### ISSUE TITLE
Pages can be renamed to invalid names

### ISSUE THREAD

**Issue by katherineqian** [FlutterFlow/flutterflow-issues#1]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.
Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

## Expected behavior

Invalid page names should be rejected so that they don't cause project build failures. At least a project error should be shown so that the user can diagnose the issue.

## Current behavior

Even though an error message is shown, invalid page names are still saved. The project will fail to build, but no project errors are shown. 

## To Reproduce

1. Create a page.
2. Double click the name of the page on the page selection panel.
3. Set the name to something invalid, e.g. 0HomePage (invalid because the name can't start with a digit).
4. Observe the error message.
5. Press enter.
6. Observe that the name is saved.
7. Click "Test".
8. Observe that project says "Build Failed". Observe that there are no project errors in the workspace. 

## Context

Users encounter build failures without any guidance on what caused the failure. It prevents users from building. 

## Screenshots

N/A

## Your environment

* Version of FlutterFlow used: N/A
* Platform (e.g. Web, MacOS Desktop): N/A
* Browser name and version: N/A
* Operating system and version (desktop or mobile): N/A

**Comment by bulgariamitko** [comment]
this is now fixed. I just tested it.

**Comment by katherineqian** [comment]
Thanks Dimitar! Closing.
