### ISSUE TITLE
Ability to write utf-8 characters in the package name

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#10]
## Expected behavior (required)
When I go to Settings - [Project Name] I should be able to write my project name in Cyrillic. To write a name of a project like - Това е пробно заглавие

## Current behavior (required)
When I go to Project name and I write something in utf-8 characters it just clears everything and then it stays blank

1. Click on Settings
2. Write something in Chinese or Cyrillic, for example - Това е пробно заглавие

## Context (required)
I would my app to appear in the Play Store and iOS in Cyrillic and not in Latin.

## Your environment

* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): Web 
* Browser name and version: Chrome 105
* Operating system and version (desktop or mobile): desctop

**Comment by katherineqian** [comment]
Closing for now as this is a feature request (adding support for UTF-8).
