### ISSUE TITLE
Can't Include Component Widget in Custom Widget

### ISSUE THREAD

**Issue by sarim** [FlutterFlow/flutterflow-issues#100]
example:

```dart
import '../../components/my_fancy_button_component_widget.dart';

.....
.....
Widget build(BuildContext context) {
    return MyFancyButtonComponentWidget();
```

## Expected behavior (required)

Compile successfully.

## Current behavior (required)

Compilation fails, it doesn't find the file.

## To Reproduce (required)

Trying to add component designed in flutterflow inside my custom widget. 
The code is correct, confirmed by checking **Exclude from compilation**. Now App runs just fine. But in design the widget doesn't show (only a placeholder) as its not compiled there.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: v3.0 October 29, 2022
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Edge 107, Chrome 107
* Operating system and version (desktop or mobile): Windows 11, Windows 10, Fedora Linux 36

**Comment by Pepino-GR** [comment]
Hi Sarim,

the placeholder is by design. You can see the result only in run mode.

**Comment by sarim** [comment]
@Pepino-GR The problem is not the placeholder, rather the failure to compile. The compilation fails and the big error in top bar, unless I check **Exclude from compilation**.

**Comment by Pepino-GR** [comment]
The today’s environment is unable to use the imported files to compile. To avoid the error, you have to exclude it for compilation.

**Comment by wenkaifan0720** [comment]
There are some updates on the custom widget (and he code editor) side so the compilation behavior may change in the future. As for now, please check "Exclude from compilation".
