### ISSUE TITLE
Datatypes do not update in document

### ISSUE THREAD

**Issue by wmacklin** [FlutterFlow/flutterflow-issues#1000]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My collection has a location field which is a datatype [string, document Reference, string]. It was passed to the page via bottom sheet action output as a datatype. The data is proven to be passed by the text being filled on the screen by the action output. I then needed to update the document with the new location data from the location datatype. I created an action to update the document. The location field was set from variable from the action output. All other fields update the document except the location action output. This also occurs using app state datatype.

### Expected Behavior

When passing the data from the action output as a datatype to update the document. The document should update since the datatypes are compatible.

### Steps to Reproduce

1.Create a page to edit data. This page can select a bottom sheet the brings back a datatype action output. The page should also have a save button that has an action to update a document. The field of concern should be a datatype (string, docRef, string).
2.Create a bottom sheet that when dismissed has a value of a created datatype
3.Set an action on the edit page save button that updates a document. update the field that is a datatype by set from variable. Set the variable from the action output.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i/LlvJd2xNta1rruccFr/TgWOUs7a40R18EbWRU8J5DaPOxzP/TBaldWUs+0dAlUO1qagmAy0/femvHTM+1daCibGbU5+rpqcjvJcGqWRpiuPLWzdW5/DeFMGUDE05+NmR1DIrRvLnxi7V+YAvOtVnbDJ4D1DGsZQs6iA5OK2SrDX1iXc2URm05KZDPz

### Context

Need to update a datatype in a document.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11440537/a622a411-27e7-41b3-843d-8cd4dde1ca3c)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11440537/42b30ec4-9586-4e72-b6b6-980d0b68b1f5)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11440537/06c6cd01-c8ca-4863-8067-196282733e7a)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @wmacklin - Thanks for submitting the issue. I looked at the project but I can't locate the issue as there are many pages and fields. For this kind of issues, we require a blank project with issue setup. Without these specific details, we do not consider issues for investigation.

However, In general I can suggest, use the data type field updates along with app states so that it gives options to update current page/all pages on field updates. I hope it can fix the issue. Try and let us know. Thanks

**Comment by wmacklin** [comment]
I found out the issue is in the adding of the datatype data on my create page. When the datatype is initially set in a document you will need to set individual fields so it gives a nested format. If you set by variable it does not create an actual datatype/nested format in the document it actually creates the data as individual fields in the document. When I go to update it does not see the datatype and therefore can not update it. I believe this may be the bug. However, this particular issue is solved. Thanks for the help.

**Comment by hariprasadms** [comment]
Thanks @wmacklin
