### ISSUE TITLE
Build fail conditional builder

### ISSUE THREAD

**Issue by Perlo34** [FlutterFlow/flutterflow-issues#1001]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There's a build error when I want to test 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/1eed066a-1f5a-423e-b9f5-30fea7e555ab)

### Expected Behavior

I want to use a conditional constructor to display 2 listViews, depending on the value of a dropdown. each is cable to add a like to the post using a toggle button.

### Steps to Reproduce

1. Create Page
2. Add a conditional builder
3. Insert 2 listView in the conditional builder and same backend querry with different filter
4. Insert dropdown outside the conditional builder
5. Insert Toggle button in each listView
6. The toggle value is LikedBy(User ref)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/f49fb6ef-8be0-43e9-b088-f064420ede6b)
7. Add an action on each toggle button to update the document with a likeCount property that be use to ordery the second listView
8. And now this error appear

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlMjf35dOpbxA+Kr9bfpV+TgXOWY1U4ZMitZxSko0fZfNGe4Iec/7VFJoTemkTFZIOlKgnnsy08rTv9ieF8cCOUysfL441L9Xdw/vcFGVVaqwEpO0VHN6M/tbfGq505i3nx1NKfNzWHgh7F+mPO7LcHTcQ+fpOldNR/2IDNzU+GyJAiLsGiNXwRUDDmreTI5ODEz25eKMrop5yfj/0w==

### Context

It's affecting me because the dropdown ordering functionality I want to do is therefore unfeasible, I'm not even sure the error comes with the toggle button because after further testing even removing them the error appears.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/fb2111af-0ca8-4329-96d3-860ce90b804f)

### Additional Info

[page Link](https://app.flutterflow.io/project/dream-i-a-analyse-aay63c?tab=widgetTree&page=Community)

### Environment

```markdown
- FlutterFlow version: 3.1 (releasejune 16 2023)
- Platform: Web
- Browser name and version: Brave 1.52.126
- Operating system and version affected:  Windows 11
```

**Comment by hariprasadms** [comment]
Hi @Perlo34 - Thanks for submitting the issue. I have looked at your project and noticed below configurations. There is one variable name _**dreamsUpdateData**_ used in both the pages  _**community**_ and **_dream analyse_** pages. 

I suggest try to use the app or page state variables to store the count values in both pages ( use one state variable for each page ) before updating the values to fire-store. 

In above given steps, step 7 is causing the issue. In both pages, you are trying to update the same references and its field count.  I am not sure your app logics so I can't comment on it. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/13d9a6fa-bbf2-4dfb-a619-61436c3f090c


https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d8646397-44b2-45fb-8a6e-d0411a7f1342

Note - For this kind of this issues, we require a blank project with issue setup. Without these specific details, we do not consider issue for investigation.

**Comment by Perlo34** [comment]
Okay thank you so i can't use 2 toggle Button with same update reference , Is that ?

**Comment by hariprasadms** [comment]
It is duplicate with #1015
