### ISSUE TITLE
Setting the Loading Indicator from Big Value to Small hangs app

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1003]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In theme settings set the Loading Indicator to Ripple From SpinKit

### Expected Behavior

Not To Hang

### Steps to Reproduce

In theme settings set the Loading Indicator to Ripple From SpinKit

Set it to a big value like 300 or 30 and then change it to 3 and the application will hang / freeze

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhefqwItIn7wG15SIY+xWgmU4C1McTL4zlO1HcxAYGO/yPbJ+Ovf7TEhVOP3hTGlhHGeIjkwJ/vzeiuPEG/VfBzeZGIBMws0MWzvLQXq8SqaNC8yRP0cnJ+xUfGag1p6WkxJQVdJZSi0i7zuEJueRQi3AN5+/Zwh9f6PHaOI=

### Context

No issues, just reporting builder bug

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/d2d1e970-c8f3-42c6-89dc-8dfc9acaf872)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
It works fine for me. You you try to open the project in Incognito mode and see if you still have the same issue?
