### ISSUE TITLE
Using query caching leads infinite loader

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#1004]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a Post collection with fields: image: ImagePath, description: String, created_by: User Collection Reference, likes: list of Users reference and some other fields. User Collection stores user data. I have made a component for Post which is used in listview to show all posts. To show creator details of each post I query user on each post component and pass it along with post document as parameter to the post component. I have enabled query caching user record since it was loading every time on scrolling list. The issue is that when I load the page with listveiw, most of the times, instead of first and second post I see a loader that keeps loading infinitely. But if the list is scrolled down and then up again the list loads normally.

### Expected Behavior

The user record should be queried and cached normally hence showing list which any loaders.

### Steps to Reproduce

1) Create a component with document as param(atleast its so in my case).
2) Create a listview and use the component there.
3) Query user(or any doc used in the component) on that component. Enable query caching for this query.
4) Run and see that infinite loader appears in place of first(and sometimes second) component. If scolled up and down the list loads normally without any loader.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l/HLuMlOxLhc+KqNdcdKqCYWHHk7aIJIjdZTY008J5DaPOxzP/TBaldWUs+0YGxXPmG0jj4xpvfemvLhDvY4KSeBG6E5zaVpFgLKUk2uRbbUDc+sem5/DZtWGlyz4LujhgpCWdhaV1IG7V6qIe7KVnftGZjWNW0dJPKYE5KK2SrDX1iXc2URm05KZDPz

### Context

The first, and sometimes also the second, posts items do not load but show the loader infinitely. Show a normal list of post with query caching the user document used to show user details in it.

### Visual documentation

User query and query caching used on "created_by" filed.
<img width="1440" alt="Screenshot 2023-06-19 at 8 40 54 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102008213/308386e9-0ba1-4ccd-8132-7c568b707c96">
Issue:
<img width="878" alt="image_2023_06_14T11_24_05_447Z" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102008213/f8884dcb-5c19-4998-8e31-bb23a2aed842">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: All
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @Shubham-VE - Thanks for posting the issue. I looked at the project. Project is not a blank project with issue setup details. However, I managed to find the page and component - _**postSearch and post(component)**_ but I can't see the query configurations as explained in the steps.  

I have tested the above steps in my test project with query caching configuration. I can confirm that, it is working as expected. 

If you are still facing the issue, can you please share below details,

1. Blank project with issue setup 
2. If any errors showing in the browser console.
3. A quick video of showing the issues and query configuration details. 
4. Run mode link 

Thanks

**Comment by eujoseant** [comment]
I am facing the same problem reported by you.

https://github.com/FlutterFlow/flutterflow-issues/issues/1692
