### ISSUE TITLE
Can have different Email Auth Actions on one project

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#1006]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I found a very strange bug!
1. I create a second page (in addition to the existing one) for user registration
2. on the button I add action - Auth Email
3. add additional fields
4. On the main registration page I get errors that the newly added fields are not filled.

thus - it turns out that there can be only ONE Action Auth Email for the whole project. In my opinion this is a mistake.

I want to create an interface where the admin can add users himself and add different fields to them during registration. At the moment this is not possible.

### Expected Behavior

А project should have any number of actions for authorization.

### Steps to Reproduce

1. create 1st auth page
2. add email auth action
3. create second page auth page
2. add email auth action
4. add additional fields to the 2nd auth action
5. On the 1st auth page you will get errors that the newly added fields are not filled (but they should never be there is the first place!)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis9f5CvOpYUec/6P1ZvOdfnY1VhfVq2p14KpsLWkuPLFMEpAASCb718yqVQYQzLTlmjbJeTF7W0PHEnDZ1MGE+O0p6zghFBIuNoWUYh3GaUBtmATXXANIT0DFQwSq/LZO4=

### Context

I want to create an interface where the admin can add users himself and add different fields to them during registration. At the moment this is not possible.

### Visual documentation

<img width="1190" alt="Screenshot 2023-06-19 at 11 16 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/b3b98864-ff33-46ed-b42d-e9c505d68503">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS
- Browser name and version: Chrome 114.0.5735.90
- Operating system and version affected: MacOS 13.4 (22F66)
```

**Comment by hariprasadms** [comment]
Hi @khomya - I presume, you are trying to add register/login features to handle users and admin login. Correct me if I am wrong. 

Technically speaking, your approach is incorrect because an app should only have one entry point. Thats the reason you can see those warning errors. By including role flag fields in user collections, you can handle this. You can add conditional checks to these role fields to route users to a set of pages according to the roles they have defined in the user collection. 

I hope this suggestion helps for your. Thanks
