### ISSUE TITLE
Cannot use "Has field" on Data Types.

### ISSUE THREAD

**Issue by evaqum** [FlutterFlow/flutterflow-issues#1007]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, trying to use "Has field" option on any Data Type basically anywhere yields "Current variable is not valid" and does not allow to use it.

### Expected Behavior

"Has field" option on Data Types can be used.

### Steps to Reproduce

1. Create a Data Type with at least one field
2. Create a page/component
3. Make that Data Type variable accessible on your page/component (for components, you could add a parameter with that Data Type, otherwise you can make a local state variable)
4. Try to use "Has Field" option of that Data Type on any of the fields. It can be a condition or value of a Text widget, for example.
5. "Current variable is not valid" 😐

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESiMjfsI5grsNZ1aqAKMdQhR4jNlx7bZNEk+pEaxEYC4PkO7YpWvrSamBoZ9ehdFFmelD8gmoD/trLjYSWNvZcBAyHY65gypFQSTrJeHGmRJS1PruaeXBPPJlWJ2KE3JmzphImA7J0S1lpig/GSw==

### Context

This bug came with one of the updates like two days ago and stuttered my work on project cause errors popped up everywhere where I used "Has field" option. Bruh

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/54950997/77206595-df4b-4da3-802d-d0cebd0dda9c

### Environment

```markdown
- FlutterFlow version: v3.1 (released Jun 16, 2023)
- Platform: Web
- Browser name and version: Chrome 114.0.5735.134
- Operating system and version affected: Windows 10 19045.2075
```

**Comment by hariprasadms** [comment]
Hi @evaqum - Thanks for submitting the issue. I can re produce the issue. Thanks

**Comment by evaqum** [comment]
@hariprasadms thanks for confirming! Any idea on when I should expect fix to roll out?

**Comment by evaqum** [comment]
Yeah, I've already made some custom functions for that. It's messy and can be prone to accidential typos, but gets the job done. Hoping for a quick fix!

**Comment by vishalagarwal2** [comment]
Hi, the bug has been fixed and will be applied in our next deploy!

**Comment by jasminder** [comment]
We are not able to use "Apply Opposite Statement" on Has field property. Why is that?

> Hi, the bug has been fixed and will be applied in our next deploy!
