### ISSUE TITLE
Revenue cat field "Price String" is not working

### ISSUE THREAD

**Issue by coffeelydev** [FlutterFlow/flutterflow-issues#1009]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created 2 plans in Revenue Cat with Android (Google Play): monthly and annual
When the user opens a paywall with this 2 plans, 2 issues are happening: 
1- Price String of the both plan is null and show an error
2- Annual Package is not working, so when the users click to purchase it, nothing happens.
I think everything in Revenue Cat and Google Play is correct!

### Expected Behavior

1. When the users open paywall, price string should be shown
2. When the users click on annual plan, google plan should be openned.

### Steps to Reproduce

1. Create 2 plans in Google Play (monthly and annual)
2. Create all the things in Revenue Cat account
3. Make the integration with FlutterFlow
4. Create a paywall page and show both plans with Price String
5. Test it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcmA05J2odtD0a6JdO9VlmI4Ijt/RJIr0e1+Uis9f5ToPJYQe8/6P1doTum9YGxLfGe2p14Jw6nPvuHqUfYEPTarfJxAybl5Eg3NWkyjaJeTF7iKTmhPM5hRJ2Ks16SZhSZDKrB2L04awGaQHN7KHx3AH5z0DHo8Sq/LZO4=

### Context

I am trying to deploy subscription plans to my users

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/4e4656b7-c506-4469-a1c5-04612c63faee)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/ca151778-1733-4066-883f-8b855f3340cc)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/9ed20982-70ab-4425-a351-6f8ad5fa4541)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/190ab00f-67bb-4375-bab9-972f18a9d5fd)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/90800dc1-53b0-43f3-9ef9-60756a723d50)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/2057b244-4d3c-4295-880d-77f6fae0cfb7)

### Additional Info

You can test it in my app https://app.flutterflow.io/project/coffeely-f-fv1-t0ewmk
Just create an way to navigate to the "PaywallPageV1" page

### Environment

```markdown
- FlutterFlow version: v3.1 (released June 15, 2023)
- Platform: android
- Browser name and version: na
- Operating system and version affected: na
```

**Comment by MoonstoneApp** [comment]
I am also having this issue. Have you been able to resolve this?

**Comment by coffeelydev** [comment]
No. I am waiting FlutterFlow fix it. :(

Em sex., 23 de jun. de 2023 06:01, MoonstoneApp ***@***.***>
escreveu:

**Comment by coffeelydev** [comment]
Hi! This is a very critical issue. I can't sell subscriptions in my app!! When will you fix it, @bulgariamitko ?

**Comment by bulgariamitko** [comment]
@coffeelydev 
The FF team should review and address this issue promptly. Please note that I do not work for FF. My role is limited to confirming the presence of the reported issue. Thank you.

**Comment by coffeelydev** [comment]
Thanks @bulgariamitko . I hope that it can be fix it quickly by FF team! I can't monetize my app until this be fixed. :(

**Comment by aemelyanovff** [comment]
@coffeelydev Thanks for reporting the issue.

I'm unable to reproduce the issue - "price string" works fine in my projects. How are you running the app (building locally with Android Studio/VSCode? CodeMagic?) Can you share the log?

Configs on your screenshots look right. The most likely reason it doesn't work I think is a mismatch between your configs in RevenueCat and PlayStore.

**Comment by coffeelydev** [comment]
Hi @aemelyanovff ! Thanks for your help. I am running the app downloading apk file and using "run mode" in FF.
One question: do I have to configure something about meta data in RevenueCat (https://www.revenuecat.com/docs/offering-metadata)?

**Comment by coffeelydev** [comment]
This is the error: 
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/18d5ff1a-81f2-4b4d-9b95-2e455fd24229">
When I remove "price string" of the page, this error is not shown.

**Comment by coffeelydev** [comment]
Yeah, subscriptions are okay in RevenueCat...

<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/a08488f5-bf57-4a7c-b8d8-9e863139b6d0">
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/c7574906-2658-4185-828f-2e827f8d8ac5">

**Comment by aemelyanovff** [comment]
@coffeelydev Thanks for the info.

We don't support RevenueCat on web, so it won't work in Run Mode. The error on the screenshot does not look like it has anything to do with RevenueCat.

By log I mean the application execution log on your device. Not sure how to obtain it if you are running downloaded APKs (would be much easier if you built in in Android Studio/VSCode), but perhaps [this can work](https://stackoverflow.com/questions/58693539/how-to-see-debug-console-when-app-installed-through-apk-in-flutter).

Note: we are upgrading the RevenueCat package (`purchases_flutter`) to the latest version in the next update, it's very possible it'll fix your errors.

**Comment by coffeelydev** [comment]
I understood it. I ran downloaded APK and the grey screen is shown. And then I just remove the price string text from the page, everything works. That is why I thing this field is the issue. Let me know when you update to the latest version, please. In meanwhile I will build in VSCode to get more error infos. Thanks.

**Comment by bulgariamitko** [comment]
@coffeelydev if you want to use subscriptions for the web I will recommend you to use Stripe instead. Here is a video explaining how you can do that 

https://www.youtube.com/watch?v=_2KJuCccuhg&t=1152s

**Comment by coffeelydev** [comment]
Hi @bulgariamitko ! Thanks but I don't want to use subscription for the web now. I just want to use RevenueCat for mobile subscriptions successfully. :/

**Comment by bulgariamitko** [comment]
@coffeelydev , you need to test it then on a mobile device and not on the web.

**Comment by afeezaziz** [comment]
I am facing the same problem as @coffeelydev and I am testing it on the mobile only. When it has anything to do with revenuecat, the page will turn to grey.

**Comment by afeezaziz** [comment]
I am setting it to be SDK V6+ and backwards compatible but it still does not work. I am also testing on iOS, which does not work either way.

**Comment by afeezaziz** [comment]
Integration between revenuecat and app stores works because I was able to use REST SDK.
<img width="844" alt="Screenshot 2023-07-13 at 8 41 00 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/677026/1be408e3-6061-4aa9-a42f-003f8b21d082">

**Comment by aemelyanovff** [comment]
We upgraded `purchases_flutter` to the latest version in the last update, I hope this helps.

**Comment by MoonstoneApp** [comment]
Did this all work in the end? @coffeelydev

**Comment by coffeelydev** [comment]
Yes @MoonstoneApp . But just the case "SDK V6+ and backwards compatible".

**Comment by coffeelydev** [comment]
I am trying to deploy on iOS without success... Same error as reported here before.
<img width="959" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/22a42cc9-04ff-431d-9efb-6ce04f542c94">
<img width="959" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/f31285c5-de1e-45f8-8d4c-32eff40fa2ae">
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/9199c8a6-b2be-4a1c-b3f4-75e61892e521">
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/883db6c6-42fb-442e-8966-a32d685ebc93">


I already read again the Flutter Flow and RevenueCat docs and I didn't find anything wrong in my configs... :(
In RevenueCat I used the "import product" button, so it is not a bug with RevenueCat itself...
Any clue what is wrong?

**Comment by coffeelydev** [comment]
Another thing, when I use the rest API from RevenueCat (https://www.revenuecat.com/reference/get-products-from-package) iOS and android offers are shown correctly. But in FlutterFlow platform just android is working. I also re-confirm if API keys were right and it is correct! 

<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/04b816d5-4a02-4d3d-a307-98a01e1061b0">
<img width="958" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/ac96cc2f-634a-44e1-aa0b-0f79b7322902">
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/95e93f47-2347-484d-8f4b-54a698843466">
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/cf4d95e7-03e3-45a0-9a8e-afc2020986d5">

**Comment by nathanwright17** [comment]
Same issue here after iOS App Review flagged the bug on my submission - with a gray screen of death showing when they tried to access the paywall on iPad. I ended up having to hard code the text prices with USD indicator because I couldn't fix it. It seem it might be a slow connection issue between the parties? As I was only able to reproduce when accessing the paywall page quickly from app open, and it was occurring most on iPad (was using the latest iPad Pro 12.9inch) especially when using mobile hotspot.

I tried the pre-load option for Revenue Cat that Flutterflow has, but it took way too long for the app to open - always over 5 secs, sometimes even over 10 secs! And no pre splash or loading indicator, just a blank screen for that long before you even get to your splash image. So it wasn't an option.

Also having an issue with Revenue Cat subscription purchases taking a long time, over 8 secs, and another 5 sec delay after purchase confirmation. I've put in a message that pops up on purchase to let the user know it will take a while - hopefully it's enough to pass App Review since I can't do anything otherwise. They initially rejected it because they assumed it was a bug and that the loading indicator would be spinning indefinitely.

**Comment by bhagwat-rahul** [comment]
It is happening as you can only fetch properties of the 'current offering' via FlutterFlow's RevenueCat api. If you have multiple offerings or haven't selected a default you won't be able to fetch.
To fix they probably need to add support for fetching offerings by offering id instead of assuming there will only be one offering you may want to fetch.

**Comment by coffeelydev** [comment]
Thanks @bhagwat-rahul ! I really think that FlutterFlow could prioritize RevenueCat for iOS. Fix the issues and make a video on YouTube with the how to.

**Comment by sertacakdogan** [comment]
> Thanks @bhagwat-rahul ! I really think that FlutterFlow could prioritize RevenueCat for iOS. Fix the issues and make a video on YouTube with the how to.

Could you share the Youtube video link. I'm encountering same issues.
