### ISSUE TITLE
Theme Text Style drop down list is empty

### ISSUE THREAD

**Issue by wednesdei** [FlutterFlow/flutterflow-issues#101]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I expect there to be options in the drop-down list.

## Current behavior (required)

The drop-down list is empty.

## To Reproduce (required)

1. Add text control to page
2. Try to change theme style of text using drop down menu

## Context (required)

Its annoying because I've setup the text styles in the admin panel, but I can't select them from the drop-down list. 

## Screenshots / recordings

<img width="211" alt="Screenshot 2022-11-06 132741" src="https://user-images.githubusercontent.com/44120439/200193451-f8bb3492-ce43-461c-9a4d-d61a789d4ee7.png">

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: Latest
* Platform (e.g. Web, MacOS Desktop): Building on web
* Browser name and version: Chrome latest
* Operating system and version (desktop or mobile): Windows 11 latest

**Comment by hariprasadms** [comment]
Hi @wednesdei, I can test it and see it is working fine for me in all projects. Can you try in Chrome Incognito mode and see how it goes. 

![image](https://user-images.githubusercontent.com/17435678/200194149-4e8729ce-666c-47a5-8016-55282ccd4b49.png)

**Comment by wednesdei** [comment]
My apologies, it looks like this was a user error on my part. When I had created my color scheme, I set some of the default values to transparent, which is why nothing was visible. I'll close this out, sorry for the mistake on my part.
