### ISSUE TITLE
Test Mode does not work, Run Mode is OK

### ISSUE THREAD

**Issue by jesperst67** [FlutterFlow/flutterflow-issues#1010]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When clicking on Test Mode, the blue loading bar keeps going on while the console comes up with loads of errors. First line of error is "https://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1687206024/dart_sdk.js Failed to load"

I tried with Google Chrome, Firefox and Edge. Restarted the computer, cleared the cookies, nothing seems to help.

Run mode works fine, Test mode gets stuck and app never loads.

I tried more apps that I have saved previously and none of them work in Test Mode.

### Expected Behavior

Test mode to work

### Steps to Reproduce

Create any app, click Test Mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wzMmBw5RPvsdc1871bfpammAUMjs9aI07l9V+Sis8GZT0B4kcYs+kfklUOcO6d1ZqJWeWqz8X/MmMjYTqUcYFOUmVbL5gz6pQZDnyIWWnbq6gDoS3b3ZTEfFmIFCH4KWCkQlDIsR0WGBmwzuhetzIfHPrJLH4CkgFI+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

I cannot test any of my applications, I need to use Run Mode but that is way too slow to test.

### Visual documentation

![2023-06-20 00_28_17-Test Mode - wordpress-auth](https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/465eca8f-077f-4844-8718-a7ff1f5d8faa)
![2023-06-20 00_33_59-](https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/b238f195-51c1-473e-b6a8-ae96a06f8844)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 114.0.5735.134 (Official Build) (64-bit)
- Operating system and version affected: All
```

**Comment by byrondowns** [comment]
I had this issue earlier but now works fine

**Comment by agreaves** [comment]
Hi, thank you for the bug report and apologies for the outage. I can confirm this is indeed fixed now.
