### ISSUE TITLE
Stripe causing build errors on test mode

### ISSUE THREAD

**Issue by DeltaForce007** [FlutterFlow/flutterflow-issues#1011]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I build an app to test mode, I get the following build error:

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/home/.pub-cache/hosted/pub.dev/flutter_stripe_web-4.0.1/lib/src/widgets/payment_element.dart:146:3: Error: Type 'js.ElementsCreateOptions' not found.
  js.ElementsCreateOptions createOptions() {
  ^^^^^^^^^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/flutter_stripe_web-4.0.1/lib/src/widgets/payment_element.dart:147:27: Error: Method not found: 'ElementAppareance'.
    final appearance = js.ElementAppareance(theme: js.ElementTheme.night);
                          ^^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/flutter_stripe_web-4.0.1/lib/src/widgets/payment_element.dart:148:15: Error: Method not found: 'ElementsCreateOptions'.
    return js.ElementsCreateOptions(
              ^^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         61.3s
Failed to compile application.

### Expected Behavior

That once I build the project it runs and I can continue testing

### Steps to Reproduce

1. Add stripe to project
2. Add stripe action to button
3. Run project in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHl8ZFOxd9c0b6JYfoxpDsWQmEcTeU30+thcw4bI+KsO4kIe/SkYhJvSOqHdHxiIVqgpD4Gpdb5ieD1DcBfIRyCQNU5+LtpUxDjRlu5eLGaEc3gdnJAI8dUfkiZ08OzuBQnFNdiS3wh702yNu6Ab3qCf9qOYwx5e6fDbOY=

### Context

I am trying to test my application but can't build it to continue which has halted its progress. 

### Visual documentation

<img width="608" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/31f92500-4096-4408-b129-cb3940076742">

### Environment

```markdown
- FlutterFlow version: v 3.1
- Platform: Web browser FLutterFlow (Chrome)
- Browser name and version: Chrome Version 112.0.5615.137
```

**Comment by hariprasadms** [comment]
Hi @DeltaForce007 - Thanks for reporting the issue. I can re-produce the issue. Thanks

**Comment by Rafa831** [comment]
The same here..

**Comment by Hello-Palmspire** [comment]
We are facing the same issue

**Comment by RobinopdeBeek** [comment]
Jep same issue same issue here

**Comment by caseyharlin** [comment]
> Hi @hariprasadms I am also getting this error. how we can fixed it. we are about to release our build.

FYI should it be helpful while they resolve the bug. I was able to run test mode by manually adding all flutter_stripe dependencies to my custom widget. I'm not an eng so there may be a better/more efficient work around but at least I can continue to build/test. 

![Screenshot 2023-06-20 at 4 34 59 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/106691257/1231b053-ab14-4e20-a0ff-cbc7de17976f)

**Comment by mdrashedbinkuddus** [comment]
Same problem here

**Comment by victoriahuang1** [comment]
Hi all, thanks for the report. We are aware of the problem, and the fix should be deployed on Thursday. Sorry for the inconvenience

**Comment by KlausGrosser** [comment]
This is still happening for me, I was able to run normally my project but suddenly Im getting this error without doing any changes.

**Comment by victoriahuang1** [comment]
Hi @KlausGrosser , thanks for the report. The bug in this issue has been resolved. The issue you are experiencing is separate from this, so it would be great if you could open a new Github issue with all of the needed info to debug your project.

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!
