### ISSUE TITLE
Unable to use JWT token from Google Login from Flutter Flow

### ISSUE THREAD

**Issue by Hkaran** [FlutterFlow/flutterflow-issues#1012]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tried testing the JWT token that was given by flutter flow with the URLs "https://oauth2.googleapis.com/tokeninfo?id_token=" and "https://www.googleapis.com/oauth2/v1/userinfo?access_token=" but both show invalid token as a response. 

### Expected Behavior

The JWT token from Google Login to return the JSON of the user details when tested with the URLs "https://oauth2.googleapis.com/tokeninfo?id_token=", "https://www.googleapis.com/oauth2/v1/userinfo?access_token=" or any other URL that can be used to get user info. 

### Steps to Reproduce

1. Create a login which uses Google 
2. Create a way to copy the JWT Token generated by the Google login. (Example: Create a button that copies the content of the JWT Token)
4. Test the JWT Token with google oauth URLs "https://oauth2.googleapis.com/tokeninfo?id_token=" and "https://www.googleapis.com/oauth2/v1/userinfo?access_token="

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48zMrl25N1m9tb+Kryb8EwuCAXHGk7U+ck1tYbURI8J5zKB+wAYvf7P1FWTLymYGw/fU2Zkn407Pfqkc7DKew5GwSBfpx/1apiZzuWfFKQM5jRO6idfW1fGptWC0Cs0piN3RJSKtBicVo1wzu6N+uRczDrNrrrOEcRR/qbKdeK2SrDX1iXc2URm05KZDPz

### Context

I am unable to use the JWT Token generated from Flutter Flow for google login verification in backend API. Currently there is a different method that is being implemented to check the JWT Token but will like to use Google token verification due to the current method is not as secure. Would like to use JWT Token from google login from Flutter Flow for google token verification. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/49593079/1c7405f6-2ef9-4bdb-af89-91baa55729d6)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, Android
- Browser name and version: Chrome 114.0.5735.134
- Operating system and version affected: Windows 10 19045.3086
```

**Comment by hariprasadms** [comment]
Hi @Hkaran - Thanks for reporting the issue. I am not sure why you are trying to use generated JWT token outside the app. What happens if you try to use the generated JWT token with in project? Please add more details.

**Comment by Hkaran** [comment]
> Hi @Hkaran - Thanks for reporting the issue. I am not sure why you are trying to use generated JWT token outside the app. What happens if you try to use the generated JWT token with in project? Please add more details.

Hi, I need the JWT token to verify the user when calling the API. I am not so sure what you mean by using the JWT token with in the project.

**Comment by Hkaran** [comment]
Any updates?

**Comment by Hkaran** [comment]
Hi @sbis04 and @hariprasadms, it has been 3 weeks. May I know the progress?

**Comment by sbis04** [comment]
Hi @Hkaran, I had looked into this and was able to reproduce it too. But this bug is not related to FlutterFlow, rather seems like a bug in the [Google Sign In package](https://pub.dev/packages/google_sign_in).

One piece of information that I can share -- the JWT token that we surface inside the Authenticated User is an `ID token` so this should be the correct URL to verify it `https://oauth2.googleapis.com/tokeninfo?id_token=`. But I know it still returns `invalid_token` for some reason and unfortunately we can't do anything about that at the moment as the bug is not on our end. So, I'll close this issue for now.

**Comment by Hkaran** [comment]
Thank you for checking. I'm disappointed with the extended delay in receiving a response. Wish you would have updated me on this not after a month of me posting the issue and asking about it multiple times.

**Comment by chanakya-reddy** [comment]
@Hkaran  Did you find any alternative other than replicating the entire signin process explicitly?

@sbis04  Does it mean that the ID token available after google sign-in in Flutterflow works only for Firebase calls and not for external calls?

**Comment by rogerthedeveloper** [comment]
I have the exact same issue, if I use the jwtToken that comes from the 'Authenticated User' component it fails to verify, but jwt created from backend works for login and then the resultant value id Token (JWT Token) cant be used to request more from backend
