### ISSUE TITLE
"Refresh" button in Pubspec dependencies / customAction is not including package

### ISSUE THREAD

**Issue by coffeelydev** [FlutterFlow/flutterflow-issues#1013]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to create a custom function to log events to amplitude without success.

### Expected Behavior

I was expecting to add "amplitude_flutter: ^3.15.0" in dependencies field, click on refresh and the package would be imported.

### Steps to Reproduce

1. Create a new action Action
2. Include "amplitude_flutter: ^3.15.0" in dependencies
3. Click on "refresh"
4. Nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

There is no bug report code in this part of the platform

### Context

I cannot compile my code.

### Visual documentation

<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/62ee3f62-7ab4-4703-9604-bcd6735d994b">

### Additional Info

And one more suggestion: I would like to save my action Function even though there are still errors in the code. ;)

### Environment

```markdown
- FlutterFlow version: v3.1 (released Jun 15, 2023)
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: windows 10
```

**Comment by hariprasadms** [comment]
Hi @coffeelydev - Thanks for reporting the issue. Is this happening already? I had noticed this before, but it is not a bug. It typically happens when there is a network delay.  I'd recommend clicking the button several times, as well as switching pages and returning to click the button. These steps will be useful if it happens again. Thanks

**Comment by coffeelydev** [comment]
Nothing happens @hariprasadms . I tried a lot of times. No message, nothing happens. Or it is a bug or the system should be return a error message with the cause.

**Comment by hariprasadms** [comment]
Can you please add project bug report code?

Meanwhile, make sure you have the below tick mark in your project's custom code editor. If you notice a crossed cloud icon, this indicates that the code analyser is not connected. The pubspec dependencies cannot be downloaded. Try again after switching pages. Thanks

<img width="968" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/f1b964df-8e31-410b-8f24-a009453039c8">

See below. The same package you are trying download, its been downloaded and no error at import lines. 

<img width="1508" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/0a4e7389-f768-465a-a478-3f9fd3bf4658">

**Comment by coffeelydev** [comment]
<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/c02407bf-d929-4105-a383-c2de33bcee84">
Maybe something in my project... I tried to add other dependencie (firebase_auth: ^4.6.3) and happened the same issue.

**Comment by coffeelydev** [comment]
Hi guys! I still facing with this error... I can't include any pubspec dependency in custom Action in my project https://app.flutterflow.io/project/coffeely-f-fv1-t0ewmk. It is not appearing any error but the dependency "amplitude_flutter: ^3.15.0" is not included.  I don't know what I have to do to work it...

**Comment by wenkaifan0720** [comment]
Hi @coffeelydev. Sorry for the late reply. I just looked into your project and seems like the package is now included, right?

**Comment by coffeelydev** [comment]
Yes @wenkaifan0720 . That is right. Thanks.

**Comment by prabhatsingh1** [comment]
hey @coffeelydev did you know what was the error mine mixpanel_flutter: ^2.1.1 package is not showing any error and also not working and not showing in pubspec.yaml file and it is for analytics so It needs to added to main.dart file but at the end it cause test screen to stuck at load screen forever. Please tell me some solution

**Comment by Aditya-Khambampati81** [comment]
This is happening for me as well ... no error ... same as example provided in flutterflow to calculate geohash from location ...trying to add custom action doesn't detect geohash even though added package name there..
