### ISSUE TITLE
PageView current index isnt updating

### ISSUE THREAD

**Issue by Thesergiolg99** [FlutterFlow/flutterflow-issues#1014]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a pageview and adding in each page a text with the current pageview index, it always remains 0

### Expected Behavior

It should update on each swipe on pages. (0...1...2...3...etc)

### Steps to Reproduce

1)create a blank project
2) Create a pageview with some pages
3) Add a text on each page and show the "current page index"
4)Run the app and you will see it remains on 0 always

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KrMLfpaliE7M0MdXJI7jNV/ewgjF774PJkDds+lSFZVXsSzaH5UOVe0pGEKzMr3ud/tNPZdFzqWG5hCz6ttFhPPbFiXVY+aDZGWdX9PEfhWfUiB0p6NgRIlAOxuc1Zh3GauDNiRQT6Cf9qOYwx5e6fDbOY=

### Context

To generate children and update each document on an specific index.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/89f2fd06-7877-41d7-805c-c111c7defcff)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/58400ab5-154e-4230-a6fc-9520330aeb42)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/33488c15-e84c-4f90-847c-9e80472316d4)

As you can see, each page shows a 0 always instead of the page index

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: WEB
- Browser name and version: CHROME (Brave) v1.52.126
- Operating system and version affected: WINDOWS 11
```

**Comment by hariprasadms** [comment]
Hi @Thesergiolg99 - Thanks for submitting the issue. I have tested the issue and I can confirm that it is working as expected. To make it work you should use **_on page swipe_** action and page or app state variables combination. See below example. Thanks 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/dc3d880a-0bf3-477b-be5b-a206dfb11e98
