### ISSUE TITLE
2 toggle button on same page

### ISSUE THREAD

**Issue by Perlo34** [FlutterFlow/flutterflow-issues#1015]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There are 2 toggle icon on my page modifying the same referent but 2 different fields, but this produces a build error because the 2 use the same variable name. 

### Expected Behavior

the 2 toggle icons should use different variable names

### Steps to Reproduce

1. Create page
2. Add 2 toggle button
3. Use same reference firestore 
4. update 2 different fields in the referecence
5. RUN

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlMjf35dOpbxA+Kr9bfpV+TgXOWY1U4ZMitZxSko0fZfNG+8UefekYlFWX+m4TAk7L0yGoGQxw+CNkfPEA+UpFzCcfoQ4zJd2YRXLfGCgbqqrO6W8eHNPJ+9JJVyG557R2iVQGNRfL3Aa1E2EOfO8dDfrGbLUOFQ8QuajNrnJpHeqQ0SLb3kNh1JWeC/v

### Context

I'm trying to have a favorites feature and a like feature on the same page with 2 toggle icons 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/6b60f7c1-4c41-42af-b577-5f636ed0b84f)

### Additional Info

I will try other solution now so in my project the error is no longer the error

### Environment

```markdown
- FlutterFlow version: 3.1 16 june 2023
- Platform: Web
- Browser name and version: Brave 1.52.1
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @Perlo34. I can't find the second toggle button with the bug report you provided. If you could try to reproduce this issue from a blank project, we can identify the issue much quicker. Thank you.
