### ISSUE TITLE
SupaBase Auth ignores "Navigate To" follow on actions.

### ISSUE THREAD

**Issue by EnacheB** [FlutterFlow/flutterflow-issues#1016]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Logging in with Supabase redirects you to the "Entry Page" (Instead of the Logged In Page, or better yet the "Navigate To" page)/

### Expected Behavior

Logging in with Supabase either redirects you to the "Logged In" page, or ideally the page navigated to by the follow-on action.

### Steps to Reproduce

1. Create a Landing Page, Sign Up Page, and a Home Page.
2. In the "App Details" settings page, set the landing page to the landing page, and logged in page to the home page. 
3. Enable Deep Linking, keep other linking-options off (not sure if this is necessary)
4. Configure Supabase
5. On your sign up page, have an button with the Supabase Create Account action.

Do a test run, you land on your landing page. Click the link on your landing page to go to your sign up page. Try to sign up. Get redirected to your landing page. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThvLlvI12rsQB+KrMcflojj0RCUMfWLsr0utuGA0hfIvkEO0iZczsSFpLYtfiTApUBFmJ+X0DwtWNidniG/AoOk6VQLpx+K5XQQLgcFKVMp+bDM2VdXJ6I95VGlSA4bSz2hZCGNduS14h112UB/CdG3qCf9qOYwx5e6fDbOY=

### Context

Users get confused when they get redirected to a feature-less landing page after signing up. After signing up or logging in I would like them to be redirected to the signed in page. 

### Visual documentation

[Screencast from 20-06-23 07:26:53 PM IST.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/8452085/fa9034b2-afd5-4d9c-a40a-25a84ac1c776)

### Additional Info

This happens with both log in actions and sign up actions. With and without a follow up navigate action
![Screenshot from 2023-06-20 19-35-32](https://github.com/FlutterFlow/flutterflow-issues/assets/8452085/8ee6d759-b1f2-4721-b897-87882f2d1ffb)

I have "Confirm Email" disabled in Supabase, but I recall "Confirm Email" being broken when I tried using it, it may be related.

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web / Test Mode
- Browser name and version: Chrome Version 113.0.5672.126 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu Linux but like that shouldn't matter
```

**Comment by bulgariamitko** [comment]
@EnacheB , what will happen if you remove the navigation action and try again without it?

**Comment by EnacheB** [comment]
Yeah, I was able to reproduce it. Bug link: ITFfhvHl249Pm9ta0L6JdsZVmSoWHD4cTeU30+thcw4bI+LmE4kqf+PSSxBBWOqHe3xcGFb9inofwd7XvfOSMMI7Ay2eR65z1rtpUxDgRmWjRYiqEpasSGh7BcdgIUiH58CzgiMlKvBtWVEt7GaEGe+Ab3qCf9qOYwx5e6fDbOY= 

No idea how you guys use that. Anyway, I forgot that I also enabled web publishing, the bug doesn't appear without it enabled. I also set the "Logged In" page to require authentication

**Comment by jellederijke** [comment]
I experience this exact issue on the webversion of my app. Thought I was going crazy, but now starting to believe it might be a bug ^^. 

Anything I can do help debug this?

**Comment by Xarjik** [comment]
I'm running into this same issue, has anybody figured out a workaround yet?

**Comment by jesperst67** [comment]
> I'm running into this same issue, and looks like it's still being worked on. Has anybody figured out a workaround for the time being?

Well, not really a workaround but as I had the same issue, I had to come up with something (as it's not been resolved for about a month now). I am a Pro subscriber so I can add unlimited API calls and I simply started following Supabase's documentation for auth API calls. Works like a charm. Takes about 1-2 hours to set it up and makes things more difficult, but to be honest I learned a lot by having to figure out how to properly authenticate users by using API calls. I know this is not a great answer, just wanted to say, that until the built-in auth issues get resolved, you can try doing the auth process manually

**Comment by jellederijke** [comment]
So did you just use these endpoints: https://github.com/supabase/gotrue#endpoints ?

**Comment by jesperst67** [comment]
> So did you just use these endpoints: https://github.com/supabase/gotrue#endpoints ?

I did not use the gotrue docs, just went by the API Docs in my dashboard 
![supa01](https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/8e92f368-6936-477d-8657-e4cd91c14a9d)
![supa02](https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/939c8171-1a18-49e0-ad7e-8591d67c7616)

**Comment by jellederijke** [comment]
awesome, thanks Jespert!

**Comment by Leonardo-Dal-Piva** [comment]
Same problem happening here, i put a loop on the login page that verifies if the user is logged in then redirect it, hope whe got a fix soon.

**Comment by vishalagarwal2** [comment]
Hi, thank you for reporting this! The issue has been fixed and will be applied in our next deploy!

**Comment by sgwozdz** [comment]
@vishalagarwal2 was it released? I face a similar issue right now. Whenever I enable email confirmation on supabase side redirection stops working. No matter if I have navigation done explicitly via action flow or through Settings -> Authentication -> Logged In Page.
