### ISSUE TITLE
App Crash Report

### ISSUE THREAD

**Issue by techpisat** [FlutterFlow/flutterflow-issues#1017]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Firebase crash analysis providing regular mail for app crash.

<img width="1252" alt="Screenshot 2023-06-20 at 7 50 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/97112013/d112064d-cf7e-4ea2-adde-8d20980e0c0b">

<img width="1252" alt="Screenshot 2023-06-20 at 7 51 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/97112013/aabcf7a5-abb3-4663-b66b-6a3b82870b73">

<img width="1252" alt="Screenshot 2023-06-20 at 7 51 43 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/97112013/e4f66cf3-55cf-4acd-8edd-92741dd99cc9">

<img width="1252" alt="Screenshot 2023-06-20 at 7 52 12 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/97112013/3c712f92-acb4-4915-a080-4370fb38bdbf">

### Expected Behavior

Apps uploaded few months earlier performing well. But apps releasing since last 2 months giving crash error

<img width="1252" alt="Screenshot 2023-06-20 at 7 57 09 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/97112013/1fd105e5-621d-48ce-b1d8-df800ef8fa3c">

### Steps to Reproduce

NA

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

I could not yet found it from live app users, But might be they could not connect me.

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: iOS
- Platform: iOS
- Browser name and version: NA
- Operating system and version affected: iOS
```

**Comment by kevintonb** [comment]
Hey @techpisat , the Github Issue Tracker is meant to resolve bugs that are found on the Flutterflow platform which are reproducible and can be addressed by the Flutterflow team. Please contact support@flutterflow.io for other queries that are not necessarily bugs, but issues that you face on Flutterflow. If you think this might be a mistake, please add more information along with reproducible steps and we will be happy to reopen and address this issue :)
