### ISSUE TITLE
Cannot Deploy Private APIs => Not Deployed (Error) | Error: Unknown error. Please contact support@flutterflow.io.

### ISSUE THREAD

**Issue by caseyharlin** [FlutterFlow/flutterflow-issues#1018]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While attempting to deploy an API to an existing (and functioning) API Group, I receive the error:  

> Not Deployed (Error)

 with the tooltip 

> Error: Unknown error. Please contact support@flutterflow.io.

The API group had been successfully deployed prior to this error and the new API was tested and working prior to deployment. 

I have several API groups all with > 1 APIs that are working and deployed. It seems to be an issue with: 

1. Customer.IO
2. Retool Webhooks

See steps to reproduce for more... 

### Expected Behavior

The new API deploys without error

### Steps to Reproduce

For Customer.IO 

- Add an API group
- - API Base URL: `https://track.customer.io/api/`
- - Header: `content-type: application/json`
- - Header: `Authorization: Basic [API KEY]`
- Add an API
- - API Endpoint: POST `v2/entity`
- - Add JSON body with variables
`{
  "type": "person",
  "identifiers": {
    "id": "<id>"
  },
  "action": "event",
  "name": "visit",
  "attributes": {
    "action": "<action>",
    "note": "<note>",
    "event_source": "<event_source>"
  }
}`

- Add a 2nd API
- - API Endpoint: POST `v2/entity`
- - Add different JSON body/variables
`{
  "type": "person",
  "identifiers": {
    "id": "<id>"
  },
  "action": "event",
  "name": "insurance",
  "attributes": {
    "action": "<action>",
    "note": "<note>",
    "event_source": "<event_source>"
  }
}`

NOTE: I'm also having this issue with Retool webhooks but it appears to only occur when I'm sharing the same webhook but posting a different JSON body.  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a unless there is a way to generate for API deployment?

### Context

Customer.IO accepts events (via this API call) which are then used to kick off customer communications/campaigns, etc. Although the API Endpoint is the same, the JSON payload can be significantly different from event to event (e.g. 'add insurance event' vs. 'appointment cancelled event') 

### Visual documentation

![Screenshot 2023-06-20 at 2 31 05 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/106691257/f639df3a-07c4-4ddb-a344-2a4cdc2abcd6)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: MacOS Desktop & Web
- Browser name and version: Chrome
- Operating system and version affected: macOS Ventura 13.4 (22F66)
```

**Comment by caseyharlin** [comment]
checking in on this one...

**Comment by caseyharlin** [comment]
I reached out to support about this one. They could not help me and told me that someone would respond to the bug report within 24 hours... it's been a week. 😣

**Comment by agreaves** [comment]
Hi @caseyharlin, sorry for the mixup here! As the error message implies, you were correct to message support, and we should not have directed you to create this GitHub issue as it is project specific and does not have reproducible steps. I'll forward this back to them but please message support again so we can flag and prioritize it since you've waited so long already.

I'll close this one here in the meantime.

(Just for future reference, we always need the Bug Report Code (you can create it on any page) in order to debug issues like these.)

**Comment by cyrezisbad** [comment]
for those wondering if what jorgemaranho said is true: yes, you need the blaze plan to use cloud functions which is what private api's use
