### ISSUE TITLE
YouTube Player Looping doesn't work

### ISSUE THREAD

**Issue by wrbmd** [FlutterFlow/flutterflow-issues#1019]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I have multiple YouTube players throughout my app within FlutterFlow that I have setup to loop videos. However, it is not looping the YouTube videos, and is actually suggesting videos after ours, which are not only irrelevant, but some of which are inappropriate and differ greatly from the type of content that we have on our app. I reached out to FlutterFlow support, and spoke to Danny, who advised me to reach out here and report that this is indeed a bug.

I have everything set up for our app to lunch, but I really wouldn't feel comfortable launching it with this current bug. If we could please work towards a resolution at your earliest convenience, so that all of the YouTube videos within our app loop, I would be most appreciative!

### Expected Behavior

Youtube videos should loop within YouTube player

### Steps to Reproduce

1. View page [hope_students] as an example (though this is present with every video on the app).
2. Play video on page and observe that it suggests unrelated video at end instead of looping our YouTube video.
3. Verify settings within YouTube player and see that it is set to loop the videos.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glsn635NgrsdA7rrcde9V/SEvJWYmR4c0tdh+GEkdB4z3BIgEfPTOak5vZrygTVVIeEyJjnEe1vfqkofxEcArPRWVbrZm+ZdcZjnyeGWlMJSvDc2VfW1TL9FgJnK94J+K2BFQHNFqL2ws6nGQCt6WYHLvN4zWIWsnGfq1LdeK2SrDX1iXc2URm05KZDPz

### Context

Trying to not have YouTube player stop playing video on repeat, let alone suggesting unrelated videos.

### Visual documentation

1. View page [hope_students] as an example (though this is present with every video on the app).
2. Play video on page and observe that it suggests unrelated video at end instead of looping our YouTube video.
3. Verify settings within YouTube player and see that it is set to loop the videos.

### Environment

```markdown
- FlutterFlow version: 1.1.84
- Platform: Chrome, MacOS Desktop App
- Browser name and version: Chrome [Version 114.0.5735.133 (Official Build) (arm64)]
- Operating system and version affected: Preview mode, Version 1 (V1)
```

**Comment by wrbmd** [comment]
Hi @aemelyanovff, do you have any updates on the resolution of this bug? The launching of our app is dependent on this fix.

Best,
Matthew

**Comment by aemelyanovff** [comment]
@wrbmd Thanks for the details.

This appears to be a bug in the [package](https://pub.dev/packages/youtube_player_iframe) that we use for YouTube: https://github.com/sarbagyastha/youtube_player_flutter/issues/733

I'll see if there's a workaround, but I can't provide any ETA.

**Comment by wrbmd** [comment]
Hi @aemelyanovff, I hope you're well. Any updates with potential workarounds for this bug?

**Comment by aemelyanovff** [comment]
@wrbmd I'm afraid I can't find a workaround. I'm afraid we have to wait until that package is fixed. And unfortunately it doesn't look like it's actively maintained.

**Comment by wrbmd** [comment]
Hi @aemelyanovff, this issue is still effecting the functionality of our application. Any updates as to status of the fix?

**Comment by aemelyanovff** [comment]
@wrbmd As I mentioned above, this is a bug in [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter). We can only wait until it's fixed there, but there's no indication that it'll happen soon. There's nothing we can do about it at the moment I'm afraid.

**Comment by aemelyanovff** [comment]
Update: we can't fix this bug at the moment. For now, we are disabling the "Loop Video" property in FlutterFlow.

**Comment by wrbmd** [comment]
Hi @aemelyanovff, can we at the very least implement something so that other random videos aren’t suggested at the end of the video included in the player?

**Comment by aemelyanovff** [comment]
@wrbmd The best we can do is add this parameter that will make sure that related videos will come from the same channel as the video that was just played.

![Screenshot 2023-09-21 at 1 21 53 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/6526d8d5-b530-4530-92f3-a336bd7a48f2)

It'll be available after the next update. Note that we don't have control over the specific behavior of this parameter, it depends on YouTube.

**Comment by aemelyanovff** [comment]
It doesn't look like the underlying bug in `youtube_player_flutter` is going to be fixed any time soon. We removed this option from FlutterFlow. Closing the issue.
