### ISSUE TITLE
Text Field is only takes First Document's Value when Generating Children through Variables

### ISSUE THREAD

**Issue by Spellytics** [FlutterFlow/flutterflow-issues#102]
## Issue
I believe I found a bug in Text Field when it's Generating Children through Variables and iterating through a list of documents queried.
It works correctly and iterates through the documents listed if it's a normal Text, but will only take the first document's value in if it is a Text Field initial value.

**Example**
Both the Text and Text Field has the same Variable, but the Text Field is displaying only 'Gin' as the initial value because it's only getting the first document's value. It means that you can only update the first document with the Text Field. 
See screenshots.

## Expected behavior (required)
Expected behaviour is for the Text Field to take on the same behaviour as Text widget when it's generating children through Variables. Text Field children should display and be connected to corresponding document's initial value and we are able to update the corresponding document value using the Text Field.

## Current behavior (required)
Text Field only takes the first document and generates it repeatedly for every children it creates from the variables.

## To Reproduce (required)
1. Create new page
2. Add Container Widget
3. Add Column
4. Add Text Field
5. Add query from backend to Generate Children through Variables
6. Set initial value from a String value from the variables
7. Observe that the Text Fields generated are all the same and takes on the first document's value

## Context (required)
In my app, I'm trying to get user inputs for ingredients in a recipe.
They should be able to change the ingredients they entered previously to something else.

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/70740500/200201114-9e068ed0-ad86-49e6-bdbc-31f809e68e01.png)
![image](https://user-images.githubusercontent.com/70740500/200201119-6c905a4c-cd31-4ca1-94bd-d9dc9f7be7dc.png)
![image](https://user-images.githubusercontent.com/70740500/200201122-59444649-1196-435d-a968-de9af071c385.png)

**Here are some other examples from other users**
On the left a Form Textfield. On the right a normal text to check if the listview worked correctly. 
![image](https://user-images.githubusercontent.com/70740500/200201314-57dbd93d-3146-4c45-bb69-ad101ff0247a.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 106.0.5249.119
* Operating system and version (desktop or mobile): Desktop Windows 10

**Comment by wenkaifan0720** [comment]
This is indeed a bug. The text fields are all using the same text controller. Thank you for bringing this up. We will roll out a fix soon.

**Comment by wenkaifan0720** [comment]
This is indeed a bug. Thank you for noticing it. At the moment we don't have an estimated time for a fix as it is quite involved. Besides, the more flutter way of solving this problem would be using components. Could you give it a try?

**Comment by Spellytics** [comment]
It kinda works - but I keep getting this error and it doesn't make sense.
Property Override "String property not properly set in [component_name]" 
![image](https://user-images.githubusercontent.com/70740500/201470356-8b448b51-5390-41cf-860f-cbb476177fd7.png)
![image](https://user-images.githubusercontent.com/70740500/201470424-c79a746c-6c8c-41cf-86f0-9caa6cb2b7cc.png)
![image](https://user-images.githubusercontent.com/70740500/201470439-1e1133f4-37b2-4fde-9669-6b64f73008bd.png)
![image](https://user-images.githubusercontent.com/70740500/201470469-a5f96b73-825a-405f-bcaf-67e1a68ae4d4.png)

**Comment by wenkaifan0720** [comment]
If it is possible, could you share with me the project link so I can debug it quicker?
I tried passing a document directly into the component and it works. See this project: https://app.flutterflow.io/project/flutterflow-issue-102-txqcxi (in the homePage).

**Comment by Spellytics** [comment]
https://app.flutterflow.io/project/foodbase-dl4dgx

**Comment by wenkaifan0720** [comment]
Hi @Spellytics. I tried deleting that textfield first and add it back again and the error goes away. Could you try it out on your project?
