### ISSUE TITLE
Compilation Error | payment_element.dart

### ISSUE THREAD

**Issue by dean-boi** [FlutterFlow/flutterflow-issues#1020]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Test / Run buttons attempt to build but ultimatly lead to error screen / message "Build Failed". Error message appears that seems to pertain to stripe widget - I have tried disabling stripe payments, and removing actions from the button that opens stripe widget. This made no difference. 

ERROR MESSAGE:

Compilation Error
Running "flutter pub get" in chat_papers...
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/home/.pub-cache/hosted/pub.dev/flutter_stripe_web-4.0.1/lib/src/widgets/payment_element.dart:146:3: Error: Type 'js.ElementsCreateOptions' not found.
  js.ElementsCreateOptions createOptions() {
  ^^^^^^^^^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/flutter_stripe_web-4.0.1/lib/src/widgets/payment_element.dart:147:27: Error: Method not found: 'ElementAppareance'.
    final appearance = js.ElementAppareance(theme: js.ElementTheme.night);
                          ^^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/flutter_stripe_web-4.0.1/lib/src/widgets/payment_element.dart:148:15: Error: Method not found: 'ElementsCreateOptions'.
    return js.ElementsCreateOptions(
              ^^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         57.9s
Failed to compile application.

### Expected Behavior

Application to build and run in browser in Test or Run mode.

### Steps to Reproduce

1. Attempt to build application

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slcr1z89grs9Y17ruYMB7/SoXH2U1U5Ikscp/bxIgGIDzPOw+ZPXsUxFvcO3iYFY+fUSmmn8x/8rKkfLyFcAEJQicRtU7zbtIEgrhUnG6UZOBDqueZXAnP/xnGXWOy6SrgyZQGMRZWF5l3HGUHNyifHfqQ4DsImdISq/LZO4=

### Context

Unable to further develop application

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/94611806/9bd3c634-f3d0-423b-b3aa-c54c65b3f8a5)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/94611806/e51db8e9-4d47-4c31-89c9-ad8ed3d69825)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Firefox 114.0.1 & Chrome 114.0.5735.134
- Operating system and version affected:  Windows 11 Version 10.0.22621 Build 22621
```

**Comment by hariprasadms** [comment]
Hi @dean-boi - We are aware about this issue. The fix will be made shortly. 
This is related to #1011

**Comment by dean-boi** [comment]
Thanks @hariprasadms, apologies for missing that. 👍
