### ISSUE TITLE
On Selected or On Change actions are triggered 'on page load' or initialization if state is not 'null'

### ISSUE THREAD

**Issue by urbanantor** [FlutterFlow/flutterflow-issues#1021]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

setting actions on text fields 'On Change' or choice chips 'On Selected' are being triggered on page initialization if the field is set with 'initial value'. 

I am using Action Blocks - in case this might be affecting the normal behavior. 

### Expected Behavior

If I'm not mistaken, I believe they should be triggered only on user interaction.

If I am mistaken, would it be possible to request that we add a 3rd option: 'On User Change', as in diff between null or initial (if set) value and current value? Not null vs initial value. 

### Steps to Reproduce

1. add textfield and/or choice chip
2. set initial value to something dynamic (I'm specifically using data from an API call)
3. go to actions and 'On Change' set a snackbar or dialog when triggered
4. go to test view and on load you will see the dialog even if you didn't modify the text field or select a choice chip. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SiMjfsM92ocMA1aqBbO9ajikXCDs6U40V0+xQEAodIZyqP4l2XOvTSE1uOOm4dG5AJmKWinEIp9qKvobhV+wnHxKIQ75m+YdUWznyYEmuVc2yPbmWW3MnO8NYC2HF34qOigldJtR1WnAQw12AOe+8aD/qJoTvOUVAJfmLLrjNpAO5Lg3KGjh2tmNecCfn

### Context

I am trying to trigger a change of component/app state in order to toggle/show buttons on the UI that will prompt the user that the document has pending changes to be saved. 

The user, when changing the initial value (if set) or null (if not set) then triggers the action to update a sync prompt bool that then shows a save button on the document header. 

### Visual documentation
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97798496/6a34023e-be00-4cb3-81c5-23fb9c57ca09)
1 ) click on entity to edit.  
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97798496/1c0cefe2-99d7-4bc8-9400-eebe3e371ada)
2 ) test dialog is set to trigger when 'on change' within choicechips but as bottom sheet loads, it is triggered. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97798496/cd66a221-2d4f-4909-9a3a-6fe5eed00e4e)
3 ) click on choice chips after dismissing dialog triggers dialog as expected

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Test mode, Run mode, Web
- Browser name and version: Chrome 114.0.5735.134
- Operating system and version affected: Windows 11
```

**Comment by kevintonb** [comment]
Hey @urbanantor , thank you for providing the steps to reproduce the issue. But this is an expected behaviour with the Choice Chips. When the initial value is setup based on an API call response, that particular value is selected when the call response is over. This would lead the onSelected action to be triggered and thus launch a SnackBar / Dialog based on the subsequent actions set up. As a workaround, you can also use a conditional action to setup firing the snackbar / dialog based on the condition that the onSelect has been triggered for the first time.

**Comment by hariprasadms** [comment]
As per confirmation in the latest comment by @kevintonb, It is expected behaviour of Choice Chips widget. Hence, we are closing the issue. Thanks

**Comment by solkennedy** [comment]
Just to throw my two cents in here, this behavior makes absolutely zero sense and results in unexpected results. Why would a developer expect that "On Selected" means "On Initialization AND On Selected"? At the very least you could change the tooltip to match the as-is behavior.
