### ISSUE TITLE
Flutterflow Error "Collection: _____ is a subcollection but the parent collection no longer exists" 

### ISSUE THREAD

**Issue by toriyn** [FlutterFlow/flutterflow-issues#1024]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to test my FlutterFlow code a debugging error Is present that states: "Collection "ChatNew" is a subcollection but the parent collection no longer exists. Tap here to delete it." After clicking on the error message as instructed I am taken to the Firebase collections screen where there is no collection named ChatNew present. 

"ChatNew" is a previous collection that had bugs and therefore I deleted it before completely restarting with a new collection named "SecondChat" 

The primary issue is that the collection has already been deleted and even after manually deleting the collection from the Firebase console, it is still being recognized as an error on Flutterflow UI builder.

![Screenshot 2023-06-22 at 11 06 12 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/129636681/e19817b5-12c7-46e6-9508-98dd1da749cc)

### Expected Behavior

I expected that If I were to click on the error message that states:

 "Collection 'ChatNew' is a subcollection but the parent collection no longer exists. Tap here to delete it." it would remove the Firebase collection and the error would go away. However, upon clicking the error, nothing happens other than being brought to the main "Firebase collections" screen in FlutterFlow.

### Steps to Reproduce

1. Create a Firebase Collection within FlutterFlow
2. Create a Firebase Subcollection within the previously mentioned collection 
3. Delete the Primary Collection and not the subcollection
4. Create a new Collection with a subcollection
5. Add elements to this collection as well as backend functionality
6. Click the "Test" button to test the project (Should not work as a result of the present error)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMr65YVNobhG1ar9be54iWQvHEQ+TL07r+5xb0gvIrbyOu9+PuCkbRNvTs/iT2lhHFabkT8F+d7yjeLtNsA6BymVUbpq+LVIcDyVLHq8RbLXDJOCZURCRJ5hIWqnyLTQ2SRdJrdvLWw/12ete/CWQTDtJ5O/Zwh9f6PHaOI=

### Context

This issue has affected me by preventing me from running an accurate test of my project thus far.  I am attempting to create a Chat feature for my project and this is preventing me from continuing.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/129636681/3b89f0b7-ebd7-4da6-937d-4722efdb73ac

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, MacOS Desktop
- Browser name and version: Chrome 114.0.5735.133 (Official Build) (x86_64)
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by aemelyanovff** [comment]
@toriyn Thanks for reporting the issue, and sorry for the late response. Are you still experiencing the issue? I believe it's been fixed.

**Comment by aemelyanovff** [comment]
Closing the issue as stale. @toriyn please feel free to reopen if you are still experiencing the issue.

**Comment by wylliamnovais** [comment]
same error here

**Comment by mraccah2** [comment]
same issue...
