### ISSUE TITLE
Firestore Query not showing up in data needed in Actions

### ISSUE THREAD

**Issue by PandomaOes** [FlutterFlow/flutterflow-issues#1025]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Firestore Query Action within Actions is not showing up.

### Expected Behavior

A Firestore Query menu should appear when providing 

### Steps to Reproduce

1. Create a random button
2. Add actions
3. Add a Firestore Query action under Firestore
4. Add any other action and try to get the firestore document reference from number 3. (this wont appear)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shc+Az5Fgod9J1aXidcBr/TwUJj42apE0scsZa0kdB4joPLJ/duD4YlhoZ9+8YWlhHFaguH0xws7vifDxUPVcFxOsftU5ybhidgLyJHq8RbKlBc+eOnNDIJpPf1y44LSW3R0lFMloL3gG20OINevLfATfCZu/Zwh9f6PHaOI=

### Context

I am trying to query and get a document reference and use it to update the document.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12844396/354d0be6-534e-49d6-b6df-9f1a3043b9cb)

As you can see, i added a simple search too to show that the simple search appears but not the firestore query above.

### Environment

```markdown
- FlutterFlow version: v3.1 (Released June 23)
- Platform:Web
- Browser name and version: Chrome 114
- Operating system and version affected: Windows 11
```

**Comment by Thesergiolg99** [comment]
you probably need to put in the action query an output name, then it will be accessible thriugh "action outputs"

**Comment by PandomaOes** [comment]
> you probably need to put in the action query an output name, then it will be accessible through "action outputs"

Hi, thanks for pointing that out. I did forget that part, which was mandatory to fill in anyways so maybe FF can implement the feature where that should not be empty when created.

Also, is there a way for it to return a document reference instead of a list? something like what you get from a backend query with the same name.
Backend Query: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12844396/732061b5-ba3b-4f1c-b28c-a380ef27b18c)

Action Outputs :
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12844396/d8610241-81c7-49b4-8119-fabf7f810818)

**Comment by bulgariamitko** [comment]
@PandomaOes it cna return a document ref if you have a document ref in your document if you are using an action it will always return the whole document just like when you are querying it from a widget.
