### ISSUE TITLE
Icon Button is Display the wrong way

### ISSUE THREAD

**Issue by JanikHalder** [FlutterFlow/flutterflow-issues#1026]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The ButtonIcon Element is not position right if the app is running on web. It should be horizontally center. 
![IMG_FF2DAAB64735-1](https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/fe39ea5b-7c17-4270-98de-3e441c83e693)

### Expected Behavior

It should be displayed like this and was before the new Flutter Update and it is still shown right in the preview and on run / test mode.
<img width="199" alt="Bildschirmfoto 2023-06-22 um 21 12 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/7775cd6d-2427-4853-a90f-050568cfc60a">

### Steps to Reproduce

Create a Container
Insert A Column 
Add a Button-Icon
Publish to Web

![IMG_EB46F3F3E90D-1](https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/cd2295e1-a869-4f21-8386-1b8c1b3ca2c0)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Any widget will work

### Context

I just want to center the Icon of the Button

### Visual documentation

![IMG_EB46F3F3E90D-1](https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/f12a45cd-03a7-42b3-90f5-10fc9e75a62f)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:  Web
- Browser name and version: Safari
- Operating system and version affected:
```

**Comment by srh98** [comment]
Seeing the same thing on my app. Attaching screenshots of how the buttons appear in the the builder and live app. 

![Screenshot 2023-06-23 at 1 45 52 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/
<img width="160" alt="Screenshot 2023-06-23 at 1 46 06 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/117376796/9975abac-dfce-4544-b2ca-e994bf68310f">
117376796/3f8077ba-122a-439b-a1e7-2d36af2a1690)

**Comment by hariprasadms** [comment]
Hi @JanikHalder - - Can you please update issue with project bug report code?

**Comment by JanikHalder** [comment]
Hi @hariprasadms 

This is the bug report code for the Icon Button.

IT40hfKA4cx1rscG7qqNccdVmik5JUw/a4Iwm+pBaCwqGJToPLUMPsneVFRuZry8TFY7e079uDs01vfqhuzLJsYqCzKVfphn+JYAVQzLZH+5aZioDKqBfW1RI+VRCUim16bQhQlDAON1V2Qt112UCu6AQgLvJ77NOFVMLfilKdeK2SrDX1iXc2URm05KZDPz

**Comment by JanikHalder** [comment]
This issue only seems to appear on mobile device, because if I open the URL on in a Laptop the Icon is displayed the right way.

@hariprasadms Are there any updates on that issue?

**Comment by wenkaifan0720** [comment]
This is probably caused by Flutter html web rendering. Could you turn on the Use Canvaskit (beta) toggle and publish to the web and see if the issue is still there?
