### ISSUE TITLE
API JSON Path Configuration

### ISSUE THREAD

**Issue by adamrUK84** [FlutterFlow/flutterflow-issues#1027]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since last FF update, named JSON paths for API calls where the JSON path includes a dash are being reported as an error. 
<img width="1161" alt="Screenshot 2023-06-22 at 21 33 06" src="https://github.com/FlutterFlow/flutterflow-issues/assets/130186974/73cb6403-643c-47f8-aef4-20a59a7babd3">

### Expected Behavior

Prior to the last FF update this was working and schema of the JSON has not changed. 

### Steps to Reproduce

Create an API call with JSON path that include a dash
Paths do not appear in Recommended list (or if API already saved previously named paths create an error)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi+fqxItNtbxa1s+NY8dV/TwWGDs2U5EvidZHSis9f5CvOpYUec/6P1NvQumgY2NcJU22p14Kwd7MhvPfEMFcCAeafYs6+cxqaQnKWXORVamTF7iKP0BAI+NWGEiuyLWrhCQmLbF0V14GwGCQGOzKYBHrO7rQDnowSq/LZO4=

### Context

No longer able to call API or run the app in Test mode.

### Visual documentation

See image above.

### Environment

```markdown
- FlutterFlow version: 3.10.4 (released 22 June 2023)
- Platform: Mac
- Browser name and version: Chrome 114.0.5735.133 (Official Build) (x86_64)
- Operating system and version affected: Ventura 13.1
```

**Comment by adamrUK84** [comment]
In the API call itself you can also see a partial error message:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130186974/7a6c13c4-4e43-43b8-9cb4-71419d482606)

**Comment by Pieter-JanRoggeman** [comment]
I have encountered the same issue, I'm not able to deploy my app anymore since FlutterFlow reports this as a bug when using a "-" in an API call.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47556325/7209bed2-5050-4681-a270-ce2a5d0aeec1)

**Comment by adamrUK84** [comment]
Hi @bulgariamitko @katherineqian, do you have an estimate of how long it will take to fix this bug please as it is preventing me from testing and has impacted my published app?

**Comment by bulgariamitko** [comment]
@adamrUK84 , sorry I do not work for FF so I can't tell.

**Comment by juanpenuelas** [comment]
Hi @adamrUK84 
I created this custom function to solve this issue temporally.
Hope it helps.

String getJsonValueWithHyphen(
  String key,
  dynamic json,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return json[key];

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

**Comment by Pieter-JanRoggeman** [comment]
Hi @juanpenuelas how would this work for lists?
Thanks already for your help!

**Comment by aemelyanovff** [comment]
This actually is the expected behavior according to https://github.com/dchester/jsonpath/issues/27#issuecomment-158672297:

> To reference a member whose identifier contains a dash, use subscript and quoted string e.g., $.status['dev-01']

However, for compatibility, in the next update we will revert [json_path](https://pub.dev/packages/json_path), which we use for validating json paths, to a previous version that allows dashes.
