### ISSUE TITLE
Conditional Logic for Fill Colour Not allowing to set to specific value

### ISSUE THREAD

**Issue by jaburton111** [FlutterFlow/flutterflow-issues#1028]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In your documentation about conditional logic you describe the ability to select the source as either a specific value or a variable. However, when I try to do this to set a conditional colour on a container it does not give me the option to select 'from a specific value'. It only gives me the option to select from variable.

### Expected Behavior

I should see an option to select an option to select 'specific value'

### Steps to Reproduce

Select a container, choose to set fill colour with variable, select conditional value (if/then/else), select the 'if' value then 'condition', the 'single condition', first value is a field from an api call, and second value is supposed to be a specific value but it does not offer that option. 
<img width="955" alt="Screen Shot 2023-06-21 at 8 50 34 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/a4490ac1-9173-4be1-bd06-5b71b392a246">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

In your documentation about conditional logic you describe the ability to select the source as either a specific value or a variable. However, when I try to do this to set a conditional colour on a container it does not give me the option to select 'from a specific value'. It only gives me the option to select from variable.

### Context

I am trying to have dynamic colour for a container which is determined by a specific value. This feature is fundamental to the functionality of my app.

### Visual documentation

<img width="955" alt="Screen Shot 2023-06-21 at 8 50 34 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/cf2475db-bafe-41a9-994f-ce9c203c826c">

### Environment

```markdown
- FlutterFlow version: v3.1 
- Platform: 
- Browser name and version: Safari v15.1 
- Operating system and version affected: macOS Monterey 12.0.1
```

**Comment by hariprasadms** [comment]
Hi @transparentgeek - Thanks for submitting the issue. I can confirm that iOS apps deployment its been working fine. The error you are seeing is clearly related push notification missing configuration. Please double check the configurations and follow the steps.

_Error (Xcode): Provisioning profile "Logbook and journey planner for your RV or caravan ios_app_store 1685931001" doesn't support the Push Notifications capability.
/Users/builder/clone/ios/Runner.xcodeproj_

See below showing latest iOS build is successful.

<img width="1073" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ac79a53a-c6a2-4f66-a9f4-d8607b30b832">

**Comment by SameerShahzad99** [comment]
@jaburton111 Thank you for submitting this bug report, I was able to reproduce this issue on my end!

**Comment by jaburton111** [comment]
> Hi @jaburton111. This is because you have set the first field from a JSON value which have type `dynamic` (basically it can be anything), so FF can not determine the type for the second field. I think in this case you'll have to use a code expression to type in the specific value you want to use.

Hi @wenkaifan0720 , I don't really understand your comments here. What would I select to input a code expression? And if I want the colour to be determined based on a specific numerical value with decimals, what would that code expression look like?

**Comment by wenkaifan0720** [comment]
Hi @jaburton111. So you would still set the second value from variable, and in the variable selection dialog you can select code expression (which is basically an inline function), and in that code expression you just use one parameter and set its type to double. You can give the parameter some name, and the code expression should just be the name of the parameter. Now you can give the parameter a specific value as you had wanted. 

The reason for this workaround is because we really can not infer the type of a field in the JSON.
