### ISSUE TITLE
The transparent bottom sheet be came none transparent colour

### ISSUE THREAD

**Issue by kailiscsk** [FlutterFlow/flutterflow-issues#1029]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The transparent bottom sheet comes with none transparent color.
this happened after the update on 22nd June 2023

### Expected Behavior

transparent bottom sheet 

### Steps to Reproduce

Create a bottom sheet as a loading page.
Set transparency to the bottom sheet.
when you test it , the color is not transparent.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl+fl4otNxOFb14SJKsJommUvC2kcTL4zlO1HcxAYGO/yPbJ/YMnRak5WUt+7TGlhHFaKklEx3Nb9iIX1Me5cNUyCc4BPzs8NWALyTXq8Rc2PBpO0WHx9I9NgN0ikyqar3CJSPuxtSlEj3zn7Hue+ZDPtCZO/Zwh9f6PHaOI=

### Context

very critical!
provide a bad user experience.

### Visual documentation

<img width="943" alt="iShot_2023-06-22_23 12 26" src="https://github.com/FlutterFlow/flutterflow-issues/assets/135726277/03ab6d84-5273-4bf2-bcc9-cf439a10733a">
<img width="443" alt="iShot_2023-06-22_23 14 24" src="https://github.com/FlutterFlow/flutterflow-issues/assets/135726277/4c7effc9-c0de-45d2-8b75-d334ddf4d0bd">

### Additional Info

the color should be transparent but displayed a gray color

### Environment

```markdown
- FlutterFlow version: 3.10.4 (released 22nd June 2023)
- Platform:MacOS, android, iOS 
- Browser name and version:google chrome, and Safari
- Operating system and version affected: Macbook
```

**Comment by srh98** [comment]
Also experiencing this problem. My bottom sheets all have color #99000000 (60% transparency) but now the background underneath the bottom sheet appears white. This is happening in both run mode and test mode.

**Comment by victoriahuang1** [comment]
Hi @kailiscsk thanks for the report. We already have a bottom sheet background fix that will be available upon the next deploy.

To confirm this is the same bug, can you show me where the bottom sheet action is in your project?

**Comment by wagnerramalho** [comment]
> Also experiencing this problem. My bottom sheets all have color #99000000 (60% transparency) but now the background underneath the bottom sheet appears white. This is happening in both run mode and test mode.

The same is happening in my projects.

**Comment by wagnerramalho** [comment]
Hello @victoriahuang1 do you know when will be deployed the widget fix? Thank you

**Comment by agreaves** [comment]
Hi @wagnerramalho and all, the fix should be deployed! Please let me know if this is fixed for you, thanks!

**Comment by srh98** [comment]
Fixed for me. Thanks, @agreaves & team!

**Comment by wagnerramalho** [comment]
Hello Guys, it's ok for me.. thanks a lot.
