### ISSUE TITLE
'SelectionArea' isn't defined

### ISSUE THREAD

**Issue by solita-jtn** [FlutterFlow/flutterflow-issues#103]
## Expected behavior (required)
No errors in downloaded code

## Current behavior (required)
The method 'SelectionArea' isn't defined for the type 'xxx'.

## To Reproduce (required)

1. Create new page
2. Add API call
3. Add Text
4. Set from variable 
5. Download code

```
  SelectionArea(
      child: Text(
    getJsonField(
      photoPageGetAPhotoResponse.jsonBody,
      r'''$.created_at''',
    ).toString(),
    style: FlutterFlowTheme.of(context)
        .bodyText1,
  )),
```

## Context (required)

Cannot build the application from downloaded code.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Hi @solita-jtn, 'SelectionArea' widget is available from Flutter 3.3 version onwards. Update your local Flutter version to 3.3 or latest stable version and see error in downloaded code can go off. Thanks

**Comment by solita-jtn** [comment]
I guess this means that minimum version (3.3) should define in the code, otherwise it fails to compile.

**Comment by agreaves** [comment]
Closing this for now, as FlutterFlow officially supports Flutter 3.3.4 currently.
