### ISSUE TITLE
Phone authentication in Firebase not working

### ISSUE THREAD

**Issue by trikayastha** [FlutterFlow/flutterflow-issues#1033]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have set up all the necessary settings in Firebase and Flutterflow to execute the Phone Authentication. But when the phone number is inputted, the SMS verification page never loads. It is mentioned that the SMS verification page will load automatically but it never loads. 

### Expected Behavior

The Phone Authentication page needs to redirect to the SMS verification page automatically after the phone number is inputted by the user.

### Steps to Reproduce

1. Create new page with all necessary Phone authentication input fields.
2. Button that needs to send the SMS verification needs to be assigned with all the necessary phone authentication details such as the input field for the phone number.
3. SMS verification page should be automatically redirected but the page never redirects.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi/Ll5ZR1octF+Kn+d+1VoGUWI0MfWLsr0utuGA0hfYDxO4oHd+OkP0tLYte8d1FiKFn+gl41+smNiN7MU8JeHyWBRaZ/1r5XQTvgITqVb7KoDc+Oe3J8RJtjIUzGyKaNhRRAXctqckVk3E2mDPCdG3qCf9qOYwx5e6fDbOY=

### Context

Phone authentication is the only option currently planned for my project and it has halted the whole completion of the project. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/125125022/1aeb3fb0-8740-4af6-92a1-c82adedd6b98)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/125125022/9e107390-7274-451d-b4d0-6fe70fb2244e)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Brave Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @trikayastha - Thanks for submitting the issues. I have tested the phone authentication and its working as expected. I looked at your project as well. Looks like configuration is not in correct order. I would suggest double check the configuration and try once again. Confirm if you still facing the issue. Thanks

**Comment by trikayastha** [comment]
Thanks @hariprasadms for confirming the issue is my side. I'm still new to this FlutterFlow platform and getting used to all the process.

I have assigned proper roles to flutterflow in firebase, properly assigned the Phone auth pages and action in necessary pages. 
It'd be of great help if you can mention where you noticed something out of order in my project that I need to fix to proceed with the process.

Thanks again.

**Comment by hariprasadms** [comment]
Hi, You can add me as your project collaborator. I can have a look and see whats going in the project.

**Comment by trikayastha** [comment]
Sure @hariprasadms that would be of great help. Can you mention your emailID so that I can add you as collaborator?

**Comment by hariprasadms** [comment]
Hi @trikayastha - Thanks for adding me as collaborator. I have done some changes in the pages and tested it. But, getting the same above error. It looks like something wrong in the firebase project authentication settings. check that you have added all the domains in the setting sections. See below.

<img width="1090" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/21d4f7fe-43d8-48c1-98da-a6df571a3d62">

https://docs.flutterflow.io/data-and-backend/firebase/authentication/phone-sign-in

**Comment by trikayastha** [comment]
I found this section from the documentation which I haven't setup yet so this will be the task as well.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/125125022/7418f6a9-01ff-40b5-8931-0f610e150e6a).

Regarding the Authorized domains you mentioned, where from where can I get the domain details in Flutterflow to add in the firebase?

Thank you @hariprasadms for helping me out on this project. Means a lot.

**Comment by trikayastha** [comment]
Hello @hariprasadms I completed the required steps from the Flutter Documentation regarding the SHA-1 keys. 

Can you verify this the only required domains in the Firebase project
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/125125022/ee7b0e28-d808-497c-b9d6-142630d793bc)


Thanks again.

**Comment by hariprasadms** [comment]
Hi @trikayastha - I apologise for the delay in getting back to you. I hope you have resolved the issue.  Please close the issue if everything is working as intended. Please update status of the issue. Thanks

**Comment by sbis04** [comment]
Closing this issue, assuming it's resolved.
