### ISSUE TITLE
Unable to login to dashboard after sign in and verifying email address on app.flutterflow.io

### ISSUE THREAD

**Issue by Hasagizo** [FlutterFlow/flutterflow-issues#1035]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely

### Expected Behavior

1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely

### Steps to Reproduce

1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

XXXXXXXX

### Context

1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely

### Visual documentation

1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely

### Additional Info

1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely

### Environment

```markdown
1. login to flutterflow.io
2.email address verification
3. Loading Dashboard Runs Infinitely
```

**Comment by agreaves** [comment]
Hi @Hasagizo, thanks for reporting this issue and apologies for the inconvenience. This should now be fixed so you should be able to login and verify email now!
