### ISSUE TITLE
Can't add data types to collection schema

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#104]
## Expected behavior (required)
Expect to be able to select data types in dropdown in collections screen.

## Current behavior
Can't reach, drop down is too short. It's worse in the browser than the FF desktop application, see below.

## To Reproduce
1. Add a collection in Firestore settings
2. Add 8 data types
3. Try adding another

## Context (required)
This is critical as further roll-out of my app is now blocked.

## Screenshots / recordings
[FF Desktop application](https://photos.app.goo.gl/CrUcHwMb3RFUkUJs7)
[Browser](https://photos.app.goo.gl/Wu2wHbepxEihC4h48)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 1.1.17
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop, Web
* Browser name and version: Safari Version 15.6.1 (17613.3.9.1.16)
* Operating system and version (desktop or mobile): MacOS 12.6

**Comment by agreaves** [comment]
Hi @ampapplarsen, thanks for the bug report! This will now be fixed upon our next deploy!

**Comment by ampapplarsen** [comment]
Just a heads-up: fixed for browser but persists for MacOS desktop app (version 1.1.8) @agreaves
