### ISSUE TITLE
Form widget cannot be in the listview

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#1040]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Project allows you to include a form widget within a listview, without showing a project error.

### Expected Behavior

Project should error when form is in list view, or create a unique key for each generated form within a listview to prevent `The key [LabeledGlobalKey<FormState>#13174] was used by multiple widgets.` Error.

### Steps to Reproduce

1. Add form to list view
2. Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

NA

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Josefpa** [comment]
Wrap it in a component and add that component to the list view

**Comment by hariprasadms** [comment]
Hi @DanielEdrisian - Thanks for submitting the issue. There is no blank project with reproducible steps. Also no project bug report code given. With out these details, we do not consider issues for investigation. Please update the details accordingly. 

A quick answer to try -  Convert form elements as a component with in list-view. It gives an option to add unique keys for component elements with in list-view. I hope this can solve the issue.

**Comment by DanielEdrisian** [comment]
Hari, I just reported this out of good will. I understand the problem myself, but I thought for another person who may not know this, they will be confused and frustrated. Thought maybe it would lead to fewer customer support requests if you actually communicate this error to the user before it goes to code-gen.

**Comment by wenkaifan0720** [comment]
![iScreen Shoter - Google Chrome - 230707160001](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/215962b2-0b39-4510-8347-6f49d68fd19c)

HI @DanielEdrisian. Looks like this has been fixed. Could you confirm?
