### ISSUE TITLE
Conditional Shadows not generating conditions in code

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1041]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a Container with box shadows: 

set an if and else with two different colours

The condition doesn't change the shadow colour 

### Expected Behavior

To Change Shadow Color

### Steps to Reproduce

set an if and else with two different colours, change condition

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx891m9sA7a6JKsBvoCA7C0McTeU7lexsaxAaI+PqE4kqOeD8UBBBSOqHT2x2ImaYglwBpPPIvt7tNPZdZQSCQIhazLpXUxDvTmSgM7XRPc2KS3MmN/1RIFOM0LbYuSVAVfRaL1I91GCmJfO+b3qCf9qOYwx5e6fDbOY=

### Context

```
Generated Code: 
Container(
  width: 100,
  height: 100,
  decoration: BoxDecoration(
    color: FlutterFlowTheme.of(context).secondaryBackground,
    boxShadow: [
      BoxShadow(
        blurRadius: 4,
        color: Color(0x33000000),
        offset: Offset(0, 2),
      )
    ],
  ),
)
```

Conditions set: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/98a48c62-7c90-43fa-9905-bae514b2aba8)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/b042ce5a-36ca-4f7d-8aaa-970804b42bf6)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @Josefpa - Thanks for submitting the bugs. I can reproduce the issue. 

Dev note - Along the above conditional configuration is not generating the code. Shadow property does not take any binding values form variables. See below. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/7a131183-833d-4c46-8067-a27e8e5ed565

**Comment by Josefpa** [comment]
Bug Fixed in Latest Release
