### ISSUE TITLE
FlutterFlow on Mac 1.1.86 Crashes and can't open

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#1043]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow on Mac 1.1.86 Crashes and can't open
1. Uninstall FlutterFlow
2. Download latest from https://flutterflow.io/flutterflow-desktop-app and install
3. Open app, it crashes

### Expected Behavior

Open app and be able to use normally
Currently I'm using FlutterFlow on Mac v1.1.82

### Steps to Reproduce

1. Uninstall FlutterFlow
2. Download latest from https://flutterflow.io/flutterflow-desktop-app and install
3. Open app, it crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

DummyC2A00ADF-3989-5316-063E-F279EBF19E95

### Context

Can't use FlutterFlow on Mac latest

### Visual documentation

<img width="997" alt="スクリーンショット 2023-06-25 9 33 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/00538e4b-11a3-466c-94c0-a126f6155478">

### Additional Info

Error messages:

Process:               FlutterFlow [9414]
Path:                  /Applications/FlutterFlow.app/Contents/MacOS/FlutterFlow
Identifier:            io.flutterflow.prod.mac
Version:               1.1.86 (1.1.86)
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           FlutterFlow [9414]
User ID:               501

Date/Time:             2023-06-25 09:33:33.599 +0900
OS Version:            macOS 11.7.4 (20G1120)
Report Version:        12
Anonymous UUID:        C2A00ADF-3989-5316-063E-F279EBF19E95

Time Awake Since Boot: 3500 seconds

System Integrity Protection: enabled

Crashed Thread:        5  Dispatch queue: com.google.firebase.firestore

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at /Users/thunder/Library/Application Support/firestore/__FIRAPP_DEFAULT/flutterflow-io-6f20/main: LevelDB error: IO error: lock /Users/thunder/Library/Application Support/firestore/__FIRAPP_DEFAULT/flutterflow-io-6f20/main/LOCK: Resource temporarily unavailable (expected created.ok())'
terminating with uncaught exception of type NSException
abort() called

### Environment

```markdown
- FlutterFlow version: 1.1.86 on Mac
- Platform:Mac
- Browser name and version:Chrome 114.0.5735.133
- Operating system and version affected: macOS 11.7.4
```

**Comment by hariprasadms** [comment]
Hi @idea-garage - The latest version v1.1.87 is available here - https://flutterflow.io/flutterflow-desktop-app. Try this and let me know how it goes. I can confirm that, It is working at my end. Thanks

**Comment by idea-garage** [comment]
Thanks @hariprasadms. I reinstalled v1.1.87, but it also crashed.
I removed mac application cashes and reinstall, result is the same.
Currently I'm using browser version, it is slower compare to mac app sometimes.
<img width="941" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/a140735b-ef66-4308-b755-98115e8749a2">

**Comment by wenkaifan0720** [comment]
Hi @idea-garage. Could you try to upgrade your MacOS version? I tested on 13.2.1 and the desktop app can be used.

**Comment by idea-garage** [comment]
Finally I updated MacOS to 13.4.1（22F82）, and the probrem solved!
Thanks for your help.
