### ISSUE TITLE
Build number not changing while deploying app in playstore.

### ISSUE THREAD

**Issue by Shrihari1357** [FlutterFlow/flutterflow-issues#1048]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While I am trying to deploy it to mobile deployment. Playstore shows error as build number is same as before. Flutterflow donot updates build number in updated aab file.

### Expected Behavior

Play store deployment 

### Steps to Reproduce

Develop an simple app
Try to deploy it to play store.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wzPHlwIt1rs9H+Krqb/oxniYWGDs5U40emNVDSis8GZT0B4kcYs+kfklUOenmYFVmJ2eKhjgX/MqPktjpG/YqBxyZY65EwcxbVQrKJVmVVpSMO4S3b2pSO5tgf3Ks07awkxNTJsFoLyUl2l6hfNivXhDtK4T1CzIGR+a4XdeK2SrDX1iXc2URm05KZDPz

### Context

The bug report code will not be there as it is full apk issue.  The issue is blocking my release and testing. It is very serious issue.

### Visual documentation

This issue cannot be shown visually as it takes lot of time. So please recreate the issue by deploying a app to playstore.

### Additional Info

The issue is in flutterflow system of deployment. I donot know just check the issue again and confirm it.

### Environment

```markdown
- FlutterFlow version: latest version
- Platform:android
- Browser name and version:chrome latest
- Operating system and version affected: Windows latest
```

**Comment by hariprasadms** [comment]
Hi @Shrihari1357 - Thanks for reporting the issue. What error you can see in mobile deployment error section?  

Are you seeing something like below ? confirm please.

<img width="741" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/9dc53a85-7655-44cd-ab73-1d8a566dffd4">

**Comment by Shrihari1357** [comment]
not this one. I downloaded AAB file and uploaded it in playstore then the play console showed error.

**Comment by Shrihari1357** [comment]
![weberreor](https://github.com/FlutterFlow/flutterflow-issues/assets/101409498/fe28fc66-3cee-4842-853f-a5101877bd5a)

**Comment by Shrihari1357** [comment]
this is exact error. I changed version code 45, 46, 47 but it shows error as version code 44

**Comment by hariprasadms** [comment]
@Shrihari1357 - Thanks for the info. If you are deploying through dowloaded app file, I think, it is expected error. Was it working fine earlier? I would suggest deploy through FF and see how it works.

**Comment by Shrihari1357** [comment]
I deployed using same method earlier. But this time I got this error. How to deploy it directly from flutter flow it shows build failed always.

**Comment by Shrihari1357** [comment]
Sir,
I always deploy by following these methods,
first I change version and build number,
next I press deploy to play store button,
After success I press check build status button. It shows failed errror. I download the aab file after failed msg and upload it in playconsole.

**Comment by Shrihari1357** [comment]
The above steps works fine for me. But this time it shows this error.

**Comment by hariprasadms** [comment]
Hi @Shrihari1357 - Just a quick question, if you are not configure mobile deployment for playstore in FF. How did you download AAB file? are you building through downloaded code ?

**Comment by Shrihari1357** [comment]
No AAB file is downloaded from flutterflow. First I press deploy play store button, nxt I press deploy, after It  shows Succcess I press check build status. It shows failed after some time. After that I download the aab file from flutterflow.

**Comment by gergo-szabo** [comment]
I have the same issue. Play store currently has version 1.0.0 and 2.0.0 app bundle. When I press Deploy to Play Store I get the message below. Manually changing version number didn't help (tried 3.0.0 and 4.0.0, no build number).
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46539838/74e5a406-9d84-4a90-9597-d553a5f407b2)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46539838/8c98bfd8-264d-4de6-9da7-90b573e5ef3f)

**Comment by gergo-szabo** [comment]
Manually changing version to 3.0.0 and build number to 3 (just to be nice, probably not a factor?) worked. I have three app version in Play Store!
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46539838/771eaa22-d665-46e6-819b-a21eb835ed12)

**Comment by hariprasadms** [comment]
Hi @Shrihari1357 - Sorry for being late to respond on the issue. Considering the general wider status of mobile deployment feature is working as expected, I would say this issue could be specific to project. However, I presume, this issue has been resolved for you now. Please 

confirm whether this is the case and I'll close this issue. Thanks!

Thanks @gergo-szabo for your inputs.

**Comment by hariprasadms** [comment]
Hi, No recent activites in the issue. We presume you have resolved the issue. Hence closing the issue. Thanks
