### ISSUE TITLE
Rive animations don't load in Mac app

### ISSUE THREAD

**Issue by sgardoll** [FlutterFlow/flutterflow-issues#1049]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- Open Mac app
- Add Rive animation widget to Scaffold
- Add a Network link to widget (I used https://rive.app/s/lCdwISBlck6VyyWt9zHivQ/)
- Animation doesn't load and Properties screen turns grey

Note: You can switch to the web app and contimue to use the widget as per normal. It's just not working in the Mac app
![Screenshot 2023-06-26 at 4 37 02 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/dbd5190a-c684-41b1-b89e-29c1a565b24e)

### Expected Behavior

- First 3 steps above should occur
- Animation should preview on Scaffold and Properties panel should show and give options

### Steps to Reproduce

- Open Mac app
- Add Rive animation widget to Scaffold
- Add a Network link to widget (I used https://editor.rive.app/file/check_animation/473679)
- Animation doesn't load and Properties screen turns grey

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkcjfz892odcB1r6JcvlsoCUvNk8cTeU30+thcw4bI+PwPYkhP87SU1pVYuqHeW1EHGGZpEUGp/DWkobDKew3OgSdfqk5+cxhUxDiIVKhVK6pCbqgWHNCGfpnI0vC5KSzmiZ7PtVaLSE46k6uIeeAb3qCf9qOYwx5e6fDbOY=

### Context

Unable to use Mac app for Rive Animations

### Visual documentation

![Screenshot 2023-06-26 at 4 37 02 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/4857573f-dffb-4e53-b913-477bad518095)
![Screenshot 2023-06-26 at 4 38 45 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/24bc4f90-67cd-4e74-8064-76e7127b7c4e)
![Screenshot 2023-06-26 at 4 39 02 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/787d67f5-5735-4d8e-a109-e4ae7dabddf2)

### Environment

```markdown
- FlutterFlow version: Screenshots attahced
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @sgardoll - Thanks for reporting the issue. Can you please confirm how it looks in web run mode ? and also add a quick videos showing both in mac and web run mode. Thanks

**Comment by wenkaifan0720** [comment]
Hi @sgardoll. I just checked on the Mac app and I can see the right panel. Is this issue still happening to you?

**Comment by sgardoll** [comment]
No, I've looked in the latest version and looks like this can be closed.
