### ISSUE TITLE
Page selector --> List of pages --> Folder --> Allow up/down movement of entire folder

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#105]
Currently, folders are sequenced in the order in which those got created. Folder sequence is fixed. Only pages can be drag and dropped. 

Allow up/down movement of the entire folder (along with all pages within that folder along). This will help sequence folders as per the developer's need.

**Comment by Pepino-GR** [comment]
I set this issue as a feature request

**Comment by agreaves** [comment]
Closing this for now as a feature request, but duly noted! We do revisit feature requests so it will be considered.
