### ISSUE TITLE
List of Data Type in Data Type is not persisted

### ISSUE THREAD

**Issue by DarthBrento** [FlutterFlow/flutterflow-issues#1050]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Issue seems similiar to this issue, which is reported fixed: https://github.com/FlutterFlow/flutterflow-issues/issues/651

Setup:
![app state](https://github.com/FlutterFlow/flutterflow-issues/assets/11893450/586a472c-aee1-40f8-b6ef-e15922295d14)
![main DataType](https://github.com/FlutterFlow/flutterflow-issues/assets/11893450/5053e680-1abe-438a-beb8-2e837f12a32c)
![StringCombo](https://github.com/FlutterFlow/flutterflow-issues/assets/11893450/16413f64-011e-4424-b4e6-83cd33d06fc8)

While items is persisted on relaunch, main_list is always empty after app relaunch.

### Expected Behavior

main_list should persist the entries on app relaunch.

### Steps to Reproduce

1. Create new app
2. Setup as described above
3. Setup widgets to display mainstate contents (main_list and items) 
4. Fill mainstate with data -> main_list and items
5. Relaunch App

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojMrqx89grs9c15P2acAxnSQXJkAnRo0Rl8pBZywgfZzzBLN/fPfQPxNWYO3gYX9IJmGMp14e0/z1js7EUPEoHw2bf75++apUZDmWTketVYuTF7WOemhBBcdjJky/0p2NgyZSH/VoL1ID7GaqP+yXHyjdJqWwImo4Sq/LZO4=

### Context

I cant persist my Data Structure in a proper way.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/11893450/6482b694-212c-45ae-b513-d751ddbefa78

### Additional Info

Linked project is a sample project, actual usecase is more complex.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.134
- Operating system and version affected: Win 11
```

**Comment by hariprasadms** [comment]
Hi @DarthBrento - Thanks for reporting the issue. I think this issue can be related to the issue #1039.

**Comment by KlausGrosser** [comment]
Im having the same issue:
ITFXkvHlvIZNrsRE7arbKPlKhSgwFjsFUOdEl9caeE0YG4jpE7Mfder+VGpdcMeKd2w/OVWLnkwH0tb4iNrLIPkEZCmqQoNozYdQWzryWnm6VKqDO6uVOHZCI8JhChG8yqS7rgl+XdZeWGwgw1r/cq3qNleeY8aSfxBlZ7vfcPo=

**Comment by wenkaifan0720** [comment]
Hi all. The data persistency is not guaranteed on instant reload where you are recompiling your app (and also on a remote virtual machine). I tested locally on a Android and iOS emulator and the data is persisted. 

Please see the package we used for persist data for more details: https://pub.dev/packages/shared_preferences.

**Comment by aculebrasj** [comment]
this is not solved @wenkaifan0720:

IT4Wl8nl7otPxLQB1rqJccdFmSQvHGY6U5Irm8N+TRA0F5DpBIwPXfikSEpWZ9+kTHxcL2Kkozkf0++LufzuA+UqHziuRb5x/roBZwLweH2gWpSoPqiJOHN7J9tJJVya08CgkSRABPhoV0IN1GWAHOuXYCnqGJz1O0QSRfyhNoH7o2+qQ0SLb3kNh1JWeC/v

**Comment by vjndr32** [comment]
this issue is still persistent to this date. why has this been marked closed?

**Comment by taggxyz** [comment]
Still facing issues with this...

This is a huge problem for us as we use 'persisted' to understand if a user has dismissed a modal for a new feature update. If this doesn't work, the new feature modal displays every time the user opens the app.

**Comment by snappetite-app** [comment]
Any update on this issue? Having exact the same issue..

**Comment by snappetite-app** [comment]
Able to locate the issue, issue with persistence only occurs when the data type used in an app state is nested within another data type.

Example: DataType1 contains DataType2 as a list -> where DataType1 is used in an App State variable

Issue does not occurs in web, only in iOS (not able to test on Android).

When the data type list is used directly in an app state variable (not nested), the data is persisted correctly.
