### ISSUE TITLE
Relative date between 2 months ago and 1 year ago is not working

### ISSUE THREAD

**Issue by coffeelydev** [FlutterFlow/flutterflow-issues#1051]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the user creates a document with a date between 2 months ago and 1 year ago, the function is not calculating correct.

### Expected Behavior

A document with date 3 months ago, shows 3 months ago

### Steps to Reproduce

1. Create a new page
2. Create documents with date between 2 months and 1 year in firebase
3. Show the documents in the page using relative moment

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcmA05J2odtD0a6JdO9VlmI4Ijt/RJIr0e1+Uis9GYjyO5YUacn7VEpBQvW9S1ZHKEWLuFgx3NLouePtNe0pAxacRr5PyM5iew7McHy/aoSnDqmedEEnGtNVGHKF36SNuyN/IsVvS04/22WMH+qufBTsQJv7Zwh9f6PHaOI=

### Context

<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/38e4acda-2ef7-436e-aac4-333b14979958">
The post date is not correct.

### Visual documentation

<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/5ea1f303-eb58-4104-b684-0b8870d7d931">

### Environment

```markdown
- FlutterFlow version: v3.1 (released Jun 25, 2023
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by kevintonb** [comment]
Hey @coffeelydev , I was not able to reproduce the issue from my end. Kindly double check that timestamps that you're feeding the text widget from your Firestore collection. If you're still facing the issue that you've mentioned please add more information, reproducible steps and a blank project so that we can troubleshoot this further.
