### ISSUE TITLE
Instead of smoothly scrolling up, it seems to jump back to the top abruptly.

### ISSUE THREAD

**Issue by coffeelydev** [FlutterFlow/flutterflow-issues#1052]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 Instead of smoothly scrolling up, it seems to jump back to the top abruptly.

### Expected Behavior

The expected behavior is scroll up smoothly.

### Steps to Reproduce

1. Create a new page
2. Show a lot of documents
3. Start to scroll down
4. Then, try to scroll up

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcmA05J2odtD0a6JdO9VlmI4Ijt/RJIr0e1+Uis9f5ToPJYQe8/6PhdBOfXhTW9mJ02cp14x0MqMuPzlIcE4GxeafoRSzc9XVQzMYGKtV7GTF7iKTmhPM5hRJ2Ks16SZhSZDKrB2L04awGaQHN7KHx3AH5z0DHo8Sq/LZO4=

### Context

This behavior is quite disruptive, especially when trying to navigate through long pages or lists. It hinders the overall user experience and makes it difficult to smoothly scroll to previous content without being redirected to the top.

### Visual documentation

You can try using my project as example. Just open https://app.flutterflow.io/project/coffeely-f-fv1-t0ewmk in run mode, create an account and try to scroll down and up the main page (Feed)

### Environment

```markdown
- FlutterFlow version: v3.1 (released Jun 25, 2023)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by bulgariamitko** [comment]
Can you please provide a video about the issue.

**Comment by coffeelydev** [comment]
https://photos.app.goo.gl/2NWH5GBLJuNznsxs9 I couldn't attach a video here.

**Comment by bulgariamitko** [comment]
@coffeelydev I think this is normal and this is how Flutter works, but I will let the FF team decide.

**Comment by coffeelydev** [comment]
Hi guys! Definitely it is a bug. I record another video https://photos.app.goo.gl/CHSDaQJ8dpt78xv27 and you can see it download Coffeely App on Google Play and use it. I can't scroll up a little bit that return to the top... doesn't make any sense!

**Comment by bulgariamitko** [comment]
Can you create a brand new project and create this issue there please?

**Comment by AvasDream** [comment]
Just for the record, I have the same issue in one of my projects.

**Comment by AvasDream** [comment]
@bulgariamitko did you use a template component from flutterflow for the cards?

**Comment by bulgariamitko** [comment]
@AvasDream no I haven't.

**Comment by agreaves** [comment]
Hi @coffeelydev, thanks for the bug report! Apologies for not following up on this, as I believe we have fixed the issue. You are no longer seeing this behavior, right? Please let me know and I'll close this issue.

**Comment by agreaves** [comment]
Upon closer inspection, this primarily occurs when using Infinite Scroll and loading individual items within the query. If you are using a loading indicator (e.g. `50px` in height) but have a much larger item, this causes the scroll position to be confused once many items load (and also causes far more items than expected to load). If anyone else runs into this, I'd recommend setting the height of the loading widget to something more similar to the expected item widget to avoid this type of issue.
