### ISSUE TITLE
Bug where the right half of the screen won't load

### ISSUE THREAD

**Issue by SpencerJPark** [FlutterFlow/flutterflow-issues#1053]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![flutterflow screenshot 2](https://github.com/FlutterFlow/flutterflow-issues/assets/106630109/d005b290-1d7f-4ce9-b175-a173b45826c3)
![Flutterflowscreenshot](https://github.com/FlutterFlow/flutterflow-issues/assets/106630109/c7bafb5d-df89-4b4b-bbc5-f2174406ccfd)

Part of the screen wont load on my account

### Expected Behavior

The screen normally loads, this started a couple days ago

### Steps to Reproduce

I am unsure what to write here. I have tried logging out and in with no changes to the state of the pages.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I don't have access to that for this

### Context

I can't work on my projects

### Visual documentation

![flutterflow screenshot 2](https://github.com/FlutterFlow/flutterflow-issues/assets/106630109/d005b290-1d7f-4ce9-b175-a173b45826c3)
![Flutterflowscreenshot](https://github.com/FlutterFlow/flutterflow-issues/assets/106630109/c7bafb5d-df89-4b4b-bbc5-f2174406ccfd)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @SpencerJPark, sorry about this issue, this is due to a Flutter regression in the latest version that affects some users depending on their screen. It only happens when zoomed out. You can either zoom back to normal (or as small as you like without causing the issue) or you can use a separate version we created to help fix the issue: https://canvaskit.flutterflow.io. Sorry again!

**Comment by SpencerJPark** [comment]
No worries Alex, thanks for the response-Spencer On Jun 26, 2023, at 9:35 PM, Alex Greaves ***@***.***> wrote:﻿
Hi @SpencerJPark, sorry about this issue, this is due to a Flutter regression in the latest version that affects some users depending on their screen. It only happens when zoomed out. You can either zoom back to normal (or as small as you like without causing the issue) or you can use a separate version we created to help fix the issue: https://canvaskit.flutterflow.io. Sorry again!
