### ISSUE TITLE
Unable to add items to appbar - iPhone 14, iPhone14 Plus & Other Device Sizes

### ISSUE THREAD

**Issue by whobick** [FlutterFlow/flutterflow-issues#1055]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Right now the appbar hit boxes do not properly adjust depending on device size in the FlutterFlow editor. So if I select iPhone SE, the hitboxes are about halfway through the appbar. However selecting larger (iPhone 14, iPhone 14 Plus, etc) I am unable to add anything into the appbar.

### Expected Behavior

The appbar hit boxes should adjust depending on device size so that no matter what device I an viewing, I can still reliably drag items into the appbar.

### Steps to Reproduce

1. Create a blank project
2. Add an appbar into the page
3. Select the iPhone 14 or iPhone 14 Plus device size
4. Try and drag items into the appbar

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkvLl5YZgrs9J1ar2de9WqCE6JUQ5R600sNobbxAjIoDoPJkUac/7alBuTuLmY39lKEWGuDk07vzxkvDhDvoCCyuuQJx+1qlqVwrNXny/aoSqC6qgWHBPBe9MIEyX0J+nhxEkHNVtcVID2UypfOeycz3aGLH4Zwh9f6PHaOI=

### Context

I am unable to drag/add items into the appbar as i always need to adjust the device size.

### Visual documentation

[](https://tella.video/wills-video-dei2)

![CleanShot 2023-06-27 at 12 36 35@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/50713619/5965dacf-33b3-4919-a0ae-893da587ed65)

![CleanShot 2023-06-27 at 12 36 57@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/50713619/591504f2-e720-4e35-a4ea-76f8ab328745)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hi @whobick Thanks for submitting issue. I can re produce the issue.

**Comment by wenkaifan0720** [comment]
Hi @whobick. This will be fixed in our next update. Thank you!
