### ISSUE TITLE
Failed to build iOS app ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:' /Users/builder/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.6.0/ios/Classes/FWFWebViewHostApi.m:203:44

### ISSUE THREAD

**Issue by almacduni** [FlutterFlow/flutterflow-issues#1058]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to build and deploy an application to AppStore, and get this error

Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Archiving com.mycompany.
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: G7779Q4LNC
Running pod install...                                           1,039ms
Running Xcode build...                                          
Xcode archive done.                                          4.9s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
/Users/builder/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.6.0/ios/Classes/FWFWebViewHostApi.m:203:44

### Expected Behavior

The app is built and deployed

### Steps to Reproduce

1. Build 
2. Deploy to AppStore

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I don't have it

### Context

Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Archiving com.mycompany.
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: G7779Q4LNC
Running pod install...                                           1,039ms
Running Xcode build...                                          
Xcode archive done.                                          4.9s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
/Users/builder/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.6.0/ios/Classes/FWFWebViewHostApi.m:203:44

### Visual documentation

<img width="628" alt="Screen Shot 2023-06-28 at 1 51 06 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/71232356/482131e2-b90c-43b6-85a2-e5153a3a0012">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by ndigacin** [comment]
I am dealing with the same issue, frustrating:



Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Archiving com.name.app...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 45VRHV2M6A
Running pod install...                                              9.0s
Running Xcode build...                                          
Xcode archive done.                                          9.8s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
/Users/builder/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.6.0/ios/Classes/FWFWebViewHostApi.m:203:44

Encountered error while archiving for device.


Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1

**Comment by milanhabi** [comment]
+1 
2 Days ago had 5 builds no problem and from yesterday everything failing. Even tried to create all new app (in appstoreconnect.apple.com) / new bundle in FF / new app id ... nothing helped. Will not repeat the screenshot since it's essentially the same as ones provided above.

**Comment by agreaves** [comment]
Hi @almacduni, @ndigacin, and @milanhabi, thank you for the report and information. Looking into this, but please add a Bug Report Code to help me debug this issue (and in general). Thanks!

**Comment by IAmPepsi** [comment]
Same here, I’m also getting an error at the top of it saying (Found build number 9 from TestFlight version 1.0.0)

I have been trying every single solution but non did work.

**Comment by ndigacin** [comment]
@IAmPepsi Did you try to changed the build number to a higher number? I have had that issue before and it was solved by changing the build number to a higher number. Try a higher number that you have not used before in the project's deployment.

**Comment by ndigacin** [comment]
Hi @agreaves ! I am not sure what a report number is. But it seems this one is #1058.

**Comment by IAmPepsi** [comment]
@ndigacin yes I did it from 10 to 40 lol it didn't work, I also tried to deploy it from GitHub and make the changes manually but I always get the exact same error with the exact same issue (it seems like it freezes at the last success deployed build number)

But i noticed something and it's when you go to the Apple developer account ==>Xcode cloud ==> it shows an error message, so I'm not really sure if the issue from Apple or FF.

**Comment by agreaves** [comment]
This should now be fixed! There was a dependency that had updated and was causing issues. Thank you all for the info!

@ndigacin For future reference you can generate a bug report code following these steps: https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements#get-bug-report-code

@IAmPepsi The build number error is a different issue from this one. Please reach out to support if you're not able to find a solution, or if you're very confident its an issue with reproducible steps you can create another GitHub issue. Thanks!

**Comment by IAmPepsi** [comment]
@agreaves the issue has been fixed, thanks a lot 🙏👍

**Comment by liangxiaojuan** [comment]
> @agreaves问题已修复，非常感谢🙏👍

hi hlep
