### ISSUE TITLE
App keeps crashing after reload

### ISSUE THREAD

**Issue by priteshkumbhare** [FlutterFlow/flutterflow-issues#1059]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have set the Expansion option of a Column inside Row from "Default" to "Expanded" i.e.
<img width="117" alt="Screenshot 2023-06-28 at 7 17 16 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/0db77c9e-e4fd-4712-822a-a5004b58bd72"> to  <img width="114" alt="Screenshot 2023-06-28 at 7 17 28 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/cd2845d5-1277-4d28-9814-ea73165cf27d">
After that, the App got crashed. Now that I try to reload it, I am getting an almost blank page where I cannot click any button. I cannot even go back to a previous version
<img width="1439" alt="Screenshot 2023-06-28 at 7 19 48 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/96c955f9-4b92-456d-a87b-b85b1b6b6b07">
My work has been stopped due to this. Please help in either undoing that change or getting me back to my previous version

### Expected Behavior

In the Expansion option, when I click from Default to Expanded and if that option is invalid, ideally I should get a warning and the action should automatically be undone.

### Steps to Reproduce

You can simply click on my project page to see the issue: https://app.flutterflow.io/project/ayu-lyf-for-doctors-938qgi

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Context

I was working on making the 4 Columns inside a Row equidistant and fitting equally inside the screen width. This issue has affected me as I am not able to proceed my work any further till it gets resolvedwith 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/12c48c10-f7a1-4178-aa4a-e52f547085f9

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.10.4
- Platform: Web
- Browser name and version: Google Chrome Version 114.0.5735.133
- Operating system and version affected: macOS Ventura Version 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @priteshkumbhare - Thanks for submitting the issue. I just looked at your project, and I can see that it loads without any issues. Below is the recent snapshots I can see. Does this start working properly on your end?

<img width="350" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/14d76228-8527-49b8-b9dd-f94e292098c8">

**Comment by priteshkumbhare** [comment]
Hi @hariprasadms, I guess you are opening the wrong project. You have opened "AyuLyf" whereas the one which gets crashing is "AyuLyf - for Doctors" i.e. this link: https://app.flutterflow.io/project/ayu-lyf-for-doctors-938qgi

**Comment by hariprasadms** [comment]
The bug report you provided above seems to be from the wrong project. Would you please update the code?

**Comment by priteshkumbhare** [comment]
I could not get the Bug Report Code for any widget of my concerned project, but the field was mandatory hence I used another project(AyuLyf)'s Bug Report Code. I have left it blank now. Please check

**Comment by priteshkumbhare** [comment]
If I may suggest, can you try to make the Expansion option of Column inside Row(in Dashboard page) back from Expanded to Default in the project code There were 4 identical Column widgets in Row. And I set Expanded for the first Column 
<img width="319" alt="Screenshot 2023-06-28 at 8 33 32 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/ee7fb474-c86d-4a50-9e22-b72d99cc7d5f">

**Comment by priteshkumbhare** [comment]
Also thanks for the prompt responses. Really appreciated
