### ISSUE TITLE
fade in issue

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#1060]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

[https://www.loom.com/share/4abd802a16184f0da05e36f620b9a8ef](url)

on my "home current" page, the media display and images seem to have a fade in effect whenever I load the page. I've scoured the page and the code and don't seem to have a fade in effect anywhere. I have spoken with Barry who reviewed the project and confirmed there is no animation set up that should result in this occuring. 

### Expected Behavior

see above

### Steps to Reproduce

1. create app. 
2. add a media display with a default asset of a network image. 
3. turn on cacheing
4. preview the app
5. you will see the image fade in. 
6. if you turn off caching, the image will instant load. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

impacting UI

### Visual documentation

[https://www.loom.com/share/4abd802a16184f0da05e36f620b9a8ef](url)

### Environment

```markdown
- FlutterFlow version: latest
- Platform:mac
- Browser name and version:chrome
- Operating system and version affected: mac
```

**Comment by aaronmt93** [comment]
I believe this issue may be due to the cacheing settings. when I turn off the caching on the images or media displays, the assets will do an instant load as expected.

**Comment by hariprasadms** [comment]
Hi @aaronmt93 - You are correct the fade is because of cacheing settings. _CachedNetworkImage_ widget basically gives a smooth transition while loading image. This is expected behaviour. You can use BlueHash which helps you show a blurred preview of an image whileit is loading.

**Comment by aaronmt93** [comment]
perfect, thank you!

**Comment by aaronmt93** [comment]
Hi @wenkaifan0720, it looks like this now works for the image widget but not for the media display. would we be able to add it to the media display as well?
