### ISSUE TITLE
Show / Hide Chat not keeping choice

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1062]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking the hide chat icon works for a couple minutes then comes back after a specific point

### Expected Behavior

For it to hide until enabled again, or enter project again not when switching pages

### Steps to Reproduce

Disable the show icon, wait a bit (have fun and build in FF) then it will appear randomly 

I observed its happening when changing pages/ entering the component editor 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhefqwItIn7wG15SIY+xWgmU4C1McTZM3lOsYGAAdB4DpEKQcYOLUaXdeOv3ieW5UCmKLgj0Jw8nIkc7hLPkpNQ2sGKF607ViTQyWXTiWMq6lCcyaWnZ6AtFXCB2m56bYnyYlKuthdHA+wE+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Not really affects me but just inconvenience to go back and fourth chaning it

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/98412cb4-5530-4319-9372-2eef0c9f65be)

### Environment

```markdown
- FlutterFlow version: 3,10,4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by kevintonb** [comment]
Hey @Josefpa, thank you for reporting this to us, I was able to reproduce this.

**Comment by victoriahuang1** [comment]
Hi @Josefpa , thanks for the report. This should be fixed in the next deploy!
