### ISSUE TITLE
Launch Map: Cannot use Place Type: Address

### ISSUE THREAD

**Issue by jmart72** [FlutterFlow/flutterflow-issues#1067]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the launch map action, using place type: address does not work. If I use geo coordinates, it works. 

### Expected Behavior

Using Place Type: address pulls up address that is inputed. 

### Steps to Reproduce

1.Create Action: Launch Map
2.Set Place Type to Address
3.Enter value as specific value
4.Enter a valid address
5.Click button that has action to Launch Map
6.Button Launches google maps with address that was inputed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gofkA1qqAKe56hQAkH1x/bZJEl9cab0sbfa2sE7MxPer+VENbT+2qSgtmMGGkmmMEwvTWvtnXKu4CB06raINozKVUbA/iQjqgRYuaO6u8VEckJNFTGH2P16S7kBJvBNFhWCUTw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to create a appointment confirmation page that allows a technician to tap the address field and pull up the clients address on google maps. 

### Visual documentation

![Screenshot 2023-06-29 at 2 28 54 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/127536329/3fe0f1ee-b7d4-4dcd-b666-f2d720fb2ac7)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: IOS 
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @jmart72 - Thanks for posting the issue. I can reproduce the issue.

**Comment by wenkaifan0720** [comment]
Unfortunately the address option only works for Google Maps for now.
