### ISSUE TITLE
Algolia Search Results Being Unnecessarily Limited

### ISSUE THREAD

**Issue by michaelperna** [FlutterFlow/flutterflow-issues#1068]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have had a thread going with one of the support agents and they asked me to come here.

### **Hypothesis:**
The FF Algolia handler is not performing a accepting the full response from Algolia endpoint  because I have 3 Algolia Searches on the same page.

### **Description:**
I have two components that set app state variable. Those states are then used to build a search query for a specific set of documents with a reference or a set of strings. No matter how I configure it I am getting a hard limit of 20 results in FF despite the Algolia API response containing the correct number of records. 

ttps://app.flutterflow.io/project/leks-play-u0kc22?tab=widgetTree&page=HomePage

### Expected Behavior

I should be receiving thousands results with each search but am coming up on a hard limit of exactly 20, no matter how many are actually sent in the Algolia response.

### Steps to Reproduce

1. Create multiple Algolia searches that use state variable as queries
2. View app in test mode
3. Execute an algolia search
4. Results are limited

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjPHl/YVgrs9D7aXTbcdWjiIsC0M2TL07ttYbZxUjIuPtBJh/Y+CkbRdpQsOkYGlhHFmLvH0JzPDMiN/TCPI7CySVY5xi/8xtFg3/RXq8R5i2BsyWXXYmOJtmJ3Kn36arqx5BAPRickI622C6Fe+sVgXZN5+/Zwh9f6PHaOI=

### Context

I am trying to execute a complex query to return documents that are displayed as markers on a map. This is a critical app feature, the ability to filter the app's content in different ways. This worked fine prior to the June 20th release.

### Visual documentation

<img width="403" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4992548/c9a3db1a-9c2f-4ddf-ad56-902fe0a03821">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, iOS, and Android
- Browser name and version: OperaGX LVL4 (core: 99.0.4788.67)
- Operating system and version affected: macOS Ventura 13.3.1
```

**Comment by LucasBene** [comment]
I'm facing an issue with Algolia too. The app I build has feed where i filter posts by location. When users iteract with posts there is no effect on the front end. It looks like there is a bug on communication and sync events between backend and Algolia.

**Comment by Mongoose089** [comment]
Experiencing this as well. When inputting the same search text in Algolia directly, I see the correct number of records. When I use that text in Flutterflow test and run modes, the list it’s limited and doesn’t show all the results. Checking the Algolia API logs, are results are sent back, Flutterflow is just not showing it

**Comment by LucasBene** [comment]
I’ve redesigned whole backend and I’ve separated comments and likes as a separate collections and I call results from separate calls. I still filter displayed content with alveoli’s but there was no solution on how to refresh Algolia and display interactions real time. 

It looks like algolia needs additional refresh to load new results on interactions.

**Comment by michaelperna** [comment]
> I'm facing an issue with Algolia too. The app I build has feed where i filter posts by location. When users iteract with posts there is no effect on the front end. It looks like there is a bug on communication and sync events between backend and Algolia.

I noticed that specifying what data type will be returned from Algolia fixed this issue for me.

**Comment by LucasBene** [comment]
> > I'm facing an issue with Algolia too. The app I build has feed where i filter posts by location. When users iteract with posts there is no effect on the front end. It looks like there is a bug on communication and sync events between backend and Algolia.
> 
> 
> 
> I noticed that specifying what data type will be returned from Algolia fixed this issue for me.

Hmm

**Comment by hariprasadms** [comment]
@michaelperna - Thanks for posting the issue. As per your latest comment, I presume you found a solution for the issue and its working fine. Please correct me if I am wrong. I hope this is something related to missing configurations.

**Comment by michaelperna** [comment]
> @michaelperna - Thanks for posting the issue. As per your latest comment, I presume you found a solution for the issue and its working fine. Please correct me if I am wrong. I hope this is something related to missing configurations.

There is no work around, issue persists.

**Comment by michaelperna** [comment]
Are there any updates on this @hariprasadms ?

**Comment by MrRongoose** [comment]
Any update? Still experiencing a hard limit at 20 results even though Algolia is sending back the full response

**Comment by michaelperna** [comment]
Yes, i still experience the same issue.

**Comment by michaelperna** [comment]
> Any update? Still experiencing a hard limit at 20 results even though Algolia is sending back the full response

Please don't let this go stale, it has never been looked at and is preventing me launching my business!!!

**Comment by michaelperna** [comment]
I am getting really sad about this one @hariprasadms . Will it ever get looked at?

**Comment by MrRongoose** [comment]
bump @vishalagarwal2 @hariprasadms Looking for help on this too. Still occurring

**Comment by vishalagarwal2** [comment]
Hi, I will look into the issue now. If you have a project with a single Algolia search with text output instead of location that would make it significantly easier for us to debug. If you could share a project link of that it'd be great! Thanks!

**Comment by michaelperna** [comment]
@vishalagarwal2 Bug is not about small data quantities. I am fetching full document from Algolia. I need thousands of full documents back per query. I filter markers (documents) on the main page with a query built from button text, facets in the document structure, references, etc. I pass the documents to Google Maps modules to display the markers. Link below. I have several Algolia search queries on the same page that are quite similar. Even with one query, hits (in this case full documents) are limited to 20.

https://app.flutterflow.io/project/leks-play-u0kc22

**Comment by MrRongoose** [comment]
@vishalagarwal2 Fantastic, Thank you! I have a single Algolia Search on this page. You can use query term: "Somerset" . It should return 46 results out of a small collection of 1185 documents. I see that on the Algolia side, but on FF, only 20 return in the GUI

Bug Report Link:
IT4wlcmAuIt1obhb+KryYMJVnj4vIjt8U4InldZ+Sis8GZT0B4kcYs+kfklUOOmqS2NAPGCZqz8X/Mr5kuHXLvEBHAWZGpw9/7VbEQnLfHqiVcWMCK63b0BCMJ5MCWnF3KezgyVTBOtaSFIbw16xOOqiVgTYQJC3ITI4DuaoXdeK2SrDX1iXc2URm05KZDPz

**Comment by vishalagarwal2** [comment]
<img width="977" alt="Screenshot 2023-08-10 at 3 20 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63578295/4a770ce5-fa95-4583-8321-f3c619af765f">
Hey thanks for sharing the project! It seems like Algolia defaults to 20 hits per page (under configuration in index!), find screenshot attached. I suspect this may be the cause of the issue.

**Comment by MrRongoose** [comment]
@vishalagarwal2 Good find! I did notice however if I set that number to 39 or above, I don't see any results returned anymore in the GUI. Is there something I need to add to FF to increment the pagination?

**Comment by michaelperna** [comment]
Yea, I second @MrRongoose . Can we get some advanced options so that we can actually roll through pages @vishalagarwal2 Happy to put in a feature request.

**Comment by michaelperna** [comment]
> @vishalagarwal2 Good find! I did notice however if I set that number to 39 or above, I don't see any results returned anymore in the GUI. Is there something I need to add to FF to increment the pagination?

I also changed the default and now the Algolia Manager returns no results at all.

**Comment by vishalagarwal2** [comment]
Yes, that sounds like a feature request! 

When you say algolia manager doesn't return any results -- is this on Flutterflow or Algolia itself? I tested this on your project @MrRongoose and it seems to be returning 36 results when I search "Somerset"

**Comment by michaelperna** [comment]
> Yes, that sounds like a feature request!
> 
> When you say algolia manager doesn't return any results -- is this on Flutterflow or Algolia itself? I tested this on your project @MrRongoose and it seems to be returning 36 results when I search "Somerset"

@vishalagarwal2 I am not seeing any results now that I have changed the number of hits per page in Algolia. This seems to be a FF issue. 
<img width="330" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4992548/40ed8bfd-dbbb-40b2-a421-7472d53894e7">

**Comment by MrRongoose** [comment]
@vishalagarwal2 
> When you say algolia manager doesn't return any results -- is this on Flutterflow or Algolia itself? I tested this on your project @MrRongoose and it seems to be returning 36 results when I search "Somerset"

On my frontend of FF, if I set that pagination option to anything over 38, I don't get any results. There should be 46 returned for a search of Somerset. I set it to 38 just so I get something back and a more refined search would at least have results. But If I wanted a dataset to return larger than 38 items, nothing appears on screen

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47441524/1cc5f800-c15a-42f4-ba9e-305ab4570086)

**Comment by takashiff** [comment]
Hello @michaelperna, are you still experiencing this issue? I just tested your project and I am getting back 100+ results on each search I have tested. Thanks

**Comment by MrRongoose** [comment]
@takashiff I see more results than I previously have, but I am still missing about 8 as compared to Algolia proper

**Comment by michaelperna** [comment]
Same, I am still missing several thousand results when I do not use geo
fencing.

**Comment by takashiff** [comment]
Hello, do you know how many results you are exactly getting? It looks like there is an upper limit of 1000 on the number of hits you can get from a search based on Algolia's Flutter package. Thanks

**Comment by michaelperna** [comment]
My testing confirms this upper limit. Any chance we can get some work on
that to extend the result limit?

**Comment by takashiff** [comment]
Sorry, unfortunately this is a decision that Algolia has made that we do not have any control over. If you'd like an increase in the upper limit, I would recommend contacting Algolia about that feature. Thank you for your bug report, I'll mark this as closed since I believe we have determined the root of this issue.
