### ISSUE TITLE
Boolean Parameters need to be trigger true before false for initalisation

### ISSUE THREAD

**Issue by benjaminathlan** [FlutterFlow/flutterflow-issues#107]
## Expected behavior (required)
When I add a boolean parameter on widget and I want it to be false by default I should let it false.

## Current behavior (required)
If I want the false value by default, I need to toggle true, then back to false

## To Reproduce (required)

1. Create a widget
2. Add boolean parameter
3. Add this widget in a page
4. Error -> widget does not specify value for parameter displayName.

## Context (required)
I wanted to have a default false value to hide a text in a widget

## Screenshots / recordings
![](https://media.cleanshot.cloud/media/25538/FE66f4oZshpvLHTW2k7uIaXhv0zhVuCrfzXutclW.jpeg?Expires=1667963673&Signature=ApDcUv5w3JyUr9p9tQpJ3zGRe58PDEnBOjKIsD-4ynAIdglv5hMbFIPLf~jMl2H~nq78jpoAmpvpV8hLKpodCc~aFfWhfasysvx6aXRfd1gJRc~kBOyHz17HUpGE0V-0M2t3RhKKcuGYNqLtbRQagwqU-2yp0VKT3fEytmFyTg8yxQKNuv68JK88bt-k1TAfqvEfIl6MRvfbdj085J-Tgk-anv-iiKRtVSlbEpWYI~w9kNFViq78t9MoioTRa-HvCQFyE~lCTJuwxNrdc87S886RT9Qo7GvUyCN0RUaTtVGXW9PIOlXTsAmUfyE6tYqkKP5dDH4xOy0D37nZGFBG~A__&Key-Pair-Id=K269JMAT9ZF4GZ)

![](https://media.cleanshot.cloud/media/25538/FGq0Fmesyp2dqr1O5WZyHE3VZX3ARQujSWdZouue.gif?Expires=1667963712&Signature=OijOdXlqLwF7Pa6Ic5c97DPiJySVA-Ah1448G4urru39pejnEkx~onu~ki-Tr~giDgAEp2BI80yHDUQ3kdN~QYfw5ZE0fMoTip-M8hZKu0Us8XJI7X-SdGhYy2qsvNlBh-L~N2S0RaWD9HaF8o8DspKa0F8W-lhHC9Ek7xoNWq3tkVjA2CUCPm7P6FEa0etXe16l7J8dBPvmhNmmOVFhKKQQ8zJryZpkAD5IW3tVbzI5Fr0uF6W6vrW67Q2zp8b4r~BKswJ58u2UowgYIffIi0IdVmNrVUs9ToLPhQ0g6bbXwzxN4e8EceRzZGcJBb-2DTlFOZEC~MxIBMYPPEaeGw__&Key-Pair-Id=K269JMAT9ZF4GZ)

## Your environment
* **Bug Report Code:**
* Version of FlutterFlow used: v3.0 October 28, 2022 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Mac
* Operating system and version (desktop or mobile): Desktop (Macbook M1 Max : 13.0 (22A380)

**Comment by hariprasadms** [comment]
Hi @benjaminathlan, Thanks for adding this issue. Your steps are bit confusing yet. There are number of ways to adding boolean values to a widget example using constants, app-state value and etc. Could you please add more exact details when you are facing this issue. Adding a screenshot and video will be more helpful to simulate the issue.

Thanks once again :)

**Comment by organicnz** [comment]
Hi @benjaminathlan Benjamin. Yeah, more visual content with the widget tree and what you're trying to achieve would be very helpful. You can use the Loom app to take pics and record :)

**Comment by benjaminathlan** [comment]
Yes, I’ll do.

Benjamin Athlan
+33 (0) 628613434 - Prenons rendez-vous
<https://meetings.hubspot.com/benjamin173>



Le 17 nov. 2022 à 14:57:11, Tarlan Isaev ***@***.***> a
écrit :

**Comment by benjaminathlan** [comment]
Hey, this is the record.

https://www.loom.com/share/dc26a6adafa94150a9e91e0aa5d39730

Benjamin Athlan
+33 (0) 628613434 - Prenons rendez-vous
<https://meetings.hubspot.com/benjamin173>

**Comment by agreaves** [comment]
Thanks for the bug report @benjaminathlan! This will be fixed upon the next release 🙂
