### ISSUE TITLE
RevenueCat not working - Google Play- Version of Depencies

### ISSUE THREAD

**Issue by jmartin39** [FlutterFlow/flutterflow-issues#1070]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On paywall, you can´t buy any new product from Google, because the version of purchases_flutter is older than the new version 5.0.0

### Expected Behavior

New products from Google Play should appear on paywall.

### Steps to Reproduce

In the purchases_flutter version in the pubspec.yaml file is 4.10.2 and it needs to be updated to purchases_flutter: ^5.2.3

In the pubspec.yaml flutterflow file that purchases_flutter version is set to 4.10.2 to resolve this issue RevenueCat said that the new package had to be downloaded and added and the purchases_flutter version needed to be 5.0.0 or higher.

In this realese from Revenuecat, they updates the Android SDK dependency from v5 to [v6] to use BillingClient 5. So it necessary for new products on Google play.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

trying to buy a new product in the internal test from google play, but i cant because this product is new and use another library.

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: v3.1 (released June 29, 2023)
- Platform:Web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by pstatile** [comment]
+1

**Comment by aemelyanovff** [comment]
@jmartin39 Thanks for reporting the issue. I agree the version of RevenueCat used in FlutterFlow is outdates, but it's working fine in my projects. Can you share links to the documents you mentioned that say that you must upgrade RevenueCat for new products?

**Comment by aemelyanovff** [comment]
@jmartin39 Actually never mind, I can confirm that new products don't work with the old `purchases_flutter`. We'll upgrade it to `5.2.3` in the next release. Thanks!
