### ISSUE TITLE
Button loading spinner pushes the button-icon away in an ugly way

### ISSUE THREAD

**Issue by Torkilws** [FlutterFlow/flutterflow-issues#1071]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After tapping on a button with an icon the icon gets pushed to the side almost outside the button. This does not look very good / professional.

Looks like this:
https://gyazo.com/d31c5a5ab28b24cd2ae457dd36011572

### Expected Behavior

After tapping on a button with an icon the icon should temporarily be hidden while the loading spinner is showing.

### Steps to Reproduce

1. Create a page
2. Add a button with an icon
3. Check "Show loading indicator"
4. Add actions that takes a few moments show that the loading spinner is showing, ex. a firestore call.
5. See that the button icon gets pushed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlMmA5c9goblH0LnqcMdqhQAkH1x/bZJEl9caaA8dB4vnO4kIOer+VFFoYM/gdFZIBFKWpEQzzPzlv4XpIMYFF0yAaINo1pF6dwuUVl+WaJipDau0Z3d8AeJbGnKz0aaviAhdCPNYcXssw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Make my app look nice. This is a visual issue that does not look good.

### Visual documentation

https://gyazo.com/d31c5a5ab28b24cd2ae457dd36011572

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.10.4
- Platform: Windows (browser)
- Browser name and version: Chrome (latest)
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @Torkilws. This will be fixed in our next update. Thank you for catching it!

**Comment by Franco98404** [comment]
Is it fixed? I still facing with this issue and in my case when the button is pressed is taking all the width

https://schoolfy365.tinytake.com/msc/ODQ1MTY5Ml8yMTc1NTY3NQ

**Comment by Franco98404** [comment]
I know the problem with the icon is solved but this is similar I think. Can you check the issue @agreaves @bulgariamitko ?

https://www.loom.com/share/c64c30b8647048fda57e1af8021e8f05
