### ISSUE TITLE
App doesn't build after changing authentication from Firebase to Supabase

### ISSUE THREAD

**Issue by Empirome** [FlutterFlow/flutterflow-issues#1073]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I changed the authentication from Firebase to Supabase in the middle of one of my projects. After eliminating all the error messages, I wanted to test the app but it doesn't build anymore with this error message: 

```
lib/auth/supabase_auth/supabase_auth_manager.dart:29:27: Error: The getter 'FFLocalizations' isn't defined for the class 'SupabaseAuthManager'.
 - 'SupabaseAuthManager' is from 'package:[my_app_name]/auth/supabase_auth/supabase_auth_manager.dart' ('lib/auth/supabase_auth/supabase_auth_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FFLocalizations'.
            content: Text(FFLocalizations.of(context)
```
![Bildschirmfoto 2023-07-03 um 20 43 29](https://github.com/FlutterFlow/flutterflow-issues/assets/138522380/b2290fc7-7698-42ba-8967-f4e68402f712)

### Expected Behavior

The expectation is that the error message does not show and the app builds. I have to slightly modify the app in Android Studio to make it work. See section "Additional info".

### Steps to Reproduce

I cannot reproduce with an app starting from scratch.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkfHqx5VNsdtF1c/tbe5FhiMXKW5/TL07ttYbZxUjIuPtBJh/PeLObRJuOOarYGlhHE60gj4GzNb4v87mV8EoaUiBfJhGwodudTqXTXq8RL7WPM6eWEEnMJ5XfxWY4LTYkB5DC7ZeWng931+uPe+ARXTqGZ+/Zwh9f6PHaOI=

### Context

I am trying to build the app.

### Visual documentation

![Bildschirmfoto 2023-07-03 um 20 48 41](https://github.com/FlutterFlow/flutterflow-issues/assets/138522380/d6ba75ab-7962-49f1-88d2-c3da1faf51f1)

### Additional Info

The workaround I'm using is:
1. Download the code from FlutterFlow
2. Open in Android Studio
3. Navigate to lib/auth/supabase_auth/supabase_auth_manager.dart
4. Add import '../../flutter_flow/internationalization.dart'; at the top:

With this modification the app will build. See picture in section "Visual documentation".

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: is this the target platform? Then it's iOS and Android
- Browser name and version: Chrome 114.0.5735.198
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next update.

**Comment by Empirome** [comment]
That was quick, thank you!
