### ISSUE TITLE
Inconsistency when Updating Nested Fields in a Map of a Firebase Sub-collection

### ISSUE THREAD

**Issue by diegoserranobst** [FlutterFlow/flutterflow-issues#1076]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've encountered a peculiar issue that might be considered a bug, involving updating nested fields within a map in a Firebase sub-collection. After making an update to one of these fields, I've noticed that the content of another 'sibling' map field (a field at the same level of the map as the updated field) gets erased completely, which should not happen.

### Expected Behavior

When updating a nested field in a map of a Firebase sub-collection, I would expect only that specific field to be modified, with all other fields in the map remaining intact.

### Steps to Reproduce

1.- Create a new blank Firebase project.
2.- Set up a sub-collection with a map structure including nested fields.
3.- Populate the map fields with data.
4.- Try to update a nested field within one of the maps.
5.- Observe the outcome.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89goeFK187ude5WjWM7GDshRLsvju5HaCs9f5CvOpYUec/6PhduOc+idwl+OWK2p14D3P+KuIfhEOw3GE+tb65/zalQbQnJdz+RR5eTF7q8XHZ5P5lRGG6j0aavuAhQCNJuWGQ/716PfvOsTgjsH77rDHo8Sq/LZO4=

### Context

This issue has significantly impacted the functionality of my application as it deals heavily with managing and manipulating data within Firebase. The unexpected erasure of sibling map fields during updates makes it impossible to maintain data consistency and integrity within the application.

What I'm trying to accomplish is a reliable and predictable method for updating nested fields within a map of a Firebase sub-collection. I expect that when a specific nested field is updated, only that particular field's data should change. Other sibling fields should remain unaffected by the update. The current bug disrupts this expectation and introduces unpredictability into the data handling of my application.

The ability to effectively manage data within Firebase is crucial for the functionality of my application. So, solving this issue is of utmost importance.

### Visual documentation

![u4d109ipcys8nwhgyy705v6vfch0](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/0b35b720-f1b3-4f3b-8d9a-11ed436b0fc2)
![rk7t94bsdpnaiveq2aeb7z5uh6ug](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/f9b73be8-fa24-4594-b359-5e50a9d9d9a2)
![67ejdspkhei36aa46qjwmrf0kodl](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/be4fa2b7-cf65-4956-8a58-dfffbc7518bc)
![s0zo9p2s6457qbvfb0l2r3etamsf](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/86c14be2-f542-4a0a-8d56-e64fb34135d2)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Linux
- Browser name and version: Chrome Version 114.0.5735.198 (Official Build) (64-bit)
- Operating system and version affected: Linux mint
```

**Comment by hariprasadms** [comment]
Hi @diegoserranobst - Thanks for submitting the issue. The above given bug report code is not a blank project. Please create a blank project in which reproduce the issue and send us the project's bug report code. Once you added these details, we can start investigating the issue. Thanks

**Comment by diegoserranobst** [comment]
@hariprasadms I have update the Bug Report Code.

This are:
IT4wz/Hqx89goeFK187ude5WjWM7GDshRLsvju5HaCs9f5CvOpYUec/6PhduOc+idwl+OWK2p14D3P+KuIfhEOw3GE+tb65/zalQbQnJdz+RR5eTF7q8XHZ5P5lRGG6j0aavuAhQCNJuWGQ/716PfvOsTgjsH77rDHo8Sq/LZO4=

**Comment by diegoserranobst** [comment]
@hariprasadms you have to press add

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/4f146812-54d4-4df3-933f-e5e93bfacf90)

Then populate... and final button "BUG".

That button is where the bug is found.

**Comment by diegoserranobst** [comment]
@hariprasadms @wenkaifan0720 Hi, do you see my response?

**Comment by wenkaifan0720** [comment]
Hi @diegoserranobst. I can reproduce this issue. Right now I can see from our generated code that you need to specify all the fields when you are updating a data struct. We will either update our documentation, or change this behavior. Thank you for reporting.

**Comment by diegoserranobst** [comment]
@wenkaifan0720 
The update feature, as it currently stands, is virtually unusable, especially for large applications like the ones I develop. These applications have extensive logic across various sections that update the nested fields. Being forced to specify all the fields every time an update is needed would mean reapplying all the logic with each update. This would result in a significant overhead in terms of both work and resources.

Moreover, I observe that the original design of the feature seems to have been intended to enable field-by-field updates. There is an option labelled "Clear Unspecified Values", which implies the deletion of all unspecified fields - this is exactly the logic that would be needed here. I suspect that this option might always be getting triggered, causing this bug. The issue might be stemming from here.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/681e9efe-dee6-41ac-9105-bae9987d336a)

**Comment by polenvinagre** [comment]
> @wenkaifan0720 The update feature, as it currently stands, is virtually unusable, especially for large applications like the ones I develop. These applications have extensive logic across various sections that update the nested fields. Being forced to specify all the fields every time an update is needed would mean reapplying all the logic with each update. This would result in a significant overhead in terms of both work and resources.
> 
> Moreover, I observe that the original design of the feature seems to have been intended to enable field-by-field updates. There is an option labelled "Clear Unspecified Values", which implies the deletion of all unspecified fields - this is exactly the logic that would be needed here. I suspect that this option might always be getting triggered, causing this bug. The issue might be stemming from here. ![image](https://user-images.githubusercontent.com/129707357/252409204-681e9efe-dee6-41ac-9105-bae9987d336a.png)

Completely agree. I am refactoring a module in my app and I am counting on this feature to work correctly and properly.
Please, do not create "strangers features".
Updating the documentation is not a "correct" way to solve this..
Fix the bug is.
Thanks in advance for the correct handling of this issue.

**Comment by diegoserranobst** [comment]
> Updating the documentation is not a "correct" way to solve this..
That is exaclty that I think.

The current approach seems to be avoiding the problem, which can impact a frequently used function. There may be a need to improve the wording to better convey the issue and potential consequences.

**Comment by wenkaifan0720** [comment]
I completely agree with all your comments above. What I suggested is a temporary workaround. We will definitely fix this issue as soon as we can.

**Comment by diegoserranobst** [comment]
Hi Team,

I'm writing to inquire if there are any updates or a potential timeline for the resolution of this issue. I'm currently involved in a crucial project that is at a standstill due to this problem.

Could you please provide an estimated timeline or any updates that could offer some insight into when we can expect a fix? Your swift response would be greatly appreciated as it would significantly aid in my project planning.

Thank you for your understanding and assistance.

**Comment by wenkaifan0720** [comment]
Hi @diegoserranobst. I am on vacation right now. But don't worry, I have transferred this issue to @agreaves, who also implemented this feature and should be able to fix it sooner than me. Sorry for the delay.

**Comment by diegoserranobst** [comment]
Hi @wenkaifan0720 ,

I appreciate your prompt response, even while on vacation. Thank you for redirecting my issue to @agreaves. I understand that delays can happen and I appreciate the team's effort in working towards a solution.

Enjoy your vacation and I look forward to interacting with @agreaves for a quick resolution of this issue.

Best Regards,
diegoserranobst

**Comment by agreaves** [comment]
Thanks @wenkaifan0720, please get some much deserved rest 😂

We've identified the issue and have a fix which should be deployed on our next release! Thank you so much for your patience 🙂
