### ISSUE TITLE
Missing Link to Discord in the UI

### ISSUE THREAD

**Issue by Julihan** [FlutterFlow/flutterflow-issues#1078]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!

### Expected Behavior

Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!

### Steps to Reproduce

Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!

Do not close issue you haven't worked on just because they are 2 months old!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!

### Visual documentation

Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!

### Additional Info

Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!

### Environment

```markdown
Same as this one: https://github.com/FlutterFlow/flutterflow-issues/issues/868
You have not fixed it!
```

**Comment by bulgariamitko** [comment]
I think you can comment on the same issue and not create a new one. 
Regarding the Discord channel and the community there would be some changes so I guess that's why the links are not yet active and in place.

**Comment by Julihan** [comment]
I did comment on the previous issue, as you would have seen if you took 1min to open the link I added in the description. I can not re-open the previous issue. If you don't look at simple link, I doubt you will look at a 'closed' issue.
>there would be some changes
When? I open this issue 2 months ago. Do I need to wait another 4 months, for a link?

**Comment by wenkaifan0720** [comment]
Hi @Julihan. I checked with our team and the reason we are hiding the Discord link is because we are migrating to our new community and fading out Discord. We will update our documentation to reflect this change. Please join our community instead. Sorry for the confusion.

**Comment by Julihan** [comment]
Ok! Thanks for the reply!
