### ISSUE TITLE
MISSING PERMISSIONS UTILS DART

### ISSUE THREAD

**Issue by l00f00** [FlutterFlow/flutterflow-issues#1079]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the file permissions utils and related dart package are missing and this breacks the functionality of test mode - run mode and the all app.

This issue makes the platform completly unusable for testing and running the app.
Please fix!

### Expected Behavior

test mode and run mode should work

### Steps to Reproduce

1. Try test mode
2. Try run mode
3. Read pubspec yaml, permissions utils package not present
4. Push code to repo or download
5. Check diff with previous version
6. The diff shows .dart and dependencies are deleted

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEel/H14othpb0F1qqJc8BahQMwJ0QlUIInj+0bWRMhNYzxB4l/ZsylVFNLYtTgY3NEAVq0mk4B/+DIiuDDEcY3By6Vb6pD1pRXQQzNUTiVMLqvC6jpOHN6P9FRf0uP0beFmSNTJrJZW3wfwDimDfCNG3qCf9qOYwx5e6fDbOY=

### Context

test and run the app in web browser, this is making the platform unusable to visualize a perfectly working app.

This started happening yesterday afterrefrewshing to ne fl;utterflow version.

### Visual documentation

![chrome_Qr0Z6EvtFv](https://github.com/FlutterFlow/flutterflow-issues/assets/43296799/935001c5-3c74-4625-a629-f12287f7b439)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by victoriahuang1** [comment]
Hi @l00f00 , thanks for the report. This issue will be fixed upon the next deploy.
