### ISSUE TITLE
Test mode AppCheck fails

### ISSUE THREAD

**Issue by loohelen** [FlutterFlow/flutterflow-issues#1080]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

AppCheck fails ONLY on FlutterFlow Test mode. AppCheck works fine on real Android, real iPhone, emulator Android (with debug token) emulator iPhone (with debug token).
I followed the doc (https://docs.flutterflow.io/settings-and-integrations/integrations/firebase-app-check), created an enterprise reCAPTCHA key on Google Cloud console. Entered its key into Firebase AppCheck Web App reCAPTCHA Enterprise provider, entered its legacy key into reCAPTCHA provider and into FlutterFlow. I also generated a debug token on Firebase AppCheck Web App, and entered it into FlutterFlow.
When running FlutterFlow Test mode, I get an error: auth/firebase-app-check-token-is-invalid
In case the following is helpful: looking at Google Cloud console, it says the enterprise reCAPTCHA key "hasn't requested a token in the last 6 weeks"

### Expected Behavior

AppCheck should work with on test mode

### Steps to Reproduce

Create a project
Set up AppCheck according to doc (https://docs.flutterflow.io/settings-and-integrations/integrations/firebase-app-check), including debug token
Try running the app in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si/Ll5YxgrulY15DqdcFr/GUWHHJ7a40wscsZa0kdB4joPLJ/deP7YlhVcOHmYENhHFGJmlsfwPzOj97xN+47CxSbboRzyc9ubTzMTXq8RbaPBqW0SUckI/9QBX6n4ZiVoQpNCNNpSnA82WaQBd+vHnTUGZO/Zwh9f6PHaOI=

### Context

Unable to test app in FlutterFlow test mode once AppCheck is enabled. Real devices, and desktop emulators work without issues

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/52323333/e9db15a3-b623-4514-b28a-472aef8f1c96)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by klyse** [comment]
I have the exact same behaviour. _Sometimes_ disabling App Check in flutter flow solves the issue (and re-enabling it for the code download).

**Comment by klyse** [comment]
@SameerShahzad99 @agreaves not sure why this issue has the tag `closed : project specific`? I cannot use flutterflow at the moment for testing anymore because I'm always getting the app check error:

```
[2023-07-07T19:42:56.872Z]  @firebase/firestore: Firestore (9.18.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unknown]: Fetching auth token failed: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).
```

App Check is not enforced:
![Screenshot 2023-07-07 at 21 38 13](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/0b5d11df-f7ee-4630-b2df-1be861c63598)

reCAPTCHA is configured:
![Screenshot 2023-07-07 at 21 38 01](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/ec989be8-b0ed-40f8-bb11-4973067467d9)

I could imagine that this is because all users apps run on your servers and google / reCAPTCHA blocks such high traffic from one location?

**Comment by klyse** [comment]
Check if you have more than one web project in firebase. FlutterFlow does not handle that well as you cannot select which project it should. Try adding the debug token to all the projects and don't forget to recreate the FlutterFlow firebase config.
![Screenshot 2023-08-02 at 07 58 43](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/b2991e3e-d6f4-459b-97d9-5e141e703abc)

**Comment by rafamessias** [comment]
> 

I have only one Web App in my firebase project, I've done the Regenerate config files and it did not work as well.

**Comment by rafamessias** [comment]
> Did you follow the docs and configure reCAPTCHA?

Yep, everything several times and it doesn't work. When I look at the network tab on browse console, it doesn't send the reCaptcha site key. It seens to be the problem...

**Comment by anorld-droid** [comment]
Here is a console log from my web app, it seems FF sends a bad POST request to firebase for appcheck
![Screenshot from 2023-09-20 07-53-11](https://github.com/FlutterFlow/flutterflow-issues/assets/61829388/e54e151a-406c-4231-a1de-1965f4056271)

**Comment by aemelyanovff** [comment]
Sorry for the slow reply.

I'm unable to reproduce the issue: it works fine for me when I set the "Run/Test Mode Debug Token". The reCAPTCHA token is not required for Test Mode.

Please try the following steps and let me know the results:
* Make sure "Run/Test Mode Debug Token" is set.
* Regenerate Firebase config files, regenerate the debug token in Firebase console, update the token in FlutterFlow, start new Test Mode session.
* Check your browser console. Does it print a message like this? `App Check debug token: <...>. You will need to add it to your app's App Check settings in the Firebase console for it to work.` Is this your token?

@anorld-droid What's in the "Request" tab and what's in the "Response" tab?

**Comment by aemelyanovff** [comment]
Closing the issue as inactive. Please feel free to reopen if you follow the steps above but it still doesn't work.
