### ISSUE TITLE
Multiple Algolia searches in an action isn't supported

### ISSUE THREAD

**Issue by priteshkumbhare** [FlutterFlow/flutterflow-issues#1081]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I query on a SearchBar(TextField), I want to display the length of the Search Results over two different collections: Doctors and Ailments. i.e. if I search "women", I expect 2 integers: no. of results matching "women" in Doctors collection, and the same in Ailments collection. But while putting Algolia Search action at onChange of SearchBar, I see I cannot put 2 Algolia Search and I can input only one collection in one Algolia Search action. Any workaround? Or can we have multiple Algolia Searches in one action? 
<img width="970" alt="Screenshot 2023-07-06 at 10 37 20 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/350881ac-5d28-40a8-91c2-2b087e560c42">

### Expected Behavior

Ideally, we should have two Algolia searches one below another

### Steps to Reproduce

1. Make two firebase collections: doctors and ailments
2. Make a page with a textfield(search bar) and two text below it which display the page state variables doctorLen and ailmentLen
3. My agenda is to display doctorLen and ailment correctly when textfield input changes. So, I put two algolia search actions in onChange of textfield followed by assigning values to doctorLen and ailmentLen which are the length of respective results. But you get an error saying "Multiple Algolia Search actions on a node are not allowed."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl87q3ItOvuFd+KnudsFFgmMRI0McX5Ir1utsewgjGKL1BuwieePSVFpWZ9SraVNcHlmboFoypNWKiobtUsJdIROcbbZZzZNqWDvee2inR6bQDZeaS0ZARO9Rf0C11p2g3SUlIsx2WE492jqmOumuYBHDFOu/Zwh9f6PHaOI=

### Context

I want to display the length of 2 search results(displaying search results is done, length is tricky) which are triggered by change of one search bar

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/66b04008-8c22-4eb9-a1b9-b0398871396d

### Additional Info

Can Custom Action be a way to have multiple Algolia Searches?

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.10.4
- Platform: Web
- Browser name and version: Google Chrome 114.0.5735.198
- Operating system and version affected: macOS Ventura v13.4.1
```

**Comment by coffeelydev** [comment]
It would be very good!!! Actually, I would like to put 2 algolia actions in same trigger with a condition with choice chips component. If user selects one choice chips, I search in an index. If user selects other choice chips, I search in another index.

**Comment by priteshkumbhare** [comment]
Well, that is also another use-case. Btw currently, even when Algolia Search actions are in different branches, it will still give an error

**Comment by SameerShahzad99** [comment]
This implementation is currently not supported in FlutterFlow as mentioned in the error, I'll mark this as a feature request!

Thanks @priteshkumbhare!

**Comment by coffeelydev** [comment]
One suggestion @priteshkumbhare is to create a new collection in firebase with the both of data using cloud functions and then sync with algolia.

**Comment by priteshkumbhare** [comment]
Thank you @SameerShahzad99!
