### ISSUE TITLE
Supabase's table issue in flutterflow

### ISSUE THREAD

**Issue by Cod-heure** [FlutterFlow/flutterflow-issues#1083]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I connected supabase in my flutterflow project. I made a simple schema with users and posts. The problem is, whenever I click on the button "get schema", the names "posts " and "users" are inverted. The post tables contains the column of the users' table and vice versa

### Expected Behavior

I want to have users table with his own column and posts table with his own column

### Steps to Reproduce

1. create a project
2. setup supabase  (follow the youtube video of flutterflow to setup an authentication with supabase)
3. create users and posts table
4. generate schema 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

lmao how am i supposed to do that in yoursetting XD

### Context

I'm just trying to setup authentication, i'm new 

### Visual documentation

![Screenshot 2023-07-07 102319](https://github.com/FlutterFlow/flutterflow-issues/assets/112079086/c429fff4-7e85-4a38-891f-eb0fc24b47bb)
![Screenshot 2023-07-07 102417](https://github.com/FlutterFlow/flutterflow-issues/assets/112079086/8479f377-1846-4edd-9353-6594213c5327)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 11 Home
```

**Comment by hariprasadms** [comment]
Hi @Cod-heure - Thanks for submitting the issue. Please create a new blank project with setups to reproduce the issue and share the project's bug report code. Thanks

**Comment by abqareno** [comment]
i have the same exact problem with my project, the first 2 tables are reversed in the options menu, however in the building menu they are showing correctly.

**Comment by amit8796** [comment]
I have the same issue. I feel this is a cosmetic issue as it did not break any of my backend calls to Supabase tables. The link between table list and it's column details seems to be broken in the Get Schema dashboard page. It's a bit irritating though :)

**Comment by amit8796** [comment]
Sure. Below is the url for a test project that shows the Supabase schema
incorrectly for all tables except the 1st table.

https://app.flutterflow.io/project/test-bed-5nnj7h

I have attached screenshots for your reference.

-Amit

**Comment by vishalagarwal2** [comment]
Hi the issue has been fixed and will be applied in our next deploy!
