### ISSUE TITLE
Firebase fails to load the entire document if one field is set as an integer but the database has a decimal.

### ISSUE THREAD

**Issue by aroberts-snag** [FlutterFlow/flutterflow-issues#1087]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attempting to call `castToType<T>` (located in `schema_util.dart`) on a `double` with the type `int` will not pass the if-check and will not call `toInt()`, instead throwing the error `type 'double' is not a subtype of type 'int' in type cast`.

### Expected Behavior

It should be truncated to integer. Eg 1.234 to 1. This is the standard behavior of web frameworks and javascript and is also noted in the code comments of FlutterFlow itself.

### Steps to Reproduce

1. Create a firebase document with a field value set to a number with a fractional decimal. i.e. 32.25
2. Create a schema for the document, where the subject field is set to `int`.
3. Attempt to serialize the document using a `<collection_name>_record.dart` file by adding a `Query`.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcnfz5Fgobhc0bXuY+9amiE7KXp8aK00sNtuTQIdCYDuBIYiacneYRNoOPalSmxHKEWL8T8xp83Iv9nLMO0qGwisfNVM+aV+ZT3gbFO/aoS6OqiOf3wnI+1NGHKg38K3pxNdLtZiZXhlwDuyPuiyaBPDNLX7Zwh9f6PHaOI=

### Context

This has been causing a recurrent pain point to our team because the backend (cloud functions) is javascript and JS has no  specific integer type. It is too easy for JS to generate a decimal number and insert it into a databse and it will cause an app failure on the frontend which can be as bad as a full-on grey screen (crash).

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118231290/85ac19db-b6e3-4609-bce9-8298625c9af9)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118231290/a07b34f0-8c67-4759-9e84-741838becf1f)
The image above shows a potential fix for this bug. Since  `value.toInt() == value` would only return true and return `value.toInt()` if the value is already an `int` (or a `double` with trailing 0's, which can already be type cast), this is obviously a bug.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Android
- Browser name and version: Google Chrome V114.0.5735.199 (Official Build) (64-bit) (cohort: Stable)
- Operating system and version affected: Android API 33
```

**Comment by agreaves** [comment]
Hi @aroberts-snag, thanks for the report! This check is actually working as intended, and is meant to catch instances where true `int`s are being represented as `double`s (e.g. `1.0`, `2.0`, etc.). It is not meant as a catch-all to automatically truncate or round double values in the database that should be integers.

So for instance, if values are stored as `1.0`, `2.0`, etc. in the database, this will sanitize those doubles as ints as they come in. However, if the values in the database are `1.234`, `32.25`, etc. then this is an error in the generated schema and these fields should instead be set to type `double` and not `int`.

**Comment by isegal** [comment]
@agreaves in this case it does not look like the `if` check is necessary because `1.0 as int` will yield 1 and `1.01 as int` will throw an exception, which mirrors the behavior of the check.

https://dartpad.dev/?id=c805a073158c25afe5fb760239f64e37

This might be in the realm of feature request, but it would reduce us a significant amount of recurring pain.
Specifically, if a document schema defines a value as int, but the actual document stored has a decimal point, currently it leads to either grey screens or an invisible document (due to a thrown exception).

There are cases of course where such strict checks are needed (eg fail-fast), but in other cases where graceful degradation is preferred, auto truncation would be more appropriate. Perhaps a 'strict' on/off switch would provide the best of both worlds, but for now we'll have to maintain our own separate branch to achieve this.

**Comment by isegal** [comment]
Other examples we've faced: A calculation on backend yields a NaN, which gets recorded into firestore doc. The frontend fails to deserialize the entire doc. Ideally we would prefer to gracefully degrade where only the problem field fails instead of the entire doc.
