### ISSUE TITLE
Send SMS - Android main body text format error and iOS "To:" phone number error

### ISSUE THREAD

**Issue by foldingtable** [FlutterFlow/flutterflow-issues#1089]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I added the standard Send SMS widget action and input the required fields with the following:

1. Phone Number: variable <paraContactPhone>, where paraContactPhone is a string with underlying as e.g 4402222222222
2. SMS Body: text combination a. text_a "Hi, I have added you as a contact" and b. text_b, variable <paraContactPhone>  etc

In Android, when the action is pressed the SMS Body’s text format(wrong) the user gets to send is:

<img width="380" alt="08072023_FF Send SMS Error Android" src="https://github.com/FlutterFlow/flutterflow-issues/assets/113984526/24af2568-b41b-4b69-898e-ff928d94c769">

In iOS, when the action is pressed, the SMS Body text’s format the user gets to send is correct, however the “To:”, does not display the phone number but a “widget_paraContactPhone”:

![08072023_FF Send SMS Error iOS](https://github.com/FlutterFlow/flutterflow-issues/assets/113984526/b49d5716-c48b-4e0b-b457-4a8f86d6a710)

### Expected Behavior

Expected Android and iOS output behaviour:

The action should allow the user to send SMS message on the user phone 

1. with the correct variable paraContactPhone i.e 4402222222222
2. and text in the main body as "Hi, I have added you as a contact .... 4402222222222" etc

### Steps to Reproduce

1. create contactDetails page 
2. add a text field "contact phone number"
3. add a submit button
4. create an inviteContact page, add component parameter call "paraContactPhone" 
5. attached an action to the submit button created in 3, which navigate to "invite contact" page and passed the paraContactPhone (set from 2)
6. add "Inivite" button to the inviteContact page
7. attached action Send SMS widget to Invite button, created in 6
8. input the required fields for the Send SMS Widget, so "Phone Number" say +4402222222222 and SMS Body with combination text "Hi, I have added you as a contact ..." and variable paraContactPhone.
9. Run on a real device mode, If the “Invite” button is pressed, the above two issues will appear, (a) Android’s main body’s text format and (b) iOS the “To:” displaying “widget.paraContactPhone” where expectation is to get an actual phone number e.g. “+4402222222222” etc.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvHl2It1mNtK+KXhbu9WiSQ4Mjt/bYJIj+phZCs9f5CvOpYUec/6PhFvXtDnTAhII2G2p14d0euOj9rXKu4EPUuCboBE/qpqSzvyIUyjRK2TF7iCTmhQO/1mIWmO0JirsRZBC/t1dXwD712yG9y9aDXvGOfIOGo8Sq/LZO4=

### Context

The issue leads to an unreadable SMS message in Android and un-send-able text in iOS. I'm trying to allow the user to invite their contacts via SMS.

### Visual documentation

Android

<img width="380" alt="08072023_FF Send SMS Error Android" src="https://github.com/FlutterFlow/flutterflow-issues/assets/113984526/2fc2a00a-e750-4cc9-82c4-70cca5c0dc54">

iOS

![08072023_FF Send SMS Error iOS](https://github.com/FlutterFlow/flutterflow-issues/assets/113984526/f6e2e672-51d4-4bef-a748-08c43f8e417b)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: developed on macOS, issues appeared on Android and iOSv16.5.1
- Browser name and version: Chrome Version 114.0.5735.198 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by SameerShahzad99** [comment]
@foldingtable Thank you so much for submitting this bug, I can reproduce the Android problem so I have marked the bug as confirmed, the team will dig deeper and test further!

**Comment by victoriahuang1** [comment]
Hi @foldingtable , we are already aware of the issue and already have a fix ready to go out with the next deploy.
