### ISSUE TITLE
Toggle, Switches and checkboxes dosent change state/value inside SwipeableStack

### ISSUE THREAD

**Issue by MangaBeats** [FlutterFlow/flutterflow-issues#109]
Toggle, Switches, checkboxes and so on, dosent change state/colors
until i navigate away and back to the page.

I tried to place a switch outside of the SwipeableStack widget and one inside. 
It seems like the SwipeableStack widget dosent update variable state/value on trigger.
It only update the state/value after refreshing the page by navigateing away and back.

https://user-images.githubusercontent.com/32901084/200726145-ae5aade7-f471-458a-b0b0-6cd36a97d074.mp4

**Comment by hariprasadms** [comment]
I can reproduce it. Thanks

**Comment by hariprasadms** [comment]
This should be fixed in latest FF updates. Hence we can close the issue.
