### ISSUE TITLE
Copy and Paste Form Element Action

### ISSUE THREAD

**Issue by Dandare** [FlutterFlow/flutterflow-issues#1090]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to copy and paste a for onChange Action from one field to anoter and it gets pasted as an onSumbit action not an onChange action

### Expected Behavior

It to be pasted as an onChange action - or whatever the source copied action was

### Steps to Reproduce

create a from
create 2 text fields on the form
for first text field create an onChange action
copy the action 
select second field
paste action
the pasted action will be an onSumbit action not onChange

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESksn1sMxgobwG7pPUbvpQhQMjNlx7bZAnktV+WRMhfeuqP5l/ZM7BVFVLYteXS2w/EVqkpDoGw6CPvd7pE8JeE0uaUYRO/5RXQQ3gRnmRVc2bO5eKY3ZBL5ljGnKe1J+j2iUkJsZeV15k2nGQGfCdG3qCf9qOYwx5e6fDbOY=

### Context

It makes it take a lot longer to create forms - as cant use copy n paste action

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Mac
- Browser name and version: Chrome 114.0.5735.198 
- Operating system and version affected: Mac OSX Ventira 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @Dandare - Thanks for submitting the issue. I just tested above steps, but not able to re-produce. It is working as expected in my test projects. Can you please share a quick video showing the issue?

**Comment by Dandare** [comment]
Hi 
Appologies for the slow reply.  I have just retested and it seems to be workin as expected now.
Many thanks for your help
