### ISSUE TITLE
When a file is uploaded in Firebase the filename is wrong

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1091]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a file is uploaded in Firebase the filename is wrong

### Expected Behavior

The filename should be the same as I have in my device

### Steps to Reproduce

1. Add a button
2. Create an upload file action
3. Upload a file
4. Check in the Firebase panel
5. You will be a different name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBazwbfe+uB4kqevfOTERDTuGoS2NMIGf9p2oW06HXhvzpCu5fNT6sf4RYz852egmUWlq7VaqNFJWgZ0FfFtFPIGnF1pi7rRBCOvdtdUIY2F2Pf+m9cCbDH6bFNXoWDa/LZO4=

### Context

I want upload file and maintain the file name

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODQyMzE0NV8yMTcxNzQ0OQ

### Environment

```markdown
- FlutterFlow version: v3.1 released July 6, 2023
- Platform: Web
- Browser name and version: Chrome 114.0.5735.199 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hi @Franco98404, thank you for the detailed bug report! This is actually intentional and has been this way for quite some time, in order to ensure that files are given distinct filenames and avoid any conflicts. We are considering adding an option to "retain" the filename or give a file a custom filename, but this is more of a feature request.

Closing for now, but thanks again for the report!

**Comment by Franco98404** [comment]
> We are considering adding an option to "retain" the filename or give a file a custom filename, but this is more of a feature request.

Please, would be a good option!

**Comment by srh98** [comment]
Another vote for this feature! When a user comes to access an uploaded file, the random file name doesn't make sense to them and they have to rename it.

**Comment by steffenb91** [comment]
+1
