### ISSUE TITLE
Problems with the snack bar when a file is uploading

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1092]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- The loading animation in dark mode is not visible
- The duration of the snack bar is very short

### Expected Behavior

- The loading animation in dark mode should be visible
- The duration of the snack bar should be active until all the files were uploaded

### Steps to Reproduce

1. Add a button
2. Create an upload file action
3. Upload a file
4. See the snack bar

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBazwbfe+uB4kqevfOTERDTuGoS2NMIGf9p2oW06HXhvzpCu5fNT6sf4RYz852egmUWlq7VaqNFJWgZ0FfFtFPIGnF1pi7rRBCOvdtdUIY2F2Pf+m9cCbDH6bFNXoWDa/LZO4=

### Context

I want upload files and I want notify to the user the status of the upload

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODQyMzE1Ml8yMTcxNzQ1OA

### Additional Info

Previously I had a custom action to upload multiples files and added these snack bar

Uploading files:
```dart
      SnackBar(
        content: Row(
          children: [
            Padding(
              padding: EdgeInsetsDirectional.only(end: 10.0),
              child: CircularProgressIndicator(),
            ),
            Text(
              'Uploading files...',
              style: TextStyle(
                color: FlutterFlowTheme.of(context).white,
              ),
            ),
          ],
        ),
        duration: Duration(days: 1),
        backgroundColor: FlutterFlowTheme.of(context).primaryColor,
      ),
``` 

Uploaded file
```dart
      SnackBar(
        content: Text(
          'Success!',
          style: TextStyle(
            color: FlutterFlowTheme.of(context).white,
          ),
        ),
        duration: Duration(milliseconds: 4000),
        backgroundColor: FlutterFlowTheme.of(context).success,
      ),
``` 

As you see I was using the primaryColor and success colors

### Environment

```markdown
- FlutterFlow version: v3.1 released July 6, 2023
- Platform: Web
- Browser name and version: Chrome 114.0.5735.199 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Thanks for submitting the issue. The reproducible steps and expected result is not fully clear. Could you please add bit more details about the issue.

**Comment by Franco98404** [comment]
In the video show the 2 problems:

Timestamp:
0:07 - The loading animation is white so it is not visible in dark mode.
0:20 - I forced a slower connection speed to show the problem is the snack bar disappear after a few seconds, this happens when the user uploads bigger files too.

- The solution for the first problem is to change the loading animation color depending on if it is dark or white theme.
- For the second problem the snack bar should be visible until all the files are uploaded

**Comment by victoriahuang1** [comment]
Hi @Franco98404 , thanks for the report. I was able to reproduce and the issue. It will be fixed upon the next deploy.
