### ISSUE TITLE
api managers '_accessToken' sent with "Token " instead of "Bearer "

### ISSUE THREAD

**Issue by chatch** [FlutterFlow/flutterflow-issues#1093]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is a property '_accessToken' on the ApiManager and the following logic in makeApiCall to but the token in a header:
```
// Modify for your specific needs if this differs from your API.
if (_accessToken != null) {
  headers[HttpHeaders.authorizationHeader] = 'Token $_accessToken';
}
``` 

but it uses then string "Token" instead of "Bearer" so a backend looking for a jwt is going to reject this.

Seems to be related to https://github.com/FlutterFlow/flutterflow-issues/issues/937 ?

### Expected Behavior

Send in proper bearer token form (RFC 6750), just replace Token with Bearer

### Steps to Reproduce

Setup an api call that requires the JWT token to be sent.
Setup a call to that api call on a page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gi87l34p2rsde0a6JcMJVtCMUJj8hRY0/m+0acw4dB7bpBI13PPT7dRZvcMiBagtAP2GGnn8y+KHJv9rXFcYrFwesQ4Ne+JNcEQLxeFyhSrHTPs6edHclJ+BPG2675LesmA9dAPFfWkVn3TmIDeSiZC/fQ5zODjMaQ/yXKq7Jj3fnGBDjKRRrzmNecCfn

### Context

Would like to use this new _accessToken feature to have tokens sent automatically for api calls without needing an action that gets the token and puts it in action output etc.

### Visual documentation

none - just look at api_manager.dart

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chromium
- Operating system and version affected: Linux
```

**Comment by chatch** [comment]
@SameerShahzad99 how is this a feature request and not a bug? can you explain that?

i don't know of any server that will accept the header form "Authorization: Token <...>".  There is no standard for this so surely it wasn't intended?

Needs a fix for this feature to be useful no?

**Comment by chatch** [comment]
its an unfixed bug



24 Sept 2023, 08:47 by ***@***.***:

**Comment by takashiff** [comment]
Hello, unfortunately this does not seem to be a bug. Please replace "Token" with "Bearer" in your code in order to support your needs. The API manager is intended to be used as a framework and should be edited based on the user's specific API needs.

**Comment by chatch** [comment]
it's a bug in flutterflow code.

here's the list of schemes on IANA https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml and on MDN https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes

"Token" of course is not there because it is not supported by any software and has never been. it's likely a hallucination of some kind.

no flutterflow app uses this, unless they've patched the buggy code shown in the description above.

**Comment by takashiff** [comment]
I see, thank you for the article links. That has cleared things up for me.

**Comment by agreaves** [comment]
Hi @chatch, thanks for the bug report! You're correct that using `Bearer` is much more standard, so we'll switch to using that. However, you'll find there are many APIs (often legacy) that use or accept `"Token <token>"` based auth:
https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication 
https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication

Still, you're correct this isn't the standard so we'll fix it!

One important note though, is that by default this token is never used (likely why this hasn't come up before). It was originally present in the code simply for convenience to make it easier if the anyone wanted to modify the code and enable it.

**Comment by chatch** [comment]
> Hi @chatch, thanks for the bug report! You're correct that using `Bearer` is much more standard, so we'll switch to using that. However, you'll find there are many APIs (often legacy) that use or accept `"Token <token>"` based auth: https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication
> 
> Still, you're correct this isn't the standard so we'll fix it!
> 
> One important note though, is that by default this token is never used (likely why this hasn't come up before). It was originally present in the code simply for convenience to make it easier if the anyone wanted to modify the code and enable it.

thanks @agreaves ! this is very helpful. yes very interesting django rest has chosen 'Token' ..

> One important note though, is that by default this token is never used (likely why this hasn't come up before). It was originally present in the code simply for convenience to make it easier if the anyone wanted to modify the code and enable it.

noted :+1:
