### ISSUE TITLE
Icon component parameter cannot be unset

### ISSUE THREAD

**Issue by smn-snkl** [FlutterFlow/flutterflow-issues#1094]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a custom component that receives an Icon as a parameter, you cannot unset the icon in component instances once an icon has been selected. For the regular button e.g. there is an "x" button to unset the field in the properties panel again, but for component parameters that "x" is missing so you can only swap the icon, but never unset it again.

### Expected Behavior

There should be an "x" button like for the icon property of the Flutterflow button component that can be used to unset the parameter again.

### Steps to Reproduce

1. Create new component with "icon" parameter of type "Icon"
2. Drag the component on a page and set an icon for the component parameter through the properties panel
3. Try to remove the previously selected icon from the properties panel of the custom component again

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl8/luI9Oj7xZ7aryLO9Vq2IWNU9+apc0sd4bGA0dCJzuPLMQdvXsQFFDUtClYX9lMESmmTkE/8LxktrXUMFfHAeBboN8zJd2cQ7yfzqnQZOBPKuBPmsnO59UfHas5KWO2xN5D/Vhc3wRwGemIdzIFz7DQeOyImdISq/LZO4=

### Context

We want to create custom button components and still be able to choose the icon property just like with the default button

### Visual documentation

![Screenshot 2023-07-10 at 13 07 07](https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/6c0dcf2a-b149-49e8-b348-cd6f6456939c)
![Screenshot 2023-07-10 at 13 07 26](https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/55289490-ded4-4f3e-8016-986652c3f74f)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: -
- Browser name and version: Chrome
- Operating system and version affected:  -
```

**Comment by hariprasadms** [comment]
Hi @smn-snkl - Thanks for reporting the issue. This is expected behaviour as per the current design. I agree with your point, it is good to have option to clear the icon. I can mark this as a feature request. Thanks

**Comment by hariprasadms** [comment]
Hi! Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!
