### ISSUE TITLE
Weird Issue on when arguments on custom functions are deleted, action panel changes arguments called on it.

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1096]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I deleted an argument from my custom function.
The rest of the arguments that are being passed into that function from the action panel also changes the order of the values assigned to them. 
suppose the functional arguments have these variables in the action panel
1. argument A = variable X
2. argument B = variable  Y
3. argument C = variable Z

if Argument A is deleted.
The Action Panel changes the order of arguments as such.

Argument B gets variable X instead of Variable Y
Argument C gets variable Y instead of Variable Z

This of course is a quick fix but re-assigning them again with correct values. But I have over 7-8 arguments and have to do it multiple times whenever I add or delete this. 

**Video Is Attached for clarification**

### Expected Behavior

If I just delete an argument from the custom function, 
it should just remove that argument without affecting other values being passed to the functions

### Steps to Reproduce

1. Change arguments on custom function
2. the other arguments should stay intact

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whc/qw4hPm+FK7q6JcvlViiMWCDsmU7gv0OxtQis9Gb7nB4YEaeLeRFppTcilSkFlKEWJ8Xkdw+jwv+DxF8JfHzOsRaU5wZdccDyXcEK/aoSXO6iKT0d5Fptjfna106aFkQpQD/tZL2AO2EyEf+nLShDbHZP7Zwh9f6PHaOI=

### Context

https://streamable.com/bfp62k

### Visual documentation

Video added.

### Additional Info

.

### Environment

```markdown
- FlutterFlow version: 3.1 - 7th July
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by FrancoSernaglia** [comment]
I have a very similar problem where I fill an argument with a variable and the other arguments get the same variable too. I dont want the other arguments to get filled with my variable. If I want to change the second argument it happens again.

Note that all arguments have the same variable:
<img width="421" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/b337e812-3a5e-4d23-a5d1-6b02a9390afa">

**Comment by FrancoSernaglia** [comment]
I solved it, the problem was on how I defined my custom action. I was filling a DocumentRef variable in a string argument. That caused the mentioned behavior

**Comment by hariprasadms** [comment]
Hi @Dev-Muhammad-Junaid - Thanks for submitting the issue. I have tested the issue as per above reproducible steps. custom functions arguments update/delete working fine as expected. Not able to reproduce the issue. 

Please share a quick video showing the issue and also a blank project setup with issue details. We can re-investigate the issue once you have updated it with these details. Thanks

**Comment by Dev-Muhammad-Junaid** [comment]
> Hi @Dev-Muhammad-Junaid - Thanks for submitting the issue. I have tested the issue as per above reproducible steps. custom functions arguments update/delete working fine as expected. Not able to reproduce the issue.
> 
> Please share a quick video showing the issue and also a blank project setup with issue details. We can re-investigate the issue once you have updated it with these details. Thanks

Thanks for taking a look. I'll see if this issue still persists. And make a video for you to verify. If not then we can close it
