### ISSUE TITLE
Conflicting definitions in model code for media upload to Firebase through bottom sheet

### ISSUE THREAD

**Issue by farosato** [FlutterFlow/flutterflow-issues#1098]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm creating a profile pic section in a page.
I have a container containing the image.
On the container I define an on tap action that shows the bottom sheet containing the actions to update or delete the profile pic.
I pass the actions as callbacks to the bottom sheet component.
Defining a Firebase upload media action for the change photo action causes a bug in the model code: there are repeated, conflicting definitions for `isDataUploading`, `uploadedLocalFile`, and `uploadedFileUrl`.
Screen attached.
This breaks the app.

<img width="440" alt="2023-07-10 at 19 35 37@2x" src="https://github.com/FlutterFlow/flutterflow-issues/assets/14915211/d63c5a70-08db-472e-bdec-1b7fd57822a9">

### Expected Behavior

I expect the code to contain just one definition of the aforementioned variables.
I expect the app to run without issues.

### Steps to Reproduce

1. Preferably start with a project with Firebase configured
2. Create a page
3. Add a container to the page
4. Add an on tap action to the container that shows a bottom sheet component (any existing bottom sheet component can be used)
5. Define a changePhoto action parameter on the bottom sheet component
6. Create an action that uploads media to Firebase and pass it as the callback changePhoto action parameter to the bottom sheet component
7. Checking the code for the initial page model will now show the repeated, conflicting definitions
8. Testing the project won't work (fails to build)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8kiPLq2492obgA+KqJccFvij4vJjsja7ssluwaTQIdCIzqEoYcfOLebhNWcsyBfwk3PGeJjnsy+c7GhIb2UsIrE0msQaJ/3JVpWjzxXn2nR4inDJagY0RAL9xhfH7D17a3ghBGA+FsdCE/1ziXf96UYC3bNb7QO1gvBP2YBL7JjlaELR/3MyZWwSkXJR7eTI5ODEz25eKMrop5yfj/0w==

### Context

Explained above.
The issue is breaking my app.

### Visual documentation

Attached above.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.198 (arm64)
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by victoriahuang1** [comment]
Hi @farosato , thanks for the report. This should be fixed upon the next deploy.
