### ISSUE TITLE
On Data Change Action incorrect code compilation

### ISSUE THREAD

**Issue by davidoort** [FlutterFlow/flutterflow-issues#1099]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/21220927/ec3850fa-c8bc-454e-a3d8-d5e90ba549c1)
The code generated does not wrap the actions in an async function, so this error occurs.

### Expected Behavior

This line ` )..listen((snapshot) {` should be ` )..listen((snapshot) async {`

### Steps to Reproduce

1. Create a listview
2. Add an on data change action that is asynchronous such as scrolling
3. Observe the generated code or download it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkcrl089NrtxE1qrqcsBaimQwGUALa+dI0tZ+TQ0jF5D4O7MTP+DebkhCQuazaH5IIWL/rE0C0srPjoXpGPQBPgeCbJRz+bl6UBPPbHihVLHREaqoSWtRNJtVG3axyquJpxEnXeNoZVI5wzqyB+mtQT+Cf9qOYwx5e6fDbOY=

### Context

Every time we pull the code there's an error in our project and we have to manually add the async to continue testing.

### Visual documentation

See screenshot above

### Environment

```markdown
- FlutterFlow version: 1.1.88
- Platform:Macos
- Browser name and version: macos
- Operating system and version affected: Multiple OSes from the team
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next update.
