### ISSUE TITLE
Index in List doesn't wprking using textField

### ISSUE THREAD

**Issue by Franco-Cruz-Schoolfy365** [FlutterFlow/flutterflow-issues#110]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

As is shown in both images highlighted in the GREEN color.

## Current behavior (required)

As is shown in both images highlighted in the RED color.

## To Reproduce (required)

1. Put a textField
2. Set as Initial Value the Index as "Index in list"

## Context (required)

I have a text highlighted with green color and a textField with red color and I both have the Index in the list as Initial Value as is shown in image two. But when I ran the app had a strange behavior, as you can see the text widget correctly shows the index but the textField always shows 0.

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/117061503/200781329-17a42b63-73a7-4021-a9af-6d80787acf8b.png)
![image](https://user-images.githubusercontent.com/117061503/200781364-e9fc3b03-4c43-406e-901d-8296b855aeb5.png)

## Your environment

* **Bug Report Code:** IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBay0jF7KuDLMqY8/RVERtUu6oYXxmIk2jnWoW3NLUiIXmG8AFHzicR6pIyqhQFg7MJUyXWozRU/HUACkbeacOQSj6
* Version of FlutterFlow used: 3.0 - 8 November
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Brave [Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)]
* Operating system and version (desktop or mobile): Windows 11 - OS Build: 22621.755 - Version: 22H2

**Comment by wenkaifan0720** [comment]
Hi @Franco-Cruz-Schoolfy365. Currently form widgets (or widgets with a state variable) will not work properly when generated dynamically. Our temporary fix is to raise an error and letting the users know. One possible solution is to wrap the widgets inside of a component and then generate the component dynamically.

**Comment by Franco-Cruz-Schoolfy365** [comment]
It's working with your workaround. Thanks!

**Comment by wenkaifan0720** [comment]
@Franco-Cruz-Schoolfy365 I am glad that it is resolved. And in my opinion the component way is the more Flutter way for implementing such feature.
