### ISSUE TITLE
FB indexes & FB rules incorrectly deployed from FF 

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1100]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, there are two bugs: deploying rules and indexes. Let's break it down:

**Rules**
Deploying Firestore rules from FF often doesn't work as intended. 
When you select all fields as "Everyone":
<img width="987" alt="Screenshot 2023-07-10 at 21 48 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/b5a046c6-dca0-41c0-8bcd-a20a064c8dc4">

And you deploy it to FB:
<img width="280" alt="Screenshot 2023-07-10 at 21 49 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/c657d8d7-4c16-4a3e-9a8c-0538f4e59641">

It removes the rules and only leaves the "read" rule. 
P.S. the rules were there in the first place because I manually added them in the FB console.

Someone pointed this bug out in this post: https://community.flutterflow.io/c/discuss-and-get-help/trouble-creating-document-in-subcollection-from-button-click#comment_wrapper_22221748

**Indexes**
Deploying Firestores indexes often doesn't do anything. I have a pretty large projects with 10s of queries using both filtering and ordering. They are all similar to the one in the image below (multiple filters + one ordering/no ordering):
<img width="313" alt="Screenshot 2023-07-10 at 23 07 15" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/acb44ddd-a011-411a-9bfd-1f7709d27f1e">

However, in the FB console, it looks like this:
<img width="1002" alt="Screenshot 2023-07-10 at 23 08 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/59b88b8d-f7da-47ef-85d1-89f54fcff482">

The indexes haven't been deployed.

### Expected Behavior

Have matching Firestore indexes and rules in both FF and the FB console.

### Steps to Reproduce

1. create new page
2. create ne collection
3. set rules for that collection
4. deploy rules - check if they are the same in FF and FB
5. create complex queries - both with ordering and without
6. deploy indexes - check if all the indexes are in FB that should be there

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

/

### Context

Doesn't allow me to use any complex queries in app.

### Visual documentation

Provided above.

### Environment

```markdown
- FlutterFlow version: v3.1 (released July 06, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 114.0.5735.198
- Operating system and version affected: MacOS Ventura 13.4
```

**Comment by bulgariamitko** [comment]
@tinrunje can you also write your project link here?

**Comment by tinrunje** [comment]
> @tinrunje can you also write your project link here?

https://app.flutterflow.io/project/clubhub-m2iccp is this the link you need?

**Comment by dhust** [comment]
Dang. This caused me to lose 1.5 days of work. This one thing.

At one point I made a subcollection, which was had two single field indexes (come to find out). Then I decided to change it so that it was just a regular root collection. After doing this I was not able to show the documents from the root collection in a listview. It would just show a loading indicator. Didn't make sense. Thanks to this post I went into the Firebase Console and deleted the two related indexes. Now everything works.

On a related note, the Firebase Security Rules were not updating properly.

This was shown in the popup after clicking on the Deploy button, which is not what it should look like.
![deploy_wrong](https://github.com/FlutterFlow/flutterflow-issues/assets/2567117/dbe2d77b-f44a-4045-8578-4b9a5809e3c7)

When the popup went away this is what it showed the rules would be, which is correct. But this one wasn't what was actually being sent to Firebase. I had to copy and paste this directly to the website.
![deploy_right](https://github.com/FlutterFlow/flutterflow-issues/assets/2567117/14966a8d-6884-4677-8af7-16c69253be22)

**Comment by tinrunje** [comment]
> @tinrunje can you also write your project link here?

Could I send it to you privately?

**Comment by bulgariamitko** [comment]
@tinrunje your link will not be accessible publicly, but if you want want to send it here you can send it using the email hari@flutterflow.io

**Comment by tinrunje** [comment]
> @tinrunje your link will not be accessible publicly, but if you want want to send it here you can send it using the email [hari@flutterflow.io](mailto:hari@flutterflow.io)

Ahh okay... I have sent it and tried on my friends computer from a different account and it was accessible, so just for extra safety measures, I'll send it to the email. Thanks!

**Comment by tinrunje** [comment]
> @tinrunje your link will not be accessible publicly, but if you want want to send it here you can send it using the email [hari@flutterflow.io](mailto:hari@flutterflow.io)

Any updates?

**Comment by bulgariamitko** [comment]
The FF team should review and address this issue promptly. Please note that I do not work for FF. My role is limited to confirming the presence of the reported issue. Thank you.

**Comment by victoriahuang1** [comment]
@hariprasadms please let me know if you have received the necessary details for this issue

**Comment by victoriahuang1** [comment]
This sounds like a bug that I already fixed a few days after my last comment, regarding mismatched FF vs actual deployed Firestore rules.

As I don't have the required information to further investigate for this particular project, I will be closing this issue. We can reopen this issue if more information becomes available.
