### ISSUE TITLE
Type 'Data Type' needed in parameters of pages

### ISSUE THREAD

**Issue by KelpME** [FlutterFlow/flutterflow-issues#1101]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

'Data Type' is needed in the dropdown menu for the Parameters of the Pages. Currently we are unable to pass custom Data Types as a parameter to a page.

### Expected Behavior

in the dropdown menu 'Type' when creating a new Parameter for a Page, I'd like to be able to access my custom Data Type.

### Steps to Reproduce

new page
create new parameter
select 'Type' drop down menu

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a, new feature request

### Context

I need to be able to pass my Data Type into a Page as a Parameter.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/100400724/e54f7bea-59ee-40c3-b2ff-dd1d3e445a98)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/100400724/6a09fff9-fece-4306-9984-cbea52ab5dc6)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: pc
- Browser name and version:brave
- Operating system and version affected: all
```

**Comment by SameerShahzad99** [comment]
@KelpME Thank you so much for sharing this, I am considering this as a feature request!

**Comment by FrancoSernaglia** [comment]
I really need this too!

**Comment by KelpME** [comment]
thank you for updating this

**Comment by helixworld** [comment]
This is very much needed

**Comment by lenny991** [comment]
How's this already not a feature? I can't see how some apps work without it.

**Comment by takashiff** [comment]
Thank you for your suggestion. I will pass it along to the team as a possible new feature.

**Comment by univermal** [comment]
I see that this ticket is closed. Has a separate feature request been opened for it? Please share the link.

**Comment by JanikHalder** [comment]
Any updates on this?

**Comment by malbrecht0792** [comment]
Hey just for anyone coming to this that needs a solution...you can specify the parameter as JSON and then when you pass in your data type as a parameter there is an option to convert it to JSON. Then in the page that you need to use the data type (the page with the JSON parameter), when you need to use it you can use the To Data Type option which will convert the JSON to your data type

Happy coding!

**Comment by reno184** [comment]
why this issue is closed ? actually not fixed, and we style have this problem... pass data-typed object from page to page it's still missing option...many thanks
