### ISSUE TITLE
Custom Action with package from pub.dev error at run time

### ISSUE THREAD

**Issue by donpanpete** [FlutterFlow/flutterflow-issues#1102]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a custom function with the dependency from https://pub.dev/packages/mixpanel_flutter

It seems that the object from imported packaged is null.
when call init function it return error.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3589066/d10e3eda-b111-4dc6-a4fb-efeb1530e167)

### Expected Behavior

It should be able to import package.

### Steps to Reproduce

1. Create new custom action.
2. Add mixpanel_flutter: ^2.1.1 in Pubspec Dependencies.
3. import package with `import 'package:mixpanel_flutter/mixpanel_flutter.dart';`
4. add ` Mixpanel mixpanel = await Mixpanel.init("test token",
      trackAutomaticEvents: true);` in action code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z/Hqx89gobxA0bX6ccFvmiM5JjMlR7grmuxRaCgoIYyuOpl/evXsYhFVZO2iYW9EIkSmmkAC0dKJkdrDDvACFASBG4hFzbp2Zjn/WTitUZOBEqiKRWh8RNtMfUCh1rWo2hFRLrd0SiRm7F+qe+yicALvJ4O2IndISq/LZO4=

### Context

To implement analytics tool like Mixpanel.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3589066/916d0549-2668-48c5-ac38-e7fa1c0a5311)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Microsoft Edge Version 114.0.1823.67 (Official build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hi @donpanpete, this issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to a pub dev package and your project, this is classified as a support request and will be closed.

**Comment by prabhatsingh1** [comment]
did you find any solution. also did you tried implementing it via api. Cause I want to know the best method to integrate mixpanel into flutterflow
