### ISSUE TITLE
Set by color not save the "Theme Widget"

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1103]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when creating a Theme widget from an existing widget, the settings for set color by variable are not copied to the Themed widget, meaning have to go through entire app to change a setting, so the concept of theme widgets isnt really working 100%

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/8b58e7d3-867e-4093-bcb3-e84e782f53cd)

### Expected Behavior

would expect to see the set by color variables also copied to the theme, and to any child widgets based on the theme:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/dc2e9513-d45a-47d0-9442-454e413cb3b4)

### Steps to Reproduce

1. add a widget to a page, with color set by variable
2. save as theme widget
3. look at theme widget, the set by variable doesn't exist

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

It would of saved days in re-theming buttons on 79 pages of app.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/8b58e7d3-867e-4093-bcb3-e84e782f53cd)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by aemelyanovff** [comment]
@OldFred2023 Thanks for reporting the issue.

This is the expected behavior. Theme widgets don't support variables - it makes it possible to use them anywhere. Consider using [custom components](https://docs.flutterflow.io/widgets-and-components/custom-components) for your use case.
