### ISSUE TITLE
Missing set color by variable

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1104]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the pageView widget is missing "Set color by variable" option:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/5a4c8a1a-0b85-49b7-a6ba-97783bad5320)

### Expected Behavior

need to be able to fully customise the UI for client complex themes.

Same thing on Expand Widget:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/09ec056f-f98a-4ae2-b3f5-40c016a90be4)

### Steps to Reproduce

This is kind of self explanatory, the pageView widget is missing "Set color by variable" option.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

need to be able to fully customise the UI for client complex themes.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/5a4c8a1a-0b85-49b7-a6ba-97783bad5320)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
I will mark this as a feature request.
