### ISSUE TITLE
Widgets:  Error in property panel

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1105]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you have a long property name for the color option in the slider widget, then the second property vanished off the edge of the screen !

Now you see it:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/3a8a075d-0470-4c29-9195-5a3d9ecfb49a)

now you dont:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/df5a7286-df6b-4de1-b3dd-676ec2732b06)

### Expected Behavior

To be able to see all properties, the panel should be responsive to its content.

### Steps to Reproduce

This is self explanatory i hope.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

in order to change the second value, have to remove the first one for it second one to become visible.

### Visual documentation

see above.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

simular for choiceChips:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/48a5f77b-4f48-4af6-82fa-7e92ab1ff402)

**Comment by sbis04** [comment]
Hi @OldFred2023, thanks for reporting this bug! The issue in Slider and ChoiceChip properties panel should be fixed in the next update. Are you facing this overflow issue in any other widget's properties panel?
