### ISSUE TITLE
[BUG]  Pro Template Firebasse URL variables are reversed 

### ISSUE THREAD

**Issue by DatadudeDev** [FlutterFlow/flutterflow-issues#1106]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Stories are not displaying photos or videos. FIrebase URL is "", despite upload successful. 

### Expected Behavior

The SniffSocial template contains functionality to create user stories (video and photo) and posts (photo)

### Steps to Reproduce

1. create a new project
2. use template SniffSocial
3. Connect firebase (first allow permissions, run all checks for schema and rules, add storage rules, enable email authentication)
4. run a test
5. try to upload a photo and video to the userStories
6. Verify that the media uploaded to Firebase (it did for me)
7. Verify that the userStory document does not contain a strink URL of the media to pass back to the app
8. Verify that the story on the homepage is displaying the default image. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeh8/l5ZRhn7xI1ZDQKPlsjQMwJ0QlUIInj+0bWRMhfLLwPZouf/SkVFNLYtefT25UPk2Ihjsf0+z9jtjPV+0pOgedG9g+yb5XQTvJXnqQWpSTCqire0ZQPNFnBWazy6aRvxRQHLduZU487EOuCPCdG3qCf9qOYwx5e6fDbOY=

### Context

The userStories functionality is broken because the backend call since the 'create document' action:

 defaults storyVideo to 'URL 2' instead of 'URL 3' 
defaults storyPhoto to 'URL 3' instead of 'URL 2' 

reversing these fields solves the issue and images are able to be uploaded to stories. 

### Visual documentation

Not necessary

### Additional Info

Brave browser shields block automated copying of the bug code to the clipboard, with no other method of retrieval. DIsabling the sheilds fizes the issue. 

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Brave 1.52.130
- Operating system and version affected: Windows 11
```

**Comment by victoriahuang1** [comment]
Hi @DatadudeDev , thanks for the report. This will be fixed upon the next deploy.
