### ISSUE TITLE
Tagalog translation not working

### ISSUE THREAD

**Issue by MakeeManalang** [FlutterFlow/flutterflow-issues#1107]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to convert pages in my app from English to Tagalog, but its not working. I think it is not working because Google Translate use the word Filipino and Tagalog, probably that is why it is not working.

### Expected Behavior

I am expecting that if I switch to Tagalog, all of the contents of the pages in my app will be translated from English to Tagalog/Filipino.

### Steps to Reproduce

Tap this-![image](https://github.com/FlutterFlow/flutterflow-issues/assets/65534486/c3999a5c-7762-4450-aab0-bf075f4d600f)
Then you will see this-![image](https://github.com/FlutterFlow/flutterflow-issues/assets/65534486/aa4d541f-0617-4154-ba3b-c22b0bca9403)

Translation is not working. I manually translate some of the words I know.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40heflzItOn7xe+KrLbfpajic5JWYjargRiupBaCosfZT2BLMcec/RVERBTu2jdAlYeFn8q2oW3Oj9kc7tKe0ECzSdbYRaz81XWgHNeDm7VZCOFJWvdUBfPJtPC2aa152vnSZTBMRhL1IBwzqIBuSWY3XUHbG3DEcCDq/LZO4=

### Context

Well it slows me down with my development, because I have to manually translate English to Tagalog. What I wanted to do is to actually focus my self in developing the functionality of the app and leave all the translation to FlutterFlow translation feature.

### Visual documentation

English ![image](https://github.com/FlutterFlow/flutterflow-issues/assets/65534486/b2cc130e-3d71-4152-9e6c-81f2fe648a43)
Tagalog ![image](https://github.com/FlutterFlow/flutterflow-issues/assets/65534486/83dbc1b5-28aa-45b3-9c94-6aec512e19e4)

### Additional Info

Same with Visual documentation

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.10.4
- Platform: Web
- Browser name and version: Google Chrome, Version 114.0.5735.199 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro, version 22H2
```

**Comment by SameerShahzad99** [comment]
@MakeeManalang you have also not shared a blank project with setup, anyways I have tested translating to Tagalog with google translate functionality in FlutterFlow and it appears to be working fine as shown in the screenshot. 
<img width="1154" alt="SCR-20230719-bker" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/ca0ce07f-b0ad-4982-af5a-41993f3d654c">

**Comment by MakeeManalang** [comment]
can you test this on play/run mode? Are you using premium account?

**Comment by MakeeManalang** [comment]
Yes, I am working on it.
