### ISSUE TITLE
Cant use custom colors in Chart widget

### ISSUE THREAD

**Issue by GiovanniBaldo** [FlutterFlow/flutterflow-issues#1109]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to change colors in Charts (for example pie chart colors property), if I set it to a custom color or theme color, the result is that a transparent color is set, instead of the one that I've choosen.
Only recent colors are accepted. manually setting rgb code works too.

### Expected Behavior

It should accept them and custom colors

### Steps to Reproduce

create a new page
add a container or column.
add a chart widget, change it to pie chart, try to change 1st color using theme or custom color. it will be set to transparent

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekfHluIt1pb0C18/caO5KiQMwJ0QlUIInj+0bWRMhfYznP6QcYuPBahFLYteFSnxEH2f+mTgewvzUj+LiU8YnEwWuQJR/yq5XQRXJWl6tMa3QPZGRPEElHZ5MBX6H55iskR1TD7N1LHwO3U2MAvCdG3qCf9qOYwx5e6fDbOY=

### Context

Im just updating colors in my app to use theme / custom colors and not rgb codes

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70816346/79a5cd27-8d19-4625-a50b-4b95942dc188)

### Environment

```markdown
- FlutterFlow version: v1.1.88
- Platform: macos desktop
- Browser name and version: Im using macos app
- Operating system and version affected: maxos ventura 13.4.1 (22F82)
```

**Comment by GiovanniBaldo** [comment]
It seems the problem is only with pie charts

**Comment by kevintonb** [comment]
Hey @GiovanniBaldo , thank you for reporting this issue to us! The issue was reproducible and is identified as a bug.

**Comment by vishalagarwal2** [comment]
Hi the issue has been fixed and will be available on our next deploy
