### ISSUE TITLE
Can't use passed Action

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1110]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you pass an action to a component, there is no way to use it:
<img width="284" alt="Screenshot 2023-07-12 at 19 38 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/23314fcf-2238-4b85-b58d-770eb780b0df">

The action panel doesn't have the action available:
<img width="1055" alt="Screenshot 2023-07-12 at 19 40 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/1adf1653-f7ad-4a14-b73d-593d88734605">

### Expected Behavior

I should be able to use the passed action.

### Steps to Reproduce

1. create new component
2. add a parameter of type "action" on component
3. create a button
4. try using the passed action on the button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

/

### Context

Can't reuse a simple component forcing me to duplicate code and make the app inefficient

### Visual documentation

In the description above.

### Environment

```markdown
- FlutterFlow version: v3.1 (released July 12, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 114.0.5735.198
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by victoriahuang1** [comment]
Hi @tinrunje , this is actually the expected behavior. To use action parameters, you need to call them via the "Execute Callback" action. Please see the documentation for more details: https://docs.flutterflow.io/actions/actions/utilities/execute-callback

**Comment by tinrunje** [comment]
> 

Ahh thanks very much!!

**Comment by smn-snkl** [comment]
Thanks a lot! Can this somehow be used to update the parent page state from within a custom component? I'm struggling with this since I can't pass any parameters right? Is there any way to update parent state from within a re-usable custom component?

**Comment by victoriahuang1** [comment]
Hi @smn-snkl , yes that should work
