### ISSUE TITLE
Can't back to previous page from App Preview

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#1111]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I preview app, I can't back to previous page editing, always force back to index page.

### Expected Behavior

I can back to previous page editing from app preview

### Steps to Reproduce

1.Create a new page different from index page
2.Preview app
3.Back to editing by click the app name top of the page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcqA5YxOtbxY7c/+cvlV/WU5KUB/RJEnk+p7aCosfZT2BLMcec/RVERWcOLgTWNceVmKkWoW0NrViOPLMfU6H0mWR4RAzal5VQvjVkGmMZCpFJWgZGhAQdxTFVSD4bWrhBImJvFvWV4T7DqmDeiWZB7XJ5iwOFQWDq/LZO4=

### Context

I simply want to get back editing page

### Visual documentation

<img width="312" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/da3c24ea-ef5a-4b34-bf1c-44c45ae263ef">

### Environment

```markdown
- FlutterFlow version: V3.1
- Platform: Any
- Browser name and version:Chrome 114.0.5735.198
- Operating system and version affected: macOS 13.4.1
```

**Comment by kevintonb** [comment]
Hey @idea-garage , I was not able to reproduce the issue that you've stated here. Please share additional reproducible steps if you think that the issue is persistent. If not this could be a project specific issue, and if that's the case kindly confirm if you're facing this issue in this thread. And please add a short video demonstrating the issue that you're facing.

**Comment by idea-garage** [comment]
I recorded the behavior of this annoying movement: 
https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/ad4168f7-ddcd-413c-bb9c-4c1a95eeec1f

**Comment by kevintonb** [comment]
Thank you for providing the recording, it is now clear. When you navigate back to the project from the Preview mode, it will load the project as you would load it for the first time. Which would by default have the main entry point page as the active page as it finishes loading. When you launch Flutterflow over the browser, it would launch the preview mode in a new tab, where you can close the tab and resume working back in the previous tab where your project state is preserved. This is a known behaviour and not a bug. However, if you would like to see this feature, please [raise a feature request](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.2-feedback) from your FF builder.

**Comment by idea-garage** [comment]
Oops, I know. Thanks.
