### ISSUE TITLE
Overwrite  ffPrivateApiCall 

### ISSUE THREAD

**Issue by Fastest-Healthtech** [FlutterFlow/flutterflow-issues#1112]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When API is deployed from one FF project to firebase functions via ffPrivateApiCall, it overwrites other API functions from 
ffPrivateApiCall. 
1. I have 1 single firebase project that connected to several ff projects
2. With different API calls in each project and none of those api calls are the same and they are different calls
3. When i try to deploy one FF API to firebase function it overwrites earlier firebase function ffPrivateApiCall from firebase
### Expected Behavior

Redeploy ffPrivateApiCall must not replace existing ffPrivateApiCall

### Steps to Reproduce

1. Create API
4. Deploy API

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjPLlwItPvsdG7rXuc8dFoCYXGDp9RJIF0+5xYCs8JJToPLAUZ8zBM05vZry7d0Fie2eKrz4exvfqhofpKMddZA6VQNll1KVIVz3NRmGtV826C6q3fW1fO9xPfxXG5p6wkQlDANphdV1m6jm6Ou+9FwDcHpP4OkQnJOSLKdeK2SrDX1iXc2URm05KZDPz

### Context

Disables API 

### Visual documentation

Deploy API is FF

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:Android, iOS, Web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by Fastest-Healthtech** [comment]
Any updates on this bug please.

**Comment by Fastest-Healthtech** [comment]
@agreaves @kevintonb @asmengistu @organicnz  Any updates on this Bug please

**Comment by agreaves** [comment]
Hi @Fastest-Healthtech, thank you for the bug report and I really appreciate your patience! This was a tricky situation but there will soon be a way to avoid this issue. Simply give your function a different name in each of the different projects you are deploying private APIs, as seen below:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/91a8ea43-fb5b-455e-aeb7-959595eb865a)

This will be present in our next release. Thanks! 🙂
