### ISSUE TITLE
Importing Pages from Marketplaces have Greyed Out Action Panels

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1113]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to import a page from the marketplace but end up having action panels being greyed out.
Tried refreshing the browser but same results.
Tried different pages and same thing.
**Video Attached for reference**

### Expected Behavior

I expected to see action panels to add actions

### Steps to Reproduce

1. Import a page from marketplace
2. Go to action panel
3. Open Action Panel

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTyfHl25F2octJ+KXUKe5WnjoRM0MCXLhE0ddTZEkYIq7yPJkuYur+VBNdONTiS34/BVL9nj4JwaHJv+zhA8ICFAWcaINo+ZNuZwnKITi6RYjSDpGOREZDN+NPIB260qWzgSNQVdhtc14sw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Adding actions

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/b8690449-aceb-4a0e-a755-27dee876de5d
<img width="1456" alt="Screenshot 2023-07-13 at 5 28 18 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/a9311bda-a90b-47f7-9114-d914e33bbf40">

### Additional Info

Added

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MACOS
```

**Comment by SameerShahzad99** [comment]
@Dev-Muhammad-Junaid Thank you so much for sharing, i was able to reproduce this bug on my end!

**Comment by vishalagarwal2** [comment]
Hi, I have been trying to reproduce the issue and have not been able to. Maybe the previous deploy fixed it. Can you confirm if you are still encountering this issue!

**Comment by Dev-Muhammad-Junaid** [comment]
Hey yes. It's fixed now. I wasn't able to reproduce it again. Thanks
