### ISSUE TITLE
Actions block aren't (fully) duplicated when duplicating pages

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#1114]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I duplicate a page with an action block, updating the action block on one page updates it on the other.

### Expected Behavior

When I duplicate a page with an action block, I expect the block to be duplicated as well, and updating one should not update the other.

### Steps to Reproduce

1. Create new page
2. Add action block with scope = "Page Level"
3. Add an action to the block. E.g. a snackbar with text="Page1".
4. Right click the page, click "Duplicate Page".
5. Open the copy, open the action block.
6. Update the action in the block. E.g. change the text to "Page2".
7. Go back to the first page.
8. Open the action block. Observe that it updated as well.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol/KB249OxLlE7ZDAb/owvyQsQzM4bIZM0O0aQg8aIpPNG4gIZfTBXE9uOP25dglEPmeJjT8fwPOOm9z1VvQoaDibGohx+ZN6SDrdRmC5MaaUOpOWPHNEGshQI3K90KuRrB0mItVZLkIc32aUO+6saBTsQo/6DVgjLvj+EILXrgfuQ0SLb3kNh1JWeC/v

### Context

Duplicating pages breaks action blocks.

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: July 11
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by vishalagarwal2** [comment]
This issue has been fixed and will be applied in our next deploy!
