### ISSUE TITLE
SMS auto verification on Android failing to create user document in firebase

### ISSUE THREAD

**Issue by squidsareevil** [FlutterFlow/flutterflow-issues#1115]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The user first enters their phone number on a phone sign in page.

The user is then navigated to a verification page to enter the code through firebase phone auth. 

On IOS or cases where the user can enter the code manually (phone number on different phone from device) the feature works fine. 

However, on android device with the entered phone number, the instant authentication is triggered. A new user is created in the "Authentication" tab on firebase, but a new user document is NOT created in the firestore database. 

This causes a failed redirect in the app and locks the user out with an "expired" OTP code

### Expected Behavior

It is expected that the instant verification will navigate the user to the home page and create a users document in firebase. The behavior for instant verification should be the same as manually entering the code, but they are not. 

### Steps to Reproduce

1. create phone login page that takes user's phone number and button that triggers "phone sign-in" action
2. create SMS code page that with pincode widget and a button that uses the firebase auth "verify sms" action
3. create home page to be navigated to
4. Run on Android physical device with attached sim card of entered phone number. (not emulator)
5. The auto log-in should trigger. (On my app it will navigate to home and redirect on page load to another page, on others it will not even navigate to home. When user tries to enter the code again manually it will say the code has expired.)
6. Check connected firebase firestore. No new user document is created. 
7. App is stuck in this loop since there is no way to turn off auto log-in

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4szsj104lPn7xK0LqBYPlR/T07NVA9R5Iescp/bxIgGIDzPOw+ZPXsSFRvXselS3NcP0SmmmYEwc7LjuzDLfYoZAWWGKY7zJFIagnNUmCla5OBDbqwe3BtM/JMJlSEyKWnuxN5PtJocmxn1EOMIuivcCvZNYTKImdISq/LZO4=

### Context

My app is currently unusable by android users. They have no way of creating new account. 

My app follows this logic:
login -> sms code -> home -(on page load check name)> getName (additional infor post login)
What happens is the auto login on sms code page navigates to getName. When user enters info, the app is stuck because there is no user document to be updated even though the user is logged in. 

I have tried removing the getName page. This will cause the user to be stuck on the sms code page. When they try to enter the code manually, they will get a snackbar notification that the code is already expired. 

### Visual documentation

Unfortunately, I don't know what would be helpful to show visually. 

### Additional Info

I believe the error could be because of the below:

in the lib/auth/firebase_auth/firebase_auth_manager.dart file. There is the below code. I believe this is outdated since auto-verification is now enabled by default. There needs to be a navigate to home action in verificationCompleted but it is commented out as the code says. 

This doesn't explain why I end up on the getName page or why firebase fails to create a user doc, but at least explains why other users on stuck on sms code page after instant-verification triggers. 

await FirebaseAuth.instance.verifyPhoneNumber(
      phoneNumber: phoneNumber,
      timeout: Duration(seconds: 5),
      verificationCompleted: (phoneAuthCredential) async {
        await FirebaseAuth.instance.signInWithCredential(phoneAuthCredential);
        phoneAuthManager.update(() {
          phoneAuthManager.triggerOnCodeSent = false;
          phoneAuthManager.phoneAuthError = null;
        });
        // If you've implemented auto-verification, navigate to home page or
        // onboarding page here manually. Uncomment the lines below and replace
        // DestinationPage() with the desired widget.
        // await Navigator.push(
        //   context,
        //   MaterialPageRoute(builder: (_) => DestinationPage()),
        // );
      },

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Android
- Browser name and version:
- Operating system and version affected: Android
```

**Comment by squidsareevil** [comment]
Any updates? It has been about a week

**Comment by sbis04** [comment]
Hey @squidsareevil, so sorry for such a late reply. I believe it's just happening on Android devices as by default auto-verify is enabled. I looked into this issue earlier today, it looks like there's no simple way to turn off auto-verify, so I'm thinking of testing with `timeout` set to `0 seconds`. I'll update you once I'm able to test it and if that solution works.

**Comment by squidsareevil** [comment]
Hi Souvik,

Thanks for the reply. Wouldnt it be easier to just have a toggle button in
flutterflow to enable verificationCompleted navigation to Home?

I resolved my own issue by, uncommenting the section in the
lib/auth/firebase_auth/firebase_auth_manager.dart file you guys specified.
This way, people that want to use auto verification still can.

**Comment by sbis04** [comment]
Yup, you are absolutely correct. I'm thinking on that, but the problem would be if any user has other actions defined in the verify page because auto-verify will basically skip all those actions and direct the user to the Logged In page. So, we have to look into whether that solution would work (actually having a toggle inside the `Phone Sign In` action and giving a warning message there should work).

**Comment by squidsareevil** [comment]
Yes, I think your concern is valid. I have also received additional
feedback from my testers that they are still having trouble creating new
accounts (even with me uncommenting the navigator). It still seems like the
auto verification creates an authentication for the user (I see it in
firebase auth with a linked UID), but does not create a user document in
firestore, which leads to error loading the next page. I would assume this
relates to the skipping of any other actions on the pages like you
mentioned.

Please let me know if there's anything else I can assist with the resolving
of this issue as it is preventing Android users from using the app. Thanks!

**Comment by sbis04** [comment]
For now, we are just turning off the auto verification on Andriod to prevent the document creation issue on Firebase. This should be fixed in the next deploy!
