### ISSUE TITLE
Alpha transparent colours not handled correctly for "color from string"

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1116]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you render a Alpha transparent color from the "color from string" setting, then they are rendered incorrectly.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/858fb3b2-613e-44cc-964e-2e69eeb820e4)

bottom sheet barrier as a color
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/d32590cb-a626-4e43-ab1d-71bdfc86498f)

bottom sheet barrier as "color from string" (has pink tint)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/f672f12a-84f8-4b82-bda1-727162a37b69)

### Expected Behavior

for alpha transparent colours to render correctly from "color as string" as they do when normally set.

### Steps to Reproduce

1. create page with two containers
2. create app setting as a string "testcolor" and populate with string (#D32E2E30)
3. fill one with color #D32E2E30 and one from the app setting
4. Note - they render differently
5. link both to bottom sheets with the two color methods as a barrier color
6. note - they render differently.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocBH7pDMbMFAhR4jNlx7bZNEm+1tewEYF5D0B4wpWszsXFdfOO25S3NAHFSbjk0E7tnFi9jpLPAqZQyHbLZN/pB2chXycECgMbKLBpDtYHdBI+dXN2K1yMG72SR/BPRtZV1pig/GSw==

### Context

the app inst showing as designed.

### Visual documentation

as above

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for posting the issue. I can confirm that it is working as intended. The colour from string should be in valid RGB, HEX or HSL formate. Try colour from below link and see how it works. 

https://www.w3schools.com/colors/colors_picker.asp?color=d32020

**Comment by OldFred2023** [comment]
So it is "intentional" that one part of FF supports colours differently to other parts?  seems an odd strategy to design it that way, unless its is a mistake, in which case it is a bug as a bug is not just errors it is anything that deviates away from the intentional design.

And just to clarify, to support alpha transparency which was the point of the issue, it is HSLA not HSL

You can close the ticket, i will use one colour identification method for solid and a different one for transparency.
