### ISSUE TITLE
MediaDisplay widget won't display videos stored in Supabase

### ISSUE THREAD

**Issue by danielsattler** [FlutterFlow/flutterflow-issues#1119]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Captura de tela 2023-07-12 125232](https://github.com/FlutterFlow/flutterflow-issues/assets/84040088/bb4d345e-49cf-40ff-b29c-135be638793a)
![Captura de tela 2023-07-12 124354](https://github.com/FlutterFlow/flutterflow-issues/assets/84040088/1cd9ea21-386c-4bd0-a7f3-062b4520d007)
The videos are being loaded to the page, as seen in the console, but it won't show on the actual display. The images are being shown correctly, but where the videos should be, it's an empty space. This only happens to videos stored in Supabase. The videoplayer widget works though.

### Expected Behavior

The supabase stored videos should appear on the website, not only images, when using the MediaDisplay widget.

### Steps to Reproduce

1. Create new page
2. Place a ListView widget
3. Place a MediaDisplay widget inside the ListView
4. Query a list of URLs from Supabase (The URLs should be of Supabase stored videos and images)
5. Set the MediaDisplay media path to these URLs
6. Publish 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx892pb0E1ZfhYcJVlQMzJDsjU5IRit1uTQIaCKL2O4h/es/CYk5vOd++TENhHGej8VIJp9bIvvLhJvA6HzqcfbY+wboBZA6UVXq8R4SzDKqWYHJAHtJTN3al37W4kQpAFO91cVZh2zvzBOivbB/dJ5+/Zwh9f6PHaOI=

### Context

I'm trying to make a horizontal display of Instagram Stories, both videos and images, but I can get to show the videos using the most efficient way (theoretically) which is the MediaDisplay. This doesn't happen when using Firebase, but switching is not a option right now.

### Visual documentation

![Captura de tela 2023-07-14 104633](https://github.com/FlutterFlow/flutterflow-issues/assets/84040088/4963bcdc-2441-4a0b-a2ef-534a327a99ef)
![Captura de tela 2023-07-12 124354](https://github.com/FlutterFlow/flutterflow-issues/assets/84040088/e79f9e65-9893-4c16-9c99-6cb03f228299)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 114.0.5735.199 
- Operating system and version affected: Windows
```

**Comment by sbis04** [comment]
Hey @danielsattler, sorry for the late reply. I did look at the bug report and the project, but it's hard to test it on our end using this project. Can you please share a simple project with the issue setup? And share its bug report code.

**Comment by danielsattler** [comment]
test project: https://app.flutterflow.io/project/teste-7nuvrk 

bug report code: ITEez/Hqx892pb0D1pPuK8BvvwMzJDsjU5IRit1uTQIaCKL2O4h/dsz7clhBON+6YENhHFSl/U4Ep+jHkc7pCcBcBz6Vbao41s1UdjnJUXq8R4SzDKqWYHJAHtJTN3al37W4kQpAFO91cVZh2zvzBOivbB/dJ5+/Zwh9f6PHaOI=

**Comment by wenkaifan0720** [comment]
Hi @danielsattler. The MediaDisplay widget requires the file extension in the path to determine the type of the media. And even if I force the video player to be used for your videos, the videos couldn't be played. I think the easiest workaround is to use a conditional builder, which chooses between the MediaDisplay widget and the VideoPlayer widget based on the media type.

**Comment by danielsattler** [comment]
But whats wrong with the videos? It's in the right format, I built the widget in the right way. It should be working right? Considering I add ".mp4" to the end of the path. 

I know there are workarounds in this situation, but I was hoping to build my app the efficient and easy way. Can't you guys fix this bug? or are you saying it isn't a bug?

And how would I be able to check the media type to build this condition?

**Comment by wenkaifan0720** [comment]
I am not sure, as the error is coming from the underlying video player package we are using. I tried on Web/Android/iOS and the videos could not be played.

I don't know if this is considered as a bug. Right now we rely on the url path to determine the type of the media and then pass the url to either the image widget or the video player widget.

What I would suggest is to store the image and videos separately, or add the file extension to the end of the url path.

**Comment by danielsattler** [comment]
OK, but are you guys going to try fixing this so I can display Supabase stored videos using the MediaDisplay widget? or will it only work on Firestore?

**Comment by wenkaifan0720** [comment]
Unfortunately I don't think there is a plan for updating the MediaDisplay widget in the short term. I'll add this to our todo list though.
