### ISSUE TITLE
Place Picker not working on phones

### ISSUE THREAD

**Issue by ndigacin** [FlutterFlow/flutterflow-issues#112]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I expect to see a list of places to pick from when I search for a place after taping on the place picker. 

## Current behavior (required)

The place picker makes no place suggestion and shows no result.

## To Reproduce (required)

1. Tap to search for a place
2.
3.
4.

## Context (required)

Being able to search for place and select one is a major feature of my mobile app. Due to this issue, I cannot launch my app. The place picker works on the FF website but does not work on cellphone during test flights.
I really need this to work.

## Screenshots / recordings

![Screen Shot 2022-11-08 at 1 11 12 PM](https://user-images.githubusercontent.com/116641569/200863382-9c08f9dd-e95a-4672-b872-b5f2a2aa9360.png)

![IMG_0001](https://user-images.githubusercontent.com/116641569/200863605-ece094c2-e21b-4ae8-8718-462d003b63a0.PNG)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile): iPhone XR, 8, 12 Max Pro

**Comment by hariprasadms** [comment]
Hello @ndigacin - I have tested this on test flight. I can pick the places. It is working as expected. I suggest check your map sdk settings in your firesbase project and also check correct api keys are set properly.

**Comment by ndigacin** [comment]
Hi Hari. Thank you>

Can you help me with this one? I have the same error message when trying to
build for Apple store.

here is the error message:
Codemagic Deploy OutputFailed Step: Flutter build ipa and automatic
versioning
Found 3 Builds matching specified filters: app=6444242841. Running "flutter
pub get" in clone... Warning: You are using these overridden dependencies:
! rxdart 0.27.4 (0.27.6 available) Running "flutter pub get" in clone...
3.5s 💪 Building with sound null safety 💪 Archiving com.piwo.app...
Upgrading contents.xcworkspacedata Updating project for Xcode
compatibility. Upgrading project.pbxproj Upgrading Runner.xcscheme
Upgrading Info.plist Automatically signing iOS for device deployment using
specified development team in Xcode project: 45VRHV2M6A Running pod
install... 646.7s Running Xcode build... Xcode archive done. 26.5s Failed
to build iOS app Error output from Xcode build: ↳ 2022-11-12 11:48:10.962
xcodebuild[60573:117552] Requested but did not find extension point with
identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
com.apple.dt.IDEWatchSupportCore 2022-11-12 11:48:10.964
xcodebuild[60573:117552] Requested but did not find extension point with
identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for
extension
Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of
plug-in com.apple.dt.IDEWatchSupportCore ** ARCHIVE FAILED ** Xcode's
output: ↳ Writing result bundle at path:
/var/folders/m7/h1mg7c7x40ddjz6mxjxm3htr0000gn/T/flutter_tools.gWkH1Y/flutter_ios_build_temp_dirg8Xxwp/temporary_xcresult_bundle
note: Using new build system note: Planning note: Build preparation
complete note: Building targets in dependency order error: Provisioning
profile "PiwoApp1 ios_app_store 1668105900" doesn't support the Associated
Domains capability. (in target 'Runner' from project 'Runner') error:
Provisioning profile "PiwoApp1 ios_app_store 1668105900" doesn't include
the com.apple.developer.associated-domains entitlement. (in target 'Runner'
from project 'Runner') Result bundle written to path:
/var/folders/m7/h1mg7c7x40ddjz6mxjxm3htr0000gn/T/flutter_tools.gWkH1Y/flutter_ios_build_temp_dirg8Xxwp/temporary_xcresult_bundle
Error (Xcode): Provisioning profile "PiwoApp1 ios_app_store 1668105900"
doesn't support the Associated Domains capability. Error (Xcode):
Provisioning profile "PiwoApp1 ios_app_store 1668105900" doesn't include
the com.apple.developer.associated-domains entitlement. It appears that
there was a problem signing your application prior to installation on the
device. Verify that the Bundle Identifier in your project is your signing
id in Xcode open ios/Runner.xcworkspace Also try selecting 'Product >
Build' to fix the problem. Encountered error while archiving for device.
Build failed :| Step 8 script `Flutter build ipa and automatic versioning`
exited with status code 1

**Comment by hariprasadms** [comment]
Hi @ndigacin - Can you please create a new issue for your last message above?. if place picker issue is resolved. I can close this issue. Thanks

**Comment by agreaves** [comment]
Closing after 2 weeks of inactivity.
