### ISSUE TITLE
Switch Breaks links to user schema

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1124]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Turning off the switch breaks the connections

### Expected Behavior

For it to disable and let users use JWT tokens for login

### Steps to Reproduce

Open a Projects with working autheticaion, create a new login action with JWT disable the create  a new account switch, get (x) amoutn of erros (based on all the user links in your app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShcjc08lgoctf+YffKPlqhQInOUA5apAvlOsbFB4jIp+tOrM+ZMzsYUNKTMPnTH1MM1mWhlMD+v+KhuHXF+0EZDGcfIh80JVAEDniLVi6MMWnDZG8XXNCBdhPfGam0cHQuSUnGMBick4c13GTNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Trying to make a QR code login system with JWT

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/0e2b7a06-5e46-4845-bc86-ddc87c2e1294)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
Hi @Josefpa, It does not look like a bug, when you turn off the create user document option, I will show up the errors on all the places where you have used the properties from the authenticated users if you want to get more information on how it works, you can reach out to the support team on live chat or our email support@flutterflow.io.

**Comment by Josefpa** [comment]
Hey @SameerShahzad99  but lets say I want to use it as a QR code login mechanism with existing users? Then why should I be creating a new user doc, and all the links should still remain the same as its an authenticated user?
