### ISSUE TITLE
Cannot get document property from firestore document reference datatype

### ISSUE THREAD

**Issue by ptmcode** [FlutterFlow/flutterflow-issues#1125]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- I have a firestore collection name 'settings' with field defined.
- I create an app state variable with document reference to collection 'settings' above
- I create an action block to query a document from settings collection then output it with name 'config' then assign it to app state config variable as document reference
- Then on page songSelection load, I call this action block to load data into config variable
- In the same page songSelection, on button 'No' pressed, in the last action step I show snackbar to display property info of config but at this step, there is only one property available for selection it is 'Document ID'. It should show all available fields of settings collection.
- 

### Expected Behavior

- In the same page songSelection, on button 'No' pressed, in the last action step I show snackbar to display property info of config but at this step, there is only one property available for selection it is 'Document ID'. It should show all available fields of settings collection.
- 

### Steps to Reproduce

You can follow in the step Current Behavior as I already described the step there. And you can check my project DontreyProducer for more detail of this issue.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlMmAvM9Pm9sF+KX6YMEwnmEsQ1w2RYE0lsF9Z0wcC7bmG7l/TMnOVBJuOLC0Y3NAf060jmEK+tXemvLPNsInAyqtfIBdwbpcdBXyZGe7R7aRO7qOem5/Dd1RIVS91ruk2CVCIvBuL1oZ22b6fN7JShDAO7r3NUcNRMj/OZOK2SrDX1iXc2URm05KZDPz

### Context

I want to create an app state variable that will hold a firestore document which the config setting for my app. I can find the way to load data into it but I cannot find the way to use any property in that document except Document ID.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6446571/f8036f48-7b92-4d8d-937a-d7feb3149b95)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6446571/0a43beb7-b991-4163-a89a-e7fda4faf201)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6446571/d630ecec-0150-4767-9bcc-da41636a63a3)

### Environment

```markdown
- FlutterFlow version: latest
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @ptmcode - Thanks for submitting the issue. The Document reference call is a future call. It needs a query to fetch the document records from a document reference. Use below option in editor to query the document reference. I can confirm that this issue is not a bug. 

<img width="270" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/79576b36-f861-4d0f-8971-15b39cf312c1">

**Comment by jessieplaydatecare** [comment]
I'm facing the similar issue, I have
1: added the backend query (query collection)
2: set the text filed to get the document's property, for example "name", and it shows right data. 
3: set the text filed to show document id, it didn't show, only show the default value (where it means the document id is null)

I started seeing those issue today
