### ISSUE TITLE
Uncaught Error in state

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1126]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When having a page (A) with data from a supabase query, that lunches a bottom sheet with a delete record action on it, that then redirects to another page (B), the state of page (A) tries to be set, but it has already been disposed of.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/fd15d717-04e7-4ff7-b187-2b17d172c0ab)

### Expected Behavior

for the error to be trapped and handled cleanly.

### Steps to Reproduce

1. Create a page (A) with data on it from a supabase query, and an action to open a bottom sheet.
2. Create the bottom sheet with a button to Delete the record shown on page (A) and navigate to page (B).
3. Then error is thrown though navigation to page B still happens.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8shsrqx5NgoctZ1s7ide9VoGA5KW4/bZIaluwadw8gGJD2PewTe+D4RFNWUu7ma1NEDWH8/TsJw/TKhuztBMBdIgeBbIg7+apXQx7vfHGmRqqKCJCWY3R6P+xhBWaP4Z6vpwpSFNdwd2w53FOyJemAYA/dGO/4Nm0/AvGaNrzJ+HerHiLJDhFJwmo4RUCaTI5ODEz25eKMrop5yfj/0w==

### Context

I have been trying everyway around this i can, everyday for almost a week with no fix or workaround that i can find, so as it is thrown an error and the issues is uncaught, i though it should be reported as a bug as it should be trapped no matter what.

It is stopping me from completing this part of the project as crashes when run on devices.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/edbd9daa-e099-4eda-abde-340dee049fd8)

Not sure can add anything else.

### Additional Info

In context, a query on a page, seems to be trying to update its state.... i assume because the underlay data has changed, but this is supabase not firestore, so the data has no listeners (correct?), but it has been navigated away from and has been disposed.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version: chrome
- Operating system and version affected: andriod
```

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for reporting the issue. I have see the issue in my projects as well. Please add a quick video showing displaying error while navigating the pages. Quick video details can help to speed up the issue's investigation and resolution. Thanks

**Comment by OldFred2023** [comment]
Why is it Stale, you have confirmed its a bug?

**Comment by agreaves** [comment]
Hi @OldFred2023, thank for the bug report! This bug doesn't actually affect app behavior but is good to fix anyway and should not be present in our next release! Thanks!
