### ISSUE TITLE
Textfield maximum characters

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1127]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This might be a bit cheeky and is a feature request really, but can the textfield widget have a maximum characters property added to it, i looked through the community forum and it would appear that people have been wanting this on and off for 2 years.

thanks.

### Expected Behavior

n/a.

### Steps to Reproduce

n/a.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

n/a.

### Visual documentation

n/a.

### Additional Info

n/a.

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for posting the issue. Please add more details about the feature you are talking about. Also provide community links where users are showing interests about the feature. Thanks

**Comment by OldFred2023** [comment]
Restrict the amount of character that can be keyed in to a textfield as a property (without page refresh on every key depression)

I am sure there are loads, just quick search will show you, here are a few in just a quick scan:

https://community.flutterflow.io/c/suggestions-and-feedback/text-input-max-character
https://community.flutterflow.io/c/suggestions-and-feedback/suggestion-for-textfield-max-length
https://community.flutterflow.io/c/discuss-and-get-help/input-max-required-characters

**Comment by Xarjik** [comment]
Bump!

I'd love to have this feature!

**Comment by anthonyfranc** [comment]
Bump!

**Comment by OldFred2023** [comment]
Nudge !

**Comment by aemelyanovff** [comment]
Apologies for the late response, @OldFred2023.

As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!
