### ISSUE TITLE
Custom Functions are all bugging

### ISSUE THREAD

**Issue by ndigacin** [FlutterFlow/flutterflow-issues#1128]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All custom functions are showing errors for no reason. They've been in use and no change has bee mande, and yet they suddenly are showing errors

### Expected Behavior

Custom function should not show error if it's been working for a long time and has not been modified.

### Steps to Reproduce

Validating custom functions

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

addItemsToTheList

### Context

![Screenshot 2023-07-16 at 9 56 57 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/116641569/9655ea82-ae0e-4cdf-88e9-8f9cb42e161a)

### Visual documentation

![Screenshot 2023-07-16 at 9 56 57 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/116641569/077febfc-990a-4d8d-a502-9edffdd6b50d)

### Additional Info

![Screenshot 2023-07-16 at 9 56 57 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/116641569/decc6e5c-2000-46d0-a0d2-584687bca04b)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
@ndigacin I think you just need to re-compile the code again and this warning will be gone.

**Comment by agreaves** [comment]
Closing this as a stale issue. I'm guessing there was a temporary outage and it has since been fixed.
