### ISSUE TITLE
Cannot disable interaction with GoogleMap on web platform

### ISSUE THREAD

**Issue by ouvreboite** [FlutterFlow/flutterflow-issues#1130]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the GoogleMap widget and disallowing the user interaction, the web user can still pan/zoom. The "zoom buttons" are also present, even if "Allow zooming the Map" is implicitly disabled

### Expected Behavior

The user should not be able to pan/zoom the map

### Steps to Reproduce

1. Create a new page
2. Add a GoogleMap widget
3. Disallow "Allow interacting with the map" (and all other features)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkcmAsJFOsdhE1qr+bu9WgSg7Jlt/RJc0sNobbxAjIoDoPJkUaczCQBNoOcjiTW9pKEWIrzoC0a3mvt/LGu4FFw+rfaFzypBybwGVcEm/aoSIPYe8PGhAGfxbGna40rWRsBJ7BNVuWngC1zqYJ/CWbz7qJ5f7Zwh9f6PHaOI=

### Context

I'm putting a map in a scrollable column, so I need the map to be non-interactive, otherwise the scroll event between the map "pan" and the column "scroll" interact together and the scroll experience is uncomfortable for the user

### Visual documentation

All interaction are disabled
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/18073057/34e071d6-ad18-4d87-b62b-a1fbd7ea4964)

The map can still be panned and the zoom buttons are visible
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/18073057/a3003bdc-e29c-40a1-bb09-8508d2f70fb5)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web (Test mode)
- Browser name and version: chrome 114.0.5735.199
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @ouvreboite - Thanks for submitting the issue. I can reproduce that on web platform, users able to interact with map even interaction settings are disabled in the widget settings.

Dev notes - These settings should be false when interactions are disabled in widget setting.

<img width="574" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/e4d8c2ac-588d-4c4d-8987-572808b5f06f">

Default setting values in code view 

<img width="843" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ec89d471-fc66-4e07-89ed-6c5c95a66c9a">

**Comment by agreaves** [comment]
Hi @ouvreboite, thanks for the bug report! In web it seems that `allowZoom` is the field that dictates interaction, so I'm making sure it's also set to `false` if `allowInteraction` is set to `false`. So this issue should be fixed upon the next release. Thanks again!
