### ISSUE TITLE
duplicate collection in Flutterflow

### ISSUE THREAD

**Issue by braddy79** [FlutterFlow/flutterflow-issues#1133]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using Firebase with Flutterflow. 

All was working well until yesterday. I have a collection named menu_groups and a collection named location_groups. 
In the db overview (front end of Flutterflow), menu_groups no longer shows. Instead, there are 2 location_groups. Somehow it seems menu_groups has been renamed and conflicts now with location_groups. I added a new collection called location_group ('group'). This was auto renamed as location_groups. 

I have tried deleting the location_groups but it then displays the user collection schema when I select the second (remaining) location_groups collection. 

In firebase (not flutterflow), it is still showing expected menu_groups and location_groups. 

<img width="958" alt="Screen Shot 2023-07-18 at 06 59 41" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20486807/8fc699fc-017f-4142-a5b2-5595740db85c">
<img width="782" alt="Screen Shot 2023-07-18 at 07 00 48" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20486807/6c03cf19-e20f-499d-af1a-300d3ff891ae">
<img width="944" alt="Screen Shot 2023-07-18 at 07 01 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20486807/47f13007-fa4c-4aa6-9323-2fa14d8d7063">

### Expected Behavior

Normal schema setup and management is expected

### Steps to Reproduce

Select the location_groups collection and you can see it also selects the duplicate. It shows the users collection schema. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

unknown

### Context

I cannot commit changes so this bug is stopping development of the app. 

### Visual documentation

![Uploading Screen Shot 2023-07-18 at 06.59.41.png…]()

### Environment

```markdown
- FlutterFlow version: 1.1.89
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: Mac
```

**Comment by braddy79** [comment]
Any update please?

**Comment by kevintonb** [comment]
Hey @braddy79 , we would need reproducible steps that we can follow to recreate this issue in a new project. The issue you are facing seems project specific. If you think that this is a bug, kindly share the steps to reproduce the issue more elaborately. Please also share the bug report code from a new blank project where you have reproduced this issue :)

**Comment by braddy79** [comment]
Hi, thanks for your reply. It is my understanding that FF doesn't allow duplicate collections? Also, I don't know what or why this happened so not possible to reproduce the error. Is it possible for you to analyse the error your side and see how this could have happened?

**Comment by wenkaifan0720** [comment]
Hi @braddy79. You are right. This shouldn't be happening in the first place and is a bug on our end. I am going to fix the issue in your project first so that you can continue working on your project. You could see some project errors afterwards but they should all be relatively easy to fix. 

Do you recall any specific operation that lead to this issue? This could really help us identifying the issue. I haven't been able to reproduce the issue yet.

**Comment by braddy79** [comment]
Hi,

No need.  I rolled back to a much earlier version and am updating it now.

Regards,  Steve

**Comment by wenkaifan0720** [comment]
Okay. In that case, I will close this issue for now. I think this issue is happening under some rare instances which we haven't been able to reproduce on our end. I'll keep an eye on this issue. Thank you!
