### ISSUE TITLE
Error on loading page: related with StreamBuilder. "Unexpected null value"  

### ISSUE THREAD

**Issue by FrancoSernaglia** [FlutterFlow/flutterflow-issues#1139]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page which used to have a backend query but I have removed the backend query and an error occurs. Without a backend query, on page load, it shows the following error:

<img width="165" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/463baa68-7cae-4d86-9ffa-6ab6ec627469">

 this is the console messages: 
<img width="309" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/43b6a504-10bc-4699-bb06-413a1d731a47">

It seems related to a UsersRecord but the page doesnt have any query now. And, there is no widget using any variable related to the query.

### Expected Behavior

To load the page normally without error and no quering.

### Steps to Reproduce

1. Create a page
2. Create backend query
3. Allow caching
4. Delete backend query
5. Load the page in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okvLlx85grs9G1s/AacFvryQQKVgkR78ricpBZywgfZzzBLN/fPfQPhduXfHhTAlifVmmp14G087sk/GSD/ECYU6bc65azLh2ZQKXIHGnWr2TF7qoOXwkEfFnG3a+5KSRgyJAFNRaLGQu6meqFtyydz/DJ4zRDEQwSq/LZO4=

### Context

I want to load my page.

### Visual documentation

Feels that here is the problem: (the cache settings are remaining afterwards I delete the backend query)

<img width="315" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/9156956f-83a7-40ce-9d9d-019e01eaa1df">

Note that ViajesRecord is my previous query

I tried query again but with Users collection, deleting the query and it deletes the cache setting. though, it didnt happened with Viajes query whose cache settings remain.

### Additional Info

<img width="192" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/c597a461-f757-47b5-b956-c7b293714b1c">

### Environment

```markdown
- FlutterFlow version:  v3.1 3.10.4
- Platform: Test Mode
- Browser name and version: Google Chrome
- Operating system and version affected: Windows 11
```

**Comment by FrancoSernaglia** [comment]
If I want to query again and enable cache I cant select my old cache configuration. I dont known if this intended or not. 
<img width="180" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/373cda2b-5918-453d-aa5a-a88acc1d59f6">

**Comment by bulgariamitko** [comment]
@FrancoSernaglia , I think you can't select the cache value because of the different data types.

**Comment by FrancoSernaglia** [comment]
okey, though, I dont want that page to have a query anyways. I just was trying to see what the problem could be. Now I have decided to create a new page and just copy what I had into the new page. The error disappeared.
