### ISSUE TITLE
Difference between API Call test menu and Run / Web mode

### ISSUE THREAD

**Issue by benjamin-carriou** [FlutterFlow/flutterflow-issues#114]
## Expected behavior (required)
I'am trying to make an API call to query a graphql API.

## Current behavior (required)
It's works in the API call test menu but it's doesn't works in Run / Web mode.

## To Reproduce (required)
In fact, this is the query send from API call test menu (works):

```
{
  "query": "mutation {  channelCreate(    input: {      currencyCode: \"EUR\"      defaultCountry: FR      name: \"test3aa\"      slug: \"test3aa\"    }  ) {    channel {      id      isActive      name      slug      currencyCode      defaultCountry {        code        country      }    }    errors {      code      field      message    }  }}"
}
```
Here, the request send from the Run / Web mode:

```
{
  "query": "mutation {  channelCreate(    input: {      currencyCode: "EUR"      defaultCountry: FR      name: "jaja"      slug: "jaja"    }  ) {    channel {      id      isActive      name      slug      currencyCode      defaultCountry {        code        country      }    }    errors {      code      field      message    }  }}"
}
```

Here, the no escaping of double quote (ex: `name: \"test3aa\"` => `name: "test3aa"`) cause the problem and return from the server the following error because the request is malformed:

```
{"errors": [{"message": "Unable to parse query.", "extensions": {"exception": {"code": "str", "stacktrace": []}}}]}
```

## Context (required)
It is confirmed by Abel it is a bug but any news about the resolution of this bug from Circle ...

More info here => https://community.flutterflow.io/c/bugs/difference-between-api-call-test-menu-and-run-web-mode#comment_wrapper_12185081

## Your environment
* Version of FlutterFlow used: latest
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: Brave 1.44.112
* Operating system and version (desktop or mobile): Linux Ubuntu Bookworm

**Comment by michaelmcroskey** [comment]
+1, this is an issue affecting me too. Specifically when sending JSON payloads where e.g. the product size or description has `"` as a measurement indicator. Would appreciate a fix :)

**Comment by aemelyanovff** [comment]
Fixed, quotes in API bodies are now escaped.
