### ISSUE TITLE
Share Action bugged when using Arabic as Primary language

### ISSUE THREAD

**Issue by Abd-elr4hman** [FlutterFlow/flutterflow-issues#1140]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

setup:
- I use arabic as primary language of my app... that led to the direction of all text in my app being RTL.

on what devices does issue appear:
- the issue appears only on ios devices.

when does the issue appear:
- whenever i click the share button in my application ( uses the share action )... all text appear inverted.
![asgag](https://github.com/FlutterFlow/flutterflow-issues/assets/87248009/d62a69db-6cf0-4a92-83dd-cebb8cbe803e)

### Expected Behavior

the share action should not show inverted text on ios device

### Steps to Reproduce

1. make arabic the primary language of the app. 
2. create a share action.
3. try to share any dummy text.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTh/Lqw8p1rt8F+KXudexFpD8WI0MbWoIzlO1Ca0kdB4joPLJ+d8nOaVtCXbXhSmlhHGGYnkYC+truhvzDVvpfZA2Bf6ly1ql2VhfjXXq8RYvWCcywOXF8M/1TIBWhyLbYkBUnWcZfSUIh60OEBe+tYHfaCZ+/Zwh9f6PHaOI=

### Context

I want to give my users the ability to share a certain link. 

On IOS devices the text on the iphone share bottom sheet appear inverted.

### Visual documentation

![asgag](https://github.com/FlutterFlow/flutterflow-issues/assets/87248009/c1ad42e0-61a5-4551-be0f-56172e47643c)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: IOS
- Browser name and version: CHROME
- Operating system and version affected: IOS 15.7 and above
```

**Comment by bulgariamitko** [comment]
I do not think this is a FlutteFlow issue. This looks more like a Flutter issue.

**Comment by hariprasadms** [comment]
Hi! Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritise feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!
