### ISSUE TITLE
Overlapping Text when using FF Preview App

### ISSUE THREAD

**Issue by wizehawk** [FlutterFlow/flutterflow-issues#1141]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I am using the Flutterflow Preview App on Android. On my computer the run preview looks fine but on the Flutterflow Preview app it looks like on the picture I have attached to Visual Documentation. I have it in a container with inf width and height then in a column. In the text widget (which is wrapped in the column) I have it set to 400-normal and I have tried all 3 expansions, changed font type and size and even tried defining the pixel range. This happens on all my pages.

### Expected Behavior

Not have my text overlapping each other when using the app.

### Steps to Reproduce

1.  Create a page
2. create a container
3. create a column
4. set column to infinite width and height,
5. create text and have it wrapped in the column.
6. text is set to 400-normal
7. do a test run - everything looks fine.
8. open Flutterflow Preview App on my Samsumg A70 and run it there and then all text is overlapping.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvLq25Ngrt9f7q6JcMFF9ToUCDt9bJIni+thYCs9GYjyO5YUacn4SFVpZ9zjYwhtKEWJkXwCwP+PjuDmU/UoaE6ub4Bn1LVUUQ7gbFu/aouVPbiWXGpSJ/NPfmrD3J+r3RNDALZtLV417E73Gd6WTXTsO7H6Zwh9f6PHaOI=

### Context

I have just started using Fluterflow and now I will not keep making the app until this is resolved. I don't want to put in a lot of time and effort and submit it to the stores if the text looks like that.

### Visual documentation

![360113115_10160681155096421_4024532439090110948_n](https://github.com/FlutterFlow/flutterflow-issues/assets/139025679/e6ea1dda-5140-4de5-9735-c5b93bd5ced4)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Windows Desktop and Samsung A70
- Browser name and version: Chrome 115.0
- Operating system and version affected: Androind 11.0
```

**Comment by wizehawk** [comment]
Can anyone help?

**Comment by SkillsUni** [comment]
Hi there,
I have the exact same issue. 
Would like to get some help with this.

**Comment by wizehawk** [comment]
> Hi there, I have the exact same issue. Would like to get some help with this.

Hi, I found out it is a bug in the app. Instead of using the app use the link it creates. I just email the link to myself so  I can click it on my phone.
