### ISSUE TITLE
Rebuilding current page via Update Widget State does not update Page Parameters

### ISSUE THREAD

**Issue by FlyingFlambe** [FlutterFlow/flutterflow-issues#1142]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If a user assigns a page parameter a value from a Firestore document, updates that document, then updates the widget state via rebuilding current page, the page parameter is not updated with the new document value.

### Expected Behavior

The page parameter is updated with the new Firestore document value after the document is updated and the widget state is updated.

### Steps to Reproduce

1. Create a new page and new Firebase project with Firestore initialized.
2. Connect the Firebase project to the Flutterflow project.
3. Create a collection and a document with a variable that includes a string data type.
4. On the FF page, add a page parameter that holds a string value.
5. Create a local page state variable. This can be anything as long as there is a page state variable so we can rebuild the page.
6. Add a text and button widget.
7. Connect the text value to the page parameter variable.
8. Set up the button so on tap, it updates the Firestore document's string value.
9. Add a second action that updates the widget state so the page is rebuilt.
10. Create a second page with a button that navigates to the page we just created.
11. For the page parameter, connect it to the document string value.
12. Set the second page as the default homepage.
13. Test by running and clicking the homepage button. It should display the initial document string value. If you press the button on the following page, it updates the document value and rebuilds the page. If done correctly, the document's value will be updated, but the text string will not be.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjsmB5ZJ1oeFJ+KXuavpvvGMQM0MBX5Ir1utvGBEdIpTuP4oQe8j+aXdWXc+FdG5iDFabsE8CpujVvYXLIfkFNkiZUaV607h2YAGWfHutVbKsDJbpVUBBJNNPGkCX3J6FmgpAB7BeSXgA6k+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I'm trying to allow users to edit variables like name, bio, summary, datetimes, location, etc. When its updated in the Firestore document, that updated data is not displayed which causes confusion.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/22328598/7119b7c9-ffc9-445e-8ba4-63e7b0ce07c6

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Windows 11
- Browser name and version: Microsoft Edge
- Operating system and version affected: Windows
```

**Comment by kevintonb** [comment]
Hey @FlyingFlambe , I have tried to reproduce the issue that is mentioned here with all the listed steps but was unable to do so. This could be due to a number of reasons, the bug was either transient and it no longer appears or this could be a project specific issue. But for more clarity, if you are able to reproduce this issue, kindly create a blank new project where this can be found and setup, and share the bug report code along in this thread so that we can have a closer look.

**Comment by agreaves** [comment]
Hi @FlyingFlambe. I am closing this issue as it is stale. However, I believe there's a misunderstanding of how the page parameter works. It's not a dynamic document, but a fixed document you pass in once. If you want live updates from the current state of the document, you must load the from a Firestore query, not a page parameter document. Hope this helps!
