### ISSUE TITLE
In actionFlow, add more than one loop action cut the end UI and block the next actions

### ISSUE THREAD

**Issue by MickaLamotte** [FlutterFlow/flutterflow-issues#1143]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an action flow that create document based on string in 4 list. To achieve this, I need 4 loop for iterate in those list and create all document expected. I have add my first loop which work well but when I add the second loop, the Action Flow Builder show some bugs (the last action is cut in the middle and the line vertical in the first loop container comes out of it)

### Expected Behavior

I just need to call 4 loop in a row to create my documents and at the end redirect to my HomeScreen.

### Steps to Reproduce

1. Open an action flow On Tap on any element
2. Add one loop with random action in it (Alert for exemple) with simple condition of loop exit.
3. Copy the action loop
4. Pastes it after the first loop
5. See the UI bug with the bottom of the loop container "cut" with no add option available 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8jf34VOxLRG1s7xbexKmmA7QkgkTLJEoetxc0gbfe/4Pe0MPcn4VBJuXcyzaH1Ue1H/p3wG0vuNvd79V/kEZASqfNh8zZZIVRPPbEa5b63WPJeCYkR6BeVXf1Say7uF2R1vKttZW04611yXOOmvbz2Cf9qOYwx5e6fDbOY=

### Context

I want to create document for each item in 4 differents list so I have too loop in my list to access every item for create my documents.

### Visual documentation

Pic 1 : Only one loop
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130373763/57428712-3f58-47d1-b8f4-beac375f89d5)

Pic 2 : Second loop added after the first one
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130373763/09131dee-9897-4d4b-af2e-d4852eafe771)

Pic 3 : The bottom Action flow is cut with no option available
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130373763/b1eb7189-c23b-41ff-b9ec-34a20147bc1a)

Pic 4 : The first loop have his "line" pass throught the container
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130373763/f7201353-76cd-4b89-897c-a51f82738409)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Sidekick 114.49.1.34655
- Operating system and version affected: Windows 11
```

**Comment by matias-pzr** [comment]
When nesting loops the situation gets worse. This is 3 loops inside 1 loop inside 1 conditional inside a periodic action. Some + buttons completely disappear.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/140118804/73f42591-9094-4465-8f28-1fb3ec298aab)

**Comment by victoriahuang1** [comment]
Hi @MickaLamotte , thanks for the report. We have found a bug on our end, and this will be fixed upon the next deploy.

**Comment by Alex-Onyeka** [comment]
Hi... I am facing the same Issue now... If I add the first Loop, it works perfectly. But when I add the second loop, on the same action, it doesn't work. Please what should I do?
