### ISSUE TITLE
TabView Icon without text breaks

### ISSUE THREAD

**Issue by programad** [FlutterFlow/flutterflow-issues#1145]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you have a tabview with three tabs only with icons (without labels) and align them horizontally so they can render nicely on the edit mode, it breaks on run mode.

Here is the edit mode:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1039567/c36bc2a8-6f86-4952-af1d-aa33365deec3)

Here is run mode:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1039567/5491b9f6-f874-4c48-abb8-3f1cc30da0e3)

### Expected Behavior

The expected behaviour is not throwing exceptions when using only icons and they should align nicely even without labels.

### Steps to Reproduce

1. Create a tabview with three tabs
2. Use only icons on the tabs, no labels
3. Align them horizontally so they can  be nice in edit mode
4. Run the app.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl8j1sIxOj7xD1aXide9ammUXJVg4apc0stluZxEoIpznBuwcdeOlQE9uUs+iaVNcJlqZ+HwEwezQj+D1U+w3PU6dfKp91KtcbRXOe2inVYynC7W0ZUZCJ8BWCkCm0MGngxFvKuliLloX22WyGPKibAzDBOu/Zwh9f6PHaOI=

### Context

I am trying to create a band profile with a list of members.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1039567/ade9e5ac-8c55-4160-bf0f-ae908f882ab8)

### Additional Info

It is simple enough to reproduce.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: debug mode
- Browser name and version: Opera One(version: 100.0.4815.54) (arm64)
- Operating system and version affected: MacOS Ventura
```

**Comment by wenkaifan0720** [comment]
Hi @programad. This should be fixed in our next update. Thank you for reporting!
