### ISSUE TITLE
Failed Build both Appstore and Googleplay with Codemagic Deployment

### ISSUE THREAD

**Issue by dao1235** [FlutterFlow/flutterflow-issues#1146]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

App store build error log:

Codemagic Deploy Output
Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Resolving dependencies...
+ _flutterfire_internals 1.3.2 (1.3.4 available)
+ archive 3.3.7
+ args 2.4.2
+ async 2.11.0
+ auto_size_text 3.0.0
+ boolean_selector 2.1.1
+ cached_network_image 3.2.1 (3.2.3 available)
+ cached_network_image_platform_interface 1.0.0 (2.0.0 available)
+ cached_network_image_web 1.0.1 (1.0.2 available)
+ characters 1.3.0
+ checked_yaml 2.0.3
+ cli_util 0.3.5 (0.4.0 available)
+ clock 1.1.1
+ cloud_functions 4.3.2 (4.3.4 available)
+ cloud_functions_platform_interface 5.4.2 (5.4.4 available)
+ cloud_functions_web 4.5.2 (4.5.4 available)
+ collection 1.17.1 (1.17.2 available)
+ convert 3.1.1
+ crypto 3.0.3
+ csslib 0.17.3 (1.0.0 available)
+ csv 5.0.1 (5.0.2 available)
+ cupertino_icons 1.0.5
+ easy_debounce 2.0.1 (2.0.3 available)
+ equatable 2.0.5
+ fake_async 1.3.1
+ ffi 2.0.2
+ file 6.1.4 (7.0.0 available)
+ firebase_core 2.13.1 (2.15.0 available)
+ firebase_core_platform_interface 4.8.0
+ firebase_core_web 2.5.0 (2.6.0 available)
+ firebase_messaging 14.6.2 (14.6.5 available)
+ firebase_messaging_platform_interface 4.5.2 (4.5.4 available)
+ firebase_messaging_web 3.5.2 (3.5.4 available)
+ flutter 0.0.0 from sdk flutter
+ flutter_animate 4.1.1+1 (4.2.0 available)
+ flutter_blurhash 0.7.0
+ flutter_cache_manager 3.3.0 (3.3.1 available)
+ flutter_html 3.0.0-alpha.5 (3.0.0-beta.2 available)
+ flutter_launcher_icons 0.12.0 (0.13.1 available)
+ flutter_localizations 0.0.0 from sdk flutter
+ flutter_secure_storage 8.0.0
+ flutter_secure_storage_linux 1.1.3
+ flutter_secure_storage_macos 3.0.0
+ flutter_secure_storage_platform_interface 1.0.1
+ flutter_secure_storage_web 1.1.1
+ flutter_secure_storage_windows 2.0.0
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ font_awesome_flutter 10.1.0 (10.5.0 available)
+ from_css_color 2.0.0
+ go_router 7.1.1 (9.1.1 available)
+ google_fonts 4.0.3 (5.1.0 available)
+ html 0.15.4
+ http 0.13.6 (1.1.0 available)
+ http_parser 4.0.2
+ image 4.0.17
+ intl 0.18.0 (0.18.1 available)
+ js 0.6.7
+ json_annotation 4.8.1
+ json_path 0.4.1 (0.6.1 available)
+ logging 1.2.0
+ matcher 0.12.15 (0.12.16 available)
+ material_color_utilities 0.2.0 (0.8.0 available)
+ meta 1.9.1
+ mime_type 1.0.0
+ nested 1.0.0
+ numerus 1.1.1 (2.1.2 available)
+ octo_image 1.0.2
+ page_transition 2.0.4 (2.0.9 available)
+ path 1.8.3
+ path_provider 2.0.14 (2.0.15 available)
+ path_provider_android 2.0.25 (2.0.27 available)
+ path_provider_foundation 2.2.2 (2.2.4 available)
+ path_provider_linux 2.1.11
+ path_provider_platform_interface 2.0.6
+ path_provider_windows 2.1.7
+ pedantic 1.11.1
+ petitparser 5.4.0
+ platform 3.1.0
+ plugin_platform_interface 2.1.3 (2.1.5 available)
+ pointer_interceptor 0.9.3+4
+ pointycastle 3.7.3
+ provider 6.0.4 (6.0.5 available)
+ rfc_6901 0.1.1
+ rxdart 0.27.7
+ shared_preferences 2.0.15 (2.2.0 available)
+ shared_preferences_android 2.1.0 (2.2.0 available)
+ shared_preferences_ios 2.1.1 (discontinued replaced by shared_preferences_foundation)
+ shared_preferences_linux 2.2.0 (2.3.0 available)
+ shared_preferences_macos 2.0.5
+ shared_preferences_platform_interface 2.2.0 (2.3.0 available)
+ shared_preferences_web 2.1.0 (2.2.0 available)
+ shared_preferences_windows 2.2.0 (2.3.0 available)
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1 (1.10.0 available)
+ sqflite 2.2.6 (2.2.8+4 available)
+ sqflite_common 2.4.5+1
+ stack_trace 1.11.0 (1.11.1 available)
+ stream_channel 2.1.1 (2.1.2 available)
+ string_scanner 1.2.0
+ synchronized 3.1.0
+ term_glyph 1.2.1
+ test_api 0.5.1 (0.6.1 available)
+ timeago 3.2.2 (3.5.0 available)
+ typed_data 1.3.2
+ url_launcher 6.1.10 (6.1.12 available)
+ url_launcher_android 6.0.27 (6.0.37 available)
+ url_launcher_ios 6.1.4
+ url_launcher_linux 3.0.5
+ url_launcher_macos 3.0.6
+ url_launcher_platform_interface 2.1.2 (2.1.3 available)
+ url_launcher_web 2.0.18
+ url_launcher_windows 3.0.7
+ uuid 3.0.7
+ vector_math 2.1.4
+ webview_flutter 4.0.5 (4.2.2 available)
+ webview_flutter_android 3.3.1 (3.9.1 available)
+ webview_flutter_platform_interface 2.0.2 (2.4.0 available)
+ webview_flutter_wkwebview 3.1.1 (3.7.0 available)
+ webviewx_plus 0.3.3
+ win32 5.0.5
+ xdg_directories 1.0.1
+ xml 6.3.0
+ yaml 3.1.2
Changed 124 dependencies!
Analyzing dependencies
[!] Unable to find a target named `ImageNotification` in project `Runner.xcodeproj`, did find `Runner`.

Build failed :|
Step 6 script `Install pods` exited with status code 1

----------------

Google play build error log:

Codemagic Deploy Output
Failed Step: Build AAB with Flutter

Resolving dependencies...
  _flutterfire_internals 1.3.2 (1.3.4 available)
  cached_network_image 3.2.1 (3.2.3 available)
  cached_network_image_platform_interface 1.0.0 (2.0.0 available)
  cached_network_image_web 1.0.1 (1.0.2 available)
  cli_util 0.3.5 (0.4.0 available)
  cloud_functions 4.3.2 (4.3.4 available)
  cloud_functions_platform_interface 5.4.2 (5.4.4 available)
  cloud_functions_web 4.5.2 (4.5.4 available)
  collection 1.17.1 (1.17.2 available)
  csslib 0.17.3 (1.0.0 available)
  csv 5.0.1 (5.0.2 available)
  easy_debounce 2.0.1 (2.0.3 available)
  file 6.1.4 (7.0.0 available)
  firebase_core 2.13.1 (2.15.0 available)
  firebase_core_web 2.5.0 (2.6.0 available)
  firebase_messaging 14.6.2 (14.6.5 available)
  firebase_messaging_platform_interface 4.5.2 (4.5.4 available)
  firebase_messaging_web 3.5.2 (3.5.4 available)
  flutter_animate 4.1.1+1 (4.2.0 available)
  flutter_cache_manager 3.3.0 (3.3.1 available)
  flutter_html 3.0.0-alpha.5 (3.0.0-beta.2 available)
  flutter_launcher_icons 0.12.0 (0.13.1 available)
  font_awesome_flutter 10.1.0 (10.5.0 available)
  go_router 7.1.1 (9.1.1 available)
  google_fonts 4.0.3 (5.1.0 available)
  http 0.13.6 (1.1.0 available)
  intl 0.18.0 (0.18.1 available)
  json_path 0.4.1 (0.6.1 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.8.0 available)
  numerus 1.1.1 (2.1.2 available)
  page_transition 2.0.4 (2.0.9 available)
  path_provider 2.0.14 (2.0.15 available)
  path_provider_android 2.0.25 (2.0.27 available)
  path_provider_foundation 2.2.2 (2.2.4 available)
  plugin_platform_interface 2.1.3 (2.1.5 available)
  provider 6.0.4 (6.0.5 available)
  shared_preferences 2.0.15 (2.2.0 available)
  shared_preferences_android 2.1.0 (2.2.0 available)
  shared_preferences_ios 2.1.1 (discontinued replaced by shared_preferences_foundation)
  shared_preferences_linux 2.2.0 (2.3.0 available)
  shared_preferences_platform_interface 2.2.0 (2.3.0 available)
  shared_preferences_web 2.1.0 (2.2.0 available)
  shared_preferences_windows 2.2.0 (2.3.0 available)
  source_span 1.9.1 (1.10.0 available)
  sqflite 2.2.6 (2.2.8+4 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.5.1 (0.6.1 available)
  timeago 3.2.2 (3.5.0 available)
  url_launcher 6.1.10 (6.1.12 available)
  url_launcher_android 6.0.27 (6.0.37 available)
  url_launcher_platform_interface 2.1.2 (2.1.3 available)
  webview_flutter 4.0.5 (4.2.2 available)
  webview_flutter_android 3.3.1 (3.9.1 available)
  webview_flutter_platform_interface 2.0.2 (2.4.0 available)
  webview_flutter_wkwebview 3.1.1 (3.7.0 available)
Got dependencies!

Upgrading build.gradle
Running Gradle task 'bundleRelease'...                          
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/builder/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.2/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Error: Couldn't resolve the package 'cloud_firestore' in 'package:cloud_firestore/cloud_firestore.dart'.
lib/backend/push_notifications/push_notifications_handler.dart:5:8: Error: Error when reading 'lib/backend/backend.dart': No such file or directory
import '../backend.dart';
       ^
lib/backend/push_notifications/serialization_util.dart:7:8: Error: Error when reading 'lib/backend/backend.dart': No such file or directory
import '/backend/backend.dart';
       ^
lib/backend/push_notifications/serialization_util.dart:3:8: Error: Not found: 'package:cloud_firestore/cloud_firestore.dart'
import 'package:cloud_firestore/cloud_firestore.dart';
       ^
lib/backend/push_notifications/serialization_util.dart:161:3: Error: Type 'RecordBuilder' not found.
  RecordBuilder<T> recordBuilder,
  ^^^^^^^^^^^^^
lib/backend/push_notifications/serialization_util.dart:51:16: Error: 'DocumentReference' isn't a type.
  if (value is DocumentReference) {
               ^^^^^^^^^^^^^^^^^
lib/backend/push_notifications/serialization_util.dart:55:16: Error: 'FirestoreRecord' isn't a type.
  if (value is FirestoreRecord) {
               ^^^^^^^^^^^^^^^
lib/backend/push_notifications/serialization_util.dart:149:14: Error: Undefined name 'FirebaseFirestore'.
      return FirebaseFirestore.instance.doc(param) as T;
             ^^^^^^^^^^^^^^^^^
lib/backend/push_notifications/serialization_util.dart:161:3: Error: 'RecordBuilder' isn't a type.
  RecordBuilder<T> recordBuilder,
  ^^^^^^^^^^^^^
lib/backend/push_notifications/serialization_util.dart:166:10: Error: Undefined name 'FirebaseFirestore'.
  return FirebaseFirestore.instance
         ^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acloud_firestore%2Fcloud_firestore.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:721:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:861:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:660:9)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:99:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
<asynchronous suspension>

Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/builder/programs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/builder/programs/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s
Running Gradle task 'bundleRelease'...                             73.6s
Gradle task bundleRelease failed with exit code 1

Build failed :|
Step 7 script `Build AAB with Flutter` exited with status code 1

### Expected Behavior

should upload the build

### Steps to Reproduce

mobile deployment

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

reported above

### Context

deploy the build to publish the app

### Visual documentation

No need
<img width="1263" alt="Screenshot 2023-07-21 alle 03 58 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140130215/29547903-7eb4-4ae6-9562-bee288b0cca1">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Flutterflow
- Browser name and version: Safari
- Operating system and version affected: macos ventura 13.0
```

**Comment by VarunAghara** [comment]
same issue with me

**Comment by kevintonb** [comment]
Hey @dao1235 , this Github Issue Tracker is to report bugs that are reproducible and persistent in nature within the Flutterflow environment, so that we can backtrack and resolve these bugs. For issues that you're facing related to deployment, kindly contact the Flutterflow Support Team at support@flutterflow.io for prompt resolution! :)
