### ISSUE TITLE
Custom Regex is not working properly

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#1147]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In custom regex when I enter ^[0-9]$|^[1-9][0-9]$|^(100)$ it is converted to ^[0-9]\\$|^[1-9][0-9]\\$|^(100)\\$(which I checked from code), adding a backward slash(\) in front of $, \ and probably for some other regex characters too. This makes regex useless.
I also face this same issue whenever I try to enter any text containing some special characters making it hard to use Unicode or control characters in the Text widget. Seems to be a related issue.

### Expected Behavior

The custom regex should be the same as the input without any changes.

### Steps to Reproduce

1. Create new project/page.
2. Add a Form with TextField within.
3. In form add any custom regex containing \ or $ and test run the app.
4. Regex will not work as expected. Check the model code and you will notice unwanted '\\' in regex. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l/HLuMlOxLhc+KqNdcdKqCYWHHk7aIJIjdZTY008KOvZPO0Me/XsVxdtUsfiY39LPkSmmkgHwej2j4bxL8I4ZA6Wfpw7zrlQbQ7xQTiQe5OBO7jpf3dfHdxjCWKD0qSJkRJNKsthL2Af6kOLNejIfCjbHpDwIlFISq/LZO4=

### Context

Using regex for form validation or textfield inputs.

### Visual documentation

<img width="887" alt="Screenshot 2023-07-21 at 8 38 23 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102008213/a13e1dd4-984f-4ad4-a35d-9e0825de806c">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by aemelyanovff** [comment]
@Shubham-VE Thanks for reporting the issue.

Backslashes escape special characters in Dart. If you still believe it's a bug, please provide an example of a simple regex that works on https://regex101.com/ but doesn't work in FlutterFlow forms.

**Comment by Shubham-VE** [comment]
@aemelyanovff The issue is that FF automatically converts \ to \\ and $ to \$ making any these symbols useless. One example of such regex would be ^[0-9]$|^[1-9][0-9]$|^(100)$ which checks if value is between 0 an 100 inclusive, as already descried in the question. You can try to use it in form's custom regex and then check the model code to see that it had been modified to ^[0-9]\$|^[1-9][0-9]\$|^(100)\$

**Comment by aemelyanovff** [comment]
Thanks, @Shubham-VE. This is the expected behavior. As I mentioned above, backslashes are added to escape special characters (in this case `$` and `\`) in Dart. You can learn more about it [here](https://dart.dev/guides/language/coming-from/js-to-dart#primitive-types).

> Escaping special characters
> To include a character with another meaning in a string, like a `$` used for string interpolation, you must escape that character. Escaping special characters in Dart works like JavaScript and most other languages. To escape special characters, precede that character with the backslash character (`\`).

It doesn't "make these symbols useless". I tried using `^\d+$` to validate a text field and it worked fine:

![Screenshot 2023-08-01 at 9 14 40 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/6130f058-af9e-4469-81ec-94f2326a189f)

![Screenshot 2023-08-01 at 9 14 52 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/c41d4ff4-5b7e-429d-8aa5-96b599628bf0)

![Screenshot 2023-08-01 at 9 15 03 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/bec9c9c0-7fc8-4062-a31e-1e7c3a39a1c6)

**Comment by tbooth-prog** [comment]
I'm getting similar strange behaviour trying to use this regex ^\d*\.?\d$ to allow a user to enter a numeric value with an optional single decimal place. When you use this on the TextField it allows the input of digits but when the `.` is added then the field is cleared. This works on regex101 but not in FlutterFlow. 

Do you want me to create a new issue or is it a part of this?

**Comment by Maazkhalid47** [comment]
I encountered the same problem but, I tried different combinations and turned out you don't have to include "/" "^" "$" or "*", you can just write the expression  "/^[a-zA-Z\s]*$/"  as "[a-zA-Z\s]"

**Comment by alta-atc** [comment]
> Thanks, @Shubham-VE. This is the expected behavior. As I mentioned above, backslashes are added to escape special characters (in this case `$` and `\`) in Dart. You can learn more about it [here](https://dart.dev/guides/language/coming-from/js-to-dart#primitive-types).
> 
> > Escaping special characters
> > To include a character with another meaning in a string, like a `$` used for string interpolation, you must escape that character. Escaping special characters in Dart works like JavaScript and most other languages. To escape special characters, precede that character with the backslash character (`\`).
> 
> It doesn't "make these symbols useless". I tried using `^\d+$` to validate a text field and it worked fine:
> 
> ![Screenshot 2023-08-01 at 9 14 40 AM](https://private-user-images.githubusercontent.com/92294640/257526034-6130f058-af9e-4469-81ec-94f2326a189f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTM4MjIsIm5iZiI6MTcxMDAxMzUyMiwicGF0aCI6Ii85MjI5NDY0MC8yNTc1MjYwMzQtNjEzMGYwNTgtYWY5ZS00NDY5LTgxZWMtOTRmMjMyNmExODlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE5NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYThkMWIwZjU4MTkyMzNmMzNmNjQzNTUyOTIxMzVhMWE5MzE2YTExNWU2MmYwMTg0ODg3Y2Q4OGYxNGY0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1tlOc2fkSnvGTFn22eVIljOs3HNvaLCHStbC6u7hOGU)
> 
> ![Screenshot 2023-08-01 at 9 14 52 AM](https://private-user-images.githubusercontent.com/92294640/257526050-c41d4ff4-5b7e-429d-8aa5-96b599628bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTM4MjIsIm5iZiI6MTcxMDAxMzUyMiwicGF0aCI6Ii85MjI5NDY0MC8yNTc1MjYwNTAtYzQxZDRmZjQtNWI3ZS00MjlkLThhYTUtOTZiNTk5NjI4YmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE5NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MjdkMzZkZGVkYzhjZGE3MWRiMTBmYzg5MjEzYThjMjA2NDhjYjI3MzZmMDBhYzQwYmE5M2IzYjk3NjBkYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xnI7vwAbjbnhR25YZCKI8WHlWEsauF1dsX6HvrrOYck)
> 
> ![Screenshot 2023-08-01 at 9 15 03 AM](https://private-user-images.githubusercontent.com/92294640/257526072-bec9c9c0-7fc8-4062-a31e-1e7c3a39a1c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTM4MjIsIm5iZiI6MTcxMDAxMzUyMiwicGF0aCI6Ii85MjI5NDY0MC8yNTc1MjYwNzItYmVjOWM5YzAtN2ZjOC00MDYyLWEzMWUtMWU3YzNhMzlhMWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE5NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWY3ZGZlMmM5MjgwYmU1YzU3MmNmMjZlMmY1MGIyYWU3NDgzZDQ5MGU0OGMwNzk5NDRmMWZjNGViZTM0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wV5S8cw8Vu5rd5bCl7h48rT7sjDpukNjt3CqVzPDOcs)
> 
> The other regex you mentioned also seems to be working fine.
> 
> Closing the issue as Not a Bug. Please feel free to reopen if you still think it's a bug. Please provide an example of a simple regex that works on https://regex101.com/ but doesn't work in FlutterFlow forms.

This is exactly what I needed to know. There should be a helpdesk article about how FF handles regex. 

I was trying to use: /(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).+/

And this worked: (?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])

**Comment by alta-atc** [comment]
> Maazkhalid47

This is exactly what I needed to know. 

I was trying to use: /(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).+/ which was failing

This was successful: (?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])

**Comment by Shubham-VE** [comment]
The regex are working properly, the confusion arrised as I was using regex usage in both form and textfield and I misinterpretted it to be related to form. Sorry for the inconvenience. You can close this issue now. Thanks.
