### ISSUE TITLE
Query filter not working when filter variable is null

### ISSUE THREAD

**Issue by yorranrigatti** [FlutterFlow/flutterflow-issues#1149]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am facing an issue with a listView of materials in my project. The listView is making a query to Firebase and filtering the results to display only the materials that have an equipmentRef equal to the reference I am passing. While this process works flawlessly when a valid reference is passed, the problem arises when the reference is null. In such cases, the query should return nothing; however, it currently returns all the materials instead.

### Expected Behavior

I need that when the reference is null it don't return any materials

### Steps to Reproduce

create new page
create a listView
Create two collections in the firebase
Conect to firebase
create a pageState to maintain the Reference to filter
Create the query using the pageState to filter 

i already did this steps from a blank project here
https://app.flutterflow.io/project/list-test-d5jqi3

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjMrqx89grt9c187pbflGmiEWJmE1TL07r+5xb0gvIrbyOu9/eMjedlttOPWkTFNhHE6ZjlgFzM7vj4XxVsYnCwuCQLZPzqpqWgLjTXq8RKamEaWCOHBtO+lhG1Sb36WNuwl+KtVYSVo42U+YHeu9TT/qCZO/Zwh9f6PHaOI=

### Context

I need that when the reference is null it don't return any materials but it's returning all of them

### Visual documentation

![Screenshot 2023-07-21 114800](https://github.com/FlutterFlow/flutterflow-issues/assets/91672979/94bc8bcb-c05d-4d03-bcf8-ce3b322c6034)
![Screenshot 2023-07-21 114813](https://github.com/FlutterFlow/flutterflow-issues/assets/91672979/7f3ab4b3-bda8-4a7a-8a60-1cce5dccb4ae)
![Screenshot 2023-07-21 114826](https://github.com/FlutterFlow/flutterflow-issues/assets/91672979/eb31da70-6347-4669-af29-cc706a183dad)
![Screenshot 2023-07-21 114851](https://github.com/FlutterFlow/flutterflow-issues/assets/91672979/c873533d-c49d-4c7c-9217-3a55e4ce39d1)
![Screenshot 2023-07-21 114922](https://github.com/FlutterFlow/flutterflow-issues/assets/91672979/25679b26-25c5-40f8-a360-29dc79595150)

### Environment

```markdown
- FlutterFlow version: v3.1 (released July 20, 2023)
- Platform: Web
- Browser name and version: Google Chrome Version 115.0.5790.102 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro
```

**Comment by LILETOAL** [comment]
Having the same issue, support redirected me here.

**Comment by khvashcheuskaya** [comment]
I also found this problem, I'm really looking forward to a solution

**Comment by LILETOAL** [comment]
btw you can add conditional visibilities with that filter to double check for the empty situation.
you can also generate children from a column, if empty returns empty.
you can pass values trough a function which, if set it to, can return empty list of whatever data type.

these are temporary solutions till' someone from flutterflow fixes this, because for big query all the methods above are inconvenient.

**Comment by davidflutterflow** [comment]
Thanks for the solution.

Right now the only workaround is to use a custom function and check the reference if it's null, we return a dummy reference.
So in case we compare a field against a reference and that reference was null query doesn't return any result.

**Comment by takashiff** [comment]
Hello, thank you for the bug report. A new option has been added to allow filters on null values, however, the default behavior will remain the same. This change will be reflected in our next deploy.

**Comment by univermal** [comment]
Is this released?

**Comment by loriscrmt** [comment]
Hello, 
I experienced the same issue. Event with the "Filter on Null Value" option checked.
Does anyone has a solution ?
Thanks
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87064666/7071ef79-5743-4435-9f7e-e7c513631d9f)

**Comment by armanddebesse** [comment]
Hello @loriscrmt I have the same issue with Filter on Null Values option checked, have you find a solution ?
Thank you very much

**Comment by Plumillon** [comment]
Those options are not available if you use the Firestore queries in actions, causing the same behaviour.

**Comment by spiqup** [comment]
So, this is FlutterFlow firestore bug which has not been resolved. Seems to be a simple bug hmm.

**Comment by sb-oth** [comment]
Same problem. Persists with "Filter on Null values" checked. Anyone with found a good workaround?
