### ISSUE TITLE
CircleImage component not initialized with default box fit

### ISSUE THREAD

**Issue by michaelmcroskey** [FlutterFlow/flutterflow-issues#115]
## Expected behavior (required)
When initially adding a CircleImage component to the widget tree, the rendered box fit should match the selected box fit in the UI. The box fit should likely also be explicitly set in the generated code.

## Current behavior (required)
See [video](https://user-images.githubusercontent.com/5116511/201182977-40eca39a-1163-4b60-afa2-38cb18209f1f.mov)

When initially adding a CircleImage component to the widget tree, the box fit selection in the side-panel UI appears to be `cover`, but actually renders as `fill` (perhaps because it's the [first BoxFit enum](https://api.flutter.dev/flutter/painting/BoxFit.html)). Additionally, the auto-generated code contains no explicit `fit` value. Note that this only affects the initial state, so toggling the box fit setting the in side-panel UI renders appropriately upon subsequent selections.

## To Reproduce (required)
1. Add a new CircleImage widget to the widget tree
2. Set a non-square asset/network image as the image source
3. Observe:
  a. Displayed Box Fit value in the side-panel UI shows cover
  b. Rendered Box Fit on screen is not cover
  c. Auto-generated code for that widget looks something like:

```dart
Container(
  width: 300,
  height: 300,
  clipBehavior: Clip.antiAlias,
  decoration: BoxDecoration(
    shape: BoxShape.circle,
  ),
  child: Image.network(
    'https://image_url_here'
  ),
),
```

Expected code should look like (see `fit: BoxFit.cover`)

```dart
Container(
  width: 300,
  height: 300,
  clipBehavior: Clip.antiAlias,
  decoration: BoxDecoration(
    shape: BoxShape.circle,
  ),
  child: Image.network(
    'https://image_url_here',
    fit: BoxFit.cover,
  ),
),
```

## Context (required)
I thought I was going crazy! We have so many places in our app where we render profile images as circles and it's likely that uploaded images are not square — so lots of pages rendered partially-masked profile images, instead of a clean circular mask. Not a huge thing, just unexpected behavior :)

## Screenshots / recordings
Recording: https://user-images.githubusercontent.com/5116511/201182977-40eca39a-1163-4b60-afa2-38cb18209f1f.mov

## Your environment
* **Bug Report Code:**
* Version of FlutterFlow used: v3.0 (2022-11-08)
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 107.0.5304.87 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): MacOS 12.6 (21G115)

**Comment by Pepino-GR** [comment]
Hi michaelmcroskey,
I can reproduce this issue.

**Comment by agreaves** [comment]
Hi @michaelmcroskey, thank you very much for the bug report! I've added a default fit for Circle Image and also make it accurately display the rendered FIT. This will be fixed upon our next release!

**Comment by michaelmcroskey** [comment]
Awesome thanks for the super quick fix @agreaves!
