### ISSUE TITLE
Firebase document list not sorted using backend call order system

### ISSUE THREAD

**Issue by jonatanmata** [FlutterFlow/flutterflow-issues#1151]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to call a list of documents from my e-commerce, there are more than 1000 products stored in firebase so far, I doubt that it is such a large number that it generates this type of error. When making the respective configurations within FF to call the list of documents, I don't use any kind of filters, I list them all and add an ordering parameter by "provider" in ascending order, but when I carry out the tests I find that said list is not ordered, I only get a 100% random order as expected

### Expected Behavior

I hope that when listing the documents in that order, the products or items listed will appear, obtaining the result of the supplier field in ascending alphabetical order.

### Steps to Reproduce

Copy the item page "dashboarProducts" to "dashboarProductosFilter" to add other essential filter types for me. In the copied page there is the same listview, but with another type of order and it is executed normally

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

Copy the item page "dashboarProducts" to "dashboarProductosFilter" to add other essential filter types for me. In the copied page there is the same listview, but with another type of order and it is executed normally

### Visual documentation

![errorInventario](https://github.com/FlutterFlow/flutterflow-issues/assets/40368706/19015065-21ba-4eb1-a71d-b71ce2f71654)

https://github.com/FlutterFlow/flutterflow-issues/assets/40368706/04d3723f-8c72-4f90-b94d-edd4d2fc18ca

### Additional Info

As you can see, I created a custom function in the color of the containers to be able to distinguish them easily by relating the initials of the providers with custom colors, this has helped me to work with this material for the moment, since looking at the provider only when it is disordered makes the task of identifying them more complex.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Flutter
- Browser name and version: all browser
- Operating system and version affected: Windows
```

**Comment by aemelyanovff** [comment]
@jonatanmata Thanks for reporting the issue. Can you add steps to reproduce the issue from a blank project? Please include the schema of your collection and a screenshot of the contents of this collection, either in the [FF Firestore Content Manager](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/firebase-content-manager) or Firestore UI. Also please include a bug report code.

**Comment by SameerShahzad99** [comment]
Closing this issue as the user is inactive for more than two weeks without providing complete details
