### ISSUE TITLE
Infinite Scroll For Grid Layout Not Working

### ISSUE THREAD

**Issue by EJS00102** [FlutterFlow/flutterflow-issues#1152]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an API call (that supports pagination)that I use to populate a grid view but if I enable infinite scrolling, then the build fails with the following error:

`Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/onboarding1/onboarding1_widget.dart:105:29: Error: The getter 'gridViewListingsResponse' isn't defined for the class '_Onboarding1WidgetState'.
 - '_Onboarding1WidgetState' is from 'package:test/onboarding1/onboarding1_widget.dart' ('lib/onboarding1/onboarding1_widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'gridViewListingsResponse'.
                            gridViewListingsResponse.jsonBody,
                            ^^^^^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         42.1s
Failed to compile application.`

<img width="324" alt="Screenshot 2023-07-22 at 13 21 56" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/1cb37d6c-410f-4e26-a1f8-f5f258902a2f">
<img width="659" alt="Screenshot 2023-07-22 at 13 22 07" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/b7c12de8-b8b9-4ad2-a5af-191bdf7ee2b8">

If I disable infinite scrolling, then it works fine again.

### Expected Behavior

The expected behaviour is that the grid view infinite scrolling needs to work.

### Steps to Reproduce

1. Add api call that supports pagination with page parameter
2. Add column with scrolling
3. Add container with finite height of 99%
4. Add grid view
5. Add API call to grid view, enable infinite scrolling and set API call page parameter to next page
6. Generate children
7. Try to run in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gruFa+pCAKOxQhQInQkA/U5MnktVxRR4YF5PpE7QQdczRNkNKT7CUd2NAHWKJoEAx0/D4jtjtJfoECxWcfoN80JVAVDyUZGW5MsmsCJOoTn9PHZ5MIFCA0LWzpCMlGLFZWmw76lz6Nq3qNleeY8aSfxBlZ7vfcPo=

### Context

Trying to accomplish infinite scroll to see many listings

### Visual documentation

<img width="324" alt="Screenshot 2023-07-22 at 13 21 56" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/1cb37d6c-410f-4e26-a1f8-f5f258902a2f">
<img width="659" alt="Screenshot 2023-07-22 at 13 22 07" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/b7c12de8-b8b9-4ad2-a5af-191bdf7ee2b8">

### Environment

```markdown
- FlutterFlow version: v3.10.4
- Platform: Web
- Browser name and version: Version 16.5 (18615.2.9.11.4)
- Operating system and version affected: macOS 13.4 (22F66)
```

**Comment by rayane69-crypto** [comment]
I have another problem: in a gridview with infinite scroll, when I filter the backend query, it loads, for example, the first 5 items, and then it gets stuck like that. However, if I remove the filter, it continues to load, and the infinite scroll works fine. 


![Capturepng](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/8483313e-bbd9-43e4-a828-0cbd8d083b7f)
![Capture2](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/5a949b7a-9fdc-4725-8024-3c382ffbd38f)

**Comment by victoriahuang1** [comment]
Hi @EJS00102 , thanks for the report. The variable you have chosen (the API response), is not valid in this situation. It conceptually doesn't make sense for a dynamic child to access its parents paginated API query, so we will be blocking access to this variable in such cases soon.

Instead, you should have the child widget access the generated `id item`.

![Screenshot 2023-07-26 at 1 03 01 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/b79e3c63-6da2-4db8-aec7-69da6d4bb306)

**Comment by EJS00102** [comment]
@victoriahuang1 I have since realised this as well and fixed it, but there is still an issue with it not working. 

lib/pages/explorer/explorer_widget.dart:341:50: Error: The getter
'gridViewNearby' isn't defined for the class 'ExplorerModel'.
 - 'ExplorerModel' is from 'package:go_kiddo/pages/explorer/explorer_model.dart'
 ('lib/pages/explorer/explorer_model.dart').
Try correcting the name to the name of an existing getter, or defining a getter
or field named 'gridViewNearby'.
                        scrollController: _model.gridViewNearby,
                                                 ^^^^^^^^^^^^^^

**Comment by victoriahuang1** [comment]
Hi @EJS00102, please post your updated bug report code.

**Comment by EJS00102** [comment]
Thank you for your effort @victoriahuang1 , here is the new bug report code:

ITFfkcnLuI1Nod9b1oSJasJF9WM4Q30cTIAZm+5+cy8YGIytBuw1eM6kaRNpZOKoaVNcOlCipH0Hw62Pit/1KsI6OS+ZRpxIwaVyTQ/Oe2iWMZjUBYeWQ3FBBZ1TGnLC4Ke7myUkLtdvV3AY6jm6AtyycDHDFOu/Zwh9f6PHaOI=

Here is the error code again for reference:

<img width="580" alt="Screenshot 2023-07-27 at 08 12 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/44476faf-72fd-4a7a-bae1-86a5f6a61033">

**Comment by EJS00102** [comment]
I managed to find the widget causing the error. It's the scroll to top floating button.

![Screenshot 2023-07-27 at 13 45 56](https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/624c0b1d-63a8-4cf2-b45f-046babf3b596)

Once I deleted it, the infinite scrolling works.

I think there might be an issue with scroll to top action, when you have a infinite scroll on grid layout.

**Comment by victoriahuang1** [comment]
This scrolling issue will be fixed upon the next deploy.
