### ISSUE TITLE
Crashing when Infinite Height is Clicked in Column

### ISSUE THREAD

**Issue by vaibhavkusalkar** [FlutterFlow/flutterflow-issues#1153]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While Creating 3 Container in Column Widget, If we have given 2 containers specific height then by clicking infinite height for the midddle container it should calculate the height as per the display height.
but it crashes and whole blank screen appears .

### Expected Behavior

For eg - While there are 3 Containers in Column Widget. and the height of 2 Container is given then the middle container should adapt the height of the screen and adjust itself accordingly.

### Steps to Reproduce

1. Create a Column
2. Add 3 Containers as a child
3. Specify the height to any two containers
4. Click on Infinite Height for 3rd Container

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lfLqwIt2sctK1bryb/pahjs5KU83RpIr18B7aDUsIuOtBuwfds7sZRNpTu6raVNfe02lvGUdpODlhtnqUPkrCz6WRb06zqVuUjv0e2inRq6LDKuaVX9BJ9lhJhWwyMGJogpBNtdoc0YC2V6uHeutbDDDFOu/Zwh9f6PHaOI=

### Context

It takes more time to give specific height to each and also to calculate.

### Visual documentation

.

### Environment

```markdown
- FlutterFlow version: v3.1 (released Jul 20, 2023)
- Platform: Web
- Browser name and version: Edge 
- Operating system and version affected: Edge 114.0.1823.86 (Official build) (64-bit)
```

**Comment by SameerShahzad99** [comment]
Hi @vaibhavkusalkar, apologies for the delayed triage, it looks like you have not attached a blank project with only the issue that you mentioned so we could proceed with the testing!

**Comment by victoriahuang1** [comment]
Hi @vaibhavkusalkar , this is actually the expected behavior (this is how Flutter itself behaves). Instead of setting the last container to have infinite height, you should change its expansion settings to "expanded".

https://docs.flutterflow.io/widgets-and-components/widgets/widget-commonalities#sizing-widgets-inside-column-and-row
