### ISSUE TITLE
Appbar style_change button is not shown

### ISSUE THREAD

**Issue by cmwang92** [FlutterFlow/flutterflow-issues#1154]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The button that is able to change appBar style is not shown
<img width="403" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139349033/45b75ad9-8734-42f1-b7da-b9c0a10c2725">

### Expected Behavior

It should have small button next to canvas 
<img width="496" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139349033/d5569c28-c32a-4e06-bd88-ab3a570f7006">

### Steps to Reproduce

1. Create new page / new project
2. Appbar button is not shown 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Appbar

### Context

not able to quickly change appBar style

### Visual documentation

<img width="496" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139349033/f25a9c63-aa16-4425-880d-fc40ecaa0745">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:Web
- Browser name and version:Chrome Version 114.0.5735.198
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @cmwang92 - Thanks for reporting the issue. I tested it in a new project. It is working as expected. See below. 
I would suggest refresh the page and zoom in/out the browser. See if there are any differences. 

If still persisting the issue, updating the issue with project bug report code and share a quick video. Once you have added these details I can re-investigate the issue. Thanks

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/66e145a3-6be0-44bd-b4fd-49ac51ed13bd)
