### ISSUE TITLE
Using a slider to filter a Firebase query

### ISSUE THREAD

**Issue by shanesuan** [FlutterFlow/flutterflow-issues#1155]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using 2 input fields and a slider to filter a Firebase backend query. The single result from Firebase is then used to set a second slider. In my case I use the same Firebase result to set the initial value, the min, and the max of the second slider (I multiply by .5 for the min and multiply by 1.5 for the max). I'd like the second slider to update automatically based on the first slider result.

When the user moves the first slider the second slider adjusts the min and max values perfectly. However the position of the slider does not update at the same time as the min and max. This is weird since all three are set from the same query result. Not until I touch the first slider an additional time will the position of the 2nd slider move to the correct location. The second slider position is always lagging one move behind. This can create an error since the Min and Max values update to a different value than the slider. This can cause an error when the slider value does not fall between the min and max values.

I've attempted to use the Firebase Result to set a variable. Then use the variable to set the min, max, and initial fields. This however makes everything delay by one result

https://github.com/FlutterFlow/flutterflow-issues/assets/55960212/77bf7607-4d76-46c5-8c06-918da1eebcda

### Expected Behavior

I'd like the min, max, and initial value of the second slider to update automatically based on the first slider result when a firebase query is used

### Steps to Reproduce

1. Create a new page
2. Add 2 text input fields
3. Add 2 Sliders
4. Create a test Firebase with 4 fields
5. Add a backend query to the page
6. Use the 2 input fields and the slider as filters for the Firebase query
7. Set 2nd slider as the result of the firebase query
8. Set Min value of slider to Firebase result * .6
9. Set Max value of slider to Firebase result *1.5
10. Slide first slider to filter values. 
11. Notice that the actual value of 2nd slider does not match the firebase result

https://github.com/FlutterFlow/flutterflow-issues/assets/55960212/1a6d8621-e503-4756-b609-6550b1bed957

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfls/l6otIsdtK0L6Jd+5agmYvG1scTZM3lOsYGAAjGIjuBJkUZcjEaXddOcjgY1FEGFL8sHMd+e+Njd/9NsIrAASsRql607tUegHwfFu7V8WzCqWCVmt8L+1QBWqPy7SvrREkHNVoLlY113GLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am recreating my established app inside FlutterFlow. I'm trying to recreate it to be similar to my current app. The existing users set sliders to adjust part parameters. This has proven to be well received. My other app had local table data instead of Firebase data. This made it faster (nearly instant) to retrieve filtered data.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/55960212/6b411192-9e8c-437d-85c7-06cf574b7514

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Android, iOS, Web
- Browser name and version: Chrome Version 114.0.5735.248 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro 10.0.22000 Build 22000
```

**Comment by wenkaifan0720** [comment]
Hi @shanesuan. I looked at the test project you provided but don't fully get what it is trying to do. But from my previous experience, the initial value for form widgets is usually set once and then controlled by the user. If you want to force the slider to rebuild with the updated initial value, I think you can try making the second slider into its own component.
