### ISSUE TITLE
Issue with Loop Action

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#1156]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Loop stops after one iteration when update App state action with update type at "Remove item from list at index"  added.

### Expected Behavior

Loop should be completed in the same manner as when run without update App state action with update type at "Remove item from list at index" 

### Steps to Reproduce

1. Create a loop action
2. Add an action to create a document in the loop
3. Add an action to update App state with update type at "Remove item from list at index" 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqw5dgobRJ7s/+bMJVgio5JmY/ULsoletRaCgoIYyuOpl/evWkSEpoZ/GmTFFEPESmmlo1+N7IjeDmU/JdAzutQN1f+M5cUzryQnuRUZOBBs6BdUZRGdlXG3654bWn3RZDIsVhLSAj7E+be+q9fBXtJ77tIlFISq/LZO4=

### Context

I am trying to remove cart items after order is placed. 

### Visual documentation

<img width="1287" alt="Screen Shot 2023-07-23 at 6 03 23 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/121250616/178e3772-6ee2-4b07-84e8-6b88bc8c323b">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
I think this is happening because of the logic you have inside your Loop. The logic needs to be to increase the index not to remove it.

**Comment by SiraEnterprises** [comment]
I have changed logic for loop and it's working fine
