### ISSUE TITLE
You can not click on the "Upgrade" button on the "Export Source Code" popup when looking at code in custom action

### ISSUE THREAD

**Issue by cecharlier** [FlutterFlow/flutterflow-issues#1157]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking on the "Upgrade Button" selects code underneath. 

### Expected Behavior

Go to the upgrade page.

### Steps to Reproduce

1. While working on a custom action (In a free account)
2. Click Developer Menu
3. Click Download Code
4. On the popup, try to click "Upgrade" 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not in widget tree... 

### Context

dude... these required fields are intense, I am just trying to tell you about a simple little bug. 

### Visual documentation

no

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: MAC
- Browser name and version: Chrome 114.0.5735.198 (Official Build) (arm64)
- Operating system and version affected: IOS Ventura 13.3
```

**Comment by hariprasadms** [comment]
Can you please share a quick video showing the issue?

**Comment by cecharlier** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/909404/d0ca579e-0005-4a19-99d1-78c501d9dba4

i am attempting to click the upgrade button and the close popup. you can see i am still selecting the code in the editor

**Comment by wenkaifan0720** [comment]
Hi @cecharlier. This is indeed a bug on our end and will be fixed in our next update. Thank you for reporting!
