### ISSUE TITLE
Udemy API always response code 403

### ISSUE THREAD

**Issue by dedidoot** [FlutterFlow/flutterflow-issues#1158]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an Udemy API with header Authorization, so I try call the Udemy API in FlutterFlow always get 403 response status code

### Expected Behavior

I tried in postman it works

### Steps to Reproduce

1. Endpoint API: https://www.udemy.com/api-2.0/courses?page=1
2. Authorization:  Basic {dm_me}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8rlvJR2rsRE1rruccBv+CQUQmYjbIIsmspOEC0jF7KuBqQcO+LeTBRuOMOraVNcB1L88XsC0/SMkfD9A/oDOTOAfoRB1rhUThb0e2igRpDREbu0ZHZ9EplhC2mP37eFuCZNBNtYWHwX2DuYLui9VT3DBOu/Zwh9f6PHaOI=

### Context

I want to use Udemy API in my project using FlutterFlow

### Visual documentation

<img width="1006" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4760225/9001421b-f35d-43e3-8aa8-e823c1ab4f40">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Android & iOS
- Browser name and version: Google Chrome Version 114.0.5735.198 (Official Build) (arm64)
- Operating system and version affected: Mac OS Ventura
```

**Comment by hariprasadms** [comment]
Hi @dedidoot - Thanks for posting the issue. Please update the issue with project bug report code. also create a blank project with issue steps details. Thanks

**Comment by dedidoot** [comment]
> Hi @dedidoot - Thanks for posting the issue. Please update the issue with project bug report code. also create a blank project with issue steps details. Thanks

hi, I updated

**Comment by hariprasadms** [comment]
Hi, Thanks for updating the bug report code. I looked at your project and tried to run your endpoint in postman. But, I get this below message. Looks like you may not have correct permission to run access the endpoint externally. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/647f884e-9f9c-49f8-a132-6b38ba48f17f)

**Comment by dedidoot** [comment]
> Hi, Thanks for updating the bug report code. I looked at your project and tried to run your endpoint in postman. But, I get this below message. Looks like you may not have correct permission to ru
<img width="875" alt="Screenshot 2023-07-24 at 22 00 56" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4760225/9603c7d3-a17a-4f5f-8c51-c7c0c9ad590c">
n access the endpoint externally.
> 
> ![image](https://user-images.githubusercontent.com/17435678/255582920-647f884e-9f9c-49f8-a132-6b38ba48f17f.png)

Hi, please don't using Bearer Token.  Udemy API just use header, please check my screenshot

**Comment by hariprasadms** [comment]
Hi, Thanks for update. Looks like the above bug report code project I can't access now. Did you delete the project ?

**Comment by dedidoot** [comment]
> Hi, Thanks for update. Looks like the above bug report code project I can't access now. Did you delete the project ?

Hi, I didn't delete it. please check again

Bug report code:
IT4oz8rlvJR2rsRE1rruccBv+CQUQmYjbIIsmspBZywgfZzzBLN/fPfQPlVtYN+kYXNHM2Kmp14HzMLej/H9GscDPkmufa46+KpiZwnyLHGnR7GTF7ivOUFtJ/FbGEvCy52jvQp4PbFuWHhg2UOAIOyWQgDZH5TwIno4Sq/LZO4=

**Comment by dedidoot** [comment]
Hello @hariprasadms , any update?

**Comment by dedidoot** [comment]
Resolved, problem with `User-Agent` value
