### ISSUE TITLE
Can't fix an issue about List<Dynamic>

### ISSUE THREAD

**Issue by Cod-heure** [FlutterFlow/flutterflow-issues#1159]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm doing a listview where there are cards.

Each card has a departure adress and arrival adress.

I want to calculate the distance between the departure adress of the current user and the departure adress of the post (of the card)

Each adress is a JSON with a coordinates. The coordinates are List<Double> with longitude and latitude in it.

I made a function that calculate distance between two coordinates (using 2 parameters List<Double> Type), the return value is a double that i transform into a string to display on the card (on the post).

Thus, the function is running for each card.

I got  the error : Expected value of type 'List<Double>', but got one of type 'List<Dynamic>'

### Expected Behavior

I just want to display the return value

If it works, that mean i can manipulate the distance to filter my ListView 

But, you guys put a form 'DistanceFilter', ou are a no code tools that allows us to build.

You made a DistanceFilter widget that doesnt event work.

### Steps to Reproduce

read the first description please

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhcj18ZN2rtxE7pDQYMFWnicwFjsaU40V0tdTY04jfbaoPZoiPer+VHdVX7CreAlbeFWKrEwx0vDyivL1M/UnAE2teINoyJB1Wz3xTmKVb5SQCJG7OXR6ROJmGH6e4cOZ3SRTC7JvZUI8w2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

please read the first description

### Visual documentation

![Screenshot 2023-07-24 220727](https://github.com/FlutterFlow/flutterflow-issues/assets/112079086/0b2b49da-acc2-4644-885d-8c7541c528cf)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: web
- Browser name and version: chrome latest
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
@Cod-heure It looks like the problem you are facing is project specific and you have also not attached an empty project with setup, I would recommend you to head over to the FlutterFlow support if you are facing any problems!

**Comment by stevey6404** [comment]
Hi @Cod-heure, did you resolve this problem? I’m experiencing the same with my custom function with a list of lat and list of long. 
For me I’m combining them to become <lay,lng) and showing it on the map as markers.

**Comment by WellDunDun** [comment]
@Cod-heure I had that issue as well and made this video on how I fixed it. I hope this helps! https://youtu.be/uqU4fh0TXwY
