### ISSUE TITLE
Problem with snake_case in page params.

### ISSUE THREAD

**Issue by LozanoJohan** [FlutterFlow/flutterflow-issues#1160]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't use a page param given to my page because it is snake_case, and flutterflow just allow camelCase page params.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/108693709/4d8b119f-9dae-466b-b0f5-ed95042812a5)

### Expected Behavior

I expected flutterflow allowed to create a snake_case page parameters. It is obligatory in my case.

### Steps to Reproduce

1. Create page.
2. Create new page parameter.
3. Write it in snake case.
4. That's it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeyfLl8ZN2pb0D+s+MYO1alQMwJ0QlUIInj+0bWRMhfarmP+wId8n8RExLYtfhewhMDFn9pHsJpd7ehvOWUscDORSBUYB6wa5XQTr/WkauV7KVPoe0fERRI+JUFUiEy6ezuAhCVcFpLVIC31+IC/CdG3qCf9qOYwx5e6fDbOY=

### Context

Hi, I'm using a third party API, It's endpoint is one of my pages with a query param, just like this (I can't change this): 

myapp.com/myPage?pay_id=1234      

I want to get "pay_id" param, but I can't as FlutterFlow just allow to define page parameters as "payId" for example, which would not work. What can I do?

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/108693709/8647d68f-9c9e-4f62-a3e0-f8e3ca976a9c)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi, @LozanoJohan, Thanks for reporting the issue. The parameters name across the FlutterFlow , it should be in camelCase. It is as per design. Parameters name does not accept snake_cases as an example. Thanks
