### ISSUE TITLE
Translation Keys getting duplicated

### ISSUE THREAD

**Issue by smn-snkl** [FlutterFlow/flutterflow-issues#1163]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Sometimes when duplicating / copy & pasting components between pages / components the same key is added to the kTranslationMap in internationalization.dart multiple times leading to weird issues where component text can't be updated separately anymore correctly for the affected components.

E.g. see screenshot below

### Expected Behavior

When duplicating, copy & pasting or applying theme styles to components, the text should receive separate, distinct translation keys and not re-use or redundantly add the same key to the translation map.

### Steps to Reproduce

We haven't found a way to 100% replicate this issue, but typically it involves
1. Creating e.g. a button somewhere, apply a button theme style and update its text
2. Copy & pasting or duplicating that button
3. Changing the text of the second button (or re-apply / unset the style)
4. The text of the old and new button might be updated together or magically "revert" to the wrong button text or the text of the button on the other screen will also update to the new text

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl8/luI9Oj7xZ7aryLO9Vq2IWNU9+apc0st5Hd0gdCOPrBuwQZ/f8UBFDQsjhaVNfeFCLjj8xw9WPiobfLfYEHxesRtVHzJF+czvke2iXVKXQEc2WOHMmJ/FjG0vE0Z+Cnh15BMd1c3A67znzNvDIE3fDFOu/Zwh9f6PHaOI=

### Context

Re-using existing components by duplicating / copy & pasting them on other screens

### Visual documentation

![Screenshot 2023-07-25 at 18 30 13](https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/e218debe-4991-498a-bc83-3dc8bf61f9f3)

### Environment

```markdown
- FlutterFlow version: v3.1 (released Jul 20, 2023)
- Platform: Web + Mobile
- Browser name and version: Multiple
- Operating system and version affected: Multiple
```

**Comment by SameerShahzad99** [comment]
@smn-snkl I am unable to reproduce this problem with the steps given, and it appears that you have not provided a blank project with setup, so can you please provide that, so we could proceed further?

**Comment by SameerShahzad99** [comment]
Closing this issue as the user is inactive for more than three weeks without providing complete details
