### ISSUE TITLE
Pie Chart single numbers crash on iOS

### ISSUE THREAD

**Issue by GuzSantos** [FlutterFlow/flutterflow-issues#1165]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page with a pie chart consisting of 6 data series. When I run the test on iOS devices using the Apple Test flight, the pie chart is just showed as grey screen. The rest of the page works normally.

On the Flutterflow Run/Test, everything works normal

### Expected Behavior

Expect to have the pie chart running on iOS. see the pictures with the current behavior in iOS and expected one.

![IMG_6950](https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/776d8fc9-8afc-4256-9886-ec532eebcd7e)

![IMG_6949](https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/06cba677-c6ab-4350-8aa4-58911de2603a)

### Steps to Reproduce

1. Create a Pie chart inside a transform widget with 270 degrees
2. add 6 data series and set as single values
3. run the test inside FF and check for errors
4. run the test on iOS device and verify if the error persists

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi8nLuJBgofVA+KriYPpvgiQXCUMAXOYvitYbVR4aIoDkPYYqfcnCQ0NKTuGdY1VMAFSIkmUx+anWjtnLGPpcCzWaG4hb0JVAYAGVZDq6RcyaPrigXHNfJ55TG2Kk36bZkCQnBPhqZXBh7TmlN63qNleeY8aSfxBlZ7vfcPo=

### Context

I'm using the donut chart where the size of the data reflects times distance in simple hours. The intention is to show the user time intervals.

I used the transform widget to turn the chart since the first slice of the pie/donut was not starting from the top. I need to show that starts at 12 hours direction

### Visual documentation

![IMG_6949](https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/ef81f1cf-dc68-4fa7-97b1-6ede0ef55167)
![IMG_6950](https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/186612b5-00ff-42bc-9761-50c34d562ef5)

### Environment

```markdown
- FlutterFlow version: 1.1.90
- Platform:MacOS Desktop
- Browser name and version: FlutterFlow APP for Mac
- Operating system and version affected: macOS Catalina 10.15.7
```

**Comment by hariprasadms** [comment]
Hi @GuzSantos, Thanks for submitting the issue. I looked at your project and configuration around pie chat looks fine. However, to investigation the issue we need below items.

1. A blank project with issue setup 
2. A quick video showing the issue.
3. 
Once you added these details we can re investigate the issue.

**Comment by GuzSantos** [comment]
Thanks Hari,

I have created a blank project /p_i_e_chart-mat5yd where I have rebuild the pie chart and it works correctly. You will see the numbers twisted due to the transform widget rotating the chart in 270degrees.

for the iOS, I have recorded a video where I'm opening the App in the web published version and show the piechart working, then I open it in the iOS deployed version and it doesn't show the Piechart, just a grey screen.


https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/1abc20c1-be1f-4f3e-99f7-d02aa9c13f64

**Comment by hariprasadms** [comment]
Hi @GuzSantos - Sorry for being late responding on the issue. Thanks for adding details. Please add bug report code for the blank project. I can't access the project with the details - project /p_i_e_chart-mat5yd.

It is a little difficult to explore the problem given that, as you mentioned, it works properly in web and debug mode and only has the issue in test flight build. I think that problem may be with the data populating in the chart. Considering the chart widget functionality as per the latest updates, I can confirm that, it is working as expected.
 
I assume that the most recent builds have fixed your issue; if so, please let us know and I will close the issue. If the problem still exists, I would advise contacting the technical support team for additional assistance.

**Comment by GuzSantos** [comment]
Thanks Hari,I didn’t make it worked and abandoned the design.Sent from my iPadOn 20 Sep 2023, at 17:09, Hari ***@***.***> wrote:﻿
Hi @GuzSantos - Sorry for being late responding on the issue. Thanks for adding details. Please add bug report code for the blank project. I can't access the project with the details - project /p_i_e_chart-mat5yd.
It is a little difficult to explore the problem given that, as you mentioned, it works properly in web and debug mode and only has the issue in test flight build. I think that problem may be with the data populating in the chart. Considering the chart widget functionality as per the latest updates, I can confirm that, it is working as expected.
I assume that the most recent builds have fixed your issue; if so, please let us know and I will close the issue. If the problem still exists, I would advise contacting the technical support team for additional assistance.

**Comment by hariprasadms** [comment]
Thanks for the update. I will close the issue. You can create a new bug if you got more issues around chat widget. Thanks for your contribution.
