### ISSUE TITLE
Endless loading spinner in ListView with Sub Collection Query

### ISSUE THREAD

**Issue by klyse** [FlutterFlow/flutterflow-issues#1166]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When querying a sub-collection on Firebase with a filter, an endless loading spinner appears.

### Expected Behavior

The loading spinner persists because the query seems to be executed as a Collection group (when adding a filter) instead of starting from the parent. To avoid any permission errors and hide the loading spinner after a successful query, the query should be executed starting from the parent.

### Steps to Reproduce

Step 1:
Create a new FlutterFlow project with Firebase

Step 2:
Enable Authentications and create a user

Step 3:
Create a sub table on the users table:
![Screenshot 2023-07-24 at 13 04 47](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/a20fffcc-7a0c-4d00-8b78-d29a23b52b9f)

Step 4:
Query the sub table and assigning it the user value as parent:
![Screenshot 2023-07-24 at 13 06 09](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/0ab3c711-8917-42bf-ba4e-5c8235c4c762)

Step 5:
Run the project. Works as expected.

Step 6:
Add a filter or a ordering parameter:
![Screenshot 2023-07-24 at 13 07 08](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/081599d0-8c82-42d3-ae80-4d93300c8734)

Step 7:
Run the project and you will see an endless loading spinner in the ListView. Running locally shows a firebase permission error. Essentially what seems to happen is that the generated code ignores the (user) parent in the query.
When removing every filter and grouping this code in the `PagingController` is removed:
          `queryBuilder: (_) => listViewPagingQuery ??= query,`

Here are the generated rules:
![Screenshot 2023-07-24 at 13 12 58](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/6d3050c1-360c-42e0-9768-d431227d3df2)

I hope you can have a look, I wend back in my git copy of the flutterFlow code and this stopped working since 14.07.2023

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gosNK+bX6aMd6hQIhNmY1bZMnktVxRR4aGIDoP+wlPc6kZUNKT8jhfW9iA2CIgl4fwfTvjt/PA+0CKSStbJhm0JVAbwqXfF2iRr6XOqqwYXN8O+FTIHaiy56R2iJSJvJYZVYT716PNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I'm trying to query a sub collection of the `users` collection.

### Visual documentation

As described in the how to reproduce section

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: ios/android
- Browser name and version: Chrome 115.0.5790.102
- Operating system and version affected: MacOS 13.4.1
```

**Comment by klyse** [comment]
I also have an email correspondence with Henry from FlutterFlow. Henry was able to reproduce this issue.

**Comment by klyse** [comment]
Hi Hari,
Thanks for having a look. Please see attached the video for additional details:

https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/80745c40-9db2-4ac3-8d2b-b5e34dcdac14

I assume you created a new user when testing the app that indeed does not have any documents in the sub collection.

**Comment by klyse** [comment]
@hariprasadms where you able to reproduce this?

**Comment by hariprasadms** [comment]
Hi @klyse - Thanks for sharing the video. Looks like this loading indicator issue is related to indexes delayed in Firestore. This is is not FlutterFlow issue as everything looks fine at the configurations end. I would suggest try the same in different collections other than user collection. 

I would suggest to use in-app chatting service in side FlutterFlow editor to get technical support if you are still stuck with the same behaviour.

**Comment by klyse** [comment]
Hi @hariprasadms, thanks for the update. I just tested the same query from a javascript SDK and got successful results (in the console on the bottom):
![Screenshot 2023-08-04 at 21 27 29](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/7fc1fea6-71ae-4cec-b215-80fa3b5024c5)
So I do believe this is not related to indexes unless I'm missing something?
Here is the FlutterFlow test query:
![Screenshot 2023-08-04 at 21 29 57](https://github.com/FlutterFlow/flutterflow-issues/assets/10352866/e67fac7e-6ac1-421d-bac0-6a501095f267)

**Comment by klyse** [comment]
@hariprasadms I think this is only happening for querys where "Enable Infinite Scroll" is enabled.

**Comment by klyse** [comment]
@hariprasadms don't think the issue is stale as I was able to reproduce the issue on a brand new project (linked above). Could you please have a look again?

**Comment by sbis04** [comment]
This should be fixed in the next update!

**Comment by taggxyz** [comment]
@sbis04 This issue appears to have resurfaced

**Comment by zappyle** [comment]
This seems back indeed
