### ISSUE TITLE
Background Audio not working

### ISSUE THREAD

**Issue by chaseaustin42** [FlutterFlow/flutterflow-issues#1167]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I enabled background audio within the default audio player widget and when testing my app through testflight on IOS, the audio pauses when I both switch apps and lock my phone. The audio unpauses when the app is in the foreground again. 

### Expected Behavior

I expect audio to continue playing when in background

### Steps to Reproduce

I've changed the audio player property, "Play in Background" to enabled to existing audio players in my app. These audio players were added to the app before the new "play in background" option was available. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiMmA5clgoctH176JdsAwvGQXG1scT5A709VuTQ4sCKL2O4kQdvWkahBCZOnhY3N+eUSmmlwJptbykeLxF/ZcEzGcUa46ws1MUgyVYEenQZOBCJaobUBCBtNQCB2g0bbQsQl5BMdZdCUD3GD3NfCXbBPvJJ/1IndISq/LZO4=

### Context

I would love to have background audio available in my app. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/130612346/e0f97383-a403-4afd-9c2e-dfd7ae748ced

### Environment

```markdown
- FlutterFlow version: v3.1 (released July 20, 2023)
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.198
- Operating system and version affected: macOS Monterey 12.5.1
- Mobile Operating System: IOS 16.0.2
```

**Comment by davoodflywheel** [comment]
FYI for the eng team, i test this in ios- emulator and experiencing the same issue. background play is not working.

**Comment by chaseaustin42** [comment]
Is there any timeframe estimate on when this might be fixed?

**Comment by agreaves** [comment]
Hi @chaseaustin42, thank you for this bug report, and apologies for the delay in fixing. We've managed to reproduce and fix this issue, so you should see background playing working again on iOS upon our next release! 🙂

Thanks again for your patience!
