### ISSUE TITLE
Gradient text breaks webpages

### ISSUE THREAD

**Issue by specificallynathan** [FlutterFlow/flutterflow-issues#1168]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When published to the web, when gradient text is used the page never loads

### Expected Behavior

Pages should load and function normally

### Steps to Reproduce

1. Create a page
2. Use gradient text on the page
3. Publish to the web
4. Try to access the page as a fresh user

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

if (_model.isEditing == false)   Align(     alignment: AlignmentDirectional(0, 0),     child: GradientText(       'Contact Details',       textAlign: TextAlign.center,       style: FlutterFlowTheme.of(context).displaySmall,       colors: [         FlutterFlowTheme.of(context).primary,         FlutterFlowTheme.of(context).secondary       ],       gradientDirection: GradientDirection.ltr,       gradientType: GradientType.linear,     ),   )

### Context

My website was un-useable until I removed all gradient text. Unfortunate because gradient color is part of the brand identity.

### Visual documentation

None

### Additional Info

This was a bug when I first tried to publish my site - it's taken me til now to report it. Not sure what the flutterflow version was, but I haven't seen anything addressing the issue so it's probably still an issue. I've stayed away from gradient text since I found it was the widget causing the issues.

### Environment

```markdown
- FlutterFlow version: 
- Platform:Web
- Browser name and version:Safari, chrome
- Operating system and version affected: Windows, iOS
```

**Comment by hariprasadms** [comment]
Hi @specificallynathan - Thanks for reporting the issue. The bug report code you given above is not valid. To generate bug report code goto any page widget tree and right click to see get bug report code option. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/af31274a-1903-483c-92b1-840ebdbd0ad2)

I just investigate the issue and confirm that, web page can access when page got gradient texts. See below. If issue still persists at your end, a quick video showing the issue is more useful and also any error in browser console. Please share these details.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/cc78249d-eef9-4cbc-a29f-567c22b85cfc

**Comment by Rmolimock** [comment]
I'm having the exact same issue. It renders text perfectly fine without gradient but with gradient the text is cut off. No other differences.
<img width="423" alt="Screenshot 2023-09-30 at 8 36 56 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/38747720/661be69b-6aa5-4aea-bf9e-7d9810f926b9">
<img width="456" alt="Screenshot 2023-09-30 at 8 36 52 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/38747720/bf846efd-2d42-4e72-a71d-35039aaa0de0">
<img width="500" alt="Screenshot 2023-09-30 at 8 34 28 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/38747720/73c8bdb2-7da0-434a-8b20-78804bc2d0fc">
<img width="519" alt="Screenshot 2023-09-30 at 8 34 22 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/38747720/02e4ac7e-f39e-4af2-833b-f756d232bba9">

**Comment by kinyuajoe4** [comment]
Facing the same issue too.Renders the text perfectly without gradient but once gradient is added some of the text characters are cut off.
