### ISSUE TITLE
Page Param issue while passing 'Uploaded File (Bytes)' data.

### ISSUE THREAD

**Issue by flutterflowdevs** [FlutterFlow/flutterflow-issues#1170]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to pass local image files from one page to another in the Flutterflow project then its giving runtime errors.
Please find below error Screenshot

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126557523/3a6a41b9-4023-4d7a-8afe-9b56705d5f02)

### Expected Behavior

After using the 'Uploaded File (Bytes)' data type as a page parameter in the Flutterflow project, the app should run successfully.

### Steps to Reproduce

- Create two pages named 'Page A' and 'Page B' in your Flutterflow project.

- Implement the following in 'Page A':
    1. Create a button called 'Select Images'
    2. Add an action named 'Store Media for Upload' to the button, with the media source set to 'Gallery'. This action allows users to select multiple images from their gallery and stores the uploaded images as a list of files.
   3. Create one more button named 'Move to Next Page'.
   4. Implement the navigation to 'Page B' and pass the uploaded image files as page parameters.

-In 'Page B':
1. Display the count of files received as page parameters.

By following these steps, users will be able to select multiple images on 'Page A', and upon navigating to 'Page B', they will see the count of uploaded files displayed.

This is an demo app only for reproducing the error in flutterflow project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8nf/Y9ItbwA7aX2a+1r/Ck6JkAjars4scp/bxIgGIDzPOw+ZPWlYRBpYOm5TFFUJUSmmmIfw6zIiobTDPQENT+abbU4yZYBdgyXIXKge5OBPLi0eUclTMBYBXKm056v3RR4HNNoWk4D1E7zN+iiQXXvO6b2IlFISq/LZO4=

### Context

To address the issue encountered while building the client project, we have created a demo application. This demo application allows us to replicate the problem easily and enables us to report the specific issue effectively.

### Visual documentation

When I am debugging the issue then I found out, There was an import package line is missing in Flutterflow Generated code. Please check the video
https://www.loom.com/share/84e584a4555e452f840b3fe136c619e1?sid=fb056bfa-5ba0-4a6d-8f50-35f61e3bfdab

### Environment

```markdown
- FlutterFlow version: v3.1-3.10.4 
- Platform: Flutterflow Panel
- Browser name and version: Chrome 114.0.5735.248
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Thanks @flutterflowdevs for reporting the issue.

**Comment by sbis04** [comment]
I believe a fix for the compilation bug is already deployed! However, I found another bug that doesn't deserialize the `UploadedFile` properly when passed to the second page. I'll try to get a fix for it soon.

**Comment by sbis04** [comment]
Should be fixed in the next deploy!

**Comment by ABDULSidgs433** [comment]
Getting the same issue when I passed the uploaded file through params from screen A to Screen B build failed due to " The argument type OBJECT can't be assigned to the parameters type Unit8List"
