### ISSUE TITLE
Wrong header in pageView action editor. "on swipe" instead of "on data change"

### ISSUE THREAD

**Issue by yairpe** [FlutterFlow/flutterflow-issues#1171]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

wrong action header on page view actions

### Expected Behavior

Instead of two "on swipe" types, it should be "on swipe" and "on data change"

### Steps to Reproduce

1. create a pageView widget on a page
2. Open actions editor for this pageView 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci/LqwIhjpbxb7aXqacFvryQsIjs/RYINiMEaRgIdJ5PMC5kAYffAXFJWUuG0S1ZIM2aJkmEe09XemvL2V+wpNgWYRtU7yZZIEgmWXjihVLqwCLmCfm5/DeBMf0/G0MCFhCZ5OtRiS3dm62eAAu6uQh3DNZzWDDIvAfykA5CK2SrDX1iXc2URm05KZDPz

### Context

It does not affect me as I do not use on data change but as you can see from the screenshot, it's definitely a bug

### Visual documentation

![ff_issue](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/8317f9bf-1e42-45d0-ab58-751f5f674c6b)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: Win 11
```

**Comment by hariprasadms** [comment]
Hi @yairpe - Thanks for reporting the issue. I looked at the project but It is not a blank project with issue setup so not able to investigate the issue. Please create a blank project with issue setup and share the bug report code of the project. Once these issue is updated with these detail, I can re-investigate the issue. Thanks

**Comment by yairpe** [comment]
It shows now only 'On swipe' so I guess it is fixed.
Thanks
