### ISSUE TITLE
It should be possible to push to github even if the project has errors

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#1172]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In our projects we sometimes get an error message that github repository is not initialized even though we initialized our github repositories over a year ago.

From our experience, it seems that this can happen when FF is unable to parse custom code. However, sometimes we need to be able to push to github in order to troubleshoot the code locally.

Having github push be blocked because or code parse errors makes debugging difficult. In worse case the error is not obvious and we have to stop development and contact support and wait.

Additionally, because of the large amount of custom widgets and actions in our project, we are not able to comply with the error's suggestion of fixing errors, because FF is unable to compile custom actions and widgets having full context. Hence our projects have to live with existing "baseline" number of errors.

### Expected Behavior

The error message should only show up when there is in fact an uninitialized github (or a specific error pushing to github).

Just like an IDE, FF should not block us from pushing to github because of some error with the codebase.

Alternatively, the error should provide more specific information (eg a log snippet of where the issue occur) so that we do not have to wait for customer support.

### Steps to Reproduce

Exact steps are unknown as some of the underlying root causes of this error are nontransparent to us.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcnfz5Fgod9c1rrUK/lahmU5JlN9RI0Nke57aCosfZT2BLMcec/RVERpTde6TXxUPmKGmWoW0MqMktnPG8Y7EzKqQKI4+M0BbwnzVjmWb8mrFJWgZnQmBcZRBUiB37eN2RNDBONaLWct2zqDN+jLcCbANOPXIXoWDq/LZO4=

### Context

We sometimes have to stop our development and wait for support, which is counterproductive if we could push the broken project and troubleshoot locally ourselves.

### Visual documentation

<img width="427" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4561505/b827893c-3989-441a-8d1e-4f4d987ee90c">

### Environment

```markdown
- FlutterFlow version: v1.1.90 (MacOS Desktop)
- Platform: Apple M1
- Browser name and version: N/A (Native)
- Operating system and version affected: MacOS 13.4.1 (c) (22F770820d)
```

**Comment by hariprasadms** [comment]
Hi @isegal Thank you for submitting the issue. This is working as expected as per design. It is potentially a feature request. 
As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!
