### ISSUE TITLE
Webview not open App's links

### ISSUE THREAD

**Issue by bthomazfdlmx** [FlutterFlow/flutterflow-issues#1173]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have a project that load a page into the Webview. When a user click to a button that redirect to a app installed on the smartphone a error page appears.

![Screenshot_20230726-173030](https://github.com/FlutterFlow/flutterflow-issues/assets/79335052/21859efc-334c-4293-b9bf-58ac60a9ba89)

The link is https://api.whatsapp.com/send?phone=[PHONENUMBER] or any link on whatsapp documentation https://faq.whatsapp.com/425247423114725/?locale=en_US&cms_platform=iphone

### Expected Behavior

Open WhatsApp installed on the phone of the user.

There are several codes on flutter to redirect this kind of urls inside a Webview

### Steps to Reproduce

1. Create new app
2. Configure Webview to https://clube.michstore.com.br/
3. Click on WhatsApp button.
4. Error appears

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48h8/lz89Pm7VE7qX2KfpVgiYvKUc7RJIViep9YE08J5jGBIkMWMzBUBFUOcumY3xAIln9rHEX/MrWjYTDFPE4AzGYRrZnzblfEwuWe3OhaKaSEb63b3FAROxnCkjG18KnnBJ4Ku1vcmRn2mCxN+iiTT7rN4DJDWweAOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

The final user configure dynamic links to open WhatsApp and Facebook share buttons on the website. Because of that this kind of buttons not work on the device of any users.

### Visual documentation

After 

1. Create new app
2. Configure Webview to https://clube.michstore.com.br/

Publish the app and download it on device, when you see the webview click on WhatsApp button and the error appears.

![step1](https://github.com/FlutterFlow/flutterflow-issues/assets/79335052/e61c9d02-eb78-462a-a2e2-b658b572d2b7)

![step2](https://github.com/FlutterFlow/flutterflow-issues/assets/79335052/1a0e2b35-d7f4-40b0-858a-618da43c2225)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Mobile
- Browser name and version:
- Operating system and version affected: Any Android
```

**Comment by vnbogdanov2020** [comment]
I have the same problem. Moreover, if you pack a Deeplink to the application page into an html file, open the file on the device and click on the link, the application opens on the specified page. And if the same code is placed in a WebView widget, then when you click on the link an error appears. Looks like a problem with WebView...
![279340014-6253f605-3bc1-4301-98d8-aab628e3cb89](https://github.com/FlutterFlow/flutterflow-issues/assets/64920418/10a7e74a-ec62-4a06-8a8e-0213679dcb5a)

**Comment by mateusioliveira** [comment]
@bthomazfdlmx Did you manage to solve it?

**Comment by vnbogdanov2020** [comment]
Unfortunately there is no solution yet. The question is still very relevant. In the latest versions the problem is also observed

**Comment by 032331** [comment]
Hola amigos, Ya lograron solucionarlo?

**Comment by vnbogdanov2020** [comment]
Unfortunately there is no solution yet. The question is still very relevant. In the latest versions the problem is also observed

**Comment by vnbogdanov2020** [comment]
> Hola amigos, Ya lograron solucionarlo?

Unfortunately there is no solution yet. The question is still very relevant. In the latest versions the problem is also observed
