### ISSUE TITLE
Action Flow Editor suddenly zooms in

### ISSUE THREAD

**Issue by Jeroen-R** [FlutterFlow/flutterflow-issues#1175]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In an (Excellent) recent  change, using the mouse wheel in the Action Flow Editor scrolls the flow. This is quite the improvement from the previous 'zoom in / out' behaviour when using the scroll wheel.

The strange thing is that it largely works, but sometimes it just zooms in the Flow with no way to reset the zoom level.

 

### Expected Behavior

Using mouse scroll wheel should ONLY move through the flow and not randomly zoom in / out.

### Steps to Reproduce

I cannot consistently reproduce, but it has happened several times. I am on M1 using latest MacOS 

Try opening a flow and repeatedly scrolling up and down. it may be caused by pressing / holding ctrl and fn keys (not at the same time) on my mac keyboard. Still not consistend. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giPHq2It2m+FF7rruYO9WpD0XJWF9RJc0st4bGAsdGOvrBuwcZsmkSE9CTum6aVNce1KijnI1zMrUuOPUU8EFEy2eG59y1qtIFgvke2iiVqqDPLuCdHNAHeNjIHKw4JinhyNTCPN0WkYa7F6EF/PIQgHDBOu/Zwh9f6PHaOI=

### Context

It is annoying, I now need to go out of the Flow Editor and go back in. 

### Visual documentation

It suddenly zoomed out. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10716254/9599637d-0b95-42ea-9ec7-c4be1e638b1e)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Mac
- Browser name and version: Brave (same as Chrome) Version 1.56.9 Chromium: 115.0.5790.98 (Official Build) (arm64)
- Operating system and version affected: Ventura 13.5
```

**Comment by hariprasadms** [comment]
Hi @Jeroen-R - Thanks for reporting the issue. I'm not able to reproduce the issue.  Please reproduce the issue in a blank project and share bug report code of the project. A quick video showing the issue is more helpful to speedup the investigation. Thanks

**Comment by khomya** [comment]
I have the exact same bug

**Comment by khomya** [comment]
My bug looks like this too! But because my trees of actions more complex - the bug appears on 2nd or 3rd scroll through the page.
