### ISSUE TITLE
Page level Action Block boolean return value causes error

### ISSUE THREAD

**Issue by Jeroen-R** [FlutterFlow/flutterflow-issues#1176]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In an Action Block with a boolean return value, I add the Return Action in the flow.

It presents me with a dropdown menu to select the return value with options True and False. Selecting one of these options results in an error 'Return action value is improperly set.'.

However, setting it to a true or false constant works fine.

### Expected Behavior

I expect both fixed values and constants to work. 

### Steps to Reproduce

1. Create Action Block of type Page (App works file)
2. Set return type to boolean
3. Insert any action, e.g. Navigate Back
4. Insert Return Action
5. Select 'true' from the presented dropdown menu.  
6. You will now see the error message.
7. Click the 'variable' icon
8. Lookup the 'True' constant and select it
9. The error will go away
10. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Return action value is improperly set.

### Context

Took me a while to figure out so time lost, but I figured out a workaround. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10716254/abbf58ae-efbd-4a0d-bc73-5d0f0ece0a30)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10716254/5a2abeb8-87a0-4b04-8567-a1bc6f661a8d)

Return action value is improperly set.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS
- Browser name and version: Version 1.56.9 Chromium: 115.0.5790.98 (Official Build (arm64)
- Operating system and version affected: Ventura 13.5
```

**Comment by hariprasadms** [comment]
Hi @Jeroen-R - Thanks for submitting the issue. I have tested above steps and I can see it works fine. No errors. Not able to re-produce the issue. If this issue still persisting, can you share a quick video showing the issue please.

**Comment by hariprasadms** [comment]
> The video is no different from the screenshots, but here you go.
> 
> Looks like you cannot accept the default 'False' value without error. You have to set it to True and then back to False to make the error go away.
> 
>  Return.Value.mov

Hi, Thanks for sharing the video. I can say that, it is working as expected. The behaviour what you seeing is as per design. on editor, till you select the value, the value is not assigned to the variable. You can see that once it is selected true/false, the error is gone. In all the places, it is working same way.

**Comment by aemelyanovff** [comment]
@Jeroen-R Thanks for reporting the issue. You are right, it's a bug. It will be fixed in the next update.
