### ISSUE TITLE
Youtube embed not displaying full screen

### ISSUE THREAD

**Issue by globaljewishfuture** [FlutterFlow/flutterflow-issues#1177]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on the full screen icon on the bottom right of the YouTube player, the screen orients to landscape and cuts off the bottom of the video, rather than creating a full screen view on the mobile device (the entire mobile device). Screen shot attached.
![IMG_2047](https://github.com/FlutterFlow/flutterflow-issues/assets/140717409/f3e3b2d8-34ac-4a15-b5d4-ca30a4d676c3)

### Expected Behavior

The video should play on the entire mobile device.

### Steps to Reproduce

When I click on the full screen icon on the bottom right of the YouTube player, the screen orients to landscape and cuts off the bottom of the video, rather than creating a full screen view on the mobile device (the entire mobile device). Screen shot attached.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTivHl7ZNInMRH+KrhYfkxoDsQGUMdXOczitVEew4bCIj4B7AfdcjBUFtCYMSzaHw7fFekmjkF0PyOvfDPG/UnH0utRYhxzbpAaRPPbGKgV66NCbm0Y0F7BfNXCEDG38OSkSZ7JtRvLXwN2U+MGtm8az6Cf9qOYwx5e6fDbOY=

### Context

When I click on the full screen icon on the bottom right of the YouTube player, the screen orients to landscape and cuts off the bottom of the video, rather than creating a full screen view on the mobile device (the entire mobile device). Screen shot attached.

Page: SpecificVideo

### Visual documentation

Here's an image:

![IMG_2047](https://github.com/FlutterFlow/flutterflow-issues/assets/140717409/ecee19e0-43dc-4540-89f8-b4f06e656353)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS
- Browser name and version: Chrome 114.0.5735.198
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment]
Hi @globaljewishfuture - Thanks for submitting the issue. I can reproduce the issue.

**Comment by globaljewishfuture** [comment]
Hi, what is the status of this bug fix?

**Comment by Finnalli** [comment]
Any update on this? I am having the same problem when I deploy to mobile. I have tried to force a full-screen mode by locking the device orientation to portrait (see FF marketplace), however the device orientation somehow switches back to landscape when I try to view the video in full-screen.

**Comment by mlafuentem** [comment]
Same problem here. The video doesn't go to full-screen mode but simply changes the orientation to landscape. This isn't very pleasant to the user, this is confusing and we can't publish this as it is now. Any progress on this bug? Thanks.

**Comment by agreaves** [comment]
Hi @globaljewishfuture and all, thank you very much for the bug report and sincerest apologies for the delayed response. I've been able to reproduce and fix the issue, so fullscreen should now be working in the next release! Sorry again and thank you for your patience.
