### ISSUE TITLE
Api manager get brooked after FF update while parsing query parameters

### ISSUE THREAD

**Issue by danielmeza** [FlutterFlow/flutterflow-issues#1178]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The latest version of FF has introduced a change in the api manager to URL encode the parameters value, that's a good notice, but that change introduce some bugs in non-strings parameters, since parameters can be different from string (Integer, Double, Boolean etc.) try to just pass a dynamic type value to the  Uri.encodeComponent method raise errors on runtime and break the application. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/65cd023d-2283-43d5-ae39-5b8c2c50b1b1)

### Expected Behavior

The asQueryParams shall not throw exception for non-string build-in types. 
This line fix the bug. 
"${Uri.encodeComponent(e.key)}=${Uri.encodeComponent(e.value?.toString() ?? '')}")

### Steps to Reproduce

1 Define a API Call, create a non-string query parameter and bid it to a Integer variable. 
Call the API sending any Integer in the query parameter. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xlcr1z4xOsdtF7s/uYO9VhjwROVg/a7geltZxYw81F4zqP7AfOvf+T3BZOMu6dFZUP2GJmm0yp97Lkd7LCO5cPhyJbNl5/rpISjvxQjihR5C0OqrteURAEfNgI3KCzpuZgAkkBMBhSk4mw0OqOuuUZAnAO5P6OG1MOP//FID++WC8KhzGGX0Jg1ZSfCvr

### Context

This issue is impacting all the endpoints with non-string query parameters in my app, a lot's of pages are not working any more. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/12b13711-4112-4f68-afd5-d9ca3e4f3699)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/0c33acbf-b2b8-4347-8aa2-29f30f225f0a)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by danielmeza** [comment]
@hariprasadms @agreaves I see that a fix has been apply, but it doesn't fix completely the bug
The fixed line is now `"${Uri.encodeComponent(e.key)}=${Uri.encodeComponent(e.value.toString())}")`
But is hdoul be `"${Uri.encodeComponent(e.key)}=${Uri.encodeComponent(e.value?.toString() ?? '')}")`
This is because the parameter value can be null, in these cases the code will raise exceptions as well.

**Comment by danielmeza** [comment]
@manishionc I had to change the code to this '${Uri.encodeComponent(e.key)}=${Uri.encodeComponent(e.value?.toString() ?? '')}' line 118 in api_manager.dart file 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/267b02df-543d-4b51-8be2-ad08322156ef)

**Comment by yokawaiik** [comment]
I have the same problems with requests' headers. I faced to this problem this week.

**Comment by danielmeza** [comment]
@yokawaiik there is also a weird behavior with query parameters bind to a List variable,  as an http standard multiple parameters can be send in an uri just duplicating the parameter name, like `'http//host?user=daniel&user=yoka' `but instead of this the api_call is converting this into a JSON array :/ this also break my queries

**Comment by manishionc** [comment]
I don't know why but some parameters works and some don't. 

Like -- one of parameter is -
filter=subject='object' -- is not working.
But it was working before the update.

I am using 

(Filter=subject) as parameter 
('object') as value.  
Fields = I'd,title is working 


Is there a way I can make it work the filteration .
I have a deadline .

**Comment by danielmeza** [comment]
@manishionc what kind or typoe of parameter is subject?

**Comment by manishionc** [comment]
I found a workaround for API calls and finished the project thanks you.

**Comment by yokawaiik** [comment]
Any updates coming soon to fix this issue?

Even test requests to API from FF do not work.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/48886721/a54d9f9d-f730-48fa-a65c-52f2e3ce1cf9)

**Comment by yokawaiik** [comment]
There are a solution to this problem.

I've used Firebase cloud Functions Gen-2, but I had forgot switched Authentication in state "Allow unauthenticated invocations" option in security tab (Cloud Run options for functions). After I had switched on the option requests were done successfully.

This problem looks like FF or dart library problem but it isn't so.

Good luck 🍀.

**Comment by agreaves** [comment]
Hi @danielmeza and @manishionc, apologies for the delay in responding as I thought this was still referring to the original issue. I believe the `e.value?.toString() ?? ''` fix should not be necessary as `null.toString()` still properly evaluates.

Are either of you still experiencing this issue? I believe it should be resolved.

**Comment by agreaves** [comment]
Closing as the original issue appears to be fixed. Please re-open or create a new issue if you experience a similar issue!

**Comment by gusdevx** [comment]
> I found a workaround for API calls and finished the project thanks you.

What was the solution?
