### ISSUE TITLE
Getting blank screen in programming mode

### ISSUE THREAD

**Issue by fabughali** [FlutterFlow/flutterflow-issues#1179]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dear team,
I am building a new project in FlutterFlow. I finished home page and then I started to design ABOUT page. Everything was okay until I tried to use Gradient option to apply it on a text. The page (About) become blank and no more open. HOME page is working fine. But there is an issue with reloading Abou page. Also, I could not reverse the status (going back to previous backup). I think I did not YET make any version for my app.

Note: this status is on programming mode (not in test mode neither in run mode)

Kindly help me.

Regards
Fuad Abughali.

### Expected Behavior

the text should have gradient option. but the page is completely blank after i tried to activate gradient option to a text.

### Steps to Reproduce

1- i created new page. the page is having by default a column, let me name it "column A".
2- i added container as a child of the "column A". and inside this container, and i set a background image of the container from my images in the assets.
3- i added a new column to this container as a child, let ma name this second one "column B". and then i added a text to this "column B" as child.
4- i set the font size according to "if" statement. the font size will change according to screen width.
5- i tried then to activate the gradient for this text. but then i god a complete blank screen. also, i could not have a chance to deactivate the gradient option for this text.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhsrq5ot1xMtd7q6JacFshWIvH2kcTeU7lexsaxAaI+PyE7MUfsnRM1tBWOqHS1BbPmaanmYG7tr9iob1Ou07PQWBGdVTyZN1UxDjXnOVVZSqCpGwOUBAGfhTIX7H0qeFsRVNKrRudFI66k2Lf9+Qb3qCf9qOYwx5e6fDbOY=

### Context

i am trying to continue working on the page or reverse my gradient setup for the text. but i could not.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/57118779/d7b8ff59-88ea-4a4b-99e3-581037c227e3

### Environment

```markdown
- FlutterFlow version: 3.1 - Flutter 3.10.4
- Platform:
- Browser name and version: MS-Edge Version 115.0.1901.183 (Official build) (64-bit)
- Operating system and version affected: Win 10 Pro 64-bit (10.0 build 19045)
```

**Comment by hariprasadms** [comment]
Hi @fabughali - Thanks for reporting the issue.

**Comment by vishalagarwal2** [comment]
Hi, I went into the issue and could not duplicate the bug. Let us know if you're still facing this issue!
