### ISSUE TITLE
Can not compile a custom widget that imports components.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#118]
This is working code but cannot compile. So, I have to exclude it from compile.
And I think this is about the time for FF to fix it to make it work.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/5080329/201260104-10bdeb42-dce5-4465-8473-618183334f76.png">

**Comment by agreaves** [comment]
Hi @thruthesky, thank you for the report. This is actually a known limitation of the current custom code compiler and in fact the primary reason that the "Exclude from compilation" button exists. We plan in the future to allow the compiler to have access to the entire codebase, but for now I'm marking this as a feature request.

I will update this thread when this is now possible!
