### ISSUE TITLE
Google map setState

### ISSUE THREAD

**Issue by al-mahi** [FlutterFlow/flutterflow-issues#1180]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not an expert on code. found some fix of issues i faced using chat gpt
1. Multiple google map instance will causes crash
2. A marker on map which has been removed can cause memory leak if not checked if the 

### Expected Behavior

```
correct code:
@override
void setState(VoidCallback callback) {
if(mounted) super.setState(callback);
_model.onUpdate();
}
memory leaky code:
@override
void setState(VoidCallback callback) {
super.setState(callback);
_model.onUpdate();
}

correct code
if (!_controller.isCompleted) {
_controller.complete(controller);
}
code that will crash if multiple google map is used:
child: GoogleMap(
onMapCreated: (controller) async {
_controller.complete(controller);
await controller.setMapStyle(googleMapStyleStrings[widget.style]);
},

```
### Steps to Reproduce

create two pages with google map
the first will work fine but second one will crash

if a marker document is removed but in map it is not update and click event will cause memory leak issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

correct code: @override void setState(VoidCallback callback) { if(mounted) super.setState(callback); _model.onUpdate(); } memory leaky code: @override void setState(VoidCallback callback) { super.setState(callback); _model.onUpdate(); }  correct code if (!_controller.isCompleted) { _controller.complete(controller); } code that will crash if multiple google map is used: child: GoogleMap( onMapCreated: (controller) async { _controller.complete(controller); await controller.setMapStyle(googleMapStyleStrings[widget.style]); },

### Context

cause my app to crash

### Visual documentation

None

### Additional Info

correct code:
@override
void setState(VoidCallback callback) {
if(mounted) super.setState(callback);
_model.onUpdate();
}
memory leaky code:
@override
void setState(VoidCallback callback) {
super.setState(callback);
_model.onUpdate();
}

correct code
if (!_controller.isCompleted) {
_controller.complete(controller);
}
code that will crash if multiple google map is used:
child: GoogleMap(
onMapCreated: (controller) async {
_controller.complete(controller);
await controller.setMapStyle(googleMapStyleStrings[widget.style]);
},

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:ios
- Browser name and version: chrome & 114.0
- Operating system and version affected: mac os ventura
```

**Comment by hariprasadms** [comment]
Hi @al-mahi - Thanks for reporting the issue. The bug report code you provided above is invalid one. You can get the bug report code from widgets in any pages. See below. 

Also, for this kind of issues, we need a quick video showing the issue and blank project with issue setup to expedite the issue investigation. Please update the issue with these details. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/3fc5a65e-4795-4d0f-9ded-5e648374c5ff)
