### ISSUE TITLE
Stripping . from permission field. Required for Health Data

### ISSUE THREAD

**Issue by devtechdigital** [FlutterFlow/flutterflow-issues#1181]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding a new permission has two fields, the permission name and the permission message.
Permission name is a string that has a leading android.permission. then the field. In most cases remainder of the string does not need a "." 

However for health connect

<manifest>

  <uses-permission android:name="android.permission.health.READ_HEART_RATE"/>
  <uses-permission android:name="android.permission.health.WRITE_HEART_RATE"/>
  <uses-permission android:name="android.permission.health.READ_STEPS"/>
  <uses-permission android:name="android.permission.health.WRITE_STEPS"/>

  <application>

We would therefore need to add e.g. health.READ_HEART_RATE 
This requires us to add the "." in the field to complete correctly.

We understand we can add to the manifest file after but it would be better to be able to manage internally.

### Expected Behavior

The ability to add "." to the permission name.

### Steps to Reproduce

1. Go to settings
2. Go to permissions
3. Add new permission
4. try to add health.READ_HEART_RATE in field to create android.permission.health.READ_HEART_RATE in the manifest file.
5. The "." is tripped from "health.READ_HEART_RATE" to be "healthREAD_HEART_RATE"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjeflwItNobgA7qXybO9agmM4JmI+RK00st5Hd0gdCOPrBuw1dsmlVFhDTcCraVNcHVKWoEcxpqHsuOHDFPUCBzWrbLU51qhUUTzke2iXR82YBqqwR0ZPHexXfHa/0MO3oh1+Ksdtcndm7FzzAuSifz7DFOu/Zwh9f6PHaOI=

### Context

We want to access Android health & fitness data collected via devices. 
We can make this work but only by modifying the manifest file outside of FF which will be over written on future modifications of the app requiring us to redo. Not too difficult but not very elegant.

### Visual documentation

<img width="722" alt="FFIssue02" src="https://github.com/FlutterFlow/flutterflow-issues/assets/92008112/84b2a7b9-27a4-4b8a-b068-4a4cdad185c8">

### Additional Info

sd

### Environment

```markdown
FlutterFlow version: NA
Browser name and version (web): NA
Operating system and version (desktop): NA
```

**Comment by hariprasadms** [comment]
Hi @devtechdigital, Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature enhancement / requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritise feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!

**Comment by aemelyanovff** [comment]
@hariprasadms I think it's closer to a bug than to a feature request, thought the distinction is not so clear. And it's very easy to do.

@devtechdigital Thanks for reporting the issue. It will be fixed in the next update.
