### ISSUE TITLE
Regarding timezone package loading issue in FlutterFlow.

### ISSUE THREAD

**Issue by IndumathiR-1995** [FlutterFlow/flutterflow-issues#1183]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Timezone package was not loaded  in our custom widgets.

### Expected Behavior

Need to load the Timezone package  in our custom widgets.

Timezone package link: https://pub.dev/packages/timezone

### Steps to Reproduce

1.	Create a project in FlutterFlow.
2.	Using the Custom code option add new widget ( wiget includes timezone package )and add the required code to run.
3.	Add the WidgetName as class name of the project 
4.	Then add the Pubspec dependencies.
5.	Then using UI Builder option drag and drop implemented widget in the display area and the timezone related was not loaded.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhvHqx4lIrsda7q6Jdfpv+T47JVMcTL4zlO1HcxAYGO/yPbJ+eMz7NhNBXt+5YGlhHFeLmjoC06n7k+PxJ/oCCE+Yfbo5z85cZxXvc3q8RZ/QO5eKeHMlDfJhGEigy6W3oQp7JtJ1ZXgH2meEJd7LTgLrGZO/Zwh9f6PHaOI=

### Context

We have used the timezone package in our widget for timing related scenarios. It was working fine in our widget. But using the FlutterFlow unable to load the timezone package.

### Visual documentation

1.	Create a project in FlutterFlow.
2.	Using the Custom code option add new widget ( wiget includes timezone package )and add the required code to run.
3.	Add the WidgetName as class name of the project 
4.	Then add the Pubspec dependencies.
5.	Then using UI Builder option drag and drop implemented widget in the display area and the timezone related was not loaded.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hi @IndumathiR-1995, thank you for the report. We do not generally debug custom widgets or actions in the GitHub issue tracker as it's intended for general issues. So I'm closing this as a project specific issue.

However, I believe this is because this package needs to be initialized at the start of the app run. You can do so by including the initialization in the `main` section of custom code. Hope this helps!
