### ISSUE TITLE
Audio Player not working properly on iPhones

### ISSUE THREAD

**Issue by ndigacin** [FlutterFlow/flutterflow-issues#1186]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The audio player play in background does not work on iPhone. It does work on Androids though.

### Expected Behavior

When activated, the play in background is expected to allow the audio to continue to play when the app is running in background. On iPhones, it stops playing when the app is in background or when the phone goes into sleep mode.

### Steps to Reproduce

use audio player in flutterFlow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESiMrq7YlgruIE+6rQcO16hQUkKVwkaIJEs+1uZ00jF5D4OrMiYuClVxFoTbGzaH9YGlWLrEQK+M7ShuLpJccFGAqcbYhm1rhxERPPbESlbLaSPMyOYnZCEdpYBWKY1JmnuQp4FNFYL0IC72CQOfPJbz6Cf9qOYwx5e6fDbOY=

### Context

Not too much but it would be good to get it worked.

### Visual documentation

![Screenshot 2023-07-29 at 9 23 43 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/116641569/f7d77a5f-3939-4fa6-b1f8-da2773f7c2d8)

### Environment

```markdown
- FlutterFlow version: last version
- Platform: FF Desktop
- Browser name and version: last version
- Operating system and version affected: Mac OS
```

**Comment by kevintonb** [comment]
Hey @ndigacin , I have tried to reproduce the issue and was not able to do so. The audio player works perfectly fine in both the foreground and the background. I would kindly request you to recheck the audio file that is being sourced to the audio player widget for any corruption. If you face any other issues please feel free to reach out to our support team at support@flutterflow.io! :)
