### ISSUE TITLE
Navbar responsive settings - shows navbar in FF builder regardless of viewport settings  

### ISSUE THREAD

**Issue by mardadi23** [FlutterFlow/flutterflow-issues#1189]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have set the nav bar to only show on mobile phones. However, it still shows in the builder when I preview the page using tablet or desktop.  

- Set to show only on mobile phones
<img width="846" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/135a01dd-13cd-45f1-a4fb-a384512b2d07">

- showing in tablet view
<img width="788" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/86514fbd-3a56-4a73-b096-9c13632dbd38">

However, when I debug the app, the navbar doest show on tablet or desktop. It looks lik ethe preview in the builder is the issue. 

### Expected Behavior

Show or hide the nav bar in the builder preview as per the settings in the NavBar 

<img width="716" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/817f36e4-a6c2-49d7-8854-7b8d02a061b4">

### Steps to Reproduce

1. Create 3 different pages
<img width="174" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/3c657bd0-3f3a-4cab-8824-0efe37ad55a5">

2. Set all pages to appear in the nav bar

<img width="527" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/c4a36c3d-e9da-4314-95bc-fb4625f5abfb">

3. Set nav bar to appear only on mobile view

<img width="941" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/b7b3128f-7739-4684-8ea3-d50040579bab">

4. preview the page by clicking on widget tree 

5. the nav bar appears regardless of viewport - mobile, tablet or desktop 
<img width="1218" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/cde32ce6-aae0-4903-978e-02850cd6697c">

 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gobhb1pDca8BQhQIgQ0QnU7gnlO1ucx40Ib7nPJYXPOP4ZUNKTe2ETW5+elKjnnsC7vyKjYfxUu43OSerG6pI0JVAWgzLTXOXMLKmPs28eXJ7P5tTN0PD5Kak3RJDNvpqdVEt61ybNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Trying to build my responsive menus. For mobile, I want to use the built -in nav bar. For larger form factors like tablet or desktop, I am using the side menu widget that shows only when desktop is clicked. It's a bit confusing as I'm not sure of outputs in previews so now have to build everytime. Reduces confidence in the builder. 

### Visual documentation

<img width="1113" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/ecc8d64b-3e52-4b43-b645-415574825487">
<img width="1052" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132626866/e5df249a-1ef4-483b-8a52-acd9738581d1">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web app
- Browser name and version: Mac desktop App
- Operating system and version affected: Mac OS 16.6.6
```

**Comment by kevintonb** [comment]
Hey @mardadi23 , I have tried to reproduce this and was successfully able to do so. The responsive visibility doesn't working in the canvas and preview mode but takes effect when you run or test the app. Thank you for bringing this up to our attention! :)

**Comment by vishalagarwal2** [comment]
This issue has been fixed and will be applied in our next deploy!
