### ISSUE TITLE
Cannot import csv in firebase with many columns. button to confirm fields creation not visibile

### ISSUE THREAD

**Issue by GiovanniBaldo** [FlutterFlow/flutterflow-issues#1190]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've a csv file with many columns. I want to import in a new firebase collections. FF will create fields for me. but when I try to confirm the fields the button to confirm is partially visible or not visibile at all. I can't click on it so it's not possibile to proceed

### Expected Behavior

after selection the csv and verifying appropriate data type for each column it should be possibile to import confirming fields creation

### Steps to Reproduce

1 create new collection
2 go to manage content
3 import a csv files with many columns (> 15 for example)
4 when u need to confirm creation of fields button is not visibile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

1212121

### Context

i'm prototyping and I need sample data that I import from excel

### Visual documentation

<img width="1470" alt="Screenshot 2023-07-30 alle 00 07 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/70816346/306b0e11-cfb3-4545-816a-a1ed0bac0935">

### Environment

```markdown
- FlutterFlow version: 1.1.93
- Platform: 
- Browser name and version: chrome Versione 115.0.5790.114 (Build ufficiale) (arm64)
- Operating system and version affected: macos ventuna 13.4.1
```

**Comment by kevintonb** [comment]
Hey @GiovanniBaldo , I tried to import a CSV with 20+ columns and was able to reproduce this issue successfully. Thank you for sharing this bug with us! :)

**Comment by aemelyanovff** [comment]
@GiovanniBaldo Thanks for reporting the issue. It will be fixed in the next update.

**Comment by bossanovaweb** [comment]
+1
