### ISSUE TITLE
Subcollection backend query not respecting the parent reference

### ISSUE THREAD

**Issue by hfcprog** [FlutterFlow/flutterflow-issues#1192]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm performing a query on a subcollection using its parent as a reference, but as a result the list displays all documents in all the subcollections and does not respect the parent reference provided.

I noticed when enabled and disabled infinity scrool change the behavior

this behavior appeared after the June 13th update

I contacted support and was asked to open this issue

### Expected Behavior

The query must return the list of documents only for the indicated parent ref

### Steps to Reproduce

1 - Create a project with firebase and authentication
2 - Create a "collection" and a "subcollection"
3 - Include some records in the "collection" and each of them with some records in the "subcollection", importat to have a filed number to order by
4 - Change permission rules for "authenticated users"
5 - Create a screen with a query for just one record in the "collection"
6 - Create a backend query in a listview of the "subcollection" with reference to the previous "collection" query
7 - In this ListView backend query ad ordering by a number
8 - Enable infinity scrool

https://app.flutterflow.io/project/provas-nlyp3t
https://app.flutterflow.io/run/BNc3QDateineTTrN8LHH

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMjfsM11rsBE1pDALMBGgmAwGUwCaI0z0tlETRQdfuP0PIY2YfT4UEpuWOqHf1diA2GjvD40w+zKjuLiV8cCJgqAbJxDwsxtUxDvQTmtVYymEc6SQERTP/lmIHHD4Z6VoSR+IsxhWEY42ma6DeyAb3qCf9qOYwx5e6fDbOY=

### Context

The query is returning documents from all subcollections, this is interfering with the application, I noticed something strange related to ordering when enabling infinity scrool

### Visual documentation

This is my query with ref:

![query](https://github.com/FlutterFlow/flutterflow-issues/assets/122238913/3f648820-2b4a-4588-b233-c107fc997b85)

https://github.com/FlutterFlow/flutterflow-issues/assets/122238913/a272646f-7622-4fe3-baee-8b1dc816c5fa

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform: Web
- Browser name and version: Chorme 114.0.5735.199
- Operating system and version affected: Windows 10
```

**Comment by MendesCorporation** [comment]
same problem here

**Comment by hariprasadms** [comment]
Hi @hfcprog - Thanks for posting the issue. We required below details to consider to investigate the issue. 

1. Blank project with issue setup and its bug report code of the project) - This is mandatory. Without this detail, it is difficult to investigate the issue. 
2. A quick recorded video ( Optional. But if you could provide this detail, it will help us to understand the issue quickly and speedup the investigation )

Please update issue with these details. Thanks

**Comment by hariprasadms** [comment]
Hi @hfcprog - Thanks for posting the issue. We required below details to consider to investigate the issue. 

1. Blank project with issue setup and its bug report code of the project) - This is mandatory. Without this detail, it is difficult to investigate the issue. 
2. A quick recorded video ( Optional. But if you could provide this detail, it will help us to understand the issue quickly and speedup the investigation )

Please update issue with these details. Thanks

**Comment by hfcprog** [comment]
Hello? any news? I have already added the requested information. Anything else I can do? @hariprasadms  @wenkaifan0720 @SameerShahzad99

**Comment by agreaves** [comment]
Hi @hfcprog, thank you for the bug report. You are correct this was indeed a bug, but this should be fixed as of late August. Closing for now but please let me know!

**Comment by LamDang** [comment]
Hello I still have this issue today
