### ISSUE TITLE
API Group Variable not populating in test mode

### ISSUE THREAD

**Issue by DeltaForce007** [FlutterFlow/flutterflow-issues#1193]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created an API group and given it a group variable of Authorization: Bearer [auth_token]. I then test the api from the Response and Test option and give the variable the required auth token.

The test passes and I get the response that I expect. 

When I add the api to a project and then run the project in test mode the group variable is passed like Authorization: Bearer [auth_token] without assigning the variable I am giving [auth_token]

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/002058c4-1d6f-4888-b0f4-8ed83bc90226)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/10b9360c-4ccd-4fd0-98a9-fc455593ec79)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/027c44c4-28d3-498e-af6d-70a54920af2a)

### Expected Behavior

I expect the variable that I am assigning to the group variable in the project to act the same way as when I test the api directly in flutterflow. 

### Steps to Reproduce

1. Create an API group
2. Give it a group variable 
3. add an api to use that group variable
4. use that api in a project
5. check request actually sent

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHl8ZFOxd9c0b6JYfoxpDsWQmEcTLkvjuphcz8YGIztBJh/ePfeSEloOMjgY2lhHGD/jXEG+c7luOHTEMAEJSeBG487+M5QbAnzTXq8Rq6yEoeVdGsnTdFVGnKa08CNhhElPtNoLWwB11+qOty8Vj7dCZ+/Zwh9f6PHaOI=

### Context

I am trying to call third party api's and can't proceed as I can't assign the auth token. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/002058c4-1d6f-4888-b0f4-8ed83bc90226)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/10b9360c-4ccd-4fd0-98a9-fc455593ec79)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23420174/027c44c4-28d3-498e-af6d-70a54920af2a)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS Ventura 13.3.1
```

**Comment by hariprasadms** [comment]
Hi @DeltaForce007 - Thanks for reporting the issue. I can reproduce the issue. This should be fixed in futures updates.

**Comment by Franco98404** [comment]
Here are other issues related to this:

https://github.com/FlutterFlow/flutterflow-issues/issues/420
https://github.com/FlutterFlow/flutterflow-issues/issues/417

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Those were old and it was raised when there was no support for variables in Api groups. Let's ignore those issues and they are closed now. 

I asked the development team to review this, and they confirmed that group level variables should not be used, nor should api keys or any other variable values that will be deployed as part of private api deployment. The deployment of cloud functions will not take such values into account. 

I would suggest do not use group variables for api keys.
