### ISSUE TITLE
Infinite scroll performance issue causing excessive data loading

### ISSUE THREAD

**Issue by coffeelydev** [FlutterFlow/flutterflow-issues#1194]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I noticed a significant performance issue on my home page. Upon investigation, I discovered that the infinite scroll is being called numerous times unnecessarily. Initially, I suspected that there might be an issue with the page itself. Consequently, I created a new page and implemented a function to print data in the console. To my surprise, the infinite scroll doesn't stop! Even without actively scrolling the page, it keeps loading more and more data...

### Expected Behavior

I was expecting just load 25 rows and when I scroll the page, another 25 rows will be loaded.

### Steps to Reproduce

1. Create a new page
2. Add a listView with infinite scroll with a collection with a lot of data
3. See that many documents are loading unnecessary.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcmA05J2odtD0a6JdO9VlmI4Ijt/RJIr0e1+Uis8GqLuPe0UWMzBUBFUOd/nS39YMGH8oHsX/MnIk/P1V+1eGxCCbKI9yKpQejrLfEW5eLKyBq63b3dSMNNhFUC9yKWNryVSOvJuR00u3GDyfee8bD3aQr2wOm1MDeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

A lot of documents are loaded.

### Visual documentation

<img width="958" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/111637971/705378fe-ee95-4b88-aabd-92a04e6def97">

### Environment

```markdown
- FlutterFlow version: 3.1 (released Jul 27, 2023)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  Windows
```

**Comment by coffeelydev** [comment]
Hi guys! Any news about this bug?

**Comment by hariprasadms** [comment]
Hi @coffeelydev - Thanks for submitting the issue. This details _The steps to reproduce above start from a blank project._ is required for us to reproduce the issue. The project bug report code you provided is the real project and not able to locate the page where you got the issue. Please provide below details.

1. Blank project with issue setup 
2. A quick video showing the issue. 

Thanks

**Comment by coffeelydev** [comment]
Hi guys! This prerequisite doesn't make any sense!!! I am a customer and I have to prove with a lot of job that it is a bug in your product!!!

**Comment by alfred1000351** [comment]
I've faced this issue as well, it just seems like the infinite scroll loads everything up front first so for the end user it gives the impression of a seamless infinite scroll. But for the developers it feels very counter-intuitive as we would expect it'll only load the first step of items we define and then load the next set as the user scrolls.

This shouldn't need a full bug report, as it's pretty simple to see what the issue is it's an issue we've been waiting for a while to get improved

**Comment by la22222** [comment]
i have the same problem

**Comment by tiagosilveiransj** [comment]
I'm facing the same problem with the web version.

**Comment by coffeelydev** [comment]
Hi @hariprasadms ! I think this bug is critical!

**Comment by la22222** [comment]
Hey guys, any update on this? It's becoming a significant issue. My ListView has 4k items, and it loads all of them at once, which freezes the app. @hariprasadms @coffeelydev

**Comment by coffeelydev** [comment]
Hi @hariprasadms ! Do you have any news about this critical issue?

**Comment by aemelyanovff** [comment]
Hi all,

A couple of tips:
* Make sure "Shrink Wrap" is disabled - it forces the entire list to load at once.
* Wrap the ListView in a container with some finite height.

If none of these help, please create a new issues **with specific steps to reproduce starting from a blank project** and a link to that project. These steps must include the exact list view configuration and the exact query configuration.
