### ISSUE TITLE
Public Link is not working

### ISSUE THREAD

**Issue by JonathanSMN** [FlutterFlow/flutterflow-issues#1195]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I copy a Public Link from my App's Preview and paste in any browser, it doesn't show my app. It looks like an static image is overlapping my app page.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/64733278/fa24dab0-85aa-42df-b525-e6383cedb79d)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/64733278/ab551f43-e32e-41cc-a58f-058656bd0a75)

### Expected Behavior

It should open my app preview in an public link, so I can share my app layout with anyone.

### Steps to Reproduce

1. Go to the preview in my app project
2. Click in the green button "Copy Public Link"
3. Paste the link in another browser.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/preview/jobs-dev-aacfyq?loginPage

### Context

I'm using flutter flow to build an app for my graduation conclusion project. One of the steps is to share a prototype of my app, so i need the public link to do that.

### Visual documentation

*

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/64733278/fa24dab0-85aa-42df-b525-e6383cedb79d)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/64733278/ab551f43-e32e-41cc-a58f-058656bd0a75)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 115.0.5790.110
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @JonathanSMN - Thanks for posting the issue. It can reproduce the issue.

**Comment by vishalagarwal2** [comment]
Thank you for reporting this issue. This has been fixed and will be applied in our next deploy!
