### ISSUE TITLE
Reset timer triggers "end of timer" action flow

### ISSUE THREAD

**Issue by cp-centerpointai** [FlutterFlow/flutterflow-issues#1198]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using the end of a timer to trigger an action but there are other actions within my project that also reset the timer.  When the timer is reset it triggers the end of timer action causing adverse affects in the application.

### Expected Behavior

When the timer is reset it should not trigger the "end of timer" action flows.

### Steps to Reproduce

1) Create an end of timer action that triggers a snack bar with message.
2) Create a button that triggers a reset timer
3) When the reset timer is triggered you will see the snack bar with message.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8rluJNPn7wA7qX2Ke9VmWU6NUQ8RIc0sNobbxAjIoDoPJkUaffSahdWXtzjd29DKEWLjXIFwNKOjvOWMu0CIT6sGZ85+KptWArNcH6/aovQCKq/PHNBO51XBUie0LaNrSJdKrF1dFICwV2MOeyAZ3TYHuL7Zwh9f6PHaOI=

### Context

I cannot use the reset timer within my game making it unusable and preventing me from finishing and, therefore, subscribing to flutterflow to release my app. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/136703128/b3b7cf34-cd94-4860-839c-d25dda40a5da

### Additional Info

This video is a simple reproduction of the steps I outlined above.

### Environment

```markdown
- FlutterFlow version: FlutterFlow 3.1 released 7/27
- Platform:web
- Browser name and version: Version 114.0.5735.198 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by jkarttunen** [comment]
I ran on the same issue - resetting timer and starting it again seems to trigger end of timer event
