### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by adamyardley** [FlutterFlow/flutterflow-issues#1199]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If a device loses connection, api calls and backend queries fail - any actions/backend queries executed whilst there is no connection result in an error - that is not caught. As a result, no further actions after the API call/backend query are executed, so it's not possible to recover the app to a state where it uses either cached data or presents an error message. The outcome experienced by users is that they see the loading widget presented until they take another action when the connection has been restored. This is a big issue for mobile users as 3g/4g/WiFI connections can be very transient dependant on location. 

### Expected Behavior

Most programming languages allow any HTTP request to set a timeout period and execute a block of code if the request does not complete within the timeout duration. Thus: 

If the API Call/Backend queries fail due to connectivity, the response from the API call / Backend query returns an error response (HTTP response 408). 

In the case of actions, this should essentially return 'succeeded' = false and a response code = 408 [Request Timeout] 

In the case of backend queries, I expect there should be a variable action chain to trigger or a widget to display this error.  

### Steps to Reproduce

1. create a page
2. create an api request to https://jsonplaceholder.typicode.com/todos/1 - no parameters required
3. add a button to the page that triggers the api call 
4. add an alert action that occurs on api call failure (succeeded =false)
5. Run test mode in chrome
6. "throttle" the connection of offline in the inspection tool
7. press the button
8. Notice the alert doesn't happen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gzPLq05NOm8tE1ar2Y+9WoCMvNkM2aq00ttx+bw4bJJCvOpYUec/6P1ttOLzmYX9EfVq2p140/tmNkYXlLfUnOUyrG5R4+c1ybg3JVl+VaZuTF7iSbXZ8DeVgfRW41sCnpwomJrRhSHA12U+LN+zIdC3aJrrNDXowSq/LZO4=

### Context

My client uses the app developed in flutterflow to run their business operations. This causes a significant number of "refresh" calls and frustration in the app. 

Essentially i'm trying to produce an app that is stable regardless of the connectivity status of the device. 

### Visual documentation

no screenshots should be required

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: All (ios, android, web)
- Browser name and version: Chrome
- Operating system and version affected: Windows 10, Window 11, iOS (all supported versions), Android (all supported versions)
```

**Comment by hariprasadms** [comment]
Hi @adamyardley - Thanks for posting the issue. Looking at the nature of issue you have described above, this is not a bug but more likely a feature improvements. 
As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritise feature requests/enhancements, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!

**Comment by adamyardley** [comment]
Hi @hariprasadms. Thank you for looking into this quickly. I'm not sure I've explained it well enough - as I definitely think it's a bug due to the fact that performing any kind of API action without a connection results in an uncaught error and termination of the the action chain. I don't think it's a feature request to expect that a failed API request (regardless of the reason for failure) should return the response object with failure and a status code, or at the very least allow the remaining actions to continue to execute? At present any actions performed including an API request terminate the action chain - with no way for the user (developer) to mitigate the issue.

**Comment by adamyardley** [comment]
For further clarity I believe the bug is caused by an error not being caught on lines 303 and 315 of api_manager.dart - if the device is offline, these lines throw and error, which is not handled.

I've managed to get the expected behaviour working by surrounding these lines with a try-catch statement and setting the result object to a new ApiCallResponse generated on the catch with an error status code 408 (not sure it's technically a timeout) 

I appreciate the following isn't a production-ready fix - as the handling shouldn't emulate a failed response, but rather give a different type of return. however I believe this should demonstrate what I expect would happen if a user tries to make an API request whilst they do not have a connection. 
```

Future<ApiCallResponse> makeApiCall({
    required String callName,
    required String apiUrl,
    required ApiCallType callType,
    Map<String, dynamic> headers = const {},
    Map<String, dynamic> params = const {},
    String? body,
    BodyType? bodyType,
    bool returnBody = true,
    bool encodeBodyUtf8 = false,
    bool decodeUtf8 = false,
    bool cache = false,
  }) async {
    final callRecord =
        ApiCallRecord(callName, apiUrl, headers, params, body, bodyType);
    // Modify for your specific needs if this differs from your API.
    if (_accessToken != null) {
      headers[HttpHeaders.authorizationHeader] = 'Token $_accessToken';
    }
    if (!apiUrl.startsWith('http')) {
      apiUrl = 'https://$apiUrl';
    }

    // If we've already made this exact call before and caching is on,
    // return the cached result.
    if (cache && _apiCache.containsKey(callRecord)) {
      return _apiCache[callRecord]!;
    }

    ApiCallResponse result;
    try {
      switch (callType) {
        case ApiCallType.GET:
        case ApiCallType.DELETE:
          result = await urlRequest(
            callType,
            apiUrl,
            headers,
            params,
            returnBody,
            decodeUtf8,
          );
          break;
        case ApiCallType.POST:
        case ApiCallType.PUT:
        case ApiCallType.PATCH:
          result = await requestWithBody(
            callType,
            apiUrl,
            headers,
            params,
            body,
            bodyType,
            returnBody,
            encodeBodyUtf8,
            decodeUtf8,
          );
          break;
      }
    } catch (_) {
      cache = false; // prevent caching of error
      Map<String, String> responseHeaders = new Map<String, String>();
      result = ApiCallResponse({}, responseHeaders, 408);
    }

    // If caching is on, cache the result (if present).
    if (cache) {
      _apiCache[callRecord] = result;
    }

    return result;
  }
```

**Comment by aemelyanovff** [comment]
@adamyardley Thanks for reporting the issue, and sorry for the slow turnaround.

I agree that it's a bug that API calls fail the way the do when the device is offline. This will be addressed in the next update. However, we decided to return a special code, `-1`, instead of HTTP 408 or any other HTTP status code. Firstly, it's not actually a timeout but an error resolving DNS. Secondly, 408 is something that's returned by the server, but if the device is offline then the server is never reached. 

The ability to set a specific timeout is a feature request. Please submit it through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. Alternatively, you can submit it to the [wishlist](https://community.flutterflow.io/wishlist).

**Comment by adamyardley** [comment]
Thank you for fixing - any idea when this update will go live? I'll do my own testing but how does that impact backend query calls (does it eliminate the 'spinner of death' as my client has so nicely named it)

**Comment by aemelyanovff** [comment]
> Thank you for fixing - any idea when this update will go live? I'll do my own testing but how does that impact backend query calls (does it eliminate the 'spinner of death' as my client has so nicely named it)

Some time this week. Most likely on Thursday.
