### ISSUE TITLE
Referral Links are not working

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#12]
## Expected behavior (required)
When you share your referral link to someone and he/she signed Up or/and Subscribed the numbers are not changing. They should increase.

## Current behavior (required)
When you share your referral link to someone and he/she signed Up or/and Subscribed the numbers stay 0.

## To Reproduce (required)
1. Open My Account
2. Copy the Referral Link and send it to a friend
3. When she or he registered the number stay 0

## Context (required)
The referral program is not working and I guess all the benefits that are coming with it. 

## Your environment

* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 105
* Operating system and version (desktop or mobile): desktop

**Comment by hariprasadms** [comment]
I can reproduce this bug.

**Comment by itskoyii** [comment]
Is this resolved?

**Comment by bulgariamitko** [comment]
no. not yet.

**Comment by asmengistu** [comment]
@bulgariamitko @itskoyii @hariprasadms  Can you still reproduce this? We've made some changes that should fix this.

**Comment by bulgariamitko** [comment]
I just registered demo2@demo.com with my referral link and it still says 0 Signed Up. :/

**Comment by agreaves** [comment]
Closing this as a stale issue, I hope this is fixed now! However, if the error persists please create a new issue and add reproducible steps. Thanks!
