### ISSUE TITLE
Chrome extension not loading due to firebase scripts

### ISSUE THREAD

**Issue by davidoort** [FlutterFlow/flutterflow-issues#120]
## Expected behavior (required)

I expected my app to run as a chrome extension, just as shown in the chrome extension Flutterflow tutorial.

## Current behavior (required)

I get a blank extension viewport and a bunch of errors related to firebase. See screenshot below

## To Reproduce (required)

1. Create an app that uses firebase
2. Download the generated code
3. If the index.html file contains some of these lines:
```
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-storage.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-functions.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-messaging.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-remote-config.js"></script>
  ```
4. you will observe that once you run `flutter build web --release --web-renderer html --csp` and upload the build/web folder to chrome, the app does not load and you observe similar errors to the ones shown in the screenshot below.

## Context (required)

It seems like I can't get the app to work as a chrome extension unless I get rid of some firebase functionality, which is crucial for my app.

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/21220927/201434512-4e699cbd-b15a-400c-9c44-73bdc3d2b348.png)
App not loading (same code leads to a splash screen):
![image](https://user-images.githubusercontent.com/21220927/201435262-876aa92e-897d-4ac5-bb38-f6e05998c35f.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web (Chrome extension)
* Browser name and version: Chrome 107.0.5304.87 (Official Build) (arm64)
* Operating system and version (desktop or mobile): MacOS Ventura 13

**Comment by hariprasadms** [comment]
Hi @davidoort - Thanks for posting this issue. 
Considering the age of the issue, looks like this issue has been fixed in latest updates and working fine for you. Hence, we will close the issue. 

Let us know if you still seeing the same behaviour, we can re-open the issue and start investigating, Thanks

**Comment by davidoort** [comment]
Yep I think this had to do with an add blocker I had as an extension in Chrome
