### ISSUE TITLE
Mobile Deployment Xcode Bug

### ISSUE THREAD

**Issue by BigFranky** [FlutterFlow/flutterflow-issues#1200]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to deploy on IOS I'm getting an Xcode error which is strange as I'm not using flutter and cant follow the steps. Before this I had an error relating to .imagenotification which I couldn't resolve either then one deployment I started getting this Xcode Issue. 

![Screenshot 2023-07-27 at 3 43 23 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/17144392/8e0a94e5-7650-4c58-83f4-5158c33ac59d)

### Expected Behavior

I've been working on an app to submit to Flutterflow experts program.
All I need to do is submit to the app store connect. I've messaged 2
flutterflow discord channels, ff community, and messaged flutter
experts. No one knows how to fix this issue and I've read all the
documentation that exists.

This seems to be an xcode Issue but we don't have access to xcode
since we are on flutterflow. Like I've said I've followed the
documentation word by word with two apple developer accounts I haven't
been able to figure out this bug.

### Steps to Reproduce

1. deploy the app to IOS

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXivLq05Z1rsRE17nUdcFahWEwGUwbUOc7j9VEGAsjCeKtB+xzduDsSFFpYuqHd1Z+Ak2jvD0Bp9r7heDLMPEECAqeQJxH+qpfUxDgRnm6Sr6RPKrtXkZBGcVWCHKF0cKNuBF4Pstic0IF7U2IPt+ub3qCf9qOYwx5e6fDbOY=

### Context

I'm not able to deploy this app on IOS for my client. 

### Visual documentation

Steps are to start mobile deployment 

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: IOS
- Browser name and version: Chrome Newest version
- Operating system and version affected:
```

**Comment by BigFranky** [comment]
![03F062A5-4C22-4199-8ECF-534271453CF6_4_5005_c](https://github.com/FlutterFlow/flutterflow-issues/assets/17144392/1fdecdf3-496e-4ebb-8454-77d67ae61d8a)

I've attached the error I was getting before the one above.

**Comment by wenkaifan0720** [comment]
Hi @BigFranky. Are you trying to deploy the app via Codemagic on FlutterFlow, or locally by yourself?

**Comment by BigFranky** [comment]
Hello @wenkaifan0720 , I'm trying to deploy this app via Fluttterflow. It looks like the main issue for this app and all my other apps is when I add ".Imagenotification " I get the errors above. 

Not sure why or what I need to change as when I look this error up I only see Xcode solutions which in this case we can't do. i've followed every step on all video/article tutorials. I've also tried on two developer accounts.

**Comment by BigFranky** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17144392/4f5d5392-da97-4858-b7c9-e0cd50fc7af2)

Good thing I'm not seeing this error anymore but now I'm getting this message.

**Comment by wenkaifan0720** [comment]
Hi @BigFranky. Sorry for the late reply. Since I don't have access to your Apple developer account, I can't debug it on my own. Is this issue still happening to you? If it is, I would suggest you contact our support.
