### ISSUE TITLE
Unknown error to compile custom code from Boilerplate code

### ISSUE THREAD

**Issue by rvantunes** [FlutterFlow/flutterflow-issues#1202]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created an empty custom widget that receives a parameter with type: UploadedFile (bytes) and copied the boilerplate code generated by FF. After compiling the component with the boilerplate component, it resulted in an Unknown Error with no details about it.

### Expected Behavior

I expect to compile with success a Custom widget generated by Boilerplate Code

### Steps to Reproduce

I executed the following steps to create the custom widget, see the following images

After creating an empty custom widget:

1.  Created a parameter with type UploadedFile (bytes)
2. Clicked on "View Boilerplate code" button
3. Clicked on Button "<>Copy to Editor"
4. Clicked on Button "Save Widget"
5. Clicked on Button "Compile Code" which resulted in "Has Errors" button.
6. The described process resulted in an Unknown Error as it is showing the image, there is no description about the error.

> Note: The error is not happening when I set the parameter to String

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grsdG+c/LY/pqhR4jNlx7bZNEk+tDbE0jJY+rBKYpWsnObkxWOOmZTQl+AE39rGczwevGvoaeM/kEMgyHbJQ/yJdQTRX/QmOmWpSDDs2edUBSTJhhN2K+57SZ2CMmPtthdV1pig/GSw==

### Context

I'm trying to create a custom component that receives the uploaded local image storaged in state (not image uploaded to firebase) and show as an image in the app.

The idea is that I have a wizard to create a new user.
One of the pages of this wizard adds a profile picture. (At this point the user is not created yet in firebase)
The user would be able to upload to a local state and will be uploaded to firebase later after the user creation, but the user needs to see the uploaded image before continue.
I could not find any component in FF that shows an image from the local state (UploadedFile (bytes))

### Visual documentation

The following images has number which follows the item described in "Steps to Reproduce"

<img width="1905" alt="Captura de tela 2023-08-01 181454" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15233622/84077a29-c637-42af-9ce0-0d8e216d99fb">
<img width="832" alt="Captura de tela 2023-08-01 181727" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15233622/3171adaf-3d86-4a16-bc31-cf384393560c">
<img width="1910" alt="Captura de tela 2023-08-01 182010" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15233622/09c967c9-e783-40e3-a886-9d40b595f5fd">

### Environment

```markdown
- FlutterFlow version: 3.1 flutter 3.10.4
- Platform: Web Browser
- Browser name and version: 
   Tested in the following Browsers:
   * Google Chrome Version 115.0.5790.110  64 bits
   * Flutter App in Microsoft Edge Version 115.0.1901.188 64 bits
- Operating system and version affected: 
   Windows 11 Home Single Language 
   Compile SO number: 22621.1992
```

**Comment by Dev-Muhammad-Junaid** [comment]
I tried to replicate this issue. Seems to work fine on my end. I was able to follow the same steps and achieve the expected results.  Try restarting, and reloading Flutterflow, ⌘+R  it works like a charm, maybe change the name of the widget. 
<img width="1511" alt="Screenshot 2023-08-02 at 1 38 20 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/ddafd444-884e-4b37-9aa4-478155d0aac6">

**Comment by Dev-Muhammad-Junaid** [comment]
Oh. Yes. Its not compiling on my end.
<img width="1189" alt="Screenshot 2023-08-03 at 1 00 15 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/8ec67f20-f2c0-4982-937f-50cc5c2cffc4">
<img width="1508" alt="Screenshot 2023-08-03 at 12 57 19 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/eae89705-e7ae-40ae-8f84-6da5ee5ca720">

**Comment by aemelyanovff** [comment]
Thanks for the detailed bug report, @rvantunes. It'll be fixed in the next update.
