### ISSUE TITLE
"the email address is already in use by another account" - but Firestore database is empty

### ISSUE THREAD

**Issue by FlowsterApp** [FlutterFlow/flutterflow-issues#1203]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to test my sign up page, but it gives this error:

![Selection_058](https://github.com/FlutterFlow/flutterflow-issues/assets/99349520/cc4faace-7702-462a-8cb9-9c6bb0b2eca9)

![Selection_059](https://github.com/FlutterFlow/flutterflow-issues/assets/99349520/5a70e897-6718-4703-99e6-87231248689a)

Which is super confusing, because my **users** collection has no documents:

![Selection_060](https://github.com/FlutterFlow/flutterflow-issues/assets/99349520/81a0b8a9-fb8f-4220-ba25-c9e0b2965f36)

I'm fairly sure my button Action is configured properly too, setting the email, password, first_name, and last_name fields.

### Expected Behavior

An account should be created.

### Steps to Reproduce

It can only be recreated in my account.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMrlx41OsdhE17r+au9VijoXQz43apc0rNlud0wdCePyO7M+dff4RxNpSOqHfXNYG1aZvDg0+azGiYbDLsAqA06tbYBaz4dtUxDgWkGmRbqTDs2KfHckGfJTN0Cj5LavnRR+ItRYcmAc3TmXOPOAa3qCf9qOYwx5e6fDbOY=

### Context

I can't proceed with my project.

### Visual documentation

Included above.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 115.0.5790.110
- Operating system and version affected: Linux Mint 21
```

**Comment by WellDunDun** [comment]
In Firebase go to the Authentication tab and delete the user from there. When a new user signs up they are added to BOTH, the authentication tab, and also to your users collection.

**Comment by FlowsterApp** [comment]
Oh wow, I should have figured that out. Thanks so much! It's weird this didn't show up in my Google searches either :thinking: 

> In Firebase go to the Authentication tab and delete the user from there. When a new user signs up they are added to BOTH, the authentication tab, and also to your users collection.

**Comment by pocnorton** [comment]
super helpful! 👍
