### ISSUE TITLE
The PDF document display inconsistency in web app.

### ISSUE THREAD

**Issue by noscura** [FlutterFlow/flutterflow-issues#1204]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The PDF format document are not displayed in pdf viewer sometimes. Some pdf is displayed some are not. Some pdf displays sometimes that will not display after sometimes. It will be difficult as there is many inconsistency and when which will displays which not is big problem to troubleshoot.

### Expected Behavior

All pdf displays in pdf viewer all time.

### Steps to Reproduce

Create a web app
Add pdf viewer.
Add upload pdf action
upload some pdf to firebase.
Display that pdf using pdf viewer.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wzPHlwIt1rs9H+Krqb/oxniYWGDs5U40emNVDSis8I5j1BLIcf/fOYk5vZry5dFFYeU20gjkxxvfqkeDDFvVfPUytRpRi1s1QSwvyTlqVVa7XC6mdfW1THe9mCh2a0qWzrAolFNFqdGAa72DzB/PJSgrYHZCyDEgRBeWLLdeK2SrDX1iXc2URm05KZDPz

### Context

The issue will decrease my web apps consistency and it will block my release.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/118156843/03afb098-49a6-4f15-84e5-550bb1184327

Video demo

### Additional Info

![pdfdisplay](https://github.com/FlutterFlow/flutterflow-issues/assets/118156843/8be88d7d-b602-45b1-ba67-f9592f73472c)
Photo of loading pdf

### Environment

```markdown
- FlutterFlow version: 3.1 Latest
- Platform:Web 
- Browser name and version:Chrome Latest
- Operating system and version affected: Windows 11 latest
```

**Comment by hariprasadms** [comment]
Hi @noscura - Thanks for submitting the issue. Can you please check what error you can see in browser console when pdfs is not loading properly and share the error details. are those pdf links https or http ?. Share these details please.

**Comment by Shrihari1357** [comment]
PDF URL is https and I will share console screenshot as well
![chrome error](https://github.com/FlutterFlow/flutterflow-issues/assets/101409498/5125cbcb-dd72-460d-b047-64b6cbe60230)

**Comment by Shrihari1357** [comment]
I followed this tutorial to solve the error but it is not working for me. [https://www.hostinger.com/tutorials/how-to-fix-err-quic-protocol-error]

**Comment by noscura** [comment]
The issue still exists.

**Comment by noscura** [comment]
PDF viewer needs a page refresh to display the pdf one after the other. If PDF viewer is not refreshed it will show spinner. PDF viewer is not updates by changing the pdf URL it needs extra page refresh. Same issue exists while we use iFrame custom code. The url passed to iframe does not changes until the page is refreshed.

**Comment by hariprasadms** [comment]
Hi @noscura - Sorry for late responding on the issue. What is the latest updates of the issue? I presume its been resolved for you in the latest FF updates. If this is the case let us know we can close the issue. Thanks
