### ISSUE TITLE
Icon Button icon not aligned properly after web publish

### ISSUE THREAD

**Issue by dhust** [FlutterFlow/flutterflow-issues#1205]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I add an icon button, the icon is not aligned properly when I publish for the web. This is both for a custom sized button and the default one.

Just found out that it works properly if I enable CanvasKit, but it doesn't work properly when I uncheck it.

![published](https://github.com/FlutterFlow/flutterflow-issues/assets/2567117/34847a3f-a4b5-47ef-8d6b-dbde917c3e0d)

### Expected Behavior

The icon would be in the middle of the circular button. It shows it aligned properly in both Test mode and Preview mode.
![test](https://github.com/FlutterFlow/flutterflow-issues/assets/2567117/ef5767c6-8680-423f-87ba-9c557f83f759)

### Steps to Reproduce

1. Add an icon widget
2. Publish to web

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hlz5VNseFd0a6JdcBanWA7Nn0cTOURiO0bFDsdF4iuPOxzac6lTE5CQu2rTH9bKEWJoFsF+crOkuHxGvFeFxaqfap5yc5QbBX/Tn+/aoSSO6uKW2hBNJpVGHah3KTQnhUkPs1vS0YZ7WC6J/CtbDDBK5/7Zwh9f6PHaOI=

### Context

I don't want to share my project with the public until this looks correct.

### Visual documentation

![published](https://github.com/FlutterFlow/flutterflow-issues/assets/2567117/ec5c8099-24de-44ec-a3f7-374e122d2bdb)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: PC, Web
- Browser name and version: Chrome Version 115.0.5790.171 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by wenkaifan0720** [comment]
Hi @dhust. This is a known issue when we publish to web using the html renderer. And right now my recommendation is to use the canvaskit renderer.

**Comment by wenkaifan0720** [comment]
Since we will be default to canvaskit renderer in the future for web publishing, I will mark this issue as low priority. Thank you.

**Comment by wenkaifan0720** [comment]
This should be fixed in our next update for the html renderer as well!

**Comment by BachewalSuresh** [comment]
Hi in my project the custom icons are not working after publishing the web version . how can i solve this issue

**Comment by wenkaifan0720** [comment]
Hi @BachewalSuresh. For custom icons I think it is not related to this issue. Could you create a new issue?
