### ISSUE TITLE
When the "Action Output Variable Name" of an API Call is edited the other actions aren't renamed

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1206]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the "Action Output Variable Name" of an API Call is edited the other actions aren't renamed

### Expected Behavior

Should be renamed all the API Call from the actions that are related to that API Call

### Steps to Reproduce

1. Create 2 different API Calls
2. Create a button and add an API Call in the actions
3. Then change the name of the API Call (is not necessary to change the API Call)
4. Now you see the API Call when the old name in the other actions

Now I realized that is not necessary to create 2 different API Calls but in the video show it so I think that you can ignore that part

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESyvLluIxgoctK1s76KcdAhQAkH1x/bZJEl9cbdEkYC4DxE7N3Oer+VxNYZMO6YX5mf079gToCpfzVkoTTM8ddFwuqeINowbVqERXdXmG6MoylDsy0YEd7LJpRfHKiy7aZhRB/JuNpcndnw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

When an API Call is renamed then is so confusing because in the editor has the old name

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODUyNjgwN18yMTg1NDE2OQ

### Environment

```markdown
- FlutterFlow version: FlutterFlow v3.1 released July 27, 2023
- Platform: Web
- Browser name and version: Chrome 115.0.5790.170 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by sbis04** [comment]
Hey @Franco98404, I think this issue has already been fixed in our current version. Thanks for reporting the issue!
