### ISSUE TITLE
JSON path reports as NOT valid

### ISSUE THREAD

**Issue by mrnicon** [FlutterFlow/flutterflow-issues#1208]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A JSON path is reported as not valid if the path contains more then one condition. 
My example is a valid JSON path and worked just fine before July 20, now it gives an error 
$.orderforms[:].definition[?(@.showinapp == 'true' && @.type == 'accordion')] will give a error.  

### Expected Behavior

no error, and the ability to Save the API call after inserting the JSON  Path. 

### Steps to Reproduce

Add this JSON Path to a JSON Path in API under Respons & Tests 

$.orderforms[:].definition[?(@.showinapp == 'true' && @.type == 'accordion')]

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hl8Yt2pbxe1oSJau1amiI4NWkcTIMziNZ+exUbfaL1BqQtPuDedhJBXuHjaVNcG1qWhmYGwPuOkfDhJMEoIkiYbaJ7wc1+YD30e2igVrKTCZOSOXElQOVbG3WO3MPYnhQkNtR1R1IF7DuUCuTLaAXDFOu/Zwh9f6PHaOI=

### Context

Get data and make range from API calls. 

### Visual documentation

![CleanShot 2023-07-20 at 10 40 44](https://github.com/FlutterFlow/flutterflow-issues/assets/26312916/93733558-456f-45cf-b010-682370924330)
![CleanShot 2023-07-20 at 10 03 03](https://github.com/FlutterFlow/flutterflow-issues/assets/26312916/b7bcb26e-2245-45d1-bb59-9bc839bf8326)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MAC
- Browser name and version: Chrome 114
- Operating system and version affected:
```

**Comment by mrnicon** [comment]
2 weeks later, what part of this issue is not understod? Please contact me to get more detailed information if you need.

**Comment by YassinELY** [comment]
Kind of the same issue here... Was working fine until today..

<img width="1728" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142539026/a4c33ba4-3e28-4839-812b-e76f94e06425">

**Comment by mrnicon** [comment]
@YassinELY I think you have to report this as a separate BUG as the bug I reported is fixed and I think this issue will be closed soon. But my testing of your problem give the same issue as in your screenshot.

**Comment by YassinELY** [comment]
hi @mrnicon, i indeed also reported it in other bugs. It is marked as "high prio" but until now no solutions... :(
https://github.com/FlutterFlow/flutterflow-issues/issues/1312

**Comment by mrnicon** [comment]
OK I'll report this directly to Alex in the Beta testing group. I hope its OK to use/send along the screenshot.

**Comment by YassinELY** [comment]
Yeah it is for sure! Thank you!

**Comment by aemelyanovff** [comment]
@mrnicon Sorry for the late reply. Are you still experiencing this issue? I just tried your JSON path and it did not trigger validation errors:

![Screenshot 2023-09-18 at 5 24 55 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/2b9bc7d9-770f-4457-91b1-57a3af7f0874)

**Comment by YassinELY** [comment]
I still have the same issue...
<img width="724" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142539026/f3359de1-4b41-4702-b390-8685846dad32">

**Comment by aemelyanovff** [comment]
> I still have the same issue... <img alt="image" width="724" src="https://user-images.githubusercontent.com/142539026/268877018-f3359de1-4b41-4702-b390-8685846dad32.png">

Try `$.splits[50]`

**Comment by mrnicon** [comment]
@aemelyanovff  - Yes this issue is fixed

**Comment by aemelyanovff** [comment]
Thanks for the confirmation! And again sorry for the slow turnaround.
