### ISSUE TITLE
Supabase filter equals null doesn't work

### ISSUE THREAD

**Issue by TimurKr** [FlutterFlow/flutterflow-issues#1209]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When querying data from supabase with filters, and specifying a filter, where certain column should equal null, an error is thrown by postgres for invalid value. `PostgrestException(message: invalid input syntax for type bigint: "null", code: 22P02, details: Bad Request, hint: null)`.

I have identified the issue to be in the underlying syntax of the query that is made. when checking for null valus, the url should have string `column_name=is.null`, where currently it is `column_name=eq.null`, but null is not a valid bigint. 

In the underlying supabase_flutter library the difference specified in the docs is here:

```dart
final data = await supabase
  .from('cities')
  .select('name, country_id')
  //.eq('name', 'The shire'); For checking equality (doesn't work for null)
  //.is_('name', null); For checking null
```

### Expected Behavior

When specifying `equals` filter, support for null values should be automatic. I advice against the solution of adding new filter option, (equals, greater than, is in, ...), as this can't be chosen dynamically, while the fact whether a value is null is usually dynamic. 

### Steps to Reproduce

1. Setup a project with supabase
2. Create a table with nullable bingint column
3. Fetch data from this table with a filter, where you only fetch the dta which has null in the previosly mentioned row

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfHqw81NocNc+KrAacFvvyQUKWJ+ULso18pOGDwbfaKvPIlzaczBdklCZMSrS29pKEWLgXM00s7RivGeDsc6GEiZRps6+pBPVQ7vfHG/aovTCquWYER6O+dUChTG0Jmr3xNBJs52dGAg7WaIf/OvTT7DQ5P4Zwh9f6PHaOI=

### Context

I am fetching data from supabase, but I need to filter them based on multiple fields, some of which might be null.

### Visual documentation

Not a visual issue

### Environment

```markdown
- FlutterFlow version: v1.1.93
- Platform: Downloaded code running localy
- Browser name and version: 
- Operating system and version affected: Ventura 13.3.1
```

**Comment by kevintonb** [comment]
Hey @TimurKr , thank you for reporting the issue. I have tried to replicate the issue following the above outlined reproducible steps and I was not able to reproduce them successfully. This could be due to the fact that this issue is project specific or a transient bug. If you are sure that you have found a bug, kindly create a new blank project, reproduce the issue and share the bug report code of the new project with us in this thread. Or if you feel that this could be a project specific issue, feel free to contact the Flutterflow Support Team at support@flutterflow.io :)

**Comment by TimurKr** [comment]
Hi @kevintonb, thanks for the reply. I reproduced it on a blank project, but I am not sure how to share it with you. I have generated the bug report code from the collumn that is fetching the data, hope that helps. I could also add you to the projcet as a collaborate, if you gave me the neccesary info. If you remove the filter from the query, it works, but with it, I get an exception from postgREST, because `eq.null` is not a valid filter. 

IT88hc/qy5d1m8tK7q6JdMJVtGAvKUM7a7srke1qEBQaIZDoPbd3ZPfBN1RAUse4d1FfemGMgVsBpqHMuOOWF/tcB0iAfLY/+LlfEh/PRl6tWq3TDs+gP3dCQOhgI37G4LWvuRJTCMlpTHs3wF2EG+etVi3dQoT2IUY8Ds6kUJPJs3CfLRDNChFF3RQXHm2hEeljIVDq+f6QspZl1eTjzw==

**Comment by yanffernandes** [comment]
Same problem, Supabase Relation "equal to" on NULL is not a valid filter. FF try to put  eq.null

**Comment by maldous** [comment]
This issue remains.

**Comment by dansomrack** [comment]
I just ran into this issue today and can confirm that it still reproduces. Here is a screenshot of the UI and the resulting code that FF writes. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11216609/ca9617f9-335d-4ba0-86c4-e4744e25c758)


```
FutureBuilder<List<ReceiptItemsWithDetailsRow>>(
                future: ReceiptItemsWithDetailsTable().queryRows(
                  queryFn: (q) => q.eq(
                    'claim',
                    null,
                  ),
                ),

**Comment by vineethvijayan314** [comment]
same here

**Comment by sbis04** [comment]
Thanks for reporting this issue! The next update should introduce two new relation types `Is` and `Is Not` which should help to filter exact values like `true`, `false`, and `null`.

**Comment by TimurKr** [comment]
Hi @sbis04, great to hear there has been some progress, but this solution unfortunately doesn't solve the scenarios, where you are filtering based on a dynamic nullable value. 

When you are not sure, whether your value will be null, how do you choose which filter should be used? I believe the correct solution would be to make the `equal` filter work with null values as well, rather then introducing new filter altogether. 

What are your opinions on this?

**Comment by sbis04** [comment]
@TimurKr Oh, you can use multiple filters on a query, right? So, the first could be to filter the `null` values using the new `Is Not` relation, and then you can apply an `Equal To` filter for whatever you are trying it filter with. Wouldn't that work?

**Comment by TimurKr** [comment]
@sbis04, not sure how that would work, as these filters work in conjunction, meaning all filters must be satisfied for a row to be returned. If I were to add 2 filters, one for `is` and one for equal `equal`, the behavior would be as follows:
1. Filtering for a non-null value
The `is` filter would not pass and I assume there would be no dynamic way to choose between `is` and `is not`, as this is not available with any other filters
2. Filtering based on a null
There is no value that could be put into the `equal` filter that would make it 'pass' the filter, as the value we are looking for is null, so not even conditionally choosing the value would help. 

I might be wrong somewhere, as I haven't had the chance to test this, but as of right now, the only dynamically selected things in the Supabase queries are the values in the filters, not the type of the user filter, nor the logical statement between them. Perhaps it might be good to open a new issue for this?

**Comment by fimbres** [comment]
I'm also facing this issue, all the filters I added in my Supabase query that tries to filter null from the value of a relationship column does not work at all, basically if a relationship column has null as a value the filter is not being applied.

For example this one returns all the workshops rows, as I said, it seems the filters are not being applied when the value is null:
`const { data, error } = await supabase
      .from('workshops')
      .select(`
        *,
        members (
          user
        )
      `)
      .filter('members.user', 'not.is', null)
      .eq('members.user', userId)`

Any updates on this one?
