### ISSUE TITLE
ListView with Infinite Scroll - List doesn't show newly added documents until the screen is viewed twice

### ISSUE THREAD

**Issue by cheggy** [FlutterFlow/flutterflow-issues#121]
## Expected behavior (required)
When I create a ListView,
And add a backend query to Firebase to it,
- Query collection
- List of documents
- Order by > post_created_time (decreasing)
- Ignore empty filter values = false
- Enable infinite scroll = true
- Listen for changes = true
- Page size = 16

When I view the screen, the list loads as expected and functions as expected.
But if someone creates a post,
When I navigate to the screen with this query, I don't see the new post added.
It's only when I navigate away and come back that the new post is shown at the top.
To be clear, I am not expecting the new post to be added to the ListView if I am looking at the screen while it is added.
But if someone adds the new post while I have the app closed.
When I open the app and go to the screen with this query, the new item is not there.
If I go from the home screen to the PostList screen, I do not see it.
If I then navigate away to another screen and then back to the PostList screen, it is shown.
It seems that you need to view the screen twice for new items to be shown.

## Current behavior (required)
New documents created are not added to the list the first time I view the list.

## To Reproduce (required)
Create screen with list view
Add Query Collection to the ListView to generate children
Add some content to the listView items so it can generate content
Copy the query settings listed above.
View the screen in the app
Close the app
Create a new document from a different instance of the app
Open the app on your device
Go to the screen
The new post is not shown.
Navigate away and then come back to the screen again.
The new post is shown.

## Context (required)
My users are coming to the forums and not seeing any new items.
It has been like this for a long time

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/3022867/201469434-9aadf3cb-870f-4bd2-9da8-65472d674521.png)

## Your environment

ITFTzMmAsYtIxLRG+KqJdO0wmiYWM0MdXZIRmOtvewgjF774P+0qecj8SFNoXcCzaH59Plb88D8F7vzrjvzmG/kEOgqrGq5NypdyelyjEA8=

Brwoser: Web, Edge current, Windows 11
* Version of FlutterFlow used: Web v3.0 9 November 2022

**Comment by cheggy** [comment]
Ok, I've found the cause (of sorts) for it.

On my home screen, I have a Row (non infinite scroll) that loads the most recent 6 'posts' that are tagged to interest of the user.  So it is a filtered list of 'posts'.  It is a:
- Query Collection
- List of Documents
- Collection = Posts
- Filter applied
- Sigle time query = false

![image](https://user-images.githubusercontent.com/3022867/201470857-458b08c5-3a51-4ccf-87ed-17a98d60a10f.png)

This list is getting cached I think
And so when I go to this new screen that has infinite scroll (even for the first time ever),
It is showing the previous Posts Collection query results from the Row on the homescreen (above)
It's only when I load the screen for the second time by navigating elsewhere and back that this new ListView Infinite Scroll screen loads the list properly.  Note that navigating into a screen and pop back to this list screen doesn't refresh the data.  I need to navigate (route) to a different screen and then navigate (route) back to the list screen to force it to load the list properly.

To add to this,
If I make the Row that only loads 6 filtered posts "Single Time Query = true", when I navigate to the new screen with the infinite scroll list, it shows a different, and still incorrect list.  I'm not sure what it's matching this time.

**Comment by cheggy** [comment]
And if I remove the filter on the Row query (so that is the same query as the ListView, but limited to most recent 8),
When I go to the ListView screen, it works correctly.

**Comment by Pepino-GR** [comment]
Hi cherry,
 I can reproduce the issue. If you see the information for 'Listen to changes' it declared it as follow:
 if true, the list will keep listening for changes to the documents
(via a Stream) in order to keep the current items up to date.

Note: This will NOT cause new items to appear nor remove
recently deleted items. It will simply keep the existing items
in the list up to date.

It show changes inside the displayed documents, but doesn't shows new inserted documents. I think, that this behavior is by design and not a bug. If you disable 'Enable infinite Scroll, it works as you expected.

**Comment by cheggy** [comment]
Hi @Pepino-GR ,

I appreciate the reply, but I don't think you understand my problem correctly.

The problem is NOT that I am expecting new items to show in the list when being viewed and new items are created.  I specified this.  The problem is that the list is not correct at all the first time you view it.  Please read my follow up comments where I can recreate it 100% of the time.

The problem is that a different list (with a query of the same collection, but with different filters) is getting cached and being shown to the user.

**Comment by Pepino-GR** [comment]
Hi cherry, 

thanks for your answer. I need to know more about your project. How are the relevant screens looks like? How do you navigate to the new screen? What are the filter settings?

**Comment by cheggy** [comment]
I will try to simplify this, as my homescreen is complex.  So instead, I have created 2 new screen that are very simple.

**A home screen.**
- It has a list of posts, in a column.
- The query on the column is to get all posts where the post_category = 'Psychic', sorted by created date
- It works correctly
- It has a button to navigate to a new screen to replicate the forums, but simpler.

**The Forums**
- It has a listView, to get all posts, sorted by created date.
- It has infinite scroll and listen for changes
- There is no filter.  It should just get all posts

Here is my new home screen.
It loads the 2 Psychic posts correctly
<img width="278" alt="image" src="https://user-images.githubusercontent.com/3022867/201500729-e761b101-410c-4882-8ec7-4e53a25a1932.png">

When I tap the button at the top, it takes me to the Forums screen.
It appears to load with a larger selection of posts, but this is not the current list.  There are many missing.
<img width="275" alt="image" src="https://user-images.githubusercontent.com/3022867/201500756-7cc49832-2933-4244-9930-92c133669cd7.png">


If I tap the back button and go back to the test home screen, we can see the same two posts as before
<img width="274" alt="image" src="https://user-images.githubusercontent.com/3022867/201500782-09db61c7-443d-4734-bae7-daacf58bf909.png">

Now I will tap the button at the top and go back to the forum screen
You can now see that the list of posts has updated.  And it is now showing the correct list.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/3022867/201500819-0d1b1c9a-0e8a-4ac8-89a9-1d3766920e8d.png">

I need to view the screen that has infinite scroll listView twice in order to get it to show the correct list.

//

I have tried other scenarios that are more complex and they also result in incorrect lists, but different scenarios result in different incorrect lists.  Let's keep it simple and keep it to the above 2 screens that have nothing but a column back end query and a listview infinite scroll query, as this is causing problem already.

**Comment by cheggy** [comment]
If I remove the 'listen for changes' selection on the ListView (Forums/All Posts) list, it seems to work correctly.

Here's another example.
A screen that has a listView of infiniteScroll, and ListenForChanges = true.
It lists people that I am following.

I open the app.  It shows me this test home screen.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/3022867/201503516-25db5ad6-d9bf-48ba-b458-33a50d1b1e50.png">

I tap the People nav in the bottom and go to the people screen.
It displays 4 people
<img width="281" alt="image" src="https://user-images.githubusercontent.com/3022867/201503536-bf2f0fa6-ecec-4942-818d-52d7d2fca67a.png">

But this is not correct.  So I go back to the Test Home screen from the bottom nav
<img width="274" alt="image" src="https://user-images.githubusercontent.com/3022867/201503555-fbec38e2-c6ca-4766-81ae-181e02a53104.png">

And then go back to the People tab.
And now it loads the list correctly.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/3022867/201503573-69e1056a-a51e-4b79-b0d6-1fb28fdb2a94.png">

If I turn the 'listen for changes' option off, then when I go to the People tab for the first time, the screen loads with the full list correctly the first time.  

The 'Listen for Changes = true' appears to be the cause of the problem.
It's been like this for at least a few months I think.  It's not something new in the last couple of releases.

**Comment by Pepino-GR** [comment]
Hi cherry,

I'm unable to reprodiuce the issue. As I find in the documentation, that in rare case, you have to disable it.

"On enabling the infinite scroll, the Listen For Changes property also gets enabled. That means, the list automatically updates if any changes are made to the item. This is done to keep all the items up to date on the screen. However, it does not update the list if any new item is added or deleted. In rare cases, you would need to disable this feature. To do so, simply turn off this property."

So I will set it as a bug, to see, how the FF Team will handle it.

**Comment by cheggy** [comment]
Hi @Pepino-GR ,

It's happening to me 100% of the time.  So there is definitely something not working right.  And making changes results in other incorrect outcomes.  I've tried creating a new project and just testing these two screens and it appears to work ok there, so there must be something else attributing to it.

I would be happy to share my project with your developers so they can find the cause.

"Turn off this property" is not really an adequate outcome for me.

I waited a long time for infinite scroll to be made available and it just never seems to have worked correctly for me.  I've been a paid user of FlutterFlow for a long time too, and it would be appreciated if this would be resolved.


Thanks, 

Tim French

**Comment by Pepino-GR** [comment]
Hi Tim,
it seems, that your issue is mainly reproducible inside your project, maybe it’s better to contact the FlutterFlow support.

**Comment by cheggy** [comment]
As an update, I attempted resolution with FlutterFlow support and was instructed to raise the issue here.

This is still occurring for me.  I have raised 2 separate issues that detail 2 individual issues I am currently experiencing with Infinite Scroll, related to this ticket.  For reference, they are:

https://github.com/FlutterFlow/flutterflow-issues/issues/233
https://github.com/FlutterFlow/flutterflow-issues/issues/234

Thanks, Tim

**Comment by morad** [comment]
I am not sure if my problem is similar to this one. But the performance of ListView (Firebase query) is really bad.

I have noticed the performance has been getting worse as more posts are being created.

The ListView feed is fetching from Firestore (infinite scroll and list for changes enabled) with pagesize 10. But it seems the pagesize is being ignored, and it's fetching and loading the entire 500+ posts with media metadata at once.

When I add .limit to the query directly on Android Studio, the performance is better.

**Comment by morad** [comment]
Hello,

I am facing the same issue for sometime, and I’ve raised it here as well as flutter support and no luck. And now I am looking into having a custom code to see if I can make adjustments / changes that will solve this problem… and by doing that, it defeats the premise of what flutterflow is all about.. simplicity.

I hope we don’t dismiss this issue, and look into it. Note, I am happy to give you access or share access to my GitHub so you can see the issue.

**Comment by agreaves** [comment]
Hi all, this is quite an old issue, so I apologize for the inconvenience. We have recently updated how Infinite Scroll is performed, which should clear up this and a few minor issues. This will be fixed in the next major release (within the next week)! Thank you for your (impressive) patience 🙂

**Comment by SamyKhara** [comment]
Hi Alex- we were almost about to give up so thanks here.

**Comment by SamyKhara** [comment]
Hi

s the “listen for changes” in infinite scroll fixed? Also, currently
infinite scroll doesn’t work if it is part of a column and the column is
scrollable and not the list. Has that been fixed?

**Comment by SamyKhara** [comment]
@agreaves @morad @hariprasadms @asmengistu - this issue is still not fixed! You promised it would be fixed in a week.

`Hi all, this is quite an old issue, so I apologize for the inconvenience. We have recently updated how Infinite Scroll is performed, which should clear up this and a few minor issues. This will be fixed in the next major release (within the next week)! Thank you for your (impressive) patience 🙂`

<img width="950" alt="Screenshot 2023-07-29 at 2 41 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/c18711f5-df18-445b-8590-4ef8a9aee970">

Is there any plan to fix such major issues?

**Comment by SamyKhara** [comment]
> Hi all, this is quite an old issue, so I apologize for the inconvenience. We have recently updated how Infinite Scroll is performed, which should clear up this and a few minor issues. This will be fixed in the next major release (within the next week)! Thank you for your (impressive) patience 🙂

We need this fixed ASAP please!!

**Comment by gooser95** [comment]
@morad @asmengistu @cheggy @agreaves @hariprasadms - I am facing the same issue. How can we elevate this issue?
