### ISSUE TITLE
Impossible to store an image uploaded by the user in an app state

### ISSUE THREAD

**Issue by paulai75000** [FlutterFlow/flutterflow-issues#1210]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I create an action to upload an image, then try to save this image in an app state, this is impossible. The message I get is: current variable is not valid. If this isn't a bug, how can I store an uploaded image in an app state to avoid going through firebase?

### Expected Behavior

Store an image uploaded by the user in an app state

### Steps to Reproduce

Add a component to upload an image
Create an action in which you try to store this file (widget state) in an app state

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

image

### Context

store an uploaded image by the user in an app state (action)

### Visual documentation

![CleanShot 2023-08-03 at 21 16 26@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/141363407/8f202337-23cb-4970-a54b-def4601fc68f)
![CleanShot 2023-08-03 at 21 19 19@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/141363407/9a070cae-6f3c-47f7-8cb6-b870e6d87a75)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version: brave
- Operating system and version affected: mac
```

**Comment by SameerShahzad99** [comment]
FlutterFlow currently does not support storing local image in the app state and also showing it through the image widget officially, So I am considering this as a feature request!

**Comment by agreaves** [comment]
Hi @paulai75000, it looks like you're trying to set it to an `ImagePath` but when you upload a file locally it results in an `UploadedFile`, which is what you should be using instead. As @SameerShahzad99 you previously could not show an image from local bytes but now you can do that as well! 🙂
