### ISSUE TITLE
Opacity from page state variable not working

### ISSUE THREAD

**Issue by blistick** [FlutterFlow/flutterflow-issues#1211]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Binding an object's opacity to a page state variable is not having any effect on the opacity. The opacity is always 1.

### Expected Behavior

It is expected that the opacity of a UI element, such as an image, can be controlled from (bound to) a page state variable.

### Steps to Reproduce

To validate this, I created a simple project called "OpacityTest", which can be found here:

https://app.flutterflow.io/project/opacity-test-m9nxrm

This project has a single page, with an image (within a column) on the page. I added a page state variable called "imageOpacity" and set its initial value at .25. I set the image to use this variable for opacity, but the image appears at full opacity, i.e. as if the value were 1.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oicj1z5VNrt8F+KXqdcAxnSQXJWY6bJ03lspBZywgfZzzBLN/fPfQPxNBXcOiTVVEO2Cmp14GwNrmuPHQG/kVBwquRrZO+Lp+WArdWkaQRrWTF7mWVHckL8VXGGKF0LTQvhZNHMxpSEIn31+lNe69bAjqHpDyIUQ8Sq/LZO4=

### Context

I am trying to produce a seamless visual transition from one image to another, without any "flicker". Controlling opacity programmatically would let me do that.

### Visual documentation

![OpacityTest_state_value](https://github.com/FlutterFlow/flutterflow-issues/assets/1686576/4a2cf3fe-1149-44f6-9c4c-81218431e663)
![OpacityTest_image_opacity_setting](https://github.com/FlutterFlow/flutterflow-issues/assets/1686576/685d7fea-dff9-4cab-a4d5-d621b2f936b2)
![OpacityTest_test_mode](https://github.com/FlutterFlow/flutterflow-issues/assets/1686576/d6d1afbf-57e7-4bb0-a85d-16bbe8db9c90)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Windows 10
- Browser name and version: Chrome 115.0.5790.111
- Operating system and version affected: Test mode on same computer, in same browser, as well as Web export under Firefox
```

**Comment by davidflutterflow** [comment]
I can approve i test this, In test mode in a brand new project, it does not work whether the page state or app state both.
Or any other condition, Seems changing the value it does not affect the widget opacity after it built

**Comment by vishalagarwal2** [comment]
This issue has been fixed and will be applied in our next deploy!

**Comment by blistick** [comment]
That's great news! Thank you!

When do you expect the next deploy? And/or is there a version number I should look for?

**Comment by vishalagarwal2** [comment]
Deploys usually occur on Thursdays, but you should be able to tell when FlutterFlow has updated when the version number in the top left corner changes.

**Comment by blistick** [comment]
Thanks!
