### ISSUE TITLE
Firestore User Collection Query Issue After 19th July Update

### ISSUE THREAD

**Issue by gianverdum** [FlutterFlow/flutterflow-issues#1213]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After creating a new user on the "Authenticate" page and being redirected to the "Home" page, a logic is implemented to verify the user registration completeness. The first action in this logic is a Firestore Query to the "User" collection, filtering by the user's uid. However, since the 19th July update, this first action fails, causing the build logic on the "Home" page to not work as expected.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/b4abae92-0a5e-4928-96ec-f0a06d173576)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/5b72d0fc-100b-4a3c-b32c-26c96c506af3)

### Expected Behavior

After creating a new user and being redirected to the "Home" page, the Firestore Query to the "User" collection should successfully retrieve the user's data based on their uid. The query result will then be used to update the App State by setting the "userRegistrationDone". This updated state will be used in the next "Condition" action to determine if the user should be redirected to the next step of the registration process or remain on the "Home" page, depending on whether the registration is complete or not.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/12abbcca-6878-4b8d-906f-5bc469435a26)

### Steps to Reproduce

1. Verify Firestore Rules: Ensure that the Read and Write permissions for the "User" collection are set correctly to allow access to users based on their uid. (User Collection or Tagged User)

2. Run Test Mode to access the app and go to the "Authenticate" page where new users can be created.

3. Create a New User: Fill in the required information and create a new user through the app's registration process.

4. Observe the Result: After creating the new user, observe the expected result, which is to be automatically redirected to the "RegisterProfile" page upon successful user creation.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wk+fluJN1xMtF1ar2b+9ViicWMjp7ba8vk8JueCs8GZT0B4kcYs+kfklUONfmd1ZUJ1mj+HIX/MmPjt/PA8IpOkicGqE7zLVubQvwLU6WWraoEr63b398RPxmfm7AyJ+n3CV5HM9oSGRgw07zG+TKQgTZNu/qNVQ7O+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

In order to proceed with developing and testing the app, I had to make alterations to the Firestore Rules to temporarily lower the security level. This decision was made out of necessity to facilitate testing and debugging processes. However, this change has raised concerns about GDPR compliance, as the User Collection is no longer adequately restricted.

I am worried that unless this issue is addressed and resolved soon, the app's MVP pilot, expected to be launched at the end of September, may encounter compliance and security challenges. It is crucial that the issue is prioritized and resolved before the official launch to ensure a smooth and legally compliant user experience.

Having this problem lingering without a clear resolution timeline creates uncertainties for the project's success and user trust. I am hopeful that by raising the bug report on GitHub, the engineering team will take prompt action to address the issue and provide regular updates on its progress. This will not only alleviate the current challenges but also ensure the app's compliance and readiness for the upcoming MVP pilot.

### Visual documentation

Step 1: Verify Firestore Rules: Ensure that the Read and Write permissions for the "User" collection are set correctly to allow access to users based on their uid. (User Collection or Tagged User).
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/9d7f79fa-a094-474d-ad64-5951ac1ef6aa)

Step 2: Run Test Mode to access the app and go to the "Authenticate" page where new users can be created.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/bbc804be-6619-47a0-94ed-0d0d5dfeb38b)

Step 3: Create a New User: Fill in the required information and create a new user through the app's registration process.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/16790ad4-1447-4ce3-8cc8-3e541cdbafbd)

Step 4: Observe the Result: After creating the new user, observe the expected result, which is to be automatically redirected to the "RegisterProfile" page upon successful user creation.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/8027ab50-f460-4fe2-8b0d-96db4308812d)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Windows Web and Desktop
- Browser name and version: Microsoft Edge Version 115.0.1901.188
- Operating system and version affected: Windows 11 Pro Version 10.0.22621
```

**Comment by gianverdum** [comment]
I am patiently waiting for updates and keeping my hopes up for a solution.

**Comment by kevintonb** [comment]
Hey @gianverdum , thank you for providing a detailed report. I have tried to recreate and reproduce the issue that you've mentioned here as per the actions set up in the project from your bug report code. However the actions that are setup work exactly how the behaviour is expected and I don't see any bugs with the platform as such. The registration => home => profile completion logic works perfectly fine on my end. If you are still facing the issue, kindly reproduce the issue in a new project with authentication and navigational actions setup so that we can troubleshoot this further. I'm currently marking this as not a bug, but please feel free to add more info so that we can forward this to our engineering team when a bug is identified.

**Comment by gianverdum** [comment]
Hi Kevin, I have an update on the issue. I created a new project to replicate it and found a misconfiguration that caused the problem. I wish I had noticed earlier. Thank you for your help!
