### ISSUE TITLE
info.plist CFBundleName is set to Project Name and not to Display Name

### ISSUE THREAD

**Issue by Jeroen-R** [FlutterFlow/flutterflow-issues#1214]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When info.plist is generated, CFBundleName is set to the content of the App Details / Project name setting

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10716254/c2ccdb5b-3676-4a65-8e2d-ead1acdafd0e)

### Expected Behavior

It should be set to the App Details / Display Name setting (when specified)

This is a problem as 
1. I cannot change the Project Name. It contains spaces (from when I created the project) and when I try to change the name, it deletes the contents of the Project Name field (Another bug for another day)
2. This display name is displayed in the iOS alert when logging in using a Google account. This looks unprofessional, and I have no control over it as I am using FlutterFlow to push out the build to the App Store.

![9FE10139-E50A-45E2-9420-0186DF5CC88D](https://github.com/FlutterFlow/flutterflow-issues/assets/10716254/45cb8494-10b2-4e55-bf2d-f7d7de131763)

### Steps to Reproduce

1. Open a FlutterFlow project
2. Set the value of the Project Name and Display name to different values
3. Download the code locally
4. Open iOS/Runner/Info.plist
5. Look in the CFBundleName

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiPHq2It2sdsA7qr2KcJaljw5KUg2a+cslsJuZw83G5jnG7l3WvfObhJUcOLjSnx+P079jmIX/MqJiOHLEfc6ZByZRaI+1c52ZTzJWkKuV8WxDJS3b3NDI8phC36O06SJoSZ4OsRedFI66k2mPvK/dAnsJpDaITIRMea4XdeK2SrDX1iXc2URm05KZDPz

### Context

My app now looks amateuristic to end users. 

### Visual documentation

Images are included in context above. 

Please do not ask me to make a screen recording of what is a well described bug.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS
- Browser name and version: Version 1.56.9 Chromium: 115.0.5790.98 (Official Build (arm64)
- Operating system and version affected: Ventura 13.5
```

**Comment by sbis04** [comment]
This will be fixed in the next update! Thanks for reporting it!
