### ISSUE TITLE
Can't update fields in a Collection MAP list

### ISSUE THREAD

**Issue by gianverdum** [FlutterFlow/flutterflow-issues#1215]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the app workflow: The "User" collection contains a MAP field called "my_vehicles," which is a list of data type "vehicle_ownership." Within this MAP list, there is a requirement to update specific fields of individual "vehicle_ownership" entries.

On the page VehicleDetails, I'm implementing a feature to update the vehicle's mileage in both the "vehicle" and "users" collections. In the "vehicle" collection, which has one document per vehicle, the data is updating as expected. However, in the "users" collection, where the necessary fields to update are within the MAP list, the data isn't updating, even though the action "Backend Call Update Document" is set to update a specific vehicle index.

### Expected Behavior

The expected behavior is that when updating the vehicle mileage on the VehicleDetails page, the changes should be reflected in both the "vehicle" collection (where each vehicle has one document) and the "users" collection (where the vehicle data is stored as a MAP list within the "my_vehicles" field).

### Steps to Reproduce

To reproduce the issue and test the application, it is essential to either run the application using my database or have a copy of the data in the "auto-maker-images" and "vehicle-images" collections to ensure that the steps provided accurately reflect the behavior related to updating fields within the MAP list of the "my_vehicles" field in the "users" collection.

1. Run the project in test mode.

2. Create a new user and complete the profile and vehicle information during registration.

3. After finishing the registration, you will be redirected to the home page, where you can view your registered vehicle displayed as part of a car card in a page view component.

4. Click on "Detalhes" in the upper right corner of the car card to be redirected to the Vehicle Details page.

5. Update the mileage of the vehicle on the Vehicle Details page.

6. Check the Firestore collections "vehicle" and "user" to confirm that the mileage information is not updating within the MAP list of "my_vehicles" in the "users" collection.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wk+fluJN1xMtF1ar2b+9ViicWMjp7ba8vk8JueCs9f5CvOpYUec/6P1hvQt+6SlVUMWGMp14B/9LTv+zlKcABITGrRqZRzs9uYA3yc3KWbp+TF7qCQnN5EdJnJ26k4KTUiBNQAPNeW1Ya2zmMB+yWThfXJIP4PHo8Sq/LZO4=

### Context

The use of the MAP structure in the "my_vehicles" field is a crucial part of our architectural plan to optimize database reads and reduce unnecessary Firestore document reads. By storing vehicle data as a MAP within the "my_vehicles" field in the "users" collection, we can retrieve all relevant information for a user's vehicles with a single document read, rather than requiring separate reads for each vehicle in a separate collection.

However, the current issue prevents us from effectively updating the vehicle data within the MAP list, leading to potential discrepancies between the "vehicle" and "users" collections. This not only impacts the accuracy of user data but also hinders our efforts to optimize database usage and reduce Firestore costs.

Given that Firestore charges per document reads, it's crucial for us to efficiently manage data retrieval and updates. The ability to update vehicle details directly within the MAP list is vital for maintaining data accuracy and optimizing database performance.

Resolving this issue promptly is of utmost importance to ensure the app's compliance with our architectural plan and to provide users with a seamless and cost-effective experience. We appreciate your attention to this matter and look forward to a resolution that allows us to effectively manage vehicle data while adhering to our architectural principles.

### Visual documentation

1. Run the project in test mode.

2. Create a new user and complete the profile and vehicle information during registration.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/96c47e1d-81f5-4b4b-9d73-3da615a34b93)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/8cf357e0-33da-4bbf-b0b0-834367d54337)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/53a056ea-d3fc-4084-b2ba-ed79b7c110bc)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/be965d92-8fc1-4986-bb6b-d1b85ade0c6f)

3. After finishing the registration, you will be redirected to the home page, where you can view your registered vehicle displayed as part of a car card in a page view component.

4. Click on "Detalhes" in the upper right corner of the car card to be redirected to the Vehicle Details page.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/482df2c7-7af4-45fa-abf8-8c096c0d31f2)

5. Update the mileage of the vehicle on the Vehicle Details page.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/23f25807-eb3e-4da0-8c0b-0dfe6ec58ffa)

6. Check the Firestore collections "vehicle" and "user" to confirm that the mileage information is not updating within the MAP list of "my_vehicles" in the "users" collection.

User collection
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/4ed3ba1c-3b42-4abd-99fe-5114ba007765)

Vehicle collection
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/d06f6e27-477b-4a94-87d6-78c95299df35)

### Additional Info

To reproduce the issue and test the application, it is essential to either run the application using my database or have a copy of the data in the "auto-maker-images" and "vehicle-images" collections to ensure that the steps provided accurately reflect the behavior related to updating fields within the MAP list of the "my_vehicles" field in the "users" collection.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Windows Web and Desktop
- Browser name and version: Microsoft Edge Version 115.0.1901.188
- Operating system and version affected: Windows 11 Pro Version 10.0.22621
```

**Comment by gianverdum** [comment]
Hey @hariprasadms, I'm wondering if there's a target date for publishing a fix for this issue. My goal is to launch my MVP by the end of the month so that I'll have time to validate it and gather all the necessary information to apply for the YC winter batch.

**Comment by aemelyanovff** [comment]
@gianverdum Thanks for reporting the issue.

I'm afraid this is not a bug. Firstly, Firestore does not have an operation like what you described. Secondly, if there were an operation like this in Firestore, adding it to FlutterFlow would have been a feature request, not a bug report. 

I can suggest 2 workarounds:

* If he’s comfortable writing a little custom code, then:
  * Create a custom function that accepts the array, the index and what should be updated.
  * Use “Set Value” with the output of this function
* Use 2 Firestore actions: first “Remove from Set” for the old value, then “Add to Set” for the updated value. But note that this won’t preserve the order of items in the list.

Sorry for any confusion and for the slow turnaround.

**Comment by gianverdum** [comment]
I appreciate your response, but I have a differing viewpoint. The ability to set collections in Firebase supports this type of operation, which leads me to believe it should be feasible. While I understand that configuring action flows within FlutterFlow is possible, the current situation indicates that the data isn't persisting in Firebase as intended.

Jones, my co-founder, has also highlighted that, even if this scenario doesn't align with an existing feature, it remains an identified front-end issue. The fact that we send a request and receive no confirmation of it working correctly is indicative of a bug. While it might require a feature request to address this specific aspect, it's crucial to acknowledge the front-end behavior that has brought this issue to the forefront.

Considering this, we may need to explore alternative solutions to address the situation.

**Comment by aemelyanovff** [comment]
@gianverdum If you still believe this to be a bug, could you write steps to reproduce it from a blank project? Something like this:

* Create data type with these fields.
* Create collection with that fields.
* Create new page.
* Create new button with this action and these parameters.
* Expected behavior: this, actual behavior: that.

Ideally keep the steps minimal, i.e. exclude details that aren't relevant to reproducing the bug.

Steps to Reproduce in the issue description describe the behavior of your project, but I'm having hard time understanding what's the bug in FlutterFlow.

Again, sorry for any confusion.

**Comment by gianverdum** [comment]
Hey @aemelyanovff,

I remain convinced that this is indeed a bug. However, due to my current commitments, I won't be able to dedicate time in the upcoming weeks to create a blank project and guide you through a simple way to reproduce the issue. I'm currently deeply involved in a taskforce aimed at delivering an MVP and ensuring that we validate the product in time for the next YC batch application. I hope you understand my situation and can explore alternative approaches to address this.

Have you considered reaching out to @hariprasadms to inquire about how they managed to reproduce the issue? His insights might shed some light on the matter.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/80184354/32789d01-5bc2-4524-9359-fe7c66feee55)

Thanks for your understanding.

**Comment by aemelyanovff** [comment]
@gianverdum If it's about absence of "Set at index" method then it can't be classified as a bug as I explained above. Please consider the alternatives that I mentioned in that response.

It it's a bug in an existing feature then we need reproducible steps starting from a blank project.

Other than that, I can only suggest reaching out to FlutterFlow support. This issue tracker is reserved for bugs in existing functionality with clear steps to reproduce.

**Comment by shufflehouse** [comment]
@gianverdum 
@hariprasadms 
@aemelyanovff 

Hey guys, found a workaround...total pain but does work. 

1) Query document to update
2) Create a local state (data type list)
3) Add Action: Update local state, Set Value, Value to set: current list (from your queried reference...see step 1) 
4) Add Action: Update local state, Add to List, Value to add: Create Data Type, set individual fields
5) Add Action: Backend Call, Update Document, Reference (see step 1), Set Fields, Set Value, Select local state

Thanks for starting the conversation! Pay it forward and have a great day!
