### ISSUE TITLE
flutter_native_splash 2.3.1 which depends on image ^4.0.17, image ^4.0.17 is required. So, because grateful depends on image 4.0.15, version solving failed.

### ISSUE THREAD

**Issue by sgardoll** [FlutterFlow/flutterflow-issues#1216]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- Click Settings --> App assets --> splash
- Change min duration to 1
- Click run mode or test mode
- Recieve message that lutter_native_splash 2.3.1 which depends on image ^4.0.17, image ^4.0.17 is required.
So, because grateful depends on image 4.0.15, version solving failed.

### Expected Behavior

- It should run fine

### Steps to Reproduce

- Click Settings --> App assets --> splash
- Change min duration to 1
- Click run mode or test mode
- Recieve message that lutter_native_splash 2.3.1 which depends on image ^4.0.17, image ^4.0.17 is required.
So, because grateful depends on image 4.0.15, version solving failed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Context

Just trying to create a nice splahs screen

### Visual documentation

![Screenshot 2023-08-05 at 1 40 10 am](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/260c8212-399f-4960-b7dd-cdc32e48d149)

### Additional Info

![Screenshot 2023-08-05 at 1 40 10 am](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/626b0dc4-332f-477e-90ab-90beaf8ad2a1)

### Environment

```markdown
- FlutterFlow version: 3.10.14
- Platform: Mac OS 14.0 Beta (23A5276g)
- Browser name and version: Chrome 115.0.5790.114
- Operating system and version affected: as above
```

**Comment by hariprasadms** [comment]
Hi @sgardoll - This is duplicate with #1212. It's been fixed already. It will be available in next update.

**Comment by danielmeza** [comment]
@hariprasadms I have the same issue today
Error: Failed running flutter pub get...
Because custom_widget depends on flutter_native_splash 2.3.1 which depends on image ^4.0.17, image ^4.0.17 is required.
So, because custom_widget depends on image 4.0.15, version solving failed.

**Comment by wenkaifan0720** [comment]
Hi @danielmeza. We have fixed this issue. Please wait for a few days until the fix is live. Thank you.
