### ISSUE TITLE
Unusable flutter flow dashboard

### ISSUE THREAD

**Issue by andrewccaris** [FlutterFlow/flutterflow-issues#1218]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When logging in the menu text is not legible

### Expected Behavior

Able to read all displayed text in the web app

### Steps to Reproduce

Open web app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lcr1z89goctF0aXcdvlahjw5Jlg3becF0up7aCosfZT2BLMcec/RVERoZ7TmTXNAI1mgo2oW0srzit/fN/UFNRGdRr5Ezql2dQrzWn66RYyxFJWgZXF7P5pRCEDE0ZivvhFRBPBZcV417V6uDOqiZBfbHbn4OUVBDq/LZO4=

### Context

Unable to code

### Visual documentation

![Screenshot_Home_Screen](https://github.com/FlutterFlow/flutterflow-issues/assets/6655289/43b988b3-c1cc-4e02-8420-e30a216455ff)
![Screenshot_Project_View](https://github.com/FlutterFlow/flutterflow-issues/assets/6655289/d7ab00b6-57ca-404f-9a7c-8bcb7fc621b1)
![Screenshot_Widget_View](https://github.com/FlutterFlow/flutterflow-issues/assets/6655289/2cc87c51-238f-475a-baa9-e5addfa12a7e)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Brave v1.56.20 Chromium to 115.0.5790.171
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @andrewccaris - Thanks for submitting the issue. This behaviour mostly to do with browser windows size. Currently we got a known issue that FlutterFlow UI elements displayed inconsistently when browser size is minimised( less than 100%). I would suggest, zoom out the browser size to 100% and see if that can help you. Let us know how it looks. Thanks
