### ISSUE TITLE
Copy / Paste and Duplicate functions are throwing an exception

### ISSUE THREAD

**Issue by dkoontz** [FlutterFlow/flutterflow-issues#1219]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I copy / paste or choose duplicate on an element in the widget tree nothing appears to happen. In the dev console I see an error message.

### Expected Behavior

A new element should be added to the widget tree that is a copy of the selected element.

### Steps to Reproduce

1. Open a new blank project
2. Go to the HomePage
3. Right click the column element
4. Choose duplicate
5. Look in the developer console and see the exception

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiMjfsJRIocMA1aqBbO9ajjgXMjt9R4EvmsJDdCs9CZDoOu9+Pcn7bk1oXbSkYENhHGf+oDgzwPDShtrLD/ldZDmVQYhb/7hPWgric3q8RLKoEruaXUBRL9NPI0i507TYhhEnAOxoWHBm2U6QBuutQXLBJ5+/Zwh9f6PHaOI=

### Context

I cannot copy/paste elements and have to create them each time from scratch.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/7493/de345b35-37ff-412e-bda1-81bd99aeed91

### Additional Info

Uncaught Error: NoSuchMethodError: s is null
    aYO https://app.flutterflow.io/main.dart.js:400250
    bNz https://app.flutterflow.io/main.dart.js:400262
    akk https://app.flutterflow.io/main.dart.js:377255
    s https://app.flutterflow.io/main.dart.js:5934
    $2 https://app.flutterflow.io/main.dart.js:149286
    v https://app.flutterflow.io/main.dart.js:5920
    cqx https://app.flutterflow.io/main.dart.js:377270
    akk https://app.flutterflow.io/main.dart.js:377244
    acR https://app.flutterflow.io/main.dart.js:377238
    s https://app.flutterflow.io/main.dart.js:5934
    $2 https://app.flutterflow.io/main.dart.js:149286
    $1 https://app.flutterflow.io/main.dart.js:149280
    adK https://app.flutterflow.io/main.dart.js:150660
    $0 https://app.flutterflow.io/main.dart.js:149754
    b9v https://app.flutterflow.io/main.dart.js:6078
    JP https://app.flutterflow.io/main.dart.js:149674
    hH https://app.flutterflow.io/main.dart.js:149269
    u https://app.flutterflow.io/main.dart.js:5924
    adF https://app.flutterflow.io/main.dart.js:375993
    s https://app.flutterflow.io/main.dart.js:5934
    $2 https://app.flutterflow.io/main.dart.js:149286
    $1 https://app.flutterflow.io/main.dart.js:149280
    adK https://app.flutterflow.io/main.dart.js:150660
    $0 https://app.flutterflow.io/main.dart.js:149754
    b9v https://app.flutterflow.io/main.dart.js:6078
    JP https://app.flutterflow.io/main.dart.js:149674
    hH https://app.flutterflow.io/main.dart.js:149269
    u https://app.flutterflow.io/main.dart.js:5924
    e0a https://app.flutterflow.io/main.dart.js:131724
    s https://app.flutterflow.io/main.dart.js:5934
    $2 https://app.flutterflow.io/main.dart.js:149286
    $1 https://app.flutterflow.io/main.dart.js:149280
    adK https://app.flutterflow.io/main.dart.js:150660
    $0 https://app.flutterflow.io/main.dart.js:149754
    b9v https://app.flutterflow.io/main.dart.js:6078
    JP https://app.flutterflow.io/main.dart.js:149674
    hH https://app.flutterflow.io/main.dart.js:149269
    u https://app.flutterflow.io/main.dart.js:5924
    bgE https://app.flutterflow.io/main.dart.js:51547
    s https://app.flutterflow.io/main.dart.js:5934
    $2 https://app.flutterflow.io/main.dart.js:149286
    $1 https://app.flutterflow.io/main.dart.js:149280
    adK https://app.flutterflow.io/main.dart.js:150660
    $0 https://app.flutterflow.io/main.dart.js:149754
    b9v https://app.flutterflow.io/main.dart.js:6078
    JP https://app.flutterflow.io/main.dart.js:149674
    hH https://app.flutterflow.io/main.dart.js:149269
    u https://app.flutterflow.io/main.dart.js:5924
    eX https://app.flutterflow.io/main.dart.js:279256
    s https://app.flutterflow.io/main.dart.js:5934
    $2 https://app.flutterflow.io/main.dart.js:149286
    $1 https://app.flutterflow.io/main.dart.js:149280
    adK https://app.flutterflow.io/main.dart.js:150660
    $0 https://app.flutterflow.io/main.dart.js:149754
    b9v https://app.flutterflow.io/main.dart.js:6078
    JP https://app.flutterflow.io/main.dart.js:149674
    $0 https://app.flutterflow.io/main.dart.js:149721
    kUF https://app.flutterflow.io/main.dart.js:6110
    kVH https://app.flutterflow.io/main.dart.js:6112
    $1 https://app.flutterflow.io/main.dart.js:149224
    lz9 https://app.flutterflow.io/main.dart.js:4676
    s https://app.flutterflow.io/main.dart.js:4684
    setTimeout handler*bYU https://app.flutterflow.io/main.dart.js:149240
    kON https://app.flutterflow.io/main.dart.js:5914
    jyP https://app.flutterflow.io/main.dart.js:5910
    a_2 https://app.flutterflow.io/main.dart.js:150669
    ir https://app.flutterflow.io/main.dart.js:6195
    eO https://app.flutterflow.io/main.dart.js:6002
    $1 https://app.flutterflow.io/main.dart.js:137208
    adK https://app.flutterflow.io/main.dart.js:150660
    I8 https://app.flutterflow.io/main.dart.js:149607
    $0 https://app.flutterflow.io/main.dart.js:149764
    b9v https://app.flutterflow.io/main.dart.js:6078
    q6 https://app.flutterflow.io/main.dart.js:149677
    $0 https://app.flutterflow.io/main.dart.js:149727
    kUF https://app.flutterflow.io/main.dart.js:6110
    kVH https://app.flutterflow.io/main.dart.js:6112
    $1 https://app.flutterflow.io/main.dart.js:149224
    lz9 https://app.flutterflow.io/main.dart.js:4676
    s https://app.flutterflow.io/main.dart.js:4684
main.dart.js:4595:3
    q https://app.flutterflow.io/main.dart.js:4595
    kv8 https://app.flutterflow.io/main.dart.js:7360
    a85 https://app.flutterflow.io/main.dart.js:7499
    $0 https://app.flutterflow.io/main.dart.js:150632
    kUF https://app.flutterflow.io/main.dart.js:6110
    kVH https://app.flutterflow.io/main.dart.js:6112
    $1 https://app.flutterflow.io/main.dart.js:149224
    lz9 https://app.flutterflow.io/main.dart.js:4676
    s https://app.flutterflow.io/main.dart.js:4684
    (Async: setTimeout handler)
    bYU https://app.flutterflow.io/main.dart.js:149240
    kON https://app.flutterflow.io/main.dart.js:5914
    jyP https://app.flutterflow.io/main.dart.js:5910
    a_2 https://app.flutterflow.io/main.dart.js:150669
    ir https://app.flutterflow.io/main.dart.js:6195
    eO https://app.flutterflow.io/main.dart.js:6002
    $1 https://app.flutterflow.io/main.dart.js:137208
    adK https://app.flutterflow.io/main.dart.js:150660
    I8 https://app.flutterflow.io/main.dart.js:149607
    $0 https://app.flutterflow.io/main.dart.js:149764
    b9v https://app.flutterflow.io/main.dart.js:6078
    q6 https://app.flutterflow.io/main.dart.js:149677
    $0 https://app.flutterflow.io/main.dart.js:149727
    kUF https://app.flutterflow.io/main.dart.js:6110
    kVH https://app.flutterflow.io/main.dart.js:6112
    $1 https://app.flutterflow.io/main.dart.js:149224
    lz9 https://app.flutterflow.io/main.dart.js:4676
    s https://app.flutterflow.io/main.dart.js:4684

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Firefox 116
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @dkoontz - Thanks for submitting the issue. I have tested your project and can see duplicate and copy/pasting elements working fine. See below. Are you facing the issue yet?

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/9a4b266b-ac28-412b-81c5-62523b9342ef

**Comment by dkoontz** [comment]
I tried again today, I still get the error in Firefox, I do not get the error in Chrome.

**Comment by mildlyconfused** [comment]
Same issue happened to me with no explanations. Flutterflow's Firefox version appears to have bugs while Chrome does not. I suggest you still attempt to fix (instead of closing as not a bug) and/or prompt users to not use FireFox at all.
