### ISSUE TITLE
Choice Chip - when disabled ignores theme settings

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1220]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you have choices chips with the theme colours set by variable: it all showings correctly, until you disable the widget with the disable property, then the colour by variable settings is ignored for unselected items and instead shows whatever colour was set in the designer.

### Expected Behavior

When disabled it should take the "colour by variable" setting that is in place and not ignore it.

### Steps to Reproduce

1. create page
2. add choice chips with colour by variable
3. set an default option
4. then use the disable property to disable the widget
5. the set  "colour by variable" setting for unselected options is ignored and uses the colour set in the designer.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8shsrqx5NgoctZ1s7ide9VoGA5KW4/bZIaluwadw8gGJD2PewTe+D4RFNWUu7ma1NcDWKJ8XsJps77vfPLFcBeaASuUao4+M52Sxble16iVq67DZeJP3BSJ+5YIFy51qu3ryNdHLJ2dEElxkyYCdiXaBfDJrLJOzM7HvKiVYbIn2yfGjLBIDgz0W45HkuVCuQXIVDq+f6QspZl1eTjzw==

### Context

Cannot complete advanced multi theme app as theme colours of the disabled options do not render correctly.

### Visual documentation

set style from "color by variable":
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/40566075-9447-44b9-88a0-50bde910d20d)
set to disabled:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/15a2a111-a70e-4e6b-9057-f98b32095357)
Run app, and will see the unselected options do not have the colour what is set by the "colour by variable"
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/b79c6be8-9d23-4960-8ad9-aaeda5418a98)
it is taking the variable from the original colour in the designer.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for reporting the issue. I can reproduce the issue. Thanks

**Comment by vishalagarwal2** [comment]
Hi this issue has been fixed and will be applied in our next deploy!
