### ISSUE TITLE
Team Design Duplicate BUG

### ISSUE THREAD

**Issue by Guy-W2** [FlutterFlow/flutterflow-issues#1221]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey
I found a bug in the Team Design library
When trying to duplicate Team Design
This duplicates it as a project and not as a Team Design

### Expected Behavior

that duplicates the Team Design as another Team Design COPY

### Steps to Reproduce

that duplicates the Team Design as another Team Design COPY

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

that duplicates the Team Design as another Team Design COPY

### Context

that duplicates the Team Design as another Team Design COPY

### Visual documentation

that duplicates the Team Design as another Team Design COPY

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: 
that duplicates the Team Design as another Team Design COPY
```

**Comment by victoriahuang1** [comment]
Hi @Guy-W2 , thanks for the report. This issue should be fixed upon the next deploy!
