### ISSUE TITLE
Refresh Database Request Causing Crash When Triggered On a Child Widget Within a Column with Supabase Query 

### ISSUE THREAD

**Issue by dellsmash** [FlutterFlow/flutterflow-issues#1222]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using A column to create a list view and placing an Icon to delete the currently clicked record, When triggering action "Refresh Database Request" on the parent column widget  after Backend 'delete row' causes entire column to crash

### Expected Behavior

Should be able to delete a selected row within a data drivin column by using a widget to trigger a delete row action.  I believe this works as expected when using a list view widget and adding a widget to delete current row.

### Steps to Reproduce

1. Create page
2. Add Column
3. Add Backend Supabase Query
4. Add Container as first widget (Gets replicated with rows returned in query)
5. Add text fields to display record
6. Add Icon.  On this icon add action to delete supabase row, then refresh backend query on the parent column

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wzsnf5c12rsdK1aXqLO9VliYXQlgmUIIFkcN+SQIafYDkPLYPQf7BSFRuZryodH9XeWekhmcyxvfqjePQGvpfCxyYf7ZkzJZQZwvxRTq7RYyLPrWRfW1RBcJnCHak17bYggpCHNdudGRg3FyEIeiXcCjtJqa3OVcjD86bKdeK2SrDX1iXc2URm05KZDPz

### Context

Generate Simple List Views Using Columns With The Ability To Delete A Row And Refresh The Query

### Visual documentation

None

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 115.0.5790.111
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @dellsmash - Thanks for submitting the issue. I apologies for being late resending on the issue. I did follow above steps and I can confirm that, deleting supabase row along with data base refresh action in a column widget, is working as expected and no errors.

The project bug report code you provided above is not from a blank project with issue steps. Without this detail its a challenge for us to investigate the issue. If issue still exists, add the details, we can investigate the issue. 

I also presume, with the latest FF updates, issue has been resolved for you. If this is the case, let us know we will close the issue.
