### ISSUE TITLE
Api not Executing after web Publishing , but working fine in test mode 

### ISSUE THREAD

**Issue by mrbose-a** [FlutterFlow/flutterflow-issues#1225]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am Calling a Post Api to send OTP to users, The Execution is Working fine on Debug mode, but When Publishish On Web the Api is Not executing at all. 

### Expected Behavior

API should Execute on the Web 

### Steps to Reproduce

Define Post Api - https://docs.fast2sms.com/#post-method10

Update page state >> otp Random string >> phone number from Widget State >>

Execute Api With the above 2 variables .

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cjs/l7ZdPm7RG+KryKMAwoCUvKUQ1RYIrkdZDc00dDZPOD7AQP8nRP1dUOcPgT29iMVqanmQX/MrViYfXKPFfPSedbKZS1rtpWgriZDiVRc2nEb63b39PHZtRBWKD5qujiCZ5CMx0S3gi7HGYOOe/XjXaO4z1NVQeQuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to send SMS OTP to users via an API so that their phone numbers can be verified,, the Action Are executing without Complication When I am Using the TEST mode in FlutterFLow , But on the WEB Published version The Whole Actinon Chain Is not Executing, I know Run mode and WEB is basically the same but It is not working on the Web.   Please See the attached video link I tried to explain it to the best of my ability 

https://clipchamp.com/watch/Xh6oEx1FPFDtheir

### Visual documentation

![Screenshot 2023-08-04 162350](https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/f706138a-9499-459b-9001-6aee412e90da)
![Screenshot 2023-08-04 162030](https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/692bd204-8b7e-4e62-82a0-6a073485d84e)
![Screenshot 2023-08-04 162012](https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/66555e8b-c11a-4579-9328-f81228551381)
![Screenshot 2023-08-04 161948](https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/7430ee90-1e8a-4b42-a7e1-bb76a0ba1107)
![Screenshot 2023-08-04 161906](https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/d308683c-0d64-46c1-9128-71d05cc2b9ff)

### Additional Info

https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/ca6afda0-e8da-44ce-96a2-07b4cb1df726

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: Version 115.0.5790.111 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language
```

**Comment by mrbose-a** [comment]
I also had a chat with the API provider, they mentioned, I might have an Integration Issue , and they are not able to help with that.

**Comment by hariprasadms** [comment]
Hi @mrbose-a - Thanks for submitting the issue. I looked at your project. I see below observation. 

1. Remove the comma and see if there is a difference in the result. 
2. As the endpoint got authentication, I would suggest mark the api call as private and see the result.

<img width="361" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/c07b420f-e54d-40b9-8395-b7c22cf62a3d">

**Comment by mrbose-a** [comment]
@hariprasadms thank you for looking into this Hari. 
1. the api couldnt be marked private >> error message multipart Api can not be Private 
2. Screenshot Attached : ""Access to XMLHttpRequest at 'https://www.fast2sms.com/dev/bulkV2' from origin 'https://businessjugaroo.flutterflow.app' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.""
![Screenshot 2023-08-07 233332](https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/4e426b67-8a62-4538-9400-621ce5a4155a)

**Comment by SameerShahzad99** [comment]
This CORS actually is related to your API and its configuration, please take a look at this article to understand your problem and how you can resolve this:  https://intercom.help/flutterflow/en/articles/8036270-understanding-api-calls-cors-and-flutterflow
Considering this as not a bug from FlutterFlow!

**Comment by mrbose-a** [comment]
Ureka I have the API working ... I changed the body from' Multipart' to 'x.www-form-urlencoded' made the call private and for authenticated users - deployed the cloud function for the API call and it worked ... thank you everyone for being there while I panicked.
