### ISSUE TITLE
upload media

### ISSUE THREAD

**Issue by ameeraidl** [FlutterFlow/flutterflow-issues#1226]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

getting issue while uploading media.. it shows error that current variable is not valid

### Expected Behavior

i am trying to store the images in firebase storage but it shows error while uploading and also it is not showing the type of upload 

### Steps to Reproduce

first i dragged an imageview..
i taken a button..
for the button i set action to upload media.. (type is not visible to set)
for image i am setting from variable source from widget state..
at the time of confirm it shows current variable is not valid.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wls/q+clOodtc0L6JcflF/SAXGDp6bJIVku1xSis/CpTuPbMIfPfDalZVXeG+dghqIGH8rHodzMnFm9z2Gu1ePTWqfKJDypNITRXwYGWjbqauDYeSSHR+GshUGlyi18KFhR4lXdhaSUJi7zmLf+q9Y3XaQ5y2PW0vO8iXNofXmAfuQ0SLb3kNh1JWeC/v

### Context

i am trying to upload image into firebase storage but it doesn't showing the type of upload and while setting the image path from variable from source widget state it shows error that current variable is not valid 

### Visual documentation

![Screenshot 2023-08-08 162151](https://github.com/FlutterFlow/flutterflow-issues/assets/139689636/7c71f31b-946b-4e03-9273-5d3364d3d3ab)

### Additional Info

solve the problem as soon as possible

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: flutter 3.10.4
- Browser name and version: chrome  115.0.5790.111
- Operating system and version affected: microsoft windows 11
```

**Comment by ameeraidl** [comment]
how to solve that current variable is not set issue?

**Comment by sohaan07** [comment]
im facing the same issue.
