### ISSUE TITLE
Update document lacking 'submit empty list' option 

### ISSUE THREAD

**Issue by Mattmannn** [FlutterFlow/flutterflow-issues#1227]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to create a field that the app knows will contain a list of some sort, FF forces you to fill it with something, so currently you have to create a dummy empty list app state in order to fill the Firestore field with nothing, even though Firestore natively allows you to create an empty array, as only later you determine the type of its contents. FF is lacking that feature, as creating a custom data type which is a map of lists of strings somehow accepts that the list can be empty, but if you try to submit a map of lists of doc refs for example, FF will force you to submit _something_.

### Expected Behavior

Ability to submit a list field which is devoid of any fields initially (for consistency of the data structure for example). 

### Steps to Reproduce

1. Create a custom data type with at least one field, which is a list of document references.
2. Set up a collection schema in FF that has a field with the data type you just created
3. Assuming Firestore is plugged into the app, add a backend call to create a document
4. 'Set fields'
5. 'Set data type'
6. 'Set individual fields'
7. No way to create the field alone, without filling it with something

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oivLqy4Z1ru5E7a6Jd+9VnSQ7KUR7apEv0cpOGDsdF4iuPOxzaeP7blJoXszhYGNlKEWJrGMK0cL9jvzxD/leFyuqfoQ7/pNicg7dQki/aoSKEs2sQ2pCI/hgJnKx06bUoBBdB/ttLGQh2Ey2A+e/FxTaH4P7Zwh9f6PHaOI=

### Context

Create a Firestore document with an empty list field 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8464443/3213b2ca-49a5-4359-8bf9-47dc0b55294c)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Windows Desktop
- Browser name and version: (Chrome desktop app) Chrome 115.0.5790.171
- Operating system and version affected: Windows 11 22H2
```

**Comment by kevintonb** [comment]
Hey @Mattmannn , thank you for reporting the issue that you're facing and getting in touch. This will have to be a feature request as this isn't a bug within the platform itself. Thank you very much for sharing your feedback, I will send this back to the team for review :) Closing this issue for now.
