### ISSUE TITLE
Canvaskit not showing media/ images

### ISSUE THREAD

**Issue by mgoering81** [FlutterFlow/flutterflow-issues#1228]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when rendering the app using the Canvaskit beta, webapp looks fine with the exception that no images (e.g. profile pictures) are displayed. Also no placeholder or error message are visible. Re-deploying the webapp using the traditional renderer solves the issue and all images are displayed as expected.

### Expected Behavior

display images regardless of used renderer in webapp

### Steps to Reproduce

1. have page with image from firebase
2. publish web app using canvaskit
3. visit page and see... nothing :)
4. re-publish using html renderer
5. visit page and see image as expected

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8iBx852pbwA7qX2Ke9Whjs7JkR9aIc0rdx+EBAjfYz4PYoAZszeRBNoOLWzaH9cJln+uGoJ+dLphYfLE/Y5OUusG4hb1pF2EhPPbE6uSrWbOpeOOXx8DexXGBG857WJ3RVdLbFZcngZ7TquHe+/Hj6Cf9qOYwx5e6fDbOY=

### Context

stops me from using CanvasKit for deploying to the web

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/112511052/849da2f7-2975-4498-b883-40dc695359f5)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: edge
- Operating system and version affected: mac os
```

**Comment by hariprasadms** [comment]
Hi @mgoering81 - Thanks for submitting the issue. Your environment detail says, browser type is Edge. FlutterFlow is not fully tested on Edge browser. FlutterFlow recommend to use Chrome as it is fully tested. Try in chrome and let us know the result. Also, can you share what error your see in browser console while images are not loading please?

**Comment by gentleVirus** [comment]
> 

Hi, I am facing the same issue even with the newest chrome version.

**Comment by mgoering81** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/112511052/2afdc745-1638-4dbb-abd6-0920c1d7b7e7)

pls see screenshot. I recreated from a new project and face the same issue.

**Comment by sbis04** [comment]
This is not actually a bug, but rather a CanvasKit limitation. There is a [guide](https://docs.flutterflow.io/actions/actions/utilities/upload-data#web-access-for-pdfs-and-other-files) in our documentation to solve this issue, though it's not specific to images but it will work for any kind of resource loaded from the Firebase Storage of the project. Let me know if it solves the issue.
