### ISSUE TITLE
Setting TextBoxTile by Variable

### ISSUE THREAD

**Issue by Djacksonspears** [FlutterFlow/flutterflow-issues#1229]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting the text box tile by variable it will return a blank textboxtile.

### Expected Behavior

I expected it to show my variable value

### Steps to Reproduce

1.Create List View
2.Child TextBoxTile
3.Set By variable (i used database field)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMjfsJFPm9tK18/Ub8Fr/SYWH1g+R+c0scp8WQgafIjJP4kQPPXsRBRtTsekd1Z+IkSmmkUypMHHk/D+UPFeCyeCQbpl/rtuaAzhTmKmUZOBEc2CeHdRPJ5Qfnai0bS7vBZvKvVpWkY+6k+QP+utHzDqNL2wIndISq/LZO4=

### Context

I was trying to set the text value of the box by variable.

### Visual documentation

https://flutterflow.intercom-attachments-3.com/i/o/803148589/3a647528202b187fc85209a3/Dashboard+-+FlutterFlow+and+4+more+pages+-+Profile+1+-+Microsoft%E2%80%8B+Edge+2023-08-08+10-57-55.mp4?expires=1691516095&signature=a31eccf7831ffceb54ed7729386b50944c9220944a2bcc87f1dcc777e2655131

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: edge 115.0.1901.188 
- Operating system and version affected: windows 11
```

**Comment by hariprasadms** [comment]
Hi @Djacksonspears - Thanks for submitting the issue. Above reproducible steps are not clear. Example when you say _Child TextBoxTile_ , not sure which widget you are talking about and the given project bug report code is not a blank project with issue setup. Also the _Visual documentation_ video link is not accessable. Please update the issue with these details.

**Comment by kevintonb** [comment]
Hey @Djacksonspears , we're closing this issue as we have not received any further information on the bug that you have reported. If you still see the bug and if it is reproducible, feel free to add to this thread so that we can reopen this issue and investigate further :)
