### ISSUE TITLE
Set option is hidden in property panel

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#123]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/5080329/201521743-51985ec7-be57-45ce-8613-85a6468c394d.png">

**Comment by hariprasadms** [comment]
Hi @thruthesky - I can confirmed that this is happening when long string names are given. Meanwhile, as a workaround can check if this can works fine by resizing the browser window.

**Comment by asmengistu** [comment]
Thanks for reporting! Should be fixed with the next release :)
