### ISSUE TITLE
Using a Custom Dialog Alert in an Action Block Doesn't Work

### ISSUE THREAD

**Issue by Fibn007** [FlutterFlow/flutterflow-issues#1230]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, whenever I call a custom dialogue alert from within an action block, it throws the following error (Happens in test mode and run mode, when downloading apk it hangs as soon as it crashes at this point):
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/3d37dd42-b42c-4bc6-8e74-4583bd51e537)

I'll also provide the context of the custom dialogue component:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/bb19504a-feb0-4d4a-b842-231fe9f8c2db)

The component can literally just be a container of any length. It throws that exact error for any container size in the component. The exact same code works outside of an action block. 

### Expected Behavior

When calling the custom dialogue, it should contain the contents of the component being invoked. 

### Steps to Reproduce

1) Create a component of just a container, any size
2) Create an action block that calls that component using "Custom Dialogue"
3) Copy the configs in this picture:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/4d938ba0-87e0-4346-892f-eacb1976783e)
4) The entire flow stops and crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kvLlw4tNrsdG+KXydcFFmjgWQ187aLsVi+5tTUs8J5DaPOxzP/TBaldWUs+0d2xbM2eWpzge06jemvP9O8ACJUiWQIhgzpFcFwvwfHGXb6nQCc6aOm5/DdxRC2Kz1rerhwlSBM9hdGAdwFy6ANitVgTANLLBOlQjRsiXOZOK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to display a loading animation from an action block that will be reused in several places. The loading animation will now need to be copy pasted every time I use it, since it won't work in an action block. 

### Visual documentation

Pictures provided in explanation

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Windows Desktop App
- Browser name and version: Chrome Version 115.0.5790.171
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Fibn007 - Thanks for submitting the issue. I have tested above steps. Custom dialogue display is working as expected and no errors are displayed. Are you still facing this issue?

I'm assuming there was a missing configuration on your end. I may therefore mark the issue as _not a bug_. If you are still having issue, please let us know. I can look into it again. Thanks
