### ISSUE TITLE
Box Shadow can not works according to conditional value.

### ISSUE THREAD

**Issue by Harsh1052** [FlutterFlow/flutterflow-issues#1232]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently I have added condition value in the box shadow which should work according to applied conditions.
![Screenshot 2023-08-09 at 11 02 53 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/72139154/56ab6e5d-9ab3-4c3f-a86b-9500e7591345)
Here is the generated code for this box shadow color. It seems like code has not applied condition on the box shadow.
![Screenshot 2023-08-09 at 11 06 09 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/72139154/164c3f48-9f42-40a3-9c79-1e2a6dd1ef80)

### Expected Behavior

It should applied condition in generated code side according added from Flutterflow UI builder side. So that it works on the output in the app.

### Steps to Reproduce

1. create container
2. Add shadow into container
3. Add condition ( Conditional value) for the color of the shadow.
4. Then run the app or check generate code of flutetrflow for that screen
You will get that issue by following these steps.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiufq3It2j7xY17X5bcJviicRHEw1TL03pu0bFEggGLbrBIYMafTOUEtuZMPjTG9LKEWL+DoBwdLwvtntGMc5CzGtG7Zgz6gBTQ3hWjm/aoSSBaWCOkdQQOFQFXaG3KeN2gpQGOhvL1Fm7FymBt6WaAHcJ4/4Zwh9f6PHaOI=

### Context

I am trying to add conditional shadow color into the list of item. When I did into Flutterflow side it has options to add conditional value but when I run tha app that shadow value did not work. So I checked generated code and I found that it had not added condition at that place.

### Visual documentation

Applied condition.
![Screenshot 2023-08-09 at 11 02 53 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/72139154/50e4553c-a2ff-4b99-9898-cf9599957905)

Generated Code.
![Screenshot 2023-08-09 at 11 06 09 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/72139154/4f23dbb2-14fb-46be-b548-08870a6770bb)

### Environment

```markdown
- FlutterFlow version: 3.1 and Flutter - 3.10.1
- Platform: All Platform
- Browser name and version: Chrome 115.0.5790.170 (Official Build) (arm64)
- Operating system and version affected:
```

**Comment by sbis04** [comment]
Hey @Harsh1052, I wasn't able to reproduce this issue. I tested it in a [demo project](https://app.flutterflow.io/project/shadow-test-m6gi6e), and it is working as expected!

Also, the code you are looking for is this:
<img width="673" alt="Screenshot 2023-08-12 at 10 05 57 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/6eeb48a3-0b8c-4fbe-a408-452794362c06">
