### ISSUE TITLE
Unable to save document in datamanager if the document contains subcollection reference

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#1237]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If i want to modify and save a document in the data manager, nothing happens if the document contains a reference for a subcollection
![CleanShot 2023-08-09 at 17 37 02](https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/30ab85b9-e13c-43e9-8bb2-b75ccfca03ed)

### Expected Behavior

save the document every time

### Steps to Reproduce

1. create 2 firebase collection
2. create a subcollection for one of them
3. add a DocRef field to one of them and it should be the subcollection
4. create some documents and add reference to the doc ref field
5. try to modify the document with the doc ref field in the data manager and observ that nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjcrl24VgrsMA1s7yLPpv9SYUCDt5R40s0MJTYCs8GZT0B4kcYs+kfklUcMekYFZhfGeWnn0X/Mr7v/DiFcJfBzWBQJhewpN+bTrgUkmnVaqxCoS3b0d5NJ9RCHay36ujpB0kBM91cloa2EyEO96vbDLBJ7rADno7Q+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I just want to use the data manager to manage my firestore collections

### Visual documentation

![CleanShot 2023-08-09 at 17 37 02](https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/599afac3-1248-4f93-885f-15e8f35dca6e)

### Environment

```markdown
- FlutterFlow version: v1.1.94-Flutter 3.10.4
- Platform: mac, web
- Browser name and version:chrome
- Operating system and version affected: mac ventura
```

**Comment by hariprasadms** [comment]
Hi @kicsijohn - What you are seeing is expected behaviour. The creation and modification of sub collections through data manager are not supported by FF at this time. Therefore, anything attempting to update with the sub collection reference can fail.

**Comment by kicsijohn** [comment]
Hi @hariprasadms, okay but I don't want to change or update the reference, I want to update other fields in a document but if the document contains just one subcollection reference it won't allow me to save it

**Comment by hariprasadms** [comment]
Hi @kicsijohn - I can see what your are trying to say. I have reproduced the issue. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/63c63a13-e396-4f9c-b781-4af79657146d

**Comment by kicsijohn** [comment]
> Hi @kicsijohn - I can see what your are trying to say. I have reproduced the issue.
> 
Thanks for taking another look

**Comment by takashiff** [comment]
Hi, this issue has already been mentioned at: https://github.com/FlutterFlow/flutterflow-issues/issues/854. Please reference this thread for any updates.
