### ISSUE TITLE
"videoplay" is not working on iOS.

### ISSUE THREAD

**Issue by ZeusFunk** [FlutterFlow/flutterflow-issues#1238]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use "videoplay" and set the URL as the video source, it works fine on web and Android. However, on iOS, the loading indicator keeps spinning and the video doesn't play.

### Expected Behavior

Under normal circumstances, it should work like Android, loading and playing the video. The URL I'm using is similar to "https://.../video.mp4", and it can be accessed directly in a browser.

### Steps to Reproduce

1. Create a blank project.
2. Use a videoplayer to load a URL as the video source.
3. Compile and run on iOS after compilation.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

This causes me to be unable to play videos from my server on iOS.

### Visual documentation

just loading indicator keep spinning

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @ZeusFunk - Thanks for submitting issue. Please update issue with project bug report code and environment details.

**Comment by SameerShahzad99** [comment]
Closed this issue because we have not received any updates from @ZeusFunk!
