### ISSUE TITLE
Paywall, RevenueCat in action block cause a return; with no true or fasle

### ISSUE THREAD

**Issue by davidflutterflow** [FlutterFlow/flutterflow-issues#1239]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If we use Paywall action inside an action block, after the condition check if entitlement is null > it return; without true or false that causing error in the code 
<img width="1009" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/57768d21-07d5-4c48-a2e2-cd5b4e70619f">
an

### Expected Behavior

Should return false

### Steps to Reproduce

1- any project with RevenueCat
2- create an action block
3- add paywall action
4- add condition right after
5- return values or do any action after
6- run or test and you will see the error message

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksrq24p2rsNK+Kr+bsBB/WIUQzs8a7hNscsZa0kdB4joPLJ/YPfsSEpWXu3mY1NhHFaluHo03PDwufztF8BdZCiBGL5nwqV2agrvd3q8RJiYEbqoY0RtL8NUf1Cu36SzvAokKsdvZV0s2E73CNyXcHPcGZ+/Zwh9f6PHaOI=

### Context

Create action block, Inside it we have paywall, then we use action block on a button

### Visual documentation

<img width="951" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/226232f9-2013-4173-b171-c55d39973826">
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/eaabf7e1-f1c0-43b5-8d68-3d93f32d9eb0)

### Additional Info

100% this is a bug i double check this

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by BrentM** [comment]
I'm also blocked by this issue. I'd appreciate it if you could bump the priority on this up.

**Comment by batllepreply** [comment]
Priority should be higher than low, considering this is one of the few ways to monetize the apps. I am waiting for the fix while paying a futterflow PRO account

**Comment by aemelyanovff** [comment]
Fixed in the next update!
