### ISSUE TITLE
App Store deployment failed

### ISSUE THREAD

**Issue by ndigacin** [FlutterFlow/flutterflow-issues#124]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The expected behaviour is to get the build completed and available in App Store Connect.

## Current behavior (required)

The build is failing every time preventing me to publish the app.

## To Reproduce (required)

1. Deploy to Apple Store
2.
3.
4.

## Context (required)

I have built my first app on the FF platform. Now I want to publish it on the stores and the build to the Apple Store is failing. Google play store was built wit no issue. As for the apple store, I was able to build 2 versions which I tested successfully. Since then I can no longer push a build to the App Store. Every build always fails with the same error. I copy/paste the error below:

Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Running "flutter pub get" in clone...                           
Warning: You are using these overridden dependencies:
! rxdart 0.27.4 (0.27.6 available)
Running "flutter pub get" in clone...                               3.9s

💪 Building with sound null safety 💪

Archiving com.piwo.app...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Automatically signing iOS for device deployment using specified development team in Xcode project: 45VRHV2M6A
Running pod install...                                            665.4s
Running Xcode build...                                          
Xcode archive done.                                         23.8s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-11-14 00:37:10.778 xcodebuild[60635:105723] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-11-14 00:37:10.779 xcodebuild[60635:105723] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** ARCHIVE FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/m7/h1mg7c7x40ddjz6mxjxm3htr0000gn/T/flutter_tools.zF01bu/flutter_ios_build_temp_dirdTDzhT/temporary_xcresult_bundle

    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    error: Provisioning profile "PiwoApp1 ios_app_store 1668385380" doesn't support the Associated Domains capability. (in target 'Runner' from project 'Runner')
    error: Provisioning profile "PiwoApp1 ios_app_store 1668385380" doesn't include the com.apple.developer.associated-domains entitlement. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/m7/h1mg7c7x40ddjz6mxjxm3htr0000gn/T/flutter_tools.zF01bu/flutter_ios_build_temp_dirdTDzhT/temporary_xcresult_bundle

Error (Xcode): Provisioning profile "PiwoApp1 ios_app_store 1668385380" doesn't support the Associated Domains capability.

Error (Xcode): Provisioning profile "PiwoApp1 ios_app_store 1668385380" doesn't include the com.apple.developer.associated-domains entitlement.

It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.
Encountered error while archiving for device.

Build failed :|
Step 8 script `Flutter build ipa and automatic versioning` exited with status code 1

## Screenshots / recordings

![Screenshot 2022-11-14 at 3 11 03 PM](https://user-images.githubusercontent.com/116641569/201756417-553b517d-ad99-4d5c-ad38-84cb901b51ba.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: Microfoft Edge latest version
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Hi, I have noticed this issue few times. This issue can replicate even after duplicating the app and rebuild it. Defiantly needs a bit of investigation around it.

**Comment by timfong888** [comment]
Can the user check and send screenshot showing associated domains has been set up in their apple developer account identifier for the related app?

**Comment by asmengistu** [comment]
As @timfong888 pointed out, this seems to be an issue with associated domains set up.

@ndigacin make sure you follow the setup steps listed here:
https://docs.flutterflow.io/advanced-functionality/deep-and-dynamic-linking#2.-ios-setup
