### ISSUE TITLE
 Signin/Signup with Google account in Android App developed by flutterflow

### ISSUE THREAD

**Issue by alcobraketeam** [FlutterFlow/flutterflow-issues#1240]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when i login/signup it's showing the Gmail account list, when i selected anyone Gmail account its just closing the window without showing any error on the screen.

I am trying to Signin/signup my Android application using Existing Gmail account by downloading the Apk from flutterflow, but am unable to login/signup. Iam able to login/signup by downloading the source code and run the app in android studio when i added SHA1 and SHA256 keys.

### Expected Behavior

Have to Navigate to another page when the Gmail account selected from the list while logging in

### Steps to Reproduce

1. create a new project in flutterflow.io by picking up an existing app
2. connect that app to database
3. enable gmail authentication and create pages/actions for Login 
4. Download the apk directly from the flutterflow
5. Download and install it in your mobile and test by signing in/signup with Gmail account.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cl8n1x4l1mMdY1c/uKMAwmikWQ0w/RYIrjMFDdwsdJ5PMC+wIZ/f7XFRuTde0YFZ+JU2jozsy3NHemvLDUvA7NQ2Bft1AybhqSQ7gZE+6WpSNC5DtRm5/DdhjfRGx17eJniZdOsdsdXwt3GCqNuiXEwrYNYf6Nm43J/2bMZCK2SrDX1iXc2URm05KZDPz

### Context

Because of this issue we are unable to login to our App using Gmail account

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/78728589/32ee9e05-043e-4188-ad84-3e502c771f2d

### Additional Info

Because of this issue we are unable to login to our App using Gmail account without logging in

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:Android
- Browser name and version: Android
- Operating system and version affected: All android versions
```

**Comment by hariprasadms** [comment]
Hi @alcobraketeam - Thanks for submitting the issue. This behaviour what you seeing is related the Secure Hash Algorithm (SHA) key configuration. Refer this section _**Additional steps for Google/Phone sign-in setup**_ at  https://docs.flutterflow.io/data-and-backend/firebase/authentication/initial-setup . Once you have done this configuration, rebuild and install the app in Android. You should be able to login with issues.

**Comment by alcobraketeam** [comment]
We followed these steps, still it did not work. After adding SHA keys as described in your documentation we built the app in flutterflow, downloaded APK file and installed on android phone. Sign in did not work. Then we downloaded the source code from flutterflow and built using android studio without changing any code. Installed that APK on android phone and sign in worked. What could cause this?

**Comment by FaizanAhmad127** [comment]
I am facing the exact same issue. Followed each and every step but still no luck. On apple devices it works like a charm but nothing on android.

**Comment by Fibn007** [comment]
Hi @hariprasadms, I've been trying to set up Google Sign in/Sign Up and am also running into the same issues as listed above. I got it to work on web for Test Mode and Run Mode, however it does not work on my real android device when I download the apk. This implies the SHA-1 is working and the domain I authorized for web app is also working. Essentially, I can also confirm that this isn't working for me as well.

**Comment by Fibn007** [comment]
Update: I uploaded the same exact version to the Google Play Internal track and it works. It still doesn't work when you download the apk. I'm not sure if this is a bug or not, but the documentation should be updated to reflect this if it isn't a bug.

**Comment by sacco-riffraff** [comment]
This might help: https://community.flutterflow.io/authentication/post/google-sign-in-not-working-on-android-but-is-working-on-web-and-ios-Rl77YRP9AApWDT2

**Comment by agni-s-chakraborty** [comment]
https://medium.com/@agnioffice10/how-to-fix-google-sign-in-issues-when-downloading-apks-from-flutterflow-f58c4d347c48
