### ISSUE TITLE
API Header getting formatted as string instead of json object

### ISSUE THREAD

**Issue by karanag** [FlutterFlow/flutterflow-issues#1241]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the API call definition this is how my header looks

Dropbox-API-Arg: [imgPath]

I use the following function to generate the JSON object for the above argument 

```

dynamic returnJsonImagePath(String path) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // return path as json with the key "path" and value beng the input path
  return jsonEncode({'path': path});

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```
Testing the above function returns {"path":"/iRug/test123.jpg"} which is a valid JSON object

But when I go to Response & Test under the API calls and enter the above JSON to the variable [imgPath] the headers are shown like Dropbox-API-Arg": "{path:/iRug/test123.jpg}" which means they are being read as String and not JSON. I am getting an error when I try to execute this API Call in Test mode.

Screenshot of API Call setup page
<img width="1003" alt="Screenshot 2023-08-10 at 6 42 29 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/79de6480-1e83-444e-a0f6-4689e08a2513">

The error on executing the code
<img width="446" alt="Screenshot 2023-08-10 at 7 33 21 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/a5430f1f-16bc-4961-a490-3ac6693b210b">

Successfully executed API call in postman with same arguments as being tried in flutterflow
<img width="1080" alt="Screenshot 2023-08-10 at 7 23 45 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/052136ec-9bf8-44cb-9cae-09aa06013866">

### Expected Behavior

The JSON object should be passed on as JSON only. 

### Steps to Reproduce

- Connect Dropbox by oAuth
- Create API call of the upload endpoint as per [this dropbox guide](https://dropbox.github.io/dropbox-api-v2-explorer/#files_upload)
- Try to execute the call
-

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.
- https://app.flutterflow.io/project/dropbox-a-p-i-test-yakali 
- The above link is to a blank project on which I reproduced this. The exact error is getting repeated.

### Bug Report Code (Required)

ITEej+fqw852j70D1qrya8J4jQMxQUB+bZ0vlO1FGAI3IrHpOrAMPM/UaXdYXfaqf2NhfU6L8U4e+fOKhvLxUfcFOS2rb7l607tIYDnJUk+QRc2IO5GSW39PEd1MCkuB06evkyJTOuhedGQjwF+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to store all media and documents on our Dropbox business account. This is critical as we use Dropbox as our primary server

### Visual documentation

<img width="446" alt="Screenshot 2023-08-10 at 7 33 21 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/710750d6-dca7-4121-8f71-fdf7e01f98a9">
<img width="1080" alt="Screenshot 2023-08-10 at 7 23 45 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/fdfa3222-983e-472b-8a68-6095e966bae9">
<img width="1003" alt="Screenshot 2023-08-10 at 6 42 29 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/4bd8ca20-2984-46bc-a799-268e2279bbf6">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 115.0.5790.170 
- Operating system and version affected: MacOS Ventura 13.2.1 (22D68)
```

**Comment by davidflutterflow** [comment]
We troubleshoot this in Support, i can approve this is an issue on our side

**Comment by wenkaifan0720** [comment]
Hi @davidflutterflow. Unfortunately we don't support API headers at the moment. But we will definitely in the future. Since this is more like a feature request, I will close this issue for now. Thank you.

**Comment by karanag** [comment]
Huh ??? 

API Headers not supported??

If I may ask what is this mysterious unknown word highlighted in the image below? English is not my primary language so maybe I am getting confused

<img width="1040" alt="Screenshot 2023-08-18 at 2 24 40 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13748283/6f42219a-209c-4f6b-b79a-bb81da954b63">

**Comment by Adventure-Hunt** [comment]
@karanag have you got this working? I also want to store files in dropbox.

**Comment by karanag** [comment]
> @karanag have you got this working? I also want to store files in dropbox.

Hi Yes,

I did manage to get it working but not via APIs. chatGPT helped me create a bunch of cloud functions and now everything from oAuth to upload, rename, delete,move etc is handled by cloud functions. In retrospect, I feel this ended up being a better and cleaner outcome.
