### ISSUE TITLE
instant reload not always update latest changes

### ISSUE THREAD

**Issue by dinasorz** [FlutterFlow/flutterflow-issues#1244]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In test mode, when clicking on instant reload a lot of times it doesn't update the latest changes, and I need to keep press over and over again till it updates.
This of course creates many false assumptions and bugs where you fixed the code but still think that it's not working from your side

### Expected Behavior

That the instant reloads should actually always reload and update the latest changes.

### Steps to Reproduce

Anyone who's working in FlutterFlow must have faced it where he needs to instant reload multiple times for it to update to the latest changes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojPLlvJFIocte7q6JccBKjSQsHH5+ap0nlMpBZywgfZzzBLN/fPfQPxBuUu2lTQlAJGacp14CzN7SiobXM8FdJTWsY4hczbVfWDvJUj2Wb6mTF7WKbWpBL9lMGWag052nvhNNKvpeWXAe1zuTON6XdCntGLrHPWo8Sq/LMBZO4=

### Context

It reduces productivity and creates many false assumptions and bugs where you fixed the code but still think that it's not working from your side

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/95580779/5e5462fa-81a8-415b-9a33-434f7141e6dd)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: PC
- Browser name and version: Google Chrome v115.0.5790.171
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @dinasorz - Thanks for submitting the issue. I have noticed this behaviour.

**Comment by karanag** [comment]
Yes, this behavior is there at FF and gets confusing at times. 

A low-tech way to tackle it (till the time the team adds a fix), I usually write a version number on the app bar 1.001, and before each instant reload I update that number say 1.002, 1.003...and so on. That's the last change before hitting instant reload.

All it does is I can make sure that the version I am testing is the latest version and there are no false assumptions

Maybe something like this can also be added as an inbuilt feature?

**Comment by OldFred2023** [comment]
I also noticed yesterday that the code in test/build/download is not the latest code.  I viewed to code of a page in FF and it was correct, i then downloaded the code, but the downloaded code was out of date and did not match the code of the current widget.

**Comment by albluwi1987** [comment]
+1

**Comment by Krystian95** [comment]
+1

**Comment by TimurKr** [comment]
+1, this has caused a lot of headache and wasted time...

**Comment by srh98** [comment]
+1

**Comment by vivekaion** [comment]
Same issue, please least porvide IDE for Windows, or Provide a Interface in Android Studio, so we can do task better.

this web based editing takes much hassel with this kind of error, me and my team facing same problem .

**Comment by aemelyanovff** [comment]
Unfortunately it's not something we can fix in the near future.

But the good news is that there's a workaround! After you start Test Mode, you can initiate Instant Reload by pressing Ctrl+Shift+i (Cmd+Shift+i on Mac) from the UI Builder. When you reload Test Mode this way it is guaranteed to use the latest version of the project.

**Comment by Krystian95** [comment]
Hi, I'm still experiencing the issue on Test Mode. I have to click (and wait) two times the "Instant Reload" button to see the changes.

**Comment by TheGeographer** [comment]
+1

**Comment by OldFred2023** [comment]
@hariprasadms @agreaves why has it been marked closed if it is still happening for users?  Even if you cant fix it you keep it open until you can, instead FF response read more like "yeah, we know there's an issues but we don't care that's it affecting users".

**Comment by eskim023** [comment]
+1
