### ISSUE TITLE
FloatingNavBar SelectedItem Color is not set properly.

### ISSUE THREAD

**Issue by nagoyan55** [FlutterFlow/flutterflow-issues#1246]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have two problems. And the first is critical.

1.Although the selected item color of floating nav bar is set to primary, it is not appeared in the test mode. Actually, its color is set to constant color(0x00000000). 
2. And also unselected item can't be seen with default color (but if you change the color, the problem is solved.)

### Expected Behavior

A selected item should be colored primary.

### Steps to Reproduce

1.Create two pages
2.Show navbar in each page.
3.In settings, change the navbar type to floating nav bar. (to show an selected item, you should change the color)
4.Run test mode or run mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goccC1c/IK8ZQhQIgQ0QnU7gnlO1ucx42B5yvELMhPvTCX0NKTteCf25HfGH++Hwxptbrifz9FMYBITKrbtl60JVAEzzKQnGgMqq4DpG3OHAkP59UI3GM4auJuBJRKbZuR3Bl3UODNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to use floating nav bar because this can be seen always unlike flutter default widget.
I inspect the project code and notice that the nav bar item is colored in below code. I would think the proper color is FlutterflowTheme.of.(context).primary not 0x00000000. And also FloatingNavbar.selectedItemColor is set to the same color.
Additionaly, why don't you use FloatingNavBarItem.title property? 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/57b00aa2-d8c4-4349-a43a-8e06461c63ba)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/9e48b559-dd3d-42c6-913e-b48fbcd53e36)

### Visual documentation

![スクリーンショット (19)](https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/ad52f092-5e85-48bd-8493-9b246cfe08d6)
![スクリーンショット (20)](https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/85a40cd1-5b2b-4b50-8431-92675110e667)
![スクリーンショット (21)](https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/cfbdb377-e465-4f78-bea6-6263f948f586)
![スクリーンショット (22)](https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/24845dfe-0461-4bd5-944d-a06d30f76cd9)

### Environment

```markdown
- FlutterFlow: v3.1
- Platform:Web
- Browser name and version:Chrome 115.0.5790.171(Official Build) (64bit)
```

**Comment by wenkaifan0720** [comment]
Hi @nagoyan55. This should be fixed in our next update. Thank you for reporting!

**Comment by lionking8600** [comment]
> Hi @nagoyan55. This should be fixed in our next update. Thank you for reporting!

Hi im facing a similar  issue, was this fixed or is it an error on my part?
ITFXz8jfz4pPxOZE0aXpLO1sjiEwGUAaU40V0t1ETRQbCIj4B4lzf8j4UFZoTfKzaHN+A2KIjT4d0/eKjeLlDcJfNk2bbIBZyod2YBPPbGOtVq6lCrqoZnFCDe9Yfki74Zi3oRVDANVYLy0N3WeEOOi9Yz6Cf9qOYwx5e6fDbOY=
![Screenshot 2024-10-21 140816](https://github.com/user-attachments/assets/703b4d66-145c-4e57-8744-204dae9497aa)
![Screenshot 2024-10-21 141034](https://github.com/user-attachments/assets/7ce36a1f-ffea-44b4-9a15-0656d898f89c)
 all i did was change the text color to a custom one.

Can you help.
