### ISSUE TITLE
Xcode cloud deployments failing 

### ISSUE THREAD

**Issue by philsegal** [FlutterFlow/flutterflow-issues#1247]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to build my project on Xcode cloud it fails. see https://community.flutterflow.io/troubleshooting/post/xcode-cloud-deployments-tjrHZWMGRQzQ8by?highlight=leodyskeMxJT7TK 

### Expected Behavior

some instructions, or better still out the box to compile and deploy on Xcode cloud. 

### Steps to Reproduce

1. Download source code. 
2. Update settings in Xcode
3. set up cloud workflow
4. commit a change/request a build

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhfHlx85Pm+EA0a6JY8dahmIvKWE7ap03lMNxeEwbCK7sELYPXPykP1doTcOiTFZYMFv8hmQd0P+MvdmeC+QHAE2VQKJ+1KlUazvhQT+WMrKyDpasfHRBP+FUNEuV58CngSJNAMBYLGQg3DmINuSAQXfDNbGzDlQ3Gf+bIt/Oo3ipAhm6Xn0Jg1ZSfCvr

### Context

Have to manually build, archive and upload the project

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16935168/914ac82d-b791-4880-a540-cce91f9619e8)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16935168/932f8e27-b7f3-4fc6-b2b0-55a20508ee22)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16935168/b0780428-0086-464d-820e-53b3934dd31e)

### Environment

```markdown
- FlutterFlow version: 1.1.93
- Platform: Mac (but on website)
- Browser name and version: latest safari
- Operating system and version affected: Mac 13.4.1 (but this is on the cloud)
```

**Comment by hariprasadms** [comment]
Hi @philsegal - We appreciate you bringing this up. I am able to confirm that the FF downloaded projects can successfully compile  and deploy using Xcode. You might be seeing an issue that is specific to your project. I would advise contacting the FF technical support team through the chat feature inside FF editor. You can come here to reopen the issue if the technical team confirm the issue. Thanks

**Comment by philsegal** [comment]
The project successfully compile and deploy using Xcode. but not the Xcode CLOUD deployment.

**Comment by kevintonb** [comment]
Hey @philsegal , you can also reach out to the support team via email through support@flutterflow.io. Hope this helps!
