### ISSUE TITLE
Icon for current location button in Google Map on iOS is not the standard one

### ISSUE THREAD

**Issue by infohdm** [FlutterFlow/flutterflow-issues#1249]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, apps created with FF using a Google Map component display a round target icon for the button that moves the map to the device's current location.
![fyH9TNLmLO6K9WcbjZlXC copy](https://github.com/FlutterFlow/flutterflow-issues/assets/109824924/0568aef6-1214-4943-a6b9-0c65418893b4)

### Expected Behavior

Use a triangle icon for this button to keep consistency with what Google Maps and Apple Maps use on iOS.

Apple Maps on iOS:
![IMG_0058](https://github.com/FlutterFlow/flutterflow-issues/assets/109824924/3a15a8ed-0cfb-4454-a136-78ba38eb5f61)

Google Maps on iOS:
![IMG_0057](https://github.com/FlutterFlow/flutterflow-issues/assets/109824924/46dea472-1954-421c-8b02-36b6e1053750)

### Steps to Reproduce

1. Create an app that uses a Google Map.
2. Push it to GitHub
3. Clone the repo to your local machine
4. open iOS simulator
5. flutter run
6. you will see that the button to "go to my current location" on the lower right corner of the map uses a circular target icon instead of a triangle.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elfLq25BOxPVA7c+JccAxgmAUJjsjaqxM0MJtZAw0GICsB6QAPOj+TGpuOLy8THxYB1qWim0dzMnIkeD+GsECaRyJbqJz+ZNubRXdeEKjRbKaBc2ROHZfN/5UGFSizpuZowklH/hfWVYc2kz3P+eUZDLAHoe2IWsnO+X/VaT4og+jGCP0Gn0Jg1ZSfCvr

### Context

I'm trying to build in FF the next version of an app that I previously developed using Objective-C.
This non-standard icon makes my app look strange to iOS users.

### Visual documentation

I already did above

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS
- Browser name and version: Chrome 115.0.5790.170 (Official Build) (arm64)
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment]
Hi @infohdm - This issue sounds more like a feature upgrade or request. Please use FF in-app feature request form (see below) which you can find under help section. This issue is _not a bug._

<img width="749" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/f3a70923-7e41-42e4-a999-4d84f484a8be">
