### ISSUE TITLE
Lottie Animation not working when put height in %

### ISSUE THREAD

**Issue by apc7788** [FlutterFlow/flutterflow-issues#125]
I have:
Scaffold > Container > Stack > Lottie Animation

When i try to set Lotiie Animation Widget height in % is not working, don't appears.

It works if i put in pixels.
I am trying to put Lottie Animation as a background, with 100% width and 100% height.

FlutterFlow version: v3.0 November 8, 2022 - Flutter 3.3.4
Workspace: Desktop google chrome navigator.
SO: Windows 10.

![image](https://user-images.githubusercontent.com/36442826/201793452-2ce6cebb-c9e0-4df0-98c9-8a9cc8e0d0e0.png)

**Comment by organicnz** [comment]
Hi @apc7788, could you pls add reproducible steps :)

**Comment by agreaves** [comment]
This will be fixed in the next release!
