### ISSUE TITLE
Launching Url not working on iOs

### ISSUE THREAD

**Issue by Saaamir** [FlutterFlow/flutterflow-issues#1250]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running my web application in safari, the launchUrl action does not execute after loading for a short period.

### Expected Behavior

When running my web application in e.g. Google Chrome, the launchUrl action launches the given url in a new tab.

### Steps to Reproduce

1. Create a button
2. Create API call that returns example url (https://...)
3. Define API call action on button
4. If API call -> succeeded, launch the received URL

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48k/Lqx8pgodtY0LX1bfow9SksJn07U5E/08F9Y0w8KOPdOoYUP8+kM0RvTtCrT3xUJU60q2oW0/TlhuHpKvdfZUiqba5cz5FxWzriQk6VVbaNFJWgPXxBINNgI0CP5rew2BF7OuxsWnw77XGEGuu9UgXvNoDJNlQWDq/LZO4=

### Context

My api returns a custom checkout link when the button is pressed. Therefore I am fetching that url, then trying to launch the checkout page using the link in a new tab.

### Visual documentation

![actionSetup](https://github.com/FlutterFlow/flutterflow-issues/assets/69773163/9c10d356-55aa-4bcc-b84c-b336152e8530)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: web
- Browser name and version: Google Chrome, version 115.0.5790.171
- Operating system and version affected: iOs 16.5.1 (Safari)
```

**Comment by hariprasadms** [comment]
Hi @Saaamir - Thanks for submitting the issue. I can confirm that launch URL action is working as expected on both chrome and Safari browsers. In safari browser, you might have popup blocker is on. Disable the the blocker and see how it works. Thanks

**Comment by Saaamir** [comment]
Solved this by calling the Url before and then launching the url without waiting for the api call. This leads to the browser not picking it up as a popup anymore!

**Comment by WhiteGamer23** [comment]
@Saaamir Can you show me the action block? I have the same problem. Thanks

**Comment by Saaamir** [comment]
@WhiteGamer23 Its pretty simple. I make the api call onPageLoad() and when the user clicks the button I launch() the link that I saved in a state before.

The only part you need to look out for is that you are getting the link before the user wants to launch the website as the launch has to happen instantly to not be mistaken for a popup.
