### ISSUE TITLE
Uncaught Error: setState() called after dispose()

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#1251]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Seems like it doesnt affect anything in behaviour but the error appears en chrome debug console. The problem seems related 

### Expected Behavior

No error should appear in debug console

### Steps to Reproduce

PROJECT:
1. make a new project with 2 pages (home, child)
2. inside home, make a button (go to child)
3. the child page should have back button in appbar
4. in child create a form validation with a field (for numbers/digits only) and a button for sumbit
5. the submit button should validate and after that must navigate back

TEST:
1. run the test project
6. click "go to child"
7. write a number like "10" in the text field
8. click "submit simulation"
9. The error appears in console (it is weird, sometimes it doesnt appear)
10. Sometimes it appears when i click "<- back button"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89godtJ15CBYO9VnicRQkA5aJc0sdlud0wdCoDuBIk+ZPWlVFpBTsSoTVFfMESmmngDpejThd/tJMBcCyucb7Za+JZ2Tg7gbHKWa5OBEriSOnNCEdpbfxWA5MPY3whdCPViZXwe3UyLfeuiQj7vK7H7IndISq/LZO4=

### Context

I dont know if this error will affect the production app. So i want to avoid any surprise.

### Visual documentation

before click submit (or back)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/27a547ee-a0af-460f-bb4e-22e222bbe65d)

after click 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/791b474d-8ac6-4fff-a594-aa85c32ac1a1)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: chrome 115.0.5790.171
- Operating system and version affected: windows 11
```

**Comment by OldFred2023** [comment]
I have also experienced the same issue, and would like to see it fixed, or at least caught.

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for highlighting this observations. We are aware about it. We advise ignoring this error right now because it is not affecting any functionality. Thanks

**Comment by sirian-m** [comment]
@hariprasadms We are facing this error as well, and while it's not per se affecting functionality right now, it is pretty significantly impacting performance in our app. This most apparent on lists with custom user card components for example, and those user cards contain multiple other components as well. When loading a page with such a list, there is a pretty significant lag. It hangs for a second (or more) in a half loaded state before continueing.
