### ISSUE TITLE
Having Phone Sign in as an action prevent all Nav actions, despite being in other conditional branches

### ISSUE THREAD

**Issue by saadullahkhankhail** [FlutterFlow/flutterflow-issues#1254]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Phone_Signin is followed by True condition outcome, and Page Navigation is followed by False condition outcome.
    But the Error is given that "Don't navigate when doing phone sign in".
    Even that Phone_signin and Page navigation are in different paths of Single_Condition.
    They don't cross each other paths.
  
  I will be pleased to have this fixed, thanks in advance!
  
  💙FlutterFlow

### Expected Behavior

Page Navigation and Phone Sign in on different true and false paths of condition shouldn't be a problem.

### Steps to Reproduce

1. Create any single condition statement.
2. On True condition path set Phone_Signin.
3. On False condition path set Page Navigation.
4. Click Run
5. Observe that project doesn't build
![WrongErrorFF](https://github.com/FlutterFlow/flutterflow-issues/assets/131300774/2c79af8d-5b80-4b5c-bbe6-d00ae9f003f9)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ejMmBx89goctF7r6JdMExmiUvMjsjbJIzjtV+cAwYG4+vBKQIe+jxP2FoUtfiTAk7L06Kinge7tXIkuDqA+UoAwSZG75xyM52aQvLfGqhVqasPJOJe2tfO9NJJVyMyJ+4nhJDCOppWF1m2V66GOfLcBHDCYTbOEceR/6IDL/Do3epQ0SLb3kNh1JWeC/v

### Context

I want to put a condition when phone number doesn't exist in database navigate to signup page, if it exists sign in using phone number.

### Visual documentation

![WrongErrorFF](https://github.com/FlutterFlow/flutterflow-issues/assets/131300774/bd0475a8-418d-4120-ac1e-3d9ced2c92a1)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: https://app.flutterflow.io/project/
- Browser name and version: Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by saadullahkhankhail** [comment]
Is this a right place to post an issue?

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This bug has been fixed and will be reflected in the next deploy.
