### ISSUE TITLE
The app made in run mode does not look the same on shows a different front page

### ISSUE THREAD

**Issue by robertjonesbanks** [FlutterFlow/flutterflow-issues#1255]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have made a demo app.
When you run it the Login page does not show bottom Nav Bar
Also in run mode it shows a page that does not exist!
Can this be sort out please

### Expected Behavior

In run mode the Login page should have bottom Nav Bar.
Then when it goes back to Login page it should be login page not some other page

### Steps to Reproduce

make page
do login page
do nav bar at bottom listing main pages for the user
this should then apper in run mode
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/44586429/3440cf46-17cf-41cd-91c0-348e913f0b5e)
instead you get this
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/44586429/886e36d7-db55-42c6-b3d7-2de7d10255c1)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olOflzItItbxY+Krqb8ExhSQUNlw4R40rkcpOGDoaB5jdB4YMac78TBNWOe2jdFZ5KEWImkEJ7srzv/P1MfcVHE2qY6JIwqhQUDrzeEW/aoTQPaW0OHxCP/tRC0iF0KeJ2iJ7OsduV3dhwGGIHPOAaAvZK5v6Zwh9f6PHaOI=

### Context

I am trying to demo a product
This should be easy to do....

### Visual documentation

make page
do login page
do nav bar at bottom listing main pages for the user
this should then apper in run mode
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/44586429/3440cf46-17cf-41cd-91c0-348e913f0b5e)
instead you get this
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/44586429/886e36d7-db55-42c6-b3d7-2de7d10255c1)

### Additional Info

This should work as said.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:pc
- Browser name and version:brave
- Operating system and version affected: win10
```

**Comment by hariprasadms** [comment]
Hi @robertjonesbanks - Thanks for submitting the issue. I can confirm that this is an issue related to demo app. In general, the above features working fine.
