### ISSUE TITLE
App Bar Responsive visibility broken in UI builder

### ISSUE THREAD

**Issue by jerperdue** [FlutterFlow/flutterflow-issues#1256]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I setup responsive visibility for the App Bar:
![Screenshot 2023-08-12 at 11 58 36 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/0b83a8bc-aded-43e7-b970-135fdc2ed382)

Mobile size displays the App Bar as expected:
![Screenshot 2023-08-12 at 11 58 14 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/5c037bfa-0405-44d5-a226-a9838e912777)

Desktop size also shows the App Bar (not as expected):
![Screenshot 2023-08-12 at 11 57 54 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/054ec005-7be1-406b-9f35-2f903f474309)

### Expected Behavior

Desktop view should not display the App Bar, when responsive visibility is setup.

### Steps to Reproduce

Create page with app bar

Set responsive visibility to not display app bar on a desktop

Change between mobile and desktop views in the UI builder.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz8mB35VNvs9G1aqNKe9ViicWMjt8UOc3l8J9YCs8GZT0B4kcYs+kfklUcMCoTUFDfGeWmmIX/Mr0voXLVMdfIRGqbLpGzc1tWwvvVlmtVLqPCa63b3NDI+BhN36a15iZpyVTBO9uZXA5wDm6Pd+Qfz/AH4zLPmsvReaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Makes it confusing to build when UI displays when it shouldn't

### Visual documentation

Screenshots above

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: Ventura 13.5 (22G74)
```

**Comment by hariprasadms** [comment]
Hi @jerperdue - We appreciate you bringing this up. I can confirm that there is no issue and that everything is working as intended.  Responsiveness can be seen in action when you deploy the app (in Run, Debug, or web deploy mode and real devices). Inside FF editor, responsiveness settings does not work as its implementation is not triggered inside the app. I hope this explanations helps you. Thanks
