### ISSUE TITLE
Unable to enable Push Notifications on Spark Plan

### ISSUE THREAD

**Issue by danysz** [FlutterFlow/flutterflow-issues#1258]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello

When I try to "deploy" Push Notifications it returns an error "Error: Your Firebase project must be on the Blaze plan in order to deploy
functions. Please upgrade your plan and try deploying again."

Why do I need the "Functions" to send push notifications ?

I have my own server and sending push notifications is available also on Spark Plan.

Thanks

Daniel

### Expected Behavior

Enable push notifications just to make the push notifications to work.

### Steps to Reproduce

1. Enable "Push Notifications"
2. Deploy 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8jfz5V2pbxA0L6JcvlalSQ7OUM2R+YRjcpBZywgfZzzBLN/fPfQP1FoTc+4TFZtelmmp14D7vToiITDMvZdJQyub4A5wc9iEAvMXmOiM7mTF7qsZnBPM+dPf2HD1Ku3gRYlXfdZLnATwDiMJeu9cBDaJr31OkQ8Sq/LZO4=

### Context

Enable the push notifications.

### Visual documentation

<img width="1054" alt="Screenshot 2023-08-13 at 21 28 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1667904/3976bbe8-5d18-4fd8-93a5-12a2dc873ca7">

### Environment

```markdown
- FlutterFlow version: Version 1.1.96 (1.1.96)
- Platform: MacOS
- Browser name and version: n/r - local installation
- Operating system and version affected: All (android and iOS)
```

**Comment by hariprasadms** [comment]
Hi @danysz - The message what your are seeing is as expected. Push notification requests go through the function calls. Hence your firebase projects should be in Blaze plan.
