### ISSUE TITLE
Custom component, action media upload, Uploaded File URL disabled (on ImagePath)

### ISSUE THREAD

**Issue by milosPavic** [FlutterFlow/flutterflow-issues#1263]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i dynamically create children, and i create there component from stack with two images, first image is place holder second one is network image. When i  use that component as action triger to upload media to firebase i cant get Uploaded File URL in AppState variable or in Database Document Update.
When i make same dynamically created children with regular image, and add action on it i can get Uploaded File URL.

So depends does dynamically created children is image or component i can or cant get File Uploaded URL, after i upload image to the firebase.

![image (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/7430264/dc44a150-e116-4d75-89c1-7000752d9380)

### Expected Behavior

When i create action on component Upload Media, after that i need to have "enabled" Uploaded File URL to put in variable who has type Image Path.

### Steps to Reproduce

1. Create new project
2. Create new collection
3. Create images as list in news collection
4. Create image type with title as String and path as Image Path
5. Add some items in news collection
6. Select one item in news collection add image type there
7. Generate dynamically children from news.images in Column
8. Call that as genImage
9. Create new component put image in component, component have Stack + two images in, and path propety as ImagePath
10. Use that component to show you image in dynamically generated children
11. Add action to that component
12. Action is Upload Media
13. After medi upload try to update genImage.paht with Uploaded File URL (it is disabled like two different types)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oifH634VIsctb1s7uY8dFiSQRNlx/R4JI18pBazwbfe+uB4kqevfOTERBZ7TnS29beWCJq2oW0tXIhuHuG/FeAzabba5IybhcdjuUUlqmb6nTFJWgVUZQAf5MGmrH08Gn2hImAPVeW39m2GaEeu+RF3TdGJDvDTIgDq/LZO4=

### Context

I wish to make image placeholder component add action on it, upload media to firebase and save Uploaded File URL in variable

### Visual documentation

Here is the video as We transfer link it works for a week from now.
[video](https://we.tl/t-FoHvSwrxdD)

### Additional Info

![image (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/7430264/57e2b338-b192-45b6-8e71-5fa2fc427a26)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Windows
- Browser name and version:Google Chrome 115.0.5790.171
- Operating system and version affected: Windows 10
```

**Comment by agreaves** [comment]
Hi @milosPavic, thank you for the bug report! I believe this should be fixed now (at least it was in the bug report project). Please let me know and once confirmed (or if it's been a while) I will close the issue. Thanks!

**Comment by agreaves** [comment]
Closing as the original issue appears to be fixed!
