### ISSUE TITLE
SliverAppBar does not smoothly animate from image to appbar background, but instant

### ISSUE THREAD

**Issue by Torkilws** [FlutterFlow/flutterflow-issues#1264]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The appbar with image background instantly switches from the image to the appback color background. Like this:
https://gyazo.com/4141920769f24becef652d09efa69eb4

### Expected Behavior

The image smoothly animates from the background image to the appbar background color. Like shown in the docs:
https://docs.flutterflow.io/widgets-and-components/widgets/page-elements/appbar#adding-sliverappbar:~:text=Here%27s%20how%20it%20looks%3A

### Steps to Reproduce

1. Create a new page
2. Add a appbar, Sliverappbar enabled and using Flexible space. With expanded height, ex 200
3. Add background widget to appbar with image
4. Add a listview/column with lots of elements
5. Start test mode and see the issue 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15776477/5587c71c-dea7-4b48-9f99-90fd6a8e0f29)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15776477/e1006072-68f3-4948-a640-99cdbf540186)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlMmA5c9goblH0LnqcMdqhQIgQ0QnU7gnlO1ucx4jfZPpPOwyPM7SZUNKTd+9T1FiEWCjpGIyw97Lks7lLfZdAw+uRqk/0JVPWw3hRkeXRLKXEc2oSnJAJ+xRfUye36azpxYkA7ZfLWQt62GHNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I won't use this appbar feature before it is works as expected, because it does currently not look good with current behaviour.

### Visual documentation

In my app:
https://gyazo.com/c430d6ea428582f47d417f8b9759481b

Made a new page to test:
https://gyazo.com/4141920769f24becef652d09efa69eb4

### Environment

```markdown
- FlutterFlow version: v3.1 (August 11.)
- Platform: Windows (browser)
- Browser name and version: Chrome Version 115.0.5790.171 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by Torkilws** [comment]
I'm waiting for this bug to be fixed before releasing my app, any ETA?

**Comment by dobleuxyz** [comment]
Also waiting on this one to get fixed. I am, for now, avoiding to use this feature because it looks bad but one of the most important pages of my app is designed to use the SliverAppBar.

**Comment by Torkilws** [comment]
This is now the only thing missing before I will publicly release my app. Is anyone working on this? 😅

**Comment by sbis04** [comment]
It looks like the issue is not coming from FlutterFlow's implementation rather from Flutter's current version we are using (as per this [issue thread](https://github.com/flutter/flutter/issues/128636)). Seems like the latest version of Flutter (3.13.1) fixes the issue. But I think we would need a longer timeframe to update FlutterFlow to that version (since this version could contain some breaking changes which we'll also need to address).

https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/c622b723-2c2e-45d8-8723-9dde49296e67

**Comment by Torkilws** [comment]
Okay I see. So you are probable talking about months in the future, or?

**Comment by sbis04** [comment]
Hi @Torkilws, this should be fixed in the next update!

**Comment by Torkilws** [comment]
Fantastic!

**Comment by dobleuxyz** [comment]
Woohoo

**Comment by Torkilws** [comment]
@sbis04 do you have an estimate when this update drop?
