### ISSUE TITLE
App freezes on Facebook sign-in, android version 11

### ISSUE THREAD

**Issue by FaizanAhmad127** [FlutterFlow/flutterflow-issues#1265]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Note: the app works fine with android version 13 but freezes on cell phones with verison 11.

When tapping on facebook button which has facebook login action, it lead me to webview where it shows me a "Continue" button as I am already logged in to my facebook. Upon tapping on continue it take 4-5 seconds and come back to login screen which i made and then the app freezes. By freezes i mean it still shows the Login UI but i wasn't able to tap anywhere.

### Expected Behavior

The app should seamlessly sign-in using Facebook sign-in on android version 11.

### Steps to Reproduce

For facebook setup, i exactly followed the docs: https://docs.flutterflow.io/data-and-backend/firebase/authentication/facebook-sign-in

1. Create a login page and add a button for facebook login.
2. Select that button and go to actions, in actions go to backend/firebase, then firebase authentication, then selected login.
3. Then choose facebook as an auth provider.
4. Choose create users document.
5. Then create another action, in which check whether the user is logged in or not, if yes then navigate to home screen.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMrlz4ZJpbxY17X5bcZFr2IsC2IjTL03pu0bFEggGLbrBIYMacmkM1JvOc+mdFVLKEWLhj4y0Nrrj9rhA8BeAxCbbaE6yYdQUDvifHK/aoSLDIe8VkclHfNQfRGF0quJvBInFLJqLy0C2l+qAO+tTjbXQb36Zwh9f6PHaOI=

### Context

I am not able to login using Facebook.

### Visual documentation

Attaching a video of testing on android version 11 and also 13. The video with freeze issue is of version 11.

videos link: https://we.tl/t-Situv6y8yo

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Android
- Browser name and version: Chrome Version 114.0.5735.198
- Operating system and version affected: Mac OS Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @FaizanAhmad127 - I appreciate you bringing this up. We do investigate any fixes surrounding most recent device OS versions given that the most stable Android version is 13 and up. We do not currently plan to support compatibility issues with older versions.

**Comment by FaizanAhmad127** [comment]
Do you mean that this issue is not gonna resolve anytime in future?

**Comment by jeanlouisliaud** [comment]
Hi community ! Same error here ✋

**Comment by jeanlouisliaud** [comment]
Hello @hariprasadms ! How are you ? 

I face the same error than @FaizanAhmad127. 
I tested on Android v10 and i got the freeze screen. 
I tested it on Android v13, and it works fine. I tested on IOS, and it works fine.

Is there any way of solving this problem on Android ? 

Best regards,
