### ISSUE TITLE
Group API variables can't be used in headers (test mode web and android)

### ISSUE THREAD

**Issue by TeferiHero** [FlutterFlow/flutterflow-issues#1266]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use API group variable placeholders ( [variable_name] )  in group headers:
- In Test&Response the placeholders are correctly substituted
- In test and run modes on web and on Android the placeholders are left unchanged

### Expected Behavior

The group headers should substitute placeholders on all devices in all modes

### Steps to Reproduce

Diagnosing with dev tools
1. Create a new API group with a variable and a header with that variable value (e.g. String "testVar", header: "test: [testVar]"). 
2. Create an API call within that group.
3. Create a button that activates the API call, with testVar set to e.g. "one"
4. Run the program in test mode or run mode.
5. Open dev tools Network Console.
6. Click on the button to activate API call
7. See in the Network console that the request header has a header "test" with value "[testVar]"

Diagnosing without dev tools
1. Create a new API group with a variable and a header with that variable value (e.g. String "testVar", header: "test: [testVar]"). Set the base URL to: https://postman-echo.com (to return request headers, arguments)
2. Create an API call within that group. Full URL should be: https://postman-echo.com/get
4. Create a new page with a variable for displaying API results.
5. Create a text that displays the page variable
6. Create a button. Add to it an action that executes the API call, and sets the page variable as the API call result
7. Run on web or download APK
8. Click on the button.
9. See the returned JSON has the field "headers", whish in turn has a field "test" with the value "[testVar]"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TkcjfsM5PtbxY17rTbcdviikUJkwma5IolutudwIdDOvnO4l3es7sT3FJXMu4d2xUJGH8sGAIpuDRuN7+V8AoC0iIQ75Hzs8JdT3KbD6WaJeYDM60Pn9tP/1MfmqF35qOiiRQWcBZWHgbwV77Oui8dHbaJbrMDTERI8j9DJj4j17hHjLREThQtmNecCfn

### Context

When trying to use the same header for many API calls I found I was unable to do so. The same placeholder was sent each time.

### Visual documentation

The API group and API call
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/20aee7d8-592c-4fcb-adac-ae597c9ec95f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/8c35a69e-c207-4b81-809b-b00b0c4bdfca)

The API Test&Response call (correct response)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/22b69f52-a21d-4524-9916-048332547e0e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/fafd079e-71f3-4b6c-a35e-a61091aa7b2e)

The test mode call (incorrect response)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/7de48f4e-9824-485a-aa3a-56d9034b0a32)
![Screenshot (134)](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/f881a660-1b8a-4b2c-b93c-cb0bc62e2e22)

### Environment

```markdown
- FlutterFlow version: 
- Platform: Web, Android
- Browser name and version: Microsoft Edge 115.0.1901.203 , Firefox 116.0.2 
- Operating system and version: Windows 10
```

**Comment by antran22** [comment]
I also encountered this issue. The issue can be seen clearly in the generated Dart code in `backend/api_request/api_calls.dart`

```dart
class APIGroup {
  static String baseUrl = 'https://example.com';
  static Map<String, String> headers = {
    'Authorization': 'Bearer [accessToken]',
  };
  static APICall apiCall = APICall();
}
// ... more codes

class APICall {
  Future<ApiCallResponse> call({
    String? accessToken = '',
  }) {
    return ApiManager.instance.makeApiCall(
      callName: 'APICall',
      apiUrl: 'https://example.com',
      callType: ApiCallType.POST,
      headers: {
        ...APICall.headers, // problematic line
      },
      params: {},
      body: body,
      bodyType: BodyType.JSON,
      returnBody: true,
      encodeBodyUtf8: false,
      decodeUtf8: false,
      cache: false,
    );
  }
}
```

The header is passed into the API Call without any string interpolation for `accessToken`.

**Comment by hariprasadms** [comment]
Hi @TeferiHero - Thanks for submitting the issue. The group variables can't be used in the api group header. This is as per design. Thanks

**Comment by TeferiHero** [comment]
Hello @hariprasadms - So the fact that they are used in Test&Response must be a bug, right?
Also, does that mean [the response to this issue](https://github.com/FlutterFlow/flutterflow-issues/issues/229) is no longer valid?
![Web capture_15-8-2023_7249_github com](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/51cffd13-1af9-491b-a395-29e1ee82672b)
