### ISSUE TITLE
Horizontal scrollbar is not visible in flutterflow

### ISSUE THREAD

**Issue by ArthDKS** [FlutterFlow/flutterflow-issues#1267]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm having issues with the development of a web system.

I have a data table with several columns, and I'm using the datatable widget to create the table. The table has 28 columns, and it becomes complicated to display all the data on the screen without enabling horizontal scrolling.

Once I enable it, I'm unable to see the horizontal scroll bar. I can only see the vertical scroll bar. To scroll horizontally, I have to use the trackpad of my MacBook. With a simple mouse, I have to hold the cursor and drag.

In any web system, when something is wider than the total width of the screen, a horizontal scroll bar is necessary.

### Expected Behavior

I need the horizontal scroll bar to be visible.
![Captura de Tela 2023-08-14 às 16 23 47](https://github.com/FlutterFlow/flutterflow-issues/assets/111399626/b7ab67e6-166f-44f3-9462-0e80bb566d6e)

### Steps to Reproduce

enable horizontal scroll bar visibility

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oi/GAvYtPxeFK0Lrube9VgjgWHG4naqxN0cFxaEgaIYvNG7UUZ8nRQHdVXc+hdG03M1qZ+T4fwNaKvszIN8EpHAWeGpxFybpMZgyUXkSnRrKrDsyWQ0FCPNpKC2Km16e7iCN/LrBecngE6k+uGuiXEnXYHZv1ImwFIOaXC9jMs3PuQ0SLb3kNh1JWeC/v

### Context

I have a project stopped because of this problem

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111399626/daf9a110-01e3-4911-b230-0cbd07f72c31)

### Environment

```markdown
- FlutterFlow version: V1.1.96
- Platform:WEB
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by hariprasadms** [comment]
Hi @ArthDKS - Thanks for posting the issue. Looking at the expected behaviour it more sounds like feature requests/enhancements. I would suggest use feature request form available under help section to raise this requirement as a feature request. 

This form is available under help section. 

<img width="749" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/92d11f49-9779-44cc-bdce-a0778e256445">

**Comment by asmengistu** [comment]
Hi @ArthDKS - we actually just recently launched a feature that covers this problem your facing.

Check out the "Scrollbar Theme" section under your Theme Settings > Design System. You can make the scrollbar always visible and customize the heck out of it :)

**Comment by ArthDKS** [comment]
Good afternoon!

@asmengistu I know it was released, but did you manage to enable it for horizontal?

Here it only works vertically.

There is no horizontal scrollbar in flutterflow.

**Comment by jmart72** [comment]
Has this been implemented??

**Comment by ArthDKS** [comment]
> Isso foi implementado??

Natively, up to the present moment, it's not possible!

**Comment by bryanmmc16** [comment]
Is there any possibility of implementing a feature for this? I had requested it because I have the same issue when scrolling through data tables or elements in scrollable rows.
