### ISSUE TITLE
Failing to successfully deploy firebase rules

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#127]
## Expected behavior (required)
Failing to successfully deploy firebase rules

## Current behavior (required)
Error message toast: 
It looks like you haven't used Cloud Firestore in this project before. 
Go to https://console.firebase.google.com/project/palmdesk-c1935/firestore 
to create your Cloud Firestore database.

## To Reproduce (required)

Environment
Window 10
crome brower
my login: info@palmdesk.com

created firestore project
added firebase@flutterflow.io as editor
created firestore database

FlutterFlow
create project
settings
enter project ID 
add
regenerate Config files
firebase setup completed

FlutterFlow
Firestore
Settings
Collection selected

Firebase schema validation
Validation status Successful

Firestore Rules
Click Deploy

Error message toast: 
It looks like you haven't used Cloud Firestore in this project before. 
Go to https://console.firebase.google.com/project/palmdesk-c1935/firestore 
to create your Cloud Firestore database.

/// I have already created the Cloud Firestore database. Why am I getting this message?

## Context (required)

I am trying to integrate the Firestore database with flutterflow project.

## Screenshots / recordings

toast is for very short duration. Difficult to take screenshot. 

## Your environment
Window 10
chrome browser

**Comment by palmdeskApp** [comment]
I tried 3 grounds-up attempts, and all 3 times I got this same error. Since I can no longer "deploy" the firebase database within flutterFlow, I might have to quit Flutterflow permanently.

**Comment by hariprasadms** [comment]
Hi @palmdeskApp - Sorry for the late reply on this. Is this issue still persisting for you ? Please confirm. As we see most of the user projects are working fine, sometime this kind issues are specific to projects. Please confirm.

**Comment by palmdeskApp** [comment]
I am no more facing this issue. I don't know how it got fixed. I did nothing different.
