### ISSUE TITLE
Supabase inserts only accepting NULL value when from constant, (PRIMARY KEY IS REQUIRED FIELD)

### ISSUE THREAD

**Issue by NLDylan** [FlutterFlow/flutterflow-issues#1270]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When inserting something to supabase in FF you are currently forced to insert something in the ID (primary key) field.
In my case, my ID field needed to be empty because I generate a custom UUID based on a safe URL pattern.
Since I could not ignore the ID field and it cannot be empty I had to search for a solution.
What I could not do is:
- Writing an empty string
- Writing NULL myself

### Expected Behavior

That there should be no difference between me writing NULL in the ID field then Flutterflow writing NULL in the id field.
My current solution is to go to constants -> select the NULL field from Flutterflow.

Also, I feel like the primary key from a table should not be required like this. I had to search multiple hours to finally find a solution on the community forums. If the ID field is left empty or not filled in then default to NULL value.

### Steps to Reproduce

1. add supabase to project
2. create random table with id, and some columns and make the id primary key
3. try to insert in to that table via FF form and leave out the ID field.
Currently you get an error. and if you type NULL this is not accepted.
4. Accepted is if you go to constants and select the NULL value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CzcmAsIZgod9Y15PqdcBsgSQRQ1wmRYIrjOwaSU4bHZPOD7AQP8nRP1dUOc+nTFViImCgnj4X/Mrtj879NPA7CAqWG9lC1rlyZwyXeHqWVZeVPIS3b3Z7P8Nmf2Kh54mrpBNCNfVpdUJn2V+pNei/ShHrHu76OWovPOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

Started to create custom functions for my inserts and after a few hours I stumbled on a post on the community forums.

### Visual documentation

Uncaught (in promise) Error: PostgrestException(message: User defined key value Null has invalid length. Expected 11, got 4., code: P0001, details: , hint: null) 

Null, null or NULL is not null? but Flutterflow NULL is Nul?

The error is not related to Flutterflow but is the response to why its failing since my ID Keys is 11 charcs long.

### Environment

```markdown
- FlutterFlow version: v3.1 Flutter 3.10.4
- Platform: web
- Browser name and version: 115.0.5790.170
- Operating system and version affected: Ubuntu 22.04
```

**Comment by hariprasadms** [comment]
Hi @NLDylan - Thanks for submitting this information. By looking the nature of expectation what you are explaining in the issue, it more sounds like features or enhancements around existing functionality. In this case, I would suggest user FF in app feature request form to request this enhancements. You can find the feedback and feature request form under help menu. Thanks

Here is the form. 

<img width="749" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/80feb8bd-2d94-46ba-88e2-e9d4495b6ab0">
