### ISSUE TITLE
white screen after building and when excute windows.exe 

### ISSUE THREAD

**Issue by bediimed** [FlutterFlow/flutterflow-issues#1274]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

after building windows.exe file display white screen and always is freez in white screen and never get home page  

### Expected Behavior

must to show home page or login page but always get white screen and application does nothing 

### Steps to Reproduce

click excute windows.exe display white acreen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

id building issue

### Context

its impossible to display content of aplication as windows.exe

### Visual documentation

i dont have image

### Additional Info

nothnig to display

### Environment

```markdown
- FlutterFlow version: 
- Platform: desktop
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @bediimed - The issue is not clear and not sure whats is about windows.exe. Please update the issue with reproducible details and required videos / images.
