### ISSUE TITLE
Variable not valid when mapping list items from a query

### ISSUE THREAD

**Issue by FrancoSernaglia** [FlutterFlow/flutterflow-issues#1275]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't map the references of a list of users from a Query Action. "Current variable not valid"

### Expected Behavior

To get the list of references from the list of users

### Steps to Reproduce

1.Create a collection with users
2.Query de collection from an action 
3.Get the action output and try to map their reference 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okvLlx85grs9G1s/AacFvryQQKVgkR78ricpOEDIgfePrBu0iOvTBfktvUtDiaVNcH1SGoEQD//OLjdjXU8BePRWbQN1T+pZ2Tg/0e2iVbJCIO8y0OXNSEdtjIGrD0bW3myJ7IrBsWXw76k+HN/OWbDDDIuu/Zwh9f6PHaOI=

### Context

I want to trigger a notification with the receivers being certain users of the users collection. Therefore, I query the collection and map their references but the variable is not valid

### Visual documentation

<img width="525" alt="Captura de pantalla 2023-08-15 210729" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/70101e84-a601-4f3d-8e8a-7e06127ca91a">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by FrancoSernaglia** [comment]
before I editted the action tree I was able to Map the users references. Thats why my concern. Map list items doesnt return a list ?

**Comment by FrancoSernaglia** [comment]
now it works:
<img width="365" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/6bdb5e57-3f8a-4137-9fa3-7c6b505e1468">
I changed the receiver to Unique and then back to multiple receivers. It help unbug the situation. Please consider this as a bug.
@hariprasadms @wenkaifan0720

**Comment by xenomorph78** [comment]
This IS A BUG. Existing code with calls to the list of user references will not allow you to map back to those references and will give an error that previously worked. This forces you to delete the action and rebuild it to make it work. So, unless you already have a user reference action to test on, building it will not reproduce this issue, but it clearly is a bug for existing actions.
![Screenshot 2023-11-11 at 9 53 09 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/74033405/6752db19-ac28-40fe-81e3-3539c98d0da9)
