### ISSUE TITLE
Apple Sign In (Web Bug)

### ISSUE THREAD

**Issue by dev-vick05** [FlutterFlow/flutterflow-issues#1276]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've been trying to set up Apple Sign In through web by following the documentation provided and through article provided by Danny from Flutterflow support. The Sign In button works as expected up until redirection back to the original website where "error=invalid_client" pops out. I shared the error screenshot to Danny and he confirmed this is a bug and requested me to report the issue here.

### Expected Behavior

A seamless sign in using users apple credentials.

### Steps to Reproduce

1. Add Sign In with Apple button
2. Follows the steps provided by Flutterflow documentation, Firebase and Apple.
3. Failed to Sign In

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

As shown in the screenshot attached

### Context

Sign In with Apple (Web)

### Visual documentation

![error_details](https://github.com/FlutterFlow/flutterflow-issues/assets/109755423/5598df07-92f1-4064-a7cb-359355cc7bb6)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 115.0.5790.173
- Operating system and version affected: All browser type. (Chrome, Safari & Mozilla)
```

**Comment by agreaves** [comment]
Hi @dev-vick05, thank you for the bug report and apologies for the confusion. Unfortunately, Apple Sign In is only supported for iOS at the moment. I realize this is not properly documented in the documentation, so we will add this. Apologies again for the confusion and thank you for the report.

**Comment by nicbyron** [comment]
@agreaves what happens if we offer both native (iOS) and web-based apps for the same service and someone signs up with Apple on iOS and then tries to authenticate via the web (or an Android device)? What options do we have to offer them?

**Comment by tensoralex** [comment]
I would like to add, that in fact it works separately for Web and for IOS depending on what identifier is specified in  the FIrebase Apple provider authentication configuration: "Services ID (not required for Apple)".
If Apple "APP ID" is specified - then it authenticates successfully on IOS,
if Apple "Service ID" (for sign-in with Apple) is specified - then it works on Web (but does not work on IOS).

So clearly it is possible to achieve or have some workaround to pass the right client_id during apple auth on Web.
