### ISSUE TITLE
FAB visibility option is no longer available

### ISSUE THREAD

**Issue by minashawky** [FlutterFlow/flutterflow-issues#1277]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently if you're adding an FAB I cannot see on the options panel the ability to set the visibility of the FAB. Previously it used to exist

### Expected Behavior

Hide and show the FAB

### Steps to Reproduce

1. Create a new page
2. Add an FAB
3. Previously the option to set the visibility of the FAB existed now it is removed

Note: I'm attaching an image of my previous FAB that I had set visibility for

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejM/f8c5PtbxC+pPTLMFshQM9JFA8a+c70u5+FBYoGJSuP4l/evz4UBJoTbyndkFiM0yGknkz3PDPm9z1N8cCBw2ZG4BDyZBiawzyXjqVRbaSC6qVdXR+GshRG2aa4Ji72BZ/Ou9pLVpn62WIF/CQbAzvJbrQIVc/AM6ZJr/XrgfuQ0SLb3kNh1JWeC/v

### Context

On my app homescreen I handle multiple different user roles. A Coach role should not see the FAB while a Client role should be able to see the FAB

### Visual documentation

<img width="221" alt="Screenshot 2023-08-16 at 11 33 37 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/0d3244fe-a46e-4620-83ef-3f542e8a1d92">
<img width="236" alt="Screenshot 2023-08-16 at 11 34 05 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/7b96d8fc-4c7c-4b50-abcc-321369d4b0a4">

### Environment

```markdown
- FlutterFlow version: v3.1 (released Aug 16, 2023)
- Platform: Web
- Browser name and version: Chrome Version 115.0.5790.170 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by aemelyanovff** [comment]
@minashawky Thanks for reporting the issue. It was fixed in the last update.
