### ISSUE TITLE
AppBar conditional visibility

### ISSUE THREAD

**Issue by Lozovytskyi-R** [FlutterFlow/flutterflow-issues#1278]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The conditional visibility of the AppBar is dissapeared. There is no conditional visibility in AppBar properties.

### Expected Behavior

AppBar properties has conditional visibility

### Steps to Reproduce

1. Create AppBar

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OiMjfsJVIrsdc1qrubMdKgSQvHHI5baxM0cFTY04aF5/NG4gIZfTBXE9uOP25dghbfWCJkj0dzMnHm9z1G8YnBw+bbaZ5/7pcFBbiYF2gaa6PEc+SQ0RUGshhJ27A0qarughDHPFvSUIi32ayGNiWVj7DH7X7C0UZJc6lNpvXrgfuQ0SLb3kNh1JWeC/v

### Context

l had conditional visibility conditions in AppBar in my project. Now i can not to set or change my conditional visibility properties of AppBar.

### Visual documentation

![Знімок екрана 2023-08-16 115900](https://github.com/FlutterFlow/flutterflow-issues/assets/121444345/15febee8-0b60-4688-9c43-c35bf3b4653e)

### Additional Info

I want the conditional visibility conditions in AppBar to come back

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web, windows
- Browser name and version: chrome 115.0.5790.171
- Operating system and version affected: windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @Lozovytskyi-R. This should be fixed in our next update. Thanks!
