### ISSUE TITLE
Expandable Icon set by color missing

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1283]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There isnt an option to change the icon color by variable in the Expandable widget (a total pain when you have an app with 40 themes!).
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/69673de5-58bd-43ed-95d6-80932950e1f8)

### Expected Behavior

have the set by variable as an option.

### Steps to Reproduce

create an Exapndable widget, and try setting the icon color.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

makes it hard to implement a multi theme app that is data driven.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/7a7cd91c-2751-430e-95a8-1bbc8be18ff1)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hello @OldFred2023 - This is a feature enhancements / requests. Use FF in-app feature request form to submit this request. You can find the form under help section.  Below is the form.

<img width="749" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/f57f40cc-c879-4ccd-b2cc-8013e799bb75">
