### ISSUE TITLE
toMap and fromMap on data types not recognized in custom functions

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#1286]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

there are many reasons to use toMap and fromMap in functions (not actions) but in functions they throw errors.

it builds fine for app publishing and works, but trying to publish to web the errors block publishing from flutter flow ui.

### Expected Behavior

since toMap and fromMap are valid methods and we have access to other methods on Data Types they should not throw errors. 

in testing locally in vs code no errors. 

### Steps to Reproduce

1. write a function with toMap or fromMap and you get errors on checking custom code.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

noncustomcode

### Context

i have been working on the user side of the app with no issues, compiling with these small (not real errors) is ok because code magic knows they aren't errors.

but now i am trying to publish a web version and i cannot publish with these "errors" in my project. 
![CleanShot 2023-08-16 at 14 03 20](https://github.com/FlutterFlow/flutterflow-issues/assets/101305587/fedfb6a4-7227-46db-8d6e-961dac3dae57)

### Visual documentation

![CleanShot 2023-08-16 at 14 03 20](https://github.com/FlutterFlow/flutterflow-issues/assets/101305587/41dcacad-cd64-4577-8d7e-e63146c00dde)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment]
Hi @trevorFields - Thanks for submitting the issue. Please update the issue with project bug report code. Thanks

**Comment by impowski** [comment]
I have the same issue. Using `fromMap` in actions is fine but functions resulting in an error.

**Comment by trevorFields** [comment]
Did the most recent update fix this?

i just tested this and saw i didnt get an error, but before i switch back to this method of making a copy using toMap and fromMap i want to make sure im not missing something.

**Comment by trevorFields** [comment]
here is the bug report, and i realized i highlighted to wrong part of my image, its the code at the end NutritionStruct.fromMap()

Bug Report from coustom code editor:
The method 'fromMap' isn't defined for the type 'FoodItemStruct'. Try correcting the name to the name of an existing method, or defining a method named

**Comment by impowski** [comment]
@hariprasadms, here is my case, pretty much the same stuff. I've tried different approaches, such as using `cast` function and else, but they don't work too when the app launches, and `fromMap` doesn't work on function check.

Using inside of the `Custom Actions`:
```dart
Future<LoadStruct> convertJsonObjectToLoad(dynamic jsonObject) async {
  return LoadStruct.fromMap(jsonObject); // works as expected
}
```

Using inside of `Custom Function`:
```dart
LoadStruct convertJsonObjectToLoad(dynamic jsonObject) {
  return LoadStruct.fromMap(jsonObject); // returns an error
}
```

**Comment by dhazeley** [comment]
I'm also seeing this error. Is there any update on this?

**Comment by Ortes** [comment]
Same here

**Comment by katherineqian** [comment]
Hi, I apologize for the very late response on this. I was not active on maintenance and I'm sorry for letting this fall through the cracks. I investigated and shipped a fix for this bug and it should be available in the next release. The details you provided in the bug report and discussion were very helpful in diagnosing the error. I wanted to provide a temporary suggestion for unblocking, but I believe that the best thing to do in the meantime is try to use a custom action in place of a function. Again, I'm sorry for the delay, and thank you for reporting this bug.

**Comment by katherineqian** [comment]
Yeah, this is fixed but it's not released yet unfortunately. Based on the current release schedule, I believe it should be in the public version around the end of next week -- so in the meantime yes, I'd still suggest the workaround with custom actions.

**Comment by trevorFields** [comment]
This seems to be not quite fixed correctly on the release today. In FF you get one error on accessing the fromMap using static access, but in vs code you get the opposite error. I believe we should be accessing fromMap using the stat access. see my code examples below:

// in FlutterFlow this returns an ERROR
// "Instance member 'fromMap' can't be accessed using static access. "
MeasurementStruct copyMeasurementStructs(MeasurementStruct original) {
  MeasurementStruct copyStruct = MeasurementStruct.fromMap(original.toMap());
  return copyStruct;
}

// in FlutterFlow does NOT throw an error
// BUT Vscode it throws this error:
// "The static method 'fromMap' can't be accessed through an instance."
MeasurementStruct copyMeasurementStructs2(MeasurementStruct original) {
  MeasurementStruct newStruct = MeasurementStruct();
  return newStruct.fromMap(original.toMap());
}


> Yeah, this is fixed but it's not released yet unfortunately. Based on the current release schedule, I believe it should be in the public version around the end of next week -- so in the meantime yes, I'd still suggest the workaround with custom actions.

**Comment by katherineqian** [comment]
Thanks for letting me know @trevorFields, investigating now

**Comment by katherineqian** [comment]
Hi @trevorFields, thank you very much for pointing out this remaining bug with the custom functions analysis on structs. It's actually fixed now (tested on both the instances that you mentioned 😅 ) and will be released in the next version next Thursday.
