### ISSUE TITLE
Translation Bug

### ISSUE THREAD

**Issue by mosh-frs** [FlutterFlow/flutterflow-issues#1288]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![cal](https://github.com/FlutterFlow/flutterflow-issues/assets/142459235/6b064a2e-7a79-43a4-a90c-7c0efeabe2b6)

![Slide2](https://github.com/FlutterFlow/flutterflow-issues/assets/142459235/6b372d12-a2b7-4a9e-9736-4269e0ad7623)

![Slide1](https://github.com/FlutterFlow/flutterflow-issues/assets/142459235/52fcf24d-09e9-4a2f-a047-7ddeeec6b702)

### Expected Behavior

1. In the calendar widget, when users select the Arabic language, the calendar is supposed to display all numbers in Arabic. However, what actually happens is that the numbers in the header are displayed in Arabic as expected, while the days are dated in English! This error occurs in both the mobile and web apps.

2. Numbers are consistently displayed in English. There is currently no way to display numbers in Arabic, especially within code expressions.

3. The translated mobile app displays numbers in the correct direction, from right-to-left. In contrast, the translated web app incorrectly displays numbers that include a comma or decimal point separator in the opposite direction, from left-to-right, similar to English! This is also the case when using a column to display numbers in the time format HH:MM

### Steps to Reproduce

1. Create a page that includes numbers with both comma and decimal point separators, such as 1,234.56 for example.
2. Place a time-formatted number on the page, such as 13:28 for instance.
3. Incorporate an action that involves a Time/Date Picker on the page.
4. Translate the page into the Arabic language.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi8mBx5d2odxE1c/ibu1Wlj8wGUALa+dI0tZ+TQ0jF5D4B7Acfc7sQFtvTfKzaH1beleYikQCweDJuPP1Nfo7EzueRapmz5BTWBPPbGGXMMzSO8y8Q3JBIJlYC1Sv55+vugpSIrBac3Ng7U2ANvC9QT6Cf9qOYwx5e6fDbOY=

### Context

I am trying to translate the app to Arabic language.

### Visual documentation

![Date Picker](https://github.com/FlutterFlow/flutterflow-issues/assets/142459235/eebfb967-0e22-46ad-b822-4ab3248f6fcc)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web & Mobile
- Browser name and version: Chrome
- Operating system and version affected: Android & iOS
```

**Comment by victoriahuang1** [comment]
Hi @mosh-frs , thanks for the report. I have been looking into this, and unfortunately this is a Flutter/Dart-level issue. There is no easy way for us to fix this, so we will be waiting for Flutter/Dart to fix the issue on their end.
