### ISSUE TITLE
web publisihing failed without a visible reason

### ISSUE THREAD

**Issue by yairpe** [FlutterFlow/flutterflow-issues#1290]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No errors in the project.
It runs fine in RUN, TEST and download+Visual Studio Code.
 

### Expected Behavior

expecting to create a working web app in vidate.flutterflow.app

### Steps to Reproduce

1. click on run selection (lightning)
2. click on [Publish] button
3. wait few seconds

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci/LqwIhjpbxb7aXqacFvryQsIjs/RYINiMEaRgIdJ5PMC+wIZ/f7XFRuTde0YwllPkyWo3Mxw/vemvLlJPdfKUiufL5R/rhcbhbMJViQbr3SBpO/OW5/DeBMf0/G0MCFhCZ5OtRiS3dm62eAAu6uQh3DNZzWDDIvAfykA5CK2SrDX1iXc2URm05KZDPz

### Context

test the project for web

'The steps to reproduce above start from a blank project' is not true but the form forces me to click it be able to submit

### Visual documentation

![web_publish_issue](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/9dbdfbbf-5f68-4014-b4c4-33269e132bf9)

### Additional Info

There are no errors in Chrome dev console

### Environment

```markdown
- FlutterFlow version: 3.1 flutter 3.10.4
- Platform: web
- Browser name and version: Chrome 115.0.5790.171
- Operating system and version affected: Win 11
```

**Comment by hariprasadms** [comment]
Hi @yairpe - Thanks for submitting the issue. I looked your project. I can see errors in a custom component in downloaded code. However, there is no error notifications showed in the FF which is not correct. This should be a bug specific to project.

**Comment by yairpe** [comment]
Hi @hariprasadms,
Thank you.
You are correct but this is another issue and I think I can bypass it (a variable that used to be in page state now is in component parameter with the same name so some places I may forgot to update)

The problem I cannot deal with is the one mentioned in this ticket, meaning failed publish to web without a reason.
Please advise

**Comment by yairpe** [comment]
It is still failing to publish to web.
There are no errors in the project.
It runs fine in TEST and RUN modes
Still in flutterflow 4.0 it fails publishing to web.

Please fix

**Comment by takashiff** [comment]
Hello, I just took a look at your project and it looks like you are using actions that are not supported on web. In the "Warnings" section, it says shareAction and htmlView widget are not supported on web, which is preventing web publishing from working properly.
