### ISSUE TITLE
Wrap widget ELW is not working

### ISSUE THREAD

**Issue by Parth-fineapple** [FlutterFlow/flutterflow-issues#1291]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using a wrap widget and the children are generated dynamically via "Generate dynamic children". Now When the query is empty it throws null. To handle null, I have added ELW but the ELW is not working? 
I am also using an app state, so previously the app state is null, later on when user performs an action the app state is updated. 

### Expected Behavior

ELW should be visible when the query is null.

### Steps to Reproduce

1. Create an app state, data type dateTime
2. Query a collection (list of docs) on container
3. Generate child on wrap with some filters(for this the app state is used) on the **Wrap widget** 
4. Filter - Only generate documents which lies within that date.
5. Set up ELW so when the query is empty ELW will be visible 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oksrlvJN1rs9H1r6JbvpanSQ7Qm59U50Zi8pOECAaIpzpBu0MYs77M09uZ7S9aVNfemaZnmEE0/OKueD9UvZfKTmdG6Y5yMxuTxbee2iXMaa4EruoOnJCEfNVC27A5ra43RNSOfhicXg66jmmO/DIH3LDFOu/Zwh9f6PHaOI=

### Context

ELW should work so that null is handled.
I have tried to download the code and changed the code and use ternary operator and it worked. 
Only need to change two lines in code for the ELW to work. I don't want to change the code every time (because of the merge conflicts).

### Visual documentation

Screenshot of what we changed in order to make ELW work - 
![Screenshot 2023-08-17 at 3 12 48 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/132039635/1c200959-9019-4a04-bc55-7783bab942b1)

Null error because ELW is not working - 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/132039635/6e097418-caaf-4df0-81c8-ca7ba86f516f)

### Environment

```markdown
- FlutterFlow version: v3.10.4 (released August 16, 2023)
- Platform: Web
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: MacBook m1 Venture 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @Parth-fineapple - Thanks for submitting the issue. I looked at your project and managed to find the page you are showing above ( Note - When blank project is not setup with issue steps, at least issue location in the project (page or component location) should be well explained to locate the the issue).  
<img width="1505" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d81f2795-fb41-40ea-86e2-de06dedbb87c">

I do not see empty list widgets are not configured where wrap widget are used. You can use conditional widget to check the null value and display the widgets accordingly or you can use in built empty widget handler option which comes with listview/column widgets. Try these options and let us know how it goes. 

<img width="370" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/673cd969-e797-44f1-a168-fd7489022320">
