### ISSUE TITLE
Display name not added to User document when signing in via Apple

### ISSUE THREAD

**Issue by MaggieThomann** [FlutterFlow/flutterflow-issues#1292]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello! My app was recently rejected by App Store Review because when using "Sign in with Apple", it didn't prepopulate the first and last name on the signed in User from the Apple credentials. I also checked in Firestore and `display_name` is not saved to the User record.

### Expected Behavior

I would expect the `display_name` to be automatically saved to the User record, similar to how it is with Google sign-in, when I use Apple sign-in.

### Steps to Reproduce

1. Sign into the app with Apple sign-in.
2. Check the user document created in Firestore and note that "display_name" is not there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kh8/lsM92pbwF1s7tbe1agSgsKWF8TLJEoetxc0gbfe/4EIYqPOLRXFBvOdSzaH5bMWD+jlI106H4iOPtFfYFEyWdfapy1ZBUEBPPbHiRRq61ELmOPHBfJ59bf2LH4KWzgAonBPZhcXsu20OUP+SRQT2Cf9qOYwx5e6fDbOY=

### Context

This was blocking our App Store review from progressing, because Apple expects you to use their "Sign in with Apple" flow fully. We ended up figuring out how to retrieve the display name from Apple using the Firebase ID token of the user in an API call that we added to our action tree right after sign in. But without that action and subsequent database update, `display_name` is never populated.

I believe it's an issue with this line in `apple_auth.dart`:

```
  // The display name does not automatically come with the user.
  if (displayName.isNotEmpty) {
    await user.user?.updateDisplayName(displayName);
  }
```

When you use a debugger, you can see that the `User` on the `UserCredential` record never gets `display_name` updated (i.e. it's always null). I found [an issue logged](https://github.com/firebase/flutterfire/issues/9662) that seems related and they claim it was fixed, but there are several comments on the issue that say otherwise. And it looks like our package (`firebase_auth`) is up to date within FlutterFlow, so it seems like it should have picked up the fix (if it was indeed fixed) 🤔 

Anyway, perhaps `apple_auth` can be edited to return both the `user` and the `display_name` and then `firebase_auth_manager` could perform the `display_name` update? Or it could all happen within `apple_auth`? iOS is so pesky to work with sometimes! I love how simple the `google_auth` file is in comparison.

I also believe this issue will affect anyone trying to get App Store review with Apple Sign In unless they have a workaround. See this old community post about it: https://legacy-community.flutterflow.io/c/discuss-and-get-help/apple-sign-in-using-profile-data

And here's our workaround API call:
<img width="1192" alt="Screenshot 2023-08-17 at 2 42 13 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15825518/1654f827-869f-4036-8cc9-96b55b867d9a">

### Visual documentation

I had to upload the demo to Google drive because the file was too large but see here:

https://drive.google.com/file/d/1YeiX-0bik0jLqdKRUSkkWLCH5X9wE94U/view?usp=sharing

### Additional Info

Thanks in advance for fixing!

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome Version 115.0.5790.170 (Official Build) (arm64)
- Operating system and version affected: macOS 13.2.1 (22D68)
```

**Comment by MaggieThomann** [comment]
Commenting because this is still an issue and so that it doesn’t become stale.

**Comment by khomya** [comment]
I've been rejected from AppStore too.
And because FF is not retrieve names from Apple.

Is someone at FF working on this issue?

**Comment by MaggieThomann** [comment]
<img width="1024" alt="Screenshot 2023-08-28 at 10 46 47 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15825518/18eed5dc-ec2a-4dad-8136-42286e4746f0">

@khomya yes, you can find it in Firebase console under Settings for your project!

**Comment by almgandre** [comment]
@MaggieThomann Thanks for sharing your workaround solution.
How do manipulate the response from your API call?

**Comment by khomya** [comment]
Yes, I tried it in the first place :)

But I think I fiil the rest fields of API Call in FF somehow wrong.
Could you please show pictures with all screen of "headers", "variables", "advanced"?

I get:
{
  "error": {
    "code": 400,
    "message": "INVALID_ID_TOKEN",
    "errors": [
      {
        "message": "INVALID_ID_TOKEN",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

**Comment by khomya** [comment]
I understand that I need to get TOKEN and than with this token I should get name&familyname from Apple.
But i dont know how to do it all :(

Maybe you can upload somewhere your files for this workaround. And I could look at them and try to recreate in my project?

I am not a skilled programmer (thats why I use FF :))

**Comment by khomya** [comment]
Nnnnnnice!
Will try this!

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @MaggieThomann. It will be fixed in the next update.

**Comment by khomya** [comment]
@MaggieThomann could you please help me...
I understood how the Api Call works and how to get a first and last name from apple later, but I can't get it to work this link https://identitytoolkit.googleapis.com/v1/accounts:lookup ?key=***

do I need to make some settings in Google?

**Comment by khomya** [comment]
<img width="1432" alt="Screenshot 2023-09-02 at 11 51 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/b18addc0-c107-4bac-9cb9-c75829db44e7">
what to do here to get displayname?

**Comment by MaggieThomann** [comment]
Ah ok you have to access the "DisplayName" JSON path! Here's a screenshot of how we do it @khomya :

<img width="1547" alt="Screenshot 2023-09-02 at 10 58 19 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15825518/83c46fde-b947-44b3-9317-3b3f11a18cef">

**Comment by khomya** [comment]
Its me again :)

What is your JSON Path on this page?
<img width="1180" alt="Screenshot 2023-09-02 at 14 13 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/9320e339-89e6-4be9-b361-685fc39b02fb">

**Comment by khomya** [comment]
And does your "test API call" return 200?

**Comment by MaggieThomann** [comment]
@khomya this is what mine looks like! Mine returns a 400 like yours when I test through the "Response & Test" flow, but works when I deploy to my app.

<img width="1173" alt="Screenshot 2023-09-02 at 1 41 09 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15825518/c7f99973-55d3-4763-87a1-7b87036f7594">

**Comment by MaggieThomann** [comment]
@aemelyanovff Hey Anton, what version should we expect this to be fixed in btw? I just tested it with v3.1 and it's still not working.

**Comment by khomya** [comment]
@MaggieThomann I cant tell how grateful I am for your help!
THANK YOU!
It motivate me to help others!!!

It worked!
I submitted project to Apple. I hope they will accept new build. (And not ask for a avatar from Apple to be inserted too)

**Comment by MaggieThomann** [comment]
Woohoo!!! So glad to hear it worked! Hope you passed App Store review 🤞 @khomya

**Comment by aemelyanovff** [comment]
> @aemelyanovff Hey Anton, what version should we expect this to be fixed in btw? I just tested it with v3.1 and it's still not working.

Most likely some time this week, but no guarantees. You can see the last update date by hovering over the FlutterFlow version:
![Screenshot 2023-09-05 at 8 24 47 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/a274e440-e5f2-4ac7-9afd-78eed894fb88)

You'll need to re-generate code and/or re-publish your app after it's updated.

**Comment by khomya** [comment]
@aemelyanovff will you add a "picture" variable, for the Apple Users? (Google users get their avatars!)

Because Apple demand avatars as well for approving app.

**Comment by neo-etremblay** [comment]
This issue is happening to me too
