### ISSUE TITLE
Swipeable Stack can't update 'STATE'

### ISSUE THREAD

**Issue by mrbose-a** [FlutterFlow/flutterflow-issues#1294]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

swipeable stack is not updating the page state or app state on tap action .

### Expected Behavior

the swipeable stack should update the state, on tap action.

### Steps to Reproduce

1. swipeable stack
2. add  2 container widget
3.  add app/page state (boolean/string) 
4. set/clear state on Tap actionswipeable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gzsrhuJZIoeFD7rruYO9Vijs7H1s4a600utoaRQgaCIz2B7M+Y/ilVEpVOPG0SghqeFm0oHg0+cHemvHxNfYBPU2rGLZl+qVIcRbibFiQMa6uDs/pYG5/DcdnBXa/5qTUkSRTHPNtLyRhwVz7OfOUZCzaNKLPC243G+SbC5OK2SrDX1iXc2URm05KZDPz

### Context

someone in the community wanted to implement a flippable card inside of a Swipeable card, but if the card face is changed the flippable card is not reverting back , on the next swipeable card, 

so I had a go to check it out and tried to build a stack with cards but with conditional visibility (appState) 
it was a pretty simple action, it should work in theory but it did not, so I replicated the same thing inside a list view it worked as intended.

### Visual documentation

ui & testMode

https://github.com/FlutterFlow/flutterflow-issues/assets/116948493/dcce2b3a-9797-4265-8514-411f77e8ec0a

### Additional Info

Additionally, check the Flipable cards behavior with Swipable Card

### Environment

```markdown
- FlutterFlow version: latest
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: windows11
```

**Comment by hariprasadms** [comment]
Hi @mrbose-a - Thanks for submitting the issue. I have looked at the project. I can confirm that swipeable stack widget working as expected while try to update the state with below actions. However _**OnTop**_ action is not available for the swipeable stack widget. If this is not the case, above reproducible steps and issue details should be updated with exact steps to reproduce the issue. 

<img width="1063" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/4d931067-12f3-4f35-ab61-e7d85875d3e0">

**Comment by azmat007** [comment]
I have tried using the swipeableStack, but whenever i try to apply an action for any kind of swipe, the 'navigation to' or even the 'bottom sheet' function both wont work when i try to preview the page. There is no action on swipe.


![image](https://github.com/user-attachments/assets/70d96b71-8a9d-48d5-b0d2-80f81352a2d1)
