### ISSUE TITLE
TextField is not properly following initial value from a firestore doc

### ISSUE THREAD

**Issue by smostovoy** [FlutterFlow/flutterflow-issues#1295]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. We have a test quiz in the app, each question is a page "Task" with a navigation action to the next question, also a page "Task"
2. on navigation we pass a firestore doc ref, all fields on the page use data, which they get from firestore by the ref
3. On the test quiz there are 3 questions, so 3 times same page is rendered with a textField. 
4. I don't see a pattern but navigating back, next, saving, unsaving - all is detached from the actual textField initial value, it seems like the field prefers existing value over the one from the firestore

### Expected Behavior

textField initial value is always actual to the firestore doc value that is set an initial value. In the app - after saving i's expected to be always equal to the value above the field in the text box

### Steps to Reproduce

1. reproduce "Current Behavior" setup
2. or run our app, using the user below, start the quiz from the home page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESi8rqw5dgouUD+qrAc+1qhQMjNlx7bZAnktV+WRMhfeP0PLN3PfTCXFtLYteGSlY2eVGGmkAd0+DtifLPNu0BGz6rGYRB+r5XQTnNXXyRRZCXCZOZPHEmO9pgCX6n0qWnmQl/JrJ0WEIQ2DuHevCNG3qCf9qOYwx5e6fDbOY=

### Context

production app usage blocking, critical

### Visual documentation

https://screenpal.com/watch/c0jbotVp2rc

### Additional Info
project: mira-8w5lc6
test user: 
+380001112233
code: 000001

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web/ios
- Browser name and version: chrome 113
- Operating system and version affected: mac, ios
```

**Comment by hariprasadms** [comment]
Hi @smostovoy - Thanks for submitting the issue. Initial value ( default value ) of the text field does not change when fire-store mapped filed value is changed. This is as per the core functionality of flutter text field widget. You should use the app or page states along with fire-store value display from references up on save. I can confirm that, this is not a bug.

**Comment by smostovoy** [comment]
@hariprasadms on page load it seems the record is no yet availability. And changing initial value to the page state will not work. How to use the page state then to solve the case in this ticket?

**Comment by smostovoy** [comment]
@hariprasadms @victoriahuang1  could you confirm it's a bug?

**Comment by smostovoy** [comment]
@aemelyanovff You basically repeated @hariprasadms . My comment to that was that I navigate to the NEW page. I don't update existing page. It's the same page name but a new rendering of a page, with a new firestore doc. So the steps would be next:
1. create page e.g. `Task`. Add page parameter as a firestore ref, e.g. `ref`
2. set page backend query to firestore query by parameter ref. You will new few records (seems to be 3 records is when it starts to fail, 2 is ok) . Each record should have 1 text attribute and 2 attributes with a ref to a next and previous record. So records form a chain, each record has an attribute referencing next record. E.g. Collection `tasks`, Task(:value, :prevTask, :nextTask)  
3. add 1 text field, set text field initial value to a current fetched firestore record attribute
4. add a 'Save' button, add an action on click:
    * update the firestore record `value` attribute with a text field value 
    * navigate to this single page `Task` with a page parameter set to the next record, e.g. current record's `nextTask` attribute
 5. Create 2 buttons to navigate back and next. Use  Task.prevTask and Task.nextTask attributes for onClick navigate actions.
 6. Now run the app, fill the value, click save, repeat until there is no next record. Navigate back
 
Expected: While you fill the values each new page render should show blank text field. Then when you updated all records and navigate back - you should see in the field the value you set for that record.
Actual: The value that was input on page 2 is shown again on page 3. Then, even if you set each field to a uniq text and click save and navigate back - you see some other values, e.g. task2 value for task3, or task3 for task2. Though I confirm that firestore DB is set correctly. Check out on video

**Comment by smostovoy** [comment]
It looks like I've found a solution - it doesm't happen when "Allow back navigation" is set to true. Would be interesting to know why. I guess rendering "way" is different in this case, each render is like a "real full rerender"
