### ISSUE TITLE
buttons ignore the size in test mode after an instant reload

### ISSUE THREAD

**Issue by alexsanderp** [FlutterFlow/flutterflow-issues#1298]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

buttons ignore the size in test mode after an instant reload

### Expected Behavior

Buttons must follow the configured size

### Steps to Reproduce

1. Run test mode
2. Run instance reload

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflMmAx4Vgobxc7r6IK+xF+Ts7OWEcTeU30+thcw4bI+PuP4oqfsjRYkhWSOqHeglqEVqWnjgf3NrVidnMFcA5GE2CbIt8z8x5UxDgcGKhVZisBauSe2pPL/xWf1yH37urqxMlCMZaS3Aa1GGqLuyub3qCf9qOYwx5e6fDbOY=

### Context

It just bothers

### Visual documentation

Test mode (init)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/30603084/c93c6523-658a-4190-9830-219ef5b17f48)

Test mode (after instant reload)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/30603084/57d15c5d-141d-435f-80fc-4d6f84158caa)

### Environment

```markdown
- FlutterFlow version: v3.10.4
- Platform: Web
- Browser name and version: Google Chrome Versão 113.0.5672.126 (Versão oficial) 64 bits
- Operating system and version affected: Ubuntu 16.04
```

**Comment by hariprasadms** [comment]
Hi @alexsanderp - Thanks for submitting the issue. I have observed this behaviour but it is inconsistent. Can you try different page and add more buttons and see when exactly showing this behaviour. Thanks

**Comment by alexsanderp** [comment]
@hariprasadms I restored to a previous version of the problem and if it solved, I decided not to waste too much time on it, thanks.
