### ISSUE TITLE
Group Variables not working in headers

### ISSUE THREAD

**Issue by nick-chargely** [FlutterFlow/flutterflow-issues#1299]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Setting variable at group API level is not getting picked up when passed in from the UI builder. When it is moved to the endpoint header and variable it works as designed. 

### Expected Behavior

Expected top be able to set the variable from the UI builder even at group level - same behavior as if it was on the endpoint level

### Steps to Reproduce

1) Go to group API (not individual endpoint)
2) set `Authorization: Bearer [jwt]` at group level
3) define a `Group Variable` - add `jwt` as the variable
4) go to UI Builder and call this API and define jwt 
5) check the logs and you will see [jwt] is never replaced which ultimately causes a server error 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr1z4Z2xNtD0a6Jbe9alSQWMjsmULgZl+4acCs8GqLuPe0UWMzBUBFUOPHhd2NIfU6j8T4X/Mr9j87lU+4pOUidQalyybVibgHxTnm6RYSTDJS3b0ZQBd1hI3KH4LeFmyJ5BMViLloS72CIHe+/d3bZGZu2NTJEMeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Currently I am having to define the jwt at endpoint level inorder to make it work - seems like there is no way to get the variable to pass properly at group API level

### Visual documentation
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/e4c21886-9c4b-48f2-ba0e-0ff4f2a3f62b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/21ea6ef6-72ce-4cd9-9972-398dee56a193)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Android / iOS
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hi @nick-chargely - Group variables can't be used at group headers. This is as per design. The point of group header parameters to keep at group level and not allowed to parameterised at actions level. This works in api test mode for testing purpose only. I hope it make sense.

**Comment by SameerShahzad99** [comment]
@hariprasadms this implementation seems confusing, It should be written in Test mode that it is for testing purpose only

**Comment by aemelyanovff** [comment]
@nick-chargely Thanks for reporting the issue. I think you are right, it's a bug. Group variables should be substituted in headers.

**Comment by helixworld** [comment]
Where are we with this? I see this is priority medium but an ETA would help

**Comment by aemelyanovff** [comment]
Fixed in the next update!
