### ISSUE TITLE
Can't set action parameter on Empty List Component

### ISSUE THREAD

**Issue by joshensongric** [FlutterFlow/flutterflow-issues#13]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

1. Create a list/column/grid/row
2. Link it to a firestore query returning a list of documents
3. activate the 'show empty list widget' option on the list/column/grid/row
4. Select a component that has an 'action' parameter
5. try to pass in an **action** parameter from the empty list widget settings
6. action flow editor should open and allow you to configure the passed in action parameter
--> (6a) OR it should not be possible to select / try to pass in the **action** parameter

## Current behavior (required)

on step (6) the action flow editor is not show and there is no way to set that parameter so it remains **unset** and a bug is shown in the Project issues menu that cannot be cleared

## To Reproduce (required)
 n/a

1. Create a list/column/grid/row
2. Link it to a firestore query returning a list of documents
3. activate the 'show empty list widget' option on the list/column/grid/row
4. Select a component that has an 'action' parameter
5. try to pass in an **action** parameter from the empty list widget settings
6.observe that the action flow editor is not visible and it is not possible to set the action parameter

## Context (required)

I am trying to use a single component for multiple empty list widgets that need to have different actions

## Screenshots / recordings

<img width="1440" alt="Screenshot 2022-09-25 at 11 25 03" src="https://user-images.githubusercontent.com/71047441/192152220-fe647c90-0b76-46df-9d1f-f22b4bcd812c.png">

## Your environment

* Version of FlutterFlow used:  3.0 September 25th
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version:  Chrome Version 105.0.5195.125 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): Mac OS Version 12.5.1 (21G83)

**Comment by bulgariamitko** [comment]
I just tried that and it is showing a normal workflow instead of the Action Panel

**Comment by sirian-m** [comment]
@wenkaifan0720 Is this issue something that is being worked on currently? Would be greatly appreciated if it could be added as it allows for components to be more easily be reused.
