### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by graymanOz** [FlutterFlow/flutterflow-issues#1300]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page in my app  - my ABOUT page - that now only shows a blank white page.  Also its clickable icons freeze and don't respond.

The change is seen in test  mode and in android emulator.

This problem has not appeared in this and past versions, as seen in test mode / android emulator / app store / play store..

My testing has been:
 - I have gone back to prior versions and the issue appears in them too, when previously they were working ok.
 - i have rebuilt the page structure in the current version of the app - using same struture - and the problem is persists
 

Changes that fixed the problem:
 - The cause of the problem appears to be the selection of Expansion: Flexible at the container level.
 - When Expansion: Default, there is no issue.

The tree is:
stack 
- column
 -- container - This is where the problem is
 --- column
 ---- text

Anyway, so it seems i have fixed it for me.  But it worked before now, so it seems like a bug. 

Thanks

### Expected Behavior

I expect to see the text on the page as per previous use, instead I get a white page.

### Steps to Reproduce

i rebuilt a new version of the page in a new project - same problem

changing the expansion per above removes the problem

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXls/l5Yx2ssBE187xLMJVqDwwGUwbUOc7j9VEGAsjCeP3EZkuYuP8TFhtYuqHfVZcJVmlgk8C0tXGivz9NvcENTCbf4h6zc9bUxDjRny5RL2YPKm0WHQmBfhRJn7G5J6zpxZCBO1hclI43DmHNvCAb3qCf9qOYwx5e6fDbOY=

### Context

my about page has gone white

### Visual documentation

![FF 18 08 2023 Screenshot (321)](https://github.com/FlutterFlow/flutterflow-issues/assets/101852823/41827655-0d4d-4013-b097-33481859347a)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: Chrome Version 115.0.5790.171 (Official Build) (64-bit)chrome
- Operating system and version affected : windows 11 home 22H2
```

**Comment by hariprasadms** [comment]
Hi @graymanOz - Thanks for submitting the issue. I looked at project about page. You got widgets inside scrollable column widget that mean, you no need to expand the widgets with in column as it can scroll as content size. I can confirm that it is not a bug. It is related to widgets layout configuration at your end. Try to adjust widgets around the column. It should work fine.
