### ISSUE TITLE
Can't share project in FlutterFlow Preview app

### ISSUE THREAD

**Issue by ntua-el17840** [FlutterFlow/flutterflow-issues#1306]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I downloaded the "FlutterFlow Preview" app and I am trying to share the project I made in FlutterFlow. The button doesn't seem to work. I am sending you a screenshot of the button I am referring to.
![Screenshot_2023-08-15-23-54-48-046_com flutterflow preview](https://github.com/FlutterFlow/flutterflow-issues/assets/75086054/70c93e83-5f2c-4b1b-ad45-33babe3555e0)

### Expected Behavior

The share project button, in the very least, should let me copy the link. Furthermore, it should be able to send it through some app (like viber or discord e.t.)

### Steps to Reproduce

1. Dowload the FlutterFlow Preview App
2. Log In
3. Go to a project
4. Press the 3 dots on the top right corner
5. Press the "Share Project" button
6. It does nothing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

It doesn't have a bug report

### Context

I downloaded the "FlutterFlow Preview" app and I am trying to share the project I made in FlutterFlow. The button doesn't seem to work.

### Visual documentation

![Screenshot_2023-08-15-23-54-48-046_com flutterflow preview](https://github.com/FlutterFlow/flutterflow-issues/assets/75086054/5842259d-7f26-4b16-b337-6c636ec74f11)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Ariel-Pichone** [comment]
Im having the same issue

**Comment by aemelyanovff** [comment]
@ntua-el17840 Thanks for reporting the issue. This feature is not implemented it; for now we'll just remove this button from the Preview app. Please use https://app.flutterflow.io/ to share your projects!
