### ISSUE TITLE
Chart widget properties has very large grey square

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#131]
## Expected behavior (required)
Use Conditional Visibilty on Charts

## Current behavior (required)
When using Conditional Visibility using a variable to show/hide a Chart widget, a very tall grey square obfuscates the properties for the Chart widget.

## To Reproduce (required)
1. Create a chart
2. Enable Conditional Visibility
3. Do a single condition set to local state

## Context (required)
It's very annoying to have to recreate the Conditional Visibility parameters every time I have to change something in the Chart widget properties.

## Screenshots / recordings
[Image](https://photos.app.goo.gl/LWksTGnq9SgU4RYQ8)

## Your environment
* Version of FlutterFlow used: 1.1.18 
* Platform (e.g. Web, MacOS Desktop):  MacOS Desktop
* Browser name and version: Safari Version 15.6.1
* Operating system and version (desktop or mobile): MacOs 12.6

**Comment by agreaves** [comment]
Hi @ampapplarsen, this should now be resolved so I'm closing for now. Please let me know if this is not the case and I'm happy to reopen the issue! If you do, please include the Bug Report Code for this widget. Thanks!
