### ISSUE TITLE
Custom Font not Found in Image Upload Action

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1311]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I added a custom found in Image Upload Action but its not loading both in test mode nor in Android Studio on Simulator
Note that I have two fonts. The other font loads fine with everything however it seems recent update changed something that caused this.

### Expected Behavior

I expected to see the Media Gallery bottom view to show the custom font I selected

### Steps to Reproduce

1. Upload Custom Font
2. Test Image gallery action
3. Change Font from there
4. Test run the app and execute Action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfHl3ItNsdtY15SJY/papyQ7NUQia7gn08pBazwbfe+uB4kqevfOTERpYO2oTUFUJk79mWoW3PDHvoSWM8coH0irRqVyzcx2TzmVbD2iV5jXFJWgeUFCJ+hgI0fG5MCzqhFACPp2Wnct7Du2Feu9YHfaQrrVOm4wDq/LZO4=

### Context

.

### Visual documentation

Here are the visual images of the errors I have faced.
<img width="1512" alt="Screenshot 2023-08-19 at 1 18 03 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/c5f165de-5c07-495e-8047-f7828ddeec7c">
<img width="1512" alt="Screenshot 2023-08-19 at 1 16 54 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/993cd7ce-2d2c-466f-8ec2-ee49e92fcee6">
<img width="1512" alt="Screenshot 2023-08-19 at 1 03 40 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/c4e96371-b641-4326-bea7-370360d8117c">

### Additional Info

.

### Environment

```markdown
- FlutterFlow version: v3.1 (released August 17, 2023)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS Sonoma
```

**Comment by takashiff** [comment]
Hello, I have been unable to reproduce this error. I have followed the steps described above, and I am not running into any issues.

**Comment by Dev-Muhammad-Junaid** [comment]
@takashiff it's been a month since I reported this. So might have been fixed by future updates.
