### ISSUE TITLE
Crash and Project Corrupt in FF

### ISSUE THREAD

**Issue by ivantodorov78** [FlutterFlow/flutterflow-issues#1314]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This crash corrupted the project and make it inaccessible to me, my co-worker was able to revert to an earlier build. 

https://youtu.be/YQigPmx46xM

The crash happened around 2:07pm PST on SAT Aug 19th. 

Project: https://app.flutterflow.io/project/lumenosity-app-93r6hh

### Expected Behavior

crash without corrupting the project

### Steps to Reproduce

see video

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

see video

### Visual documentation

see video

### Additional Info

see video

### Environment

```markdown
Google Chrome on macOS
```

**Comment by SameerShahzad99** [comment]
Hi @ivantodorov78, I am able to access the project on my end, please reach out to the support team if the problem resists on your end! closing this issue as it is project specific.
