### ISSUE TITLE
Bug when pressing View Full Screen on run mode

### ISSUE THREAD

**Issue by saa1627** [FlutterFlow/flutterflow-issues#1315]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On run screen, when I click View Full Screen, a new window appears with a screen that is blank (white).

### Expected Behavior

On run scree, when View Full Screen is clicked, the new screen should show the app.

### Steps to Reproduce

1. Run application
2. Click on View Full Screen button on the top right of the screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClfHl8ZNPxd9c+KXhYe9VnSQvIjt9RY0nkutuGBIgN5PMC+wIZ/f7XFRuTde0Snw3e2ejhmcKw+/emvDlDfQCOU2qb4BfyLt+bjzyTky5aL6vEs3gdm5/AtxTGEyzy6WF3BZ4KvhaWkYA2WaMI9i/VXffJIDrIlUvOsqKF5OK2SrDX1iXc2URm05KZDPz

### Context

I am trying to view the application on run mode in full screen.

### Visual documentation

This is how it looks when I run it (which is fine):
![Screenshot 2023-08-20 at 6 34 35 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/128199136/0756023c-f6ac-4508-9ebd-0d5bde818b35)

This is how it looks when I click on View Full Screen button on the top right (which is the problem as the full screen does not appear):
![Screenshot 2023-08-20 at 6 35 03 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/128199136/44631359-9c80-47bf-8059-c65adf9887b9)

### Environment

```markdown
- FlutterFlow version: 1.1.97
- Platform:MacOS Desktop and Web
- Browser name and version:Saar 16.6, Microsoft Edge 114.0.1823.55, Chrome 116.0.5845.96
- Operating system and version affected: macOS Ventura 13.5.1
```

**Comment by srh98** [comment]
Am also having this issue.

**Comment by sharma93Aman** [comment]
I am facing similar issue for phone screen chopped up view buttons missing screen width portion blank

**Comment by aemelyanovff** [comment]
Fixed!
