### ISSUE TITLE
Listview - I can't choose the backend response when I generate the children from response

### ISSUE THREAD

**Issue by Nedal1990** [FlutterFlow/flutterflow-issues#1317]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After adding a listview to my page as you can see in the below screenshot, I tried to generate children from the variable but I couldn't find the response for my backend call (second screenshot).

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/2d1f5d98-5182-48f3-9aff-6cc5f17d473a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/53d38373-b61e-4984-9be7-df29fd88284f)

### Expected Behavior

To be able to choose the backend response when I generate children from variable in listview

### Steps to Reproduce

1. Create a new page
2. Add listview with backend call
3. Try to add children from the backend response call
4. Observe that you don't have the backend response in the available options

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekvLqw5dNtbxb+ZfcYcBsowMwJHI/auYvte5+d0shNZz0O4YUZvekPxRLYtejelZiJ1H8r3IepPTlufziUsA3ITGrbIB6+b5XQRbNXnGlabqICqiWVEF7L+ZWf3aGy7SFpiZvBNV2cmcj2lOADfCNG3qCf9qOYwx5e6fDbOY=

### Context

I can't complete my project with this issue it's totally a blocker for me, I'm trying to add a page to view all the received matching requests.

### Visual documentation

1. Open the project
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/498c2c47-8738-4ff4-b4bc-ae34cc80661b)
2. Click on requests page
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/4b63261b-1e82-4d1c-b483-da860510ce57)
3. Click on ListView widget
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/8ff5ca98-3d3c-42dc-8644-dfdf3fb86df9)
4. Click on generating children from variable
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/b286a26c-a0eb-4ca4-a54a-6b6799c3db98)
5. Set the value and observe that there is no option to choose the backend response result as a value

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Mobile
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: Ventura 13.1 (22C65)
```

**Comment by hariprasadms** [comment]
Hi @Nedal1990 - Thanks for submitting the issue. I checked your project.  In request page I can see children widgets are generated for ListView widget. Is this still an issue ? Looks like you have figured out the solution.

**Comment by Nedal1990** [comment]
Hi @hariprasadms - Not really I couldn't solve it, the issue is when I try to set the listview data source I can't find the backend response as you can see in the screenshot below
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6751367/c0ca029b-d8e4-42a5-9946-235e76a8ed6a)

For example in this tutorial https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/listview#2.3-generate-dynamic-children 
He configures the backend call and set the response as a data source, go to **2.3 Generate Dynamic Children**, and checks the video at second 10 he is able to choose the backend response, I can't do the same because I can't see the backend response as an option (as you can see the attached image)

**Comment by hariprasadms** [comment]
Hi @Nedal1990 - Thanks for sharing more details. I found the issue. When you got infinite scrolling option is enabled, response object property is not showing up in the list. Disable the infinite scrolling, you can see the response option in the list. This is a bug. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/64773cec-33ba-4a5b-b697-36f8f1cd757f

**Comment by victoriahuang1** [comment]
Hi @Nedal1990 , thanks for the report. I have fixed an issue on our end, and this should be resolved upon the next deploy
