### ISSUE TITLE
API Calls not working on the Web

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#1319]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an api calls.
action in my application that looks like this
<img width="627" alt="Screenshot 2023-08-21 at 10 55 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/606fe115-0d1e-4fb5-9fd7-79dda7723a2b">

In the case of true, it shows one message, in the case of false, another.

In iOS, Android and in Test and Run mode - everything works. Either a message pops up in the True or False branch.
And after that the Custom Action and Push Notifications are executed.

But on the Web, both in normal mode and in Canvas Kit mode, NONE of the messages pops up. and accordingly, the API Call itself does not work and Custom Action and Push Notifications are not executed.

What could be the matter?

### Expected Behavior

API calls should work on the Web too.
Previously - they worked. But suddenly they stopped. And i dont know the reason.

### Steps to Reproduce

1. I just find out about this situation...

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis9f5CvOpYUec/6P1toZMO6Y1Z9MU22p14f0MLGjtrIFfE4AyyAfJxkwal+dQzLeEinM7mTF7W0PHEnDZ1MGE+O0p6zghFBIuNoWUYh3GaUBtmATXXANIT0DFQwSq/LZO4=

### Context

Users on the web cant use fuctions of the app.

### Visual documentation

<img width="649" alt="Screenshot 2023-08-21 at 10 59 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/dc66f7e7-57c5-48d3-bd65-85b643bd5414">
<img width="1183" alt="Screenshot 2023-08-21 at 10 59 53" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/486c9b83-b5ef-4e07-aa66-f1622d04e464">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 115.0.5790.170 and Safari 16.5.2 (18615.2.9.11.10)
- Operating system and version affected: MacOS 13.4.1 (c) (22F770820d)
```

**Comment by khomya** [comment]
Also I have a function that generate Blur Hash for images:

```
import 'package:blurhash_dart/blurhash_dart.dart';

Future<String?> getImageHash(String imagePath) async {
  http.Response response = await http.get(Uri.parse(imagePath));
  final rawImage = response.bodyBytes;
  final image = img.decodeImage(rawImage);

  if (image != null) {
    final blurHash = BlurHash.encode(image, numCompX: 4, numCompY: 3);
    return blurHash.hash;
  }
  return null;
}
```

And its  not working on the Web TOO. On iOs and Android its working.

**Comment by hariprasadms** [comment]
Hi @khomya - Thanks for submitting the issue. Can you please share what error you see in web browser console when see this behaviour?

Also share web deployed link of the app please.

**Comment by khomya** [comment]
Hi!

The app is here: https://georgiatennis.ge/

the error is from CORS
<img width="916" alt="Screenshot 2023-08-23 at 17 51 50" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/9c292965-2ce8-43b6-a23c-c5cae6c2dbf5">

**Comment by khomya** [comment]
'Find' and 'FindDoubles' for example.
Action on a blue button.

**Comment by khomya** [comment]
Any news? I need this fix!

**Comment by kevintonb** [comment]
Hey @khomya , thank you for getting in touch. I have taken a look at the information that you have provided and from the browser console you can see that this is a CORS issue. CORs is a widespread well-known issue for web applications not limited to Flutter / Flutterflow. This comes up when the server blocks requests from the source url which currently here is https://georgiatennis.ge/ . This cors exception will have to be handled from the API server and if you could whitelist and allow requests from the hosted source, you will not be seeing this issue happening. And since this isn't an issue with Flutterflow itself, I'm closing this issue for now. If you still feel like there is a bug on the platform, please add more information to this thread :) We highly appreciate and thank you for taking the time to report this, as it helps us make the platform better for all our users.

**Comment by khomya** [comment]
Well - previously API calls worked! And the website - is on YOUR platform.

>>>This cors exception will have to be handled from the API server and if you could whitelist and allow requests from the hosted source, you will not be seeing this issue happening. 
I dont know what does it mean. :(
Could you please tell me what and where I should do?

And i will add once more - API calls worked at the beginning. And then, they stopped!

**Comment by millarboy** [comment]
do we have any updates on this?

**Comment by kayuzee** [comment]
Try use something like corsproxy.io in front of your API URL. That should fix on web, and also work on app, turn of proxies for that. 

Just Google cors proxy and you'll find a bunch, they're free, easy to use. Ideal? Eh maybe not, but will solve it for a long while
