### ISSUE TITLE
Dropdown Multi Select Causing Errors in Android Studio

### ISSUE THREAD

**Issue by colinriche** [FlutterFlow/flutterflow-issues#1323]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dropdown multi select option appears to work in FF
But if you use the code from FF in Android Studio the following errors appear

DropDown Multi Select - Allow Multi Select

isMultiSelect: true
The named parameter 'isMultiSelect' isn't defined.
The named parameter 'onChangedForMultiSelect' isn't defined.
The argument type 'Null' can't be assigned to the parameter type 'dynamic Function(String?)'.

isMultiSelect: false
The named parameter 'isMultiSelect' isn't defined.

### Expected Behavior

That the dropdown to work in FF and studio
Once added or changed a dropdown in FF
It caused errors in Studio when copied across

### Steps to Reproduce

1. Create page in FF
2. Add Dropdown to page
3. Download code or copy & paste code into Android Studio
4. Check for Errors with isMultiSelect 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl+fqy5dPm/lA1pDbbfow9SQWNkw6aIJEl8N+cE0cB4OuOpwPXf/eTFRvT9ekSgk7L2agrHky0N7OhYbEA+UqHzebGZRBzLtIVDvyXXOjbKrRO6WCQWtPJ99JJVPD5sKvghEkLu5iS3Ng216IAeyRdBPfJ5SyOkUwR+aICJ7VgW+qQ0SLb3kNh1JWeC/v

### Context

Project that builds and compiles in FF
Does not build or compile in Android Studio

I had downloaded my working project into Android Studio and it worked there too
Then I updated some pages in FF and copy and pasted the individual page code and Model code
It was then I saw the errors appear from using Dropdowns.

Easy workaround in Studio
if not using Multi Select then comment out or remove the line isMultiSelect: False 

I have looked through the other issues with Dropdown and I raise this as it could be a root cause to other related issues.

### Visual documentation

Produces 1 to 3 errors

FlutterFlowDropDown<String>(
  controller: _model.dropDownValueController ??=
      FormFieldController<String>(null),
  options: ['Option 1', '2', '3', '4', '5'],
  onChanged: (val) => setState(() => _model.dropDownValue = val),
  width: 300,
  height: 50,
  searchHintTextStyle: FlutterFlowTheme.of(context).labelMedium,
  textStyle: FlutterFlowTheme.of(context).bodyMedium,
  hintText: 'Please select...',
  searchHintText: 'Search for an item...',
  icon: Icon(
    Icons.keyboard_arrow_down_rounded,
    color: FlutterFlowTheme.of(context).secondaryText,
    size: 24,
  ),
  fillColor: FlutterFlowTheme.of(context).secondaryBackground,
  elevation: 2,
  borderColor: FlutterFlowTheme.of(context).alternate,
  borderWidth: 2,
  borderRadius: 8,
  margin: EdgeInsetsDirectional.fromSTEB(16, 4, 16, 4),
  hidesUnderline: true,
  isSearchable: true,
  isMultiSelect: false,
)

### Environment

```markdown
Flutterflow 3.10
Flutter 3.10.4
Android Studio Giraffe | 2022.3.1
Chrome
Windows 10
```

**Comment by hariprasadms** [comment]
Hi @colinriche - Thanks for submitting the issue. As you mentioned above multi select dropdown works fine in FF, I can confirm that is working in both FF and downloaded. As you are changing the code locally, I presume there could be something missing in the copied code.
I would advise making the same modifications inside of FF and downloading the code to test it out. I can confirm that It is not a bug.

**Comment by wenkaifan0720** [comment]
Hi @colinriche. This is because we recently added multi select support for the `FlutterFlowDropDown` widget. But the update will not be there if you directly copy code from FF to Android Studio. You need to download the entire code.
