### ISSUE TITLE
Folder Management Issues on Canvaskit using Chrome

### ISSUE THREAD

**Issue by EduardoGascaAP** [FlutterFlow/flutterflow-issues#1326]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Platform & Version: 3.1

Browser: Chrome 
Platform: FlutterFlow Canvaskit Subdomain
Description of the Issue:
Upon utilizing the new folder management system for project organization, I've identified multiple anomalies:

Folder Hierarchy Inconsistency: Child folders are mistakenly shown as parent folders upon creation within the main directory.

Drag-and-Drop Discrepancies:

Initially, pages cannot be added to the folder either via drag-and-drop or the "new page" function.
After a page refresh, the folder hierarchy corrects, but the drag-and-drop function remains inoperative. A second refresh is required to activate this feature.
Page Count Display Error: After adding files to the corrected folder, the displayed page count remains at zero. An additional refresh accurately updates this count.

### Expected Behavior

Expected Behavior:

Child folders should be correctly nested within parent folders without any manual refresh.
Drag-and-drop should be functional without the need for multiple page refreshes.
Page count should accurately reflect the number of pages within a folder immediately after addition.

### Steps to Reproduce

Steps to Reproduce:

Create a child folder within a main project folder.
Observe its placement as a parent folder.
Attempt to drag-and-drop or add a new page.
Refresh the page to rectify hierarchy and drag-and-drop function.
After dragging files into the folder, note the displayed page count.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEezPLl085Jn7xZ0LX5Ye1WjQMxQUQ5a50rlu1FGBYdGO6rP7AEYeLUaXdBZ8PiYAhMEGKZoGMK+NruktrDDew3H02Bf4d607t2VRWXZEWhabqqPLjhXnNDEdxUJnKy35+jnhV+VPh1dCEB6l+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I just want to use the folder correctly without refreshing the page

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/55267078/1e2b961a-b31a-4621-8b69-9593013d07c7)

### Additional Info

none

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:FlutterFlow
- Browser name and version:Crome
- Operating system and version affected: windows
```

**Comment by hariprasadms** [comment]
Hi @EduardoGascaAP - Thanks for submitting the issue. I can reproduce the issue. Thanks 

Folder issue - 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/bf944188-5053-4edb-b7fd-dfde56125a6a

**Comment by agreaves** [comment]
Hi @EduardoGascaAP, thank you for this bug report! We've been able to reproduce this issue and have finally generated a fix, which will be present in our next release! 🙂
