### ISSUE TITLE
String property not properly set in Dropdown

### ISSUE THREAD

**Issue by darin-olea** [FlutterFlow/flutterflow-issues#1327]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get an error when I create a dropdown.  Existing dropdowns don't show the error, but all new ones do.

String property not properly set in [dropdown name]

### Expected Behavior

Either no error or a better description of the problem.

### Steps to Reproduce

1. Create page
2. Add drop down - 

Padding(
  padding: EdgeInsetsDirectional.fromSTEB(0, 8, 0, 0),
  child: FlutterFlowDropDown<String>(
    controller: _model.meterStatusValueController ??=
        FormFieldController<String>(
      _model.meterStatusValue ??= 'Maintenance',
    ),
    options: [
      'Maintenance',
      'Pinned',
      'Survey Exception',
      'Survey Complete',
      'Quality Review',
      'Complete',
      'City Requests Removal',
      'Awaiting City Repair',
      'City Requests Reinstall',
      'Internal Maintenance',
      'Install Olea MHA Device',
      'Replace Olea MHA Device',
      'Remove Olea MHA Device'
    ],
    onChanged: (val) => setState(() => _model.meterStatusValue = val),
    width: MediaQuery.sizeOf(context).width,
    height: 50,
    textStyle: FlutterFlowTheme.of(context).bodyMedium,
    hintText: 'Meter Status/Maintenance',
    icon: Icon(
      Icons.keyboard_arrow_down_rounded,
      color: FlutterFlowTheme.of(context).secondaryText,
      size: 24,
    ),
    fillColor: FlutterFlowTheme.of(context).secondaryBackground,
    elevation: 2,
    borderColor: FlutterFlowTheme.of(context).alternate,
    borderWidth: 2,
    borderRadius: 8,
    margin: EdgeInsetsDirectional.fromSTEB(16, 4, 16, 4),
    hidesUnderline: true,
    isSearchable: false,
    isMultiSelect: false,
  ),
)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89god9J1s75bflF9WMXGDp+R+cv1+1xeCs8GojnPO0ESs+lYldUOLyjdH9AJFmGknoX/MrXhYf9OPddJgeVb7Y+1qpiSjzNXnOjVZDQO763b396I/5YfxW60cG7sxBSBLFfLWxh32etfOeuaAraGbX1IjMnFuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I can't publish, but I can download the project and it works fine locally.

### Visual documentation

Nothing to show besides the error

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web (developing on ubuntu)
- Browser name and version: Chrome 114.0.5735.133 (Official Build) (64-bit) 
- Operating system and version affected: Ubuntu 22.04
```

**Comment by hariprasadms** [comment]
Hi @darin-olea - Thanks submitting the issue. I looked at your project and tested above issue. It is working fine my projects. See below. What happens if you remove the dropdown and add new one with the option values ? Try this and let us know. Thanks 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/937549c8-4fea-4a64-89de-51cbfc854055

**Comment by darin-olea** [comment]
Recreating the drop down instead of copying from another dropdown in the project works.  It produces the following widget code:
Padding(
  padding: EdgeInsetsDirectional.fromSTEB(0, 8, 0, 0),
  child: FlutterFlowDropDown<String>(
    controller: _model.meterStatusValueController ??=
        FormFieldController<String>(
      _model.meterStatusValue ??= 'Maintenance',
    ),
    options: [
      'Maintenance',
      'Pinned',
      'Survey Exception',
      'Survey Complete',
      'Quality Review',
      'Complete',
      'City Requests Removal',
      'Awaiting City Repair',
      'City Requests Reinstall',
      'Internal Maintenance',
      'Install Olea MHA Device',
      'Replace Olea MHA Device',
      'Remove Olea MHA Device'
    ],
    onChanged: (val) => setState(() => _model.meterStatusValue = val),
    width: MediaQuery.sizeOf(context).width,
    height: 50,
    textStyle: FlutterFlowTheme.of(context).bodyMedium,
    icon: Icon(
      Icons.keyboard_arrow_down_rounded,
      color: FlutterFlowTheme.of(context).secondaryText,
      size: 24,
    ),
    fillColor: FlutterFlowTheme.of(context).secondaryBackground,
    elevation: 2,
    borderColor: FlutterFlowTheme.of(context).alternate,
    borderWidth: 2,
    borderRadius: 8,
    margin: EdgeInsetsDirectional.fromSTEB(16, 4, 16, 4),
    hidesUnderline: true,
    isSearchable: false,
    isMultiSelect: false,
  ),
)

I don't see a difference, so my guess there is still a bug there somewhere.. but I guess I'm no longer blocked, so...

**Comment by darin-olea** [comment]
I just saved my page with 25 existing dropdowns, and they all have this error now.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/142902002/8d2ccb2a-22eb-4d4b-9024-c90a2af476ee)

I do not want to have to redo all of these.  Please investigate this issue.

**Comment by hoisel** [comment]
I have the same issue

**Comment by jaded0** [comment]
still happening

**Comment by waltartist** [comment]
This is happening for me too

**Comment by tartarugadf** [comment]
This is happening for me too but with textfield "String property not properly set in Textfield"

**Comment by mdrashedbinkuddus** [comment]
@tartarugadf check your autocomplete option. If you set autocomplete for text field and then copy it over other page then just remove the value before turn off autocomplete

**Comment by appach22** [comment]
@hariprasadms In the end this looks like a bug. Copying dropdown from other pages leads to error.

**Comment by GSANCHESAV** [comment]
This is happening for me too

**Comment by htsnet** [comment]
I have the same issue. I tried to make the label and value dynamic and the FF said about a string misconfigured on label. 
I removed the original Dropdown widget and recreated, exactly equal. It worked.

**Comment by charliefabley** [comment]
Me too

**Comment by Nvsuhail** [comment]
Years old bug it is! But the case is closed... Why?
