### ISSUE TITLE
Chart - Cannot rename data series

### ISSUE THREAD

**Issue by lucacox** [FlutterFlow/flutterflow-issues#1328]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding a data to a line chart, I am not able to modify its name. It remains always "[Line] Chart Data 1"

### Expected Behavior

When changing the name of a line chart data series, it should change

### Steps to Reproduce

1. Add a Chart widget to a page
2. Add a data series
3. Try to rename it with the rename (pencil) button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhufl/ot1xMtD7YSIYcZVnjk4NnkcTb4zjdZxa0ghfePxEYkcP8zRP1FLYteDe3x9Plf+pD0e3MKMuN7lEsEEAw2rG5s4zZRXQTzKWkemVYiMCc3pfEZ7NJpUfXaE1KaJpCN4GMtoLEYu12GufvCdG3qCf9qOYwx5e6fDbOY=

### Context

I was trying to rename the data series

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1597231/c046c290-86b7-4625-8f85-dc1b5f3ca724)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Mac
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: MacOs 13.5.1
```

**Comment by SameerShahzad99** [comment]
@lucacox Thank you for submitting this issue, i was able to reproduce it on my end!

**Comment by aemelyanovff** [comment]
Fixed in the next update.
