### ISSUE TITLE
Custom widget used in pages has default wrapper of fixed color

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1330]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a custom widget in a page FF is wrapping in in a container, mainly for width/height reasons... However the container has a background of a solid color, where as it should be transparent
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/014c91ad-3caa-4ee6-9954-985449b107b3)
It is totally messing up designs if trying to have a customer widget on a gradient or image background.

### Expected Behavior

for a container to be transparent as it is totally messing up designs if trying to have a custom widget on a gradient or image baCKGROUND

### Steps to Reproduce

create page with a gradient or image background
Create a customer widget (or based on one in pub.dev, with a transparent background)
place widget on page
run, you will see widget with a solid background as the widgets transparency is over the top of the solid wrapper that FF adds.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocBH7pDMbMFAhQMkQzM6bZI7ku1EdwEhNb7xP5oTOs/8akhLYtejdEFEBFSjvH4x+MLXiePfFe5dNQ6bfIRy1ZRXQQLMQj2tMsSaDc2oXEYlP8JgIHKw06aVvQpAJfhhcUYtwUz7F/CdG3qCf9qOYwx5e6fDbOY=

### Context

breaks the design, cannot use custom widgets on gradient or image backgrounds.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/f4ce0ec2-7d4f-4cb2-834f-1b03a0ee6644)
 A = Wrapper color, not from the widget or the page.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for submitting the issue. I looked at your project and custom widget code. You got the custom widget start with scaffold widget which is not correct. It should be wrapped with a container as FF page already got scaffold widget as a parent widget. It looks like there are widgets overlap in the custom widget. I would suggest play around the widgets and wrapping with a column and set _mainAxisAlignment: MainAxisAlignment.center,_ and so on. It should work as you expecting. I can confirm that it is not a bug.

I just made some changes around custom widgets and scaffold background colour. It looks as below now. 
 
<img width="397" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/7d6c507e-9671-4a8f-8e5a-033c7bf933e9">
