### ISSUE TITLE
Push Notifications are not displaying selected page

### ISSUE THREAD

**Issue by arielramos** [FlutterFlow/flutterflow-issues#1331]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I send a push notification (instantly or scheduled) the user will click on it a go to an specific page, but, in Android and iOS this is no working in a specific condition:

The thing is that this issue will appear if the app was already running (I don't mean that the app is displayed in the cellphone), I mean that the app was opened and you are doing something else, if you receive the notification in that momento and you clik on it you will be sent to your home page.

But, if your app was closed and you received the push notification, the specified page will be displayed.

### Expected Behavior

The user will receive the push notification and the specified plage will be displayed, no mater if the app was opened or closed, and by "opened" I don't mean that the app is displayed in the screen, it is running in the background.

### Steps to Reproduce

1. Create a push notification (instant or scheduled) and select an specific page to be displayed when the user tap on the notification.
2. Send the notification, but before that, the app has to be already opened and you have to be on another app like your social media or email.
4. If you tap on your push notification, the home page will appear.
5. If your app was totally closed, you will be sent to the page that you specified in step 1

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Any widget will work

### Context

My project is: https://app.flutterflow.io/project/pepper-health-limitada-919uf1

### Visual documentation

-

### Additional Info

-

### Environment

```markdown
- FlutterFlow version: V 3.1
- Platform: Mobile iPhone 14 pro max and Samsung Galaxy S22
- Browser name and version:
- Operating system and version affected:  iOS and Android
```

**Comment by hariprasadms** [comment]
Hi @arielramos - Thanks for submitting the issue. I have tested above steps. I can confirm that it is working as intended in both the scenarios while the programme is closed and running in the background. I presume there could be something missing around the push notification settings. Please have a look. If problem is persisting, share a quick video showing the issue. Meanwhile you can reach technical support team to get support on this. Thanks

**Comment by arielramos** [comment]
Hi @hariprasadms Thank you for your quick response, I dont know why, but today is working, I repeated the same tests and it's showing the specific pages.

Thank you
