### ISSUE TITLE
Web Push noifications are not showing up

### ISSUE THREAD

**Issue by arielramos** [FlutterFlow/flutterflow-issues#1332]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I made some apps that uses push notifications, they are showing up and that's awesome, but I deployed also a web applitacion in order to allow customers to have the mobile app and the browser version, but the browser is not showing the push notifications. Does FlutterFlow support that feature or it is just for mobile?

I set up my firebase and web certificate, APNs an the other configurations in Apple Developer account, also my browser is configured to not block push notifications

### Expected Behavior

Show Web Push Notifications in browser

### Steps to Reproduce

1. Deplay your app as a Web App
2. Send a push notification to see if it appears in the computer

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

-

### Visual documentation

-

### Additional Info

-

### Environment

```markdown
- FlutterFlow version: V 3.1
- Platform: Web
- Browser name and version: Chrome macOS Version 114.0.5735.106 (Official Build) (arm64)
- Operating system and version affected: MacOS Ventura 13.5
```

**Comment by sistemagro** [comment]
@hariprasadms Hi, is this still unsoported?
