### ISSUE TITLE
Flutterflow is displaying that scholarship licenses are expired

### ISSUE THREAD

**Issue by arielramos** [FlutterFlow/flutterflow-issues#1333]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hope you are well

Students in Fidelitas University (domain ufide.ac.cr) received their scholarship license in May 2023, but today, many of them told me that their scholarship license expired, it could be a bug, but as far as I know, this license lasts one year, for example, the following users are having this issue:

lsegura70860@ufide.ac.cr
ecubero10043@ufide.ac.cr
jherrera80446@ufide.ac.cr
vchacon80627@ufide.ac.cr
avillarreal30809@ufide.ac.cr

This issue is not hapening to students that received their license in January 2023.

I think that there was something in the last update that changed the expired date, this week they are having their final project presentation and need to complete their apps. Could you please help us?

### Expected Behavior

Scholarship licenses need to be active for one year for students that received them in May, but they expired today

### Steps to Reproduce

1. Open any of the users with domain email (ufide.ac.cr) that acivated their scholarship account in may 2023
2. Check the license expired date, it should be one year, but expired today august 22nd

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No Bug report

### Context

Fidelitas University is using FlutterFlow to teach about Mobile Development in our carrer "Computer Science", currently we have +-200 students that used scholarship licencise in FF, currently we need help because the students that receinved their licence in May 2023 expired today august 22nd

### Visual documentation

![480751c546013a451212990591749c645e16f33514be603a6e34677dfc929066](https://github.com/FlutterFlow/flutterflow-issues/assets/11698932/4b2af613-fc3b-41f9-bb3f-cf4abf095b19)

### Additional Info

-

### Environment

```markdown
- FlutterFlow version: v 3.1
- Platform: Desktop
- Browser name and version: Chrome and Safari
- Operating system and version affected: Windows and MacOS
```

**Comment by hariprasadms** [comment]
Hi @arielramos - This is not a FF issue. This is related to support team query. I would suggest reach FF support team using email contact or chat option to get it checked and resolved. Users who are experiencing issues with FF functionalities can post them here.

**Comment by arielramos** [comment]
> Hi @arielramos - This is not a FF issue. This is related to support team query. I would suggest reach FF support team using email contact or chat option to get it checked and resolved. Users who are experiencing issues with FF functionalities can post them here.

Thank you!

**Comment by davidflutterflow** [comment]
Hi @arielramos, I couldn't locate your Flutterflow account. Please email us at support@flutterflow.io and we'll investigate the issue. Ping me once you've sent the email.

**Comment by arielramos** [comment]
Hi @davidflutterflow The issue appeared to my students last week, I told them yo contact support via email to receive the assitance, thank you for your follow up
