### ISSUE TITLE
App bar goes missing in iPad portrait mode.

### ISSUE THREAD

**Issue by ramsaicharan** [FlutterFlow/flutterflow-issues#1334]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"App bar" at the top goes missing in iPad portrait mode. faced the issue in flutterflow test mode, published mode tested it in chrome responsive viewer, and also faced the issue in real device. I have installed the app on iPad using TestFlight

### Expected Behavior

App bar is visible at all the times

### Steps to Reproduce

1. Create a new page with app bar
2. Run the app to go to test mode
3. Select iPad, iPad Air, iPad mini, or iPad Pro 11".
4. You can see "App bar" at the top is missing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeivHlz8tItb1J0bncacdoqwMxQUw4apA3iuxFGA8cF7b3ELAcZ87EaXdZXPWcTGNiG1q0rGYypqHmk/zlDcI7GxWVc6F607tuTwriJDunV4zXEpOCYHNfI/xbfxGc0bW3qxJ+PbNadHgF7V+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

The app bar is missing and I can't tap on back button on App bar.  or perform any actions that can be performed on App bar, such as tapping on the text in app bar to go to a page or going back or showing user the Page in which they are in

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/18374140/8137ff96-cbcc-4f24-b971-90af4d117b2d

https://github.com/FlutterFlow/flutterflow-issues/assets/18374140/270ed2ca-248b-4507-a121-7b1463a48beb

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, iPad OS
- Browser name and version:  Chrome 116.0.5845.96 (responsive mode set to iPad)
- Operating system and version affected: macOS 13.5.1 (22G90), iPadOS 16.6
```

**Comment by hariprasadms** [comment]
Hi @ramsaicharan - Thanks for submitting the issue. I looked at your project. you do not see the app bar in ipad mode because you got app bar responsive setting as below. Change the setting and see how it works. 

<img width="915" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/70ce9ad0-9f21-4ee0-a3c9-304e752042f5">

After switch on ipad responsive settings. 

<img width="486" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/41662fd9-4885-4575-a232-730a019c5023">

**Comment by ramsaicharan** [comment]
Oops, Thanks. This was the issue. I spoke to customer support earlier and they asked me to raise a bug and hence I did. 

Thanks for pointing it out.
