### ISSUE TITLE
Json path bug

### ISSUE THREAD

**Issue by lammworks** [FlutterFlow/flutterflow-issues#1335]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am calling a WIX API and the Flutterflow tool for mapping the json path is not recognizing a valid path.
Valid path $.contact.info.extendedFields.items.[custom.area] should bring "SAN" and it brings a null.

The API response body:
`{
"contact": {
"id": "216d7149-c9db-47a2-8201-d341a768c409",
"revision": 18,
"source": {
"sourceType": "THIRD_PARTY",
"wixAppId": "0d6fc425-208c-46fc-96c3-76dc7ee145c3",
"appId": "0d6fc425-208c-46fc-96c3-76dc7ee145c3"
},
"createdDate": "2023-08-01T19:16:00.984Z",
"updatedDate": "2023-08-17T11:13:56.528Z",
"lastActivity": {
"activityDate": "2023-08-12T16:40:37.697Z",
"activityType": "ECOM_PURCHASE"
},
"primaryInfo": {
"email": "[diegoc@gmail.com](mailto:diegoc@gmail.com)",
"phone": "65503337"
},
"info": {
"name": {
"first": "Test",
"last": "Cordero"
},
"emails": {
"items": [
{
"id": "952d3535-81e6-4d43-a488-9200c2eb64e1",
"tag": "MAIN",
"email": "[diegoc@gmail.com](mailto:diegoc@gmail.com)",
"primary": true
}
]
},
"phones": {
"items": [
{
"id": "07cc9d24-fc4a-48cf-b9fe-7afa6fc9f160",
"tag": "MOBILE",
"countryCode": "PA",
"phone": "65503337",
"e164Phone": "+50765503337",
"primary": true
}
]
},
"addresses": {
"items": [
{
"tag": "HOME",
"address": {
"country": "PA",
"subdivision": "PA-8",
"city": "panama",
"addressLine": "PH Arboleda APT14a",
"addressLine2": "Calle primera parque lefevre",
"formattedAddress": "PH Arboleda APT14a, Calle primera parque lefevre\npanama, Panamá\nPanama",
"countryFullname": "Panama",
"subdivisions": [
{
"code": "8",
"name": "Panamá",
"type": "ADMINISTRATIVE_AREA_LEVEL_1",
"typeInfo": "province"
}
]
}
}
]
},
"labelKeys": {
"items": [
"contacts.customers",
"custom.limpieza-1-cuarto-1-bano"
]
},
"extendedFields": {
"items": {
"contacts.displayByLastName": "Cordero Test",
"invoices.vatId": "",
"custom.area": "SAN",
"emailSubscriptions.deliverabilityStatus": "NOT_SET",
"emailSubscriptions.subscriptionStatus": "NOT_SET",
"emailSubscriptions.effectiveEmail": "[diegoc@gmail.com](mailto:diegoc@gmail.com)",
"contacts.displayByFirstName": "Test Cordero",
"custom.zona": 1
}
}
}
},
"responseType": "REGULAR"
}`

### Expected Behavior

SAN

### Steps to Reproduce

1. Create an API Call to https://www.wixapis.com/contacts/v4/contacts/[WixID] (or similar)
2. in the "response and test" page, test the api and go to JSON Path to map the response
3. Add a new json path "$.contact.info.extendedFields.items.[custom.area] "

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Trying tu use the response of my store backend API.

### Visual documentation

https://share.cleanshot.com/QTYfM1YP
https://share.cleanshot.com/3k5GMQd8

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: web
- Browser name and version:chrome Version 115.0.5790.170 (Official Build) (arm64)
- Operating system and version affected: OSX
```

**Comment by hariprasadms** [comment]
Hi @lammworks - Thank for submitting the issue. Can you please share the bug report code of the project?
Also, in the given screenshot below, where error is displayed i do not see path is not starting from _$.contact_. is this missed out or expected?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/5aa7acff-31e4-4ae6-91cd-e9293e616cd0)
