### ISSUE TITLE
grey screen in TestFlight 

### ISSUE THREAD

**Issue by jaburton111** [FlutterFlow/flutterflow-issues#1337]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created test builds for my app using code magic. However, while testing in TestFlight several key screens are replaced with a grey screen of death. The strange thing is, it doesn't happen all the time, just most of the time. This issue does not occur in FlutterFlow test or run mode. Here is a clip of what I'm talking about:

https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/5e12aeaf-f368-43c1-92d0-46fbad982727

There are some occasions where the grey screen takes up part of the screens, as in the following:

https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/1656aac9-8021-472a-b4e8-56767e6bbc03

### Expected Behavior

The expected behaviour can be seen in the following clip, which is how the app functions in FlutterFlow test mode:

https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/4fc65836-cc6b-40de-8428-843997b96c86

### Steps to Reproduce

The steps to reproduce this issue are unclear. I can give you access to my TestFlight app to experience the behaviour for yourself. Beyond that, the error is happening somewhere between the code and flutterflow and the final build in TestFlight.

This can be recreated by exporting a build of my app into TestFlight and navigating to said screens. As to what exactly is causing the error, or where it is originating, I have no idea.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejvLluJZNpbxa7rrULMd4lQMwJ0QlUIInj+0bWRMhfbHmB7AtdvfBVElLYte+fWN+OGejuz4ypfzNjvHpN/BeBzWdGqp4/q5XQRfwZGWuRbqnDZaeOn9RJ+JMFXawy8Cn2SVSHM5iSUIa3FzzJfCdG3qCf9qOYwx5e6fDbOY=

### Context

This issue is making my app unusable in a real world testing environment. 

### Visual documentation

na

### Additional Info

flutterflow project url > https://app.flutterflow.io/project/jambi-cdiyw6

There are a number of backend calls where this is happening, but the two main calls for which I am getting the grey screen are:

page > artistDetails
https://x6om-fdfm-vpzd.n7c.xano.io/api:Xy6miFrZ/getUasRecord
https://x6om-fdfm-vpzd.n7c.xano.io/api:Xy6miFrZ/artistAlbums

page > ArtistDashboard
https://x6om-fdfm-vpzd.n7c.xano.io/api:Xy6miFrZ/getUasRankings

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:MacOS Desktop
- Browser name and version: Chrome Version 115.0.5790.170 
- Operating system and version affected: Ventura 13.5
```

**Comment by hariprasadms** [comment]
Hi @jaburton111 - We appreciate you bringing this up. Can you test the code locally on iOS or Android simulators to check what issue you get when you see that grey page? Investigating this one is a little difficult because it works properly in run and debug modes.

Also update the issue with Api/backend details, page and component names in the project which is causing the issue.

**Comment by jaburton111** [comment]
Hi @hariprasadms ... I struggled with setting my machine up to do local simulation testing, so I don't know if I would get the same results there. I will try to go through that process again and let you know the results. Will that tell us something? Whether the same issue happens or does not happen in a simulation, will that help us zero in on the cause?

In the meantime, I have updated the details above to include some more information about the pages, backend calls, etc. associated with the grey screen error. Please let me know if there is more information that will help with troubleshooting.

**Comment by jaburton111** [comment]
Hi there @hariprasadms. I can confirm the issue is present when using a simulator locally, as you can see the attached images. Every time you navigate to an artist detail page the same error appear: "type 'int' is not a subtype of type 'double?'. Which I assume is a clue to what's happening here?

![Simulator Screenshot - iPhone 14 Pro - 2023-08-29 at 17 15 29](https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/ed5d902a-bd20-4fb2-a885-f694075ca88e)

Note, the same error occurs often on the Albums tab but not all the time.

![Simulator Screenshot - iPhone 14 Pro - 2023-08-29 at 17 14 52](https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/def77dc3-44cc-45f5-b6bd-8b3690242cbf)

![Simulator Screenshot - iPhone 14 Pro - 2023-08-29 at 17 15 14](https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/e0671931-ec4a-49c3-9ebf-b61f89203f96)

You may also notice that the UI colours are completely wrong when running in the simulator. You can see when comparing to the images above what the app is supposed to look like. Strange that the colours show up correctly in Test Mode and Test Flight but are all wrong in Run Mode and this simulator. This may be a separate issue but one also needing desperate attention.

**Comment by jaburton111** [comment]
@agreaves , @SameerShahzad99 ... I notices you are both assignees on this ticket, so just wanted to check in. I haven't seen any additional input on this since I added the requested info.

**Comment by agreaves** [comment]
Hi @jaburton111, thank you for the additional details. When you see this type of issue, it's almost always that somewhere in your app you're getting a Double value from an API that you are using as an Integer. It looks like these values are coming from an API, so when you are debugging it locally, try to look in the Debug Console and see exactly where the error is occurring in order to determine where best to fix it in your app.

Unfortunately, this issue seems to be specific to your project, whereas this issue tracker is intended for general bugs that are applicable to all users, so I'm closing this as a support request at the moment. I'd recommend you continue to search the source of the issue locally, but you can also use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/) for additional assistance.

Hope the above info helps!

**Comment by jaburton111** [comment]
Thank you @agreaves . I can go back to support, but just a thought: Is it not strange that this error only happens in the simulator and not in Test or Run mode in FlutterFlow? Would that not seem suspicious and be considered a bug if test mode and run mode are telling me everything is fine and the app becomes virtually unusable in a simulator? I understand the simulator can test some things that test/run mode can't, but this doesn't seem like it should fall into that category. No?

**Comment by jaburton111** [comment]
@agreaves , also, what about the fact that the colour scheme presents totally differently in run mode than it does in test mode? You can see this in the images above. The weird white and grey pics are from run mode and pics with the regular dark colour screen are from test mode. Nothing else changed.I understand this may warrant a separate ticket, but would this be considered a bug?

**Comment by agreaves** [comment]
Hi @jaburton111, I can provide the technical reason for why you only see this on device, and not Run/Test mode. It's because Test mode is the compiled Web version of the app, which uses JS under the hood, and `int` and `double` are represented by the same underlying type so there's no error converting between the two. However on iOS/Android this is not the case, and you can't simply cast a `double` as an `int`. So this isn't so much a bug as it is a quirk of being able to run on different platforms.

As for the color scheme difference, I'm guessing this is a Dark vs Light mode difference, but I'm not sure of course without taking a closer look.

Hope this helps!

**Comment by jaburton111** [comment]
@agreaves , thank you for this. This is helpful. I have a follow-up question if you are willing to indulge me.

First, regarding the colour scheme, I assume you are right that it is a default light mode it is resorting to in both run mode and in the simulator. However, as you can see in the image below of run mode, it says it's in dark mode, and if you switch to light mode, the colours stay the same and just the screen background becomes white.

<img width="997" alt="Screenshot 2023-09-17 at 3 24 14 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/7454bd96-2361-4c37-8706-99d9ce914647">

Regarding the type error, after a bit more trouble shooting I believe I know which data are generating the error. I trouble is, I am not aware of anyway in FlutterFlow to resolve the issue.

I am using Xano as my backend. The data that are causing the error is a series of decimal numbers (and their type is set as decimal numbers in Xano) which are a result of a calculation on the backend. The problem is, when this calculation results in a whole number (or even just a zero) FlutterFlow reads that as an integer regardless of what the type is set as in Xano. Here is a snapshot of some of the data:

<img width="1378" alt="Screenshot 2023-09-18 at 8 26 43 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/137405470/36a7395f-6f36-470b-a9bd-472bea3eeadf">

The record above will show up fine because every field is showing decimals, but the record below with throw an error because one field remains as zero.

I thought of trying to correct this with a code expression using .toDouble() so the '0' is read as '0.0', but since a code expression requires you to set the type before the data can be processed I can see any way to do this.

I apologize if I should be going to support with this instead, but you seem to have more insight here and it doesn't seem right that there wouldn't be a fix. And my app can't function if there isn't a fix.

Does this make sense? And do you have a suggestion for how I could resolve this?

**Comment by Krishna-05012000** [comment]
![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/103092316/aa3a8fb3-b155-4bd0-a0aa-9d55167a09a0)
![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/103092316/a240b2e5-2dbf-4ddd-9e6e-5c36b59a5ded)

The same issue for me alsooo..In test the colour background is different and dark
