### ISSUE TITLE
DatePicker widget issue

### ISSUE THREAD

**Issue by FarheenAnsari-dev** [FlutterFlow/flutterflow-issues#134]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The Date picker should open a dialog and from date and time should be selected 

## Current behavior (required)

Nothing happen on action with DatePicker action

## To Reproduce (required)

1.
2.
3.
4.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by organicnz** [comment]
Hi @FarheenAnsari-dev, could you pls add reproducible steps :)

**Comment by organicnz** [comment]
@FarheenAnsari-dev, have you seen the documentation by any chance? :)

https://docs.flutterflow.io/actions/actions/ui-interactions/date-time-picker

**Comment by FarheenAnsari-dev** [comment]
Hi,

I have added a new button with date picker action. Now, it's working fine.


Thanks

________________________________

**Comment by organicnz** [comment]
That's great, mate. Glad you got that sorted out :)
