### ISSUE TITLE
Conditional Builder: Copy and paste in widget tree doesn't work as expected

### ISSUE THREAD

**Issue by mobyjames** [FlutterFlow/flutterflow-issues#1340]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Copy a widget from within a condition section that is hidden
2. Paste the widget somewhere else
3. Nothing happens

### Expected Behavior

1. Copy a widget from within a condition section that is visible OR hidden
2. Paste the widget somewhere else
3. Widget is pasted as expected

### Steps to Reproduce

1. Create a blank project
3. Add a Conditional Builder to the Column in the default page
5. Add a text field to the "If" section
6. Hide the "If" section and reveal the "Else" section
7. Attempt to copy and paste the text field from the "If" section to the "Else" section.
8. Observe nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TlcmAvJRNrt9A1s+NccFB/TkRJmY8U5Irm8N+a0kjNurpOrN+OsmlU3FJXMu4d2xUJGH8sGAIpqmPuIfpFfkCFw2IQ75CyMx2exXNUTulMYywPLueWkd8M5hMG0zC06COiiZSPbJ1dVIAw1+AOuyREwPDQLLoPUcsAM//WJLAnHOrGhDCUjh2tmNecCfn

### Context

Slows down development when using Conditional Builder.

### Visual documentation

<img width="369" alt="Screenshot 2023-08-23 at 3 02 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1327007/e9eff0a3-3de5-4eaf-acb9-db44fdf61221">

### Environment

```markdown
- FlutterFlow version: 3.1 (released Aug 22, 2023)
- Platform: Any
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: MacOS 13.4 (22F66)
```

**Comment by wenkaifan0720** [comment]
Hi @mobyjames. This is the expected behavior as of now. The widget has to be visible in order to be able to be copied. I think this is something we might want to reconsider, but I would not mark it as a bug.
