### ISSUE TITLE
Error message "value is not properly set" on nullable parameters (custom widget)

### ISSUE THREAD

**Issue by matlin76** [FlutterFlow/flutterflow-issues#1348]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get an error message that "the value is not properly set" even if it's a nullable parameter.
I have tried using null safety in both the constructor and in the build method but nothing helps.

### Expected Behavior

I expect only the required parameters to be required.

### Steps to Reproduce

- Create a new custom widget.
- Add one required parameter. 
- Add one or more nullable parameters.
- Take care of the null safety in the custom code.

Use the custom widget on a page and only add value to the required parameter.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cj8nqy4x2obxc1pPqacFvryQsIjs/RYIsmMJEbwkaHZPND+x/esnRQFJuZ9OrdghIemCJvHMzzNKMm9z1JsArHzCdQIB4+ahhFwr/UXGiabaqC5GeeX9uGshnBX6PyLTYgRJ4IvVpLVFlw02Le++yaBLAJabSOEUzAuaLIoTXmAfuQ0SLb3kNh1JWeC/v

### Context

Build custom widgets that my team can drag and drop and use without the need to fill in all parameter values.

### Visual documentation

![Screenshot 2023-08-24 at 19 06 45](https://github.com/FlutterFlow/flutterflow-issues/assets/22887602/8e0cd1f3-f543-4de0-9444-dc5a09e11129)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 116.0.5845.96
- Operating system and version affected: Mac OS Ventura 13.4.1
```

**Comment by jasonNumar** [comment]
The issue also seems to be happening with custom data types.
<img width="294" alt="Screen Shot 2023-08-24 at 8 51 02 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/129347853/e6c2b21d-7afb-4310-856b-c71c0cba50d4">

**Comment by agreaves** [comment]
Hi @matlin76, thank you for the bug report! This was generally there to make sure people don't forget to set values for custom widget parameters, however I agree the above issue is much worse. This will be fixed on our next release! 🙂

**Comment by DrPenguinn** [comment]
Nope! It's not fixed yet. The issue still exist when trying to set a nullable optional icon param in a custom widget. :(

**Comment by felipemontero** [comment]
not fixed yet. I have a custom action for creating a json as variable for an api call, because the json body also can't handle null value on an api call. So the workaround also needs a workaround.
Not good FF

**Comment by TahaHamad** [comment]
I agree with @felipemontero , we need a fix to this please :)
I removed a whole functionality from my app because of it

**Comment by kantarse** [comment]
This issue is still NOT fixed. The only change is that the field is not called "nullable" any more, but "required". Even when I set a **not required**, Flutterflow refuses the build because of missing parameter.

**Comment by sabatage3** [comment]
Any updates here? The issue persists. What's the point of having nullable variables if FlutterFlow forces us to set a value?
