### ISSUE TITLE
Action "On phone shake"

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#135]
This action works very badly

First of all, this action is very sensitive. Tilt the phone a little and it works. Reduce the sensitivity of the sensors.
Secondly, this action works not only on the screen on which the setting is located, but also on all other screens, except for those that I go to from the appbar

Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## To Reproduce (required)

1.
2.
3.
4.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by katherineqian** [comment]
Hi @oper2k , 

Thank you for your submission! In order to be fair to all users who submit bug reports, we ask that you fill out the required information in the report template. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by agreaves** [comment]
Closed due to inactivity
