### ISSUE TITLE
No ability to change visibility of PageView Page. Empty Dropdown

### ISSUE THREAD

**Issue by ancientgreys** [FlutterFlow/flutterflow-issues#1350]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Despite a dropdown header, there is no ability to change the visibility settings of a PageView Page. Opening the "Visibility" header while the PageView Page is selected results in just an empty space.

### Expected Behavior

There should be options to change the visibility of a PageView Page (I believe, otherwise why is there a "visibility" header?).

### Steps to Reproduce

1. Create a page
2. Create a PaveView Widget
3. Create/select a PageView Page
4. Click the "visibility" header

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkPLl8ZJIsbRF7q6Jae5VliM4C08cTrk/kdZ+bxQYCOPtBJkQdvukaklWONPidglpfGagrzk1+srMm9z1FMc5OQ2YbNlhzJZ+WzrMTlOQRZipC8yaREd+GshnGhG04beFhR1DA/phc1oZ2F2XNuqUTnPfK6bQOlgdHv6IWN/XvgfuQ0SLb3kNh1JWeC/v

### Context

I am trying to display the images for a listing, however there can be anywhere from 4-9 images being referenced for the listing. If there are only 4 images for the listing, I do not want there to be 5 or more PageView Pages, they would result in empty images and all the indicator dots would still be visible. However is there are 9 images, I need all 9 PageView Pages visible.

### Visual documentation

<img width="1440" alt="Screenshot 2023-08-24 at 6 36 18 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/98117906/92c5c688-767d-43f9-ab97-2128bb9ecea2">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: MacOS Desktop, iOS, Android
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: MacOS Ventura 13.4.1
```

**Comment by sbis04** [comment]
The empty Visibility section seems to be a UI bug on our end, but we actually don't support visibility on the PageView Pages. I think for what you are trying to achieve here, you should be either using "Backend Query" or "Generate Dynamic Children" on the PageView widget so that the number of pages are determined based on the query.

**Comment by sbis04** [comment]
The UI bug should be fixed in the next update!
