### ISSUE TITLE
Can not login community.flutterflow.io

### ISSUE THREAD

**Issue by sunjianan9900** [FlutterFlow/flutterflow-issues#1351]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I can't log in with flutterflow's email password, what should I use? There's no registration either
You can log in to flutterflow with your email password, but not to the community.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10936316/18664a5b-1e2f-486c-8369-696b49199ab3)

### Expected Behavior

I want login

### Steps to Reproduce

1.create flutterflow account
2.login flutterflow
3.You're surprised to find there's no login and you can't log in community.flutterflow.io

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

None

### Context

can not login

### Visual documentation

None

### Additional Info

none

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): macOS Monterey 12.2.1
```

**Comment by sunjianan9900** [comment]
I logged into the community to ask a question, and it would be great if anyone could stop by and answer me here.
flutterflow How to edit AndroidManifest.xml?
I want to add a meta-data into it:
<meta-data
    android:name="com.baidu.lbsapi.API_KEY"
    android:value="AK" />

**Comment by pooja-ff** [comment]
@hariprasadms is correct! You can automatically login via your FlutterFlow editor. For more information, check out the steps in the [documentation](https://docs.flutterflow.io/miscellaneous/additional-resources#flutterflow-community-forum)

**Comment by sunjianan9900** [comment]
That's exactly how I found this community, but Not work

https://github.com/FlutterFlow/flutterflow-issues/assets/10936316/0313acff-3b16-40ae-8829-fbb7dd2fd31a

**Comment by pooja-ff** [comment]
Does the same thing happen when you do it from the Resources tab of the FlutterFlow home page?
