### ISSUE TITLE
Passing data to another page issue in TestMode, RunMode works

### ISSUE THREAD

**Issue by genyys** [FlutterFlow/flutterflow-issues#1353]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

passing data to another page not working in TestMode, but RunMode works fine the same page

### Expected Behavior

passing data must be working in TestMode, like maybe two days ago

### Steps to Reproduce

1. from page "Titulinis_loggedIn" ListView
2. to page "UserPage"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol8nfsM9NsdtJ+Kr2b8BKpyQXHDMibb87lspBazwbfe+uB4kqevfOTERCXfarYWxpPkyar2oW0NL8iODpDMJeOQmdRtlI+bpAZwmWTk+haaaXFJWgeGsmJ+dbGm674cKJqhB/LrB2W01mwzuYDNmXY3LAGITUDm1NDq/LZO4=

### Context

when i click my project in TestMode and try to pass data to another page, i see blank page. when i RunMode my project, thank everythings fine. Few days ago everything worked fine.

### Visual documentation

list view
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/143159101/9f3f9aaa-916b-4f9a-a4e5-785e3a4139b0)
to another page
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/143159101/aefff0f8-371f-4c58-b5ec-f822d59ff7f1)

### Additional Info

RunMode the same page works fine

### Environment

```markdown
- FlutterFlow version: 3.10.4 (released august 25)
- Platform: web, mobile
- Browser name and version: chrome 115.0.5790.110 versija (Oficialiai pagaminta) (64 bitų)
- Operating system and version affected: windows 10
```

**Comment by hariprasadms** [comment]
Hi @genyys - Thanks for submitting the issue. I looked at your project and above pages. I there data is passing to next page. but UserPage got layout rendering issues. Hence it is showing blank page. Keep UserPage layout simple so it should work fine. 

See below,

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/100e1798-b3ce-4ff8-88b4-5a1c8de75d77
