### ISSUE TITLE
Vertex AI package cannot be imported due to conflicting dependencies

### ISSUE THREAD

**Issue by Shokhrukh99** [FlutterFlow/flutterflow-issues#1354]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to compile the code of a custom function I get the following error: 
`Failed running flutter pub get...
Because every version of vertex_ai depends on http ^1.1.0 and image_picker_platform_interface >=2.0.0 <2.6.4 depends on http ^0.13.0, vertex_ai is incompatible with image_picker_platform_interface >=2.0.0 <2.6.4.
So, because custom_widget depends on both image_picker_platform_interface 2.6.2 and vertex_ai ^0.0.4, version solving failed.
`
It turns out that there is a conflict in http package version which is used by image_picker and vertex_ai. 
I need the vertex_ai package. How can the issue be resolved?
Thanks in advance.

### Expected Behavior

When compiled the package must be added with no conflicting errors

### Steps to Reproduce

1. Go to custom actions section
2. Try to add vertex_ai package and all of its dependencies
3. Compile the code
4. Observe the versioning issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i/Hl2491xMtD+Kr2b8BFoCMXQls7R4EniexuawE8KOPdOoYUP8+kM0RtOP2iSnxceWaGo2oW0vzIjYXlK+1cEE2qf4hz+ah2Zg6UQlGhMoTXFJWgWmglRPFVCnaA5LW3ux4kA7JuciFh6mCmPPOtEw7tQe/uDkQWDa/LZO4=

### Context

I'm working on a project that includes the implementation of Vertex AI online prediction tasks. 
For that to work I created a custom action and added the vertex ai package and all of its dependencies. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/460d9218-ad4a-43b1-8ad9-da85d9b771ca)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/65f678cd-578f-4e78-8652-55c57f487d72)

### Additional Info

This is the link to the package: [vertex_ai](https://pub.dev/packages/vertex_ai)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Google Chrome 116.0.5845.110 
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Shokhrukh99 - Thanks for submitting the issue. As it is related package dependency upgrade, It can be a feature request. Please submit this issue as request using feature request form under help section. This is not a bug.

**Comment by Shokhrukh99** [comment]
Hi, @hariprasadms - Thanks for reviewing the issue. I overcame the issue by using Palm API instead of a package. But it would be great to have the ability to access and edit the project's pubspec.yaml file to be able to configure versioning of the packages.
