### ISSUE TITLE
Dynamically Generated Choice Chips Doesn't accept Single Value from JSON

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1357]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://drive.google.com/file/d/1Xd97x9DLuei5LCx88SF6_A31V1G_eZhS/view?usp=sharing

### Expected Behavior

I expected my choice chips to be mapped in one of the following ways as shown in the video

### Steps to Reproduce

1. Create a Component with choice chips
3. Create a Blank Page
4. Add List View with Choice Chip Component
5. Dynamically Generate with JSON **[JSON provided]**
6. Pass children's items to component
7. Mapping ways shown in Video.
8. Error "Expected a value of type 'List<dynamic>', but got one of type
'String'"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjPHlz4ZOm+FF7oSJc8dahmIvIjt5a+dF1+tEVis8GqLuPe0UWMzBUBFUOd/gTGNIeU2KozgX/Mrsjtn9NMdfByytbapEz7VySxbiTk+5eLaDO663b0d5I+5TIBHFy7SV2RZ5OspYS1Ycw2b7A+qsdC/qNu/YOWw/D+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

Just trying to map data to choice chips from json .JSON

### Visual documentation

<img width="820" alt="Screenshot 2023-08-25 at 6 11 05 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/170eb452-269b-4bb3-b6cb-ca732d94786f">
<img width="1512" alt="Screenshot 2023-08-25 at 6 09 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/7e273c08-8821-4dea-8ce1-15ea8bc90e10">
<img width="1512" alt="Screenshot 2023-08-25 at 6 09 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/2dc1b6a6-505c-4225-97e8-bde4f1ca9951">
<img width="1512" alt="Screenshot 2023-08-25 at 6 09 10 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/a2bacc59-2f4b-4054-9598-171ff173e911">
<img width="1512" alt="Screenshot 2023-08-25 at 5 39 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/d49d1ec4-90f0-4448-8b54-8243d6bce95d">

### Additional Info

**JSON 01 - The original I wanted to use with name field as string to be passed in choice chips** 
`{
      "categories": [
        {
          "index": 0,
          "name": "Alerts",
          "abbreviation": "ALRT",
          "category_count": 0
        },
        {
          "index": 1,
          "name": "Avatars",
          "abbreviation": "AVTR",
          "category_count": 0
        },
        {
          "index": 2,
          "name": "Badges",
          "abbreviation": "BDGS",
          "category_count": 0
        },
        {
          "index": 3,
          "name": "Buttons",
          "abbreviation": "BTNS",
          "category_count": 0
        },
        {
          "index": 4,
          "name": "Cards",
          "abbreviation": "CRDS",
          "category_count": 0
        },
        {
          "index": 5,
          "name": "Contact",
          "abbreviation": "CNTCT",
          "category_count": 0
        },
        {
          "index": 6,
          "name": "Dropdown",
          "abbreviation": "DRPDWN",
          "category_count": 0
        },
        {
          "index": 7,
          "name": "FAQs",
          "abbreviation": "FAQS",
          "category_count": 0
        },
        {
          "index": 8,
          "name": "Forms",
          "abbreviation": "FRMS",
          "category_count": 0
        },
        {
          "index": 9,
          "name": "Footers",
          "abbreviation": "FTRS",
          "category_count": 0
        },
        {
          "index": 10,
          "name": "Headers",
          "abbreviation": "HDRS",
          "category_count": 0
        },
        {
          "index": 11,
          "name": "Inbox messages",
          "abbreviation": "INBX",
          "category_count": 0
        },
        {
          "index": 12,
          "name": "Horizontal Menu",
          "abbreviation": "HMENU",
          "category_count": 0
        },
        {
          "index": 13,
          "name": "Popups",
          "abbreviation": "POPS",
          "category_count": 0
        },
        {
          "index": 14,
          "name": "Prices",
          "abbreviation": "PRCS",
          "category_count": 0
        },
        {
          "index": 15,
          "name": "Products",
          "abbreviation": "PRDCTS",
          "category_count": 0
        },
        {
          "index": 16,
          "name": "Reviews",
          "abbreviation": "RVWS",
          "category_count": 0
        },
        {
          "index": 17,
          "name": "Testimonials",
          "abbreviation": "TSTMS",
          "category_count": 0
        },
        {
          "index": 18,
          "name": "Vertical Menu",
          "abbreviation": "VMENU",
          "category_count": 0
        }
      ]
    }`

**JSON 02 - The one changed to test the choice chips where name field is passed as array instead of one string**

`{"categories":[{"index":0,"name":["Alerts","Buttons"],"abbreviation":"ALRT","category_count":0},{"index":1,"name":["Alerts","Container"],"abbreviation":"AVTR","category_count":0},{"index":2,"name":["Alerts","Warning"],"abbreviation":"BDGS","category_count":0},{"index":3,"name":["Buttons"],"abbreviation":"BTNS","category_count":0},{"index":4,"name":["Cards"],"abbreviation":"CRDS","category_count":0},{"index":5,"name":["Contact"],"abbreviation":"CNTCT","category_count":0},{"index":6,"name":["Alerts","Container"],"abbreviation":"DRPDWN","category_count":0}]}`

### Environment

```markdown
- FlutterFlow version: Flutter Flow v3.1 released August 25, 2023
- Platform: Web
- Browser name and version:  Chrome
- Operating system and version affected: macOS Sonoma 14 Beta 6
```

**Comment by agreaves** [comment]
Hi @Dev-Muhammad-Junaid, thanks for the detailed bug report! I've reproduced and fixed the issue, which should be reflected in the next release. Thanks!

**Comment by Dev-Muhammad-Junaid** [comment]
@agreaves Thanks for the update on this.
Glad to be of service 🫡🥳
