### ISSUE TITLE
Passwordless email auth is missing

### ISSUE THREAD

**Issue by bean5** [FlutterFlow/flutterflow-issues#1359]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In order for me to implement passwordless auth, I have to create a custom function. This seems strange given that anonymous authentication is an option.

### Expected Behavior

Passwordless authentication is an auth type.

### Steps to Reproduce

1. Create a login page
2. Add email address field only
3. Create "Login" button
4. Add action to login button
5. Select authentication "Log In" as action. In dropdown for password, look for "passwordless" (it is missing)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlOflzItPj7xJ+Kr+bPpVtGURNmYlaqxM0OthY0ogGK3NGu4MPsneVFRuZry7TAlmM02kmnkexvfqjd7DJ8FfZBGufIg6/qpAexaUTXyQMJfSCarsfW1SBZ5UIFSH17SzhhQmOu5hWF1lw1y2C/OsYA7cQpDqDEdNR/ilKdeK2SrDX1iXc2URm05KZDPz

### Context

Users have to manage passwords instead of just authenticating by email.

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: Latest?
- Platform: All?
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @bean5 - We appreciate you bringing this up. Anonymous authentication can be used to login without a password ( you are already aware about it) . If FlutterFlow doesn't presently support the authentication mechanism you're seeking for, I would advise adding that request as a feature. We internally refine the feature request and should have a solution in near future. I hope this response is useful to you. Thanks
