### ISSUE TITLE
Video Widget disapears when you exit full mode in web published app

### ISSUE THREAD

**Issue by arielramos** [FlutterFlow/flutterflow-issues#1363]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you use a video widget in a webapp (publish web in FlutterFlow), the video disappear after you exit the Full View Mode, this is an example: https://admin-pepper-health.flutterflow.app/login

### Expected Behavior

Video have to be always visible even after exit the full view mode

### Steps to Reproduce

1. Click on the video widget
2. Go to full view mode
3. Exit Full view mode and you will se that the video disapear

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

-

### Visual documentation

<img width="965" alt="Screenshot 2023-08-27 at 12 04 02 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11698932/c9064168-1340-408d-916b-8f6c74b81519">

<img width="958" alt="Screenshot 2023-08-27 at 12 04 10 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11698932/6a12179e-c7c8-4717-8b44-cfcf9c5270b9">

### Environment

```markdown
- FlutterFlow version: V3.1
- Platform: Web
- Browser name and version: Chrome Version 116.0.5845.110 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura / Windows 11
```

**Comment by takashiff** [comment]
Hi, this issue has already been answered. Please see the following thread: https://github.com/FlutterFlow/flutterflow-issues/issues/866
