### ISSUE TITLE
Secured POST API call with null variables

### ISSUE THREAD

**Issue by Shokhrukh99** [FlutterFlow/flutterflow-issues#1364]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a POST API call is made private and successfully deployed to Cloud Functions and the call has variables, for some reason in test mode the app freezes when an API call is made. In the console, there is an `"Unexpected null value"` error. But when I do not check the "Make private", it works fine. I assume that the reason is that the variables are not being passed to the Cloud functions when the "Make Private" is checked. 
By the way, when I test the API call, it works perfectly. 

### Expected Behavior

The API call made Private and deployed to Cloud Functions with variables should not freeze and pass variables.

### Steps to Reproduce

1. Create any POST API call
2. Add variables 
3. Make API call Private
4. Deploy API
5. Test API call and observe that it works fine and responds (any response)
6. Create any button widget, and attach API call action, and provide variables 
7. Run test mode
8. Click the button and observe that the app freezes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i/Hl2491xMtD+Kr2b8BFoCMXQls7R4EniexuawE8J5zKB+wAYvf7P1FWTLy+dG9mPVqkgmQfxvfqj9j9IO1fNkyqc6ZTwbl6ZwvKUT65VJjWPKu7fW1RINFgG0iv37TYhhFDKuhsdUYH7GWufe/IUXbsGL74DTIjGOW1LdeK2SrDX1iXc2URm05KZDPz

### Context

I cannot make private API calls because it contains an API key

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/74ed78a9-b33d-4a54-9ba8-9830a4706452)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/fabe3587-1f35-4d99-94fb-611c8d7c916c)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/0555758f-dc06-47f5-8546-f0f39eba930d)

### Additional Info

The issue can be observed in the test mode, but when testing API calls in the "Response and Test" tab, it works fine

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 116.0.5845.111
- Operating system and version affected: Windows 10
```

**Comment by kashgod** [comment]
Hello @Shokhrukh99 , 

Please give this fix a shot -> [](https://github.com/FlutterFlow/flutterflow-issues/issues/1368)

There's a bug where that Private function is not sending the request body in JSON type, though you send a JSON.

**Comment by hariprasadms** [comment]
Hi @Shokhrukh99 - Thanks for submitting the issue. I looked at your project. Api configuration looks good. I did follow the above steps as well. Api calls works fine for both the cases where api call is private and not private. I can I'm not able to reproduce the issue. Please share the screenshot of private api call cloud function deployed to fb console ? les see how json body looks along with variable assigned to it.
