### ISSUE TITLE
Clicking a gif on the Flutterflow docs disables scrolling

### ISSUE THREAD

**Issue by NielAgi** [FlutterFlow/flutterflow-issues#1365]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking a gif on the Flutterflow docs disables scrolling and breaks page in other ways.
Scrolling is still possible when clicking down the scroll button.

### Expected Behavior

scrolling keeps working

### Steps to Reproduce

1) Go to any flutterflow docs page that has a gif (https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/checkboxlisttile)
2) Click the gif
3) Try to scroll
4) Refresh page to fix

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Context

.

### Visual documentation

.

### Environment

```markdown
- FlutterFlow docs
```

**Comment by hariprasadms** [comment]
Hi @NielAgi - Thanks for posting the doc related issue. I tested it and it works fine. It could be browser side glitch. Which browser you are using?

**Comment by NielAgi** [comment]
I am using brave browser

Op ma 28 aug. 2023 18:56 schreef Hari ***@***.***>:

**Comment by hariprasadms** [comment]
Hi @NielAgi - I would suggest use chrome browser. Please confirm. Thanks
