### ISSUE TITLE
APIs not working when 'Make Private' feature is enabled - Bug Fix

### ISSUE THREAD

**Issue by kashgod** [FlutterFlow/flutterflow-issues#1368]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you add a new API and choose the 'Make Private' option to ensure secure routing through a FlutterFlow cloud function, your app's request takes a detour. It first goes to a cloud function in your Firebase account and then to your API endpoint. Your API then processes the request and sends the response back to FlutterFlow's private function, which then sends it back to your app.

However, due to a current bug in FlutterFlow's automatically deployed private function JavaScript code, your API endpoint isn't accepting your app's request. This bug assumes that your API endpoint code functions properly when tested locally, in the cloud, and without enabling the 'Make Private' feature.

### Expected Behavior

When 'Make Private' is enabled, everything should work smoothly as though you haven't enabled that feature.

### Steps to Reproduce

Below are steps to solve the issue:
1. Go to the **ffPrivateApiCall** cloud function deployed in your google cloud account. 
2. Locate your API call in the **api_manager.js** file and search for the 'var body' variable.
3. Now, remove the single quotes to that variable, essentially converting that string variable to a dictionary variable.
4. Re-assign the values to the keys of that dictionary with the variables of your API call which are in the scope of the same async function.
5. Save and Redeploy it.
6. Remember that every time you redeploy your Private APIs, this function keeps updating with the old changes until Flutterflow fixes it.
7. That's it. Your API is now rerouted securely through that cloud function.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Backend Bug

### Context

Couldn't use the 'Make Private' feature. 

### Visual documentation

Kept getting 400 error.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @kashgod - This looks like you are addition a solution for the issue _'Secured POST API call with null variables'_. You can add this as comment for the issue. It should not be raised as issue type.

**Comment by kashgod** [comment]
Hello @hariprasadms, This issue I've created is the actual bug and I've also mentioned the fix and where Flutterflow's code is wrong. You can reproduce it by making adding an API request with a JSON body and enabling the 'Make Private' feature. 

For this issue - _'Secured POST API call with null variables'_ , I've just suggested that this fix could be a workaround, but flutterflow devs should still fix it.

**Comment by hariprasadms** [comment]
I am closing this bug and keep your original issue for issue triage. Thanks

**Comment by 1stpd12** [comment]
This is still a bug, and I experienced the same thing today.

**Comment by Zuuai** [comment]
Same here. Getting the same error when making a API call private

**Comment by sabatage3** [comment]
I'm having this same issue, only google map api calls work with "make private" optinion turned on, the rest of API Calls fails as soon as I turn on "make private" is there any solution for this? right now API Keys are completely exposed
