### ISSUE TITLE
Error while retrieving API response after publishing to the web

### ISSUE THREAD

**Issue by nextcompta** [FlutterFlow/flutterflow-issues#1369]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello everyone, I wanted to publish a webapp. No error when testing the application locally (Run OK) and the API request works normally. As soon as the application is published in the web, I can no longer retrieve the API response and I have the following error at the console level: main.dart.js:2963 Uncaught FormatException: SyntaxError: Bad control character in string literal in JSON at position 36
at Object.j (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:2963:3)
at Object.bjR (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:5063:9)
at afb.qg (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:41342:19)
at afb.ec (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:41344:21)
at aSD.$0 (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:44662:18)
at anA.X (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:80440:8)
at https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:44618:3
at b64.a (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:4272:62)
at b64.$2 (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:39191:14)
at Object.K (https://storage.googleapis.com/flutterflow-prod-hosting/builds/MIxCMtBjqPRvApEiUf85/main.dart.js:4258:10)

### Expected Behavior

I expected to have the catch the api response after publishing on the web.

### Steps to Reproduce

...

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

nc-api

### Context

Api response is Ok (response 200) localy on run mode but not after publishing on the web.

### Visual documentation

...

### Additional Info

...

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: WEB
- Browser name and version: Google Chrome Version 116.0.5845.110 (Build officiel) (x86_64)
- Operating system and version affected: desktop macOS Ventura
```

**Comment by hariprasadms** [comment]
HI @nextcompta - Thanks for reporting the issue. Please provide project bug report code and mention the pages and api call names. Without these details, we are unable to look into your project and determine what is happening. Thanks

**Comment by nextcompta** [comment]
Hello, I have created this new project with one single page and one api call.
https://canvaskit.flutterflow.io/project/jul27-dust-8514v6
Same error while publishing to the web.
<img width="1418" alt="Capture d’écran 2023-08-29 à 07 44 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6018776/2a97b67e-5e54-45a1-b91e-afad85a3705f">
<img width="1334" alt="Capture d’écran 2023-08-29 à 07 43 01" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6018776/663d0125-bfa3-469f-955b-312da036ccfc">
<img width="1196" alt="Capture d’écran 2023-08-29 à 07 41 05" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6018776/cead20ba-28ad-448a-b668-84bae4d0b9aa">

**Comment by hariprasadms** [comment]
Hi, Please send project bug report code.

**Comment by nextcompta** [comment]
Hi,
Locally, I have no error. No bugs. everything works normally.
So i don't have bug report code.
By when I dpublish the app the api response is no longer processed. I only have the error on the web console.
The project is cloneable (public) at the adress https://canvaskit.flutterflow.io/project/jul27-dust-8514v6.
Thank you

**Comment by nextcompta** [comment]
Hello, 
On the console i have also this error :
Access to XMLHttpRequest at 'https:/xxxxxxxxxxx' from origin 'https://xxxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
How to solve it from flutterflow ?

**Comment by wenkaifan0720** [comment]
Hi @nextcompta. Sorry for the late reply. The API you provided seems to be not working anymore. And the error you see looks like a CORS issue, which I believe you need to setup your own proxy to avoid it in production (see https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9).

**Comment by hariprasadms** [comment]
Hi, Due to inactivity, we are closing the issue. Thanks
