### ISSUE TITLE
Getting an merge error when testing on iOS devices.

### ISSUE THREAD

**Issue by almantas88** [FlutterFlow/flutterflow-issues#1371]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Getting a merge error when testing on an iOS device and doing the first run.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47143702/9bd5061b-92c0-438d-aec1-6e8130c7e7f8)

### Expected Behavior

There shouldn't be an error.

### Steps to Reproduce

Create a new app;
Integrate two languages (Lithuanian and english);
Make primary and display language as lithuanian);
Push the code to github;
Pull the code to your local machine;
Run the code on an iOS device;
Do some changes in Fluterflow editor;
Do another push to github;
Try pulling the code and the error comes up;

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ok/Lqx8pgod9c7ZPpbcAwmikRHGYlU4ZN0utHbAE3GKnNG4gIZfTBXE9uOP25dkFYMGaKhT4d/vuNm9z1Cfc6KU2qc6Z/wZd+TBaXez+QR6aYPartR0FUGshjfxGz16S3ghBSCLdtWXgA2Vy6JeyUZATaQ+PjIFgvIM+ZNpjXmAfuQ0SLb3kNh1JWeC/v

### Context

Just basic testing, I need to remove the project and do another pull again and it consumes a lot of time;

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47143702/67a9b8bc-36e4-4910-92e2-207ef876c98c)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47143702/4b0d5014-2873-4667-9fe9-881242e1887d)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS
- Browser name and version: Chrome latest
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment]
Hi @almantas88 - Thanks for submitting the issue. This error purely related to git pull / push error. This is nothing to do with FlutterFlow dowloaded code. I would suggest pull to different local work folder and try again. It should work fine.
