### ISSUE TITLE
Widget text do not show text on some devices

### ISSUE THREAD

**Issue by desarrollador5excelsolar** [FlutterFlow/flutterflow-issues#1372]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello Flutterflow team, we have an issue with our row widget like menu, the situation is that the text does not show on some devices specifically iphone 11 and iphone 13 pro, on other devices does show the text of each menu "clientes" , " oportunidades", "productos, "calendario", "tablero" , please could you help me ?

### Expected Behavior

On others devices the text do show 

### Steps to Reproduce

1. open app on iphone 13 pro or iphone 11 with testflight
2. login into app (even the text of the start button does not appear )
3. the text of menu do not show

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi+fl3It1rs9H+KrqdMBKiiAWI0MBX5Ir1utvGQEcG4+vE+0MfczUaXdCOvWlTwlcB1WkpFIF0MLlkd/XIfQCZA6CfaF607lbFg/zUkGWb5jSCquwQn8mLJ9QG2WOyMOrhAhNA7FtSiUN62GLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

menu names not displayed on some devices

### Visual documentation

![issue text](https://github.com/FlutterFlow/flutterflow-issues/assets/44376396/405218db-d61b-43fb-b065-31343fd5c603)
![WhatsApp Image 2023-08-28 at 11 35 16](https://github.com/FlutterFlow/flutterflow-issues/assets/44376396/4b9ab0e7-49e4-41e1-9ec3-68ccf4c0d3e3)

### Environment

```markdown
- FlutterFlow version: v3.1 (released August 17, 2023)
- Platform: Web
- Browser name and version: Chrome 116.0.5845.111 (Build oficial) (64 bits)
- Operating system and version affected: iOS 16.6
```

**Comment by hariprasadms** [comment]
Hi @desarrollador5excelsolar - Thanks for submitting the issue. It is related to language settings. You have selected display language as English and primary language as Spanish. But There is no english translated texts present through app. But bit confused when you say it works on iPhone phone some devices. Try correcting this language settings and see how it goes. Thanks 

<img width="748" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/47a646de-006f-4309-abb6-3538900eeebf">


<img width="999" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/be270501-2e4c-4d0d-b2b6-be366a32d4f0">
