### ISSUE TITLE
Firebase Filter Query needs support of isNull True / False

### ISSUE THREAD

**Issue by jagpreetsethi** [FlutterFlow/flutterflow-issues#1377]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

**Objective**: Pull records from the collection that have played_quiz field populated. 
To do so, following were the selections made in the UI which generated the code like so:

userActivityRecord.where('user_ref', isEqualTo: currentUserReference)
.where( 'played_quiz', isNotEqualTo: null)

Same firebase collection is used to track other user activity as well. Thereby it throws an error "Null Check generator used on a null value".

### Expected Behavior

Error should not appear.

### Steps to Reproduce

1) Create a firebase collection with fields - timestamp, PlayedUserRef, NotPlayedUserRef
2) Create a "Query Collection" to generate a list of played user by referring to PlayedUserRef field.
3) Create a "Query Collection" to generate a list of not played user by referring to NotPlayedUserRef field.
4) Now populate the collection with the record:

INSERT RECORD 1: timestamp (2023-08-29), PlayedUserRef(/user/djflskdjfs), NotPlayedUserRef (Field DOES NOT exist)
Both the list views showing played user i.e. 1  now and not played users i.e. 0 works fine.. All good!

Insert Record 2: timestamp (2023-08-29), PlayedUserRef(Field DOES NOT exist) NotPlayedUserRef (/user/laksjdflksjd)
Error: Null Check generator used on a null value

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shcrl/ZBgrsNG7c/UccFB/CcRHGV9RpIosct/RQEgF5j4PLAHP87SQFFvOdCzaHw3eFGJgXwEpsrHhdntMsI7EzaYQJxg1ql+WhPPbFytaa7TPpOeT3ZRN8ZUGGrF56SF3xJ7BPNuc3An6l66Ouq+Zz6Cf9qOYwx5e6fDbOY=

### Context

Collection is sparsely populated with some fields doesn't exist in every document. As a result, I'm trying to fetch records from the collection that have certain field populated or is not null for those.

### Visual documentation

<img width="306" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15049832/e28c0d0f-ea6a-46a2-ac10-e67dfc798625">

### Additional Info

**FIX THAT WORKED FOR ME:** 

In the code, I was able to fix by two ways:

**Solution 1:** userActivityRecord.where('user_ref', isEqualTo: currentUserReference)
.where( 'played_quiz', **isNull: false**)

**Solution 2:** userActivityRecord.where('user_ref', isEqualTo: currentUserReference)
.where( 'played_quiz', **isNotEqualTo: ""**)

Both these solutions require code change and not able to achieve from the FF UI.

### Environment

```markdown
- FlutterFlow version: v1.1.100 (Desktop App)
- Platform: iPhone 13 Pro Real Device
- Browser name and version: Chrome Browser
- Operating system and version affected: IOS
```

**Comment by hariprasadms** [comment]
Hi @jagpreetsethi - Thanks for submitting the issue. First of all we need project bug report code is required to investigate the project. You can find project bug report code right clicking on any pages widget tree.  

I am not sure that I fully understood what you're attempting achieve. While retrieving the documents from the collection, I assume you're attempting to ignore docs that are null. If I'm wrong, please correct me. If this precisely what you are looking for, you can utilise the _**Ignore Empty Filter Values**_ option. Look below. However, you got custom code capability in FF, you can use it to customise your query needs.

I would advise getting in touch with the FF technical support team if you are still looking for assistance with it. They can assist you. 

<img width="384" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a3e8461f-8f87-4e4d-a132-7557c6c54b90">

**Comment by alexredder** [comment]
This thread helped me find my solution too. If this issue is being terminated, i hope you at least include the workaround in the documentation. 
However i also vote for an "either/or" option.
Thanks

**Comment by joshua-ffio** [comment]
This issue was a duplicate of #1149 and has bene addressed.

**Comment by joshua-ffio** [comment]
> Thanks @joshua-ffio for addressing the issue. In what release can we expect this to be fixed?

I believe the "Filter on null values" toggle in the backend query dialog should be live now. Tune in to the linked ticket #1149 for any further updates on the matter.
