### ISSUE TITLE
CheckboxGroup right overflow

### ISSUE THREAD

**Issue by ash007osh** [FlutterFlow/flutterflow-issues#1378]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I use a long text in CheckboxGroup, I get right overflow error. Whereas this issue is not there, if I use CheckBoxListTile instead.

### Expected Behavior

The long text should get wrapped into multiple lines instead.

### Steps to Reproduce

1. Create New Page
2. Add a Column and then add checkboxgroup inside that.
3. Add options in checkboxgroup, while adding a long text in one of the option.
4. Try running Test and an overflow error would be thrown.
![problem](https://github.com/FlutterFlow/flutterflow-issues/assets/1225987/c06037bb-140e-49b4-8538-86424ebe13da)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klfHqw89goekB15PtbccwtCc7Q0wjTL0npu5udxIYfZDoO5sids+lUFVUOLHnSnNiJEyKoD0X/Mr0udrxO8YCPROcGdVZyLpxFj3gWk6tb4iDOpS3b3AkGe1VGXKw4ZmFpSRSIsBadEIf616UGO+tdD3rH4DqNUUzBOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Not able to build an important functionality in my app.

### Visual documentation

![problem](https://github.com/FlutterFlow/flutterflow-issues/assets/1225987/b809ed18-66e8-4582-a48e-b059636cb59f)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: iOS, Android
- Browser name and version:Chrome
- Operating system and version affected: None
```

**Comment by ash007osh** [comment]
Hey Guys.. Any update on this one.. I need to decide if I should go ahead with this Widget or try something else, so a tentative timeline will be helpful

**Comment by ash007osh** [comment]
Is there anyone looking into it?

**Comment by SameerShahzad99** [comment]
@ash007osh, this problem seems to be project-specific due to your configuration, can you please wrap the text inside a container and set a specified width, this should resolve the problem you are experiencing.
if you still face any problems you can reach out to the support team through live chat or email at support@flutterflow.io!

**Comment by ash007osh** [comment]
Hi @SameerShahzad99 this is an in built widget in flutterflow. I don’t think there is an option to wrap text in this case. I believe this has to be done inside the widget’s source code

**Comment by ash007osh** [comment]
@aemelyanovff may you have a look at it please?
