### ISSUE TITLE
Scan Barcode will not open in testing

### ISSUE THREAD

**Issue by thomaslsimpson** [FlutterFlow/flutterflow-issues#1379]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The "Scan Barcode/QR Code" widget simply does not open from what I can see.

### Expected Behavior

You can simply attach the action to any button and clink the button and it ought to start the camera (as in the video examples) but it does not. I have done a "Alert A" -> "Scan Barcode" -> "Alert B" type test in a project and Alert A works and Alert B works in the "Preview" mode but no other way. The scanner does not work in any case.

### Steps to Reproduce

1. Create a new blank app.
2. Add a Button.
3. Select Actions on the button.
4. Click Add Action
5. Choose "On Tap"
6. Chose "Widget/UI Interactions", then "Scan Barcode/QR Code"
7. In the Options widget, set the variable name to "someoneDidNotTestThis".
8. Run Preview
9. Click the button

(This will also work if you build out the application from step 8 and test it in that mode.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz+fq6otPxNsA0KX5be5WqycvG1B9TLJEoetxc0gbfe/4EIk+ZPfBUFBuOdyzaHxIH1eb8Dg0wfD6iuLMV/ZdJgedft1YybgNFhPPbFOjRrLROpe0XXwlJ/FVI2nD4abUvhNNHMBZSmwu2k2QFtmWRT6Cf9qOYwx5e6fDbOY=

### Context

This is the main function I need for the application and without it I cannot move forward at all.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/3473349/f871d29c-c8d6-4364-83e5-549e6fa2eb1b

### Additional Info

This is a ridiculous amount of information when all you really need is: the barcode scanner is not working. I get that is is tough to run. down the bugs on things sometimes but if you'd just start with that, you could reply "works for me" and then I could get into details. Putting this much off on me puts me off as a user for something this trivial and obvious.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Mac OS Web; iPhone (preview and real Test Mode give slightly different failure modes)
- Browser name and version: Chrome 116.0.5845.110 (Official Build) (arm64)
- Operating system and version affected: 13.4.1 and iPhone 14
```

**Comment by hariprasadms** [comment]
Hi @thomaslsimpson - Thanks for reporting the issue. At this stage the current version of scan barcode feature does not work on web. It does not work in test mode (debug mode), which is eventually web mode. Additionally, because preview mode displays the design in a static page views, it does not work. 

Read FlutterFlow [docs](https://docs.flutterflow.io/actions/actions/widget-ui-interactions/scan-barcode-qr-code) related to Scan Barcode/QR code configuration for more understanding. 

I hope this answer can help you.

**Comment by thomaslsimpson** [comment]
I appreciate you getting to this quickly and the response is clear but does it say this somewhere in your documentation that you referred me to there? I'm evaluating platforms to use for our company's LCNC exploration and scanning QR codes is the main thing I want to do with this application. You have a widget that says it scans QR codes. You have documentation that says you scan QR codes. But, you don't scan QR codes?

Are you saying that there is a way to use the feature not on web? Since it is at this stage, does that mean there is a future stage where it is going to work and if so, can I know that?

Thank again!

**Comment by wenkaifan0720** [comment]
Hi @thomaslsimpson. We use this [package](https://pub.dev/packages/flutter_barcode_scanner) for scanning barcode and it only supports Android and iOS at this stage. You would need to download the code and run it on a local emulator/real device in order to test it.

**Comment by orchard800** [comment]
I first came across the issue last year and it's still not been addressed! One of the core functionalities of most apps involves scanning a QR code.

To say that you can't test that in the app designed for testing is ridiculous!

I wonder how many agencies are being put off using FF as a serious platform because of this very basic issue - not to mention how long people have been asking for it :-(

**Comment by nicbyron** [comment]
I really want to implement QR code scanning into my app, but don't want to force users to download an app to do so. Further, not being able to test it in test mode makes me hesitant to include it even if I do decide to go for a native app. @FlutterFlowEng do we have an idea of where this is on the roadmap?
