### ISSUE TITLE
Apps not loading in Chrome

### ISSUE THREAD

**Issue by Hendler** [FlutterFlow/flutterflow-issues#138]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
App page opens

## Current behavior (required)
 Loading page stalled

## To Reproduce (required)

Tried restarting chrome, logging out and logging in. Using Google SSO. 
Dashboard will load with error in js console below. Opening app stalls. 
 
 

## Context (required)
I have been unable to work on an app.

## Screenshots / recordings
<img width="1766" alt="Screen Shot 2022-11-17 at 1 48 25 AM" src="https://user-images.githubusercontent.com/144833/202504722-2d23e448-1d82-4b70-b0f7-02ba440ece28.png">

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: unnownn
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome 107.0.5304.110
* Operating system and version (desktop or mobile): Monterey 12.6

Able to reproduce on Firefox.

**Comment by organicnz** [comment]
Hi Jonathan @Hendler. Thanks for adding this issue 🙂
Have you tried to use Google Sign-In before implementing Google SSO? :)

**Comment by Hendler** [comment]
> Hi Jonathan @Hendler. Thanks for adding this issue 🙂 Have you tried to use Google Sign-In before implementing Google SSO? :)

Sorry, if the language was confusing. I mean I am logging into FlutterFlow using Google sign in. 

I was using the TODO list sample template. I've tried other templates, and to create a blank project. Still no dice.

**Comment by organicnz** [comment]
> > Hi Jonathan @Hendler. Thanks for adding this issue 🙂 Have you tried to use Google Sign-In before implementing Google SSO? :)
> 
> Sorry, if the language was confusing. I mean I am logging into FlutterFlow using Google sign in.
> 
> I was using the TODO list sample template. I've tried other templates, and to create a blank project. Still no dice.

No worries at all, mate :) 
Could you pls share your widget tree and screenshots/ recording would also be very useful :)

**Comment by Hendler** [comment]
```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at main.dart.js:228834:3
    at eQc.a (main.dart.js:5521:62)
    at eQc.$2 (main.dart.js:108923:14)
    at eJW.$1 (main.dart.js:108917:21)
    at bT_.RE (main.dart.js:110165:33)
    at e8D.$0 (main.dart.js:109387:11)
    at Object.aH7 (main.dart.js:5656:40)
    at bG.zO (main.dart.js:109304:3)
    at bGy.f4 (main.dart.js:108907:8)
    at Object.w (main.dart.js:5511:10)
main.dart.js:6778 Uncaught TypeError: Cannot read properties of null (reading 'b')
    at main.dart.js:94752:12
    at eQc.a (main.dart.js:5521:62)
    at eQc.$2 (main.dart.js:108923:14)
    at eJW.$1 (main.dart.js:108917:21)
    at bT_.RE (main.dart.js:110165:33)
    at e8D.$0 (main.dart.js:109387:11)
    at Object.aH7 (main.dart.js:5656:40)
    at bG.zO (main.dart.js:109304:3)
    at bGy.f4 (main.dart.js:108907:8)
    at Object.w (main.dart.js:5511:10)
us-central1-flutterflow-io-6f20.cloudfunctions.net/getCountryCode:1          Failed to load resource: the server responded with a status of 500 ()
```
Project directory appears as normal
<img width="1274" alt="Screen Shot 2022-11-20 at 5 34 41 PM" src="https://user-images.githubusercontent.com/144833/202942346-052438d0-8aa7-4928-b1be-bae49492441a.png">

Never leaves this screen.
<img width="591" alt="Screen Shot 2022-11-20 at 5 34 46 PM" src="https://user-images.githubusercontent.com/144833/202942357-eea5b678-e2bb-4c7c-8f5b-d5a433d5569e.png">

**Comment by organicnz** [comment]
@Hendler thank you for providng the content. Sitll can't be reproduced as the widget tree with configured collections and actions is needed or the project could be publicly shared if it's easier at the moment.

<img width="1440" alt="Screen Shot 2022-11-22 at 09 49 37" src="https://user-images.githubusercontent.com/4765090/203245165-316faeb3-4c79-40f6-bbf9-2c7e594a8eb1.png">

**Comment by Hendler** [comment]
Maybe from the error there's something in the server logs, even if you can't reproduce?

```
us-central1-flutterflow-io-6f20.cloudfunctions.net/getCountryCode:1          Failed to load resource: the server responded with a status of 500 ()
```

Sorry, I don't know what you mean by sharing a widget tree. Widget tree never renders. I can tell you this happens even when creating a "blank" project from the project page.

**Comment by Hendler** [comment]
Ok, I've been able to eliminate the issue by logging in with a standard `@gmail.com` account. Before I was logging in with "Google" but using a custom domain hosted on gcloud. The issue is likely caused by the back end expecting some metadata to be present in user profile and failing on the backend.

**Comment by organicnz** [comment]
> Ok, I've been able to eliminate the issue by logging in with a standard `@gmail.com` account. Before I was logging in with "Google" but using a custom domain hosted on gcloud. The issue is likely caused by the back end expecting some metadata to be present in user profile and failing on the backend.

Glad that's fixed by now. Thanks for providing some details on your part, mate.
