### ISSUE TITLE
Custom Function and FirestoreRecord objects

### ISSUE THREAD

**Issue by nilsabegg** [FlutterFlow/flutterflow-issues#1382]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a encountered a very strange problem with custom functions:

I have a Firestore Document called Location with some fields. 
I created a custom function to return a List of LocationRecord objects.

When I try to access the static function of LocationRecord, I always get an error when I test the function, that this function is not defined. Even though in the function editor itself, these functions are getting auto suggested.

I bought the cheapest plan to be able to download the code and see what's going on, but in the LocationRecord class is everything correct, as the auto suggest in the function editor suggests. 

Thank you and best Regards

### Expected Behavior

I expect to be able to call the static functions and members of my Location document in a custom function like this:
`var lr = LocationRecord.collection.doc()`

### Steps to Reproduce

1. Create new document collection called Location and give it one string field called 'name'.
2. You create a new custom function with a return type of Document->Location and in the function body, where you are supposed to enter code, you enter:
`var lr = LocationRecord.collection.doc()`
3. Test the function

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kMrl7ZBgrt9f7arUavpV+Ts5JmI+bYEvku1RaCosfZT2BLMcec/RVERWZ/G6SglqIWGZu2oW0PCKjofXNfk6YBCYc5xiz7pcZRXwezuXbKqbFJWvPHR5I+ZXIGqZyKe7sB0lIft1dXdn7HGADdnKfHbsNrruPW4sDq/LZO4=

### Context

I am trying to set the values of a custom document record object in Flutterflow. I created a collection and a Location document type. I want to pass a list of these Location Documents to the GoogleMaps component of Flutterflow and it only allows to attach data for markers when you use documents. So I can't use a list custom data types for it.

I had this code already working with the custom data type, but now I need to rewrite it to make it work with the document records, since this is the only way, to pass any data beside LatLng to a marker that the marker can pass it to a BottomSheet on click. My actual data is coming from an API, which is all working fine.

### Visual documentation

<img width="919" alt="Bildschirm­foto 2023-08-31 um 01 22 34" src="https://github.com/FlutterFlow/flutterflow-issues/assets/283556/84767e4f-c93a-452b-a4a5-3f4b64ccb24d">
<img width="727" alt="Bildschirm­foto 2023-08-31 um 01 22 19" src="https://github.com/FlutterFlow/flutterflow-issues/assets/283556/07f9fcaf-1796-4889-a76a-d7a4ce4f8659">

### Environment

```markdown
- FlutterFlow version: The current browser version
- Platform: Web, MacOs Desktop
- Browser name and version: Chrome current
- Operating system and version affected: OSX current
```

**Comment by isegal** [comment]
Following up on this.

Is there a way to return a record object from a custom function? For example, to initialize with a set of defaults.
Since FF allows us to define a specific record return type for custom functions, it implies that there is a way. 

Has anyone got this to work?
