### ISSUE TITLE
"Collection Field Name" Not Clickable on Query Collection Backend Query

### ISSUE THREAD

**Issue by Fibn007** [FlutterFlow/flutterflow-issues#1384]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm doing a backend query on a Chart widget. When I try to perform a "Query Collection" and I try to "Order By", the "Collection Field Name" is not clickable and thus, doesn't let me order the query. 

Setup of Backend Query:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/b7066820-e719-4840-8b31-013790f564ad)

Image displaying it isn't clickable:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/14f38b47-54f5-42d2-b06f-08302e435a4a)

Widget Setup for Chart:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/ecad075f-f0b7-4de7-ad1c-892dcf2b68b7)

### Expected Behavior

When I mouse over the "Collection Field Name" portion from within "Ordering" in the query collection, I'd expect the Collection Field Name to be interactable. 

### Steps to Reproduce

1. Create a Column and Add a Chart to that Column.
2. Perform a backend query on the Chart
3. Copy this config:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/f9a89d74-6972-41a0-9588-cf6b41227478)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/a65e402d-2db1-4ae8-9c99-cd38a3e6ef90)
4. Cannot click on the "Collection Field Name"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kvLlw4tNrsdG+KXydcFFmjgWQ187aLsVi+5tTUs8KO/aP5kAdsnQP1hoTdDiSnw6fGe2p14FwNbTivPPEcI3HEmWR5xJ+rtiEwnwQkCnV7GTF7WaRXBCJ+JPIEfG5LaZhBQlC7NZWiFh72CLf+fKbBXAK4D6C2o8Sq/LZO4=

### Context

Can't order my backend query data by datetime on a Chart. 

### Visual documentation

Attached in steps above

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Windows Desktop App
- Browser name and version: 
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Fibn007 - Thanks for posting the issue. I can confirm that this behaviour as expected. Order by field accepts only field value which are not list type. This is as per the design. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/fea7f43a-2fe0-496c-92f4-d0199ba01224)
