### ISSUE TITLE
Classes are not defined/imported from other customs

### ISSUE THREAD

**Issue by dinasorz** [FlutterFlow/flutterflow-issues#1390]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If we defined a class in a custom widget, and wrote this class in another custom widget it'll give an error of Undefined class

### Expected Behavior

for the class to be defined and available for other custom widgets

### Steps to Reproduce

-Create Custom Widget
-Define class
-Creater another Custom Widget
-Try to use this class, then compile, it'll give you undefined class error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

MBIT4ojPLlvJFIocte7q6JccBKjSQsHHMB5+ap0nlMpBZywgfZzzBLNMB/fPfMBQPxBuUu2lTQlAJGacp14E0sr7kvHTNu1dKQqdGqZEzapAVwrMeECiaZeTF7WKbWpBL9lMGWag052nvhNNKvpeWXAe1zuTON6XdCntGLrHPWo8SqMB/LZO4=

### Context

Destroying the concept of code reusability

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/95580779/88bfb3e4-db1e-43f8-93d9-7a990ba43d4e)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: PC
- Browser name and version: Google Chrome v115.0.5790.171
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @dinasorz - Thanks for submitting the issues. Your above steps are confusing at step 2. Can you add more details about step _define a class_ ?. However, I can confirm that, FF allows accessing widgets between custom widgets. I can confirm that it is woking as expected. See below a simple example showing it is working as expected with no compile errors.

Note - Custom widget code should be compiled successfully before accessing each other.

<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/913ff18e-d3ca-4547-ac13-ae38ad8a8d83">
