### ISSUE TITLE
Red 'Unexpected null value' page when page state variable name is the same as the component parameter name

### ISSUE THREAD

**Issue by yairpe** [FlutterFlow/flutterflow-issues#1391]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the page state name matches exactly the parameter name of a component and it is a data type, a red error page with 'Unexpected null value'  message appears
![flutterflow_issue_red_page](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/a1277f2d-717d-4a8f-a764-4033cc89de28)

### Expected Behavior

normal page display without any errors

### Steps to Reproduce

1. create new page
2. create data type myType
3. create page state variable: myVar
4. create component (any name)
5. define input parameter for the component: myVar of data type myType
6. add the component to the page and pass to it the page state myVar
7. test 
I've created this minimal project with the bug

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89grsNY1qrtbcFviiQvIjs9a50v0O1DYCs8JJToPLAUZ8zBM05vZryoS1Y6M2f9pzoy/PfqivPxEu0DGw6dQNg++c5xFzzJRnqQWqqvEbiNfW1SGphjGXai4cG7mBFDOup1ZU5i2066BfPLTTDbH5j4NW1MFvm1LdeK2SrDX1iXc2URm05KZDPz

### Context

This is a tricky bug as it took several hours of traditional eliminations to finally guess that the same name of variable and parameter  may cause system confusion.

P.S. If it's not a bug but a dart/flutter normal behavior, IMHO it should appear as a note in the documentation. 

### Visual documentation

![flutterflow_issue_red_page_with_dev_console](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/2cdd9e1e-ee76-4c3a-85b4-b73752ed290a)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: chrome Version 116.0.5845.140 (Official Build) (64-bit)
- Operating system and version affected: Win 11
```

**Comment by hariprasadms** [comment]
Hi @yairpe - Thanks for submitting the issue. I looked at your project. As per above steps, when I run the project in debug mode, build is success and it works fine. I do not see any errors displayed. I hope this has been fixed for you as well. Please let me know if issue still persists. Meanwhile i will mark this as not a bug. Thanks

**Comment by yairpe** [comment]
It seems fixed. Thank you.
