### ISSUE TITLE
Issue with creating Team API

### ISSUE THREAD

**Issue by vineethvijayan314** [FlutterFlow/flutterflow-issues#1392]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We created an API in the Team section so that we can use it across projects. We have to pass accessToken to our API. But when we put it as a team variable and team header. it doesn't work. It Literally takes accessToken as the text instead of the variable passed

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/81630465/ef9c2609-5f84-4844-97e1-715905c7a364)

### Expected Behavior

I expect the API takes the right access token from the variable I am passingtake

### Steps to Reproduce

1. Create a team API
2. Add headers and variables on the group level
3. Try accessing the API from any project
4. Check if the headers passed

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ei8mBw4ZOxe5E0b6JbcEwhiAXNl87UIIvlu5+FQwcJZ+tEYl3fej+QGdvZ7ylfHw3emGi8T400NLWv9nDD8AHPiiZRphfzrhAbgmXZGCXeLqREpOCeEZfP5hUfRSHzbWjuRV5LshZcXgu7TmIHeStFj7cJJzOPlQ3GciYKoD4+06XKwzCXn0Jg1ZSfCvr

### Context

We are trying to use the API's in multiple projects

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/81630465/32ee80dd-0739-42e6-9b15-2e010f1c2bbb)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: web
- Browser name and version: Brave 1.57.53
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @vineethvijayan314 - Thanks for submitting the issue. I can confirm that group level variables are not allowed to access at Api headers. It is as per design. We recommend you to use actual Api key value in the header instead through variables. _This issue is not a bug_. I hope this answer can help you.

**Comment by vineethvijayan314** [comment]
Okay, normally API key is unique to each user (based on their login). So I would guess it would work the other way around.
