### ISSUE TITLE
Google/Apple auth doesn't save e-mail

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1394]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a user with Google/Apple like so:
<img width="903" alt="Screenshot 2023-09-01 at 12 13 28" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/f5982058-c259-47fe-bb2a-a15cc97214c4">

The users document gets created, but the e-mail doesn't get saved. Here's an example:
<img width="844" alt="Screenshot 2023-09-01 at 12 15 36" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/afa9e5fa-89b3-4e7e-9d06-8d8734743441">

I talked to support and they told me it was impossible... They also couldn't find anything "weird" with my project. However, it is real and is a problem if you want to use the e-mail address for things like sending a receipt for a Stripe payment.

### Expected Behavior

The google/apple e-mail would be saved in the e-mail field.

### Steps to Reproduce

1. Create auth page
2. Add google/apple login
3. Create new account through that auth
4. Check DB for email

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlcn635ZNvttZ+KqIYMJVgjoWM0MfWLsr0utuGA0hNYDpPLMIfPT8RFVLYtSrTVdiHmKGmkAf3NbGi/LAUfpcGyWYRYhq+pRXQQLNRlu6MsmUCoeCYGtAL91gIWK/yqTZ2RFvNrJhL3g772WAOPCrG3qCf9qOYwx5e6fDbOY=

### Context

Cannot send e-mail receipts for payments to customers.

### Visual documentation

Shown above.

### Environment

```markdown
- FlutterFlow version: v3.1 (released Aug 28, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 116.0.5845.110 
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @tinrunje - I appreciate you bringing this up. I looked at your project and verified the above tested. But everything works perfectly on my end. Lets try this, turn off push notifications and register as a new user to check if a user account is created. Share a brief video of the steps you described above as well as showing Firestore user collection after sign up is completed.

**Comment by tinrunje** [comment]
Okay, I have done that. Unfortunately nothing changed.
So the user does get created (I tried with Google login):
<img width="827" alt="Screenshot 2023-09-01 at 17 46 48" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/cbc71466-4214-4e16-b27b-f6aafefc783a">

But still doesn't have the e-mail field. I tried creating a new project and tried with a new fake e-mail address and it worked:
<img width="1138" alt="Screenshot 2023-09-01 at 18 17 03" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/55cd07d7-5504-4788-9c77-8768190aa0f1">

However, I tried the same thing on my project now, with the same email address:
<img width="832" alt="Screenshot 2023-09-01 at 18 17 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/42170b07-cd61-4ef9-913c-76249b69eee5">

I also made sure the Firebase rules are maximally open (same on both projects, all set to true), so it isn't something related to those. I can't find any differences in the projects either... Here's a short video:
https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/0b4bf379-938f-433c-a9ee-97e7437b98af

**Comment by tinrunje** [comment]
@hariprasadms The only difference in the projects is that my original project had a SHA-1 key, and the new "test" one didn't. I removed the SHA-1 key from the original project as well, but didn't solve the issue.

**Comment by hariprasadms** [comment]
@tinrunje - Hi, Thanks for the details. Looks like it is project specific issue.

**Comment by aemelyanovff** [comment]
@tinrunje I'm unable to reproduce this issue either, but I made a change that hopefully will fix it for you. It's basically [this](https://stackoverflow.com/a/73343193). It will be available in the next update.

Please try again after the next FlutterFlow update and let us know if it worked.
