### ISSUE TITLE
CanvasKit not showing (some) images

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1395]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, when deploying with CanvasKit, some images (~80% of user uploaded images) don't get displayed. However, in test mode, these work perfectly fine. Here's the same account/user in CanvasKit and in test mode. 
CanvasKit:
<img width="408" alt="Screenshot 2023-09-01 at 12 23 26" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/fdbd0ff1-183f-4b55-81ab-ea6464b3207a">

Test mode:
<img width="278" alt="Screenshot 2023-09-01 at 12 25 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/5620a674-11ee-479c-a9d3-8c5764a770c8">

We can see that in test mode these images (user uploaded some demo images of a character icon) are shown and in the Canvas Kit version they aren't.

### Expected Behavior

Images are shown appropriately.

### Steps to Reproduce

1. Create new page
2. Add a button to upload an image/save an image
3. Add an image widget to display the uploaded/saved image
4. Deploy using CanvasKit
5. Check the image in deployed version

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Klcn635ZNvttZ+KqNafkwpGAsQ3J+ULswluttdEo2GJetG7lzRc/BQExWXLyjYEFAJ2aWmXwd7PfqkYb9Mu4qMk2AfbZFyJdyZA7zeHiQMK7XPbWVfW1QLJtWN0C558Ks2x1BOu9ZLSEG3U+uOfO8RXXqNLLIDkcFAMiLJdeK2SrDX1iXc2URm05KZDPz

### Context

Show the data user inputs appropriately.

### Visual documentation

Shown above.

### Additional Info

/

### Environment

```markdown
- FlutterFlow version: v3.1 (released 28 Aug, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 116.0.5845.110
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @tinrunje - Thanks for submitting the issue. CanvasKit web deploy is in beta stage and the issues are expected. To understand the issue more, please share the error details you see in browser console when you see the missing images.

**Comment by tinrunje** [comment]
Hey @hariprasadms 
Okay perfect. I got some interesting errors. So the error is:
Failed to load resource: [IMAGE-LINK]. Origin [URL] is not allowed by Access-Control-Allow-Origin. Status code: 200

Sorry the image link and the url aren't getting copy-pasted.
Now, to my unprofessional opinion, I believe "Access-Control-Allow-Origin" needs to be added to the header from the server-side.

**Comment by hariprasadms** [comment]
Yes. Update the header and see how it works.

**Comment by tinrunje** [comment]
I tried adding it, nothing changed... 
Maybe I added it incorrectly?

**Comment by tinrunje** [comment]
I added it using this:
https://thehotcode.com/firebase-gcloud-fix-cors-issues/
And it worked. Maybe you code include this step in the docs or something.
Found it on this link:
https://legacy-community.flutterflow.io/c/community-tutorials/how-to-deal-with-those-cors-issues
