### ISSUE TITLE
Slider isn't working

### ISSUE THREAD

**Issue by jay-electronica** [FlutterFlow/flutterflow-issues#1397]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon adding the FlutterFlow slider widget to my project several problems emerged. 

**First problem:** When setting initial value the slider isn't updated automatically, the indicator stays fixed at the same point on the slider.
**Second problem:** When checking the "Show value" checkbox and testing the slider it doesnt show the indicator that should appear and show the value that is being chosen.
**Third problem:** I've added a text field and linked it to the slider via "Set from variable" but when testing the value of the slider wont be shown in the text field.

### Expected Behavior

1. Indicator should show initial value
2. Should show indicator
3. Text box should show value

### Steps to Reproduce

First
1. Create new page
2. Add slider
3. Set minimum value to 130
4. Set maximum value to 200
5. Set initial value to 170 for example

Second
6. Check Show value checkbox
7. Test in preview

Third
8. Add text field
9. Set from variable (String) - Slider

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiMjf35FOm8tF0L6JbsExqDwWGDs2apI7iusaaCs9fpTtP4kUY876P0hBYMOkTVFMPGK2p14xwayOi+HLCMdeOSueGKZCz6tIawrhVmagVpuTF7jhSH9PI8ZYCXKb07ezsRZ+BLFhSmAFwU2uN+zIShTUQePzIUQ4Sq/LZO4=

### Context

I need a slider but it doesnt work and its very annoying

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/143325076/8f8c034a-41f2-4818-be7c-c058f7bef4b2

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: most recent versions of Chrome and Safari
- Operating system and version affected: macOS 13.5.1 Ventura
```

**Comment by sbis04** [comment]
Hey @jay-electronica, from the screen recording, it seems like you are trying in the [Preview mode](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#12.-preview). In preview mode, variables don't work, please try using the [Test mode](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#13.1-test-mode).
