### ISSUE TITLE
Example: Pages can be renamed to invalid names

### ISSUE THREAD

**Issue by katherineqian** [FlutterFlow/flutterflow-issues#14]
**This is an example bug report that shows clear reproducible steps.**

Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Invalid page names should be rejected so that they don't cause project build failures. At least a project error should be shown so that the user can diagnose the issue.

## Current behavior (required)

Even though an error message is shown, invalid page names are still saved. The project will fail to build, but no project errors are shown.

## To Reproduce (required)

1. Create a page.
2. Double click the name of the page on the page selection panel.
3. Set the name to something invalid, e.g. 0HomePage (invalid because the name can't start with a digit).
4. Observe the error message.
5. Press enter.
6. Observe that the name is saved.
7. Click "Test".
8. Observe that project says "Build Failed". Observe that there are no project errors in the workspace.

## Context (required)

N/A

## Screenshots / recordings

N/A

## Your environment

* Version of FlutterFlow used: 3.0.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 105.0.5195.125
* Operating system and version (desktop or mobile): MacOS

**Comment by wenkaifan0720** [comment]
Hi @bulgariamitko. Are you still experiencing this issue? I just tried and couldn't reproduce.
