### ISSUE TITLE
Single quotes getting stripped from API call header

### ISSUE THREAD

**Issue by bcdefga123456** [FlutterFlow/flutterflow-issues#140]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

API call headers should be able to have single quotes in them.

## Current behavior (required)

Single quotes get stripped from API headers.

## To Reproduce (required)

1. Create a new API call
2. Add header "xyz: abcde'fge'h'"
3. Go to response and test tab
4. See that header now excludes the single quotation marks that were supposed to be part of the header value

## Context (required)

Prevented me from using API calls in certain cases where single quotation marks are needed in the header.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: Latest
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 104
* Operating system and version (desktop or mobile): desktop

**Comment by bulgariamitko** [comment]
@bcdefga123456  I think this is working right now. Can you check and let me know.

**Comment by agreaves** [comment]
Yes, this should be fixed now (it was indeed a valid bug at the time). Thanks for the bug report!
