### ISSUE TITLE
Choice Chips error in setting value and displaying updated setting (see video)

### ISSUE THREAD

**Issue by ALazutin10** [FlutterFlow/flutterflow-issues#1400]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting choice chips, I they are set to appear when a calendar day is set, eg- Sunday, then it doesn't set or update the required page state and a blank text value that is supposed to display chosen option from choice chips. It works when multiple choice chips set one value (a page state for example) but when these values are intermixed with calendar and appear on certain days, they are not behaving as expected. 

### Expected Behavior

Expecting text fields and page state to update every time a choice chip value is set. 

### Steps to Reproduce

1. Create a new page
2. Add a calendar 
3. Create a page state with string type
4. Add two sets of choice chips
5. Make one of them visible only when calendar day is certain day (eg Sunday) 
6. Add two text fields that show value of each of the choice chips
7. Try choosing different days using calendar and witness how when selecting choice chips, display values behave

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlvHlz85IvuZE7qrycMF4iWIwGVgLaJJEktYbdzwYCLbpPe9+O+LSalhWYMvnYHlhHGKb8WI0pejwkt/9LPArNSyCfKJC+ZZAUTuXTXq8RbKSDYeWXEZSGp9YIFSX1Kavgx0lBNdpdE0t112YIeq9Uh7fGZu/Zwh9f6PHaOI=

### Context

It is a vital part to the project so users can select a time for a particular day and make a booking. This bug stops this procedure as the correct time cannot be passed correctly. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/119873933/7c9d12ce-16f1-4b0a-9b44-f9a61a461979

### Additional Info

Please see video. The larger pink string is page state, two smaller texts at the bottom display choice chip value. As you can see, the first value doesn't update when chosen, only when second one is chosen. 

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Mac Desktop App
- Browser name and version: Desktop app
- Operating system and version affected: MacOS. App for iOS/Android
```

**Comment by MohitKandu25** [comment]
I've been facing the same issue! In my case, I have a state variable that shows different choice chips based on the current state value. The first choice chip works fine but the next one doesn't do anything! I tried to print some data on choice chip actions and the first one prints the data but second one doesn't.

**Comment by ALazutin10** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/119873933/668abbf3-5f2e-406b-ae15-5dbc4fc7cdbd

This is an issue indeed. Here is a separate screen showing specifically this issue. There is one page state (Pink text) and all other texts should be set when time is set using choice chips for different days. Clearly, only one day works (when calendar day is same as current day) else it doesn't set at all.

**Comment by ALazutin10** [comment]
@kevintonb @katherineqian Do you have any updates on this?

**Comment by ALazutin10** [comment]
Continue action... it hasn't been addressed

**Comment by ALazutin10** [comment]
@hariprasadms @aemelyanovff Guys, are you able to take a look at this? The allocated engineers to address this case are idle and don't respond anywhere. I contact you since you answered some of the technical bugs here. For almost a month, no reply anywhere.... I hope you guys can either answer or direct me to a communicable source

**Comment by sbis04** [comment]
Hey @ALazutin10, so sorry for the late reply. This issue looks quite similar to [this issue](https://github.com/FlutterFlow/flutterflow-issues/issues/1321), if it is then I have included a solution there. Let me know if that helps.

**Comment by ALazutin10** [comment]
@sbis04 I have implemented the solution mentioned, this issue is different but the solution (labelling each choice chip set in "testing") solves the bug. I updated recently and in the latest version, from a few days ago, this fix was possible. Thanks for your input and help in solving this!
