### ISSUE TITLE
"Safe Area" not working as in the Flutter Flow Deep Dive

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1403]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

At this point in the Flutter Flow Deep Dive video...

https://youtu.be/mlR6rcWexdI?si=W8imnSIqHnjgE926&t=224

...the gentleman adds a text widget that automatically drops 30ish or whatever pixels below the top of the screen. 

That at this point in the video...

https://youtu.be/mlR6rcWexdI?si=1tJbuIpUx86jFU6g&t=268

...he points out the Safe Area and how it works. 

But that is not working on my screen

![Screenshot 2023-09-04 at 6 57 27 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/81047785/12a02804-08ba-491a-b14e-41049dadc35c)

I have reproduced it from blank. 

### Expected Behavior

Have a working Safe Area as in the video

### Steps to Reproduce

Follow the instructions in the video exactly

1. create new project
2. name it
3. select blank project
4. delete everything
5. drag in text field
Nothing happens

see loom

https://www.loom.com/share/8576062cecd64b0aa8c325c171b913ef

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goe5I0aX9LcJqhQIgQ0QnU7gnlO1ucx4cG5SvP+0iYc/BQ0NKT/KqeH59MGaGgXwzwejKiezlV8AqPSmtfapa0JVAaQLxZHmuVLbTPLqOY3N7HdpgI0yF56WJvhFQCLZYSVok1Fz2Nq3qNleeY8aSfxBlZ7vfcPo=

### Context

So, the first feature demonstrated in the first recommended video from the team failing is not great for confidence in the rest of the product. 

But based on the number of people I am hearing talk about this I'm pretty sure that this is a temporary thing or maybe something weird on my end.

### Visual documentation

https://www.loom.com/share/8576062cecd64b0aa8c325c171b913ef

### Environment

```markdown
- FlutterFlow version: latest
- Platform: iOS (going through the tutorial)
- Browser name and version: Chrome latest
- Operating system and version affected: Mac Sonoma
```

**Comment by sbis04** [comment]
Thanks for reporting the issue. It should be fixed in the next update!
