### ISSUE TITLE
iOS 16.6 Loading/Pre-load Stuck on White Screen

### ISSUE THREAD

**Issue by VOSOps** [FlutterFlow/flutterflow-issues#1405]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow (and it seems also Flutter) app is stuck in pre-load (white screen) on iOS 16.6, and does not load/move past the screen.
- The same app was working on previous verions.

App is working properly on Play Store.

### Expected Behavior

1. Loading splash/login page, to give user access to app.
2. Loading plash/login screen

### Steps to Reproduce

1. Download app from Testflight
2. Open app on mobile/iPad with iOS 16.6

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzeflsYtPj7xY17X5bcBvhjoRG0d9TL07ttYbZxUjIuPtBJh+O8/OXxFtTtejYENhHGGbrFg1/srpuN/tD/AoNU6YfJhC/qpcYBXwXXq8RYTTCqiKfnxtO8FgJhWY0cCnqiR5ObNZSVIb3DqHNueuQgvdN5u/Zwh9f6PHaOI=

### Context

Users on iOS are not able to log into the app.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/113295522/b60c3f70-9c59-4063-8dc6-d14c11f927e4

### Additional Info

Issue Record on Flutter Github:
https://github.com/flutter/flutter/issues/131319

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Apple: Testflight, "On-device"
- Browser name and version: "On-device"
- Operating system and version affected: iOS 16.6
They say the issue has been resolved in Flutter 3.13.0. When is that version going to be available in Flutterflow?
```

**Comment by webuijorgeGL** [comment]
This is happening to me as well, once the app is installed from TestFlight or from the App Store just in real devices. The issue is not happening on simulators.

`✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-x64, locale en-CO)
    • Flutter version 3.10.6 on channel stable at /private/var/folders/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (8 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1`

**Comment by sbis04** [comment]
@VOSOps It seems like the issue is occurring because you don't have Remote Config enabled in your Firebase project. This is the issue I faced when I ran the project locally:

<img width="1004" alt="Screenshot 2023-09-19 at 6 51 07 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/7cccae7e-77dc-4e9a-8f1a-9168e207b2de">

Make sure you follow the Remote Config setup docs [here](https://docs.flutterflow.io/settings-and-integrations/project-setup/firebase/remote-config).

In case it still doesn't solve the issue, [this solution](https://stackoverflow.com/a/54603795) might help.

**Comment by VOSOps** [comment]
Hi @sbis04 I'll check out that solution. From my knowledge, Remote Config is enabled, but I'll disable it, and reenable and see if that helps. Thanks for the solution.

**Comment by VOSOps** [comment]
> Hi @sbis04 I'll check out that solution. From my knowledge, Remote Config is enabled, but I'll disable it, and reenable and see if that helps. Thanks for the solution.

Issue resolved. Thanks @sbis04 for the solution. I had to disable, and reenable Remote Config, and it seems everything is loading successfully.

**Comment by sbis04** [comment]
Glad to know that! Thanks for letting me know! 😄
