### ISSUE TITLE
Cannot create or edit any theme widgets after duplicating project of previous bug report

### ISSUE THREAD

**Issue by k98kurz** [FlutterFlow/flutterflow-issues#1406]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to create or edit any theme widgets in either the original or duplicate project.

### Expected Behavior

I should be able to create and edit theme widgets.

### Steps to Reproduce

1. Open the project.
2. Try to create or edit a theme widget.

Idk how this project got into this state, so I do not know how to reproduce it from scratch. This is the same project that has the [glitchy action chain](https://github.com/FlutterFlow/flutterflow-issues/issues/1396) which took many hours to create.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8klPHlx5NOmN9J7arAacZvmjs5JjsjauYzju1ERRQaJurnEoYiOsn8V1tucsyCf1VYeWeJ8X4Ip9bXkezyUcYCFwuIQ718+alybxWXRXOXVZSKBcyORXB8GfJnCk/G1KCOiiRAPrNsV1I47VOIGd+tQibXHabRDFgSQsr9Nr3LnVa+LhzGFDh2tmNecCfn

### Context

I am trying to just make progress on this project, but it looks like somehow it has gotten into a state where it is becoming increasingly infeasible to continue working on it. I really don't want to start over from scratch and might just give up at this point. If projects can just randomly get into this broken state where progress can no longer be made and hours of work can just go down the drain, then the platform is fundamentally broken (or if it is specific to team accounts, then the paid product is fundamentally broken).

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/4357561/4c4ed361-06d6-4a14-ac27-f3a753f3b48f

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: web
- Browser name and version: Vivaldi 6.1.3035.302 and Chromium 116.0.5845.140
- Operating system and version affected: Ubuntu 22.04
```

**Comment by k98kurz** [comment]
Did an experiment where I duplicated the project once again and progressively deleted everything. I was able to add a theme widget only after deleting the Design System. Is it the intended behavior to be unable to create new theme widgets if a Design System is active? If so, there should be some kind of indication on the page that the ability to create theme widgets has been restricted due to the design system -- or better yet, it should redirect to that Design System.

**Comment by wenkaifan0720** [comment]
Hi @k98kurz. Yes, if a design system is selected, then all the theme widgets are coming from that design system and you can not create a new one in the current project. We changed the mouse cursor to reflect this, but we should also add a button that redirect you to the design system.
