### ISSUE TITLE
Test Mode UI has pixelated text  and spacing/colors that dont match preview mode

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#1407]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in preview mode, spacing, text, borders, colors etc. look crisp and as intended. however, when I run in test mode, the borders and text appear to be pixelated and not as crisp. The colors also look more saturated and the spacing gets messed up to where text is going below the bottom of the profile pic in the UI. 

see picture 1 for the intended view. see picture 2 for text mode. borders and text do no appear to be as sharp and the colors look more saturated. additionally the spacing is off. 
<img width="602" alt="Screenshot 2023-09-03 at 5 38 52 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/2e2af208-b987-466d-8807-c82bd8096467">
<img width="614" alt="Screenshot 2023-09-03 at 5 38 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/a3ff2703-b445-4c09-8723-1de1fa2c7a83">

### Expected Behavior

I just want test mode to look like preview mode with proper spacing, identical colors, non pixelated text, and smooth borders.

### Steps to Reproduce

1. create page
2. add column
3. add row with containers with gradient
4. add tab bar
5. add text for headers
6. add containers with pictures and text info

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0sNobbxAjIoDoPJkUaeOlVxdvYMOmYFFlKEWIoEQept7qidrtCMInOgWsQIBnyc1cUAzzRnu/aoStCKW0Y3MlM+hWCh2z0Z2RnSV7LbNpS3gE7E2mCeqUfHbcK736Zwh9f6PHaOI=

### Context

It is completely messing up the UI making it look poor and unusable. 

### Visual documentation

see images above. 

### Additional Info

see above

### Environment

```markdown
- FlutterFlow version: latest
- Platform: mac desktop web
- Browser name and version: chrome
- Operating system and version affected: mac os ventura 13.3.1a
```

**Comment by aaronmt93** [comment]
bumping

**Comment by agreaves** [comment]
Hi @aaronmt93, apologies for the delay in response. This is actually because of the difference in how the application is rendered on the web.

In order to address this, please go to Settings -> Platform, and then check "Web" and check Advanced Settings -> "Use CanvasKit". This will enable the different rendering engine for Run/Test/Web mode (see [Flutter docs](https://docs.flutter.dev/platform-integration/web/renderers)).

If you're having any trouble loading images after this, you may have to take a additional steps (see the "CORS Proxy for Images" setting and its tooltip). Hope this helps!

**Comment by aaronmt93** [comment]
its not just on the app, its on release mode in the app too on my phone where the text is pixelated. also spacing gets messed up when I use emojis and if I dont set a line height

**Comment by aaronmt93** [comment]
@agreaves heres two pictures for reference, one is a screenshot from the desktop app in the builder. the second is a screenshot on my phone. as you can tell the phone is pixelated. 

<img width="202" alt="Screenshot 2023-09-18 at 9 30 23 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/886f916e-7fa1-4304-aeb0-9d022a84d47b">
![IMG_8842](https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/a9bcd0a2-ebdb-421d-b8a7-787f1ece8dda)

**Comment by agreaves** [comment]
Hi @aaronmt93, how are you viewing the app on your phone and what phone / browser are you using?

**Comment by aaronmt93** [comment]
Hi @agreaves, I am using an iphone 11 and chrome. as you can see in the first screenshot, the spacing seems to be off in test mode and will do the same thing on my phone. that was when using default line heights. if I define the line heights they will be as shown in preview mode. I'd prefer if I could just use defaults however. and then the text pixellation dont know why that is.

**Comment by agreaves** [comment]
Interesting... I'm not sure exactly what the issue is yet, but I'd like to ask a few more questions, sorry if it's a lot:

1. Does this occur only when using a custom font?
2. What do you have to set the line heigh to? And can you show me a screenshot of the difference between setting the line height and not setting the line height?
3. Have you selected the option to use CanvasKit and tried re-deploying?
4. On your iPhone, are you testing the native app (via TestFlight / local debug) or the web deployed version on Chrome?

Mainly I want to understand a bit better how you're testing this and what steps you've taken to try to address it so far. Thanks again for your patience, I'm hoping to get to the bottom of this! 🙂

**Comment by aaronmt93** [comment]
hi Alex, 

1. I'm using a google font (outfit)
2. screenshot of what is working here...I also should have mentioned I made a component as. screenshot of the older version that looked off in test mode is second pic where there were line heights. 

<img width="1512" alt="Screenshot 2023-09-24 at 9 49 27 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/079bfd86-71fe-4fef-adf9-e6c8017a8621">
<img width="1512" alt="Screenshot 2023-09-24 at 9 53 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/5367974d-40e6-4482-b70f-cf4d741208cb">

3. Yes believe I have canvas kit set up. Since moving to component, creating a new page, and setting line heights it no longer seems to be an issue. But I had made a copy of the prior page and when i run that one in preview and test it does look off even with canvas kit enabled. Since its resolved with my steps for me personally I'm no longer worried about it at the moment but whatever it is still seems to be causing a difference in how the test mode looks vs preview mode. As you can see the last row with the chat bubble overhangs the end of the picture where as I'd set them up in the project to be perfectly aligned as seen in preview mode. even if there is nothing wrong bug wise, the difference between preview mode style and test mode style makes it really hard to tell if there is issues in the UI due to the inconsistencies in style between the two. 

4. I am testing via test mode in flutterflow on google chrome. On phone, I'll download code and run via android studio release mode.  It seems fine here. So think maybe the issue is something to do with test mode on flutterflow where the project doesnt look right there. 


<img width="1023" alt="Screenshot 2023-09-24 at 10 04 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/73142c60-d6d4-4985-b02e-4b3bb944b4c0">
<img width="586" alt="Screenshot 2023-09-24 at 10 05 00 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/f148e7ae-1be2-4d1d-b29c-5674aa935e04">

<img width="589" alt="Screenshot 2023-09-24 at 10 05 09 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/620b60d1-af96-481d-a91f-e8d75bd2309a">
<img width="414" alt="Screenshot 2023-09-24 at 10 20 59 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/fda86f7e-24d2-4f44-a7d6-6fa2e0c1317b">

**Comment by aaronmt93** [comment]
even looking at these pictures some more, you can tell that the iphone version ends up looking closer to what I saw in preview mode than in test mode. for example, in test mode, the test looks bolder than what is in preview mode or iphone. I spent a ton of time iterating on the project since test mode looked off and not consistent with what I wanted.

**Comment by aaronmt93** [comment]
@agreaves the new update ended up fixing a lot of the pixelated text issues. the app looks AMAZING now on iphone as I had intended it in the figma. 

re the line heights, i've realized it seems the issue is if there is an emoji, it throws off the line heights making them inconsistent if they are left to the default settings. it'd be great if we could add line heights to the text theme settings so I don't have to set it every time I add a new text and reset all my text widgets individually if I adjust line heights.
