### ISSUE TITLE
Login function not working in community on direct access

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1408]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Created account with google auth

Tried to post a question in community, asked me to log in

No google auth login option for the community

Deleted Google auth account

Signed up with same email address and a password, NOT with Auth

Worked fine, new account setup 

Tried to log into community.

Didnt work. "Member not found with given credentials"

Looked around and can't find any "sign up" anywhere obvious or not obvious

Clicking "back to Flutterflow" in the top left DOES work.

So my browser/flutterflow thinks I am logged in there. 

Community does work, if I click on the Community button from within app.flutterflow. 

### Expected Behavior

googling flutterflow community and clicking on that link I should be loggen in already, or the login screen actually works

### Steps to Reproduce

see above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

there is no bug report button for community page

### Context

get to the community to ask a question. 

### Visual documentation

none. any I make would expose email and or credentials

### Environment

```markdown
- FlutterFlow version: latest
- Platform: macOS
- Browser name and version: chrome latest
- Operating system and version affected: sonoma
```

**Comment by hariprasadms** [comment]
Hi @chuggmuffin - I presume, it is already resolved to you. If you are still facing login issue. I suggest check with FlutterFlow support team. Git repo is mainly for FlutterFlow features related issue. Hence I have marked the issue as support issue and closed.

**Comment by chuggmuffin** [comment]
It was still a bug as of a couple of days ago.

You can't access the community from the community page.

You CAN however log in via the flutterflow "resources" section in the app
itself, so I have had no issue getting in recently.

I helped someone else who had the same issue.

Thanks!

Brian

**Comment by sbis04** [comment]
The community page uses SSO login via FlutterFlow, so initially you need to visit the community page from the Resources section inside FlutterFlow (it uses the same credentials for the community). But once you are logged in properly into the community, then the credentials should be cached and you should be able to visit the community page directly.

**Comment by chuggmuffin** [comment]
Hi Souvik thanks for responding :)

Yeah I get that I’m there frequently thee days

My issue is it makes the login page on the community page confusing at
best.

Instead why not just say to the user “access the community page from the
flutterflow resources page” as opposed to having an impossible to access
through login portal?

**Comment by sbis04** [comment]
Yes, we are looking into whether there's a way to disable the login in the community or redirect to the FlutterFlow app for authenticating the user. I know this is making it confusing for the users.

**Comment by chuggmuffin** [comment]
Ok cool!

Glad to hear you're on in :)

Thanks for the response.

B
