### ISSUE TITLE
UI editor completely fudged. 3 bugs in first 10 minutes of deep dive. Cant add rows, columns, containers without editor breaking

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1409]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Just watch the video. 

https://www.loom.com/share/3b837b6afd314b13b6283bae6abe396f

### Expected Behavior

This video to work

https://www.youtube.com/watch?v=mlR6rcWexdI&ab_channel=FlutterFlow

### Steps to Reproduce

follow the deep dive. nothing works

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grssF1c/+YcFqhQIgQ0QnU7gnlO1ucx4bNZTkBJYIZuD4ZUNKQs+YdG1Le1WkjT4JpqzIiYT2U/FdKTCVfqJz0JVPEhXwfEiQVK6xELjhf3F8MJ9TFWK7y6WnpAl4WcFac1Jn7XGDNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I can't get 10 minutes into the deep dive video without 3 major bugs

### Visual documentation

https://www.loom.com/share/3b837b6afd314b13b6283bae6abe396f

### Environment

```markdown
- FlutterFlow version: 3.1.04
- Platform: mac
- Browser name and version: Chrome latest
- Operating system and version affected:  Sonoma latest
```

**Comment by hariprasadms** [comment]
Hi @chuggmuffin - Thanks for submitting the issue. I have seen the points you have explained in the video. I can say all those points are working as expected. 

1. The safe area affect you can only when you have selected the devices frame for the page. 
2. Widgets copy and paste working as expected. While pasting you should select a parent widget to past the child widget and it works accordingly. 
3. Storyboard pages zoom in and zoom out is working as expected. I presume the observation what you see its related to zoom in and zoom out at your end. 

I can confirm that the issue is not a bug.

**Comment by chuggmuffin** [comment]
1. The issue is different from the original video as posted. Completely
possible that you guys changed the editor behaviour in the interim which is
fine.

2. Correct that was me not understanding core flutter/dart container
dynamics. My apologies.

3. Could be. Still not working on my end tho and my zoom
functionality works fine it Miro and other zoom in and out websites so
theres an edge case somewhere in there.

Thanks for taking a look!

Brian

**Comment by victoriahuang1** [comment]
@chuggmuffin you should use Cmd+Scroll to zoom for storyboard

**Comment by chuggmuffin** [comment]
Thanks Victoria!

I have tried every single combo on my keyboard...

CMD
CMD+Shift
option CMD
crtl CMD
shift ctrl cmd

Everything I can think of! Using a Magic Mouse... maybe that's it?

Brian

**Comment by victoriahuang1** [comment]
I have never used a magic mouse, but you should be able to scroll with it:
https://support.apple.com/en-us/HT204895#:~:text=Mouse%20gestures%20require%20a%20Magic%20Mouse.&text=Click%20the%20right%20side%20of%20the%20mouse.&text=Slide%20one%20finger%20up%20or%20down%20to%20scroll.&text=Double%2Dtap%20with%20one%20finger,of%20a%20webpage%20or%20PDF.

**Comment by chuggmuffin** [comment]
100%

I scroll no issues in every single other scrolling app I have ever used...

Miro, Capcut, Canva, Adobe...

...even now I am CMD scrolling in Supabase' Schema visualizer.

I have a lot of scrolling experience.

It's quite strange which is why I figured it was a bug.

The only thing I can think of is something screwy with Mac Sonoma Beta but
thats all that come to mind right now.

B
