### ISSUE TITLE
List of Maps Update Document in Firestore Causes Build Failure

### ISSUE THREAD

**Issue by morgantrainer** [FlutterFlow/flutterflow-issues#1410]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page in Flutterflow named scoring_line and I have a list of custom data type. The datatype is named TestItem which has 7 keys defined in it. I use this data type as a list in a page. I have a Firestore collection that has a field which is an array of maps that matches the List of TestItem in Flutterflow. My page in FF has a data table where I generated dynamic children and show them in the data table as textfields to allow the user to update them. I set an action on the datatable that On Data Change to update the document reference with the data from the generated dynamic children. When I go to Test I get this message:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/f8ec679f-a500-4143-a502-90fff8476df2)

Since this is no code I want your help to find the error. In my debugging I used the field from the Firestore collection to update itself On Data Change in the data table and it has no error (of course nothing is updated since it is the record I read before updating it). The main point is that I get no error. When I change from the Firestore collection field to the Dynamic Generated Children variable I get the error. Please help me fix it.

### Expected Behavior

I expected that when Test mode comes up that I can retrieve the record into the data table. I can then change a field in the data table and upon exiting the field it will kick off the action to update that field into the list of maps on the Firestore database.

### Steps to Reproduce

1. Create a collection in Firestore that has a field which is an array of maps.
2. Create a custom data type that has at least 2 fields to match the map in Firestore.
3. Add a data table to a page in FF.
4. Add a backend query on the data table object to get a single document from the Firestore collection.
5. Generate children from a variable on the data table object from the queried collection document on the field for the array of maps.
6. Add a column of text fields in the data table and set it from the variable to one of the fields.
7. Create an action on the data table that On Data Change to make a backend call to Firestore to Update a Document.
8. Pass the document reference from the backend query on the data table.
9. Pass the variable for the generated children 
10. Try to run in test mode (and get the nice RED screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjs/l25F2pbxb15DuY8Awij4vIjs/Ro0zj+tuQis8GZT0B4kcYs+kfklUONOkYXNcP1mgnmUX/MqPiIaSOOwqPU6qQb5Mzrt2EDuXLUmVVJSQBq63b39AHdpmfXaDy7eNgglTHPd0SCUb72aUF96+ZA3cH4DyOGseRea4XdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to update a list of maps through FF into Firestore.

### Visual documentation

1. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/eba4ca26-d531-48c9-85e9-02537bc02a98)
2. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/953f918c-a68b-42d0-8cea-e293a769bf6b)
3. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/1611d2ac-2c9c-4d6a-9417-7fa408fcc296)
4. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/cede5a1b-ac9e-4e71-b5ab-54a76c49f596)
5. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/68259397-fcbc-4a7a-a0bb-5baa40204d81)
6. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/45918d0e-633e-446f-9039-688e51ef5d33)
7. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/be506a19-090f-4e09-a48e-95259845e3c7)
8. 9. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144192894/2e87cb1e-7b16-42fb-ab96-45602adc65d3)

### Environment

```markdown
- FlutterFlow version: v3.1 flutter 3.10.4
- Platform: Laptop 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz with 64Gb RAM
- Browser name and version: Chrome Version 116.0.5845.141 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Home V 22H2
```

**Comment by joshua-ffio** [comment]
Hi @morgantrainer, this issue appears to be specific to your project and because this issue tracker is intended for general bugs that are applicable to all users, this is classified as a support request and will be closed.

I took a quick look at the steps you described and I have a few preliminary observations that hopefully can help you:

It seems that you've set your action to update your document to the `onDataChanged` trigger on the DataTable, which is where you've also set your backend query. This `onDataChanged` is triggered when your firebase query changes, as seen in the tooltip next to the action name:
<img width="605" alt="Screenshot 2023-09-22 at 1 31 25 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/141682285/edb2bb70-eac5-458a-8c1e-69fbe8852120">

In order to react to changes to individual TextFields, you will want to add an action to the textfield itself, either onSubmit (probably more appropriate) or onChange.

If you need more help with this issue, please use the chat support or contact support@flutterflow.io 

Thanks!
