### ISSUE TITLE
Page parameters JSON type does not generate correctly inside push_notification_handler.dart

### ISSUE THREAD

**Issue by Neillbar** [FlutterFlow/flutterflow-issues#1414]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On my app i have a Page called "CommsEmailOpen" and it takes in a JSON parameter. 

On my my page parameters i have a JSON type parameter is called "data" and is of Type JSON. When i download the code inside the push_notification_handler.dart the generated code for parameters there is a bug. 

this is what it generates inside the parametersBuilderMap variable ->

 'CommsEmailOpen': (data) async => ParameterData(
        allParams: {},
      ),
      
    this is what it should generate 
      
       'CommsEmailOpen': (data) async => ParameterData(
        allParams: {
          'data': getParameter<Map<String,dynamic>>(data, 'data'),
        },
      ),
      
      if i add a parameter like a String it looks like this -> 
      
      `  'CommsEmailOpen': (data) async => ParameterData(
        allParams: {
          'subject': getParameter<String>(data, 'subject'),
        },
      ),`

      
      

### Expected Behavior

   `     'CommsEmailOpen': (data) async => ParameterData(
        allParams: {
          'data': getParameter<Map<String,dynamic>>(data, 'data'),
        },
      ),`

### Steps to Reproduce

1. Create app on Flutter flow
2. Create page with a parameter called "data" make the type "JSON"
3. enable push notifications for the project
4. download code
5. navigate to push_notifications_handler.dart inside lib/backend/push_notifications/push_notifications_handler.dart
6. look at variable parametersBuilderMap, look for the page name that you created and look at the ParameterData object passed to your page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xl8nl5c9NpbxY17X5bflV+WAUKVh6RY08lu1QEBI1GIirE7MQds/+T3BZOMu6dFZUP2GJmm0zzNLRv97tC8IrAByJb6Y7yc9UcDn/eHGVRJTUPZe0fEZQGZ9bIECizpuZsBBCHMxtL14Z702DfejLYDPtHq7EDEgzJeX8ELr/gXi6KybkG30Jg1ZSfCvr

### Context

I am sending a push notification to a device with initalPage and parameters, I would like to access the JSON object when navigating to the page. It works if i do every field separate, but i would like to pass the whole JSON object

this is how i am currently by passing the bug to make it work

![Screenshot 2023-09-07 at 11 49 18](https://github.com/FlutterFlow/flutterflow-issues/assets/43991798/f82188d4-ffd0-4ee3-932a-e902422b181e)

this is what i want to achieve ->

![Screenshot 2023-09-07 at 11 50 04](https://github.com/FlutterFlow/flutterflow-issues/assets/43991798/6e9b9923-2a76-4e92-a9bc-39db8d721f89)

### Visual documentation

![Screenshot 2023-09-07 at 11 55 00](https://github.com/FlutterFlow/flutterflow-issues/assets/43991798/53d07497-7795-49fd-8a43-5822090eecb1)

### Additional Info

-

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:ANDROID || IOS
- Browser name and version: N/A
- Operating system and version affected: N/A
```

**Comment by katherineqian** [comment]
Hi, I'm so sorry for the late response here. I was not active on maintenance. The JSON data type is currently not supported as a parameter for push notifications. However, I have implemented support for it and the change will be available in the next update. Thank you for reporting this.

**Comment by katherineqian** [comment]
Hi, I'm sorry to bring you this update, but we had to close this feature request for now until a larger upgrade to push notifications  is made. Supporting JSON currently would only work partially and break in several cases. I'm going to reclassify this as a feature request.
