### ISSUE TITLE
Upload media Web - Cannot limit source options for video upload on web

### ISSUE THREAD

**Issue by PierreSmn** [FlutterFlow/flutterflow-issues#1415]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using "Upload media" for video uploads from a web app (ios in my case) you cannot limit the sources options. 
The user will always get to choose between Gallery - Camera - and file upload
You won't be able to limit users to only use their photo gallery for example. 

![IMG_1607](https://github.com/FlutterFlow/flutterflow-issues/assets/58378528/5476686c-0f34-42b7-ae9a-628a2957b828)

This cannot be altered by changing the settings in Flutterflow, for the media upload.

<img width="326" alt="Screenshot 2023-09-07 at 11 55 52" src="https://github.com/FlutterFlow/flutterflow-issues/assets/58378528/dbd9b3da-de9f-4d9a-be98-d8f2ba4b35f8">
<img width="305" alt="Screenshot 2023-09-07 at 11 55 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/58378528/61f96f5a-f76e-44f3-a2c7-06786dd68d63">

Even with the right selection, supposed to prevent user from being able to use the camera, the options will remain the same. The user will have to choose between the 3 options. 

### Expected Behavior

A user of a web application should be limited to only upload media from his gallery if that was selected in Flutterflow. 

### Steps to Reproduce

1. Create a new page for Web use
2. Add a button with Upload media action
3. Limit user to video upload and only from gallery 
<img width="305" alt="Screenshot 2023-09-07 at 11 55 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/58378528/8e825902-5e3a-47bc-a607-b5a4b127cdd4">
<img width="326" alt="Screenshot 2023-09-07 at 11 55 52" src="https://github.com/FlutterFlow/flutterflow-issues/assets/58378528/0446120e-bc3e-4d88-a441-db05a22f70ae">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lcmA7ZNIrsBE1qqBcMJVtDw5JmYha4IV0sJBaCwqGJToPLUMPsneVFRuZrygYXw/PmCGuH0d/PfqiPLLKvFdZU+VRt1J1c1qShXxXl6uV5eVEc2dfW1fN99XFX6d0p2FhB1TJtNYWGwg1EOMBvDIfAHDH4T4Ckc4RM6lJdeK2SrDX1iXc2URm05KZDPz

### Context

It may be another bug actually but Video quality for web app media uploads from Camera are terrible. 

Because of that I need to limit my user to only upload from Gallery to insure high quality of videos. 

### Visual documentation

No addition to previous documentation

### Environment

```markdown
- FlutterFlow version: v3.1 (released Aug 28, 2023)
- Platform: Web (chrome) and user side Safari, Ios
- Browser name and version: Chrome 114.0.5735.133
- Operating system and version affected: macOs 13.5.1 (22G90)
```

**Comment by sbis04** [comment]
I looked into this, but unfortunately I think there's no way we can limit those options from showing up on iOS web. Seems like it's a native menu implemented by Apple for web (while choosing from gallery).
