### ISSUE TITLE
Firebase auth with Phone Number in IOS Real Devices

### ISSUE THREAD

**Issue by LILETOAL** [FlutterFlow/flutterflow-issues#1416]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I implemented correctly the phone sign in in FlutterFlow (page A where you input the phone number with a button with 2 actions in this order: updating app state to save the phone number, Auth phone sign in with correct parameters) (page B where you input the OTP Code sent through SMS).
Please note that auth functions properly in Android Real Devices.

1-On the Flutter Code Side FireBase Support told me that the code:

__________________________________________________________________________________________
await authManager.beginPhoneAuth(
  context: context,
  phoneNumber: phoneNumberVal,
  onCodeSent: (context) async {
    context.goNamedAuth(
      'AUTH_SmsVerification_5',
      context.mounted,
      ignoreRedirect: true,
    );
  },
);
__________________________________________________________________________________________|

shouldn't look like this but like below:
__________________________________________________________________________________________
await FirebaseAuth.instance.verifyPhoneNumber(
                          phoneNumber: phoneNumberVal,
                          verificationCompleted:
                              (PhoneAuthCredential credential) async {
                            // This callback is called when the verification is completed automatically.
                            // You can handle it appropriately, e.g., sign in the user.
                            // ANDROID ONLY!
                            // Sign the user in (or link) with the auto-generated credential
                            await FirebaseAuth.instance
                                .signInWithCredential(credential);
                          },
                          verificationFailed: (FirebaseAuthException e) {
                            // Handle verification failure, e.g., display an error message to the user.
                            if (e.code == 'invalid-phone-number') {
                              print('The provided phone number is not valid.');
                            }
                          },
                          codeSent: (String verificationId, int? resendToken) {
                            // Navigate to the SMS verification screen with the verification ID and resend token.
                            // You can use Navigator to push to the verification screen.
                            Navigator.of(context).pushNamed(
                                'AUTH_SmsVerification_5',
                                arguments: {
                                  'verificationId': verificationId,
                                  'resendToken': resendToken,
                                });
                          },
                          codeAutoRetrievalTimeout: (String verificationId) {
                            // This callback is called when the auto-retrieval timeout has passed.
                            // You can handle it if needed.
                          },
                        );
__________________________________________________________________________________________|

Because in the FlutterFlow code there isn't a CallBack.

2 - Even so, when the button with the properly set action is pressed, in the phone number input page (page A), it redirects the user to a reCaptcha check, passing it automatically (the majority of times), but instead of continuing and redirecting the user to the OTP input page (page B) it fails throwing this error:
__________________________________________________________________________________________
[GoRouter] No initial matches: /link?deep_link_id=https%3A%2F%2F{project Id}.firebaseapp.com%2F__%2Fauth%2Fcallback%3FauthType%3DverifyApp%26recaptchaToken%3D03ADU{...really long token...}
[GoRouter] Using MaterialApp configuration
__________________________________________________________________________________________|

where it fails to, though deep linking, get back to the correct page of the app, and instead using the MaterialApp configuration It redirects the user to the first page of the auth process, which btw doesn't work at that point either.
Note that instead of the {...} above there are the correct info related to the app.

Working with the FireBase Support Team we found the issue to be related both to deep Linking and to some configuration error (still to me unknown) on IOS Xcode side of the project.

For the former it suggested to do:
-Double-check your Firebase settings and ensure deep linking is correctly set up. I recommend you check[ this blog related to deep Links in Flutter](https://docs.flutter.dev/ui/navigation/deep-linking) .
-On the iOS side, ensure you've established the Apple App Site Association file and configured both URL Schemes and Universal Links in Xcode. There's an informative blog on deep links that might be helpful for you.
-Ensure that the GoogleService-Info.plist file in your Xcode project is the right one. Also, verify that your iOS app's bundle ID in Firebase Console matches the one in Xcode.

Please note that even if it redirects me wrongfully it still sends the SMS.

I will check again everything they suggested to do, but it is still Unfortunate that I have to go through all this trouble just to make something as important and fundamental as Sign In, that should have worked fine from the beginning, to fail making it work.

Waiting from news. Tommaso.

### Expected Behavior

The expected behaviour is:

After clicking the button on the phone num input page (page A) it should go to the next page (either passing through reCaptcha or not, preferably not), the OTP code input page (page B), sending the message and letting the user sign In in iPhone Real Devices without any issue.

Note that the reCaptcha part is important because it could be all due to the redirecting through deep linking not working properly after the reCaptcha are verified.

### Steps to Reproduce

1. Enable on FireBase side the phone auth method
2. take necessary precautions for Android (taking and uploading necessary SDKs and codes) and IOS (either activating "Silent APNs notifications" or "reCAPTCHA verification", I tried skipping reCaptcha by activating APNs but it still didn't worked)
3. Create 2 pages: A and B plus a blank page to go once the auth is completed
4. on page A put text field and button (2 actions in this order: -update app state to save number -"Auth Phone Sign In" with phone Number-> number in text field and Selected Page -> page B)
5. on page B put pinCode widget and input on this widget the action -> OnCompleted  "Auth Verify SMS Code" with SMS Code -> "PinCode"
6. Download code
7. Open it through VS Code 
8. Run Flutter Pub Get
9. Run open ios/Runner.xcworkspace and after xCode opens go to Runner -> Signing and Capabilities -> input the right apple Developer Account with necessary certifications.
10. Run dart fix --apply on any specific error it throws you want to solve (like unused imports)
11. cd ios -> Run pod install
12. Run and Debug on iPhone Real Device
13. Try to login

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

[GoRouter] No initial matches: /link?deep_link_id=https%3A%2F%2F{project Id}.firebaseapp.com%2F__%2Fauth%2Fcallback%3FauthType%3DverifyApp%26recaptchaToken%3D03ADU{...really long token...}

### Context

I am developing an app that has a clear launch date on September 20th of 2023, I need to fix this error ASAP. Money and Reputation is at Stake.

Furthermore if the app is successful you can advertise that it was made trough FlutteFlow.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/131921499/2e207f68-b9a7-4143-9551-22b13ac2df58

### Additional Info

I have enabled "FlutterDeepLinkingEnabled" ios/Runner/Info

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iPhone Real Device
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1 (to debug through VS Code) and latest ios on iPhone
```

**Comment by sbis04** [comment]
Hi @LILETOAL! Really sorry for the late reply, but I couldn't find a proper bug report code to investigate into the issue. You can generate a bug report code from the Widget Tree by right-clicking on the widget causing the issue.

<img width="530" alt="Screenshot 2023-09-19 at 3 28 47 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/e0f856c0-1131-4668-8a73-e9009c6ba2af">
