### ISSUE TITLE
Wrong "errorBuilder" prop on CachedNetworkImage

### ISSUE THREAD

**Issue by faxioman** [FlutterFlow/flutterflow-issues#1417]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I enable the image option "Show Error Image on fail" I get an error in flutter code:
```
The named parameter 'errorBuilder' isn't defined.
```

### Expected Behavior

Instead of generating an `errorBuilder` prop an `errorWidget` prop should be generated on flutter code.
Also, I suggest to add a test for this property.

### Steps to Reproduce

1. add an image with wrong network path
2. enable "Show error image on fail"
3. kabooom

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ShvLlvJVNofVA1oSJY8dajicXQkB/RYI7lexqEEgjNbbnE7N+XOn9alZVXeG+dgk3eWagjj80+dbMm9z1C/QCIRCec4RI/7piTj3wfEauSqqnOqWeYHBUGshWfWqG06uRgyV/ItdaSV5g1FOIFu++aDPvK6bEOG0NMP21LrnXrgfuQ0SLb3kNh1JWeC/v

### Context

Simple test app

### Visual documentation

This options:
<img width="309" alt="Screenshot 2023-09-07 at 16 49 11" src="https://github.com/FlutterFlow/flutterflow-issues/assets/943944/9dc7b6f8-d3cc-40d8-9cfe-419bda26e933">

Generate this code:
<img width="914" alt="Screenshot 2023-09-07 at 16 54 24" src="https://github.com/FlutterFlow/flutterflow-issues/assets/943944/f66bcb05-92d4-4628-bc30-a818924a7ed6">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: iOS / Android
- Browser name and version: Chrome 116.0.5845.140
- Operating system and version affected: MacOs 13.5.1
```

**Comment by aemelyanovff** [comment]
@faxioman Thanks for reporting the issue. We _just_ fixed it :-)
