### ISSUE TITLE
Component param of type Boolean is not showing property name after binding the value to it

### ISSUE THREAD

**Issue by stepanic** [FlutterFlow/flutterflow-issues#142]
Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Component parameter name of type boolean should be visible
<img width="319" alt="Screenshot 2022-11-20 at 04 22 59" src="https://user-images.githubusercontent.com/315282/202881210-1be82e61-113f-452b-b2fa-8b02dd50a10a.png">

## Current behavior (required)
Component parameter name of type boolean is not visible when it is set to the value from variable
<img width="318" alt="Screenshot 2022-11-20 at 04 23 10" src="https://user-images.githubusercontent.com/315282/202881215-1f93803e-a141-4844-9d3b-a5464063c99e.png">

## To Reproduce (required)
Bind custom function to the component boolean param.

## Context (required)
After binding value to the component param. I want to know to which param existing value is binded.

## Screenshots / recordings
With attached value (BUG):
<img width="319" alt="Screenshot 2022-11-20 at 04 22 59" src="https://user-images.githubusercontent.com/315282/202881210-1be82e61-113f-452b-b2fa-8b02dd50a10a.png">
Without attached value property name is visible:
<img width="318" alt="Screenshot 2022-11-20 at 04 23 10" src="https://user-images.githubusercontent.com/315282/202881215-1f93803e-a141-4844-9d3b-a5464063c99e.png">

## Your environment
* **Bug Report Code:**
* Version of FlutterFlow used: 2022-11-18

**Comment by wenkaifan0720** [comment]
Hi @stepanic. Could you elaborate on what functionality are you trying to achieve here? If it is possible, could you share with me the project that has this bug?

**Comment by stepanic** [comment]
As you can see here
![image](https://user-images.githubusercontent.com/315282/204788500-5d17b76f-8926-4579-8c67-79830f718473.png)
the Boolean property `isSectionActivityWithTimeline` is visible but when is assign some value to it like here
![image](https://user-images.githubusercontent.com/315282/204788740-841c9b82-f21e-476d-af64-5c8a20da74ea.png)
then I don't know that the name of the property is `isSectionActivityWithTimeline`.

But for the type of `Document` after assignment still is visible parameter name `sectionActivity`

**Comment by wenkaifan0720** [comment]
Ah. I got you now. I'll look into this.

**Comment by wenkaifan0720** [comment]
@agreaves I tried to deal with this issue on main. But somehow the `Set from Variable` button is not working for boolean parameters in component properties. 

![iScreen Shoter - 20221202210709249](https://user-images.githubusercontent.com/112435854/205299769-1b2c417f-6170-4b18-8c6d-1ce8e3df565e.jpg)

**Comment by wenkaifan0720** [comment]
@stepanic We have fixed this issue now. It should be alive soon. Thank you for raising this issue!
