### ISSUE TITLE
Run and Test Modes completely screwed

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1420]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Preview running as expected (with one minor glitch maybe... see video)

Run mode broken

Test mode broken

See video

https://www.loom.com/share/7e2995bd20104a8cad949b8533b72982

### Expected Behavior

Simply run the app as expected

### Steps to Reproduce

https://www.loom.com/share/7e2995bd20104a8cad949b8533b72982

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lcmAuIhOxLgA7qqNKe9anjwWQls7RLsS0e59cwg8J5zKB+wAYvf7P1FWTLyoTHx6JGeakmc11vfqvuP1Gu4CYEiuG9VPwpNbEzyUUnKRRr62Crq/fW1TJNNjCG7H07Wo3RMnFM1qS3wW7V61fuivUXXsGJzzOlgRDeaLLdeK2SrDX1iXc2URm05KZDPz

### Context

https://www.loom.com/share/7e2995bd20104a8cad949b8533b72982

### Visual documentation

https://www.loom.com/share/7e2995bd20104a8cad949b8533b72982

### Environment

```markdown
- FlutterFlow version: latest, after clicking refresh button too
- Platform: MacOS
- Browser name and version: Chrome latest
- Operating system and version affected: Sonoma
```

**Comment by hariprasadms** [comment]
Hi @chuggmuffin - Thanks for your reporting the issue. I looked at your project and its widgets. There are few missing configurations I found.

1. In HomePage2 component you have not given width and height for the component to display. See below.

<img width="1518" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/abd1552e-8a87-4c55-b3c8-8613c7281c02">

2. The HomePage2 component visibility condition is on but no condition added. You should disabled this if there is no condition is configured. 

<img width="992" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b504dde2-8cde-4940-9d10-2231fecdb236">

3. In SecondPage2, you got on page load action set with navigation action, thats the reason you can page navigation is going back when you click on Homepage2 text.

Regarding theme color change, I didn't find any wrong configuration around it. It should work fine. The blank project you provided in the issue. It can build and running fine. See below. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/13d0790a-e88e-4542-a6ac-d6b19abeceaf

**Comment by chuggmuffin** [comment]
ohhhhhhhhhhh kkkkkkkkkkkkkkkk

Thanks you!

I think I see what happened.

I was trying to use...[image: Screenshot 2023-09-07 at 4.12.14 PM.png]

to make the height dynamic, but instead of setting the CHILD COLUMN in the
component to contract to fit space, I used expand.

The system didn't read that there was an overflow error like it usually
does for some reason and so I didn't that to be an issue, especially since
a version of the component popped up both in run time and in the preview.

Any idea why there were 3 completely different "views" depending on what
run mode, vs a universal one?

Brian

**Comment by chuggmuffin** [comment]
Also, I still get the "dark mode" in the run version vs the test version
and I haven't put on dark mode on my computer

B

**Comment by hariprasadms** [comment]
Dark mode change could be issue specific to your project. I can confirm that in general it is working fine. Create a new project and see consistency of the issue. If issue presists consistently , we can look into it. I hope that helps you. Thanks
