### ISSUE TITLE
Action block + Revenue Cat = bug

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#1422]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have the action block with revenue cat
<img width="1205" alt="Снимок экрана 2023-09-08 в 08 21 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76915134/654ff03b-81eb-4b85-8e69-5f96fb918e50">

this block check the subscriptions (in revenue and cloud payments) and returns true or false
but this action block will crashed my project
<img width="1728" alt="Снимок экрана 2023-09-06 в 18 15 50" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76915134/5fa1f7af-a38e-451f-8a4a-428e6304a486">

I've do some research and found - revenue cat action can be null and if it null - just call return but action block need to return true or false 
<img width="1287" alt="Снимок экрана 2023-09-06 в 07 29 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76915134/be232867-2ecc-4475-9af6-64836728a49d">

### Expected Behavior

Action block will be work with Revenue Cat

### Steps to Reproduce

1. Create project
2. Create action block which will return true or false
3. add revenue cat entitlements check
4. return true or false 
5. try to run project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oksjfz85gocdY1rr+bPowmSQsJkQia7sZ0spBazwbfe+uB4kqevfOTERoZ9OmYEFUPWKKkWoW0e/GktjpUMFeFE2BQbpIzrh9FhfgWmanRK66FJWvPnxtNJ9MG2nH4Ji7hhB+FOptZXw/2DqAPPDIdAPbN7rIClYkDq/LZO4=

### Context

I can't complete my app

### Visual documentation

on a top

### Environment

```markdown
- FlutterFlow version: 1.1.100
- Platform: iOS
- Browser name and version: app
- Operating system and version affected: Ventura
```

**Comment by hariprasadms** [comment]
Hi @oper2k - Thanks for submitting the issue. Looking at the nature of issue and details. I would advise you to first contacting the Flutter Flow technical support team, who can look into the project and make recommendations for a solution. If technical support team confirms this is a bug, you can come back here re initiate the bug. I hope that works for you.

**Comment by aemelyanovff** [comment]
Duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1239
