### ISSUE TITLE
Clicking in endDrawer triggers the youtubePlayer and webView widget placed under the meny option

### ISSUE THREAD

**Issue by LinnMarita** [FlutterFlow/flutterflow-issues#1424]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open the enddrawer and there is a youtubePlayer or webView under where I want to click, the player/view is affected and not the content in the endDrawer.

### Expected Behavior

Clicking on content in the endDrawer should only register a click in the endDrawer

### Steps to Reproduce

1. In addition to the homePage, create another empty page to navigate to
2. Add an endDrawer to the homePage.
3. Add a column to the endDrawer and add a text-widget inside the column. Add padding of 150 on the top of the column so the text will be placed over the video-window (This is important! The text needs to be on top of the youtubePlayer when the endDrawer is open).
4. Add an action to the text-widget, so that it navigates to the second page.
5. Add a youtubePlayer to the homePage.
6. Set an action to the icon in the appBar to open endDrawer.
7. Run app.
8. Click on the icon to open endDrawer.
9. Click on text to navigate to the next page (this is not working)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l7c92rsMA+KXyKsEwgj4WI0MYXoJE0+thdxEjGZjtB4YqY876PhZCZ8+kd2NlekyMp140+cLVjuGWDO1dJQSbbYRe1c9MbDzLQmGtVaWTF7mWP3NSQOdYfVDF5qu3vgpNNupodCwuwV2PevKubHHqK6bRCkQ8Sq/LZO4=

### Context

I have created a menu inside an endDrawer. The menu-elements that is placed on top of a youtubePlayer or a webView (with an external audioPlayer), clicking on the menu item only affects the youtubePlayer/webView.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/144349486/50ae8f80-c28d-4fe6-9842-e4b8cfa9767d

### Additional Info

I'm still working on building the app and waiting for apple developer account, so I don't have a paid subscription to test if this is only a bug in test/run mode.

### Environment

```markdown
- FlutterFlow version: v3.1 (released sep 7, 2023)
- Platform: web
- Browser name and version: Chrome 116.0.5845.179
- Operating system and version affected: macOS Ventura 13.5.2
```

**Comment by LinnMarita** [comment]
Any updates?

**Comment by vaital3000** [comment]
I have some issue

Components don't intercept gestures on top of the webview in web

I reproduce it in blank app.

1. Create new Page
2. Add WebViewComponent and setup height to end of the page
3. Add component on top of webview(for example I show BottomSheetView component)
4. Add button with action to the new component(for example show Alert Dialog)
5. Run web app.

IT8givHl35Rgrt9G+KXcYPpajSQRQ2Z/aJZM0dV+aAwdIrbyOqd3Ycn7dRNWXeaBa31qJVqiknsKzPzZvfPPUMcBMgeqfNhq3bpcQxaWfEmgSqWaCs68eXJREd9XJlyY4J2r2Ax9FMVqSEI/3DmXOOiQdD7vN5zMPG0wQuWXDIP5n1bjLBDkUiAyyiZecCfn

For fix this issue You need to wrap components in WebViewAware https://pub.dev/packages/webviewx_plus#important-
But flutterflow don't have this wrapper.
And I can't create custom widget wrapper.

**Comment by selcukgoktas** [comment]
> ### Has your issue been reported?
> * [x]  I have searched the existing issues and confirm it has not been reported.
> * [x]  I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.
> 
> ### Current Behavior
> When I open the enddrawer and there is a youtubePlayer or webView under where I want to click, the player/view is affected and not the content in the endDrawer.
> 
> ### Expected Behavior
> Clicking on content in the endDrawer should only register a click in the endDrawer
> 
> ### Steps to Reproduce
> 1. In addition to the homePage, create another empty page to navigate to
> 2. Add an endDrawer to the homePage.
> 3. Add a column to the endDrawer and add a text-widget inside the column. Add padding of 150 on the top of the column so the text will be placed over the video-window (This is important! The text needs to be on top of the youtubePlayer when the endDrawer is open).
> 4. Add an action to the text-widget, so that it navigates to the second page.
> 5. Add a youtubePlayer to the homePage.
> 6. Set an action to the icon in the appBar to open endDrawer.
> 7. Run app.
> 8. Click on the icon to open endDrawer.
> 9. Click on text to navigate to the next page (this is not working)
> 
> ### Reproducible from Blank
> * [x]  The steps to reproduce above start from a blank project.
> 
> ### Bug Report Code (Required)
> ITFTls/l7c92rsMA+KXyKsEwgj4WI0MYXoJE0+thdxEjGZjtB4YqY876PhZCZ8+kd2NlekyMp140+cLVjuGWDO1dJQSbbYRe1c9MbDzLQmGtVaWTF7mWP3NSQOdYfVDF5qu3vgpNNupodCwuwV2PevKubHHqK6bRCkQ8Sq/LZO4=
> 
> ### Context
> I have created a menu inside an endDrawer. The menu-elements that is placed on top of a youtubePlayer or a webView (with an external audioPlayer), clicking on the menu item only affects the youtubePlayer/webView.
> 
> ### Visual documentation
>  BugReportFlutterflow.mov 
> ### Additional Info
> I'm still working on building the app and waiting for apple developer account, so I don't have a paid subscription to test if this is only a bug in test/run mode.
> 
> ### Environment
> ```
> - FlutterFlow version: v3.1 (released sep 7, 2023)
> - Platform: web
> - Browser name and version: Chrome 116.0.5845.179
> - Operating system and version affected: macOS Ventura 13.5.2
> ```

I have the same issue. 

Is there any update ? Or how can we solve this problem ?

**Comment by LinnMarita** [comment]
> 
> I have the same issue.
> 
> Is there any update ? Or how can we solve this problem ?

As mentioned above, you would need this: 
For fix this issue You need to wrap components in WebViewAware https://pub.dev/packages/webviewx_plus#important-
But flutterflow don't have this wrapper.

As an app on a phone, this is not a problem (I have now tested), but I would think this is a problem for a web-app.

**Comment by aemelyanovff** [comment]
@LinnMarita Thanks for reporting the issue. It will be fixed in the next update - all drawers, dialogs and bottom sheets will be made `WebViewAware` if there's `WebView` in the project (YouTube player also counts as a WebView).
