### ISSUE TITLE
Query configurator stores incorrect value

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1428]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When configuring a firestore query, the configuration sometimes doesn't detect the change of value (boolean), so there's no Confirm button appearing.

My query was showing True but returning items that were False. Eventually, the query showed False. When I tried changing it to true, the choice could not be saved.
__

### Expected Behavior

When the boolean is changed, the Confirm button should appear.

### Steps to Reproduce

1. Create a new backend query
2. Filter on a field that has a boolean
3. Confirm the query
4. Edit the query again and change the boolean to the opposite value
5. Sometimes the change is not detected and the confirm button doesn't appear.

### Reproducible from Blank

- [X] #1510

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sd4bGA0dCJzuPLMQdvWlXBBpXcvgTGxmO0Smml0E/tKPudrXFsI3PQqBbJRZzLphFwrwcFuXQZOBEpO3dkB6EelMJ2qZ0MKJryVBIsB0SHga6mWPe+vIUXTAJLL2ImdISq/LZO4=

### Context

I was trying to set up my query.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/8a9108c2-03ab-4021-8245-7ef4433cc868

### Environment

```markdown
- FlutterFlow version: 3.1 Sept 7th
- Platform: Chrome
- Browser name and version: Chrome Version 116.0.5845.140 
- Operating system and version affected: Mac OS 13.5.1 (22G90)
```

**Comment by neian-world** [comment]
Update: I thought I saved it, but the query somehow reverted again to false after some time.

**Comment by joshua-ffio** [comment]
I've found the issue and the fix will be available in the next update. Thank you for bringing this to our attention!
