### ISSUE TITLE
App Check integration no longer visible with latest update

### ISSUE THREAD

**Issue by ebamoh1** [FlutterFlow/flutterflow-issues#1429]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the most recent update, I no longer see the Firebase App Check integration in FF.

<img width="404" alt="Screenshot 2023-09-09 at 1 00 24 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/135924498/b0ff0c1d-c204-4177-97fc-18e9861038e4">

### Expected Behavior

Firebase App Check integration used to be present before the most recent update.

### Steps to Reproduce

1. Go to Settings > Integrations
2. You'll notice there is no longer ab option for Firebase App Check.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk87buJJOsbQD14SJa+5shiIRH18cTIMziNZ+exUbfaL1Bu0Md8z8SxFucN+9aVNcIlaLvF0JpK3pj/DPFMc5ExOaQN1AypYNWwv0e2iQbJiuEaW/P3dtGfFgIWK+38PUqh4nBLdiS14/2zqAeujKTXLDBOu/Zwh9f6PHaOI=

### Context

I use Firebase App Check and this integration is important to updating the test and live keys.

### Visual documentation

<img width="404" alt="Screenshot 2023-09-09 at 1 00 24 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/135924498/eda974cf-b647-4a02-bc5a-f2bf87bfe668">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Version 115.0.1901.188 (Official build) (arm64)
- Operating system and version affected: macOs Ventura Version 13.3
```

**Comment by scharfschiesser** [comment]
It was moved to the Firebase tab

**Comment by ebamoh1** [comment]
Just saw it. Thank you
