### ISSUE TITLE
Date/ time picker not working or popping up in debug.. 

### ISSUE THREAD

**Issue by sumreetpawar** [FlutterFlow/flutterflow-issues#143]
enviroment: pc windows 10 and windows 11
browser.. check on chrome, firefoxn also microsoft edge. 
operating system.. while making mobile app.
Step1. Made new page.
Step2. Added container with icon.
step3. step container "on click" action to date/time picker.
step4. add button
step5. add button "onclick" action to update date/time picker to "startdate" timestamp variable. 
step6. launch debug.
step7. click on container with date/time picker set.
step8. date and time picker is not loading like before ... not popping up or no selection menu showing up.

please help.

**Comment by Pepino-GR** [comment]
Hi sumreetpawar,
I can't reproduce this issue. I need some more information. Please write down all steps one by one to reproduce the issue. Can you please show me the page?

**Comment by sumreetpawar** [comment]
it is loading now ... the datepick/time picker was not loading in debug.. but it seems to be working all of the sudden in all browser.. all good now. 

this is the pic btw, thank you for getting back. 
problem was the date picker / time picker menu was not showing up ... no matter how many times i click the icon... 
it works now ... 
<img width="261" alt="Capture" src="https://user-images.githubusercontent.com/118656027/202901547-28cf1931-44de-4e43-9d8a-b39722c614ac.PNG">
<img width="347" alt="Capture2" src="https://user-images.githubusercontent.com/118656027/202901548-dfddbbc3-6f47-4243-9863-6b1127133b0f.PNG">
