### ISSUE TITLE
Slider Component Referencing Issues

### ISSUE THREAD

**Issue by vowzee-git** [FlutterFlow/flutterflow-issues#1430]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm working on a screen with multiple sliders and multiple actions that refer to multiple components. However, when I added any new components, some of the actions referenced disappeared.

### Expected Behavior

Adding component without breaking the sliders actions reference.

### Steps to Reproduce

Example 1:
1. Add Tabs view
2. Add few sliders with actions referenced to few components in the first tab.
3. Add few sliders with actions referenced to few components in the second tab.
4. Make some changes in either tab by adding new components.
5. Showing some issues in the Project Issues notifications.

Example 2:
1. Duplicate the page with tabs and sliders in each tabs.
2. Showing some issues in the Project Issues notifications.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SjMrq05NgoeVG1qrtbcBKhiYvOVwlbZIRlO1AEUsbF7LrO7QtXOjASEhVXd+/TAl2Ilv8rH8xwNHIhdniUuQHAyedbKF8+pYBUgLyezumRIyoDpO8ZkQkPJhjJEuV0MC72SRRB/piLSUZ6k2mBuiif3PsJ5DENmsBPOSJOpLDn3CaAi+6Xn0Jg1ZSfCvr

### Context

I'm in the middle of working on a complex calculator, but with these issues, I need to spend more time fixing the reference.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: 3.10.4
- Browser name and version: Chrome, 116.0.5845.140
- Operating system and version affected: 13.4.1
```

**Comment by hariprasadms** [comment]
Hi - Thanks for submitting the issue. Update with project bug report code please.

**Comment by vowzee-git** [comment]
I have added in the initial post: IT4SjMrq05NgoeVG1qrtbcBKhiYvOVwlbZIRlO1AEUsbF7LrO7QtXOjASEhVXd+/TAl2Ilv8rH8xwNHIhdniUuQHAyedbKF8+pYBUgLyezumRIyoDpO8ZkQkPJhjJEuV0MC72SRRB/piLSUZ6k2mBuiif3PsJ5DENmsBPOSJOpLDn3CaAi+6Xn0Jg1ZSfCvr

**Comment by sbis04** [comment]
I wasn't able to reproduce the issue on my end (and I couldn't find the page referenced in the Bug Report code).

But generally, if you have any action on a widget and you try to duplicate or copy it, in some cases it might cause issues because of duplicate/incorrect reference of any variable used inside those actions.

I wouldn't consider these a bug since they show up in the Project Issues panel.
