### ISSUE TITLE
Timer component doesn´t work in web or installed PWA

### ISSUE THREAD

**Issue by Wahappen** [FlutterFlow/flutterflow-issues#1432]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FF timer component works perfectly in debug mode inside web interface of FF, but once you download code and publish it outside FF, timer doesnt work inside any web environment. why is this?

If you use the web app in a browser it works sometimes, but the point is, when you install that web app (PWA) in your smartphone and start it clicking icon as an usual app, timer doesn`t work never, it doesn´t count down, the time is stopped always.

If pwa is encapsuled inside a PWA and started clicking it as an usual app, it doesnt work. I dont know if its a problem with workservice or something relationed with installed PWA.

### Expected Behavior

Timer should works inside any web hosting and even as a PWA installed in smartphones

### Steps to Reproduce

1.- Create project
2.- Use Timer component
3.- Download code
4.- Publish it, for example in google cloud hosting
5.- Install app in Android or iOS
6.- Open app
7.- See behavior, it doesnt work

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

Any context

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS and Android
- Browser name and version: any
- Operating system and version affected: any
```

**Comment by hariprasadms** [comment]
Hi @Wahappen - Thanks for submitting the issue. We need bug report code with blank project setup with issue steps and also a quick video to see the issue at your end. Send us published app link as well. Please update the issue with these details. Thanks

**Comment by SameerShahzad99** [comment]
This issue has been closed because of no response from the author!
