### ISSUE TITLE
POST requests with a request body fail when using FF private API cloud function

### ISSUE THREAD

**Issue by scharfschiesser** [FlutterFlow/flutterflow-issues#1433]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When making a POST request with a JSON body payload to an API that is routed through FF's secure cloud function, the server-side logs of my API indicate that the request body is empty. The issue only occurs when using POST requests with a body. GET requests work as expected.

### Expected Behavior

APIs routed through ffPrivateApiCall need to include the JSON body payload.

### Steps to Reproduce

1. Create a new POST API with a JSON body in FlutterFlow's API editor.
2. Select "Make Private" and "Require Authentication" and deploy API (creates the ffPrivateApiCall cloud function).
3. Make a POST request to the API from within the Flutter app (this will route the request through the cloud function).
4. Observe server-side logs of the API to inspect the request.
5. Notice that the entire body is missing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8nc24Z2octK0KXyde9WmioWJUB5bb00st5Hd0gdCOPrBuwIds7SUFBpTfXiaVNcIWK0kXwH+s7LifPxV/o6BxaeR7pMyM9ASTz0e2ilMq6aO8+KX3JCRONnJlyn3MCF2hFAAMlZdGxg3E+uHvO9YAnDFOu/Zwh9f6PHaOI=

### Context

All my APIs aren't working and this issue ahs a huge impact on my project.

### Visual documentation

<img width="766" alt="Screenshot 2023-09-10 at 00 09 17" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40205459/baaac9f2-e87f-49bd-bf62-02d8bafd1956">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 116
- Operating system and version affected: macOS Ventura 13.5.1
```

**Comment by scharfschiesser** [comment]
I found the issue. In the ffPrivateApiCall cloud function, the request body is created dynamically based on the content type:

```javascript
function createBody({ headers, params, body, bodyType }) {
  switch (bodyType) {
    case "JSON":
      headers["Content-Type"] = "application/json";
      return body;
    case "TEXT":
      headers["Content-Type"] = "text/plain";
      return body;
    case "X_WWW_FORM_URL_ENCODED":
      headers["Content-Type"] = "application/x-www-form-urlencoded";
      return qs.stringify(params);
  }
}
```

The createBody function expects 'body' as a named parameter. However, the API calls are passing ffApiRequestBody as a named parameter.

Here's an example API call to check a phone number:

```javascript
async function _checkPhoneCall(context, ffVariables) {
  var phone = ffVariables["phone"];

  var url = `https://XXX.cloudfunctions.net/checkPhone`;
  var headers = {"x-api-key": `XXX`,};
  var params = {};
  var ffApiRequestBody = `
{
  "phone": "${phone}"
}`;

  return makeApiRequest({
    method: "post",
    url,
    headers,
    params,
    body: createBody({ headers, params, ffApiRequestBody, bodyType: "JSON" }),
    returnBody: true,
  });
}
```

'ffApiRequestBody' is being passed as a named parameter to the createBody function, resulting in the body becoming undefined.

There are two solutions to this.

Either:

Pass the parameter correctly to the createBody function (this would require updating all your API calls):

```javascript
body: createBody({ headers, params, body: ffApiRequestBody, bodyType: "JSON" }),
```

OR:

Update the createBody function to use the new variable 'ffApiRequestBody':
```javascript
function createBody({ headers, params, ffApiRequestBody, bodyType }) {
  switch (bodyType) {
    case "JSON":
      headers["Content-Type"] = "application/json";
      return ffApiRequestBody;
    case "TEXT":
      headers["Content-Type"] = "text/plain";
      return ffApiRequestBody;
    case "X_WWW_FORM_URL_ENCODED":
      headers["Content-Type"] = "application/x-www-form-urlencoded";
      return qs.stringify(params);
  }
}
```

Both ways the body can be passed to the function correctly.

This is only a temporary workaround and needs to be fixed in the FF cloud function source asap. Redeploying the ffPrivateApiCall cloud function overwrites the changes and causes the API calls with a body to fail again.

**Comment by agreaves** [comment]
Hi @scharfschiesser, thank you so much for the detailed bug report (and solutions) and thank you for your patience. We're looking into this now!

**Comment by agreaves** [comment]
Just for clarification, did you notice this as a regression (was working before) or was it never working as intended for you?

**Comment by scharfschiesser** [comment]
> Just for clarification, did you notice this as a regression (was working before) or was it never working as intended for you?

It was working without any issues until about 2 days ago, that's when I started noticing the API calls failing.
I checked previous revisions of the cloud function source code and the issue started as soon as the 'body' variable was changed. Not quite sure when that happened though.

**Comment by agreaves** [comment]
Thanks so much for the info and for catching this one, it was certainly quite a bug! This should now be fixed 😊
