### ISSUE TITLE
Interger value cannot be negative in X/Y alignment conditional

### ISSUE THREAD

**Issue by winthermich** [FlutterFlow/flutterflow-issues#1434]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to add a conditional which will change the X/Y alignment of an element (e.g. container or column), you cannot specify that value should be -1.

Positive values work fine - negative integer values do not.

### Expected Behavior

It should be possible to enter a negative value in a conditional.

### Steps to Reproduce

1. Add a container to the canvas.
2. Add a conditional to the X alignment value based on responsive size.
3. Attempt to enter -1 for "Small screen"
4. Result = it is not possible to enter a negative sign.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkMmAsJRNobVE+anQLcFFvCowGUALa+dI0tZ+TQ0jF5D4OrQqPM+lbhRtZ8yzaHNMAGeKpEA1wt74kfLpKPEECASZR4BAzagJVBPPbFKRb8mrPLi8XHJ7I9pYN0if1MHUuhV/BOpoSl4Q60OyH/OsYz6Cf9qOYwx5e6fDbOY=

### Context

I need the alignment of certain elements to change based on the screen size (to improve UI).

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/f05283f2-4f59-4bdd-a65f-affbf72bdd67)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web + Desktop
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by winthermich** [comment]
Hi again.
This is a general issue with all "Integer" and "Double" values throughout Flutterflow.
The issue also exist when attempt to set a state value (local, global).
Could you provide a general fix?

**Comment by hariprasadms** [comment]
Hi @winthermich - I appreciate you bringing this up. You are currently seeing behaviour that is in line with the present design. Using the feature request form, you can submit this request as a feature or enhancement.

**Comment by wenkaifan0720** [comment]
Hi @winthermich. Thank you for raising this issue. This should be fixed in the next update!

**Comment by winthermich** [comment]
Hi @wenkaifan0720 
Awesome - seems to work :)
Thanks!

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/02838ca2-ab5f-4ed1-9890-81a08cb3757d)
