### ISSUE TITLE
E-mail form validation is wrong

### ISSUE THREAD

**Issue by mickealmprivat** [FlutterFlow/flutterflow-issues#1437]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I noticed e-mail validation pattern when using the form validation seems to be wrong. It looks for xxxx@xxxx but no .xxx at the end

### Expected Behavior

test@gmail should validate as wrong
test@gmail.com should validate as correct

### Steps to Reproduce

1. Add form validation widget
2. Add textfield
3. Set textfield to email validation

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i/HluIlPm+Fc14SJb/lr/WUXQl87a+ca1tV+Vkw8KOvZPO0Me/WkPlhvYMOqS1Z2fUSmmmcz+s7pjuDxV8dfHwmYf7Z9ysxUTQ7vVjiQUZOBBs6WS2tDM+VTI0i00LWjhwpBBPJYS3wQ32Wme/OvVgrdQpT7ImdISq/LZO4=

### Context

This leaves the user exposed to entering their e-mail incorrectly

### Visual documentation

<img width="406" alt="Screenshot 2023-09-11 at 10 11 15" src="https://github.com/FlutterFlow/flutterflow-issues/assets/26624187/337fa478-a89a-42d2-a10f-5947a8afc844">

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Mobile
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: macOS Ventura 13.1
```

**Comment by hariprasadms** [comment]
Hi @mickealmprivat - Thanks for submitting the issue. I can reproduce the issue. 

**Dev note** - I have tested this with and without custom regular expressions but still not working. When regular expression used, it does not allow to enter anything to text field.  Below is the code with regular expression pattern.

` RegExp(r'^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$'),`

<img width="686" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/5307ceac-f662-4e51-8f39-5054f052f80a">

**Comment by aemelyanovff** [comment]
@mickealmprivat Thanks for reporting the issue. In the next update we are switching to [this expression](https://stackoverflow.com/a/201378) for validating emails.
