### ISSUE TITLE
Cannot create Firebase collection field name with only 1 character

### ISSUE THREAD

**Issue by theopenplatform** [FlutterFlow/flutterflow-issues#1438]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm linking an existing Firebase project with Firestorm database to Flutterflow. Firestore allows creating field names with only 1 character, but when trying to create this field name in Flutterflow, an error appears stating that Field Name must have minimum 2 characters. 

Changing the Firestore schema in existing project will take large amount of work to migrate all data and risk breaking end user functionality. Flutterflow should support just 1 character field name since Firestore supports it.

### Expected Behavior

I expect to be able to create Firestore collection field names with 1 character, just like I can do in Firestore directly.

### Steps to Reproduce

1. Create new Flutterflow project and connect to Firebase
2. Click on Firestore icon in Flutterflow and add new Collection
3. In the field name enter 1 character
4. Select a data type
5. Click on Green Check Icon to save

Error appears stating:
"Name must be at least 2 characters long."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40h8/lz4pIschE1rrud/lV+Ts5JmF+RJ0nle1RaCwqGJToPLUMPsneVFRuZrynTQlmfWD8vHEzxvfqjYfPN8coFxasRoA+ys9yTw7iTnKXbKa1Orm7fW1QHe9QCFC+35mKkxYlVehuWkUu3V62I+m9cHLUH4f6PFgFLc+bKdeK2SrDX1iXc2URm05KZDPz

### Context

Cannot proceed to use paid Flutterflow version since I cannot replicate my existing Firestore project schema.

### Visual documentation

<img width="832" alt="Screenshot 2023-09-11 at 19 03 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/144388492/3d15f813-36ad-430a-9486-50fdc63c2cc9">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Safari 
- Operating system and version affected: MacOS
```

**Comment by wenkaifan0720** [comment]
Hi @theopenplatform. This will be allowed in our next update. Thank you.

**Comment by sandpat** [comment]
This is really bad guys. I am new to Flutterflow, everything was awesome till the point I decided that I will make use of real-time updates of firestore and replace my backend with firestore by letting external systems write to my firestore. Then I realized that I need to define schemas in fireflow. **No-SQL db needing schema**, what an irony! And then ok I said, then this. Now I modify my scripts to handle deep nested attribute names because flutterflow won't allow single characters variable names though firestore does. Come on guys, as good as your API calls handling is, firestore handling is a disappointment.

**Comment by eiriknh** [comment]
@wenkaifan0720 
Hi. Seems like this issue was fixed for Firestore schema, but not for the Data Schema? 

Adding a field with one character in Data Schema still gives this error message:
"Name must be at least 2 characters long."

Could this fix be done for Data Schema also?
