### ISSUE TITLE
Google Play Deployment Error

### ISSUE THREAD

**Issue by alexstockman** [FlutterFlow/flutterflow-issues#1439]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Return error when publishing to google play

### Expected Behavior

to properly publish to google play

### Steps to Reproduce

1. Deploy to Play Store 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No Bug Report Code in settings

### Context

I have live users that need a critical update on android

### Visual documentation

![Screenshot 2023-09-11 at 10 12 01 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/136628596/b7f4c157-86c0-453b-954b-abe98f77d507)

Codemagic Deploy Output
Failed Step: Publishing

== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact app-release.apk
Publishing artifact app-release.apk
Publishing artifact app-release.aab
Publishing artifact release_mapping_mapping.txt
Publishing app-release.aab to Google Play
Published app-release.aab to track internal
Google Play failed to upload artefacts. You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.: {
    "error": {
        "code": 403,
        "message": "You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.",
        "status": "PERMISSION_DENIED"
    }
}

Build failed :|

Publishing failed :|
Google Play failed to upload artefacts. You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.: {
    "error": {
        "code": 403,
        "message": "You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.",
        "status": "PERMISSION_DENIED"
    }
}

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Android
- Browser name and version: Google Chrome
- Operating system and version affected: Mac OS
```

**Comment by alexstockman** [comment]
It seems the cause is the version code on my most recent deployment (3) is lower than the last (145), witch is causing the error.  I was testing to get hub integration, and it seems like it may have reset the version number.  

![Screenshot 2023-09-14 at 3 43 16 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/136628596/82343b02-c2fe-4c27-8af6-06278b801996)

**Comment by wenkaifan0720** [comment]
Hi @alexstockman. Could you change the Release name field to have a larger version number than your previous release's (145)?

**Comment by SameerShahzad99** [comment]
@alexstockman This problem seems to be project specific, please reach out to the support team for this issue on live chat or email: support@flutterflow.io
