### ISSUE TITLE
Pageview now not working in list, when list backend set to collection and list of doucments. 

### ISSUE THREAD

**Issue by sumreetpawar** [FlutterFlow/flutterflow-issues#144]
before the recent update my page view held images list through children variable and showed a list of documents in collection in pageview ... (i had images set pageview..) now it tell me to put it in a composition.. which i did and set list of pictures in composition.. but in debug it shows grey where pageview is... and shows no picture... please help... what should i do to make pageview view pictures in a list viewing listings... 
it worked before this recent update.. 

thanks.

**Comment by sumreetpawar** [comment]
the pageview in component set to showe imagelist:
hey this is working now.. the problem was one of the documents didnt have any images in the imagelist... the list was empty so all of the widget was showing grey.. (i only have 2 documents in my collection..one had images, one did not.) .. 

now the problem is the component only shows one type of document... it shows the total number of documents in the list accoeding to how many there are (so 2 documents in collection = 2 documents in the list) but only shows the most latest document.. on both listings... its not 2 different documents.. the list is only showing 1 type of document on all of them ... and again its always the most lastest uploaded one.. for some reason it isnt working as a list...

**Comment by katherineqian** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by hariprasadms** [comment]
Hi, Considering no enough details and no follow on this issues, we are closing the issue. We can re-open the issue once added enough details as pert template. Thanks
