### ISSUE TITLE
When the user scrolls on the list (ListView), the Google map below moves.

### ISSUE THREAD

**Issue by breotonum** [FlutterFlow/flutterflow-issues#1442]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The user should be able to move the map (Google Map and zoom in) but when the user scrolls on the list (ListView), the Google map below moves.

### Expected Behavior

The user should be able to move the map (Google Map and zoom in). When the user scrolls on the list (ListView), the Google map below should not move.

### Steps to Reproduce

1 Open : https://list-view-ignore-pointer-zjrz1m.flutterflow.app/
2 Scroll on the list with a mobile phone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fjMrqx89grtdA7qXbbcJVqCUXQkAjRY0/lO5+FEgjF5PqO7M2dsj8QFZJbbSHdGNmeVu0kmcewMmOvd79E+QHAzWafNlT1rtuZTvdXj+WV8WDOpOOTn9AJJtYJEuV1piNoRVDKrFfdFpi2zqYG96ubAvXHabSDVgvGuSXKdnNjWzjAhm6Xn0Jg1ZSfCvr

### Context

I reported this bug at the request of Henry from FlutterFlow support after describing the problem to him and he tested it. I hope that this bug can be resolved quickly. It is for a web application that is already live, and this problem makes the functionality quite unusable in its current state. Thank you in advance for your help.

### Visual documentation

<img width="950" alt="Capture d’écran 2023-09-11 233002" src="https://github.com/FlutterFlow/flutterflow-issues/assets/108001238/fd9586a3-fe5b-4ae5-9c4f-d46ca15b5e97">

https://github.com/FlutterFlow/flutterflow-issues/assets/108001238/76ebd144-39d5-4f30-b339-406b44869e1d

### Environment

```markdown
- FlutterFlow version: v3.1 Flutter 3.10.4 
- Platform:Web
- Browser name and version:Chrome Version 116.0.5845.180 (Build officiel) (64 bits)
- Operating system and version affected: Windows 11 Professionnel and Iphone 11 iOs 16.6.1 (with Chrome)
```

**Comment by SameerShahzad99** [comment]
@breotonum Thank you for submitting this bug, i was able to reproduce this issue on the web app!

**Comment by agreaves** [comment]
Hi @breotonum, thank you for this bug report! I was able to reproduce and fix this issue, so on web scroll events should no longer interact with the Google Map!

**Comment by breotonum** [comment]
Thank you, when will the bug fix be deployed?
