### ISSUE TITLE
Test Mode fails to load if Supabase enabled

### ISSUE THREAD

**Issue by ScissorHill** [FlutterFlow/flutterflow-issues#1443]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon enabling Supabase and connecting to a project, running Test Mode results in the loading animation running forever. Run Mode and Web Publishing work fine. 

### Expected Behavior

With Supabase enabled, one expects the Test Mode to be functional, go beyond the loading animation and actually display the app as seen in the Run and Web Publishing modes.

### Steps to Reproduce

1. Create new project.
2. Click on 'Test'. Confirm that the test mode is functional, even without any widgets added. The default design, a blank app with 'Page Title' on the bar is visible.
3. Settings->Integrations->Supabase->Enable. Copy paste Supabase API URL and Anon Key. Click on 'Get Schema'
4. Go to the test window, and click on 'Instant Reload'. Loading animation (blue and indigo bar at the top) runs forever. The blank app with 'Page Title' is never seen.
5. Settings->Integrations->Supabase->Disable.
6. Go to the test window, and click on 'Instant Reload'. The default design, a blank app with 'Page Title' on the bar is visible.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlPHluIlgrt9c187pbcFV9TsvIjsmbYIelutudEs3G4juG7YAW/SkQE9WZ7yhdH03emD8vHMd+anRhszIN/UnFy+ZfIRc+cxyEgrgZFmQVrbSCs2CT3EnAtpKC3Kb5sGnsCRCBNZ2L04O3DqQA9ivHwDvQ4SxDHo4RvL9Mqf/jXPuQ0SLb3kNh1JWeC/v

### Context

I need to develop web apps, and if I'm using Supabase, that means that I need to publish every little change to see the effect. Which takes a few minutes, so any meaningful development is next to impossible.

I'm actually quite surprised that this bug hasn't been reported before - made me wonder how many people are using FF with Supabase for serious app development. I didn't come across any mention in the Community either.

Which is why I tested this with different browsers, and created new Supabase and FlutterFlow projects, just to test this out. This bug is very reproducible.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/26180991/290895ed-e666-45c9-b9f4-fc5209095238)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/26180991/61940072-0894-4c6e-af48-d5db5ab55051)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: 
1. Google Chrome Version 116.0.5845.179 (Official Build) (64-bit)
2. Brave Version 1.50.119 Chromium: 112.0.5615.121 (Official Build) unknown (64-bit)
- Operating system and version affected: Ubuntu 22.04.3
```

**Comment by hariprasadms** [comment]
Hi @ScissorHill - Thanks for notifying the issue. I have tested above steps and can see test mode works fine even when Supabase integration is enabled. Not able to produce. At this stage I presume it could be project specific issue. I would suggest try the same steps in new projects and see consistency of the issue. Let us know how it goes.

**Comment by ScissorHill** [comment]
Thanks for the quick response. Like I mentioned before - I'm facing this issue across multiple FF projects, across browsers, across Supabase projects, even.

Could you please suggest any steps that we could take to reproduce this issue? I can share some of my projects as public, if that's necessary. Any other suggestions are welcome.

**Comment by ScissorHill** [comment]
After seeing your response, I wondered if it has something to do with my FlutterFlow account.  So did the following tests:

1. From a new account  on Chrome, I recreated the test project and test mode worked, even with Supabase enabled. 
2. From the new account in Incognito mode (Chrome), test mode fails to go beyond the loading animation.
3. From the original account in Incognito mode (Chrome), test mode fails to go beyond the loading animation.
4. From the original account  on Chrome, the test project and test mode worked, even with Supabase enabled. 
5. From either account in Brave, test mode fails to go beyond the loading animation, whether in Incognito or not.

Bottomline: Test Mode works only on Chrome, _and only when NOT in incognito_!

I still consider this a bug, though, because unless I've missed it, it's not mentioned in the documentation. Quite the opposite: the documentation actually recommends incognito mode for troubleshooting [here](https://docs.flutterflow.io/troubleshooting/basic-troubleshooting-guide#frontend-ui-builder-issues).

**Comment by hariprasadms** [comment]
Hi @ScissorHill - In order to access any project's test mode, the user must be logged into FF editor of that specific incognito session. If not, you cannot access projects test mode by simply accessing the link from regular browser mode.

Below showing test mode worked in incognito mode. 
<img width="1509" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/4155546b-3038-4935-a462-3fdafb4ee951">

**Comment by agreaves** [comment]
Hi @ScissorHill, thank you for the bug report! It does seem that using Supabase when in incognito mode causes issues. As @LigiaMurillo pointed out (muchas gracias!), this may be a configuration you need to change within your Supabase project. Regardless, we'll make sure to add that to the Known Issues so users are aware that it may cause issues. Thanks!
