### ISSUE TITLE
Dynamic Children For Listview ,Column Gridview.....

### ISSUE THREAD

**Issue by Guy-W2** [FlutterFlow/flutterflow-issues#1447]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey :)
🙏 Please before you decide to respond to me
🙏Please discuss if the rest of the team
I think I really, really need in Team Design Library
Add the list option
such as:
**Dynamic Children For Listview, Column Gridview..... and all the rest**
**Even from Dynamic Json**
Currently there is no option at all in Team Design Library
Use lists or Dynamic Children
And for those who understand the power of Flutter Flow
!! and the power of Team Design Library
It's really, really disappointing
Right now for me personally it has stopped all my work on future projects
that are linked to one project in the Team Design Library
!!!!! And I can't continue to work without using lists or Dynamic Children
--
It just takes away the whole idea and power of using the Team Design Library
-------------------
Flutter Flow announces many new updates
(which is blessed) and we are waiting and loving all the new updates and features
but still
**Lists or Dynamic Children to Team Design Library**
**It is mandatory and required :)**
**Even from Dynamic Json or something**
---------
🙏🙏 Please take care of this as soon as possible
For me it is considered a bug :)
I would be happy and hope that you and the team will tag this request as a bug
Urgent to treat

Thank you very much for an excellent service
❤️ Flutter Flow

### Expected Behavior

Be Lists or Dynamic Children in Team Design Library
Minimum From Dynamic Json

### Steps to Reproduce

Create Dynamic Children in Team Design Library Even From Dynamic Json

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

that duplicates the Team Design as another Team Design COPY

### Context

Very very frustrating
Stopped all my work
And I'm sure many more Flutter Flow users

### Visual documentation

aaaa

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @Guy-W2 - We appreciate you sharing this information. Looking at the given information, I can see that this issue looks like an enhancement for the current feature in the teams design library. I advise submitting this feature request through the support section's feature request form. 

The form is as below,

<img width="1095" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/96e9fe1e-1e64-4bb1-b3a7-f923513646d1">

**Comment by Guy-W2** [comment]
Yes please pass this on to the team
to consider starting work on it
This is what I really need in Team Design Library

**Comment by Guy-W2** [comment]
Listen, I just want to help
I work very deeply with Flutter Flow (naturally NO CODE)
And I run into some "problems" that are a must
! This can save you and your users a lot of code
and unnecessary combinations that need to be performed

So I write it down for you here :)
And I really hope you will pass it on to the team and we will discuss it
It's just smart suggestions that Flutter Flow will be much more powerful
These are things that I think
Mandatory in Flutter Flow's basic functionality
To make it easier for your users

1. Dynamic Children For Listview, Column Gridview.....
in Team Design Library
(That's what I was actually referring to up here)
---

2. JSON TYPE BACK
I and probably many, many other users work with JSON
And when I return a result from JSON
There is no way to define as what type this variable is
(for example: $.price \ $.boolShowPrice)
And usually also for conditional visibility
What I did was create a lot of Custom Functions
Text To Boolean
Text To INT
Text To Double
And more... all kinds of things like that
!!!!! It is extremely unnecessary and exhausting to work like this
My project and my Team Design Library
Really just bursting with such unnecessary functions
-- If possible please 🙏 Finally add a variable type returned from JSON
---

3. TextField - DYNAMIC REGEX & MASK
For example I have several projects under one Team design library
And there are projects that work with Decimal and some only INT
The problem is that it can create confusion and discomfort on the user experience side of any project
Just an example
When filling out forms such as quantity....
There are projects related to one Team Design Library
some of which should work in the quantity field only with INT
To avoid unnecessary confusion and inconvenience (on the end users' side)
And some projects should only work with Decimal
And there are many more cases for such a need
---------------------
It is very important to have an option to choose
Keyboard type, custom REGEX, custom MASK
in a dynamic way that suits every project

**Comment by wenkaifan0720** [comment]
Hi @Guy-W2. Team design libraries is really more for design system and components. Since you don't have access to the backend (API, firebase, app state etc), why do you need dynamic children for listview and other widgets? Dynamic children is really easy to setup, I don't understand the reason for having it in a design library and why it is blocking you from working with FF.

**Comment by Guy-W2** [comment]
what? Are you serious
It is so so consumed there
There are millions of reasons and scenarios that need it there
I'll just give you 2 examples
1. For example I created a global order form for several projects
(Of course some projects from 1 Team design library - dynamic order form)
And I want to make a selection of attributes for selection
Dynamic from JSON which is from API CALL (different according to each project)

2. For example I prepared SIDE POPUP components of global product information
And I want to display there a LIST of other products of the same model
or a list of related products
(for quick access)
or a list of future stock
more and more....

And there is so much more needed
I will not present it here
In my personal opinion, it's not just for simple components at all
Once you have this option
Dynamic Children For Listview, Column Gridview.....
Even from JSON
**So "the sky is the limit"**
For the power and what can be done with Team design library
It is a basic thing and need to display lists in Flutter Flow
And it is very important to also have the option in the Team design library

**Comment by Guy-W2** [comment]
> Hi @Guy-W2. Team design libraries is really more for design system and components. Since you don't have access to the backend (API, firebase, app state etc), why do you need dynamic children for listview and other widgets? Dynamic children is really easy to setup, I don't understand the reason for having it in a design library and why it is blocking you from working with FF.

/
/
/

**Comment by wenkaifan0720** [comment]
Hi @Guy-W2, I get that. My question was, since you are not able use any backend stuff in a team design library, you can't configure the dynamic listview/column/etc in the design library. Are you suggesting we open the backend tabs as well in a design library? 

And just to make sure, what you are suggesting is more for usability (saving you time), instead of a complete blocker that stops you from developing in FF, right?

**Comment by Guy-W2** [comment]
Hey :) @wenkaifan0720 
Of course it opens up a lot of possibilities
The minimum that Listview, Column Gridview.....
Will work with JSON dynamically pulled from the associated projects
----------
And beyond that what about Team Api Library

**Comment by wenkaifan0720** [comment]
HI @Guy-W2 . This is definitely something on our roadmap. Being able to reuse a component as well as all the relevant backend stuff it is using. Since this is more like a feature request, I will close this issue for now. Thank you!

**Comment by Guy-W2** [comment]
Hi @wenkaifan0720 
sorry have to ask :)
When do you expect time this to happen in your roadmap?
Even an estimated time would help
I'm right in the middle of a project that really depends on this option
of dynamic lists in Team design library

**Comment by Guy-W2** [comment]
> Hi @wenkaifan0720 sorry have to ask :) When do you expect time this to happen in your roadmap? Even an estimated time would help I'm right in the middle of a project that really depends on this option of dynamic lists in Team design library

?

**Comment by wenkaifan0720** [comment]
I am sorry but we can't really give estimation of feature updates. New features, will be scoped by the team and put on our roadmap, but there is no estimated time of implementation.
