### ISSUE TITLE
Google Nav Bar Icons move

### ISSUE THREAD

**Issue by jacobsimons7** [FlutterFlow/flutterflow-issues#1448]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using Google Nav Bar in my project. When I tap one of the icons on the nav bar, the middle icon moves every time and sometimes the icon on the right moves. 

### Expected Behavior

I expect no icons to move. I expect them to stay in the same position like what happens on a normal Navbar.

### Steps to Reproduce

Create New Project
Duplicate the first page twice, so there are now three pages
Add nav bar to each page
In Nav Bar settings change Nav Bar to Google Nav Bar
Remove the labels from the Nav Bar, so that there are only icons showing and no words on it
Then go into test mode and play around with tapping different nav bar icons and watch them move

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89gobhY0JSJcPpahSQRHFA5bYIom8pBZywgfZzzBLN/fPfQP0xtOcPkdAhAPU2mp14d0Nb6vYXDN8ECNgebGak+walcVRXKRj+VWpeTF7mSZkR8MJlRCH6Z5LSVvx1QANZqSWQZ7GCUHeuyd3LYNq6wPFQ8Sq/LZO4=

### Context

It affects the premium brand look that we are trying to show with our app. It makes the app seem budget.

### Visual documentation

<img width="352" alt="Screenshot 2023-09-13 at 08 54 11" src="https://github.com/FlutterFlow/flutterflow-issues/assets/119720981/97b74e69-1d33-4f8d-a8ac-266227dbbe09">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: IOS and on the test emulator on Mac 
- Browser name and version: Google Chrome
- Operating system and version affected: It has happened on all types of Iphones
```

**Comment by hariprasadms** [comment]
Hi @jacobsimons7 - Thanks for submitting the issue. The behaviour what you see, its the expected behaviour of google nav bar.
