### ISSUE TITLE
Dynamic Linking dont open page in App Store 

### ISSUE THREAD

**Issue by approde** [FlutterFlow/flutterflow-issues#145]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Open App in App Store

## Current behavior (required)

Dont work

## To Reproduce (required)

1. Generate Link
2. Share link
3. Open on Apple device with Safari
4.

## Context (required)

Have tried to open the link on an iPhone. However, does not load the app in the App Store.

Works fine on Android 

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): Mobile
* Browser name and version:  Safari
* Operating system and version (desktop or mobile):
iOS

**Comment by timfong888** [comment]
I am having some challenges using the instructions for deep link construction based on the docs. When I send them as described (I manually construct based on the page route) I get an incorrect dynamic link format. 

I started to review for ease deep link docs and they require a lot of parameters. 

Also the FF docs aren't super explicit regarding what scheme to use. It implies that for a deep link to use a custom scheme, but dynamic links revert to https.

**Comment by aemelyanovff** [comment]
@approde "Expected behavior", "Current behavior" and "To Reproduce" sections need a lot more detail, preferably with screenshots. I can't quite understand the issue by the existing description.

**Comment by aemelyanovff** [comment]
Closing as inactive. @approde, if you still experience the issue, please add more details to "Expected behavior", "Current behavior" and "To Reproduce" sections and reopen the issue.
