### ISSUE TITLE
SerializeParam & ParamType not defined during compilation but fine in editor

### ISSUE THREAD

**Issue by AlexandreHurbe** [FlutterFlow/flutterflow-issues#1452]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On code compilation, I get the following messages:
The function 'serializeParam' isn't defined. Try importing the library that defines 'serializeParam', correcting the name to the name of an existing function, or defining a function named 'serializeParam'.

Undefined name 'ParamType'. Try correcting the name to one that is defined, or defining the name.

However, when hovering over the ParamType or serializeParam function in code it's able to recognise 

<img width="195" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/37171772/e847c1e7-355d-416c-882b-a4aee2b85743">

I have tried importing the file "import 'flutter_flow/nav/serialization_util.dart''
but get the following message: The import of '/flutter_flow/nav/serialization_util.dart' is unnecessary because all of the used elements are also provided by the import of '/flutter_flow/flutter_flow_util.dart'.
Try removing the import directive.dart[unnecessary_import](https://dart.dev/diagnostics/unnecessary_import)

### Expected Behavior

Should not get any errors for using those functions/types

### Steps to Reproduce

1. Create new custom action
2. Create a context.PushName function and pass in query parameters using serializeParam and ParamType. No error in code but when compiling errors will show up

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj8nc25NPn7xH1aXqc8JB/GUQHDp6R+cwscpCbw4bIYj2P4lzY876P05tXcPgYXNDPmC2p14DwvTxv9/TOPQ6NT6cRbk+yKt9Fw3vXk+gRcyTF7WJOUZfHtJbGnKm58OZgh1SKspZcVo411yEf9nIY3PqGOP2OkQ8Sq/LZO4=

### Context

I'm unable to create custom routing between pages that require parameters

### Visual documentation

During compilation:
<img width="195" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/37171772/443a0004-a661-46f8-9ef0-085762e627e5">

In editor, it's recognized:
<img width="244" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/37171772/5dd89549-1755-412d-a18d-b025b2fc2d2b">

### Environment

```markdown
- FlutterFlow version: 3.10.4 (released September 7, 2023)
- Platform: Web (Windows)
- Browser name and version: Brave Version 1.57.64 Chromium: 116.0.5845.188 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 22H2
```

**Comment by hariprasadms** [comment]
Hi @AlexandreHurbe - Thanks for submitting the issue. Can you please add more details why you are trying to access.

**Comment by AlexandreHurbe** [comment]
Hi Hari, I've got a custom widget with a button that when pressed needs to navigate to another page while passing in page parameters.

**Comment by hariprasadms** [comment]
I just updated my comment. Please ignore my earlier comment.

**Comment by AlexandreHurbe** [comment]
Thanks Hari. Sorry I forgot to add but it appears that navigation with parameter doesn't work as well from my testing.

**Comment by hariprasadms** [comment]
No worries. Did you try ignoring from compile ? Is it still not working ?

**Comment by AlexandreHurbe** [comment]
Yep I've tried ignoring it from compile and it still wasn't working

**Comment by hariprasadms** [comment]
It should work fine. Here is the working sample custom widget code. Make sure route / page name is correct. Follow as below.

<img width="788" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/2aa54801-bab0-4d6a-84a4-9fc6e989d190">

**Comment by AlexandreHurbe** [comment]
Okay thanks! I must have done something wrong in my code with it.
