### ISSUE TITLE
Typo in copy widget style prompt

### ISSUE THREAD

**Issue by 1stthingapps** [FlutterFlow/flutterflow-issues#1453]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"Copy widget style" and "Paste Widget Style" tooltips have typos ("properties" missing an "r")

### Expected Behavior

Should be spelt "properties"

### Steps to Reproduce

1. Right click component title
2. Hover over "copy widget style" or "paste widget style" to display tooltip
3. See heinous typo

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi+fl4otItbxa15DuccdF9SkWCDs5RJ0vi8F+eCs9f5zpPZsMZ876PhJuTuG7TGNUJE2mp14DzPTVhtjxF/EBIT+afpxH+LgJeDyVRT6mRLWTF7rgOHd6I59hC26ny57UgQhSBNtpV3wF11yLe+uvShHAQZOxC0Q8Sq/LZO4=

### Context

I take each day as it comes and breathe

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111969999/0b8d735f-bf33-4ddf-93d8-ad994ec55091)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111969999/2e55452b-37d3-4f93-8118-003dc003ec12)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: PC 
- Browser name and version: Chrome Version 116.0.5845.188
- Operating system and version affected: Windows 11
```

**Comment by 1stthingapps** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111969999/9dd40348-3010-484f-beec-91becb1ae824)

**Comment by victoriahuang1** [comment]
Hi @1stthingapps , thanks for the report. This should be fixed upon the next deploy
