### ISSUE TITLE
Progress bar animates from 0 every time

### ISSUE THREAD

**Issue by yadaniyil** [FlutterFlow/flutterflow-issues#1458]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Changing the ProgressBar widget progress from the variable runs the progress bar animation from 0. So assuming I have 0.3 and I set new value to 1.0 it will animate from 0.0 to 1.0.a 

### Expected Behavior

So assuming I have 0.3 in ProgressBar and I set a new value to 1.0 it should animate from 0.3 to 1.0.

### Steps to Reproduce

1. Create project
2. Add a progressBar widget. 
3. Create AppState variable "double progress"
4. Create a button that will increment that appState variable on some value, e.g. 0.2
5. Bind the progressBar value to this AppState value
6. Pressing the button will animate the progress bar from 0 all the time, but animation should start from previous value

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CiMjfsJFPm9tK14SJcPpahSQsH1whRYIFkuwba00dHZPLC5YMefelTE5vOcuRd2NEL2aZrz4Kpq3Jk/zyA+UnAwqsQYBTws1UbgL/Qj6XaJS2CruoQHZSJJlJJVPF18CF2xN+XdZeSkZi1zuEPufKVirfQb7JIkYvBPj9KrL4jnOqQ0SLb3kNh1JWeC/v

### Context

I'm trying to build the user onboarding showing the progress updated on every step. Right now the progress animates every time from the beginning.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/16175106/c9552980-4c17-4382-ada9-de24e29d968b

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: All
- Browser name and version: Google Chrome
- Operating system and version affected: macOS
```

**Comment by sbis04** [comment]
Hey @yadaniyil, thanks for reporting the issue! It should be fixed in the next update! 😊

**Comment by AdrKacz** [comment]
@sbis04 do you have updated? Will there be an option to animate from A to B? (ideally being able to set the time of the animation)
