### ISSUE TITLE
Code export fails when there are recursive data structures and Algolia is enabled

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#1459]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Code export fails when there are recursive data structures in the project and Algolia is enabled.

### Expected Behavior

Either code export succeeds or there's a project error.

### Steps to Reproduce

1. Create new data structure, e.g. `MyDataStruct`.
2. Add field with type = `MyDataStruct` to the data structure.
3. Create new Firebase collection.
4. Add field with type = `MyDataStruct` to the collection.
5. Enable Algolia.
6. Check the collection under "Indexed Collections".
7. Try exporting code for the project, or starting Run Mode or Test Mode.
8. Observe the error. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi8rqx5VgoddA15DucPpagjw4GDp8RLgz08JxRis8GZT0B4kcYs+kfklUOcfmdwl2Ok2aij8X/MmLifPLGvEFPQutGqJJws8BSDnieHOuRaqgO663b3d5I+BXFVSz38CvviUkOspqckIg3V2MHN/Lfz/sK4DbPDEFH+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

It breaks code export.

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 9/15/2023
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by victoriahuang1** [comment]
@aemelyanovff thanks for the report. I have fixed an issue on our end, and this should be fixed upon the next deploy
