### ISSUE TITLE
Add Delete option to right click menu + key command when backspace is overridden

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#146]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Selecting a widget in the tree or canvas and hitting Delete/Backspace key should delete the widget.

## Current behavior (required)

Hitting a Delete/Backspace key with a selected widget does not delete the widget.  Instead it deletes a character in the widget's value.   This is actually a preferred behavior.   But there needs to be another way to delete a widget. 

## To Reproduce (required)

1.   Select a text widget
2.  Hit Backspace key
3.  The last character of the text widget's value is deleted and not the widget
4.

## Context (required)

There needs to be an explicit way to delete a widget.  Currently the workaround is to Cut it.  Perhaps Shft + Backspace/Delete or something similar.  This is not urgent or critical.   But will be confusing for new users.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by katherineqian** [comment]
Hi @KirilOkun , 

Appreciate the report. I will close this issue as a feature request, but it is a reasonable usability improvement. I edited the title to reflect the feature being requested so we can easily reference this issue.

**Comment by KirilOkun** [comment]
@katherineqian   This used to work as recently as last week.  This behavior is very new, and although it works for a text widget it's not a desired behavior for all other widgets.   Right now there appears to be no way to delete a placed widget.  I'd think it's an important bug rather than a feature.

**Comment by KirilOkun** [comment]
@katherineqian    Thank you.  Not sure why it wasn't working yesterday but deleting a widget by hitting backspace works today.
