### ISSUE TITLE
Cant change color of Multi-select Dropdown checkbox

### ISSUE THREAD

**Issue by eddiebrasil** [FlutterFlow/flutterflow-issues#1462]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The new festure of Multi-select dropdown doesnt let us change the color of the checkbox. That means in darkmode APPs, the checkbox cant be seen.

### Expected Behavior

Enable a configuration to let us change its color when the app is in light aND DARK MODE.

### Steps to Reproduce

1. Create a Multi-select dropdown with values
2. Run the app in dark mode )make sure Multi-select dropdown background is dark.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn1sJVOxcBE7a6Jbu9ajSQvNjM5a+Yr0cpBZz0aIuPpDJl/PM/6PlpWZOHkYFFEOmK2p14DwfTXhvLxKfY6F06CfaJn+aVqEAKVLUWteJuTF7WWVnx6TMpQCkid5LSnuwp7LshodVo92melfvDKFz/aCb22C2owSq/LZO4=

### Context

Users cannot see the checkbox and functionality turns out to be unsusuable

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/30787978/534c7da0-1d57-4be8-8797-141648070b7e)

### Environment

```markdown
- FlutterFlow version: ALL versions
- Platform: All versions
- Browser name and version: All versions
- Operating system and version affected: All versions
```

**Comment by wenkaifan0720** [comment]
Hi @eddiebrasil. This makes total sense! However, since this is more like a feature request, I will close this issue for now. Thanks!

**Comment by antonyxshaw** [comment]
Also found this to be and issue. Renders it useless without being able to choose colour as no one will see it.

<img width="306" alt="Screenshot 2023-11-14 at 13 51 56" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7004991/70c531ea-721f-4dec-ae95-a2b326c29656">

**Comment by DaveDelphia** [comment]
I'm running into the same issue. When in dark mode the checkbox color disappears into the background. I understand that adding a checkbox color setting might be considered a feature, but at a very minimum couldn't the checkbox render using the same value from the Text Color setting? That's what I initially expected would happen and consider to be a bug.

**Comment by erok415** [comment]
I'm running into the same issue. Is there a work around to set these colors until the "feature" is fixed?

**Comment by erok415** [comment]
How can this be considered a feature request when it's more like a bug. The widget is incomplete.

**Comment by GamxXamg** [comment]
Hey, nothing new here ?

**Comment by ville-social** [comment]
Hey FF team, any updates here? This is a bug.

**Comment by John-DreamLabs** [comment]
Still waiting on this
