### ISSUE TITLE
Implicit animation bug with dynamic container height based on internal content changes

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1464]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/c3d586d3c9944ad197b4deb23967aef4

### Expected Behavior

https://www.loom.com/share/c3d586d3c9944ad197b4deb23967aef4

### Steps to Reproduce

https://www.loom.com/share/c3d586d3c9944ad197b4deb23967aef4

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WjuflvYt1xPVA1pDMKcBvmjw5JkQ8a+dIjsN+EBA3GIz1P7YPXfikSEpWZ9+kTHxcL2CammY1+fuPkfDmA+UqFwmuGKp9wqpiFxbheFmmaKayDLmwVGtAAp5JJVPGyKSJqiNDPtF0Wi0n2mCHe+yiYArAJZDPIW1ANMqjJtn5s3upQ0SLb3kNh1JWeC/v

### Context

see loom vid

### Visual documentation

https://www.loom.com/share/c3d586d3c9944ad197b4deb23967aef4

### Environment

```markdown
- FlutterFlow version: latest
- Platform: mac desktop
- Browser name and version: Chrome latest
- Operating system and version affected: Mac Sonoma
```

**Comment by victoriahuang1** [comment]
Hi @chuggmuffin , thanks for the report. This is a flutter issue, so it will be non-trivial for us to fix. I will put this down as a feature improvement that we should work on supporting for now.

And in the meantime, I have a workaround for you:

You should create your own custom widget, and use the code provided for `AnimatedClipRect` in top answer to this stackoverflow [post](https://stackoverflow.com/questions/59132930/flutter-animatedsize-works-in-one-direction-only/59133346).
And in your case, you can set `horizontalAnimation` to `false`.

**Comment by chuggmuffin** [comment]
Ok thanks for the tip!

I'll try to hack my way through and see what I can do :D

Brian
