### ISSUE TITLE
iOS - swipe from left to navigate back not working on only one page in the app

### ISSUE THREAD

**Issue by LeftoversTodayAppAdmin** [FlutterFlow/flutterflow-issues#1467]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- My app has multiple pages with back navigation enabled and it works fine on Android and iOS on the physical device except on one single page itemListAlgolia. 
- Everything is set to the defaults and there is nothing special about this page except for the fact that it resets a few app state parameters and text fields before it navigates back. 
- Clicking on the back button in the app bar works as expected on all pages. 
- These additional actions on each navigate back should not disable the iOS gesture to swipe from the left to navigate back.

### Expected Behavior

Navigate back works on a physical iOS device regardless of whether there are additional actions like resetting state and fields.

### Steps to Reproduce

- Open my app
- Navigate to any of the categories from the home page
- Swipe from the left on an iOS device to navigate back

Alternatively you can also try to repro the issue by adding custom actions to the navigate back button in the app bar.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8CjPHl089Oxddc15P1bcdF9TssKWE7a4JEi+5+WRQ1GJzpPZ13eMzBflRoSbTiYAhUO2KKjVgVpPTVvoaSIcc3A02tGdlt/6V2VBXjWn25b8SDGbjpQ39CM9JmG3aH0ZiVrRRTPu1hL2QHwVy2P/aSXnXtGYTTDG43Of+hEKHApF7jGRDCFC8z+y8/IVOrBcoYawWIpIuUtpJh0eDnyw==

### Context

The gesture to swipe to navigate back does not work on one of the most used pages of the app while working on every single other instance where it is used.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/139936478/d15cb3cb-4a18-4d87-a4e2-8bdb8320e40d

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS physical device
- Browser name and version: N/A
- Operating system and version affected: iOS 16
```

**Comment by hariprasadms** [comment]
Hi @LeftoversTodayAppAdmin - Thanks for submitting the issue. I looked at the project bug report code you have provided above. This is not a blank project with issue setup details. Looking at the nature of bug, its a challenge for us to investigate the issue without blank project details. Update the issue with required details. 

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by takashiff** [comment]
@LeftoversTodayAppAdmin Thank you for your bug report. I am going to mark this as closed for now, as we lack the necessary information to properly triage and resolve this bug. Please feel free to follow up in this thread or create a new bug report if the issue persists. Thanks!
