### ISSUE TITLE
Dropdown with value keeps reseting

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1468]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

At very random times (at least to my knowledge as of now), all dropdowns' values in my project that have "Option Labels" activated get reset. Furthermore, the bug checker doesn't find them, but the project just doesn't run. Here's the behaviour:
<img width="992" alt="Screenshot 2023-09-17 at 13 03 09" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/a581ce29-d815-43f4-8db8-446c0103ffbd">

And the error:
<img width="725" alt="Screenshot 2023-09-17 at 13 03 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/bf32e2b9-48e8-40b0-97c1-accfac50f9d5">

This has been happening in all my projects since the latest release. I haven't yet found what triggers this to happen, but in the last couple of days it has been happening 8-10 times a day.

Also, some dropdowns just have a bunch of un-removeable labels:
<img width="319" alt="Screenshot 2023-09-17 at 13 06 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/9028db90-1101-4876-8f5e-0410161312c4">

### Expected Behavior

The value for the dropdown remains the same.
Empty labels that don't have a value are not shown.

### Steps to Reproduce

1. Create new page
2. Add dropdown and set "Add Option Labels" to true
3. Set the values to integer and set 2-3 values.
4. Perform some actions and attempt to trigger the "reset"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcn635B1m+UB7ZSJY/owiiUXHFw2RY0Zi+5+d042DZPMDJYMec7TVFRoOLC0TWNqeVq0knoy+s3emvL9FPoCKSqqc65+zc5qYDnyUjmRRaaPBs68OW5/DcZMCBzF0Z7YvQl4ObNhci0h216let+AdB/AHYTsPFcdBsiHIZKK2SrDX1iXc2URm05KZDPz

### Context

Constant errors slowing down build time.

### Visual documentation

Above.

### Environment

```markdown
- FlutterFlow version: v3.1 (released Sep 15, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 116.0.5845.187
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @tinrunje - Thanks for submitting the issue. The above project bug report code is not a blank project with issue step details. Create a blank project and setup issue steps to show the issue what you are facing. Update the issue with the required details. 

Considering the dropdown functionality around defining its labels and values, I can confirm that it is working as expected and no issues around it. 

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by wenkaifan0720** [comment]
Hi @tinrunje. I made a test project (https://app.flutterflow.io/project/flutterflow-issue-1468-cabvec) but haven't been able to reproduce the issue. Would you be able to reproduce the issue within this project?

**Comment by tinrunje** [comment]
Hi,
Thanks for the responses. In the meantime I have uninstalled FF and I have been trying to replicate it again myself, but haven't been successful. I have tried both web and app versions. 
Sorry for posting something that might not have been an issue, just wanted to help fix it in case it has become a bug for everyone.
