### ISSUE TITLE
Issue with private API calls functions

### ISSUE THREAD

**Issue by tadamtech** [FlutterFlow/flutterflow-issues#1469]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1) I set up an API call in my FF project (Get Contacts in Hubspot Group). The call works and I get a response from Hubspot
2) I make the Hubspot API call group private.
3) Functions are properly deployed on google cloud function
4) Then I tried to make a call through my web app and get an error : {status: error, message: Authentication credentials not found. This API supports OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview, correlationId: fddc0bb9-61ed-4016-9e12-4fccd6ecaa6b, category: INVALID_AUTHENTICATION}. While, it works well when building my API call in FlutterFlow

I found that the function deployed has header : 
`headers: {"Content-Type": `application/json`,"Authorization": `Bearer [hubspotToken]`,}`

I replace this by : 
```
headers = {
"Content-Type": "application/json",
"Authorization": `Bearer ${hubspotToken}`,};
```
By using ${hubspotToken} instead of [hubspotToken], it works well.

Here is the complete code :
 
```
const axios = require("axios").default;
const qs = require('qs');

/// Start Hubspot Group Code

const hubspotGroup = {
  baseUrl: "https://api.hubapi.com"
  // **headers: {"Content-Type": `application/json`,"Authorization": `Bearer [hubspotToken]`,}** REMOVE THIS LINE
}

async function _getContactsCall(context, ffVariables) {
  if (!context.auth) {
    return _unauthenticatedResponse;
  }
  var hubspotToken = ffVariables["hubspotToken"];

  var url = `${hubspotGroup.baseUrl}/crm/v3/objects/contacts`;
  **var headers = {
    "Content-Type": "application/json",
    "Authorization": `Bearer ${hubspotToken}`,
  };** // DECLARE AUTHORIZATION HEADER HEAR WITH ${hubspotToken}
  var params = {'properties': `firstname,lastname,address,email,city,zip`,'limit': 100,};
  var ffApiRequestBody = undefined;

  return makeApiRequest({
    method: "get",
    url,
    headers,
    params,
    returnBody: true,
  });
}


/// End Hubspot Group Code



/// Helper functions to route to the appropriate API Call.

async function makeApiCall(context, data) {
  var callName = data["callName"] || "";
  var variables = data["variables"] || {};

  const callMap = {
    "GetContactsCall": _getContactsCall,
  };

  if (!(callName in callMap)) {
    return {
      statusCode: 400,
      error: `API Call "${callName}" not defined as private API.`,
    };
  }

  var apiCall = callMap[callName];
  var response = await apiCall(context, variables);
  return response;
}

async function makeApiRequest({
  method,
  url,
  headers,
  params,
  body,
  returnBody,
}) {
  return axios
    .request({
      method: method,
      url: url,
      headers: headers,
      params: params,
      ...(body && { data: body }),
    })
    .then((response) => {
      return {
        statusCode: response.status,
        headers: response.headers,
        ...(returnBody && { body: response.data }),
      };
    })
    .catch(function (error) {
      return {
        statusCode: error.response.status,
        headers: error.response.headers,
        ...(returnBody && { body: error.response.data }),
        error: error.message,
      };
    });
}

const _unauthenticatedResponse = {
  statusCode: 401,
  headers: {},
  error: "API call requires authentication",
};

function createBody({ headers, params, body, bodyType }) {
  switch (bodyType) {
    case "JSON":
      headers["Content-Type"] = "application/json";
      return body;
    case "TEXT":
      headers["Content-Type"] = "text/plain";
      return body;
    case "X_WWW_FORM_URL_ENCODED":
      headers["Content-Type"] = "application/x-www-form-urlencoded";
      return qs.stringify(params);
  }
}

module.exports = { makeApiCall };

```

### Expected Behavior

1) Define the API Call
2) Deploy the call as private on Google Cloud Function
3) The call just works fine on both API builder console and Google Cloud Function

### API Call group
1. Create an API Call group called Hubspot (https://api.hubapi.com)
2. Set up headers : 
- Content-Type: application/json
- Authorization: Bearer [hubspotToken]
3. Add variable [hubspotToken] as string

### API call
5. Create an API call in group Hubspot called Get contacts
6. endpoint : /crm/v3/objects/contacts
7. Generate a bearer token in Hubspot and test. It should works.

### Make API Call group private
8. Make the API Call group Hubspot private. Wait for deployement

### Display contacts in web application
9. Add local app variable called hubspotToken that take as default value the bearer token I've created in Hubspot
10. Create a new page> add column> Backend Query (API Call) > Choose Get Contacts > Set parameter hubspotToken = hubspotToken (local variable).
11. Published to web

If you did not updated  ffPrivateApiCall, you should get this error : 
**{status: error, message: Authentication credentials not found. This API supports OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview, correlationId: fddc0bb9-61ed-4016-9e12-4fccd6ecaa6b, category: INVALID_AUTHENTICATION}**

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

I am editing ffPrivateApiCall to correct the bug, so I can work with that bug. However, it ask to edit it each time I deploy my private API Calls.

### Visual documentation

No visual doc.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome v. 116.0.5845.187 
- Operating system and version affected: macOS Venture 13.4
```

**Comment by agreaves** [comment]
Hi @tadamtech, thank you for the report. Unfortunately, variables are not supported in Private API Groups at the moment. This is not anywhere in the documentation so I apologize for this, we'll make sure to add it. In the meantime, we will consider this for near term improvements to our API support.
