### ISSUE TITLE
Supabase auth login action terminates the action chain on login failure

### ISSUE THREAD

**Issue by chatch** [FlutterFlow/flutterflow-issues#1471]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using the supabase auth signin action, if signin fails (eg. wrong password) then the action chain is broken. It means that no custom handling is possible. I have a check after signin to see if user is logged in, however this is skipped when there is a failure.

The reason is the `return;` if user == null in the generated code:
```
final user =
    await authManager
        .signInWithEmail(
  context,
  _model
      .emailAddressController
      .text,
  _model
      .passwordController
      .text,
);
if (user ==
    null) {
  return;
}
```

Below this is the rest of my action chain but it never gets a chance. 

### Expected Behavior

Don't return from the function but instead continue and if there is another action in the chain execute it. Additionally provide an action response with the error details as returned by supabase.

What I'd like to do is use those details and display an error more prominently (than the snackbar error that the auth manager shows).

### Steps to Reproduce

1. Create a login page with a username, password and login button
2. Got the login button and load the action editor for it and add the supabase auth login action.
3. Add an action after this, eg. show snack bar.
4. Run the app and login with invalid credentials.
5. the snack bar in 3. will not be displayed as the chain was broken (return null)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gi87l34p2rsde0a6JcMJVtCMUJj8hRY0/m+0acw4dB7bpBI13PPT7dRZvcMiBa21AI1qZkmYypuDUhIftGsI7E0mtfLY/3JVqEwrxRk+leJeYPc+SRHN5Ed9UGUi01MKF3xVWA+FeSGxk3E+mA+SRYC/tNJDGPmsBBc6lCLD5onSaGjLvOREx5y8XJR7eTI5ODEz25eKMrop5yfj/0w==

### Context

Alternative error handling to the simple snack bar the auth manager displays. I'd like to display a prominent in page error to the user and potentially send the failure to a logging service as well.

### Visual documentation

The second action checking if the user is logged in is never reached here. I would like it to get executed then do some handing on the false side ...

![screen](https://github.com/FlutterFlow/flutterflow-issues/assets/1477978/36fb80e9-5030-4cfa-b6fa-017f06b4323b)

### Environment

```markdown
- FlutterFlow version:  v3.1 Sept 18
- Platform: Web
- Browser name and version: Opera
- Operating system and version affected: Ubuntu Linux 22.04
```

**Comment by damonrand** [comment]
Subtle distinction between bug and feature here! ;-)

In our view accessibility issues should be treated as bugs not feature requests, see here for example.
https://github.com/readme/guides/fix-accessibility-bugs

**Comment by johnstonisaac99** [comment]
@chatch Did you ever figure out a way to capture the login errors?

**Comment by chatch** [comment]
@johnstonisaac99 i changed my action chain to look like this:

![image](https://github.com/user-attachments/assets/155ad6f7-04fc-4823-8d06-eba216a1b3f1)

adding the 500ms wait then checking the user logged in global variable allowed me to handle the false case.  in my case  i'm just setting a page state variable that indicates the login error occurred and with that i can display a fixed message that stays on the page (unlike the toast).

but I still can't capture the details of the auth failure...  ie. status code or message.

**Comment by VR-Architect** [comment]
I am also stuck with this issue. If I use a conditional if/then action after the Supabase Auth Action, where I check isUserLoggedIn variable, the false path is never fired. I also tried just to set a page state variable right after the AuthAction and it is not being set. DEVS - we really need an OnError exit path on the Auth Action please. The little snackbar showing the error is not large enough for web. For some reason that action is just stopping the flow on error.
