### ISSUE TITLE
Add new component to page is extremely slow when having multiple level deep inclusion

### ISSUE THREAD

**Issue by Urriellu** [FlutterFlow/flutterflow-issues#1472]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When editing a page, after clicking `Add child to this widget` => `Components`, the entire page freezes for around 3 minutes so I have to click `Wait` on Chrome multiple times so that Chrome doesn't kill the tab. Eventually the list of custom components appears.

This started happening after I created multiple custom components (currently I have 12) that include each other in a tree, multiple levels deep (I have 7 levels deep). I suspect this issue is caused by trying to create thumbnails of custom components that are multiple levels deep, which takes too long.

Once deployed, the application works fine. The issue is exclusive to the FlutterFlow UI / Dashboard, when adding a new component to a page.

### Expected Behavior

I would expect the list of custom components to be displayed immediately.

### Steps to Reproduce

This happens on multiple browsers.

1. Create custom component L7.
2. Create custom component L6 and include L7 as a child of L6.
3. Create custom component L5 and include L6 as a child of L5.
4. Create custom component L4 and include L5 as a child of L4.
5. Create custom component L3 and include L6 as a child of L3.
6. Create custom component L2 and include L6 as a child of L2.
7. Create custom component L1 and include L6 as a child of L1.
8. Create custom component L0 and include L6 as a child of L0.
9. Create a page => Add child => Components.
10. The list of widgets will take too long to appear.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMmB25dIsbVE15DucflFmik5KUN/aOcziutBaCsofePrOpkAf8/7UFtUONenSn9APWCGjnIX/MqPj9/QU/QoHyiCc6Z4+qp2cA3MIHyhb7K3Cr63b0F6O8VgGnGByMOR2iV+XLdZS0IW62eYCevLaAXaCZjvIEUvR+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

I'm simply trying to add custom components to a page.

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: FlutterFlow UI
- Browser name and version: Chrome 117.0.5938.62
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Urriellu - We appreciate you bringing this up. According to the steps you described above, it may be a combination of your device's performance and UI clutter (complex design, adding components at various levels). A sophisticated UI structure depends heavily on device processing performance, which might also make it less usable. Keep your UI design simple and apply the components wherever they are needed

However, I can mark this issue as project specific bug. We will investigate the project and see what is the issue around FF editor performance. Considering the nature of the issue we may not be able to indicate ETA for the fix. I hope this answer can help you. Thanks

**Comment by hariprasadms** [comment]
Hi, I noticed below widget overflow errors in the most of the components in you project. These overflow errors matters to the experience you are seeing in the project. I would suggest, check and fix all these overflow issues. It can help to fix your project issue. 

<img width="694" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/43a2ce74-1cd9-4050-a38c-99f502264b55">

**Comment by hariprasadms** [comment]
Hi @Urriellu - I am marking the issue back to need more information. Let us know the status of the issue once you have fixed all overflow issues in the components. If issue still persists we can re investigate the issue. Thanks

**Comment by victoriahuang1** [comment]
Hi @Urriellu , thanks for the report. The performance issues you are experiencing are indeed due to your many levels of nested components. Normally nesting is ok, but in your case, you have dynamically generated list views in all your components. This means that the number of widgets generated just to show you the examples of the dynamically generated items in your list views is exponential (over 3^7 = 2187 if you have 7 levels of nesting).

This is not a scalable solution. I am adding warnings, which should catch and point out this kind of app designs / architecture that will cause performance issues.

To improve performance, please consider removing levels of nesting.

**Comment by Urriellu** [comment]
Thank you @victoriahuang1 

I understand how the dynamic generation of examples grows exponentially to 2187 and therefore does not scale. Therefore, for the time being, I am reorganizing my app a little bit to work around this limitation.

Nonetheless, I believe this is a reasonable use case that we often see in many other apps/websites, for example when displaying a potentially infinitely deep comment replies (that is, comments can be replied to, and subcomments can also be replied to, and so on). This use case can be solved either by supporting recursive children, or partially solved by hardcoding many levels of children as I tried to do. None of these solutions are supported by FlutterFlow, therefore infinite comment replies cannot be implemented in FlutterFlow but can be done in many other products. The fact that FlutterFlow's ListView example automatically shows 3 children by default is the only cause of this bug. I consider this a limitation of FlutterFlow and I encourage you to consider this a feature request.

Thank you very much

**Comment by Urriellu** [comment]
@hariprasadms Thank you for your help. Would it be possible to remove the screenshot above from this thread? Thank you!

**Comment by victoriahuang1** [comment]
I have removed the screenshot
