### ISSUE TITLE
Add support for Custom Data Types in Team Functions

### ISSUE THREAD

**Issue by Urriellu** [FlutterFlow/flutterflow-issues#1473]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom Data Types can only be defined at Project level. Therefore we are unable to share code in a team for multiple projects if those custom functions receive a Custom Data Type as argument or return one.

### Expected Behavior

We would like to write Team-shared code that allows custom data types.

### Steps to Reproduce

(feature request)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

-

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @Urriellu - Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!
