### ISSUE TITLE
It is actually a bug (response to Icon Button Hover Fill Colour is Bugged. Only one colour)...and if it is not it is silly

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1474]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

### Expected Behavior

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

### Steps to Reproduce

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48j/KAsIpgoccB0LXqb/pr/TkRJmk7a+Y7ie1+TUk8J5zKB+wAYvf7P1FWTL3jSlZiIU6jsH4J/PfquIb9A/IEZD6bQKpe+bliZwLxQkynR5CQEKizfW1TJNNjCG7H07Wo3RMnFM1qS3wW7V61fuivUXXsGJzzOlgRDeaLLdeK2SrDX1iXc2URm05KZDPz

### Context

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

### Visual documentation

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

### Additional Info

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by TeferiHero** [comment]
It seems similar (if not identical) to this issue, which has been deemed a bug
https://github.com/FlutterFlow/flutterflow-issues/issues/1436#issue-1889155109

**Comment by chuggmuffin** [comment]
Yes, sorry I missed it in the repo.

I was told in a previous post by a team member it was not a bug which
seemed strange.

Thanks for catching this! I will patiently await the fix
