### ISSUE TITLE
Bug or annoying feature? arrow buttons cycle the widget tree when trying to edit widget name. Multiple Projects and from new

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1475]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/09578d9b514f430dab3fcffeee6a6bce

### Expected Behavior

https://www.loom.com/share/09578d9b514f430dab3fcffeee6a6bce

### Steps to Reproduce

https://www.loom.com/share/09578d9b514f430dab3fcffeee6a6bce

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocdZ7aqJbcJ6hQMkQzM6bZI7ku1EdwEhfJD3P4kuYuPBTFpLYteaS1B6JU78jTk0w9KOi/HqUMYnGzeuG9lJz4RXQRbjUmSlbKq3CpewXEdSQOlNCGKO0be3uxNRNvdqcmQG6jiPOPCNG3qCf9qOYwx5e6fDbOY=

### Context

https://www.loom.com/share/09578d9b514f430dab3fcffeee6a6bce

### Visual documentation

https://www.loom.com/share/09578d9b514f430dab3fcffeee6a6bce

### Additional Info

https://www.loom.com/share/09578d9b514f430dab3fcffeee6a6bce

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by neian-world** [comment]
Definitely a bug :D 
Reported here as well
https://github.com/FlutterFlow/flutterflow-issues/issues/1461

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. In particular, all steps must be written as text. Videos and images accompanying bug reports are encouraged, but they don't substitute written reports. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by agreaves** [comment]
Hi @chuggmuffin, this issue has since been fixed! It should no longer be present in either the web or MacOS version of FlutterFlow.

**Comment by chuggmuffin** [comment]
I can confirm that has been fixed on my side thank you very much!!
