### ISSUE TITLE
Code magic deploy error - Custom icons can't be named as a number

### ISSUE THREAD

**Issue by LMicol** [FlutterFlow/flutterflow-issues#1476]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We ran into this issue while testing custom icons.
I've searched for this error and wasn't able to find any mentions.
We already figured out the problem, it's an easy fix, and here's how to do it.

---------------------------

Error message:

Codemagic Deploy Output
Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Error detected in pubspec.yaml:
Font family must either be null or a String.
Please correct the pubspec.yaml file at /Users/builder/clone/pubspec.yaml

Build failed :|
Step 6 script `Install pods` exited with status code 1

---------------------------

We had a Custom icon created with the name 1.
In the test worked fine, but when deploying we faced the issue above.

### Expected Behavior

Apple deploy successfully

### Steps to Reproduce

1. Go to "Theme Settings"
2. Go to "Typography & Icons" tab
3. Scroll down to "Custom Icons"
4. Click "Add Icons"
5. Add an Icon with the family name set to a number
6. Deploy to app store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ckcjf35NOm99G1s7yY+9V/CQRGDs4RY0NkuxxTRY0N5PQCJkQO8nQP1NocMilYHw/OWKcp14d0MrzjvzDIfEqGz+bGYh4z6p+aAqVWj2mRLWTF7mCQ0R9M9xWIWaC4Z+nsR1BBPJickIY3E62BNmUbA/bNpzwPWo8Sq/LZO4=

### Context

Creating custom icon for the project.

### Visual documentation

We pushed the code to Github.
This is how the pubspec.yaml looks in the repo:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/26265417/82f4846c-641b-451f-a14c-59bb8ece998e)

### Additional Info

To fix it, manually rename the icon's family name, or change it in github and deploy from there. Deleting the icon also solves the issue.

I don't think the user should be allowed to send this to the project since it causes an error, or FF should at least do a conversion to prevent this.

Also, adding quotation marks in the family in the pubspec.yaml probably solves the issue too, but I didn't test it.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Brave 1.58.124
- Operating system and version affected: Windows 10
```

**Comment by agreaves** [comment]
Hi @LMicol, thanks for the bug report! We've fixed this on our end so you should no longer see this issue after the next release. Thank you for the report and your patience! 🙂

**Comment by iaasthatech** [comment]
We are facing this issue. When is the next release going live?
