### ISSUE TITLE
Theme widgets (with unbound text) internationalization codes are the same for different texts

### ISSUE THREAD

**Issue by TeferiHero** [FlutterFlow/flutterflow-issues#1477]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I you create a theme widget with an unbound text. After exiting and reentering project, if I add a few instances of this theme widget with different text in editor, they have the same internationalization code (show the same text in run mode and built application).

### Expected Behavior

If the text is unbound, the internationalization codes, and therefore text should be different.

### Steps to Reproduce

1. Create a new project
2. Add languages
3. Create theme widget with an unbound text (e.g. text or button, click on the green chain)
4. Exit the project (to the page where you can see all your projects)
5. Go back to the project
6. Add two theme widget instances to page
7. Change one of the texts inside the theme widgets
8. Click on View Code and and observe that the internationalization codes are the same, but preview texts are different.
OR Enter Run Mode, see the texts are the same, though they were different in the editor.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kz8r134t2pbwD1arqd/lanSQUKUQ1bYIoltVTawIaJZSvG7l3WvfObhJUOcOiS3xheEyGnn8X/Mr9v879GO0qJSWuRqo7yqgBVT3yeFy6aLXSPr63b0ZSQOlgCki5yqbYnBJTPrNvSXga7DqmG97ISjXsNbKwPnojBeaeXdeK2SrDX1iXc2URm05KZDPz

### Context

I'm creating a multilingual app, and I want to be able to use theme widgets with different texts.

### Visual documentation

![Web capture_18-9-2023_172145_app flutterflow io](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/ed11dcee-9519-4eb5-ba1c-8a4abec4c3d2)
![Screenshot (148)](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/8dba380c-ef7f-4e8f-adb4-19ed6696d641)
![Web capture_18-9-2023_17242_app flutterflow io](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/ae21598c-bf55-4b4a-b5be-621d4b134668)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/e67e036f-a7f7-43aa-a8c4-d0ba460c1073)

### Environment

```markdown
- FlutterFlow version: v3.1 released September 17, 2023
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment]
Hi @TeferiHero. Thank you for the detailed report. I can reproduce this issue on my end. Working on a fix right now.

**Comment by wenkaifan0720** [comment]
This should be fixed in our next update!
