### ISSUE TITLE
Google Play deployment error: Without advance settings options from mobile deployment section

### ISSUE THREAD

**Issue by Spotynet** [FlutterFlow/flutterflow-issues#1478]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Return error when publishing to google play

### Expected Behavior

To properly publish to google play

### Steps to Reproduce

1. Deploy to Play Store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No Bug Report Code in settings

### Context

I have live users that need a critical update on android

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2172020/5f490914-d9d0-4d06-ace8-919aa50af379)

Codemagic Deploy Output
Failed Step: Publishing

== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact app-release.apk
Publishing artifact app-release.apk
Publishing artifact app-release.aab
Publishing artifact release_mapping_mapping.txt
Publishing app-release.aab to Google Play
Published app-release.aab to track internal
Google Play failed to upload artefacts. Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.: {
    "error": {
        "code": 400,
        "message": "Changes cannot be sent for review automatically. Please set the query parameter 
          changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the 
          Google 
          Play Console UI.",
        "status": "INVALID_ARGUMENT"
    }
}

Build failed :|

Publishing failed :|
Google Play failed to upload artefacts. Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.: {
    "error": {
        "code": 400,
        "message": "Changes cannot be sent for review automatically. Please set the query parameter 
          changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the 
          Google Play Console UI.",
        "status": "INVALID_ARGUMENT"
    }
}

### Environment

```markdown
- FlutterFlow version: 3.1 (realeased sept 7, 2023) Flutter version is 3.10.4
- Platform: Android
- Browser name and version: Google Chrome
- Operating system and version affected: Android
```

**Comment by Spotynet** [comment]
Hi @hariprasadms , I appreciate your help, as you can see in the Visual Documentation unfortunately I don't have the advance option (Changes Not Sent for Review). I already increased App version and builder numbers with same error output of codemagic.

**Comment by sbis04** [comment]
Hi @Spotynet, from the screenshot you have provided, it seems like you are not the owner of the project. Can you please reach out to the owner and ask to turn on the "Changes Not Sent for Review" (owner should have that option).

Also, this looks like a support request.  This doesn't qualify for the issue tracker since it's specific to your project and the steps are not reproducible, and hence will be closed. Please use chat support or contact `support@flutterflow.io`.
