### ISSUE TITLE
Not able to store a list of Colors to Firebase

### ISSUE THREAD

**Issue by joop1001** [FlutterFlow/flutterflow-issues#1479]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

An action will stop executing when trying to store a list of colors to a Firebase Array. Storing a single Color to a String in Firebase however is no problem.

### Expected Behavior

I would like to be able to store a list of Colors to a Firebase Array

### Steps to Reproduce

1. Store a list of colors in a App state Colors List
2. Create an action to store this App state to a Firebase Array

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Does not work

### Context

I am trying to have the user select colors and store it to their project

### Visual documentation

I have no visual documentation

### Environment

```markdown
- FlutterFlow version:  v3.1
- Platform: Web
- Browser name and version: Safari 16.2
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by hariprasadms** [comment]
Hi @joop1001 - Thanks for submitting the issue. You have not provided project bug report code of a blank project with issue steps details. Also adding images and quick videos to describe the exact issue you are talking about will help us to speedup the issue investigation.

**Comment by sbis04** [comment]
Hey @joop1001, I think this is a bug in our current version. But we already have a [fix](https://github.com/FlutterFlow/flutterflow/pull/1195) for this, should be available in the next update! Thanks for reporting the bug!
