### ISSUE TITLE
Getting null Authenticated User after login or refresh on web

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#148]
After login/refresh, I access the Authenticated user field and navigate to respected page based on the field value. It works fine on mobile app but when I run it on web I get unexpected results like navigating to the wrong page. I checked the issue locally and found that there is a null value error and upon further introspection, I narrowed down the issue to currentUserDocument property being null after login for a short time frame.

I have set this condition on the Home page Load also so if the user reloads while filling the profile he is navigated to the profile complete page instead of the home page I am getting the same issues sometimes on the refreshing page.

## Expected behavior (required)

Authenticate User record provides proper field values after login.

## Current behavior (required)

Getting null Authenticate User record(currentUserDocument) after login.

## To Reproduce (required)

1. Add Login Action
2. use any user field in conditional action directly after the login action
3. Add navigation(or snackbar with different messages) to different pages depending on the conditional action value
4. Run on the web
5. Try login
6. Observe the null error in the IDE console

## Context (required)

Cannot check field values after logging. I want to check a user field value(like isProfileCompleted) and then navigate to the appropriate page depending on it. Eg. Navigate to the Profile page if the profile is not complete.

## Screenshots / recordings

<img width="1282" alt="Screenshot 2022-11-22 at 9 48 30 AM" src="https://user-images.githubusercontent.com/102008213/203220694-c18c3467-3417-459b-bd1a-25e0fbce5e2a.png">

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: FlutterFlow v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 107.0.5304.110 (Official Build) (arm64)
* Operating system and version (desktop or mobile): macOS Monterey Version 12.6

**Comment by organicnz** [comment]
@Shubham-VE Hi mate. Thank you for adding this issue 🙂
I was able to reproduce this issue. Could you delete a `user_location` field in a document with a null value just to be able to avoid the null error and then navigate that user to complete adding some specific fields if it's needed? It should solve your business logic :)

**Comment by Shubham-VE** [comment]
Sorry I didn't get you. In case I am not clear, in code `if (currentUserDocument!.userLocation == null) {}` condition is used & since currentUserDocument is null with ! used it gives error. I cannot use any field related to currentUserDocument. Did you mean to delete user_location field from User collection adn use it in other collection? How an I check user_location value then as all records are accessed via currentUserDocument(Authenticated User) fields which is null. Can you plz explain in detail. Thanks.

**Comment by wenkaifan0720** [comment]
Hi @Shubham-VE . Could you share with me the project that has this issue? Or just the generated code of the login page. Thank you!

**Comment by Shubham-VE** [comment]
Hi @wenkaifan0720. Here's the project URL: https://app.flutterflow.io/project/test-chat-app-teuvmw

**Comment by wenkaifan0720** [comment]
Hi @Shubham-VE. I have pushed a fix for this issue. Thank you for your patience.
