### ISSUE TITLE
Dark Mode Bug Run Mode vs Test Mode (System default settings?)

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1480]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/af5dcf424c0a4dce9f3cf26dd4c7925c?sid=c258c82f-f043-4133-986e-8e6461b4932b

### Expected Behavior

https://www.loom.com/share/af5dcf424c0a4dce9f3cf26dd4c7925c?sid=c258c82f-f043-4133-986e-8e6461b4932b

### Steps to Reproduce

https://www.loom.com/share/af5dcf424c0a4dce9f3cf26dd4c7925c?sid=c258c82f-f043-4133-986e-8e6461b4932b

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tlsjfz4p2tbxF7qXbbflFiikUCDs7a+cvjsN+a0kjNuusEYkQePf7NnFIO8vhT2NcI2KI8WAx083HhobPEsItPiibUaZ+wc5UaALjcHuVRaq7EquKdXR8BcVVIEuHzbewkSZQJrNtWV1g2jm6AOyuTgXtJqGzOlUCRcmkKpvPkV6pAgzKXn0Jg1ZSfCvr

### Context

https://www.loom.com/share/af5dcf424c0a4dce9f3cf26dd4c7925c?sid=c258c82f-f043-4133-986e-8e6461b4932b

### Visual documentation

https://www.loom.com/share/af5dcf424c0a4dce9f3cf26dd4c7925c?sid=c258c82f-f043-4133-986e-8e6461b4932b

### Additional Info

https://www.loom.com/share/af5dcf424c0a4dce9f3cf26dd4c7925c?sid=c258c82f-f043-4133-986e-8e6461b4932b

### Environment

```markdown
- FlutterFlow version: latest public not beta
- Platform: mac
- Browser name and version: chrome latest
- Operating system and version affected: mac sonoma
```

**Comment by agreaves** [comment]
Hi @chuggmuffin, thanks for this hilarious bug report! I'd noticed something strange happening but had never investigated, so thanks for this. I managed to figure out what's going on, so this should be fixed on our next release! 😁

**Comment by chuggmuffin** [comment]
Thank goodness this was driving me nuts!

Hard to trust the previews when you get different results in different
modes and have to reload multiple times to check a change.

Glad I could help :D
