### ISSUE TITLE
Clear Color not works at Pull to Refresh Style

### ISSUE THREAD

**Issue by beckzg** [FlutterFlow/flutterflow-issues#1481]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Clear Color option not works at Pull to Refresh Style Background Color

### Expected Behavior

Clear the color, show Unset value!

### Steps to Reproduce

Click the Clear Color button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skPLl8Yt2rsdG+Kr+bsBB/Tg4QkQ1U+coscp/bxIgGIDzPOw+ZPWkYRNoTeLjYHNUIESmmlsJw/zyiOHAU/ArE0+bfKpPzc9uYQGWQn2XQZOBDM+gYUFBL5tQG2KZ57SJnhNCWPhqR1Yn73GYf++sf3PXGZz4IlFISq/LZO4=

### Context

Suddenly I set up a color in Background Color option and can not remove.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/16578737/05aa9e67-8f0a-4659-a002-d1acc159f46d

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.88
- Operating system and version affected: macOS 13.5.2 (22G91)
```

**Comment by hariprasadms** [comment]
Hi @beckzg - Thanks for reporting the issue. I can reproduce the issue. Thanks

**Comment by wenkaifan0720** [comment]
Hi @beckzg. This should be fixed in our next update. Thank you!
