### ISSUE TITLE
ChoiceChips Row rendering incorrectly

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1482]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The layout option (row) is supposed to render the choicechips in a scrollable row:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/d868d030-3382-4683-b126-a8f98c1f4244)

designer:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/53405458-df92-4942-970f-e3ab14c094fc)

It doesnt, in run mode:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/50ca83a0-656a-4297-8a61-0defad268ae5)

### Expected Behavior

For it to do as described, to render in a scrollable row.

### Steps to Reproduce

1. create blank page
2. add choicechips with layout=row

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocBH7pDMbMFAhQUkQ2I5aIIzjt4bSQgaB5T4ELQcfc/eRBRpZ/azaHxmBFClgloxpfzGktr+U/cpByWbG59x+bpycBPPbGamWoyIC4eeRHZ8TNFbIG6D36a3vxQkIfpqdVo56kOLe9/LRT6Cf9qOYwx5e6fDbOY=

### Context

Doesn't do as describe, so therefore cant be used for intended purpose.

### Visual documentation

as above

### Environment

```markdown
- FlutterFlow version: 3.20.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment]
Hi @OldFred2023. This should be fixed in our next update. Thanks!

**Comment by OldFred2023** [comment]
The fix is only half finished, it just changes the background color and nothing else, we need to be able to change the border and text color when disabled also:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/1fea8dc7-be09-401a-94a5-8be6174f01a8)
