### ISSUE TITLE
Bug on web publishing PWA

### ISSUE THREAD

**Issue by Cesarmorl** [FlutterFlow/flutterflow-issues#1486]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When publishing on web with the PWA button on it does not show the install button on the web browser.
I have send a message in flutterflow

"Hi César. This is Danny from the Support Team. 👋
Thank you for reaching out,
My apologies for the late reply
I have checked and it seems to be a bug on the web,
Please submit a bug report in the github issue tracker"

### Expected Behavior

It should show the install button.

### Steps to Reproduce

1. Click on enable PWA on the web publishing page
2. It should publish the page with the install

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlcmAuJdPschE+c/2du1KlicwFjMLa+cF0+1+FB40GJfkOoY2Y8/8bUNKT7WreAhYf0yJhnoKwfDMjYSWGPE7GEmYQKJM0JVAaxbhVT6mb8SbOrm7dnxDI/5YCG6D17uNpiMmA/V1R2QY3F6tNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to make a PWA

### Visual documentation

![pwa](https://github.com/FlutterFlow/flutterflow-issues/assets/42975028/f27362fd-7a1e-49d4-b8ed-23cd2694f9eb)

### Additional Info

Please check the bug on the pwa 

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: Desketop
```

**Comment by sbis04** [comment]
Hey @Cesarmorl, thanks for reporting the issue! It should be fixed in the next update! 😊

**Comment by fafa16** [comment]
Hello, I have the same issue (nov 2024).Enabled PWA but no prompt or event desktop icon ..
