### ISSUE TITLE
AudioPlayer crashing on web-recorded file (if Duration is infinity)

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#1488]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you add an AudioPlayer and try to play a file that was recorded from a Chrome web browser (in m4a format), it will not be able to play the file. On iOS/Android it will simply not play, on Web it will have a rendering bug and cover the whole screen in gray.

### Expected Behavior

It should be able to handle unknown Duration and simply play the file, since the audio file is valid.

### Steps to Reproduce

1. Create new page
2. Add an Audio Player
3. Add a link to an audio file which was recorded using the web browser (you can use the FlutterFlow Recording action on Chrome)
4. Try to load the page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

impossible to right click in widget - I can share test app where it reproduces

### Context

This is blocking us to release our app since we're not able to play all types of audio recordings.

### Visual documentation

<img width="415" alt="Screenshot 2023-09-20 at 9 26 16 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/6f662d7a-45ae-4c6a-b990-633458209aec">

### Additional Info

Investigating the issue myself in the code I have found what is happening.
In `flutter_flow_audio_player.dart` the `Duration` returned from the `RealtimePlayingInfos` is basically undefined at the very start of the play. It's crashing when trying to get it's values since it's actually returning infinity values, leading to wrong divisions, etc.
Changing this method:
```
  Duration duration(RealtimePlayingInfos infos) {
    try {
      print(infos.duration.toString());
      return infos.duration;
    } catch (e) {
      return Duration(hours: 0, minutes: 0, seconds: 0);
    }
  }```

Fixes the bug: you can start playing correctly and it even gets the time correctly, but only once you start playing.

### Environment

```markdown
- FlutterFlow version: v.4.0
- Platform: Web
- Browser name and version: Chrome Version 117.0.5938.88 
- Operating system and version affected: Mac Venture 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @bloemy7 - Thanks for submitting the bug. I suggest create a blank project with issue setup details and share project bug report code with us. This information is very much required to access the project and speed up the the investigation process.

Right click on any page widgets tree to see generate bug report code.  

<img width="498" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/f2050a88-8183-434d-b992-1e378e1c663d">

**Comment by bloemy7** [comment]
Hi, here is the bug report code:

`ITFTz/Hqx891rs9H+KrycflojSoWI0MdXOczitVEew4bCIj4O7AqYffBYkxBZOazaHNqJ1H9kkcz0an5htnLUPkFBxKBGqFzyM1hFxPPbEKiabaqCLuOVWt8HfJjC0Cv3J+s2RB7Is9aWCEY6lyyDfO/bz2Cf9qOYwx5e6fDbOY=`

Thanks!

**Comment by hariprasadms** [comment]
Thanks for the code @bloemy7

**Comment by agreaves** [comment]
Thanks @bloemy7 for the detailed bug report and investigation! We've applied a fix, which should be present in the next release 🙂

**Comment by koya-sunup** [comment]
@agreaves 
Hi I am experiencing the same error and happy to see this is solved!
Just would like to know when will it be the next release?
