### ISSUE TITLE
Previous character always highlighted in text input fields (only on iOS 17)

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1490]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When testing on a real device (iOS), text input fields have a strange behaviour where the character before the current position is always highlighted.
It is not actually selected, since typing does not override the character.
Quite jarring for users though.

### Expected Behavior

No highlighting of previous character

### Steps to Reproduce

1. Create a new text field
2. Build with Xcode
3. Test on a real iOS device (either connected through USB or testflight

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sdlud0wdCoDuBIk+ZPXsYRBCOOaqdGNcO0Smml4ewtGMhYfpKfYoPSiVG70//pBiYAHwTl+gQZOBEpO3dkB6EelMJ2qZ0MKJryVBIsB0SHga6mWPe+vIUXTAJLL2ImdISq/LZO4=

### Context

Normal text field behavior

### Visual documentation

![IMG_0001](https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/ee401cc2-c93c-4cd8-abd5-672037ee2601)

### Environment

```markdown
- FlutterFlow version: 4.0 Sep 20
- Platform: iOS
- Browser name and version:
- Operating system and version affected: iOS 17
```

**Comment by sbis04** [comment]
Hey @kium-one, thanks for reporting the bug. This issue comes from the [Flutter engine](https://github.com/flutter/flutter/issues/128406) itself and happens just on iOS 17 devices. This should be fixed when we upgrade FlutterFlow to use the latest Flutter version, which I'm guessing will happen very soon!

**Comment by kium-one** [comment]
Amazing, thanks a lot for the details :)On Sep 21, 2023, at 4:49 AM, Souvik Biswas ***@***.***> wrote:﻿
Hey @kium-one, thanks for reporting the bug. This issue comes from the Flutter engine itself and happens just on iOS 17 devices. This should be fixed when we upgrade FlutterFlow to use the latest Flutter version, which I'm guessing will happen very soon!

**Comment by defaultsettings** [comment]
Can you forecast when this issue will be solved?

**Comment by hariprasadms** [comment]
Hi, Is this issue still persisting ?

**Comment by kium-one** [comment]
Not yet solved in the Sep 28 release.

**Comment by sbis04** [comment]
It's not deployed yet, should be out this week! Keep an eye on when the Flutter version updates to `3.13.x`:

<img width="268" alt="Screenshot 2023-10-02 at 5 18 57 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/b9683143-11f0-4431-af3e-24666af01fac">
