### ISSUE TITLE
Lottie animations doesn't work with conditions

### ISSUE THREAD

**Issue by sabatage3** [FlutterFlow/flutterflow-issues#1491]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am currently trying to create a transition between 2 Lottie animations, a loading animation, and then a success animation, there are multiple ways to achieve this, I am using a conditional widget to show one Lottie animation or the other depending on a variable, to test this you can simply create a switch widget or a boolean condition to specify which widget within the conditional widget will be shown, and you will notice that it only shows the default, sometimes when the condition is true it only shows the same Lottie animation but smaller, this only happens with Lottie animations, I have tried using different widgets in the conditional widget and it works fine, I have also tried using a single Lottie animation but with a condition in its path, and I got the same result, it only shows the default one.
If I show the 2 Lottie animations at the same time on the page, there is no problem only happens when trying to show multiple Lottie animations using conditions.

I have already tried to publish my application for the web before reporting this, I had the same result

### Expected Behavior

The expected behavior is to show one Lottie animation or another depending on a condition.

### Steps to Reproduce

1. Create a new page with a switch widget or a boolean variable and a conditional widget with 2 Lottie animations.
2.  Assign a condition where a Lottie animation will be shown if the switch or boolean variable is = true (you could also use an int variable and assign a number to each Lottie animation in the conditional widget, but you will have to use a button to modify the value of the variable).
3. You will notice that even when the condition works and the value of the variable is changing (you can use a text to print its value) the Lottie animation that is supposed to be shown is not shown, only the default animation will be shown.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Lq4Y9grs9c15Pyb+9VtD0RHDp6aK00u9tuGEgdCLbyD4lzf8/BQBJtXbyndghEPU2J8XE1082Nm9z1U/UrEyqcfrZNzpN6SgvyIUKtMqagOpDtbWpUGshWCUDH5MKG3B0lGNt1c0IY70+IO9+/ExfbQpe2IlUaRfGaMZLXvgfuQ0SLb3kNh1JWeC/v

### Context

I would like to create a seamless transition between 2 Lottie animations, for example, a "loading" animation followed by a "success" or "fail" animation depending on a condition, since is not possible with a single Lottie animation, the closest approach would be to use 2 separated Lottie animations, but this issue forces us to use a single Lottie animations per time

### Visual documentation

Here one of the Lottie animations is shown because the int variable is = 1.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15147720/aba4ba88-70a5-4310-a957-ea09da49535d)

But when the variable changes to "2" it just shows the same Lottie animation but bigger instead of showing the other one.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15147720/891ced6d-d606-4f6c-83a8-621b602aff45)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Brave/Chrome
- Operating system and version affected: Desktop: Windows
```

**Comment by joshua-ffio** [comment]
Hi @sabatage3, from my testing, it looks like this behavior only happens in web builds. Can you confirm that is your experience?

You should be able to get the correct behavior by assigning a unique ValueKey to both of your lottie animations. Please try this out for now.

<img width="298" alt="Screenshot 2023-09-22 at 6 13 39 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/141682285/4b04cf74-7366-439f-ae22-274e3228d80f">

I will keep this ticket open for now to do a bit more investigation, but please let me know if this solution works for your use case.

Thanks!

**Comment by joshua-ffio** [comment]
@sabatage3 , I've submitted a fix for this issue and it should be going into an upcoming version update of FlutterFlow. You will be able to use your conditional builder with different lottie without the workaround that I mentioned in my last comment. Thank you for reporting this and helping us improve FlutterFlow!
