### ISSUE TITLE
New update in FF

### ISSUE THREAD

**Issue by Demetre-Panjakidze** [FlutterFlow/flutterflow-issues#1496]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A new update came out and when I open up any of the projects a green rectangle is shown that says: "More recent version of FlutterFlow not available! Simply tap to refresh". I clicked on it on my computer and it worked. now I need it to work for another computer with the same account. I click on it and after a page restarts nothing is changed and the green rectangle appears again.
![greenMessage](https://github.com/FlutterFlow/flutterflow-issues/assets/111850949/7fcf49bc-182f-4cec-aba6-8e77c2940f15)

### Expected Behavior

After clicking it FF should update.

### Steps to Reproduce

1. tell me what could be wrong
2. help me fix it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grs9J1s/IdfoxnSQ7NUh+aLswmspBZywgfZzzBLN/fPfQPhNWZMvgTVZte2Gmp14DpfOKvuDlMccBOROCGoRl/7libjnjVj6hVJeTF7qCZXZAJ59XfWKs3Jm7pyUnBM9YckIH60+uG+u9cHHbNpj7DFQ8Sq/LZO4=

### Context

I can't update FlutterFlow.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/111850949/a3abd242-99ce-482e-a5fb-db6c484e0366

### Environment

```markdown
- FlutterFlow version: want to have the newest v4 but can't update to have it.
- Platform: Web
- Browser name and version: Chrome 117.0.5938.89
- Operating system and version affected: Windows 11
```

**Comment by Demetre-Panjakidze** [comment]
Thanks for the response. I already fixed it. It worked on every browser except Chrome and after I cleaned the site data the problem was resolved.

**Comment by hariprasadms** [comment]
Thanks. I'm closing the issue as you its been resolved for you now. Thanks
