### ISSUE TITLE
Bug on animation preview.

### ISSUE THREAD

**Issue by Boburshoh** [FlutterFlow/flutterflow-issues#1498]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can not select widget after clicking animation preview. Also animation preview works only one time.

### Expected Behavior

I expect that I could have select widget again and can preview animation again and again.

### Steps to Reproduce

1. Drag any container to screen.
2. Add animation.
3. Preview animation.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

There is no bug report code

### Context

I am trying to preview animation again.

### Visual documentation

There no visual documentation.

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: iOS
- Browser name and version: Version 116.0.5845.187 (Official Build) (arm64)
- Operating system and version affected: iOS
```

**Comment by sbis04** [comment]
Thanks for reporting the issue! It should be fixed in the next update! 😊
