### ISSUE TITLE
"SlideableListTile" doesnt come up in widget search even though it exists in the widget list

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1499]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Expected Behavior

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Steps to Reproduce

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Context

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Visual documentation

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Additional Info

https://www.loom.com/share/0f3e4e4d9aa44ccb940cbf0c4366da3c

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by victoriahuang1** [comment]
@chuggmuffin thank you for the report. I have fixed an issue on our side, and this should be resolved upon the next deploy

**Comment by chuggmuffin** [comment]
Happy to help!
