### ISSUE TITLE
iPad version doesn’t allow changes to custom code

### ISSUE THREAD

**Issue by bertke** [FlutterFlow/flutterflow-issues#1500]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the iPad version of flutterflow, any change to custom code will not ‘save’.  When you add code and click save (even if just a comment) the following error is returned: “The function is empty or cannot be parsed. Make sure not to modify code outside of the designated area’.  The code added can be within the designated areas and this error still returned.  The same change applied through the web UI or Mac version will save successfully.

### Expected Behavior

Code changes (that are valid) should save on the ipad

### Steps to Reproduce

1. Open a project in FF
2. Go to custom code area
3. Modify an existing custom function
4. Click save

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

cant_get_on_ipad

### Context

Develop on the iPad 

### Visual documentation

Graphic would just be a picture of the error. Defect is easy to reproduce

### Environment

```markdown
- FlutterFlow version: 
- Platform: iPad
- Browser name and version: NA (native iPad app)
- Operating system and version affected: current iPad os
```

**Comment by SameerShahzad99** [comment]
Thank you so much for reporting this bug, I was able to reproduce this issue on my end!

**Comment by bertke** [comment]
thank you!
