### ISSUE TITLE
iOS's screenshots are not in correct size

### ISSUE THREAD

**Issue by marcaureln** [FlutterFlow/flutterflow-issues#1501]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In Screenshot Mode, the iOS captures are not in the correct size. They cannot be imported on the Apple App Store. E.g. For the iPhone 6.7” display, it should be 1290×2796, but I got 645×1398. And it's the same for all other devices, iPhones and iPads.
(when I say same, not the same size, but they are all undersized)

### Expected Behavior

Screenshot should come in the correct dimensions.

### Steps to Reproduce

1. Click on `Preview app`
2. Click on `Screenshot Mode` and open dropdown
3. Toggle App Store Screenshots (iPhone & iPad)
4. Click on `Generate Screenshots`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lPLlw5dOseZE7c/AaflV+WA5Jjs8beYN0etraCosfZT2BLMcec/RVERCXf2+YXNEfWeWo2oW0fz1iPD9F/IBBw6VbrZb+ZYAEwrzXlOXRL6WFJWgWmh9MJ9hGUC55ravuBN/AMl1R1of7E2Te97KaALsQ7rKNVQWDa/LZO4=

### Context

Was trying to complete my iOS app submission on App Store

### Visual documentation

![Capture d’écran du 2023-09-21 11-10-59](https://github.com/FlutterFlow/flutterflow-issues/assets/12394791/ee0af613-77e7-4d9f-9750-9302f5b333d9)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chromium 117.0.5938.62 (Official build) for Linux Mint (64 bits)
- Operating system and version affected: Linux Mint 21.2 x86_64
```

**Comment by SameerShahzad99** [comment]
@marcaureln Thank you so much for submitting this issue, i was able to reproduce this on my end!

**Comment by corestats** [comment]
Hi @sbis04  after trying to manual resize the exported file (Powertools Windows) I also get an error regarding the transparency channel of the screenshot, it's not allowed in App Store Connect.
![Screenshot 2023-09-21 071703](https://github.com/FlutterFlow/flutterflow-issues/assets/68249631/3711cbfd-d202-4c8f-8480-9a32ea25771e)

**Comment by sbis04** [comment]
Hey @marcaureln, thanks for reporting the issue! It should be fixed in the next update! 😊

@corestats can you please create a separate issue regarding the transparency (or alpha channel) issue? Also, include a sample screenshot causing issue while uploading.
