### ISSUE TITLE
Problem with connecting to Firestore from FlutterFlow project

### ISSUE THREAD

**Issue by Demetre-Panjakidze** [FlutterFlow/flutterflow-issues#1502]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In some of the projects, I'm having problems with connecting to Firebase. I try to log in to my account using Firebase. Authentication is updated and the user is created. However, despite the fact that I have turned on the creation of a document in a collection, it is not updated and the data is not received from Firebase. The page is loaded without content from the back end. When I look at the console I see two errors:
"@firebase/firestore: Firestore (9.18.0): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend." 
and 
"dart_sdk.js:5476 Uncaught (in promise) Error: FirebaseError: [code=unavailable]: Failed to get document because the client is offline.".

### Expected Behavior

I want to have a good connection with Firebase and load data successfully.

### Steps to Reproduce

1. Help me find the issue
2. Help me fix the issue

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hvLlvJROxL1E17Xyb8JvmjoRNUM7aL8vmOwbWQo8J5zKB+wAYvf7P1FWTLy/SmNEOmejjmQy/Pfqjs7PO/QEHyucGpxa1blcaDvdQkOjaJfSO5aJfW1QL8JRGnbC0MOnsx5/NsxZLXwZ7WaUHNi+ShPYNIC0OkU7DsibKdeK2SrDX1iXc2URm05KZDPz

### Context

I can't use FlutterFlow correctly anymore with the back end in my app.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/111850949/12f683a9-02d1-43fd-9820-96f1093b279d

https://github.com/FlutterFlow/flutterflow-issues/assets/111850949/b508cc26-02d8-4040-8d54-e97b19043247

![problem2](https://github.com/FlutterFlow/flutterflow-issues/assets/111850949/b4ba66fa-cfb1-49e2-b856-cf8fcbd5dd57)

### Environment

```markdown
- FlutterFlow version: v4 
- Platform: Web
- Browser name and version: Chrome 117.0.5938.89
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment]
Okay, so this seems to be a project-specific problem, App check is turned on on your project, this problem is usually caused when you have not set that up correctly, please follow the documentation for Appcheck again:
https://docs.flutterflow.io/settings-and-integrations/project-setup/firebase/app-check
if you still face any problems, you can reach out to chat support or email at support@flutterflow.io!
