### ISSUE TITLE
Onboarding popup returns on relaunch

### ISSUE THREAD

**Issue by MadeByDouglas** [FlutterFlow/flutterflow-issues#1505]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using FlutterFlow in the browser (safari or arc (chrome)) the onboarding comes up telling me to "build your first page" and no matter what I do, this popup always comes back if I refresh the page or come back after closing the tab. see https://community.flutterflow.io/widgets-and-design/post/how-to-stop-build-your-first-page-onboarding-coming-back-YmUTtl6BiJsdC0Z?highlight=EiFx2tayCRbQRjV

### Expected Behavior

after completing the onboarding I expect to never see it again on relaunch of the app / website

### Steps to Reproduce

1. start using fluter flow
2. be annoyed by the onboarding popup forever

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

It's annoying, I want to use the editor and not close out the onboarding every time. My teammate also experiences this behavior.

### Visual documentation

![CleanShot 2023-08-03 at 01 48 58@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/10858053/68ff34d6-53a4-4d36-a16e-726532dad178)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Safari 16, 17; Arc 1
- Operating system and version affected: macOS 13, 14
```

**Comment by wenkaifan0720** [comment]
Hi @MadeByDouglas. This is because you are in the tutorial project which will always launch the tutorial in our current setup. I do agree that this is not the best UX and we are working on improving our onboarding process. Since this is more like a feature request/update, I will close this issue for now.

**Comment by MadeByDouglas** [comment]
Uhh, this is not the tutorial project, it's our startups project. Or if it was the tutorial project, we created our entire project on top of it. Why do you say its the tutorial project, and / or how would we go about changing that?

**Comment by wenkaifan0720** [comment]
Hi @MadeByDouglas. Could you provide a bug report code? I can manually resolve this issue for you.

**Comment by MadeByDouglas** [comment]
OK here it is IT4gz8jfz812ofpE7aX6bu9ahSkQNWIjUL00sNobbxAjIoDoPJkUaeCkN09DTseqdHxDKEWJgloepsmKvuzxOvkFOkmCfro/yLgJWhXzTTq/aoTWDZOaYEFSQMpgFVTA356JryVSXPVuWXBiw02MHPOQbCbBNb37Zwh9f6PHaOI=

**Comment by wenkaifan0720** [comment]
Should be resolved for you now!

**Comment by MadeByDouglas** [comment]
ah wonderful! thank you
