### ISSUE TITLE
API Variables not showing on Actions

### ISSUE THREAD

**Issue by eborges-git** [FlutterFlow/flutterflow-issues#1506]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created an API POST Call with Variables.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/58300234/b9225254-d9ff-4a35-bc4d-b45ab807ed8b)

When I try to call that API via Action, the Variables won't show up to be filled.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/58300234/8e7a76fc-f119-4698-a35d-bcb7b2fd4027)

It also displays an error that the API isn't found:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/58300234/fc03c6a5-8673-4352-aa16-a786d8a36618)

Even though it has been Deployed for Function (CORS issues), Tested and Saved.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/58300234/110a9715-46cd-4ca2-8410-ed2711c12850)

PS: I also noticed that if you start the API call as GET and change to POST, bugs happen.

### Expected Behavior

Variables should be available to be set, such as another API call I have working properly:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/58300234/0b11f357-259e-4c7b-9096-235985d09600)

### Steps to Reproduce

1. API Calls
2. Add API Call
3. Set POST and URL
4. Create Variable "credentialId" as String, isList false, default empty.
5. Define Body as: { "credentialId": "<credentialId>" }
6. Save
7. (deploy as private call to fix CORS errors)
8. (it works on blank projects)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okvHlvJFgobwF+KX2dsdVpyQ7Jk83bIIR0MpBZzUYF5SuCJkqfPfAP0lBQuHgY29Ye2emp140wtrXkt/LLPFfHAecGdU/1rpcbg2Wd3OtM7mTF7qwRXFtEZhNBWK+4JmFsB5NHMBYdVYe3zqqHN+icAnvHpjFDGowSq/LZO4=

### Context

Call my backend

### Visual documentation

Submitted above.

### Additional Info

I'm struggling with CORS errors on Safari browsers and iPhones. Recently activated CanvasKit to make it work, even though sometimes images are not loaded due to that change.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web - MacBook Pro M2 Max
- Browser name and version: Chrome 116.0.5845.187 (Official Build) (arm64) 
- Operating system and version affected: Ventura 13.5.2 (22G91)
```

**Comment by agreaves** [comment]
Hi @eborges-git, thanks for the bug report! This was due to a bug we had when you initially create an API call. If you go back to the project you should see that the option to add variables for this API call is now present. In any case, we've fixed this bug, and this should be reflected in our next release. Thanks! 🙂
