### ISSUE TITLE
insertAtIndex not added to model

### ISSUE THREAD

**Issue by TomJFox** [FlutterFlow/flutterflow-issues#1507]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am attempting to add to the start of a list rather than the end.  I attempted to use the 'Insert at Index' to update a list of Image Path variables in the Page State.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/106626912/c395a592-5534-49da-9082-533e92198697)

However, upon running a Test Build, I get the following compilation error:

```
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/pages/home_page/home_page_widget.dart:191:34: Error: The method 'insertAtIndexInPhotos' isn't defined for the class 'HomePageModel'.
 - 'HomePageModel' is from 'package:add_remove_page_state_list/pages/home_page/home_page_model.dart' ('lib/pages/home_page/home_page_model.dart').
Try correcting the name to the name of an existing method, or defining a method named 'insertAtIndexInPhotos'.
                          _model.insertAtIndexInPhotos(1,
                                 ^^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         75.4s
Failed to compile application.
```

### Expected Behavior

I was expecting for a new image to be added at the beginning of the list rather than then end of the list.

### Steps to Reproduce

1. Create a new page
2. Add a list to the Page State
3. Set action to insert at position 1.
4. Run test build.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gl/H12ItPm9tE1s7ide9ajjgvQ187auYviutudAwbCLbkOp13f+P8RFRBcO6BagtEeGeGmn0y+KDIv4fMVsY4aE6CQ4Nez7tXEQ7vWjmtM7HSOqqCSX9TJ8ZWBVTDyJ6smA9SNsdsSiE57TiMDO/KaAnZJ4zuDFYdDvmIBNv/pGCBGh/CUSx7wmNecCfn

### Context

I have a list of images displayed from the list of image paths stored in the Page State.  I want the list to be displayed in reverse order (so the newest addition shows to the left rather than the right).

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/106626912/bd28f501-59fb-4147-aefb-6f4c9821387d)

### Environment

```markdown
- FlutterFlow version: v3.1 and v4.0
- Platform: Intel x86 Jasper Lake
- Browser name and version: Google Chrome Version 116.0.5845.189 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro Version 10.0.22621 Build 22621
```

**Comment by sbis04** [comment]
Hi @TomJFox, thanks for reporting the issue! It should be fixed in the next update! 😊

**Comment by TomJFox** [comment]
@sbis04 thanks 👍

**Comment by TomJFox** [comment]
Hi @sbis04, When will the update be published?
