### ISSUE TITLE
Error in custom function

### ISSUE THREAD

**Issue by K0styan** [FlutterFlow/flutterflow-issues#1508]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I test my custom function I got an error message.
"Error running the function . Pleas contact support@flutterflow.io"

### Expected Behavior

I have created a custom function.
Here it is:

`import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/uploaded_file.dart';
import '../../flutter_flow/custom_functions.dart';
import '/auth/supabase_auth/auth_util.dart';

dynamic rrSchedule(List<TournamentsPlayersRow> participants) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  //  get list of rows from supabase table and create roundrobin schedule as json string
// function to create round robin schedule from list of participants
  final int numParticipants = participants.length;
  final int rounds = numParticipants - 1;
  final int half = numParticipants ~/ 2;

  List<List<String>> schedule = [];

  // create initial schedule
  for (int i = 0; i < numParticipants; i++) {
    List<String> row = [];
    for (int j = 0; j < half; j++) {
      int opponent = (i + j + 1) % numParticipants;
      row.add('${participants[i].player} vs ${participants[opponent].player}');
    }
    schedule.add(row);
  }

  // create reversed schedule
  List<List<String>> reversedSchedule = [];
  for (int i = 0; i < numParticipants; i++) {
    List<String> row = [];
    for (int j = 0; j < half; j++) {
      int opponent = (i - j - 1 + numParticipants) % numParticipants;
      row.add('${participants[i].player} vs ${participants[opponent].player}');
    }
    reversedSchedule.add(row);
  }

  // interleave reversed schedule with initial schedule
  List<List<String>> interleavedSchedule = [];
  for (int i = 0; i < rounds; i++) {
    if (i.isOdd) {
      interleavedSchedule.add(reversedSchedule[i]);
    } else {
      interleavedSchedule.add(schedule[i]);
    }
  }

  // create json string from schedule
  List<Map<String, dynamic>> jsonSchedule = [];
  for (int i = 0; i < interleavedSchedule.length; i++) {
    for (int j = 0; j < interleavedSchedule[i].length; j++) {
      Map<String, dynamic> match = {
        'match_number': (i * half + j + 1),
        'team1': participants[j].player,
        'team2': participants[(j + half) % numParticipants].player,
        'date': '',
      };
      jsonSchedule.add(match);
    }
  }

  return jsonEncode(jsonSchedule);

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
`
I expected that this function will get a list of rows from subabase's table.
Here the schema of the table.
![tournaments_players](https://github.com/FlutterFlow/flutterflow-issues/assets/15695694/8dba296e-cc19-4024-917b-61aa74bba2bb)
Then the function should combine player id's into a schedule of games based on roundrobin principle.
The schedule is a JSON string like {q12w3e4r5t vs 0p9o8i7u6y, w3e4r5t6 vs i8u7y6t5}

In Test Function tab I created a dummy rows like this.
![test_data](https://github.com/FlutterFlow/flutterflow-issues/assets/15695694/74f22db0-765c-49ca-b0a5-08679533059a)

After that I run test and get the error message - "Error running the function . Pleas contact support@flutterflow.io"

### Steps to Reproduce

1. create a supabase table like mine
2. copy and paste my function
3. fill in test data
4. press run button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez8/f24l1pbxI17rAasZFvwMwJ0QlUIInj+0bWRMhNY+uBIY2Ycj7P0pLYtfhfH1iOlSjoHsdzNbzjuzxDfUrFE+cfIA9z75XQQLMfDuXRKarDZe0bUZAJ59RIBXH07eFkBJAA7ZaLkY42WGQLvCdG3qCf9qOYwx5e6fDbOY=

### Context

This function is one of the core functions in my project.

### Visual documentation

none

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Firefox
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
This problems seems to be specific to your custom function, please dig deeper to find the core problem, if you think this is some bug from our end, you can reach out to FlutterFlow support,  find out the exact issue and reproduce it on a blank project first!

**Comment by dawitephrem565** [comment]
I hate your answer. none of your response are useful if you don't know any think about the solution just keep quite. I hate the custom function of flutter flow the dev's are too junior to develop it bad platform.
