### ISSUE TITLE
Using Supabase in Custom Functions

### ISSUE THREAD

**Issue by buyblvd-ryan** [FlutterFlow/flutterflow-issues#1509]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom functions allow you to select Supabase rows as a type when specifying parameters or returns, but there is no way to include the package necessary to use these types without errors.
![CleanShot 2023-09-22 at 12 37 18@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/117312895/44619a2a-5ce3-4cf7-a398-34697dbd3c8e)

### Expected Behavior

If I'm allowed to select the type, it should automatically add the correct import to the project.

### Steps to Reproduce

1. Create a project with supabase connected
2. Create a new function and select Supabase Row as return or parameter type
3. Bask in the glow of the errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ts7nwIZJnbRK1pfQa8cwmhIWJEA6X5EW18J7aCsofePrOpkAf8/7UFtUOOaldFFXM02aij0X/Mrokd/hIcABOSScfqJy/89UewndcFqlMZfRDYS3b0Z8PJlWGGqf5KW3mB5DHPVpL3xgw0+qO+u/ThfrJoP4OWokAOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I would like to work with supabase rows in a custom function.  In this case, i need to use the custom function to generate a list of custom data types from an inputted list of rows.  there is no clean workaround to use an action, and I shouldn't have to anyways.  This is necessary due to the limitations of generated drop down menus. 

### Visual documentation

![CleanShot 2023-09-22 at 12 37 18@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/117312895/d6432339-e724-406c-a044-01087abe39d2)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Development
- Browser name and version: Arc 1.5.1 (Chrome-based)
- Operating system and version affected: N/A
```

**Comment by agreaves** [comment]
Hi @buyblvd-ryan, thank you for the bug report! We've reproduced this issue and have a fix that will be present in the next release! 😊

In the meantime, feel free to ignore the errors in the code editor, the function will still compile and work correctly.
