### ISSUE TITLE
iPad code reformatter clears custom code (Custom Function, Custom Widget & Custom Action)

### ISSUE THREAD

**Issue by ToddHerron** [FlutterFlow/flutterflow-issues#1511]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the iPad app to edit custom code and you press the “format code” icon, all the code disappears from the editor and it only shows line numbers 1 and 2 with no code content. 

### Expected Behavior

Custom code should reformat. 

### Steps to Reproduce

1. Using an iPad, go to custom code
2. Select any of “New Function”, “New Widget”, or “New Action”. 
3. Press the code reformat icon. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/test-project-e1hto6?tab=customCode&customCodeTab=functions

### Context

Unable to edit projects on iPad. 

### Visual documentation

[https://share.icloud.com/photos/00bjPG19kkEpp9xJJCVgpSktw](url)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iPad 
- Browser name and version: n/a
- Operating system and version affected: iPadOS 16.7 (20H19)
```

**Comment by hariprasadms** [comment]
Hi @ToddHerron - Thanks for posting the issue. I can reproduce the issue. 

Dev note - Below is the quick video showing the issue.
https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b7e6e7b3-45e2-4f56-b519-86e2ee596111

**Comment by ToddHerron** [comment]
Unfortunately, this still isn't working for me. Now I get "Code is improperly formatted" when I press the REFORMAT button. 

To recreate:

1. Add a Custom Function
2. Add the line of code `return "Hello World!";`
3. Press REFORMAT

![Screenshot 2023-10-16 at 15 10 08](https://github.com/FlutterFlow/flutterflow-issues/assets/2007969/53a149ae-f7f8-4353-924a-c8c3d8b96c82)

**Comment by ToddHerron** [comment]
It turns out that you need to turn OFF "Smart Punctuation" on an iPad so the single and double quotes remain the vertical ones (' and " are the only ones accepted by the Dart compiler) instead of the slanted ones (‘ and “). 

To turn OFF Smart Punctuation:

1. On your iPad, go to **Settings > General > Keyboards**
2. Under the **All Keyboards** section, toggle OFF **Smart Punctuation**

**Comment by sbis04** [comment]
Thanks @ToddHerron for confirming that works! I was trying to figure out if there's a way to fix that without turning off the "Smart Punctuation" (since a lot of people might not be able to figure out this), but haven't got anything yet. I'll update this thread if there's a solution!

**Comment by sbis04** [comment]
Hey @ToddHerron, this should be fixed in the next FlutterFlow iPad app update! It should now work properly even with "Smart Punctuation" ON.

**Comment by ToddHerron** [comment]
Works perfectly now! Thanks! :)
