### ISSUE TITLE
Inability to define %, px and inf in conditional formatting for height and width

### ISSUE THREAD

**Issue by winthermich** [FlutterFlow/flutterflow-issues#1513]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to add conditional formatting for the width and height of a component (e.g. a container), we cannot select whether the entered value is %, _px_ or _inf_.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/1b1773d7-94a7-4a40-94e8-76583a2ab927)

### Expected Behavior

When attempting set the conditional width or height of a component, it should be possible to select whether the entered value applies to px, % or whether the value is inf.

I am aware that someone might treat the px + % part as a feature request. But I would assume that the inability to set an inf-value is a bug.

Here's a mock-up of what I would be expecting (in a perfect world) :)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/dc08a3cd-81ea-458b-9412-adf0aa6a8e33)

### Steps to Reproduce

1. Add a container to a canvas
2. Attempt to define the a conditional for the width of the container.
3. Conclude that it is not possible to indicate whether the value is %, px + that it is not possible to select inf.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkMmAsJRNobVE+anQLcFFvCowFjMMbY0v0u0bFB4cG5TvPewUfeP8V0NKTeG7fW9YMU6YrDkzwvOKiNrpM8IEORyuGd1n0JVAez3KIUKXR5iyCJGOfX9tGcJTfxGl15mJgRRAJsZeV2QEwF2HNq3qNleeY8aSfxBlZ7vfcPo=

### Context

This limitation severely prevents us from achieving a truely responsive design (i.e. when we want to set it to 350px for large screens, and 100% or _inf_ for small and medium screens).

### Visual documentation

Current functionality:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/207cb1b3-6cdf-4c25-9c2f-2644cfdfd7ea)

I guess this is how it should have been implemented:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/944c56b6-82d5-4c8f-b513-a7b66f30e8f6)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 116.0.5845.188 
- Operating system and version affected: Windows 10
```

**Comment by agreaves** [comment]
Hi @winthermich, thanks for the bug report! I agree it would be quite useful to set by `% of screen` more easily, and understand that what you provided would be the best UI for it. As you said, however, this is indeed a feature request strictly speaking.

However, luckily we have two mostly easy workarounds:

**For Using as %**
We have the "Fraction of Screen Width" and "Fraction of Screen Height" variable options, which allow you to set a variable as a fraction of the total screen dimension.
<img width="428" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/9f08f569-9731-4370-a9fc-e8548037d59a">

**For Infinity**
We're adding an "Infinity" option to the `Constants` variable menu in the upcoming release 🙂
<img width="483" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/5b912f1d-8c90-4427-9ad8-d0b6952a2019">

Hope this helps!
