### ISSUE TITLE
Floating navbar icon size has no effect

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1514]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the floating navbar style is selected, the icon size settings don't have any effect.

### Expected Behavior

Same as other navbar styles.

### Steps to Reproduce

1. Choose floating nav bar style
2. Change the icon size for one of the pages
3. The icon size doesn't change

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sNobbxAjIoDoPJkUac7RSBJvZOm6YAk2KEWJ+Uwz+vTKv9rxVPdfJkyCRog9+Id2FgnxeEC/aoubOpeWOn8nMJlPf0yi0ra3nQolKbdaSiVm7XGqF9++RXbUQeb7Zwh9f6PHaOI=

### Context

Trying to use the floating navbar because the default navbar doesn't allow "always show navbar on page".

### Visual documentation

<img width="705" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/811c4264-cfd6-40b0-8e57-ab813cafabd3">

### Environment

```markdown
- FlutterFlow version: v4.0 Sep 20
- Platform: Chrome
- Browser name and version:Chrome Version 116.0.5845.179 (Official Build) (x86_64)
- Operating system and version affected: MacOS 13.5.2 (22G91)
```

**Comment by kium-one** [comment]
Workaround: enable "different active icon", then the size is considered.

**Comment by agreaves** [comment]
Hi @kium-one, thank you for the bug report! We've reproduced and fixed the issue, which should be reflected in our next release. Thanks! 🙂
