### ISSUE TITLE
Refreshing App State-Based Values Used in a Component within a ListView

### ISSUE THREAD

**Issue by EmersonFJ** [FlutterFlow/flutterflow-issues#1518]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a API-based Backend Query on a ListView using Infinite Scroll and storing the backend query in App State so that it can be accessed across the app, refreshing App State does not result in a refresh of App-state based values.

See pre-build project here for reference: https://app.flutterflow.io/project/sync-page-list-view-test-1mfesy

### Expected Behavior

I would expect that you could refresh the App State-based values within the component tiles of the ListView without causing a re-scroll or a re-call of the API.

### Steps to Reproduce

1. See pre-build example referenced above and here: https://app.flutterflow.io/project/sync-page-list-view-test-1mfesy
2. Create a CustomDataType to hold values from the API call
3. Create an AppState variable that is a List of CustomDataType
4. Create a page with a Listview ("ListViewPage"); have that ListView be an infinite scroll API-based backend query 
5. Create a custom component that can be used as a ListView Tile, and have that component use OnInit to load the data from the backend query into the AppState CustomDataType List; have functionality to change values shown on that custom component and update the AppState CustomDataType List to reflect changed values; put a "View" button on the custom component to navigate to a specific page showing the same component
6. Create the page you navigate to after clicking the "View" button referenced in #-5 ("ViewPage")
7. Run the App and wait for the ListViewPage to load. Scroll down a couple pages and then click "View" on a component to navigate to ViewPage. On ViewPage, change one of the values shown and make sure that also updates AppState to reflect the change.
8. Navigate back to the ListViewPage
9. You will see that the values on ListViewPage did not refresh.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fhc7lvJVgrs9Y7s/tbcFFoCoRMjt9aIIr0cNxcxQafIvqE4l3YvfOSBdJYteBd2xcOWH+gjo03MrJvtieG8EFPQuCQbk7+IVXdzmWRn6XVqaRC7i8WGtCDe9MCH671pmvvCNTC/NzWiE+2GeIHemyVj3aNpDvIUcGQ/GlCJzUpGCDHSLRUyYzzRgUMG7eTI5ODEz25eKMrop5yfj/0w==

### Context

This prevents me from being able to create a production-ready app due to an inability to create a consistent experience between pages for the user. 

I think a good way to explain why this matters so much would be to look at anyone using FF to make a social media-like app - so think a Twitter clone... or Instagram, Facebook, etc.

You have a newsfeed that has 100+ Tweets. You scroll down and you keep loading more, eventually you click on a Tweet to see that Tweet-specific page and all the comments. You like the Tweet on that Tweet-specific page. You click the back button. Now, you should see on that newsfeed that you liked that Tweet. The data should be consistent between those two pages for each individual Tweet.

Right now, actions done on the Tweet-specific page cannot be synced to the newsfeed, as discussed above. (In the pre-built example discussed below, the Tweet-specific page would be "ViewPage" and the newsfeed would be "ListViewPage")

### Visual documentation

Here is a pre-built project: https://app.flutterflow.io/project/sync-page-list-view-test-1mfesy

The ListViewPage loads an Infinite Scroll ListView using an API. The Listview within that page replicates TileComponent for the list. The TileComponent can be clicked on to view a specific "post" on the ViewPage. The ViewPage also shows a TileComponent that should be in sync with ListViewPage tile for the same index.

The TileComponent uses OnInitialization to store the value from the Backend Query to an List in AppState. This is done for two reasons - 1) since a ListView disposes tiles when they scroll across screen, you can ensure that your previous selection of "Default" or "Custom" is kept when scrolling back and forth (this is done by a conditional statement in the OnInit) and 2) it lets you theoretically keep data consistent between ListViewPage and ViewPage (except it doesn't as discussed here, thus this bug report).

The TileComponent has a radio button set to "Default". You can change this to "Custom." Changing the radio button updates the list in App State at the appropriate index to reflect this change. If you change this on the ListViewPage, and then navigate to the ViewPage, the data will be the same. However, if you make a change on the ViewPage and navigate back to the ListViewPage, the change will not be reflected.

Thank you for all the help. Love the FF team! This is, as far as I am aware, the only issue I am having that prevents me from launching a limited user initial trial of a product. Thank you!

### Additional Info

Thank you for reviewing. 

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 114.0.5735.133
- Operating system and version affected:  MacOS
```

**Comment by EmersonFJ** [comment]
Thank you @hariprasadms - please let me know if you need anything else at the moment and very much appreciate your help here. Hope all is well!

**Comment by jerperdue** [comment]
+1 Similar issue for me. I have a listview and a details page. If I navigate to the details page, change a value, and hit "Back", the listview does not appear updated with the new value (although the value is updated on the backend). This seems like a basic workflow that should work properly, I would love to see a fix asap.

**Comment by nicmohr25** [comment]
Hello @EmersonFJ @jerperdue i'm not 100% sure but i just scrolled past your bug report. Seems like you're facing a similar problem like i did a few days ago. 
I'm not 100% sure but you could check out this ticket i created: #1440
https://github.com/FlutterFlow/flutterflow-issues/issues/1440

Cheers

**Comment by EmersonFJ** [comment]
Thank you for flagging this; I believe this is a different issue related to the way AppState is working with ListViews; we specifically DO NOT want to have the API be re-called; that would be terrible as it would cause a re-scrolling of the infinite scroll ListView; We are NOT worried about changing the backend at all; we are changing AppState and the AppState based variables are not being updated in the component within the ListView; we are refreshing AppState and it is just not refreshing - you can see this in the example project; thank you!Sent from my iPhoneOn Sep 26, 2023, at 12:53, nicmohr25 ***@***.***> wrote:﻿
Hello @EmersonFJ @jerperdue i'm not 100% sure but i just scrolled past your bug report. Seems like you're facing a similar problem like i did a few days ago.
I'm not 100% sure but you could check out this ticket i created: #1440
#1440
Cheers

**Comment by nicmohr25** [comment]
I think it's similar. In my case, i was receiving the Value from a Backend but i don't think this part matters. What matters is the fact that the ListView is not registering your change because for the ListView your Component has not changed. 
The Unique Key is preventing that. What I did to solve this issue is to integrate the value which can change into my unique key. 
Flutterflow builds the Unique Key by default like this: key: Key('Keyftn_${apiPostsIndex}_of_${apiPosts.length}')
What I did was to integrate the value that is critically into the unique key: Keyftn_${apiPostsIndex}_of_${apiPosts.length}_${your_critical_value}'.
With that, the ListView was able to register the change and rebuild the ListItem. 
I don't think that it necessarily refreshes the API Request, but thats something you might need to check. This was just something I needed in my case. 

Cheers

**Comment by EmersonFJ** [comment]
Ok - thank you for taking the time to explain that all; I am going to try this this evening and will circle back to this group; if this is the issue, I will confirm if it is the fix; I will make changes in the public example app link as well so we can all review, whether it works or not; thank you again Sent from my iPhoneOn Sep 26, 2023, at 13:23, nicmohr25 ***@***.***> wrote:﻿
I think it's similar. In my case, i was receiving the Value from a Backend but i don't think this part matters. What matters is the fact that the ListView is not registering your change because for the ListView your Component has not changed.
The Unique Key is preventing that. What I did to solve this issue is to integrate the value which can change into my unique key.
Flutterflow builds the Unique Key by default like this: key: Key('Keyftn_${apiPostsIndex}of${apiPosts.length}')
What I did was to integrate the value that is critically into the unique key: Keyftn_${apiPostsIndex}of${apiPosts.length}_${your_critical_value}'.
With that, the ListView was able to register the change and rebuild the ListItem.
I don't think that it necessarily refreshes the API Request, but thats something you might need to check. This was just something I needed in my case.
Cheers

**Comment by EmersonFJ** [comment]
Ok everyone - I think this is working; check out the link to the public test project... what I did here was add a random string to the end of the unique key. I will do a little bit more testing, but @jerperdue, can you also try this solution. If you confirm that it works for you, then I think we can close this out as the solution.

I will circle back as well but it will take a little bit due to other priorities atm outside of this workstream, but I will be layering it into a more complicated use case and will confirm back it works as expected there as well (so far, I think FF 4.0 changed things such that refreshing AppState does NOT recall an API in a Listview, which is absolutely the best thing you could have done for me, so thank you @agreaves !)

**Comment by EmersonFJ** [comment]
Ok - I believe this is the answer, and on my end, something related to FF 4.0 + this manual unique key was the solution. I think we can close this one out. thank you FF team!

**Comment by takashiff** [comment]
Hi folks, I apologize for the delayed response. This issue has been fixed, so I will be marking it as closed. Please feel free to follow up in this thread if the same issue persists. Thanks
