### ISSUE TITLE
iOS Codemagic deploy issue: Failed Step: Generate Launch Icon

### ISSUE THREAD

**Issue by Ken-JIAnomads** [FlutterFlow/flutterflow-issues#1519]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Just now, tried to deploy an iOS build (version 70 now) and received the following message for the first time.  This does not make sense as I'm not deploying to Android and is now blocking my release. Please help!

![Screenshot 2023-09-25 at 1 31 31 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/130031825/16497a98-c4e0-43a9-b57e-b9680d1000e0)

### Expected Behavior

Codemagic should deploy, build as expected (as per the past 69 builds)

### Steps to Reproduce

1. Mobile deployment
2. Deploy to App Store
![Screenshot 2023-09-25 at 1 37 49 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/130031825/76e0ccc6-fcf8-4125-ad23-312b43f3c9cc)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiMjfsIt1odxE176Jb+9VgmI4Ijs1U4E8m+5TYCs8GZT0B4kcYs+kfklUOd+5SlVtfGG0rGUX/Mr0kuGfVvYEZDacUYhe1ZZUWgHwczmieJ+YCa63b3NPHZ9hGG615LurrhQkAOxfdX8t11y2FdzKcCbYQZDsC1Q/QuaeXdeK2SrDX1iXc2URm05KZDPz

### Context

The bug is not with a widget, but with mobile deployment.  Nevertheless I generated a bug report code from the Landing widget.    I can't launch my iOS beta app to the App Store so this is critical!

### Visual documentation

![Screenshot 2023-09-25 at 1 37 49 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/130031825/758d4532-5ad5-4e94-a350-eec2edf2d01c)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform:Web, MacOS Desktop
- Browser name and version:Chrome Version 117.0.5938.92 (Official Build) (arm64)
- Operating system and version affected: (desktop): macOS Ventura 13.5.2
```

**Comment by youssefabouelneaj** [comment]
I am experiencing the same issue, IOS builds worked find until last night.

**Comment by nicmohr25** [comment]
I am facing the same issue.

**Comment by Jensoulus** [comment]
Same issue here

**Comment by martynbowis** [comment]
Same bug.

**Comment by UFOStudios** [comment]
I'm experiencing the same issue when downloading my code from Flutterflow.

**Comment by momineutec** [comment]
Facing same problem for my project well it was processing fine till last working day

**Comment by KeepTrackSolutions** [comment]
We get the same message for both Android and iOS deployment and have since Sunday evening. Sunday afternoon builds completed as normal.

**Comment by YukChenLee** [comment]
Same bug. For both iOS and Android deployment.

**Comment by devlocityapps** [comment]
Same issue starting last night after dozens of successful deployments. Tried removing the launch icon and choosing a different image, and that didn't work. Tried opening the project in xcode and android studio, that didn't help. Definitely seems like an issue with flutterflow mobile deployment or within codemagic.

**Comment by agreaves** [comment]
Hi @Ken-JIAnomads  thank you for the bug report! And apologies for this issue, it looks like the image package updated and broke the flutter_launcher_icons package. We've deployed a fix for this so this should no longer be occurring.

I'll be closing this shortly, but please let me know if you are still facing this issue.

**Comment by momineutec** [comment]
It Worked Alex. Thanks a lot for quick resolve

**Comment by Ken-JIAnomads** [comment]
Thanks Alex for getting it fixed so quickly!
