### ISSUE TITLE
Firestore Indexes not populating if only used in custom action

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#152]
## Expected behavior (required)
- Ability to use firestore composite indexes when only using that index in a custom action (and not present on a page within the app)

## Current behavior (required)
- When i create a custom action that uses a composite index in the custom action but not on a page within the app, the custom action fails
- upon investigation my firsestore.indexes.json is empty even if the index is in firestore

## To Reproduce (required)
- create a custom action that requires a composite index and do not have a query that uses that index on a page in the app
- run build, the build will fail, this is because that index does not exist in the firestore.indexes.json file (even if the index does exist in firestore)
- then add a blank page and set a backend query that has the same filter you are trying to use in the action
- this adds the index to the firestore.indexes.json file
- run build on action again, it works because it is present in the code
- issue is this requires you to have any composite indexes used in a custom action to be present somewhere on a page

### Bug Report Code
CUSTOM ACTION CODE
import 'dart:math' as math;

Future<DocumentReference?> setDailyLog(
  DocumentReference currentUserReference,
  DateTime inputDate,
) async {
  // Add your function code here!

  var dailyLog = await FirebaseFirestore.instance
      .collection("daily_log")
      .where('user', isEqualTo: currentUserReference)
      .where(
        'date',
        isGreaterThanOrEqualTo: DateTime(
          inputDate.year,
          inputDate.month,
          inputDate.day,
          00,
          00,
          00,
        ).toUtc(),
      )
      .where(
        'date',
        isLessThanOrEqualTo: DateTime(
          inputDate.year,
          inputDate.month,
          inputDate.day,
          23,
          59,
          59,
        ).toUtc(),
      )
      .get();

  return dailyLog.docs.first.reference;
}

## Context (required)
this requires you to create any composite indexes on a page in your app and you cannot use them just in a custom action

**Comment by aemelyanovff** [comment]
I'm afraid there's no way FlutterFlow can figure out that an index is needed based on custom action code. You'll have to create the index manually: when you run your project, it should print to console a Firebase link to create the index.
