### ISSUE TITLE
Excel lib save(download) not working on test mode

### ISSUE THREAD

**Issue by fernandoff** [FlutterFlow/flutterflow-issues#1524]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The option of saving(download) a new excel file is not working on test mode only when you publish your application on web or when you run it locally on chrome.

### Expected Behavior

Since the test mode is also a web application all the web functionalities should work too I think.

### Steps to Reproduce

1. Create custom function using sample from Excel lib documentation.
2. Create a button action to invoke the custom function.
3. On test mode the file is not sent for download.
4. On published website it does.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Skufl0ItOsbRa7arPbcdFmioRMjsla5Iriu1AEBMYIqnpOu0hXOmmTBNoQtekTFc2MVn8+Tozw+vGktzIN/A6Ok6cfaJl1pBUZTyXWXO6MMXREs+gPkRPJNpKCmLH0Z2jkwlBLftpLlYHw1OuPN6+ZD3tNOa3OW1MMM+jDKLXnXfuQ0SLb3kNh1JWeC/v

### Context

Trying to create a custom code for selling on the market and would be nice for users to have a feedback on the test mode.
Also the cause of this could affect other web functionalities not discovered yet.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3987627/d449a4d7-65e4-4cc2-b707-fcda07505589)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome Version, 116.0.5845.188 - 64 bits
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @fernandoff - Sorry for being delayed response on the issue. I hope you found the solution. Due to inactivity, I am closing the issue. Let us know if you still facing the problem. Thanks
