### ISSUE TITLE
Conditional alignment does not work

### ISSUE THREAD

**Issue by winthermich** [FlutterFlow/flutterflow-issues#1526]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The X and Y alignment properties of a container fails to render correctly if the values are being defined by a condition.

Example:
X alignment property is set to the following values depending on the screen size:
Small screen: 0
Medium screen: 0
Large screen: 1
Else: 1

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/006bc29b-8fae-43f6-bdd1-f7f5cf2ab569)

### Expected Behavior

I would expect that the conditional rules have the same impact as if had selected one of the 9 dots in the alignment matrix (which subsequently yields a value of -1, 0, or 1 in the X and Y properties.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/6db2a1e8-9a50-42f9-99d0-e28be1b4341c)

### Steps to Reproduce

1. Add a container to a page.
2. Include a text within the container (to make the issue more apparent).
3. Add a condition to the X-property of the container's alignment. The condition should have the following specification:

**Responsive value**
Small screen: 0
Medium screen: 0
Large screen: 1
Else: 1

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkMmAsJRNobVE+anQLcFFvCowGUALa+dI0tZ+TQ0jF5D4BIkqOffOSxJvXdyzaHxmemCgrHkE0cLUuOztCu0qIT+VQKZ+/85iVxPPbFKRb8mrPLi8XHJ7I9pYN0if1MHUuhV/BOpoSl4Q60OyH/OsYz6Cf9qOYwx5e6fDbOY=

### Context

The bug makes it difficult to create a responsive design.

### Visual documentation

As can be seen of the image, despite have a condition which states that the container should be centered (i.e. 0) if the screen is small or medium, the app fails to render the alignment correctly:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/ddaa46b7-1cac-4c93-9cdc-fa1c2229aa40)

### Environment

```markdown
- FlutterFlow version: v4.0 - 3.10.4
- Platform: All platforms.
- Browser name and version: Chrome Version 117.0.5938.92
- Operating system and version affected: Windows 10
```

**Comment by SameerShahzad99** [comment]
When set by the conditions, you'll need to test the implementation by running the app on test mode or run mode, please share a blank project URL if the problem gets reproduced, as the current project you shared is not blank with issue reproduced!

**Comment by wenkaifan0720** [comment]
Hi @winthermich. This is the intended behavior. Because the condition/value can be anything, right now we can't evaluate a variable value in the builder. You'll have to test the behavior in test/run mode.
