### ISSUE TITLE
iOS emulation error: Undefined symbols:

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#1528]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After updating to the latest iOS, I cannot launch my app on an iOS emulator. I get the following error:

![Bildschirmfoto 2023-09-26 um 08 19 09](https://github.com/FlutterFlow/flutterflow-issues/assets/106015154/cd47303c-2280-478b-95cd-c90dccd7d71d)

It runs on an Android emulator and I can deploy it via codemagic.

### Expected Behavior

The app starts on iOS emulator

### Steps to Reproduce

1. Download the Code from FF (I do it via GitHub)
2. run the app via an iOS Emulator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

FailsToCopyToClipboard

### Context

I want to run on an iOS Emulator

### Visual documentation

![Bildschirmfoto 2023-09-26 um 08 19 09](https://github.com/FlutterFlow/flutterflow-issues/assets/106015154/e3e015e7-8e96-46b1-98d3-7f91a4b0901b)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:iOS
- Browser name and version:Safari 16.6
- Operating system and version affected: Mac OS

Flutter doctor:
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by vipierozan99** [comment]
I've exported my project to github and if I clone it on a mac it builds succesfully, but I am getting the same error using flutterflow UI.
