### ISSUE TITLE
I have created a custom widget and want to fetch values after clicking on button, Page is not rebuilding on button.

### ISSUE THREAD

**Issue by shankhan2** [FlutterFlow/flutterflow-issues#1529]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a custom widget and created 2 app states as well. I am fetching the timer starting and ending time on the custom widget button in the Flutterflow text widget. The problem is, that when I click on the button of the custom code widget, it does not add values to the Flutter Flow app widget. But if I click on sides on the custom widget, it rebuilds the pages and adds values,

My problem is why it is not rebuilding the page on the custom widget button clicking.

### Expected Behavior

Null

### Steps to Reproduce

Null

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8slMrl389goctH176JcMZR/SoUNkw6RYI7l9VqEAwgF5CrB4l2e/TCYhJWTbyja1NEDWH8/TsJw/TKhuztBPlcAE2sGdR8wYdpQx7iIXimMYysPs2KbURfI9JPJhG60cCrvhFRCPZwd2wW2meXNueRFzPDQefGOW4zBcr+A5DDs2CHHh/3KiBs3TA4MHKaTI5ODEz25eKMrop5yfj/0w==

### Context

Null

### Visual documentation

Null

### Additional Info

Null

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:flutter-flow
- Browser name and version: Google Chrome
- Operating system and version affected: windows
```

**Comment by shankhan2** [comment]
![Screenshot (12)](https://github.com/FlutterFlow/flutterflow-issues/assets/144530389/e873a124-8eeb-4f55-9301-92212c0afe5a)

**Comment by hariprasadms** [comment]
Since the issue is considerably old and there has been no follow-up, we assume that it has been resolved in the latest FF updates. Thanks
