### ISSUE TITLE
Somali translation breaks forms and dropdowns

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#153]
## Expected behavior (required)
Select Somali from language option dropdown and everything work as intended.

## Current behavior (required)
Selecting Somali renders dropdowns inoperable and blanks out forms with a very (maybe infinite) grey square. This happens on web deployment, iOS and Android production. See it in action here http://ampower.app/ - select somali in settings and try selecting another language. Go to Contact and observe grey box.

## To Reproduce (required)
1. Add Somali as translation language
2. Add language switcher dropdown widget

## Context (required)
Have somali speaking people be able to use my app.

## Screenshots / recordings
![in Test mode](https://user-images.githubusercontent.com/114226492/203512459-156e36f9-a348-4668-8665-7902c195adf0.png)

## Your environment
* Version of FlutterFlow used: v3
* Platform (e.g. Web, MacOS Desktop): Web, MacOS Desktop
* Browser name and version: Safari 16.1 (17614.2.9.1.13, 17614
* Operating system and version (desktop or mobile): MacOS 12.6.2 (21G312)

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. Unfortunately, it turns out that Somali localization is not supported by Flutter, so there's nothing we can do about it at this moment. We'll remove Somali from the list of available languages.
