### ISSUE TITLE
Can't create 1:1 chat

### ISSUE THREAD

**Issue by Kum0-Iwazaru** [FlutterFlow/flutterflow-issues#1531]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Firstly, I created a FF Community thread, that contains all informations you can found below : [https://community.flutterflow.io/database-and-apis/post/can-t-create-1-1-chat-jbHM97CRvHx1bQq](url)

I am trying to create a 1:1 group chat. So I created a page called **CreateGroupChatPage** to create chat, and **ChatPage** to receive/send messages.
On this page, I'm able to select users (checkbox list), and trigger a button to create group.

### The problem is, I can create multiple users group chat, but not "private" group chat...

The actions flow of this button is the following : 
1. Check that **checkedList** is not empty _(if empty: display message)_
2. Check number of items checked of **checkedList** (call it **numChecked**)
3. Conditional action :
 3.1 If **numChecked not equal** to 1 : Create multiple user group chat, send Push Notification and navigate to **ChatPage**
 3.2 If **numChecked equal** to 1 : Create single user group chat, send Push Notification and navigate to **ChatPage**

Here is a screenshot of the action flow :
![Screenshot 2023-09-26 at 13 58 32](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/e0620ef8-dff3-4f04-8b00-f21f216147ec)

Here is the two create group actions :
![Screenshot 2023-09-26 at 13 59 00](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/0b318528-5be1-461e-8c2c-994f9e61643f)
![Screenshot 2023-09-26 at 13 59 41](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/9d414ff3-0849-43a5-a0ba-8eab114d05b9)

But the problem is located at the creation of the chat group. In fact, the group is simply not created...
So I got a **null check operator** when trying to navigate to the ChatPage (or displaying it on a dialog).

Then I tried to dig in this bug :
On Android Studio, I'v got an error message, telling me the null check operator is raised by the **create_chat_page_widget.dart** at line 515. This is the content of this file :
![Screenshot 2023-09-26 at 14 06 47](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/9c8245b2-7e3a-48a1-9bf9-5096bc228c87)

We can clearly see that the target line refers to the **_model.groupChatSingle** created fews lines before (**line 499**).
At this point, we know that **_model.groupChatSingle?.reference.id** return null. So we can suppose that **createChat** function (**line 501**) return null value.

Command + Left Click on the function name to go at the function constructor (file: **lib/flutter_flow/chat/flutter_flow_chat_manager.dart**) : 
![Screenshot 2023-09-26 at 14 09 08](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/e55723c7-f2e3-463d-8c83-2a3452b3cfcc)

**And here, you can see the problem directly by looking the code...**
Line 208: `if (users.length < 3) { return null; }`
So, according to the source code, it is impossible to create a 1:1 chat...

**_Is this a bug ? If not, how should I create a 1:1 chat ?_**

I tried to replace this condition by : `if (users.length < 2) { return null; }`
And it's working.

**BUT** I am using FlutterFlow App Mobile Deployment, so I can't edit these files if I'm not local...

### Expected Behavior

The expected behavior is simply the creation of a 1:1 goup chat, like in the official FF tutorial.

### Steps to Reproduce

1. Create chat pages
2. Create ListView with a backend query that fetch users
3. Display only users with a display_name set
4. Create an action flow composed of a conditional action, checking if selected users count is equal to 1
5. If True, put action **Create Group Chat** on **Single Users** with reference of first checked item of the users list
6. If False, put action **Create Group Chat** on **Multiple Users** with checked items from users list

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfLl5ZBOtbxe18/9bsdF/AMxQUB+bZ0vlO1FGUodF5/kBKQLd+PuaXduX8+of2xYIlagml8Kwan6i+HDJPoCKTeqR49607VUFgGXfGWlaZPQCcy0VmtQJ+djfm6y0LeNkx1RItR1SVoY2E+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I cannot create private chat so I can't continue my application...

### Visual documentation

CreateGroupChatPage :
![Screenshot 2023-09-26 at 14 15 16](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/6ddda7f7-6960-4a63-a926-d0b83c0650a1)

Create Button action flow :
![Screenshot 2023-09-26 at 14 15 59](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/3cc30e52-2ec2-41cc-86df-62fe5f72fff1)

Create Single user chat :
![Screenshot 2023-09-26 at 14 16 30](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/9b985523-81db-4758-96fa-11764a26c0fa)

Action Alert dialog :
![Screenshot 2023-09-26 at 14 17 42](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/fc539c98-fe32-4fa6-aeca-b3b86be06633)

Dialog result :
![Screenshot_20230926-094043](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/b4b91270-b8f9-42bb-a133-f3de5150a017)

Flutter Version :
![Screenshot 2023-09-26 at 14 19 05](https://github.com/FlutterFlow/flutterflow-issues/assets/118829959/6a7a0e7a-e088-48ff-a45a-48f695a7e056)

### Environment

```markdown
- FlutterFlow version: v4.0 -- Flutter 3.10.4
- Platform: MacOS MacBook Pro M2 Ventura 13.2.1
- Browser name and version: Google Chrome 116.0.5845.187
- Operating system and version affected: Samsung Galaxy Android v10 SM G960F
```

**Comment by hariprasadms** [comment]
Hi @Kum0-Iwazaru - We appreciate you bringing this up.  Debugging the issue is difficult because the project bug report code you given above is not from a blank project. Given the nature of the issue, I would advise you to contact the FF technical support team to get technical support in order to achieve what you are expecting around the use case. You can come here to submit a bug report if the technical support team decides that this is a bug. Thanks
