### ISSUE TITLE
Dismiss Dialog Problem

### ISSUE THREAD

**Issue by cmregazzo** [FlutterFlow/flutterflow-issues#1533]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created an Action, on the button I have in my Drawer, which when clicking on the button, the Drawer is closed via "Close Drawer", then I display an Alert Dialog via "Custom Dialog", then I execute it in a 3000ms Delay via "Wait (Delay)" and finally I try to close the Alert Dialog via "Dismiss Dialog".

When executing Dismiss Dialog, it does not close the Custom Dialog, and the following message is displayed in the browser console:

"Uncaught (in promise) Error: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable."

### Expected Behavior

When executing the Dismiss Dialog, the Alert Dialog that is open on the screen should be closed.

### Steps to Reproduce

1. Insert a Drawer into the project;

2. Place a button in this Drawer;

3. Create the following Actions on this button:

Action 1 - Close Dialog, Drawer

Action 2 - Alert Deialgo (Custom Dialog)

Action 3 - Wait (Delay) - 3000ms

Action 4 - Dismiss Dialog

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XiMjfsJZOsdtE+KrqacAw/SAWQkc7U5IRiu1uGBY1F4jzE4ocP/fUT3BZOMu6dFZUP2GJmm0epqmKvc7DEMcnEByJbJhz1rt+Tg3gIU+5WpCUDqm/dXBAP8pMI3KmzpuZ3BJ7PbJ2LS1l3FOme+SWSi/cQYTTOlYjQvylMtzM+XDnAQ3eGX0Jg1ZSfCvr

### Context

This issue is affecting the functionality of my Application.

I'm trying to close the Dialog Alert.

### Visual documentation

I made a video demonstrating the problem and made it available on DropBox:

https://www.dropbox.com/scl/fi/x24satzl3l0pzw1vj28tf/ErrorDismissDialog.mp4?rlkey=a0tqknqkh8jvphkqievf59yqp&dl=0

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Android, Web
- Browser name and version: Edge 117.0.2045.41  
- Operating system and version affected: Microsoft Windows 11 22H2 - 22621.2283
```

**Comment by cmregazzo** [comment]
Good morning,

An issue cannot be closed as it has not yet been proven by the FlutteFlow team.

Thanks.

**Comment by cmregazzo** [comment]
Good afternoon, how are you?

The problem mentioned in the issue is occurring in other situations, such as closing dialogs and displaying Snacbars.

Could you please pay attention to my request?

Thanks.

**Comment by jerperdue** [comment]
@cmregazzo I'm having a similar issue with bottom sheets and custom dialog. 

Steps to repro:
1. Create a custom dialog or bottom sheet
2. Set non-dismissable = false
![Screenshot 2023-11-01 at 1 44 06 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/91f0e251-b8c7-44d2-b6a8-15badcebdd70)

Expected:
User clicks outside the dialog box, the box should dismiss

Actual: 
Dialog is not dismissed

**Comment by takashiff** [comment]
Hello, @cmregazzo, I am going to mark this as resolved for now, as it looks like @TheDescar has found a solution. Thank you for your bug report, and if this issue still persists, please feel free to follow up in this thread.
