### ISSUE TITLE
Several languages not translating

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#154]
## Expected behavior (required)
Languages added be translated. 

## Current behavior (required)
Language fields are blank after running translation action

## To Reproduce (required)
1. Add languages (see screenshots below for particulars)
2. Run translate

## Context (required)
Have language translations for my app work as intended. 

## Screenshots / recordings
![Screenshot 2022-11-18 at 11 58 10](https://user-images.githubusercontent.com/114226492/203513928-dbce63b4-97ca-4311-8d09-054b858699b7.png)
![Screenshot 2022-11-18 at 11 58 27](https://user-images.githubusercontent.com/114226492/203513936-044af92b-9952-4d06-bc71-846ba2ebd28d.png)
![Screenshot 2022-11-18 at 11 58 43](https://user-images.githubusercontent.com/114226492/203513940-b2e688fe-9b5b-44bf-baf9-8117432cae60.png)
![Screenshot 2022-11-18 at 11 58 56](https://user-images.githubusercontent.com/114226492/203513946-ea605202-8118-44ad-bfb8-5de6961f0e88.png)
![Screenshot 2022-11-18 at 11 56 22](https://user-images.githubusercontent.com/114226492/203513952-7ef291c1-cefa-4313-b463-a67483593775.png)
![Screenshot 2022-11-18 at 11 57 50](https://user-images.githubusercontent.com/114226492/203513955-5324b581-93e1-444c-a990-6878e3b2005c.png)

## Your environment
* Version of FlutterFlow used: v3
* Platform (e.g. Web, MacOS Desktop): Web, MacOS Desktop
* Browser name and version: Safari 16.1 (17614.2.9.1.13, 17614
* Operating system and version (desktop or mobile): MacOS 12.6.2 (21G312)

**Comment by agreaves** [comment]
Hi @ampapplarsen! There are several languages that are not supported by the Google Translate API. So if you add any of these (including the ones you've listed), when you click the "Translate All" button FlutterFlow warns you about the languages that are not supported.

I'm going to close this issue for now as WAI, but please let me know if there are any other inconsistencies or unexpected behavior!
