### ISSUE TITLE
Enabling NavBar crashes the application.

### ISSUE THREAD

**Issue by smalpani-git** [FlutterFlow/flutterflow-issues#1541]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Application fails to load with error "Unexpected null value"

This happens after enabling NavBar in the project and adding it to the page where the app ends up after logging in. Note, I use a different page than the "HomePage" for user land up.  I have also enabled the NavBar in several pages of the project. 

Everything was working fine until the NavBar was enabled.

### Expected Behavior

App should just run.

### Steps to Reproduce

1. Use the project spiel-plan-2gqxrk  , NavBar branch
2.  Try to run the app. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcj15ZNOtbxH1rr+bO9Whj4WKWI2aK00sNobbxAjIoDoPJkUafSldhNVXciqYWxfKEWLoFkC+Nb4ifGTUPU7HxSqbN1B/rV6aQndTkG/aoSoDM2rdXQkI8pPfki+0MK7hR5+HPpfWUZi112EFuyWdB/BNoP4Zwh9f6PHaOI=

### Context

Add a NavBar to my app.

### Visual documentation

<img width="1728" alt="Screenshot 2023-09-27 at 16 28 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/123644544/a6ce475a-48f2-4166-ba93-dd4ba444a1db">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Test
- Browser name and version: Google Chrome Version 117.0.5938.92 (Official Build) (arm64)
- Operating system and version affected: MacOS Version 12.5
```

**Comment by smalpani-git** [comment]
I can update that this crash occurs only with the floating navigation bar, and switching to google navigation bar resolves the issue.

**Comment by hariprasadms** [comment]
Hi @smalpani-git - Thanks for submitting the issue. I looked at your project and can see no errors while running with the same configurations. Is this issue still persisting ?  if yes, setup a blank project with issue steps and share the bug report code. Once you have updated issue with these details, we can investigate the issue. Thanks
