### ISSUE TITLE
Data not retrieves from DB

### ISSUE THREAD

**Issue by ahmedelnaqa** [FlutterFlow/flutterflow-issues#1542]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I follow all the steps to retrieve data from Firebase.
structure:
- simple form includes a column inside it a listview with text inside it.
- the list view is connected by a **Query Collection** and the text shows it's connected to DB by retries in the screen and DB icon in the items tree.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72502706/68c99be1-fe11-41e9-ba21-a518e23e17db)
- Then convert the text value to read from the listview collection and specify the field name. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72502706/bb2dc3a0-5f6d-4909-b782-c3344382b8c5)
- when I preview the screen no data is shown.
Note:
- I tried the Firestore data manager and I see all the data from the database this means the connection is ok.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72502706/e36da75e-ebf8-45c0-bc30-63097f3faa56)

- The collection called" Hotels" includes just one field called " HotelName" that's all !! 

what is this problem?

### Expected Behavior

the data shown is based on the Firestore data manager 

### Steps to Reproduce

try to connect to DB and show data in text

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfHqw811ruZE7qqNKcZR/WY6KUQ1U50Wscp/bxIgGIDzPOw+ZPXsRBJpYN+7TVFLMUSmmlodw6mOkYb1G+w3GyyYfrpi/pZuZQzMcF+gUZOBEc3sOUdQAe9bGHalyJ6vkxNSXbNvc0If12GuC9iuaHLDGOPwImdISq/LZO4=

### Context

I can't complete 

### Visual documentation

provided in the question

### Environment

```markdown
- FlutterFlow version: 4
- Platform:win10
- Browser name and version: Brave
- Operating system and version affected: 10
```

**Comment by SameerShahzad99** [comment]
This looks like a project-specific problem, the latest firestore rules are not deployed, please try after deploying the latest rules, if you still face any problems, reach out to the support team for the project-specific issues through live chat or email(support@flutterflow.io)
