### ISSUE TITLE
Hero animations have a yellow underline on text (apparently a scaffold is needed)

### ISSUE THREAD

**Issue by dobleuxyz** [FlutterFlow/flutterflow-issues#1546]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting up hero animations for components that have text on it, it works but when the component is flying from one page to another, it adds a yellow underline to text. After some quick research, apparently, a scaffold needs to wrap the component in order to prevent this issue from happening. This is even present on the example that flutterflow shows on its Hero Animations documentation.

### Expected Behavior

Text should not have yellow underlines.

### Steps to Reproduce

Create a component with text.
Set it on 2 different pages.
Activate hero animation for component on both pages.
Test or run app. You will se yellow underline on text while its flying. It will disappear when it lands.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://www.loom.com/share/cf8980ca68074fd0a24ce2fbef3e0a11?sid=edf26f30-7320-4c5f-bc3a-c3e2607ebb66

### Context

I am trying to achieve a clean animation but this issue is making it impossible. It flies perfectly but the yellow underline ruins it.

### Visual documentation

![Screenshot_20230928-010849](https://github.com/FlutterFlow/flutterflow-issues/assets/19288406/b375403e-3216-4e30-8e0d-dfc60e1f6dbf)

this is how it looks. This is also present on flutterflow documentation samples: https://www.loom.com/share/cf8980ca68074fd0a24ce2fbef3e0a11?sid=edf26f30-7320-4c5f-bc3a-c3e2607ebb66

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Android, Test and run on web.
- Browser name and version: Chrome
- Operating system and version affected: Android but I think it happens everywhere.
```

**Comment by SameerShahzad99** [comment]
@dobleuxyz Can you please share a blank project URL with the issue reproduced?

**Comment by dobleuxyz** [comment]
Sure, hope this helps: https://app.flutterflow.io/project/hero-animation-issue-6heg03

Because the underline is a bright yellow, it may not be that obvious on every interface, specially white ones, so I added a black background.

**Comment by sbis04** [comment]
Hey @dobleuxyz, this should be fixed in the next deploy!

**Comment by dobleuxyz** [comment]
Great. will be on the lookout for it! Thanks!
