### ISSUE TITLE
Local Build for IOS: intl 0.18.0, version solving failed.

### ISSUE THREAD

**Issue by Optionaled** [FlutterFlow/flutterflow-issues#1547]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Without any local code changes, when running "pub get" locally through VS Code, I get the following error:
------------------------------------------------------------------------------------------------------------
[aitoolkit] flutter pub get --no-example
Resolving dependencies...
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because implementing_a_i depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required.
So, because implementing_a_i depends on intl 0.18.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.18.1
exit code 1
------------------------------------------------------------------------------------------------------------

This can be resolved through manually changing intl: 0.18.0 to intl: 0.18.1

### Expected Behavior

Project that builds on FlutterFlow should build without any local adjustments or changes,
Dependency resolve not producing errors.

### Steps to Reproduce

1. Push to GitHub.
2. git pull -- rebase
3. Run "flutter pub get"
4. Failure

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No_specific_widget

### Context

This affects local builds only. Have only tried building for iOS locally.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2619339/3709faf5-8493-4b84-ac9d-1abb1393d268)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS
- Browser name and version: N/A
- Operating system and version affected: macOS Ventura 13.5.2
- Flutter version: 
Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (9 days ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0
```

**Comment by Jensoulus** [comment]
I think you are on the wrong Flutter version. You are on 3.13.5. You should be on 3.10.4

**Comment by SameerShahzad99** [comment]
@Jensoulus is correct, you'll need to downgrade to a correct Flutter version (3.10.4) supported by FlutterFlow in order to resolve this problem!
