### ISSUE TITLE
After enabling Push Notifications bug on iOS Emulator: Cycle inside Runner; building could produce unreliable results.

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#1548]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After I enable push messages in FlutterFlow, I can't launch the app on the iOS emulator because the following error occurs (The Error is much longer but contains project specific information). I have this error in several projects.

Error:
Cycle inside Runner; building could produce unreliable results.

### Expected Behavior

App runs on iOS Emulator without Error

### Steps to Reproduce

1. Create Project
2. Enable push notification
3. Get code locally (Git or Code Download)
4. Try to run on iOS Emulator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failed to copy

### Context

I am trying to test the app locally on iOS and this is and that makes my development slower

### Visual documentation

![Bildschirmfoto 2023-09-28 um 12 19 20](https://github.com/FlutterFlow/flutterflow-issues/assets/106015154/8951df30-0967-4eba-8066-b6cd76a08f33)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: MacOS
- Browser name and version:
- Operating system and version affected: iOS 17
```

**Comment by davidoort** [comment]
We're having the same issue on MacOS Sonoma and iOS 17 where a blank Flutter app runs flawlessly on the simulator but we get the same issue when running our FF app
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/21220927/6fc0f826-76fa-4b3b-b83d-b3bec2163e40)

**Comment by davidoort** [comment]
@agreaves is this something you guys have seen at some point? Would appreciate to get acknowledgement that this could be an issue on your side :)

**Comment by davidoort** [comment]
We've run into the same "Cycle inside Runner" for a couple of our FF apps now, so it's not something tied to a single project.

**Comment by Jensoulus** [comment]
@davidoort That's my observation as well. Do you have push notification activated in all the projects you have this problem with? Because I only have this issue with these projects.
Maybe we can make it easier for the FlutterFlow Team if we narrow down the problem.

**Comment by davidoort** [comment]
Yes, the two projects I've tested have push notifications enabled

**Comment by davidoort** [comment]
We're still having this issue, please don't close

**Comment by rolf-schurink** [comment]
We are experiencing the same issue. Please don't close it.

**Comment by sbis04** [comment]
Hey, can anyone of you please share a Bug Report Code from the project having this issue? We need that in order to securely access the project and look into the issue. In this case, you can generate it by right-clicking any widget inside the widget tree and copy the bug report code.

**Comment by davidoort** [comment]
The issue still persists, please don't close

**Comment by davidoort** [comment]
Hi @sbis04 we're still not able to test our app on the iOS simulator, wondering if you've dug further into this? 🙏

**Comment by hariprasadms** [comment]
We already got a issue for the same error. Hence I am marking this as duplicate with #1766. There is a solution found by a user. Please refer comment at #1766 . Thanks
