### ISSUE TITLE
Unable to call API

### ISSUE THREAD

**Issue by raomanohar** [FlutterFlow/flutterflow-issues#1549]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the API call section i am trying to call an API and the response errors to 404 however I can successfully call the api on postman without any issues

### Expected Behavior

A detailed explanation of the error would be appreciated

### Steps to Reproduce

call the api without any SSL certificate

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not a widget

### Context

cant connect to the datasource I want

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47004490/ebdd8ecd-b7e7-43a2-99f2-fbbdaeb5129b)

### Additional Info

none

### Environment

```markdown
- FlutterFlow version: latest
- Platform: mobile
- Browser name and version: chrome
- Operating system and version affected: windows
```

**Comment by mnimer** [comment]
I am running into the same problem testing an API. Looking in the debug console the url it is trying to call has the herokuapp url prefixed to my url (double url)

https://agile-ridge-02432.herokuapp.com/https://cloudcenorthamcentral.cloud.looker.com/api/4.0/login

**Comment by SameerShahzad99** [comment]
This looks like a project-specific problem, please reach out to the support team for this case through live chat, or email: support@flutterflow.io

**Comment by raomanohar** [comment]
> I am running into the same problem testing an API. Looking in the debug console the url it is trying to call has the herokuapp url prefixed to my url (double url)
> 
> https://agile-ridge-02432.herokuapp.com/https://cloudcenorthamcentral.cloud.looker.com/api/4.0/login

Apparently Flutterflow does not allow API which are not secure. Meaning the API which I was calling was not SSL Encrypted. I believe the two link is just a proxy. Please check if your API is secure. 

When you try to call your API on Postman please check if you are getting any warning as "Unable to verify your first certificate" if there are no warning I think Flutterflow shoe have no issues.

**Comment by tarekjradi** [comment]
On Advanced Group Settings, disable `Use Proxy for Test`
