### ISSUE TITLE
Error for default variable value for integer and double from text input

### ISSUE THREAD

**Issue by Tu12tle** [FlutterFlow/flutterflow-issues#155]
## Expected behavior 

User input if left blank should default to the default value set so that the document can be created. 

## Current behavior (required)
if the value is intended to be an integer or a double then an error is thrown when trying to use the default value. Works as expected if the user has entered a value.

## To Reproduce 
create form with submit button for user to add to firestore.
set data type as integer or double as the variable you wish to add. 
Set the default for the variable if null 
leave as blank and try to submit

throws error of format exception if integer and invalid double if double

## Context (required)
trying to have a comprehensive form for user to fill in as much detail as they want but not make all information required such as sold price which may not be applicable yet if item has not sold.

## Your environment
flutterflow v 3.3.4
mac os
google chrome Version 107.0.5304.110

**Comment by agreaves** [comment]
Thanks for catching this! We'll now make exceptions for when a default value is provided so that parsing doesn't automatically fail, so this will be fixed upon our next release! 🙂
