### ISSUE TITLE
Countdown Timer widget is not picking up the right Date Time from flutterflow

### ISSUE THREAD

**Issue by maalhammadi** [FlutterFlow/flutterflow-issues#1550]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The timer widget used as a countdown timer for my auction up, it's linked to firebase it's  picking up the end time DateTime from Firebase but somehow the timer is calculating the time wrongly.

### Expected Behavior

DateTime from Firebase is picked for the countdown timer to calculate the time correctly. presented in the timer widget.

### Steps to Reproduce

1-Create a new page
2- Add a timer widget
3- Query "Product" document from Firebase with contain DateTime data
4- Link the "endDate" DateTime to be used for the countdown timer
5- Run and the correct time remaining is picked

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi/Lq+Zd2seZE+aryLcdKlmAwFj8aaIJMjuxFGA4jfeLmPaQAPPfUaXdVXMiregpEDWf9mlkJpMGKiOPLDvECHzOWQIN607t6bj3yQn6nWoyOPqmaVEckHdJmCkCF0pms3R4mOtJeSmdk3XGPcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Accurate Countdown: The primary goal is to have the countdown timer accurately reflect the remaining time until the end of an auction. This accuracy is essential for maintaining user trust and ensuring the smooth operation of the auctions.

Seamless Integration: Ensure that the timer widget integrates seamlessly with Firebase, accurately fetching the end time DateTime and calculating the remaining time without errors.

Troubleshooting and Resolution: Identify the root cause of the miscalculation, whether it is due to time zone differences, format discrepancies, or other issues, and implement a solution to rectify it.

User Satisfaction: By resolving this issue, aim to enhance user satisfaction and trust in the app, fostering a more engaging and reliable platform for auctions.

Feature Completion: Once the timer issue is resolved, you can focus on refining other features of the app and implementing additional functionality, ultimately contributing to the app’s overall success.

Suggested Steps to Resolve:
Review Code: Check the logic used for calculating the remaining time. Ensure that there are no logical errors or miscalculations.

Time Zone Check: Verify if time zones are being handled correctly. Mismatched time zones between the server and the client can cause discrepancies.

Format Verification: Ensure that the DateTime format used in Firebase is consistent with the format expected by the Flutter app.

Logging: Implement extensive logging to trace the flow of data and calculations. This can help identify where the discrepancy is occurring.

Testing: Conduct thorough testing with various scenarios and edge cases to ensure that the issue is resolved and the countdown timer is accurate in all situations.

Community Assistance: If the issue persists, consider reaching out to Flutter and Firebase communities or forums for additional insights and assistance.

### Visual documentation

![Screenshot 2023-09-28 at 9 45 54 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/23508799/8290b845-3855-4919-9f52-b79bc0925488)

### Environment

```markdown
- FlutterFlow version: 4
- Platform: flutter 3.10.4
- Browser name and version: Chrome: Version 117.0.5938.88 (Official Build) (arm64)
- Operating system and version affected: macOS 13.5 (22G74)
```

**Comment by sbis04** [comment]
Hi @maalhammadi, sorry for the late reply. Can you explain a bit more in what way is the time wrong? (is it ahead/behind the actual remaining time it should show, or there's any other issue?)

**Comment by maalhammadi** [comment]
This is an auction app with a countdown timer for each auction.  countdown timer accurately reflects the remaining time until the end of an auction. The end of the auction is a DateTime format from the Firebase document. When the countdown timer is set from the DateTime picked up from Firebase, the timer is miscalculating the time and it's not matching the DateTime from Firebase.

**Comment by blinkinfo** [comment]
you can create a custom function that takes DateTime value from firebase and returns the countdown value in milliseconds (ms). and then you can call this custom function in Timer widget.

here is the snippet for custom code if you need it.

`// function that takes DateTime and returns coundown value in ms

int countdownms(DateTime timestamp) {

  int currentTime = DateTime.now().millisecondsSinceEpoch;
  int targetTime = timestamp.millisecondsSinceEpoch;
  int countdown = targetTime - currentTime;
  return countdown > 0 ? countdown : 0;

}`

hope this helps
<img width="321" alt="Screenshot 2023-12-17 at 9 23 23 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/53660007/7085d96e-846d-48d9-95c6-3c662a0aa7a0">

**Comment by takashiff** [comment]
Hello, thank you for your bug report. It looks like the above solution may have resolved your issue. As such, I will be marking this issue as closed. If the issue persists, please feel free to follow up in this thread. Thank you for your patience.
