### ISSUE TITLE
Algolia serialization convertAlgoliaParam > returning null when paramType == ParamType.DocumentReference

### ISSUE THREAD

**Issue by haydenrumble** [FlutterFlow/flutterflow-issues#1553]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The latest serialisation update (28/09/2023) convertAlgoliaParam is missing a Return control flow statement for the Switch Case: ParamType.DocumentReference. ref: lib/backend/algolia/serialization_util.dart  > convertAlgoliaParam > line 58

currently:

      switch (paramType) {
      ...
      case ParamType.DocumentReference:
        isList
            ? (data as Iterable).map((s) => toRef(s))
            : safeGet(() => toRef(data));
        break;

Without the return value, any Algolia property that is a Firestore document reference will serialise to null

### Expected Behavior

should be: 

      switch (paramType) {
      ...
      case ParamType.DocumentReference:
        return isList
            ? (data as Iterable).map((s) => toRef(s))
            : safeGet(() => toRef(data));
            
This returns the document reference as defined in Firestore / Algolia

### Steps to Reproduce

1. Create an Algolia index for any collection of Firestore documents that have a field that is a document references
2. In FlutterFlow, setup an Algolia Search to query that index
3. Add the Algolia Search action to a FF page
4. Do a search for anything that returns the documents containing a field that is a document reference.
5. In Brower dev tools, observer the response from Alogia contains the field with a document reference
6. In FlutterFlow observe that the document reference is always null
7. Put a breakpoint on the code at:  lib/backend/algolia/serialization_util.dart line 58 to see error firsthand

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

It's no longer possible to use Algolia Search in conjunction with Firestore documents that contain document references (i.e. use Algolia as a search tool to point to other Firestore documents).

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/19659949/14372f6d-8795-46c7-83a8-f8998960bffc

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Chrome, Android - it's not platform specific
- Browser name and version: Chrome, Android
- Operating system and version affected:
```

**Comment by YatinBajajOP** [comment]
I am facing the same issue.
I have mentioned this in the community here, https://community.flutterflow.io/integrations/post/algolia-search-returning-null-for-reference-fields-to-other-firebase-dpamirrDAj9SPBP

With the document reference fields the datetime object field also return a null value, you can check it here, https://github.com/FlutterFlow/flutterflow-issues/issues/1567

**Comment by hariprasadms** [comment]
Hi, I can reproduce the issue.  Here is a quick video showing collection and its fields configurations.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/0bc625dd-2bf7-47ea-b5d2-e89608449e50

**Comment by aemelyanovff** [comment]
Sorry for the delayed response. The issue has been fixed for some time. @haydenrumble please reopen the issue if it's still happening in your projects.
