### ISSUE TITLE
"Apply opposite statement" not copied with variable

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1554]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When copying a configured variable, the "Apply opposite statement" is not copied with it, so when pasting it often leads to mistakes.
Minor issue once you know how it works, but unexpected.

### Expected Behavior

"Apply opposite statement" is also copied when pressing copy variable.

### Steps to Reproduce

1. Configure a conditional visibility based on some boolean page state, and set "apply opposite statement"
2. Copy the variable
3. Paste the variable on another component
4. The apply opposite statement is reset to false

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0rNlud0wdCePkPYoId8zeTFFoSOqHfwhYPVaIoEwB/+DujoTTGPYqBEiWGr5gzqoMUxDjXj25MYyMDqmBdkRRO/JQGhSM1KeNmRNNNvh0WXAnwHGUId+ub3qCf9qOYwx5e6fDbOY=

### Context

Copy pasting variables.

### Visual documentation

<img width="325" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/7d59bdec-c8aa-4663-a3db-ede7d8676045">

### Environment

```markdown
- FlutterFlow version: 4.0 Sep 28
- Platform: Chrome
- Browser name and version: Chrome  116.0.5845.179
- Operating system and version affected:  Mac OS 13.5.2 (22G91)
```

**Comment by hariprasadms** [comment]
Hi @kium-one - Can you add blank project with issue steps details please. The above given project code, goes to real project  and there are more pages. Its a challenge to locate the issue. Please update the details.

**Comment by kium-one** [comment]
Sure thing:
ITESz/Hqx89goddc7s/fYcFqhR4jNlx7bZNEjexTcAIjCL2rO7YpWvnAXHpBUteqdG1ieFaZ+XMF//DqjYT1LvcnBAyHb6Y91s5ITAnzTXGVRLK7DarodnRDGdtWFX6MyrWFmglvOuxZS11pig/GSw==

It's pretty simple actually:
https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/1b0f33f5-b0bc-499c-95b2-4c4ac8e2b54b

**Comment by agreaves** [comment]
Great catch @kium-one! Sorry for the long wait on this one, this will be fixed next release :)
