### ISSUE TITLE
Error when consuming an API with DorpDown = expected a value of type 'list<int>', but got one of type 'list<object?>' 

### ISSUE THREAD

**Issue by f4cilsolucoes** [FlutterFlow/flutterflow-issues#1556]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am consuming an API that returns a LIST<int>, but when applying the list to the Define Options Value property, when executing the project it presents the following error: expected a value of type 'list<int>', but got one of type 'list<object?>' .

The Error was reported to support, who managed to reproduce it and I was advised to open this Issue.

### Expected Behavior

This error should not appear, since the API EndPoint returns a List<int> as expected. For some reason FlutterFlow is interpreting it as a List<Object>

### Steps to Reproduce

1. Create new Page
2. Add. DropDown
3.  Enter the Query backend: UsuarioPolo with the following parameters: idPessoa = 14686
Token = (Get the token from the Login endpoint with the parameters: login = giovani and  password = 1234)
4. Set the Dropdown parameters to:
    > Set Optios Labels = True
    > Define Optios Values ​​= idPolo
    > Define Optios Labels = fantasia

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skuX1x49OtbxD7qr+csB7/WMRJlt/aJ0kscp8cwEbfJjbPO0ievWkflBoQvXmT2NceUSmmnMC+NruhdnhM8JeAE6qbrZJ1ahQSQLxVmeRQZOBEcyoW39QROdQfmHF356ngSQnItFfcnMt2mCyf+qyQnPtJOfbImdISq/LZO4=

### Context

This functionality is ok, but in the last update it started showing this error

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/123669693/489fbd36-5cd7-4c2b-bb81-6e93d4226109)

### Environment

```markdown
- FlutterFlow version: v4.0 flutter 3.10.4
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected:  Windows 10
```

**Comment by hariprasadms** [comment]
Hello @f4cilsolucoes - Thanks for submitting the issue. 
Dev note - Issue is confirmed by support team.

**Comment by f4cilsolucoes** [comment]
Hello! Is there a timetable for this bug to be fixed?

**Comment by victoriahuang1** [comment]
Hi @f4cilsolucoes , thanks for the report. I have identified an issue on our end, which should be resolved upon the next deploy

**Comment by beepixl** [comment]
Hi I have id and name in API when I select the option value as integer it won’t allow me to show names in options labels.

**Comment by victoriahuang1** [comment]
Hi @beepixl can you open up a new Github issue with all of your information, so that we can investigate further?
The original issue was resolved, so you are likely experiencing a new issue.
