### ISSUE TITLE
Dynamic Component timer value (ms) integer passed as string not as integer

### ISSUE THREAD

**Issue by Jakesf1** [FlutterFlow/flutterflow-issues#1557]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With the new update on Friday 29 Sept 23, if you now try to access, in my case a timer time (ms), from a dynamic component the integer value (as stated on screen) is passed back as a string to the condition and options for great than etc are gone and only equal to or not equal to. The boolean is set depending on the condition and in my case passed to a custom dialog. The upgrade from Thursday to Friday, where I have one action in another part of the app that work fine and try to replicate that function one cannot. 

First - 
<img width="518" alt="Screenshot 2023-09-29 at 09 07 28" src="https://github.com/FlutterFlow/flutterflow-issues/assets/31532938/01e11c8b-4939-4ebe-ae1e-6c0a24e502ee">

Second - card timer 
<img width="504" alt="Screenshot 2023-09-29 at 09 07 51" src="https://github.com/FlutterFlow/flutterflow-issues/assets/31532938/033e8d4b-13b7-4e3e-abcd-a99c7591d5f8">

This behavior is on both the mac app as well as web version using chrome.

### Expected Behavior

if the value is stated as an integer it should pass back the selected value as integer to the condition.

Example of working function before the upgrade;

<img width="954" alt="Screenshot 2023-09-29 at 09 02 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/31532938/23e50729-7ac0-4fdc-9946-29e0a202a503">

### Steps to Reproduce

1. Create a component (Timer) with a Timer widget counting down
2. Create a component (card) and add the timer component as a dynamic to the card component
3. Add an action to a button and call the card component as a custom dialog.
4. Call custom dialog and pass a boolean parameter to the dialog based on timer value (ms) and access type: Value for key

Result is the value is an integer but passed to condition as a string after the update on Friday 29th 2023.

<img width="910" alt="Screenshot 2023-09-30 at 08 44 58" src="https://github.com/FlutterFlow/flutterflow-issues/assets/31532938/9f19364c-22a6-43c6-bd0a-a9bbe26cc9e7">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89goctH176JdMdohmQ4KW0cTeU30+thcw4bI+P2P7N/Y8zBdlFtSOqHf243PmL/oGIJ+db8i9nMUMY7OSWub6Z/1blpUxDiQXGXVrnRC6mwen98TMFNCFy/57uzkBZ7KrBfLWwj2mGEOeyAb3qCf9qOYwx5e6fDbOY=

### Context

We had to get a demo out to client and could not in time. We ended up using a code expression to pass the correct boolean value.

### Visual documentation

As per the above images

### Additional Info

as per the above images

### Environment

```markdown
- FlutterFlow version: 4.02
- Platform: mac / web
- Browser name and version: chrome Version 117.0.5938.132 (Official Build) (x86_64)
- Operating system and version affected: NA
```

**Comment by agreaves** [comment]
Hi @Jakesf1, apologies for completely missing this issue. It looks like this happened because "Number Format" was set by default when you selected the `Timer Time` variable. This meant it's formatted as a string. In the screenshot you added under "Available Options" it's auto-selected to "Number Format". You can instead change that to "No Further Changes" in order to get the integer value out of it.

Apologies for the confusion, I know that may not be the intuitive use case. And again apologies on the delay getting to this issue.
