### ISSUE TITLE
Teams version - duplicated users on list when assigning comment 

### ISSUE THREAD

**Issue by Tomaicomm** [FlutterFlow/flutterflow-issues#1559]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When assigning comment to teammate I get duplicates on the list of users.
<img width="287" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128980409/434edd28-c130-4b0d-a93d-0b8f3c3594f3">

### Expected Behavior

1 teammate = 1 position on the list

### Steps to Reproduce

1. select component
2. select "add comment"
3. Insert comment
4. Click "@" to assign a teammate
5. You'll get duplicated names on the list

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not applicable

### Context

I want to assign comment to a teammate

### Visual documentation

<img width="287" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128980409/e7612ce5-0eaa-44bc-bd69-f36381e1aa61">

https://github.com/FlutterFlow/flutterflow-issues/assets/128980409/fe5a2ebd-0bcd-4592-a45f-0693d3398de5

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:MacOS
- Browser name and version: latest Microsoft Edge
- Operating system and version affected: macOS Sonoma 14
```

**Comment by hariprasadms** [comment]
Hi @Tomaicomm - Thanks for submitting the issue. Please update project bug report code so that I can get access to your project to investigate the issue. 

Usually this happens when user is there in both the places, in project collaborator list and also in team list. Remove it from one place and see if there any differences. Please update.

**Comment by Tomaicomm** [comment]
@hariprasadms you are right, I removed user from the collaboration and now I see just single entry - so all is good.
Thank you for indicating this, though its bit confusing.
