### ISSUE TITLE
Button with Icon alignment

### ISSUE THREAD

**Issue by janmestek** [FlutterFlow/flutterflow-issues#156]
## Expected behavior (required)
Button widget should centre the icon when no padding is set. It works in the editor.

## Current behavior (required)
Button widget doesn't align icon correctly in the test mode. 

## To Reproduce (required)

1. Create new page
2. Add button widget
3. Set icon
4. Click Run
5. Observe that Icon is not aligned properly 

### Bug Report Code
IT4kiMjfsI52ocMA+KrTbe5GqGQvNUB8TLJEoetxc0gbfe/4EOwhPvfCbk5VOdSzaH5+JEyJhXIJpqnmhYXhKfEqKQWBQb5h+KtUaVyjEA8=

## Context (required)

I need a button where user can choose a type of collection. This button should be selected and change fill color to grey for indicating selection. This logic is working through local state but since the icon alignment is very ugly, it affects the user experience. 

I have tried using other widgets such us icon within container or icon button, but for some reason, the fill color through local state variable doesn't work even though its set up exactly as the button widget with icon.

## Screenshots / recordings
Editor:
<img width="367" alt="Screenshot 2022-11-23 at 12 55 31" src="https://user-images.githubusercontent.com/118629165/203564192-2bb3ca1e-be9c-4a3b-8782-4d4575af5258.png">
Test:
<img width="385" alt="Screenshot 2022-11-23 at 12 59 04" src="https://user-images.githubusercontent.com/118629165/203564262-54e71c24-f716-4cf4-85b8-83b8b256d83e.png">

**Comment by davhad** [comment]
![Screenshot 2022-12-20 at 18 48 32](https://user-images.githubusercontent.com/72607/208732706-2e97dde4-3eb5-41f2-a009-8decd2af8401.png)
Same here. Tried changing border-size, icon-padding, button-padding. None of these workarounds work.

**Comment by wenkaifan0720** [comment]
Hi @janmestek @davhad . Are you still experiencing this issue?

The issue with the icon button could be related to this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/431. I have pushed a fix for that.

**Comment by wenkaifan0720** [comment]
The Material button design will not center the leading icon because the text is always expected. Since we have fixed the bug for icon button, you can use the icon button now for the desired UI effect.
