### ISSUE TITLE
APK Build Failed (The following dependencies "Location" do not satisfy the required version!)

### ISSUE THREAD

**Issue by albluwi1987** [FlutterFlow/flutterflow-issues#1561]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,
I'm following FF Enable RevenueCat in Google Play Store steps [here](https://docs.flutterflow.io/settings-and-integrations/in-app-purchases-and-subscriptions/revenuecat)
and one of those steps is :
4. Click Download APK in the navigation bar and wait until your project is built.
But when I try to download the APK i my projects an Error message appears 
<img width="775" alt="‏لقطة الشاشة ١٤٤٥-٠٣-١٥ في ٥ ٢٢ ٠٢ م" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/1f5e2086-cd00-4f74-9314-0a3cea819884">

### Expected Behavior

Download the APK without any errors

### Steps to Reproduce

I'm not sure if it can be reproduced or not but I'm using location permissions so
1- create a new project
2- enable location permissions
3- try to download apk

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflfLl8ZNOm99Y15SJacZagioUJmUcTIMziNZ+exUbfaL1Bu0LP/f7SFNDXdPnaVNcO039ml0f06CLv9/tGPIVEE+aGdVxypF6FAvee2iuMJSoCqmOR2h8ROFUGB2xy6anvCUnKtdpSVVl7Fy2AeSRYD/DFOu/Zwh9f6PHaOI=

### Context

Major Effect
I've already published my app to apple store , and I can't continue google play store deployment

### Visual documentation

<img width="775" alt="‏لقطة الشاشة ١٤٤٥-٠٣-١٥ في ٥ ٢٢ ٠٢ م" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/3c0674af-a6c7-454e-b7fc-baa4d29e1bd9">

### Environment

```markdown
- FlutterFlow version: v4.0 (released september 28, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 117.0.5938.132
- Operating system and version affected: macOS Ventura 13.6
```

**Comment by SameerShahzad99** [comment]
@albluwi1987 I tried reproducing the issue with the steps mentioned but I was unable to reproduce this issue, also the project that you have attached does not seem to be a blank project with the issue reproduced, This looks like a project-specific problem, so reach out to the support team through live chat or email at support@flutterflow.io so they could guide you further regarding your project!
