### ISSUE TITLE
Youtube Player setting menus don't scroll down (iOS and Android)

### ISSUE THREAD

**Issue by mlafuentem** [FlutterFlow/flutterflow-issues#1563]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On real Android devices, when you open a certain settings menu on the YouTube Player, you can't scroll it down. For example, if you select 'auto-translation', you can't scroll down and select languages other than the ones given at the upper part of the list (from Afrikaans to Arabic); or if you want to select a certain speed you can only select the speeds given at the upper part of the list... You can't scroll those menus down and select other options. I'm not sure if this also affects iOS devices.

### Expected Behavior

The user should be able to scroll down those setting menus and select other options that should appear below.

### Steps to Reproduce

1. Create a new page and insert a YouTube player widget.
2. Give the Youtube Player a certain URL, like https://www.youtube.com/watch?v=MVYrJJNdrEg
3. Export the code and run it on a real Android device.
4. Play the Youtube Player widget: Press 'settings' icon: press 'subtitles CC/English', press 'Auto-translation', you can't scroll down this menu. This happens with any settings menu that should be scrollable: it's not scrollable (e.g., playback speed menu, subtitles CC options menu).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wk8nlsM9NobRF7arPbflvoGA5JlA/a7g7kcN+Qg83B5OvB7YPWPrBPxNoQtO7dG1MOlqWpGcz+KHUk/DEG8ECCw+CQ4NeyalUegzMRj+5RK7SEqmedEYkJ51UG3ak1J2gmA9TKbZYSU5l7zqAGPPKbBTAHozwC1gjAMj9WbnDnXSJHSLvEjhVxmNecCfn

### Context

My Android users can't use the auto-translation option to select their language and watch the Youtube videos with subtitles in their own language. It's vital for my project that users can watch those videos and set the subtitles in their own language if they need to.

### Visual documentation

![Screenshot_2023-10-01-02-56-10-661_flutterflow emotional fitness app](https://github.com/FlutterFlow/flutterflow-issues/assets/60664735/7bc74676-569b-4754-8bb5-c6d41d224090)
![Screenshot_2023-10-01-02-55-48-188_flutterflow emotional fitness app](https://github.com/FlutterFlow/flutterflow-issues/assets/60664735/9880a096-b3b3-425b-b531-a034c13b4f18)
![Screenshot_2023-10-01-02-57-00-357_flutterflow emotional fitness app](https://github.com/FlutterFlow/flutterflow-issues/assets/60664735/f4fb2f44-45b8-4298-837a-b074c80f8ace)

### Environment

```markdown
- FlutterFlow version: v4.0 Flutter 3.10.4 (released on the 28th of September)
- Platform: Android
- Browser name and version: Chrome 117.0.5938.132 (Build official) (64 bits)
- Operating system and version affected: Android 11 RKQ1.200826.002
- Compiler: Android Studio Giraffe | 2022.3.1 Patch 2
- Android device: Xiaomi Redmi 10 Pro
```

**Comment by hariprasadms** [comment]
Hi @mlafuentem - Thanks for submitting the issue. I can reproduce it. 

Dev note - Below video is from android emulator showing the scrolling issue while selecting language.  
https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/4e3f2307-520b-4801-b09c-cebcd56903a6

**Comment by mlafuentem** [comment]
@hariprasadms Thanks! I have just seen exactly the same bug on iOS devices. Do I need to open another bug report, or will you fix the bug in both environments?

**Comment by joshua-ffio** [comment]
Hi @mlafuentem, thank you for reporting this issue! This ticket serves enough for both platforms, but thank you for letting me know it was reproducible on iOS as well. I will take a look into it today.

**Comment by sbis04** [comment]
Hey @mlafuentem, sorry for getting back to this after so long. This should be partially fixed in the recent update this week! However, I found it might still exist in full-screen mode for certain cases which should be fixed in the next FlutterFlow update!
