### ISSUE TITLE
The audio player functions correctly in the simulator but doesn't work when tested on an iPhone device.

### ISSUE THREAD

**Issue by superkeven2020** [FlutterFlow/flutterflow-issues#1564]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a custom action that can connect to Azure TTS and play the audio by just_audio package.
I have tested the code work perfectly in flutterflow simulator,but doesn't work when tested on an iPhone device.

I think the issue is that the permission setting is not working as expected.

Expectation in info.plist

	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
	</array>

### Expected Behavior

   The permission setting is shown below in the info.plist

    <key>UIBackgroundModes</key>
    <string>audio</string>

### Steps to Reproduce

1. set up permission as below
<img width="407" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/ac8b500b-3c59-4601-bbdf-428638067e6f">

2. Download the Plist
the plist doesn't set expected  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl+fl4otNxOFb14SJKsJommUvC2kcTL4zlO1HcxAYGO/yPbJ+ds/sbRZDUs+9dFNhHGGIoEYG7sLWvd7DE/AqBy+eGZxjzagJcDrjQXq8Rc2PBpO0WHx9I9NgN0ikyqar3CJSPuxtSlEj3zn7Hue+ZDPtCZO/Zwh9f6PHaOI=

### Context

Playing audio is a fundamental function of my app, and this functionality impacts all of my app's users.

### Visual documentation

<img width="466" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/c8aa4076-e921-4ee7-8a4a-07e920e79a8e">

inside Plist
<img width="532" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/e39447f8-204d-493a-b189-310ff94f6f43">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: MacOS web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by superkeven2020** [comment]
Someone has reported this issue in the ticket, but it hasn't been resolved yet.
https://github.com/FlutterFlow/flutterflow-issues/issues/1444

**Comment by SameerShahzad99** [comment]
@superkeven2020 As you can see from the reply from the technical team, this has been considered as a feature request, and hope to see this feature in the near future!

We also offer an [in-app tool](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#how-to-submit-bug-reports-and-feature-requests) where you can share your ideas for potential new features. Sharing your ideas here helps us prioritize the features that are most needed within the FlutterFlow community.
