### ISSUE TITLE
IPad IOS Flutter Flow Version out of Date Refresh Button not working

### ISSUE THREAD

**Issue by Ajris** [FlutterFlow/flutterflow-issues#1565]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a project that was refreshed on the webpage due to version mismatch. When I logged in on the iPad to try it out, the refresh button doesnt refresh anything (seems like it doesnt have any action assigned).
<img width="471" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10548910/e6a5852f-881f-4759-8391-c8dd93d526af">

### Expected Behavior

I expected it to refresh and that I will be able to access the project. Logging in and out didn’t help.

### Steps to Reproduce

Actually I do not know if it is possible to reproduce for any current project that doesnt experience version mismatch. But what I would suggest is:
1. Create a project running with some old version
2. Refresh on the webpage for the new version
3. Modify it
4. Open the iPad application
5. Try to access the project and refresh the page 
6. Refresh should succeed, but it doesnt do anything

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhcr1sIhPvuZE1rnQce1sgj4wGUwbUOc7j9VEGAsjCePnPLMqeePSSEpvSOqHf0FAOE6inkwdps7Qjt/pIPEoOQmcbJR//pZfUxDiRnmXMq6DPpGCWX9TL+VXC36j0rWruxImPbFfLF4uwF+HNdyAb3qCf9qOYwx5e6fDbOY=

### Context

I cannot work on my project on the ipad app. My project is completely not accessible by the application.

### Visual documentation

I have added it above. There seems to be no action assigned to the refresh button.

### Additional Info

Additionally:
I tried getting the bug report code on the google chrome on the iPad, however I wasn’t able due to the Platform Exception (…, null, null) being thrown (same happens even after requesting desktop site).

### Environment

```markdown
- FlutterFlow version: v3.10.4
- Platform: iPad application
- Browser name and version: (iPad Application)
- Operating system and version affected: iPadOS 16.6.1
```

**Comment by shishamchudal** [comment]
Same issue for me as well. 
IPadOS version: 17.0.2. 
FlutterFlow app version: 4.0.2.

**Comment by jhacking34** [comment]
Same issues as well

**Comment by Worktrainer-nl** [comment]
Same issue on multiple projects

**Comment by Xarjik** [comment]
Also faced with this issue, ipad app completely unusable as a result.

**Comment by sbis04** [comment]
The issue with the iPad app should be solved in the next update, which will probably be deployed sometime this week!

**Comment by Ajris** [comment]
@sbis04 Thank you for info. As soon as the new update is released, I will add a comment here confirming whether the fix works :) Can't wait!

**Comment by ToddHerron** [comment]
Same issue for me on only one project.

**Comment by ifallah** [comment]
Same issue on multiple projects From 16 days I have iPad because of flutter flow 
I have now the a new MacBook Air M2 15inch same issues same screen refresh but nothing happened using web version only so I can continue using 

kindly fix this issue ASAP

regards

**Comment by Rak4u** [comment]
Same issue. Can we know the next update please cuz I have had this problem for about a month now. Thanks

**Comment by dvdstrk** [comment]
New projects work fine, but can't open any existing ones.  It's like we're being punished for being current users.  ;-)

**Comment by dvdstrk** [comment]
This was marked completed, but the behavior persists.  The version in the App Store is still 4.0.2 and was updated three weeks ago

**Comment by ifallah** [comment]
As per today Saturday 14 October 2023 9:35 AM  the issues still remain Sent from my iPadOn 13 Oct 2023, at 10:08 PM, dvdstrk ***@***.***> wrote:﻿
This was marked completed, but the behavior persists.  The version in the App Store is still 4.0.2 and was updated three weeks ago

**Comment by vincekruger** [comment]
Please give an update on when we can expect the iPad release.

I was working on a project on my iPad and I haven't opened it on desktop at all, and now I cannot continue because of this issue. :(

**Comment by albluwi1987** [comment]
Same Issue

**Comment by Ajris** [comment]
Maybe the fix is implemented yet it is not released yet? @sbis04 it would be good to know the potential release date for the iPad app if you could share!

**Comment by bertke** [comment]
Same issue - can no longer use the iPad to work on a project

**Comment by jhacking34** [comment]
My iPad updated this morning with the new update and it fixed the issue.  Looks like the update hit the AppStore last night for me.

**Comment by sbis04** [comment]
Hey all! Really sorry for the delay in updating the iPad app, the **update (`v4.0.3`) should be live on the App Store now!** Hope it fixes a couple of issues that people were facing on the FlutterFlow iPad app. There are a few more minor iPad app fixes that are pending, those will probably be deployed sometime in the coming week!

**Comment by vincekruger** [comment]
Woohoo. All working again 😃

**Comment by ifallah** [comment]
Glad it worked!

**Comment by Xarjik** [comment]
> Also faced with this issue, ipad app completely unusable as a result.

Works after updating the app, thank you very much!! Yay!

**Comment by dvdstrk** [comment]
Hooray! Thank you! Now don’t touch anything. 😉  The iPad app is a joy to work on and I may or may not ever go back to the browser version.On Oct 15, 2023, at 11:42 AM, Saleh Ali ***@***.***> wrote:﻿
Glad it worked!



On Sun, Oct 15, 2023 at 7:38 PM Vince Kruger ***@***.***>

wrote:

**Comment by bertke** [comment]
Back in action, thank you!!!!

**Comment by Ajris** [comment]
Works like charm @sbis04 :) Thank you!

**Comment by ketupia** [comment]
I had to trigger the app update in the app store but then - yes it's working!

**Comment by thachjackson** [comment]
Hello, affter two weeks the issue was fixed. It happens again now.
This time, there's no Refresh button, only Dashboard button. Going back to dashboard and open the project again, problem still persists
![IMG_0233](https://github.com/FlutterFlow/flutterflow-issues/assets/82443959/9433053d-71c2-44a9-8b2c-209cc93c0db2)

**Comment by dvdstrk** [comment]
This is maddening.  My one and only complaint about FlutterFlow is that they are too aggressive with their updates and we have no option of using the previous stable version.  They are already about 20 iterations ahead of the documentation and now are getting ahead of their own iPad app.  I wish they would tone it down a little.

**Comment by dvdstrk** [comment]
Correction: there’s an update in the App Store that fixes the problem.

My complaint stands about being out ahead of their documentation, though.

**Comment by pierrecorbay** [comment]
Hi everyone, 

Same issue with the macOs app v4.0.2. I edited few things in my project on the web version and switched back to the macOs app and the pop up saying FlutterFlow Version out of Date appeared.
Same problem with the macOs v4.0.2 application. I edited a few elements of my project on the web version and then returned to the macOs application, at which point the pop-up indicating that FlutterFlow Version out of Date appeared.

Thanks in advance for the fix !!

**Comment by bertke** [comment]
Throwing my name in as having this problem. The team has been so good at
fixing these issues quickly I’m not panicking but I am dead in the water
with developing from my main machine.

**Comment by ToddHerron** [comment]
I'm having this issue (again) on my iPad. Seems to be a "Thursday Issue".

**Comment by dvdstrk** [comment]
It’s a feature

**Comment by thachjackson** [comment]
It's fixed in the latest update on iPad. Thanks

**Comment by ToddHerron** [comment]
Now it is fixed.

**Comment by vincekruger** [comment]
This is happening on the desktop mac app now. :(

**Comment by rssluca** [comment]
> This is happening on the desktop mac app now. :(

You can fix it by downloading and installing the latest version https://flutterflow.io/flutterflow-desktop-app (not ideal)

**Comment by hiayrtonlavayen** [comment]
![Screenshot 2023-11-09 at 21 04 03](https://github.com/FlutterFlow/flutterflow-issues/assets/138722538/a14d607a-2520-4deb-bd8e-c025508f044e)
I'm having the same issue right now on the macOS app, I have to open it in the browser for it to work fine!

**Comment by Juanjereff** [comment]
I have the same problem on the desktop version of Windows!! can you help me!!

![Captura de pantalla 2024-03-30 055522](https://github.com/FlutterFlow/flutterflow-issues/assets/162837272/e578c73c-a15d-4c7d-9c2a-0fd083292352)

**Comment by dylanfox22** [comment]
Hello FlutterFlow team, please review this request immediately, this issue is **not** resolved.

Loading a project on the iPad application essentially makes it invalid to open on any other device or browser. How can an app be have a more recent update deployed than what is up on the desktop browser? This is maddening, as no user troubleshooting can be done to resolve this.

Please feel free to go into my recent projects and make necessary changes. Thanks.

**Comment by critgames** [comment]
I hit this issue again today. Used iOS application and now I cannot open project on any other platform (Web, macOS, or Windows).  https://github.com/FlutterFlow/flutterflow-issues/issues/2721

**Comment by billshipton** [comment]
I have the issue now. I edited my projet on the iPad version, and now cannot open it on any other platform or web without hitting the Version Out OF Date warning. When I hit refresh button it refreshses but always comes back to the warning. So frustrating. What is the fix?

**Comment by dvdstrk** [comment]
It drives me crazy.  Why can’t they test on the iPad before releasing a new version?  The iPad is a pleasure to work with, but it’s unusable because this issue can come up at any time and then you have to wait for FlutterFlow to get back on the same page.


============================
David Stark
Question Mark Media
5 Tudor City Place, #612
New York, NY 10017
917-543-1921
