### ISSUE TITLE
Text field doesn't scroll horizontally to follow cursor

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1566]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When moving the cursor on iOS using the press on spacebar and hold, the field doesn't scroll.

### Expected Behavior

Moving the cursor scrolls the text field to follow.

### Steps to Reproduce

1. Create new text field (1 line)
2. Test on iOS device
3. Type long text, then press and hold spacebar. Moving the cursor doesn't scroll the view.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goddc7s/fYcFqhQMjNlx7bZAnktV+WRMhfYD0EJoudcjCZRBLYtfiYW9EeFebhngD/+jGvvLyVsY6IS2qRrY+yK5XQRXJe3GRb5igEZeWY3AmHe1gGWq0yqSNpyN7IbZtLWNnwFymO/CdG3qCf9qOYwx5e6fDbOY=

### Context

Trying to scroll like in other apps.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/3de6c508-0341-4709-9add-252eedc6f6bb

### Environment

```markdown
- FlutterFlow version: 4.0 Sep 28
- Platform: iOS (iPhone 11 Pro)
- Browser name and version: Chrome Version 116.0.5845.179
- Operating system and version affected: Mac OS 13.5.2 (22G91)
```

**Comment by SameerShahzad99** [comment]
Hi @kium-one, It looks like the video that you were attaching was not completed before submitting the bug, can you please share the link for the video here?

**Comment by sbis04** [comment]
Hi @kium-one, this is an iOS 17 issue on the current Flutter version we are using. In the next update, we'll update the Flutter version to the latest which should fix this issue!
