### ISSUE TITLE
Clear all/select all action does not work as expected with ChoiceChips

### ISSUE THREAD

**Issue by dobleuxyz** [FlutterFlow/flutterflow-issues#1568]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Apparently it changes the values, but the user interface won't actually update and will still show previusly selected chips as if they were still active.

### Expected Behavior

User interface of ChoiceChips should be updated and reflect when this action runs, either for selecting all or deselecting.

### Steps to Reproduce

1. Create a page
2. Add ChoiceChips with options and multiselect activated
3. Add 2 buttons, one with a select all action for ChoiceChips and the other one with a clear all action.
4. Test or run the project, press both buttons. ChoiceChips will stay the same no matter which one you press, the visual state of ChoiceChips will stay the same. My guess is that they need to be rebuild after the actions, because from what I have tested, the actual value they output seems to be changing, just not the interface. This is very confusing for users.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slcr1sI91xNta1brUbsB7/SkXQzM+UOcSsclsbxcbfbb0BIsIYMzORFhUOdOrdAhIPGCJrzkX/Mr9iuHTMMAEKRaufLpCwahqcgGXYHqVbpebBpS3b0FPJ+FRfm2O0bujmglTBLBuS3Nl602Eeu+Xb3fANZDsDkYeROa4XdeK2SrDX1iXc2URm05KZDPz

### Context

Users can be very confused when they clear ChoiceChips but they appear to be selected still, or vice versa.

### Visual documentation

![choice](https://github.com/FlutterFlow/flutterflow-issues/assets/19288406/b6cfbe6e-dba3-4ddf-914f-e9e4a28b5ce0)

### Additional Info

Here is a blank project with the issue > https://app.flutterflow.io/project/choicechips-roojcj

### Environment

```markdown
- FlutterFlow version: .0
- Platform: Test, Run, Android, most likely iOS as well (can't test)
- Browser name and version: Chrome latest...
- Operating system and version affected: Web, Android, iOS
```

**Comment by SameerShahzad99** [comment]
Hi @dobleuxyz, the bug report code that you shared seems to be incorrect, can you please share the correct bug report code, so i could proceed further with the testing?

**Comment by dobleuxyz** [comment]
just updated the post with the new bug code and here it is as well:

IT4slcr1sI91xNta1brUbsB7/SkXQzM+UOcSsclsbxcbfbb0BIsIYMzORFhUOdOrdAhIPGCJrzkX/Mr9iuHTMMAEKRaufLpCwahqcgGXYHqVbpebBpS3b0FPJ+FRfm2O0bujmglTBLBuS3Nl602Eeu+Xb3fANZDsDkYeROa4XdeK2SrDX1iXc2URm05KZDPz

**Comment by Krystian95** [comment]
Is the same of https://github.com/FlutterFlow/flutterflow-issues/issues/1577?

**Comment by hariprasadms** [comment]
Duplicate with - https://github.com/FlutterFlow/flutterflow-issues/issues/1577?
