### ISSUE TITLE
Firebase Region Bug - "Unknown Error. Please contact [support@flutterflow.io](mailto:support@flutterflow.io)"

### ISSUE THREAD

**Issue by raldred2** [FlutterFlow/flutterflow-issues#1569]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

** Please note that I have been discussing/testing with Flutterflow Support and they confirmed this is a bug *

My Flutterflow project is reporting "Unknown Error. Please contact [support@flutterflow.io](mailto:support@flutterflow.io)" whenever I try to [Deploy] new Cloud Functions to Firebase.

After liaising with Flutterflow support (Barry), we believed it to be related to the differing regions used by FF and Firebase.  

FF = [europe-west2] (also tried changing to [us-central1], but same error)
Firebase (Firestore DB) = [europe-west2] (which I don't believe I can change)
Firebase (Functions) = ** the existing {onUserDelete} function deployed by FF deploys to [us-central1] **

I have tried changing FF to [us-central1] - either way, deployment of my custom functions fails, but regardless of selected region under [Advanced] in FF, the built in {onUserDelete} always deploys to [us-central1].

I am now unable to progress my application due to these errors.

Thank you.

### Expected Behavior

No errors :)

** I would also expect to this to work, even with differing regions (whilst acknowledging best practice and potential latency issues.  I ideally want everything deployed in EU/London - but I guess that's a secondary issue.

### Steps to Reproduce

n/a

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whc/6w49PsdhE7c+BbMFvmjoRMjsjao0v08BxRis8GZT0B4kcYs+kfklUOce4YXxfeFqj8DoX/Mr0hobQV8IoNTucGro+wZZtEgrddzulbLaPDIS3b3wkP/hWfn6E5ra7nhRTBO9uV1oA2mGqItnJcDTfJK7uOG0zA+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I have had to completely halt my app development with your product until this is resolved.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/73439020/b019116e-9f87-4c07-a835-64b4fa81aa05

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
This looks like a project-specific issue, please reach out to the support team for project-specific issues, also FlutterFlow currently does not support validation of cloud functions, so would highly recommend you to test locally regarding the validity and correctness of your code, if the issue still persists reach out to the support team.

**Comment by atlas-wonami** [comment]
I`m having the same issue. My region is south america 1, and it is trying to call central america
