### ISSUE TITLE
Sub-collections not shown in Content Manager

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#157]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
https://app.flutterflow.io/cms/
Here only main collections are visible. Subcollections and documents under subcollection are not visible. 

## Current behavior (required)
Only main collection names are visible. Only documents under main collections are editable/deletable.

## To Reproduce (required)
Flutterflow --> Project --> Firestore --> Collections --> Manage contains. 
Subcollections not visible. 

## Context (required)
I need to open the firebase console to check if entries in sub-collections are working fine or not.

## Your environment
windows 10 --> Crome browser -->

**Comment by oper2k** [comment]
and We can't add/change parameter Color and Image in data types from FF CMS

**Comment by katherineqian** [comment]
Hi @palmdeskApp, 

According to the [documentation](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/firebase-content-manager), "Subcollections are not supported in Content Manager at this time." I will mark this as a feature request. 

Thank you for your contribution!

**Comment by katherineqian** [comment]
Hi @oper2k, 

Please create a new issue report for the bug you are reporting in your comment, since it's not the same issue as the one being reported here. This will help us and other users triage and track the bug, if it's reproducible. Thank you very much!
