### ISSUE TITLE
Cant attach an image to the website in webview

### ISSUE THREAD

**Issue by kiwisoftapp** [FlutterFlow/flutterflow-issues#1570]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In my application, I display a website in a webview. You can attach a photo on the website, which works fine in the browser, but not in the webview of the application. Adding permissions to the app doesn't help either. Nothing happens on android when we try to attach a picture. On iOS, you can attach a picture from the gallery, if you try using the camera, the application crashes.

### Expected Behavior

When we try to attach an image to the website in webview, the application should open the gallery or the camera.

### Steps to Reproduce

1. Create a new page
2. Add WebView component
3. Set an URL where you can attach photo

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflfLqx5BgobxY176Ja8JKiiYQJWEcTJMZjtZFewgjF774PLMuZOOlQBBWZMCzaHNEM2KLjlwJ/9bthvD9Jfk5CzWVGoRFwbl+dRPPbGOibJC6O83hQkYnJ+BjCkib56aFrB0nVLdoL0If7UzzGt6RRT2Cf9qOYwx5e6fDbOY=

### Context

My client cannot attach an image to his website in his application, which is displayed in a webview in the application.

### Visual documentation

![IMG_0094](https://github.com/FlutterFlow/flutterflow-issues/assets/144942255/8aec095c-c8d1-4bf0-adc1-e21d99193224)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by kiwisoftapp** [comment]
@hariprasadms When is the bugfix expected?

**Comment by kiwisoftapp** [comment]
Hello!1. Please open https://cashmap.hu and select “Belépés”2. Do login: ***@***.*** / cashmap01$3. Pick one product4. Scroll down and select “Hibabejelentés”5. Attach photo with “Fájl kiválasztása”Thank you!Az iPhone-omról küldve2023. okt. 19. dátummal, 17:25 időpontban Victoria Huang ***@***.***> írta:﻿
@kiwisoftapp can you provide the url you used?

**Comment by victoriahuang1** [comment]
Hi @kiwisoftapp , thanks for the report. I have made a fix on our side, which should go out with the next deploy.
