### ISSUE TITLE
Failed to compute merge conflits

### ISSUE THREAD

**Issue by mztmoraes** [FlutterFlow/flutterflow-issues#1572]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have 3 branches created. One main one, one mine and one from a teammate.

When trying to merge, it shows the error "Failed to compute merge conflicts" and does not show any possible conflicts. It also doesn't update the main one.
![error](https://github.com/FlutterFlow/flutterflow-issues/assets/18100786/cda94280-c97d-4322-985e-8a10bef5663b)

### Expected Behavior

I expected the main branch can be updated with the individual branches.

### Steps to Reproduce

1. Made the changes to my individual branch;
2. Click on the "merge" button;
3. The error "Failed to compute merge conflicts" appears;
4. The main branch does not update or carry possible conflicts;

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40uM/e5YVPnctd55DMKcFXliYiN2YgXOQzjdp7aCosfZT2BLMcec/RVERWcM/iYXNcOk60kWoW0P/Ihc7LC/JdFxWcQYhxz5FuUQHdXnmiWpCkFJWgeGhRGp9UfVzA1Im32xB/PbNeSmAB3GamIOusbz7XGJD4OlgsDq/LZO4=

### Context

We are trying to update the main branch so that everyone works on the same version and can be published later.

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.10.4
- Platform:v4.0
- Browser name and version: Microsoft Edge
Versão 117.0.2045.43 (Compilação oficial) (64 bits)
- Operating system and version affected: Windows 11 Home - 22H2 - Windows Feature Experience Pack 1000.22674.1000.0
```

**Comment by Tomaicomm** [comment]
I do confirm I have exactly same error in all of my projects (old and new). I raised the problem around 5 days ago via chat.

**Comment by wenkaifan0720** [comment]
Hi @mztmoraes @Tomaicomm. We are aware of this issue and is working on fixing it. Thank you for your patience.

**Comment by atlas-wonami** [comment]
I'm having the same issue here, it is impacting our users' experience. Is there any estimated timeframe for when this issue might be resolved?

**Comment by mztmoraes** [comment]
> Hi @mztmoraes @Tomaicomm. We are aware of this issue and is working on fixing it. Thank you for your patience.

Hi @wenkaifan0720 ! 

You have an update for this fix. We are waiting for an important publication to the app.

thanks

**Comment by atlas-wonami** [comment]
@wenkaifan0720 Hi,

do you have any news?

**Comment by liamwoodrepo** [comment]
Is there an expected timeline for for this to be resolved?

**Comment by wenkaifan0720** [comment]
It might be that the merge is initiated from an outdated client. Could you try updating FF first?

**Comment by liamwoodrepo** [comment]
@wenkaifan0720 Worth noting, on our end, after clicking the merge button and the merge window begins to load, we are presented with an infinite loading screen. Which sounds different to the above?

We were told to monitor the bug on here by the support team, however,  we need to guage a rough idea on when this may be resolved please?

**Comment by Tomaicomm** [comment]
> It might be that the merge is initiated from an outdated client. Could you try updating FF first?

It's certainly not a root problem as reload was enforced many times since branches delivery...

**Comment by atlas-wonami** [comment]
> It might be that the merge is initiated from an outdated client. Could you try updating FF first?

I did this in my project and we got the same result here

**Comment by Tomaicomm** [comment]
@victoriahuang1 perhaps you have any feedback on that matter? We are completely blocked with our projects at the moment.

**Comment by victoriahuang1** [comment]
@Tomaicomm can I get the date + time of when you attempted to initiate a merge?

**Comment by victoriahuang1** [comment]
@Tomaicomm I made a fix, which should go out with the next deploy.

In the meantime, can you do the following:
1. make any change on the branch
2. wait a couple of seconds and undo the change on that same branch
3. merge that branch

**Comment by Tomaicomm** [comment]
Dear @victoriahuang1  I did test it with the oldest - and largest project we have - it did not worked.
With the  fresh project I managed to open Merge window however o changes were visible even though I made modifications on the page.
It's very confusing and perhaps best would be to set up an online session so I can present you the case or if you can share some place where I could upload videos (larger than 10 MB limit on github)

regards
Tom

**Comment by victoriahuang1** [comment]
Hi @Tomaicomm , please upload screen recordings with explanations of what you expect vs what is happening for both projects. It would also be helpful to include the project urls.

**Comment by Tomaicomm** [comment]
@victoriahuang1 i have this project commercial so id prefer to share it on private channel. Please Let me know how we can do it?

**Comment by atlas-wonami** [comment]
> Dear @victoriahuang1 I did test it with the oldest - and largest project we have - it did not worked. With the fresh project I managed to open Merge window however o changes were visible even though I made modifications on the page. It's very confusing and perhaps best would be to set up an online session so I can present you the case or if you can share some place where I could upload videos (larger than 10 MB limit on github)
> 
> regards Tom

same here

**Comment by Tomaicomm** [comment]
> Hi @Tomaicomm , please upload screen recordings with explanations of what you expect vs what is happening for both projects. It would also be helpful to include the project urls.

Dear @victoriahuang1 I spoke to the support, they'll share the materials with you internally. 
thank you

**Comment by siddharthshah3030** [comment]
@victoriahuang1 When it's expected to be deployed ?

**Comment by victoriahuang1** [comment]
@siddharthshah3030 it should be in a few days.

**Comment by matjbarcelos** [comment]
@victoriahuang1 
Do we have an alternative to merge while the bug is not fixed? Or do you suggest make the whole feature again in the main branch?

**Comment by victoriahuang1** [comment]
@matjbarcelos the bug is related to team resources. If there are no team resources, it should work. The fix should be deployed in a couple of days!

If you are still experiencing issues even without team resources (like team API), please open a separate github issue for investigation.

**Comment by victoriahuang1** [comment]
The fix should be deployed now. Please let me know if there is still an issue.

**Comment by Tomaicomm** [comment]
derar @victoriahuang1, thank you for fixing this up. The merge window indeed opens.
However 2 things:
1. No matter how many changes I'll do in sub-branch I get information that "there are 0 conflicts"
2. However when I click "Merge branch" apparently all changes are merged to the main branch.
3. I can not push the su-branch into the Github (simply when going to sub-brach Repo the configuration is read only) - but perhaps this is expected and there is other way to sync sub-branch to the repo

Please let me know if:
- 1 and 2 are possible errors
- 3 is works as expected and if yes how to push branch to my github repo.

thank you

ps. 
@matjbarcelos , @siddharthshah3030 , @atlas-wonami , @wenkaifan0720 , @liamwoodrepo , @mztmoraes 
I wonder what is your current experience.
If you're using Teams version and willing to cross the experiences please reach out via community [https://community.flutterflow.io/member/5vosgH9Raq](https://community.flutterflow.io/member/5vosgH9Raq)

cheers!

<img width="1213" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128980409/2c64fe51-0a2a-4cbb-bd06-c64f8f7a41ea">

**Comment by J-Amaya** [comment]
Hi. 
Me and any team are having the same issue. 
It is not happening in all the projects and this project use team resourses., Api and images.

The steps are simple:
1.- open project in main branch ( it doesn't matter if there are other brances or if it is the only one)
2.- create a new branch
3.- make a simple text change in a page
4.- merge brance 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/78978197/00f6a186-a5e1-4a04-bd51-17e1f90108bc)

Thanks in advance for your help!!

**Comment by victoriahuang1** [comment]
> derar @victoriahuang1, thank you for fixing this up. The merge window indeed opens. However 2 things:
> 
> 1. No matter how many changes I'll do in sub-branch I get information that "there are 0 conflicts"
> 2. However when I click "Merge branch" apparently all changes are merged to the main branch.
> 3. I can not push the su-branch into the Github (simply when going to sub-brach Repo the configuration is read only) - but perhaps this is expected and there is other way to sync sub-branch to the repo
> 
> Please let me know if:
> 
> * 1 and 2 are possible errors
> * 3 is works as expected and if yes how to push branch to my github repo.
> 
> thank you
> 
> ps. @matjbarcelos , @siddharthshah3030 , @atlas-wonami , @wenkaifan0720 , @liamwoodrepo , @mztmoraes I wonder what is your current experience. If you're using Teams version and willing to cross the experiences please reach out via community https://community.flutterflow.io/member/5vosgH9Raq
> 
> cheers!
> 
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/128980409/278583506-2c64fe51-0a2a-4cbb-bd06-c64f8f7a41ea.png">

1 & 2. 0 conflicts doesn't mean 0 changes -- it's just that there was nothing that needed human intervention. So yes this is expected.
3. yes this is unfortunately a current limitation, but we do plan on making this possible in the future!

**Comment by victoriahuang1** [comment]
@J-Amaya thanks for the report. Please file this as a new Github issue, with all of the necessary information.

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!
