### ISSUE TITLE
Firebase Cloud Messaging

### ISSUE THREAD

**Issue by ricardocosta43** [FlutterFlow/flutterflow-issues#1573]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Implemented push notification in the project.
If I log in with the same user on two different devices, a second token is created in the "fcm_tokens" collection.
When I send a notification to this user, he is using the first token he finds, not the last one created

### Expected Behavior

push the last token created

### Steps to Reproduce

Log in as user A on a device. Then log in with user A on another device.
Send a push notification via the app to user A

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NOT HAVE

### Context

I am sending push notification from one user to another user.
NOT BULK SHIPPING

### Visual documentation

![Captura de Tela 2023-10-02 às 07 04 00](https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/5fb63c7c-b728-490d-a63c-2ba0e6f2e85a)

### Additional Info

IMPORTANT NOTE

I'm testing push notification on a real device. When there is only one record in fcm_tokens, it works perfectly

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Android
- Browser name and version: Chrome 116.0.5845.187
- Operating system and version affected: macOS Sonoma 14.0
- Device version affected: Android 11
```

**Comment by hariprasadms** [comment]
Hi @ricardocosta43 - Thanks for submitting the issue. Please provide us the project bug report code. Without bug report code, we can't investigate the issue. Also, confirm below points.

1. How are you sending the notifications to user device ? From editor or from app (using push notification action trigger)? 
2. Are you using target audience or user reference option to send a notification to specific user?

When you log in with the same user on two different devices,Firebase Cloud Messaging (FCM) generates a unique registration token for each device. These tokens are used to identify the specific device that should receive the notification. Therefore, I advise clearing these tokens and test message triggers several times to see whether the issue persists. Please confirm these details.

**Comment by hariprasadms** [comment]
Hi @ricardocosta43 - Any updates about the required details?

**Comment by ricardocosta43** [comment]
the project does not issue a bug code
________________________________
De: Hari ***@***.***>
Enviado: quarta-feira, 4 de outubro de 2023 12:47
Para: FlutterFlow/flutterflow-issues ***@***.***>
Cc: ricardocosta43 ***@***.***>; Mention ***@***.***>
Assunto: Re: [FlutterFlow/flutterflow-issues] Firebase Cloud Messaging (Issue #1573)


Hi @ricardocosta43<https://github.com/ricardocosta43> - Any updates about the required details?

**Comment by hariprasadms** [comment]
Hi @ricardocosta43 - You can get the project bug report by right clicking on on page widgets tree. Also add details about above two points. If this issue is already resolved for you, let us know we can close the issue. Thanks

**Comment by hariprasadms** [comment]
Hi, As there is no response, I presume the issue has been resolved. If this is the case let me know I can close the issue. Thanks
