### ISSUE TITLE
flutter_facebook_auth version is too old

### ISSUE THREAD

**Issue by jeanlouisliaud** [FlutterFlow/flutterflow-issues#1574]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using facebook authentication on my Flutterflow application and I'm getting an error on the facebook developer dashboard (c.f screenshot). 

<img width="1093" alt="Capture d’écran 2023-10-02 à 18 14 02" src="https://github.com/FlutterFlow/flutterflow-issues/assets/115577193/dc846645-0ca8-4bf1-a13a-eab86df344ce">

It seems that the version of the facebook SDK used by Flutterflow, via the flutter_facebook_auth library, is an old version that needs updating. The version of flutter_facebook_auth used by Flutterflow is 3.5.3, which includes SDK 12.0.1.

Do you know if an update of this package is planned to integrate version 13 of the SDK?

### Expected Behavior

The version of the flutter_facebook_auth lib has been upgraded to at least version 4.2.1 

### Steps to Reproduce

1. Install facebook auth and config it in Flutteflow
2. Go to facebook develop package
3. Watch the warning/blocking message for Android SDK

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skufl3ItOtbxG+Kr+bsBB/WYWOVAiRJJJscsZa0kdB4joPLJ/O+P7YRBWXse9dHlhHFaYjmAd0c6Jv4bhVsI7BxWsc4B++KhyVznge3q8RqqWPJOwWHZCJ9hTGm6m38KzvRRdLsZoSkFn62WQJuuicz3cGZu/Zwh9f6PHaOI=

### Context

This affects my client in terms of setting up pubs.

### Visual documentation

<img width="1093" alt="Capture d’écran 2023-10-02 à 18 14 02" src="https://github.com/FlutterFlow/flutterflow-issues/assets/115577193/01b3f04d-6500-4ca6-a27d-5ffd32e4a771">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mobile
- Operating system and version affected: IOS / Android
```

**Comment by hariprasadms** [comment]
Hi @jeanlouisliaud - Thanks for submitting the issue. Please confirm whether Facebook authentication is that working properly with the current version. The message that you are seeing is a warning, so it shouldn't have any impact on FB authentication working status. Please confirm.

**Comment by jeanlouisliaud** [comment]
Hi @hariprasadms ! Facebook authentication works on android versions greater than or equal to 13

**Comment by hariprasadms** [comment]
Hi @jeanlouisliaud - This is related to dependency update. However I have marked it as bug so that team can have a look at it. Thanks

**Comment by jeanlouisliaud** [comment]
Hi @hariprasadms ! Any update on this issue ?

**Comment by hariprasadms** [comment]
Hi @jeanlouisliaud - No updates about it. Dev team should be able to look at this in sometime. But no ETA. Thanks

**Comment by jgupdogg** [comment]
Hi, there are still a lot of people including myself who need help to resolve this issue.  I purchased a fluterflow pro subscription, largely because the the auth flows for facebook, google, and others.  My other flows work fine, but the facebook does not work at all.  Knowing flutterflow has known about this for months but not addressed the issue because not enough people were commenting, eventhough its a main advertising point is quite concerning!

Please resolve this issue.

**Comment by agreaves** [comment]
Hi @jeanlouisliaud and @jgupdogg, apologies for the delay in getting to this issue. We're working on a fix, currently testing out upgrading the `flutter_facebook_auth` version to `4.4.1+1`.

In the meantime, a workaround for anyone affected by this is to create a dummy Custom Action and add a pubspec dependency for `flutter_facebook_auth: 4.4.1+1`. This will override the version FlutterFlow uses by default.

**Comment by vedantatech** [comment]
Hi @jgupdogg

How did you complete the Android , iOS and Web configurations?
https://facebook.meedu.app/docs/6.x.x/android

Was this issue resolved?

**Comment by jgupdogg** [comment]
I stopped using flutterflow and switched to React Native with draftbit.  Now it works.

**Comment by rzambroni** [comment]
HI everyone! so sorry about the delayed answer, we are trying to get up to speed with every reported issue. We revalidated this one and it seems to be working as expected now. Would you mind confirming if you're still having issues with the facebook integration? 

Thanks a lot!
