### ISSUE TITLE
Checkbox group even when selected is not showing anything in the result list that i am using as filters for backend query as a result the filter isn't working

### ISSUE THREAD

**Issue by TandemloopTechFlutterflow** [FlutterFlow/flutterflow-issues#1575]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On selecting items from group should produce a list using which i am filtering a backend query list
![slectedGroup](https://github.com/FlutterFlow/flutterflow-issues/assets/118335584/1096dd5f-eab3-45cf-bdca-752f23e0ba3e)
![Selection count](https://github.com/FlutterFlow/flutterflow-issues/assets/118335584/b2241017-e24a-4843-b385-56aa65334f1b)

### Expected Behavior

The count as per above should be 3 

### Steps to Reproduce

Select the items on a page with multiple checkbox groups, use text variables  supposed to show the list length post selection, one or both showing incorrect length   

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lfLqwIt1m+FC7q6JYPlV+WAsJn07R4INjsFhcEs8J4DaP5kQZcykTFRpT+GrTAhYPlu0pGQy082PkvzMUuQHAwWrfYhAyaVuUDnKIWOXb4i3CZOoT3F8DexmNEuV0buvqyZNNsVuWEY+62eICO6vThfYJZjbDmtAL86jENz4pWDiAhm6Xn0Jg1ZSfCvr

### Context

This list i need to produce for using as filter a list of backend documents however since results anomalous the filters behaving absurdly

### Visual documentation

This is unfiltered list
![Unfiltered list](https://github.com/FlutterFlow/flutterflow-issues/assets/146804620/c6984ab1-1906-4ff0-8c20-65cb2aa7d209)
This is filter
![Filter](https://github.com/FlutterFlow/flutterflow-issues/assets/146804620/7ecddc68-91b2-41bf-a623-aeb9db698c87)
Based on selection 4 seats it should show cards that have only 4 seats in them
![Post filter list](https://github.com/FlutterFlow/flutterflow-issues/assets/146804620/37ccc416-b25d-4ef6-a7b3-c7aaee95b949)

### Environment

```markdown
- FlutterFlow version: v1
- Platform: Android
- Browser name and version: none
- Operating system and version affected: none
```

**Comment by SameerShahzad99** [comment]
@TandemloopTechFlutterflow As I checked, it looks like a project-specific issue, please reach out to the support team by emailing support@flutterflow.io or using live chat
