### ISSUE TITLE
File picker for web HTML element

### ISSUE THREAD

**Issue by MAlMazrou** [FlutterFlow/flutterflow-issues#1576]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After uploading an image the file picker for web element appears on top left of the page.

<img width="429" alt="Screenshot 2023-10-03 at 12 10 05 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/f730df5b-29f1-46c8-b4bb-e1eb27c1c3bd">

### Expected Behavior

The file picker element should not be appearing.

### Steps to Reproduce

Go to image upload page.
Upload image.
Go back.
Logout.
Login.

Maybe the file picker is there but I cannot see it because the appbar is covering it, but in the login page the appbar is removed so the file picker is visible.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiMjfsI52ocMA+KqNKe5FgSoRGUMfWLsr0utuGA0hNZyvP4kuec7OaVtLYteDfwhUI1ajrFgy7vT2i+OWUvldITCuGrZzwa5XQRbKcFOnMaqRDaWOeXd6J/hWIW69y6SJkQpDD/V2LlYd1zuqJfCdG3qCf9qOYwx5e6fDbOY=

### Context

The app is working fine, but the file picker shouldn't be appearing.

### Visual documentation

The file picker element appears once I open the app, but for some reason it's hidden.

But after doing those 2 steps the file picker will be displayed

<img width="418" alt="Screenshot 2023-10-03 at 1 46 35 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/aad3178e-2c48-41c5-81d8-373adb2f3e4b">
<img width="429" alt="Screenshot 2023-10-03 at 1 47 13 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/56c97f45-59fd-4be9-bc31-3ec41b803f22">

### Environment

```markdown
- FlutterFlow version: v5 (released September 28, 2023)
- Platform: Web
- Browser name and version:Version 117.0.5938.92
- Operating system and version affected: MacOS Ventura 13.5.2
```

**Comment by MAlMazrou** [comment]
It is also appearing in the safari browser, but it also shows the icon of the image uploaded.

<img width="1710" alt="Screenshot 2023-10-03 at 2 04 22 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/e9c14520-1e5f-4e6c-882c-d81ed387c13e">

**Comment by hariprasadms** [comment]
I just checked above steps in my projects. It all works fine. Can you also confirm what type of upload you are using?

**Comment by MAlMazrou** [comment]
I created a blank project, file pick element was not there, I added a button with upload media action, then the element appeared.

**Comment by MAlMazrou** [comment]
> Hi @MAlMazrou - Thanks for submitting the issue. I looked at your project. There are many pages. Not able to locate the page where you got the issue. Please create a blank project and reproduce the issue with all the steps. Share the bug report code of the same project. We will be happy to investigate the issue when the necessary information is provided.

You can go to SellerPortalNewItemPage and add use the button upload image, the go to login page, then you should find it on the top left.

**Comment by MAlMazrou** [comment]
> > added a button with upload media action, then the element appeared.
> 
> I'm still not able to re produce. Send the blank project with bug report code where you can see the issue.

Until now I couldn't re produce it exactly, I am still trying, once I find out how, I will update you.

**Comment by MAlMazrou** [comment]
In the login page I added a third button under "back" once you click on it you should see the element on top left, in the mean time, I am creating another firebase project for the blank project to see how can I reproduce this issue, and by the way I am not getting any error messages regarding this element, I am getting several errors but they are related to firebase, to be honest I am not sure if it has any kind of impact, do you want me to share the errors?
<img width="542" alt="Screenshot 2023-10-03 at 9 35 54 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/151a5492-a2d6-423e-b9ed-1d04c62aad72">

**Comment by MAlMazrou** [comment]
I created a new project and connected it to the firebase but still can't re produce it in an identical way.

**Comment by MAlMazrou** [comment]
I found out that I get this error when I upload any image on my project, but in the blank project its all fine.

<img width="820" alt="Screenshot 2023-10-03 at 9 53 06 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/e707fa9f-4f41-4ad7-9b27-87b78b979af0">

**Comment by MAlMazrou** [comment]
Maybe the reason I couldn't re produce the same error in a blank project is this.

<img width="473" alt="Screenshot 2023-10-03 at 10 42 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/14786cb2-1611-4eeb-8010-0d2e3c983121">

In the above image you can see that I can't choose the upload type in the new blank project, I have done all the firebase setup required but the upload type didn't appear.

<img width="472" alt="Screenshot 2023-10-03 at 10 43 51 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/146825312/4dec87c7-b705-4f31-b287-3bdea7ff4884">

The above image is from my current project when I can choose the upload type.

I can't decide if its is relevant or not, but I am trying to figure out how to re produce this error, but I can't and at the same time I can't fix my project.

**Comment by hariprasadms** [comment]
This issue sounds like project specific. This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/).

**Comment by MAlMazrou** [comment]
@hariprasadms Thanks for your time, and sorry for any trouble, take care.
