### ISSUE TITLE
Reset form field action - ChoiceChips, Is not working

### ISSUE THREAD

**Issue by davidflutterflow** [FlutterFlow/flutterflow-issues#1577]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we perform a reset form field action, to reset a choicechips to its initial value, it throws exception errors in the console: Bad state: No element

### Expected Behavior

Choicechips should reset to its initial value

### Steps to Reproduce

1- add a choicechips to a page
2- add reset form field action and select the choicechips
3- Test it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Olcr1sI91xNhE7c/QacBB/SkvKUQjbZZMitYbewkdG5/NGu4Iec/eUFZuZr3jTVZmeGGJozgd/PfquOOSVO4FC0uBc5w+ypBIazvheGC6VZubDKW3fW1SQNpVIEzE14m33RBSANtqLk4+wEzzed6RSi3aHpzFDGszLvibLdeK2SrDX1iXc2URm05KZDPz

### Context

This is a bug report from support.

### Visual documentation

![SCR-20231003-owjs](https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/52f52a5a-61ef-4fca-a7b4-34cf84645da1)

### Additional Info

Replicated the issue in a new project:

Project URL: https://app.flutterflow.io/project/choice-chip-reset-acfju1?tab=widgetTree&page=HomePage
Run link:https://app.flutterflow.io/run/x2BTLcDoLmpgtZNGwdxh

### Environment

```markdown
- FlutterFlow version: 3.10.4 Sept 28
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hi @davidflutterflow - Thanks for the issue. I can confirm that it is a bug. Resetting choice chip form widget is not working any cases ( either selecting index from the list or first value ).

 Dev note - 

<img width="778" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/41c49a01-37d1-4378-8593-91a35f5e1f87">

**Comment by Krystian95** [comment]
Hi, yes the problem still persists.

https://app.flutterflow.io/run/5Ih2LYkQFNdzS9wxCZZj

**Comment by ChangeMaker13** [comment]
I read your codebase for a while, and I recommend you to update this part of code in "flutter_flow_choice_chips.dart"

`
...
changeSelectedValues.addListener(() {
      if (widget.onChanged != null) {
        widget.onChanged!(selectedValues);
        choiceChipValues = selectedValues; //this
      }
    });
...
`

I think the state of raw choice chip widget (aka choiceChipValues) and the controller value(selectedValues) didn't communicate each other well. It's a trivial opinion, but I'd appreciate it if you could refer to it

**Comment by Krystian95** [comment]
Hi, I'm facing issues also on Set Form Field > ChoiceChips. Also anyone else?

Project Run: https://app.flutterflow.io/run/DfubACZ1AFR3eG9D1LXE

Bug report code: ITESz/Hqx89gosAD1s/AY8FAhQAkH1x/bZJEl9cbGA4jfJvmE4Ytd+r+VENfYOGAeGNXM1f+pHwKw9GMuNnEVsIoHzScaINoypN6EDuXUlGXWq6DDauoQmpBEZlPGUCwy8GNqxBSOtFaZVUjw2z/cq3qNleeY8aSfxBlZ7vfcPo=

**Comment by JamesKr85** [comment]
It happens me too suddenly after ff version update

**Comment by spiralventures** [comment]
This also happens when using the "Clear All" and "Select All" actions, it updates the output for the choicechips widget but doesn't actually update the "choiceChipValues". I asked ChatGPT why it wasn't updating and this is what it's outlined if it helps.

"When the "Select All" or "Clear All" buttons are pressed, the FlutterFlowChoiceChips widget's controller is updated, but it seems like the widget's internal state, represented by choiceChipValues, does not get updated accordingly. The choiceChipValues list is only updated in the onSelected callback of each ChoiceChip, and not when the controller value changes."

**Comment by wenkaifan0720** [comment]
Hi All. This should be fixed in our next update. Thank you!

**Comment by nicmohr25** [comment]
Hello @wenkaifan0720, is the update regarding the reset Action already deployed? I am still facing this issue

**Comment by garenkarapetian** [comment]
I'm still facing this bug in FlutterFlow on Nov 17, 2023.  Still getting a red screen with "Bad state: no element" error.  Is there a quick patch that we can implement in code??

**Comment by Krystian95** [comment]
Hi to all, @wenkaifan0720,

The problem with the action "Reset Form Field" (ChoiceChips) still persists: https://app.flutterflow.io/run/yciZX5ZRIBeFq0JQEwoP
In this simple example if you selected some chips and then press the button to clear (that execute the above mentioned action), the ChoiceChips are not cleared.

Project Id: test-37olsl
Button debug code: ITESz/Hqx89gosAD1s/AY8FAhQAkH1x/bZJEl9cadwIjCLbvP6QuOer+VGBYONeHYH1+CmekgToepcqOhePDJfo5HzKbeINoypN6EDuXUlGXWq6DDauoQmpBEZlPGUCwy8GNqxBSOtFaZVUjw2z/cq3qNleeY8aSfxBlZ7vfcPo=
