### ISSUE TITLE
Gap above App bar

### ISSUE THREAD

**Issue by efficientaman** [FlutterFlow/flutterflow-issues#1578]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was using default app bar without any silverAppBar behaviour. But after recent updates, I see there is extra gap above my app bar i.e. some default padding at the top of app bar and I am not able to remove it.

### Expected Behavior

No padding/extra space at the top of app bar.

### Steps to Reproduce

1. Create a new page
2. Add an app bar
3. You will see there is some extra padding at the top of app bar

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N.A

### Context

Now the app bar is taking extra space which is worsening the mobile experience.

### Visual documentation

![Screenshot 2023-10-02 at 12 46 35 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/127823947/d725d4b5-d8e0-4b26-b3ef-1e48744a6051)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web and mobile
- Browser name and version: Google Chrome
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @efficientaman - Thanks for submitting the issues. Add project bug report code please. I just checked the app bars adding to new page. It all looks fine. I would suggest create new pages and add app bars using settings. See the consistency of the issue.
