### ISSUE TITLE
Screen shots generation does not include 5,5" screens for apple store

### ISSUE THREAD

**Issue by ccasallas** [FlutterFlow/flutterflow-issues#1579]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Screen shoots generation does not include 5,5" screens for apple store

### Expected Behavior

Screen shoots generation must include 5,5" screens for apple store.

### Steps to Reproduce

1. Preview App
2. Screenshot mode
3. Enable App store screen shots
4. Generate screen shots

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

On mobile deployment.

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: 4
- Platform: -
- Browser name and version: chrome, last version.
- Operating system and version affected: windows
```

**Comment by sbis04** [comment]
Should be fixed in the next update!
