### ISSUE TITLE
Algolia Timestamp Unix error Value - Unexpected null value

### ISSUE THREAD

**Issue by B4sti3n** [FlutterFlow/flutterflow-issues#1580]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A lot of people  have a problem with the display of Algolia timestamp Unix result.

The response body is fine as bellow :

![Capture d'écran 2023-10-02 235155](https://github.com/FlutterFlow/flutterflow-issues/assets/23076459/d15dc644-a524-44ea-ad93-dca8c154d8e7)

But I cannot diplay anymore the date in flutteflow... All the text is fine but I have an error as soon as I try to diplay the date. It worked perfectly fine before.. Does Flutterflow can't anymore parse the Unix Date from Algolia ? If I remove the date in the UI it work again...

![Capture d'écran 2023-10-02 235441](https://github.com/FlutterFlow/flutterflow-issues/assets/23076459/f77b9acc-de22-4278-96aa-8cdd90780527)

### Expected Behavior

Date from algolia on UI from Flutterflow

### Steps to Reproduce

1. Get from aloglia a timestamp information
2. try to diplay it on Flutterflow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkvHq05NOmNxE+ZD2cMIxjikwGUwCaI0z0tlETRQdfuKvOoYAO8nBNxdtWOqHTQhqe078/X8ep/T4iN7lK+0oNUmcfaZcyKVxUxDgWTuVSr6uCJO0YkR5L8FWGH6j56enmyNTJrNaLkYk3EOuf+yua3qCf9qOYwx5e6fDbOY=

### Context

Can't anymore see the result on my app and a lot of other people are affected

### Visual documentation

see in first description

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Algolia
```

**Comment by Wittrup90** [comment]
I experience the same.

**Comment by hariprasadms** [comment]
Hello @B4sti3n - I apologies delay in responding to the issue. I'm started investigating the issue ( and all its linked issues as well ). I will update the status shortly. Thanks

**Comment by ggabrovski** [comment]
I experience the same. Here you can find the bug report code for my project:

IT4oivHq34ZOxcMB15DcdcBspyQ7HGF/a7gJm8pBZzUYF5SuCLMqY8mnPltuTc/hT2w7PGCmp14D+ezXhof9N8dfFzOWGL5bzapAVz3MJUatVLWTF7WOfXR6L9FQGHau4Ku3iAlSG/heckYf3V2qIuqiSjDaJabFPFQ8Sq/LZO4=

**Comment by hariprasadms** [comment]
Hi, I can re-produce the issue.

**Comment by FilliTech** [comment]
We have the same, pls adjust asappppp

**Comment by hariprasadms** [comment]
Hello, A quick update. We have fixed the issue. It should be available in next updates.

**Comment by Wittrup90** [comment]
@hariprasadms when will that be?

**Comment by hariprasadms** [comment]
> @hariprasadms when will that be?

That should be next week Thursday.

**Comment by aemelyanovff** [comment]
Sorry for the slow response. I believe it's been fixed a while ago, so I'm closing the issue. Please reopen it if it's still happening.
