### ISSUE TITLE
Api doesn't work

### ISSUE THREAD

**Issue by singular6N** [FlutterFlow/flutterflow-issues#1581]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is a simple api request. But i don't understand what is hapend.

Im adding all the tests with postman if you need test this one with complete information.

### Expected Behavior

![image (10)](https://github.com/FlutterFlow/flutterflow-issues/assets/138240040/2cfa8f1d-c20a-4c53-ad58-2c77da0e88e9)

### Steps to Reproduce

1. Just test the api on postman. It works on postman.
2. Test this one on flutterflow.
3. On flutterflow it fails.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Status 404 (Failure)

### Context

I cant continue developing my project.

### Visual documentation

![image (10)](https://github.com/FlutterFlow/flutterflow-issues/assets/138240040/e40bd76b-16dc-4b90-ab41-1f2a90fa6662)
![image (9)](https://github.com/FlutterFlow/flutterflow-issues/assets/138240040/a81b2387-bbf6-4773-925b-702d9331ddf6)
![image (8)](https://github.com/FlutterFlow/flutterflow-issues/assets/138240040/cfe5d316-5ac7-471b-b583-f70caec66194)
![image (7)](https://github.com/FlutterFlow/flutterflow-issues/assets/138240040/bb1018c6-f44e-43c2-9e31-13b7372386db)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: FlutterFlow App For Mac
- Browser name and version: Google Chrome
- Operating system and version affected: Mac
```

**Comment by sbis04** [comment]
Hi @singular6N, can you please add the Bug Report code from your FlutterFlow project? You can generate one by right-clicking on any widget inside the Widget Tree.

<img width="530" alt="Screenshot 2023-09-19 at 3 28 47 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/e205da28-a1f6-4954-abf6-aa8da4819d47">

**Comment by CarlosSingularDesign** [comment]
Hi @sbis04 I get this bug report code

`IT40l/H134x1obgA1s71bcB7/To5JWImRI0rjsF7aCosfZT2BLMcec/RVERtXbHgY29DfWK0hWoW0daNis7MFe05NTGYfqZn1ahuWgqXRTuiMJSuFJWgdHd9I/tPJnKF18GR3RJ5BNFsc2Qk6k73B/ORFy3qJYD7DWokDq/LZO4=`

**Comment by hariprasadms** [comment]
Hi @singular6N - Do you still have this issue ?

**Comment by hariprasadms** [comment]
Thanks for your response. The CORS related issues you should handle with the correct proxy configured at your end.  As it is not bug at FlutterFlow end, I will close the issue. If you got any more issues you can always create new issue with required details. Thanks for your contributions.
