### ISSUE TITLE
Checking if field on user document is set doesn't work

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1583]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating an action with the condition "[user document field] is set", the condition returns true if the field doesn't exist.
How else can I check if the field is present or is null?

Here's the code for this function:
Future welcomeSubscriptionPermissions(BuildContext context) async {
  if (valueOrDefault<bool>(currentUserDocument?.subscribed, false) != null) {
    context.goNamed('homePage');

    await action_blocks.checkSubscription(context);
  } else {
    context.goNamed('welcome');
  }
}

ChatGPT's answer about it:
If the subscribed field does not exist and you're still being directed to the homePage, it's likely because of the way the valueOrDefault<bool>(currentUserDocument?.subscribed, false) function is implemented or being used. In your original code, this line:

```
if (valueOrDefault<bool>(currentUserDocument?.subscribed, false) != null) {
  context.goNamed('homePage');
  await action_blocks.checkSubscription(context);
}
```
will always evaluate to true because valueOrDefault seems designed to return a default value (false in this case) if the field doesn't exist or is null. Therefore, the comparison != null will always be true, and the code will always navigate to homePage.

### Expected Behavior

"Is set" should return false if the field is not set. 

### Steps to Reproduce

1. Create an action with a condition "is set" on a user document's field
2. Delete the field on the user document if it exists
3. Action goes to true even if the field is null

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0st5Hd0gdCOPrBu0MZODBPhZpZ7yoaVNcImH9kkEC+Pz9uNrhDPoECwydbrk+z6gNZxXee2i5bJOYOpC8Tmt9O8RXfEyw56evqwhCAMxfcVlg2Dm1fPOtQjPDFOu/Zwh9f6PHaOI=

### Context

Trying to check if the field is null or non-existent.

### Visual documentation

<img width="1628" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/88d895e1-dab8-434a-a068-3cbf76fd8864">

### Environment

```markdown
- FlutterFlow version: 4.0 Sep 28
- Platform: Chrome
- Browser name and version: Version 116.0.5845.179
- Operating system and version affected: Mac OS 13.5.2 (22G91)
```

**Comment by kium-one** [comment]
I tried this but it also doesn't work. I'll send a support request.

<img width="1233" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/00d98f86-f789-40ab-b063-f73470d7d129">

**Comment by davidflutterflow** [comment]
Hi, Hope you doing well. this is not a bug, you are just checking the wrong condition. for a boolean, you shouldn't check whether is set or not because always it's true. because of how we implement this in FF.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/e0498937-d446-482c-a87f-4c72bbc7ab29)

You need to directly select the subscribed field in your condition no need for a single condition

It should be like this:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/4b364ae4-d95e-4896-9350-bde039d9c9bf)

Another issue I can see in your action flow is you have an action block after a navigation action. You shouldn't do this unless you know what you are doing. generally in normal cases the navigation action should be the last action in the chain of actions

**Comment by kium-one** [comment]
Thank you David! I want to check if the subscribed field exists (regardless of true or false). I believe setting the condition on the subscribed field directly would return false if the field is “false”, but I want it to return true because it is set.Is there any other way of doing this?On Oct 5, 2023, at 5:53 PM, David ***@***.***> wrote:﻿
Hi, Hope you doing well. this is not a bug, you are just checking the wrong condition. for a boolean, you shouldn't check whether is set or not because always it's true. because of how we implement this in FF.

You need to directly select the subscribed field in your condition no need for a single condition
It should be like this:

Another issue I can see in your action flow is you have an action block after a navigation action. You shouldn't do this unless you know what you are doing. generally in normal cases the navigation action should be the last action in the chain of actions

**Comment by kium-one** [comment]
From my understanding of how FF is built, this is a bug, or should not be named “field is set”. Otherwise what does it mean for a field to be set if it returns true even when the field doesn’t exist?
I’ll create a custom function for this in the meantime.
I hope the rest of the product works fine. When I use “field is set” in conditional visibility, it seems to behave properly.

**Comment by kium-one** [comment]
I think the issue lies somewhere else: there's no way to do an action post-login because an auth action automatically navigates to the home page, so essentially it doesn't matter what I set up. I'll close the issue, seems like a feature request.
