### ISSUE TITLE
JSON Path issue in ListView

### ISSUE THREAD

**Issue by nitin-anantpranali** [FlutterFlow/flutterflow-issues#1587]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi,

I am using a ListView and using API call to load the List.
In the ListView there are multiple fields which I want to fetch from the API Response.

In Generate Dynamic Children in List View, I have attached JSON Body. And in the separate children, I am assigning the JSON Path as $.items[:].sCityName.

But it generates error. Where I am going wrong?

My JSON Response is as follows
{
"page": 1,
"perPage": 30,
"totalItems": 2,
"totalPages": 1,
"items": [
{
"id": 1,
"collectionName": "Cities",
"sCityName": "ABC",
"sPinCode": "101010"
},
{
"collectionName": "Cities",
"id": 2,
"sCityName": "PQR",
"sPinCode": "121212"
}
]
}

### Expected Behavior

As mentioned in the Video, the JSON Path should work as 

$.items[:].sCityName

### Steps to Reproduce

1. Create Page (I have selected List Page with multiple fields in List Childs)
2. Assign API Call in Backend Query to ListView
3. Generate Dynamic Children = JSON Body
4. First Text Field in ListView, Assign Text property to JSON Path as $.items[:].sCityName
5. Second Text Field in ListView, Assign Text property to JSON Path as $.items[:].sPinCode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi/Ll5YphosxE1c7XbsFVuCIwGUwCaI0z0tlETRQdfuPyPZkyPs/OZVpCcuqHeW5heVf+8TsewaHvkofhOMYDIS6BbLZjwZFXUxDhZHy6eK6MCbuwe0B7O8dPf1SG0p+7giMmPu9Zc3gCwFyhe9yAb3qCf9qOYwx5e6fDbOY=

### Context

Can't run the App

### Visual documentation

<img width="365" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/116695322/59d9fb00-0fc5-421c-9767-f181a8aea835">

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/116695322/7d6475a2-96a1-447d-b724-33c49e636a7b)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @nitin-anantpranali - Thanks for submitting the issue. I looked at your project. I see the Api end point you are showing above works fine in test but not in run mode. Can you see what error you see in browser console when you navigate to the page. I think, the network is blocking the api response due to CORS error. This can happen when the api is private and it expects a proxy.

**Comment by nitin-anantpranali** [comment]
When I transfer to the page, I get this response.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/116695322/09b56eaf-6568-4370-86a5-dd6c724cb03d)

Also in Postman I get proper reply from API as

{
  "page": 1,
  "perPage": 30,
  "totalItems": 2,
  "totalPages": 1,
  "items": [
    {
      "collectionId": "giqtt8yfkfhtiqr",
      "collectionName": "Cities",
      "created": "2023-10-04 04:47:51.852Z",
      "id": "ldkldve5cslu055",
      "sCityName": "Loni",
      "sPinCode": "413713",
      "updated": "2023-10-04 04:47:51.852Z"
    },
    {
      "collectionId": "giqtt8yfkfhtiqr",
      "collectionName": "Cities",
      "created": "2023-10-04 04:48:05.824Z",
      "id": "mo4y3grz9y94ue7",
      "sCityName": "Rajgurunagar",
      "sPinCode": "410505",
      "updated": "2023-10-04 04:48:05.824Z"
    }
  ]
}

**Comment by hariprasadms** [comment]
Hi, There is a wrong in your api query configurations on the page. Hence you are seeing the issue. Follow configurations as below,

Cities/records, endpoint is not returning list of objects. Items property is the list you should access to get the list of cities.

<img width="283" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/dd52df99-9d14-4db8-b1ce-a77e0a892c8f">

<img width="583" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/7101b3ed-cd1b-4e47-a8c2-61e3a6736ff1">
