### ISSUE TITLE
Can't able to change the authenticated user email address in firebase authentication using flutter flow

### ISSUE THREAD

**Issue by Hitisha14** [FlutterFlow/flutterflow-issues#1588]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have inserted everything that's needed but then also not able to change the user email id in the authentication in Firebase, it is changing in the Firebase database only not in authentication I tried to implement the login, and logout options as well but then also I can't able to fix that, plz let me know what needs to be done.

### Expected Behavior

the email address should get updated in the authentication firebase  as well, not only in firebase database. 

### Steps to Reproduce

1.Create page
2. Enable firebase and auth
3. Add user to firebase
4. Add textfield and button to the page
5. Add action on button to edit email
6. Choose textfield to new email
7. Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlMjf35dOpbxA+Kr9bfpV+TgXOWY1U4ZMitZxSko0fZfNGu4MPsneVFRuZrymdEFif1qZkmUK7PfqkvLhVO5fIS6sGd1E/7tqeALJTj6tM5CJBYeRfW1QGd5gGUCF1sK32hUlXeluSCxk2EyuefPLcB3DGb37OVY/PPK1KdeK2SrDX1iXc2URm05KZDPz

### Context

I want to update the email of my user directly in the app, and that i wanted to get updated in the authentication as well

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/09314123-0507-48c9-a0ab-23cb40ccbbc0)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/51d72e90-dd13-4731-98be-380bd06331be)

### Environment

```markdown
-FlutterFlow version: 3.1 20 july
- Platform:web
- Browser name and version: chrome 1.54
- Operating system and version affected: windows 11
```

**Comment by Hitisha14** [comment]
please can you resolve it as quickly as possible?

**Comment by hariprasadms** [comment]
Hi @Hitisha14 - Thanks for reporting the issue. I can reproduce the issue.

**Comment by Hitisha14** [comment]
Hi, @hariprasadms Thank you for confirming that you can reproduce the issue. I appreciate your prompt attention to this matter. If you need any further details or logs to assist in diagnosing and fixing the problem, please let me know. I'm here to provide any additional information that might be helpful. Looking forward to a resolution soon.

**Comment by DhruvalGolakiya** [comment]
Any update on this I'm also facing the same issue

**Comment by sbis04** [comment]
The issue is due to a breaking change from Firebase: https://stackoverflow.com/questions/77147854/firebase-please-verify-the-new-email-before-changing-email-auth-operation-not

We have updated our implementation to fall back to `verifyBeforeUpdateEmail` in case `updateEmail` fails. And, when `verifyBeforeUpdateEmail` is used, the user will receive a verification link on the new email, once that's opened it should update the email used in Firebase Authentication.

This should be fixed in the next release!

**Comment by DhruvalGolakiya** [comment]
So what can I do now If I want to add Update Authenticated user email from App in flutterFLow?

**Comment by braininsolutionsza** [comment]
Hi, I am currently experiencing this issue now. Was there a solution?

**Comment by DhruvalGolakiya** [comment]
Hi, you just need to make sure your email is verfied before updating it or change it there is also one method for verifying your email for google login it will automatically verify your email for signup you need to add logic for verify it during signup using otp or something then you can update email using flutterflow update method
