### ISSUE TITLE
Conditional statements not working

### ISSUE THREAD

**Issue by erok415** [FlutterFlow/flutterflow-issues#1590]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set a simple condition on a component such as an image, the conditions don't work. In fact, I even cloned this project to test the NavBar and the conditions don't work in this app either https://app.flutterflow.io/project/custom-navigation-final-s47c9d

### Expected Behavior

I expect that if I create a condition, the condition will work.

### Steps to Reproduce

In my new account on Flutterflow, I've created a new application.

1. Create a component.
2. Define a parameter "setPageIndex"
3. Add one icon to the component.
4. Click conditions next to Opacity.
5. Select "Conditional Value (if/then/else)
6. Click Unset, Conditions, Single Condition, click Unset, then select "setPageIndex", and confirm.
7. For the second value, write "1, confirm.
8. Not for the true value, set "1," and for the false value, set 0.5 and confirm.
9. Duplicate the first icon, go to the opacity conditions, and for the "setPageIndex" write 2 and confirm.
10. Create an action for each icon to navigate to a page where you include the component.
11. Add the component to two pages and on the first page, write "1" in the setPageIndex and "2" in the second setPageIndex field.
12. Run the application and you'll find that the conditions change opacity based on 
![FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/8429801/83b54cc4-917a-4c32-b327-47b29f2de076)
when you move from one page to the next.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

1111

### Context

I'm unable to use conditions.

### Visual documentation

![FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/8429801/c71c760a-11a4-4b0f-acac-9e0f56b3944d)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Apple
- Browser name and version: Chrome Version 117.0.5938.149 (Official Build) (x86_64)
- Operating system and version affected: Testing mode
```

**Comment by erok415** [comment]
It turns out that conditions only work in Test or Run mode and not Preview mode.

**Comment by hariprasadms** [comment]
Hi @erok415 - As per your last comment, I presume conditions are working in run and test mode. In preview mode conditions does not work. The reason is project code does not trigger any logics in preview mode as it is just a preview mode.

**Comment by erok415** [comment]
I feel like somewhere in the app it should state that. It would save a lot of time trying to solve logic issues.

**Comment by wenkaifan0720** [comment]
@erok415. You are right. We should add a tooltip somewhere stating this.
