### ISSUE TITLE
Error: Failed to generate project code [ Push to Repo ]

### ISSUE THREAD

**Issue by jasminder** [FlutterFlow/flutterflow-issues#1591]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project has no errors, The code is downloadable. 
There is no permission error with Git. 
When pushing to git, throwing an error: 
![sc](https://github.com/FlutterFlow/flutterflow-issues/assets/1322355/11793932-5c4a-4d38-896e-a7645c9cfff6)

### Expected Behavior

Should push to repository

### Steps to Reproduce

1. Project id is roster-aak06p
1. Goto Setting and Github and try to push to repo.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Trying to push to Git

### Visual documentation

![sc](https://github.com/FlutterFlow/flutterflow-issues/assets/1322355/c1dfadb4-1869-4ab4-8626-802c40344cd7)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mac
- Browser name and version: Chrome latest
- Operating system and version affected: Mac OS
```

**Comment by jasminder** [comment]
Some more details from the network requests : 
<img width="1045" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1322355/eac8d9ec-c78c-48c9-b826-a6df9f8441c6">

**Comment by hariprasadms** [comment]
Hi @jasminder - Thanks for submitting the issue. I just tested push to git repo working status in other project. It is working fine. Share the project bug report code. With out these details we are not able to investigate the issue. Once you have shared the required details, we can start investigate the issue. Thanks

**Comment by jasminder** [comment]
Hi @hariprasadms , Even for us other apps works fine. 
The issue is with this particular project. How to get the bug report code from the Github button ?
Please [DM](https://twitter.com/Singh_Jasminder) your email, i will add you as collaborator or check at your end.

**Comment by jasminder** [comment]
I was able to reproduce the bug. 
Please check this video : 
https://www.awesomescreenshot.com/video/21336365?key=bcc1143231e84c0ef51c6532a1a34b14
Let me know if you want me do this on a fresh project.

**Comment by hariprasadms** [comment]
Brilliant. Thanks for the video @jasminder I will re check and confirm shortly.

**Comment by hariprasadms** [comment]
Hi, I can confirm this is a bug. I am able to reproduce the issue. This happens when trying to update toggle values using  toggle form controllers in actions.

<img width="1540" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/48ab3352-5f2f-4c0b-bd28-eddece798f2d">

**Comment by jasminder** [comment]
Thanks @hariprasadms . Looking forward for a fix.

**Comment by agreaves** [comment]
Hi @jasminder, thanks for the report. Closing this issue as it appears to already be fixed! However, please let me know if this is not the case and I'll reopened. If so, please include a Bug Report Code!
