### ISSUE TITLE
Calendar running "on date selected" action when initializing

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#1593]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- when using the calendar widget and setting an on date selected action this action gets run when the calendar loads
- vs only when a user selects a date

### Expected Behavior

- expected to not run on init, if you have an action that says "closes dialog" when the calendar loads it immediately runs and closes the dialog
- i have added a conditional to check if it is primed but this leads to other issues if it is on page and a user can select multiple times, and say the calendar hides, then when it loads again the on init action is run again so to get around this you would have to create a component around the widget to store init state each time

### Steps to Reproduce

1. create a page with a button
2. on button click show modal with calendar
3. have on selected date action to close the modal

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si87huJJOxLRb+KrAb/l7/Cc4OW46ROcwscp8bxAbCIzrBJkAdvWkQFtoOdOqdGw3JESmmlwKps7MkePhNcACIQ2tG6p4z6VibgnMLU6hQZOBPqqNP2hBO9xVIH3C1rbU3yZDLtpYc0Zm2mWIfu6/XiztJJCzImdISq/LZO4=

### Context

im using calendar widgets in a few places and having to add checks or components when not needed complicates the building process and logic

### Visual documentation

- no video

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: chrome
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @trevorFields - Thanks for submitting the issue. I can reproduce it.

**Comment by takashiff** [comment]
Hi @trevorFields, we have recently put in a fix for this issue, and it should be reflected within the next few weeks. Thank you for your bug report and your patience.

**Comment by Mattmannn** [comment]
It's not fixed, I'm running the latest version of FlutterFlow and this exact bug - executing OnDateSelected on widget initialization if Initial Date is set - is still very well present.
