### ISSUE TITLE
Custom code is no loading

### ISSUE THREAD

**Issue by ruvart** [FlutterFlow/flutterflow-issues#1594]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It started today, When i try to open some custome code, like custom action or custom function the code editor remains black, not a single line of code is shown (in the tag Function code).

I also can't create any new custom functions or actions.

I can try switch to any otrer function or action with the same result, I can also opens the views because the rest of the IDE seems to work, just the code editor that remains in black.

### Expected Behavior

When i open some custom code the editor is supposed to show the code so I can edit it

### Steps to Reproduce

Create new proyect
try to create new custom action or custom function
try to edit custom action or custom function

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ChfHl7c5NobxA7qqNKcF7/TgWNjN6a+YwltZQEA41GO7qB413YuHBPlZvY7SkY29YPE78o1gVwtbVheP9D8FdKRaXUYRnwpNQWDvwUn+zaq6zErW7dn9BJ5pQfVyF0pmvnBZBCOpsR1Ye23KtLO7LVgLbJ4DoIkURJs6IOt77olabG3rrUyFqvhY+IGKbCa46VBGRyM+UtpJh0eDnyw==

### Context

I can't progress in my project and I'm starting to worrying if I can loss my custom code that I already created

### Visual documentation

![Captura de pantalla 2023-10-05 133519](https://github.com/FlutterFlow/flutterflow-issues/assets/1543011/30853a3b-06df-4372-94ec-0ad66a5d97ec)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform:web
- Browser name and version: chrome Versión 117.0.5938.134
- Operating system and version affected: Windows 10 Pro 22H2
```

**Comment by hariprasadms** [comment]
Hi,  I looked at your project. Custom code is loading fine. No issues. Are you still experiencing the issue ?

**Comment by ruvart** [comment]
Hi. Thank You for your answer.
Since last night I don't have this problem. I don't know if it was the browser, the pc or the flutterflow app or a bug that you solved, but it seems to work fine now.

Thankyou for your support
