### ISSUE TITLE
Checklists unchecks when checked checklisttiles go off screen.

### ISSUE THREAD

**Issue by NielAgi** [FlutterFlow/flutterflow-issues#1595]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![chrome_1BkxquoxBq](https://github.com/FlutterFlow/flutterflow-issues/assets/41204235/9c4223e4-5f12-45c2-b629-db16fdfc6cce)
I check a checklistile.
I scroll down so it goes off screen. 
Seems like you need to scroll a little bit more.
You scroll back, checklistile is unchecked.

### Expected Behavior

Checked items stay checked

### Steps to Reproduce

I **haven't** been able to reproduce it in other projects.
I make a component with a checklisttile in it and then put the component in a listview passing parameters.
Henry said it's an issue with listview.

![F427rA0Yo6](https://github.com/FlutterFlow/flutterflow-issues/assets/41204235/7bbc5d13-e0ee-4d83-9d9b-02b8cfb1637c)
In tablet mode go to OpstartProcedure screen by pressing sun icon

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TlvLqx491j7xA0Lr+asJViiU5Jjsna7g7jO1+dw0dDOquPbMAYsmkNnFJYcukTFVcIWKZ/Wcz+KHSvYbfCscoYEyVU4NezKtUdwzyYD6VVbHWOpeCOEYkN95bI1S/yrSCmA9dANhpS00u7F+UHdnKcBfXQbrFOzIRQfmYKqjOs3S4GiLFKSZ7wmNecCfn

### Context

How has this issue affected you?
I forget what I checked.
What are you trying to accomplish?
make a checklist that remembers what I checked so I don't have to.

### Visual documentation

![chrome_1BkxquoxBq](https://github.com/FlutterFlow/flutterflow-issues/assets/41204235/4fa19735-42b9-4ded-a322-b0dec8d20135)
![F427rA0Yo6](https://github.com/FlutterFlow/flutterflow-issues/assets/41204235/7bbc5d13-e0ee-4d83-9d9b-02b8cfb1637c)
In tablet mode go to OpstartProcedure screen by pressing sun icon

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: web
- Browser name and version: all
- Operating system and version affected: windows 10
```

**Comment by SameerShahzad99** [comment]
Thank you so much for reporting this issue, i was able to reprodue this on my end!

**Comment by NielAgi** [comment]
I managed to reproduce it in a blank project by not wrapping the listview in a column
IT4Szsnfx5B2ocNC1aqNd+9Vgj8vJkQ9a5IRmOtqEAgYIrb2P5oTXOjDflJvOdeFT2xYelv9kj8fwNrLheDxUOQHAE2cY6JZ+ZZqZBXheEaVbr2bOqqoenwnBdhUJEuV4KWNrwl/IvZ1SVJn3F77JdyvfBfUQKbENmszJ+b9MrnXjFafAi+6Xn0Jg1ZSfCvr

**Comment by wenkaifan0720** [comment]
Hi @NielAgi. This is not a bug but rather how Flutter behaves. A list view will dispose invisible items to save memory/increase performance, which in this case means the checkboxes are disposed and their internal state are lost. If you want to keep the checkboxes states, you should store a list of boolean at the page's level, and manage these booleans instead.

**Comment by NielAgi** [comment]
Can you recheck if this is intended?
https://app.flutterflow.io/project/unchecking-checklist-ijiah5?tab=widgetTree&page=checklist

I changed the test project.
On the start screen you will see 2 buttons and a listview wrapped in a column:
-The top button brings you to a listview of checklisttiles. These **stay checked** when they go off screen.
-The bottom button brings you to a listview of a component that contains a checklisttile. These **uncheck** off screen.
-The listview on the main page is a listview of a component that contains a checklisttile wrapped in a column. These **stay checked** when they go off screen.

How is this intended behaviour?

**Comment by wenkaifan0720** [comment]
Could you add me (wenkai@flutterflow.io) as a collaborator to your project so I can do some testing there? Or could you increase the item height on the main page and see if the tiles still stay checked?

**Comment by NielAgi** [comment]
Is this issue still being looked at?

**Comment by wenkaifan0720** [comment]
Hi. I noticed that you checked shrink wrap in the list view on the homepage. This will make the list view behave essentially like a column (no caching).

**Comment by NielAgi** [comment]
> Hi. I noticed that you checked shrink wrap in the list view on the homepage. This will make the list view behave essentially like a column (no caching).

I don't see any different behavier with or without shrink wrap.

**Comment by NielAgi** [comment]
The unchecking only happens when you use a component of a checklisttile but if you just do the same thing without using a component than it stays checked.

**Comment by NielAgi** [comment]
Is there any explanation for this yet?

**Comment by wenkaifan0720** [comment]
Hi, as I have mentioned, enable shrink wrap will make a listview not caching items, thus the state of the checkboxes will not be lost. The UI will look the same, but the underlying caching mechanism changes.

**Comment by NielAgi** [comment]
This seems to work in the test project but doesn't work in my main project

**Comment by Mr-G254** [comment]
Hi, the solution is to use a SingleChildScrollview instead of the listview. Place a column inside the SingleChildScrollview then add the checkbox
