### ISSUE TITLE
Warning: Assetsize exceeds 20 MB - File does not exist in Assets

### ISSUE THREAD

**Issue by DavidWalters123** [FlutterFlow/flutterflow-issues#1597]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get [this](https://www.dropbox.com/scl/fi/8kv3av84xgrblg9c4rhuf/image-2.png?rlkey=r6m8103oundye8i90dzueem8l&dl=0) and [this](https://www.dropbox.com/scl/fi/0fwohkx2gn70zbq0w9b7x/image-3.png?rlkey=hu4o8ugttpjcokf72v3oisteg&dl=0) warning. This file does not exist in the Media Assets section.

I duplicated the project and deleted all assets but the warning still persists.

### Expected Behavior

No file -> No warning. 

### Steps to Reproduce

The steps potentially cant be reproduced from a blank project. 
Go to the Media Assets and search for file mentioned in the screenshots. 
![image (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/28622235/92fa118f-7420-401e-a989-6cee8c48286f)
![image (3)](https://github.com/FlutterFlow/flutterflow-issues/assets/28622235/1afaba0c-f87a-46c8-aad0-0225714268bb)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wz8r13ItIobhA1oSJc8EwtCMvJkR/aI0njsN+ZEoaCJOtOowPXfikSEpWZ9+kTHxcL1mahTsz06nFhYaTA+UoaEidbpxN1Ll2cgKVczu6M76oCLiwdHZRP5lJJVyZy7aG3SRSOfhoSUYM2F+mBfCiTXbaQLrJDkQzMs6KGIL4nWOqQ0SLb3kNh1JWeC/v

### Context

Im trying to get my Warnings section empty and eliminate anything causing performance issues. 

### Visual documentation

![image (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/28622235/b99975c3-af4f-49e2-b5c7-88a82fc3a7d7)
![image (3)](https://github.com/FlutterFlow/flutterflow-issues/assets/28622235/2befda84-db6e-4725-b917-ff50e8708f71)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: both desktop and browswer
- Browser name and version: Brave / Chrome
- Operating system and version affected: MacOS Sonoma 14.0 / MacOS Monterey
```

**Comment by wenkaifan0720** [comment]
Hi @DavidWalters123. Could you make a run mode/web publish/apk download? I think this will pull the latest asset analysis info on your project and may remove these warnings.

**Comment by DavidWalters123** [comment]
Done and the "total asset size" warning is gone but the "963 asset is too big" warning is still there.

**Comment by wenkaifan0720** [comment]
Somehow the error image in app assets is mistakenly set to this mp4 file. Could you try delete it and do another run mode/web publish?

**Comment by DavidWalters123** [comment]
I mentioned in the bug description above: This file does not exist in the Media Assets section.

I've told this to support many many times but for some reason this is not being understood. The file does NOT exist. That is the core problem. Please acknowledge that there is not a single file in the media assets. Therefore there should be no warning.

**Comment by wenkaifan0720** [comment]
Hi @DavidWalters123. A FF project contains assets not only in the media assets tab. The asset you saw is in App Settings -> App Assets -> Error Image. If you clear this image, I think the warning would go away. I can do it for you if you add me (wenkai@flutterflow.io) as a collaborator.

**Comment by DavidWalters123** [comment]
Thanks again but there is nothing there. I have added you as a collaborator.

**Comment by DavidWalters123** [comment]
I see the warning is now gone. We have the same issue in the other project I just invited you to. Id appreciate if you could remove the warning their too. Thanks.

**Comment by wenkaifan0720** [comment]
Done. Since I think this is a project specific error (a .mp4 file is not allowed in the app asset error image now), I will close this issue.
