### ISSUE TITLE
When using ListView and Widgets like TextField and RatingBar they will act as one Widget instead of separate ones

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#16]
## Expected behavior (required)
If I use a RatingBar component in the children of a ListView, I expect to be able to click and rate each generated RatingBar independently.

## Current behavior (required)
When I click to edit the rating of one child, all other children in the ListView are also changed.

## To Reproduce (required)
1. Create new page
2. Add ListView or Column
3. Generate Children via DB query or Generate Dynamic Children from Variable (ensure more than 1 child will be generated)
4. Include a RatingBar component in the Child (it can be a sole child, or within a more complicated container)
5. Run the app and change a rating in one of the generated children
6. You should see all the generated children change along with the one you interact with.

## Context (required)
In my use case, a single entity has multiple categories in which you can rate them. These rating categories are also dynamic, so they are not always the same and must be constructed from a database query. I want to create a list of Categories each with a Rating to allow the user to rate an entity granularly, based on particular characteristics. 

## Your environment
Your environment
* Version of FlutterFlow used: FF V3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 105.0.5195.125 (Official Build) (arm64)
* Operating system and version: MacOS 12.4 (M2 chip)

**Comment by bulgariamitko** [comment]
This issues was reported in the community originally by Tom Bean, https://community.flutterflow.io/c/bugs/generated-dynamic-children-with-rating-bar-do-not-behave-independently

But I can confirm that this issue was there a long time ago of all kind of custom data widgets like TextField Widget and RatingBar Widget.

**Comment by winsonloh** [comment]
Yes, I'm facing the same issue as well when using SwitchListTile in ListView

**Comment by wednesdei** [comment]
I have experienced this as well. When generating a list using text input fields, all the input text fields are connected. Editing text in one propagates to all input text fields. Also, when using them to generate a list, setting the default values with variables is hit or miss, perhaps because of the connection issue.

**Comment by wenkaifan0720** [comment]
Hi all. This is a known issue in FF and we are trying to come up with a better solution, which is why it hasn't been fixed for now. For now, could you try making those widgets that need to keep their own states into a custom component?
