### ISSUE TITLE
Google Play Store Deployment Documentation No Longer Valid

### ISSUE THREAD

**Issue by glamourhammer** [FlutterFlow/flutterflow-issues#1600]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is not a bug per se, but it is a serious issue in that Google rendered the FlutterFlow/Codemagic deployment workflow obsolete. It is now impossible to follow the documentation and deploy to the Play Store as the API Access page within the Play Console was removed. 

### Expected Behavior

One should be able to follow the FF documentation to successfully deploy to the Play Store. This is no longer the case.

### Steps to Reproduce

1. Reference the FF documentation to [publish to the Play Store [https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment](url)
2. Reference the CodeMagic documentation regarding Setting Up Google Play API Access [https://docs.codemagic.io/flutter-publishing/publishing-to-google-play/#setting-up-google-play-api-access](url)
3. Note that Google has completely removed this function

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmA7ZFJn7wE0bXXYcdsrwMwJ0QlUIInj+0bWRMhfLKuE+0UPPT8T1tLYtfkfXw/JVWghnsFzMrPiuHuGsc6NTmqc4B/zpRXQQ3MTl6lbL6RO6ieWnZ7N8dTIFCM15mzohElNttYWVYi2V+AA/CdG3qCf9qOYwx5e6fDbOY=

### Context

I can not deploy to the Play Store due to mis-matched upload key signatures, and I cannot generate new key signatures following the FF documentation.

### Visual documentation

![Screenshot 2023-10-06 10 41 36 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92355591/87b6cf12-37e8-4552-8999-dd118df2c698)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Mobile
- Browser name and version: Chrome 118.0.5993.26
- Operating system and version affected: Android
```

**Comment by hariprasadms** [comment]
Hi, Thanks for letting un know these points. Its been routed to documentation team to take care.

**Comment by hariprasadms** [comment]
Hi, The doc is update to date now. Please check and let us know. I can close the issue. Thanks
