### ISSUE TITLE
Unplayable video when user is offline

### ISSUE THREAD

**Issue by caioamoedo** [FlutterFlow/flutterflow-issues#1601]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the application I'm developing, video players don't work in offline mode, as I didn't find a way to show an Uploaded File in Flutterflow's native video widget.

### Expected Behavior

The user should be able to upload and play a video while offline.

### Steps to Reproduce

1: Create a new page
2: Add a Video Player Widget
3: Create an action to save video media to the device
4: Click to configure the video type
5: Observe that there are only the "Asset" and "Network" options

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8r634pItbwE7aqNb+9ahj8vNlw/bZc0t9lETRMjGOPPPJkAOvfOTERDUum5T3NMME6gq2oW063WueDAUfYDA0mBc7ZM/7pqZj3wLTqnRYiMFJWgX2gnBftmCly61sCNpxJCVbJYZXgm3GWXNuTJdBTYJoDJDTMkDq/LZO4=

### Context

According to business rules, the application will also need to work offline, development ended up being paused due to this need that I was unable to meet.

The user sends a video that needs to be shown to them the moment they upload it, as well as temporarily saved on the device so that when the user connects to the internet again, the video is uploaded to the backend (Xano).

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/114263710/c38d2782-420e-44d1-abb8-31d3769ec7dd)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.134
- Operating system and version affected: Windows 10 Pro 22H2
```

**Comment by hariprasadms** [comment]
Hi @caioamoedo - Thanks for submitting the issue. When you say media file is saved locally, Can you explain this bit more to understand in what formate media file is saved? Any media file delivered throuhg network calls, it required internet access to play that inside the app.

**Comment by caioamoedo** [comment]
> Hi @caioamoedo - Thanks for submitting the issue. When you say media file is saved locally, Can you explain this bit more to understand in what formate media file is saved? Any media file delivered throuhg network calls, it required internet access to play that inside the app.

The video file is saved locally via the native Flutterflow action "Store Media for Upload". It may be referenced in the editor as "Uploaded Local File". But Flutterflow's native video player widget doesn't have the option to show an Uploaded Local File. This option is available in the image widget, but not in the video widget. 

I'm looking for a way to make this video uploaded and accessed offline, because as a business rule the application also needs to work with the user disconnected. And I'm not able to do this with Flutterflow. Can you please help me in any way to make this feature work?

**Comment by caioamoedo** [comment]
> Hi @caioamoedo - Thanks for submitting the issue. When you say media file is saved locally, Can you explain this bit more to understand in what formate media file is saved? Any media file delivered throuhg network calls, it required internet access to play that inside the app.

Hi, @hariprasadms. Thank you for the support!

The video file is saved locally via the native Flutterflow action "Store Media for Upload". It may be referenced in the editor as "Uploaded Local File". But Flutterflow's native video player widget doesn't have the option to show an Uploaded Local File. This option is available in the image widget, but not in the video widget.

I'm looking for a way to make this video uploaded and accessed offline, because as a business rule the application also needs to work with the user disconnected. And I'm not able to do this with Flutterflow. Can you please help me in any way to make this feature work?

**Comment by hariprasadms** [comment]
Hi @caioamoedo - To access the uploaded video file in offline is not possile in current version of FlutterFlow. It can be  a feature request. Please submit a feature request using feature request form under help section. Thanks
