### ISSUE TITLE
Supabase package not accessible in custom function testing

### ISSUE THREAD

**Issue by jarrydc22** [FlutterFlow/flutterflow-issues#1604]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We can use the supabase client in custom actions using SupaFlow.client but doing this in custom function causes the function to return an error and can't utilize the "Test" mode. The supabase package (import '/backend/supabase/supabase.dart';) is included in both so it shouldn't return an error on the function.

If running test mode before checking custom functions everything loads and it works, same with testing on device. The big issue is that if you run the function check you can't then run test mode as it blocks you. This essentially makes running test mode impossible moving forward even though the function works correctly. Seems the supabase package isn't being imported correctly making it useless in the custom functions testing.

### Expected Behavior

The Supabase package should import correctly in custom functions so that SupaFlow and subsequent actions from it are available in custom functions the same way they are available in custom actions.

### Steps to Reproduce

1. Create a custom function.
2. try to use Supaflow.client to create a supabase client.
3. Use any of the actons/features available for supabase.
4. try to test without saving (in test mode or on device) the function works (if the code is correct)
5. check functions which returns the error
6. then try to run a new test mode (it blocks it due to the error)

In my use case currently I'm accessing the authenticate user's appmetadata field as I have a field that includes if a user has marked their account for deletion so they can't login anymore (data isn't deleted for 7 days to allow them a chance to reinstate their account if they change their mind or someone else tried to delete their account).

bool? userDeleteValue() {
  /// MODIFY CODE ONLY BELOW THIS LINE

  final supabase = SupaFlow.client;
  final session = supabase.auth.currentSession;
  final user = session?.user;
  final appMetadata = user?.appMetadata;

  if (appMetadata != null) {
    print(appMetadata['delete']);
    return appMetadata['delete'] as bool?;
  } else {
    print('No session or user found');
    return null;
  }

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci+flsYtOj7xB+KX2KMBFijksKUQjRYEzje59bEkjDZPND+x/esnRQFJuZ9OrdghiPU2j+Xox7snGm9z1L/ZfMgecGr5I1LgBTw7jQj+6Vq63OqigXmtUGshhIVTG1rSOkRB+OsR2WEVm7zuPfOyuYAXtN5OzDlgRR+WLJoTXmAfuQ0SLb3kNh1JWeC/v

### Context

This issue breaks test mode as you can no longer use test mode due to Flutterflow thinking there's an error with the custom function even though there's no issue and it works.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/123430021/bb681b94-f3aa-4978-9d05-83c2106525df)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/123430021/3aecaced-a494-49fd-96f8-a7d91095ec93)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Edge Version 117.0.2045.47 (Official build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by jd-bell** [comment]
Are there any updates on this issue?   I'm seeing the same behavior.

**Comment by katherineqian** [comment]
Sorry I didn't provide an update! I made a fix to this and it should be released within the next 2 versions.

**Comment by rdawsonsdp** [comment]
Is this fixed in the current release of FF?

**Comment by katherineqian** [comment]
Yeah, it should be fixed -- are you still encountering the issue? If so, can you please provide a bug report code?

**Comment by katherineqian** [comment]
Oh, thank you for sharing this screenshot, super helpful -- that's the same issue as #1951 and #1943, which I'm currently fixing as we speak. Feel free to follow those and I'll leave a comment there with an update.

**Comment by yabir** [comment]
I'm still getting this same error. Is this solved ? Anyone has a workaround ?
