### ISSUE TITLE
Dynamic Link Deeplink opens all pages twice

### ISSUE THREAD

**Issue by nick-chargely** [FlutterFlow/flutterflow-issues#1606]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Every link generated is opening the destination page twice - this requires user to back out twice and it's firing off all logic in the `addPostFrameCallback` twice

### Expected Behavior

It should only open once

### Steps to Reproduce

1. Create a new page
2. Create a button
3. Add widget logic to generate on click
4. Add logic to share the link
5. After you share back out of the page - back to root
6. Where you send it -> click on the link 
7. you will see the page load twice 
8. you now need to back out twice

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr1z4Z2xNtD0a6Jbe9alSQWMjsmULgZl+4acCs9f5ToPJYQe8/6P1tvOcPhTVY7PWKMp14zp+j3jt7hU/Q7EzCcbJxGzKhIbz3jfH+RVJuTF7WafUckP5pjI0PF5MCRsBV4ItZpSGQX216QCvOsST3BNLL2PVQ8Sq/LZO4=

### Context

every page required backing out twice 0- bad user experience

The most critical is i have a referral handler page which only allows them to use a referal link once... this is causing the second load to show error even if the first load was successful

### Visual documentation

n/a

### Additional Info

This has been happening for a while. I thought for a bit that it was my logic but then i noticed ALL the links were doing it. So i went back to the base flutterflow branch where none of my custom code it and it was still doing it. Then i created a base and noticed it was still doing it. So this is definitely something in the handling. 

### Environment

```markdown
- FlutterFlow version: 4.0 
- Platform: Android
- Browser name and version:
- Operating system and version affected:
```

**Comment by nick-chargely** [comment]
Adding this on line 80 in `firebase_dynamic_links.dart` fixes the problem - seems like the dynamic links are deeplinking and then firing off the same action via the firebase listener. 

`
if(widget.router.location != location) {
      widget.router.push(location);
    }
`

<img width="687" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/597ba5ec-fde0-4ed1-8783-a0d48fc5009d">

**Comment by nick-chargely** [comment]
Any updates?

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This issue has been resolved and should already be live. As such, I will be marking this as closed. If this issue persists, please feel free to follow up in this thread. Thank you for your patience.
