### ISSUE TITLE
ListView Scrolling Issue in FlutterFlow Applications

### ISSUE THREAD

**Issue by DevKursat** [FlutterFlow/flutterflow-issues#1607]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When scrolling down in the ListView on the iOS version, it throws out of the application.

### Expected Behavior

I expect it to scroll down in an ordinary way and not throw it out of the application.

### Steps to Reproduce

1- Open the application on IOS.
2- Click the button in the middle of the navigation bar
start scrolling down.
3- You are kicked out of the application.

(On iOS, Firebase also kicks out of the application on writes)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeyfLl05NPn7xJ16X1LccwmQMwJHI/auYvte5+d0shfJD0P7M+d8n4YhNLYteAS1ZAHmCLkmcJp/TXv+LtEfYBGzirRohd/75XQQ/zVXyQbKapC6madWslP8BPCmqB3J2r2ApAPvt0S04S32GqevCrG3qCf9qOYwx5e6fDbOY=

### Context

I have received hundreds of complaints from my iOS users and I am very bored. I aim to use my application without any problems.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/141324500/2551848f-153f-40a1-ac51-1e7d74e57ab8

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: IOS Mobile
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
Hi @DevKursat , The bug report code that you shared does not seem to be from a blank project with an issue setup, can you please check if it is reproducible on a blank project, yes- please share the project URL for that.

**Comment by DevKursat** [comment]
On Apple, it crashed when infinite refresh was active, but when it was
turned off, the crash stopped, but for those who still want to turn on
infinite refresh, you can check it. Data from Firebase is shown in list
view. Crashes on iPhone when infinite refresh is on.

SameerShahzad99 ***@***.***>, 13 Eki 2023 Cum, 22:51
tarihinde şunu yazdı:

**Comment by SameerShahzad99** [comment]
I understand but, as I mentioned in the previous message, please attach a blank project with the issue reproduced, if it is not reproducible, you should react out to the support at support@flutterflow.io or live chat!
