### ISSUE TITLE
URL Clicks in HtmlView not working

### ISSUE THREAD

**Issue by awarsing** [FlutterFlow/flutterflow-issues#1608]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Properly rendered HTML with NO clickable links

### Expected Behavior

HTML renders correctly using various methods, with clickable links

### Steps to Reproduce

Using HtmlView widget, FlutterFlow v3.10.4

### Testing Examples
The first paragraph in the image below is text from the API response (which is from the default WordPress API), into a custom function that removes all HTML tags except `<p>` tags.

The second paragraph in the image below is the same text from the API response, into a custom function that removes `<iframe>` and empty `<p>` tags.

The third paragraph in the image below is from pasting test text direct into the HtmlView box.

Only the third example is clickable. (I also took the test output from the custom function and pasted that into the HtmlView box, and the links were clickable.)

I have tried setting the return value from the custom function as a string and JSON, both fail to produce a clickable link.

I tried the Text Combination widget and added this code to the first text entry, then the return value from the same custom functions as above, and it renders, but no clickable links (see second image below):
`<head> <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet"> <style> h3 { font-family: 'Open Sans', sans-serif; font-size: 80px; font-weight: bold; } p { font-family: 'Open Sans', sans-serif; font-size: 16px; line-height: 1; } </style></head> `

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlMrl05JNocMB1rXpbcExjiAXHGY5a7swlut9Z0o2C4z0G7YARsnRN1FaZ+m+Sgo2e06j+ToKpvzPv/bIN/YnFyWVGpxnz7VcTAzjVmauaaamEbjhZGpTINpKClyx1p7YpgonObJoSVoE7TmQIunLVh7dJrruOWoRPfiLKdr4o3/uQ0SLb3kNh1JWeC/v

### Context

- I want to have text from a WordPress blog, via an API response, displayed in the HtmlViewer widget.
- Each step works properly as expected, except for the URL links are not clickable.

### Visual documentation

![screenshot - 000246](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/ddc97655-b571-479e-8301-4d3079b87004)
![screenshot - 000247](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/c704219a-0fa7-42e7-b309-b1dc85b8fbcb)

### Additional Info

It seems with any method to populate the HtmlView widget with a string fails to produce clickable links, except for a direct paste of HTML code in the widget input box. Any use of 'set from variable' fails to produce a clickable link.

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS
- Browser name and version: Chrome, version 117.0.5938.132 (Official Build) (arm64) 
- Operating system and version affected: macOS Sonoma 14.0 (23A344)
```

**Comment by hariprasadms** [comment]
Hi @awarsing - Thanks for submitting the issue. I looked at your project. I tested the html content with hyperlink. I can confirm that hyper links are clickable in run and test mode both. 

Considering your project data source is wordpress api content and its data structure, I would suggest FF support team is the primary contact to investigate the issue. Considering the nature of bug, it is required more effort to investigate and validate the correctness of configurations. 

In the get repo, we can only determine whether an issue is a bug or not.  I can say it is not a bug because the hyperlink in HTML is now working as intended. Contact FF technical support team and see whats they would suggest. Thanks

**Comment by awarsing** [comment]
Here is a new, blank app with one htmlView widget and one `<a>` tag in an App State variable.

https://app.flutterflow.io/project/html-view-test-u5h8nm



https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/74cded1e-aa5e-49ee-b032-602113a071a8

![screenshot-000117](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/7b6387c3-63ad-4c65-a036-a0d6b7009e13)
![screenshot-000115](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/3a1ba764-4ccd-406c-9cc8-afbc85a20b67)
