### ISSUE TITLE
Checkbox doesn't have option to be read-only

### ISSUE THREAD

**Issue by codeorlov** [FlutterFlow/flutterflow-issues#1609]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Checkbox doesn't have option to be read-only.

### Expected Behavior

Checkbox has to has option for be read-only like other form widgets like radio.

### Steps to Reproduce

1. Create new page.
2. Add checkbox widget.
3. Find option for set checkbox to read-only.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcr135VNxMdG0b6JKsB4qCo4NUccTIAzjdV+bwogIuOqBqQAdeDCYVhvZNe+aVNfelr+o3MK0dLMvuHfUfEDEyyWc7ZyysxUcQz0e2itVqaIBpGVP39AP8JWCkyh1piZhCQlGM9oLHA93161NtmySgzDBOu/Zwh9f6PHaOI=

### Context

I want to disable my checkbox for selection using variable.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130235685/899f24d5-98b7-4fdd-aae4-1927e5f82096)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: All
- Browser name and version: Chrome 117.0.5938.149
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi - Thanks for submitting the issue. This is as per current design. This should raised as feature request. Thanks
