### ISSUE TITLE
Phone Authentication - Custom Routing Fails

### ISSUE THREAD

**Issue by mustaphaarakji** [FlutterFlow/flutterflow-issues#161]
https://intercom.help/flutterflow/en/articles/6300011-custom-routing-when-a-user-logs-in

I'm following the above article, I need to route the admin user to the admin home page only if the "role" field is set to "admin". I have a condition on my "missiongControl" page to check if the user "role" == admin, this works fine, routing is successful, but it breaks the authentication persistance session. So everytime the user closes the web browser and open it again, he will need to go through the authentication process again. The expected behaviour for the authentication session to persist.
If I remove the condition on "missionControl" page, the authentication session persists successfully.

## Expected behavior (required)
Authentication session should persist, even if I have a condition on the "missonContorl" page.

## Current behavior (required)
Everytime the user close his browser, re-open it again, he will need to authenticate, enter his phone and sms code.

## To Reproduce (required)
Simply follow this guide as documented by flutterflow team: https://intercom.help/flutterflow/en/articles/6300011-custom-routing-when-a-user-logs-in

1. create a phoneSignIn page
2. create an smsCode page
3. create a missionControl page
4. create adminHomePage
5. complete the usual steps to configure authentication
6. Configure authenticaiton in flutterflow
![image](https://user-images.githubusercontent.com/18700010/203872484-27a888ae-eed8-40f5-869a-d233956a86ea.png)
7. configure missionControl on pageLoad
![image](https://user-images.githubusercontent.com/18700010/203872538-b3f653fe-7f68-409b-8e4a-8d497a73429f.png)

### Bug Report Code
I've create a new project only to simulate this bug, here the Bug Report Code:

ITFficnf8cpIsdtK0L6JcO4w+WAUJk8cTIMziNZ+exUbfaL1Bu0XPMylSExBTbCjaVNcBlD+/ToCpvCOkfOWDsdcGyWtR4hi1pFUWw32KTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)
Authenticating everytime the user need to access the application will discourage him from using it, making the application useless.

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/18700010/203872538-b3f653fe-7f68-409b-8e4a-8d497a73429f.png)

## Your environment

* FlutterFlow: v3.0
* Platform: Web only
* Browser name and version: Chrome / Safari
* Operating system and version (desktop or mobile): Windows 11 (Desktop, using Chrome), Android 13 (Mobile, using Chrome), macOS 12.6 (using Safri)

**Comment by Pepino-GR** [comment]
Hi mustaphaarakji,

I think, this is the wrong place to get another new user login. The condition takes place, when a user is logged in.  If the admin user is logged in, you got the admin page. If another user is logged in, you should go to the main page of the app.

**Comment by mustaphaarakji** [comment]
Hi,

I don't want to register new users
Also this is admin app only, I have different app for non-admins.
I don't want anyone accessing this app unless he got the admin role.

Let me know your thoughts.

Thanks.

**Comment by Pepino-GR** [comment]
The condition takes place, when a user is logged in. If this is possible, you can do two actions inside the false part. First is to logout the user and then navigate to your Phone Sign In Page

**Comment by mustaphaarakji** [comment]
Ok, I did add a logout action as you explained, but I'm still facing the issue.

Issue: Every time I close the browser and open it again, I'm redirected to the login page.

**Comment by Pepino-GR** [comment]
Than your condition doesn’t work. It seems, that it is always false. Can  you please verify it?

**Comment by Pepino-GR** [comment]
Do you clean the browser cache, every time you close your browser?

**Comment by mustaphaarakji** [comment]
No, my condition is not always false, that's why I think it's a bug.

If I login having an admin role, I get directed to the home page, as expected.The problem is only when I close the browser.

No I do not clear the cache, I do Not clear cookies, I want the session to persist mate. I want my user to be able to go back to homePage after closing the browser without getting to login again.

To reassure it's a bug, i did the following: if I remove the condition on my homepage, the auth session persists even if the user closes the browser!

**Comment by Pepino-GR** [comment]
I cannot reproduce this issue. This is why I try to find out, what happened. It seems to be specific to your project. Can you please share your project or your website to troubleshoot.

**Comment by Pepino-GR** [comment]
Or please copy the page and the code of your missionControl page into a comment.

**Comment by mustaphaarakji** [comment]
Hi,

This is my project: https://app.flutterflow.io/project/onlytest-b3ntia
to test, you can go to https://onlytest-b3ntia.flutterflow.app/ (i've used flutterflow to publish it to web)
phone: +61421000000 (has the role of admin), code: 000000

I created this simple project just for troubleshooting this one issue, so feel free to edit.

**Comment by Pepino-GR** [comment]
I can reproduce your issue with your weblink. To look into your project, please share it with the share button to the public.

**Comment by mustaphaarakji** [comment]
Done. pleae check. Thanks for your time looking into this.

**Comment by Pepino-GR** [comment]
I can reproduce the issue with your project. It seems to be a bug.

**Comment by mustaphaarakji** [comment]
Ok cool, what is the steps from here? do you think we can put priority on this one, it's a big deal for me, I can't go live with my app with this issue.

**Comment by Pepino-GR** [comment]
The fastest way is to use chat support or contact support [at] flutterflow.io for further assistance

**Comment by Pepino-GR** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by hariprasadms** [comment]
Hi, As per @Pepino-GR last comment, please raise a new bug specific to your project. Hence we are closing this one.
