### ISSUE TITLE
Unable to open the google maps in trial mode.

### ISSUE THREAD

**Issue by kimo** [FlutterFlow/flutterflow-issues#1610]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Tried to implement by using an icon and action, Launch Maps, System Default and setup the location properly. No Feedback or errors reported. 

### Expected Behavior

Expecting the maps or browser to open and atleast do 

1. show an error that the keys don't exist or something
2. or show if there was any other error in being unable to launch the browser. 

### Steps to Reproduce

Followed the instructions here for the Travel Starter App. 

https://docs.flutterflow.io/actions/actions/widget-ui-interactions/launch-map

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xz8jfz812ofpE7qXQccFajiMvIjs1bZI7m+tudwE1GOKrO5kxOs7ET3ZfXcukTFBEeGeGmn0y+KDHkYbxC8EFBwysQ4Ne1bh2Fwr/Qka5b5COPbisRmh7N+hhFVSl15mKmA9SVdVsSVY82mCIfu68QgnfJYzzPmodGuSaOr/LnEnjGXnOUDhFxmNecCfn

### Context

Trying to test how the map works on browser on mac in Test/Run Mode in trial version.

### Visual documentation

Nothing appears including the errors and warnings. the button tap doesn't do anything. 

### Additional Info

Nothing appears including the errors and warnings. the button tap doesn't do anything. 

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Mac
- Browser name and version: Chrome Version 117.0.5938.149 (Official Build) (x86_64)
- Operating system and version affected: macOS Monterey 12.7
```

**Comment by hariprasadms** [comment]
Hi @kimo - I looked at your project. There is no google map keys are configured. Also I was not able to find a page where you got map widget. What type of map widget you are using?. Reproducible steps are not clear. Please update required details. 

When you use google map widget and no keys are configured, you should see below errors related to map configuration. 

<img width="479" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/71fb0ada-e21b-467a-8552-502db82307c9">

**Comment by kimo** [comment]
Thanks @hariprasadms . Let me read through your comments.

**Comment by kimo** [comment]
Thanks for your help.

**Comment by kimo** [comment]
Sorry. I closed the issues.  I know it's tough out there and all around.  opened it again. Don't know what this comment is all about.
