### ISSUE TITLE
Timer count down much faster than expected

### ISSUE THREAD

**Issue by DanyNaumann** [FlutterFlow/flutterflow-issues#1611]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a timer that count down in a drawer. The timer start when i launch the quizz. But when i close and open the drawer the time in the timer drops by 20s suddenly for example (it could be another value but much greater than the time the drawer was closed). If you repeat and open and close the drawer multiple times, it drops again and again really fast.

### Expected Behavior

The timer might count down correctly, if I close the drawer and reopen it after 5s, the count down might be 5s in the timer not a higher value.

### Steps to Reproduce

1. Put a timer in a drawer
2. Launch the timer
3. Close the drawer
4. Open the drawer
5. Do it a some times
6. The time count down much faster than expected

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiMrl8YlIsdhE15DucflKpyQUNUN9ROYkmspOFC0YGOvyPbJ/PMnsXBFvTfG+TFNhHFqZoFkyzPDJhd7DJ8crGEyafZxyzLhIegKWXXq8RLqOC8y0ZHRCQOdbGhGhyqWzuhFCCNVeW1IiwV6MGfOvSgrDJ5+/Zwh9f6PHaOI=

### Context

I'm trying to do a quiz with a timer which is in a drawer. You can see the remaining time by open the drawer and after you can close it to continue to do the quiz.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/46889325/5f015bb0-b324-4183-94de-607bf292aa09

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.92
- Operating system and version affected: Windows and MacOS
```

**Comment by DanyNaumann** [comment]
I still have the bug, why this issue has been closed ?

**Comment by sbis04** [comment]
Hey @DanyNaumann, The bug has been fixed but it's not deployed yet, should be available in the next update sometime in the coming week!

**Comment by DanyNaumann** [comment]
Hello @sbis04, after the last week update, I thought the issue was resolved. Today, I tested again and the bug is still present. I need to deploy in production this project in few days and this issue is really blocking for us. Do you have any information about this ?

**Comment by DanyNaumann** [comment]
Hello @sbis04, any news about it ? It's very important to us that it will be corrected very soon
