### ISSUE TITLE
Black background and labels missing in Running Test mode

### ISSUE THREAD

**Issue by helendeguinion1** [FlutterFlow/flutterflow-issues#1612]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon running in test mode the UI changes
- instead on white it becomes all black
- text in buttons, text fields and text widget is all gone
- some navigations is not working properly it does not call the correct action 

### Expected Behavior

The expected behavior should be the same in the preview mode all are visible and navigation is correct

### Steps to Reproduce

1. Create a screen
2. Create a separate component for navigation, forms and footer
3. use the created components on the screen
4. run in Test mode, the output should be the same in preview instead of having a black screen

Note: 

I've been using columns and list view, I found some question about it but the fix recommend is not working on my end which is replacing the column with ListView widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

nq

### Context

It greatly affect me since it is not showing the UI that I created, I inspect the console no error at all.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/40648263/a838b7c9-2104-4461-aeba-e8adc5b5e415

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web (Chrome browser)
- Browser name and version: Version 117.0.5938.149 (Official Build) (arm64)
- Operating system and version affected: Mac OS Ventura (13.4.1 (c))
```

**Comment by hariprasadms** [comment]
Hi @helendeguinion1 - Thanks for reporting the issue. Can you provide your project link please? Without project access its a bit challenge for us to investigate the issue. Please update required details.

**Comment by helendeguinion1** [comment]
@hariprasadms this is my first time developing using FlutterFlow is this the correct [link](https://app.flutterflow.io/project/p-c-n-travailler-p-a-r-t-o-u-t-jz68vp?tab=widgetTree&page=RegistrationPage) or I still need to grant you some permission?

**Comment by helendeguinion1** [comment]
Hello an update with this problem, turns out it is related to the app translation, it was fixed now all I have to do is set my translations, thank you for taking the time.
