### ISSUE TITLE
Bar chart compilation error

### ISSUE THREAD

**Issue by efficientaman** [FlutterFlow/flutterflow-issues#1613]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have tested the bar chart on FF and though it does not give project errors but at the time of build, it fails saying the type mismatch error. That is definitely an issue on FF chart widget. It has not allowed nullable values. This is the build error.
![Screenshot 2023-10-09 at 11 21 26 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/127823947/a6152e45-81c3-417f-a178-5e55e20a5493)

### Expected Behavior

The bar chart which I have created should run without any build error.
![Screenshot 2023-10-09 at 11 57 22 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/127823947/6e130b60-d28c-442c-bbc9-a143579c1440)

### Steps to Reproduce

1. Add a bar chart
2. Fill it with random sample data
3. And build it in run mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gk/Hf0491xOFc1pPpbcAwgj8XQzM8RYInm+0bFEg1GIzrBJ13fPfsTEtvXtSBalBAJlqWgjsIp/zHvvPhUcdcGw+IQ759wbV2egziUXGgR4ybCLq3OHdBHdNnI2Kc4YqOiiZCVcB1SF4XwzmEJt7LSibrJb6zCkUNLcmZEJrXs1ahAXjJVzhQtmNecCfn

### Context

It am trying to incorporate bar chart in my project and it is adversely affecting my production time.

### Visual documentation

N.A

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web app
- Browser name and version: Chrome
- Operating system and version affected: N.A
```

**Comment by hariprasadms** [comment]
Hello, Please reproduce the issue in a blank project and share bug report code of the same. Without these details we are not able to investigate the issue.

**Comment by efficientaman** [comment]
In the fresh project. I didn't get any error.
So I pushed the code to my repo and I saw those same 3 errors in flutter_flow_charts.dart file on Visual studio code editor. What to do now?

![Screenshot 2023-10-09 at 9 05 34 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/127823947/4d33f1ae-05da-44af-a907-557db13a9ff9)

**Comment by efficientaman** [comment]
It was due to dependency conflict between the custom widget and FF widget. It got fixed after removing the custom widget.
