### ISSUE TITLE
Problem with google map widget. Markers inaccessible within "OnMarkerTap" action when markers type is "LatLng".

### ISSUE THREAD

**Issue by santygarces** [FlutterFlow/flutterflow-issues#1614]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using the google map widget and I want to access the information of the marker that I am clicking on the "onMarkerTap" action, I am not being able to do that, the only thing I can access is the center of the map, which tells me which It was the previous center because the center changes after the action is executed.this happen when the type of the marker is "latlng"

### Expected Behavior

I should be able to access the marker which triggers the "onMarkerTap" action within the action and regardless of the type of the marker

### Steps to Reproduce

1. add the Google map widget on a page
2. in properties, select:
num markers: multiple.
Marker Type: LatLng.
Markers LatLng: "Select a list of LatLng"
3. Add on marker tap action
4. select  alert dialog action
5. on the title try the bind data about the map widget, the only data available is the center of the map

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://www.loom.com/share/f2ec3d78d87340a5ac6e6720966339c1?sid=65b9cdad-f780-4c5b-bc7c-b0018ef690fe

### Context

I have a map with markers that were dynamically generated with an API call, I need to be able to select them and trigger behaviors taking into account the selected markers

### Visual documentation

https://www.loom.com/share/f2ec3d78d87340a5ac6e6720966339c1?sid=65b9cdad-f780-4c5b-bc7c-b0018ef690fe

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform:web
- Browser name and version:Chrome 117.0.5938.149 
- Operating system and version affected: Windows 10 Pro
```

**Comment by mTorres95** [comment]
Hi, we still have this problem so we want to keep this issue opened until it gets fixed.

**Comment by hariprasadms** [comment]
Hi, Can you please reproduce the issue in a blank project and share the bug report of the project. These details are required to investigate the issue. Thanks

**Comment by hariprasadms** [comment]
I got what you are looking at this issue. As per the current version of this feature, it is working as expected. However this can be a feature/enhancement request. 

As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!

**Comment by nurzhands** [comment]
+1 needed feature

**Comment by katherineqian** [comment]
Hi @nurzhands and @santygarces, thanks for reporting -- as @hariprasadms has classified this as a feature request, I will close this issue. However, I wanted to direct you to the FlutterFlow Community Wishlist as well  (https://community.flutterflow.io/wishlist) where you can post ideas and have them upvoted by other users. We do look at this list for feature suggestions.
