### ISSUE TITLE
Chat widget isn't pulling User name anymore

### ISSUE THREAD

**Issue by antonyxshaw** [FlutterFlow/flutterflow-issues#1617]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The chat widget now shows "Friend" in the list instead of the users name, making it hard to know who you're about to chat with.

### Expected Behavior

Show the users name who you are about to chat with.

### Steps to Reproduce

Add the chat template and add the chat pages. 

Set up two devices, start a chat with someone.

Go the "All Chats" page 

The name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KXQL+1FlWIUI0MdXOczitVEew4bCIj4PJolP+LRchFCQtCzaH5qClb/mk4e+s7HkePpEvEEGwisbL5a/qt+TxPPbHGuR7awBpeKeHFQO8pXBXK456uJhBBSBO5hLk4uw2WECtiRRT2Cf9qOYwx5e6fDbOY=

### Context

It's hard to know who you are messaging as the name isn't visible. 

<img width="394" alt="Screenshot 2023-10-09 at 17 46 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7004991/69f76781-4c4b-4c4e-a369-fc3364a9ab6b">

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/7004991/55015df2-875b-48f8-a965-c79a00a3b995

### Additional Info

This is a recent issue, it's not clear what changed - also the widget limits what we can do with it so it's hard to solve from the flutterflow UI

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Chrome
- Browser name and version: Chrome + iOS Safari via xcode
- Operating system and version affected: iOS and Web
```

**Comment by hariprasadms** [comment]
Hi - Thanks for submitting the issue. The above given blank project does not have chat issue setup showing the issue. Can you setup the issue and highlight where exactly you are facing it? This information is very much required to investigate the issue. Thanks

**Comment by antonyxshaw** [comment]
Hi @hariprasadms thanks for your response.  After further investigation we found that if the "Display Name" field is empty, then the chat doesn't automatically fallback and show the First / Last name - instead reverts to "Friend". Which is slightly problematic for apps that don't use Display Name as a field. 

In my case i'm happy to close this issue.

Thanks!
