### ISSUE TITLE
My app appears fine in build mode but when I 'Run' its blending the text color with the background color

### ISSUE THREAD

**Issue by codewithjaidesai** [FlutterFlow/flutterflow-issues#1618]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My app is not showing any text when I 'Run' or 'Test' the application. The text is blending with my background

### Expected Behavior

when I 'Run' or 'Test' the application, the app text should be visible as it is in build mode

### Steps to Reproduce

Build a basic page for your app and create a list view where you are able to see the design and text 
Run it in the test/run mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Okcjfz89Nrt8B7rrtbcJv9WEWHD8na5ZNlexxYxE3CLXNG4gIZfTBXE9uOP25dghMO2aj8WIe/t6Nm9z1KMEqGw6aQKp9zpBuFA7wIUWmabKRDKuZP0R+GshXf36u0quJoCV7IvV1SE4C3E+Uf+vJdBXUK5D1C2w3Rea1JofXrgfuQ0SLb3kNh1JWeC/v

### Context

Yes. I'm trying to test my project by 'Run' mode.

### Visual documentation

[](url)
![Screen Shot 2023-09-28 at 11 18 23 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/143659176/b4222848-a707-43e9-9f00-537358dcda98)
![Screen Shot 2023-09-28 at 11 33 07 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/143659176/1b54d41e-8b9e-4799-89e9-c816d154344b)

### Additional Info

[](url)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: 117.0.5938.132 (Official Build) (x86_64)
- Operating system and version affected: Mac OS
```

**Comment by hariprasadms** [comment]
Hi, I looked at your project and did some adjustments around column widget in below page. It looks fine now. Its due to column widget was not scrollable. Its a layout design issue at your end.

<img width="404" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a869627e-dbfd-487b-899d-2300439da09f">
