### ISSUE TITLE
Can't select the "Data" in Database "Data Type"

### ISSUE THREAD

**Issue by dinasorz** [FlutterFlow/flutterflow-issues#1619]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't select "Data" from the "Data Type"

### Expected Behavior

-To be able to select a Data from a list

### Steps to Reproduce

-Database
-Create a new "Data Type" field, a "Data" field will appear but it's unselectable
-If you created it it'll write "Data (Unkown)" and will cause an error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojPLlvJFIocte7q6JccBKjSQsHH5+ap0nlMpBZywgfZdwaxzzBLN/fPfQPxBuUu2lTQlAJGacp14CzN7SiobXM8FdJTWsY4hczbVfWDvJUj2Wb6mTF7WKbWpBL9lMGWag052nvhNNKvpeWXAe1zuTON6XdCntGLrHPWo8Sq/LMBZO4=

### Context

Can't use Data Type / Firestore Map in the Database

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/95580779/ddbd5f0b-00c3-4359-868e-ffb21409fa17)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: PC
- Browser name and version: Chrome 117.0.5938.134
- Operating system and version affected: Windows 10
```

**Comment by wenkaifan0720** [comment]
Hi @dinasorz. I think this is because you don't have a data type defined yet in your project. I don't think our current UX is the most intuitive, but it shouldn't be a bug.

**Comment by hariprasadms** [comment]
Hi @dinasorz - Above given bug report code is wrong. Not able to fetch project details. Please check and add new one. Thanks

**Comment by hariprasadms** [comment]
Hi, Any updates? I hope you found the solution now. If this is the case, let us know we can close the issue. Thanks

**Comment by hariprasadms** [comment]
Hi, As there is no latest updates about the issue. I presume issue has been resolved for you. Hence closing the issue.
