### ISSUE TITLE
Pages are case sensitive and cause build errors

### ISSUE THREAD

**Issue by mixart** [FlutterFlow/flutterflow-issues#1620]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you have 2 pages in Flutterflow with the same name but different casing it causes a build error.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13832/d8ebb99a-2bff-4435-8bd1-7caa59ab938a)

### Expected Behavior

Either make builds accept case sensitivity or don't allow case sensitivity duplications in FlutterFlow UI.

### Steps to Reproduce

1. Create a page
2. Duplicate and change the name to the same with just a casing different
3. build

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no widgets were needed

### Context

Had to rename the page to a new name and then it worked

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13832/8bde47bb-f763-4c7c-88c8-b54f18cb182c)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web build mode
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by agreaves** [comment]
Hi @mixart, thanks for the report! We'll make sure users can't mane pages the same name in the future. This will be reflected in the next release.
