### ISSUE TITLE
Project won’t load on iPad app “version out of date”

### ISSUE THREAD

**Issue by raldred2** [FlutterFlow/flutterflow-issues#1622]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been working on a FF project through the iPad app version, without problem, but following editing through the web browser… when I go back to the iPad app and try loading the project is reports…

FLUTTERFLOW VERSION OUT OF DATE
You are on an older version of FlutterFlow than the most recently edited version of this project.  Please refresh the page to use the latest version.

…clicking the [Refresh] button has no effect.

I have tried reinstalling the iPad app (clearing cache) but nothing happens.

NB. Other FF projects never used the app work fine when opening on iPad.

### Expected Behavior

Open the project.

### Steps to Reproduce

1. Open iPad app
2. Click project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I_get_failed_to_copy_to_clipboard

### Context

Cannot use the iPad app.

### Visual documentation

<img width="515" alt="FF_iPad_App_Version jpeg" src="https://github.com/FlutterFlow/flutterflow-issues/assets/73439020/6c8011f5-a8fd-482f-8c6f-d4d8b4952021">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi - This issue already fixed as part for this issue #1565 . This fix should be available in next update release.
