### ISSUE TITLE
Info Tooltips don't work on iPad

### ISSUE THREAD

**Issue by vincekruger** [FlutterFlow/flutterflow-issues#1624]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The info tooltips are not showing on iPad

### Expected Behavior

The should show

### Steps to Reproduce

Tap on an info tooltip.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Context

Trying to view the tooltips.

### Visual documentation

<img width="306" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/360833/a9092e12-7490-4be9-9a7e-740065d54959">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iPad Air
- Browser name and version: App
- Operating system and version affected: iPadOS 17.0.3
```

**Comment by sbis04** [comment]
Hi @vincekruger, thanks for reporting the issue. This should be fixed in the next iPad update!

**Comment by vincekruger** [comment]
Will this come in the form of an app update?
