### ISSUE TITLE
Flutter flow export to github not properly buildable

### ISSUE THREAD

**Issue by frank-bee** [FlutterFlow/flutterflow-issues#1625]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- I export my flutter project to github
- I run it with codemagic:
```
  web-workflow:
    name: Web app workflow
#    triggering:
#      events:
#        - push
#      branch_patterns:
#        - pattern: main
#      cancel_previous_builds: true
    max_build_duration: 10
    environment:
      flutter: 3.10.4 #stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build webapp
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log
```
-"flutter analyse" fails with warnings e.g.
```
warning • Unused import: 'package:flutter_spinkit/flutter_spinkit.dart' • lib/pages/user_management/sign_up/sign_up_widget.dart:10:8 • unused_import
warning • Unused import: 'package:google_fonts/google_fonts.dart' • lib/pages/user_management/sign_up/sign_up_widget.dart:12:8 • unused_import
warning • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
```
-"futter test" fails with 
```
the error log is:
00:06 +0: loading /Users/builder/clone/test/widget_test.dart
00:07 +0: loading /Users/builder/clone/test/widget_test.dart
00:08 +0: loading /Users/builder/clone/test/widget_test.dart
00:08 +0: Counter increments smoke test
00:08 +0: Counter increments smoke test
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following FirebaseException was thrown building MediaQuery(MediaQueryData(size: Size(800.0,
600.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, systemGestureInsets:
EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false,
disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional,
gestureSettings: DeviceGestureSettings(touchSlop: null), displayFeatures: [])):
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
When the exception was thrown, this was the stack:
#0 MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
#1 Firebase.app (package:firebase_core/src/firebase.dart:56:41)
#2 FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:44:47)
#3 authenticatedUserStream (package:dreambeez/auth/firebase_auth/auth_util.dart:50:46)
#4 authenticatedUserStream (package:dreambeez/auth/firebase_auth/auth_util.dart)
#5 new _MyAppState (package:dreambeez/main.dart:58:23)
#6 MyApp.createState (package:dreambeez/main.dart:43:33)
#7 new StatefulElement (package:flutter/src/widgets/framework.dart:5381:25)
#8 StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:775:38)
#9 Element.inflateWidget (package:flutter/src/widgets/framework.dart:4177:42)
#10 Element.updateChild (package:flutter/src/widgets/framework.dart:3701:20)
#11 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#12 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#13 ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#14 Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#15 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#16 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#17 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#18 StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#19 Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#20 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#21 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#22 ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#23 Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#24 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#25 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#26 StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#27 Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#28 RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#29 RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#30 RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#31 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#32 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#33 AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1378:19)
#34 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#35 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#36 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#37 AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1233:9)
#40 TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#41 AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1220:27)
#42 WidgetTester._pumpWidget (package:flutter_test/src/widget_tester.dart:587:20)
#43 WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:572:14)
#46 TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#47 WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:571:27)
#48 main.<anonymous closure> (file:///Users/builder/clone/test/widget_test.dart:16:18)
#49 testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:165:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:08 +0 -1: Counter increments smoke test [E]
Test failed. See exception logs above.
The test description was: Counter increments smoke test
To run this test again: /Users/builder/programs/flutter/bin/cache/dart-sdk/bin/dart test /Users/builder/clone/test/widget_test.dart -p vm --plain-name 'Counter increments smoke test'
00:08 +0 -1: Some tests failed.

```

### Expected Behavior

flutter verify and flutter test should not fail

### Steps to Reproduce

see "current behavior"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

I want to use the flutterflow functionality of exporting the code , which I pay for quite a lot ( monthly , 70 bucks) ;-)

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: web, android
```

**Comment by frank-bee** [comment]
BTW, I did not test this issue from a blank project but wrote to flutter flow support (which I pay for) . They can do that, please, they can also use my project if they want

**Comment by hariprasadms** [comment]
Hi @frank-bee - Whats you are project bug report code ? Update issue with this detail.

As you said, you have already wrote to FF supported, what is their suggestion around the issue? I would suggest wait for support team to get back to you with details.

**Comment by davidflutterflow** [comment]
@frank-bee We downloaded your project source code and built it without any change or issue as you can see in the screenshot. So as I mentioned in your support ticket you need to reconfigure your Flutter SDK and use the same version of Flutter SDK that Flutterflow uses.
<img width="1800" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103986553/c88c6b70-746b-4991-a7b8-7d47a15c567a">
@hariprasadms I think we can close this issue here.

**Comment by hariprasadms** [comment]
Thanks @davidflutterflow

**Comment by frank-bee** [comment]
It is not about buildung but verify and test. See my bug report.

**Comment by frank-bee** [comment]
Why do you generate tests in flutterflow, if they fail?

**Comment by joshua-ffio** [comment]
Hi @frank-bee ,the `test/widget_test.dart` file is the standard sample widget test file, but isn't expected to work without change and isn't related specifically to your project. If you were to export a second FF project, you'd see the exact same file as well. This sort of example test file is a standard file that is typically created with all Flutter projects, even outside of FlutterFlow (if you were to start a Flutter project in your IDE), which is why it is included in your project.

Is the presence of this file causing your code_magic deployment to fail, or is it just the tests/analysis reports mentioning the test failures?

**Comment by frank-bee** [comment]
Hi @joshua-ffio ,
thanks for your  reply.

> Is the presence of this file causing your code_magic deployment to fail, or is it just the tests/analysis reports mentioning the test failures?
only "flutter analyse" and "flutter test" fails, which is part if the standard code magic pipeline. 
For a "clean export", it would be nice, if those steps are not failing.
If I start a flutter project in the IDE , I expect a "template" but not if I export a project from a FF project which is "in production".

In general, before I would start another project with flutter flow , I'd expect to have an export which a can do all the time (while I pay the 70 bucks a month  ;-) ) and *right away" deploy it to google play or whatever I configured in FF.
If I have to set this up afterwards of each time I do an export, thats very inconvenient.
I'd would like to work with flutter flow but have the build / deployment pipeline running on my own.
Nice would be: I fix something in flutter flow , push it to github and my pipeline is triggered there ( you could start with exporting a code magic yaml ( a fully working one including all the config for google play or whatever is configured in FF) or even a github workflow ( to avoid having another "vender lockin" of your users).

Don't get me wrong: You are developing a great product but if feels like there is a  "forced vender lock-in" because of your magic build which code magic - which you do not export.

P.S. one issue I really had to struggle with after FF export : the launcher icons  I configure in flutter flow were not exported. instead all the flutter default icons were in the android folder. Deploying the exported project "as is" to google play lead to failing reviews (unfortunately with unclear review message from google, which is for sure not your fault ;-) )
