### ISSUE TITLE
FirebaseAuth deleteUser is not working

### ISSUE THREAD

**Issue by jseandr** [FlutterFlow/flutterflow-issues#1627]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a custom action because I want to delete all users with a member_status 'student' and also delete them from the firebase authentication.

This is the error encountered
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/115357923/8887ad19-eadf-4948-b316-7cb1a8d59085)

I also tried to change the deleteUser into 'delete', didn't work.

### Expected Behavior

The expected behavior:
1. Delete user document from firestore
2. Delete user from firebase authentication.

### Steps to Reproduce

1. Create a button
2. Add an Action
3. Custom Action
4. Input the script I asked from ChatGPT

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejMmA7Y9On70A+7XfLMJKiQMxQUB+bZ0vlO1FGA42F5juPIYUP8jEaXdaT+nge3NXeFKWglEDw6H2vfzpDu0qGzaCGaF607t2ag2VUkynaKaqO6iKVmt8GdNPI3K108OVvB5NNshpW1pk1GGHcq3qNleeY8aSfxBlZ7vfcPo=

### Context

The expected output:
1. Delete user document from firestore
2. Delete user from firebase authentication.
3. Do not delete the current user. (The ADMIN who has a permission to click the button to trigger this script)

### Visual documentation

Here's my script.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/115357923/cf610e63-ff6c-4995-8cbf-35cf3374a7c9)

### Additional Info

I already achieved to delete all user document with a member_status 'student' with this script
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/115357923/4f3e5787-d261-407b-83c0-807895504a68)

I also want to delete all user from the Firebase Authentication but it's not working

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.152
- Operating system and version affected: Windows 10
```

**Comment by jseandr** [comment]
@hariprasadms  @aemelyanovff  do you guys have any updates with regards to this issue?

**Comment by aemelyanovff** [comment]
@jseandr The error message you are seeing is exactly right, there's no such method in `FirebaseAuth`: https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth-class.html
