### ISSUE TITLE
missing proyect

### ISSUE THREAD

**Issue by isaacpinadelucio** [FlutterFlow/flutterflow-issues#1628]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

missing project

I had been working for months and hours on a project, paying the pro subscription every month for several months now and some of the projects that I have been doing for months disappeared, not just for a few hours, months, I can't send a message to support, it won't let me and I had always been able to before, how am I supposed to solve it if they don't answer me? I can't send messages, what's happening, the chat section disappears??? Someone who can help me, it's not fair, I've been working for months, the test section doesn't load, the texts can't be seen and it doesn't load, so I don't know what's happening. I need help. I can't communicate with Flutterflow even though I have the subscription.

### Expected Behavior

find my projects where I left them

### Steps to Reproduce

no encuentro mis proyectos no se donde estan no los elimine no puede ser que hayan desaarecido no puede ser llevo meses pagando premium

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no hay este campo

### Context

find my projects where I left them

### Visual documentation

find my projects where I left them

### Additional Info

no encuentro mis proyectos y no tengo soporte

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @isaacpinadelucio - I'm sorry to see that you're having issues finding some of your projects in FF. There would be something wrong in your user account. The FlutterFlow support team is the primary contact for this kind of issues. Please contact them; I'm sure they will be able to assist you. Thanks
