### ISSUE TITLE
Cloud function doesn't work. Block by cors, but I already add it to trust domains

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#1630]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I need some help with FF cloud function.

I have this sample cloud function test and deployed it.

const functions = require('firebase-functions');
const admin = require('firebase-admin');

exports.test = functions.region('australia-southeast1').https.onCall(
  (data, context) => {
        if (!context.auth.uid) {
      return;
    }
        const test = data.test;
    // Write your code below!

    // Write your code above!
        return test;
  }
);

### Expected Behavior

return result

### Steps to Reproduce

1.create a simple cloud function
2. call it in FF

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Access to fetch at 'https://us-central1-xxxxx.cloudfunctions.net/test' from origin 'https://ff-debug-service-frontend-ygxkweukma-uc.a.run.app/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Context

When I call it, it give me this error.

Access to fetch at 'https://us-central1-xxxxx.cloudfunctions.net/test' from origin 'https://ff-debug-service-frontend-ygxkweukma-uc.a.run.app/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Visual documentation

null

### Additional Info

null

### Environment

```markdown
- FlutterFlow version: latest
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by dantedmn** [comment]
I have the same issue, been banging my head against the stupid CORS issue the whole week. Nothing I do helps. The settings are right in firebase and GCM, but nothing makes that solve the problem.

**Comment by nicmohr25** [comment]
This bug got fixed and comes with the next patch. 
#1538

**Comment by RizalSafwan** [comment]
im not sure when will flutterflow push the fix for now i found a temproady solution

find all ( FirebaseFunctions.instance ) and replace with ( FirebaseFunctions.instanceFor( app: FirebaseFunctions.instance.app, region: 'Replace-this-with-your-firesebase-region') )

this only works with if you're hosting outside of flutterflow

**Comment by hariprasadms** [comment]
Hi @simon-zhangmuye - This should be fixed in next update. This error you see because your cloud function region says 'australia-southeast1' but the cloud function link while accessing is _us-central1_ which is in correct. To make it run successfully, add 'all users' permissions as below. Try this and let me know how it goes. Thanks

<img width="585" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/87cc868c-d543-4bb5-aee4-6d9e461d7d1e">

**Comment by simon-zhangmuye** [comment]
@hariprasadms 
Hello, why I can't add allUsers to my principals?
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10706610/06e89f93-eb26-4378-9607-2cb3e772dec2)

**Comment by aicommadmin** [comment]
@hariprasadms I'm not using latest functionality with cloud functions and my project firebase database is deployed in eur3(europe-west). However I observe that right after opening a project in the editor I get in the log the following:

<img width="1010" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128803082/1dd64829-332e-43ab-87d5-19e89a6155ca">

Might it be somehow related with the above?
