### ISSUE TITLE
API Response Body consumed by Flutterflow Proxy

### ISSUE THREAD

**Issue by steverist1** [FlutterFlow/flutterflow-issues#1631]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi _ i have written  simple sub Azure Function as part of an evaluation of Flutterflow.  https://lvauth.azurewebsites.net/api/HttpTrigger1?code=R6KI_P00LM-hZGAz3aRaiHmk_fB_BqV4iGriUhSA_SM7AzFu7PwXRg==

There is no security in this test function and I can access it easily from a browser of from Postman.

When I invoke it as a FlutterFlow PAI Call, I get a 200 OK response, but no body. Something in the FlutterFlow stack is consuming my response body.

### Expected Behavior

I expect to get a 200 OPK status and a text response body, whereas I get null

### Steps to Reproduce

Invoke https://lvauth.azurewebsites.net/api/HttpTrigger1?code=R6KI_P00LM-hZGAz3aRaiHmk_fB_BqV4iGriUhSA_SM7AzFu7PwXRg==

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

I am trying to integrate a FlutterFlow app with a legacy system using Azure Functions as an isolation layer. This has stopped my project. 

### Visual documentation

Not needed

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @steverist1 - Whats your project bug report code ? Whats the response body you are expecting from this api ?

**Comment by steverist1** [comment]
Hi Hari,

I have managed to resolve the issue. I was expecting  plain text response which worked in Postman.

When I changed the return to a json string, FF p[assed it through.
