### ISSUE TITLE
Cloud functions not in the default region fail

### ISSUE THREAD

**Issue by scharfschiesser** [FlutterFlow/flutterflow-issues#1632]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Cloud functions deployed via FlutterFlow can override the default region. However, when calling a function somewhere in the project, it doesn't reflect the custom region in the code.

Example:
For a cloud function that is named 'checkPhone' and located in europe-west6, this is the code that is generated by FF:

```dart
final result = await FirebaseFunctions.instance.httpsCallable('checkPhone').call({
                                            "phoneNumber": _model.phoneController.text,
                                          });
```

The above code, however, is incorrect and will return the following error message (when printing the FirebaseFunctionsException catch):

```
flutter: [firebase_functions/not-found] NOT FOUND
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2 MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:22:24)
<asynchronous suspension>
```

### Expected Behavior

The correct code looks like this:

```dart
final result = await FirebaseFunctions.instanceFor(region: 'europe-west6').httpsCallable('checkPhone').call({
                                            "phoneNumber": _model.phoneController.text,
                                          });
```

Notice how the region needs to be explicitly set when calling the function.

### Steps to Reproduce

1. Create a new cloud function in a different region besides the default region (for example europe-west6)
2. Add an action to call the function and do something with the returned data
3. Download the code and run it on a physical device
5. Observe that the function fails

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8nc24Z2octK0KXyde9WmioWJUB5bb00st5Hd0gdCOPrBqQLdczRNxFoOMugaVNfMFWLpHoy0PDQk/PTMfYCYDSrQapRzrl2czzee2ilMq6aO8+KX3JCRONnJlyn3MCF2hFAAMlZdGxg3E+uHvO9YAnDFOu/Zwh9f6PHaOI=

### Context

This issue affects all my cloud functions, as I need to host them in different regions.

### Visual documentation

<img width="718" alt="Screenshot 2023-10-12 at 20 23 34" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40205459/f1427511-c34a-4fa3-8575-14fa30baa7fd">

<img width="340" alt="Screenshot 2023-10-12 at 20 24 01" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40205459/d77ea1f0-8843-4c1d-a0e4-cafee67e28a2">

<img width="356" alt="Screenshot 2023-10-12 at 20 24 20" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40205459/11c7bddf-894a-4e0d-b84e-a593aaee0cd8">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome Version 117.0.5938.149
- Operating system and version affected: macOS Sonoma 14.0
```

**Comment by hariprasadms** [comment]
Hi @scharfschiesser - I was looking at my projects and can see deployment works fine irrespective to the function region selected. Are you still facing the same issue ? Please check and confirm. Thanks

**Comment by scharfschiesser** [comment]
Yes, I'm still facing the same issue. I need to manually set the region in the source code for every function to work.

Console output when printing FirebaseFunctionsException

flutter: [firebase_functions/not-found] NOT FOUND

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:22:24)
<asynchronous suspension>
#3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:49:37)

After setting the region manually with 'instanceFor(region: 'europe-west6', it works.

**Comment by scharfschiesser** [comment]
> deployment works fine irrespective to the function region selected

I'm not referring to the cloud function deployments on FlutterFlow, my issue is with the source code that's generated by FF.

**Comment by scharfschiesser** [comment]
Looks like this issue has been fixed in yesterday's update. Thanks a lot!
