### ISSUE TITLE
Builds failing since 3:00am last night

### ISSUE THREAD

**Issue by mattholdsme** [FlutterFlow/flutterflow-issues#1633]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The deployment to google and apple was working perfectly fine until ~3:00 am AEST last night. I now receive the below error message for both deployments. I have tried to revert back to early changes, checked functions, redeployed all api's, firebase and cloud functions. I have done some research too and it seems related to a built in package native_device_orientation that could of been modified with the last flutter patch.

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/home/.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.
      case AppLifecycleState.hidden:
                             ^^^^^^
Waiting for connection from debug service on Web Server...         61.6s
Failed to compile application.

### Expected Behavior

Flutterflow should be able to deploy to both apple and google as it has been.

### Steps to Reproduce

go to settings, Mobile Deployment and deploy project. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Error (Xcode): ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.

### Context

This is impacting our initial release of alpha and crowd funding. We are now at a point of MVP and this is going to delay our release coming into the weekend.

### Visual documentation

![error](https://github.com/FlutterFlow/flutterflow-issues/assets/10339007/9636c3af-4727-475c-a2ea-280670f2c5c2)

### Additional Info

Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Found build number 45 from TestFlight version 1.0.1

Archiving com.EntwinedProduction.MeDoDare...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 3H6R7NCQ6B
Running pod install...                                             12.0s
Running Xcode build...                                          
Xcode archive done.                                         252.7s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.

Encountered error while archiving for device.

Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: ios and android
- Browser name and version: chrome and edge
- Operating system and version affected: windows 10
```

**Comment by MyTechAgent** [comment]
Also, Test mode doesn't work anymore but run mode does.

**Comment by MyTechAgent** [comment]
Hey team,

so i have done some more investigating and it looks like it's to do with the package native_device_orientation. They released a new update 39 hours ago and has failed the Pass static analysis. Is there a way to roll this back or a workaround? I can not even download an APK.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113911679/6f3eaa07-8d17-45d4-baaa-ec66c4d886e1)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113911679/5553eeb6-3ba4-467a-8cd9-be8eb376dd9d)

**Comment by hariprasadms** [comment]
Hi, Can you please update project bug report code ? Are you still experiencing the same issue ?

**Comment by mattholdsme** [comment]
Hi I am not sure how to update a project bug report? Yes, I am still having the issue. I did find that the native_device_orientation is in the pubspec.lock code but not in the pubspec.yaml. So i gather this is part of the core project?

**Comment by mattholdsme** [comment]
Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Archiving com.EntwinedProduction.MeDoDare...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 3H6R7NCQ6B
Running pod install...                                             12.8s
Running Xcode build...                                          
Xcode archive done.                                         275.9s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.

Encountered error while archiving for device.


Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1

**Comment by SameerShahzad99** [comment]
@mattholdsme Can you please share the bug report code, so we can check out the problem?

**Comment by dimemacau** [comment]
I'm having this same issue, any solution is greatly appreciated as I was also planning on Beta Testing and this unfortunate bug is delaying the launch. Thank you.

**Comment by MyTechAgent** [comment]
> Hi @mattholdsme, Can you please share the bug report code, so we can check out the problem?

Hi team. Can you please advise the actions you need me to take as I don't know how to do what you are requesting.

**Comment by MyTechAgent** [comment]
Update: this is a weird bug as I tested with an entirely different project and it works as expected.

**Comment by dimemacau** [comment]
Hi @MyTechAgent can you let me know what changed with your other project? Did you have anything specific that might refer to this specific issue in regards to device orientation?

**Comment by mattholdsme** [comment]
This I’m unsure of. I have tried to revert back to older versions that
worked and this didn’t work. I was working and the system requested me to
refresh due to a patch, and it hasn’t been working since. I tested a brand
new project last night but the current project I’m dead in the water with
and is starting to look like I may have to recreate the entire project….
Which is not feasible but will have to do what I have to do…

**Comment by prayersocial** [comment]
having similar issue for the past couple days

**Comment by MyTechAgent** [comment]
Hey team,

Additional information. I had saved a duplication of my project 14 days ago and setup the backend again. This is still doing the same thing. I also create a blank widget to try and pull the updated package through. It seemed like it stating 2.0 now but the same error message about being hidden. What widgets on flutterflow used the native package? I'm desperate for a workaround as we are about to start funding. I can export and manually upload but that will only allow me to solve the android side of things and would be a lengthy task.

**Comment by sgardoll** [comment]
Adding https://github.com/FlutterFlow/flutterflow-issues/issues/1639

**Comment by agreaves** [comment]
Hi @mattholdsme, thanks for the bug report and all the relevant information. It does look like an issue with the `native_device_orientation` package, which I've now updated to not use the most recent, broken version. The fix is now being deployed, thanks!

**Comment by rossman-x** [comment]
Hello @agreaves, how to update to the latest version ?
Thank you.

**Comment by MyTechAgent** [comment]
Hi team,

Thanks for the update. I can now use the app in run mode and have managed to download an apk now. I still get the same error running test mode and my deployments to app and google store still fail with the same error too. I assume you have implemented the patch and set up the deployment ready to go? Or am I doing something wrong?

**Comment by agreaves** [comment]
Hi @MyTechAgent, all of the above should be working now. Are you deploying to App Store and Play Store from a GitHub repository or directly from FlutterFlow?

**Comment by agreaves** [comment]
Also, if the issue _is_ still continuing please include a Bug Report Code to help me further debug the issue.

**Comment by rossman-x** [comment]
The bug is fixed after `flutter upgrade`

**Comment by mattholdsme** [comment]
Hi Team,

I am deploying to App Store and Play Store directly from flutterflow. I'm in AEST

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10339007/c0498bc4-fdd6-4443-99ab-c4117e35d72c)

Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Archiving com.EntwinedProduction.MeDoDare...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 3H6R7NCQ6B
Running pod install...                                             10.4s
Running Xcode build...                                          
Xcode archive done.                                         228.5s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.

Encountered error while archiving for device.


Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1

**Comment by MyTechAgent** [comment]
I have just checked and can deploy now. Must of been a delay. Thank you all.

**Comment by agreaves** [comment]
Hi @mattholdsme, are you deploying from your own GitHub repository? That would cause the issue to continue.

Otherwise, please include your Bug Report Code as requested (right click from widget tree). Otherwise I will not be able to help.

**Comment by dimemacau** [comment]
Can confirm it is working. Thanks everyone!
