### ISSUE TITLE
Automated tests don't work with Supabase login (error: Supabase needs to be initialized)

### ISSUE THREAD

**Issue by ScissorHill** [FlutterFlow/flutterflow-issues#1635]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'd like to use Automated Tests on a project that involves Supabase authentication. The downloaded test code fails to compile locally, with the following error:

`Exception has occurred.
_AssertionError ('package:supabase_flutter/src/supabase.dart': Failed assertion: line 32 pos 7: '_instance._initialized': You must initialize the supabase instance before calling Supabase.instance)`

Note that the app itself compiles and runs perfectly in an Android emulator.

**Bonus:** 

Adding a precondition on login raises a different error. An  `await FirebaseAuth.instance.signInWithEmailAndPassword` call is injected into the test code, resulting in the compile error `Undefined name FirebaseAuth`.

### Expected Behavior

1. I expect the test code to compile and run without errors, even with Supabase authentication. 
2. I expect that adding a login precondition allows the test code to compile and run without errors, even with Supabase authentication.

### Steps to Reproduce

1. Create a new page as the initial page (login).
2. Add a row with a TextField for email.
3. Add a row with a TextField for password.
4. Add a submit button.
5. Create another page to serve as the logged-in page.
6. Enable Supabase, add url/anon key, and fetch schema.
7. Enable authentication, select Supabase as the authentication type, and set the initial and logged-in pages.
8. To the submit button on the login page, add action->Supabase authentication->login, set appropriate textfields for email and password.
9. Once everything works as expected, download code.
10. Run main.dart (under /lib), with an Android emulator. Check that everything works as expected.
11. Run test.dart (under /integration_test), with an Android emulator. Compile fails with the following error: `Exception has occurred.
_AssertionError ('package:supabase_flutter/src/supabase.dart': Failed assertion: line 32 pos 7: '_instance._initialized': You must initialize the supabase instance before calling Supabase.instance)`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TlPHluIlgrt9c187pbcFV9TsvIjs1bY0/isN+a0kjNurnEIYid8jRT3FJXMu4d2xUJGH8sGAI7sKMk/zLFvoCHwqIQ75+wpNqbRWWUXyXVJSbDM+ORHJPJ+hWfkfE1JqOiiMnAMFidCEZ7WeIIee8ZBbUGZC0OjABMeX9UaL++F7nHXjRLThmtmNecCfn

### Context

I'm excited about the new Automated Tests feature. All my projects use Supabase authentication, so if this bug isn't resolved, the new feature is a non-starter for me.

### Visual documentation

![Screenshot from 2023-10-13 16-14-30_mod](https://github.com/FlutterFlow/flutterflow-issues/assets/26180991/25a3960c-bdfe-4335-a87e-83cc20a38183)
![Screenshot from 2023-10-13 17-54-59_mod](https://github.com/FlutterFlow/flutterflow-issues/assets/26180991/d52ec68f-5c95-4f02-853b-2d6526731aa5)

### Environment

```markdown
- FlutterFlow version: 4.0 (Flutter 3.10.4)
- Platform: Android
- Browser name and version: Chrome Version 117.0.5938.149 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 22.04
- VSCode version 1.83
```

**Comment by wenkaifan0720** [comment]
Hi @ScissorHill. Sorry for the super late response. This should be fixed in our next release. Thank you!
