### ISSUE TITLE
Issue inserting row into Supabase table with encrypted column (Supabase TCE Encryption)

### ISSUE THREAD

**Issue by buyblvd-ryan** [FlutterFlow/flutterflow-issues#1636]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to insert row into a table with an encrypted column, get a permissions error.  By default, there shouldn't be any restrictions on inserting into a row with an encrypted column, only on reading the decrypted table.  Seems like it's an issue with how FlutterFlow uses the PostgREST API maybe.  I'd settle for a workaround, but I can't figure one out besides not using encrypted tables.

### Expected Behavior

I should be able to insert into a table with an encrypted row, but not be able to read the decrypted value.

### Steps to Reproduce

1. Create a project and link a supabase project with an encrypted column.
2. Try to insert a row into that table.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ts7nwIZJnbRK1pfQa8cwmhIWJEA6X5EW18J7aCsofePrOpkAf8/7UFtUOcugd2NXfVmJrGAX/MrThvzEGvZdJRCdRYg5+pNqTQ6XUlG6VqaLDJS3b0Z8PJlWGGqf5KW3mB5DHPVpL3xgw0+qO+u/ThfrJoP4OWokAOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I can't insert rows into a table, and I *really* need to.

### Visual documentation

![console error](https://github.com/FlutterFlow/flutterflow-issues/assets/117312895/5df0ea33-0fdf-4597-8a3c-d6b161823c6b)
![headers](https://github.com/FlutterFlow/flutterflow-issues/assets/117312895/e5b47680-a4f8-45bc-b220-8183efa5c01f)
![payload](https://github.com/FlutterFlow/flutterflow-issues/assets/117312895/ef021e3b-f823-4a93-9262-559c0eaccdba)

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: Web Test Mode
- Browser name and version: Arc (Chrome)
- Operating system and version affected: macOS Sonoma
```

**Comment by buyblvd-ryan** [comment]
Bumping this to keep GH bot from closing it

**Comment by SameerShahzad99** [comment]
As FlutterFlow currently does not support encrypted rows, I would not be able to consider this a bug.
I am considering this as a feature request!
