### ISSUE TITLE
Can't deploy to stores

### ISSUE THREAD

**Issue by dimemacau** [FlutterFlow/flutterflow-issues#1637]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow is throwing an error when deploying to stores. The current message goes like this:

Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Found build number 45 from TestFlight version 1.0.1

Archiving com.EntwinedProduction.MeDoDare...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 3H6R7NCQ6B
Running pod install... 12.0s
Running Xcode build...
Xcode archive done. 252.7s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.

Encountered error while archiving for device.

Build failed :|
Step 10 script Flutter build ipa and automatic versioning exited with status code 1

### Expected Behavior

The pubspec.lock file should have the correct version of the native_device_orientation package so the app can be deployed.

### Steps to Reproduce

I suppose trying to deploy to stores will bring this issue, possibly from projects created before yesterday when the issue started.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlsn15YpNxcRE0JDic8d4pCowFjMLa+cF0+1+FB4gIqnkOoYlPMykS0NKTt+rf0FiME2grEIDpuzKuOPqFe4qAz+qRa5M0JVPWhfyJHy6R6nWEbigVXJfGcRPfRHF1qa3gR5vLtNZdFIQw2CxNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I finished a one-month journey to build my functional MVP and was really excited to launch today, to find out I can't because of a FlutterFlow bug.

### Visual documentation

![Screenshot 2023-10-14 at 12 03 22 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/146033967/5482800b-868d-4a22-8b39-2011bf958b6a)

### Additional Info

Other users are getting this error, it's becoming a major bug that's preventing many users from deploying. Please fix ASAP.

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web, MacOS Desktop (app is working locally)
- Browser name and version: Google Chrome
- Operating system and version affected: macOS Sonoma v14.0
```

**Comment by sgardoll** [comment]
We must have been going through the same issues. I logged around the same time. Includes some additional detail and debugging: https://github.com/FlutterFlow/flutterflow-issues/issues/1639

**Comment by agreaves** [comment]
Hi @dimemacau, thanks for the bug report. This is the same issue as #1633, and will be fixed momentarily. Thank you for your patience!
