### ISSUE TITLE
form validate doesn't work for radiobutton, pincode, dropdown and checkboxgroup

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#1638]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

form validate doesn't work for radiobutton, pincode, dropdown and checkboxgroup

### Expected Behavior

validate input

### Steps to Reproduce

1.create a new page
2.add form
3. add column
4. add pincode
5. add radiobutton
6. add dropdown
7. add checkbox group
8. check form validate

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

null

### Context

cannot validate input

### Visual documentation

null

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @simon-zhangmuye - Thanks for submitting the issue. Issue details are not in recommended issue template formate. Please follow the issue template instructions and add the required details. Without these details we do not consider issues for investigations. Thanks

**Comment by hariprasadms** [comment]
Hi, I can reproduce the issue for below widgets,

**1. Dropdown widget
2. Radiobutton widget**

For other widgets you mentioned, form validation does not work and it is as expected.

**Comment by aemelyanovff** [comment]
@simon-zhangmuye Thanks for reporting the issue, and sorry for the late response.

Form validation for dropdowns and radio buttons _actually_ is working, but it's less nice than for, say, text fields. The "Validate Form" action will exit if a radio button or a dropdown is invalid, but it won't display that nice red "Field is required" text.

We will track this internally as a feature request.
