### ISSUE TITLE
Issues with Mux widget and/or apivideo_live_stream and/or flutter_native_device_orientation dependancy causing AppLifecycleState.hidden issues

### ISSUE THREAD

**Issue by sgardoll** [FlutterFlow/flutterflow-issues#1639]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying to App Store, both the iOS and Android build fail with an error related to the native_device_orientation package, specifically pointing to an unrecognized AppLifecycleState:

**Android:**
> Upgrading build.gradle
> Running Gradle task 'bundleRelease'...                          
> ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.
>       case AppLifecycleState.hidden:
>                              ^^^^^^
> Target kernel_snapshot failed: Exception
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/Users/builder/programs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1201
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command '/Users/builder/programs/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 24s
> Running Gradle task 'bundleRelease'...                             85.8s
> Gradle task bundleRelease failed with exit code 1
> 
> 
> Build failed :|
> Step 8 script `Build AAB with Flutter` exited with status code 1

**iOS:**
> Archiving com.connectio.knak...
> Upgrading contents.xcworkspacedata
> Updating project for Xcode compatibility.
> Upgrading project.pbxproj
> Upgrading Runner.xcscheme
> Upgrading Info.plist
> Removing script build phase dependency analysis.
> Adding input path to Thin Binary build phase.
> Automatically signing iOS for device deployment using specified development team in Xcode project: UGM4QHBM9W
> Running pod install...                                              9.2s
> Running Xcode build...                                          
> Xcode archive done.                                         197.0s
> Failed to build iOS app
> Error (Xcode): ../.pub-cache/hosted/pub.dev/native_device_orientation-1.2.0/lib/native_device_orientation.dart:218:30: Error: Member not found: 'hidden'.
> 
> Encountered error while archiving for device.
> 
> 
> Build failed :|
> Step 11 script `Flutter build ipa and automatic versioning` exited with status code 1
 

Upon inspection, it was found that this package is a transitive dependency of the apivideo_live_stream package, which is at its latest version (1.1.2). The problematic lines in the native_device_orientation package were:
```
case AppLifecycleState.hidden:
  // seems to be synthetic event on iOS/Android
  break;
```

### Expected Behavior

The app should build successfully without any issues related to unrecognized AppLifecycleState.

### Steps to Reproduce

1. Steps to Reproduce:
2. Add apivideo_live_stream package to pubspec.yaml.
3. Run flutter pub get.
4. Build the iOS app using Xcode.

Unfortunately not as simple as just creating a new project from scratch in Flutterflow as the error relates to something within the native_device_orientation dependancy of apivideo_live_stream which Mux widget uses. 

### Temporary Solution

- I've been able to get the project to build in Android Studio after forking native_device_orientation to https://github.com/sgardoll/flutter_native_device_orientation where I've commented out lines 218 - 220 (inclusive) - these are the problematic lines I've referenced in "Current Behaviour" above.
- Manually override the dependency in the project's pubspec.yaml as follows:
```
dependency_overrides:
  native_device_orientation:
    git:
      url: https://github.com/sgardoll/flutter_native_device_orientation.git
```
- Running the following commands to update dependencies and rebuild the project:
```
flutter pub get
flutter clean
```

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi87huIxNrtdc+KX2KcBvmjgXIjs2ULgom+tTaCs8GqLuPe0UWMzBUBFUcNDiYHNDMEyarGcX/Mrvid/EG8E6aC+abp85yc5Ucwr/Uj66aK7QO763b3F7HflUCFSj57WvvxRDLrRedXwk1Ey6Ptm8fDXsHoCyPFcRGeaoXdeK2SrDX1iXc2URm05KZDPz (this is for a widget on another page as I was getting this error when trying for a widget on the page using the Mix widget: Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null) )

### Context

Completely unable to deploy or build any code that will deploy or compile in Android Studio or Xcode in current state.

### Visual documentation

![Screenshot 2023-10-14 at 11 58 22 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/72906115/a0c8cb73-43b2-476f-8a2d-2b33c7a1c19f)

### Additional Info

Happy to share code directly, but don't want to upload to a public forum

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: 14.1 Beta (23B5067a)
- Browser name and version: Chrome Version 117.0.5938.132 (Official Build) (arm64)
- Operating system and version affected: All
```

**Comment by agreaves** [comment]
Hi @sgardoll, thanks for the bug report. This is the same issue as #1633, and will be fixed momentarily. Thank you for your patience!
