### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by DevTeamTeam** [FlutterFlow/flutterflow-issues#164]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

**I was hoping to see the facebook login page.**

## Current behavior (required)

**Nothing happened**

## To Reproduce (required)

**As part of my internship, I have to do this step in my work.**

## Your environment

* Version of FlutterFlow used: **Last-version**
* Platform (e.g. Web, MacOS Desktop): **Linux (Fedora 36)**
* Browser name and version: Chrome (last-version)

**Comment by aemelyanovff** [comment]
Issue tracker is only used for reporting bugs. New feature suggestions and questions should be discussed on [Community](https://community.flutterflow.io/) or submitted through the user feedback form.
