### ISSUE TITLE
Compilation Errors Due to Missing 'ApiCallResponse' Type in Register Page Model

### ISSUE THREAD

**Issue by kamil220** [FlutterFlow/flutterflow-issues#1640]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While running or building an app I receive following message:

Error message:
```lib/pages/authentication/register_page/register_page_model.dart:69:10: Error: Type 'ApiCallResponse' not found.
  Future<ApiCallResponse> recentlyAddeed({
         ^^^^^^^^^^^^^^^
lib/pages/authentication/register_page/register_page_model.dart:72:21: Error: Type 'ApiCallResponse' not found.
    required Future<ApiCallResponse> Function() requestFn,
                    ^^^^^^^^^^^^^^^
lib/pages/authentication/register_page/register_page_model.dart:68:55: Error: 'ApiCallResponse' isn't a type.
  final _recentlyAddeedManager = FutureRequestManager<ApiCallResponse>();
                                                      ^^^^^^^^^^^^^^^
lib/pages/authentication/register_page/register_page_model.dart:72:21: Error: 'ApiCallResponse' isn't a type.
    required Future<ApiCallResponse> Function() requestFn,
```

Problem: The ApiCallResponse type seems unavailable or not imported correctly in the relevant file, leading to compilation errors.

### Expected Behavior

Not receiving errors during running and building.

### Steps to Reproduce

1. Add a list view with an API call on an example page for example: homePage,
2. Enable Query Caching for this component, then set Scope as Page Level and create query name.
3. Create a register/login page, and use Firebase to authentication,
4. On the Register and Login page in Route Setting uncheck "Requires Authentication",
5. Try to build SDK or run it on your local device.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiOfl3ItIseZE7pSJde9VmSQvMjt6U4Ee0OtHZCs8GZT0B4kcYs+kfklUcO6lT29MJE2WhTkX/MnIufLmUsI6AwibUbl8zqt2VjqUVmamaJi0DJS3b0ZRI+ZWGWqz5JmnuglDLth2V3st3E2LN+eiSnTXQJDuOzA7QeaeXdeK2SrDX1iXc2URm05KZDPz

### Context

After the integration of an authentication system using Firebase, compilation errors related to a missing 'ApiCallResponse' type have been observed in the register_page_model.dart file. Although the initial solution was to add the missing library (api_requests/api_manager.dart), a deeper review of the code hints at potential issues in cache management and possibly redundant code.

Error message:
```lib/pages/authentication/register_page/register_page_model.dart:69:10: Error: Type 'ApiCallResponse' not found.
  Future<ApiCallResponse> recentlyAddeed({
         ^^^^^^^^^^^^^^^
lib/pages/authentication/register_page/register_page_model.dart:72:21: Error: Type 'ApiCallResponse' not found.
    required Future<ApiCallResponse> Function() requestFn,
                    ^^^^^^^^^^^^^^^
lib/pages/authentication/register_page/register_page_model.dart:68:55: Error: 'ApiCallResponse' isn't a type.
  final _recentlyAddeedManager = FutureRequestManager<ApiCallResponse>();
                                                      ^^^^^^^^^^^^^^^
lib/pages/authentication/register_page/register_page_model.dart:72:21: Error: 'ApiCallResponse' isn't a type.
    required Future<ApiCallResponse> Function() requestFn,
```

Problem: The ApiCallResponse type seems unavailable or not imported correctly in the relevant file, leading to compilation errors.

### Visual documentation

![CleanShot 2023-10-14 at 17 51 02](https://github.com/FlutterFlow/flutterflow-issues/assets/16455814/9f2afaf9-1f63-4798-9545-5737ddd1f76e)
![CleanShot 2023-10-14 at 17 51 53](https://github.com/FlutterFlow/flutterflow-issues/assets/16455814/e21bbfb1-173b-4469-b541-25cf93a9edea)
![CleanShot 2023-10-14 at 17 53 23](https://github.com/FlutterFlow/flutterflow-issues/assets/16455814/f5ef5a95-6a5a-44af-b5b8-d1c175b8597e)

### Additional Info

I was able to fix the issue locally, by adding 
```import 'package:p_e_ti_f_e_e_d/backend/api_requests/api_manager.dart';```
on the beginning of the file.

Edit: After disabling query caching for the component everything working well. Below screenshot with information about the amount of changed code.
![CleanShot 2023-10-14 at 17 59 02](https://github.com/FlutterFlow/flutterflow-issues/assets/16455814/6a3165c4-0389-46ba-bcf7-f7c71df3b340)

### Environment

```markdown
- FlutterFlow version: v.4.0, Flutter 3.10.4
- Platform: Android, iOS
- Browser name and version: Google chrome v.118.0.5993.70
- Operating system and version affected: MacOS Sonoma 14.1 Beta
```

**Comment by SameerShahzad99** [comment]
@kamil220 Apologies for the delay, It looks like you have not attached the bug report code of a blank project with issue reproduced, we'll need that to confirm the issue!

**Comment by aemelyanovff** [comment]
This will be fixed in the next update!
