### ISSUE TITLE
Cross Axis Count doesnt work in GridView when using Conditional

### ISSUE THREAD

**Issue by eddiebrasil** [FlutterFlow/flutterflow-issues#1641]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to show two columns and one column depending on the Response Value.

### Expected Behavior

When large size is 2 per row, anyother 1 per row.

### Steps to Reproduce

1. Create a Gridview with a database result
2. Add a container inside
3. In Cross Axis Count, dont use an actual number but set from Variable
4. Add conditional "Responside Value"
5. Forf Breakpoint large put 2. For other 1.
6. Make a test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn1sJVOxcBE7a6Jbu9ajSQvNjM5a+Yr0cpBZzAaIrb1CLMqY8mnPhZCTf3idH9meWC2p14H+PvFjvz2UfdcHzGdGK5RyJFuTAH/cDihbpeTF7WWVnx6TMpQCkid5LSnuwp7LshodVo92melfvDKFz/aCb22C2owSq/LZO4=

### Context

Different versions for web and app

### Visual documentation

=

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Any
- Browser name and version: Edge
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment]
@eddiebrasil It looks like the bug report code that you have attached is not from a blank project with the issue reproduced, please share the correct bug report code, so i can continue testing!

**Comment by sbis04** [comment]
Hey @eddiebrasil, I wasn't able to reproduce the issue. It generates the code correctly as well:

<img width="542" alt="Screenshot 2023-10-21 at 11 13 29 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/52614006-1327-4737-a68b-c74b6b7bc428">

Can you please test once more and let me know of the issue still persists?
