### ISSUE TITLE
Cannot add custom permission `com.google.android.gms.permission.AD_ID`

### ISSUE THREAD

**Issue by Gintasz** [FlutterFlow/flutterflow-issues#1642]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So uploading app to google play, I get this warning:

```
Your advertising ID declaration in Play Console says that your app uses advertising ID. A manifest file in one of your active artifacts doesn't include the **com.google.android.gms.permission.AD_ID** permission.

If you don't include this permission in your manifest file, your advertising identifier will be zeroed out. This may break your advertising and analytics use cases, and cause loss of revenue. [Learn more](https://support.google.com/googleplay/android-developer/answer/6048248)

You can remove these errors by updating your advertising ID declaration


Apps that target Android 13 (API 33) without the AD_ID permission will have their advertising identifier zeroed out. This may impact advertising and analytics use-cases. [Learn more](https://support.google.com/googleplay/android-developer/answer/6048248)
```

I cannot add this permission as custom permission inside flutterflow because the android permissions have a fixed prefix, which is not suitable for this one.

### Expected Behavior

Remove hardcoded android permission prefix

### Steps to Reproduce

Create a new project that includes google analytics
try to upload it to google play and view errors in google play console release page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

described earlier

### Visual documentation

<img width="712" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6189625/bc724dc5-04b0-4fa5-91f2-a07e856ffad0">

### Environment

```markdown
- FlutterFlow version: 4
- Platform: android, google play
```

**Comment by wenkaifan0720** [comment]
Hi @Gintasz. This should be allowed in our next update. Thank you!

**Comment by Gintasz** [comment]
@wenkaifan0720 I don't see it fixed yet... last update was oct 23, 3 days ago...

**Comment by Gintasz** [comment]
@wenkaifan0720 I have a custom billing code and I can't even add custom permission "com.android.vending.BILLING" because of the same reason. So this should be top priority.

**Comment by Gintasz** [comment]
I see the new update today, all is good, thank you.
