### ISSUE TITLE
Improve speed of loading Ratings Reviews in FF marketplace 

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#1643]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

it takes too much time for  Rating and Reviews section to be uploaded in FF marketplace 

### Expected Behavior

Rating and Reviews section should load very fast 

### Steps to Reproduce

1. visit https://marketplace.flutterflow.io/
2. select any items for example https://marketplace.flutterflow.io/item/6vglMkVMjQEr5yGaU0fB
3. check the rating reviews section loading 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://marketplace.flutterflow.io/item/6vglMkVMjQEr5yGaU0fB

### Context

it make the user experience less friendly 

### Visual documentation

<img width="1275" alt="Screenshot 2023-10-15 at 23 28 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/6e80441d-7844-49a6-822f-e21fcffaa4f4">

### Environment

```markdown
- FlutterFlow version: website market place
- Platform: 
- Browser name and version: chrome
- Operating system and version affected:
```

**Comment by katherineqian** [comment]
Hi @sergedahdouh, appreciate the report! I agree with @hariprasadms that this is a feature request so I will close it for now, but your feedback is noted and I'll send this back to the Marketplace team for us to review.
