### ISSUE TITLE
Unable to add Pubspec dependencies

### ISSUE THREAD

**Issue by mickealmprivat** [FlutterFlow/flutterflow-issues#1644]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It seems I can no longer add pubdev packages when creating a custom widget. No error is shown, and clicking the refresh button does nothing. I have tested the following packages:
https://pub.dev/packages/super_editor
https://pub.dev/packages/html_editor_enhanced
https://pub.dev/packages/quill_html_editor

I have had a working implementation of html_editor_enhanced previously where I successfully only imported that package (ie, no dependencies) and the same behavior is detailed in [this thread](https://community.flutterflow.io/c/community-custom-widgets/post/two-fully-functional-rich-text-html-editors-for-ff-community-psYBqr7mpwcuonH)

### Expected Behavior

Package imports should be added to code, or show errors with necessary dependencies

### Steps to Reproduce

1. Create a new project
2. Add a Custom Widget
3. Add pubdev package
4. Furiously click refresh as nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Klc/qx89OxL1E0M/UcvkwmmA5KVgjauYslusbGAsafbbwG7YMS8+kMxJVXemndGNEL2agkXwdw9aLuPzMA+UnGy2WfJxy/5dqehbjdz6jaJSPEs2/dEEkN8NJJVyn1MCzsyUkOtBpR1Yj2Fy2I+i+ZDTUJbrXIkcnP/GIKrv+gV2qQ0SLb3kNh1JWeC/v

### Context

I can not create my custom widget

### Visual documentation

There is nothing to show!

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: MacOS Browser
- Browser name and version: Chrome Version 118.0.5993.70
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @mickealmprivat - Thanks for submitting the issue. I looked at the above project. I can see no error while adding import line of the package you have added in the custom code. See below. 

Is this you are expecting ?

<img width="1503" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ab9e7cc5-7322-4de1-9bb2-6fd2cf108f51">

**Comment by mickealmprivat** [comment]
@hariprasadms exactly, but that's not happening for me

**Comment by hariprasadms** [comment]
Did you try in different projects? if not, try and confirm please. It could be a project specific.

**Comment by mickealmprivat** [comment]
@hariprasadms I tried in different projects and on different accounts

**Comment by mickealmprivat** [comment]
@hariprasadms I may be misunderstanding the expected behaviour? I just saw a video where they manually paste the import from the pub dev example, but I seem to remember it being automatically added from the refresh button?

**Comment by lumobilab** [comment]
I'm dealing with the same issue. Multiple projects.

Nothing happens, the dependency is not saved, but looks like it is "added" somehow.

Some time later the project build fails because of the missing dependency, and the only way I was able to "solve" it is reverting to a previous version/snapshot. Doesn't make sense to me.

**Comment by hariprasadms** [comment]
> I'm dealing with the same issue. Multiple projects.
> 
> Nothing happens, the dependency is not saved, but looks like it is "added" somehow.
> 
> Some time later the project build fails because of the missing dependency, and the only way I was able to "solve" it is reverting to a previous version/snapshot. Doesn't make sense to me.

Hi, Yes. you are correct. manually added dependencies, required adding import line manually.

**Comment by hariprasadms** [comment]
> I'm dealing with the same issue. Multiple projects.
> 
> Nothing happens, the dependency is not saved, but looks like it is "added" somehow.
> 
> Some time later the project build fails because of the missing dependency, and the only way I was able to "solve" it is reverting to a previous version/snapshot. Doesn't make sense to me.

This could be a different issue. Please create a new issue with all the required details for investigation. Thanks
