### ISSUE TITLE
Firebase confirm email and password reset actions not working

### ISSUE THREAD

**Issue by absolutelynick** [FlutterFlow/flutterflow-issues#1646]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a new firebase db and linked this to my flutterflow project. This project on the build can write to the database in the new project. But sadly some features in flutterflow seem to say that they cannot connect to the firebase project as the firebase@flutterflow.io has not been added as a user with the correct permissions. This is incorrect and has been done. The features that seem not to be working are:

- sending of "confirm email" links to users on sign-up
- sending of password reset links
- in the flutterflow bd page I can access the MANAGE CONTENT link but get  an error message, attached
![Screenshot 2023-10-16 174712](https://github.com/FlutterFlow/flutterflow-issues/assets/5681155/4ab26133-8931-43fa-9144-4d7c55e5de0d)

### Expected Behavior

The opposite of above

### Steps to Reproduce

1. Open and run the app.
2. Create a new user and wait for the email confirmation link.
3. This will not come.
4. Next you can open flutterflow and open the firestore button on the left
5. On the users option in the database page
6. above click the button to MANAGE CONTENT
7. The page will say user not authorised.Firestore

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8/14YlPxOVc7arAKcJB/TgWG183U+Y4scsZa0kdB4joPLJ+dc7RchJVZMPmTUNhHFqjv3wKzPTtvfP1DcAqNSqCRYh4wqhcYDvNd3q8RLKNC82OTmhBEf1RBWaY17eFgiZ+Ju91SC0u22eqDd6uTirbJ5+/Zwh9f6PHaOI=

### Context

1. I need to be able to verify users and connect with Firebase fully or I cannot publish this project.
2. I need to be able to manage context in the database schema in flutterflow.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5681155/618443ca-3d70-4efb-b286-68b3c3e600c8)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5681155/023ffd66-5da0-4edc-968f-1ee752e86ad1)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by lennongames** [comment]
hello [absolutelynick] and thank you for creating this question. I'm currently experiencing the same issue as well. I can create records in firebase, I can create records via the FF project, however, when I want to manage content from FF, I receive the same issue. 

Is it a FF known issue?

**Comment by sbis04** [comment]
Hey @absolutelynick, the third issue you mentioned above should be fixed in the next update! We'll look into the other two issues that you are facing.

**Comment by agreaves** [comment]
Hi @absolutelynick, thanks for the bug report! As @sbis04 mentioned, we have fixed the third issue you mentioned! However, sending confirm password and password reset emails are configured on the Firebase side. The code for the actions does appear to be correct and working for other users so this appears to be a project specific issue. It's possible that the email provider is blocking the reset links for some reason ([this link](https://support.google.com/firebase/answer/7000714) provides a bit more info).

Give that the issue on the FlutterFlow side is fixed, I'm closing this issue for now. Please reach out to support if you continue to have issues with the sending auth emails, we're happy to help.
