### ISSUE TITLE
Upload/Save File Action does not preserve picked filename

### ISSUE THREAD

**Issue by TomJFox** [FlutterFlow/flutterflow-issues#1647]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using 'Upload/Save File' Action to Firebase Storage, user is asked to pick a file.  The Filename, is not duplicated on Firebase storage, instead a set of numbers (which appears to be a timestamp) is used for the filename.

### Expected Behavior

When Uploading a file, I would like for the filename to be used on Firebase Storage or for the original filename to be available from the Upload/Save File action such that it can be stored with the generated Firebase link for later use.

### Steps to Reproduce

Create project with Firebase Storage
Create new page
Add button with Upload/Save File Action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OismB2492m+Fa7aXqacEw+CQRNlw1bZZMjMFxQgEjGOrNGu4MPsneVFRuZrzgS29YImKKoGAJxvfqufLxE/c4ITiWfLpGyM5cEDmXYFyWRc2zEqirfW1QL+5VGBGb5sCvqhUlIsxsS0447V2qNu+9QnbrHozQOlcwRfK1KdeK2SrDX1iXc2URm05KZDPz

### Context

I am unable to preserve the filename that the user has selected during the upload.  Later when the file is downloaded, the filename is no longer available to the user.

### Visual documentation

Picture of uploaded file when 'Test Document.pdf' uploaded.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/106626912/0190b376-3beb-4fc5-9fd7-2cbfd78255e6)

### Environment

```markdown
- FlutterFlow version: v4.0 released September 28, 2023
- Platform: Web
- Browser name and version: Google Chrome Version 117.0.5938.152 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi, Please submit a feature request for this using in-app feature request form under help section.

**Comment by TomJFox** [comment]
Feature request submitted.  I look forward to seeing this in an update soon.

**Comment by felipe-arrowdigital** [comment]
How did you solve TomJFox?

**Comment by felipe-arrowdigital** [comment]
Could you please be so kind as to share? Help out this poor soul who's been searching for a solution all day. @TomJFox

**Comment by Serhio1210** [comment]
Bumping this thread. Would appreciate help with custom action

**Comment by felipeboff** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45862227/466169e2-d92e-4536-b8b7-6f7fe149aeeb)

```
import 'package:file_picker/file_picker.dart';

Future<List<FFUploadedFile>?> pickAndUploadFiles() async {
  try {
    final result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
    );
    if (result != null) {
      List<FFUploadedFile> uploadedFiles = [];
      for (var file in result.files) {
        int? fileSizeBytes = file.bytes?.lengthInBytes;
        if (fileSizeBytes != null &&
            fileSizeBytes > 0 &&
            fileSizeBytes <= 100000000) {
          final fileData = file.bytes ?? Uint8List(0);
          final uploadedFile = FFUploadedFile(bytes: fileData, name: file.name);
          uploadedFiles.add(uploadedFile);
        }
      }
      return uploadedFiles.isNotEmpty ? uploadedFiles : null;
    }
  } catch (e) {
    return null;
  }
  return null;
}
```

Pubspec Dependencies
`file_picker: ^6.1.1`

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45862227/b22d48bd-d522-43a8-b80d-4c7ee4fe01d3)

```
String? extractFileName(FFUploadedFile? file) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  if (file != null) {
    return file.name.toString();
  }
  return null;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

**Comment by WouterGlorieux** [comment]
@felipeboff Thanks, your custom action works on the webapp version, but when I try on the android version there is no file data.
Do you have any idea why this could be?

**Comment by WouterGlorieux** [comment]
If anyone needs this, here is how to modify the code above so that it works on both webapp and mobile:

```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'dart:io';

Future<List<FFUploadedFile>?> pickAndUploadFiles() async {
  try {
    final result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
    );
    if (result != null) {
      List<FFUploadedFile> uploadedFiles = [];
      for (var file in result.files) {
        int? fileSizeBytes = file.bytes?.lengthInBytes;

        if (!kIsWeb && file.path != null) {
          print("On mobile File path: ${file.path}");
          // On mobile, use the path to read bytes
          final fileData = await File(file.path!).readAsBytes();
          print("File size (from path): ${fileData.length}");
          fileSizeBytes = fileData.length;
          if (fileSizeBytes > 0 && fileSizeBytes <= 100000000) {
            final uploadedFile =
                FFUploadedFile(bytes: fileData, name: file.name);
            uploadedFiles.add(uploadedFile);
          } else {
            print("Skipping file: Size check failed");
          }
        } else {
          print("On web");
          fileSizeBytes = file.bytes?.lengthInBytes;
          print("File size (from bytes): $fileSizeBytes");
          if (fileSizeBytes != null &&
              fileSizeBytes > 0 &&
              fileSizeBytes <= 100000000) {
            final fileData = file.bytes ?? Uint8List(0);
            final uploadedFile =
                FFUploadedFile(bytes: fileData, name: file.name);
            uploadedFiles.add(uploadedFile);
          } else {
            print("Skipping file: Size check failed or bytes are null");
          }
        }
      }
      if (uploadedFiles.isNotEmpty) {
        print("Files uploaded successfully");
        return uploadedFiles;
      } else {
        print("No valid files to upload");
        return null;
      }
    } else {
      print("File picker returned null");
      return null;
    }
  } catch (e) {
    print('An error occurred: $e');
    return null;
  }
}
```

**Comment by sahawnehwajdi** [comment]
@WouterGlorieux & @felipeboff both of your codes works nicely! many thanks!
However, I'm new to flutterflow, and I encountered this issue. What's next after creating the custom action and function? the custom action returns an uploaded file, how to get it across to firebase or any other storage with the original file name?

**Comment by WouterGlorieux** [comment]
The custom action will return a list of files, so in the next action where you need the file you need to select the output of the custom action, then select 'item in list', and then the first item.

**Comment by sahawnehwajdi** [comment]
Thank you @WouterGlorieux 
I'm struggling! I have a warning in Pubspec Dependencies.
Please see what I have so far:
Can you be so generous and share screenshots of how the action should look like? much appreciated!

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/131411269/91e1fc5b-f60f-4700-bbb2-aab813679de6)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/131411269/5f2b820d-7e0a-4c8e-abe3-8812d2bb4fbd)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/131411269/3cb4cb17-3d26-4e2d-ae93-607decfa5912)

**Comment by WouterGlorieux** [comment]
You can leave the pubspec dependencies empty, it is already imported by default.
I don't use firebase myself, but where you need the filename, you can then use the custom function you made in the same way, just select the output of the custom action, with item at index and first item, and then you should get the name of the file as a string.

**Comment by felipe-arrowdigital** [comment]
@WouterGlorieux
Thank you for your help in solving the issue with the Upload/Save File action. Your solution fixed the problem with the file name on mobile devices. I refactored the original code to make it more concise, clear, and efficient while maintaining the same functionality.

```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'dart:io';

Future<List<FFUploadedFile>?> pickAndUploadFiles() async {
  final filePickerResult = await FilePicker.platform
      .pickFiles(
        allowMultiple: true,
        withData: true,
        type: FileType.any,
      )
      .timeout(Duration(seconds: 30));

  if (filePickerResult != null) {
    List<FFUploadedFile> uploadedFiles = [];

    for (final pickedFile in filePickerResult.files) {
      if (pickedFile == null) continue;

      int? fileSizeBytes = pickedFile.bytes?.lengthInBytes;
      if (fileSizeBytes != null &&
          fileSizeBytes > 0 &&
          fileSizeBytes < 100000000) {
        Uint8List? fileBytes = kIsWeb
            ? pickedFile.bytes
            : await File(pickedFile.path ?? "").readAsBytes();

        if (fileBytes == null || fileBytes.isEmpty) continue;

        FFUploadedFile uploadedFile = FFUploadedFile(
          bytes: fileBytes,
          name: pickedFile.name,
        );
        uploadedFiles.add(uploadedFile);
      }
    }

    return uploadedFiles.isNotEmpty ? uploadedFiles : null;
  }

  return null;
}
```

Thanks again!
