### ISSUE TITLE
Missing documentation - deploy to Google Play from Github

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1648]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is missing documentation for deploying your app to Google Play from Github. It should be under 4.6 here (as indicated by the URL): https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment#4.6_deploy_from_github_branch 

The URL is found here when pressed on the "Click" button:
![Screenshot 2023-10-17 at 01 29 56](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/2e0ed207-586a-47e2-bf2a-98b8cc1e3f56)

### Expected Behavior

Find instructions on how to deploy from Github to Google Play.

### Steps to Reproduce

/

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcn635ZNvttZ+KX2KMBFijksKUQjRYEVmtYaaxIbN5PMC+wIZ/f7XFRuTde0dAlAIGKapH01+cHemvH1KMcoJgSZGr58wap2cQnwZH6WaLKSO4eKR25/DcZMCBzF0Z7YvQl4ObNhci0h216let+AdB/AHYTsPFcdBsiHIZKK2SrDX1iXc2URm05KZDPz

### Context

Don't know how to deploy to Play Store from Github as there is no instructions.

### Visual documentation

/

### Environment

```markdown
- FlutterFlow version: v4.0 (released Sep 28, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 117.0.5938.149
- Operating system and version affected: macOS Sonoma 14.0
```

**Comment by hariprasadms** [comment]
Thanks for submitting the issue. Its been passed to documentation team to check and update.

**Comment by SameerShahzad99** [comment]
We already have documentation for deploying from GitHub here:
https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment#deploy-from-github
