### ISSUE TITLE
Indexing bug on Carousel Widget.

### ISSUE THREAD

**Issue by dimemacau** [FlutterFlow/flutterflow-issues#1649]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using conditional visibility on a carousel widget. If it hides while on index 0 and then reappears without changing pages, everything works fine. But if it hides on index 1 and reappears, there needs to be a swipe to refresh the UI. Seems like the carousel reappears on the wrong page. I wouldn't mind it fully refreshing and appearing on index 0, but it reappears on index 0 visually but the index is still 1.

### Expected Behavior

Unhidding the carousel widget should index correctly or at least fully refresh.

### Steps to Reproduce

Create any type of project with a carousel and hide the carousel widget with a backend visibility condition on any index other than 0 (for example on index 1). Reappear the carousel without changing pages. Carousel has to be swiped twice to change indexes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlsn15YpNxcRE0JDic8d4pCowGUwLUI03lOtxbxQbCeKuO4l/f+PCTFZDSOqHTwtAEGegkjgK0Mr1kvzxKu0EMkibfY87/rpfUxDjUT6gVr3SDam/PHFRHfJnGkOM0Z2FoxVCKuh2WVYh316PNu6Aa3qCf9qOYwx5e6fDbOY=

### Context

I'm using conditional visibility on a carousel widget. If it hides while on index 0 and then reappears without changing pages, everything works fine. But if it hides on index 1 and reappears, there needs to be a swipe to refresh the UI. Seems like the carousel reappears on the wrong page. I wouldn't mind it fully refreshing and appearing on index 0, but it reappears on index 0 visually but the index is still 1.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/146033967/f26b111c-35e4-42af-8cfd-3d918e0acd5a

### Additional Info

Adding a carousel control feature could potentially open workarounds, but right now I'm stuck on this.

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @dimemacau - Thanks for submitting the issue. I looked at your project. It is not a blank project with issue setup details. For this kind of issues, you should demonstrate the issue by setting up it in a blank project otherwise it is a challenge for us to fully understand whats going on in real project. Update the issue with the required details.

**Comment by hariprasadms** [comment]
Hi, Are you still experiencing the issue ?

**Comment by hariprasadms** [comment]
Closing the issue due to inactivity. Thanks
