### ISSUE TITLE
Conditional labels in charts not displaying

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#165]
## Expected behavior (required)
Display of labels based on conditional variable, ie. if a local state is true, display a string, if not then display another.

## Current behavior (required)
Nothing is shown in chart label unless a static value is used.

## To Reproduce (required)
1. Create a chart
2. Create a local state variable
3. Open axis properties, either one will do
4. In Title Text Properties, create a variable based on local state
5. Observe that the string is not displayed in the chart. 

## Context (required)
My charts display prices internationally. I want to display currencies based on the user selected (stored in local state variable) country's currency.

## Screenshots / recordings
![Screenshot 2022-11-25 at 12 02 49](https://user-images.githubusercontent.com/114226492/204024326-2af92b34-3ac0-4365-86e2-bf439b39013b.png)

## Your environment
* Version of FlutterFlow used: v3
* Platform (e.g. Web, MacOS Desktop): Web, MacOS Desktop
* Browser name and version: Safari 16.1 (17614.2.9.1.13, 17614
* Operating system and version (desktop or mobile): MacOS 12.6.2 (21G312)

**Comment by agreaves** [comment]
Thanks for the bug report @ampapplarsen! This will be fixed upon our next release! 🙂
