### ISSUE TITLE
supabase password reset failure

### ISSUE THREAD

**Issue by drclohite** [FlutterFlow/flutterflow-issues#1650]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

logged out of app. Go to log in using same old password and it fails.
Request new password
it says EmailRequired
- email is entered into the emailfield as specified. I even set my email address as the initial value in the code.

### Expected Behavior

expect to be able to write new password and save.
I have seen the process operate on third party videos
in my case the opportunity to enter a password does not occur

### Steps to Reproduce

1. Logout of app
2. try to log in again - says credentials invalid
3. click on link forgot password
4. says Email Required! (I set it as an initial value as well as attempted to overwrite)
5. - see current behaviour above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/qy5d1m8tK7q6JKflagmA5JUN6bYErjO5RaCgoIYyuOpl/evWkdRZBONfnd2NbPkSmmjoxwMKKhdrpF/ECAziVGohF+apPEzzzcF2gQZOBDqiOZXR7EfxbIFC50p+n2SZSCOtaSF1n2173BNzLTj7YQ6K3IlFISq/LZO4=

### Context

I cannot get back into any of my apps if I use supabase. THis means testing is impossible and I cannot produce a commercially viable output. 

Also I use a mac I cannot left click, left clicking functionality is not available to me. For this reason I could not get a bug report code other than to log into my pc and get it there. 

### Visual documentation

<img width="389" alt="Screenshot 2023-10-17 at 09 20 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/39235874/aae2a61b-688c-414d-9935-e1a8cc2e6059">

### Additional Info

<img width="802" alt="Screenshot 2023-10-17 at 09 22 05" src="https://github.com/FlutterFlow/flutterflow-issues/assets/39235874/c8d1a439-afcd-40ae-b6e5-d788d0d066fe">
<img width="804" alt="Screenshot 2023-10-17 at 09 22 52" src="https://github.com/FlutterFlow/flutterflow-issues/assets/39235874/a4744571-54d1-433e-b5b8-d33e8e37c484">

### Environment

```markdown
- FlutterFlow version: v4 3.10.4
- Platform: Macbook pro
- Browser name and version: Chrome Version 117.0.5938.149 (Official Build) (x86_64) auto updates turned on
- Operating system and version affected: Mac OS Catalina

I get the same problem on my PC Windows 10 etc
```

**Comment by drclohite** [comment]
Also material icons on mac don't work, only Font Awesome - and these are from the templates Flutterflow supplies. Does anyone do any testing? I got another problem with components not showing up properly on mac and PC - from another video tutorial, admittedly not yours. Sure I can waste another hour going through this process to create mini apps to show you what is wrong with your software. It is pretty annoying and created unceccessary delay. V4, I doubt your commitment from these errors, I look at each of these new developments in V4 and wonder if I as a beginner would use them. I don't think so. There are so many bugs as I am a new user with less than a month experience of your tool i figured for a few weeks it was me. You think it is reasonable I should find all these bugs and you should allow them to permeate?

**Comment by SameerShahzad99** [comment]
@drclohite As I tried testing, it looks like the supabase password reset action is working fine, check the attached screenshot:
[https://drive.google.com/file/d/1PLTxm4pizrB_tvKbvT2Jtf_cCpIHuj4y/view?usp=sharing](url)

**Comment by SameerShahzad99** [comment]
Regarding the issue that you are facing with email not getting set, it looks like it is due to some issue in the template not setting a different text field name, that's why a text field value from the other tab bar is getting selected, you can change the name of the text field and select it to fix the problem
[https://drive.google.com/file/d/1fWmeQzxBHSH4jl2-p-9a-KGZyQAMqBit/view?usp=sharing](url)
[https://drive.google.com/file/d/1uRIoEGc7tkTbUJlGkzyNXrMYbJaxuynm/view?usp=sharing](url)

**Comment by drclohite** [comment]
Those image links lead to blank page, so I can't see what you refer to.

**Comment by drclohite** [comment]
OK, got it, thanks I will test and see If I can fix this. You may have noticed this is from a template in your template store, the color of the text is in the template for the forms is incorrect too.
