### ISSUE TITLE
Error List View or JSON Path with two queries results are returned, but only one query is shown.

### ISSUE THREAD

**Issue by raycelgraterol** [FlutterFlow/flutterflow-issues#1651]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

with two queries results are returned, but only one query is shown and the other is not in the view list.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/b288f3b7-e900-476c-ad45-bb23e84cc7b3)

Result in test of the API
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/614b8ba6-d62b-4053-abb8-9d05477e3c40)

Config of the list view and JSON Path

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/0b309f2b-71bb-4510-ace0-5d22723049b3)

Result in running app.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/bf3fd801-447c-44cb-8539-f75eb8a7145a)

Both return result but just one is shown in the list view the another no.

### Expected Behavior

The two queries should bring results and display them in the list view.

### Steps to Reproduce

1. create a widget with a backend query.
2. in the backend query add the API (group InventoryAPIERP) > getProducts
3. Generating Children from Variable and set JSON Body > JSON Path > products.
4. in the list view in some Text add From List View some property like $.name or $.id for test or just the index.
5. Run the app and is no showed the items.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48j+fq0491xcNY1pPpbflR/Sk5KUs7ULhFm9Z+UUo8J5zTP4YIP/v7ak5oO72ldEFMImeKoGAKxvfqhuGWMvAqJTWqbYRTyKl6aQnKeFmVR8mKCpedfW1QHp5YfG6H0bS3uRR4CNphLnwO6kOpfuvJTivvQ4zLClUFQc+lKdeK2SrDX1iXc2URm05KZDPz

### Context

![CONFIG IN LIST VIEW](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/cc4f6bed-a576-4923-b590-bd71531a7837)

Configuration of the list View

### Visual documentation

![1 -TEST RESULT BOTH DATA BOTH APIS](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/d1e97521-34b7-482f-a45d-c8594933deb7)
![2 -CONFIG IN LIST VIEW](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/1d78b628-0ba3-40d5-9167-74cbb572d18a)
![3 -RESULT RUNNING APP](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/6a638448-f57c-4011-b705-b193dac0c046)

steps

### Additional Info

result of the API Query in network console.

![products](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/c7afe122-88b9-4af4-9980-3407368d4117)
![purchase](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/56f91773-055e-4709-b1ff-9019206cf17e)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.152
- Operating system and version affected: Windows 11 Pro
```

**Comment by SameerShahzad99** [comment]
@hi @raycelgraterol This looks like a project-specific issue, please reach out to the support team through live chat or email at support@flutterflow.io for this issue!
