### ISSUE TITLE
Need Replacement to Firestore Dynamic Links 

### ISSUE THREAD

**Issue by jerperdue** [FlutterFlow/flutterflow-issues#1655]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Firebase dynamic links are being deprecated. [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links) Is there a suggested solution to achieve the same behavior?

![Screenshot 2023-10-17 at 11 40 20 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/274b3059-9d1b-42d0-8fbb-d13bf59bae10)

### Expected Behavior

I want to create a link that will take a user to download or open an app on Android or Mobile

### Steps to Reproduce

[see above]

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

N/A

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: All versions
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
Hi @jerperdue I am marking this as a feature request!
