### ISSUE TITLE
CORS error during CRUD of any self-hosted supabase table

### ISSUE THREAD

**Issue by Shokhrukh99** [FlutterFlow/flutterflow-issues#1656]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I recently self-hosted Supabase on my computer. I was able to connect to it via FF

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/8a0c95e7-2799-4c20-ae3c-359e31d76cae)

However, when I try to do any CRUD operation I get the following error in the browser console:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/51e7bd1f-dda0-425a-9129-67110ab65317)

It is complaining about CORS policy: "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource".

### Expected Behavior

Perform CRUD operations without CORS error

### Steps to Reproduce

1. Self-host Supabase using Docker
2. Create a few tables. For some reason it doesn't matter whether the table has active RLS or not, still, the issue persists
3. For proxy and domain I used Keenetic router's KeenDNS with SSL certificate
4. Connect FF to Supabase 
5. Try to query or insert any data into the table

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelefluJN2tb0A+c7iasBopwMwGkQ5a7sviu5+FBQaI+LmPLQEPM6kUBZWcuqHfFFqD1KWrzgB+dHGifOeU/E4ISurQJR9yKhbUxDhQXGWVJC7BbrhY3NBM8FVJ3al552N2xUnG7NZdHwu7DmUIPOAa3qCf9qOYwx5e6fDbOY=

### Context

I cannot perform any CRUD operation with my DB, and I can't use any other cloud solutions such as Firebase due to local (Uzbek) regulations. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/51e7bd1f-dda0-425a-9129-67110ab65317)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/8a0c95e7-2799-4c20-ae3c-359e31d76cae)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 118.0.5993.70
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Shokhrukh99 - Thanks for submitting the issue. Currently FlutterFlow does not support self hosted supa-base configurations. So the error what you are experiencing could be a expected one and not in scope to investigate the issue. You can reach FlutterFlow technical support team to get more help around it. I can confirm that it is not a bug. Thanks
