### ISSUE TITLE
Firestore tab link to Manage Content Doesn't work if changed firebase project 

### ISSUE THREAD

**Issue by tokach** [FlutterFlow/flutterflow-issues#1658]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After initial setting up a new firesbase project I made new connection in Settings but in Firestore tab of the builder when I click to Manage Content button on the top right corner it opens link to the old firebase project, e.g.
when app was created I set up a firebase myproject-kasdf2
then a while later I set a new firebase project myproject-5
and when I click Manage Content it opens me [my](https://app.flutterflow.io/cms/myproject-kasdf2, not my currently connected myrpoject-5

Also due to this it is not connecting to new base when running app in Test Mode

### Expected Behavior

Firebase settings changes across all the Flutterflow app not only in Project Settings

### Steps to Reproduce

create new app, set up firebase with guide
build something 
delete firebase project and create new one
connect app to new firebase project
try to open Manage Content (it will try to show you old firebase project and data from it, cause you have not set user error)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfi8rlvM1OxOFa7q6Ja8FoiiURNWEcTeUzlO1hdwwbI+PzO7AMY+PBYhRpWOqHYW5UP2GbrHwzpt7nud7PLe1cGxWZY6o/zKlTUxDhQjiWacWxCLWaW2skN/1jfRW/55iJnx5AJst1S3wk216Hf96+b3qCf9qOYwx5e6fDbOY=

### Context

I need to make app from scratch also not sure how to transfer already created page to new project?

### Visual documentation

https://drive.google.com/file/d/1p3YhlCNg3LCyhZ-w3VHRgklLKXIWI8en/view?usp=sharing screencast 2min

### Environment

```markdown
- FlutterFlow version: 4
- Platform: app for Android built on Web
- Browser name and version: Chrome 115.0.5790.170
- Operating system and version affected: elementary OS 5.1.7 Hera (Ubuntu 18.04.6 LT)
```

**Comment by SameerShahzad99** [comment]
@tokach Thanks for sharing, i was able to reproduce this on my end!

**Comment by katherineqian** [comment]
Hi @tokach, did you regenerate the config files from within FlutterFlow after updating your Firebase project ID?

**Comment by aemelyanovff** [comment]
@tokach I apologize for the slow response.

The id in https://app.flutterflow.io/cms/<id> is the id of your FlutterFlow project, not your Firebase project, so it's not supposed to change after you connect a different Firebase project.

I'm unable to reproduce the problem, but I suggest this:
- First and foremost, reach out to FlutterFlow support, they might be able to help.
- "Regenerate Config Files" from Firebase settings.
- When you open https://app.flutterflow.io/cms/<id>, open the "network" tab of your browser dev tools and inspect calls to https://identitytoolkit.googleapis.com. Responses from them usually contain clues for why it doesn't work.

**Comment by tokach** [comment]
Hi there, issue is related to the saving process of firebase projects IDs not to the flutterflow project itself, I have submitted issue here and your colleague was able to reproduce it not sure what I should ask from support I am no longer working on that project, however issue was present last time I checked it
best regards
