### ISSUE TITLE
JSON Parameter not passed when navigating to different page

### ISSUE THREAD

**Issue by yongtheskill** [FlutterFlow/flutterflow-issues#166]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior 
When navigating to a page with a JSON parameter, selecting a JSON object when navigating to the page will allow the passed JSON object to be accessed on the new page.
After navigating, to the new page, the JSON object is not null and should be the passed object.
From the downloaded code (modified to work as per expected behaviour):
```dart:
context.pushNamed(
    'newPage',
    queryParams: {
      'jsonParameter': serializeParam(
        jsonData,
        ParamType.JSON,
      ),
    }.withoutNulls,
    extra: <String, dynamic>{
      'jsonParameter': jsonData,
    },
  );
```

## Current behavior
When navigating to a page with a JSON parameter, selecting a JSON object when navigating to the page does not work.
After navigating, to the new page, the JSON object is null.
From the downloaded code:
```dart:
context.pushNamed(
    'newPage',
    queryParams: {
      'jsonParameter': serializeParam(
        jsonData,
        ParamType.JSON,
      ),
    }.withoutNulls,
  );
```

## To Reproduce
1. Create a page named pageA
2. Create a page named pageB
3. Add a page parameter to pageB of type JSON
4. Add a text widget on pageB that uses the JSON parameter as its value
5. Create a JSON object on pageA
6. Add a button on pageA, set its onTap action to navigate to pageB, and pass the above JSON object as a parameter
7. Run the project. Clicking on the button on pageA will navigate to pageB, but the text widget on pageB will show null

### Bug Report Code
IT4OiMr18c5NodxE7rr+KfpR/TwXH1g2bIZNldYaUQAdGJfNG7UIec/4VEptXbC+TVc3O1q0gmQfwNrRuPbIN/c4KTmuc75/wZBIEwKVID6gRJSTPc2WfHJPMJYGSSDy

## Context 
When i try to pass JSON from one page to another, I just get a null value on the target page. Thus I am unable to pass any unstructured data from page to page without manually modifying the code.

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform: Android, IOS and Web
* Browser name and version: Chrome 107.0.5304.122
* Operating system and version: desktop Windows 10 Home 22H2

**Comment by Pepino-GR** [comment]
Hi yongtheskill,

can you please complete the steps to reproduce. How do you create the JSON object on PageA an how does it looks like?

**Comment by agreaves** [comment]
Hi @yongtheskill, thanks for reporting the issue and adding those steps. However, I'm still not able to reproduce the issue even after following those steps. Would you be able to create a video of the bug in action, or create a simple test project that recreates the issue?

**Comment by yongtheskill** [comment]
Hi, thanks for the quick response. I have just found out that the issue only happens on mobile, not web, so sorry for the miscommunication.

Following the above steps, using a json object created in local state, the issue occurs. 

Here is a screen recording of the same app, deployed on web and with the downloaded apk. The web version works, but the apk does not. I can share the project if required (but you will have to tell me how :p).

[Screen recording ](https://lh3.googleusercontent.com/pw/AL9nZEXrzpzTDYoRYd1HyOD4t2ga8QMqQ77mcq310lYS4jZs_d2ERKItbpbrKtfbGEzSNF63O7u0YbjSqFwHv4n3YOVv-xVqT6fme48iNPbuYyHLkMiDJrvK=m18) 

Thanks!

**Comment by agreaves** [comment]
@yongtheskill Would you mind adding the bug report code for the example project you created (not the original project)? I can then download and test it out on Android 🙂

**Comment by yongtheskill** [comment]
Here is the bug report code
IT4KjufqxItOj7xF+KrUY8Axmjw5KVgjauYsltZ+dwEdIb6rG7YAW/SkQE9WZ7yhdH03OmKZmmEdw87WuNzIN/BfMkyeGrZNz89cegrKJUKVbK7RCs6KbXJBNJYGSSDy

**Comment by agreaves** [comment]
Hi @yongtheskill, it looks like the page it's navigating to is trying to use the JSON data as a String even though it is a Map (JSON) type. Could this potentially be happening in your app as well?

**Comment by yongtheskill** [comment]
Hi, 
I see the problem, thank you so much.
