### ISSUE TITLE
Test Mode never finishes loading (Run Mode works)

### ISSUE THREAD

**Issue by jerperdue** [FlutterFlow/flutterflow-issues#1660]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently my project works in Run mode, but not in Test mode. Test mode never finishes "loading"

![Screenshot 2023-10-18 at 10 16 04 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/29c24b3e-48e2-415a-a647-de036e734a88)

### Expected Behavior

Test mode should finish loading as expected. 

### Steps to Reproduce

Run test mode on my app: https://app.flutterflow.io/project/touchpoint-app-wcbn10

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz8mB35VNvs9G1aqNKe9ViicWMjt8UOc3l8J9YCs8GZT0B4kcYs+kfklUOLHndFVbMWGaoD8X/Mr1koXXA/lcPQSqR6E7+qt6dRbif3G5V4SwEa63b3NDI+BhN36a15iZpyVTBO9uZXA5wDm6Pd+Qfz/AH4zLPmsvReaoXdeK2SrDX1iXc2URm05KZDPz

### Context

This is seriously blocking me from building. I cannot test small changes quickly. Maybe I got into a bad state, but I need to get out of it so I can continue building. 

### Visual documentation

![Screenshot 2023-10-18 at 10 16 04 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/04454df5-5c97-4891-8406-1fb93d3aeb4f)

### Environment

```markdown
- FlutterFlow version: n/a
- Platform: web
- Browser name and version:
- Operating system and version affected:
```

**Comment by jerperdue** [comment]
I'm getting the same error. Please help! It's really difficult to make progress without the Instant Loading in Test mode. Right now I am completely blocked from using it. 

![Screenshot 2023-10-21 at 5 07 24 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/62181919/4927e49e-6c05-487f-b16a-3de69adafe58)

**Comment by hariprasadms** [comment]
Hi, are you experience this issue yet? Looks like it was intermediate issue while platform upgrade or maintenance. Let us know if you still experiencing the issue. We can take a look at your project. Thanks

**Comment by ReCoL1337** [comment]
Hi, I'm still experiencing this issue, I think there is something with the CanvasKit renderer because when I created a custom widget that needed the CanvasKit render in order to work, it wasn't working in test mode for some reason (it gave me errors that I don't have CanvasKit enabled). When I opened it in the run mode and on the hosting everything worked fine. I don't recall exactly when this happened but shortly after that my test mode wasn't working at all (returning the error above). And yes, I have enabled the renderer in the settings. It's gust a wild guess but maybe it'll help.

**Comment by jerperdue** [comment]
@hariprasadms Yes, I am still experiencing the issue

**Comment by hariprasadms** [comment]
Hi @jerperdue - I looked at your project code. I see below error while running get pub specs. Fix these dependency conflicts. It can fix the issue what you are facing. You can see error showing up in custom code as well.

<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/e769c3ea-0e68-4bcf-8a00-c780a5ceed9a">

<img width="1335" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6d4a1976-05fc-43e0-bb5e-b89b418c85ee">

**Comment by dmslabsbr** [comment]
Hi, I´m having the same error.

I shared my project with you.    [FlutterFlow APP Promo-Share ](https://app.flutterflow.io/project/promo-share-88lh3r)

I'm currently using FlutterFlow 4.0 and Flutter 3.13.7. Notably, there's no error indicated by these versions.

![tela-flutter](https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/b3a1f80b-97b1-45f0-9133-32b7ce993347)

I've already posted the error on the community forum, but without positive results so far.

[FlutterFlow Update Issue: App Freezes in "Test Mode"](https://community.flutterflow.io/c/bugs/post/flutterflow-update-issue-app-freezes-in-test-mode-VsguH1turo7YgJF)

In "Test Mode", the loading bar keeps spinning indefinitely.

I've captured the following error from the browser's debug console:

![erro-flutterflow](https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/0942a43d-707f-44e7-b6b4-5bba0712dc67)

After downloading the code, I ran the command: flutter pub get --no-example

No errors with dependencies.

![pub-get](https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/6560a6f2-ccec-42d9-9b6b-12296eb4730f)

I agree this is becoming a big problem for me too – I can't test and iterate quickly

**Comment by hariprasadms** [comment]
@ReCoL1337 - It looks like your issue is something different one. Can you create a separate issue and add all the required details please. 

@jerperdue - Are you still facing the issue ?

**Comment by dmslabsbr** [comment]
As recommended, I created a separate new issue - [App NEVER run in "Test Mode" #1795](https://github.com/FlutterFlow/flutterflow-issues/issues/1795)

**Comment by jerperdue** [comment]
@hariprasadms Yes, I am still experiencing the issue. It's still a big problem. Please help

**Comment by hariprasadms** [comment]
Hi, This issue initially identified as related to external package error and solution was suggest. Hence closing the issue.
