### ISSUE TITLE
Flutterflow cloud function custom response doesn't put result in WithdrawCloudFunctionCallResponse

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#1662]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow cloud function custom response doesn't put result in WithdrawCloudFunctionCallResponse

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10706610/fdce0def-2639-4907-acaf-1c4b13468516)

### Expected Behavior

pass result to WithdrawCloudFunctionCallResponsethe 

### Steps to Reproduce

build a custom function and listen to its result. you will get an error because it is a null value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

_model.cloudFunctionmyv!.succeeded! cannot be null

### Context

I cannot finish my cloud function result check

### Visual documentation

null

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by simon-zhangmuye** [comment]
Did you guys release this without testing for bugs at all?

**Comment by hariprasadms** [comment]
Hi @simon-zhangmuye - Thanks for submitting the issue.  Whats your project bug report code? Please update the issue with this detail.

**Comment by hariprasadms** [comment]
Hi, Any updates on required details please ?

**Comment by takashiff** [comment]
Hello, thank you for the bug report. The issue has been resolved and should be reflected in the next deploy.
