### ISSUE TITLE
Google Maps Error on rebuild/ conditional build

### ISSUE THREAD

**Issue by bash-bash** [FlutterFlow/flutterflow-issues#1663]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When switching (rebuilding) between Google Maps view and a listview an error occures (but only on Test Mode on web). 1. Error is "Bad State" and second is "Maps cannot be retrieved before calling buildView". 

### Expected Behavior

It should show the google map view with the markers on the screen or when clicking the FAB it should switch to a listview and vice versa.

### Steps to Reproduce

1. Login (register before)
2. Click on the FAB on the bottom right. (listview is visible)
3. Click again on the FAB to switch back to Google Maps view
4. Check console within the browser. There are the errors.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfjcrl25R2rsdG1oSIKvlaoCcsKWEcTuUzlO1EcwgdCLboPLMAfPz4UFJuTde+TVc3JWaaknMKpvzWvvbIN/U5Fwmqbr5k+pN2VTryJV25MLasPLqwPkF7NNpKC0yc4KSNvAhSHMFZL3w57Vz3LuyvUnLqQLLSDGonHv3+DITNnXPuQ0SLb3kNh1JWeC/v

### Context

I'm not able to implement further actions like bottomsheet when clicking on a marker. As every click on the map throws an error. 

### Visual documentation

https://www.loom.com/share/42fa64b470e44128a6825cdfec2abde0?sid=d313a085-792c-4100-88ad-8b492c2f6c96

<img width="423" alt="error2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/33637315/066431cc-b952-4137-b0ed-4331a82486a3">
<img width="1060" alt="error1" src="https://github.com/FlutterFlow/flutterflow-issues/assets/33637315/e5b235d0-052e-41b8-88aa-07e95cdc37be">

### Additional Info

Your support testet it on my project and on a blanc project. The problem orruced always on web/browser.
He tested also locally. There the problem does NOT occure. 

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome Version 118.0.5993.71
- Operating system and version affected: Windows 11 and MacOS
```

**Comment by bash-bash** [comment]
No :/

**Comment by rzambroni** [comment]
Hi everyone,

I apologize for the delayed response. We are working hard to address all reported issues. Are you still experiencing this problem? I attempted to replicate it in a blank project and it seems to be working as expected on my end. If you are still encountering this bug, could you please provide the code for a blank project where the issue is reproducible? This will help us investigate further.

Thank you!
