### ISSUE TITLE
api group was deleted after update

### ISSUE THREAD

**Issue by kanatbkeeep** [FlutterFlow/flutterflow-issues#1664]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Api group was deleted after update. And when i try to create api group with same name and url to restore it, it is not being created.

### Expected Behavior

Refund of my api groups with api inside

### Steps to Reproduce

Created api group,
Set header Authrorization: Bearer [token],
Update flutterflow
My api groups with Authorization header was deleted.
Try to restore it and create same Api group and wasn't created

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gyfLlvYtNxLRE7qrcae9ajWUQNjI3a700st5Hd0gdCOPrBu02fuP4XFFtXtyraVNcD2e0mmcE+ej1udjtC/Y5PTWZG6E/ws9MSzn0e2iuV8SbO7mCf3wnL9JRIECD1sOJkxEmKrd2LFlk1GeIIfCWTXbDBOu/Zwh9f6PHaOI=

### Context

Return everything as it was

### Visual documentation

![photo_2023-10-19_22-40-34](https://github.com/FlutterFlow/flutterflow-issues/assets/79863395/e718b123-680e-4875-99a0-79963abebc23)
there were profile and questions api groups

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Android and IOS
- Browser name and version: Chrome 118.0.5993.71
- Operating system and version affected: WIndows 11
```

**Comment by kanatbkeeep** [comment]
how i understand after updates it not possible to create groups with same url and maybe because of that all groups except the first one was deleted

**Comment by katherineqian** [comment]
Hi @kanatbkeeep, this issue should now be resolved. We apologize for the disruption.
