### ISSUE TITLE
Error messages after update

### ISSUE THREAD

**Issue by kasdef** [FlutterFlow/flutterflow-issues#1666]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the update I got today, I get an error stating that:
Collection "xx" has field "x-x", which contains an invalid character.

### Expected Behavior

No errors because my app was working fine before the update. 

### Steps to Reproduce

No steps, it is just there

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlPHl0It2seFe1aXqccFB/To5KUM7a4ZNm+1DbwkaNYPNG4gIZfTBXE9uOP25dkFmM2KknTszw6HSm9z1GMcoaBaVf75Jz7VUVQ/xc3yWbr62OqWCYGt+GshUfkCCy6eJghBQFNZsSVYN2UyuA+SsfC3AH7rvDjIFIs+aFJrXmAfuQ0SLb3kNh1JWeC/v

### Context

I can't work on my project any more and I can't publish the project because you can't do this if you have bugs. 

### Visual documentation

**It is just there.**

### Additional Info

I have no additional information 
<img width="272" alt="Scherm­afbeelding 2023-10-19 om 18 51 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/148480509/bfffd1e7-c57b-4998-b6c3-b344a6ba1caf">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: macOS Desktop
- Browser name and version: Chrome 118.0.5993.88
- Operating system and version affected: macOS 13.4.1
```

**Comment by katherineqian** [comment]
This should now be fixed, thank you for reporting.
