### ISSUE TITLE
Error in API Calls

### ISSUE THREAD

**Issue by fellipepfc** [FlutterFlow/flutterflow-issues#1667]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I didn't make any changes to API call groups, but some disappeared. And when trying to create a new group, it doesn't save. Please reverse the error so as not to lose what was done. It would be a lot of work to redo.
https://app.flutterflow.io/project/catelago-virtual-xano-4r9ur3?tab=pageSelector&page=Home

### Expected Behavior

It is working normally and when updating the page the calls disappeared. It wasn't supposed to disappear. I didn't delete the API calls

### Steps to Reproduce

If I go back to the snapshot, no errors appear. (as in the attached image). If you update the page, fix the errors as if I had deleted the API

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

nocode

### Context

As a result, my project is stuck. I can not do anything

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/148478823/15d0ae9f-b374-42c8-a3e1-e5295ea7c7ff)

### Environment

```markdown
- FlutterFlow version: 2.13.7
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 11
```

**Comment by fellipepfc** [comment]
catalogo_xano_principal
https://app.flutterflow.io/project/catelago-virtual-xano-4r9ur3?tab=pageSelector&page=Home

**Comment by SameerShahzad99** [comment]
@fellipepfc As i tested your project, it looks like this issue is no longer appearing, can you please confirm if you are still experiencing any issues?

**Comment by fellipepfc** [comment]
100% ok

Thanks

Em qui., 19 de out. de 2023 16:55, SameerShahzad99 ***@***.***>
escreveu:

**Comment by katherineqian** [comment]
This issue should now be resolved. Apologies for the disruption.

**Comment by fellipepfc** [comment]
hello. The BUG returned. Same problem after updating flutterflow.

**Comment by fellipepfc** [comment]
my api calls disappeared again.
I only received an email that I had paid my invoice

Em qui., 26 de out. de 2023 às 14:00, Kathy Qian ***@***.***>
escreveu:

**Comment by fellipepfc** [comment]
only two groups remained
[image: image.png]

Em qui., 26 de out. de 2023 às 15:22, fellipe cabral ***@***.***>
escreveu:
