### ISSUE TITLE
Custom font uploading not working

### ISSUE THREAD

**Issue by mitch-wyrth** [FlutterFlow/flutterflow-issues#1668]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding new font to project I get the following:

![Screenshot 2023-10-19 at 2 44 42 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/113925566/d1df238f-80c5-4aea-bcf2-010fdcd68952)

Happens when loading new font into existing family as .ttf, new family as set of .ttf files or as a single .otf.

This was working last night without issues.

### Expected Behavior

I expected the files to upload.

### Steps to Reproduce

1. try to upload a custom font
2. watch it not work

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Si/Lqx892rsRE0M7UYMdFqyQWOUA5aLgriOtqEAsYIbGvELQtXOnAVE5pQte0dG9mf2K0mjky0+/emvGWJ8IqC0uZG91jwpBuTzmWdzigMJCwErmwfW5/Dd1PCnHE58PQ2SNQKu5tWHwb2lOPfunJQgDZK5zaC1VEQ/6aD5OK2SrDX1iXc2URm05KZDPz

### Context

We're unable to load fonts to implement our app. Complete blocker.

### Visual documentation

![Screenshot 2023-10-19 at 2 47 14 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/113925566/56f683a5-5c5d-4c9e-8b8e-a793123fccaa)
![Screenshot 2023-10-19 at 2 47 27 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/113925566/3b94e051-ae10-414b-abe4-561949d47c2a)
![Screenshot 2023-10-19 at 2 47 36 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/113925566/2a1d4c5c-c43d-4625-82ad-c3082d8aab51)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:macbook pro/apple chip
- Browser name and version: chrome current
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
@mitch-wyrth thank you for submitting this issue I was able to reproduce this problem on my end!

**Comment by SameerShahzad99** [comment]
A similar problem is being faced while uploading the Lottie animation files.

**Comment by katherineqian** [comment]
Hi, the issue should be fixed now. Thanks for reporting and sorry about the inconvenience.
