### ISSUE TITLE
Multiple Marker from user Document -> location crashing when LATLANG is not available.

### ISSUE THREAD

**Issue by EiffelApp** [FlutterFlow/flutterflow-issues#167]
**Expected behavior** - when a new user signs up or a user decides not share the location, the Google Map shoould not crash IF it is getting LatLang data from User Document -> Location

**Current behavior** - When a user doesnt share the location OR when user is first signing up, everyone elses screen goes red as the app receives NULL values for LatLang

**Steps To Reproduce - example:**
1. Create a map
2. multiple, latlang, and user document - location for markings
3. delete one of the user's latlng on Firebase completely.
4. See the red screen.

**Context** - I am trying to show locations of ALL new/existing users IF they allowed location sharing and of their location on Google Maps via Multiple Marker.

**Screenshots / recordings - BELOW**

**Your environment**
*** Version of FlutterFlow used: FLUTTER 3.34
* Platform (e.g. Web, MacOS Desktop): MacOS
* Operating system and version (desktop or mobile): Desktop...testing it on iOS and Android Simulator.**

Here is what it looks like. 🙂 This is the moment when I manually deleted a location of a user while other devices where listening in

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-27 at 16 11 35](https://user-images.githubusercontent.com/1294007/204123792-dc1739d6-4435-43fb-b498-c2ca3dbd370c.png)

**Comment by wenkaifan0720** [comment]
Hi @KJYoo1989 . Could you share with me the generated code of this page? Thank you!

**Comment by KJYoo1989** [comment]
so on firebase if the location value is missing from one of the users and i hot restart the app, this is what i get: 

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building StreamBuilder<List<UserRecord>>(dirty, state:
_StreamBuilderBaseState<List<UserRecord>, AsyncSnapshot<List<UserRecord>>>#aedbe):
Null check operator used on a null value

The relevant error-causing widget was:
  StreamBuilder<List<UserRecord>>
  StreamBuilder:file:///Users/kjyoo/Downloads/Untitled/lib/map_screen/map_screen_widget.dart:47:12

When the exception was thrown, this was the stack:
#0      _MapScreenWidgetState.build.<anonymous closure>.<anonymous closure> (package:eiffel/map_screen/map_screen_widget.dart:143:49)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:51:28)
#6      ListIterable.toList (dart:_internal/iterable.dart:213:44)
#7      _MapScreenWidgetState.build.<anonymous closure> (package:eiffel/map_screen/map_screen_widget.dart:144:28)
#8      StreamBuilder.build (package:flutter/src/widgets/async.dart:444:81)
#9      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#10     StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#20     _invoke (dart:ui/hooks.dart:148:13)
#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#22     _drawFrame (dart:ui/hooks.dart:115:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by KJYoo1989** [comment]
Thank you so much @wenkaifan0720 :)

**Comment by KJYoo1989** [comment]
Since the app crashes when you get null values from firestore, maybe you can build in a function where if the value is Null, it ignores it. I found in the community someone created a custom function like this: https://community.flutterflow.io/c/discuss-and-get-help/app-is-crashing-in-ios-when-trying-to-load-pictures#comment_wrapper_11914791

![image](https://user-images.githubusercontent.com/1294007/204358663-eb8ff269-fc42-4bbf-9202-e25e0c6fb7d5.png)

**Comment by wenkaifan0720** [comment]
This custom function approach could work. Could you paste the generated code of the page? I mean the Flutter code instead of the debug messages.

**Comment by KJYoo1989** [comment]
Ah sorry i misunderstood. Here it is: 

import '../auth/auth_util.dart';
import '../backend/backend.dart';
import '../components/notification_widget.dart';
import '../flutter_flow/flutter_flow_google_map.dart';
import '../flutter_flow/flutter_flow_theme.dart';
import '../flutter_flow/flutter_flow_util.dart';
import '../instagram_page/instagram_page_widget.dart';
import '../postphoto_screen/postphoto_screen_widget.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';

class MapScreenWidget extends StatefulWidget {
  const MapScreenWidget({Key? key}) : super(key: key);

  @override
  _MapScreenWidgetState createState() => _MapScreenWidgetState();
}

class _MapScreenWidgetState extends State<MapScreenWidget> {
  LatLng? currentUserLocationValue;
  final scaffoldKey = GlobalKey<ScaffoldState>();
  LatLng? googleMapsCenter;
  final googleMapsController = Completer<GoogleMapController>();

  @override
  void initState() {
    super.initState();
    // On page load action.
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      logFirebaseEvent('MAP_SCREEN_PAGE_MapScreen_ON_PAGE_LOAD');
      if (valueOrDefault(currentUserDocument?.uploadedPhoto, '') == null ||
          valueOrDefault(currentUserDocument?.uploadedPhoto, '') == '') {
        logFirebaseEvent('MapScreen_navigate_to');
        await Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => PostphotoScreenWidget(),
          ),
        );
      } else {
        if (valueOrDefault(currentUserDocument?.instagramId, '') == null ||
            valueOrDefault(currentUserDocument?.instagramId, '') == '') {
          logFirebaseEvent('MapScreen_navigate_to');
          await Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => InstagramPageWidget(),
            ),
          );
        }
      }
    });

    logFirebaseEvent('screen_view', parameters: {'screen_name': 'MapScreen'});
    getCurrentUserLocation(defaultLocation: LatLng(0.0, 0.0), cached: true)
        .then((loc) => setState(() => currentUserLocationValue = loc));
  }

  @override
  Widget build(BuildContext context) {
    if (currentUserLocationValue == null) {
      return Center(
        child: SizedBox(
          width: 50,
          height: 50,
          child: SpinKitPulse(
            color: FlutterFlowTheme.of(context).primaryColor,
            size: 50,
          ),
        ),
      );
    }
    return StreamBuilder<List<UserRecord>>(
      stream: queryUserRecord(),
      builder: (context, snapshot) {
        // Customize what your widget looks like when it's loading.
        if (!snapshot.hasData) {
          return Center(
            child: SizedBox(
              width: 40,
              height: 40,
              child: CircularProgressIndicator(
                color: FlutterFlowTheme.of(context).primaryColor,
              ),
            ),
          );
        }
        List<UserRecord> mapScreenUserRecordList =
            snapshot.data!.where((u) => u.uid != currentUserUid).toList();
        return Scaffold(
          key: scaffoldKey,
          resizeToAvoidBottomInset: false,
          backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
          body: SafeArea(
            child: GestureDetector(
              onTap: () => FocusScope.of(context).unfocus(),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      Padding(
                        padding: EdgeInsetsDirectional.fromSTEB(0, 10, 0, 10),
                        child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            AuthUserStreamWidget(
                              child: Text(
                                '${valueOrDefault(currentUserDocument?.coin, 0).toString()} coins',
                                textAlign: TextAlign.start,
                                style: FlutterFlowTheme.of(context)
                                    .bodyText1
                                    .override(
                                      fontFamily: 'Bigshot One',
                                      color: Color(0xFFF3C021),
                                      fontSize: 25,
                                      letterSpacing: 2,
                                      fontWeight: FontWeight.normal,
                                    ),
                              ),
                            ),
                            Text(
                              'eiffel',
                              textAlign: TextAlign.start,
                              style: FlutterFlowTheme.of(context)
                                  .bodyText1
                                  .override(
                                    fontFamily: 'Comfortaa',
                                    color: FlutterFlowTheme.of(context)
                                        .tertiaryColor,
                                    fontSize: 25,
                                    letterSpacing: 8,
                                  ),
                            ),
                            NotificationWidget(),
                          ],
                        ),
                      ),
                    ],
                  ),
                  Expanded(
                    child: FlutterFlowGoogleMap(
                      controller: googleMapsController,
                      onCameraIdle: (latLng) =>
                          setState(() => googleMapsCenter = latLng),
                      initialLocation: googleMapsCenter ??=
                          currentUserLocationValue!,
                      markers: mapScreenUserRecordList
                          .map((e) => e.location!)
                          .toList()
                          .map(
                            (marker) => FlutterFlowMarker(
                              marker.serialize(),
                              marker,
                            ),
                          )
                          .toList(),
                      markerColor: GoogleMarkerColor.blue,
                      mapType: MapType.normal,
                      style: GoogleMapStyle.retro,
                      initialZoom: 14,
                      allowInteraction: true,
                      allowZoom: true,
                      showZoomControls: false,
                      showLocation: true,
                      showCompass: false,
                      showMapToolbar: false,
                      showTraffic: false,
                      centerMapOnMarkerTap: false,
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

**Comment by wenkaifan0720** [comment]
@EiffelApp. I understand what is going wrong now. I'll talk to our team and hopefully figure out a fix by the end of this week. Thank you for noticing of this issue.

**Comment by wenkaifan0720** [comment]
I have pushed a fix for this issue. Thank you for raising it!
