### ISSUE TITLE
The chat page will only see up to 30 messages when loading.

### ISSUE THREAD

**Issue by qaz0450** [FlutterFlow/flutterflow-issues#1670]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We did an additional test using the following method.
1. I sent 50 mails from 'test 50' to 'test 01' for chat messages.
Test 50
Test 49
Test 48
...
Test 03
Test 02
Test 01
2. Shut down the app and reconnect.
3. You have confirmed that the first message is 'test 30'.

### Expected Behavior

I thought that if there were more past chat messages, they would load as I scrolled up and I would be able to see more chat history than 30.

### Steps to Reproduce

1. Read the 'flutterflow' official documentation and open a 1:1 chat room.
2. Log in with one account and send at least 30 messages.
3. Exit the app and reconnect.
4. You can see that only 30 messages have been loaded.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

-

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: v4.0 released October 20,2023
- Platform:Web
- Browser name and version: Chrome
- Operating system and version affected: Windows home 11
```

**Comment by hariprasadms** [comment]
Hi @qaz0450 - Thanks for submitting the issue. I have tested 1:1 chat recently and I can confirm that it is working as expected and it loads all chats when you login anytime.

Update issue with your project bug report code and also images/videos to show the issue you are facing. 

You can reach support team to get more help around it before adding issue here.

**Comment by hariprasadms** [comment]
Hi @qaz0450 - Sorry ignore my ealrier comment. I can reproduce the issue after downloading the code. See below. It shows only recent few chat messages. All messages are not displaying.
2023-10-20_13-59-14.mp4

**Comment by qaz0450** [comment]
Thank you for your confirmation. I just hope this problem is solved.

**Comment by agreaves** [comment]
Hi @qaz0450, thanks for the bug report! We will add an option to set the number of messages loaded in the next release!
