### ISSUE TITLE
Can't choose Data Type in Firestore schema builder

### ISSUE THREAD

**Issue by dwatrous** [FlutterFlow/flutterflow-issues#1674]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using FlutterFlow to build an app around an existing Firestore database. One of my fields is a "map", which isn't available under the "Data Type" column. I tried choosing the "Data Type" data type from the pull down, which gives another pull down which I expected to have "map", or similar. The bug is that the second pulldown does nothing. I can't pull it down. If I try to save the field anyway (green checkmark), it doesn't save, but choosing "Data Type" again from the pulldown creates a new row which can't be saved.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/c189a92d-8f91-4a43-8ee8-056612119fb2)

This is in a subcollection. I also don't see any way to update/edit the schema definition. All I can do is delete it and start over, which gives me the same experience.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/5322e07b-e35b-4c6e-a0bd-185674489043)

I'm using the latest version of Chrome and I have the app open in "app move" which shows it outside of a browser window.

### Expected Behavior

I need there to be some way to represent the existing data types of my current firestore database

### Steps to Reproduce

1. click into the Firebase settings from the left icon menu
2. click plus to add the top level collection
3. add some fields
4. click plus to add a subcollection
5. add some normal fields
6. add the intended "map"
7. choose "Data Type" from the pull down in the "Data Type" column
8. attempt to click on what looks like a new pull down to the right which says "Data"
9. click the green checkmark
10. choose "Data Type" from the pull down in the "Data Type" column
11. end up with a new field with the same name. the first field shows "Data (Unknown)"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi8mBx4dIoeEA1oSJbfpaqyQRH1wibZIzjspBZywgfZzzBLN/fPfQPlpvUtyrTXxLe0yMp14Jw+yPit/XFcEDBwWsfJh4zZFqWjrzeF+nMJ+TF7uWXEYlHfhVCB2H1rSziCRSOsdpcXMt7GWEDOmRUnPqNYzROWo8Sq/LZO4=

### Context

I started with the Robin.do app and am modifying it to be the app I need it to be. There is an existing Firestore database with a pre-defined schema including a subcollection

### Visual documentation

See screenshots above

### Environment

```markdown
- FlutterFlow version: V4.0 (released October 19, 2023)
- Platform: Web
- Browser name and version: 118.0.5993.70 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

**Comment by mattholdsme** [comment]
I am getting similar issues but mainly around testing custom functions. I have found that package for firestore was updated 27 hours ago and may have impacted our core packages.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10339007/48e44fec-27c5-47ee-9a2c-d8719c5cad18)

**Comment by hariprasadms** [comment]
Hi @dwatrous -  Thanks for submitting the issue. After creating a datatype in the datatype section, you can see it in the dropdown. Refer this [doc](https://docs.flutterflow.io/data-and-backend/custom-data-types) 

It is not a bug. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/befaa654-6cec-42aa-9431-82c5fb832141

**Comment by dwatrous** [comment]
Thanks, this got me farther along, but I have another question. I have one bit of data that has two forms

```
{
    "dayofweek": 6,
    "timeofday": {
        "type": "fixedtime",
        "value": [
            23,
            0
        ]
    }
},
{
    "dayofweek": 6,
    "timeofday": {
        "type": "relativetime",
        "value": {
            "sunevent": "sunrise",
            "sunposition": "before",
            "deltaminutes": 5
        }
    }
}
```

`timeofday` can be either fixedtime or relativetime. Is there some way to represent this as a datatype?
