### ISSUE TITLE
Email Verification Issue

### ISSUE THREAD

**Issue by jahnavipatti** [FlutterFlow/flutterflow-issues#1675]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Once a user verifies their email, the initial evaluation for the "email is verified" condition incorrectly returns "false". On running the check again without making any changes, it correctly indicates "true". There's some issue with refreshing the "is verified" state in FF

### Expected Behavior

Once the user verifies their email, the "is verified" condition should immediately return true. 

### Steps to Reproduce

1. Set up an account registration page.
2. Send a verification link to the user's email when the "Create an Account" button is pressed.
3. Implement a conditional check: If user email "is verified" equals true, navigate to the homepage, else display a popup error.

You'll notice that even once the user's email is verified, the initial check results in an error message. However, on the second click the user is correctly navigated to the homepage

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

// Generated code for this Button Widget... Align(   alignment: AlignmentDirectional(0.00, 0.00),   child: FFButtonWidget(     onPressed: () async {       logFirebaseEvent('CREATE_ACCOUNT_CONTINUE_WITH_GOOGLE_BTN_');       logFirebaseEvent('Button_auth');       GoRouter.of(context).prepareAuthEvent();       final user = await authManager.signInWithGoogle(context);       if (user == null) {         return;       }       logFirebaseEvent('Button_backend_call');       await currentUserReference!.update(createUsersRecordData(         count: 1,       ));       logFirebaseEvent('Button_navigate_to');       context.pushNamedAuth('question0', context.mounted);     },     text: 'Continue with Google',     icon: Icon(       Icons.add,       color: Colors.transparent,       size: 20,     ),     options: FFButtonOptions(       width: 240,       height: 44,       padding: EdgeInsetsDirectional.fromSTEB(0, 0, 0, 0),       iconPadding: EdgeInsetsDirectional.fromSTEB(0, 0, 8, 0),       color: FlutterFlowTheme.of(context).primaryBackground,       textStyle: FlutterFlowTheme.of(context).titleSmall.override(             fontFamily: 'Plus Jakarta Sans',             color: FlutterFlowTheme.of(context).accent2,             fontSize: 14,           ),       elevation: 4,       borderSide: BorderSide(         color: FlutterFlowTheme.of(context).primaryBackground,         width: 0,       ),     ),   ), )

### Context

Email verification is a critical component of the account creation workflow. We need to ensure that users are signing up with a valid email address. The issue with the authenticated user's "email is verified" state is delaying our launch 

> 

> 

### Visual documentation

<img width="1435" alt="console after verification check" src="https://github.com/FlutterFlow/flutterflow-issues/assets/148546599/ab7230a5-b1c7-4b63-a9fc-47d2d113a60a">
<img width="1431" alt="console before verification check" src="https://github.com/FlutterFlow/flutterflow-issues/assets/148546599/54086ebb-86dd-44bd-a8c8-8cb09f921395">
<img width="1270" alt="email verification action workflow" src="https://github.com/FlutterFlow/flutterflow-issues/assets/148546599/f1727330-6c86-4184-8250-7aba48beb3a5">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 118.0.5993.70
- Operating system and version affected: macOS Ventura 13.5.2
```

**Comment by Exter007** [comment]
Same issue !

**Comment by takashiff** [comment]
Hello, thank you for the bug report. We have recently created a fix for this issue, and it should be reflected in our next deploy. Thank you for continued patience!
