### ISSUE TITLE
API call JSON body on iPad gives "uknown formatting error in JSON body" error.

### ISSUE THREAD

**Issue by waltartist** [FlutterFlow/flutterflow-issues#1677]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to follow this tutorial for logging user in with Xano:
[https://youtu.be/2j5si0uOyCc?t=301](url)

I'm using FF on iPad. (the ipad app) and on it it seems to give error "uknown formatting error in JSON body" if i try to do the same as in the tutorial. On PC i didn't get this issue.

### Expected Behavior

Adding the body would work the same as on PC.

### Steps to Reproduce

1. On flutterflow iPad app add a POST type API call
2.  Add variables "password" and "email"
3.  Add JSON type body and paste this there 

{
  "email": "",
  "password": ""
}

4. Try to drag the variables to the brackets and hit Format. The error should pop up.
5. You can see how it is done here: [https://youtu.be/2j5si0uOyCc?t=301](url)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMn1z8p2xcdG0KqNcu9VqCQQKW1+UK00sNobbxAjIoDoPJkUaeDsVE5WTszmYGx5KEWIuEwy+PDFvvPiVvYFCzGdGqpi1rVicAGVRmq/aoSNOpaodXZATJ5Xf1C+0MGVnRRAPvJYdU4Q2HGmf9+tUgXfJu77Zwh9f6PHaOI=

### Context

I'm trying to use Xano with the Flutterflow app on iPad but apparently its not possible.

### Visual documentation

![IMG_2270](https://github.com/FlutterFlow/flutterflow-issues/assets/148568861/1520ce43-aac4-44ee-96e9-05f378cea670)

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform: iPad
- Browser name and version:
- Operating system and version affected:
```

**Comment by sbis04** [comment]
Hi @waltartist, thanks for reporting the issue. It seems like the formatting issue could be because of the quotes (`"`) parsed as different a Unicode character on iPad. Can you please try the solution posted [here](https://github.com/FlutterFlow/flutterflow-issues/issues/1511#issuecomment-1773276171)?

**Comment by waltartist** [comment]
> Hi @waltartist, thanks for reporting the issue. It seems like the formatting issue could be because of the quotes (`"`) parsed as different a Unicode character on iPad. Can you please try the solution posted [here](https://github.com/FlutterFlow/flutterflow-issues/issues/1511#issuecomment-1773276171)?

Yes that solution seemed to fix this issue, thanks!

**Comment by sbis04** [comment]
Hey @waltartist, this should be fixed in the next FlutterFlow iPad app update! It should now work even with "Smart Punctuation" ON.
