### ISSUE TITLE
API call returns security errors

### ISSUE THREAD

**Issue by jessieplaydatecare** [FlutterFlow/flutterflow-issues#1678]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When test API call or trigger API call from actions, it returns the following error:
Deceptive site ahead
Attackers on agile-ridge-02432.herokuapp.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).

It was working fine yesterday (10/19/2023)

### Expected Behavior

I tested the same API call in postman, it works fine, but when trigger from FF, above error occurs. 

### Steps to Reproduce

Test an API call (Post request)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMn1z8pgod9Y0LrtbfowiikvIjsnap08lut+Z0scGIjyG7l/TMnOVBJuOLC0dGx6JVqZuHM1+ffemvHLN/EoGzmrUbpm/qVyVA2WXkCQM7q1Dc2gVG5/DedgG2mMyKuz2xR/JrdvSGwn2k2hONyvEnfvQL60C0dFAP+YC5OK2SrDX1iXc2URm05KZDPz

### Context

Blocker issue

### Visual documentation

![Screen Shot 2023-10-20 at 1 25 46 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/104877660/44f9a560-ae9e-4702-b163-c29443fd6cb4)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Macbook Pro
- Browser name and version: Chrome
- Operating system and version affected: Mac OS 11.7.10
```

**Comment by KelpME** [comment]
I have the same issue going on here

**Comment by phoenixshawcollery** [comment]
Same, on Chrome. Breaking my app. OpenAI API call, if that matters.

**Comment by hariprasadms** [comment]
Hi @jessieplaydatecare - Thanks for posting the issue. Are you still experiencing the same issue ?

**Comment by jessieplaydatecare** [comment]
Hi @hariprasadms , it works fine now, thank you

**Comment by paulVu** [comment]
I'm still in this issue, 
https://community.flutterflow.io/c/bugs/post/is-it-a-virus-of-my-computer-or-flutterflow-bug-5GLOXzVk7KPLpoH

**Comment by paulVu** [comment]
When I try to "Test mode" I get it many time

**Comment by LucasThin** [comment]
Having the same issue but calling out to n8n workflow

**Comment by fullpixelco** [comment]
Still having this issue

**Comment by alexruimy** [comment]
also having this issue.
