### ISSUE TITLE
Project is not running after the latest update

### ISSUE THREAD

**Issue by Philippez3r** [FlutterFlow/flutterflow-issues#1679]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i try to test/run/build an apk it just gives me an error that appears right after the latest update... 19 October and still persist on version of 20 October.
I get this text on each try to build:

TEST MODE
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/home/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/extended_image.dart:976:36: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/sdks/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/sdks/flutter/packages/flutter/lib/src/painting/border_radius.dart').
              borderRadius: widget.borderRadius,
                                   ^
/home/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:202:13: Error: 'ImageTilingInfo' isn't a type.
      final ImageTilingInfo info =
            ^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:203:11: Error: Method not found: 'createTilingInfo'.
          createTilingInfo(repeat, rect, destinationRect, sourceRect);
          ^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/extended_image_library-3.5.2/lib/src/network/network_image_web.dart:25:10: Error: Method not found: 'createDomXMLHttpRequest'.
  return createDomXMLHttpRequest();
         ^^^^^^^^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/extended_image_library-3.5.2/lib/src/network/network_image_web.dart:166:53: Error: The argument type 'Null Function(DomEvent)' can't be assigned to the parameter type 'Never'.
 - 'DomEvent' is from 'package:flutter/src/services/dom.dart' ('/sdks/flutter/packages/flutter/lib/src/services/dom.dart').
      request.addEventListener('load', allowInterop((DomEvent e) {
                                                    ^
/home/.pub-cache/hosted/pub.dev/extended_image_library-3.5.2/lib/src/network/network_image_web.dart:184:64: Error: The argument type 'void Function(Object, [StackTrace?])' can't be assigned to the parameter type 'Never'.
 - 'Object' is from 'dart:core'.
 - 'StackTrace' is from 'dart:core'.
      request.addEventListener('error', allowInterop(completer.completeError));
                                                               ^
Waiting for connection from debug service on Web Server...         66.6s
Failed to compile application.

RUN MODE a bit different:

Error: Command failed: flutter build web  --web-renderer html --no-pub --no-version-check --no-tree-shake-icons
Target dart2js failed: ProcessException: Process exited abnormally:
/opt/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/extended_image.dart:976:36:
Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/sdks/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/sdks/flutter/packages/flutter/lib/src/painting/border_radius.dart').
              borderRadius: widget.borderRadius,
                                   ^
/opt/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:202:13:
Error: 'ImageTilingInfo' isn't a type.
      final ImageTilingInfo info =
            ^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:203:11:
Error: Method not found: 'createTilingInfo'.
          createTilingInfo(repeat, rect, destinationRect, sourceRect);
          ^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/extended_image_library-3.5.2/lib/src/network/network_image_web.dart:25:10:
Error: Method not found: 'createDomXMLHttpRequest'.
  return createDomXMLHttpRequest();
         ^^^^^^^^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/extended_image_library-3.5.2/lib/src/network/network_image_web.dart:166:53:
Error: The argument type 'Null Function(DomEvent)' can't be assigned to the parameter type 'Never'.
 - 'DomEvent' is from 'package:flutter/src/services/dom.dart' ('/sdks/flutter/packages/flutter/lib/src/services/dom.dart').
      request.addEventListener('load', allowInterop((DomEvent e) {
                                                    ^
/opt/.pub-cache/hosted/pub.dev/extended_image_library-3.5.2/lib/src/network/network_image_web.dart:184:64:
Error: The argument type 'void Function(Object, [StackTrace?])' can't be assigned to the parameter type 'Never'.
 - 'Object' is from 'dart:core'.
 - 'StackTrace' is from 'dart:core'.
      request.addEventListener('error', allowInterop(completer.completeError));
                                                               ^
Error: Compilation failed.
  Command: /sdks/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /sdks/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/sdks/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/a794cf2681c6c9fe7b260e0e84de96298dc9c18b/ --native-null-assertions --no-source-maps -o /tmp/ff_service_scratch/OBQT1lQcTeDbNZPfSfAC/legit_auth/.dart_tool/flutter_build/ab3a3098cd0276e0ecb3b3bdc8d74c3b/app.dill --packages=.dart_tool/package_config.json --cfe-only /tmp/ff_service_scratch/OBQT1lQcTeDbNZPfSfAC/legit_auth/.dart_tool/flutter_build/ab3a3098cd0276e0ecb3b3bdc8d74c3b/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)

Exception: Failed to compile application for the Web.

### Expected Behavior

It just should compile it without any errors

### Steps to Reproduce

Just run a test or run mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjPHl7Y9ItbxY0KXqdu9WjjoXKWl6R700sNobbxAjIoDoPJkUaeP7TBBvZO6qS1FpKEWJu3EKwvzluNriGsA4AxacboRFz5BqUT3JTni/aoSzBqmKSndPEf5MCmKg0cGzqhRQJvZqc0Zi7V2UJ+mvFj7tK737Zwh9f6PHaOI=

### Context

i just need to build the final version and i cant with this fake error

### Visual documentation

Just run a test/Run mode
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124400035/63bfc221-0056-43b1-af23-06612e6d43d8)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124400035/54167864-8e3f-42ca-bf54-d6e73c946a1d)

### Environment

```markdown
- FlutterFlow version: 4.0 released October 20, 2023
- Platform: WEB
- Browser name and version: Chrome 118.0.5993.89
- Operating system and version affected: Windows 10
```

**Comment by Philippez3r** [comment]
Thank you! You re right! Have a nice one!

**Comment by nickydlt** [comment]
@Philippez3r where did you find that package to update it? I'm experiencing exactly the same problem but don't see that package included in any of my custom code.

**Comment by Philippez3r** [comment]
> nickydlt

I was using one of my custom widget to work with an image this package was there:) You have to probably check more attentive all your custom code :) Gl
