### ISSUE TITLE
Issue with deep links and phone signing

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#168]
## Expected behavior (required)

1. I go to the application via a link (deep link)
2. The registration window opens, because the screen I come to has the "Required Authentication" settings
3. I enter a phone number
4. The SMS input screen opens.
5. I enter the SMS code.
6. The page opens to which I clicked on the link from the first paragraph

## Current behavior (required)

1. I go to the application via a link (deep link)
2. The registration window opens, because the screen I come to has the "Required Authentication" settings
3. I enter a phone number
4. The SMS input screen opens DON'T OPEN

## To Reproduce (required)

1. Create new project with 4 screen: Login (use phone authentication), SMS Verification, Home (requires authentication), Screen with some info (requires authentication)
2. Enable deep link and Firebase dynamic links
3. Set up Firebase dynamic links in the firebase project and setup scheme in the app setting in FF
4. Try to open link from second paragraph
5. The screen with login will open
6. Screen with SMS code will not open

## Context (required)

I'm trying to make a project with the transition to the screen about the information I need using SMS login

## Your environment

* Version of FlutterFlow used: 3.0 18 November
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @oper2k, thanks for reporting your issue. Could you please add a Bug Report Code to this issue so that I can better investigate?

In the meantime, I'm guessing that the screen with SMS code is marked as "Require Authentication", which means it can only be accessed if the user is logged in (which of course they are not in this case). Please check if this is the case and if so then unchecking this setting should fix it!

**Comment by oper2k** [comment]
Hello

the screen with SMS code is NOT marked as "Require Authentication"

Here is code from phone page:
ITFTzciA3ItIvtsA+KXQbu1KmiI4I0MdXOczitVEew4bCIj4ELAAd+D8altWcMizaH1+MGeJ/VoJ+trKic7LMsJeAxSWGZhz1apAFlyjEA8=

Here is code from sms page
ITFTzciA3ItIvtsA+KXQbu1KmiI4I0MdXOczitVEew4bCIj4EIYMfuP7ZVhoTbWzaHxLe2CWozgCwsrLidnLOMA3A0yaf4g+yqoNd1yjEA8=

**Comment by oper2k** [comment]
> Hi @oper2k, thanks for reporting your issue. Could you please add a Bug Report Code to this issue so that I can better investigate?
> 
> In the meantime, I'm guessing that the screen with SMS code is marked as "Require Authentication", which means it can only be accessed if the user is logged in (which of course they are not in this case). Please check if this is the case and if so then unchecking this setting should fix it!

Hello

the screen with SMS code is NOT marked as "Require Authentication"

Here is code from phone page:
ITFTzciA3ItIvtsA+KXQbu1KmiI4I0MdXOczitVEew4bCIj4ELAAd+D8altWcMizaH1+MGeJ/VoJ+trKic7LMsJeAxSWGZhz1apAFlyjEA8=

Here is code from sms page
ITFTzciA3ItIvtsA+KXQbu1KmiI4I0MdXOczitVEew4bCIj4EIYMfuP7ZVhoTbWzaHxLe2CWozgCwsrLidnLOMA3A0yaf4g+yqoNd1yjEA8=

**Comment by agreaves** [comment]
Hi @oper2k! Thank you for the relevant information. It looks like there was potentially an issue validating the phone number, which could explain why it doesn't go to the next screen. However, in the project you provided it seems to be working with certain phone numbers (that start with "+7"). Can you attach a screen recording of the behavior?

**Comment by oper2k** [comment]
Hello

here is
[https://vsetut.flutterflow.app/vitrina/6978NIFON63saspVi0ND](url)

**Comment by oper2k** [comment]
hi @agreaves any news?

**Comment by agreaves** [comment]
Hi @oper2k, sorry for the delay! This one took quite some time to track down, and is indeed a bug on our end. As you'd imagine, it had to do with redirection during phone authentication - we need to ignore redirects when navigating to the SMS page as unlike other forms of authentication we will not be logged in yet and cannot simply come back to the original deep link.

This will finally be fixed on our next release early next week! 🙂
