### ISSUE TITLE
Create Document Not working

### ISSUE THREAD

**Issue by ash007osh** [FlutterFlow/flutterflow-issues#1685]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to create a document upon a button click or via toggle icon call, it is not happening

### Expected Behavior

When button is clicked or icon toggled, the document should get created

### Steps to Reproduce

1. Create a new Page
2. Create a button
3. Open Action Flow editor
4. Backend Call to Create a Document upon button Click
5. Select a Pre existing collection and try to set some fields.
6. Test by running the Code
7. Click Button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klfHqw89goekB15PtbccwtCc7Q0wjTLJEoetxc0gbfe/4E4k1Psz7ZRFpZMyzaHxYImGKrHEFpejJjuz1JfU6aUmuQYRJz899ExPPbF+RV6q4EaiOPmsnAdxbfWKH16aR3BVDNsRhV1pi2FyEJOytUT6Cf9qOYwx5e6fDbOY=

### Context

Unable to add any document to my firebase DB. This is a show stopper.

### Visual documentation

![bug](https://github.com/FlutterFlow/flutterflow-issues/assets/1225987/d74a09b0-e776-4864-8614-0fce6cc84c11)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: All
- Browser name and version: Chrome Version 118.0.5993.89 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @ash007osh - I looked at your project.  The collection you are trying to create document does not have write access. Update it and deploy the firestore rule. Once you have updated this changes successfully, you should be able to create documents.
