### ISSUE TITLE
Blur Component Performance issue

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#1686]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Blur component when used with multiple items on the same page it's causing huge performance issues.
Here is my setup:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/f4ab3962-5731-4205-ba98-916cdef353e6)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/55b54ca1-769f-4ee9-95d7-c0e286f3b066)

### Expected Behavior

It should work smoothly without any performance issues.

### Steps to Reproduce

1. Create New Page
2. Add new blur widget
3. Duplicate (30-40 items in page)
4. page should be scrollable to be noticed

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcr1z5R1obxY0LXTbfpWoCcXJVx+TL03pu0bFEggGLbrBIYMafekN1hpUu2kdFZHKEWJjnMf09KNiPDlIMECAy+WRb5n+KpyTwLvcDm/aoSmO4eaWEFQP9JjIXK10MGJniVSCMtsW01lw06XfvCva3TcO4f7Zwh9f6PHaOI=

### Context

It's slowing down my app, a huge decrease in performance so I resulted too not using the Blur widget.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/51df2a45-b39a-4102-960c-e53f31fa5d4c)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/faebc493-00be-479d-bbd2-fbe1a4e4cebb)

### Environment

```markdown
- FlutterFlow version: V4.0
- Platform: iOS & Android
- Browser name and version:
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @alih552 - Thanks for submitting the issue. I've tested above mentioned steps, but I do not see any project performance issue. Are you still experiencing the same issue? If so, reproduce the issue in a blank project and send us bug repot code of the same. Include any error information from the browser developer console as well.. These details are essential for us to investigate the issue. Thanks

**Comment by alih552** [comment]
Hi @hariprasadms you need to test on a real device to notice the performance issue. Can you do that and let me know if you still can't find any issues, thanks.
