### ISSUE TITLE
The video on the VideoPlayer stopped showing when returning from full screen on the web.

### ISSUE THREAD

**Issue by davidd108** [FlutterFlow/flutterflow-issues#1687]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on full screen and then click on the option to exit full screen view and return to the page, I am unable to see the video. I can only see the video controls and the background color behind the video, but I can still hear the audio. I have to reload the page in order to see the video on the page. This issue occurs on the web and test mode.

### Expected Behavior

That when I exit full screen, I can still see the video on the page.

### Steps to Reproduce

1-. Create blank page.
2-. Add VideoPlayer widget.
3-. Go to test mode.
4-. Play video.
5-. Go to Full Screen.
6-. Exit full screen.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kls/l6otIm+Fb7qqAbcBsnmU7H0t7TL0vte5+cxQbfpjtB4YqY876P1BvXdPgY29ffVq2p14xwtL2j/zXIfI3Cw6ZGqZR+aoNbRWXJUOWVrWTF7uePURRHcZRfmXG5KSJuBVDOvBhcU0u702Uet+sVj3tO5DrCmo8Sq/LZO4=

### Context

Reproduce video on full screen on my App and being able to exit full screen and keep watching the video.

### Visual documentation

![bugVideo](https://github.com/FlutterFlow/flutterflow-issues/assets/41306199/a16ba1b4-8b8e-4f64-aef1-58fb072061ae)

### Additional Info

It also happens when the project is uploaded to the web 

### Environment

```markdown
- FlutterFlow version: 4.0 - Flutter 3.13.7
- Platform: Web and Test Mode
- Browser name and version: Chrome Version 118.0.5993.88 (Official Build) (arm64)
- Operating system and version affected: Sonoma 14
```

**Comment by hariprasadms** [comment]
Hi @davidd108 - Thanks for submitting the issue. I can reproduce it. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/3a672e70-c71c-495b-9b08-8a5ebd45ae52

**Comment by agreaves** [comment]
Hi @davidd108, thanks for the bug report! I've reproduced the issue and managed to provide a fix, which should be reflected in the next release!
