### ISSUE TITLE
FlutterFlowAudioPlayer does not override didUpdateWidget

### ISSUE THREAD

**Issue by siddharthadevops** [FlutterFlow/flutterflow-issues#169]
## Expected behavior (required)
FlutterFlowAudioPlayer widget must override didUpdateWidget and call openPlayer() in order to set the audio source specified in parameter audio. Otherwise when widget is updated, but not the state, the audio source never changes.  

## Current behavior (required)
When the FlutterFlowAudioPlayer without re-creating the state, the widget plays the previous audio set.

## To Reproduce (required)
1.- Create FlutterFlowAudioPlayer in a StreamBuilder.
2.- Change the audio source parameter in a rebuild of the widget.
3.- Play.

## Context (required)
On a page that updates when the audio source changes in FireBase, the audio source does not change in the widget when the page is rebuilt. So when play is called it plays the sound that was set on the first load of the widget state.

## Your environment
It occurs in all platforms.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next release.

Note: it won't reload if the player is already playing.
