### ISSUE TITLE
NavBar won't appear in run or test mode

### ISSUE THREAD

**Issue by vasov97** [FlutterFlow/flutterflow-issues#1690]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Navbar is shown only in editor, while in test/run mode it can't be seen, or just appears but without nav icons
I have column widget which I wrapped with Stack and placed custom made navbar in the Stack and aligned it at the bottom of the Stack over the Column.

### Expected Behavior

Navbar should be seen at the bottom of the screens

### Steps to Reproduce

1. Create column widget
2. Put enough elements so the column can be scrollable
3. Wrap column with Stack widget
4. Put custom navbar into the stack
5. Align navbar at the bottom of the stack

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8r135ZPm9tY0Lrfbfl4iiQWJmI7TL07ttYbZxUjIuPtBJh/eePRYkhpXby/SmlhHGaKoE4Dwd7Tj9jtV/A6Fw2VR4hj1boBEQLJWXq8R7KJPauaPn9QAeRUJnaY0qa3oCRdKtVfdF1m6k6qDeu/UXbvJ5+/Zwh9f6PHaOI=

### Context

Users can't see navbar when testing the app

### Visual documentation

![breath](https://github.com/FlutterFlow/flutterflow-issues/assets/25417544/136f4bfb-560c-49e3-9fbb-ba7c509c6abe)
 app screen in the editor
![breateh2](https://github.com/FlutterFlow/flutterflow-issues/assets/25417544/d9307561-06a0-458b-9dfa-0f3854ab5db7)
app screen in the run mode

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome Version 118.0.5993.89 (Official Build) (64-bit)
- Operating system and version affected: Not important
```

**Comment by SameerShahzad99** [comment]
This problem seems to be specific to your project and custom implementation, please reach out to support for such cases through emailing at support@flutterflow.io or live chat.

**Comment by Ace-ebuks** [comment]
@vasov97  i am coming across this same issue. Was yours resolved? Regards,
