### ISSUE TITLE
GIT integration feature is absolutely broken

### ISSUE THREAD

**Issue by stefanlenoach** [FlutterFlow/flutterflow-issues#1694]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On multiple occasions now, the new Git integration feature seems catastrophic. Just now I tried to merge a branch into main. "No conflicts" it said. Instead of merging the changes into main, it looks like it merged main into the branch. So the feature we were working on was reverted to the original state. Moreoever the 'history' section does not give you access to the history so it's almost useless. I'm very surprised a normal git integration does not exist in the UI already, this seems essential and relatively straightforward. Anyway I'm upset because on multiple occasions this seems to not work the way it's supposed to and doesn't give any of the assurances, safety, and flexibility that Git is supposed to give. 

### Expected Behavior

Normal git behavior

### Steps to Reproduce

Use the git feature for a little while.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40k8rk27x1rulc+c2AYcZKjjkgQVwKapAWmOtRaCosfZT2BLMcec/RVERWcMviYHNYPVmjo2oW0/PFv9nuUPEVEEiaf4Bm1bhycw3xTXOQMIyWFJWgRmtARMNgGFDA5LWK2hF+KsFtS0Zh2WGMA+uAcAvtNb7bNm4kD6/LZO4=

### Context

Wasted time, has left us have needing to rebuild the same feature multiple times.

### Visual documentation

N/A

### Additional Info

n/a

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: MacOS Desktop
- Browser name and version: N/A
- Operating system and version affected: Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @stefanlenoach - Thanks for submitting the issue. I presume you are taking about branching feature ( You mentioned issue title as Git integration). 

_Instead of merging the changes into main, it looks like it merged main into the branch._

- I have tested it. Merging to respective branches is working fine. I think, there could be mistake while selecting the correct branch to merge. I would suggest look at the project activity log in collaboration section. You can see which merge you did select while merging the changes. Sample is below.

<img width="1169" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8161b4e5-ec8a-4897-8422-eeaa43e4f668">



_Moreover the 'history' section does not give you access to the history so it's almost useless._ 

- Current version of branching feature. History has limited use. It will be improved in future. Add more details about what more functionality you like to see around **History**. 

In overall, we are aware about there few existing issues around branching. Dev team activity working on it. These fixes can improve flexibility around branching functionalities.

**Comment by hariprasadms** [comment]
I am closing the issue as branching and merging working as expected. Thanks
