### ISSUE TITLE
snackbar message text exceeds screen width error.

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#1695]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Here is the snackbar message in lib/flutter_flow/flutter_flow_util.dart
void showSnackbar(
  BuildContext context,
  String message, {
  bool loading = false,
  int duration = 4,
}) {
  ScaffoldMessenger.of(context).hideCurrentSnackBar();
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(
      content: Row(
        children: [
          if (loading)
            Padding(
              padding: EdgeInsetsDirectional.only(end: 10.0),
              child: Container(
                height: 20,
                width: 20,
                child: const CircularProgressIndicator(
                  color: Colors.white,
                ),
              ),
            ),
          Text(message),
        ],
      ),
      duration: Duration(seconds: duration),
    ),
  );
}

### Expected Behavior

void showSnackbar(
  BuildContext context,
  String message, {
  bool loading = false,
  int duration = 4,
}) {
  ScaffoldMessenger.of(context).hideCurrentSnackBar();
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(
      content: Row(
        children: [
          if (loading)
            Padding(
              padding: EdgeInsetsDirectional.only(end: 10.0),
              child: Container(
                height: 20,
                width: 20,
                child: const CircularProgressIndicator(
                  color: Colors.white,
                ),
              ),
            ),
          Expanded(
            child: Text(
              message,
              softWrap: true,
              overflow: TextOverflow.visible,
            ),
          ),
        ],
      ),
      duration: Duration(seconds: duration),
    ),
  );
}

### Steps to Reproduce

find default snackbar message in lib/flutter_flow/flutter_flow_util.dart

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

snackbar message text exceeds screen width error.

### Context

snackbar message text exceeds screen width error.

### Visual documentation

null

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi - No blank project and project bug report code is provided. In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by hariprasadms** [comment]
Hi @simon-zhangmuye - Any updates about required details ? If you already have found a solution of the issue, you can close the issue. Thanks

**Comment by simon-zhangmuye** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10706610/50362f8c-3f92-4755-8b01-a96ad24a331a)
There is no update in your snackbar message in flutter_flow_util.dart file. Some messages are too long and cannot be shown in such a way.

**Comment by simon-zhangmuye** [comment]
Use an expanded widget to wrap text like this.
Expanded(
            child: Text(
              message,
              softWrap: true,
              overflow: TextOverflow.visible,
            ),
          ),

**Comment by hariprasadms** [comment]
Hi, As there are not required reproducible steps and project details provided, I presume you found the solution for the above issue., Hence i am closing the issue.
