### ISSUE TITLE
Template page "Profile 10" crashes straight after creation from blank project

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#1696]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Creating a template page from "Profile 10" template list in a blank project crashes the designer and it is not created, regardless of the name given to it and whether I choose to use my theme or the template theme.

### Expected Behavior

The template page from "Profile 10" is created without errors, regardless of the name given to it (provided it is not taken yet) and whether I choose to use my theme or the template theme.

### Steps to Reproduce

1. Create blank project
2. Add new page
3. Select "Profile 10" template (regardless of using My Theme or Template Theme)
4. Give it any name (provided it is not taken yet)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

There's no widget since no page was created

### Context

I'm trying to start a design from that template because I liked it at first glance, but this error won't let me even start it.

### Visual documentation

1 - Create blank project

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8472285/66b11fa8-6389-41a5-a69d-10a090e563f9)

2 - Add new page

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8472285/37de5d70-ed8e-43ff-ba43-c3831260ed02)

3 - Select "Profile 10" template (regardless of using My Theme or Template Theme)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8472285/57700e9f-0e17-4f04-8453-fd6b5bea5da5)

4 - Give it any name (provided it is not taken yet)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8472285/5a64cd83-994e-47d0-bcbf-2b0aba2d9f3e)

5 - Crashes

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8472285/3919695f-fb3b-4b7f-8b13-79a49b6701bf)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Brave version 1.59.120
- Operating system and version affected: Windows 11 Pro 64 bits (version 22H2, build 22621)
```

**Comment by hariprasadms** [comment]
Hi @vitoras - Thanks for submitting the issue. I can reproduce it.

**Comment by agreaves** [comment]
Hi @vitoras, thank you for the bug report! We have disabled this template page for now and will fix it in the near future!
