### ISSUE TITLE
Custom code - Calling a widget which has internationalization

### ISSUE THREAD

**Issue by Thesergiolg99** [FlutterFlow/flutterflow-issues#1699]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1) Ive created a widget with flutterflow UI builder with language dependent texts
2) Created a custom widget that returns the UI widget from step 1
3) When running, i get a NULL when showing the widget

It happens with any widget with language dependent texts, that you want to call from custom code.

NOTE: If you navigate to that widget with an action in the UI builder, no NULL appears.

### Expected Behavior

Show the widget with no problems or nulls

### Steps to Reproduce

1) Create a page with  UI builder which contains language dependent texts.
2) create a custom widget and return the Page created in step 1.
3) NULL appears.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kj8ncx891oelJ7aqIbe1KvCAXNnk1TLJEpu0bWUkbGO/4P4YtPOClahZCZ/KzaH1qMWCWkngHwsrJj4bhMfA6G0mqfLpjzpdUZBPPbGWlbr6OPajtfUEmI8NUIW6916S7pBFSHOluWXwk702ENeu/fz6Cf9qOYwx5e6fDbOY=

### Context

I want from a custom widget to show a widget page (that contains language dependent text) that ive created with UI builder.

### Visual documentation

![Error](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/3a34ea9d-5e50-4163-a256-d7a4dd0e7882)
![widget](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/39348913-fa28-4633-a5b1-ef2455663b2b)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: WINDOWS 11
- Browser name and version: Google Chrome Latest Version
- Operating system and version affected: WINDOWS 11
```

**Comment by hariprasadms** [comment]
Hi @Thesergiolg99 - Thanks for submitting the issue. I looked at the given project but not able to locate the issue as there are more number of pages. Considering the nature of the issue. You should setup a blank project with issue step reproducable details. Without these details we can't investigate the issue. 

 We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!
