### ISSUE TITLE
APK build failing with: Current version of plugin supports minimal Gradle version: 6.8

### ISSUE THREAD

**Issue by bnorw24** [FlutterFlow/flutterflow-issues#170]
Hello! Getting this error when attempting to download APK from FF editor. If I download the code and attempt to run, I get the same error. If I update the gradle URL in Android Studio with version 7.0.2 I am able to run locally but obviously this does not fix the issue in FF. I think it may be related to enabling the in app notifications, but unsure. Experienced this issue around the same time as that. 

To get around, I download the code, update the gradle distribution URL from 
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
to 
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip
then I build the APK locally. 

If someone could update this in my project forever, that would be amazing, sad I cant use the premium feature I'm paying for :( 

**Expected behavior** - Able to download APK without error or download and run code without updating gradle version manually

**Current behavior** - Download APK throws error and downloading and running code requires a manual update to gradle version

**Steps To Reproduce** (in my project, message me for project link):
1. Download APK
2. Notice error
OR
1. Download code
2. Run app
3. Notice error

**Context** - I am unable to download APK for app distribution on Firebase and am unable to

**Screenshots / recordings** -
<img src="https://user-images.githubusercontent.com/47465401/204337577-59bf1758-7c3f-4492-a67f-e0cd4b7dd378.png" width="300" />

**Your environment**
* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web/Android Studio on Windows Desktop
* Browser name and version: Chrome/107.0.5304.88 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Desktop/Windows 11

**Comment by bnorw24** [comment]
Someone else is experiencing this issue: https://community.flutterflow.io/c/bugs/apk-build-failing-in-ff-editor-with-current-version-of-plugin-supports-minimal-gradle-version-6-8

**Comment by agreaves** [comment]
Hi @bnorw24! Thanks for finding and reporting this issue! We'll update the active gradle version 7.0.2, so this issue will be fixed on our next release 🙂
