### ISSUE TITLE
cant sign in using phone

### ISSUE THREAD

**Issue by Zoka98** [FlutterFlow/flutterflow-issues#1701]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i **Enabled** the phone sign in provider in the firebase and set everything good(sign in page and OTP, actions everything, and i still get this error, 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/109471773/85c726b1-8660-4cc7-92c2-7d3d7c8fb5d8)

### Expected Behavior

i expect to log in with phone number 

### Steps to Reproduce

1. i fill the field with the country code and phone i set in the test phone numbers.
2. i press a button that has phone sign in action and taking the number from the field, and a page with pin code field is set to be automatically redirected to.
3. nothing happens, and i get this error in the console 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/109471773/b4dc4a40-3de0-4a9b-8662-006cfa81a700)

**even tho i enabled the phone provider and the project is connected to the firebasee i can CRUD docs **

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slfLl8YlPm+Fc18/ubMB7/WEWJVh9bZ0WscsZa0kdB4joPLJ/d87eRxZVZN+/Y3lhHFGYnn4F/tLOkvPXOscFPSiZbNg4/qgBTzzhc3q8R7LSCsywXX96EdxTGm65y8CnnRFTOrRqLngfwU+MP+jIEjDsCZ+/Zwh9f6PHaOI=

### Context

sign in using phone 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/109471773/7594c57f-7f70-4096-98e9-98342de6f468)

### Environment

```markdown
- FlutterFlow version: v4.0-Flutter3.13.7
- Platform: desktop
- Browser name and version: chrome
- Operating system and version affected: desktop
```

**Comment by hariprasadms** [comment]
Hi @Zoka98 - Thanks for submitting the issue. Can you confirm below authentication settings for phone long is enabled in your project? Please check and confirm. 

<img width="930" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/fe039abd-f868-487b-81d6-cbeae0722c01">

**Comment by hariprasadms** [comment]
Do one more check. have you given test phone number and sample verification code? If these details are given. You should try to login with the same phone number. 

I confirmed phone login is working fine and also I do not have access your firebase project settings. I would suggest reach out technical support team to get more help around missing configurations. If they confirm this is not working in your project and more bug details. You can come back her to update the issue with more details.

**Comment by Zoka98** [comment]
thanks for your time, the problem was that the created testing phone's country code wasnt matching the one in the list of regions,
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/109471773/9b2fde43-9199-49d3-aed8-4c51ee82987a)
once i created a testing number with the right country code it worked :).
