### ISSUE TITLE
Calendar DATE filter is looking for exact match from Firebase DATETIME timestamp, resulted in 0 results being filtered

### ISSUE THREAD

**Issue by jessieplaydatecare** [FlutterFlow/flutterflow-issues#1702]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Store the date in firebase
follow this instruction to set the calendar(https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/calendar#querying-a-collection)
- Setting the date from firebase to flutterflow's page variable "selectedDate"
- Query the collection then filter it by setting "startDate" (from firebase) equal to page variable (which was set to calendarSelectedDate)

If the date source in firebase is stored as Oct 23, 2023 at 12:00:00AM UTC-7, the filter will work
Otherwise the filter will return nothing because it looks for not just a date match but also a time match

### Expected Behavior
Store some random date time data from Firebase, with different time other than 12:00:00AM UTC-7. 
Should work as this document suggested https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/calendar#querying-a-collection

### Steps to Reproduce

https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/calendar#querying-a-collection

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMn1z8pgod9Y0LrtbfowiikvIjsnap08lut+Z0scGIjyG7YAQszOSBJaZ+m+Sgo3OWGkrHwK06yMkfbIN/QEGzmafr5/yLhxFwGVbH2XSqXTO6WaOX9PINpKCFCC0ImskSNdNsl2cXga7Ey6AuuAZDfaGYTwCkgFR8mbIqT7nXPuQ0SLb3kNh1JWeC/v

### Context

Blocker issue

### Visual documentation

no

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Macbook Pro
- Browser name and version: Chrome
- Operating system and version affected: Mac OS 11.7.0
```

**Comment by hariprasadms** [comment]
Hi @jessieplaydatecare - Thanks for submitting the issue. I can reproduce the result what you are expecting. However, I can confirm that it is not a bug but it can be feature enhancement. 

Note - You can resolve this by extracting the date formate using custom function. 

In the collection you can define fields to store date with **_Date Time_** type ( it is not just a date type ) that means, in the backend it stores the date with a time stamp ( formate is Oct 23, 2023 at 12:00:00AM ). Thats the reason in action while selecting date only type, it stores the date in the same formate. You can resolve this by storing dates in the **_Date Time_** formate ( formate Oct 23, 2023 at 12:00:00AM ). This can help to filter the way you are expecting.

**Comment by katherineqian** [comment]
Closing as a feature request.
