### ISSUE TITLE
Custom Headers not recognised 

### ISSUE THREAD

**Issue by DevinFlorentino** [FlutterFlow/flutterflow-issues#1703]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have added custom headers to a web published domain.

Example of the headers we added:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'">
<meta http-equiv="Permissions-Policy" content="default-src 'self'">
<meta http-equiv="Referrer-Policy" content="no-referrer">
<meta http-equiv="Strict-Transport-Security" content="max-age=31536000; includeSubDomains">
<meta http-equiv="X-Content-Type-Options" content="nosniff">
<meta http-equiv="X-Frame-Options" content="DENY”>
```

This is so the project can successfully pass the tests at [https://securityheaders.com](https://securityheaders.com/)

However, when we add these custom headers, the test doesn’t pick them up, so it fails.

### Expected Behavior

The custom headers should be recognised and project should successfully pass the tests at [https://securityheaders.com](https://securityheaders.com/)

### Steps to Reproduce

1. Add the custom headers
2. Publish the web app
3. Go to https://securityheaders.com/ 
4. Scan the domain

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8Cksn63492vsdY+KXqYPpVnjw5KUg5arsviu1qEBAjCOvuPLd3ePTBM05uSbSkTHxYfE79gVgVwtbVheP9D8FdKRaXGdg++roNEjmVdzqzaq64C8+KYUFPGfJbfHHEyMO0kSZvPvdpLloe62KtLNyXbBHbQoC2C1gWRMn9MpPL+HjiLg7VJydE4wsIRmW0OcoQbBG3yM+UtpJh0eDnyw==

### Context

The project has to pass the scan. For security reasons.

### Visual documentation

Issue:
<img width="1229" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52498399/45ddec3f-b060-4fc8-9e01-45b724df111e">

Example of expected outcome:
<img width="658" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52498399/6e49c2d9-4688-4d76-876f-39b688f2552c">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome - Version 118.0.5993.88 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.0 (23A344)
```

**Comment by hariprasadms** [comment]
Hi @DevinFlorentino - I just marked this site as bug. But I'm not fully sure the header of websites built in FlutterFlow is fully compatible with header security check the way you are trying to do. Dev team will decide the status of it when they are ready to pick this for investigation. No ETA. Thanks

**Comment by wenkaifan0720** [comment]
@DevinFlorentino, @hariprasadms. Unfortunately not all these tags are not supported by the current FF web publish. Since this is more like a feature request, I will close this issue for now.
