### ISSUE TITLE
cached image load lag IOS

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#1707]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

see the post in the community here. there is a lag with loading the cached images on iphone. 

https://community.flutterflow.io/c/bugs/post/image-cacheing-dyamic-children-not-working-ios-RJBn9oJ5nCMddfz

### Expected Behavior

On web, cached images load instantly in a carosel or page. On IOS, doesnt seem to be the case. As you can see in the video, it shows the background before loading. 

### Steps to Reproduce

1. take pictures on your iphone 
2. upload multiple images to a field in a list 
3. Create new page
4. add carosel or page view
5. add image to a page
6. dynamically generate page view or carosel
7. link to image in a list of image document refernces

Test on IOS. Images i have used have been 1 to 5 mbs in size. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0st4bGAsdGOvrBuwLPMn8UE5VUsfiaVNcfFWjsGUBpfzOveDlCcY5CAWtf4g++LliFDree2igbpDXPru8ZHR8Dd1QCBHA56TUnglAObdvLWwM3F2yfdmvcHLDIuu/Zwh9f6PHaOI=

### Context

Causes the UI to look bad and disrupts the user experience making the app look amateur. 

### Visual documentation

https://community.flutterflow.io/c/bugs/post/image-cacheing-dyamic-children-not-working-ios-RJBn9oJ5nCMddfz

### Environment

```markdown
- FlutterFlow version: 4.0 3.13.7
- Platform: Mobile
- Browser name and version: Chrome
- Operating system and version affected: IOS 17.1
```

**Comment by hariprasadms** [comment]
Hi @aaronmt93 - Thanks for submitting the issue. I looked at your project but could not locate the page where you got issue. I have tested above steps in iOS simulator. When the picture cache property is enabled, photos that were taken with an iOS device and saved in Fire Store loading as intended. 

You can utilise the blur hash property in the image widget to improve the user experience when images load slowly. 

 If you still believe there is a problem with your images and they are loading slowly. You can reproduce the issue in a blank project and update the issue with the project bug report code. We can look at the matter again. I hope this can help you. Thanks

**Comment by aaronmt93** [comment]
@hariprasadms did you watch the video I sent you? is that normal behavior? I would think with cacheing the loading should be instant. its also a ton of work to create a whole new project with a firebase database to recreate.

**Comment by hariprasadms** [comment]
> @hariprasadms did you watch the video I sent you? is that normal behavior? I would think with cacheing the loading should be instant. its also a ton of work to create a whole new project with a firebase database to recreate.

I have watched the video and I can see that images are loading slow. However, until I see the type images you have and the configurations, I can't say for sure what the issue is. In one of my test apps, I followed exactly what you mentioned in the above steps, and everything appears to be working as it expected. 

Did you test with other images with smaller size comparatively ? how it is working comparatively?

In bug report template, its been mention that _the steps to reproduce the issue start from a blank project_. Consider the nature of issue, defiantly we need a blank project with issue setup details. If you could share images as well, that will be great. 

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by aaronmt93** [comment]
hi @hariprasadms these are example images as they are saved on firebase as well as screenshots of how they look on firebase. looks like they are saved as jpg but initially had been live photos. maybe something in the conversion is causing the bug.  


![1699027699660669_2](https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/fa5e9d85-d446-496d-bafb-ecaa9ca0f15d)

![1699027699660116_0 (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/fb11cb79-c754-479c-8ff3-b86c8c81fca2)

![1699027699660686_1](https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/20ea7350-9391-4aba-b0b1-05a28fbb684c)

<img width="1104" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/79803407-1fcd-4bdc-8aee-7653575a8430">

<img width="262" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/ed84173b-e0be-4c33-ac1a-78d8fd4ebcb6">

**Comment by aaronmt93** [comment]
hi @hariprasadms I just reseted to confirm given new updates the issue doesnt happen on the web browser or the simulator which is what looks like you are testing on, it only happens on a real device. I dont think its wifi as I have 200mbps and as I said seems specific issue on the real device. 

see the video here. i have an iphone 11 with 17.03 installed.  

https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/0daa9b4b-1729-4329-91ef-7e2064f39de7

**Comment by hariprasadms** [comment]
Have you enabled image cached option ?

**Comment by aaronmt93** [comment]
hi @hariprasadms yes I have. it seems to work on web and simulator but not on real device if you were able to test on an actual iphone? 

<img width="1465" alt="Screenshot 2023-11-21 at 9 50 23 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/0a57e5bb-5d2d-43c6-ac15-225fcd652ef3">

**Comment by aaronmt93** [comment]
@hariprasadms saw you closed this, were you able to test on a real device?

**Comment by aaronmt93** [comment]
looping in @agreaves this has been open for over a month
