### ISSUE TITLE
ListView with BackendQuery doesn't show all items first time

### ISSUE THREAD

**Issue by SEGVeenstra** [FlutterFlow/flutterflow-issues#1709]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a ListView with participants of an event.
It is connected to a Firestore query that is:
- Paginated (page size 10)
- Filtered by numberId
- Ordered by username

When I enter the page for the first time, it will only show a single user:
![Scherm­afbeelding 2023-10-26 om 15 02 04](https://github.com/FlutterFlow/flutterflow-issues/assets/5990148/756cfb8e-e5cc-4722-b227-8d9902ad1ffd)

Then when I go back to the previous page, and open the same page again, it does show both participants:
![Scherm­afbeelding 2023-10-26 om 15 02 39](https://github.com/FlutterFlow/flutterflow-issues/assets/5990148/39a6885e-dc28-4be9-9362-ac72fbf03f7d)

### Expected Behavior

That the page shows both participants the first time as well.

### Steps to Reproduce

1. Create a page with a ListView
2. Add a backend query
  2.1 Filter by one field
  2.2 Order by another field
3. Turn on infinite scroll
4. Page size 10
5. Visit page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48k8/qw4lOm+Fa14SJdcdvmiUROUc7UOcO0dYabE08J5zTP4YIP/v7ak5oO7yodHx2O2GaimQz/PfquIfpE8deBy2sRaJBzs91EgvhRnKjV7bUEKWVfW1TEdljGmqa15mjvSMlNs1qS04+6ky6LuuyTnbrNoyzClQ/OOa1KdeK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to get a list of participants for an event.
If the list is broken (incomplete), the user might not allow participants to enter because they don't appear in the app.

### Visual documentation

![Scherm­afbeelding 2023-10-26 om 15 02 28](https://github.com/FlutterFlow/flutterflow-issues/assets/5990148/4fb60c71-8e43-42c7-8a41-4411f8319418)
![Scherm­afbeelding 2023-10-26 om 15 02 04](https://github.com/FlutterFlow/flutterflow-issues/assets/5990148/f15f8ea0-c029-42d5-93ee-819ec1eb98aa)
![Scherm­afbeelding 2023-10-26 om 15 02 39](https://github.com/FlutterFlow/flutterflow-issues/assets/5990148/ef66b9dd-5c19-4def-9f5b-5dc9c8b3df01)

### Additional Info

Note that the first user that does show up is the currently logged in user.

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 117.0.5938.132 (Officiële build) (x86_64)
- Operating system and version affected: MacOS 13.2.1 (22D68)
```

**Comment by SEGVeenstra** [comment]
After some help with ChatGPT it turned out the code was just not compiling.
It would be nice to have a proper error for that, but for now this issue is resolved.

**Comment by simonrayray** [comment]
@SEGVeenstra I'm facing a similar problem at the moment. Could you share more infos on how you resolved this issue?

**Comment by SEGVeenstra** [comment]
> @SEGVeenstra I'm facing a similar problem at the moment. Could you share more infos on how you resolved this issue? 

I didn't.
We just showed a warning that the user had to restart 😂
