### ISSUE TITLE
Authenticated User info

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#171]
i am trying to retrieve the authenticated users email for a doc in my app the issue is that if they sign up through the app using the email authentication for some reason the Authenticated users email is blank as oppose to if i create the user in the auth dashboard on firebase the workaround for now is that i have to call the user doc to get the information from there

**Comment by Pepino-GR** [comment]
Hi joekman990,
in order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by agreaves** [comment]
Hi @joekman990, thank you for the bug report and apologies for the delay. The Authenticated user document was not being initially populated, so if you access it immediately it was originally blank as you observed. This should be fixed upon our next release! 🙂
