### ISSUE TITLE
Audio player doesn't work on iphone web (Safari + Chrome)

### ISSUE THREAD

**Issue by eternallcharles** [FlutterFlow/flutterflow-issues#1710]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The audio player works properly on ipad, desktop, simulation ... but it doesn't work on safari or Chrome on Iphone. It works on Android. 
It doesn't appear at all. 

### Expected Behavior

The audio player should be displayed on the web page as it is on the simulator, on desktop and on ipad 

### Steps to Reproduce

1. Create a new page with an app flaged with "enable PWA"
2. Add the audioplayer with the default path to get audio : https://filesamples.com/samples/audio/mp3/sample3.mp3
3. Use an iphone and launch this page on Safari or Chrome. Everything will be displayed except the audio player

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ls/l6ot1rttb1aqBbsFFimUvKUM7R5E30eptcwA8J4jcOokUf8+nRFFVUum+TVc3JlmZ+XE0p/CLvvbIN8IqGEiYQapNz856WgrMbGWVeKqWC5G/dkFBEtpKBWqv3J7UrR0lJrdsR1Y46nGuAunIShHtQLr3Oms7GOaKLobPs3PuQ0SLb3kNh1JWeC/v

### Context

It impact me significantly. My project is around audio collection. it is important that my users can listen what they recorded.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149094818/a67136d0-a667-4fe6-bc9f-550256aa2a17)
![Bug-audioplayer](https://github.com/FlutterFlow/flutterflow-issues/assets/149094818/fde173a8-4c08-47a2-b922-e0ff134e6df1)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: safari or chrome
- Operating system and version affected: iphone 13 pro with ios 17
```

**Comment by SameerShahzad99** [comment]
Hi @eternallcharles, Thank you for completing the requirements and submitting the bug, I was able to reproduce this issue on my end!

**Comment by vahekhumaryan** [comment]
Hi Flutterflow team. When is the approximate expected timeline for this fix with audioplayer?

**Comment by takashiff** [comment]
Hello, thank you for your bug report! This issue has been reported previously, so I'm going to mark this as closed. Please refer to [this issue](https://github.com/FlutterFlow/flutterflow-issues/issues/87) for updates. If you believe I've incorrectly flagged this as a duplicate, feel free to follow up in this thread. Thanks!
