### ISSUE TITLE
FlutterFlow's 'Web View' Widget Constantly Refreshes URL on Android Mobile Web (URL: TypeForm

### ISSUE THREAD

**Issue by JuanDiegoG** [FlutterFlow/flutterflow-issues#1711]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Issue Description: When using the '**Web View**' widget in FlutterFlow to load a TypeForm URL on an Android mobile web browser, the TypeForm consistently refreshes, especially when attempting to input text in a text field within the TypeForm. This behavior triggers the URL to reset and the component to refresh. This issue is specific to the **web application when accessed from an Android device** and occurs similarly in **PWA** mode on Android. The problem does not occur on iOS, and it functions correctly on Android when the application is packaged as an APK.

### Expected Behavior

I expected that when using the 'Web View' widget in FlutterFlow to load a TypeForm URL on an Android mobile web browser, the TypeForm would remain stable, allowing users to input text into the text fields within the TypeForm without causing the URL to reset or the component to refresh, similar to how it functions on iOS.

### Steps to Reproduce

1. Create a new page.
2. Add a 'Web View' component.
3. Insert a TypeForm URL with a text-based question.
4. Deploy it as a web application.
5. Test it on an Android device.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi8/cyIZ1xLRE17r+YMdFoDsXCDp7apE/iewbZCs8Cb7yB7Icf/fOYkRVZ+m4S2xiIVqZhWoW3PTTkfD9L/cBFw2AfIh91pBceDrNVj2mbqqtFJWgPHRBP+NRfEPD0pm7vRMmNupeckVl60yPe9mubDbUNqLMITAsDq/LZO4=

### Context

This issue has had a substantial impact on our project. We are using this functionality to enable users to answer dynamic TypeForm questionnaires, and the inability to proceed with this feature significantly hinders our development and the expected scope. Our users rely on this functionality to interact effectively with the application, and the current issue prevents us from providing them with a seamless experience.

### Visual documentation

ISSUE:

https://github.com/FlutterFlow/flutterflow-issues/assets/12850621/456da8a0-b14c-40fd-b1f8-d99c12ffe911

EXPECTED:

https://github.com/FlutterFlow/flutterflow-issues/assets/12850621/3bc52f77-d7ff-4371-aa68-adcaa49492b6

### Additional Info

Widget Settings:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12850621/593b5127-bbe1-4108-bb1e-7d472c172fa7)

### Environment

```markdown
- FlutterFlow version: v3.13.7
- Platform: Web Android
- Browser name and version: Chrome 118.0.5993.80
- Operating system and version affected: Android 12; M2007J20CG Build/SDK Q1.211019.001
```

**Comment by JuanDiegoG** [comment]
Any Update? 7 days please its important for me @SameerShahzad99 and @agreaves

**Comment by agreaves** [comment]
Hi @JuanDiegoG, apologies for not getting to this issue until now. It's a bit difficult for me to reproduce however, and appears to be a project specific issue. Are you still experiencing this issue and have you found any sort of workaround?

**Comment by JuanDiegoG** [comment]
Hi @agreaves,

I haven't found a solution to the problem yet, and the issue persists. I understand that it may be a very project-specific problem; however, I believe this issue might be related to the interaction with Android in general. We've observed another problem in conjunction with this one, which involves responsiveness when displaying the keyboard on Android mobile devices (both in web applications and browsers like Chrome, Bing, and Edge). Every time the keyboard is displayed, a white bar of the same size as the keyboard appears, causing all the components on the screen to shift (view image below).

If you could take a detailed look at these two aspects, I believe we might uncover something crucial that could be causing multiple issues.

Thank you in advance for your response, and I'll be eagerly awaiting your insights.

Feel free to let me know if you have any further questions or if there's anything specific you'd like to adjust!

![Imagen de WhatsApp 2023-12-26 a las 09 06 16_640c46f4](https://github.com/FlutterFlow/flutterflow-issues/assets/12850621/1fce9f7f-b139-488b-8a28-df163c88bd83)

**Comment by JuanDiegoG** [comment]
@SameerShahzad99 Yes, it still happening :'(

**Comment by SameerShahzad99** [comment]
@JuanDiegoG I really apologize for your experience, can you please start a ticket with the support team through live chat if you are on the pro plan, or use the email support@flutterflow.io if you are not on the pro plan, the team will try to get this resolved as soon as possible as this is a project-specific issue!

**Comment by waymorphood** [comment]
I am seeing this as well. The webview is not usable because of this

**Comment by hariprasadms** [comment]
Hi @JuanDiegoG - Please reach support team for this issue. Thanks
