### ISSUE TITLE
Supabase policy auth with Fultterflow

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#1712]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to RLS policy in Supabase which is policy ((auth.jwt() ->> 'sub'::text) = user_id) but in return i get an error 401 unauthorized, when i remove the policy is work perfect 

### Expected Behavior

 ((auth.jwt() ->> 'sub'::text) = user_id) this policy should allow auth user who has the id to delete update his own row 

### Steps to Reproduce

1. create a new project
2. create a new db in supabase 
3. confirm your steup in ff for supabase
4. enable rls 
5. add new policy 
6. policy should be all and ((auth.jwt() ->> 'sub'::text) = user_id
7. create a new account user 
8. check your supabase
<img width="1383" alt="Screenshot 2023-10-26 at 18 41 07" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/6c8018ca-22a8-4828-9008-c16603bc7291">
<img width="1383" alt="Screenshot 2023-10-26 at 18 41 12" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/a8b71889-4480-4013-a384-136c9b3bf914">
<img width="1367" alt="Screenshot 2023-10-26 at 19 05 33" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/99a75e4c-2b55-4b56-9662-9b075a1092e5">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/testauction-26ii4i?tab=uiBuilder&page=Auth4

### Context

you cannot use supabase policy 

### Visual documentation

you cant use supabase policy 
![Screenshot_2023-10-26_at_18 47 28](https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/094f7e3c-cfa3-4497-ab15-20edcbe2c967)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: web test mode 
- Browser name and version: chrome 
- Operating system and version affected: mac os
```

**Comment by casey1011** [comment]
I think this is an issue from your supabase, try using, ' auth.uid() = user_id '

**Comment by sergedahdouh** [comment]
I think this is an issue from your supabase, Try 'using'auth.uid() = user_id.

Hello, I tried, but it did not work. Have you tired of it? by the way, my user_id is text 

![Screenshot_2023-10-26_at_18 47 28](https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/194c5f15-7358-44a2-b666-9b081cd7f00e)

**Comment by casey1011** [comment]
hmm, using jwt.io, I see your sub is 123456 is that what you had it as? Are you logged in when you try to make the request?
<img width="1274" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24780069/44377e68-4dee-4af7-be30-2e66ecacf9b9">

**Comment by sergedahdouh** [comment]
no this when i create the account then i need to insert a row 
<img width="1471" alt="Screenshot 2023-10-26 at 22 23 40" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/84609799-d969-45ed-8761-cb12a54014a3">

<img width="1471" alt="Screenshot 2023-10-26 at 22 23 46" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/dde35f00-a6d9-4993-900b-723788298559">

**Comment by sergedahdouh** [comment]
<img width="1471" alt="Screenshot 2023-10-26 at 22 29 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/9cc63acd-61d7-432c-8659-13f8c0795153">
<img width="1471" alt="Screenshot 2023-10-26 at 22 29 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/bbc8d52a-b6fe-4a29-937a-22b606d0d804">

**Comment by katherineqian** [comment]
Hi @sergedahdouh, thank you for submitting this issue. This issue tracker is intended for general bugs that are applicable to all users. It looks like this error may be specific to your project, so this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/) where they can be more helpful in allowing you diagnose the cause of your issue.
