### ISSUE TITLE
FlutterFlow Version out of Date

### ISSUE THREAD

**Issue by ToddHerron** [FlutterFlow/flutterflow-issues#1713]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Project\ suddenly showed **FlutterFlow Version out of Date** message for _only one project_. 

Platforms:

- MacOS
- iPadOS

All updates were lost. I can only update the affected project using the FF web version.

![Screenshot 2023-10-26 at 11 47 04](https://github.com/FlutterFlow/flutterflow-issues/assets/2007969/82f08665-43ba-493f-a83e-60352964cda8)

### Expected Behavior

To be able to get into my project to edit it on MacOS and iPad.

### Steps to Reproduce

Click on the affected project from the Dashboard on MacOS or iPadOS.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Unable to access code due to the error.

### Context

Unable to develop on native FF platforms.

### Visual documentation

![Screenshot 2023-10-26 at 11 56 27](https://github.com/FlutterFlow/flutterflow-issues/assets/2007969/81122279-7614-4686-af62-942186ccb516)

### Additional Info

![Screenshot 2023-10-26 at 11 52 07](https://github.com/FlutterFlow/flutterflow-issues/assets/2007969/bc465f8c-7f5b-4a8a-a10b-6e70c2a0aa2c)

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: MacOS and iPadOS
- Browser name and version: n/a
- Operating system and version affected: MacOS Ventura version 14.4.1 / iPad OS 17.0.3
```

**Comment by ToddHerron** [comment]
Addendum ... I was able to resolve the issue on MacOS by deleting and reinstalling FlutterFlow. I tried doing the same on iPadOS but the problem remains.

**Comment by diegomm796** [comment]
Same, reinstalling
