### ISSUE TITLE
Collection name overflowing left bar when it's too long

### ISSUE THREAD

**Issue by jorgeferrarice** [FlutterFlow/flutterflow-issues#1714]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you add a collection with a name too large, it'll overflow it's container.

### Expected Behavior

The collection name should be trimmed and show a tooltip on hover with it's full name.

### Steps to Reproduce

1. Go to your dashboard
2. Go to the database tab (you must have your app connected with Firebase)
3. Click "+"
4. Type a long collection name, it can be a child collection or not
5. Check the name on the left sidebar overflowing it's container

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

This is a platform UI bug

### Context

This is not affecting/blocking me, is just a UI bug.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/134354663/a3d1dd3c-312e-46ec-98be-40d8f80f4ea6)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Platform
- Browser name and version: Chrome 118.0.5993.117
- Operating system and version affected: Windows
```

**Comment by katherineqian** [comment]
Hi, thanks for reporting! Fixed and will be released in the update next week.
