### ISSUE TITLE
Filtering and Ordering on Grid View or Staggered View when the ordering is a Date doesn't work

### ISSUE THREAD

**Issue by sambondareff** [FlutterFlow/flutterflow-issues#1715]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I realise that both the grid and staggered view will not show anything if I am trying to use a date as an orderby parameter, I have resorted to using a interger datatype to get it working. The error in the console that is returned is "Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received”, there is nothing else.

### Expected Behavior

The query collection should be ordered by the supplied date field for both grid and staggered views.

### Steps to Reproduce

1. Create Page.
2. Add either a staggered or grid view widget.
3. Create a backend query (I am using Firestore, not sure if it is the same problem with Firebase)
4. Add a filter
5. Add a orderby (make sure it is a date field)
6. Run.
7. Nothing will return and the error in the consol is not helpful

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kis/15ZVgosRH+Zf1bflFuCIsQ0AmTL07quxETRMvIrbyOu9/fcz8XxJpZNzmTFNhHFeJrGEJwMrevdjhUvk6ZCWZfYBDwpBUejuXY3q8RbnWDcywVHMmGcVgBWau18OvhghNHMlYZUYcwzqYG+fLSXTYJ5+/Zwh9f6PHaOI=

### Context

Was trying to create a list of Gallery items sorted by date.

### Visual documentation

<img width="351" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/48588229/2450f5f1-438c-4d4f-8f19-1ddd15e063c3">

### Environment

```markdown
- FlutterFlow version: 4.0 released Oct 27, 2023
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 118.0.5993.70 (Official Build) (arm64)
- Operating system and version affected: macOS 14.0
```

**Comment by hariprasadms** [comment]
Hi @sambondareff - Thanks for submitting the issue. I looked at your project but not able to find the page/widget where you got the issue. There are more pages in your project. Considering the nature of bug, you should replicate the issue in blank project and send us the bug report code of the project. Without these details we can con't investigate the issue. 

We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by hariprasadms** [comment]
Due to inactive and no further details, closing the issue.
