### ISSUE TITLE
FAB Element is being overlapped by Navbar when the Navbar style is set to Floating Nav Bar

### ISSUE THREAD

**Issue by Rulios** [FlutterFlow/flutterflow-issues#1717]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running the project test mode, the FAB element is being overlapped by the Navbar. The Navbar style must be Floating Nav Bar to have it happen. 

![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/22872640/5cf28872-56cf-41c2-bb42-b8b09a5123c2)

### Expected Behavior

The Navbar must not overlap the FAB element. Just as it is being showed in the app design canvas. 

![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/22872640/dc2b41d2-9643-4e01-949d-e8be3ac09ff9)

### Steps to Reproduce

1. Create at least 2 pages. So that Navbar works. 
2. Enable Navbar navigation between the 2 pages. 
3. Add a FAB element to either pages.
4. Go to the Project Settings in Nav Bar & App Bar section
5. Set the Nav Bar style to be "Floating Nav Bar"
6. Now run the app in Test Mode
7. Check for the pages that have the FAB Element. It looks overlapped by the Floating Nav Bar

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gosRJ0brAb8JAhTQnHHI5UI0vku1ERTogfIjuPOxzTMnOVBJuOLC0SmNcJWH9kmQd083emvHtDu44aQecY7Z+1KoAEDnJVnyiM77UC82OQW5/DZpNG2a60qWJrghRBPtsSHw/7GCQO/OUaDbaHoDAPGonDvG1OZOK2SrDX1iXc2URm05KZDPz

### Context

I was trying to use the Floating Nav Bar style of Navbar, because it adds text to the navigation options. It also happened that in one of my app pages had a FAB Element. When I ran into test mode, the navbar overlapped the FAB element. 

![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/22872640/cb6d78c2-fb57-4469-b1f0-152e47a3052d)

![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/22872640/e3994915-c8fc-4d8a-bee0-744cbe718439)

### Visual documentation

Current Behavior

![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/22872640/5cf28872-56cf-41c2-bb42-b8b09a5123c2)

Expected Behavior

![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/22872640/dc2b41d2-9643-4e01-949d-e8be3ac09ff9)

### Environment

```markdown
- I encountered the issue in Test Mode, so not sure if asides from the FFlow version info, every other aspect is important. 
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 118.0.5993.90
- Operating system and version affected: Windows 10
```

**Comment by johnD369** [comment]
Please fix this bug or provide the option to manually set margin for the FAB inside flutterflow. As a temporary solution thu, you could create a custom widget FAB and include it to your project so that you could set your own margins.

**Comment by jessieplaydatecare** [comment]
I have the same issue, kindly please prioritize the task

**Comment by sbis04** [comment]
In the next update, you will have a way to set padding on the `FAB` widget, which I believe solves this issue! We couldn't find any better way to avoid this situation.
