### ISSUE TITLE
Sending non UTF-8 characters to API

### ISSUE THREAD

**Issue by gams1976** [FlutterFlow/flutterflow-issues#1718]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am doing a search on a supabase backend though rest API. The user types the text for the search. Simple ascii text (not diacritics). The supabase backend returns 500 code saying it received non utf-8 char. It returns null and the listview crashes

### Expected Behavior

send UTF-8 codes

### Steps to Reproduce

Send text to a API backend

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohcjq35d2tbxE7q6JbMExryQvG0h9aLsn1spOEC0jF7KuBqQEYczBbVhucM+7aVNcAlGipEgCws6Ojt/hJewoNRWVc7k5z6ttWwvee2i6aLKTBpagOHR7LJ5YG1SE156WniNTB7Z2LkYm2maqI9ivHnPDBOu/Zwh9f6PHaOI=

### Context

Impossible to use supabase API

### Visual documentation

![flutterflow3](https://github.com/FlutterFlow/flutterflow-issues/assets/36744327/659bac77-67e5-41c4-9960-ad8e201262d4)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 118.0.5993.71 
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @gams1976 - Thanks for submitting. I took a look at the given project above. However, I was unable to locate the page where you got the search issue. Please configure the issue steps in a page and share the details.

**Comment by gams1976** [comment]
Thank you very much for the support, but the issue stopped happening. I tried to replicate it in the same screen it was happening but now it runs properly. So you can mark as solved.
