### ISSUE TITLE
Component Crash when sending null parameter

### ISSUE THREAD

**Issue by gams1976** [FlutterFlow/flutterflow-issues#1719]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Any component crash when i send a null parameter (even if not required) and I don't do anything with it

### Expected Behavior

Not crash (or allow null test in loading action)

### Steps to Reproduce

Create a component
Pass a null parameter

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohcjq35d2tbxE7q6JbMExryQvG0h9aLsn1spOWSsbfL74PexyPOOkPxBoOOKzaHNUAVeljmAC/9bzi+HXKvo3FEmaGodxzcxicBPPYzm5MIyLC7WwT3N9GcdVIFCx57ej2RBBC/htWGAb70yUeumAQT2Cf9qOYwx5e6fDbOY=

### Context

Pre-check every parameter befire sending to component

### Visual documentation

no

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Web
- Browser name and version: Versão 118.0.5993.71 
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @gams1976 - When there is parameter is defined in a component and its been mapped to a widget, there should be a default value should be assigned to it. Otherwise in run it can throw an error as parameter is null and no value to display. Check you got default value assigned to the parameter in component.

**Comment by gams1976** [comment]
My bad, this is true. no bug. Sorry
