### ISSUE TITLE
Importing Firebase Analytics in Custom Action works in Test mode but shows up as a Project Error

### ISSUE THREAD

**Issue by dansomrack** [FlutterFlow/flutterflow-issues#1720]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to use the following call inside a custom action to log an event to Google Analytics. (I have also modified the code in a develop branch in GitHub to send to more sources. 
`logFirebaseEvent('eventName');`

It should work because of the default import below, since this works when building the app in VSCode locally.  
`import '/flutter_flow/flutter_flow_util.dart';`

However, I am getting project errors. Even if I try any of the following import statements, it still gives me an error:
```
import '/backend/firebase_analytics/analytics.dart';
import '../../backend/firebase_analytics/analytics.dart';
import 'package:silver/backend/firebase_analytics/analytics.dart';
```

I was able to build and run the project, despite these errors and the app works. 

### Expected Behavior

There should be no project errors if there are no build errors. 

### Steps to Reproduce

1. Create a custom action
2. Add a line logFirebaseEvent('createClaims');
3. Compile custom code

It will show a project error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WksrlvJdOm8NA7arPbflFiioUNkA5UI03icNxQksYNZzkB4wPXfikSEpWZ9+kTHxcL0yGimUdpt7OkdnQA+UqKQmZbNRx+qp2djvvfz6tMrqJBsySdEd6I8dJJVzH1qejgyZANsRZL3gm2E2Lfu6/ExPcNrrTImwjJcj8BK3/pX+qQ0SLb3kNh1JWeC/v

### Context

I realize now that I can still run the app if there are build errors, but often Flutterflow will prevent me from running the pap until build errors are taken care of. 

### Visual documentation

![Screenshot 2023-10-26 140348](https://github.com/FlutterFlow/flutterflow-issues/assets/11216609/f5919588-01de-4a3e-879d-e24f6111241b)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Windows Web
- Browser name and version: Chrome 
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @dansomrack. We are working on a fix. In the meantime, you can exclude this action from compilation.

**Comment by wenkaifan0720** [comment]
Should be fixed in our next update. Thanks!
