### ISSUE TITLE
Media Assets upload accepts file names that cannot be accessed

### ISSUE THREAD

**Issue by smadds** [FlutterFlow/flutterflow-issues#1721]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When uploading a file there is insufficient checking on file names acceptable to the storage location - e.g. a file name including the character '#' is accepted and reported as uploaded, but the thumbnail of the image is not shown in the grid and not accessible to preview

### Expected Behavior

Any filenames that are not acceptable should create an error and either require offending characters to be removed or automatically replaced/removed

### Steps to Reproduce

1. Go to Media tab
2. Upload a file with a '#' character in its name
3. Upload is confirmed, but preview of image is not shown
4. Click arrow icon over image space to open the asset in a new tab
5. Error message from Google saying unable to access the file

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not widget related

### Context

Wasted a lot of time wondering whether Firebase was properly connected

### Visual documentation

![Screenshot 2023-10-26 235138](https://github.com/FlutterFlow/flutterflow-issues/assets/5259870/89df2f87-7f17-47d6-9e06-ca3e01c435f0)
![Screenshot 2023-10-26 235306](https://github.com/FlutterFlow/flutterflow-issues/assets/5259870/01000446-6763-48e2-874c-8da47925083d)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Web
- Browser name and version:Edge 
- Operating system and version affected: n/a
```

**Comment by hariprasadms** [comment]
Hi @smadds - Thanks for submitting the issue. I can reproduce the issue. Thanks

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @smadds. This will be fixed in the next update.
