### ISSUE TITLE
Error when reading 'lib/flutter_flow/permissions_util.dart': No such file or directory

### ISSUE THREAD

**Issue by dvdbrv** [FlutterFlow/flutterflow-issues#1725]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I use the Health package, and therefore need a user's permission to make it work. FlutterFlow does not allow custom permissions, so I've made a custom action for it.
![Screenshot 2023-10-27 at 13 58 02](https://github.com/FlutterFlow/flutterflow-issues/assets/149161862/dbd26c2f-c364-48a2-98c3-00c912f82172)

### Expected Behavior

When I try to deploy, I get this error. 
![Screenshot 2023-10-27 at 13 58 47](https://github.com/FlutterFlow/flutterflow-issues/assets/149161862/f86e6525-a7a5-4317-818c-fb78f540e8fa)

### Steps to Reproduce

1. Create a new custom action
2. Add "permission_handler: ^11.0.1" dependency
3. Import these packages "permission_handler/permission_handler.dart';" and "'../../flutter_flow/permissions_util.dart';"
4. Write the function to ask for permission - Future healthPermission() async {await requestPermission(Permission.activityRecognition);}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

healthPermission()

### Context

I'm trying to ask a user for permission for their Apple HealthKit activity data

### Visual documentation

![Screenshot 2023-10-27 at 14 05 52](https://github.com/FlutterFlow/flutterflow-issues/assets/149161862/5817ae51-168f-4c20-bcb1-d6e67876a18e)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome Version 118.0.5993.88 (Official Build) (arm64)
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
Closing this ticket due to no response form the user end!
