### ISSUE TITLE
PageView ExpandingDotsPainter.paint is causing crashing errors

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#1729]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The ExpandingDotsPainter.paint component are being reported from Google Crashlytics that are causing crashes for users as shown below:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/d2155002-8e85-44aa-87d0-3edf0e24184e)

### Expected Behavior

No crashes.

### Steps to Reproduce

1. new page
2. add pageview with dots/expanding dots
3. monitor the performance/errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcr1z5R1obxY0LXTbfpWoCcXJVx+TL07s9Z+RRQvIrbyOu9+P/ekflVvQsDiYWlhHFaknTkezNLvj9jDIccVPQqZGpxx+Kt6VBfgc3q8R7LREruWPHx5P9pUGG6i5Lujmh0lBNt1dUEj3F+XN+yAQgLqN5+/Zwh9f6PHaOI=

### Context

My app is live on production, and this issue are causing crashes for users.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/fa30e2a0-ce24-4ca4-b1ce-5c6cfa38f577)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: iOS & Android
- Browser name and version: -
- Operating system and version affected: all
```

**Comment by sbis04** [comment]
Hey @alih552, sorry for such a late reply. This issue looks quite old, just to confirm, are you still getting this error report?
