### ISSUE TITLE
Responsive View doesn't work for some reason

### ISSUE THREAD

**Issue by shawn9556** [FlutterFlow/flutterflow-issues#1730]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For some reason, the create account page's responsive view doesn't work. The mobile view and the tablet/desktop view should be different but it shows the same view with smaller sizes which breaks the content.

### Expected Behavior

The mobile view should have a different layout but it's giving me the same layout as the tablet/desktop view.

### Steps to Reproduce

1. Create new page
2. Check the screen size for mobile clicking mobile icon(on the top center)
3. Check screen size for tablet/desktop clicking tablet/desktop icon(on the top center)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Okufl0It2od8B7c/+KcJV9SU5JU84RIZMke5+ewE3IZ/NG7UIec/4VEptXbC+TVc3J2Kj/Wcyp8qMhdzIN8A6NROcRrp6yboJTT3/XlilVcjQCpCKWnRABtpKBUCc56aFoRJvPtJaLlI73GD3O9zJaBbtQ5jGDFYdOfyIUZvVnXfuQ0SLb3kNh1JWeC/v

### Context

The aesthetic is wrong and it mess up the whole UI of the app

### Visual documentation

mobile: 
<img width="2560" alt="Screenshot 2023-10-29 at 2 56 18 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102288310/0ccab61c-5183-4d84-b57b-2dfd68a0e066">

tablet: 
<img width="2560" alt="Screenshot 2023-10-29 at 2 56 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102288310/72dc6d21-9b98-4100-9aad-d9f7c61bc624">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web, MacOS Desktop
- Browser name and version: Chrome Version 118.0.5993.117
- Operating system and version affected: macOS Sonoma 14.0
```

**Comment by wenkaifan0720** [comment]
Hi @shawn9556. Not sure about how you set up the responsive design, but if it involves more than responsive visibility, then you need to run the app live in order to test the responsiveness.

**Comment by shawn9556** [comment]
I used the “create account 2” template provided from the flutterflow template. Didn’t configure any responsive views.

**Comment by hariprasadms** [comment]
Hi @shawn9556 - As @wenkaifan0720 mentioned responsive visibility settings should be set and project should be run in run or debug mode to see the responsiveness of the app.  This is not a bug. There are good youtube videos explaining responsiveness settings in FlutterFlow. Please take a look. Thanks
