### ISSUE TITLE
Error on desktop version - Flutterflow version out of date...

### ISSUE THREAD

**Issue by xenomorph78** [FlutterFlow/flutterflow-issues#1731]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Reported in the community: https://community.flutterflow.io/discussions/post/flutterflow-version-out-of-date-ipad-pro-refresh-not-working-avwvSdatOIM8hri

On the desktop version, when selecting the project, a popup comes up and says that the Flutterflow version is out of date and to refresh the page to get the updated version, but there is no option to refresh.
Workaround: Having to use the web version which is too slow for me.

![Screenshot 2023-10-29 at 12 15 39 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/74033405/4a314251-bc24-42f3-9320-401f70536ab2)

### Expected Behavior

To be able to use the desktop version that I pay for.

### Steps to Reproduce

Just open the desktop app and try to open my project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfHlzItOodtc0L6JK+5r/WMRC24ha7swscp/bxIgGIDzPOw+ZPWlVxZDQuHnTH9tfUSmmn8JzMLyuNnxU/YoPTSsR6Jnys1UYAKXZE2ta5OBCbm/dXB8J/9YIGKwy8KC2h1AWcZ2WiUHw3GAGPCAQjPYQ4z2IlFISq/LZO4=

### Context

I can't user flutterflow app (non-web) version.

### Visual documentation

![Screenshot 2023-10-29 at 12 15 39 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/74033405/ff2ce10a-1129-415c-b71a-989e589dba46)

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: FlutterFlow for MacOS
- Browser name and version: Chrome
- Operating system and version affected: MacOS, Ventura 13.3.1 (1)
```

**Comment by wenkaifan0720** [comment]
Hi @xenomorph78. Could you try to update your mac app version here: https://flutterflow.io/flutterflow-desktop-app?

**Comment by benjaminathlan** [comment]
Hello,

Still experiencing the same issue only for one project. 
Same behavior on iPad FF app.

**Comment by wenkaifan0720** [comment]
Hi @benjaminathlan. What is your iPad FF app version?

**Comment by Krystian95** [comment]
Hi, I've been in trouble with this issue from many months, I've also reported it to the support via email. The only solution I've found to work is to uninstall the Desktop FF app and reinstall it... very annoying unfortunately

**Comment by SameerShahzad99** [comment]
@xenomorph78 Can you please confirm if this issue is still experienced on your end?

**Comment by alexsung7** [comment]
I've been having this issue on mac for the past few days and uninstalling did not work for me. Anyone fixed this yet?

**Comment by xenomorph78** [comment]
> @xenomorph78 Can you please confirm if this issue is still experienced on your end?

Not having the issue after I deleted the app completely and re-installed it.

**Comment by JohnyDeath** [comment]
Same behavior on Windows

**Comment by github-world192** [comment]
encountered same problem

**Comment by JohnyDeath** [comment]
reinstalling the application does not solve the problem (Windows)
Where are the settings stored? Perhaps I should clear the settings directory...

**Comment by Rp2patilrahul** [comment]
same issue on windows version,
