### ISSUE TITLE
Datetime Custom Format for Week (w) not working

### ISSUE THREAD

**Issue by julianlikesdeveloping** [FlutterFlow/flutterflow-issues#1733]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to get the week of the year as a single-digit. For example, "1" for the first week of the year.
I've formatted the custom format as "w" as per the docs of Flutterflow (see here: https://docs.flutterflow.io/advanced-functionality/global-properties/current-time).

However, the value I get instead of the weeknumber is the following: w.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149370135/42c18112-40dd-40c8-9ca5-e53b5eb53246)

All the other datetime formats (like MMMM for Month) work with no problem.

### Expected Behavior

I expect the current week number (For example, "1" for the first week of the year) of my selected Date in the Calendar Widget.

### Steps to Reproduce

1. Create a Calendar Widget

2. Create a Text Widget and assign it the value of the Widget State of the Calendar.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149370135/419073f2-f4cf-413c-aa44-9de2f58470f0)

3. Select the "DateTime Format" from the Available Options Dropdown. 
4. Select "Custom" DateTime Format Option.
5. Set the "Custom Format" to "w"
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149370135/cd1ffd60-423d-491c-b374-e33d5d6dcf14)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XlcjfsMxOn7xE7arUcsB7/ToXNmYja7ssltZxYw81F5jwBLMMd8/uT3BZOMu6dFZUP2GJmm0JpvDTuOOWDO4nMhyJbIhnyal6ZALxfESVbJSLPLWJdXZ6P99nGhTDzpuZ3RZ7KbB2R1Y8wDu6e+uucDLfJIDuPEUBRv6ZDLnL+2yJLXneGn0Jg1ZSfCvr

### Context

I'm creating a Dashboard with a Calendar where the Events of the selected Week will show up in a Listview.
To do this, I need to fetch the Weeknumber from the selected Date in the Calendar.

### Visual documentation

Already provided in the Steps to Reproduce

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Windows Web
- Browser name and version: Chrome Version 118.0.5993.118
- Operating system and version affected: Windows 10
```

**Comment by agreaves** [comment]
Hey @julianlikesdeveloping, thank you for the bug report! Apologies for the confusion, it looks like our documentation is incorrect, as unfortunately this is not a valid date time formatting pattern. The official list can be found here: https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html

We'll make sure to update our documentation, but for now you may need to use a custom function in order to properly display the week of the year as a number, such as one found here: https://stackoverflow.com/questions/49393231/how-to-get-day-of-year-week-of-year-from-a-datetime-dart-object.
