### ISSUE TITLE
api - list string format inaccurate

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#1734]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when creating an api this is the body it generates 

{
  "Team No": [2, 4],
  "Transaction No": [33, 44],
  "Unique Id": "[test1, test2]"
}

the string list is not formating correctly

### Expected Behavior

this is the format it should generate 

{
  "Team No": [2, 4],
  "Transaction No": [33, 44],
  "Unique Id": ["test1", "test2"]
}

### Steps to Reproduce

1.create an api with string as variable set it list to true 
2. now test this api and when you give string list data in the perview it shows incorrectly

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ol/KA4Y92rtdc1pPqL+9VijsXJmY6RYI7l9Vhaw4YGIvqB4YEeOHOVBRBXfW5S3lHG1b8hmMK+cLJvvP1BO4FPQ6CGZh7+qpXQx7iZDqnRa63DqqJPkB6GeRUGUyi4LWzgSJAPrJwd2wR7TmyBOuXHzHaH4DMOVggRviKD534jEKVLnv3VSdFwSkMH2qZTI5ODEz25eKMrop5yfj/0w==

### Context

unable to call an api - it shows as invalid format error . affecting my project 

### Visual documentation

![Screenshot 2023-10-30 131300](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/bd75827e-08fd-4485-834e-d1415ee576ce)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:web
- Browser name and version:android
- Operating system and version affected: win 11
```

**Comment by aemelyanovff** [comment]
@padeepz Thanks for reporting the issue. It will be fixed in the next update.

Note that the issue occurs only when using the "Test API Call" functionality. Generated apps handle this correctly.

**Comment by felipemontero** [comment]
Seems like the issue is not resolved completely, if the API call it's a GET type and you use a string variable as list, it's not formatted properly still.
<img width="997" alt="Captura de pantalla 2025-01-06 a la(s) 2 01 50 a m" src="https://github.com/user-attachments/assets/136df016-2eb7-43d4-a65e-de3aa77ee7a5" />
