### ISSUE TITLE
When we convert the data coming from any API to "Any data type" with "Map List Items", we get an error.

### ISSUE THREAD

**Issue by Kyzaghan** [FlutterFlow/flutterflow-issues#1737]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am fetching data from an API endpoint and converting it to my own custom data type, but as a result, I am encountering an error.

### Expected Behavior

I should be able to convert the data to my custom data type without encountering any errors.

### Steps to Reproduce

1. Create an api request (json array)
2. Add the listview component to the widget tree
3. Call api in the data tab
4. Go the generate the dynamic children section and set settings like this
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20926114/2fc0486b-9752-4908-baa4-616873204f01)
5. Run project 

Problem is "withoutNulls" part because there are not exists any extension function
  final data = TestCall.products(
                            listViewTestResponse.jsonBody,
                          )
                              ?.map((e) => e != null && e != ''
                                  ? ProductStruct.fromMap(e)
                                  : null)
                              **.withoutNulls**
                              .toList()
                              ?.toList() ??
                          [];

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5flPLq25dgrt8F17rtbfow9SURHFw2aucRlO1AEBEdGLnqB6QUfOD8UBZJYsOfT2NAeVWjpGc0paHHk+PIUMc3IU+WQ4NeyKpXEAmWeHqlaYjWDaWaRHJ7P9xWCEyx1p6smA9QOu9oLXwj7UOYJOmsVh7UGZjuOjINPP6HEJLNnXDiKx3BEzpVxmNecCfn

### Context

I've need to use the data types in the listview

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20926114/2fc0486b-9752-4908-baa4-616873204f01)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20926114/d311d179-0214-486d-9440-755cd81734b3)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Any
- Browser name and version: Microsoft Edge - Latest
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Duplicate with #1684
