### ISSUE TITLE
Languages selector typo issue

### ISSUE THREAD

**Issue by Digitalize-Me** [FlutterFlow/flutterflow-issues#1740]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,

This not a bug just a typo issue but the upper case is missing on the f in français in project set up > languages > Display languages.
And it's the same on the languages selector widget.
I tried in case of on a fresh blank project and the upper case still missing.

### Expected Behavior

capitalization of the first letter as for any other country name write with the Latin alphabet.

### Steps to Reproduce

Just adding french as a possible languages translation.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocgB7qn6dO5qhQohNkw6U+YritUbdywjGKLyB+0Uec76P0ltOfXkTGx6emaMp14d0cLoveDPJvkoZCmYfrpgwZN9VQ/ieDqVbq2TF7i8XGgnP9tXCWaGy5izswhNHMleck4c2FyMJPPKdDTZJ5TNC2o8Sq/LZO4=

### Context

My client pointed out the issue to me.

### Visual documentation

![CleanShot 2023-10-30 at 17 54 57](https://github.com/FlutterFlow/flutterflow-issues/assets/111974933/76e203df-f38c-4064-b2f9-0b876d4a80f3)

![CleanShot 2023-10-30 at 18 04 43](https://github.com/FlutterFlow/flutterflow-issues/assets/111974933/af51b1bb-49ad-43dc-a852-a25afe52e1f5)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

**Comment by SameerShahzad99** [comment]
@Digitalize-Me I was able to reproduce it, thanks for reporting!

**Comment by victoriahuang1** [comment]
Hi @Digitalize-Me , thanks for the report. I have made the fix on our end, so this should be resolved upon deploy.
