### ISSUE TITLE
Gray Screen When Typing (iPad & MacOS Desktop)

### ISSUE THREAD

**Issue by ableinc** [FlutterFlow/flutterflow-issues#1741]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There's a bug on the iPad and MacOS beta app that greys out the screen when searching for icons (this is after you place the icon widget on the screen). After typing 2 letters the screen grays out. I've noticed if I type slowly and put a space between each character it will not grey out. Same goes for slowly removing each space.

### Expected Behavior

1. Type in search box
2. Screen does not gray
3. Select icon

### Steps to Reproduce

1. Create new page
2. Drag icon widget onto page
3. Go to icon properties
4. Scroll down to Icon section
5. Tap button to change the icon
6. Start typing in the window search box

Example of searching for an icon labeled "card":

Search: ca (gray screen)
Search: c a r d (typing slowly, no gray screen)
Search: c a r d > c a rd > c ard > card (typing slowly, no gray screen)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsI52ocMA+KnfLe9Wr2Q7HG18R600rNx+bw4bI+P1EIkIeOPRUFZpSOqHT3x+J1Kb8TgF0d71vob+GvYCGxCsG5w//qoMUxDhZGWuMM3QPrWWdXB5I/tXfm7G15iR2gldAPpidCEE3Vz7G++Aa3qCf9qOYwx5e6fDbOY=

### Context

Changing the icon button

### Visual documentation

![Screenshot 2023-10-30 at 11 58 06 AM (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/26948458/3abd3a8d-4602-487e-aae5-a06e85516ecb)

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: iPad, MacOS Desktop
- Browser name and version: N/A
- Operating system and version affected: iOS 17, macOS Ventura 13.5.2
```

**Comment by ableinc** [comment]
Update: I've seen the same behavior when searching for widgets in the Widget Tree.

**Comment by hariprasadms** [comment]
Hi @ableinc - Thanks for submitting the issue. I can reproduce the bug.

**Comment by ableinc** [comment]
> > Update: I've seen the same behavior when searching for widgets in the Widget Tree.
> 
> 
> 
> I can't reproduce while searching in widget tree. It is working fine. Can you add bit more details when you see the bug while in widget tree?

It only happened once for me

**Comment by Abayjafton** [comment]
same error on web

**Comment by ableinc** [comment]
After the recent update to both the iPad and macOS app, I do not see this issue happening anymore. Not sure if this was meant to be closed.

**Comment by aemelyanovff** [comment]
I no longer can reproduce the issue. I'm assuming it's been fixed and closing this issue. Please let me know if it's still happening.
