### ISSUE TITLE
EndDrawer Widget creates Icon in Appbar

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#1743]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i add the EndDrawer Widget to a Page it creates a icon in the AppBar. The Icon can not be edited, changed, hide etc.
I can't even find it in the generated code. This does not happen with the normal Drawer.

### Expected Behavior

When i add a EndDrawer Icon i dont find a icon in the appbar. 

### Steps to Reproduce

Create a Page, add a appbar, add a EndDrawer Widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lcmB34hNodcF+Kr2b8FajjgXH2E7aLszkOxxRUs8J5DYPLMUSs77QBFWUs+0TwllM2eGimEe3MHemvz1G/FeIRaWfr58yJFQFgnyZEaQR7avOqu8Om5/DZljfVTHyMOnrhVBNvZiLyUY2U+mPei9QnXrNIy3OTJAD/GXC5KK2SrDX1iXc2URm05KZDPz

### Context

Add a Drawer from the right side to my project

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/120254395/6d5deca7-14d1-4317-9c86-12b7354b2118)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 118.0.5993.117 (Offizieller Build) (x86_64)
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @nicmohr25 - Thanks for submitting the issue. I can reproduce it.

**Comment by sbis04** [comment]
Hey @nicmohr25, you can drag a different widget on the AppBar where the End Drawer icon is present, and it should replace it.
