### ISSUE TITLE
Merge not going through with a couple people working on the same project

### ISSUE THREAD

**Issue by szymonpodwyszynski** [FlutterFlow/flutterflow-issues#1745]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When couple other people are working on the same project, when for example one person tries to merge from one branch to another and the other user has the project opened, the merge rarely goes through and the changes made on the other branch are merged to main (the changes are not on the main branch). 

### Expected Behavior

When a merge is going through its supposed to go through no matter whos working on the project. Alternatively there should be a information about ongoing merge to other users working on the project so the merge can go through without any problems.

### Steps to Reproduce

1. Have for example two users working on the same project
2. One user stays on main, other creates new branch
3. User on seperate branch make some changes and try to merge
4. After merge the changes are rarely on the main branch

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40tfGDw7xNmOoF1bXyWsJEpBsUJjI2WIMritxBaDUsIuOtBuwtdc/BdRBoOPLnaVNcfFKioEkx0ezRv4SSVMAFNQ2BbtlS1bpATQ/0e2i7RLK3BZasQXFQTPNjC2HF0Z6zrCJ5JutedCQt3Dv3Oue/RXLDFOu/Zwh9f6PHaOI=

### Context

Merge process really slows down with merges not completing correctly. We have to make sure that noone touches the project while merge is ongoing as this bug will be present.

### Visual documentation

<img width="977" alt="Screenshot 2023-10-31 at 11 17 06" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/3017c870-6a05-49a8-8415-ccfe720c1020">

### Environment

```markdown
- FlutterFlow version: newest as of 31.10.2023
- Platform: macOS web
- Browser name and version: Google Chrome 118.0.5993.123/124
- Operating system and version affected: macOS Sonoma 14.0
```

**Comment by victoriahuang1** [comment]
Hi @szymonpodwyszynski, thanks for the report. Once the changes I made are deployed, merging will be blocked and you will be prompted to ensure nobody else is in the project (if there are other active users).
