### ISSUE TITLE
Display Device + Zoom Level Causing builder render bugs

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1746]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Enable Device  Frames and zoom out and the UI will not render correctly 

### Expected Behavior

For it to look correct with the UI

### Steps to Reproduce

Enable Device  Frames and zoom out or look at conditional  widget s

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShcjc08lgoctf+YffKPlqhR0gHDN8UeY7mO5DZxM2G5esGbYUfPvOVBFZZ+G7fUFUeVeIpDsBzNrMud7lD8EsPh6rRoRbzpdcVAriTlOhRKqpPbmWXXEnTN9Wfx2E1KSrhBUnIbJ2eClpig/GSw==

### Context

Nothing much just strange 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/dde80c7c-5eed-4b67-8f02-e4814dd97d56)

### Environment

```markdown
- FlutterFlow version: 
- Platform: PC
- Browser name and version: CHROME
- Operating system and version affected:  all
```

**Comment by Josefpa** [comment]
Video demo: 
https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/574c109f-567b-4541-9f98-76642904d871

**Comment by SameerShahzad99** [comment]
Thank you so much for reporting this issue, i was able to reproduce this on a blank project, with height and widget set to 100%!

**Comment by victoriahuang1** [comment]
@Josefpa are you still experiencing this issue? There may have been a fix that went out already

**Comment by Josefpa** [comment]
Yes fixed before the big update last week thanks @victoriahuang1 forgot to close
