### ISSUE TITLE
DateTime add method does not support months

### ISSUE THREAD

**Issue by anywheresa** [FlutterFlow/flutterflow-issues#1748]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the Datetime add method, Duration months is not supported by Flutterflow.
IE. This works.
final today = DateTime.now();
final fiftyDaysFromNow = today.add(const Duration(days: 50));

This does not
final today = DateTime.now();
final ThreeMonthsFromNow = today.add(const Duration(months: 3));
I think you guys forgot about months.

### Expected Behavior

Supposed to be able to do Datetiem adding of months.

### Steps to Reproduce

1. Create a Custom Function
2. Try add the following code to add 3 months to a any date.
3. final today = DateTime.now();
final ThreeMonthsFromNow = today.add(const Duration(months: 3));

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not relevant to a widget

### Context

Cant do datetime calculations involving months

### Visual documentation

![months not supported](https://github.com/FlutterFlow/flutterflow-issues/assets/56668789/f5c4c0c5-3ddb-43e6-bb12-f224a5652cfb)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Windows
- Browser name and version:Chrome Version 118.0.5993.118
- Operating system and version affected: Windows 10
```

**Comment by joshua-ffio** [comment]
Hi @anywheresa , 

This custom code excerpt is not using any FlutterFlow specific code using the `dart:core` [Duration class ](https://api.flutter.dev/flutter/dart-core/Duration-class.html#Contstructors:~:text=Duration(%7B,const) which only supports time units of days and smaller.

I believe a workaround you could use here is to create a new DateTime object and reference your original date and do your addition/subtraction in-line:

```dart
final newDate = DateTime(date.year, date.month +3, date.day);
```

Please let me know if there is something here that I've misunderstood and you believe should be relooked at.

Thanks!

**Comment by anywheresa** [comment]
Ah, thank you for clarifying this. I see there is a pub.dev package called jiffy that allows for years, months, weeks, days, hours, minutes, seconds, milliseconds and microseconds.

DateTime d = Jiffy.now().add(months: 6).dateTime; // 2020-04-26 10:05:57.469367
// You can also add you own Datetime object
DateTime d = Jiffy.parseFromDateTime(DateTime(2018, 1, 13)).add(months: 6).dateTime; // 2018-07-13 00:00:00.000

Thank you
