### ISSUE TITLE
Error: "Data Type "address" currently has no fields." even when there is no data type address

### ISSUE THREAD

**Issue by jessidjo** [FlutterFlow/flutterflow-issues#175]
An error saying "Data Type "address" currently has no fields." appears and stays even when the collection Address is entirely deleted.

I created the fields in a collection Address and still see the error. The error appeared first when I created a collection Address and deleted it, the error never disappeared. I am able to reproduce the error each time by creating another collection Address and deleting it right after. When I do so, more errors appear and add up as you can see in the screenshots below. I went from 1 error to 9 by doing so. Therefore, no way I see I can resolve the error since the collection is not there anymore.

![image](https://user-images.githubusercontent.com/119433269/204573796-431c81bb-3423-4be6-9355-bb93d158ce12.png)
![image](https://user-images.githubusercontent.com/119433269/204573915-90e817d4-18df-4b49-b853-a8914b85760c.png)
![image](https://user-images.githubusercontent.com/119433269/204573989-457c1827-7d9b-4a11-9883-0c014182aedb.png)
![image](https://user-images.githubusercontent.com/119433269/204574031-bc74e8bd-344b-4d2f-8709-127c17be106c.png)

**Comment by jessidjo** [comment]
By clearing out the data type tab it resolves the problem
![image](https://user-images.githubusercontent.com/119433269/204579223-2247288c-497a-4c59-9dcd-7dadb8ee68ee.png)

**Comment by hariprasadms** [comment]
Hi, As per your last message, I see that you got your issue resolved. Please confirm. We can close the issue. Thanks

**Comment by jessidjo** [comment]
Yes, the issue was resolved. Thanks
