### ISSUE TITLE
Custom fonts and icons don't display correctly on FlutterFlow iPad

### ISSUE THREAD

**Issue by sirian-m** [FlutterFlow/flutterflow-issues#1754]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom fonts and icons added in the theme settings or from an external design library project, don't display correctly in the app. They display a default font, and the icons are all a question mark.

### Expected Behavior

I would expect my uploaded custom fonts/icons to correctly display like on the web version of FlutterFlow

### Steps to Reproduce

1. Create a new project
2. Import a custom font and icons
3. Add some widgets to the page set to that font/icon
4. Open the project on the iPad version of FlutterFlow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkcrl089NrtxE1qrqcsBaimQwGUALa+dI0tZ+TQ0jF5D4BO0IZs/sREltTfazaH5DMFqijmcf3PDLufPLKPc6KSyAbJw9yc9+ehPPbGKXR6q3DLrtSERCM9tVC0eO16ernyRACNtfW1Jh32DzAd6/Yz2Cf9qOYwx5e6fDbOY=

### Context

It limits me in building new screens/components on the iPad version, as I can't see the exact icon I'm choosing as they all look the same on iPad.

### Visual documentation

![5BE57688-D002-4CD9-98A2-8E8EB70F201D_1_102_o](https://github.com/FlutterFlow/flutterflow-issues/assets/109159237/bba31a91-1f21-468c-8ab7-a92a18fe8dd0)
<img width="1389" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/109159237/634d6acb-83b3-44bf-a1c8-6effa938c59b">

### Environment

```markdown
- FlutterFlow version: v4.1.6
- Platform: iPad
- Browser name and version: -
- Operating system and version affected: iPadOS 17.2
```

**Comment by hariprasadms** [comment]
Hello @sirian-m - Due to inactivity in the issue, we presume the problem has been resolved with the latest FF iPad version updates. Hence, I am closing the issue. If the issue still persists, feel free to reopen or create a new one.
