### ISSUE TITLE
Deeplinks inside the application from WebView do not work

### ISSUE THREAD

**Issue by vnbogdanov2020** [FlutterFlow/flutterflow-issues#1755]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to create a page in an application on which a WebView widget will be placed, containing a DeepLink in HTML to the pages of my application. This functionality is necessary to implement a payment widget in a banking HTML application - when opened, it requests hyperlinks to the page that needs to be opened upon a successful transaction.

After compiling and testing on a mobile device, I observe a problem, namely, the widget does not recognize the link scheme and displays the error ERR_unknown_url_scheme.
It turns out that the WebView browser does not understand links such as myapp://myapp.com/myPage. Moreover, if you package Deeplink on an application page in an html file, open the file on the device and click on the link, the application will open on the specified page. And if you place the same code in a WebView widget, an error appears when you click on the link. Looks like a problem with the WebView...

### Expected Behavior

After compiling in the application, when I open my page, I see a clickable link "Open APP" in the widget. When you click on the "Open APP" link, the startPage page of my application opens

### Steps to Reproduce

1. I create a page in the application with a WebView widget
2. I place in the body of the widget a text containing a hyperlink to the DeepLink of the page of my application, for example "`<a href="myapp://myapp.com/startPage">Open APP</a>`"
3. After compiling in the application, when I open my page, I see a clickable link "Open APP" in the widget
4. When you click on the "Open APP" link, the startPage page of my application opens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl+fl4otIm9tF+Krcb+9WnWMRQ2Yjapc0s9kbdxEvIrbyOu9/f87eahFvZ9fhY3lhHFaWnkMBpPz2kfPLC8FeHz+ZGYBn+c5pWjvwUXq8R6qbCoe0WURSM95jGHKZyJm33RVdAPFZSloX7zv7NvO9Tj3vN5+/Zwh9f6PHaOI=

### Context

This functionality is necessary to implement a payment widget in a banking HTML application - when opened, it requests hyperlinks to the page that needs to be opened upon a successful transaction.

### Visual documentation

![Screenshot_2023-10-31-16-11-14-220_com company flutterai](https://github.com/FlutterFlow/flutterflow-issues/assets/64920418/9d957a19-9734-4921-9e9a-60a0ae413526)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 118.0.5993.118
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
@vnbogdanov2020 Thank you for reporting this, considering this as a feature request for the webview widget!
