### ISSUE TITLE
Cannot deploy to Cloud Function

### ISSUE THREAD

**Issue by MikeYates** [FlutterFlow/flutterflow-issues#1756]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot deploy google cloud function for some reason. It was working before, but I deleted my function in flutterflow and firebase console. Then when I try to deploy again it would fail.
I have 1 function that I deployed and deleted both on flutter flow and firebase console, which I deleted. Then I added 2 function, 1 is the same as before. That one says deployed while the other comes up with an error "Out of Date". But on my firebase console no function is showing.

### Expected Behavior

Should say "deployed"

### Steps to Reproduce

1. Create a cloud function
2. Click deploy

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghvHqy5dNrsdb7aXqce9V/To6JmYgaIc0sNobbxAjIoDoPJkUacmlTFpuYNe+d1VfKEWGikYx+aHLjoTLJsJdJk+rc4Rfys19VQ3McHq/aoSLEpCwOERtL91PFUi+5La7rBFSJsFtdHsuwGWUB+m/F3TXJIP7Zwh9f6PHaOI=

### Context

Cannot deploy cloud function

### Visual documentation

[Screenshot](https://imgur.com/undefined)

### Additional Info

Error log from firebase console

`Unable to retrieve the repository metadata for projects/repairdata-cc326/locations/us-central1/repositories/gcf-artifacts. Ensure that the Cloud Functions service account has 'artifactregistry.repositories.list' and 'artifactregistry.repositories.get' permissions. You can add the permissions by granting the role 'roles/artifactregistry.reader'.`

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome, latest
- Operating system and version affected: MacOS Big Sur
```

**Comment by SameerShahzad99** [comment]
This looks like a project-specific issue, please reach out to the support team for such cases by emailing at support@flutterflow.io or live chat!
