### ISSUE TITLE
Apple Login feature does not transfer required information for app review.

### ISSUE THREAD

**Issue by cartworthy** [FlutterFlow/flutterflow-issues#1757]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Apple Login functionality currently does not connect the information associated with the apple account. In my case, a users first name and last name are being collected manually during signup. Apple requires that these items are auto-filled when users login with Apple. Apple is rejecting my app, forcing me to remove Apple Login functionality.

### Expected Behavior

When offering the ability for users to login with apple, the first name and last name (maybe profile photo and other account information) associated with the account should automatically be assigned to the Users document.

### Steps to Reproduce

1. Implement Apple Login on an app that collects users first and last name during sign up.
2. Try to get approved by Apple Review.
3. Get rejected.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

My app is being rejected by app review and they demand I remove Apple Login functionality because the app collects first/last name during signup. I'm unable to use Apple Login entirely without this necessary functionality. I've searched the FF community and others have reported this as a problem, but no one knows how to solve it.

### Visual documentation

<img width="983" alt="Screenshot 2023-10-31 at 8 17 11 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/67118663/f8ed2b5b-2a80-4717-bdf7-2947205b3264">

### Additional Info

Many of my users report that they don't want to create an account with email — they would prefer to login with external platforms. Names are required for my app functionality, and therefore I will not be able to use Apple Login unless this bug is fixed.

### Environment

```markdown
- Any/All
```

**Comment by cartworthy** [comment]
How can I keep this from going stale? My app is completely shut down from App review because of this. I've already had users sign up with Apple and now their accounts will be inaccessible because I'll have to remove the Apple Login functionality to pass app review. Please fix this bug!

**Comment by SameerShahzad99** [comment]
You'll need to navigate to the screen after logging in from Apple where you need to set the first name for the user, try implementing that, this should resolve the problem. The issue that you are experiencing is due to the design of the app not according to the guidelines.

**Comment by BestRazer** [comment]
> You'll need to navigate to the screen after logging in from Apple where you need to set the first name for the user, try implementing that, this should resolve the problem. The issue that you are experiencing is due to the design of the app not according to the guidelines.

That won't be sufficient. I'm doing that right now and Apple has rejected my app because of this.
