### ISSUE TITLE
Flippable card does not support other actions

### ISSUE THREAD

**Issue by captainjdi** [FlutterFlow/flutterflow-issues#1758]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an action is added to a flippable card container, the card no longer flips. The action does take place. 

### Expected Behavior

The card should flip and the action should take place. 

### Steps to Reproduce

1. Create a new page
2. Add a flippable card
3. Add an action to the front side container
4. Run test mode
5. Click on the flippable card
6. Action will happen but the card will not flip

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40icn65YtPvttK+KqJb8FvmmU5JlgiUK8Viu57aCsofePrOpkAf8/7UFtUcMuoYWxhM2H8vD8X/MnIkeH+U8IoBAqubJty/89qeBfvQkWuMrKqO763b3YmJJlVGEya5reCkxJ4JtFYLFYl62GbN9yWY3bvH5zTPjMgQ+a4XdeK2SrDX1iXc2URm05KZDPz

### Context

I cannot use the selection of the flippable card as an action that users are taking to then modify downstream elements of the app based on their selection. 

### Visual documentation

I cannot provide visual documentation because the click action doesn't do anything. Follow the steps to reproduce. 

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by SameerShahzad99** [comment]
Flippable Card does not support actions, the action that you are performing is on the container inside, so as it occupies the entire space for on-tap, you are unable to flip the Flippable Card

**Comment by SameerShahzad99** [comment]
Regarding using them both actions at the same time, considering this as a feature request!
