### ISSUE TITLE
Stripe and code expression

### ISSUE THREAD

**Issue by blueprin4** [FlutterFlow/flutterflow-issues#1760]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on the stripe value `amount` and to set the value I click `code expression`.  From there I set the expression like var1 * 100. I think click check for errors and it's ok.    However the 100 is not added to the code.

### Expected Behavior

The value are multiplied to give stripe the correct amount to charge.

### Steps to Reproduce

1. add stripe action
2. click amount
3. create code expression
4. multiple var1 times 100
5. click view code to see if expression was added

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkvHqx89IrsBE+aribsFWlmIwFjsLUI03iddTdwobIZjuELAQOur+VFhYZseafAtIA0ybklwK0tXHj87mGvEnGxeqaINo1pZPWwmWWjiXbKqSOqivPkB5EeJMfkiZyqSrogldA/Vsci1gw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

had to add new fields to collection with the stripe charge amount until fixed

### Visual documentation

<img width="655" alt="Screenshot 2023-10-30 at 5 21 45 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10341681/d43762c5-6af4-4374-b1a6-f3f993c65e51">
<img width="1441" alt="Screenshot 2023-10-30 at 5 20 43 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10341681/2862d578-75c3-48ca-b94e-70fcc265eb67">

### Additional Info

none

### Environment

```markdown
- FlutterFlow version: 4.02
- Platform:MacOS
- Browser name and version: Safari 
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hi @blueprin4 - Thanks for submitting the issue. Are you still experiencing the issue ? I looked at your project but could not locate the page where you got stripe payment action. Update this detail in the issue. Once you have added this detail, we can consider the issue for investigation. Thanks

**Comment by hariprasadms** [comment]
Due to inactivity closing the issue. Update required details and let us know if you are still experiencing the issue. We can re investigate the issue.
