### ISSUE TITLE
Google Maps Integration uses unknown / broken API Key in development and preview

### ISSUE THREAD

**Issue by matteofriz** [FlutterFlow/flutterflow-issues#1764]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using Flutterflow's native integration with google maps. At first, everything works fine, with maps/placepicker search working perfectly using my api keys. After some time (typically I'll get up and go do something else, then come back a few hours later), I notice that the map and placepicker stop working. I get a popup on the map that says "this page can't load Google Maps correctly".

Inspecting the console shows me that the requests to google's API are failing due to an exceeded quota, but the API key in the request is not one that I recognize.  

Interestingly, when I publish my Flutterflow app to web and use the published version, my correct API key is being used and the maps features work without issue.

### Expected Behavior

1. My API key is used to make requests to google maps 
2. Google integration features (i.e. maps and placepicker) work as expected in the app builder and preview 

### Steps to Reproduce

1. Add google api keys to project
2. Create new page
3. Add google maps widget to page
4. Add placepicker widget to page 
5. Attempt to use both widgets in the app builder and in preview and they work perfectly fine 
6. Leave and come back some hours later and see that the widgets are getting an error and inspect console to see the unfamiliar api key
7. Publish app to web and see that the widgets work perfectly fine, inspect console to see your api key is being used

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OiMjfsI52ocMA+Kr+KcdFmiQWOVs7R7xMm+1xb0sYCLXNG7Uiec+kYlFWX7S6TX02e1mZjnI13OiMuMzIN+0EA0meftk5+Kl6egHMWjuRSqq0PrWoeXdCQdpKC2bA4LuRpSR5BM11WmQ831OQfO+ibzDvGOPJIjMdHv+ZLobLo3fuQ0SLb3kNh1JWeC/v

### Context

I'm unable to use google maps features in the builder and in preview. Not being able to use these features before I publish would make me extremely worried about pushing out new features to my users, and I wouldn't be able to test them ahead of time.

### Visual documentation

![Error in Preview mode](https://github.com/FlutterFlow/flutterflow-issues/assets/149710809/5aca6103-4745-4997-9fd0-ef54f3bbbf87)
![Working fine in pubished app](https://github.com/FlutterFlow/flutterflow-issues/assets/149710809/8f43eed3-4fad-49f5-a784-dd457c05d21a)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform:Web
- Browser name and version:Chrome 119.0.6045.105
- Operating system and version affected: macOS Monterey 12.6.7
```

**Comment by SameerShahzad99** [comment]
@matteofriz  Thank you for sharing this, i was able to reproduce this issue on my end!

**Comment by kiwimagic** [comment]
I am also seeing this in my web chrome console when viewing my FF App - NOTE I AM NOT USING GOOGLE MAPS and have not set anything up for it in my project here is my console snapshot from when I was getting firebase issue (google global problem) so ignore the other error this is just shown so you can see the key I get is the same as the one in this bug. My App should not be accessing Google Maps API!    
<img width="818" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10331428/00c9c395-78b2-4b58-a0b8-29ae764e4200">

**Comment by johnD369** [comment]
still waiting for the issues to be solved. please solve this issue, its been weeks since the bug confirmed and no progress after that.

**Comment by agreaves** [comment]
Hi @matteofriz, @johnD369 and others. Thanks for the bug report! This is not actually a bug, but working as intended. The Google Map is not intended to be functional in the builder or preview mode, it's just a placeholder for building purposes.

We cannot use your provided Google Maps API key in the builder for security reasons so we must use our own. However, as you can imagine, rendering a true Google Map for hundreds of thousands of users is quite expensive so instead we've added a quota and show a placeholder which still serves the primary purpose as far as building is concerned. Hope this makes sense!

**Comment by johnD369** [comment]
I don't understand why this is for security reasons! why don't you use the user Google Web Maps API key for each individual separated user project? or give a setting option for the user to use their own API key or flutter-flow provided key for their project because most of the time the allowed quota will reach its maximum then it is frustrating to make any adjustments to the Google map widgets, it requires to render it each time to check the results for any adjustments we made.

**Comment by pratyakshm** [comment]
@agreaves i'm unable to comprehend what are the so called "security reasons" behind this. 

i want to look at my widget live as i make changes to it. publishing it every single time or even going to run mode to achieve the same, when your entire app is reliant on maps, is hectic and suboptimal at best.

at least we should have an option to choose if we want to use our own API keys in test mode.

**Comment by pratyakshm** [comment]
@agreaves i'm unable to comprehend the security risks for allowing us to use our own key in test mode.

i want to look at my widget live as i make changes to it. publishing it every single time or even going to run mode to achieve the same, when your entire app is reliant on maps, is hectic and suboptimal at best.

at least we should have an option to choose if we want to use our own API keys in test mode.

**Comment by Alontsoran** [comment]
i have another issue , when i am loking for location its not finding anything and just loading 
and in google maps platform i see a record that its used the api 
![image](https://github.com/user-attachments/assets/844346c8-a4f8-4f88-a438-813842b9619e)
![image](https://github.com/user-attachments/assets/40834b80-af68-497b-a506-73c78c828a7e)
please help me :)

**Comment by koji06ochi-ship-it** [comment]
This appears to have resurfaced in September 2026 with the same failure mode.

Current behavior:
- FlutterFlow project settings have our own Google Maps API key configured for Android / iOS / Web (key prefix `AIzaSyCJX...`).
- In the FlutterFlow Builder, the GoogleMap widget shows “This page can’t load Google Maps correctly.”
- DevTools Console reports `Google Maps JavaScript API error: OverQuotaMapError`.
- The script request in Builder is using a different, unrecognized key (prefix `AIzaSyBAj4Nqm...`), not the key configured in the project.
- The published FlutterFlow web app loads Google Maps correctly, which strongly suggests the configured project key itself is valid and that Builder/Preview is injecting a different key.

This is blocking Builder-side map development/testing even though the deployed app can render the map.

Could the team please confirm whether this is a known regression and either reopen this issue or point us to the current fix/workaround? We can provide a current Bug Report Code and project details if needed.
