### ISSUE TITLE
Google Maps Widget Causes: Undefined symbols. Linker command failed with exit code 1

### ISSUE THREAD

**Issue by JustUserHere** [FlutterFlow/flutterflow-issues#1765]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Description:
The application fails to build after if the Google Maps widget (contained within the AddressPicker component) is included. Deleting the widget allows the project to build successfully.
The project fails to build after the Google Maps widget is in the project. The following error message is displayed: "Linker command failed with exit code 1..."

### Expected Behavior

The project should build and run successfully, regardless of the Google Maps widget being included or after the project has been re-downloaded from GitHub.

### Steps to Reproduce

1. Delete the Google Maps widget from the Promotions page.
2. Delete the local folder containing the project.
3. Re-download the project from GitHub.
4. Run the project (at this point, everything works as expected).
5. Add the Google Maps widget back into the Promotions page.
6. Restart the project (it still works correctly).
7. Delete the project and re-download it from GitHub once more.
8. Attempt to run the project (the project fails to build).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsYt2m+FF7rruYO9WimU4HFAhaq00sd0bGA4jfaLyCokAePWlak9uXu2lS3x6MESmmkI0w97FhoTtDsIqZEycfNV+zatcFDzMWTmue5OBBZbsdUZQRNpgIX7F57S7vQlNNvVtcV4F2UOlN+e9fDPcQaLrImdISq/LZO4=

### Context

App is not working

### Visual documentation

![Google maps wodget error](https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/9516bdad-1f03-461d-87d2-05c157a17d6a)

### Additional Info

Issue was reproduced by Henry (from chat support)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mac and Web
- Browser name and version: Safari
- Operating system and version affected: mac os 14.1 (23B74)
```

**Comment by nurzhands** [comment]
Another issue with building/code downloading after adding GoogleMap, attached screenshots of error messages.
![Uploading Screenshot 2023-11-05 at 12.57.13.png…]()

**Comment by nurzhands** [comment]
Another issue with building/code downloading after adding GoogleMap, attached screenshots of error messages.
![Screenshot 2023-11-05 at 12 56 19](https://github.com/FlutterFlow/flutterflow-issues/assets/11344264/e313fec2-ce3b-48c9-844a-22afa81fca36)
![Screenshot 2023-11-05 at 12 57 13](https://github.com/FlutterFlow/flutterflow-issues/assets/11344264/18a1ec03-90ef-4c6a-b0b1-f79726e9d0ed)

**Comment by JustUserHere** [comment]
Hello!
@SameerShahzad99  @agreaves - please, give an update. Looking forward to use google maps again in my app.
thanks!

**Comment by JustUserHere** [comment]
any update here please?

**Comment by JustUserHere** [comment]
Dears! Please have a look on it!
1 month!

**Comment by SameerShahzad99** [comment]
@JustUserHere I really apologize for the delay, can you please confirm if you are still experiencing this issue, so we could dig deeper and get this resolved as soon as possible!

**Comment by JustUserHere** [comment]
> @JustUserHere

Hello! Yes I have this issue and cant resolve it.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/b5f81c63-88a1-433c-bf48-c5c932603c61)

**Comment by hariprasadms** [comment]
Hey there, Since due to inactivity and considering the age of the issue, I assume that the latest updates from FF have fixed the problem or you've found a solution. So, I'm going to close this issue now. If the issue continues, please create a new one with all the latest reproducible steps. Thanks!

**Comment by JustUserHere** [comment]
> Hey there, Since due to inactivity and considering the age of the issue, I assume that the latest updates from FF have fixed the problem or you've found a solution. So, I'm going to close this issue now. If the issue continues, please create a new one with all the latest reproducible steps. Thanks!


Hi!
This issue is not resolved for me.

**Comment by JustUserHere** [comment]
@hariprasadms 
can you please reopen this issue? I really looking forward to solve it
