### ISSUE TITLE
Push notifications error: Cycle inside Runner; building could produce unreliable results.

### ISSUE THREAD

**Issue by JustUserHere** [FlutterFlow/flutterflow-issues#1766]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After enabling push notifications i cant run my app.

### Expected Behavior

Push notifications works and app can't start

### Steps to Reproduce

Enable push notifications
Push to GitHub
Pull from GitHub
run compilation

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsYt2m+FF7rruYO9WimU4HFAhaq00sd0bGA4jfaLyCokAePWlak9uXu2lS3x6MESmmnoCptbruOOeOsIBBw+qf4RkyLVQewzhcEyXe5OBBZbsdUZQRNpgIX7F57S7vQlNNvVtcV4F2UOlN+e9fDPcQaLrImdISq/LZO4=

### Context

can't compile the project

### Visual documentation

![Push notifications error](https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/eda06685-0ae1-4c0e-bde4-174e57e0c5b1)
[push notifications error.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/13243676/push.notifications.error.pdf)

### Additional Info

Issue was reproduced by Henry (from chat support)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mac and Web
- Browser name and version: Safari
- Operating system and version affected: mac os 14.1 (23B74)
```

**Comment by hariprasadms** [comment]
Hi @JustUserHere - Thanks for submitting the issue. I can reproduce the error. Can you please confirm that app can build when push notification settings are disabled ( removed ) from the project ?

**Comment by hariprasadms** [comment]
Thanks for the update @JustUserHere

**Comment by binaverse** [comment]
I was able to resolve this by adjusting the runner.xcodeproj build phases and moving the Embed phases above the run script.

@hariprasadms @JustUserHere @kevintonb @joshua-ffio 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51916304/f20d8689-993d-4154-83dd-c5eb2a9b6a38)

**Comment by davidoort** [comment]
This solves the issue for us! Would be great if FF could let us update the build steps from the project so they don't get overwritten every time we export the project with the FF extension

**Comment by JustUserHere** [comment]
would be great if at least FF team can keep us updated on status and progress... i feel like no one taking care for this issue at the moment.

**Comment by MaggieThomann** [comment]
@JustUserHere what version of cocoapods are you using? I had this issue for a while, even after I upgraded my cocoapods to 1.13.0, which supposedly fixed this issue. `flutter doctor -v` does indeed show I'm using 1.13.0. The only way I finally got this to work was by adjusting the build phases of the Runner target to this when running the xcworkspace proj.

<img width="1383" alt="Screenshot 2023-11-15 at 11 07 29 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/15825518/929324e2-2170-4853-a21b-b032d898dcd5">

**Comment by aaronmt93** [comment]
same, i'm manually having to adjust this every time I download code

**Comment by kamil220** [comment]
I encountered a similar issue and resolved it effortlessly thanks to @binaverse. Does anyone know of a method to bypass the repetitive manual tasks following each code download?

**Comment by JustUserHere** [comment]
bug is not solved and you are closing it without any comment?!

**Comment by sbis04** [comment]
It's not yet released, this should be fixed in the next FlutterFlow update!
