### ISSUE TITLE
Update Email action not working

### ISSUE THREAD

**Issue by arielramos** [FlutterFlow/flutterflow-issues#1768]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Authenticated user email is not being updated, is still the same in Firebase Authentication Module

### Expected Behavior

Update authenticated user email in FlutterFlow app

### Steps to Reproduce

1. Create an app with Firebase authentication
2. Create auser and login into the app
3. Create an textfield widget and button to update the email

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Cg9CdXR0b25fY2d0YnlhdHAYCSKyAUqdAQorCgdHdWFyZGFyEQAAAAAAACxAGgtMZXhlbmQgRGVjYSgGOgYI/////w9ABhIgCh4I44o8Eg1NYXRlcmlhbEljb25zIAAyB3NhdmVfYXMZAAAAAAAA8D8pAAAAAABAYEAxAAAAAAAAREA5AAAAAAAAIEBJAAAAAAAA8D9SAhANWgIIAMIBFgoJCQAAAAAAQGBAEgkJAAAAAAAARECIAwL6AwDyBQkJAAAAAAAA8D9iAIoB9wIS8AIKCGc4NDJoeXdzErICIqQCEqECEpQCCjoKBWVtYWlsEjEKBwoFZW1haWwyJggHEhJUZXh0RmllbGRfajhzNTJxMTJCDkIMCgoQAzoGAQIFBAoNCkgKDGRpc3BsYXlfbmFtZRI4Cg4KDGRpc3BsYXlfbmFtZTImCAcSElRleHRGaWVsZF94Z20wcWd5MUIOQgwKChADOgYBAgUECg0KQgoJb2JqZXRpdm9zEjUKCwoJb2JqZXRpdm9zMiYIBxISVGV4dEZpZWxkX25rODFmc2cwQg5CDAoKEAM6BgECBQQKDQpICgxwaG9uZV9udW1iZXISOAoOCgxwaG9uZV9udW1iZXIyJggHEhJUZXh0RmllbGRfcnVjcm51bHpCDkIMCgoQAzoGAQIFBAoNGggIAkIECgIICKoCCGMxMjY5cmxwKi8KCG8yY2gyY2RhEiMyFggJGhJUZXh0RmllbGRfajhzNTJxMTKqAghnZXAzeGw0cBoCCAGSAQcwnu6U9IMwwgEA

### Context

User can´t update his email

### Visual documentation

<img width="358" alt="Screenshot 2023-11-02 at 22 34 59" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11698932/6d709d4b-2ebd-42ea-8583-641dbc2f2999">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:iOS
- Browser name and version: Chrome Version 117.0.5938.149 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.0
```

**Comment by hariprasadms** [comment]
Hi @arielramos, Thanks for submitting the issue. I have tested email address update action and I can confirm that it is working fine. There will be a email verification email sent to new email address. Once email is verified, user can see new email address updated in FB authentication section. Have you verified new email before checking new email address updated in Firebase auth section?

Refer doc here - [Update email address](https://docs.flutterflow.io/actions/actions/backend-database/firebase-authentication/update-email)
