### ISSUE TITLE
Document Property "Index in List" not accepted within action

### ISSUE THREAD

**Issue by vitruvo** [FlutterFlow/flutterflow-issues#1769]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When selecting the Document Property "Index in List" within an action, the dropdown switches to "undefined", the "Index in List"option can't be selected, wile other document properties can.

In my specific use case, I´m aming for an action that triggers the new carousel component to jump to a specific card once a marker on a google map widget is tapped.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/869740/1eeea168-a952-46f6-bc28-ed6c067493a8)

### Expected Behavior

Ability to select "Index in List" from document properties object within an action.

### Steps to Reproduce

1. create a carousel widget
2. create a google maps widget
3. add markers to google map
4. set up an "on marker tap"-action for the google maps widget.
5. (try to) select the "index in list" property to be passed to the "jump to" action type associated with the carousel component.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Context

In my specific use case, I´m aming for an action that triggers the new carousel component to jump to a specific card once a marker on a google map widget is tapped.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/869740/1eeea168-a952-46f6-bc28-ed6c067493a8)

### Additional Info

Genration of bug report code fails:
Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Environment

```markdown
- FlutterFlow version: 4.0 / 3.13.7
- Platform: Web
- Browser name and version: Safari 17.1
- Operating system and version affected: Mac OS Sonoma 14.1 (23B74)
```

**Comment by vitruvo** [comment]
So this just remains here without any feedback or triage then?

**Comment by vitruvo** [comment]
So this just remains here without any feedback or triage then?

**Comment by hariprasadms** [comment]
Hi @vitruvo - Sorry for delay in responding to the issue. Due to inactivity in the issue, we presume the problem has been resolved with the latest FF updates. Hence, I am closing the issue. If the issue still persists, feel free to reopen or create a new one.

**Comment by vitruvo** [comment]
Hi @hariprasadms - thanks for getting back to me on this issue.
Unfortunately, it seems that this issue persists even after the latest updates. The behavior on this particular scenario remains unchanged. :-(
I was wondering how and why nobody payed any attention...
