### ISSUE TITLE
 Group chat isnt working on readymade Chat app

### ISSUE THREAD

**Issue by sundarv18** [FlutterFlow/flutterflow-issues#177]
Quick 3-min video of the exact problem: https://drive.google.com/file/d/1-TElN4ABoTqvGwsOlMItVlkbyKyKpnpV/view?usp=sharing

URL to project:https://app.flutterflow.io/project/chat-test-evfjwp

This issue is specific to using the readymade Chat template of FlutterFlow. Tested and reproduced on both Android and Web platforms.

I cloned the [readymade Flutterflow app](https://app.flutterflow.io/project/chat-test-ns4t94) and then added the Group Chat feature exactly as mentioned [in the docs](https://docs.flutterflow.io/advanced-functionality/chat-+-group-chat#adding-group-chat). However, the Group Chat isn't working. Just throws a blank page.

## Expected behavior (required)
Once we create a group chat, we expect to get directed to chat page and chat with the group.

## Current behavior (required)
Once we create a group chat, we get directed to the chat page but the page is blank.

## To Reproduce (required)
1. Go to the project. URL: https://app.flutterflow.io/project/chat-test-evfjwp
2. Click Run.
3. Create an account and login, to land on All Chats page.
4. Click on the + icon on the App bar (top-right) and try to create a group chat.
5. Observe that you get directed to a blank page.

### Bug Report Code
Console error: _Another exception was thrown: Instance of 'minified:jY<void>'_

## Context (required)
Trying to create a dynamic prototype for my project and Group Chat is a key feature for the prototype.

## Screenshots / recordings
https://drive.google.com/file/d/1-TElN4ABoTqvGwsOlMItVlkbyKyKpnpV/view?usp=sharing

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Android apk, Web platform (MacOS), Flutter build run-mode
* Browser name and version: Multiple browsers
* Operating system and version (desktop or mobile): both desktop and mobile.

**Comment by Pepino-GR** [comment]
Hi sundarv18,

can you please share your project to the public, so I can troubleshot?

**Comment by sundarv18** [comment]
Hi @Pepino-GR - Done. this build is now public: https://app.flutterflow.io/run/AEQwvpZ0mfLtXi9pGck0.

**Comment by Pepino-GR** [comment]
Hi sundarv18,

I can reproduce it on your shared app, but I cannot reproduce it in general. Its seems to be project specific.

Please use chat support or contact support [at] flutterflow.io for further assistance.

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. 
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by sundarv18** [comment]
Support sent me here and this project is a clone of the project they shared 🙂. Either way, thanks for checking @Pepino-GR . 

If you know this works on any other project, pls share link. that will help me check as well.

**Comment by Pepino-GR** [comment]
If it is a clone, you can share your project as public, not only the run version. So I can look inside the project to see what happened.

**Comment by sundarv18** [comment]
ah! my mistake. The project is public now.  https://app.flutterflow.io/project/chat-test-evfjwp

**Comment by Pepino-GR** [comment]
In your chatMain Page, there are 2 Page Parameter missing. chatUser Document(users) and chatRef Doc reference(chats).

I've inserted it into the Page. Can you please try it?

**Comment by Pepino-GR** [comment]
And the chatDetails Page needs to be renamed to ChatPage. The system generates the Group Chat but cannot find the ChatPage

**Comment by sundarv18** [comment]
Renaming chatDetails to ChatPage now. 

I don't see your Page Parameters changes too chatMain page. But will try to check that out too.

**Comment by Pepino-GR** [comment]
You have to set the page parameter yourself.

**Comment by Pepino-GR** [comment]
Please keep me informed about the state

**Comment by sundarv18** [comment]
Nope. The chatDetails > ChatPage is a good point. I have changed it and also added chatUser Document(users) and chatRef Doc reference(chats) to chatMain. But still a groupChat ends up blank.

**Comment by Pepino-GR** [comment]
Can you see the created Groupchat inside the All Chat Page?

**Comment by sundarv18** [comment]
Not unless I manually pass the param chatUser and then add text. 

However, I am sure the chat gets created as I see 1. a new chats document getting created in Firebase. and 2. user is getting directed to the ChatPage with chatRef param. 

But unless chatUser params gets passed, the ChatPage is blank.

**Comment by Pepino-GR** [comment]
Can you please update actual version runtime link https://app.flutterflow.io/run/AEQwvpZ0mfLtXi9pGck0 with the actual version?

**Comment by sundarv18** [comment]
https://app.flutterflow.io/run/39eknnKVjLrsxaoI6dnd

**Comment by Pepino-GR** [comment]
I didn't see any changes inside the behavior of the run. Let me do some other troubleshooting steps and come back tomorrow.

**Comment by Pepino-GR** [comment]
It seems, that some component versions not fit together. To see how it works, you can go to the following project https://app.flutterflow.io/run/9Q1vLkqyrzM25zphX715 or you go to the project https://app.flutterflow.io/project/chattest-df8wss and clone it. You can also create a new project and use the SniffSocial template. Hope this helps

**Comment by sundarv18** [comment]
Thanks @Pepino-GR - I was able to clone SniffSocial and make GroupChat work. 🙌
