### ISSUE TITLE
Backend query filtering causes a compile time error when you use the .contains method

### ISSUE THREAD

**Issue by bhagwat-rahul** [FlutterFlow/flutterflow-issues#1770]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to filter a backend query by checking if an int is present in a list of int's field in SupaBase returned data. However to do so the .contains method is trying to concatenate an int with { curly braces } which is causing a compile time error since you cannot concatenate int's and strings.

Code:- 
    FutureBuilder<List<WorkoutsRow>>(
      future: WorkoutsTable().queryRows(
        queryFn: (q) => q
            .eq(
              'program_name',
              widget.programName,
            )
            .contains(
              'week_number',
              '{' + 1 + '}',
            )
            .eq(
              'day_number',
              sevenDaysItem,
            ),
      ),
      
      Error:- 
      
      Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/components/page_view_widget.dart:102:47: Error: A value of type 'int' can't be assigned to a variable of type 'String'.

### Expected Behavior

It should just check if the int is present in the list.

### Steps to Reproduce

Create new page
Create supabase table with a field that has a list of integers, say a list of week numbers.
Create a data table / listview ( anything dynamically generated )
Query that table and filter the list of ints using the 'list contains' method and pass an int.
Code will not report errors but crash at runtime.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skcmBw49OsfVY+KriacdB/Tg4NjM+aIEescpCbw4bIYj2P4lzY876P1hoTbC5TUFcJWC2p14e3NqOvvP1IfcqJT6bb4RPzatIcwzicGO5Va2TF7iVOWh6J5hPfUPD1J7UvSZ5NvJfWiwt212Dfem+fBDaQ77rPUQ4Sq/LZO4=

### Context

Trying to get a list of workouts for a specific week when i want to show workout summary for a workout program in my fitness app.

### Visual documentation

<img width="1470" alt="Screenshot 2023-11-03 at 2 39 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/45214779/4245000f-c556-4f0f-9272-c288be4912b3">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web, Mac OS
- Browser name and version: Arc, Chrome
- Operating system and version affected: macOS
```

**Comment by SameerShahzad99** [comment]
Hi @bhagwat-rahul, As I tried testing, I was unable to reproduce the issue that you are currently experiencing on my project, can you please share the bug report code for blank project with this issue reproduced?

**Comment by SameerShahzad99** [comment]
Closing this ticket due to a lack of response from the user.
