### ISSUE TITLE
Dropdown widgets - cannot set labels after setting values

### ISSUE THREAD

**Issue by eilzo** [FlutterFlow/flutterflow-issues#1772]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There are two label-related issues with the drop down widget: 

1. When creating a dropdown, once the options are set, the user cannot toggle 'Add Option Labels'.
2. If multiselect is enabled for a dropdown, there is a build error when trying to set labels for them.

### Expected Behavior

- We should be able to toggle labels on/off whether or not values have been set for a drop down. 
- We should be able to set labels for multi select widgets

### Steps to Reproduce

Issue 1: 
- Add a dropdown widget
- See 'Add Option Labels' toggle
- Add values to 'Define Options'
- See 'Add Option Labels' toggle disappear.

Issue 2:
- Add a dropdown widget
- Select 'allow multiselect'
- Add labels and values for drop down
- Build app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

-

### Visual documentation

Issue 1, cannot set labels after setting values: 

https://github.com/FlutterFlow/flutterflow-issues/assets/134552781/d7f011fa-1164-4800-a826-87ecd5d97227

Issue 2, cannot set both multi select and labels:

![image (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/134552781/dc31eff7-6b2b-4864-837d-3d1507f9190d)

![image (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/134552781/32963450-1b84-4b69-8062-5522b794e673)

### Additional Info

-

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: FlutterFlow application
- Browser name and version: Chrome
```

**Comment by hariprasadms** [comment]
Hi @eilzo - Thanks for submitting the issue. I can reproduce the above point 2. But point 1 not fully clear. Can you please add more details around it ? so that dev team can consider all the points while fixing it. Thanks

**Comment by eilzo** [comment]
Sure thing! 

- The toggle option 'Add Option Labels' disappears from the UI if 1) the toggle is currently set to false, and 2) the dropdown options values are set via a variable. This can be verified by setting the dropdown to be a random list of strings. This is the demonstration in the video.

- If 'Add Option Labels' is toggled true, and then the dropdown values are set from a variable, then the toggle button remains.

**Comment by acedweb** [comment]
Hi, i'm currently experiencing the same issue in my project, @eilzo did you find an alternative way to getting this done? thank you

**Comment by agreaves** [comment]
Thanks @eilzo for the bug report 😊

This will be fixed in the next deploy!

**Comment by fabienCambournac** [comment]
@agreaves
Hi, the issue 2 has not been fixed in the latest version
<img width="585" alt="Capture d’écran 2024-01-11 à 13 52 49" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40824967/c510898b-3064-4f5b-977b-012f500a407e">
<img width="1639" alt="Capture d’écran 2024-01-11 à 13 57 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40824967/51c165e0-a2be-4bb1-a914-9bcfee369644">
