### ISSUE TITLE
logout authentication bug

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#1773]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

after logging in via SMS on IOS, the app runs as normally. however, if i logout, login again without closing the app, the on page load actions dont run on the home page. 

### Expected Behavior

On page load actions should always load. 

### Steps to Reproduce

1. Build app with sms auth.
2. Have several actions set to run on the logged in page
3. logout
4. login again without closing app
5. actions dont run. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0sNobbxAjIoDoPJkUaeLBXBJvXuGndwltKEWIpGE1wM70heOeUcI5FxWaUb5Tzrh2Eg/MWkW/aoStCKW0Y3MlM+hWCh2z0Z2RnSV7LbNpS3gE7E2mCeqUfHbcK736Zwh9f6PHaOI=

### Context

the app requires on page load actions to run correctly on the home page. 

### Visual documentation

i dont want to add video here since my project isnt released and this is public. feel free to message privately if needed. this is one error message I'm seeing when doing the auth the second time which may be the reason. 

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0 Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4558:9)
#1 Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4572:6)
#2 Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4591:12)
#3 GoRouter.of (package:go_router/src/router.dart:384:17)
#4 NavigationExtensions.goNamedAuth (package:noplans/flutter_flow/nav/nav.dart:484:28)
#5 _OnboardingPhoneWidgetState.build.<anonymous closure>.<anonymous closure> (package:noplans/pages/onboarding_phone/onboarding_ph<…>

### Environment

```markdown
- FlutterFlow version: latest
- Platform: IOS
- Browser name and version: chrome, latest
- Operating system and version affected:IOS 17.1
```

**Comment by hariprasadms** [comment]
Hi @aaronmt93 - Thanks for submitting the issue. I have looked at your project and also tested the above steps. It can confirm that on page load actions are triggering as expected.

In your project, I guess onboaring_completed field status is not properly updating when user is logged in. Check the status of it and see if there any improvements.

**Comment by aaronmt93** [comment]
@hariprasadms the issue is on IOS, not on web if were able to see the issue on an iphone? thats where I have the issue

**Comment by hariprasadms** [comment]
I have tested on iphone simulator. I am not able to reproduce the steps.
