### ISSUE TITLE
xcode breaks after setting up notifications

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#1774]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

xcode won't run app after setting up the notifications per the documentation instructions

### Expected Behavior

app should run in xcode on iphone

### Steps to Reproduce

1. create app
2. enable notifications in app per documentation
3. attempt to run on phone. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0sNobbxAjIoDoPJkUaeLBXBJvXuGndwltKEWIpGE1wM70heOeUcI5FxWaUb5Tzrh2Eg/MWkW/aoStCKW0Y3MlM+hWCh2z0Z2RnSV7LbNpS3gE7E2mCeqUfHbcK736Zwh9f6PHaOI=

### Context

unable to test the app on my device slowing down testing and production

### Visual documentation

error message here

Could not build the precompiled application for the device.
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': ExtractAppIntentsMetadata
○ Target 'Runner' has copy command from '/Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/ImageNotification.appex' to '/Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/PlugIns/ImageNotification.appex'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/ImageNotification.appex' to '/Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/PlugIns/ImageNotification.appex'

Raw dependency cycle trace:
target: ->
node: <all> ->
command: <all> ->
node: /Users/aaronmtiscarenoaaronmtiscareno/Library/Developer/Xcode/DerivedData/Runner-egmxridmmokgicexgmqixrwtdzjr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata ->
command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->
node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files> ->
command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files ->
node: <Copy /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/PlugIns/ImageNotification.appex> ->
CYCLE POINT ->
command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/PlugIns/ImageNotification.appex /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/ImageNotification.appex ->
node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources> ->
command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources ->
node: /Users/aaronmtiscarenoaaronmtiscareno/Library/Developer/Xcode/DerivedData/Runner-egmxridmmokgicexgmqixrwtdzjr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-55067970987309DE09E9DE72-Pods-Runner-resources-Debug-input-files-58961480d68d951a7c35514607e664ea-resolved.xcfilelist ->
command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/aaronmtiscarenoaaronmtiscareno/Library/Developer/Xcode/DerivedData/Runner-egmxridmmokgicexgmqixrwtdzjr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-55067970987309DE09E9DE72-Pods-Runner-resources-Debug-input-files-58961480d68d951a7c35514607e664ea-resolved.xcfilelist ->
node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->
command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->
node: /Users/aaronmtiscarenoaaronmtiscareno/Library/Developer/Xcode/DerivedData/Runner-egmxridmmokgicexgmqixrwtdzjr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-2838A0ADC44730F0A2303575-Pods-Runner-frameworks-Debug-input-files-e8e8bef62a84a185c0a07def74041b5f-resolved.xcfilelist ->
command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/aaronmtiscarenoaaronmtiscareno/Library/Developer/Xcode/DerivedData/Runner-egmxridmmokgicexgmqixrwtdzjr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-2838A0ADC44730F0A2303575-Pods-Runner-frameworks-Debug-input-files-e8e8bef62a84a185c0a07def74041b5f-resolved.xcfilelist ->
node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->
command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->
node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->
command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/aaronmtiscarenoaaronmtiscareno/Library/Developer/Xcode/DerivedData/Runner-egmxridmmokgicexgmqixrwtdzjr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->
node: /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/Info.plist/ ->
directoryTreeSignature: k ->
directoryContents: /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/Info.plist ->
node: /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/Info.plist ->
command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/Info.plist /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/ios/Runner/Info.plist ->
node: /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/PlugIns/ImageNotification.appex ->
command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/Runner.app/PlugIns/ImageNotification.appex /Users/aaronmtiscarenoaaronmtiscareno/StudioProjects/noplans/build/ios/Debug-iphoneos/ImageNotification.appex

Error launching application on Aphone.
​

### Environment

```markdown
- FlutterFlow version: latest
- Platform: IOS
- Browser name and version: chrome, latest
- Operating system and version affected:IOS 17.1
```

**Comment by JustUserHere** [comment]
i have exactly the same issue: Push notifications error: Cycle inside Runner; building could produce unreliable results. #1766

**Comment by hariprasadms** [comment]
Duplicate with #1766 . Lets close this issues and follow 1766.
