### ISSUE TITLE
Endless loading when trying to display a video stored on Firestore

### ISSUE THREAD

**Issue by DimitriKamps** [FlutterFlow/flutterflow-issues#1775]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have some videos uploaded on my Firestore project and when I want to display them in the app they are loading endlessly

### Expected Behavior

to display the video

### Steps to Reproduce

Create a new page, create a container inside of it create a video player. Add a backend query, then assign the path to the video player ( video stored in Firestore). Try to display the video in the app --> endless loading

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkcn63892rsBE7pD+c8dF9SkQIjs9RJI3kcFxdCs/CYDuBJkQefjRfkppXdOrdkFHeWCJmXEzzPDSm9z1JvQ6FziBGIg7+s12UzrdXnOQR8mnDs2KPER+GshRIFyg5KevrSJdKvh0WWQXw2eYP+mUcB7fQqbSIVQ3AvyaFJnXmAfuQ0SLb3kNh1JWeC/v

### Context

display some videos in the app

### Visual documentation

<img width="453" alt="Screenshot 2023-11-03 at 18 50 19" src="https://github.com/FlutterFlow/flutterflow-issues/assets/149817263/84fa5c39-f460-4378-9949-f2fb63273e29">

### Environment

```markdown
- FlutterFlow version: v3.13.7
- Platform: MacOS 
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by hariprasadms** [comment]
Hi @DimitriKamps - Thanks submitting the issue. I looked at your project. Looks at below error displayed while accessing the video on the page. Is this URL path correct ? are you able access video using the path link ? how did you upload the video to firebase ?. If you are able to access the video link outside FF ( when you logged in to fb with a valid user ) , its pretty much should work with no issues. Please check these points. 

<img width="1172" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/0ab0fdc2-e337-4787-a1e2-86d0f08502c5">

**Comment by hariprasadms** [comment]
Yes the link is wrong. You should take the link from here. See below.

<img width="1188" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ada0a271-61c2-4aa0-8ab2-3f25bf0b8389">

**Comment by hariprasadms** [comment]
Close the issue once you are able to add the correct link and access the video inside app.

**Comment by DimitriKamps** [comment]
Thank you very much for your help !
