### ISSUE TITLE
TabBar widget not responding to single-tap actions

### ISSUE THREAD

**Issue by TruckeeDavid** [FlutterFlow/flutterflow-issues#1776]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm unable to get actions to respond to a single-tap or double-tap from the TabBar widget buttons. Double-tap and long-tap both work fine. And the single-tap is registered when the widget main body is clicked. (Just not the buttons.)

### Expected Behavior

"On Tap" should trigger actions.

### Steps to Reproduce

1. Create a new project
2. Add TabBar widget to the home page
3. Add single-tap action to show snackbar (or whatever)
4. Nothing happens on a single tap of the TabBar buttons, but it _will_ work when the main body of the widget is single-tapped. (Double-tap and long-tap events work as expected.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/LlwItIsdtK0L6JcMBajWMsQ0McTIMziNZ+exUbfaL1BqQUePT7MxJtcNyraVNfM0yZjl8Fwa3lj/L1FfVeIU+dRr5zzrpyUgnee2iuRrq3O6mWR0B6J/5NCm7EyJ+z3REkIbZicUFn72etetmRQj3DFOu/Zwh9f6PHaOI=

### Context

Trying to create an action to update a page-state variable based on the TabBar button clicked. 

### Visual documentation

<img width="1340" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/84606817/64776743-4219-475c-8141-1bc39d0ea283">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Mac OS
- Browser name and version: Chrome 118.0.5993.117
- Operating system and version affected: Mac OS 14.1
```

**Comment by wenkaifan0720** [comment]
Hi @TruckeeDavid. I don't think onTap should be supported for the TabBar widget. The onTap action should be set for each Tab instead, which we will support in our next update. And if you just want the current index of the TabBar widget, you have access to it in the Widget States.
