### ISSUE TITLE
Test API Call endpoint marked as phishing by google - affects Test Mode as well

### ISSUE THREAD

**Issue by cswizard11** [FlutterFlow/flutterflow-issues#1777]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When clicking the 'Test API Call' button, Chromium blocks the request and warns of a 'Deceptive site ahead'. This is true for each of my API calls.

### Expected Behavior

I expect the 'Test API Call' button to make the request I provide, and return the response.

### Steps to Reproduce

1. Create a new API Call
2. Add a Call Name and URL. To test, I used the name Test and the URL https://jsonplaceholder.typicode.com/todos/1
3. Under the 'Response & Test' tab, click 'Test API Call'
4. Observe that the request has been blocked

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shcqB4otOodtb+Kr+bsBB/TovJUA9bJ0ksctCTQwgGL7yBuwQZM/OQBRvOMyoaVNcKFWignsDp9KPjYfPF/UBFymsRbpMwbl+ETnOe2ijRbrQDaW8Ynd6DcdjCB3A0cGVkRUlBNZ0W1YA612Ye/PIVirDFOu/Zwh9f6PHaOI=

### Context

I am trying to test my API calls, and cannot do so without disabling Chromium's deceptive and dangerous site alerts.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13397393/d47e6729-b574-4aff-8c4f-0caaadb5bc7c)

### Environment

```markdown
- FlutterFlow version: 3.17.7
- Platform: Web
- Browser name and version: Chromium 119.0.6045.105
- Operating system and version affected: Arch Linux kernel 6.5.9-arch2-1
```

**Comment by cswizard11** [comment]
I have just tried to test my app by running in Test Mode, and when the app tries to make an API call I experience the same issue as above

**Comment by roderickjackson** [comment]
I'm experiencing the same issue also.

**Comment by srh98** [comment]
Also experiencing the same issue

**Comment by roderickjackson** [comment]
This issue has been resolved for me on Sunday. I'm able to test the APIs with out any issues.
