### ISSUE TITLE
Compilation Error - Supabase table field names & Test Mode not working  

### ISSUE THREAD

**Issue by AleksRatkovic** [FlutterFlow/flutterflow-issues#1778]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am not able to generate a test build in test mode. I removed all the widgets, more or less, to make sure it wasn't something with the way it was set up initially but realized it is due to the way flutterflow is reading the supabase table which is integrated within the flutterflow app.

Based on the error messages, it appears it is getting caught up on a particular table called stock_data where there is a column names "T" and another column named "t". These a two different columns with different values of data. We are not able to rename these columns on the database side because this table receives data from an API and would no longer work if we renamed either column within Supabase. All other view within supabase which are based off of this core table work just fine. 

I messaged the team via chat and said that this is definitely a bug and create an issue he directly. Thank you for looking into this.

### Expected Behavior

Expected to generate test build without issues. Technically the columns are named differently, particularly when referencing the character case. 

### Steps to Reproduce

1. Just try generating a build in test within the PlayTradez app. https://app.flutterflow.io/project/play-tradez-icuj30?tab=uiBuilder&page=Login

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Launching lib/main.dart on Web Server in debug mode... Waiting for connection from debug service on Web Server...       lib/backend/supabase/database/tables/stock_data.dart:38:15: Error: 'tField' is already declared in this scope.   String? get tField => getField<String>('t');               ^^^^^^ lib/backend/supabase/database/tables/stock_data.dart:20:15: Context: Previous declaration of 'tField'.   String? get tField => getField<String>('T');               ^^^^^^ lib/backend/supabase/database/tables/stock_data.dart:39:7: Error: 'tField' is already declared in this scope.   set tField(String? value) => setField<String>('t', value);       ^^^^^^ lib/backend/supabase/database/tables/stock_data.dart:21:7: Context: Previous declaration of 'tField'.   set tField(String? value) => setField<String>('T', value);       ^^^^^^ Waiting for connection from debug service on Web Server...         54.0s Failed to compile application.

### Context

We are trying to build out this app using the backend tables and databases we have built within Supabase but this bug is preventing us from moving forward with anything. 

### Visual documentation

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/backend/supabase/database/tables/stock_data.dart:38:15: Error: 'tField' is already declared in this scope.
  String? get tField => getField<String>('t');
              ^^^^^^
lib/backend/supabase/database/tables/stock_data.dart:20:15: Context: Previous declaration of 'tField'.
  String? get tField => getField<String>('T');
              ^^^^^^
lib/backend/supabase/database/tables/stock_data.dart:39:7: Error: 'tField' is already declared in this scope.
  set tField(String? value) => setField<String>('t', value);
      ^^^^^^
lib/backend/supabase/database/tables/stock_data.dart:21:7: Context: Previous declaration of 'tField'.
  set tField(String? value) => setField<String>('T', value);
      ^^^^^^
Waiting for connection from debug service on Web Server...         54.0s
Failed to compile application.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/69167934/d43e4a20-b6f2-4ff6-a43b-096fd4d8f7e0)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/69167934/f44c3401-d731-4f1f-a18a-1d6ba4400505)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web, Desktop, PC
- Browser name and version: Chrome, latest version
- Operating system and version affected: Windows 11 Pro
```

**Comment by AleksRatkovic** [comment]
Another point to note here is that the app/project isn't even using the this table that is causing the issue. In fact, the project is more or less blank and isn't referencing any tables or views from Supabase at the moment. 

It will only reference the views that have been built based off of the stock_data table.

**Comment by SameerShahzad99** [comment]
@AleksRatkovic Thank you for reporting this bug, i was able to reproduce this on my end!

**Comment by AleksRatkovic** [comment]
thanks @SameerShahzad99 - is this an easy fix on your end?

**Comment by AleksRatkovic** [comment]
hi @SameerShahzad99 @takashiff - just following and seeing we have resolved the issue on your end?

**Comment by AleksRatkovic** [comment]
@SameerShahzad99 @takashiff following up here

**Comment by takashiff** [comment]
Hello, thank you for your bug report. We have fixed this issue and it should be reflected in our next deploy. For future reference, the bug report code is generated by right-clicking the relevant widget and clicking "Generate Bug Report Code." Thank you for your continued patience.
