### ISSUE TITLE
Custom Fonts causing errors in Test mode & Prod 

### ISSUE THREAD

**Issue by paybud** [FlutterFlow/flutterflow-issues#1779]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I used a third party Text file, that I uploaded into Flutterflow, and now sits in the custom fonts category.

This error only seems to apply in Mobile test, what can I do to fix this? 
<img width="387" alt="Screenshot 2023-11-04 at 13 10 23" src="https://github.com/FlutterFlow/flutterflow-issues/assets/149337993/4b2cdbd0-c3c4-4b54-a6ce-a5b08b19990a">

### Expected Behavior

No error to show and screen to load

### Steps to Reproduce

1: upload custom font
2: add custom font to an element
3: run test mode
4: switch to mobile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Padding(   padding: EdgeInsetsDirectional.fromSTEB(0.0, 40.0, 0.0, 0.0),   child: Column(     mainAxisSize: MainAxisSize.max,     crossAxisAlignment: CrossAxisAlignment.start,     children: [       Padding(         padding: EdgeInsetsDirectional.fromSTEB(24.0, 24.0, 0.0, 20.0),         child: Row(           mainAxisSize: MainAxisSize.max,           mainAxisAlignment: MainAxisAlignment.start,           children: [             if (Theme.of(context).brightness == Brightness.dark)               Image.asset(                 'assets/images/PayBud_Logo_(3).png',                 width: 170.0,                 height: 60.0,                 fit: BoxFit.fitWidth,               ),             if (!(Theme.of(context).brightness == Brightness.dark))               Image.asset(                 'assets/images/finWallet_logo_landscapeDark@3x.png',                 width: 170.0,                 height: 60.0,                 fit: BoxFit.fitWidth,               ),           ],         ),       ),       Padding(         padding: EdgeInsetsDirectional.fromSTEB(24.0, 0.0, 24.0, 0.0),         child: SingleChildScrollView(           child: Column(             mainAxisSize: MainAxisSize.max,             children: [               Row(                 mainAxisSize: MainAxisSize.max,                 children: [                   Text(                     FFLocalizations.of(context).getText(                       'o07j3mgv' /* Let's get you inside.  */,                     ),                     style: FlutterFlowTheme.of(context).displaySmall.override(                           fontFamily: 'Telegraf',                           useGoogleFonts: GoogleFonts.asMap().containsKey(                               FlutterFlowTheme.of(context)                                   .displaySmallFamily),                         ),                   ),                 ],               ),               Padding(                 padding: EdgeInsetsDirectional.fromSTEB(0.0, 12.0, 0.0, 0.0),                 child: Row(                   mainAxisSize: MainAxisSize.max,                   children: [                     Text(                       FFLocalizations.of(context).getText(                         'fzxvw3mu' /* Login for access to your accou... */,                       ),                       style:                           FlutterFlowTheme.of(context).titleMedium.override(                                 fontFamily: 'Telegraf',                                 useGoogleFonts: GoogleFonts.asMap()                                     .containsKey(FlutterFlowTheme.of(context)                                         .titleMediumFamily),                               ),                     ),                   ],                 ),               ),               Padding(                 padding: EdgeInsetsDirectional.fromSTEB(0.0, 20.0, 0.0, 0.0),                 child: TextFormField(                   controller: _model.emailAddressLoginController,                   focusNode: _model.emailAddressLoginFocusNode,                   obscureText: false,                   decoration: InputDecoration(                     labelText: FFLocalizations.of(context).getText(                       'a9j78va9' /* Email Address */,                     ),                     labelStyle: FlutterFlowTheme.of(context)                         .bodySmall                         .override(                           fontFamily: 'Telegraf',                           useGoogleFonts: GoogleFonts.asMap().containsKey(                               FlutterFlowTheme.of(context).bodySmallFamily),                         ),                     hintText: FFLocalizations.of(context).getText(                       'i7f18cve' /* Enter your email... */,                     ),                     hintStyle: FlutterFlowTheme.of(context)                         .bodySmall                         .override(                           fontFamily: 'Telegraf',                           useGoogleFonts: GoogleFonts.asMap().containsKey(                               FlutterFlowTheme.of(context).bodySmallFamily),                         ),                     enabledBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     focusedBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     errorBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     focusedErrorBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     filled: true,                     fillColor:                         FlutterFlowTheme.of(context).secondaryBackground,                     contentPadding: EdgeInsetsDirectional.fromSTEB(                         20.0, 24.0, 20.0, 24.0),                   ),                   style: FlutterFlowTheme.of(context).bodyMedium.override(                         fontFamily: 'Telegraf',                         useGoogleFonts: GoogleFonts.asMap().containsKey(                             FlutterFlowTheme.of(context).bodyMediumFamily),                       ),                   validator: _model.emailAddressLoginControllerValidator                       .asValidator(context),                 ),               ),               Padding(                 padding: EdgeInsetsDirectional.fromSTEB(0.0, 12.0, 0.0, 0.0),                 child: TextFormField(                   controller: _model.passwordLoginController,                   focusNode: _model.passwordLoginFocusNode,                   obscureText: !_model.passwordLoginVisibility,                   decoration: InputDecoration(                     labelText: FFLocalizations.of(context).getText(                       'wztjmbn8' /* Password */,                     ),                     labelStyle: FlutterFlowTheme.of(context)                         .bodySmall                         .override(                           fontFamily: 'Telegraf',                           useGoogleFonts: GoogleFonts.asMap().containsKey(                               FlutterFlowTheme.of(context).bodySmallFamily),                         ),                     hintText: FFLocalizations.of(context).getText(                       'lw1jpm1f' /* Enter your password... */,                     ),                     hintStyle: FlutterFlowTheme.of(context)                         .bodySmall                         .override(                           fontFamily: 'Telegraf',                           useGoogleFonts: GoogleFonts.asMap().containsKey(                               FlutterFlowTheme.of(context).bodySmallFamily),                         ),                     enabledBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     focusedBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     errorBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     focusedErrorBorder: OutlineInputBorder(                       borderSide: BorderSide(                         color: Color(0x00000000),                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(8.0),                     ),                     filled: true,                     fillColor:                         FlutterFlowTheme.of(context).secondaryBackground,                     contentPadding: EdgeInsetsDirectional.fromSTEB(                         20.0, 24.0, 20.0, 24.0),                     suffixIcon: InkWell(                       onTap: () => setState(                         () => _model.passwordLoginVisibility =                             !_model.passwordLoginVisibility,                       ),                       focusNode: FocusNode(skipTraversal: true),                       child: Icon(                         _model.passwordLoginVisibility                             ? Icons.visibility_outlined                             : Icons.visibility_off_outlined,                         color: Color(0x98FFFFFF),                         size: 20.0,                       ),                     ),                   ),                   style: FlutterFlowTheme.of(context).bodyMedium.override(                         fontFamily: 'Telegraf',                         useGoogleFonts: GoogleFonts.asMap().containsKey(                             FlutterFlowTheme.of(context).bodyMediumFamily),                       ),                   validator: _model.passwordLoginControllerValidator                       .asValidator(context),                 ),               ),               Row(                 mainAxisSize: MainAxisSize.max,                 mainAxisAlignment: MainAxisAlignment.spaceBetween,                 children: [                   FFButtonWidget(                     onPressed: () {                       print('Button-Login pressed ...');                     },                     text: FFLocalizations.of(context).getText(                       'qbmoi1av' /* Login */,                     ),                     options: FFButtonOptions(                       width: 341.0,                       height: 50.0,                       padding:                           EdgeInsetsDirectional.fromSTEB(0.0, 0.0, 0.0, 0.0),                       iconPadding:                           EdgeInsetsDirectional.fromSTEB(0.0, 0.0, 0.0, 0.0),                       color: FlutterFlowTheme.of(context).primary,                       textStyle:                           FlutterFlowTheme.of(context).titleSmall.override(                                 fontFamily: 'Telegraf',                                 color: FlutterFlowTheme.of(context).secondary,                                 useGoogleFonts: GoogleFonts.asMap()                                     .containsKey(FlutterFlowTheme.of(context)                                         .titleSmallFamily),                               ),                       elevation: 3.0,                       borderSide: BorderSide(                         color: Colors.transparent,                         width: 1.0,                       ),                       borderRadius: BorderRadius.circular(30.0),                     ),                   ),                 ],               ),             ],           ),         ),       ),       Padding(         padding: EdgeInsetsDirectional.fromSTEB(0.0, 20.0, 0.0, 0.0),         child: Row(           mainAxisSize: MainAxisSize.max,           mainAxisAlignment: MainAxisAlignment.center,           children: [             InkWell(               splashColor: Colors.transparent,               focusColor: Colors.transparent,               hoverColor: Colors.transparent,               highlightColor: Colors.transparent,               onTap: () async {                 context.pushNamed('registerAccount');               },               child: Container(                 width: MediaQuery.sizeOf(context).width * 0.8,                 height: 44.0,                 decoration: BoxDecoration(                   color: FlutterFlowTheme.of(context).secondaryBackground,                   borderRadius: BorderRadius.circular(8.0),                 ),                 child: InkWell(                   splashColor: Colors.transparent,                   focusColor: Colors.transparent,                   hoverColor: Colors.transparent,                   highlightColor: Colors.transparent,                   onTap: () async {                     context.pushNamed(                       'PayBudOnboarding',                       extra: <String, dynamic>{                         kTransitionInfoKey: TransitionInfo(                           hasTransition: true,                           transitionType: PageTransitionType.rightToLeft,                         ),                       },                     );                   },                   child: Row(                     mainAxisSize: MainAxisSize.max,                     mainAxisAlignment: MainAxisAlignment.center,                     children: [                       Text(                         FFLocalizations.of(context).getText(                           'cjqb8ial' /* Don't have an account? */,                         ),                         style: FlutterFlowTheme.of(context)                             .bodyMedium                             .override(                               fontFamily: 'Telegraf',                               useGoogleFonts: GoogleFonts.asMap().containsKey(                                   FlutterFlowTheme.of(context)                                       .bodyMediumFamily),                             ),                       ),                       Padding(                         padding: EdgeInsetsDirectional.fromSTEB(                             15.0, 0.0, 0.0, 0.0),                         child: FFButtonWidget(                           onPressed: () async {                             context.pushNamed(                               'PayBudOnboarding',                               extra: <String, dynamic>{                                 kTransitionInfoKey: TransitionInfo(                                   hasTransition: true,                                   transitionType:                                       PageTransitionType.leftToRight,                                 ),                               },                             );                           },                           text: FFLocalizations.of(context).getText(                             'd6jkak2c' /* Create */,                           ),                           options: FFButtonOptions(                             height: 38.0,                             padding: EdgeInsetsDirectional.fromSTEB(                                 24.0, 0.0, 24.0, 0.0),                             iconPadding: EdgeInsetsDirectional.fromSTEB(                                 0.0, 0.0, 0.0, 0.0),                             color: Color(0xFF012800),                             textStyle: FlutterFlowTheme.of(context)                                 .titleSmall                                 .override(                                   fontFamily: 'Telegraf',                                   color: FlutterFlowTheme.of(context).primary,                                   useGoogleFonts: GoogleFonts.asMap()                                       .containsKey(                                           FlutterFlowTheme.of(context)                                               .titleSmallFamily),                                 ),                             elevation: 1.0,                             borderSide: BorderSide(                               color: Colors.transparent,                               width: 1.0,                             ),                             borderRadius: BorderRadius.circular(8.0),                           ),                         ),                       ),                     ],                   ),                 ),               ),             ),           ],         ),       ),       Padding(         padding: EdgeInsetsDirectional.fromSTEB(0.0, 2.0, 0.0, 24.0),         child: FFButtonWidget(           onPressed: () async {             context.pushNamed('forgotPassword');           },           text: FFLocalizations.of(context).getText(             'm2xyjvuf' /* Forgot Password? */,           ),           options: FFButtonOptions(             width: 170.0,             height: 40.0,             padding: EdgeInsetsDirectional.fromSTEB(0.0, 0.0, 0.0, 0.0),             iconPadding: EdgeInsetsDirectional.fromSTEB(0.0, 0.0, 0.0, 0.0),             color: Color(0x001A1F24),             textStyle: FlutterFlowTheme.of(context).bodySmall.override(                   fontFamily: 'Telegraf',                   useGoogleFonts: GoogleFonts.asMap().containsKey(                       FlutterFlowTheme.of(context).bodySmallFamily),                 ),             elevation: 0.0,             borderSide: BorderSide(               color: Colors.transparent,               width: 1.0,             ),             borderRadius: BorderRadius.circular(8.0),           ),         ),       ),       StyledDivider(         thickness: 1.0,         color: FlutterFlowTheme.of(context).tertiary,         lineStyle: DividerLineStyle.dashed,       ),       Padding(         padding: EdgeInsetsDirectional.fromSTEB(20.0, 20.0, 0.0, 0.0),         child: Column(           mainAxisSize: MainAxisSize.max,           crossAxisAlignment: CrossAxisAlignment.start,           children: [             Text(               FFLocalizations.of(context).getText(                 '33i716s3' /* Looking for... */,               ),               style: FlutterFlowTheme.of(context).bodyMedium.override(                     fontFamily: 'Telegraf',                     useGoogleFonts: GoogleFonts.asMap().containsKey(                         FlutterFlowTheme.of(context).bodyMediumFamily),                   ),             ),             if (Theme.of(context).brightness == Brightness.dark)               Image.asset(                 'assets/images/PayBud_Logo_(4).png',                 width: 170.0,                 height: 60.0,                 fit: BoxFit.fitWidth,               ),             Text(               FFLocalizations.of(context).getText(                 'ahddqm3u' /* Click here instead */,               ),               style: FlutterFlowTheme.of(context).bodyMedium.override(                     fontFamily: 'Telegraf',                     useGoogleFonts: GoogleFonts.asMap().containsKey(                         FlutterFlowTheme.of(context).bodyMediumFamily),                   ),             ),             Padding(               padding: EdgeInsetsDirectional.fromSTEB(0.0, 10.0, 0.0, 0.0),               child: FFButtonWidget(                 onPressed: () async {                   context.goNamed(                     'BusinessBudhomePage',                     extra: <String, dynamic>{                       kTransitionInfoKey: TransitionInfo(                         hasTransition: true,                         transitionType: PageTransitionType.rightToLeft,                       ),                     },                   );                 },                 text: FFLocalizations.of(context).getText(                   '7yjwyr26' /* Business */,                 ),                 options: FFButtonOptions(                   height: 40.0,                   padding:                       EdgeInsetsDirectional.fromSTEB(24.0, 0.0, 24.0, 0.0),                   iconPadding:                       EdgeInsetsDirectional.fromSTEB(0.0, 0.0, 0.0, 0.0),                   color: FlutterFlowTheme.of(context).primary,                   textStyle: FlutterFlowTheme.of(context).titleSmall.override(                         fontFamily: 'Telegraf',                         color: FlutterFlowTheme.of(context).secondary,                         useGoogleFonts: GoogleFonts.asMap().containsKey(                             FlutterFlowTheme.of(context).titleSmallFamily),                       ),                   elevation: 3.0,                   borderSide: BorderSide(                     color: Colors.transparent,                     width: 1.0,                   ),                   borderRadius: BorderRadius.circular(8.0),                 ),               ),             ),           ],         ),       ),     ],   ), )

### Context

can't test app in mobile test mode. 

### Visual documentation

<img width="387" alt="Screenshot 2023-11-04 at 13 10 23" src="https://github.com/FlutterFlow/flutterflow-issues/assets/149337993/dcfa91aa-0f17-4aec-9e95-1a5dea7725ef">

### Environment

```markdown
- FlutterFlow version: v4.02 Flutter 3.13.7
- Platform: MacOS Desktop
- Browser name and version: Arc Browser Version 1.15.1 (43023)
Chromium Engine Version 119.0.6045.105
- Operating system and version affected: MacOS Ventura Version 13.4
```

**Comment by SameerShahzad99** [comment]
@paybud  Can you please share the correct bug report code from the blank project with issue reproduced, so i test this issue on my end?

**Comment by SameerShahzad99** [comment]
Closing this ticket due to a lack of response from the user.
