### ISSUE TITLE
Problem with Algolia Search in ListView

### ISSUE THREAD

**Issue by ReCoL1337** [FlutterFlow/flutterflow-issues#1780]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

ListView doesn't load some items returned by Algolia. It just loads forever.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/bd9e9c56-e023-42df-95cf-b231561b1891)

### Expected Behavior

ListView shows everything that algolia returns

### Steps to Reproduce

1. Open my project in run mode (test mode doesn't work - see https://github.com/FlutterFlow/flutterflow-issues/issues/1763 for more info)
2. Go to the Dashboard page
3. If you leave the textfield empty ListView will just load forever (I have set a wildcard as a default variable for the textfield). Other queries don't work too (sometimes one of them works but I don't know when this happens).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghvLlvJROxL1E0M/ucO9Vu2U4Qm4jaL00st4bGAsdGOvrBu0EPs+laRJvOebgaVNcf1egoEIC+eDyjuHyUu4qKSiaUaJTyblcWxXOe2ihWpDTDcyKY3wnEcVQG2KmyMKvvglRCPtpWk4n3HGqBfOREwPDFOu/Zwh9f6PHaOI=

### Context

I basically copied this video: https://www.youtube.com/watch?v=jtdhOdCCzk8 (first 7 minutes)
In the Algolia dashboard everything looks fine:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/7c64e9df-757e-417f-bc65-fb15d8f6d7a8)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/b7f1e856-6e41-426e-884a-a1f10943f12b)
When typing "value"
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/3e0dcb1f-3b5a-436e-aa84-76f257ab8c4f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/03456956-c208-407b-9991-97d2e9fe86dc)
Here is the configuration file for the index:
[export-Products-ESQBRFMEBX-1699111425.json](https://github.com/FlutterFlow/flutterflow-issues/files/13257012/export-Products-ESQBRFMEBX-1699111425.json)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/da25f6f8-4c6c-4a28-ab31-dc4618ccc46e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/7c64e9df-757e-417f-bc65-fb15d8f6d7a8)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/b7f1e856-6e41-426e-884a-a1f10943f12b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/3e0dcb1f-3b5a-436e-aa84-76f257ab8c4f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46446137/03456956-c208-407b-9991-97d2e9fe86dc)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: OperaGX, Firefox, Google Chrome
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @ReCoL1337 - Thanks for submitting the issue. Sorry for the delay in response to the issue. Are you still facing the issue or issue resolved ?

**Comment by hariprasadms** [comment]
Hi @ReCoL1337 - There is no response about issue status. I presume issues has been resolved for you. Hence closing the issue. Thanks
