### ISSUE TITLE
Triggered by action PUSH notification's image is not displaying.

### ISSUE THREAD

**Issue by elementh69** [FlutterFlow/flutterflow-issues#1781]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Sending push notification to post owner with information who likes his post.
Field recipient - working
Field title - working
Field text - working
Field image - not working (value is set to postPhoto)

### Expected Behavior

Receiving push notifications with all field information and photo.

### Steps to Reproduce

Trigger push notification by action and as a value of image field set some photo from database (ie. post photo or user photo).
Warning! Sending notofication with image from notification settings or project is working correctly.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMrqy4xOj7xY17X5bcZWhiA7H181TLJMqNYbGA0hfbWsO4YqZc7STExLYtemdwhhM1eahTkzw6HTjoX1Mcc4PT+bbJxk+JRXQQLvfEmQR5S2OqjhRkZBP5thBWaz1sKRoiZ+ItZaR2Rg62eQfPCdG3qCf9qOYwx5e6fDbOY=

### Context

I was trying to send push notification with photo/image/picture.

### Visual documentation

<img width="646" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13348374/266fd48b-fb27-4473-afcc-d9a4adce1e19">

### Environment

```markdown
- FlutterFlow version: today
- Platform: android
- Browser name and version: chrome
- Operating system and version affected: macOS
```

**Comment by elementh69** [comment]
*UPDATE*
Avatar pictures are working, only big images like postPhoto are not displaying in the push notification.

**Comment by takashiff** [comment]
Hi @elementh69, I apologize for the delayed response. This is currently intended behavior, as push notification images have a max limit of 300 KB. Thanks
