### ISSUE TITLE
Firestore query not returning or displaying all records

### ISSUE THREAD

**Issue by dwatrous** [FlutterFlow/flutterflow-issues#1783]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a ListView that queries a Firestore database. Rather than load all records, it only loads one. Here is how I have setup the query in flutterflow
![2023-11-04_20-29-31](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/ee0d48c1-435e-44f2-9c21-43d06b0cf14e)

Here you can see that my firestore database with what I think is the same query, returns two records.
![2023-11-04_20-29-02](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/2d65b0db-08d5-417d-bc10-59eb4be30e51)

When testing the app, only one is returned and listed
![2023-11-04_20-25-54](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/fc56a7db-4bce-4a21-b6b1-33b649722c2d)

### Expected Behavior

I would expect all records matching the query to be displayed in the listview

### Steps to Reproduce

1. Create a listview and add a qeury
2. query only returns or lists one document

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi8mBx4dIoeEA1oSJbfpaqyQRH1wibZIzjspBZzUYF5SuCLMqY8mnP0huUvW8d1VYIWGcp14C3OjQjvPMFfcFAEiBbI85zKl2Fg7iLV+RbqmTF7uWXEYlHfhVCB2H1rSziCRSOsdpcXMt7GWEDOmRUnPqNYzROWo8Sq/LZO4=

### Context

I am concerned that some relevant records won't be listed.

### Visual documentation

See above

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: FlutterFlow website loaded as Test
- Browser name and version: Chrome 118.0.5993.120 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

**Comment by dwatrous** [comment]
This is still happening.

**Comment by DayneLinx** [comment]
I have the same problem and it has not been resolved for months...

**Comment by katherineqian** [comment]
Hi @DayneLinx, would you mind adding a bug report code? It's possible these may be different issues so I'd like to confirm when investigating.

**Comment by hariprasadms** [comment]
Hi @dwatrous - Due to inactivity in the issue, we presume the issue has been resolved with the latest FF updates. Hence, I am closing the issue. If the issue still persists, feel free to reopen or create a new one.

**Comment by timfong888** [comment]
I have had the same problem and filed a new ticket.  I ended up writing up my own script using the firebase admin sdk with the same query and get the correct results.
