### ISSUE TITLE
Links/buttons etc Do Not Work When You Publish To App Store TestFlight

### ISSUE THREAD

**Issue by prayersocial** [FlutterFlow/flutterflow-issues#1784]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I run my project in test mode all links, action buttons etc work fine as expected but when I publish to Apple TestFlight and install on an Iphone, non of the links or action buttons work. Basically, other than the main navbar, nothing else works in the App. I've seen a few people report the same bug in the community page. 

### Expected Behavior

The links and buttons etc should work. Please see the video in the link. [https://photos.app.goo.gl/wmb4x62UVQTnyrgg8](url)

### Steps to Reproduce

Please watch the video link I attached in the expected behavior description

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiOfqw5JPm7RE+Kr2dvpanSQQHDsnbecam8pBZywgfZzzBLN/fPfQP1pvYNDhY1Y2e1q2p14C3Pz6idrpNfcFFxWsfKJ6/rl+ezngYzuXbr2TF7rgOHFTEdphIUiE56a3sxBTNbZqSl4B3E2EfumUZCrvO7mwNXo8Sq/LZO4=

### Context

I cannot publish App updates to the App Store. Apple is rejecting the App

### Visual documentation

https://photos.app.goo.gl/DJZS5dvFRNFkrPmz7

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform:Flutter 3.13.7
- Browser name and version:Chrome
- Operating system and version affected: iOS and perhaps Android(I have not tried on Android)
```

**Comment by bscheurman** [comment]
Did you enable dynamic links in the project?  If so, that may be what led to the issue. 
This is an open issue about that #1697

**Comment by prayersocial** [comment]
Dynamic links were already enabled in the project a while back, from the very beginning and it's been fine. So it must a recent bug.

**Comment by SEGVeenstra** [comment]
> Dynamic links were already enabled in the project a while back, from the very beginning and it's been fine. So it must a recent bug.

Same for us. We took over a project that was created earlier this year (around April). Back then Dynamic Links worked.

**Comment by prayersocial** [comment]
Thanks for the feedback. Question - did disabling Dynamic links resolve the issue for you?

**Comment by SEGVeenstra** [comment]
I don't know, haven't tried it because it wasn't an option for our client. We worked around it by just showing a banner message for people that used a link to login, to restart the app.

**Comment by prayersocial** [comment]
Ok, I appreciate the feedback. Thanks.

**Comment by bscheurman** [comment]
disabling dynamic links, and trying it in testflight, resolved it
but its a pretty important feature, so pushing to get it fixed

**Comment by prayersocial** [comment]
thanks for the feedback.

**Comment by JustUserHere** [comment]
Same issue

**Comment by mlagus** [comment]
I also have this problem
App works normal after regular start.
Generating a link
Clicking it
Then it opens app (wrong page) and no other links in the app is working
If i restart the app then all links in the app works again

**Comment by victoriahuang1** [comment]
Hi @prayersocial , can you confirm if this issue has been resolved for you?

**Comment by prayersocial** [comment]
> Hi @prayersocial , can you confirm if this issue has been resolved for you?

No, I waited for so long without response from from FF so I basically had to remove all Dynamic Generated links from my app to make it work. The issue was only present if you had any dynamically generated links in your App.

**Comment by JustUserHere** [comment]
> > Hi @prayersocial , can you confirm if this issue has been resolved for you?
> 
> 
> 
> No, I waited for so long without response from from FF so I basically had to remove all Dynamic Generated links from my app to make it work. The issue was only present if you had any dynamically generated links in your App. 

Hi!
I had the same issue and I solve it with removing custom domain in Firebase. I do not know why, but when custom domain set in firebase dynamic links not working. I can't experiment here, cause when you are removing domain, you need to wait 1 months to add it back

**Comment by victoriahuang1** [comment]
Closing this, but feel free to reopen if the issue persists
