### ISSUE TITLE
FF doesn't detect all components and their elements

### ISSUE THREAD

**Issue by MaximeDelhorme** [FlutterFlow/flutterflow-issues#1786]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a component which has a textfield.
When trying in a "Set Form Field" action to replace the value of the textfield within the component, FlutterFlow shows as option one of components several time instead of an instance of each component.

### Expected Behavior

I expect that each component should be in the list instead of several time the same one.

### Steps to Reproduce

1. Create new page
2. Create component with title and text field
3. Create a column with 4 times this component
4. Change the names of the 4 components
5. Create a Set Form Field action on the column
6. See that FF provide wrong options for set form field

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jMrq081NodhE18/+ccB7/Ck5JWI8a+cvj+x7aDUsIuOtBu0qP8jeYlBDXs/kaVNcKE7+pEUdpfyNi+DxEcInOROBbIR8wpZhFwLOe2iWbKa1EqqKOERSO8VNGnKl4Z+rvQhSJu5eV3wd3F2mCeuAcHPDIuu/Zwh9f6PHaOI=

### Context

I'm trying to populate some textfield automatically.
I can't target them if they are not available in the UI

### Visual documentation

Create 4 components:
<img width="456" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17178134/bd54be3d-21b7-4a83-a0e9-8763818fb39d">
Give them different names:
<img width="264" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17178134/5679d6d4-e41e-47c6-86e8-70e41226f4fe">
Try to target the textfields in a Set Form Field action in the column (or other place):
<img width="274" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17178134/5f888385-1390-4fab-a783-c01cb3faf02a">

Only component4 is visible 4 times.

### Environment

```markdown
- FlutterFlow version: v4.0 (released November 4, 2023)
- Platform: Web
- Browser name and version: Chrome version 113.0.5672.126
- Operating system and version affected: macOS Monterey 12.5
```

**Comment by MaximeDelhorme** [comment]
up

**Comment by MaximeDelhorme** [comment]
up

**Comment by alfredogranda** [comment]
up

**Comment by takashiff** [comment]
Hi all,

We've put in a fix recently for this issue, and it should be reflected within the next few weeks. I want to extend my sincere apologies for the delay in addressing this issue, as it falls short of the level of service we aim to provide. Your patience throughout this process has been greatly appreciated. Thank you for your understanding.
