### ISSUE TITLE
DocReference not functioning in Data Type (2 examples)

### ISSUE THREAD

**Issue by bkannes** [FlutterFlow/flutterflow-issues#1787]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Example 1:

Bug report code:
ITFfzfHl7Yl1xOVc7pSILMFFliAQJnkcTeUzlO1hdwwbI+OsEYkDdc/eXxFWYuqHem9IGmGknkIB+aCMv/HfL+4DAz+BRt0/+pZbUxDhRlmtWqWYC5CoVkd9P8dgN26z0JmNkSYnIvd2R1IdwDiQJe+Aa3qCf9qOYwx5e6fDbOY=

You can see below that when the condition is "app state listGroceriesFruitsVegetables contains item" which is simply a list of document references, then I can easily select Reference from the FoodsSupplements document.

![1](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/e784ef3b-296e-46e8-b17f-f5d76550e90e)

However, when the condition is "app state listGroceriesFruitVegDATATYPE contains item" which uses a data type/dataStruct, then Reference/Document ID is not available.

![2](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/8080529b-eaa3-4a30-90a2-2bb6997ef7b2)

Example 2:

I use DataStruct (Data Type) on the app state level to send default values to Firestore. All parameters and values get sent to Firestore except docReference, although the field does have value!

![appstate](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/6b58d838-5952-4753-b124-f83f04b2856f)

Bug report code: ITFfzfHl7Yl1xOVc7pSILMFFliAQJnkcTZM3lOsYGBAaIoPkPIk1d8nEaXduXtTgfVdiAGKJkj0C+tbMuPPfO/YEPSeBG9x607tqcAH/TXGgb4y4PZeSYEdtP+5XJ0iO5MGvnApNKst1LEY+3HGPcq3qNleeY8aSfxBlZ7vfcPo=

Before the click:
![2](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/16e92d62-286e-4991-9b95-3f5ece41d094)

After the click:
![3](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/a15ad577-6076-4e3b-8184-8817df42dd10)

As you can see, all parameters got sent to Firestore **except docReference**, although the field does have value as shown in the first screenshot of this example!

Besides that, there's actually one more issue:
There are wrong listUnits values in the Firestore document ("Orange" should have listUnits values "medium" and "g", not "medium" and "each").

### Expected Behavior

Example 1:

To be able to select reference/document ID when using Data Types

Example 2:
1) docReference should appear in the Firestore document among the other parameters in the Data Type
2) listUnits (list of strings) should display the correct values in the Firestore doc (as explained earlier)

### Steps to Reproduce

Example 1:

LINK TO PROJECT: https://app.flutterflow.io/project/test-467wm7 

1) In Cloud Firestore, create a new collection. Then, create a few documents with similar (or random) fields and values as below.
![Screenshot 2024-01-10 at 22 59 30 (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/9e6777e3-9ca5-4f09-866c-5f220e3f2e55)

2) In Flutterflow, go to Firestore settings and set up the schema. "Add new collection" -> collection name as in Firestore -> set up the schema

3) In Flutterflow, go to Data Types. "Add new data type" -> create the schema, make sure to create a Doc Reference to the newly created collection (image below)
![Screenshot 2024-01-10 at 23 06 29 (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/5180c7b5-1731-45ba-9ddc-17bb15958e0c)

4) In Flutterflow, go to App values. "Add app state variable" -> add a random name, select "Data Type" as the data type, and switch on "is list" and "persisted"
![Screenshot 2024-01-10 at 23 11 59 (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/25ceb593-1df4-4f8b-94f3-bd5278daffdc)

5) In Flutterflow, create a new blank page. Add a new component "CheckboxListTile". 

6) Select the component "ChecboxListTile" and add a backend query. Add Query -> Query Collection -> collection = the collection that was created in step 1 -> select Single Document - > Click confirm

7) Lastly, while the "CheckboxListTile" component is still selected, go to Actions. "Add conditional action" -> single condition -> **First Value = the newly created App State** -> from the dropdown menu, select "List contains item" -> select Document -> select Reference ------> as you can now see, Document ID can not be selected.
![Screenshot 2024-01-10 at 23 32 58 (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/606b3547-9d38-4cbc-b82c-677104444203)

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzfHl7Yl1xOVc7pSILMFFliAQJnkcTeUzlO1hdwwbI+OsEYkDdc/eXxFWYuqHem9IGmGknkIB+aCMv/HfL+4DAz+BRt0/+pZbUxDhRlmtWqWYC5CoVkd9P8dgN26z0JmNkSYnIvd2R1IdwDiQJe+Aa3qCf9qOYwx5e6fDbOY=

### Context

Example 1: Trying to make sure that when the selected item already exists in an app state list, then it wouldn't be allowed to be added again as it already exists. 
Example 2: Trying to add default values to a list (from app state) after the user has removed them. 

### Visual documentation

![1](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/680d7492-fd0e-4c5c-955e-38b8d4c55bef)
![2 copy](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/b23045c7-5e2f-492b-9ed5-f4976ec7fc02)
![3 copy](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/17c48e5e-3589-4bae-9178-ae0a779948f1)
![4](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/7e9ad6d8-564e-48d5-ae4a-f5d8b1b56bab)
![3](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/706b2874-185b-46ab-821b-1c358c0bb942)
![appstate](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/86778fec-3cf5-4d9d-98bd-c9a2d47d3620)

### Environment

```markdown
- FlutterFlow version: v4.0 released November 4, 2023
- Platform: Web, MacOS
- Browser name and version: Chrome 118
- Operating system and version affected: OS X 10.15.7
```

**Comment by bkannes** [comment]
Hi, any updates on this?

**Comment by aemelyanovff** [comment]
@bkannes Thanks for reporting the issue. I'm having hard time reproducing it - when I follow the steps to reproduce, I end up with the same thing as on your first screenshot ![1](https://github.com/FlutterFlow/flutterflow-issues/assets/79152008/680d7492-fd0e-4c5c-955e-38b8d4c55bef)

But I don't see what's the problem with it - I don't see `Available options "Document ID" in red/can't be used` error here. Can you update Steps to Reproduce to include steps to reach that error?

**Comment by bkannes** [comment]
Use "listGroceriesFruitVegDATATYPE" as an app state instead of "listGroceriesFruitsVegetables".

The difference between the two is that "listGroceriesFruitVegDATATYPE" is a list of Data Types (that doesn't work) and "listGroceriesFruitsVegetables" is a list of document references (that works).

**Comment by aemelyanovff** [comment]
> Use "listGroceriesFruitVegDATATYPE" as an app state instead of "listGroceriesFruitsVegetables".
> 
> The difference between the two is that "listGroceriesFruitVegDATATYPE" is a list of Data Types (that doesn't work) and "listGroceriesFruitsVegetables" is a list of document references (that works).

Sorry I'm having hard time following. Could you update the "Steps to Reproduce" section? Currently, when I follow it, it doesn't produce any errors. The steps must start from a blank project, including creating all necessary data types and collections. And it would be very helpful if you reproduced the issue in a blank project and shared a link to it.

**Comment by bkannes** [comment]
Updated and added a link to the project. From there, you can start from the last (7th) step. Let me know if anything is still unclear on my side.

**Comment by aemelyanovff** [comment]
@bkannes Thanks for the updated steps to reproduce. It's a lot clearer now.

In this example, `newTestAppState` is a `List<TestDataType>`. So the second value for "contains item" must be a `TestDataType`. You cannot use `Document->Reference->Document ID` because it's a `String`, so a `List<TestDataType>` cannot possibly contain this value.

If I understand your use case correctly, you need a custom function like this:
![Screenshot 2024-01-11 at 10 55 50 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/86af0426-ba69-4ead-b774-ee28ab937156)

**Comment by bkannes** [comment]
From what I understand, you recommend creating a condition where "newTestAppState contains item newTestAppState".  But this is not the condition I need for my use case. Simply put, the condition should be the following:

"Check if the selected item (the action trigger is "on toggled on") already exists in the newTestAppState which is a List<TestDataType>"

If the item already exists, I would not add the same item again but instead, recalculate another parameter called Amount. Let's say you have a grocery list of items, you would not want to have "2 apples" and "3 apples" appearing on separate lines - instead, it should be "5 apples" in one row for a better UX.  

Are there currently any other possible solutions to this? Storing in Firestore (may get too expensive?), json, etc.?

I also find it interesting that I can retrieve the Document ID if it is stored in a list of Document References but not from a list of Data Types. 

I created a sample condition on the same ChecboxListTile component, feel free to take a look! The first value is testAppStateDocRef (list of Document References), then "contains item", and the second value is Document -> Reference. Is there a logical reason why it works in a list of Document References but not in a list of Data Types?

**Comment by aemelyanovff** [comment]
@bkannes

> I created a sample condition on the same ChecboxListTile component, feel free to take a look! The first value is testAppStateDocRef (list of Document References), then "contains item", and the second value is Document -> Reference. Is there a logical reason why it works in a list of Document References but not in a list of Data Types?

The list and the item in "contains item" conditions must have the same type. That's why you can check that a list of references contains a reference, but can't check that a list of data types contains a reference.

If you need further assistance, I suggest reaching out to FlutterFlow Support and/or asking https://community.flutterflow.io/. This issue tracker is only for bug reports, and I don't think it's a bug. 

My apologies for the slow turnaround.
