### ISSUE TITLE
Unable to launch Scan QR code action

### ISSUE THREAD

**Issue by orchard800** [FlutterFlow/flutterflow-issues#179]
I cannot get any widget to launch the scan QR code action. 

Trying on FF Preview android app and web and following the documentation to the letter:
https://docs.flutterflow.io/actions/actions/ui-interactions/scan-barcode-qr-code

I read elsewhere that some people had issues a few months ago but that it should be fixed now.

Could you help me please? My app completely depends on reading QR codes so this is a big wall we've hit.

Thanks.

**Comment by orchard800** [comment]
Also, the project is: Stampcard
And the bug report code is: IT4ghc/1z4tPtbxa7aXycu9ahjgvG0AhU5c0st5Hd0gdCOPrBqQPP+P4bRdoXu7iaVNcA2H+kmoyp8GLkfzPD/U6GwqqQN1qwaVQdQHQKTbkEuzyT+3IHDUHZbsSXTTm

**Comment by wenkaifan0720** [comment]
Hi @orchard800 . Could you try on a real device or an emulator? The FF Preview app is still running the app in preview mode and certain functionalities are limited (it is more for previewing the UI). And on web the QR scanning is not supported yet.

**Comment by wenkaifan0720** [comment]
I'll close this issue due to inactivity.
