### ISSUE TITLE
GoogleMap document markers don't compile

### ISSUE THREAD

**Issue by nurzhands** [FlutterFlow/flutterflow-issues#1790]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently adding GoogleMap with latlng markers works fine.
But setting marker type to Document doesn't show any errors but fails to compile/download code.

### Expected Behavior

To be able to download/run the app

### Steps to Reproduce

1. Create empty project
2. Add GoogleMap following projects
3. Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

I'm trying to add list of document markers onto GoogleMap

### Visual documentation

.

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
Can you please share a bug report code, so i could take a look into this issue?

**Comment by SameerShahzad99** [comment]
Closing this ticket due to no response from the user
