### ISSUE TITLE
Stacked chats notifications are not cleared after opening chat thread.

### ISSUE THREAD

**Issue by elementh69** [FlutterFlow/flutterflow-issues#1792]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. User A sends 5 messages to User B using FlutterFlow's chat.
2. User B receives 5 push notifications on their device.
3. User B clicks on one of these notifications, resulting in the opening of the chat thread.
4. After clicking on the notification, the clicked notification disappears as expected.
5. However, the remaining unclicked notifications continue to display, which is not as expected.

### Expected Behavior

I expect that clicking on one of the notifications related to the same thread will open the thread and clear all notifications associated with it.

### Steps to Reproduce

1. start blank project
2. add flutterflow's chat
3. repeat steps from "current behavior" description

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMrqy4xOj7xY17X5bcZWhiA7H181TL07pu5uZ0gsCJzwBIh/duDCQE9DTe7hY1NhHFm0nlsBzNLqkd/tVO0pBxSdfYhq+LhudQzdWXq8Ra7WDqWKRXAkGftRFWKl4bujnhVQGONocmQQ2zmuediyVhLqCZ+/Zwh9f6PHaOI=

### Context

Clear notifications

### Visual documentation

no attachement needed

### Environment

```markdown
- FlutterFlow version: newest today
- Platform: MacOS
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by SameerShahzad99** [comment]
Hi @elementh69, considering this as a feature request, as this should be specific to the chat implementation
