### ISSUE TITLE
Push notifications not parsed for DocumentReference

### ISSUE THREAD

**Issue by nick-chargely** [FlutterFlow/flutterflow-issues#1794]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When sending a push notification which holds a document reference as a string push notifications is trying to parse the object rather than using the string. 

For example something that should resolve to 
/initialPage/unique-document-id-from-firebase

ir it trying to resolve the object
/initialPage/[DocumentReference] 

### Expected Behavior

One of two things:
- Logic for handling document reference: When a document is cast 'as Document Reference' it should instead parse from string. 
- Probably easier: update push notification handler to instead of use DocumentReference just use a string. and require the page to have path in routing as 'page/:documentId' so firebase library parses it into a document reference properly

### Steps to Reproduce

1. Create a new page
2. Set a document reference in page parameter required
3. Send a push notification to the device with page parameters for the reference and id 
4. Notice that the device goes to root because it fails to parse the document id

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr1z4Z2xNtD0a6Jbe9alSQWMjsmULgZl+4acCs8GZT0B4kcYs+kfklUcO3gTXx6O1n8rGYX/Mrzi9/qUfkCFEirRt1iyKp9EjrzQmSXRK6JEL63b0ZQBd1hI3KH4LeFmyJ5BMViLloS72CIHe+/d3bZGZu2NTJEMeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I have setup a chat page and a cloud function trigger which sends out push notifications to users who are subscribed. I noticed I needed to update the push notification handler with the following code:

`'stationChatPage': (data) async {
    final allParams = {
      'commsRef': getParameter<String>(data, 'commsRef'),
    };
    return ParameterData(
      requiredParams: {
        'commsRef': serializeParam(
          allParams['commsRef'],
          ParamType.String,
        ),
      },
      allParams: allParams,
    );
  },`

Before the update, FF had it setup as, it was

`'stationChatPage': (data) async {
    final allParams = {
      'commsRef': getParameter<DocumentReference>(data, 'commsRef'),
    };
    return ParameterData(
      requiredParams: {
        'commsRef': serializeParam(
          allParams['commsRef'],
          ParamType.DocumentReference,
        ),
      },
      allParams: allParams,
    );
  },`

### Visual documentation

None

### Additional Info

Two things:
1. FF lets you set DocumentReference for push notifications but seems to fail - im assuming it is failing to parse here when sending the request and hiding error
2. When I create an object with DocumentReference and try to parse from a string it is also failing as it is casting to document reference. This should always allow parsing from a string and creating the document reference 

### Environment

```markdown
- FlutterFlow version: new
- Platform: all
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!
