### ISSUE TITLE
App NEVER run in "Test Mode"

### ISSUE THREAD

**Issue by dmslabsbr** [FlutterFlow/flutterflow-issues#1795]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After several attempts, I discovered that the app operates as expected when I switch to the "**RUN MODE**". However, it still refuses to work in "**Test Mode**".

It's really difficult to progress without Instant Loading in Test mode. I am currently completely unable to use it.

 I've tried on different computers and encountered the same issue across all of them.

I'm currently using **FlutterFlow 4.0** and **Flutter 3.13.7**. Notably, there's no error indicated by these versions.

![](https://user-images.githubusercontent.com/3632067/279503068-b3a1f80b-97b1-45f0-9133-32b7ce993347.PNG)

In "Test Mode", the loading bar keeps spinning indefinitely.

![](https://tribe-s3-production.imgix.net/yl86sGgdKnrtZJtfg2w7H?auto=compress,format&dl)

I shared the app to other flutterflow users who cloned the app and it still didn't work in test mode.

I tested it on other browsers and it didn't work either.

I've captured the following error from the browser's debug console:

![](https://user-images.githubusercontent.com/3632067/279503928-0942a43d-707f-44e7-b6b4-5bba0712dc67.PNG)

As suggested, I downloaded the code and checked my computer to see if there were any errors in the dependencies.

I ran the command: `flutter pub get --no-example`

Apparently no errors.

![](https://user-images.githubusercontent.com/3632067/279507124-6560a6f2-ccec-42d9-9b6b-12296eb4730f.PNG)

Here's the code of the function that's displayed on the screen when this issue occurs:

```
// Automatic FlutterFlow imports
import '/backend/schema/structs/index.dart';
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!
import 'package:supabase_flutter/supabase_flutter.dart';
/**
  renomear o nome de um arquivo no supabase storage
 */
Future<bool> trocaNomeArquivoSupabase(
    String nome, String novoNome, String bucketName) async {
  print("Action: trocaNomeArquivoSupabase 6");
  bool ret = false;
  try {
    final supabase = Supabase.instance.client;
    final storage = supabase.storage;
    print("Nome: " + nome + " para: " + novoNome);
    //final Future<String> result = storage.from(bucketName).move(nome, novoNome);
    final String result = await storage.from(bucketName).move(nome, novoNome);
    print("result: " + result.toString());
    ret = true;
  } catch (e) {
    print('Erro ao renomear arquivo: $e');
  }
  return ret;
}
```

I deleted custom code "trocaNomeArquivoSupabase" and it still not work.  Now, a new error appears.

```
dart_sdk.js:52 Uncaught TypeError: Cannot read properties of undefined (reading 'Symbol(_privateNames)')
    at dart.privateName (dart_sdk.js:52:24)
    at load__packages__promotorias__flutter_flow__nav__serialization_util_dart (lista_buckets_supabase.dart:36:1)
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at callGetModule (require.js:1203:63)
    at Object.completeLoad (require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (require.js:1717:29)
```

Any insights or suggestions to troubleshoot and resolve this problem would be highly appreciated.

Thanks in advance!

Daniel

### Expected Behavior

It should run. Like in "RUN MODE" or after publishing.

### Steps to Reproduce

1. Open the app (https://app.flutterflow.io/project/promo-share-88lh3r )
2. 
3. Click "test Mode" button to start.
![testMode1](https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/43315c13-c567-4231-98d7-b921941725ea)

4. The "Test Mode" never finish and app never run.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMjfsItOj7xK1br+YPlR/GQ6NnIgROY0scp/bxIgGIDzPOw+ZPXsQxNCOP2jSghUPkSmmng1wtLMuOOeUsEBCzCtR7o7ys1MbAHdRnKle5OBCJOCVWtQEflUfUiv58K4nh1/IbNvV3A12WCQGefKYBLbQZv4ImdISq/LZO4=

### Context

I recently upgraded my plan to be able to use the "test mode" for longer. I never managed to take advantage of this greater time.

It is a big problem for me – I can't test and iterate quickly.

### Visual documentation

[Dashboard---FlutterFlow1.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/92f6580f-3475-40f9-b979-40aa5a6eb2ad)

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/d3c978b5-d73f-44f2-86f0-0efcd2cff5c1

### Environment

```markdown
- FlutterFlow version: 4.0
- Flutter 3.13.7
- Platform: Web
- Browser name and version: Chrome  117.0.5938.134
- Operating system and version affected: Windows 10
```

**Comment by treirouxel88** [comment]
I have the same problem here, i created a blank projet to test it, here a screen shot of the screen i'm stuck on :
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/2eb66f53-c3d5-4c5e-88ea-19511e058648)

the error displayed in console here :
`
dart_sdk.js:5415  Uncaught (in promise) Error: FormatException: SyntaxError: Unexpected end of JSON input
    

    at Object.createErrorWithStack (dart_sdk.js:5415:12)
    at Error._throw (dart_sdk.js:8564:18)
    at Error.throwWithStackTrace (dart_sdk.js:8561:18)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:40357:18)
    at Object._microtaskLoop (dart_sdk.js:40214:13)
    at _startMicrotaskLoop (dart_sdk.js:40220:13)
    at dart_sdk.js:35968:9
`

**Comment by sabatage3** [comment]
i'm having the same issue, test mode is not working :(

**Comment by dmslabsbr** [comment]
Hi, @hariprasadms ,
Hi, @aemelyanovff ,

Is there anything new? I keep having the same problem.

**Comment by aemelyanovff** [comment]
This will be fixed in the next update.

**Comment by juandps** [comment]
I'm having the same problem again.

Any news about this ?

**Comment by Saaamir** [comment]
I have the same Issue after working with XML. I removed everything that could be related to XML and also tried reverting to old versions. I am now stuck in the loading screen everytime.

What can I do?

**Comment by RouryR** [comment]
Hi, @hariprasadms ,
Hi, @aemelyanovff ,

Is there anything new? I keep having the same problem.

I restored to an older version where it was working, but it hasn't been resolved. If I run the project in Run mode, everything works fine, and when I install the APK, everything also works.

However, Test Mode does not work for me

![Screenshot_8](https://github.com/user-attachments/assets/6bf3d81c-d0fc-4686-8f46-72c8f29262f0)

**Comment by finallyfit** [comment]
Commenting here to mention that I'm experiencing the same error.

**Comment by Saaamir** [comment]
@RouryR try removing "play sound" actions. It said "just_audio" in my console error too and after that it was working again.
