### ISSUE TITLE
Using the id JWT value to be validated in backend results in invalid signature

### ISSUE THREAD

**Issue by rogerthedeveloper** [FlutterFlow/flutterflow-issues#1796]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

using a custom JWT from backend for login ,and works perfect for login in flutter flow.
token = this.appService.signToken({
        uid: i.user.uid,
        aud: "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
        iss: "firebase-adminsdk-uefwx@yego-app-2793d.iam.gserviceaccount.com",
        sub: "firebase-adminsdk-uefwx@yego-app-2793d.iam.gserviceaccount.com",
      });
     
 now getting the id JWT value from flutter flow to request the backend and get
JsonWebTokenError: invalid signature in backend

### Expected Behavior

using id JWT value of current user logged by custom JWT, to result in success validation in back for request

### Steps to Reproduce

the id jwt token value like this should be able to use in backend to request with the same key to get signature verified.

{
  "iss": "https://securetoken.google.com/app-123",
  "aud": "app-123",
  "auth_time": 1699311639,
  "user_id": "USERUSERID1234",
  "sub": "USERUSERID1234",
  "iat": 1699311639,
  "exp": 1699315239,
  "email": "email@email.com",
  "email_verified": false,
  "firebase": {
    "identities": {
      "email": [
        "email@email.com"
      ]
    },
    "sign_in_provider": "custom"
  }
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WiOflsYt1j7xY17X5bcdKhjgXH0QiU403mMN9RUogNbbqPaYPQfvRUBZoTLy9SlFEJ2aghmEJ7PfqvvHPKvUpITatQLY7/qp2Ug//XnmiR6XTDZO3fW1QBdtWGBGFy8ORngpdCOtfR1Zl1Ez3fumvXgzYNJj7OjIjGPm1LdeK2SrDX1iXc2URm05KZDPz

### Context

after success login I want to use the JWT id value to use it around the entire app for make requests to my backend with security and clean use of the id JWT value feature of flutter flow

### Visual documentation

Wanted to use this value in the whole app to make backend requests after succes login with custom token jwt:
![imagen](https://github.com/FlutterFlow/flutterflow-issues/assets/9954853/f5b604e6-6668-4f29-9aa6-1b8fcd704b4d)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rogerthedeveloper** [comment]
this is the solution to use the id JWT token that FF brings for your custom backend
https://firebase.google.com/docs/auth/admin/verify-id-tokens

**Comment by takashiff** [comment]
Hello, thank you for your bug report. I am going to mark this issue as resolved for now, as it looks like the above reply from @rogerthedeveloper may have solved your issue. If this issue still persists, please feel free to reply in this thread so that it can be reopened. Thank you for your patience.
