### ISSUE TITLE
Using path_provider package generates error. Cannot add pubspec dependency as this is pre-loaded by FlutterFlow

### ISSUE THREAD

**Issue by steverist1** [FlutterFlow/flutterflow-issues#1798]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I invoke getTemporaryDirectory() from the path_provider package in a Custom Action, I always get an error: MissingPluginException

### Expected Behavior

the path to the Temporary Directory is retuned an no exception is raised. 

### Steps to Reproduce

1. Create new Custom Action
2. // Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:convert';
import 'dart:io';
import 'package:path_provider/path_provider.dart';

Future<String> newCustomAction(String str1, String str2) async {
  // concatenate two strings
  try {
    final directory = await getTemporaryDirectory();
    final filePath = '${directory.path}/temp.pdf';
    return filePath;
  } catch (e) {
    return 'Error= ' + e.toString();
  }
  return str1 + str2;
}

Invoke from a Button. Error is raised.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESl8j15c9gotsG0brQdPlQhQAkH1x/bZJEl9cbeEogGJfmE7QcOur+VGFuXOmzf2NEeFD+uH0xp9qKuM7LFPJfHwuBQoNozZdibgmUZFKgMsWLEauORHxDL/pnJlzHyqez2hF7NvZYV1IQw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to write a Base64 stream to a temporary PDF file for viewing in the PDF viewer.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126586372/d21d40db-47d8-48ea-976e-fa105b2a0f47)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126586372/4a807ec5-8940-458e-aec7-73f7491f4041)

### Additional Info

N/A

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected:  Windows 10
```

**Comment by hariprasadms** [comment]
Hi @steverist1 - Thanks for submitting the issue. The error you are expected while running build in web, debug and run mode of FlutterFlow. The reason is [path_provider](https://pub.dev/packages/path_provider) package works only in native platforms not in web platforms. 

<img width="669" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/5e1e991b-e679-4958-8119-b1c21418a86a">

**Comment by steverist1** [comment]
Ok – this is confusing: how do I test in Windows then?

***@***.***

**Comment by hariprasadms** [comment]
Hi @steverist1 - What you mean by windows? You mean you are accessing [https://flutterflow.io/](https://flutterflow.io/) in a browser in a windows PC ? how did you run this custom code ?
