### ISSUE TITLE
Unable to add/wrap/duplicate/cut/paste widgets in ConditionalBuilder Widget within a Page View Widget

### ISSUE THREAD

**Issue by ToddHerron** [FlutterFlow/flutterflow-issues#1799]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a ConditionalBuilder Widget is on the second page (index page 1) of a Page View Widget

Error 1. the ELSE clause of the ConditionalBuilder won't allow adding of Widgets (nothing happens). 
Error 2. the Duplicate Widget  (⌘+D) functionality doesn't work in the main IF clause (nothing happens).
Error 3. the COPY Widget  (⌘+C) and Paste Widget  (⌘+D) functionality doesn't work to copy widgets from the main IF clause to the ELSE clause
Error 4. when you try to wrap a widget with a Column Widget in the main IF clause, the widget is deleted from the widget tree

### Expected Behavior

Error 1. Widgets should be added to the widget tree when selected from the widget palette
Error 2.  FF should provide the Replace Child Widget dialog.
![Screenshot 2023-11-07 at 07 28 58](https://github.com/FlutterFlow/flutterflow-issues/assets/2007969/f6fc6297-a8a0-4db1-82ee-63b810484dc3)
Error 3. Copying and pasting from one Conditional Builder IF/ELSE clause should work.
Error 4. The widget should be wrapped with desired widget, and should not be deleted.

### Steps to Reproduce

1. Create a page
2. Add a Page View Widget
3. Go to page 2 (index 1) of the Page View Widget
4. Delete the default Image Widget
5. Add a Column Widget
6. Add a ConditionalBuilder
7. Click on the 
8. In the IF clause, add a Container Widget
9. In the Container Widget, add an Image Widget

Error 1. Click on the palette beside ELSE clause and try to add a Container Widget
Error 2. Click on the Container Widget in the IF clause and press Duplicate Widget (⌘+D)
Error 3.  Use COPY Widget  (⌘+C) and Paste Widget  (⌘+D) to try to copy the Container Widget in the IF clause to the ELSE clause
Error 4. Left click on the Container Widget in the IF clause and then select Wrap Widget and then Column.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oksn6389IsdtJ+KriasExryQsH1whaqxM0sEaaEgYB4vNG4gIZfTBXE9uOP25dkFUMGKgnnoe+vDRm9z1G/AnEz6rfYBH1LhuVBXvZDuuRZvQCrqCYXF+GshUBUyH4aWrsRB7ANpZWiU11zmMFuutUirXGZv6O2w7R/H/BJDXmAfuQ0SLb3kNh1JWeC/v

### Context

I am building a Wizard using a Page View to walk my users through creating a record. On the second page of the Wizard, I ask them to upload an image. I use the ConditionalBuilder to see if a local copy of the image has already been uploaded (in case they had been going back and forth through the Wizard pages). 

Since ConditionalBuilder isn't working, I'll have to use Conditional visibility.

### Visual documentation

I am building a Wizard using a Page View to walk my users through creating a record. On the second page, I ask them to upload an image. I use the Conditional Builder to see if a local copy of the image has already been uploaded (in case they go back and forth through the Wizard pages). 

Since ConditionalBuilder isn't working, I'll have to use Conditional visibility.

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2007969/50df1a6b-cad9-4690-b4be-37801f7acee4)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mac
- Browser name and version: Chrome Version 118.0.5993.117 (Official Build) (x86_64)
- Operating system and version affected: Sonoma 14.1
```

**Comment by kiwimagic** [comment]
Just read this issue post and wanted to flag it may have the same underlaying cause as the bug  #[1788](https://github.com/FlutterFlow/flutterflow-issues/issues/1788) As part of that issue I also had problems sporadically accessing widgets to add within PageViews > page 1

**Comment by victoriahuang1** [comment]
Hi @ToddHerron thanks for the report. I have found and addressed an issue on our end. This should be fixed once it is deployed.
