### ISSUE TITLE
WebView on Android devices laggy when scrollng

### ISSUE THREAD

**Issue by kotdeveloper123z** [FlutterFlow/flutterflow-issues#180]
## Expected behavior (required)
I expected to experience a smooth scroll when adding my site to the Webview widget.

## Current behavior (required)
The scroll causes a lag and a blurring effect.

## To Reproduce (required)

1. Create new page
2. Add webview widget
3. Add url specifically a page which has a scrollbar e.g. rosettaenglishtutoring.com/test-bot
5. You can type the response "youtube" into the above bot and a response will load.
6. To load up more responses, respond with 'yes'
7. Once you have loaded up a few responses, you can scroll but it is very laggy.

## Context (required)

I already have purchased an app from CodeCanyon which uses the flutterinappwebview library and the scroll is seamless. The problem with that app is that it doesn't have an In app purchases feature. I want to use Flutterflow because it has both a Webview feature and IAP feature; however I cannot use the Webview feature as of now because of the lag. If you can replace the current webview library with flutterinappwebview, then all will be fine. 

## Screenshots / recordings
https://drive.google.com/file/d/17HSERrrLMagEcKoayNPe4JPA1vxZ4uFT/view?usp=share_link

## Your environment
On Android devices

**Comment by aemelyanovff** [comment]
Thanks for the feedback.

The only thing we can do is switch to another WebView package - currently we use webviewx which hasn't been updated in 15 months.

I don't think this is a bug, though. We'll track this separately as a feature request.

**Comment by kotdeveloper123z** [comment]
Yes. I think you should replace it with Flutterinappwebview as it is
unusable at the moment.
