### ISSUE TITLE
Can't get date from firebase sub collection document

### ISSUE THREAD

**Issue by JustUserHere** [FlutterFlow/flutterflow-issues#1800]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

can't get date field from sub collection document on firebase, it is just not returning any information. Different DateTime format options not changing behaviour. Other field works well. 

### Expected Behavior

be able to get Date field from sub collection document Firebase

### Steps to Reproduce

Create collection
Create sub collection with date type field
Try to get date field from sub collection document

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsYt2m+FF7rruYO9WimU4HFAhaq00sNtuTQIdCYDuBIYiaePCUE1tYNe7T3x9KEWJrH0x//vFkYfDJsEqGwyafIhY/8xiFzzhZES/aoSPC5eSe0dABd5UI0CF35+s2CN7LtVYc1YN60+EJOeXFw/vQZ/7Zwh9f6PHaOI=

### Context

i'm trying to get sub collection doc creation date from date field

### Visual documentation

![bug](https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/800991d3-0136-4573-9525-1ebf236cfdd1)

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: mac or web
- Browser name and version: safari
- Operating system and version affected: any
```

**Comment by hariprasadms** [comment]
Hi @JustUserHere -  Thanks for submitting the issue with all the details. I have tested above steps. I can confirm that the date values from sub collection getting displayed as expected. 

How did you enter the date values to sub collection ? Please confirm these details.

**Comment by JustUserHere** [comment]
> Hi @JustUserHere - Thanks for submitting the issue with all the details. I have tested above steps. I can confirm that the date values from sub collection getting displayed as expected.
> 
> How did you enter the date values to sub collection ? Please confirm these details.

Hello @hariprasadms 
this is custom code with which one i'm adding doc to subcolletion:

// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/actions/actions.dart' as action_blocks;
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:cloud_firestore/cloud_firestore.dart';

Future newCommentAndRating(
  String userID,
  int userRating,
  String advID,
  String? userComment,
  String? userName,
) async {
  CollectionReference advDatabase =
      FirebaseFirestore.instance.collection('adv_database');
  DocumentReference ratingsRef =
      advDatabase.doc(advID).collection('AdvRatings').doc(userID);

  DateTime now = DateTime.now();

  ratingsRef.get().then((docSnapshot) {
    if (docSnapshot.exists) {
      ratingsRef.update({
        'UserID': userID,
        'UserName': userName,
        'UserComment': userComment,
        'UserRating': userRating,
        'Date': now.toUtc(),
      }).catchError((error) {
        // Handle the error here
        print("Error updating document: $error");
      });
    } else {
      ratingsRef.set({
        'UserID': userID,
        'UserName': userName,
        'UserComment': userComment,
        'UserRating': userRating,
        'Date': now.toUtc(),
      }).catchError((error) {
        // Handle the error here
        print("Error creating document: $error");
      });
    }
  }).catchError((error) {
    // Handle the error here
    print("Error getting document: $error");
  });
}

**Comment by victoriahuang1** [comment]
@JustUserHere it looks like you're querying for `date` (lowercase), but your custom code function is setting the value for `Date` (uppercase). Please match the cases and let us know if this is resolved for you.

**Comment by JustUserHere** [comment]
> @JustUserHere it looks like you're querying for `date` (lowercase), but your custom code function is setting the value for `Date` (uppercase). Please match the cases and let us know if this is resolved for you.

Hello!
in FF  no option to change querying 'date' to upper case. It is not a filed where i can entry anything, I can only choose one of the doc properties.

**Comment by victoriahuang1** [comment]
@JustUserHere you will need to change your firestore schema to uppercase

**Comment by JustUserHere** [comment]
> @JustUserHere you will need to change your firestore schema to uppercase

This doesn't help. Same issue. In firestore schema it is in upper case now and i have same issue.

**Comment by victoriahuang1** [comment]
@JustUserHere can you check the data in your firestore db?

Also as @hariprasadms mentioned, this is not reproducible. And this project is too large and complex to debug. For further debugging, please reproduce this issue in a simple project from scratch and provide the new bug report code

**Comment by JustUserHere** [comment]
> @JustUserHere can you check the data in your firestore db?
> 
> Also as @hariprasadms mentioned, this is not reproducible. And this project is too large and complex to debug. For further debugging, please reproduce this issue in a simple project from scratch and provide the new bug report code

Hello,

It appears that merely adjusting this in the Firebase schema is insufficient without a corresponding rewrite of the documents. After implementing these changes -> delete all docs from subcollection-> write them back = works well now.

Thank you very much for your assistance and support in this matter.
