### ISSUE TITLE
iOS Builds Failing after 3.13 upgrade. 

### ISSUE THREAD

**Issue by scottefein** [FlutterFlow/flutterflow-issues#1802]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to build, this is the error. 

== Building for iOS ==
> xcode-project use-profiles
Configure code signing settings
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.mobileprovision
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.provisionprofile
List available code signing certificates in keychain /Users/builder/Library/codemagic-cli-tools/keychains/06-11-23_yuyekwf_.keychain-db
Searching for files matching /Users/builder/clone/ios/**/*.xcodeproj
Completed configuring code signing settings
- Using profile "ImageNotification ios_app_store 1693356669" [7ae290fa-f0b3-403c-ae81-e492391c4cc0] for target "ImageNotification" [Debug] from project "Runner"
- Using profile "ImageNotification ios_app_store 1693356669" [7ae290fa-f0b3-403c-ae81-e492391c4cc0] for target "ImageNotification" [Profile] from project "Runner"
- Using profile "ImageNotification ios_app_store 1693356669" [7ae290fa-f0b3-403c-ae81-e492391c4cc0] for target "ImageNotification" [Release] from project "Runner"
- Using profile "The Just Because App ios_app_store 1693356670" [88f50493-98ac-4cb3-ae5f-6763f7a019e2] for target "Runner" [Debug] from project "Runner"
- Using profile "The Just Because App ios_app_store 1693356670" [88f50493-98ac-4cb3-ae5f-6763f7a019e2] for target "Runner" [Profile] from project "Runner"
- Using profile "The Just Because App ios_app_store 1693356670" [88f50493-98ac-4cb3-ae5f-6763f7a019e2] for target "Runner" [Release] from project "Runner"
Generated options for exporting the project
- Method: app-store
- Provisioning Profiles:
- com.impromptupost.app.ImageNotification: ImageNotification ios_app_store 1693356669
- com.impromptupost.app: The Just Because App ios_app_store 1693356670
- Signing Certificate: Apple Distribution
- Signing Style: manual
- Team Id: 3W5PVN249K
Saved export options to /Users/builder/export_options.plist
> flutter build ipa --release --export-options-plist /Users/builder/export_options.plist --build-name=1.0.42 --build-number=42
Archiving com.impromptupost.app...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 3W5PVN249K
Running pod install... 330.1s
Running Xcode build...
Xcode archive done. 425.4s
Failed to build iOS app
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': CodeSign /Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app
○ That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/ImageNotification.appex' to '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/PlugIns/ImageNotification.appex'

### Expected Behavior

It should build the IPA file. 

### Steps to Reproduce

Run a build on any iOS project that uses 3.13. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

Flutter issue #135739 appears to be the issue. 

I went ahead and was able to change the project locally -this worked. Can we get that fixed upstream? buildPhases = (
3EA46EF11B42FC3BFF6A4BBC /* [CP] Check Pods Manifest.lock */,
9705A1C41CF9048500538489 /* Embed Frameworks */,
6430E641270005EF009BEAC7 /* Embed App Extensions */,
9740EEB61CF901F6004384FC /* Run Script */,
97C146EA1CF9000F007C117D /* Sources */,
97C146EB1CF9000F007C117D /* Frameworks */,
97C146EC1CF9000F007C117D /* Resources */,
3B06AD1E1E4923F5004D2608 /* Thin Binary */,
2838A0ADC44730F0A2303575 /* [CP] Embed Pods Frameworks */,
55067970987309DE09E9DE72 /* [CP] Copy Pods Resources */,
);

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: v4
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: N/A
```

**Comment by SameerShahzad99** [comment]
I tried downloading the code from the FlutterFlow latest version with Flutter 3.13.7, and it appears to be working fine on my end, this looks like a project-specific issue, please reach out to the support team at support@flutterflow.io or live chat.
