### ISSUE TITLE
JSONPath defaults to string value of "null" when expected value is nullable string

### ISSUE THREAD

**Issue by dryprogrammer** [FlutterFlow/flutterflow-issues#1804]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

JSONPath defaults to string value of "null" when expected value is nullable string.

I'm not sure if there are plans to add nullable types to DataType, but the current behavior is to default null to an empty string of "".

### Expected Behavior

Expected behavior is nullable string should not default to string value of "null" but real null.

### Steps to Reproduce

Example mock api: https://0eqg4.wiremockapi.cloud/json/1

Sample response with null value:
```
{
  "id": 1,
  "value": "things",
  "alwaysNull": null
}
```
Project to test this:
https://app.flutterflow.io/project/null-field-in-a-p-i-response-not-nullable-annooc

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITwkis/l8YxgoddA7qrAcu9VoCU5Jk87apZMksNxaxQafJjoPLAIY+HBM1RoSbSnSmx2OlqZgngKx6nXvtmSFMFdHC6KfaJhwqpiTzqVbGCsMM2aEZO7P0Z5BZ9FJXamy4mvsCMmOtRZSHwe2znzJ9++dA/qN5TjC3kaFMqjMqnPnXTjHnn3IRBW0QwNMVu6Ca8ydTigkZz96dQQi66lttQ9hThL0p/O3snpUA6PRUU=

### Context

This has caused many to test and retest assumed expected behavior of JSONPath and DataType for many days. This should be better documented, but I believe this is a bug.

### Visual documentation

Test results (click Go):
https://nullvalues.flutterflow.app/

![Screenshot from 2023-11-08 21-32-37](https://github.com/FlutterFlow/flutterflow-issues/assets/40515415/087bbbda-1b99-4fe8-adb7-d16bcccc5b64)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.88
- Operating system and version affected: Ubuntu 22.04.3 LTS
```

**Comment by dryprogrammer** [comment]
This issue is still ongoing
https://community.flutterflow.io/discussions/post/don-t-use-jsonpath-use-datatype-instead-but-even-then-with-caution-V5WneK4io4awRiN

**Comment by takashiff** [comment]
Hi @dryprogrammer, I apologize for the delayed response. Currently, FlutterFlow does not accept null values for an API request/response. I've put in a feature request internally, as I do believe that this should be addressed. Thanks

**Comment by Night-coyote** [comment]
I can't apply filter condition, because this issue
