### ISSUE TITLE
Project endlessly loading and not opening

### ISSUE THREAD

**Issue by tshepolondo** [FlutterFlow/flutterflow-issues#1806]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project keeps loading or diplsaying the flutterflow loading icon for hours and not opening. 

project link is [here](https://app.flutterflow.io/project/twiqleweb-35mjuo)

### Expected Behavior

It should open and display the entry page of the application to edit.

### Steps to Reproduce

Open the project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Cant select widget

### Context

Was opening the project after exiting another

### Visual documentation

![Screenshot 2023-11-08 184409](https://github.com/FlutterFlow/flutterflow-issues/assets/101550402/3fe02995-3caa-492e-b556-72c15d4b906c)

### Environment

```markdown
- FlutterFlow version: Dont'know(can't open project to see details
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi - Thanks for submitting the issue. Please add project bug report code. This information is needed to get access to your project and start investigating the issue. Thanks

**Comment by tshepolondo** [comment]
I cannot open the project at all and therefore I cannot get the bug report code because I can't get to any widget in the project. When I click to open the project, that is when I get the endless loading.

**Comment by p1igus** [comment]
Me too. After authorization via google I have endless preloader with your logo. Tested on Safari and Chrome. Your app on Mac doesn't work also.

**Comment by martingazdik** [comment]
Me too. Exactly same situation as users above. Cant work in safari, chrome or ipad

**Comment by adriansegovia** [comment]
Hi, I am experiencing the same issue, it does not open the dashboard to view my projects, it keeps loading infinitely. I tried with Firefox, Chrome and Safari and with different internet connections.

**Comment by hariprasadms** [comment]
Hello @tshepolondo - Are you still experiencing the issue?. Please update the issue with project bug report code. 

@adriansegovia @laiquend-mg @p1igus - Please share bug report code of your projects. 

I need this detail to get access to your project.

**Comment by tshepolondo** [comment]
> Hello @tshepolondo - Are you still experiencing the issue?. Please update the issue with project bug report code.
> 
> @adriansegovia @laiquend-mg @p1igus - Please share bug report code of your projects.
> 
> I need this detail to get access to your project.

@hariprasadms Yes I am still experiencing the same issue. 
As I have said in the issue and the replies, I cannot get a bug report code as I cannot open the project at all. Please click the project link [here](https://app.flutterflow.io/project/twiqleweb-35mjuo) to see why I cannot access the bug report code. When you click to open, it starts loading and nothign else

**Comment by laiquend-mg** [comment]
> Hello @tshepolondo - Are you still experiencing the issue?. Please update the issue with project bug report code.
> 
> @adriansegovia @laiquend-mg @p1igus - Please share bug report code of your projects.
> 
> I need this detail to get access to your project.

for me its already working

**Comment by geraldmelendez** [comment]
Try removing your JSON paths in your elements "Backend Query" tab. This was stalling most of the edit panels and slowing down the ones that did work in my project.

**Comment by aemelyanovff** [comment]
Apologies for the late response.

@tshepolondo it looks like you are able to open the project now. If you are still experiencing this issue, please reach out to FlutterFlow support. This issue tracker is intended for issues with steps reproducible from a blank project.
