### ISSUE TITLE
API post call returns 503 error

### ISSUE THREAD

**Issue by filippobertossi** [FlutterFlow/flutterflow-issues#1807]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to integrate imageKit api in my app but the post call doesn't work. I tried the same api call from terminal and from postman and it works fine but when I try in flutterflow test api call page it returns null. If I do it on safari I get the popup XMLHttpError and when I try in testing from the console the api call fails with 503 error.

### Expected Behavior

The api call should works as with postman.

### Steps to Reproduce

1. Create a new project
2. create a post api call with url https://upload.imagekit.io/api/v1/files/upload
3. set the header as Authorization: Basic [apiKey] with your api call from your imageKit account
4. fill the body with a json with the fields "file" a url of a photo or video and "fileName" the name you want 
5. Run test

For more informations about the api of imageKit here is the specific documentation: https://docs.imagekit.io/api-reference/upload-file-api/server-side-file-upload

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lvHqx89NodhE7ZDUKflR/Ts5JkM7RpEV0utuTRM8KOPaPOw+Ps/BM0RCOerhd29bMU20hWoW08rwioTIG/AoBzmCfIRHyZNQWgnyIUC6V5SsFJWgQXZAI8BgfUOM0MKRhRJNOvtsR3gb3EOqNenIaCjAJKbGNTMaDq/LZO4=

### Context

I am trying to implement a simple post api call that works fine on postman as on terminal

### Visual documentation

<img width="1040" alt="Screenshot 2023-11-08 at 23 23 59" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126472122/c2b72093-d2f3-444f-bb23-c81fbdedc403">
<img width="1039" alt="Screenshot 2023-11-08 at 23 24 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126472122/979ee716-c2ca-4a84-afba-e30e57884c92">

### Environment

```markdown
- FlutterFlow version: v4.0.2
- Platform: any
- Browser name and version: any
- Operating system and version affected: macOS
```

**Comment by FilliTech** [comment]
Hi guys any news? @hariprasadms @aemelyanovff

**Comment by hariprasadms** [comment]
Hi @filippobertossi - Thanks for submitting the issue. Considering the nature of issue, I guess its more to do with configurations. I recommend first you reach to FF support team to get more help around it. If they confirm this is not working for any reason, you can come here to re-open the issue. 

I can confirm the Api post requests are working as expected. Thanks
