### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'x') main.dart.js

### ISSUE THREAD

**Issue by VittorioS** [FlutterFlow/flutterflow-issues#1808]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The published app throw the following error and show the blank screen:

main.dart.js:4098 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at amX.ZF (main.dart.js:75855:34)
    at amX.jw (main.dart.js:86930:5)
    at amX.a9U (main.dart.js:59720:3)
    at Object.aWl (main.dart.js:24360:3)
    at bd2.$0 (main.dart.js:111408:17)
    at main.dart.js:52276:33
    at bbj.a (main.dart.js:5458:62)
    at bbj.$2 (main.dart.js:46742:14)
    at Object.H (main.dart.js:5444:10)
    at bbx.$0 (main.dart.js:52281:10)

### Expected Behavior

The app works.

### Steps to Reproduce

1. Run the published app.
2. See the blank screen.
3. Open the browser console.
4. Search the error in the console.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slfLl8ZVNobRY17X6K+5R/WUUJjs4RLhNscpCbw4bIYj2P4lzY876PltVYO3iTFZIe022p14CwNaJifzlDPkqYEmuR7Zq/qVpWjziYHOubpOTF7uVOHd5EtxWIWK80J27hBRDCPN0WVIi3E77Nt6AdCzZNpjRDVQwSq/LZO4=

### Context

I am trying to use the app.

### Visual documentation

<img width="528" alt="Screenshot 2023-11-09 alle 11 39 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/18756482/8c7aa13d-945b-4bfc-ba71-6a29f3f94e28">

I attach also my main.dart because I see some differences with new blank projects generated.
<img width="591" alt="Screenshot 2023-11-09 alle 11 40 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/18756482/ffc237ca-ef18-4bba-a0b8-c3b0b32898b9">

### Additional Info

The project is about a year old.
The bug is not reproducible from blank project.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.132
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @VittorioS  What is the current status of the issue? Are you still encountering the problem? The error you're observing typically shouldn't cause any issues in the project. It's possible that your project has a different error. Please review and update the details accordingly. If issue not more exists, please close the issue. Thanks
