### ISSUE TITLE
Ability to control minSdkVersion of app

### ISSUE THREAD

**Issue by panantha** [FlutterFlow/flutterflow-issues#1809]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was able to export the apk on 09/11/2023 and I am not able to download it again yesterday there was no change made. Below are the errors.

When I google it, its recommended to update minSdkVersion 

Below are the errors.

Error: Command failed: flutter build apk --no-pub --no-version-check
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /tmp/ff_service_scratch/Dz2Dj8QUdLmd9gY3ZtdG/tacitous/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}

Note: /opt/.pub-cache/hosted/[pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java](http://pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java) uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/[pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java](http://pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java) uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/[pub.dev/firebase_messaging-14.6.2/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java](http://pub.dev/firebase_messaging-14.6.2/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java) uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/tmp/ff_service_scratch/Dz2Dj8QUdLmd9gY3ZtdG/tacitous/android/app/src/main/AndroidManifest.xml Error:
uses-sdk:minSdkVersion 21 cannot be smaller than version 22 declared in library [:fluttertoast] /tmp/ff_service_scratch/Dz2Dj8QUdLmd9gY3ZtdG/tacitous/build/fluttertoast/intermediates/merged_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 21
Suggestion: use a compatible library with a minSdk of at most 21,
or increase this project's minSdk version to at least 22,
or use tools:overrideLibrary="io.github.ponnamkarthik.toast.fluttertoast" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 22 declared in library [:fluttertoast] /tmp/ff_service_scratch/Dz2Dj8QUdLmd9gY3ZtdG/tacitous/build/fluttertoast/intermediates/merged_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 21
  Suggestion: use a compatible library with a minSdk of at most 21,
  or increase this project's minSdk version to at least 22,
  or use tools:overrideLibrary="io.github.ponnamkarthik.toast.fluttertoast" to force usage (may lead to runtime failures)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 54s
Gradle task assembleRelease failed with exit code 1

### Expected Behavior

It compiles and I can download the APK

### Steps to Reproduce

Just click Download APK.  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Llx49IsbQB14SJL/kw+SERQ20cTIMziNZ+exUbfaL1BuwUPsj7P1htXf3naVNfMFWZpDkHwPSMkfLDNMFdGzeWQLpFyKhQVDzOe2iVVa6LPairPHRPGdhPIWKA356NhiYkOvVeWCBm2mGHetmySjHDFOu/Zwh9f6PHaOI=

### Context

Cannot create a APK

### Visual documentation

![APKFailed](https://github.com/FlutterFlow/flutterflow-issues/assets/20857165/6ff4103c-5ad5-41e5-a872-ea61fc23bd2b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/20857165/eba7d1ef-6d9b-43c1-a7b7-efc033993d94)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by million-dollar-baby** [comment]
I am facing the same issue.

**Comment by panantha** [comment]
Its a backend config which is not exposed. I don't think we have control over that from inside Flutterflow, and if we export the code to change, then we cannot bring the project back, which defeats the object of paying for flutterflow.

**Comment by katherineqian** [comment]
Hi, it looks like this is happening due to an external dependency you're using that's now requiring a higher minSdkVersion than we have (`fluttertoast` in @panantha 's case). I will mark this as a feature request and prioritize this item. In the meantime, changing the minSdkVersion should be a quite minimal change. You can also use the GitHub feature to keep non-core code changes like this in your codebase, see https://docs.flutterflow.io/settings-and-integrations/integrations/github#how-to-make-local-changes-so-they-wont-be-overwritten-with-your-next-push-from-flutterflow

**Comment by jonny07** [comment]
I have the same problem. What do you mean with "In the meantime, changing the minSdkVersion should be a quite minimal change. ". Where can I change it in Flutterflow? I only found explanation that I need to export code (for which I need a higher paid version of flutterflow that I don't have). And even if I had, I would not be able to import the code back to flutterflow. Can you please explain what is the solution for this currently? Or is the only way: Use another tool to write my app?
