### ISSUE TITLE
AuthUserStreamWidget is a useless widget

### ISSUE THREAD

**Issue by siddharthadevops** [FlutterFlow/flutterflow-issues#181]
## Expected behavior (required)
When the authenticated user changes on FireBase, the child widget should rebuild. 

## Current behavior (required)
The child is not rebuilt.

## To Reproduce (required)
1.- Create a page that uses authenticated user.
2.- Refresh some field in User record.
3.- The page not show the new updates.

### Bug Report Code

Instead of user your widget like you are doing now:

 ```
@override
  Widget build(BuildContext context) {
    return AuthUserStreamWidget(
      child: StreamBuilder<List<LeccionesRecord>>(
        stream:  ...
```

Use the StreamBuilder:

```
  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: authenticatedUserStream,
      builder: (context, _) => StreamBuilder<List<LeccionesRecord>>(
        stream: ...

```

## Context (required)
A simple page that uses the authenticated user.

**Comment by agreaves** [comment]
Fixed on our next release! Done slightly differently from your suggestion, the `AuthUserStreamWidget` widget itself has been modified to take in a `builder` instead of simply a `child`. Thanks for the feedback!
