### ISSUE TITLE
Preview App does not respect current changes.

### ISSUE THREAD

**Issue by aunumever** [FlutterFlow/flutterflow-issues#1810]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Does not reflect current changes when clicking "Preview App" and deletes all changes made when coming out of "Preview App".

https://drive.google.com/file/d/1qmOGh835E2oJ0LMc_z5huoKBh2WPEFIV/view

### Expected Behavior

Clicking Preview App will show the current state of design and not lose any changes when exiting. 

It would also be nice to be placed back where you were working, instead of the the default Widget Palette as every time you preview,  you need to go dig into the component tree to find where you left off.

### Steps to Reproduce

[I submitted a video](https://drive.google.com/file/d/1qmOGh835E2oJ0LMc_z5huoKBh2WPEFIV/view)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whcj135VNoctD+KrQb/owuDwQIjs9aIEZkMJuESs8GZT0B4kcYs+kfklUOMOiS3N+f2Kggj8X/MqNjs7qV8E7FzGaGqZFypN6TT3KRlGRRa7RPL63b0FAJ59WBVSd0cCJrB55Iu9fLmQA13GqBuzIYADXJOfwNUQdP+a4XdeK2SrDX1iXc2URm05KZDPz

### Context

I've had to redo the design every time I preview, so now I'm extra cautious and it has put fear in me as a developer, especially not being able to control my own code through git.

### Visual documentation

https://drive.google.com/file/d/1qmOGh835E2oJ0LMc_z5huoKBh2WPEFIV/view

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: Mac and browser
- Browser name and version: Chrome - Version 119.0.6045.105 (Official Build) (arm64)
- Operating system and version affected: Mac Sonoma 14.0
```

**Comment by aunumever** [comment]
After the video cuts off, the "profile" page has disappeared, and my changes were lost.

**Comment by aunumever** [comment]
I noticed that when I clicked "Push to Repository" it would spin and do it's thing, then come back with a "Success" message. When checking my repo, no code changes were pushed. It was saying "Success" even though it was not a success.

So, I figured a restart might be a good idea. 

FF Froze on initial login (had to quit and reopen), but things seem to be working normally now.

**Comment by hariprasadms** [comment]
Hi @aunumever - Thanks for submitting the issue. I watched the video and followed the steps, but I couldn't reproduce the problem. 

Are you experiencing the same issue yet? 
What is the consistency of the issue?
When you navigate to the preview after changes, can you refresh the page and see if there are any changes ? Please update these details.
