### ISSUE TITLE
Unbounded Image Size Warning when uploading File(not Image)

### ISSUE THREAD

**Issue by vardarsezgin** [FlutterFlow/flutterflow-issues#1811]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I saw there is a new feature "Optimizations & Enhancements". 

But it gives size warning when uploading file(pdf, docs, other documents).

### Expected Behavior

no warning

### Steps to Reproduce

1. set action to upload file
2. select pdf or other document types
3. it gives warning

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozsiAz89gruFG1pDuKcJV/CQWNlN+bbs7kspOGDsdF4iuPOxzac6kdlpCTtfmY1FbKEWIrHgz+dLSjtjXD/EEKRyVbtlawc1MdwGURkK/aoS7CcyKdXd6Ee1UG0Cb07arnSUnPbJtLF4j606uCuetTj/UN734Zwh9f6PHaOI=

### Context

It does not give me a problem. I just wanted you to know.

### Visual documentation

![Ekran Resmi 2023-11-09 19 21 49](https://github.com/FlutterFlow/flutterflow-issues/assets/103498910/5c4ffea3-2400-49d8-a7b5-6e35058657cb)

### Environment

```markdown
- FlutterFlow version: 4
- Platform: MacOS
- Browser name and version: Chrome 119.0.6045.105
- Operating system and version affected: MacOS Sonoma 14
```

**Comment by agreaves** [comment]
Hi @vardarsezgin, thanks for the bug report! This should now be fixed!
