### ISSUE TITLE
API do not work in test mode

### ISSUE THREAD

**Issue by kanatbkeeep** [FlutterFlow/flutterflow-issues#1812]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

During calling any api get message
This API enables cross-origin requests to anywhere.

Usage:

/               Shows help
/iscorsneeded   This is the only resource on this host which is served without CORS headers.
/<url>          Create a request to <url>, and includes CORS headers in the response.

If the protocol is omitted, it defaults to http (https if port 443 is specified).

Cookies are disabled and stripped from requests.

Redirects are automatically followed. For debugging purposes, each followed redirect results
in the addition of a X-CORS-Redirect-n header, where n starts at 1. These headers are not
accessible by the XMLHttpRequest API.
After 5 redirects, redirects are not followed any more. The redirect response is sent back
to the browser, which can choose to follow the redirect (handled automatically by the browser).

The requested URL is available in the X-Request-URL response header.
The final URL, after following all redirects, is available in the X-Final-URL response header.

To prevent the use of the proxy for casual browsing, the API requires either the Origin
or the X-Requested-With header to be set. To avoid unnecessary preflight (OPTIONS) requests,
it's recommended to not manually set these headers in your code.

Demo          :   https://robwu.nl/cors-anywhere.html
Source code   :   https://github.com/Rob--W/cors-anywhere/
Documentation :   https://github.com/Rob--W/cors-anywhere/#documentation

### Expected Behavior

I expected to see a correct API rest

### Steps to Reproduce

1. Run test mode
2. Call rest

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gyfLlvYtNxLRE7qrcae9ajWUQNjI3a700sNobbxAjIoDoPJkUac+kN1VvTsjjTGNbKEWJpDgf063ViPLtU+wqBzuAfrpF+pNtVQzhVmq/aoSOC4eSPGt6DcFQI26938HUpRRdItpYR38u7XGQIuiXRT7ZJ4P4Zwh9f6PHaOI=

### Context

-

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/79863395/cf59a038-7f07-404d-8f47-b8a62b3cae20)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Test mode
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hi @kanatbkeeep, thank you for the bug report! I've indeed confirmed this issue and am deploying a fix as we speak! 🙂

Please do confirm whether it is indeed fixed, it will go live approximately 15 minutes from the time of this message.

**Comment by DigitalServitec** [comment]
I also have the same problem, APIS calls are not working

**Comment by agreaves** [comment]
@kanatbkeeep @DigitalServitec The fix has now gone live! Please let me know whether it is now working for you!

**Comment by kanatbkeeep** [comment]
@agreaves Thanks for the promptness, everything has been fixed!

**Comment by manshil-sum8-dev** [comment]
I'm still not able to hit any APIs successfully

**Comment by josepacheco22** [comment]
sigue igual, ayuda justo tengo una reunión para mostrar la app

**Comment by agreaves** [comment]
@manshil-sum8-dev @josepacheco22 You will need to re-deploy or restart Test mode for the fix to apply.

Please also send me a Bug Report Code for your projects so I can take a look.

**Comment by manshil-sum8-dev** [comment]
Hi @agreaves its working. Thank you

**Comment by josepacheco22** [comment]
si hay si, gracias salvaron mi vida

**Comment by fborgherodbsagency** [comment]
Same here, API CALL are not working anymore  if PROXY is enabled on the API  (returning 200 with empty response)

disabling in advanced settings on the api definition seems to solve

**Comment by AndresPaul** [comment]
Thanks for informing. You still have problems with proxy API calls. It is a critical problem. This error with the APIs appeared since the update, please review it.

**Comment by agreaves** [comment]
@fborgherodbsagency and @AndresPaul could you please add a Bug Report Code so I can see in details what is occurring? Any additional screenshots, screen recordings, or information would be helpful as well.

Also, please ensure you are on the latest version of FlutterFlow and have re-deployed / restarted test mode since after the fix was applied. Thanks!
