### ISSUE TITLE
Firestore Server Timestamp causes white screen when writing to fields in database

### ISSUE THREAD

**Issue by xenomorph78** [FlutterFlow/flutterflow-issues#1814]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Recently changed the chat timestamp to populate the Firestore Server timestamp. 
This causes the chat screen to go white before updating the screen for about 1 second.
When reverting back to GLOBAL>CURRENT TIME as the value, it does not display the white screen.
This also happens on the loading screen that writes the user's login time using the Firestore Server Timestamp.
The reason I'm going to the server timestamp is because a user can change their device time and date to manipulate the timestamp, causing issues with chat (loading out of order) and other time sensitive variables.

### Expected Behavior

Expect the stream of data to update without a white screen as it does with GLOBAL > CURRENT TIME.

### Steps to Reproduce

1. Create an action that writes to a date/time field that uses FIRESTORE SERVER TIMESTAMP
2. Run that action either on page load or from a button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhfHlzItOodtc0L6IKvp4imQ7KUMcTYARiO0bFB4dfIvkOpYids/SR0NKT8+CdH9tMVGZrzgypNKNjeHTUcI6FzaBc4hZ0JVAdxfjXlimRLKPBqiNP3NtEcdWJmmB0aWokwpTNfh1LSUM3GbyN63qNleeY8aSfxBlZ7vfcPo=

### Context

It does not look professional to have a white screen flash every time a document is updated with a timestamp.

### Visual documentation

Video showing the effects:
https://github.com/FlutterFlow/flutterflow-issues/assets/74033405/621989f4-e5e9-4e92-891c-64704f0ebd8f

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: iOS14
- Browser name and version: App and also in the FF test enviornment
- Operating system and version affected: All
```

**Comment by aemelyanovff** [comment]
@xenomorph78 Thanks for reporting the issue, and sorry for the slow turnaround.

I'm unable to reproduce the issue - setting fields from "Firestore Server Timestamp" works fine for me, without any white screens.

I'm closing the issue for now, but please reply if you update the steps to reproduce to be reproducible from a blank project. Alternatively, you can reach out to FlutterFlow support for further assistance.
