### ISSUE TITLE
API Groups no longer accessible

### ISSUE THREAD

**Issue by brian-tempo** [FlutterFlow/flutterflow-issues#1815]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When clicking on an API Group, I am unable to see the API group details including the base url, group headers, variables, etc. I have multiple API Groups in my app, and only the first one in the list makes the group settings available.

This issue appeared today, and unfortunately makes it impossible to work on the API calls the power my app. 

### Expected Behavior

When clicking on an API Group under the API Calls tabs, I should be able to see the API Group settings (name, base url, headers, variables, etc) and be able to change them.

### Steps to Reproduce

1. Visit the API Calls tab
2. Try and visit an API Group (I have multiple, and the issue is with one that is further down the list)
3. The details of the API Group are not shown and cannot be edited. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/HluIhOj70B1Zf+Y8BFhQMxGmY7UIIZjtdTawIYGJevEZofPur+VxFbXNOZeFZ6GFqZmkkDwPDehuztC8c4ZU2eeINoz7V2dDnLRTq5Mra3CLu7dnxPLJtUN2KP0KuvvSNDHMl2dUIdw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

This issue has blocked my progress on developing the API portion of my app, which is the foundation of its functionality. 

### Visual documentation

In this image I actually have Test Group Two selected, but its details do not appear. 

<img width="1491" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/150393579/b05ff7bc-6cd3-4fe8-b608-64313e5cedab">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.123 (Official Build) (arm64)
- Operating system and version affected: macOS 13.4.1
```

**Comment by agreaves** [comment]
Hi @brian-tempo, thank you for the report! This is now fixed!
