### ISSUE TITLE
Can't edit api call group

### ISSUE THREAD

**Issue by tiagorocha4sys** [FlutterFlow/flutterflow-issues#1816]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't edit the base URL of my api groups

### Expected Behavior

being able to edit the base url of a group

### Steps to Reproduce

When creating an API call group and saving it is not possible to edit the group.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oksmB34ZOoctC7qXyY+9WhSQRH0M3aoEW1spBazwbfe+uB4kqevfOTERWOPHhTVVYf2GWgWoW097xjeDtNfc4HxytG6pE/rluFBWUWlOgR4iOFJWgR3dSRNpQGGqvyKaVkxBBCM1fSE0s20ylNemvQj3sQID3PjJNDq/LZO4=

### Context

I have several groups of api calls.
As flutterflow does not have an environment variable to change the environment for API calls, I manually change the base url of all groups before deploying

### Visual documentation

https://drive.google.com/file/d/1FEN1gRL_A-nvCXiYANitZ94ip5QX1ADp/view?usp=drivesdk

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: 
sdsds
```

**Comment by brian-tempo** [comment]
I'm having the same issue. See here: https://github.com/FlutterFlow/flutterflow-issues/issues/1815

**Comment by agreaves** [comment]
Hi @tiagorocha4sys, thanks for the report. This is now fixed!
