### ISSUE TITLE
Variables are not substituted in API URL's

### ISSUE THREAD

**Issue by dkoontz** [FlutterFlow/flutterflow-issues#1818]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to be able to swap the API endpoints of my application using an App variable and an API Group. I define the API group's base url using the app variable and then define a route. Variables in the route are substituted, but not the base url portion.

### Expected Behavior

When a variable is used in the base url of an API group, it will be substituted when making the API call.

### Steps to Reproduce

1. Create a new app variable, for example `serverUrl`
2. Create a new API group, use the variable created in #1 as the url, for example `[serverUrl]`
3. Create a new route in the API group, go to the response & test tab and look at the API URL, it shows the variable as text, not the value of that variable, for example `[serverUrl]` instead of `https://swapi.dev/api/`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8kzfLqw491ocdD7q6JY8dVhioRNmZ/bY0vku0bFQwgIYzwEoolO+DeZRFCcsyCfwk3OmeZ+X4Ip/zXuNrpEcAnAweIQ745yc9bVQ7MeFiuRJ+bC6uCZnQnQZ9TIWam06COihIlB/VuWVZg2GWHNtivExLsQb7aDlcRPvH8OrPIjFKFLgzsVjhmtmNecCfn

### Context

I cannot easily swap between a production and development environment by altering an application variable. I must set the value explicitly, this prevents the use of tooling to set the environment based on URL parameters, server location, etc.

### Visual documentation

![Screenshot 2023-11-09 193816](https://github.com/FlutterFlow/flutterflow-issues/assets/7493/7358f7ad-eb27-476c-8c6a-652e7ccecbc6)
![Screenshot 2023-11-09 193757](https://github.com/FlutterFlow/flutterflow-issues/assets/7493/2db494f6-507c-4c34-8639-856f266b19b7)
![Screenshot 2023-11-09 193725](https://github.com/FlutterFlow/flutterflow-issues/assets/7493/1ed54d6f-4b16-4f94-8e40-b6d19c61625f)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Windows
- Browser name and version: Firefox 119.0
- Operating system and version affected: N/A
```

**Comment by connecty-in** [comment]
@wenkaifan0720 and @hariprasadms Is this issue fixed or do you consider this as a feature/enhancement request?
Because last I checked being able to use variables in API Calls is already an existing feature. That makes this a bug, but not a feature request. And can you add notes before you close out github issues? I have had multiple instances where a github issues is closed without proper public reasoning.

**Comment by takacsoliver** [comment]
Hello, i found a workaround.
https://community.flutterflow.io/community-tutorials/post/tutorial-api-group-base-url-variable-workaround-0o5dLg18neED4em

**Comment by jessydm** [comment]
Thank u for sharing the workaround.

> Hello, i found a workaround. https://community.flutterflow.io/community-tutorials/post/tutorial-api-group-base-url-variable-workaround-0o5dLg18neED4em

**Comment by metalik** [comment]
> Hello, i found a workaround. https://community.flutterflow.io/community-tutorials/post/tutorial-api-group-base-url-variable-workaround-0o5dLg18neED4em

@takacsoliver Your workaround works when running the App but seems not cannot get the "Test Response" in the "FF Define API Call" section?

 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/722845/17f32c56-ac3b-4cdd-9a12-5911e4da04dc)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/722845/59f287da-62e8-48cd-a2b9-6c814bca8d67)
