### ISSUE TITLE
Flutterflow mac app stuck in "out of date" loop

### ISSUE THREAD

**Issue by mixart** [FlutterFlow/flutterflow-issues#1819]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I launch the app and open my project it says Flutterflow version out of date
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13832/c5216ad2-0c97-4ae5-ad9d-78292c31332d)

I click the button that says "Dashboard" and re-open the project and it repeats the modal. 

Quitting the app and restarting does not resolve.

### Expected Behavior

App should refresh version on mac app.

### Steps to Reproduce

1. Launch mac app
2. Open project
3. Modal appears, press button to go back to dashboard
4. repeats with no way to resolve.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

Unable to use mac app.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13832/c5216ad2-0c97-4ae5-ad9d-78292c31332d)

### Environment

```markdown
- FlutterFlow version: ?
- Platform:Mac OS
- Browser name and version: ?
- Operating system and version affected: Mac OS
```

**Comment by agreaves** [comment]
Hi @mixart, which version of the MacOS app are you on? If you are on the latest version you should not see this message.

**Comment by cartworthy** [comment]
> Hi @mixart, which version of the MacOS app are you on? If you are on the latest version you should not see this message.

I don't think it matters which version he's on. I've had this issue with every version. It happened today and maybe a week or two ago for me. I have to re-download the application from the FF website and delete the old one. It would be nice if the application offered the ability to update itself.

**Comment by xenomorph78** [comment]
I've had this happen twice. 
1. Delete the app from your Applications folder
2. Close out of the Web UI of FF
3. Download the LATEST version from :https://flutterflow.io/flutterflow-desktop-app
4. Install and it will likely tell you there is a newer version available so do the auto upgrade there.
5. Don't open the WEB UI version of FF while your app is open. This seems to be what causes the issue for me.

**Comment by hariprasadms** [comment]
Hi, I've observed that the FlutterFlow latest version for Mac, this issue no longer exists. Therefore, I am closing the issue.
