### ISSUE TITLE
can not create SubSubCollection

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#182]
My collection design ins as follows. 
Main_Collection_A
          SubCollection_A1
          SubCollection_A2
                    SubSubCollectionA2.1
                    SubSubCollectionA2.2
          SubCollection_A3
Main_Collection_B
Main_Collection_C

## Expected behavior (required)
Flutterflow ---> Firestore ---> + icon ---> Create Collection ---> Is SubCollection = True ---> Select Collection dropdown list to add SubSubCollection under --> I can't select current SubCollection to add a SubSubCollection.

## Current behavior (required)
Flutterflow ---> Firestore ---> + icon ---> Create Collection ---> Is SubCollection = True ---> Collection list ---> Current SubCollections are not shown in dropdown list.

## To Reproduce (required)
Flutterflow ---> Firestore ---> + icon ---> Create Collection ---> Is SubCollection = True ---> Collection list ---> Current SubCollections are not shown in dropdown list.

## Context (required)
I have SubSubCollection under SubCollection. Firebase allows such design. But Flutterflow does not support such design. 

## Screenshots / recordings
My collection design ins as follows. 
Main_Collection_A
          SubCollection_A1
          SubCollection_A2
                    SubSubCollectionA2.1
                    SubSubCollectionA2.2
          SubCollection_A3
Main_Collection_B
Main_Collection_C

## Your environment
Window10, crime browser. Latest FF. 
![Bug about add SubSubCollection](https://user-images.githubusercontent.com/117246043/204966280-095a55de-7af1-4fd5-8e4b-75eb4c3556e3.png)

**Comment by Pepino-GR** [comment]
Hi palmdeskApp,

in the documentation, you see:

At this time, FlutterFlow supports one level of nesting (e.g. collection -> subcollection). Second level nesting is not currently supported ( e.g. collection -> subcolleciton 1 -> subcollection 2)
[
](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/creating-subcollections)

This is not a bug, to I will set it to a feature request.

**Comment by palmdeskApp** [comment]
Thanks. The lack of this feature limits FF's usefulness only for entry level applications.
