### ISSUE TITLE
Slider's initial value from page state variable doesn't work

### ISSUE THREAD

**Issue by gymeney** [FlutterFlow/flutterflow-issues#1820]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

page state variable **inlevel** (type: double) = 5.
a - in text **inlevel** works correctly
b - in initial  value of slider **inlevel** doesn't work (now 7 - like in default value of inlevel)
a != b
![Снимок экрана 2023-11-10 102540](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/1920f9bf-d066-46fe-9a98-f7d96679e3b5)

### Expected Behavior

I expect
a == b
slider = text above the slider = 5
Because
text = inlevel = 5
slider = inlevel = 5 (not 7 now)

### Steps to Reproduce

1. I created page state variable "inlevel" as double.
2. onpageLoad I set inlevel as 5 (default value = 7)
3. I use this variable for slider's initial value.
Initial value = inlevel
4. I use this variable for text above the slider
Text = inlevel

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz/Hqx89grsND1arqdcBr/GMWJVg4RpI0scsYbwsYGIjyPbJ/ZM/SXFtCOcyoYXlhHGKbvF0FpsrOkt+SEsFdOQubGr59yapuTxaWVXq8RbXXOqmOVmh5N55RGXacyLWgkyNQWcxucVoM7EOHNdyvUnLdCZ+/Zwh9f6PHaOI=

### Context

This is a form for updating document in Firebase. If the slider contains wrong value the user can't read right value.

### Visual documentation

![Снимок экрана 2023-11-10 103449](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/18932ef5-7dd9-405b-9534-ea9ebdd2b078)
Initial value (inlevel) for slider:
![Снимок экрана 2023-11-10 103536](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/2fb9a359-efa1-407b-b87c-99ed24ae97d0)
Text (inlevel):
![Снимок экрана 2023-11-10 103827](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/c664921a-da6a-40ba-b885-8f40c9e9e510)

Result in Google Chrome (Test Mode):
![Снимок экрана 2023-11-10 102540](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/f7d9d52d-e91d-4f8b-8ee9-ac7b0f7aceec)

### Additional Info

There is the similar issue for initial value of CheckboxListTile.
https://github.com/FlutterFlow/flutterflow-issues/issues/1889

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Google Chrome Version 119.0.6045.124 (Official), (64 bit)
- Operating system and version affected: 
Windows 11
Version	10.0.22621 installation 22621
```

**Comment by SameerShahzad99** [comment]
@gymeney It looks like the bug report code that you shared is not for the blank project with the issue reproduced, please share that, so we can proceed with the testing!

**Comment by gymeney** [comment]
@SameerShahzad99 I updated bug report code - for new blank project

**Comment by gymeney** [comment]
@SameerShahzad99 is my new code OK? Did you get confirmation that it's not a single error and it is in all new blank projects.

**Comment by gymeney** [comment]
@SameerShahzad99 I haven't gotten info about this issue. I replace bug report code of widget in a new blank project. Is it bug or not?

**Comment by victoriahuang1** [comment]
Hi @gymeney , similar to the response you received in #1889, this is the expected behavior due to how page loading interacts with widget rendering.
Again instead of updating page state, please directly set an initial field value for your local page state variables.
