### ISSUE TITLE
URLs Not Clickable in htmlView when Using Set From Variable

### ISSUE THREAD

**Issue by awarsing** [FlutterFlow/flutterflow-issues#1821]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

WordPress API response is transformed in a custom function, the output is valid HTML. The htmlView widget displays everything properly, including CSS styles.

I add an htmlView widget to a project page, then using set from variable a custom function is chosen, and then the input is the JSON path to the WordPress. All fine. No errors.

URLs in the body of the rendered text in the Run, Test, or TestFlight modes are not clickable.

If I manually type in a URL in the htmlView widget, the link is clickable in all the above modes.

![screenshot-000108](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/ea3d95bc-8c28-41b2-8e09-f7d66a363fdd)
![screenshot-000107](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/8c2dd260-99ba-4826-8bfb-9fad2d8bccc5)
![screenshot-000106](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/cabe595f-0186-4a93-89a0-5de1cf033abe)

### Expected Behavior

Using HTML code set from variable should allow links to be clickable.

The link in the rendered text should be clickable.

### Steps to Reproduce

1. add the htmlView widget to a page
2. choose add from variable
3. choose custom function
4. link input data to function
5. run test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlMrl05JNocMB1rXpbcExjiAXHGY5a7swlut9Z0o2C4z0G7YARsnRN1FaZ+m+Sgo2e06j+ToKpvzPv/bIN+07Azuab4hPypBuaz3jXmK6MZinO5CodHwnTdpKClyx1p7YpgonObJoSVoE7TmQIunLVh7dJrruOWoRPfiLKdr4o3/uQ0SLb3kNh1JWeC/v

### Context

I cannot publish text to my app when URLs are not clickable, this will confuse my users.

### Visual documentation

The video below demonstrates links are not clickable using add from variable, but are clickable from manually entered HTML into htmlView, and from text links via Action Flow Editor (just to show a third case).

I added a text view to display the same HTML that the custom function generates, just to show the HTML is valid.

https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/84ef713e-1ef7-4aa8-8be6-9a14ff324c40 

### Additional Info

I opened a ticket before, but maybe didn't describe it well enough.

https://github.com/FlutterFlow/flutterflow-issues/issues/1608

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: iOS
- Browser name and version: Chrome Version 118.0.5993.117
- Operating system and version affected: macOS Monterey 12.7.1 (21G920)
```

**Comment by darlene003** [comment]
I'm having the same issue.

**Comment by awarsing** [comment]
No change for me. I did one other simple test. Adding a single line of text in an <a> tag to a State Variable also does not produce a clickable link.

**Comment by awarsing** [comment]
Here is a new, blank app with one htmlView widget and one `<a>` tag in an App State variable.

https://app.flutterflow.io/project/html-view-test-u5h8nm



https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/8dabdd00-deb7-412c-96c5-4c05589943c3

![screenshot-000117](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/bcde5ad9-093e-49fc-b71f-1a857c1ddb02)
![screenshot-000115](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/c6a521fa-4f4f-48ef-b8c3-041485a1a99f)

**Comment by sbis04** [comment]
This should be fixed in the next FlutterFlow update!
