### ISSUE TITLE
Firestore Settings 'Users Collection' turns on on open

### ISSUE THREAD

**Issue by staplKody** [FlutterFlow/flutterflow-issues#1822]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I turn off the Users Collection setting in Firestore settings, it turns itself back on whenever I reopen the project. 

### Expected Behavior

I would expect the setting to persist the last setting. When turned off I would expect it to stay off.

### Steps to Reproduce

1. Add a firestore collection
2. Turn on Firestore Settings > Users Collection
3. Choose the collection
4. Exit project
5. Reopen project
6. Turn off Firestore Settings > Users Collection
7. Exit project
8. Reopen project
9. Note if the setting turned back on

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CkcjfsMx2rsRE7aX6bu9VijsXJmY6RY0RkewbZwsbN5PTC7N/PPWkZRBuYOKqYW9EIkSmmXI0/+DyiYfuUfFdOUmub6JkzZBXEhXKTnyQe5OBPruWXEZTO/lXGWKh5rWz2R5vNsBtLEYe1F6LONyQTXPrJb72ImdISq/LZO4=

### Context

I turned on the setting to see how it worked, realized it wasn't useful to me and turned it back off. Ever since then, any time I open flutterflow (even if I CTRL+S) the setting is back on. This is an issue because I do not have the correct fields for a users collection and therefore FF provides errors. This means I have to go turn the setting off each time, or set up a dummy collection so that I don't get errors. 

### Visual documentation

These errors appear on every open of my FF project: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/86f7aa53-9ff9-4349-8f79-e6533ed603a5)

This is the setting in question.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/b5adfadc-704b-4683-9116-feb32a3d0b89)

### Environment

```markdown
- FlutterFlow version: V4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Chrome  119.0.6045.124 installed as a PWA
- Operating system and version affected: Windows 11 22H2 OS Build 22621.2283
```

**Comment by agreaves** [comment]
Hi @staplKody, thank you for the bug report! We've managed to reproduce this, and the issue should now be fixed! 🙂

**Comment by staplKody** [comment]
@agreaves Thank you very much this makes my life a bit easier now
