### ISSUE TITLE
Unable to build in Test mode or APK

### ISSUE THREAD

**Issue by sbosell** [FlutterFlow/flutterflow-issues#1824]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the last update yesterday it seems the app won't build in Test Mode or produce an APK.  It generates the following error:

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/actions/actions.dart:58:25: Error: Method not found: 'safeSetState'.
      ).then((value) => safeSetState(() {}));
                        ^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         62.3s
Failed to compile application.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1896962/fe5daa00-4a51-4e9e-9473-a1eeecb5fea8)

The entire app is showing NO issues in the interface.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1896962/6dc8c791-a0c7-43cc-96f6-a24573f767a6)

### Expected Behavior

Clicking TEST mode or producing an APK should compile.  It does not at this time.

### Steps to Reproduce

1. Click Run Test
2. or 
3. Click Download APK

I did not try to reproduce from a blank project as it isn't applicable to my issue.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48jsmAwIt1m7RY15DpbflR/Sk5KUs7aoI40uxxaEk8J5zKB+wAYvf7P1FWTLy/YFFmIGe0inwx/Pfqhd79Eu44PTSrRoBI/pdyTg7LTjqRR5CnCc2/fW1QAedYJ27A5sG7nR1vLtZ1SXgQ72euG+++dBPXHYDRNm4WDf2LKdeK2SrDX1iXc2URm05KZDPz

### Context

I am unable to test the app or product an APK.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1896962/6088e462-7103-4963-baf7-00a178820392)

https://github.com/FlutterFlow/flutterflow-issues/assets/1896962/a022203b-69f3-4544-9af1-8446b725f8a5

### Environment

```markdown
- FlutterFlow version: Web and Android - Flutter Flow 4.0
- Platform: Web
- Browser name and version:  Edge Version 119.0.2151.44 (Official build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @sbosell - I can reproduce the issue. It mostly happens when custom actions got action parameters and calling the same action to show buttomsheet in a action chain. Downloaded code got this error.

<img width="1168" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/9337e2f9-eaff-4d60-8f69-be0e90fa104d">

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/db1f0373-7437-4b54-adff-860ee0fb3e6d

**Comment by sbosell** [comment]
Are you tracking this as a bug or something I need to change?  I wanted to open the bottom sheet when an NFC event occurred which is why I am passing that into an action.

**Comment by vishruth-ram** [comment]
Getting the same issue. Even for code generation

**Comment by agreaves** [comment]
Hi @sbosell, thank you for the bug report! I've reproduced the issue and it will be fixed in the next release.
