### ISSUE TITLE
Upload Media to Supabase (Typo in Choose source Option)

### ISSUE THREAD

**Issue by Rart3001** [FlutterFlow/flutterflow-issues#1825]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you add an action to a button that uploads an image to Supabase, when the application opens the Media Picker Modal to choose the source of the image "Gallery" or "Camera", the text for the option "Gallery" has a typo, The Gallery Option Said "Hallery" instead of said "Gallery", and has the same problem for the Spanish language.

### Expected Behavior

When the choose source modal is open:

For English has to say "Gallery".
For Spanish has to say "Gallería".

### Steps to Reproduce

1. Create a project configured with Supabase
2. Create a page
3. Add a Button
4. Add an Action to the button to Upload Images to Supabase.
5. Run the application and tap the button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksrq24p2rsNK+Kr+bsBB/WIUQzs8a7hNscoZTRIbfe/dOoYUP8+kM0RucMTmSlVMIGaWgWoW0PCJiPLxDcYqNQiZGapgzJFQZTqVd3GnMZfQFJWvOHQkN+NUC2Kv0rSR3xNDPslfciEf32eIF+6tVg/dQefoDGo0Dq/LZO4=

### Context

This makes my application look bad.

### Visual documentation

<img width="500" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12099493/af99a649-fbde-4742-94ee-790455fdb43f">

### Additional Info

I validate the error comes from the text in "internalization.dart" file:

In the "upload_data.dart" file you can see the call to the FFLocalizations class to get the text using the key of the text 'qb7o5bd7':

<img width="539" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12099493/9603c27e-0ecb-459f-aaf5-beb8534a4e6d">

And in the "internalization.dart" file you can see the typo:

<img width="372" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12099493/8a5d95b4-df45-4905-b071-a3485cb9b24c">

### Environment

```markdown
- FlutterFlow version: V4.0
```

**Comment by LuisFlywheel** [comment]
This is happening to me too, the customer reported this error a few days ago and I don't know how to fix it.

**Comment by Rart3001** [comment]
Hello @kevintonb, @aemelyanovff  some update about this issue?

**Comment by aemelyanovff** [comment]
@Rart3001  Thanks for reporting the issue, and sorry for the slow turnaround.

Not sure how this could happen - our default spelling is correct. Luckily, there's an easy fix for this:
- Go to Settings/Languages/Preset In-App Messages/Upload Data Messages/Gallery
- Update the next there.
