### ISSUE TITLE
Capitalization is not working

### ISSUE THREAD

**Issue by rcandeo** [FlutterFlow/flutterflow-issues#1826]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I selected in a text field a capitalization to Characters and it is not working

### Expected Behavior

if I fill as character, I expect to be CHARACTER

### Steps to Reproduce

1. selected a text field where I need to be upper case
2. selected Capitalization to CHARACTERS
3. run the app and go to fill this field in lowercase
4. the result continues in lowercase
5. see the result recorded in suppabase
6. the result continues in lowercase

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l7ZJOvtsA0LruYO9VniUsG1N/a700sdlud0wdCoDuBIk+ZPWlYlhuUsvjdG9MIkSmmXwzpKHrvobhDfE3GxeZGKE/yLl2dgnwJV6gUZOBCrqgdER7HcJTfki01MKzrQkmALZpWC0SwF6PNd+uZD/qN7qzImdISq/LZO4=

### Context

I need to record in upercase in my database to avoid duplicated names

### Visual documentation

![Captura de Tela 2023-11-10 às 15 03 32](https://github.com/FlutterFlow/flutterflow-issues/assets/150471618/7e18abf1-5b65-4570-9097-19db0b169a2b)

### Environment

```markdown
- FlutterFlow version: 4.0 3.13.7
- Platform: Web
- Browser name and version:Chrome 119.0.6045.105
- Operating system and version affected: Mac OS Sonoma 14.0
```

**Comment by rcandeo** [comment]
thank you

I have this problem in web

you have to agree with me that there is no sense in me to make this
adjustment...

Regards



Em sex., 17 de nov. de 2023 às 19:42, Hari ***@***.***>
escreveu:

**Comment by krystian-dev548** [comment]
Hi 🙂 Is there any update related to a fix for the Web? It still not work in Web Deployment, visiting the site from a desktop.
