### ISSUE TITLE
Algolia search return null subtype

### ISSUE THREAD

**Issue by Ortes** [FlutterFlow/flutterflow-issues#1827]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have documents indexed in algolia with nested DataType. When I make a request with FF algoliasearch the nested DataType are null. `ExerciseRecord` is my document type and `FieldData` is my subtype (DataType).

I dug a little bit into the code a posted [here](https://github.com/FlutterFlow/flutterflow-issues/issues/1567#issuecomment-1786851110) what I have found.

### Expected Behavior

The subtype not to be null.

### Steps to Reproduce

Create a algolia indexed firebase collection with a subtype (DataType).
Create a textfield that makes a algolia search on submit on that collection.
Check the return of the `fromAlgolia` function.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ks/l8YxPseUF18/Ub+9VgjgWHF87auYRkOtDbxQ8J5DLBIYuP//7ak5uTde0TGxEI1mJ/T0x0PvemvztCPFdaE+YRaVz1LtQdgnwQlmmVLqVPri8SW5/DeljCUyy56u7ryR5AMltdEIk61y2PN6vcA7qN77SPjJFRfiiOZOK2SrDX1iXc2URm05KZDPz

### Context

I want to make a search bar on a collection.
I can not make display the data from my search bar (from that subtype `FieldData` at least).

### Visual documentation

![2023-11-10-190216_1187x598_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/4e890cd5-38d5-4b5e-9143-280a16741edc)
![2023-11-10-190443_1176x215_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/1f58a8c7-0df8-439e-ab00-35393850ebf5)

### Environment

```markdown
FlutterFlow v4.0 released November 10, 2023
Flutter version is 3.13.7
- Platform: web
- Browser name and version: Google Chrome Version 118.0.5993.88 (Official Build) (64-bit)
- Operating system and version affected: Web
```

**Comment by srh98** [comment]
@Ortes one workaround for this is to use a custom function to get the documents using the document references returned by Algolia, then use those documents to display the data.

**Comment by hariprasadms** [comment]
Hi @hariprasadms - Sorry for the delay in responding on the issue.  Need bit more details to understand your collection and its structure ( document fields and data type structure ). Can you share those details here?

**Comment by srh98** [comment]
tagging @Ortes @hariprasadms

**Comment by srh98** [comment]
@hariprasadms for us datatypes that are not displaying look like this:
 
<img width="464" alt="Screenshot 2023-11-27 at 8 41 53 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/117376796/eeb0d8f8-facc-4ba0-9fa0-5b82de9c5be1">
