### ISSUE TITLE
BUG API CALL VARIABLES

### ISSUE THREAD

**Issue by lianr7** [FlutterFlow/flutterflow-issues#1828]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tested it on two projects and it happens on both.
I create a variable and add it to Query Parameters, so far so good. However, when creating a CALL API action and adding the variable to the action, it leaves the Query Parameters field and it is not possible to select it again.

### Expected Behavior

The correct option would be to remain with the selected variable and the call to function

### Steps to Reproduce

Add a GET call, any API http, even if it's dummy. Create a variable and a query parameter, select the created variable. After that, create an action, configure the variable and return to the CALL API panel to check if it is still selected or unset

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTk8/fsIxOvttG+KXUYcdvmWMXI0MfWLsr0utuGA0hfa7mP7AXdffRclBLYtfjd21AMGCKmTsC3NqMvuDhFsI3GyydY71xzJRXQQ3iZ3O6R6qKCYeOXnx8QN5WGBWx0JivhAlCHMBtc3ge716qB/CNG3qCf9qOYwx5e6fDbOY=

### Context

An important API call stopped working

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/90485704/d9a279b1-af63-45e8-93f3-eae7d666fa84)

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Versão 119.0.6045.124 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11 Home
```

**Comment by lianr7** [comment]
The bug has not been resolved. The variables remain selected until I pass a value to them in the API call action. It's not just a problem with one project, it's happening across all of my projects.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/90485704/d1bd8b1e-0d77-4bf3-9e0a-3b6f9c43841a)

**Comment by lianr7** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/90485704/0f47b0f3-12ac-4ee6-bf81-cab1c9f4d59a

**Comment by agreaves** [comment]
Hi @lianr7, thank you for the bug report! I've managed to reproduce the issue, which should now be fixed!

**Comment by patrickzu999** [comment]
The Bug is back for me is it for you @lianr7 ?

**Comment by lianr7** [comment]
For me too! The problem returned! @agreaves

**Comment by patrickzu999** [comment]
> For me too! The problem returned! @agreaves

Possible you can open a new request. I don't know how to do the bug report code.

**Comment by agreaves** [comment]
Sorry about this @patrickzu999 @lianr7, the fix got accidentally dropped in the latest release. Re-deploying the fix momentarily so you should see this fixed within the next half hour.
