### ISSUE TITLE
Unfunctional Request Photo Library Permission

### ISSUE THREAD

**Issue by BarnabasCollinsThe3rd** [FlutterFlow/flutterflow-issues#183]
Request permission for photo library is not functional on android devices, dialog box does not pop up.
tested it on several devices, even when permission is changed manually to allow access it doesn't read it as a true value.

## Expected behavior (required)
Request permission to pop up as a dialog box and ask for permission to photo library.

## Current behavior (required)
Unresponsive behavior.

## To Reproduce (required)
1. Create a new button with an action to Request permission
2. Select Photo Library as the permission
3. Create a condition and select Permission > Photo Library
4.  Add a snack bar for true and false values

Same steps as here: [https://docs.flutterflow.io/actions/actions/alerts/request-permission](https://docs.flutterflow.io/actions/actions/alerts/request-permission)

### Bug Report Code
IT4klPLq25Ngrt9c187pbcIwpyc4H2F7TLJEoetxc0gbfe/4B7AtdsnBSxZVYNCzaH1mGle0gjoy0tbXvuH1Kvc6PRGrG75k/pd6alyjEA8=

## Context (required)
Unable to request permission.

## Screenshots / recordings
[https://res.cloudinary.com/testingout/video/upload/v1669875571/photo_permission_tlaqy6.mp4](https://res.cloudinary.com/testingout/video/upload/v1669875571/photo_permission_tlaqy6.mp4)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Android, Android Emulator, Desktop, Web
* Browser name and version: Chrome & Firefox
* Operating system and version (desktop or mobile): desktop & mobile

Thank you!

**Comment by agreaves** [comment]
Hi @BarnabasCollinsThe3rd, I'm not able to reproduce this issue. When tested on emulator and Android device I'm able to grant permissions in both cases (for both Library and Camera). Please see the attached images. Can you provide any additional context for this issue?

![Screenshot_1671420351](https://user-images.githubusercontent.com/7757399/208341842-732efe2b-d102-4ed3-9085-2bc6dbe329bd.png)
![Screenshot_1671420358](https://user-images.githubusercontent.com/7757399/208341847-5860bf03-3dc9-4516-85cc-344a345f61e6.png)

**Comment by agreaves** [comment]
Closing this issue for now due to inactivity, but happy to re-open this issue if we get additional information and are able to recreate it!

**Comment by agreaves** [comment]
Closing this issue for now due to inactivity, but happy to re-open this issue if we get additional information and are able to recreate it!
