### ISSUE TITLE
Variables in API Endpoint Parameters UNSET themselves when used in actions as variables populated from Page Parameters

### ISSUE THREAD

**Issue by mackgorski** [FlutterFlow/flutterflow-issues#1831]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey there is something weird going on when I try to set variable in my api endpoint I can do this and save the endpoint but then in actions editor I want to use this variable and fill it in from the page parameters as the url contains parameter with the same name. When I save exit actions editor and go back to endpoint parameters the parameter that had variable set is now unset and does not react when I want to set it back.
You can look at my app Petronus and I am talking about "code" variable and parameter in 'logincontinue' endpoint and it's included in 'onboarding' page actions

### Expected Behavior

As a user I expect that variables can be used in actions, filled with page parameters and then value passed as my API endpoint parameter call.

### Steps to Reproduce

1. Create ne API endpoint
2. Add Parameter e.g., code
3. Set value of this parameter to be a variable
4. make sure variable has type as string 
5. in a new page go to actions 
6. add on load api call 
7. add a variable - reference the same variable created in API endpoint 
8. select to fill its value with page parameter in my case its code
9. go back to API endpoint created and see that the parameter's variable has been UNSET and it cannot be set back until deleted and re-created but then same happens all over again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

cannot generate one as error comes up

### Context

I am trying to pass "code" parameter with my API endpoint call but the vale of this parameter must be set from variable that in turn is set from page parameter = reading a "code" value returned as part of redirect_uri. I am trying ot use Auth0 to authenticate but from Xano integration and I have very hard time to make it work in FF.

### Visual documentation

Uploading Screen Recording 2023-11-11 at 18.46.01.mov…

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS, Android, Web
- Browser name and version: Safari Version 17.1 (19616.2.9.11.7)
- Operating system and version affected: MacOS 14.1.1 (23B81)
```

**Comment by mackgorski** [comment]
Here's the screen recording as it was to large for GH https://drive.google.com/file/d/1I6_qI4yZa3w30-Ctu3IdNIaUbg544BeK/view?usp=share_link

**Comment by agreaves** [comment]
Hi @mackgorski, thanks for the report. That does indeed look like a bug! Could you try again to generate the Bug Report Code? I need that to get the project link and recreate the issue myself. Otherwise, please let me know the exact time you tried to generate it and it failed so that I can look it up in the logs and figure it out that way 😅. Thanks!

**Comment by mackgorski** [comment]
Hey Alex!Thanks for coming back to me! It happened Today at 18.46 CET here’s a video I also attached to bug on GH https://drive.google.com/file/d/1I6_qI4yZa3w30-Ctu3IdNIaUbg544BeK/view?usp=drivesdkHope that this is enough to triage. I am away from my keyboard already for Today. Looking forward to more info. Best,Mack GórskiSent from my iPhoneOn 11 Nov 2023, at 21:03, Alex Greaves ***@***.***> wrote:﻿
Hi @mackgorski, thanks for the report. That does indeed look like a bug! Could you try again to generate the Bug Report Code? I need that to get the project link and recreate the issue myself. Otherwise, please let me know the exact time you tried to generate it and it failed so that I can look it up in the logs and figure it out that way 😅. Thanks!

**Comment by marianneke** [comment]
I am experiencing the same issue

**Comment by Empirome** [comment]
Same here.

**Comment by mackgorski** [comment]
Hey @agreaves ! Any updates by any chance on this one? It's kinda blocker for moving forward with my project and I see others are also experiencing the same bug.

**Comment by mackgorski** [comment]
@agreaves I still cannot generate Bug Report Code from the UI. Here's the error I'm getting `Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)`

**Comment by mackgorski** [comment]
Thanks @agreaves I was using Safari :) but opened in Chrome enabled that setting and now I could copy the Bug Report Code. Here it is:

`ITFfiPHq24ZOxLgB14SJbe0w+T0XJUscTIMziNZ+exUbfaL1BqQiYsneVEluQt+oaVNcDFWb8U0EwdaKiuH9FvcVHE+qbohiz81LWD3ke2imb8mJBc/tTkFAPNxXC0/C55i3hhFSXftfdGQs2kyUPPOXfA7DBOu/Zwh9f6PHaOI=`

Hope it will be a quick fix ;)

**Comment by agreaves** [comment]
Thanks @mackgorski! I've now reproduced the issue and just deployed a fix 😊
