### ISSUE TITLE
Bug in build your first page tutorial step 1/12

### ISSUE THREAD

**Issue by Thoryeah** [FlutterFlow/flutterflow-issues#1832]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to do the first thing the tutorail show me. step 1/12.
-Drag-and-drop the listview widget under Highest Rated.
Get error. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150575168/79d02bea-5b8d-4cca-a7c4-426af2e38d52)
 

### Expected Behavior

What the guide shows should happen

### Steps to Reproduce

Ddont know how to start the tutorial over. 
It poped up when i stated a project. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9ajWU7HFw1UIc0sNobbxAjIoDoPJkUaeLBQFJVUte7S3xLKEWLozsFwMrIhobDUO5daC+VY7p6wcxUdQHwLUO/aoSyEbiwRHd6J9tbGH6706aFmQpSD/V1dVo67WetfOu8Vh3DQ7n4Zwh9f6PHaOI=

### Context

i cant follow the tutorial to learn flutterflow. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150575168/239f7bc3-0b02-4bc9-a7cd-08f378249d4d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150575168/dccebd2a-09f3-4e14-b116-7e8a9c6acbbc)

### Additional Info

would be great if the tutorial was working. 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 (released November 11, 2023)
- Platform: (e.g. Web, Lenova Desktop) Web.
- Browser name and version: (web): Chrome 107.0.5304.110
- Operating system and version affected: Windows 11, version 22H2 for x64 (KB5031323)
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @Thoryeah! It will be fixed in the next update.
