### ISSUE TITLE
Test mode load fails due to push notification package

### ISSUE THREAD

**Issue by celiostat** [FlutterFlow/flutterflow-issues#1834]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since last week, test mode keep on getting stuck and throwing this error in dev console : 
One time out of two, it will somehow work, but most of the time, it won't.

### Expected Behavior

That test mode load and does not fail.

### Steps to Reproduce

1. Open test mode
2. Test mode fails : page keep loading, error in browser console is showing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

I cannot test app.

### Visual documentation

Pleas see below a screenshot of the error : 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8578710/daf9ff94-e48e-4980-85a3-ff7c4cf514b7)

### Environment

```markdown
- FlutterFlow version:  v4.0 Flutter 3.13.7
- Platform:  ?
- Browser name and version: Version 119.0.6045.124 (64 bits)
- Operating system and version affected: Windows 10
```

**Comment by ready4sea** [comment]
I am encountering the same symptoms. No clue if it is due to a notification package, but unending progress bar is displayed and unable to test my project either.

**Comment by aemelyanovff** [comment]
@celiostat Thanks for reporting the issue. Please update the steps to reproduce to start from a blank project. If there's no clear way to reproduce it from a new project, please reach out to FlutterFlow support for further assistance.

**Comment by celiostat** [comment]
Seems like occurring less and less now, and as it happens now every now and
then, it is hard to reproduce. Thanks for answer.

Le ven. 15 déc. 2023, 17:17, Anton Emelyanov ***@***.***> a
écrit :
