### ISSUE TITLE
Conditional Builder broken when using DropDown value as condition

### ISSUE THREAD

**Issue by zachspar** [FlutterFlow/flutterflow-issues#1838]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a dropdown that determines which ListView I would like to show in a ConditionalBuilder block. The first time I select from the dropdown, the ListView loads. Every subsequent change of the DropDown the ListView does not show. There is also undefined behavior when I set the each ConditionalBuilder child widget visibility.

### Expected Behavior

Conditional Builder children should be shown based on DropDown value.

### Steps to Reproduce

1. Create new page
2. Create App Bar with a dropdown with multiple values
3. Create a conditional builder block with each condition dependent on the dropdown value
4. Run in test mode
5. Select something from the dropdown
6. Now select something different from the dropdown (it won't show this item)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hsrl25R2pbxE7q6JKcJFoCo5JkQ6ULg3i+5BaBoofePrBJkqP8zBP1dVXf2RSmxiOlmJnnIIp/+MkvDDF/k4GxCIQ7041pN6aDnJeDuRR7XTEbqgfURABfxQGhzGyKCOiiNTAMVpS1oZ1E6mAufIYCbrHZTBDUcZAfr9UZPJpXznAh+3FDhmtmNecCfn

### Context

I have a dropdown value to select a category and each category has its own API call. I want to show a different ListView to call a different API based upon which category is selected from the dropdown. I use a ConditionalBuilder with each condition checking the value of the selected dropdown to render the appropriate ListView to call the API.

### Visual documentation

![widget-tree](https://github.com/FlutterFlow/flutterflow-issues/assets/41600414/f1eb89f9-e425-4ca5-b8d4-743325038bdf)
![facts-not-working](https://github.com/FlutterFlow/flutterflow-issues/assets/41600414/1bf7df93-4155-405c-aa96-d134bd03c2bc)
![dadjokes-working](https://github.com/FlutterFlow/flutterflow-issues/assets/41600414/9f71f80d-cf55-4176-aff0-627817e8ea9c)
![dropdown](https://github.com/FlutterFlow/flutterflow-issues/assets/41600414/293019f4-595c-4428-8bb8-128c481c913f)
![riddles](https://github.com/FlutterFlow/flutterflow-issues/assets/41600414/e7dc4c0c-c262-4eba-91cb-d8bc546d4dec)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web, iOS, Mac, Linux
- Browser name and version: Chrome Latest
- Operating system and version affected: Arch Linux
```

**Comment by takashiff** [comment]
Thank you for your bug report! We have fixed this issue, and it should be reflected in our next deploy!
