### ISSUE TITLE
Sign In with Apple does not work on MacOS App

### ISSUE THREAD

**Issue by Empirome** [FlutterFlow/flutterflow-issues#1841]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to Sign In with Apple on the latest FlutterFlow MacOS App, there is a Firebase auth error. See attached screenshot.

### Expected Behavior

I'd like to sign in with my Apple account.

### Steps to Reproduce

1. Download FlutterFlow macOS app.
2. Start downloaded app.
3. Click on Sign In with Apple button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not available

### Context

I'd like to develop on the MacOS app instead of in the browser.

### Visual documentation

<img width="306" alt="Bildschirmfoto 2023-11-13 um 20 10 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138522380/857c6405-da15-40d4-b740-31631720b9f0">
<img width="672" alt="Bildschirmfoto 2023-11-13 um 20 11 16" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138522380/70fd2220-1e0a-43c7-87be-c67340da3837">

### Environment

```markdown
- FlutterFlow version: MacOS version 4.0.3+5
- Platform: MacOS Desktop
- Browser name and version: -
- Operating system and version affected: macOS Monterey & Sonoma
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @Empirome. Unfortunately we can't make Apple Sign-in work an MacOS at the moment. We'll disable it in the next update.

**Comment by ABIV** [comment]
Any fix for those that have already used this, we are effectively locked out of desktop, why not allow adding a second email to the account as a workaround?

**Comment by selaru** [comment]
it's the same for the windows desktop app
