### ISSUE TITLE
Dropdown fails when option values are the same

### ISSUE THREAD

**Issue by anywheresa** [FlutterFlow/flutterflow-issues#1842]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using labels and option values in a dropdown, the dropdown expects values to be unique, which is wrong logic.
In many cases you may have unique labels but some of these labels may contain the same value as other values for different labels.
Your dropdown does not know how to handle values that are the same and then just displays garbage data. When I say garbage data, I am saying that you logic takes the labels that have duplicate values and repeats them the same amount of times it finds the same value for that label somewhere else in the table.
The data table is from mysql.
The API inside of FF pulls the correct information from this table and displays it correctly. It is the dropdown that does not know how to display this info.

### Expected Behavior

I expect your dropdown to handle different labels that may have the same option values.
Example. I have a table of different countries displayed as labels of the dropdown. Some of these countries have the same call rate value. The correct call rate values must be displayed instead of getting confused and showing countries with the same call rate over and over again.

### Steps to Reproduce

1. Create a table in mySQL with data containing two colums ie. Country and Rate.
2. Populate table with different unique countries but some of the countries must have the same rate. This was done in mysql
3. Example Australia //(country) 3.00 //(rate)
4. United States 4.00
5. UK 3.00
6. etc..
7. Create API to get data
8. Create blank project.
9. Add dropdown to page.
10. Add country to dropdown label.
11. Add rate to dropdown option value.
12. Display data in dropdown with Country as Label and rate as value option.
13. United States will be displayed once which is correct but Australia and UK will be displayed twice each and the display order will be trashed,

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sivHq4c9grt9J7aXidcFB/SAvNmI4a5ISscp8cwEbfJjbPO0ievXsYlRvQsO9TAhmIESmmlgfw+COiYbLNu4oaCmVf65M+KhMZD3jfzime5OBPcyCYXR6RO1Wf0ik5MG7ggpNCPptWVYR3DmEJOStSjDtJqLyIlFISq/LZO4=

### Context

Cant use drop down to display correct information.

### Visual documentation

Database
![Dropdown_2](https://github.com/FlutterFlow/flutterflow-issues/assets/56668789/0af4e42b-7749-49a9-9dd9-deff757eb5ef)
API Correct
![Dropdown_3](https://github.com/FlutterFlow/flutterflow-issues/assets/56668789/e6a3d39a-ddac-4494-87ca-c0b91b9901a3)
Design Correct
![Dropdown_4](https://github.com/FlutterFlow/flutterflow-issues/assets/56668789/e58d952c-cedb-4d7a-baf6-486317772965)
Display Incorrect
![Dropdown_1](https://github.com/FlutterFlow/flutterflow-issues/assets/56668789/4422cb7f-9558-4fe6-9a62-95d65809dd27)

### Additional Info

The above info should be comprehensive enough.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Windows
- Browser name and version:Chrome 119.0.6045.106
- Operating system and version affected: Windows 10
```

**Comment by anywheresa** [comment]
@hariprasadms That is ridiculous! 
Whatever option value is related to label should be displayed regardless. What you are saying if two different countries have the same rate, a dropdown cannot be used???? LOL. Sorry but that That is absurd. 
This is a BUG. Please open this

**Comment by anywheresa** [comment]
Its like mySQl or Mongo or Firebase saying to me, you cannot have two records where  firstNames and Surnames are not unique. LOL we will have to give you a unique surname, maybe Hariprasad10011?
How would you handle it if there are two names Peter and John and they both have the same surnames? Not have a dropdown? LOL

**Comment by anywheresa** [comment]
You close this but it is a BUG.

**Comment by davidvm2** [comment]
This is a valid issue, why was it closed?

@anywheresa did you find a solution for this?
