### ISSUE TITLE
Stack Component not working like before

### ISSUE THREAD

**Issue by Matar91** [FlutterFlow/flutterflow-issues#1844]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,

In test mode, suddenly, several buttons and a Google map stopped working in my app. 
this is because the are in a lower level under a stack component.

For example, when I try to interact with some markers on the map, they don't respond as they should (they don't do anything).

I tried removing the column that contains the filter (which above the map in the same Stack component as the map), and the map started working again.

 It seems that now, if you have one component over another in the stack, the one below is not "clickable."

### Expected Behavior

I should be able to interact with components in a lower level of a Stack Component like maps markers or buttons.

### Steps to Reproduce

1.Create a Stack component.
2. Put a button on a lower level.
3. Put an action to the button.
4. put a trasparent container on a higher level.
5.launch test mode and try to click the button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlsmB34p1xNtb+KrPK8cxqD0RGUMcW+dElNUbWRQtGJzpBu0pP8+ldhFvZ7SiaVNcM2L/mmEGpMHHvfzAV/ZfIReZbYhn/5F6bgHOe2inaZjWDc3tekFQEcdmCn7CyJ6Gnh15Kux2LkEtwzn7HOuuQg7DBOu/Zwh9f6PHaOI=

### Context

Can't use the map component or other combined stack logics. 

### Visual documentation

![Screenshot 2023-11-14 105621](https://github.com/FlutterFlow/flutterflow-issues/assets/19257081/31189aa8-57f1-4aee-b8cd-99db8134b771)

### Additional Info

![Screenshot 2023-11-14 105621](https://github.com/FlutterFlow/flutterflow-issues/assets/19257081/7796c261-ccf5-4bf4-b520-9b20ca185b5d)

### Environment

```markdown
- FlutterFlow version: v.3.13.7
- Platform: Web test mode
- Browser name and version: Chrome and Firefox
- Operating system and version affected:
```

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This looks like intended behavior, as the container (although transparent) is still covering the button. However, I do agree that there should be an option to interact with the lower levels, so I will put in a feature request. As a workaround, you can wrap anything above the lower levels with an IgnorePointer widget, and that should let you interact with anything below it. Thank you for your continued patience and patronage.
