### ISSUE TITLE
API call adding all query parameters even if the variable is not set

### ISSUE THREAD

**Issue by tx2z** [FlutterFlow/flutterflow-issues#1845]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I create an API call and add some query parameters linked to a variable. When I test the APIs in the API Calls section, if the variable is not set (I think) the query parameter is not included, so my APIs work as expected.
The problem is when calling the API in a Backend query (I think) the parameters are being included, witch produces an error

NOTE: I can't / don't know how to debug properly the calls, but based on the response of the API this is what I imagine it's happening.

### Expected Behavior

In an API call, if a query parameter is using a variable and the variable is not set or don't have a default value, don't include the query parameter.

### Steps to Reproduce

1. Create a new API Call
2. Add some query parameters linked to a variable
3. Define the variable as string without a default value
4. Test the API call without adding the variable (the query parameter is not included)
5. Add the API call to a Backend query
6. Use the backed query in a ListView without defining the variable (the query parameter is included in the call)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiMrl8ZFPm+FE0ZSIbvlooD0UJmkcTIAFkuwacy8YGIytBqQuPMn4dldBYNCoaVNcHVeLgjgF7s7ziezmVu1eIQydbJs7zYdqQwHOe2imb8WuCbivOEB8ONxRIW2B06evsRZCObN2dU4O31yXet+tcA3DFOu/Zwh9f6PHaOI=

### Context

In my project I'm using supabase and want to use API calls for some "complex" queries. I imported the swager Open API from supabase and it added all the posible parameters to the API witch is great but give me this problem.

### Visual documentation

![CleanShot 2023-11-14 at 11 57 10@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/79719ac5-0264-45ab-ab02-b1f7489f9a41)

![CleanShot 2023-11-14 at 12 00 11@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/56388263-2918-4d0e-87db-32ca02f3a659)

![CleanShot 2023-11-14 at 12 01 05@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/bb97154c-86e0-4460-8b1a-dc6e483ee556)

![CleanShot 2023-11-14 at 12 07 35@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/be392b90-cac9-40d1-b423-3eb20dedcd28)

![CleanShot 2023-11-14 at 12 07 58@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/056a6bb6-84be-4486-b06c-f5f70297ea6c)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released November 13, 2023
- Platform: Web
- Browser name and version: Chromium Version 120.0.6079.0 (Developer Build) (arm64)
- Operating system and version affected: MacOS Sonorama
```

**Comment by tx2z** [comment]
Hello @hariprasadms Thank you for the message and for look into the issue.

I can workaround the API calls, thats not the problem. 

I'm sure there is a difference in the way the API are called in the "Response and Test" tab and when calling them as a "Backend query".
In the first case (Response and test) when there is a "query parameter" assigned to a variable, if the variable is not set the API call is made without that query parameter (that's why it give me no error)
![CleanShot 2023-11-14 at 15 08 36@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/91078648-ed3a-46e9-96cb-ab1e1f582140)

In the Backend Query case, when the variable is not set the query parameter is send with the API call. 
![CleanShot 2023-11-14 at 15 10 21@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/1382210/af9e711c-e484-4216-b1e1-fd18a37f5d4d)

Was I expect is that when calling a backend query only pass the query parameters when the variable is set and not always

**Comment by hariprasadms** [comment]
Hi @tx2z - Thanks for additional details. I did test the exact step but with one query parameter using json place holder endpoint. I can see query request is success and the data is displayed. 

I would suggest try to test using an endpoint other than supabase and see if there are any differences.

<img width="1387" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/5be49ede-c77c-4ab1-a289-4ecdc9cf2b62">

**Comment by tx2z** [comment]
thank you again for the response and look into it @hariprasadms 

I'm recreating the API Calls "by hand" instead of using the ones generated (the workaround I mentioned earlier). That's ok for me and covers my specific case. I'm just not adding the query parameters that I don't use.


Anyway you can use this as a "feature request", as I would expect that if a query parameter is linked to a variable, the query parameter is only added to the api url if the variable is set.

Ex:
For the api "/products"
if a have the query parameter "id" linked to the variable "product_id"

if product_id is set the URL should be
/products?id=[product_id]

if product_id is not set it should be
/products (not "/products?id=" as it's happening now when adding the API as a backend query)

**Comment by takashiff** [comment]
Marking as closed due to inactivity

**Comment by swildermann** [comment]
having the same issue; a bit annoying
