### ISSUE TITLE
Allow one letter variable name in Data Schema

### ISSUE THREAD

**Issue by msteingruber** [FlutterFlow/flutterflow-issues#1847]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Variable names must have at least two letters

### Expected Behavior

Variable names with one letter are allowed 

### Steps to Reproduce

1. Create a new variable in an Data Schema
2. Try to use a one letter variable name. 
3. See error message "Name must have at least 2 ..."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez8/qw4pPn7xB1aXIKcEwlQMxJ1gjbJ0vhNV9ewsYGIDtO7NybuvTampWQt+RfwltfFqgnkcJ+N7xueDqU+44KQiEQ5Rm1rlbVTzvfEyQV6qJCsyKR3FQI8pXGX6EyrWOkRJdAMZYW38tig/GSw==

### Context

I use an API that has variable names like x and y. I cannot map the response to the correct data type.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2179676/424eab94-9980-4924-bd9f-7eae61dd8eac)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Safari
- Operating system and version affected: macOS 13.5.1
```

**Comment by hariprasadms** [comment]
HI @msteingruber, This is as per current design. This can be a feature request. You can create a feature request using feature request form available under help section. Add more details ( images and blocker details ) about why you are expecting variable names with single letter. More details can help us to understand the challenge you are facing and compare with wider user cases so we can treat this as a feature request.

**Comment by msteingruber** [comment]
The API returns something like
`{x: 1}`
It's not possible to map this JSON to a data type currently.

In my opinion there are 2 workarounds:
- Use untyped jsons
- Write in custom code a mapper which map the field x from API response to a field (e.g. xValue).

In my opinion it's somewhere in between a bug and a feature request because i cannot consume my API with data types currently. But i can also write it as a feature request.
