### ISSUE TITLE
Cannot Delete Collections from FlutterFlow

### ISSUE THREAD

**Issue by mfourman4** [FlutterFlow/flutterflow-issues#1849]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a number of Firestore collections in FlutterFlow which are incorrectly name or are duplicates.

Is there any way to delete these collections?

### Expected Behavior

I would expect to see an interface to delete collections from FlutterFlow.

### Steps to Reproduce

Create a Colection
Try to delete it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fjMrlvJFOj7xD7qr+bu9ajikUKVAnbZIoltZEdwIdCJ/qEKQAecn8V1tJbbyRSmNceWH8/W0fzP+NhePDE/pcEByJbZx5+s9uSQ6XUlGVMKXQO5OzdWh7LJpnIFSCzpuZ2BV5KtNuLUYB2k6Qfeu/cALaJJzROW0zPP6bMpnUp3S6KiToGn0Jg1ZSfCvr

### Context

I have a several incorrectly named collections, including duplicates. When trying to Query a collection, this makes the process of selecing the correct collection in the dropdown error prone.

### Visual documentation

None.

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform: NA
- Browser name and version: Version 119.0.6045.123 (Official Build) (arm64)
- Operating system and version affected: NA
```

**Comment by hariprasadms** [comment]
Hi @mfourman4 - I hope you have already found the option to delete the collection. You can find it here.

<img width="1458" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/232c80a3-2d2e-4e98-9150-4099c0b90224">

**Comment by mfourman4** [comment]
Thank you!
