### ISSUE TITLE
FlutterFlow Slider value  Bug

### ISSUE THREAD

**Issue by ABDULSidgs433** [FlutterFlow/flutterflow-issues#185]
We noticed  Slider value behavior will not work as expected values start 1 - 100 if we increase the value at the point reached value 55 throws a Bug like 55.00000124.  

## Expected behavior (required)
The slider should give the value 55.

## Current behavior (required)
Current the slider gives the value 55.000000123

## To Reproduce (required)

1. Create new page
2. Add Slider widget
3. Set min value = 0 and Max value = 100
4. Set step size = 5
5.Run the Code

Reproduce the slider Bug: https://app.flutterflow.io/project/sliderbug-apfijd

1. Slide the slider to the value 55.

## Context (required)
Slider Value reached 55 throws bug.

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/110808460/205034928-cd4b9034-f661-4f83-a9a9-f8069be5c66f.png)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform : Windows 10
* Browser name and version: Chrome & Version 107.0.5304.122
* Operating system and version : Mobile

**Comment by hariprasadms** [comment]
I can reproduce this issue. Below is the image. It happens only when slider interval comes at the mid of the max value. Otherwise, for all other intervals it works fine.

![image](https://user-images.githubusercontent.com/17435678/205050611-b5cb89b5-d822-454f-be15-1f7f11f70e70.png)

**Comment by agreaves** [comment]
Thank you for the bug report! While this bug comes directly from the Flutter slider widget, we will now allow you to specify the number of decimals to round to (including 0) in order to avoid this issue. This should be fixed in our next deploy! 🙂
