### ISSUE TITLE
Dropdown to select Collection for "Query a collection" only shows 6 out of 9 collections

### ISSUE THREAD

**Issue by mfourman4** [FlutterFlow/flutterflow-issues#1850]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to add "Query a collection" action to a button.

When I click on the dropdown to select the collection, it only show 6 of the 9 collections I have in my project.

### Expected Behavior

Show all of the collections in my project in the dropdown.

### Steps to Reproduce

Creat a new project
Add 9 collections
Add "Query a collection" action to a button
Review the list of collections available in the dropdown.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fjMrlvJFOj7xD7qr+bu9ajikUKVAnbZIoltZEdwIdCJ/qEKQAecn8V1tJbbyRSmNceWH8/W0fzP+NhePDE/pcEByJbNlkwbp2cgLxWjqQbqaaCs20OnNCQOBVIH6YzpuZ2BV5KtNuLUYB2k6Qfeu/cALaJJzROW0zPP6bMpnUp3S6KiToGn0Jg1ZSfCvr

### Context

I cannot query the collections I need to access in my application.

### Visual documentation

NA

### Additional Info

NA

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform: NA
- Browser name and version: Version 119.0.6045.123 (Official Build) (arm64)
- Operating system and version affected: NA
```

**Comment by hariprasadms** [comment]
Hi @mfourman4 - Thanks for submitting the issue. I have tested the action query with more than 10-12 collection. I can see all collections while adding query collection action. I can confirm that it working as expected.

I looked at your project as well. It works all right. If you still facing the issue, can you please add a quick video or sample project where you got the issue ? 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6ae65116-aecd-480b-8503-e984086fb0e0

**Comment by mfourman4** [comment]
Thank you for the quick response.

Here's what I'm seeing.


https://github.com/FlutterFlow/flutterflow-issues/assets/51795444/1003c15d-3a0b-4d4c-9f6c-db3c6feabeac

**Comment by mfourman4** [comment]
I have created a new project to work around this, so we can close it.
