### ISSUE TITLE
Regex empties textfield instead of displaying correct results

### ISSUE THREAD

**Issue by MaximeDelhorme** [FlutterFlow/flutterflow-issues#1851]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to put a regex that only allows decimal numbers between 0 and 100. Regex is verified [here](https://regex101.com/r/hW9kP5/2). When I enter a decimal on my keyboard in the textfield using this regex, the textfield is emptied

### Expected Behavior

Textfield should show the number with correct regex

### Steps to Reproduce

1. Create new page
2. Add textfield
3. Textfield properties choose Keyboard Type: Number (with decimal)
4. Textfield properties choose customer regex
5. enter this regex ^(?:100(?:\.00?)?|\d?\d(?:\.\d\d?)?)$

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jMrq081NodhE18/+ccB7/Ck5JWI8a+cvj+x7aCsvCIyqOpscf/fBfklUONDgTFZDPmf8q3EX/MmLveHXEMEDAE2qbohdzahiaQ2VQTqQaa3SDJS3b0d5L/xPGnbC5LavhwhCOtFfc14AwUyII9iyTg7cJbLEOXojQ+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

Trying to prevent user from inputting incorrect numbers in the field

### Visual documentation

<img width="295" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17178134/cb17a7dc-b5b4-4c28-98db-8854660d36fe">

### Environment

```markdown
- FlutterFlow version: v4.0 (released November 11, 2023)
- Platform: Web
- Browser name and version: Chrome version 113.0.5672.126
- Operating system and version affected: macOS Monterey 12.5
```

**Comment by nicmohr25** [comment]
Not a FlutterFlow Dev but i came across the same problem. Remove the '$' sign. This should resolve your problem.
Cheers

**Comment by MaximeDelhorme** [comment]
Thanks for the tip. Just tried it, but it doesn't solve the problem. Instead of clearing the field, the value now stays in the field but I can not enter any decimal separator int he field.

**Comment by MaximeDelhorme** [comment]
Shouldn't someone have a look at the issue before closing it?

**Comment by agreaves** [comment]
Hi @MaximeDelhorme, unfortunately this is simply the behavior of the mask in Flutter. This is similar to the issue described here: https://github.com/FlutterFlow/flutterflow-issues/issues/1705#issuecomment-1865321063

In this case, instead of using a filter, I highly recommend using a Number keyboard and Form Validation instead.
