### ISSUE TITLE
Codemagic Deploy Output Failed Step: Fetch signing files

### ISSUE THREAD

**Issue by asobini** [FlutterFlow/flutterflow-issues#1852]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Deployment to App Store via Magicode failed:

Codemagic Deploy Output
Failed Step: Fetch signing files

GET https://api.appstoreconnect.apple.com/v1/bundleIds?limit=100&sort=name&filter%5Bidentifier%5D=com.mycompany.kudcesapp&filter%5Bplatform%5D=IOS returned 401: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens

Build failed :|
Step 4 script `Fetch signing files` exited with status code 1

### Expected Behavior

I followed the deployment as decribed here:
https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/app-store-deployment

After first failure, 
I re-generate the API keys and iOS distribution certificate. It failed again with the same failure message. 

Deployment to Play Store via Code Magic was successful.

### Steps to Reproduce

1. Choose any app from my account
2. Go to Setting tab > App Settings > Mobile Deployment
3. Add private key, key ID (generated on App Store Connect), add issuer ID and app ID
<img width="740" alt="Screenshot 2023-11-14 at 21 46 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/89592607/4039590b-fafb-4a97-88b6-f8fc1f73eaed">
4. Press Deploy to App Store 
5. Notification that deployment start is successful ("success"), after a while status changes to "queued"
6. After few more minutes failure message appears

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

magiccodedeployappstoredoesnotwork

### Context

I am trying to deploy my app to App Store.
How it affects me? I have to shift my introduction to series.

### Visual documentation

<img width="1286" alt="Screenshot 2023-11-14 at 21 52 27" src="https://github.com/FlutterFlow/flutterflow-issues/assets/89592607/0d9da50b-6e59-4e7a-a980-d338bbba5a81">

### Additional Info

  
<img width="1373" alt="Screenshot 2023-11-14 at 21 54 11" src="https://github.com/FlutterFlow/flutterflow-issues/assets/89592607/c78c4d17-04b2-421e-9b48-5fcfe4c67000">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: iOS App
- Browser name and version: Version 16.5.1 (18615.2.9.11.7)
- Operating system and version affected: MacOS Ventura 13.4.1
```

**Comment by K-dra** [comment]
I'm facing the same issue with FlutterFlow 
are you also not the Account holder in your App Store Connect ?

**Comment by mvogel-dev** [comment]
I'm having this issue as well (also on a fresh project and app).

**Comment by victoriahuang1** [comment]
Hi @asobini , thanks for the report. Are you still experiencing issues? If so, please include the bug report code. We cannot debug otherwise.

**Comment by asobini** [comment]
I found 2 root cause myself. It was accidentally entered spacebar in the issuerID entry field.

**Comment by victoriahuang1** [comment]
@asobini thank you for the update. I will be closing this since it looks like it's resolved for you.

**Comment by eduriftio** [comment]
I have absolutely the same issue, I have tried literally everything, regenerated Private Keys and I get the same error over and over again @victoriahuang1 I tried to restart and complete Apple deployment from scratch and nothing happens
<img width="1176" alt="Screenshot 2024-02-10 at 23 25 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145130088/ae575a0e-0b3d-41f1-910e-fd7efbb77c03">
