### ISSUE TITLE
Error when trying to query Firestore Databas

### ISSUE THREAD

**Issue by mfourman4** [FlutterFlow/flutterflow-issues#1855]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have defined a query to run to populate a list view.

![List view screen](https://github.com/FlutterFlow/flutterflow-issues/assets/51795444/9d21fa62-e7a6-47b9-9af4-91dcaa7133bc)

![Firebase Query](https://github.com/FlutterFlow/flutterflow-issues/assets/51795444/74a5148d-e054-457e-a227-445598ac1e36)

My Firebase Rules settings are:

rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.token.email.matches("firebase@flutterflow.io");
    }

    match /users/{document} {
      allow create: if request.auth.uid == document;
      allow read: if request.auth.uid == document;
      allow write: if request.auth.uid == document;
      allow delete: if false;
    }

    match /{document=**} {
      allow read, write: if false;
    }
  }
}

However, when I run the app go to the screen I get the error message:

Run mode-only notification:
Firestore Security Rules Error on ListView: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.

### Expected Behavior

The query will run succesffully.

### Steps to Reproduce

1. Create a new page with a list view
2. Create a query to return a list of documents to populate the list view
3. Run in Test Mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CjMrlvJFOj7xD7qr+bu9VhjwRNk82RYIe0sJhZ0sdHZPMCpkqdcnQXFJWUuG0S1FYM2eGmnsy+fPemvHfLvA4AyiWGod8zs52SjrNd3yVMKaRCajtXG5/DZpQIWKn0MGzvBNQPrBtWkIR2lyIHOuXYAzbJ4TxIW47Hs6jD5OK2SrDX1iXc2URm05KZDPz

### Context

I cannot build my app if I cannot access the database.

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform: Webapp
- Browser name and version: Version 119.0.6045.123 (Official Build) (arm64)
- Operating system and version affected: NA
```

**Comment by mfourman4** [comment]
Hi Hariprasams, Yes, I am.

**Comment by hariprasadms** [comment]
Hi @mfourman4 - Sorry for late in responding to the issue. I can confirm that, fire-store query calls are working fine. This is something to do with your project and configurations around fire-store rules.  Can you please re deploy the fire-store rules try again ?  If you still experiencing the same issue in the project, try in a new project and see the consistency of the issue. Try and let me know how it goes. Thanks

**Comment by hariprasadms** [comment]
No response. I presume problem have fixed for you. Hence closing the issue. Thanks
