### ISSUE TITLE
Action -> Alert Dialog -> Custom Dialog -> Barrier Color: Unable to clear Barrier Color

### ISSUE THREAD

**Issue by jpollone** [FlutterFlow/flutterflow-issues#1856]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no "Clear Color" option in the color picker.

### Expected Behavior

There should be a "Clear Color" option in the color picker.

### Steps to Reproduce

Assuming a component is available:
1. Open the Action Flow Editor
2. Add Action
3. Select Alert Dialog -> Custom Dialog
6. Select a component
7. Choose any Barrier Color

To attempt clearing the color:
8. Select the color to open the color picker
9. There is no "Clear Color" option

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMn1z8p2xcdG0KqNcu1B/SoQNnonU4EWscsZa0kdB4joPLJ/ds7RQFpWZMDhYHlhHFWYhkAK3PTxkvDlJfVcGzaqftV4+qoNbTnxUXq8Sr6qC5a8QUZ5JJ9jCW6e4aaK3BIlFLNuW3gcwDuqF9itHyjZN5+/Zwh9f6PHaOI=

### Context

I can simply create another action, add the modal, and not select a Barrier Color

### Visual documentation

![screenshot 2023-11-15 0840@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/957276/06f2c19e-6492-4754-b565-635acc8ec215)
![screenshot 2023-11-15 0841@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/957276/9a139b71-7129-4fa6-a1b9-103e90a27150)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: Edge Version 119.0.2151.58
- Operating system and version affected: macOS Sonoma
```

**Comment by wenkaifan0720** [comment]
Hi @jpollone. This should be enabled in our next update. Thanks!
