### ISSUE TITLE
Media Assets Upload Successfully but do not render properly.

### ISSUE THREAD

**Issue by lullahub** [FlutterFlow/flutterflow-issues#1857]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This was raised as part of a previous issue. It was marked as resolved and closed, but I'm still experiencing a similar issue.

See issue: https://github.com/FlutterFlow/flutterflow-issues/issues/810

I've got a few SVG files which upload successfully, but will not render, or render when inserted in any containers anywhere in the app.

- I've tried to resize the SVG files, but they still won't render, even after dropping the resolution right down.
- I've also tried starting a blank project to see if it was related to the template file, but the issue still remains - no matter how much I alter the file, it just will not render properly.
- This doesn't appear to be a consistent issue - I can upload some other SVGs and they render fine. It seems that any artwork with approximately square dimensions seems to render fine. Anything else with more rectangular proportions will not render at all.

The file is the main logo for the whole app, so it's essential it renders in some form!! I've attached one of the problem files below, as well as a screenshot of the issue. (Visual Documentation Section)

Any help would be much appreciated.

### Expected Behavior

I'd expect all files to render properly. As SVGs are scalable, the resolution shouldn't technically make any difference.

### Steps to Reproduce

1. Create new Project - Blank or Template
2. Create or Select Container
3. Insert Image
4. Use uploader to add SVG file.

OR

1. Create new Project - Blank or Template
2. Navigate to Media Assets on LH Sidebar
3. Upload SVG files

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfjM/l8Yx1oeUB7ZSJbfpspDk7QkccTb4RltZ+RRQhNYzxBJkUYODOXEpLYte8dHNlfVGapH8y/tL6udr1DMFcGE+ZQIN8+YRXQQmXRkeRR5SsEYeZPWtCRZ5XJhTC4ae7piJRCPNpLWAb1FOYe/CrG3qCf9qOYwx5e6fDbOY=

### Context

I'm trying to upload all of the required media assets in order to design my app with the necessary branding.

### Visual documentation

![LLHB_GenLetterLogo_TranspSVG_500px](https://github.com/FlutterFlow/flutterflow-issues/assets/150933195/d7975b73-a21f-4ce6-b777-26960ea9361e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150933195/ee54b28f-713c-454e-8452-b2416423364c)

### Environment

```markdown
- FlutterFlow version: v4.0-Flutter 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.124 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro 22H2 OS Version 22621.2428
```

**Comment by lullahub** [comment]
I've managed to get this to work, but it requires a very specific set of export settings for the SVG in Adobe Illustrator - see below. All text must be converted to paths, as embedding text characteristics cannot be preserved, only presentational attributes.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150933195/82397984-35e4-4642-86f9-9643a524e8ce)

However, using these options, my logos managed to render in the Flutterflow app. However, it still will not work with any other forms or variants of exported SVGs.

**Comment by aemelyanovff** [comment]
@lullahub Thanks for reporting the issue, and sorry for the slow turnaround.

Not sure how this could happen - our default spelling is correct. Luckily, there's an easy fix for this:
- Go to Settings/Languages/Preset In-App Messages/Upload Data Messages/Gallery
- Update the next there.

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!
