### ISSUE TITLE
InActive Track color missing

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1858]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no property to set InActive track color, which isnt good when you have multiple themes

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/461d1f5a-12bc-43d0-a205-63dcc31b84e2)

### Expected Behavior

needs to be able to set the color, and it needs to be set by a variable.

### Steps to Reproduce

use audio player, there is no property.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

appearance is terrible so the color is fixed to some shame of grey and cannot be changed.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/b9605070-7720-4717-bb93-bc5b23b4fc0f)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by victoriahuang1** [comment]
@OldFred2023 thanks for the report. This is a feature request, but regardless I have gone ahead and addressed this. You should see this feature available soon!
