### ISSUE TITLE
Can not open FlutterFlow desktop app FF loading icon continually displays & console inspector shows errors

### ISSUE THREAD

**Issue by kiwimagic** [FlutterFlow/flutterflow-issues#1859]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My "desktop FF App" has stopped working. [MacOS] I was in it and out of nowhere it came up with a message saying Restricted access you do not have permissions to access this project and had a return to home button. The Home button tries to load the dashboard (I have multiple projects) and all it does is show the FF loading icon. I can access my projects using the Web version via safari https://app.flutterflow.io/ 

Inspecting the "non-working console" there are errors related to google identity kit "The requested URL /v1/accounts:lookup?key=[removed] was not found on this server. " and Cross-Origin-Opener-Policy policy would block the window.closed call

Two other FF Community members are reporting same in Discord - please check there for further reports.  Here is someone else's comment "I'm on windows, won't load in edge either, same happened to me permission error then stuck on loading"

Note there **was** an issue open (now in closed list) on https://docs.flutterflow.io/flutterflow-status [I can't find GitHub ticket] "15-Nov-2023 Engineering Team is actively investigating an issue that preventing FlutterFlow from loading for a small subset of users." Current Issues >> There are no known issues at this time. I am posting this to GitHub because the issue is listed as closed and I (and other discord community members) can not access FF.

### Expected Behavior

Desktop app should allow me to access my FF projects

### Steps to Reproduce

1. click on Flutter Flow App icon on desktop
2. watch blue loading FF icon... 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

can't get to this app will not open

### Context

<img width="862" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10331428/b8398a35-8814-4b12-8e26-f88f476ecab5">

### Visual documentation

<img width="862" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10331428/252d930a-4cfa-4590-87f9-166b88b82466">

### Environment

```markdown
- FlutterFlow version: I did have an update pushed out and installed today can't open App to verify #
- Platform: Mac OS Desktop
- Browser name and version: App
- Operating system and version affected: Mac OS Ventura 13.6.1
```

**Comment by agreaves** [comment]
Hi @kiwimagic, we are currently experience a partial outage due to a widespread Firestore outage. This is currently being resolved and we hope everything is working properly within a few hours.

We apologize for the inconvenience in the meantime.

**Comment by zetabrands** [comment]
Also running into this. Regular user on MacOS, suddenly came back to my desk and was just spinning. Also can't login on Chrome anymore.

**Comment by kiwimagic** [comment]
For future reference - this was not a FF "bug".  Google Firebase Auth went out globally for a number of hours. Confirming that I can now open the Web App. Issue was Firebase https://status.cloud.google.com/incidents/iRvJVnsbz8T47ySiy5Hg
