### ISSUE TITLE
Infinite loading and uncaught error in main.dart.js:3350 when accessing app.flutterflow.io

### ISSUE THREAD

**Issue by PaniSPejskem** [FlutterFlow/flutterflow-issues#1860]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When accessing [https://app.flutterflow.io](https://app.flutterflow.io)/{anything} (including base route), the webpage does not load and instead is loading indefinitely. As a result, I cannot access and use Flutterflow in any way.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/73820773/ea111308-2b90-4f77-83de-62db9f6f5e69)

### Expected Behavior

Flutterflow loads normally and shows Flutterflow UI after loading is finished.

### Steps to Reproduce

1. Access [https://app.flutterflow.io](https://app.flutterflow.io) and log in using "Sign in with Google" option
2. Complete login
3. Page after auth never loads

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

unable to access widget tree

### Context

Cannot access any Flutterflow feature or project

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/73820773/ea111308-2b90-4f77-83de-62db9f6f5e69)

### Environment

```markdown
- FlutterFlow version: cannot see
- Platform: Web, Windows 10 Desktop
- Browser name and version: Edge, Google Chrome
- Operating system and version affected: Windows 10
```

**Comment by fborgherodbsagency** [comment]
same here kicked off multiple times and now the FF interface is ot loading

**Comment by godarren** [comment]
Same for me, looks like there's an outage here reporting a small subset of users being affected, hopefully it's resolved for us too soon.

https://docs.flutterflow.io/flutterflow-status
https://community.flutterflow.io/c/bugs/post/we-are-currently-investigating-a-partial-outage-of-flutterflow-K6lo12DxN4p9P4e

**Comment by PaniSPejskem** [comment]
Today it is working. @SameerShahzad99  @joshua-ffio  based on @godarren  comment, it might be worth to point out that users should also check https://status.cloud.google.com/ when experiencing troubles, not only https://docs.flutterflow.io/flutterflow-status. Closing this issue
