### ISSUE TITLE
Missing Resources for iOS Code

### ISSUE THREAD

**Issue by cr4819642** [FlutterFlow/flutterflow-issues#1861]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When downloading code for an iOS project, and opened in XCode, the application cannot be built / run owing to 2 missing resources: Pods-Runner.debug.xcconfig & Generate.xcconfig
I can consistently reproduce this, even with a blank project.
Screenshot of errors attached.
![ff error](https://github.com/FlutterFlow/flutterflow-issues/assets/56320617/7f8fb8f2-eb15-4921-8e3d-f0f921430e4b)

### Expected Behavior

App should import and build in XCode.

### Steps to Reproduce

1. Download FlutterFlow code - even from blank project
2. Open runner for iOS in XCode
3. Build app in XCode - triggers errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkPHl8YxOj7wB1pDUK/lahiovIjs/bZI7l+txaCs8GZT0B4kcYs+kfklUOcfhS1VEJmGjrGAX/MrmveHPA/Q6AwycGJxeyc1AbAvdWnmlbKmVBoS3b3xCROdnG2qPyKer2hMkPtp2Wiwu3WeUftyiTgzcH4zEIUgvHuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I need to be able to bring into XCode for on device testing and submission.
Without this fix, Flutter Flow is effectively unusable for me and will force me to cancel my subscription.

### Visual documentation

screenshot of XCode error
![ff error](https://github.com/FlutterFlow/flutterflow-issues/assets/56320617/67ef32ff-e76a-4cde-a715-26e2ef6d3eae)

### Additional Info

![ff error](https://github.com/FlutterFlow/flutterflow-issues/assets/56320617/46734791-e859-4b8b-95ac-0c730e66c9fa)

### Environment

```markdown
- FlutterFlow version: 4.03
- Platform: iOS
- Browser name and version: n/a
- Operating system and version affected: Mac OS X Sonoma 14.1.1
```

**Comment by agreaves** [comment]
Hi @cr4819642, thanks for the bug report! For Flutter projects, you have to run `flutter pub get` and `pod install` (from the `ios` directiory) prior to opening it in XCode for there to be no errors present. This will populate all the necessary Podfiles and configurations for it to load properly.
