### ISSUE TITLE
WebView can't go back to previous webpage (Android)

### ISSUE THREAD

**Issue by kiwisoftapp** [FlutterFlow/flutterflow-issues#1863]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On an Android device, if you navigate to a page in webview, you cannot navigate back afterwards.

### Expected Behavior

You can go back to the previous website by swiping left on iPhone. On Android, it would be nice if the device's back button worked as well, or if there was a back button within the webview.

### Steps to Reproduce

1.Create a new page
2.Add WebView component
3.Set any URL
4.Navigate somewhere inside the webview

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflfLqx5BgobxY176Ja8JKiiYQJWEcTJMZjtZFewgjF774PLMuZOOlQBBWZMCzaHNEM2KLjlwJ/9bthvD9Jfk5CzWVGoRFwbl+dRPPbGOibJC6O83hQkYnJ+BjCkib56aFrB0nVLdoL0If7UzzGt6RRT2Cf9qOYwx5e6fDbOY=

### Context

A client's application opens a web page in webview. Users on Android devices cannot navigate back to the previous page within the webview.

### Visual documentation

![Screenshot_20231116-084556](https://github.com/FlutterFlow/flutterflow-issues/assets/144942255/a468b3a8-10dd-41b3-bacf-81e370d17373)

### Environment

```markdown
- FlutterFlow version: v4.0 (released November 15, 2023)
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by takashiff** [comment]
Hello @kiwisoftapp, thank you for your bug report. Unfortunately, this is a current limitation of the WebView widget in FlutterFlow. If you'd like, I can always put in a feature request for you internally. Thank you for your patience.
