### ISSUE TITLE
GBP (Pound value) decimal issue

### ISSUE THREAD

**Issue by DanMohaha** [FlutterFlow/flutterflow-issues#1864]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Considering a stripe integration, the data passed between FlutterFlow and Stripe is resulting in the decimal on the total payment amount being placed in the wrong place. This is a GBP (£) amount.

Upon checkout the decimal is in 2 points out. So the amount reads £ 2,50 instead of £ 250.00

### Expected Behavior

The decimal should be reflected as per the checkout amount

### Steps to Reproduce

1. Go to check out
2. Click accept and pay
3. See the decimal that is out of place upon Stripe connection

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzfLl8Y9Om7RJ+KnxLfp4jSgWGUMdXOczitVEew4bCIj4PIkyfeDORE9oXsSzaHNIHVGl/XkxwMLwvuDpKsA3OTqubJw/+rhQZRPPbFKVR6qzPs2oZmtPN8NUCm6O1MG4kB55Ns1YcU4X7DuTN9+ibz+Cf9qOYwx5e6fDbOY=

### Context

We are trying to ensure a reliable and accurate checkout. 

This is preventing us from launching and having users pay the correct amount

### Visual documentation

<img width="353" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/107678687/e1c1ce52-cfcb-4da6-85bf-edd8f72b3f9a">

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/107678687/3891323c-8d0a-4bc1-9ed8-624a2fc7e37e)

### Environment

```markdown
- FlutterFlow version: v4, 3,13,7
- Platform:MacOS
- Browser name and version: Chrome, Version 118.0.5993.117 (Official Build) (arm64)
- Operating system and version affected: Mac OS Ventura, 13.3.1 (22E261)
```

**Comment by hariprasadms** [comment]
Hi @DanMohaha - Thanks for submitting the issue. Have checked this note and configured the payment value accordingly?  

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a1feb528-d02b-4794-8113-205fd7ebb93a)

**Comment by smadds** [comment]
Maybe just rename the field label to "Integer Amount" to avoid confusion? If unclear to anyone it then prompts pressing the info icon!

**Comment by hariprasadms** [comment]
Thanks for a suggestion. I presume you have solved the issue. Hence closing the issue. Thanks
