### ISSUE TITLE
Can't update nested values in firestore

### ISSUE THREAD

**Issue by dwatrous** [FlutterFlow/flutterflow-issues#1866]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Nested values from a firestore document can be displayed in a page, but CANNOT be updated using the Firestore Update functionality.

### Expected Behavior

I would expect to use the Update Document action to save the values back to the datastore that were used to populate the fields on the page

### Steps to Reproduce

1. Create a page and add TextField (or similar) widgets
2. Use TextField Initial Value to keep traverse the document down as many levels as the values are nested
3. Add an action and choose Update Document
4. Click "+ Add Field"
5. Choose the first nesting level, click the orange "update <Data Type>"
6. Set Update Type to Set Individual Fields
7. Click "+ Add Field"
8. Choose the next level (which is an array in my case)
9. Instead of being able to identify the index in the array (which is set for the page and was used to populate the fields on page load), I see only "List Update Type". I am unable to drill down to choose the actual field inside the object in the array to update based on the current widget state.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi8mBx4dIoeEA1oSJbfpaqyQRH1wibZIzjspOEC0jF7KuBu0cfPfCSFhWZMuiaVNceEyakkkew+jnuODxIfoCKQutQIc/wZFhWAz0e2ihMsWYPruSVXElBeJYC1SB36azriJRJvdYSl4b3Tiqf+uWbBDDFOu/Zwh9f6PHaOI=

### Context

See https://community.flutterflow.io/database-and-apis/post/how-to-use-nested-array-in-firestore-to-populate-listview-and-save-to-zjqvmM5lg8Kz7L3
The first comment may also be a bug, but the second comment and screenshot show the specific details to this bug, which is that I can't update the fields that I can obviously see.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/8d4596b3-3cfe-42f8-8579-a1f16cfd579a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/aa0b651c-e6fd-4d27-8e92-d45503d7da55)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Android, iOS, Web
- Browser name and version: Chrome 119.0.6045.125 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

**Comment by elementh69** [comment]
Hey @dwatrous , i think that action called "read document" is that what are you looking for.
You can simply read specific nested document, save it in a variable within action chain and update it in later actions.
Let me know if i'm wrong.

**Comment by dwatrous** [comment]
@elementh69 I'm not sure I understand, but I did try going to the ListView element to add an action to Read Document. I can drill down as far as sprayoccurrences, but the Available Options don't allow me to return the whole list.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/4f0d3283-863b-4b4f-9da7-965e65d3d671)

Here are the options I get 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/a7da93f4-9a1a-4590-ba1c-ad611d6fed0b)

I would want to read all of them. Even if I choose "First Few Items", I get stuck here:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/8c0d129e-83b2-4a11-9d2b-6e4bd8d8c762)

It seems like there should be a way to do this in the UI, but something is breaking down in this case. 

A workaround (or solution) I found was to write a custom function

```
List<SprayOccurrenceStruct>? getSprayOccurrences(
  List<ZoneStruct> zoneslist,
  int zoneIndex,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return zoneslist[zoneIndex].sprayoccurrences;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

I can then list them as follows 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/320748/b3f2ff14-fda3-420b-993c-6d20aed7365e)

**Comment by elementh69** [comment]
Does sprayoccurrences have references? If so, try reading the document twice. Here's the suggested approach:
Read the zones document.
Based on the output from the zones document, read the sprayoccurrences document.

**Comment by victoriahuang1** [comment]
Hi @dwatrous , thanks for the report. Currently, only setting the value for entire lists for firestore documents is supported. 

> You can simply read specific nested document, save it in a variable within action chain and update it in later actions.

This suggestion is correct. The only thing is, the "Read Document" action expects the action output to be a Document Reference. That's why your attempt to use this action to retrieve the spray occurrences is failing -- it's a Data Type, not a Document Reference.

What you can do instead is:
- maintain either an app or page state variable of type spray occurrence (or list of them, depending on your use case) for your spray occurrence.
- add an action to update this state variable

<img width="635" alt="Screenshot 2023-12-21 at 8 38 01 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/e9137c1b-2865-4544-b7a4-510c3c465a97">
<img width="634" alt="Screenshot 2023-12-21 at 8 37 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/26f8f26d-f0e8-46dd-9936-998eed053acb">

Please let me know if this works for you.
