### ISSUE TITLE
Bug Firetore Setup - indexes and storage

### ISSUE THREAD

**Issue by ddiegosousa** [FlutterFlow/flutterflow-issues#1868]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When opening my project, errors appear in Firebase Setup.
Index and Storage problems.
When I try to run their deployment in the settings, "loading" appears, but it doesn't return anything and my project keeps showing the error.

I have already given the necessary flutterflow permissions in firebase

Follow the image in evidence
![error_flutter_flow](https://github.com/FlutterFlow/flutterflow-issues/assets/32843622/eaf673d7-a81a-491a-8c91-05fc40ee3f2a)

### Expected Behavior

Return solution problem urgent

### Steps to Reproduce

1. Open Project
2. Run Deploy indexes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Run

### Context

In the construction of the project

### Visual documentation

evidence is above

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Windows 10
- Browser name and version:Chrome  119.0.6045.160
- Operating system and version affected: Windows 10
```

**Comment by aemelyanovff** [comment]
@ddiegosousa Thanks for reporting the issue and sorry for the slow turnaround.

I'm unable to reproduce the issue - it appears to be specific to your FlutterFlow project and/or your Firebase project. Please reach out to FlutterFlow support for further assistance.
