### ISSUE TITLE
Video Widget plays in the background when navigating to different pages

### ISSUE THREAD

**Issue by Aewister** [FlutterFlow/flutterflow-issues#187]
## Expected behavior (required)
When navigating from a page with the Video Player widget to a different page, the Video Player widget from the previous page should not continue playing in the background.

## Current behavior (required)
When navigating from a page with the Video Player widget to a different page, the Video Player widget from the previous page plays in the background.

## To Reproduce (required)
From: https://app.flutterflow.io/project/linkall-eqwit7
1. Open app, start from home page (far left icon on the Nav Bar).
2. Click the '커뮤니티' page (second icon from the left on the Nav Bar)
3) Click '채팅' (Blue icon on the upper left of the page).
RESULT: Audio from Commerce page Video Player widget plays in the background.

## Context (required)
It is annoying and confusing for users when something from a previous page continues to play in the background.

## Screenshots / recordings
https://youtube.com/shorts/NPpLTS3O4bc?feature=share

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Browser name and version: Chrome Version 107.0.5304.121
* Operating system and version (desktop or mobile): Desktop, OSX, Monterey

**Comment by bulgariamitko** [comment]
This was already reported.

**Comment by aemelyanovff** [comment]
Duplicate: https://github.com/FlutterFlow/flutterflow-issues/issues/3
