### ISSUE TITLE
PWA manifest.json errors

### ISSUE THREAD

**Issue by smadds** [FlutterFlow/flutterflow-issues#1870]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The PWA manifest.json file contatains 2 icon descriptions, but links to the same uploaded icon file. It also reports them as type png whatever their format.

### Expected Behavior

Allow PWA configuration within FF UI - all aspects as currently assumptions are made for icons, colours and screen orientation.

### Steps to Reproduce

1. Enable PWA under web publishing
2. Inspect the manifest.json file

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not widget related

### Context

Frustration as not seeing icons and errors on manifest

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5259870/4431abf3-a7ab-4fbe-ac50-45b17967ddef)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Web
- Browser name and version:Edge
- Operating system and version affected: n/a
```

**Comment by kiwimagic** [comment]
@smadds thanks for logging. I agree re the manifest not being published correctly. I would like to add to your comment "currently assumptions are made for icons, colours and screen orientation"  that name/short_name is reflecting the project name which is not my "App display name" which "should" appear on users device when added to Home Screen. We need the ability to set this name that the user sees when adding to Home Screen and not default it from the Project Name which drives other technical related naming setups throughout. Currently FF App Details > **Display Name** is not applied in the manifest at all. This is what I would expect to see as the end users App name or the least the description they see when setting the icon on their come screen.  And specifically for my tablet focused App the screen orientation is essential to be able to set. In my case I need "orientation": "landscape-primary" currently all FF apps are set to this screenshot. Note: the background_color and theme_color are a color that is not even in my theme settings so unsure where that is populating from...? 
<img width="427" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10331428/ebd847a6-e2d3-4356-b99c-6503659d4b5b">

**Comment by smadds** [comment]
Totally agree with @kiwimagic . Just because it's not been fixed yet does not mean the issue should be closed!

Is there any way to manually edit the manifest until  proper gui solution is implemented?

**Comment by smadds** [comment]
any update on this, @hariprasadms , @takashiff ??

**Comment by smadds** [comment]
Again, is there any update on this, @hariprasadms or @takashiff ? 

I really need the PWA web app to work in portrait mode and nothing I try is working. How can we override the default PWA manifest settings?

**Comment by shefa** [comment]
Ping, this is affecting me as well - I'm trying to set up PWA but it is not happening because of the missing manifest file

**Comment by takashiff** [comment]
Hello @smadds, thank you for your bug report. Unfortunately, this is a current limitation of FlutterFlow, as there is no way to customize the `manifest.json`. I have put in a feature request internally to allow for customization of the `manifest.json`, since I do agree with you that this is something that should be customizable by the user. Thank you for your patience!

**Comment by shefa** [comment]
Please don't close as completed when it's not.
Where's the link to the feature request you've added?
@takashiff

**Comment by smadds** [comment]
Why did you close this, @takashiff ? The bug is still there as the system is still report incorrect sizes for images in the manifest.
It's still a current bug, whether or not there is a feature request to make it editable.

**Comment by VadymBoikov** [comment]
Very relevant as well! 
Is there any chance to know when this feature will be put to development?

**Comment by NiltonFelicio** [comment]
It's been 2 years since this was raised. I need to adjust the PWA manifest, I'm having the same problem. Any news on this? This is the basics of the basics, they included adjustments in AndroidManifest, Info.plist, estc and in a simple PWA manifest we can't change it without having to download all the code. Let's do the basics.

**Comment by smadds** [comment]
I see in the latest release you've added the "Ability to edit platform configuration files" - but only for Android and IOS platforms. Why not for Web too? Such a simple request and the system is still reporting false information on the manifest!

**Comment by NiltonFelicio** [comment]
@smadds Do they listen to us? They closed the problem without even solving it.
