### ISSUE TITLE
Run mode still loading

### ISSUE THREAD

**Issue by kaizenap** [FlutterFlow/flutterflow-issues#1873]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i want to use the **run mode** to test my app (Kaizenapp) , FF loading infinity and not finish the process of create a new run version... The bug was appears one day ago.

I test the run mode in another projects and worked well.

![Bug - Run Mode](https://github.com/FlutterFlow/flutterflow-issues/assets/151190932/7d5c3c9a-2c34-4345-9c0c-1917999f46b4)

### Expected Behavior

FF must to finish the the "new run version" and show me available the app to test it.

### Steps to Reproduce

1. Select "Run" mode
2. Click
3. FF opens a new window with the run mode versión loading
4. Bug: FF never finish the creation of the a new run mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjfLl5cl2obhY17X5bccwlmI4QlAmTL07ttYbZxUjIuPtBJh+Os7RSxBDTum4Y1NhHFaIhj0yp9GOit/fEfQFCxKWfYBB+ZNQZQ6VZ3q8Ra6oELi0eH8lO+5nIHaY0KeFgBN5BMRoS0Yl31z7HtyucC7tGZO/Zwh9f6PHaOI=

### Context

High priority: I can't finish my work.
![Bug - Run Mode](https://github.com/FlutterFlow/flutterflow-issues/assets/151190932/ae54c2cb-7c50-49df-9315-70b113a952e2)

### Visual documentation

![Bug - Run Mode](https://github.com/FlutterFlow/flutterflow-issues/assets/151190932/41f9d5c6-3657-4398-bd55-1983284dfac1)

### Additional Info

-
![Bug - Run Mode](https://github.com/FlutterFlow/flutterflow-issues/assets/151190932/eb074a53-2e53-46bc-9984-990dd2e7bfce)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by kaizenap** [comment]
![Bug - Run Mode 2](https://github.com/FlutterFlow/flutterflow-issues/assets/151190932/10b8eeaf-ae90-477b-8204-ea3251dd046e)

**Comment by hariprasadms** [comment]
Hi @kaizenap - Thanks for submitting the issue. Are you still facing the issue ?

Can you please add below details as well.

Whats happens in debug run mode ?
What happens in web run mode ?

**Comment by kaizenap** [comment]
Now is working, thanks you. The bug was fixed for your college Alex
Greaves. 🙌🏻

**Comment by GreatPika** [comment]
@hariprasadms I have the same problem after updating to mac os sonoma

**Comment by GreatPika** [comment]
Hi! How did you solve the problem?
