### ISSUE TITLE
Typo in Github Advanced Settings help text

### ISSUE THREAD

**Issue by PrenSJ2** [FlutterFlow/flutterflow-issues#1875]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

says performant

### Expected Behavior

performance

### Steps to Reproduce

Settings > Github > Advance Settings > ( i )

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

typo

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70067036/8a8b4714-c4ea-435d-9b7f-88087e6c3fe3)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
Hi @PrenSJ2 performant is actually a word, you can confirm that with the dictionary.

**Comment by PrenSJ2** [comment]
fair enough
