### ISSUE TITLE
App crashing on video playback (Android)

### ISSUE THREAD

**Issue by MyTechAgent** [FlutterFlow/flutterflow-issues#1876]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My app now crashes constantly on android but not on apple, this also doesn't happen in run or test mode. The google play console is throwing the below error and I think this could be the root cause. I have tried several different things but it seems like the connection between flutterflow and firebase could be losing connection somewhere in the FF backend. I am using mux and firebase which assisted me in narrowing it down to a bug with the ff videoplayer. I have also searched the community and found someone else having the same issue.

Error:

Exception java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/base.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/base.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.en.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.x86.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/lib/x86, /data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/base.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/base.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.en.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.x86.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so" at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java) at io.flutter.embedding.engine.FlutterEngineGroup.<init> (FlutterEngineGroup.java) at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java) at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java) at io.flutter.embedding.android.FlutterFragment.onAttach (FlutterFragment.java) at androidx.fragment.app.Fragment.performAttach (Fragment.java) at androidx.fragment.app.FragmentStateManager.attach (FragmentStateManager.java) at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java) at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java) at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java) at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java) at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java) at androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java) at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java) at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java) at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1391) at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart (MonitoringInstrumentation.java:2) at android.app.Activity.performStart (Activity.java:7157) at android.app.ActivityThread.handleStartActivity (ActivityThread.java:2937) at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:180) at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:165) at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:142) at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70) at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1808) at android.os.Handler.dispatchMessage (Handler.java:106) at android.os.Looper.loop (Looper.java:193) at android.app.ActivityThread.main (ActivityThread.java:6669) at java.lang.reflect.Method.invoke at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858) Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/base.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/base.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.en.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.x86.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/lib/x86, /data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/base.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/base.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.en.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.x86.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so" at java.util.concurrent.FutureTask.report (FutureTask.java:123) at java.util.concurrent.FutureTask.get (FutureTask.java:193) at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java) Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/base.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/base.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.en.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.x86.apk", zip file "/data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/lib/x86, /data/app/androidx.test.tools.crawler-QclQzO7e6qppwT-3CoLUgg==/base.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/base.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.en.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.x86.apk!/lib/x86, /data/app/com.EntwinedProduction.MeDoDare-2UG4pvW_Xhpse9lSDIUl7w==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so" at java.lang.Runtime.loadLibrary0 (Runtime.java:1012) at java.lang.System.loadLibrary (System.java:1669) at io.flutter.embedding.engine.FlutterJNI.loadLibrary (FlutterJNI.java) at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java) at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java) at java.util.concurrent.FutureTask.run (FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641) at java.lang.Thread.run (Thread.java:764)

### Expected Behavior

The video should buffer and than play back without closing out the app.

### Steps to Reproduce

1. create a new page
2. add a mux or another source video playback
3. play the video

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No bug is thrown on the flutterflow end

### Context

The team is very close to an official beta launch, which is how we picked this bug up on the android side.

### Visual documentation

https://community.flutterflow.io/troubleshooting/post/app-crashing-6HhW4a788hoeX9i

The user in the above post has already captured what is happening.

https://github.com/FlutterFlow/flutterflow-issues/assets/113911679/f60960b0-1f87-4e45-aecc-f63f2a1c6906

### Additional Info

no further information

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:android
- Browser name and version: Chrome
- Operating system and version affected: Windows 10
```

**Comment by Bar343** [comment]
Any word on this??? My app is video heavy, and this only started happening recently!  it's buggy in APK builds, and even worse on we build when running on device.

**Comment by MyTechAgent** [comment]
Hey,
This went stale because no one else had similar issues. I ended up not launching on android and only iOS as it is a vast difference in UX. I did some googling and it seems it could be linked to the backend packages being used for the video player. Seems the android dependencies / video player package is very outdated. 


Sent from Yahoo Mail for iPhone


On Saturday, December 30, 2023, 5:01 am, Bar343 ***@***.***> wrote:




Any word on this??? My app is video heavy, and this only started happening recently! it's buggy in APK builds, and even worse on we build when running on device.

**Comment by Bar343** [comment]
This makes sense.  Thank you for the reply.   Thing is I'm having issues
with web builds too. But again, only when viewing the site on Android...


Guess I'll open a new ticket if need be. Thanks again.

**Comment by hariprasadms** [comment]
Hi @MyTechAgent - Sorry for the delay in responding to the issue. Are you still encountering the problem? It's important to note that without essential details and a provided project bug report code, issues with incomplete information tend to have lower priority for investigation and may be skipped.

I recommend creating a blank project that replicates the issue, including all the necessary details, and provide the project bug report code for further consideration. This will enable a more focused and effective investigation. Thank you.

**Comment by hariprasadms** [comment]
HI - The investigation cannot proceed due to inactivity and missing essential details. Therefore, closing the issue. If the problem persists, kindly initiate a new issue and provide all necessary information. Thank you.
