### ISSUE TITLE
OneSignal doesn't work

### ISSUE THREAD

**Issue by Golicraft** [FlutterFlow/flutterflow-issues#1877]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Enter the details, error. 
https://community.flutterflow.io/integrations/post/onesignal-integration-not-working-vUUiqczXJJcZEGw

### Expected Behavior

It should be deployed. 

### Steps to Reproduce

Connect OneSignal with Flutterflow. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

https://community.flutterflow.io/integrations/post/onesignal-integration-not-working-vUUiqczXJJcZEGw

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11066952/fdb663c1-4f6a-43e1-aa56-39901a21df56)

### Additional Info

It's not an issue with me. The whole community experience the same 
https://community.flutterflow.io/integrations/post/onesignal-integration-not-working-vUUiqczXJJcZEGw

### Environment

```markdown
- FlutterFlow version: Newest
- Platform: Windows
- Browser name and version:
- Operating system and version affected:
```

**Comment by trevorFields** [comment]
same issue.

**Comment by jgardunojre** [comment]
experiencing the same problems, unable to deploy One Signal

**Comment by Golicraft** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11066952/3a961edb-acc0-49ec-9e18-67b646a37545)

I removed all custom code (the one I had for OneSignal), tried to deploy again and then it worked.
