### ISSUE TITLE
FlutterFlow and Firestore Queries - Usage Filter + OrderBy Problems

### ISSUE THREAD

**Issue by DataTeamITInternal** [FlutterFlow/flutterflow-issues#1878]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have a listview for a collection called Locations. Here we need to FILTER the data based on a tenantId which is a Document Reference and then OrderBy dateCreated. 

We create a query then add Filter 1 = locations.tenant EQUAL TO authenticated users.tenantId = WORKS
We then need to Order By locations "dateCreated" but cannot.

**FF accepts this and Firestore builds an index? Why** 

So we reviewed the Firestore rules which states your 1st Order By must match the context of your 1st Filter. So we did this.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16638707/ef4132ef-27da-4266-8e4b-3358c59e0766)

**According to this:**

https://stackoverflow.com/questions/68166318/the-initial-orderby-field-fieldpathid-true00-has-to-be-the-same

- Example Not Work: query: FirebaseFirestore.instance.collection('Phones').where('price',isGreaterThan:'560' ).orderBy('id',descending: true)
- 
- Example Works: query: FirebaseFirestore.instance.collection('Phones').where('price',isGreaterThan:'560' ).orderBy('price').orderBy('id',descending: true)

And we get this

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16638707/cc51cce4-effe-4119-ba62-67c4968e78bd)

### Expected Behavior

1. Creating a "Query" which is accepted by FF and also is subsequently generated in Firestore Indexes should work. It should not throw an error during testing. The query should work if its allowed to be created, 

2. Also warn the user, that Firebase often takes >3-4 min to generate the index so NOT to test until the firestore index is "ENABLED" by checking the status of the Index in Firebase itself. 

3. Maybe on FF documentation you could make 5 examples or so of FILTERING with ORDER BYs - Most of the docs are great but are extremally basic. This would save hours for each person.

### Steps to Reproduce

1. Create three collections. users, tenants and locations. In users and locations collections create a field named tenantId of type Doc Ref. 
2. Create a tenant record and grab the tenant doc ref, and insert into the users.tenantId and locations.tenantId
3. Create a page, add a list view. 
4. Build a query where you must GET locations where AUTHENTICATED users.tenantId IS EQUAL to locations.tenantId, then add ANY "Order By" from locations. As example ORDER BY dateCreated or even the tenantId itself.
5. Login as the user and open the view. You will see the error "The inital orderBy() field has to be the same as the where() field parameter"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhcqA5Yp1xMtJ7q6IKe5vuGM7JkccTIMziNZ+exUbfaL1BqQqY8j8QBBWTte9aVNfeGG0rE8HwtXGvuPxJ/QnHw6sQKZPzcx6TAL0e2i7R4ioEZaCdX9RJ8pPC1SG38GrvAokIulYdVYn72D7H+e/dADDFOu/Zwh9f6PHaOI=

### Context

We are trying to use FF for enterprise level applications which are all multi-tenant. Every query contains filters 1st by tenantId and then by a subsequent one. 

** We simply need to query data with a min 2 filters and 1 order by ** 

### Visual documentation

**1st Image** is the FF application and the query - and errors which show based on rules == and IN which are not in line with Firestore

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16638707/674c500e-4675-47f4-ab59-3aadc8d8f8e4)

**2nd Image** is the debug view of the Page/Listview based on a FF accepted Firestore Query & Index 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16638707/7ef8303f-7c2e-4169-bba2-2a835188f90c)

**3rd Image**  is 3 index's generated by FF - Where we tried to use the "Query UI" Filter 1/Order By 1 and have unexpected results.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16638707/c3170dd3-27a5-4fe4-937c-dc5f5a03e31e)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.160 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro, 23H2 - OS Build 22631.2715
```

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!
