### ISSUE TITLE
Reverting Changes to Custom Widget Code - Won't Let Me Save New Code

### ISSUE THREAD

**Issue by will4381** [FlutterFlow/flutterflow-issues#1879]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've been using ChatGPT to generate code and copy and pasting back and forth. Now currently the old widget code which is 153 lines when I select all and replace with new code, 143 lines. It doesn't appear an option to save, only upon selecting exclude from compilation, the save button appears but upon clicking it, it reverts the new code back to the old ie the 143 lines block to 153 lines. The code compiles correctly. 

https://drive.google.com/file/d/1oTTPVxXlbqEEtp9m8EBIzRn5hJfw-8oQ/view?usp=sharing

### Expected Behavior

I expect when I paste new code into custom widget code section for me to be able to save it and it not revert back to prior code.

### Steps to Reproduce

https://drive.google.com/file/d/1oTTPVxXlbqEEtp9m8EBIzRn5hJfw-8oQ/view?usp=sharing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khc/1z892xPVA7rrtbflVlWEsKWU3TL03pu0bFEggGLbrBIYMacjRdhZoXbDnYAk2KEWGuGAC096Jv4fiFfoFCwWCfYhez8xTWwryRl2/aoS2DKq3OXJ6QO9mGmnF5Lu3qhVSIvRYdU5n2E+ECuyucDbsJ7H4Zwh9f6PHaOI=

### Context

Trying to update a custom widget cant do it anymore. Halts my production

### Visual documentation

https://drive.google.com/file/d/1oTTPVxXlbqEEtp9m8EBIzRn5hJfw-8oQ/view?usp=sharing

### Additional Info

Tried on different browsers, mac app, and clearing cookies the issue still persists.

### Environment

```markdown
- FlutterFlow version: Flutter Flow 4.0 Flutter Version 3.13.7
- Platform: Web
- Browser name and version: Safari Version 16.6
- Operating system and version affected:  macOS Ventura 13.5.2
```

**Comment by ScreenClub** [comment]
have this same bug. Keep correcting the bugs but whenever I save, and reload project, it reverts the changes of the custom action
