### ISSUE TITLE
CheckboxListTile state change is delayed

### ISSUE THREAD

**Issue by dhust** [FlutterFlow/flutterflow-issues#1880]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to get the current state of the Checked Items from the CheckboxListTiles, but I keep getting the previous state instead of the current state after choosing a value from the dropdown.

When I choose a value from a dropdown, it updates a `Column `that contains `CheckboxListTiles`. For instance, I have two courses in a dropdown. If I choose `StudentsA `from the dropdown it will show 3 students. If I choose `StudentsB `from the dropdown it will show 4 students. This all works fine.

The problem is that when I try to read the state of the `Checked Items` it doesn't display, through a `Snackbar`, the correct number of items that are checked. Here is what I have setup:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2567117/94f3117b-b26a-4600-81eb-2dceb440e5ff)

I have 3 App States setup: `StudentsA`, `StudentsB`, and `selectedStudents`. If I choose `StudentsA `from the dropdown, then `selectedStudents `will be set to `StudentsA`, likewise for `StudentsB`.

I have a `Column `that contains `CheckboxListTiles`. This column is `Generating Children` from the `selectedStudents `app state. The problem is that if I show a `Snackbar `of the number `Checked Items` after choosing either `StudentsA `or `StudentsB` for the first time, then it will show `0`, but it should be showing `3` for `StudentsA `or `4` for `StudentsB`. If I add a `Wait `of 1000ms, as shown in the image, after setting the `selectedStudents `to either `StudentsA `or `StudentsB`, then it will show the correct number of students in the `Snackbar`.

In summary, if I choose a value from the dropdown, then the `Snackbar `shows the previous state of the number of `Checked Items,` but if I had a `Wait `of 1000ms, then it shows the current state instead.

### Expected Behavior

The `Checked Items `should be providing, in the Action's Tab, the current state of checked items in the list as opposed to the previous state.

### Steps to Reproduce

1. Create 3 app states: **A**, **B**, and **Selected**.
2. Add 3 students to **A** and 4 students to **B**.
3. Create a `Dropdown`, a `Column`, and add a `CheckboxListTile` in the `Column`.
4. Add two options to the dropdown: **A** and **B**.
5. `Generate Children` in the `Column` based on the **Selected** app state.
6. Add a `Conditional Action` to the dropdown.
7. This conditional action should set **Selected** to either **A** or **B** based on choosing either **A** or **B** in the dropdown.
8. Show a `Snackbar` after the `Conditional Action` to show the `Number of Items` in `Checked Items`.
9. Test the app by choosing **A.** The `Snackbar `should show a 0. Then choose **B** and the `Snackbar `should show 3.
10. Now add a `Wait` of 1000ms before showing the `Snackbar`.
11. Test the app by choosing **A**. The `Snackbar` should show a 3. Then choose **B** and the `Snackbar` should show 7.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcr135VNxMdG0b6IKMFF+T4XQlscTIMziNZ+exUbfaL1BqQTOszRMhZDUs+naVNcGlL8uEME3M7GiOGSC/c6BwWabIhD1rl+SgHOe2iVWqq3CZeeXWtBGe5UIGKC5raFvBN+XLJvV14Z11+EJt6+Sj7DFOu/Zwh9f6PHaOI=

### Context

I'm trying to get the current state of the Checked Items from the CheckboxListTiles, but I keep getting the previous state instead of the current state after choosing a value from the dropdown.

### Visual documentation

https://youtu.be/KXqu_EIYXh0

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 119.0.6045.125
- Operating system and version affected: Windows 10 Home 22H2
```

**Comment by victoriahuang1** [comment]
Hi @dhust thanks for the report. This is actually not a bug, but the expected behavior.

What you are noticing is the result of maintaining state in 2 different places: you are trying to maintain the state in 1) the action chain you have linked, but also 2) the `CheckboxListTile` itself maintains its own state.
When your action chain updates the state, this change in state is not immediately reflected in the `CheckboxListTile` (since its own internal state was not updated by the action chain). So what happens is the `CheckboxListTile` is only updated later, when it is rebuilt _after_ the change in the action chain has already occurred.

To fix your issue, consider maintaining state in only 1 place -- like using the "On Toggled On/Off" action triggers to directly keep track of what is being checked.
