### ISSUE TITLE
ListView Page Size not being honoured for Query Collection

### ISSUE THREAD

**Issue by Hypersight** [FlutterFlow/flutterflow-issues#1881]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Created a ListView and set a backend query setting it to a Query Collection. A collection of documents are created in Firestore Database, these documents just have one string field called 'name". Back in the ListView, select a collection just created in Firestore (for our purposes here, there should be more than 3 documents).  Query Type is set to List Of Documents and there are no Filters or Order by clauses. Enable Infinite Scroll and set the Page Size to 3. Inside the ListView, a simple text widget is added and set to the "name" field of the document. When the page loads, the ListView shows all records. The ListView is set inside a Container, the Container width is infinite and the height is 200px. The Text widget font size is set to 18.

### Expected Behavior

When the page loads, I would expect the ListView widget to load the first 3 documents, upon scrolling to the bottom of the ListView, I would expect a loading widget to load and the next 3 documents to load and so on.

### Steps to Reproduce

1. In Google Firebase, create a Collection and inside that Collection create 9 documents. In each document create a String field called "name" and enter a random name in each document
2. Create a blank page in FlutterFlow
3. Create a Column and set it to not scroll and to Expand
4. In that Column create a Container, set the width to Infinite and the height to 200px
5. In that Container create a ListView
6. In the ListView, create a Backend Query and set it to Query Collection
7. For the "Query Collection", select the Collection you created in Firestore and set the "Query Type" to "List of Documents"
8. Enable the "Enable Infinite Scroll" option
9. Set the Page Size to 3

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelsn1z4pNj71H7qn2asJ4mQMwJ0QlUIInj+0bWRMhfJCvE7AIOsj8R1tLYtfjeVZ6AWL+jj40+MKOkfHXDuw7EE2YRapqzoRXQQrgcFuXbpiqEKqWXHwmO/tXCn6Z3KSzgBNTJtBZZUIZ2meqOvCrG3qCf9qOYwx5e6fDbOY=

### Context

I wish to set a Container with a fixed height that I can scroll 100's of Documents infinitely if needed, 3 documents at a time. To do this, I chose to create a fixed height container and use a ListView with Infinite Scrolling and setting the Page Size to 3.

### Visual documentation

A video of the issue can be viewed here https://youtu.be/RQjQ19ythcE

### Environment

```markdown
- FlutterFlow version: 4.0 (Flutter 3.13.7)
- Platform: MacOS 
- Browser name and version: Chrome 119.0.6045.159 (Official Build) (x86_64)
- Operating system and version affected: Sonoma 14.1.1
```

**Comment by Hypersight** [comment]
It should also be noted that I have looked at fixes for this issue based on this prior issue https://github.com/FlutterFlow/flutterflow-issues/issues/1231
The suggestions here do not help my problem. The parent container has a 100px Height and Max Height set and the ListView has Shrink Wrap disabled. Still, all documents from the collection load when the page loads.

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!
