### ISSUE TITLE
Custom Code Errors are not easily scrollable and cannot be copied

### ISSUE THREAD

**Issue by dryprogrammer** [FlutterFlow/flutterflow-issues#1882]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom Code Errors are not easily scrollable and cannot be copied to the analyzed in another program. A low hanging fruit would be to add a “Copy to Clipboard” button to copy all the errors to the clipboard

### Expected Behavior

“Copy to Clipboard” button to copy all the errors to the clipboard

### Steps to Reproduce

1. Create custom code with lots of errors
2. Open and try to interact with the Custom Code Errors window

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gjMmB24VgobRd+Kr2KMAxniYXIjsla+cvjsN+dwEaIuPnPad3OuDRbhFBOMyBa21AI1qZkmYypuDUhIfDD8IoAw+sRog93JVqSzzgbEmmWoyaELjhYnFBHe5MFUy84LujkRRGA+Fac0YX21+Mf+zLVgXrJIzQOEUNLv7+DIP+j169Lh/JGidHwSsXJR7eTI5ODEz25eKMrop5yfj/0w==

### Context

It slows down checking errors. I wanted to send it to ChatGPT to speed up debugging

### Visual documentation

![Screenshot from 2023-11-19 11-53-56](https://github.com/FlutterFlow/flutterflow-issues/assets/40515415/16855ffb-b8db-4216-b83e-1cf09b685a07)

You can use this public project as a starting point
https://app.flutterflow.io/project/lots-of-custom-code-errors-y0hw3b

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.88
- Operating system and version affected: Ubuntu 22.04.3 LTS
```

**Comment by hariprasadms** [comment]
Hi @dryprogrammer, I looked at your project and CC errors. I can scroll and copy error lines. Are you still experiencing the issue ?

**Comment by dryprogrammer** [comment]
Are you able to copy all the errors at once?

**Comment by hariprasadms** [comment]
It does not work that way. Each error details are list tile items so it should be copied individually.

**Comment by dryprogrammer** [comment]
@hariprasadms When there are more than 10 errors, where some are related to each other, it's not practical to scroll and copy each error. For any serious custom code, this is a show stopper and often even breaks the code download for local troubleshooting. Therefore, please expedite this as a bug. I even tried scraping the error messages but it's not possible, maybe because of CanvasKit
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/40515415/e1fd2a66-b103-4ec8-85d8-fb0a1ef251f8)
