### ISSUE TITLE
Custom function return type in condition error

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1883]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you use a function with a return type of Integer then the return type is recognised (correct):
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/9a9d71fc-4de1-46d9-96f0-65653f2ffd61)

However, if the same function is then given a parameter of a string, then the return type of the function is ignored and the return type is fixed as a string (incorrect, as the function stills returns an integer):
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/429a438d-6fe2-41c9-9af0-c3a0e4b74674)

### Expected Behavior

The return type of the function must be honoured as an Integer regardless of what parameters the function has.

### Steps to Reproduce

1.create a function with no parameters, and return type of Integer
2. add a button with the single condition, the first argument being the custom function (it is recognised as a integer)
3. amend the function with a parameter of a string
4. add a button with the single condition, the first argument being the custom function (it is recognised as a string -- incorrect, the return type is still an integer)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

failed to generate

### Context

simple conditional action on the result of a custom function

### Visual documentation

as above

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - Thanks for submitting the issue. 

I did try the steps mentioned above but not able to reproduce the behaviour what you are seeing. If you still experiencing the issue, setup the steps in a blank project and share the project bug report code with us. Thanks
