### ISSUE TITLE
Compile issue about infinite_scroll_pagination

### ISSUE THREAD

**Issue by hankquan** [FlutterFlow/flutterflow-issues#1884]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have compile issue with package paged_vertical_calendar: ^1.1.6
It worked, but cannot work few days ago after new release of flutterflow.

The compile error is 
"Error: Failed running flutter pub get...
Because paged_vertical_calendar >=1.1.2 depends on infinite_scroll_pagination from hosted and custom_widget depends on infinite_scroll_pagination from git, paged_vertical_calendar >=1.1.2 is forbidden.
So, because custom_widget depends on paged_vertical_calendar ^1.1.6, version solving failed.
"

### Expected Behavior

Compile should pass.

### Steps to Reproduce

1.create a custom function
2.add dependency paged_vertical_calendar: ^1.1.6
3.check if it works

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okPHlz4xNobhe+KqJdcFV9CQvOVg9ROYzj8pBazwbfe+uB4kqevfOTERvTteodG9EJGaJnWoW0vDrhoT9EvQqGzqrc6pdwahPVTvJeDuiM66IFJWgdHNDP8ZVGUie17anmx5BC/hsSkY86mCuPOu9RXPtCb7VDEgSDq/LZO4=

### Context

It just cannot work but worked before.

### Visual documentation

custom function compile error

Error: Failed running flutter pub get...
Because paged_vertical_calendar >=1.1.2 depends on infinite_scroll_pagination from hosted and custom_widget depends on infinite_scroll_pagination from git, paged_vertical_calendar >=1.1.2 is forbidden.
So, because custom_widget depends on paged_vertical_calendar ^1.1.6, version solving failed.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released November 15, 2023
- Platform: APP
- Browser name and version: Edge 119.0.2151.72 
- Operating system and version affected: macos 14.1.1
```

**Comment by victoriahuang1** [comment]
Hi @hankquan , thanks for the report. We will be bumping up our `infinite_scroll_pagination` dependency to the latest version, upon the next deploy.

Unfortunately, it doesn't look like your `paged_vertical_calendar` package is compatible with the latest `infinite_scroll_pagination` version. At this time, we don't have a way of supporting both `infinite_scroll_pagination` and `paged_vertical_calendar`. We recommend you to look for packages that are compatible and to replace `paged_vertical_calendar`.

Sorry for the inconvenience.
