### ISSUE TITLE
Impossible to access to an active item page on a PageView with query collection infinte scroll enabled

### ISSUE THREAD

**Issue by MickaLamotte** [FlutterFlow/flutterflow-issues#1887]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the Discover Section of my app, I have a PageView with a query collection on all posts of user. I have check the infinite scroll option on the query to allow me to scroll all over the post.
In the onPageSwipe action, when I try to access to the item info, it's never appear. I can't have access to my active page info and I can't play the song of the posts.

### Expected Behavior

In my Discover section, I want a PageView with a querycollection with infinite scroll option activated that allow me to access to the active page information in the onPageSwipe Action. That allow me to access to an url of a sound to play each time user scroll to the next page.

### Steps to Reproduce

1. Create a new page with a PageView
2. Query a collection on that PageView and enable the infinite scroll option.
3. Enter in the onPageSwipe Action on the PageView Widget
4. Try to access to the active item shown by the PageView Widget.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEei8mAsJRJpbwD7pf1LcZWmQMwJ0gnU+crte5+d0shfZTpPZkDduP7aRdLYte+e31APmCihk8x/8L4veH9NfkCOk+rRYhCwYRXQQzjXmC7SrXQBc+ofXFBO9pYGXbF4bSCkRBSG7BhLVI4w07zDPCNG3qCf9qOYwx5e6fDbOY=

### Context

In my infinite scroll page view I want first a pagination which will improve performance of my discover feature. Secondly, I want to have access to the item info because when user scroll to a new page, this page have an url song that I want to play immediatly on page swipe. Without that, my section is just useless.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130373763/2d20caa9-664d-4e6f-ba11-49ece1d02c9f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130373763/68cd3283-a81b-4ecb-83a3-aa12bf332d98)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Sidekick 114.49.1.34655
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!
