### ISSUE TITLE
Checkbox's initial value doesn't work

### ISSUE THREAD

**Issue by gymeney** [FlutterFlow/flutterflow-issues#1889]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Снимок экрана 2023-11-20 181757](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/b6138747-b1d5-4c44-b8e7-888435d624de)
1) page state variable initCheckbox01 = true
2) initial value for CheckboxListTile 1 = initCheckbox01 (should be true)
3) But CheckboxListTile 1 = false
CheckboxListTile 1 != initiCheckbox01

### Expected Behavior

CheckboxListTile 1 = initCheckbox01 = true

### Steps to Reproduce

1. Created page
2. Created page state variable initCheckbox01.
3. On Page Load Action Update State Management is created. initCheckbox01 is set as true
![Снимок экрана 2023-11-20 210754](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/94f64591-320e-4184-90ae-f1571278497f)

5. Added widget CheckboxListTile with initial value from initCheckbox01
![Снимок экрана 2023-11-20 181927](https://github.com/FlutterFlow/flutterflow-issues/assets/59705169/3ebf93bd-cad4-4801-9b45-7e22412a3c5c)

6. Added widget Richtext with value from  initCheckbox01.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lcr135VNxMdG0b6JKflagmA5Jn03UOY40sBraCIofbLyB+wyZs+lbm9tUsvieHxiOlmY8Do0/vTJuNrlCMAXPiiBQbZxzJNyUxXvZF+gboysDLqCdEBQGZ5XGFOHzbSo3CJBOth2cVZh3V+QJfC8Zz3qNuPMOm47L8mHJZD7nE7mHDLOXn0Jg1ZSfCvr

### Context

CheckboxListTile is used in form for updating document. And it's necessary to output value from document in checkboxes. 

### Visual documentation

All images are in previous blocks

### Additional Info

There is the similar issue for initial value of slider.
See here https://github.com/FlutterFlow/flutterflow-issues/issues/1820

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Google Chrome Version 119.0.6045.124 (Official), (64 bit)
- Operating system and version affected: 
Windows 11
Version	10.0.22621 installation 22621d:
```

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This looks to be intended behavior due to how page loading interacts with widget rendering. Instead of updating page state, I would suggest setting an initial field value for your local page state variables. If you encounter any other issues, please feel free to make another bug report.

**Comment by DiegoteWhite** [comment]
When you assign the value to checkbox01, you should also update the checkbox widget.  Use the SET action.

**Comment by Karthikaddagalla** [comment]
@DiegoteWhite  Hey can please explain what do you mean by SET action ?

**Comment by DiegoteWhite** [comment]
On page load, add a SET FORM FIELD action and update the Checkbox.

![IMG-20240414-WA0017](https://github.com/FlutterFlow/flutterflow-issues/assets/115485184/96e4080e-33c8-428a-af3f-ec80aa3798f3)
