### ISSUE TITLE
In test mode, a container is missing on one of my pages and one of the fonts is incorrect

### ISSUE THREAD

**Issue by jacobsimons7** [FlutterFlow/flutterflow-issues#189]
Expected behavior (required)

When I run test mode, I expect the fonts to match exactly to what I built and I expect all the widgets that I built to be visible and laid out how I built them.

 Current behavior (required)

When I run test mode, one of the main headings is showing in a different font to what I built and one of the containers I built is missing which is leading to the container next to it being in the wrong position.

To Reproduce (required)

1. Create new page
2. Add 1 row
3. Add a stack into row 
4. Add two containers ontop of each other into the stack
5. Add text into each container
6. Set the colours of each container to slightly different colours from each other
7. Set conditional visibility for each of them based on a boolean local state. One appears when it is true and the other when it is false
8. Set actions for each of them - when the visible container is tapped, it changes local state to True so that the invisible one will appear. When the invisible one appears and then is tapped it clears the local state so that the original visible container appears
9. Set the one that is invisible on page load to be hidden in UI builder
10. Copy and paste this entire stack into the same row
11. Copy and paste the row twice onto the page so that there are now 3 rows in the page, each with two stacks in and each stack has two containers in
12. Set up an additional 5 local states based on boolean and replicate the conditional visibility logic and actions on each of the containers. Each of the 6 stacks in the page will now relate to a different local state
13. Add headings into the page with a custom font
14. Run test mode and see one of the headings in wrong font and and one of the stacks with each of its containers missing

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1.
2.
3.
4.

### Bug Report Code

When I try to do this it says bug report code failed 

## Context (required)

It's prevented me from having the correct onboarding flow. I am building an investment backed app for a friend, trying to convince him to have it built in Flutterflow rather than coded by developers and this issue is making him doubt Flutterflow.

## Screenshots / recordings

<img width="409" alt="Screenshot 2022-12-03 at 08 25 25" src="https://user-images.githubusercontent.com/119720981/205426191-a758b95a-4c1d-46e7-9005-210342660b32.png">

The above photo shows what the app page looks like in the UI builder and the below page shows what it looks like in Test Mode. Please note that in this most recent test mode the fonts are all showing correctly but in the last test mode they weren't. I have changed NOTHING between test modes

<img width="409" alt="Screenshot 2022-12-03 at 08 44 39" src="https://user-images.githubusercontent.com/119720981/205426267-fb959ae5-2230-4313-ab6d-e9dd67215c30.png">

## Your environment

* Version of FlutterFlow used: V3 - 3.3.4
* Platform Mac
* Browser name and version: Google Chrome
* Operating system and version (desktop or mobile): MacOS 11.6.8

**Comment by Pepino-GR** [comment]
Hi jacobsimons7,

I've tried to reproduce it with the actual version v3.0 December 9,2022 but cannot do so. If it is possible, please share the run version or share a test project to the public.

**Comment by aemelyanovff** [comment]
Closing the issue as inactive. @jacobsimons7 please feel free to reopen if you add more details.
