### ISSUE TITLE
Alignment & Screen Resolution Issues in Test Mode

### ISSUE THREAD

**Issue by sujitbellary** [FlutterFlow/flutterflow-issues#1890]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Even though the screen resolutions are same in different desktop systems/laptops, I'm facing an alignment issue (causes overlap or may be pushing of content to next line) in screen designs when ran through test mode.
![FlutterflowIssue1](https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/6f6d4426-9f82-4115-b2ee-1a20082212c1)
![FlutterflowIssue2](https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/774a42e8-b169-43cc-a552-d0a684ee9fcd)

https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/4b6830da-f88e-4969-9a4d-7e11b8c3d1b4

### Expected Behavior

There shouldn't be any discrepancies or any disorder in alignments (causes overlap or may be pushing of content to next line) of the screen design in any desktop systems when the screen resolution is same in the test mode (May be responsive too).

### Steps to Reproduce

1. Create a new page.
2. Add a two or more texts in a row with any font size.
3. Run & test it in different desktop systems.
4. Observe that there is an alignment or may be a padding issue which causes overlap and pushing the content to the next line.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wj8nqy4ZOxddd7ZD+c8Ixmic4GDslargwlephTis9CZDoOu9/ffekblhoZNTgYFNhHGClnlICwcroiPLtLe45CwuuG4Rl1qtIUhbKf3q8Ra62PZCJdXF8Df5YJ2qj5J7UoRZBPtRacV4R11+UHO6iSh7dN5u/Zwh9f6PHaOI=

### Context

So far, this issue has caused an overlap or may be pushing of content to next line leading to no proper alignment shown in test mode when checked on different desktop systems. I'm just trying to accomplish an app.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/f016c668-8a3f-4731-8ae6-80aff6491caa

![FlutterflowIssue1](https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/d6680ff9-00f5-42c6-b720-49c3b3d8fb2a)
![FlutterflowIssue2](https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/0f86eca4-cacf-455f-af8e-09c00d7fe72d)

### Additional Info

Please take a look at the text "CREATE YOUR ACCOUNT!" in different desktop systems.

https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/6d9e68e9-944e-4686-8bd3-f9423e6eb11b

![FFI2](https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/410fb9da-527d-479a-aaa2-c1d575275910)
![FFI1](https://github.com/FlutterFlow/flutterflow-issues/assets/113446745/963aedc4-eb02-4315-a769-04f9870f99c2)

### Environment

```markdown
- FlutterFlow version: v4 (released Nov 21, 2023)
- Platform: Windows Desktop
- Browser name and version: Microsoft Edge 119.0.2151.72 & Chrome 119.0.6045.160
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @sujitbellary - Thanks for submitting the issue. I have tested the above steps but not able to reproduce the issue. 

Are you still facing the issue ?

**Comment by hariprasadms** [comment]
Hi @sujitbellary - There is no response about issue status. I presume issues has been resolved for you. Hence closing the issue. Thanks
