### ISSUE TITLE
The TextField created as a component appears repeatedly in the Set Form Field action. The others do not appear.

### ISSUE THREAD

**Issue by annaisdevk** [FlutterFlow/flutterflow-issues#1891]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a TextField as a component:
![component_textfield](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/188f1e26-49d8-4beb-ae4b-de456bdf35c1)

A page contains + 1 of this component. To distinguish them on the page, each one has its own name:
![textfields_form](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/48e8778d-ab3d-41e5-9260-bdc41266a097)

If you want to read the value of one of these TextFields, through Widget State, they appear correctly differentiated and you can get the value of each one. This is correct.
![widget_state](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/b106447c-5d43-45ba-b39a-cfe3c05b0fbd)

**BUG:** 
The problem is when you want to set a value using Set Form Field action. Not all TextFields are displayed. Only 1 appears and it appears repeatedly.
![repeated_textfield](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/695c8dc1-7f5a-4b2d-a01d-2e97e7d9da78)

### Expected Behavior

In 'Set Form Field' should appear each of the TextField that contains the page. In the same way that they do appear from Widget State.

Expected:

![EXPECTED](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/508d0aff-e74b-4e6c-8ad0-684ace33d34b)

### Steps to Reproduce

1. Create a new Component
2. Add a TextField in this Component
3. Then create a new page and add this component to it +1 time, and set a custom name for each of them.
4. Create a Set Form Field action. You will see that only 1 TextField appears and repeats.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gz/Hq4c9goddA7qrAcu9VgiYXKUg5a7grl+tqEAgafJSvBI13d/elXBFVZOqBa21AI1qZkmYypuDUhM7xG8c7EweVb65l3JVqZwuUfE+XVYyJDLmRdXFfGcdPf26Y0MKg3AlsA+FsdCEY7V+mAee9Tj3UNITQDXovRcmaOqH4p0qYAh3rGzpU4yoXJR7eTI5ODEz25eKMrop5yfj/0w==

### Context

I have TextFields  that I want to reuse on different pages and not have to repeat the same settings and actions each time. For this reason, I created the TextField as a component.

This problem makes it impossible to set values for the text fields.

### Visual documentation

The screenshots are attached to the previous messages describing the problem.

### Environment

```markdown
- FlutterFlow version: v4.0 released November 21, 2023
- Platform: Web
- Browser name and version: Chrome 119.0.6045.160
- Operating system and version affected: Windows 10
```

**Comment by elementh69** [comment]
As seen in the first screenshot, there is a widget named 'TextField' within your widget tree. If you can find a way to dynamically rename it, it should appear correctly in actions as you expect.

**Comment by takashiff** [comment]
Hello @annaisdevk, thank you for your bug report. As @elementh69 has stated above, the names are based on the widget name. If the issue persists, please feel free to follow up in this thread so that it can be reopened.

**Comment by annaisdevk** [comment]
@takashiff  It is not a problem with the names. It is a problem with the custom components added to the page and how FF gets them.

If we look at the code, they are correctly differentiated:
![2024-02-04_19h17_11](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/7e3864f5-4329-440c-b652-e50336b18d7a)

And it works fine when it comes to reading their values. The problem occurs when you create the **Set Form Field** action and FlutterFlow lists the widgets compatible with this action. There should be listed the 3, but only 1 of the 3 appears and repeatedly. Note that it is not a problem of names, it is that **it always gets the same component**. 

To check it, assign a value to each of the components that appear in the Set Form Field and you will see that it is always the same:
![2024-02-04_19h13_57](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/16580eb6-eafd-45ec-aaa0-3f8233328b74)

**Comment by annaisdevk** [comment]
@leighajarett  @takashiff  Can you check this bug again? it is obvious that it is a FlutterFlow bug, because from VSCode I can normally access the components by their names. 

For example:
![2024-02-23_21h02_09](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/aa822243-9eab-4726-a2f6-9e423fbd9660)

![2024-02-23_21h03_18](https://github.com/FlutterFlow/flutterflow-issues/assets/98616090/17f4d773-a83b-4ebe-bbf0-dc335e46c683)

**Comment by itwrites** [comment]
Having the same issue , it's a bug in FF
