### ISSUE TITLE
Problem on the MapPage with the TabBar icon color options

### ISSUE THREAD

**Issue by sergevb** [FlutterFlow/flutterflow-issues#1892]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 I cannot open the options to change the color of the tabs icon.

### Expected Behavior

Everything is explained in the screenshot 😉 
<img width="1261" alt="Screenshot 2023-11-21 at 18 47 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134484327/8b5cbffc-b383-49f1-88cd-18c77a2afd79">

### Steps to Reproduce

1. Create a blank page
2. Add a TabBar widget to the column
3. Add an icon on a tab
4. Try to access the options 
<img width="863" alt="Screenshot 2023-11-21 at 20 38 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134484327/441cc611-7f7b-4a70-bf36-e6186df2bb0a">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grv1J0M/MY8ZAhR0jNkwmUecz0+1xewA2B5zyGbYUQ//8blVDQsCrYG1UIWD9pEYKpujwiNnPNfYGPh6ZboA4wZFqaAHwUmSgVKaRDqm8VXdQP+JPJ26GyLbYuwkkKbZ2aClpig/GSw==

### Context

I need to define a color via an App State (EventColor) as in the menu here available for the Label.

<img width="721" alt="Screenshot 2023-11-21 at 20 43 17" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134484327/a9cc9ca1-f06e-48f5-99be-fea260d18c68">
ab.

### Visual documentation

<img width="1261" alt="Screenshot 2023-11-21 at 18 47 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134484327/82c13a96-d0b6-4c26-b64b-657097822e54">
<img width="863" alt="Screenshot 2023-11-21 at 20 38 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134484327/fbe3edca-1c38-4c89-981d-2e2ce3b40aac">

### Additional Info

/

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released November 21, 2023
Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome version 119.0.6045.159
- Operating system and version affected: Mac OS Sonoma 14.1.1
```

**Comment by SameerShahzad99** [comment]
@sergevb Thank you for reporting this bug, i am able to reproduce this on my end!

**Comment by victoriahuang1** [comment]
@sergevb thanks for the report. This should be addressed once the fix is deployed.
