### ISSUE TITLE
Drawer is adding left margin/padding automatically

### ISSUE THREAD

**Issue by yogeshpatelTD** [FlutterFlow/flutterflow-issues#1894]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Drawer when opened in Preview or after publishing code shows up with left margin/padding and it is looking very wieged.

### Expected Behavior

As it was originally before the latest update.

The Drawer when opened should be left align without any margin/padding on the left.

Like below given screenshot.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/117966150/bc9269f5-64a0-41be-a4cc-de1cab5297ec)

### Steps to Reproduce

1. Add a new page to any project.
2. Place Drawer widget on page
3. Test it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ls/l5Yx2tbxY17X6YMExljw5JUc7bLsriOx+cws8KOPbPbMAPPfOTERucMfhSlZmPGKgiWoW3NbvvdryVvldKTaCRZxOzrV+exaWWjqnVaWaFJWgPXNRJ9NTGEeM5KaF2R1QBPdaR0Y97WeAOeyARTDtJLK0OkcsDq/LZO4=

### Context

We are on verge of completing a web app project and going to go live in a 2 days but this bug is holing us back.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/117966150/248cfe61-4868-4580-b75e-6065ab954faa)

It should show up like this:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/117966150/8b76134b-0115-42cc-9843-86f7dfb66da7)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: 3.13.7
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by sabatage3** [comment]
I'm having the same issue, any updates on this?

**Comment by sabatage3** [comment]
still no updates?

**Comment by SameerShahzad99** [comment]
@yogeshpatelTD I really apologize for the delayed response, it looks like the issue that you were facing has been resolved, check the attached screenshot
<img width="1508" alt="SCR-20240123-qary" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/2b0b724a-c318-4606-8bd6-3c91e33dd494">
