### ISSUE TITLE
Page properties don't allow DataType properties

### ISSUE THREAD

**Issue by mnimer** [FlutterFlow/flutterflow-issues#1897]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a DataType defined to map API responses to. This works in the ListView. However, when I try to pass this object to the next page, as a page parameter, I can not define a new variable of the same type in page #2.  As you can see in the attached screen shots there is a DocumentReference and Document, but not an option for DataType. 

I also checked in Document meant DataType, this might be a 2nd bug, as you can see in the 2nd and 3rd screen shots. The collection list for DocumentReference and Document are both the same and both of these map to my Firebase Collections, not my custom DataTypes.  

### Expected Behavior

1. I should see DataType as an option. 
2. DocumentReference should point to firebase collections and Document should point to DataTypes

### Steps to Reproduce

1. Create a new page
2. Make sure you have one DataType defined 
3. Define a new property. Try to create a new Page Property using this DataType. 
4. DataType is not an option in the drop down list. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiM/qy4hJpbxd1aqNcvlahSQ4KUc2becw0MpBZywgfZzzBLN/fPfQPxJoOO2mYXNffGemp14EwPDqvYX1KfUoGwieGLpC1KpiczvKXnOnM7WTF7iseEQnM9pXC0C7yJmvvRIlOttqcllgwVOyJu++YC7bHpjFOXo8Sq/LZO4=

### Context

I'm stuck, I can not move from page 1 to page 2.  

### Visual documentation

<img width="319" alt="Screenshot 2023-11-22 at 3 54 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/590830/6e473506-80bc-4792-a57e-ac9c6d1c2848">
<img width="314" alt="Screenshot 2023-11-22 at 4 03 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/590830/d77cfe3d-6198-4122-bdfe-83371a1b6db0">
<img width="314" alt="Screenshot 2023-11-22 at 4 03 32 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/590830/901178ad-40e7-4928-b3c3-cfd2b261625e">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected:  Mac Ventura 13.6.1
```

**Comment by mnimer** [comment]
any update?

**Comment by bob-reus** [comment]
I'm running into the same issue, and it's currently blocking progress. A response from the dev team would be much appreciated :)

This is also listed as a feature request: https://community.flutterflow.io/general-wishlist/post/page-parameter-missing-data-type-cfJC8NFxd2J1NlY

**Comment by hariprasadms** [comment]
Hi, @mnimer @bob-reus - Could you provide more details on why you are looking data type option available in page parameters, and could you also elaborate on how its absence is hindering your progress or affecting your work?

**Comment by mnimer** [comment]
Is the last release you added the ability to Map API results to a DataType. So on page 1 I converted my code from json array to a data type and use it on the page (instead of json paths).  Now I want to pass the selected list element (DataType) to the detail page. Instead of an id and making another api call or as json and being required to going back to json paths for every variable.  Basically you added a new feature in the last release to map API results to an object and I want to pass around. 

Also note, I think you have a 2nd bug (detailed above). You have two property types that both list the same Firestore collections.

**Comment by bob-reus** [comment]
> Could you provide more details on why you are looking data type option available in page parameters, and could you also elaborate on how its absence is hindering your progress or affecting your work?

In our app, users can create a sequence of timers with different durations, of variable length. I want to store these locally as a custom datatype we call a `Table`, and pass these to the page with the timer widgets. In its most simple form, it would look something like this: 

```
{
    "type": "string",
    "breath_holds": [
    {
        "hold_sec": 105,
        "breath_sec": 120
    },
    {
        "hold_in_sec": 105,
        "breath_sec": 105
    },
    {
        "hold_sec": 105,
        "breath_sec": 90
    }
]
}
```

There's no limit to the length of the `breath_holds` array, every `hold_sec` and `breath_sec` could have any value, and it's likely that  in the future we'll add more keys to both the `Table` DataType and the DataType in the `breath_holds` array. 

Passing all these as separate parameters is complex and error prone, especially when we want to expand functionality. The alternative is to convert between JSON and DataTypes, but as the manual [encourages the use of datatypes](https://docs.flutterflow.io/data-and-backend/api-calls/api-calls-101#json-to-from-data-type)...

**Comment by wenkaifan0720** [comment]
Hi all. This is more like a feature request instead of a bug. So I will close this issue for now. But it is a super valid feature request and I will pass it to our dev team for further discussion. Thank you!

As for your second question, Document and DocumentReference are both concepts for Firebase, where Document means the actual data, and DocumentReference is a reference (pointer) to the data. So you will always see that they have the same options.
