### ISSUE TITLE
Bugs with Translation

### ISSUE THREAD

**Issue by KreKdev** [FlutterFlow/flutterflow-issues#1898]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you use some components, the text dont appear in translate menu, examples:

Any text inside a "Text combination" dont appears in Languages/Translation menu
Any text inside a "Informational Dialog" dont appears in Languages/Translation menu
Any text inside a "Confirm Dialog" dont appears in Languages/Translation menu

### Expected Behavior

I expected to see all the texts I used on the page when I went to the "Languages/Translation" menu, even those inside these "objects", like "Text combination" or "Informational Dialog"

### Steps to Reproduce

1. Create a page
2. Create a Button
3. Set "Text combination" in field "Text", will not appear in the menu "Languages/Translation", only if it is a normal text

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXjMrqx891rsBE1ZfUbu0wp2EwFjMMbY0v0u0bFB4bIoDwOqQEYczeX0NKT9+Qe3N+BlaIgkIew/TGv4TLF/kVC02efIRf0JVAcz3NQlq6RK6OCZedPX98O95XCkvE3J6VsBMnJfp2W1Yg70OtNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Unfortunately, I used a lot of "Text combination", "Informational Dialog" and "Confirm Dialog" in my project, and now that I've looked at this translation part, I'm worried about how I'm going to find all the texts inside these "objects".

### Visual documentation

Dont need visual confirmation.

### Environment

```markdown
- FlutterFlow version: 4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Version 119.0.6045.160 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by katherineqian** [comment]
Hi @KreKdev, Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). You can also vote for new features in the FlutterFlow Community by going to the Community Wishlist. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas! Closing this issue for now.
