### ISSUE TITLE
Custom component: sync callback not executed

### ISSUE THREAD

**Issue by andreigubceac** [FlutterFlow/flutterflow-issues#190]
## Expected behavior (required)

Custom component with action is not called for synchronous callbacks.

## Current behavior (required)

From docs https://docs.flutterflow.io/actions/actions/ui-interactions/execute-callback the custom action is expecting an async callback. But trying to add callback with synchronous callback is not working

## To Reproduce (required)
1. Create new component with button.
2. Add custom parameter to component as action.
3. Link the button OnTap action with component's action.
4. From external usage add an action to show an Alert dialog.
5. The alert is not shown on tapping the component's button.

From code listed the button is waiting for an async callback, but the feature is requiring a sync callback.

### Bug Report Code

class CustomButtonWidget extends StatefulWidget {
  const CustomButtonWidget({
    Key? key,
    this.buttonAction,
  }) : super(key: key);

  final Future<dynamic> Function()? buttonAction;

  @override
  _CustomButtonWidgetState createState() => _CustomButtonWidgetState();
}

class _CustomButtonWidgetState extends State<CustomButtonWidget> {
  @override
  Widget build(BuildContext context) {
    return FFButtonWidget(
      onPressed: () async {
        await widget.buttonAction?.call();
      },
      text: 'Custom Button',
      options: FFButtonOptions(
        width: 130,
        height: 40,
        color: FlutterFlowTheme.of(context).primaryColor,
        textStyle: FlutterFlowTheme.of(context).subtitle2.override(
              fontFamily: 'Poppins',
              color: Colors.white,
            ),
        borderSide: BorderSide(
          color: Colors.transparent,
          width: 1,
        ),
        borderRadius: BorderRadius.circular(8),
      ),
    );
  }
}

## Context (required)

Not able to reuse components with custom action.

## Screenshots / recordings

Video attached. The video shows the normal behaviour of the button with show Alert action. Wrapping it in a custom action doesn't show the alert.

## Your environment

* Version of FlutterFlow used: v30 Nov 18, Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): MacOS 13.0.1 (22A400)
* Browser name and version: Safari 16.1 (18614.2.9.1.12), 
* Operating system and version (desktop or mobile): desktop

https://user-images.githubusercontent.com/1044756/205433099-fc761eb3-793c-4526-8719-daedc93817cf.mov

**Comment by bulgariamitko** [comment]
I will make this as a bug, but just to make sure @andreigubceac did you test this in Run mode as well? Do you have the same behavior?

**Comment by andreigubceac** [comment]
Tested Now with  FlutterFlow V3.0 December 11 2020 - Flutter 3.3.4 and looks like works as expected.

**Comment by andreigubceac** [comment]
Just to confirm: in Run Mode works as expected. Only in preview mode it doesn't. So it just half bug?

**Comment by andreigubceac** [comment]
> 

Just to confirm: in Run Mode works as expected. Only in preview mode it doesn't. So it just half bug?

**Comment by bulgariamitko** [comment]
I am not sure to be honest. I think the preview mode is used only to see how the App will look like and the functionality itself can't be trusted there. So I am marking this as not a bug for now and let the FF team decide if the functionality should work in the Preview mode as well as I am not sure to be honest.

**Comment by andreigubceac** [comment]
Roger that. Thanks.
