### ISSUE TITLE
Project stopped opening

### ISSUE THREAD

**Issue by hoisel** [FlutterFlow/flutterflow-issues#1900]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't open my project. It keeps loading forever. I can't even duplicate it.

### Expected Behavior

I expect the project opens normally

### Steps to Reproduce

1. Try to open the project from dashboard or via link

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I cant open the project, so I can't get it

### Context

We have been working on a project that has stopped working suddenly. I was with the project open, working on it, when I was presented a popup indicating lack of internet connection. After that, refreshing the browser does not load the project anymore. 
I've tried:

-  the safe mode
- cleaning browse data 

But those didn't work. **We have to meet the project deadlines**, so I ask you for help, please. The internet connection is quite good also (340MB). The other projects under my account open normally. 

As an additional info, I can't even duplicate the project (when I click duplicate button nothing happens). Thanks in advance!

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/400244/ef52c2ea-edf5-4b5f-b485-039c97c0ea62)

### Additional Info

As an additional info, I can't even duplicate the project (when I click duplicate button nothing happens).

### Environment

```markdown
- FlutterFlow version: 3.13.7 (I guess)
- Platform: Web
- Browser name and version: chrome Version 119.0.6045.105 
- Operating system and version affected: Linux mint tricia
```

**Comment by hoisel** [comment]
I guess the error is related to the project being flagged as team project. If I create another project  I can browser this new project freely until I flag it as team project (I'm currently a pro user). From the dashboard I can see the project with issues is flagged a Team Project. I don't remember of changing this config recently. At least this gives you some hint on what is going on.

**Comment by hoisel** [comment]
What I noticed: The project wasn't opening in my workplace nor in my coworker's house. But, surprisingly it opens in my house (using the the same laptop). So, the only difference was the internet connection. I was suspecting the problem was related to team collaborations permissions, as I mentioned previously. I order to have the problem solved, I did the following:

The steps I did:

1. Here in my house I could open the project as well as duplicate it (I even coudn't duplicate it at work). I did it and the copy opens normally in my workplace. Notice that the copy wasn't created with team collaboration enabled.
2. I headed to my project settings and the collaborations config was: **Organization sharing disabled and updated collaboration enabled**
3. I disabled updated collaboration: project couldn't still be opened at my workplace.
4. **I switched the share with my organizations off =>on, and then on => off again. After that, the Team tag faded from the project cover in the dashboard, and we could open the project again in my workplace. The error was gone and my initial guess seems to be right: that was something related to team permissions. The weird part is, I don't remember changing these settings recently. Luckily, and for some unknown reason, I was able to open the project here at home (from any computer) to disable the inconsistent team collaboration setting that prevented the project from opening at my workplace (on any computer).**

I wanted to share this with you. It may help in some way.

**Comment by hariprasadms** [comment]
Hi @hoisel - Thanks for submitting the issue. As per your latest comment, I presume you got access to project and continue working on it. Not sure whats happening when you access in work place network. We keep this behaviour noted and see if there more similar observations from other users. Thanks for the details.
