### ISSUE TITLE
Expandable widget inside pageview

### ISSUE THREAD

**Issue by ricardocosta43** [FlutterFlow/flutterflow-issues#1901]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I'm in a pageview from page index 1 onwards and I add an expandable to a container, I can't see the expandable's UI when I click on any component inside it

### Expected Behavior

Being able to normally see the fields inside the expandable

### Steps to Reproduce

1 - Create a page and insert a pageview

2 - Insert a column within page 1 (index 0) and some fields as texts

3 - Go to page 2 (index 1) and insert a listview

4 - insert a container and an expandable inside the container

5 - try to edit widget inside expandable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkfHqx89IsbRF+KqNLO1FpDkRM0MBX5Ir1utvGQ8dfLbtB7MqefTuaXdfXbycYWxIJmeWpHkEzMqJiYXiGuw4HwitRYt607hUagLdUkOjV6nTDKuWX3FBN91UJna/y6eK3BJTLvpvSmwk2nGLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Sim

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/62fef0d5-d4ed-455e-86d7-7d94463f35c4

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 116.0.5845.187
- Operating system and version affected: Mac OS Sonoma 14.0
```

**Comment by ignalauret** [comment]
Closing this issue, since it has been fixed in newest version of FlutterFlow.
