### ISSUE TITLE
Container max width not recognize Constant Value

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#1902]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I set max width of a container using constants(double type).
But container size was not limited in the value.
v4 - fluter 3.13.7

### Expected Behavior

Container recognize const value and max

### Steps to Reproduce

# Reproduce Bug
1. Make a Outer Container under Scaffold
2. Make a Inner Container under Outer Container
3. Set Max Width of Inner Container to Consts(900px)
4. Delete Inner Container default width(100px)
5. Add TextField into Inner

Now, you can see TextField NOT limited 900px at No.5.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/e9a0a3a6-329e-436d-a9e5-54831c2ad5b8)

# it's OK
1,2. Same as above.
3. Set Max Width of Inner Container to 900px as value.
4, 5. Same as above.

Now, you can see TextField is limited in 900px properly.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/e8a6f248-9f78-496c-9cb0-fbc2a8847c35)

----- additional info ----
plus..
6. Replace Max Width of Inner Container 900px to Consts(900px).

Now, limitation still keeping.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/88bed0a0-c622-486c-ae8d-45408fe1e3cf)

and then..
7. Remove Consts, then 900px value re-appears.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/7f2f8e6b-ae9e-4b1e-93fd-44ead0cacf95)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8jq3ItOm8sC1a6Jd+1Wnj4sH2UcTIMziNZ+exUbfaL1Bu0fPc7eVxBoZMu4aVNcC2eJpGU1+ajIiYTpJ/ADPSiCR6ZT+KlUUz30e2imRrKgEaWoX0d8DfhUCn6s37uk2xQlKu5eSVIT2Wb7AuzLZADDFOu/Zwh9f6PHaOI=

### Context

I consider the use of constants in the right places to be a constant in development. I have to proceed with development by scattering magic numbers without using constants, and later have to consider the hassle of collecting them and the risk of omitting to correct them.

### Visual documentation

see reproduce section

### Additional Info

TOO MUCH asterisk (* required). Who's bug?

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 119.0.6045.159 
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment]
Hi @ryutosh - Thanks for submitting the issue. The values from constants module can trigger only when app is running in build mode. It does not trigger in editing mode. Hence I can confirm that it is not a bug.

Build the project and see how it goes. Thanks

**Comment by ryutosh** [comment]
Hi, @hariprasadms 
Thank you for your reply.

I was able to confirm that the layout is done based on the constants in test mode.
I couldn't find it in the document, so your information that helped.
I am also disappointed that I can't check it in editing mode.

May I close this issue?
