### ISSUE TITLE
White Screen Of Death

### ISSUE THREAD

**Issue by teacherguy2020** [FlutterFlow/flutterflow-issues#1903]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have one page in my app that works fine in the testing environment but produces a white screen when published. I have tried countless fixes to try and solve. I’m out of ideas.

### Expected Behavior

I expect the published environment to reproduce the testing environment 

### Steps to Reproduce

This page includes cards, if that is a clue. I saw another post where gradients were an issue so I turned off elevation, but still can’t solve.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no bug in the testing environment

### Context

There are no bugs reported in the IDE

### Visual documentation

![IMG_8691](https://github.com/FlutterFlow/flutterflow-issues/assets/64993948/e020a84a-513c-45db-97fb-d618cfe46e55)

### Environment

```markdown
- FlutterFlow version: 4.1.11
- Platform: mac os
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @teacherguy2020 - Thanks for submitting the issue. Bug report code is required to get access to your project. Please add bug report code and also the page name in which you are experiencing the issue. Thanks
