### ISSUE TITLE
Merges not completing with changes on many branches

### ISSUE THREAD

**Issue by szymonpodwyszynski** [FlutterFlow/flutterflow-issues#1905]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In a more complex project, after creating branches from main, and making changes in those branches as well as in main, when we try to merge those changes, after the merge these changes are rarely present on the main branch, sometimes there are a half of those changes and sometimes the merge didnt came through at all. We've noticed that when merge didnt came through correctly, the Conflict screen didnt showed any information about conflicts even when we've produced those conflicts for specially for testing merging. 

### Expected Behavior

After starting merge, there should be a Review Conflicts screen if there are any, and after resolving those conflicts, the merge should go through correctly.

### Steps to Reproduce

1. Get a more complex project with a lot of elements, pages, actions etc.
2. Create two new branches
3. In every branch including main make some changes
4. Try to merge
5. See if the conflicts were shown
6. See if the merge came through correctly

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi/Hqw5F2pbwA7qX2Ke9VpGMsH0N8R700rNkaaxAaCeP0B7QUf/f8QxJpYuqHen9UDmG0gk0ypKnxhuGeU/AqGxStRqo4/ql9UxDjfF+iRaauC7igenMlHflMfRGd17uRuh57HMx2dHAb7GaQB/Kub3qCf9qOYwx5e6fDbOY=

### Context

The merging in this state is pretty problematic as we have to do merges a couple times sometimes as changes wont go through for the first couple times. It has really slowed our app making capabilities.

### Visual documentation

Custom Branch:
<img width="707" alt="Screenshot 2023-11-24 at 15 25 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/babfd247-174d-4910-b35d-062516e7196c">

Before merging main Branch:
<img width="707" alt="Screenshot 2023-11-24 at 15 25 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/fdda8bad-a123-4dc8-9553-532130933313">

After merging main Branch:
<img width="692" alt="Screenshot 2023-11-24 at 15 35 03" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/168c20cb-59c2-4a9c-8b7c-def09d3020bf">

I dont want to add any complex visual documentation, for safety purposes. If You wish to see a screen recording or some additional information please contact me privately.

### Environment

```markdown
- FlutterFlow version: Newest as of 24.11.2023
- Platform: Mac
- Browser name and version: Chrome Version 119.0.6045.159
- Operating system and version affected: MacOS Sonoma 14.1.1
```

**Comment by szymonpodwyszynski** [comment]
Hello! Has there been any updates on this case? I see You removed the status: stale so i hope everything is all right. If theres anything i can do to help please let me know! :)

**Comment by infocodiste** [comment]
I'm encountering a problem while merging branches. When I merge another branch into the main one, it ends up overwriting all the changes from the other branch, and the main branch loses its modifications. Additionally, attempting to rebase with the main branch causes the other branch to adopt the characteristics of the main branch and loses its modifications. This is quite frustrating for me as a developer, especially after investing in the enterprise-level access. After spending two days carefully merging two branches, I'm unable to find a well-merged branch, forcing me to resort to manual project management by manually write within the main branch

**Comment by smian0** [comment]
Hi flutterflow team, we are facing the exact same issue. We lost days of work and parallel development is a no-go at this point. Please address this issue since we are also a paying team customer and we expected this feature to work flawlessly.

**Comment by szymonpodwyszynski** [comment]
Hello! Has there been any updates on this case? We would appreciate some sort of info on hows this issue is going. Instead if thats an expected scenario, we would really appreciate some sort of documentation about how merges are supposed to work in FF.
Thanks

**Comment by maverickLDR** [comment]
We are also hitting into this problem and I can see that there were no updates for more than a month.  Is this considered "low priority"?  Because the merge issue is a very important feature for us!

**Comment by leighajarett** [comment]
Hi all - so sorry you're dealing with this. We're investigating this issue. It would be great to get more detailed information here. 

This is definitely not a low priority - but we need detailed information from everyone to investigate further. If you have experienced this issue please send me an email me (leigha@flutterflow.io) with your:

1.  Project ID
2. What merge specifically went bad (screenshot of merge history tab with highlighted merge, or date + branch names)
3. Example to look at in the project (e.g. "I had x on this branch and expected it to also appear in the resolved project, but it wasn't there post merge" -- with screenshots and videos to make very clear)

I know this information can be a pain to provide, but we're really trying to make sure we solve this issue for everyone! Every detail matters :) 

Thank you sooo much for your patience and once again I'm really sorry you're dealing with this frustration!
