### ISSUE TITLE
Int Based Enum

### ISSUE THREAD

**Issue by sarim** [FlutterFlow/flutterflow-issues#1906]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No option to select enum's value type

### Expected Behavior

option to select enum's value type: int, string etc...

### Steps to Reproduce

1. Create Enum
2. When decoding in runtime throws error String expected int found

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

N/A

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: v4.0 Nov 24 2023
- Platform: Web
- Browser name and version: Edge 119.0.2151.72 
- Operating system and version affected: Windows 11
```

**Comment by sarim** [comment]
> Hi @sarim - Thanks for submitting the issue. Please add more details in steps to reproduce. Create steps in a blank project and share project bug report code please.

It's more of a feature request.

**Comment by katherineqian** [comment]
Hi @sarim, Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). You can also vote for new features in the FlutterFlow Community by going to the Community Wishlist. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas! Closing this issue for now.
