### ISSUE TITLE
Synfusion flutter charts suddenly not working after latest update

### ISSUE THREAD

**Issue by Ryujinie** [FlutterFlow/flutterflow-issues#1909]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

App not running in test mode and giving errors regarding custom widgets with syncfusion chart. Tried updating the dependencies but still giving the same error.  

### Expected Behavior

Should be able to run the app in test mode

### Steps to Reproduce

1. Create a custom widget with the following code

// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:convert';
import 'package:flutter/src/widgets/framework.dart';
import 'dart:html';
import 'dart:ui';
import 'package:syncfusion_flutter_charts/charts.dart';
import 'package:syncfusion_flutter_charts/sparkcharts.dart';
import 'package:intl/intl.dart';

class Charts1 extends StatefulWidget {
  const Charts1({
    Key? key,
    this.width,
    this.height,
    this.chartTitle,
    required this.legend,
    required this.backgroundColor,
    this.titleColor,
    required this.completedTasks,
    required this.barcolor,
  }) : super(key: key);

  final double? width;
  final double? height;
  final String? chartTitle;
  final bool legend;
  final Color backgroundColor;
  final Color? titleColor;
  final Color barcolor;
  final List<CompletedTasksRecord> completedTasks;

  @override
  _Charts1State createState() => _Charts1State();
}

class _Charts1State extends State<Charts1> {
  _Charts1State();

  @override
  Widget build(BuildContext context) {
    return Center(
        child: SfCartesianChart(
            //title: ChartTitle(text: widget.chartTitle),
            legend: Legend(isVisible: widget.legend),
            backgroundColor: widget.backgroundColor,
            primaryXAxis: DateTimeAxis(
              dateFormat: DateFormat.MMMd(),
              intervalType: DateTimeIntervalType.days,
              interval: 1,
              maximum: DateTime.now(),
              minimum: DateTime.now().subtract(Duration(days: 7)),
            ),
            primaryYAxis: NumericAxis(visibleMinimum: 0),
            // Palette colors
            palette: <Color>[
              Color.fromRGBO(75, 57, 239, 1),
              Colors.teal,
              Colors.brown
            ],
            series: <ChartSeries<CompletedTasksRecord, DateTime>>[
              ColumnSeries<CompletedTasksRecord, DateTime>(
                //Enables the tooltip for individual series
                color: widget.barcolor,
                enableTooltip: false,
                dataSource: widget.completedTasks,
                borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(4), topRight: Radius.circular(4)),
                xValueMapper: (CompletedTasksRecord tasks, _) => tasks.date,
                yValueMapper: (CompletedTasksRecord tasks, _) =>
                    tasks.cpTasksInt!.toDouble(),
                width: 0.8,
                spacing: 0.2,
                //borderRadius: BorderRadius.all(Radius.circular(15)),
                markerSettings: MarkerSettings(isVisible: false),
                name: 'Completed task',
                dataLabelSettings: DataLabelSettings(isVisible: false),
              )
            ],
            tooltipBehavior: TooltipBehavior(enable: false)));
  }
}

class tasks {
  String user_id;
  DateTime date;
  List task;
  int cp_tasks_int;
  tasks({
    required this.user_id,
    required this.date,
    required this.task,
    required this.cp_tasks_int,
  });

  tasks copyWith({
    String? user_id,
    DateTime? date,
    List? task,
    int? cp_tasks_int,
  }) {
    return tasks(
      user_id: user_id ?? this.user_id,
      date: date ?? this.date,
      task: task ?? this.task,
      cp_tasks_int: cp_tasks_int ?? this.cp_tasks_int,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': user_id,
      'date': date.millisecondsSinceEpoch,
      'task': task,
      'cp_tasks_int': cp_tasks_int,
    };
  }

  factory tasks.fromMap(Map<String, dynamic> map) {
    return tasks(
      user_id: map['user_id'] ?? '',
      date: DateTime.fromMillisecondsSinceEpoch(map['date']),
      task: map['task'] ?? '',
      cp_tasks_int: map['cp_tasks_int']?.toInt() ?? 0,
    );
  }

  String toJson() => json.encode(toMap());

  factory tasks.fromJson(String source) => tasks.fromMap(json.decode(source));

  @override
  String toString() {
    return 'tasks(user_id: $user_id, date: $date, task: $task, cp_tasks_int: $cp_tasks_int)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is tasks &&
        other.user_id == user_id &&
        other.date == date &&
        other.task == task &&
        other.cp_tasks_int == cp_tasks_int;
  }

  @override
  int get hashCode {
    return user_id.hashCode ^
        date.hashCode ^
        task.hashCode ^
        cp_tasks_int.hashCode;
  }
}

2. Add dependency syncfusion_flutter_charts: ^23.2.5 or syncfusion_flutter_charts: ^23.2.4
3. Run in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiMjfsJRIocMA1aXide9amSQ7OVt9U50vkcpBazwbfe+uB4kqevfOTERvZ8yrTUFqM02Wp2oW0fz4uOHyFe4CIUuCb6Z8wapfEgrycH25RKaRFJWgOUZRO+Bmfna+4LWn3BF/CONfLHg+3DqMJ/OtVjLbJbrKPDIWDq/LZO4=

### Context

Cant edit my project that is due tomorrow

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72432031/6de03ae4-e246-4251-ba28-0c897c172f24)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72432031/fa1efabc-e6ab-4c2f-9de4-32c626761961)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released November 24, 2023
Flutter version is 3.13.7
- Platform: WIndows Desktop
- Browser name and version: Microsoft Edge
- Operating system and version affected:
```

**Comment by yuma-developer** [comment]
I have the same problem

**Comment by hariprasadms** [comment]
Hi @Ryujinie - Thanks for submitting the issue. As @trevorFields highlighted, this issue specific to syncfusion package. Update the package version accordingly. 

@trevorFields - Thanks for adding your input.
