### ISSUE TITLE
Web publishing "mapIndexed" compilation error

### ISSUE THREAD

**Issue by Shokhrukh99** [FlutterFlow/flutterflow-issues#1914]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to publish to Web, the build error appears with the following error message: 
```
Error: Command failed: flutter build web --web-renderer html --no-pub --no-version-check --no-tree-shake-icons
Target dart2js failed: ProcessException: Process exited abnormally:
lib/doctor/doctor_patients/doctor_patients_widget.dart:931:60:
Error: The method 'mapIndexed' is defined in multiple extensions for 'Iterable<dynamic>' and neither is more specific.
- 'Iterable' is from 'dart:core'.
.mapIndexed((patientSearchResultsIndex,
^^^^^^^^^^
lib/flutter_flow/flutter_flow_util.dart:229:11:
Info: This is one of the extension members.
List<S> mapIndexed<S>(S Function(int, T) func) => toList()
^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/collection-1.17.2/lib/src/iterable_extensions.dart:170:15:
Info: This is one of the extension members.
Iterable<R> mapIndexed<R>(R Function(int index, T element) convert) sync* {
^^^^^^^^^^
Error: Compilation failed.
```
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/0cbc50f8-78d1-41b3-a31b-99c48831c66a)

I have two DataTables with API call and Supabase Query. I assume that error originates from the DataTable with API call. When I downloaded the code, the error is the following

![image (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/d80c44cb-a4c3-4e0d-971b-6c069b6a5647)

### Expected Behavior

Web publishing should work without any compilation errors

### Steps to Reproduce

1. Create DataTable with API call
2. Create DataTable with Supabase Query
3. Publish to Web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelefluJN2tb0A+c7iasBopwMwGlgnbZI7t9Z+awsjGePuEYYqfMnSTxNWcuqHe3w7AU2L/UYB/8LGhuzpDe04KTScfo84+ZNfUxDhQXGWVJC7BbrhY3NBM8FVJ3al552N2xUnG7NZdHwu7DmUIPOAa3qCf9qOYwx5e6fDbOY=

### Context

I cannot publish to web

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/0cbc50f8-78d1-41b3-a31b-99c48831c66a)
![image (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/32006946/d80c44cb-a4c3-4e0d-971b-6c069b6a5647)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Google Chrome 119.0.6045.160
- Operating system and version affected: (desktop) Windows 10
```

**Comment by rayduui** [comment]
same issue for me

**Comment by sbis04** [comment]
Hey @Shokhrukh99l and @rayduui, are you still facing this issue? Seems like it has been already fixed.

**Comment by rayduui** [comment]
> Hey @Shokhrukh99l and @rayduui, are you still facing this issue? Seems like it has already been fixed.

Hi, not anymore, looks like it’s fixed
