### ISSUE TITLE
Page navigation after user sign up not working

### ISSUE THREAD

**Issue by tflax32** [FlutterFlow/flutterflow-issues#1915]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a create account page. I have an action that creates an account. Then I have it navigate to my "Capture" page. The problem is that it does not navigate. I also tried adding a navigation to the

### Expected Behavior

It navigates to the page that I specify in the actions.

### Steps to Reproduce

1. Used a default login page
2. Go through the basic create account process.
3. See how the page doesn't automatically navigate to page required.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjsmB34ZOm9sF+KrqdPlKpD0RM0MfWLsr0utuGA0hfL3mBJoiZcj7clpLYteYYG9YOGL9iTkC0ujFv+DLF/YnBEysRo9y1q5XQQ/wLXinb5SpPqWzOUQnQZ9bIUPC36WJhhR/IsxadFIb3GeIPfCdG3qCf9qOYwx5e6fDbOY=

### Context

Users are confused when they create an account. They click create account, then nothing happens.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91764341/07c0d175-908f-4c75-9397-5a1ca13393a0)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91764341/fca47f26-510e-41d6-aa4d-e63b3aa46812)

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Flutterflow
- Browser name and version: Google Chrome
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi, Due to inactivity I presume, this issue has been resolved for you. Hence closing the issue. Thanks

**Comment by Anyaoha** [comment]
Can someone confirm that this is fixed? @hariprasadms 
I find the navigation after sign up, auto navigating to home page instead of following the 'navigation to other pages' in the action.

So instead of navigating to pages set in the action steps, it ignores them and auto navigate to home page.
