### ISSUE TITLE
Audio player blank on lock screen

### ISSUE THREAD

**Issue by LinnMarita** [FlutterFlow/flutterflow-issues#1916]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Playing audio in the background works fine, but the audio player on the lockscreen (just tested iPhone) is blank.

![IMG_5514](https://github.com/FlutterFlow/flutterflow-issues/assets/144349486/e72d2387-a124-4462-a8c1-c42f3a00974c)

### Expected Behavior

Expect progressbar, title, artist and artcover to show on the locked screen. (As for now there is no place to input artist and artcover, so that would be a feature request)

![IMG_825C8FD44873-1](https://github.com/FlutterFlow/flutterflow-issues/assets/144349486/e36dd6b7-306a-4380-94ee-52bdbdd331ba)

### Steps to Reproduce

1. Create new page
2. Add audio player widget
3. Pass in the asked information and audio
4. Run app
5. Start playing from the audio player
6. Lock screen and wake up screen.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OismBw5N1pbxE7qrqaflV/SAWQ3o5a7xN1u1ue0o0fJPNGJsAPvfRalRZTf26S2xYMFu0gnszwNbLv+zMFeQHAy+ZfJRB/rpAZjvjRky6R5CkDc6aQGpRJ5hgDkuVyMCFvBN+GOxoLHAs6l2bN9mXYAzaCZu3OnoeQuahENv/pXDnAi+6Xn0Jg1ZSfCvr

### Context

About to release my app that has audio as a big part of the design. Looks bad.

### Visual documentation

Current behavior:
![IMG_5514](https://github.com/FlutterFlow/flutterflow-issues/assets/144349486/834ce57a-b25c-4ed4-977d-bb47b6a0022f)

Expected behavior:
![IMG_825C8FD44873-1](https://github.com/FlutterFlow/flutterflow-issues/assets/144349486/d81f8c21-a6c3-4ee3-8d18-fb7218a9d44d)

### Environment

```markdown
- FlutterFlow version: v4.0 (released November 28, 2023)
- Platform: Web / iPhone
- Browser name and version: Chrome 119.0.6045.199
- Operating system and version affected:
```

**Comment by victoriahuang1** [comment]
Hi @LinnMarita , thanks for the report. This is the current expected behavior (there is no image, title, album, ... because there wasn't anywhere for you to provide that info).

I will put this down as a feature request.
