### ISSUE TITLE
Unable to compile Flutterflow when using the Flutterflow PDF Viewer

### ISSUE THREAD

**Issue by paulwheatley** [FlutterFlow/flutterflow-issues#1918]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All works well within Flutterflow, but once exported to Android Studio and/or Xcode to build for release the following error occurs... 
`error: ../../../../.pub-cache/hosted/pub.dev/pdfx-2.3.0/lib/src/viewer/pdf_page_image_provider.dart:24:55: Error: Type 'DecoderCallback' not found.`

### Expected Behavior

Able to build and PDF viewer functions as exopected

### Steps to Reproduce

Create a new page
Add a PDF Viewer component
Add a PDF (either via Asset or Network)
download code
Open in either Xcode or Android Studio
Build

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giOfl2It2n7wA7qX2Ke9ahSgXHHIlaJc0sdpucxUvIrbyOuwQdvXsaktBTu2mT2NAPESmmjsE3PTIkoThA/EDCzGrQYA4zqttETyURmege5OBEKigW3N5OJljCGqfy8KJhx14IbZvckYH7TmQBuyUbD/ZJr62IlFISq/LZO4=

### Context

I am unable to release my app as it requires PDF viewer functionality

### Visual documentation

<img width="760" alt="Screenshot 2023-11-29 at 10 19 48" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7361239/4a878a83-4998-42e2-bb1d-4d4cd04cf605">

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform: iOS and Android
- Browser name and version: N/A
- Operating system and version affected:
```

**Comment by dellsmash** [comment]
Found a solution on stackoverflow. https://stackoverflow.com/questions/77517742/error-type-decodercallback-not-found-imagestreamcompleter-loadpdfpageimagep

Change your pdfx: line in pubspec.yaml to

pdfx: 
  git:
   url: 'https://github.com/ScerIO/packages.flutter' 
   ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'  
   path: packages/pdfx

**Comment by aemelyanovff** [comment]
@paulwheatley Thanks for reporting the issue, and sorry for the late response.

I'm unable to reproduce the issue - projects with PDF viewer compile fine for me. And the project in the bug report does not seem to exist anymore.

I'm assuming the issue has been resolved, but please let us know if it's not.
