### ISSUE TITLE
Button text alignment not working

### ISSUE THREAD

**Issue by ayuno** [FlutterFlow/flutterflow-issues#192]
I am surprised that there has been no official bug report on this as there are multiple posts about this bug on the Community forum. So here goes:

## Expected behavior (required)
<img width="142" alt="image" src="https://user-images.githubusercontent.com/21143928/205661155-29ba9680-cefd-44be-a5b7-031ba2ac3403.png">

Text align property should align text within Button widget.

## Current behavior (required).
Nothing happens in the UI (and I am not seeing anything changing in the code either when I set the alignment).

## To Reproduce (required)

1. Create a button widget
2. Set "text" alignment to left/right
3. Observe that nothing happens

### Bug Report Code
ITFTi/Lq25NOm+Fa+Kn2bu1oiikXI0MfWLsr0utuGA0hfKroP+0QfM7CXxNLYteke1VEGmL9kmEx/vz2jeHyGu4rOUyaGd1n+bwFH1yjEA8=

## Context (required)
I am struggling to create a form with the PlacePicker included where everything is left aligned.

## Screenshots / recordings
<img width="541" alt="image" src="https://user-images.githubusercontent.com/21143928/205662174-089abcce-8639-438a-8cc3-8070fd2a19bd.png">

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Windows 10
* Browser name and version: Chrome (latest)
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
Hi @ayuno. I think this due to the fact that the `FFButtonWidget` does not really have a text align property. What we really should do is removing that align selection widget.

For achieving your desired button UI, I suggest creating a custom component.
