### ISSUE TITLE
When a Form is copy/duplicated doesn't persist the validation fields

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1921]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a Form is copy/duplicated doesn't persist the validation fields and I need to re set manually again

### Expected Behavior

When a Form is copy/duplicated should persist the validation fields and avoid to re set again

### Steps to Reproduce

1. Create a form
2. Add one or more textField
3. Go the Form widget and configure it
4. Now duplicate or copy and paste in the same page or another
5. Now you see the validation field of the form is empty

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Cg9Db2x1bW5fOGRrbnQ5amoSwAQKDUZvcm1fMmVkYm4xd3oS6QIKD0NvbHVtbl93N2ZiajJmOBKmAQoSVGV4dEZpZWxkXzg4bjBqZnk1GBAiiAFaEgkAAAAAAAAgQBkAAAAAAAAgQIoBYgoCQAYSVwgCGQAAAAAAAABAIiQJAAAAAAAAIEARAAAAAAAAIEAZAAAAAAAAIEAhAAAAAAAAIEA6AhAEYgJADmoCQA5yAhAPeg8KDUxhYmVsIGhlcmUuLi6KAQIQARgBgAEB+gMA8gUJCQAAAAAAAPA/YgDCAQASpgEKElRleHRGaWVsZF9mcWQzbm1hOBgQIogBWhIJAAAAAAAAIEAZAAAAAAAAIECKAWIKAkAGElcIAhkAAAAAAAAAQCIkCQAAAAAAACBAEQAAAAAAACBAGQAAAAAAACBAIQAAAAAAACBAOgIQBGICQA5qAkAOcgIQD3oPCg1MYWJlbCBoZXJlLi4uigECEAEYAYABAfoDAPIFCQkAAAAAAADwP2IAwgEAGAQiAiIAGDwiuwH6AwCSBKgBClQKElRleHRGaWVsZF84OG4wamZ5NRABIjwyDQoLTG9yZW0gaXBzdW16KwopUGxlYXNlIGNob29zZSBhbiBvcHRpb24gZnJvbSB0aGUgZHJvcGRvd24KUAoSVGV4dEZpZWxkX2ZxZDNubWE4EAEiODIJCgdUZXN0aW5neisKKVBsZWFzZSBjaG9vc2UgYW4gb3B0aW9uIGZyb20gdGhlIGRyb3Bkb3du8gUJCQAAAAAAAPA/YgDCAQAYBCITIgIyAPoDAPIFCQkAAAAAAADwP2IAwgEA

### Context

Sometimes I need to reutilize some forms or when I need to copy and paste a entire page to another because I was doing a reskin of the project

### Visual documentation

https://www.loom.com/share/1d39148af46f45e4995ec4038a0e886a

### Additional Info

Another bug is that there are 2 form-validation widgets, you can see in the next link

https://www.loom.com/share/1d39148af46f45e4995ec4038a0e886a?highlightComment=24892955&t=8

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released November 28, 2023 - Flutter version is 3.137
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)
- Operating system and version affected: W11 23H2
```

**Comment by wenkaifan0720** [comment]
Hi @Franco98404. I believe this has been fixed in the latest release.

**Comment by Franco98404** [comment]
Hello @wenkaifan0720 I can confirm this bug is solved, but it still appears 2 forms

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/a76d7f0a-87df-4917-a8ac-8c14e0c96b28)

**Comment by wenkaifan0720** [comment]
This one should be fixed in our next update!
