### ISSUE TITLE
App Crashes after taking photo

### ISSUE THREAD

**Issue by tarakiga** [FlutterFlow/flutterflow-issues#1924]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i use the default camera widget to take a photo, instead of returning to previous screen and updating image on page, the app crashes and reloads

### Expected Behavior

After photo is taken, should to return to previous screen and add image to that screen

### Steps to Reproduce

1. login
2. select "student onboard" tab
3. select image upload
4. take photo
5. photo is added to page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kk+fqxIt2pbxE+KrTbcB7/SQXQ0A/a5IolsB9RgAgF4jvG7k+XM+lYkRCUu6od29UImG0jWoW0PSPvfHtOPYDCzOqR6p8zZZ2cgrxfGqWMMTSFJWgVHFDM/pQGXKHyKW7oBBNPvJfWCBn3WWYONzISj7aH5jSPFYWDq/LZO4=

### Context

Photo is a required field which halts onboarding processthe 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/43468764/cc081787-a045-4320-aeb5-7ebc9ec415ac

### Additional Info

nothing more to add

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Android mobile
- Browser name and version:
- Operating system and version affected:
```

**Comment by tarakiga** [comment]
Any updates on this please? Thanks.

**Comment by tarakiga** [comment]
Hello, still haven't received a response for this after my last message. Can i have an update on the status?

**Comment by hariprasadms** [comment]
Hi @tarakiga - I apologise for the delay in my response. I'm not able to reproduce the issue in Android devices. Is this issue still existing even after latest FF updates last week? Please confirm. Thanks

**Comment by hariprasadms** [comment]
Hi @tarakiga - I can reproduce the issue now on iOS and Android both.

**Comment by tarakiga** [comment]
Seems to be device-specific and maybe a memory issue as I tried on another device and it worked but still getting the error on the original device so i believe we can close this.

**Comment by arpit786shukla** [comment]
Hi @hariprasadms , I am also experiencing a similar issue. The app is working fine on android but its crashing on iOS. I tried a lot of things and found the issue atleast in my case. I am using listview to load the products (images). When I try to load more than a certain number of images in one go, it crashes in iOS. But somehow android is able to handle the load. Solution would be some kind of lazy load in the listview
