### ISSUE TITLE
When an API call is imported from Swagger the variables cannot be modified

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1925]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an API call is imported from Swagger the variables cannot be modified. The POST and PATCH types has the problem.

### Expected Behavior

Should be able to do modifications without problems

### Steps to Reproduce

1. Import a Swagger file to FF
2. Go to an API Call that has a body (POST or PATCH)
3. Do some modifications, for example, rename/delete a variable
4. Now you see the error

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/0f58d527-df95-47ce-b408-44bb107934df)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkufl0It1mNte14SIKcJsgiYUNkMcTIMziNZ+exUbfaL1Bu0AOcnBblpoYMu4aVNcOVCKkTkGpvD9i/PpOO5cHy2ZbIBM+Id+Ew3ee2iuSq7REoeSZmsnBexTfEia55+42BQkOtZ1Wmw42WGILu+XRXTDBOu/Zwh9f6PHaOI=

### Context

I want to do some modifications to an API

### Visual documentation

https://www.loom.com/share/237c9dcba9ff42d194edde100e5b1389?sid=2cce386e-5055-41e1-8d5d-685d2077ce0f

### Additional Info

Here is the Swagger file that I used in the video:
[openapi3_0.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13502289/openapi3_0.zip)

I tried to replicate the error with APIs created manually (not imported from Swagger) and I couldn't so I think is related to the API imported from Swagger

Another bug is when an API is duplicated the focus is still in the original API, and should be focus in the duplicated API Call

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released November 28, 2023 - Flutter version is 3.137
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)
- Operating system and version affected: W11 23H2
```

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Thanks for posting the issue. I have tested it and can see it happens when imported json structure got mapped variables already. When you do the same variable mappings to request body inside FF api editor, it all works fine while modifying. I can confirm this can be a bug. Thanks

**Comment by sarim** [comment]
Question, In my apis, I can't get flutterflow to generate variables. I wanted to create a new issue but searched "swagger" here and found this. In this issue's provided openapi schema file, variables are declared twice, parameters in query, then also in request body. But It is POST request, so data will be provided only via requestBody. I noticed if I remove it from parameters when flutterflow doesn't generate variables. So seems like it is a hack to coarse flutterflow to generate variable?

Also another issue: flutterflow doesn't create content-type and accept header from openapi schema...

**Comment by takashiff** [comment]
Hello @Franco98404, thank you for your bug report. This looks to be an issue with the body of the api call. When you remove/edit a variable, the name in the body must also be updated.
<img width="1279" alt="Screenshot 2024-01-12 at 1 54 39 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134453477/b9d5cc8c-a576-4d89-8a00-cd6d9537a481">

**Comment by takashiff** [comment]
Hello @Franco98404, thank you for your bug report. As a temporary workaround, you can change the method type to "GET", go into the "Query Parameters" tab, and remove all of the query parameters. Thank you for your patience.

**Comment by takashiff** [comment]
Hi @Franco98404, just wanted to provide an update. We've put in a fix for this issue recently, and it should be reflected within the next few weeks. Thank you for your patience!

**Comment by Franco98404** [comment]
Hi @takashiff, what about this?

> Another bug is when an API is duplicated the focus is still in the original API, and should be focus in the duplicated API Call
