### ISSUE TITLE
After closing a branch is not possible to create another with the same name

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1927]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After closing a branch is not possible to create another with the same name

### Expected Behavior

I don't know if it is a bug but I think that is necessary create a new branch with the same name or reopen the branch

### Steps to Reproduce

1. Create a new branch
2. Go to that branch and close it
3. Now go to the project and try to create a new branch with the same name and is not possible

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkufl0It1mNte14SIKcJsgiYUNkMcTIMziNZ+exUbfaL1Bu0AOcnBblpoYMu4aVNcBmGLgkUDpvDRiIX+GvUoNU6CG7461cxybAvke2iuSq7REoeSZmsnBexTfEia55+42BQkOtZ1Wmw42WGILu+XRXTDBOu/Zwh9f6PHaOI=

### Context

I don't want to have a lot of branches so I'm deleting after the merge to be more organized.

Sometimes I need to test something and create a "testing" branch, I do some tests and I merge it or close it. After a time I want to test something again and I can't use the "testing" branch name

### Visual documentation

https://www.loom.com/share/6e6c8280e5a648bfb15810d4c4a93a8e

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released November 28, 2023 - Flutter version is 3.137
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)
- Operating system and version affected: W11 23H2
```

**Comment by victoriahuang1** [comment]
Hi @Franco98404 thanks for the report. This is actually the expected behavior for now.
I can put this in as a feature request though.
