### ISSUE TITLE
Type Mismatch Error: Passing List<Object> as List<Double> Argument in Custom Function

### ISSUE THREAD

**Issue by AntonioFrancoDeOliveiraCanto** [FlutterFlow/flutterflow-issues#1928]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My API returns Lists <Double> (https://d2y5h3osumboay.cloudfront.net/pvhkeuhvybcmjmxwrcbibleu099a (here are the Json Paths, and types))

I insert these Lists <Double> into a custom function that returns them as a List <LatLng>(https://d2y5h3osumboay.cloudfront.net/wcih84ukt3z9dclhlqk7cyz4n7yj (custom func), https://d2y5h3osumboay.cloudfront.net/3fx9szpqzs85odwraang2gh84tun (insertion of Json Path data into the custom function ))

The error says that it expected a value of type List <Double>, but receives a List <Object>, it turns out that the api returns a List <Double>, I insert a List <Double>, and it presents an error in the same way (https://d2y5h3osumboay.cloudfront.net/ukizbxwhyv34chn91oex3nabiade)

It is not possible to pass something of type Object as an argument, and anyway, something of type Object should "be able to fit into anything"
Neither in test mode nor in publishing they work, but in run mode they do

### Expected Behavior

Era esperado que os dados da API em lista<Double> fossem passados em lista<Double>, e se passados em lista<Object> fossem manipulados da mesma maneira pela função

### Steps to Reproduce

Clone the project below, enter your Google Place API credentials, go to test mode, search for a location, and click on a marker
https://app.flutterflow.io/project/nearby-places-pxpegh?tab=uiBuilder&page=mapPage

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ivHlz4Z1mOZE17rAcfowmio5KUh7apIrjO5raCosfZT2BLMcec/RVERDTs+6TwlEJE2jgWoW0fyOhdnTN8BdOk6eR4hR1roJShXLcGCXR5SsFJWgOHFBBdlPG2qA3J+RhxFvIbdudF4X3F2mA+etQgTaHpDYOjJBDq/LZO4=

### Context

With this error I can't continue with my project, considering it's not possible to manipulate things like Object in flutterflow's custom function

### Visual documentation

https://d2y5h3osumboay.cloudfront.net/pvhkeuhvybcmjmxwrcbibleu099a
https://d2y5h3osumboay.cloudfront.net/wcih84ukt3z9dclhlqk7cyz4n7yj
https://d2y5h3osumboay.cloudfront.net/3fx9szpqzs85odwraang2gh84tun
https://d2y5h3osumboay.cloudfront.net/ukizbxwhyv34chn91oex3nabiade

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: web
- Browser name and version: edge 119.0.2151.72
- Operating system and version affected: Windows 10 Pro
```

**Comment by hariprasadms** [comment]
Hi @takashiff - Thanks for submitting the issue. While passing json response as it is to custom code parameters, arguments type should be a json type ( If it is list of object than it should be list of json type ) not just a list of string. I can confirm that this issue is not a bug.
