### ISSUE TITLE
WebView widget create error on Test

### ISSUE THREAD

**Issue by StewiiContact** [FlutterFlow/flutterflow-issues#1929]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to integrate a webview into my app so I can access some webpage from it. The main purpose is to confirm a payment with Stripe. Stripe can sometime send a url to confirm a payment and I want to integrate the webview inside my app.

### Expected Behavior

I want the webpage to open without any error popping inside the console in test mode.

### Steps to Reproduce

1. Create a page
2. Add the webview widget 
3. Bind the webview widget to a url: for example https://www.wikipedia.org
4. Test the app using google chrome or firefox
5. Open the console
6. Navigate to the page containing the webview
7. You will see the errors in the console

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhc/138xNoeZE7Yf5YMdGmiMwGUgXU4I3te5+d0shNZzpB4oUeuLBTFZLYteifGxbMWGbvGM1/+DXieDLJPc3HE+BbL5SyL5XQTvMeGSgeKXXO8yOXHJBEd5WCnayyJ6FpiYlA7FZcmQ+7U2Ef/CdG3qCf9qOYwx5e6fDbOY=

### Context

I am trying to finalize a payment by opening a url Stripe is sending to me.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/152452144/ed0159e2-ce71-47cb-9a39-cec09c341561

### Environment

```markdown
- FlutterFlow version: V4.0 Released Nov 28, 2023
- Platform: Web
- Browser name and version: Google Chrome 119.0.6045.161
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @StewiiContact - Thanks for submitting the issue. How this error is affecting the feature you are trying to implement in your app ?. Is this breaking the functionality ?

**Comment by StewiiContact** [comment]
> Hi @StewiiContact - Thanks for submitting the issue. How this error is affecting the feature you are trying to implement in your app ?. Is this breaking the functionality ?.
> 
> Considering stripe checkout page you are trying to render within web view, It does not work in most of the cases because of the limitation around web-view compatibility with stripe checkout page. And it is not a secure approach as well.
> 
> I would suggest use launch url action instead. It is safe and simple.

**Comment by hariprasadms** [comment]
Hi @StewiiContact - Thanks for confirming the error you see is not breaking your app. About stripe integration with flutter using WebView. I would suggest to go through docs available in flutter discussion forums that can help you to find better  approach to achieve it. Thanks

**Comment by StewiiContact** [comment]
Crazy! I don't understand why you consider it as "not a bug" with all the details I sent, the use case and also how to reproduce it.
