### ISSUE TITLE
SHA1 Key not updating to Flutterflow

### ISSUE THREAD

**Issue by CANinfinity** [FlutterFlow/flutterflow-issues#1932]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Getting Error on Flutterflow that my SHA1 is incorrect

### Expected Behavior

Expected SHA1 key has been added to Firebase, And I have re-generated Firebase on Flutterflow, but still get the same error, does not matter what I do, how many times I update and regenerate, problem is not being resolved. I have asked support to assist and followed guidelines, but still no luck.

### Steps to Reproduce

SHA1 key not updating to Flutterflow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzPHqx89PxdtJ7q6JY+1voCk6KVscTIMziNZ+exUbfaL1BqQUduP7VElvZ7S+aVNcJGKLpDgewtGLjvzDK/pfJkmWRoh9/5FbFgvee2ijVcWtO7qeOXRDN/9nG2K0y6WFhBR+OrRsW1Uu2znzAOuAf3fDBOu/Zwh9f6PHaOI=

### Context

Yes, And I cannot publish to playstore due to this issue

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/69190557/bdfe6b60-ec9a-4da8-9d83-9fe7b9ed0061)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Android
- Browser name and version: Current Brave and Edge Version
- Operating system and version affected: Windows 11
```

**Comment by CANinfinity** [comment]
Good day

 

Thank you for the reply as per below, I will attempt to do it again as I have done so previously. Will provide feedback should I still not be successful.

 

Kind regards/Vriendelike Groete,

 

 







 

E-mail Disclaimer

The information contained in this email is confidential and without prejudice and may contain proprietary information. It is meant solely for the intended recipient. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted in reliance on this, is prohibited and may be unlawful. No liability or responsibility is accepted if information or data is, for whatever reason corrupted or does not reach its intended recipient. No warranty is given that this email is free of viruses. The views expressed in this email are, unless otherwise stated, those of the author and not those of  CANinfinity.  CANinfinity or its management reserves the right to monitor, intercept and block emails addressed to its users or take any other action in accordance with its email use policy.

**Comment by hariprasadms** [comment]
Hi @CANinfinity - What is the latest update about the issue. Let us know if this issue no more exists in your project so that we can close the issue. Thanks

**Comment by CANinfinity** [comment]
Good day Hari

 

As per previous email sent, I had a look and downloaded the keystore as mentioned, however it does not give me an option to upload it, only give me an option to regenerate the key.

 

We did already regenerate the key before I logged an issue, but still does not seem to come right. Please also take note that we have an live app on the playstore before we moved over to flutterflow, should that help in any event.

 

Kind regards/Vriendelike Groete,

 

 







 

E-mail Disclaimer

The information contained in this email is confidential and without prejudice and may contain proprietary information. It is meant solely for the intended recipient. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted in reliance on this, is prohibited and may be unlawful. No liability or responsibility is accepted if information or data is, for whatever reason corrupted or does not reach its intended recipient. No warranty is given that this email is free of viruses. The views expressed in this email are, unless otherwise stated, those of the author and not those of  CANinfinity.  CANinfinity or its management reserves the right to monitor, intercept and block emails addressed to its users or take any other action in accordance with its email use policy.

**Comment by takashiff** [comment]
Hello, thank you for your bug report. It looks like you may need to reset your upload key in the Google Play Console, since the application has already been uploaded previously before migrating to FlutterFlow. You can check this thread [here](https://support.google.com/googleplay/android-developer/community-video/239160561/how-to-reset-your-google-play-developer-console-app-upload-key?hl=en) and try uploading your regenerated key. Please let me know if the issue persists after that. Thank you for your patience.

**Comment by takashiff** [comment]
Marking as closed due to inactivity. If this issue persists, please reply in this thread so that the ticket can be reopened.
