### ISSUE TITLE
CheckboxGroup adds inconsistent padding accross platforms

### ISSUE THREAD

**Issue by ZandrePakwe** [FlutterFlow/flutterflow-issues#1933]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The CheckboxGroup Component has got top and bottom padding that is inconsistent between web, ios and android, with no way to customise it. It seems to be the case when you add the checkboxGroup component in a page that is not marked as a safe area. 
See screenshots below:
web - 
<img width="432" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145122041/4dfac897-63d2-4449-9ebf-aa68b2b06f1c">

android -  
<img width="442" alt="Screenshot 2023-11-30 at 10 01 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145122041/3f2834bf-77ea-4c76-ae81-d545f04d5f03">
 ios - 
<img width="448" alt="Screenshot 2023-11-30 at 10 03 39 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145122041/f86e7704-e62d-4aaa-9d8e-98e216f6e80a">

When I add the value `padding: EdgeInsets.zero,` to the builder function of the checkboxGroup component of flutter flow `flutter_flow_checkbox_group.dart` I get the desired response. However it is not possible to customise the start spacing and end spacing of the underlying listview component from the flutter flow ui.
 

### Expected Behavior

I would like for the padding to be consistent or configurable so that you get the expected styling for the component

### Steps to Reproduce

1. Create a new app on flutter flow.
2. remove the safe area toggle
3. add a checkbox group component with some options
4. (optional) wrap in a column and add any element on top to more easily see the padding being applied and differences between environments.
5. run app on ios, android and on web, and observe the differing paddings between the element on top(or below) the checkbox group and the checkbox group.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sz/Hqx89gocNf7qr2a+9VhiYQMjsharhE0+xqEBMjCOKtEO0PXOv9SE1WXcugd1Y3fVH9gn00zNrZhvPhUMcoB0iqf6lq3bhMZgzKf3OgMq6pCZGobXMnQNJVCHKzyrTYgAx9G/V1LlYi7VyUHeiydA7YNO/OIVcjOf2jOrr4nVaQLA/jDyJZ2iZecCfn

### Context

I want to show a checkbox group on a page specifically built to not make use of safe area, however I now get large areas of dead space on that screen with on actual devices (and this was not visible on the test mode for the app so only discovered the issue after deploying the app to the store.

### Visual documentation

Screenshot of the blank test app to reprodice the bug - note safe area view is disabled: 
<img width="1728" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145122041/2ef8e60c-f31c-4dc1-8104-657b14c3c722">
this can be achieved by following the steps to reproduce steps laid out above.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS, android, Web
- Browser name and version: Chrome 119
- Operating system and version affected: MacOS Sonoma 14.1.1
```

**Comment by wenkaifan0720** [comment]
Hi @ZandrePakwe. This should be fixed in our next update. Thanks!
