### ISSUE TITLE
Custom icon widget show error when download APK

### ISSUE THREAD

**Issue by badnguyenky** [FlutterFlow/flutterflow-issues#1937]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I create a custom icon widget code to render an icon by iconCode and fontFamily from my API, it compile and run successfully in test mode, but when I download APK it shows this error
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/52956049/9c9b9106-e361-4f0e-8a96-089181964d77)

### Expected Behavior

Download APK successfully

### Steps to Reproduce

1. Create a custom widget
2. Compile with no error showing
3. Using custom widget
4. Download APK and the error appears

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfKAz4pgrshE15SJc8Ewnjw5JkQjaOdMktZBaCsofePrOpkAf8/7UFtUOeqqT1FDeU60mnEX/MqLvfH1O/A4ZByrG6k7wsxqSALKRn6QMMnWEa63b0FRO99VIUi45pmKniNTNtZtS3wQ7zuYed6sSgrZHrL4CzESQua4XdeK2SrDX1iXc2URm05KZDPz

### Context

I really to download the APK to send to my customer, 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/52956049/6f08a68e-7d2b-4cf5-9548-c7db4f0dc9a9)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/52956049/468b2329-5059-43dc-a03f-3b8aa677b309)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/52956049/9c9b9106-e361-4f0e-8a96-089181964d77)

### Additional Info

Project: https://app.flutterflow.io/project/scan-q-r-code-cekmib

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 119.0.6045.160 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 22H2
```

**Comment by badnguyenky** [comment]
the API response look like this :
[
    {
        ...,
        "icon":"0xf05a0",
        "fontFamily":"MaterialIcons"
    }
],
...

**Comment by hariprasadms** [comment]
Hi @badnguyenky - Thanks for submitting the issue. Are you still experiencing the issue? I copied your CW code in a different project and can download the apk with no issues.

**Comment by hariprasadms** [comment]
Are you still experiencing the issue ?

**Comment by hariprasadms** [comment]
Hi @badnguyenky - As there is no further updates on the issue, I presume it has been resolved for you. Thanks
