### ISSUE TITLE
Invalid HTTP method/URL pair. Retrive url from firebase storage 

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#1939]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to call an api from builship which get 3 parameters and one of the parameters is url from storage where i have before upload a file and store the link in one of the field, the issue that when the file is store is store inside users/userid/id/upload, which i do not think FF is not getting the correct path 

### Expected Behavior

The correct should be retrive and point to correct path 

### Steps to Reproduce

1) store a file in storage 
2) sae the url in one of field 
3) try to call the api which require the url 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXk/KA4YlgrupE1qX+b+0wmScwFnIca+YZhOtHRgIbfbmsOpYtbuvTdVpeTumkSglcBlqZpD0DpNLzis7xU8BcITCEQ5Rzyc1iFzndTky7VLKUCs+dPGpCGcRRGGGP5ImJ3QpCH/psWEEtig/GSw==

### Context

is stop me from calling the api and continue the work 

### Visual documentation

<img width="662" alt="Screenshot 2023-12-01 at 09 40 49" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/2f53c24d-5cba-4e88-9867-fae281cbe619">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: web
- Browser name and version: chrome 
- Operating system and version affected: mac pro
```

**Comment by hariprasadms** [comment]
Hi @sergedahdouh - Thanks for submitting the issue. The image you given above. It shows you are calling the endpoint in postman tool and the response is 400. What is the response in FF editor ? 

The details are bit confusing. You have image url stored in users collection and trying to access it through build ship end point inside Flutter Flow. As long as user is authenticated successfully and user id is matching the document you are looking for and the image url is valid, you should be able to fetch the image with no issues.
