### ISSUE TITLE
Nested radio buttons not functioning 

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1940]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Sometimes (key word) when a radio button is hidden and shown when a different radio button is toggled to a specific value, it becomes un-clickable. This issue is pretty common and there is a very dumb and inefficient workaround, however it looks like a bug that could be fixed.

### Expected Behavior

When a radio button is visible (and not disabled) it should be clickable.

### Steps to Reproduce

1. Create new page
2. Add radio button with several values
3. Add radio button that is visible only when a specific value from the previous radio button is clicked
4. Perform this nested combination a couple of times
5. Try changing the value of the radio button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMmBx891oeJE0M/ucO9Vgig7HDo4U600t9pEZxMYGOPdOoYUP8+kM0RBOdCrTAlcOGGkiWoW3MmPheLMV+0EaCqYf4g91btiWAvgWnm6M6q4FJWgYWtSTZhWIB2iy5602B14VfduSnNh7HGQF/OUdCndJL7zDEg0D6/LZO4=

### Context

When creating a complex form, you want to lead the users to their solution by giving them different options based on their previous input. This is why we need a very seamless experience in navigating through the user input.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/0bc92126-595b-48b6-a17f-76a660c3996f

### Environment

```markdown
- FlutterFlow version: v3.13.7 (released Dec 1, 2023)
- Platform: MacOS Desktop;
- Browser name and version: Chrome 119.0.6045.159
- Operating system and version affected: macOS Sonoma 14.1
```

**Comment by hariprasadms** [comment]
Hi @tinrunje - Thanks for submitting the issue. I have tested the above steps and can see its working as expected. I believe step 3 you are handling using boolean flags. I looked at your project but could not locate the page where you got the issue. Considering the nature of the issue, we need a blank project with issue re producible steps setup. Please update the issue with required details.

**Comment by tinrunje** [comment]
Hey @hariprasadms - my bad for not mentioning I have these radio buttons in columns (although it sometimes even breaks when they are not in columns - but columns always break it). I created a project with the setup so here is everything you might need:

**The project:** 
https://app.flutterflow.io/project/radio-button-error-5al9t4

**Steps to reproduce:**
1. On "Radio 1" press "4"
2. On "Radio 2" press anything and then press "c"
3. On "Radio 5" press anything
4. Now go back to "Radio 1" and press on "5"
5. On "Radio 3" press anything ... nothing will happen

**Bug report for "Radio 3":**
IT4KhvLl249Oj7xZ0KXqKcEw+CQvKUA2a+Y0lsF+Zws2F4uuG7YUXPTBVFJuOs/jSnNcP2Gi8WQKp+jNvdrhCsctPiiCf6pj1qh+ZgHNVnKmWrqJC4eKY3ZCEflTI0uHzbS42RNvCM1ZLllm1F+UIt/IExXdN7r0IUYWRc+IBKD7jkqkLAzCXn0Jg1ZSfCvr

**Video showing it:**
https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/84c0b325-cb36-48e6-ad35-15555aa32efe

**Comment by tinrunje** [comment]
@hariprasadms wow ... that's insane. Can I ask: what's your FF version? Are you using Mac or windows? Web or app?
I mean I've been having this issue for a very very long time so it has been going on over multiple updates so I'm kind of impressed that it works for you.
Also, I get this issue in my production app on mobile (both iOS and Android) although I have found a really dumb trick to fix it with multiple actions. Here's the video of it not working in an app in production as I forgot to add the "trick" for this set of radio buttons:
Uploading RPReplay_Final1701455384.MP4…

**Comment by hariprasadms** [comment]
@tinrunje - I am using the same version - FlutterFlow version: v3.13.7 (released Dec 1, 2023) and FF web app.
