### ISSUE TITLE
Canvaskit doesnt load external images

### ISSUE THREAD

**Issue by eddiebrasil** [FlutterFlow/flutterflow-issues#1941]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In my website, when in Canvaskit, images that is on my server doesnt load in the website. If I turn off, shows normally. In apps also shows normally.

### Expected Behavior

Show all external images

### Steps to Reproduce

Open main page of my website.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn1sJVOxcBE7a6Jbu9ajSQvNjM5a+Yr0cpBZywgfZzzBLN/fPfQP01WXs/nTAhpM1q2p141//SKk/HQUfkqYDGVY4hIypZAUQyVJVq7V7WTF7WWVnx6TMpQCkid5LSnuwp7LshodVo92melfvDKFz/aCb22C2owSq/LZO4=

### Context

Want to use Canvaskit because if has faster loading time.

### Visual documentation

Round circles supposed to have images in it.

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Edge or Chrome browser
- Browser name and version: Edge
- Operating system and version affected: WIndows 11
```

**Comment by hariprasadms** [comment]
Hi @eddiebrasil - This is related to CORS settings at your server side where images are stored. If it is firebase follow the steps in this doc - https://thehotcode.com/firebase-gcloud-fix-cors-issues/. Othere server, follow their CORS settings details, it should work with no issues. Thanks
