### ISSUE TITLE
Custom 'Transition Type' not working

### ISSUE THREAD

**Issue by inigousoa** [FlutterFlow/flutterflow-issues#1942]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Transition types between page navigation not working, popping instantly instead. Only default transition works in some cases. 
Noticed it on my main project yesterday night, confirmed it on my dummy project this morning.

### Expected Behavior

Transitions should work

### Steps to Reproduce

https://app.flutterflow.io/project/route-testing-0p1xr8

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not being detected as bug by vscode

### Context

Page navigation

### Visual documentation

<img width="351" alt="Screenshot 2023-12-01 at 4 10 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/147109659/1e3ef25c-6bac-4131-9393-628937f8d61d">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by aaronmt93** [comment]
also having this issue

**Comment by andresacero-brokerfy** [comment]
The problem here

**Comment by anvaesi** [comment]
Same problem for a long time

**Comment by inigousoa** [comment]
@anvaesi @aaronmt93 @andresacero-brokerfy seems to have been fixed! at least its working for me at the moment. i would suggest checking your projects

**Comment by Deffer7** [comment]
Same problem for a long time too

**Comment by aaronmt93** [comment]
yep working for me now!

**Comment by agreaves** [comment]
Yep! Sorry should have updated, but we released a fix this morning :)
