### ISSUE TITLE
Existing custom function breaking : Compiling with sound null safety | Supabase

### ISSUE THREAD

**Issue by Rodriq** [FlutterFlow/flutterflow-issues#1943]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since last night I noticed my custom function misbehaving.
1. I am unable to use a function that returns an integer tin a conditional because for some reason it gets translated to string.
2. When I go back to test a function that was functional before I get complaints about Supabase dependencies: This is visible in more than one project across two different organizations

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/39289592/8bd8a23e-5c1f-4eaf-84ae-ecea5529868f)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/39289592/970e1f1f-2c3b-4d2f-9ca0-8b7532824660)

### Expected Behavior

A simple function that takes a string and returns the same string should work or better still let my existing functions work.

### Steps to Reproduce

1. Working on  Flutterflow v4.0, Flutter 3.13.7
---
2. Just create a function on a project that has supabase linked.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMjfsItPvtxE+s7uasBVhiIwFjMLa+cF0+1+FB4YJYz2P4YhduClS0NKT9/keXNmIVG0mlgB//zQjt7lNvAqNUmeRak60JVASgH/WT+tWrKrOrWaRH9SRdxhCH7G57aNvQhTIfpoL3wu31z6N63qNleeY8aSfxBlZ7vfcPo=

### Context

Delay.

### Visual documentation

Pasted above

### Additional Info

Nothing

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by olivierb24** [comment]
I'm getting the same issue for all my functions.

**Comment by Rodriq** [comment]
Closes #1951 Same issue reported again

**Comment by katherineqian** [comment]
Hi, thanks for reporting and sharing details. I submitted a fix and it should be reviewed and deployed in the next version. I apologize for the inconvenience that this caused.

**Comment by Rodriq** [comment]
> Hi, thanks for reporting and sharing details. I submitted a fix and it should be reviewed and deployed in the next version. I apologize for the inconvenience that this caused.

Is it possible for this to be shipped as a quick fix or something?
It is a hassle.

When approximately should we be expecting the next release?

**Comment by katherineqian** [comment]
The next release should be this Thursday.

**Comment by katherineqian** [comment]
Update, it didn't make it into this week's release so I'm hoping for next week. Hopefully it can work for you to test your functions in a local editor for now.

**Comment by Rodriq** [comment]
@katherineqian  That is too long. The issue is not that I can't test my functions.
The functions also appear broken when I try to use them in my app. And only works when I publish to the web.

This has slowed down my development process big time

**Comment by ankushlmp** [comment]
getting same issue in all my custom function

**Comment by katherineqian** [comment]
Hi, this has been fixed today in the recent update.
