### ISSUE TITLE
Lottie Animations are not visible on the web

### ISSUE THREAD

**Issue by cskonstantyn** [FlutterFlow/flutterflow-issues#1947]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Before I started, this was not an issue a month ago!
Using the Lottie Widget, I upload a file and it shows in the project itself and even animated, not static like it use to be, but when it is published to the web the Lottie animation does not show up anymore!
Here is the image of the project: 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121922639/aed23461-6867-4825-8474-87848e0ccfdd)
Here is the image of the published website

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121922639/448ed7f2-bd53-467d-9682-3bf53efc3d98)

The same issue occurs on any browser, and on phone, tablet and computer

### Expected Behavior

Well of course the expected behaviour would be for Lottie animation to show up and not only on the project page but also on the web where our client will go to....... It is our image......

### Steps to Reproduce

New page
Add Lottie Widget
Publish to web - see the issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glcr1z89goe5E176JKe9aoCUvH0QgRK00u9tuGEgdCLbyD4lzf8/BQBJtXbyndghAM2f9oHoKzMrSm9z1UccpGwStGdxx1qhqEQ3iJWW6M6qDBZGWSXFuGshPG2a957e3piVTLrBiSEIm712bfujJfBHZNOb4IUdAMeWaJdrXvgfuQ0SLb3kNh1JWeC/v

### Context

All of the pages across the whole app do not show the lotties anymore. How it affect us? The app is not usable T_T Many page on the app had lottie to make the user experience more pleasant and now all of them show empty boxes that make the app ugly! It is especially disappointing right after we choose to go for pro plan T_T

### Visual documentation

Here is the image of the project: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121922639/9847417b-55bf-4a34-9854-e3d68c0fa146)
Here is the image of the published website
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121922639/448ed7f2-bd53-467d-9682-3bf53efc3d98)

### Additional Info

It used to work everywhere and we did not even think it could be a problem, everything worked like a charm!!!! PLS FIX IT!

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Edge, Chrome
- Operating system and version affected: Desktop, iPhone, iPad
```

**Comment by cskonstantyn** [comment]
I noticed just now that I provided by accident a different page from the project, but regardless of the page the lotties  does not work in the whole project. They don't show up at all anywhere across whole project!

**Comment by hariprasadms** [comment]
Here you can see animations are working fine in both the palces, editor and deployed web mode. This is when lottie animations through network and also from assets. 

<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6c40d3dd-c6dc-4e20-9c7d-e390ad8956ae">

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6e7b817a-61bb-4a53-8e2e-4c9e0b9d0402

**Comment by cskonstantyn** [comment]
any suggestion on what's next?

**Comment by hariprasadms** [comment]
Please add more details about new problem you are experiencing.

**Comment by cskonstantyn** [comment]
what kind of details are you looking for?
