### ISSUE TITLE
Customize border and text color for disabled ChoiceChips

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1948]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

You only implemented the ability to change the background color when the choice chip are disabled, not the border and text color, which means it still is causing issues in themes:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/1c7b1f06-ddbc-41eb-b7e1-a33009a18dd5)

### Expected Behavior

add disabled border and text color so the fix is done properly not the half hearted attempt in  issue1482.

### Steps to Reproduce

see issue 1482.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

cannot complete multi them project has dont have full control over the apperance.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/016ca322-d71b-4d42-87bf-98fddf43d06a)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by OldFred2023** [comment]
Its stale because FF have failed to even look at the issue so far.

**Comment by OldFred2023** [comment]
nudge

**Comment by OldFred2023** [comment]
nudge

**Comment by aemelyanovff** [comment]
@OldFred2023 You can use conditional values to customize `ChoiceChips` colors when they are disabled. Just the same condition what you use to determine if the `ChoiceChips` widget should be disabled. Something like:

![Screenshot 2024-01-11 at 10 07 37 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/43af4f7e-d332-4de7-8a95-4462032b6fc2)
