### ISSUE TITLE
Yours QR scanner doesn't work in WEB. Can’t use 3d-party QR scanner (the flutter_barcode_scanner is outdated)

### ISSUE THREAD

**Issue by falcorrus** [FlutterFlow/flutterflow-issues#1949]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't use simple_barcode_scanner (install it as a custom widget). I got a compilation error.
I asked the developer and he answered "This is because your custom_widget and simple_barcode_scanner uses flutter_barcode_scanner internally. Hence version conflict is occurred. Please check and update version and see if it is working."

### Expected Behavior

Your QR scanner works in WEB or I need to install an external one.

### Steps to Reproduce

install https://pub.dev/packages/simple_barcode_scanner and make a custom widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Context

Yours QR scanner doesn't work in WEB so I needed to install an external one.

### Visual documentation

...

### Additional Info

Scanner developer:  https://pub.dev/packages/simple_barcode_scanner
CodingWithTashi/simple_barcode_scanner <[simple_barcode_scanner@noreply.github.com](mailto:[simple_barcode_scanner@noreply.github.com]

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 2, 2023
- Platform: Mac os (Sahoma Beta 14.2 (23C5047e))
- Browser name and version: Chrome 119.0.6045.199
- Operating system and version affected: web

Project: happyTest1201
Project ID: happy-test1201-r39qxp
FlutterFlow v4.0 released December 2, 2023
Flutter version is 3.13.7
```

**Comment by hariprasadms** [comment]
Hi, Thanks for submitting the issue. At this stage, we do not have immediate plan for QR code widget support for web platform. No ETA. In this case package conflicts error what you are seeing is expected. Thanks

**Comment by aemelyanovff** [comment]
Closing as not a bug.

**Comment by nicbyron** [comment]
+1 on feature request for qr code scanning on web
