### ISSUE TITLE
Test Function in custom function error

### ISSUE THREAD

**Issue by sergedah** [FlutterFlow/flutterflow-issues#1951]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you run a test on the function to do manual inputs, we get an error stating it is something to do with supabase. After looking into this, it could be related to supabase package.

### Expected Behavior

when you run the test is work and five error 

### Steps to Reproduce

1) create a function 
2) try to test it 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXk/KA4YlgrupE1qX+b+0wmScwGUwbUOc7j9VEGAsjCeKuP5kAZ8+lXFFCYuqHe2N+JWGgmkAE0vzUi97hIMcFGE2BbaZJwqt5UxDvUkOmbJCQEZaBOXAlTP9bGXXD1qSJoxZBJvB0V3Ms73GEFueub3qCf9qOYwx5e6fDbOY=

### Context

is anyoning that cant test the function 

### Visual documentation

<img width="1549" alt="Screenshot 2023-12-03 at 19 55 20" src="https://github.com/FlutterFlow/flutterflow-issues/assets/152044699/9b86af11-2ea1-42b2-a49b-84521300ce5f">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: web 
- Browser name and version :chrome 
- Operating system and version affected: mac pro
```

**Comment by hariprasadms** [comment]
Hi @sergedah - Thanks for submitting the issue. I can reproduce the issue. Thanks

**Comment by katherineqian** [comment]
Hi, thanks for reporting and sharing details. I submitted a fix and it should be reviewed and deployed in the next version. I apologize for the inconvenience that this caused.
