### ISSUE TITLE
undefined name 'kDebugMode'

### ISSUE THREAD

**Issue by sarim** [FlutterFlow/flutterflow-issues#1953]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Visibility -> Code Expression -> kDebugMode
shows the error undefined name 'kDebugMode'

### Expected Behavior

No error. Widget visible when in debug mode.

### Steps to Reproduce

1. In a widgets properties click visibility -> conditional
2. Select code expression
3.  `kDebugMode` as body
4. click check error button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

In the app sometimes its necessary to have widgets / functionality for developers eyes only. Suppose a button that only rendered in debug mode.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1235888/c49cef1c-174a-43e3-a99b-4c5fe0cea8ac)

### Additional Info

I also tried creating a function and `return kDebugMode` inside it. But in function I can't add import foundation for kDebugMode.

Potentially consider adding "Is Debug Mode" in Global Properties
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1235888/af9d5c26-c315-43b8-bdb5-11c667a563f2)

### Environment

```markdown
- FlutterFlow version: v4.0 Dec 2, 2023
- Platform: Web
- Browser name and version: Edge 119.0.2151.93
- Operating system and version affected: Windows 11
```

**Comment by sarim** [comment]
@hariprasadms do you mean true/false constants? They won't do what I'm trying to achieve. Imagine you have 10 special buttons throughout your app, its only for developer's testing purpose. If you use True/False constant you have to set true/false each time you test as developer vs sending to production. Using kDebugMode would do this automatically.

**Comment by ch-muhammad-adil** [comment]
kDebugMode is not even available in FlutterFlow custom functions ..
