### ISSUE TITLE
Links not clickable on Xiaomi devices (maybe more devices, but Xiaomi is tested)

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1959]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The action "Launch URL" is not functional on Xiaomi devices. Nothing happens.

### Expected Behavior

For the link to open when pressed on it.

### Steps to Reproduce

1. Create new page
2. Add a button 
3. Add an action to the button "Launch URL"
4. Enter any URL, something simple like "https://flutterflow.io"
5. Push to Google Play
6. Download on a Xiaomi device
7. Click the button with the action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcn635ZNvttZ+KX2KMBFijksKUQjRYEVmtYaaxIbN5PQCJkQO8nQPxJvOdeiYAlqe0ycp14zp8LSvYaSOPA3NTacbJtz/6luaDzyXl2uVbGTF7qBPHFtEeRgfGnE36e3hCUnWdBoW3giwE2hfdm9Qg3vNKb1DEQwSq/LZO4=

### Context

Buttons that lead the user to the browser don't function - e.g. privacy policy, t&c, ...

### Visual documentation

Xiaomi (shown on one button, but this goes for all buttons on all apps):
https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/d5fe32ec-4de1-4817-b9af-a7cfbc37f5b1

iPhone:
https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/d6d8128d-ef07-4bae-ba12-e48100abd6dc

### Environment

```markdown
- FlutterFlow version: v4.0 (released Dev 1, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 119.0.6045.199
- Operating system and version affected: macOS Sonoma 14.1
```

**Comment by hariprasadms** [comment]
Hi @tinrunje - Thanks for submitting the issue. I have tested these steps on android simulator. URL can launch fine with no issues. When you see url is not opening in mobile browser it is mostly because browser settings blocking it. Check the device browser settings looks all fine. Meanwhile, I can give try in real device as well.

**Comment by hariprasadms** [comment]
It would be great if you could try different kinds of Android devices as well. To confirm that it is unique to the type.

**Comment by tinrunje** [comment]
I tried all Android devices I have: LG, Xiaomi, Huawei & Samsung. Xiaomi is the only one of those 4 that doesn't work. I can also confirm that my clients only complained about Xiaomi's too.
On my Xiaomi I can't find any settings that could be related to this.

**Comment by tinrunje** [comment]
Alright @hariprasadms , so if there isn't anything you can do about this with FF, you can close this issue and I will share it across the Xiaomi development forums/teams.
