### ISSUE TITLE
The message "The email address is already in use....." does not appear in the translation menu

### ISSUE THREAD

**Issue by KreKdev** [FlutterFlow/flutterflow-issues#1960]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The message "The email address is already in use....." does not appear in the translation menu, because of this, when you use another language, the error message appears empty.

### Expected Behavior

In english: Error: "this email address is already in use by another account....."
In any other language: Error:
![flutterflow email message bug english](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/98be4706-44f6-4079-bbed-7989872c3b36)
![flutterflow email message bug portuguese](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/ecdaedfa-4ed0-45cf-8593-f8e0f8fec975)

### Steps to Reproduce

1. Use English language
2. Try to create a user with an email already registered
3. Change to another
4. Try again

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXjMrqx891rsBE1ZfUbu0wp2EwGUwbUOc7j9VEGAsjCePkEO02YM7sYhBocuqHeAhceVL8pEMK0NbwuIbhDvQBHwedQb5i+c9fUxDhVj26VL3SCbqOW2hDI8ZTfxGn5Jm7gCYkBNJidVEjw0zzINiQb3qCf9qOYwx5e6fDbOY=

### Context

When users of another language try to register with the same email, they will only receive a generic error, not knowing that they have already registered.

### Visual documentation

I already added it above, but again:
![flutterflow email message bug english](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/98be4706-44f6-4079-bbed-7989872c3b36)
![flutterflow email message bug portuguese](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/ecdaedfa-4ed0-45cf-8593-f8e0f8fec975)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 1, 2023
Flutter version is 3.13.7
- Platform:Windows 10
- Browser name and version:Chrome is up to date
Version 119.0.6045.200 (Official Build) (64-bit)
- Operating system and version affected: Web
```

**Comment by victoriahuang1** [comment]
@Franco98404 yes, please open a new github issue with all of the required info to debug
