### ISSUE TITLE
Dependency added in the "Custom Actions" UI is not added to the pubspec file, nor loaded in the code

### ISSUE THREAD

**Issue by bnoeson** [FlutterFlow/flutterflow-issues#1962]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I add the [csv package](https://pub.dev/packages/csv/versions) to a custom action, it doesn't load in the application, and doesn't show up in the pubspec file.

### Expected Behavior

I expect that all these steps described below would lead to the package being added to the pubspec file and loaded in the application.

### Steps to Reproduce

- In a custom action, add code that uses the csv package parser ("print(CsvToListConverter());")
- Add the import 'package:csv/csv.dart';
- Add the csv dependency with the UI ("csv: ^5.0.0") to the file (for me "setupItemHive")
- Click the Refresh button
- Click the save button
- Click the compile button
- Run the application. I get an error : "setup_item_hive.dart:100 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'CsvToListConverter')", which means that the csv package was not loaded.
- Click "View Code", the package can not be found in the pubspec file.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kMrq05NgrsNY1qX6avlR/TgWOUs7ROY30e1udxc8J5zKB+wAYvf7P1FWTLznY39UOE20nXIz7PfqueDlUfU5F0+rUbp+wZBqUTzjQnKgMpibCcyzfW1SBcVgIBzH55+s2Qp/OtR1ZUYD1zuEJNytdHbtNrLLClgdIcmlJdeK2SrDX1iXc2URm05KZDPz

### Context

Trying to add some code to a custom action.

### Visual documentation

-

### Additional Info
I found a very similar issue experienced by another user: https://community.flutterflow.io/database-and-apis/post/what-have-changed-in-the-way-of-importing-libraries-pTKG5avLu84ot60.

### Environment

```markdown
- FlutterFlow version: 4.0.0
- Platform: Web
- Browser name and version: Chrome 119.0.6045.200
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @bnoeson - Thanks for submitting the issue. I see your project can run in debug mode with no issues. Are you still facing above mentioned error? If issue is resolved please let us know so that we can close the issue. Thanks

**Comment by bnoeson** [comment]
Hi Hari, thanks for replying. No it isn't solved, I had to move on with my project so I commented those lines out and made a workaround to fix the build.

**Comment by hariprasadms** [comment]
I appreciate the update. Set up a blank project with issue steps and share the project bug report code if you still want us to investigate the issue. This information is crucial to investigate the issue. Thanks

**Comment by bnoeson** [comment]
Code: ITFTlciB0It1mNte+Krca+5KnicvCUMdXOczitVEew4bCIj4B4Yif+ClRFFBTcCzaH5+O1aYuEgyzMLVkobIUO0pAzqWG5xizqtfEhPPbECuMMmUEartWGtTPJpUGUfG056vqx1SAOlfR1Yc3UOue+utEj+Cf9qOYwx5e6fDbOY=

- Added New custom action 'newCustomAction'
- Added csv: ^5.0.0 as a dependency
- Clicked the dependency refresh button
- Added import to csv dependency: import 'package:csv/csv.dart';
- Added a piece of code that uses the package
```
Future<void> newCustomAction() async {
  print(CsvToListConverter());
}
```
- Saved the "newCustomAction" file
- Added "newCustomAction" as an Initial action in custom files
- Click Test Mode button

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23740164/e548d2c3-eb05-4090-877d-ef7809bd9543)

**Comment by hariprasadms** [comment]
Thanks for the details. I can reproduce the issue. This happens mostly while adding dependency in actions. While adding dependencies in custom widgets package details can show up in pubspec.yaml file in code view and no errors.

**Comment by victoriahuang1** [comment]
Hi @bnoeson , is this still an issue for you? I cannot reproduce this in the latest Flutterflow version.

**Comment by bnoeson** [comment]
Yes indeed, it seems to be fixed! I will close the ticket.
