### ISSUE TITLE
Register redirection is override by default redirection

### ISSUE THREAD

**Issue by LeBlank0** [FlutterFlow/flutterflow-issues#1963]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a registerPage that redirect you to an page to fill some data before getting you to the homePage, on my homePage I have an action "onPageLoad" that logout anyone with an unverified email.
But 4/5 of the time when I register to my app I'm not redirected to this said page but to the register page instead.
What I think is happening is that the default redirect to the homePage (set up inside FlutterFlow/App Settings/App Details) is triggered right before the redirect I made after the register logic and therefore, the action to logout the user that is inside the homePage "onPageLoad" event is triggered.

Note :
In the video I'm redirected to the loginPage
First image is the default redirect options 
Second image is the homePage action
Third image is the register logic
The "ignore redirects" option is active on the register logic redirection only

### Expected Behavior

When an user register, he should be redirected every time to my custom page and not to the homePage which log him out

### Steps to Reproduce

- Create a registerPage (set as first page when unlogged), a homePage (set as first page when logged) and a page to add infos to an account after it is created
- Create your register logic with FireBase Email Auth
- On the homePage "onPageLoad" action, check if the user's email is verified and then log him out if not
- After the register logic send the user to the page that allow him to enter some datas like his name, phone... (check the "ignore redirects option")
- Launch your app and create an account
- You should not be able to register properly (try multiple time)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXj8nqy5d1xdxE16Xua8BGpycwGUwbUOc7j9VEGAsjCePoP+wqZ87RUExuYuqHegk6PmGIkmMxpKnXi9jXJ/FeHAqZR4Rm+IdTUxDvTjutaLq0O5GKOXAnQMJPCmmMy6S3hwlDJbNvWXgC3Ey6N+yQb3qCf9qOYwx5e6fDbOY=

### Context

I'm trying to build a Web App that simply allow people to fill a PDF with some data using Textfields.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/47787962/95375743-5856-4056-870c-23aa5bd5d363

### Additional Info

<img width="1438" alt="Capture d’écran 2023-12-05 à 17 47 36" src="https://github.com/FlutterFlow/flutterflow-issues/assets/47787962/02e7cb9b-ebda-4255-a7a8-00e053b03190">
<img width="1284" alt="Capture d’écran 2023-12-05 à 17 49 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/47787962/a71c85bb-9fa7-41da-bf96-a7ece3a02937">
<img width="1274" alt="Capture d’écran 2023-12-05 à 17 56 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/47787962/6887a878-f2ac-4f19-8873-cbdf7ef992ff">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 1, 2023, Flutter version 3.13.7
- Platform: Web
- Browser name and version: Chrome 119.0.6045.199 (Build officiel) (arm64)
- Operating system and version affected: MacOS 14.1.1(23B81) and Windows10
```

**Comment by hariprasadms** [comment]
Hi @LeBlank0 - As per issue details, this is more related to actions configuration as per your use case. Hence I would suggest this issue is a candidate for FF support team to get their help to check your configurations correctness. Please reach support team for more help. Thanks

**Comment by LeBlank0** [comment]
I've seen that there is now a "skip on load..." button on the main page, idk if it's because of this post but thanks anyway it solved everything !
