### ISSUE TITLE
TextField onFocusChange not working when other Textfield selected

### ISSUE THREAD

**Issue by LeBlank0** [FlutterFlow/flutterflow-issues#1964]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page with multiples TextFields, they are supposed to update some data in my Firebase DB when the onFocusChange trigger is triggered, It works well whenever you change the focus unless the "focus change" action is to select another TextField, either by clicking another TextField or by pressing "Tab". 
So to summarize this action only works when you click on a random pixel to unselect the TextField but not when you select another TextField.

### Expected Behavior

The expected behavior is for the action event to be triggered when I change my focus from a TextField to another TextField.

### Steps to Reproduce

- Create a page
- Add 2 or more TextFields
- Add action on their "onFocusChange" trigger to change some data in a Firebase DB
- Enter some data in the first TextField and then select another TextField without unselecting the first one
- Your data will not be saved to your Firebase DB

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXj8nqy5d1xdxE16Xua8BGpycwGVAbbZI7jNUbdwEjGIjJP4kQPPWlRFVBcNCoTQlDMESmmkQx0MrIid7xMPZfYE+dbtldz89iVAuVYFige5OBO5OKZWhBI5lUBUii0Z6onh5vIbNhSHdl22GUAuqscALsO5DBImdISq/LZO4=

### Context

I'm trying to build a Web App that simply allow people to fill a PDF with some data using Textfields.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/47787962/36a1be23-db27-4fb8-ae71-65fdaf1447ad

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 1, 2023, Flutter version 3.13.7
- Platform: Web
- Browser name and version: Chrome 119.0.6045.199 (Build officiel) (arm64)
- Operating system and version affected: MacOS 14.1.1(23B81) and Windows10
```

**Comment by hariprasadms** [comment]
Hi @LeBlank0 - Thanks for submitting the issue. I looked at your project and the page/component where you got issue. you got a custom action to handle the FB collection updates based on some condition when text field focus changes. 

While I am testing the same steps using FF create or update documents actions, I can see that text focus changes in anyways, it can trigger the actions. Looking at this, I can presume your custom action which you got FB collection updates code needs a bit of update based on your use cases. 

Please update us. Thanks

**Comment by LeBlank0** [comment]
Hello, thanks for your answer, this is kinda weird because there is literally no difference wether you click on a textfield or on nothing about the function call, it's juste the "focus change" trigger that calls my code. I'll try to post this in the community, but I think that this is an error from FlutterFlow maybe just with custom functions ?

**Comment by hariprasadms** [comment]
Hi @LeBlank0 - Thanks for reply. Sure look for community help and see if there are more users experience the issue with the same configurations. so we can re open the issue and start investigating. For now I am going to close the issue. Thanks
