### ISSUE TITLE
"List Is Set and Not Empty" conditional action error

### ISSUE THREAD

**Issue by LeBlank0** [FlutterFlow/flutterflow-issues#1965]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- When I trigger a conditional action depending on whether a List inside of my FireBase DB is set or not, the app crashs. It seems like the "Is Set and Not Empty" conditions does not check Lists and therefore the app crashs. (Note that on the video there is also no error showing)

### Expected Behavior

My conditional action should work properly depending on whether or not my List is set/empty or not.

### Steps to Reproduce

- Create a page
- Create an user with a List of Strings inside
- Fill this list with some data (or don't create anything, neither option works)
- Add action "onPageLoad" on any page (or any other action that you can trigger, this was just my exact example) that checks if this said List is empty and do something depending on the result
- Start the Test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXj8nqy5d1xdxE16Xua8BGpycwGUwbUOc7j9VEGAsjCePoP+wqZ87RUExuYuqHegk6PmGIkmMxpKnXi9jXJ/FeHAqZR4Rm+IdTUxDvTjutaLq0O5GKOXAnQMJPCmmMy6S3hwlDJbNvWXgC3Ey6N+yQb3qCf9qOYwx5e6fDbOY=

### Context

I'm trying to build a Web App that simply allow people to fill a PDF with some data using Textfields.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/47787962/4a1db2a4-135d-4f43-8f22-426a8f3991b8

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 1, 2023, Flutter version 3.13.7
- Platform: Web
- Browser name and version: Chrome 119.0.6045.199 (Build officiel) (arm64)
- Operating system and version affected: MacOS 14.1.1(23B81) and Windows10
```

**Comment by wenkaifan0720** [comment]
Should be fixed in our next update. Thanks for reporting!
