### ISSUE TITLE
cannot put a negative number in API testing

### ISSUE THREAD

**Issue by alexjordi** [FlutterFlow/flutterflow-issues#1968]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Input doesn't allow you to add a negative number, even if this is a totally legit input. So for center point, I cannot put in a negative coordinate:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/129039815/83f5d93d-7989-4b82-bc04-3b193a75f024)

### Expected Behavior

Should let me put whatever number I want. My endpoint can deal with invalid coordinates.

### Steps to Reproduce

Just try to add a list of negative numbers as an input

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

Its annoying that I can test my endpoint with a valid coordinate

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/129039815/c13b3a3c-ccc7-4386-9523-e3669f30bb6f)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by victoriahuang1** [comment]
Hi @alexjordi , thanks for the report. I have made changes on our end that should have this resolved once deployed.
