### ISSUE TITLE
I can't push to GitHub

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1971]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't push to GitHub

### Expected Behavior

I should be able to push to GitHub

### Steps to Reproduce

1. Go to the Developer Menu
2. Click on Push to Repository
3. Now you see the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z/Lqx89Jpbxa1s+NKcBv9SM5KWF9bbsrm+17aCosfZT2BLMcec/RVERvZ+LmSgliImaJmWoW3N7vvePDNsI4YEuuc4A51rlUajrKeFGnVZC7FJWgZ0FfFtFPIGnF1pi7rRBCOvdtdUIY2F2Pf+m9cCbDH6bFNXoWDa/LZO4=

### Context

I want do a push to my repository

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/57f27df0-4553-45f6-aae0-8cce0cecf690)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released November 28, 2023 - Flutter version is 3.137
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)
- Operating system and version affected: W11 23H2
```

**Comment by hariprasadms** [comment]
Hi @Franco98404 , Thanks for submitting the issue. The message say your repository is not yet initialised. Did you check that please ?
Follow steps here - https://docs.flutterflow.io/settings-and-integrations/integrations/github

**Comment by hariprasadms** [comment]
Just checked. Git push working with no issues. Another point to check, make sure you project not showing up any errors. 

<img width="1188" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a02b5441-794d-472c-83ba-0cef2957ff05">

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Are you still experiencing the issue ?

**Comment by Franco98404** [comment]
> Hi @Franco98404 - Are you still experiencing the issue ?

I no longer have an active account to test

**Comment by Franco98404** [comment]
@hariprasadms Really? That is the solution? I unsubscribed from FF because of this and many other bugs and they have no intention of fixing it?

**Comment by Franco98404** [comment]
Still have the bug... @hariprasadms @agreaves
