### ISSUE TITLE
*Extreme* bug with backend API calls

### ISSUE THREAD

**Issue by alturic** [FlutterFlow/flutterflow-issues#1975]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Concise would simply be there is some sort of loop happening with Backend API calls that certainly should not be happening.

### Expected Behavior

What I would expect, literally, is 1 API call to the endpoint any time I navigate *to* the MyItems page. I certainly would *not* expect navigation to *other* pages to call the API call that is only assigned to the MyItems page, let alone call it multiple times.

### Steps to Reproduce

There are two pages, Home and MyItems. When associating a Backend API call with a ListView on MyItems the first navigation to the page results in 1 API call - expected. However, randomly scrolling/touching something in the list (can't narrow down what it is) results in yet another API call. That's not even the biggest bug with this. There are a few more issues:

1.) Navigating away from that page, back to Home, results in *multiple* calls to this endpoint.
2.) Reloading the Home route (from sidenav) results in *multiple* calls to the endpoint that is, afaik, only supposed to be ran on the MyItems pageload.
3.) Navigating back to the MyItems page results in even more multiple calls to this endpoint.
4) Rinse/repeat and the worst part of it all, every time you go from Home back to MyItems it adds yet *another* call to the endpoint. So yes, I am saying if I go from Home->MyItems->Home->MyItems->Home->MyItems I can just keep increasing the amount of calls to the endpoint seemingly to infinity.

![flutterflow](https://github.com/FlutterFlow/flutterflow-issues/assets/28596624/439c5019-256f-4bb4-8cc5-6ce90c063a7b)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8jc35Ngrulc7aXqdvlahSQRNVg2RI0SlcpBZzUYF5SuCLMqY8mnPhdoZ/WkTXw7fWeMp14x3NrPjobTCflfIQmCGak51odyERbMRki6MJOTF7WBP3N5L9JTIEjD4cKngxUkJtFpWCUg22eYOtm+dHXbQJjuC0Q8Sq/LZO4=

### Context

I'm looking to have a single API call be made on navigating to a page which is seemingly what the expected behavior reads to be.

### Visual documentation

Attached above.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Android
- Browser name and version: Chrome/119.0.6045.200
- Operating system and version affected: Windows 10
```

**Comment by shavenple** [comment]
I am having the same issue with API calls being duplicated as I navigate my app.  This is new as of about a week ago so in line with this ticket.  Even when navigating to pages with no calls, it duplicates previous calls for seemingly no reason.  My backend charges per API call so this bug is blowing up my costs and making my app unusable.  Any updates on this bug?

**Comment by alturic** [comment]
So, I have to ask, am I doing something wrong with API calls as backend queries are ultimately useless with this behavior, or is this not considered a huge issue to the FF team? @hariprasadms

**Comment by aemelyanovff** [comment]
@alturic Please [enable caching](https://docs.flutterflow.io/data-and-backend/backend-query#backend-query-caching) for your query - it should resolve the issue.

**Comment by alturic** [comment]
Very strange bug then how caching would prevent it from *multiplying* the amount of calls every time you load the page. However, that's just a bandaid, not a fix.

**Comment by aemelyanovff** [comment]
Backend queries run every time the page is updated because the query parameter could have been updated. Enabling caching prevents it from running if parameters didn't change. I agree it's not always the most intuitive behavior, but we aren't planning to change it in the near future - our recommendation is to enable caching.

**Comment by alturic** [comment]
I want to be clear on something as it *seems* like it may have been missed. None of us would have any issue with it running the query every time the route was loaded - that's just the exact expected behavior.

What the issue is, is that if I load the route, it makes a call - perfect, expected behavior. When I navigate away, and then come back to the route, it makes 2 calls - why? If I navigate away and then come back, it makes 3 calls... why? How is anywhere near expected?

The "change" would be literally fixing the bug that it doesn't only make 1 call per route load.

**Comment by aemelyanovff** [comment]
When you navigate away from a page, Flutter (not just FlutterFlow) still keeps the previous page alive in case you navigate back to it, and it can still run queries on certain events. You can change it if you disable "Allow Back Navigation" in your "Navigate" action, but I don't think you can do it with nav bars.

It's a long story why it is the way it is, but enabling query caching solves the vast majority of practical problems with duplicate query calls.

**Comment by alturic** [comment]
Ha, I didn't even know Allow Back Navigation would have done that, but I already have that off because I didn't want people to hit the back button and have it "go back" (unsure if that's what it even was doing but whatever). I don't think I use nav bars like you mean, I use SideNav/drawer navigation.

I will possibly test it with the query cache aspect, but I have a hard time believing that the cache would not have it duplicate a bunch of queries based on my example simply because the cache was expired. I firmly believe if I had caching on, and I `visited -> left -> visited -> left -> visited -> cache expired -> left -> visited ` it would be 3 or 4 queries and not just 1 as the only thing we've changed fundamentally is preventing it from making all these queries against the actual endpoint while it was cached.

**Comment by prajwaldhatti123** [comment]
Bro please get back to me if you solved that issue even I’m facing the same

**Comment by navid-ka** [comment]
This is still an issue.

**Comment by lucassmaestri** [comment]
@aemelyanovff, I'm still waiting for a practical solution to this issue. How can query caching be enabled when the query is triggered by an action?
