### ISSUE TITLE
Deployments to Play Store failing because FlutterFlow is using deprecated version of Google Play Billing Library

### ISSUE THREAD

**Issue by ebamoh1** [FlutterFlow/flutterflow-issues#1976]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I successfully deployed an update to Apple App Store but for Play Store, I got the following message that says FF is using an old version of Google Play Billing (which I suspect is related to the Google Play Billing Library and RevenueCat SDK natively built into FF (the purchases_flutter dependency being used by default in FF code is v4 when the latest version is v6).

I had received emails some months ago from Google Play and RevenueCat separately about the fact that my deployed app relied on an older version of Play Billing Library (PBL) and that PBL v4 will be deprecated on Nov. 1 so devs should migrate to the newer versions of PBL and the updated RevenueCat SDK, respectively. I thought FF would have received similar messages and addressed this in their native integrations so I didn't both but it looks like that hasn't happened.

I've reached out to FlutterFlow's Support but I haven't heard back from them and no one has responded to my question on the Community page (https://community.flutterflow.io/c/bugs/post/unable-to-deploy-to-play-store-because-ff-using-old-version-of-google-0pZlxegxEyrkndr) so I thought I'd ask the question here as I believe it's not unique to me and will apply to all FF users looking to deploy to the Play Store going forward. See error image below.

![Screenshot 2023-12-05 at 11 30 25 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/135924498/2edf71e3-f476-44e9-a5df-8cbcb637e247)

### Expected Behavior

I expect to be able to deploy to the Play Store using CodeMagic in the "Mobile Deployment" page in FF.

### Steps to Reproduce

1. Go to "Settings and Integrations".
2. Go to the "Mobile Deployment" page and click on "Deploy to Play Store".
3. The deployment will fail and you can view the logs for the failed deployment in the "Status" section of the Play Store section of the page. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk87buJJOsbQD14SJa+5shiIRH18cTIMziNZ+exUbfaL1BqQAPcz8S1ptZ7S6aVNcelD+uHId0634iuHtMMc7EzGBQaZl+c5ubALOe2iQbJiuEaW/P3dtGfFgIWK+38PUqh4nBLdiS14/2zqAeujKTXLDBOu/Zwh9f6PHaOI=

### Context

I'm unable to deploy new updates to my app on the Play Store so there's a disconnect between what's available on the iOS app and the Android app.

### Visual documentation

![Screenshot 2023-12-05 at 11 30 25 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/135924498/3fdee549-7d9f-4b50-8c55-f966c17ae3ee)

### Additional Info

N/A

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Edge Version 119.0.2151.97 (Official build) (arm64)
- Operating system and version affected: MacOS Ventura Version 13.3
```

**Comment by ebamoh1** [comment]
@hariprasadms @takashiff is the FF team aware of this issue, that new PlayStore deployments using FF are no longer possible because the Play Billing Library v4 FF uses has been deprecated and RevenueCat has also updated their SDK?

**Comment by ebamoh1** [comment]
this isn't stale. It's just that FF team hasn't acted on it

**Comment by MyTechAgent** [comment]
hey team, this exact thing is happening to me too. Can we please get someone to update the backend please?

**Comment by takashiff** [comment]
Hello @ebamoh1, I apologize for the late reply. Our `purchases_flutter` version has been upgraded to `6.0.0`, but it looks like your custom action `revenuecatPurchasePackage` is using version `4.12.0` for `purchases_flutter`, which is overriding the FlutterFlow native `6.0.0` version. If you change the version to `6.0.0` in your pubspec dependencies, this issue should be resolved.
