### ISSUE TITLE
Multi-select dropdown outputs string instead of list. Generated code has compiler error assigning String to List<String>

### ISSUE THREAD

**Issue by Murphy-Joe** [FlutterFlow/flutterflow-issues#1977]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="454" alt="Screenshot 2023-12-07 at 5 56 22 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/55860945/591b5a0e-1796-489d-b026-e4c65a6f5870">
<img width="788" alt="Screenshot 2023-12-07 at 5 57 05 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/55860945/e6bfc837-104f-4862-b891-af20112fbb38">

### Expected Behavior

Multi-select dropdown value would be a list, not a string. 

### Steps to Reproduce

1) Create a new page
2) Add a DropDown widget
  a) define dropdown values as 1, 2, 3
  b) define dropdown labels as a, b, c
  c) toggle multi-select to on 
3) Download the code 
-> View compiler error in *_widget.dart file in the FlutterFlowDropDown
-> or in the FF UI, see attempt to use the "DropDown" value from Widget State and see that it is a string value instead of a list

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzMrqx5B1xMtJ7r6ILO5FuCUQJkMcTIAvm+0aYz0bfL7rBqQfP+PRUxdWTcDhaVNcAmGGknsCwtKOv/PhN8E3PQWdQLpNzqgNVgLke2ineKayEZOOY0QnHd1gC2aF36uN2xFBKshfclkuwF6mAeqvEw/DFOu/Zwh9f6PHaOI=

### Context

I am trying to allow the user to select multiple contacts to send invites to.  The dropdown list is preferable as the list of contacts is likely small and I'd like to save space. 

### Visual documentation

<img width="1430" alt="Screenshot 2023-12-07 at 6 11 37 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/55860945/f515d06b-db67-4ec3-8f79-146ae9e6b954">
<img width="876" alt="Screenshot 2023-12-07 at 6 12 31 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/55860945/1c9a1f29-1014-4088-85c6-7bce2335b163">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 6, 2023 - Flutter version is 3.13.7
- Platform: MacOS
- Browser name and version: Safari and Chrome latest, not browser related
- Operating system and version affected: macOS 14.0
```

**Comment by Murphy-Joe** [comment]
Addendum: this seems to only be an issue when I choose "Add Option Labels".

**Comment by Murphy-Joe** [comment]
And this seems to be the fix in *_model.dart ..change dropdown value from List<String> to String.  Takes care of the compiler error in *_widget.dart

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/55860945/2effcab8-1d18-492e-8e23-d71ef19b89eb)

<img width="613" alt="Screenshot 2023-12-07 at 9 05 54 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/55860945/641b8d5c-42cf-410a-9ac5-53bd07496fb1">

**Comment by Murphy-Joe** [comment]
No eyes on this? I thought it was a pretty specific and easily reproducible bug.  A comment would have went a long way

**Comment by J-Nius** [comment]
I also encountered this issue. I can confirm that the error only occurs when the dropdown has both "Add Option Labels" and "Allow Multi-Select" enabled. Adding any value to the widget is not required for the issue to occur.

**Comment by marektomczyk** [comment]
Any updates?

**Comment by takashiff** [comment]
Hello @marektomczyk, I apologize for the delayed response. We have put in a fix for this issue recently, and it should be reflected in the next couple of weeks. Thank you for your patience!
