### ISSUE TITLE
List View pagination is not working. All items are getting queried

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#1978]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list view which retrieves data from Firestore. I have activated the infinite scroll and set the page size to 25. I have checked the network traffic of the app and found out that the full query (450 documents) is still loaded even though I am not scrolling. The whole collection seems to be loaded in packages but still everything. The documentation says the following: "It works by showing only a limited number of items (e.g., 15, 25) at first and loads subsequent items before the user reaches the end of the list. At the end of the list, a circular progress bar is visible as the new items are loaded." 

Unfortunately, this is not the case for me.

### Expected Behavior

Just load the visible documents and load more documents once I am reaching the end of the list

### Steps to Reproduce

1. create a new page
2. insert list view
3. implement back end query and turn on infinite scroll
4. See how many documents are being loaded

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not able to receive

### Context

This is issuing way to expensive queries which is unnecessary 

### Visual documentation

This is the network traffic displayed by Xcode once I click on the page with the list view. it can be seen that the data is being loaded over a longer period of time while already showing data

![Bildschirmfoto 2023-12-07 um 12 46 20](https://github.com/FlutterFlow/flutterflow-issues/assets/106015154/27446031-d25f-45c5-8cd4-15fa16c5c1a3)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: iOS and Android
```

**Comment by takashiff** [comment]
Hello @Jensoulus, thank you for your bug report. This looks to be a duplicate issue. Please refer to the [following issue](https://github.com/FlutterFlow/flutterflow-issues/issues/1881) for further updates. Thank you for your patience.
