### ISSUE TITLE
Dropdown Widget -Searchable box font color doesn't respect theme color

### ISSUE THREAD

**Issue by richenri** [FlutterFlow/flutterflow-issues#1979]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a dropbox named aulaAgendamento with gray background color. The option Is Searchable is enabled. My problem is that I cant change the text search color and the dafault is black. Due this, I cant see the information. Look the print
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11671340/c7066539-db65-4ca3-b2b5-2058efe98ecf)

My DarkTheme is disabled and I have this palette of color
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11671340/18775898-79b4-4f8a-b7e1-8f6e91a6ddc9)

As you can see, my primary text color is White.

I've contact the support team and they can't help me.

### Expected Behavior

Allow select the font color or use the Primary Text colos as default

### Steps to Reproduce

1. Use my theme color
2. Create a dropbox with searchable 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lsmBw5dgrs9J1oSJbsFFimU5Jm16R+cVjup7aCorB5DoPZsUecmkM0RVcOnnYG9lMWaZ/GoW3M7Tj+PXEvkFPU+CGb5Bzc1LWz3vf3O5RbrWFJWgOnR8BZ9jJ2q+35+33RBANfhtdGQC3DmMHNiydDLvQee2OjA8Da/LZO4=

### Context

The users can't see the informed text

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/11671340/57f50b05-3347-416c-b6bb-1d0a1e02910d

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: All (IOS, Android and Web
- Browser name and version: All
- Operating system and version affected: All
```

**Comment by richenri** [comment]
Any response?

**Comment by richenri** [comment]
Not yet! :(

**Comment by SameerShahzad99** [comment]
@richenri Thank you for sharing this, i am marking this issue as confirmed now!

**Comment by richenri** [comment]
Thanks @SameerShahzad99. Do you have any plans to fix it?

**Comment by aemelyanovff** [comment]
We'll add the ability to style the search text in the next update.

**Comment by richenri** [comment]
@aemelyanovff can you confirm the version? I've updated today and the problem is not fixed. I'm using the version 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11671340/6cdeafe4-20d7-4347-b70a-cc6b750b3041)

**Comment by richenri** [comment]
@aemelyanovff  It's OK now. Thanks

**Comment by rajat-westack** [comment]
Is this fixed ?
