### ISSUE TITLE
OTP verification not Working

### ISSUE THREAD

**Issue by Shrihari1357** [FlutterFlow/flutterflow-issues#198]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Phone authentication using OTP verification and Google sign in

## Current behavior (required)

It is not working. Verification fails and shows error.

## To Reproduce (required)

I downloaded app from flutterflow and added SHA1 and SHA 256 key in firebase settings. The app shows error as "Please verify that the correct package name and SHA 1 are configured in the Firebase Console.[A safety_net_token was passed, but no matching SHA 256 was registered in the Firebase console. Please make sure that this application's packageName/SHA256 pair is registered in the Firebase Console]

1.I added SHA1 and SHA 256 in firebase
2. I configured it in flutterflow as documentation says.
3.I downloaded the app
4.I run the app in my android device
5. It shows error as above mentioned

## Context (required)

The issue made my app not working because without authentication we can do anything in app

## Screenshots / recordings

![Screenshot_20221205_120308](https://user-images.githubusercontent.com/101409498/206090030-0907f18f-5dff-43da-99aa-5ca25d46068c.jpg)

![Screenshot_20221205_120308](https://user-images.githubusercontent.com/101409498/206089959-fabf5d74-a273-4d13-8a44-066a6b8f5ea5.jpg)

## Your environment

* Version of FlutterFlow used: nov18 2022 released version
* Platform (e.g. Web, MacOS Desktop): Windows 
* Browser name and version: Chrome latest version
* Operating system and version (desktop or mobile):Windows 11, android 12

**Comment by Shrihari1357** [comment]
I think firebase changed security to play integrity so flutterflow is not upgraded for that one.. Can flutter flow team can give updates on it?

**Comment by organicnz** [comment]
Hi @Shrihari1357. Thank you for adding this issue 🙂

Sorry for the late response, mate. Could you please confirm that the problem still exists? :)

**Comment by hariprasadms** [comment]
Hi, As there is no follow on this issue, we presume, this issue is not more exists and works fine. We can re-open the issue if the problem persists again. Thanks

**Comment by Shrihari1357** [comment]
It still doesn't work. We have to use android studio to work it properly.
Please make it in flutterflow itself.
