### ISSUE TITLE
Build fails with multi-condition button visibility including a code expression

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#1980]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I combine a code expression with the conditional logic for a radio button being unset it causes the build to fail

### Expected Behavior

Logic should not cause build issue

### Steps to Reproduce

Exact context is created in this test project: https://app.flutterflow.io/project/radio-button-test-irccik

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OhvLl249Oj7xZ0KXqKcEw+CQRNlw1bZZMkuxEbxIYGKnNG4gIZfTBXE9uOP25dkFEeWKJnT8y0NrJm9z1O/ArPSetG9l6+s5bFzmXeDiWMJS2C5aof2pUGshWN2qO5qaZ2yNBALBpSiE43E+MCvKtUjDcJoSwDjBMPM6jIp/XmAfuQ0SLb3kNh1JWeC/v

### Context

I need to disable a button based on a few conditions, and am unable to do so

### Visual documentation

<img width="1421" alt="Screen Shot 2023-12-07 at 10 35 28 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/147427658/819169da-147c-469a-979c-f7feb7b92f2f">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 119.0.6045.199
- Operating system and version affected: macOS Monterey 12.7
```

**Comment by wenkaifan0720** [comment]
@max-h-silverman I can reproduce this issue. Thank you for reporting! 
@katherineqian I think this has to do with the conditional value being not self contained when inside of another (A ? B : C) expression.
