### ISSUE TITLE
Duplicate subscriptions on Android - RevenueCat

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1984]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When on an Android device, changing a RevenueCat subscription doesn't cancel the old one. This works on iOS as it is handled by Apple, but needs to be manually configured for Android devices - see here: https://www.revenuecat.com/docs/managing-subscriptions#upgrade-or-downgrade-a-subscription
This results in users being subscribed to two packages simultaneously where this is really not wanted behaviour.

### Expected Behavior

When a user changes subscription package, it is expected that the old package is cancelled is some way. Google has PRORATION MODES, where Apple uses behaviour similar to "IMMEDIATE_WITH_TIME_PRORATION" so it would be preferred if this was default behaviour on Android too.

The proration modes that RevenueCat uses can be found here: https://github.com/RevenueCat/purchases-flutter/blob/6c31a21985918656aff6bae9590b29d0a0ea9cf6/lib/models/google_product_change.dart#L31-L46

### Steps to Reproduce

Android devices:
1. Create a project and add at least 2 subscriptions offers. 
2. Subscribe to one and then change subscription to the other.
3. Check subscription(s) in Google Play Store and RevenueCat for that user.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fkMmAuI92mOZE7YSJb+9V/CQWMjsnRYJJlu56EBQ1F5fqE5oQfcnRYk5JbbyRSmNceWH8/W01+ejJufP2FcddaRyJboBizrVUczvzcE6uVZC3PLiOempAI/lhG0yszpuZhAlQVLFvci0AwGaXfueXHzLbJrG3DXonL+WhMoTJnlKiLADGG30Jg1ZSfCvr

### Context

When a user changes subscriptions, they shouldn't have to pay for the old, non-active subscription anymore.

### Visual documentation

Here's an image of one of my customers experiencing this issue (image is from RevenueCat console for a customer paying a subscription for a product in production): 
![Screenshot 2023-12-08 at 10 34 39](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/2250c388-6fbe-4908-9bf2-f342d6d27b67)

### Additional Info

/

### Environment

```markdown
- FlutterFlow version: v4.0 (released Dev 6, 2023)
- Platform: macOS Desktop
- Browser name and version: Chrome Version 119.0.6045.199
- Operating system and version affected: macOS Sonoma 14.1
```

**Comment by tinrunje** [comment]
How is this stale... this is a huge issue.
How do we run our businesses if we can't have proper payments in FF?

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This looks to be a duplicate issue. Please refer to [this issue](https://github.com/FlutterFlow/flutterflow-issues/issues/1585) for further updates on this bug. If you believe it is a separate issue, please feel free to follow up in this thread so that we can reopen it. Thank you for your continued patience.
