### ISSUE TITLE
FFappState with RemoveatIndex custom data types not working 

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1985]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It does not update the Ui but makes the changes

### Expected Behavior

To update the ui

### Steps to Reproduce

Create a Custom Data Type

and try to change it with teh custom code below

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+Krcbu4w+T4vI0MBX5Ir1utvGAgYIpTuO5kqfc7EaXddXd+Le2xcO2CIr3IxweuMjezPLvAqJkmCc6F607t6dz3/ZFmuRbarDpaOQ2hQGeJbfEjEyKeFoSNCNrdvSlIg1F+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Future newCustomAction(int index) async {
  FFAppState().update(() {
    //remove at index not working
    FFAppState().removeAtIndexFromStringsss(index);
  });

  print('butclieks');
}

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/3740e575-2bd1-4652-ae3d-1e9934f0a71f

### Additional Info

https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/6419e9ff-9c35-4a60-aad0-bcc5ac321a43

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Josefpa** [comment]
Theres a temporary fix: just add a FF.AppState update after and update a random variable after

**Comment by takashiff** [comment]
Hello @Josefpa, thank you for your bug report. It looks like the code for the custom action you have provided is updating the `Stringsss` List, whereas the children in the column were generated from the `elements` List (in the provided bug report code). If the same list/variable is used, it should be updated properly. Please let me know if you are still facing issues and I will be more than happy to follow up with you. Thank you for your patience.
