### ISSUE TITLE
Initialy Expanded

### ISSUE THREAD

**Issue by ricardocosta43** [FlutterFlow/flutterflow-issues#1986]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

An expandable widget when setting initialy expanded true does not work

I downloaded the code to check, and it really wasn't set to true

### Expected Behavior

An expandable widget starts as expanded

### Steps to Reproduce

1 - Create a blank canvas
2 - Add an expandable widget
3 - mark initialy expanded

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkfHqx89IsbRF+KqNLO1FpDkRM0MbW40VldZ+FBMgGJDtBIh/ePT8XE1pZ9+9TGlhHFCgjkwHwvTMv/LpM8EEYDGtbLp4zagNTQnxXXq8R5CqBYeeRHJCIJpRG2ql0aWjnxF+Pst1S39h202AN+mvXjfaCZ+/Zwh9f6PHaOI=

### Context

I can't launch an expandable widget as expanded

### Visual documentation

![Captura de Tela 2023-12-08 às 05 14 28](https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/e036daad-55dc-4790-9829-787e739652e5)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web, Android and IOS
- Browser name and version: Chrome 116.0.5845.187, Android 13, IOS 17
- Operating system and version affected: macOS Sonoma
```

**Comment by hariprasadms** [comment]
Hi @ricardocosta43 - Thanks for submitting the issue. I have tested the _Expandable Widget_. It is working as expanded in both run and local run mode. see video below for your reference. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/3c1f0029-577e-4db0-b8f8-94e426b63bff

**Comment by hariprasadms** [comment]
Hi, Thanks for additional details. You can see that Initially Expanded option is true at below code lines. This eventually handled by expandable controller. 

<img width="775" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/52d2ee5b-32ae-4c18-b9fd-1183854a19b5">

**Comment by ricardocosta43** [comment]
Yes yes..
If you do it manually it works, but flutterflow is not doing it automatically.
It would be very important if the flutterflow online platform automatically did

<https://1drv.ms/i/s!Ah4MiFABIt2ZijGoEF2LmQZD7nM7>
[https://nw7hzg.dm.files.1drv.com/y4mhBGvPIZfjI6g9nqXfjqBOPywEP2AoZPZVXv9OOGrtG8bRhngJZUrlAyBrVqpeZsNP8_5VNFkAVlvHWnE0BNF3yBb0ynoZf7zEpPEeGf5ocpkGwYIxBic61tDRlXoywE_graVMA3ajxEy7-8NRPYUIOgY8GwWaCqYxCvTbjcdqy8sAJ2oC7yoVPnZiuRFX2L4vY_XVMiks61vXD8h7PWmtg?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Captura de Tela 2023-12-11 às 17.20.22.png
________________________________
De: Hari ***@***.***>
Enviado: segunda-feira, 11 de dezembro de 2023 19:23
Para: FlutterFlow/flutterflow-issues ***@***.***>
Cc: ricardocosta43 ***@***.***>; Mention ***@***.***>
Assunto: Re: [FlutterFlow/flutterflow-issues] Initialy Expanded (Issue #1986)


Hi, Thanks for additional details. You can see that Initially Expanded option is true at below code lines. This eventually handled by expandable controller.

image.png (view on web)<https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/52d2ee5b-32ae-4c18-b9fd-1183854a19b5>

**Comment by hariprasadms** [comment]
@ricardocosta43 - It is working fine while running builds from FlutterFlow and also locally. Can you please add a quick video clip what you are trying to explain. Sorry I'm bit still confused.

**Comment by ricardocosta43** [comment]
Good morning!
follow the video
________________________________
De: Hari ***@***.***>
Enviado: terça-feira, 12 de dezembro de 2023 07:08
Para: FlutterFlow/flutterflow-issues ***@***.***>
Cc: ricardocosta43 ***@***.***>; Mention ***@***.***>
Assunto: Re: [FlutterFlow/flutterflow-issues] Initialy Expanded (Issue #1986)


@ricardocosta43<https://github.com/ricardocosta43> - It is working fine while running builds from FlutterFlow and also locally. Can you please add a quick video clip what you are trying to explain. Sorry I'm bit still confused.

**Comment by hariprasadms** [comment]
Where is the video link ?

I just tested IT again. You can see controller value is set to true when code is downloaded. Not sure where we both exactly missing the point :)

<img width="1512" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8a6e2691-b11e-479c-8e96-45200e9dd5a1">

**Comment by ricardocosta43** [comment]
You dont see my video
https://drive.google.com/file/d/1h6aIHWl8T4xM4c1t-HvHS1T8UQk2oIOC/view?usp=sharing
