### ISSUE TITLE
Command pallete shortcut CTRL + K didn't work when i open tab API Call. 

### ISSUE THREAD

**Issue by reeganaga** [FlutterFlow/flutterflow-issues#1987]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to press keyboard shortcut ctrl + K when i'm on API Call Tab

### Expected Behavior

I home shortcut CTRL + K  can be access anywhere when i open my project

### Steps to Reproduce

go to tab API Calls
press ctrl + K
the command pallete didn't show up

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

actually its not major issue, but it would be better if it fixed,

### Visual documentation

just open the tab API Calls

### Environment

```markdown
- FlutterFlow version: 4
- Platform:android
- Browser name and version: microsoft edge Version 119.0.2151.97 (Official build) (64-bit)
- Operating system and version affected: windows
```

**Comment by hariprasadms** [comment]
Same issue while in settings module.

**Comment by sbis04** [comment]
Hey @reeganaga, we actually don't allow shortcuts on the API Call page and inside Settings: Language tab, could be because of some conflict of the shortcut with other functionality of those pages. So, I won't regard this as a bug.
