### ISSUE TITLE
Backend Query (api to open AI) on column, its calling infinitely, which leads to high bills 

### ISSUE THREAD

**Issue by RohitKanade** [FlutterFlow/flutterflow-issues#1988]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

page view has 3 pages, each page has Backend Query (api to open AI) on column, its calling infinitely, which leads to high bills 

### Expected Behavior

page view has 3 pages, each page has Backend Query (api to open AI) on column, its should call 3 times.  

### Steps to Reproduce

1. create new project 
2. Create new page which has Page View with 3 page view page 
3. add column in each page view (3 column in 3 page view)
4. have get api call on each column backend query.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Its shows failed to copy

### Context

page view has 3 pages, each page has Backend Query (api to open AI) on column

### Visual documentation

![Screenshot 2023-12-09 at 12 19 16 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/d86ae7ac-d614-4e5c-894c-f8a1cd80deec)

### Environment

```markdown
- FlutterFlow version:  v4.0 released December 6, 2023
- Platform:- Platform:web
- Browser name and version: chrome 115.0.5790.171
- Operating system and version affected: MAC OS  

Project: LinkBuddy
Project ID: link-buddy-dzh1rs
FlutterFlow v4.0 released December 6, 2023
Flutter version is 3.13.7
```

**Comment by RohitKanade** [comment]
Page level caching do the tricks, but seems weird/not natural behaviour, which costs me.

**Comment by hariprasadms** [comment]
Thanks for confirming. I hope issue has been resolved for you now.

**Comment by RohitKanade** [comment]
@hariprasadms it should not be closed. issue is there I made trick to work it, bu you may need to check this issue

**Comment by mrnicon** [comment]
Please make sure to check the same issue in dropdowns. As  and a API call on the event of On Select make two calls. One using the new selected value, the next one sends the previous value. If you use the API call to set the selected value you will get the old one all the time....

**Comment by mrnicon** [comment]
What I have found in a web app is the Referer in the request to the server is using the page I am coming from in the first request and the next request is using Referer as the page I'm inside. - this is on page load. Making the API call from a Action on load or on a ListView dose not mater, it the same behavior.

**Comment by RohitKanade** [comment]
@leighajarett  I think issue still there

**Comment by RohitKanade** [comment]
@agreaves @hariprasadms issue is still there and other bug related it also closed -- https://github.com/FlutterFlow/flutterflow-issues/issues/2150
