### ISSUE TITLE
Data of the Authenticated User is not loading when is starting the app on Web

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#199]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Load the data of the Authenticated User

## Current behavior (required)

On Web the data of the Authenticated User is not loading

## To Reproduce (required)

1. Open the Main Page of the app
2. Select a widget and click on "Set from variable"
3. Choose a Photo URL or Display Name from "Authenticated User" Source
4. Now open the app on web page and the values from the widget is not showing

### Bug Report Code

I can't generate the Bug Report Code, always appears this message
"Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)"

## Context (required)

When the user opens the app, I want to show the user's info

## Screenshots / recordings

https://user-images.githubusercontent.com/36147203/206105844-23360dbd-6edd-4f6d-a819-9e6cf99a471c.mp4

## Your environment

* Version of FlutterFlow used: November 18, 2022 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Android, Desktop Web and Mobile Web
* Browser name and version: 107.0.5304.141
* Operating system and version (desktop or mobile): Android 12

**Comment by Franco98404** [comment]
Only happens when you open the app and load the first page. When you go to another page it is working properly.

**Comment by bulgariamitko** [comment]
Is it possible because you don't have access to the Authenticated User at the first screen?

**Comment by agreaves** [comment]
Hi @Franco98404, please try creating the Bug Report Code again (it should work this time). I haven't been able to reproduce this in another project as of yet. Also, if you please provide me a test account to use (so that I can log into the app and diagnose the issue), that would be very helpful. Thanks!

**Comment by Franco98404** [comment]
Bug Report Code:
IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpOFDIbGJzwBIh/Yc/eS1pCcNyrTWlhHGGjnkkDps7Xv9/tUfcnIQmtQYty1Yd2YDr/RTbkEuzyT+3IHDUHZbsSXTTm

About the test account, if you want can you send me your email, and will add you to our project.

**Comment by bulgariamitko** [comment]
@Franco98404 , the project is visible to the FF team. They just need a test user in order to login into your app.

**Comment by Franco98404** [comment]
> @Franco98404 , the project is visible to the FF team. They just need a test user in order to login into your app. 

Thanks for clarifying, these are a credentials for a testing account
Email: testing@schoolfy365.com
Password: 123456

**Comment by Franco98404** [comment]
Now it is working properly with the last update. Thanks!

**Comment by agreaves** [comment]
Awesome!! No problem.

**Comment by Franco98404** [comment]
Unfortunately, it is working better, but it is not resolved. The first time when open the web page had the same problem but the subsequent times it is working properly

**Comment by bulgariamitko** [comment]
I will remove the closed fixed status then

**Comment by Franco98404** [comment]
Ok, thanks!
