### ISSUE TITLE
No Popup after downloading code

### ISSUE THREAD

**Issue by wizehawk** [FlutterFlow/flutterflow-issues#1990]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was told to report the bug that I am not getting a popup after downloading my code. I have made sure Flutterflow is not blocked by popup blockers.

### Expected Behavior

To get a popup when downloading the code explaining the commands that need to be run.

### Steps to Reproduce

download code from developers menu.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvLq25Ngrt9f7q6JcMFF9ToUCDt9bJIni+thYCs8GZT0B4kcYs+kfklUOMilTVZle2KGnmYX/MmLvfP1CccrFySYQJg41bVQdRfhfHmlVpSNBq63b2hQDe9WN0yz04mvkyJCJtFeWiUO602mJuqXXgjYK5zYITINQ+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to open and sign my app to deploy to the Google Play Store

### Visual documentation

none

### Environment

```markdown
- FlutterFlow version: 4
- Platform: Windows
- Browser name and version: Chrome version 120.0.6099.71
- Operating system and version affected: Windows 10
```

**Comment by victoriahuang1** [comment]
@wizehawk can you check, with your dev tools open, if there are any errors when you try downloading? I tried downloading your project and it worked for me. This is likely a browser issue.

Also is the issue just that there isn't a popup? Or that the code isn't downloading either?

**Comment by wizehawk** [comment]
Hello, it was just the popup window that didn't appear. Thank youChrisOn Jan. 23, 2024 4:16 p.m., Victoria Huang ***@***.***> wrote:
@wizehawk can you check, with your dev tools open, if there are any errors when you try downloading? I tried downloading your project and it worked for me. This is likely a browser issue.
Also is the issue just that there isn't a popup? Or that the code isn't downloading either?

**Comment by victoriahuang1** [comment]
@wizehawk are you able to provide a screen recording? Also, does this work on incognito?
