### ISSUE TITLE
While Build APK

### ISSUE THREAD

**Issue by XmediawebDeveloper** [FlutterFlow/flutterflow-issues#1994]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When Build apk throw this error for very long time i am using Google Api and other map work

### Expected Behavior

I want to build apk

### Steps to Reproduce

project fails to build apk

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Get Bug Report Code

### Context

I don't know

### Visual documentation

Error: Command failed: flutter build apk --no-pub --no-version-check
Note: /opt/.pub-cache/hosted/pub.dev/geocoding_android-2.1.2/android/src/main/java/com/baseflow/geocoding/Geocoding.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/geolocator_android-4.2.4/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /opt/.gradle/caches/transforms-3/8e58de5c6c1768f420c6e5590593173a/transformed/jetified-kotlin-stdlib-common-1.9.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (48, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (75, 15): Unresolved reference: apply
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (76, 17): Unresolved reference: lockscreenVisibility
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (78, 33): Overload resolution ambiguity: 
public open fun createNotificationChannel(p0: NotificationChannel): Unit defined in androidx.core.app.NotificationManagerCompat
public open fun createNotificationChannel(p0: NotificationChannelCompat): Unit defined in androidx.core.app.NotificationManagerCompat
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (86, 54): Unresolved reference: let
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (87, 17): Unresolved reference: it
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (87, 26): Unresolved reference: it
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (89, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (91, 14): Overload resolution ambiguity: 
public open fun setSmallIcon(p0: IconCompat): NotificationCompat.Builder defined in androidx.core.app.NotificationCompat.Builder
public open fun setSmallIcon(p0: Int): NotificationCompat.Builder defined in androidx.core.app.NotificationCompat.Builder
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (95, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (101, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (109, 33): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (115, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (118, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (120, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (124, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (169, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (172, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (173, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (193, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (194, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (196, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (201, 23): Unresolved reference: let
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (203, 21): Unresolved reference: it
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (214, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (215, 23): Unresolved reference: let
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (216, 32): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (217, 21): Unresolved reference: it
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (227, 23): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (229, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (242, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (244, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (250, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (251, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (253, 14): Class 'kotlin.Suppress' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Suppress.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (254, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (257, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (261, 33): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (264, 13): Unresolved reference: mapOf
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (264, 31): Unresolved reference: to
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (264, 63): Unresolved reference: to
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (271, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (272, 19): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (279, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (281, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (282, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (283, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (285, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (286, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (292, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (294, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /opt/.gradle/caches/transforms-3/2e5c2bfe33b21d2bc1f6177f33a38e1a/transformed/jetified-kotlin-stdlib-1.9.0.jar!/kotlin/Unit.class
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (302, 23): Unresolved reference: let
e: /opt/.pub-cache/hosted/pub.dev/location-5.0.3/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (303, 69): Unresolved reference: it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 10s
Gradle task assembleRelease failed with exit code 1

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: Chrome 
- Operating system and version affected: windows
```

**Comment by hariprasadms** [comment]
Hi @XmediawebDeveloper - What is the bug report code please? Update actual environment details where you are seeing this errors.

**Comment by sarim** [comment]
Same issue happened to me after adding  `flutter_nfc_kit` via a custom  action. Here is the full terminal log. 
[error.log](https://github.com/FlutterFlow/flutterflow-issues/files/13668449/error.log)

I edited build.gradle and set 
```kt
    ext.kotlin_version = '1.9.0'
```

While this would allow me to build locally, What about flutterflow build and deploy?

**Comment by hariprasadms** [comment]
Is this still the same even after latest updates ?

**Comment by hariprasadms** [comment]
I assume your issue has been resolved now. Thanks
