### ISSUE TITLE
Issue with Row Widget's Main Axis Alignment and Start Spacing

### ISSUE THREAD

**Issue by wookim789** [FlutterFlow/flutterflow-issues#1996]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i configuring the main axis alignment option of a Row widget with Space Between and setting start spacing 1.

my widget tree like this.

row
- text
- text

### Expected Behavior

i expect like that

row
[1px] - text ------------------ text

but result

[ton of spacing]------------text ----------------text
![스크린샷 2023-12-12 오전 10 18 36](https://github.com/FlutterFlow/flutterflow-issues/assets/38445103/48e41604-1bb4-4315-9285-a8773473f12a)

if i put 0 in start spacing result is equal.

### Steps to Reproduce

1. create row
2. put 2 text
3. set row main axis alignment spacing between.
4. set row start spacing 0, 1, 2 ...
5. result is unexpected.
6. new empty project same occur.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocNd+pDAcexQhR0gHDN8Uecam9VDexAaGO/3GbYUePekdhFvTeGleEFAfWKIpzgFpsLVvdnEG8IGPh6BbIhFzJF+bzmUZHqVMKaqPs6KS3F8GphRJh2D4KSrsSZ4Ou52eClpig/GSw==

### Context

a list view that some image and text and buttons. and i want to space between that emlement. and i want to start spacing the first element. 

### Visual documentation

i upload image above.

### Additional Info

i upload image above.

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform:mac os application.
- Browser name and version:chrome 120.0.6099.71(공식 빌드) (arm64)
- Operating system and version affected: mac sonoma 14.0
```

**Comment by hariprasadms** [comment]
Hi @wookim789 - Thanks for submitting the issues. The behaviour what you are seeing is as per design and also its a default behaviour of row or column widgets while using _.addToStart_ method to add item space. The design you are expecting can achieve using padding instead item spacings. 

This is not a bug. Thanks

**Comment by wookim789** [comment]
ok thanks. i solve this problem like your solution. but i still think the spacing option is weird.
