### ISSUE TITLE
When using toJSON in a datetype that contains a DateTime, the datetime is not serialized

### ISSUE THREAD

**Issue by ssaguadoinversiva** [FlutterFlow/flutterflow-issues#1997]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an API call that sends a JSON serialized and I use a custom DataType that contains two datetime fields. When it enters

String _serializeJson(dynamic jsonVar, [bool isList = false]) {
  jsonVar ??= (isList ? [] : {});
  try {
    return json.encode(jsonVar);
  } catch (_) {
    return isList ? '[]' : '{}';
  }
}

the datetime fields are converted to null

### Expected Behavior

I expect to be converted to a ISO string

### Steps to Reproduce

Explained in the current behavior

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48j8nc05NPmMNA0JD9bfpVniQUJj47apEZjextawk8J5zTP4YIP/v7ak5oO7yoSn9fM06Kgn0e/PfqjeDpA/crFAWabLZxybVqEQmXIWSXM7qwDKiJfW1fL+BWClya4KuwkxF4AO9tS1YQ2nGAOtmsZD3XGJDUNjJEJuaLLdeK2SrDX1iXc2URm05KZDPz

### Context

Using an API call that receives a DateTime

### Visual documentation

Not needed

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mac
- Browser name and version: Google Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hi @ssaguadoinversiva - Thanks for submitting the issue. I looked at your project but there is lot going on there. Could not find the issue page and configurations. Please setup a blank project with issue steps setup and share project bug report code. Once we got these details. We can investigate the issue. Thanks

**Comment by hariprasadms** [comment]
Hi @ssaguadoinversiva - Any updates about required details?

**Comment by hariprasadms** [comment]
Hi, There is no enough details to investigate the issue. I presume you have found a solution for the issue. Hence I am closing the issue. If issue still persist, you can reach us with required details for further investigation. Hence I am closing the issue. Thanks

**Comment by ridehike** [comment]
@hariprasadms @katherineqian 

I have encountered this issue as well, or at least a similar issue related to attempting to use the `toMap` function of converting a data type into a JSON object.

When I attempt to serialize a data type with a DateTime that is set with a datetime, the serializer generates a incorrectly formatted JSON string.  I can provide details if needed.
