### ISSUE TITLE
Radio button initial value is blank

### ISSUE THREAD

**Issue by katherineqian** [FlutterFlow/flutterflow-issues#2]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.
Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

## Expected behavior

When a user sets an initial value for a radio button widget from a variable, the initial value should be correctly set. 

## Current behavior

When the initial value for radio buttons is set from Firestore collection data, the radio button widget appears empty and unchecked. 

## To Reproduce

1. Create a new RadioButton widget.
2. Create two options, "Option 1" and "Option 2". 
3. Create a Firestore collection "testColl" containing a document with field name "test" and value "Option 2". 
4. Add a Single Document query on testColl, turning off "Hide Widget If No Match". 
5. Set the Initial Option for the RadioButton widget from variable, and select testColl Document > test. 
6. Click "Run". 
7. Observe that the Radio Button widget is blank, even though Option 2 should be selected.

## Context

If the user has already selected a value for the radio button, when the user's document is loaded, the radio button widget still appears blank. 

For example, let's say we have a user profile page with "Developer" and "Designer" radio buttons to indicate the user's role. If the user selects "Developer" and saves their profile, the next time they open the profile page, the radio buttons still appear unselected, even though "Developer" should be selected already as the initial value.

This issue severely affects use cases where end users need to edit RadioButton values after submission.

## Screenshots

N/A

## Your environment

* Version of FlutterFlow used: N/A
* Platform (e.g. Web, MacOS Desktop): N/A
* Browser name and version: N/A
* Operating system and version (desktop or mobile): N/A

**Comment by yellowsnowagency** [comment]
Is someone working on this? It would be great to have this functioning without a workaround.

Thanks

here our example of the issue:

code is missing the initialValue parameter

child:
FlutterFlowRadioButton(
options: [
'TV & Digital Programs',
'Entertainment',
'Advertisement',
'Corporate Content'
].toList(),
onChanged: (val) =>
setState(() =>
categoryValue =
val),
optionHeight: 25,
textStyle:
FlutterFlowTheme.of(
context)
.bodyText2,
selectedTextStyle:
FlutterFlowTheme.of(
context)
.bodyText1,
buttonPosition:
RadioButtonPosition
.left,
direction:
Axis.vertical,
radioButtonColor:
FlutterFlowTheme.of(
context)
.primaryText,
toggleable: false,
horizontalAlignment:
WrapAlignment
.start,
verticalAlignment:
WrapCrossAlignment
.start,
),

**Comment by yellowsnowagency** [comment]
btw it's always not only on firestore - thats why we generated a new issue

**Comment by cheggy** [comment]
This ticket has been raised in the community forums since July 2021.  There are so many posts about it.  It seems like a fairly simple thing to fix, compared to everything else.  Would be great to know when it will be resolved.

**Comment by cheggy** [comment]
How long is this feature going to be broken for?  It's been broken since August 2021.  Not exaggerating.

**Comment by yellowsnowagency** [comment]
Can please someone fix that radio button default vale bug??? We stopped developing and hoped it would be fixed - truly CAN'T understand why @katherineqian set this issue on low priority there is now multiple complaints on the forums and everyone who seems to have a clue about coding says its an easy thing to fix but stops a lot of apps to be developed at the moment if you read your forum... PLEASE PLEASE FIX THIS !!!! PLEASE!!!

**Comment by hariprasadms** [comment]
Hi @katherineqian - Looks like this issue still exists. Even after model interduced at page level, this issue is not working. Could you please have a look.

![image](https://user-images.githubusercontent.com/17435678/218513699-c416da81-be5f-4a2e-8cc0-fa775e03ec20.png)

**Comment by hariprasadms** [comment]
It is working fine now in latest update. Keep FF editor up to date.
