### ISSUE TITLE
When having a DataType inside a Custom Function and try to Test it, it returns an error.

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#20]
## Expected behavior (required)
Get 'FF is great' when press on 'Run' in Test in Custom Funtion

## Current behavior (required)
Get '1' and the error 'Error running the function, please connect support support@flutterflow.io' is great' when press on 'Run' in Test in Custom Funtion

## To Reproduce (required)
1. Create a simple DataType variable
2. Create a simple Custom Function and in Function Definition in Function Arguments write the name 'dt' and Data Type select DataType, Type select (in my case) Product, Is List - false, Nullable - True; enter the return type as String to the Function.
3. Click Code and enter ---  return 'FF is great';
4. Click Test and then Run

## Context (required)
I can't test my Custom Function when there is a Data Type in them

## Your environment

* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 106
* Operating system and version (desktop or mobile): desktop

**Comment by agreaves** [comment]
This old bug should now be fixed as of a while back!

**Comment by bulgariamitko** [comment]
No I still got the same error. This is the code I am using

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

String? dt(CarStruct? dtp) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return 'FF is great';

  /// MODIFY CODE ONLY ABOVE THIS LINE
}


and this is the error I am getting
'Error running the function, please connect support [support@flutterflow.io](mailto:support@flutterflow.io)'

I think this should be re-open as it is not fixed.

**Comment by agreaves** [comment]
Closing as not planned for now.

**Comment by bulgariamitko** [comment]
@agreaves isn't it better to add a new status like we talked about it. Like planned for future or something like that?
