### ISSUE TITLE
Windows desktop fails to build with "enable Developer Mode" error

### ISSUE THREAD

**Issue by tobyjo** [FlutterFlow/flutterflow-issues#2000]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Even though I can build native Flutter Apps and compile and deploy as a window desktop app without error, the code I download from flutterflow fails to run with this error:
`Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.`

Dev mode is enabled, and all requirements met - as proved by the fact that I can deploy a native flutter code.
I also enabled Windows platform in flutterflow project.

### Expected Behavior

WIndows app built

### Steps to Reproduce

Build basic flutter flow app
Enable Windows platform in settings of flutterflow project
Download code
Get latest packages
Run
`flutter build windows`
Fails with message:
`Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.`

If I run
`flutter run -d windows`
Terminal window pops up and disappears immediately.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlsn1z4pNjMhE7pDuYcZao2IwGUwbUOc7j9VEGAsjCePvP6QAefT7flBpSOqHf1dAGFe0iXIFpc7riuPxUe4DBAeWUbpM1bpTUxDiUj+5MaqQDaqrPXRDP8BYf1SF5pmNmBYlXLd1LF4W70+DfuiAb3qCf9qOYwx5e6fDbOY=

### Context

Cannot build windows desktop app

### Visual documentation

![flutterflowbug](https://github.com/FlutterFlow/flutterflow-issues/assets/25321698/aafa09a9-fb73-4b32-b440-fe7bfb26d0f6)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:Windows
- Browser name and version:Chrome v120
- Operating system and version affected: Win11
```

**Comment by sbis04** [comment]
Hi @tobyjo, I have tested the FlutterFlow project on a Windows system and it builds and runs perfectly. Make sure you have configured Flutter properly on the system you are trying to run. Also, make sure the Windows platform is enabled in Flutter, you can enable using `flutter config --enable-windows-desktop`. If you still face any issues, please reach out to our support.
