### ISSUE TITLE
Youtube player Issue

### ISSUE THREAD

**Issue by rahil320** [FlutterFlow/flutterflow-issues#2001]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

YouTube player enters to Fullscreen mode automatically upon taping when used inside ListView even if portrait mode is disabled on Android cell phone. If I disable "Show Full Screen Control" from YouTube player settings in Flutterflow then the full screen issue gets resolved but it introduces another problem where the Listview does not scroll up/down when finger is placed on YouTube player. It only scroll when we place the finger between the gap of Listview items (youtube player)

### Expected Behavior

YouTube player should not get into fullscreen mode on single tap and also be able to scroll inside Listview when "Full screen mode" is disabled from flutterflow.

### Steps to Reproduce

1. Create a new project and page
2. Insert "Listview" in widget tree
3. Insert multiple YouTube players inside Listview
4. Try to run the project on Android/IOS device and it enters full screen the moment user taps on the player.
5. If "Full screen mode" is disabled from Youtube player settings in flutterflow, then the player does not get into full screen but it introduces another problem that the Listview does not get scrolled when finger is placed on Youtube player

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ysmB389Iocdc17rAccZVmik5KUs2U4Iale1RaC8uGOOvOpYQZvfARFFVUum+TVc3I2eKhngx/tXHvczIN8c6HxSdfrY/1qoBcRfwbFOnM72VPcyKT3NBMNpKBVSH1ru7oQolOuhZc041w2GIft6QYzDcQrrwNUcCD86YBJv4jX/uQ0SLb3kNh1JWeC/v

### Context

I am trying to display Youtube channel videos in a ListView and unable to accomplish this since the player enters full screen automatically or the Listview doesn't work (scroll)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/57478029/85103618-c9d0-42c5-aac8-f3172cdec4aa)

### Additional Info

The problem only occurs if Youtube player is inside a ListView in widget tree. If I place a standalone Youtube player , then the problem does not occur

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Android
- Browser name and version: Microsoft Edge
- Operating system and version affected: Android 14
```

**Comment by wenkaifan0720** [comment]
Hi @rahil320. This should be fixed in our next update. Thanks!
