### ISSUE TITLE
Custom function fails to test : Supabase Error message after clicking run button

### ISSUE THREAD

**Issue by MamadAsap** [FlutterFlow/flutterflow-issues#2002]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i try to use the " Test Function" feature for  my custom function i have an error message 
![Compilation Error](https://github.com/FlutterFlow/flutterflow-issues/assets/116876408/fd15b80e-c535-451b-8772-5a141ada53e4)

### Expected Behavior

I should have the result of my test

### Steps to Reproduce

Create a custom function
Test it in "Test function" tab

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8iAz4hgoctH176Jc/pV+TsUJlgnbZZMju5xaEo0G5fNGogUY8jeVERpZNzmY29UJWaJgWoW0N7GuPPxLcJdZAScGLpG1rhUdwLdWkCieJCuFJWgQkBBO5hWJm6y58PUuBFQC/V2R1If2juQAOetaHHtK5D1PVUkDq/LZO4=

### Context

I can no longer test my custom functions

### Visual documentation

![Compilation Error](https://github.com/FlutterFlow/flutterflow-issues/assets/116876408/b9073071-751f-4a9b-a57e-d1ced881c209)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Arc Version 1.20.1 (43987)
- Operating system and version affected: Sonoma 14.1.2 (23B92)
```

**Comment by rahil320** [comment]
Experiencing the same issue as mentioned. Custom function cannot be tested and gives this Supabase error.

**Comment by katherineqian** [comment]
Can you please try this again? We had a new release today that should have fixed this error.

**Comment by rahil320** [comment]
> Can you please try this again? We had a new release today that should have fixed this error.

Checked and tested. It is working perfectly fine after the new release.

**Comment by katherineqian** [comment]
Thanks for confirming, glad to hear the fix worked! I'll close this issue now.
