### ISSUE TITLE
Reset Form Fields Action Does Not Target Selected Components

### ISSUE THREAD

**Issue by robertoprd** [FlutterFlow/flutterflow-issues#2003]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the "Reset Form Fields" action in FlutterFlow on a page containing multiple instances of a component ("tfComponent") that includes a TextField, the generated code only resets the fields of the first instance, ignoring the selection made during the "On Tap" action configuration.

### Expected Behavior

The "Reset Form Fields" action should reset the fields of the selected instances of "tfComponent" rather than just the first one.

### Steps to Reproduce

1. Create a component that contains only a Container and in it a TextField. We'll call it "tfComponent".
2. In the HomePage, add two or more instances of "tfComponent" and a Button.
3. Define an "On Tap" action for the button. The action should be "Reset Form Fields."
4. FlutterFlow will present the list of all "tfComponent"s to select those to reset. No matter what you select, the generated code will reset only the fields of the first one.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvHqx5NItbxd1s7ybe9VhmEvCDt/bZ0NmMJ9dCs8GZT0B4kcYs+kfklUONOkd2xDPmCjrHIX/Mr6jeHPLvUVAySZbt1gwaoNZw7MZGa6aJjSC4S3b0dDM+RhIByByMCw2yJQXLJ0W3wQ1zm6GOiAQh3qJKLyPGokDuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to reset all the form fields that I have in multiple instances of a component

### Visual documentation

![i1](https://github.com/FlutterFlow/flutterflow-issues/assets/141933394/e45fc61d-2ec4-493e-9d8c-f1f0e3b02f1b)
![i2](https://github.com/FlutterFlow/flutterflow-issues/assets/141933394/84b50cde-1746-4da9-82e4-98be70e282af)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.71
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi, I can re produce the issue. Thanks

**Comment by ignalauret** [comment]
Hey @robertoprd thanks for your report. This bug is already fixed on the newest version of FlutterFlow, I'm sorry you weren't notified. I'm closing this issue because it was resolved, have a great day!
