### ISSUE TITLE
Wrong Icon used for "Share"

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#2004]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Set Icon "Share" to IconWidget.
But, wrong icon displayed that is different with "Choose Icon" Dialog.

### Expected Behavior

Correct Icon selected.

### Steps to Reproduce

1. Make Container
2. Put IconWidget
3. Click Icon property
4. Select "share" icon on "Choose Icon" dialog
5. Wrong Icon choosed
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/5987720b-f9c2-4cbd-b1a3-96ff26dafaa8)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8jq3ItOm8sC1a6Jd+1Wnj4sH2UcTYARiO0bFB4dIrmrPLQie8zSYUNKT+GjdG1MGVCGkTg1wPDHkofxLsJeBEmbGaJl0JVAZxWXUTqRbraXC7uSWX97GcBhGX661KS33BJANuNZL2wQ206bNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Not affected now, I use "share outlined" instead.

### Visual documentation

As in reproduce section

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 119.0.6045.159 
- Operating system and version affected: iOS
```

**Comment by wenkaifan0720** [comment]
Hi @ryutosh. This is more of a display issue on the frontend (which will be fixed in our next update). But the generated code should still be correct.
