### ISSUE TITLE
Using pushNamed, serializeParam and ParamType in custom actions gives error 

### ISSUE THREAD

**Issue by furkanorka** [FlutterFlow/flutterflow-issues#2006]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Actually can compile code (its functioning code) but for some reason FlutterFlow decides to throw an error. 

### Expected Behavior

To not throw an error and passing the code check. 

### Steps to Reproduce

1. Create new custom action
2. Create a context.PushName function and pass in query parameters using serializeParam and ParamType. No error in code but when compiling errors will show up

(taken from https://github.com/FlutterFlow/flutterflow-issues/issues/1452 thanks @AlexandreHurbe)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oicjf/ZdPxOFJ1c/uKcJV/CQXJm4/a7hElcpBZywgfZzzBLN/fPfQPxZpZPW7d29IOFm2p14D0+zxi9+SUcI6Gzecc65SyqgBSRbhVT+RRLmTF7uSOUZ9HfNnC2qc5sGFhhVvBO92L3w+1GCIPdyyZAPvO72yPmo4Sq/LZO4=

### Context

It affects my sanity. I don't want to see a warning or error bug at top right while everything should be OK because the code itself is functioning but FlutterFlow instead wants to throw an error for some unknown reason. This is the same as (https://github.com/FlutterFlow/flutterflow-issues/issues/1452) when I contacted support about it they said to me to re-create the issue instead of re-opening (which only the creator of issue or someone from the FlutterFlow organization can do) 

The error can be ignored by enabling **Exclude from compilation** but then we will get a permanent warning (which we cant just say ignore this warning and don't highlight it) and have to live with it forever? 

### Visual documentation

![Ekran görüntüsü 2023-12-14 105451](https://github.com/FlutterFlow/flutterflow-issues/assets/153807639/6f4e6ada-2f71-4dfd-b928-50af88dbb0fb)
![Ekran görüntüsü 2023-12-14 110230](https://github.com/FlutterFlow/flutterflow-issues/assets/153807639/a17c247e-6a62-4ea3-b0f2-b66b16407055)

### Additional Info

Please fix it or let us ignore warning somehow so we don't have to live with it. 

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.71 
- Operating system and version affected: Windows 11 22H2
```

**Comment by aemelyanovff** [comment]
Fixed in the next update.
