### ISSUE TITLE
Project crash on test or on download code

### ISSUE THREAD

**Issue by htsnet** [FlutterFlow/flutterflow-issues#2008]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project crash when I try to run a test or when I try to download the code.

### Expected Behavior

Not crash...

### Steps to Reproduce

1. Open the project "Colecionador" --> Project ID: colecionador-k7ckat
.
2. Try to run a test or try to download the project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olcmA8ZN1xOFG1pD+csExhSQUC24laOc70spBZzUYF5SuCLMqY8mnP1htXeLmdFVpeWGcp14H0tKOvoSWDvE6BwSWGqI9yJZ+FAmXeGCuRbGTF7u8TkZRGcNVCBG657TYgwp/KrNZWmwk606uDOqiTi/dCb7oOEQ8Sq/LZO4=

### Context

I can´t test my "ColecaoEdicaoPage". It is a simple page with an action on load and a listview that uses one AppState field.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/9755885/ab8b8293-86d9-470f-9b91-14d50df7a8ce)

### Additional Info

I left the project as it was and copied it to another one (Colecionador 2). In the new one, I removed the page and created it again, in the same way. On the new project, it is working. I think that is a "dirty" code in my original project. I left it intact to try to understand the issue. Maybe it is a bug. 

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Windows
- Browser name and version: Chrome Versão 120.0.6099.72 (Versão oficial) 64 bits
- Operating system and version affected:
```

**Comment by sbis04** [comment]
Hey @htsnet, are you still facing this issue? It seems to me the project is building fine now.

**Comment by hariprasadms** [comment]
Hi @htsnet - I have verified that the project code can successfully download and execute test runs without any issues. Hence, I am closing the issue. Thank you.

**Comment by htsnet** [comment]
@hariprasadms Yes! I opened now the project, without any change, and it runs. Maybe the new FF version solved the issue. Thanks.
