### ISSUE TITLE
Can't create Firebase records with DataType with Color field

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#201]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
create Firebase records with DataType with Color field

## Current behavior (required)
Can't create Firebase records with DataType with Color field

## To Reproduce (required)
1. Create new project
2. Create any database 
3. Create any DataType with text field and color field
4. Create field in database (use the new Datatype)
5. Open Manage content and try to create new records with DataType with color field

## Context (required)
I can't manage my app(((

## Screenshots / recordings
Link to the video:
https://drive.google.com/file/d/1FoaU87gDzNPWmpZ6uqdVan97OCquCm93/view?usp=sharing

## Your environment

* Version of FlutterFlow used: 1.1.20
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Safari
* Operating system and version (desktop or mobile): MacOS

**Comment by Pepino-GR** [comment]
Hi oper2k,

I can reproduce it. The problem occurred, if you use the data type Color inside a Data Type
