### ISSUE TITLE
Test Mode Not showing texts

### ISSUE THREAD

**Issue by renanbirlem** [FlutterFlow/flutterflow-issues#2010]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running projects in Test Mode (emulator), some texts contained in the layout do not appear.

### Expected Behavior

The expectation is that the testing mode works correctly, showing all elements contained in the layout

### Steps to Reproduce

1. Create some layout
2. Execute Test Mode to validate

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wk+fl4c51n7xH1rr+Kflv9SkXIjskbbsn0NUaeCs8GZT0B4kcYs+kfklUOc/jYwhhMGKZuDoX/Mr9keHLVu0pFzKYY65PzLlcWjrgbGWVaL7WEb63b3dPP8JQJlyk4aW3ghF4Iu9scng+1DmEHt+9QnHBJqLsClY3JeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

We have "Times" mode enabled. This problem does not occur with me (user owner), but it does occur with other team members.

We have already tested it on Mac, Windows and Linux.
We have already tested it on two browsers: Chrome (main) and Safari.
I currently use Mac, Intel processor (works).

We have already tested the hypothesis that they are translations. We enable, disable, add all translations. This is currently disabled.

The screen I gave as an example is the Login screen, but it happens on all others. Even on certain screens some texts still appear, but not all.

### Visual documentation

![CURRENT](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/67361eb6-c394-4622-abbe-6f6e4d79524b)
![EXPECTED](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/0d7c20e8-02c6-4eaa-8b88-9c09463db4ed)

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): macOS Monterey 12.2.1
```

**Comment by renanbirlem** [comment]
Complement: We have been trying to resolve this problem for two weeks.

**Comment by Emvipy** [comment]
> **Other important update: We copied all screens to other blank project and will continue developing in this new project, because here we the Test Mode runs correctly. We will keep the "problematic" project for troubleshooting questions.**

Do you have more than one language ? I had the same problem a few days ago and in my case was that I had 2 languages but only one full completed...

**Comment by renanbirlem** [comment]
> > **Other important update: We copied all screens to other blank project and will continue developing in this new project, because here we the Test Mode runs correctly. We will keep the "problematic" project for troubleshooting questions.**
> 
> Do you have more than one language ? I had the same problem a few days ago and in my case was that I had 2 languages but only one full completed...

Hello! We tested with one or more languages enabled, but the problem persists.

**Comment by hariprasadms** [comment]
Hi @renanbirlem - Thanks for submitting the issue. I looked at your project I see translation is missing for the given languages. When you change primary language you see below message. Make sure you have re generated translations for all the language. 

Please confirm.

<img width="997" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b6014fa5-ece4-4525-a6c8-1569642f4de3">

**Comment by hariprasadms** [comment]
> **Other important update: We copied all screens to other blank project and will continue developing in this new project, because here we the Test Mode runs correctly. We will keep the "problematic" project for troubleshooting questions.**

Compare this working project configurations with the project where you see the issue. I hope you have already done it.

**Comment by renanbirlem** [comment]
> Hi @renanbirlem - Thanks for submitting the issue. I looked at your project I see translation is missing for the given languages. When you change primary language you see below message. Make sure you have re generated translations for all the language.
> 
> Please confirm.
> 
> <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/17435678/290825680-b6014fa5-ece4-4525-a6c8-1569642f4de3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTgxNTgsIm5iZiI6MTcwMjY1Nzg1OCwicGF0aCI6Ii8xNzQzNTY3OC8yOTA4MjU2ODAtYjYwMTRmYTUtZWNlNC00NTI1LWE2YzgtMTU2OTY0MmY0ZGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MzA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTFhODk0NzllY2FkOTI4ZTk4NjdhZGE5NGUxMTBmMmMxMjI0OTQ5MjhiOTFlZmNhOWIxYTI3ZjhkYTBkZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vX2ekL_AUT2A-r6JMNmD5VbwyWNk03QNXi9Z8GIJ90g">

Helo @hariprasadms , thanks for the reply.
We added this configurations (2nd language), just for test. At this moments I returned the primary config, setting PT-BR language.

Our language config are like this:
![Captura de Tela 2023-12-15 às 13 37 59](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/5012bb54-aef4-4a04-bc78-80c19297308e)

**One importante detail:** as we mentioned, we created a new project and start to migrate screens. This new project started running corretly (Test Mode), without text problems yesterday. By the way, in this new project we only changed the Firebase config and nothing more. (No language configs, for example). And today, when we started the Test Mode, the problem are also ocurring in this new project. Anyway, we revised the language configurations and set PT-BR by default.

About compare the projects configs, as I mentioned, in this new project (now with the same problem too), we changed ONLY Firebase config (and now language to Portuguese). In short, this new project it's exactly the same as the print above about language settings.

**Comment by renanbirlem** [comment]
@hariprasadmssome more evidence for you, **now on the new project that "stopped working":**
Bug Report Code in this new project: IT5fk8nf7Y9Om9tc15DUbPl7/T8RJkM7apIFiutuew4aIurqPKQIYcnSRE5JYsOGdwlIJFmj8XgK0qHNheDxFvoBCwuBaYNeyqV+aDyWWTmgbpObBs+8TnJDL+Bhf36wy7SOmA9QHMRfSVID1DqEIuStShHAHu63DFQdLf6IB5PApHDiHSTCGRFFwmNecCfn

1. What the login screen looks like:
![Captura de Tela 2023-12-15 às 14 03 04](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/2637948b-68e2-4565-90ff-59bae6af76b1)

1.1. As it is in Test Mode (it is perfectly correct, with all the texts).
![Captura de Tela 2023-12-15 às 14 03 30](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/118ce42b-1869-4a7e-8631-93f3ba1b1818)

2. Now the initial screen (after login), as it is coded (note the Label properties, it does not have the "globe" of translations, as we only have one language enabled):
![Captura de Tela 2023-12-15 às 14 04 11](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/a515d0af-9564-41ec-b4b5-df0a6e72863b)

2.1 Now how it appears in Test Mode (we circled the elements that should appear in red):
![Captura de Tela 2023-12-15 às 14 04 00](https://github.com/FlutterFlow/flutterflow-issues/assets/13525605/1cca670f-d051-49eb-8b6a-55107190e891)

**Comment by renanbirlem** [comment]
> @hariprasadmssome more evidence for you, **now on the new project that "stopped working":** Bug Report Code in this new project: IT5fk8nf7Y9Om9tc15DUbPl7/T8RJkM7apIFiutuew4aIurqPKQIYcnSRE5JYsOGdwlIJFmj8XgK0qHNheDxFvoBCwuBaYNeyqV+aDyWWTmgbpObBs+8TnJDL+Bhf36wy7SOmA9QHMRfSVID1DqEIuStShHAHu63DFQdLf6IB5PApHDiHSTCGRFFwmNecCfn
> 
> 1. What the login screen looks like:
>    ![Captura de Tela 2023-12-15 às 14 03 04](https://private-user-images.githubusercontent.com/13525605/290889531-2637948b-68e2-4565-90ff-59bae6af76b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjA2MjcsIm5iZiI6MTcwMjY2MDMyNywicGF0aCI6Ii8xMzUyNTYwNS8yOTA4ODk1MzEtMjYzNzk0OGItNjhlMi00NTY1LTkwZmYtNTliYWU2YWY3NmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE3MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZGM4MDhkZDRhYzUyMjg0NGEwYzk2ZmIzN2ZhNjZjMDUxOWZkNDgyOTYyN2Y4YmRhOWJhYjUxN2UxZTU3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYCxPrwtea6YG820sqxUSs39RIRNOkkiLF6wSlJId8o)
> 
> 1.1. As it is in Test Mode (it is perfectly correct, with all the texts). ![Captura de Tela 2023-12-15 às 14 03 30](https://private-user-images.githubusercontent.com/13525605/290889554-118ce42b-1869-4a7e-8631-93f3ba1b1818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjA2MjcsIm5iZiI6MTcwMjY2MDMyNywicGF0aCI6Ii8xMzUyNTYwNS8yOTA4ODk1NTQtMTE4Y2U0MmItMTg2OS00YTdlLTg2MzEtOTNmM2JhMWIxODE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE3MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMTUwZmU5OGM4MGFhZDk2ZDAwMDAyZTgzMzE0NDdkOWNiNDQ0NGI2OWRhN2I3ZWU4ZTZjYTI4OTcyYTNkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPRDBX8QWpy3pk1no_t70U5TNMN0-zhPtVtNPcCD5vs)
> 
> 2. Now the initial screen (after login), as it is coded (note the Label properties, it does not have the "globe" of translations, as we only have one language enabled):
>    ![Captura de Tela 2023-12-15 às 14 04 11](https://private-user-images.githubusercontent.com/13525605/290890341-a515d0af-9564-41ec-b4b5-df0a6e72863b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjA2MjcsIm5iZiI6MTcwMjY2MDMyNywicGF0aCI6Ii8xMzUyNTYwNS8yOTA4OTAzNDEtYTUxNWQwYWYtOTU2NC00MWVjLWI0YjUtZGYwYTZlNzI4NjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE3MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTgwNGVkYjM0Y2ZiYjEwMTMzNGEyMDI4NWY1Yjg4MmZkNWUwYmViZjAxMjJjM2M3Yzk0ZGNlMWEzYTdiMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkEhGKmTEaqoqO9VGACT9Q3sVowM6iDmeUHPq93DL2M)
> 
> 2.1 Now how it appears in Test Mode (we circled the elements that should appear in red): ![Captura de Tela 2023-12-15 às 14 04 00](https://private-user-images.githubusercontent.com/13525605/290890250-1cca670f-d051-49eb-8b6a-55107190e891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjA2MjcsIm5iZiI6MTcwMjY2MDMyNywicGF0aCI6Ii8xMzUyNTYwNS8yOTA4OTAyNTAtMWNjYTY3MGYtZDA1MS00OWViLThiNmEtNTUxMDcxOTBlODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE3MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZGFmZTdmYTE5ZTZlNjA1MTU2Njk1MjE4NTYwMDVjYjc3MWZhODZmODQ0NTQ2OWY0OWNiM2FlMTc3YTM5MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LvA-l_j-_0IZwfcERQCvvjh9ix3V2may6nr29AHbJp4)

Sorry, I reversed the 1 with 1.1 figure.

**Comment by gutomec** [comment]
I have the same issue, but it only occurs for me in Google Chrome. In Safari, everything works perfectly. I've uninstalled all extensions thinking the problem was some incompatibility with an extension, but that wasn't it.

**Comment by renanbirlem** [comment]
> I have the same issue, but it only occurs for me in Google Chrome. In Safari, everything works perfectly. I've uninstalled all extensions thinking the problem was some incompatibility with an extension, but that wasn't it.

Interestingly we have the same problem in Chrome and Safari. 😞

**Comment by renanbirlem** [comment]
@hariprasadms @sbis04 poderiam nos ajudar a entender melhor esse problema? Os projetos estão disponíveis para verificação a qualquer momento.

**Comment by sbis04** [comment]
Hey @renanbirlem, this just looks like a color issue. So, for the `HomePage` you can explicitly set the color of the background to white but the texts are using `PrimaryText` color which is white in dark mode (and in test mode by default the theme is selected based on your system theme, and that looks like set to dark mode). So, if you just fix the `PrimaryText` color to something darker it should fix the issue.
