### ISSUE TITLE
FlutterFlow Deploy to App Store Finishes, but never makes it to TestFlight

### ISSUE THREAD

**Issue by xenomorph78** [FlutterFlow/flutterflow-issues#2011]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying an app to the App Store, FlutterFlow says that it's finished, but never appears in TestFlight. This is after many successful deployments, but now multiple FF users are having this issue.

### Expected Behavior

Expect the build to show up in App Store Connect TestFlight after 20 to 30 minutes, but never does.

### Steps to Reproduce

1. Deploy to App Store
2. Wait until it shows 'Finished' and then give it 30+ minutes and see if it shows up in TestFlight
3. Notice that it never does.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHq2It1mNsG0ZSILMdGpGQXC08cTIMziNZ+exUbfaL1Bu0AO+PBZVVoXsDgaVNcDlSZnk0yp9bvv9r1FvYEKQiWc7lz1YdqFBb0e2iiRpubCpaKWH96M+1MfEfF36bUrQpQXdF2ZVYDw3GmO+vKfDPDIuu/Zwh9f6PHaOI=

### Context

Trying to deploy to App Store TestFlight.

### Visual documentation

![Screenshot 2023-12-14 at 7 57 40 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/74033405/92195a3d-4c1b-47f1-8963-b7a9ede52ef4)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by pierrecorbay** [comment]
I'm having the same issue. I tried 2 times to deploy my app to App Store and Play Store. Probably a Codemagic-related bug.

**Comment by agreaves** [comment]
Thanks for the bug report, we're taking a look at this now.

**Comment by agreaves** [comment]
This should hopefully be fixed in the next 30 minutes. I'll check in then to verify whether the fix worked.

**Comment by agreaves** [comment]
The fix should be live now actually! 🙂 Please let me know if you continue to experience this same issue!

**Comment by pierrecorbay** [comment]
It's working again, thanks Alex for your responsiveness!
