### ISSUE TITLE
Lottie not loading from assets in Web platform when using CanvasKit

### ISSUE THREAD

**Issue by adamrUK84** [FlutterFlow/flutterflow-issues#2012]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When publishing a Lottie to the Web as an app Asset using CanvasKit there is a 404 error. The asset is trying to be fetched from 'assets/assets/assets/lottie_animations/

### Expected Behavior

Lottie should load.

### Steps to Reproduce

Upload asset
Add Lottie to page
Publish to Web using CanvasKit

Example blank project: https://lottie-issue-h6lhjm.flutterflow.app/

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojMmB289NodhE1aX2Y8dVmSQUNVA8aJINlspBSTUbfIiuP4kQTc/7alZVUteiTAk7L02JhnI1zNGOvt7iA+UnIT+Bbrpe1cx5EQ7LUj6nVJioDLm8Pn9DEfNJJVyz4cCNhRUlXchtZVYH1GWMOPOATj7bJ4zHOWs7Nf2XCN/PnkmrQ0SLb3kNh1JWeC/v

### Context

I'm trying to show Lottie's loaded as an Asset in Web using the CanvasKit

### Visual documentation

![Screenshot 2023-12-15 at 08 00 56](https://github.com/FlutterFlow/flutterflow-issues/assets/130186974/83adb087-9b99-44d7-87e0-35b4c009efdc)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 14, 2023. Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Version 120.0.6099.109 (Official Build) (arm64)
- Operating system and version affected: MacOS 13.4.1 (c)
```

**Comment by takashiff** [comment]
Hello, thank you for your bug report! We've created a fix for this issue, and it should be reflected in the app soon. Thank you for your patience!
