### ISSUE TITLE
Issue with "Paste Data Type" Functionality in FlutterFlow

### ISSUE THREAD

**Issue by gutomec** [FlutterFlow/flutterflow-issues#2014]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to copy Data Types from one project to another in FlutterFlow, I encounter a problem. Initially, the "Paste Data Type" button functions correctly for the first paste but then disappears for subsequent pastes. The alternative method, using the three-dot menu (...) inside an existing Data Type, results in duplication of the current Data Type rather than pasting the new one.

### Expected Behavior

The expected behavior is to have a consistent and functional "Paste Data Type" button or feature, allowing for multiple Data Types to be pasted across projects without disappearing or causing duplication issues.

### Steps to Reproduce

1. Copy a Data Type from one FlutterFlow project.
2. In another project, use the "Paste Data Type" button for the first time - it works as expected.
3. Try to paste another Data Type - the "Paste Data Type" button is no longer available.
4. Use the alternative method (three-dot menu inside an existing Data Type) - it results in duplication of the existing Data Type instead of pasting the new one.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No widget related

### Context

This issue is hindering the efficiency of managing multiple projects with shared Data Types, leading to increased time and potential for errors in the development process.

### Visual documentation

When blank has "Paste Data Type" Button;
<img width="1462" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4014465/1242b5aa-da9e-4a0e-bbe0-660b3a33ff36">

After first paste the button disappear, and can't paste another ones.
<img width="1466" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4014465/fa509050-8a46-4c35-89d1-76ce54fcd881">

This paste option duplicates the Data Type.
<img width="1464" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4014465/f9dea5e7-0cb8-4331-9833-bbd9499487c7">

### Environment

```markdown
- FlutterFlow version: Kotlin Version 1.7.10
- Platform: Web, MacOS Macbook Air M2
- Browser name and version: Chrome, Safari and FlutterFlow App
- Operating system and version affected: Sonoma 14
```

**Comment by gutomec** [comment]
This issue should be simple to resolve by not hiding the 'Paste Data Type' button after the first data type is created, or by allowing the open data type to be closed and, when closed, displaying the initial screen as if no data type is open, or by adding a button next to the '+' for 'Paste' when there is a data type in the clipboard.

**Comment by hariprasadms** [comment]
Hi @gutomec - Thanks for posting the issue. I can see what you are trying to see. This I can make it has enhancements. However by clicking on three dots in the right top corner you can still past the data types and create a new type.

**Comment by gutomec** [comment]
> Hi @gutomec - Thanks for posting the issue. I can see what you are trying to see. This I can make it has enhancements. However by clicking on three dots in the right top corner you can still past the data types and create a new type.

Hi @hariprasadms, When you paste using the 3 dots, the opened data type is duplicated, and the data type that was in the clipboard is not pasted.

Please, try do it.

**Comment by gutomec** [comment]
---
title: Inconsistent 'Paste Data Type' Functionality
labels: bug
assignees: @hariprasadms 

---

### Description
There is an inconsistency with the 'Paste Data Type' functionality. When copying a Data Type X to paste into Y with the intention of renaming it to Z, Y gets duplicated instead of X being pasted. This unexpected behavior indicates a bug and not just "feature / enhancement request".
### Steps to Reproduce
1. Access 'Data Types' and create two Data Types.
2. Copy one of these Data Types or one from another project.
3. Attempt to paste it into a different Data Type than the one copied, using the paste option in the three-dot menu.
4. Observe that the Data Type in which you are gets duplicated, instead of pasting the copied Data Type.

### Expected Behavior
The expected behavior is to paste the copied Data Type into Data Types without duplication.

### Actual Behavior
The Data Type where the paste is attempted gets duplicated, and the copied Data Type is not pasted/created.

### Impact
This bug affects the expected functionality and workflow efficiency, leading to potential errors and time loss.

### Environment
- FlutterFlow version: 1.7.10
- Platform: Web, MacOS
- Browser: Chrome, Safari, FlutterFlow App
- OS: MacOS Sonoma 14

### Additional Context
I have suggested some improvements to address this issue, but the fundamental problem persists as a bug. I am available for further clarification if needed.

BR.

**Comment by gutomec** [comment]
Team member, It is a BUG, and it is simple to be solved. Don't close it. Mark it as bug please.

**Comment by sbis04** [comment]
Hey @gutomec, I think currently it's not possible to paste data types across FlutterFlow projects. This is correctly marked as a feature enhancement, but I understand the frustration of not being able to copy/paste data types across projects. We will look into improving this.

**Comment by gutomec** [comment]
I'd like to emphasize that this problem also exists within the same project, which I consider to be a BUG. It's possible to perform the first paste between different projects when the destination project doesn't have any data type yet. But, after this action, the paste option disappears, probably because it's not possible to have a screen without an open data type. This significantly limits the functionality and efficiency of working in FlutterFlow.

For different projects that use many of the same data types, it would be very important to have this functionality working properly, as it would avoid wasting hours creating dozens of data types. I also understand that when a BUG is not considered a BUG, you give it less attention to its correction, which in this case is simple to be done.

**Comment by sbis04** [comment]
Thanks for more info @gutomec. Just wanted to give an update, we already have an item on our board for improving this copy/paste experience!
