### ISSUE TITLE
App Store Deploy Fail: "Error: Dart library 'dart:html' is not available on this platform"

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#2015]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I deployed many times and still the same and when I switch to the exported code it's still the same.
The problem from Web config with firebase after my last check!
<img width="1680" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/9f875f13-3757-43a1-9c1f-f9b1490de195">

### Expected Behavior

This project its a mobile app and we decided to use the website also as web app linked with custom domain and we set all the configurations well that came from your base.

### Steps to Reproduce

Is about deployment !

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTisrlz8xIpb1I+KnQd+5VoDsWGUMdXOczitVEew4bCIj4EOwUduClUFNvcO6zaH5AAlf8+Dod0+jeiYTtFu45MkyqfaY7ypYNWBPPbGShaLagO7isX2pBL+1YN0DAy8PUkx1+WdRedXcuwU77POi+RT2Cf9qOYwx5e6fDbOY=

### Context

We're wasting time and the client need to test the app via TestFlight !
We need to move fast at this moment if you can help.

### Visual documentation

<img width="1228" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/5221c919-9bdc-4362-8bcb-b124a217170c">
<img width="1680" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/a2b43618-4f6d-4aec-a48e-1b5f634ad3ec">
<img width="1295" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/b83ab582-8119-44b7-a325-881904995121">

### Additional Info

1- After we finish our 80% of project client we want to start the tests via TestFlight 
2- The issue is come after that.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 14, 2023
Flutter version is 3.13.7
- Platform: Mobile & Web
- Browser name and version: Chrome 119
- Operating system and version affected: macOS Sonmoma
```

**Comment by ImadBouirmane** [comment]
Hi FlutterFlow trzm
Please can you remove the conditionals when we send a new issue because I must to check boxes and is not necessary like reproduce then I can submit!!

**Comment by ImadBouirmane** [comment]
I need your response here team like a guide to solve it outside the project.
@kevintonb @takashiff

**Comment by ImadBouirmane** [comment]
Any updates here team @kevintonb @takashiff @agreaves

**Comment by hariprasadms** [comment]
Hi @ImadBouirmane - Thanks for submitting the issue.  The error you see below reason.

In this custom code _**getProfileViewersCount**_  you have used `import 'package:firebase_analytics_web/firebase_analytics_web.dart';` This import should not be called directly in custom code. Remove this line and build. It should work with no errors.

<img width="1512" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b438a7e4-30e7-4567-bdea-f93a66290a73">

iOS build is successful. 

<img width="329" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/2213c60b-719d-4e5b-86ed-a5256575ed16">

**Comment by ImadBouirmane** [comment]
Thanks @hariprasadms it's work 👌🏻
