### ISSUE TITLE
Unable to use Enums with "List contains item" option

### ISSUE THREAD

**Issue by Hodgekins** [FlutterFlow/flutterflow-issues#2018]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I create a list of enums, I'm unable to use "List contains item" and select the enum.
<img width="975" alt="Screenshot 2023-12-17 at 11 13 24" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2507526/b970c471-7037-4b91-ac69-96a8d9e77040">

### Expected Behavior

To be able to choose "List contains item" and select an enum, and for a boolean to be returned.

### Steps to Reproduce

1.) Create an enum "roles", create some values E.g. "editor"
2.) Add a page parameter: List<roles> (page parameter for simplicity, in my project I'm adding this list to a users collection)
3.) Choose any widget and try to use a variable to control visibility. Find the page parameter, choose "List contains item" select enum, roles, and I'm unable to select any enum values. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx892sdtD+KXibflFpD04CUMBX5Ir1utvGBMjC5ysE4oiP+LEaXduQtOXSghcAmCbhlMDzM77j87LF8I6ZA6ufb1607puVzzhfFinV8TTO7iSYXZCJ9hXCHaM4cOJswl+VcRZSU4SwE+Pcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I would like to use enums to create role based permissions. I'm trying to control visibility based on whether a user has a role. I can achieve this using List<String>, but I thought using enums would be better.

### Visual documentation

<img width="975" alt="Screenshot 2023-12-17 at 11 13 24" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2507526/b970c471-7037-4b91-ac69-96a8d9e77040">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web, MacOS Desktop
- Browser name and version: Chrome 120.0.6099.109
- Operating system and version affected: macOS Sonoma 14.1
```

**Comment by hariprasadms** [comment]
Hi @Hodgekins - Thanks for reporting the issue. At present, Enums are not able use as list features. This is limitation around current implementation. I can mark this issue has enhancement request. No ETA. However you can use custom code functionality to work with Enums as per your requirements.

**Comment by Hodgekins** [comment]
Hi Hari,

Thank you for letting me know. Much appreciated!

All the best,

Ben

**Comment by tophat1986** [comment]
> Hi @Hodgekins - Thanks for reporting the issue. At present, Enums are not able use as list features. This is limitation around current implementation. I can mark this issue has enhancement request. No ETA. However you can use custom code functionality to work with Enums as per your requirements.

Is this is also related to Enums not working as **dropdown options**?  I can get it to "map list items" but it then still requires "sorting" or "filtering" which also doesn't seem possible (this shouldn't be required either, or at least the option to sort easily per requirement)

I was excited to use Enums but it seems it might be part of other bugs surrounding it atm - https://github.com/FlutterFlow/flutterflow-issues/issues/1840

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/29504604/028d0298-88d8-477b-bc75-a71833deab5c)

**Comment by takashiff** [comment]
I believe it could be related. I've put in a feature request internally for better support surrounding enums (the use cases described above). Thank you for your patience.
