### ISSUE TITLE
Cannot hit test a render box that has never been laid out.

### ISSUE THREAD

**Issue by kanatbkeeep** [FlutterFlow/flutterflow-issues#2019]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The application crashes when I try to render the page In test mode. In run mode all is alright. With error: 
The following assertion was thrown during performLayout():
dart_sdk.js:29145 RenderFlex children have non-zero flex but incoming height constraints are unbounded.
dart_sdk.js:29145 When a column is in a parent that does not provide a finite height constraint, for example if it is
dart_sdk.js:29145 in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
dart_sdk.js:29145 flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
dart_sdk.js:29145 space in the vertical direction.
dart_sdk.js:29145 These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
dart_sdk.js:29145 cannot simultaneously expand to fit its parent.
dart_sdk.js:29145 Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
dart_sdk.js:29145 children (using Flexible rather than Expanded). This will allow the flexible children to size
dart_sdk.js:29145 themselves to less than the infinite remaining space they would otherwise be forced to take, and
dart_sdk.js:29145 then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
dart_sdk.js:29145 constraints provided by the parent.
dart_sdk.js:29145 If this message did not help you determine the problem, consider using debugDumpRenderTree():
...
Cannot hit test a render box that has never been laid out.

### Expected Behavior

fix the error

### Steps to Reproduce

Create a page. Add text fields. Check. Everything works in test mode. After +-2 month add new text fields. Nothing works in test mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gyfLlvYtNxLRE7qrcae9ajWUQNjI3a700st4bGAsdGOvrBu0EPc6kSBJtZMylaVNcBFWlsHkx0v+KvuDDEfQCPkmbQbpB1rV+SznOe2iuV8SbO7mCf3wnL9JRIECD1sOJkxEmKrd2LFlk1GeIIfCWTXbDBOu/Zwh9f6PHaOI=

### Context

It became harder to work. Since now I need to check all the time through "run mode" or through the apk file

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/79863395/12f18d79-5afa-4295-b44f-823ac07c8138)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: android, ios
- Browser name and version: chrome 120.0.6099.72
- Operating system and version affected: windows 11
```

**Comment by hariprasadms** [comment]
Are you still facing the issue ? I can't reproduce it. Can you please try this in a new project?
