### ISSUE TITLE
Color setting from local state is different from color setting manually with the same color code

### ISSUE THREAD

**Issue by lakshmiRamesh2** [FlutterFlow/flutterflow-issues#202]
There is a difference When I am setting the color to a container from the local state vs setting it manually. Here the color code is the same.

## Expected behavior (required)
It should render the same color when testing it Run/Test mode

## Current behavior (required)
It is rendering the two different colors when testing in Run/Test Mode
## To Reproduce (required)

1. Create new page
2. Add container widget
3. Set a color maually to it, the color code is #804B39EF
4. Create a variable in the local state of type string, give the default value is #804B39EF
5. Add one more container, and set color from string, select local state option.
6. Run 
7. You will observe the two containers with two different colors
8. Project URL: https://app.flutterflow.io/debug/gC2JOkYRNUoGTfvkcYiz

## Context (required)
When I am trying to set color dynamically, visually it looks different.

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/45360049/206448366-0f2c3acb-9923-413a-9aae-ad115be499ba.png)

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome and Version 107.0.5304.107 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): desktop

**Comment by wenkaifan0720** [comment]
Due to inactivity and inability to reproduce of this issue, I'll close it for now.
