### ISSUE TITLE
Any new page added to project shows blank

### ISSUE THREAD

**Issue by olivierb24** [FlutterFlow/flutterflow-issues#2020]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a fully functional app (deployed to play store). Any new page added to the project shows up blank. Pages with just text, images or even template pages all show up as blank which makes it impossible to continue developping the app.

Console shows no error, Android studio does not show any error. 

### Expected Behavior

Any newly added page should be visible and functional.

### Steps to Reproduce

1. Create new page
2. Add anything to the page
3. Naviguate to the page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olPHlw852j7xe7aXycfkwmSQQOW42UIJJmMpBZywgfZzzBLN/fPfQP1RucN+qYH9XfGe2p14F//+KveHxGvUqNTSYfqpH+KgNVTr/ZHmVbKWTF7W8eXdRGcdmCGq13KuvvxEnVbRuSl4b7TuYJPOtYAPfCZTTPmo4Sq/LZO4=

### Context

I am unable to continue the development of my app since anything new I add to it does not appear. No errors or console issues show up.

### Visual documentation

![Screenshot 2023-12-15 164500](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/49f8676d-675d-4194-82bd-ba715eefbd44)
![Screenshot 2023-12-15 150516](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/b22916f5-c153-4285-82ee-b47ec2481ad9)
![Screenshot 2023-12-15 150438](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/e0272d35-ceb9-44ad-9336-70329777f3cc)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web, Desktop, Android
- Browser name and version: Chrome Version 120.0.6099.109
- Operating system and version affected: Windows 11
```

**Comment by olivierb24** [comment]
Hi, yes still no luck. Unable to continue working this app. Just did some more testing (18 Dec 2023). Same issue, I just get blank screens (grey screen) and no visible errors. When I ran in "run mode" I got this error in the console but that is all:


![Screenshot 2023-12-16 103807](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/270b6d10-d4ae-4385-82d8-01a010da0a58)

**Comment by hariprasadms** [comment]
Can you please check if this can happen in new a project as well? if it happens send me the project link. Thanks

**Comment by olivierb24** [comment]
So far it's not happening in new projects. I'm re-creating the entire app and I can add pages normally.
