### ISSUE TITLE
Issue with Updating 'emailVerified' Boolean Value in Users Document

### ISSUE THREAD

**Issue by Ivorleafer** [FlutterFlow/flutterflow-issues#2023]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Encountered an issue while attempting to update the 'emailVerified' boolean value in the users document. The requirement involves toggling the boolean value to 'true' when a user verifies their email address. This functionality aims to reflect the email verification status within the user record.

Unable to update the 'emailVerified' boolean value to 'true' after a user verifies their email address. This prevents the accurate reflection of the verification status within the user record.

### Expected Behavior

Upon successful email verification, the 'emailVerified' boolean should be set to 'true' in the user's document, indicating the verification status as 'verified.'

### Steps to Reproduce

1. Trigger email verification for a user.
2. Attempt to update the 'emailVerified' boolean value to 'true' in the user's document.
3. Verify the status of the 'emailVerified' boolean post-update.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8/fsIZOsdtY7pSIYO9WiicRJkN6a700st5Hd0gdCOPrBuxzfeCkP1tvTt+iaVNfeWGJgXEz/83Hi979LPJcAAebQb5Hwc5Ibzn0e2iQR5iwDpONPmtfEd5NGn6uy4mNkBEnHLJiR1IG3GapeumUa3fDFOu/Zwh9f6PHaOI=

### Context

The 'emailVerified' boolean should update to 'true' in the user's document upon successful email verification, ensuring an accurate representation of the verification status.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/48736987/37120217-37cc-4c19-9ee2-388490b24671)

### Additional Info

Preferably, the 'emailVerified' boolean value should reflect as 'true' for verified email addresses and 'false' for non-verified addresses within the user record.

### Environment

```markdown
- FlutterFlow version: V4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.72
- Operating system and version affected:
```

**Comment by Ivorleafer** [comment]
Hello,Thank you for responding.1. The user receives a link to their email.2. There isn’t an action I have added to update the users document. Only an action to send the link. In hindsight I can indeed create an action to update the document, but, I’m looking for the document to update when the user verifies their email.3. How would I go about implementing the cloud function?Thanks,LanceOn Dec 19, 2023, at 08:20, Hari ***@***.***> wrote:﻿
Hi @Ivorleafer - Thanks for submitting the issues. I need bit more information to understand where exactly the issue. Can you please explain the flow of verify email you have configured. Answer below questions.
Are you receiving verify email link when send email verification action is triggered ?
When email is verified by user, what action you got to update the boolean flag in doc after post update ? - If you got action, where is that action is configured ?
At present, FF does not have default feature to update the doc once email is verified. This can be done via cloud functions.
`
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
exports.updateUserProfile = functions.auth.user().onCreate((user) => {
const uid = user.uid;
const emailVerified = user.emailVerified;
if (emailVerified) {
    // Update Firestore document
    const userRef = admin.firestore().collection('users').doc(uid);

    return userRef.update({
        emailVerified: true
    });
} else {
    return null;
}

});

**Comment by hariprasadms** [comment]
As per current design, document fields are not able to update after email verification is done. This should be handle through custom functions.

Here is a youtube video about custom functions - https://www.youtube.com/watch?v=Xn8iWNN_12U

**Comment by takashiff** [comment]
Hello, you can find more info on FlutterFlow cloud functions [here](https://docs.flutterflow.io/customizing-your-app/cloud-functions). Thank you for your bug report, and as always, if you encounter any other issues, feel free to contact our technical support team or open another GItHub issue.
