### ISSUE TITLE
Bug reports in experts.flutterflow.io

### ISSUE THREAD

**Issue by nyaroon** [FlutterFlow/flutterflow-issues#2024]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

change picture in experts flutterflow cause grey crash and make it back to 1st form creation experts

### Expected Behavior

after change picture the picture should be change to new picture previvew and save it succesfully and back to home page

### Steps to Reproduce

1. register as experts and fill the form
2. go to profile and edit profile
3. press change picture directly
4. the picture didnt change
5. if you press seave the page will be grey and cause error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

as

### Context

change the picture of experts

### Visual documentation

0

### Environment

```markdown
- FlutterFlow version: lastest
- Platform: web 
- Browser name and version: safari
- Operating system and version affected: sonoma 14.2
```

**Comment by hariprasadms** [comment]
Hi @nyaroon - Thanks for submitting the issue. Can I ask you to refresh your browser cache and try again ? Try visiting the dashboard and then navigating to the Edit Profile page again. Let me know how it goes. Thanks

**Comment by hariprasadms** [comment]
Hi @nyaroon - We have made some changes. If there is no image found, it will set one as the FF logo while visiting the page. 
Can you please give a try ?
