### ISSUE TITLE
Can't edit backend query.

### ISSUE THREAD

**Issue by Bonnary** [FlutterFlow/flutterflow-issues#2025]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When moving the backend query to the top of the component you can't edit or delete the query.

### Expected Behavior

Can edit the backend query or prevent the user from moving the backend query to the top of the component.

### Steps to Reproduce

1. create a component
2. create a widget that can do backend query
3. move the backend query to the top of the component.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glvLlx412oblE7ZPud+9WpCYvJn56RL00sd4bGA0dCJzuPLMQdvWkXFBpUu3nSn9mfESmmnw0pMGKi9jIGMYCFE6CfNw7wqludwmXIUGRa5OBEbi7dXdSL/hnIFCy4bSrnB5vOtpZL0Il3GayFdmWdz3aNpOzIndISq/LZO4=

### Context

It's annoying when I accidentally click on it.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/69995568/15f73ae2-c63b-4bfc-b6b7-f8225d2715ec

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: any 
- Browser name and version: Chrome 120.0.6099.110
- Operating system and version affected: Windows 11
```

**Comment by gregkeys-fideseo** [comment]
Just ran into this myself, it seems when using the convenience button to move the query to root elements it allowed me to move the query to the top of the component and now I can't do anything with the query.


Here's the bug report code
ITFTksrl25NPxNtG+KXQcMZsp2IQGUMcWOdEl+tuZwgbIoznBu0cPs77cRNtQtDnaVNce06lknwC//zrv+D1Mfk3HwSuRb5B1ZAJSTrOe2i7VYzWOqmST3RDNNNgIG69y8C3ggp/JsVtWXgn202EFeevfA7DBOu/Zwh9f6PHaOI=
