### ISSUE TITLE
Image and text widget not using the default value if empty or null

### ISSUE THREAD

**Issue by DrigoDomingos** [FlutterFlow/flutterflow-issues#2027]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a project and setup several images placeholders across the project and for every API call I have setup a default image to show in case the response is empty or null. it worked since january 2023 till last Friday. Now the default information is not considered and FF is interpreting as error and not displaying any images. I have ran the code on visual code to get more details and I found that a method .toString() was added recently and apparently is transforming the null return to something like 'null
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5956222/371a13fe-6148-4202-a7c4-7e8e55a48c21)
'

Placeholder image: https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/projects/hadronlink-f5o87i/assets/9yjr1333d3bh/NoImagePicture.png

### Expected Behavior

If the API return empty or null use the default image that I setup not thrown an error. 

### Steps to Reproduce

1 Create a new page
2 Setup the source of the image (API or other source)
3 Setup a default value in case the image return null or empty
4 force the image (3) to return empty or null and observe the issue

The same is applied to text

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kz/Hqx892pbxH1rr+c/lR/T8XQ3IkU400ltZ+bEk3GOP1G7YUS8zOTEhuTdOYTGxIJ1mY8Tk1zPyNudrlDsEtPiibRrZn1s0JdwzKe3ymWqWYPrire2t9I99QN3WHzbSO2x4lOtFZLlYn116mIueWSjPqJYDaIVczBfybCK7AonSiASLKXn0Jg1ZSfCvr

### Context

I'm working  in a larger project that this situation is happening everywhere, and due to this issue I cannot keep my tests to deploy my App

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5956222/a8fa1d70-b81c-426e-be1e-9c8328a2a4da)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5956222/25a3d8b7-6f02-486a-849b-48dabe79a276)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5956222/5ce62499-e17f-46a9-aae0-e86cb277f2b6)

### Additional Info

November 20 code working
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5956222/8609669e-4c83-4ce3-b9c1-7c45336b9a7e)

Recent code not working
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5956222/8191171e-bf4a-4871-ae5c-2ed2fe282876)

### Environment

```markdown
- FlutterFlow version: 4.0 - 3.13.7
- Platform: web
- Browser name and version:
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @DrigoDomingos - Thanks for submitting the issue. Did you try 'show error image on failure' option enabled instead   default variable value. See below. Please confirm if that can help you.  

<img width="335" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8834a3a7-c87b-441f-a95c-91ba3daa945f">

**Comment by DrigoDomingos** [comment]
Yes, I tried it but the problem is it enable just one generic image to be used in all pages, and I need specifics default images depending the page the user is in. Also, it’s not an error instead it is empty at some point until the users upload the image, and I believe that’s the objective of this default image to use the default image until the return is not empty or null.

**Comment by agreaves** [comment]
Hi @DrigoDomingos, thanks for the bug report! I've been able to reproduce and track down this bug, and it will be fixed in our next release!
