### ISSUE TITLE
Can't save a custom action

### ISSUE THREAD

**Issue by Milvkim** [FlutterFlow/flutterflow-issues#2029]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, I tried to save a custom action and it doesn't work. I have the pop-up when i click the save action "confirm save" but then nothing happen and it is not appearing in the custom action. 

### Expected Behavior

To find the action in custom action and to be able to apply it in the "action flow editor"

### Steps to Reproduce

1 in custom code
2 press add button 
3 select action
4  go to tab code Copilot
5 Rename action name 
6 entered the action description
7 activate return value and set the type
8 add argument  name and type
9 click on green button and see the code below 
10 click on save action 
11 confirm the pop up that i want to save 
12 nothing happen and it is not saved

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/whotutorial-39d9v9?tab=customCode&customCodeTab=functions

### Context

I can't save a custom action

### Visual documentation

I don't have it sorry

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Milvkim** [comment]
yes i'm still trying to save the custom action but still no't working, here his the link : https://app.flutterflow.io/project/whotutorial-39d9v9?tab=customCode&customCodeTab=actions

**Comment by hariprasadms** [comment]
I just created a custom action in above given project. I can save the code. See below. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/676aeab7-7a5e-4baf-8311-7a14992d1b20

**Comment by Milvkim** [comment]
You are going to fast for me ! I'm a begginer here :D but you can save customaction wich means i'm doing something wrong.. i'm sending you screenshot so maybe you could see what is done wrong, thanks 
![customAction1](https://github.com/FlutterFlow/flutterflow-issues/assets/154342456/462dd716-7bac-4238-8a54-e9aee5340790)
![customAction2](https://github.com/FlutterFlow/flutterflow-issues/assets/154342456/3c39b74f-8321-45f7-89ac-d8b05bfd73b1)
![customAction3](https://github.com/FlutterFlow/flutterflow-issues/assets/154342456/1dfa155d-d552-489d-9249-9074ff59b6ef)
![customAction4](https://github.com/FlutterFlow/flutterflow-issues/assets/154342456/10c6b6b4-c02a-41ea-8707-e978e7e053af)

**Comment by hariprasadms** [comment]
Please follow this video - https://www.youtube.com/watch?v=rKaD9eKuZkY
Custom actions Doc - https://docs.flutterflow.io/customizing-your-app/custom-functions/custom-actions

**Comment by Milvkim** [comment]
Thanks! it was the issue..
