### ISSUE TITLE
Custom code editor is broken

### ISSUE THREAD

**Issue by wednesdei** [FlutterFlow/flutterflow-issues#203]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I expect an upgrade in FF to not break an existing functioning project.

## Current behavior (required)

My custom code editor was upgraded to the new version. The new version has the following issues:
 Clicking the help button shows the list of help items, but you can't click on anything other than the close button.

- Its not parsing variables correctly, as in you can't access list items with a period
 EG: mylist.item 

- It isn't highlighting any errors in the code

- The error message it provides is generic and not as useful as the previous version

- You can assign a double to an int

- Excluding from compilation doesn't even allow the project to compile..................................................

## To Reproduce (required)

See above

### Bug Report Code

The code analysis is broken in this new code editor, or not turned on...

## Context (required)

I can't build my project.

## Your environment

* Version of FlutterFlow used: latest
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: chrome latest
* Operating system and version (desktop or mobile): windows 11 latest

**Comment by bcdefga123456** [comment]
I'm also experiencing this issue.

**Comment by aemelyanovff** [comment]
We fixed a number of issues with the code editor since the release. If you are still experiencing issues, please create another issues. And please include detailed steps to reproduce the issue.
