### ISSUE TITLE
No Actions get executed after Default Action "Create Account"

### ISSUE THREAD

**Issue by KevDev99** [FlutterFlow/flutterflow-issues#2030]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i've the following action chain for a register button:
<img width="265" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/3dd37a91-aa0e-4ba0-940d-c73746a41f6d">

i want to accomplish a very simple task: user clicks create account -> navigate to login page -> show a snack bar with the information to confirm mail.

it doesn't run the navigate to command or the show snack bar command - what is missing here ? 

as backend supabase is used.

### Expected Behavior

when "account created" action is successfully the" navigate" action is executed also the "show snack bar"

### Steps to Reproduce

set the actions as in the image 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcjfz4VNseFd0a6Jc8ZVlWQQHF8cTeU30+thcw4bI+PzP4YEZuPBP1NvcuqHf1BYG2H8rE8E063FjuzuU/kDEziVfLpNwcxfUxDvUme5R8jQPKiCT3F5M8RnGEyE1MKF3AokLvJeV1oG2Dibf9m+Y3qCf9qOYwx5e6fDbOY=

### Context

i can't even get the register flow working. googling didn't get me a correct result, i can't believe that this isn't a standard functionality which should work.

### Visual documentation

<img width="265" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/3dd37a91-aa0e-4ba0-940d-c73746a41f6d">

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Edge, 120.0.2210.61
- Operating system and version affected: Windows 10, 22H2
```

**Comment by hariprasadms** [comment]
Hi @KevDev99 - Thanks for submitting the report. The behaviour what you are seeing now is a expected behaviour. Once account is created in supa-base, you should login action to login to the application but it does not allow user to login while registering the account. This is current limitation what we got at the moment. 

Refer below message in create account action. It gives some idea to implement the behaviour what you are expecting. 

<img width="457" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/3ddedf64-5109-4400-8c2b-dfead711aa91">

**Comment by KevDev99** [comment]
Hi @hariprasadms - it is an unnecessary complication of the process, is this something that is likely to be fixed at some point ? I can't imagine that something like this is being deliberately accepted

**Comment by hariprasadms** [comment]
Hi @KevDev99 - Sorry for the confusion. I just checked it. It should allow user to automatically login to app when create account is successful. It works fine at my end. 

I assume it may not be happening for you as you might have user table row level security issue. Can you please confirm all set correctly at user table and its rule level.

**Comment by KevDev99** [comment]
Hi @hariprasadms thanks for your feedback. well of course it does work when disabling the email verification but i think that needs to get asap on the roadmap to improve the connection between flutterflow and supabase. an authentication flow is mostly the first process you create and that already needs a workaround which costs a lot of more time then for exampling coding it directly... authentication standards such as Email Verification simply have to work seamlessly in a low code solution

**Comment by hariprasadms** [comment]
Hi @KevDev99 - As per current design its been recommended to disable email verifications. However, we already got a feature request for this. Thanks for highlighting. We will make a note of it. 

Can you please change the title of the issue specific to enable email verification? Thanks

**Comment by takashiff** [comment]
Hi @KevDev99, thank you for your bug report. As @hariprasadms has mentioned, this is currently intended behavior due to how Supabase Auth functions. I can put in a feature request internally for you if you'd like, although I cannot make any guarantees on an ETA. Thank you for your patience.
