### ISSUE TITLE
Change to background color of Action Flow Editor (sometimes) makes it difficult to see flow lines

### ISSUE THREAD

**Issue by RickAtSavveLabs** [FlutterFlow/flutterflow-issues#2031]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In one of my Actions, the background has changed as shown below. Note that I only experience with one of my Actions, and the others continue to render fine in the editor. This particular action has both conditions and a loop.
![Screenshot of Safari (12-19-23, 10-32-45 AM)](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/2d353cc7-28fc-4e14-8231-92d3c2482472)

### Expected Behavior

The normal dark background should be shown to provide easy to see contrast with the flow lines

### Steps to Reproduce

1. Enter the action flow editor. Unclear if this is associated with flows that contain conditions and/or loops.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

Hampers my ability to continue editing my workflow

### Visual documentation

![Screenshot of Safari (12-19-23, 10-32-45 AM)](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/2d353cc7-28fc-4e14-8231-92d3c2482472)

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Mac
- Browser name and version: Safari, v17.2
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
HI @RickAtSavveLabs - Thanks for submitting the issue. Is this still happening for you ?

**Comment by RickAtSavveLabs** [comment]
Hi Hari,

Thanks for the responsiveness. 

I just checked, and unfortunately, it is still happening.


-----
Rick Chin
SavvēLabs
***@***.***
(508) 736-5749

**Comment by RickAtSavveLabs** [comment]
Hi Hari,

Quick update. I was working on that Action, and deleted the loop I had defined within. As soon as the loop was gone, the display returned to normal.

**Comment by takashiff** [comment]
Hi @RickAtSavveLabs, thank you for your bug report. Could you share the bug report code for the widget with the associated action(s) that is causing this? Thanks

**Comment by RickAtSavveLabs** [comment]
Hi @takashiff . I am still relatively new to FlutterFlow, so apologies if I did not do this correctly.

As mentioned above, the issue disappeared after I deleted a loop. I went back to my v9 of the project (20-Dec) to get the bug report code. This did not seem to work. I tried to get report on the latest version, but there was a copy to clipboard failure. 
![Screenshot of Safari (12-28-23, 10-01-16 AM)](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/9d0dca78-d004-417d-984c-53ecdc8b04b6)

How might I proceed in a helpful manner. Thanks.

**Comment by takashiff** [comment]
@RickAtSavveLabs No worries. Did you run into the same error when trying to generate the bug report code on your previous version?

**Comment by RickAtSavveLabs** [comment]
@takashiff nothing seemed to happen when I tried on the earlier version. I clicked twice and the menu disappeared. I did a paste, and there was no bug report code.

**Comment by takashiff** [comment]
Got it, thanks for the update. If you don't mind elaborating, where exactly is/was the loop action? I am not seeing it inside of the screenshot you have provided. Thanks

**Comment by RickAtSavveLabs** [comment]
@takashiff does this help?
![entireActionBlockWithLoop](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/7a779bf9-6426-4c74-b369-81def532dab0)

![Loop](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/aa0e782e-974a-4747-84ac-4bbad921f959)

**Comment by takashiff** [comment]
@RickAtSavveLabs Yes, thank you!

**Comment by victoriahuang1** [comment]
This should fixed upon the next deploy
