### ISSUE TITLE
Custom Dialog not scroll

### ISSUE THREAD

**Issue by ricardocosta43** [FlutterFlow/flutterflow-issues#2033]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![errado](https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/7ccbada9-0826-4838-8a4b-b741658a8e14)

When using the "Custom Dialog" action, passing a widget, and in this widget there are several items such as TextField. When the keyboard opens the dialog does not scroll up
I noticed that fluterflow uses the "aligned_dialog" package, and it doesn't really behave like a regular Flutter Alert dialog

This is bad for use cases like the one described above

The user is not smart enough to know that when clicking away he dismisses the keyboard

### Expected Behavior

I hope the dialog scrolls up as shown in the print sent
![correto](https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/f7ea6692-f7ae-46f3-9659-091fbab3de80)

Este exemplo do print, utilizo AlertDialog nativo do Flutter
![Captura de Tela 2023-12-19 às 10 24 50](https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/a9eb0f42-14e3-4d4f-86e6-3710b88b165b)

### Steps to Reproduce

1 - Create a project, a blank page and add a button
2 - Create a component that has a text field
3 - Add a "Custom Dialog" action to the button and add the created component
4 - Run the project on Android or IOS and click on the button
5 - Click on the textfield, see the keyboard open and notice that the dialog does not go up for you to see it completely

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

not more

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/12566796/862d6a60-0e2b-469e-8d47-2266bb3a30dc

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform: Android and IOS
- Browser name and version: Chrome 116.0.5845.187
- Operating system and version affected: mac Sonoma
```

**Comment by SameerShahzad99** [comment]
@ricardocosta43 please share the bug report code from the blank project where this issue has been reproduced, as it would be required to proceed with the process!

**Comment by sbis04** [comment]
This should be fixed in the next update!
