### ISSUE TITLE
Condition Action is not working (crashing)

### ISSUE THREAD

**Issue by KreKdev** [FlutterFlow/flutterflow-issues#2035]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Condition Action is not working when you try to compare the current date with a date field, and this date comes from a field in firebase, but if this field does not exist for a specific user, the conditional does not return true or false, it must be freezing internally.

### Expected Behavior

Even if the firebase record does not contain the field, the Conditon Action should return True or False, not freeze

### Steps to Reproduce

1. create a conditional for compare two dates in Unix Secs format
2. first value must be a field in Firebase in timestamp format with DateTime to Unix Timestamp, Seconds
3. second value must be Current Time with DateTime to Unix Timestamp, Seconds
4. if the field in not present in the database, the action hangs, not returning true or false

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXjMrqx891rsBE1ZfUbu0wp2EwGUwbUOc7j9VEGAsjCePtB7MqPczCUEluWOqHeVFAAWD/inIGpejpkYThLfEpB0uBY65OybtbUxDhVj26VL3SCbqOW2hDI8ZTfxGn5Jm7gCYkBNJidVEjw0zzINiQb3qCf9qOYwx5e6fDbOY=

### Context

Make a simple comparison

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/f84528ec-6f93-415c-af81-9c0c3d93ad78)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/9939bff8-d94b-434d-b923-9b7982e4c5e2)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/7911a130-120f-4a5b-9dea-06a70f43e5c3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/c458eef4-8acd-4f02-9b8c-cdf7d74d6d6f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151834055/446c4127-2c7e-4c9b-a8b8-98fc0ea4de2e)

### Additional Info

The credits_validity field is a timestamp field in firebase

### Environment

```markdown
- FlutterFlow version: Flutter version is 3.13.7
- Platform: web
- Browser name and version: Version 120.0.6099.109 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @KreKdev - Thanks for submitting the issue. I can confirm that it is not a bug in the feature. It is mostly related to date formate conversation to compare two values. You should use custom code to make it work.
