### ISSUE TITLE
Deploy to App Store Previous Build Version Error causes Failed Step in Publishing

### ISSUE THREAD

**Issue by armandoeortiz** [FlutterFlow/flutterflow-issues#2036]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying to the Apple App store and incrementing the Build Number on the Mobile Deployment page but using the same App Version, I get a "Failed Step: Publishing" error and the content reads "409: The bundle version must be higher than the previously uploaded version."  However, the bundle version is higher as I have manually incremented it.  The only way I have found to resolve this issue is to increment the App Version by X.X.1 and the Build Number by 1 and then resubmit the Deploy to App Store button.   I am using the MacOS Client.  I have successfully deployed over 100 times in the past month so I know it is not my App store setup causing the issue.  This issue is with MacOS FF 4.0.3 and was a problem already before the 12/16 update of the MacOS client and remains an issue.

### Expected Behavior

Expect that when using manual Build Number assignment, incrementing the Build Number should be sufficient to represent a new build version and we should not need to increment the App Version as well.

### Steps to Reproduce

1. Update my project
2. Save the project
3. Navigate to Mobile deployment
4. Manually set the Build Number by incrementing it by one
5. Click Deploy to App Store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not Widget Specific

### Context

When this happens I cannot update my app in TestFlight or the App Store delaying my app deployments.

### Visual documentation

<img width="617" alt="Upload UsersbuilderclonebuildiosipaJuri ipa to App Store Connect" src="https://github.com/FlutterFlow/flutterflow-issues/assets/149453748/ec67bc0a-51fa-4376-920f-4430afd6b8ed">

### Additional Info

Note that once I increment the App Version, I can deploy, but that is not the expectation.  We should be able to keep the app version the same and only increment the build number.

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform: MacOS
- Browser name and version:N/A MacOS 12/16/23 version
- Operating system and version affected: MacOS
```

**Comment by SameerShahzad99** [comment]
This looks like a project-specific issue , please reach out to support for such cases!

**Comment by armandoeortiz** [comment]
@SameerShahzad99 This is not a project issue and could likely be an issue with the MacOS FF app and Codemagic.  The fact remains that on occasion the FF MacOS app does not seem to send an updated Build Number eventhough I have provided one in the Mobile Deployment Page.  In fact, I now have a new screen shot from this week where the build number seen on the Mobile Deployment page is set to 180 but the error referrences the previous 178 build which makes me think the MacOS FF app is not sending the correct build number or at times is not updating the build number for some reason.  I do not know if this happens from the web app for FF.  My temporary work around is to increment the App Version number and rerun the Deploy to App Store button.  See updated screenshot.
<img width="1243" alt="Pasted Graphic" src="https://github.com/FlutterFlow/flutterflow-issues/assets/149453748/4eb505d3-7630-4f88-8936-2f4dad08f674">
