### ISSUE TITLE
Unable to use Enums with "dropdown options"

### ISSUE THREAD

**Issue by tophat1986** [FlutterFlow/flutterflow-issues#2037]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Enums cannot be used in dropdown options.
You can select "[]values" but cannot progress any further.
It requires "sorting" but setting that doesn't seem to work either.

### Expected Behavior

To allow a Enum list to be used as the "options" in a dropdown. 

### Steps to Reproduce

1. Create Enum values
2. Add Enum option to dynamic dropdown option
3. Select Enum list created
4. Unable to create (shows error)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzMr1z89goelA7pPpbcFsqycWC1B8TL07p+xEGA8rCOOtPLJ+eM/eTEhCXt+4T2lhHFeKiXIdwcr9iPH1DsAFHyqWGdlO+bhQZTuXQXq8Raa1DKi/dHMlP8RUGWKXyIm3mxRdOvpuW1IF3GWhN+TKQibUGZ+/Zwh9f6PHaOI=

### Context

Use Enums for controlling list options for various use cases.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/29504604/7f617447-aa8a-410b-b282-8142d2d7865e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/29504604/78904b34-de33-41d7-8211-757fe4d3172f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/29504604/9afa7ef8-a6d0-4df7-9f25-bbdc9e3a31ae)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.110 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by takashiff** [comment]
Hello, thank you for your bug report. Unfortunately, this looks to be a current limitation of FlutterFlow. I will go ahead and put in a feature request internally, so that this could one day be supported. Thank you for your patience.

**Comment by federico-s** [comment]
Any update on this? I think this IS a bug and need to be addressed.

**Comment by Night-coyote** [comment]
Waiting to solve this issue

**Comment by sebastianoboem** [comment]
i know this is a closed issue but i kinda have repicated the problem:
It seems affected by the alignment property of any parent widget of the dropdown
if you remove any sort of alignment it will work.. at least for me

and try to find if u have named any enum in a way that can be too similar of a property of any kind...
