### ISSUE TITLE
Radio Button Disable Bug

### ISSUE THREAD

**Issue by harshtonde** [FlutterFlow/flutterflow-issues#2038]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a Radio Button disability condition is set from a variable then the RadioButton's state doesn't update once the the radio button gets enabled.

### Expected Behavior

On selection of radio button the option should get selected

### Steps to Reproduce

1. In a blank project, add a dropdown and a Radio Button
2. Set the Radio Button Disable condition based on if the Dropdown's value is not set or empty. 
3. Run the App.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fhvLl249Oj7xZ0KXqKcEw+CQvNmY1UII3kdV6EBEdGLnqEYouZ/TsT1VJbbyWTAl2eGGZ/W0zp8rFuM7tDMBcAByJbIBBycxyWAGUWmWtV8mgO868YUZSGflgI0C1zpuZnAp5KrFiSiEB62auLuiUfC/ZGIDBOmsdBsqLDL7ApGjiLgzOGX0Jg1ZSfCvr

### Context

Radio Button state should update  once it is enabled after being disabled

### Visual documentation

![Screenshot 2023-12-20 at 2 00 46 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/59639282/ccae725d-17f0-49ff-9d2e-1b6a8ba26647)

### Additional Info

This is the code that fixes the issue. 
```

class _FlutterFlowRadioButtonState extends State<FlutterFlowRadioButton> {
  void Function()? get listener => widget.onChanged != null
      ? () => widget.onChanged!(widget.controller.value)
      : null;

  @override
  void initState() {
    if (listener != null) {
      widget.controller.addListener(listener!);
    }
    super.initState();
  }

  @override
  void dispose() {
    if (listener != null) {
      widget.controller.removeListener(listener!);
    }
    super.dispose();
  }

  @override
  void didUpdateWidget(FlutterFlowRadioButton oldWidget) {
    super.didUpdateWidget(oldWidget);
    final oldWidgetHasOnChanged = oldWidget.onChanged != null;
    final newWidgetHasOnChanged = widget.onChanged != null;
    if (oldWidgetHasOnChanged != newWidgetHasOnChanged) {
      if (oldWidgetHasOnChanged) {
        oldWidget.controller
            .removeListener(() => widget.onChanged!(widget.controller.value));
      }
      if (newWidgetHasOnChanged) {
        widget.controller.addListener(listener!);
      }
    }
  }

  List<String> get effectiveOptions =>
      widget.options.isEmpty ? ['[Option]'] : widget.options;

  @override
  Widget build(BuildContext context) {
    return Theme(
      data: Theme.of(context)
          .copyWith(unselectedWidgetColor: widget.inactiveRadioButtonColor),
      child: RadioGroup<String>.builder(
        direction: widget.direction,
        groupValue: widget.controller.value,
        onChanged: (value) => widget.controller.value = value,
        activeColor: widget.radioButtonColor,
        toggleable: widget.toggleable,
        textStyle: widget.textStyle,
        selectedTextStyle: widget.selectedTextStyle ?? widget.textStyle,
        textPadding: widget.textPadding,
        optionHeight: widget.optionHeight,
        optionWidth: widget.optionWidth,
        horizontalAlignment: widget.horizontalAlignment,
        verticalAlignment: widget.verticalAlignment,
        items: effectiveOptions,
        itemBuilder: (item) =>
            RadioButtonBuilder(item, buttonPosition: widget.buttonPosition),
      ),
    );
  }
}
```

### Environment

```markdown
- FlutterFlow version: v4.0 released December 16, 2023
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.109 (Official Build) (arm64)
- Operating system and version affected: macOS 14.1.2 (23B92)
```

**Comment by agreaves** [comment]
Thanks for this! Will be fixed next release!
