### ISSUE TITLE
[Custom Function] - Unable to test with FFUploadedFile argument in Custom Function

### ISSUE THREAD

**Issue by choonjia** [FlutterFlow/flutterflow-issues#2039]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Develop a custom function that takes an argument of type FFUploadedFile.
2. Encounter an issue in the Test Function Tab where a lengthy empty container is displayed (as depicted in the attached image), preventing the ability to test the function using the FFUploadedFile argument.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77397741/9f64e01e-6b20-4651-a7a0-cf2ddfe772a3)

When attempting to test another Custom Function, encounter an error message displayed in the Test Function Tab (as illustrated in the attached image).
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77397741/af870071-5e78-46a9-93b5-9f04703c2dc9)

### Expected Behavior

User should able to test with 'UploadedFile'/'FFUplaodedFile' argument in the system without affecting other Custom Functions.

### Steps to Reproduce

1. Define a custom function that accepts a parameter of type 'FFUploadedFile'.
2. Attempt to test the function designed for testing purposes but encounter difficulties in doing so.
3. Prior to incorporating the custom function with a FFUploadedFile type argument, test another existing custom function.
4. Conduct testing on the overall functionality, including the custom function with the FFUploadedFile type argument.

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Custom Code > Custom Functions

### Context

To test other working Custom Functions

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/77397741/50ebc5ed-ac6a-499e-872d-7c30d30bdcd5

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Android, IOS
- Browser name and version: Google Chrome Version 120.0.6099.110 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

**Comment by hariprasadms** [comment]
Hi, You are correct, FFUploadedFile as an argument does not worm in custom function tests. This is the current limitations.

**Comment by choonjia** [comment]
@hariprasadms The modification had an impact on the testing of other custom functions. Shouldn't the unintended consequence be classified as a bug?

**Comment by takashiff** [comment]
@choonjia Hello, thank you for the bug report. I apologize for the delay in response. This issue has been fixed and should be reflected in our next deploy. Unfortunately, we do not currently support Uploaded Files for Custom Function testing, but it should no longer prevent you from testing other Custom Functions. Thank you for your patience!
