### ISSUE TITLE
Cannot set local variable to null after 9 Dec 2022 update

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#204]
After the update on 9 Dec 2022, I noticed that UI sections on some pages are not updating anymore. When inspected found that we can no longer set local variables to null which makes the Clear value option pretty much useless. If it's an intentional feature there is no clear message that the variable value cannot be set to null. I want to be able to set a variable to null.

## Expected behavior (required)
The local variable should be set to null(false if bool) on clear value action. I want to be able to set a variable to null.

## Current behavior (required)
the local variable remains unchanged after clear value action.

## To Reproduce (required)

1. Create any non-bool local variable
2. use it for show/hide(value is set condition) or document create update
3. set some value on the variable
4. now try to "Clear Value" of that local variable
5. observe, the UI remains unchanged or created/updated doc's value field is not set to null.

### Bug Report Code

Updated Code in app_state.dart file causing this issue.

    DocumentReference? _activity;
    DocumentReference? get activity => _activity;
    set activity(DocumentReference? _value) {
    notifyListeners();
    // this line prevent null value update
    if (_value == null) {
      return;
    }
    _activity = _value;
    }

## Context (required)

cases where I am facing issues:

- If the variable is set show/hide a field.
- Pass variable value to Document creation/update so if the variable is null the field is not added and no need to add checks if the value is null. This especially comes in handy when there can be multiple such fields hence don't need to use multiple checks.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by Pepino-GR** [comment]
Hi Shubham-VE,

it seems to be fixed in version December 10, 2022

**Comment by wenkaifan0720** [comment]
Hi @Pepino-GR. If this has been fixed, could you close this issue?
