### ISSUE TITLE
API key throwing 403 authorization error

### ISSUE THREAD

**Issue by Hitisha27** [FlutterFlow/flutterflow-issues#2040]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to call the api from the flutter-flow but it is giving the 403 error and returning the null value . and all of the files is defined in the firebase.

### Expected Behavior

need to produce the data from firebase to flutterflow with the help of the api key

### Steps to Reproduce

1. created the firbase account
2. connected firebase with flutterflow
3. defined the database json files in firebase
4. defined the api key in the flutterflow
5. not getting the response 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/luItJpbwF+rXIL+4xpwMxQUQ5a50rlu1FGAscIqLkEZk+OcnuaXdeZ7Wre25IHlajrH4FwvCPieP9Du1fOQSBbYN607h+SBXyYGWVM4yJCbm8YkBRGcRRIHKzy7uFhxQkHLZtWkIt72GHcq3qNleeY8aSfxBlZ7vfcPo=

### Context

trying to get the data from the firebase that is defined there with the help of the api 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/128101146/9de194c1-1bef-4e1d-9728-7d51e564286d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/128101146/83640d77-8826-49b1-a8de-5805711c6eb0)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: web
- Browser name and version: chrome 107.0.5304.110
- Operating system and version affected: windows 11
```

**Comment by hariprasadms** [comment]
Hi, I have look at the project, I can see that the endpoint returning null is not a valid API endpoint. If you haven't already noticed this, please verify and ensure that the endpoint you are trying to access works outside of FlutterFlow.
