### ISSUE TITLE
Problem when getting to save data type in double field

### ISSUE THREAD

**Issue by fredicabral** [FlutterFlow/flutterflow-issues#2041]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When making a call to an api call to save the values ​​in the data type below:

The percentage field that is defined as double, but in the api call the value received is int is giving an error.

**(type 'int' is not a subtype of type 'double' in type cast)**

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/108d5508-8982-477a-b83d-f33d4c3a1f53/47b5a780-1e70-463f-a7de-4629006ae278?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMDhkNTUwOC04OTgyLTQ3N2EtYjgzZC1mMzNkNGMzYTFmNTMvNDdiNWE3ODAtMWU3MC00NjNmLWE3ZGUtNDYyOTAwNmFlMjc4IiwiaWF0IjoxNzA3MTQwMjMwLCJleHAiOjMzMjc3NzAwMjMwfQ.6y8agju5SJNQE_EqomtV7LIWN1Q5bFHnai-TG-dDmn8)

Made the calling action and defined a conditional that when the value is different from 0 it has the get and if it is equal to zero it has the value 0.00

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/906a27c0-0403-4b2d-b9c6-34045b86cd37/74600b3d-59f5-429a-b74f-feb2db3630d9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MDZhMjdjMC0wNDAzLTRiMmQtYjljNi0zNDA0NWI4NmNkMzcvNzQ2MDBiM2QtNTlmNS00MjlhLWI3NGYtZmViMmRiMzYzMGQ5IiwiaWF0IjoxNzA3MTQwMjMwLCJleHAiOjMzMjc3NzAwMjMwfQ.MsU4-CWPmwXlyYK1FsVfg4LhcAaehEd00lRwexEX-cU)

It's strange that in Run Test mode the problem does not only appear when compiling or exporting the code, this problem is occurring after the last Flutterflow update

### Expected Behavior

When using a conditional to transform the value from a string, integer to double should be possible using a function or by the conditional itself

### Steps to Reproduce

Create an api get call with an integer value, and in flutterflow create a datatype with the value double. Create a get action from the api call and use a function converting the received value to double or a conditional using code expression

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

code api

### Context

The problem generated was obtaining the data for the application, which has the functionality to create a sales order, and it is necessary to receive data on payment terms, customers and products that contain double fields

### Visual documentation

I created a post in the community and there are some conversations with the moderator who can help resolve the bug

Link: [https://community.flutterflow.io/database-and-apis/post/problem-when-getting-to-save-data-type-in-double-field-5j9j7e1xABFrqSZ](https://community.flutterflow.io/database-and-apis/post/problem-when-getting-to-save-data-type-in-double-field-5j9j7e1xABFrqSZ)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 released December 16, 2023
- Platform: Web
- Browser name and version: Chrome 120.0.6099.110
- Operating system and version affected: Desktop and Mobile
```

**Comment by hariprasadms** [comment]
Hi @fredicabral - Thanks for submitting the issue. I can confirm that this is not bug in the feature. It is working as expected. Its a type mis match error in run time. Try changing datatype value from double and integer and see how it works. However, you got custom code to update the api response values and use as you need int he UI. I hope it can help you.

**Comment by fredicabral** [comment]
Hi @victoriahuang1 @hariprasadms 

After the last update, the field format was made available in the call api, defining the field as double worked to insert the data!
Thank you very much
