### ISSUE TITLE
Adding an Auth flow to project is NOT creating the necessary Firebase collections

### ISSUE THREAD

**Issue by bizignite** [FlutterFlow/flutterflow-issues#2045]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not creating necessary Firebase collections

### Expected Behavior

Should add necessary Firebase collections

### Steps to Reproduce

1. Create project
2. Add flow to project > "simple authentication" Auth Flow (2 pages, 3 components, 2 collections)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz8rlz4lgocgB0M/ccO16hQIgQ0QnU7gnlO1ucx4Yfe7nEJk2OuPeZUNKTte9eH5AHU2kkn8y0e+Lic7DEfYrBz+bR4R70JVAEw/vXT6teJiqDLmSdHJ7M55jI1Sx0rW3swpNNrFvR2Qs2WCTNa3qNleeY8aSfxBlZ7vfcPo=

### Context

Affected: having to manually create collections and fields that are supposed to be auto created by adding Flow
Accomplish: adding Flow with built-in Firebase collections

### Visual documentation

![Screenshot 2023-12-21 134411](https://github.com/FlutterFlow/flutterflow-issues/assets/149336151/0bb677ee-7f1f-4522-af37-6f7fe12078ce)
![Screenshot 2023-12-21 134704](https://github.com/FlutterFlow/flutterflow-issues/assets/149336151/7a11967a-d897-4849-871c-8aae902617eb)
![Screenshot 2023-12-21 134721](https://github.com/FlutterFlow/flutterflow-issues/assets/149336151/a1a9c2cd-b3dc-43a5-b7a8-400bd6e82bb4)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version: Google Chrome
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @bizignite - Thanks for submitting the issue. I can reproduce it. Thanks

**Comment by sbis04** [comment]
This should be fixed in the next update!
