### ISSUE TITLE
App not running after launching the test mode 

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#2048]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It been three weeks now, launching the project in the test mode and not running.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/89715d5f-8f08-48a7-8117-bc9eb545d3b2/5491a377-80f8-40f5-b104-ea86601f7532?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84OTcxNWQ1Zi04ZjA4LTQ4YTctODExNy1iYzllYjU0NWQzYjIvNTQ5MWEzNzctODBmOC00MGY1LWIxMDQtZWE4NjYwMWY3NTMyIiwiaWF0IjoxNzA3MTQxOTc3LCJleHAiOjMzMjc3NzAxOTc3fQ.CssQIgzlDYU566Hz2xjbZ6qQuyGaDNdWhfCU2RmDjOc "=1680x")

### Expected Behavior

We except to continue building in the project after the MVP live version to continue the updates in the app.

### Steps to Reproduce

Project Fails to launching the app in the test mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESj/KAvJdgoupK17rAdMJQhQIgQ0QnU7gnlO1ucx4gGJzxBKQMYsnBPkNKT7yFfQtiHlSjjXEC7vSPuIf9G8AECzWVGqJF0JVATQ3NXkmQR4ixEKuCSn9tEZ1MfRGM35jUvyJ/D/h0Wi0n20+hNa3qNleeY8aSfxBlZ7vfcPo=

### Context

It was before working before by May 2023 as last progress and now I'm stuck to launch the app in the test mode.

### Visual documentation

* Project had any issues as you can see

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c9b3bdb6-52f1-4215-ab23-880ddabdde81/3b2559e4-2a70-442d-9475-d458f8d8b214?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jOWIzYmRiNi01MmYxLTQyMTUtYWIyMy04ODBkZGFiZGRlODEvM2IyNTU5ZTQtMmE3MC00NDJkLTk0NzUtZDQ1OGY4ZDhiMjE0IiwiaWF0IjoxNzA3MTQxOTc3LCJleHAiOjMzMjc3NzAxOTc3fQ.2auT9g0cPtqcUIHsOpZva0paFxXRB-Dg1kWAYRu2YoQ "=1679x")

* After Run Mode:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/135ee4df-999c-4f8d-a119-137e7d409a31/2fa254c2-8329-429b-bd2d-6eb9c6376fbf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMzVlZTRkZi05OTljLTRmOGQtYTExOS0xMzdlN2Q0MDlhMzEvMmZhMjU0YzItODMyOS00MjliLWJkMmQtNmViOWM2Mzc2ZmJmIiwiaWF0IjoxNzA3MTQxOTc3LCJleHAiOjMzMjc3NzAxOTc3fQ.8euXL6HowlcwwHdEZdCc6OLup2L8yF48wvobsFx4XLE "=1677x")

* After Test Mode:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e457d51c-575f-4de8-a5a0-ab65576c4676/5cddd672-044d-455b-999f-ba2b6df51819?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNDU3ZDUxYy01NzVmLTRkZTgtYTVhMC1hYjY1NTc2YzQ2NzYvNWNkZGQ2NzItMDQ0ZC00NTViLTk5OWYtYmEyYjZkZjUxODE5IiwiaWF0IjoxNzA3MTQxOTc3LCJleHAiOjMzMjc3NzAxOTc3fQ.QpFpXzo3Y-wbmPVOatPWctsURo5vXCv59w8\_-rJGxz0 "=1680x")

* Here we have an issue showing in the Console:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c8daa7cf-3789-4274-b041-0e71890c79be/7915a144-ac5e-4ed6-9030-b3b7edf062b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jOGRhYTdjZi0zNzg5LTQyNzQtYjA0MS0wZTcxODkwYzc5YmUvNzkxNWExNDQtYWM1ZS00ZWQ2LTkwMzAtYjNiN2VkZjA2MmIyIiwiaWF0IjoxNzA3MTQxOTc3LCJleHAiOjMzMjc3NzAxOTc3fQ.d6MPc83flYsMCdBE7XEuOQlSplx6DKmH50T7GZJXIM4 "=597x")

For that I disabled the Push Notifications:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7dc5b319-a2a9-4716-83e4-8efa80876e0e/28338307-735b-4482-b37b-6b78283bb635?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZGM1YjMxOS1hMmE5LTQ3MTYtODNlNC04ZWZhODA4NzZlMGUvMjgzMzgzMDctNzM1Yi00NDgyLWIzN2ItNmI3ODI4M2JiNjM1IiwiaWF0IjoxNzA3MTQxOTc3LCJleHAiOjMzMjc3NzAxOTc3fQ.W6EwUHiVL57FhNU2rrOHJqD0x65mf4msGQ_LvqhVhNM "=1327x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: FlutterFlow v4.0 released December 21, 2023
- Platform: Web
- Browser name and version: Chrome 119
- Operating system and version affected: macOS Sonoma Beta 3
```

**Comment by ImadBouirmane** [comment]
One thing mention here, I already talked with your FlutterFlow Support Team David and I did what he said to me and even that still the issue, and what we did is this:
- I removed the local_notifications package after we saw that the package don't support Web!
- I added app.flutterflow.Io to Authorised Domains on Firebase Auth and also another link showed on the console (ff-debug-service-frontend-ygxkweukma-uc.a. run.app).

**Comment by hariprasadms** [comment]
Hi, This is the error message I see while running your project code in local. FirebaseMessaging package can't be used because of its permission requirements. In does not work in test run mode. Remove custom actions related this package and try again please. 

<img width="1181" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6c034802-c15c-4813-a437-d5fb85079f60">

**Comment by ImadBouirmane** [comment]
You're right @hariprasadms 
I removed the Custom Action from the main.dart file in FF and then it's work, second time problems with custom code especially the actions part.
To let you know it was work fine before with the same config, if you have any helpful informations let me know.
