### ISSUE TITLE
Test mode broken stuck in never ending loops

### ISSUE THREAD

**Issue by technoclectic** [FlutterFlow/flutterflow-issues#2052]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to test my project using Chrome with no existing sessions open or live I get the following:

1. Hover test (lightning bolt in builder) says "test session expires in -5591 minutes"
2. Click test button red warning appears saying only 1 session at a time.
3. Click open session
4. New tab appears that says Service Unavailable and has Session about to expire green box at bottom
5. Click green to relaunch session
6. Success.

Scenario 2

1. Session within 3 minutes of expiration green Session about to expire box shows.
2. Click green box to relaunch
3. Fails due to FlutterFlow thinking I have an existing session open.
4. Must wait for existing session to expire to relaunch

I have cleared cookies, cache, restarted Chrome and the computer. Nothing working.

![Screenshot 2023-12-23 at 11 41 34](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/183f8b53-4073-4fd7-90b1-ef75dd555a93/f1cffa06-9c1e-4869-b1d7-92af0c40f641?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xODNmOGI1My00MDczLTRmZDctOTBiMS1lZjc1ZGQ1NTVhOTMvZjFjZmZhMDYtOWMxZS00ODY5LWIxZDctOTJhZjBjNDBmNjQxIiwiaWF0IjoxNzA3MTQxOTgwLCJleHAiOjMzMjc3NzAxOTgwfQ.bByKFBMmB1DfxhE0rfWBYCWE1qmA2wGgJMJTp_5zpWw "=534x")

![Screenshot 2023-12-23 at 11 41 48](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8369c960-73aa-4c38-89dc-c8d41985aab4/c3961ced-2c55-40ff-8b6b-a62ac47968e7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MzY5Yzk2MC03M2FhLTRjMzgtODlkYy1jOGQ0MTk4NWFhYjQvYzM5NjFjZWQtMmM1NS00MGZmLThiNmItYTYyYWM0Nzk2OGU3IiwiaWF0IjoxNzA3MTQxOTgwLCJleHAiOjMzMjc3NzAxOTgwfQ.NMd8csw-utm5V5fJYoWvZW7AZ-oFI8sN9ukGDcGukw8 "=671x")

![Screenshot 2023-12-23 at 11 42 16](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b5992cf4-e0c3-47c6-b603-6acb2c17992b/7fd12592-d4fa-43f1-a0a9-8c76f7fbb035?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNTk5MmNmNC1lMGMzLTQ3YzYtYjYwMy02YWNiMmMxNzk5MmIvN2ZkMTI1OTItZDRmYS00M2YxLWEwYTktOGM3NmY3ZmJiMDM1IiwiaWF0IjoxNzA3MTQxOTgwLCJleHAiOjMzMjc3NzAxOTgwfQ.VU7WbvKPyXDNMoPkUpSTSqLRZ148z_YtpjApxSKKBz8 "=1840x")

### Expected Behavior

When test is hovered with no active session should show no active session.
No red box should show in scenario 1
Launching new test session by clicking red dialog shouldn't show Service Unavailable.
Clicking green dialog should reload test session with new 30 min clock.

### Steps to Reproduce

1. Hover test (lightning bolt in builder) says "test session expires in -5591 minutes"
2. Click test button red warning appears saying only 1 session at a time.
3. Click open session
4. New tab appears that says Service Unavailable and has Session about to expire green box at bottom
5. Click green to relaunch session
6. Success.

Scenario 2

1. Session within 3 minutes of expiration green Session about to expire box shows.
2. Click green box to relaunch
3. Fails due to FlutterFlow thinking I have an existing session open.
4. Must wait for existing session to expire to relaunch

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClefqwItOpbxJ7qX2bsEw+SoUKVAjRYE70e5HdxEaN5PND+x/esnRQFJuZ9Ordgl6MWaWpHwd+eDVm9z1VvAFPT6abtl71blQFhXNRmGVV8WsOqWedkduGshYCWbC1MGR2BZCGMhuck483FOYAOu/HzLqGLr6PFcBBeaZKZDXvgfuQ0SLb3kNh1JWeC/v

### Context

This has slowed my development effort by at least 50%. I have to Launch 4 new tabs to get a new test session.

### Visual documentation

![Screenshot 2023-12-23 at 11 41 34](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/84e53846-0238-4bba-8f57-6131dd7f0233/63163416-b83f-426c-9b32-424dc44368af?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NGU1Mzg0Ni0wMjM4LTRiYmEtOGY1Ny02MTMxZGQ3ZjAyMzMvNjMxNjM0MTYtYjgzZi00MjZjLTliMzItNDI0ZGM0NDM2OGFmIiwiaWF0IjoxNzA3MTQxOTgwLCJleHAiOjMzMjc3NzAxOTgwfQ.At2jJEdsU2WUOfJ7R8QQuq-QG0vyQYOoeAHHc_Ex--c "=534x")

![Screenshot 2023-12-23 at 11 41 48](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4bd597b3-8f82-46a4-b201-aa951dbbd60d/8f8ccee2-10d6-4cac-a485-8e233e88194a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YmQ1OTdiMy04ZjgyLTQ2YTQtYjIwMS1hYTk1MWRiYmQ2MGQvOGY4Y2NlZTItMTBkNi00Y2FjLWE0ODUtOGUyMzNlODgxOTRhIiwiaWF0IjoxNzA3MTQxOTgwLCJleHAiOjMzMjc3NzAxOTgwfQ.uo-ZI8WePhKVF1qNabnkEwc55YOM8Y3sJ9uTtvs7EEc "=671x")

![Screenshot 2023-12-23 at 11 42 16](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdda3c93-bb38-418f-81e5-3e9e8f8d7edf/d21c1b42-353b-4cda-9aa8-bf98ba5f9b6b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGRhM2M5My1iYjM4LTQxOGYtODFlNS0zZTllOGY4ZDdlZGYvZDIxYzFiNDItMzUzYi00Y2RhLTlhYTgtYmY5OGJhNWY5YjZiIiwiaWF0IjoxNzA3MTQxOTgwLCJleHAiOjMzMjc3NzAxOTgwfQ.XfWZUl6XM-wo4Tg2DatQtTkSoli5Sa7YGNNLmPDUk8o "=1840x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Chrome 120.0.6099.71
- Operating system and version affected: Sonoma 14.3
```

**Comment by hariprasadms** [comment]
Hi @technoclectic - Thanks for submitting the issue. I can see the below error when running your project in test mode. I hope that the loading issue in test mode has already been resolved at your end. If you can fix below issue, your project should run fine with no issues.

If test mode loading issue already resolved. Please close the issue. Thanks

<img width="1507" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/e85e7a48-b41c-4ba2-bb6c-321c557d82f6">

**Comment by technoclectic** [comment]
Hi Hari,
That error wasn't occurring before the latest update in the browser. This issue is still open. CounterStatus is an enum and values are set accordingly. Did something about that change? It's not reflected in the editor as an error when I set the values. Also it looks like the timer has changed as well according to the error message, now accepting a decimal value instead of an integer? I'm confused as to what caused these errors. I will say that the reset timer to specific time action has been giving me problems all along. I haven't made any significant changes to the project since submitting the initial bug. Please advise.

**Comment by hariprasadms** [comment]
Hi @technoclectic - Given that the initial problem of the broken test mode and the never-ending build loop has been resolved, please close the existing issue. Feel free to open a new one specifically addressing the latest issue you are currently facing. This will help in maintaining a clear and organised tracking of the ongoing issue. Thank you.
