### ISSUE TITLE
Webview can not opening any URL other than https://flutter.dev

### ISSUE THREAD

**Issue by priteshsisale** [FlutterFlow/flutterflow-issues#2053]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to add my Google site in Webview bit it shows refused to connect. Also normal [google.com](http://google.com) also not working
Example: [https://sites.google.com/view/pssfamily/home](url)

### Expected Behavior

I want my flutter Webview should open my website.

### Steps to Reproduce

1. create new page
2. add web view widget
3. change website url
4. and run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl/LfxItIsdtK0L6JY/l4njsUG0ccTJMZjtZFewgjF774ELQuP8nSYlVuZ72zaH9YM1WjrH4GpODMjYXhOPYpHxWtfKp9ys1ybxPPbEGuMJCtPoeaVnN6BptVBWay3JjQmhRBBM50WGQ4wU6EFuuXHj6Cf9qOYwx5e6fDbOY=

### Context

I want to run Google sites in my Webview

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/41caf000-d38d-476b-adbb-abde6996760f/807ca1bd-20c6-4272-98b1-3cd44e9191ba?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MWNhZjAwMC1kMzhkLTQ3NmItYWRiYi1hYmRlNjk5Njc2MGYvODA3Y2ExYmQtMjBjNi00MjcyLTk4YjEtM2NkNDRlOTE5MWJhIiwiaWF0IjoxNzA3MTgxNjg1LCJleHAiOjMzMjc3NzQxNjg1fQ.AkYldYrpZMERzH48G4SpvRNpzpa4uHaGs0XYI8z_0xY)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 (3.13.7)
- Platform: Web
- Browser name and version: Google chrome - Version 120.0.6099.129 (Official Build) (64-bit)
- Operating system and version affected: Web
```

**Comment by hariprasadms** [comment]
Hi @priteshsisale - Thanks for submitting the issue. I can reproduce the issue. Thanks

**Comment by takashiff** [comment]
@priteshsisale Hello, thank you for your bug report. Some websites do not support embedding, so in order to bypass this, you may need to enable the "Bypass Domain Restrictions" setting. If loading a custom site from Google sites, I believe there should be an option when setting up your website to allow embedding as well. Please let me know if this solves your issue. Thanks

**Comment by priteshsisale** [comment]
@takashiff website created on Google Sites supports embedding, also I have already enabled the "Bypass Domain Restrictions" setting it still won't work.

**Comment by takashiff** [comment]
Hi @priteshsisale, can you ensure you have the required CNAME record in your domain configuration on your Google site? Thanks

**Comment by hariprasadms** [comment]
@priteshsisale - Are you still experiencing the issue ? If it is resolved, please close the issue. Thanks
