### ISSUE TITLE
Custom Functions Compilation error: Compiling with sound null safety

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#2056]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been having this issue since last week whenever I create a function or test my previous functions I get sound null safety error. Even with simple functions, this is coming up. I already declared my variable with const, final etc but the issue persists. And due to this I also can't Push my repo to Git to troubleshoot further. Only when I remove the functions I get to push to Repository my project.

### Expected Behavior

Able to test the function.
Able to Run/Test Mode the App.
Able to Push my App to Github Repo

### Steps to Reproduce

1. Create a function
2. Test the function.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olOfqwIt2pbxY+KqJdfpV+CQWNnojR787i8pBZywgfZzzBLN/fPfQP1htTsCqd2NmOWKmp140+vT6ivLDV+0CIU6cRb5E/qpQEwvhUlmuM5OTF7rtPXdSP95mN3aE4barvxUmKfVpZV4i3TquGuSidBfZJYzRDFQ8Sq/LZO4=

### Context

Not able to Push to Repo, Test/Run the App or Test functions due to functions issue. No errors shown

### Visual documentation

![Screenshot 2023-12-25 at 10 20 38 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f4cc8354-7897-41ad-bc37-5114c66af460/a887bead-c27e-4b7f-b4b8-b73e84b8ef85?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNGNjODM1NC03ODk3LTQxYWQtYmMzNy01MTE0YzY2YWY0NjAvYTg4N2JlYWQtYzI3ZS00YjdmLWI0YjgtYjczZTg0YjhlZjg1IiwiaWF0IjoxNzA3MTQxOTgxLCJleHAiOjMzMjc3NzAxOTgxfQ.DJ4wv_JN0dAQn8znhn0mqRLQ7UK5UJlUch2aMoHgFNI "=1608x")

![Screenshot 2023-12-25 at 11 36 02 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fae0c4eb-017a-49cb-ab79-29759c5051df/ffa6befa-7172-4db8-953b-abfaa97d2901?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYWUwYzRlYi0wMTdhLTQ5Y2ItYWI3OS0yOTc1OWM1MDUxZGYvZmZhNmJlZmEtNzE3Mi00ZGI4LTk1M2ItYWJmYWE5N2QyOTAxIiwiaWF0IjoxNzA3MTQxOTgxLCJleHAiOjMzMjc3NzAxOTgxfQ.SSFm5PUh7sfJ0VfkMjehgl617RnQxlX0ZA8VNp91hHk "=1522x")

![Screenshot 2023-12-25 at 11 39 32 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/470dceb0-0ad0-4eb1-b811-373eb719e611/cb60aab3-cb83-42ec-813a-7687ab7ee6ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NzBkY2ViMC0wYWQwLTRlYjEtYjgxMS0zNzNlYjcxOWU2MTEvY2I2MGFhYjMtY2I4My00MmVjLTgxM2EtNzY4N2FiN2VlNmNlIiwiaWF0IjoxNzA3MTQxOTgxLCJleHAiOjMzMjc3NzAxOTgxfQ.jhIRyneFnfFsnTtLJRoTjQ3_vyPQAW0OOB0TSSZ7ULw "=1505x")

### Additional Info

None.

### Environment

```
- FlutterFlow version: v4.0 released December 23, 2023
- Platform: Web
- Browser name and version: Web
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hi @Dev-Muhammad-Junaid - There was a null value set in data type - dailyRequest for an integer filed. Once I cleared it, I was able to run the app in test mode with no error.  I hope you have noticed it. check and try again. Thanks

<img width="1078" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a9093928-a1b5-438b-ad54-10b97a4bf091">


<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d9cf3d20-d05d-4977-b84b-ebfe1ec3b661">

**Comment by hariprasadms** [comment]
Its glad to see your issue is resolved. Looks like there are some edge case bugs around data type and its default values defined. I will have a look at them. Thanks for your contributions.

**Comment by hariprasadms** [comment]
Please close the issue if you think your issue is resolved. Thanks

**Comment by Dev-Muhammad-Junaid** [comment]
Got it. Thanks
