### ISSUE TITLE
Package dependencies update

### ISSUE THREAD

**Issue by nicorne** [FlutterFlow/flutterflow-issues#2057]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to use a web3 wallet authentification package which uses the url-launcher package.

The problem:
url-launcher is deprecated on Flutterflow. 

I am unable to achieve web3 wallet authentication because of that.

__

### Expected Behavior

It would work with the latest version of the url-launcher package.

### Steps to Reproduce

1. Install wallet connect (https://docs.walletconnect.com/web3modal/flutter/installation)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not_specific_to_a_widget

### Context

I am unable to progress on my app without web3 wallet authentification.

### Visual documentation

-

### Additional Info

When do you plan to update Flutterflow url-launcher next? How often are these dependencies updated?

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Macos
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by nicorne** [comment]
Fairly simple question:

When do you plan to update Flutterflow url-launcher next? How often are these dependencies updated?

Thanks

**Comment by takashiff** [comment]
Hello @nicorne, unfortunately we are currently unable to provide an ETA on an upgrade. However, a potential workaround is to create a blank custom action, and add the `url_launcher` dependency with the version you need, and include the action somewhere on the page.

**Comment by nicorne** [comment]
We tried using custom actions and got this error:
<img width="981" alt="Screenshot 2024-01-09 at 14 14 26" src="https://github.com/FlutterFlow/flutterflow-issues/assets/45595586/33b3f7b6-1330-4b4d-8cbb-ba36ab5ec5a2">

**Comment by takashiff** [comment]
Hi @nicorne, just wanted to follow up on this topic. Was the workaround able to work for you? Thanks

**Comment by nicorne** [comment]
It didn't work. we are not using flutter flow anymore
