### ISSUE TITLE
Varchar doesn't work in API call

### ISSUE THREAD

**Issue by yassirLio** [FlutterFlow/flutterflow-issues#2058]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

varchar with supabase not working in API call. 
The string variable in API call work only when text is short. I did some tests to confirm the bug:

- Standard supabase action with short text: it works.
- Standard supabase action with 1000 caracter: it works.

- API call to supabase with short text: it works.
- API call to supabase with 1000 caracter: it doesn't works.

### Expected Behavior

When:
- Declaration of the variable in supabase is "verchar"
- declaration in API call with supabase is "text"
- Variable with longer caracters (8000 as standard, 1000 in my case)

API call should record the data in subapase 

### Steps to Reproduce

When:
- Declaration of the variable in supabase is "verchar"
- declaration in API call with supabase is "text"
- Variable with longer caracters (8000 as standard, 1000 in my case)

API call should record the data in subapase 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfjM7l8cp2sbRG1oSJasBKqDs4C18cTIMziNZ+exUbfaL1BuwMZ87CXBdWTdzhaVNcMU6iin0dpcLsuN+SCvZfHy6YQb49+pNQFAL0e2iXWpCsDqqwWUB7J8dNGBWyy52RghMkOrdpZVY+3zmqN++Rd3fDBOu/Zwh9f6PHaOI=

### Context

I'm in the last phase of the mobile app development, this issue inn now blocking me

### Visual documentation

https://flutterflow.intercom-attachments-3.com/i/o/916598587/017f2792989114127cc0c0d6/20231222-1742-31.4525616.mp4?expires=1703534933&signature=4dd9565bc66f284ed22f4acf80f08e1618a0f7fc8bb4cfdaff7d229da4c5d441

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @yassirLio - Thank you for submitting the issue. I have tested it by making an API call with 2000 characters. The data retrieval was successful without any errors. 

When you say that it is not working, what specific error you are experiencing? Please add these detail.

**Comment by yassirLio** [comment]
Hello Hari, Thanks for the reply.

here below a record for the issue I'm facing. As explained before, the text don't record to supabase if it's long.

https://www.dropbox.com/scl/fi/go9ex2o71mf65xfa7sgjl/Recording-2023-12-29-215441.mp4?rlkey=jqpyuag8lzi39dbw7vnmgtp6g&dl=0


You're right, it works in the API test, but not in the live (when the text is text field maybe).

Regards.

**Comment by takashiff** [comment]
Hello @yassirLio, thank you for your bug report. I'm currently unable to reproduce the issue, even in a live version of an app. Could you paste the text that you are using for testing? Thanks

**Comment by yassirLio** [comment]
Hello,

THank you for your replay. The text is about a description that the user can write about themselves. Bellow a text that doesn't work., I generate from chatgpt. As per my anderstanding, the problem can come from the textfield :

Sophia, a woman of captivating grace and indomitable spirit, stands as a living tapestry woven from the threads of her diverse experiences and multifaceted personality. Her almond-shaped hazel eyes, shimmering with intelligence and kindness, hint at the depth of her soul. Framed by a cascade of chestnut waves, her hair dances with each step, embodying both strength and vulnerability.

Sophia's presence is magnetic, drawing people into her orbit with an effortless charm that belies a lifetime of learning and growth. A slender silhouette hints at her commitment to health and well-being, while her posture exudes confidence earned through challenges faced and conquered. Dressed in a fusion of classic elegance and contemporary flair, Sophia effortlessly blends timeless style with a modern edge.

In conversation, Sophia's voice resonates with warmth and authenticity, each word chosen with care and deliv

**Comment by takashiff** [comment]
Hi @yassirLio, I tried the same with the text you have provided, and with a TextField that contains a limit of 1000 characters, and I am still currently unable to reproduce it. Can you check if you encounter similar behavior in Postman? Thanks

**Comment by yassirLio** [comment]
Is there any specific requirement for the setting of the text field?

**Comment by takashiff** [comment]
@yassirLio I just used a regular TextField and set the maximum number of characters to 1000.

**Comment by takashiff** [comment]
Is it working without issue in Postman?

**Comment by takashiff** [comment]
Marking as closed due to inactivity. Feel free to follow up in this thread if the issue persists so that the ticket can be reopened.
