### ISSUE TITLE
FF project freeze when you go to thumbnail mode for pages

### ISSUE THREAD

**Issue by Niralempiric** [FlutterFlow/flutterflow-issues#2059]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FF project freeze when you go to thumbnail mode for pages
![Screenshot 2023-12-26 at 9 33 28 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/108325883/9f5d2650-e3f9-4cdf-b9cc-b26b0b16b226)

### Expected Behavior

it should work without any issue

### Steps to Reproduce

1. Open Project
2. Go to thumbnail mode for pages

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48zfHl8c12rtxE17r+Y8AxjiYWH1s7RoEo1utEFBE8J5zKB+wAYvf7P1FWTLy5TVY3f2CZvGcd7PfquITiUfVdIU2YboA/+atIbBXhRk+gV4yoCaWNfW1SPJ5NGH3C4JiFvSZQHNJ1LyUd2WeQfemvSgnDCZTAC0YnR/+bKdeK2SrDX1iXc2URm05KZDPz

### Context

when i try to click on thumbnail mode 
it freeze 

### Visual documentation

![Screenshot 2023-12-26 at 9 37 31 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/108325883/fe217ed4-ede8-41a2-ac51-d3a9890e422f)

### Environment

```markdown
- FlutterFlow version: 4.0 & Flutter 3.13.7
- Platform: Within FlutterFlow Editor
- Browser name and version: Brave v1.61.109
- Operating system and version affected: FlutterFlow Editor
```

**Comment by hariprasadms** [comment]
Hi @Niralempiric - We recommend to user Chrome as primary browser. In other types of browses, these kinds of glitches are expected as FF is not compatibility tested with other browsers. 

How above behaviour works in Chrome browser ?

**Comment by Niralempiric** [comment]
@hariprasadms @kevintonb 
Same in chrome i face same issue

**Comment by hariprasadms** [comment]
Hi @Niralempiric - I looked at your project and tested above steps in chrome. It looks fine and no issues. 
Can you share a quick video about the issue you are facing ?

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8da4e5e0-16ac-4243-8099-5d92079ac192
