### ISSUE TITLE
Error in custom code Dec 9 update

### ISSUE THREAD

**Issue by jerco2** [FlutterFlow/flutterflow-issues#206]
## Expected behavior (required)
retain code and be able to edit and fix.

## Current behavior (required)
resets code, can't edit and fix.

## To Reproduce (required)
1. Create custom function.
2. Add a String argument named let's say "data".
3. In the code body, input "return data" don't add a ";" at the end.
4. Test function.
5. Receives error, then go back to Function Code tab.

## Context (required)
difficult to work with custom code, you have to start all over again when you encountered an error.

## Screenshots / recordings
https://user-images.githubusercontent.com/87056920/206702667-0b90e034-9440-4185-9342-f67b08a0dbe9.mp4

## Your environment
* Version of FlutterFlow used: v3.0 December 9, 2022 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Google Chrome
* Operating system and version (desktop or mobile): Windows 10

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. We will deploy a fix later today.
