### ISSUE TITLE
FlutterFlow doesn't deploy Firestore subcollection indexes and resets them if I deploy them manually, breaking my subcollections queries

### ISSUE THREAD

**Issue by sabatage3** [FlutterFlow/flutterflow-issues#2060]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to execute a query on a subcollection using filters and ordering. However, when testing the project, I encounter a Firestore indexes error. The error message contains a link that, when opened, creates the necessary indexes in Firestore, resolving the issue.

The problem comes when I perform a different query with filters. FlutterFlow requires redeployment of Firestore indexes, but upon doing so, it resets the indexes I had just manually set using the link provided in the Firestore indexes error message. So, I find myself having to recreate the index in Firestore.

### Expected Behavior

FlutterFlow should request the deployment of indexes for subcollection queries in the same manner as it does for regular queries. Alternatively, it should refrain from resetting indexes that were not deployed by FlutterFlow

### Steps to Reproduce

1. Execute a query on a subcollection, using filters and ordering.
2. Check that FlutterFlow does not display a warning about outdated indexes.
3. Test the project and observe a red error message related to Firestore indexes.
4. Click on the link provided in the error message to generate the necessary indexes and resolve the error.
5. Create a new query on a different collection with different filters.
6. Redeploy the indexes as prompted by the FlutterFlow message indicating outdated indexes.
7. Notice that the query on the subcollection from step 1 once again produces an error related to indexes when testing the project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ck8nf34Z2xOFc+Kr2dvlVgiI5JUN/RYEWmO0bWQ0gJ5PND+x/esnRQFJuZ9OrdghIJFqkkTge/s7Sm9z1E/c4PTWYR4RjypZAUjrve3GVMs26CrmSf2huGshWCUDH5MKG3B0lGNt1c0IY70+IO9+/ExfbQpe2IlUaRfGaMZLXvgfuQ0SLb3kNh1JWeC/v

### Context

I'm attempting to execute a query on a subcollection, applying filters to count the number of documents created by a specific user in the last hour. However, I've encountered this indexes problem. As a temporary solution, I've decided to query all subcollections without filtering and ordering. Unfortunately, this approach eliminates the purpose of having subcollections.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/555f1485-6838-403c-bd68-c708616656b6/6b5c4e4d-ff11-4d56-ac17-13cfc424d112?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NTVmMTQ4NS02ODM4LTQwM2MtYmQ2OC1jNzA4NjE2NjU2YjYvNmI1YzRlNGQtZmYxMS00ZDU2LWFjMTctMTNjZmM0MjRkMTEyIiwiaWF0IjoxNzA3MTQyNDg4LCJleHAiOjMzMjc3NzAyNDg4fQ.W58rCeNtkA_fL49Sn48iXsSjFyWOxlhl7ysOGMwZUus)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0 (released Dec 22, 2023)
- Platform: Web
- Browser name and version: Brave
- Operating system and version affected: Windows
```

**Comment by sabatage3** [comment]
Any updates here?

**Comment by AvantN** [comment]
I've been watching this since my post is right above yours. Looks like they don't care

**Comment by sabatage3** [comment]
Ikr! I’ve been watching how they respond to everyone else and ignore this issue, is frustrating

**Comment by sabatage3** [comment]
@kevintonb please help it's been more than a week

**Comment by sabatage3** [comment]
Omg @kevintonb @sbis04 please i need help, why nobody cares 😿

**Comment by sabatage3** [comment]
@sbis04 @kevintonb any updates after 3 weeks?

**Comment by nvimalraj** [comment]
I have the same issue as well, seems to have started sometime since December 2023, prior to that the indexes even if it is added via run-time, they stay intact. And yes this issue is specific to subcollection.

**Comment by takashiff** [comment]
Hi @sabatage3, I apologize for the delayed response. After following the steps to reproduce the issue, it looks like the indexes are being deployed properly, but is just taking some time to build. If you take a look at the `Indexes` tab on your Firebase project, you can see the status of each index. As long as the specified indexes are set as `Enabled`, the queries will function properly. Please let me know if this resolves your issue. Thank you for your patience.
<img width="1473" alt="Screenshot 2024-03-14 at 4 57 45 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134453477/d0e46f41-9812-4a7a-ae1d-792bdfc5c4a6">

**Comment by sabatage3** [comment]
Hi @takashiff I'm not able to reproduce this error again, we can close this issue for now, I'll take a look at that tab you mentioned next time I get that red error in test mode, thank you for your help

**Comment by takashiff** [comment]
@sabatage3 I'm glad to hear this issue has been resolved for you, thank you for your patience and continued support!
