### ISSUE TITLE
Action not working when two filters are present involving the app state value

### ISSUE THREAD

**Issue by AvantN** [FlutterFlow/flutterflow-issues#2061]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

An action to query a collection with a filter that pulls a document from the firestore database randomly will work correctly alone. However, it will crash when added with a second filter that requires the randomized document number to not be equal to the document number in the app state. An error will occur randomly after about 2-4 attempts with an "Unexpected Null value", which I believe is due to a random number generated that does not meet the second filter's requirement (though it is still possible to meet both filter requirements). Clearing the app state variable list will temporarily resolve it, but as integers are added to the app state list, it will crash again.

### Expected Behavior

Having a filter for a random document pulled from the collection database should also include the requirement of the second filter, and both filters should be applied without issues. When I have integers added into the app state variable list, it should not crash until all possible integers are exhausted rather than just 2-4 queries (sometimes the first one will crash it). There should be no null values generated to crash the app until all possible integers are within the app state list.

### Steps to Reproduce

1. create database in firestore with 10 documents each with a unique integer field from 1-10.
2. create a data schema of an integer data type, then create an app state variable datastruct list using integers that is persisted
3. create a button that queries the collection for a random document by searching the integer field for a random integer between 1-10 (using a filter) and then create a second filter within the same query that the integer must not be within the app state list. The final action of the button can go to a second page (Page 2) and send over the parameter from the retrieved document (maybe text of what the numbered document is, such as "document # 3" if it was given a field value of 3). 
4. On the second page, have a button with an action that updates the app state by adding to the app state list the current document number (from the parameter), and then have this button navigate back to the first page.
You can create another query the collection with the same filter 1 that randomizes the document pulled using the document number equal to random integer. then create filter 2 as such (collection field name: 'document number field', Relation: Not In, Value pulls "Item in List" in the app state variable list
Going back and forth between the two pages should add a new integer into the app state, removing that numbered document from the possible documents pulled randomly. However, hitting the button a few times will instead crash it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lcjfz4VNtbxJ7qX6YMEwnmEsQ187RoEVi+5EVg88J5zKB+wAYvf7P1FWTLyqYXNmMVn8kmIxxvfquNjlEMJcG0+bR6U7zpZiTw3zWkWRVLqSDKjgfW1QTNxRJn653KeJngpdKuhadEIZ6l+uOdnLZA3YCb7OC1URR8ibKdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to make a flash card app that will generate random cards from the database but has the feature of removing learned cards. This is the feature that is supposed to remove the learned cards from the card pool, however it is generating errors.

### Visual documentation

![error code](https://github.com/FlutterFlow/flutterflow-issues/assets/154860475/9e643528-6cf6-400e-a685-494503f14c03)

### Additional Info

I don't know if you can access with the ID, but this is the crash reproduce app:

Project: Crash reproduce
Project ID: crash-reproduce-98bjl0

### Environment

```markdown
- FlutterFlow version: 4.0 - Flutter 3.13.7
- Platform: Mobile
- Browser name and version: Google Chrome Version 120.0.6099.129 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by AvantN** [comment]
I don't know if you can access with the ID, but this is the crash reproduce app:

Project: Crash reproduce
Project ID: crash-reproduce-98bjl0

**Comment by AvantN** [comment]
The more I play around with it, I think the crashes only happen when there is something in the app state variable list

**Comment by AvantN** [comment]
@aemelyanovff can you please help me? no one has done anything yet and this is the last thing I need to get the app working from what I can tell...

**Comment by aemelyanovff** [comment]
@AvantN Most likely there are no documents matching the query, while the page assumes that there is one. If it's the case, it must be handled in the project. I don't think it's a bug in FlutterFlow.

If you need further assistance, please reach out to FlutterFlow support of ask https://community.flutterflow.io.
