### ISSUE TITLE
Can't install Progressive Web App

### ISSUE THREAD

**Issue by gentleVirus** [FlutterFlow/flutterflow-issues#2069]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't install Progressive Web App anymore. 

It doesn't show the install icon or the install button in the browser submenu.
And as far as I know the "add a link to home screen" button should say "install" for the web app to be installed.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/141834860/c7e044e2-fe8b-416c-9109-3baf9956a7cc)
![0](https://github.com/FlutterFlow/flutterflow-issues/assets/141834860/94819a31-1e07-4133-acd1-6d6847daa7c3)

### Expected Behavior

I should be able to install the PWA.

Google Guide:
https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DAndroid&oco=0

### Steps to Reproduce

1. Open FlutterFlow Project
2. Open Settings and Integrations
3. Oben the Web Publish Tab
4. Turn on the "Enable PWA" switch
5. Click the "Publish" Button and wait to for the Web Page to deploy
6. Open the Web Page and open the submenu (three dots at the top right corner)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejMrlvJNPj7xH+c/+c/lvrwMwJ0QlUIInj+0bWRMhfevqPJoQdc/OQE5LYteCYXNmGFaJgmUDw+jGivHTCMEBISeBQKI91b5XQQvvWnyRacWUDc6BOUYmN9hgCn3G36anhBV4ItdoSlo/3E+QfvCrG3qCf9qOYwx5e6fDbOY=

### Context

It worked before without any problems. I only republished with minor visual changes, which I already tried to revert.
I believe it stopped working after the December 16th FutterFlow Update.

Tested several Android Smartphone/Tablets and Windows Desktop devices (With Chrome and Firefox browser). Apple seems to work.

### Visual documentation

...

### Additional Info

I talked with the FlutterFlow support about the problem. We came to the conclusion that the Web Manifest.json might be the problem.

The Chrome Console reports the Following for the Web Page which should be able to install the PWA:
Manifest: property 'start_url' ignored, should be same origin as document.

The Web Manifest.json says for the start_url line:
start_url: "."

I assume the start_url is supposed to be the startpage/auth_page.

**If that's the reason causing the PWA not to install and the default Web Manifest is created by FlutterFlow, this should be easily fixed by changing the "." to a variable for the individual FlutterFlow User's Web Page URL.**

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 22, 2023
Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.116
- Operating system and version affected: Android 14
```

**Comment by gentleVirus** [comment]
One thing that could be done on the same run: It would be nice if the Web Manifest.json Variables  "background_color" & "theme_color" adapt to the flutterflow user's theme. Currently it using a blue tone (#0175C2) by default for both variables, which always shows when opening the the app via browser or PWA.

**Comment by takashiff** [comment]
Hello @gentleVirus, thank you for your bug report. This issue has been fixed and should be reflected within the next couple of weeks. In regards to your most recent comment, I have put in a feature request internally to allow for customizing the `manifest.json`. Thank you for your patience!

**Comment by Red-right-hand** [comment]
@takashiff thank you for putting that request. it is very necessary as i have been seeing a lot of issues related to manifest.json file. i have also seen some capabilities being limited by non-customizable index.html file. 
if you could answer this, is it possible for flutterflow PWA on mobile to hide browser bar as user scrolls? i have not found a single dependable solution online.

**Comment by Ravivizsoft** [comment]
Hello, This issue still not fixed.

**Comment by fafa16** [comment]
Hi, I have the same issue. What is the solution please?
