### ISSUE TITLE
Empty screen bug in api calls

### ISSUE THREAD

**Issue by adil-nauruzbaev** [FlutterFlow/flutterflow-issues#2071]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when im trying add integer variable to my json body i got this screen https://imgur.com/a/A2Bpx29

### Expected Behavior

expect to test api call

### Steps to Reproduce

Create Post Api call, add integer variable, add to json body, click to response and test, and add value in this integer

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jM/q4c5PmOZE1bqBKflVtCo5Jkx5ao0/0tZRaCgofePtOol3evWlYhBocMzhT3N+OkSmmkkJzM7njdruUsEEZDCBfr5y+Zd2Vz3gWmqge5OBPM6WPXdSRORYGm6457SvuhJ+VfBsR3AW7E2qANnIYBXvH4DoImdISq/LZO4=

### Context

test api call

### Visual documentation

https://imgur.com/a/A2Bpx29

### Environment

```markdown
- FlutterFlow version:  v3.1
- Platform: Web
- Browser name and version: Chrome 120.0.6099.130
- Operating system and version affected: windows 10
```

**Comment by sbis04** [comment]
Hey @adil-nauruzbaev, this should already be fixed in the last update!
