### ISSUE TITLE
Invalid flutter code generation when using API call parsed result path

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#2072]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Create API call with DataType result:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9538e278-b86b-44e6-935f-821191e6aafe/6b8c2d76-c7b1-4e81-ac54-2cd301e39ccf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NTM4ZTI3OC1iODZiLTQ0ZTYtOTM1Zi04MjExOTFlNmFhZmUvNmI4YzJkNzYtYzdiMS00ZTgxLWFjNTQtMmNkMzAxZTM5Y2NmIiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.ZBAImHZefRDqwNO_oIQI9K4EThDmDnY_YqtxdrPlfPU)

1. Use the result of this call to display text in Text widget:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c7531aea-c1be-4775-8e6e-245d5dbb3f0b/e97326ee-df53-4f8b-8a2c-f558f1997e7a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNzUzMWFlYS1jMWJlLTQ3NzUtOGU2ZS0yNDVkNWRiYjNmMGIvZTk3MzI2ZWUtZGY1My00ZjhiLThhMmMtZjU1OGYxOTk3ZTdhIiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.kOJYptD7dYz0TzapqVHgQ8dJNxk6cjaVvQEOrvM2hPk)

Compilation fails because tha API call result is casted to string prior to field access:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1f2ee2a2-ce5b-4598-a397-5b5ba7050634/f21864ce-9f7b-43d6-8def-db9e0e40b179?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZjJlZTJhMi1jZTViLTQ1OTgtYTM5Ny01YjViYTcwNTA2MzQvZjIxODY0Y2UtOWY3Yi00M2Q2LThkZWYtZGI5ZTBlNDBiMTc5IiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.DLCvKnNBAcNuS-BB8E4jiNoJaCcstxatp1B8t5yBZFQ)

Compilation error text:

```
 The getter 'aPPFirstName' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'aPPFirstName'.
                              ).toString()?.aPPFirstName} ${ApiUserGetCall.user(
```

### Expected Behavior

Generated code accesses DataType's field without casting it to string.

### Steps to Reproduce

1. Create API call with DataType result ( endpoint is [https://foundersdao.bubbleapps.io/version-test/api/1.1/obj/User/1703009701822x845178788487511000](https://foundersdao.bubbleapps.io/version-test/api/1.1/obj/User/1703009701822x845178788487511000) )
2. Use the result of this call to display text in Text widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wksmB34p2sdtJ14SJb+9V+CQvIjs9RL8VkdYbdCs9GYjyO5YUaczOSFZCXe2iT1FXKEWIiXEGwcrukfPtE/kqZEubGr5D1c5QdjzdQkK/aoSgCamKZHNQTO5nGn6z0LuJoBN7JrNhS0Y42E+POPK9d3XqNKH6Zwh9f6PHaOI=

### Context

I'm trying to make an API call as a page backend query and use the received object to display data on the page.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cf81d3db-fefe-4705-97bf-8a7a10b1ea12/f460cd28-7ee1-4483-8939-b41f01e58cda?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZjgxZDNkYi1mZWZlLTQ3MDUtOTdiZi04YTdhMTBiMWVhMTIvZjQ2MGNkMjgtN2VlMS00NDgzLTg5MzktYjQxZjAxZTU4Y2RhIiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.VYvFIklTC3hjhAz75q1avnt0BImeoOm5uTbtjX0FFh0)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1efccb07-fe07-4567-911e-d46ff897c7ea/56a0b2ee-0b79-4918-8f97-ddb0b99c9263?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZWZjY2IwNy1mZTA3LTQ1NjctOTExZS1kNDZmZjg5N2M3ZWEvNTZhMGIyZWUtMGI3OS00OTE4LThmOTctZGRiMGI5OWM5MjYzIiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.EK8pm82qA_mmUGt3-fFo1WG6eWQqM0yVZQtyzuQec7w)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5051d679-98bf-46de-9889-db04a938b2d0/01bd6a09-8dc1-459c-bb53-7329ffde3363?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MDUxZDY3OS05OGJmLTQ2ZGUtOTg4OS1kYjA0YTkzOGIyZDAvMDFiZDZhMDktOGRjMS00NTljLWJiNTMtNzMyOWZmZGUzMzYzIiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.h52KJHX8WKIzg6-S0IhvnLh_lkFmXICboJP659WcF9g)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e27d62c0-9abf-401a-9f37-816c432fd1f5/61825a11-757d-4489-90b8-0c7c2956ce91?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMjdkNjJjMC05YWJmLTQwMWEtOWYzNy04MTZjNDMyZmQxZjUvNjE4MjVhMTEtNzU3ZC00NDg5LTkwYjgtMGM3YzI5NTZjZTkxIiwiaWF0IjoxNzA3MTgxODExLCJleHAiOjMzMjc3NzQxODExfQ.svKlNNaTQ95fq4yeRm7NSQhDTJOpEjl9pnJ1XnIK-Io)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: FlutterFlow v4.0 released December 22, 2023
- Platform: Web
- Browser name and version: Chrome 120.0.6099.130
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @appach22 - Thanks for submitting the issue. Could you please specify the endpoint mentioned in the issue? This information is essential to start the investigation.

**Comment by appach22** [comment]
Hi, @hariprasadms !
Below is the corresponding endpoint:
https://foundersdao.bubbleapps.io/version-test/api/1.1/obj/User/1703009701822x845178788487511000

**Comment by appach22** [comment]
Hi, @hariprasadms !
Any updates on this?

**Comment by appach22** [comment]
Hi, @hariprasadms !
I've tried to work around the issue but got a similar one instead:

1. First I added a predefined path of type "Json":
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/f49296bf-0e6e-468e-b4fb-8852f49a1af3)

2. Then I tried to use a string field of the result as a text variable in a Text widget:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/ce9ff5cd-96d5-44fd-9200-9c4cf9ac1454)

3. Generated code compiles well but crashes at runtime because of excessive cast to String:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/ed4d3bc8-7d56-4e15-853a-c53bc3c3082c)

I decided not to create a new issue because they are pretty similar in their nature.

**Comment by hariprasadms** [comment]
Hi @appach22 - Apologies for being late in responding to the issue. I can re produce the issue.  This happens when you have mapped the Api root response property to type of datatype and trying to access the response result as json type. 
 
<img width="1506" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/30989e06-0579-4b0b-bddd-f96eeb2829db">
However, you got a work around here to use json path to access values from api response. I hope you are not blocked here. Thanks

**Comment by appach22** [comment]
@hariprasadms thanks for the reply! You've found another scenario of reproducing the bug. In my case I have an Api result predefined Json path, mapped to a DataType (let's say "User" which has a string field "FirstName") and then I try to set Text widget's text property to Api Result -> Json Body -> Predefined Path -> User -> Data Structure Field -> FirstName

And I don't have an acceptable workaround here. The only option I discovered is to wrap the widgets to a Component and then pass Api Result -> Json Body -> Predefined Path -> User as a component parameter. Unfortunately the workaround you suggested is quite unconvenient because I have lot's of objects with lot's of fields to display in my project.

**Comment by victoriahuang1** [comment]
@appach22 @hariprasadms are you still experiencing the issue? When I download the code for the snapshot corresponding to the bug report code, I get this code:

```
'${ApiUserGetCall.user(
  homePageApiUserGetResponse.jsonBody,
)?.aPPFirstName} ${ApiUserGetCall.user(
  homePageApiUserGetResponse.jsonBody,
)?.aPPLastName}',
```

There is no casting to string, as expected

**Comment by appach22** [comment]
@victoriahuang1 no. The issue disappeared at some point in the end of January :)

**Comment by victoriahuang1** [comment]
Glad to hear it's working as expected now :)

Sorry for the delayed response!
