### ISSUE TITLE
For iOS App, generating Info.plist will not work for 20%+ of apps

### ISSUE THREAD

**Issue by kodjima33** [FlutterFlow/flutterflow-issues#2073]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Note: I'm re-opening the issue 1444 because it was closed by mistake and shouldn've have been closed => too many people complain about it 

Trying to add new permission for iOS App, for key like "UIBackgroundModes" and want to add value as "audio", the genrated Info.plist is not proper as this key expects the value as "Array of strings" but it is generating just String as below
UIBackgroundModes
audio

INSTEAD of

UIBackgroundModes

audio

With this there is no way that manually add/edit Info.plist in flutterflow to add permission to the audio player for playing it in background

----
This means that ANY IOS app that requires background mode WOULDN'T WORK ON FLUTTERFLOW

### Expected Behavior

The generated Info.plist should be

UIBackgroundModes

audio

### Steps to Reproduce

Open Settings -> Permissions
Click on "+ Add Permission" to add new permission
Enter iOS Permission Key as "UIBackgroundModes", Permission Message as "audio" and save
The generated Info.plist is not proper

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Any Widget will work

### Context

Since our app requires background permission, We cannot push the app from flutterflow because it wouldn't work

I'm [Nik](https://www.linkedin.com/in/nik-shevchenko-08565b18b/), founder of welovenocode.com (one of the biggest traffic providers for flutterflow)

The ticket should not have been closed. This is a major issue that caused at least 2 of our devs to churn from Flutterflow. We are also paying for a Flutterflow "team" package but this issue is causing us so much pain and wasted time that we are considering to leave

Any IOS app that requires background services on the background WILL NOT WORK, because this permission is inside of an array of UIBackgroundmodes, there is no way to edit this permission from Flutterflow.

I'd really ask you to look into this and fix this asap because there is no use in flutterflow's deployment feature with this bug
-----

This means that ANY IOS app that requires background mode WOULDN'T WORK If DEPLOYED FROM FLUTTERFLOW

### Visual documentation

![CleanShot 2023-12-28 at 18 47 04](https://github.com/FlutterFlow/flutterflow-issues/assets/43514161/285a0d6a-16af-490a-b2a6-41e833d244dd)

### Environment

```markdown
- FlutterFlow version: v3.13
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 116.0.5845.179 (Official Build) (arm64)
- Operating system and version affected: iOS App
```

**Comment by MartinLockheart** [comment]
Has there been any progress on this? I'm about to be building background functionality into one of my apps, and I want to make sure I can deploy it properly when it's finished.

**Comment by wenkaifan0720** [comment]
Hey @kodjima33. Just to make sure, is background audio playing on iOS still not working for you right now (which should have been by issue #1167)? Or are you trying to add a new custom permission type?

**Comment by takashiff** [comment]
@kodjima33 Hello, thank you for your bug report. This looks to be the same issue as #1682, so I'm going to mark this as a duplicate. If you believe this to be a separate issue, please feel free to follow up in this thread. Thank you for your patience.

**Comment by SMCHub** [comment]
Hallo zusammen, ich benötige dringend eine Lösung für dieses Problem. Könnte jemand bestätigen, ob dieses Issue noch offen ist und ob es bereits Fortschritte gibt? Vielen Dank!
