### ISSUE TITLE
Geolocation error

### ISSUE THREAD

**Issue by meeuwsstefaan** [FlutterFlow/flutterflow-issues#2074]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My code:
// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:geolocator/geolocator.dart';

Future newCustomAction() async {
  // save the current location to a variable
  var currentLocation = await Geolocator.getCurrentPosition();
  print(currentLocation);
// Do something with the current location variable
}

The output in the Edge browser console:

Error: Geolocation has been disabled in this document by permissions policy.

### Expected Behavior

The location is supposed to be printed in the Edge browser console.

### Steps to Reproduce

1. Create a new page
2. In Custom Code / Add / Custom Actions
3. Paste the code as shown above (including "print(currentLocation);"
4. On the page, create a button with Action = the new Custom Action
5. Run the app
6. You will get the Geolocation error in the Console of your browser.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hsrk+Y9PmNsF4rvqLMJoghchQG5/WLknp9Z7aCwqGJToPLUMPsneVFRuZrykT3NXfWKgimAd7Pfqht7LE8EFBwWdfaJTzpAJbw3/c3GjRLawEqjsfW1fGtNbN27D58Kg2QhDBOluLloEwzumIdiWdHbDJKbIDDIZLfyLKdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to get the currentLocation at 500ms intervals, so I can calculate the speed of the Android device and thus of the user.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/93784697/bee2facb-ddbd-4109-aa9d-234fbb73ea51)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/93784697/c295daa5-601d-4c82-aa3b-30728ce08df5)

### Environment

```markdown
- FlutterFlow version: 4
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows 11
```

**Comment by meeuwsstefaan** [comment]
I am new at FlutterFlow. Please be very precise when you give instructions.

**Comment by hariprasadms** [comment]
Hi @meeuwsstefaan - Thank you for submitting the issue. Based on the error, it seems to be related to your browser settings. It's possible that your browser permissions are preventing the display of geolocations. Please try enabling the necessary permissions in the Edge browser? Additionally, you can test it in Chrome browser to see if the issue persists.

**Comment by hariprasadms** [comment]
I trust you are no longer experiencing the reported issue. I will close the issue for now, but feel free to reopen it if the same behavior persists on your end with more details. Thank you.
