### ISSUE TITLE
Theme widget unlink width and height does not work as expected for containers with no values

### ISSUE THREAD

**Issue by SebyOnGitHub** [FlutterFlow/flutterflow-issues#2076]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In a Themed Container there is a functionality to disable the width and height.
The tooltip says: "If link is off, this property will be ignored when this theme widget style is applied."
But if the link is disabled, the value will still be applied to all containers in the project that use that theme.
This only happens to containers within the project that have no width/height values set inside them.

### Expected Behavior

The width and/or height should remain unchanged from the theme widget when linking is disabled.
The disabled linking only works if there is no number set inside the theme widget.
It should still not write values into the empty width/height, even if there is a value set inside the theme widget, when linking is disabled. 

### Steps to Reproduce

1. Create a new page
2. Add a container widget
3. Place a text inside this new container widget
4. Remove the width and height from the container widget
(the container should now have the width and height of the text)
(in this example i made the widget red, to make it more visible)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/1f3c9f3c-30bf-4d47-8789-26f166cedd0c)

6. Under Theme Widgets, create a new Container Theme Widget
7. Under Container Properties, unlink the width and height (but leave the 100 in both)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/74e99786-0823-4e99-aaa2-36271b87b626)

8. Go back to the new container widget with the text in it
9. Apply the newly created Theme widget to this container
10. Now you can see that even with the linking disabled, the width and height are still being overwritten, which should not happen.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/4d5b7183-4806-47de-9ae7-26261f0da7b4)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oz8r134t2pbwD1arqd/lanio5JkB+U6xMj+1xdwoYfa3NG7UIec/4VEptXbC+TVc3PWeJjT8Jw9bLvczIN/ddFAeVfqJAzc5IchXiYFGhMb7XDc/tSnFPPNpKCH7F0J6JuiVCJuxZWEYb1GCMftyXfD3ZJ7r3PDBEM/mJDIT7nX/uQ0SLb3kNh1JWeC/v

### Context

Every time I update the Container Theme widget, all containers with no width and/or height in the project are overwritten. The "workaround" of setting no value to the theme widget is not elegant, as the theme itself is then no longer visible.

### Visual documentation

All the visual documentation was created within the Steps to Reproduce.

### Additional Info

No additional Infos.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web, Windows
- Browser name and version: Chrome 120.0.6099.111
- Operating system and version affected: Windows 10
```

**Comment by sbis04** [comment]
Hey @SebyOnGitHub can you please add a bug report code from the project in which you are using the theme widget? The bug report helps us to get more context about the project to investigate an issue.

**Comment by SebyOnGitHub** [comment]
@sbis04 I have now inserted the bug report code from a project that you can use for testing purposes.

**Comment by sbis04** [comment]
Looks like this only happens when a property is not set on the page widget, in those cases it applies the theme's properties. It's a little annoying, but I believe it's not a blocker since you can just remove the values from the widget on the page after applying the widget style. I'll make it a low priority for now but we'll try fixing it soon.

**Comment by wenkaifan0720** [comment]
This should be fixed in our next update. Thanks!
