### ISSUE TITLE
When creating a new field, the dropdown box for "Enum" data type does not work in Chrome or Edge

### ISSUE THREAD

**Issue by jonathanmr22** [FlutterFlow/flutterflow-issues#2077]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a new field, the dropdown box for "Enum" data type does not work in Chrome or Edge. I cannot finish making an Enum data type because of this issue. It cannot be clicked on.

### Expected Behavior

The Enum dropdown box should be useable.

### Steps to Reproduce

(1) Create a new field, (2) name the field, (3) choose "Enum" for data type, (4) then attempt to select the dropdown box to choose the Enum type.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okufqyItPj7xJ1s7uKflagSQXJUwhaLsZjcpBay0jF7KuDLMqY8/RVERBcNSoT3NUJWD9jWoW0PTMuNrhVPQrPTurG5RN1Khyag2XLWWXVqalFJWvOHx8TNJWChWg0pmjsRJdAPpfLUYA1F+UAe+uaCbaN5DKNlYgDq/LZO4=

### Context

I am trying to create fields in Firebase

### Visual documentation

None

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome (120.0.6099.130) and Edge (120.0.2210.91)
- Operating system and version affected: Windows 11 (23H2)
```

**Comment by hariprasadms** [comment]
Hi @jonathanmr22 - The provided reproducible steps lack sufficient details to understand the issue in your project. To conduct a more in-depth investigation, please create a new project with detailed steps and share bug report code please.  Your cooperation is appreciated. Thank you.

**Comment by hariprasadms** [comment]
NO sufficient details to reproduce the issue. Hence, I will close the issue for now, but feel free to reopen it if the same behavior persists on your end with more reproducible steps details. Thank you.
