### ISSUE TITLE
GridView missing start/end spacing

### ISSUE THREAD

**Issue by realimposter** [FlutterFlow/flutterflow-issues#2078]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you create a GridView widget there is no option to add start or end spacing
<img width="221" alt="gridview" src="https://github.com/FlutterFlow/flutterflow-issues/assets/51212151/186b2dab-f807-4bd8-bb4e-7bdcbdd7dcd0">

### Expected Behavior

There should be start/end spacing options similar to the ListView
<img width="222" alt="listview" src="https://github.com/FlutterFlow/flutterflow-issues/assets/51212151/a188cae0-918a-48fb-822f-debb56689acd">

### Steps to Reproduce

1. create GridView
2. missing GridView Properties->start spacing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelPHlw852j7xc1s7ydu5GhQMwJ0QlUIInj+0bWRMhfL7zPJotds+lalFLYteleXxHME3+gjkdpOzFv/PEV8AqKQ+WR5xY/r5XQT3vfE+5MszQDqmafmtQP+ZXfW6D55+nhiJdJsBuV14M21OAO/CrG3qCf9qOYwx5e6fDbOY=

### Context

I'm creating a page with the main content visible behind the header. This works when I place the header in a stack over the main content, and use a ListView with start spacing to offset the size of the header. But when I switch the ListView for a GridView, the start spacing is missing from the properties.

### Visual documentation

<img width="222" alt="listview" src="https://github.com/FlutterFlow/flutterflow-issues/assets/51212151/3e7366b3-e028-4e97-b3d1-0cbec941b1f5">
<img width="221" alt="gridview" src="https://github.com/FlutterFlow/flutterflow-issues/assets/51212151/d0c47579-d29c-42cd-81e6-32c876cea714">

### Environment

```markdown
- FlutterFlow version: v4 3.13.7
- Platform:Web
- Browser name and version: Chrome 120.0.6099.130
- Operating system and version affected: Windows
```

**Comment by wenkaifan0720** [comment]
Hi @realimposter. The start and end spacing for list view is really just a convenience method. Conceptually it doesn't really work for grid views as grid view is a 2D layout widget. If you want to add spacing, you can add padding to the grid view.

**Comment by realimposter** [comment]
> Hi @realimposter. The start and end spacing for list view is really just a convenience method for adding padding to the start and end of the list view. Conceptually it doesn't really work for grid views as grid view is a 2D layout widget. If you want to add spacing, you can add padding to the grid view.

Thanks for the reply, the problem with padding is that it clips the contents of the list/grid. But with start spacing you can make the list start below stacked widgets like a header, and then the main content scrolls behind the header without clipping like on iOS

**Comment by wenkaifan0720** [comment]
I see. In that case, could you try putting the grid view inside of another list view (which has start/end spacing) and set the grid view to be shrink wrapped?

**Comment by realimposter** [comment]
hey @wenkaifan0720 I tried that too but the problem is shrink-wrap doesn't work with infinite scrolling, causes the all the items to load at once and then the app crashes. I feel like the grid view really needs the same start spacing property, works perfectly for lists

**Comment by realimposter** [comment]
> Hi @realimposter. The start and end spacing for list view is really just a convenience method for adding padding to the start and end of the list view. Conceptually it doesn't really work for grid views as grid view is a 2D layout widget. If you want to add spacing, you can add padding to the grid view.

if you create a ListView and GridView both with top padding you can see the GridView is missing the internal padding:  

```
// ListView
Padding(
  padding: EdgeInsetsDirectional.fromSTEB(0, 9, 0, 0),     //9 px top padding
  child: ListView(
    padding: EdgeInsets.fromLTRB(
      0,
      60,    //60px start spacing
      0,
      60,    //60px end spacing
    ),
    children: [
    ],
  ),

// GridView
Padding(
  padding: EdgeInsetsDirectional.fromSTEB(0, 9, 0, 0),     //9 px top padding
  child: GridView(
    padding: EdgeInsets.zero,    //missing internal padding parameter
    children: [
    ],
  ),
)
```

**Comment by realimposter** [comment]
@wenkaifan0720 @kevintonb can you look into this again? I don't understand why the issue is closed,  internal padding works just like ListView even with the 2d Gridview widget. Here's an example of the GridView with start spacing vs padding:  

https://github.com/FlutterFlow/flutterflow-issues/assets/51212151/ea32612a-742a-4923-ac52-cea1c5418390

https://github.com/FlutterFlow/flutterflow-issues/assets/51212151/e0c25df9-08cb-415d-a6c4-7157323a76ea

**Comment by wenkaifan0720** [comment]
Hi @realimposter. Sorry I misunderstood the problem. I thought ListView's start and end spacing was added by adding two empty SizedBox to the beginning and end of the list (which wouldn't make sense for GridView). This is totally doable and should be added in FF. Thank you for your suggestion and detailed explanation.

**Comment by wenkaifan0720** [comment]
Should be added in our next update. I'll close this issue for now. Thanks!

**Comment by realimposter** [comment]
> Should be added in our next update. I'll close this issue for now. Thanks!

Thank you! really appreciate all your work 👍
