### ISSUE TITLE
No option "Item at index" in list of complex objects drop downs

### ISSUE THREAD

**Issue by MaximeDelhorme** [FlutterFlow/flutterflow-issues#2079]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No way to select "Item at Index" option in the drop down for "Available Options" for list of user defined data type. This is true for all actions

### Expected Behavior

The option "Item at Index should be available in the drop down options

### Steps to Reproduce

1. Create new page
2. Create a data type
3. Create a component on your page that takes for input a list of data type created in 2
4. In the component create an action that needs to access the list at a desired index
5. See that there is no option to do that

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jMrq081NodhE18/+ccB7/Ck5JWI8a+cvj+x7aCorB5DoPZsUecmkM0RpQuHjTWx+IU2KgWoW0anTivz1IMYoCwmYRt1Jz7tiYQLzUkKnboy4FJWgeUF7LNNYBUyZ1MGC3B1DJrBuc1lg12aUe9i/TgHYQ4DaIVgSD6/LZO4=

### Context

Just trying to access an element of a list at specific index

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/87cc83c9-d3d5-4ab1-9efa-ed24ee245709/e0bfdadc-28b5-4ecd-bf0e-98e20882514c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84N2NjODNjOS1kM2Q1LTRhYjEtOWVmYS1lZDI0ZWUyNDU3MDkvZTBiZmRhZGMtMjhiNS00ZWNkLWJmMGUtOThlMjA4ODI1MTRjIiwiaWF0IjoxNzA3MTQxOTUyLCJleHAiOjMzMjc3NzAxOTUyfQ.lGW_HH7oJFA9F5pKQRadKDeLfXHeGCbqqIiqudu64YU "=309x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 released December 22, 2023 Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 113.0.5672.126
- Operating system and version affected: macOS Monterey 12.5
```

**Comment by hariprasadms** [comment]
Hi @MaximeDelhorme - Item at index option available while mapping to a field which accepts a single value but not list. It is same for all actions. The dropdown option property accepts only list of values. Above provided image not showing which property you are trying to set. 

If you still have questions regarding this issue, I recommend setting up a new blank project with detailed steps to reproduce the issue. Share the bug report code from this new project for further investigation and resolution.

I hope it can help you. Thanks

**Comment by MaximeDelhorme** [comment]
Hi Hari,

Thanks for the reply.
I am trying to give as parameter to a component the value of a list at a certain index.
Maybe you could indicate me how to do that?

Thanks,
Maxime

**Comment by hariprasadms** [comment]
Hi, If the parameter type is not a list type in that case you can map a value from index. See below. 
Another way is, custom code. I hope this can help you.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/cd9bd29d-9510-4f69-bb96-be64210032b4

**Comment by MaximeDelhorme** [comment]
Thanks! It helps!
