### ISSUE TITLE
The first time a user signs in, Push Notifications doesn't works 

### ISSUE THREAD

**Issue by siddharthadevops** [FlutterFlow/flutterflow-issues#208]
## Expected behavior (required)
The first time a user signs in, Push Notifications should works

## Current behavior (required)
The first time a user signs in, Push Notifications doesn't works 

## To Reproduce (required)
1. Create and App
2. Sign in with SMS

This bug is caused because when user finishes the sign in process the NavBarPage is pushed this way:

                        await Navigator.pushAndRemoveUntil(
                          context,
                          MaterialPageRoute(
                            builder: (context) =>  NavBarPage(initialPage: 'Lessons'),
                          ),
                          (r) => false,
                        );

In the main page, instead, you ara using the widget PushNotificationsHandler to receive notifications. Sou you could call the nav bar page this way to solve the problem:

                        await Navigator.pushAndRemoveUntil(
                          context,
                          MaterialPageRoute(
                            builder: (context) =>
                                PushNotificationsHandler(child: NavBarPage(initialPage: 'Lessons')),
                          ),
                          (r) => false,
                        );

## Context (required)
Every single FlutterFlow App.

**Comment by organicnz** [comment]
Hi @siddharthadevops. Thank you for adding this issue 🙂
Pls add more content through steps/ widget tree/ actions to reproduce this exactly 🙂

**Comment by siddharthadevops** [comment]
Hi @organicnz I have shared this repository with you:

https://github.com/siddharthadevops/acim/tree/flutterflow.

There you can take a look at the code generated by FlutterFlow. When a user signs in no notifications are received. When the app is detached and relaunched then they do work.

**Comment by organicnz** [comment]
> Hi @siddharthadevops. Thank you for adding this issue 🙂 Pls add more content through steps/ widget tree/ actions to reproduce this exactly 🙂

Thanks for sharing mate :)

**Comment by siddharthadevops** [comment]
Hi @organicnz, Thank you for your response.

In flutterflow.io -> Settings & Integrations -> AppDetails -> Initial Page section I can set an "Entry Page" and a "LoggedIn Page". When the user is not logged EntryPage is showed and when user is logged the "LoggedIn Page" is built.

This works fine when user initializes the app and is already logged because you build the main page as follow:

main.dart
...
```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ACIMSOCIAL',
      localizationsDelegates: [
        FFLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: _locale,
      supportedLocales: const [
        Locale('en'),
        Locale('es'),
      ],
      theme: ThemeData(brightness: Brightness.light),
      darkTheme: ThemeData(brightness: Brightness.dark),
      themeMode: _themeMode,
      home: initialUser == null || displaySplashImage
          ? Builder(
              builder: (context) => Container(
                color: Color(0xFF250879),
                child: Image.asset(
                  'assets/images/Logo_ACIM.png',
                  fit: BoxFit.fitWidth,
                ),
              ),
            )
          : currentUser!.loggedIn
              ? PushNotificationsHandler(child: NavBarPage())
              : WellComePageWidget(),
    );
  }
}
```
Note that in this case you are using your PushNotificationsHandler widget as parent widget of NavBarPage().

But, when the user first signs in via SMS and your FF action "Verify SMS Code" is called, after the code is verified, you are pushing NavBarPage(..) without using your widget PushNotificationsHandler(child: NavBarPage()) as you do in the code snippet shown above. Instead, in this case you are pushing the page this way:

phone_login_code_intro_widget.dart (In this page is where I'm using your "Verify SMS Code" action)
...
```
Padding(
                    padding: EdgeInsetsDirectional.fromSTEB(0, 20, 0, 15),
                    child: FFButtonWidget(
                      onPressed: () async {
                        final smsCodeVal = pinCodeController!.text;
                        if (smsCodeVal == null || smsCodeVal.isEmpty) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(
                              content: Text('Enter SMS verification code.'),
                            ),
                          );
                          return;
                        }
                        final phoneVerifiedUser = await verifySmsCode(
                          context: context,
                          smsCode: smsCodeVal,
                        );
                        if (phoneVerifiedUser == null) {
                          return;
                        }

                        await Navigator.pushAndRemoveUntil(
                          context,
                          MaterialPageRoute(
                            builder: (context) =>
                                NavBarPage(initialPage: 'Lessons'),
                          ),
                          (r) => false,
                        );
                      },
                      text: FFLocalizations.of(context).getText(
                        '7aodj86h' /* Verify */,
                      ),
                      options: FFButtonOptions(
                        width: 200,
                        height: 40,
                        color: Colors.white,
                        textStyle:
                            FlutterFlowTheme.of(context).subtitle2.override(
                                  fontFamily: 'Roboto',
                                  color: Color(0xFF060606),
                                  fontSize: 18,
                                ),
                        borderSide: BorderSide(
                          color: Colors.transparent,
                          width: 1,
                        ),
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                  ),
```

So, as PushNotificationHandler widget is not used in the later case, the App is not handling the notifications until it's detached and initialized again.

**Comment by agreaves** [comment]
Hi @siddharthadevops, thank you for the bug report and the very detailed explanation. This is indeed an issue and a great solution, which will be added upon our next release! Thanks 🙂
