### ISSUE TITLE
Auto-size issue with container

### ISSUE THREAD

**Issue by Perlo34** [FlutterFlow/flutterflow-issues#2080]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a problem with the size of my text, in fact I wrap them in containers that are defined on a certain percentage of the width of the screen, the text is on auto-size so that the text is always the same size whatever the dimensions of the screen but I have a kind of bug I think that happens only on the first screen of the application. I have the impression that it's the auto-size that doesn't take effect immediately, because after the slightest click on a part of the screen, everything is displayed correctly.

https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/de175f1b-9d80-40a7-9659-79607c2c2e76

### Expected Behavior

I'd like to use the auto-size feature on a text wrapper in a container that measures a certain percentage of the screen width so that the text always faces the same despite different smarphone screen sizes.

### Steps to Reproduce

1. create project 
2. create a text
3. wrap it into a container
4. set auto-size and max line to 1
5. set container size in poucentage with exactly the size of the current text
6. test with smaller screen than screen use to designing ( issue is only on first screen of the app)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89god9b1ofpKPpqhR0gHDN8UecsmO5xTQAdG5DmGbYURfjDU1hZZ8ioSghIfU3/hnsC0tGLk/DuUPAGPh6ufNl/1c9Abg7/cEOgVa6wPYeKWURPGphUG0+PyqervxJ+HOh2eClpig/GSw==

### Context

When I launch my app I get a screen with several text bugs until I click anywhere. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/f39a4059-c301-4f8a-9df6-9a01e781d4a7

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/375beef2-9c0c-4b93-af9f-8a1b35011739)

Before click and after click on app launch
![Capture d'écran 2023-12-30 152737](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/127a6f1a-08b3-424b-a083-1af57c2ef5b7)

![Capture d'écran 2023-12-30 152746](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/07180748-26e3-465a-a784-7412b43df9e7)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Brave 1.61.109
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @Perlo34 - Thanks for setting up a blank project. I have looked at the project. I can see the same behaviour. 
It works fine after removing the container which was wrapped the text ( See image below ). It is mostly related to the design. However, I can mark this for technical review before deciding not a bug. 

Try changes as below and see if that can help you. Thanks 

<img width="426" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/28037c55-1243-4258-811a-14e1a031bf3d">

**Comment by Perlo34** [comment]
if I delete the container that wraps the text, then what I'm trying to do doesn't make sense, because the reason I wrapped it in a container was so that the text would always be the same size on any screen size.

**Comment by takashiff** [comment]
@Perlo34 Are you still currently facing this issue? I am currently unable to reproduce it.

**Comment by Perlo34** [comment]
no i receive a message from support that the issue has been patch

**Comment by takashiff** [comment]
Got it, thanks for the update. Going to mark this as "fixed" now.
