### ISSUE TITLE
FocusNode was used after being disposed 

### ISSUE THREAD

**Issue by mohanedsayed** [FlutterFlow/flutterflow-issues#2081]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The case for this project is that the user is asked to add multiple items or single item into the cart and once signed in the user is asked to add 4 required images and have the option to add a description text to the item in cart. these image upload placeholders and text fields are generated dynamically through a component. The issue appears whenever I have more than one item in cart, if the user adds the text for the text fields only, no errors will appear but once the user touches the upload image widget and try to add 1 image, I think the focusnode is being disposed off and the error appears then.

### Expected Behavior

I expect the user to input data in text fields and upload the needed images for all the existing cart items and proceed with no crashes.

### Steps to Reproduce

1- create new page
2- create a listview
3- create a component that contains a text input field and an image widget with the image upload action inside.
4- create dynamic children for the listview and put the created component as the child of the listview.
5- run the project in test mode or publish it.
6- try to use the upload image widget in a listview that contains more than 1 item.
6- observe what happens to the text input fields if the image widget is being interacted with after inputing data in the text fields.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wzMrl8YxNoctE+KrcdcExhj4vIjt5bLszle5DYCs8JJToPLAUZ8zBM05vZr3mYwhUJ0yWijodxvfquOGXVsI4HzStfrk4/6hqbxWXcHGgb7a6C7mVfW1QEe9nBUiE4Le72hRCNu9sR1YZ2066P+iyZ3fXGbr1PW0zHOalLdeK2SrDX1iXc2URm05KZDPz

### Context

I need the user to be able to have multiple items in his cart, this affects the main process of the app.

### Visual documentation

![Screenshot 2023-12-31 at 4 50 48 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4812460d-ddd4-4c19-9eea-779b66dd63bd/e26160e9-d793-4d61-a761-0078efdbec87?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODEyNDYwZC1kZGQ0LTRjMTktOWVlYS03NzliNjZkZDYzYmQvZTI2MTYwZTktZDc5My00ZDYxLWE3NjEtMDA3OGVmZGJlYzg3IiwiaWF0IjoxNzA3MTgxODI2LCJleHAiOjMzMjc3NzQxODI2fQ.yObWEjUsbENqBaGeT-g8xTjYxtOf3Rxqjxk97gIOOOk "=1440x")

![Screenshot 2023-12-31 at 4 51 59 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/397c01ef-a154-44a2-adc6-d859ace0006f/2301e88d-5b08-40ed-a477-23747a6eeca5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zOTdjMDFlZi1hMTU0LTQ0YTItYWRjNi1kODU5YWNlMDAwNmYvMjMwMWU4OGQtNWIwOC00MGVkLWE0NzctMjM3NDdhNmVlY2E1IiwiaWF0IjoxNzA3MTgxODI2LCJleHAiOjMzMjc3NzQxODI2fQ.lVBSNXgH3qZEvcpNHNx-lid6F9fR84C9nwXl5CGIE2E "=1440x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4
- Platform: Web
- Browser name and version: Chrome 120.0.6099.109
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by JP-BLURP** [comment]
@mohanedsayed were you able to find a workaround to this? I haven't been able to make any progress in app the past few days?

**Comment by hariprasadms** [comment]
Hi @mohanedsayed - Thanks for submitting the issue. I looked at your project page but could not find the issue steps as described in above steps.

Upon reviewing steps 3 and 4, it appears to be more of a design issue. Based on my understanding, you are attempting to upload multiple images for a single child item in a list view. The error arises because the upload action component is not unique in your scenario. To address this, consider modifying the design to enable multi-item uploads for each element in the list view or ensure uniqueness of the component within the list view. Implementing these changes should potentially prevent the error you are encountering. Please correct me if my interpretation of your issue is inaccurate.

If the problem persists, it would be helpful if you could create a blank project with the specified steps to allow us to run and investigate the configurations, It helps us in identifying the root cause of the issue. Thanks

**Comment by JP-BLURP** [comment]
@hariprasadms I have the same issue in my project, but it only happens when I use the "Unique Key" feature. If I don't use the unique key it works fine, but then I can't use text fields dynamically. I tried using different variations of the unique key, such as: combine text with "create_at" and "UserID" and also "unique key base on index" both of which cause the focus node error in my project. This only started happening roughly 5 days ago, as I've been building my app for over a year, and haven't had this issue

**Comment by JP-BLURP** [comment]
@hariprasadms  here's a blank project I created with the issue: https://app.flutterflow.io/project/test-project-bug-bya7n4?tab=widgetTree&page=HomePage

**Comment by JP-BLURP** [comment]
Here is the error I get: 
![Screenshot 2024-01-02 at 11 59 52 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/104392279/b043f052-e2ee-473f-a069-14af890306a2)
![Screenshot 2024-01-02 at 1 04 33 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/104392279/7b9ed430-66d6-4713-8f82-9dcb67acc231)

**Comment by mohanedsayed** [comment]
> Hi @mohanedsayed - Thanks for submitting the issue. I looked at your project page but could not find the issue steps as described in above steps.
> 
> Upon reviewing steps 3 and 4, it appears to be more of a design issue. Based on my understanding, you are attempting to upload multiple images for a single child item in a list view. The error arises because the upload action component is not unique in your scenario. To address this, consider modifying the design to enable multi-item uploads for each element in the list view or ensure uniqueness of the component within the list view. Implementing these changes should potentially prevent the error you are encountering. Please correct me if my interpretation of your issue is inaccurate.
> 
> If the problem persists, it would be helpful if you could create a blank project with the specified steps to allow us to run and investigate the configurations, It helps us in identifying the root cause of the issue. Thanks

@hariprasadms, thank you for replying to my issue but unfortunately I implemented the image upload widgets to also be unique and each item upload logic is separate from the other one's. I will create a small project with the same design hierarchy as the main project and post it here for you.

**Comment by mohanedsayed** [comment]
> @mohanedsayed were you able to find a workaround to this? I haven't been able to make any progress in app the past few days?

Unfortunately I haven't found a workaround for it yet.

**Comment by sbis04** [comment]
@JP-BLURP I looked into the blank project with the issue setup, looked like it is happening because of specifying the "Unique Key" on the component. Can you try removing the key and checking if the issue still exists?

**Comment by JP-BLURP** [comment]
@sbis04 It only happens when the "Unique Key" is set, which is needed for dynamically using components
