### ISSUE TITLE
FloatingActionButton gets overflowed

### ISSUE THREAD

**Issue by KevDev99** [FlutterFlow/flutterflow-issues#2083]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the floating action button is showing cut off on the emulator or when installing the .apk.

### Expected Behavior

Showing the FloatingActionButton correctly in the right bottom cornen without overflowing

### Steps to Reproduce

**standard setup of page:**

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/b6fa6336-7ffb-4c37-a991-4ec27eaa1bd4)

**looks fine in the builder:**

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/2de85350-88b7-4389-9574-cc72b2fbbd13)

**is overflowed in the emulator or when testing on real device:**
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/45159a51-5daa-4c52-b65f-b766ad25152d)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcjfz4VNseFd0a6Jc8ZVlWQQHF8cTIMziNZ+exUbfaL1BuwQO86lXBBVXbXmaVNcGFSaklEE/vDQk+LiGvA6aAmdGbk4wqhAFw3ee2iXVamVC5eCdHd8P+RhGkzD1rSVrREmB/huWHhg7TqEF9mQdHfDIuu/Zwh9f6PHaOI=

### Context

just want to use the FAB component with a nav bar

### Visual documentation

here on a blank page:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/addbcec4-73e3-4549-b3af-66d0aa8c6854)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/3a010638-07e7-4341-a825-cdc226cbed6a)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.129 
- Operating system and version affected: macOS 13.6.1 (22G313)
```

**Comment by KevDev99** [comment]
it works with the "Flutter Default Nav Bar" , hm i think it would be good to have at least a warning when using an floating action button with a floating nav bar

**Comment by sbis04** [comment]
There's a similar issue reported [here](https://github.com/FlutterFlow/flutterflow-issues/issues/1717), please follow that for further updates. Closing this as duplicate.
