### ISSUE TITLE
Unable to Fetch some Firestore Collections  when using web version

### ISSUE THREAD

**Issue by ikram3mkaissi** [FlutterFlow/flutterflow-issues#2086]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i keep getting this error whenever i try to fetch a certain "Surat" collection when using a web version
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/93371753/0333da67-9c11-45bf-9f80-cc53408edec3)

then no data is shown after waiting for a while,

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/93371753/65f54b0c-f351-4c16-ac05-09441b8c40da)

### Expected Behavior

fetching the "Surat" Collection works perfectly on a real device
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/93371753/2dab1c3e-ffee-4f0b-84d9-8f7edee38ce5)

### Steps to Reproduce

head to homepage ,add a backend query of the "surat" collection, add a text widget to show each surat document name, 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkPLl8Yx2rshE0KnybcdKgjgwGUwKarhEld1uGEsbI+PqELN/PPTBdk1WSOqHT1ZielWgnkMC0trliNr9Ie07Fy6rft05zrptUxDjWjiVRK6VCZGVe0ZtHf1PC2HHy6bQkBR+IbFac3AF1HGmB/OAb3qCf9qOYwx5e6fDbOY=

### Context

i can't get data from firestore database and test

### Visual documentation

Uploading Screen Recording 2024-01-02 at 11.54.20 AM.mov…

### Environment

```markdown
- FlutterFlow version:  v4.0 released December 29, 2023
- Platform: Web
- Browser name and version: Google Chrome Version 120.0.6099.129 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @ikram3mkaissi - Are you still experiencing the issue? What happens with other collections ?

**Comment by ikram3mkaissi** [comment]
> Hi @ikram3mkaissi - Are you still experiencing the issue? What happens with other collections ?

yes i'm still experiencing the issue ! some collections can be fetched properly and some not , i'm guessing it depends on the size of the documents

**Comment by hariprasadms** [comment]
Hi @ikram3mkaissi - Unfortunately, I am unable to reproduce the issue on my end. It seems to be project-specific and might be related to permissions. I recommend giving it another try in a new project, setting up the same collection with the same number of documents. If the issue persists, please share the bug report code of that project so that we can thoroughly investigate the issue.
