### ISSUE TITLE
Code expression giving wrong result

### ISSUE THREAD

**Issue by flutterflowdevs** [FlutterFlow/flutterflow-issues#2087]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Added a code expression to text widget to calculate mathematical expression which giving wrong result for some scenarios.

### Expected Behavior

Mathematical expression result should be same for every use text/ test case.

### Steps to Reproduce

1. Create a new page
2. Add 2 Text Field Widget (name as A, B) for input number.
3. create code expression with variable name **var1** and bind the var1 value which condition expression like if (A > B) then A else B.
4. Inside code expression simply write var1*100.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kksn6389IsdtJ7pDAb8d7/SAWQkR+U40wlu5HbAA0IbbnG7YAW/SkQE9WZ7yhdH03OFmZmnwywNLTuMzIN/I3FxyefrpOypBhFhXKUk6RaLKvPJGoW3AlINpKBWa8557Ynx1SPrNvLk4+606yPui/TgDYHoTMDFYzQ+WiCNz4nX/uQ0SLb3kNh1JWeC/v

### Context

I'm having trouble retrieving data from two different documents based on a condition and then using that data to evaluate an expression. The code expression wasn't working, so I managed to solve the issue by creating a custom function to handle it.

### Visual documentation

Please find the video below for Reproduce same error.

https://youtu.be/0uZ-uE0bXdM

### Additional Info

Please find the link of the demo public project so you can easily check the issue into your flutterflow project.

https://app.flutterflow.io/project/flutterflow-issues-js12yr?tab=pageSelector&page=CodeExpressionBug

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Flutterflow Platform
- Browser name and version: Chrome Version 120.0.6099.130 
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi, Do the expression changes as below. It is working as expected.

<img width="671" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/4e804966-1edc-4610-8c99-4d71b43a0d04">

**Comment by takashiff** [comment]
@flutterflowdevs Marking this as closed as the above seems to have solved the issue. If the issue still persists, please feel free to follow up in this thread. Thank you for your bug report!
