### ISSUE TITLE
DataTable widget code generation fail

### ISSUE THREAD

**Issue by Miamoto-Musashi** [FlutterFlow/flutterflow-issues#2088]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

building datatable from api call on google maps places result return a compilation error once run on test

### Expected Behavior

error should be hilighted before test run on UI or there shouldn't be any error

### Steps to Reproduce

1. define google api call with jsonpath for places
2. use api results in data table widget
3. use item value for text widgets
4. run in test mode
5. compilation fails

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SlefqwItOpbxJ7qX2bsEw+SoUKVAjRYI7lexqEAoYIpOtPOwxXOj9VEpoTcOHd2xEOlmY8XsK0NmOkeDlEsI9PiiCfKZmzqpxFg7ic3KtMZivDM6BOXB5L59VG22Hzbe33xVRNvdYWFo4wFyqH+68ZA/sO5f6C1UNAcikEJ/IpGDnLTLOXn0Jg1ZSfCvr

### Context

I'm tryin to use data table with places api results

### Visual documentation

<img width="621" alt="Screenshot 2024-01-02 alle 12 54 30" src="https://github.com/FlutterFlow/flutterflow-issues/assets/283196/e37e85bf-1a10-4f89-99d4-7fef7e58fda7">

### Additional Info

<img width="1579" alt="Screenshot 2024-01-02 alle 12 56 01" src="https://github.com/FlutterFlow/flutterflow-issues/assets/283196/e217af98-b5da-4e7a-ba2c-7f8afffb6486">

<img width="1057" alt="Screenshot 2024-01-02 alle 12 59 54" src="https://github.com/FlutterFlow/flutterflow-issues/assets/283196/b940fbb5-ca5c-4cd0-9db5-8a8a9f27f7a7">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version:Microsoft Edge Version 119.0.2151.97 (official build) (x86_64)
- Operating system and version affected: MacOs
```

**Comment by Miamoto-Musashi** [comment]
additional info:
after some experiments I found out the problem is given by the checkbox that is statically set to false, waiting for user input; the generated code thinks is set by the element variable

**Comment by hariprasadms** [comment]
Hi @Miamoto-Musashi - Are you still experiencing the issue ?

I reviewed your project, but I couldn't find the checkbox widget within the table. I did a test using a data table with checkbox widget as its children through an API call, and the test ran smoothly without any errors. However, in code view I observed that it automatically maps the checkbox value to the response item `_model.checkboxValueMap[todosItem] ??= true,` which seems incorrect.

**Comment by Miamoto-Musashi** [comment]
HI @hariprasadms , thanks for the review; to go ahead with the project I changed the UI and used a button instead of the checkbox; with the button the issue is not anymore present.
I'm not sure if the issue was coming from a previous assignement I was using for initial value of the checkbox, then reverted, or by the assumptions made during code generation.
If it helps I can help investigating by reverting to the historical version where the problem was present.

BR

**Comment by victoriahuang1** [comment]
Hi @Miamoto-Musashi , thanks for the report. I have put out a fix for this issue, and it should be resolved upon the next deploy.
