### ISSUE TITLE
Widget states are frozen when documents are excluded based on a filter

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#209]
**## Expected behavior (required)**

I have a PageView widget with a backend query for a list of documents and a filter. Based on this filter, the value of the field “statusTreatment” (which is a string) must be “forTreatment” for the document to be included in the list. 

Inside the PageView is a Card widget, and inside the Card widget is a Component. Inside the Component is a column with four widgets: a Text widget, a Textfield widget, a Slider widget, and a Button widget. 

The user must write something in the TextField, choose a value on the Slider, then click on a Button ("Done").

The Button ("Done") has an action that updates the field “statusTreatment” to a different value (“notForTreatment”), which means that this document is now excluded by the filter and kicked out of the list. Thus, the next document in line appears on screen. 

When the next document appears, I expect the TextField widget to be empty and the initial value value on the Slider to be zero. 

**## Current behavior (required)**
When the next document appears, the TextField and the Slider retain the same value that were entered by the user for the previous document. 

**## To Reproduce (required)**
1- Create a collection of documents titled "Anticipated_Events" (it should contain 3+ documents)
2- Each document should have a String field titled "WhateverText", in which you can write whatever you want, as long as it is different for each document. For me, I wrote "Document 1", "Document 2", and so on. 
3- Each document should also have a String field titled "statusTreatment". The value in this field should be "forTreatment" (for all documents). 
4- Create a PageView widget. 
5- Add a Card widget into the PageView page (inside the PageView widget). 
6- In the PageView widget, make a backend call for the Collection "Anticipated_Events", with the Query Type "List of Documents". Add a filter that specifies that the field "statusTreatment" must be equal to the following specific value: "forTreatment".
--> Sigle Time Query is OFF
--> Ignore Empty Value is OFF
7- Create a custom component titled "Custom 1" that contains a column, inside of which are four widgets: a Text widget, a TextField widget, a Slider widget (value can range from 1-7), and a Button widget with "done" written in it. 
8- Add the "Custom 1" component inside the Card widget. 
9- Pass a "Document" parameter from the PageView widget to the custom component "Custom 1". 
10- In the Text widget (inside your component), choose "from variable" and select the "WateverText" field of the document. 
11- In the button widget (inside your component), add an action that updates the field "statusTreatment" to a new value: "notForTreatment". 
12- The last thing to do is to run the app. Write something in the TextField and select a value on the Slider. Then click on the Button ("done"). The document will be excluded (since the value of it's field "statusTreatment" is no longer equal to "forTreatment"), but what you wrote in the TextField and the value you chose for the Slider will be repeated in the next document.

P.-S. the Text widget (not to confound with the TextField widget) is just to let you know that you are indeed looking at a different document, since it will show the value of the "WhateverText" field, which is unique to each document. 

**Code can be included in this section if it is relevant to reproducing the bug.** 
--> N/A

**Steps to reproduce the behavior:**

I described the steps above. 

## Context (required)
I expect the value of the TextField and the value of the Slider to "refresh" to empty/zero when a document is excluded from the list and a new document is showed on the screen. Otherwise, the user experience will be negatively impacted. 

**## Screenshots / recordings**
See the screen video at this address (recorded with Loom):
https://www.loom.com/share/b70d28513954479f8d1c6b0b6a5bd9f0

**## Your environment**
Windows 11, Desktop, Chrome, FF version 3.3.4.

**Comment by bulgariamitko** [comment]
@Alexandre-Lemyre , can you try to move your back-end query to the top of your page. To BugReport at the top and try again and let me know if that fix the issue.

**Comment by Alexandre-Lemyre** [comment]
@bulgariamitko, I am not sure I understand the strategy. If I move the back-end query to the top of the page (instead of the PageView widget), I can no longer pass a document parameter to the component. Am I missing something?

See the video where I tried what you suggested:
https://www.loom.com/share/8400a48a5821440a8395748db8ecdc58

**Comment by bulgariamitko** [comment]
I believe this is another issue that FF has unfortunately. That's why you can't set it up to the top level. Ok let's see what the FF team will say about this.

**Comment by Alexandre-Lemyre** [comment]
@bulgariamitko the status of this issue report is still "needs information". Is it an oversight?

Thank you.

**Comment by agreaves** [comment]
Hi @Alexandre-Lemyre, thanks so much for the info! I'll admit this way a tricky but fun issue to track down, as it has to do with how Flutter maintains the state of dynamically generated components. To bore you with the details, we need to add a `UniqueKey` to each component if it's dynamically generated, which we were doing in some cases but not all.

Long story short this issue should be fixed upon the next release early next week! 🙂

**Comment by Alexandre-Lemyre** [comment]
Thank you so much!

Very happy with that.

Looking forward for the next update.

Alexandre Lemyre, Ph.D., M.A.
Stagiaire Postdoctoral, École de criminologie, Université de Montréal
Centre d'Étude sur le Trauma (CÉT), Centre de recherche de l'Institut universitaire en santé mentale de Montréal (CR-IUSMM)
-----------------------------------------
Postdoctoral Fellow, School of criminology, University of Montreal
Trauma Studies Center, Research Center of the Montreal University Institute of Mental Health

**Comment by bulgariamitko** [comment]
@agreaves can you change the status to fixed, please.
