### ISSUE TITLE
Text field Focus Node Error on lists

### ISSUE THREAD

**Issue by JP-BLURP** [FlutterFlow/flutterflow-issues#2092]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get a focus node error whenever using the "Unique Key" feature on a text component.

![Screenshot 2024-01-02 at 1 04 33 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/47a44edc-8c06-4e87-884c-7d762c0a0198/cd96c319-38f5-439f-bf52-795c7ddbfe03?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80N2E0NGVkYy04YzA2LTRlODctODg0Yy03ZDc2MmMwYTAxOTgvY2Q5NmMzMTktMzhmNS00MzlmLWJmNTItNzk1YzdkZGJmZTAzIiwiaWF0IjoxNzA3MTgyMzk2LCJleHAiOjMzMjc3NzQyMzk2fQ.ZSx-fgrXd2Z8Yph3yNHpiGbx3pNRbUStIEj8Ssjv-\_U)

### Expected Behavior

I should be able to use the Unique key to use component dynamically. It's been the case in all other pages in my app.

### Steps to Reproduce

1. create a page.
2. create a container.
3. add list to container
4. add container to list.
5. add text to container.
6. convert text to component.
7. add query to list.
8. add Unique Key to text component.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cz/Hqx89grs9J1s/IdfoxnSQsH1whRYI319Z9RQ03DZPMC+wIZ/f7XFRuTde0TH9UPGGKmnMd7v/emvPAU/YFGwWZft19zrgJcAvgYGWQVJPXBc/pPm5/DZpQfkiF4LazuBRvCNhsW1Us7UOmfumycArUJ4OyC1UjLvGaB5CK2SrDX1iXc2URm05KZDPz

### Context

I can't use any components dynamically in my projects.

### Visual documentation

![Screenshot 2024-01-02 at 1 09 09 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5424f83c-a35b-4762-99d4-18bd8730a5ea/b0713899-ff61-4503-851b-00944cc729cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NDI0ZjgzYy1hMzViLTQ3NjItOTlkNC0xOGJkODczMGE1ZWEvYjA3MTM4OTktZmY2MS00NTAzLTg1MWItMDA5NDRjYzcyOWNiIiwiaWF0IjoxNzA3MTgyMzk2LCJleHAiOjMzMjc3NzQyMzk2fQ.2lEUDe4j6UytJbkUDw6z12vDFo-ELn51z8vR3ku-18I)

### Additional Info

This is in test mode

![Screenshot 2024-01-02 at 11 59 52 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8006ac36-d31b-4c10-873d-c6080c2b7c80/0de9a42e-9c45-4ca6-b668-a069821bd708?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MDA2YWMzNi1kMzFiLTRjMTAtODczZC1jNjA4MGMyYjdjODAvMGRlOWE0MmUtOWM0NS00Y2E2LWI2NjgtYTA2OTgyMWJkNzA4IiwiaWF0IjoxNzA3MTgyMzk2LCJleHAiOjMzMjc3NzQyMzk2fQ.D8z_bx2-MoLjxsD8-yE_c_GsQXIXkGlnNIcEhruG1G0)

### Environment

```
- FlutterFlow version: FlutterFlow v4.0.3 - Flutter version is 3.13.7
- Platform: web and desktop on my m1 Mac mini
- Browser name and version: Safari Version 16.1 (18614.2.9.1.12)
- Operating system and version affected: Mac Ventura version 13.0
```

**Comment by takashiff** [comment]
Hi @JP-BLURP, thank you for your bug report. This looks to be a duplicate issue with #2081. Please refer to the following thread for further updates. thanks
