### ISSUE TITLE
Nullable checkbox within list Argument from custom functions makes list emptyable but not nullable

### ISSUE THREAD

**Issue by SebyOnGitHub** [FlutterFlow/flutterflow-issues#2093]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Checking Nullable on a list argument, the generated code makes the list emptyable, but not nullable.
The name of the checkbox is therefore technically incorrect and misleading.
(See screenshot of steps to reproduce)

### Expected Behavior

When Nullable is checked on a list argument, it should generate code of a nullable list.

Here is an example of a nullable list:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/3cea7af5-db71-4fc5-9b06-141bec7295a4)
(See the "Context" section at the bottom of this report, where I show all four possibilities, including an example of a nullable list that is also emptyable.)

### Steps to Reproduce

1. Create a new custom function
2. Add an argument
3. enable "Is list" on this new argument
4. enable "Nullable" on this new argument
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/e7dd69c5-6d0d-4cc1-b2fd-b0a6e10057ab)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40is/l8Yx1ocdD7q6JasJagmA5Jjt5RK8Ziup7aCosfZT2BLMcec/RVERtcOHjTAl+OlmgmWoW0vT3uNn2GMY3NSWaG4B61rVtVQ//fEemMrKIFJWgS0EmP8RXIBWf38GZghN4NsZfSGQ57Tqpet+RUgnfQ4TYNTIeD6/LZO4=

### Context

I was expecting NullableLists in FlutterFlow, but this basic functionality is missing because of this reported bug. This is unfortunate.
The same goes for PageStates, WidgetStates and so on. But since I get nullable lists directly from Supabase, it only bothers me in custom functions for now.

Here is an example of the 4 types that are possible in Dart: (But not in FF)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/4e9cb0f1-5698-492e-9c86-f57e594efa6b)

### Visual documentation

All the visual documentation was created within the previous examples.

### Additional Info

The project from the bug report code can be used for testing purposes.
In addition, there is quite a lot of documentation about null safety for Dart/Flutter, which explains the differences between an empty list and a nullable list.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web, Windows
- Browser name and version: Chrome 120.0.6099.111
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
HI @SebyOnGitHub -In the provided screenshot above, I observe that when the nullable checkbox is selected, "testargument2" is marked as nullable. Could you please bit more clarify your expectations?

**Comment by hariprasadms** [comment]
If you are referring to the function signature based on the selected arguments property, I can confirm that it is displaying as expected. If you have any specific concerns or questions regarding this, please provide additional details for further clarification.

**Comment by SebyOnGitHub** [comment]
Hi @hariprasadms 
No, that is not correct. If the checkbox nullable is checked, the list is not nullable.
If the nullable checkbox is checked, the list can be empty but not nullable. These two are not the same thing.
A list is nullable if the question mark is placed directly after the paratemer type, like this `DateTime?`.
Here is an example of a nullable list:   `List<DateTime?>?`.
Here is an example of a list that is **not** nullable:   `List<DateTime>?`.
So is the List in FlutterFlow Not nullable.
The ? after the >? only indicates that the list can be empty, but not nullable, which is a big difference. Please have a look at the official Dart Null Safety Concept if you are not sure what I mean.
And thats be bug I am reporting here, the checkbox says nullable, but it does not make the list nullable, thats wrong and a bug, so please remove the "not a bug" status.

**Comment by aemelyanovff** [comment]
@SebyOnGitHub When we refer to a list as nullable, we mean that the list itself can be null. Currently, FlutterFlow does not support lists with nullable elements. I couldn't find the term 'emptyable lists' mentioned anywhere on https://dart.dev/.

If you would like FlutterFlow to support lists with nullable elements, please either file a feature request on the [community wishlist](https://community.flutterflow.io/general-wishlist) or use the in-app feedback form.

Thanks!
