### ISSUE TITLE
Renaming widget de-selects the widget

### ISSUE THREAD

**Issue by daniel-pixelprism** [FlutterFlow/flutterflow-issues#2095]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm having an issue renaming my widgets, wherein typing letters into the widget name deselects the widget after each keystroke. I.e., it only lets me enter one character at a time before de-selecting.

I am using an Alienware R17 r4 laptop with Windows 11 Pro (22H2) and Google Chrome (Version 120.0.6099.129 (Official Build) (64-bit)). Caps lock is off, number lock is on, insert is off.

### Expected Behavior

If I type "Hello" and hit enter, I expect the widget to be renamed "Hello.

Instead, as soon as I type "H", the widget renames itself "H" and de-selects. 

### Steps to Reproduce

Note: Side view is set to split page tree / widget tree

1. double click a widget in the widget Tree (I confirm I see the blinking "|" to indicate I am editing)

2. Begin type "Hello"

3. As soon as I type "H", the widget will save the edit (I.e., the widget will be named "H", and I will have to double click it again and repeat the process to add "O", then "L", etc. etc.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9amWUXC1w5a700st4bGAsdGOvrBu0qZPfebVhvZ+25aVNcAWakklkxweDViPHhA/cEFEiuG91FwodyUAzOe2iVVKaIPqrpSUdtI8ZhG2KfyrWv2xUnBNBfS1Yt71yTOOiydD7DFOu/Zwh9f6PHaOI=

### Context

Nothing in widget tree can be renamed. As a workaround I type the desired widget name in notepad, then copy and paste it into FlutterFlow but this only works sometimes (it's finicky). 

The page tree is not affected at all. It is only the widget tree.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/155578299/5d9e358b-5201-4209-8d65-0a6e70dd2f42)

### Environment

```markdown
Project: bugReport
Project ID: bug-report-u9o5on
FlutterFlow v4.0 released December 29, 2023
Flutter version is 3.13.7

- Platform: Alienware R17 r4 laptop
- Browser name and version: Google Chrome (Version 120.0.6099.129 (Official Build) (64-bit))
- Operating system and version affected: Windows 11 Pro (22H2)

Caps lock is off, number lock is on, insert is off.
```

**Comment by hariprasadms** [comment]
Hi @daniel-pixelprism - Thank you for reporting the issue. I can confirm that this is indeed a bug, and it will be addressed in future builds. As an alternative solution, you have the option to edit the widget name in the widget property section. I hope you've already observed this workaround. Appreciate your feedback. Thanks

**Comment by otizhi** [comment]
Hi there, can confirm that this is also an issue in Edge Version 120.0.2210.91 (Official build) (64-bit)
When renaming a component directly in the Widget Tree, the editor closes after typing the second character. There is no way to get past the first two characters. The max characters that can be typed are two.
Any idea on when the fixed will be rolled out? If is a productivity killer.

**Comment by takashiff** [comment]
Hello @daniel-pixelprism, thank you for your bug report. This issue has been fixed recently and should be reflected within the next few weeks. Thank you for your patience!

**Comment by saphiroko** [comment]
This is still an issue.
