### ISSUE TITLE
Text field: If then statements combined with "Combine Text" causes compilation error

### ISSUE THREAD

**Issue by John-DreamLabs** [FlutterFlow/flutterflow-issues#2097]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've had this happen a few times in different places in the app. By layering if/then statements with combine text in a text field, the application fails to compile. 

### Expected Behavior

combining if/then statements with Combine Text in a text field shouldn't cause the app to crash.

### Steps to Reproduce

1.  create a text field
2. add "combine text" as initial value
3. add some dynamic conditional text via if/then statements 
4. run via test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTis/qw89Irsdc+Kn6YcExhioWI0McX5Ir1utsewgjGKL1Bux3euCkYRFoTfWhaVNffVn8pDgdzPTNidjtMvcVPQuZc75Hz4dUFwree2iiaKrRCJa0YkF7N+JXC0OM5p6zoiJBCNVeSiUt12aUFeesbCvDFOu/Zwh9f6PHaOI=

### Context

Trying to pre-populate some text based on a few different conditions. 

### Visual documentation

<img width="894" alt="Screenshot 2024-01-03 at 12 15 01 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145049643/9fe0fdbf-f4f6-4fab-9f00-d2d9bfc505eb">
<img width="589" alt="Screenshot 2024-01-03 at 12 17 23 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145049643/90a9fdd7-66c5-4640-a395-84c4f1a1135c">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0.3 Flutter version is 3.13.7
- Platform: Test Mode
- Browser name and version: Version 120.0.6099.129 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.1.2 (23B92)
```

**Comment by victoriahuang1** [comment]
Hi @John-DreamLabs , thanks for the report. I have addressed the issue on our end, and this should be resolved upon the next deploy.

**Comment by John-DreamLabs** [comment]
Awesome, thank you!
