### ISSUE TITLE
Updated WebView plugins

### ISSUE THREAD

**Issue by rgrajivchn** [FlutterFlow/flutterflow-issues#2099]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Web view URL getting cached and not showing the latest page - Please see page - Events in App - GospelinChennai - [https://app.flutterflow.io/project/gospelin-chennai-7xv73z](https://app.flutterflow.io/project/gospelin-chennai-7xv73z).

There is no setting done for any caching. And see the behaviour working fine on iPhone, Android Phone. BUT, on iPad, even after 3 days, it is still showing the earlier version of the webpage. Even after killing the app several times, it still shows the older version of web page.

### Expected Behavior

The latest version of the webpage should be shown, when the page is launched in the app

### Steps to Reproduce

Launch App - GospelinChennai, Go to Events - page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CkcmBx4h2ofVA1pSJc8JFmiUXHEw/RYEZ1utDQgIcJ5PMC+wIZ/f7XFRuTde0TwlEM02J/X8K0P/emvL2Gu0oGEydbtlCycxQVgvLUk+RWpClDqmSOG5/DcBUFWqz4bW3uyNQB/pvSXwb1zqAJtm/bDfsGL7NNm0CDc6lNZCK2SrDX1iXc2URm05KZDPz

### Context

Create a new page - web view and use URL - [https://www.gospelinchennai.info/mv/](https://www.gospelinchennai.info/mv/)

### Visual documentation

Create a new page - web view and use URL - [https://www.gospelinchennai.info/mv/](https://www.gospelinchennai.info/mv/)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: iOS
- Browser name and version: Not applicable
- Operating system and version affected: iPad OS
```

**Comment by rgrajivchn** [comment]
environment in flutterflow?. If you can be specific please.

**Comment by rgrajivchn** [comment]
Can you please respond

**Comment by crossxsecure** [comment]
I’d like to bring to your attention that the WebView feature in Flutterflow has several issues. Even if we disregard our project for a moment and focus solely on creating a browser application using Flutterflow, we encounter numerous compatibility problems.

For instance, many websites, when opened in Flutterflow’s WebView, do not trigger the keyboard. Additionally, pressing the back button often leads back to the activity screen, instead of navigating to the previous webpage within Flutterflow. This is despite these websites functioning perfectly in mobile browsers like Chrome and Edge.

Now, turning our attention back to our project, we encounter another issue with WebView. I experimented with a simple Bing search page and found that every time I clicked on the search area, the page reloaded and failed to open the keyboard in the web version.

Similarly, with another website, I noticed that tapping the back button in the web version did not navigate to the previous webpage. Instead, after tapping the back button 2-3 times, it navigated to the Activity page from the WebView. In contrast, in the app, tapping back for the first time navigates back to the Activity Page, rather than navigating back within the WebView page.

These issues highlight the need for improvements in Flutterflow’s WebView functionality.

**Comment by rgrajivchn** [comment]
> I’d like to bring to your attention that the WebView feature in Flutterflow has several issues. Even if we disregard our project for a moment and focus solely on creating a browser application using Flutterflow, we encounter numerous compatibility problems.
> 
> For instance, many websites, when opened in Flutterflow’s WebView, do not trigger the keyboard. Additionally, pressing the back button often leads back to the activity screen, instead of navigating to the previous webpage within Flutterflow. This is despite these websites functioning perfectly in mobile browsers like Chrome and Edge.
> 
> Now, turning our attention back to our project, we encounter another issue with WebView. I experimented with a simple Bing search page and found that every time I clicked on the search area, the page reloaded and failed to open the keyboard in the mobile web version.
> 
> Similarly, with another website, I noticed that tapping the back button in the web version did not navigate to the previous webpage. Instead, after tapping the back button 2-3 times, it navigated to the Activity page from the WebView. In contrast, in the app, tapping back for the first time navigates back to the Activity Page, rather than navigating back within the WebView page.
> 
> These issues highlight the need for improvements in Flutterflow’s WebView functionality.
> 
> PFA Reference Video: https://drive.google.com/file/d/1AuaqX6DUMn3mD6ecWTIKEDpzHep-C6OH/view?usp=drivesdk

OK, looks like webview has lot of limitations

**Comment by wenkaifan0720** [comment]
Hi @crossxsecure, @rgrajivchn. We are using Flutter's built in webview on the web, which could have some issues, especially on iOS/iPadOS web. The current version is a bit outdated, which we will definitely update soon. 

In the meantime, I just want to point out that it is not the best practice to place a webview inside of a Flutter web app, especially on mobile. Does launching the web page on a new tab work for your use case?

**Comment by rgrajivchn** [comment]
Thanks for all the updates

**Comment by crossxsecure** [comment]
Hi @wenkaifan0720, could you please include the updated versions in the upcoming FF release?

**Comment by crossxsecure** [comment]
Hi @wenkaifan0720 @kevintonb @FlutterFlowEng, this ticket is aging since last month and it is just about updating the WebView respective plugins to the most recent stable versions. Hence, could you please address the same?

**Comment by wenkaifan0720** [comment]
Hi @crossxsecure. Unfortunately updating the webview package requires updating other packages as a whole, so I can't do it right away. We do have regular package updates every few months. I'll speed up the process but it could take a while.

**Comment by wenkaifan0720** [comment]
The webviewx_plus package will be updated in our next release!

**Comment by crossxsecure** [comment]
Thanks @wenkaifan0720 for providing an update, I believe it would also include the similar WebView plugins update as well?

1. webview_flutter
2. webview_flutter_android
3. webview_flutter_platform_interface

**Comment by nyashasam** [comment]
Hey @wenkaifan0720 has WebView been updated? I'm facing similar issues with it.
