### ISSUE TITLE
A broken permission element in AppManifest.xml

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#210]
I applied a Custom permission to iOS only.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/5080329/206828352-2b026b12-5296-4fff-a2e5-563177b493ac.png">

And I found out there is a broken permission element in AppManifest.xml

<img width="757" alt="image" src="https://user-images.githubusercontent.com/5080329/206828303-db59b64f-eefd-4aac-8c65-737734f92687.png">

**Comment by Pepino-GR** [comment]
Hi thruthesky,

with the version of  today, December 10, 2022, it seems to be fixed

**Comment by thruthesky** [comment]
@Pepino-GR It is still there.

**Comment by Pepino-GR** [comment]
In your screen copy, I only see the iOS setting. Below, you will see the setting in fFlutterFlow  and the setting in the AndroidManifest.xml. Maybe you can remove it in FlutterFlow  and set it again.

<img width="826" alt="Bildschirm­foto 2022-12-11 um 12 33 52" src="https://user-images.githubusercontent.com/35230751/206901141-81651514-58e2-49f5-b208-ec4890873074.png">
<img width="666" alt="Bildschirm­foto 2022-12-11 um 12 40 44" src="https://user-images.githubusercontent.com/35230751/206901480-09c4d28d-e31c-49d1-afc6-b9085bb005a5.png">

**Comment by thruthesky** [comment]
@Pepino-GR I don't need ACCESS_FINE_LOCATION because it exists already in the AndroidManifest.xml. So, Just left it as empty.
I applied the Custom permission to iOS only.

**Comment by Pepino-GR** [comment]
The ACCESS_FINE_LOCATION is only a sample. But if you do not set android.permission, you don't want to see the line inside the  AndroidManifest.xml?

**Comment by Pepino-GR** [comment]
Thanks for inform us.

**Comment by agreaves** [comment]
Thanks @thruthesky for the bug report! I agree that if the Android or iOS permission name is empty it should not be included. This will be fixed in the upcoming release! 🙂

**Comment by thruthesky** [comment]
@agreaves Yes, Thank you :)
