### ISSUE TITLE
When converting Data Types to JSON the JSON String is not being formatted correctly. The String is generated without the appropiate Quotes

### ISSUE THREAD

**Issue by OrbysSocialMediaLLC** [FlutterFlow/flutterflow-issues#2101]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we try to send information to an API from a toJSON that is converted from a Data Type stored in a PAGE State is not formatting the JSON string correctly.

This is what is sending:

{UserId:89,UserName:username,FullName:First Second,EMail:user@domain.com,TimeZone:z152,Currency:USD,UserNameChanges:0}

It should be sending:

{"UserId":89,"UserName":"username","FullName":"First Second","EMail":"user@domain.com","TimeZone":"z152","Currency":"USD","UserNameChanges":0}

### Expected Behavior

When converting the Data Type variable to JSON the string value should be formatted as a standard JSON String like:

{"UserId":89,"UserName":"username","FullName":"First Second","EMail":"user@domain.com","TimeZone":"z152","Currency":"USD","UserNameChanges":0}

### Steps to Reproduce

Just try to send convert any Data Type to JSON and even try to Display it on an ALERT. I also checked the backend API and it's still doing the same thing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeicjfw8pPj7xA7Yfcc8ZWgQMxQUB+bZ0vlO1FGUgaB6qqO5YiePTEaXduX9CrT252I2eKknEdpK2Okt/tLPUoH0uCboN607V1EwKVWmKWRqmYDau0Y3NRFtNnGUCG08OrnRMnGPh2LVlk1GGLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

When you need to send information to any API in JSON format the API can't receive the information and parsed it. 

### Visual documentation

Create a Page call a query for the page fields and call Action on Load to store the initial values of that page in a Local Page State Variable. Then put a bottom un the page and create action when clicked to display the content of the Local State Variable (DataType to JSON).

* You will need to create the Data Type to store the results of the JSON call on load. 
![Untitled](https://github.com/FlutterFlow/flutterflow-issues/assets/104394285/26e2ef5b-7d1e-4afb-8b58-236e114eedb0)

### Additional Info

![Untitled](https://github.com/FlutterFlow/flutterflow-issues/assets/104394285/cb042659-dfba-4e7c-8954-42d760503edb)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: All
- Browser name and version: ALL
- Operating system and version affected: ALL
```

**Comment by OrbysSocialMediaLLC** [comment]
Here is a sample project showing the issue with another API:

https://app.flutterflow.io/project/issue-data-typeto-j-s-o-n-string-jkgewo

**Comment by hariprasadms** [comment]
Hi @OrbysSocialMediaLLC - I looked at your project and api response configuration. The correct configurations should be as below for your use case. Try and confirm please.

<img width="666" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/85bead7b-7bd6-4127-a257-1ba0cae3b347">

Regarding response you mentioned above, is this causing any breaking issues in the project?. Please confirm. Thanks

**Comment by OrbysSocialMediaLLC** [comment]
That is incorrect. I should be ale to send the whole body. Not a specific Node.

**Comment by OrbysSocialMediaLLC** [comment]
So how can update an API with multiple values? What are you saying is that I need to update every value one by one? Seriously?

**Comment by OrbysSocialMediaLLC** [comment]
In the Example I used only one value to demonstrate the issue. I already spend hours troubleshooting this issue and I also had to build a test project. To show the issue. You didn't even looked at my images in the issue where I show you multiple values. 

So let me explain one more time.....

If I need to submit a JSON body to an API the body of that JSON needs to be formatted correctly so the receiving API could parse the request. 

so like I said before your system is sending this:

This is what is sending:

{UserId:89,UserName:username,FullName:First Second,EMail:[user@domain.com](mailto:user@domain.com),TimeZone:z152,Currency:USD,UserNameChanges:0}

It should be sending:

{"UserId":89,"UserName":"username","FullName":"First Second","EMail":"[user@domain.com](mailto:user@domain.com)","TimeZone":"z152","Currency":"USD","UserNameChanges":0}

**Comment by OrbysSocialMediaLLC** [comment]
I have additional information after multiple testing and trying to get a resolution in our side.  I'm attaching video showing the issue:

1. when using Variables to send the Body in JSON or Parameters in URL (for example {POST} https://demo.api.com/SaveInfo/{"id":1,"name":"John Doe"}) the variable coming out of FF is not being formatted correctly.
2. If you look at the video you will see the example
3. Is clear that the JSON is not forwatted correctly when using variables. 

[https://youtu.be/HeafebU_7Vc](url)

https://youtu.be/HeafebU_7Vc

**Comment by OrbysSocialMediaLLC** [comment]
It seems that it was an issue with the type of variable that I was using. It seems that you can't use the String variable when trying to send JSON in FlutterFlow. If anyone have a similar issue that is the solution. If you are going to send a JSON payload with a variable you need to ensure you are using a variable with type JSON and not String in FF. Thanks to support for helping me find a solution.
