### ISSUE TITLE
iPad application sync issue

### ISSUE THREAD

**Issue by chris-PearlIT** [FlutterFlow/flutterflow-issues#2103]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon logging into my project via the iPad application my project's uiBuilder was updated/ rolled back to the current version held in the iPad.

### Expected Behavior

Whichever platform I use to log into my project the current git hub repository is the most up to date version of my project, not the version held in my iPad since I last logged in with it 2 days ago.

### Steps to Reproduce

create a project. my project was created in chrome browser.

1. log into project with iPad app.
2. close iPad app.
3. do work on your project from chrome, edge... anywhere.
4. log into iPad app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkOfl0It1pbxK+KX6b8BsnjgXMjs6bIJNm9YacCs8GZT0B4kcYs+kfklUOcPhS1FIfU60rGEX/MmPvuDPKe0EaAqbbKU6+pBuSjnhRki6M73REYS3b3NCI/hPf1Cc35iZhiMkPbZ2L1INwzqYGNysZB/dJKGzNWwFR+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

I was given to understand my projects are held in a central git hub repository, that no matter which platform I use to access it, via FF, I will be presented with the latest version of it updated to the second. It's my belief that the iPad application should query the current repository and resolve differences in versions using timestamp data. That is of course assuming you can work on the iPad application offline. If you cannot do that, then surely the iPad application, upon start up, should dump it's data and download the current repository version.
The behavior I am seeing is that the iPad has updated the repository version with it's own automatically.
This issue has affected me by deleting the contents of 2 pages one of my devs has been working on, several 50+ fields datatypes, some app state variables, and several custom functions that deserialized json's into those data types. In essence about 15 - 20 paid hours of building / coding.
The other effect this has is that unless working on a project solely within the iPad application. That application is useless for fear of losing progress.

### Visual documentation

![Screenshot 2024-01-04 165156](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9bf531c4-1308-49a7-9fa1-5a7fab027d8b/deacb0b3-057b-4018-9e1f-c94dc25e84e2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YmY1MzFjNC0xMzA4LTQ5YTctOWZhMS01YTdmYWIwMjdkOGIvZGVhY2IwYjMtMDU3Yi00MDE4LTllMWYtYzk0ZGMyNWU4NGUyIiwiaWF0IjoxNzA3MTgyMzc0LCJleHAiOjMzMjc3NzQyMzc0fQ.Pg9qHX4DUjyZHIjvYtVnJAmgfCqHSgWL-pTs0pI0iqk)

### Additional Info

The image above shows at 16:02 an update made by myself to the uiBuilder. I logged into my iPad application at that time to view only, no changes were made to the project.
The entry has been auto generated by my iPad. I do not believe it to be a conflict of 2 people working on the project at the same time as my other dev left the project around 14:30.
In hindsight, a couple of days ago I lost a small amount of work, but didn't think anything of it as i resolved it in about ten minutes. It was around the time that I log into the FF iPad app running on my mac mini.

### Environment

```
- FlutterFlow version: 4.1.18
- Platform: iPad
- Browser name and version: iPad Application
- Operating system and version affected: IOS 17.2
 
Alternate platform also being used on project.
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.131
- Operating system and version affected: Windows 11 Pro 10.0.22621 Build 22621
```

**Comment by sbis04** [comment]
Hi @chris-PearlIT, so sorry that you faced the project overwrite issue. We have recently deployed a fix for the FlutterFlow iPad app to prevent this issue in the future.
