### ISSUE TITLE
Markdown hyperlinks not working

### ISSUE THREAD

**Issue by jeffgalak** [FlutterFlow/flutterflow-issues#2104]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a markdown widget with well formatted markdown hyperlinks. The links show up in blue (as they should) and the mouse-over behavior works (the mouse icon changes to the clicking icon). However, nothing happens with the link is clicked. There is no redirect or page open of any kind. 

### Expected Behavior

When clicking on the link, the webpage should call a web browser and open the link.

### Steps to Reproduce

1. create a new page. 2. add markdown widget. 3. Populate it with "[Google](http://www.google.com)" as a test. Run. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci/Lqw412sbQD1pSJKe9VmSQWCDt/RY080dV9cEwYN5PMCokAdsykVFRoOLC0S2xiMU6KmngzzP/emvPEUvE5GzebR65zzc9+VA/KWnKuVbKoO6WCSm5/AtNjGHHH0Z+32hVdOtNvS1IM7E+Het6RQg3fQ4T6IEgzOMj8JZOK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to create a GPT-style chat bot. OpenAI sends its content back in markdown. I'd like the links to render and send users to wherever they are routed.. 

### Visual documentation

Not needed

### Environment

```markdown
- FlutterFlow version: 4.0 - 3.13.7
- Platform: mac
- Browser name and version: chrome
- Operating system and version affected: all
```

**Comment by hariprasadms** [comment]
Hi @jeffgalak - Thanks for submitting the issue. I can reproduce the issue. onTapLink action property is not set to markdown widget. 

<img width="441" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/cd697e18-e5f9-4a09-9b60-2a4f9df1013e">

The work around is, you can use custom code to achieve this. I hope that works for you.

**Comment by jeffgalak** [comment]
Thank you for the reply. I’m not too familiar with using custom code. Would
you mind walking me through that? Would it work with dynamically generated
links that OpenAI creates and passes to the app via their api? Or must the
links be hardcoded?



Please excuse any typos as this is sent from my mobile device

**Comment by sbis04** [comment]
This should be fixed in the next update!

**Comment by jeffgalak** [comment]
Awesome. Thank you!

Any idea when the update will go live?

Thanks again!
Jeff

Please excuse any typos as this is sent from my mobile device
