### ISSUE TITLE
Bug in FlutterFlow App Check Implementation with reCaptcha Enterprise

### ISSUE THREAD

**Issue by pedrohssales** [FlutterFlow/flutterflow-issues#2105]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using App Check with reCaptcha Enterprise in a web-based FlutterFlow project, a persistent error 400 occurs, preventing the application from loading. This issue persists despite following the documentation provided by both FlutterFlow and Google Cloud.

### Expected Behavior

The application should successfully load on the web without encountering any errors, especially after correctly implementing App Check with reCaptcha Enterprise as per the provided documentation.

### Steps to Reproduce

1. Ensure Firebase is configured in the project.
2. Navigate to 'Settings and Integrations' in the FlutterFlow interface.
3. Access the 'Firebase > App Check' tab.
4. Enable App Check and follow the documentation provided by FlutterFlow and Google Cloud for App Check implementation.
5. Obtain an App Check key and register your app's domain with this key.
6. Enter the obtained key in the Firebase dashboard under 'App Check'.
7. Publish your app on the web.
8. Attempt to access your app's URL. The app will not be accessible, except in Test mode or Run mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShcrqx4hgosgC7qXcYMF6hQMjNlx7bZAnktV+WRMhfJPmOpYQOffCVE1LYtSoeX47BmaGhkkJw/DTufHxUcJeISerfqI/+ZRXQTvxZF2mMpDREruWS3dRM+JTG0yAyLungBN/NvJuWnNg71OmBfCdG3qCf9qOYwx5e6fDbOY=

### Context

I am currently using App Check with reCaptcha Enterprise in my project. I have meticulously followed the documentation provided by FlutterFlow ([FlutterFlow Documentation](https://docs.flutterflow.io/settings-and-integrations/project-setup/firebase/app-check)) and Google Cloud to implement this security feature in my application. However, I encountered a persistent error 400, as shown in the image below, which prevents my web application from loading. My application is exclusively web-based and is now stuck on an eternal loading screen.

![293831672-a4be56af-c355-4ff5-85b1-fd15a0ae780d](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0d87c061-12d3-41d2-b734-63f6a657889a/a6d5edf9-ad0b-4a95-a2cc-3b3077c54286?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZDg3YzA2MS0xMmQzLTQxZDItYjczNC02M2Y2YTY1Nzg4OWEvYTZkNWVkZjktYWQwYi00YTk1LWEyY2MtM2IzMDc3YzU0Mjg2IiwiaWF0IjoxNzA3MTc4ODAyLCJleHAiOjMzMjc3NzM4ODAyfQ.5PshPVldPkUd9ZveV8-mXuB7Oj46ZyH16x0J4rZtuWo)

![293832449-27d153da-3dfe-4e6c-8e72-3825c614dfee](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2180da8b-eaa5-4a9f-88ad-66878b1a2d3a/f60f79e1-fc48-4923-8e3b-6d6225d58ff1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMTgwZGE4Yi1lYWE1LTRhOWYtODhhZC02Njg3OGIxYTJkM2EvZjYwZjc5ZTEtZmM0OC00OTIzLThlM2ItNmQ2MjI1ZDU4ZmYxIiwiaWF0IjoxNzA3MTc4ODAyLCJleHAiOjMzMjc3NzM4ODAyfQ.tAwt83eTj5GSiRNCnKa_VjCwNrgI3w9feZFD7UFgDtA)

After sharing my issue in the community forum ([FlutterFlow Community Post](https://community.flutterflow.io/integrations/post/app-check-issues-GuWa9riLDDqKoHf)) and receiving no response, I decided to investigate the error in more depth through my browser. I noticed that the error message referenced an attempt to obtain a key for reCaptcha V3, which was surprising since I was using the Enterprise version.

Subsequently, I reached out to the Firebase support team to report this issue. Below is the response I received from them.

![screenshot](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d72dac58-7cc4-4aed-9b21-9038581da406/47588247-190c-4f78-bd84-5486ffba8787?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNzJkYWM1OC03Y2M0LTRhZWQtOWIyMS05MDM4NTgxZGE0MDYvNDc1ODgyNDctMTkwYy00Zjc4LWJkODQtNTQ4NmZmYmE4Nzg3IiwiaWF0IjoxNzA3MTc4ODAyLCJleHAiOjMzMjc3NzM4ODAyfQ.cYO5mZ5rSzEmrG6YDflF-HeFkBZcFToee_Zfsj-jjbA)

As you can see, the issue lies with FlutterFlow. It is attempting to create a key using reCaptcha V3 instead of reCaptcha Enterprise.

I believe this is a significant bug that could affect many users. It's of high importance as it hinders the implementation of a crucial layer of backend security, potentially preventing attacks on Firebase through unwanted requests.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/53bc8ad3-df59-418a-8e0e-a916c5991f9f/36d3463f-530f-4ab9-a3b3-1808c8bff63a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81M2JjOGFkMy1kZjU5LTQxOGEtOGUwZS1hOTE2YzU5OTFmOWYvMzZkMzQ2M2YtNTMwZi00YWI5LWEzYjMtMTgwOGM4YmZmNjNhIiwiaWF0IjoxNzA3MTc4ODAyLCJleHAiOjMzMjc3NzM4ODAyfQ.YAEYvdpsd5qunumxJJTeKr9ftemzzh7LUHH3eCPDoZc)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Cgrine 120.0.6099.130
- Operating system and version affected: Windows 10 22H2
```

**Comment by ignalauret** [comment]
Hey @pedrohssales thanks for your report. The AppCheck integration has been fixed in newer versions. Could you confirm if you are still experiencing this issue with your reCaptcha Enterprise?

**Comment by leighajarett** [comment]
Closing this issue since we have not heard back
