### ISSUE TITLE
url-launcher next update?

### ISSUE THREAD

**Issue by nicorne** [FlutterFlow/flutterflow-issues#2106]
## Question
When do you plan to update Flutterflow url-launcher next? How often are these dependencies updated?

## Problem
I am trying to use a web3 wallet authentification package which uses the url-launcher package.

The problem:
url-launcher is not up to date on Flutterflow.

I am unable to achieve web3 wallet authentication because of that.

**Comment by nicorne** [comment]
@hariprasadms I followed the template on #2057. 

My question is straightforward and doesn't require the template's detailed info to be answered.

Please give me an answer, my company depends on it. 🙏

**Comment by hariprasadms** [comment]
Hi @nicorne - What you mean by url launcher is depricated in FlutterFlow.   We got url_launcher: 6.1.10 version of package  and its action works fine as expected.

**Comment by nicorne** [comment]
@hariprasadms I meant up to date.

The `url_launcher` latest version is 6.2.2. [Link](https://pub.dev/packages/url_launcher)

Thank you!

**Comment by takashiff** [comment]
Hello @nicorne, this looks like a duplicate issue with [the following](https://github.com/FlutterFlow/flutterflow-issues/issues/2057). Please refer to the linked thread for further updates on this issue.
