### ISSUE TITLE
Enable setVolume feature on the video player

### ISSUE THREAD

**Issue by ishak-lm** [FlutterFlow/flutterflow-issues#2108]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Screenshot 2024-01-05 at 21 03 55](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a6bdfc95-48b6-453d-b5d6-233811ddd475/d914c01b-d342-4382-8ed4-bcca6bad5cae?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNmJkZmM5NS00OGI2LTQ1M2QtYjVkNi0yMzM4MTFkZGQ0NzUvZDkxNGMwMWItZDM0Mi00MzgyLThlZDQtYmNjYTZiYWQ1Y2FlIiwiaWF0IjoxNzA3MTQ0NzU0LCJleHAiOjMzMjc3NzA0NzU0fQ.Qg0cQTHLA0ALsDzaPOvFQ7tLKa4AEdNizOaRjOqyu2w "=301x")

### Expected Behavior

Possibility to have access to all the parameters of video_player.

### Steps to Reproduce

1. Add videoPlayer widget
2. Enable loop
3. Disable Show controls
4. Enable auto-play

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8r13ItPsbRG1r6JdPlFp2M4KV8cT5MnktVudw4sCKL2O4kQdvWkXEpvZMDjTwhheUSmmn0C+cqJj+PDEPYrHAqAfrU5z81qUDvKYD2la5OBOriePnclAcFhC0PE0cPYkx1SBPJ1ZU4n6mWmefDIaAPvJr72IlFISq/LZO4=

### Context

We want to be able to display a video using FF player with:

* Loop = true
* showControls = false
* auto-play = true
* setVolume = 0

The goal is to create a kind of feed like insta/linkedin/facebook ...

### Visual documentation

We created a custom widget for that, but we couldn't manage to play/pause video when scrolling the page.

```
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!
 
import 'package:video_player/video_player.dart';
import 'package:flutter/widgets.dart';
import 'package:visibility_detector/visibility_detector.dart';
 
class CustomVideoPlayer extends StatefulWidget {
  const CustomVideoPlayer({
    Key? key,
    this.width,
    this.height,
    this.path,
  }) : super(key: key);
 
  final double? width;
  final double? height;
  final String? path;
 
  @override
  _CustomVideoPlayerState createState() => _CustomVideoPlayerState();
}
 
class _CustomVideoPlayerState extends State {
  late VideoPlayerController _controller;
  bool isPlaying = false;
  bool isVisible = true; // Flag to indicate whether the video is visible
 
  @override
  void initState() {
    super.initState();
    final url = widget.path ?? '';
 
    _controller = VideoPlayerController.asset(url)
      ..initialize().then((_) {
        setState(() {});
      });
 
    _controller.addListener(() {
      if (_controller.value.isPlaying) {
        if (!isVisible) {
          // Pause the video if it is visible
          _controller.pause();
          isPlaying = false;
        }
      } else {
        if (isVisible && !isPlaying) {
          // Play the video if it becomes visible again
          _controller.play();
          isPlaying = true;
        }
      }
    });
 
    // Set looping to true
    _controller.setLooping(true);
    // Set volume to 0 for no sound
    _controller.setVolume(0);
  }
 
  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
 
  @override
  Widget build(BuildContext context) {
    return VisibilityDetector(
      key: const Key('customVideoPlayer'),
      onVisibilityChanged: (visibilityInfo) {
        final visible = visibilityInfo.visibleFraction > 0.9;
        setState(() {
          isVisible = visible;
        });
      },
      child: Container(
        width: widget.width,
        // height: widget.height,
        child: VideoPlayer(
          _controller,
        ),
      ),
    );
  }
}
```

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: Ios / Android
- Browser name and version: Chrome
- Operating system and version affected: Test Mode
```

**Comment by ishak-lm** [comment]
@hariprasadms Do you know when it will be added in FF? We need it to release our app. Or is there any way to fix it in our project ?

**Comment by ishak-lm** [comment]
Any update?

**Comment by ishak-lm** [comment]
@victoriahuang1 @hariprasadms Any update, really quick to fix...

**Comment by cheungysophie** [comment]
Would love this feature too!

**Comment by leighajarett** [comment]
Thanks for the feedback! We've added this to our backlog and hope to get to it soon. However, we are keeping this tracker specifically for reproducible bugs. Will be closing this issue but we will track in our internal system. Thanks!
