### ISSUE TITLE
Custom code editor is broken - It is still broken !!

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#211]
@jerco2 reported this issue
https://github.com/FlutterFlow/flutterflow-issues/issues/206

And it is still broken.

https://user-images.githubusercontent.com/5080329/206860001-f19a2864-9a60-485d-9df7-c4c1c08e6b25.mp4

**Comment by bulgariamitko** [comment]
Thanks for reporting this issue.

**Comment by agreaves** [comment]
Hi @thruthesky! This is happening because you had removed the "DO NOT MODIFY" lines within the function body. Make sure to not modify these as they mark the beginning and end of the function. Closing this issue for now.

**Comment by thruthesky** [comment]
@agreaves Yes, thank you.
