### ISSUE TITLE
Null errors when querying for document from Firebase using filter for custom function output

### ISSUE THREAD

**Issue by AvantN** [FlutterFlow/flutterflow-issues#2110]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get null errors when querying for a Firebase document with a specific field value integer equal to the integer output from custom function (using app state variable list).

I at first thought that it may be because the app state variable list name is the same as what is used in the argument name for the custom function, but this is not the case. I think the problem comes from the requirement of putting in argument within the custom function when I just want the custom function to pull from the existing designated app state variable list. I believe it may work if I did not need to input the variable through argument, and just have it within the code. However, flutterflow will not allow me to edit above the line.

### Expected Behavior

A document should be obtained that has the field value with the integer that the custom function outputs.

### Steps to Reproduce

1. create app state variable with a list of five integers between 1-10, in my case I named it "integerlistofcardsremoved".
2. create custom function as follows:

```
int? randomintegernotinlist(List? integerlistofcardsremoved) {
 
  final random = math.Random();
  int? randomNumber;
  do {
    randomNumber = random.nextInt(10) + 1;
  } while (randomNumber != null && integerlistofcardsremoved?.contains(randomNumber) == true);
  return randomNumber;
 
}
```

1. create a database of 10 documents in firestore, each document with a field of a unique integer between 1 and 10
2. create action to query database for document in firebase, using a filter to select for a field number equal to the output of the custom function

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fkPHluJdIsbRH7aXqdsEwtCYvQmE7becR0u5qEBM1GJPqBJkLd8z7MhdJbbyRSmNceWH8/W0e+srSk/DPE8ABCByJbYRyzKlTFjzMd3OiR6bXDcyKfEYlGcFUCU/FzpuZnyRQHMVvclFg7U+AN+TIVgHaO4O3DTMRJviZA97J+mybKwDCGn0Jg1ZSfCvr

### Context

I am creating a flash card app storing cards viewed/learned in the app state variable list. I want to query for documents (cards) randomly that are not seen/learned.

### Visual documentation

N/A

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0 - Flutter 3.13.7
- Platform: Mobile
- Browser name and version: Google Chrome Version 120.0.6099.129 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by ignalauret** [comment]
Hey @AvantN thanks for your report. The parameters of the custom functions that you create are defined by the settings that you placed on the right panel. If you remove the "integerlistofcardsremoved" parameter from the right panel, it will disapear from the function declaration.<br>I hope this was helpful, have a great day!
