### ISSUE TITLE
Duration value of a snack bar does not change if you select a different snack bar

### ISSUE THREAD

**Issue by krkxone** [FlutterFlow/flutterflow-issues#2112]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The duration value of a snack bar does not change if you select a different snack bar.

If you select a snack bar, click in the canvas (no focus on snack bar) and then click on another snack bar, the value adjusts correctly

### Expected Behavior

If you select a snack bar with a duration value of, for example, 1000 and then a snack bar with a value of 2000, the duration value should change and the range bar should adjust. However, this does not change.

### Steps to Reproduce

1. Create a new page
2. Add Action ShowSnackbar (Duration value: 1000)
3. Add Action ShowSnackbar (Duration value: 2000)
4. Switch between both actions, Duration value does not change

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KjMmAx5dOtbxK0Lr+KflR/ToXQz8iaIIeluxEe04cF7LoG7YAW/SkQE9WZ7yhdH03IE2GmnkJzM7HkszIN/Q3Cw+ZY4Rayc5bEjzzRnquM7nWBc6KeHx8GtpKC2qd0KS3qxUnFM1edEYb6lOQHefJfA7XJuf1IUdEBfj9CLnVjXPuQ0SLb3kNh1JWeC/v

### Context

The error causes me to give new snack bars incorrect values

### Visual documentation

![Screenshot 2024-01-07 at 14 24 09](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7b838c85-ed82-441e-bbe3-bdf90a371764/c0fa1e14-72e0-4577-97a1-e06c37eb05e7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YjgzOGM4NS1lZDgyLTQ0MWUtYmJlMy1iZGY5MGEzNzE3NjQvYzBmYTFlMTQtNzJlMC00NTc3LTk3YTEtZTA2YzM3ZWIwNWU3IiwiaWF0IjoxNzA3MTc4NzYwLCJleHAiOjMzMjc3NzM4NzYwfQ.WwU1VyQ6DdZEaDo44CkK-C-8B3DzJXDqESw62ecEThA "=1136x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 (Flutter Version: 3.13.7)
- Platform: Browser (Google Chrome)
- Browser name and version: Chrome 120.0.6099.199 (official build)
- Operating system and version affected: MacOS 14.2.1 (Sonoma)
```

**Comment by rzambroni** [comment]
Hi @krkxone, thanks for the report, we were able to replicate the problem and we will look into it. Apologies for the delay in the response.
