### ISSUE TITLE
There is no place where you can adjust the height or width of the chips in the ChoiceChips component

### ISSUE THREAD

**Issue by MathiasKalj** [FlutterFlow/flutterflow-issues#2113]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no place where you can adjust the height or width of the chips in the ChoiceChips component

### Expected Behavior

There is a place in the properties panel where I can adjust the height and width of chips in the ChoiceChips component

### Steps to Reproduce

1. Create project
2. Use ChoiceChips element
3. Try to set height or width

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kefl2ItPtbxJ+KqJccIwmik5JmY8aOYrlsFraC0ofbLoP4kIY/ykblJvQsu0TwlcIWCJo3wx7tXemvH1EOw3HE2YRoNzyLpuWxaXZECiV4SOEZeweG5/DdNPBUCj0ZmNrxRvPtRtSkFn2jqQJvKtXjbqO7LYIkcBAvq1IZCK2SrDX1iXc2URm05KZDPz

### Context

I want to change the height and width of my chips in my project to make them smaller.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/155903174/f0ef928c-1010-4849-9063-5fe2e6c1fd72)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/155903174/b8fa6368-6dfe-463f-bf69-9691216fcf54)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Desktop
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by MathiasKalj** [comment]
Basically I would be really happy if the ChoiceChips element had ChoiceChips properties or for example something like a dropdown element has 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/155903174/f61e602e-07c4-451b-b888-debb7a46d455)

**Comment by takashiff** [comment]
Hello, @MathiasKalj, thank you for the bug report. Unfortunately, this is a current limitation of the Choice Chips widget in FlutterFlow. If you'd like, I can always put in a feature request for you internally. I will mark this as closed for now, as this looks like a feature enhancement, rather than a bug. Thanks!
