### ISSUE TITLE
Parts of  the run/test mode screen not showing properly

### ISSUE THREAD

**Issue by OlafNekemanAmberflow** [FlutterFlow/flutterflow-issues#2114]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can only part of the mobile screen in test/run mode. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149107141/188274fd-3a7d-4321-a3a6-1dd2fbbeb2b9)

### Expected Behavior

Just the normal screen.

### Steps to Reproduce

Press the test mode. I am working on a Ubuntu 22.04 with google chrome browser.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl8nlw5NPn7xd1rqBKu9V9SUXH3o4R700sNobbxAjIoDoPJkUafelTEtVcNziT2NlKEWIrHIE/87lueLPKPoECwysRYRC1KhhWg7LfFi/aoSmPrWSPkdPEZhjfmaj35mvuBJ/KfpYLFZl7Fytfd+XaB7cNOL7Zwh9f6PHaOI=

### Context

Hinders development. I cannot see the snack bars for instance.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149107141/c93f4a19-939e-47c4-a60c-a7b375e10e00)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Ubuntu
- Browser name and version: Chrome
- Operating system and version affected: Ubuntu
```

**Comment by hariprasadms** [comment]
Hi @OlafNekemanAmberflow - Thank you for submitting the issue. The provided reproducible steps and issue details lack sufficient information to understand the issue. Page and query details are not mentioned, and it would be helpful to know the cache name used in the project. These details are essential for us to pinpoint the issue location in your project and initiate the investigation. Kindly add these details, and once they are included, we can begin investigating the issue. Thank you.

**Comment by hariprasadms** [comment]
Hi @OlafNekemanAmberflow - Please follow this - To expedite the issue triage, you can create a blank project and reproduce the issue in it, then share the bug report code. If creating a separate project is not feasible, another efficient approach is to create a separate page within your existing project and replicate the issue steps. By providing these details, we can swiftly pinpoint the issue and conduct a thorough investigation.

**Comment by OlafNekemanAmberflow** [comment]
Sorry, the title is from another bug issue I wanted to address. You can open any page from my project and the issue will show.

**Comment by hariprasadms** [comment]
Please update the issue title and also add bit more details.

**Comment by OlafNekemanAmberflow** [comment]
I would like to add more details but I do not what to add. It is quite simple, every page shows the inproper screens.

**Comment by OlafNekemanAmberflow** [comment]
There appears to be a 20px wide lane on the right side of the screen. And the bottom 50px of the screen are also whited out. They are clickable though.

**Comment by hariprasadms** [comment]
That is strange.  I am looking at it now. Meanwhile can you send the run mode link where you see these issue.

**Comment by OlafNekemanAmberflow** [comment]
https://app.flutterflow.io/debug/rRfHYyzlUE4Olw5p97zl

**Comment by hariprasadms** [comment]
Due to inactivity and no further follow the current issue is closed. If the problem persists, kindly initiate a new issue and provide all necessary information. Thank you.
