### ISSUE TITLE
There Are Some Problems in the Message Template

### ISSUE THREAD

**Issue by mackjames434** [FlutterFlow/flutterflow-issues#2116]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello. I added your ready templates to add chat feature to my app. But when I send a message, it does not appear. Also, it does not create a file in firebase. How can I solve this?

As far as I understand, it does not create messages in firebase. I followed all the steps given in the document, one by one. But there is such an error.

You can see my problem in the image and video below:

https://github.com/FlutterFlow/flutterflow-issues/assets/120029873/404d288a-736f-4b68-b783-d86f42a02fe5

<img width="310" alt="Ekran Resmi 2024-01-08 10 16 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/120029873/2ddca4fb-fbb4-46c7-8af8-b84ebfa27fd5">

### Expected Behavior

I want this system to work properly. I would appreciate it if you let me know where there is a mistake and what I should do.

### Steps to Reproduce

I installed the ready message template in Flutterflow. Then I made firebase settings. However, when I send a message to someone, the messages do not appear and it does not create messages in firebase. A chat is created but no message is created.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ekPLlw5NPm/Vc15SJK/lR/SoUJj96UIIFkdVxaAwjG7bxP+wqd+j+TGZuOLDid2xiPFmWgm01/tLKheP1CewoJhyJbqZHyap+ajvjVmCmaZiwO5e8REdBHdFUFXXFzpuZhh5vJrd2WHwt7XGMHeeyQjPsNpDMDG4nBP6IB9/7+3CfGXvCG30Jg1ZSfCvr

### Context

I want to send messages to my users through the application. But I can't do it because there is a problem.

### Visual documentation

<img width="310" alt="Ekran Resmi 2024-01-08 10 16 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/120029873/9406467f-d491-426b-bbd9-714008d2c81a">

https://github.com/FlutterFlow/flutterflow-issues/assets/120029873/cd38bb93-658f-460d-8950-e13a591a515c

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Android
```

**Comment by hariprasadms** [comment]
Hi @mackjames434 -  Due to issue inactivity, I presume the issue has been resolved for you. Therefore, I am closing the issue. If you encounter any further problems or have additional concerns, feel free to reopen the issue. Thank you!
