### ISSUE TITLE
List is set and not empty - Build fail, bool? cannot be assigned to bool

### ISSUE THREAD

**Issue by olivierb24** [FlutterFlow/flutterflow-issues#2118]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using 'list is set and not empty' on an array (from a linked supabase table) I get an error saying that a type bool? cannot be assigned to a variable of type bool.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/8a22e254-fc14-47e3-a56e-7b6e51a2f1ea)

### Expected Behavior

Should be able to return a bool if the array is set and not empty.

### Steps to Reproduce

1. Create a page with a any widget
2. Link a Supabase project
3. Pull an array from Supabase
4. Add conditional visibility based on array
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/80aa4402-fce9-4f0b-a4de-1cfe62f73028)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl+fqx85Nrt9c+KX+Y8JaqGAvM0MfWOdEket+EA0hfLWtP4kqYOLBSxNLYteDYApEAmeGmlID09LlufDPJe46GwWcc5xG1L5XQTyVIU6jVarSDs2SZEYmI/NgflSk1JjUkxV4PbNiSloQw02ADPCNG3qCf9qOYwx5e6fDbOY=

### Context

Cannot dynamically display widgets

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/8b97a570-ece8-43bd-a7f0-fac408692f3c)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/0c644757-4902-4678-87b2-0226d6251712)

### Environment

```markdown
- FlutterFlow version: 3.13.17
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.131 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by olivierb24** [comment]
This behavior is similar to issue #1965

**Comment by wenkaifan0720** [comment]
This should be fixed in our next update. Thanks!

**Comment by vitoras** [comment]
> This should be fixed in our next update. Thanks!

Hi, can you tell when next update will roll out?
