### ISSUE TITLE
App freezes when running 'Close Dialog, Drawer, etc.' action

### ISSUE THREAD

**Issue by almantas88** [FlutterFlow/flutterflow-issues#2119]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running the action 'Close Dialog, Drawer, etc.' and there is no Dialog open the app freezes.

### Expected Behavior

Running the action 'Close Dialog, Drawer, etc.' when there is no Dialog should do nothing.

### Steps to Reproduce

Create a button with an action 'Close Dialog, Drawer, etc.' and press the button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ok/Lqx8pgod9c7ZPpbcAwmikRHGYlU4ZN0utHbAE3GKnNG4gIZfTBXE9uOP25dkFYMGaKhT4d/vuNm9z1Cfc6KU2qc6Z/wZd+TBaXez+QR6aYPartR0FUGshjfxGz16S3ghBSCLdtWXgA2Vy6JeyUZATaQ+PjIFgvIM+ZNpjXmAfuQ0SLb3kNh1JWeC/v

### Context

I always have to check if there is a dialog, to run this action. Which seems irrelevant, the action should do nothing.

### Visual documentation

Nothing to show.

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: iOS and Android
- Browser name and version: Chrome
- Operating system and version affected: iOS and Android
```

**Comment by aemelyanovff** [comment]
@almantas88 I'm afraid that's just how Flutter works and there's little we can do about it. [The code](https://api.flutter.dev/flutter/widgets/Navigator/pop.html) to close a bottom sheet or a dialog is the same as the code to navigate back.
