### ISSUE TITLE
Textfield custom filter regexp bug

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#212]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When using a custom regexp on textfield filter (digits and one dot) should let the user enter a value

## Current behavior (required)
the textfields value is cleared when user enters a dot.

## To Reproduce (required)
1. Create new page
2. Add textfield widget
3. Set filter to custom regexp
4. enter: ^(\d*\.)?\d*$
5. Click Run
6. Observe that textfield value deleted when entering a dot.

### Bug Report Code
ITESz/Hqx89gruEG+bn+Ke16hQMjNlx7bZAnktV+WRMhNZesE4ocfffSQFNLYtfmYwt2PGeLhkU1w9LOudj1C/UqKRWBRb5x/7wFH1yjEA8=

## Context (required)
Trying to let the user enter a custom amount (of money)

## Your environment

* Version of FlutterFlow used: v.3.0 released on 10th dec
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version:  Chrome latest version
* Operating system and version (desktop or mobile): desktop, Windows 11

**Comment by agreaves** [comment]
Thanks for the report! This issue is now fixed!
