### ISSUE TITLE
Failed Step: Install pods & New Flutter update has broken all previous working actions

### ISSUE THREAD

**Issue by MyTechAgent** [FlutterFlow/flutterflow-issues#2120]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to deploy to apple and all my functions are now broken after the most recent flutter upgrade.

### Expected Behavior

errors should be green and I should be able to deploy to apple.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/36d6af38-b29a-418a-9e00-5e2745033214/4ede5e7a-9fc4-4e69-8f31-41d7d42d8299?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNmQ2YWYzOC1iMjlhLTQxOGEtOWUwMC01ZTI3NDUwMzMyMTQvNGVkZTVlN2EtOWZjNC00ZTY5LThmMzEtNDFkN2Q0MmQ4Mjk5IiwiaWF0IjoxNzA3MTc4NjAzLCJleHAiOjMzMjc3NzM4NjAzfQ.1uTWvhYnZnPdz-9aV06Hw5RtIoJSTuXhDXa-9CC1FLQ)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ba2151d7-df51-44b7-9f82-39f80a0be28e/f55df470-5116-4225-ac57-ea222c88b811?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYTIxNTFkNy1kZjUxLTQ0YjctOWY4Mi0zOWY4MGEwYmUyOGUvZjU1ZGY0NzAtNTExNi00MjI1LWFjNTctZWEyMjJjODhiODExIiwiaWF0IjoxNzA3MTc4NjAzLCJleHAiOjMzMjc3NzM4NjAzfQ.PYjGpjiihDX_LzRaILEFNF0ZxydPG_I3B4uZaLBzRHY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0e0224bf-3eb7-4a89-a416-2b9897b68586/aa026859-31a6-40d6-8906-10484467eb8d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZTAyMjRiZi0zZWI3LTRhODktYTQxNi0yYjk4OTdiNjg1ODYvYWEwMjY4NTktMzFhNi00MGQ2LTg5MDYtMTA0ODQ0NjdlYjhkIiwiaWF0IjoxNzA3MTc4NjAzLCJleHAiOjMzMjc3NzM4NjAzfQ.LGExBiLC4tm45wI84DAEDVRtQtriaIR0Yby0WKzoYBU)

### Steps to Reproduce

1. try to create a new action using the following code.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/120c2197-8c4d-4bb1-a367-47998f8dcc9a/7935e195-b251-4200-9efb-d9d8d135dad8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMjBjMjE5Ny04YzRkLTRiYjEtYTM2Ny00Nzk5OGY4ZGNjOWEvNzkzNWUxOTUtYjI1MS00MjAwLTllZmItZDlkOGQxMzVkYWQ4IiwiaWF0IjoxNzA3MTc4NjAzLCJleHAiOjMzMjc3NzM4NjAzfQ.jYUjDPJtnREmCeTrUt6YyOv3lb0P2C6XeLY-5ru5Pjc)

// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

Future convertCentsToDollars(int cents) async {
// convert cents to dollars
double dollars = cents / 100;
return dollars;
}

1. Try to deploy to apple.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OiPHqw4VOxLhY1rrUKcZR/T0UKUA1bZZM0NZxSgE2G73NG4gIZfTBXE9uOP25dglqOGeakn8zzN7Im9z1EsYnBw+bRr5CzqoJaw7jUnqgSrahPqW8TkB+GshnJhWv1qan3yJ7D7d2c14E6jqLN/O8cB/ZJpz7NnodAcqaMt/XmAfuQ0SLb3kNh1JWeC/v

### Context

I was going to run campaigns and do my first production release for my FF app.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/478679f4-3666-4f90-8b79-f88ac5cce478/9c9ec8d1-dbaf-4b07-9882-905aef4270f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80Nzg2NzlmNC0zNjY2LTRmOTAtOGI3OS1mODhhYzVjY2U0NzgvOWM5ZWM4ZDEtZGJhZi00YjA3LTk4ODItOTA1YWVmNDI3MGY2IiwiaWF0IjoxNzA3MTc4NjAzLCJleHAiOjMzMjc3NzM4NjAzfQ.xeXXl1l3vYvDaScK-qV2am6rFdD0SUXanEYjJoyiCqg)

Deployment Error:

Codemagic Deploy Output
Failed Step: Install pods

Command exited with code 128: git fetch --tags
Standard error: error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: expected flush after ref listing

Resolving dependencies...

* \\\_fe_analyzer_shared 61.0.0 (65.0.0 available)
* \\\_flutterfire_internals 1.3.16
* analyzer 5.13.0 (6.3.0 available)
* archive 3.4.10
* args 2.4.2
* async 2.11.0
* auto_size_text 3.0.0
* boolean_selector 2.1.1
* cached_network_image 3.2.1 (3.3.1 available)
* cached_network_image_platform_interface 1.0.0 (4.0.0 available)
* cached_network_image_web 1.0.1 (1.1.1 available)
* characters 1.3.0
* checked_yaml 2.0.3
* cli_util 0.4.1
* clock 1.1.1
* cloud_firestore 4.13.1 (4.14.0 available)
* cloud_firestore_platform_interface 6.0.5 (6.1.0 available)
* cloud_firestore_web 3.8.5 (3.9.0 available)
* cloud_functions 4.5.8 (4.6.0 available)
* cloud_functions_platform_interface 5.5.11
* cloud_functions_web 4.6.11
* collection 1.17.2 (1.18.0 available)
* convert 3.1.1
* cross_file 0.3.3+7 (0.3.3+8 available)
* crypto 3.0.3
* csslib 1.0.0
* csv 5.0.1 (5.1.1 available)
* cupertino_icons 1.0.6
* dropdown_button2 2.3.9
* equatable 2.0.5
* fake_async 1.3.1
* ffi 2.1.0
* file 7.0.0
* file_picker 6.1.1
* file_selector_linux 0.9.2+1
* file_selector_macos 0.9.3+3
* file_selector_platform_interface 2.6.1 (2.6.2 available)
* file_selector_windows 0.9.3+1
* firebase_auth 4.15.2 (4.16.0 available)
* firebase_auth_platform_interface 7.0.8 (7.0.9 available)
* firebase_auth_web 5.8.11 (5.8.13 available)
* firebase_core 2.24.2
* firebase_core_platform_interface 5.0.0
* firebase_core_web 2.10.0
* firebase_messaging 14.7.8 (14.7.10 available)
* firebase_messaging_platform_interface 4.5.17 (4.5.18 available)
* firebase_messaging_web 3.5.17 (3.5.18 available)
* firebase_performance 0.9.3+8
* firebase_performance_platform_interface 0.1.4+16
* firebase_performance_web 0.1.4+16
* firebase_storage 11.5.5 (11.6.0 available)
* firebase_storage_platform_interface 5.1.3
* firebase_storage_web 3.6.17
* flip_card 0.7.0
* flutter 0.0.0 from sdk flutter
* flutter_animate 4.1.1+1 (4.4.0 available)
* flutter_blurhash 0.7.0 (0.8.2 available)
* flutter_cache_manager 3.3.1
* flutter_card_swiper 6.0.0
* flutter_google_places 0.3.2 from git [https://github.com/fluttercommunity/flutter_google_places](https://github.com/fluttercommunity/flutter_google_places) at fa3484
* flutter_launcher_icons 0.13.1
* flutter_lints 3.0.0 (3.0.1 available)
* flutter_localizations 0.0.0 from sdk flutter
* flutter_native_splash 2.3.1 (2.3.9 available)
* flutter_plugin_android_lifecycle 2.0.17
* flutter_secure_storage 8.0.0 (9.0.0 available)
* flutter_secure_storage_linux 1.2.0
* flutter_secure_storage_macos 3.0.1
* flutter_secure_storage_platform_interface 1.0.2
* flutter_secure_storage_web 1.1.2
* flutter_secure_storage_windows 2.1.1 (3.0.0 available)
* flutter_spinkit 5.2.0
* flutter_stripe 9.4.0 (10.0.0 available)
* flutter_stripe_web 4.4.0 (5.0.0 available)
* flutter_test 0.0.0 from sdk flutter
* flutter_web_plugins 0.0.0 from sdk flutter
* font_awesome_flutter 10.6.0
* freezed_annotation 2.4.1
* from_css_color 2.0.0
* glob 2.1.2
* go_router 7.1.1 (13.0.1 available)
* google_api_headers 1.6.0 (3.7.0 available)
* google_fonts 4.0.3 (6.1.0 available)
* google_identity_services_web 0.2.2 (0.3.0+2 available)
* google_maps_webservice 0.0.20-nullsafety.5
* google_sign_in 6.1.5 (6.2.1 available)
* google_sign_in_android 6.1.20 (6.1.21 available)
* google_sign_in_ios 5.6.4 (5.7.2 available)
* google_sign_in_platform_interface 2.4.2 (2.4.5 available)
* google_sign_in_web 0.12.1 (0.12.3+2 available)
* html 0.15.4
* http 0.13.6 (1.1.2 available)
* http_parser 4.0.2
* image 4.0.17 (4.1.3 available)
* image_picker 1.0.4 (1.0.7 available)
* image_picker_android 0.8.8 (0.8.9+2 available)
* image_picker_for_web 3.0.1 (3.0.2 available)
* image_picker_ios 0.8.8+2 (0.8.9 available)
* image_picker_linux 0.2.1+1
* image_picker_macos 0.2.1+1
* image_picker_platform_interface 2.9.1 (2.9.3 available)
* image_picker_windows 0.2.1+1
* intl 0.18.1 (0.19.0 available)
* iregexp 0.1.1 (0.1.2 available)
* js 0.6.7 (0.7.0 available)
* json_annotation 4.8.1
* json_path 0.6.2 (0.7.0 available)
* lints 3.0.0
* logging 1.2.0
* lottie 2.7.0
* matcher 0.12.16 (0.12.16+1 available)
* material_color_utilities 0.5.0 (0.8.0 available)
* maybe_just_nothing 0.5.3
* meta 1.9.1 (1.11.0 available)
* mime 1.0.4
* mime_type 1.0.0
* nested 1.0.0
* octo_image 1.0.2 (2.0.0 available)
* package_config 2.1.0
* package_info_plus 4.2.0 (5.0.1 available)
* package_info_plus_platform_interface 2.0.1
* page_transition 2.1.0
* path 1.8.3 (1.9.0 available)
* path_provider 2.0.14 (2.1.2 available)
* path_provider_android 2.0.25 (2.2.2 available)
* path_provider_foundation 2.2.2 (2.3.1 available)
* path_provider_linux 2.1.11 (2.2.1 available)
* path_provider_platform_interface 2.0.6 (2.1.2 available)
* path_provider_windows 2.1.7 (2.2.1 available)
* petitparser 5.4.0 (6.0.2 available)
* pigeon 11.0.1 (16.0.0 available)
* platform 3.1.4
* plugin_platform_interface 2.1.6 (2.1.8 available)
* pointycastle 3.7.3
* provider 6.0.5 (6.1.1 available)
* pub_semver 2.1.4
* quiver 3.2.1
* rfc_6901 0.1.1 (0.2.0 available)
* rxdart 0.27.7
* shared_preferences 2.2.2
* shared_preferences_android 2.2.1
* shared_preferences_foundation 2.3.4
* shared_preferences_linux 2.3.2
* shared_preferences_platform_interface 2.3.1 (2.3.2 available)
* shared_preferences_web 2.2.1 (2.2.2 available)
* shared_preferences_windows 2.3.2
* sign_in_with_apple 4.3.0 (5.0.0 available)
* sign_in_with_apple_platform_interface 1.0.0
* sign_in_with_apple_web 1.0.1
* sky_engine 0.0.99 from sdk flutter
* source_span 1.10.0
* sprintf 7.0.0
* sqflite 2.2.6 (2.3.0 available)
* sqflite_common 2.5.0+2
* stack_trace 1.11.0 (1.11.1 available)
* stream_channel 2.1.1 (2.1.2 available)
* stream_transform 2.1.0
* string_scanner 1.2.0
* stripe_android 9.4.0 (10.0.0 available)
* stripe_ios 9.4.1 (10.0.0 available)
* stripe_js 3.2.0 (3.3.0 available)
* stripe_platform_interface 9.4.0 (10.0.0 available)
* synchronized 3.1.0 (3.1.0+1 available)
* term_glyph 1.2.1
* test_api 0.6.0 (0.7.0 available)
* timeago 3.2.2 (3.6.0 available)
* typed_data 1.3.2
* universal_io 2.2.2
* url_launcher 6.1.10 (6.2.3 available)
* url_launcher_android 6.0.27 (6.2.2 available)
* url_launcher_ios 6.1.4 (6.2.3 available)
* url_launcher_linux 3.0.6 (3.1.1 available)
* url_launcher_macos 3.0.7 (3.1.0 available)
* url_launcher_platform_interface 2.1.2 (2.3.1 available)
* url_launcher_web 2.1.0 (2.2.3 available)
* url_launcher_windows 3.0.8 (3.1.1 available)
* uuid 4.2.2 (4.3.1 available)
* vector_math 2.1.4
* video_player 2.8.1 (2.8.2 available)
* video_player_android 2.4.10 (2.4.11 available)
* video_player_avfoundation 2.5.1 (2.5.5 available)
* video_player_platform_interface 6.2.1 (6.2.2 available)
* video_player_web 2.1.2 (2.1.3 available)
* watcher 1.1.0
* web 0.1.4-beta (0.4.0 available)
* win32 5.1.1 (5.2.0 available)
* xdg_directories 1.0.4
* xml 6.3.0 (6.5.0 available)
* yaml 3.1.2
  Changed 189 dependencies!
  Analyzing dependencies
  cloud_firestore: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  cloud_functions: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  firebase_auth: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  firebase_core: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  firebase_messaging: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  firebase_performance: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  firebase_storage: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
  Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

CocoaPods 1.14.3 is available.
To update use: `gem install cocoapods`

For more information, see [https://blog.cocoapods.org](https://blog.cocoapods.org) and the CHANGELOG for this version at [https://github.com/CocoaPods/CocoaPods/releases/tag/1.14.3](https://github.com/CocoaPods/CocoaPods/releases/tag/1.14.3)

Downloading dependencies
Installing AppAuth (1.6.2)
Installing BoringSSL-GRPC (0.0.24)
Installing DKImagePickerController (4.3.4)

\\\[!\\\] Error installing DKImagePickerController
\\\[!\\\] /opt/homebrew/bin/git clone [https://github.com/zhangao0086/DKImagePickerController.git](https://github.com/zhangao0086/DKImagePickerController.git) /var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/d20240109-1779-usmktx --template= --single-branch --depth 1 --branch 4.3.4

Cloning into '/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/d20240109-1779-usmktx'...
remote: Internal Server Error
fatal: unable to access '[https://github.com/zhangao0086/DKImagePickerController.git/](https://github.com/zhangao0086/DKImagePickerController.git/)': The requested URL returned error: 500

Build failed :|
Step 6 script `Install pods` exited with status code 1

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows
```

**Comment by MyTechAgent** [comment]
Thank you errors have gone away. testing deployment to apple now.

**Comment by hariprasadms** [comment]
Hi @MyTechAgent - Great to see the errors resolved! It's common to encounter issues during Flutter upgrades. Please close the issue as you can proceed further. Thanks

**Comment by MyTechAgent** [comment]
thank you closing now, deployment successful. Legend.
