### ISSUE TITLE
XMLHttpRequest error when testing an API

### ISSUE THREAD

**Issue by jhune23** [FlutterFlow/flutterflow-issues#2122]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to make a Post API call request on my project but I am getting an XMLHttpRequest error.
I have tried making the same test using Postman and Swagger and got a status 200 and can see the full json response.

### Expected Behavior

FF should be able to display the json response from the API.

### Steps to Reproduce

1. On the API Calls section, click Add button
2. Click Create API Call
3. Input API Call Name
4. Select Post on the Method Type
5. Input API URL
6. Add Content-Type: application/json as Headers
7. Input the Json Body
8. On the Response & Test tab click Test API Call button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

cant get a bug report code from API Calls

### Context

I cannot proceed with the completion of this project due to this error.

### Visual documentation

![FF error](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bff45c28-ef26-42ee-8035-cdcb63a46630/599774ca-ec56-45ae-b3ce-b1473e5fc8e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZmY0NWMyOC1lZjI2LTQyZWUtODAzNS1jZGNiNjNhNDY2MzAvNTk5Nzc0Y2EtZWM1Ni00NWFlLWIzY2UtYjE0NzNlNWZjOGU5IiwiaWF0IjoxNzA3MTc4NTU1LCJleHAiOjMzMjc3NzM4NTU1fQ.coDAYT-qhKeUEha6Pk2Nf9aFQG1uIpmWA9flFpAgXec "=572x")

![postman test](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/561ac467-42e8-4405-babb-bd5a309f71eb/1713c0c5-c772-4303-b5cc-0ed40fb07a05?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NjFhYzQ2Ny00MmU4LTQ0MDUtYmFiYi1iZDVhMzA5ZjcxZWIvMTcxM2MwYzUtYzc3Mi00MzAzLWI1Y2MtMGVkNDBmYjA3YTA1IiwiaWF0IjoxNzA3MTc4NTU1LCJleHAiOjMzMjc3NzM4NTU1fQ.9Msw3pFSpmXGYSaYLh8o00anYUHSX_4pZ7A87gLVbJ8 "=854x")

### Additional Info

![FF error](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e09ecc66-616a-46aa-90d6-6bd483cf36d9/7aa753ef-7fad-4a6d-bff1-aabefaec4179?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMDllY2M2Ni02MTZhLTQ2YWEtOTBkNi02YmQ0ODNjZjM2ZDkvN2FhNzUzZWYtN2ZhZC00YTZkLWJmZjEtYWFiZWZhZWM0MTc5IiwiaWF0IjoxNzA3MTc4NTU1LCJleHAiOjMzMjc3NzM4NTU1fQ.VGi9aaYsrSrJUUwP5oi9F4782dBT3p0F16t8iuSuVpY "=572x")

![postman test](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/feea927f-a602-42df-bd51-35eaa5d26cb2/5853c84a-80d9-49e3-99e0-a9ff2ac2ef06?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZWVhOTI3Zi1hNjAyLTQyZGYtYmQ1MS0zNWVhYTVkMjZjYjIvNTg1M2M4NGEtODBkOS00OWUzLTk5ZTAtYTlmZjJhYzJlZjA2IiwiaWF0IjoxNzA3MTc4NTU1LCJleHAiOjMzMjc3NzM4NTU1fQ.bTW4FuuBuhSrwUvsE1bA_SBMyif5a0p3pRYzyk0tzLY "=854x")

### Environment

```
FlutterFlow version: FlutterFlow v4.0 released January 5, 2024
                       Flutter version is 3.13.7
Platform: Web
Browser name and version: 120.0.6099.199
Operating system and version affected: Windows 11
```

**Comment by jhune23** [comment]
Dear colleagues,

BTW I also added the following code on my deployed app for the CORS issue
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136065646/9f97dc18-a2e2-465f-815d-ebdfd1c9d759)

I also have these settings on the Advanced Settings:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136065646/7f1c42f5-f34c-49d2-95b8-9395aef94462)

But I'm still getting the same reported issue.

**Comment by rzambroni** [comment]
Hello @jhune23, thank you for your report, and please accept our apologies for the delayed response. Are you still encountering the issue with the API call? If so, while we understand that you cannot provide the bug code directly to the API call, would it be possible for you to include the bug code on the home page of a blank application where this call is implemented? This would enable us to examine the specific issue more closely, greatly assisting our troubleshooting efforts.

**Comment by rzambroni** [comment]
Closing this ticket due to inactivity. If you are still experiencing this issue please feel free to re-file it. Thanks a lot!
