### ISSUE TITLE
Page Tree items move (instead of open) when clicked

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#2123]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On about 50% of occasions when I click on a component in a page / component  tree that is in a folder, it will appear to vanish instead of open. It actually moves somewhere else, but it i hard to find. I control z but it is wasting time. 

### Expected Behavior

To simply open the page or component

### Steps to Reproduce

Click on component in nested foddered page tree. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YMS8+kMxJVXemndGNEL1n8/WMxwNbXhePAA+UrCxKcRbpGz4d6VBXdcE2jVK6wEc/pQXJCAdpJJVyw34m3rRRCIfpfSl4a1Dque+TJYz3tGL7MIkUeDcj+Jp3XnGOqQ0SLb3kNh1JWeC/v

### Context

Slows me down. 

### Visual documentation

Go to my project click on Createcomponent under createPage

### Additional Info

None

### Environment

```markdown
- FlutterFlow version: 3.13.17
- Platform:Windows
- Browser name and version:Chrome
- Operating system and version affected: Windows 12
```

**Comment by hariprasadms** [comment]
Hi @charliefabley - Thank you for submitting the issue. I am unable to reproduce it on my end. Could you please provide a brief video demonstrating the exact issue you are facing? Thanks.

**Comment by charliefabley** [comment]
[items moving.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13890269/items.moving.zip)
Had to zip it, it was too big. You will see at the beginning it seems not to happen, and then there is a slight movement of the mouse and it moves the item (way too sensitive in my opinion) , and then at the end there is no visible movement of the mouse at all yet the items still vanish / move. Sometimes I will do a mouse click 4 or 5 times and control z it back until finally it is highlighted.

**Comment by hariprasadms** [comment]
@charliefabley - Thanks for providing additional details. Your expectation seems to align with an improvement to the current design. However, given the broader usage of the feature, the current design is working as intended. We appreciate your feedback and will certainly consider it for future enhancements. Thanks!
