### ISSUE TITLE
Flutter Flow AiGen Fail

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#2124]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't use AiGen, it keeps giving "Bad State:" on the element.

How can I used it?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10706610/539356d3-a0f5-4485-abe4-e1c445ea9539)

### Expected Behavior

generate page component

### Steps to Reproduce

1.use aigen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

null

### Context

null

### Visual documentation

null

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by andrewf65432** [comment]
Me too. I am on the free version and have not used this feature before so it still says '5/5 page generations left.'

**Comment by leowolter** [comment]
> Me too. I am on the free version and have not used this feature before so it still says '5/5 page generations left.'

I was too. Upgraded to paid version but the same error happens.

**Comment by aHagouel** [comment]
+1

**Comment by aemelyanovff** [comment]
It was fixed in the last update. Please let me know if the issue persists.
