### ISSUE TITLE
Retrieving timedatez from Supabase doesn't convert to local

### ISSUE THREAD

**Issue by jpollone** [FlutterFlow/flutterflow-issues#2125]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have 2 dates in a Supabase table. One date is type `timestampz` and the other is non-recommended `timestamp`.

![screenshot 2024-01-09 1200](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/72b4dec9-fde3-4c78-b6af-f685c63f593a/f8aea87c-f689-4c64-966d-23d3f36e6601?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MmI0ZGVjOS1mZGUzLTRjNzgtYjZhZi1mNjg1YzYzZjU5M2EvZjhhZWE4N2MtZjY4OS00YzY0LTk2NmQtMjNkM2YzNmU2NjAxIiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.OcnCVuUkEMyTIsVBVgUZ9_s9f8x0U0aJXpMi8yZ2bjY)

When I set each using CurrentTime, both appear to set properly.

![screenshot 2024-01-09 1203](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b2865cb7-2e31-428e-94df-a531c21876c2/8098904d-3dcb-4679-8e56-0ca2d21becd0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMjg2NWNiNy0yZTMxLTQyOGUtOTRkZi1hNTMxYzIxODc2YzIvODA5ODkwNGQtM2RjYi00Njc5LThlNTYtMGNhMmQyMWJlY2QwIiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.M_NW_C15TaE4AdJlLO0lLQ-VwGPcy6o68sL9lcEwHZQ)

![screenshot 2024-01-09 1202](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2214fcb9-2b57-4303-94bf-0048c9972ede/ae93d43c-cc62-4b97-957e-1ff87c023a79?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMjE0ZmNiOS0yYjU3LTQzMDMtOTRiZi0wMDQ4Yzk5NzJlZGUvYWU5M2Q0M2MtY2M2Mi00Yjk3LTk1N2UtMWZmODdjMDIzYTc5IiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.weCsYLZpOgx6oO0uJdv_h7gFjJJYi1yf242iHtNv970)

However, when I retrieve the datetime there is an issue converting the UTC time to local.

![screenshot 2024-01-09 1213](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/93b8450a-2b89-4dde-a9fa-1a1b2dcfea12/c20c81fc-0489-4013-b438-862f74f11db0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85M2I4NDUwYS0yYjg5LTRkZGUtYTlmYS0xYTFiMmRjZmVhMTIvYzIwYzgxZmMtMDQ4OS00MDEzLWI0MzgtODYyZjc0ZjExZGIwIiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.V3AnnD2tbskRbPauXgmn9skFfUGuVk-LfaZ6Ep7DPpQ)

### Expected Behavior

The built-in formatting helper leads the developer to believe that the timedate will return to local time. Just as CurrentTime sets via the local time.

![screenshot 2024-01-09 1159](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/92fbf8de-ff34-429a-9fc8-df38fed485d3/e82242b4-e7b6-4628-a4b2-d43b25f8dd9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MmZiZjhkZS1mZjM0LTQyOWEtOWZjOC1kZjM4ZmVkNDg1ZDMvZTgyMjQyYjQtZTdiNi00NjI4LWE0YjItZDQzYjI1ZjhkZDljIiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.0HLIgCFExSA_29FKLH9KQaWu7sp0ujWnwJ7a1KpaVSk)

### Steps to Reproduce

1. Create a Supabase table with timestamp and timestampz columns
2. Create a page, column
3. Add a Query to the column
4. Add two text widgets and set 1 to refer to the timestamp column and the other to the timestampz
5. Set DateTime Format to M/d h:mm a

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8rluJNJm7RF7qXXbe5FqykWQ2Y3TL07ttYbZxUjIuPtBJh/Z8+lblJCUumhdGlhHFaZoEEypdL8i+PpNewpIQusbIRAzJAJbw7MQXq8Sr6qC5a8QUZ5JJ9jCW6e4aaK3BIlFLNuW3gcwDuqF9itHyjZN5+/Zwh9f6PHaOI=

### Context

When I use the proper and recommended timestampz I need to wrap the datetime in function to convert to local first.

![screenshot 2024-01-09 1214](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/046076dc-e04e-49ed-8258-68e9286091b6/522e24e6-421b-4e2c-a949-d34ef6d7985e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNDYwNzZkYy1lMDRlLTQ5ZWQtODI1OC02OGU5Mjg2MDkxYjYvNTIyZTI0ZTYtNDIxYi00ZTJjLWE5NDktZDM0ZWY2ZDc5ODVlIiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.1eyFZiH8BJpkLWGhhWl6JhPaTYeY_dCXr0ZOh7iViDU)

### Visual documentation

![screenshot 2024-01-09 1213](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a108befc-1b69-4831-8edb-0f1dfde3303c/d0187f36-7052-47b1-a907-f70ba5922cc4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMTA4YmVmYy0xYjY5LTQ4MzEtOGVkYi0wZjFkZmRlMzMwM2MvZDAxODdmMzYtNzA1Mi00N2IxLWE5MDctZjcwYmE1OTIyY2M0IiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.IWkD-dqr7NxjgATeFBNrozj9KUASzIhnAxAZ__LhWws)

![screenshot 2024-01-09 1214](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9ec40a2e-6250-4574-bf89-12875562ca74/65886b64-db23-4164-b731-219ad46a2c1c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZWM0MGEyZS02MjUwLTQ1NzQtYmY4OS0xMjg3NTU2MmNhNzQvNjU4ODZiNjQtZGIyMy00MTY0LWI3MzEtMjE5YWQ0NmEyYzFjIiwiaWF0IjoxNzA3MTc4NTM3LCJleHAiOjMzMjc3NzM4NTM3fQ.aQCOqPpz5To3J8ZFH9-79a-f6NoY3ZbxDhrLVRrsF-k)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: macOS
- Browser name and version: Edge 120.0.2210.121
- Operating system and version affected: macOS 14.2.1
```

**Comment by Xarjik** [comment]
This caused me so much pain for a few hours, thought I was going crazy and doing something wrong somewhere!

Can't wait for the fix!

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. After the next update FlutterFlow will convert timestamps from Supabase to local time.
