### ISSUE TITLE
Push Notification Issue - Europe West 1 region

### ISSUE THREAD

**Issue by darwishx** [FlutterFlow/flutterflow-issues#2127]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Push Notification sent to 0 Devices.
After deploying the notifications function to firebase same region as the firestore and Firebase project (europe-west1) the manual and user triggered push notifications are not working.

![Screenshot 2024-01-10 121742](https://github.com/FlutterFlow/flutterflow-issues/assets/99121252/6036c03a-b3d5-4949-9d0f-3c0e6fb67370)

### Expected Behavior

Push notification to be sent to devices that run the application. 
The app runs on Web and Android APK version is installed on a device but still same behaviour

### Steps to Reproduce

1. Create project and Firestore database in eur3 (europe-west1) region
2. Confirgure the project Firebase advanced settings to have the default for the cloud function region to be europe-west1
3. Follow FlutterFlow documentation to set up the Push Notification: https://docs.flutterflow.io/settings-and-integrations/app-settings/push-notifications#add-push-notifications
4. Use Manual Push Notification 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Keeps failing to generate a Bug report code 

### Context

Need the Push notification to be sent to users in case of emergency as the app is responsible for notifying users of danger nearby

### Visual documentation

![Screenshot 2024-01-10 131033](https://github.com/FlutterFlow/flutterflow-issues/assets/99121252/0adb5c59-a11e-48bc-9945-c5f77a782125)
![Screenshot 2024-01-10 121742](https://github.com/FlutterFlow/flutterflow-issues/assets/99121252/bf4f432b-8d66-45bc-8b4c-381064e45bf5)

### Additional Info

Flutterflow project: insavior-rgfsug

### Environment

```markdown
- FlutterFlow version: v4.0 Flutter - 3.13.6 
- Platform: Web & Android
- Browser name and version: Chrome & Edge
- Operating system and version affected: Android
```

**Comment by darwishx** [comment]
Hi,
Is there any update here?

**Comment by aemelyanovff** [comment]
@darwishx Does it work when you deploy it to another region?

Either way, I suggest reaching out to FlutterFlow support - I believe this issue is specific to your project (FlutterFlow and/or Firebase). In the meantime, check the log of the `sendPushNotificationsTrigger` function to see if there's anything helpful there.

**Comment by darwishx** [comment]
Hi @aemelyanovff ,
Sorry for the late reply. I was doing some tests and investigations on the logs of the cloud function. But I get that it is successful. I assume that the initialization of the fcmAddTocken is not for some reason done (as there was no call for that cloud function from the app). I have already tried to deploy in other regions in europe and also create a new project in europe-west 1 and europe-west3 but I am getting the same behaviour. (I have tried to make a custom push notification with onesignal and that worked fine, but flutterflow push notification is not working).

Nevertheless, I have already reached the support and they are the one that told me to write a ticket in Github. The issue is not resolved even after contacting them and writing here. Please reconsider the status update you made.

**Comment by davidflutterflow** [comment]
@darwishx Hi, Hope you doing well, Could you please provide the email ( Flutterflow account ) you reached out to support with?

**Comment by darwishx** [comment]
@davidflutterflow Hi,
This is the email used:
ahmed.darwish@naqlx.com


Also I have checked logs in cloud functions and apparently addFCMToken function is the one that has errors when it is triggered (I will share the error details later today).
