### ISSUE TITLE
Buggy behavior while editing layer name in widget tree

### ISSUE THREAD

**Issue by terronce** [FlutterFlow/flutterflow-issues#2129]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I double-click to edit a name, I'm able to begin typing... however after two characters are entered the field looses focus and saves the name as only two characters. I'm unable to add more characters to the name.

### Expected Behavior

I should be able to complete the name edit and either click out of the field, or hit enter to save the change.

### Steps to Reproduce

1. Double click the layer 
2. Type to edit the name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Okufl0It2od8B7c/+KcJV9SU5JU84RIZMl9YbSREgGJfNGJsIf877SFFWX+mmd2xqJVv9rGYJzPuMvd7pEeQHAzGZf65l1pZyaDnyJUKRRr60PpCWSEFABfNnDkuV4buJnhBSB7NuSU4M2zv6e/K+TizAQ67SDHoeRP+JB97P+mCgAi+6Xn0Jg1ZSfCvr

### Context

I'm learning how to use FlutterFlow from you YouTube tutorials. I'm trying to rename a layer and can't.

### Visual documentation

<img width="302" alt="Screenshot 2024-01-10 at 12 23 20 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142747791/a5f1cd06-fd7b-4747-90c4-75337ebd3f6a">

### Environment

```markdown
- FlutterFlow version: v4.0 
- Platform: Web
- Browser name and version: Chrome 120.0.6099.199
- Operating system and version affected: MacOS Sonoma 14.1.1
```

**Comment by takashiff** [comment]
Marking as closed since the issue has been fixed
