### ISSUE TITLE
Big issue and a lot of issues with the new Code editor(Please return the old one until all issues fixed)

### ISSUE THREAD

**Issue by Habbouche** [FlutterFlow/flutterflow-issues#213]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Hi I have a custom action that have a functions to read the numbers and do some work and returns a list of strings, before the last update everything was amazing, I wrote the code and run it and run the app fine.

## Current behavior (required)

Hi I have a custom action that have a functions to read the numbers and do some work and returns a list of strings, before the last update everything was amazing, I wrote the code and run it and run the app fine.
now it gone crezy, everytime I edit the code, it remove the tick from the function return type as list, this causing the whole app to stop working as I was assinging the return list of string to local state list.
now without the tick an erro shown that I can't assign normal string to a list of string variable.
Please Please please just revert the code editor updates as a lot of people facing issues 😭
## To Reproduce (required)

// Automatic FlutterFlow imports
import '../../flutter_flow/flutter_flow_theme.dart';
import '../../flutter_flow/flutter_flow_util.dart';
import '../actions/index.dart'; // Imports other custom actions
import '../../flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:math' as math;
import 'package:js/js.dart';

List<String> assignParameters(
  int melt5pCounter1687Value,
  int megChcoCounter1383Value,
  int megDrmCounter1385Value,
  int megRdVtCounter1380Value,
  int uni10Counter1386Value,
  int stdRdVtCounter1487Value,
  int mdRdVtCounter1488Value,
  int mdDrmCounter1489Value,
  int stdChcoCounter1490Value,
  int mdChcoCounter1491Value,
  int stdDrmCounter1492Value,
  int uniCounter1396Value,
  int stdBluCounter2008Value,
  int stdStrCake2009Value,
  int stdCrotCounter2010Value,
  int mdLotsCounter2011Value,
  int mdVnlaCounter2012Value,
  int mdChcoVtCounter2013Value,
  int crdwltCounter2111Value,
  int lnchFerCounter1873Value,
  int lnchChcoCounter1872Value,
  int lnchLotsCounter1871Value,
  int lnchRdVtCounter1870Value,
) {
  /*
  melt5pCounter1687Value.toString();
  megChcoCounter1383Value.toString();
  megDrmCounter1385Value.toString();
  megRdVtCounter1380Value.toString();
  uni10Counter1386Value.toString();
  stdRdVtCounter1487Value.toString();
  mdRdVtCounter1488Value.toString();
  mdDrmCounter1489Value.toString();
  stdChcoCounter1490Value.toString();
  mdChcoCounter1491Value.toString();
  stdDrmCounter1492Value.toString();
  uniCounter1396Value.toString();
  stdBluCounter2008Value.toString();
  stdStrCake2009Value.toString();
  stdCrotCounter2010Value.toString();
  mdLotsCounter2011Value.toString();
  mdVnlaCounter2012Value.toString();
  mdChcoVtCounter2013Value.toString();
  crdwltCounter2111Value.toString();
  lnchFerCounter1873Value.toString();
  lnchChcoCounter1872Value.toString();
  lnchLotsCounter1871Value.toString();
  lnchRdVtCounter1870Value.toString();
*/

  // final apiParameters = <String>[];

  // List<String> apiParameters = List<String>.empty(growable: true);
  // var apiParameters = ['1687#1'];

  List<String> apiParameters = ['hello'];
  apiParameters.removeAt(0);

  if (melt5pCounter1687Value != 0) {
    // melt5pCounter1687Value.toString();
    [//apiParameters.toList()](https://apiparameters.tolist%28%29/);
    apiParameters.add('1687#$melt5pCounter1687Value'); [//as](https://as/) List<String>?;
    // apiParameters.toList();
  }

  if (megChcoCounter1383Value != 0) {
    apiParameters.add('1383#$megChcoCounter1383Value');
  }

  if (megDrmCounter1385Value != 0) {
    apiParameters.add('1385#$megDrmCounter1385Value');
  }

  if (megRdVtCounter1380Value != 0) {
    apiParameters.add('1380#$megRdVtCounter1380Value');
  }

  if (uni10Counter1386Value != 0) {
    apiParameters.add('1386#$uni10Counter1386Value');
  }

  if (stdRdVtCounter1487Value != 0) {
    apiParameters.add('1487#$stdRdVtCounter1487Value');
  }

  if (mdRdVtCounter1488Value != 0) {
    apiParameters.add('1488#$mdRdVtCounter1488Value');
  }

  if (mdDrmCounter1489Value != 0) {
    apiParameters.add('1489#$mdDrmCounter1489Value');
  }

  if (stdChcoCounter1490Value != 0) {
    apiParameters.add('1490#$stdChcoCounter1490Value');
  }

  if (mdChcoCounter1491Value != 0) {
    apiParameters.add('1491#$mdChcoCounter1491Value');
  }

  if (stdDrmCounter1492Value != 0) {
    apiParameters.add('1492#$stdDrmCounter1492Value');
  }

  if (uniCounter1396Value > 0) {
    apiParameters.add('1396#$uniCounter1396Value');
  }

  if (stdBluCounter2008Value != 0) {
    apiParameters.add('2008#$stdBluCounter2008Value');
  }

  if (stdStrCake2009Value != 0) {
    apiParameters.add('2009#$stdStrCake2009Value');
  }

  if (stdCrotCounter2010Value != 0) {
    apiParameters.add('2010#$stdCrotCounter2010Value');
  }

  if (mdLotsCounter2011Value != 0) {
    apiParameters.add('2011#$mdLotsCounter2011Value');
  }

  if (mdVnlaCounter2012Value != 0) {
    apiParameters.add('2012#$mdVnlaCounter2012Value');
  }

  if (mdChcoVtCounter2013Value != 0) {
    apiParameters.add('2013#$mdChcoVtCounter2013Value');
  }

  if (crdwltCounter2111Value != 0) {
    apiParameters.add('2111#$crdwltCounter2111Value');
  }

  if (lnchFerCounter1873Value != 0) {
    apiParameters.add('1873#$lnchFerCounter1873Value');
  }

  if (lnchChcoCounter1872Value != 0) {
    apiParameters.add('1872#$lnchChcoCounter1872Value');
  }

  if (lnchLotsCounter1871Value != 0) {
    apiParameters.add('1871#$lnchLotsCounter1871Value');
  }

  if (lnchRdVtCounter1870Value != 0) {
    apiParameters.add('1870#$lnchRdVtCounter1870Value');
  }
  return apiParameters;
}
1.
2.
3.
4.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

https://user-images.githubusercontent.com/81159190/206871174-7d8d4234-3cf7-47fc-9cb6-c03f4235594e.mp4

**Comment by wenkaifan0720** [comment]
Hi @aemelyanovff. Do you know what is causing this issue? When the user saves the custom function, the `List` checkbox for the return type gets unchecked.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. There are a few problems with the code preventing FF from parsing it correctly:
1. An action should return a `Future`.
2. When you return a list it should specify the type of elements.

So if you want your custom action to return a list of strings, it should look like this:

```
Future<List<String>> assignParameters(...) async {
  ...
  return apiParameters;
}
```

You can use the green button to generate boilerplate code for your parameters:
![Screen Shot 2022-12-12 at 2 01 07 PM](https://user-images.githubusercontent.com/92294640/207131734-1755c1fc-e6ff-4b04-807c-055ee57fa7bd.png)


I'm a little surprised that that code worked before to be honest. 

We are updating our code parser to be more forgiving in cases like this.
