### ISSUE TITLE
PDF viewer wrong full height behaivor

### ISSUE THREAD

**Issue by ArmandoGomez** [FlutterFlow/flutterflow-issues#2130]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is a short usage of the feature behaivor when implementing PDFviewer component. It is great to have the option to change from vertical slide to horizontal but if you maximize the size of the pdfviewer to whole screen it will **auto-add gap between pages** , while the default pdfviewer features doesnt have gaps between pages than means that you should be able to determine if you want to stack or show listed pages of the pdf without incrementing gap.

### Expected Behavior

Besides horizontal scroll option you should have the stacked option and keep default pdf viewer behaivior if this option is not selected showing PDF's as listed pages vertically.

### Steps to Reproduce

1. Create a page
2. Create a Container and make it full height and full width
3. Insert pdfViewer and make it full height and full width
4. You will see an stacked view instead a vertical listed view

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMmBw891pbxH1s/AacZviio5Jn59Ro0RkMJBaCssCIjzCLMqY8mkUFtUcO2/Y1ZqJ2CWgT4X/Mr0udnQFcEoBwiCQaZA1ZNUUjqXIUSlMIyMPpS3b0R6Ad9XN0yG5LuRqx55ALBYWGwD3zuyffO+Sg7cNLL2IUUwQ+a4XdeK2SrDX1iXc2URm05KZDPz

### Context

I want a listed pdfview in my project

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9a0c46f2-f9ea-4d4e-9255-954304dc3ed4/7a4eccfc-c7ae-47ca-93f0-5bd13e94c37a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YTBjNDZmMi1mOWVhLTRkNGUtOTI1NS05NTQzMDRkYzNlZDQvN2E0ZWNjZmMtYzdhZS00N2NhLTkzZjAtNWJkMTNlOTRjMzdhIiwiaWF0IjoxNzA3MTc4NDk0LCJleHAiOjMzMjc3NzM4NDk0fQ.4T0oWCMQh5Bj2H9NJ-OjFZbXgBQ7V_wBxg9Q9eCSVAA)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7a2e3857-1323-4317-a969-2336e41c7134/a9fea0ef-0baa-4f55-be1c-d02d6bee82bf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YTJlMzg1Ny0xMzIzLTQzMTctYTk2OS0yMzM2ZTQxYzcxMzQvYTlmZWEwZWYtMGJhYS00ZjU1LWJlMWMtZDAyZDZiZWU4MmJmIiwiaWF0IjoxNzA3MTc4NDk0LCJleHAiOjMzMjc3NzM4NDk0fQ.kx38q-GpXqrPH238H4SQ8yuZmX_Kr_o6FFlYl2Z9Cdk)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0.3
- Platform: MacOS Desktop
- Browser name and version: Chrome 120.0.6099.109
- Operating system and version affected: macOS Sonoma 14.1.2
```

**Comment by wenkaifan0720** [comment]
Hi @ArmandoGomez. Could you try setting the width of the PDF viewer widget to something less than 100% width? Seems to make the PDF display in listview mode after I made this change.

**Comment by ArmandoGomez** [comment]
HI @wenkaifan0720 it looks to have the same behaivior for me, im still getting a big gap between pages instedad of being listed immediately in the bottom on each other.

**Comment by takashiff** [comment]
Hi @ArmandoGomez, I've taken a look at your project and it looks like the pdfViewer widget being used is misconfigured. Please let me know if you are still encountering this issue with the proper configurations. Thanks

**Comment by hariprasadms** [comment]
Based on the in activity, we presume that the issue has been resolved for you. Therefore, we are closing the issue. If the problem persists, please feel free to reopen the issue with any additional details. Thank you.
