### ISSUE TITLE
"View" button of action block not works

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#2132]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"View" button of action block not works.
Only in the action flow editor, it works.

### Expected Behavior

"View" button of action block works.

### Steps to Reproduce

1. Press "view" button of action block editor.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ok8rl7cpOj7xK7aqJbsFFmSQXJkd7R78/lcpBZywgfZzzBLN/fPfQPxFDTemrYHxUPmacp14J+MGKkuD2U8EBHwWZbL5O/qt6Vg3/VTq5R5eTF7qeOXFCI+dbFXKOyJ+vugpNCPZ2WHNg6mCLfemvTjPsJrLzO0Q8Sq/LZO4=

### Context

Annoying

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5666acff-4d73-40fd-936f-cc2639e53367/443f9517-abe6-4f93-a557-c4351362bfbe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NjY2YWNmZi00ZDczLTQwZmQtOTM2Zi1jYzI2MzllNTMzNjcvNDQzZjk1MTctYWJlNi00ZjkzLWE1NTctYzQzNTEzNjJiZmJlIiwiaWF0IjoxNzA3MTgyMzE3LCJleHAiOjMzMjc3NzQyMzE3fQ.Bryo6j1Swu_uS6lsORcckxOcdvLbwafeg63k-KXk7Wk "=293x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: V4.0
- Platform:Mac
- Browser name and version:Chrome newest
- Operating system and version affected: NaN
```

**Comment by takashiff** [comment]
Hi @idea-garage, thank you for the bug report. This issue has been fixed recently, and should be out within the next update. I apologize for the delayed response, and thank you for your patience.
