### ISSUE TITLE
Copy Variable action doesn't show Save Changes confirmation on a modified condition being copied and instead closes the condition editor losing changes

### ISSUE THREAD

**Issue by yoohoomedia** [FlutterFlow/flutterflow-issues#2133]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Bring up a 'Set from Variable' popup editor window from property UI panel (ie: Fill Color for a container) and set in a new Single Condition (but don't Save it yet).
2. Choose 'Copy Variable' from the (3-dot) menu icon.
3. The popup editor window now closes following by a snack bar message stating variable is copied.

The condition you have created earlier is lost and you have not been given the opportunity to save it.

### Expected Behavior

If the condition is uncommitted, and you choose to the copy variable, then the editor should remain and the copy action still takes place.
If the condition is unaltered then continue as it's current behaviour and close the editor window.

### Steps to Reproduce

1. Create a new Project with skip setup.
2. Open the properties for the 'Column' widget in the blank page.
3. Enable 'Conditional' switch (for example)
4. Create a 'Single Condition' (any values would) but for this test we set First Value to Global Property->Screen Width and the Second Value to 100 (don't save the change.
5. Now, choose 'Copy Variable' from the menu icon in the 'Set from Variable' ui.

The 'Set from Variable' popup editor disappears and the new condition you entered is lost.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l6oZhosBK+KrfYOxWqCIRM0MfWOdEket+EA0hfIytPaQUZfSlahFLYtezS25EBE2GrDgG+dL2vtmSLO06JRaqfpxYzpRXQQ7wWn6nRrqTCriKP0QlHfhTIBCMyLWnoSMlFNN1dHAc1F+uOfCrG3qCf9qOYwx5e6fDbOY=

### Context

A series of widgets resembling a segmented control where each segment has variable colour attributes (border, fill, text colour) based on a common condition for that segment. Since there are multiple segments that multiple conditions are candidates for a copy variable with a minor alteration on the next segment widget.

Current steps

 1. One must create the condition for widget1 - fill color
 2. Save the Change
 3. Go back into that condition
 4. Copy the Variable
 5. Go to border color and paste variable
 6. Go to widget2 -> fill color
 7. paste variable, alter the condition
 8. Save the condition
 9. Go back into the condition
10. Copy the variable
11. Then proceed to the border color, and so on.

If the 'copy variable' action detects an uncommitted condition and does NOT close the window but still copies the variable, the following steps would be required:

1. One must create the condition for widget1 - fill color
2. Copy the Variable
3. Save condition
4. Go to border color and paste variable
5. Go to widget2 -> fill color
6. paste variable, alter the condition
7. Copy the variable
8. Save the condition
9. Then proceed to the border color, and so on.

### Visual documentation

![2024-01-12_17-53-45](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/adf544f2-11e8-437a-86dd-59088e4088f0/f9eb8363-658a-428b-9fc6-0b2f0eb28a87?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZGY1NDRmMi0xMWU4LTQzN2EtODZkZC01OTA4OGU0MDg4ZjAvZjllYjgzNjMtNjU4YS00MjhiLTlmYzYtMGIyZjBlYjI4YTg3IiwiaWF0IjoxNzA3MTc4NDUzLCJleHAiOjMzMjc3NzM4NDUzfQ.Z2BML4teE2qhfULs3gpU38_ZzW781OjxCV6Vs2RC214)

[https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/c7f8a4ba-082b-4b73-8474-35aa0f7e0428](https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/c7f8a4ba-082b-4b73-8474-35aa0f7e0428)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Brave 1.61.116
- Operating system and version affected: macOs Ventura 13.6.3
```

**Comment by ignalauret** [comment]
Hey @yoohoomedia thanks for your report. I was able to replicate your steps, and I'm going to send a feature request to our technical team.<br>Thanks for your help, have a great day!
