### ISSUE TITLE
Label references word 'PostgresRow' rather than 'Supabase Row' in Bottom Sheet dismiss Action return value Data Types.

### ISSUE THREAD

**Issue by yoohoomedia** [FlutterFlow/flutterflow-issues#2134]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is more of a legacy label typo (I believe).

In 'Bottom Sheet' Dismiss action for a Component, the Data Type list contains the label 'PostgresRow' when it out likely ought to say 'Supabase Row'.

![2024-01-11_16-22-19](https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/ffc52c10-0d58-43e5-a96b-98f88a3928dd)

### Expected Behavior

Label should read 'Supabase Row'

### Steps to Reproduce

1) Create a new Component
2) Create an Action -> Bottom Sheet Dismiss
3) Set 'Has Value' to TRUE
3) Go to Data Types'
   The Data Type list contains PostgresRow rather than 'Supabase Row'

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlcmBy8pgrtdY15DUcfpvtDw5KVgjauYslupxeEg3GKKsG7YMS8+kMxJVXemndGNEL06Whj80+c3IuOPyA+UrH0udGIRRyaVhFw7xWT+7VbKkPbWSY0RtL5lJJVyg3MHUoApCHNNpV3Am702IDN+QazDbJrKxO0Y0Rfn/BIbVngKrQ0SLb3kNh1JWeC/v

### Context

It doesn't affect me.

Selecting PostgresRow functions as if it is 'Supabase Row'

### Visual documentation

Flutter UI Property Page
![2024-01-11_16-22-19](https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/d176ae3f-816c-46d9-ad36-8c81751ed285)

DataType List
![2024-01-11_16-35-06](https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/f519445c-2ef6-47d4-afad-4d0a1b6b0696)

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Web
- Browser name and version: Brave 1.61.116
- Operating system and version affected: macOs Venture 13.6.3
```

**Comment by victoriahuang1** [comment]
Hi @yoohoomedia , thanks for the report. This should be fixed upon the next deploy.
