### ISSUE TITLE
FlutterFlow reverting to a specific version is not working. 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [FlutterFlow/flutterflow-issues#2135]
I've encountered significant challenges with our project and have sought assistance from KRINO (Technical Support). Despite providing them with detailed information and videos, I'm still struggling. I've been working on this for about a full day now, facing issues particularly after implementing a new action. It's possible that my slow internet connection and a failing code analyzer contributed to the problem, but even reverting to an earlier version didn't resolve the issue. Reverting back to earlier version is not saving as expected. 

Originally, the action appeared to be correctly implemented according to standards, but it suddenly led to numerous errors in my project. When I reverted to a previous version, these errors disappeared, and I even saved this as a new version to proceed with my work. Although it operates correctly, it fails to synchronize with GitHub, indicating errors. Refreshing my browser causes the errors to reappear with all other changes I made after specific version(functional one), and I'm now dealing with approximately 200 errors, making resolution a complex task. I've identified that the absence of an 'Authenticated User' reference in the app might be causing these issues or may be only issue is reverting back is not being saved properly. Despite clearing the browser cache and attempting various solutions, the problem persists. I suspect it might be related to FirebaseAuth, as that's a component I've been using in the action.

We have already sent an email with the video link to your support team and they have already shown that to your technical team. 

Organising a video call might help better to fix this issue or show you again what is happening. I won't take more than 2 minutes to explain it. This is my email address if you want to reach out chmuhammadadil7@gmail.com. 

_Originally posted by @ch-muhammad-adil in https://github.com/FlutterFlow/flutterflow-issues/issues/1303#issuecomment-1884824434_

**Comment by ch-muhammad-adil** [comment]
@hariprasadms  @sbis04 ?? Can you please look at this matter on priority, we got no fix until now on this matter. We are in serious urgency and trying to reach out again and again. Kindly help us, we are really stuck.

**Comment by ch-muhammad-adil** [comment]
I have attached video for the problem.. please check this out now. 

https://github.com/FlutterFlow/flutterflow-issues/assets/8264639/1ef848a2-ad76-4de3-9d8b-396b8c5ba6d9


https://github.com/FlutterFlow/flutterflow-issues/assets/8264639/b839fd69-8e92-43e5-a27d-18ab1f71846b

**Comment by ch-muhammad-adil** [comment]
Sorry to say but it is a bit disappointing situation that after a lot of back and forth tries/communications technical team did nothing here in this regard. 

We are now able to resolve problem by using **FLUTTERFLOW DESKTOP APPLICATION**, where we have applied same steps and it has worked for us.

**Comment by leighajarett** [comment]
So sorry that you waited so long without a response! I can understand why you're disappointed. 

Just to confirm, this issue is now resolved?
