### ISSUE TITLE
Date Type variables are not immediately instantiated in Page and Component States upon Widget creation causing null access crash

### ISSUE THREAD

**Issue by yoohoomedia** [FlutterFlow/flutterflow-issues#2137]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I create a Date Type with a field containing a default value.

I add this Date Type as a variable to an App State, Page State and Component State.

In App State the variable is accessible upon page initialisation, but the other two variables are not.

Examining the code, it seems that in Page State and Component State models the Data Type is not instantiated 'until a field is updated', therefore prior to that those variables are uninitiated.
Conditions in particular expect initialised data types when referencing values therefore they will immediately cause a crash of the page on load.

Workaround - is to create an On Page Load action that updates a single field for all variables of Data Type.

### Expected Behavior

I expect variables of type Date Type in a Page and Component State to be instantiated upon widget creation, as is done for App State.

### Steps to Reproduce

From the Sample Bug Reject:

1. Click the 'Click to crash' button to crash the app.

From a New Project:

1. Create a New Data Type called 'MyDataType'.
2. Add a Boolean field to this Data Type called 'myDefaultBool' with a Default value of False.
3. On the HomePage create Page App State called 'myPageVar' of type MyDataType'
4. Add a Container to the HomePage with a condition on the Background Fill Color, the condition:
   * If myPageVar->myDefaultBool == true than return RED colour otherwise report a BLUE colour.

The crash would be on the condition as it tries to reference the Data Type with a non-null assertion operator while that property is null.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l6oZhosAD+KqBccIwnSkWCUMdXOczitVEew4bCIj4BJoUevTBPxdCTcCzaH5XMGeapEgdw82LudjDNPEBGzGBGLpPyatybBPPbF2tMMmrEqqoXXdfEdljC26155msnhJACLFvWVVm3DumI/KtHj+Cf9qOYwx5e6fDbOY=

### Context

Uninstantiated variables in the Page or Component State leads to an unexpected null exceptions (page crash) for conditions that attempt to access the properties of that Date Type. .

### Visual documentation

![2024-01-15_13-10-44](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d63dd41e-f163-4974-b9f1-a85c177ec9e4/b4932aa5-9f69-4b52-bd92-b2899e437aaa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNjNkZDQxZS1mMTYzLTQ5NzQtYjlmMS1hODVjMTc3ZWM5ZTQvYjQ5MzJhYTUtOWY2OS00YjUyLWJkOTItYjI4OTllNDM3YWFhIiwiaWF0IjoxNzA3MTc4NDIyLCJleHAiOjMzMjc3NzM4NDIyfQ.aSFjCKs9Npgd6cc3e10FgS3_ewtqktg6xumJsjCUHk4)

The instantiation of Data Types structures (ie: MyTypeStruct) is different between AppState and the other two States.

FFAppState performs an actual instantiation of **MyTypeStruct \\\\\\\_AppStateVar = MyTypeStruct()**.

```
class FFAppState extends ChangeNotifier {
  static FFAppState _instance = FFAppState._internal();
 
  factory FFAppState() {
    return _instance;
  }
 
  FFAppState._internal();
 
  static void reset() {
    _instance = FFAppState._internal();
  }
 
  Future initializePersistedState() async {}
 
  void update(VoidCallback callback) {
    callback();
    notifyListeners();
  }
 
  MyTypeStruct _AppStateVar = MyTypeStruct(); // <-- appState
  MyTypeStruct get AppStateVar => _AppStateVar;
  set AppStateVar(MyTypeStruct _value) {
    _AppStateVar = _value;
  }
 
  void updateAppStateVarStruct(Function(MyTypeStruct) updateFn) {
    updateFn(_AppStateVar);
  }
}
.
.
.
```

HomePageModel (Page State) and MyComponentModel (Component State) delay an instantiation until an updateData call however the initial state of the variable is uninitialised (**MyTypeStruct? compStateDT;**).

```
class MyComponentModel extends FlutterFlowModel {
  /// Local state fields for this component.
 
  MyTypeStruct? compStateDT;
  void updateCompStateDTStruct(Function(MyTypeStruct) updateFn) =>
      updateFn(compStateDT ??= MyTypeStruct());**
 
  /// Initialization and disposal methods.
 
  void initState(BuildContext context) {}
 
  void dispose() {}
 
  /// Action blocks are added here.
 
  /// Additional helper methods are added here.
}
```

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: FlutterFlow v4.0 released January 5, 2024 Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Brave 1.61.116
- Operating system and version affected: macOS Ventura 13.6.3
```

**Comment by yoohoomedia** [comment]
Can someone from Flutter team please look into this? It's a rather serious issue as any widget within a Component or Page cannot reference any of the properties for a Data Type with out crashing the page.

ie: You create a Contact Data Type with default values. In a New Contact Editor component you add a variable into its App State of that Contact Data Type. Widgets in that component set its initial values from the content of that Data Type.
This will crash the page as the Data Type during the build() call for those widgets is null. It becomes more challenging when inner custom components require parameters to exist.

Can the FF team see whether DataTypes could be instantiated in the same way as they are in AppState?

**Comment by yoohoomedia** [comment]
A possible solution could be:

Enable a 'Nullable' checkbox for the State Variable UI for Data Type variables, similar to the one provided for the other types such as String, Image Path and so on.

This 'Nullable' option can be enable by default for backwards compatibility, while disabling it would force the Data Type to be instantiated on Component/Page construction.

![2024-01-26_15-24-51](https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/4a1e4328-a686-48cd-a1ec-422bdbb0cf1f)

**Comment by yoohoomedia** [comment]
Is there any update on this issue, please?

**Comment by fiveminutejob** [comment]
Is there any update on this issue, please?

**Comment by ignalauret** [comment]
Hey @yoohoomedia thanks for your report. I was able to replicate the issue following your steps. I will send a ticket to the Technical team. <br>Have a great day!

**Comment by fiveminutejob** [comment]
5+ Months of pain finally resolved, thank you.

Philip Martin

Innovation Engineer

Tel: 07716 030942

Email: ***@***.***

Web: FiveMinuteJob.com

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Five Minute Job. If you are not the intended recipient
of this email, you must neither take any action based upon its contents,
nor copy or show it to anyone.



Please contact the sender if you believe you have received this email in
error.
