### ISSUE TITLE
MuxBroadcast Widget Bug

### ISSUE THREAD

**Issue by ambience-kim** [FlutterFlow/flutterflow-issues#2138]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding the MuxBroadcast widget to the screen, an error occurs.
![스크린샷 2024-01-11 오후 5 23 20](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/1fd833eb-7d97-47e9-b78b-88592ebe71dd)

![스크린샷 2024-01-11 오후 5 23 38](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/54730a3e-eb35-4c3d-85ae-2b4409702ae1)

### Expected Behavior

No errors should occur.

An error occurs simply by adding the MuxBroadcast Widget to the screen.
I have completed both Mux and Firebase setup.

![스크린샷 2024-01-11 오후](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/4f54ae7a-6d72-414f-bbf7-168423d2bc1d)

![스크린샷 2024-01-11 오후 5 26 42](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/ca4f78a5-4894-4dca-ba8b-7ad5bded6104)

### Steps to Reproduce

1. Create a new screen.
2. Add the MuxBroadcast widget.
3. Run
4. An error occurred

![스크린샷 2024-01-11 오후 5 27 14](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/9700ffad-79d6-442a-8de0-27a4e8358d55)

![스크린샷 2024-01-11 오후 5 26 51](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/204f6918-7d3a-4fc0-b3aa-3be6c875d4fd)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oz8jc34VIsdtb+KrcKMJVnjw5JlgjbbxM08FHd0o3F7nNG4gIZfTBXE9uOP25dghiIk6khjg1/sLJm9z1Dfo3PSWdQYs++rhcVQLxcFqtb8W0PbqCbXN+GshnIFCiyqSNvx1AHO5pSE4D3FyMOfPLcDLvO7L1NTAFDfm1Kp/XrgfuQ0SLb3kNh1JWeC/v

### Context

Disability of MuxBroadcast widget

### Visual documentation

![스크린샷 2024-01-11 오후](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/bef970b5-558c-4fea-a12f-6171ca9ad69f)
![스크린샷 2024-01-11 오후 5 26 42](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/84088bf7-a991-4a69-a548-001ddb735b11)
![스크린샷 2024-01-11 오후 5 27 14](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/f48e0cad-aa7a-433d-a6af-4a73ee243a7b)
![스크린샷 2024-01-11 오후 5 26 51](https://github.com/FlutterFlow/flutterflow-issues/assets/140410622/368f2ee6-4b8b-443c-b611-a9d2d6826c38)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web Browser
- Browser name and version:Chrome Version 120.0.6099.199 (x86_64)
- Operating system and version affected: macOS Venture Ver. 13.6.3
```

**Comment by hariprasadms** [comment]
Hi @ambience-kim - The Mux widget is not compatible with web deployment; it works exclusively on mobile devices. The error you're encountering in debug run mode is expected since this mode eventually operates in a web context.

**Comment by ambience-kim** [comment]
I couldn't find anything in the documentation that says it doesn't work on the web.
https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/muxbroadcast

It seems like the document needs to be updated as soon as possible.
