### ISSUE TITLE
White box on Tab bar

### ISSUE THREAD

**Issue by karolpaw85** [FlutterFlow/flutterflow-issues#2139]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

HI, i have this strange white artefact box on my services tab:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/45e3f363-5f42-4395-9d64-5a1140c4f2d4/541d9714-ee28-41d2-b06c-91b8a82ce1db?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NWUzZjM2My01ZjQyLTQzOTUtOWQ2NC01YTExNDBjNGYyZDQvNTQxZDk3MTQtZWUyOC00MWQyLWIwNmMtOTFiOGE4MmNlMWRiIiwiaWF0IjoxNzA3MTc4Mzc4LCJleHAiOjMzMjc3NzM4Mzc4fQ.ALuKtYn6saXG1zsI0qTagC2Yjl-8Ls-K80M6RV5JdWk)

it also appears on rentals when you are on rentals tab. the two middle ones are ok.

### Expected Behavior

I expect to see Services tab name.

### Steps to Reproduce

1. go to the app, use: [karol1@email.com](mailto:karol1@email.com), 123456 password
2. click account button
3. my add
4. you should see the problem.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no code

### Context

obviously users will not see the tab name

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/adc0bc22-a61a-4711-983f-221e1f1f0e14/b259ff35-e6ad-4f57-9c99-7eeda9dac5f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZGMwYmMyMi1hNjFhLTQ3MTEtOTgzZi0yMjFlMWYxZjBlMTQvYjI1OWZmMzUtZTZhZC00ZjU3LTljOTktN2VlZGE5ZGFjNWYyIiwiaWF0IjoxNzA3MTc4Mzc4LCJleHAiOjMzMjc3NzM4Mzc4fQ.Cy3A_wEEXXkGrkHNk821AUpuMFyXGtRY_Njpr-jkMG8)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform:Flutterflow
- Browser name and version:edge 120.0.2210.121
- Operating system and version affected: win11
```

**Comment by karolpaw85** [comment]
Hi, this issue is still present, let me know what can i do to proceed.

**Comment by leighajarett** [comment]
Sorry for the delay, we're working on it @karolpaw85!

**Comment by hariprasadms** [comment]
Hi @karolpaw85 - Has the issue been resolved? With the latest FlutterFlow updates, I've been unable to replicate the problem. Everything seems to be working smoothly. Since there haven't been any follow-ups on the issue, I assume it's no longer exists in the project. However, if the problem persists, I recommend creating a new issue with a blank project to reproduce the issues. Thanks

**Comment by karolpaw85** [comment]
Indeed, the problem is gone. Thanks!
