### ISSUE TITLE
Display Name on App Icon

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#214]
Non-English like Korean has much meaning on a character.
It is asking to put minimum of 4 characters. But 2 characters are more than enough in Korean language. The 4 character restriction is really no good.

Can you make it two or three?

<img width="487" alt="image" src="https://user-images.githubusercontent.com/5080329/206916283-0ea16b28-7711-4ebd-ab08-43ac70e5260d.png">

**Comment by bulgariamitko** [comment]
FF team can argue this is a feature request, but I think this is a bug considering the many languages out there and in this case as @thruthesky stated that there is no need for more then 2 chars in Korean language for example.

**Comment by wenkaifan0720** [comment]
I agree.

**Comment by wenkaifan0720** [comment]
This settings has been updated in main. I'll close this issue for now.
