### ISSUE TITLE
Youtube player sound fades out

### ISSUE THREAD

**Issue by metaflowdev** [FlutterFlow/flutterflow-issues#2143]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When playing a youtube video on our iOS app, the sound sometimes fades out quickly without reason while the video keeps on playing. Stopping the video and starting it again turns the sound back on. This appears to be a systemic issue, either caused by the Youtube player widget or Youtube or an incompatibility of the player with a recent change in Youtube API/widgets.

### Expected Behavior

The video should play with sound on.

### Steps to Reproduce

1. Add a Youtube player to the project
2. Build on iOS
3. Play the video (maybe you will need a couple of tries)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/Hq25dgoddD1s7bbcBvlSc4C0d8TL0nuO0ad0gdGJDyC5k+Z8jBUFtUOLDgT3w3MU6jnnoX/Mr6iPzlJvACKRWtbLp6+KgJVQvidz6lMLKSCL63b3Z8IJpmfGHC4aWr3RN5ObBvcnNl3F+Ie+eXdA7XQ5DFOWwzH+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

Our customers have complained to us about this and we could reproduce it right away. Since this was not discovered in earlier testing, maybe this was introduced by a youtube api change or a new iOS version.

### Visual documentation

This video shows simply how the sound fades out:
[https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/b46e137a-60aa-4b22-811d-c73ea27ebca5](https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/b46e137a-60aa-4b22-811d-c73ea27ebca5)

This video shows how the sound fades out and immediately comes back when the video is briefly stopped and then restarted:
[https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/f3e14b6b-c69a-4be6-9c82-7769c949c062](https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/f3e14b6b-c69a-4be6-9c82-7769c949c062)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 (December 2023)
- Platform: Apple
- Browser name and version: None
- Operating system and version affected: iOS 17.2.1
```

**Comment by metaflowdev** [comment]
Hi, is there any news on this issue? We are getting multiple customer complaints about this.

@hariprasadms @wenkaifan0720

**Comment by metaflowdev** [comment]
Hi, is there any news on this issue?

@hariprasadms @wenkaifan0720

**Comment by metaflowdev** [comment]
Hi, we just released a new version with the latest FlutterFlow version and the issue still persists.

**Comment by wenkaifan0720** [comment]
Hi @metaflowdev. Are these issues happening on real devices or emulators as well? What iOS version is the device running on? And could you please provide the video links that has these issue? I tried on an emulator with the default youtube video and can't reproduce.

**Comment by metaflowdev** [comment]
@wenkaifan0720 The issue happens on multiple real devices. I have not tested with an emulator because the issue is clearly there on real devices which is what matters to us and our users. The devices were initially running iOS 17.2.1 (as originally reported) but the issue also has been seen now on iOS 17.3.0.

**Comment by leighajarett** [comment]
So sorry you're going through this @metaflowdev - we're taking a look. Thanks for your patience!!

**Comment by metaflowdev** [comment]
> @metaflowdev - Are yo still experiencing the issue ?

YES!!!

You wrote earlier that you are looking into it. Are you still looking into it? Why is there no update for 3 weeks? And why to you try to close this issue when the status is that I am waiting for your response and not the other way around?

**Comment by hariprasadms** [comment]
Are you still encountering this issue? I've tested it on both the simulator and an iOS device, but I couldn't reproduce it. Everything seems to be working fine. Could you please send me the YouTube link where you're experiencing the issue? Have you tried testing it with other video links? Also, what is the consistency of the issue? These details would be helpful in troubleshooting further.

**Comment by metaflowdev** [comment]
> Are you still encountering this issue?

Yes

>  I've tested it on both the simulator and an iOS device, but I couldn't reproduce it. Everything seems to be working fine.

How often have you tried? It doesn't happen with every play, sometimes it just happens every 3-4 video plays.

> Could you please send me the YouTube link where you're experiencing the issue?

Here are few example links: 
https://www.youtube.com/watch?v=8hVO7SfF7nc
https://www.youtube.com/watch?v=TKT649LAZ6I
https://www.youtube.com/watch?v=0bRCfjzQ5tQ

> Have you tried testing it with other video links?

With about ~40 video links, we use many videos in our app.

> Also, what is the consistency of the issue? These details would be helpful in troubleshooting further.

Very consistent. We get very frequent complaints from users about this and all iOS users in our team see this issue.

**Comment by rzambroni** [comment]
Hello @metaflowdev, thank you for your report, and we apologize for the delayed response. Despite several attempts, I have not been able to replicate the issue you described; it seems to be working as expected. If possible, could you provide an example of the issue within a blank project? Doing so would be immensely helpful, as it would allow us to rule out any project-specific factors and better isolate the problem. Thanks!

**Comment by rzambroni** [comment]
Closing this ticket due to inactivity. If you are still experiencing this issue please feel free to re-file it. Thanks a lot!
