### ISSUE TITLE
A Modification in Data Schema UI invalidates Custom Function compile state causing FF Error requiring a Custom Function check and recompile.

### ISSUE THREAD

**Issue by yoohoomedia** [FlutterFlow/flutterflow-issues#2146]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Making a change in the Data Schema FF UI such as adding Enum, adding or modifying a Data Type causes FF to display a compilation required Error for Custom Functions (even unrelated to the change).

This appears to be new as of 12th Jan FF release.

### Expected Behavior

There should be no need to recompile these function, especially ones that are not related to the Enum or Data Type.

### Steps to Reproduce

Bug Report Project:
1. Go to the FF Data Types UI page.
2. Do any of the following:
  - add/modify a new Enum with a single value
  - add/modify a new Data Type
At this stage a "Custom functions need to be checked for errors. Click here to check for errors." error is generated.

New Project
1. Create New Project
2. Create a Custom Function and ensure it's compiled (not FF errors).
```
String getHello() {
  return "Hello";
}
```
3. Create an Enum with a single value.
(this causes a recompile error)
4. Recompile the custom functions.
5. Go back to Data Types UI and add a new Data Type
(this will cause a recompile error)
7. Add the previous enum as a field.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l6oZhotwC+Kn+acFVhmY7I0MfWOdEket+EA0hNZutE5kMZ/feRFNLYteAd2N+JlmImXEKzN6KuOD9O/koaAWbbJxOwq5XQQ7wWn6nRrqTCriKP0QlHfhTIBCMyLWnoSMlFNN1dHAc1F+uOfCrG3qCf9qOYwx5e6fDbOY=

### Context

It's disruptive, requiring time to perform unnecessary recompilations while leading to greater FF resource consumption for for those compilations that are not impacted by the Data Type changes.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/57424939/c24d9cd4-85ff-4fcf-a43e-e4cd5450e06f

### Environment

```markdown
- FlutterFlow version: v4.0 released January 15, 2024 Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Brave
- Operating system and version affected: macOS Ventura
```

**Comment by yoohoomedia** [comment]
Also, a Browser refresh cases the Custom Function recompilation error to appear

**Comment by wenkaifan0720** [comment]
Hi @yoohoomedia. I can confirm this happens but would like to mark it as low priority. This is because custom code can rely on data types in any fashion, so we can't really determine the change to data types will have no impact on the validity of the custom code, without recompiling it.
