### ISSUE TITLE
Right to Left Decimal Numbers Changing Direction

### ISSUE THREAD

**Issue by Plosconos** [FlutterFlow/flutterflow-issues#2148]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello FlutterFlow team,

1. My app is in 2 languages (English and Hebrew).
2. In Hebrew words are written from right to left... only words... **NOT numbers**
3. I have in the app a textfield to type a decimal number (price)

The issue in the system is: When changing the language from english to hebrew also the decimal numbers are changing position (did not supposed to).

Example: when I write 50.25 in english and I change to hebrew is showing 25.50 and this is wrong!

Also if I direct typre in Hebrew is also changing direction in decimal numbers... if I type 50.25 already in hebrew is showing 25.50 for example.
[New Compressed (zipped) Folder.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13918146/New.Compressed.zipped.Folder.zip)

### Expected Behavior

Numbers ( intergers, decimals, percentage, etc...) did not suppouse to change direction in right to left languages.

In **ALL** right to left languages only words change direction...NOT numbers.

My expection is when using right to left languages the numbers DO NOT change direction.

### Steps to Reproduce

1. create new project
2. select hebrew as language
3. add a textfield
4. type any decimal number
   [New.Compressed.zipped.Folder.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13918208/New.Compressed.zipped.Folder.zip)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz/Hqx89gosRE+arAa8IwgmUwGUwbUOc7j9VEGAsjCeKqELMDdvT8UFpucuqHelB6DFqlmk0Dp8KNufztIPQnGy2BR6ZGz4dbUxDgcGe5bKazBcyKP2tRM8RUGhGn06aR2yZdD7JYR3g46k6mOO+Qb3qCf9qOYwx5e6fDbOY=

### Context

I am trying to build a web and native app where to follow up costs... The web app and the native app will be in hebrew.

This issue with numbers makes impossible to develope the app since is changing the numbers direction.

### Visual documentation

[New.Compressed.zipped.Folder.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13918243/New.Compressed.zipped.Folder.zip)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: most recent
- Platform: web and native
- Browser name and version:
- Operating system and version affected:
```

**Comment by victoriahuang1** [comment]
Hi @Plosconos , thanks for the report. This is similar to #1288.

Unfortunately, this is a Flutter bug. It's not something that we can really change from our end. But hopefully the Flutter team will come up with a fix soon. And in the meantime, we will keep thinking about ways we can mitigate this issue on our end before they roll out a fix.

**Comment by Plosconos** [comment]
Hi @victoriahuang1 , how are you?

Thanks for your reply...

Questions: 

1) Is the Flutter Team aware about this issue? 

2) How can I contact them?

3) How is possible to know if they are fixing it or not?

Sorry about those questions but this is crucial for me to decide continue using FlutterFlow or not.

Kindly let me know.

Best regards and have an amazing weekend ahead.

Gerson

**Comment by victoriahuang1** [comment]
Hi @Plosconos , I do not work directly with the Flutter team, so I cannot provide answers on their timeline for bug fixes for them. However, you can contact them and post about bugs in a similar way as you do for FlutterFlow: via [their github issues](https://github.com/flutter/flutter/issues).

Hope you have an amazing weekend too.
