### ISSUE TITLE
Project save timeout issue

### ISSUE THREAD

**Issue by esamzenhom** [FlutterFlow/flutterflow-issues#2149]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Project save timeout error appear, and all the changes within 5 or 10 min are lost, and when this happens, when trying to go to projects dashboard, loading icon keeps rolling infinitly

### Expected Behavior

save project

### Steps to Reproduce

random

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Bug Report Code (Required)

ITEejM/q25dJn7xZ+7nfY8ZVhQMwGkQ5a7sviu5+FBQaI+KsP7AUe8/eXFhucuqHeFdlPlml8TszpOjtkt+SDsI6KQSefb5B/7VTUxDveDqjVLaXCKWOTn9QI8ZhBUi606uFohBTHPppWnwl7U2Mf/OAb3qCf9qOYwx5e6fDbOY=

### Context

save project

### Visual documentation

![Screenshot 2024-01-12 at 2 19 26 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7274fe39-52d8-4bdf-a1b7-34c810defa90/067c108c-39b4-41b8-973c-8bb7b700ebfe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83Mjc0ZmUzOS01MmQ4LTRiZGYtYTFiNy0zNGM4MTBkZWZhOTAvMDY3YzEwOGMtMzliNC00MWI4LTk3M2MtOGJiN2I3MDBlYmZlIiwiaWF0IjoxNzA3MTgxOTcwLCJleHAiOjMzMjc3NzQxOTcwfQ.2Mb3Dzdi-yVoSOmuKg2_UhpQU3fCKCC5oAaUvaZMCc4)

![Screenshot 2024-01-12 at 2 19 05 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a920a58f-ec23-453f-8f7d-2430707e0df7/2dc97ed2-cb4e-47e9-9931-614dc72f42fa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hOTIwYTU4Zi1lYzIzLTQ1M2YtOGY3ZC0yNDMwNzA3ZTBkZjcvMmRjOTdlZDItY2I0ZS00N2U5LTk5MzEtNjE0ZGM3MmY0MmZhIiwiaWF0IjoxNzA3MTgxOTcwLCJleHAiOjMzMjc3NzQxOTcwfQ.S4SCa1CSUYsZOcU5YyGWd7czCzFU_yF0_i7CpCNbyzc)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: Macos and windows os (beta app and live app)
- Browser name and version: native app
- Operating system and version affected:
```

**Comment by msedats** [comment]
We have the same problem - @iabdullah15

**Comment by renanbirlem** [comment]
Same problem here.

**Comment by KlaudiaBronowicka** [comment]
Same problem. It suggests saving a new version but versions fail to load as well

**Comment by dabupk** [comment]
I having the same problem 
After using Flutterflow for like 5 min I get project same timeout and I couldn't even load other web pages for few seconds 
After that everything start working again but changes made in flutterflow are lost.
My platform details are below 

Windows 10 Pro
Build version : 10.0.19045 
Chrome Version 120.0.6099.217 (Official Build) (64-bit)
FlutterFlow v4.0 released January 12, 2024
Flutter version is 3.13.7

**Comment by jimmyper211** [comment]
I've got the same problem, just five minutes working and then the problem again. I tried to work in mac but the problem persist. Now i'll try with the incognito.

**Comment by renanbirlem** [comment]
> > I having the same problem After using Flutterflow for like 5 min I get project same timeout and I couldn't even load other web pages for few seconds After that everything start working again but changes made in flutterflow are lost. My platform details are below
> > Windows 10 Pro Build version : 10.0.19045 Chrome Version 120.0.6099.217 (Official Build) (64-bit) FlutterFlow v4.0 released January 12, 2024 Flutter version is 3.13.7
> 
> I figured it out why it was happening. I am not sure why it was happening but when I tried running flutterflow in Incognito it worked. So I removed all extensions. Maybe it was caused by some conflict between adblocker and new flutterflow version

I worked in Safari without any installed extension and I got the same problem.

**Comment by hariprasadms** [comment]
Hello everyone, When you lose the changes, can you please look at the browser console and check if there are any errors related to user authentication or connection error with a 404 error?

Also, share the exact action you were performing when the save timeout error was displayed. These details are very much required to investigate the issue.

**Comment by esamzenhom** [comment]
Hi Hari, This issue happens with me while using MacOS app and the beta new one, not in browser version.
the action was random, even when i leave the project for a while and try to go to dashboard, dashboard keeps loading infinitly, indicating that the connection have been lost, same "infinit loading" happens directly after "project timout" when happens

**Comment by hariprasadms** [comment]
Hello @esamzenhom - Thanks for confirming.

**Comment by jimmyper211** [comment]
Hi Hari, same as Esam, but i work with windows app, and i have the same issue in the browser version. At the moment i'm working with incognito browser and i don't have any problem at the moment.

**Comment by stevey6404** [comment]
Same problem occuring! Upvoting!

**Comment by abaix** [comment]
Same problem, same fix. Managed to work around it by going incognito. 

FlutterFlow v4.0 released January 15, 2024
Flutter version is 3.13.7

Found it on reddit as well: 
https://www.reddit.com/r/FlutterFlow/comments/196fd1i/wifi_gone_and_slow_in_chrome/

**Comment by KlaudiaBronowicka** [comment]
Hi @hariprasadms, I'm working on a Mac, using web version (Chrome). Flutterflow 4.0.0. Flutter 3.13.7

It's not action specific, just happens every now and then, even when left idle, so I assume it's when the autosave runs. 

On Sunday I lost about 1hr of progress during which I kept seeing the error messages either about Project save timeout or network being disconnected (it was only Flutterflow tab not working though, so not a connection problem). Near the end I saw a few green popups 'Project saved', yet it didn't actually save the progress made earlier. 

Today I tried to save using cmd  + s. I got the green 'Project saved' pop up and soon after the error 'Project save timeout'. Happened everytime I used cmd + s.

No errors in the console when it happened.

**Comment by esamzenhom** [comment]
i don't know if this could assist, but today i used the browser, all of those error appeared, just after FF hang, 
![Screenshot 2024-01-21 at 6 08 12 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/117540200/3b701a30-482b-4d9e-818e-08b597ee9e11)
![Screenshot 2024-01-21 at 6 08 02 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/117540200/6fcf6665-e82b-4ea3-925c-21c945a20aad)

**Comment by victoriahuang1** [comment]
Hi all, could you list out the extensions you have enabled for your browser (with and without incognito)?

**Comment by esamzenhom** [comment]
even if we are using native app ?

**Comment by victoriahuang1** [comment]
For the people that reported things working only on incognito.

**Comment by esamzenhom** [comment]
For everyone still having this issue, can you try to duplicate the project, and remove the old one, i think my issue have been solved using this trick, **could anyone confirm solving the issue so i can close the ticket ?**
after i have duplicated the project, i found 2 issues appeared with two images i got in my project, the two images was not read from the assets properly, i think FF was hanging somewhere.
**Thanks to Mr. Fettouh Mounir for offering the successfull solution.**

**Comment by esamzenhom** [comment]
confirm : the issue have been solved for the web app

**Comment by esamzenhom** [comment]
Update : this issue happens when dealing heavily with Code Expressions

**Comment by takashiff** [comment]
Hi @esamzenhom, are you still experiencing this issue? We had a similar issue in the past that was resolved, so it may be fixed by now. Thanks

**Comment by esamzenhom** [comment]
hi takashiff, its now resolved, it sometimes happens in macos app, but its major like before, in the future once i'm able to reproduce, i will raise another ticket, but for now its resolved yes :) ... thanks a lot

**Comment by takashiff** [comment]
@esamzenhom That's great to hear. Thanks again for the bug report and your continued patience.

**Comment by holyonenl** [comment]
@takashiff We also have this issue in the native MacOS app. Every 15 minutes a popup shows up with the message "Network disconnected" and the toast "Project save timed out". Is there anything we or you can do to resolve this issue?

![Scherm­afbeelding 2024-02-23 om 09 54 57](https://github.com/FlutterFlow/flutterflow-issues/assets/84071019/e6498a12-d855-49ad-b80a-1c0acc7e44ab)
