### ISSUE TITLE
When using the non-Interactive RatingBar Component inside a ListView it freezes the app

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#215]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Nothing special, the RatingBar Component is supposed to just display the icons

## Current behavior (required)

When using the non-Interactive RatingBar inside a ListView it seems like it freezes the whole app after One List View Element leaves the screen while scrolling. 
 
## To Reproduce (required)

ITFTlcmB34hNodcF+KrqdcJslWQsCUMdXOczitVEew4bCIj4EJlyds74YltWcO6zaH5mOFGj/DkE3MKMvuztIe5cISitfpx8+Jd6UVyjEA8=

## Context (required)

Just building a ListView with different components

## Screenshots / recordings

https://user-images.githubusercontent.com/120254395/206918991-beb8a6e7-1752-4865-8495-921e01c33d59.mov

## Your environment

* Version of FlutterFlow used: v3 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 
* Operating system and version (desktop or mobile): Mac OS Monterey 12.5.1

**Comment by bulgariamitko** [comment]
First of all can you add reproducible steps and second I see the stars of the RatingWidget, what is the issue exactly?

**Comment by nicmohr25** [comment]
Of course, it seems like i accidentally deleted the steps. 
1. Create List View
2. Add Card
3. Add Columns, Rows etc to get a similar layout as shown in the video
4. Use the StarRating Widget - disable interactive flag
5. Run Test Mode
6. Swipe from left to right (in this case i just queried for two firestore docs) 
7. Swip so far that one List Item leaves the screen
8. See how the whole App freezes 
9. Error as shown in the console is logged

The issue is that when i'm using the StarRating Widget my App freezes. When i'm removing it everything works properly.

**Comment by bulgariamitko** [comment]
Ok I will mark this as a big.

**Comment by wenkaifan0720** [comment]
Hi @nicmohr25. Have you tried download the code and run locally? I tried locally with web, iOS and Android and doesn't see this issue. I think this might be a Flutter webview related bug. Could you share with me the project link (or bug report code)?

**Comment by wenkaifan0720** [comment]
I tried with setting the rating bar widget to be interactive or using non-integer values, but sometimes it would still hang during the debug session. So I am not sure if the issue you mentioned earlier is of the same cause. 

This is the project that I created: https://app.flutterflow.io/project/flutterflow-issue-215-jfju7x. You might have to scroll for a while to see the app freeze in debug mode.

**Comment by wenkaifan0720** [comment]
This is the exception I saw during test mode :`element.parentnode == _resources host is not true`.

I think this issue is related to Flutter web html renderer in debug mode (https://github.com/flutter/flutter/issues/104305). 

When I run my test project locally in chrome, the app does not crash.
