### ISSUE TITLE
Multiple simultaneous API Calls Triggered in Webapp, iOS and Android Apps (backend queries)

### ISSUE THREAD

**Issue by 00Cedge** [FlutterFlow/flutterflow-issues#2150]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On test/debug mode a single API calls is made.
On the Webapp version, the endpoints are triggered twice.
On the Android app, the endpoints are triggered **4+ times**.
On the iOS app, the endpoints are triggered approximately **30 times**, leading to significant delays in the application's response.

### Expected Behavior

Only one API call (Backend Query) should be made when a user opens these chats from the "Inbox" button to ensure efficient and timely loading.

### Steps to Reproduce

1. Create a new get API with any list data  (can use this: https://api.robethood.net/api:XzuYc62E/chats/wex/for-testing)

2. Create a new component (which will be used as a bottomsheet)
  - add column
  - add ListView (nested inside)
  - add container (nested inside)
  - add text (nested inside)
  - in the "ListView" widget, add the API call as a backend query.
  - 
3. On the homepage. 
  - create a button. 
  - set the button action to open the bottomsheet
  
 4. Publish the app to WEB
 
 5. Open in the webapp and run you should notice that the API is fetched twice.
 
 6. On iOS apps I find like 30 executions at the same time. On Android apps I'm getting ~4 at a time.  Testing in debug results in only one API call.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89gocdY18/Uc+9ahWERJm44U600st5Hd0gdCOPrBuwtdsjRclhCXseqaVNcOWCZrHwypf+PvobxV/kBG0ueQaZ4/5ZAahX0e2inVYjTCrjoP3RCI/xVIG7C0pjQqgpCWcxYLXwN212MOt6XShDDFOu/Zwh9f6PHaOI=

### Context

It's been an ongoing issue for about 1 year.  I added rate limiting on the backend to try prevent the server getting overloaded, but it's becoming more of an issue.  The 30 consecutive API calls slow down our B.E. server and require the user to wait ~30 seconds sometimes. Or they hit rate limits etc..

### Visual documentation

https://www.loom.com/share/bcc4490574324c4895c440fae1484b01?sid=e60d2dd6-6c39-4f08-ba5c-462738206465

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: iOS, Android and Webapp...
- Browser name and version: Chrome - Version 120.0.6099.217 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by mrnicon** [comment]
I have the exact same issue, 
Bug report code 
ITFfz/Hl8Yt2pbxe1oSJau1amiI4NWkcTIAFkuwacy8YGIytBuwAYcz4S1toTs+9aVNcelajmjs1wNrruPPfKPQCJRSec6E6waoBcg70e2igVrKTCZOSOXElQOVbG3WO3MPYnhQkN

Image is from API calls Log, just by  opening the widget. 
![CleanShot 2024-01-22 at 14 41 51](https://github.com/FlutterFlow/flutterflow-issues/assets/26312916/db49dd2f-8119-42f7-a5e3-e772c0bfbe6b)
tR1R1IF7DuUCuTLaAXDFOu/Zwh9f6PHaOI=

**Comment by 00Cedge** [comment]
As a **workaround** - I changed our chat system to use "infinite scroll," Which seems to have reduced the number of API calls significantly.

**Comment by takashiff** [comment]
Hello, thank you for the bug report. This looks to be a duplicate issue to #1988. Please refer to the aforementioned thread for further updates. Thanks
