### ISSUE TITLE
Unknown error compiling custom code. (Authentication and Custom Actions)

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#2152]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was struggling to discover the cause of this issue it takes me a lot of time.

Current Behaviour
When "Custom Authentication" is enabled in app settings menu, the custom actions doesnt compile, this error appear:

```Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.```

### Expected Behavior

That FF compiles custom actions correctly even with custom authentication enabled.

### Steps to Reproduce

1. Open FF dashboard
2. Create a blank project
3. Add a blank page called Login
4. Go to AppSettings/Authentication and enable it
5. Put Login Page into entry page
6. Put Home page into loggeIn page
7. Go to custom code 
8. Add a blank action (that dont do nothing) with any name and save it
9. Click compile
10. You will see the error
11. Go to AppSettings, turn off authentication
12. Go to the custom action and change its name and save it
13. Click compile
14. The error disappear  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40k8jcw4lPn7wB1pDMbMExqCU5Jm49becSmu5raDYvCIyqOph/fsjeUBFoOP2iTWlhHEybglsB/96PhobxV8IEGAqcQYBywc9caDnyJHq8Rr6hOpGORER6O99gf1Cm4JmJ2iRSIbZoSnw9wGeUfN6XSnPDGZu/Zwh9f6PHaOI=

### Context

It is a super bad behaviour to compile actions, so I cant know if the compilation of my app is wrong. And I dont know if it is affecting my app code in some way.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/217a4bd8-b498-41fe-95c7-ec3602312a49)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/953a5477-6f0c-4000-8b1e-dead9f4cd324)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome Versión 120.0.6099.217 
- Operating system and version affected: Windows 11
```

**Comment by Franco98404** [comment]
I have the error too

**Comment by BenjaminAlvarezDiaz** [comment]
me too

**Comment by dfeinberg5** [comment]
I'm also running into this error with a custom widget

**Comment by silva8** [comment]
I have a similar issue, but only when I choose Custom Authentication Type.

When I create an empty custom action having Custom Authentication Type I get Unknown compilation error, I does not happen for example with Supabase Authentication Type.

**Comment by treyhendon** [comment]
As an example, the DottedBorderWidget tutorial does not compile when custom authentication is enabled, but as soon as authentication is disabled, DottedBorderWidget compiles correctly.

**Comment by hariprasadms** [comment]
Hi @treyhendon - Apologies for the delayed response to this issue. Are you still encountering the issue? I have recently tested it, but I couldn't replicate the problem.

**Comment by treyhendon** [comment]
No worries!  Thanks for following up.

Unfortunately, still receiving the "Unknown error" pill when hovering over the [now failed] compile button.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3513589/254a2652-c086-4aa8-b59d-87d464f05f15)

Once clicked to view errors, the list modal is blank with "Cancel" and "Try compile again" options.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3513589/e0f54b5e-4ab7-4b9c-a76c-e57b49468231)

If it helps, here are my authentication settings as well (I'm using a self-hosted Keycloak instance):
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3513589/dd810866-fa43-407a-bfe5-a164c4279823)

And User definition:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3513589/ab76b204-cb26-4a63-9593-3c497f396cf2)

**Comment by nev-21** [comment]
Hi @hariprasadms 
I'm also still seeing the problem

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/f608b700-c73e-4533-a820-e536c394a52a)

**Comment by treyhendon** [comment]
Great news, v4.1 seems to have resolved this issue.  Maybe we can get an explanation?

**Comment by ChecoG88** [comment]
I have the same issue, sorry but I don't know to create a new issue.
<img width="1470" alt="Captura de pantalla 2024-01-31 a la(s) 7 22 30 p m" src="https://github.com/FlutterFlow/flutterflow-issues/assets/158389058/56fb4e72-b5f8-49cb-b184-f8c14a5d1642">
