### ISSUE TITLE
Missing "Undo" in Actions Flow Editor

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#2154]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the case of a user mistake or some bug (as is was in my case when I cut a huge actions chain but after paste only the first action from the chain was pasted) it's impossible to revert back the changes made. The only option is digging in snapshots which isn't very convenient.

### Expected Behavior

There should be a possibility to revert changes in the Actions Flow Editor.

### Steps to Reproduce

1. Open action flow editor.
2. Make some changes.
3. Reverting is impossible.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NNN

### Visual documentation

No

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: FlutterFlow v4.0 released January 12, 2024
Flutter version is 3.13.7
- Platform:
- Browser name and version: Google Chrome 120.0.6099.200
- Operating system and version affected:
```

**Comment by takashiff** [comment]
Hello @appach22, thank you for your bug report. Unfortunately, this is a current limitation of FlutterFlow. If you'd like, I can put in a feature request for you internally. Thank you for your patience.

**Comment by appach22** [comment]
Hi, @takashiff ! Thanks for getting back. Yes if you could post a feature request that would be great! Thank you!
