### ISSUE TITLE
Unexpected shadow on custom dialog

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#2155]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When opening a custom dialog (using a component), an unwanted/unexpected shadow appear.
And there is no parameter or setting to change this behaviour.

### Expected Behavior

The shadow should not appear. Or there should be another way to config it (but I think this is not necessary cause there is a BoxShadow and elevation to config).

### Steps to Reproduce

1. Create a blank project
2. Create a component with a column and a container(100px x 100px) with a text inside
3. Turn off box shadow and elevation in container.
4. Add a button to open a custom dialog with transparent barrier color
5. Go test mode
6. click the button
7. see the unwanted/unexpected shadow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ok8jcw4lPn7xK1br+csExryQ7OVs3a68rk8pOGDsdF4iuPOxzaePSXBZWQs+hTEFDKEWJkj8DpvzVid/1UO0rByuYfLplyJNUFw3jTnK/aouVDpOoWnclBcFgGh2E0cCO3SMmLuh0Wngd12GYGdnJbDfrN5/4Zwh9f6PHaOI=

### Context

I need many custom dialogs, but the shadow is ugly and damage the UI presentation and UX

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/82cea306-d23f-4bbf-a0cb-4321a456cc30)
.
.
.

Action:
.
.
.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/1c159a18-1b7a-4160-8b0a-a08540f96666)
.
.
.
.
Container:
.
.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/f8ee5750-2e36-44a9-af4b-2a8c74063fd9)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Web
- Browser name and version: Chrome Versión 120.0.6099.217 
- Operating system and version affected: Windows 11
```

**Comment by nev-21** [comment]
This is still happening, in my app. UIt is an unwanted effect.

@takashiff please help

**Comment by sbis04** [comment]
This should be fixed in the next update!
