### ISSUE TITLE
When trying to use Sort Key with a JSON Path, Data Type can't be selected

### ISSUE THREAD

**Issue by alsopgroup** [FlutterFlow/flutterflow-issues#2157]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using an API to pull data for a ListView that I would like to sort, when I choose a known JSON Path and want to set the Data Type, it won't let me select the drop down.

I am trying to do this because if I just use the JSON Path with No Further Changes it tells me that it is an invalid key.

### Expected Behavior

I should be able to select a data type

### Steps to Reproduce

Add an API query, then select the query to define a list of dynamic children with the response. Try to enable a Sort Key and define a JSON Path and data type.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ListView

### Context

I can't sort a list view from API query data

### Visual documentation

![Screenshot 2024-01-08 at 2 21 20 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0690bb7d-e3f0-46cb-af5c-80421cbcd287/52017f11-852c-4197-8c48-9ea64350985a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNjkwYmI3ZC1lM2YwLTQ2Y2ItYWY1Yy04MDQyMWNiY2QyODcvNTIwMTdmMTEtODUyYy00MTk3LThjNDgtOWVhNjQzNTA5ODVhIiwiaWF0IjoxNzA3MTc4MjIyLCJleHAiOjMzMjc3NzM4MjIyfQ.u84cmJEjJU9rQ7uyN-kACC-b9ugKoAoePLvYZ9RnyLM "=594x")

![Screenshot 2024-01-10 at 10 59 13 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7b79982d-faf4-482b-900c-c7203462191d/f33f57d2-8c98-4c94-b691-d4e534cf9f90?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83Yjc5OTgyZC1mYWY0LTQ4MmItOTAwYy1jNzIwMzQ2MjE5MWQvZjMzZjU3ZDItOGM5OC00Yzk0LWI2OTEtZDRlNTM0Y2Y5ZjkwIiwiaWF0IjoxNzA3MTc4MjIyLCJleHAiOjMzMjc3NzM4MjIyfQ.EYzkvkG1VvP21a4Po8Cu9YpM_8P5TxZwS0c1Cq9u8ZY "=631x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: latest
- Platform: iOS
- Browser name and version: Chrome - latest
- Operating system and version affected: MacOS - latest
```

**Comment by alsopgroup** [comment]
To follow on this, even in the API call I can't set the DataType - the selection box does't work.  I've tried multiple machines, the Desktop App, and even my iPad app.  It won't allow it to open to select a type.

<img width="454" alt="Screenshot 2024-01-12 at 11 28 07 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17467923/a73f8c31-206d-4ce5-8668-ecb90d851e14">

**Comment by davidflutterflow** [comment]
@hariprasadms This is a project issue, Seems there is no data type in the project so the selecting data type option is red.
More info: https://docs.flutterflow.io/data-and-backend/custom-data-types/custom-data-type-with-api#converting-a-single-json-object-into-a-custom-data-type

**Comment by ignalauret** [comment]
Hey @alsopgroup thanks for your report. It looked like you had some misconfiguration with your DataTypes, so nothing was appearing on you DataType dropdown. Where you able to solve this issue?

**Comment by ignalauret** [comment]
I'm closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
