### ISSUE TITLE
FlutterFlow is Down!

### ISSUE THREAD

**Issue by dmk23** [FlutterFlow/flutterflow-issues#216]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

https://app.flutterflow.io/ supposed to load and let me login. Previously created run-links are supposed to work too

## Current behavior (required)

Infinite loading screen, with this JS error in console

## To Reproduce (required)

1. Just open FF and try to log in

### Bug Report Code

N/A

## Context (required)

Trying to just use FF. It died in the middle of updating a Custom Function

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/1828444/206935591-638ea230-ad20-46b9-90b0-54f0a5c76774.png)

## Your environment

* Version of FlutterFlow used: Latest
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 107.0.5304.122
* Operating system and version (desktop or mobile): Windows 10 Home, latest update, desktop

**Comment by wenkaifan0720** [comment]
Could you try to go to flutterflow.io first and login from there?

**Comment by dmk23** [comment]
> Could you try to go to https://flutterflow.io first and login from there?

Tried that, it didn't work. One of my public run links isn't working either, same on Chrome desktop and Safari iPhone: https://app.flutterflow.io/run/zQFlTAaQmfwvuc77Niqv

**Comment by Pepino-GR** [comment]
Hi dmk23 and wenkaifan0720,

I 'm also unable to connect to the public link.

**Comment by wenkaifan0720** [comment]
Hi @Pepino-GR. I just got informed that public run link sharing have been disabled now (outside of the admin team). This is probably for security reasons. If you can still access the main site then things should be fine.

**Comment by dmk23** [comment]
> 

Is this just temporary or public link sharing is gone for good?

**Comment by dmk23** [comment]
> Hi @Pepino-GR. I just got informed that public run link sharing have been disabled now (outside of the admin team). This is probably for security reasons. If you can still access the main site then things should be fine.

Is this just temporary or public link sharing is gone for good?

**Comment by dmk23** [comment]
> Hi @dmk23. I still can't reproduce. I can open your public run link too. Is FF still down for you now? Have you tried with a VPN?

I found that I wasn't able to log in with Chrome incognito (which I usually use/prefer), but regular non-incognito Chrome in fact works. Not sure why this could be. I cleared all application storage/ cookies in incognito too and it still didn't help

So I am able to use FF for now, but the problem with some browsers is a concern

**Comment by jacquelinekazmaier** [comment]
Same issue for me, created an account and (several) new projects and can't get past the loading screen for any of them

Chrome Version 108.0.5359.124 (Official Build) (x86_64)
From macOS Ventura 13.0.1

<img width="1792" alt="Screenshot 2022-12-18 at 15 49 59" src="https://user-images.githubusercontent.com/38219458/208301980-9910e5c2-15bc-47cd-a2a9-7f0c03b214a8.png">

**Comment by dmk23** [comment]
> > Hi @dmk23. I still can't reproduce. I can open your public run link too. Is FF still down for you now? Have you tried with a VPN?
> 
> I found that I wasn't able to log in with Chrome incognito (which I usually use/prefer), but regular non-incognito Chrome in fact works. Not sure why this could be. I cleared all application storage/ cookies in incognito too and it still didn't help
> 
> So I am able to use FF for now, but the problem with some browsers is a concern

Now the incognito login works after and rebooting and relaunching the browser

Can you share on whether link sharing is going to be supported in the future or it is turned off temporarily?

**Comment by agreaves** [comment]
Hi @dmk23, unfortunately Run Mode link sharing (with the general public) is no longer supported for the foreseeable future due to security concerns. We recommend you use web publishing in order to generate a sharable link from now on.

(Closing this ticket now, but can answer any further questions)
