### ISSUE TITLE
Calender Widget icon not working

### ISSUE THREAD

**Issue by rindishkrishna** [FlutterFlow/flutterflow-issues#2161]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We've encountered an issue with the calendar component in our project. Previously, clicking the calendar icon would open a datepicker, but it has recently stopped working. We'd greatly appreciate your assistance in resolving this matter.

### Expected Behavior

clicking calendar icon should open date picker

### Steps to Reproduce

1. import calendar widget
2. add random date state
3. run and click calendar icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThvHlx5NNrs8A+KqBY/pVhmQ7CUMdWOc7kdV+FBMgF5D4PbQAesnRXxdVOOqzaHNbfFGbhTsdpsrHjc7DNsAEAzGtRrZT+roIFxPPYziiR5SgDJeWWkZQHdFVCFSO36a3pQlACNJhLyEd6jiAee7KRT6Cf9qOYwx5e6fDbOY=

### Context

trying to use a calendar widget to filter data based on date

### Visual documentation

<img width="417" alt="Screenshot 2024-01-13 at 9 57 08 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/29222911/1bc51132-b44d-46e9-83a7-c3662fbce994">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: web
- Browser name and version: chrome Version 120.0.6099.216 (Official Build) (arm64)
- Operating system and version affected: macos sonoma 14.2.1 (23C71)
```

**Comment by hariprasadms** [comment]
Hi @rindishkrishna - I'm not entirely certain about your expectations regarding the icon. The icon in the calendar widget. When clicked, it navigates back to the associated date state, this is as per current design. If your understanding differs or you require further clarification, kindly provide additional details, possibly with a blank project setup that replicates the issue for better analysis.
