### ISSUE TITLE
App crashes immediately due to Pub package

### ISSUE THREAD

**Issue by minashawky** [FlutterFlow/flutterflow-issues#2162]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the most resent update the pub package has 
`flutter_facebook_auth: 4.4.1+1`

Which is causing all apps using it to crash on testflight

### Expected Behavior

Expecting the app to open

### Steps to Reproduce

1. Publish an app to test flight
2. Run the app locally
3. App crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lfLl08pgoddY7ZDUb+9anjwsJjo7ROc41up+SQs8J5zKB+wAYvf7P1FWTLykTwhDMGCamTke/Pfqit7lGu4oOS+aGYRJ/852UAzwXn+6RbGYPqi/fW1SGfpYFVSx4aao2B1+COhfLGQt2HGLNu6XSh3bJ4DrDEgZJf2LKdeK2SrDX1iXc2URm05KZDPz

### Context

Whenever I'm testing now a new update on Testflight the app doesn't launch and crash immediately before showing the splash screen. The report on Xcode shows the following:

<img width="680" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/f85ba782-04e4-4f8a-92cc-413b4cfdbb6f">

FBSDKCoreKit: -[FBSDKGraphRequestConnection raiseExceptionIfMissingClientToken] + 384

### Visual documentation

Whenever I'm testing now a new update on Testflight the app doesn't launch and crash immediately before showing the splash screen. The report on Xcode shows the following:

<img width="680" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/f85ba782-04e4-4f8a-92cc-413b4cfdbb6f">

FBSDKCoreKit: -[FBSDKGraphRequestConnection raiseExceptionIfMissingClientToken] + 384

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS
- Browser name and version: iOS - Test Flight
- Operating system and version affected: iOS
```

**Comment by khomya** [comment]
I have the same problem

**Comment by steven-ck** [comment]
I got the same problem. Facebook sign-in requires a client token (from Facebook app) in Info.plish but there is no way to configure it in FlutterFlow. I tried to set it manually and it works.

**Comment by jasonNumar** [comment]
Has anybody had this same issue on a platform other than ios?

**Comment by hariprasadms** [comment]
Hi, we need additional details. I've looked at your project, but I couldn't find the Facebook login and the package version you mentioned above. Have you made changes to the auth config in your project?

**Comment by michelflight** [comment]
it is necessary to push the code onto a git and add the FacebookClientToken parameter in info.plist for iOS. I have not yet tested on Android, but it should be the same.

**Comment by minashawky** [comment]
@hariprasadms yes so actually as @michelflight mentioned. I don't even use Facebook auth on the app yet my workflow includes me pushing the code and deploying to testflight via github. This `flutter_facebook_auth` package was added to the project and was updated recently to version 4.4.1+1 which is causing the issues.

I didn't try @michelflight suggestion to add the FacebookClientToken in the info.plist file but I downgraded the package to this and it worked:

```
flutter_facebook_auth:
    git:
      url: https://github.com/asmengistu/flutter-facebook-auth
      ref: b65ffb049c9f1e2704adbeb1aa19c61693c946a5
      path: facebook_auth
```

**Comment by khomya** [comment]
@hariprasadms pls look at my project too. (https://app.flutterflow.io/project/georgia-tennis-4hpmkx)

My Facebook App Name and Facebook App ID - are empty. And I dont use B Auth.
But I still got errors and cant compile my project.

And in community - I saw that several people has the same problem.

<img width="290" alt="Screenshot 2024-01-13 at 18 00 46" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/0e21d063-c429-4712-80e7-9b58ce5a2bde">
<img width="308" alt="Screenshot 2024-01-13 at 18 01 46" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/d9e3aa2c-3083-406f-bae5-0876e890fec1">

**Comment by hariprasadms** [comment]
> @hariprasadms pls look at my project too. (https://app.flutterflow.io/project/georgia-tennis-4hpmkx)
> 
> My Facebook App Name and Facebook App ID - are empty. And I dont use FB Auth. But I still got errors and cant compile my project.
> 
> And in community - I saw that several people has the same problem.
> 
> <img alt="Screenshot 2024-01-13 at 18 00 46" width="290" src="https://private-user-images.githubusercontent.com/2369704/296731492-0e21d063-c429-4712-80e7-9b58ce5a2bde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTU5NjcsIm5iZiI6MTcwNTMxNTY2NywicGF0aCI6Ii8yMzY5NzA0LzI5NjczMTQ5Mi0wZTIxZDA2My1jNDI5LTQ3MTItODBlNy05YjU4Y2U1YTJiZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTA0NzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA3NTcwNDBjZTMzNWVlZGZjYTBmZDI1Yzc2NWRlN2IyNGZmNTlmM2VjNjYxMDY1ZjJmMDdkNTcxNzdkZjNjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5OglyfQ0UqIKDtqEQc52-fduAhSx5TELisI3H-vpsAU"> <img alt="Screenshot 2024-01-13 at 18 01 46" width="308" src="https://private-user-images.githubusercontent.com/2369704/296731513-d9e3aa2c-3083-406f-bae5-0876e890fec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTU5NjcsIm5iZiI6MTcwNTMxNTY2NywicGF0aCI6Ii8yMzY5NzA0LzI5NjczMTUxMy1kOWUzYWEyYy0zMDgzLTQwNmYtYmFlNS0wODc2ZTg5MGZlYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTA0NzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQwMzA1YWNkOWFiNzczZThjNWRhOTgyMjkzOWJlYmIyNTJhODQ5MDI1MGFiYjEyYWNmMjJkYWRjY2FiZTM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1xpm3tdwA_ftZgAzmg3za_jWBvfBBfARcqK8GVdfFMM">
> Link to FF community: https://community.flutterflow.io/ask-the-community/post/the-app-crashes-immediately-in-testflight-DlcuPUncN6ecBiL?highlight=vrYYS9mNU26h0be

Hi @khomya - If you're seeing this message, it might be due to having a Facebook login as the authentication type in any of your pages' actions. Please check and make sure you don't have any actions tagged as FB auth actions.

**Comment by Marcelo1chagas** [comment]
> > I got the same problem. `flutter_facebook_auth: 4.4.1+1` include SDK 13 and requires a client token (from Facebook app) in `Info.plish`/`AndroidManifest.xml` but there is no way to configure it in FlutterFlow. My only option is downgrade to version 3.x
> 
> I tried adding the token to info.plist locally and it did indeed solve the problem. Hopefully there will be a solution for adding it from Flutterflow soon.

hello, I have the same error. Can you pass me the code you used to add the Client Token. thanks!

**Comment by Marcelo1chagas** [comment]
> > > > I got the same problem. `flutter_facebook_auth: 4.4.1+1` include SDK 13 and requires a client token (from Facebook app) in `Info.plish`/`AndroidManifest.xml` but there is no way to configure it in FlutterFlow. My only option is downgrade to version 3.x
> > > 
> > > 
> > > I tried adding the token to info.plist locally and it did indeed solve the problem. Hopefully there will be a solution for adding it from Flutterflow soon.
> > 
> > 
> > hello, I have the same error. Can you pass me the code you used to add the Client Token. thanks!
> 
> This is the error log in Xcode. Doing this worked, but... not really a solution unless it is added into flutterflow.
> 
> * Terminating app due to uncaught exception ‘NSInternalInconsistencyException’, reason: ‘Starting with v13 of the SDK, a client token must be embedded in your client code before making Graph API calls.
>   Visit [https://developers.facebook.com/apps/{appId}/settings/advanced/] to find your client token for this app.
>   Add a key named FacebookClientToken to your Info.plist, and add your client token as its value.
>   Visit https://developers.facebook.com/docs/ios/getting-started#configure-your-project for more information.’

thanks!!!

**Comment by michelflight** [comment]
Add in info.plist

<key>FacebookClientToken</key>
<string>YOURCLIENTTOKEN</string>

You will find your client token in the Advanded Settings section of facebook account developer

**Comment by Marcelo1chagas** [comment]
Hello again

> Add in info.plist
> 
> ```
> <key>FacebookClientToken</key>
> <string>YOURCLIENTTOKEN</string>
> ```
> 
> You will find your client token in the Advanded Settings section in your facebook account developer

Hello again, I added the client token and the SDK, but the problem still there

**Comment by victoriahuang1** [comment]
Hi all, thank you for the report. Crashing due to `flutter_facebook_auth` should be fixed upon the next deploy.
