### ISSUE TITLE
Title: Crash on Startup after Latest Update on macOS Catalina

### ISSUE THREAD

**Issue by Marakase12** [FlutterFlow/flutterflow-issues#2163]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the most recent update, the desktop application for macOS fails to launch and immediately crashes.

### Expected Behavior

The application should start normally and be usable without crashing.

### Steps to Reproduce

Open the desktop application on macOS.
Observe that the application crashes immediately upon launch.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable (the issue is with application startup, not a specific widget).

### Context

I am unable to use the desktop application at all due to this startup crash. The issue is preventing me from accessing my projects and continuing my work.

### Visual documentation

No visual documentation available as the application does not stay open long enough to capture any visuals.

### Additional Info

Platform: Desktop
Browser name and version: Not applicable (desktop application)
Operating system and version affected: macOS Catalina 10.15.7

### Environment

Platform: Desktop
Browser name and version: Not applicable (desktop application)
Operating system and version affected: macOS Catalina 10.15.7

**Comment by gorgulij** [comment]
Same trouble!

**Comment by SPYSEL** [comment]
Same trouble

**Comment by rzambroni** [comment]
Hi everyone! I'm closing this issue as a duplicate in favor of already resolved => [https://github.com/FlutterFlow/flutterflow-issues/issues/2178](https://github.com/FlutterFlow/flutterflow-issues/issues/2178). 
If you are still experiencing issues with MacOS Catalina, please make sure to update to the latest version of MacOS.
