### ISSUE TITLE
Data Types from Action Block parameters are not showing when used with filters

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2165]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Data Types from Action Block parameters are not showing when used with filters

### Expected Behavior

Data Types from Action Block parameters should appear when used with filters

### Steps to Reproduce

1. Create a data type
2. Create an action block and define as a parameter the data type created previously
3. Inside the action block created, try filtering a list using fields from the action block parameter (data type)
4. Now you can't find the data type parameter.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkufl0It1mNte+KqJY+5VpDk7CUMdXOczitVEew4bCIj4O5oIfePsYRJCZNyzaH47HWCYoEEF+MrXk+z9O/cVHy6BRohx/80NYBPPbGCQSp+YEpCVP3Z8L+9VGnKD05m3pRFDIbJvWEI1w2eyCOeART2Cf9qOYwx5e6fDbOY=

### Context

I want filtering a list using fields from the action block parameter (data type)

### Visual documentation

https://www.loom.com/share/36837f7a737d422896a8b4dec8b03b5b

You can see when I want to use a field from the action parameter to filter, it doesn't appear but it is possible to paste the variable. Anyway doing pasting the variable produces an error

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released January 11, 2024 - Flutter version is 3.137
- Platform: Web
- Browser name and version: Chrome 120.0.6099.217 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by victoriahuang1** [comment]
Hi @Franco98404 , thanks for the report. This should be fixed upon the next deploy.
