### ISSUE TITLE
Accessing Switch Component value causes Null page crash despite initial value.

### ISSUE THREAD

**Issue by yoohoomedia** [FlutterFlow/flutterflow-issues#2166]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Accessing a switch component value within a page causes a null error crash.

In my cause I had a container where the fill color was by a condition on the state of a switch component.

The cause is by the switch value being uninitialise in the page model, while the initial state of the Switch is set separately (leaving the model value uninitialised). The Container Fill Colour condition expects a non-null value in its test therefore error is triggered.

Workaround: Set the switch widget state to your indented default state within the On Page Load Action which will initialise it's value in the model.

### Expected Behavior

A Switch has no null state when a default state is set therefore Page should not error out on construction when another component attempts to use the switch state for its purpose.

### Steps to Reproduce

1. Create a New Project
2. Add a Switch component and set it's default state to True
3. Add a container with a Fill Colour condition that sets the colour to either one or another based on the state of the Switch.

Run the test and page will crash.

### Reproducible from Blank

*From a Blank Project*

1. Create a Blank Project
2. Add a Container to the Home Page Column
3. Also, add a Switch to the Home Page Column
4. Add a condition on the Container Fill Color to switch between Red and Blue based on the value of the previous Switch widget.

Run the App and it will crash with a null error.

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l6oZhotQC+KXibsdsqyosGUMcWOdEl+tuZwgbIoznBqQufuPRclVCUt/gaVNcD1e0jkMEp/THv9jLOMIBBwmVUb5P1ZZMEQvke2iiVbKXDLmefXBSJ5hjf0yl1J7VkwpTKspfL2wFwGCmB+euSjHDIuu/Zwh9f6PHaOI=

### Context

I wanted to set colour states of components based on a switch component.

I also wanted to set the default state of the switch component, via the UI rather than force it via an Action.

### Visual documentation

![2024-01-14_00-24-11](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/74512435-961f-4b4b-b091-02ccd3bdb42e/8b72eb2e-1ba5-4b6b-87d9-b77b8bbfa292?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NDUxMjQzNS05NjFmLTRiNGItYjA5MS0wMmNjZDNiZGI0MmUvOGI3MmViMmUtMWJhNS00YjZiLTg3ZDktYjc3YjhiYmZhMjkyIiwiaWF0IjoxNzA3MTM4NzIxLCJleHAiOjMzMjc3Njk4NzIxfQ.8jH6yutLsH3wCYXqSkskGoXAU9kJ7zhBTQbe1t98PpU)

HomePage Model shows the state of mySwitchValue has optional and unset.

```
class HomePageModel extends FlutterFlowModel {
  /// Local state fields for this page.
 
  MyTypeStruct? data;
  void updateDataStruct(Function(MyTypeStruct) updateFn) =>
      updateFn(data ??= MyTypeStruct());
 
  /// State fields for stateful widgets in this page.
 
  final unfocusNode = FocusNode();
  // State field(s) for mySwitch widget.
  bool? mySwitchValue;
 
  /// Initialization and disposal methods.
 
  void initState(BuildContext context) {}
 
  void dispose() {
    unfocusNode.dispose();
  }
 
  /// Action blocks are added here.
 
  /// Additional helper methods are added here.
}
 
```

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.1.20
- Platform: web
- Browser name and version: Safari 17.2.1
- Operating system and version affected: macOs Ventura 13.6.3
```

**Comment by yoohoomedia** [comment]
Any updates for this?

**Comment by rzambroni** [comment]
Hey @yoohoomedia, I was able to replicate the issue and will pass it on to the team so they can take a look.

Thanks for the report and apologies for the delay in the response, we are trying to get up to speed with everything.
