### ISSUE TITLE
SDK version warning

### ISSUE THREAD

**Issue by joveptesg** [FlutterFlow/flutterflow-issues#2167]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Warning when APP deployment in Google play. Same problem with 6 app.

The developer of reCAPTCHA Enterprise (com.google.android.recaptcha:recaptcha) added the following note to SDK version 18.1.2:
A critical security vulnerability was discovered in reCAPTCHA Enterprise for Mobile. The vulnerability has been patched in the latest SDK release. Customers will need to update their Android application with the reCAPTCHA Enterprise for Mobile SDK, version 18.4.0 or above. We strongly recommend you update to the latest version as soon as possible.

Learn more about the SDKs that you're using and make informed SDK choices with [Google Play SDK Index](https://play.google.com/sdks).

### Expected Behavior

Not show this worning

### Steps to Reproduce

Deployment app in google play

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

Flutterflow use old apk version, is it very bed

### Visual documentation

![Screenshot_6](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bbe9b5eb-22ca-4b5b-a747-a469a630a0f3/84e17e92-cd9b-46a4-96ec-33483574eee4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYmU5YjVlYi0yMmNhLTRiNWItYTc0Ny1hNDY5YTYzMGEwZjMvODRlMTdlOTItY2Q5Yi00NmE0LTk2ZWMtMzM0ODM1NzRlZWU0IiwiaWF0IjoxNzA3MTc4MDk4LCJleHAiOjMzMjc3NzM4MDk4fQ.T3a54g4VksknMXEM-zXJCi9O6qXi0iW-HRdkQ9BOGQk)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version:
3.13.7
- Platform: android
- Browser name and version:-
- Operating system and version affected: -
```

**Comment by Muhammad-Tayyab67** [comment]
I'm encountering a similar issue while trying to integrate 'easy_linkedin_login',  with conflicts arising from package dependencies.
 
<img width="591" alt="Screenshot 2024-01-14 at 10 59 01 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/95230366/cd5e33fd-b8d7-4fe9-96d2-034363f8d49f">

And if I also add the http: ^1.1.2 and test the project.


<img width="529" alt="Screenshot 2024-01-14 at 11 00 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/95230366/eac5322a-3635-407c-9af8-adc7c0738c56">

**Comment by momineutec** [comment]
Same issue with our app. Did any of you guys reach out to the support team ?

**Comment by TT450** [comment]
Same problem, and phone auth not working...
![Screenshot 2024-01-24 014008](https://github.com/FlutterFlow/flutterflow-issues/assets/39283886/a238f001-4727-4563-b87a-148e6a1ced5c)

**Comment by KelpME** [comment]
@victoriahuang1 @hariprasadms 
any advice?

**Comment by victoriahuang1** [comment]
Hi @joveptesg , can you share your bug report code so that we can use it to debug?

**Comment by leighajarett** [comment]
Since we haven't heard from you, I'm going to close this. Please create a new issue with the bug report code if you're still running into this issue. Thanks!
