### ISSUE TITLE
Rating bar always showing 5 stars in mobile web

### ISSUE THREAD

**Issue by stevey6404** [FlutterFlow/flutterflow-issues#2169]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On iOS Safari and Chrome, the interactive rating bar does not behave like the web version. It is always showing 5 stars even though they have different rated and unrated colour. 

### Expected Behavior

It should behave like the web version where clicking each star will give it a rating, thus the interactivity. 

### Steps to Reproduce

1. Create new page
2. Add rating bar 
3. Deploy to web
4. Access website from iOS 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvLq249Om+5E7ZD+YO9VhmEvCDo3UIE/lNUbaCs8I5D2OpkqevemTEpvZr2oYWxXPmH8uDkx/PfqvdjtKMICA0uZf7Y6wc1+SBb/Vk26ac2SDqiRfW1THeRmC0fCy8ConiZ7PsxYLFVh606MBN/Ic3bbJ7LsPW0dA+SbLdeK2SrDX1iXc2URm05KZDPz

### Context

Interactive rating bar is used quite common in providing ratings. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/578a15b3-6a8d-4419-9da4-4ec57c8818f6

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome  120.0.6099.129
- Operating system and version affected: iOS 17.2.1
```

**Comment by stevey6404** [comment]
Please see example and open in Desktop and iOS browser 
https://ratingbarbug.flutterflow.app/

**Comment by dsg27** [comment]
I'm encountering this issue too, and it's causing frustration among many end-users. 🙏

I would greatly appreciate it if this could be fixed, or an update provided, allowing me to provide positive news to end-users. 👍

**Comment by wenkaifan0720** [comment]
Hi @stevey6404 @dsg27. Could you try to enable Canvaskit for web publishing and see if the problem persists?

**Comment by hariprasadms** [comment]
Hi @wenkaifan0720 - I can confirm that, i can reproduce the issue with canvas-kit disabled but it works fine when it is enabled. It looks like related to canvaskit settings. 

@stevey6404 @dsg27 - Please confirm your observations as well.

**Comment by stevey6404** [comment]
hi @hariprasadms, correct, turning on canvaskit made it worked. Would there be other potential bugs since canvaskit is still in beta mode?

**Comment by wenkaifan0720** [comment]
Hi @stevey6404. The canvaskit mode has been the default for Flutter web on Android. Html mode is still default for Flutter web on iOS, but should eventually be replaced by canvaskit in the future as well. I think the Flutter team is shifting their effort towards supporting canvaskit so we could be experiencing more and more issue with html mode, especially on iOS. Flutterflow itself is even rendered with canvaskit mode now. I can't think of any current bugs that is on canvaskit mode, so I would suggest you to stick to canvaskit mode for the time being. Thanks!

**Comment by diegoserranobst** [comment]
@wenkaifan0720 @hariprasadms @leighajarett 
Currently, the bug has returned. I have CanvasKit active, but it still doesn't work on iPhone. All stars always appear marked to the maximum. I tested it on Chrome, Safari, and Firefox.

Can you guys open this bug again?

**Comment by diegoserranobst** [comment]
![mobile](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/4087f010-b5f8-4ebe-8574-15077bbb1c26)
![desktop pc web](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/668724eb-7338-468f-99c0-378ae79d4122)
![canvakit](https://github.com/FlutterFlow/flutterflow-issues/assets/129707357/8356b9fe-9148-4f80-bbb1-fadbdb6affb6)

I attach screenshots

**Comment by adrilevendi** [comment]
Same here

**Comment by xmatthewx** [comment]
Hmm. Should canvas kit be pulled out of Beta? If widgets are silently failing without it turned on, it's probably worth considering.

**Comment by adrilevendi** [comment]
Got it to work.

**Comment by olivermarshall2** [comment]
> Got it to work.

Can I ask how?
