### ISSUE TITLE
Periodic Action Stop Function does not work in the following case

### ISSUE THREAD

**Issue by anywheresa** [FlutterFlow/flutterflow-issues#217]
## Expected behavior (required)
When adding the periodic action to Load Page and then having a condition when true, the periodic action must stop and navigate to a different page. 

## Current behavior (required)
The periodic action fires and when condition is met and true, app does navigate to a different page. This works perfectly, however the periodic action stop is not fired and the action continuous running on the different page

## To Reproduce (required)
1. Create new Start Periodic action on page load ex on Page A (Works)
2. Add condition. When current date/time is less than a date/time that was set on startup in local state variable. (Works)
3. When Condition = True (Works)
4. Stop Periodic Action (DOES NOT WORK - STOP PERIODIC ACTION DOES NOT FIRE)
5. Navigate to Page B (Works)

As above

### Bug Report Code
NA

## Context (required)
The Periodic Action is useful to indicate when a jwt token has expired and then navigates the user to login. This is now preventing me from publishing the app

## Screenshots / recordings

![periodic](https://user-images.githubusercontent.com/56668789/207028670-0f9ace2d-b1e3-4ea8-b83d-f38e1253b1cb.JPG)

## Your environment

* Version of FlutterFlow used: 
* Platform: Web: 
* Browser name and version: Version 108.0.5359.98 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 10

**Comment by bulgariamitko** [comment]
So basically it is navigating, but the action is not stoppning?

**Comment by anywheresa** [comment]
Correct. The repeat is set to every 30seconds. So what happens the user is stuck in a redirect loop back to the Landing page every 30 seconds and cant go anywhere.

**Comment by bulgariamitko** [comment]
And the condition statement where is it coming the value from and how changing to true or false

**Comment by anywheresa** [comment]
Check point 2 in how to reproduce issue.
Every 30 seconds I compare the value of the local state date/time value to current date/time and if smaller than current/date/time execute as true.

**Comment by bulgariamitko** [comment]
When you visit the page, do you change the local state after that or not?

**Comment by anywheresa** [comment]
No

**Comment by anywheresa** [comment]
Any response to this?

**Comment by agreaves** [comment]
Hey @anywheresa! Could you please add a Bug Report Code to this issue, that will help me investigate what might be going on. Thanks!

**Comment by anywheresa** [comment]
There is no bug report.Sent from my Galaxy
-------- Original message --------From: Alex Greaves ***@***.***> Date: 2022/12/23  08:17  (GMT+02:00) To: FlutterFlow/flutterflow-issues ***@***.***> Cc: anywheresa ***@***.***>, Mention ***@***.***> Subject: Re: [FlutterFlow/flutterflow-issues] Periodic Action Stop Function does not work in the following case (Issue #217) 
Hey @anywheresa! Could you please add a Bug Report Code to this issue, that will help me investigate what might be going on. Thanks!

**Comment by agreaves** [comment]
In order to generate a Bug Report Code, all you need to do is right click anywhere on the widget tree and select "Generate Bug Report Code". Thanks.

**Comment by anywheresa** [comment]
IT48k/KA8Y9PvsNc+Kr2b8Fv+TwsQls7bJ0Njex+TRU8KOPbPbMAPPfOTERCTu29SnNAPVmJp2oW0vTRueHPGPoEYCitGbZRzJdUYQnNVXKjR7KUU/HUACkbeacOQSj6

**Comment by agreaves** [comment]
Thank your very much for this! I was able to identify the issue, which will be fixed upon our next release 🙂
