### ISSUE TITLE
Resolution for Duplicate Parameter Issue in Google Cloud 'ffPrivateApiCall' Function

### ISSUE THREAD

**Issue by palridr** [FlutterFlow/flutterflow-issues#2170]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the 'ffPrivateApiCall' function to make OAuth API calls, the 'grant_type' parameter is being included twice in the request - once in the URL query string and once in the body. This results in an error from the API: "Duplicate values defined for 'grant_type' parameter."

### Expected Behavior

The 'grant_type' parameter should only be included once in the request body as 'application/x-www-form-urlencoded' data when making a POST request to obtain an OAuth access token.

### Steps to Reproduce

* Set up an OAuth API call using the 'ffPrivateApiCall' function.
* Configure the request with 'grant_type', 'code', 'client_id', 'client_secret', and 'redirect_uri' parameters.
* Execute the API call.
* Observe that the 'grant_type' parameter is sent both in the query string and the request body, causing the API error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjMrlvI1gobhZ1s+BY8dB/SgRQm41bYIoscp/bxIgGIDzPOw+ZPWlTFFtOcfgYX9UMUSmmlkC0a3HufL9FsY6YEybGIR6zc1IEDqUQj6hQZOBEpCgYnB7L95jCByPyLWwkSQlXbNoLSEl7zv3COiQTjbfK5jFIndISq/LZO4=

### Context

This issue prevents successful authentication with the LinkedIn OAuth service, as the API call fails due to the parameter duplication. The expected outcome is to receive an access token upon a correct API call.

### Visual documentation

The resolution involves adjusting the '\\\_accessTokenCall' function in the 'api_manager.js' to ensure that parameters intended for the request body are not appended to the URL. Instead, they should be URL-encoded and included in the request body only. Here's the adjusted code for reference:

![bug-flutterflow](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6f293c15-70dc-4228-922d-2ce7d42b1954/6756caa9-25ad-466b-9c9e-7ad31f356a52?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZjI5M2MxNS03MGRjLTQyMjgtOTIyZC0yY2U3ZDQyYjE5NTQvNjc1NmNhYTktMjVhZC00NjZiLTljOWUtN2FkMzFmMzU2YTUyIiwiaWF0IjoxNzA3MTgxNTU2LCJleHAiOjMzMjc3NzQxNTU2fQ.PWYW3P8bdQ8IYrUBHNqU0EYwaMMps_yqLQAkLGTKgpA)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 (Flutter 3.13.7)
- Platform (e.g. Web, MacOS Desktop): Web
- Browser name and version (web): Chrome 120.0.6099.217 (64 bits)
- Operating system and version (desktop): Windows 11 23H2 22631.3007
```

**Comment by takashiff** [comment]
Hi @palridr, thank you for the bug report. Do you receive the same duplicate error for the other parameters, or is it just for `grant_type`? Thanks

**Comment by palridr** [comment]
Hi @takashiff, it's just for `grant_type`. I can't tell if another grant_type parameter has been added or if there's a problem reading the parameters. What I do know is that the change solves the problem and LinkedIn authentication works.

**Comment by hariprasadms** [comment]
Thanks @palridr the updates. We appreciate your contributions. Thanks
