### ISSUE TITLE
flutterflow_cli does not sync assets\sqlite_db_files

### ISSUE THREAD

**Issue by pfreund** [FlutterFlow/flutterflow-issues#2172]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow seams not syncing new assets\sqlite_db_files folder.

### Expected Behavior

Download assets\sqlite_db_files folder.

### Steps to Reproduce

Upload .db file in flutterflow
Download project code with flutterflow_cli : flutterflow export-code --dest . --include-assets --no-fix --project <project> --no-parent-folder
Run flutter test integration_test/test.dart

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

null

### Context

I'm trying to execute my app with a local android emulator.

### Visual documentation

# flutter test integration_test/test.dart
Error: unable to find directory entry in pubspec.yaml: C:\<folder>\assets\sqlite_db_files\
Error: Failed to build asset bundle

### Environment

```markdown
- FlutterFlow version: flutterflow_cli 0.0.11
- Platform: windows
- Browser name and version: NA
- Operating system and version affected: NA
```

**Comment by pfreund** [comment]
mkdir assets/sqlite_db_files resolvs the issue.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @pfreund. It's been fixed - please update `flutterflow_cli` on your machine (`dart pub global activate flutterflow_cli`).
