### ISSUE TITLE
minWidth (min w) property for container widget not working

### ISSUE THREAD

**Issue by wolfiL** [FlutterFlow/flutterflow-issues#2173]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can define the properties "min w" and "min h" for a container, but the values have no effect either in pixels or in percent. If I look at the code, I can see that the constraints property is missing (as far as I have understood correctly).

### Expected Behavior

The container adopts the minimum and maximum values if the content is correspondingly smaller or larger.

### Steps to Reproduce

1. Create a new Page.
2. Add a Row Widget.
3. Add a Container Widget to the Row.
4. Set the fill color of the Container differently from the background color of the Page so you can see it when you run the App.
5. Add a Text Widget to the Container.
6. Set the Text property of the Text Widget to "Hello World".
7. Set the property "min w" of the Container to 200 Px (at least a value bigger than the text width).
8. run the App.
9. Observe that the Container width isn't 200px, but it should be.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slsjf35d2tbxa15D+dMdB/SI7Q1w1R78wscpCbw4bIYj2P4lzY876PhZtOeLmdwhEfGemp14D0M7Pjd71LO0FFw6cQKp7zatyUxXwQlmXVbWTF7mWeHN9MJpmfX6n0Z6zvQlRANNhL04l3WD7edivRXfUGbrXDEQ8Sq/LZO4=

### Context

In a row, I want to set a minimum width of a container that contains a text, so that the 2nd element in the row is on a fixed position if the text is smaller than the minimum width of the container.

### Visual documentation

<img width="1042" alt="Bildschirm­foto 2024-01-15 um 14 42 32" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17195486/13013f3a-e0b8-454a-83e4-383cb50a0d62">
<img width="402" alt="Bildschirm­foto 2024-01-15 um 14 42 59" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17195486/fdfacde4-9b78-4cc7-bfd7-ac6a20190a9f">
<img width="564" alt="Bildschirm­foto 2024-01-15 um 14 44 33" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17195486/e9e42bc2-aaee-49e7-b1d2-a7d3ab1f784b">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.216
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @wolfiL - Thanks for reporting the issue. I can confirm that it is a bug at our end. It will be fixed in future updates. Thanks for your contributions.

**Comment by victoriahuang1** [comment]
Hi @wolfiL , thanks for the report. This should be fixed upon the next deploy
