### ISSUE TITLE
Bug in RatingBar on webapp, working on PC browser but not working on iOS browser

### ISSUE THREAD

**Issue by raphald** [FlutterFlow/flutterflow-issues#2174]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open my project on browser the rating bar is synced and show the correct rating but when I use the same browser(like chrome) on iPhone the rating bar appears full 5 stars, always. 

### Expected Behavior

I expect see the same behavior of rating bar that works on browser on PC.

### Steps to Reproduce

-Open my only project on PC browser
-Open "Lojinhas"
-Check rating bar (stars)

-Open the same project on Mobile browser (IOS)
-Open "Lojinhas"
-Check rating bar (stars)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l+fl4ot2xNtF+KX6YMEwvDwsQls7R4IZmO5HTUg8J5DNB4YUf8/7YmFVUs+0T3NAO1r9jmM1wNHemvzAGsFdOReuGoBbzLpcbRWVJWGibr2bBs+WOG5/DdxRBXaa4Z2jpBNQHLdhc1o72jqQfNnKfHLYQoTuOVcjAPyYKZOK2SrDX1iXc2URm05KZDPz

### Context

I am trying to do a rating bar to help customers with listed stores.

### Visual documentation

Browser on PC
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4820371/9b74914d-e27c-46f5-bb74-e7d97ac7646b)

Browser on IOS
![CondoAmigo](https://github.com/FlutterFlow/flutterflow-issues/assets/4820371/e5a085a7-e878-47f1-a849-73683657831c)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome Versão 120.0.6099.217 (Versão oficial) 64 bits / Safari (IOS 17.2.1)
- Operating system and version affected: Windows 11 Home Single Language / IOS 17.2.1
```

**Comment by stevey6404** [comment]
Hi, I submitted the same issue here previously https://github.com/FlutterFlow/flutterflow-issues/issues/2169

**Comment by takashiff** [comment]
Marking as closed due to duplicate issue. Please refer to #2169 (as @stevey6404 has commented above) for further updates on this issue.
