### ISSUE TITLE
Project not updated

### ISSUE THREAD

**Issue by denissonsillva** [FlutterFlow/flutterflow-issues#2175]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Last night I started my project at FF. I did several screens, action and such…
I saved the code and downloaded the apk on Android, and everything was ok.
This morning I went back to the project to continue and it's as if I hadn't made any changes, that is, FF somehow didn't save anything I did.
However, the changes that occurred in the fire base are still there and the app that I installed using the apk continues to run normally.
How to get it back?

### Expected Behavior

I expected the project to open today with the changes I made yesterday.

### Steps to Reproduce

1. I renamed pages and made several changes to all of them.
2. I moved these pages from the AddInformation folder to the ViewInformation folder.
3. I deleted the AddInformation page because it was empty.
4. This morning everything was back to how it was before, as if I hadn't done items 1, 2 and 3.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skfHqx891pbwA+KrTbcB7/SkQNmF9ROc0scpCbw4bIYj2P4lzY876PhBBTenmTWxqMFqcp14K/tnGkfGeGO1cFwqYfY9zzLpbVRaXXkegRZ+TF7WKZkZQI/5bfm6l1J+vuBNNKthtdUIt1EOQGu+vEj3tNLqyPXo8Sq/LZO4=

### Context

I'm developing an app for obstetric nursing management. This problem means I have to do a lot of rework and delay delivery of the app to my client.

### Visual documentation

![Captura de Tela 2024-01-15 às 14 34 44](https://github.com/FlutterFlow/flutterflow-issues/assets/47433250/803e890e-c01a-478a-a721-482f223473c0)

This is the page tree from yesterday, showing the PatientDetails page, before I started making changes. Today, after 6 hours of work, they appeared the same way as before, that is, without the changes made.

### Additional Info

![pacientDetails](https://github.com/FlutterFlow/flutterflow-issues/assets/47433250/6e36b836-e925-421a-b38a-c70003d9e923)

To give you an idea, the PatientDetails page that I left last night was this one, and not the one that appears in the project today.

### Environment

```markdown
- FlutterFlow version: 4.0 
- Platform: Android e iOS
- Browser name and version: Google Chrome
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by MartinLockheart** [comment]
One of my team members had the same thing happen a few days ago. Several hours of work gone. They've submitted a support ticket about it, looking forward to seeing what the cause is!

**Comment by takashiff** [comment]
Hi @MartinLockheart, I apologize for the delayed response. Did you have multiple tabs of the same project open when you made the changes that weren't saved to the project? Also, were/are you able to restore any of your lost work using snapshots? Thanks

**Comment by denissonsillva** [comment]
It’s solved. Thanks a lot!


Em qua., 31 de jan. de 2024 às 15:52, takashiff ***@***.***>
escreveu:

**Comment by takashiff** [comment]
That's great to hear! Thanks again for your patience!
