### ISSUE TITLE
Unable to run FlutterFlow built-in Actions' code from Custom Widget

### ISSUE THREAD

**Issue by evt3135** [FlutterFlow/flutterflow-issues#2176]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, since FlutterFlow doesn't offer a slider with non-step-sized values, I am using a Custom Widget to create a slider with discrete non-step-sized values [1,2,4,6,10]. However, I need to run some built-in "On tap" Actions when the value of this custom slider is changed. I was able to find the code for built-in actions here:

<img width="1133" alt="image (3)" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126603310/b05ab219-c1b1-43d2-b57a-c897285829e1">

But if I just copy/paste the code as is, it gives me this error:

```
Type: InvalidType
Undefined name '_model'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)
```

<img width="479" alt="image (2)" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126603310/dad2cbb4-3c05-4640-9de4-12f395036f58">

### Expected Behavior

I tried importing the _model file of the page and created a _model but it did not work. I should be able to just import whatever file I need and run those built-in Actions from the Custom Widget. Please help. Thanks. 

```
import '/pages/page_card_selector/page_card_selector_model.dart';

class _WidgetQuantizedSliderState extends State<WidgetQuantizedSlider> {
  late PageCardSelectorModel _model;
```

<img width="386" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126603310/617f551d-4a57-41a4-a8cd-698ed5401754">

### Steps to Reproduce

1. Copy the built-in Action code and paste it in a Custom Widget. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fhc7qx892ob1E7rruY8JVqCU5KUg2a+cv09Yacwgbfe7qE4oEd+LBcVhJYs+WTAk7eVqZpH4KzNLZkt7tE/knGE+BfLVq3bhqdQ7xVmWuMKqvEpC8OWgnM8FmI26f5JizhQx9FOx0WVIA3WGIPejKVinXK4C3DG1EPsiLCLDNpWi8GwDkUyFV3iRecCfn

### Context

I am trying to create a custom slider with discrete non-step-sized values [1,3,6,7,60] since FlutterFlow does not offer one. 

### Visual documentation

Images are already added. 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released January 15, 2024 (3.13.7)
- Platform: Web
- Browser name and version: Version 120.0.6099.217 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro Version 10.0.22621 Build 22621
```

**Comment by hariprasadms** [comment]
Hi @evt3135 - This is more related to how to use a custom widget. '_model' is not exposed outside pages, hence it can't be used. The error messages you see are expected. The code you use within the custom widget should be in its own scope and can only use the exposed properties and functions from other classes. Please refer to the custom widget documentation for more details on how to use it efficiently. I hope this can help you.

**Comment by hariprasadms** [comment]
@evt3135 - You can access the properties and functions from the imported classes, as shown in the first part of the custom widget. Additionally, user created custom actions can be accessed inside custom widgets. Please refer documents and youtube video for more informations. Thanks
