### ISSUE TITLE
adding enums with bulk .csv uploader failing

### ISSUE THREAD

**Issue by Desync-o-tron** [FlutterFlow/flutterflow-issues#2177]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when uploading a .csv containing an string that describes an enum, validation sometimes fails.
oddly it worked the first time I tried it with one enum, I added more enums and it failed. I then removed the other enums to the original working case and it failed again.
Switching the schema to a string will pass.
here's my .csv:
```
name,force
Barbell Curl5,push
```
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35696371/fbaf966b-c979-4738-bc9d-28619ef54c9d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35696371/8a486e78-829c-4954-9d21-407f40a097d6)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35696371/d090cd8c-852a-4605-b952-066797d91590)

### Expected Behavior

my data should update with the enums.

### Steps to Reproduce

see current behavior.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kicj134p2m+EA1pDuY8AxniksJkQ9U400ltVtSRUjfJuvG7YAW/SkQE9WZ7yhdH03I06jmToz+srNvebIN/FePgWZQNl51bgJVD3jUjqXaJTQEqq0f0FAEtpKCGqj1rWFpCZQOu9ZL2AA2GeqDfCUfCzbGOfqDUceR+WKGJLXnXfuQ0SLb3kNh1JWeC/v

### Context

I just want to use enums.

### Visual documentation

see current behavior.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: brave 1.61
```

**Comment by Desync-o-tron** [comment]
honestly after messing with this for another hour and looking at the documentation further, it would be nice if the documentation had a more complete example .csv
the example .csv from your [doc](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database-cloud-firestore/firebase-content-manager#upload-csv-file-for-bulk-addition):
```
name,location,last_updated
Central,"(40.76835069123224, -73.97203144014624)",2022-11-07 13:05:32
Museum,"(40.8217031079394, -73.9256367137398)",2022-11-09 16:12:02
Zoo,"(40.85452267684994, -73.8774290321384)",2022-11-04 03:05:54
```
this doesn't contain enums or lists, so the user is left guessing a bit on formatting.

**Comment by wenkaifan0720** [comment]
Hi @Desync-o-tron. Uploading enum data type is not supported on FF right now. I'll mark this as a feature request and nofity our dev team. Thanks!
