### ISSUE TITLE
Flutterflow app on Mac crashes

### ISSUE THREAD

**Issue by nishanthpasham** [FlutterFlow/flutterflow-issues#2178]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Crashes when Mac app is downloaded and launched for the first time

### Expected Behavior

App should launch

### Steps to Reproduce

1. Download Mac app from flutterflow.io
2. Open dmg and drag flutterflow app to Applications
3. Open flutterflow app
4. App crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89grs9J1s/Xbe0xpGQvQmV/TL0Ns+1uZxIjGLLoPJkUY876YlJWTeG+Sn03f2KJvD8dp82LuebIN8YqB0+afaY4/5ZpEzvMLWKQV4SgBc2wOnx6EtpKCm3Gy6S33yNNPuhZWV4F31OQCNyuYA/cGJz7PDMRR/mKJtnUo3PuQ0SLb3kNh1JWeC/v

### Context

Flutterflow too slow and unresponsive on Chrome. So wanted to try out the Mac app. But that crashed on launch, right after download from flutterflow.io website
[flutterflow_mac_crash_report.log](https://github.com/FlutterFlow/flutterflow-issues/files/13944046/flutterflow_mac_crash_report.log)

### Visual documentation

![Screen Shot 2024-01-15 at 7 23 57 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/11204601/d34b5771-e281-4a93-8642-24a915c89349)

### Environment

```markdown
- FlutterFlow version: Lastest (Jan 15, 2024) Mac app
- Platform: Macbook Pro 2019
- Browser name and version:
- Operating system and version affected: 2.4GHz 8-Core Intel Core i9 32GB 2667 MHz DDR4, AMD Radeon Pro 5500M 8GB Graphics
```

**Comment by hariprasadms** [comment]
Hi @nishanthpasham - Thanks for reporting the issue. I can confirm that the Mac version of FlutterFlow can be downloaded and installed successfully. I have tested it recently. Your case is unique and may be related to your OS version compatibility as well. Thanks for sharing the crash log details. We will look into it. Meanwhile, please check if any updates are required for your Mac OS, and see if that update can help resolve the issue. Thanks

**Comment by halfraf** [comment]
I'm also experiencing crashing since the latest update.

[flutterflow_mac_crash_report.log](https://github.com/FlutterFlow/flutterflow-issues/files/13990618/flutterflow_mac_crash_report.log)

**Comment by sbis04** [comment]
@nishanthpasham @hariprasadms we have recently released a new version of the macOS app. Can you install the latest version and check if the issue still exists?

**Comment by nishanthpasham** [comment]
@sbis04 I updated my mac to Sonoma 14.2.1 (23C71) and the flutterflow app now launched without crashing. Thanks!
