### ISSUE TITLE
Define API Call / Response & Test / Variables cannot accept a minus for negative values (read longitude)

### ISSUE THREAD

**Issue by rptoca** [FlutterFlow/flutterflow-issues#2179]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't enter the value of -96.501495 for a longitude variable

### Expected Behavior

I can enter a minus sign for a double variable

### Steps to Reproduce

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/140273737/012397c0-3a62-4775-be0d-9729cd1cabfd)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/140273737/2be7f1c8-1d5d-4aed-a1b4-6c962bfdc7f1)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXk8/f34pIvsBE187uc8dvr2IwGUwHargRidlETRQdfuP1E6QQY8/SXE9pWOqHSlVUOlqjglodwsLWuPPIFe06AAWrfKo+1pBPUxDgfzi6bqaPC82wP3dTHf5RCBGZ5JingCRSJu1oWV4g72CyPuiAb3qCf9qOYwx5e6fDbOY=

### Context

It was the first api call I attempted to define and I couldn't get it to run a test because I couldn't enter a test value of a negative longitude.

Note the Bug Report Code above was just entered to satisfy the required field.  The issue is in the definition of API calls and associated variables.

### Visual documentation

See images in steps to reproduce

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform: Uncertain, assume web
- Browser name and version: flutter flow desktop
- Operating system and version affected: Mac Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @rptoca - Thanks submitting the issue. Your issue details are not clear. when you say you can't enter the value of -96.501495, what really happening ? what error or warning message you see ?

**Comment by hariprasadms** [comment]
I just looked at your project. I can see you can use the value -96.501495. I hope you got the issue resolved already. If so, please close the issue. Thanks.
