### ISSUE TITLE
JSON/API response to data type can't be used in instances where a 3rd party API has fields beginning with _underscores.

### ISSUE THREAD

**Issue by buyblvd-ryan** [FlutterFlow/flutterflow-issues#2180]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, it's not possible to map some JSONs/API responses to data types because we can't give data type fields names beginning with underscores. Given the field the same name but without the underscore (e.g. \\\\\\\\\\\\\\\_rankingInfo -> rankingInfo) leads the mapping to fail.

### Expected Behavior

Ideally, it should be possible to give fields names beginning with underscores. Barring that, consider fields beginning with underscores to be equal to fields with the same name without the underscores (\\\\\\\\\\\\\\\_rankingInfo -> rankingInfo).

### Steps to Reproduce

1. Create a project.
2. Try to map a JSON with a field name beginning with an underscore to a data type.
3. Be sad when it doesn't work.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/q4ot1m/UC7r6JK+57/SIWNVw6bYISsct/cxQcB4j4EJoUf87CQE1vONSzaH1mP1WWkl4DwfSNj87yV/U4PSWVQKpDwqhQQxPPbHKlaKasDs+SfHNABcNVI2a+1ruGnghSXddoWi1h3F+MGPO+Zz6Cf9qOYwx5e6fDbOY=

### Context

As described above.

### Visual documentation

N/A

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4
- Platform: All
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @buyblvd-ryan - Can you please share the endpoint details that have responses beginning with '_'? Also, please set up a blank project with issue steps details to speed up the issue triage process, as it can delay the resolution. Thanks.

**Comment by buyblvd-ryan** [comment]
Hey there @hariprasadms, I appreciate you taking a look.  I'm using the Algolia Search API, which returns fields with labels like `_rankingInfo` and `_highlightResult`, and you can see an example of the problem in a project I just created and the image below. The mapped data type result shows the wrong value, where just using the JSON path works fine.

Bug Report Code:  `IT4Cl8n17YlOseFY+Kr+bsJR/TsvJjs5RY0omusaSUscHZPMC+wIZ/f7XFRuTde0Y29meVq0gnwe0NHemvLlC8cFAy2df65N+M9MFBXgYGGRac2JPM6wdG5/DdJTJ3641MGrmRFCHOpscVYc3UOlOPK9FxLdNu+3PVQ7IOWLIZOK2SrDX1iXc2URm05KZDPz`

![CleanShot 2024-01-17 at 12 04 43](https://github.com/FlutterFlow/flutterflow-issues/assets/117312895/a90f326c-ec89-49e0-be0c-473d86e90012)

**Comment by wenkaifan0720** [comment]
Hi @buyblvd-ryan. Thanks for the detailed test project! The no underscore constraint when defining data types is more of a Dart constraint, which we can't really do about it. However, when parsing a json response into a data type, we can certainly treat fields with/without the underscore the same. But I need to discuss further with our team to see if this could have any side effect. Thanks!

**Comment by appach22** [comment]
Yes, this issue need to be fixed. Neither Algolia nor many other external API's become partly or totally unusable due to this.

**Comment by buyblvd-ryan** [comment]
hi @wenkaifan0720 , just wanted to see if there was any update here.  struggling a lot using Aloglia still

**Comment by buyblvd-ryan** [comment]
@appach22 just in case anyone comes across this thread and needs a workaround, it can be done fairly easily with the new api response interceptor feature.  Posting an example down below that does exactly what we're talking about, just strips leading underscores from any key fields. Working fine for me and lets me map directly into a Data Type as we were hoping for.

```
class ProductSearchInterceptor extends FFApiInterceptor {
  dynamic removeLeadingUnderscoresFromJsonKeys(dynamic json) {
    if (json is List) {
      // Process each element in the list if it's an array
      return json
          .map((item) => removeLeadingUnderscoresFromJsonKeys(item))
          .toList();
    } else if (json is Map) {
      // Process each key-value pair in the map if it's an object
      var newMap = <String, dynamic>{};
      json.forEach((key, value) {
        // Remove leading underscores from the key
        var newKey = key.startsWith('_') ? key.substring(1) : key;
        // Recursively process the value
        newMap[newKey] = removeLeadingUnderscoresFromJsonKeys(value);
      });
      return newMap;
    }
    // Return the value directly if it's neither an object nor an array
    return json;
  }

  @override
  Future<ApiCallOptions> onRequest({
    required ApiCallOptions options,
  }) async {
    // Perform any necessary calls or modifications to the [options] before
    // the API call is made.
    return options;
  }

  @override
  Future<ApiCallResponse> onResponse({
    required ApiCallResponse response,
    required Future<ApiCallResponse> Function() retryFn,
  }) async {
    // Perform any necessary calls or modifications to the [response] prior
    // to returning it.
    var modifiedJsonBody =
        removeLeadingUnderscoresFromJsonKeys(response.jsonBody);
    return ApiCallResponse(
      modifiedJsonBody,
      response.headers,
      response.statusCode,
    );
  }
}
```

**Comment by leighajarett** [comment]
Thanks for adding this! Since there is a viable work around I am going to close this for now. I dont think we would change the ability to add underscores as field names in data types. But, we're hoping to support easier "mapping" in the UI at some point
