### ISSUE TITLE
Can't test projects with SQLite on web

### ISSUE THREAD

**Issue by leighajarett** [FlutterFlow/flutterflow-issues#2181]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Users that leverage SQLite who test their projects in the web get an error that `Field "_database" has not been initialized`

### Expected Behavior

We should warn users that they cannot test on the web and instead prompt them to test on a real device or an emulator

### Steps to Reproduce

1. Leverage SQLite in a FlutterFlow project
2. Test the project on the web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

This error has been reported through support and through the community forum

https://community.flutterflow.io/discussions/post/when-will-sqlite-be-available-on-flutterflow-DuReLGZchjxRqqi

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @leighajarett - SQLLight feature does not work on web at the moment. This is default behaviour of package we are using. Its here - https://pub.dev/packages/sqflite. I hope it can help you. Thanks

**Comment by itwrites** [comment]
What about supporting the web experimental https://pub.dev/packages/sqflite_common_ffi_web

**Comment by Empirome** [comment]
> What about supporting the web experimental https://pub.dev/packages/sqflite_common_ffi_web

It should be done to at least allow testing on Web.
