### ISSUE TITLE
"Intially expanded" property not working for dynamically generated Expandable widgets

### ISSUE THREAD

**Issue by AnirudhGoel** [FlutterFlow/flutterflow-issues#2183]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've a list of list of 4 strings:
<img width="996" alt="Screenshot 2024-01-16 at 2 01 35 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13799773/239ab8dc-f57d-4352-87e4-80ac59244974">

I'm dynamically generating 4 "Expandable" widgets using this list var.
<img width="642" alt="Screenshot 2024-01-16 at 2 07 22 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13799773/1883605b-6302-46dc-bba5-8762251d5f99">
<img width="298" alt="Screenshot 2024-01-16 at 2 07 53 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13799773/ea4dfb03-346f-4767-bffd-0fc63bb91d0f">

I've set the "Initially Expanded" property of the Expandable widget to true.
<img width="300" alt="Screenshot 2024-01-16 at 2 08 38 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/13799773/30dbaf61-a369-4194-a236-171a03d21c55">

But it is not working. All the expandables being generated are collapsed initially and have to be expanded manually every time. I've also tried replacing the ListView with a column.

### Expected Behavior

The dynamically generated expandables should be expanded initially.

### Steps to Reproduce

Add a ListView / Column Widget to your scaffold. Add a Expandable widget inside the ListView. Go to "Generating Children from Variable" tab of the ListView and use a list of strings to generate the expandables dynamically. Set the "Initially Expanded" property of the expandables to true.
Run the project, the expandables will be initially collapsed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlc/qx4V2rscA+KX+b8AwtGMRCUMbW40VldZ+FBMgGJDtBIh/fvfsV1VoZ8u9TWlhHE78+X8xw/CJuIbLGvk4JTWrQLZHyqlyUw/jUXq8RJPRDqWCR0Z6EeZUJm6l4YmN3SJNLsRYLFYi3UOUOPPLShXXGZ+/Zwh9f6PHaOI=

### Context

I'm trying to build an online food ordering app. This issue occurs on my restaurant's menu page. All the food categories are initially collapsed which hampers the User Experience and makes the page look awfully blank.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/13799773/7470046e-811f-449b-bf6d-0ad99e7d58c0

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.129
- Operating system and version affected: iOS and Android
```

**Comment by hariprasadms** [comment]
Hi @AnirudhGoel - Thanks for submitting the issue. Have you double-checked the issue in the web deployed version as well, please? If yes, can you please send the web app link?

Additionally, you have not provided the blank project with the issue set up. This can delay the issue resolution process. I would suggest setting up a blank project, reproducing the issue, and sending the details to us so that we can speed up the issue triage. Thanks.

**Comment by AnirudhGoel** [comment]
Hello Hari, thank you for the prompt response.

> Have you double-checked the issue in the web deployed version as well, please? If yes, can you please send the web app link?
I'm not sure I understand. If you mean, if I have checked the issue in the FF web platform, then yes, that's where I'm developing (I'm not aware if there're other development platforms as well). If you mean, the web deployed version as in a web version in addition to the iOS and Android platforms, then no, my app is not meant for the web platform, so I haven't tested there.

Regarding a blank project, reproducing the issue, here's the link - https://app.flutterflow.io/project/test-1oa09n

Kindly let me know if you require any more details. Hoping for a speedy resolution. 🤞🏻

**Comment by hariprasadms** [comment]
Hi @AnirudhGoel - Thanks for the details. i can confirm that this is bug. Below property is not set in the code. This will be fixed in future updates. 

<img width="863" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b216a439-c30f-444e-82a3-da18af0e98c6">

**Comment by AnirudhGoel** [comment]
Thank you for the confirmation @hariprasadms. I have 2 questions regarding this:

- Do we have a timeline for when it would be fixed and available on the platform?
- For the time being, is there a way that I can manually modify the code somewhere at my end to fix it for the current version of my apps? I'm using FF's mobile deployment feature for the Play Store and App Store deployment, so I'd prefer to not have to download the code for the modification.

**Comment by victoriahuang1** [comment]
@AnirudhGoel in the meantime, if you also set a max width or height (along with the min), it should work.
The fix will probably be deployed within the next week or so.

**Comment by victoriahuang1** [comment]
Marking as resolved, as this should be resolved upon the next deploy.
