### ISSUE TITLE
Cannot publish to web a project with share button

### ISSUE THREAD

**Issue by yairpe** [FlutterFlow/flutterflow-issues#2185]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a project that is targetting web with a share action, publish to the web fails.
Setting the share action in contional like `!is_web` does not help.
Removing the Share action everywhere allows web publishing to succeed
 

### Expected Behavior

Publish to the web should succeed even when there is a share action in the project.
If a share button is pressed in web, it should display a message (like in test mode): "Share doesn't work on web"

### Steps to Reproduce

1. Create new page
2. Add button with action of Share
3. Click Publish to web
6. Observe that project doesn't build: "Web Publish Failed"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8Wz/Hqx89grs9J1s/IdfoxnSQWQ2InargolusbTUgYDOutBIkPe87eUEtuTemoT3g/fE2kr3wKw+vsmITtU8cnAwutR9U6+qpUEDzNcziVepO3EKW8RH8nRMFYCW6v0MCN2RBNBMVfdXhm1zihPvW/SXTvJ4TWCzIvBv2ZNoLUs2DlGg3/KTsw4CkPGG2ZBvNnfQ6cuM+UtpJh0eDnyw==

### Context

Cannot publish my project to web.
Since the project targets web and mobile, cannot have share functionality on mobile AND publish to the web.

### Visual documentation

![Screenshot 2024-01-16 190506](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/11a86b8a-9684-438e-b348-048333a32f29)

### Environment

```markdown
- FlutterFlow version: 4.0   Flutter 3.13.7
- Platform: web
- Browser name and version: Chrome
- Operating system and version affected: Win 11
- project: test-project-share-with-web-publish-y680ek
```

**Comment by hariprasadms** [comment]
Hi @yairpe - Thanks for submitting the issue. I have tested the above steps, but I do not see any web deployment failures; it deploys successfully. Can you please retest it in a new project and confirm if this build failure still exists?

The message 'Share doesn't work on web' is displaying in the web app for the share action. This could be considered as an enhancement.

**Comment by hariprasadms** [comment]
I haven't been able to reproduce the issue you're experiencing. Can you confirm whether you're still encountering the problem? if not, please close the issue. Thanks

**Comment by yairpe** [comment]
Cannot publish my project (project id: mar09-dating-a-i-jc7x3v) to the web.
Removing the share actions from all places and the publish to web succeeds

**Comment by victoriahuang1** [comment]
Hi @yairpe , thanks for the report. I have identified the issue and this should get resolved once my fix is deployed.

In the meantime, you should be able to resolve this yourself by removing the name you assigned to the share action.

**Comment by yairpe** [comment]
Thanks a lot. Publishing for the web works now. @victoriahuang1 great job!
