### ISSUE TITLE
QR/Barcode scanner does not trigger route properly second time

### ISSUE THREAD

**Issue by Dbrrohof** [FlutterFlow/flutterflow-issues#2186]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

have created an "On page load" flow for one of my pages i use to scan barcodes with. This is the beginning of the flow:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f75edafa-dfa9-4e0d-94ad-0bfd7d1e1e01/0e13f101-59db-4974-ac63-abd3b47f6389?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNzVlZGFmYS1kZmE5LTRlMGQtOTRhZC0wYmZkN2QxZTFlMDEvMGUxM2YxMDEtNTlkYi00OTc0LWFjNjMtYWJkM2I0N2Y2Mzg5IiwiaWF0IjoxNzA3MTM4ODg3LCJleHAiOjMzMjc3Njk4ODg3fQ.AgFp9FUQkY286eIS10mrSzhSfQra9ER2sZ7nuxuCfsg)

If the user clicks "back"/"close" on the scanner it returns a value of "-1" and then it goes to the homepage based on this flow. This also works the first time, but if the user does the same thing again it doesnt navigate to the homepage. I have downloaded the code and added a print statement to verify that it is indeed reaching the correct point in the flow:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0a27b83a-2fff-4e38-91b4-d27aaf923d08/1bf53f29-a5d3-4c9e-87e4-7f61ebd02a56?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYTI3YjgzYS0yZmZmLTRlMzgtOTFiNC1kMjdhYWY5MjNkMDgvMWJmNTNmMjktYTVkMy00YzllLTg3ZTQtN2Y2MWViZDAyYTU2IiwiaWF0IjoxNzA3MTM4ODg3LCJleHAiOjMzMjc3Njk4ODg3fQ.D91lBHJqgy_AlaCKcfqy2IeBsUhIxiKpGdjpotL9sKI)

### Expected Behavior

When the router is called i expect it to go to the proper page set in the flow.

### Steps to Reproduce

1. Create a new blank page
2. Create a flow on "on page load"
3. Call the QR/Barcode scanner action
4. Add a condition to check the output of the scan if it equals "-1" (this is when the user clicks the back button)
5. If it is "-1" then go to the homepage
6. After this is setup now launch the app and go to the page. The qr scanner will load on page load
7. Click back once and the navigation to the homepage will work fine
8. Go back to the page and the qr scanner will load again.
9. Now click back and the navigation will not go to the homepage

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zMmBw41OxdsA+KryKPlFnmU5JUN6ao07mO5raCosfZT2BLMcec/RVERpTeG+d29IImf9mWoW0anlv+D1IfE6PRCBG9U4wpZyWwLJWkeWacmqFJWvPXR9M9pRfEfF34mFgRNvCNhqLndk2DuMf9+ySg3aJIf1ITEsDq/LZO4=

### Context

I want to launch the QR scanner on the click of a page (since it is not possible in the current flutterflow navbar to launch an action instead of a page) in the navbar, and then when the user clicks the back button they will be taken back to the homepage. Ideally they would return to the previous page, but that is not possible with the current navbar.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d574116b-bd3d-4294-91e1-87b9419a180c/b81bb3ab-3d64-4418-998d-c9a6ac629acf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNTc0MTE2Yi1iZDNkLTQyOTQtOTFlMS04N2I5NDE5YTE4MGMvYjgxYmIzYWItM2Q2NC00NDE4LTk5OGQtYzlhNmFjNjI5YWNmIiwiaWF0IjoxNzA3MTM4ODg3LCJleHAiOjMzMjc3Njk4ODg3fQ.jWmrUhyUR2La398OGIec7CdSQ7QCLgtL3T1uiOOtopg)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7507c3c6-3730-4211-8ecb-21bd0a8f7d26/640eddf6-3ae8-4426-be28-b8076fc64df9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NTA3YzNjNi0zNzMwLTQyMTEtOGVjYi0yMWJkMGE4ZjdkMjYvNjQwZWRkZjYtM2FlOC00NDI2LWJlMjgtYjgwNzZmYzY0ZGY5IiwiaWF0IjoxNzA3MTM4ODg3LCJleHAiOjMzMjc3Njk4ODg3fQ.kbZMx2pEW7EVV7x8GR5S8UtpiSObpwVGXnIhI3965vk)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: V4
- Platform: Web and Mobile
- Browser name and version: Google Chrome 120.0.6099.217 (Officiel version) (64-bit) (cohort: Stable)
- Operating system and version affected: Windows 11 Home 22H2
```

**Comment by Dbrrohof** [comment]
Any news on this? It is creating a very poor UX for our users when dealing with the QR scanner. 
If the flutterflow team can provide an alternative solution to how we can create a QR scan popup from the native navbar i'm all ears.

**Comment by paulperez-dev** [comment]
Hi @Ddrrohof, I'm sorry for the delay in the response, we are trying to get up to speed with everything. Are you still facing this issue? Your issue may be because you are trying to push a page that already is in the page stack. Did you try navigating back instead of pushing the page?

**Comment by paulperez-dev** [comment]
Closing this issue since we have not heard back.
