### ISSUE TITLE
Testing APIs appends a query parameter for JSON Body types

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#2187]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

[Forum posting](https://community.flutterflow.io/ask-the-community/post/why-is-a-query-parameter-being-appended-in-my-api-xwHlMVhkk2HpLO5)

When I try to test an API that uses variables for a body (either JSON or url-encoded), a query parameter is appended.

This did not happen before.

### Expected Behavior

I expect the prior behavior: the URL does NOT have an appended query parameter when I use a variable in a JSON body type.

I do expect the value populated with the test show up in the BODY.

I do expect the URL to remain WITHOUT a query parameter.

### Steps to Reproduce

1. Go to the API create page
2. Add variable to a body type of JSON or x-url-encode
3. Go to test
4. Check mark the variable you want to add

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

in API section

### Context

I am using external APIs and in order to define the JSON paths of the response, I need to be able to run the test.

However, the API calls are generating errors because of the query parameter, which is a malformed request.

### Visual documentation

[https://community.flutterflow.io/ask-the-community/post/why-is-a-query-parameter-being-appended-in-my-api-xwHlMVhkk2HpLO5](https://community.flutterflow.io/ask-the-community/post/why-is-a-query-parameter-being-appended-in-my-api-xwHlMVhkk2HpLO5)

### Additional Info

[https://community.flutterflow.io/ask-the-community/post/why-is-a-query-parameter-being-appended-in-my-api-xwHlMVhkk2HpLO5](https://community.flutterflow.io/ask-the-community/post/why-is-a-query-parameter-being-appended-in-my-api-xwHlMVhkk2HpLO5)

### Environment

```
- FlutterFlow version: v 4.0 January 14, 2024 release
- Platform: Macos
- Browser name and version: Brave Brave is up to date
Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.1.2
```

**Comment by hariprasadms** [comment]
Hi @timfong888 - Thank you for submitting the issue. If this is an existing API, have you tried deleting it and creating a new one with the same details? Please check and update the status accordingly.

**Comment by timfong888** [comment]
Yes it occurs with a brand new api. I fix it temporarily by copying an existing api.

**Comment by timfong888** [comment]
https://youtu.be/NbCankVxJNg @hariprasadms

**Comment by timfong888** [comment]
Why is this stale, has it been fixed?

**Comment by timfong888** [comment]
@hariprasadms still see the problem...thankfully the end-point does want a query parameter as a GET in this case, but still the underlying issue is when there's a POST, the expectation should *not* be to inject a query param when the API expects a body.....

**Comment by timfong888** [comment]
I still see the problem -- curious am I one of the only ones?

**Comment by paulperez-dev** [comment]
Hi @timfong888, I'm sorry for the delay in the response, we are trying to get up to speed with everything. Are you still facing this issue? I tried to replicate it on a blank project, but I was unable to do so.
