### ISSUE TITLE
Chrome browser going into loop after latest update. 

### ISSUE THREAD

**Issue by azvox** [FlutterFlow/flutterflow-issues#2189]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using an older version of Chrome browser. Flutterflow asked me to install the latest update yesterday. After the upgrade I cannot login with chrome, it is going into loop and the dashboard doesnt come up. I am now using Firefox, and it is working perfectly.

### Expected Behavior

Should have opened the dashboard on app.flutterflow.io

### Steps to Reproduce

1. Try to login with Chrome running on macOS 10.13. 
The version of Chrome is 116.0.5845.187 (Official Build) (x86_64)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

dashboard

### Context

Just trying to login
![Screen Shot 2024-01-17 at 11 01 48](https://github.com/FlutterFlow/flutterflow-issues/assets/7048213/e67fc5d0-8351-42b8-95ae-a18ca576faea)

### Visual documentation

[untitled folder.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13962380/untitled.folder.zip)

### Additional Info

Latest Flutterflow
 Chrome running on macOS 10.13. 
The version of Chrome is 116.0.5845.187 (Official Build) (x86_64)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @azvox - While the OS and browser versions aren't the primary factors, keeping them up to date is recommended for optimal software performance. If you're stuck at the loading screen, check the browser console for any errors.

**Comment by sbis04** [comment]
This could be due to some browser caching issue. Try opening the Chrome Inspect menu, then right-click on the Reload button and click "Empty cache and hard reload". I think it should solve the issue.
