### ISSUE TITLE
Flutter Flow Drop Down Latest update. Unresponsive page on dropdown select.

### ISSUE THREAD

**Issue by johnPgilson** [FlutterFlow/flutterflow-issues#2190]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Selecting a dropdown causes the page to freeze. This behaviour is apparent on any page where a dropdown is used.

### Expected Behavior

I would expect the drop down to work smoothly without freezing the page.

### Steps to Reproduce

Open a project built prior to the latest drop down changes, Either run the application in the test environment or download the code and run locally. Upon using one of the drop downs, the application / page will freeze.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4eicj6249OoeFK7q6JdcFajiMXQmYjU4ZMiuxhYAwgGJzoPZoqe+j+QHZVOMO/dFY3OlmI8T8x+sqMkuzEUfoXPiieQJRI1s1+czzKXnOiSrqREqrtQXMnGfhXCBSHzbWRmBNdOtNvLngM7EOAG9yAYAntN4zxPVYwAM6JOrPLogObAhzOXn0Jg1ZSfCvr

### Context

This issue prevents our App from being used due to the freezing issue when selecting a dropdown.

### Visual documentation

NA

### Additional Info

The issue is with the updates made to flutter_flow_drop_down.dart

As a temporary work around, I have replaced the flutter_flow_drop_down.dart file with a copy of the file from a previous deployment (pre 12th Jan update) and commented out the search styling properties (Not used with the pre 12th Jan version of the drop down) in the page widget where these are used.

### Environment

```
- FlutterFlow version: 4.0
- Platform: All (Windows, MacOSX, IOS, Android, Browser)
- Browser name and version: All tested browsers.
- Operating system and version affected: All tested OS.
```

**Comment by johnPgilson** [comment]
Is this being investigated?

**Comment by leighajarett** [comment]
We're working on it! Sorry about the delay @johnPgilson

**Comment by johnPgilson** [comment]
Any updates on this one?

**Comment by rzambroni** [comment]
Hey @johnPgilson, I'm sorry for the delay in the response, we are trying to get up to speed with everything.

Are you still experiencing these freezes? I was trying to replicate it on a blank project so we could better isolate the issue with the component, but I was unable to do so. It is working well on my end. 

Are you able to reproduce this issue on a blank project? if so, could you please share the bug report code of that blank project?

It would help us a lot, so we can discard project-specific issues and better isolate the problem with the dropdown.
