### ISSUE TITLE
Persisted app state with a list of enums doesn't retain the set value

### ISSUE THREAD

**Issue by leighajarett** [FlutterFlow/flutterflow-issues#2191]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

(This was brought up with a customer on support but I was able to recreate in a test project)

When I create an app state using a list of enums, the value for the items is removed after navigating away from the page. See attached screen recording for an example.

### Expected Behavior

The value set for the item should remain after navigating away from the page

### Steps to Reproduce

1. Create an enum
2. Create a data type with a field that leverages the enum
3. Create an app state field that is a list of the data type you created
4. Set the value of an item to an enum value and save
5. Go to a different page and come back to the field

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+Kn2avlWoCERM0MfWOdEket+EA0hfJfpPbMQduLRQEpLYteRYH9cfVf8hmME0eCMjdn9EsYpISSZGq46zoRXQRXxVmS6M6qVDpbtbUZQEphPfnax4auFkR14GLBtWHNk602YIPCrG3qCf9qOYwx5e6fDbOY=

### Context

This issue is preventing a customer from moving forward with their development.

### Visual documentation

[app_state_issue.zip](https://github.com/FlutterFlow/flutterflow-issues/files/13964600/app_state_issue.zip)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Arc Version 1.25.1
- Operating system and version affected: macOS sonoma 14.1
```

**Comment by gwwb2024** [comment]
i am also having this issue

**Comment by hariprasadms** [comment]
Hi @leighajarett - I can reproduce it. Thanks

**Comment by alan-crts** [comment]
Hi, I have the same issue

**Comment by takashiff** [comment]
Hi all, this bug has been fixed recently, so I will be marking it as closed now. If the issue persists, feel free to follow up in this thread. Thank you for your patience and continued support.
