### ISSUE TITLE
marketplace components errors: permission and projects

### ISSUE THREAD

**Issue by Miamoto-Musashi** [FlutterFlow/flutterflow-issues#2193]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

adding a component from the marketplace show a permission error and does not show all my projects, only one

### Expected Behavior

the component downloaded from the marketplace is added correctly to selected project

### Steps to Reproduce

1. open my dashboard in marketplace
2. select first component
3. see the permission error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SlefqwItOpbxJ7qX2bsEw+SoUKVAjRYI7lexqEAoYIpOtPOwxXOj9VEpoTcOHd2xEOlmY8XsK0NmOkeDlEsI9PiiCfKZmzqpxFg7ic3KtMZivDM6BOXB5L59VG22Hzbe33xVRNvdYWFo4wFyqH+68ZA/sO5f6C1UNAcikEJ/IpGDnLTLOXn0Jg1ZSfCvr

### Context

adding a marketplace component to my project

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/283196/e4086db7-4edd-4a4c-806d-e987e7188096](https://github.com/FlutterFlow/flutterflow-issues/assets/283196/e4086db7-4edd-4a4c-806d-e987e7188096)

### Additional Info

you can notice 2 errors:
component show permission errors
not all my projects are shown but only last one

### Environment

```
- FlutterFlow version: 4.1.20
- Platform: MacOs
- Browser name and version: Edge
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @Miamoto-Musashi - Thanks for submitting the issue. The above provided video is not playing. Please check.

**Comment by Miamoto-Musashi** [comment]
@Hi @hariprasadms, [here](https://www.loom.com/share/6292b7f1e9df44ef8f54d603f173004f?sid=e2d66ff2-8baa-49bc-a0ec-09ba58bf8e7e) a link to watch it online

**Comment by hariprasadms** [comment]
Hi @Miamoto-Musashi - Appreciate for sharing the video. I've verified the steps and successfully replicated the steps outlined. The permission message appears when attempting to add a market item to projects without access, particularly when multiple FlutterFlow accounts are open in different browser sessions. However, upon closing the browser sessions and opening a single FlutterFlow account associated with the project, the steps worked smoothly, and no permission message was displayed. 

Try this and let me know how it goes.

**Comment by Miamoto-Musashi** [comment]
Hi @hariprasadms tried the workaround but didn't solved I only had one browser session and still the message appeared; also the project list does not show all projects I have (in the video you can see I have 2 projects on my dashboard but only one is shown on the marketplace list)
thx

**Comment by wenkaifan0720** [comment]
Hi @Miamoto-Musashi. I checked your account and your user data looks normal to me. Could you try to log into marketplace in incognito mode and see if your two projects show up correctly?

**Comment by Miamoto-Musashi** [comment]
Hi @wenkaifan0720 yes thanks in Incognito solved.

BR
