### ISSUE TITLE
No font family by name 'Telegraf' was found

### ISSUE THREAD

**Issue by prossion** [FlutterFlow/flutterflow-issues#2194]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The program crashes when loading with a custom Telegraf font

### Expected Behavior

The program works without crashes, just like with other fonts

### Steps to Reproduce

1. Upload custom Telegraf font to FlutterFlow
2. Make this font Primary and Secondary Font Family
3.Set this Font Family to all of the Style Names
4. Set a font for some text
5. Run the program in "Test Mode"
6. Get an app crash and error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfksrlvJdOm8NA7a6JcO5VmiQUQ18cTeUzlO1hdwwbI+PwOoYqPs+kM0htSOqHT35IJ2aIrE8x+dWKiezxO+03NS+ZbLly/85TUxDjfD+lMYyyDpaoeHx5BeRWGFSM37W3pB1BB/pfdCVl7F6uJeyua3qCf9qOYwx5e6fDbOY=

### Context

I need to use the Telegraf custom font in the project

### Visual documentation

<img width="518" alt="Screenshot 2024-01-17 at 19 58 37" src="https://github.com/FlutterFlow/flutterflow-issues/assets/67923348/7e0d4545-a23f-4225-93d3-152fb2bf9c24">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.216 arm64
- Operating system and version affected: MacOS & Windows
```

**Comment by hariprasadms** [comment]
Hi @prossion - Are you still experiencing the issue ? did you test this in another new project ?.
I just tested with with same font package, it all works fine with no build error. See below. 

<img width="542" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/78852a62-70c3-42de-b112-cfbd0a2aa9f7">
