### ISSUE TITLE
Initial Page Requires spot on nav bar

### ISSUE THREAD

**Issue by livecleanly** [FlutterFlow/flutterflow-issues#2195]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to set up custom routing when a user logs in, I am not able to set the mission control page to be the logged in page. It gives an error saying that the logged in page must have a nav bar. I added a nav bar, but it doesn't fix the issue. When I add the mission control page to the nav bar, it works and lets me set the page... but I don't want the mission control page to be on the nav bar... I don't really even want it to have a navbar on it

### Expected Behavior

I can set a simple splash screen with an animation on it as my mission control page. From here, I can route to different versions of my app home page for different user types

### Steps to Reproduce

1. Create 2 pages
2. Add a navbar to one of the pages
3. Set one of the pages to be the not logged in landing page and the other to be the logged in landing page
4. See that the page without a navbar isn't able to be set as a landing page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

I need to set up my app to have an onboarding flow for new users or hit the home screen for existing users. I am also considering a different flow for admins vs customers within the app

### Visual documentation

<img width="415" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/149027529/fcfaae4c-6f38-4b69-b616-99e7aba96c4e">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @livecleanly - The current behaviour aligns with the existing design. With authentication enabled, the landing page should be incorporated as part of the navigation bar items. It's advisable to adjust the app route settings accordingly it. I hope it can help you. Thanks
