### ISSUE TITLE
App Crash on IOS. 

### ISSUE THREAD

**Issue by rodnickel** [FlutterFlow/flutterflow-issues#2198]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We deployed the app to the Playstore and Apple Store. It worked well in both places, but now it doesn't work in testflight.
The app closes before showing the home screen.

The crash report is confusing. We need help understanding where the problem is, as there are no error warnings on the flutterflow platform.

I will attach the bug reports.

[crashlog-EA488AE2-D8FF-4C2E-9B1A-A2763C4562BB.txt](https://github.com/FlutterFlow/flutterflow-issues/files/13978901/crashlog-EA488AE2-D8FF-4C2E-9B1A-A2763C4562BB.txt)
[crashlog-7D43854B-5ECF-4F7F-8F15-CE5FB9FB5FAC.txt](https://github.com/FlutterFlow/flutterflow-issues/files/13978902/crashlog-7D43854B-5ECF-4F7F-8F15-CE5FB9FB5FAC.txt)
[crashlog-038D28D7-0DD7-4B89-9AF0-B98405554DE4.txt](https://github.com/FlutterFlow/flutterflow-issues/files/13978903/crashlog-038D28D7-0DD7-4B89-9AF0-B98405554DE4.txt)

### Expected Behavior

The application should load without errors

### Steps to Reproduce

We download the test flight
we install the app
we click open
the app starts opening but closes before the first screen appears

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjfLl05NJtbxa1s76afpR/SEvHH56bLgoscp/bxIgGIDzPOw+ZPXsVE1pUuqoSnNbPkSmmnkC0PzQi/HxGvABOUicGot8ypB2ehaUfFG6UZOBDbi3dUZ6EeZNCUiy0aW3sSVSAPh2cXgk3WCIJOu8SXbsN5TLImdISq/LZO4=

### Context

The problem prevents testing and approval of the app in the Apple store. Our app is already published on plyastore.
We are trying to publish our app on the apple store.

### Visual documentation

We don't have images because the app doesn't even open. the crash reports have already been attached above.

![WhatsApp Image 2024-01-18 at 13 17 42](https://github.com/FlutterFlow/flutterflow-issues/assets/122025955/2639fced-4f11-43f0-99f6-8bd59d186ed0)

### Environment

```markdown
- FlutterFlow version: Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome 120.0.6099.217
- Operating system and version affected: IOS - All versions
```

**Comment by pfreund** [comment]
Same issue here.
No errors, no logs, no crashlytics. App just won't start, but works well with Android.

**Comment by rodnickel** [comment]
@hariprasadms news? tks

**Comment by hariprasadms** [comment]
Hi @rodnickel - Thank you for reporting the issue. Could you please regenerate the FB configuration files within the FF editor and try to deploy to TestFlight again? I recently encountered a similar issue in my test app, and after regenerating the FB config files, the issue was resolved. Please give this a try and let me me of the results. Thanks

**Comment by pfreund** [comment]
Personally I still have the problem after regenerating Firestore config files and a new deployment to TestFlight.

**Comment by rodnickel** [comment]
Good morning.
regenerate the configuration file and it didn't solve the problem.

**Comment by rodnickel** [comment]
@pfreund After seeing your message, we deployed it to test, and it also worked here.
@hariprasadms Did you detect a bug? It is important to see if something was fixed and resolved the problem.

**Comment by spandey1230** [comment]
I Just faced the same issue, the app was deployed to Play Store and App Store, works perfectly through Play Store, but through TestFlight, it crashes immediately when opened, tried it on different iOS devices too, no crash logs, please help.

https://github.com/FlutterFlow/flutterflow-issues/assets/23615854/b4aa983f-598f-463f-9d45-f03508b06bdb

**Comment by takashiff** [comment]
Hi @rodnickel, we recently had several reports of the same issue, which was being caused by an issue with Facebook Auth. We've resolved the issue and put in a fix with the last deploy. Thank you for your patience.
