### ISSUE TITLE
Slider value tooltip not rounded as per setting

### ISSUE THREAD

**Issue by ready4sea** [FlutterFlow/flutterflow-issues#2199]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting slider properties to show a rounded integer, the slider "bubble" or "tool tip" that shows the value incorrectly shows a decimal value, i.e. 12.0 instead of 12

### Expected Behavior

When choosing the settings "Show Value", "Round Value" and "Num Decimal Places = 0", I expect a whole number to be displayed, i.e. 12, not 12.0

### Steps to Reproduce

Create a new page
Add a slider
Toggle the settings "Show Value" and "Round Value" to true.
Set the "Num Decimal Places" to = 0

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hubZ27NNm+VF+7vqX/FUnWMQNVAFWuQZk+traCgsfaLuBJkQdvWkUBdWZ9+rYXxIf0Smmkwd+vvHvuLxLMAnCEmbGoBAzpN2dwKXLWqtUZOBPaqwZHdREexWf23G16W7sBIkPfVsdF5h7FyIPd+XdC3tJrX4IndISq/LZO4=

### Context

The slide can be used to show any discrete steps, such as a number of days, weeks, months or years. Or a priority level. Or the sound volume. All these are usually shown as whole numbers and users find it strange when they are displayed as decimals.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ceac4460-1693-4a35-bc7a-c9591f2e954c/85a2c804-f9c7-4d87-a37b-ca7cf41fbea9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZWFjNDQ2MC0xNjkzLTRhMzUtYmM3YS1jOTU5MWYyZTk1NGMvODVhMmM4MDQtZjljNy00ZDg3LWEzN2ItY2E3Y2Y0MWZiZWE5IiwiaWF0IjoxNzA1NzQzMzM3LCJleHAiOjMzMjc2MzAzMzM3fQ.k0_YBjhMoNU8nRqPkC00JrWcCj_m4TGItE_QhCX2Q0U "=394x")

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/70a444e2-ac02-49d8-9e7f-d5d4dc60f95d/4f418366-7678-4c92-acf0-b339c94f6b74?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MGE0NDRlMi1hYzAyLTQ5ZDgtOWU3Zi1kNWQ0ZGM2MGY5NWQvNGY0MTgzNjYtNzY3OC00YzkyLWFjZjAtYjMzOWM5NGY2Yjc0IiwiaWF0IjoxNzA1NzQzMzM3LCJleHAiOjMzMjc2MzAzMzM3fQ.l9v_K8A2dlxu2TOvHqhEMDObxsMIDJ-KYKKz-BBn9mQ)

### Additional Info

This is clearly feasibly in Flutter, as shown in the Slider class documentation :
[https://api.flutter.dev/flutter/material/Slider-class.html](https://api.flutter.dev/flutter/material/Slider-class.html)

The key is that when the settings point to displaying a whole number, then the label attribute should read :
`label: _model.sliderValue.round().toString()` instead of `label: _model.sliderValue.toString()` as it does now.

See also : [https://blog.logrocket.com/flutter-slider-widgets-deep-dive-with-examples/](https://blog.logrocket.com/flutter-slider-widgets-deep-dive-with-examples/)

### Environment

```
- FlutterFlow version: v4.0 (Flutter 3.13.7)
- Platform: MacOS, iOS, Android
- Browser name and version: Chrome 120.0-6099.216
- Operating system and version affected: MacOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @ready4sea - It works fine in a project with exact your settings. Are you still experiencing it ?

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/cac1c568-38f3-4d92-87e0-41145232d8ce

**Comment by ready4sea** [comment]
Hi @hariprasadms ,

Thank you for reviewing the issue. Sadly, however, I am still experiencing the issue.

I should have mentioned that I am testing **in a simulator** after fetching the code **using FF CLI**. I just tried test mode like you did and it's fine there. On a device, though, it's not OK. This is consistent with the code being generated which looks like it is a double behind it all and that double is being transformed with `toString()` with no rounding or formatting.

<img width="383" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/105978018/e809857b-e8a1-4d6c-aae4-30ad8cbb1121">

**Comment by hariprasadms** [comment]
Hi @ready4sea - Thanks for confirming. I can reproduce the issue in iOS simulator.

**Comment by mae3555** [comment]
Hello, I have the exact same problem...

**Comment by ready4sea** [comment]
Any news regarding this ? It's still happening.

**Comment by leighajarett** [comment]
So sorry for the delay here! We have a fix that is about to get merged and should be out in production in the next few weeks. Thanks so much for your patience
