### ISSUE TITLE
Custom Code Actions Error "Function Name does not appear in the code"

### ISSUE THREAD

**Issue by gotruckly** [FlutterFlow/flutterflow-issues#22]
Renaming / Creating new Custom Code introduces " Custom code action is named "x" but this function name does not appear in the code." Issue (error). Can't resolve issue without deleting action. 

## Expected behavior (required)
 New Custom Action being used in Code resolves issue (error).

## Current behavior (required)
New Custom Code Actions creates issue (error) that restricts you from running code, etc.)

## To Reproduce (required)

1. Create new Custom Code Action
2. Add Custom Action to Action Flow
3. Error is not resolved

## Context (required)

Unable to test code because of error catching / blocking 
Unable to download code because of error catching / blocking

## Screenshots / recordings 

![image](https://user-images.githubusercontent.com/111748375/193415822-9f5ee014-3312-472c-8d36-ffdc7249a5f5.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop 
* Browser name and version: Chrome
* Operating system and version (desktop or mobile):

**Comment by Pepino-GR** [comment]
Hi gotruckly,

I can't reproduce the issue following your 'To Reproduce' steps. Could you please show us your custom action code to see what happened there?

**Comment by gotruckly** [comment]
My apologies. I discovered the root cause of the error. When you duplicate a function, it changes the functions addressable name in FF, however, it does not rename the true function inside of the Custom Code. Therefore, even when referencing the Custom Code action in the actual Action, it throws an error because the true function name is not being called. 

Consequently, this would be more of a feature request to 
1. test the case in which:
The reference name and function name are mismatched.
2. Throw exception if top most function name (in function body) doesn't match the reference custom code action name.


<img width="902" alt="image" src="https://user-images.githubusercontent.com/111748375/193628549-a461eddf-06a5-4332-ac48-2844f40afb77.png">

**Comment by Pepino-GR** [comment]
Thank you for your troubleshooting result.
