### ISSUE TITLE
Non Dismissible Bug (In New Update)

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#220]
Setting the new Non Dismissible variable to true will result in this bug when trying to run:
![image](https://user-images.githubusercontent.com/67612575/207172133-9535315d-260b-4ac4-a875-c9a859be27eb.png)

Tested on multiple projects...

How to recreate: Simply create a component and have an action that calls it while setting the "Non Dismissable"  to true and you will not be able to run the project

(even is if you have a Close popup action inside that component)

Hope this helps to fix it

 Seems like the dev team misspelled isDismissible with isDismissable. I've had to change this multiple times after downloading the code to VS.

**Comment by bulgariamitko** [comment]
Original community post - https://community.flutterflow.io/c/bugs/non-dismissible-bug#comment_wrapper_13674862

**Comment by Josefpa** [comment]
> Original community post - https://community.flutterflow.io/c/bugs/non-dismissible-bug#comment_wrapper_13674862

Yes I posted it on the community but also put it here :)

**Comment by wenkaifan0720** [comment]
We have fixed this issue in the dev channel. Should be out in a few days.

**Comment by bulgariamitko** [comment]
Can you make it as fixed? I am not allowed to do this :D

**Comment by Josefpa** [comment]
Nice and quick! Great job team!
