### ISSUE TITLE
RatingBar renders incorrectly. Icons that should be in Unrated color are instead rendered in Rated color and with blur

### ISSUE THREAD

**Issue by RickAtSavveLabs** [FlutterFlow/flutterflow-issues#2208]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Rating bar should render using specified Rated and Unrated colors. Instead, the icons that should be in the Unrated color are in the Rated color, but they are rendered slightly blurry. 

In the attached image, I specified a rating of 2 out of 5. If you look closely, you will see stars 3-5 have a slight blur. They should have been in the Unrated color of grey, which I had specified.

![Screenshot of Safari at Jan 20, 2024 at 7_48_07 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/7e4cd6c0-8452-4217-bd6b-49fa94fe21d7)

### Expected Behavior

Stars 3-5 should have been rendered in the Unrated color.

### Steps to Reproduce

1. Define an app state variable for rating and give an initial value of 2
2. Add the RatingBar to page
3. Set the RatingBar to be interactive
4. Set its initial value to be the app state variable
5. Define an "On Tap" action for the RatingBar that updates the app state var
6. Set the Unrated color to be something very different than Rated color
7. Run in Test Mode. 
8. You will see a result similar to that in the image attached above.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Received an error from FlutterFlow when I tried to get the code

### Context

My interface looks like the user is not able to change their rating of something.

### Visual documentation

![Screenshot of Safari at Jan 20, 2024 at 8_03_50 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/31de5daa-1100-4372-a3cf-32bc2bdbf82d)

### Environment

```markdown
- FlutterFlow version: v4.0 - Flutter 3.13.7
- Platform: Mac
- Browser name and version: Safari v17.2.1
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @RickAtSavveLabs - This issue is duplicate with #2169. Hence close the issue. Please refer the linked issue to track the status of the bug. Thanks
