### ISSUE TITLE
Test Mode Screen Size Reveals Safe Area Rendering Bugs

### ISSUE THREAD

**Issue by chris-PearlIT** [FlutterFlow/flutterflow-issues#2209]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running my app in test mode the available screen size is greater than the builder screen size. Test mode only runs in full screen mode ?
I cannot access the height of the safe area when using the getter MediaQuery.of(context).size.height - (MediaQuery.of(context).padding.top + MediaQuery.of(context).padding.bottom)), it just returns the MediaQuery.of(context).size.height.

### Expected Behavior

99% of apps made will be running in the safe area, it is VITAL that when designing apps you have access to this double. If i want to create an non scrollable page with flutter flow my only option is to use flex widgets. I cannot create a page of widgets whose total height is equal to 100% of the safe area height because i have no idea what it is with FF. What i am seeing in test mode is not a representation of a real device at all.
If i describe a widget's height as 20% and that widget is a child of the safe area widget then it should be 20% of the safe area height.

### Steps to Reproduce

1. Set device to iPhone 14 Pro
2. Verify screen size is 393 x 852 px
3. Create New Page
4. Add Row
5. Add Container
6. Set container height to 100%
7. Add Container
8. Set container height to 758 px
9. Run in test mode
10. set test device to iPhone 14 Pro
11. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkOfl0It1pbxK+KX6b8BsnjgXMjs6bIJNm9YacCs8GZT0B4kcYs+kfklUOLC+dG9qfE78jmIX/MrGiIf1VsYpNReeR5xEyaViTxXJUmChR7KzCa63b3NCI/hPf1Cc35iZhiMkPbZ2L1INwzqYGNysZB/dJKGzNWwFR+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to make a responsive app, If I have a minimum android SDK of 23 and iPhone's of 13.0 + then I have 17,000 different devices with 17,000 different safe area heights.
I have requested in FF's wish list that they include a Global Constant called safeHeight. But the Emulator needs to include the system and navigation bars, or possible have a toggle to switch in and out of full screen mode.
I honestly don't know the best way for FF to handle this, I just know that it's currently a problem. When i download my code into VSC and run it on multiple android devices i have overflows everywhere !

### Visual documentation

Difference in screen size between my build UI and the Emulator. Both are set to Samsung Galaxy Note 20 which has a size of 412 x 916. I'm looking at them both at 100%.
![Screenshot 2023-12-09 224622](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/e1a99bd6-fa42-44e6-b753-d9f03f2e413b)
Both displays are running at the px size I wrote above, but the emulator doesn't seem to be taking my system and navigation bars into account as evidenced by the extra space below the "Birth Surname Until" widget.
![Screenshot 2023-12-09 224639](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/80d30aeb-7d9e-47a9-ab0b-a09429af5471)
A more visual representation using an iPhone 14 Pro.
The Builder
![Screenshot 2024-01-21 005838](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/50d3683b-9281-406a-8e1a-c1fcee7a0ee0)
The Emulator
![Screenshot 2024-01-21 005847](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/4b1c16b3-4d2d-4b72-9a84-f9a21f3063f3)

### Additional Info

I've tried to get around the problem by setting an App State variable called safeHeight and running a custom action in the build of my first page. The below was used with the device set to iPhone 14 Pro.
![Screenshot 2024-01-21 005923](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/8d877f8c-4f03-4c76-b544-7bda8373bdf9)
However this does not return any usable information. This is my console log from chrome.
![Screenshot 2024-01-21 005856](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/bb452d2f-ceee-483b-b1b1-edd4719f1cb7)

### Environment

```markdown
- FlutterFlow version: 4.0 - flutter 3.13.7
- Platform: Windows PC
- Browser name and version: Chrome 120.0.6099.225 (64-bit)
- Operating system and version affected: Windows 11 Pro 10.0.22621 Build 22621
```

**Comment by wenkaifan0720** [comment]
Hi @chris-PearlIT. Thanks for the very detailed explanation! Really impressed. 

The reason you are not getting the expected safe area is because right now test mode is only accepting the device size as an input, not the device safe area (as opposed to the builder). We have considered of passing this information but ran into some trouble. Since we have been seeing people asking for this feature, we might give it another try. 

The good news is, we will soon launch a new app called flutterflow runner, which will let you run your FF apps locally on any emulator/real devices. This should give you the desired result, and a much smoother testing experience. Stay tuned!

**Comment by chris-PearlIT** [comment]
That sounds amazing, I'm used to coding in VSC and running my builds on a real device so I'm really looking forward to that.
I do still stand by my comment about describing widget height by % when it is a child of the Safe Area. Any chance of getting a Global constant of safeHeight ? I know it currently wont affect the way it looks in test mode but at least it'll work correctly when apps are released.

**Comment by wenkaifan0720** [comment]
I think it is a valid suggestion and will bring it up to our dev team for review. Thanks!

**Comment by chris-PearlIT** [comment]
I'm a little worried about the classification of this issue, I am currently seeing daily posts from community members asking why their apps work in FF but on a real device they're getting overflow issues. All I can do for them is refer them to this page so they understand their issue. In reality, with the very much needed implementation of padding by variable this issue is becoming more prominent.
This is not a feature enhancement, it's causing problems for people when their apps leave your environment and graduate to real world devices. 
I'm only asking that when you pass this to the dev team you stress the importance of tackling this issue sooner rather than later. Thanks
