### ISSUE TITLE
Styled Divider

### ISSUE THREAD

**Issue by kjoyceee** [FlutterFlow/flutterflow-issues#221]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Add Styled Divider to app

## Current behavior (required)
Works on the FlutterFlow platform, but when export code it doesn't add styled_divider to pubspec nor does it add the import to the code.

## To Reproduce (required)
1. Create page
2. Add divider to page
3. Change to dotted
4. Export

### Bug Report Code
"Failed to generate bug report code."

**Comment by wenkaifan0720** [comment]
Hi @kjoyceee. Could you share with me a project link? I just tried it and it is working.

**Comment by wenkaifan0720** [comment]
OK. I just created a new project and can confirm this is a bug. I have pushed a fix for it. Thank you!

**Comment by kjoyceee** [comment]
Hi @wenkaifan0720 sorry I just saw the email you replied. Glad to see its been resolved. Thank-you.
