### ISSUE TITLE
All side draws not displaying properly 

### ISSUE THREAD

**Issue by ValetCEO** [FlutterFlow/flutterflow-issues#2212]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I woke up on Thursday morning to find that all side draws had a transparent strip down the right-hand side. This has happened on every single side draw on every single page. I've tried to reach out to support but i'm getting no response. I've now also noticed that on custom alert dialogs the grey-out is also only taking up a small section of the screen.

![Screenshot 2024-01-21 at 13 54 41](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e5c498a9-c117-452c-9305-d9aeda4a1604/18bef9ff-eea7-4ba5-a6ff-b12b8601c5bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNWM0OThhOS1jMTE3LTQ1MmMtOTMwNS1kOWFlZGE0YTE2MDQvMThiZWY5ZmYtZWVhNy00YmE1LWE2ZmYtYjEyYjg2MDFjNWJiIiwiaWF0IjoxNzA3MTc5NzcyLCJleHAiOjMzMjc3NzM5NzcyfQ.enwG9VDlB25TTKZ-Zzh-z5QFYHwhnaH4x7IFlWalc-k "=1680x")

![Screenshot 2024-01-21 at 14 03 35](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/51a79d2a-3541-4ec2-995a-c6bb20d40061/2e3e175e-0aac-412b-b1a6-91148423101d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MWE3OWQyYS0zNTQxLTRlYzItOTk1YS1jNmJiMjBkNDAwNjEvMmUzZTE3NWUtMGFhYy00MTJiLWIxYTYtOTExNDg0MjMxMDFkIiwiaWF0IjoxNzA3MTc5NzcyLCJleHAiOjMzMjc3NzM5NzcyfQ.j8F1ctT8H-n5Od2YeWHw6uCSPDv88xp5DM34hVgkftg "=1680x")

### Expected Behavior

Side draws should take up all the space to the right

### Steps to Reproduce

1. Log into my project
2. Click any of the plus icons on any page
3. See that the side draw has a transparent strip
4. On the home page tap on the 'open tasks' tile and see how the greyout doesn't cover the whole screen

I have no idea if this will work from a blank project, this is being seen on my project and as I said above I'm getting 0 response from support on this.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcrqw5VOsdhE7c+BbPowoDwWHG4jRYEn1usbGAk0N5PNDIlzZP/eTEpoONOrdghmO2GgjmIK09aJm9z1KcFeFxOrbYBH1c9PFg3Nd3yQRYvQBZOKQHNUGshUfGqe5p2juBVDNvBoWEZg7XGMO+7IEnfrN5DEC0dMDs//DJvXmAfuQ0SLb3kNh1JWeC/v

### Context

I'm unable to go live with my app while this issue exists

### Visual documentation

![Screenshot 2024-01-21 at 13 54 41](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fac73015-bfd7-48fb-8a52-a34b76066fcf/09a1dd5b-5af1-4e61-93e2-9d2b9e59a591?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYWM3MzAxNS1iZmQ3LTQ4ZmItOGE1Mi1hMzRiNzYwNjZmY2YvMDlhMWRkNWItNWFmMS00ZTYxLTkzZTItOWQyYjllNTlhNTkxIiwiaWF0IjoxNzA3MTc5NzcyLCJleHAiOjMzMjc3NzM5NzcyfQ.OVu9dLSkhMMcxqWY92b4aXDicMFthjg0rr6ZDdRPv4M "=1680x")

![Screenshot 2024-01-21 at 14 03 35](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/60b9f788-8b8a-467b-a881-38e4bf53cfd2/077681e9-2cd9-4cd8-b6b8-b046599edf9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MGI5Zjc4OC04YjhhLTQ2N2ItYTg4MS0zOGU0YmY1M2NmZDIvMDc3NjgxZTktMmNkOS00Y2Q4LWI2YjgtYjA0NjU5OWVkZjllIiwiaWF0IjoxNzA3MTc5NzcyLCJleHAiOjMzMjc3NzM5NzcyfQ.pthFthGUDVsWjEtvNXEO_knsB2uLdKizRUbqm9BRg8o "=1680x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform:Web
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by ValetCEO** [comment]
Please note this issue is happening on every side draw on every page and just started happening - No work was being done on these elements when the issues appeared overnight

**Comment by ValetCEO** [comment]
Upon further investigation it appears that the side draw will not extend further than the standard width for a side draw (the standard preset width that it's given when places on the page)

**Comment by rzambroni** [comment]
Hey @valetCEO, i really apologize for the very late response and that you that troubles contacting support. I was trying to replicate this issue but i couldn't on a blank project. Are you still experiencing this? if so, it is very likely that this is project-specific issue and our support team is our best chance to get it solved. I know it can be frustrating because you already tried but would you mind following up with them?  You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. 

Thanks.
