### ISSUE TITLE
Webview refresh on screen switch

### ISSUE THREAD

**Issue by chaha0s** [FlutterFlow/flutterflow-issues#2214]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Have made the WebView component's URL dynamic - fetched from firebase - associated with a user. 

When I switch screen from the page having webview component, and switch back to it, the component reloads the same page - even when no change is made in the URL. 

This undos all the progress (eg. partially filled a form) user had made on the webpage. 

### Expected Behavior

The webview component should not reload the URL on screen switch.

### Steps to Reproduce

1. Create a WebView component
2. Add a dynamic URL - fetch this from a firebase store (I had shop object (has shop link) and a shop (shop ref) associated with the user. 
3. Add another screen
4. Add navbar
5. Open webivew screen, do some activity on the webpage - fill forms, do internal navigation, etc.
6. Switch screen
7. Switch back to WebView screen - You'll see that you loose the progress made becuase the component reloads the URL

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wifHf0ItIseVc+Kr2dvpahmAWCDt5R4I7kO0bUis8Cb7yB7Icf/fOYkRBYMyoTAhMJU2Jo2oW097ljoXDIe0DGyieftRywZYNcwqVTkmlVIybFJWgXnAlO+JYfR245rS3mhB5LtVtWiFmw0yqJefIHzTbQYT3DlgeD6/LZO4=

### Context

Affects the UX largely - a release blocker

### Visual documentation

<img width="822" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24517604/4cd19ba1-9e27-4db2-bcc8-d88ec2e78021">

### Environment

```markdown
- FlutterFlow version: v4.0 (released Jan 15, 2024)
- Platform: Web
- Browser name and version: Chrome 120.0.6099.216 
- Operating system and version affected: Android and iOS
```

**Comment by chaha0s** [comment]
Just mentioning @hariprasadms and @wenkaifan0720

**Comment by chaha0s** [comment]
@hariprasadms can you please mention the original issue here?

**Comment by hariprasadms** [comment]
This issue is related this bug - #2192

**Comment by chaha0s** [comment]
@hariprasadms this is not the same. In #2192 using input filed in the webivew is causing this problem, here switching screen is.

**Comment by chaha0s** [comment]
@hariprasadms FYI - the component reloads the URL whenever it comes into view - even if we are not changing the screen.
Tried visibility logic (of the element, and of other elements as well) - still refreshes

**Comment by chaha0s** [comment]
Hey @wenkaifan0720, thanks for the reply - I understand that the native webview does not provide this functionality. 
I even tried visibility logic - to show items above the main webview - just to avoid screen changing, still facing the same problem.
Do you have any other recommendations?

**Comment by wenkaifan0720** [comment]
The best way I can think of is to reimplement that form in FF directly.

**Comment by chaha0s** [comment]
Sadly I do not have the APIs required to recreate all those e-commerce functionalites on FF @wenkaifan0720 :(
