### ISSUE TITLE
Stripe integration - failed to catch error when payment failed

### ISSUE THREAD

**Issue by iamhsong** [FlutterFlow/flutterflow-issues#2216]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Stripe payment action works perfectly when its response is success but it doesn't work when payment is refused.

It throws an error and output var doesn't get any response, stripe layer doesn't ever disappear. This layer freezes and nothing happens, no output value, nothing.

[https://community.flutterflow.io/general-wishlist/post/stripe-integration---failed-to-catch-error-when-payment-failed-zfi2X00gRHfDD5V](https://community.flutterflow.io/general-wishlist/post/stripe-integration---failed-to-catch-error-when-payment-failed-zfi2X00gRHfDD5V)

### Expected Behavior

When payment failed and exception is thrown, it should be caught in the code and return error, instead of halted and stop processing.

### Steps to Reproduce

1. Setup Stripe Payment.
2. Make payment using faulty test credit card number such as 4000000000000002.
3. The payment will be rejected and halted and nothing will be returned. Unlike successful payment, it will return a payment ID associate with the payment as indication of success process.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gyfHlvYt1xMtF0JD+Y+9VhicQOV98aJc0sNobbxAjIoDoPJkUacz7XExWXcDiTWxhKEWIuFIy7sLLiuzuGscqIQiVY4haypBIZQLzXny/aoS7O8yCQEElJ/hPf0C93KarhBNQNrRYWGQD312Yet69UizXH5v7Zwh9f6PHaOI=

### Context

When payment failed, the process got halted and couldn't proceed with the rest of the processes such as prompting message to user and db update. Users get confused because nothing is responding on the screen..

### Visual documentation

![Screenshot 2024-01-22 161432](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6f42845f-8a3f-4455-be75-81f8e39045ee/42971dee-1e7a-4a0d-94d9-cc7edba96383?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZjQyODQ1Zi04YTNmLTQ0NTUtYmU3NS04MWY4ZTM5MDQ1ZWUvNDI5NzFkZWUtMWU3YS00YTBkLTk0ZDktY2M3ZWRiYTk2MzgzIiwiaWF0IjoxNzA1OTEzNTUzLCJleHAiOjMzMjc2NDczNTUzfQ.hZLjVDBoWOkmQsCCwFxBqvZGt5_OTBWdK3YOMFJOOmo)

[https://community.flutterflow.io/integrations/post/stripe-payment-doesn-t-catch-errors-OgSItliJABLyrk5?highlight=GHMHD3GnwuaOb1A](https://community.flutterflow.io/integrations/post/stripe-payment-doesn-t-catch-errors-OgSItliJABLyrk5?highlight=GHMHD3GnwuaOb1A)

### Additional Info

![Screenshot 2024-01-22 161432](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/177d74a1-6163-454c-8db6-9c51368b9aba/bc3e7077-797d-4186-80f8-c546c792596b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzdkNzRhMS02MTYzLTQ1NGMtOGRiNi05YzUxMzY4YjlhYmEvYmMzZTcwNzctNzk3ZC00MTg2LTgwZjgtYzU0NmM3OTI1OTZiIiwiaWF0IjoxNzA1OTEzNTUzLCJleHAiOjMzMjc2NDczNTUzfQ.b4rAaKStvWQ6FEr7NhJJC4YZ1I1tJbhveCiWiyfP4mQ)

![Screenshot 2024-01-22 161432](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ff348cc0-5d3a-4a2e-9f6d-814993ed2bed/97cc335f-7ebc-45f0-acda-0497576337dc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZjM0OGNjMC01ZDNhLTRhMmUtOWY2ZC04MTQ5OTNlZDJiZWQvOTdjYzMzNWYtN2ViYy00NWYwLWFjZGEtMDQ5NzU3NjMzN2RjIiwiaWF0IjoxNzA1OTEzNTUzLCJleHAiOjMzMjc2NDczNTUzfQ.qWfY_NklMoopurTXIS7nc9UJo5GicaNAFnN5X2isFAo)

### Environment

```
- FlutterFlow version: v4.0
- Platform: Android
- Browser name and version: Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
- Operating system and version affected: Windows11
```

**Comment by hariprasadms** [comment]
Hi @iamhsong - Thanks for submitting the issue.  The behaviour you are experiencing is as per the current design. I understand the points you are expecting, and this could be considered an enhancement for the current design. Thank you

**Comment by leighajarett** [comment]
Since this is a feature request, I'm going to close this issue. We're discussing this request internally. Thanks so much for the feedback!

**Comment by naesevol** [comment]
Am I reading this right? You're just _not_ going to handle declined cards/payment issues with this stripe "integration"? This is one of the reasons I paid for Flutterflow. Please reconsider, as this is a non-starter. We can't use this to handle real life transactions if we can't even redirect/communicate upon error. Come on!

**Comment by leighajarett** [comment]
Thanks for the feedback, your request is totally reasonable. We're discussing internally and will get back to you!

**Comment by naesevol** [comment]
> Thanks for the feedback, your request is totally reasonable. We're discussing internally and will get back to you!

Thanks! Someone actually found the issue in your community thread for what it is worth, and provided the solve (but it isn’t usable via the flutterflow ui, you have to download the code and modify):

[https://community.flutterflow.io/discussions/post/catch-stripe-error-f1N8wvgWRfR6wgP](https://community.flutterflow.io/discussions/post/catch-stripe-error-f1N8wvgWRfR6wgP)

hopefully it is something the team can take a look at and quickly at least handle the exceptions when they happen.

**Comment by alabamasearchandrescue-us** [comment]
I have the same issue! When will this be fixed! This is bad.

**Comment by alabamasearchandrescue-us** [comment]
> Thanks for the feedback, your request is totally reasonable. We're discussing internally and will get back to you!

This is a major bug and feature breaking

**Comment by alabamasearchandrescue-us** [comment]
> > Thanks for the feedback, your request is totally reasonable. We're discussing internally and will get back to you!
> 
> Thanks! Someone actually found the issue in your community thread for what it is worth, and provided the solve (but it isn’t usable via the flutterflow ui, you have to download the code and modify):
> 
> https://community.flutterflow.io/discussions/post/catch-stripe-error-f1N8wvgWRfR6wgP
> 
> hopefully it is something the team can take a look at and quickly at least handle the exceptions when they happen.

We cant modify code because we use the web version

**Comment by alabamasearchandrescue-us** [comment]
![IMG_9914](https://github.com/FlutterFlow/flutterflow-issues/assets/73841043/d13ff5a4-3ccf-4e99-a7d6-eaeab1e44d58)
