### ISSUE TITLE
Dropdown configuration with "Reference" but in Text type

### ISSUE THREAD

**Issue by jessieplaydatecare** [FlutterFlow/flutterflow-issues#2219]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When select "Reference", dropdown configure the type "Reference" to type "Text"

### Expected Behavior

dropdown should configure the type "Reference"

### Steps to Reproduce

Create a dropdown
Query collection to that dropdown
Configure the dropdown as shown in the screenshot, you see it shows "Type: List<String>", but I selected Reference, it should be type "Type: List<Reference>"

![Screen Shot 2024-01-22 at 5 06 30 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/104877660/43167b37-a99c-4e20-87b7-0cf333997b78)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMn1z8pgod9Y0LrtbfowiikvIjsnap08lut+Z0scGIjyG7YASs77P1VeTbzhTFc3JmKJjjsx+aHLkdzIN/BcGw6CfYRN/8xuWg3wUl6naLaWEZbtYXRCMNpKCFCC0ImskSNdNsl2cXga7Ey6AuuAZDfaGYTwCkgFR8mbIqT7nXPuQ0SLb3kNh1JWeC/v

### Context

I was trying to query the dropdown document reference, and for each selection, update the page and update different fields associated to that document reference selected.

### Visual documentation
![Screen Shot 2024-01-22 at 5 06 30 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/104877660/b3074d3f-0603-484c-9f43-a4d891b90021)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @jessieplaydatecare - I may not fully understand your expectation regarding the issue. Could you please provide more details about what exactly you expect when mapping a document reference to dropdown options?

Dropdown options expect a list of items of type String, making its type List<String>. When mapping a document reference, the available item of string type is the Document ID, which results in its display as such. Could you elaborate on your expectation here? Adding more details will help me better understand your concerns

<img width="298" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/46ac9f09-e60c-4eae-98af-fc757d9bdce8">

**Comment by jessieplaydatecare** [comment]
> understand your expectation regarding the issue. Could you please provide more details about what exactly you expect when mapping a document reference to dropdown options?
> 
> Dropdown options expect a list of items of type String, making its type List. W

hi @hariprasadms , can drop-down expect a list of type Reference? Seems many people needs experience this limitation: https://community.flutterflow.io/actions-logic/post/save-a-reference-to-a-doc-after-selection-in-dropdown-or-choicechips-how-KeVFPL0yBmoLKEe
