### ISSUE TITLE
Black Screen In Run Mode

### ISSUE THREAD

**Issue by eljotape** [FlutterFlow/flutterflow-issues#2220]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am working on a project that has been a really nice experience so far to work with (I am new to Flutter).
Out of the blue, it didn't show me anything but a black screen when I tried to run in test mode (after a very long period of seeing the progress bar moving).

### Expected Behavior

I just expect that I can see everything properly displayed as before when running in test mode.

### Steps to Reproduce

1. Open an existing project or even create a new one
2. Create or update any UI 
3. Try running in test mode
4. The screen will be just blank, and/or you will see an infinite animated progress bar 
5. If you check the console in the browser, you will find several errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9Vhj4XC0d+R700sNobbxAjIoDoPJkUacmlRE5tQsvgYAlHKEWGuEQG0anRjs79CfACBzOqboBazrh+Sw/NTTi/aoSUBaWKZGttJ9lgCEC80MHUuRUmKtFadUIX62aYP+qtVj3bJpv7Zwh9f6PHaOI=

### Context

Originally, I experienced this issue working with Brave browser, so I tried with Chrome, but I got exactly the same issue.
I thought it was something related to my project so I created a new project from scratch, and I experienced the same issue.

I searched the docs, and found this:
https://intercom.help/flutterflow/en/articles/6143053-black-screen-in-run-mode

...I followed all the steps there, and the only thing that worked for me was to right-click and reload the frame.

I continued working on my original project on FlutterFlow, and when I tried to run it again, I got the same issue: black screen.

I found this post on flutterflow community, but I found no solution there:
https://community.flutterflow.io/troubleshooting/post/widgets-not-being-displayed-vqN0Imk2tFPKHhO

While I was writing this issue, I found this breaking issue:
https://community.flutterflow.io/c/bugs/post/outage-in-test-mode-runs-2M5mPVp1B18FWlF

That seemed to be the reason. 
Some minutes later, the team reported that this issue was fixed.
Tried again and voila! Everything was working as expected, but, a few minutes later, SAME ISSUE!

I am just trying to continue working with the normal workflow (working in the visual editor, then running in test mode to see everything working while I interact with the UI I built). 

Sadly, this is really blocking me.

### Visual documentation

<img width="958" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2105415/0adb4365-fa32-416c-afd3-b46a707c6832">

### Additional Info

Here´s what I see after the breaking issue was resolved and the issue returned:
<img width="955" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2105415/2777b271-9c13-44cc-a549-8fced76f4392">

### Environment

```markdown
- FlutterFlow 4.0
- Platform: web
- Browser name and version: Chrome 120.0.6099.225 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language 22H2
```

**Comment by farhannkaskar** [comment]
The FF team seems to be looking into this https://community.flutterflow.io/c/bugs/post/outage-in-test-mode-runs-2M5mPVp1B18FWlF

but why is this outage like these not surfaced on https://status.flutterflow.io/

This is the second outage and the status page was always in ALL GREEN state
<img width="1183" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5175527/0267aca2-4104-4473-b0d6-2e74dd52494f">

**Comment by hariprasadms** [comment]
Hi @eljotape -Thank you for bringing this to our attention. We are aware about the issue. Our team is actively addressing the issue, and we will inform users once it has been resolved. Please stay tuned for updates in the community portal - https://community.flutterflow.io/

**Comment by hariprasadms** [comment]
Hi @eljotape - This issue is resolved now. Hence closing the issue. Thanks
