### ISSUE TITLE
Chart label spacing bug

### ISSUE THREAD

**Issue by captainjdi** [FlutterFlow/flutterflow-issues#2222]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Y-axis labels on the chart widget do not have enough room to show properly. I've used the compact number format, but there still isn't enough space to show the numbers without wrapping. When wrapping, they overlap and look terrible. I was asked to create a test project that shows the issue, which is what I've done. Note that I tried making the font smaller and that did not solve the problem. See attached.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/55acef27-efe2-4ed9-810a-2e1d9efd11b7/14f65ca0-f409-46c0-a6f1-7affd5eb8db5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NWFjZWYyNy1lZmUyLTRlZDktODEwYS0yZTFkOWVmZDExYjcvMTRmNjVjYTAtZjQwOS00NmMwLWE2ZjEtN2FmZmQ1ZWI4ZGI1IiwiaWF0IjoxNzA3MTU2MzkzLCJleHAiOjMzMjc3NzE2MzkzfQ.UQ-zgZxsrTUSJyuf7m2HvW84QBPMpTWD5FfEUHv1iLQ "=351x")

### Expected Behavior

I would expect to be able to adjust the amount of space to show the amounts without wrapping. I would hope to have the ability to control that spacing and/or to just make sure there is enough space so that it doesn't wrap.

### Steps to Reproduce

1. Create new project
2. Add chart widget
3. Create a dataset for x-axis and y-axis values
4. Make sure the y-axis values are in the hundreds of thousands and millions at a minimum
5. Set the number format to compact
6. Preview the chart in test mode

[https://app.flutterflow.io/project/chart-spacing-example-z1j3zm?tab=widgetTree&page=HomePage](https://app.flutterflow.io/project/chart-spacing-example-z1j3zm?tab=widgetTree&page=HomePage)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elcr1z4ZItbxK17r+c8JV+T45Jlx7UIJMle1udAwcJZzvE+02e+jxM2ZtTcOrSn03M1qj8Ds10+/GkfbIN8cBExWabNVDwZBMTT3zeFKiaaqJCbiwXUR6BtpKCFCjy5+NoB1NLbF2Ll4922WMONyUSXXDJKbQIVcFJP6KLtvVjXfuQ0SLb3kNh1JWeC/v

### Context

I'm trying to show people the value of their investments over time. It is critical to have a y-axis amount that shows and is easily readable for the end user.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7fc04faf-bfd4-4487-b3e2-c8e85fb9544f/6d8dba12-e1e5-40f1-8e1f-7cf95b0a932a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZmMwNGZhZi1iZmQ0LTQ0ODctYjNlMi1jOGU4NWZiOTU0NGYvNmQ4ZGJhMTItZTFlNS00MGYxLThlMWYtN2NmOTViMGE5MzJhIiwiaWF0IjoxNzA3MTU2MzkzLCJleHAiOjMzMjc3NzE2MzkzfQ.alnJVhePfrKZmns_idkRuc0TtJXRCHkknOS14MNQEzY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/08b5affc-dfc1-485f-8d76-1069ebcf38c5/437a16d4-bfca-46bc-b78a-d39c33b0dd24?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wOGI1YWZmYy1kZmMxLTQ4NWYtOGQ3Ni0xMDY5ZWJjZjM4YzUvNDM3YTE2ZDQtYmZjYS00NmJjLWI3OGEtZDM5YzMzYjBkZDI0IiwiaWF0IjoxNzA3MTU2MzkzLCJleHAiOjMzMjc3NzE2MzkzfQ.Zn3CdQwDK3owRJntNHShegVrKq0oLhm0KwapHr-umV4 "=351x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment]
Hi @captainjdi - Thank you for submitting the issue. I can reproduced the issue using the same dataset you have used in the project. Interestingly, it appears to be related to the data interval, particularly when dealing with large values. 

Developer's Note:

While investigating, I observed a gray section appearing during the label interval adjustment, especially noticeable when changing values from 0 to 100 and similar increments. Additionally, when using the same dataset used in the user's project, I observed that the application freezes, rendering the build area unresponsive in test run mode.

**Comment by Franco98404** [comment]
I have the same error too

**Comment by Krystian95** [comment]
Hi, me too

**Comment by captainjdi** [comment]
@hariprasadms Any update on this? It's been almost 2 months

**Comment by rzambroni** [comment]
Hey everyone! sorry about the late response, we are trying to get up to speed with everything. I sent this ticket to the team so they can implement a fix. We will update the status once it is fixed.<br>Thanks for your patience and the report.

**Comment by Franco98404** [comment]
Hi @rzambroni, I have the same problem but with the legend

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/55e58757-bd71-47f3-81b6-d29b4d7e011a)

**Comment by RomanStirskyi** [comment]
Hi, me too
