### ISSUE TITLE
Can't import '/flutter_flow/flutter_flow_icon_button.dart' in custom code widget

### ISSUE THREAD

**Issue by dawgster** [FlutterFlow/flutterflow-issues#2223]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to import '/flutter_flow/flutter_flow_icon_button.dart';  in my custom code widget it gives me the following error:

`Target of URI doesn't exist: '/flutter_flow/flutter_flow_icon_button.dart'. Try creating the file referenced by the URI, or try using a URI for a file that does exist.`

### Expected Behavior

I expected o be able to start making a custom code widget by taking the code of a widget I made in the GUI and extending it. However the imports that work for normal GUI widgets do not seem to work the same way for custom code widgets. I would expect to be able to simply extend the code of a GUI-made widget.

### Steps to Reproduce

Try to compile the following minimal code:

// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import '/flutter_flow/flutter_flow_icon_button.dart'; // BUG: This import can no be found

class TestWidget extends StatefulWidget {
  const TestWidget({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);

  final double? width;
  final double? height;

  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gofkC+of+bcZQhR4mJkQ5a7lElMB+QkojfYDyO7YpWs7ebRdeT+mReG1IJlGiiXEC+PT0ueLuUvc7FAyHbtg6zbVuEjngfF66MqayPM+WQnJPMJhhfkeO0MCRnQpQPshtW11pig/GSw==

### Context

I can not make a custom code widget with the same icons as in the GUI

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Brave
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @dawgster - The default imports in the custom widget template are predefined, and any additional imports beyond those won't work. This adheres to the current design.

**Comment by dawgster** [comment]
So its not possible at all to use flutterflow primitives in custom widgets? Seems a little counter-intuitive to me.

**Comment by hariprasadms** [comment]
Can you please add a bit more details whey it is counter-intuitive. 

As I confirmed that above, it is not possible. However, you can still compile the code by selecting excluding it from compilation. Did you try this ?

**Comment by takashiff** [comment]
Hi @dawgster, unfortunately this is a limitation of FlutterFlow. With our current flow, we intend for additional functionalities to existing widgets to be done through custom functions and custom actions. Thanks
