### ISSUE TITLE
API Bad Request Error 400 when new line (n/) formatting used in text field input

### ISSUE THREAD

**Issue by ChasingTechGPT** [FlutterFlow/flutterflow-issues#2224]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Submitting this as bug as requested by FlutterFlow support

There seems to be an issue with API request (at least to BuildShip) when the input when it has return values. I am able to get a successful API request when testing in FlutterFlow API manager and Postman.

When in test mode, the Google console debug shows that the payload seems to be structured properly, but perhaps there is an "invisible" character that the input field is passing that causes an issue with the request?

### Expected Behavior

User should be able to copy & paste text with /n new line formatting into the text field input and pass that text as a variable to the API call without getting a bad request 400 error

### Steps to Reproduce

1. Create a page as shown with inputs "title" and "ingredientsInstructions":
<img width="453" alt="Screenshot 2024-01-22 at 7 21 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/133de453-74fe-4df5-a44b-eac379af179f">

2. Create an API POST request such as this one:
[buildship-tyc228-spec.json](https://github.com/FlutterFlow/flutterflow-issues/files/14017143/buildship-tyc228-spec.json)

JSON Body Format for API settings (variables "title" as string and "ingredientsInstructions" as string): 
{
  "title": "<title>",
  "ingredientsInstructions": "<ingredientsInstructions>"
}

3. Create action flow on the page to do an API call to the newly added API POST such as shown here:
<img width="1122" alt="Screenshot 2024-01-22 at 7 24 24 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/aa267b8d-0e8c-4f04-86ce-6233d74d6aaf">

4. Create page state variable that shows the API status:
<img width="1135" alt="Screenshot 2024-01-22 at 7 24 45 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/6b156a32-e060-4d3f-8736-85a4373a44b0">

5. Run Project in Test Mode

6. Enter the ingredients/instructions & title (title = "kino pancakes", ingredients/instructions = "INGREDIENTS:

-  80g of oats
- 1 scoop KINO COLLAGEN 
- 200g liquid egg whites
- 1 tsp baking powder
- 50g blueberries
- 100g raspberries

DIRECTIONS:

1 - Add all ingredients accept the berries in to a blender and blend well.
2 - Poor 2 medium size cakes onto a nonstick pan and flip once the bottom is well cooked and then serve with berries, KINO FROSTING (175g 2% greek yogurt, 20g vanilla jello pudding powder), and 0 calorie maple syrup. "

7. Press button to run API call which should return nutrition information in this case

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjMrl05Ngrs9J1aqNKe9avCk4C1AlaIc0st5Hd0gdCOPrBqQXd8nRclZBcMegaVNcGlmkhkQB+dbqiYXqVvVdYBWCQN1Cyap+exXOe2iQM7a4Ebu0Z3QkJ5hmIEy73J6zoRN7HOloWmw93WeyA++tHxbDFOu/Zwh9f6PHaOI=

### Context

User should be able to copy & paste text with /n new line formatting into the text field input and pass that text as a variable to the API call without getting a bad request 400 error
<img width="1440" alt="Screenshot 2024-01-22 at 7 19 26 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/0c87f844-4bfb-433b-96cd-6478bd6d8c09">

User would have to remove all /n new line formatting to get a successful call:
<img width="453" alt="Screenshot 2024-01-22 at 7 21 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/1b26f43d-b476-4105-84b6-18a8ed0d54c9">

### Visual documentation

Example of how I suspect FlutterFlow is passing the variable (shown in Postman):
<img width="1026" alt="Screenshot 2024-01-14 at 1 17 34 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/2627fa8a-2bee-41c9-88e8-d51bf6721c8f">

Successful API call in Postman using same user inputs (passed via variables)
<img width="1363" alt="Screenshot 2024-01-14 at 1 07 16 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/0a54b1d6-619b-4f38-b01e-59c2c167208e">

Successful API test in FlutterFlow API manager:
<img width="1417" alt="Screenshot 2023-12-14 at 8 59 39 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/93435b6a-7686-4854-b682-9638bec1f40b">

Demonstrating bad request 400 error in FlutterFlow test mode alongside the Google debug console (request payload shown):
<img width="1440" alt="Screenshot 2024-01-12 at 10 13 23 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/0fbc8f0c-a9bc-4a30-97e0-3386a1276c8d">

Request payload passed by FlutterFlow shown in detail (shown in Google debug console):
<img width="988" alt="Screenshot 2024-01-12 at 10 12 30 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140826567/d8d6a8c3-82ef-4ef5-96eb-b1e04cfe76a8">

### Additional Info

Title:

JSON Body Format for API settings: 
{
  "title": "<title>",
  "ingredientsInstructions": "<ingredientsInstructions>"
}

title input variable: "kino pancakes"

ingredientsInstructions input variable example with /n new line format:

"INGREDIENTS:

-  80g of oats
- 1 scoop KINO COLLAGEN 
- 200g liquid egg whites
- 1 tsp baking powder
- 50g blueberries
- 100g raspberries

DIRECTIONS:

1 - Add all ingredients accept the berries in to a blender and blend well.
2 - Poor 2 medium size cakes onto a nonstick pan and flip once the bottom is well cooked and then serve with berries, KINO FROSTING (175g 2% greek yogurt, 20g vanilla jello pudding powder), and 0 calorie maple syrup." 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.20 Flutter 3.13.7
- Platform: Web and MacOS Desktop
- Browser name and version: Chrome 120.0.6099.109 (Official Build) (x86_64)
- Operating system and version affected: Mac Ventura 13.2.1 (22D68)
```

**Comment by takashiff** [comment]
Hi @ChasingTechGPT, thank you for the bug report. Could you share the project/bug report code for the blank project you've created above? This should help speed up the debugging process. Thanks

**Comment by ChasingTechGPT** [comment]
Hello,Here is the bug code from the blank project:ITEelsn1z4pNj7xd16n2b8JFvwMwJ0QlUIInj+0bWRMhfLLoO4YiO/TCQ1VLYtSleAlEOWCJrGExw62NjuPfLfArFziAfJhEya5XQTyWXlG6RJCJDs6KP0F6HeZbIHa+0Z2RghRQFOtoc2QY3Fz7HvCdG3qCf9qOYwx5e6fDbOY=Project link:FlutterFlowapp.flutterflow.ioSent from my iPadOn Jan 30, 2024, at 5:01 PM, takashiff ***@***.***> wrote:﻿
Hi @ChasingTechGPT, thank you for the bug report. Could you share the project/bug report code for the blank project you've created above? This should help speed up the debugging process. Thanks

**Comment by takashiff** [comment]
@ChasingTechGPT Great, thanks so much!

**Comment by takashiff** [comment]
Hi @ChasingTechGPT, I've reviewed the project you've provided and did some testing. It looks like the newline issue is specific to the API you are using, as using `https://postman-echo.com/post` as the endpoint with the text you have provided works without issue. The reason it works within the FlutterFlow API Manager is because the input text field is limited to one line, whereas the TextField in the blank project you have provided has a max limit of 10 lines.

**Comment by ChasingTechGPT** [comment]
Thank you for reviewing further takashiff. I will review and discuss further with BuildShip (API platform) where I created the API.

**Comment by solkennedy** [comment]
This is still an issue - FlutterFlow does not send properly formatted JSON. Unless I actively escape using a custom function, Flutterflow happily sends invalid JSON containing unescaped newlines:

SyntaxError: Bad control character in string literal in JSON at position 26
    at JSON.parse (<anonymous>)
    at parse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/body-parser/lib/types/json.js:92:19)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/body-parser/lib/read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at invokeCallback (/layers/google.nodejs.functions-framework/functions-framework/node_modules/raw-body/index.js:238:16)
    at done (/layers/google.nodejs.functions-framework/functions-framework/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/layers/google.nodejs.functions-framework/functions-framework/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:524:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1698:12)

Is this a bug? YES!

The JSON specification (RFC 8259) classifies newlines and carriage returns as "control characters" (U+0000 through U+001F). These characters must be escaped when they appear inside a JSON string to ensure data portability and consistent parsing across different systems and programming languages
