### ISSUE TITLE
Sorting a dynamically generated list based on a custom function has a forced formatting despite the having the correct settings in the UI. 

### ISSUE THREAD

**Issue by michielpr** [FlutterFlow/flutterflow-issues#2226]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi there FF team, 

Here's a weird behavior that I have discovered (and something that I have been working on with Serge Middendorf). You can find our thread here: https://community.flutterflow.io/ask-the-community/post/odd-interesting-find-sorting-a-list-of-children-based-on-a-custom-bFM8XtDI17J6Vky

**My goal**: 
I am trying to get a list of locations sorted based on the physical distance away from our our user.

How I have set things up: 
Setup: 

- In my project, I have a collection called `/POI` which will contain hundreds of locations. Each POI has a set of attributes, one of which a `LatLng`.
- I wrote and validated a custom function which calculates the distance between the POI LatLng and the Device GPS coords. 

**Execution** (and the area where I think the bug is): 

1. I created a `generated list` based on a queried collection of documents (all POIs) 
2. I applied the my `custom function` to calculate distances as the `sorting key` -- this works.. _until the bug arises._  
3. When the list gets generated, I can see that there is 'some' sorting happening. However, I think it's because the of _some_ number formatting issues. In the various screenshots, you can see that the sort is indeed sorting, however it's mixing units. It goes from 1, 2, 3, etc.. but then also: 55, **5.2k**, 56, 70, **9k**, 96,  etc etc.  

Screenshots of the behavior and setup are attached. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47259560/26f2b18b-e23a-4acb-b7f7-d23e5a7a4482)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/47259560/2e714e9e-b11d-4468-aab2-099f953d1fa7)

### Expected Behavior

I am expecting the list to sort based on the calculated key (therefore not intermixing units) 

Ideally, the sorted list should behave like any sorted, ascending list.  

### Steps to Reproduce

1. Create new page and apply query to POI collection 
2. Create a listview 
3. Create a generated children list 
4. Set the sorting key to the custom function to calculate the distance between the user and the POI (define the POI LatLng and the Global Properties GPS location   

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8r13It1xOVY18/tbcBVniQvJkAhTLJEpu0bWUkbGO/4BLAAPffsTBBBTsizaH5De060nk8EwPTxv9juUfACCzSqfL5lz6liZhPPbH6gRZCpDbqOSnYlM+FYfnbG5omnpQkkOvt1R04E2E6MGuitFj6Cf9qOYwx5e6fDbOY=

### Context

I can't seem to get this to work regardless of the settings and number formatting options. 

### Visual documentation

I have created a recording in Descript. Here's the video/narration: https://share.descript.com/view/V0sQ4tYBN4x

Happy to reupload/send directly if that works for you. 

### Environment

```markdown
- FlutterFlow version: v4.0; Flutter: 3.13.7
- Platform: Web
- Browser name and version: Chrome 120.0.6099.234 (Official Build) (arm64)
- Operating system and version affected: Mac OS Ventura 13.6.3 (22G436)
```

**Comment by hariprasadms** [comment]
Hi @michielpr - Thank you for raising the issue. I've looked at the community post and observed that discussions are ongoing. I hope you've found a solution for the problem. Could you update me on the current status?

Regarding the triaging of this issue, given its nature and the above described setup, I recommend reaching out to the FlutterFlow support team initially to seek help with the custom function and verify its correctness. If they confirm it to be a bug in the feature, you can then bring it here for confirmation. Considering the potential delay in response time for triaging, this approach ensures a quicker resolution to the issue. I hope this can help. Thanks
