### ISSUE TITLE
Custom function fails to test : Firebase Error message after clicking run button

### ISSUE THREAD

**Issue by elysificated** [FlutterFlow/flutterflow-issues#2227]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to use the Test Function feature for my custom code, I receive the error:
![Screenshot 2024-01-23 5 09 42 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/157417179/e488b436-d38d-46f0-81b5-a8a760f7b609)
My code is: 
```
dynamic createHistory(DocumentReference userID) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return FirebaseFirestore.instance
      .collection('chat_messages')
      .where('user', isEqualTo: userID)
      .orderBy('timestamp')
      .snapshots()
      .map((snapshot) => snapshot.docs
          .map((doc) => {'role': doc['role'], 'content': doc['text']})
          .toList());

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

### Expected Behavior

I should have the result of my test.

### Steps to Reproduce

1. Create the custom function, e.g.
```
dynamic createHistory(DocumentReference userID) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return FirebaseFirestore.instance
      .collection('chat_messages')
      .where('user', isEqualTo: userID)
      .orderBy('timestamp')
      .snapshots()
      .map((snapshot) => snapshot.docs
          .map((doc) => {'role': doc['role'], 'content': doc['text']})
          .toList());

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```
1. Test it in the "Test Function" tab

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcr1z89IsdtK0L6IKMBV/TgWHGkcTOURiO0bFDsdF4iuPOxzaeLBMlhWONPhd2w2KEWKhkEHwNLJhuHfEsACaAiabrZbzLVXFjzwcE6/aoSmBpCCfGsnM91VJ2qx3MOG3AlSBNRuZU0t12GAJd+XbC3dQL37Zwh9f6PHaOI=

### Context

Without the implementation of this code, I cannot implement the most critical function of my app. I need to create a mapped list for my API call.

### Visual documentation

Create custom function:
```
dynamic createHistory(DocumentReference userID) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return FirebaseFirestore.instance
      .collection('chat_messages')
      .where('user', isEqualTo: userID)
      .orderBy('timestamp')
      .snapshots()
      .map((snapshot) => snapshot.docs
          .map((doc) => {'role': doc['role'], 'content': doc['text']})
          .toList());

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```
Go to Test Function, run test and receive error:
![Screenshot 2024-01-23 5 09 42 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/157417179/ce71b5b9-d495-4c38-961f-e338dbdbc2ff)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: chromebook
- Browser name and version: chrome 120.0.6099.203
- Operating system and version affected: chromeOS 120.0.6099.203
```

**Comment by hariprasadms** [comment]
Hi @elysificated - You cannot access the FirebaseFirestore instance in custom functions because functions are not of async type. Instead, try using it in custom actions. I hope this approach can be helpful. Thanks
