### ISSUE TITLE
App email login throwing error with no snackbar

### ISSUE THREAD

**Issue by stevey6404** [FlutterFlow/flutterflow-issues#2228]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Launched an app on TestFlight, when entering a random email + PW, a huge error is being thrown instead of the usual snackbar. 
**Problem video** 
https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/a7487a1a-fea4-408a-8e3b-b5474b0ee8a6

**The usual snackbar should be like the below:**
https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/72c4f7f9-8c8f-4d1c-8bef-8605841cb2c0

I also checked did the web version and it throws a different snackbar error. Although the web version shows a snackbar, on mobile it is rendered differently. 

<img width="1085" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/2aaff5d3-c0c2-4f67-8457-fa58603631f5">
<img width="1082" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/9730fd77-1919-42a8-980b-29aeca55292f">

### Expected Behavior

Native app should be showing the correct snackbar error. 

### Steps to Reproduce

1. Have email login AND Google login enabled 
2. Deploy app as a native app on iOS
3. Enter random email and PW

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grs9d0bqNdO1AhQAkH1x/bZJEl9cbd040IrL2O7MMOur+VE9oTuG5SldqPmCl+WM0psLeidn9IMY4Pk+CeINo1LgNEg7dcziXaL6TO7jpdkZTGZ9TfVSA36e3uwknCMVaWCRhw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Bad UX and error was not considered

### Visual documentation

**NOT Expected**
https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/d98c0c53-781f-4ad6-8a69-3f7679c215ef

**Expected:**

https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/d1efcbb8-79b2-42bc-bd4f-eda9abe22b88

### Environment

```markdown
- FlutterFlow version: v4.0 3.13.7
- Platform: iOS 
- Browser name and version: Chrome Version 120.0.6099.216
- Operating system and version affected: iOS
```

**Comment by wenkaifan0720** [comment]
Hi @stevey6404. This should be fixed in our next update. Thanks!
