### ISSUE TITLE
Timer doesn't accept changes to duration 

### ISSUE THREAD

**Issue by bertke** [FlutterFlow/flutterflow-issues#223]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
The timer widget has an option to set the duration by variable.  I would expect this to be dynamic based on whatever the timer is bound to, but this value never changes based on that 'variable', rather it only implements the first value retrieved.

## Current behavior (required)
There are a few ways to test this but one is to set the duration equal to a local variable and then change that variable.  The change in local variable will never be received by the timer widget.  This can also be done using a custom function that returns different values (based on input or time of day as an example) and the widget will never recognize a value other than the first one retrieved.

## To Reproduce (required)
1.  Create a local variable (integer) with a default value (e.g. 10000)
2. Create a timer and bind duration to the local variable
3. Create a button that changes the value of the local variable to something other than the default
4. No action exposed by the timer will cause the timer to pick up any new value (stop/start/reset)

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1.
5.
6.
7.

## Context (required)

This issue has held me up for about a week as I explored any means of creating a timer where the user could affect the countdown.  I will be entering another bug as this is also not doable with the periodic timer feature recently implemented (due to errors when navigating to another page via the navbar).

The net affect of both issues is that any app that requires a custom countdown timer cannot be built in FF unless a custom developed navbar is used.  A custom navbar should allow for this functionality as it would allow an event (when changing pages) to turn the periodic timer off until the user navigates back.  

## Your environment

* Current version of FF (3.3.4) 
* Platform: Web 
* Browser name and version: Chrome 
* Operating system and version Mac (current OS)

**Comment by bertke** [comment]
This does change the values of the timer but forces a full page reload.  On a mobile device the screen appears to flicker and it's much more pronounced on a web implementation.  Technically this is a workaround but I'd have to question whether I'd want to ship a product with that user experience.

**Comment by bulgariamitko** [comment]
Ok can you try one more thing please. Instead of updating the value from local host can you update the value from FB and see if that will work without navigating to the same page?

**Comment by bertke** [comment]
A few different things to respond on this.  First I'm assuming FB = Firebase.  If so, I would say that doesn't really fit my need but I have tried this in an effort to get anything to work.

There are a couple of ways to attempt to connect the timer to Firebase.  One is to have a number field in the database that represents a milliseconds duration and bind the timer to that.  The second way is to have a future date/time in the database and use a local function to convert that to a milliseconds from now.

Attempting the first way, this causes an error when compiled locally.  Meaning that there are no errors in FF, but once brought local it raises an error.  This error is hard to troubleshoot (for me) but refers to a concern that an int? cannot be assigned to int but the line referenced doesn't have an 'int' but uses a 'currentUserDocument' class which I am betting is a FF object.  I've tried this a few times and it can't be made to work.  I wonder if this worked before the null safety changes but I'm very new to FF.

The second option uses a date in the database and a custom function.  The custom function just takes a parameter (a future date - which will come from Firebsase) and returns the milliseconds from now.  I then bound the timer to that function with the above referenced connection to firebase.  This attempt follows the previous pattern in that the timer retrieves an initial state but no changes to the data in Firebase will cause this to update. Again a page reload will force it to retrieve/recalculate.

Let me know if this helps or you want me to try something else.  Thanks!

**Comment by agreaves** [comment]
Hi @bertke, thank you for the bug report! As you mentioned, the Timer value that can be set from a variable is effectively an "Initial Timer Value" in that it can only be set once. The reason it is not dynamic is because if the timer value were to change while still running, this would have the unexpected effect of resetting the timer time.

As a solution, we have added a way to reset the timer to an arbitrary time via the Reset Timer action. You can use this action to update the timers value. Hope this helps!

**Comment by bertke** [comment]
This is huge and solves my issue.  Thank you!!!
