### ISSUE TITLE
Grey screen on empty action within a custom action in an action block

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#2230]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to add action to a custom action, if that is within an action block.
If I copy+paste an action to it from somewhere I am getting errors during deployment too.
![CleanShot 2024-01-24 at 10 31 03](https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/6b42e1c7-6c10-4710-9f85-8587e4cde886)

### Expected Behavior

ability to add action

### Steps to Reproduce

1. create a custom action and add an action parameter to it
2. go to he action block panel, create a new action block
3. add the custom action to the action block
4. go to the action parameter that was given to the custom action in the first step
5. add an action
6. observe the grey screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otIsdtK0LruYO9anmM6OUA3a600st5Hd0gdCOPrBu0EPsz4aRJDQsOraVNcGlH9inEF+v/Iiuz1GPUCIk2ZY5x4+M1ISjn0e2iiRYSVDYe8eXMlEeRYfH6C0aSRsBFdIvdfcU1kwDqQe/PIE3fDIuu/Zwh9f6PHaOI=

### Context

I want to add custom action to an action block

### Visual documentation

https://share.cleanshot.com/Nd32GvDh

### Environment

```markdown
- FlutterFlow version: v 4.0 - Flutter 3.13.7
- Platform: macOS & web
- Browser name and version: Chrome Version 120.0.6099.234 (Official Build) (x86_64)
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by victoriahuang1** [comment]
Hi @kicsijohn , thanks for the report. This should be resolved upon the next deploy
