### ISSUE TITLE
Change Persistent appState

### ISSUE THREAD

**Issue by ckarmy** [FlutterFlow/flutterflow-issues#2231]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a Bool type app state is changed to 'persistent', the variable gets duplicated, resulting in one persistent and one non-persistent variable.

### Expected Behavior

Change persistent app state. Not duplicate

### Steps to Reproduce

1. Create a bool app state (persistent = false)
2. Edit app state and change persistent = true

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

selecting any widget

### Context

App state

### Visual documentation

![Captura de pantalla 2024-01-24 a la(s) 10 19 32](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/645e9dc4-a61f-4532-879f-24e0ac4b8ea0/100666a9-41ad-4b91-8c07-31be6e8aded0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NDVlOWRjNC1hNjFmLTQ1MzItODc5Zi0yNGUwYWM0YjhlYTAvMTAwNjY2YTktNDFhZC00YjkxLThjMDctMzFiZTZlOGFkZWQwIiwiaWF0IjoxNzA3MTU2MzkxLCJleHAiOjMzMjc3NzE2MzkxfQ.E74RVdGZp4eY7eX6dVA0DqB8e5u88k84JLFbwRWuJvU "=517x")

![Captura de pantalla 2024-01-24 a la(s) 10 19 37](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8021603b-3297-4d9f-aca8-d340ce740229/dec266fb-745c-448e-931a-09656782980f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MDIxNjAzYi0zMjk3LTRkOWYtYWNhOC1kMzQwY2U3NDAyMjkvZGVjMjY2ZmItNzQ1Yy00NDhlLTkzMWEtMDk2NTY3ODI5ODBmIiwiaWF0IjoxNzA3MTU2MzkxLCJleHAiOjMzMjc3NzE2MzkxfQ.oWlm1Ugwtl6MdRwrdJ_yTMuhALoQ0fKhMTl52j9A9UU "=1062x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: web, mac
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hi @ckarmy - Unable to reproduce the issue. If the problem persists, create a blank project with the issue steps reproduced in it and share the details. No project bug report details were provided in the issues. Issues with insufficient details will not be considered for investigation. Thanks.
