### ISSUE TITLE
Unknown error compiling custom code.

### ISSUE THREAD

**Issue by Bimsara132** [FlutterFlow/flutterflow-issues#2232]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am not able to add custom widgets and actions to the flutter-flow app. it says that 
"Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor"

tried downloading the project, it's working while running in local. but the custom codes and widgets are not compiling in the flutter flow editor 

### Expected Behavior

so when added new custom widgets or actions it should compile.

### Steps to Reproduce

Not able to compile the custom codes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

FLUTTERFLOWUNKNOWNERROR

### Context

When adding new custom widgets and custom actions
![Screenshot 2024-01-24 at 19 13 51](https://github.com/FlutterFlow/flutterflow-issues/assets/150698023/fe3d0d6a-9dec-4b4b-b0ca-25f46292878b)

### Visual documentation

![Screenshot 2024-01-24 at 19 14 39](https://github.com/FlutterFlow/flutterflow-issues/assets/150698023/a9f47365-3b37-4009-a4a7-28b42d2bcc97)
![Screenshot 2024-01-24 at 19 14 56](https://github.com/FlutterFlow/flutterflow-issues/assets/150698023/091971c1-42c1-462e-845e-e3ba0157764e)
![Screenshot 2024-01-24 at 19 15 12](https://github.com/FlutterFlow/flutterflow-issues/assets/150698023/7da01c75-cb07-4c58-b290-f0c50b84e02f)

### Environment

```markdown
- FlutterFlow version: V4.0
- Platform: web, MacOS
- Browser name and version: Chrome Version 120.0.6099.234 (Official Build) (x86_64)
- Operating system and version affected: MacOS Sonoma 14.2.1 (23C71)
```

**Comment by hariprasadms** [comment]
@Bimsara132 - Thanks for reporting the issue. I have seen this error sometime but inconsistent.

**Comment by SpeedotrackGPS** [comment]
Hello, I am also getting the same issue while compiling the custom code but the same custom widget is getting compiled on a fresh project but cannot add to the existing project. Please let me know how to solve that

**Comment by activeSergio** [comment]
I have this error and my code does not contain errors, and i need to create urgently a component 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/157737355/e0f516fb-7969-466d-bfd2-e75546a080bc)

**Comment by paulVu** [comment]
<img width="1125" alt="Screenshot 2024-01-26 at 9 50 46 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/89efdfd3-439f-40c8-bfd1-b28ec0da3846">
I have the same problem.

**Comment by paulVu** [comment]
OMG, I'm deleted the custom widget but it's still in this issue. 
<img width="278" alt="Screenshot 2024-01-26 at 10 17 50 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/b68ec274-e12e-4621-9bda-1216623f9edd">

**Comment by paulVu** [comment]
Also the app now can't deploy
`Codemagic Deploy Output
Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Resolving dependencies...
+ _fe_analyzer_shared 61.0.0 (66.0.0 available)
+ _flutterfire_internals 1.3.16
+ analyzer 5.13.0 (6.4.0 available)
+ animated_text_kit 4.2.2
+ archive 3.4.10
+ args 2.4.2
+ assets_audio_player 3.0.6 (3.1.1 available)
+ assets_audio_player_web 3.0.6 (3.1.1 available)
+ async 2.11.0
+ audio_session 0.1.18
+ auto_size_text 3.0.0
+ boolean_selector 2.1.1
+ cached_network_image 3.2.1 (3.3.1 available)
+ cached_network_image_platform_interface 1.0.0 (4.0.0 available)
+ cached_network_image_web 1.0.1 (1.1.1 available)
+ carousel_slider 4.2.1
+ characters 1.3.0
+ checked_yaml 2.0.3
+ chewie 1.7.1 (1.7.4 available)
+ cli_util 0.4.1
+ clock 1.1.1
+ cloud_firestore 4.13.1 (4.14.0 available)
+ cloud_firestore_platform_interface 6.0.5 (6.1.0 available)
+ cloud_firestore_web 3.8.5 (3.9.0 available)
+ cloud_functions 4.5.8 (4.6.0 available)
+ cloud_functions_platform_interface 5.5.11
+ cloud_functions_web 4.6.11
+ collection 1.17.2 (1.18.0 available)
+ convert 3.1.1
+ cross_file 0.3.3+7 (0.3.3+8 available)
+ crypto 3.0.3
+ csslib 1.0.0
+ csv 5.0.1 (5.1.1 available)
+ cupertino_icons 1.0.6
+ dbus 0.7.10
+ easy_debounce 2.0.1 (2.0.3 available)
+ emoji_flag_converter 1.1.0
+ equatable 2.0.5
+ fake_async 1.3.1
+ ffi 2.1.0 (2.1.2 available)
+ file 7.0.0
+ file_picker 6.1.1
+ file_selector_linux 0.9.2+1
+ file_selector_macos 0.9.3+3
+ file_selector_platform_interface 2.6.1 (2.6.2 available)
+ file_selector_windows 0.9.3+1
+ firebase_auth 4.15.2 (4.16.0 available)
+ firebase_auth_platform_interface 7.0.8 (7.0.9 available)
+ firebase_auth_web 5.8.11 (5.8.13 available)
+ firebase_core 2.24.2
+ firebase_core_platform_interface 5.0.0
+ firebase_core_web 2.10.0
+ firebase_messaging 14.7.8 (14.7.10 available)
+ firebase_messaging_platform_interface 4.5.17 (4.5.18 available)
+ firebase_messaging_web 3.5.17 (3.5.18 available)
+ firebase_storage 11.5.5 (11.6.0 available)
+ firebase_storage_platform_interface 5.1.3
+ firebase_storage_web 3.6.17
+ flutter 0.0.0 from sdk flutter
+ flutter_animate 4.1.1+1 (4.4.0 available)
+ flutter_blurhash 0.7.0 (0.8.2 available)
+ flutter_cache_manager 3.3.1
+ flutter_launcher_icons 0.13.1
+ flutter_lints 3.0.0 (3.0.1 available)
+ flutter_localizations 0.0.0 from sdk flutter
+ flutter_plugin_android_lifecycle 2.0.17
+ flutter_secure_storage 8.0.0 (9.0.0 available)
+ flutter_secure_storage_linux 1.2.0
+ flutter_secure_storage_macos 3.0.1
+ flutter_secure_storage_platform_interface 1.0.2
+ flutter_secure_storage_web 1.1.2
+ flutter_secure_storage_windows 2.1.1 (3.0.0 available)
+ flutter_staggered_grid_view 0.7.0
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ font_awesome_flutter 10.6.0
+ from_css_color 2.0.0
+ glob 2.1.2
+ go_router 7.1.1 (13.0.1 available)
+ google_fonts 4.0.3 (6.1.0 available)
+ google_identity_services_web 0.2.2 (0.3.0+2 available)
+ google_sign_in 6.1.5 (6.2.1 available)
+ google_sign_in_android 6.1.20 (6.1.21 available)
+ google_sign_in_ios 5.6.4 (5.7.3 available)
+ google_sign_in_platform_interface 2.4.2 (2.4.5 available)
+ google_sign_in_web 0.12.1 (0.12.3+2 available)
+ html 0.15.4
+ http 0.13.6 (1.2.0 available)
+ http_parser 4.0.2
+ image 4.0.17 (4.1.4 available)
+ image_picker 1.0.4 (1.0.7 available)
+ image_picker_android 0.8.8 (0.8.9+3 available)
+ image_picker_for_web 3.0.1 (3.0.2 available)
+ image_picker_ios 0.8.8+2 (0.8.9+1 available)
+ image_picker_linux 0.2.1+1
+ image_picker_macos 0.2.1+1
+ image_picker_platform_interface 2.9.1 (2.9.3 available)
+ image_picker_windows 0.2.1+1
+ infinite_scroll_pagination 4.0.0
+ intl 0.18.1 (0.19.0 available)
+ iregexp 0.1.1 (0.1.2 available)
+ js 0.6.7 (0.7.0 available)
+ json_annotation 4.8.1
+ json_path 0.6.2 (0.7.0 available)
+ just_audio 0.9.36
+ just_audio_platform_interface 4.2.2
+ just_audio_web 0.4.9
+ lints 3.0.0
+ logging 1.2.0
+ matcher 0.12.16 (0.12.16+1 available)
+ material_color_utilities 0.5.0 (0.8.0 available)
+ maybe_just_nothing 0.5.3
+ meta 1.9.1 (1.11.0 available)
+ mime 1.0.4 (1.0.5 available)
+ mime_type 1.0.0
+ nested 1.0.0
+ octo_image 1.0.2 (2.0.0 available)
+ package_config 2.1.0
+ package_info_plus 4.2.0 (5.0.1 available)
+ package_info_plus_platform_interface 2.0.1
+ page_transition 2.1.0
+ path 1.8.3 (1.9.0 available)
+ path_provider 2.0.14 (2.1.2 available)
+ path_provider_android 2.0.25 (2.2.2 available)
+ path_provider_foundation 2.2.2 (2.3.2 available)
+ path_provider_linux 2.1.11 (2.2.1 available)
+ path_provider_platform_interface 2.0.6 (2.1.2 available)
+ path_provider_windows 2.1.7 (2.2.1 available)
+ pedantic 1.11.1
+ percent_indicator 4.2.2 (4.2.3 available)
+ permission_handler 10.0.0 (11.2.0 available)
+ permission_handler_android 10.3.6 (12.0.3 available)
+ permission_handler_apple 9.1.4 (9.3.0 available)
+ permission_handler_platform_interface 3.12.0 (4.1.0 available)
+ permission_handler_windows 0.1.3 (0.2.1 available)
+ petitparser 5.4.0 (6.0.2 available)
+ photo_view 0.14.0
+ pigeon 11.0.1 (16.0.4 available)
+ platform 3.1.4
+ plugin_platform_interface 2.1.6 (2.1.8 available)
+ pointycastle 3.7.4
+ provider 6.0.5 (6.1.1 available)
+ pub_semver 2.1.4
+ quiver 3.2.1
+ record 5.0.4
+ record_android 1.0.4
+ record_darwin 1.0.1
+ record_linux 0.7.1
+ record_platform_interface 1.0.2
+ record_web 1.0.5
+ record_windows 1.0.2
+ rfc_6901 0.1.1 (0.2.0 available)
+ rxdart 0.27.7
+ shared_preferences 2.2.2
+ shared_preferences_android 2.2.1
+ shared_preferences_foundation 2.3.4 (2.3.5 available)
+ shared_preferences_linux 2.3.2
+ shared_preferences_platform_interface 2.3.1 (2.3.2 available)
+ shared_preferences_web 2.2.1 (2.2.2 available)
+ shared_preferences_windows 2.3.2
+ sign_in_with_apple 4.3.0 (5.0.0 available)
+ sign_in_with_apple_platform_interface 1.0.0
+ sign_in_with_apple_web 1.0.1
+ sky_engine 0.0.99 from sdk flutter
+ sliver_tools 0.2.12
+ smooth_page_indicator 1.1.0
+ source_span 1.10.0
+ speech_to_text 6.5.1
+ speech_to_text_macos 1.1.0
+ speech_to_text_platform_interface 2.2.0
+ sqflite 2.2.6 (2.3.1 available)
+ sqflite_common 2.5.3
+ stack_trace 1.11.0 (1.11.1 available)
+ stop_watch_timer 3.0.2 (3.1.0+4 available)
+ stream_channel 2.1.1 (2.1.2 available)
+ stream_transform 2.1.0
+ string_scanner 1.2.0
+ synchronized 3.1.0 (3.1.0+1 available)
+ term_glyph 1.2.1
+ test_api 0.6.0 (0.7.0 available)
+ timeago 3.2.2 (3.6.0 available)
+ typed_data 1.3.2
+ url_launcher 6.1.10 (6.2.4 available)
+ url_launcher_android 6.0.27 (6.2.2 available)
+ url_launcher_ios 6.1.4 (6.2.4 available)
+ url_launcher_linux 3.0.6 (3.1.1 available)
+ url_launcher_macos 3.0.7 (3.1.0 available)
+ url_launcher_platform_interface 2.1.2 (2.3.1 available)
+ url_launcher_web 2.1.0 (2.2.3 available)
+ url_launcher_windows 3.0.8 (3.1.1 available)
+ uuid 3.0.7 (4.3.3 available)
+ vector_math 2.1.4
+ video_player 2.8.1 (2.8.2 available)
+ video_player_android 2.4.10 (2.4.11 available)
+ video_player_avfoundation 2.5.1 (2.5.6 available)
+ video_player_platform_interface 6.2.1 (6.2.2 available)
+ video_player_web 2.1.2 (2.1.3 available)
+ wakelock_plus 1.1.4
+ wakelock_plus_platform_interface 1.1.0
+ watcher 1.1.0
+ web 0.1.4-beta (0.4.2 available)
+ win32 5.1.1 (5.2.0 available)
+ xdg_directories 1.0.4
+ xml 6.3.0 (6.5.0 available)
+ yaml 3.1.2
Changed 205 dependencies!
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/builder/.rbenv/versions/3.0.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.13.0
        Ruby : ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]
    RubyGems : 3.4.20
        Host : macOS 13.3.1 (22E261)
       Xcode : 14.2 (14C18)
         Git : git version 2.39.2
Ruby lib dir : /Users/builder/.rbenv/versions/3.0.4/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 4419c469e56b99217ca68c65d9c895f83f7e8fed

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'GoogleUtilities'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        # dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        # dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        # dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        # dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end

target 'ImageNotification' do
  use_frameworks!
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'
end
```

### Error

```
RuntimeError - [Xcodeproj] Type checking error: got `PBXFileReference` for attribute: Attribute `files` (type: `to_many`, classes: `["PBXBuildFile"]`, owner class: `AbstractBuildPhase`)
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object_attributes.rb:142:in `validate_value'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object_list.rb:205:in `block in perform_additions_operations'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object_list.rb:202:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object_list.rb:202:in `perform_additions_operations'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object_list.rb:76:in `<<'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:301:in `block (2 levels) in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:113:in `open'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:1194:in `block (2 levels) in inspect_targets_to_integrate'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:1193:in `each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:1188:in `inspect_targets_to_integrate'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:422:in `analyze'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:162:in `install!'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
/Users/builder/.rbenv/versions/3.0.4/bin/pod:25:in `load'
/Users/builder/.rbenv/versions/3.0.4/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Type+checking+error%3A+got+%60PBXFileReference%60+for+attribute%3A+Attribute+%60files%60+%28type%3A+%60to_many%60%2C+classes%3A+%60%5B%22PBXBuildFile%22%5D%60%2C+owner+class%3A+%60AbstractBuildPhase%60%29&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - RuntimeError - [Xcodeproj] Type checking error: got `PBXFileReference` for attribute: Attribute `files` (type: `to_many`, classes: `["PBXBuildFile"]`, owner class: `AbstractBuildPhase`)
   https://github.com/CocoaPods/CocoaPods/issues/9117 [closed] [4 comments]
   22 Aug 2019



Build failed :|
Step 6 script `Install pods` exited with status code 1`

**Comment by bbeckford** [comment]
I'm also having this issue, really getting in the way of development now! Thanks

**Comment by sharmilaccd** [comment]
Facing the same issue... Hope this gets fixed soon!

**Comment by treyhendon** [comment]
Are you using custom Authentication by chance?  If so, I noticed you listed 4.0 as your FlutterFlow version.  The recent 4.1 update seems to have resolved my "silent" errors.

https://github.com/FlutterFlow/flutterflow-issues/issues/2152#issuecomment-1910870689

**Comment by aemelyanovff** [comment]
@bbeckford Please add a bug report code from anywhere in the project, otherwise we can't troubleshoot the issue.

**Comment by bbeckford** [comment]
@aemelyanovff Looks like this is fixed, thanks #2152

**Comment by paulVu** [comment]
It's fixed. 
But at the old project. You need to edit a custom function to compiling again. it's will solved. 
<img width="194" alt="Screenshot 2024-01-31 at 11 26 56 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/5940d28c-f7ba-4a04-91e6-851305496747">
<img width="284" alt="Screenshot 2024-01-31 at 11 27 10 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/32fef20b-024e-463d-a137-d0e2e17d78d2">

**Comment by ChecoG88** [comment]
Hi, I'm having the same issue, but it haven't solved with the upgrade.
<img width="1470" alt="Captura de pantalla 2024-01-31 a la(s) 7 22 30 p m" src="https://github.com/FlutterFlow/flutterflow-issues/assets/158389058/62e94b53-4a83-44cc-a023-fc2f59244c1f">

**Comment by aemelyanovff** [comment]
Closing this issue as resolved.

> Hi, I'm having the same issue, but it haven't solved with the upgrade.

@ChecoG88 Please create a new issue with a new bug report code. This seems to be something differently (unfortunately there's more than one reason why an "Unknown error compiling custom code" can occur.

**Comment by ollosimango** [comment]
I have a solution. place this in a stack with a PointerInterceptor (custom code) place the button on top of the custom widget and you will be able to click there
