### ISSUE TITLE
Firebase issue creates Account without getting Email + Password. Testflight + Run Mode

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#2235]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is also happening in run mode.
I am creating an account with a simple flow -> Name + Email + Password
But I just checked and it is going through creating an account without even giving any errors regarding
Video Attached + Action flow attached.

### Expected Behavior

I have already done over 10+ builds and tested. Only this one came up like this.

I did new things from firebase
\\\\\\\\\\\\\\\\-> Deploy Delete User
\\\\\\\\\\\\\\\\-> Setup Indexes
\\\\\\\\\\\\\\\\-> Re-deploy the Rules.
Firebase

### Steps to Reproduce

1. Create Account Action Firebase
2. Pass name + email field

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcj15YhNvuZE7aX6bu9aq2AsJm01UIc0sNobbxAjIoDoPJkUacj8bRZuTeG6d1VXKEWLgXMxzPONjeGeLMFeITWabJxizod6YRXgLWK/aoSJDqW8eUR7HdtQFUuP0MGN2BBCNbB2clo91zqUfvDJYCnZJO77Zwh9f6PHaOI=

### Context

.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/4a6e36e1-81c7-4017-9176-a400b31f120e](https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/4a6e36e1-81c7-4017-9176-a400b31f120e)

![Screenshot 2024-01-25 at 10 29 29 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a0e8ff3f-60bc-48f8-aec5-2c099cb57b66/582944ca-1d1b-4d75-bd9e-11e314a78de0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMGU4ZmYzZi02MGJjLTQ4ZjgtYWVjNS0yYzA5OWNiNTdiNjYvNTgyOTQ0Y2EtMWQxYi00ZDc1LWJkOWUtMTFlMzE0YTc4ZGUwIiwiaWF0IjoxNzA3MTU2MzkwLCJleHAiOjMzMjc3NzE2MzkwfQ.o-YXzI1tmsoXO-zo66BzauCQ70OJhybICmrFVnE5tkA "=795x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: Web,IOS
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by Dev-Muhammad-Junaid** [comment]
In addition to this. Not sure if I should create another issue. But seems to be Google Fonts API issue as well. 
I'm using Poppins + Lato.
![148shots_so](https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/aed7e285-2b1c-4daf-a265-45f1c4f3b615)

**Comment by Dev-Muhammad-Junaid** [comment]
For now, I have managed to fix this using Form Validation. As I already have edge cases setup and the App didn't crash on me. But it could easily do so in such cases

<img width="398" alt="Screenshot 2024-01-25 at 11 01 56 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/7d9b94bf-9ef9-4c0e-b5e6-8e974d7c17d3">

**Comment by hariprasadms** [comment]
Hi @Dev-Muhammad-Junaid - Thanks for reporting the issue. Based on your latest comment, has the issue now been resolved on your end?

**Comment by Dev-Muhammad-Junaid** [comment]
@hariprasadms the issue is still there. Its a work around I did. 
Secondly , there is also internal error with Firebase 
during login with the Wrong password. Is that also related?
It keeps showing in Testflight version. 
![Simulator Screenshot - iPhone 15 Pro - 2024-01-25 at 11 49 47](https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/e2706c5f-1128-40d6-92db-b3c3aa0a32e6)

**Comment by hariprasadms** [comment]
> @hariprasadms the issue is still there. Its a work around I did. Secondly , there is also internal error with Firebase during login with the Wrong password. Is that also related? It keeps showing in Testflight version. ![Simulator Screenshot - iPhone 15 Pro - 2024-01-25 at 11 49 47](https://private-user-images.githubusercontent.com/65047962/299619751-e2706c5f-1128-40d6-92db-b3c3aa0a32e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzg1MjAsIm5iZiI6MTcwNjE3ODIyMCwicGF0aCI6Ii82NTA0Nzk2Mi8yOTk2MTk3NTEtZTI3MDZjNWYtMTEyOC00MGQ2LTkyZGItYjNjM2FhMGEzMmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwMjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNWQ5ZjM5MDM3MTAxNmQ4MWVhYzk5NjcxMjI4ZDcwOWQ1ZWFiYzYxZjdhNWM5OTZmZmJhZTU1Zjc0ZDlkZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AUACyhjqJ41TxlWALfyPju1kjeLsfsQ0IMhsMSOIcOU)

This is we already know. There is issue raised for this is already.

**Comment by Dev-Muhammad-Junaid** [comment]
Okay sure. Can you kindly provide link to the issue to keep track once its fixed?
