### ISSUE TITLE
HTML View Widget displaying data from am Action Output only correct in FF Test mode but not on a physical device (IOS or Android)

### ISSUE THREAD

**Issue by RonGelb** [FlutterFlow/flutterflow-issues#2237]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have created a component named 'utf8DecodeAndDisplayHtml' which includes a HtmlView widget. This HtmlView widget is responsible for displaying data from an Action Output called 'decodedString.' This Action Output is generated through two actions during initialization: a Custom Action named 'firestorageToString' and 'Update Component State.'

The 'NotebookMain' page utilizes the 'utf8DecodeAndDisplayHtml' component to display the content that the user inserted on the 'Html' page.

When we run the app in FF Test-Mode, everything runs as expected. However, when we deploy the app to a physical device, whether it's IOS or Android, we receive at the 'NotebookMain' page a NULL value at 'HtmlView' of the 'utf8DecodeAndDisplayHtml' component instead of the expected text.

### Expected Behavior

Receive a string not a NULL value

### Steps to Reproduce

1\\\\.) Start the app and create an account using the "Create Account" button (other login modes currently not implemented)
2\\\\.) On the next page press "Select Container"
3\\\\.) On the next page press "Select Notebook"
4\\\\.) On the next page press "Add Note"
5\\\\.) Now enter a title text for the note under "Title" and enter a text or you can use the default text "Text" and press "Save"
6\\\\.) You will directed to the "NotebookMain" page and you will see the Title and the text in test mode, but not on a physical device. On the physical device you will see a ? which indicates a NULL value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oismB25NPj7xC7qrubvlahSQRJj99U78e1spBazwbfe+uB4kqevfOTERuUsTiSghUeWG0hWoW3N7lifLtFPQDGxGYbt1H/rhUTgvMRlitMpiMFJWgVEcmBZhmJn6s38KnnRFSIbJ2WHAS1GemOd/LVgPUNZDtC2seDa/LZO4=

### Context

We can not go on with the production of the app with at issue. Production is on hold!

### Visual documentation

![screen](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f0414e6a-3c20-46f0-a563-51f789f25caa/5caede89-05c4-41a5-a71e-b4add46c8656?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMDQxNGU2YS0zYzIwLTQ2ZjAtYTU2My01MWY3ODlmMjVjYWEvNWNhZWRlODktMDVjNC00MWE1LWE3MWUtYjRhZGQ0NmM4NjU2IiwiaWF0IjoxNzA3MTU2Mzg5LCJleHAiOjMzMjc3NzE2Mzg5fQ.V2PXcR_NU54lFBjJRdvAlQI_vcsUz-6irMwyMbBiZQg)

![screen1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/eb351fa2-7643-4ac6-a418-8b5de1002ea4/9494fac5-b81b-4e27-b861-99163f3c704f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYjM1MWZhMi03NjQzLTRhYzYtYTQxOC04YjVkZTEwMDJlYTQvOTQ5NGZhYzUtYjgxYi00ZTI3LWI4NjEtOTkxNjNmM2M3MDRmIiwiaWF0IjoxNzA3MTU2Mzg5LCJleHAiOjMzMjc3NzE2Mzg5fQ.AbcSvVLhrHpXgaBbhdnKCLNgbW4EAAPNqrgiWyRDBjY)

### Additional Info

---

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: MAC and PC
- Browser name and version: Not depending on a browser
- Operating system and version affected: IOS and Android
```

**Comment by RonGelb** [comment]
I wanted to bring to your attention that the issue regarding the FF package, for which I have an active support subscription, has been open for the past 7 days without any recent activity from the support team.

As a valued customer, I rely on the support provided to address and resolve any issues promptly. I kindly request you to check the status of the support ticket associated with my FF package and provide updates or assistance at your earliest convenience.

Your prompt attention to this matter is crucial to ensuring a seamless experience with the FF package. If there are any additional details needed from my end, please let me know, and I'll be happy to provide them.

Thank you for your immediate assistance.

**Comment by leighajarett** [comment]
Thank you for your message. We're sorry you're dealing with this! We'll look into it as soon as we are able to. Thanks so much for understanding!

**Comment by RonGelb** [comment]
You're welcome! If you have any further questions, please don't hesitate to reach out.
