### ISSUE TITLE
DATE bug in FlutterFlow

### ISSUE THREAD

**Issue by pdp020460** [FlutterFlow/flutterflow-issues#2238]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When in Flutterflow I have added a Date Time variable in the Firestore Data Manager. Then I manually enter adate of birth into the Firestore Data Manager (not when setting as a variable within the Flutterflow language). The Firestore Data Manager says that I can not add an age prior to January 1, 1970 !

I received the follow response from Henry (below) and photo (also below).

Hi there,
Thanks for reaching out – I am happy to help!

It looks like a current restriction from FlutterFlow that you cannot set a date before 1970 using content manager. But we see how this could be very helpful to you and others! Thank you for sharing. 😊
If you have a moment, could you record this suggestion through our [in-app feature request tool](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#how-to-submit-bug-reports-and-feature-requests)? Sharing your ideas here helps us centralize requests across all users and prioritize the features that are most needed within the FlutterFlow community.

Best,
Henry

![Date Issue](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4ac4c4e6-9fe5-4120-97ca-47480ea8489e/cc3490fb-7ae0-45fc-8a7b-cb1792adfa9a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YWM0YzRlNi05ZmU1LTQxMjAtOTdjYS00NzQ4MGVhODQ4OWUvY2MzNDkwZmItN2FlMC00NWZjLThhN2ItY2IxNzkyYWRmYTlhIiwiaWF0IjoxNzA3MTU2Mzg5LCJleHAiOjMzMjc3NzE2Mzg5fQ.Pn4EYEM3NItYQn1G8FlTRu4AgrrifTT4NFLnPoiVhug)

### Expected Behavior

That a time period prior to Jan 1 1970 is possible.

### Steps to Reproduce

See photo.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

This is not applicable

### Context

Its a minor irritation and can be worked around.

### Visual documentation

See attached photo

### Additional Info

See Photo

### Environment

```
- FlutterFlow version: 4.0
- Platform: Windows 11
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by leighajarett** [comment]
Thanks for reporting this! We're sorry you're facing this issue. Since this is a feature enhancement, I will add it to our tracking system for feature requests and discuss with the team. I'll close this issue since this tracker is specifically for bugs.
