### ISSUE TITLE
DataTable not allowing to create a backend query

### ISSUE THREAD

**Issue by santiramirezc** [FlutterFlow/flutterflow-issues#2239]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to create a datatable and bound its data to a backend query but flutterflow is not showing this icon

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/957374e2-6de8-4dd5-bb25-82c36a0e86fb/642ce9fd-8b46-4da2-9a9f-1aed44761c6d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NTczNzRlMi02ZGU4LTRkZDUtYmIyNS04MmMzNmEwZTg2ZmIvNjQyY2U5ZmQtOGI0Ni00ZGEyLTlhOWYtMWFlZDQ0NzYxYzZkIiwiaWF0IjoxNzA3MTU2Mzg4LCJleHAiOjMzMjc3NzE2Mzg4fQ.Nq08y9rgilBqftOmDMJR2A0m6UsTq8po3KBN1FRH1wA)

### Expected Behavior

I should be able to create a backend query on a DataTable Widget

### Steps to Reproduce

1. Create new page
2. Add DataTable witget
3. Try to add a backend query

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlcjc35RgoctG0arqacZqhTIgNkwhaIJIiutudxMrCJyuB4gUZ/T7fk5UOMukdFFDM2H9gjgX/Mrwj9nDKvQnAz6bf6pk/qthWALzWkyuR8nQEa63b2gnQMNTIGqEyLSWnhRTJbNvW3AM212Hfuuib3fDHqb6PUU7Q+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I can't use DataTable witget. Can't deploy my app

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bbdd0338-cec6-4b15-a19f-55bbb50c850c/eb54810f-9e04-4681-9dc2-57fb207bc1a6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYmRkMDMzOC1jZWM2LTRiMTUtYTE5Zi01NWJiYjUwYzg1MGMvZWI1NDgxMGYtOWUwNC00NjgxLTlkYzItNTdmYjIwN2JjMWE2IiwiaWF0IjoxNzA3MTU2Mzg4LCJleHAiOjMzMjc3NzE2Mzg4fQ.KeSNCa453DIVoerpZfvzX2hMc_6K1702NSskz6TwUog)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version:FlutterFlow v4.1 released January 25, 2024 | Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome Versión 120.0.6099.225 (Build oficial) (64 bits)
- Operating system and version affected: Windows 11
```

**Comment by carlosgonzalezucv** [comment]
same here guys

**Comment by carlosgonzalezucv** [comment]
workaround. I'll just wrap the datatablee widget with a container and then make the backend query from that container.. After that  you just need to set the rows dinamically and thats it..

**Comment by takashiff** [comment]
Hi all, the DataTable widget intentionally does not currently support backend queries by design. We want to steer users towards the design that @carlosgonzalezucv has described, in which the backend query occurs at a page, column, or container level. Thanks
