### ISSUE TITLE
Firebase field dataType select does not scroll

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#224]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
A pop-up with all data types appears and when Doc Reference is selected, the pop-up can be scrolled

## Current behavior (required)
A pop-up with all data types appears and when Doc Reference is selected, the pop-up can NOT be scrolled

## To Reproduce (required)

1. Add a field on a firebase collection.
2. Select Doc Reference as Data Type. 
3. Try to scroll to select which reference to add as a data type

## Context (required)

It happens in the MacOS flutterflow app

## Your environment

* Version of FlutterFlow used: 1.1.24
MacOS Flutterflow App. (MacOS 13.1 Ventura M1 Chip)

**Comment by organicnz** [comment]
Hi @pstatile . Thank you for adding this issue 🙂
Yeah, there's a scrolling bug. I was able to reproduce this issue. Could you pls work in the Chrome browser for now? :)

**Comment by organicnz** [comment]
Recording:
https://www.loom.com/share/13a2f66293a7431fa3cfd7516715dbbb

**Comment by agreaves** [comment]
Thank you for this bug report! This will now be fixed upon our next release 🙂

**Comment by pstatile** [comment]
Great! Thanks!
