### ISSUE TITLE
Cloud Function Region is not set in Code

### ISSUE THREAD

**Issue by abegehr** [FlutterFlow/flutterflow-issues#2242]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

new_contact_sheet2_model.dart L127: `FirebaseFunctions.instance.httpsCallable('searchFor')`

### Expected Behavior

I expect the cloud function call to have the region specified that I have set on the cloud function definition in FF (default = europe-west3). However it soely specifies `.instance`, instead of `instanceFor(region: 'europe-west3')`.

### Steps to Reproduce

1. Create a Project with default region europe-west3.
2. Create a function.
3. Implement an action on a button that calls the function.
4. Push code to GitHub.
5. Function region is not europe-west3 but is not set at all.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlvHqx892rsBE15PIbcdviWIwGUQFUOdEl95Hd0gdCOPrBu0UZsjeVFRBQsO4aVNcPlWZoEIe+s7RiOOeJPECFyuCbphk1LlqaRXee2iWVbabO5CoS0EnQPtYIWKe5raskCVNKtZsSkIi32CQAdyAdzDDFOu/Zwh9f6PHaOI=

### Context

I'm trying to call a cloud function coded in FF from the FF app. 

### Visual documentation

n.a.

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome 120.0.6099.234
- Operating system and version affected: 
macOS 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @abegehr - Thanks for reporting the issue. After reviewing your project, it seems that the cloud function region settings in the property section indicate "default," but in the code, a specific region is selected. 

I can confirm that the Git push code successfully takes the changes in the cloud function and applies them to the associated action with the selected region without any issues. If you have any further questions or concerns, please let me know.
 
Below is your project cloud function code snippet.

<img width="1183" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a183ea00-e32a-465f-8a3a-13dbacfec8ca">

**Comment by abegehr** [comment]
Hey @hariprasadms, thank you for taking a look! That's correct, the cloud function region is set to `[Default]`, however the project's default is `europe-west1`.

The code comes form the boilerplate generator and includes the region setting:

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
// To avoid deployment errors, do not call admin.initializeApp() in your code

exports.searchForDoctor = functions.region('europe-west3').https.onCall(
  (data, context) => {
		if (!context.auth.uid) {
      return;
    }
		const query = data.query;
		const place = data.place;
    // Write your code below!

    // Write your code above!
		return [{
      "name": "",
			"types": "",
			"contactId": ""
    }];
  }
);
```

![Screenshot 2024-01-26 at 14 12 14](https://github.com/FlutterFlow/flutterflow-issues/assets/23075874/f0895960-d13b-42e9-975b-bd2e3d65a40e)

Therefore, if FF's boilerplate code generator treats the project's region as `[Default]`, I would expect the FF client to also treat the project's region as `[Default]` and not use the global cloud functions default of `us-central1`.
As a workaround, I'll set the cloud function region manually instead of `[Default]`.

**Comment by hariprasadms** [comment]
Hi @abegehr - When switching the region from the default value to another value , it's essential to regenerate the boilerplate code and save the changes manually. The code in the editor does not update automatically, and this reflects the current behaviour. Refer the tool top at the cloud function region dropdown. 

What you mean by project default is europe-west3?

**Comment by abegehr** [comment]
The firebase project's default region is `europe-west3`.
With `Cloud Function Region` set to `[Default]`, the boilerplate generator set's the function region to `europe-west3`. I have saved the function in between boilerplate generation. When setting to another region, it specifies that region in the boilerplate generator. When choosing default the boilerplate sets to `europe-west3`.
![Screenshot 2024-01-26 at 14 51 20](https://github.com/FlutterFlow/flutterflow-issues/assets/23075874/5efa3ee6-7b2b-441d-ab63-4b8d1be43956)
![Screenshot 2024-01-26 at 14 51 27](https://github.com/FlutterFlow/flutterflow-issues/assets/23075874/fe33e7b6-9dbd-40a1-b894-668124500061)

**Comment by takashiff** [comment]
Hi @abegehr, thank you for your bug report. We've recently put in a fix for this issue, and it should be reflected within the coming weeks. Thank you for your patience.
