### ISSUE TITLE
DataTable compilation error when trying to use index in list

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#2243]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When populating a DataTable with a list and assigning the index from list to a text widget inside a DataCell, FF will show a compilation error on test mode saying that "The getter 'xIndex' isn't defined for the class '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_YWidgetState'." (where "x"is the list name and "Y" is the page name), although no errors are shown in the UI builder

### Expected Behavior

Test mode compilation should recognize list index variable from populated data.

### Steps to Reproduce

1. Create new page
2. Add DataTable widget
3. Add sample list from variable (list of names, for example) and give it any name ("testList", for example)
4. Change text inside any DataCell to show index from testList defined in previous step
5. Start test mode
6. Error occurs

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gosxH7ZDuKMZqhTIgNkwhaIJIiutudxMrCJyuB4gUZ/T7fk5UOOrjSmxtemD9uGEX/MqLjvLpOPAoPSqsfNlnzc0MWDzvTl6tMbq1PK63b0BPJNJMCX7A0KavvhBAWPtfcWQa2F7zG+utYBTXHr7sPmojQeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

It's slowing my development as I need to find a workaround to mimic a DataTable's appearance, with containers, columns and rows.

### Visual documentation

1. Create new page

![Captura de Tela 2024-01-26 às 02 21 58](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/000da9ae-cffd-410e-b199-adbfc2acf1bf/a1b989f6-aa87-4ec5-8b09-dbd635810fae?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMDBkYTlhZS1jZmZkLTQxMGUtYjE5OS1hZGJmYzJhY2YxYmYvYTFiOTg5ZjYtYWE4Ny00ZWM1LThiMDktZGJkNjM1ODEwZmFlIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.nTmbFmswScv0SIV7EcZLRZMp_U1NO8CXxexHoLCTjxs)

1. Add DataTable widget

![Captura de Tela 2024-01-26 às 02 22 57](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4f3e3570-19a0-44c7-8bde-13191f760411/91671bf6-66e2-41a3-b479-36909b142729?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZjNlMzU3MC0xOWEwLTQ0YzctOGJkZS0xMzE5MWY3NjA0MTEvOTE2NzFiZjYtNjZlMi00MWEzLWI0NzktMzY5MDliMTQyNzI5IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.rWyPzq8HsqH_XwOqChViCr-G6gBJQi0oV0n_IMpMxBc)

1. Add sample list from variable (list of names, for example) and give it any name ("testList", for example)

![Captura de Tela 2024-01-26 às 02 23 51](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/62ce4976-0acc-48ea-9018-29b7a91b37c9/78e15c7a-e9dd-4ea4-9af0-2f32d538e11f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MmNlNDk3Ni0wYWNjLTQ4ZWEtOTAxOC0yOWI3YTkxYjM3YzkvNzhlMTVjN2EtZTlkZC00ZWE0LTlhZjAtMmYzMmQ1MzhlMTFmIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.sZm66oV_ypTXmtqs4z3F564u7kjYOTpBsJBiZ5DtPRM)

1. Change text inside any DataCell to show index from testList defined in previous step

![Captura de Tela 2024-01-26 às 02 24 50](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/474e7fb1-5f83-40b5-832e-5c3da5c5a4af/7d185c42-7b70-43ec-a44e-79b1ec7c555f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NzRlN2ZiMS01ZjgzLTQwYjUtODMyZS01YzNkYTVjNWE0YWYvN2QxODVjNDItN2I3MC00M2VjLWE0NGUtNzliMWVjN2M1NTVmIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.qYRvJN73dOJJybLw2OkLcOSV2RFiIsCpMAoKBq2Dtbw)

![Captura de Tela 2024-01-26 às 02 25 09](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/44a90484-fa39-4742-bd67-061ccb77ed35/258f4c15-d35a-4172-81a2-05b0db88bd79?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NGE5MDQ4NC1mYTM5LTQ3NDItYmQ2Ny0wNjFjY2I3N2VkMzUvMjU4ZjRjMTUtZDM1YS00MTcyLTgxYTItMDViMGRiODhiZDc5IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.mS6SDJJID0Jz485wjOrWH7hKUXLHftExAWuivW5KpGg)

1. Start test mode

![Captura de Tela 2024-01-26 às 02 26 24](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d5af193f-26b6-4a40-b0f0-08cb7a417986/0072a8b0-c9b3-40c2-8725-3d3b255fc65c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNWFmMTkzZi0yNmI2LTRhNDAtYjBmMC0wOGNiN2E0MTc5ODYvMDA3MmE4YjAtYzliMy00MGMyLTg3MjUtM2QzYjI1NWZjNjVjIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.lhfmctRHR08vb85857qalBumfWk-U1-R4HmCwod9Hz8)

1. Error occurs

![Captura de Tela 2024-01-26 às 02 27 20](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f13806cc-fa60-43be-b153-5f04397d9424/d0037611-5773-425a-8f0a-f86546e61d89?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMTM4MDZjYy1mYTYwLTQzYmUtYjE1My01ZjA0Mzk3ZDk0MjQvZDAwMzc2MTEtNTc3My00MjVhLThmMGEtZjg2NTQ2ZTYxZDg5IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.2F7YCWj4aZgvR7HZ_5jW_6_zaRd9sxBGqpnA2S7CqCY)

### Additional Info

Detailed error message:

> Launching lib/main.dart on Web Server in debug mode...
> Waiting for connection from debug service on Web Server...
> lib/pages/home_page/home_page_widget.dart:124:29: Error: The getter 'testListIndex' isn't defined for the class '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_HomePageWidgetState'.
>
> * '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_HomePageWidgetState' is from 'package:test/pages/home_page/home_page_widget.dart' ('lib/pages/home_page/home_page_widget.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named 'testListIndex'.
>   testListIndex.toString(),
>   ^^^^^^^^^^^^^
>   Waiting for connection from debug service on Web Server... 42.3s
>   Failed to compile application.

### Environment

```
- FlutterFlow version: 4.1.23
- Platform: MacOS Desktop
- Browser name and version: Brave v1.62.153
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @vitoras - Thanks for submitting the issue. I can reproduce the issue. Thanks

**Comment by antunesales-dev** [comment]
Hi all, is supposed to populate the table now with the "Generate Children from Variable"? Instead of querying?  @hariprasadms

**Comment by aemelyanovff** [comment]
Fixed - the project in the bug report builds fine in the last update.
