### ISSUE TITLE
Creating Branch from Branch - Unable to Merge/Rebase Back to Main

### ISSUE THREAD

**Issue by Optionaled** [FlutterFlow/flutterflow-issues#2244]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a branch from main called "Subcollection_magic".
From this branch I created a new branch "choiceChip_from_datatype".
I then deleted "Subcollection_magic", as I wanted to clean up the branches.

After being finished with the work on "choiceChip_from_datatype", I want to merge back to main. But there is no option for it in the branching dialog
I only have options to merge or rebase back to "Subcollection_magic".
I don't want to do that, but if I "merge" or "rebase" (to "Subcollection_magic"), nothing happens (as the branch does not exist).
<img width="392" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2619339/f7909de0-a843-4114-bfb6-9e726d5430af">

### Expected Behavior

Having a functional dialog option where I can rebase or merge back to main.

### Steps to Reproduce

1. Create branch A from main
2. Create branch B from branch A
3. Delete branch A
4. Try to merge back to main or A

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40if/Z+axis8Nf4bnyV8F4oCQUQ3p7aL83lO1BaCosfZT2BLMcec/RVERpXcCoYWNUMGC0jWoW0fz0keLhV8BdCz+cfb5l/qlqSQLMZEiQVZDWFJWgZkEnGcZmCHav0bezoBFQHM1vSmQm7TqUJfCWcDXsNYTbO1cSDq/LZO4=

### Context

I am unable to collaborate with my team and merge back my changes from a feature branch
Project: https://app.flutterflow.io/project/oNJR4ChP2Mo9mkjxj2on?tab=uiBuilder&page=InitiativeForm

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/2619339/f2b04170-fbc0-4845-8369-4e2eaa86ac41

### Additional Info

<img width="392" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2619339/e3064b70-552a-4fc4-81b4-e188dd4422ad">

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: N/A
- Browser name and version: Safari Version 17.2.1 (19617.1.17.11.12)
- Operating system and version affected: Version 14.2.1 (23C71
```

**Comment by Optionaled** [comment]
Hey.
Any updates or workarounds here? I need to merge into main. 
Best,
Tim

**Comment by takashiff** [comment]
Hi @Optionaled, this is currently intended behavior, as FlutterFlow currently only supports merging/rebasing into the parent branch. However, I've changed the parent branch of `choiceChip_from_datatype` to `main`, so you should be able to merge it back in for now. We are currently working on a way to block users from deleting branches with unmerged child branches, but in the meantime, please make sure any sub-branches are merged into the parent before proceeding with deletion. Thanks

**Comment by Optionaled** [comment]
Hi.
I presume this is the intended way it should work until you have added functionality to merge to any branch?
Coming from GIT, I am used to being able to branch out to topic branches as it fits, and then merge back to main, without having to merge all the way through all the "parent branches".
Thanks.

**Comment by Optionaled** [comment]
Makes sense! Thanks for your feedback.
