### ISSUE TITLE
Build error bug with recent Gridview update

### ISSUE THREAD

**Issue by mixart** [FlutterFlow/flutterflow-issues#2245]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the recent update to be able to add END SPACING on a grid view, when a value is set, there is build error in flutterflow. If I remove the end spacing it builds OK.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/701c3713-1524-434b-9792-851c3d063177/ae683bcc-a850-4649-956f-a28eeccb30f9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MDFjMzcxMy0xNTI0LTQzNGItOTc5Mi04NTFjM2QwNjMxNzcvYWU2ODNiY2MtYTg1MC00NjQ5LTk1NmYtYTI4ZWVjY2IzMGY5IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.Mq-a-8DRbkMrnSzbnqLpfPb6Fi3GSzcd5peSoXztLBQ)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e8381beb-6e51-4392-8f53-20aab8859404/7c1e5fe0-4528-42eb-94a2-dba4a972ce2f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lODM4MWJlYi02ZTUxLTQzOTItOGY1My0yMGFhYjg4NTk0MDQvN2MxZTVmZTAtNDUyOC00MmViLTk0YTItZGJhNGE5NzJjZTJmIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.WeZhzU8sWdKAK0vN2W7sAMHu_tJo5YIPlx_pwKAg2Wc)

### Expected Behavior

FF should be able to build when you use a new feature or it's just silly.

### Steps to Reproduce

1. Create a grid view
2. Enter end spacing
3. Build in FF
4. Error displays (see second image)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si87huIh1rsdC+KqJccBB/Tk7JmZ6apIOscp8RQEYGIjJP4kQPPXsRBRvTfHgYX9DeUSmmngz0dbnks7yU/Y5FxKZf7piwbpfWzqVTk2Qa5OBPJCSZmhCP+RYfGWB4Z+k3R5CIutickYu31+MGdmySindQ4OzImdISq/LZO4=

### Context

Can't build, need end spacing feature to deploy my project.

### Visual documentation

Attached images

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.1
- Platform:browser
- Browser name and version: google chrome
- Operating system and version affected: mac
```

**Comment by hariprasadms** [comment]
Hi @mixart - Thanks for submitting the issues. Is this still happening. I just tested it and it all works fine with no build failures.

**Comment by hariprasadms** [comment]
Hi @mixart - I can reproduce the issue. 

Dev note - This typically occurs when end spacing is applied. Additionally, the end spacing entry doesn't seem to have any visible effect in the editor.
