### ISSUE TITLE
Passing null values in API Call

### ISSUE THREAD

**Issue by Dark-Akkula** [FlutterFlow/flutterflow-issues#2246]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a supabase instance where I am making api calls out from flutterflow.  If I have a double variable type in the flutterflow app, supabase throws an error when trying to test the api saying

{
  "code": "PGRST102",
  "details": null,
  "hint": null,
  "message": "Empty or invalid json"
}

However, if I input a default value of 0 or another valid double, it works just fine.  This appears to be the case because 'null' is not able to be input as a default value for most data type in an api request.  If the null placeholder is not used, flutterflow either sends and empty string or in the case of a double the api call just fails without any placeholder in the value for that json.  In my testing I have also found this same behavior in date fields.  

The only solutions I can think of is having to dummy out data in the api call and have a process on the back end to fix these dummied out fields.  I would think the ability to pass null values in an api call is a pretty important feature and a deal breaker for many users who may not adopt the platform if they are forced to junk up their database with empty strings and dummy data.

Is there a work around or fix or am I missing something on how to pass null values?

### Expected Behavior

Be able to pass a null value for all api call variables

### Steps to Reproduce

Create a supabase instance and send a post request to post data.  You either have to post dummy data or empty strings.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z/Lq7ot2sctK1bryb/pahjs5JlAmRpEnksJ7aCosfZT2BLMcec/RVERBTd/mYAlbM1n9jWoW0anJjt+SIMY6KS2YQLk/wcxhEg/MYEGmMMmwFJWgQ0YnRJ5MG26+4bWRrB1AHMhacnAe6073C+uQYDDXJpzJDmswDa/LZO4=

### Context

Send a post request to supabase without dummy data or empty strings

### Visual documentation

n/a

### Additional Info

na

### Environment

```markdown
- FlutterFlow version: Most Recent
- Platform: Web
- Browser name and version: All
- Operating system and version affected: All
```

**Comment by nev-21** [comment]
I have this problem too

**Comment by Dark-Akkula** [comment]
Another related issue is that if you have previous data in Supabase that has true NULL values, when you pull the data into flutterflow the value of "NULL" is actually populated as a string inside a text widget (and likely others).  This causes real problems because the user sees "NULL" and has to physically overwrite that value and the data validation won't work either.  For example, if you have a required field that must be populated, the form validation won't recognize there is no value in that field if a "NULL" string is sitting in there tricking the system to believe a value is there when it really isn't on the back end.

**Comment by hariprasadms** [comment]
Hi @Dark-Akkula - According to the current design, assigning a null value to API variables is not possible. If you set null as the default value for a string variable, it is treated as a string

**Comment by nev-21** [comment]
Hi, @hariprasadms thank you, please is there a way to fix that in order API variables accepts null, cause JSON accepts null

**Comment by Franco98404** [comment]
I also have the problem

**Comment by JoaquinMendoza28** [comment]
I have the same problem.

**Comment by Dark-Akkula** [comment]
I would hope this is something that is on the roadmap to be addressed in some way.  Null values are pretty important to pass, particularly if your back end is doing calculations.  This is not just an issue with Supabase but whatever backend you are using.  Forcing a zero value in a double field as a default could give a wrong calculation in the database if really the calculation is undefined.  For example, saying sales tax is zero on an order if a rate is not properly set.  I also think it would be better to not force income data with null values into a string saying "null" instead of giving a true null for the same reasons.  I can try to use custom functions to get around this issue and reload incoming api data but I cannot do much for outbound api it doesn't seem.  

I love the platform and you have a lot of really cool and fancy features...but this seems like one that is a pretty basic functionality that perhaps should be prioritized before doing something more "sexy."

**Comment by takashiff** [comment]
Hi @Dark-Akkula, as @hariprasadms has stated earlier, this is a current limitation of FlutterFlow. However, I agree with your sentiments and I do believe this needs to be addressed, so I have put in a feature request internally to support null values. Thanks

**Comment by smplfy** [comment]
I'm also experiencing this issue. Hoping a fix is in the works.

**Comment by tizum** [comment]
I'm having the same problem too, my system works 100% based on an API for the backend made in C#, how can I get around this problem? There is something in the roadmap to improve this, as API Call is an extremely important feature.

**Comment by metalik** [comment]
I am facing same problem too. Null value support for API call is essential feature.

**Comment by nev-21** [comment]
Hi, There some new about this issue? Why is this closed if it is not fixed yet?

**Comment by pireslopesvinicius** [comment]
Hello, I am facing the same problem, I didn't find a easy way to get around this problem.

I think in the api variables tab it should have a option that says if the variable is nullable after the type of the variable, It would be very much appreciated. Thanks.

**Comment by pireslopesvinicius** [comment]
A simple checkbox, like flutterflow does in other places as well.

**Comment by tiagosilveiransj** [comment]
Same issue here, please reopen.

**Comment by badreal** [comment]
how on earth this feature is not available, many less obvious features are available and not this one ?!!!

**Comment by tiagosilveiransj** [comment]
The same thing happends when you parse data to a datatype, null values are being transformed into empty string, this is a problem, specially when dealing with uuid values.
