### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by erram** [FlutterFlow/flutterflow-issues#2247]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If i use the built in navbar to navigate back and fort from 2 given pages AND i have an additional logic piece like a button that also navigates:
First time it works well.
Second time if i go to the page the button stops navigating

### Expected Behavior

I can navigate

### Steps to Reproduce

https://github.com/FlutterFlow/flutterflow-issues/assets/5526767/974f263c-9da9-4035-8a6f-70514b6c9c78

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40u8nlvKh/nNta1qruUexKiWIsHUQYbLhE1t5BaCosfZT2BLMcec/RVERvYMDiT2NYOVmamWoW08r7uPHTKMYBNSesc7o9zJNcegLdeFinVJShFJWgfnclI5tTJ3640JivvxBDJsheV3wfwUymB+quYAXsJo/1NjICD6/LZO4=

### Context

Well it messe with our functionality.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/5526767/2e7124af-7962-4300-a55a-775e0968d1b5

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @erram - Are you still got this issue ? if not please close the issue.

**Comment by hariprasadms** [comment]
Due to inactivity and no response, I presume the problem has been resolved for you. Thanks
