### ISSUE TITLE
Image not uploading in collection files / Files cannot be saved after image upload in collection 

### ISSUE THREAD

**Issue by aidabejgane** [FlutterFlow/flutterflow-issues#2251]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, 
When I try to add an image to a collection, the image cannot be added, I cannot save the new files in the collection with the image. I'm using property image path for the image.

### Expected Behavior

I should be able to upload an image in the collection files and save it 

### Steps to Reproduce

1. open a files in alltreatments collection
2. upload an image in image path property 
3. save the modified files 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehcr1z41Ipb0E16X+cfowvwMwQWYla+dIoetxc0gbfe/4EZkMYvf4RBFWZ72zaHxEAWCYgkQy7tLNvdrDCfUCPS+ubZxT+btIVxPPbEKnV7KJBc6KSXx7EeZVBW604JirkwpABNdqdCAs7HGmLuiXVT6Cf9qOYwx5e6fDbOY=

### Context

I was trying to add images in my Alltreatments collection

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/156856459/04539303-6b51-4fe9-9891-9a5175aeedd3

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released January 15, 2024 Flutter version is 3.13.7
- Platform: MacBook Pro
- Browser name and version: Chrome Version 120.0.6099.234
- Operating system and version affected: macOS Sonoma version 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @aidabejgane - Thanks for submitting the issue. It seems that the collection you are trying to update does not have write access. Check Firestore rules and storage permissions and update them accordingly. Also, check for any errors in the browser console when you click the button. Please update the issue details with these findings.

If the issue persists, create a blank project, reproduce the issue, and share the project bug report code. Thanks.
Thanks

**Comment by aidabejgane** [comment]
Hi, Thank you for your message. 
I did the following: 
- update the collection permission to everyone
- check any error browser - none was seen. 
I still have the same problem - see video attached in ticket. 
Thank you 
Aida

**Comment by hariprasadms** [comment]
What error you see in the browser console @aidabejgane - Did you try in another project ? Please provide a blank project with issue produced in it ?

**Comment by MaazBinMusa** [comment]
> Hi, Thank you for your message. I did the following:
> 
> * update the collection permission to everyone
> * check any error browser - none was seen.
>   I still have the same problem - see video attached in ticket.
>   Thank you
>   Aida

I fixed it by going to the storage rule in my firebase console and changing write: if false to just write.

**Comment by hariprasadms** [comment]
Hi @aidabejgane, Check storage rules deployment status in Flutter Firebase storage section. Deploy the rule and try again. It should work with no issues.

<img width="1506" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/7cf47cac-98fb-4ad4-bdf3-2a9c83f16a6a">

**Comment by hariprasadms** [comment]
Hi @aidabejgane - Check the storage rules and its deployment status please.

**Comment by aidabejgane** [comment]
Yes it was that! I could upload an image after a few changes. Thank you very much.
