### ISSUE TITLE
Cannot use ListView with infinite scroll and "api call" action

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#2254]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I need ListView to generate children with a component-state-variable (I dont want to use backend-query, to have more control on data vía a comp-state-variable), so I have to get data with "api-call" action, but with this method I lost "infinite scroll" feature for the list.

### Expected Behavior

ListView should have "infinite scroll" option in properties section, and an event raised as effect of "infinite scroll" (maybe called "onPagination" or "onInfiniteScroll") so I can put an "api-call" action on that event.

### Steps to Reproduce

1. Just create a list in a new component
2. create a component state variable (that is a list of json)
3. make an api call "on-initialization" and set the response to the variable
4. use the variable in generate-children section of ListView

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zsnf25NPmMMA7aqNcsJV+T45JjM2beY71+traCotCLbkOpgcf/fOYkRBUsfjYW9feWCKo2oW0aHLuez1JPAnPUisQap/1rVuTwLhcEigRJiqFJWve3R5Bf1Qf1Sc56TYmxMmA7ZfLFY+wU6uBuSQfBHqQJzyCkQ8Da/LZO4=

### Context

I need to do this to have more control on data, cause when using backend-query I can't update a single record that was updated by the user, this is a huge benefit for UX.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d0c89d98-a534-4a80-8582-60e933a177b1/d6934e07-ddd6-41b9-9092-9d5544ac359e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMGM4OWQ5OC1hNTM0LTRhODAtODU4Mi02MGU5MzNhMTc3YjEvZDY5MzRlMDctZGRkNi00MWI5LTkwOTItOWQ1NTQ0YWMzNTllIiwiaWF0IjoxNzA2Mzc2NjA4LCJleHAiOjMzMjc2OTM2NjA4fQ.BjI_aNiJDiwDoUznxBILKXug_V4P4Lt27oxwn7_KgG0)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/261a6721-9c3f-48e3-8ef6-4db184e6e450/52597ed3-f6b9-479f-b4ea-23f1469f029f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNjFhNjcyMS05YzNmLTQ4ZTMtOGVmNi00ZGIxODRlNmU0NTAvNTI1OTdlZDMtZjZiOS00NzlmLWI0ZWEtMjNmMTQ2OWYwMjlmIiwiaWF0IjoxNzA2Mzc2NjA4LCJleHAiOjMzMjc2OTM2NjA4fQ.G4I2n1Z2sPvS08BVdr0OtnOodUgY0g0xY95T6HYxSP0)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: 120.0.6099.225
- Operating system and version affected: win 11
```

**Comment by nev-21** [comment]
Hi, please just want to know if there is any plan to improve the ListView widget, its events or actions related to it.

**Comment by Anyaoha** [comment]
Also add to this issue - 

**Cannot get infinite scroll for list of documents passed via parameter or dynamic generated children **

**Comment by paulperez-dev** [comment]
Hi @nev-21, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!<br><br>@Anyaoha with the suggested change you should be able to handle those scenarios.

**Comment by Anyaoha** [comment]
Thanks @paulperez-dev I’ll await for the infinite scroll on dynamic generation (including through parameters) as well as on query type done on widgets outside list views.

**Comment by nev-21** [comment]
> await for the infinite scroll on dynamic generation (including through parameters) as well as on query type done on widgets outside list views.

Thank you @paulperez-dev we are waiting for these features

**Comment by bdonovan858** [comment]
@paulperez-dev Do you have any updates on when this may be available? Thank you.
