### ISSUE TITLE
generated code does not compile

### ISSUE THREAD

**Issue by Miamoto-Musashi** [FlutterFlow/flutterflow-issues#2255]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

downloaded code from project does not compile from sources with dependency iussue
```bash
❰mac❙~/❱✔≻ flutter pub get                                               Sat Jan 27 19:27:09 2024
Resolving dependencies... (2.2s)
Note: collection is pinned to version 1.18.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_test from sdk depends on collection 1.18.0 and guests depends on collection 1.17.2,
  flutter_test from sdk is forbidden.
So, because guests depends on flutter_test from sdk, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on collection: flutter pub add collection:^1.18.0
```

### Expected Behavior

downloaded code should compile without problem

### Steps to Reproduce

1. flutterflow export-code --project <my-project-id> --dest . --include-assets --token <my-token>
2. enter folder with vscode
3. flutter pub get
4. see the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ehvHlvM91ofpE7c/Ab8FvmSQRIjs/RYInm9V+dAw2G4uqBLMteOj+QHZVOMO/dFY3OlmI8Dg1w++MuPOTGu4XPiisf6I71bVIShXLcGeXb5/SBc3pdUdQDZhPN0+Hzbe33xVRNvdYWFo4wFyqH+68ZA/sO5f6C1UNAcikEJ/IpGDnLTLOXn0Jg1ZSfCvr

### Context

trying yo test a page that use websocket and can do it only on a android device since web version is blocking ws address

### Visual documentation

<img width="1195" alt="Screenshot 2024-01-27 alle 19 40 48" src="https://github.com/FlutterFlow/flutterflow-issues/assets/283196/5c176f07-f624-47d3-ab1f-c3b5505382b2">

### Additional Info

[pubspec.json](https://github.com/FlutterFlow/flutterflow-issues/files/14073391/pubspec.json)

### Environment

```markdown
- FlutterFlow version: 4.1.23
- Platform: MacOS
- Browser name and version: NA
- Operating system and version affected:  MacOs Ventura 13.6.3
```

**Comment by hariprasadms** [comment]
Hi @Miamoto-Musashi -  Are still facing this issue ? I have verified your project downloaded code. All works with no errors.
Whats your flutter and dart versions at you location machine ?

**Comment by Miamoto-Musashi** [comment]
Hi @hariprasadms here my flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.6.3 22G436 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
