### ISSUE TITLE
Secondary action not executed during user account creation in flutterflow

### ISSUE THREAD

**Issue by obisi7** [FlutterFlow/flutterflow-issues#2258]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

why is the second action, navgate to profilePage, after account is created in flutterflow s ignored? No page navigation occurs even though account is succesfully created and user is logged in automatically. I need user to provide fullname, phone number and other pieces of data during sign up and hence my action 2 navigating the user to a profile page. Even when I remove this second action, expecting auto navigate to homepage as defined in the app settings, no navigation occurs.

### Expected Behavior

I expect the second action after account creation to be executed which is to navigate to a profilePage to capture additional user data such as fullname, etc.

### Steps to Reproduce

1. create a blank project
2. create a registration page
3. add email and password fields
4. add a button which when clicked will create a user account in firebase and navigate to a profile page
5. create a profile page with at least one field (fullname) whose data will become the display_name
6. Create 2 actions for the button on the registration page
7. Action 1: auth_create
8. Action 2: navigate to profile page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gksjf34VNssdb1s+BYO9WljkWKWI7a5c0st5Hd0gdCOPrBqQEfOP4ahdVZ9eraVNfM1mimkIG063WvdrpC/BeCyiYc6JHzpYBSDvke2iWWrHQPruSZEFDI/1WIVSz06eC3QknObJeS1pm3F6ICOqXdA7DBOu/Zwh9f6PHaOI= <img width="404" alt="Screenshot 2024-01-27 at 10 09 59 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2617883/4d0cf8ca-f492-445a-8a58-6ba1485187ae">

### Context

Stopped me cold completing my project. Tried multiple times creating blank projects to see if I can get past this nasty bug but no luck. I can't make my app work if the logic won't be executed as desigened. In the MVC model, the C(ontroller) is not working.

### Visual documentation

<img width="404" alt="Screenshot 2024-01-27 at 10 09 59 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2617883/c2aa37c6-8a1a-49ca-8f64-c81fa3ed28e2">

### Additional Info

none

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Mac OS Desktop
- Browser name and version: Chrome  120.0.6
- Operating system and version affected: Mac OS Sonoma 14.2
```

**Comment by hariprasadms** [comment]
Hi @obisi7 - I have verified the steps you provided, and everything seems to work fine on my end. After inspecting your project, I noticed that the Firestore rules status is shown as "not deployed." This might affect the document creation during the account creation/authentication process. Please check the error messages in the browser console when you encounter navigation issues to understand the root cause.

**Comment by obisi7** [comment]
Thanks for the help. You're right, the issue was with not deploying the rules as you pointed out. It all works now.
