### ISSUE TITLE
In the Firestore tab and then the Collections tab the menu you get when selecting a new data type from the drop down after adding a new field won't scroll down when expanding the doc reference option on the MacOS FlutterFlow App.

### ISSUE THREAD

**Issue by third-eye-cyborg** [FlutterFlow/flutterflow-issues#226]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
I expected the menu to be able to scroll down so all of the options are available when adding a data type to a field in the Firestore Collections tab. 

## Current behavior (required)
The menu in the Firestore Collections tab that pops up when you click on adding a new field's data type won't scroll down correctly on the MacOS version of FlutterFlow. 

## To Reproduce (required)

I am not able to access all the options in the menu for adding a data type to a field in the Firestore Collections tab. 

## Screenshots / recordings

https://user-images.githubusercontent.com/71515337/207647898-65721770-b265-4630-ab8a-380f721a7b15.mov

## Your environment

* Version of FlutterFlow used: FlutterFlow v.1.1.24
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Operating system and version (desktop or mobile): MacOS Ventura Version 13.0.1 (desktop) MacBook Air M1 2020 13.3" Display

**Comment by Pepino-GR** [comment]
Hi third-eye-cyborg,

I can reproduce it. It's a bug. Thank you for the information.

**Comment by agreaves** [comment]
Thank you for this bug report! This will now be fixed upon our next release 🙂
