### ISSUE TITLE
Delete button for a icon passed in parameter of a component is missing

### ISSUE THREAD

**Issue by fusionstudioro** [FlutterFlow/flutterflow-issues#2260]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Remove button not shown
[https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx](https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx)

### Expected Behavior

Remove button should be displayed

### Steps to Reproduce

1. Create a component that contains an icon
2. Set up the icon to be added as a component parameter (passed as a variable)
3. Add the component to a page
4. Set up the icon for the component

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz8mAvM5Pj7xH1rXuY+9ViicWMjsgbedJmOxTeCs8JJToPLAUZ8zBM05vZryrY0FiMWaGmnEe1vfqjd/TMcAFHy2dfaJ4yKoBaQ7vQme7VbqnO6rgfW1fI/pQFXa03KSR2RFRANhoV0Fn702MBd+/UhPZJoTHNUcZO/G1KdeK2SrDX1iXc2URm05KZDPz

### Context

[https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx](https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx)

### Visual documentation

[https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx](https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx)

![VajzyscHQUZCvIEiP9M5I](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6d8e8909-5c10-4f1b-82fe-76eeae1ce5e7/88bdebb8-7cde-44ff-800d-4af3b4019e99?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZDhlODkwOS01YzEwLTRmMWItODJmZS03NmVlYWUxY2U1ZTcvODhiZGViYjgtN2NkZS00NGZmLTgwMGQtNGFmM2I0MDE5ZTk5IiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.wL9B5Bd8YJwKMXZ-hc2BmUjNHXQTx9WY2upoYPzThy8)

### Additional Info

![VajzyscHQUZCvIEiP9M5I](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/18f0b143-fcdc-42bd-b943-cfa67c871f8d/e9eec15e-6dfc-4305-ba90-df8759cd1761?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xOGYwYjE0My1mY2RjLTQyYmQtYjk0My1jZmE2N2M4NzFmOGQvZTllZWMxNWUtNmRmYy00MzA1LWJhOTAtZGY4NzU5Y2QxNzYxIiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.maExobNth9X8HZikBORdpnsEA-2XrxocEjPRMRzxJS0)

### Environment

```
- FlutterFlow version: Flutter version is 3.13.7 (FutterFlow v4.1 released January 25, 2024)
- Platform: Windows Web
- Browser name and version: Chrome Version 121.0.6167.85
- Operating system and version affected: windows 10
```

**Comment by hariprasadms** [comment]
Hi @fusionstudioro - Thanks for submitting the issue. 

Dev note - Basically when icon is associated to a comp icon parameter, there is no option to remove selected icon in editor UI editor.

<img width="377" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8fefdf9c-e61d-4230-a6e0-d45344678337">
