### ISSUE TITLE
API response data structure field formatting issue

### ISSUE THREAD

**Issue by alexjordi** [FlutterFlow/flutterflow-issues#2263]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1a01e018-199e-4de4-a1b9-ea9aee7c1ed1/a8ef59ba-dabc-4fcc-af53-c68d9eba53f1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYTAxZTAxOC0xOTllLTRkZTQtYTFiOS1lYTlhZWU3YzFlZDEvYThlZjU5YmEtZGFiYy00ZmNjLWFmNTMtYzY4ZDllYmE1M2YxIiwiaWF0IjoxNzA3MTQxMzM2LCJleHAiOjMzMjc3NzAxMzM2fQ.6YwvLM1G-WJrTKyPZ-jFXtRYIa-WKcOGbI-5EZTfScU)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/05d51009-12ac-46c1-ac20-9cdb57a907aa/41597137-dc0b-44d2-951f-5ec23921f942?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNWQ1MTAwOS0xMmFjLTQ2YzEtYWMyMC05Y2RiNTdhOTA3YWEvNDE1OTcxMzctZGMwYi00NGQyLTk1MWYtNWVjMjM5MjFmOTQyIiwiaWF0IjoxNzA3MTQxMzM2LCJleHAiOjMzMjc3NzAxMzM2fQ.jNuM_OhUXd2bkDqih7T62tL-XKFHJMLAESdZ1MBgHM4)

I have attached 2 images showing the problem with the current behavior. When you have selected the data field, it shows a very long string which then pushes some of your display out of the way. This isn't great, just makes it irritating to use but otherwise manageable.

### Expected Behavior

I guess it should display something else that is shorter or by default cut it off and only have the long form visible when you click into the widget concerned.

### Steps to Reproduce

Easy, just make a widget value dependent of a data structure field from an API call.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xi8rlvI9OrttE+KXiafpVhiMvIjs4arhEiet+b0g1GKnkP5k2e/TET2xaTdPmSn03PWGkrD4e/tXIuebIN/kBAyqYbJR/+bVtVRbwTlKQb4yQCJC7e2tCONpKCFyd5ImrsR5DHONicXA12jquPO7KSizZO4CxOFgkRf21BJjXnXPuQ0SLb3kNh1JWeC/v

### Context

Just trying to make my app and editing with the other widget disappearing is annoying.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ac385632-ff1f-4d07-8e0f-50126e4eaecc/d59b4308-4104-46ff-b573-a7f436ffe667?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYzM4NTYzMi1mZjFmLTRkMDctOGUwZi01MDEyNmU0ZWFlY2MvZDU5YjQzMDgtNDEwNC00NmZmLWI1NzMtYTdmNDM2ZmZlNjY3IiwiaWF0IjoxNzA3MTQxMzM2LCJleHAiOjMzMjc3NzAxMzM2fQ.z8aYqNMSx-a2vhohykMtvEblRYpQU_fxAl3PemxUKMI)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows (latest)
```

**Comment by leighajarett** [comment]
Hi there! We have release the UI builder value so you can relabel fields
