### ISSUE TITLE
Turning on CanvasKit prevents display of uploaded images in published web apps

### ISSUE THREAD

**Issue by RickAtSavveLabs** [FlutterFlow/flutterflow-issues#2264]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In my web app, I allow the user to upload a pic as their profile pic. I can then show this pic on their profile page. This works fine in Test Mode. I then Publish the web app and viewed both in my desktop browser and on my phone. The profile pic is not shown in the published version.

![Screenshot of Safari at Jan 29, 2024 at 7_47_22 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/487730a0-7718-412a-8bc3-2e527ff7eddd/0d63e0c6-ec49-47c4-aa66-1c6bcfbd593c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODc3MzBhMC03NzE4LTQxMmEtOGJjMy0yZTUyN2ZmN2VkZGQvMGQ2M2UwYzYtZWM0OS00N2M0LWFhNjYtMWM2YmNmYmQ1OTNjIiwiaWF0IjoxNzA2ODczNjU4LCJleHAiOjMzMjc3NDMzNjU4fQ.umIDtpFyck0_nJ5UXlhbDt7l4GC9tckFNH8uOQcZDHU)

When CanvasKit is turned off, then the image renders fine both in Test and Published versions.
I also tried turning on the "Deploy with Firebase" option for CORS Proxy for Images and which resulted in a publishing error.

![Screenshot of Safari at Jan 29, 2024 at 10_00_11 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0ffed226-e2e1-4b34-ae8b-158eb7fda6c6/6bdf1246-e753-48aa-b27b-a2b8268d7edf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZmZlZDIyNi1lMmUxLTRiMzQtYWU4Yi0xNThlYjdmZGE2YzYvNmJkZjEyNDYtZTc1My00OGFhLWIyN2ItYTJiODI2OGQ3ZWRmIiwiaWF0IjoxNzA2ODczNjU4LCJleHAiOjMzMjc3NDMzNjU4fQ.7vsbHqP92YLuXAcCHX6vwG1pPHKx7vi8X_57a8tJalE)

![Screenshot of Safari at Jan 29, 2024 at 10_02_53 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6f797d01-33f2-4e0d-bc77-82428676e6ab/b545a6f3-a956-456d-99bc-1236f3370f4c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82Zjc5N2QwMS0zM2YyLTRlMGQtYmM3Ny04MjQyODY3NmU2YWIvYjU0NWE2ZjMtYTk1Ni00NTZkLTk5YmMtMTIzNmYzMzcwZjRjIiwiaWF0IjoxNzA2ODczNjU4LCJleHAiOjMzMjc3NDMzNjU4fQ.CrHwiWg2e9Jugd69LQliFi7Dy2Pj48BhMG5fMoCXK9c)

### Expected Behavior

An image uploaded to Firebase should render correctly both in Test and Published modes

### Steps to Reproduce

 1. Add image widget to a page
 2. Give it the Firebase url for the image to render
 3. Run the app in Test mode and see that the image renders fine
 4. Publish the web app
 5. Run the web app and notice the image still renders fine
 6. In settings, turn CanvasKit ON
 7. Publish the app again
 8. Run the web app, and this time the image does not render and is blank
 9. Back in settings under CanvasKit, set CORS proxy to "Deploy with Firebase"
10. Publish the web app, and you will get a "Web Publish Failed" error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I get an error when I try to generate this code

### Context

I am letting user upload a pic to use as their profile pic

### Visual documentation

![Screenshot of Safari at Jan 29, 2024 at 10_00_11 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2741e7a1-8481-4059-9a90-7361d053690e/4c583d8f-9c43-4028-a3bd-0952648fc983?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNzQxZTdhMS04NDgxLTQwNTktOWE5MC03MzYxZDA1MzY5MGUvNGM1ODNkOGYtOWM0My00MDI4LWEzYmQtMDk1MjY0OGZjOTgzIiwiaWF0IjoxNzA2ODczNjU4LCJleHAiOjMzMjc3NDMzNjU4fQ.tQrQbJVpNMYaGpBvBvASUfohqf_fRtL4y\_-xwyLCYBA)

### Additional Info

Similar but may be different than this issue
[https://github.com/FlutterFlow/flutterflow-issues/issues/2225](https://github.com/FlutterFlow/flutterflow-issues/issues/2225)

### Environment

```
- FlutterFlow version: 4.1
- Platform: MacOS
- Browser name and version: Safari v17.3
- Operating system and version affected: macOS Sonoma 14.3
```

**Comment by hariprasadms** [comment]
Hi, Thanks for posting the issue. I have verified the steps at my end. i noticed the web build failures when canvas kit is and deploy with firebase option is selected. Below is the build error I can see.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/64572f8b-baf8-4577-8a19-125f99bd1edd/6abf6aa3-d227-46a8-a6d5-a831bd596211?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NDU3MmY4Yi1iYWY4LTQ1NzctOGExOS0xMjVmOTliZDFlZGQvNmFiZjZhYTMtZDIyNy00NmE4LWE2ZDUtYTgzMWJkNTk2MjExIiwiaWF0IjoxNzA2ODc0NDUzLCJleHAiOjMzMjc3NDM0NDUzfQ.2YoEIoHLhN6h7pWofwAO7P3ZYb32iXoj68GZGCMfmYg " alt="image.png" width="1407" height="732" />

However, it all works fine and image can display with no issues. This time, canvas kit was on and CORS proxy option was 'None'. Did you try this ? if not, try and let me know how it goes. Thanks

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next update.

**Comment by RickAtSavveLabs** [comment]
Thanks @aemelyanovff! That's great to hear. Take care.
