### ISSUE TITLE
Switch API Base URL does’nt work

### ISSUE THREAD

**Issue by legrec14** [FlutterFlow/flutterflow-issues#2266]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I need to be able to switch between a development and a production API Base URL.

This is a quite common convenience feature and need for API development.

Here is an example, through a swagger generated documentation from an OpenAPI standard description:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e6148765-a583-4679-af6b-2e501c13b990/136066f6-2c71-44cc-9cf4-e32c623279c7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNjE0ODc2NS1hNTgzLTQ2NzktYWY2Yi0yZTUwMWMxM2I5OTAvMTM2MDY2ZjYtMmM3MS00NGNjLTljZjQtZTMyYzYyMzI3OWM3IiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.X8uiTXVzPNl0QoKhBSseodEcXe156GoCuBoFS0PqgVo)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d5486d34-313e-4b59-af56-14da580112b3/b9a90ceb-4907-42a2-874e-55922d6792fb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNTQ4NmQzNC0zMTNlLTRiNTktYWY1Ni0xNGRhNTgwMTEyYjMvYjlhOTBjZWItNDkwNy00MmEyLTg3NGUtNTU5MjJkNjc5MmZiIiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.GadR6Ro6U3y10qT1vsHgr9SKlMtPB5_j8s0BjjXUf8Y)

You can indicate a few servers adresses regarding to OpenAPI specification, so this is a common and desired behaviour.

When I import such an OpenAPI file inside FlutterFlow, it just creates an API group with the first of the many servers URL provided in the file. So it seems there is not a full and correct implementation of the OpenAPI standard specification inside FlutterFlow.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ebefc828-7dd2-4729-8840-d296e28c7c00/2df5df0b-df5f-4459-b7e4-ce1ccfdf94f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYmVmYzgyOC03ZGQyLTQ3MjktODg0MC1kMjk2ZTI4YzdjMDAvMmRmNWRmMGItZGY1Zi00NDU5LWI3ZTQtY2UxY2NmZGY5NGYyIiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.D8-0zS_fn7lfrZ1oI4lTdOBixmsGOJMnV7sW5bPqqe8)

Is there any way that I haven’t seen to be able to rapidly switch from API Base URL inside FlutterFlow ?

A possible trick would be to use a variable value for the API Base URL, as it has been suggested in this other issue:
[https://github.com/FlutterFlow/flutterflow-issues/issues/1818](url)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/17077500-5fec-442f-9b18-c59b4373f35d/2c50174a-268a-4246-b18b-2fb3711ae078?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzA3NzUwMC01ZmVjLTQ0MmYtOWIxOC1jNTliNDM3M2YzNWQvMmM1MDE3NGEtMjY4YS00MjQ2LWIxOGItMmZiMzcxMWFlMDc4IiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.2r0VwFcT6Sa24h42wc2TuUhmVZ8QcmHYxw34k6qIwy8)

That would make the API Base URL easy to change at global level by modifying the default value, or also at single API call level, but it doesn’t work either.

### Expected Behavior

Be able to select between the many API Base URL indicated inside an OpenAPI file.

### Steps to Reproduce

1. Create an OpenAPI file with many servers.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6cda6ca4-f623-45f5-87fe-fd05e19ab94f/ea0fe81c-1563-4cce-993a-dbaa2cde68b6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82Y2RhNmNhNC1mNjIzLTQ1ZjUtODdmZS1mZDA1ZTE5YWI5NGYvZWEwZmU4MWMtMTU2My00Y2NlLTk5M2EtZGJhYTJjZGU2OGI2IiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.0So1GD6zOfyzRCI8b974LVok4lagfIWbTEHQo0ynwb0)

1. Import this file inside FlutterFlow
2. See only the first API Base URL has been created, and there is no way to switch between many API Base URL.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not a bug from the widget tree but from API calls basic feature.

### Context

I cannot easily switch from the production API to the dev API, to try new features and then switching back easily to production API.

### Visual documentation

Generated API group from an OpenAPI file only fetch the first servers URL:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4c831437-ff56-4d2d-8fa8-fd27fab697a7/cf11979c-5b16-4052-b67e-1fd619cee41c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YzgzMTQzNy1mZjU2LTRkMmQtOGZhOC1mZDI3ZmFiNjk3YTcvY2YxMTk3OWMtNWIxNi00MDUyLWI2N2UtMWZkNjE5Y2VlNDFjIiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.vrBIZq5gpEt-oE93w2LBnCUpuqA9rievjb-69Kv24ng)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b8acb731-fd39-4d50-8ac0-66a9ef6bcd19/6acfcad3-4205-4b15-be87-b0f93aab2acf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iOGFjYjczMS1mZDM5LTRkNTAtOGFjMC02NmE5ZWY2YmNkMTkvNmFjZmNhZDMtNDIwNS00YjE1LWJlODctYjBmOTNhYWIyYWNmIiwiaWF0IjoxNzA3MTQxMzM3LCJleHAiOjMzMjc3NzAxMzM3fQ.AoINQ-ahPvoTmgAbgOkIzx5u0p-rBSvTRQh9zNJVhuM)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.1
- Platform: Web browser / local
- Browser name and version: Mozilla Firefox 121.0.1
- Operating system and version affected: N/A
```

**Comment by leighajarett** [comment]
Since this is a feature request, I've added it to our internal request tracking system. Going to close this issue since this is purely for bugs. Thanks for the feedback!
