### ISSUE TITLE
iOS permission messages disappear.

### ISSUE THREAD

**Issue by AnaGriiettnerF** [FlutterFlow/flutterflow-issues#2267]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I submitted my app for approval on the Apple Store, and every time it was rejected with the same reason, stating that the camera and gallery permission messages were not clear enough. However, each time I submitted it with messages within Apple's guidelines. When I opened the project in FlutterFlow, I noticed that the messages were generic. Another colleague and I attempted to submit it, and the same issue occurred. Our app also supports Portuguese and Spanish, and the translations remained correct; however, the English message always remained generic.

### Expected Behavior

The expected behavior is that the English message is not replaced by the generic message.

### Steps to Reproduce

1. Go to the language tab in the settings.
2. Open the iOS permissions messages.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

This error delayed the approval process on the Apple Store by a few days and was only resolved after uploading the version through GitHub.

### Visual documentation

![Captura de tela 2024-01-28 181109](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/564d0dcc-80f9-4e00-bdfc-a054e7f641d1/bbd6309f-8562-404c-baeb-660cdda7e108?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NjRkMGRjYy04MGY5LTRlMDAtYmRmYy1hMDU0ZTdmNjQxZDEvYmJkNjMwOWYtODU2Mi00MDRjLWJhZWItNjYwY2RkYTdlMTA4IiwiaWF0IjoxNzA2ODkyMjg2LCJleHAiOjMzMjc3NDUyMjg2fQ.NYNbPs9zxWwqNEQuK8N-dKO-d1MZYApgwZAGsilI2jc)

![Captura de tela 2024-01-28 181835](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cda8eed2-d181-445f-812b-3be5e0f9c768/1eaea821-6fff-4043-abf3-1f6a5292ebe1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZGE4ZWVkMi1kMTgxLTQ0NWYtODEyYi0zYmU1ZTBmOWM3NjgvMWVhZWE4MjEtNmZmZi00MDQzLWFiZjMtMWY2YTUyOTJlYmUxIiwiaWF0IjoxNzA2ODkyMjg2LCJleHAiOjMzMjc3NDUyMjg2fQ.niO9nKtEsWYy85NDV2wNG_dh6YXCxikSoRsGy92aQGU)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v 4.1 flutter 3.13.7
- Platform: Web
- Browser name and version: Chrome 120.0.6099.225 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11 Home Single Language / 22H2 / 22621.3007
```

**Comment by mrnicon** [comment]
I had the same problem way back. To fix the problem I had to turn of and on the Permission and write the text again to make it written to the info.plist and manifest files. - Need to be fixed.

**Comment by AnaGriiettnerF** [comment]
I did that too, but it didn't work. I even redid the entire language part of the app, and it still didn't work. It always reverts to the generic one.

**Comment by hariprasadms** [comment]
Hi @AnaGriiettnerF -  Could you please provide more specific details about the issue you're facing with iOS messages? For a more accurate investigation, let me know which specific messages on iOS permissons are disappearing, and any additional information about the scenario or conditions under which this occurs.

**Comment by AnaGriiettnerF** [comment]
The issue was noticed in the camera and photo library messages. Every time I or another editor input the message in English 'TruckMator needs to access your camera to allow you to capture and upload images of your vehicle. This helps in identifying the vehicle and personalizing your profile in the app.' when switching out of the language tab, it reverts to the generic message 'Use camera for pictures.' As you can see, the translations in Portuguese and Spanish remain as desired, but the English string consistently reverts to the generic one.

I made a video with a test project showing the bug

https://github.com/FlutterFlow/flutterflow-issues/assets/155084105/65281d4e-d068-43b3-b309-b0f4f41a885f

**Comment by hariprasadms** [comment]
Hi @AnaGriiettnerF Thanks for the details. I can confirm that I can reproduce the bug. Thanks

**Comment by takashiff** [comment]
Hi @AnaGriiettnerF, I apologize for the delayed response. Sometimes, it takes some time for changes to be communicated and saved to our database, so I would suggest waiting a few seconds after making changes before exiting the app or switching tabs. Please let me know if this solves the issue for you. Thanks
