### ISSUE TITLE
Android App Icon with Circle Shape Not Getting Filled

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#2269]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever I deploy an app to Android, the app icon (specifically the android app icon with the circle shape) does not take up the full space. It works on IOS and works on other Android app icon shapes. It only does not work on the circle shape. This is a re-submission of an existing closed ticket ([https://github.com/FlutterFlow/flutterflow-issues/issues/1260](https://github.com/FlutterFlow/flutterflow-issues/issues/1260)). I am opening a new one per FlutterFlow support recommendation.

### Expected Behavior

Launcher icon should fill the circle.

### Steps to Reproduce

Set launcher icon in FF, deploy using Codemagic.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87lx4lgoddA1rrtbcExvCo4H245TL07ttYbZxUjIuPtBJh/fuPObkxWcOG6YHlhHEyYkTsf06HPvez9EvkBC02rfro7+pANag6WRXq8R8SYPKWeQUF5IJ5mJnK536awkxVRAPBYWkIR6ma2H+6UVhbsGZO/Zwh9f6PHaOI=

### Context

Launcher icon doesn't display properly.

### Visual documentation

![IMG_4301](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/54ac7ac1-6a2b-49d9-b5cc-a311068dc327/887e7c5e-88e3-4dbb-87ca-965ca696da5f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NGFjN2FjMS02YTJiLTQ5ZDktYjVjYy1hMzExMDY4ZGMzMjcvODg3ZTdjNWUtODhlMy00ZGJiLTg3Y2EtOTY1Y2E2OTZkYTVmIiwiaWF0IjoxNzA3MTQxMzM1LCJleHAiOjMzMjc3NzAxMzM1fQ.b5AHM5DLzZ07R8iJfcCDwNzme5-QfwiSfjf0iTvhmsI)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: MacOS
- Browser name and version: Chrome latest
- Operating system and version affected: OSX Monterey
```

**Comment by hariprasadms** [comment]
Hi @max-h-silverman - It's the default behavior on the Android platform. To see the icon in a circular shape, you should upload an image that is already circular in shape.

**Comment by max-h-silverman** [comment]
@hariprasadms Won't uploading a circular image cause the iOS launcher icon to not display properly? How can I have both iOS and Android icons display properly while using the one-click deployment?
