### ISSUE TITLE
Failure to deploy for internal testing on Google Play Console

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#227]
## Expected behavior (required)

Deploy for internal testing on google play Console. 

There are four threads on the FF forum on this topic:
https://community.flutterflow.io/c/discuss-and-get-help/firtst-android-deploy
https://community.flutterflow.io/c/discuss-and-get-help/strange-gpstore-deployment-error#comment_wrapper_8310054
https://community.flutterflow.io/c/discuss-and-get-help/displaying-error-when-deploying-to-play-store
https://community.flutterflow.io/c/discuss-and-get-help/codemagic-deploy-output-failed-step-publishing

## Current behavior (required)
Failure to deploy, with the following error message:

Codemagic Deploy Output
Failed Step: Publishing

== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact app-release.apk
Publishing artifact app.apk
Publishing artifact app-release.apk
Publishing artifact app-release.aab
Publishing artifact release_mapping_mapping.txt
Publishing app-release.aab to Google Play
Published app-release.aab to track internal
Google Play failed to upload artefacts. Only releases with status draft may be created on draft app.: {
    "error": {
        "code": 400,
        "message": "Only releases with status draft may be created on draft app.",
        "status": "INVALID_ARGUMENT"
    }
}
Build failed :|
Publishing failed :|
Google Play failed to upload artefacts. Only releases with status draft may be created on draft app.: {
    "error": {
        "code": 400,
        "message": "Only releases with status draft may be created on draft app.",
        "status": "INVALID_ARGUMENT"
    }
}

## To Reproduce (required)

1. Follow this tutorial: https://www.youtube.com/watch?v=z3RbgbVR2fo&t=3s

### Bug Report Code
N/A

## Context (required)
Cannot deploy to Play Store for internal testing. 

## Screenshots / recordings

![Screenshot 1 - failure to deploy](https://user-images.githubusercontent.com/120210391/207693947-1f748ed9-17f5-4a91-b80a-d4d03a476c78.png)
![Screenshot 2 - failure to deploy](https://user-images.githubusercontent.com/120210391/207693996-d49cc85b-51dd-4ec4-97c6-185e443210fa.png)
![Screenshot 3 - failure to deploy](https://user-images.githubusercontent.com/120210391/207694039-cc66602c-22cc-458a-8f8e-0b172726b109.png)

## Your environment
Desktop Windows 11, Chrome, FlutterFlow V. 3.3.4

**Comment by Alexandre-Lemyre** [comment]
I contacted FF support and here is the solution: you need to complete all the information for your app in Google Play Console, including the app description, the featured image, screenshots of your app on mobile and tablets (I used window's snipping tool to take "screenshots" from Flutterflow), the logo, etc. It worked for me. 

https://intercom.help/flutterflow/en/articles/6530615-only-releases-with-status-draft-may-be-created-on-draft-app

**Comment by hariprasadms** [comment]
Thanks. Closing the issue as solution found.
