### ISSUE TITLE
appbar has flutterflow blue progress bar after test is built

### ISSUE THREAD

**Issue by phongyewtong** [FlutterFlow/flutterflow-issues#2272]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

flutterflow blue progress bar should IS there after the app is built

### Expected Behavior

The flutterflow blue progress bar should not be there after the app is built

### Steps to Reproduce

1. Wake up this morning
2. Click on New Session button.
3. Refresh the flutterflow build screen and load again, still there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl+fl4ot1m7RG1YSIKcZWlSgUQ1scTeU7lexsaxAaI+OoE7ALePT7cRZucuqHSn4/AWCagkQ0w62KhtnpF/leFzisRqpnyboIUxDgQjqnRbKvO86BP3d9J/9jIFSY0cGSkBUkBONuS3w53WapNumQb3qCf9qOYwx5e6fDbOY=

### Context

i cant build my layout correctly, its affect the appbar and some other screen are not able to load as well.

### Visual documentation

![Screenshot 2024-01-31 at 4 41 15 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cfdbaa68-fa40-4bb3-8441-a31ad37212be/bfbfb2b9-038d-468c-a2a2-92873bafd592?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZmRiYWE2OC1mYTQwLTRiYjMtODQ0MS1hMzFhZDM3MjEyYmUvYmZiZmIyYjktMDM4ZC00NjhjLWEyYTItOTI4NzNiYWZkNTkyIiwiaWF0IjoxNzA2ODY5NTE3LCJleHAiOjMzMjc3NDI5NTE3fQ.j5hxMBnJSlRZB_CCuMW0t-DI_zbRj5W890L1mG2V1Qo)

### Additional Info

nope

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released January 26, 2024
Flutter version is 3.13.7
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: Big sur 11.7.10
```

**Comment by hariprasadms** [comment]
Hi @phongyewtong - Are you still experiencing the issue? Have you attempted this in different projects? If the problem persists, please set up a new project, reproduce the issue, and share the bug report code for further investigation.

**Comment by phongyewtong** [comment]
yes i still have the problem

**Comment by phongyewtong** [comment]
same issue on new project with just appbar.

ITESz/Hqx89goeZH16qJLflAhQAkKUg4WLg7m9caURM0G7bvPJkyf+r+VGpeOd+CSmw/M1KZklMe0aH7huLXDcYFF0mqaINowaVuawGXbDiQaJilEbuWfUR6EftjN26+0rWRuwhSNslaS14bw2z/cq3qNleeY8aSfxBlZ7vfcPo=

**Comment by hariprasadms** [comment]
Your same project looks fine at my end. See below.

<img width="1509" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/52fafb9e-6338-422a-a77d-17c1f55efa01">

Whats your OS, windows or Mac ?

**Comment by phongyewtong** [comment]
MacBook Pro (Retina, 15-inch, Mid 2014)
2.2 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3
11.7.10 (Big Sur)

**Comment by hariprasadms** [comment]
Thanks for the details. OS details looks fine. Since the issue appears to be unique and unable to reproduce it at my end, it might be specific to the user's environment or setup. It could be related to your browser configurations, network settings, or other factors. 
I would suggest try this in more than one project and see the consistency. If same issue persists in all the projects, contact FlutterFlow support team to get it checked specific to your user account.

Considering wider impact, I can mark the issue as _not a bug_ and _not able to reproduce_.
