### ISSUE TITLE
Letter Spacing Doesnot work in Custom Fonts

### ISSUE THREAD

**Issue by aqib822** [FlutterFlow/flutterflow-issues#2274]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever i insert a custom font the letter spacing prperty doesnot work then

### Expected Behavior

I expect the letterspacing property to work on custom fonts as well

### Steps to Reproduce

Create a page, add container, add a text, change the family to any custom font, and then the letter spacing doesnot work

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ksmAvM9goeFK187ude9anjwWQls7RL8V0u5xaAE8KOvLBIYuP/WkMxdCYMiqY2x2e0Smmk8Ew63tivHhNvA3Gz6bRrU4+M9iTA3LeGehUZOBBpe8W2pQGZ9QIHKM4LWNkyJdItBfL0YN7XGDe+e+TgDtQo+zImdISq/LZO4=

### Context

to get the letter spacing

### Visual documentation

i think no need for that, because its a simple issue to understand

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: macOs and web both
- Browser name and version: google chrome 121.0.6167.85
- Operating system and version affected: macOS Montery
```

**Comment by hariprasadms** [comment]
HI @aqib822 - Thanks for submitting the bug. I can confirm that I can re-produce the issue. Thanks

**Comment by aqib822** [comment]
i am setting it manually but its not working in preview mode
