### ISSUE TITLE
image widget

### ISSUE THREAD

**Issue by santosh81066** [FlutterFlow/flutterflow-issues#2275]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i am placing image widget i had gave an action to select file from desktop i had enable the the show error image on failure i had uploaded image in app assets but i am not able

![error1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e12847e2-1bd1-441f-958a-8e3c375bbf37/f86d5840-6ffd-4951-bea0-c70bf77e42c2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMTI4NDdlMi0xYmQxLTQ0MWYtOTU4YS04ZTNjMzc1YmJmMzcvZjg2ZDU4NDAtNmZmZC00OTUxLWJlYTAtYzcwYmY3N2U0MmMyIiwiaWF0IjoxNzA2NzI2NzM4LCJleHAiOjMzMjc3Mjg2NzM4fQ.M9sTio8Sdjs_fD-gS2UG25Onn-jpU_cbtWle9cYnxXg)

![Screenshot 2024-01-30 022831 PNG](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bb68e374-1fab-4761-8b37-d0d28dce9f95/b19ac57a-cad9-4395-9ff4-f4f9e142223e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYjY4ZTM3NC0xZmFiLTQ3NjEtOGIzNy1kMGQyOGRjZTlmOTUvYjE5YWM1N2EtY2FkOS00Mzk1LTlmZjQtZjRmOWUxNDIyMjNlIiwiaWF0IjoxNzA2NzI2NzM4LCJleHAiOjMzMjc3Mjg2NzM4fQ.g0MdoQHH8-y6LoUAHUYjVYrcYtdhcXr8YkfhBO3vkNo)

to see default place holder image if image is not there

### Expected Behavior

expected result i want default image to be displayed if there is no uploaded image

### Steps to Reproduce

[https://app.flutterflow.io/project/image-test-poglyr?tab=widgetTree&page=HomePage](https://app.flutterflow.io/project/image-test-poglyr?tab=widgetTree&page=HomePage)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8nlz5F2pbwA7qX2Ke9ajiYvQ3J6ar00sNobbxAjIoDoPJkUacj7XxdBZ8viT2NXKEWIoH0ep/T5veLhNPc4NQ6uUbU++M1qSjryez6/aoS2BpOOSHFSL/1mC36+0cGzkBUmOsB2LkIE2DmIFt6+bHbfGJv4Zwh9f6PHaOI=

### Context

i am trying to make registration form for my users in that process i want profile pic to upload

### Visual documentation

![error1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6bed0030-f3e4-4bec-8dcc-d2e2fc61ea56/accece4a-942b-412f-bdb1-bfb4078e5edf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YmVkMDAzMC1mM2U0LTRiZWMtOGRjYy1kMmUyZmM2MWVhNTYvYWNjZWNlNGEtOTQyYi00MTJmLWJkYjEtYmZiNDA3OGU1ZWRmIiwiaWF0IjoxNzA2NzI2NzM4LCJleHAiOjMzMjc3Mjg2NzM4fQ.rptV7Xs2qJDn8Yd3FR2nAiyIZxfM6k2G_f5oKpUChsQ)

![Screenshot 2024-01-30 022831 PNG](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fd959751-00b2-4c2c-aad6-1a399650ef5b/06ed11e8-84a1-46e6-9000-e3bff87514e7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZDk1OTc1MS0wMGIyLTRjMmMtYWFkNi0xYTM5OTY1MGVmNWIvMDZlZDExZTgtODRhMS00NmU2LTkwMDAtZTNiZmY4NzUxNGU3IiwiaWF0IjoxNzA2NzI2NzM4LCJleHAiOjMzMjc3Mjg2NzM4fQ.oz9uNzZghARq-KA8aKDv0BsuupF7-ZedFDMcn1Tg-6s)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:web
- Browser name and version:google chrome
- Operating system and version affected: desktop
```

**Comment by hariprasadms** [comment]
Hi @santosh81066 - Thanks for submitting the issue. I can reproduce the issue. It mostly happens in debug and run mode. In web deployment mode working fine.
