### ISSUE TITLE
checkmark appears on choiceChips on android & iOS emulators/devices

### ISSUE THREAD

**Issue by AmaouiON** [FlutterFlow/flutterflow-issues#2276]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Checkmark appears on active choiceChips on android & iOS emulators/devices (not on web test/run mode), even I tried to make the icon font size 0

### Expected Behavior

have an option to enable/disable the checkmark, or change the icon/color and have the same expected visual style on all platforms

### Steps to Reproduce

1. create a choiceChips
2. add multiple options to it
3. push the project to github OR download the code
4. run the project locally on android and iOS emulators
5. select one or multiple chips

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ok+fluYtPtbxA+KXxbflR/SoRNjM2U4ZN0e5xc00jIrXNGJsIYM+kakhWX8u9T2NMM1v8sH80+tbHuPPuGOQHAy2cfr5Y1bpiFgGXZ3KuV4iNBc2oPX97EtJNDkuVyqujnRFQCNtaSnwt72D3Bee9bHXvJrL6C24kDf6ICN/NnmziAi+6Xn0Jg1ZSfCvr

### Context

* 

### Visual documentation

* 

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released January 25, 2024
- Platform: Android & iOS
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @AmaouiON - The details provided for the issue are not sufficient to fully understand the problem. Could you please set up a blank project where the issue steps are reproduced and share the necessary details? 

If the issue no longer persists, feel free to close the ticket. Thank you.

**Comment by hariprasadms** [comment]
Closed the issue as no further information updated. If issue still persists, please create a new issue with all required details. Thanks
