### ISSUE TITLE
depedencies conflict "geolocator_android"

### ISSUE THREAD

**Issue by isneverdead** [FlutterFlow/flutterflow-issues#2277]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

it started today, when I wanted to build the project, this error was showing up, 

<img width="667" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/27068556/256952f1-b25b-4f09-a1f5-b24663498ed2">

### Expected Behavior

it should be running just fine

### Steps to Reproduce

it just randomly happens when i'm build the project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

```IT4SjMrq05NgoeVG1qrtbcBKhiYvOVwlbZIRlO1AEUsbF7LrO7QtXOj9YlRuOOGhdG4/IWCI8Dgd3NrSuNnqVu4XPiiYc6JxzLhAZzmVbH6XV661BpewZHMmJ/NWGhyHzbSV2BFSFLRuW3gb602mI+nLQXTDNu63OVg0Qvj+LtjXn3uqHSLKXn0Jg1ZSfCvr```

### Context

i can't run my project 

### Visual documentation

<img width="667" alt="Screen Shot 2024-02-01 at 16 00 28" src="https://github.com/FlutterFlow/flutterflow-issues/assets/27068556/bea6109f-b9bc-4220-9023-8947399d8a90">

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: 3.13.7
- Browser name and version: chrome 120.0.6099.234
- Operating system and version affected: Mac os, Monterey
```

**Comment by Mdmuzammil16** [comment]
Getting the same Issue and also not able to create IPA FIle

**Comment by hariprasadms** [comment]
Hi @isneverdead - Add project bug report code please. are you using any third-party packages in custom code ? Add all these details which can help to investigate the propble please.

**Comment by isneverdead** [comment]
> Hi @isneverdead - Add project bug report code please. are you using any third-party packages in custom code ? Add all these details which can help to investigate the propble please.

Hi, @hariprasadms we are not using any third party related to these dependencies, and for the bug report code I just updated it

**Comment by hariprasadms** [comment]
I see this version in pubspec geolocator_android: 4.2.4 which is correct and no error in downloaded code. You try download apk now and let me know how it goes.

**Comment by hariprasadms** [comment]
@isneverdead - Are you still experiencing the issue ? if not please close that issue. Thanks
