### ISSUE TITLE
Unable to Build IPA or APK File neither from flutterflow nor from local 

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#2278]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Getting the Below Error
<img width="882" alt="Screenshot 2024-02-01 at 2 07 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/56119343/44ee97a6-041e-456d-a5ab-1ec86eac1155">

### Expected Behavior

It Should Download IPA & APK Files

### Steps to Reproduce

Click on Download APK or run flutter build ipa command after installing the code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

JpBhaCD69hW91PUy5AZ9dUniqA62JpBhaCD69hW91PUy5AZ9dUniqA62JpBhaCD69hW91PUy5AZ9dUniqA62

### Context

Unable to Build

### Visual documentation

Already Added Images

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @Mdmuzammil16 - What is the project bug report code ? are you using any third-party packages ? did you download the code and compile locally and what error you see ? Add all these details please.

**Comment by Mdmuzammil16** [comment]
I haven't added any of the third-party packages shown in the error image above. i have run this locally and got the same issue shown above in the image

**Comment by hariprasadms** [comment]
Above give project bug report code is invalid ? add a valid one please. You can share project link as well.

**Comment by hariprasadms** [comment]
Right click on widget tree on a page and you can see generate bug report option.

**Comment by hariprasadms** [comment]
Hi, Are you still expiring the issue? If it is fixed please close the issue. Thanks
