### ISSUE TITLE
Map doesn't work

### ISSUE THREAD

**Issue by isneverdead** [FlutterFlow/flutterflow-issues#2279]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The map doesn't move when the latlng is updated

### Expected Behavior

it should move once we insert the new lat long

### Steps to Reproduce

1. create new map,
2. create a button with action to change the map's latlng

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SjMrq05NgoeVG1qrtbcBKhiYvOVwlbZIRlO1AEUsbF7LrO7QtXOj9YlRuOOGhdG4/IWCI8Dgd3NrSuNnqVu4XPiiefLp4zrhiVTrvQjijVralOqrtOXF6BedPJ2mHzbSV2BFSFLRuW3gb602mI+nLQXTDNu63OVg0Qvj+LtjXn3uqHSLKXn0Jg1ZSfCvr

### Context

ii'm making the simplest way to replicate the function, to set the new map position by using pre defined latlng stored in the app state

### Visual documentation

![Screen Shot 2024-02-01 at 19 14 50](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5071aeb1-6dc5-4d31-af03-9ccbfdabf07a/7674c420-95ae-4685-b8eb-3916439ca3fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MDcxYWViMS02ZGM1LTRkMzEtYWYwMy05Y2NiZmRhYmYwN2EvNzY3NGM0MjAtOTVhZS00Njg1LWI4ZWItMzkxNjQzOWNhM2ZlIiwiaWF0IjoxNzA2ODA3MzE1LCJleHAiOjMzMjc3MzY3MzE1fQ.J_b0vj9Jw9rLtCCfysyJKMvvdksuKZT_90FAySeZWKA "=342x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: 3.13.7
- Browser name and version: chrome 120.0.6099.234
- Operating system and version affected: Mac os, Monterey
```

**Comment by hariprasadms** [comment]
I can reproduce the issue where map is not rebuilding when mapped default location is changed through local app state. But no grey page is displayed in my case.

**Comment by isneverdead** [comment]
> I can reproduce the issue where map is not rebuilding when mapped default location is changed through local app state. But no grey page is displayed in my case. 
> 

Yes the main issue is the location are not updated after changing the default location, just leave it aside for the grey screen

**Comment by hariprasadms** [comment]
Hi, There is an additional action is required to move the map to the dynamic locations. Add 'Move Map Center' action. see below. This is not a bug.

<img width="1070" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/f75bdca0-b066-47cd-8e46-386301ef2f56">
