### ISSUE TITLE
Back navigation results in gray screen after deep linking from a push notification

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#228]
Quick summary:

If a page has a back button and we deep link to that page via a push notification upon cold start of the app, back button will lead to a grey screen.

## Expected behavior (required)

App should navigate to root if there is no back history.

## Current behavior (required)

Grey screen.

## To Reproduce (required)

1. Enable deep linking and push notifications.
2. Create a page that has a back navigation button. It MUST be a non-home page. Eg `Home -> Category`
3. Ensure the app is NOT running in the background.
4. Send a push notification that deep links to the `Category` page.
5. Tap on the push notification, it will open the app on `Category` page.
6. On that page, navigate back.

### Bug Report Code

Workaround (via direct patch):

```
--- a/lib/backend/push_notifications/push_notifications_handler.dart
+++ b/lib/backend/push_notifications/push_notifications_handler.dart
@@ -47,23 +47,24 @@ class _PushNotificationsHandlerState extends State<PushNotificationsHandler> {
 
     if (mounted) {
       setState(() => _loading = true);
     }
     try {
       final initialPageName = message.data['initialPageName'] as String;
       final initialParameterData = getInitialParameterData(message.data);
       final pageBuilder = pageBuilderMap[initialPageName];
       if (pageBuilder != null) {
         final page = await pageBuilder(initialParameterData);
-        await Navigator.push(
+        await Navigator.pushAndRemoveUntil(
           context,
           MaterialPageRoute(builder: (context) => page),
+          (r) => false,
         );
       }
     } catch (e) {
       print('Error: $e');
     } finally {
       if (mounted) {
         setState(() => _loading = false);
```

For any back navigation button, we add additional `canPop()` check. This works in combination with the above push handler changes (but does not work without them.)

```
                             onPressed: () async {
                               logFirebaseEvent(
                                   'CATEGORY_PAGE_BackButton_ON_TAP');
-                              context.pop();
+                              if (Navigator.of(context).canPop()) {
+                                context.pop();
+                              } else {
+                                context.goNamed('Checkup');
+                              }
                             },
```

## Context (required)

Deep linking into any pages that have back navigation is impossible as it will crash the app on some customers that do not have it running in the background.

## Your environment

* Version of FlutterFlow used: 3.3.5
* Platform (e.g. Web, MacOS Desktop): iOS
* Browser name and version: N/A
* Operating system and version (desktop or mobile): 16.1.1

**Comment by isegal** [comment]
Update: Apparently mixing GoRouter with Navigator for navigation is unreliable. In the above workaround I had problems when trying to deep link into an app that has been running in the background (the opposite problem).

The following works better as it uses purely GoRouter:

```
--- a/lib/backend/push_notifications/push_notifications_handler.dart
+++ b/lib/backend/push_notifications/push_notifications_handler.dart
@@ -44,28 +44,21 @@ class _PushNotificationsHandlerState extends State<PushNotificationsHandler> {
       return;
     }
     _handledMessageIds.add(message.messageId);
 
     if (mounted) {
       setState(() => _loading = true);
     }
     try {
       final initialPageName = message.data['initialPageName'] as String;
       final initialParameterData = getInitialParameterData(message.data);
-      final pageBuilder = pageBuilderMap[initialPageName];
-      if (pageBuilder != null) {
-        final page = await pageBuilder(initialParameterData);
-        await Navigator.push(
-          context,
-          MaterialPageRoute(builder: (context) => page),
-        );
-      }
+      context.goNamed(initialPageName, queryParams: initialParameterData);
     } catch (e) {
       print('Error: $e');
     } finally {
       if (mounted) {
         setState(() => _loading = false);
       }
     }
   }
 
   @override
@@ -140,24 +133,25 @@ final pageBuilderMap = <String, Future<Widget> Function(Map<String, dynamic>)>{
   'RedeemCongratsPage': (data) async => RedeemCongratsPageWidget(
         title: getParameter(data, 'title'),
         body: getParameter(data, 'body'),
       ),
   'DeleteAccountSuccess': (data) async => DeleteAccountSuccessWidget(),
 };
 
 bool hasMatchingParameters(Map<String, dynamic> data, Set<String> params) =>
     params.any((param) => getParameter(data, param) != null);
 
-Map<String, dynamic> getInitialParameterData(Map<String, dynamic> data) {
+Map<String, String> getInitialParameterData(Map<String, dynamic> data) {
   try {
     final parameterDataStr = data['parameterData'];
     if (parameterDataStr == null ||
         parameterDataStr is! String ||
         parameterDataStr.isEmpty) {
       return {};
     }
-    return jsonDecode(parameterDataStr) as Map<String, dynamic>;
+    final decoded = jsonDecode(parameterDataStr) as Map<String, dynamic>;
+    return decoded.map((key, value) => MapEntry(key, value.toString()));
   } catch (e) {
     print('Error parsing parameter data: $e');
     return {};
   }
 }
```

Note: PageBuilder is no longer necessary, but the way parameter data deserialized is not ideal. Since I do not have access to code generator I had to do it this simple way but there may be edge-cases with deserialization.

**Comment by bulgariamitko** [comment]
I am not sure if this is feature request, but if it result in grey screen then this is a bug.

**Comment by thruthesky** [comment]
I experienced the same issue. Hope this will be fixed soon.

**Comment by thruthesky** [comment]
Ah, by the way, I took a video on how it produces error. Actually I was about to create the same issue and then I found out that this issue already exists.

https://user-images.githubusercontent.com/5080329/211575395-8c29ea08-9b86-4882-b66e-99ad9e16efcc.mp4

**Comment by agreaves** [comment]
I believe this issue has been fixed, please let me know otherwise!
