### ISSUE TITLE
Capitalization in textfield does not work in test mode and in web publishing

### ISSUE THREAD

**Issue by alissonbragarocha** [FlutterFlow/flutterflow-issues#2281]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Capitalization parameter set in Characters does not work in Test Mode nor in Web Publishing

### Expected Behavior

The Capitalization parameter set in Characters should always put the text in upper case, even in Test Mode and Web Publishing

### Steps to Reproduce

Add a Textfield
Change the Capitalization parameter to Characters
run Test Mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx892pbxA0JfUaO1vgQMwHVgjbJ0vpe5+dwsjCeOqPIkxP8/4RFFCWOqHTXx6E2KLoGYG08LQi+DLDO0EJT6aQap5+KlhUxDvQXGXbpjTOriWS2pSP8VQJ2Kx58KJnRB5JuhodEIe2GauIOSQb3qCf9qOYwx5e6fDbOY=

### Context

I need all texts added to the textfield to be displayed in uppercase.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c6224b8a-ec2a-438c-b15e-042f556c9836/67514d12-0a81-443a-93c6-8e1b3b8cb45a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNjIyNGI4YS1lYzJhLTQzOGMtYjE1ZS0wNDJmNTU2Yzk4MzYvNjc1MTRkMTItMGE4MS00NDNhLTkzYzYtOGUxYjNiOGNiNDVhIiwiaWF0IjoxNzA2ODY3OTgwLCJleHAiOjMzMjc3NDI3OTgwfQ.1IR27-r7DP63lwyJVFE11OYrVpEXA9QYCC2p89HqDTI)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 121.0.6167.86
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @alissonbragarocha - Thanks for posting the issue. I can reproduce the issue. 

Dev note - This issue primarily occurs in Debug, Run, local run web mode and FF Web deployment modes. However, it works correctly on both iOS and Android real devices and emulators.

**Comment by aemelyanovff** [comment]
I think there's misunderstanding about what Capitalization does. It doesn't automatically capitalize any characters - it just, quoting [Flutter documentation](https://api.flutter.dev/flutter/material/TextField/textCapitalization.html), configures how the platform keyboard will select an uppercase or lowercase keyboard. 

So it only works on mobile devices (including web publishing) but has no effect on desktops/laptops. I'll update text in FlutterFlow to make it clearer.

If you want to automatically capitalize text in text fields on all devices, then I don't think it's supported yet. Please consider creating a feature request.
