### ISSUE TITLE
Selecting an autocomplete option doesn't trigger onChange

### ISSUE THREAD

**Issue by Mar-Koe** [FlutterFlow/flutterflow-issues#2283]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have set up a simple search as shown in the Docs and the YouTube tutorial, but whenever I select an autocomplete suggestion, nothing happens in terms of the search.
The selected value gets set in the text field, but it seems that onChanged is not executed.

### Expected Behavior

I expect onChanged to be triggered when I select an autocomplete suggestion.

### Steps to Reproduce

1. Setup basic simple search with autocompletion
2. Select a suggested autocompletion for the search

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfj8nf+ot2sdta1YSJLMJGlmEWHH0cTLkvjuphcz8YGIztBJh/d877bRJtQt/kY0NhHGCgnj4HzPTTvfGeO/ldHxaCGro++c5ycw3zQXq8R6XTELiBPWtBBftUf0CuyJ27oRYkJbZvSVot12aMfOm+fADZJ5+/Zwh9f6PHaOI=

### Context

The simple search does not work as expected - autocompletion is useless with this behavior.

### Visual documentation

It might be very easy to reproduce, no visual documentation needed.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Chrome 121.0.6167.87 (Official Build) (64-bit)
- Operating system and version affected: Web, Android
```

**Comment by hariprasadms** [comment]
Hi @Mar-Koe - Thanks for submitting the issue. I have verified the steps and auto complete feature. It is working fine as expected. Below is the widget property you should choose to select the auto selected value.

<img width="693" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d50f64fa-bf73-46f6-a4cb-532a444ba867">

Below option should be enabled to see the changes when text value changed in text field. 

<img width="1025" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/af4139b4-cb37-4524-876a-4e4393b3495c">

If you believe you're referring to a different issue, please set up a blank project with the issue reproduced in it. This will assist in investigating the problem. Thank you.
