### ISSUE TITLE
Routing added disappears when I leave the project

### ISSUE THREAD

**Issue by BryanFlywheel** [FlutterFlow/flutterflow-issues#2285]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

(This issue has happened since the update of FlutterFlow today) 
After making changes to the page routes, I save the project, I leave the project and I access the project again and the changes I made have been reverted.

### Expected Behavior

The changes made to the page routes should be saved after saving the project, no matter if I leave the project and come back to it.

### Steps to Reproduce

Create a new project.
Add deep linking.
Add pages with routes that start with a parameter (:color as an example).
Save the project.
(FlutterFlow update from today occurs)
I change the routes for each of the pages that I have to include /bry before a parameter.
I save the changes.
I leave the project and go back to the Flutterflow Dashboard.
I access the project again and the changes I made have been reverted.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grsdG0KXqacFvryQ4JlA8a5Ir0spBZywgfZzzBLN/fPfQP01VOO6qS1FcMWGMp14D0MnFjuz9M/EoPRyYRrpDybgNVQzvQmCjRJOTF7qOPndCRORUfEC50LbQsyV+HMluS3gM7V6IOd68bHLsHZjjOmo8Sq/LZO4=

### Context

Everytime I access the project errors would appear regarding the way the routing I had previously does not work properly with FlutterFlow any more.
I am trying to have a stable version of the project at all times, that does not revert to a previous version on its own.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150449751/0ccbb22b-9982-48bd-9b3c-1d503c1174da)

### Environment

```markdown
- FlutterFlow version: v4.1 released February 1, 2024
- Platform: Web
- Browser name and version: Chrome Version 121.0.6167.87
- Operating system and version affected: Windows 11
```

**Comment by BryanFlywheel** [comment]
Saving a version of the app when the changes are made and then reverting to said changes seems to help with the issue.
However this is just a workaround and should not be the intended way of using a project.

**Comment by agreaves** [comment]
Hi @BryanFlywheel, thanks for the bug report! We've identified the bug and it will be resolved shortly!
