### ISSUE TITLE
Bug on filter on Generating filter from variable

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#2288]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've an old page that working fine but last FF show a wrong error !
When i try to create a new page with the new Datatable widget i can't do same filter because this wrong validation!
To confirm this i pushed code to my git repo, do the same filter of old page and it works!

[https://github.com/FlutterFlow/flutterflow-issues/assets/1261851/c91b3550-d940-46a8-bc3a-589e3f32861a](https://github.com/FlutterFlow/flutterflow-issues/assets/1261851/c91b3550-d940-46a8-bc3a-589e3f32861a)

### Expected Behavior

I'm that filters works fine !
this code is correct in my case!

```
                          final bookingsByDate2 =
                              BookingsByDateCall.bookingsByDate(
                                    reportPagev3BookingsByDateResponse.jsonBody,
                                  )
                                      ?.where((e) =>
                                          getJsonField(
                                            e,
                                            r'''$.company_id''',
                                          ) ==
                                          _model.selectedCompanyID)
                                      .toList()
                                      ?.toList() ??
                                  [];
```

### Steps to Reproduce

Looking my project you can see ReportPage v2 working fine also if validation inside filter is not
Look also that main project validation is ok

ReportPagev3 is a cloned with new DataTable but i can't set the right filter because this bug
Changing directly on code it works !

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs8JIj2OpkAWvTBTFFWXL3jTEFXe1mkgXwy1vfqj87lKMArPQ+aG4Q6zbpyaT3zVnKmb8mpBpGNfW1QFp9hf2Ky1p2zpSRBBOteR0Ihw2GIIvDLVhXaJpO3CzEnDfKlKdeK2SrDX1iXc2URm05KZDPz

### Context

I simply want to filter the records based on the SelectedCompanyID

### Visual documentation

just added on previous field

### Additional Info

![Screenshot 2024-02-02 alle 08 48 44](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ce0885d4-c858-406d-bccd-75851427de37/134746a7-c55b-466b-9118-bdc54cdfec80?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZTA4ODVkNC1jODU4LTQwNmQtYmNjZC03NTg1MTQyN2RlMzcvMTM0NzQ2YTctYzU1Yi00NjZiLTkxMTgtYmRjNTRjZGZlYzgwIiwiaWF0IjoxNzA2ODY5OTY0LCJleHAiOjMzMjc3NDI5OTY0fQ.lICpTR-iXuYx_6Y4I4gk_Lp7iSwbwyU4BbgKZcAVrKU "=352x")

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Android, iOS
- Browser name and version: Chrome and also your Chrome App
- Operating system and version affected: MacOS Sonoma 14.3
```

**Comment by blondie63** [comment]
Because i need to release my app i've created a new version V19 and you can find page referred to Bug Report Code on V18
Anyway i've discovered a workaround you can see in V19
There's a BIG bug on this FF about extracting data using json path and data type conversion !!!!
In my case i need to extract a company_id that logically is an integer but FF consider it a Json value, so i can't compare with a Page State Variable that is an Integer
FF need an automatic data type conversion or a built in function to convert string to int or viceversa!
This is my opinion

**Comment by takashiff** [comment]
Hi @blondie63, thank you for the bug report. Unfortunately, we currently do not have a way to explicitly determine what data type a JSON field is. As such, to err on the side of safety, we have added this update in place to prevent potentially buggy code that may show up without errors. I will mark this as a feature improvement so that this may be considered in the future. Thank you for your patience and continued support.
