### ISSUE TITLE
Passing variables to API group headers or URL does not work

### ISSUE THREAD

**Issue by WiltAdmin** [FlutterFlow/flutterflow-issues#229]
## Expected behavior (required)
Passing variables to API group, both header and URL, through brackets. 

## Current behavior (required)
It only works when using the "Respons and test" function in the API call editor. But not in either test mode, or when you run the app. 

## To Reproduce (required)
1. Create a API group with a header that uses a variable in in brackets. For example "Token: [AuthToken]". 
2. Create a call within the group that has the "AuthToken" as a variable. 
3. Bind something from the respons to a element on the screen. And it will always be "null", even though the "Respons and test" seemed fine. 

Using variables in url's on API groups seems to have the same issue.  
1. Create a API group and just set the url as a variable. For example: [appBaseUrl]
2. Create a call within the group that has "appBaseUrl" as a variable. 
3. Bind something from the respons to a element on the screen. And it will always be "null", even though the "Respons and test" seemed fine. 

## Context (required)
I wanted to have authToken on group level, so I don't have to add it to each call. And the base url would help, since the app is going to be duplicated, and use different base url's. 

## Screenshots / recordings

**API group settings:** 

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/118193242/207782529-c38e8abc-097b-40f7-a71d-b3ae87de4e23.png">

**Variables on a call that should pass to the headers set in the API group:**
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/118193242/207782801-4f020ee2-2f3e-4977-a872-a30b8d0c0610.png">

**Works in respons and test:**
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/118193242/207783211-7ef8f12c-831c-4550-ba60-15c66c50121c.png">

I also have a recording of the issue that I sent in the chat to David, and he asked me to post it here. I see now that there is some sensitive information in the recording since this is a client build, so I wont post it here. But let me know if you need it, and I'll send it to you. Espen@wilt.no

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Sidekick 106.33.1.28263
* Operating system and version (desktop or mobile): macOS Ventura 13.1

**Comment by aemelyanovff** [comment]
Thanks for your contribution.

We are planning to solve it by adding API Group Variables. We'll track it internally as a feature request.

**Comment by cja-github** [comment]
> Thanks for your contribution.
> 
> We are planning to solve it by adding API Group Variables. We'll track it internally as a feature request.

Hi, please can you say when you will add this? I have about ten API headers that I have to set in each request and it's a pain at the moment because I have to specify them all each time I call the request
