### ISSUE TITLE
Routing - Error of pages both have routes that start with ':'. Only one page can have a route that starts with ':'.

### ISSUE THREAD

**Issue by eddiebrasil** [FlutterFlow/flutterflow-issues#2290]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm having this error
Workshop_Detail and Event_Detail pages both have routes that start with ':'. Only one page can have a route that starts with ':'.

### Expected Behavior

No error was happening before 01/01/2024. FF team tried to fix an issue in URLs that did not impact me at all. The changes you guys are suggesting will impact my app in the terms of google and shortlinks URL. And it was not informed before.

My slugs are contructed as.

One page is like this: :slugCity/blocos/:slugBloco
The other is like this: :slugCity/workshops/:slugWorkshop

### Steps to Reproduce

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4a65810c-81bb-4c50-9c93-dc6c6e22761f/475d2d10-cf75-4803-a7a7-527d01c26871?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YTY1ODEwYy04MWJiLTRjNTAtOWM5My1kYzZjNmUyMjc2MWYvNDc1ZDJkMTAtY2Y3NS00ODAzLWE3YTctNTI3ZDAxYzI2ODcxIiwiaWF0IjoxNzA2ODkyMzY0LCJleHAiOjMzMjc3NDUyMzY0fQ.xTYMe_v0UZy_9zbgRjAH5o5kPKSfr_oF9fZ4K3Ah9fc)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn1sJVOxcBE7a6Jbu9ajSQvNjM5a+Yr0cpBZywgfZzzBLN/fPfQPxdVZ+HiSnxcO02cp14Eps7ohoXyUsYrOT6Zfptx1c1+chbweF+QR7GTF7WWVnx6TMpQCkid5LSnuwp7LshodVo92melfvDKFz/aCb22C2owSq/LZO4=

### Context

IT4olsn1sJVOxcBE7a6Jbu9ajSQvNjM5a+Yr0cpBZywgfZzzBLN/fPfQPxdVZ+HiSnxcO02cp14d0vDFj4TTV/dcPRSbQLZh+bpIEBXKWTihVq2TF7WWVnx6TMpQCkid5LSnuwp7LshodVo92melfvDKFz/aCb22C2owSq/LZO4=

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c41d0700-08c4-45ba-9f4a-c26d4fb9fee5/0c51f70c-396c-45fc-b8a6-a111724cd064?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNDFkMDcwMC0wOGM0LTQ1YmEtOWY0YS1jMjZkNGZiOWZlZTUvMGM1MWY3MGMtMzk2Yy00NWZjLWI4YTYtYTExMTcyNGNkMDY0IiwiaWF0IjoxNzA2ODkyMzY0LCJleHAiOjMzMjc3NDUyMzY0fQ.oAr9zpcg1rcbh8nSd4SlTyvOcUOxWKrySifp_2Zi5qw)

### Additional Info

* 

### Environment

```markdown
- FlutterFlow version: Last
- Platform: Editor
- Browser name and version: Chrome
- Operating system and version affected: Windowws
```

**Comment by eddiebrasil** [comment]
@hariprasadms  @agreaves can you take a look at this one, pls? The changes you guys made yesterday in FF impacted my APP. I need to publish fixes but I can't because of an error that is not actually an error. If I make changes on my side, that would mean make a nonsense change, have really ugly URL structure, changes in Google SEO, changes in more than 2 thousand Shortlinks. My website is online and I expect to launch the apps tomorrow.

**Comment by AnaGriiettnerF** [comment]
This happened to me when I made a copy of a page, and the route remained the same. I deleted the route from one of the pages, and it worked.

**Comment by hariprasadms** [comment]
Hi @eddiebrasil Thank you for submitting the issue. I have reviewed your project and the specific pages you mentioned. Upon removing the ':' symbol, I observed that the error disappeared. Please remove the symbol and confirm if the issue is resolved on your end as well. Let me know the result. Thanks

**Comment by eddiebrasil** [comment]
@hariprasadms  I cant remove that. Its a parameter where it sends the city name. its a dinamic value,

**Comment by agreaves** [comment]
@eddiebrasil This has been temporarily downgraded to a **warning** for now so you should still be able to deploy, but I'm continuing to investigate as this practice is generally not best practice and can lead to unexpected results.

Make sure to refresh FF for now!

**Comment by eddiebrasil** [comment]
@agreaves thank you!!!

Look into it carefully, please. Websites related to guides are pretty normal to have the location (city or country)danamically first in URL.

If you guys come back with this, I will have to create a page for each city. It will be a pain when I have 8, 10 cities. Probably will impact more users i think.

https://www.timeout.com/newyork/things-to-do/city-guide
https://www.timeout.com/los-angeles/things-to-do/february-events-calendar

https://www.lonelyplanet.com/sweden/stockholm/gamla-stan/attractions/kungliga-slottet/a/poi-sig/406802/1341998
https://www.lonelyplanet.com/india/uttar-pradesh/agra/attractions/taj-mahal/a/poi-sig/449189/356509

**Comment by agreaves** [comment]
Great, after some investigation, I agree! It looks like this is acceptable so long as there is another "subpath" in the URL.

So for example, having two routes like:

Page 1: `/:cities`
Page 2: `/:countries`

is not acceptable, but

Page 1: `:cities/activities`
Page 2: `:countries/cities`

is acceptable.

This will be reflected in the next deployment! Since it's already just a warning hopefully that's good enough for now.

**Comment by eddiebrasil** [comment]
@agreaves Nice! Thank you!
