### ISSUE TITLE
Fonts/texts visible in builder view but not in test or deployed mode

### ISSUE THREAD

**Issue by sjuanandres0** [FlutterFlow/flutterflow-issues#2291]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I see the font and text when I am in the builder page [https://app.flutterflow.io/project/capataz](https://app.flutterflow.io/project/capataz) but when I run the test (including instant reload) and I publish the app is always showing without text. I can see everything else such as: icons, buttons, rows, cols, etc. It's just that the text is not displaying.

I also tried to create new pages from templates and the issue persist.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/623556c0-060b-4b7e-a60c-bc59e8bb8bd6/a494a192-8059-41c3-b7c5-b2d4349a7cdc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MjM1NTZjMC0wNjBiLTRiN2UtYTYwYy1iYzU5ZThiYjhiZDYvYTQ5NGExOTItODA1OS00MWMzLWI3YzUtYjJkNDM0OWE3Y2RjIiwiaWF0IjoxNzA3MTQyOTY1LCJleHAiOjMzMjc3NzAyOTY1fQ.Ntx8Zw6lSBCqzqkjF9ZzAppag6o7X9jDPSolEW-vFQE)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f1071616-352e-4c0c-b70c-53f705e9fd66/c885a88b-c895-417f-88b1-8af6a709ad31?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMTA3MTYxNi0zNTJlLTRjMGMtYjcwYy01M2Y3MDVlOWZkNjYvYzg4NWE4OGItYzg5NS00MTdmLTg4YjEtOGFmNmE3MDlhZDMxIiwiaWF0IjoxNzA3MTQyOTY1LCJleHAiOjMzMjc3NzAyOTY1fQ.1ENqr3DwuwTXzuo3KZIzQ4g6Lv9rV32Qm6O9gjaIjkM)

### Expected Behavior

I expect to see the text in the final application

### Steps to Reproduce

1. Run Test
2. Publish

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlfLqy5dIscsG+Kn+cO4xnjgQI0MdXOczitVEew4bCIj4E4k+fuDeSBdvYOazaHNiH1qZ+XsEp9mLk/zXJvArCy2AfLY4+KhUYRPPbEylMZCVEoeOSEFSAZ5UGXaC16aRrSJ+OtduV3Aj7V+EBuesbz6Cf9qOYwx5e6fDbOY=

### Context

It's critical for the app, without it, nothing makes sense

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/623aec1f-0407-42e9-9dd7-c83fdea5d089/fb56184c-fee3-43dc-9cc9-f9ed44cb0613?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MjNhZWMxZi0wNDA3LTQyZTktOWRkNy1jODNmZGVhNWQwODkvZmI1NjE4NGMtZmVlMy00M2RjLTljYzktZjllZDQ0Y2IwNjEzIiwiaWF0IjoxNzA3MTQyOTY1LCJleHAiOjMzMjc3NzAyOTY1fQ.-UVEf5cJ27zR5vhlkbK7RaKakkFjce2aqrjVCo6hMRk)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdce79dd-eda6-472c-90e9-cdc5f8b1222f/c233e88f-d12d-454a-ac7c-eb5803894a88?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGNlNzlkZC1lZGE2LTQ3MmMtOTBlOS1jZGM1ZjhiMTIyMmYvYzIzM2U4OGYtZDEyZC00NTRhLWFjN2MtZWI1ODAzODk0YTg4IiwiaWF0IjoxNzA3MTQyOTY1LCJleHAiOjMzMjc3NzAyOTY1fQ.7MFvhAjkc7-NcgOaLcq84HiIN4_qbURJNL7fFaDpI5U)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: All
- Browser name and version: Chrome / Brave
- Operating system and version affected: Windows 11 pro
```

**Comment by hariprasadms** [comment]
Hi @sjuanandres0 - Thanks for reporting the issue. It appears to be related to the language settings. Please check if the language setting has translations configured for all selected languages. I noticed that English is empty in your project. There no option to choose language in the deployed app page. Fix these things and it should work fine.

**Comment by sjuanandres0** [comment]
Hi @hariprasadms, that worked! Thanks a lot!
