### ISSUE TITLE
The wrap widget and visibility condition

### ISSUE THREAD

**Issue by VaidasSa** [FlutterFlow/flutterflow-issues#2292]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The container layout in the wrap widget appears well-arranged. However, when a visibility condition is added to a container, the layout gets disrupted, and some containers seem to have extra margins.
This behavior is not observed in design mode; it only becomes apparent during testing or after deployment.

### Expected Behavior

The addition of a visibility condition should not alter the layout design.

### Steps to Reproduce

1. Create ListView
2. Then Wrap widget
3. Then Container.
4. Create a Query collection for Wrap
5. Add Visibility condition for Container, for instance "List Contains Item == true.
6. Run Test mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khfHlw892obxZ7qXxbe1Kp2IQNkR/TL03pu0bFEggGLbrBIYMaePRbkhtUsPidAl5KEWLnT8Jwt7Wj+zDKcYoNQSsRoh7/qpMbQ2UUlq/aoSKEKjoPnJRNJtXI2Ks38O4kAknKtNfSVo83Du2LvPKXjPfQeb7Zwh9f6PHaOI=

### Context

Design looks ugly and therefore the application cannot be published.

### Visual documentation

![FF wrap widget](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bd582abb-d698-4d61-b55d-4026e668a426/c22f62cd-f988-4058-9560-baf5dbf67256?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZDU4MmFiYi1kNjk4LTRkNjEtYjU1ZC00MDI2ZTY2OGE0MjYvYzIyZjYyY2QtZjk4OC00MDU4LTk1NjAtYmFmNWRiZjY3MjU2IiwiaWF0IjoxNzA2OTc2MzI2LCJleHAiOjMzMjc3NTM2MzI2fQ.ckPzhYl2_RevLuZYUCVhVII1l1eaoQRJI3xn\_-DbkJc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: V4.1, Flutter 3.13.7
- Platform: web, Android
- Browser name and version: Chrome, 120.0.6099.225
- Operating system and version affected: Win11
```

**Comment by VaidasSa** [comment]
@leighajarett Any news about this bug?

**Comment by hariprasadms** [comment]
Hey @VaidasSa - The issues is with development team now and will be addressed according to its priority. Issue status will be updated here.

**Comment by takashiff** [comment]
Hi @VaidasSa, I apologize for the delayed response. I took a look at your project, and it looks like the rendering issue has been resolved. I just wanted to confirm whether you are still experiencing this issue. Thanks

**Comment by VaidasSa** [comment]
Hi @takashiff I ran a "Test mode" and the rendering issue persisted.
![issue](https://github.com/FlutterFlow/flutterflow-issues/assets/158614140/cfac691d-1073-4ad6-9614-3c6bf9f6695c)

**Comment by takashiff** [comment]
Hi @VaidasSa, thanks for the quick response. I was taking a look at your project, and it looks like the rendering on the `search` page appears to be working without issue. I've done some testing myself, and I'm currently still unable to reproduce the bug even after following the steps you have described above. Is there any difference between the two pages that may provide some insight into the root cause of this issue? Thanks for your cooperation.

<img width="665" alt="Screenshot 2024-03-19 at 3 23 09 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134453477/819fbf20-5488-4a69-a855-8fd95ef9e9fc">

**Comment by VaidasSa** [comment]
Hi @takashiff The "Search" page looks ok. The problem is still in the pages under TabBar.
You can login using https://sebtember.app, then find some users, click follow, then back to your profile / Following.
This is mine:
![following](https://github.com/FlutterFlow/flutterflow-issues/assets/158614140/f70bc59c-b788-4822-8633-cd607e124bae)

**Comment by VaidasSa** [comment]
@takashiff any news regarding this bug?

**Comment by takashiff** [comment]
Hi @VaidasSa, apologies for the delayed response. It has been taking a bit longer than intended to find the root cause of the issue. Just want to let you know that we are still working on this. Thanks

**Comment by VaidasSa** [comment]
@takashiff please, update the status.

**Comment by duEuler** [comment]
Cursor Reset Issue During 'Wrap Widget' Operation in Application Interface

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36971433/61d41f0b-0075-400a-a249-4c18e7a0ab45)

When I attempt to use the "Wrap widget" feature by right-clicking, I encounter a recurring issue: the cursor automatically moves to the start of the page. This behavior prevents the wrap operation from being successfully completed on the first try. Often, I need to repeat the process two or three times for it to work. This issue occurs both in the visual interface and other parts of the application.

**Comment by duEuler** [comment]
> Oi@takashiffA página "Pesquisar" parece boa. O problema ainda está nas páginas do TabBar. Você pode fazer login usando https://sebtember.app , encontrar alguns usuários, clicar em seguir e voltar ao seu perfil/Seguindo. Isso é meu: ![seguindo](https://private-user-images.githubusercontent.com/158614140/314554646-f70bc59c-b788-4822-8633-cd607e124bae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjgxMjksIm5iZiI6MTcxNDg2NzgyOSwicGF0aCI6Ii8xNTg2MTQxNDAvMzE0NTU0NjQ2LWY3MGJjNTljLWI3ODgtNDgyMi04NjMzLWNkNjA3ZTEyNGJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMDEwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWFlZjFhOWI3NDBjNGZiZTFjODkxMWMyYzdiNTYwYWRkNWFkYmZkNjg0NDkzODliYTkxYzkxYzc3ZGQ5ZDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F55IXa_jUEOiar0WoFoZe5s37LyEqz5xOh8pOGU_sOs)

Place your component, if applicable, into a container and remove all paddings, applying 'infinity' to them. The parent container should not have any padding, and you need to set both height and width. In the Wrap, configure the vertical and horizontal spacing; this works perfectly.

**Comment by VaidasSa** [comment]
@duEuler thanks for your advice. However, it did not help. Please, check the changes I did.
![Ekrano kopija 2024-05-06 140519](https://github.com/FlutterFlow/flutterflow-issues/assets/158614140/597b84d0-a477-4038-834a-f2fcb5ea0991)

**Comment by VaidasSa** [comment]
@duEuler thanks for your advice. However, it did not help. See the changes I did.
<img width="524" alt="Issue" src="https://github.com/FlutterFlow/flutterflow-issues/assets/158614140/69574868-e641-4779-ac7d-1cb99a975420">

**Comment by VaidasSa** [comment]
@takashiff @duEuler After waiting 4 months for a solution, I finally deleted the conditional visibility and made a database filter instead.
Ticket is closed.
