### ISSUE TITLE
Checking if bool field exists

### ISSUE THREAD

**Issue by pt173** [FlutterFlow/flutterflow-issues#2293]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We are trying to check whether a specific field of type value exists/is set in the user's document. We do so by creating an action that check if the specific field "is set".
Unfortunately, if the field is not set, FF will return that it is, and believes the field of the value is false.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0fbc7341-6c42-40df-9d9f-1ab844332ff4/4975c75e-1ea8-4009-a60e-256f659ebe46?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZmJjNzM0MS02YzQyLTQwZGYtOWQ5Zi0xYWI4NDQzMzJmZjQvNDk3NWM3NWUtMWVhOC00MDA5LWE2MGUtMjU2ZjY1OWViZTQ2IiwiaWF0IjoxNzA3MTQxMjY2LCJleHAiOjMzMjc3NzAxMjY2fQ.rc1b54Od8DVQsiEOu5NdqW3bYzOkhurbqp_0OjRlBN8)

### Expected Behavior

1. The "is set" operator, should result in true whether the value of the field is set to either true or false, and should return false if the field does not exist, if the field is "not set".
2. FF should show "null" when trying to show the value of an "unset" bool field, and not false.

### Steps to Reproduce

1. Create a blank project and setup firebase & authentication
2. Create a bool field in your consumer document (and data structure)
3. Create an action on tap of button that checks whether that field is set
    3\\\\.1. Log the result of the first condition
    3\\\\.2. Log the value of the field (independently of the result of the first condition)
4. Test with bool field = true
5. Test with bool field = false
6. Test with bool field unset (just delete the field from the document if firestore)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lvLl25F2rsRE7aX6bu9ahjwsJn07beYvm8Jue0k8KOPdOoYUP8+kM0RvYOHjYXw7M0yagWoW0trLkuH1FflfYASuQL1yyqgBTTmUeH6gRpSPFJWvP38nL8FUfHKwy7SZrSZTHNBeWkYtw177Ct7KEzHfJLLPCzAkDq/LZO4=

### Context

I'm just checking whether a field is set or not, allowing me to handle some users differently

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/976bbd22-f2cd-4d2a-8ef0-a7c2a15659a5/a58eb5eb-c33e-4a79-9980-9b01c4cc86a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NzZiYmQyMi1mMmNkLTRkMmEtOGVmMC1hN2MyYTE1NjU5YTUvYTU4ZWI1ZWItYzMzZS00YTc5LTk5ODAtOWIwMWM0Y2M4NmExIiwiaWF0IjoxNzA3MTQxMjY2LCJleHAiOjMzMjc3NzAxMjY2fQ.KhK5iY4gDbd1_Dq-rr66yfe2bw0mhi9NbZd3ldJVd6Q)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Chrome 121.0.6167.86 (Official Build) (64-bit) (cohort: Stable)
- Operating system and version affected: Windows 11 Home, 23H2, 22631.3007
```

**Comment by hariprasadms** [comment]
Hi @pt173 - Thanks for reporting the issue. I've reviewed the steps and tested them in my projects, and everything seems to be working fine. If you still believe you're experiencing the issue, please set up a blank project with the issue steps reproduced in it and share the bug report code. 

This will help expedite the investigation and resolve the issue promptly. Thanks!

**Comment by Azilone** [comment]
I have exactly the same problem, the behavior is not the same depending on the project I have no explanation to date.
