### ISSUE TITLE
SQLite: 'List' Suffix Appended to Variable Names in Function Parameters Causing Compilation Errors

### ISSUE THREAD

**Issue by carsonzylicz** [FlutterFlow/flutterflow-issues#2294]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Screenshot 2024-02-03 at 10 48 55 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/942be7d3-98d8-4190-b46e-67f908494ddb/7622e4cf-fefa-4238-8d34-8b8f8cc18823?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NDJiZTdkMy05OGQ4LTQxOTAtYjQ2ZS02N2Y5MDg0OTRkZGIvNzYyMmU0Y2YtZmVmYS00MjM4LThkMzQtOGI4ZjhjYzE4ODIzIiwiaWF0IjoxNzA3MTQxODcxLCJleHAiOjMzMjc3NzAxODcxfQ.Uuk2yi5OPVqDnWL2cxp6WyE-nFd1XeswoPkSuFdkupo "=1512x")

When creating a variable of any type List, flutterflow is appending “List” to the variable only in the parameter of the manager function and read/ update functions.

This is causing error:
Error (Xcode): lib/backend/sqlite/sqlite_manager.dart:41:9: Error: No named
parameter with the name 'tcgids'.

### sqlite_manager.dart

Future> gETCollections({
    List? ***tcgidsList***,
  }) =>
      performGETCollections(
        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_database,
        tcgids: tcgids,
      );

### sqlite/read.dart

Future> performGETCollections(
  Database database, {
  List? ***tcgidsList***,
}) {
  final query = '''
SELECT
    [collection.id](http://collection.id) AS collectionId,
    collection.card_id AS cardId
    card.tcg_id AS cardTcgId,
    card.image_url AS cardImageUrl,
    collection.qty
FROM collection
JOIN card ON [card.id](http://card.id) = collection.card_id
WHERE card.tcg_id IN $tcgids;

''';
  return \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_readQuery(database, query, (d) => GETCollectionsRow(d));
}

### sqlite_manager.dart

Future> gETCollections({
    List? ***tcgids***,
  }) =>
      performGETCollections(
        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_database,
        tcgids: tcgids,
      );

### sqlite/read.dart

Future> performGETCollections(
  Database database, {
  List? ***tcgids***,
}) {
  final query = '''
SELECT
    [collection.id](http://collection.id) AS collectionId,
    collection.card_id AS cardId
    card.tcg_id AS cardTcgId,
    card.image_url AS cardImageUrl,
    collection.qty
FROM collection
JOIN card ON [card.id](http://card.id) = collection.card_id
WHERE card.tcg_id IN $tcgids;

''';
  return \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_readQuery(database, query, (d) => GETCollectionsRow(d));
}

### Steps to Reproduce

1. Create sqlite query with an input variable of type List. 2. View generated code in sql_manager.dart and read.dart/update.dart

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

sqlite

### Context

Creating sqlite queries and testing locally.

### Visual documentation

![Screenshot 2024-02-03 at 10 48 55 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4e341546-5e79-4089-8faf-d442e3aaa819/60a5e672-f3ba-4b3d-a70b-c2f72ccd9a3a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZTM0MTU0Ni01ZTc5LTQwODktOGZhZi1kNDQyZTNhYWE4MTkvNjBhNWU2NzItZjNiYS00YjNkLWE3MGItYzJmNzJjY2Q5YTNhIiwiaWF0IjoxNzA3MTQxODcxLCJleHAiOjMzMjc3NzAxODcxfQ.VroTmhVtNA4krfPGM28qshLC7lrCeb3eR1Nv8CoaBZ4 "=1512x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.24
- Platform: MacOS
- Browser name and version: N/a
- Operating system and version affected: Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @carsonzylicz - Please provide project bug report code. This information is required to access your project to investigate the issue. Thanks

**Comment by hariprasadms** [comment]
Hi, As no additional details updated, I presume the issue no more exists or its been resolved for you. Hence closing the issue. If you think issue still persists please create a new issue with all required details which can help to investigate the issue. Thanks

**Comment by DCristianValentini** [comment]
Good morning!
I'm facing the same issue. Is there any solution?
