### ISSUE TITLE
The placepicker widget gives name results in my web-solution in German and in my identical IOS/Android app in English.

### ISSUE THREAD

**Issue by Lars2024** [FlutterFlow/flutterflow-issues#2295]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The flutter flow name of my app is "ausflugsapp". I use placepicker to search/ enter a location and store the name and address in my database. The code implementation in web, IOS and android is identical. The language setting of the app in flutter flow is German only. The language settings of the app devices are German only.

When I search "Schloss Heidelberg" in placepicker I get an option "Schloss Heidelberg". If I select this option however "Heidelberg Palace" is set as name (which is stored in my database). This happens both in the IOS and Android app version. In the released web version the name is stored correctly in German language.

### Expected Behavior

I would expect the name result of placepicker in the IOS and Android app being German, if the app language as well as the app devices are set for German language.

As example when I search "Schloss Heidelberg" in placepicker I get an option "Schloss Heidelberg". If I select this option "Schloss Heidelberg" should be set as name (and not "Heidelberg Palace"). Ideally the placepicker widget could be extended with a language selection option for the name outputs.

### Steps to Reproduce

1. Find the flutter flow app "ausflugsapp" and access it. The marketing name of the app planned in the app/play store is "99best places". The web version can be accessed at [www.99bestplaces.de](http://www.99bestplaces.de)
2. Open the app "99 best places" with an IOS or Android device (not with the flutter flow web test, because strangely as web version is works fine)
3. on the first page enter in the placepicker search field "Schloss Heidelberg" and press enter
4. You can see that not "Schloss Heidelberg" is shown in the placepicker field but "Heidelberg Palace" which is the English name.

This can be reproduced on several other pages. It becomes a problem if a new entry is entered in the database with a name that is not German but English.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

all placepicker widgets in the app "99 best places"

### Context

The issue affects the customer value of my app which is to provide a database with trip suggestions in a defined distance of a target region. Several trip names are shown in English even though a user would expect them to be in German. In addition opening a map as function will not lead to the optimal trip location because of the English name.

As the placepicker widgets gives the name of the location picked in the web solution in German (as expected) and in the IOS/Android apps in English this will lead to double entries in the database and a user experience that is unacceptable.

In summary it endangers the success of my app severely.

### Visual documentation

![IMG_7144](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/74db86c1-fd17-4a22-8fbb-c9fc02db2763/2cace0f3-6de3-4f50-baf5-ad31c17bf4f0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NGRiODZjMS1mZDE3LTRhMjItOGZiYi1jOWZjMDJkYjI3NjMvMmNhY2UwZjMtNmRlMy00ZjUwLWJhZjUtYWQzMWMxN2JmNGYwIiwiaWF0IjoxNzA2OTk0NTU1LCJleHAiOjMzMjc3NTU0NTU1fQ.jeokxiJyA56SWIM69yqYW0PELsFhe-l1v0Fs8Vuvm9Y)

![IMG_7145](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a8f1ecd9-e830-4675-9f5a-4f4c8130f4f2/b2fa036b-b910-43cd-a16e-cd64ed9e60d9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hOGYxZWNkOS1lODMwLTQ2NzUtOWY1YS00ZjRjODEzMGY0ZjIvYjJmYTAzNmItYjkxMC00M2NkLWExNmUtY2Q2NGVkOWU2MGQ5IiwiaWF0IjoxNzA2OTk0NTU1LCJleHAiOjMzMjc3NTU0NTU1fQ.I0hMDmUTea2zybipbyUvCir2LAwbBBmuLO4P1v17HUM)

![IMG_7146](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/36bf49c9-2f34-47e1-ba94-e3b97ce26063/69c05b62-e8f0-4c90-81b3-d459e16af492?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNmJmNDljOS0yZjM0LTQ3ZTEtYmE5NC1lM2I5N2NlMjYwNjMvNjljMDViNjItZThmMC00YzkwLTgxYjMtZDQ1OWUxNmFmNDkyIiwiaWF0IjoxNzA2OTk0NTU1LCJleHAiOjMzMjc3NTU0NTU1fQ.cpewNKAghjyH2rwX6tAKkT_v2GlMOTd97S_PZangdOA)

![IMG_7147](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b74cab67-cd7c-4e45-9375-b04545024266/096b30bb-c205-4358-9f59-0aba1745457b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNzRjYWI2Ny1jZDdjLTRlNDUtOTM3NS1iMDQ1NDUwMjQyNjYvMDk2YjMwYmItYzIwNS00MzU4LTlmNTktMGFiYTE3NDU0NTdiIiwiaWF0IjoxNzA2OTk0NTU1LCJleHAiOjMzMjc3NTU0NTU1fQ.o_V0BYwbSuOyJYMj4W0y4WLq0BvmRqVTTLI-rZhzNdo)

![IMG_7149](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fbd47916-9e2c-49c9-960c-ae9e15dea07b/dbee08c2-8b38-4c98-9014-a75a0371a215?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYmQ0NzkxNi05ZTJjLTQ5YzktOTYwYy1hZTllMTVkZWEwN2IvZGJlZTA4YzItOGIzOC00Yzk4LTkwMTQtYTc1YTAzNzFhMjE1IiwiaWF0IjoxNzA2OTk0NTU1LCJleHAiOjMzMjc3NTU0NTU1fQ.fTIySzAkWaggJr45Vh83IDMXnFmOK7Nknv9ltXC5Ilo)

![IMG_7150](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1dd5ea38-76d1-4540-8a30-aedd926284a7/36a89ee0-f37a-4bd3-b269-6fa39c1ff414?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZGQ1ZWEzOC03NmQxLTQ1NDAtOGEzMC1hZWRkOTI2Mjg0YTcvMzZhODllZTAtZjM3YS00YmQzLWIyNjktNmZhMzljMWZmNDE0IiwiaWF0IjoxNzA2OTk0NTU1LCJleHAiOjMzMjc3NTU0NTU1fQ.daXq-LjyAaRJbVT9rctMqP_Ko-4pjoMoWB1cQS5Dr0g)

### Additional Info

Please get in touch with me via e-mail in case you would like more details.

Thank you in advance for your support !!

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: IOS and Android devices with app "99 best places"
- Browser name and version: safari
- Operating system and version affected: IOS 17.2
```

**Comment by takashiff** [comment]
Hi @Lars2024, thank you for your bug report. Would it be possible to provide a blank project where this error has been reproduced? This may help us in the triaging and fixing process. Thanks

**Comment by Lars2024** [comment]
Hi,

yesterday I tested the placepicker widget of flutterflow in a blank project named "place picker test".

Unfortunately the problem has occurred again. The language is set to German both in the flutter flow settings as well as with my iPad test device.
As output of the placepicker widget both the name as well as the address of the location are returned in English on IOS devices. Using the web version is fine with results returned in German as expected.
I looked at the definition of the google maps API places. There it is possible to send a country code which defines the language of the return result. If no country code is send to API places the return defaults to English.

Best regards

Lars

**Comment by Lars2024** [comment]
Thank you for your support to identify this bug. 
What happens next? Is there a timeline in which the bug will be fixed?

Thank you for your reply which is important for the roll-out of my app.

**Comment by takashiff** [comment]
Hi @Lars2024, thank you for the additional information. It has greatly helped us in the identification and resolution of the bug, and I appreciate your cooperation. We've just put in a fix for this bug, so it should be live within the next few weeks (typically by the next deploy/update). Thank you for your patience.

**Comment by Lars2024** [comment]
Hi @takashiff,

thank you very much for this fast implementation of the bug fix. I experienced the whole issue process of you and your colleagues as highly professional and exceptionally good. This is much appreciated and will ensure the continuation of my app development.

**Comment by takashiff** [comment]
Hi @Lars2024, thank you for the kind words, that means a lot to me! As always, please do not hesitate to open up a new ticket in the future should you encounter any bugs. Thanks 🙂
