### ISSUE TITLE
Test mode bug

### ISSUE THREAD

**Issue by harveynguyen09** [FlutterFlow/flutterflow-issues#2296]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![flutterflow](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/53fd4359-63e0-49ad-b4b7-851be39d5ef6/eb7bc383-3658-4c71-95a2-c51094c9cba6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81M2ZkNDM1OS02M2UwLTQ5YWQtYjRiNy04NTFiZTM5ZDVlZjYvZWI3YmMzODMtMzY1OC00YzcxLTk1YTItYzUxMDk0YzljYmE2IiwiaWF0IjoxNzA3MTQxMjI4LCJleHAiOjMzMjc3NzAxMjI4fQ.aKjmnZTTRLw4XPyLAk3F2mteqye_8Nr1xAVimAMz_TY "=954x")

I realize the test mode is not run well recently. I was waiting for 5 minutes but It was still the same.
But if I change the screen mode (from phone to web) and back to phone mode, It will be back to normal.

### Expected Behavior

Test mode is running well because this bug will affect our front-end design.

### Steps to Reproduce

1. Create page
2. Code some component.
3. Runt test mode
4. You will see it my attachment
5. Change from phone to web
6. Change from web to phone
7. The result.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcmAx491ofpE7aX6bu9VgiUQHGF6U700rNx+bw4bI+P1P5kuZcz7UEhVcuqHYwtcG0yZ8Vs0/tnGvdr1D8FfGEyZY6piws1TUxDjRji6V7qXCc+gT3R8BfhXCmq5056s2hR+XfheSGAd2F+Tf96QY3qCf9qOYwx5e6fDbOY=

### Context

this bug will affect our front-end design.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/93a96fd9-9327-4276-88eb-8138ce7a80c0/afef649e-af03-4f29-806f-b13d330eeece?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85M2E5NmZkOS05MzI3LTQyNzYtODhlYi04MTM4Y2U3YTgwYzAvYWZlZjY0OWUtYWYwMy00ZjI5LTgwNmYtYjEzZDMzMGVlZWNlIiwiaWF0IjoxNzA3MTQxMjI4LCJleHAiOjMzMjc3NzAxMjI4fQ.QeG3E1xK0yJdc2-cLNhmXUywyKYInJfnUv4EaER3C88 "=954x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome121.0.6167.140
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
@[**harveynguyen09**](https://github.com/harveynguyen09)** **\- Thank you for bringing up the issue. After verifying it in my own projects, I can confirm that everything is working correctly without any issues. Therefore, I will proceed to close this issue. If you encounter any further issues or have additional concerns, please don't hesitate to let me know.
