### ISSUE TITLE
Tabbar ~Can't set initial tab index

### ISSUE THREAD

**Issue by vardarsezgin** [FlutterFlow/flutterflow-issues#2299]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

can't set initial tab index. I set it 0 or 1 for example then it deletes it automatically. I noticed when I clicked another widget and turn back.

### Expected Behavior

to store it.

### Steps to Reproduce

add tab bar
set initial index

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPHqw49Om7xY0JDTbcZGmmMROUR5TLJEt9Z+azsgF5D4B4oPP8+lUFpCUtCzaH9cAVCJnkAE+M7eidrXK/cEORCZRtlqyIdueBPPbFKiM66bDZC8SnNBEcZUCG6C58Gw2REmJvVeWngR1FyqN+e+TT2Cf9qOYwx5e6fDbOY=

### Context

I mentioned above

### Visual documentation

![Screenshot 2024-02-05 at 20 09 20](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fc6321d0-ca4b-4651-9459-4c47caf07904/d0a7345b-0629-4351-ac01-c517f49cf43a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYzYzMjFkMC1jYTRiLTQ2NTEtOTQ1OS00YzQ3Y2FmMDc5MDQvZDBhNzM0NWItMDYyOS00MzUxLWFjMDEtYzUxN2Y0OWNmNDNhIiwiaWF0IjoxNzA3MTUzNTAzLCJleHAiOjMzMjc3NzEzNTAzfQ.3PchvQkq3Dt2XKSOKx1e2DeeMW3B_l4hxvDDkDLDCi0 "=410x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1 feb 5, 2024
- Platform:macos
- Browser name and version:chrome 121.0.6167.139
- Operating system and version affected: mac os 14
```

**Comment by hariprasadms** [comment]
Hi @vardarsezgin - Blank project with issue reproduced init please. Without these details we can't investigate the issue.

**Comment by hariprasadms** [comment]
No worries. I can reproduce the issue. Thanks 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/bd46df08-9d19-427f-a50c-d0dd1469b562

**Comment by takashiff** [comment]
Hi @vardarsezgin, thank you for the bug report. We've put in a fix for this issue recently, and it should be out within the next few weeks. I apologize for the delay and thank you for your patience.
