### ISSUE TITLE
Scan Barcode/QR Code scans whole screen not only scan area on Andriod devices

### ISSUE THREAD

**Issue by RonGelb** [FlutterFlow/flutterflow-issues#23]
Using in an '**Action**' the '**Scan Barcode/QR Code**' from '**UI Interaction**' does not only scans the scan area but scans objects seen on the whole screen. This creates unwanted results during the scan. In my case, I want to scan the barcode of an item. If there are several articles next to each other, (not only) the barcode of the article that is in the scan area is scanned, but any barcode within the screen that is found first. It doesn't matter whether "Barcode Mode" is set or not.

**This bug is only on Android devices**. With IOS devices, the scan works as expected.

## Expected behavior

Using in an '**Action**' the '**Scan Barcode/QR Code**' from '**UI Interaction**' only barcodes with the scan area should be scanned.

## Current behavior
All barcodes are scanned which are on the screen.

## To Reproduce

* Version of FlutterFlow used: 3.0.5
* Operating system and version (mobile): Android 12

**Comment by Pepino-GR** [comment]
Hello RonGelb,

on my Pixel4, inside the  action 'scan Barcode/QR code the setting 'Barcode Mode' reduced the barcode scanning window. Maybe it can help you

**Comment by bulgariamitko** [comment]
Is that coming from FF or is it a device issue?

**Comment by Pepino-GR** [comment]
I have tested it with a Google Pixel 4a. For me it is an issue with the imported flutter package flutter_barcode_scanner

**Comment by agreaves** [comment]
Unfortunately, this is a limitation of the QR-code scanning package that we use, and is not something we can easily fix. Sorry about that! I'm going to close this issue for now, but I will update if we at some point down the line upgrade the QR code package.
