### ISSUE TITLE
FF does not generate code correctly.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#230]
I defined a function that accepts a parameter of document list and that may be null.

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/5080329/207862574-70ee9209-c4e6-4194-90ff-eb8513bc63bc.png">

I am passing a list that is actually null. (Algolia search result variable)

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/5080329/207862816-3af657b7-7322-470c-b178-5fef345ae113.png">

And see the code that FF generated.
<img width="581" alt="image" src="https://user-images.githubusercontent.com/5080329/207863115-fa5a1327-b6ed-4881-a4c2-3516d6260d3a.png">

It should be `algoliaSearchResults?.toList()`.

**Comment by aemelyanovff** [comment]
This will be fixed in the next release.

@thruthesky Thanks for reporting the issue. In the future, please follow the bug report template :-)
