### ISSUE TITLE
Can't authenticate with email (signup/login)

### ISSUE THREAD

**Issue by dan-arki** [FlutterFlow/flutterflow-issues#2301]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When my textfields are filled im trying auth by clicking on the button, it's loading like 15 seconds an an error message is shown and im still in the login/signup page

### Expected Behavior

I excepted to navigate to the next page, and that a document in the user collection will be created

### Steps to Reproduce

1. fill the fields
2. Press the button lo log
3. and then the error comes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oisrl7ZBItbxK16XuccBvmSQUJVAmU5IzjcpOGDsdF4iuPOxzac/8TBJVZNyrSgllKEWGnkIy09bwk+DuV/AnIRCtbYBT+Khuag3LQXy/aovSCJagWUB9GehjI3az07a3nyR4OtZ0WEJh602yLuSUbHbvQ7H4Zwh9f6PHaOI=

### Context

This is very urgent because it's for a freelance mission

### Visual documentation

![CleanShot 2024-02-05 at 20 50 56@2x](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4349dc6a-6516-4fa6-bebf-b740cbf0b6db/ebb32f26-983d-4828-be13-973cc1f5bdb2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MzQ5ZGM2YS02NTE2LTRmYTYtYmViZi1iNzQwY2JmMGI2ZGIvZWJiMzJmMjYtOTgzZC00ODI4LWJlMTMtOTczY2MxZjViZGIyIiwiaWF0IjoxNzA3MTcwOTMyLCJleHAiOjMzMjc3NzMwOTMyfQ.ikm8No65V84TU40N63xVJrVa-iJftAUpfkw6Zs6KCQQ)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 - Flutter 3.13.17
- Platform: Macbook Pro M1
- Browser name and version: Arc Version 1.28.0 (45831)
Chromium Engine Version 121.0.6167.139
- Operating system and version affected: MacOs sonoma 14.0 (23A344)
```

**Comment by hariprasadms** [comment]
Hi @dan-arki, Thanks for reporting the issue. Are you still experiencing the problem?

Upon reviewing your project, the Firebase authentication settings appear to be correct. However, it's possible that the Firebase configuration files may be corrupted. I recommend regenerating the files to see if that resolves the issue.

Additionally, I've tested the Firebase registration and sign-in actions in my projects, and they are working without any issues.

**Comment by dan-arki** [comment]
Hi thanks, so I just have to regenerate the config files on the flutterflow
project?
Because I’ve reset many times and the problem still

**Comment by hariprasadms** [comment]
Try these steps please. 

1. I see app check is enabled but I do not see key details are added. Disable app check and try to login. 
2. Add debug mode domain to authentication settings. Try login both the ways, username password and google login. 

Let me know how it goes.

**Comment by hariprasadms** [comment]
Hi @[**dan-arki**](https://github.com/dan-arki)** - What is the latest updates on the issue? If issue is resolved for you, please close the issue. Thanks**

**Comment by jessieplaydatecare** [comment]
Hi @hariprasadms , I have the same issue, it was working before but now after the auth action, it stopped working, here's the code:  IT4KiMn1z8pgod9Y0LrtbfowiikvIjsnap08lut+Z0scGIjyG7l/TMnOVBJuOLC0TG9Uf2eWhnEf09HemvPPNscEKRSBUbp4zpZiUw/zc3K5V6aVErWef25/DedgG2mMyKuz2xR/JrdvSGwn2k2hONyvEnfvQL60C0dFAP+YC5OK2SrDX1iXc2URm05KZDPz

**Comment by dan-arki** [comment]
Hello, it’s okay It was the app check he was activated but useless so i
disabled it and it’s okay now, thanks
