### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by leighajarett** [FlutterFlow/flutterflow-issues#2302]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

N/A

### Expected Behavior

N/A

### Steps to Reproduce

N/A

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

N/A

### Visual documentation

N/A

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by leighajarett** [comment]
I'm testing notications

**Comment by hannah-ff** [comment]
Testing testing testing
