### ISSUE TITLE
Can't assign colour to App State element

### ISSUE THREAD

**Issue by kartoshhka** [FlutterFlow/flutterflow-issues#2304]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I create an app state with a data type that stores a colour, I can't pick a colour. If I enter a hex value, it disappears.

### Expected Behavior

App state should allow you to choose a colour from the colour picker or save the entered hex value.

### Steps to Reproduce

1. Create Data Type that has Color field.

![screen_1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c6e72047-4298-4178-ad5b-1a1adb568cca/e756f55a-6b3b-42a9-abda-5652fa4f965c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNmU3MjA0Ny00Mjk4LTQxNzgtYWQ1Yi0xYTFhZGI1NjhjY2EvZTc1NmY1NWEtNmIzYi00MmE5LWFiZGEtNTY1MmZhNGY5NjVjIiwiaWF0IjoxNzA3MjIyNjIwLCJleHAiOjMzMjc3NzgyNjIwfQ.fW09azJgbrBxk9olRrdLNsCSqo_DUUu5vNsRCnwAPlg)

1. Add App State that stores a list of created Data Type.

![screen_2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/427d5b09-10ea-4c09-a563-c2f5755c2fad/8b636e3e-37d9-4724-bf5a-8dec9d5afff7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MjdkNWIwOS0xMGVhLTRjMDktYTU2My1jMmY1NzU1YzJmYWQvOGI2MzZlM2UtMzdkOS00NzI0LWJmNWEtOGRlYzlkNWFmZmY3IiwiaWF0IjoxNzA3MjIyNjIwLCJleHAiOjMzMjc3NzgyNjIwfQ.NNHcaxBLUWOJnblWV_bVFPDKSuHj-\_YcW6duylN5NsA)

1. Add new Item and try to assign color to it.

![screen_3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bea25376-fd2e-4540-a01a-825658e64b35/0a9f8d32-c0ab-494a-8e1b-f72bb29de916?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZWEyNTM3Ni1mZDJlLTQ1NDAtYTAxYS04MjU2NThlNjRiMzUvMGE5ZjhkMzItYzBhYi00OTRhLThlMWItZjcyYmIyOWRlOTE2IiwiaWF0IjoxNzA3MjIyNjIwLCJleHAiOjMzMjc3NzgyNjIwfQ.sgd2V0rT7WcoGtzfaLF0Gy2bNj8cdQFRsOu7LqcCWgQ)

When clicking on color picking square, browser console throws following error:

![screen_4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fa00a656-868e-4a31-82b1-c2c437983c3c/8b94f4f1-09be-4938-af13-6dff1cf52a0d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYTAwYTY1Ni04NjhlLTRhMzEtODJiMS1jMmM0Mzc5ODNjM2MvOGI5NGY0ZjEtMDliZS00OTM4LWFmMTMtNmRmZjFjZjUyYTBkIiwiaWF0IjoxNzA3MjIyNjIwLCJleHAiOjMzMjc3NzgyNjIwfQ.pDQgEJNooVbNFOLJVxtxs2aSY6v-0h7HjQc0sdCvsRc)

When trying to add hex value manually, it dissapears when clicking anywhere outside color field.

I also encountered a problem with enums not being saved in this data type, but it is already open in [this issue](https://github.com/FlutterFlow/flutterflow-issues/issues/2191).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goctE+ZCMK8F6hQAkQzM8bYJMl9cbEAoafJCtBLQQZOr+VFZDTdOde3xYPVqb8VEE+vzqi9nTEvYFAziseINoz4d6Zg7wYHGRVczTPpGOYHFATN9QfnLF0J6VmSJdLttvclkjw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to store my app data locally, so correctly working app states are essential.

### Visual documentation

Provided in "Steps to Reproduce".

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released February 2, 2024
- Platform: Web
- Browser name and version: Chrome 121.0.6167.140
- Operating system and version affected: Windows 10 Home 22H2 19045.3803
```

**Comment by sheprograms** [comment]
I may be experiencing a related issue. See my description with steps to reproduce here: 
https://community.flutterflow.io/ask-the-community/post/problem-setting-color-from-variable-TPymWwdkFhTO5fC

**Comment by takashiff** [comment]
Hi all, I apologize for the delayed response. This issue has been fixed a few weeks ago, and the changes should be reflected on the live application. Please let me know if this issue persists. Thanks

**Comment by kartoshhka** [comment]
@takashiff Hi, thank you for the response, but I still can't assign the colour to an App state variable (checked it in two projects and also in both Chrome and Firefox). But the [problem with enums](https://github.com/FlutterFlow/flutterflow-issues/issues/2191) has gone.

**Comment by takashiff** [comment]
@kartoshhka Thank you for the quick response, I apologize for the incorrect closure of the ticket.

**Comment by youdjin2** [comment]
this issue is still present, can;t assign color to app state variable or to a form field

**Comment by Maoyikurt** [comment]
this issued is still present, cant assign color to appstate when using dataTypes. And its not persisted.
