### ISSUE TITLE
Callback action parameter value isn't accessible in the Action Flow Editor

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#2305]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a custom component that accepts a callback action with String parameter. I use this component as a component for bottom sheet. In a "Show Bottom sheet" action settings I select this component and below in section "Parameters" I see my callback action with type "Action (String)" and possibility to open an Action Flow Editor. Now if I open the action flow editor and want to get use of that String parameter value I cannot do this because the value is not accessible (I cannot find it among available variables).

### Expected Behavior

Possibility to use the callback's parameter value.

### Steps to Reproduce

1. Create a custom component with a parameter of type "Action (String)"
2. Somewhere in the project add action "Show Bottom sheet".
3. Specify the above custom component as a component for the bottom sheet.
4. In the parameters section select the component's parameter and open the Action Flow Editor.
5. Try to get use of the callback's parameter value (e.g. display it in a snack bar). You'll be unable to do it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wksmB34p2sdtJ14SJb+9V+CQvIjs9RL8VkdYbdCs9f5CvOpYUec/6P1dVXs+8T1VDeVqcp14F3NbFufzDM/o6aBKZfrk4wpN+bAqXWkGmR5eTF7ieWmtQM/5gfXbD35izuCJQBM1YcUI4wEyUGvCAZ3PUN4yyDUQwSq/LZO4=

### Context

I'm trying to get a value back as a result of an action inside the bottom sheet. And I still have to use App State variable.

### Visual documentation

The component parameter definition:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/404ea94e-b3e2-4b22-aa9a-ff0d1be9d7a5/f214b95e-3f32-4581-9667-5fcf2af8af76?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MDRlYTk0ZS1iM2UyLTRiMjItYWE5YS1mZjBkMWJlOWQ3YTUvZjIxNGI5NWUtM2YzMi00NTgxLTk2NjctNWZjZjJhZjhhZjc2IiwiaWF0IjoxNzA3MjQyMDE2LCJleHAiOjMzMjc3ODAyMDE2fQ.xYd9vSAlezZsdA05EwpUuXG_eGU2rXVnvrjAKHZ5DG8)

Component usage as a bottom sheet component:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/57ea9168-f561-44c8-aad0-68a9157df642/6cecc74b-e456-4078-89b5-f088fb3933f5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81N2VhOTE2OC1mNTYxLTQ0YzgtYWFkMC02OGE5MTU3ZGY2NDIvNmNlY2M3NGItZTQ1Ni00MDc4LTg5YjUtZjA4OGZiMzkzM2Y1IiwiaWF0IjoxNzA3MjQyMDE2LCJleHAiOjMzMjc3ODAyMDE2fQ.9bf_GwcJqzGX18_Kobb7tycPMZpUYm2VqFXMpPPsXTM)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released February 2, 2024
- Platform: Windows
- Browser name and version: Google Chrome version 121.0.6167.85
- Operating system and version affected:
```

**Comment by avocadoblue** [comment]
I have the same issue with a component that is used as custom dialog

**Comment by the-digital-pro** [comment]
Yes this is a real pain and needs attention quickly. I have the same issue with a Custom Dialog. It's like the Action Flow editor does not recognise it as a callback but a regular action flow.

**Comment by Spixz** [comment]
Same here thanks for the report.

**Comment by PedrosoDev** [comment]
I have the same problem with the custom dialog

**Comment by ssdesign** [comment]
I also reported a similar issue where the Image list parameter does not work as expected:

When I try, this is what it looks like. As soon as I select the Value Source as "Uploaded Photo/Video, I do not get the option to specify which "uploaded file URLs list" I want to send:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/959358/83c48dfe-03f0-476b-81c0-0a2ef1c007d0)

**Comment by sbis04** [comment]
This should be fixed in the next update!

**Comment by Mohit-1521** [comment]
I am facing the same issue when using a component inside a tooltip. The callback parameter option is not available in the Action Flow Editor for that callback.
