### ISSUE TITLE
Action Reset Form Fields not work in component Choice Chips

### ISSUE THREAD

**Issue by paramparim** [FlutterFlow/flutterflow-issues#2306]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When performing the Reset Form Fields action, the selected elements in the Choice Chips component are not reset. This does not work either on the page or in the popup component.

### Expected Behavior

When performing the Reset Form Fields action, the selected elements in the Choice Chips component must be reset

### Steps to Reproduce

1. Create new page
2. Add Choice Chips widget
3. Add App State variable with a list of values for Choice Chips
4. Add this variable to the Define Options section of the Choice Chips element
5. Add a Reset button and add an action in it when pressed - Reset Form Fields and select the Choice Chips element
6. Launch the application - clicking on the button does not clear the values of Choice Chips

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8eksrlvJRNobhe+Kr9bfpsmj45JlA5arxM0u5udAwafIzpPZl/dsnVN1hWUs/gT2xAJU+WnXwf3NrVk+buN/JdOQuufKJnys9QUjvvWm2VMLqaEbmaZERtOMpECly1yIm7vBFCHLJZS04m2VOuCNmybAjDHabvJGgCAPr9BNzJjnCFLCWyFSJZzQ0PI2mhOfMLKA7WhabJ+NRYlrCEu4l8qBVXzoPSwtX1TBKTWVk=

### Context

I want this action to work correctly

### Visual documentation

![Снимок экрана 2024-02-06 в 18 14 36](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d0c111a7-4988-4bb7-ae5e-2b3e7d57050c/c0c1d127-4d7e-4c56-99fa-927cf2a60b8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMGMxMTFhNy00OTg4LTRiYjctYWU1ZS0yYjNlN2Q1NzA1MGMvYzBjMWQxMjctNGQ3ZS00YzU2LTk5ZmEtOTI3Y2YyYTYwYjhlIiwiaWF0IjoxNzA3MjM0MjQ5LCJleHAiOjMzMjc3Nzk0MjQ5fQ.9DwdEayOa_BKgFKjZOyRifohWCS-Hndm_Hrnx8pvaNo)

![Снимок экрана 2024-02-06 в 18 14 58](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/12cf6560-1d86-4393-a3fd-7bda50e88e36/c5ca689f-4181-422c-bfb8-58872c208dc0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMmNmNjU2MC0xZDg2LTQzOTMtYTNmZC03YmRhNTBlODhlMzYvYzVjYTY4OWYtNDE4MS00MjJjLWJmYjgtNTg4NzJjMjA4ZGMwIiwiaWF0IjoxNzA3MjM0MjQ5LCJleHAiOjMzMjc3Nzk0MjQ5fQ.clr_M34lSfqGkigDRV9gv2mn1iJCfOEUlQpcDQDXeio)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released February 2, 2024
- Platform: Web
- Browser name and version: Chrome 121.0.6167.139
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by Krystian95** [comment]
https://github.com/FlutterFlow/flutterflow-issues/issues/1577
