### ISSUE TITLE
setting parameters for custom widget conflict

### ISSUE THREAD

**Issue by esamzenhom** [FlutterFlow/flutterflow-issues#2307]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i got a custom widget in the custom team widgets, with color and and double parameter, after importing the widget to a project, on setting the color, the double goes empty, and vice versa,
attached illustrative video

### Expected Behavior

setting color and double properly

### Steps to Reproduce

i got a custom widget, with color and and double parameter, on setting the color, the double goes empty, and vice versa,

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8oh/Lq25dPn7xA1pPqdcBv+TgRNmY5a7g7kcN+EBAbIZjoOuwQduHCblNoQvWiYWlHGlL88X40097PvtnxG/sVAwSBGdk4ws9AEx/PRXG6bqq7CqWSeXwkGd9hGnXC34mNiCUmJs5fXHs361OUFeiXEx3qJpDpNVcvAM6aFLz++UqKGCbBJiZG+ykPR3LQEfljIVDq+f6QspZl1eTjzw==

### Context

\\\\*\\\\*

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/117540200/5c28b443-78df-4439-bda8-c6e345c3dab6](https://github.com/FlutterFlow/flutterflow-issues/assets/117540200/5c28b443-78df-4439-bda8-c6e345c3dab6)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.24
- Platform:macos app
- Browser name and version:
- Operating system and version affected: macos
```

**Comment by hariprasadms** [comment]
Hi @esamzenhom - I have verified your project. I can see that the issue no more exists and it all works fine. Hence closing the issue. Thanks

**Comment by esamzenhom** [comment]
Thanks @hariprasadms for your quick action
