### ISSUE TITLE
firebase realtime_database

### ISSUE THREAD

**Issue by fubr** [FlutterFlow/flutterflow-issues#2309]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No version of firebase_database works when creating a custom action.This is the same error i receive no matter what version i attempt to try.

```
Error: Failed running flutter pub get...

Error on line 31, column 3 of pubspec.yaml: Not a valid package name.

31 │ firebase_database 10.4.4:

│ ^^^^^^^^^^^^^^^^^^^^^^^^
```

### Expected Behavior

expected behavior is the plugin to be found

### Steps to Reproduce

1. add new custom action
2. add pubspec Dependency
3. paste in firebase_database
4. create test code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

thereIsNoErrorCode

### Context

This issue is restricting me from being able to continue with my project as my project relies on using the realtime database.

### Visual documentation

![Screenshot (1)](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f7ddbc27-c734-4584-ba42-0d0005a33b4c/041f5964-ae55-4740-9714-e1ea345d8dc5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mN2RkYmMyNy1jNzM0LTQ1ODQtYmE0Mi0wZDAwMDVhMzNiNGMvMDQxZjU5NjQtYWU1NS00NzQwLTk3MTQtZTFlYTM0NWQ4ZGM1IiwiaWF0IjoxNzA3MjUwNDczLCJleHAiOjMzMjc3ODEwNDczfQ.q2PPz3WSS6hc05MTBr9gSBFHD6H1O08yvNaqUAzbiLI)

![Screenshot (2)](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/194b1fe1-708f-486a-81a8-bd4afb861193/8a1ccb33-78d6-4303-827c-81574a589255?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xOTRiMWZlMS03MDhmLTQ4NmEtODFhOC1iZDRhZmI4NjExOTMvOGExY2NiMzMtNzhkNi00MzAzLTgyN2MtODE1NzRhNTg5MjU1IiwiaWF0IjoxNzA3MjUwNDczLCJleHAiOjMzMjc3ODEwNDczfQ.4NzY3WlMCJuJF7nFraSBkeatNwib7Jh1kCmOQWVXm8o)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: 121.0.6167.140 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro N
```

**Comment by hariprasadms** [comment]
Hi @fubr - Thank you for bringing up this issue. The 'firebase realtime_database' package isn't officially supported by FlutterFlow. Consequently, it may encounter version conflicts with existing supported packages. As a result, it's currently not recommended for use. Your understanding is appreciated.
