### ISSUE TITLE
Serious problem with Local State variables

### ISSUE THREAD

**Issue by rdspencer** [FlutterFlow/flutterflow-issues#231]
This line seems to have been added lately at the start of building each page: context.watch<FFAppState>();;. Is it something I have done to the project or have you changed the code generation.
The problem is that if a local state variable is updated in a the build of a Custom Widget, the app goes into an infinite loop. Can you put a switch in the FlutterFlow UI to turn this off?
I have to set a Local State variable in a Custom widget as a work-around to an earlier reported problem. Please fix ASAP as means I am dead in the water using FlutterFlow.
When I went through the code generated by FlutterFlow and commented out the context.watch<FFAppState>() statements, the problem went away. This is definitely the source of my SERIOUS problem. Please just put a switch in the UI to optionally remove this from the code.

**Comment by isegal** [comment]
I too noticed it added the watch() for everything, which seems like an overkill. Ideally it should be more lazily added, i.e. only in widgets that access the local state.

In your case though, is there a reason to set local state inside build? Flutter intended build() methods should be pure / have no side effects (in other words, they should be read-only and not modify any state or global variables).

As an alternative, you can add the following in your custom widget's initState():

```
  @override
  void initState() {
  super.initState();

  // On page load action.
  SchedulerBinding.instance.addPostFrameCallback((_) async {
             // <---- Update the local state here
  });

**Comment by rdspencer** [comment]
Thank you for your suggestion - I will give it a try.
The reason I am writing to a Local State variable during the build is to workaround another FlutterFlow code generation bug.

I want to pass the DocumentReference of a subcollection document as a parameter from one page to another, but instead I write it into a Local State variable and use that to access the document in the called page.  This is because there is a bug in the code generation on passing parameters.  The problem is in serialization_utils.dart, in the function serializeParam. This bit of code is wrong when the parameter is a Firestore subcollection: case ParamType.DocumentReference:
return (param as DocumentReference).id; It dhould be: case ParamType.DocumentReference:
return (param as DocumentReference).path;

I reported this bug in the chat a month ago, I don't think it has been fixed yet - perhaps I should report it here.

**Comment by wenkaifan0720** [comment]
Hi @rdspencer. Don't worry, I'll look into both problems and hopefully fix them by the end of next week.

**Comment by wenkaifan0720** [comment]
Hi @rdspencer. I have pushed a fix for the second issue you mentioned. As for the first one, I also don't think it is good practice to update a local state variable in the widget's `build()` method.

**Comment by rdspencer** [comment]
You do not seem to have fixed my 'second' problems - I have checked this in the code produced today.
I think the problem is in your file serialization_utils.dart, in the function serializeParam. This bit of code is wrong when the parameter is a Firestore subcollection: case ParamType.DocumentReference:
return (param as DocumentReference).id; It dhould be: case ParamType.DocumentReference:
return (param as DocumentReference).path;

**Comment by wenkaifan0720** [comment]
Hi @rdspencer. The fix hasn't arrived in the public version yet. There is usually some delay, especially during the holidays.

**Comment by rdspencer** [comment]
OK - thanks.

**Comment by agreaves** [comment]
Hi @rdspencer, both the issues you mentioned will be fixed in the next deploy! In the local state case, you'll need to wrap any local state updates you've done in custom code with
```
FFAppState.updateSilently(() {
  FFAppState().foo = 'bar';
});
```

**Comment by rdspencer** [comment]
Thank you I will try that.  And thanks too for the forthcoming fixes.

**Comment by rdspencer** [comment]
I have a problem with the fix proposed: FFAppState.updateSilently() does not exist.

**Comment by rdspencer** [comment]
Thank you - the initial problem has been solved by a FlutterFlow update.  Local State variable updates no longer cause an automatic rebuild - thank you.
