### ISSUE TITLE
SwipeableStack generating children from query: The getter 'index' isn't defined (doesn't build)

### ISSUE THREAD

**Issue by blue9384** [FlutterFlow/flutterflow-issues#2310]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using a SwipeableStack widget that dynamically generates its children from a Firestore query. Flutterflow does not display any issues, however, the code doesn't build (tested for iOS). Instead, the console output says:

Error: The getter 'index' isn't defined for the class

Upon reviewing the code more carefully, it appears that the problematic usage of index occurs within the .listen method attached to the StreamBuilder's stream.

### Expected Behavior

The code should compile and the SwipeableStack should be usable, including if its children have been generated dynamically from a database call. This behavior is explicitly described in the corresponding Flutterflow documentation and it is important because this is the only way to get the important "On Data Change" option for actions.

### Steps to Reproduce

1. Create a new page
2. Create a SwipeableStack widget
3. Add a query for multiple documents to the SwipeableStack and let it generate its children dynamically from the query's results
4. Download the code and try to build it
5. Observe that the project doesn't build

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlcr65YZPsdhE0LrUYMdFhSkwGW4bbecRldV+ZxEbCIzKOpkAZcynP1doOde8T2xqOWC2p14B+N7LiPPtN8EnOTCBGL5O1ZNTEwyXZH6nSr2TF7WRdUYnO/5WBVSn06WrhQl+HPZhdCUB32WAIu+9FnfYK4SwIlQ4Sq/LZO4=

### Context

I was trying to build a SwipeableStack widget that displays data dynamically based on a query. I tried a workaround but that leads to other issues, not at compile time, but at runtime, because state management and syncing is more inefficient and inflexible if not performed directly on the SwipeableStack.

### Visual documentation

![Screenshot 2024-02-06 at 20 46 51](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a9edc9c6-5b6e-4bb1-913c-63576fe73964/1048d36a-df3b-4d51-9bfc-d4ef67400f30?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hOWVkYzljNi01YjZlLTRiYjEtOTEzYy02MzU3NmZlNzM5NjQvMTA0OGQzNmEtZGYzYi00ZDUxLTliZmMtZDRlZjY3NDAwZjMwIiwiaWF0IjoxNzA3Mjk3MTQ3LCJleHAiOjMzMjc3ODU3MTQ3fQ.oeOI6MhKfKs_J2ld4UtXJpr3zcDUPDqlZ8XU3XBQDXw "=327x")

![Screenshot 2024-02-06 at 20 47 32](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9bfd5728-a5ce-4f3d-b79b-74d1c68b4062/1fa1e637-4baf-4004-a75f-3e2edd4eda85?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YmZkNTcyOC1hNWNlLTRmM2QtYjc5Yi03NGQxYzY4YjQwNjIvMWZhMWU2MzctNGJhZi00MDA0LWE3NWYtM2UyZWRkNGVkYTg1IiwiaWF0IjoxNzA3Mjk3MTQ3LCJleHAiOjMzMjc3ODU3MTQ3fQ.a6ZkWJnF4XHz06-1BpqKCAp0D1Y8go3Mu4Ujczlla1Q "=564x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: iOS
- Browser name and version: Chrome 121.0.6167.139
- Operating system and version affected: macOS Sonoma 14.3
```

**Comment by hariprasadms** [comment]
Hi @blue9384 - Thanks for reporting the issue. I've thoroughly checked the steps in the project and downloaded the code. Everything appears to be functioning properly on my end, and I didn't encounter any of the errors you mentioned. However, I did notice one difference: in the Swippablestack widget and its query, you have used a container widget to query the Firestore collection and then mapped the query result to the Swippablestack widget. I suggest shifting the Firestore query to the Swippablestack widget to see if this resolves the issue.

**Comment by blue9384** [comment]
Hi @hariprasadms, thank you for having a look at the issue.
Now, I am not sure if you will still read this because you marked the issue as closed already. But I have hope you might be looking into it because the most recent issue as of writing this, #2324, is almost exactly the same.
I apologize for making changes since reporting the bug, changes aimed at fixing it. The container is some kind of fix, but as I said, it leads to other issues, at runtime. I just switched it back to the SwipeableStack directly again and it doesn't build now for me.
I think I will go on to custom code this widget. Perhaps one day someone describes it better than me and then it will be fixed.

**Comment by hariprasadms** [comment]
Hi @blue9384 - I have confirmed the status of the issue based on the reproducible steps provided above. I have tested the steps, and everything works as expected. If you still believe the issue persists, I recommend creating a blank project and reproducing the issue in it, then sharing the bug report code. I will re-investigate the issue and we can determine its status accordingly.
