### ISSUE TITLE
Audio upload to Firebase not working

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#2312]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Recently, Flutterflow added the capacity to store audios into Firebase: [https://docs.flutterflow.io/actions/actions/utilities/audio-recording](https://docs.flutterflow.io/actions/actions/utilities/audio-recording)

Unfortunately, it does not work for me.

I am able to start and stop the audio recording without any issue (with the corresponding actions on a start button and a stop button). See the attached pictures.

However, I am unable to upload the Bytes file in Firebase Storage using the "Upload file to Firebase" action. I have no idea why it does not work. My only cue is that I see "Recorded File" instead of "myrecordBytes" (the "Action output variable name") in the widget states.

### Expected Behavior

The upload action should work and the audio file should appear in Firebase Storage.

### Steps to Reproduce

I followed the same steps as in the documentation: [https://docs.flutterflow.io/actions/actions/utilities/audio-recording](https://docs.flutterflow.io/actions/actions/utilities/audio-recording)

I created two buttons : one with the "Start audio" action and one with the "Stop audio action" followed by the "Upload file to Firebase" action. See the attached pictures for details.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KivHq389Pm8tD1aXIccdFoCYXGDsnRYIoltVDYwkbCJCsG7l/S8+kfhNuXbC0TWxAJVqggTkz+vfemvPPUO45AxCsGKZjz7gBZAz/QmGiVbLWDc3teG5/DflXIH6F1raRmh4kIsttSEZh7zu2FumAQXXAQ671OlgjBcihKZKK2SrDX1iXc2URm05KZDPz

### Context

Unable to upload audio recordings to Firebase.

### Visual documentation

![start](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/487290ad-6b76-4aea-9028-6a250781c2f0/268f71cc-1df3-4cc1-92a2-befe1b38feea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODcyOTBhZC02Yjc2LTRhZWEtOTAyOC02YTI1MDc4MWMyZjAvMjY4ZjcxY2MtMWRmMy00Y2MxLTkyYTItYmVmZTFiMzhmZWVhIiwiaWF0IjoxNzA3MzIzMTQ5LCJleHAiOjMzMjc3ODgzMTQ5fQ.VBh_eFdTqY1f3iTbR_u7jaWmKLKoUzJLwhRYLg_RZ50)

![stop](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/79da17da-0d34-44e5-a51b-333b16472a18/e7570d90-7266-46f4-b4e4-2eb0f9554547?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83OWRhMTdkYS0wZDM0LTQ0ZTUtYTUxYi0zMzNiMTY0NzJhMTgvZTc1NzBkOTAtNzI2Ni00NmY0LWI0ZTQtMmViMGY5NTU0NTQ3IiwiaWF0IjoxNzA3MzIzMTQ5LCJleHAiOjMzMjc3ODgzMTQ5fQ.4iutc5jzPdvN4oeE5kY1gfHLMfSBroAezOGHxgzDh1Y)

![Upload](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/99ec06ab-0193-48bb-a0b1-21a16c812b64/3b8d1247-2ee3-4dec-8755-9ec06fb867b0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OWVjMDZhYi0wMTkzLTQ4YmItYTBiMS0yMWExNmM4MTJiNjQvM2I4ZDEyNDctMmVlMy00ZGVjLTg3NTUtOWVjMDZmYjg2N2IwIiwiaWF0IjoxNzA3MzIzMTQ5LCJleHAiOjMzMjc3ODgzMTQ5fQ.O3PorS7NOgS15w71rA6HU1BuTPSpgHAo0sfCc7X_pLM)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by Alexandre-Lemyre** [comment]
Nevermind, everything works fine when I do it directly on the app (on my phone). It just does not work in test mode. It would be helpful to specify it in the documentation.

**Comment by ruveydasevinc** [comment]
I'm having the same problem. If you fixed it, can you let me know? about how you do it
