### ISSUE TITLE
HTML View does not show base64 image datauri

### ISSUE THREAD

**Issue by gams1976** [FlutterFlow/flutterflow-issues#2313]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

if you put a<img> tag with src refering a data uri base64 image, it does not show. If you use a remote address it dows work.

### Expected Behavior

show image.

### Steps to Reproduce

include a image tag with datauri. Simple example below

<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMTAwIiB3aWR0aD0iMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI0MCIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIzIiBmaWxsPSJyZWQiLz48L3N2Zz4="/>

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohcjq35d2tbxE7q6JbMExryQvG0h9aLsn1spBZywgfZzzBLN/fPfQP1toXbXnTFVEO2Kcp141zOjGjvHfEfADIQytfa5Y+ZN6Uj3gRmKWeJuTF7mBdkR6P+ZnCG6hyqS3iCYlNvF2V0YOwU+MGtzKEyjUK7rSIEQ4Sq/LZO4=

### Context

View SVG images with are not supported by the image widget

### Visual documentation

Esy steps described before

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:Web
- Browser name and version: Chrome 121.0.6167.141
- Operating system and version affected:  Windows 11
```

**Comment by hariprasadms** [comment]
Thanks for the details. It is helpful.

**Comment by takashiff** [comment]
Hi @gams1976, thank you for your bug report. The HTMLView widget in FlutterFlow uses Flutter's native `Html` widget, so unfortunately, fixing this is currently out of our control. Thanks
