### ISSUE TITLE
Recorded audio files uploaded to Supabase are corrupted 

### ISSUE THREAD

**Issue by julian-dymek** [FlutterFlow/flutterflow-issues#2316]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using the Actions Editor, I record and upload a voice recording to Supabase. The mp3 file is always uploaded into the Supabase bucket. Sometimes, it is playable, most of the time though, it is corrupted and not playable, also when downloaded and tested locally. I have tried fixing it by adding a delay, to give the audio file more time to get saved, did not work though.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0bb59a18-1082-4b0e-939d-2cc007e0839b/bda62e5c-6e8d-4d72-8b96-d78397f96eb1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYmI1OWExOC0xMDgyLTRiMGUtOTM5ZC0yY2MwMDdlMDgzOWIvYmRhNjJlNWMtNmU4ZC00ZDcyLThiOTYtZDc4Mzk3Zjk2ZWIxIiwiaWF0IjoxNzA3NDEwODYwLCJleHAiOjMzMjc3OTcwODYwfQ.jWU5U80G9w6vo94vkPBpwnM-rO0IiNZzNo2czrwzP4Q "=505x")

### Expected Behavior

It should upload the file correctly to Supabase, so it's usable and playable.

### Steps to Reproduce

1. Set Up and connect Supabase (In project settings). In Supabase, create bucket called "audio", folder called "rec" within bucket.
2. Create a button to start the recording (icon button)
3. In Action Flow Editor, add these actions:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/aa1a5d5b-212a-4bc4-9531-476a52cb5d74/6fdcf92e-ad71-4496-b301-fc7d9ed31099?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYTFhNWQ1Yi0yMTJhLTRiYzQtOTUzMS00NzZhNTJjYjVkNzQvNmZkY2Y5MmUtYWQ3MS00NDk2LWIzMDEtZmM3ZDllZDMxMDk5IiwiaWF0IjoxNzA3NDEwODYwLCJleHAiOjMzMjc3OTcwODYwfQ.ZyXRrIzKFBCDHwzuvrMqixcG6tb468XkYeXup429PiU "=593x")

1. Create another button to end the recording (icon button)
2. In Action Flow Editor, add these actions:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6ee69910-feee-4547-81b3-8540dfb91832/ae21774f-3639-409a-bf64-5288830d54f7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZWU2OTkxMC1mZWVlLTQ1NDctODFiMy04NTQwZGZiOTE4MzIvYWUyMTc3NGYtMzYzOS00MDlhLWJmNjQtNTI4ODgzMGQ1NGY3IiwiaWF0IjoxNzA3NDEwODYwLCJleHAiOjMzMjc3OTcwODYwfQ.6zqoeU-mXz4i5PsdJVRVLrS9iKqLPOMxB994tXx9FA8 "=210x")

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bfda7580-b31c-4c4f-b5aa-85d81f043b1d/c77a4501-b5c3-4636-9912-c7d3ccde1bb6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZmRhNzU4MC1iMzFjLTRjNGYtYjVhYS04NWQ4MWYwNDNiMWQvYzc3YTQ1MDEtYjVjMy00NjM2LTk5MTItYzdkM2NjZGUxYmI2IiwiaWF0IjoxNzA3NDEwODYwLCJleHAiOjMzMjc3OTcwODYwfQ.6vWi9thSdfTUwTtUd1d0Lznw7V1MxiYVIRNkRuJNoP0 "=237x")

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null

### Context

I'm trying to upload the recorded audio to Supabase and pass it to the OpenAI Whisper API.

### Visual documentation

Added above already

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web/Mac
- Browser name and version: Chrome 120.0.6099.234 arm64
- Operating system and version affected: MacOS 14.2.1 (23C71)
```

**Comment by hariprasadms** [comment]
Hi @julian-dymek - Thanks for reporting the issue. I have verified above steps in my project. It all works fine. audio can record and upload to supabase storage successfully. It can playback the recorded audio file with no issues. If you still experiencing the issue, reproduce the issue steps in a page in your project and share project bug report code with setup details. We can investigate the issue. It mostly looks like the configuration issue at your end. Thanks

**Comment by daronstinnett** [comment]
I think I am having the same issue. The uploaded audio plays fine in the Supabase web interface however when I download it to my mac, it won't play. Nor will tools like Adobe Audition successfully load and play the downloaded file.

**Comment by julian-dymek** [comment]
Try Chrome, that worked for me! Not only to run the web app, but for
everything.

Daron Stinnett ***@***.***> schrieb am Mi. 28. Feb. 2024 um
12:41:

**Comment by ruveydasevinc** [comment]
Hi I'm trying to do the same thing and it's not working. Can you help me if you fixed it?

**Comment by julian-dymek** [comment]
Like I said, switching to Chrome worked for me.

ruveydasevinc ***@***.***> schrieb am Mo. 11. März 2024 um
18:55:

**Comment by DigitalLabSlash** [comment]
Hi, Same issue here. The files are inherently corrupted, and won't play again once sent back to the app

**Comment by DigitalLabSlash** [comment]
This might be causing the issue : https://github.com/FlutterFlow/flutterflow-issues/issues/2749#issuecomment-2061710671

**Comment by kevinxzhou** [comment]
I have the exact same issue, audio files uploaded to supabase do not play and are corrupted. The uploaded file sizes make sense however. This is a pretty major bug and should be fixed immediately as this is delaying our ability to use Flutterflow.

**Comment by hyochan** [comment]
It is currently happening to me

**Comment by JamesSlash** [comment]
For anyone interested in a solution we have created a workaround. contact@slash-digital.io
