### ISSUE TITLE
Flutterflow web publish not GDPR (EU) compliant.

### ISSUE THREAD

**Issue by corsaro0** [FlutterFlow/flutterflow-issues#2317]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Web app publishing function is hosted on US servers.

However, according to the GDPR laws, it is not possible for us to publish sites or apps that do not have servers hosted in Europe.

### Expected Behavior

I expect to be able to publish the web app on European servers or use Firebase hosting

### Steps to Reproduce

1. Create a project
2. publish on web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl8nf5ZZ1rsNc+KX1K/pvr2QQI0MdXOczitVEew4bCIj4B6QIfc/4XEpWZMizaH5IemGJpGIypcLOifzPNPZcEy6bfpw4ycxiWBPPYzimM5iMELigWn9BM9FVCB205sOKkSYmKsxtR0Y92V2Df9+yTT+Cf9qOYwx5e6fDbOY=

### Context

It means that we cannot 100% use all the flutterflow features we are paying for without running into legal problems

### Visual documentation

.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by leighajarett** [comment]
Hi there! This is something in our backlog, closing this issue as we're keeping this tracker specifically for reproducible bugs. Thanks
