### ISSUE TITLE
"On Selected" updating once for ChoiceChips

### ISSUE THREAD

**Issue by olivierb24** [FlutterFlow/flutterflow-issues#2318]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a "choiceChip" selector, the first time an option is selected, the state of choicechips is updated and the "onSelected" actions also trigger. Any subsequent selection does not update the state or trigger "OnSelected" unless another component is updated.

### Expected Behavior

On each selection, the state and "onSelected" actions should trigger.

### Steps to Reproduce

1. Create New Page
2. Add a choice Chip
3. Create a "on selected" action, like updating a page state variable with the value of the choice chip
4. Select one of the choice chips options and notice that the "onSelected" only works once.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cz/Hqx89gocNf1s/Uc/lR/ToUNmY4RYErksBhZEk0DZPLD+wueczBSE5dOO2iTXNAL1n8pHs13NbSkuD+A+UqGyuubrZYzLpqEjrdfFuWb82tCaqSYXZ9P5tJJVzF55izsx1NPsZqclIu2F2mOdiWYATaHZjFNUQjH/r/LZ3PjHOpQ0SLb3kNh1JWeC/v

### Context

Choice chips are not usable to flip flop between options

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/b4888bf5-53b0-45eb-bdd1-5f710b67ad86)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/51684431/0aca730d-dbbe-4083-86f1-e2a9a31a6ec6)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Microsoft Edge Version 121.0.2277.98 (Official build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by JustUserHere** [comment]
@hariprasadms 

i have this issue too, seems that after last FF update it is broken now.  
On top of this - error if default choice chips field is empty
https://github.com/FlutterFlow/flutterflow-issues/issues/2319

**Comment by gellert234-dev** [comment]
I have the same issue, thanks for your report :).

**Comment by JustUserHere** [comment]
@takashiff 
Could you please provide an estimated timeline for resolving the current bug issue? 
and this one too - issue with default choice chip empty field
https://github.com/FlutterFlow/flutterflow-issues/issues/2319

thanks a lot!

**Comment by chongranhao** [comment]
I can confirm this issue too. 
Please keep us updated.

**Comment by proptechbex** [comment]
I can confirm this issue too.
Please keep us updated.

**Comment by takashiff** [comment]
Hi all, thank you for the bug reports. We've resolved the issues that have been brought up and ChoiceChips should be functioning properly within the next 30 minutes. I apologize for any inconveniences and thank you for your patience.
