### ISSUE TITLE
choice chips - not working (after FF update to v4.1.25?)

### ISSUE THREAD

**Issue by JustUserHere** [FlutterFlow/flutterflow-issues#2319]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey-hey!
seems choice chips broken after update (today?) - even old versions which were released and works perfectly, currently not working in simulator (i did not checked on real device)

* empty default choice chip field causing error
* if default choice chip filled with one of the option - it is showing only this choice.

### Expected Behavior

should work as before

### Steps to Reproduce

1. create blank new page
2. put choice chips
3. run and test - red error screen
4. fill default choice chip
5. run and test - choice chips showing only default

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsYt2m+FF7rruYO9WimU4HFAhaq00t94bSQ4YGJTyD+wuf87eSERoZ/XndHxIeE6kiWoW0NrHjc7DG+w6KTWBRrZ7zKhyZBbLRkGtMrKgFJWgYXF9P9xgGlSD052Fmh15IbNfcVYD7WeAFti+YCzUHufKDjI8Dq/LZO4=

### Context

My app is not working anymore.

### Visual documentation

![Снимок экрана 2024-02-08 в 22 28 09](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c63f4fb9-e480-4c5a-b04f-b78f9c2de66f/65341711-1b7f-49a5-8c07-a3a603999229?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNjNmNGZiOS1lNDgwLTRjNWEtYjA0Zi1iNzhmOWMyZGU2NmYvNjUzNDE3MTEtMWI3Zi00OWE1LThjMDctYTNhNjAzOTk5MjI5IiwiaWF0IjoxNzA3NDE5ODcxLCJleHAiOjMzMjc3OTc5ODcxfQ.Z_IjKqCoWb6lyRSCDAGj03ZMonouEXdhs8H5PBhtiT8 "=1504x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: mac
- Browser name and version: safari
- Operating system and version affected: mac
```

**Comment by JustUserHere** [comment]
One of the bug confirmed by another user here https://github.com/FlutterFlow/flutterflow-issues/issues/2318

**Comment by takashiff** [comment]
Hi all, thank you for the bug reports. We've resolved the issues that have been brought up and ChoiceChips should be functioning properly within the next 30 minutes. I apologize for any inconveniences and thank you for your patience.
