### ISSUE TITLE
SQLite .db upload Error

### ISSUE THREAD

**Issue by KahaSieHaha** [FlutterFlow/flutterflow-issues#2321]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After Flutterflow app update, unable to upload .db file. Error msg pop out. DB not exceeds 20MB. The issue was posted on community questions and three more people experience the same problem.

[https://github.com/FlutterFlow/flutterflow-issues/assets/159511296/24e35c2e-be86-48aa-adbc-782d6dbe8860](https://github.com/FlutterFlow/flutterflow-issues/assets/159511296/24e35c2e-be86-48aa-adbc-782d6dbe8860)

### Expected Behavior

a new .db base file should upload. Worked yesterday with the older version

### Steps to Reproduce

under the projest

1. got settings
2. integrations
3. SQLite
4. try upload new database .db file

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx89hpb0D1qrAY+4xiQMwJ0QlUIInj+0bWRMhfYD1B+0qYsjCQxNLYteoT2NcEGCjsFIe092NieHxLfJfZQSCbNly+r5XQRfgXnulM5CDDIeWf3YnRMdmBWK50qujkQpQPsB2WlIQ2mWMOvCrG3qCf9qOYwx5e6fDbOY=

### Context

does not apply, no code app problem

### Visual documentation

screen capture mp4

[https://github.com/FlutterFlow/flutterflow-issues/assets/159511296/0e62f6f7-d2ab-4eba-8fd0-2d850d39be9a](https://github.com/FlutterFlow/flutterflow-issues/assets/159511296/0e62f6f7-d2ab-4eba-8fd0-2d850d39be9a)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.25 Flutter version is 3.13.7
- Platform: Macos
- Browser name and version: Version 121.0.6167.139 (Official Build) (x86_64)
- Operating system and version affected: MacOS Sonoma 14.3
```

**Comment by hariprasadms** [comment]
Hi @KahaSieHaha - Thanks for submitting the issue. I can reproduce it.

**Comment by edwinabb** [comment]
I got the same problem, even if I download from FF the db file and I upload it.  
Thanks for your support,

**Comment by KahaSieHaha** [comment]
@hariprasadms any idea on the timeline for fixing this, it block us a little bit in our development

**Comment by edwinabb** [comment]
I am delivering an app to a customer, he asked for a small change but I can not implement it because I can not upload the new SQlite file.  
It would be great, if you can give as a date, so we can comunicate it to our customers.

**Comment by KahaSieHaha** [comment]
Same here, project on hold. I need to know time frames to communicate to the client

**Comment by agreaves** [comment]
@KahaSieHaha Hey folks! Sorry for this issue, this should now be fixed!

**Comment by edwinabb** [comment]
Thanks for your support!!!

**Comment by edwinabb** [comment]
Hi @agreaves
It is not working again
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/96086641/74c67332-a8dc-429b-abb8-2cf31181b229)

**Comment by edwinabb** [comment]
If I reload the page the issue is solved.
