### ISSUE TITLE
Using the `Swipable Stack Current Element` causes build to fail

### ISSUE THREAD

**Issue by untersalmberger** [FlutterFlow/flutterflow-issues#2324]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using the `Swipable Stack Current Element` value on an `Image` widget's `Path` property, when the `Image` widgets are generated as children within the `SwipeableStack` widget, causes the build to fail.

### Expected Behavior

Using the `Swipable Stack Current Element` value on an `Image` widget's `Path` property, when the `Image` widgets are generated as children within the `SwipeableStack` widget, should show the images with their respective paths in the swipeable stack.

### Steps to Reproduce

1. Start a new project w/o firebase
2. Add an app constant of type `ImagePath` and call it `theImagePaths`, make it a list, add a few items
3. Create a new page
4. Place the `SwipeableStack` widget on the page
5. Select the `SwipeableStack` widget, go to `Generating Children From Variable`, give the variable a name (like `imagePaths`) and set the value of the variable to the before created constant `theImagePaths`, save the variable
6. Remove all `SwipeableStack` pages except the first
7. On the remaining `SwipeableStack` page select the `Image` widget, set the `Path` property to `Swipable Stack Current Element`
8. Run the app in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ghc+A5Yh1ocdD7q6JY8dFijoUCDs/a7gvjupqEAgafJSvBI13duP8XExDXbGBam1cJWaGmm0zwMmLhdrAU+0nCByJbLpZ/5N+TjvNTni5V7a2CJaOZUB6TOlMC0vDzpuZrRZAAO12LlVm3WGMG+eiVgPDQrmxDEYZBPykB9/XnVapHADgG30Jg1ZSfCvr

### Context

I am currently blocked to build a more complex swipeable stack where access to the current element (in my case a struct with arrays included) is required to build the elements within the swipable stack.
Usually there is a workaround to address the current element by indexing the list with the index of the current element, but when the list elements contain another list there seems to be a limitation that I cannot select the nested list.

### Visual documentation

![Screenshot 2024-02-09 at 16 24 19](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/68d8a738-4dbe-4962-a9bc-0fc879058480/d267b114-d4ab-421e-90a7-030311e3a42e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82OGQ4YTczOC00ZGJlLTQ5NjItYTliYy0wZmM4NzkwNTg0ODAvZDI2N2IxMTQtZDRhYi00MjFlLTkwYTctMDMwMzExZTNhNDJlIiwiaWF0IjoxNzA3NDk1OTk3LCJleHAiOjMzMjc4MDU1OTk3fQ.eYsgCGUlfcfq5AR_nFUoXhm39p07gIDJupHEX155fpQ "=1904x")

![Screenshot 2024-02-09 at 16 25 25](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e0f26bfd-abca-44df-a044-710e8fa746c7/edd3d9e7-c4e1-4529-960f-e956a224a2bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMGYyNmJmZC1hYmNhLTQ0ZGYtYTA0NC03MTBlOGZhNzQ2YzcvZWRkM2Q5ZTctYzRlMS00NTI5LTk2MGYtZTk1NmEyMjRhMmJiIiwiaWF0IjoxNzA3NDk1OTk3LCJleHAiOjMzMjc4MDU1OTk3fQ.F7N7xMgN6HcfFlvxRe9yWLmmduRUdWLFSmTxIfsoYvg "=1904x")

### Additional Info

The issue is that the `Image` builder uses `index` instead of `imagePathsIndex` (or in fact it should use the just defined variable `imagePathsItem`, which currently remains unused). `index` is available in the event handlers, but not in the itemBuilder:

![Screenshot 2024-02-09 at 16 26 47](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/18a5502f-7831-4337-8eca-def3c569b7c7/779702ab-fefd-4a66-a2c0-581ab8e0b177?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xOGE1NTAyZi03ODMxLTQzMzctOGVjYS1kZWYzYzU2OWI3YzcvNzc5NzAyYWItZmVmZC00YTY2LWEyYzAtNTgxYWI4ZTBiMTc3IiwiaWF0IjoxNzA3NDk1OTk3LCJleHAiOjMzMjc4MDU1OTk3fQ.aNdxZd4YIMgldYHZbo2utgAChY1ywXM-frszYekV3yk "=1904x")

The project with the issue can be found here: [https://app.flutterflow.io/project/swipable-stack-index-issue-r66g9n?tab=uiBuilder&page=HomePage](https://app.flutterflow.io/project/swipable-stack-index-issue-r66g9n?tab=uiBuilder&page=HomePage)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web, also VSCode after having pushed the source code to GitHub
- Browser name and version: Version 121.0.6167.139 (Official Build) (x86_64)
- Operating system and version affected: MacOS Sonoma Version 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @untersalmberger - I looked at your project. Below variable mapping is the issue. It should be the variable from the generated from image list.

<img width="714" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6d7dabe2-d2f1-4b5e-aa25-1fc22dfaa4da">
