### ISSUE TITLE
Inadvertent Selection of All Form Fields When Attempting to Reset Specific Fields

### ISSUE THREAD

**Issue by rajat8527** [FlutterFlow/flutterflow-issues#2325]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is an issue with form field selection throughout the app. When attempting to select specific fields for resetting, all fields on the UI are inadvertently selected instead. This problem is not specific to a particular page but is happening across multiple areas of the application.

### Expected Behavior

We expected that when clicking on the "Reset" button or attempting to select specific form fields for resetting, only those fields selected or associated with the action would be reset. In other words, the user should be able to target and reset individual form fields without affecting others on the UI.

### Steps to Reproduce

1. Navigate to any screen containing a form with multiple input fields (e.g., text fields) or create a new form.
2. Attempt to perform an action that involves resetting specific form fields, such as clicking on a "Reset" button associated with the form or selecting individual fields to reset.
3. Notice that instead of only the intended fields being reset, all form fields on the UI are selected or reset.
4. Repeat the above steps on different screens and forms throughout the application to confirm that the issue is pervasive and not specific to a single page or form.
5. Observe that the problem persists regardless of the type of form or the specific actions taken within the form.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5flvHlz89goccB7c/MacdB/TgvNjs/a7xMle0aa0ggGK3qOrA2Zs6kNltJbbSVTAhEPVv8oHEe0NbJvuzXVuQHAxGVGbpS/rpQET3xVk65VL61EpG8YmtPI+dmHkuV38PY2xNNC/tvSn8j2jqECvOXFxXsHbLIDjIgRPr8D5PXo2yVAi+6Xn0Jg1ZSfCvr

### Context

This issue with form field selection and resetting affects our workflow within FlutterFlow, the tool we rely on for developing our application. As developers, our goal is to efficiently design and implement user interfaces without encountering obstacles that hinder our progress.

The unintended behavior of selecting all form fields when attempting to reset specific ones disrupts our development process and slows down our ability to create and iterate on UI designs. It undermines the usability of FlutterFlow and complicates our efforts to create intuitive and user-friendly interfaces for our application.

This issue has a direct impact on our productivity and efficiency as we work to build and refine our app. It prevents us from fully leveraging the capabilities of FlutterFlow and forces us to spend additional time troubleshooting and finding workarounds for the problem.

In summary, addressing this issue within FlutterFlow is essential for streamlining our development workflow and ensuring that we can effectively utilize the tool to bring our app to fruition. We rely on FlutterFlow to simplify the development process, and resolving this issue will help us maintain momentum and focus on delivering a high-quality product to our users.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/15009025/e180185b-cfb0-4187-a92c-d134e494749b](https://github.com/FlutterFlow/flutterflow-issues/assets/15009025/e180185b-cfb0-4187-a92c-d134e494749b)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 121.0.6167.160
- Operating system and version affected: MacOS Sonoma 14.1.1
```

**Comment by takashiff** [comment]
Hi @rajat8527, thank you for the bug report. This is currently a known bug regarding components. Currently, as a workaround, instead of using a component for the Form Widgets you'd like to reset, you can wrap your component in a container, copy it from the right click menu, and paste it in where it is needed. Thanks

**Comment by rajat8527** [comment]
Hi @takashiff, The workaround works. Cheers :)

**Comment by takashiff** [comment]
Hi @rajat8527, we've put in a fix for this issue. I will go ahead and mark this as closed for now, but if you are still experiencing this, feel free to follow up in this thread. Thanks for your patience!
