### ISSUE TITLE
lib/flutter_flow/flutter_flow_charts.dart 

### ISSUE THREAD

**Issue by JacoboJacome** [FlutterFlow/flutterflow-issues#2326]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is not possible for me to compile for testing or publish on the web. The error comes from an FF library that I do not have access to.

### Expected Behavior

I am adding an external library for graphics "fl_charts" in version 0.64.0, it compiles well and does not say it has any errors but for some reason it gives an error in the native graphics library.

### Steps to Reproduce

run testing or publish on web publishing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not

### Context

I am adding an external library for graphics "fl_charts" in version 0.64.0, it compiles well and does not say it has any errors but for some reason it gives an error in the native graphics library.

### Visual documentation

![Imagen de WhatsApp 2024-02-09 a las 23 53 07_a048237f](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/86edc06f-98e3-4402-9235-c28a8fca6083/e892442b-e34e-4881-bacc-0ca8e350a5ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NmVkYzA2Zi05OGUzLTQ0MDItOTIzNS1jMjhhOGZjYTYwODMvZTg5MjQ0MmItZTM0ZS00ODgxLWJhY2MtMGNhOGUzNTBhNWVkIiwiaWF0IjoxNzA3NTU3ODkyLCJleHAiOjMzMjc4MTE3ODkyfQ.\_Z8CBfrEn0u-8R4pAA-f1MoHsh02QHhCwz9n3ih-kfc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Brave 1.62.162
- Operating system and version affected: Win 11 23H2
```

**Comment by hariprasadms** [comment]
Hi @JacoboJacome - Thanks for submitting the issue. To proceed with investigating the issue, we require the bug report code associated with your project. Without it, we cannot effectively address the issue. From the description provided, it seems that the external package you are attempting to use might not be compatible with the existing packages in FlutterFlow. I recommend downloading the code and attempting to compile it locally to identify any errors. This process should help you pinpoint the cause of the build failure. Let us know if you need further assistance. Thank you.

**Comment by hariprasadms** [comment]
No required details updated. We presume the issue no more exists or resolved for you. If you issue stll persists, please create a new issue with all required details which can help to investigate the issue. Thanks
