### ISSUE TITLE
Calendar widget not working as expected. Today not clickable and not firing api

### ISSUE THREAD

**Issue by imaginifica** [FlutterFlow/flutterflow-issues#2327]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When calendar widget load, today date does not fire api call and is not clickable anymore, unless I click on another day and then click again on today..

### Expected Behavior

Call api on widget load and today is clickable.

### Steps to Reproduce

1. insert calendar widget
2. create an action to fire an api call on selected date.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfyfHqw4lPsdtD1a6JaMBViioQNUccTIAziu1udw0jCJznBqQieM7BMhZBQsuiaVNcJmGlhXIept70keHUV/k7GzCAbt1bz5dbEg/ke2ihMoy3EqqKP3B7BeFgIHa8yrbQuiNNJtZYL0Ik2DimJOysdCzDFOu/Zwh9f6PHaOI=

### Context

get available time slot from my database through api call on selected day

### Visual documentation

![Screenshot 2024-02-09 alle 21 23 59](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/01a3b2ac-46d3-4067-97ac-d0706a8913b3/894b0a68-f715-4946-a676-c1627628ba63?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMWEzYjJhYy00NmQzLTQwNjctOTdhYy1kMDcwNmE4OTEzYjMvODk0YjBhNjgtZjcxNS00OTQ2LWE2NzYtYzE2Mjc2MjhiYTYzIiwiaWF0IjoxNzA3NTU3OTY3LCJleHAiOjMzMjc4MTE3OTY3fQ.xCkRNPjIker_nsZBr0ls-1Jxv485rj4SlVnVz0vxHCo "=365x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: All
- Browser name and version: Chrome 120.0.6099.234 (Build ufficiale) (arm64)
- Operating system and version affected: Mac osx last update
```

**Comment by takashiff** [comment]
Hi @imaginifica, thank you for the bug report. The previous behavior was actually an unintended bug with the calendar widget. However, I understand your frustrations in how the calendar widget no longer works as expected. I will go ahead and submit a ticket internally to see how we can upgrade our calendar widget to support the behavior you have described above. Thank you for your patience and understanding.
