### ISSUE TITLE
After the successful completion of payment using RAZORPAY, Status gets stuck on processing and orderID is not fetched.

### ISSUE THREAD

**Issue by yashtiwaribitspilani** [FlutterFlow/flutterflow-issues#2328]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the completion of payment through Razorpay, the status is stuck on processing No orderId is fetched but the payment is registered successfully on Razorpay. The app is not updated

### Expected Behavior

After the successful payment, It should not show processing till infinity and should show the success snack bar while fetching the orderId as the action output.

### Steps to Reproduce

1. Create a new page.
2. Add a button.
3. add action of RAZORPAY payment gateway
4. Complete the payment in app,
5. Observe the infinite processing loader.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klcmA04lIobhb7qXxbcFWjiQ7KVB8TLJEoetxc0gbfe/4OqQLPeD7NhZvTcizaH9mHFWbpFwDwvCPuPLtOPcDEwScbaE+zbVidBPPbD67VpSMDc3hS0dAINFUCm6b4aeFrQl/LtRYV3gC2E6EB+SsZz6Cf9qOYwx5e6fDbOY=

### Context

I am not able to capture any payment in my app using RAZORPAY. Please solve this issue.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/115389165/c0c935bf-af52-4664-9ed7-4bd80c474266](https://github.com/FlutterFlow/flutterflow-issues/assets/115389165/c0c935bf-af52-4664-9ed7-4bd80c474266)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:android app
- Browser name and version: chrome 121.0.6167.161
- Operating system and version affected: Windows 11 23H2
```

**Comment by hariprasadms** [comment]
Hi @yashtiwaribitspilani - Thanks for submitting the issue.  I can reproduce the issue.

**Comment by sbis04** [comment]
Hi @yashtiwaribitspilani, from the video a few things are not clear to me. So, I have a few questions:
* I believe you are trying the payment in the TEST mode of Razorpay? 
* If yes, which UPI ID are you using for testing?
* Are you trying in the release mode on the Android device?

**Comment by yashtiwaribitspilani** [comment]
1. Yes I am in the test mode of Razorpay but the payment is not getting captured.
2. I am using test cards and all for the payment given in the Razorpay docs.
3. Yes I also tried on an android device but the result was no different.
Thank you.

**Comment by sbis04** [comment]
Thanks for answering the questions.

I wasn't able to reproduce the issue on a demo Razorpay project, but I was able to reproduce it with your project. And, seems like something is going wrong in accessing the `testVerifySignature` cloud function after the payment is complete (which is resulting in that infinite spinning indicator). Can you check once by opening the Firebase console > Functions page, if that function is present (can you also share a screenshot of that if present). And, then can you please re-deploy the cloud function and try again (basically press "Deploy" in the Razorpay integration of FlutterFlow).

**Comment by yashtiwaribitspilani** [comment]
Thank you for replying to my message.
Sure I am sharing the details with you. Yes, the function is present.

**Comment by yashtiwaribitspilani** [comment]
> @yashtiwaribitspilani did you get a chance to redeploy the cloud functions for Razorpay and try once more? 

Hello there, yes I had tried it but it wasn't working so I have now set up the payments in my app manually using api calls and a lot of custom functions. The inbuilt Razorpay on flutter flow wasn't working.

**Comment by hariprasadms** [comment]
Hi, Its been tested in latest FF updates and I can confirm that it is working as expected. If the issue still exists, please create new issue with latest details. Thanks
