### ISSUE TITLE
Infinite scroll loads ALL images, not just the page view amount

### ISSUE THREAD

**Issue by cheggy** [FlutterFlow/flutterflow-issues#233]
## Expected behavior (required)
When I have a ListView with infinite scroll, it will load the amount of documents that I define.  And when I scroll to the bottom of the ListView, it will load the next number of documents defined.

If I scroll a ListView component to view ALL documents, when I close the app and re-open, if I come back to this ListView, it will not attempt to load ALL of the documents straight away.  It will only load the number that I define as the page size.

## Current behavior (required)
The response is being cached by the user.  Let's say I have a list of 200 documents.  And when I display the document, I display the title, and the image for the document.  And if you tap on it, you are taken to a screen with the details of that document.

If I decide to scroll through the list, it will load all of these posts.

But if I navigate away (or close the app and re-open), when I come back to this screen with the Infinite Scroll list, it will load all of the documents straight away.  Not just the first x that I have defined.  The result is that everytime I go to this screen with the ListView, it calls ALL of the images that are displayed in ALL of the documents.

## To Reproduce (required)

1. Create a screen with a ListView
2. Setup a database collection query for a collection that has a decent amount of documents (more than 40) and has images for each document
3. Add a component to build out the ListView, which includes some text and images from the document response
4. Add Infinite scroll.  I have it set to the screen shot below for the query
5. ![image](https://user-images.githubusercontent.com/3022867/207963051-769968db-232d-4150-a65d-468cc62de6b1.png)
6. Start test mode
7. Go to the app in test mode
8. Visit the screen with the query.
9. Scroll through the ListView till you get to the bottom.
10. Navigate back, navigate somewhere else if you like, close the app.
11. Re-open the app / start Test Mode again.
12. Open Dev Tools to the Network tab
13. Go to the screen that has this Infinite Scroll.
14. You will see all of the images loading for the Documents that should not have loaded yet because infinite scroll says to only load the first 6.

### Bug Report Code
ITFTzMmAsYtIxLRG+KqJdO0wmiYWM0MBX5Ir1utvGBYcJbbmE4kIf8/EaXddXOmBSgk/PGaZ8TkFw9LKkoXlJ/E5OSitGL02k/UwKlCvHAM=

## Context (required)
This causes the screen to be sluggish affecting user experience, users are transferring too much data which affects their data usage, and it affects my hosting bill.

I don't think I should enable caching on the images, because it's user generated content and constantly changing, and would quickly fill up the users storage.

## Screenshots / recordings
Here, you can see I have just loaded the list for the first time and not scrolled.  It should only load the first 6 items.  But it is loading over 100, and calling the image assets for them, which causes the ListView to perform sluggishly as it attempts to load all these images, and is costing me a rather large amount in data transfer fees.

![image](https://user-images.githubusercontent.com/3022867/207969187-1e13fd4a-9d0d-4d57-bb6c-421509e16aa0.png)

Here's the query.  Pretty simple query with sort by created date.  Only asking to load 6 at a time.
![image](https://user-images.githubusercontent.com/3022867/207961937-63d2e515-fc6f-4d63-8d56-9ea2df35ddf3.png)

## Your environment
This is in Chrome, Win 11, FlutterFlow v3.0 Dec 16.  But I have experienced ongoing issues with Infinite Scroll since it came out.  It has never worked correctly for me in different ways.
This also happens in Android Studio Emulator, in Debug mode on a device, and in Production.

There are other issues with infinite scroll that I will log separately.

**Comment by cheggy** [comment]
After some more playing around, I don't think it has anything to do with previous requests and caching.  I have cleared out all cache/db for FlutterFlow in browser.  Logged back into the app.flutterflow site, run the Test mode again (for the first time) on a screen with infinite scroll that should load 16 at a time.  And it is loading everything.  I don't think infinite scroll is working at all.

Worth mentioning the following error is logged over and over again.
RangeError (end): Invalid value: Only valid value is 0: 1

**Comment by cheggy** [comment]
> Is it happening when you first load the Test mode or only when you reopen the app?

It happens when you have a listView with infinite scroll and the size of the listView's primary direction is not confined.

So if you have a vertical listView and don't wrap it in a container with a set height, it will just load everything.  

I figured it out, but there's probably a lot of people who think they have infinite scroll working but don't. Maybe this scenario needs a warning or error shown.

**Comment by agreaves** [comment]
Hi @cheggy, thanks for following up. I'm just going through cleaning up older issues that have been resolved.

Your explanation is correct, however more specifically this happens when a ListView has `Shrink Wrap` set to `true`. This renders the entire ListView when it loads.
