### ISSUE TITLE
IconButton setting icon size from variable/responsive doesn't work

### ISSUE THREAD

**Issue by TeferiHero** [FlutterFlow/flutterflow-issues#2330]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to set size of an IconButton icon from variable, or as responsive value, it stays at the size it was before. Setting the value of an Icon widget works correctly.

### Expected Behavior

I expect the size of the icon in IconButton to be set properly, as it is set in the Icon widget.

### Steps to Reproduce

1. Create new page
2. Add 2 IconButton widgets (the default size should be 24)
3. Create a constant integer with value different than 24 (e.g. 48)
4. Set size of an icon in one of the IconButton widgets from the constant
5. Click the View Code option in the developer menu. See that the size hasn't changed OR
6. Run the project in test mode. Notice the sizes are the same

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ShvHqx4hOxLhK1aXide9VoDoXQz47bZIrmOtqEBEgfJjwEYkTXOimakhuOLCRSmNceWH8/W0y7vyMuIfDD8YFHByJbtlCyKVidTrdVlK7V8WIC8yoXHAlAcZMIUCjzpuZnhN+KvFaSiBh2jn3HuuycAnZJuf0OTE7DcqYFJnM+mCXAR/0G30Jg1ZSfCvr

### Context

I was trying to create a button sized differently on a phone and on a tablet, but I can't change the IconButton icon size

### Visual documentation

Responsiveness in test mode

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/38a668ad-2bd1-4999-8241-9874fdea6f6e/d301d096-afb8-4758-ad5e-03a81afb0c49?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zOGE2NjhhZC0yYmQxLTQ5OTktODI0MS05ODc0ZmRlYTZmNmUvZDMwMWQwOTYtYWZiOC00NzU4LWFkNWUtMDNhODFhZmIwYzQ5IiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.DwRkRpanTQdFcoL8Tv6gMerHeCLIQtl7sblJNnGjpiY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/32513756-4a9b-41e4-918a-0713069cf7fc/31344ece-eaea-4360-91d2-d17696855715?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMjUxMzc1Ni00YTliLTQxZTQtOTE4YS0wNzEzMDY5Y2Y3ZmMvMzEzNDRlY2UtZWFlYS00MzYwLTkxZDItZDE3Njk2ODU1NzE1IiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.K2W0gVvrNHuYoXR6ITNPzpCAR26I4KDrJFE4QhrjyiM)

Setting size from variable (case described in steps to reproduce)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/01194ef1-55c1-4de6-9439-9fdf6b71b1f4/5f6e0456-68f1-4bcf-9acf-b4dfad5840c3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMTE5NGVmMS01NWMxLTRkZTYtOTQzOS05ZmRmNmI3MWIxZjQvNWY2ZTA0NTYtNjhmMS00YmNmLTlhY2YtYjRkZmFkNTg0MGMzIiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.NT3KjBhR9mXc3QOEFNCUIG2-1IpJVwwH3D4sJJ3F3LU)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ae7cbe4b-9e5c-4414-9f9b-10725996db9b/47c8773b-6678-4de7-89d4-671a385f242f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZTdjYmU0Yi05ZTVjLTQ0MTQtOWY5Yi0xMDcyNTk5NmRiOWIvNDdjODc3M2ItNjY3OC00ZGU3LTg5ZDQtNjcxYTM4NWYyNDJmIiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.9IKrMgRzP2WW8aVjL2ytuRRQbKPPsWMXvS0SiKt5L5o)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0e894916-ef37-411f-b708-377a12879881/435ff6ab-0962-4e9a-bc36-72dbd2da592d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZTg5NDkxNi1lZjM3LTQxMWYtYjcwOC0zNzdhMTI4Nzk4ODEvNDM1ZmY2YWItMDk2Mi00ZTlhLWJjMzYtNzJkYmQyZGE1OTJkIiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.u_1cv3gZtGsP3aE4xJlzWyL3HRwLRAOkxf4emy1Q-H0)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/afb9e875-e2ca-45db-830f-cb4e2957d606/99dd5d9f-27fd-46bc-a39d-fd8b631c72ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZmI5ZTg3NS1lMmNhLTQ1ZGItODMwZi1jYjRlMjk1N2Q2MDYvOTlkZDVkOWYtMjdmZC00NmJjLWEzOWQtZmQ4YjYzMWM3MmFjIiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.1yDt9XZFfVYKPNuOHgMCLLv0Kmd4YL9YFZ7DtPFM-zY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdb4ff11-b302-4554-b402-218114be5a59/26241cf6-58a1-4ab4-bc48-5fc04cac6ee6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGI0ZmYxMS1iMzAyLTQ1NTQtYjQwMi0yMTgxMTRiZTVhNTkvMjYyNDFjZjYtNThhMS00YWI0LWJjNDgtNWZjMDRjYWM2ZWU2IiwiaWF0IjoxNzA3NjA3MjM4LCJleHAiOjMzMjc4MTY3MjM4fQ.pewrXRu2DzLKLd4QK8Lqe2Vr1-7VeyM5i5O0k6q6Zng)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released February 9, 2024
- Platform: Web
- Browser name and version: Microsoft Edge Version 121.0.2277.112
- Operating system and version affected:
```

**Comment by univermal** [comment]
I am still encountering this bug in v5.0.8. Is this not yet fixed?
