### ISSUE TITLE
No interface method getBuffer()Lokio/Buffer; in class Lokio/BufferedSource

### ISSUE THREAD

**Issue by skShrikant24** [FlutterFlow/flutterflow-issues#2333]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

facing firestore connectivity issue

### Expected Behavior

its get data from firestore

### Steps to Reproduce

build project on android

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

1111

### Context

![Screenshot (25)](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ec6ed412-aec3-488a-899c-88da21c5cb01/c1775d47-de08-475a-8855-32b666624627?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYzZlZDQxMi1hZWMzLTQ4OGEtODk5Yy04OGRhMjFjNWNiMDEvYzE3NzVkNDctZGUwOC00NzVhLTg4NTUtMzJiNjY2NjI0NjI3IiwiaWF0IjoxNzA3NzMxODUwLCJleHAiOjMzMjc4MjkxODUwfQ.QGOkHYnqO9DG8m3gxraWIrt35dlMYOVJATqBGzR2hd0)

na

### Visual documentation

![Uploading Screenshot (25).png…](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8af36674-402a-4606-9e88-b3dbed51a735/2599b126-1f34-4541-91ab-e97f3c90605d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84YWYzNjY3NC00MDJhLTQ2MDYtOWU4OC1iM2RiZWQ1MWE3MzUvMjU5OWIxMjYtMWYzNC00NTQxLTkxYWItZTk3ZjNjOTA2MDVkIiwiaWF0IjoxNzA3NzMxODUwLCJleHAiOjMzMjc4MjkxODUwfQ.ZarvcwTOYYTRsIv_sr7JVBTODD75tZS56FCNGapCU-4)

na

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v3.13.7 (released Feb 08, 2024)
- Platform: Web, MacOS,Desktop,Android
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: desktop
```

**Comment by hariprasadms** [comment]
Hi @skShrikant24 - The issue details provided do not adhere to our recommended issue template. It lacks reproducible steps and screenshots, making it challenging to understand the problem you're encountering. Typically, issues submitted without following the template format are closed as invalid. Kindly adhere to the template and include all relevant details that can aid in investigating the issue. Thank you.
