### ISSUE TITLE
2 to 160 bugs in an instant

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2336]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Two days ago, I was adjusting settings and all of a sudden I went from having 2 bugs to now 160 bugs without making any changes. Seems like an error on the Flutterflow side vs actual bugs as several of these now bugs I had already set up

Thank you!

### Expected Behavior

I wouldn't expect to randomly have items that I've built and created the proper way turn into bugs

### Steps to Reproduce

1. Go inside project
2. Look at 160 bugs
3. Identify how all of the sudden 160 bugs could have been created - is it a specific parameter? did something go missing that caused? Is there an underlying issue? Are there any common themes?

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCsofePrOpkAf8/7UFtUcNzmTWw2MFr8hmMX/MmPiITfIfYFCxGsRbo4zc5tFwzgfD2gR7qyBa63b0ZPGZ5NGECby7ejuR1TOsBhdCEF1E6MPOvJYBDcQ6ayDEg/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Note - Bug Report Code above only applies to one page, not the rest

This has prevented me from pushing my project live - after 1.5 months and over 50 hours of learning the platform and watching YouTube videos to make it work. This is a huge set back that would require a lot of time to resolve. Considered hiring someone but don't want to have to pay for something that wasn't my mistake

### Visual documentation

When I first load the app, it shows 2 bugs and then it goes straight to 160. I'm really not sure what caused this.

![Screenshot 2024-02-12 at 4 21 34 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6a3cdcf8-409c-4390-97b5-f5a5b0f80527/87822f10-892e-45c5-a4dc-da0621dacbe5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YTNjZGNmOC00MDljLTQzOTAtOTdiNS1mNWE1YjBmODA1MjcvODc4MjJmMTAtODkyZS00NWM1LWE0ZGMtZGEwNjIxZGFjYmU1IiwiaWF0IjoxNzA3NzgwMzA2LCJleHAiOjMzMjc4MzQwMzA2fQ.IL89EErvucakm93Te2r4v0BGkJCE5nU-BZ0BxEncFMA "=1095x")

![Screenshot 2024-02-12 at 4 21 47 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fcf1ee90-132c-4322-9c9b-e13f42c6f30d/ccc49b9c-6c2c-484d-8e60-05c147bb9a7e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mY2YxZWU5MC0xMzJjLTQzMjItOWM5Yi1lMTNmNDJjNmYzMGQvY2NjNDliOWMtNmMyYy00ODRkLThlNjAtMDVjMTQ3YmI5YTdlIiwiaWF0IjoxNzA3NzgwMzA2LCJleHAiOjMzMjc4MzQwMzA2fQ.X2TFX0B2RmisNux5F3ibznj2Kw-ivSGp6-hUYzoZTpM "=1075x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Flutterflow
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by lovestar18** [comment]
link to project: https://app.flutterflow.io/project/stars-of-love-i8ygiw?

**Comment by lovestar18** [comment]
As an additional note, when I try to add the "authenticated user" or "userRef"  or "reference user" it's not showing up as an option

<img width="989" alt="Screenshot 2024-02-13 at 7 10 50 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/2057abb3-72bc-4b7f-928e-2d76211b8b89">
<img width="980" alt="Screenshot 2024-02-13 at 7 11 04 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/a6c1a6d6-f8bb-4a3f-8e47-a237c229c84b">

**Comment by lovestar18** [comment]
@hariprasadms - checking in to see if you have any updates or thoughts on the above? Greatly appreciate your help! Thank you!

**Comment by lovestar18** [comment]
@takashiff - checking in to see if you have any updates or thoughts on the above? Greatly appreciate your help! Thank you!

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! Any updates here? I think support was maybe going to reset my instance to where I was on Saturday. Thank you!

**Comment by agreaves** [comment]
Hi @lovestar18, thanks for the report. This appears to be due to the configuration of your project to not enable a users collection. This is likely the setting you were playing around with, and turning it off caused the issues to appear. If you turn it back on and select the `users` collection you should see the issues come back down!

<img width="1230" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/481263a2-8f1a-4be9-9e8b-81ad335c377e">

**Comment by lovestar18** [comment]
That fixed it!! I am so relieved! Thank you SO much!
