### ISSUE TITLE
The text alignment in the "show snack bar" malfunction 

### ISSUE THREAD

**Issue by hao666888** [FlutterFlow/flutterflow-issues#2337]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

as described. The text alignment of the "show snack bar" does not work. The text will always be at the left side of the bar.

### Expected Behavior

center works

### Steps to Reproduce

just create the widget and test the test alignment.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvHlxItNsbQA7qrAY+9V+TwRCDo4a+Ya1upDbCs9CZDoOu9/deOkalBocOmoT2lhHE6Kgj81zNbQhuOSKsE4Fy2cQNVq/pYAWj3MLHq8RqaNCc6wSGpSEd1PIVSf0LujpBYkPfhtLFI72E6UGvPJSXXDN5u/Zwh9f6PHaOI=

### Context

it does not look good.

### Visual documentation

it is simple as described above, no need for images.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:all
- Browser name and version: chrome
- Operating system and version affected: macOS Monterey 12.6.7
```

**Comment by hariprasadms** [comment]
Hi @hao666888 - Thanks for submitting the issue. I can reproduce the issue.
