### ISSUE TITLE
Unable to push to repository due to failed widget. But no Error being displayed

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2338]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i have created pages with a staggeredview widget and there are no errors reported. But when i try to push to repository, i am getting a Failed widget error response and block the push to repository. There is not enough information about the build error as well.

![Screenshot 2024-02-13 at 16 02 03](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ce4530c5-339b-4c21-89e4-97c323393c71/6b30a6a2-e983-4064-ae0b-6278041eb7f4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZTQ1MzBjNS0zMzliLTRjMjEtODllNC05N2MzMjMzOTNjNzEvNmIzMGE2YTItZTk4My00MDY0LWFlMGItNjI3ODA0MWViN2Y0IiwiaWF0IjoxNzA3ODM5ODgwLCJleHAiOjMzMjc4Mzk5ODgwfQ.jK33CXA_ffZIIAr96WCamrPpIE5-85a2Z4jN2Da6yDg "=441x")

![Screenshot 2024-02-13 at 15 58 10](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ff7068d7-d5a5-4734-a563-27c368880839/692bd789-9b72-40b2-afc3-8e72f94d9caf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZjcwNjhkNy1kNWE1LTQ3MzQtYTU2My0yN2MzNjg4ODA4MzkvNjkyYmQ3ODktOWI3Mi00MGIyLWFmYzMtOGU3MmY5NGQ5Y2FmIiwiaWF0IjoxNzA3ODM5ODgwLCJleHAiOjMzMjc4Mzk5ODgwfQ.\_3VpRaXgtQj-jNbo-5qLn-2h-SzU03wqsobn1LOMXYs "=755x")

### Expected Behavior

I should be able to push to repository when there are no errors are displayed.

### Steps to Reproduce

1. Create page
2. Add new column
3. Add staggeredView widget
4. Add query for staggeredview
5. Change height of a staggeredview element by index to show in the pinterest style.
6. Run the project from flutterflow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlPLlvJV2otxE15DuY8BFmjoRMjs3bI0k0+xuZCs8GZT0B4kcYs+kfklUON/nTwlieFqjmj0X/MrRi9/xGME4IQerbb5G/rV+UxXgXk2RVJfSCpS3b3d5EftRJkixy7e7pxMnBPhecV4N2zv7DOfLfHXDQpjBDDInA+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

Yes, I am unable to push the code to repository and work further. There is not enough information about what is the problem that causes build failure.

### Visual documentation

![Screenshot 2024-02-13 at 16 02 03](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4a11a5d7-e599-4c47-b682-b06ba08fc16d/de53915c-cb62-4742-92a4-b92be099bf5c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YTExYTVkNy1lNTk5LTRjNDctYjY4Mi1iMDZiYTA4ZmMxNmQvZGU1MzkxNWMtY2I2Mi00NzQyLTkyYTQtYjkyYmUwOTliZjVjIiwiaWF0IjoxNzA3ODM5ODgwLCJleHAiOjMzMjc4Mzk5ODgwfQ.m67He61OvzbikBDrdty23_12zv6J4_Tzf6Vf9f3LV0s "=441x")

![Screenshot 2024-02-13 at 15 58 10](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7f70e1fe-fd2d-42a8-b68e-9c200e944384/13ae4e16-e8eb-441b-ae75-a7dc30e1600e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZjcwZTFmZS1mZDJkLTQyYTgtYjY4ZS05YzIwMGU5NDQzODQvMTNhZTRlMTYtZThlYi00NDFiLWFlNzUtYTdkYzMwZTE2MDBlIiwiaWF0IjoxNzA3ODM5ODgwLCJleHAiOjMzMjc4Mzk5ODgwfQ.ppN_ZQSIe9k1PYhsbq7cDb2hEBnx5kZRE_GY3vzkPcU "=755x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version: Edge Browser
- Operating system and version affected: MacOS
```

**Comment by takashiff** [comment]
Hi @task-win, thank you for the bug report. There is currently an issue with start/end spacing for the StaggeredView widget. If you remove the spacing from all of your StaggeredViews, you should be able to download and push your code. Thank you for your patience.

**Comment by task-win** [comment]
Hi @takashiff, I have tried your suggestion to remove start spacing and also cross axis spacing. It is still makes it impossible for me to push the code. This is a blocker for our project. The solution suggested did not work. Please help. Thank you,

**Comment by takashiff** [comment]
Hi @task-win, did you remove start/end spacing for all StaggeredView widgets? I took a look at your project and it seems to be working fine now. Thanks.
