### ISSUE TITLE
Infinite Scroll displays previously cached response, does not show correct query

### ISSUE THREAD

**Issue by cheggy** [FlutterFlow/flutterflow-issues#234]
## Expected behavior (required)
If I have a Screen A that gets ALL documents in a collection with a filter,
And another Screen B that gets ALL documents, without a filter, 
If I navigate from screen A to screen B, I expect to see the correct query on Screen B, of all documents in this collection.

## Current behavior (required)

- I have a home screen (Screen A) that has a ListView (nothing else) with infinite scroll that gets all Posts that I have liked (and a button to navigate to another screen).  It is an Inifinite Scroll list,  with a filter, sorted by created date and getting 6 at a time.
- When I open the app and this ListView loads, it loads the Documents that match my query correctly (although it loads ALL matching documents in 1 go, not the 6 I defined in Page Size - I have logged another ticket for this)
- Then I navigate to another screen (ScreenB) that has only a ListView.  This ListView has a Firestore query to get ALL posts, sorted by date, no filter.  When I navigate to this page, it is displaying the same posts as from the previous screen.  The response is cached.
- If I navigate back to screen A, and then go back to screen B, the query now loads correctly.
- I can recreate this 100% of the time.
- I have created new screens with new queries and it happens every time

## To Reproduce (required)

1. Create a screen with a Firestore query on a ListView, with infinite scroll set to match the settings in the screen shot below.  Infinite scroll, page size = 6, listen for changes, filter applied, sort applied/
2. Create a second screen with a ListView query on the SAME COLLECTION, with the same sort, but without the filter.  Also infinite scroll, listen for changes, page size = 6.
3. Open the app on Screen A and observe the documents that load.
4. Navigate to Screen B and notice that the documents that load are the same as from Screen A.  The filter is still applied.  The response is cached.
5. Navigate back to Screen A
6. Navigate back to Screen B.  Notice that the documents now reflect the query correctly.  The filter is no longer applied.

### Bug Report Code
ITFTzMmAsYtIxLRG+KqJdO0wmiYWM0MdXZIRmOtvewgjF774ELMQZ+PBdklpXdSzaHx+D2CWij8x097ev+GWM/AoHw6rfJxq+ZB2dlyjEA8=

## Context (required)
The content displayed to users is incorrect.
It results in users not be able to view the app's content because they can only see a previously filtered version of the app's content.
Users, on first view, never see the new content, so they assume there is nothing new to see.  Everytime they come to the app, they just see the same list.  It never updates because they do not know they need to navigate away and come back to the screen for it to refresh.

## Screenshots / recordings

1. ![image](https://user-images.githubusercontent.com/3022867/207984229-d77065a9-d03d-401c-a1ed-d00fe6d5a284.png)
2. Load screen A.  Notice the posts that load are all like by me (the filter) shown by the red heart.  Also note it is loading way more than the 6 posts I defined.
3. ![image](https://user-images.githubusercontent.com/3022867/207985307-675d863f-a8f8-4c07-9fbd-83254ad300c3.png)
4. I navigate to the screen B that should load all posts, but you can see it is just loading the same posts
5. ![image](https://user-images.githubusercontent.com/3022867/207985420-e011b2dc-2cc4-4c8b-8dd7-e29d45a055d5.png)
6. I navigate back to screen A (same as before)
7.  ![image](https://user-images.githubusercontent.com/3022867/207985474-4ee398bd-126d-4923-aaa3-12a518f2d4f5.png)
8. And now I navigate to screen B again, and we can see now on it's second load, it loads the query correctly, with some posts that are newer that I have not liked.
9. ![image](https://user-images.githubusercontent.com/3022867/207985650-14dbcfc0-46a2-44d3-8e81-3c0611f6818f.png)

## Your environment
Win 11, Chrome, v3.0 December 16 Flutterflow
Also happens in Android Studio Emulator/Debug, also happens in Prod.
Has been happening for a very long time.  I have raised this in the forums, previously here, and also to support.  I have not been given a proper response yet.

**Comment by hariprasadms** [comment]
Hi @cheggy - Closing this issue as it is quite old one and this should be fixed in latest FF builds. Let us know if this issue still persists. We can re-open and investigate the issue. Thanks
