### ISSUE TITLE
Allow list values for native permissions

### ISSUE THREAD

**Issue by ZiyadgodilDev** [FlutterFlow/flutterflow-issues#2341]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm encountering an issue while trying to set the UIBackgroundModes permission in FlutterFlow. Specifically, I need to include the following modes: processing, remote-notification, and voip. However, I'm unsure how to properly configure this permission within FlutterFlow. Can anyone provide guidance on how to accomplish this?

I need to add below permission on iOS

UIBackgroundModes

processing
remote-notification
voip

### Expected Behavior

I need to add permission on iOS like below format but flutter flow not added like that so please give me suggestion about that.

UIBackgroundModes

processing
remote-notification
voip

### Steps to Reproduce

Property List error: Encountered unexpected character s on line 74 while looking for close tag / JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klfLqwIt1xOVc7c/LbcZWgjwvQ357TLJEpu0bWUkbGO/4O7M2YvT4QBFWUuazaHNEJlmKjlsx0tL7vfHhIO4pHE2qf6pcwpZAdBPPbHm6b8mqPrmSX0EmL/1XN2WM0aWJqwp/Js5tWE4hwDmQCt7KST6Cf9qOYwx5e6fDbOY=

### Context

UIBackgroundModes

processing
remote-notification
voip

Please review above permission i want to add permission like
 UIBackgroundModes

processing
remote-notification
voip

But,When i add permission flutterflow automatically added tag after tag.

### Visual documentation

[flutter_callkeep: ^0.3.3](https://pub.dev/packages/flutter_callkeep)

### Additional Info

![Screenshot 2024-02-14 at 12 11 00 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/35526e45-8ae4-4809-ad61-54f51b530788/72bedf7b-47cd-40b9-ad20-b779aadc4a21?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNTUyNmU0NS04YWU0LTQ4MDktYWQ2MS01NGY1MWI1MzA3ODgvNzJiZWRmN2ItNDdjZC00MGI5LWFkMjAtYjc3OWFhZGM0YTIxIiwiaWF0IjoxNzA3OTA3MDA0LCJleHAiOjMzMjc4NDY3MDA0fQ.s0jNkgthmWNIsSauQiNIGCXvLBczapR06EqLBaLJRRA)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: flutterflow
- Browser name and version: chrome and 121.0.6167.160 (Official Build) (x86_64)
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment]
Hi @ZiyadgodilDev - At this stage, the permissions in list type, not able to add through FF editor. However, You can  update this through downloaded code. I can mark this issue as feature enhancement request. Thanks

**Comment by leighajarett** [comment]
We have added this as a feature in our backlog, but closing here as this tracker is for reproducible bugs
