### ISSUE TITLE
Firebase Analytics: User ID not set

### ISSUE THREAD

**Issue by bfmill253** [FlutterFlow/flutterflow-issues#2343]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently the `user` parameter used when sending firebase events is set to `'unset'` when the user is authenticated.

Looking at `backend > firebase_analytics > analytics.dart:15`

```dart
  parameters.putIfAbsent(
      'user', () => currentUserUid.isEmpty ? currentUserUid : 'unset');
```

If currentUserUid is empty, it returns currentUserUid, otherwise, it returns the string 'unset'

### Expected Behavior

We should have the user id set as a parameter:

```dart
parameters.putIfAbsent(
      'user', () => !currentUserUid.isEmpty ? currentUserUid : 'unset');
```

Even better, we should be using `setUserId` if currentUserUid exists:

[https://firebase.google.com/docs/analytics/userid#dart](https://firebase.google.com/docs/analytics/userid#dart)

This will make analytics reports significantly easier to genereate

### Steps to Reproduce

1. Enable analytics
2. Trigger analytics event/action while authenticated
3. Observe missing user parameter

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Olcr1z89goe5E176JKe9agjgXKUg8U4ZM1+pHYAAbCJPNGu4MPsneVFRuZr2lT3NqPk38+WMd7PfquNr1N/cDNkydbL1yz89IaAzJXmCXb5iqDqWdfW1TO5lMGkyd5LaznBMlBO5hL1Iu3UOUJ+iXEy7ANpDEPEdEGfilKdeK2SrDX1iXc2URm05KZDPz

### Context

We have exported our analytics to BigQuery in order to generate reports and run user behavior analytics. We noticed we are unable to map events/sessions back to our firebase auth user instances due to missing user ids.

### Visual documentation

Example of the params sent from an auth guarded screen:

![bug-1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/61a41db8-f0b4-492e-8f5c-a54c1bd7ddf4/7e5a672f-de8b-4f99-8a27-0f622f5613a4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MWE0MWRiOC1mMGI0LTQ5MmUtOGY1Yy1hNTRjMWJkN2RkZjQvN2U1YTY3MmYtZGU4Yi00Zjk5LThhMjctMGY2MjJmNTYxM2E0IiwiaWF0IjoxNzA3OTM1MTc2LCJleHAiOjMzMjc4NDk1MTc2fQ.WJbIzpg--XVgnZeFp2K3_N1mfzLyqqwTwL75NwRSlhs)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: iOS, Android
- Browser name and version: Chrome
- Operating system and version affected: Windows 10
```

**Comment by carmenchargely** [comment]
We're also experiencing this issue.

**Comment by rzambroni** [comment]
Hey everyone, sorry for the delayed response! this bug was confirmed and passed to the team so they can take a look, we will update the status here once it is fixed.

Thanks for the report!

**Comment by carmenchargely** [comment]
Thanks @rzambroni ! Any updates would be appreciated. Is there an eta for when this will be prioritized?
