### ISSUE TITLE
Google Sign up bug on Android

### ISSUE THREAD

**Issue by eduriftio** [FlutterFlow/flutterflow-issues#2345]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Google Sign up is broken after the Flutterflow update because it worked before on Android only. iOS works fine

### Expected Behavior

Be able to Sign in and Sign up with Google on Android

### Steps to Reproduce

1. Create an app and setup Google sign in
2. Download the Android app and test Google sign up popup

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no link

### Context

Google sign up pop up is not working on Android

E/flutter (11276): \\\[ERROR:flutter/runtime/dart_vm_initializer.cc(41)\\\] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (11276): #0 GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
E/flutter (11276):
E/flutter (11276): #1 GoogleSignIn.\\\_callMethod (package:google_sign_in/google_sign_in.dart:278:30)
E/flutter (11276):
E/flutter (11276): #2 GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
E/flutter (11276):
E/flutter (11276):

### Visual documentation

[https://drive.google.com/file/d/1vcWSxutySuu8WYvHbvsDq9YYPed9CFA\\\_/view?usp=sharing](https://drive.google.com/file/d/1vcWSxutySuu8WYvHbvsDq9YYPed9CFA\_/view?usp=sharing)

[https://drive.google.com/file/d/1bb12GD1DFxSBn30spbUd_1RuxFP917Au/view?usp=sharing](https://drive.google.com/file/d/1bb12GD1DFxSBn30spbUd_1RuxFP917Au/view?usp=sharing)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:Web
- Browser name and version: Chroma
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment]
Hi @eduriftio - Thanks for submitting the issue. You should generate SH1 key and to the project in firebase console. Follow below doc. Once keys are added successfully, regenerate the config files in FlutteFlow firebase config section and you are good to go. 

<img width="747" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6fc6ea46-2ce7-4e73-afb4-c76ae045a7b5">

https://docs.flutterflow.io/data-and-backend/firebase/authentication/initial-setup#1.-generate-the-sha-1-key
