### ISSUE TITLE
(Crucial) AdMob interstitial ad still shows (Test Ads) even when turned off in FF

### ISSUE THREAD

**Issue by albluwi1987** [FlutterFlow/flutterflow-issues#2350]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,
Before I Published the app to Apple App Store I've turend off (Show Test Ads) in FF

![‏لقطة الشاشة ١٤٤٥-٠٨-٠٦ في ١ ٤٧ ٠٥ م](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ed80e786-2681-4434-959f-43ba4cb3f0ba/d931140d-ebc0-492b-8618-da71852e4503?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZDgwZTc4Ni0yNjgxLTQ0MzQtOTU5Zi00M2JhNGNiM2YwYmEvZDkzMTE0MGQtZWJjMC00OTJiLTg2MTgtZGE3MTg1MmU0NTAzIiwiaWF0IjoxNzA4MDgyNTA1LCJleHAiOjMzMjc4NjQyNTA1fQ.hmwwsve6mKo4JsADP1EIUvsmhGr0o866sBko_tA7RzY "=2172x")

But After Downloading my app from the store , it's still showing Test Ads !?

[https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/4ee49062-b9fd-479c-807a-10eede7f0a09](https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/4ee49062-b9fd-479c-807a-10eede7f0a09)

### Expected Behavior

It Supposed to show Real Ads !

### Steps to Reproduce

1. Create 2 pages (page 1 have navigation button to page 2)
2. set the actions of (Show/Load Interstitial Ad) before navigating to page 2
3. Turn off (show test ads)
4. Test it (Run the App)
5. also upload the to apple app connect and test it on real device (TestFlight)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfLl/Y11rt9F7a6Jd/pVoDs5KWY/bZ001uxBaCosfZT2BLMcec/RVERVcN++Sm9MJWeGp2oW0ejehvLXN8c3Nk2qQKpE+btuQxfzRj26b4i7FJWgYkRSGflMGEuP0aaNvxMlNbNqSUYi112QCei+cDPvQ+frPlgwDq/LZO4=

### Context

it's effect my app very badly as it's already published in (apple) app store

### Visual documentation

![‏لقطة الشاشة ١٤٤٥-٠٨-٠٦ في ١ ٤٧ ٠٥ م](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b445772f-2041-472d-b41c-d8076d1d6977/83d7c8c2-2de9-41f7-9136-16311fae445f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNDQ1NzcyZi0yMDQxLTQ3MmQtYjQxYy1kODA3NmQxZDY5NzcvODNkN2M4YzItMmRlOS00MWY3LTkxMzYtMTYzMTFmYWU0NDVmIiwiaWF0IjoxNzA4MDgyNTA1LCJleHAiOjMzMjc4NjQyNTA1fQ.yuYMP4RCYhc5u4jZSHRzKioQg44OTyx73Z_8qSVajQw "=2172x")

[https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/def96879-db92-4d15-b50f-1f7c9185c043](https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/def96879-db92-4d15-b50f-1f7c9185c043)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform:Web
- Browser name and version: Chrome 121.0.6167.184
- Operating system and version affected: macOS Ventura 13.6.4
```

**Comment by hariprasadms** [comment]
Hi @albluwi1987 - Thanks for submitting the bug. I was able to reproduce the issue. However, I need a bit more information. Did you notice the ad displaying after the second click instead of the first click?

**Comment by albluwi1987** [comment]
Hi @hariprasadms 
Thanks for responding...I actually didn't understand your question!? Could you explain more what did you mean!

**Comment by hariprasadms** [comment]
When you click on the button to load and display the ad, does the ad show up on the first click or the second click?

**Comment by albluwi1987** [comment]
No in my case from the first click it shows the ad i have no problem with that

**Comment by aemelyanovff** [comment]
@albluwi1987 "Show Test Ads" is `true` when you load the ad in the action "On Page Load" action. If you set it to `false` it should show real ads.

**Comment by albluwi1987** [comment]
> @albluwi1987 "Show Test Ads" is `true` when you load the ad in the action "On Page Load" action. If you set it to `false` it should show real ads.

Hello, did you look to at pictures that I've attached earlier! I've already set (Show Test Ads) to FALSE before deploying and publishing my app to the store YET it shows Test Ads ???

**Comment by aemelyanovff** [comment]
> > @albluwi1987 "Show Test Ads" is `true` when you load the ad in the action "On Page Load" action. If you set it to `false` it should show real ads.
> 
> Hello, did you look to at the pictures that I've attached earlier! I've already set (Show Test Ads) to FALSE before deploying and publishing my app to the store YET it shows Test Ads ???

It's `false` in the action on tapping a button. The initial load happens in the "On Page Load" action, and there it's `true`.

![Screenshot 2024-02-20 at 6 16 22 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/f4c509b7-c9b3-4d72-b811-84744e16809f)

**Comment by albluwi1987** [comment]
> > > @albluwi1987 "Show Test Ads" is `true` when you load the ad in the action "On Page Load" action. If you set it to `false` it should show real ads.
> > 
> > 
> > Hello, did you look to at the pictures that I've attached earlier! I've already set (Show Test Ads) to FALSE before deploying and publishing my app to the store YET it shows Test Ads ???
> 
> It's `false` in the action on tapping a button. The initial load happens in the "On Page Load" action, and there it's `true`.
> 
> ![Screenshot 2024-02-20 at 6 16 22 PM](https://private-user-images.githubusercontent.com/92294640/306443229-f4c509b7-c9b3-4d72-b811-84744e16809f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjI5OTQsIm5iZiI6MTcwODU2MjY5NCwicGF0aCI6Ii85MjI5NDY0MC8zMDY0NDMyMjktZjRjNTA5YjctYzliMy00ZDcyLWI4MTEtODQ3NDRlMTY4MDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAwNDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZmE3N2RkMjBkOGNiNzMxZjM3ZjEyNDVhMTVkODYyOTg1YjkyZWI1MDViZDIyMTRhMzVkODNhYjgzNjY1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdPDKJdiWzhDGnTMxVAvkvIeCDDhLRwGlxiVJar5Kvk)

My bad , you were right , thanks for the help
