### ISSUE TITLE
Window without any action to proceed

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2351]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A window opens when trying to work further stating that a team is already working on the project. But it does not allow me to close or click on any buttons that are available

### Expected Behavior

1. Able to go to teams.
2. Able to go to home

### Steps to Reproduce

1. Go to project which a team is collaborating with outsider
2. A team member is working on the project already
3. The collaborator is trying to commit the code
4. A pop up will open that project is in use
5. No possibility to exit from this screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No bug report code -

### Context

Block to proceed with coding. I have to reload the project to work

### Visual documentation

![ScreenRecording2024-02-16at13 18 06-ezgif com-video-to-gif-converter](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/09212986-7583-4d9d-8a42-538109a467d5/a96b1d7a-0f62-4b39-9786-d1c9639a9349?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wOTIxMjk4Ni03NTgzLTRkOWQtOGE0Mi01MzgxMDlhNDY3ZDUvYTk2YjFkN2EtMGY2Mi00YjM5LTk3ODYtZDFjOTYzOWE5MzQ5IiwiaWF0IjoxNzA4MDg5MTExLCJleHAiOjMzMjc4NjQ5MTExfQ.S0hiPehVQdYDFb6vo0g2lajC5hq2G9x7k0d3isjdjfc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @task-win, sorry about that! I believe that happens when you are over the code editor. This will be fixed in the upcoming release!
