### ISSUE TITLE
New version of Flutter Flow doesn't work with newest Google Chrome.

### ISSUE THREAD

**Issue by kamil220** [FlutterFlow/flutterflow-issues#2352]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open a page, that contains a List view with a component and horizontal axis I receive a massive amount of errors (in the console log), and then the page stops working.

This issue occurs only in google chrome. Disabling extensions and open flutter-flow with incognito mode don't work.

**Error message:** Shader compilation error
**Google chrome version:** 121\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.0.6167.184 (Official Build) (x86_64)
**Device:** Macbook Sonoma 14.3

![CleanShot 2024-02-16 at 17 11 20](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e36f7cbf-2c1d-47fd-ba35-a085840ee4d4/81255f4a-019b-4f4a-8d37-b04086908b54?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMzZmN2NiZi0yYzFkLTQ3ZmQtYmEzNS1hMDg1ODQwZWU0ZDQvODEyNTVmNGEtMDE5Yi00ZjRhLThkMzctYjA0MDg2OTA4YjU0IiwiaWF0IjoxNzA4MTAxNTM5LCJleHAiOjMzMjc4NjYxNTM5fQ.UH6fNMjRghZtNAN_VECYzgw3kIBlhHaxUB6KCT4QULY)

### Expected Behavior

The site should work normally. In case of a compilation error, we should get an error instead of a huge amount of console logs.

### Steps to Reproduce

Hard to say, because, the problem started after 2 weeks of doing nothing.
My internal investigation shows, that the error appear in ListView component.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiOfl3ItIseZE7pSJde9VmSQvMjt6U4Ee0OtHZCs8GqLuPe0UWMzBUBFUOPGqY2xII2GkhmQX/Mr4k/OfGvc3EwuubaI4+rlQczrzUmCtMb6sBa63b0dAP5lRCG6PyKWo3BInJuhtL1Fk3WGmP+SAY3XtQIz4IVVBQuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I can't open flutterflow via google chrome and via PWA app.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/16455814/5983cbfe-8b96-4f07-a1fd-2fea4726596c](https://github.com/FlutterFlow/flutterflow-issues/assets/16455814/5983cbfe-8b96-4f07-a1fd-2fea4726596c)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 - Flutter 3.13.7
- Platform: Web / MacOS Desktop
- Browser name and version: Google Chrome v.121.0.6167.184 (Official Build) (x86_64)
- Operating system and version affected: MacOS Sonoma 14.3
```

**Comment by kamil220** [comment]
> @kamil220 yes, this was pointed out [here](https://github.com/FlutterFlow/flutterflow-issues/issues/2349)! Cheers mate

A little different steps to reproduce the problem, but it is exactly the same error. Thank you!

**Comment by kamil220** [comment]
It seems that the issue from the thread mentioned by @Kato-iOS was fixed, but here problem still exists.

**Comment by hariprasadms** [comment]
Hey @kamil220 - Thanks for following up. Some related fixes went live around 6 hours ago, so hoping the update did the trick!  Could you take a quick time to check and let me know if issue is fixed now? Still stuck? No worries! Just shoot me some more details about what's happening, and I'll do my best to help you out.

**Comment by SimonSoftware** [comment]
Same problem

**Comment by takashiff** [comment]
Hi @kamil220, please let me know if you still experience this issue after upgrading to Chrome version `122.0.6261.94`. I'm currently unable to reproduce it on my system. Thanks

**Comment by kamil220** [comment]
Unfortunately still has the same error.

**Comment by kamil220** [comment]
Hey,

I haven't chance to try, but It seems, that after the last Chrome update, everything working properly. We can close this issue :)
