### ISSUE TITLE
Flutterflow rais Error (and i cant run the app) when there is no error!

### ISSUE THREAD

**Issue by NadavTraub** [FlutterFlow/flutterflow-issues#2354]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when im sending conditional action into a component the flutterflow rais an error
but when i press the error twice (to see where is the error) it opens the action board and then becoming green
but when i close it to run the app it becoming red again

### Expected Behavior

no raising error

### Steps to Reproduce

1. create a component with action as param
2. send conditional action as the param
3. try to run the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi/Lq25VNseFY+KXfYe0w9CkvGUMcWOdEl+tuZwgbIoznBqQAYuPCblFuZ9+9aVNcJWaj8XodwujWud/XN/ECMkyYfIA4+rgJEzvke2iiSpCYDM20QnElEtxMGkCO08CzmCVSVdNZWk5n1HGAfNzLSi7DFOu/Zwh9f6PHaOI=

### Context

im trying to run the app (sometimes its working and i can tell that there is no issue with the logic)

### Visual documentation

![Screenshot 2024-02-17 at 0 32 46](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b37a89b5-5c4d-4bd7-baf2-e2f1116688d8/eab9b7d7-549d-4e08-811a-3300c9402562?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMzdhODliNS01YzRkLTRiZDctYmFmMi1lMmYxMTE2Njg4ZDgvZWFiOWI3ZDctNTQ5ZC00ZTA4LTgxMWEtMzMwMGM5NDAyNTYyIiwiaWF0IjoxNzA4MzUxNjUxLCJleHAiOjMzMjc4OTExNjUxfQ.5QRmjzKWSoMK9xEvty4Pe6rQ4nww6Ax4u-T4D543YbE "=703x")

![Screenshot 2024-02-17 at 0 32 54](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5dc1e2c0-1834-44d1-9d61-b3e2ff154047/9d71adf1-ab16-4e9b-a3e5-0b367d032c06?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ZGMxZTJjMC0xODM0LTQ0ZDEtOWQ2MS1iM2UyZmYxNTQwNDcvOWQ3MWFkZjEtYWIxNi00ZTliLWEzZTUtMGIzNjdkMDMyYzA2IiwiaWF0IjoxNzA4MzUxNjUxLCJleHAiOjMzMjc4OTExNjUxfQ.Ll1PWRvmcAIAtSt2RZevgYm69FQZ_pFtxnVnWUkvhx8 "=383x")

![Screenshot 2024-02-17 at 0 33 02](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/28aefd16-ad14-4851-b7f5-a347e47c967f/5b2cb716-7532-4c61-a6d4-48b3a6d81358?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yOGFlZmQxNi1hZDE0LTQ4NTEtYjdmNS1hMzQ3ZTQ3Yzk2N2YvNWIyY2I3MTYtNzUzMi00YzYxLWE2ZDQtNDhiM2E2ZDgxMzU4IiwiaWF0IjoxNzA4MzUxNjUxLCJleHAiOjMzMjc4OTExNjUxfQ.wiIz72mESz1TaceKvo6BKgOK6ur-7MaHje_IYIrGD7E "=464x")

![Screenshot 2024-02-17 at 0 33 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cba98125-4f08-4ad4-9b78-2096aeecb118/27505387-10ee-42cf-985a-9fa2d8a42977?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jYmE5ODEyNS00ZjA4LTRhZDQtOWI3OC0yMDk2YWVlY2IxMTgvMjc1MDUzODctMTBlZS00MmNmLTk4NWEtOWZhMmQ4YTQyOTc3IiwiaWF0IjoxNzA4MzUxNjUxLCJleHAiOjMzMjc4OTExNjUxfQ.00U_pQtg-6_zZ4ZWwamVTS65KAiu76DRaJldjaFdwso "=1091x")

![Screenshot 2024-02-17 at 0 33 23](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/58603407-4db1-45e6-bfe4-7d7e87eb9a72/34c385ac-92c3-4a86-85cf-2d76840df206?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ODYwMzQwNy00ZGIxLTQ1ZTYtYmZlNC03ZDdlODdlYjlhNzIvMzRjMzg1YWMtOTJjMy00YTg2LTg1Y2YtMmQ3Njg0MGRmMjA2IiwiaWF0IjoxNzA4MzUxNjUxLCJleHAiOjMzMjc4OTExNjUxfQ.6e5Fmu_JW_uevB65OXU7k7lwjbOFyQlC3hYGb5ebZX8 "=928x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web, MacOS Desktop
- Browser name and version:
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @NadavTraub - Thanks for posting the issue. I see there is some UI issue at FlutterFlow editor. Your project downloaded code looks fine and no errors. That means its indeed a project specific bug.

**Comment by NadavTraub** [comment]
Hi, when do you think you will fix the bug? It's blocking me from moving forward... I can't run the app!

**Comment by hariprasadms** [comment]
Hi, The issue is with Dev team now. It will be looked into based the priority. We will update here soon. Thanks

**Comment by NadavTraub** [comment]
@sbis04 hey would love for an update:)

**Comment by NadavTraub** [comment]
@hariprasadms ?

**Comment by NadavTraub** [comment]
hey @hariprasadms @sbis04 can anyone update?? i cant run my project anymore because of this errors!!

**Comment by josescgar** [comment]
Related/duplicated https://github.com/FlutterFlow/flutterflow-issues/issues/2464
