### ISSUE TITLE
Toggle Icon cannot set toggle value from variable when in a component

### ISSUE THREAD

**Issue by sheprograms** [FlutterFlow/flutterflow-issues#2355]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a toggle icon nested within a component. It should show whether the authenticated user has this item in their list of favorites. However, I cannot access any variables from within the Toggle Value configuration panel. The Source list is blank, and searching does not return any results.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fa708319-e970-4f8c-8686-86cc6effb2d5/94ba90b3-0f84-4ef4-ab36-41747629ba11?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYTcwODMxOS1lOTcwLTRmOGMtODY4Ni04NmNjNmVmZmIyZDUvOTRiYTkwYjMtMGY4NC00ZWY0LWFiMzYtNDE3NDc2MjliYTExIiwiaWF0IjoxNzA4MzUyMDY1LCJleHAiOjMzMjc4OTEyMDY1fQ.imASPRgG4T1qc9KnaZUA77mG4ubeXenK5eY8xdmpigU "=837x")

### Expected Behavior

I should be able to access component parameters as variables to set the dynamic value of the toggle value just like I can if the toggle icon isn't within a component.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a7d88733-4db3-4eac-b12d-497e2cc7eb66/4f0cf7f0-e818-4c77-8ca0-f0f4c444d33b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hN2Q4ODczMy00ZGIzLTRlYWMtYjEyZC00OTdlMmNjN2ViNjYvNGYwY2Y3ZjAtZTgxOC00Yzc3LThjYTAtZjBmNGM0NDRkMzNiIiwiaWF0IjoxNzA4MzUyMDY1LCJleHAiOjMzMjc4OTEyMDY1fQ.7a9xfMkLmZeL63t3iXVvKJcJv5xBtbEYmJ7cb4J2jFk "=859x")

### Steps to Reproduce

1. Create a projects and a users schema, and add a favorites list of projects to the users schema.
2. On a new screen, create a list view to show all projects
3. Within the list view, add a card. Within the card, add a toggle icon. Set the value to true if the authenticated user's favorite list includes the current project.
4. Convert the card to a component.
5. Pass in the authenticated user's favorite list as a parameter to the component. Delete the auto-generated parameter for the toggle icon
6. Attempt to set the toggle icon to true if the authenticated user's favorite list includes the current project.
   Current behavior: the variable list will be blank.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkcn635NgrsMA1ar2a+9Vv2EvJj5/aK00ttluGBYjfaLyDYkIec/6PxNCTtOrTX9melmmp14E+cr5j+GWOvQCGzuBGZtywcxUbxXwRjqhb6mTF7uOQ3Z8MJtXClCZyLWviBIlNbd1S3wm6juMf/K+QjbvH6bODmowSq/LZO4=

### Context

I'm trying to create a reusable view of a project so that I can have a consistent look and feel to project lists across the application. I wanted to use list tiles like this in at least four different locations. This issue is leading to me duplicating a lot of "code" instead of using a reusable component once and keeping my application DRY. When I need to adjust this part of my app as I get design feedback, I'll have to make changes in multiple places, adding time and complexity.

### Visual documentation

Images included

![Screenshot 2024-02-17 at 2 26 49 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e946d466-9767-4eae-b254-3418d2368d58/9a18abe5-1174-4829-b0a5-e452e86f9b72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lOTQ2ZDQ2Ni05NzY3LTRlYWUtYjI1NC0zNDE4ZDIzNjhkNTgvOWExOGFiZTUtMTE3NC00ODI5LWIwYTUtZTQ1MmU4NmY5YjcyIiwiaWF0IjoxNzA4MzUyMDY1LCJleHAiOjMzMjc4OTEyMDY1fQ.qyDHzxB0zNqSxk_vqEPgRVqOLWj7rhKcwCbUtxU3nsw "=837x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 121.0.6167.160
- Operating system and version affected: Ventura 13.4
```

**Comment by sheprograms** [comment]
I needed to delete this toggle icon so that I could continue to build and test my project. I've regenerated a bug report code on the round container that would contain it.

IT4gkcn635NgrsMA1ar2a+9Vv2EvJj5/aK00sd4bGA0dCJzuPLMQdvXsUBRWXdelS3NlPkSmmTkCpsqNkvGWMsYoaBycGqJC+KtpWhbiLUSQQZOBCajtR3RDJ/pjf0OB0MKRvRV/B7N0WGBn3ziTe/PIVjbZGKLzIlFISq/LZO4=

**Comment by hariprasadms** [comment]
Hi @sheprograms - Thank you for bringing this issue to our attention. I understand the problem you're encountering. The toggle variable doesn't seem to have access to component parameters when it's within a component. The only workaround currently seems to be mapping the value from the application state. I'll make a note of this bug. Thanks again!

**Comment by leighajarett** [comment]
Hi there! I think for you purpose, I think you should use a conditional builder that build out two different icon buttons based on the condition

**Comment by lifesights** [comment]
I don't see a "thumbs-up" on this bug report, but I just spent the last hour+ trying to figure out why I can't set an initial value for the ToggleIcon in my component, also for a FavIcon toggle -- looks like a similar problem.   

We need to be able to set the value of the ToggleIcon within the component, ideally from a component parameter.

**Comment by leighajarett** [comment]
Sorry for the UX confusion! That's definitely frustrating. Are you able to use the conditional builder as mentioned above?

**Comment by ColeDrain** [comment]
@leighajarett that's not the main issue though.
I think the purpose of a toggle icon as described in its tooltip is:

> Sets the toggle value from the selected Firestore field and also creates an action
setting the Firestore field once the widget is toggled.

But it doesn't seem to fulfill this or we can't seem to link it to a boolean.
The main point is toggling a boolean variable in firestore.

**Comment by helloheesu** [comment]
I'm facing the same issue. I have achieved my goal with conditional builder anyway, but it would be way easier if I could use component parameter in toggle icon. When I use conditional builder I have to set icon size individually which is quite a hassel.
