### ISSUE TITLE
Failed Step: Build AAB with Flutter

### ISSUE THREAD

**Issue by Jonatasales** [FlutterFlow/flutterflow-issues#2358]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Codemagic Deploy Output
Failed Step: Build AAB with Flutter

Get package "com.mycompany.ieqbahia" latest build number from track "production"
Found latest version code from "production" track: 1
Resolving dependencies...
  \\\_fe_analyzer_shared 61.0.0 (67.0.0 available)
  \\\_flutterfire_internals 1.3.16 (1.3.21 available)
  analyzer 5.13.0 (6.4.1 available)
  cached_network_image 3.2.1 (3.3.1 available)
  cached_network_image_platform_interface 1.0.0 (4.0.0 available)
  cached_network_image_web 1.0.1 (1.1.1 available)
  cloud_firestore 4.13.1 (4.15.4 available)
  cloud_firestore_platform_interface 6.0.5 (6.1.5 available)
  cloud_firestore_web 3.8.5 (3.10.4 available)
  collection 1.17.2 (1.18.0 available)
  ffi 2.1.0 (2.1.2 available)
  firebase_analytics 10.7.4 (10.8.5 available)
  firebase_analytics_platform_interface 3.8.4 (3.9.5 available)
  firebase_analytics_web 0.5.5+11 (0.5.5+17 available)
  firebase_auth 4.15.2 (4.17.4 available)
  firebase_auth_platform_interface 7.0.8 (7.1.4 available)
  firebase_auth_web 5.8.11 (5.9.4 available)
  firebase_core 2.24.2 (2.25.4 available)
  firebase_core_web 2.10.0 (2.11.4 available)
  firebase_crashlytics 3.4.8 (3.4.14 available)
  firebase_crashlytics_platform_interface 3.6.16 (3.6.21 available)
  firebase_performance 0.9.3+8 (0.9.3+13 available)
  firebase_performance_platform_interface 0.1.4+16 (0.1.4+21 available)
  firebase_performance_web 0.1.4+16 (0.1.4+21 available)
  flutter_animate 4.1.1+1 (4.5.0 available)
  flutter_blurhash 0.7.0 (0.8.2 available)
  flutter_lints 3.0.0 (3.0.1 available)
  font_awesome_flutter 10.6.0 (10.7.0 available)
  go_router 7.1.1 (13.2.0 available)
  google_fonts 4.0.3 (6.1.0 available)
  google_identity_services_web 0.2.2 (0.3.0+2 available)
  google_sign_in 6.1.5 (6.2.1 available)
  google_sign_in_android 6.1.20 (6.1.21 available)
  google_sign_in_ios 5.6.4 (5.7.4 available)
  google_sign_in_platform_interface 2.4.2 (2.4.5 available)
  google_sign_in_web 0.12.1 (0.12.3+2 available)
  http 0.13.6 (1.2.1 available)
  image 4.0.17 (4.1.7 available)
  intl 0.18.1 (0.19.0 available)
  iregexp 0.1.1 (0.1.2 available)
  js 0.6.7 (0.7.1 available)
  json_path 0.6.2 (0.7.0 available)
  mask_text_input_formatter 2.4.0 (2.9.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.12.0 available)
  octo_image 1.0.2 (2.0.0 available)
  path 1.8.3 (1.9.0 available)
  path_provider 2.0.14 (2.1.2 available)
  path_provider_android 2.0.25 (2.2.2 available)
  path_provider_foundation 2.2.2 (2.3.2 available)
  path_provider_linux 2.1.11 (2.2.1 available)
  path_provider_platform_interface 2.0.6 (2.1.2 available)
  path_provider_windows 2.1.7 (2.2.1 available)
  petitparser 5.4.0 (6.0.2 available)
  pigeon 11.0.1 (17.0.0 available)
  plugin_platform_interface 2.1.6 (2.1.8 available)
  pointer_interceptor 0.9.3+7 (0.10.1 available)
  provider 6.0.5 (6.1.1 available)
  rfc_6901 0.1.1 (0.2.0 available)
  shared_preferences_foundation 2.3.4 (2.3.5 available)
  shared_preferences_platform_interface 2.3.1 (2.3.2 available)
  shared_preferences_web 2.2.1 (2.2.2 available)
  sign_in_with_apple 4.3.0 (5.0.0 available)
  sqflite 2.2.6 (2.3.2 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.6.0 (0.7.0 available)
  timeago 3.2.2 (3.6.1 available)
  url_launcher 6.1.10 (6.2.4 available)
  url_launcher_android 6.0.27 (6.3.0 available)
  url_launcher_ios 6.1.4 (6.2.4 available)
  url_launcher_linux 3.0.6 (3.1.1 available)
  url_launcher_macos 3.0.7 (3.1.0 available)
  url_launcher_platform_interface 2.1.2 (2.3.2 available)
  url_launcher_web 2.1.0 (2.2.3 available)
  url_launcher_windows 3.0.8 (3.1.1 available)
  uuid 3.0.7 (4.3.3 available)
  web 0.1.4-beta (0.5.0 available)
  webview_flutter 4.0.5 (4.7.0 available)
  webview_flutter_android 3.3.1 (3.15.0 available)
  webview_flutter_platform_interface 2.0.2 (2.10.0 available)
  webview_flutter_wkwebview 3.1.1 (3.12.0 available)
  webviewx_plus 0.3.3 (0.4.1 available)
  win32 5.1.1 (5.2.0 available)
  xml 6.3.0 (6.5.0 available)
  youtube_player_iframe_web 2.0.2 (3.0.0 available)
Got dependencies!

Upgrading build.gradle
Running Gradle task 'bundleRelease'...
Note: /Users/builder/.pub-cache/hosted/pub.dev/cloud_firestore-4.13.1/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Font asset "fa-brands-400.ttf" was tree-shaken, reducing it from 189684 to 1912 bytes (99.0% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 912 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-solid-900.ttf" was tree-shaken, reducing it from 394668 to 2220 bytes (99.4% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-regular-400.ttf" was tree-shaken, reducing it from 63348 to 1608 bytes (97.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 5800 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
  Execution failed for task ':app:signReleaseBundle'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.FinalizeBundleTask$BundleToolRunnable
> Failed to read key \\*\\*\\*\\*\\*\\*\\*\\* from store "/tmp/keystore.keystore": No key with alias '\\*\\*\\*\\*\\*\\*\\*\\*' found in keystore /tmp/keystore.keystore

* Try:

> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at [https://help.gradle.org](https://help.gradle.org)

BUILD FAILED in 2m 38s
Running Gradle task 'bundleRelease'... 159.1s
Gradle task bundleRelease failed with exit code 1

Build failed :|
Step 7 script `Build AAB with Flutter` exited with status code 1

### Expected Behavior

It was successful and the implementation on Google Play was completed.

### Steps to Reproduce

I can't deploy the application to Google Play through Flutterflow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failed Step: Build AAB with Flutter

### Context

I can't deploy the application to Google Play through Flutterflow.

### Visual documentation

Na implantação do aplicativo na aba de mobile deployment.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 (lançado em 15 de fevereiro de 2024)
- Platform: Web
- Browser name and version: Safari Versão 17.3 (17617.2.4.11.9, 17617)
- Operating system and version affected: macOS Monterey 12.7.3
```

**Comment by hariprasadms** [comment]
Hi @Jonatasales - This issue should be escalated to the support team initially, as it is specific to the project and involves mobile app deployment related issues. Please contact the support team first and return here once you have received confirmation from them. Thank you.

**Comment by Jonatasales** [comment]
Prezados,

Estou seguindo orientações da equipe do flutterflow.

Por isso registrei a ocorrência.

*Jônatas Sales Nery de Souza*
71 3622 2653 (Residencial)
71 99107 4906 (Celular Claro)




Em ter., 20 de fev. de 2024 às 13:39, Hari ***@***.***>
escreveu:
