### ISSUE TITLE
Custom data types and cloud functions

### ISSUE THREAD

**Issue by damianfraire** [FlutterFlow/flutterflow-issues#2359]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using a specific cloud function to list customer stripe payment methods. This function retrieves the methods and returns a custom data type list that contains payment methods attributes in a <String, dynamic> format. i.e. {"last4": "4444", "default": true, "expirationMonth": 4}. Then, I used this result data type list to populate a variable that then populates a ListView. 

Everything works fine in FlutterFlow test mode and run mode. The problem is when I export the code and run it in an emulator or my phone using android studio. It compiles without issues, but when I go to the section to run the cloud function, I get the below error message and it does not work.

"type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>.

The error references the code that takes care of manipulating the cloud function response and adding it to the custom data type, using the "fromMap" custom data type method:

_model.listPaymentMethodsOutput =
    ListUserStripePaymentMethodsCloudFunctionCallResponse(
  data: (result.data as List)
      .map((d) => StripePaymentMethodStruct.fromMap(d))
      .toList(),
  succeeded: true,
  resultAsString: result.data.toString(),
  jsonBody: result.data,
);

I had to hardcode the data type passed like below in order to get it working in the actual app.

.map((d) => StripePaymentMethodStruct.fromMap({
              "last4": d["last4"] as String?,
              "brand": d["brand"] as String?,
               ..... etc

### Expected Behavior

It should consistently work in FlutterFlow test/run mode and the actual app.

### Steps to Reproduce

1. create cloud function that returns a list of <String, dynamic> (mix different dynamic types).
2. create a custom data type to receive the cloud function result.
3. execute cloud function using an action with an action output variable.
4. download the code and execute in android studio.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjc+A5ZVNxd8B15CMbccxgj0vJnp7TL07ttYbZxUjIuPtBJh/Zcj7XFZuXfWmSmlhHFGjrD4y/6GOitjxDvkrHwmaRYBT/6pMaA/jXXq8R7asDauoRHZTGfFMGn6l3MHUgiVQPsVac2QR1GWmIuzLYBbtCZO/Zwh9f6PHaOI=

### Context

Is affecting the functionality of the app.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70819362/1664f2e6-64f8-456e-bd58-e035c433a6db)

### Environment

```markdown
- FlutterFlow version: 4.1.27
- Platform: MacOS
- Browser name and version: Native MacOS app used - Browser Chrome Version 121.0.6167.160
- Operating system and version affected: Sonoma - Version 14.3.1
```

**Comment by apppbuilder** [comment]
I found a pretty similar bug.

The thing is almost the same:

Steps to Reproduce
1. create cloud function that **receives** a list of <String, dynamic> (mix different dynamic types) in a cloud function variable as a JSON.
2. create a custom data type.
3. bind the data type into an app state and feed it to **send data to** cloud function.
4. execute cloud function using an action and selecting the app state to the variable, map items and transform every item in list to JSON.
![123](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/34366438-dbee-493a-82c8-5b1835fe93e0)
5. execute the action in test/run mode.

The JSON list always reach the cloud function as blank!

**Comment by hariprasadms** [comment]
Hi @damianfraire - Thank you for reporting the issue. Are you still encountering the problem? It seems like the CORS policy might be blocking the external API call since it's inside a cloud function. When testing within the FF debug run, it works fine because we use a proxy to execute the API calls. However, when you deploy the same to the app store or devices, you need to handle the CORS policy on your end. To double-check, could you please confirm how it works when you deploy the app in web mode and also in run mode? Please provide these details for confirmation.

**Comment by hariprasadms** [comment]
Hey @damianfraire, Due to inactivity, so I'm guessing the issue has been sorted out on your end. If you still think there's a problem, feel free to start a new issue with all the latest details and screenshots.
