### ISSUE TITLE
BLOCKER - Push to repository does not work even when there are no errors!!

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2360]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created screens and have been saving and i see no errors on the project. It is a simple project. But when i try to push the code to repository, i am getting push failed and it is not giving any further error report of what actually is wrong. It is only stating to contact [support@flutterflow.io](mailto:support@flutterflow.io).
IT IS A BLOCKER FOR ME!. I wrote to support on chat, E-Mail and I feel i am shouting in vaccum.

### Expected Behavior

When the project has no errors, the commit should succeed without errors.

### Steps to Reproduce

1. Go to the project
2. Check if there are any reported errors.
3. click on code icon
4. click push to repository and add comment and click on PUSH button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No bug report code - It is not a widget.

### Context

BLOCKER! I have a demo to client tomorrow and i was not able to work on the project at all. I feel worried if flutterflow will help at all.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/b51c7469-2671-4292-b150-d126d1de096f](https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/b51c7469-2671-4292-b150-d126d1de096f)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:4.1
- Browser name and version: Edge
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hi @task-win - Thanks submitting the issue. Whats your project bug report code ? without this detail we can't get access to you project. Please update the issue details asap. Thanks

**Comment by task-win** [comment]
IT4wlPLlvJV2otxE15DuY8BFmjoRMjs3bI0k0+xuZCs8GZT0B4kcYs+kfklUOPLiSnw/JFq0imQX/MrLk/HUUMAqKS6qc6pazJNQcxbMeF+tV5SwEK63b3d5EftRJkixy7e7pxMnBPhecV4N2zv7DOfLfHXDQpjBDDInA+aoXdeK2SrDX1iXc2URm05KZDPz

**Comment by task-win** [comment]
Hi,
I do not know what you mean by project bug report code.
The project Id is: dance4-respect-qyv5pa

I have just generated the code from a page: IT4wlPLlvJV2otxE15DuY8BFmjoRMjs3bI0k0+xuZCs8GZT0B4kcYs+kfklUOPLiSnw/JFq0imQX/MrLk/HUUMAqKS6qc6pazJNQcxbMeF+tV5SwEK63b3d5EftRJkixy7e7pxMnBPhecV4N2zv7DOfLfHXDQpjBDDInA+aoXdeK2SrDX1iXc2URm05KZDPz

Thank you,
Regards,
Taskwin

From: Hari ***@***.***>
Date: Monday, 19. February 2024 at 18:34
To: FlutterFlow/flutterflow-issues ***@***.***>
Cc: srinivas sanikommu ***@***.***>, Mention ***@***.***>
Subject: Re: [FlutterFlow/flutterflow-issues] BLOCKER - Push to repository does not work even when there are no errors!! (Issue #2360)

Hi @task-win<https://github.com/task-win> - Thanks submitting the issue. Whats your project bug report code ? without this detail we can't get access to you project. Please update the issue details asap. Thanks

**Comment by task-win** [comment]
Hi I hope this helps. @hariprasadms 
Thank you,
Srinivas

**Comment by Miamoto-Musashi** [comment]
As a side comment i noticed that even if the loading indicator seems working, pushing to repo does not take effects if there are no modifications on the code; i suggest to add some label, hint or similar "fake" edits to force the push

**Comment by task-win** [comment]
Hi @Miamoto-Musashi  i have tried your suggestion and added an invisible row and tried. No luck. This is bothering me and has become a blocker for my project. 

https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/c339fa51-d491-4e65-8614-14fcaaf4a156

**Comment by Miamoto-Musashi** [comment]
Hi @task-win I see you have a clear error, my case was different; was telling success but didn't pushed.

What i did was to add a `print('bla');` on a custom code to force recompile the project.
If you want to debug the error in your case try open a developer console on the web  and see if it show the error.

Another trick could be to open a anonymous session and see if it solves; FF get confused when there are many open sessions (also desktop app).

Hope it helps
BR

**Comment by task-win** [comment]
Hi @Miamoto-Musashi  Thanks for the suggestion and workarounds. I have checked to see if there is anything in developer console. But I find the firebase google api issues which belong to flutterflow but not my firebase project.

<img width="1615" alt="Screenshot 2024-02-20 at 11 13 10" src="https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/038160f9-2729-4973-9f4d-4bf92a8ef7f7">

I also tried with incognito mode browser and logged out before trying it. But no luck.
<img width="1654" alt="Screenshot 2024-02-20 at 11 18 40" src="https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/7fa31d13-6966-4aca-8c8b-b7ee04045163">
Thank you,

**Comment by task-win** [comment]
Hi @Miamoto-Musashi @hariprasadms Even my last attempt to download code also failed.
<img width="1674" alt="Screenshot 2024-02-20 at 11 20 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/b53df963-eaa3-4543-b144-87a6a5467165">

**Comment by task-win** [comment]
<img width="1711" alt="Screenshot 2024-02-20 at 11 21 41" src="https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/bcfa0870-1947-4717-b3fd-d035c998b0a5">

**Comment by Miamoto-Musashi** [comment]
seems something related to code generation, sorry but cannot suggest further, make sure your code looks good (main.dart) or wait for the support to investigate in your project
Best luck

**Comment by hariprasadms** [comment]
Hi @task-win - Thank you for providing the bug report code. I attempted to download the code from your project, but encountered an error. I received the following message:

"Error: Unable to download code. Please try again later."

<img width="1502" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/85551b59-c956-414e-80d0-96ff362bdd6b">
I also tried to download the code through the CLI, but encountered the same error. It seems that there is indeed an issue with the project. Since this issue appears to be specific to the project, I agree that it should be marked as a project bug. Thank you for bringing this to my attention. Since you're unable to proceed, I'll go ahead and escalate the issue to the team for further investigation. We'll prioritize resolving this as soon as possible. Thank you for your cooperation.

**Comment by task-win** [comment]
Hi @Miamoto-Musashi I should thank you for suggesting some process. The issue for my project is solved now. I will explain the steps what i have done.
1. Opened the project.
2. Kept the developer console in browser open to see any issues.
3. Clicked on download code.
4. I observed an error called "dance_home_model" failed to format code.  --> I sensed that this page is creating an issue.
5. I deleted the complete page in the project.
6. Tried to download and was successful.
7. So, tried the Git Push and succeeded. 

Thanks a lot. But i think flutter flow should atleast allow downloading code even if there are issues. Just give a info message to be sure to proceed to download even if errors or issues exist and if the developer says yes, flutterflow should give the code out.

This helps atleast that developer will have the option to design pages on flutterflow and work with code outside the FF ecosystem without getting blocked on the project.
@hariprasadms  Thanks a lot.

**Comment by Miamoto-Musashi** [comment]
Happy to ear that
Best luck

**Comment by hariprasadms** [comment]
Hey @task-win, I've just double-checked your project, and it looks like the code can be downloaded successfully. Additionally, the git push operation is working fine. Therefore, the issue mentioned here seems to be resolved. I'll go ahead and close the issue. Thanks a lot for your contribution!

**Comment by dustin38231** [comment]
Hopefully this helps everyone as we continue to have this exact same issue. Clone your project and set everything back up. Should work for you then. I know its not ideal but its a workaround
