### ISSUE TITLE
Failed Step: Build AAB with Flutter…The following dependencies do not satisfy the required version: project ':location'

### ISSUE THREAD

**Issue by albluwi1987** [FlutterFlow/flutterflow-issues#2361]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,
When I try to download the apk or deploy my app to google play console (Beta Track) I get this error message:

Upgrading build.gradle
Running Gradle task 'bundleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
  The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
  The following dependencies do not satisfy the required version:
  project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

### Expected Behavior

To deploy or download apk without any errors

### Steps to Reproduce

Not sure but I think

1. Activate location service
2. Try to get the device location

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflfLl8ZNOm99Y15SJacZagioUJmUcTIMziNZ+exUbfaL1Bu0LP/f7SFNDXdPnaVNcHFqammYdzNrVkvzDDPI6YAiZGLZI/rpXWwnee2iuMJSoCqmOR2h8ROFUGB2xy6anvCUnKtdpSVVl7Fy2AeSRYD/DFOu/Zwh9f6PHaOI=

### Context

Badly…Because I’ve finished my App on ios and it’s published on apple app store…and this stopped me from publishing it to google play store!

### Visual documentation

![IMG_1067](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5e59923e-72bc-4e5d-95ce-3f7d57eb5699/0df2e6ff-3b65-4949-8782-172d209e35a3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ZTU5OTIzZS03MmJjLTRlNWQtOTVjZS0zZjdkNTdlYjU2OTkvMGRmMmU2ZmYtM2I2NS00OTQ5LTg3ODItMTcyZDIwOWUzNWEzIiwiaWF0IjoxNzA5MDM1OTY4LCJleHAiOjMzMjc5NTk1OTY4fQ.xFAF06Nimr68gLcWYqN2K8IfQCYTDknEdXCn4U9XaSk)

![IMG_1068](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/48261378-0c94-4584-81a0-0b4559e66d24/702044f9-13cf-4852-a50b-b352e85ffdc4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODI2MTM3OC0wYzk0LTQ1ODQtODFhMC0wYjQ1NTllNjZkMjQvNzAyMDQ0ZjktMTNjZi00ODUyLWE1MGItYjM1MmU4NWZmZGM0IiwiaWF0IjoxNzA5MDM1OTY4LCJleHAiOjMzMjc5NTk1OTY4fQ.wLQsC8WyMAqBu1P6uv5mIe_zifQ2_WpNABpDu-DiBLI)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v3.1 developed at that time
- Platform: Web and iPad
- Browser name and version: Chrome
- Operating system and version affected: iPadOS , iMac Ventura
```

**Comment by aemelyanovff** [comment]
This is an issue with one of custom dependencies, `smooth_compass`: https://github.com/alihadi5125/smooth_compass/issues/7

I'm afraid there's nothing we can do about it on the FlutterFlow side.
