### ISSUE TITLE
Custom logout navigates without being called

### ISSUE THREAD

**Issue by SEGVeenstra** [FlutterFlow/flutterflow-issues#2363]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app should not navigate when the user cancels the logout dialog.

### Expected Behavior

Even if the user cancels the dialog, the app still navigates to the login screen.

### Steps to Reproduce

1. Create a login page that uses custom login for authentication.
2. Create a homepage for the when the user is logged in.
3. Add a logout button
4. Add the actions as follow:

![Scherm­afbeelding 2024-02-19 om 11 20 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1df14800-2516-473b-ad91-3651d8231f9f/6a36efae-cd81-48be-9e40-7851d5631c69?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZGYxNDgwMC0yNTE2LTQ3M2ItYWQ5MS0zNjUxZDgyMzFmOWYvNmEzNmVmYWUtY2Q4MS00OGJlLTllNDAtNzg1MWQ1NjMxYzY5IiwiaWF0IjoxNzA4MzQ1NDMyLCJleHAiOjMzMjc4OTA1NDMyfQ.-ogzqadD04oBH7JIsmDxDH61nxQr9DkOVi3meIIzOOE)

1. Test the app

Now whatever option you pick, cancel or logout, both will result in the app navigating to the login page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Thc/1z4hOsdtK+KryccBvgiYvNl87aucziu1EFBQaJuvoB7QHPPekbXFJOum4TAk7CmeWmjsypq3Zud7DGMEnHxGrbLlq3bl2FA/xQlujRLrUPKrtREdREppWfHLG3KaO2wx9G7FaLXg+1F6bOOjJQgDaGJOwNjMnBPyjMt7+kVKUKxDsGiFrxidecCfn

### Context

I need the user to stay on the homepage if they cancel the logout request so they can continue using the app.
Other aspects are working, like retaining the user loggedin state.

### Visual documentation

![Scherm­afbeelding 2024-02-19 om 11 20 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/29bf1af6-5428-45a6-9969-d395c674681f/506f6fec-8ef5-4f5f-a5ed-440722dcd526?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yOWJmMWFmNi01NDI4LTQ1YTYtOTk2OS1kMzk1YzY3NDY4MWYvNTA2ZjZmZWMtOGVmNS00ZjVmLWE1ZWQtNDQwNzIyZGNkNTI2IiwiaWF0IjoxNzA4MzQ1NDMyLCJleHAiOjMzMjc4OTA1NDMyfQ.mXvvmHOKteMsNfIXwgjl_wMc8HdB8ZV0uAEnaEJCQYM)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Mac
- Browser name and version: Chrome 120.0.6099.216 (Officiële build) (x86_64)
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @SEGVeenstra - Thank you for submitting the issue. Given the nature of the issue and its association with the involved data, it appears to be more project-specific, which may require additional time for thorough investigation on our end. To expedite the resolution process, I recommend creating a sample function with mock data (utilizing app state to store the data) to replicate the issue. Share the details with us. it will greatly help us in swiftly investigating and resolving the issue.

**Comment by SEGVeenstra** [comment]
> Hi @SEGVeenstra - Thanks for submitting the issue - You should add terminate step to stop the action execution. See below. 
> 
> <img width="595" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/994ac2f3-3a30-41ef-a273-d202f2b3b120">
> 

Thank you for your reply.
Can you tell me why that is needed?

Why does it perform the navigation even though that part of the condition is not met?

**Comment by Franco98404** [comment]
> Can you tell me why that is needed?
> 
> Why does it perform the navigation even though that part of the condition is not met?

Hello @hariprasadms, I have the same doubts. I appreciate it if you give us an explanation :)

**Comment by leighajarett** [comment]
Re-opening this for further investigation!

**Comment by ignalauret** [comment]
Hey @SEGVeenstra thanks for your report. I've been able to replicate your issue, and it only happens with the Custom Logout action. I can see the bug in the code generation, and it getting fixed when you add the terminate as Hari suggested. Please use that workaround until our technical team can fix the Code generation.<br>Have a great day!
