### ISSUE TITLE
Is there a bug in the Flutterflow Language Selector?

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#2364]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I have created an app through Flutterflow which has two languages, English and Greek. The problem I am facing is that even I set English as the default language, Greek appear when I start the app. What can we do to fix this issue? Is there a bug in the Language Selector / the settings of Flutterflow?

### Expected Behavior

I would have expected the app to start in English

### Steps to Reproduce

Create a project with English and Greek as languages, try starting in English, starts in Greek for me.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OzMmBw412odtF+KryKMJVtDsWQ2I/apZMiu1DdwIcG4PNG4gIZfTBXE9uOP25dgl5emaGknMe+snGm9z1MMApHxCZGKJbws9tVTrMWj26SoyvPM28QnB+Gshhfmai552NhiZCXdJhLVIg72aLeui8dDfdQpzbDkczRvmlDNrXmAfuQ0SLb3kNh1JWeC/v

### Context

I am trying to create an app with at least two languages

### Visual documentation

You can see these in my project

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Windows 11
- Browser name and version: Chrome Version 121.0.6167.185 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hello @adrfinance, Thank you for submitting the issues. It appears that there is no default language term used in the language settings. I believe you are referring to the primary language. It's important to distinguish between two types of languages: the primary language, which affects the language displayed in the deployed app version, and the display language, which determines the language displayed inside the FF editor.

I have tested both selections, and they are working as expected. Additionally, it's worth noting that every time the primary language is changed, it is recommended to regenerate the translation.

**Comment by hariprasadms** [comment]
I looked at your project, it seems to be working fine as you got langage selecting dropdown in the login page. I hope you have resolved the issue. If issue is resolved for your please close the issue. Thanks

**Comment by adrfinance** [comment]
Hello

I used the language drop-down because the project would always start with
Greek.

Στις Τρί 20 Φεβ 2024, 18:26 ο χρήστης Hari ***@***.***>
έγραψε:

**Comment by hariprasadms** [comment]
When I did try your project debug run at my end, I see langage selection is working as expected. It looks like it is your browser. Can you please try in incognito mode.

**Comment by adrfinance** [comment]
I will take a look thank you

Στις Τρί 20 Φεβ 2024, 18:34 ο χρήστης Hari ***@***.***>
έγραψε:
