### ISSUE TITLE
Surface clip behavior for scrollables

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#2367]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when you make a row or a list view of children dynamic, the drop shadows get clipped.

### Expected Behavior

drop shadows shouldn't be clipped when generating dynamic children or generating contents from a query in a row or horizontal list.

### Steps to Reproduce

1. add a row to your column
2. add a fixed height container with a drop shadow (preferably blur 20 to make it noticable.
3. duplicate the above
4. generate the contents of the row from a query or as dynamic children
5. the drop shadows will be clipped.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0sNobbxAjIoDoPJkUaczBclpBXt/gS2NPKEWLmk80+dbFieP9FPUFAwmbb7k5+aoIEQ/yQnm/aoStCKW0Y3MlM+hWCh2z0Z2RnSV7LbNpS3gE7E2mCeqUfHbcK736Zwh9f6PHaOI=

### Context

causes the UI to be wrong and unusable

### Visual documentation

![Screenshot 2024-02-19 at 11 46 52 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/64d9b785-cf35-4f18-97a0-6a266dbb519d/56c6014d-1ed3-493a-a93c-6b729e12ce74?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NGQ5Yjc4NS1jZjM1LTRmMTgtOTdhMC02YTI2NmRiYjUxOWQvNTZjNjAxNGQtMWVkMy00OTNhLWE5M2MtNmI3MjllMTJjZTc0IiwiaWF0IjoxNzA4Mzc4MDE5LCJleHAiOjMzMjc4OTM4MDE5fQ.DQsZdcZGuTcJMhKlRtsvw5LLU_nJo9OyYXUa4BPUWiQ "=551x")

the bottom image has the drop shadows clipped with the only difference being the children are generated dynamically

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: latest
- Platform: mac desktop
- Browser name and version: chrome latest
- Operating system and version affected: IOS and Chrome online version
```

**Comment by hariprasadms** [comment]
Hi @aaronmt93 - Thank you for bringing up the issue. I'm still struggling to grasp the exact problem you're trying to explain. Could you please provide additional details, along with examples, to clarify the issue you're experiencing? This will help me better understand and assist you. Thank you.

**Comment by aaronmt93** [comment]
Hi @hariprasadms. in the picture above, I have a row with a child that has a drop shadow. as you can see the drop shadow expands beyond where the border of the row would be. 

However, I have take that same row and then set it to generate children dynamically, the drop shadows are getting clipped on the top and bottom parts of the row

**Comment by hariprasadms** [comment]
Hi @aaronmt93 - Got it. Thanks for the details. 

Dev info - 

When it is row,

<img width="483" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/01c5e41b-003a-41fe-b9ac-a88e8ef9c02c">

With column, 

<img width="378" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/23bb9d37-ca4b-4e40-8191-dfb47044bfe7">

**Comment by wenkaifan0720** [comment]
This is because the row didn't have enough vertical space for the shadows. If you wrap the bottom row with a container and give it enough height (say 150), you can see the drop shadow being rendered correctly.

**Comment by aaronmt93** [comment]
@wenkaifan0720 in the first example though in my screenshot a container wasn't required. And then having to put a container the size of the drop shadow messes up the spacing between items in a list or column so isn't a realistic fix in most cases.

**Comment by wenkaifan0720** [comment]
After further investigation, looks like this only happens in the builder (not in the actual generated app), and only happens when the row is longer than the page's width (doesn't matter if it is dynamic or now). I would put this issue as low priority for now.

**Comment by aaronmt93** [comment]
@wenkaifan0720 i think you are right that it happens when it exceeds pages width. however I am seeing it happen on my device not just in the builder.

**Comment by wenkaifan0720** [comment]
@aaronmt93 You are right, the clipping behavior happens (but not always). See this test site: https://issue-2367-8up1fo.flutterflow.app/. This looks like a Flutter issue, as we are using standard Flutter widgets in the test project.

**Comment by aaronmt93** [comment]
@wenkaifan0720 hm ok. did some quick digging, per the last comment in this issue seems like clip behavior has to manually be set to none in the code for scrollable widgets otherwise this happens.
 
<img width="907" alt="Screenshot 2024-02-23 at 5 21 21 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/9a2c7180-b5d7-4425-b887-20add6c00721">



https://github.com/flutter/flutter/issues/59424

**Comment by wenkaifan0720** [comment]
Interesting find. Thanks! We don't surface this option for scrollables right now, but we should certainly do that. I'll mark this as a feature request.

**Comment by aaronmt93** [comment]
thanks @wenkaifan0720.  does marking it as feature vs. bug here reduce its priority? whether its a bug or feature kind of feels like it should be the default behavior as its making using drop shadows with horizontally scrolling rows/carousels unusable currently.

**Comment by leighajarett** [comment]
Hi there! @aaronmt93 no it does not reduce priority - it's merely how we track things internally. We do have a separate place for tracking feature requests internally so I will be closing this issue out here and moving it over there so we can make sure it's added to our backlog
