### ISSUE TITLE
Not pushing to app store

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2369]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Deployment to apple App Store is failing

### Expected Behavior

Deployment to app store is successful

![Screenshot 2024-02-20 at 7 55 59 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b460ccc1-463a-419c-8da7-feb38b0357b4/459f8dc2-c31e-4f68-b059-a69e591ee8ea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNDYwY2NjMS00NjNhLTQxOWMtOGRhNy1mZWIzOGIwMzU3YjQvNDU5ZjhkYzItYzMxZS00ZjY4LWIwNTktYTY5ZTU5MWVlOGVhIiwiaWF0IjoxNzA4NTE5ODAxLCJleHAiOjMzMjc5MDc5ODAxfQ.GvkYHbkQnFkmlYfgxgR79Mtrp6XaCqQNO8YNaeEq-n0 "=896x")

### Steps to Reproduce

1. Go to mobile deployment
2. Click deploy to app store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

notapplicable

### Context

I can't push my app to 'under review' in the app store

### Visual documentation

![Screenshot 2024-02-20 at 2 45 43 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/742b7885-3601-42f3-9421-22c5ccfacdab/8fe56274-2453-49a1-b511-be837064bb0d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NDJiNzg4NS0zNjAxLTQyZjMtOTQyMS0yMmM1Y2NmYWNkYWIvOGZlNTYyNzQtMjQ1My00OWExLWI1MTEtYmU4MzcwNjRiYjBkIiwiaWF0IjoxNzA4NTE5ODAxLCJleHAiOjMzMjc5MDc5ODAxfQ.r6Y7cR7pWw0R_aoCK_ElfQrVpwYtv7Sws54OUo2GpmM "=925x")

![Screenshot 2024-02-20 at 7 55 59 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/86cf7a2b-bc2c-4596-9089-6db8b1453076/92fcb8f3-29fe-4112-b59d-151c4c9122f8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NmNmN2EyYi1iYzJjLTQ1OTYtOTA4OS02ZGI4YjE0NTMwNzYvOTJmY2I4ZjMtMjlmZS00MTEyLWI1OWQtMTUxYzRjOTEyMmY4IiwiaWF0IjoxNzA4NTE5ODAxLCJleHAiOjMzMjc5MDc5ODAxfQ.g6VBwUMOtDhX6EEUFBbIJ6un3SFNTvafL3fFphDdio4 "=896x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.6
- Platform: Mac
- Browser name and version: Google Chrome
- Operating system and version affected: Mac
```

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! Here is the bug report code - IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCotCLbkOpgcf/fOYkRpQs/gT3xfemL8p2oW0N2OuezXUfE5FxOYbo86zpBpFgziLU+jbr64FJWgdEBPHp5Qf33GyLbYghFAKu9vc1Y/3zm6F96sfA/dHYT1DGwsDq/LZO4=

Please let me know if I can provide any additional information. Thank you!

**Comment by hariprasadms** [comment]
Hi @lovestar18 - Thank you for sharing the project bug report code. Upon review, I identified an immediate missing configuration: the build number. Before proceeding with deployment, it's essential to provide a build number. I recommend adding a build number, for example, '1', and testing to see if this resolves the issue. If the problem persists, please share the details so that we can further assist you. Thank you.

<img width="755" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b2a89a39-e312-4ec1-bf16-adf28c850251">

**Comment by lovestar18** [comment]
Got it, thank you very much @hariprasadms ! Before I deploy, I have two questions I was hoping you might be able to help with:

1. I'm trying to filter by the 'groups document' or 'wall posts' as the user reference underneath that document but it will only let me filter to the reference under 'authenticated user.' Else I receive an error such as the one in the screenshot attached. Is there a way I can change this?

<img width="1006" alt="Screenshot 2024-02-16 at 7 19 53 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/1fe11fcb-19c8-472e-9c6c-98b66193d019">
<img width="1003" alt="Screenshot 2024-02-16 at 7 18 49 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/ea654058-cf79-49df-81dc-32dc4db81f1d">

2. When I test the 'listoftopics' page, I see the error below - could there be something wrong with my data setup? There should be a list of categories / topics which I've set up in Firebase. Will it show once the app is deployed?

<img width="294" alt="Screenshot 2024-02-21 at 5 16 06 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/f28c12da-cd09-46fe-a176-8943c592ba28">

Thank you!

**Comment by hariprasadms** [comment]
Hi @lovestar18 - Thank you for confirming that the test app deployment includes the build number. Regarding your other question, I suggest creating a new issue outlining all the reproducible steps with a blank project setup. This will make it easier to work on the steps and assist you in resolving any configuration issues. Thank you!

Close this issue once you see app deployment is working and no further issues. Thanks

**Comment by lovestar18** [comment]
Will do - thank you @hariprasadms !

**Comment by lovestar18** [comment]
Hi @hariprasadms I did add a build # but it still failed to push to the App Store - any insight as to why this could be?

![Uploading Screenshot 2024-02-29 at 3.06.18 PM.png…]()

**Comment by lovestar18** [comment]
I submitted a new ticket since this one was closed - https://github.com/FlutterFlow/flutterflow-issues/issues/2416
