### ISSUE TITLE
Error widget for ListView

### ISSUE THREAD

**Issue by marektomczyk** [FlutterFlow/flutterflow-issues#2370]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When API call fails for `ListView` then we have infinity loader.

### Expected Behavior

We have ability to set loading widget while fetching data. There is a missing Error widget when fetching fails.

### Steps to Reproduce

1. Create page
2. Add `ListView` widget and set API call
3. When API Call fail you will have an infinity loader

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sz8jfz5R2rulA1pDpbfpVniQUJj47bZJElO1qEAg2CJTwP4YTXOjDflJvOdeFT2xYelv8+XE0p+jLv+DEGuQHAyyWR4BJ+qoJaTzdXkK5M766CZOCXnAmI8dPHkuV0be3gBNSKvphSmQt1EyTOOSRbHPUQabHOUQ7R/6jOoHUp2y9Ahm6Xn0Jg1ZSfCvr

### Context

I want to display error widget when ListView API Call fail.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/56510166/a1497297-131e-4860-b7b8-e90a4a63272f)

### Environment

```markdown
- FlutterFlow v4.1 released February 16, 2024
- Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Arc 1.30.0 (46409) or any other
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by hariprasadms** [comment]
Hi @marektomczyk - Thank you for bringing up the issue. The behavior you are expecting is custom and can be addressed through custom code implementation. Additionally, there's an option for a loading widget type (as indicated below) that allows for the display of a custom widget while data is loading.

The ListView widget's current behavior aligns with its design and is not indicative of a bug.

<img width="496" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/e3eaea39-424c-4170-8c23-a4f76d3dd721">
