### ISSUE TITLE
Firestore Schema "Field Name" field's vertical alignment is bottom-aligned instead of middle-aligned

### ISSUE THREAD

**Issue by ToddHerron** [FlutterFlow/flutterflow-issues#2373]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is just a minor visual thing.

When you go to the Firebase schema, the items in the "Field Name" column are bottom-aligned and not middle-aligned (like the "Data Type" column).

### Expected Behavior

All schema fields should have the same vertical alignment (i.e. middle aligned)

### Steps to Reproduce

1. Go to the Firestore schema page
2. Select any collection with a schema

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oksn6389IsdtJ+KriasExryQsH1whaqxM0sEaaEgYB4vNG4gIZfTBXE9uOP25dkFUMGKgnnoe+vDRm9z1JsEoNRGVbJhFyZdQcRbJcDmVaLa1DpeCRWtEGshUBUyH4aWrsRB7ANpZWiU11zmMFuutUirXGZv6O2w7R/H/BJDXmAfuQ0SLb3kNh1JWeC/v

### Context

Just a minor visual annoyance.

### Visual documentation

This is a visual change. It does not affect functionality.

### Additional Info

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4e59bea9-963a-447c-9fcb-5db2fc3959f1/e3e22d67-e02c-4867-ba10-332b308a33f0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZTU5YmVhOS05NjNhLTQ0N2MtOWZjYi01ZGIyZmMzOTU5ZjEvZTNlMjJkNjctZTAyYy00ODY3LWJhMTAtMzMyYjMwOGEzM2YwIiwiaWF0IjoxNzA4NTU2NjkwLCJleHAiOjMzMjc5MTE2NjkwfQ.xhKXfZXSIoo6tanUJaAe8TDyDcuGHd6MOXMDru_4_Zk)

### Environment

```markdown
- FlutterFlow version: v4.127
- Platform: Mac
- Browser name and version: https://beta.flutterflow.io/project/flutter-flow-bugs-t7r4ht?tab=widgetTree&page=LoggedIn
- Operating system and version affected: Mac OS Sonoma 14.3.1 (23D60)
```

**Comment by hariprasadms** [comment]
Hi @ToddHerron -Thank you for reporting the issue. The behavior you are currently experiencing is intended according to the current design and is not considered as a bug. Therefore, I am closing the issue. Thank you.
