### ISSUE TITLE
List View com Banked Query está fazendo busca de forma incorreta

### ISSUE THREAD

**Issue by ImoAppBrasil** [FlutterFlow/flutterflow-issues#2374]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No meu app, na tela inicial (Home) há duas LIst View, em uma delas apenas mostra postagens com a categoria "Destaque" com o valor "True", e na outra List View mostra todas as postagens. A List View que mostra apenas os destaques está funcionando de forma correta, porém na segunda List View, no test mode, ao atualizar pela terceira vez, por algum motivo ela filtra apenas as postagens com o "Destaques" que estejam com o valor "True" igual a primeira List View.

### Expected Behavior

O comportamento esperado é que ao atualizar o teste mode cada list view continue filtrando os itens do jeito que foi colocado na Query Colletion.

### Steps to Reproduce

1\.Crie duas List Views; 2. Colque filtros diferentes em uma Query Collection na List View em cada uma; 3. Inicie o Test Mode e atualize algumas vezes; 4. Note que alguma List View vai mostrar resultados que não são aqueles desejados com filtros colocados na Query Collection.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTj8nlsYt1rs9H+Knqc8BavCMUM0MdXZIRmOtvewgjF774PbAIeOLRck9tZ+KzaHxfMFCLqz8z/tLGjeLlJvQ6ZBWeGJxN/rVQcxPPY3KVR820Pru0Q3Z7L9lXfXbA1MCj3RNBNbdpV1pi62GuHuyXfz+Cf9qOYwx5e6fDbOY=

### Context

Esse problema me afetou muito, pois estou desenvolvendo um projeto de aplicativo de anúncios de imóveis há mais de 5 meses, e com esse tempo venho notado que recentemento alguns bugs vem acontecendo com frequência, o que era diferente há um tempo atrás.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/160800981/4e221e4c-43c3-45fc-a1a7-cab36df66cc5](https://github.com/FlutterFlow/flutterflow-issues/assets/160800981/4e221e4c-43c3-45fc-a1a7-cab36df66cc5)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Opera Gx 106.0.4998.76 e Google Chrome 122.0.6261.57
- Operating system and version affected: Windows 22H2
```

**Comment by hariprasadms** [comment]
Hi, Due inactivity of the issue we presume the issue is not more exists in the project. There are number of bug fixes are released with the latest updates. Please check and create new issue if issue still exists. Thanks
