### ISSUE TITLE
Test environment - not showing Firebase data

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2377]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I test the 'listoftopics' page, I see the error below - could there be something wrong with my data setup? There should be a list of categories / topics which I've set up in Firebase. Will it show once the app is deployed?

### Expected Behavior

Topics are shown on the community forums page and not an error

### Steps to Reproduce

1. Test the 'list of topics' page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

When I test the 'listoftopics' page, I see the error below - could there be something wrong with my data setup? There should be a list of categories / topics which I've set up in Firebase. Will it show once the app is deployed?

### Context

Preventing me from pushing my app live to the app store

### Visual documentation

![Screenshot 2024-02-21 at 5 16 06 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a9a3ed95-f9fc-4a02-8618-3f9ca9838c6b/f33a29e0-9bea-442b-af6e-1e1184c5da1b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hOWEzZWQ5NS1mOWZjLTRhMDItODYxOC0zZjljYTk4MzhjNmIvZjMzYTI5ZTAtOWJlYS00NDJiLWFmNmUtMWUxMTg0YzVkYTFiIiwiaWF0IjoxNzA4NjEwMzgyLCJleHAiOjMzMjc5MTcwMzgyfQ.PMk1AEC_HsY-UN8ah6WZHVfNRdrz4uZAzvMH14YI4Ic "=294x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Mac
- Browser name and version: Flutterflow
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hi @lovestar18 - Please share project bug report code ?

**Comment by lovestar18** [comment]
@hariprasadms - here it is - IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCosfZT2BLMcec/RVERvYNzgYHNiMWf8gWoW3M7mkd7DMe03Ok2qbbZO+agBagmVQkC5VpiaFJWgdEBPHp5Qf33GyLbYghFAKu9vc1Y/3zm6F96sfA/dHYT1DGwsDq/LZO4=

**Comment by hariprasadms** [comment]
Are you still experiencing the issue?
I've checked out your project, but couldn't pinpoint the exact page where the problem is occurring. However, as a first step, try regenerating the FB configuration files and see if that helps resolve the issue.

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! I did regenerate the FB configuration files and I am still seeing the error below in testing. I found this error by testing the app and from the _homepage_, clicking on _community_ and then I find this error.

<img width="1054" alt="Screenshot 2024-02-27 at 8 26 55 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/1e43fb7c-8157-4bcc-8591-17a185327981">

**Comment by hariprasadms** [comment]
Hey @lovestar18 , I took another look at the project, and it seems like the problem is with the query mapped to the list-tile with the click action on the listoftopics page. I suggest trying something: remove the query from the list-tile and see if the list-view query shows the items properly. Then, you can work with the data. It seems like more of a configuration thing than a bug in how it works.

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! I have done that but I now seeing a different error - any recommendations?

Thank you!

<img width="290" alt="Screenshot 2024-02-28 at 7 00 48 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/9deff5e4-468a-403c-a7fe-077d2fc44b15">

**Comment by lovestar18** [comment]
Hi @hariprasadms - I am still seeing a few issues in my project. I have tried to troubleshoot - would it be possible to please provide guidance on how these might be able to be fixed? Thank you!

I saw a [post in the community](https://community.flutterflow.io/database-and-apis/post/firebase-security-rules-error-mCbdW92fmgdAgNO) to change all rules to "authenticated user" so I have done that but it didn't seem to help.

To replicate these errors, please go to test mode and follow the process below:

Homepage > Community Forums
<img width="239" alt="Screenshot 2024-03-06 at 8 49 59 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/9c1173e7-31b6-48f5-a37b-97014d46455a">


Homepage > ForJew Page
<img width="222" alt="Screenshot 2024-03-06 at 8 49 37 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/2d50b81a-071d-4b60-9462-1bc459d23e1a">

Homepage > Your Profile (top right) > click "Create Wall Post"
<img width="220" alt="Screenshot 2024-03-06 at 8 49 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/78eee097-f400-4848-a652-8d7711fafac0">

Thank you!

**Comment by takashiff** [comment]
Hi @lovestar18, thanks for the bug report! It looks like your Firestore Indexes are out of date, which may be causing this issue. Can you try redeploying your indexes and confirming whether the issue persists? Thanks

**Comment by lovestar18** [comment]
This issue has been fixed - thank you @takashiff

**Comment by takashiff** [comment]
I'm glad this resolved the issue for you! Going to mark this as closed now.
