### ISSUE TITLE
Navigation element to exit full-screen mode not visible for images with white in upper left-hand corner

### ISSUE THREAD

**Issue by constant-work** [FlutterFlow/flutterflow-issues#2379]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the Make Expandable option is selected for an Image Widget the image is able enter full screen mode upon the user clicking it. However, since the "X" the user must click on to exit full-screen mode is white with a transparent background, it is not visible to the user when the image happens to be white in the area the "X" element is located over. Thus, the user becomes stuck in full-screen mode.

### Expected Behavior

After an image enters full-screen mode the expected behavior is that a user can see an option to exit full-screen mode, even if the image happens to be white.

### Steps to Reproduce

1. Add an image that is white in the upper-left hand corner.
2. Expand image to full-screen.
3. Try and locate the element to click to exit full-screen mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhefl0ItIsdtK0L6IKOxKoGMWKUccTb4RltZ+RRQhfKqqPYkIefTBM1hLYte/S1FiBlGapE0zwfSJveHTM/YDPgWtGaZZ+pRXQQvxeECWVraKCcyaRURRM+xUGhWB0bWruh4lGLdfV04s6mCqP/CdG3qCf9qOYwx5e6fDbOY=

### Context

Users cannot exit full-screen mode for images with white behind where the element displays for exiting full screen mode. Users end up stuck in full-screen mode.

### Visual documentation

Where should the user click to exit full-screenmode?

![2024-02-22_16-19-22](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b0431fb2-18d6-4902-ab0b-de84784204d0/e69edea4-393a-488a-b8d6-0118cbdffaa2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMDQzMWZiMi0xOGQ2LTQ5MDItYWIwYi1kZTg0Nzg0MjA0ZDAvZTY5ZWRlYTQtMzkzYS00ODhhLWI4ZDYtMDExOGNiZGZmYWEyIiwiaWF0IjoxNzA4NjQyNzkwLCJleHAiOjMzMjc5MjAyNzkwfQ.Fd0Ax3Inl0YJHn5u4p2HHU3bAxHRQ8VP6rahXaRWWxI)

### Additional Info

Perhaps the simplest fix would be to make the background of the "X" non-transparent.

### Environment

```markdown
- FlutterFlow version: v.4.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @constant-work - I'm unable to replicate the issue. When the image is expanded, the close icon at the top left corner is always present and visible for closing the image. If the issue still exists, please setup a page inside project with issue reproduced in it in one of the projects, and direct me to the page. If the issue no longer exists, please consider closing it. Thank you.

**Comment by constant-work** [comment]
Hi there. Thanks for taking a look at this and for the follow up. To replicate the issue you may need to resize your browser window so that the image comsumes the full sapce of the window and the "X" is then necessarily located over the image. If there happens to be a black "gutter" in the bowser to the left of the image, than the white "X" will be visible against the black. It may be that the issue occurs only when a white image fills the full browser window with no black gutter. In this circumstance, the white "X" is invisible against the backdrop a white image. An easy fix may be to make it so the white "X" includes a drop-shadow or some contrast so it is visible when appearing over white.
