### ISSUE TITLE
backend.dart not imported in widgets

### ISSUE THREAD

**Issue by robin-torwell** [FlutterFlow/flutterflow-issues#238]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
To be able to use custom DataType in a widget, the "import '../backend/backend.dart';" should be added.

## Current behavior (required)
Custom DataType are identiefied as "Undefined class 'CustomDataType'." by the (local) Dart Analyzer.

## To Reproduce (required)

1. Create a DataType
2. Write a Custom Action, which returns a variable of that Data Type
3. Use that action in "On Page Load" of a widget
4. Use the action output of type DataType in that widget
5. Download Source Code
6. Try to run the App or observe the Dart Analyzer output

### Bug Report Code

IT4WisrlvJNPmMBE7c/QdcFV+SAROWU7U7g7l8N+EAIgfJjsOqYPXfikSEpWZ9+kTHxcL06Znn0ew63Ik/PIA+UqKU+dbKI6/5ZiWBaXcEOuMM2nBs2RPGtPEtIGSSDy

## Context (required)

Test the app locally, but without many manual adjustments the app does not build.

## Screenshots / recordings

<img width="626" alt="Screenshot 2022-12-16 at 17 03 27" src="https://user-images.githubusercontent.com/120737392/208139328-68cc3a46-46d1-4971-905c-0ae0de414ec8.png">

## Your environment
Version of FlutterFlow used: 
<img width="250" alt="Screenshot 2022-12-16 at 17 04 18" src="https://user-images.githubusercontent.com/120737392/208139488-42727e7a-40cd-4c97-a886-420486b481ec.png">

Platform (e.g. Web, MacOS Desktop): MacOS Desktop and Web
Browser name and version: Chrome Version 108.0.5359.94 (Official Build) (x86_64)
Operating system and version (desktop or mobile): MacBook, MacOS Ventura 13.0.1

**Comment by agreaves** [comment]
Thank you @robin-torwell for the bug report! This should be fixed upon our next release 🙂
