### ISSUE TITLE
FAB looks different on Flutter 3.19 vs. 3.13

### ISSUE THREAD

**Issue by ametaplus** [FlutterFlow/flutterflow-issues#2380]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The FAB looks different now (round) vs. on the Test-Mode for Flutter 3.19:

![FAB_now](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8f1c3c54-3de2-4a27-88b0-1b093f899884/ea2c1411-064f-4ec1-8f56-abbe384b4467?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84ZjFjM2M1NC0zZGUyLTRhMjctODhiMC0xYjA5M2Y4OTk4ODQvZWEyYzE0MTEtMDY0Zi00ZWMxLThmNTYtYWJiZTM4NGI0NDY3IiwiaWF0IjoxNzA4NjgyMDAxLCJleHAiOjMzMjc5MjQyMDAxfQ.3cFvDNbvjd40Wt9qLw8eNn_HncD4CzVBBFvmZo43ZT0)

![FAB_then](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1e0716bf-4b7d-4e96-90dc-8e7b1aa44ad4/e1af3882-0dde-48e5-880d-66f1776e6651?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZTA3MTZiZi00YjdkLTRlOTYtOTBkYy04ZTdiMWFhNDRhZDQvZTFhZjM4ODItMGRkZS00OGU1LTg4MGQtNjZmMTc3NmU2NjUxIiwiaWF0IjoxNzA4NjgyMDAxLCJleHAiOjMzMjc5MjQyMDAxfQ.D6hOWAibJP8q64ltnKALcZtn2eRYE786S8NYkcPTFaw)

### Expected Behavior

It should also be round

### Steps to Reproduce

1. Create new page
2. Add FAB

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8nl3891rs9D0KX1bu5r/WAWH0h8ULskscd8ewsbfZyuP4lzYfzBSBJtXbynf1VYeWeJ8X4I7tLFhezXFMYoGxCIQ704z7VqWjmWfzugWq6tO5eOWnxtO9JQBXa14LCOihVvAPV2LV5h3WGYI++8SjDcK4zONW0RQvL9Oob4+QOFLSO2LjhmtmNecCfn

### Context

It's not that important, but you should know

### Visual documentation

See first question

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7 vs. 3.19
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows 11
```

**Comment by takashiff** [comment]
Hi @ametaplus, this is because Flutter has updated their `material` package, which has led them to adopt a new design for the `FloatingActionButton` widget. Unfortunately, this seems to be out of our control. Thanks
