### ISSUE TITLE
Navbar not showing in Test mode

### ISSUE THREAD

**Issue by benwa248** [FlutterFlow/flutterflow-issues#2383]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can view the navbar on my project in the Edit Mode and Preview Mode. But I can not see the bar when i go to test mode. Due to this my project is stuck. I need to log out of a test user i created but cant log out from the logged in page because the nav bar does not show on it. please help

### Expected Behavior

To see the nav bar at the bottom of the page. I have clearly marked for the nav bar to show, so when running in test mode it doesn't show.

### Steps to Reproduce

1. create template to create login page
2. create template of list page
   3\\\\.INtital page login landing page will be list page
3. enable nav bar from settings
4. enable to show nav bar on page on the list page and and another page
5. run in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lcr1sIZ2occB7rrqLO9alSk5JkB/bb83iNVRaCsvCIyqOpscf/fBfklUOeGlSkFle2CajnkX/MmLvvPhIfACGE2eR7pHyLgBFgLvRnKlb5S3Pa63b3dPL9NMJkCC1MKvriN5HPRpL0Ik1Dqyf9i9FwvDNr7MO3oWR+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

I am stuck!. I cant log out and create a second user. I need the second user to have a different role, so need to be able to logout of the 1st test account before proceeding.

### Visual documentation

is pretty simple. nav bar not showing in testing mode

### Additional Info

i saw this happened before to another user but no one ever solved it.

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:
- Browser name and version: google chrome
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hey @benwa248, Looks like more activity in the issue. So I'm guessing the issue has been sorted out on your end. If you still think there's a problem, feel free to start a new issue with all the latest details and screenshots if needed.
