### ISSUE TITLE
Google Maps & Google Maps related services no longer working since update.

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#2386]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Adding Google Map no longer works in run and the script refuses to load on Chrome from the get go. I have tested by pushing the app on TestFlight and it does work there (I am guessing for Android as well) however you are not able to work with it in FlutterFlow on run to test your app in any way. Please see attached.

### Expected Behavior

To work on run or test so to be able to develop the app, as the alternative of developing on Xcode or Android studio defeats the purpose.

### Steps to Reproduce

1. Create new project with Firebase directly from flutter flow.
2. Ensure connection works
3. Added all possible Google Maps services on Google Cloud and inserted key to FlutterFlow
4. Added Map to new blank page.
5. Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l7YVgrsdc17qBYMdB/TwQHGYja5Eoscp/bxIgGIDzPOw+ZPWkVFRoUsviYwl9fESmmkgC7vT7iYTIUMICMk6VRqJ+zpFUTQ3gJV6WQZOBDLmwf0ZtO+dhG0ic38GzrhNTNth2W0IF12CQJfOAYALaQJDTImdISq/LZO4=

### Context

Simply using Google Maps in any app developing with FlutterFlow.

### Visual documentation

![1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2d38dea8-cfa9-43ab-b3cb-8904db743cfb/2b253b9f-0d72-47a3-99df-2bb004f01366?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZDM4ZGVhOC1jZmE5LTQzYWItYjNjYi04OTA0ZGI3NDNjZmIvMmIyNTNiOWYtMGQ3Mi00N2EzLTk5ZGYtMmJiMDA0ZjAxMzY2IiwiaWF0IjoxNzA4ODYyNzY0LCJleHAiOjMzMjc5NDIyNzY0fQ.67\_-WU5tjbo4FTeEDCJO8KkwO6bFbjPLK_o90gmHka0)

![2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8c485b33-801e-4cf4-bfc7-f39d08ef6d97/ac15b024-b445-4a45-af29-1ec053408bb9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84YzQ4NWIzMy04MDFlLTRjZjQtYmZjNy1mMzlkMDhlZjZkOTcvYWMxNWIwMjQtYjQ0NS00YTQ1LWFmMjktMWVjMDUzNDA4YmI5IiwiaWF0IjoxNzA4ODYyNzY0LCJleHAiOjMzMjc5NDIyNzY0fQ.oAxCO-IHdHOVGsiPtpMa__4sIn2uf62tg0WWnDbx1cU)

![3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/df9da5b1-4f17-4795-9001-a024c7e7b3fd/4416045f-85ab-4b3d-8f9c-6e55c53aeb5e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZjlkYTViMS00ZjE3LTQ3OTUtOTAwMS1hMDI0YzdlN2IzZmQvNDQxNjA0NWYtODVhYi00YjNkLThmOWMtNmU1NWM1M2FlYjVlIiwiaWF0IjoxNzA4ODYyNzY0LCJleHAiOjMzMjc5NDIyNzY0fQ.JzQQMHH7k2wfgm39CDNda15Tbk9sqYb7ptxOLMHRlWY)

![4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/46008b08-0045-4743-a859-127b864f8484/0d94e1fb-7d42-4a18-9ac7-9411a81d3309?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NjAwOGIwOC0wMDQ1LTQ3NDMtYTg1OS0xMjdiODY0Zjg0ODQvMGQ5NGUxZmItN2Q0Mi00YTE4LTlhYzctOTQxMWE4MWQzMzA5IiwiaWF0IjoxNzA4ODYyNzY0LCJleHAiOjMzMjc5NDIyNzY0fQ.JoIHE0InCW5POXDstsBw_sbZLBTgBwz0JG3aXIvF3T8)

![5](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7fece764-952e-451a-a9f5-fecfcf82133e/7f34e0be-3049-4128-a2e4-60880e1193f4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZmVjZTc2NC05NTJlLTQ1MWEtYTlmNS1mZWNmY2Y4MjEzM2UvN2YzNGUwYmUtMzA0OS00MTI4LWEyZTQtNjA4ODBlMTE5M2Y0IiwiaWF0IjoxNzA4ODYyNzY0LCJleHAiOjMzMjc5NDIyNzY0fQ.Not3I1gxI-OVSRmN87vtPItVHR0hxCaax19aae0EJTM)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Developing for iOS, Android & Web
- Browser name and version: Chrome Version 122.0.6261.69
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi - Thanks for submitting the issue. Is this similar to this issue #2357 ? Please check.

**Comment by Kato-iOS** [comment]
Hi @hariprasadms , yes it's the same. For some reason I did not find that issue earlier. I'll close this and follow the other one. Thanks for looking into it.
