### ISSUE TITLE
Compile Button doesn't work

### ISSUE THREAD

**Issue by StKing3** [FlutterFlow/flutterflow-issues#2388]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, in custom code widget I'm trying to compile my code, but once I click on button compile it doesn't do anything. It was working normally but after I put some of a items from marketplace it doesn't do anything anymore. Same thing happened to me in different project but just with code analyzer so I had to start a new project. The compile button works in different project, but in my main doesn!t work now.

![Snímek obrazovky 2024-02-26 011943](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/176d1d55-c312-41f8-b037-e5d8b15d70ea/9a479ac3-3dbc-4f5e-b2bf-227c6f690110?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzZkMWQ1NS1jMzEyLTQxZjgtYjAzNy1lNWQ4YjE1ZDcwZWEvOWE0NzlhYzMtM2RiYy00ZjVlLWIyYmYtMjI3YzZmNjkwMTEwIiwiaWF0IjoxNzA4OTM1ODgxLCJleHAiOjMzMjc5NDk1ODgxfQ.8-FN4uwaDU9Q2qFvUOjyLl5-r0Os4ot21UW1P6xurl4)

### Expected Behavior

Trying to compile my code.

1. Go to custom code 2)Click Add Widget 3)Name Widget 4)Make parameters and custom code 5) Check for errors 6)No Errors - go and click on compile button 7)Normally it starts running and return feedback - Error / Check - in my case it doesn't start working, I just click on button and nothing will happen.

### Steps to Reproduce

1. Go to custom code 2)Click Add Widget 3)Name Widget 4)Make parameters and custom code 5) Check for errors 6)No Errors - go and click on compile button 7)Normally it starts running and return feedback - Error / Check - in my case it doesn't start working, I just click on button and nothing will happen.

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89god9Y1rX2ae9WmWMROUh7RL00rdoacxAgfa74PJk+Yc/SUE5CTfazaHxiG2KanXwx+M6NuPLXL+wnHzOabL5l1qlQFhPPbFGQSrmVBZeVPGpQL9NUC36F5p2v2BInC/tYR2QB32GqP/CAdz6Cf9qOYwx5e6fDbOY=

### Context

I can't do anything custom now. Can't work with a custom code in FlutterFlow now.

### Visual documentation

![doesnt do anything](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/11f5873b-e7bf-4d8a-8723-571bce540f50/1bec5e9e-1da5-4962-a172-4bce231ff801?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMWY1ODczYi1lN2JmLTRkOGEtODcyMy01NzFiY2U1NDBmNTAvMWJlYzVlOWUtMWRhNS00OTYyLWExNzItNGJjZTIzMWZmODAxIiwiaWF0IjoxNzA4OTM1ODgxLCJleHAiOjMzMjc5NDk1ODgxfQ.Whv9SPNMB4_MmsHp8xDbLDJjgC8UZlyFju5ZXEQ2uw4)

![this one works](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6bc16986-7dd6-4306-83af-b20718a4b4ab/a1ddb871-2911-4c2a-8364-dbd51aaed9d4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YmMxNjk4Ni03ZGQ2LTQzMDYtODNhZi1iMjA3MThhNGI0YWIvYTFkZGI4NzEtMjkxMS00YzJhLTgzNjQtZGJkNTFhYWVkOWQ0IiwiaWF0IjoxNzA4OTM1ODgxLCJleHAiOjMzMjc5NDk1ODgxfQ.MDYu4BcNL9KjXOFNYMHlY6jeTpeIfJgk-23ZCKKBZ_g)

### Additional Info

![Snímek obrazovky 2024-02-26 011943](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/14d7a277-62ff-4fb7-8424-e30cb14ecf27/56c653d3-3480-4353-b838-5078b2fe1abc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNGQ3YTI3Ny02MmZmLTRmYjctODQyNC1lMzBjYjE0ZWNmMjcvNTZjNjUzZDMtMzQ4MC00MzUzLWI4MzgtNTA3OGIyZmUxYWJjIiwiaWF0IjoxNzA4OTM1ODgxLCJleHAiOjMzMjc5NDk1ODgxfQ.ktWZdfNY_35a20S1EBaRpalPuojmtglbyI2laEq8rx8)

### Environment

```markdown
- FlutterFlow version: v 4.1 Flutter 3.13.7
- Platform: Web
- Browser name and version: 122.0.6261.69
- Operating system and version affected: Windows 11 Home 22H2
```

**Comment by hariprasadms** [comment]
Hi @StKing3 - Could you please provide the bug report code for your project? This information is necessary to get access to your project. Kindly ensure the details are updated accordingly.

**Comment by StKing3** [comment]
Hello that Bug report code is in my bug report.

**Comment by StKing3** [comment]
There is another one: IT4gz/Hqx89god9Y1rX2ae9WmWMROUh7RL00rdoacxAgfa74PJk+Yc/SUE5CTfazaHxiG2KanXwx+M6NuPLXL+wnHzOabL5l1qlQFhPPbFGQSrmVBZeVPGpQL9NUC36F5p2v2BInC/tYR2QB32GqP/CAdz6Cf9qOYwx5e6fDbOY=

**Comment by hariprasadms** [comment]
Hey, I've checked out your project and didn't find any errors matching the description you provided above. However, there was a dependency warning in one of the custom widgets below. Have you had a chance to look into this? Is the issue resolved for you now?

<img width="415" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/53651a67-b3a5-4e82-ae75-db8ba7c42004">

**Comment by StKing3** [comment]
Hi Hari, thank you for your attempt. It seems like there is still the same problem, just see atteched video for detailed description of my issue. With that dependencies I know about it thanks. I already removed that dependencies, but the issue with compiling is not atteched to any of the custom widget it seems like it doesn't work for whole project. 

https://github.com/FlutterFlow/flutterflow-issues/assets/161262132/a97557ac-e76d-4c60-afdd-d4f9c8a1582d

**Comment by StKing3** [comment]
Hi Hari, thank you for your attempt. It seems like there is still the same problem, just see atteched video for detailed description of my issue. With that dependencies I know about it thanks. I already removed that dependencies, but the issue with compiling is not atteched to any of the custom widget it seems like it doesn't work for whole project.


https://github.com/FlutterFlow/flutterflow-issues/assets/161262132/affbe1fc-7b8b-4b32-9e9d-0d3b667add34

**Comment by StKing3** [comment]
Hi Hari, for clearification the end action is in another project. That is what I was talking about. So the thing is, that the compilation button doesn't work in my main project where it worked before and then suddenly stoped working for no obvious reason. I'm not reporting about compiltion result, so it doesn't really metter if compilation failed or not. But again it was different project in which that compilation started, In my main project it just doesn't do anything, there is a button animation once you click on that compiling button but it jsut doesn't do anything. I atteched 2 more videos so you can see more clearly. The 1st video starte with my main project and then you will see the rest pretty clearly I guess, If you would have any more questions just let me know, thank you. 


https://github.com/FlutterFlow/flutterflow-issues/assets/161262132/e0bc73d2-a086-4175-848a-2229e5d9d43c



https://github.com/FlutterFlow/flutterflow-issues/assets/161262132/2f4df601-4ee7-4f49-9faf-1e0ffe40119e

**Comment by StKing3** [comment]
Hey Issued has been resolved with one of your collegues by contacting support email. Thank you. Just FYI, the problem was actually in builder with one of the toggle button: 

''.​I've taken a look at your project and it seems that there are two toggle buttons causing issues with the custom code compiling. Don't worry, I can help you fix this. You can either provide these widgets with a default boolean variable or remove them, and the custom code will compile perfectly.​''

So if somebody would have a similar problem, the compiling button can be probably affected by some errors in builder which aren't correlated to custom widget.

**Comment by ped-84** [comment]
I've got another issue with compile button and that is not appearing at all. I would appreciate If you can help me why it doesn't exist!
![complile](https://github.com/user-attachments/assets/ed0bf08b-fd28-45b2-95e5-3183ffc91fb0)

**Comment by ped-84** [comment]
Another Issue is that when I switch tabs, e.g. go to Code Copilot tab and come back, code dissapears!!
![Uploading saveissue.jpg…]()

**Comment by darshitsoftrefine** [comment]
Also getting the same issue as @ped-84

**Comment by darshitsoftrefine** [comment]
when adding custom function simply return cartItems and then click on Save then the compile button will appear. Worked for me.
