### ISSUE TITLE
Passing sqlite row as page parameter results in null values

### ISSUE THREAD

**Issue by AndreReginattoPoupante** [FlutterFlow/flutterflow-issues#2389]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When passing a sqlite row as page parameter results in null values.

### Expected Behavior

When passing a sqlite row as page parameter, the second page should get the parameter

### Steps to Reproduce

1. Create two pages
2. Create a list view in page 1
3. Attach a sqlite query to the list view in page 1
4. Add a button to list view
5. On tap of button navigate to page 2 passing the sqlite row as page parameter for page 2
6. Define the page parameter as sqlite row in page 2 to accept the incoming data
7. Create a text field on page 2 to display the incoming data and set the text property to one of the columns of the incoming row

result:

The incoming data in page 2 will be null and fall back to the default value

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Got and error: Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Context

I was trying to edit a sqlite row, but couldn't get the current data on the edit page.

### Visual documentation

When clicking "Editar categoria"("Edit category") goes to the edit page without the data of the category to edit

![Screenshot_2024-02-26-09-31-44-320_com parable poupante](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/31abc82a-160b-4705-8358-f1e04c163dff/324f13e6-83a1-44c7-b4cc-70c3c4d25d6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMWFiYzgyYS0xNjBiLTQ3MDUtODM1OC1mMWUwNGMxNjNkZmYvMzI0ZjEzZTYtODNhMS00NGM3LWI0Y2MtNzBjM2M0ZDI1ZDZhIiwiaWF0IjoxNzA4OTc0OTQxLCJleHAiOjMzMjc5NTM0OTQxfQ.jQ5VPe5m5QUxuQiEBFQpeJ1jZPCKbdumkl5LldpL2HE)

![Screenshot_2024-02-26-09-31-48-182_com parable poupante](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/665dad08-bc2a-4cce-9b78-f08485000cd0/3733c3a5-4f90-4065-83b2-e555414a67d9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NjVkYWQwOC1iYzJhLTRjY2UtOWI3OC1mMDg0ODUwMDBjZDAvMzczM2MzYTUtNGY5MC00MDY1LTgzYjItZTU1NTQxNGE2N2Q5IiwiaWF0IjoxNzA4OTc0OTQxLCJleHAiOjMzMjc5NTM0OTQxfQ.BEoOhh4WXFTpm7BTSrR5d1W8RuDKfrA7oC69H04IUB0)

### Additional Info

I could resolve this issue on my code by adding the type of the sqlite row on the params.getParam.

This is the code I got from Flutter Flow:

![Screenshot 2024-02-26 at 09 12 18](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6b326ec0-63ee-47d3-ba11-9ee6d2f583c2/2d3060a8-620d-426b-8844-60c32bb12bc1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YjMyNmVjMC02M2VlLTQ3ZDMtYmExMS05ZWU2ZDJmNTgzYzIvMmQzMDYwYTgtNjIwZC00MjZiLTg4NDQtNjBjMzJiYjEyYmMxIiwiaWF0IjoxNzA4OTc0OTQxLCJleHAiOjMzMjc5NTM0OTQxfQ.SXmw4AxF48fKUfkPlYrc9L_AvVefeRLL4Ke93VsOi0s)

This is my code that worked, I just added SelectCategoriesIsDefaultRow Type to the getParam:

![Screenshot 2024-02-26 at 09 13 59](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/264e125c-4ba3-42f8-ab4f-8fd6c7f7b93d/fc21b637-4351-42f1-873f-372bf1c4e43e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNjRlMTI1Yy00YmEzLTQyZjgtYWI0Zi04ZmQ2YzdmN2I5M2QvZmMyMWI2MzctNDM1MS00MmYxLTg3M2YtMzcyYmYxYzRlNDNlIiwiaWF0IjoxNzA4OTc0OTQxLCJleHAiOjMzMjc5NTM0OTQxfQ.NZda0hvRZCrrdb7a-0SDPg2pXxS7wZhdvMa1U7A4KEY)

I noticed that the issue is on deserializeParam, that is inside the getParam.
Inside the deserializeParam, on the case ParamType.SqliteRow, the code checks the type of class T, but it doesn't had a type.

![Screenshot 2024-02-26 at 09 16 07](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d979874c-1b09-4dbd-93e4-6da23fd4bc0b/791a211d-54ed-4942-85cd-fe31e827d9b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kOTc5ODc0Yy0xYjA5LTRkYmQtOTNlNC02ZGEyM2ZkNGJjMGIvNzkxYTIxMWQtNTRlZC00OTQyLTg1Y2QtZmUzMWU4MjdkOWI5IiwiaWF0IjoxNzA4OTc0OTQxLCJleHAiOjMzMjc5NTM0OTQxfQ.svB5hRjrUf4Q_1uOFee-SanTtm8H2RC-INVqEnvsQ6c)

As the "T" did not have a type, the code passed directly and the parameter was always null.
I passed the sqlite row type and it worked.
Of course, maybe this isn't the right way to solve it, but this is as far as I managed to get and it solved the problem.

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Safari, Version 17.2.1 (19617.1.17.11.12)
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hey @AndreReginattoPoupante, Could you share your project code with me? Also, could you point me to the page you're referring to? Having these details will help speed up the process of diagnosing the issue and determining its status.

**Comment by rzambroni** [comment]
Hi, @AndreReginattoPoupante, are you still experiencing this issue? if so, would you mind please sharing the details @hari is asking for in the above message? It would be really helpful for us. Thanks a lot!

<br>If this issue is no longer relevant feel free to close it! 

Thanks!
