### ISSUE TITLE
Refresh Database Request - Wait For Result Not Working

### ISSUE THREAD

**Issue by olivierb24** [FlutterFlow/flutterflow-issues#2390]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a "refresh database request" action is used, the request is correctly refreshed, but the subsequent actions use the previous results, and not the most recent request results.

### Expected Behavior

when using "refresh database request" and selecting the "wait for results" switch, subsequent actions should use the most recent data received from the database request.

### Steps to Reproduce

1. Create New Page
2. Add a textfield input 1
3. Create an API call that can return an array of varying length based on textfield input 1
4. Add a backquend query API call on top container

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d937eb74-39fd-484d-98a2-a025f4619950/9fd136ab-f656-4552-9554-205e80333efd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kOTM3ZWI3NC0zOWZkLTQ4NGQtOThhMi1hMDI1ZjQ2MTk5NTAvOWZkMTM2YWItZjY1Ni00NTUyLTk1NTQtMjA1ZTgwMzMzZWZkIiwiaWF0IjoxNzA4OTc0OTE2LCJleHAiOjMzMjc5NTM0OTE2fQ.Pwr5Dt7f76-UH4fiAVR84Z6seGGzPtCoOHW4Gel8Jcs)

1. Create a page variable named "itemsProcessed"

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/25a4ee19-bdfc-448d-abee-3aeedca04d14/af49ad6f-a68a-4b2a-8d6c-0e647332547e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNWE0ZWUxOS1iZGZjLTQ0OGQtYWJlZS0zYWVlZGNhMDRkMTQvYWY0OWFkNmYtYTY4YS00YjJhLThkNmMtMGU2NDczMzI1NDdlIiwiaWF0IjoxNzA4OTc0OTE2LCJleHAiOjMzMjc5NTM0OTE2fQ.4-HO4-BDqTSIQqlROyB_mJzdSv6ipWkkCEp5fKJiTRU)

1. Add an action chain that does the following

6\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.1 "refresh database" (with await results)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/18d8bc00-ef7b-4256-9ef6-f81a54c83079/0a37373d-c8b5-41e2-b572-02fee8e13c1e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xOGQ4YmMwMC1lZjdiLTQyNTYtOWVmNi1mODFhNTRjODMwNzkvMGEzNzM3M2QtYzhiNS00MWUyLWI1NzItMDJmZWU4ZTEzYzFlIiwiaWF0IjoxNzA4OTc0OTE2LCJleHAiOjMzMjc5NTM0OTE2fQ.UXQRohYlFo1LzYiFQizC1zhNIME_lPF6W5_mmMbB5yk)

6\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.2 "update page variable" with the number of items received from the updated query

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/950b1e53-33cd-44c5-aeca-64d8660e6164/6f29faa6-4ea4-476b-972e-f2d0addaf93e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NTBiMWU1My0zM2NkLTQ0YzUtYWVjYS02NGQ4NjYwZTYxNjQvNmYyOWZhYTYtNGVhNC00NzZiLTk3MmUtZjJkMGFkZGFmOTNlIiwiaWF0IjoxNzA4OTc0OTE2LCJleHAiOjMzMjc5NTM0OTE2fQ.zd7YCTW-OUxC6HUZjibJlbk_l__o5Ayoyxa6L4YlayI)

1. Display both the number of items from the query AND the page variable "itemsProcessed"

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7647f464-6f57-400f-b28d-4409b1b04741/15c54eed-86e2-4303-b466-ce75c99b573c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NjQ3ZjQ2NC02ZjU3LTQwMGYtYjI4ZC00NDA5YjFiMDQ3NDEvMTVjNTRlZWQtODZlMi00MzAzLWI0NjYtY2U3NWM5OWI1NzNjIiwiaWF0IjoxNzA4OTc0OTE2LCJleHAiOjMzMjc5NTM0OTE2fQ.HQEXCIAs9HYMu0O0EyvmsB6Fa96Jxc6uWnhR3TXXzN4)

1. Notice how the text (number of items from query) is updated dynamically but the page variable is not, meaning that the action executed after our refresh database used our previous API results.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPm9tH1s7yKcB7/SAsJUgmaOcSscp/bxIgGIDzPOw+ZPXsTxBucM+qd0FHe0SmmkcD0srpuOPPNcAqF0yuG5hnybpfWgHxWkyWa5OBO8/tSXJAI5tTfW6e5sK3sSUmHNBqdCEu3GaTfuSvaAPDNZTBIndISq/LZO4=

### Context

Utilizing refreshed data is not possible. UI components update correctly but actions that run immediately after the "refresh database" don't use the correct results.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c20610f5-702b-496e-94ce-f84acf07045c/9ee4e587-6f6c-4658-9dee-98c8f3615f0e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMjA2MTBmNS03MDJiLTQ5NmUtOTRjZS1mODRhY2YwNzA0NWMvOWVlNGU1ODctNmY2Yy00NjU4LTlkZWUtOThjOGYzNjE1ZjBlIiwiaWF0IjoxNzA4OTc0OTE2LCJleHAiOjMzMjc5NTM0OTE2fQ.4yCBhDMoxW4F1V8j1GGrhZgT-fjozAF-0d6PmCTrRx8)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome Version 122.0.6261.69 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by TerenceStupple** [comment]
I also have this exact issue.

**Comment by olivierb24** [comment]
@takashiff Any updates on this issue? Seems like it's still not working

**Comment by takashiff** [comment]
Hi @olivierb24, I apologize for the delayed response. We're currently taking a look into this issue. Thanks

**Comment by takashiff** [comment]
Hi @olivierb24, I've done some testing, and this looks to be intended behavior based on the generated code. Since the `setState` action is being called in the same `buildContext`, the API call response in the current snapshot is not updated since the page has not yet been rebuilt when `setState` is called. Thus, even though the database request has been refreshed, since we are still working in the same `buildContext` as before it was refreshed, that it why the old value is showing up. I would recommend adding an action at the page-level ('On Page Load') to achieve your desired behavior. Hope this helps. Thanks
