### ISSUE TITLE
The RevenueCat Subscription Bottom Sheet component links to a non-existent style color

### ISSUE THREAD

**Issue by blistick** [FlutterFlow/flutterflow-issues#2392]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I installed your component, "RevenueCat Subscription Bottom Sheet", from the FlutterFlow marketplace. When I tried to test my project it failed to build. Upon investigation I found that a couple of the containers in the component were specifying a non-existent color (weatherCloudy). That theme, which I assume is part of the full sample project, diesn't exist for the component.

### Expected Behavior

The component should be able to be installed and used as is. The component should not rely on a custom style.

### Steps to Reproduce

1. Create new project
2. Create new page
3. Add component to project from marketplace
4. Use component on page
5. Try to test/run the project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I ALREADY FIXED IT IN MY CODE

### Context

The issue cost me time to track down the bad color references. The issue will happen to anyone who installs the component, so I'm trying to help save others from the hassle of having to fix it on their own.

### Visual documentation

None needed.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Desktop browser
- Browser name and version: Brave 1.62.165
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @blistick - Thank you for reporting the issue. Could you please provide the component link and also share a few images showing exactly what you are experiencing as the issue? This information will help us to resolve the bug promptly. Thank you.

**Comment by blistick** [comment]
Hi Hari,

The link to the component that's causing the issue is:

https://marketplace.flutterflow.io/item/gI3aaZdslZgxKhN1E6bP

As I mentioned before, I've already fixed this in my project and I'm not
going to take the time to recreate it for your benefit. I've provided all
of the information necessary for someone at FlutterFlow to fix it.

Best,

Barton

**Comment by takashiff** [comment]
Hi @blistick, thank you for the bug report. This component looks to be an item created by RevenueCat, and is not something we can directly control. I would advise reporting the item as 'Broken' on the Marketplace Item page. Thanks
