### ISSUE TITLE
DateTime send to supabase database lacks timezone details

### ISSUE THREAD

**Issue by danny-support-flutterflow** [FlutterFlow/flutterflow-issues#2393]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When updating or sending datetime time details to supabase timestamptz row, timezone details are not sent

### Expected Behavior

Timezone details should be sent , from FF datetime data type when converting the date to timestamptz

### Steps to Reproduce

1. Create a page with a button /action. that send datime time info to a supabase row
2. Create supabase table with timestamptz
3. Add a place holder time , using now() to create a specific time in supabase
4. Update the row with datetime from Fluterflow and observe the time zone is not sent

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/qy5d1m8tK7q6JKflagmA5KUg5bYEVlux7aCgoIYyuOpl/evWlZRBCTcu4dGNmMESmmkMxpdbxv4XpJMI6ZDCbQJxkwZFxVQ/ie3OuUZOBPM28enAlTJ9VGH6k4bSwkR4mB7NpS3gf7TiuBt7Ja3TaNrWwIndISq/LZO4=

### Context

N/A

### Visual documentation

N/A

### Additional Info

N/A

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: FF Web
- Browser name and version: Chrome - Version 122.0.6261.69 (Official Build) (arm64)
- Operating system and version affected: MacOs Sonoma
```

**Comment by hariprasadms** [comment]
Hi @danny-support-flutterflow, Thank you for submitting the issue. I have tested the above steps. Below is the date details inserted to supa-base fields. To clarify further, could you specify the time zone you expect to be inserted into the Supabase time and timestamptz fields for a better understanding of your expectation?

<img width="841" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/c2ac3d1d-07dd-476e-96d5-37d21eaaaadb">

**Comment by danny-support-flutterflow** [comment]
Hello @hariprasadms, thank you for taking the time to review this issue. From the screenshot that you shared, it is the same that I get when testing the time update. I changed my testing timezone to ( +1,+3, -5), but none of this gets reflected. The time zone remains (+00), as shown in the screenshot.

You can confirm this with your current time zone and check if it is the same as the one shown in supabase.

**Comment by barrhavensolutions** [comment]
I have the same question. I live in Canada so it should show -05 but it showing +00.

**Comment by danny-support-flutterflow** [comment]
> Hey, how did you switch the time zone to (+1, +3, -5)? I didn't notice those changes in the project link you shared above. It seems to mostly stick to the current time.

I did Changed the timezone by using a VPN, the reset back to default.

**Comment by davhad** [comment]
How about if a team member *fix* the bug?

**Comment by takashiff** [comment]
This looks to be a duplicate issue with #2125. Please refer to the aforementioned thread for further updates. Thanks

**Comment by SebyOnGitHub** [comment]
@takashiff This does not appear to be a duplicate problem with https://github.com/FlutterFlow/flutterflow-issues/issues/2125.
In this case, the problem is not querying the time, but uploading the time to the supabase.
The other bugfix converts timetz to local when loading from supabase. But we still need to be able to send the timezone along with the time to the timetz supabase.
