### ISSUE TITLE
Conditional action on Supabase timestamptz is not functioning

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#2396]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a conditional action based on a timestamptz in a Supabase row, the action cannot be completed.

### Expected Behavior

You should be able to use conditional actions based on a timestamptz. For exammple, comparing it to now or to another date.

### Steps to Reproduce

Create a supabse table with one of the columns being a timestamptz.
Create a column querying one element from this table in Flutterflow
create an on page load or on tap action flow where the first step is a conditional action.
Choose the timestamptz column as the conditional field and attempt to continue that flow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grs9J1s/IdfoxnSQWKW1/a50e0MpBazwbfe+uB4kqevfOTERCcNO8dEFEf1r8u2oW0/SPjoTpCsFfNQSBbJhg+boAEArvTk6nbLWaFJWge3AkM8RnGEyg4au0kxMnVLJpcWQA32eMFu+udArdGOPqNUVBDq/LZO4=

### Context

Can't compare or access dates (if present or not) and therefore unable to mark the items as read.

### Visual documentation

![Screenshot 2024-02-26 at 23 05 44](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/154f1ce5-aadb-4395-8199-8a4188d47919/63906be1-75e8-40a9-bc56-ee91f2bf04d7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNTRmMWNlNS1hYWRiLTQzOTUtODE5OS04YTQxODhkNDc5MTkvNjM5MDZiZTEtNzVlOC00MGE5LWJjNTYtZWU5MWYyYmYwNGQ3IiwiaWF0IjoxNzA5MjI1OTU4LCJleHAiOjMzMjc5Nzg1OTU4fQ.aofe_DOK-evPFFiXC6eTrqf-MxZBzWBAsg8wckhFNxk "=1017x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: Macos
```

**Comment by victoriahuang1** [comment]
@davhad  I cannot reproduce the bug. I am able to use supabase timestamptz in conditional actions.

Based on the screenshot, it looks like you are trying to directly plug-in, the timestamptz into the condition. However, the intended case is to first select condition and then put the timestamptz as a field inside of a condition. Have you tried that?

<img width="1177" alt="Screenshot 2024-04-10 at 12 28 15 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/94629712-584c-48fd-893a-00ad53dff4f3">

**Comment by davhad** [comment]
What do we do if we want to set that timestamptz value on a supabase field?

--
David Haddad

**Comment by victoriahuang1** [comment]
> What do we do if we want to set that timestamptz value on a supabase field?

You would use the update row action.

**Comment by davhad** [comment]
Hey Victoria, I know that :)

But are you able to set the timestamptz value on an update? If yes can you
post a screenshot?

--
David Haddad

**Comment by victoriahuang1** [comment]
@davhad hope this helps

<img width="1184" alt="Screenshot 2024-04-11 at 9 06 22 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/7284b16c-fea1-4ec6-afd0-1f1de5e5e8ae">

**Comment by davhad** [comment]
An arbitrary timestamptz value other than current time

--
David Haddad

**Comment by leighajarett** [comment]
Hi @davhad this seems like you're looking for some help with your app architecture / design. I would suggest posting your question on community.flutterflow.io or reaching out to our support team. 

This tracker is only for bugs reproducible from a blank project. Thank you
