### ISSUE TITLE
Collapsible SliverAppBar does not respect the Safearea

### ISSUE THREAD

**Issue by ssdesign** [FlutterFlow/flutterflow-issues#2398]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I have a SliverAppBar in my project with Collapsible and floating behavior, the appbar and the app content do not respect the safearea and the content goes behind the safe area.

![unnamed](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/90d332c8-56fe-4b96-acda-ef9753c3ba35/7165d9f0-d4da-4dff-8d8f-aebfad501f8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MGQzMzJjOC01NmZlLTRiOTYtYWNkYS1lZjk3NTNjM2JhMzUvNzE2NWQ5ZjAtZDRkYS00ZGZmLThkOGYtYWViZmFkNTAxZjhlIiwiaWF0IjoxNzA5MTMyMDg5LCJleHAiOjMzMjc5NjkyMDg5fQ.B41az9zOp0opniClxMcNqAxSId0dGY6ZsItWbGmIfS8)

### Expected Behavior

The Appbar should stay below the safe area when collapsing and the content should not scroll behind the safearea.

### Steps to Reproduce

1. Create a blank app.
2. Toggle "Safearea - On" on the page.
3. Select the AppBar and set following Appbar behaviour: Collapsible = On, Floating = On
4. Add somecontent on the page and make it scrollable.
5. Now test the app.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wz/Hqx89grsND1aXidcBr/TgWOUs7ULg7m8NxZ0sgF4DrO7YPXfikSEpWZ9+kTHxcL2K0rH0ypv/GuPzMA+UqNSubGZxRyqVcbBfwWjmuaLLUDsyOQEBREZpJJVy035+vrxB4GPZoL2xk11OUBOiRYD/dJK6yDWwRGfGLBN/4+0mqQ0SLb3kNh1JWeC/v

### Context

We are building an app that uses collapsible sliverappbar and we are not able to achieve the desired behaviour and that is causing poor user experience for our app.

### Visual documentation

![unnamed](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5331d70e-22b5-414c-8107-5dd6f9465c5e/84e77c4b-72bb-4a4e-a1ce-0c939e0c1dd0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MzMxZDcwZS0yMmI1LTQxNGMtODEwNy01ZGQ2Zjk0NjVjNWUvODRlNzdjNGItNzJiYi00YTRlLWExY2UtMGM5MzllMGMxZGQwIiwiaWF0IjoxNzA5MTMyMDg5LCJleHAiOjMzMjc5NjkyMDg5fQ.1_j3w1iG_5sPwEiWMoO4qG3r3FUpV7NZZwW0gOBoz9A)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: MacOS
- Browser name and version: Chrome Version 122.0.6261.69 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.3.1
```

**Comment by takashiff** [comment]
Hi @ssdesign, thank you for your bug report. Could you provide the device that you are experiencing this issue on? I am currently unable to reproduce it using iPhone 15 Pro Max and Google Pixel 6 emulators. Thanks

**Comment by ssdesign** [comment]
Hi,
This cannot be reproduced on Emulator.
Test it on a device.

I tried it on the iPhone 14 pro and Blu Android phone.

Thanks
Sajid

**Comment by ssdesign** [comment]
Is it resolved?
I am still facing this issue.

**Comment by AnushaFF** [comment]
Hi! thanks for the report. But unfortunately, it is a flutter widget and this is the expected behavior when the 'floating' option is toggled. More about it can be found here: https://docs.flutterflow.io/widgets-and-components/widgets/page-elements/appbar#adding-sliverappbar
