### ISSUE TITLE
Unable to input Component Name 

### ISSUE THREAD

**Issue by tsu2024** [FlutterFlow/flutterflow-issues#2399]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to convert what I build into a component, but when the Component Name screen pop up. I'm unable to input text in the field. The box blinks instead of text appearing.
 
<img width="1440" alt="Screenshot 2024-02-28 at 3 35 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/161570183/37f5f59f-0325-410d-819e-5384a7a26c03">

### Expected Behavior

Component Name screen to be able to input text to name the component which next can create the component.

### Steps to Reproduce

1. Create project
2. Create page
3. Build widget tree with widgets.
4. Right click, select "Convert to component". Component Name screen will pop up.
5. Input Component Name
6. Click on "Create"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

unable to retrieve

### Context

Unable to create components in project to be used in pages

### Visual documentation

<img width="1440" alt="Screenshot 2024-02-28 at 3 35 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/161570183/c91d1b0e-ae8a-48c9-bfde-941183125d12">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Safari
- Operating system and version affected: macOS Sonoma 14.4 Beta 5
```

**Comment by hariprasadms** [comment]
Duplicate #2387
