### ISSUE TITLE
Custom Component with Custom Data Type parameter - Compile Error

### ISSUE THREAD

**Issue by UniBrowse** [FlutterFlow/flutterflow-issues#24]
## Expected behavior (required)
Able to pass a custom data type as a parameter to a custom component.

## Current behavior (required)
This error is shown when compiling:
`
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/components/custom_component_widget.dart:14:9: Error: Type 'CustomDataTypeStruct' not found.
  final CustomDataTypeStruct? info;
        ^^^^^^^^^^^^^^^^^
lib/components/risk_benefit_card_widget.dart:14:9: Error: 'CustomDataTypeStruct' isn't a type.
  final CustomDataTypeStruct? info;
        ^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         45.9s
Failed to compile application.
`

## To Reproduce (required)
1. Create custom component
2. Define parameter with type set to "CustomDataType"
3. Create new page
4. Add the custom component to the page
5. Set parameter of "CustomDataType" to value (from backend query)
6. Run project in test mode

## Context (required)
You must have the custom data type defined in the firestore menu and query a document containing a field with that type.

## Your environment
* FlutterFlow Version: 3.0.5
* Platform: Web (Run: Test Mode)
* Browser: Chrome Browser 
* Operating System: Windows Desktop

**Comment by agreaves** [comment]
This is now fixed!
