### ISSUE TITLE
How can I get Existing flutter-flow project Keystore/JKS File

### ISSUE THREAD

**Issue by ZiyadgodilDev** [FlutterFlow/flutterflow-issues#2400]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have built an app using FlutterFlow and successfully published it on both the Play Store and the App Store through FlutterFlow. Now, I have downloaded the code to make some changes that are not feasible within the FlutterFlow platform. Consequently, I need to manually deploy the app using the signing certificate and the existing JKS/Keystore files. Could you please guide me on how to obtain the necessary files from FlutterFlow?

Thank you in advance for your support.

### Expected Behavior

Need to be Export Existing JKS / Keystore file from Flutter flow

### Steps to Reproduce

Need to be Export Existing JKS / Keystore file from Flutter flow

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Need to be Export Existing JKS / Keystore file from Flutter flow

### Context

Need to be Export Existing JKS / Keystore file from Flutter flow

### Visual documentation

Need to be Export Existing JKS / Keystore file from Flutter flow

### Additional Info

Need to be Export Existing JKS / Keystore file from Flutter flow

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Android
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hi, This issue details looks like question but not an issue with the functionality. Post the questions in [FlutterFlow community](https://community.flutterflow.io/) to get answers. Or you can reach FF support team using chat window in FF editor.
