### ISSUE TITLE
Snackbar Duration can't be changed to less than 2000ms

### ISSUE THREAD

**Issue by KevDev99** [FlutterFlow/flutterflow-issues#2401]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using the Action "Show Snack Bar" gives the option to set the Duration in ms. When changing the value it is not saved after reopening the Action Tree. Example: Changed from 2000ms to 1000ms -> press the Close Button -> reopen the Action Tree: Action shows still 2000ms

### Expected Behavior

Duration can be changed and the changed value will be saved.

### Steps to Reproduce

Using the Action "Show Snack Bar" gives the option to set the Duration in ms. When changing the value it is not saved after reopening the Action Tree. Example: Changed from 2000ms to 1000ms -> press the Close Button -> reopen the Action Tree: Action shows still 2000ms

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcjfz4VNseFd0a6Jc8ZVlWQQHF8cTIMziNZ+exUbfaL1Bu0QfPf4SE5CUsO6aVNcP1D8+HE0wMrVjs7pA+w5NS2CbJxhybhyTwv0e2iXVamVC5eCdHd8P+RhGkzD1rSVrREmB/huWHhg7TqEF9mQdHfDIuu/Zwh9f6PHaOI=

### Context

tried it multiple times also waited some seconds before clicking on the close button as i thought it is a sync issue.

### Visual documentation

**Start:**

![Screenshot 2024-02-28 at 10 06 05](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/664e06a1-93c5-443e-bdcb-79fa3bc05698/c0469360-15de-48cb-bc1b-356d56f0f553?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NjRlMDZhMS05M2M1LTQ0M2UtYmRjYi03OWZhM2JjMDU2OTgvYzA0NjkzNjAtMTVkZS00OGNiLWJjMWItMzU2ZDU2ZjBmNTUzIiwiaWF0IjoxNzA5MTI4ODU2LCJleHAiOjMzMjc5Njg4ODU2fQ.F9bxvveioQSCv6T74aE_MbeQXbFVfJPCXqN6yqkRtLE)

**Changed to 1000ms:**

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9bf76b93-6a2b-4d9c-99a4-0f5d3010331f/b478ed8f-8657-4cda-8171-096753b91d49?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YmY3NmI5My02YTJiLTRkOWMtOTlhNC0wZjVkMzAxMDMzMWYvYjQ3OGVkOGYtODY1Ny00Y2RhLTgxNzEtMDk2NzUzYjkxZDQ5IiwiaWF0IjoxNzA5MTI4ODU2LCJleHAiOjMzMjc5Njg4ODU2fQ.oxcgn1N8FA2g-AiZ5GzYaqUcoGPScTi5HOsn8pvrmOU)

**Reopening: Wrong initial value is set**

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/993c26c8-2ddd-4bd1-aa67-84663c16beb7/c126f315-08f5-41c4-9520-b10bc1eb4ac1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OTNjMjZjOC0yZGRkLTRiZDEtYWE2Ny04NDY2M2MxNmJlYjcvYzEyNmYzMTUtMDhmNS00MWM0LTk1MjAtYjEwYmMxZWI0YWMxIiwiaWF0IjoxNzA5MTI4ODU2LCJleHAiOjMzMjc5Njg4ODU2fQ.Xck4-aWbP7mZz5NMxqTnGzr5xneOLagiB5r01L19ThU)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome 122.0.6261.69
- Operating system and version affected: MacOS Darwin 23.3.0
```

**Comment by KevDev99** [comment]
Just found out it is only when there are two "Show Snack Bar" in the Action Tree the one showing later takes the time from the parent one, although this makes not much sense to me. One could be 3 seconds the other only 1 second for example...

**Comment by hariprasadms** [comment]
@KevDev99 - I just verified it. It is working as expected.
