### ISSUE TITLE
The FetchEvent for "https://.region("southamerica-east1") corsProxy the promise was rejected.

### ISSUE THREAD

**Issue by tudotubestudio** [FlutterFlow/flutterflow-issues#2403]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I started to feel a huge slowdown until the webapp crashed, looking at the console, I saw that there was a cors proxy error. Analyzing the status of flutterflow services, I also noticed that there was an error in the custom domains, today 02/28. Any expected return?
![Captura de tela 2024-02-28 121628](https://github.com/FlutterFlow/flutterflow-issues/assets/138179563/5766ceab-6881-4ff5-bcea-343412c21560)
![Captura de tela 2024-02-28 143311](https://github.com/FlutterFlow/flutterflow-issues/assets/138179563/c4061abb-e0bf-4277-81fa-65a7ad8a0710)

### Expected Behavior

Last night, I was recording normally and there were no changes to the project until I noticed that part of the files were not being recorded.

### Steps to Reproduce

Use a Loop to create 20 or more documents in firestore, the problem starts here.
![Captura de tela 2024-02-28 143615](https://github.com/FlutterFlow/flutterflow-issues/assets/138179563/716860fe-152b-4ae8-914d-84a70e73e927)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ismBw892pbxA+Kr1bfpR/Sc5KUs7bZIOmMF9exE8KOPdOoYUP8+kM0RBZ7XmTHNAImf8r2oW0vz5ivPDOO4ECEysfKJczpZUewzgTlyQR7HWFJWgeHNCO8RUfUuP15m33B5BOrNqLS04317zJ9m9YALbQ7LzPFQeDq/LZO4=

### Context

At this stage, the button generates the employees' annual agenda, checks which dates and in a loop it creates the document for each day, using the largest list it had, yesterday it took 40 seconds, the total recording, using 1/10 from the list, it took 8 minutes and was not completed, most of it didn't even record, it was rejected by firestore.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/138179563/647b73e6-f470-4db1-9e1c-dfd1f202c712

### Environment

```markdown
- FlutterFlow version: v4.1 released
- Platform:Web
- Browser name and version:Chrome 122.0.6261.71, Brave: Versão 1.63.162
- Operating system and version affected: Windows 11, 23H2
```

**Comment by rzambroni** [comment]
Hey @tudotubestudio, sorry about the delay in the response, we are trying to get up to speed with everything.

Are you still experiencing this issue or did you have any other occurrences after this event?
