### ISSUE TITLE
Supabase email update

### ISSUE THREAD

**Issue by 66leo** [FlutterFlow/flutterflow-issues#2405]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Supabase Auth action "Update Email" sends an email to the current email address rather than the new one.
A confirmation email is sent to the current address and therefore the link doesn't verify the new one.
The mail address is therefore not updated.

### Expected Behavior

A confirmation email sent to the new address.

### Steps to Reproduce

1. Create new project
2. Connect Supabase account
3. Enable Supabase authentication
4. Create new page
5. Insert 4 textfields (email, paswd1, paswd2 and email_update)
6. Insert 3 buttons (Sign In, Log In, Update Email)
7. Implement the action Sign In with 'email', 'pswd1', 'pswd2'
8. Implement the action Log In with 'email' and 'pswd1'
9. implement the action Update Email with email_update
10. Sign In and verify address via confirmation email
11. Log in with credentials
12. Update Email action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocdb0ZfucOxAhQAkH1x/bZJEl9cbFEkjJb7zO7N/O+r+VFdpX+mHTHx+E1K0pHoK0/T5ivzhMMY5AxCqQoNozqhcbAKXYEWRVZS7EauCQHJRI8NRG2GB0rSNnh5BBPZtL04gw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Update a user email

### Visual documentation

<img width="350" alt="Screenshot 2024-02-29 at 08 51 30" src="https://github.com/FlutterFlow/flutterflow-issues/assets/161693876/8f45a7a0-9f3e-4640-8a32-421ce0ef9fdc">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by 66leo** [comment]
Visual documentation is limited because I'd have to upload my email address and reference it to the auth schema.

**Comment by hariprasadms** [comment]
Hi @66leo - Thanks for submitting the issue. I have tested the above steps. I can confirm that it is working as expected. When user is authenticated and perform update email action, it eventually triggers a notification with email change link to new email address saying below message. This is expected. 

<img width="734" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/751ce906-a6d2-4695-83c8-da2aedc8c58f">

Refer supabase email update guide, step 2 here - https://www.restack.io/docs/supabase-knowledge-supabase-email-change-guide. This says that _'Supabase will send a confirmation email to the new address. The user must click the link in the email to verify the new email address'._

**Comment by 66leo** [comment]
This happens both with the integrated Supabase Auth action and with this custom action

`Future changeEmail(String newEmail) async {
  final response =
      await SupaFlow.client.auth.updateUser(UserAttributes(email: newEmail));

  if (response.user != null) {
    return true;
  } else {
    return false;
  }
}`

**Comment by 66leo** [comment]
I just deactivated the SMTP provider (still in sandbox) If you want to get inside the project and try it yourself with the built-in Supabase email service. I've also contacted Supabase but the support didn't feel it was their problem.

**Comment by hariprasadms** [comment]
Hi @66leo - I understand your point. In this case, I recommend reaching out to the FlutterFlow support team for a more in-depth investigation into what's happening with your project. Additionally, we could test the same functionality in a different project to see if the issue persists consistently. Hopefully, this approach will be helpful for you. Try and let me know. Thanks

**Comment by 66leo** [comment]
Ok, we made sure it's not a bug, therefore now it goes to support for a case-based investigation. Got it.
Thank you Hari.

**Comment by hariprasadms** [comment]
You can come back and reopen the issue if support team confirms this is a bug in the feature. For now I am going to close the issue. Thanks
