### ISSUE TITLE
Problem with google maps widget

### ISSUE THREAD

**Issue by alexjordi** [FlutterFlow/flutterflow-issues#2408]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The error concerns the my_home page. However the default view is a list view. To see the error you must toggle from list view to map view, then back to list view and finally back to the map view. This is done by using the floating action button on the bottom right.

When I display the google maps widget within a conditional builder, it works as expected to start with. So when it is loaded for the first time I don't have any problems. However, if the condition changes, and then changes again to display the google maps widget again, this is where I encounter the error. Essentially, the action for "on marker tap" no longer complete.

I have noticed that if I visit a new page, and then return to the google map widget from a new page (not by changing the conditional builder) it works as expected again. But then as soon as the condition changes and is changed again the error reappears.

### Expected Behavior

Well it should just work no matter how I navigated to the map widget.

### Steps to Reproduce

1: Create a page with a conditional builder
2: place a google map widget under one of the conditions
3: populate it using an API call which returns a list of latLngs
4: place an action for a "on marker tap" trigger which finds the index of the marker that was tapped
5: in the action chain the page state variable should be changed to display a component over the map which contains data from the marker that was tapped on.
6: view your console to see the error

"""
dart_sdk.js:5402 Uncaught (in promise) Error: Bad state: Future already completed
    at Object.throw\_ \[as throw\] (dart_sdk.js:5402:11)
    at \_AsyncCompleter.new.complete (dart_sdk.js:35012:51)
    at flutter_flow_google_map.\_FlutterFlowGoogleMapState.new. (flutter_flow_google_map.dart:104:25)
    at Generator.next ()
    at runBody (dart_sdk.js:39921:34)
    at Object.\_async \[as async\] (dart_sdk.js:39957:7)
    at flutter_flow_google_map.dart:103:26
    at google_maps_flutter.\_GoogleMapState.new.onPlatformViewCreated (google_map.dart:427:19)
    at onPlatformViewCreated.next ()
    at dart_sdk.js:39902:33
    at \_RootZone.runUnary (dart_sdk.js:39737:59)
    at \_FutureListener.thenAwait.handleValue (dart_sdk.js:35127:29)
    at handleValueCallback (dart_sdk.js:35709:49)
    at \_Future.\_propagateToListeners (dart_sdk.js:35747:17)
    at \[\_completeWithValue\] (dart_sdk.js:35588:23)
    at async.\_AsyncCallbackEntry.new.callback (dart_sdk.js:35622:35)
    at Object.\_microtaskLoop (dart_sdk.js:40214:13)
    at \_startMicrotaskLoop (dart_sdk.js:40220:13)
    at dart_sdk.js:35968:9
"""

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xi8rlvI9OrttE+KXiafpVhiMvIjs4arhEiet+b0g1GKnkP5k2e/TET3ZaTby8dAl2JVCZhn0y+KHGv87lV8coAxeVeYNeys5UTjrgRmatMoSYPaqSSXBtO+xWfnKi16WCmA9QFOlaZV4M112yLuSUQibaQrrxPDAZHPyHNtnNkWvhGTLjEThVwmNecCfn

### Context

I want the user to click on a marker and have a bottom sheet display with information from that marker.

### Visual documentation

[https://drive.google.com/drive/folders/1cLBoU8qCtP_z1daW2mVYk_A-l8K0QaEx?usp=sharing](https://drive.google.com/drive/folders/1cLBoU8qCtP_z1daW2mVYk_A-l8K0QaEx?usp=sharing)

That video shows the error occuring.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: Windows 11 Pro
```

**Comment by hariprasadms** [comment]
Hi @alexjordi - Thanks for bringing up the issue. Based on the description provided, it seems like the issue is related to state management. You should utilize either app states or page states to ensure widgets update correctly based on conditions. I've reviewed the project you provided, but I couldn't locate the specific page where the issue occurred. Could you please update the issue with these details? This will help us investigate the issue more effectively. Thanks for your cooperation.

**Comment by alexjordi** [comment]
Hi Hari 

Thanks for getting in touch. I've updated the issue. The error is related to the my_home page but exclusively the map view. And indeed, I have been using page states and rebuilding the page when changing them as needed.

**Comment by bozzoleandro** [comment]
Hi @alexjordi, Does the explanation above help you to resolve your issue or are you still having problem with that? Please let us know so we can help you.

**Comment by alexjordi** [comment]
Hi

That suggestion did not work. Eventually I found a workaround.

Instead of using an if else block I used a stack where each item in the
stack had a conditional visibility. The map is always visible (so it only
builds once) whereas the other items in the stack are shown over it. This
works well so my problem is solved.

Thanks
Alex

**Comment by azizirac** [comment]
@alexjordi @bozzoleandro @hariprasadms 

Hi, I just encountered the same issue. I have a page where I want to show the results of a query. 
- The query is made when the page loads and the result saved in Page State. 
- The page has a Conditional Builder which either shows Google maps or a list based on a boolean State variable

These are the scenarios:
- the page loads in List. I switch to Maps - WORKS 
- the page loads in Maps, I switch to list, and then back to Maps - DOES NOT WORK when I click.

This are the logs I see when the issue happens (not sure it helps):

```
E/flutter ( 8947): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.dev/google_maps_android_5)
E/flutter ( 8947): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 8947): <asynchronous suspension>
E/flutter ( 8947): #1      _FlutterFlowGoogleMapState.build.<anonymous closure>.<anonymous closure> (package:runthevu/flutter_flow/flutter_flow_google_map.dart:215:21)
E/flutter ( 8947): <asynchronous suspension>
E/flutter ( 8947): 
```

**Comment by alexjordi** [comment]
Hi Rachid

Instead of using a conditional builder, try using a stack with conditional
visibility.

That worked for me.

Alex
