### ISSUE TITLE
Unexpected null value. (paywall with revenueCat; testing with Flutter 3.19.1, the same issue occurred again)

### ISSUE THREAD

**Issue by xiaoyaoyun** [FlutterFlow/flutterflow-issues#2410]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have both the RevenueCat and Google Play Console subscriptions set up correctly, following the step-by-step instructions in the documentation manual. The paywall uses the RevenueCat Price String variable, but an unexpected error occurred (Unexpected null value).
<img width="391" alt="Screenshot 2024-03-01 at 00 11 42" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8433905/64361f28-acdc-49f4-a875-6e64d253d2d7">

### Expected Behavior

the price string should be presented in the paywall, but it doesn't; error occurred

### Steps to Reproduce

I don't know, maybe you guys can review my flutterflow project.
<img width="640" alt="Screenshot 2024-03-01 at 00 20 39" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8433905/13503fee-3a1d-4fd9-b6db-c2fc030634e5">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWsct/cxQcB4j4E4oiduClXxJWZMCzaHxYGVa0pDgy/+D3ktr1V+0EaCmYfIBizKVUERPPbGCtb5StDKu8ZUZfEfhYGB26yLSZhRRCGPFfLS0t2HGQJNivVT6Cf9qOYwx5e6fDbOY=

### Context

I have tried various methods, including watching videos and reading documentation tutorials, but still haven't solved it. Could you please take a look at this issue? 
many thanks!!!

### Visual documentation

<img width="640" alt="Screenshot 2024-03-01 at 00 20 39" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8433905/7fbcc72d-8c45-41ea-be89-054ab89fd44d">

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: both web and android devices
- Browser name and version: Chrome 121.0.6167.139
- Operating system and version affected: macOS
```

**Comment by xiaoyaoyun** [comment]
I have set up everything that needs to be set up, including RevenueCat and Google Play Console. I have also logged into the app on my phone using the test user list (via the download link from Google Play Console), but there is still an issue.

**Comment by xiaoyaoyun** [comment]
Could someone please help me take a look at this issue? I would greatly appreciate it! I have been stuck on this problem for many days now, and I have tried setting it up multiple times without success.

**Comment by xiaoyaoyun** [comment]
my android device it shows a grey screen

**Comment by xiaoyaoyun** [comment]
> Also experiencing the same issue.

I have tried many times and it still doesn't work. I guess it might be that the dependence versions called by FlutterFlow are not correct.

**Comment by xiaoyaoyun** [comment]
When I was testing with Flutter 3.19.1, the same issue occurred again. Could someone please help me take a look at this problem? Thank you so much!

**Comment by paulperez-dev** [comment]
I'm going to close this issue since we have not heard back

**Comment by xiaoyaoyun** [comment]
The current issue is that when I log in to Google Play with account 1 to
download this app, the paywall doesn't show a gray screen. However, when I
log in to Google Play with diff account 2 to download the same app, the
paywall does show a gray screen. By the way, I was using the same account
to log in to this app, what could be the reason for this?

Paul Pérez ***@***.***> 于2024年4月22日周一 02:59写道：
