### ISSUE TITLE
Walkthroughs and SliverAppBar

### ISSUE THREAD

**Issue by WellDunDun** [FlutterFlow/flutterflow-issues#2411]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c6418137-d619-4f13-bc2a-7a3bc487558c/f4f690bb-79e3-4829-a8d9-f8f6471ab253?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNjQxODEzNy1kNjE5LTRmMTMtYmMyYS03YTNiYzQ4NzU1OGMvZjRmNjkwYmItNzllMy00ODI5LWE4ZDktZjhmNjQ3MWFiMjUzIiwiaWF0IjoxNzA5Mjk4NTQyLCJleHAiOjMzMjc5ODU4NTQyfQ.MqP4lO_3P7Lk2krEP1Lk6o0JM5xTzw4eD6PweIG8dzY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a3eaaea2-27e4-4d4d-8938-37c5e9e56d8f/b2df9028-acda-4f3a-a335-0214d6ac7bb4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hM2VhYWVhMi0yN2U0LTRkNGQtODkzOC0zN2M1ZTllNTZkOGYvYjJkZjkwMjgtYWNkYS00ZjNhLWEzMzUtMDIxNGQ2YWM3YmI0IiwiaWF0IjoxNzA5Mjk4NTQyLCJleHAiOjMzMjc5ODU4NTQyfQ.kU4QcOTaUsiEpMZxAC1l3WLbWqGjcvVHQsVq_tsxuaI)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dffc72c5-3d2e-44bd-8607-952ae97f14b5/d6ee89d8-8e6b-4f40-84a3-168246f967b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZmZjNzJjNS0zZDJlLTQ0YmQtODYwNy05NTJhZTk3ZjE0YjUvZDZlZTg5ZDgtOGU2Yi00ZjQwLTg0YTMtMTY4MjQ2Zjk2N2IyIiwiaWF0IjoxNzA5Mjk4NTQyLCJleHAiOjMzMjc5ODU4NTQyfQ.4mjOkoELHAlSC8KHFWV_6GtaND1Y9cfIMzmF8aO_kuI)

It crashes and throws different errors that were insanely hard to track down. 5+ hours spent on this

### Expected Behavior

It works and doesn't crash OR it should give an error in the editor that this will cause a breaking change so we undid it for you

### Steps to Reproduce

1. Enable SliverAppBar.
2. Create component for walkthrough.
3. Create walkthrough.
4. Add step and select any widget in your SliverAppBar as the target.
5. Add a button the navigates to the page or create another page to navigate to and use the back navigation
6. Try to reload or navigate back to the page from another page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xj+fl049Jtbxd+KricMdVqCo5JlA5arxMj+xEdxQ1GOvmO5kUd+PUT3JdOLyhSmw/PFu0nXE1+ezXv9nLFeQHAyyZf4s7/7txEDrgRnGgeK6PPc2we3Z7N/1QHkuV0J2RgRUmLvJedGMj3EyEfuqRFzbrJuPKOlUzROaHENz5+XC8Ahm6Xn0Jg1ZSfCvr

### Context

It was a ton of work to debug this issue and delayed an app update for my users. I would love to be able to use the new walkthrough feature to onboard users

### Visual documentation

[https://www.loom.com/share/c4c11afdba4e44ad80e4a758a13d0a2b?sid=6c4c326f-b3aa-49fc-982c-0edcc235c6e9](https://www.loom.com/share/c4c11afdba4e44ad80e4a758a13d0a2b?sid=6c4c326f-b3aa-49fc-982c-0edcc235c6e9)

### Additional Info

I tested this on iOS and Android both on simulators and actual devices

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Chrome Version 122.0.6261.71 but it happens everywhere
- Operating system and version affected: N/A
```

**Comment by sbis04** [comment]
This should be fixed in the latest version of FlutterFlow!

**Comment by WellDunDun** [comment]
> This should be fixed in the latest version of FlutterFlow!

Thank you so much Souvik! Big fan of your work and hope to see you on the livestream one day!
