### ISSUE TITLE
Setting container width to % using variable defaults to pixels not %

### ISSUE THREAD

**Issue by kemperflow** [FlutterFlow/flutterflow-issues#2412]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I have the container width set to 20% the project works as expected. If I set a page state variable called colWidth and set it equal to 20 (tried double or integer) and then set that container width via the colWidth variable, it defaults to displaying in pixels vs %

![Screenshot 2024-02-29 125831](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/12ee0200-6f5c-4c08-905c-76b2f7b24f08/a858c53f-f2f9-4b08-a979-137a4a88ef37?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMmVlMDIwMC02ZjVjLTRjMDgtOTA1Yy03NmIyZjdiMjRmMDgvYTg1OGM1M2YtZjJmOS00YjA4LWE5NzktMTM3YTRhODhlZjM3IiwiaWF0IjoxNzA5NTUwMTgzLCJleHAiOjMzMjgwMTEwMTgzfQ.BOyLZ4QSrM3zqS9bQcKt9WjUu_95q7GxdaRaQQK3Ugo)

![Screenshot 2024-02-29 124813](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ccd5ba68-8740-45bd-80a7-7c88c59c6456/0aaba868-d9ba-49e0-b73f-b8473a6235d0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jY2Q1YmE2OC04NzQwLTQ1YmQtODBhNy03Yzg4YzU5YzY0NTYvMGFhYmE4NjgtZDliYS00OWUwLWI3M2YtYjg0NzNhNjIzNWQwIiwiaWF0IjoxNzA5NTUwMTgzLCJleHAiOjMzMjgwMTEwMTgzfQ.aXs1cQkzP94Hq7HUR6IMnd8f0b-0lVqtu2c5iFxvkXM)

![Screenshot 2024-02-29 124729](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4fec9417-09d2-4b74-81d9-fe77230586da/d262a86b-38ab-4ec6-951f-2cf948e10db3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZmVjOTQxNy0wOWQyLTRiNzQtODFkOS1mZTc3MjMwNTg2ZGEvZDI2MmE4NmItMzhhYi00ZWM2LTk1MWYtMmNmOTQ4ZTEwZGIzIiwiaWF0IjoxNzA5NTUwMTgzLCJleHAiOjMzMjgwMTEwMTgzfQ.lbrkno4s4clmiKOufoH4fX7NkNRefFXMJ6wEs-Ro6iE)

### Expected Behavior

If I have selected % as the width type of a container and I insert a variable, I expect it to use the value as a % not as a pixel value.

### Steps to Reproduce

1. Create 5 containers in a horizontal row and set each width to 20%
   Expected output is 5 equally spaced containers across the entire width, which works.
2. Create a pagestate variable called 'colWidth' (I tried using a double or an integer, neither solved this issue) set the variable to 20
3. Replace the 20 in the container width the new colWidth variable. It shows the % to the left of the variable after inserted.
4. Re-run the project and you should see the containers are now set to 20 pixels, not 20%

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olPLqw89grsNa1s7yacFvryQQNW41RoE3j8pBazwbfe+uB4kqevfOTERvZ7C+T1Y2MWKJ+GoW0aH6kuzhJPYEAyueQa4+zJFcVw2VeHKmaLqnFJWvOEFREd9XIEfE17SnhBB5Ns1eS3gk2WWEfPPIcArANqb0IlQ4Dq/LZO4=

### Context

I'm writing a game which contains five columns. If there are two players, I only show three columns, if there are four players, I show all five columns. In the event there are two players, I resize the container holding the columns to 40% width (40% width for player 1, 20% for score in the middle, 40% for player 2 on the right). If there are four, I size each container/column to 20%.

I'm sure there are other ways to accomplish this, but setting % width via the method described here should be supported regardless.

### Visual documentation

![Screenshot 2024-02-29 125831](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4511edc0-a598-4b7a-af1e-be1856704bfd/77f293ec-c879-44a2-a080-cb7fa10bf6b5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NTExZWRjMC1hNTk4LTRiN2EtYWYxZS1iZTE4NTY3MDRiZmQvNzdmMjkzZWMtYzg3OS00NGEyLWEwODAtY2I3ZmExMGJmNmI1IiwiaWF0IjoxNzA5NTUwMTgzLCJleHAiOjMzMjgwMTEwMTgzfQ.oJFLOizH0nqfhWk2ygYecO777OppeHJHZ40N3Z9RhRU)

In the first row, you'll see four names that should be spaced 20% each across using a variable to set the 20%
In the second row, you'll see the columns that are forced to 20% width without a variable.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web/Android
- Browser name and version: Visual Code w/ Android Emulator
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @kemperflow - Thank you for bringing up the issue. I've been able to replicate the behavior you described. This behavior aligns with the current design. However, I can flag this bug for technical review to see if it could be considered for feature enhancements. Your contributions are appreciated.

**Comment by takashiff** [comment]
Hi @kemperflow, thank you for the bug report. As @hariprasadms has stated, this looks like a feature enhancement. I will pass this forward internally so that this feature may be implemented in the future. Thanks
