### ISSUE TITLE
Figma import not working

### ISSUE THREAD

**Issue by Casraw** [FlutterFlow/flutterflow-issues#2414]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tried to import a figma design but it wont work I got only a GET[ https://api.figma.com/v1/files/y8zbbieG4hGCClYrFyqdZy/nodes?ids](https://api.figma.com/v1/files/y8zbbieG4hGCClYrFyqdZy/nodes?ids=)= 400 (Bad Request)

### Expected Behavior

The import is started and worked

### Steps to Reproduce

1. Click on Figma theme import
2. Set the url
3. set the token

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

XXX

### Context

I cant import my figma theme

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9a20826e-74d4-4b09-b0eb-8ab75d948f65/c70d329f-3369-4eab-9bc9-700349486228?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YTIwODI2ZS03NGQ0LTRiMDktYjBlYi04YWI3NWQ5NDhmNjUvYzcwZDMyOWYtMzM2OS00ZWFiLTliYzktNzAwMzQ5NDg2MjI4IiwiaWF0IjoxNzA5NTcyNzg4LCJleHAiOjMzMjgwMTMyNzg4fQ.6spIslGkiDGQg_Z_Ktp4msHM9oE_z52k6jUD2a-nPjI "=1739x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Version 122.0.6261.71 (Offizieller Build) (64-Bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
HI @Casraw - I can see the same error in the developer console.

**Comment by takashiff** [comment]
Hi @Casraw, thank you for the bug report. Figma import are currently generally working, and I'm unable to reproduce the issue. Could you provide the bug report code so that we can look into this matter further? Thanks

**Comment by Casraw** [comment]
@takashiff sure: ITESz/Hqx89gobgG7ZCJLcdAhQIgQ0QnU7gnlO1ucx40NbGsE4YhdszeX0NKTf25dFdIAFmZ/UwEptbKhd7LO+0VEz+cR4Q+0JVAUTrNTXyiaarSO5C0S3BCO91MCk+P552vpBMmOvhZSl5n2F6pNa3qNleeY8aSfxBlZ7vfcPo=

But this is only a testing instance. It didn't work on any of my Projects... First, it seems it is working but there are 0 imports. And the error in the console.

**Comment by elektron314** [comment]
I have the same issue
MacOS
Any browser or app
Trying to feed it with figma URL and token:
"Error loading your Figma project. Please check that the URL and access tokens are correct."
Different figma files and tokens were generated - same effect.
Several days ago everything was fine.

**Comment by webmuppet** [comment]
> I have the same issue MacOS Any browser or app Trying to feed it with figma URL and token: "Error loading your Figma project. Please check that the URL and access tokens are correct." Different figma files and tokens were generated - same effect. Several days ago everything was fine.

Seeing exactly the same issue. First time I tried to do this as a test it worked fine. A day later it is refusing to work from any combination of browsers or stand-alone apps.

![CleanShot 2024-05-20 at 17 44 47](https://github.com/FlutterFlow/flutterflow-issues/assets/1232300/c5a78e31-ee3f-4cb4-964a-72064084f2b9)

Doesn't seem to be passing the Figma file URL correctly.

**Comment by vbykintmp** [comment]
I'm having the same problem

**Comment by tostinni** [comment]
We're still having this issue.
When inspecting the network console, it's trying to make a call to `https://api.figma.com/v1/files/:` which led to a 404 error.
This seems to be the same error reported by https://github.com/FlutterFlow/flutterflow-issues/issues/2414#issuecomment-2119711614

@PoojaB26 was there a fix applied to correct this ?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/585338/f4e35d11-5cde-4173-8a11-88450e27142c)
