### ISSUE TITLE
iPhone issue- Screen not rendering for iPhones other than iPhone 14 Pro Max

### ISSUE THREAD

**Issue by CGann** [FlutterFlow/flutterflow-issues#2415]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm having an issue where one page in my app, the LoginPage, isn't rendering for any iPhone other than the 14 Pro Max in the FF editor . Other pages seem to render just fine. When I select any iPhone other than the 14 Pro Max in the FF editor, all I see is a blank screen.

All Samsung and other devices seem to work just fine.

I don't see any settings on the container that would cause this.

Any ideas what's going on here? This is important because a user just informed me that on their iPhone 15 Pro (IOS 17.2.1) they are only seeing a blank screen after the splash page.

### Expected Behavior

All screens should render properly

### Steps to Reproduce

not really sure. You may have to check my code. Not certain why this is affecting only one page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl/KB24lPn7wA15D+Le9ahjwvNlw1aIIZl8N9ewoaGLmqPaYPXfikSEpWZ9+kTHxcL2Gajj4xp8HIkdnIA+UqG06eQLZk+boJaQnJZHqlMs2OC6q8VnMkL9pJJVye06az3BR+WcV0Sk472mCYPPO+ZB3YGLrUClgzMP2YVb/J+m+rQ0SLb3kNh1JWeC/v

### Context

a user just informed me that on their iPhone 15 Pro (IOS 17.2.1) they are only seeing a blank screen after the splash page.

### Visual documentation

![2024-02-27 10_31_46-Window](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4a047a3f-aac5-49bc-a335-33921673635c/3d4c3015-dd80-4385-91b6-4a0009f30b30?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YTA0N2EzZi1hYWM1LTQ5YmMtYTMzNS0zMzkyMTY3MzYzNWMvM2Q0YzMwMTUtZGQ4MC00Mzg1LTkxYjYtNGEwMDA5ZjMwYjMwIiwiaWF0IjoxNzEyMDc3NDQ4LCJleHAiOjMzMjgyNjM3NDQ4fQ.uAXHq5VxFOAo7brCz31lLoFIMPWrom-j7yO4pez_QO4)

![2024-02-27 09_42_38-Window](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1fc748fd-bcfb-4226-954d-ad41028812e7/5eb593cb-7845-4a12-83fc-e1c534217a03?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZmM3NDhmZC1iY2ZiLTQyMjYtOTU0ZC1hZDQxMDI4ODEyZTcvNWViNTkzY2ItNzg0NS00YTEyLTgzZmMtZTFjNTM0MjE3YTAzIiwiaWF0IjoxNzEyMDc3NDQ4LCJleHAiOjMzMjgyNjM3NDQ4fQ.jf3gZ1Z2qiJbqN95jyxFyQNgyXLK2atQdHWz1_pmQ1E)

![2024-02-27 09_42_58-Window](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c032b0f9-bc4b-45a8-917a-19a481f5e5ba/b445c3d8-b300-419e-94bb-2687b183bd0b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMDMyYjBmOS1iYzRiLTQ1YTgtOTE3YS0xOWE0ODFmNWU1YmEvYjQ0NWMzZDgtYjMwMC00MTllLTk0YmItMjY4N2IxODNiZDBiIiwiaWF0IjoxNzEyMDc3NDQ4LCJleHAiOjMzMjgyNjM3NDQ4fQ.gTxRm5YOWNkUk7Mbe3Qn-00vsgrbpqpr52fS75Hi2BQ)

![2024-02-27 09_43_12-Window](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/932bcb3b-90d2-4cb1-b70d-b28eabd75c79/45ea19ea-bd85-402a-b012-77542007dcf5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MzJiY2IzYi05MGQyLTRjYjEtYjcwZC1iMjhlYWJkNzVjNzkvNDVlYTE5ZWEtYmQ4NS00MDJhLWIwMTItNzc1NDIwMDdkY2Y1IiwiaWF0IjoxNzEyMDc3NDQ4LCJleHAiOjMzMjgyNjM3NDQ4fQ.m8pGcJrhjzAaz-H0xzP01Ruosx4K9HF5zU_0ibzV2pE)

![2024-02-27 09_43_27-Window](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9f80e5fe-dad5-4ed4-b970-cc3841aab07a/9a195c6b-9ebb-41b2-abd4-eabf8e6ad718?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZjgwZTVmZS1kYWQ1LTRlZDQtYjk3MC1jYzM4NDFhYWIwN2EvOWExOTVjNmItOWViYi00MWIyLWFiZDQtZWFiZjhlNmFkNzE4IiwiaWF0IjoxNzEyMDc3NDQ4LCJleHAiOjMzMjgyNjM3NDQ4fQ.2CkNsS9cI3hDcZKnFnMBwVmmKEB0rT1M9hME-q-D3ss)

### Additional Info

Link to my project and the affected page:
[https://app.flutterflow.io/project/actor-trax-redesign-6kqg8s?tab=widgetTree&page=LoginPage](https://app.flutterflow.io/project/actor-trax-redesign-6kqg8s?tab=widgetTree&page=LoginPage)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web, desktop, PC
- Browser name and version: Chrome Version 121.0.6167.185 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro 22H2 OS build 19045.4046
```

**Comment by hariprasadms** [comment]
Hi @CGann - This issue is related to breakpoints. It seems that you have altered the breakpoints in the design section. Please revert them back to their default settings, and everything should work fine. I've tested your project after changing the breakpoints, and it functions properly.

Default breaking points values 

<img width="1159" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/c1eaf648-aaab-4594-9f26-a76782ba362c">
