### ISSUE TITLE
Parameter Passing and NavBar Visibility Issues with Different Transition Modes

### ISSUE THREAD

**Issue by javierlobra** [FlutterFlow/flutterflow-issues#2417]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Parameter Passing Issue with Instant Transition: When using the "Instant" navigation transition mode to pass a parameter from one page to another, the parameter fails to be passed. Despite setting up a parameter to be passed to the second page with a numerical value, executing this action results in the second page's title displayingthe default value instead of the parameter value.
2. NavBar Disappearance with Default Transition: After changing the navigation transition from "Instant" to "Default" for the same action, the parameter is correctly passed, and its value is displayed on the second page's title. However, the NavBar on the second page disappears, which was not the intended behavior.

### Expected Behavior

1. The parameter should successfully pass to the second page, and its value should be displayed in the title, regardless of the navigation transition mode ("Instant" or "Default").
2. The NavBar should remain visible on the second page when navigating with any transition mode, ensuring consistent navigation elements across the application.

### Steps to Reproduce

1. Create a new project in FlutterFlow and add a second blank page.
2. On the second page, create a page parameter (Integer, not required).
3. Enable the NavBar on both pages.
4. On the first page, add an action to the page title: on tap, navigate to the second page with "Instant" transition, and select the newly created parameter to pass it, assigning it any numerical value.
5. Modify the title of the second page to display the parameter value, with "none" as the default value.
6. Test the functionality to observe the failure in parameter passing—the title of the second page is "none".
7. Change the navigation transition type of the created action on the first page from "Instant" to "Default".
8. Test the functionality again to observe that while parameter passing now works (the title of the second page displays the parameter's numerical value), the NavBar on the second page disappears.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cls/l6otPm9tH1s7yKe9VliAXHEw8RYEVl+sbTUo3HZPQCJkQO8nQPxRWOO24dwlqJ1q2p141w/DRv9mSC/cnGyuefr5myqgNSg/KfGG5V62TF7WaQUckL+9VIGnD5qSFsApNHM1iSnwCwV+UevKySh3AGYzVDkQwSq/LZO4=

### Context

These issues hinder the effective passing of dynamic data between pages using different transition modes.

### Visual documentation

I have created this project for you:
[https://app.flutterflow.io/project/bug-report-final-8nwiv5?tab=widgetTree&page=HomePage](https://app.flutterflow.io/project/bug-report-final-8nwiv5?tab=widgetTree&page=HomePage)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: web
- Browser name and version: Chrome 121.0.6167.184
- Operating system and version affected: MacOS Ventura 13.6
```

**Comment by hariprasadms** [comment]
Hi @javierlobra - Thank you for submitting the issue. I've tested the steps and observed the same behavior, but it seems inconsistent. Most of the time (7 out of 10), it worked fine, but there were 3 instances where it did not work. Nevertheless, I've marked it as a bug so that the development team can review the details and implement any necessary fixes.

**Comment by javierlobra** [comment]
Hi @hariprasadms,
Thanks for addressing this. It's never worked for me, and it seems I'm not alone. Many reported the same issue recently: https://community.flutterflow.io/widgets-and-design/post/navbar-disappears-when-navigating-to-a-page-with-parameters-ZA44LsxrJJYuQoW
Best,

**Comment by leighajarett** [comment]
Thanks for flagging, it's in our backlog and we're hoping to have a fix out soon!

**Comment by fafa16** [comment]
Hello, any news??

**Comment by leighajarett** [comment]
This issue should be resolved, are you still experiencing it?
