### ISSUE TITLE
Adding "Too Many" Languages causes the UI To slow and Translations dont complete

### ISSUE THREAD

**Issue by RealDanCarroll** [FlutterFlow/flutterflow-issues#2418]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever I add more than lets say 10 supported languages, I get an error saying translations cant be completed. This seems to be effected by the attempt to translate the Preset In-App messages

### Expected Behavior

I expect to be able to add as many languages as I want without having performance issues.

### Steps to Reproduce

Add another language, click Translate All or Translate the pages manually. Current languages chosen English, Spanish, Chinese (Both), Tagalog, Vietnamese, Arabic, French, Korean, Russian, German, Hebrew. (Hebrew doesn't translate Preset In-App Messages, additional languages have similar issue)

Also, I'm not taking the time to make a blank project to test this for you. That's a silly request. How about since you want me to do your developers job for you by doing additional troubleshooting, I'll check to see if this breaks in a blank project if you refund a month's FlutterFlow fee in exchange for doing your troubleshooting.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not Applicable

### Context

It has prevented me from launching a full featured application. I want an application accessible globally and this isnt possible with language limitations im experiencing.

### Visual documentation

![11111111111111111111111](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dba7b660-c7e2-4f6e-aefc-1fb08c74e041/c5ef2e51-fa31-43e1-9bba-f41798dd0eed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYmE3YjY2MC1jN2UyLTRmNmUtYWVmYy0xZmIwOGM3NGUwNDEvYzVlZjJlNTEtZmEzMS00M2UxLTliYmEtZjQxNzk4ZGQwZWVkIiwiaWF0IjoxNzA5Njc4MzUyLCJleHAiOjMzMjgwMjM4MzUyfQ.nISgj5swtbWx0ppk90YjYxPS-SQ7rqka-lzAmDC9zc8)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1 - Flutter 3.13.7
- Platform: Web GUI
- Browser name and version: Chrome, Newest
- Operating system and version affected: ALL
```

**Comment by RealDanCarroll** [comment]
If you need project access, Ill be happy to give you a URL via DM.

**Comment by takashiff** [comment]
Hi @RealDanCarroll, thank you for your bug report. Could you provide the bug report code (any widget in your project will suffice) so that we can triage this further? The bug report code will provide us access to take a look at your project without the need for a URL. Thanks

**Comment by RealDanCarroll** [comment]
ITFflfLqw5NgochE1a6IKMdammA4H20cTIMziNZ+exUbfaL1BqQEPMjOTE1oQsu7aVNcA2Gl/D8z093IkeHtCPUrCEyWRbZB/6tiVAn0e2ijRK3WPriCPnZDJ+xPf0yz3J+o2BRdB/VvdEIH20OqF9zKHwDDBOu/Zwh9f6PHaOI=

I grabbed this from the Auth page, note that the error isn't specific to this page.

**Comment by takashiff** [comment]
Hi @RealDanCarroll, what type of plan are you currently on? I believe Google Translate is restricted to Pro and above

**Comment by RealDanCarroll** [comment]
I have FF Team plan. The feature is available to me as I am complaining about it partially working not that the feature is unavailable.

All you have to do to recreate the problem is add 1 language option in excess of what I had in the project and click "Translate All". I have added Italian to the project now and clicked the button, the problem is still there. If you drill down farther, you will see the issue happens when it is attempting to translate Preset In-App Messages.

**Comment by RealDanCarroll** [comment]
@takashiff Why is that only a problem when I add a new language but if I take away Italian form the list, there is no error? Perhaps I am wrong about the source..... I'm not the expert here.

**Comment by RealDanCarroll** [comment]
@takashiff I just did some additional troubleshooting. I took away italian and clicked translate on those messages and still got the error... But if I click translate all, no error. Add Italian, click translate all, get an error.

Please troubleshoot this issue adequately before dismissing the issue.

**Comment by takashiff** [comment]
Hi @RealDanCarroll, upon further testing, it looks like there are two issues leading to the above behavior. The first issue is the one I had described previously, in which the 'Preset In-App Messages' are blank, leading to nothing being translated. The second issue ('Translate All' failing when adding another language) is due to Google Translate API's rate limit being exceeded due to too many translations in a single request. In order to continue translating your app without issue, I would advise following the below steps.
1. Add a message for the primary language for each of the Preset In-App Messages
2. Translate section-by-section (i.e. translate each component/page/messages/permissions separately) to avoid exceeding the rate limit.

Thanks

**Comment by RealDanCarroll** [comment]
@takashiff I'm glad you figured out the issue. Seems like this is still an issue to be fixed by FlutterFlow. They should queue the requests so the rate limit isn't exceeded.

**Comment by takashiff** [comment]
@RealDanCarroll I agree, that could solve similar issues in the future. I will go ahead and mark this as closed now since the issue is (tentatively) resolved.

**Comment by RealDanCarroll** [comment]
@takashiff Respectfully, I would like to request that you reopen this issue until the problem is solved. 

In addition to this issue, I am unable to get a decent experience out of the app when I add ALL of the languages. Once I add all 150, the app slows to a crawl and I am unable to make edits to the app like normal. Each action, including opening the project, takes a minute or more.

Perhaps @hariprasadms can look into this directly?

**Comment by RealDanCarroll** [comment]
@takashiff If this is outside intended use, what is the intended use? 

You want to enable users to make their app PARTIALLY globally accessible?

Like "Select any language, as long as you don't try to include everyone cause NO ONE could possibly want to be fully inclusive?"

**Comment by takashiff** [comment]
Hi @RealDanCarroll,

Thank you for your prompt response and for seeking clarification on the intended use of the internationalization feature. I understand that my previous message might have caused some confusion, and I apologize for any miscommunication I may have caused.

To clarify, our goal with the internationalization feature is indeed to enable users to create applications that are fully accessible and inclusive on a global scale. While we aim to provide a robust framework for internationalization, unfortunately, full global accessibility without limitations is not currently supported on our platform. Our current feature set is designed to accommodate a wide range of internationalization needs, but we do recognize that there may be limitations in certain scenarios.

I apologize for any inconvenience this may cause, and thank you for your patience. Thank you for your understanding and continued support.
