### ISSUE TITLE
FlutterFlowStaticMap makes page loading slow

### ISSUE THREAD

**Issue by tmpsantos** [FlutterFlow/flutterflow-issues#2419]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding a FlutterFlowStaticMap that loads a Mapbox map, the following code gets added to the page widget builder:

```
    if (currentUserLocationValue == null) {    
      return Container(                            
        color: FlutterFlowTheme.of(context).primaryBackground,    
        child: Center(    
          child: SizedBox(    
            width: 50.0,                                                                    
            height: 50.0,                                                                   
            child: CircularProgressIndicator(                                               
              valueColor: AlwaysStoppedAnimation<Color>(                                    
                Colors.white,                                                               
              ), // AlwaysStoppedAnimation                                                                                                        
            ), // CircularProgressIndicator                                                                                                       
          ), // SizedBox                                                                                                                          
        ), // Center                                                                                                                              
      ); // Container                                                                                                                             
    } 
```

This has two negative side effects:

* It adds a `CircularProgressIndicator` that will only go away when the app can get a lock on the user location (which might take quite a while when indoors).
* Will trigger onPageLoad events, which might be technically correct because the builder has returned, it is perhaps semantically incorrect, because we are seeing an intermediate state before the page gets actually loaded.

### Expected Behavior

The FlutterFlowStaticMap still won't load the map synchronously because after getting the user location, it will still make an request to Mapbox APIs.

A good solution could be remove this code and chain both async calls: get location and get the map. Visually looks the same, except that we don't see the `CircularProgressIndicator`.

### Steps to Reproduce

Adding a `FlutterFlowStaticMap` to any page should do it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohs/lvIpNobhe+KqJccdFmSQ7Qlh7bJJJlcpBaywdCJyuP4kIQfTORERDUuLhTHxAfVqjmWoW0tGOkvD1O/oEOTqAfNxyzYdtWhXiYEanVKqRFJWgZn9SJ/NMI2qc3Ka3vxNNAMt0SHhi1DmUfOvLdBTsQ6boPEQgDa/LZO4=

### Context

I wanted to make sure my page was loaded fast so my hero animations could be seem, but the `CircularProgressIndicator` was blocking the page loading.

### Visual documentation

N/A.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: tested only Android
- Browser name and version: n/a
- Operating system and version affected: any
```

**Comment by leighajarett** [comment]
Thank you so much for this feedback, we'll consider this for future updates to our mapping capabilities!
