### ISSUE TITLE
Custom Function Removes Necessary Import Upon Saving?

### ISSUE THREAD

**Issue by ShubhamHande99** [FlutterFlow/flutterflow-issues#2420]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to create a custom function that returns data based on the app mode, whether it's in release or debug mode, using "kReleaseMode" from "package:flutter/foundation.dart". However, when I try to save the function, it removes the "package:flutter/foundation.dart" import, which prevents me from saving or creating the function.

### Expected Behavior

The expected behavior is that the custom function should not remove the necessary import required for its functionality upon saving.

### Steps to Reproduce

1. Open the custom code section.
2. Create a custom function and provide a function name.
3. Now create a function that returns string data based on the app mode (e.g., release mode).
4. Use "kReleaseMode" to check the app mode and import "package:flutter/foundation.dart".
5. Save the function and observe that upon saving, the custom function editor removes the import "package:flutter/foundation.dart".
6. Unable to create and save the custom function.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grtsC0ZfcLMFAhQIgQ0QnU7gnlO1ucx4dC4OuBLAMZ8jCT0NKTcviS2xYEVaLoF0Kws7ej/DDOPoBE0mdGYhk0JVPERaUcH6jb7mYEcyKWnNCDd9nBX6dy5iNohQlBOx2WkIG32WDNq3qNleeY8aSfxBlZ7vfcPo=

### Context

1. The issue is preventing me from creating a reusable custom function.
2. What I'm trying to accomplish is creating and saving a custom function.

### Visual documentation

Video attachment -
[https://github.com/FlutterFlow/flutterflow-issues/assets/45396085/8a728f62-fc22-497e-a1a7-ac0d1e7cb1d8](https://github.com/FlutterFlow/flutterflow-issues/assets/45396085/8a728f62-fc22-497e-a1a7-ac0d1e7cb1d8)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 and Flutter 3.13.7
- Platform:
- Browser name and version: Chrome, Safari
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @ShubhamHande99 - Custom functions cannot include imports that are not predefined, and attempting to save such imports by hitting the save button will not work due to current design constraints. However, this restriction does not apply to custom widgets; you can experiment with importing external 'imports' there. While your expectation to allow external imports in custom functions seems reasonable, there may be technical reasons behind this limitation. We can mark this issue for technical review and collectively decide its resolution. Thank you for your valuable contributions.

**Comment by takashiff** [comment]
Hi @ShubhamHande99, as @hariprasadms has stated, it is a current limitation of FlutterFlow that we do not allow imports in custom functions. If possible, I would suggest using a custom widget/action as mentioned earlier to achieve your desired goal. Thanks
