### ISSUE TITLE
Deleting a Single Character Clears the Entire Field

### ISSUE THREAD

**Issue by LordCortes** [FlutterFlow/flutterflow-issues#2423]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Encountering an issue with a masked number field in my system. When attempting to edit the field, any effort to delete a single character results in the entire field being cleared. 

### Expected Behavior

that only deletes one character and not the entire field

### Steps to Reproduce

https://github.com/FlutterFlow/flutterflow-issues/assets/132726784/7d1a40bf-a58b-413b-8d62-9fb5b0343ad0

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/132726784/f0f940f5-b361-4dc0-843a-6720e74a5380)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkPLq28l1ofVY1b6Jd/pViicsJnkcTLkvjuphcz8YGIztBJh/ZsjRclZWOO3hS2lhHE6ioGEJ+PDGi+PqGMIoOS2uGIR4+Llydgvve3q8Rc2vDoe/dnRBGfFnIWal0Z6rgQlCItJhc1YFw1yPfN+9Tg3cCZ+/Zwh9f6PHaOI=

### Context

I have a number field with a mask. When editing the field, if I try to delete just one character, it erases the entire field. Does anyone know why this is happening? And how can I prevent it?

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/132726784/a449773f-1205-42d9-b199-6d771ff80992)

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform:Web
- Browser name and version:chrome
- Operating system and version affected: windows and movile
```

**Comment by rzambroni** [comment]
Hi, @LordCortes, thanks for the report.. unfortunately, i'm not being able to reproduce this issue on a blank project. 

Are you still having this problem? If so, perhaps you could try to reproduce this on a blank project to discard any project specific issues and share that code with us. 

Thanks!
