### ISSUE TITLE
SQLite error when trying to pass parameters between pages

### ISSUE THREAD

**Issue by marco2299** [FlutterFlow/flutterflow-issues#2425]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

SQLite error when trying to pass parameters between pages. What happens is the following: When I try to pass the "cursoSelected" parameter from the Course page to the Coursedetails page, the returned value of this variable returns as null, making it impossible for me to access the data passed by reference.

### Expected Behavior

I needed the reference to be passed as an actual document value and not a null value.

### Steps to Reproduce

1. create two pages
2. Create a list view in page 1

3)attach a sqlite query to the list view in page 1

1. add a button to list view

5)On tap of button navigate to page 2 passing the sqlite row as page parameter for page 2

1. define the page parameter as sqlite row in page 2 to accept the incoming data
2. create a text field on page 2 to display the incoming data and set the text property to one of the columns of the incoming row

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzvHf8ZdgobVE7r6JLexGmj84JWEcTYMvjuphcx43IojrPIYuY+PCU0NKT7GlTQhqf02bhTsx0c70veDiFcJeIUyZfZxI0JVPWA7NVkCgVJinEqWSRnwnM5hQIH6O1qSRkxZAXcRZZXdm216LNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to add the same name as the course clicked on the previous page. In other words, pass the name of the course list as a reference to the Course details page.

### Visual documentation

![image (2)](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f144c5dc-37ca-41d9-b8a6-0edc10d480cb/9012429d-bc16-4b59-8439-5a4ead41d465?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMTQ0YzVkYy0zN2NhLTQxZDktYjhhNi0wZWRjMTBkNDgwY2IvOTAxMjQyOWQtYmMxNi00YjU5LTg0MzktNWE0ZWFkNDFkNDY1IiwiaWF0IjoxNzA5Mzc0MjEzLCJleHAiOjMzMjc5OTM0MjEzfQ.yA7XksGnPSAMB_sfuELIpDoKUe_GX-rvow1xBlk_DtQ)

![image (1)](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c29c4a9c-ea89-415f-9507-491fb8a9a7ea/70736711-a29e-4950-94ab-54baadc7e1a7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMjljNGE5Yy1lYTg5LTQxNWYtOTUwNy00OTFmYjhhOWE3ZWEvNzA3MzY3MTEtYTI5ZS00OTUwLTk0YWItNTRiYWFkYzdlMWE3IiwiaWF0IjoxNzA5Mzc0MjEzLCJleHAiOjMzMjc5OTM0MjEzfQ.lgop-HyFX9yNX486N2zNA1DoOx6whQZ_3MPEK7XroTk)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/399f2efa-bfb0-4759-be84-53d35c1b8c7d/2eb0a024-8e1a-4bb2-948c-6e9b52b5951a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zOTlmMmVmYS1iZmIwLTQ3NTktYmU4NC01M2QzNWMxYjhjN2QvMmViMGEwMjQtOGUxYS00YmIyLTk0OGMtNmU5YjUyYjU5NTFhIiwiaWF0IjoxNzA5Mzc0MjEzLCJleHAiOjMzMjc5OTM0MjEzfQ.rdaBYy1o1T2G-0i3bNUvgNhWLkYKwbhtkZbhykhPBbE)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Mobile.
- Operating system and version affected: Windows 10
```

**Comment by ignalauret** [comment]
Hey @marco2299 thanks for your report. I followed your steps from a blank project and was able to pass a SQLite row through page parameters. Then I used a value from the Row to display on a Text on the second page, and everything worked as expected. <br>Are you still experiencing this issue? Have I missed something on my steps to reproduce it?

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
