### ISSUE TITLE
After page load of FF dashboard site after a few seconds the screen gets black

### ISSUE THREAD

**Issue by mvolution** [FlutterFlow/flutterflow-issues#2429]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After page load of FF dashboard site after a few seconds the screen gets black and nothing is seen / displayed

### Expected Behavior

The dashboard should be visible

### Steps to Reproduce

1. Open FF dashboard

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzcmA8Y1PxOVY0KX1bfkwqCYRJmI+TL07ttYbZxUjIuPtBJh/euD4SxdWZNOkYXlhHFKYimAC0NbKiOzPE+w4OQecUapywqVcbDzdTXq8Rc20DqqRPkBCO5lhfkih5rWFvQknVctqc1of12aqedivcz/aJ5+/Zwh9f6PHaOI=

### Context

I cannot work, if I cannot see my projects

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/132994374/e18cae8b-9714-483a-9175-8fa9d06ef256

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released February 24, 2024 Flutter version is 3.13.7
- Platform: MacOS Desktop: Web
- Browser name and version: Chrome Version 122.0.6261.94 (Offizieller Build) (x86_64)
- Operating system and version affected: MacOS Sonoma 14.3
```

**Comment by takashiff** [comment]
Hi @mvolution, thank you for the bug report. There's currently an issue with [Flutter shaders compiling on Chrome](https://github.com/flutter/flutter/issues/140504). The following steps may help to temporarily work around this issue:

- Go To chrome://flags/
- Search for "Out-of-process 2D canvas rasterization" and enable the flag
- Relaunch the chrome browser

Let me know if this works. Thanks

**Comment by takashiff** [comment]
Hi @mvolution, thank you for the bug report. There's currently an issue with Flutter shaders compiling on Chrome. The following steps may help to temporarily work around this issue:

Go To chrome://flags/
Search for "Out-of-process 2D canvas rasterization" and enable the flag
Relaunch the chrome browser
Let me know if this works. Thanks

Note: To keep the main Flutter issues thread less cluttered, please refer to [this link](https://github.com/FlutterFlow/flutterflow-issues/issues/2450) on our FF issue tracker to find the link to the Flutter issue.

**Comment by takashiff** [comment]
Going to mark this issue as closed for now. Feel free to follow up in this thread if the issue persists.
