### ISSUE TITLE
Cannot set value on Local State

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#243]
As you can see in the video, I cannot set any value into the Local Sate variable.
I changed browsers, used different pro accounts, but still the same.

I tried 3 accounts, 2 computers, 2 browsers. It shows all the same error.

https://user-images.githubusercontent.com/5080329/208396407-0a88ea2c-91e8-4afa-aadb-eeafb9807283.mp4

https://user-images.githubusercontent.com/5080329/208396426-2b9ec380-c38b-4d5e-8915-03517137e8cf.mp4

https://user-images.githubusercontent.com/5080329/208396869-1058ad1e-dc2b-47f4-9da6-d2168457a295.mp4

**Comment by agreaves** [comment]
Hi @thruthesky and @davhad, thank you both for the bug report. This has been fixed and will be deployed in our next release, likely tomorrow! Apologies for the issue!

**Comment by thruthesky** [comment]
@agreaves Thank you :)
