### ISSUE TITLE
copilot ai fonction costum error

### ISSUE THREAD

**Issue by vivince1991** [FlutterFlow/flutterflow-issues#2431]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the co-pilot has conction which allows you to create custom functions does not work he always tells me to try again later

### Expected Behavior

that it generates code according to my request

### Steps to Reproduce

the app generates those since it does not have any code generated by ai copilot for the costum functions

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

faild to generate code. please try again

### Context

I'm trying to generate a costum fun

### Visual documentation

![Capture](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4e5058a9-4ea6-43fd-8bf8-63bf6401231c/9f41d7c9-bbcd-4121-802f-9b5db53896e1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZTUwNThhOS00ZWE2LTQzZmQtOGJmOC02M2JmNjQwMTIzMWMvOWY0MWQ3YzktYmJjZC00MTIxLTgwMmYtOWI1ZGI1Mzg5NmUxIiwiaWF0IjoxNzA5NTcyODE0LCJleHAiOjMzMjgwMTMyODE0fQ.hpDIRODuytSsGIMgtSaXSHDCl-p46ktfo6SxWAYu0Z0)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:web windows
- Browser name and version:Chrome 122.0.6261.95
- Operating system and version affected: windows 10
```

**Comment by hariprasadms** [comment]
Hi @vivince1991 - I can reproduce the issue. Thanks

**Comment by victoriahuang1** [comment]
I cannot reproduce the issue. @vivince1991 please provide a project ID and / a bug report code. This will be needed to continue debugging.

**Comment by vivince1991** [comment]
I have no error code the only error and on the photo
