### ISSUE TITLE
Reordering "handles" show up in Web Run, but doesn't show up in ios Testflight

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#2434]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have enabled `reorder` for several `ListViews`.

The reorder `handles` appear when I run via the web, but does not show up on iOS

Here is what I see in the web Run:

![▶️ sophia - FlutterFlow 2024-03-03 at 7 11 46 PM jpg](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/82d4f18f-8f62-486b-8809-cd474de4e541)

This is from iOS:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/88122399-4bc8-41ca-adcd-d947c482de9f)

### Expected Behavior

I expect the handles that show up in web run show up in ios

### Steps to Reproduce

1. Create ListView
2. Select `reorderable` toggle
3. Run Web Run
4. Deploy to Testflight

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhcmBy5BNochE0IfqduxKiSgwGUwCaI0z0tlETRQdfuPsOuwuZcjeYRNvcuqHeFBUGFWj+U4y0snFiPL9K/k5IU2dfIhNwbtxUxDhcEi6VaaLDZaKfGtBGfhYfVCh4Z+Jnx5DOrFhZUJk1DuEI+6ua3qCf9qOYwx5e6fDbOY=

### Context

Users of the mobile app should know based on the UI that they can reorder a ListView.

### Visual documentation

![IMG_1AE308ADF0D6-1](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/e07bf460-308f-43b6-94be-be1ac95aba29)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Mac OS
- Browser name and version: 
About Brave
v 1.62.165
- Operating system and version affected: IOS 17.3.1 iphone 13
```

**Comment by bozzoleandro** [comment]
Hi, @timfong888, Thanks for your report about this issue, we were able to confirm it on our side, we will be taking a look.

**Comment by takashiff** [comment]
Hi @timfong888, I have taken a look at your project and it looks to be intended behavior. Since the ListView is dynamically generated (and thus, has infinite scrolling), reordering is disabled as we currently do not support reordering infinitely scrollable widgets. Thanks

**Comment by pedroreactive** [comment]
Same problem here, even if listview has limited number of items sort icons don't appear on mobile browsers and iOS app. And I can't find any native workaround, please fix.

**Comment by takashiff** [comment]
Hi all, we've taken another look into the issue, and the behavior is intentional. The ListView widget is Flutter's native `ReorderableListView`, which has different behavior on mobile vs web. On web, the sort/drag icons can be clicked/dragged to reorder the list. On mobile, the ListView is still reorderable, but in order to reorder the list, the user must hold down and drag the widget being moved. If you'd still like to add the icon on mobile. I would recommend adding a widget that is only visible on certain devices using responsive visibility. Thanks
