### ISSUE TITLE
Optional Nullable Icon Paramters In Custom Widgets Register As Required

### ISSUE THREAD

**Issue by TahaHamad** [FlutterFlow/flutterflow-issues#2435]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

'Widget?' parameters declared in custom widgets (i.e. Icon nullable non-required params) are being treated as required parameters which limits custom widgets testing.

### Expected Behavior

The expected behavior is to treat any optional nullable **icon** parameter as non-required.
I was expecting the icon parameters would be treated the same as setting a 'String?' or 'bool?' or any other parameter.

### Steps to Reproduce

1. Create any empty or non-empty custom widget
2. Set an icon parameter and set it as "nullable" from the right tab and click the boilerplate button, or directly from the code by typing 'Widget?'
3. Place the custom widget on your page
4. You will see an error message on the top right saying "\[customWidgetName\]'s \[iconParam\] not set properly"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slcjf3MtIsdhE17rAKMB7/GUXOUw9U4EWscpCbw4bIYj2P4lzY876P05vOLDiT29cI2Gcp1410fDphuHfEvYoAyeZfYR+z7VxFzviYGOXabGTF7WoPX8nHdtgfECF4JmJvwhCJsBZSVo/w2WbffOvcAnAQITRImo8Sq/LZO4=

### Context

I was trying to implement the Chewie package as a custom widget with extensive features that are all set as optional such as "String?", "bool?", etc by either setting them from the right tab or typing them directly on the editor.

However, upon trying to implement the same logic with Icon parameters I started receiving error messages that the parameters are required even though they were set as nullable in the code editor.

I tried to consult with some fellow programmers and they confirmed that my implementation should work as expected (i.e. the icon parameters will be treated as optional) outside of FlutterFlow. So I suspect it's either an internal issue within the FlutterFlow system, the FF IDE, etc.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8bf76bec-b9e5-4ad1-a38e-97636e050451/e1125131-cad0-4f04-a3c3-bf7e43a60b86?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84YmY3NmJlYy1iOWU1LTRhZDEtYTM4ZS05NzYzNmUwNTA0NTEvZTExMjUxMzEtY2FkMC00ZjA0LWEzYzMtYmY3ZTQzYTYwYjg2IiwiaWF0IjoxNzA5NTUwNjgzLCJleHAiOjMzMjgwMTEwNjgzfQ.EvwgsJvyVAB7bw9ELJh0lkUzyMOanbEqeFDjEXPC4eA)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2ee1f9fe-c57b-4112-80cd-3d16401d5285/71d69545-ced8-460a-aeb1-a540ee16e811?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZWUxZjlmZS1jNTdiLTQxMTItODBjZC0zZDE2NDAxZDUyODUvNzFkNjk1NDUtY2VkOC00NjBhLWFlYjEtYTU0MGVlMTZlODExIiwiaWF0IjoxNzA5NTUwNjgzLCJleHAiOjMzMjgwMTEwNjgzfQ.cse1XZuKe3CSTmk9_nj8U-0XO_DnB9xEbsvyV2DKPxE)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/be98f220-62d3-4f96-9c4d-1d10cbc74eff/e9c31e84-a410-496d-975d-cf2e67d67fc8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZTk4ZjIyMC02MmQzLTRmOTYtOWM0ZC0xZDEwY2JjNzRlZmYvZTljMzFlODQtYTQxMC00OTZkLTk3NWQtY2YyZTY3ZDY3ZmM4IiwiaWF0IjoxNzA5NTUwNjgzLCJleHAiOjMzMjgwMTEwNjgzfQ.TGCOHo3VWMenKTXlWfR1gjM-y8oBDf1klO8_EG7uhqQ)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e67089eb-26a1-42f5-97fb-30b6ff6f4016/76e0472e-5f10-4179-9ce4-1a4ed26cb644?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNjcwODllYi0yNmExLTQyZjUtOTdmYi0zMGI2ZmY2ZjQwMTYvNzZlMDQ3MmUtNWYxMC00MTc5LTljZTQtMWE0ZWQyNmNiNjQ0IiwiaWF0IjoxNzA5NTUwNjgzLCJleHAiOjMzMjgwMTEwNjgzfQ.CTogQx63XQB41TDygnAqYGivo7O0NnkX6nnu39C02kc)

### Additional Info

I am looking forward to having this issue solved as I am trying to build a custom widget with multiple optional parameters, and having to set the value for each one would be a pain!
I searched the internet for this, it doesn't seem like it's a Dart/Flutter issue, but rather FlutterFlow, unless if I missed something!

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Windows
- Browser name and version: Chrome 122
- Operating system and version affected: Windows 11, version 22H2
```

**Comment by rzambroni** [comment]
Hi @DrPenguinn, thanks a lot for the report, I was attempting to replicate this issue but I was not able to do so. Are you still experiencing the problem?
