### ISSUE TITLE
Components with action callbacks with action parameters of enum type,  generate a compile error

### ISSUE THREAD

**Issue by chrisatwyrth** [FlutterFlow/flutterflow-issues#2437]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In downloading code in which I have a component, which takes an action callback as a component parameter, and in turn which has an action parameter of enum type, then generates a compile error by the Dart compile system.

There is a simple fix: the component file is missing an import: import '/backend/schema/enums/enums.dart';

By manually inserting this missing line into the component file, then compile error is then fixed.

### Expected Behavior

The component file should compile without a Dart compile error

### Steps to Reproduce

1. create a component
2. add an action parameter with an enum action parameter.

Generated code will look something like this:::

class PostCommentWidget extends StatefulWidget {
  const PostCommentWidget({
    super.key,
    required this.width,
    required this.height,
    required this.apiErrorCallBack, // HERE is the action parameter
  });

final double? width;
  final double? height;
  final Future Function(ApiErrors? errorType)? apiErrorCallBack; // HERE is the definition of the action parameter, with an enum ApiErrors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

The problem is from the Dart compiler: lib/components/post_comment/post_comment_widget.dart:27:25: Error: Type 'ApiErrors' not found. final Future Function(ApiErrors? errorType)? apiErrorCallBack;

### Context

Cannot compile the generated code

### Visual documentation

![Screenshot 2024-03-04 at 07 55 32](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/54fe6c8e-0566-4806-ae87-5c9fbbd413ca/cf5464ee-fd33-4811-a508-3b0acb66b7e6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NGZlNmM4ZS0wNTY2LTQ4MDYtYWU4Ny01YzlmYmJkNDEzY2EvY2Y1NDY0ZWUtZmQzMy00ODExLWE1MDgtM2IwYWNiNjZiN2U2IiwiaWF0IjoxNzA5NTQxNTIyLCJleHAiOjMzMjgwMTAxNTIyfQ.yjHvthr5ZgymDAWOdeHImPCMrknvmATqSEs2pWlnbc0 "=753x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.17
- Platform: Apple
- Browser name and version: Version 122.0.6261.94 (Official Build) (arm64)
- Operating system and version affected: sonoma 14.2.1
```

**Comment by zerowhybr** [comment]
I have experienced this same issue using a custom data type.

**Comment by davidflutterflow** [comment]
@hariprasadms Seems it's an issue i also experience it. Not sure if it's related to ENUMs or not. But i couldn't return data types containing dateTime fields from an action callback.

**Comment by bozzoleandro** [comment]
Hi chrisatwyrth, we were able to replicate this issue, we're looking into it. Thanks for the report

**Comment by Chrisjhorn** [comment]
Perfect,  many thanks!
