### ISSUE TITLE
Update page state with permission fails build

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#2438]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a page-state-boolean and setting it to the permission for notification on page-load, build fails with the error:
`Launching lib/main.dart on Web Server in debug mode... Waiting for connection from debug service on Web Server... lib/pages/home_page/home_page_widget.dart:33:13: Error: 'await' can only be used in 'async' or 'async*' methods.`

### Expected Behavior

It should not fail

### Steps to Reproduce

1. Create a new page
2. Set notification-permission in settings for the app
3. create a page-state-boolean
4. create an action that gives the page-state the value of permission>notification

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z/Hqx89grs9c15CJacAxgiAXQz47U4JN08J+TRI8J5zKB+wAYvf7P1FWTLylS2NifVn9mjgx/Pfqi9nDKfc3FAWsfIh8+LV6WA6XJWWRVLnTDM3gfW1SFp5hCWqf4KaO2x1APthYWkJm3TmYIditaCrUJO/SOVdAOf+LKdeK2SrDX1iXc2URm05KZDPz

### Context

I want to show on a page if the app has currently the permission to notify the user or not

### Visual documentation

![Screenshot 2024-03-04 110650](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5b659cb8-beb8-404f-829d-1c57baf7c25c/154c56ac-1d12-4a3a-bab7-c497be33c2bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81YjY1OWNiOC1iZWI4LTQwNGYtODI5ZC0xYzU3YmFmN2MyNWMvMTU0YzU2YWMtMWQxMi00YTNhLWJhYjctYzQ5N2JlMzNjMmJiIiwiaWF0IjoxNzEwMjYxMTY1LCJleHAiOjMzMjgwODIxMTY1fQ.ajyF1bvb_Rlik0BnbwRV1le2hxVWNsk0V7yPbS17yPo)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1 (current)
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows 11
```

**Comment by bozzoleandro** [comment]
Hi @webwurm, thanks for your report, it seems that you are trying to use the ‘await’ keyword in a method that is not a ‘future’. Let me know if that helps

**Comment by webwurm** [comment]
I am not using any custom code - so the "await"-keyword is in the FF-code I guess

**Comment by bozzoleandro** [comment]
Hi @webwurm, I was able to reproduce the issue, I will send it to the ENG team so they can work on this! Thanks!
