### ISSUE TITLE
Adding To Cart Glitches 📺

### ISSUE THREAD

**Issue by PathologyBazaar** [FlutterFlow/flutterflow-issues#2439]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

# Adding To Cart Glitches

### Expected Behavior

I Expected It Wont Be Glitchy, Because It Was Not Before! I Tried To Roll Back Too, It Didnt Just Work.

### Steps to Reproduce

I Dont Know Others, Thats Why I Am Asking.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CiPLq25BOxPVG7s7TbfpvimYsJkw2RYInl8IbTUsbN5PND+x/esnRQFJuZ9OrdghqIE6gnjkdpveNm9z1McIFOU2rbJR9/qgAWAqVYFKjVbKnCrmeYUFUGshQfUCE06SVoSUnFPhpc3dh2l6EFe+yfz7AGZf6IjERQ/j/CKPXvgfuQ0SLb3kNh1JWeC/v

### Context

Trying To Solve This

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6af604b5-3f24-40e3-b839-c3f8bedd36b1/f83d3c62-6d8e-41d9-88fb-eda40d8f3fd2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YWY2MDRiNS0zZjI0LTQwZTMtYjgzOS1jM2Y4YmVkZDM2YjEvZjgzZDNjNjItNmQ4ZS00MWQ5LTg4ZmItZWRhNDBkOGYzZmQyIiwiaWF0IjoxNzA5NTYyMjAwLCJleHAiOjMzMjgwMTIyMjAwfQ.H_rm2dvjXIBlUi56Jt1eZsnbz0s0vULJPiHgk56RSiA)

[https://github.com/FlutterFlow/flutterflow-issues/assets/160833658/c03b0a2c-2253-4797-b7ed-a4c4c1f407b2](https://github.com/FlutterFlow/flutterflow-issues/assets/160833658/c03b0a2c-2253-4797-b7ed-a4c4c1f407b2)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Windows 11
- Browser name and version: Chrome Version 122.0.6261.95 (Official Build) (64-bit)
- Operating system and version affected: Microsoft Windows 11 Enterprise 10.0.22635 Build 22635
```

**Comment by hariprasadms** [comment]
Hey @PathologyBazaar - Thank you for reporting the issue. The reproducible steps provided are unclear. Please add more details. Additionally, a better way to debug this would be to create a new project and replicate the exact issue specific to the behaviour you're observing. If the issue persists consistently, it will help in diagnosing the problem more effectively. If the issue persists, please share the bug report code of the blank project. This will help us quickly analyse what's going on in the steps.

**Comment by PathologyBazaar** [comment]
what should i write in that because i dont know how did that error begun and what cause is for it thats why i posted @hariprasadms
