### ISSUE TITLE
FF removes capital letters when copy/paste into ADD DEPENDENCY 

### ISSUE THREAD

**Issue by colinriche** [FlutterFlow/flutterflow-issues#244]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Copy & paste a dependency in custom functions, custom widgets etc
as capital letters are not allowed, expected Uppercase letters to be converted to lowercase
instead they are removed, which can be easily missed and cause an unnecessary bug.
## Current behavior (required)

Paste text into the ADD DEPENDENCY text box that contains capital letters and the capitals are removed and not replaced
## To Reproduce (required)

1. copy some text containing some capital letters
2. paste into the 'Add Dependency' field
3. capital letters are removed
4. when they should be replaced with lowercase letters
5. not an issue when typing as capitals are not accepted 

## Context (required)

May cause an unnecessary bug as the typo is easily missed

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @colinriche, thanks for the bug report! Unfortunately, this is simply the default behavior in Flutter when pasting a string into a TextField with input filters. At the moment, there is nothing we can do about this without completely re-writing how we validate the text in TextFields.

For now, I'm closing this issue and marking it as "Won't fix" until a workaround in Flutter comes up. Sorry about this, and thanks again for reporting!
