### ISSUE TITLE
Unchecked Color Checkbox isn't working in Flutter 3.19.1 - issue with unselectedWidgetColor.

### ISSUE THREAD

**Issue by yanffernandes** [FlutterFlow/flutterflow-issues#2442]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The color selected in to the Checkbox Properties -> Unchecked Color is not working when using flutter 3.19.1, using test mode preview or xcode simulator. The checked color works fine.

![Screenshot 2024-03-04 at 14 29 17](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7113cdd2-5c25-4265-8ed7-247f318fcd27/337454f7-f68a-4947-9683-e851aeb34779?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MTEzY2RkMi01YzI1LTQyNjUtOGVkNy0yNDdmMzE4ZmNkMjcvMzM3NDU0ZjctZjY4YS00OTQ3LTk2ODMtZTg1MWFlYjM0Nzc5IiwiaWF0IjoxNzA5NTc4MzA1LCJleHAiOjMzMjgwMTM4MzA1fQ.97By1IWEs06LYOrga74xtw6noRgEPNlZbRpy6WuY_jk)

### Expected Behavior

When selecting an unchecked color for a checkbox, the application should utilize this chosen color throughout its interface.

### Steps to Reproduce

1. Create a new page.
2. Add a checkbox.
3. Select a color for "Unchecked Color" in "Checkbox Properties."
4. Run the project using Flutter 3.19.
5. Observe that the color is not being used for the unchecked checkbox.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfHlx5ZPm8tA1pSJKflagmA5KUg4aL8w0tVRaCoofbLyB+wyZs+lbkRuXf2oTXxqPmf8nWoW3NaJhvLXA/lfIRycQbZT1qpidzvyUk6jR4/TFJWgSXBTHZhRFXaF55+K2yZdBMFZL2dn2UyTfOyvHxLdQYzsClQkDa/LZO4=

### Context

I use this function to differentiate an important task from a normal task in my app.

### Visual documentation

1. Create a new page.
2. Add a checkbox.

![Screenshot 2024-03-04 at 14 46 43](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a297b20b-a03f-4603-bcdb-6e68929a7c2a/9e9537bc-f0b1-4d24-a2db-3a3b357805d5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMjk3YjIwYi1hMDNmLTQ2MDMtYmNkYi02ZTY4OTI5YTdjMmEvOWU5NTM3YmMtZjBiMS00ZDI0LWEyZGItM2EzYjM1NzgwNWQ1IiwiaWF0IjoxNzA5NTc4MzA1LCJleHAiOjMzMjgwMTM4MzA1fQ.UIc2txFHw-HoQa0cAJ8qBk8EdsIFAZWPK_WOHrGi4Jw "=626x")

1. Select a color for "Unchecked Color" in "Checkbox Properties."

![Screenshot 2024-03-04 at 14 46 59](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/22b9a09d-360b-4577-a1dc-1c0c11dbd9de/6403b7fa-13bb-4b55-8bba-1ead9116e849?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMmI5YTA5ZC0zNjBiLTQ1NzctYTFkYy0xYzBjMTFkYmQ5ZGUvNjQwM2I3ZmEtMTNiYi00YjU1LThiYmEtMWVhZDkxMTZlODQ5IiwiaWF0IjoxNzA5NTc4MzA1LCJleHAiOjMzMjgwMTM4MzA1fQ.QlPvreOpL1qHrrGwraoNxiOXf1aKmxiSMYSArpd1-Ww "=299x")

1. Run the project using Flutter 3.19. (code preview or test mode)

![Screenshot 2024-03-04 at 14 47 15](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3ee85091-5522-4d48-9c0b-aaf7de553f31/a0ffbe80-d560-45d4-a28c-c57de3dd0dfa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zZWU4NTA5MS01NTIyLTRkNDgtOWMwYi1hYWY3ZGU1NTNmMzEvYTBmZmJlODAtZDU2MC00NWQ0LWEyOGMtYzU3ZGUzZGQwZGZhIiwiaWF0IjoxNzA5NTc4MzA1LCJleHAiOjMzMjgwMTM4MzA1fQ.ybJQWgTbIztu2_ZAn3VxWY04lnJRxFEQe9Nc05CGlG8 "=642x")

1. Observe that the color is not being used for the unchecked checkbox.

![Screenshot 2024-03-04 at 14 50 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/77bbb1df-8aab-49ce-be50-b339b28fd964/7095b329-5e90-463c-9ee6-711db7685fa6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83N2JiYjFkZi04YWFiLTQ5Y2UtYmU1MC1iMzM5YjI4ZmQ5NjQvNzA5NWIzMjktNWU5MC00NjNjLTllZTYtNzExZGI3Njg1ZmE2IiwiaWF0IjoxNzA5NTc4MzA1LCJleHAiOjMzMjgwMTM4MzA1fQ.Cg_TDk4VA3dbrr-5WI1OvNZyFJcuHKxpK4M5FDesRAE)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: MacOS
- Browser name and version: ARC 1.32.0
- Operating system and version affected: MacOS Sonoma 14.3.1
```

**Comment by edpaulucci** [comment]
Realmente está com problema.... Unchecked color não exibe a cor selecionada.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/55762059/a0627334-f54f-41c6-b02d-d74d49b813d7)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/55762059/a580c9ae-cec5-44b8-9c55-295af9a94775)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/55762059/83f14e5e-b523-476b-93bd-9ca96da89d3c)

**Comment by michaelmakr** [comment]
I am able to reproduce the same issue. Is there a workaround?

**Comment by Golicraft** [comment]
Yes! Same here. So annoying. Please fix asap

**Comment by bozzoleandro** [comment]
Hi @yanffernandes, we were able to replicate this issue, we're looking into it. Thanks for the report

**Comment by leighajarett** [comment]
This should now be fixed!
