### ISSUE TITLE
Firebase Remote Config not updating Flutterflow

### ISSUE THREAD

**Issue by spier24** [FlutterFlow/flutterflow-issues#2443]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I add or update a Firebase Remote Config Parameter in Firebase Web Console, I do not see the parameters or updates on FlutterFlow. It was working until recently (do not have specific date), I added a new one yesterday and it still doesn't show, I updated one and do not see the updates. My Firebase Firestore/data works fine, so does Auth and Cloud Functions.

### Expected Behavior

Added parameters and updated parameters to show in Flutterflow as intended.

### Steps to Reproduce

1. Add or update a parameter in firebase console and view it in test mode app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlMmAvJdOsbVE7of9LfoxjiYwFjsaU40V0tdTbwwcG4PmPZY2fOr+VFtCOM+6TX5IO0ybkmMdpdaNud7lCvQ6C0itQoNoyqhUZzzzfEalMbaMDM+KZX96DZlnFUy44cG3mxFBPupZc3Acw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am unable to use remote config at all if I can't add or update parameters. This is a showstopper

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9160f496-4c00-4bf5-aee3-b1bce469898d/c9c29d88-cf0e-49dd-bac1-a84c6c4a8ef5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MTYwZjQ5Ni00YzAwLTRiZjUtYWVlMy1iMWJjZTQ2OTg5OGQvYzljMjlkODgtY2YwZS00OWRkLWJhYzEtYTg0YzZjNGE4ZWY1IiwiaWF0IjoxNzA5NTk0NzkyLCJleHAiOjMzMjgwMTU0NzkyfQ.FogXhBr0AdvUpBUi5EromzMh98TJD0jUo8RY69zyLUw "=578x")

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4994cbfa-447e-486f-bd39-32fb262d0e8e/cc8ed286-8e02-45b5-bf11-1a1b881a943b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80OTk0Y2JmYS00NDdlLTQ4NmYtYmQzOS0zMmZiMjYyZDBlOGUvY2M4ZWQyODYtOGUwMi00NWI1LWJmMTEtMWExYjg4MWE5NDNiIiwiaWF0IjoxNzA5NTk0NzkyLCJleHAiOjMzMjgwMTU0NzkyfQ.pbcBCVNNuMcpQm4r0VRlr9CYmzbPiwHKSb9hjegSgns "=906x")

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/94b1667f-3076-49c5-9275-d241e247753c/d1dcad22-1f5d-48e2-82f5-da91ed8ec2b6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NGIxNjY3Zi0zMDc2LTQ5YzUtOTI3NS1kMjQxZTI0Nzc1M2MvZDFkY2FkMjItMWY1ZC00OGUyLTgyZjUtZGE5MWVkOGVjMmI2IiwiaWF0IjoxNzA5NTk0NzkyLCJleHAiOjMzMjgwMTU0NzkyfQ.fzJWMMZEyiee5JNOYtnINONlnmVALhFd13osKDBMGCE "=635x")

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dcc0da66-79b4-430d-bc45-b7e815932369/0a79cdcb-234c-44a0-a1d4-1b074f42cc4e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kY2MwZGE2Ni03OWI0LTQzMGQtYmM0NS1iN2U4MTU5MzIzNjkvMGE3OWNkY2ItMjM0Yy00NGEwLWExZDQtMWIwNzRmNDJjYzRlIiwiaWF0IjoxNzA5NTk0NzkyLCJleHAiOjMzMjgwMTU0NzkyfQ.vG4b3OkMadBX39jBADTFIMgV92mtHDOedCp0QarLTS4 "=433x")

### Additional Info

**This is a showstopper**

### Environment

```markdown
- FlutterFlow version: 4.1.29
- Platform:MacOS
- Browser name and version:Safari 17.3.1
- Operating system and version affected: Web, Mobile, Desktop
```

**Comment by paulperez-dev** [comment]
Hi @spier24! Thanks for your report and sorry for the late response.

We have released some updates since this issue was opened. Can you please confirm if the issue persists?

**Comment by spier24** [comment]
Thank you it seems to be working now.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

On Apr 15, 2024 at 6:36 PM -0700, Paul Pérez ***@***.***>, wrote:
> Hi @spier24! Thanks for your report and sorry for the late response.
> We have released some updates since this issue was opened. Can you please confirm if the issue persists?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by paulperez-dev** [comment]
Glad to hear that! I'm going to close this issue.
