### ISSUE TITLE
Convert to component is unusable

### ISSUE THREAD

**Issue by Miamoto-Musashi** [FlutterFlow/flutterflow-issues#2444]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the title mask of convert to component does get selected preventing use

### Expected Behavior

title mask get selected and I can insert title

### Steps to Reproduce

1. create a layout with nested widgets
2. right click on one of the widget
3. select convert to component
4. notice name mask blink and cannot insert name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShcrq25NgoeED7aXtLe5QhR4kQ0w2U5NF0exEa04cB6rtP4wpWsjRTFVeOsuqS25qe1GLsHEJ+Nb6v4SeUMI3GAyHb7o9ybliVzvgWme6VZSyDLuaREdfNNNmGFyA5piRnBV4NrZZZV1pig/GSw==

### Context

cannot use this function

### Visual documentation

https://www.loom.com/share/7e8493a29a89414da71534f6d8bcc8aa?sid=16898738-81f4-4e4b-a278-dd668b6363f8

### Environment

```markdown
- FlutterFlow version: 4.1.29
- Platform: IOs
- Browser name and version: NA
- Operating system and version affected: MacOs ventura 13.6.4
```

**Comment by hariprasadms** [comment]
Duplicate with #2387
