### ISSUE TITLE
Blank screen when opening a project

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#2446]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When opening the dashboard for projects it shows a blank screen

### Expected Behavior

when opening the dashboard you should able to access your projects

### Steps to Reproduce

open the [https://app.flutterflow.io/](https://app.flutterflow.io/)
after few second blank screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

[https://app.flutterflow.io/](https://app.flutterflow.io/)

### Context

cant work anymore

### Visual documentation

![Screenshot 2024-03-04 at 18 34 31](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/96561fa5-ef99-41c8-8641-ae80143512c0/f4766cac-25ec-41ec-9907-7bee4e3223e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NjU2MWZhNS1lZjk5LTQxYzgtODY0MS1hZTgwMTQzNTEyYzAvZjQ3NjZjYWMtMjVlYy00MWVjLTk5MDctN2JlZTRlMzIyM2U5IiwiaWF0IjoxNzA5NzMxNzQzLCJleHAiOjMzMjgwMjkxNzQzfQ.brnujFXq5om3qmsKDE4GgKHgProyzYEMVhHFOs13HEU "=1727x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: ios
- Browser name and version: chrome
- Operating system and version affected: Sonoma 14.4
```

**Comment by takashiff** [comment]
HI @sergedahdouh, thank you for the bug report. There's currently an issue with [Flutter shaders on Chrome](https://github.com/flutter/flutter/issues/140504). The following steps may help to temporarily work around this issue:

- Go To chrome://flags/
- Search for "Out-of-process 2D canvas rasterization" and enable the flag
- Relaunch the chrome browser

Thanks

**Comment by sergedahdouh** [comment]
> HI @sergedahdouh, thank you for the bug report. There's currently an issue with Flutter shaders on Chrome. The following steps may help to temporarily work around this issue:
> 
> * Go To chrome://flags/
> * Search for "Out-of-process 2D canvas rasterization" and enable the flag
> * Relaunch the chrome browser
> 
> Thanks
> 
> Note: To keep the main Flutter issues thread less cluttered, please refer to [this link](https://github.com/FlutterFlow/flutterflow-issues/issues/2450) on our FF issue tracker to find the link to the Flutter issue.

Great thank you
