### ISSUE TITLE
Experts Flutterflow Bug Account

### ISSUE THREAD

**Issue by nyaroon** [FlutterFlow/flutterflow-issues#2448]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

[https://github.com/FlutterFlow/flutterflow-issues/assets/39451264/267c958c-a807-4114-85e2-17db364e6407](https://github.com/FlutterFlow/flutterflow-issues/assets/39451264/267c958c-a807-4114-85e2-17db364e6407)
Here's the video of problem,
continue from the last bug, it seems i found another bug after its fixing, everytime i open Experts flutterflow it seems my account got reset and need to create new profile, and my experts account got dissapear from list of [experts.flutterflow.io](http://experts.flutterflow.io)
this bug already here from last month and still not fixing that's why i open support

### Expected Behavior

after opening the web, if the user already login directly go to experts homepage

### Steps to Reproduce

1. register account,
2. register experts
3. inputing experts detail
4. the bug show up
   dunno if it;s can be reproduce in another account because i dont havfe other expert account

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiM7qw5dOoeFb+KXpK8dolWARGUMcWOdEl+tuZwgbIoznBuwDd/f4blZtUsviaVNcGmCagmExpfTFkeLhKvAqBzSsGLZYzYd+EQree2iQV82gOpGaWmtSRMNYIVSO55jVkR5ACMxtW1487V+LfOmXSjTDIuu/Zwh9f6PHaOI=

### Context

my experts profile seems got reset and need to be re input everytime i open the site

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/39451264/512284cf-8ed7-441a-8220-de874a0734e2](https://github.com/FlutterFlow/flutterflow-issues/assets/39451264/512284cf-8ed7-441a-8220-de874a0734e2)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: lastest
- Platform: experts
- Browser name and version: google chrome lastest, safari lastest
- Operating system and version affected: windows, and macos
```

**Comment by takashiff** [comment]
Hi @nyaroon, I apologize for the delayed response. Could you reach out to support@flutterflow.io regarding this issue? They may have better capabilities in assisting you, as the GitHub issue tracker is typically for more general, reproducible issues. Thanks
