### ISSUE TITLE
FlutterFlow Crashes!!!!

### ISSUE THREAD

**Issue by NadavTraub** [FlutterFlow/flutterflow-issues#2450]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Suddenly, every time I enter the matchia_upload_photos_page, everything crashes, and I see a black window. It used to work fine until yesterday, but suddenly, it started to crash on this page.

### Expected Behavior

it will not crash and ill be able to continue working

### Steps to Reproduce

just enter the project and select the matchia_upload_photos_page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

cant create one, its happened when selecting the page

### Context

continue working on this page

### Visual documentation

![Screenshot 2024-03-05 at 11 09 53](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5fd5e73e-094d-4439-8183-cabb49e0586d/e690a965-61cb-4cf3-b186-3b340e94dcca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ZmQ1ZTczZS0wOTRkLTQ0MzktODE4My1jYWJiNDllMDU4NmQvZTY5MGE5NjUtNjFjYi00Y2YzLWIxODYtM2IzNDBlOTRkY2NhIiwiaWF0IjoxNzA5NjMwMTc0LCJleHAiOjMzMjgwMTkwMTc0fQ.wK1XiTzz7DDyhO_JnmPJs6OcwrWnSTrKxAopna-THfs "=1401x")

![Screenshot 2024-03-05 at 11 09 34](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/261bcb30-d28a-41b1-9ec5-6145b95c0a6f/d3e9db4e-87ab-4f00-96ce-279fe11cf526?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNjFiY2IzMC1kMjhhLTQxYjEtOWVjNS02MTQ1Yjk1YzBhNmYvZDNlOWRiNGUtODdhYi00ZjAwLTk2Y2UtMjc5ZmUxMWNmNTI2IiwiaWF0IjoxNzA5NjMwMTc0LCJleHAiOjMzMjgwMTkwMTc0fQ.VFwFT61jX3cAONjCY2_ZdKpV8m-WpO23ZB-fQabDIMk "=1410x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: web and macos desktop
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @NadavTraub - Thanks for submitting the issue. Share your project link please.

**Comment by NadavTraub** [comment]
https://app.flutterflow.io/project/matchia-x17o2f

**Comment by sergedahdouh** [comment]
i have same issue but instead of one project, it happens to me when i access the dashboard of any project

**Comment by hariprasadms** [comment]
Hi @NadavTraub - 
I just checked out your project. As I navigated through the pages, I didn't encounter any errors. Everything seems to be working fine in you project.

**Comment by NadavTraub** [comment]
i think its happened when you have a image inside a container with size define in %
@sergedahdouh let me know if you also have it in your page too

**Comment by NadavTraub** [comment]
@hariprasadms stay at the matchia_upload_photos_page for 3 seconds

**Comment by sergedahdouh** [comment]
> i think its happened when you have a image inside a container with size define in % @sergedahdouh let me know if you also have it in your page too

Hello, no, my issue as long as you open https://app.flutterflow.io/, I can see my dashboard for few seconds, then my screen turns blank its FF issue  with chrome

**Comment by hariprasadms** [comment]
Everything is running smoothly on my end. I recommend minimizing the errors you got in the project.

**Comment by sergedahdouh** [comment]
<img width="1727" alt="Screenshot 2024-03-05 at 15 03 11" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/677cb8fb-4dbb-4348-b16d-8f04a6cfe816">
<img width="1727" alt="Screenshot 2024-03-05 at 15 03 17" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40029858/530a0849-a758-4b59-8b9e-2be8cda169ee">
this from console

**Comment by NadavTraub** [comment]
@hariprasadms unfortunately i cant minimizing the errors in the projects because it relate to another issue that been open for long time without any updateds...
https://github.com/FlutterFlow/flutterflow-issues/issues/2354

**Comment by NadavTraub** [comment]
@hariprasadms its nothing to do with my errors (that are not really errors if you will look at my open issue)
try to run it with the latest chrome version: Version 122.0.6261.94 (Official Build) (x86_64)
and open it in the dashboard (dont just try to run the code) please

**Comment by NadavTraub** [comment]
@hariprasadms  yes the problem is with chrome..... just tried to run it in Safari browser and its working fine..

**Comment by hariprasadms** [comment]
@NadavTraub - Thanks for the heads-up. I also use the Chrome browser, but I'm not entirely sure if any installed Chrome extensions might be causing issues. To verify, you can try accessing it in incognito mode.

**Comment by NadavTraub** [comment]
@hariprasadms just tried with incognito.. still crashing..

**Comment by sergedahdouh** [comment]
> @hariprasadms just tried with incognito.. still crashing..

same.

**Comment by jrap1000** [comment]
I am also experiencing this issue on Chrome (works fine on iPad app and Safari). This suddenly happened about 1 hour ago and I have tried going back to previous snapshots where it was working (both earlier today and much further back) but no luck.

**Comment by pream912** [comment]
> > i think its happened when you have a image inside a container with size define in % @sergedahdouh let me know if you also have it in your page too
> 
> Hello, no, my issue as long as you open https://app.flutterflow.io/, I can see my dashboard for few seconds, then my screen turns blank its FF issue with chrome


Facing this issue for couple of days. Blindly clicking at a project's position would open the project, but it is getting worse.

Note: Using Chorme on mac.

**Comment by takashiff** [comment]
Hi all, there's currently an issue with [Flutter compiling on Google Chrome](https://github.com/flutter/flutter/issues/140504). The following steps may help to temporarily work around this issue:

- Go To chrome://flags/ 
- Search for "Out-of-process 2D canvas rasterization" and enable the flag 
- Relaunch the chrome browser

Thanks

**Comment by takashiff** [comment]
Marking as closed since the issue seems to have been resolved.

**Comment by raldred2** [comment]
Works for me... thank you! 

However, surely this is a workaround and not a fix so why is this being closed @takashiff?

**Comment by takashiff** [comment]
Hi @raldred2, this is currently an issue with Flutter/Chrome (and not FlutterFlow), so unfortunately, this is out of our control. We would like to keep our GitHub issue tracker to solely track issues specific to FlutterFlow (i.e. issues that can be fixed by our team), and as such, I have marked this issue as closed. I hope this clears things up for you. Thanks
