### ISSUE TITLE
app store deployment returns a new error - publishing

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2455]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Failed Step: Publishing

== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact starlove.ipa
Publishing artifact App.framework.dSYM.zip
Publishing artifact ImageNotification.appex.dSYM.zip
Publishing artifact Runner.app.dSYM.zip
Publishing artifact AppAuth.framework.dSYM.zip
Publishing artifact openssl_grpc.framework.dSYM.zip
Publishing artifact DKImagePickerController.framework.dSYM.zip
Publishing artifact DKPhotoGallery.framework.dSYM.zip
Publishing artifact FMDB.framework.dSYM.zip
Publishing artifact FirebaseABTesting.framework.dSYM.zip
Publishing artifact FirebaseAppCheckInterop.framework.dSYM.zip
Publishing artifact FirebaseAuth.framework.dSYM.zip
Publishing artifact FirebaseAuthInterop.framework.dSYM.zip
Publishing artifact FirebaseCore.framework.dSYM.zip
Publishing artifact FirebaseCoreExtension.framework.dSYM.zip
Publishing artifact FirebaseCoreInternal.framework.dSYM.zip
Publishing artifact FirebaseCrashlytics.framework.dSYM.zip
Publishing artifact FirebaseFirestore.framework.dSYM.zip
Publishing artifact FirebaseFirestoreInternal.framework.dSYM.zip
Publishing artifact FirebaseFunctions.framework.dSYM.zip
Publishing artifact FirebaseInstallations.framework.dSYM.zip
Publishing artifact FirebaseMessaging.framework.dSYM.zip
Publishing artifact FirebaseMessagingInterop.framework.dSYM.zip
Publishing artifact FirebasePerformance.framework.dSYM.zip
Publishing artifact FirebaseRemoteConfig.framework.dSYM.zip
Publishing artifact FirebaseSessions.framework.dSYM.zip
Publishing artifact FirebaseSharedSwift.framework.dSYM.zip
Publishing artifact FirebaseStorage.framework.dSYM.zip
Publishing artifact GTMAppAuth.framework.dSYM.zip
Publishing artifact GTMSessionFetcher.framework.dSYM.zip
Publishing artifact GoogleDataTransport.framework.dSYM.zip
Publishing artifact GoogleSignIn.framework.dSYM.zip
Publishing artifact GoogleUtilities.framework.dSYM.zip
Publishing artifact FBLPromises.framework.dSYM.zip
Publishing artifact Promises.framework.dSYM.zip
Publishing artifact RecaptchaInterop.framework.dSYM.zip
Publishing artifact SDWebImage.framework.dSYM.zip
Publishing artifact SwiftyGif.framework.dSYM.zip
Publishing artifact absl.framework.dSYM.zip
Publishing artifact assets_audio_player.framework.dSYM.zip
Publishing artifact assets_audio_player_web.framework.dSYM.zip
Publishing artifact file_picker.framework.dSYM.zip
Publishing artifact flutter_keyboard_visibility.framework.dSYM.zip
Publishing artifact grpcpp.framework.dSYM.zip
Publishing artifact grpc.framework.dSYM.zip
Publishing artifact image_picker_ios.framework.dSYM.zip
Publishing artifact leveldb.framework.dSYM.zip
Publishing artifact nanopb.framework.dSYM.zip
Publishing artifact package_info_plus.framework.dSYM.zip
Publishing artifact path_provider_foundation.framework.dSYM.zip
Publishing artifact share_plus.framework.dSYM.zip
Publishing artifact shared_preferences_foundation.framework.dSYM.zip
Publishing artifact sign_in_with_apple.framework.dSYM.zip
Publishing artifact sqflite.framework.dSYM.zip
Publishing artifact url_launcher_ios.framework.dSYM.zip
Publishing artifact video_player_avfoundation.framework.dSYM.zip
Publishing artifact wakelock_plus.framework.dSYM.zip
Publishing starlove.ipa to App Store Connect
> app-store-connect publish --path /Users/builder/clone/build/ios/ipa/starlove.ipa --key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER --issuer-id @env:APP_STORE_CONNECT_ISSUER_ID --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY
/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/models/certificate.py:123: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  return self.certificate.not_valid_after.replace(tzinfo=timezone.utc)

Publish "/Users/builder/clone/build/ios/ipa/starlove.ipa" to App Store Connect
App name: starlove
Bundle identifier: com.mycompany.starsoflove
Certificate expires: 2025-02-19T04:37:18.000+0000
Distribution type: App Store
Min os version: 13.0
Provisioned devices: N/A
Provisions all devices: No
Supported platforms: iPhoneOS
Version code: 4
Version: 1.0.2

Upload "/Users/builder/clone/build/ios/ipa/starlove.ipa" to App Store Connect
2024-03-06 09:56:48.862  INFO: ContentDelivery version 2.141.101 (141101).
2024-03-06 09:56:48.866  INFO: Show Progress: Contacting Apple Services…
{"tool-version":"6.043.14043","tool-path":"\/Applications\/Xcode-14.2.app\/Contents\/SharedFrameworks\/ContentDeliveryServices.framework\/Versions\/A\/Frameworks\/AppStoreService.framework","os-version":"13.3.1","product-errors":[{"message":"The provided entity includes an attribute with a value that has already been used","userInfo":{"original_server_error":{"status":"409","detail":"The bundle version must be higher than the previously uploaded version.","source":{"pointer":"\/data\/attributes\/cfBundleVersion"},"id":"5f39f72b-7dd7-4b27-8b37-f7d0592d0a36","code":"ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE","title":"The provided entity includes an attribute with a value that has already been used","meta":{"previousBundleVersion":"4"}},"NSLocalizedDescription":"The provided entity includes an attribute with a value that has already been used","previousBundleVersion":"4","NSLocalizedFailureReason":"The bundle version must be higher than the previously uploaded version: ‘4’. (ID: 5f39f72b-7dd7-4b27-8b37-f7d0592d0a36)"},"code":-19232}]}

Failed to upload archive at "/Users/builder/clone/build/ios/ipa/starlove.ipa"
Failed to publish /Users/builder/clone/build/ios/ipa/starlove.ipa

Failed to publish starlove.ipa to App Store Connect.

Build failed :|

Publishing failed :|
Failed to publish starlove.ipa to App Store Connect.

### Expected Behavior

App pushes to App store

### Steps to Reproduce

Try to deploy my app to the testflight over FF Mobile Deployment

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCsofePrOpkAf8/7UFtUOLHgTVZDelmZjnIX/Mr3j+DiV/koByeVfotz1qluYDzKfzuRaL3TDYS3b0ZPGZ5NGECby7ejuR1TOsBhdCEF1E6MPOvJYBDcQ6ayDEg/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Can't publish to app store

### Visual documentation

<img width="859" alt="Screenshot 2024-03-06 at 9 17 38 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/93e167cf-2340-4d2a-b61c-7f2b55a51941">

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by wspimentel** [comment]
Did you manage to solve it? I'm facing the same issue.

**Comment by lovestar18** [comment]
@wspimentel - I did solve it - it started working for me again - not sure what went wrong

**Comment by Vadefolarin** [comment]
@wspimentel  @lovestar18   I am having the same issue, please how did you solve it

**Comment by lovestar18** [comment]
@Vadefolarin - it just started working for me again. Maybe try publishing again now?
