### ISSUE TITLE
Naming a Component is not functioning

### ISSUE THREAD

**Issue by kbscherer22** [FlutterFlow/flutterflow-issues#2456]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I select an object to "Convert to Component" I receive a pop-up to name my current component. 

The fillable field for the component name will not let me enter text into the field so I am unable to create a component.

### Expected Behavior

Within the "Convert to Component" naming pop-up I would be able to enter a name to create a component.

### Steps to Reproduce

1. Navigate to my project: "MomsFit"
2. Open my existing component "NewNoteSelectorComponent"
3. Open my "NoteCollectorColumn" object
4. Right click one of the circle containers
5. Select "Convert to Component"
6. View the "Component Name" pop-up
7. Try and enter a name into the fillable field - I am unable to

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksrq24p2rsNK+KrPY8BFpDksI0McWOdEl+tuZwgbIoznBqQTPszBVxNCcNOjaVNcClm0jmo1wMrxhs72UvFfJQ6ufL5nzKtucgrke2imSqbWCZG0eGgnHdJjfFSu1KaznCJ5PrJocUYf2GCQJt69SjfDFOu/Zwh9f6PHaOI=

### Context

I am not able to create any new components in my project

### Visual documentation

[Screen Recording 2024-03-06 at 10.15.34 AM.mov.zip](https://github.com/FlutterFlow/flutterflow-issues/files/14514047/Screen.Recording.2024-03-06.at.10.15.34.AM.mov.zip)

### Environment

```markdown
- FlutterFlow version: V4.1 Released Feb 23, 2024
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Its Duplicate with #2399
