### ISSUE TITLE
JSON data is not being sent in API Call

### ISSUE THREAD

**Issue by apppbuilder** [FlutterFlow/flutterflow-issues#2457]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey everyone,

I have an App State and I'm feeding it with this DataType -> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[nextReview (datetime), phraseRef (docRef), priority (int), stageReview (int), unique_words (string list)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\].

When I call the API sending it as a JSON, it becomes blank.

In my case, I'm calling a Google Cloud Function via API.

Here is the code:

====================================================

```
function transformArray(array) {
  console.log('Iniciando transformArray para', array); // Log in the beginning of the function
  // Verifica se array é null ou undefined e retorna um array vazio caso seja
  if (!array) return [];

  return array.map(item => ({
    nextReview: item.nextReview,
    phraseRef: item.phraseRef,
    reviewStage: item.reviewStage,
    priority: item.priority,
    unique_words: item.unique_words
  }));
}


exports.insertHistoryPhrasesInReview2 = onRequest(async (req, res) => {
    console.log('Função iniciada'); // Log in the beginning of the function
    const data = req.body;

    // const historyPhrases = data.historyToReview;
    // const learningPhrases = data.userPhrases || [];
    // const phrasesLearned = data.userPhrasesLearned || [];

    let historyPhrases = transformArray(data.historyToReview);
    console.log('historyPhrases transformado:', historyPhrases); // Log after transformation
    let learningPhrases = transformArray(data.userPhrases || []);
    console.log('learningPhrases transformado:', learningPhrases); // Log after transformation
    let phrasesLearned = transformArray(data.userPhrasesLearned || []);
    console.log('phrasesLearned transformado:', phrasesLearned); // Log after transformation
```

====================================================

Here's the logs of its console.log in the API Call:

![Logs API](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3cf4c3bd-d927-453c-9eb8-48c0f053cc41/1bcb5e6a-c582-47cc-8cc3-32105a592c14?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zY2Y0YzNiZC1kOTI3LTQ1M2MtOWViOC00OGMwZjA1M2NjNDEvMWJjYjVlNmEtYzU4Mi00N2NjLThjYzMtMzIxMDVhNTkyYzE0IiwiaWF0IjoxNzA5NzY0NDc0LCJleHAiOjMzMjgwMzI0NDc0fQ.3Xa5xyLMSW0TP6XZL0raLZjjdiucp_v-d27ACD_TUR4)

Also, I did the same, transforming it using custom functions and didn't worked. Then I started using the map to JSON and still didn't worked.

![234](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/965aac73-4461-43c0-ac30-f028f6d3c66d/16d938c3-690f-4e24-bdcb-c83e8dc074ee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NjVhYWM3My00NDYxLTQzYzAtYWMzMC1mMDI4ZjZkM2M2NmQvMTZkOTM4YzMtNjkwZi00ZTI0LWJkY2ItYzgzZThkYzA3NGVlIiwiaWF0IjoxNzA5NzY0NDc0LCJleHAiOjMzMjgwMzI0NDc0fQ.uE96ePMLv9ZFIEELkb2s_OfbMfaoh5bfE2GlJTxGDOc)

Also, in this API call to reach the Google Cloud Function, I'm sending String, DataType 1 and DataType 2. Only the String reaches the Cloud Function as expected. Both DataTypes turn {}...

### Also, in this case, I'm using the AppState as **A LIST** of DataTypes. So the JSON needs to return list of itens too and it's just not doing it, just returning blank.

I'm open to give more infos about the issue.

### Expected Behavior

The JSON data should arrive in the Cloud Function.

### Steps to Reproduce

The steps to reproduce are easily:

1. Create a DataType, bind it into an App State.
2. Feed the App State.
3. Call API with this App State to JSON.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CjPLlvJFIocte7q6JcMdVoCMvNlw2RYIw1+xEVg8cDZPOD7AQP8nRP1dUOdDiYHxAJVmZrH8X/MrOuITfLfkBNTWcGKpawqhiZBXMRjqWMLaTCJS3b3J8M/1mJlSC58K3phIkOvRoL2NgwEylNdmtUhbXH4DzC1g3NOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

Does it affect the app funcionality?
Yeah, completely. It's part of the algorythm inside the app that runs in a Cloud Function. I also had much more problems while using the Cloud Function native integration, then switched to API call it, and yet it's not even working, so I can't go over and make the app works as it should.

### Visual documentation

Don't have it for now.

### Additional Info

No adittional infos for now.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released March 8, 2024, Flutter version is 3.19.1
- Platform (e.g. Web, MacOS Desktop): Android or any other that can execute an API Call
- Operating system and version affected: Any system version
```

**Comment by apppbuilder** [comment]
Is this issue going to get any attention? @leighajarett @hariprasadms @sbis04 ?

**Comment by apppbuilder** [comment]
Well, it's been an entire month... Can I get an answer on this FF bug? @rzambroni @bozzoleandro @leighajarett @hariprasadms @sbis04 @takashiff

**Comment by apppbuilder** [comment]
Also, I found another way to reproduce this bug.

1. Create API call sending the JSON data in the Body field (without it being an AppState).
2. Test the API Call.
3. No JSON file is sent.

I made a video showing it live.

https://youtu.be/bybqpO_V5L0

**Comment by apppbuilder** [comment]
It's been more than a month with this issue, I can't do the things work inside the app and no answer since then... Can you guys point anything on this? @leighajarett @hariprasadms @sbis04 @rzambroni @bozzoleandro @takashiff

**Comment by paulperez-dev** [comment]
Hi @appbuilder! Thanks for your report. So sorry for the delay in the response, we are trying to get up to speed.

I noticed you opened another issue that seems related to this, is it the same issue? If not, please replicate this issue in the blank project @rzambroni is asking for. Paste the new bug code here and we will take a look.

Thanks so much!

**Comment by paulperez-dev** [comment]
Closing this issue since we have not heard back
