### ISSUE TITLE
Does not allow editing a component or page

### ISSUE THREAD

**Issue by ingsistempro** [FlutterFlow/flutterflow-issues#2458]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am currently working with the "chatPreview" component in our project. I've noticed that I am unable to access the fields of this component or modify its variables from the panel I am working on. In this case, the fields I would like to edit are the name, photo URL, and description as shown in the attached image.

* It's not possible to select the variables of the "chatPreview" component or page in order to change their values directly.
* I am unable to access the actions associated with the component and require assistance in editing them as well.

I have attempted to understand the structure of the component and verify the visibility of the fields, but so far, I have been unable to resolve the issue. I have reviewed the available documentation, but I have not found relevant information regarding this specific problem.

### Expected Behavior

Accessing the fields of the "chatPreview" component in our project and being able to modify its variables from the panel are essential requirements. Specifically, I need to edit fields such as the name, photo URL, and description, as depicted in the attached image.

Additionally, I am unable to access the actions associated with the component and require assistance in editing them as well.
![errorChatPreFlutterflow](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/b9697d10-c535-474c-bc56-abac46c54bff)
![errorChatPreFlutterflowEdit](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/2cf69fef-55a0-43c9-8e82-498227779a46)

### Steps to Reproduce

1.Open your project in FlutterFlow and navigate to the screen editor.
2.Select the component you want to edit.
3.In the properties or settings panel of the component, locate the variable you want to modify.
4.Click on the variable to select it.
5.Edit the value of the variable in the corresponding field or through dropdown options, depending on the variable type.
6.Save your changes by clicking on the save button or applying the changes according to the FlutterFlow interface.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcmAvM91rs9H+YSJdcBKmiQ6NkccT5AzjdZxcykaIoysP4kQPPWkZRZvOeHnYX9UeUSmmj4EwtaLk/HDV/oBPS2WQJx7zZNcawvieEClUZOBPLqKSEFtI8dVFWHD07SJhwhSPvRecWRiw2aYP9itdHPcHq7zIlFISq/LZO4=

### Context

I'm having trouble changing the data of the "chatPreview" page or component in our project as shown in the attached image. I would like to be able to modify the name, photo URL, and description. Additionally, I wish to edit the actions to implement new functionalities. For instance, when clicking on an item in the ListView, I need to pass new parameters to the next page. I appreciate any guidance or assistance you can provide to address this issue.

### Visual documentation

![errorChatPreFlutterflow](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/0c6c9391-fb8a-4830-a8a5-69d9965369b4)
![errorChatPreFlutterflowEdit](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/f4f2d806-ce7c-42dc-b3b2-34cb5d2cc0af)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released February 23, 2024
Flutter version is 3.13.7
- Platform: WINDOWS
- Browser name and version:Actualizando Brave
Versión 1.63.165 Chromium: 122.0.6261.94 (Build oficial) (64 bits)
- Operating system and version affected: OS 64 bits, procesador basado en x64
```

**Comment by ignalauret** [comment]
Hey @ingsistempro thanks for your report. I have tried to replicate your bug but I'm able to modify the variables correctly with the interface. <br>Are you still seeing this issue in your end or was it fixed with newer versions of the platform?
