### ISSUE TITLE
No option to delete a folder

### ISSUE THREAD

**Issue by Peghbali** [FlutterFlow/flutterflow-issues#2459]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I right click on a folder and cannot find the option to delete it, only rename it. 

### Expected Behavior

According to the docs, there should be an option to delete folders.

### Steps to Reproduce

1. right click on folder and there is no option to delete it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gof1C0ZDpLcdQhQIgQ0QnU7gnlO1ucx4jCJSoPJouOeDCQ0NKTMCqYGNPe1Kb8WcH/sLIhuHpFvEpPSudba5R0JVAaRfjUXylaaa3BquWQnxAGfpNGhGzy7bZkCZdOvp2c1Yt22GpNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I need to delete unuseful folders

### Visual documentation

<img width="282" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/162514622/f249f973-2095-4ff2-8c44-f27924fbe7da">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:web
- Browser name and version:chrome latest version
- Operating system and version affected: windows 11 enterprise
```

**Comment by hariprasadms** [comment]
Hi @Peghbali - Thanks for submitting the issue. At present, you see delete option when folder is empty. if a folder container items, delete option not available. Thats the enhancement will be available soon.

**Comment by Peghbali** [comment]
Thank you for letting me know!

Em qui., 7 de mar. de 2024 às 07:34, Hari ***@***.***>
escreveu:
