### ISSUE TITLE
Using supabase the relation "Contained By" show a gray screen

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#246]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I want to filter a row if it is contained with a value

## Current behavior (required)

Show a gray screen

## To Reproduce (required)

1. Create a button
2. Go to the Action Flow Editor
3. Add an action
4. Supabase -> Update a row
5. Select any table
6. Go to Matching Row section
7. Add a filter
8. Choose any field name
9. Choose "Contained By" relation
10. Appears the gray screen

### Bug Report Code

I can't generate the Bug Report Code, show me the following message
"Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)"

## Context (required)

I want to filter a row if it is contained with a value

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/208530926-846788f0-b4b5-45ba-a81a-8ffff51b1d71.png)

## Your environment

* Version of FlutterFlow used: December 16 December
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by agreaves** [comment]
Hi @Franco98404, thanks for the bug report! Could you include the Bug Report Code for this project? It looks like you had a permissions error, so you just need to grant FlutterFlow clipboard permissions ([instructions on accessing clipboard permissions](https://support.microsoft.com/en-us/office/troubleshoot-copy-and-paste-errors-in-powerpoint-for-the-web-0dc01da6-6988-40e5-96ea-0567c151ae2f)). Thanks!

**Comment by Franco98404** [comment]
I have permission to the clipboard
![image](https://user-images.githubusercontent.com/36147203/208548160-38913d69-9092-4e8c-a5e4-e032d35110b4.png)

**Comment by Franco98404** [comment]
I switched to Chrome and generated the code there:
IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp141wtLSv4SWCMIVNQuZQLZf+atiEDzKcH+WbqnfU/HUACkbeacOQSj6

**Comment by SiraEnterprises** [comment]
Following error is thrown by Supabase

operator is not unique: bigint <@ unknown

Seems like someone by mistake added "<" for contained by. Operator for contained by is @
