### ISSUE TITLE
the Dart compiler exited unexpectedly

### ISSUE THREAD

**Issue by kasdef** [FlutterFlow/flutterflow-issues#2460]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I'm trying to load my project in test mode, about 70% of the time I get a Build Failed error saying “the Dart compiler exited unexpectedly.”

There is no further description, and I have no critical (red) bugs in my flutter project.

![Scherm­afbeelding 2024-03-07 om 11 07 34](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/70f158e5-f1b1-4fe0-8423-ba4d4f00d63d/71d1fbee-8f50-429d-a084-04f829316851?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MGYxNThlNS1mMWIxLTRmZTAtODQyMy1iYTRkNGYwMGQ2M2QvNzFkMWZiZWUtOGY1MC00MjlkLWEwODQtMDRmODI5MzE2ODUxIiwiaWF0IjoxNzA5ODE2NDkwLCJleHAiOjMzMjgwMzc2NDkwfQ.J_C-g7di3B_cx9D5V33PgFUgP4nCfcwa2_hshG5v3HE "=625x")

![Scherm­afbeelding 2024-03-07 om 11 14 25](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/984023aa-9aaf-45c6-bdaf-de79201adffc/62bbd257-f7c1-4075-86dc-2722b6d5e1cc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ODQwMjNhYS05YWFmLTQ1YzYtYmRhZi1kZTc5MjAxYWRmZmMvNjJiYmQyNTctZjdjMS00MDc1LTg2ZGMtMjcyMmI2ZDVlMWNjIiwiaWF0IjoxNzA5ODE2NDkwLCJleHAiOjMzMjgwMzc2NDkwfQ.biNMEs8wJISGpc5mC7qKyWdz8pGT7ciNAyoQkLao8j4)

### Expected Behavior

Not ginging the bug

### Steps to Reproduce

Start a test mode in my project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlPHl0It2seFe1aXqccFB/To5KUM7a4ZNm+1DbwkaNYPNG4gIZfTBXE9uOP25dglcI06arGcK0PTNm9z1FfFcOReuY6Fzz7pMcDrKfF+6M7qICZOaOXFEGshUfkCCy6eJghBQFNZsSVYN2UyuA+SsfC3AH7rvDjIFIs+aFJrXmAfuQ0SLb3kNh1JWeC/v

### Context

It is taking a lot of my time.

### Visual documentation

![Scherm­afbeelding 2024-03-07 om 11 07 34](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a60d1993-ae7b-4484-a88d-06798c50ed83/efb076fb-1e8b-41e0-baf0-e61d600ad77b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNjBkMTk5My1hZTdiLTQ0ODQtYTg4ZC0wNjc5OGM1MGVkODMvZWZiMDc2ZmItMWU4Yi00MWUwLWJhZjAtZTYxZDYwMGFkNzdiIiwiaWF0IjoxNzA5ODE2NDkwLCJleHAiOjMzMjgwMzc2NDkwfQ.YKYJpUd16ffQf8sbiDulBdZXTyA8wfSxShaJ0UBF8mw "=625x")

![Scherm­afbeelding 2024-03-07 om 11 14 25](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/353cfb06-ad35-4ee2-be4e-65d41a69d2ea/5d24199b-29d5-4323-8611-80062b59fafe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNTNjZmIwNi1hZDM1LTRlZTItYmU0ZS02NWQ0MWE2OWQyZWEvNWQyNDE5OWItMjlkNS00MzIzLTg2MTEtODAwNjJiNTlmYWZlIiwiaWF0IjoxNzA5ODE2NDkwLCJleHAiOjMzMjgwMzc2NDkwfQ.v-M_NxVF3Q1422HTpdj0Nghah2-dVmUWY583hARfSZU)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: mac os, web
- Browser name and version: Chrome 122.0.6261.111
- Operating system and version affected: 14.2.1
```

**Comment by bozzoleandro** [comment]
Hi @kasdef, thanks a lot for your report!, I'm not able to reproduce it, Are you still having this issue? please let me know so we can help you.

**Comment by kasdef** [comment]
I will let you know! I'm currently using the new local run feature and that works better for me. Thanks for your response.Op 8 apr. 2024 21:33 schreef bozzoleandro ***@***.***>:
Hi @kasdef, thanks a lot for your report!, I'm not able to reproduce it, Are you still having this issue? please let me know so we can help you.
