### ISSUE TITLE
Dependency conflict. Unable to debug on Vscode or Xcode

### ISSUE THREAD

**Issue by inigousoa** [FlutterFlow/flutterflow-issues#2462]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dependency Conflict: http 1.2.0 Incompatible with flutter_test Due to web Version Pinning

### Expected Behavior

There shound't be any dependency conflicts

### Steps to Reproduce

Push repository and attempt running Vscode or Xcode debugger.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlsjf35dIseVG+KXcYcJoqGYRI0MdXOczitVEew4bCIj4OrAQdc+lX1VDXsCzaH1be1mJglIew+/Gvof1M/FfCz6YbqZO1rtcURPPbEi5Ma7UPZavdnJQJ5hWGn6e3J+O3B4mAPFsSWQY71OIDeitHj6Cf9qOYwx5e6fDbOY=

### Context

Unable to test on iOS simulator or real device

### Visual documentation

![Screenshot 2024-03-07 at 6 06 02 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0bda61c1-1ff6-4671-a8ec-1b658af1309f/97402d09-2fb0-4dc9-a32a-50c8f91435bf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYmRhNjFjMS0xZmY2LTQ2NzEtYThlYy0xYjY1OGFmMTMwOWYvOTc0MDJkMDktMmZiMC00ZGM5LWEzMmEtNTBjOGY5MTQzNWJmIiwiaWF0IjoxNzA5ODMzNzMzLCJleHAiOjMzMjgwMzkzNzMzfQ.rBj7BqmUZ8ru5cuxMHO0MrI_KTf1EAiORZXucl-QfGI "=705x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by maxIrvine** [comment]
I'm also having this issue and can't deploy as a result

**Comment by agreaves** [comment]
Hi folks, this is likely due to custom code dependencies that are outdated or no longer compatible based on the recent Flutter 3.19.1 upgrade.

Could you please include the relevant Bug Report Code's to this ticket for any affected projects (right click anywhere on the widget tree and you should see the option)? Thanks!

**Comment by maxIrvine** [comment]
@agreaves Thanks for the response! Here is my bug report: 

IT4slvHl289Nobxc+Kr9bcJR/TgvKUQ9RoI0scpCbw4bIYj2P4lzY876P05oTfbnYWNYOFqcp14e+MqOjdrhL/U4Hy6rbak6+JBIajngczuQVZOTF7W0T0ZDINJYIUiC0pjQsBMlWehhdGRk3Tm6OdyyaCbaHZz0PWo8Sq/LZO4=

**Comment by inigousoa** [comment]
@agreaves Updated the bug report code sorry about that

**Comment by inigousoa** [comment]
Is this something project specific? Because none of my custom code uses the http, flutter_test or web packages.

**Comment by maxIrvine** [comment]
@inigousoa ^^ same here

Isn't http built into flutterflow?

**Comment by agreaves** [comment]
Oh I see, does this occur when debugging locally? If that's the case, you'll need to update Flutter locally to version 3.19.1 (and make sure to get the latest code from your project).

**Comment by maxIrvine** [comment]
@agreaves That worked for me! Thank you!

**Comment by inigousoa** [comment]
Worked as well!! Ty
