### ISSUE TITLE
APK Download not working

### ISSUE THREAD

**Issue by jonny07** [FlutterFlow/flutterflow-issues#2463]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to build the APK of the following project: [https://app.flutterflow.io/project/sleep-position-o6gz6q](https://app.flutterflow.io/project/sleep-position-o6gz6q)
Already waiting since 30minutes for the second time now and still no APK available (update: after 3h still no APK, just the circling circle next to the download), should be availabel in 2-4min according to documentation. Seems it never comes.
This is urgent, as I can not go on with development if I can't get the APK. There should be at least an error message when APK creation is not working!

### Expected Behavior

The APK is available for download

### Steps to Reproduce

Copy the custom action from aboves link to a new custom action.
In the widget pallette: Add a button that opens the custom action.
Click create APK

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whcn135NPtbxH1s72acdFoCYXGDs5R7gZ1MFHZCs8GZT0B4kcYs+kfklUOMunS2w3I02Jqz4X/Mrok+H1DsICNQiVGLpS+rpMEQrwfH2RRKayPb63b3NDEcpTfWqh4aWk2QokLs9vckEu1F+LN/KsdBbZJrLxC0UBI+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

I want to connect to the Polar H10 sensor. This does not work in the browser on my phone, so I assumed it woulf work with an APK.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cc9bfcb9-9dac-4a8e-89d6-382f1068d2b9/30c80e84-cf5c-4346-9c64-3838b96e66a4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jYzliZmNiOS05ZGFjLTRhOGUtODlkNi0zODJmMTA2OGQyYjkvMzBjODBlODQtY2Y1Yy00MzQ2LTljNjQtMzgzOGI5NmU2NmE0IiwiaWF0IjoxNzEwMjYxMjIwLCJleHAiOjMzMjgwODIxMjIwfQ.beLEr-jWPz2ofprNVwUx3mI_3oAKNn5EqHegrDiSk_w)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web (on windows, Edge)
- Browser name and version: Edge Version 121.0.2277.128 (Offizielles Build) (64-Bit)
- Operating system and version affected: Windows 11 Pro 23H2
```

**Comment by hariprasadms** [comment]
Hi @jonny07 - Thank you for bringing up the issue. Are you still encountering the problem? I tested the APK download after the latest update, and while the download is working properly, there seems to be a delay compared to before. However, this delay may be a temporary glitch in the network. Could you please check again and confirm if the issue still persists?

**Comment by jonny07** [comment]
Thanks a lot for your feedback. At least I get an error message now. So I need to increase the min SDK version. Where can I do this in flutterflow? Found some older threads on google where it was not possible, which means flutterflow would be useless for me. Is it possible in the mean time to change that value?
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5730137/b0d04221-03de-482a-9477-4731f9bda5a1)

**Comment by jonny07** [comment]
Will someone set a new label, I answered few days ago?

**Comment by rzambroni** [comment]
Hi @jonny07, sorry for the delay in the answer. Unfortunately, as of now, it is not possible to control the minsdk version from flutter flow. It was previously reported and added to the team's backlog as a feature request. We hope they can get to it soon.
[https://github.com/FlutterFlow/flutterflow-issues/issues/1809](https://github.com/FlutterFlow/flutterflow-issues/issues/1809)
Thanks for the report!
