### ISSUE TITLE
GridView Displays Null Values as Empty Fields Despite Exclusion Instructions from Query

### ISSUE THREAD

**Issue by ingsistempro** [FlutterFlow/flutterflow-issues#2465]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The error being encountered is that, despite instructions from the query to exclude certain fields, the GridView widget displays null values as empty fields. Instead of showing these empty fields, it would be more appropriate for the GridView to completely omit the display of fields that should be excluded according to the query instructions. This would ensure an accurate representation of the data and prevent confusion in the user interface.

### Expected Behavior

To address this issue, the GridView widget should be modified to accurately follow the query instructions. During grid rendering, it should check each field against the query instructions. If a field is marked as excluded or if its value is null, the GridView should skip rendering that field entirely. This approach ensures that only relevant and non-null fields are displayed, thereby providing a more accurate representation of the data in the user interface.
![errorGridView1](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/c4135e27-a7dc-44be-9202-4d8687b77a81)

### Steps to Reproduce

Retrieve Data: Fetch the data to be displayed in the GridView, along with the instructions provided by the query regarding which fields should be excluded.

Iterate Over Data: Iterate over each item in the data set.

Check Exclusion Criteria: For each item, check if it meets the criteria for exclusion based on the instructions provided by the query. This may involve checking if certain fields are null or if they are marked for exclusion.

Render Grid: When rendering the GridView, only include the fields that are not excluded according to the criteria determined in the previous step.

Display Relevant Data: Ensure that only relevant and non-null fields are displayed in the GridView. Omit rendering any fields that should be excluded based on the query instructions.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcmAvM91rs9H+YSJdcBKmiQ6NkccTIAZm+5+cy8YGIytBqQIeszBXBBCXf3gaVNcIU2bpHMDpN7KkobTLPYBHwWCQal8yKhqEA7ke2iXRa6mO4eOYHJPMJ5UCkyYyrSznyJ7HLR2ck4k61yQe++XXjbDIuu/Zwh9f6PHaOI=

### Context

"Estamos encountering an issue with data display in our application. We utilize a widget called GridView to showcase a grid of elements on the user interface. However, we're facing challenges in handling the appearance of empty fields within this grid. Despite our efforts to hide these fields using visibility properties and refining our data queries, they still persist in the grid.

This situation is problematic because we aim for the grid to display only relevant data, avoiding the presence of empty fields. Currently, we're seeking a solution that allows us to accurately filter the data and ensure that only fields with valid values are shown in the grid."
![errorGridView2](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/c534f57d-0b9d-40c1-af90-fb51264c0631)

### Visual documentation

![errorGridView2](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/663e962b-dfd4-40dd-a1f0-d93db83fbfce)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126360060/2cb68368-9790-48a1-8b6d-11515f06984a)

### Environment

```markdown
- FlutterFlow version: v4.1 released February 23, 2024
Flutter version is 3.13.7
- Platform:WINDOWN 10
- Browser name and version:Versión 122.0.6261.96 (Build oficial) (64 bits)
- Operating system and version affected: X64
```

**Comment by paulperez-dev** [comment]
Hi @ingsistempro! Thanks for your report and sorry about the delay in the response, we are trying to get up to speed with everything.

What about adding a new filter not to consider if the value is Null?

Also, we recently released a new version, can you please let me know if the issue persists? If so, please share the bug report code again from a blank project with the minimal code to reproduce it.

**Comment by leighajarett** [comment]
Closing this issue since we have not heard back
