### ISSUE TITLE
Google Play Store Deployment Issue

### ISSUE THREAD

**Issue by nhatzbulawan** [FlutterFlow/flutterflow-issues#2466]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I clicked the Deploy to Play Store button, I received an error message "Codemagic build error: FormatException: Could not find End of Central Directory Record".

I followed the steps mentioned here [https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment](https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment).

### Expected Behavior

Based on this link [https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment](https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment), it should generate the AAB file.

### Steps to Reproduce

1. Go to Settings -> Mobile Deployment.
2. Click The "Deploy to Play Store" button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kks/qw5VNseFD7r6JKvpahjwUNjN+aucolsB+dxcjfLXpG7YAW/SkQE9WZ7yhdH03PE2apHE1/vTWhszIN/oFByqWQbpD1LhIVhb/QnKhV4iSELuwf3dCTdpKCWnG1pmgkxF5D7daLUY53WD7NdmWZCvsQZDXDlU7Lf6LIdjXo3fuQ0SLb3kNh1JWeC/v

### Context

I want to deploy the App on the Play Store

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/3007744/3987e7a9-9445-4f6c-bae6-3706c18d9c71](https://github.com/FlutterFlow/flutterflow-issues/assets/3007744/3987e7a9-9445-4f6c-bae6-3706c18d9c71)

Please see video.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Chrome 122.0.6261.112
- Operating system and version affected: macOS Sonoma 14.2.1 (23C71)
```

**Comment by hariprasadms** [comment]
Hi @nhatzbulawan - Thank you for submitting the issue. Upon reviewing your project, it seems that there is no Android build yet, possibly due to it not being successfully deployed yet. The error you're encountering could be an intermediate issue at the Codemagic end. Overall, the Play Store deployment appears to be functioning as expected. However, I recommend trying to deploy more than once to check the consistency of the error. If the error persists, please provide an update here. Thanks!

**Comment by nhatzbulawan** [comment]
Hi @hariprasadms , Thank you for your response. 
However, I tried it multiple times before I submitted an issue here in Github. 

You mentioned that there is no Android build yet. You are correct because based on the instruction [here](https://docs.flutterflow.io/settings-and-integrations/app-settings/mobile-deployment/google-play-store-deployment#id-4.1-getting-the-aab-app-bundle-file) I need to generate the AAB and upload it to Play Store for fresh deployment. 

The problem is I cannot generate the AAB File because of the issue I reported. I tried it more than 10 times, but the same issue still exists. 

Is there something that we can do about this?

**Comment by hariprasadms** [comment]
Thanks, @nhatzbulawan, for the update. I'll flag this as a project-specific issue, as I can confirm that Play Store deployments are generally working fine. In the meantime, if you could try this in a brand new project and see if the error persists, that would be great.

**Comment by nhatzbulawan** [comment]
Hi @hariprasadms,

Thank you for responding to my queries. However, if it works in the new project, I need to re-create everything and set up a new package name and everything. 

Is there still a way to fix the current project that I am working on?

**Comment by hariprasadms** [comment]
I have flagged the issue as project specific now. It will be checked by Dev team shortly. But no ETA at the moment. Meanwhile if you could double check the issue in a new project that would be great.

**Comment by nhatzbulawan** [comment]
Hi @hariprasadms, 

I managed to deploy the duplicated project.
