### ISSUE TITLE
Crash in ListView Page (ios)

### ISSUE THREAD

**Issue by abyssmaljib** [FlutterFlow/flutterflow-issues#247]
## Expected behavior (required)

For ListView, I made it like a feed in social media, including username, time, and content. Each "post" will display a data "report" as well. It should appear nicely and shouldn't crash.

## Current behavior (required)
It crashes in ios. 

## To Reproduce (required)
[https://flutterflow.intercom-attachments-3.com/i/o/638214561/4590d8b9e42119f329e6d788/IMG_2323.mp4?expires=1671504028&signature=f88d92f480b544474bb099a57462af115be64f020e2e56f730c7b89794967313](url)

In test mode, it runs well but crashes on ios when deployed to testflight.

### Bug Report Code
`IT4oj8jf34p2pbxH1rXuY+9ahSQXNU9/RLsemspBZzUYF5SuCLMqY8mnP1RBXcioY39APFqcp14Cwcr9j9meFsE6ITKWR4RM+bpyEDuUcE2nV4/fU/HUACkbeacOQSj6`

## Context (required)

I tried to change listView to the column, but it still crashed. This view is supposed to show all my employee reports for me to check if their report is correct.

## Screenshots / recordings
[https://flutterflow.intercom-attachments-3.com/i/o/638214561/4590d8b9e42119f329e6d788/IMG_2323.mp4?expires=1671504028&signature=f88d92f480b544474bb099a57462af115be64f020e2e56f730c7b89794967313](url)

## Your environment

* Version of FlutterFlow used: FF v3.0 Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Brave
* Operating system and version (desktop or mobile): ios

**Comment by abyssmaljib** [comment]
> 

Sure
https://youtu.be/yq2tyndKzLY

**Comment by wenkaifan0720** [comment]
If it is possible, would you mind share with me the project link? I can test your project on my end and see if it crashes.

**Comment by abyssmaljib** [comment]
of course, Here 
https://app.flutterflow.io/project/irene-plus-r-l142w1
(on the test mode it seem fine but it crash on ios test drive)

**Comment by wenkaifan0720** [comment]
Hi @abyssmaljib. This issue has been fixed. Thank you for your patience.
