### ISSUE TITLE
Buttons not working on live app

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2471]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the "back" "change cover photo" and "change profile photo" are not working

### Expected Behavior

1. When you push back button, it navigates back
2. Change cover photo allows you to change the photo
3. Change profile photo allows you to change the photo

### Steps to Reproduce

1. Test application in test flight
2. Go to edit profile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCosfZT2BLMcec/RVERCTemiYFFMe2f9jWoW0fTvveP1U/BcFAStR6Je1rtiaQLLTj25M7q6FJWgdEBPHp5Qf33GyLbYghFAKu9vc1Y/3zm6F96sfA/dHYT1DGwsDq/LZO4=

### Context

Can't publish app live

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/744fc019-5c64-4dda-8699-8a609450095b](https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/744fc019-5c64-4dda-8699-8a609450095b)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
Hello @lovestar18 - You've provided the project bug report code, but you haven't specified where to locate the issue within your project.After navigating through the pages and comparing with the video clip, I found the issue. In the "Edit Profile" page component, there's a callback action for navigating back. However, inside the component, there you got  "Choose Image" and "Upload to Firestore" action. That's the reason why clicking on the button triggers the image upload bottom sheet and navigates back. To resolve this, you should remove the navigate back action and make it a separate component. This approach will help you fix the issue.

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! I have deleted the "navigate back" action for now and am trying to see if that works but can't test it at the moment.

I am experiencing a similar issue on the _chat_2_details_ page as you can see in the video, nothing populates when I press the "+" button - any advice on how to fix this?

Thank you!

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/c39d981e-4452-4aa4-98d3-9bf8d8dfe097

**Comment by lovestar18** [comment]
Hi @hariprasadms - I am still facing issues with the upload button on the edit profile. It is not working. Please see the video below and let me know your thoughts.

I can only take a picture for the change cover photo. I can't upload a photo for the cover photo or profile photo. The profile photo button won't even click.


Uploading RPReplay_Final1710382627.mov…



Thank you!

**Comment by lovestar18** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/b36b55c1-6291-4e0b-a323-29c6a2cc30ef

**Comment by lovestar18** [comment]
Hi @hariprasadms - I can now take a photo and upload it as a profile photo but when I press gallery it does not work.


https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/ea682e52-cc92-436c-8b65-0424687af945
