### ISSUE TITLE
Can't use current row index or is ascending in DataTable sort action

### ISSUE THREAD

**Issue by zerowhybr** [FlutterFlow/flutterflow-issues#2472]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Before the latest update to v4.1, my project had a DataTable with a custom sorting action that used the two available actions: the current row index and the is ascending flag. Now, when I try to use them, the option to use the variable is not selectable and is not applied.

### Expected Behavior

The variables should be applied and the app should't restrict the usage of them in the on sort changed action.

### Steps to Reproduce

1. Create new page
2. Add a DataTable
3. Configure the sorting action normally
4. Try to use the sorting action variables in an action
5. FlutterFlow doesn't allow to use them

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lPLq25dIsctZ1rrtbfpsmj45Jk9/a5E/09V7aBosCJzwP4lzZ8nRUEleTcPid21cIVqjsGcIpsqNhezLFsEoZAiIQ745ypANcgmVXjmhb5SbELrpZ3J6BcJTJ26a35qOighTJuloS04e12WyAui9aAjZO4TTNTA/Dci1IqHD+w+6GADNDjhQtmNecCfn

### Context

This issue affect the normal usage of DataTable data sorting

### Visual documentation

Image showing the option to select both available DataTable variables, but when clicking them nothing happens

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d569aa98-011f-4cf8-a772-801e65697c41/48779325-95ee-452c-a1d9-3a5c2fcdd16c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNTY5YWE5OC0wMTFmLTRjZjgtYTc3Mi04MDFlNjU2OTdjNDEvNDg3NzkzMjUtOTVlZS00NTJjLWExZDktM2E1YzJmY2RkMTZjIiwiaWF0IjoxNzA5OTI3NzY3LCJleHAiOjMzMjgwNDg3NzY3fQ.CD4-Y7vFGQzS7ECDDlJnOxroLgenjFwsRX7KWq7JTjI)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released March 7, 2024. Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Chromium Version 122.0.6261.111
- Operating system and version affected: Arch Linux
```

**Comment by davidflutterflow** [comment]
@hariprasadms We troubleshoot this in Support, Seems you can't use the tableIndex for any integer or double.
Also the same is happening with the isAscending variable

**Comment by MaxFF1800** [comment]
<img width="915" alt="Screenshot 2024-03-08 at 2 46 23 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/161855694/bfcb0598-6be8-4537-963a-61275ae1c396">

**Comment by danielcaus** [comment]
Hello. I noticed that today (11/03/2024) the error inside the Action no longer appears, but persists outside it, as shown in the images below:
![2024-03-11_11h05_43](https://github.com/FlutterFlow/flutterflow-issues/assets/147090484/2ae18483-774d-4a7a-8fcc-4f078ad1fc5e)
![2024-03-11_11h06_14](https://github.com/FlutterFlow/flutterflow-issues/assets/147090484/d94f620d-fb9d-4dad-9ed3-fbf54f70b632)

**Comment by zerowhybr** [comment]
> Hello. I noticed that today (11/03/2024) the error inside the Action no longer appears, but persists outside it, as shown in the images below: ![2024-03-11_11h05_43](https://private-user-images.githubusercontent.com/147090484/311732552-2ae18483-774d-4a7a-8fcc-4f078ad1fc5e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjY5MTEsIm5iZiI6MTcxMDE2NjYxMSwicGF0aCI6Ii8xNDcwOTA0ODQvMzExNzMyNTUyLTJhZTE4NDgzLTc3NGQtNGE3YS04ZmNjLTRmMDc4YWQxZmM1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxNDE2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTRhMzNkMDg1ZDUwMGI0ODJkYjY0ODQ3NTA4N2JlNGQ3MWEwZjYwZjA5NDVmN2MxMDE0N2VhNWI5YWY5OWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WqF52R8SE6EDG3hZeVG-3M-bAdFAzD6jX1RuyNQDeSc) ![2024-03-11_11h06_14](https://private-user-images.githubusercontent.com/147090484/311732571-d94f620d-fb9d-4dad-9ed3-fbf54f70b632.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjY5MTEsIm5iZiI6MTcxMDE2NjYxMSwicGF0aCI6Ii8xNDcwOTA0ODQvMzExNzMyNTcxLWQ5NGY2MjBkLWZiOWQtNGRhZC05ZWQzLWZiZjU0ZjcwYjYzMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxNDE2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODMyNjc5ZWFiN2M4OGZhMWZiMGRiZDJmNWZhYmIzM2IzZjAzMTJjYjU4M2Q3ZTE0MTI3NTQ1NWM5N2RmY2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fYs70hgvlqGIBFC8zrqekj7ZOYAGL2w6gOSNKDQHIcc)

This is happening to me as well

**Comment by michelraggio** [comment]
Hi, I have the same problem.
Adding the action in Action Flow Editor. Action on Sort Changed: "Update Page State". Set value to custom sorting function and 3 arguments:
- page state
- index = Data Table Sorted Column Index
- ascending = Data Table Is Ascending.

In Action Flow Editor there is no error.
In Property Panel it shows an **error on "Sorted Column Index" and "Is Ascending"** saying "Variable not properly set".

The page shows a bug that says:
> **App State Update Action**
> _Field "" has an update value that is not properly set in Update App State action for PaginatedDataTable_


Pages that were working fine now are not working. I have uploaded 2 screenshots for reference here:

<img width="1440" alt="Screenshot 2024-03-11 at 20 10 50" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6590764/c23f819c-e4fd-475e-b37a-0f3ec1866f4b">
<img width="619" alt="Screenshot 2024-03-11 at 20 09 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6590764/f3d4aae1-8850-4795-aa8b-1ceacdf57358">

**Comment by carlalutzdias** [comment]
Hi. I'm having the same problem when trying to use the row index variable, but not in the sorting action. In my case, I'm updating a page state so I can use it's value later to make an API call.
![flutterflow_paginacao_issue](https://github.com/FlutterFlow/flutterflow-issues/assets/47217351/43cc816e-6855-4e08-ba90-a896b2a3c599)

**Comment by carlalutzdias** [comment]
Hi, I'm having a similar issue, but not in the sorting action. In my scenario, I try to use the rowIndex variable to update a page state, so I can make an API call later. No errors appearing while setting the variable, but the error appears on the project. This was functioning perfectly until a few days ago.
![flutterflow_paginacao_issue](https://github.com/FlutterFlow/flutterflow-issues/assets/47217351/f721cdff-ca12-44e3-8950-53bfe253bc55)
![flutterflow_paginacao_issue2](https://github.com/FlutterFlow/flutterflow-issues/assets/47217351/328ec7b2-5441-4884-b06c-0d784e0af5c3)

**Comment by PortView** [comment]
This is happening to me as well in 20/03/2024

**Comment by rzambroni** [comment]
hi everyone! Sorry about the delay on this. 

I was able to reproduce the issue you are describing on a blank project. 
Will send this over to the team so they can take a look.  As soon as we have news, we will update the status here.

Thanks for your report!
