### ISSUE TITLE
My login Action dont work for Android

### ISSUE THREAD

**Issue by estccerv** [FlutterFlow/flutterflow-issues#2473]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i have a login action but now dont worl correctly

### Expected Behavior

i need a usefull login action

### Steps to Reproduce

touch buton with auth action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

dont have a one

### Context

i create a onboard logic but dont work in android but in web well done

### Visual documentation

the page only reload

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform: Android
- Operating system and version affected: all Android
```

**Comment by hariprasadms** [comment]
Hey @estccerv - You should refer to this [document](https://docs.flutterflow.io/data-and-backend/firebase/authentication/initial-setup) and follow the steps outlined in the "Generate the SHA-1 key" section. This is not a bug; the SHA-1 key section should be added before building the APK.
