### ISSUE TITLE
Backspace stops working after a while

### ISSUE THREAD

**Issue by ebrammer** [FlutterFlow/flutterflow-issues#2474]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the update backspace and my left/right arrows on my keyboard stop working after a while. They work for the first few minutes but once I make any changes to my project, they stop working. This is only happening within Flutterflow and if I reload the project - it goes back to working for a few minutes.

### Expected Behavior

Backspace and left/right arrows to work.

### Steps to Reproduce

1. Make any changes to a project and it then backspace stops working.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whc/135d2sddY187pbcZFiiUXCDo2R4Enk+4aQis8JJToPLAUZ8zBM05vZrzhdFVEIlmjmnsd/PfqvvL+GPUoPTWcRrpdypd2ETrwIV+jbJipDpedfW1QBexRCB3F4auJrxQmBNJYV1ph1HGQHd++bDbYCbrjOW4ZOv2LKdeK2SrDX1iXc2URm05KZDPz

### Context

Normal work.

### Visual documentation

None.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.30
- Platform: MacoS Desktop
- Browser name and version: Chrome
- Operating system and version affected: Mac OS 12.7.3
```

**Comment by jigneshdarji91** [comment]
I'm facing the same issue. 

**Workaround**: Select the text with mouse and re-write.

**Comment by rpock** [comment]
I would also like to point out that the arrow keys on the keyboard will no longer work when this issue occurs.

**Comment by rpock** [comment]
Same issue here.

**Comment by jmvl** [comment]
same here backspace and cursor keys not working

**Comment by tmpsantos** [comment]
@jmvl @rpock @jigneshdarji91 @ebrammer This has happened to me too and I'm trying to establish a pattern to see what we all have in common (and help FF engineering team).

- I'm using a macbook
- External keyboard with US International layout
- Restarting the app "fixes" it consistently

**Comment by byrondowns** [comment]
same here, still issue on mac with latest version

FlutterFlow v5.0.6 released October 13, 2024
Flutter version is 3.22.2

**Comment by hamreen** [comment]
Iam facing this issue now.

After sometimes, backspace,tab and some other buttons stops working. they start working after restarting the app.
