### ISSUE TITLE
Set form field incorrectly displays list of available nested form fields

### ISSUE THREAD

**Issue by alfredogranda** [FlutterFlow/flutterflow-issues#2475]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to use the action "Set form field" on fields that are inside other components, not every available field is displayed. Instead the same form field is repeated multiple times which prevents usage of the other available form fields.

### Expected Behavior

The list displayed in "Set form field" should contain all of the available form fields and not a single one repeated many times.

### Steps to Reproduce

1. Create a component called `DemoComponent` and add a `TextField` inside of it.
2. Create a component called 'DemoContainer`and add 2 instances of the`DemoComponent`and name them`AAA`and`BBB\\\\\\\\\\\\\\\` respectively.
3. Add a Button to the `DemoContainer` and add a `OnTap` action to it.
4. In the `OnTap` action set `Set form field`. The list shows `BBB.TextField_1` twice instead of displaying one for `AAA` and the other one for `BBB`.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i8rqx4VNobRF+Kr2b8FsnikXQ307argrkMFEEUg8J5DaPOxzP/TBaldWUs+0Snw/fGCGhnk0zN3emvGWEPcrAxCWfIhR/pYIVQKWfFq5MZSuO8+SW25/De1Tf1CE1MCjux5DHPRaWiEH1FOIAvKvYAPfQbKyDTJANP+KKZOK2SrDX1iXc2URm05KZDPz

### Context

Not able to reuse a component with a TextField multiple times.

### Visual documentation

![Screenshot 2024-03-08 at 7 10 57 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1a896128-fa86-498d-b022-56d8322eb976/96c5b718-86b9-4db8-8188-bb530ca84cba?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYTg5NjEyOC1mYTg2LTQ5OGQtYjAyMi01NmQ4MzIyZWI5NzYvOTZjNWI3MTgtODZiOS00ZGI4LTgxODgtYmI1MzBjYTg0Y2JhIiwiaWF0IjoxNzEwMTU1NTA1LCJleHAiOjMzMjgwNzE1NTA1fQ.cMDtlErQNwKs46o4IULYlUNBAl4zq57Abkzlptz38RQ "=970x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.30
- Platform: OSX 14.3.1
- Browser name and version: Flutter flow macOS app
- Operating system and version affected: OSX 14.3.1
```

**Comment by takashiff** [comment]
Hi @alfredogranda, this looks to be a duplicate issue with #1786. Please refer to the other issue for further updates. Thanks
