### ISSUE TITLE
Fail to Push Mobile App to App Store

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#2476]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to publish the app to the apple store, it fails Since last Flutter version update.

### Expected Behavior

Publish without errors

### Steps to Reproduce

1. Publish to the Apple Store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMfWOdEket+EA0hfZDtBLATdczCbVVLYtfmS31DPmH+sEkfwvDpkd/1F+04YU+BUaZTzL5XQQ3jVlGhRcmpELqeW3ZBBeFmJ0yi0cHYnRFCNbBidEYk2mGuffCdG3qCf9qOYwx5e6fDbOY=

### Context

Error:

\\\\\\\`Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Found build number 139 from TestFlight version 1.1.46

Archiving com.flutterflow.streeto...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: U5425C86GD
Running pod install... 14.1s
Running Xcode build...
Xcode archive done. 75.1s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'OIDTokenRequest' declares the selector 'initWithConfiguration:grantType:authorizationCode:redirectURL:clientID:clientSecret:scope:refreshToken:codeVerifier:additionalParameters:'
/Users/builder/clone/ios/Pods/GTMAppAuth/GTMAppAuth/Sources/GTMOAuth2KeychainCompatibility.m:136:31

Encountered error while archiving for device.

Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1\\\\\\\`

### Visual documentation

![Captura de pantalla 2024-03-08 a la(s) 21 25 50](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/685ce08b-7f70-4405-9920-96b4f2f856c5/6777610a-796e-4ccc-8712-e5105fa9bec2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ODVjZTA4Yi03ZjcwLTQ0MDUtOTkyMC05NmI0ZjJmODU2YzUvNjc3NzYxMGEtNzk2ZS00Y2NjLTg3MTItZTUxMDVmYTliZWMyIiwiaWF0IjoxNzEwMTU1NjIwLCJleHAiOjMzMjgwNzE1NjIwfQ.kRzt-7MncPrGMJ635FjOiVqrKZx4w_EFXf_ak3m4KBI "=1206x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by damianfraire** [comment]
I'm getting the same issue, can't deploy to google play or play store.

**Comment by andresacero-brokerfy** [comment]
Also getting the same issue
<img width="1512" alt="Captura de pantalla 2024-03-09 a la(s) 9 47 29 a m" src="https://github.com/FlutterFlow/flutterflow-issues/assets/148167109/12367069-bf69-48bb-ba00-8de5bdb06167">

**Comment by michielpr** [comment]
Yups. Same situation here. 

This is the error that I'm getting as well: 
```
ARC Semantic Issue (Xcode): No visible @interface for 'OIDTokenRequest' declares the selector
'initWithConfiguration:grantType:authorizationCode:redirectURL:clientID:clientSecret:scope:refreshToken:codeVerifier:additionalParameters:'
```

There is a thread in the flutter repo also talking about this: [](https://github.com/flutter/flutter/issues/144860 )
_Not entirely sure on how to fix it tho._

**Comment by michielpr** [comment]
Oh amazing! :-) Which build number did you use?

**Comment by pstatile** [comment]
The next one. You have two numbers, one is your version and the other is the Build number. That one is consecutive on every push to the Apple Store. The first time ever you had to put 1. And then if you leave it blank it will take the next one. Try to use the next one due, and then it will start to work again and the following build you can start omitting the build again and it will take the following number. ThanksPablo El 10 mar. 2024, a la(s) 20:17, Michiel ***@***.***> escribió:﻿
Oh amazing! :-) Which build number did you use?

**Comment by andresacero-brokerfy** [comment]
Thanks @pstatile that fixed it for me :))

**Comment by michielpr** [comment]
Thanks all! This is promising! 😊

 Where do you set this actually?

**Comment by andresacero-brokerfy** [comment]
<img width="534" alt="Captura de pantalla 2024-03-11 a la(s) 12 22 22 a m" src="https://github.com/FlutterFlow/flutterflow-issues/assets/148167109/cce3ad48-9f42-415c-a13d-68b3ead42385">

In mobile deployment and then build number at the top ;)

**Comment by michielpr** [comment]
Oh snap! Of course! haha. Thank you! Will try some things ;)

**Comment by takashiff** [comment]
Hi all, it looks like this issue has been resolved, so I will go ahead and mark it as closed accordingly. If the issue persists, please feel free to follow up in this thread so that it can be reopened. Thanks
