### ISSUE TITLE
Switch Widget Nolonger following color selections

### ISSUE THREAD

**Issue by xenomorph78** [FlutterFlow/flutterflow-issues#2481]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Switch Widget no longer follows the colors assigned.

### Expected Behavior

Switches that have been in place and assigned an active color, no longer display in test or on device in that color. It appears to follow 'Inactive Thumb Color' instead. Additionally, Active Color is no longer applied anywhere in the switch. There is also no way to control 'Active Thumb Color' as it seems to default to white.

### Steps to Reproduce

1. Create a new page
2. Add a switch widget
3. Assign 'Active Color'
4. Run App
5. Notice Active color does not have any effect.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhfHlzItOodtc0L6IKvp4imQ7KUMcTZM3lOsYGQIdIr6oO4oXOszuaXdCO9+ESgtcOE2ZsD41w6iLv/LXMcdcPSmsf49607tpFhXLXk6hMKaKDam8VGslI+RTN2a40JmsnhF/IbFZSXAT7F+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Yes, it affects the visual consistencies of my app.

### Visual documentation

![Screenshot 2024-03-09 at 5 19 32 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f4e83d36-96d5-4f34-8a76-bf43047c9e13/9d336a23-d143-433e-b314-628df712afaa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNGU4M2QzNi05NmQ1LTRmMzQtOGE3Ni1iZjQzMDQ3YzllMTMvOWQzMzZhMjMtZDE0My00MzNlLWIzMTQtNjI4ZGY3MTJhZmFhIiwiaWF0IjoxNzEwMTgzODgzLCJleHAiOjMzMjgwNzQzODgzfQ._6HfWh1QbBj95T0zEthlGT73QKdjfCVyz184MauyLAo)

![Screenshot 2024-03-09 at 5 17 10 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e33b5753-13d9-4567-8a45-f80f0e08c422/15e71dcd-1407-429f-83f4-7be06f347060?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMzNiNTc1My0xM2Q5LTQ1NjctOGE0NS1mODBmMGUwOGM0MjIvMTVlNzFkY2QtMTQwNy00MjlmLTgzZjQtN2JlMDZmMzQ3MDYwIiwiaWF0IjoxNzEwMTgzODgzLCJleHAiOjMzMjgwNzQzODgzfQ.Vp0o-ekvnyaBC_nqualaB0nNVE6UIwE6QdgoRgmGoR4)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.30
- Platform: MacOS
- Browser name and version: Chrome
- Operating system and version affected: Sonoma 14.4 (23E214)
```

**Comment by Torkilws** [comment]
Same issue with the toggle widget

**Comment by ready4sea** [comment]
Same issue here

**Comment by rzambroni** [comment]
Hi, @xenomorph78, thanks for the report. We were able to replicate this issue and was sent to the team to be fixed. We'll let you know when it is fixed.

**Comment by rzambroni** [comment]
Hey @xenomorph78, 

There is a feature in FF that will allow you to get the desired `active_color` behavior by changing the platform type for the switch (Click on the switch in FF, go to the properties tab, expand "Platform" (collapsed by default) and set Platform Type to Android). However, this does also change the style of the switch to look more like Android .A new property to overwrite the color of the thumb while retaining the Adaptive style is not currently supported and would be a new feature. <br><br>FlutterFlow switch widgets are currently "adaptive" widgets, meaning that their style depends on the platform. The Flutter team has defined the functionality for what the field `active_color` should do on switches to be in line with expectations users have on specific platforms (for example, on iOS, switch thumbs by convention do not change color when the switch is turned on, only the background behind the thumb changes colors).

Hope that heps!
