### ISSUE TITLE
Supabase OtpType undefined when access on custom actions

### ISSUE THREAD

**Issue by AmbotSaImoDude** [FlutterFlow/flutterflow-issues#2482]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow doesn't identify OtpType enums imported from supabase.dart.

Note: Using OtpType enum works and was able to verify the code but the problem is flutterflow gives error on OtpType enum during complilation. I just tried to exclude it from compilation to allow my code to continue.

### Expected Behavior

Flutterflow should be able to identify OtpType enums from supabase.dart as it is imported by default in custom actions.

### Steps to Reproduce

1. Create a project
2. Enable Supabase
3. Create custom code
4. Create a custom action
5. Create an otp verfication process with supabase
6. Use OtpType enum
7. Try to compile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfjMmA6otPxLhG7ZSJb8ExqCQQKWUcTYAnlOxEEB4bfbHpEOwLd+P8X0NKQvW8YwhqAEyIjjgD/tGNuPz1EfI5ORKVR7pA0JVAFwuUUlyjR5fWEbuCSHN8GcdRG2aY5J+nkAlAVfpfdFIH6mCHNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to perform an OTP verification with supabase through verification code emailed to the user.

### Visual documentation

![Screenshot 2024-03-09 200622](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/936a0362-86f0-4978-8a6f-c1d7b7751301/82e6c65b-e527-4a08-a1da-037e6a16c384?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MzZhMDM2Mi04NmYwLTQ5NzgtOGE2Zi1jMWQ3Yjc3NTEzMDEvODJlNmM2NWItZTUyNy00YTA4LWExZGEtMDM3ZTZhMTZjMzg0IiwiaWF0IjoxNzEyNzgwNzIyLCJleHAiOjMzMjgzMzQwNzIyfQ.U6zYhtIzDuZutfa_IUdSG2KN9vL1SmfuOJMslihfPuU)

![Screenshot 2024-03-09 200649](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/59bbdce4-2578-4add-ba11-73409523b8bd/4e3c6272-bc02-4aac-8397-51f8d710855b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81OWJiZGNlNC0yNTc4LTRhZGQtYmExMS03MzQwOTUyM2I4YmQvNGUzYzYyNzItYmMwMi00YWFjLTgzOTctNTFmOGQ3MTA4NTViIiwiaWF0IjoxNzEyNzgwNzIyLCJleHAiOjMzMjgzMzQwNzIyfQ.zoSviTYNJJdPfSk2pa07LkEJTA6Eibu5U5NvfKn68F8)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Android & iOS
- Browser name and version: Chrome Version 122.0.6261.112
- Operating system and version affected: Windows 11 version 22H2 x64
```

**Comment by paulperez-dev** [comment]
Hi @AmbotSalmoDude! Thanks for your report and sorry about the delay in the response, we are trying to get up to speed with everything.

We recently released a new version, can you please let me know if the issue persists? If so, please share the bug report code again from a blank project with the minimal code to reproduce it.

**Comment by leighajarett** [comment]
Closing this issue since we have not heard back
