### ISSUE TITLE
Undo/Redo not working in code editor on desktop

### ISSUE THREAD

**Issue by rimb05** [FlutterFlow/flutterflow-issues#2484]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Undo / Redo works fine on the Chrome version, but not on the desktop version.

### Expected Behavior

I expect it to work with standard key commands: Command Z and Shift command Z

### Steps to Reproduce

1. Create a new project
2. Create a new custom widget
3. Type something
4. Try to undo

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

Trying to undo

### Visual documentation

Simple to reproduce

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.32
- Platform:Mac
- Browser name and version: none
- Operating system and version affected: M2 Max / Ventura
```

**Comment by takashiff** [comment]
Hi @rimb05, thanks for your bug report! Unfortunately, our custom code editor on the Desktop app is limited compared to the web version. I am going to mark this closed, as this is more in the vein of a feature request, but we are currently working on several custom code improvements to enhance users' experiences. Thanks!

**Comment by rimb05** [comment]
The trouble is the web version doesn't support device debugging. So developers are left with having to switch back and forth between desktop and web if they want to write code. Not a great usage pattern.

**Comment by takashiff** [comment]
Hi @rimb05, I completely agree with your perspective. I can go ahead and add this as a request internally as a part of our improvements to the custom code editor.

**Comment by rimb05** [comment]
ANy progress on this?  It's really frustrating not being able to undo and redo when working with code.
