### ISSUE TITLE
Save as Template not working

### ISSUE THREAD

**Issue by bamboat3** [FlutterFlow/flutterflow-issues#2489]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the user chooses the component to save as a template, the saving box doesn't let the user insert the name of the template, and without it, it is not possible to save the component as a template.
[ice_video_20240310-175250.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/11148244/91001a03-6f1f-47e1-93c9-1167b13afe3e)

### Expected Behavior

It is supposed to save the component as a template

### Steps to Reproduce

1. Right-click on the component from the component tree
2. select Save as Template option
3. Try to enter the name of the template

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThefl7ot1xdRK+Kn5YcF4nWU7I0MAXOYvitYbVR43JZOqPLQUZuLRYUNKTMujT3xiH1eZpDk1/+z7joXLNPU6CxeYfaJc0JVPExbKbFinaLqNEajhXHN7PNFVIWqM1rukkxB+NvpeSiUe1zihNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to accomplish that I would like to save the component as template and use it on the next pages

### Visual documentation

video attached
[ice_video_20240310-175250.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/11148244/094d154f-db76-40be-ac96-1e15c9d2adc7)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Windows 11
- Browser name and version: Chrome v. 122.0.6261.112
- Operating system and version affected: Windows 11
```

**Comment by takashiff** [comment]
Hi @bamboat3, this looks to be a duplicate issue with #2387. Please refer to the following issue for updates. Thanks
