### ISSUE TITLE
Inaccessible properties from record's DataType list data coming from query

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#249]
When attempting to access DataType list data as part of a query, the properties are inaccessible and so is the datatype object itself. For example tried to access the string properties of the data type in a text widget, and also pass this and the whole property to a component that takes this exact datatype as a parameter. All is red. See screenshots.

As a result I'm unable to access part of my collection data. Using Flutterflow 1.1.25. Also tried again in 1.1.26

![Screenshot 2022-12-20 at 16 51 18](https://user-images.githubusercontent.com/72607/208733561-376d7596-27fd-49aa-919e-0db990a35a91.png)
![Screenshot 2022-12-20 at 16 50 39](https://user-images.githubusercontent.com/72607/208733648-78ca9dbb-025e-4162-872a-2b389acc4d78.png)
![Screenshot 2022-12-20 at 16 50 26](https://user-images.githubusercontent.com/72607/208733665-496435a5-da5e-40ed-add6-7f6cc1a1a443.png)

**Comment by bulgariamitko** [comment]
Can you test this with a brand new project as well to confirm the same behavior?

**Comment by davhad** [comment]
@bulgariamitko this issue doesn't appear anymore either on the original project or on another test project. Maybe was fixed in 1.1.28.

**Comment by bulgariamitko** [comment]
Yes it was fixed.
