### ISSUE TITLE
Walkthroughs returning Null Target Position

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#2490]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have tested the walkthroughs in detail and attached a video and they are returning null target position value

### Expected Behavior

Initial walkthroughs and previewed in demo

### Steps to Reproduce

1. Create Walkthrough
2. onPageLoad -> Start Walkthrough

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjPHlz4ZOm+FF7oSJc8dahmIvIjt5a+dF1+tEVis8GZT0B4kcYs+kfklUOO27Sm9tMGGjgnEX/MrHvd/fVMcENRGVfoBB/6l6agzjUli6Mb6yDIS3b39SM5hgIFSv5Ka33wp5IvJfSXg5wGGIJeSXaBHqJ5j6NTEZAeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

.

### Visual documentation

![Screenshot 2024-03-10 at 9 59 21 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/eec59aa4-ca92-4db7-8313-1f4dcaa886ca/e1e3418b-f721-4636-96ef-5af46587a29e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZWM1OWFhNC1jYTkyLTRkYjctODMxMy0xZjRkY2FhODg2Y2EvZTFlMzQxOGItZjcyMS00NjM2LTk2ZWYtNWFmNDY1ODdhMjllIiwiaWF0IjoxNzEwMDk3NjY4LCJleHAiOjMzMjgwNjU3NjY4fQ.\_bl6YMfC1fQfJTFB2oepDwDoFK7oi0uqPsFbo_pWsHA "=864x")

[https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/c39ae2b8-e995-4800-8b24-58c8cd1e2ecf](https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/c39ae2b8-e995-4800-8b24-58c8cd1e2ecf)

### Additional Info

..

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web, MacOS
- Browser name and version: Web,MacOS
- Operating system and version affected: Sonoma
```

**Comment by shefa** [comment]
# Please look into this ASAP - I don't think anyone is able to use the walkthrough feature at the moment.

I get the same error, whatever I try to make walkthrough appear - even if the walkthrough is just 1 step, on a static, non-loading page. I've tried many variants, without any success to get a simple walkthrough working:

- Invoking StartWalkthrough action on PageLoad (with no other actions)
- Invoking StartWalkthrough action on a Button press (see video)
- Invoking StartWalkthrough in a loop with 3 second wait inbetween loop iterations, as I thought maybe for some reason the page elements are not initiated when the walkthrough is called, but nope - the same error.

Here's a video demonstrating this issue, starting from a blank project, as well as running into issue #2512 in the process:

https://github.com/FlutterFlow/flutterflow-issues/assets/8330340/d4c90909-6413-49ea-93e3-160aa055cecd

**Comment by shefa** [comment]
> What version is your flutterflow I think you have to update the version I have the same problem but how do I update the version

```
FlutterFlow v4.1 released March 9, 2024
Flutter version is 3.19.1
Google Chrome Version 122.0.6261.129 (Official Build) (64-bit)
```

Running latest flutterflow, latest google chrome, in incognito mode, so nothing is cached.

**Comment by emanuelmarlon** [comment]
A MINHA VERSÃO TAMBEM É ESSA JA TEM UMA SEMANA OU MAIS QUE ESTOU COM ESSE PROBLEMA SEGUNDO UM USUARIO O FLUTTERFLOW JATA NA VERSÃO 4.1.32 ACREDITO QUE POSSA SER UMA SOLUÇÃO PARA NOSSO CASO MAS COMO ATUALIZAR A VERSÃO?

**Comment by emanuelmarlon** [comment]
Thank you, I called the flutterflow chat and they are already using my case 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/119950869/201ef5ef-443e-49a3-bae3-5e390f0f171a)

**Comment by marcosaimola** [comment]
I was looking forward to this feature, but it's frustrating to know that it was launched without even a basic unit test since nobody can use it yet.

**Comment by grivdm** [comment]
Agree, I have the same problem. Completely useless.

**Comment by shefa** [comment]
@sbis04 I see you've marked the bug as fixed, when can we expect the fix to be in production? What was the issue?

**Comment by sbis04** [comment]
Sorry for the late reply, the fix is in production now! There was a code generation issue on our side which was fixed last week, and currently it's possible to use only one walkthrough per page (if there are more than one, that should show up as a project error now).
