### ISSUE TITLE
Google Maps Widget Causes: Undefined symbols. Linker command failed with exit code 1 - Second ticket from nov 2023

### ISSUE THREAD

**Issue by JustUserHere** [FlutterFlow/flutterflow-issues#2494]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey folks!
I'm waiting to solve this issue since 2nd November 2023. Previous [ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/1765) was closed with comment "Since due to inactivity and considering the age of the issue, I assume that the latest updates from FF have fixed the problem or you've found a solution"

No need to assume - you can ask me directly. Glad that you know that this issue is aged, but for me it is not solved.

The application fails to build after Google Maps widget included to project. Deleting the widget allows the project to build successfully. The project fails to build after the Google Maps widget is in the project. The following error message is displayed: "Linker command failed with exit code 1..."

### Expected Behavior

should work

### Steps to Reproduce

1. add google maps to project
2. try to run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsYt2m+FF7rruYO9WimU4HFAhaq00st4bGAsdGOvrBqQcY8mkQBFDXd+kaVNcDlCWgkg1/sLxudjlMPUrCE6tGog5+bppFw3ee2iuacibPLrpfUd7L5hgCn6iy6u7nhF7JtNsV3Ms1EyYO+/IUi7DFOu/Zwh9f6PHaOI=

### Context

i cant use google maps

### Visual documentation

![Снимок экрана 2024-03-11 в 01 07 35](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4b4735e8-67bb-4945-9b75-5ea4f14e2753/070505ef-0da3-4d58-ad2f-7cb0ee3c9ca7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YjQ3MzVlOC02N2JiLTQ5NDUtOWI3NS01ZWE0ZjE0ZTI3NTMvMDcwNTA1ZWYtMGRhMy00ZDU4LWFkMmYtN2NiMGVlM2M5Y2E3IiwiaWF0IjoxNzEwMjU2OTM2LCJleHAiOjMzMjgwODE2OTM2fQ.fXuah3-v07TCFtMESlQ5TXyWrFTcm3R9jNvOHBPZWeY "=564x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: mac
- Browser name and version: mac app
- Operating system and version affected: mac
```

**Comment by hariprasadms** [comment]
Hi @JustUserHere - Thank for re submitting the issue. I have verified the steps you mentioned above. I project can build when map widget is placed, in all modes, web, run, android emulator and test debug mode. However, i noticed the exact same error are facing while running iOS simulator locally.  Is this the same in your case ? please confirm.

**Comment by hariprasadms** [comment]
I can also confirm that the build works fine on iOS real devices (iPhone 11 and 13) running the latest OS. However, it specifically failed on the iPhone 15 simulator. The failure seems to be more specific to the iPhone simulator. I'll mark this issue for technical review to finalize the status. If you have any additional details to add, please do so. Thank you.

**Comment by JustUserHere** [comment]
@hariprasadms 
on emulator iphone SE (3rd generation) it is fails to run too, same as on others
I tested it on real device - it is starting, but google maps widget works with bug, for example zoom is not woeking

**Comment by JustUserHere** [comment]
@hariprasadms @takashiff 
Do not close this ticket again. I'm waiting since October

**Comment by victoriahuang1** [comment]
@JustUserHere @hariprasadms I am not able to repro the issue on either iphone SE (3rd generation) or iphone 15.

Please let me know if you are able to reproduce from blank. If so, please share the project with me. Otherwise this would be a project specific issue.

<img width="545" alt="Screenshot 2024-03-20 at 11 07 40 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/a37401b9-3fb7-436c-a6b2-3036e27774fd">
<img width="568" alt="Screenshot 2024-03-20 at 11 09 41 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/e375e3ab-b2d9-470b-9926-dadfe0ff3707">

**Comment by takashiff** [comment]
@victoriahuang1 I was able to reproduce it with this project https://app.flutterflow.io/project/language-translate-g258o6?tab=uiBuilder&page=HomePage

**Comment by JustUserHere** [comment]
@victoriahuang1 @takashiff 
Dears,
I don't know what is the difference between project specific or just a bug in FF - in my eyes it is the same, since it is resulting to same - Google maps not working in simulator but works well on real device.

Please, help me to resolve the issue, I'm waiting for 5 months.

**Comment by takashiff** [comment]
Hi @JustUserHere, I apologize for the delay in getting this issue resolved. After some testing, it looks like this is actually an [issue](https://github.com/flutter/flutter/issues/94491) with the Google Maps widget in Flutter. As a current workaround (until the Google Maps widget is updated), applications that use Google Maps can only be ran on a Rosetta simulator, and not an ARM simulator (which most likely explains why @victoriahuang1 was unable to reproduce the issue). Please let me know if this solves the issue for you. Thank you for your patience and continued support.

**Comment by JustUserHere** [comment]
> Hi @JustUserHere, I apologize for the delay in getting this issue resolved. After some testing, it looks like this is actually an [issue](https://github.com/flutter/flutter/issues/94491) with the Google Maps widget in Flutter. As a current workaround (until the Google Maps widget is updated), applications that use Google Maps can only be ran on a Rosetta simulator, and not an ARM simulator (which most likely explains why @victoriahuang1 was unable to reproduce the issue). Please let me know if this solves the issue for you. Thank you for your patience and continued support.


Hello. I have m1 MacBook, how can I run Rosetta simulator? I don't catch how I can solve the issue?
Are you going to fix it on next update?

**Comment by Nick-Zhang1996** [comment]
When you build in Xcode, you can select "build for Rosetta" so that you are building with the legacy X86_64 ios simulator instead of the arm64 version that's native to your M1 mac. You can check relevant issue https://github.com/flutter/flutter/issues/94491.

**Comment by takashiff** [comment]
Hi there! As @Nick-Zhang1996 has pointed out above, you can configure this within your XCode project settings. I hope this resolves your issue. Thanks!

**Comment by lleo132** [comment]
I have the same problem, however, this error occurs after adding the Google Maps widget and trying to start deploying it to the Apple Store
