### ISSUE TITLE
Disabling an action causes error stemming from actions downstream

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#2495]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I select an action in a chain to "disabled" i get errors that the subsequent actions no longer have access to an Output Variable -- even if that Output Variable is defined *after* the disabled action.

### Expected Behavior

I expect the Chain of Actions to still work downstream from a disabled action as long as there is no dependency, specifically, where that action creates an Output Variable that must be used by downstream actions.

![Zight 2024-03-10 at 5 02 42 PM jpg](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/994def78-168e-427f-9e93-ed19d6a2e680)

### Steps to Reproduce

1. Create a chain of actions
2. The last actions use an Output Variable
3. Disable an action **before** the creation of the Output Variable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhcmBy5BNochE0IfqduxKiSgwGUwbUOc7j9VEGAsjCeP3EIouPuP7VxBVWOqHdwliEFeGjjsC0trziePfKscDMkibY6E/ys19UxDhcEi6VaaLDZaKfGtBGfhYfVCh4Z+Jnx5DOrFhZUJk1DuEI+6ua3qCf9qOYwx5e6fDbOY=

### Context

I am seeing issues where not all actions in the action chain are not executing, and it's difficult to troubleshoot these.  So I put lots of "show snack bars" to check state and want to subsequently remove those to clean up the experience.

### Visual documentation

https://zight.fong888.com/7Kunn91m

![Zight 2024-03-10 at 5 02 42 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/3c34ae0d-bea5-4ec6-bb8e-9bad770e9ae1)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: MacOS Web
- Browser name and version: Brave is up to date
Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (arm64)

- Operating system and version affected: MacOS Sonoma 14.4
- ProjectID: sophia-w4h8q1
```

**Comment by hariprasadms** [comment]
Hi @timfong888 - The project code provided above lacks details on where to locate the issue. Please either create a blank project with the issue replicated in it, or update the issue details to specify where to find the setup in the given project.
