### ISSUE TITLE
Unable to Install plaid_flutter Package for Custom Widgets

### ISSUE THREAD

**Issue by vedantatech** [FlutterFlow/flutterflow-issues#2496]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Encountered an issue installing the plaid_flutter package for use with custom widgets. Despite following the standard package installation instructions, the package does not seem to integrate properly, resulting in build failures and preventing further development.

### Expected Behavior

Plaid link is generated and user is able to connect their bank accounts

### Steps to Reproduce

1. Create custom widget
2. Add depedencies
3. Add custom widget example code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Unable to build the app on flutterflow platform

### Visual documentation

NA

### Additional Info

NA

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Chrome
- Browser name and version:Chrome
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @vedantatech - Thank you for submitting the issue. Could you please provide the project bug report code to gain access to your project? Additionally, I attempted to use the package you mentioned in my project. Interestingly, it worked in one project but not in another. It appears to be project-specific or inconsistent. Share your project details I will have another look and decide the status. Thanks

**Comment by vedantatech** [comment]
We were able to resolve it by adding a script under custom header
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
