### ISSUE TITLE
Bug - Automated testing

### ISSUE THREAD

**Issue by ShubhamHande99** [FlutterFlow/flutterflow-issues#2497]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an application in which I'm using custom authentication (login) that utilizes persistent data and SQL CRUD operations. Both of these functionalities work as expected.

To explore the automated testing feature provided by FlutterFlow, I have written tests for login and SQL CRUD operations. However, when I export the code and try to run the tests, they fail.

**Here are the reasons for the failing tests:**

1. It does not add necessary initialization code:
   * I'm getting a "LateInitializationError: Field '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_prefs@1287424658' has not been initialized" error while running the automated test for login.
   * Also, a "LateInitializationError: Field '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_database@1286352526' has not been initialized" error occurs while running the automated test for the SQL CRUD functionality.
2. When I group the tests from the FlutterFlow platform and export the code
   * it adds async to the group tests, which results in: Invalid argument(s): Groups may not be async.

**Here is the login test auto generated code by FlutterFlow -**

```
  void main() async {
IntegrationTestWidgetsFlutterBinding.ensureInitialized();


group('Auth', () async {
  group('Login', () async {
    testWidgets('Login success', (WidgetTester tester) async {
      _overrideOnError();


      await authManager.signOut();
      await FFLocalizations.initialize();
      FFAppState.reset();
      final appState = FFAppState();
      await appState.initializePersistedState();


      await tester.pumpWidget(ChangeNotifierProvider(
        create: (context) => appState,
        child: MyApp(
          entryPage: LoginWidget(),
        ),
      ));


      await tester.pumpAndSettle();
      await tester.enterText(
          find.byKey(ValueKey('emailAddress_a2bh')), 'john@mail.com');
      await tester.enterText(
          find.byKey(ValueKey('password_x4ya')), 'changeme');
      await tester.tap(find.byKey(ValueKey('Button_2opa')));
      await tester.pumpAndSettle();
      expect(find.byKey(ValueKey('Text_pbrl')), findsOneWidget);
    });
  });
});
}
```

As you can see, the code is missing the initialization method for 'authManager' before the `await authManager.signOut();` code, as well as the 'async' keyword for the groups and same for the sql crud test code.

### Expected Behavior

The expected behavior is that after exporting code from FlutterFlow and running automated tests, they should run successfully. We should not encounter any errors because the auto-generated code by FlutterFlow, it should add the required and correct code to run tests.

### Steps to Reproduce

1. Enable custom authentication and add custom authentication functionality with persistent data.
2. Enable SQL and add SQL functionality.
3. Write automated tests using FlutterFlow editor for login and SQL functionality.
4. Download the code.
5. Run the test.dart file from the "integration_test" folder.
6. You will encounter the errors I have mentioned above.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xksn6389IsdtJ+KriasExryQvJkQ5a4JMjuxEbxQ1F5TnEOwud8/+T2xaTdPmSn02MVr9ozsd3NaPk+bIN8IBFzSrRYRg1qh2bDzKfz67VpiUC86JdmpBPNpKCHaYy5+Jhwl4CNp0V1I5wF6yAOqyVhTAQqbwNTEvRsn/OtnNjXPuQ0SLb3kNh1JWeC/v

### Context

The issue has affected to run the tests added using FlutterFlow's automated test feature.

### Visual documentation

No Visual documentation

### Additional Info

No Additional Info

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by aemelyanovff** [comment]
@ShubhamHande99 Thanks for reporting the issue. Could you add a new Bug Report Code? The one in the description does not work. You can create if from any widget in the project, it doesn't matter.

**Comment by ShubhamHande99** [comment]
@aemelyanovff I'm unable to generate the new bug report code and am receiving an error. 

An image is attached for reference : 
<img width="617" alt="bug_report_code_ff" src="https://github.com/FlutterFlow/flutterflow-issues/assets/45396085/7253fadc-4f22-4c90-9166-813ff4d73471">

**Comment by aemelyanovff** [comment]
> @aemelyanovff I'm unable to generate the new bug report code and am receiving an error.
> 
> An image is attached for reference : <img alt="bug_report_code_ff" width="617" src="https://private-user-images.githubusercontent.com/45396085/318033767-7253fadc-4f22-4c90-9166-813ff4d73471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTYxNTEsIm5iZiI6MTcxMTcxNTg1MSwicGF0aCI6Ii80NTM5NjA4NS8zMTgwMzM3NjctNzI1M2ZhZGMtNGYyMi00YzkwLTkxNjYtODEzZmY0ZDczNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMWVkOThlYThlMmFkMjMxNjkyMDAxOGM4YjA0NGUwZTYyNjA2MDYzZWI4NmRiMmFlMjBjNDdjMTU3YmEyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.auJZh4txrl7rL9iMXWbGcU2eu2BHngjahYR65zZKzao">

Can you attach a link to the project then? `https://app.flutterflow.io/project/<project id>`.

**Comment by ShubhamHande99** [comment]
@aemelyanovff I tried again, and this time I was able to copy the bug code.

IT5Xksn6389IsdtJ+KriasExryQvJkQ5a4JMjuxEbxQ1F5TnEOwud8/+T2xaTdPmSn02MVr9ozsd3NaPk+bIN8IBFzSrRYRg1qh2bDzKfz67VpiUC86JdmpBPNpKCHaYy5+Jhwl4CNp0V1I5wF6yAOqyVhTAQqbwNTEvRsn/OtnNjXPuQ0SLb3kNh1JWeC/v

Updated in the the Bug report code column as well.

**Comment by aemelyanovff** [comment]
@ShubhamHande99 Thanks for reporting the issue. The fix will be released soon, most likely by the end of the next week.
