### ISSUE TITLE
Missing settings asset

### ISSUE THREAD

**Issue by ShubhamHande99** [FlutterFlow/flutterflow-issues#2498]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In my application i'm using SQL, everything works as expected when run on a device.

However, the issue related to the database asset file in the FlutterFlow platform itself is as follows:

When I create a new branch from the main branch which has all the SQL setup, after some time working on the newer branch, I get the following error:

"Getting Missing settings asset: 'database.db'. Please re-upload or select a different asset, or run the project again to check if the issue persists. Because of this issue, I have to upload the databse asset file again and again.

### Expected Behavior

The expected behavior is that when we create a new branch from the main branch, the newer branch should contain all the assets that the main branch has and should not show the following mentioned error.

### Steps to Reproduce

1. You are working on the main branch.
2. Enable SQL and set up SQL by uploading the database asset file.
3. Create a new branch from the main branch.
4. The new branch will run successfully and will show all the necessary asset files.
5. After working and spending some time on the newer branch close the project entirely and reopen after a few hours, it will start showing the "Missing settings asset" error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grtsC0ZfcLMFAhQIgQ0QnU7gnlO1ucx4dC4OuBLAMZ8jCT0NKTcviS2xYEVaLoF0Kws7ej/DDOPoBE0mdGYhk0JVPERaUcH6jb7mYEcyKWnNCDd9nBX6dy5iNohQlBOx2WkIG32WDNq3qNlse28aSexBlZ7vfcPo=

### Context

The issue has affected me in a way that I have to upload the database asset file again and again.

### Visual documentation

No Visual documentation

### Additional Info

No Additional Info

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @ShubhamHande99 - Thank you for bringing this issue to our attention. Regarding the steps you mentioned, I'm unable to reproduce step 5. After creating a new branch from the main branch and spending 30 minutes working on it, I didn't encounter any issues; everything appears to be functioning properly.

To further investigate the problem you're experiencing, could you please provide a video clip demonstrating exactly when the error occurs? This would greatly assist us in understanding the issue within your project.

Additionally, it seems that the project bug report code provided above is invalid and unable to fetch the project details. Could you please update the code with the correct information? Thank you for your cooperation.

**Comment by ShubhamHande99** [comment]
Hi @hariprasadms, Thank you for addressing the issue. As you mentioned, after spending 30 minutes working on it, I didn't encounter any issues; everything appears to be functioning properly. Please try closing the project entirely and then reopening it after a few hours to check if everything functions properly.

Regarding the bug code i'm unable to generate new code by clicking on any widget, as it's giving a "Failure to copy to clipboard" error, I will check it again and update the bug code here once i get it.

**Comment by MaxAlcance** [comment]
Hello friends, who can help me: After having the entire project and 100% finished, an unexpected error arose: Missing settings asset: "Camion_Cisterna.jpg" Please re-upload or select a different asset, or run the project again to check if the issue persists.
50 image errors that I don't know where they came from, can you tell me how to solve this? Thank you.

**Comment by MaxAlcance** [comment]
![Captura](https://github.com/FlutterFlow/flutterflow-issues/assets/155498599/a92e1bc7-9889-4f81-82b3-b654be7cef22)
