### ISSUE TITLE
Browser/App refresh/crash when edit some pages.

### ISSUE THREAD

**Issue by raldred2** [FlutterFlow/flutterflow-issues#2499]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

From Chrome or the downloaded MacOS desktop app, whenever I click on a page (such as 'groupPage') to edit it, it starts to render the page but then immediately refreshes the entire browse/app window (all goes black). I have to reload and start again.

NB. This works fine and doesn't happen on Safari. But need to use Desktop version for Local Run - which I can't.

### Expected Behavior

Render the page for editing.

### Steps to Reproduce

1. Open OOME FF project
2. Click on `groupPage` to edit
3. FF starts to open/render the page - then goes blac
4. I have to restart the app from beginning
5. \\\\\\\\-- NB. This works fine on Safari --

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Context

I can't use FF in any meaningful way until this is resolved.

### Visual documentation

![Error - Generate Bug Report Code ](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7591a24f-8cf0-4013-ac2c-320c47bf99e3/b1078c08-6fe8-49be-bb1b-56337385cb54?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NTkxYTI0Zi04Y2YwLTQwMTMtYWMyYy0zMjBjNDdiZjk5ZTMvYjEwNzhjMDgtNmZlOC00OWJlLWJiMWItNTYzMzczODVjYjU0IiwiaWF0IjoxNzEwMTQ3MjcxLCJleHAiOjMzMjgwNzA3MjcxfQ.Nu0AT5HfEE8r9TgLDE5vxbbVot7so1IEzLDBLL7u5BU)

[https://github.com/FlutterFlow/flutterflow-issues/assets/73439020/cbf38e94-3b7a-48b6-9f15-e49a58712a9a](https://github.com/FlutterFlow/flutterflow-issues/assets/73439020/cbf38e94-3b7a-48b6-9f15-e49a58712a9a)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 - Flutter 3.19.1
- Platform: MacOS
- Browser name and version: Chrome - Version 122.0.6261.69 (Official Build) (x86_64) + MacOS desktop version
- Operating system and version affected: MacOS
```

**Comment by raldred2** [comment]
I've noticed (and you can see in the video/demo) that briefly 2x red errors appear whilst loading, then disappear.  Not sure if related - but wanted to call out.

**Comment by hariprasadms** [comment]
Hi @raldred2 - Share the project link which is leading to this error please. Thanks

**Comment by raldred2** [comment]
@hariprasadms - here you go...
https://app.flutterflow.io/project/stripe-connect-eqtu9x

**Comment by takashiff** [comment]
Hi @raldred2, this looks to be a duplicate issue to #2450. I will mark this as closed for now, but if your issue is still not resolved, feel free to follow up in this thread so that it can be reopened. Thanks
