### ISSUE TITLE
ListView Infinite scroll error when add client side filter.

### ISSUE THREAD

**Issue by Bonnary** [FlutterFlow/flutterflow-issues#2500]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get this error:

![Screenshot 2024-03-11 164818](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d8966143-9284-4fc4-95bd-860c796888d5/f2cff065-4321-4d02-a980-25a2ef4e6230?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kODk2NjE0My05Mjg0LTRmYzQtOTViZC04NjBjNzk2ODg4ZDUvZjJjZmYwNjUtNDMyMS00ZDAyLWE5ODAtMjVhMmVmNGU2MjMwIiwiaWF0IjoxNzEwMTUxODUwLCJleHAiOjMzMjgwNzExODUwfQ.oOGfoy4cT7j_ucB8qb1ngavC7BiDLDU0Mv3B24S2DdU)

when I add the filter. here how:

[https://github.com/FlutterFlow/flutterflow-issues/assets/69995568/f3694032-27b7-4281-af38-036564de1c12](https://github.com/FlutterFlow/flutterflow-issues/assets/69995568/f3694032-27b7-4281-af38-036564de1c12)

### Expected Behavior

running fine without error.

### Steps to Reproduce

1. Add API query on the listview with infinite scroll turn on
2. Add Filter List Items with Condition if the dropdown name Officer value Is Not Set or Is Empty return true else filter only the list item with dropdown value equal to the ListView Item with JSON path $.byusername.
3. run the project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShcmA25dgod9J+ZDyLO16hQIhNmY1bZMnktVxRR43JYzvOootduDBMkNKQt+UfVBqAVaIpHkf0NrSitmSEMInEziBY7050JVPEgrdXk6mbrbUPs2WPHx6QMFMG0CA16SRriZ5ALBtW1oZ31+XNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I am stock with this bug.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/69995568/f3694032-27b7-4281-af38-036564de1c12](https://github.com/FlutterFlow/flutterflow-issues/assets/69995568/f3694032-27b7-4281-af38-036564de1c12)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released March 9, 2024
- Platform: Web
- Browser name and version: Chrome 122.0.6261.112
- Operating system and version affected: windows 11
```

**Comment by hariprasadms** [comment]
Hi @Bonnary - Thanks for submitting the issue and all the details. I have marked it as bug now. Thanks
