### ISSUE TITLE
FlutterFlow Desktop not available for enterprise account

### ISSUE THREAD

**Issue by zraza** [FlutterFlow/flutterflow-issues#2502]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I downloaded the FF desktop Mac version when I tried to login and open my project, I got an error to open the enterprise app (see the attached screenshot)

![Screenshot 2024-03-11 at 12 18 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5aa70145-c565-45c0-9762-280a820046d9/622cac06-b0fe-44ff-afd9-d95e30ad855e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81YWE3MDE0NS1jNTY1LTQ1YzAtOTc2Mi0yODBhODIwMDQ2ZDkvNjIyY2FjMDYtYjBmZS00NGZmLWFmZDktZDk1ZTMwYWQ4NTVlIiwiaWF0IjoxNzEwMTc5OTIzLCJleHAiOjMzMjgwNzM5OTIzfQ.MK4CZntM6yC2lvLh0HHjkchm-Bu6Fumcd0VSzcTPGow "=1179x")

### Expected Behavior

I should be able to use my enterprise account on FF Desktop app

### Steps to Reproduce

1. Open FF desktop app
2. Login with enterprise account
3. Open/create a project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

DESKTOP_APP_ISSUE

### Context

not able to use local setup with my enterprise account

### Visual documentation

![Screenshot 2024-03-11 at 12 18 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fc4e8d29-b683-4d8e-8be1-f214f9d31086/e2860a59-3844-4c3b-bda6-f2c07afa3d0e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYzRlOGQyOS1iNjgzLTRkOGUtOGJlMS1mMjE0ZjlkMzEwODYvZTI4NjBhNTktMzg0NC00YzNiLWJkYTYtZjJjMDdhZmEzZDBlIiwiaWF0IjoxNzEwMTc5OTIzLCJleHAiOjMzMjgwNzM5OTIzfQ.aCr-CM14n9wVJWZTdmljp804yMRfaj87IGmMZ5tLMEs "=1179x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by takashiff** [comment]
Hi @zraza, is your enterprise account a part of Enterprise India, or just regular Enterprise? Thanks

**Comment by zraza** [comment]
Hi @takashiff - I guess I am using regular Enterprise. It was created for one of your reps for us to play around.

**Comment by takashiff** [comment]
@zraza Thanks for the info! Unfortunately, we currently don't have a Desktop app version for Enterprise, and only have Desktop support for Enterprise India. I apologize for the inconvenience
