### ISSUE TITLE
Flutterflow homepage has AN-AL in the preview.  

### ISSUE THREAD

**Issue by michielpr** [FlutterFlow/flutterflow-issues#2505]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, on the homepage of flutterflow, Alex and Andrew are 'working' in the same project. It spells out "ANAL". I am not sure whether this was intended or not.

Definitely made me and my colleague smirk/laugh.

Fullscreen:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2a0edac5-2947-4cb6-ab84-8600deaea504/4a762880-d7dd-400b-bd4a-f2d6b2f41986?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYTBlZGFjNS0yOTQ3LTRjYjYtYWI4NC04NjAwZGVhZWE1MDQvNGE3NjI4ODAtZDdkZC00MDBiLWJkNGEtZjJkNmIyZjQxOTg2IiwiaWF0IjoxNzEwMTk3MTQ0LCJleHAiOjMzMjgwNzU3MTQ0fQ.hSArZvGH7_qMIFMP7iVPUTIREvbRBuRnNNcmmYjz1fA)

Zoomed in:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/24e47376-fffb-42fa-84a1-7ba0bd5c13fc/a26a7e84-5b4c-42cb-b37f-81be651dc5b6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNGU0NzM3Ni1mZmZiLTQyZmEtODRhMS03YmEwYmQ1YzEzZmMvYTI2YTdlODQtNWI0Yy00MmNiLWIzN2YtODFiZTY1MWRjNWI2IiwiaWF0IjoxNzEwMTk3MTQ0LCJleHAiOjMzMjgwNzU3MTQ0fQ.eaXvOYFT__rw5963KauvNabxTv6vP1CDP0Xmwb43VKA)

Maybe this feature of using initials could be revisited/changed or at least, have the animation changed.

### Expected Behavior

The feature works the way it's intended. However, could be tweaked/changed.

### Steps to Reproduce

Go to [flutterflow.io](http://flutterflow.io) and watch the main page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Olcr1z4V2pb1K+KX2KMBFiSk5JlM7ULxMlNZ9RkoYGLXNGu4MPsneVFRuZrzmS1VAfGD88HIK/PfqvvLLUMEDAxeZY485yc5qcA7KfFynMraxBbrsfW1QQOZjGFSz36a3pR5AAOxfV0Yuw16xfOuib3bqGO/XPjEnJcmbKdeK2SrDX1iXc2URm05KZDPz

### Context

Just go to the main homepage of flutterflow and watch the animation.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9072e605-335c-4a3b-b8e9-0ee876e0a2ea/cabc655e-db5b-4a59-bef4-9cd4a3f03f2a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MDcyZTYwNS0zMzVjLTRhM2ItYjhlOS0wZWU4NzZlMGEyZWEvY2FiYzY1NWUtZGI1Yi00YTU5LWJlZjQtOWNkNGEzZjAzZjJhIiwiaWF0IjoxNzEwMTk3MTQ0LCJleHAiOjMzMjgwNzU3MTQ0fQ.3o_C5yLg9XkY-\_sYraYzyRr5Z082KFsS560-YQSEsIA)

### Additional Info

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/486b103b-f5d3-478a-bbf4-a84cb809c95c/7d416c74-175c-4862-8e48-11f43841cb57?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODZiMTAzYi1mNWQzLTQ3OGEtYmJmNC1hODRjYjgwOWM5NWMvN2Q0MTZjNzQtMTc1Yy00ODYyLThlNDgtMTFmNDM4NDFjYjU3IiwiaWF0IjoxNzEwMTk3MTQ0LCJleHAiOjMzMjgwNzU3MTQ0fQ.GYd_dVOe3BQeBugi91VxH-\_bqnkCqWLopo06h-6Ay0I)

### Environment

```markdown
Any.
```

**Comment by hariprasadms** [comment]
@michielpr - Thanks for reporting it. We will update it shortly. Thanks

**Comment by michielpr** [comment]
Thanks! 👍
