### ISSUE TITLE
Homepage is getting stuck on test mode

### ISSUE THREAD

**Issue by amcny** [FlutterFlow/flutterflow-issues#2506]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i want to test my app. it working fine upto authentication, when authentication is done, on homepage load the whole app is getting stuck, and i can't navigate to any page. This only happens in test mode. but everything works fine in Run mode

### Expected Behavior

It should show homepage without stuck and able to navigate to other pages as well

### Steps to Reproduce

1. Test my app in flutterflow
2. Login in to my app using given credentials

* email: [622241@student.nitandhra.ac.in](mailto:622241@student.nitandhra.ac.in)
* password: test1234

1. After login check for issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goulb0KXIYO1AhQIgQ0QnU7gnlO1ucx40G5StP4k2O8+lX0NKT/WRTVdUH1eb+Dod/6zFhePyVvAFEzOufNlc0JVATRfvUl+XaYSbDqW0Y0RREeBPGX6P3KWvmh0lAMhqdVYX2FyPNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to make sure my app is working in test mode also, if its working on run mode, then it should also work on test mode.

### Visual documentation

![Screenshot 2024-03-12 075340](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e86c8392-b858-4cab-878d-4116882be5b0/7efb15a7-1602-4453-9e0b-cda54bb1b09e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lODZjODM5Mi1iODU4LTRjYWItODc4ZC00MTE2ODgyYmU1YjAvN2VmYjE1YTctMTYwMi00NDUzLTllMGItY2RhNTRiYjFiMDllIiwiaWF0IjoxNzEwMjUxODM2LCJleHAiOjMzMjgwODExODM2fQ.t-dQ73XXPdyY5AS89h7On2i-MePa6eXX2jy4YNALRAw)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow Version: v4.1 (released March 9, 2024)
- Platform: Web
- Browser name and version: Google Chrome (122.0.6261.112)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @amcny -Thanks for reporting the issue. I've checked the project, but unfortunately, I'm unable to load it in test debug and run modes at my end. It keeps throwing the following error.

<img width="1363" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/1d9be6e6-7a22-45ed-b473-50342559e55f">

Tested out the downloaded code locally on the web went smoothly - no issues encountered. I was able to log in using the provided details. Hence marked it as project bug. We will look into it shortly and update the status here.

**Comment by amcny** [comment]
Thanks for the response, please check into this, because test mode is indeed. To test the app, I need to use run mode everytime which is disgusting. so please try to fix this

**Comment by hariprasadms** [comment]
We'll investigate further. In the meantime, let's redirect the logged-in homepage to a new page and check if the after-login page displays without any issues.

**Comment by hariprasadms** [comment]
In that case, the issue might be with the home page. Have you tried removing the widgets one by one to see which one is causing the issue? If not, please try this approach and let us know the results.

**Comment by amcny** [comment]
Okay

**Comment by amcny** [comment]
I removed a lottie file. and now its working. but what if i want that lottie animation compulsary ?

**Comment by takashiff** [comment]
Hi @amcny, unfortunately this is a current limitation of test mode, in which Lottie files may not load properly. If possible, I would advise either
1. Debugging in run mode or using Local Run
2. Removing the Lottie Animation when debugging in Test Mode

I apologize for the inconvenience. Thanks

**Comment by amcny** [comment]
Thank you
