### ISSUE TITLE
DropDown widget issues in UI Builder when using list variable, and also issues with height and initial value text.

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#2507]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

DropDown widget currently has three different issues, as far as I have encountered since the latest FF update:

* When options are fetched from a variable instead of manually filled one by one, the UI Builder itself shows those giant gray empty spaces like when there is an "Unexpected null value" at runtime in our applications;
* The height seems to be defaulted at 56px and decreasing it just changes its containing "box", so to say, whereas its actual content overflows outside of it;
* The "Initial Option Value" simply is never shown

### Expected Behavior

It should work just like it was one week ago, with none of the aforementioned issues. It may be related to the Flutter upgrade, though, if I may take a guess.

### Steps to Reproduce

1. Create new blank project;
2. Add a DropDown widget to the empty column;
3. For the empty space issue, you can just add a list of names from the sample data as variable to the DropDown and then scroll the widget properties down;
4. For the content overflow issue, just change the widget height to any value below the default 56px, like, for example, 30px;
5. And for the Initial Option Value issue, simple try adding literally any text to it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gruVD15fuKMFqhQInOUA5apAvlOsbFB4YG5zwB4kMZ/TCS0NKQt+5SglYGFGZrEw0w8L4ifDPJsc6IU2BGKY50JVAFzzjXTu6bIywDsyCVnF9P5lnJhWg0aWvvx5DJutaWHAXwFOtNq3qNleeY8aSfxBlZ7vfcPo=

### Context

It was working one week ago and it affects User Experience on important content filtering.

### Visual documentation

Here are some screenshots:

#### Giant empty space after adding list of values as variable:

![Captura de Tela 2024-03-12 às 00 34 53](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dc98b192-7a7a-4499-94e0-8a9603fedec5/8121719e-5045-46a3-b94a-392ca70faef5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYzk4YjE5Mi03YTdhLTQ0OTktOTRlMC04YTk2MDNmZWRlYzUvODEyMTcxOWUtNTA0NS00NmEzLWI5NGEtMzkyY2E3MGZhZWY1IiwiaWF0IjoxNzEwMjM1OTQ5LCJleHAiOjMzMjgwNzk1OTQ5fQ.azofq1b8pV99r2bES1j1N0VD44YWpwapXgfdQXN7hvs)

#### Content overflow issue after decreasing widget's height and also the initial value not showing:

![Captura de Tela 2024-03-12 às 00 40 01](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fc898b60-5dc1-4284-992e-c50d7622c4f3/0af5116f-0c38-4ade-b4cb-e40a9e4fa771?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYzg5OGI2MC01ZGMxLTQyODQtOTkyZS1jNTBkNzYyMmM0ZjMvMGFmNTExNmYtMGMzOC00YWRlLWI0Y2ItZTQwYTllNGZhNzcxIiwiaWF0IjoxNzEwMjM1OTQ5LCJleHAiOjMzMjgwNzk1OTQ5fQ.pKmVg01KnsMcGEWBkYZ3wAvEe_jjkKMDh_BGlIQQAso)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.32
- Platform:MacOS Desktop
- Browser name and version: Brave v1.63.169
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by furkanyilmazorka** [comment]
i have similar dropdown issues caused probably by the 3.19 flutter upgrade i assume?

**Comment by hariprasadms** [comment]
Hi @vitoras - Thanks for reporting the issue. I can reproduce the point number 1 but no other two.

1. When options are fetched from a variable instead of manually filled one by one, the UI Builder itself shows those giant gray empty spaces like when there is an "Unexpected null value" at runtime in our applications;

<img width="953" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/eb4a1413-3afd-44eb-b177-8140554f9925">

2. The height seems to be defaulted at 56px and decreasing it just changes its containing "box", so to say, whereas its actual 
 content overflows outside of it;
- This is as per current design. 

3. The "Initial Option Value" simply is never shown - It is working as expected.

**Comment by vitoras** [comment]
Hi @hariprasadms !

> 2. The height seems to be defaulted at 56px and decreasing it just changes its containing "box", so to say, whereas its actual
content overflows outside of it;
>  - This is as per current design.

I don't get it. I could swear it was not overflowing it before with a height lower than 56px. So we cannot define any other height below this, therefore?
