### ISSUE TITLE
FlutterFlow sorting "Data Table" didn't work

### ISSUE THREAD

**Issue by NilsAKEcke** [FlutterFlow/flutterflow-issues#2509]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,
I'm new to FlutterFlow and currently trying to create a sorting function in a DataTable.

For implementing my use case, I'm referring to the example provided in the FlutterFlow Docs titled "DataTable (Paginated)" (Link: [https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated?](https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated?)), specifically the "Sorting" example.

I've attempted to implement the example as described in the documentation.
However, I encounter an error when trying to pass the values "Is Ascending" and "Sorted Column Index" to my custom function.

![grafik](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/16604cc0-32ef-4dec-9164-087e66d7f095/d4aa9dd8-efe3-4b6c-8886-de0a6468e5fb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNjYwNGNjMC0zMmVmLTRkZWMtOTE2NC0wODdlNjZkN2YwOTUvZDRhYTlkZDgtZWZlMy00YjZjLTg4ODYtZGUwYTY0NjhlNWZiIiwiaWF0IjoxNzEwMjM1ODY5LCJleHAiOjMzMjgwNzk1ODY5fQ.FFFH3_liLeBZw8f5UP1oQy9lapuA1ux1Lhczx7S7RIM)

The error message states, among other things, "Field "" has an update value that is not properly set in Update App State action for PaginatedDataTable." According to the FlutterFlow Support, this is a bug that I should report here. As per the Support, the issue seems to be: "It looks like the issue is that the "Is Ascending" field is not getting selected correctly for any bool variable; I have tried testing directly with a simple page state variable and similar issues are experienced."

Currently, FlutterFlow is using version 3.19.1.

I would greatly appreciate a solution to the problem.
Feel free to reach out if you have any questions.
Thank you in advance.

### Expected Behavior

I expected that the values "Is Ascending" and "Sorted Column Index," provided by the DataTable, could be passed to the custom function.

### Steps to Reproduce

To replicate the issue, simply recreate the example provided in the FlutterFlow Docs.
See Link: [https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated?#sorting](https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated?#sorting) (#Sorting)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lPLq25dgrt9Y7ZDuau9agiYWH1s7RI000NYbVgE8J67PB4kif8/7QBJWXdeXd2NcIVWJjmIy087Zvtr9U8ACKUyrUb1q3bhyVQziQkSQWpebDKqwdHd7J/pMBWaX37Wwngx9FMhaLEYc7DuyFfO9UgPbGZTpC1YdMv6JBJnAgVXjASTWGhFX5CdecCfn

### Context

To replicate the issue, simply recreate the example provided in the FlutterFlow Docs.
See Link: [https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated?#sorting](https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated?#sorting) (#Sorting)

### Visual documentation

Currently, I'm unable to deploy the project.

![grafik](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2a2f021a-39cb-4e05-ae86-d6c09d7ee9a7/2660bb2c-bf30-4746-bd0e-041d9449a5d4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYTJmMDIxYS0zOWNiLTRlMDUtYWU4Ni1kNmMwOWQ3ZWU5YTcvMjY2MGJiMmMtYmYzMC00NzQ2LWJkMGUtMDQxZDk0NDlhNWQ0IiwiaWF0IjoxNzEwMjM1ODY5LCJleHAiOjMzMjgwNzk1ODY5fQ.OljaZHNz9wvhzl2n-FiMzeLoyS4VKJzDJKjtVNYZngQ)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released March 9, 2024
- Platform: Web
- Browser name and version: Chrome and Firefox
- Operating system and version affected: Windows 11
```

**Comment by NilsAKEcke** [comment]
Hallo,
the bug still exists at the moment. 
Please do not close the ticket. 
If you have any further questions, feel free to ask.

**Comment by rzambroni** [comment]
Hey @NilsAKEcke, Sorry about the delay on this. 

I was able to reproduce the issue you are describing on a blank project. I believe there might be a bug or a step missing in the docs.

Will send this over to the team so they can take a look.  As soon as we have news, we will update the status here.

Thanks for your report!

**Comment by rzambroni** [comment]
Hey @NilsAKEcke, i just noticed this was already reported before, will close this as a duplicate, please consider keeping an eye on the original ticket as it will be updated when this is fixed. [https://github.com/FlutterFlow/flutterflow-issues/issues/2472](https://github.com/FlutterFlow/flutterflow-issues/issues/2472)
