### ISSUE TITLE
URL Launcher not working on Android devices

### ISSUE THREAD

**Issue by damianfraire** [FlutterFlow/flutterflow-issues#2513]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Before flutter upgrade, URL launcher was working and launching local browser with the provided URL. Now it's not launching crashing the app completely on Android devices. Although it does work on flutterflow test mode using the browser and also in iOS, it does not work on Android devices (I tried both my local android phone and also Android Studio pixel simulator).

### Expected Behavior

It should launch the required URL

### Steps to Reproduce

1. Create a new page
2. Add a button
3. Under actions -> select URL Launcher
4. Pass any url (i.e. [https://www.google.com](https://www.google.com)).
5. Test on an android device/simulator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

[IT4oz/Hqx89grs9J1s/IdfoxnSQvQl83U+YRlMpOGDsdF4iuPOxzac/7aVhVOcjjdwlhKEWLgmoBp8L4hdjxDPICHziBQKZdz8xiTj3ibFi/aoShC6iObXcnEp5VGXKb0J6vnB1SFMdpcmQ13EyYfOeRaBXbO5v6Zwh9f6PHaOI=](https://linear.app/flutterflow/issue/QA-331/url-launcher-not-working-on-android-devices)

### Context

I deployed a new version to app stores (both apple and google) and did not perform regression testing on these URL launcher as they are pretty much OOTB flutterflow components, so this bug affected my deployed app.

### Visual documentation

There's no app screenshots to take as it would just crash the app and close it, but I took as screenshot below of the simulator right after it happened.

![Screenshot 2024-03-12 at 1 12 29 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6227a0c-8179-4d7f-aec2-0567d3c56cae/8d7f8732-e463-4c4b-8d81-a4af4e2f90eb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNjIyN2EwYy04MTc5LTRkN2YtYWVjMi0wNTY3ZDNjNTZjYWUvOGQ3Zjg3MzItZTQ2My00YzRiLThkODEtYTRhZjRlMmY5MGViIiwiaWF0IjoxNzEwMjY1MjgyLCJleHAiOjMzMjgwODI1MjgyfQ.Lv82nrzyTksVXJXY2ZdIWM5lKKK_odxSYDkVWpPy2Lw)

### Additional Info

Error log:

D/AndroidRuntime(24299): Shutting down VM
E/AndroidRuntime(24299): FATAL EXCEPTION: main
E/AndroidRuntime(24299): Process: com.mycompany.testproject, PID: 24299
E/AndroidRuntime(24299): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.testproject/io.flutter.plugins.urllauncher.WebViewActivity}: java.lang.SecurityException: com.mycompany.testproject: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(24299): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
E/AndroidRuntime(24299): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
E/AndroidRuntime(24299): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(24299): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(24299): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(24299): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
E/AndroidRuntime(24299): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24299): at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(24299): at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(24299): at android.app.ActivityThread.main(ActivityThread.java:8913)
E/AndroidRuntime(24299): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24299): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/AndroidRuntime(24299): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/AndroidRuntime(24299): Caused by: java.lang.SecurityException: com.mycompany.testproject: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(24299): at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
E/AndroidRuntime(24299): at android.os.Parcel.createException(Parcel.java:3053)
E/AndroidRuntime(24299): at android.os.Parcel.readException(Parcel.java:3036)
E/AndroidRuntime(24299): at android.os.Parcel.readException(Parcel.java:2978)
E/AndroidRuntime(24299): at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
E/AndroidRuntime(24299): at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
E/AndroidRuntime(24299): at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
E/AndroidRuntime(24299): at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
E/AndroidRuntime(24299): at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
E/AndroidRuntime(24299): at io.flutter.plugins.urllauncher.WebViewActivity.onCreate(WebViewActivity.java:146)
E/AndroidRuntime(24299): at android.app.Activity.performCreate(Activity.java:8960)
E/AndroidRuntime(24299): at android.app.Activity.performCreate(Activity.java:8929)
E/AndroidRuntime(24299): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
E/AndroidRuntime(24299): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
E/AndroidRuntime(24299): ... 12 more
E/AndroidRuntime(24299): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(24299): at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16590)
E/AndroidRuntime(24299): at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
E/AndroidRuntime(24299): at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
E/AndroidRuntime(24299): at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
E/AndroidRuntime(24299): at android.os.Binder.execTransactInternal(Binder.java:1375)
E/AndroidRuntime(24299):
I/Process (24299): Sending signal. PID: 24299 SIG: 9
Lost connection to device.

### Environment

```markdown
- FlutterFlow version: 4.1.32
- Platform: Android device/simulator
- Browser name and version: Chrome 122.0.6261.94 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.3.1
```

**Comment by GoCloudToday** [comment]
I have had the exact same issue, and the only solution that worked was to update the version of the url_launcher packages on pubspec.yaml

  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.5
  url_launcher_platform_interface: ^2.3.2

**Comment by simonrayray** [comment]
I can confirm that the open URL action also crashes my app completely on Android after the 3.19 update.

**Comment by Karthikaddagalla** [comment]
Yeah, I am having the same issue with launch URL action

**Comment by lancasterjones** [comment]
Same issue here.
Works fine with iOS but causes android devices to crash.

**Comment by damianfraire** [comment]
Hi flutterflow team @takashiff @hariprasadms @FlutterFlowEng. Could you please validate this issue? It seems to be a bug.

**Comment by damianfraire** [comment]
This is still an issue. Can someone please update on it?

**Comment by paulperez-dev** [comment]
Hi @GoCloudToday! Thanks for your report and sorry about the delay in the response, we are trying to get up to speed with everything. I was not able to reproduce this issue on a blank project.

We recently released a new version, can you guys please try to launch a link in a new project? If you face any issues, please share the bug report code again.

**Comment by damianfraire** [comment]
Hi @paulperez-dev , thanks for the response. I re tested today and now it's working. It looks like the new version took care of this issue. Thanks!

**Comment by damianfraire** [comment]
Closing as fixed.

**Comment by paulperez-dev** [comment]
Glad to hear that!
