### ISSUE TITLE
FlutterFlow Mac Desktop App Crashes

### ISSUE THREAD

**Issue by zhengyishen0** [FlutterFlow/flutterflow-issues#2515]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. The desktop app crashes when I click on the subcollection tab in Firestore data schema settings.
2. The app also crashes when I update an icon after searching by icon names (it works fine if I just scroll down and select an icon).

The web version has no such issues. Only the desktop version crashes.

### Expected Behavior

No crashes happen.

### Steps to Reproduce

In the Mac app, open a project that has a subcollection in the data schema, and click on the name of any subcollection. The app will crash.
Add an icon button on any page, update the icon by searching keywords of the icon name, then click any icon, and the app will crash.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESls/l7YVgrulB7s7qLcBAhR4mJkQ5a7lF1u1HUQwbIYOvBIwpWszTP0taTc+YTVZAI1qghmEe3MLTifHfN8BcGAyHY4hJws1qERWWVkWRR8WsC6uwVHFQL+dRN32O3ImzmhV7KrZZZVFpig/GSw==

### Context

I cannot use the desktop app since it keeps crashing. I use the web version now but prefer to use the desktop version to leverage the new "Local Run".

### Visual documentation

[icon_bug.txt](https://github.com/FlutterFlow/flutterflow-issues/files/14576684/icon_bug.txt)
[subcollection_bug.txt](https://github.com/FlutterFlow/flutterflow-issues/files/14576685/subcollection_bug.txt)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.32
- Platform: Macbook Air M1, 8g, 256g.
- Browser name and version:
- Operating system and version affected: MacOS Sonoma 14.3.1 (23D60)
```

**Comment by takashiff** [comment]
Hi @zhengyishen0, thanks for the bug report! If you don't mind, could you share a video of this occurring? I am currently unable to reproduce the issue. Thanks

**Comment by zhengyishen0** [comment]
Hi, @takashiff,

Thanks for getting back to me. I've recorded a video to reproduce this bug.

The app crashes on my M1 Mac when:
1. click on the subcollection
2. click an icon after search the name (it's fine when not searching)

I have reinstalled the app and restarted my mac many times. The crash happens every time.

https://github.com/FlutterFlow/flutterflow-issues/assets/114040523/51728bc9-2fa3-416e-ae0e-768223e5dbe3

**Comment by zhengyishen0** [comment]
Any updates on this bug?

**Comment by AnushaFF** [comment]
Hi @zhengyishen0 
Thank you for your patience, we are looking into the issue and are still unable to reproduce this error.
I tried looking at your project and couldn't find the firebase collection that's mentioned in the video. Have you updated the project recently? In the meanwhile could you please check if there any updates available for the latest mac OS version?

**Comment by AhmedWagdi1** [comment]
both mac and windows crashed on start-up.. and the flutterflow team decided that its better to ignore the issue and close it all !!
