### ISSUE TITLE
Error consuming an api

### ISSUE THREAD

**Issue by PensarSolpen** [FlutterFlow/flutterflow-issues#2516]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So, i´m building a app on FlutterFlow addressed in "solpen-producao-853uz8". Its a simple app, that i need to deploy on a local server running Windows Server over IIS7. 
When i run the app at FlutterFlow enviroment, every thing is ok, i.e,  i have comunication perfect into my API.
My problems start when i make a "download the code", and using a Flutter instalation, i build the app for web enviroment, using "flutter build web". 
After the build, i deploy into a IIS7 server. 
When i try to execute over a web browser like chrome, i receive the status -1, when the api call happen. As showed on attached image. 
![api_error](https://github.com/FlutterFlow/flutterflow-issues/assets/19392966/e2d2f9d8-2f78-4018-9de0-3c1c35e6c1c4)
For considerations, i inserted a web.config to avoid cors call, and the content of file is bellow :
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
  <httpProtocol>
    <customHeaders>
      <add name="Access-Control-Allow-Origin" value="*" />
      <add name="Access-Control-Allow-Methods" value="GET,PUT,POST,DELETE,OPTIONS" />
      <add name="Access-Control-Allow-Headers" value="Content-Type" />
    </customHeaders>
  </httpProtocol>
 </system.webServer>
</configuration>

i hope that you can help with this.

Thank you

Alexandre

### Expected Behavior

Expected to be able to consume api on local enviroments.

### Steps to Reproduce

1 - Download the project code
2 - Build over flutter enviroment (flutter buid web)
3 - Deploy on a iis7 webserver
4 - Any value on a start screen , the error will come.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no code

### Context

I tried help, from the flutterflow support, and they asked for open the issue.

### Visual documentation

![api_error](https://github.com/FlutterFlow/flutterflow-issues/assets/19392966/800d9e20-680e-4756-86ee-8b68441fe5ca)

### Environment

```markdown
- FlutterFlow version: 3.19.3
- Platform: windows server 2016 over iis7
- Browser name and version: chrome 
- Operating system and version affected: windows server 2016
```

**Comment by hariprasadms** [comment]
Hi @PensarSolpen - Thank you for submitting the issue. Since you mentioned that it works fine in FlutterFlow but not from local deployment, it is likely specific to the setup and there could be a CORS blocking issue. Please open the developer console and check for any errors, as this may provide a clearer idea of why it is failing. If the issue is specific to the user's configurations, we recommend contacting FlutterFlow support for further help. In general, I can confirm that API calls are working fine with FlutterFlow. Therefore, I can mark this as not a bug.

**Comment by PensarSolpen** [comment]
Hello,

I already contacted the support team, and they tell us to contact the issue system. I don´t about if its a bug or no, i know that it´s not working in my desired enviroment.
How can i access the developer console ?

thanks

Alex
________________________________
De: Hari ***@***.***>
Enviado: sexta-feira, 15 de março de 2024 13:17
Para: FlutterFlow/flutterflow-issues ***@***.***>
Cc: PensarSolpen ***@***.***>; Mention ***@***.***>
Assunto: Re: [FlutterFlow/flutterflow-issues] Error consuming an api (Issue #2516)


Hi @PensarSolpen<https://github.com/PensarSolpen> - Thank you for submitting the issue. Since you mentioned that it works fine in FlutterFlow but not from local deployment, it is likely specific to the setup and there could be a CORS blocking issue. Please open the developer console and check for any errors, as this may provide a clearer idea of why it is failing. If the issue is specific to the user's configurations, we recommend contacting FlutterFlow support for further help. In general, I can confirm that API calls are working fine with FlutterFlow. Therefore, I can mark this as not a bug.

**Comment by PensarSolpen** [comment]
Hello, i dont know who i should contact, The support tells me contact the issue, the issue tells me contact the support.
Who can help me ?
