### ISSUE TITLE
Timer does not reset in callback function

### ISSUE THREAD

**Issue by yannicschuller** [FlutterFlow/flutterflow-issues#2517]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the timer stops and a bottom sheet is openend. The callback function in the bottom sheet can't reset or start the timer on the homepage.

### Expected Behavior

Timer can be controlled in the callback function.

### Steps to Reproduce

1. Create a timer on one page.
2. When the timer stops, open a bottom sheet.
3. Bottom sheet has a callback function for a timer reset / timer start.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wz/Hqx89grt9A1qruYO9VgjgXNnImUIIzkMN+TkggfLLkEYwPQPvRalZWUs+0Y29bfWGjgn0e+tnemvHyUsJcPS6dc6I/zZBxVQ/wfzuuSrqrC5GOS25/DeVgfmKw36a72xMmBMFhSCUE7TqXe+uRaHTYK5DQIW1MAeaLJZOK2SrDX1iXc2URm05KZDPz

### Context

Timer can be reset and started after a bottom sheet was openend. So the user can continue the timer.

### Visual documentation

![CleanShot 2024-03-13 at 00 26 26@2x](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e4132820-2742-4a24-b5f8-0618425fad43/58d1cd95-e04b-474a-921f-388b9deeae51?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNDEzMjgyMC0yNzQyLTRhMjQtYjVmOC0wNjE4NDI1ZmFkNDMvNThkMWNkOTUtZTA0Yi00NzRhLTkyMWYtMzg4YjlkZWVhZTUxIiwiaWF0IjoxNzEwNTIxNDI1LCJleHAiOjMzMjgxMDgxNDI1fQ.BehIsaR6-Q56qBOS2U8bMcSP6nxaBbCLiWb8aauq85o)

![CleanShot 2024-03-13 at 00 26 51@2x](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dec3b94d-4c5c-4084-8fac-05203a08c97a/5d286188-52df-48b2-bf85-087601135749?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZWMzYjk0ZC00YzVjLTQwODQtOGZhYy0wNTIwM2EwOGM5N2EvNWQyODYxODgtNTJkZi00OGIyLWJmODUtMDg3NjAxMTM1NzQ5IiwiaWF0IjoxNzEwNTIxNDI1LCJleHAiOjMzMjgxMDgxNDI1fQ.oiXHz8Y0mlS1q1QPUcIxlVE4gjDbCf78hNOxHORiZ10)

### Additional Info

Test project: [https://app.flutterflow.io/project/test-timer-callback-ihvtgs?tab=pageSelector&page=HomePage](https://app.flutterflow.io/project/test-timer-callback-ihvtgs?tab=pageSelector&page=HomePage)
Bug has also already been reviewed by "David" in chat support.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released March 9, 2024
Flutter version is 3.19.1
- Platform: Browser
- Browser name and version: Safari 17.4
- Operating system and version affected: MacOS
```

**Comment by davidflutterflow** [comment]
@hariprasadms we reproduced this in support and seems it's a bug, and may be related to the state of the timer, as we are show the modal in at timer end event on the timer.
