### ISSUE TITLE
widget searching is not working

### ISSUE THREAD

**Issue by wtklim** [FlutterFlow/flutterflow-issues#2518]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/163215039/a9272875-6206-4eaa-aa22-cfd6f9c5b720)

search not working in widget. please fix asap. otherwise, i can't start develop...

### Expected Behavior

can't search widget..  please try byyourself. even i search containerks262, it is not searched

### Steps to Reproduce

check above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

lkjlkj

### Context

check above

### Visual documentation

check abovecheck above!!!!
check above!!!!
check above!!!!

### Additional Info

check above check above!!!!
check above!!!!
check above!!!!

### Environment

```markdown
check above!!!!
 check above!!!!
```

**Comment by hariprasadms** [comment]
Hey @wtklim - I've verified it, and I can confirm that the widget tree search is generally working as expected. However, to investigate the issue specific to your case, please provide the project bug report code to access your project.

**Comment by wtklim** [comment]
Hello

I am wondering you actually checked or not?

Create the container
Change the name for each container. Forexample container1 container2
container3
Try search container3 by typing at search box
You can see it is not working which means all of container will just shown.
It supposed to be shown only container3

I already share this error with Danny who is your team and he also
confirmed it is error

Please do check this error and please can you fix asap? Because I need this
functio  asap to develop app quickly..

Thanks

2024년 3월 16일 (토) 오전 1:24, Hari ***@***.***>님이 작성:

**Comment by rzambroni** [comment]
Hello @wtklim,

I've been attempting to replicate the issue you reported but everything seems to be functioning correctly on our end with the latest version of FlutterFlow.

Are you still experiencing this problem?

if so, would you mind adding a bit more evidence to the issue to help us troubleshoot your specific scenario? Environment, Visual documentation (video) and the bug report code would be of really good help.

This information will greatly help us in troubleshooting your specific scenario.

Thank you for your cooperation.

Best regards,

**Comment by wtklim** [comment]
hi
can you see this?
https://drive.google.com/file/d/1g0vWkiyzZYZfucrpED_8JDq_tGnvwhMy/view?usp=sharing
i made video for you
thanks

**Comment by rzambroni** [comment]
Hey, @wtklim, thanks a lot for the video and context. I was able to see the problem you are having by using the search function in your project. Will send this to the team so they can take a look.

**Comment by leighajarett** [comment]
Hi there! Thanks for this issue, we'll be working on improving our search capabilities later in the year and will also focus on the use case you specified. Thanks so much for the feedback! Closing this issue because its tracked in our internal roadmap

**Comment by wtklim** [comment]
hi. what the bad service flutterflow... when will you fix this error?
it is very crucial function in flutterflow. User has to be able to search
the widget but it is not working!!! You are ignoring my bug report, right?
