### ISSUE TITLE
Not possible to pass Null constant to nullable properties

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#252]
## Expected behavior (required)

When defining nullable properties in custom components, custom functions or custom actions, it is impossible to pass Null constant from FF to the properties:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/4561505/208793915-0f14b2d4-ab61-465f-af80-3605964bc112.png">

![image](https://user-images.githubusercontent.com/4561505/208794151-2fba1639-5d9f-41ab-befa-1141181c8cff.png)

Since it's impossible to explicitly pass the Null constant, leaving a nullable parameter undefined makes FF report it as an error.

## Current behavior (required)

Null appears in red, so it is not possible to pass it.

Workaround:
We have to create a custom function that returns a specific nullable type for each data type and return null from that function. We then have to pass that function as parameter.

## To Reproduce (required)

1. Create a custom function or component that takes a nullable Document type parameter
2. Add the component to a page
3. For parameter, select Specific Variable -> Constant -> Null

## Context (required)

Need to be able to pass Nulls in some cases when it makes sense (eg a value does not exist).

## Your environment

* Version of FlutterFlow used: 1.1.27
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Browser name and version: N/A
* Operating system and version (desktop or mobile): OSX Ventura 13.0.1

**Comment by agreaves** [comment]
Thanks @isegal for the bug report! Currently Null can be applied to almost everything, but not Documents and Document References due to a bug. This will now be fixed upon our next release! 🙂
