### ISSUE TITLE
Walkthrough causing errors and unable to test

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2521]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Walkthrough on the homepage was causing us to not be able to test the app per the error below. I have since deleted the walkthrough

![Screenshot 2024-03-12 at 10 55 51 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/efe6d623-6e9e-4137-a24d-161c1dd8529d/774eb3a7-238f-47db-b957-1b2af3c7a69a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZmU2ZDYyMy02ZTllLTQxMzctYTI0ZC0xNjFjMWRkODUyOWQvNzc0ZWIzYTctMjM4Zi00N2RiLWI5NTctMWIyYWYzYzdhNjlhIiwiaWF0IjoxNzEwMzM0NjA1LCJleHAiOjMzMjgwODk0NjA1fQ.au7fL6whsOcS2nzbMYzygKqPcx3q2J7ilm4xVTRxGoo "=524x")

### Expected Behavior

Walkthrough does not cause errors in testing

### Steps to Reproduce

1. Go to project (I duplicated the project with the walkthrough video)
2. Try to test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OhcmA/otIj7wD7arAa8dFpCkXQlwhaJZN08FHa0oYIpfNG7UIec/4VEptXbC+TVc3PE2ggmEeps7Xv9zIN/Q5ITuZc6ZSz89yUxbdfDuQeJDUO5eBPUBfEtpKBWLD4KeNoR1/PfVvLUYC31yYAOi9dAPsNbL6OWsRPM+HIpPMo3PuQ0SLb3kNh1JWeC/v

### Context

I had to delete the walkthrough which I was very much hoping to use within my app

### Visual documentation

![Screenshot 2024-03-12 at 10 55 51 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0dd9b968-79ee-47e1-af3c-309fbd5f4384/0962401a-3c7b-4fa9-b0f2-025ab19344e8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZGQ5Yjk2OC03OWVlLTQ3ZTEtYWYzYy0zMDlmYmQ1ZjQzODQvMDk2MjQwMWEtM2M3Yi00ZmE5LWIwZjItMDI1YWIxOTM0NGU4IiwiaWF0IjoxNzEwMzM0NjA1LCJleHAiOjMzMjgwODk0NjA1fQ.0ocFyTCBYc7Pj_Udo2BkW7_nos8mShfcg5DqvHy1ZHw "=524x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by DevKursat** [comment]
THIS ERROR NEEDS TO BE FIXED URGENTLY! I DON'T THINK IT IS TOO DIFFICULT FOR THE TEAM, BUT IT NEEDS TO DRAW ATTENTION.

**Comment by karabil** [comment]
Having the same issue. Hopefully could be fixed soon.

**Comment by DevKursat** [comment]
We are waiting, can you please let us know when it will be resolved?

**Comment by raphald** [comment]
Same error here!

**Comment by DevKursat** [comment]
My error was not resolved, why did you close it?
Project URL: https://app.flutterflow.io/project/zafer-rqs8we?tab=widgetTree&page=AnaSayfa

**Comment by Dev-Muhammad-Junaid** [comment]
@sbis04 just checked, this issue is still pending.
And this time I can't build or publish the application whilst creating a new walkthrough,
<img width="658" alt="Screenshot 2024-03-15 at 8 44 55 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/ba26a2e1-6a62-452f-b67c-ac68a874b438">


https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/6e1ec612-0117-4ac8-ab4b-d1b20b23ac18

**Comment by gematlas** [comment]
I am also having the same issue

**Comment by sbis04** [comment]
Sorry for the late reply, the fix wasn't fully deployed when this issue was closed. But now it is, so the walkthrough issues should be fixed!

**Comment by DevKursat** [comment]
You should allow using multiple walktroughs on the same page and could you also check this error please: DropDown Crash! #2547
