### ISSUE TITLE
Wrong text font in the desktop custom code

### ISSUE THREAD

**Issue by rambros** [FlutterFlow/flutterflow-issues#2523]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the desktop app, all codes appear in an unreadable font. The same project has the correct text font in custom code.

![MeditaBK - FlutterFlow 2024-03-12 at 3 11 12 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8ee22972-64f1-41af-8678-c8bcbcc34841/cda1145d-3abf-4655-babd-c1d6c3c70907?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84ZWUyMjk3Mi02NGYxLTQxYWYtODY3OC1jOGJjYmNjMzQ4NDEvY2RhMTE0NWQtM2FiZi00NjU1LWJhYmQtYzFkNmMzYzcwOTA3IiwiaWF0IjoxNzEwNTIwNTMzLCJleHAiOjMzMjgxMDgwNTMzfQ.Jxa4H7QihRA2GF4B64TpgHkhbn7A8mezjXutqaYQYpc)

### Expected Behavior

the same text font online and in desktop app

### Steps to Reproduce

1\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.just open desktop app and go to custom code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi/Hl249IschE7ZSJa+9avCQsQk9/RK00sNobbxAjIoDoPJkUaePBNhJVOd+qdFVPKEWLrzkep/Tzj/DhJ/k3FwWrbqJez5BMEDuUez+/aoSNDYe8f0FDJ+1YG3Ka0LSJrBYmLvVqcVoa31+IHO6QZz/tQe77Zwh9f6PHaOI=

### Context

I can't use the desktop app because I can't see or undestand the custom code (functions, widgets or actions)

### Visual documentation

![MeditaBK - FlutterFlow desktop](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b268f290-b0df-449f-b756-a18814c9c7ad/eb14ad2e-de1a-4e42-b2a9-9966f5ddc0ab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMjY4ZjI5MC1iMGRmLTQ0OWYtYjc1Ni1hMTg4MTRjOWM3YWQvZWIxNGFkMmUtZGUxYS00ZTQyLWIyYTktOTk2NmY1ZGRjMGFiIiwiaWF0IjoxNzEwNTIwNTMzLCJleHAiOjMzMjgxMDgwNTMzfQ.uw9KwtEUq6RRVpJ1gmvQ4i2YIbzLCVqe5WUoMGkqG1Y)

![MeditaBK - FlutterFlow desktop_online](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c284c5cd-5fd8-4a75-8277-e963a0a0fbc3/0b340061-c193-41f7-972e-84836a01d94a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMjg0YzVjZC01ZmQ4LTRhNzUtODI3Ny1lOTYzYTBhMGZiYzMvMGIzNDAwNjEtYzE5My00MWY3LTk3MmUtODQ4MzZhMDFkOTRhIiwiaWF0IjoxNzEwNTIwNTMzLCJleHAiOjMzMjgxMDgwNTMzfQ.cD7x2bUk3UIZflo_6srDm91_NUzorBijXWVlzJBW_1c)

![MeditaBK - FlutterFlow online](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6550a27e-103e-4656-8342-0a499b741258/492eb074-a3dd-409f-a36c-f6cc855c4a52?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NTUwYTI3ZS0xMDNlLTQ2NTYtODM0Mi0wYTQ5OWI3NDEyNTgvNDkyZWIwNzQtYTNkZC00MDlmLWEzNmMtZjZjYzg1NWM0YTUyIiwiaWF0IjoxNzEwNTIwNTMzLCJleHAiOjMzMjgxMDgwNTMzfQ.3GxcUIFmgE9M_G40CjDX_LzPHLwAVGPQISChmw61320)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.32
- Platform: macOS desktop
- Browser name and version: Chrome Version 122.0.6261.112 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by takashiff** [comment]
Hi @rambros, thank you for the bug report. Is this an issue across all of your projects, or just the one specific project you have provided? Thanks

**Comment by rambros** [comment]
Hi,
all projects in desktop.
When I select some text and copy to VS Code, it is ok.
The same code works fine on both the iPad and web browser.
Regards
Rodrigo

Em ter., 19 de mar. de 2024 às 20:00, takashiff ***@***.***>
escreveu:

**Comment by rambros** [comment]
Thanks for the tip!
I had this font installed but reinstalled and now it is working.
Great!

Regards
Rodrigo

Em qua., 20 de mar. de 2024 às 15:46, takashiff ***@***.***>
escreveu:

**Comment by takashiff** [comment]
@rambros Glad to hear this resolved the issue for you!

**Comment by rambros** [comment]
Thanks for your support.

Em qua., 20 de mar. de 2024 às 18:38, takashiff ***@***.***>
escreveu:
