### ISSUE TITLE
Text Alignment on Place Picker stuck as "centered"

### ISSUE THREAD

**Issue by tokaviva** [FlutterFlow/flutterflow-issues#2525]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am encountering an alignment issue with the text of a Place Picker button within the Flutter Flow interface. Despite setting the button text to align left within the properties panel, the text remains centered and does not reflect the alignment setting applied.

### Expected Behavior

The button text should align to the left side of the button as per the properties setting.

### Steps to Reproduce

1. Add a Place Picker widget to the canvas.
2. Go to the properties panel for the button within the Place Picker.
3. Set the 'Text Align' property to left-align.
4. Observe that the text alignment does not change and remains centered.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESls/l7YVgrs9Z1rn1Ku1AhQUgNnInUOcrs+5+bwojF5D4EZYIe+OkSxFoOPazaH42M2GLgTgD+crFidjpEvQENQqtY756yboJexPPbGS6RLqTDJaSOXd7L+BbGlOP0MCk2hQlOu5sWXgG2U2uAfKyaz+Cf9qOYwx5e6fDbOY=

### Context

I want to align the Place Picker text to the left inside the widget.

### Visual documentation

![Screenshot 2024-03-13 195530](https://github.com/FlutterFlow/flutterflow-issues/assets/132686422/8b0309cb-66be-4a2b-8efb-ce10fe0d14ad)

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome 122.0.6261.129
- Operating system and version affected: Windows 11 Home 23H2
```

**Comment by hariprasadms** [comment]
Found this in your project. See below, this is because column widget cross axis property set to stretch. Keep this default. Remove and add back column widget.

<img width="1476" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8d8bdf50-c848-4000-bb13-ef522fa7d247">

**Comment by tokaviva** [comment]
<img width="1248" alt="Screenshot 2024-03-15 113202" src="https://github.com/FlutterFlow/flutterflow-issues/assets/132686422/d2c0b6ce-ba5f-42c3-afd6-1a74c88630d7">

The issue still seems to be there, I would like to put the place picker inside a form style page, but it centers on the middle.
What I would like to do is to match all the other text field widgets, see below:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/132686422/4833278f-c621-49db-80e6-6996b5729c46)

**Comment by rzambroni** [comment]
Hey @tokaviva, thanks for the report. I was able to replicate the issue and will send it over to the team for review. Will update the status of the ticket once it is fixed.
