### ISSUE TITLE
Docs Page Fails after loading

### ISSUE THREAD

**Issue by ericwiedemann** [FlutterFlow/flutterflow-issues#2526]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

You can try to visit: https://docs.flutterflow.io/widgets-and-components/widgets/page-elements/appbar
and the page will crash after attempting to load a widget, I have tried on multiple browsers and computers and all have the same effect the page will load and then crash.

### Expected Behavior

the page stays loaded.

### Steps to Reproduce

simply visit the page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

This is in the documentation pages.

### Visual documentation

https://www.loom.com/share/60a7745932b844f1af8325efbe699250

### Environment

```markdown
- FlutterFlow version: 
- Platform: Chrome Safari
- Browser name and version:
- Operating system and version affected: 
mac os
```

**Comment by zawadsoon** [comment]
Same here.

It would be helpful if documentation would work.

**Comment by zawadsoon** [comment]
Looks like it started working
