### ISSUE TITLE
Arrow button with action not working

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2528]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on the pencil icon in the groupdashboard, nothing happens, even though there is an action to go the the next page

### Expected Behavior

When you click on pencil, it goes to ModeratorGDashboard

### Steps to Reproduce

1. Go to Dashboardgroups 
2. Switch tab to created
3. Click on pencil icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

CgxSb3dfeDkyYWE3bXgS7wEKD0J1dHRvbl9weWpmMGtjNhgJIq4BSpwBCikKBkNhbmNlbBEAAAAAAAAsQCgHOgYImbPm/A9ABXoKEgg0NDk0ajV4MBkAAAAAAAAAADEAAAAAAABCQEkAAAAAAADwP1ICCABaAggAci8JAAAAAAAAIEARAAAAAAAAIEAZAAAAAAAAIEAhAAAAAAAAIEAoAjEAAAAAAAAgQHoLOQAAAAAAAAAAQALCAQ0KABIJCQAAAAAAAEJA+gMA8gUJCQAAAAAAAPA/YgCKASMSHQoIMnVzYzU2cWwSEVoEEgA4AaoCCGNxNHl3eGU0GgIIAcIBABJ6Cg1UZXh0X29qaHN0bWI4GAIiYhI9ChdOZXcgUG9zdCBvbiBGb3JKZXcgUGFnZREAAAAAAAA4QCgHOgYIgICA+A9ABnoKEghlcHA2ejVmdKgBAHISCQAAAAAAAAAAEQAAAAAAAAAA+gMA8gUJCQAAAAAAAPA/YgDCAQAYAyI0GgQQBSoAWh0JAAAAAAAAKEARAAAAAAAAPkAZAAAAAAAAKEBAAfoDAPIFCQkAAAAAAADwP2IAwgEA

### Context

Can't publish my app and test this page

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/ccc0e1c6-9d32-4621-b789-5fb855d852dc

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment]
@lovestar18 - The bug report code provided above is invalid, and it's not possible to access the project. Please provide us with the project link and specify which page in the project we should refer to. Alternatively, you can set up the issue steps in a blank project and share the details with us. Once we have these details, we can begin investigating the issue. Thank you.
