### ISSUE TITLE
App crashes in live environment

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2529]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app crashes in live environment - can visit 3-4 pages and then it fails

### Expected Behavior

App doesn't crash

### Steps to Reproduce

I can add you as a test user if you'd like

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Cg9CdXR0b25fbTZsdDVwczMYCSLcAUqzAQoyCgdDb25uZWN0EQAAAAAAACxAGgZPdXRmaXQoBDoGCP////8PQAZ6ChIIbGtkNGh0cDEZAAAAAAAAAEApAAAAAACAUUAxAAAAAAAAQkA5AAAAAAAAIEBJAAAAAAAA8D9SAhABWgIIAHIvCQAAAAAAACBAEQAAAAAAACBAGQAAAAAAACBAIQAAAAAAACBAKAIxAAAAAAAAIEDCARYKCQkAAAAAAIBRQBIJCQAAAAAAAEJAWgs5AAAAAAAAAABAAogDAvoDAPIEBAoCCgDyBQkJAAAAAAAA8D9SIAoNEAcaBwoFdXNlcnMgABINCgcKBXVzZXJzKAEwAToAYgCKAcsBEsQBCghhMXZha3AwZhKGASJ5EncSUgpQCglmb2xsb3dpbmcSQwoLCglmb2xsb3dpbmcqNAgDGjAKCwoJZm9sbG93aW5nMiEIBEICEgBKBYIBAhABggERCg9CdXR0b25fbTZsdDVwczMaIQgEQgISAEoFggECEAGCAREKD0J1dHRvbl9tNmx0NXBzM6oCCHA0djh6eTl5Ki8KCDJuM3ViendpEiOqAgg5YjU4MXJmbfICFRABKhEKD0J1dHRvbl9tNmx0NXBzMxoCCAGSAQcwj6z01IgwwgEA

### Context

Prevents me from publishing my app

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/0cdc43f3-b39e-47a2-abcf-afaaabb2d429

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment]
Hi @lovestar18 - The bug report code provided above is invalid. It's unable to fetch the project details. Please provide the correct code. Additionally, please verify the build with the latest FlutterFlow release from yesterday and see if you're still experiencing the issue. Thank you.

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! I have re-pushed the app and will circle back with you. Here's the bug code IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCgofePtOol3evWkbVVWYOmkd1FpMUSmmnkFpfD4v9/UFfI5Cw2tRqZazbVqewKWXjqWe5OBPKW0OWpCEcZMCWam37W3qx1+WdNhWlon2DiEGO/KVnftO5zVImdISq/LZO4=

**Comment by lovestar18** [comment]
@hariprasadms - confirming the app still crashes pretty quickly. I just re-pushed app to deployment yesterday and tested now. Here is the result:


https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/326fe662-1435-44b9-9303-2ee75e0003cc

**Comment by hariprasadms** [comment]
Have you got crash report to share ?

**Comment by hariprasadms** [comment]
Still above code is not working ?

**Comment by lovestar18** [comment]
Hi @hariprasadms - confirming it is not working. Here's what I see in my crashlytics dashboard - is this what you're looking for?

Thank you!

<img width="957" alt="Screenshot 2024-03-18 at 4 49 24 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/143e9c36-3ca1-45ad-845a-50b757562c25">
<img width="663" alt="Screenshot 2024-03-18 at 4 49 37 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/d43fddab-2223-4ad7-9bd5-82e39a5b51a4">

**Comment by leighajarett** [comment]
Hi @lovestar18 , so sorry for the delayed response here! 

Can you please reach out to our support team - support@flutterflow.io? This seems like a project-specific error and without steps to reproduce from a blank project we are unable to fix this issue. 

Our support team can help troubleshoot and figure out if there is anything misconfigured in your specific project. Thanks so much!
