### ISSUE TITLE
Mobile Deployment inconsistently failing to start

### ISSUE THREAD

**Issue by staplKody** [FlutterFlow/flutterflow-issues#2531]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying my flutterflow project to the Google Play Store or the App Store, I sometimes get an error pop up that says either "Build Failed" or "Error updating service account info"

![Screenshot 2024-03-14 120637](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bb388281-e003-4dd7-9764-6815f8f7574e/b653f436-9ed9-4426-ad4c-e3d05e380166?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYjM4ODI4MS1lMDAzLTRkZDctOTc2NC02ODE1ZjhmNzU3NGUvYjY1M2Y0MzYtOWVkOS00NDI2LWFkNGMtZTNkMDVlMzgwMTY2IiwiaWF0IjoxNzEwNDQ5NzYyLCJleHAiOjMzMjgxMDA5NzYyfQ.ds-CkoMjN7-qySvGKoI0N61flIqdCcCsOae7-cFmazQ)

If I just keep trying it for a few minutes, it eventually works. It is not consistent.

### Expected Behavior

Typically, the status would set to submitted and then queued before providing some error via the codemagic output. That is if there is an error at all.

### Steps to Reproduce

Not sure if reproducible in other projects, but I am just building in mine. It doesn't appear consistently so it's not a guarantee to happen.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcjfsMx2rsdY17X5be5Fv2UUQlAgTL03pu0bFEggGLbrBIYMac7CV1hoYOmnTVVbKEWL8T4fwMrXjtj1IMYFFzuCG6pS+s9+ewLgRn6/aoSmEKuoVGhAHp5UN0yA38HYnxJ7APthWGQN2lz2euu9bA/qN734Zwh9f6PHaOI=

### Context

It's only began since the last major update when the local run was added to the mac OS app. I am working in flutterflow as a PWA on a windows 11 machine. It's not a breaking problem, but I would suspect that not many people care to report it if it's as inconsistent for them as it is for me. As long as I keep trying to deploy, it eventually succeeds.

### Visual documentation

![Screenshot 2024-03-14 120637](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e9e9f844-c821-44b9-93ae-0a3ec4e40aeb/68d16f5f-ad86-464d-8f6a-04f9a1927dd2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lOWU5Zjg0NC1jODIxLTQ0YjktOTNhZS0wYTNlYzRlNDBhZWIvNjhkMTZmNWYtYWQ4Ni00NjRkLThmNmEtMDRmOWExOTI3ZGQyIiwiaWF0IjoxNzEwNDQ5NzYyLCJleHAiOjMzMjgxMDA5NzYyfQ._MLpesVcTV-HOmC_-kR2WpF1xxamjuSCyy-NFd7FaSc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: V4.1
- Platform: Web app added to my desktop as a PWA
- Browser name and version: Chrome 122.0.6261.112
- Operating system and version affected: Windows 11 Version 23H2
```

**Comment by drpark** [comment]
same here with Playstore

**Comment by rzambroni** [comment]
Hey @staplKody, so sorry you were experiencing this issue and for the delay on this answer. Could you confirm if you are still having troubles with it? It is coincident with some problems on CodeMagic around the time you filled this ticket and it was likely solved when their service normalized.

Please let us know! thanks!

**Comment by staplKody** [comment]
I believe it was fixed after the whole code magic outage. It may have been an edge case on their side since it was happening for weeks before that outage happened. I haven' had any troubles in the last week or so.

**Comment by rzambroni** [comment]
Good to hear,

Thanks for letting us know!

**Comment by lapms** [comment]
We are still experiencing this issue as of today/

**Comment by Bobarinn** [comment]
Same here, couldn't publish to both App store and Play Store.

Error for the App store says "Failed to start build" and that of Google play say "Error updating service account info"

Don't if the two errors are related but I noticed them at the same time.

@rzambroni 

<img width="342" alt="Screenshot 2024-05-20 at 8 38 05 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/89941176/3f2d45ab-ad3b-4c26-9550-18290e707993">


<img width="455" alt="Screenshot 2024-05-20 at 8 38 33 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/89941176/a8a42ba8-d099-4652-96a6-c5c3e38d4d39">

**Comment by glnmahsun** [comment]
same from me, a deployment issue for play store is definitely exist for couple of hours. " Error updating service account info. " . it needs a quick fix

**Comment by Al-Mishkat** [comment]
Same Here , a deployment issue for play store  " Error updating service account info. " .

**Comment by HJPittham** [comment]
Also here with App Store deployment 'Failed to start build'

**Comment by boomriderrrr** [comment]
Same here 
App Store
<img width="502" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143303728/cead24b9-e06a-4fd8-a384-71c385e3f9aa">

Google Play Store
<img width="502" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143303728/11856c4d-dae3-445f-8aad-6b82f4fa6abe">

**Comment by youssefabouelneaj** [comment]
Same here

**Comment by SimonNewM** [comment]
Same here..

**Comment by manni-io** [comment]
Same here...

**Comment by Madv010** [comment]
same issue

**Comment by staplKody** [comment]
I'm going to assume that since this has gotten so many comments in the last hour that CodeMagic has had some issue today haha.

**Comment by sntre** [comment]
same issue here on all my projects
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83634953/8f318344-b085-4bea-907d-7f3b86c4d3cc)

**Comment by Alexandre-Lemyre** [comment]
Same here

**Comment by devkaleo** [comment]
Same here
