### ISSUE TITLE
Toggle Icon Does not accept "Document exists" as boolean for the conditional

### ISSUE THREAD

**Issue by stefanuntura** [FlutterFlow/flutterflow-issues#2534]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding the widget "ToggleIcon" and trying to pass a conditional for the trigger as "Document exists" an error is generated by flutterflow

The error states - only booleans or list contains allowed

More Context: Why do I need this? I am trying to implement the functionality that the toggle icon changes the icon based on if a friend invite document for this user exists or not (in a ListView)

### Expected Behavior

Expected: Expect the "Document exists" to be handled as a valid boolean within the ToggleIcon, as it is handled in conditional actions just fine

### Steps to Reproduce

1. Create a toggle icon anywhere
2. Query a document or list of documents from a Firestore database
3. Set the toggle icon conditional to "Document exists" field of a queried document from the Firestore database

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehcj1z4ZNj71J17XuaO1apwMwQFg5U+cZkdV8TRIbfe/4E5otOs/sbldBTeazaHx+GkyWrHkCp9rzhuHpDfdfIQSbG5w7zatiExPPbGW7V8jXCpCSVXxDFtJXCFeP4ZirsSJ5NfpicXA63DuIBOm/az2Cf9qOYwx5e6fDbOY=

### Context

More Context: Why do I need this? I am trying to implement the functionality that the toggle icon changes the icon based on if a friend invite document for this user exists or not (in a ListView)

### Visual documentation

![Screenshot 2024-03-15 at 12 39 41](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6e76a47-2ed2-4711-a09b-3ed2f905bab3/6dc36461-ae61-4db9-86fb-4a039edeff53?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNmU3NmE0Ny0yZWQyLTQ3MTEtYTA5Yi0zZWQyZjkwNWJhYjMvNmRjMzY0NjEtYWU2MS00ZGI5LTg2ZmItNGEwMzllZGVmZjUzIiwiaWF0IjoxNzEwNTA5NjEzLCJleHAiOjMzMjgxMDY5NjEzfQ.aGy4d4FUp41GO7hsI7GVdt40xNcNS4ZMs2QJIAW2LqU)

![Screenshot 2024-03-15 at 12 40 01](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/116a0e3a-9cf6-4edc-ab25-b6cdfc152a5c/2dcf984b-3b23-43a7-ab4d-4ff33980d07c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMTZhMGUzYS05Y2Y2LTRlZGMtYWIyNS1iNmNkZmMxNTJhNWMvMmRjZjk4NGItM2IyMy00M2E3LWFiNGQtNGZmMzM5ODBkMDdjIiwiaWF0IjoxNzEwNTA5NjEzLCJleHAiOjMzMjgxMDY5NjEzfQ.HpYZUOAAkqxfpwRjeBnySzuL0xWpD0FfBFjEY_ZCWI0)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 - flutter 3.19.1 (old version had same error/behaviour)
- Platform: Mac and windows (Chrome browser)
- Browser name and version: Chrome latest
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @stefanuntura - Thank you for submitting the issue. The current design of the toggle icon has a few limitations in its functionality. In your use case, the best option is to utilize a conditional widget and display the widgets based on the conditions. It's easier and more convenient to handle this way. I hope it works for you. Thanks

<img width="339" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/9ba946e0-adc0-407e-a179-af1fa9c3c809">
