### ISSUE TITLE
Markdown widget doesn't show images from storage

### ISSUE THREAD

**Issue by davood-flutterflow** [FlutterFlow/flutterflow-issues#2536]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

You can't show an image from Firebase storage in Markdown widget. User reported that it was working fine before the last update.

Markdown show the other images.

The image that markdown doesn't show it, could be shown in a normal image widget

Note: You can see the image in markdown in the editor, but not in test or run mode or published web app

### Expected Behavior

as the image URL from Storage is a public URL it should shown in markdown like a normal image URL

Image from storage: [https://firebasestorage.googleapis.com/v0/b/intercom-openai.appspot.com/o/users%2F2gxNEL8vCPbmMFz10MYVlzDIgTr2%2Fuploads%2F1708897273057000.jpg?alt=media&token=54f35410-d3b1-4fe6-a750-4f4506e0a506](https://firebasestorage.googleapis.com/v0/b/intercom-openai.appspot.com/o/users%2F2gxNEL8vCPbmMFz10MYVlzDIgTr2%2Fuploads%2F1708897273057000.jpg?alt=media&token=54f35410-d3b1-4fe6-a750-4f4506e0a506)

### Steps to Reproduce

try to show an image in markdown widget from firebase Storge url

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Si/Lqw412sbQD1pSJKsJVnj4vKVs7bZIrmOtqEBcbIu/1OpYtXOmmSFRuQtOmTFc2M1mKgTsx/v+KkdzIN8Y6Ok+cGpxxypdqbRWVXkCgV8msDs+7dHxtJNpKCBGH0p6J2xVvOrZsWHgN3zqYJfO9F3HtGLroO20/MMikJrPJnXfuQ0SLb3kNh1JWeC/v

### Context

Support report.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/67bfff91-5990-4344-872c-cea87f242e81/6a613df2-df06-421a-86cb-5573f76ab889?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82N2JmZmY5MS01OTkwLTQzNDQtODcyYy1jZWE4N2YyNDJlODEvNmE2MTNkZjItZGYwNi00MjFhLTg2Y2ItNTU3M2Y3NmFiODg5IiwiaWF0IjoxNzEwNzY2Njk5LCJleHAiOjMzMjgxMzI2Njk5fQ.qb2VAuTOdexh8IHNOrCr391if2Mu-ZxO1bLKc7rUNXI)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d26d29fb-971d-4fb4-8cbd-9e9122e3e2e4/0257e625-432d-4e79-88ee-51a7caae4a02?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMjZkMjlmYi05NzFkLTRmYjQtOGNiZC05ZTkxMjJlM2UyZTQvMDI1N2U2MjUtNDMyZC00ZTc5LTg4ZWUtNTFhN2NhYWU0YTAyIiwiaWF0IjoxNzEwNzY2Njk5LCJleHAiOjMzMjgxMzI2Njk5fQ.zw2wr5FCIjicPQSqooOrF-005livj_m6tmuf2gg4K68)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/374d8b3a-0957-4088-9ef7-31e8429b1e15/1460f2f6-ebb0-43e2-b37d-058d8cf3a6d9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNzRkOGIzYS0wOTU3LTQwODgtOWVmNy0zMWU4NDI5YjFlMTUvMTQ2MGYyZjYtZWJiMC00M2UyLWIzN2QtMDU4ZDhjZjNhNmQ5IiwiaWF0IjoxNzEwNzY2Njk5LCJleHAiOjMzMjgxMzI2Njk5fQ.ChPH_HwF-td2Eag-4_9ucEjBHYAvZNMrVEoLZvR5oys)

### Additional Info

Project URL: [https://app.flutterflow.io/project/markdown-widget-test-hnndty?tab=widgetTree&page=HomePage](https://app.flutterflow.io/project/markdown-widget-test-hnndty?tab=widgetTree&page=HomePage)

Reproduced here

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web chrome
- Operating system and version affected: v4.1 released March 14, 2024
```

**Comment by ArturWitos** [comment]
This error happened to me in my project. If you have any questions, I am available to help.

**Comment by victoriahuang1** [comment]
@ArturWitos can you check whether you have set up the CORS configuration on the Firebase storage side?

**Comment by ArturWitos** [comment]
Yes, together with [davidflutterflow](https://github.com/davidflutterflow) we configured. And only in Markdown it doesn't work. The same Firebase Storage images work, but in other widgets, for example image.

**Comment by victoriahuang1** [comment]
@ArturWitos it looks like this is a parsing issue on the markdown widget side. It's being parsed into this: `"https://firebasestorage.googleapis.com/v0/b/intercom-openai.appspot.com/o/users/2gxNEL8vCPbmMFz10MYVlzDIgTr2/uploads/1708897273057000.jpg?alt=media&token=54f35410-d3b1-4fe6-a750-4f4506e0a506"`

Notice how it work when you try opening this link.

But the original URL does: `https://firebasestorage.googleapis.com/v0/b/intercom-openai.appspot.com/o/users%2F2gxNEL8vCPbmMFz10MYVlzDIgTr2%2Fuploads%2F1708897273057000.jpg?alt=media&token=54f35410-d3b1-4fe6-a750-4f4506e0a506`

This would need to be fixed on markdowns and unfortunately. In the meantime, though, you can try creating a different URL (like tools to shorten URLs).
