### ISSUE TITLE
Convert to Component and Save as Template wont focus on name input

### ISSUE THREAD

**Issue by CorySavit** [FlutterFlow/flutterflow-issues#2537]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Both Convert to Component and Save as Template wont focus on the name input box and so you can't give the component a name, so you can't finish either action.

That is to say, when you right click on a component, you are able to choose Convert to Component from the dropdown menu, but you can never actually create one since you can't enter a name in the textbox.

### Expected Behavior

give a component a name and create it

### Steps to Reproduce

1. create new project
2. add some widgets to the tree
3. right click on any component/widget in any page
4. choose "Convert to Component"
5. try to type in a name in the text box
6. be really sad

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4el/HLuJdgoeZE7c+BYMZR/TsRKUg8aIIziutudAwjIYDrO7QqfOj+QHZVOMO/dFY3OlmI8XoJzNbXuIbuG8IXPiiAfLpawbh+Fwz/QnGRV7KgDquWSWsmP8ZmIXGHzbeK2hZ4JtFZdGQ77VyYHfC9ShLsHqLaDlQ7Q///MtvJpAqrKhzOXn0Jg1ZSfCvr

### Context

I can't create components!

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/688c4902-8fec-4c36-960b-da9333528208/b9da374b-b821-4860-9f2c-2184900bc1e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ODhjNDkwMi04ZmVjLTRjMzYtOTYwYi1kYTkzMzM1MjgyMDgvYjlkYTM3NGItYjgyMS00ODYwLTlmMmMtMjE4NDkwMGJjMWU0IiwiaWF0IjoxNzEyMDMyMjIzLCJleHAiOjMzMjgyNTkyMjIzfQ.vcOF3jOtxa7KWxVrsm1SnYRhekexaP912BPfDDhTcD0)

all I can really show is the input box that will not allow focus, and therefore won't allow creation of a component

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Brave Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)
- Operating system and version affected:
Windows 11
```

**Comment by kiwimagic** [comment]
I have exactly the same issue. Can not create custom component or save something as a Template. Text field to enter name of new [component/template] will not allow focus/data entry. I am on MacOS desktop App. appears to be same as reported here #2387 and here #2451

**Comment by CorySavit** [comment]
@kiwimagic thank you for finding those related tickets.
I SWEAR I searched and could not find anything, but then again it was also the end of the work week and I was exhausted. Again, thanks.

**Comment by CorySavit** [comment]
@hariprasadms it may be a duplicate, and the other ticket may say closed, but I assure you the problem still exists. In the closed thread it says that it will be fixed in the next release, [posted 5 days ago](https://github.com/FlutterFlow/flutterflow-issues/issues/2387#issuecomment-1988751101), but I had multiple "new version of flutter flow please refresh" messages since then and the issue has not been fixed. Is it only going to happen in the next major release? If so, any timeline on when that will be? Closing the ticket before the issue is resolved on the customer end isn't helpful.

**Comment by BernhardRitz** [comment]
Problem still exists - I can't assign a name to the new component, because the focus is on an element in the background. This is not just a nice to have feature - would be great if somebody fixes this. Thanks.

**Comment by Jodebjo** [comment]
This needs to be fixed soon please, We pay a lot for the product and can't use it.
It has been broken for at least 2 weeks now.

**Comment by leighajarett** [comment]
[Screen Recording 2024-04-05 at 1.45.46 PM.mov](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dd22bc5e-a027-4296-8a87-4a2175068094/8a2c21bf-4f79-4f45-ad7b-6cd948e467c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZDIyYmM1ZS1hMDI3LTQyOTYtOGE4Ny00YTIxNzUwNjgwOTQvOGEyYzIxYmYtNGY3OS00ZjQ1LWFkN2ItNmNkOTQ4ZTQ2N2M2IiwiaWF0IjoxNzEyMzM5MjU4LCJleHAiOjMzMjgyODk5MjU4fQ.tR5QwwjRcz_UNcCL3bYrXKTVYxDwmbNQ_jYwzq59WhA)

Hi there! First of all, I'm so sorry you're facing this issue! That sounds really frustrating!

 I tried to reproduce this issue but it seems to be working for me. Can you confirm you're still facing this issue?

Also, if you try to create a component from the right hand side panel, are you able to do so, or do you still have an issue with focus?
