### ISSUE TITLE
FlutterFlow side nav jitters on overscroll for desktop app

### ISSUE THREAD

**Issue by nunezal** [FlutterFlow/flutterflow-issues#2538]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow settings side navigation menu jitters on overscroll for desktop app

### Expected Behavior

The overscroll shouldn't jitter, just bounce back once.

### Steps to Reproduce

Open desktop app
Make project and overscroll on any left side nav menu

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grtcC+s7qcu1QhQIgQ0QnU7gnlO1ucx4bCOvvEO0hdcmkQ0NKQsSrdH4/DlSYnlMG7v/Fk+zlCMEFB0usQbpe0JVATQ/MeFqlMKazPJeKVHx7GcJbGkCj5J+zviNQBMFfLkYnwGWlNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Just a UI bug. Not a major issue. Just letting you know

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1beea8b1-ea79-4f95-99b7-f7d71c497667/ec44abb0-9702-496d-9433-934dd1b6d13c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYmVlYThiMS1lYTc5LTRmOTUtOTliNy1mN2Q3MWM0OTc2NjcvZWM0NGFiYjAtOTcwMi00OTZkLTk0MzMtOTM0ZGQxYjZkMTNjIiwiaWF0IjoxNzEwOTMwMzQ0LCJleHAiOjMzMjgxNDkwMzQ0fQ.v-xCX0xufvZf1kkosV0l-QyiB-uOPMqMloan7RPHMnE "=319x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hey @nunezal, Thanks for submitting the issue. Could you please clarify which OS you are referring to on desktop?Additionally, what exact behaviour are you experiencing? It would be helpful if you could share a quick video clip. Thanks!

**Comment by nunezal** [comment]
I have a mac Version 13.3.1 (a) (22E772610a)

<img width="491" alt="Screenshot 2024-03-19 at 7 33 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/36378251/b91a766f-6b4a-4778-b657-2d91c197dab4">

https://github.com/FlutterFlow/flutterflow-issues/assets/36378251/49f0fc38-472a-4e6d-abc7-2cf4d2a9e7a9
