### ISSUE TITLE
Initial Value from a Text Field is not working with Supabase

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#254]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Load the Initial Value from a Supabase Row

## Current behavior (required)

When the page is loading the app crashes.

## To Reproduce (required)

1. Put some widgets
2. Do a Backend Query using Supabase
3. Add a Text Field
4. Set an Initial Value from the Supabase Row created recently
5. Try to build the app and show an error

### Bug Report Code

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBay0jF7KuDLMqY8/RVERCQtPjY3xAJUyWq2oW3PeOufHPIfIEPUuZfb0/zqtqSQ/JZHitbpCyU/HUACkbeacOQSj6

## Context (required)

When the user wants to change a value, for example the phone number, I want have a Text Field with the actual number as Initial Value

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/208832146-51b2edac-22fa-4ad8-b94d-3c7588195ec3.png)

## Your environment

* Version of FlutterFlow used: December 16 December
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by Franco98404** [comment]
Any news about this problem? @agreaves @bulgariamitko @wenkaifan0720

Now we can't build the app by this bug

**Comment by bulgariamitko** [comment]
Can you try this on a brand new project as well just to make sure you have the same experience there as well?

**Comment by Franco98404** [comment]
Yes, I have the same experience

![image](https://user-images.githubusercontent.com/36147203/209409915-52cf2c81-c0bf-469d-b711-d70cc3d07034.png)

**Comment by wenkaifan0720** [comment]
As the error message states, the variable `columnSchoolRow` is not defined/could not be found. Where did you define it?

**Comment by Franco98404** [comment]
I didn't change the name of the column, that is the problem, for some reason is changed automatically

Here is the link of the project:
https://app.flutterflow.io/project/test-o7tv5e

**Comment by agreaves** [comment]
Hey @Franco98404, thanks for the report. I've identified the issue, it's definitely a bug on our end. This will be fixed on our next deploy!

Thanks for all the other bug reports by the way, you've helped us catch a lot! And by that I mean sorry the inconvenience 😅. We previously deployed today with all other bug fixes (not including this one), so the rest of your GitHub issues should be fixed if we've closed them. Thanks again!

**Comment by Franco98404** [comment]
Thanks for answering and fixing the bugs!

By the way, in the same way as this "issue tracker" is very helpful for FF team and the community, a "feature request tracker" and an "update tracker" would be nice!
In our case it is very important to know when the next FlutterFlow update will be released, the same way with the feature request it should be nice know what feature the FF team are working on. At the end of the emails usually you say the next features you are working on, but are major features, some "minor" features are not included and I would like to know too!

Hope you read this and happy holiday!
