### ISSUE TITLE
LocalRun not synching with remote application

### ISSUE THREAD

**Issue by Netkomm** [FlutterFlow/flutterflow-issues#2540]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

LocalRun starts with an old version of a project and will not synch with the current version available on servers.
However it does synch instead the local version to the server and by doing that erasing whatever modification was made.
At the moment LocalRun has stuck with a 2 days old version of the app on device.

### Expected Behavior

Sync realtime with the server (two-ways)

### Steps to Reproduce

just use LocalRun on a project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzMmBw5RPvsdc1871bcZGlj87H0Q6TL07ttYbZxUjIuPtBJh/e8jOTFZVcMPkYWlhHGD88UkF+NbPjYTtUPQEKSidGbpOzpF2EzvdXXq8RrqvC5COY3B7P8JbFWKl4KSRvhVvNtJZL3gb1E2qGujKaDbYGZ+/Zwh9f6PHaOI=

### Context

it messed up my project - but I saved on remote before using LocalRun so I had a recovery point.
for now I uninstalled LocalRun

### Visual documentation

none available

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Mac M1
- Browser name and version: Chrome 122.0.6261.129
- Operating system and version affected: Sonoma 14.3.1
```

**Comment by aculebrasj** [comment]
hey, I just lost all the advances I made in the last week in my app due to this and I'm seeing the very first version of the app, is there any way to revert it? @agreaves

**Comment by tomkosmita** [comment]
I have the same situation.
some symptoms:

1. In my case the project with issue is like **12 months old** so It went via issues with most of the upgrades (just mentioning crazy issues with branching).@aculebrasj @Netkomm - is your project as old as mine?
2. **Team work** - I'm on teams version - It might be that it messed up when other teammates  started to work on the same 

what I tried:
- reconfiguration - did not help
- reinstall - did not help

Local version got stacked with changes, I'm nut using it as it messes up my original app - it looks like it can not 
 - apply correctly merge action
 - pull latest code
Below what I see on the status part - might it be connected?

**Happy to grant access to my project to the FF developers**

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/152166542/7172cf1a-f2c3-4757-b919-c05707333dd2)

cheers
Tom

**Comment by sbis04** [comment]
Thanks for bringing this issue to our attention. Did you have the FlutterFlow MacOS app or have been using the MacOS app actively before using Local Run?

**Comment by tomkosmita** [comment]
> Thanks for bringing this issue to our attention. Did you have the FlutterFlow MacOS app or have been using the MacOS app actively before using Local Run?

I wasn't using it actively. 
It was my first use of mac app since more than 6 months. 

I was using GitHub + android studio for local runs. 

Very unlikely I guess but Might it be that this setup interfere with new app?

**Comment by sbis04** [comment]
Got it, my assumption is that it's a FlutterFlow MacOS app issue and not at all related to Local Run. Just to give more context, Local Run can only export code and run it on the selected device, it's not possible for Local Run to write back to the project.

@tomkosmita did you check if you were on the latest FlutterFlow macOS app? Can you share a screenshot of the app version? (you can find the exact version from MacOS top bar > FlutterFlow > About FlutterFlow)

**Comment by tomkosmita** [comment]
I was using version that i downloaded on 13th of march. 
And installed it over the following weekend. 
I can install it again today to test and get back with feedback to you

**Comment by tomkosmita** [comment]
@sbis04 
Perhaps realted hint.
Since using the app I'm occasionally getting this error:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/152166542/ab862c54-5cd7-44ad-bcb6-2640737dc51a)

I've never seen such before
"93 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...  "

As I was checking with other teammates they do not see it - might it be because I messed up something with the app?

Just a guess

**Comment by leighajarett** [comment]
Were you able to test it again?

**Comment by leighajarett** [comment]
Closing for now but please re-file if you run into this again
