### ISSUE TITLE
Clicking Logout leads to settings page

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2542]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click logout - it takes me to the settings page and doesn't log me out of the app

### Expected Behavior

Clicking 'log out' will take me to log out as that's how the action is setup

### Steps to Reproduce

1. Test the app
2. Click on the three line menu button, opening the end drawer
3. click logout

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCsofePrOpkAf8/7UFtUOOKoYXNiMFmZmn0X/MmNiuHPIfI7FzOBRrk6zJABEw6UTlGVRKqYOq63b0ZPGZ5NGECby7ejuR1TOsBhdCEF1E6MPOvJYBDcQ6ayDEg/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Can't log out of the app and test sign in

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/e0862ec8-1f21-49be-8bb9-82a1e46c173c

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hey @lovestar18 - I looked at your project. I see that you got two actions for logout component. See below. correct it and it should work fine.

<img width="1472" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d341d280-f359-4d49-aa20-ca2c17076beb">

**Comment by lovestar18** [comment]
Thank you @hariprasadms ! My apologies!
