### ISSUE TITLE
Container Max Width doesn't work inside the ListView

### ISSUE THREAD

**Issue by b-arte-k** [FlutterFlow/flutterflow-issues#2543]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Max width is NOT working for Containers inside ListView.

### Expected Behavior

the width and max width should be recognized

### Steps to Reproduce

1. create new page
2. add ListView
3. Inside ListView add a container
4. set up Width to 100%
5. set up Max W to 500 px
6. Run test mode
7. Switch between phone/tablet/PC view and see that max width is NOT working

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gotsC+qnTbsZQhQIgQ0QnU7gnlO1ucx4aG7GrPaQueM+laUNKTuLmd1BqA0yZ+Hw1wamKvfL9KME7EzusfpRM0JVAcQLNUk6jVLagPKW0S3x6I91hfG690J7V3B4lGNFZSiEi32GHNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I wanted to set up max width for some containers inside ListView

### Visual documentation

Not necessary as this issue is simple to reproduce

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: web
- Browser name and version: Opera
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @b-arte-k - Thank you for submitting the issue. In the ListView widget, the Container widget by default takes the entire available width, and the width and max width sizes are not affected. To see the given width size in effect, you should wrap the Container inside a Column or Row widgets. 

Alternatively, if you want the Container to take the width of its child widget and not the width of the ListView, you can use Align or Center widget as the parent of the Container.
