### ISSUE TITLE
MissingPluginException when adding phyllo_connect` to FlutterFlow

### ISSUE THREAD

**Issue by vedantatech** [FlutterFlow/flutterflow-issues#2544]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The plugin is causing a MissingPluginException, indicating that it is not properly linked or recognized by the FlutterFlow environment.

### Expected Behavior

The plugin should be recognized, and no MissingPluginException should occur after adding it through the FlutterFlow UI.

### Steps to Reproduce

1. Create a custom action with the below code
2. Add the pubspec depndencies (phyllo_connect: ^0.3.5)
3. Add custom action to a page
4. Click test and then click the button

```
// Automatic FlutterFlow imports
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// Additional imports for Phyllo Connect and logging
import 'package:phyllo_connect/phyllo_connect.dart';
import 'dart:async';
import 'dart:developer' as developer;

Future<String> connectWithInstagramFlutter(BuildContext context) async {
  // Assuming these values are retrieved securely from your server/environment
  final String clientId = '------------------';
  final String clientSecret = '------------------';
  // The user ID and token should be dynamically obtained from your backend
  final String userId = '------------------';
  final String sdkToken = '------------------'; 

  final _phylloConnect = PhylloConnect.instance;

  Map<String, dynamic> config = {
    'clientDisplayName': 'Vedanta tech',
    'environment': 'sandbox', // Change to 'production' as needed
    'userId': userId,
    'token': sdkToken,
    'workPlatformId':
        '------------------', // Replace with actual Instagram ID from Phyllo
  };

  String result = "Initialization Failed";
  try {
    _phylloConnect.initialize(config);
    _phylloConnect.open();

    // Setup callback listeners
    _phylloConnect.onConnectCallback(
      onAccountConnected: (accountId, workPlatformId, userId) {
        developer
            .log('onAccountConnected: $accountId, $workPlatformId, $userId');
        result = "Success: Connected with account ID: $accountId";
      },
      onAccountDisconnected: (accountId, workPlatformId, userId) {
        developer
            .log('onAccountDisconnected: $accountId, $workPlatformId, $userId');
        result = "Disconnected: Account ID: $accountId";
      },
      onTokenExpired: (userId) {
        developer.log('onTokenExpired: $userId');
        result = "Error: Token expired for user ID: $userId";
      },
      onExit: (reason, userId) {
        developer.log('onExit: $reason, $userId');
        result = "User exited: $reason";
      },
      onConnectionFailure: (reason, workPlatformId, userId) {
        developer.log('onConnectionFailure: $reason, $workPlatformId, $userId');
        result = "Connection Failure: $reason";
      },
    );
  } catch (error) {
    developer.log('Error initializing Phyllo Connect: $error');
    result = "Error initializing Phyllo Connect: $error";
  }

  return result;
}

```

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9254607e-1245-43ba-8973-4c13ce3b601a/eafc733b-b7ed-4473-9842-9d9e0d56e0f9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MjU0NjA3ZS0xMjQ1LTQzYmEtODk3My00YzEzY2UzYjYwMWEvZWFmYzczM2ItYjdlZC00NDczLTk4NDItOWQ5ZTBkNTZlMGY5IiwiaWF0IjoxNzEyMzM5MDQwLCJleHAiOjMzMjgyODk5MDQwfQ.yfuIY2f1DllqXdOSeF2BqHFVtf_2H8hdKB85-djOZF0)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhc/qy5d1m8tK7q6JL8FKhjwXQzIcTeU30+thcw4bI+OvEIYqYvT7QFRWSOqHfH5mAE6LhmoFw6iPuM7tGO46NgStfLZiycxXUxDgRjqlMqqNCKiKfnBAHfJNGhWg5LSV2RV+WfhsdHgW702hOOyQa3qCf9qOYwx5e6fDbOY=

### Context

I'm trying to integrate the phyllo_connect plugin into a FlutterFlow project, but I'm encountering a MissingPluginException. I have followed the steps to add the plugin as per the example provided on pub.dev but have been unable to resolve this issue due to the limitations within FlutterFlow's environment.

### Visual documentation

[https://docs.getphyllo.com/docs/api-reference/connect-SDK%2Fmobile%2Fflutter-SDK-integration](https://docs.getphyllo.com/docs/api-reference/connect-SDK%2Fmobile%2Fflutter-SDK-integration)

Here is the pub.dev guide: [https://pub.dev/packages/phyllo_connect](https://pub.dev/packages/phyllo_connect)

### Additional Info

A few other people facing similar issue
[https://community.flutterflow.io/ask-the-community/post/how-to-implement-custom-action-that-require-pub-dev-import-r5XpTnau2JgOaIZ](https://community.flutterflow.io/ask-the-community/post/how-to-implement-custom-action-that-require-pub-dev-import-r5XpTnau2JgOaIZ)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web and Android
- Browser name and version: Chrome Latest
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @vedantatech - Thank you for submitting the issue. The error you are encountering is expected when you try to run in web mode. Test debug, and run modes eventually use web run mode. The package you are trying to use is compatible only for iOS and Android modes. Therefore, you should test on device simulators and real devices. This is not a bug.
