### ISSUE TITLE
Textfield autocomplete gets stuck while using Algolia search for its "autocomplete options"

### ISSUE THREAD

**Issue by zobansro** [FlutterFlow/flutterflow-issues#2545]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

whenever I use the combination of textfield widget with autocomplete option on and algolia result to populate these autocomplete options I get following behaviour:

1. User starts typing
2. After relevant update delay (say it is set to 1 sec.) nothing happens and the debugging console gives the error "refused to set unsafe header "user-agent"
3. user starts typing again and again after the delay the autocomplete options finally show up.

### Expected Behavior

The autocomplete options should appear the first time the user stops typing.

### Steps to Reproduce

1. insert textfield widget
2. set a backend query with algolia search that will use this widget's state as the search term
3. turn the autocomplete option on
4. turn the update component on text change on
5. set update delay to 1000ms
6. use the algolia search result as "Autocomplete options" in autocomplete properties
7. test :)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cycr635ZOm9tK+KX6YPlavCAUHFw1RYJFmu1HeE0bJ5PNCJkQO8nTXFJWXf25dglAO038pH0e/tLGm9z2UcBdZDuCfap6z81qSz3MeDm5V6a2EaqNOH9uGshhN0PDyMPYkx5CJrJYLlIe2k+mJO+tYB7aQbrKNTMvBsqKLpnXrgfuQ0SLb3kNh1JWeC/v

### Context

I wanted to use this several times and always failed ending up using simple search. I want the users to search database in a simple, efficent and user freiendly way.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/135464703/6622ba30-2a6b-4edd-babe-28f6bfb21355](https://github.com/FlutterFlow/flutterflow-issues/assets/135464703/6622ba30-2a6b-4edd-babe-28f6bfb21355)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.
- Platform: web
- Browser name and version: Chrome
- Operating system and version affected: windows 10
```

**Comment by AnushaFF** [comment]
Hi @zobansro thanks for the bug report! As it turns out, the user agent message is actually more of a warning, and does not actually impact the search results. In your case, reducing the update delay should solve your issue.
Closing the issue for now, let us know if it persists!

**Comment by zobansro** [comment]
Hello AnushaFF. I hoped you would not dismiss it like that. Reducing the update delay is a workaround and not a very practical one: In order not to confuse the user, I would basically have to reduce the delay to 0 and this would drastically increase the usage of Algolia, rendering this feature useless for real-life applications. I hope you will eventually fix this and will continue to use simple search in the mean time. Best Regards. Michal
