### ISSUE TITLE
Bug Report Code is not generating using Brave Browser

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#255]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Generate the Bug Report Code

## Current behavior (required)

I can't generate the Bug Report Code, always appears this message
"Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)"
I have permission to the clipboard:
![image](https://user-images.githubusercontent.com/36147203/208833658-503d58e6-a378-48e7-8136-5d416381b388.png)

## To Reproduce (required)

1. Right click on a widget
2. Click on "Get Bug Report Code"
3. Now appears the problem

### Bug Report Code

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp14F/+j2ufLEU/I7GxCaR4R/1KoAVQyVeGahMqXfU/HUACkbeacOQSj6

Workaround: Use Chrome browser

## Context (required)

Generate the Bug Report Code

## Your environment

* Version of FlutterFlow used: December 16 December
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by bulgariamitko** [comment]
Just to double check sometimes when I try to report the bug I get the same error and then I try again and it worked. You have tried it a couple of times right? Have you try it incognito mode as well in Brave?

**Comment by Franco98404** [comment]
Yes, I tried a couple of times, I found a curious behavior, when I generate the Bug Report Code on Chrome and switch to Brave I can generate the Bug Report Code without problems.

I tried in incognito mode in Brave and doesn't work too.

**Comment by bulgariamitko** [comment]
I get the same behavior when I am using Chrome. The first time doesn't work, but the second time works.

**Comment by Franco98404** [comment]
Just to clarify, using Brave is imposible to generate the Bug Report Code, you can try a lot of times and you will get the same error. But if you switch to Chrome and generate the code and the returns to Brave again now it will work on Brave

**Comment by aemelyanovff** [comment]
I'm afraid we only officially support Chrome at this time. We make no promises that anything will work in Brave.

**Comment by Franco98404** [comment]
Still persist the error using Chrome

**Comment by bulgariamitko** [comment]
If you have the change to record a video and I will re-open this issue.
