### ISSUE TITLE
creating a text box assigning a value from a page parameter that accepts null.

### ISSUE THREAD

**Issue by kjsdad** [FlutterFlow/flutterflow-issues#2551]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

create a page add a text field, create a page parameter of type string and allow null provide no default value. assign page parameter to text field it will not allow you to without providing a default value. There appears to be no way to allow null when first assigning a parameter to a text field or provide a value for display/test purposes. work around: save it edit the field and remove the default value.

### Expected Behavior

The interface completely changed put back the functionality that existed during your state management flutterflow university video creation.

### Steps to Reproduce

1. create a page add a text field,
2. create a page parameter of type string and allow null provide no default value.
3. assign page parameter to text field it will not allow you to without providing a default value. There appears to be no way to allow null when first assigning a parameter to a text field or provide a value for display/test purposes. work around: save it edit the field and remove the default value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksjf35Rhpbxa1s/Ab8Br/WUsQlAmR5Iasct/cxQcB4j4PO0cYcj7QBBVOLGzaH5YeVKirHgF0dL6kfzuGsEFEzmYbL5qys5yTxPPbH+7R7a6BqrtdkQlL5hVJ0yl38GnrSVQWfFaSEIY7WCQJ+vJcz6Cf9qOYwx5e6fDbOY=

### Context

Null is a very important value and very different than empty string. When creating applications I save data to a sql database and null is a must.

### Visual documentation

NA

### Additional Info

na

### Environment

```markdown
- FlutterFlow version: 4.1. 3.19.1
- Platform: MacOS Desktop: web
- Browser name and version: microsoft edge 122.0.2365.80 ARM
- Operating system and version affected: Sonoma 14.4
```

**Comment by ignalauret** [comment]
Hey @kjsdad thanks for your report. I followed your steps and was able to assign the non required String page parameter as the label of the TextField. Was that what you were having troubles with? Or is there somewhere else you are trying to assign the variable?

**Comment by leighajarett** [comment]
Closing this issue since we have not heard back
