### ISSUE TITLE
Error when change action output variable name.

### ISSUE THREAD

**Issue by gabdreux** [FlutterFlow/flutterflow-issues#2553]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is a "Read a Document" action initiated by clicking on a column and when I try to change the "Action Output Variable Name" all other components that are using this return "breaks" as if the return was no longer recognized.

I can change the name of some of these action returns in some components without problems, but it's breaking in some others.

![bug01](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f8860b20-9cf3-4686-a6ed-179cd2488daa/69899030-9da7-4dec-ac77-3d9303ecd059?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mODg2MGIyMC05Y2YzLTQ2ODYtYTZlZC0xNzljZDI0ODhkYWEvNjk4OTkwMzAtOWRhNy00ZGVjLWFjNzctM2Q5MzAzZWNkMDU5IiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.03EDlsZGvND7YJhxtGXesf-RvGkoZaTbY7L69V74f3o)

![bug02](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1238198f-bbd9-40b7-aef3-d1e58ee9d173/4d11ec7e-beed-4d2f-aa04-bfc199206b2c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMjM4MTk4Zi1iYmQ5LTQwYjctYWVmMy1kMWU1OGVlOWQxNzMvNGQxMWVjN2UtYmVlZC00ZDJmLWFhMDQtYmZjMTk5MjA2YjJjIiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.jc0d1GP7ZYoU3z-upOXxXQGS0O_GfLVXbszmiZNRAso)

Project link:
[https://app.flutterflow.io/project/monitor-13-gurq9c?tab=widgetTree&page=done](https://app.flutterflow.io/project/monitor-13-gurq9c?tab=widgetTree&page=done)

THANK YOU SO MUCH!!!!!

### Expected Behavior

When changing the name of the "Action Output Variable Name", the components will continue to recognize the origin of the variable it is consuming.

### Steps to Reproduce

1. Go to page "done".
2. Click on the column named "Column_with_bug".

![bug03](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5c8f6704-c7cf-4a99-9eec-f11f83d9bc36/a461d4d7-61f6-42a1-a48c-910941f70437?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81YzhmNjcwNC1jN2NmLTRhOTktOWVlYy1mMTFmODNkOWJjMzYvYTQ2MWQ0ZDctNjFmNi00MmExLWE0OGMtOTEwOTQxZjcwNDM3IiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.6Np0av1iBdtyhTFPB_tjJQrt_5DrdleXzRYYHR05TCU)

1. Go to "On tap" action and change the name of "Action Output Variable Name" of the action number 2.

![bug04](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/703d0098-332a-49e6-af43-e084843c02c8/ccb4fa80-a9e4-4ebe-808a-9a186b77dce1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MDNkMDA5OC0zMzJhLTQ5ZTYtYWY0My1lMDg0ODQzYzAyYzgvY2NiNGZhODAtYTllNC00ZWJlLTgwOGEtOWExODZiNzdkY2UxIiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.1dD0bgSZeJRHjM9UDC0tVnDj8IN8Iflbt6pnEJpMntE)

Thats it.

![bug02](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/01d201e4-b6d8-4a9c-bda3-c68fe86e6608/5b294131-e431-4211-9d82-670f71feff90?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMWQyMDFlNC1iNmQ4LTRhOWMtYmRhMy1jNjhmZTg2ZTY2MDgvNWIyOTQxMzEtZTQzMS00MjExLTlkODItNjcwZjcxZmVmZjkwIiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.haHvLdOju-94Qo6kOlRvP5xHiCWb2jIXonbVY2Z5HCo)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi8mAvI9IsbRJ+Kn9Y+9VqGEWH096UK00st4bGAsdGOvrBuwUefT8RFRBZ/GlaVNceGeGkT4J//eMioT1CsEqPkiaft1O+M0JSQrke2i5bpCTO5OKT0cmFphXf0y+1pmgkB5CBMZhclIS33GIO+mvdHHDIuu/Zwh9f6PHaOI=

### Context

I have 3 days of work that consume the output of the variable that I need to change the name because there is already another output action with the same name on the page where I am trying to place this component.

### Visual documentation

![bug01](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/590f5b3f-fcc0-41e1-b130-57020b8849f3/3e6701fb-2a77-48a6-85d6-3454e4105e38?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81OTBmNWIzZi1mY2MwLTQxZTEtYjEzMC01NzAyMGI4ODQ5ZjMvM2U2NzAxZmItMmE3Ny00OGE2LTg1ZDYtMzQ1NGU0MTA1ZTM4IiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.EDNS7f0GpseqR-FGHeVtmsZzUS_0fax9a43DXEwKPwU)

![bug02](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5fe2e509-b287-4807-9075-52d44c43ad41/e0a71693-6c22-42d5-947e-bea29019dbe3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ZmUyZTUwOS1iMjg3LTQ4MDctOTA3NS01MmQ0NGM0M2FkNDEvZTBhNzE2OTMtNmMyMi00MmQ1LTk0N2UtYmVhMjkwMTlkYmUzIiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.ED6cfZQhv7jUDvOAQBzBDvuORPi7x0UI4E1wGNpH__Q)

![bug03](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/966e3b78-fae5-422f-b39f-4918ba1f737a/0450ecdb-1e1f-4eae-8b1a-2a8c39f97b14?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NjZlM2I3OC1mYWU1LTQyMmYtYjM5Zi00OTE4YmExZjczN2EvMDQ1MGVjZGItMWUxZi00ZWFlLThiMWEtMmE4YzM5Zjk3YjE0IiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.1iRs8ZZ5lFaE74aTvPnW3gq6pRnR_I3LDNeig1jEFX8)

![bug04](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fd679110-75e9-494c-b9ee-b2d58cb0d004/8652931d-99f5-4667-b57f-c7f9dd3fb06d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZDY3OTExMC03NWU5LTQ5NGMtYjllZS1iMmQ1OGNiMGQwMDQvODY1MjkzMWQtOTlmNS00NjY3LWI1N2YtYzdmOWRkM2ZiMDZkIiwiaWF0IjoxNzEwODYzNzI2LCJleHAiOjMzMjgxNDIzNzI2fQ.PQmglhXVvXiMt0TxqzYGT_cJ8J-ejyfYiRkYKbhIm9M)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Internet Explorer
- Operating system and version affected: all
```

**Comment by ignalauret** [comment]
Hey @gabdreux thanks for your report. I checked your project but I can't see any page called Do, or find you component. I hope this means that you've been able to fix it. <br>If not, could you please show me the steps to reproduce this on a Blank Project? How to build the component and what names to use to replicate the issue.

**Comment by leighajarett** [comment]
Closing this issue since we have not heard back
