### ISSUE TITLE
Swipable stack's current element not visible when putting two swipable stack in a stack widget.

### ISSUE THREAD

**Issue by yashtiwaribitspilani** [FlutterFlow/flutterflow-issues#2554]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to show two swipeable stack widgets conditionally under a stack but the current element of neither of them is visible in widget state.

### Expected Behavior

I should have access to the current element of both the swipeable stack widget.

### Steps to Reproduce

1. Create an empty page
2. Put a stack widget
3. Add two swipeable stack widget
4. Try adding an action involving current element of the swipeable stack widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klcmA04lIobhb7qXxbcFWjiQ7KVB8TLJItutuZxIYfuP1P+w1PfTCUBBCYuqHe1dMO1ejuH400/z0ktnTOPAEaBGeRt0++MxbUxDgIUylMKaXDcyNdmpCHcBWC26m0qe7gCZQKvhocUIu61z7CdmAb3qCf9qOYwx5e6fDbOY=

### Context

I am trying to have two swipeable stacks under a stack widget to accomplish business logic of my application.

### Visual documentation

![Screenshot_bug](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8e9cbf38-db5c-4288-9b47-92ed30c8e0a6/5d381b90-35c9-4113-82c2-49881b999da7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84ZTljYmYzOC1kYjVjLTQyODgtOWI0Ny05MmVkMzBjOGUwYTYvNWQzODFiOTAtMzVjOS00MTEzLTgyYzItNDk4ODFiOTk5ZGE3IiwiaWF0IjoxNzEwODYzNzI1LCJleHAiOjMzMjgxNDIzNzI1fQ.ZGly1khNFrGG5K4WXd3fa-rQNE3HCWRIYJzeAxIMCH0)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:web
- Browser name and version:Chrome latest
- Operating system and version affected: latest windows 11
```

**Comment by yashtiwaribitspilani** [comment]
Now for performing some action using the current stack element on both of the swipable stack gives some error.

**Comment by leighajarett** [comment]
Hi @yashtiwaribitspilani - this seems like a different issue, please file a new issue with the exact details on how to reproduce the problem you are having from a blank project. Thank you!!
