### ISSUE TITLE
CORS error of place picker in Web app build using FlutterFlow

### ISSUE THREAD

**Issue by vickyone0** [FlutterFlow/flutterflow-issues#2555]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I attempt to select a location using the place picker, **a CORS error occurs.**

Also is the search option of place picker also ,it doesn't show any location to select .

![Screenshot 2024-03-14 131445](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c46d6502-b514-4800-aac2-e3791e244404/c5c36093-4d39-4c00-ac4a-4ac1f661aaa6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNDZkNjUwMi1iNTE0LTQ4MDAtYWFjMi1lMzc5MWUyNDQ0MDQvYzVjMzYwOTMtNGQzOS00YzAwLWFjNGEtNGFjMWY2NjFhYWE2IiwiaWF0IjoxNzEwODU4MTYyLCJleHAiOjMzMjgxNDE4MTYyfQ.f0nNDK-t9ch-Bk0se2T1j3mbNC6UCqt7VtOeUUxaATo)

### Expected Behavior

Expected that when i search location in the place picker , want to show a some place .

### Steps to Reproduce

1. Create a web page with place picker widget.
2. Connect the project with firebase
3. Download the code locally
4. Host the website in firebase hosting
5. Try to select the location using place picker

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8wlMmAx89OxcRE7c/AacFvoDo5Jj8jbaxMidV+EA41F4DyPbAIf8+kMlZVOerhYH9qfEamjl8Jpt7ShtmeEfkpaQeVb7Z++aVcFxbPe16gabaVDM+3dUEnJ+RVG2HC4J27mCJCKuhscUUlxk+qC9m9HyvZJYTHIjANJPqkFKT7ogubAXvrLiNvzW45PEeREtoTIVDq+f6QspZl1eTjzw==

### Context

when this error occur then we can't able to release our web app in production

### Visual documentation

![Screenshot 2024-03-19 094748](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/14efcf59-dce0-433d-82ca-2980e684a391/68af0a5f-3592-47e6-b7f2-947d7589b457?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNGVmY2Y1OS1kY2UwLTQzM2QtODJjYS0yOTgwZTY4NGEzOTEvNjhhZjBhNWYtMzU5Mi00N2U2LWI3ZjItOTQ3ZDc1ODliNDU3IiwiaWF0IjoxNzEwODU4MTYyLCJleHAiOjMzMjgxNDE4MTYyfQ.xkm1ZmgBdNmBB6ilSaNuArfDUqv7Fc-lrKAgEyRO_h8)

This is the behavior occur when i try to search the location

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 (FLutter 3.19.1)
- Platform: Web
- Browser name and version:Chrome 122.0.6261.112 (Official Build) (64-bit)
- Operating system and version affected: windows 11
```

**Comment by ignalauret** [comment]
Hey @vickyone0 thanks for your report. Does this CORS issue appear also if you deploy the web using the Flutter Flow publish option?

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by FilliTech** [comment]
I am facing the same problem and saw on the community that others have the same problem and they couldn't solve it as of my knowledge
