### ISSUE TITLE
Wiget on WidgetTree will be deleted if BackSpace pressed on Foreground Panel

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#2557]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Pressing "Backspace" key (on MacOS /w HHKB keyboard) on Foreground Panel, the Wiget on WidgetTree will be deleted.
i.e. If I press "Backspace" to correct "WrongCaracter" on the Panel, "Wrap" Widget on WidgetTree will be deleted.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/16b017a8-c270-45fb-9934-e410cf978153/577ea4c4-5a0f-4d45-b620-83227216ec25?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNmIwMTdhOC1jMjcwLTQ1ZmItOTkzNC1lNDEwY2Y5NzgxNTMvNTc3ZWE0YzQtNWEwZi00ZDQ1LWI2MjAtODMyMjcyMTZlYzI1IiwiaWF0IjoxNzEwODU4MTQ3LCJleHAiOjMzMjgxNDE4MTQ3fQ.t4ToB5EOoDt14m5YvdqgGLqCdnOdSz-ZSaFDMNEhUC4)

After pressing "Backspace"

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9993035d-b68f-48ae-9822-c88efb9edda3/3ba458a2-098c-4903-80d4-da4824d367d0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OTkzMDM1ZC1iNjhmLTQ4YWUtOTgyMi1jODhlZmI5ZWRkYTMvM2JhNDU4YTItMDk4Yy00OTAzLTgwZDQtZGE0ODI0ZDM2N2QwIiwiaWF0IjoxNzEwODU4MTQ3LCJleHAiOjMzMjgxNDE4MTQ3fQ.JTUlLYcwlM_PZGBfNBLMltGKd9kTehoqKsA-OR_M_tk)

#### F.Y.I.

Pressed Key code

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3431d01c-5f92-4a72-9cdb-50c04c0e285f/858752de-8222-4ebe-808d-c2a6f592aa61?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNDMxZDAxYy01ZjkyLTRhNzItOWNkYi01MGMwNGMwZTI4NWYvODU4NzUyZGUtODIyMi00ZWJlLTgwOGQtYzJhNmY1OTJhYTYxIiwiaWF0IjoxNzEwODU4MTQ3LCJleHAiOjMzMjgxNDE4MTQ3fQ.NOBAlkx5zntSLBG9eX0tQqTrpKC3B_BBVOEtR-PSB6A)

### Expected Behavior

Just work as backspace on foreground panel.

### Steps to Reproduce

As in Current Behavior section.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8jq3ItOm8sC1a6Jd+1Wnj4sH2UcTYMZm9ZxYx4aJZytP4ktPOP4Q0NKTMznYHxiDk2kqzgE+ez9uNnXDPECaC+cbak+0JVAZxWXUTqRbraXC7uSWX97GcBhGX661KS33BJANuNZL2wQ206bNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I know this problem and I can avoid this issue by don't pressing Backspace.
But if forgetting that, little panic.
If I wanted to try delete several characters and repeated pressing "Backspace", many widgets will disappear, really panic.

### Visual documentation

As in Current Behavior section.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 - Flutter 3.19.1
- Platform: Web
- Browser name and version: Chrome 122.0.6261.129 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by blueprin4** [comment]
I was just coming here to report the same thing.  I spent hours trying to figure out why all my widgets were deleted when  I know I didn't delete them.   Finally discovered the same especially when deleting code in custom actions code or even deleting the title of customer action.

**Comment by ryutosh** [comment]
> I was just coming here to report the same thing. I spent hours trying to figure out why all my widgets were deleted when I know I didn't delete them. Finally discovered the same especially when deleting code in custom actions code or even deleting the title of customer action.

Ha-ha! Thanks for your additional information!
I knew about Backspace problem a long time ago, and I should have reported it earlier😅
But it was a hard process of Issuing (see the number of required fields above), but the more I concentrate on developing(and forgetting to avoid Backspace), the more the widget disappears, and I couldn't stand it anymore😂
