### ISSUE TITLE
Mac Destop App download link missing from redirect page

### ISSUE THREAD

**Issue by kiptoomm** [FlutterFlow/flutterflow-issues#2562]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

From the FF Dashboard, there's a "Mac Desktop App" card that when clicked, redirects to [https://flutterflow.io/flutterflow-desktop-app](https://flutterflow.io/flutterflow-desktop-app). That page does not have any link to install the app

### Expected Behavior

The redirect should provide the ability to download the actual desktop app

### Steps to Reproduce

1. Go to [https://app.flutterflow.io/dashboard](https://app.flutterflow.io/dashboard)
2. Supported Platforms -> Mac Desktop App. Click on the card
3. The user is redirected to [https://flutterflow.io/flutterflow-desktop-app](https://flutterflow.io/flutterflow-desktop-app), which is a landing page with no download link

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

I'm trying to install the desktop app and give it a try. I had to use a search engine to find [https://flutterflow.io/desktop](https://flutterflow.io/desktop), which seems to be the correct page.

### Visual documentation

![Screen Shot 2024-03-19 at 11 11 33 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b376816d-459f-48b0-8821-d6736213e8d8/ee528139-1153-47c7-8486-e8d654f963b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMzc2ODE2ZC00NTlmLTQ4YjAtODgyMS1kNjczNjIxM2U4ZDgvZWU1MjgxMzktMTE1My00N2M3LTg0ODYtZThkNjU0Zjk2M2IyIiwiaWF0IjoxNzEwOTMwMzU0LCJleHAiOjMzMjgxNDkwMzU0fQ.UX59DlzKaZ5N8QSKfsBQR6HLRgFnzcOMyNjqK-4vhG8)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: macOS
- Browser name and version: Chrome 122.0.6261.129 (Official Build) (x86_64)
- Operating system and version affected: 11.7.10
```

**Comment by kiptoomm** [comment]
activity ;)

**Comment by leighajarett** [comment]
Thanks for flagging this! Should be resolved now
