### ISSUE TITLE
App goes blank in Edit mode.

### ISSUE THREAD

**Issue by mccoyg** [FlutterFlow/flutterflow-issues#2563]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dashboard works. Go to click on edit project. Project screen appears and then goes blank.

![Screenshot 2024-03-19 at 13 19 33](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6a83e6d0-1c51-45b2-92ba-286847e34f6b/fa847412-dcce-49c3-805e-4476cd9ecab8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YTgzZTZkMC0xYzUxLTQ1YjItOTJiYS0yODY4NDdlMzRmNmIvZmE4NDc0MTItZGNjZS00OWMzLTgwNWUtNDQ3NmNkOWVjYWI4IiwiaWF0IjoxNzEwOTMwMzUxLCJleHAiOjMzMjgxNDkwMzUxfQ.7a2NKAd9AWSItDYSqZjvp0S3oLLE0kUALtumnt8XaPc "=1457x")

### Expected Behavior

I expect to edit the project. I am in demo mode.

### Steps to Reproduce

1. sign in > Dashboard
2. click on project card
3. Project opens in uiBuilder?
4. Add container
5. Add Column
6. Add Image
7. Screen goes blank

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlsn1z4pNjMhE7pP+du4xlWIwGUwbUOc7j9VEGAsjCeOrOokQZOD4XFNpYuqHS1FieGCbrEMCwtL0heDxIfEnFySrc6Zk+qlpUxDjUkiiaZeaPpOaYHR6J/NMC2KG0aWF3B1TLtFqLHwi3DqLOOeQb3qCf9qOYwx5e6fDbOY=

### Context

I am just trying to demo this application to see if it fits my workflow. Not great if I need to submit a bug report in the first 30minutes of evaluation and can get no answers or live chat help........

### Visual documentation

![Screenshot 2024-03-19 at 13 19 33](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ea102b3e-05a0-4852-825e-e7ff44b3d722/fdd10d21-0a55-4053-869b-1319de12a729?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYTEwMmIzZS0wNWEwLTQ4NTItODI1ZS1lN2ZmNDRiM2Q3MjIvZmRkMTBkMjEtMGE1NS00MDUzLTg2OWItMTMxOWRlMTJhNzI5IiwiaWF0IjoxNzEwOTMwMzUxLCJleHAiOjMzMjgxNDkwMzUxfQ.GDLMzfXUln0_QwM7aF55-kTDJO_EJXKZFzppCqIG0VA "=1457x")

### Additional Info

*No response*

### Environment

```markdown
FlutterFlow version: v3.19.1
Platform: MacOS
Browser name and version (web): Chrome 122.0.6261.129
Operating system and version (desktop): macOS Sonoma 13
```

**Comment by takashiff** [comment]
Hi @mccoyg, thanks for the bug report! This looks to be a duplicate issue with #2450, so I will be marking this as closed. Please refer to the aforementioned thread for updates. Thanks!
