### ISSUE TITLE
Phone Auth without Home requiring authentication - doesn't work

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#2564]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an apps "Home" page doesn't have the toggle "Requires Authentication":

![Screenshot 2024-03-20 at 09 47 05](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3a7ba7cd-dca6-435b-9f47-e157d7625192/82eda6bb-9833-4d6d-a540-48a48c07f1c0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYTdiYTdjZC1kY2E2LTQzNWItOWY0Ny1lMTU3ZDc2MjUxOTIvODJlZGE2YmItOTgzMy00ZDZkLWE1NDAtNDhhNDhjMDdmMWMwIiwiaWF0IjoxNzEwOTMwMzMwLCJleHAiOjMzMjgxNDkwMzMwfQ.4z-2DsL1yZb89rNfsYDgd3rH0R7RSXjNRghD2MpRXr4)

And it is set as the "Logged In Page" in the Authentication settings:

![Screenshot 2024-03-20 at 09 47 44](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/74560eae-d54f-490f-8a3e-6ea15fc2f526/e305c22e-7b6b-4ac5-b5b7-ad5bd9bff587?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NDU2MGVhZS1kNTRmLTQ5MGYtOGEzZS02ZWExNWZjMmY1MjYvZTMwNWMyMmUtN2I2Yi00YWM1LWI1YjctYWQ1YmQ5YmZmNTg3IiwiaWF0IjoxNzEwOTMwMzMwLCJleHAiOjMzMjgxNDkwMzMwfQ.rq0YrTz-Q9Tf8RoydPruqcJisjVg_QBWRqMVjqKrozA)

Firebase Phone Auth doesn't work.

![Screenshot 2024-03-20 at 09 48 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ba037eb1-e1d0-4bf7-b5ef-ce6485185fce/ce76228e-bba0-43c9-8b44-485f6eac9876?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYTAzN2ViMS1lMWQwLTRiZjctYjVlZi1jZTY0ODUxODVmY2UvY2U3NjIyOGUtYmJhMC00M2M5LThiNDQtNDg1ZjZlYWM5ODc2IiwiaWF0IjoxNzEwOTMwMzMwLCJleHAiOjMzMjgxNDkwMzMwfQ.jsT07WOXV-9kQAOR5q4D4Vv32J4nto2DGLBG5QkNPxw)

Upon clicking on a button with the action "Phone Sign In" the app automatically goes to the "Home" page. No matter where the action on the button may lead to. Unfortunately, FF doesn't let you add another "Navigation" action after the "Phone Sign In" action, so you can't control it after that.

### Expected Behavior

It is expected for the app to follow the navigation flow, no matter of whether the home page requires authentication or not, especially if it doesn't.

### Steps to Reproduce

 1. Activate firebase auth
 2. Add 3 pages: EnterPhoneNumber, ConfirmPhoneNumber & Home
 3. Set EnterPhoneNumber as "Entry Page" in the Authentication settings
 4. Set Home as "Logged In Page" in the Authentication settings
 5. On EnterPhoneNumber add a textfield and a button
 6. On the button, add action "Phone Sign In" that will take in the textfield as a number & lead to ConfirmPhoneNumber
 7. On ConfirmPhoneNumber add a pincode widget and a button
 8. The button should have the action "Verify SMS Code" and take the pincode as input, after that action add a navigate to "Home"
 9. Make sure that none of the pages have "Requires Authentication" turned on -- KEY STEP
10. Try the process and see if you can login

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

/

### Context

In modern apps, we *have* to let users see the app before logging in - at least a glimpse of it. For this, we would need to have our home page visible to all users, no matter whether they are logged in or not. This works perfectly with email sign in, google sign it, apple sign in, etc. It only doesn't work with phone authentication.

### Visual documentation

In the Current Behavior.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.33
- Platform: MacOS Desktop
- Browser name and version: 122.0.6261.129
- Operating system and version affected: macOS Sonoma 14.1
```

**Comment by ignalauret** [comment]
Hey @tinrunje thanks for your report. Are you still experiencing this issue with the Phone Authentication and a Home that doesn't require authentication? Have you tried having two home screens, an Authenticated Users Home and a Guests Home?

**Comment by leighajarett** [comment]
Closing this issue since we have not heard back
