### ISSUE TITLE
AppCheck updates not taking effect in browser

### ISSUE THREAD

**Issue by mackaby** [FlutterFlow/flutterflow-issues#2565]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After setting incorrect AppCheck keys for web, and trying to update the keys, it is not working instantly. I would assume that it is due to token expiry (if set to a few days in firebase it is problematic if there is an issue).

### Expected Behavior

When keys are updated, it should take effect even if the user has used the app before. Is there a way to trigger token refresh if keys are updated? 

### Steps to Reproduce

Change the appcheck keys and see if it has any effect on your verification. Clearing cookies, cache etc wont work). 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkfLluJNPjMRE15fUdMExiiAwGUwbUOc7j9VEGAsjCeP1OrAuOczeaRdWWOqHYwl2IFb+rH8dw+z0ht7mGPI3FweabNg++YdpUxDvWme6R5iJEpOofWgnDeVYGFyy0aWrph0nPutaLkEj2EOAB+yua3qCf9qOYwx5e6fDbOY=

### Context

Trying to improve security by using AppCheck. Impact is that something is done wrong in the setup, it will take time for users to get an updated appcheck connection.

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: 4.1.33
- Platform: web
- Browser name and version: chrome 122.0.6261.129
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by ignalauret** [comment]
Hey @mackaby thanks for your report. Is you experience with AppCheck still not the expected, or has it been fixed on the newer versions of FF?

**Comment by leighajarett** [comment]
Closing this issue since we haven't heard back from you
