### ISSUE TITLE
Unable to download app code and app file

### ISSUE THREAD

**Issue by Tweetsavage** [FlutterFlow/flutterflow-issues#2566]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to download why app code and app file 

project id: slizen1-25p7m7
![266382120-f07a7fc6-9c02-470a-b2ab-83e64ad2da55-2](https://github.com/FlutterFlow/flutterflow-issues/assets/98621557/4aea810d-cf06-4971-8286-06849118ca2d)

### Expected Behavior

Need to download the app code. 
<img width="311" alt="Screen Shot 2024-03-21 at 12 47 58 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/98621557/a4aa7758-74c1-4f97-8105-5c51c8fc4d58">

### Steps to Reproduce

Done

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThcn15cl2oblI+KnxKMBGqCQ7CUMfWOdEket+EA0hfa3kPZoIYfT4TEtLYteDT39IIWGkpEEd/62OuPHtFOwoYAyBfrk5z4RXQQGWZE+QVK2bCKueWHBQL5tbf36X5LazohJBBLFtS39m2VObNvCdG3qCf9qOYwx5e6fDbOY=

### Context

Yeah, the app needs to have been pushed to production since Monday but due to this error we could;dn't

### Visual documentation

![266382120-f07a7fc6-9c02-470a-b2ab-83e64ad2da55-2](https://github.com/FlutterFlow/flutterflow-issues/assets/98621557/e9988552-adeb-4743-9dda-101c9eb676be)

### Environment

```markdown
- FlutterFlow version: 4.1.33
- Platform: (web and macOS )
- Browser name and version: safari, chrome 
- Operating system and version affected: macOS Monterey 12.7.4
```

**Comment by ignalauret** [comment]
Hey @Tweetsavage thanks for your report! I've been able to see your project and everything looks fine. Were you able to download your code or are you still experiencing this issue?

**Comment by Tweetsavage** [comment]
Thank you @ignalauret , I am still unable to download the app code.

**Comment by ignalauret** [comment]
@tweetsavage if you are still unable to download it, then this must be a project specific bug that you are experiencing. The technical team is going to check your project and try to figure out why. They will keep you updated on this thread. 
Have a great day.

**Comment by paulperez-dev** [comment]
Hi @Tweetsavage! Can you please try to download the code again?

**Comment by Tweetsavage** [comment]
Thanks you all, the issue has been fixed. I have been able to download my app code

**Comment by paulperez-dev** [comment]
Thanks for the confirmation @Tweetsavage! I'm closing this issue.
