### ISSUE TITLE
Unable to download app code 

### ISSUE THREAD

**Issue by Tweetsavage** [FlutterFlow/flutterflow-issues#2567]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Im trying to download my code project, but i have a error, <> Unexpected error. Please try again.

I don't have any error in my project, and wen use the Test for my project worked.

I dont know what happened.
Also, the downloaded app file was not able to be installed on an android device

project id: slizen1-25p7m7

### Expected Behavior

I wanted to be able to download my app's code to test locally.

project id: slizen1-25p7m7

### Steps to Reproduce

Done

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThcn15cl2oblI+KnxKMBGqCQ7CUMfWOdEket+EA0hNYyuEJoueuLSZRdLYtThTFBiOGGjrEQy3N7JkvPPDPA7PTGcUaU/yZRXQQGWZE+QVK2bCKueWHBQL5tbf36X5LazohJBBLFtS39m2VObNvCdG3qCf9qOYwx5e6fDbOY=

### Context

I was trying to send the app file to my team .

![266382120-f07a7fc6-9c02-470a-b2ab-83e64ad2da55-2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d3324ee7-e28f-463d-8995-3e1ffa9e6026/9e91b309-08f5-4357-b4b3-7988d0df5cf2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMzMyNGVlNy1lMjhmLTQ2M2QtODk5NS0zZTFmZmE5ZTYwMjYvOWU5MWIzMDktMDhmNS00MzU3LWI0YjMtNzk4OGQwZGY1Y2YyIiwiaWF0IjoxNzExMzgyNzQ0LCJleHAiOjMzMjgxOTQyNzQ0fQ.5j4ag68eWnvEQ2hxM3XVLLVwhKUV5k-UXNNu6VgODyY)

### Visual documentation

![Screen Shot 2024-03-21 at 12 47 58 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cd1aeb6b-2301-4cff-b98a-d155670a6f27/c39c86b9-b86e-4089-b0a2-c733ddf5fcb2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZDFhZWI2Yi0yMzAxLTRjZmYtYjk4YS1kMTU1NjcwYTZmMjcvYzM5Yzg2YjktYjg2ZS00MDg5LWIwYTItYzczM2RkZjVmY2IyIiwiaWF0IjoxNzExMzgyNzQ0LCJleHAiOjMzMjgxOTQyNzQ0fQ.KifnYeaUc4GIYQBErdomX_7O40QgaxrnILnfsTKJ8Aw "=311x")

### Additional Info

![266382120-f07a7fc6-9c02-470a-b2ab-83e64ad2da55-2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/85cb6881-016c-4f14-9bb4-0ea7637dd013/75c7d6d5-3201-47c5-bff1-b91ed082b84e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NWNiNjg4MS0wMTZjLTRmMTQtOWJiNC0wZWE3NjM3ZGQwMTMvNzVjN2Q2ZDUtMzIwMS00N2M1LWJmZjEtYjkxZWQwODJiODRlIiwiaWF0IjoxNzExMzgyNzQ0LCJleHAiOjMzMjgxOTQyNzQ0fQ.BOydDCyoVdpIlToy3kcFpoPymCHeaR3hSHl4tFBH94o)

### Environment

```markdown
- FlutterFlow version: 4.1.33
- Platform: web
- Browser name and version: safari and chrome
- Operating system and version affected: macOS
```

**Comment by Snellies** [comment]
I am having the same issue! Wondering how to fix!

**Comment by takashiff** [comment]
Hi, thanks for the bug report! Currently, this looks to be a code download timeout issue. We are currently working on a fix for this, thank you for your patience!

**Comment by Tweetsavage** [comment]
Okay. I am still facing the same issue. Can you please notify me when it is done.

**Comment by takashiff** [comment]
Hi @Tweetsavage, can you try going into 'App Details' in 'App Settings' in your project, and disabling the toggle 'Run "dart fix"'? Thanks
