### ISSUE TITLE
Custom function with a return type of int, returns a string instead

### ISSUE THREAD

**Issue by Hypersight** [FlutterFlow/flutterflow-issues#2568]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have written a custom function that has a return type of int. It passes in a non-nullable list of a custom datatype that has two properties: DocReference (to a Users table) and a datetime field. It also passed in a DocumentReference of the currently authenticated user.

When I attempt to create a condition for a Button element to show, I create a Single Condition, I set the custom function to be the first value to use, i then provide the parameters of the List<CustomType> and the DocumentRef of the Authenticated user.
I leave Available Options as Number Format and Number Format Options as Not Formatted. I then click Confirm to add the first value of my Single Condition.

At this point, it should know that the function has a return type of Int. However, in back in the original Condition window after clicking Confirm, it says that the first value returns (String).

This means that I cannot use comparison types for my Second value of things such as >=, >, <, <= and so on.

### Expected Behavior

The custom function is set to return an Int. The custom function returns an Int type parameter, therefore the conditional function should detect it's an Int return type and give me options to select number comparisons.

### Steps to Reproduce

1. Create blank project
2. Create a Users collection
3. Create a DataType called PrizeEntry and a parameter called "userRef" which is a reference to a Users collection DocumentRef and a datetime field called "dateentered"
4. Create a Custom function with a non-null return type of int, it should have a List parameter called "entries" referencing the DataType called PrizeEntry and a DocumentReference param referencing the Users collection
5. Copy and paste the following code into the function:
```
 int count = 0;
  for (var prizeEntry in entries) {
    if (prizeEntry.userRef == userRef) {
      count++;
    }
  }
  return count;
```
6. Go to the Home page design
7. Create a dummy Local Page state variable called testEntries, mark it as a DataType of PrizeEntry and as a List.
8. Create another dummy Local Page state variable called testUser and set it to a type of DocumentReference and the collection Users
9. Back in the design for Home Page, create a button and enable Conditional and create a Single Condition.
10. In the Condition for the first value, choose the Custom Function, for the parameters to pass the custom function, choose the two local state page variables you created in Step 7 & 8. Leave all the number formatting default and click Confirm.
11. At this point, you will see that the condition thinks it's returning a string and not an int. You can also not select a number comparison for the first value and the second value of the condition.
12. This same issue also happens in a browser (Chrome 122.0.6261.12 on MacOS Sonoma 14.4)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slPHlw852j7xZ1rr+bMJ7/SgUKUB5U4JFscsZa0kdB4joPLJ/P87SSFNucM+lY1NhHGGkjk0D+s2Kv4b9IfQBIROuG5s7+LlcdQqXJHq8R66MC86SVHdtGcFWf2qi0cKjhCZSKulidGwH21z6fum/Ex7sGZO/Zwh9f6PHaOI=

### Context

This has made number comparison operations impossible. We have an application that rewards users for amount of points earned for example. This bug now breaks this functionality.

### Visual documentation

<img width="633" alt="Screenshot 2024-03-20 at 5 26 00 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4229798/3545012a-85dc-430b-b35e-b2086b3c49b0">
<img width="966" alt="Screenshot 2024-03-20 at 5 47 01 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4229798/f0f9acbe-4d74-4bd5-883e-5118a1201760">
<img width="929" alt="Screenshot 2024-03-20 at 5 47 09 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4229798/905c6e07-2672-49ab-813d-ec5b9734ed37">
<img width="934" alt="Screenshot 2024-03-20 at 5 47 54 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4229798/e9d2980e-373a-4eb8-bd4c-d9505957fcc7">
<img width="776" alt="Screenshot 2024-03-20 at 5 48 18 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4229798/1c2afdbd-a3bb-4a0a-8532-d9412d40bf67">

### Additional Info

This did work previously, but think that maybe it regressed after an update at some point in the last 2-3 weeks. I am unable to say which version was affected.

### Environment

```markdown
- FlutterFlow version: 4.1.33 (Flutter 3.19.1)
- Platform: MacOS Sonoma 14.4 (Mac native app)
- Browser name and version: Chrome 122.0.6261.12
- Operating system and version affected: MacOS Sonoma 14.4
```

**Comment by Hypersight** [comment]
Don't close. I am still awaiting someone to triage this issue.

**Comment by Ed-Lemaitre** [comment]
Same problem here.

**Comment by ignalauret** [comment]
Hey @Hypersight thanks for your report. I was able to follow your steps, and I can see you have a small issue. At the end, you have selected "Number Format" on the Available Options, that is the default one. That is formatting your integer to a String. You need to change that to "No Further Changes" for it to remain as an Integer. 
I hope this was helpful for you and @Ed-Lemaitre. 
Have a great day!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bd248eec-5338-4b7b-b74a-189d702f60da/336621d2-aed1-4cf9-98d3-e07ae0095248?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZDI0OGVlYy01MzM4LTRiN2ItYjc0YS0xODlkNzAyZjYwZGEvMzM2NjIxZDItYWVkMS00Y2Y5LTk4ZDMtZTA3YWUwMDk1MjQ4IiwiaWF0IjoxNzEyNjkxMTY4LCJleHAiOjMzMjgzMjUxMTY4fQ.3vsMYNeAEnfPQH75TU5diCuTqO_EjesdfijOJD9B3dI " alt="Screenshot 2024-04-09 at 4.30.29 PM.png" width="652" height="555" />

**Comment by Ed-Lemaitre** [comment]
Thanks! @ignalauret . :bow:

**Comment by ignalauret** [comment]
You are welcome, glad it worked. Closing this issue because it got solved, good luck with your project!
