### ISSUE TITLE
Command palette doesn't search components and other organisational issues

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#257]
Notice how in the attached screenshot editSocial is in the components sidebar tree but fails to appear in the command palette cmd+k. The same applies to all other components.

![Screenshot 2022-12-21 at 13 25 36](https://user-images.githubusercontent.com/72607/208904665-dba77802-4a73-46cf-9f64-085770b548d0.png)

Along that there are two similar issues: 
1. The components cannot be organised into folders like you can do with pages creating a big mess.
2. Folders cannot be re-ordered.
3. Folder close and open status isn't kept when moving away from pagetree.

It seems to me like like a low-hanging fruit that make a huge difference in the life of flutterflow developers as projects grow to medium size and above.

**Comment by Pepino-GR** [comment]
Hi davhad, 

as the reported issues are no bugs, I will set this as a feature request.

**Comment by agreaves** [comment]
Thanks for the report! It's on our TODOs :)
