### ISSUE TITLE
App Deployment curl timeout error

### ISSUE THREAD

**Issue by deepanchal** [FlutterFlow/flutterflow-issues#2570]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying to iOS or Android app stores, code magic throws the following error:

```
Codemagic Deploy Output
Failed Step:

== Use Flutter version 3.19.1 ==
> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.1-stable.zip --connect-timeout 10.00 --max-time 45.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.1-stable.zip
curl: (28) Operation timed out after 45005 milliseconds with 159944022 out of 1167172797 bytes received

Downloading Flutter release timed out, try again...

> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.1-stable.zip --connect-timeout 10.00 --max-time 45.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.1-stable.zip
curl: (28) Operation timed out after 45001 milliseconds with 66961103 out of 1167172797 bytes received

Downloading Flutter release timed out, try again...

> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.1-stable.zip --connect-timeout 10.00 --max-time 45.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.1-stable.zip
curl: (28) Operation timed out after 45000 milliseconds with 1166787380 out of 1167172797 bytes received

Downloading Flutter release timed out


Build failed :|
Downloading Flutter release timed out
```

### Expected Behavior

Deploy should work without this error.

### Steps to Reproduce

1. Navigate to Settings > Mobile Deployment > Google Play Store > Deploy to Play Store
2. Click Deploy to Play Store and during `building`, it's throwing this error

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/8284aa2b-406f-4216-80ba-9f6a5af4ec15)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

None

### Context

I can't deploy my app to App store or Google Play Store

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/890efa56-f395-49ed-89c4-9cc3bf073df3)

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: iOS & Android
- Browser name and version: None
- Operating system and version affected: None
```

**Comment by deepanchal** [comment]
It looks like the issue has been resolved. I was able to deploy without this error. However, I did get a similar error but with a timeout of `120 seconds` instead of `45 seconds`.

- https://community.flutterflow.io/ask-the-community/post/app-publishing-issue-eKY9SQeDWwf1O6d
- https://community.flutterflow.io/c/bugs/post/app-deployment-curl-timeout-error-8Y52sm2mvwGruoq

**Comment by deepanchal** [comment]
This error is happening again with 120 s curl timeout.

```
Codemagic Deploy Output
Failed Step:

== Use Flutter version 3.19.1 ==
> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.1-stable.zip --connect-timeout 10.00 --max-time 120.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.1-stable.zip
curl: (28) Operation timed out after 120005 milliseconds with 119258435 out of 1167172797 bytes received

Downloading Flutter release timed out


Build failed :|
Downloading Flutter release timed out
```

**Comment by drpark** [comment]
same here

**Comment by paulofilip3** [comment]
same

**Comment by devtahirzahid** [comment]
Same for me, i am getting the same error, i pushed the previous build 5 days ago

**Comment by AgIntelligence** [comment]
Can also verify this is happening.

**Comment by sosdeveloppeur** [comment]
Same problem for me

**Comment by yusufceyhun** [comment]
Same

**Comment by iamtruwealth** [comment]
happening here too

**Comment by DhaferBA** [comment]
Same here 
> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.1-stable.zip --connect-timeout 10.00 --max-time 120.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.1-stable.zip
![Screenshot 2024-03-28 213218](https://github.com/FlutterFlow/flutterflow-issues/assets/29396434/23505576-8f7b-4849-85d8-0414083282be)

**Comment by CorySavit** [comment]
I have been able to get a build through occasionally overnight, usually between 12am-7am eastern time, but it's useless during the day. Whatever the issue is, it seems to be less of a problem with less server congestion.

**Comment by ignalauret** [comment]
Hey @deepanchal thanks for your report. CodeMagic has been experiencing issues in the last 2 weeks, but they have apparently solved them. Sadly, we can't control if any of the  3rd party services are experiencing troubles. 
I hope everything is running smooth now, have a great day.

**Comment by pdgitgrv** [comment]
também estou com o mesmo erro: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/149795103/11fd8128-6e88-4fb4-9178-b2509e3a96b0)
