### ISSUE TITLE
APK build not passing Splash Image

### ISSUE THREAD

**Issue by zeymermontes** [FlutterFlow/flutterflow-issues#2571]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you build an APK from FF it wil succesfully generate the APK file, but the App won't pass splash image.

Extra Tests:
Even when Downloading the code and Trying to build the APK on VScode you get an exception when trying to Initialize Firebase.

### Expected Behavior

Build the APK
Install in device
Open the app succesfully to the home page.

### Steps to Reproduce

Create a project
Add Firebase to the project
Add Firebase Auth
Set Logged in page
Create APK
Install on device
Open the App

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiPLlx41PxOFd0a6Jc/lVpGM7JmEcTL4zlO1HcxAYGO/yPbJ/Z+LCUEpDQsfmTUNhHFSGrE8Ept7zjd/PCvUCH0itGrlyyZFiZAGXe3q8R4yvOqqWYEckI9xjCky404m7rRZ+NrRpdVYa2lOuAOyWQi7vJ5+/Zwh9f6PHaOI=

### Context

I need to publish the App to the playstore or send it to the client, but the app doesn't work.

### Visual documentation

![image (5)](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4308fbd2-b8a2-4b33-a74b-1dbf1887d464/b0cf6e86-8162-460a-86f6-22eb67ed07dd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MzA4ZmJkMi1iOGEyLTRiMzMtYTc0Yi0xZGJmMTg4N2Q0NjQvYjBjZjZlODYtODE2Mi00NjBhLTg2ZjYtMjJlYjY3ZWQwN2RkIiwiaWF0IjoxNzExMDc3MjM0LCJleHAiOjMzMjgxNjM3MjM0fQ.KEswOM0YJ4VPVYfBn3vNR92kiju7OtPugDPon4wh98U)

This is the Issue when running from VScode on Emulator.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Android
- Browser name and version: Chrome Version 122.0.6261.94 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.3.1
```

**Comment by hariprasadms** [comment]
Hi @zeymermontes - Thanks for submitting the issue. Is this still persisting at your end?

**Comment by lgsus81** [comment]
Hi- @[hariprasadms], In my case
 the issue persists; the app crashes at the splash screen

**Comment by lgsus81** [comment]
hi @hariprasadms In my case, the issue persists; the app crashes at the splash screen

**Comment by zeymermontes** [comment]
no, this issue has been fixed for me, thanks

**Comment by ignalauret** [comment]
Hey @zeymermontes I'm glad your problem was solved by the team. I'm closing this issue because it has been fixed.
