### ISSUE TITLE
CORS error only on GET API calls

### ISSUE THREAD

**Issue by rudvlimadev** [FlutterFlow/flutterflow-issues#2573]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Good evening everyone,

I'm facing an issue with a GET request to an API in production. My POST calls are okay, but the GET ones are encountering CORS (Cross-Origin Resource Sharing) problems.

The strange thing is that in FlutterFlow it works in 'test' mode and fetches the data correctly, but when I publish it on the web, CORS issues arise.

Has anyone experienced this?

### Expected Behavior

I expected the call to bring the JSON correctly in production

### Steps to Reproduce

Create a GET API call and publish it to the web. Then try accessing it on a page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Access to fetch at 'https://-----------/cadastros/solicitacoes/usuario/1' from origin 'https://costarica.flutterflow.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Context

I expected the call to bring the JSON correctly in production

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/98406114/bf5d1f5b-4c61-45c9-a17c-7ffd19453c16)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/98406114/49e280f8-5bdf-4c04-870e-5c925d56d454)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/98406114/a9847795-e137-428b-9f83-7e23cbff50d2)

### Environment

```markdown
Project ID: costarica-r59g5d

- FlutterFlow version: FlutterFlow v4.1 released March 21, 2024
- Flutter version is 3.19.1
- Browser name and version: Chromer
- SERVER - RailWay
- APLICATION : Python/Django
```

**Comment by ignalauret** [comment]
Hey @rudvlimadev thanks for your report. The CORS policy is configured on your Backend side, so first you should check if you have your policies ready for accepting calls from your domain. <br>Secondly, you could try adding the `Access-Control-Allow-Origin: *` header to  your API call in FF, to see if that fixes the issue. <br>Hope it was helpful, have a great day!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, thanks!
