### ISSUE TITLE
Can not add color to list item in app state when using Flutter Desktop for Windows

### ISSUE THREAD

**Issue by conbruno** [FlutterFlow/flutterflow-issues#2574]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a custom type that has a field of name and type color. The default value is "unset".
When I do the following to my list in app state:
Add Item -> Tap to Edit Fields -> click on the square left of the hex textfield -> the color dialog does not open.
or
Add Item -> Tap to Edit Fields -> enter a hex value in the color field -> the value is not saved.

### Expected Behavior

Add Item -> Tap to Edit Fields -> click on the square left of the hex textfield -> the color dialog does open.
or
Add Item -> Tap to Edit Fields -> enter a hex value in the color field -> the value is saved.

### Steps to Reproduce

see current behavior.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fhc/15ZVNxeZE1pCBKflagSQRNlw1bZ0/m+0bURQgfIvqP+wUPOLRbkhJbbSYdwk3PFv9uGMyp/COuPz9FeQHAE6BGd1a/qVcVA/LXl2XVrbSCqmWVHQlDZtgNEuVy6WNqxJAGM9aZU0swV2AfeesbD/vJuPpNmojR/j9MrrAjnCCAi+6Xn0Jg1ZSfCvr

### Context

I want to add some default items.

### Visual documentation

hard to show as a picture, because it is an event that does not happen.

### Environment

```markdown
- FlutterFlow version: 4.1.33
- Platform: Desktop
- Operating system and version affected: Windows
```

**Comment by ignalauret** [comment]
Hey @conbruno thanks for your report. I checked out your project but I was not able to find a component with the parameters you are mentioning. Could you please clarify which is the component that has the color parameter that is not working?
