### ISSUE TITLE
On Change Update Query

### ISSUE THREAD

**Issue by Somimpkno** [FlutterFlow/flutterflow-issues#2576]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using the on-change update query in Firestore database, but it continuously triggers even when no updates are made to the document after any single conditional action.

This issue persists even when there are no updates being made to the document. I am not sure why this is happening.
The query works fine during the initial page load, but if you have applied a filter on the onchange update query and then changed it after page load, it starts to perform an unlimited query.

in Hindi (मैं on change update (firestore database) query का उपयोग कर रहा हूं जब on change update पर किसी single conditional action के बाद कोई भी update लगायें या न लगाएं। यह लगातार on change update दिखाने लग जाता है जबकि उस document को कोई भी update नहीं कर रहा है । यह क्यों हो रहा है पता नहीं चल रहा है यह query initial page lode के समय सही से काम करती है लेकिन यदि आपने on change update query पर filter लगा रखा है तथा page lode के बाद उसे बदल दिया है तो यह unlimite query करने लग जाता है )

### Expected Behavior

I want the same property for the 'on change update query' as in, the query will only update when there is a document change, otherwise not.

in Hindi (मैं वहीं चाहता हूं कि जैसे on change update query की property है कि document change होने पर ही update होगा अन्यथा नहीं। )

### Steps to Reproduce

1. Create new page
2. more all step view in " Visual documentation " by image and video
3. Click Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMr1sM9OxdtH1rqBcvlR/TsRJlgibLssscsZbw4bB4zqPLJ/PcjRalJucNPmSmlhHFWLnjgy/9GOkc7PCvZdNk2aGr5O1pAJTRfgLHq8RKnRDquOZWhCQPFWI0Cd4LWvnB1SWbZsWXwD3zuMFuvLfD/vJ5+/Zwh9f6PHaOI=

### Context

```
      This problem is so critical that if it exists in any large app and the number of users running it reaches even 10,000, its Firebase price will skyrocket to the extent that it won't be affordable.

       People won't either build apps with FlutterFlow or be able to run them because the app owner won't have any money left. I've already asked this problem as a general question to the FlutterFlow community, but they haven't responded yet.
    
      I don't know if people are asking questions because we can't update the data. This is because it queries the data at intervals of seconds and sets it in the text field, making it impossible for us tochange the text.
     
     I request you to please solve this problem quickly before anyone incurs financial losses for no reason
```

in Hindi ( यह समस्या इतनी खतरनाक है कि यदि यह किसी बड़े app में मोजूद हो तथा उसे चलाने वालो की संख्या 10000 भी हो तो उस उसकी firebase price इतनी ज्यादा हो जायेगी कि वह चुका ही नहीं पायेगा। लोग flutterflow से ना तो app बनवायेंगे ओर न ही चला पायेंगे क्योंकि app मालिक के पास पैसा बचेगा ही नहीं। मैं इस समस्या को flutterflow community से एक सामान्य question के रूप में भी question कर चुका हूं लेकिन उन्होंने अभी तक कोई उत्तर नहीं दिया है आपको पता नहीं लोग question कर रहें हैं कि हम data को update नहीं कर पा रहे हैं? क्योंकि यह seconds के अन्तराल में data query करता है तथा text field में set कर देता है जिससे यह हमें text को बदलने ही नहीं देता है। आपसे निवेदन है जल्दी से इस समस्या को समाधान करो इससे पहले की किसी के रुपयों का बेमतलब में नुकसान न हो )

### Visual documentation

first : -

![first](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/718462de-ab1d-43a4-8136-191402d54a9e/6ee0367d-4ffb-4c2b-aaee-0f7c794f2687?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MTg0NjJkZS1hYjFkLTQzYTQtODEzNi0xOTE0MDJkNTRhOWUvNmVlMDM2N2QtNGZmYi00YzJiLWFhZWUtMGY3Yzc5NGYyNjg3IiwiaWF0IjoxNzExMTQ0Nzk4LCJleHAiOjMzMjgxNzA0Nzk4fQ.BXrFUwBHf1RFzOSYGauAJnMeY753QaQfvqPESBKS-Rw)

second :-

![second](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c84cdcd5-882c-48aa-ab24-1533a4291761/e3845bf5-c840-4d2a-9525-c0c4e7be64aa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jODRjZGNkNS04ODJjLTQ4YWEtYWIyNC0xNTMzYTQyOTE3NjEvZTM4NDViZjUtYzg0MC00ZDJhLTk1MjUtYzBjNGU3YmU2NGFhIiwiaWF0IjoxNzExMTQ0Nzk4LCJleHAiOjMzMjgxNzA0Nzk4fQ.W1sMK4eaM9UrZwWRwa0ezuKwlSgO6CBhA4BN7rdX6jg)

therd : -

![therd](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9b81a9ee-7b0c-44ef-9105-563043838196/4a15e8f0-a5da-4e2d-aeb8-319f6e6ac8a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YjgxYTllZS03YjBjLTQ0ZWYtOTEwNS01NjMwNDM4MzgxOTYvNGExNWU4ZjAtYTVkYS00ZTJkLWFlYjgtMzE5ZjZlNmFjOGExIiwiaWF0IjoxNzExMTQ0Nzk4LCJleHAiOjMzMjgxNzA0Nzk4fQ.xaabq-V5hemz5bA2WfQw2dZhEJtAaM1eOWfgzoxFU20)

fourth :-

![fourth](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ca9faeb2-3d96-4d18-8ba5-cdfaaf045334/ad5106f5-1ce2-4b2f-a9cb-c000b0838f3d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jYTlmYWViMi0zZDk2LTRkMTgtOGJhNS1jZGZhYWYwNDUzMzQvYWQ1MTA2ZjUtMWNlMi00YjJmLWE5Y2ItYzAwMGIwODM4ZjNkIiwiaWF0IjoxNzExMTQ0Nzk4LCJleHAiOjMzMjgxNzA0Nzk4fQ.IAaBJDeZ7WnFdYEqlisfuwC3iAT1nNsckzTp0882vaE)

video : -

[https://github.com/FlutterFlow/flutterflow-issues/assets/128114034/7c7acc09-e439-41f7-a648-f965cc1665f5](https://github.com/FlutterFlow/flutterflow-issues/assets/128114034/7c7acc09-e439-41f7-a648-f965cc1665f5)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 -Flutter 3.19.1
- Platform:all ( Web , ...)
- Browser name and version:chrome
- Operating system and version affected: windows 11
```

**Comment by Somimpkno** [comment]
Thank you for replying. 
                Yes, I'll let you know that it's still behaving as I described. 
   The mistake I see in your process is that you haven't applied a filter in the 'on change update' query and then changed the filter value using a dropdown. (For example, create a student collection with a student name and class field in each document, then filter based on student class later).

**Comment by ignalauret** [comment]
Hey @sominpkno I have tried what you suggested. So I added a field to my note data type called Author, added a dropdown with author names, and changed my query to be *author == $authorFilter*. I can still see only one execution of the query being done. <br>I understand what you are saying, that you are only changing the query filter and there has not been any document updated, so there shouldn't be a new execution of "On Data Changed". You need to understand that the query is being done on the Firebase side, so the query MUST be executed again to get the new data when you change the filter, even though there has not been any document update. <br>About your infinite updating loop, I'm sadly not able to replicate it. Could you try to replicate it from a Blank project and send me the Bug Report Code so I can look into it? <br>Thanks for your patience and your help.

**Comment by Somimpkno** [comment]
I have made this bug project public on the marketplace. If the FlutterFlow community approves it, you can check it out.
https://marketplace.flutterflow.io/item/PQIukVHLBpDjvQW27cZY

**Comment by leighajarett** [comment]
We would need steps from a blank project @Somimpkno

**Comment by Somimpkno** [comment]
I had seen this bug in my main project, and then when I added this function to another project, the same issue persisted there as well. Now, speaking of a blank project, let me tell you that for the marketplace project link I shared with you, I created a new account in FlutterFlow using my other email, and I also created a new Firebase account with that same email. And the first project created with this new account is also made for this bug. But the bug still persists here. Now, tell me, what more could be done for a blank project?

**Comment by leighajarett** [comment]
I'm simply asking you to describe the steps you took from a blank project, so we can follow the same steps to reproduce. Sorry if that wasn't more clear!

**Comment by Somimpkno** [comment]
"Thank you for responding. Even when I reported the bug, I provided these steps and shared the project, yet you're still asking for steps. I don't understand something. Let me explain again.

Bug project steps:
1. Create a blank project.
2. Connect the project with Firebase.
3. Create a User collection.
4. Create a Login page (email and password) with action.
   Now, I'm specifying the main steps that must be followed:
5. Create a student collection with fields (student_name {string}, student_class {integer}).
6. Now, create a blank page named "bug_report." In this page, follow the steps below:
   (A). First, add a column.
   (B). Then, add a container to the column.
   (C). Next, add a column to the container.
   (D). Then, add a text field (student name) and a drop-down (student class) that returns an integer. Define options and option labels from 1 to 10.
   (E). Next, within the same container column, add a save button (to create the student collection) along with the action to create the student collection.
   (F). Now, create a page state variable named "updatequerycount" with data type "integer" and default value "0".
   (G). Then, below this save button, add another container in the column with a text. In this container, create a query collection on the student collection, filtering by student_class (default "1"), and keeping single-time query false. Save it.
   Now, on the "on change update" of this container, apply a conditional action (assuming query collection of student is not empty and set). On both conditions (true and false), apply an action to update the page state variable (updatequerycount) by incrementing it from 1.
   Finally, display the value of this page state variable (updatequerycount) in the text of the same container.
   (H). Now, run it. After logging in, when you fill in any name and create a document in the student collection (by clicking the save button), you'll see how quickly the value of the page state variable displayed in the container's text changes.

Note: This event occurs even if some documents in the student collection are created and we change the filter value."

If you still don't understand, you can share your email with me so that I can share the project with you as a viewer.





IN HINDI  : -- धन्यवाद आपको reply देने के लिए  | 
 मैं bug report करते समय भी इन step को बता चुका हूं  साथ project भी share कर चुका हूं  फिर भी आप step की मांग कर रहे हैं  मेरे समझ में नहीं आया कुछ  | चलो फिर से बता देता हूं  | 
Bug project step - 
1. एक blank project create करें 
2.  firebase  से project को connect करें 
3 . User collection बनायें 
4 . Login page बनायें  ( email and  password  )  with action . 
     अब मुख्य step बता रहा हूं  यह होनी ही चाहिए :-
5. एक student collection बनायें उसके field (  student_name { string} , student _class {integer } )  रखें 
6. अब एक blank page create करें माना उसका नाम "  bug_report " है  इस page में निम्न step follow करनी है :- 
 (A) .     पहले एक column add करें 
 (B).      फिर column में एक container add करें 
 (C).     फिर container में एक column add करें 
 (D).     फिर  container में एक text field ( student  name ) add करें , साथ ही एक drop-down( student  class ) भी add करें जो integer return करें  | drop-down  define options  and options labels 1 to 10 है | 

( E)      फिर इसी container column में एक save button ( student collection create करने के लिए ) भी add  कर दें साथ ही  student collection create करने का action भी लगा दें | 

( F) .     अब एक page state variable बनायें  ( जिसका नाम " updatequerycount " रखें  तथा  data type " integer "   व default value "  0 " रखें ) 

( G).       फिर इसी save button के निचे  button वाले column में ही एक और container add करें व container में text add करें |  इसी container पर  student collection पर query collection  वो भी student _class  को filter (default " 1" ) बनाते हुए  ( यहां filter value आप पहले बनायें गये drop-down का भी उपयोग कर सकते हैं  या ओर drop-down filter भी बना सकते हैं ) तथा single time query  को false  रखते हुए save करें  |   
 अब इसी container पर "  on change update "  पर एक  conditional action ( माना query collection of student not empty and set ) लगायें   | अब इसकी दोनों condition ( true and false ) पर page state variable   ( updatequerycount)  update action ( 1 से increment ) लगायें |  
अन्त में आप इस page state variable   ( updatequerycount) की value को इसी container के text में  show करें | 

( H).       अब आप इसे run करें तथा login के बाद कोई भी name fill करते हुए student collection का document create ( save button ) करें तो आप देखेंगे कि page state variable value जो हमने container के text में show की थी वह कितनी शीघ्रता से बदल रही है 

Note :-     यह घटना ही यदि कुछ document student collection के create किये गये है तथा हम filter value बदलते हैं तो भी होती है | 


यदि आपको अब भी समझ में न आया हो तो आप मुझे कोई अपनी email बता दें जिसे मैं project में viewer  की अनुमति देते हुए आपको project share कर सकूं |

**Comment by ignalauret** [comment]
Hey @somimpkno sadly I've tried exactly what you sent and I have not been able to get the same behaviour. Could you please reproduce it on a blank project and share me the Debug Code so the technical team can take a look. I know it's extra work, but we really want to resolve your issue and without having a project with the behaviour we are not going to be able to.<br>Thanks again for the effort, have a great day!

**Comment by Somimpkno** [comment]
Thank you for your reply.
   However, I regret to inform you that I haven't been able to understand it yet. In this [YouTube video](https://youtu.be/wcUIwuBigMc?feature=shared
), I have demonstrated this project as a new project. If you follow this video and create it, you will be able to identify this bug.

**Comment by ignalauret** [comment]
@Somimpkno thanks for the clarifying video. Following the video I was able to replicate the issue. I think the problem is the Query being done on the Text Widget that shows the update Count, and this is generating an infinite rebuilding loop. However I will send this to the technical team so they can take a look and give you an answer on this thread. Thanks for helping me replicate the bug, have a great day!

**Comment by ValetCEO** [comment]
Is this going to be assigned to someone to resolve? I'm having a similar issue with 'on-data-change' but it doesn't look like any progress has been made since the issue was raised.

**Comment by ValetCEO** [comment]
Hi, still chasing for an update on this, will this be re-assigned?

**Comment by ValetCEO** [comment]
@leighajarett what's going on with this? I was speaking to support on this and they said it was being worked on but it's now been closed ?

**Comment by Alezanello** [comment]
Hello everyone,

Apologies for the lengthy thread and the time it’s taken to address this issue. At the moment, I’m unable to replicate the behavior on my end.

Could anyone please share a bug report code or a video demonstrating the issue? It's possible that the latest FlutterFlow updates have resolved it, but if you’re still encountering this problem, your input would be invaluable.

Thank you for your patience and support! I look forward to your updates.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
