### ISSUE TITLE
filepicker popup not loading when in testmode

### ISSUE THREAD

**Issue by Willemglasbergen** [FlutterFlow/flutterflow-issues#2577]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All my Flutterflow apps that use the filepicker to pick images or video have the same issue. When clicking a button with this action assigned to it, the file picker is not shown. So I can't select files from my laptop for uploading them to Firebase.
I prepared a really simple FF app to show the issue: testpicker-npki8v

### Expected Behavior

When clicking a button that has the "store media for upload"-action defined, a window should popup showing the local folder with files that I can select.
Note: when published to web or when hosted on Firebase, all seems to work fine. So I think this is only a problem in test mode.

### Steps to Reproduce

1. start new project
2. add one button
3. asign the action "store media for upload" to button
4. run app in test mode
5. click button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89PseFa1c/uYO9V+ScUQ2F7bb00st5Hd0gdCOPrBqQQeszSXFVucN+7aVNcEVD/pGMG0taKhYTLMPQqZDCeGKVxwbVUdDrke2iXRJSSCquwSHR6BdhbfGbF16uOkx5NAMRYLXgO6k+AGd6vEnXDBOu/Zwh9f6PHaOI=

### Context

I have several apps for which I need to upload files. 

### Visual documentation

<img width="1487" alt="Scherm­afbeelding 2024-03-22 om 08 43 02" src="https://github.com/FlutterFlow/flutterflow-issues/assets/164473847/4fe056e2-2915-4ff0-b6b3-4059c85dba71">
<img width="1481" alt="Scherm­afbeelding 2024-03-22 om 08 40 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/164473847/fad33c2e-f622-4e63-b691-2a94fcdb2eb3">
![Scherm­afbeelding 2024-03-22 om 08 38 16](https://github.com/FlutterFlow/flutterflow-issues/assets/164473847/ea01d388-7c85-412c-8a16-0d73396d6577)

### Environment

```markdown
- FlutterFlow version: 4.1 flutter 3.19.1
- Platform: Web
- Browser name and version: Chrome  122.0.6261.112
- Operating system and version affected: macOS
```

**Comment by Willemglasbergen** [comment]
Hi Hari,

I do not think it had to do with blocking popups. It seems that doing the latest update of Chrome solved the problem.

Currently it is solved and everything is working fine.

Met vriendelijke groet,
 
Willem Glasbergen
UX/UI designer



￼
 
￼



|  Outline solutions
|  06-42018123
|  Ruiterskwartier 119A, 8911BS Leeuwarden
|  www.outlinesolutions.nl

**Comment by bozzoleandro** [comment]
Hi @willemglasbergen, since this is not a bug, and the problem that you were having has been resolved with a Chrome update, will close this bug. Thanks!

**Comment by mredodos** [comment]
i have same beahvior with edge last versione all permission is active

**Comment by dinegredin** [comment]
I have the same problemon mac os 15.4. I have tested it on chrome, firefox and safari. the pop up never appears on test mode. Did you manage to find a solution ?

**Comment by Willemglasbergen** [comment]
For me an update of Chrome seemed to solve the problem although I'm not 100% sure that this was indeed causing the bug. It currently works without any problems so I moved on.
