### ISSUE TITLE
Issue with the Scroll Until Visible Automated Test

### ISSUE THREAD

**Issue by TestdeviceAcc** [FlutterFlow/flutterflow-issues#2578]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is not scrolling the page and facing the issue in the local environment " Bad element".
Tried with most of the possibilities like find by value, find by widget etc and with different steps as well. But unable to scroll the page.

### Expected Behavior

It should scroll the widgets in the page

### Steps to Reproduce

1. Create a page which will have scrollable widgets and give the value key.
2. Create the automated test to scroll the elements.
3. Download the code and run the test.dart file.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfKBw4lOsfpE0LruY8dB/GAUJV97a7gSscp/bxIgGIDzPOw+ZPWkP1RBZMu5dwhII0Smmjge3PDLj+LqUfo3Ez+aY4g5/7lxExbMQmSnUZOBBqiVPURQEfJhIECu0p+NniJAPut1ZUIbwF6mH/K/bDTdJueyImdISq/LZO4=

### Context

Unable to test the page scrolling

### Visual documentation

![Automated_test](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8136848c-bc42-4200-8146-f1a6798c267f/76794e42-d880-481f-9c2d-e5522133da66?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MTM2ODQ4Yy1iYzQyLTQyMDAtODE0Ni1mMWE2Nzk4YzI2N2YvNzY3OTRlNDItZDg4MC00ODFmLTljMmQtZTU1MjIxMzNkYTY2IiwiaWF0IjoxNzExMTMxMTY1LCJleHAiOjMzMjgxNjkxMTY1fQ.VDZRWDnevppQCqHdPcRgny8QxkEX-dPO3JoZB3MazYE)

### Additional Info

Project: [https://enterprise.flutterflow.io/project/scroll-test-4i58nj?tab=pageSelector&page=HomePage](https://enterprise.flutterflow.io/project/scroll-test-4i58nj?tab=pageSelector&page=HomePage)

### Environment

```markdown
- FlutterFlow version:
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected:
```

**Comment by szymonpodwyszynski** [comment]
Hi, i can confirm that i also have this issue. No matter the configuration, the scroll on automation tests is not working.

**Comment by leighajarett** [comment]
Thank you for the information! We have confirmed this bug on our side and are working on a fix

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. The fix will be released soon.

But also in the attached project you selected incorrect scrollable: you should select the column containing the containers as your scrollable instead.
