### ISSUE TITLE
Bug in 'add action to Textfield'

### ISSUE THREAD

**Issue by richard-lifegroup** [FlutterFlow/flutterflow-issues#2579]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When clicking on the choices for what prompts an action on a textfield, the pull down continues to obscure the following choices.

### Expected Behavior

The following menu items should be available

### Steps to Reproduce

Should be fairly easy to reproduce

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KhfKAz5J2m/VA7pDtbcAxmicWNjM2bZE4lutDa0wcJbL0G7YMWvfObhJeZ+m+THxcL2GknToy+d7JhuDuA+UoC06af6p9z6tQQzmVXmquM7qbPauNdnAkO9NJJVPG1ruFpBNAFLdZSWQt2E+YHtitFxHcQoz1IFQ/PvmKCN/Is12pQ0SLb3kNh1JWeC/v

### Context

I am trying to add actions to Textfelids 'on Focus Change' but cannot complete this.

### Visual documentation

![screenshot1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a5d13824-ff26-4de8-b154-c8118aecdf7e/b6437472-a286-4911-ab1d-559b64cd41d3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNWQxMzgyNC1mZjI2LTRkZTgtYjE1NC1jODExOGFlY2RmN2UvYjY0Mzc0NzItYTI4Ni00OTExLWFiMWQtNTU5YjY0Y2Q0MWQzIiwiaWF0IjoxNzExMTAyNDg1LCJleHAiOjMzMjgxNjYyNDg1fQ.r6SwwdtN_wydlhHVwe5ahxqesokcDPcWolY0snBX7cU)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Windows 10
- Browser name and version: Chrome 122.0.6261.129 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @richard-lifegroup - Thank you for submitting the issue. I attempted to replicate the problem using the details provided above, but everything appears to be working correctly on my end. If you believe the issue persists on your end, please provide additional details to help reproduce the problem, and consider including a brief video demonstration, as this would be more helpful in investigating the issue further. Thank you.
