### ISSUE TITLE
App Store Push Notification Entitlement Warning when Push Notifications Have Never Been Enabled.

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#258]
In my attempt to troubleshoot a push notifications error that has prevented me usign push notifications since the last 6 months, I went ahead and create a completely new app from scratch and came across an Apple App Store Connect post-deployment warning about push notifications when push notifications haven't even been enabled on Flutterflow or on the app's Apple developer identifier.

The warning message is: 

`ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.`

Please see screenshots below about app config on Apple Developer and Flutterflow. Please note this app is brand new and less than a few hours old. The setup of the app was followed letter by letter. And most importantly no push notifications were enabled either as identifier entitlements or on flutterflow's dashboard.

![Screenshot 2022-12-21 at 15 14 16](https://user-images.githubusercontent.com/72607/208925696-b48c2150-e9e3-4c53-afbc-ccd4b0fad492.png)

![Screenshot 2022-12-21 at 15 14 07](https://user-images.githubusercontent.com/72607/208925715-37961de1-51a3-40a8-87e3-5e50520f82f3.png)

![Screenshot 2022-12-21 at 15 13 54](https://user-images.githubusercontent.com/72607/208925729-d92a498b-a5fa-41fb-b5e4-e586c895f2fa.png)

**Comment by bulgariamitko** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by isegal** [comment]
Just a wild guess: Does your project have Firebase authentication enabled? It might be related to FCM requiring a notification permission.

**Comment by agreaves** [comment]
Hi @davhad, in order to better assist, please respond with a Bug Report Code for both the old project (that was failing) and the new project you created. Thanks!

**Comment by davhad** [comment]
> Just a wild guess: Does your project have Firebase authentication enabled? It might be related to FCM requiring a notification permission.

@isegal yes it's got authentication enabled.

**Comment by davhad** [comment]
> This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance. If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce. Thank you for your contribution!

@bulgariamitko definitely a general issue. Tried another project, followed push notifications instructions to the tee, same issue. Will update t o highlight.

**Comment by davhad** [comment]
> Hi @davhad, in order to better assist, please respond with a Bug Report Code for both the old project (that was failing) and the new project you created. Thanks!

@agreaves yes sure, I'll share the bug report code for the new project because it's infinitely simpler having been created yesterday for the purpose of better understanding push notifications: ITESiPLqx4VgodxI14fyKMZQhQIgQ0QnU7gnlO1ucx4YC73mOu0uP87BdUNKT/alTW1qJ0yZjjkFzPzohobTIfQECzaVY4Rzk/UwKlCvHAM=

**Comment by bulgariamitko** [comment]
Ok I will change the status to can't reproduce and let's see what the FF team have to say about this as I can't reproduce the issue.

**Comment by isegal** [comment]
@bulgariamitko try with Firebase authentication enabled, I believe this has to do with SMS-based authentication support which requires FCM.

**Comment by agreaves** [comment]
Thanks @davhad for that bug report code, I now understand the issue a bit better. This is actually just a warning that arises in some Flutter apps that is not actually a problem. See [this Flutter issue](https://github.com/flutter/flutter/issues/9984) (and [this one](https://github.com/flutter/flutter/issues/14182)).

The long story short is this warning sometimes comes up for Flutter builds and in fact **can be safely ignored**. It should not affect your submission to the app store. Regardless, this is not a FlutterFlow level issue so there isn't much we can do about it besides point you to those resources.

As a side note, the new project does currently use Push Notifications, is that a recent addition?

**Comment by davhad** [comment]
@agreaves Ok thanks for clarification as to the source of the issue. Yes it was a recent addition done as part of testing.
