### ISSUE TITLE
JSON initial value setting in text field not working

### ISSUE THREAD

**Issue by VenzpireZero** [FlutterFlow/flutterflow-issues#2580]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

JSON initial value setting in text field not working

### Expected Behavior

JSON initial value setting in text field should work

### Steps to Reproduce

1. Setting a JSON initial value setting in text field not working in component

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmB+cpgrsdc1aqNacJ7/ToXNlwna7grm8NxeEs3C7avPYwPXPykP1doTcOiTFZYMFv8hXw0p9bOvdnyV+QHAE2WUap9z7lqag/LZEelb7qtPLWOfGpSAf1WJEuV1J6RpyZSJrJuV11gwGDzNti/QT7dCZzNO2ojHuSXNdnNgWyaAj+6Xn0Jg1ZSfCvr

### Context

Setting a JSON initial value setting in text field not working in component

### Visual documentation

![Capture3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b16bce01-5ecb-4783-a4f7-db08ef102d73/6030a334-1967-40ad-bee8-987bb81cc41c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMTZiY2UwMS01ZWNiLTQ3ODMtYTRmNy1kYjA4ZWYxMDJkNzMvNjAzMGEzMzQtMTk2Ny00MGFkLWJlZTgtOTg3YmI4MWNjNDFjIiwiaWF0IjoxNzExMTE5MTc3LCJleHAiOjMzMjgxNjc5MTc3fQ.l-vJ6gMP5Qr8HyIg1ubG6AJDGv93Euq1DhnAAtah1b0)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: In all platforms
- Browser name and version: Firefox
- Operating system and version affected: All systems
```

**Comment by ignalauret** [comment]
Hey @VenzpireZero thanks for your report. Could you please share the component that you are using and the exact steps that I should follow to reproduce your bug?

**Comment by VenzpireZero** [comment]
> Hey @VenzpireZero thanks for your report. Could you please share the component that you are using and the exact steps that I should follow to reproduce your bug?

Hi @ignalauret , If trying to set the number value from JSON to textfield initial value means, It's not showing. Getting NULL value only. This issue faced in initial value only. In hint value it's working fine

**Comment by ignalauret** [comment]
I was able to understand your issue. Sadly I can't run your app to see if it's working or not, but I replicated it on a blank project and the text field initial value inside a component looks to be working correctly, so there must be an issue with the integration with your API call and the Widget. 
Please feel free to contact our Customer Support for project specific help to achieve what you are looking for. 

Have a great day.
