### ISSUE TITLE
Unable to log into FlutterFlow Windows Desktop App using Google Sign-in

### ISSUE THREAD

**Issue by phil528i** [FlutterFlow/flutterflow-issues#2582]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

\\\[From Luiz Eduardo Silva\\\] Firstly, on the login screen there is no way to log in socially with Google, I created my account using social login and I can't log in to the system. When I click on create account, where the "Login with Google" button will appear, I click on the button and a blank screen appears and when I close this screen, it closes the entire system. ( [Original post](https://community.flutterflow.io/discussions/post/bug-on-flutterflow-desktop-windows-U3XWNNhIgKaxgBd) which includes a video).

### Expected Behavior

Sign-in with Google works.

### Steps to Reproduce

1. Launch the Windows Desktop App
2. Select "Create Account".
3. Attempt to sign in using Google by pressing the button.
4. Fail to log in and see blank screen.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

Can't log in to the FlutterFlow Desktop App

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3a2f6585-1e9f-40ae-b102-07516499ae5e/7bc4323e-41ff-4d6a-b84b-ce5ae333ae5b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYTJmNjU4NS0xZTlmLTQwYWUtYjEwMi0wNzUxNjQ5OWFlNWUvN2JjNDMyM2UtNDFmZi00ZDZhLWI4NGItY2U1YWUzMzNhZTViIiwiaWF0IjoxNzExMTM4NTM2LCJleHAiOjMzMjgxNjk4NTM2fQ.Ba-\_NyRJZ8vPkjK6O5P1yIcReufLfchC33bXM8ptqUk "=949x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: Windows Desktop App 4.1.33
- Platform: Windows
- Browser name and version: N/A
- Operating system and version affected: Win 11 Pro
```

**Comment by gentleVirus** [comment]
Had the same issue. With "Forgot Password" you can create a new password and log in manually. Nevertheless a working Google Sign In would be more convenient.

**Comment by EdoSag** [comment]
Same thing happening here, I was excited for the Windows version, but unfortunately it doesn't allow social log ins...

**Comment by deviak13** [comment]
same here, would love to use it but I am unable to log in with my Google account...

**Comment by webflavor** [comment]
same issue here! Will stick to the web version until this is available

**Comment by iamhsong** [comment]
Excited for having desktop version released... Disappointing at the same time as Google sign in is not working. 
Have to stick to web version until this is fixed and hope the update will be available soon.

**Comment by 21stfloor** [comment]
Please fix this

**Comment by zeymermontes** [comment]
I think this is an issue with flutterfire now supporting social logins in windows. Windows support for firebase has been around just for a couple of months. Its amazing the FF team managed to run FF on windows so fast. I think this is more on the Firebase side than on FF.

**Comment by kevin-smets** [comment]
+1
Was excited to try out the local run feature, but sadly the Google sign-in doesn't work. Even worse, when I close it, the Flutterflow app just crashes.

**Comment by phil528i** [comment]
Saw the email update today, got the latest version (4.1.36), noticed that there is now a "Sign-in with Google" button directly on the log-in screen (nice work there). Clicked it, it opened a Google credentials page and I then clicked Continue about the services it was already using, then login verification completed and I was in the app. Good fix!

**Comment by leighajarett** [comment]
Great! Glad it's working well!
