### ISSUE TITLE
intigers variable in the body of an api causes error

### ISSUE THREAD

**Issue by hossamahmed9999** [FlutterFlow/flutterflow-issues#2586]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![17111686818202416697966577143146](https://github.com/FlutterFlow/flutterflow-issues/assets/164600218/4b30b37c-0d13-4408-970a-dc6ef06b6223)
i tried every thing to make it work but it cant be solved
![1711169013394418416495252564687](https://github.com/FlutterFlow/flutterflow-issues/assets/164600218/e93c042c-1d84-43ed-9437-49fdda4697e7)
![17111690569997906452375926119794](https://github.com/FlutterFlow/flutterflow-issues/assets/164600218/bc7cdfc2-884d-4ce3-9ccf-5e993aa64cf3)
i tried to remove default values the same erro so i tried to link it to a state variable with of datatype intiger it gives the same error i tried to remove the variable and put the intiger direct it gives mee 200 status 
this problem is only with intigers for me because when i leave the variable of string which equals somthing for now the test gives me 200 satus 

### Expected Behavior

when i remove the intiger variables and put the intigers values the api test success 
![17111695282863842665611703611496](https://github.com/FlutterFlow/flutterflow-issues/assets/164600218/87fd54b3-f84f-413a-a87b-03514113e3ba)
![17111695599304754563026619139982](https://github.com/FlutterFlow/flutterflow-issues/assets/164600218/92e3e144-d102-4c9c-bb3d-3a4d07c945cb)
it seems like the intiger variable itself has a problem because the string variable is made with same steps and it doesnt give an error 

### Steps to Reproduce

1 created the api name then post type then the url 
2 made a hson body with the sutable syntax 
3 test the api and gives me 200 statuse
4 made a string variabe then link it to a value then test it gives me 200 status 
5 made an intiger variable and link it to a value then test it so it gives an error
6 i tried to put string in double quotes so the respond from api tells me that its not an intiger 
7 i put an intiger instead of the variable it gives 200 status

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

{"message": "invalid request.","errors "101"}

### Context

.

### Visual documentation

i cant add video because i have a token

### Additional Info

v3.1    
web
chrome
windows

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bozzoleandro** [comment]
Hi @hossamahmed9999, thanks for yor report, we're not able to reproduce it, are you still experiencing this issue?
