### ISSUE TITLE
List of DataType are detected as "Unknown" Type in the Condition "List Contains Item"

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#2587]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

List of Predefined DataType can contain the DataType.
But "List Contains Item" condition can not detect its type.

### Expected Behavior

"List Contains Item" condition detect its type.

### Steps to Reproduce

1. Create DataType
2. Create Page State of List<No.1's DataType>
3. Make Condition "List Contains Item" for No.2

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8jq3ItOm8sC1a6Jd+1Wnj4sH2UcTIMziNZ+exUbfaL1BqQqecjBXxJuONSqaVNcP2eirEgBp9XFhvP1JvdeGzSCGq5cyKphEQvee2imRrKgEaWoX0d8DfhUCn6s37uk2xQlKu5eSVIT2Wb7AuzLZADDFOu/Zwh9f6PHaOI=

### Context

Can not use data type for List.

### Visual documentation

Page State of List of userSnippet Data Type.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/817d05a5-5eb5-436b-9a6e-bef85ec3921e)

"List Contains Item" condition can't detect its type and show that "Type: Data (Unknown)"
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/7dd9762c-12a9-4890-8f07-1535e63fba58)

Fundamental type (like Integer) can be detect as "Type: Integer".
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/653ea8fa-4185-4149-a2bb-ad8a9127d3a9)

### Environment

```markdown
- FlutterFlow version: 4.1.34
- Platform: MacOS Desktop
- Browser name and version: Chrome 122.0.6261.129
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by bozzoleandro** [comment]
Hi @ryutosh, thanks for your report. We were able to replicate the issue, we're looking into it.

**Comment by leighajarett** [comment]
Hi, this issue has been fixed and will be available in the product in the next week or two

**Comment by cobus-meyer** [comment]
> Hi, this issue has been fixed and will be available in the product in the next week or two

Hi Leigha. I am currently on V4.1.65 and still experiencing the same issue, just wanted to check if this fix has been released yet?

**Comment by leighajarett** [comment]
We decided not to release a new version of FF yesterday because we are still working on a few things. But it will be included in the release next week - sorry for the delay!
