### ISSUE TITLE
Parallel actions do not work properly in Flutterflow Windows.

### ISSUE THREAD

**Issue by cleberorati** [FlutterFlow/flutterflow-issues#2589]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

To reproduce the problem, simply use FlutterFlow Windows and edit a parallel action in any widget, add, for example, two more actions in a parallel action then when deleting one of the four actions it does not disappear, then if the screen of actions is closed it is no longer possible to open it when clicking on the open button, however if we access the project in the web interface it is possible to open the actions and verify that in the edited parallel action there are 3 actions. If this third action is deleted in the web interface then access to the actions works again in FlutterFlow Windows when you click open.

### Expected Behavior

It's a bug. Simply follow the steps I described to verify the failure.

### Steps to Reproduce

1.On Flutterflow Windows insert a parallel action
2.Add two more action into the parallel action
3.Delete the fourth action to see that it does not disappear from the diagram
4.Close the action screen
5.Click on the Open (actions) button and you will see that nothing happens
6.Open Flutterflow web and then open the problem widget
7.Click to open actions and you will see it works
8.Check that the parallel action contains 3 built-in actions, that is, the deletion happened in FlutterFlow Windows although it did not show properly
9.Delete the third action within the parallel action
10.Open FlutterFlow Windows and now see that everything is back to normal, as long as no more actions are inserted in the parallel action.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflsjfz4VNobxA0b6JKO5ViiovQ3kcTIMziNZ+exUbfaL1BqQQe+POVBRBQtyqaVNcOVqWmkQe0amKkuPTMsEFOkybUaFz+LpUUQnOe2i5aLKSPKiwRH98AcVgf2KM4auv2BN5PbdfSWQD32D7Hem+dBLDFOu/Zwh9f6PHaOI=

### Context

I am unable to work with FlutterFlow Windows properly due to the issue.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/17750095/33bd77f6-12f0-4a48-9247-ea65c4e8c72e](https://github.com/FlutterFlow/flutterflow-issues/assets/17750095/33bd77f6-12f0-4a48-9247-ea65c4e8c72e)

[https://github.com/FlutterFlow/flutterflow-issues/assets/17750095/71e1360a-2897-4a5f-a8f9-26671bf3c1d4](https://github.com/FlutterFlow/flutterflow-issues/assets/17750095/71e1360a-2897-4a5f-a8f9-26671bf3c1d4)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.33+
- Platform:Windows
- Browser name and version: Google Chrome 122.0.6261.131
- Operating system and version affected: Windows 10 Pro
```

**Comment by sabatage3** [comment]
I'm having the same issue. Any idea when it will be fixed in the Windows app?

**Comment by bfosberry** [comment]
Im seeing similar issues but much more broadly. Im using Flutterflow Windows and changes are NOT being synced. Files (custom functions/actions) I've added in the web ui do not get created in flutterflow windows, and it will overwrite my state and remove files in the web ui. It's impossible to use atm due to sync issues.

**Comment by MrRongoose** [comment]
This exists as an issue with the Mac app as well

**Comment by Bar343** [comment]
This also happens in the web version. Even move action or up/ down does not work. it seems the parallel action in general is quite buggy on all platforms.
