### ISSUE TITLE
Deployment Logs Gray Screen in Flutterflow Mac App

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#259]
In the Mac app (doesnt' concern the web app), the deployment logs are not visible when clicking on the Latest Status: Logs link. Please see attached screenshot of the gray screen bug. Using 1.1.26 But this has been an issue in some of the previous issues as well but not always an issue. So this bug must have been introduced in a recent update from the last few weeks I would guess.

![Screenshot 2022-12-21 at 15 22 12](https://user-images.githubusercontent.com/72607/208927311-cf35e097-d946-4012-90c2-20fd87622462.png)

![Screenshot 2022-12-21 at 15 19 20](https://user-images.githubusercontent.com/72607/208927175-39962b68-d5a5-4388-b227-8dac6824ccde.png)

**Comment by wenkaifan0720** [comment]
@agreaves, I still couldn't register as an Apple Developer so I can't really debug this issue. Could you take a look? Thanks!

**Comment by agreaves** [comment]
Hi @davhad, is this still occurring? And if so, could you please include a Bug Report Code? Thanks.

**Comment by wenkaifan0720** [comment]
I can see the log screen now as of today. Closing this issue.
