### ISSUE TITLE
Выдает неизнанную ошибку при создании пользовательского виджета

### ISSUE THREAD

**Issue by Steelynss** [FlutterFlow/flutterflow-issues#2590]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

/// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

//import '/backend/backend.dart';

import 'package:just_audio/just_audio.dart';
import 'package:audio_session/audio_session.dart';
import 'package:rxdart/rxdart.dart';
import 'dart:math';

void main() => runApp(const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: AudioCustomWidget(),
    ));

class AudioCustomWidget extends StatefulWidget {
  const AudioCustomWidget({Key? key}) : super(key: key);

@override
  AudioCustomWidgetState createState() => AudioCustomWidgetState();
}

class AudioCustomWidgetState extends State
    with WidgetsBindingObserver {
  final \_player = AudioPlayer();

Future \_init() async {
    final session = await AudioSession.instance;
    await session.configure(const AudioSessionConfiguration.speech());
    \_player.playbackEventStream.listen((event) {},
        onError: (Object e, StackTrace stackTrace) {
      print('A stream error occurred: $e');
    });
    try {
      await \_player.setAudioSource(AudioSource.uri(Uri.parse(
          "[https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3](https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3)")));
    } catch (e) {
      print("Error loading audio source: $e");
    }
  }

@override
  void dispose() {
    ambiguate(WidgetsBinding.instance)!.removeObserver(this);
    \_player.dispose();
    super.dispose();
  }

@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      \_player.stop();
    }
  }

Stream get \_positionDataStream =>
      Rx.combineLatest3(
          \_player.positionStream,
          \_player.bufferedPositionStream,
          \_player.durationStream,
          (position, bufferedPosition, duration) => PositionData(
              position, bufferedPosition, duration ?? Duration.zero));

@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: \[
            ControlButtons(\_player),
            StreamBuilder(
              stream: \_positionDataStream,
              builder: (context, snapshot) {
                final positionData = snapshot.data;
                return SeekBar(
                  duration: positionData?.duration ?? Duration.zero,
                  position: positionData?.position ?? Duration.zero,
                  bufferedPosition:
                      positionData?.bufferedPosition ?? Duration.zero,
                  onChangeEnd: \_player.seek,
                );
              },
            ),
          \],
        ),
      ),
    );
  }
}

class ControlButtons extends StatelessWidget {
  final AudioPlayer player;

const ControlButtons(this.player, {Key? key}) : super(key: key);

@override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: \[
        IconButton(
          icon: const Icon(Icons.volume_up),
          onPressed: () {
            showSliderDialog(
              context: context,
              title: "Adjust volume",
              divisions: 10,
              min: 0.0,
              max: 1.0,
              value: player.volume,
              stream: player.volumeStream,
              onChanged: player.setVolume,
            );
          },
        ),
        StreamBuilder(
          stream: player.playerStateStream,
          builder: (context, snapshot) {
            final playerState = snapshot.data;
            final processingState = playerState?.processingState;
            final playing = playerState?.playing;
            if (processingState == ProcessingState.loading ||
                processingState == ProcessingState.buffering) {
              return Container(
                margin: const EdgeInsets.all(8.0),
                width: 64.0,
                height: 64.0,
                child: const CircularProgressIndicator(),
              );
            } else if (playing != true) {
              return IconButton(
                icon: const Icon(Icons.play_arrow),
                iconSize: 64.0,
                onPressed: player.play,
              );
            } else if (processingState != ProcessingState.completed) {
              return IconButton(
                icon: const Icon(Icons.pause),
                iconSize: 64.0,
                onPressed: player.pause,
              );
            } else {
              return IconButton(
                icon: const Icon(Icons.replay),
                iconSize: 64.0,
                onPressed: () => player.seek(Duration.zero),
              );
            }
          },
        ),
        StreamBuilder(
          stream: player.speedStream,
          builder: (context, snapshot) => IconButton(
            icon: Text("${snapshot.data?.toStringAsFixed(1)}x",
                style: const TextStyle(fontWeight: FontWeight.bold)),
            onPressed: () {
              showSliderDialog(
                context: context,
                title: "Adjust speed",
                divisions: 10,
                min: 0.5,
                max: 1.5,
                value: player.speed,
                stream: player.speedStream,
                onChanged: player.setSpeed,
              );
            },
          ),
        ),
      \],
    );
  }
}

class SeekBar extends StatefulWidget {
  final Duration duration;
  final Duration position;
  final Duration bufferedPosition;
  final ValueChanged? onChanged;
  final ValueChanged? onChangeEnd;

const SeekBar({
    Key? key,
    required this.duration,
    required this.position,
    required this.bufferedPosition,
    this.onChanged,
    this.onChangeEnd,
  }) : super(key: key);

@override
  SeekBarState createState() => SeekBarState();
}

class SeekBarState extends State {
  double? \_dragValue;
  late SliderThemeData \_sliderThemeData;

@override
  void didChangeDependencies() {
    super.didChangeDependencies();

```
_sliderThemeData = SliderTheme.of(context).copyWith(
  trackHeight: 2.0,
);
```

}

@override
  Widget build(BuildContext context) {
    return Stack(
      children: \[
        SliderTheme(
          data: \_sliderThemeData.copyWith(
            thumbShape: RoundSliderThumbShape(),
            activeTrackColor: Colors.blue.shade100,
            inactiveTrackColor: Colors.grey.shade300,
          ),
          child: ExcludeSemantics(
            child: Slider(
              min: 0.0,
              max: widget.duration.inMilliseconds.toDouble(),
              value: min(widget.bufferedPosition.inMilliseconds.toDouble(),
                  widget.duration.inMilliseconds.toDouble()),
              onChanged: (value) {
                setState(() {
                  \_dragValue = value;
                });
                if (widget.onChanged != null) {
                  widget.onChanged!(Duration(milliseconds: value.round()));
                }
              },
              onChangeEnd: (value) {
                if (widget.onChangeEnd != null) {
                  widget.onChangeEnd!(Duration(milliseconds: value.round()));
                }
                \_dragValue = null;
              },
            ),
          ),
        ),
        SliderTheme(
          data: \_sliderThemeData.copyWith(
            inactiveTrackColor: Colors.transparent,
          ),
          child: Slider(
            min: 0.0,
            max: widget.duration.inMilliseconds.toDouble(),
            value: min(\_dragValue ?? widget.position.inMilliseconds.toDouble(),
                widget.duration.inMilliseconds.toDouble()),
            onChanged: (value) {
              setState(() {
                \_dragValue = value;
              });
              if (widget.onChanged != null) {
                widget.onChanged!(Duration(milliseconds: value.round()));
              }
            },
            onChangeEnd: (value) {
              if (widget.onChangeEnd != null) {
                widget.onChangeEnd!(Duration(milliseconds: value.round()));
              }
              \_dragValue = null;
            },
          ),
        ),
        Positioned(
          right: 16.0,
          bottom: 0.0,
          child: Text(
              RegExp(r'((^0\*\[1-9\]\\d\*:)?\\d{2}:\\d{2}).\\d+$')
                      .firstMatch("$\_remaining")
                      ?.group(1) ??
                  '$\_remaining',
              style: Theme.of(context).textTheme.bodySmall),
        ),
      \],
    );
  }

Duration get \_remaining => widget.duration - widget.position;
}

class PositionData {
  final Duration position;
  final Duration bufferedPosition;
  final Duration duration;

PositionData(this.position, this.bufferedPosition, this.duration);
}

void showSliderDialog({
  required BuildContext context,
  required String title,
  required int divisions,
  required double min,
  required double max,
  String valueSuffix = '',
  required double value,
  required Stream stream,
  required ValueChanged onChanged,
}) {
  showDialog(
    context: context,
    builder: (context) => AlertDialog(
      title: Text(title, textAlign: TextAlign.center),
      content: StreamBuilder(
        stream: stream,
        builder: (context, snapshot) => SizedBox(
          height: 100.0,
          child: Column(
            children: \[
              Text('${snapshot.data?.toStringAsFixed(1)}$valueSuffix',
                  style: const TextStyle(
                      fontFamily: 'Fixed',
                      fontWeight: FontWeight.bold,
                      fontSize: 24.0)),
              Slider(
                divisions: divisions,
                min: min,
                max: max,
                value: snapshot.data ?? value,
                onChanged: onChanged,
              ),
            \],
          ),
        ),
      ),
    ),
  );
}

T? ambiguate(T? value) => value;

### Expected Behavior

I expected the code to compile after fixing all the errors

### Steps to Reproduce

![Снимок экрана 2024-03-24 в 00 21 44](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f1b4015c-7aac-4de9-89aa-ae5a7e60be9a/23d0a3e0-8cda-4bac-bd51-461131c9f24d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMWI0MDE1Yy03YWFjLTRkZTktODlhYS1hZTVhN2U2MGJlOWEvMjNkMGEzZTAtOGNkYS00YmFjLWJkNTEtNDYxMTMxYzlmMjRkIiwiaWF0IjoxNzExMzA5MzUxLCJleHAiOjMzMjgxODY5MzUxfQ.zhOwxWVTIb6Wbn-5OaTyEtYxcX0XxHCLUAOE5OjIi-U "=1710x")

Indeed, I had practically no strength left, I checked the connections and the name - no errors were found / the code does not compile/ I tried to assemble other widgets, but in the end even the simplest ones produced this exact error. I'm at a dead end

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

### Context

I expected the code to compile after fixing all the errors

### Visual documentation

I want my custom widget to work

### Additional Info

*No response*

### Environment

```markdown
FlutterFlow v4.1 released March 21, 2024
Flutter version is 3.19.1
MacOSSonoma Версия 14.3.1
Safari Версия 17.3.1 (19617.2.4.11.12)
Progect - autonica-wjuwiq
```

**Comment by hariprasadms** [comment]
Hey @Steelynss - Thank you for submitting the issue. Upon reviewing your custom code template, it appears that the template is incorrect and does not adhere to the custom widget template. The main function is called inside the custom widget code. Please refer to the FlutterFlow custom widget documentation and rectify the issue accordingly. I hope this resolves the problem. Thank you.
