### ISSUE TITLE
Empty url error when url is not empty

### ISSUE THREAD

**Issue by withinboredom** [FlutterFlow/flutterflow-issues#2591]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For doing CRUD operations, it appears that creating an API group and simply setting the API Endpoint to `/` will be quite useful:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/71565c41-b227-4164-9e2f-32e30420ffb0/d59a9dfa-660b-4972-b93d-ba0a6797fcf3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MTU2NWM0MS1iMjI3LTQxNjQtOWUyZi0zMmUzMDQyMGZmYjAvZDU5YTlkZmEtNjYwYi00OTcyLWI5M2QtYmEwYTY3OTdmY2YzIiwiaWF0IjoxNzExMzA5MzUxLCJleHAiOjMzMjgxODY5MzUxfQ.-HM4sgavMJSURQ5AU495E70qgKg3zZcmPleBMSscRkg)

i.e., `GET /query` to get the query, `POST /query` to update the query, etc.

However, flutter flow considers the URL to be empty when trying to save it, even though there is a `/`:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3b9a359d-1e71-46df-a197-1f84ae3b72aa/f777645d-9985-4d54-bf0e-a0fa1a692bff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYjlhMzU5ZC0xZTcxLTQ2ZGYtYTE5Ny0xZjg0YWUzYjcyYWEvZjc3NzY0NWQtOTk4NS00ZDU0LWJmMGUtYTBmYTFhNjkyYmZmIiwiaWF0IjoxNzExMzA5MzUxLCJleHAiOjMzMjgxODY5MzUxfQ.nB9W2tVjdBlDW1EGH7rPOm2LV72o1t0id9-0KkH10Ls)

### Expected Behavior

To be able to use API groups in CRUD operations in a useful manner.

### Steps to Reproduce

1. Create an api group.
2. Create an api call in that group
3. leave the `/` for the URL
4. Save the API call.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

Call GraphQL endpoints and perform CRUD operations.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/44f900e0-6b44-4ea6-8204-15147a8f65e0/49788ea4-6933-4eff-879e-0ecff222dda6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NGY5MDBlMC02YjQ0LTRlYTYtODIwNC0xNTE0N2E4ZjY1ZTAvNDk3ODhlYTQtNjkzMy00ZWZmLTg3OWUtMGVjZmYyMjJkZGE2IiwiaWF0IjoxNzExMzA5MzUxLCJleHAiOjMzMjgxODY5MzUxfQ.ZGmYlXhnKjXC4PA7UJKItzqhsX_i8-zC15GlBHWwVcc)

### Additional Info

N/A

### Environment

```markdown
- FlutterFlow version: v4.1.33+
- Platform: Windows
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

**Comment by withinboredom** [comment]
Hi @hariprasadms, it isn't empty, it has `/` in it.

**Comment by hariprasadms** [comment]
Hi @withinboredom - As per standard practice, API endpoints typically use resource endpoints for access. This is the practice we have followed. If your endpoints' results are accessed at the base domain level, this could be considered a feature request. However, it's unclear if we can prioritize this. I have escalated this for technical triage; they can decide on its status. Thank you.

**Comment by takashiff** [comment]
Hi @withinboredom, as @hariprasadms has stated earlier, we encourage users to follow standard practice, and as such, accessing endpoint results at the base domain level (within an API group) is restricted. As a workaround, you can create a singular API call at the domain level, and have your other endpoints exist within the group. Hope this helps, thanks.

**Comment by withinboredom** [comment]
> Hi @withinboredom, as @hariprasadms has stated earlier, we encourage users to follow standard practice, and as such, accessing endpoint results at the base domain level (within an API group) is restricted. As a workaround, you can create a singular API call at the domain level, and have your other endpoints exist within the group. Hope this helps, thanks.

Hi @takashiff, I agree with you, however, it is also a pretty standard practice in CRUD to have a single API endpoint where only the payload and verb is different, i.e.:

- `GET /users/[id]`
- `POST /users/[id]`

It would be helpful to simply create an API group for `/users/[id]` where we need to only configure the verb and payload, vs. having a group for `/users` and then configuring multiple calls with just `/[id]`.
