### ISSUE TITLE
Custom Domain Insufficient

### ISSUE THREAD

**Issue by DevKursat** [FlutterFlow/flutterflow-issues#2592]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a domain containing Turkish characters, but I cannot upload my Flutterflow application to this domain.

### Expected Behavior

Regardless of whether there are Turkish characters in my domain name, I should be able to upload successfully if the server information is correct.

### Steps to Reproduce

Try adding the domain name "kürşat.app" as a custom domain

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeyfLl05NPn7xJ16X1LccwmQMwGkQ5a7sviu5+FBQaI+P1BIkUe8zRYRJDWOqHS29AH1mbnmEz//CNhYbPJvFcNS6Vf65JzahhUxDhf3y5SqbQDJboe0Z9EcJYCWac5rSrkCNBKsdYdX9m3F6Le9iuY3qCf9qOYwx5e6fDbOY=

### Context

I couldn't publish the web version of my app

### Visual documentation

![Ekran görüntüsü 2024-03-25 091619](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2857b997-76a3-4ae6-9ce0-3c50d9b71fb4/affc4707-3ed6-4872-b1ac-a402ff78872e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yODU3Yjk5Ny03NmEzLTRhZTYtOWNlMC0zYzUwZDliNzFmYjQvYWZmYzQ3MDctM2VkNi00ODcyLWIxYWMtYTQwMmZmNzg4NzJlIiwiaWF0IjoxNzExMzg0ODU0LCJleHAiOjMzMjgxOTQ0ODU0fQ.OibigsBfxKfzsy5cqdqovyzbqrIdpkVALpCN9jjG9zo)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow App ID: zafer-rqs8we
```

**Comment by ignalauret** [comment]
Hey @DevKursat thanks for your report. I was able to confirm that you can't use that custom domain right now on our platform. The technical team is going to check if this could be done, they will keep you updated on this thread. 
Have a great day.

**Comment by ignalauret** [comment]
Hey @DevKursat the technical team has checked and only ASCII characters can be used on a url, as you can read on the documentation: [https://www.rfc-editor.org/rfc/rfc3986#section-2](https://www.rfc-editor.org/rfc/rfc3986#section-2)
So please provide a valid domain to be able to deploy. Closing this issue, have a great day!
