### ISSUE TITLE
support for international seems to be out of date

### ISSUE THREAD

**Issue by riseaboveit** [FlutterFlow/flutterflow-issues#2593]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

uses 0.18.1 which has issues, should be on 0.19.0

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/127778286/c3f7ed9b-7e3f-4175-95f8-96b77b03c294)

### Expected Behavior

to be on version without issues.

### Steps to Reproduce

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/127778286/8b1e09f8-bc5d-4f5a-85dc-a99c9d951979)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/127778286/33a762cc-7745-4300-bdfb-8aa589f11d70)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/127778286/5351ba85-bced-4c1b-97e0-70d403579b1d)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @riseaboveit - Thank you for bringing up the issue. Could you please specify the exact error or behavior you are encountering in the project or app? Kindly provide these details for better understanding.

Additionally, to clarify, the current version of this package is compatible with existing other packages, hence you are observing this particular version. To incorporate the latest versions, it's essential to test their compatibility with other packages, which we typically do in a planned manner.

If you're not experiencing any issues with the project and the functionality of its features, it indicates that no version change is necessary and there are no bugs. I hope this clarification helps you. Thank you.

**Comment by riseaboveit** [comment]
Cannot import widgets, as they depend on the latest version of intl:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/127778286/2d408741-7e27-4210-b0c0-ed311ad27bde)

**Comment by bozzoleandro** [comment]
Hi @riseaboveit, we're assigning this issue to the corresponding team for further review. Thanks!

**Comment by takashiff** [comment]
Hi @bozzoleandro, you can overwrite the version of `intl` specified in FF by adding it as a pubspec dependency with the specified version you'd like to use. Let me know if this helps, thanks.
