### ISSUE TITLE
Bug Parallel Mac Desktop.  Can't Open Action Flow Editor on Mac Desktop

### ISSUE THREAD

**Issue by rcunhadf** [FlutterFlow/flutterflow-issues#2595]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't open the Action Flow Editor on a button that contains 9 actions after I created Parallels and went to add the 3rd Parallel.

### Expected Behavior

That it worked normally.

### Steps to Reproduce

1. Open the FLow Action Editor

2. Adds more than 4 Parallels.

3. You will see it in the Panel on the right, but it does not appear in the visual graph

4. I close the Editor that shows no errors

5. Try to open the Editor and nothing will happen.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

dont have

### Context

I can't modify my actions

### Visual documentation

[Gravação de Tela 2024-03-26 às 09.22.58.mov.zip](https://github.com/FlutterFlow/flutterflow-issues/files/14758301/Gravacao.de.Tela.2024-03-26.as.09.22.58.mov.zip)

### Additional Info

no extra

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: MAC Desktop
- Browser name and version: Desktop
- Operating system and version affected: Apple M2 Sonoma 14.2.1
```

**Comment by ignalauret** [comment]
Hi @rcunhadf thanks for submitting the issue. I can confirm that I can reproduce the bug following your steps on MacOs App. If you are blocked by this issue, you can use the Web app as a workaround until our team is able to fix it.

**Comment by rcunhadf** [comment]
Ok thanks. How I’ll be notified about MacOS App new version?

Rodolpho Cunha
+55 61 99686-6333


Em ter., 26 de mar. de 2024 às 10:39, Ignacio Lauret <
***@***.***> escreveu:
