### ISSUE TITLE
Edit walkthrough cause focus lost in editor

### ISSUE THREAD

**Issue by davood-flutterflow** [FlutterFlow/flutterflow-issues#2597]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After you edit the walkthrough and save it, when you come back to the editor and select a widget, the moment you click in the properties panel, it will unfocus from that widget and the root widget will be focused - Video included

Reproduced in this sample project: https://app.flutterflow.io/project/testfor-kri-no-k9q6rg?tab=widgetTree&page=HomePage

### Expected Behavior

-

### Steps to Reproduce

-

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx892m7RJ+KrMYMJR/SUXCDs9Ro040OxEQis9f5ToPJYQe8/6PxdCZ/2oTGxYMVmcp14G0/TtivGWOPADHEiCfIBMyc9QVRXKRnuRaamTF7jtfXJ6HZlQN3LC0rSNsBYkNuh1WCVi7WCuJemXbADtGJDbPFQ4Sq/LZO4=

### Context

Replicated/Reproduced in support

### Visual documentation

Video: https://drive.google.com/file/d/13S0Y6SyQZONpUsRGtymZ5gQ6wVFGOOzW/view

### Environment

```markdown
FlutterFlow v4.1 released March 21, 2024
Flutter version is 3.19.1
```

**Comment by bozzoleandro** [comment]
Hi @davidflutterflow, Thanks for your report, I could not reproduce it, Are you still experiencing the same issue?

**Comment by leighajarett** [comment]
Since we haven't heard back, we're closing out this issue

**Comment by cragroc** [comment]
I reported this to support as well, showed them my repro. It's very easy to repro and happens all the time even in a new project. I see it was just closed, can you take another look, it makes it really hard to work on walkthroughs.

**Comment by cragroc** [comment]
Simplest repro steps I have are these and I tested in 3 different projects.
* In a text widget, click the text theme style to change it, like from Headline Small to Headline Medium to verify it works like it should.
* Go to Settings, Walkthroughs. (You don't even need to have one or edit anything.)
* Go back to the text widget and try to click the theme style again. Now it won't let you and the UI jumps to a different spot in the widget tree.

**Comment by leighajarett** [comment]
Thanks, we'll try to reproduce again!

**Comment by rzambroni** [comment]
Hey @cragroc, thanks for sending the steps to reproduce. I was able to confirm the issue and will send it to the team so they can take a look.  It's a rare one for sure!

Once it is fixed we will update the status here and let you know.

**Comment by damianfraire** [comment]
Facing the same issue.

**Comment by sbis04** [comment]
Should be fixed in the next update!
