### ISSUE TITLE
workthrough not focusing for the first step

### ISSUE THREAD

**Issue by cmwang92** [FlutterFlow/flutterflow-issues#2599]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It seems like for every "first" step of the walkthrough , will not able to focus well on the widget. It seems working fine on rest of the steps.

### Expected Behavior

Take below image as example, expect it focuses on the entire choicechips , instead of random square 
### Steps to Reproduce

1. create a new walkthrough
2. add steps 
3. run the app 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz/Hqx89gruVH7aX6dcBr/CgQNnp6U4Iesclsbxcbfbb0BIsIYMzORFhUOPGlTHxiPWC0hj0X/MrQuOGWEvEBEAWZRb5O1c5IVzqVLUmiWrHXDb63b397BfpYIGqy3KW3rgknCPtsWVY83U2QO/PIYAPUCYTGNldNReaoXdeK2SrDX1iXc2URm05KZDPz

### Context

i want to add walkthrough to my app 

### Visual documentation

![Screenshot 2024-03-26 at 22 53 52](https://github.com/FlutterFlow/flutterflow-issues/assets/139349033/2c416dda-61d7-4cb9-bb6b-d9b6f56791ad)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by cmwang92** [comment]
solved by adding wait time

**Comment by karabil** [comment]
Is it really solved? 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/48866801/ef34b21f-3ba2-434b-b23d-ba4666b73c55)
