### ISSUE TITLE
Updating body within "My Team API" does not alway refresh the API body in my app

### ISSUE THREAD

**Issue by graybright** [FlutterFlow/flutterflow-issues#260]
## Expected behavior (required)
When modifying text within the body of a "My Team API" it is expected that it will immediately update within the app, however it seems like it is caching somewhere and when you run (or instant reload) the app, the old body text is still used in the API call.

## Current behavior (required)
When modifying the text of a body within a "My Team API" I am noticing that it does not alway refresh when I run my app. I have observed that I have to 'force a reset' of the API by going into the 'Backend Call - Action' section within my app and re inputting the details of the app (basically delete the reference to the API in my app linked to a button, and then set the API on the button again).

## To Reproduce (required)
1. Update body within a "My Team API"
2. Run the app
3. Sometimes when I activate the API, it uses the OLD body which I have updated
4. To make sure it uses the new text, I go to the button, remove the API Call from the action, and then reimplement the API call onto the button (like a force delete and reset of the API linked to the button which makes me think it's a caching issue somewhere)

### Bug Report Code
No report code displayed

## Context (required)
When trying to debug a API call, this makes it very hard because sometimes when you update your API code and re-run the app, it's still using the old code!

## Screenshots / recordings
N/A

## Your environment

V3.0 12/21 Flutter 3.3.4
Macbook
Chrome

**Comment by organicnz** [comment]
Hi @graybright. Thank you for adding this issue 🙂
Have you tried reproducing this issue with another, possibly free, API provider? :)

**Comment by aemelyanovff** [comment]
@graybright Thanks for reporting the issue. Unfortunately, we can't change this behavior at the moment. I can only suggest a couple of workarounds:
1. Update the team project and the "child" project in the same browser tab.
2. Refresh the browser tab with the "child" project after updating the team project.
