### ISSUE TITLE
Unable to save project / Network disconnected error

### ISSUE THREAD

**Issue by cheungysophie** [FlutterFlow/flutterflow-issues#2602]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I keep getting the error that Flutterflow is experiencing error saving my project and that there's network connection issues. Whenever I run test mode, it won't show me my most updated version, and only shows me the version from 16 hours ago (when I started experiencing the error). I've been stuck for a few hours and it's very frustrating, please let me know how to proceed. 
Publishing to web does work.
I have tried different browsers (brave, arc, safari), logging out, logging in, clearing cache, turning computer on/off, Flutterflow desktop version, none of the solutions worked. 

I have deadlines and this has cost me an entire day of not making ANY progress on the project. Would really appreciate help ASAP

### Expected Behavior

The project should save automatically, or my manual saves should be reflected. Test mode should also reflect my most recent changes. 

### Steps to Reproduce

unable to save

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelsmAsI1Pj71K1qnydvlsrwMwJ0QlUIInj+0bWRMhfY+sE+wiOs7sRFZLYtTheVBAH1KkpGID/6nSvvOSCPU6ZAubRthz+JRXQQn/fHmQbrXQCLWVPWt7N/1mCmK0yqSRryNSKfVYW3w81GGEN/CrG3qCf9qOYwx5e6fDbOY=

### Context

I am unable to make any changes, unable to run Test Mode with any of my new changes. Manual saving works but is not reflected in Test Mode. Projects screen shows last saved 16 hours ago even though I've been trying to manual save it. 

### Visual documentation

<img width="562" alt="Screenshot 2024-03-26 at 10 49 22 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/80649756/b015d6bf-11bd-4526-af96-0d8f66fcf5a9">
<img width="1357" alt="Screenshot 2024-03-26 at 10 59 00 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/80649756/70ecb66f-1895-49a4-8cdb-552967a2b2fd">
<img width="1133" alt="Screenshot 2024-03-26 at 10 59 14 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/80649756/9386a1a9-718a-4bc9-9c0f-6a236b122595">

### Environment

```markdown
- FlutterFlow version: 
v4.1
- Platform:
- Browser name and version: 
Brave (though I've tried Safari, Arc as well and they all have the same issue)
- Operating system and version affected: 
Mac
```

**Comment by cheungysophie** [comment]
Hi, when can I expect to receive help? I have a deadline for Thursday and would really appreciate help asap, I've lost the entire day due to this issue. Thank you very much

**Comment by bozzoleandro** [comment]
Hi @cheungysophie, thanks for your report, are you still experiencing the issue?

**Comment by leighajarett** [comment]
Closing this issue since we haven't heard back from you
