### ISSUE TITLE
Test groups throw errors

### ISSUE THREAD

**Issue by JulianMarc1** [FlutterFlow/flutterflow-issues#2603]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, when executing locally tests inside test groups, an error ocurss, stating: "Groups may not be async". Even if the group is empty, the error occurs.

### Expected Behavior

Tests inside groups execute well.

### Steps to Reproduce

1. Create a new test group.
2. Export locally using flutterflow's cli.
3. Run flutter test integration_test/test.dart from the root folder of the project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IDontHaveAReportCode

### Context

I am trying to use groups to run tests, at first locally, and then with device farm.

### Visual documentation

This is a test run with an empty group. Same behaviour occurs on a group with tests.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/152976641/7d0cac86-4289-4518-bb10-764eba4c4d24)

Also, removing the async fixes the issue, and all tests inside the group execute properly

### Environment

```markdown
- FlutterFlow version: 3.1.19
- Platform: Android or chrome with chromedriver
- Browser name and version: ChromeDriver 123.0.6312.58
- Operating system and version affected: sdk_gphone64_x86_64 Android 14
```

**Comment by ignalauret** [comment]
Hey @JulianMarc1 thanks for your report. I've been able to reproduce your bug with the Test Groups, and as you said it has an async that shouldn't be there. I have elevated a ticket for the engineering team to fix it, they will keep you updated on this thread. 
Have a great day.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. We have a fix, it'll be released most likely by the end of the next week.
