### ISSUE TITLE
Testing is blocked by the error image issue

### ISSUE THREAD

**Issue by supertatsis** [FlutterFlow/flutterflow-issues#2604]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I got an error message
"Missing settings asset: "error_image.png" Please re-upload or select a different asset, or run the project again to check if the issue persists."

Reuploading and rerunning the project doesn't help,

### Expected Behavior

I expect not having this error, I didn't have it a few hours ago.

### Steps to Reproduce

Link to my project: [https://app.flutterflow.io/project/mvp-1-kidnzm?tab=appSettings&appSettingsTab=appAssets](https://app.flutterflow.io/project/mvp-1-kidnzm?tab=appSettings&appSettingsTab=appAssets)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Padding( padding: EdgeInsets.all(6.0), child: FlutterFlowIconButton( borderColor: Colors.transparent, borderRadius: 20.0, borderWidth: 1.0, buttonSize: 60.0, fillColor: Colors.transparent, icon: Icon( Icons.arrow_back_rounded, color: FlutterFlowTheme.of(context).primaryBackground, size: 24.0, ), onPressed: () async { logFirebaseEvent('CREATE_ACCOUNT_arrow_back_rounded_ICN_ON'); logFirebaseEvent('IconButton_navigate_to'); context.goNamed('GetStarted'); }, ), )

### Context

It just appeared in the errors, I haven't had the assets uploaded and decided this was made a requirement. I went ahead and uploaded all assets but the error stayed in place. I thought I was blocked from loading the test mode, but not, I was able to test.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fb924be1-9272-49b1-8295-2b7b061a0190/1d555a8d-8ed3-495d-9800-defc25d05b19?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYjkyNGJlMS05MjcyLTQ5YjEtODI5NS0yYjdiMDYxYTAxOTAvMWQ1NTVhOGQtOGVkMy00OTVkLTk4MDAtZGVmYzI1ZDA1YjE5IiwiaWF0IjoxNzExNDc5OTc2LCJleHAiOjMzMjgyMDM5OTc2fQ.L1VhhDUmhp2h-STnVNMP1FY6Ixehheqm19TjEfpHqpE "=1429x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.34
- Platform: Mac
- Browser name and version: desktop app
- Operating system and version affected: macOS Monterey 12.7.4
```

**Comment by ignalauret** [comment]
Hey @supertatsis thanks for your report. I just checked your project and I can see you were able to upload correctly the error image and you have no errors, great job!
I'm closing this issue, feel free to open a new one if you run into another problem. Good luck!

**Comment by stephenaimona** [comment]
hi @supertatsis can you tell me how do you fix the problem ? as i have the same problem.....tks
![image](https://github.com/user-attachments/assets/e93d5729-a4b1-4df4-b34e-f2b20be8bbe1)
![螢幕擷取畫面 2024-12-23 134237](https://github.com/user-attachments/assets/c67df1a7-9b32-474b-9bca-4efb9fe2415b)

**Comment by Iam-ozzy** [comment]
> ### Has your issue been reported?
> 
> * [x]  I have searched the existing issues and confirm it has not been reported.[x]  I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.
> 
> ### Current Behavior
> 
> I got an error message "Missing settings asset: "error_image.png" Please re-upload or select a different asset, or run the project again to check if the issue persists."
> 
> Reuploading and rerunning the project doesn't help,
> 
> ### Expected Behavior
> 
> I expect not having this error, I didn't have it a few hours ago.
> 
> ### Steps to Reproduce
> 
> Link to my project: https://app.flutterflow.io/project/mvp-1-kidnzm?tab=appSettings&appSettingsTab=appAssets
> 
> ### Reproducible from Blank
> 
> * [x]  The steps to reproduce above start from a blank project.
> 
> ### Bug Report Code (Required)
> 
> Padding( padding: EdgeInsets.all(6.0), child: FlutterFlowIconButton( borderColor: Colors.transparent, borderRadius: 20.0, borderWidth: 1.0, buttonSize: 60.0, fillColor: Colors.transparent, icon: Icon( Icons.arrow_back_rounded, color: FlutterFlowTheme.of(context).primaryBackground, size: 24.0, ), onPressed: () async { logFirebaseEvent('CREATE_ACCOUNT_arrow_back_rounded_ICN_ON'); logFirebaseEvent('IconButton_navigate_to'); context.goNamed('GetStarted'); }, ), )
> 
> ### Context
> 
> It just appeared in the errors, I haven't had the assets uploaded and decided this was made a requirement. I went ahead and uploaded all assets but the error stayed in place. I thought I was blocked from loading the test mode, but not, I was able to test.
> 
> ### Visual documentation
> 
> ![image](https://camo.githubusercontent.com/ecbbe5e7c4ee2f01e8ee62288b52053cad346ebed5789dd21ac5f035a9db7f34/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f66623932346265312d393237322d343962312d383239352d3262376230363161303139302f31643535356138642d386564332d343935642d393830302d6465666332356430356231393f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a53396d596a6b794e474a6c4d5330354d6a63794c545135596a45744f4449354e533079596a64694d445978595441784f5441764d5751314e5456684f4751744f47566b4d7930304f54566b4c546b344d4441745a47566d597a49315a444131596a45354969776961574630496a6f784e7a45784e4463354f5463324c434a6c654841694f6a4d7a4d6a67794d444d354f54633266512e4c3156686844556d687032682d53546e564e4d5031465936497865686865716d3139546a45667048717045)
> 
> ### Additional Info
> 
> _No response_
> 
> ### Environment
> 
> - FlutterFlow version: v4.1.34
> - Platform: Mac
> - Browser name and version: desktop app
> - Operating system and version affected: macOS Monterey 12.7.4

Hi, 
I am experiencing a similar issue, can anyone direct me to the fix please?

**Comment by Iam-ozzy** [comment]
@supertatsis how were you able to solve?
