### ISSUE TITLE
Locked out of project for whole team  because  of merge bug - CRITICAL FAILURE

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#2605]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As said, we are all locked out of the project. A merge was initiated in Flutterflow for Windows and it behaved strangley, the merge button clicked but did not do anything. Closed the app and started it again and eteral loading spinning wheel. All other team members locked out for HOURS becuase is says merge in progress

### Expected Behavior

Do the merge and move on. 

### Steps to Reproduce

Go to the project and see for yourself. 

https://app.flutterflow.io/project/2YAvBPwkvTGe9XANKiw1?tab=uiBuilder&page=homePage

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

unavailabe locked out

### Context

Crticial and VERY UPSET. Whole day of teamwork lost. NO tech support ALL DAY. 

### Visual documentation

None

### Additional Info

None

### Environment

```markdown
- FlutterFlow version: Latest
- Platform:All but starting with Windows
- Browser name and version: Flutterflow Desktop
- Operating system and version affected: ALL
```

**Comment by leighajarett** [comment]
@charliefabley oh no! That's not good. So sorry this is happening! We're taking a look now. Will reach out with more updates / questions ASAP

**Comment by victoriahuang1** [comment]
@charliefabley you should be able to open the project now. I have a fix that should prevent this from going forward, once it is merged in and deployed

**Comment by zeymermontes** [comment]
@victoriahuang1 @leighajarett   I have the same issue on 2 projects any help please:
project ids:
packsify-cehw5i
drag-and-drop-o09bva

**Comment by zeymermontes** [comment]
@victoriahuang1 thanks, should we stop merging any project until this is fixed?

**Comment by davidflutterflow** [comment]
@victoriahuang1 I have 2 similar reports related to the same issue.

**Comment by mrocchini22** [comment]
@victoriahuang1, I have the same problem, I don't know if I should report it in another bug or I can give you the project ID.
The project ID is beeto-d-e-v-sbpjgc. It's still working for 3 hours but I read in this post https://community.flutterflow.io/ask-the-community/post/project-unreachable-after-merge-attempt-JomPI62ruosAQqD that someone is still waiting for more than 4 days.
If you can stop this I would be very grateful

**Comment by victoriahuang1** [comment]
@zeymermontes you can try again. It seems like there was some issue on the firebase side. I have not been able to reproduce this in any of my projects, so I think firebase has resolved whatever issue they had. If you still experience this, please let me know, and I can look into it further.
