### ISSUE TITLE
Flutterflow API grey screen instead of showing results

### ISSUE THREAD

**Issue by terracomsa** [FlutterFlow/flutterflow-issues#2608]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, when I download my project to my Android phone, I sometimes see a grey page instead of the results on a listview that is populated through an API call. This happens sometimes, even though the API call is successful on the Flutterflow app.

### Expected Behavior

See the results properly instead of the grey screen

### Steps to Reproduce

Download the APK from my project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OzMmBw412odtF+KryKMJVtDsWQ2I/apZMiu1DdwIcG4PNG4s+f86lVHVtXdPhdglfeWaKrzky06COm9z1KMIrNReCG5hJzpBhWzzheF6WM7qNCJGZPUZuGshhfmai552NhiZCXdJhLVIg72aLeui8dDfdQpzbDkczRvmlDNrXmAfuQ0SLb3kNh1JWeC/v

### Context

I am trying to see the API results on a page, but I see a grey page instead

### Visual documentation

![Screenshot_20240327_100249](https://github.com/FlutterFlow/flutterflow-issues/assets/39090100/620067b3-4ee1-460d-b9af-ff18deaf69ff)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Windows
- Browser name and version: Chrome 
- Operating system and version affected: Android Samsung phone
```

**Comment by cheungysophie** [comment]
I have the same issue too

**Comment by leighajarett** [comment]
I believe this is is a duplicate so closing this one

Please use: [https://github.com/FlutterFlow/flutterflow-issues/issues/2609](https://github.com/FlutterFlow/flutterflow-issues/issues/2609)
