### ISSUE TITLE
Flutterflow grey screen instead of showing API results in a listview

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#2609]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, when I download the APK on my Android phone, I sometimes see a grey page instead of the results in the listview.

### Expected Behavior

Seeing the results properly in the page.

### Steps to Reproduce

Download the APK from my project

From a blank project:
1) Create a new page with an API call
2) Download APK on Android phone
3) See that you sometimes get grey screen instead of seeing the results

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OzMmBw412odtF+KryKMJVtDsWQ2I/apZMiu1DdwIcG4PNG4s+f86lVHVtXdPhdglfe2D9iXIz3M6Km9z2UfkCPRaZRZw7zrhQSRXjVl+mVJiwDJOJdn9+Gshhfmai552NhiZCXdJhLVIg72aLeui8dDfdQpzbDkczRvmlDNrXmAfuQ0SLb3kNh1JWeC/v

### Context

I am trying to see the API results on a page

### Visual documentation

![Screenshot_20240327_100249](https://github.com/FlutterFlow/flutterflow-issues/assets/11061846/943696a9-baba-476d-a556-106090a76e2f)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected: Windows on my PC, Android on my Samsung phone
```

**Comment by bozzoleandro** [comment]
Hi @adrfinance, thanks for your report, Can you please verify if the AndroidManifest.xml (inside the android folder in your project)  file has the following permission <uses-permission android:name=“android.permission.INTERNET” /> (under the manifest tag)?

**Comment by leighajarett** [comment]
Closing this issue since we haven't heard back from you
