### ISSUE TITLE
Codemagic deploy error: curl: (28) Operation timed out

### ISSUE THREAD

**Issue by Gintasz** [FlutterFlow/flutterflow-issues#2612]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Click to deploy app to iOS app store, get error:
Failed Step:

== Use Flutter version 3.19.1 ==
> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.1-stable.zip --connect-timeout 10.00 --max-time 120.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.1-stable.zip
curl: (28) Operation timed out after 120011 milliseconds with 525151681 out of 1167172797 bytes received

Downloading Flutter release timed out

Build failed :|
Downloading Flutter release timed out

### Expected Behavior

not get error

### Steps to Reproduce

Click to deploy app to app store. Have not tried from blank account

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESi87lw5NgosdY+arUYflQhQAkQzM8bYJMl9cbd0gdGOquBLMMd+r+VGpVX9OHY29iJmD+oH8C7trHhtryUfkrB0mteINozqpUWwnNRluVVq6mPpGKfUZRGcFYC3KEy8HYpxBBKfVeS1Utw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

deploy to app store

### Visual documentation

<img width="676" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6189625/8310e4d3-28ff-4a17-8818-3c80a18260be">

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: n/a
- Browser name and version: arc browser/chrome
- Operating system and version affected: n/a
```

**Comment by Gintasz** [comment]
Also, my google play deployment submission is status queued for 3-4h now.

**Comment by apsdsk** [comment]
same here

**Comment by leighajarett** [comment]
Closing since we haven't heard from you
