### ISSUE TITLE
Toggle and Checkbox conditional false value action ignored

### ISSUE THREAD

**Issue by skiunke** [FlutterFlow/flutterflow-issues#2613]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The conditional state change of a checkbox and toggle button does not trigger the FALSE condition. The action following the FALSE condition is ignored and not executed.

### Expected Behavior

The action following the FALSE condition is executed.

### Steps to Reproduce

1. Create a new project
2. Create a toggle or checkbox item
3. Create a conditional action based on the toggle or checkbox item
4. Create a TRUE and False Action. that open an Informational Dialogue
5. Toggle the Checkbox
 -----------
7. On TRUE the Dialogue opens
8. ON FALSE nothing happens.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9WpCQUKW44bYc0sN4bSRQgfa73PO0uaeDsXxZDXe2+Y2xDKEWKkl8B+NnIj+LyUcACNQWcRZx6yKh+YDriXkm/aoSvDs/hWkFtL/xYfxzF3JmFkwp/Nu1qSk4m1Dile/OvXgTYGb37Zwh9f6PHaOI=

### Context

Trying to update the supabase databaset boolean value based on the checkbox or toggle

### Visual documentation

<img width="1900" alt="Screenshot 2024-03-27 191124" src="https://github.com/FlutterFlow/flutterflow-issues/assets/44609405/287b412d-f908-450e-bf68-21a7b63cac4a">
<img width="726" alt="Screenshot 2024-03-27 191110" src="https://github.com/FlutterFlow/flutterflow-issues/assets/44609405/f1ec894f-cf11-4601-9ed3-e5c373deac1f">
<img width="1918" alt="Screenshot 2024-03-27 191134" src="https://github.com/FlutterFlow/flutterflow-issues/assets/44609405/1209a34e-c856-44d1-88d4-3982f99d7bf6">

### Environment

```markdown
- FlutterFlow version: v,1,33+ with Flutter 3.19.1
- Platform: Web
- Browser name and version: Chrome 123.0.6312.87, Edge 122.0.2365.92
- Operating system and version affected: Windows 11
- Affects both local testing and cloud testing
```

**Comment by ignalauret** [comment]
Hey @skiunke thanks for your report. Keep in mind that for the CheckBoxes you have to setup actions for "On Toggled On" and "On Toggled Off". Check out in the Actions editing panel you have a switch at the top to set which state you are configuring.
Good luck!
