### ISSUE TITLE
Windows Flutterflow hot restart. Restart App and hot reload seem to be the same. Does not break out of a crash.

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#2614]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If the app hangs, in VSCode a hot restart app would reset the app, but in Flutterflow WIndows it does not. In fact it seems both buttons do the same thing which is a hot reload and not a hot app start.

### Expected Behavior

App restarts

### Steps to Reproduce

Stop and then restart app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

123456789

### Context

Need to stop the app and run the test again. Waste of time.

### Visual documentation

xxx

### Additional Info

xxx

### Environment

```markdown
- FlutterFlow version: lastest
- Platform: Windows Flutterflow
- Browser name and version: NA
- Operating system and version affected: Windows 11
```

**Comment by rzambroni** [comment]
Hi @charliefabley, unfortunately, I'm not being able to replicate this issue and seems to be working as expected on our end. Are you still experiencing it? if so, would you mind adding more evidence to help us troubleshoot? a video from a blank project would be great. Thanks!
