### ISSUE TITLE
FLUTTER SDK

### ISSUE THREAD

**Issue by drazevedo123** [FlutterFlow/flutterflow-issues#2615]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![ERRO FLUTTER](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/30922a27-ea9f-4024-aa63-ac0a29ed79a8/7bd23108-e6ad-4ea3-8d91-c8aceadd3664?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMDkyMmEyNy1lYTlmLTQwMjQtYWE2My1hYzBhMjllZDc5YTgvN2JkMjMxMDgtZTZhZC00ZWEzLThkOTEtYzhhY2VhZGQzNjY0IiwiaWF0IjoxNzExNjQ2OTc0LCJleHAiOjMzMjgyMjA2OTc0fQ.1cLjv7vj8SulqyH8o29av1grR9G-VOxfYIqF4LFB7bk)

Error when starting run mode

### Expected Behavior

INSTALLING FLUTTERFLOW RUN MODE.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Context

INSTALLING FLUTTERFLOW RUN MODE.

### Visual documentation

INSTALAÇÃO DO FLUTTERFLOW MODO RUN.

### Additional Info

Looking in the flutterflow files, I found the shared_preference file the same "flutter.flutterBinPath":"C:\\Users\\Danilo Azevedo\\AppData\\Roaming\\com.example\\flutterflow/flutter/bin" has this file , I believe the correct way it should be would be "flutter.flutterBinPath":"C:\\Users\\Danilo Azevedo\\AppData\\Roaming\\com.example\\flutterflow\\flutter\\bin"

### Environment

```markdown
- FlutterFlow version: v4.1.33
- Platform: windows
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: w10
```

**Comment by AnonZ7** [comment]
Having the same problem, I tried to clean install it and modified the Flutter folder path in shared_preferences, but I'm still experiencing the same issue!

**Comment by Abadar169** [comment]
Same issue persists after the latest version.

**Comment by Vize2024** [comment]
i have the same issue, managed to solve?

**Comment by Habari1447** [comment]
Same issue there

**Comment by gunnarjessee** [comment]
I had fixed this issue by:

- Uninstalling the FlutterFlow program in Windows
- Removing all FlutterFlow files in %appdata%/Roaming/FlutterFlow

Hope this helps someone in here.

**Comment by azharbinanwar** [comment]
I'm facing the same problem but I'm not sure @sbis04 how this is marked as closed/completed.

Would you like to share your thoughts on how I can solve this or which version contains this fix??

I really appreciate any help you can provide.

**Comment by WelcomeMaks** [comment]
@gunnarjessee helped:D
