### ISSUE TITLE
Adding 3rd parallel action breaks the action system

### ISSUE THREAD

**Issue by ebrammer** [FlutterFlow/flutterflow-issues#2616]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you click on + parallel action to add a third or more actions:
1. The additional parallel action flow doesn't show up - it continues to show just the first 2
2. If you exit the action dialog and then click "open" to reopen it - it won't. 

You're able to navigate to other action editors and open and close them, but the original is now no longer open-able

https://github.com/FlutterFlow/flutterflow-issues/assets/5923757/826458b0-08d6-4d83-882d-2a575567f6bd

### Expected Behavior

1. Should have added a third parallel action flow
2. Should be able to enter/exit the action flow editor after

### Steps to Reproduce

1. Open the action flow editor.
2. Add a parallel action.
3. Add a third action.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Chc/135d2sddY187pbcBKhjgQJlw2RY0nlutteEkcHZPMC+wIZ/f7XFRuTde0S2NcMWGZoz81+tXemvLmVu46aCmsfL5n+Jd+cQz/fH+QM7qUPJG/PW5/DdpQJkym4cC33RVAGLZvLFYu61yhf+itUT7vH7W3OGwvQv+JMZOK2SrDX1iXc2URm05KZDPz

### Context

Trying to run more than 2 parallel actions at once.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/5923757/826458b0-08d6-4d83-882d-2a575567f6bd

### Environment

```markdown
- FlutterFlow version: v.4.1.34
- Platform: MacOS Desktop
- Browser name and version: Chrome
- Operating system and version affected: macOS Monterey 12.7.3
```

**Comment by rzambroni** [comment]
HI @ebrammer, thanks for the report. We were able to reproduce this issue on the macOS desktop app. Might be useful to know that it is working fine on the FlutterFlow web app, just in case you need a workaround until this is fixed. 

Thanks.
