### ISSUE TITLE
Local Project will not update since 4.1.35 upgrade

### ISSUE THREAD

**Issue by solacetouch** [FlutterFlow/flutterflow-issues#2617]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been working in the MacOS app all day and everything was working fine. I then updated to FF 4.1.35 and not my local project won't update. I have a Google Pixel 8 Pro connected in my devices. The hot reload, restart functions will not send the updated changes I made in the builder. Also, both the Test & Run fail in browser despite their being no errors in the project. 

<img width="857" alt="Screenshot 2024-03-28 at 5 20 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90054679/f994c8ab-8ffc-4437-8acc-db5b90aa6c92">

### Expected Behavior

The updated project should be exported to the device. 

### Steps to Reproduce

1. Update to latest MacOS FF app
2. Create a page
3. Test on local device
4. Make a change on the page
5. Test on local device
6. Observe the change is not reflected

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/q4ot1mMdG1c+BasJR/T0WH2E2UK88scp/bxIgGIDzPOw+ZPWkck9BYOGjT29AekSmmlMCpMLWjc71Juw7FzaZc6pS+blcEjziJUK5UZOBDKiKWEZRJ+JWf36935+z2QpAFNhvWmQ/60z2eu6Qb3PdK7q3IlFISq/LZO4=

### Context

I am unable to continue development as changes are not reflected. I cannot troubleshoot effectively as I have made a change that should fix an issue but it is not being updated

### Visual documentation

I tested with a simple change: 

**1. Screenshot in builder with "Messages" in the app bar**
<img width="422" alt="Screenshot 2024-03-28 at 5 21 47 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90054679/e71321ba-a6af-4dbb-95e5-4c5a9ed03142">

**2. Screenshot showing "Messages" was removed from the appbar @**
<img width="423" alt="Screenshot 2024-03-28 at 5 21 53 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90054679/2b3ae283-3cd0-4623-96e1-6d77084928cf">

**3. Screenshot of the project being exported to the local Google Pixel Device after the change** 
<img width="1680" alt="Screenshot 2024-03-28 at 5 26 19 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90054679/f563c2f8-f355-46c0-b97e-c3f485f6b9ad">

**4. Screenshot of Google Pixel device not reflecting update**
![Screenshot_20240328-173026](https://github.com/FlutterFlow/flutterflow-issues/assets/90054679/d0191fa5-15c0-4865-8fa9-57d1b8f74197)

### Environment

```markdown
- FlutterFlow version: 4.1.35
- Platform: MacOS app
- Browser name and version: N/A
- Operating system and version affected: MacOS Ventura 13.4
```

**Comment by rzambroni** [comment]
Hi @solacetouch, unfortunately, i'm not being able to reproduce this issue on a blank project. Tested both with Android and IOS devices and using the latest FF version for MacOS. 

Both the hot reload and restart are exporting the changes to the device as expected. Are you still having this issue? If so, perhaps you could try to reproduce this on a blank project to discard any project specific issues.

**Comment by solacetouch** [comment]
I believe this was a project issue. I reverted the project to an earlier time and it was resolved.
