### ISSUE TITLE
Flutterflow Crash After using Dynamic Components

### ISSUE THREAD

**Issue by nyaroon** [FlutterFlow/flutterflow-issues#2620]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in flutterflow editor when i open the page, the page suddenly freeze and become blank 
<img width="1724" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/39451264/6ec638e4-38e0-4f3f-8d26-a50da34fe702">

### Expected Behavior

when opening page the editor work properly and can be clicked not blank

### Steps to Reproduce

1. create a new page
2. add reference dropdown (from supabase quary)
3. make datatable that show data from reference quary
4. add component for note
5. crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiM7qw5dOoeFb+KXpK8dolWARGUMdXOczitVEew4bCIj4EJoUOs/RTFtoZMizaH56GmaL8Tk07taNhobfVMY4aByAY7l8/pZ2URPPbDqgV7rUCruNPHFAM8ZVI2KD0ZmngRUlXdd2clIsw2GmANytUT+Cf9qOYwx5e6fDbOY=

### Context

editing on flutterflow like normal, i try to make dynamic content when user input the data the preview pdf will show up

### Visual documentation

<img width="1747" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/39451264/670d363f-b013-4bf2-b239-45d787e22fc5">

### Environment

```markdown
- FlutterFlow version: 4.1.35
- Platform: MacOS Desktop
- Browser name and version: Flutterflow Mac Desktop and Google Chrome
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by ignalauret** [comment]
Hey @nyaroon thanks for your report. I checked your project and I was able to add a component without it breaking. Are you still experiencing this issue?
