### ISSUE TITLE
Tap to hide keyboard not working

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#2621]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Taping anywhere on the screen does not hide the keybaord. There is a down icon on the bottom of the keyboard, but that is not the same.

### Expected Behavior

Keyboard is hidden

### Steps to Reproduce

Create page, set hide keybaord on tap to true, add text input, focus on text input when app is renered on Android phone. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YMWvfObhJeZ+m+THxcL2CZmmMz7sLJvuPIA+UqGziAbLZizahQZxWXQkmRV82SBaWOOHwnJ9pJJVyw34m3rRRCIfpfSl4a1Dque+TJYz3tGL7MIkUeDcj+Jp3XnGOqQ0SLb3kNh1JWeC/v

### Context

Poor user experience
![Screenshot_20240329_003602](https://github.com/FlutterFlow/flutterflow-issues/assets/153652817/037d37bb-578a-4cc9-88e4-40db6314c86e)

### Visual documentation

aaa

### Additional Info

aaa

### Environment

```markdown
- FlutterFlow version: latest
- Platform:Windos?Android
- Browser name and version: NA
- Operating system and version affected: Android
```

**Comment by ignalauret** [comment]
Hey @charliefabley thanks for your report. Sadly I was not able to reproduce your issue, the keyboard is hiding for me when I have that option selected, and staying there if I unselect it. Please make sure that you are not tapping on another widget that can get focused and keep the keyboard there. 
If you still have this problem, please share a video with your experience so I can replicate it better.
Have a great day.
