### ISSUE TITLE
Flutter flow for windows not updated?

### ISSUE THREAD

**Issue by withinboredom** [FlutterFlow/flutterflow-issues#2622]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Starting a new flutterflow project in the browser then opening the same project in flutterflow for windows results in an error:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1883296/ef36b10c-8c02-4208-becd-20dff6458210)

The current windows version is 4.1.33, the web version just says 4.1 released March 28th

### Expected Behavior

A new update for Windows to be released at the same time as the web version for local testing to work.

### Steps to Reproduce

1. create a new project on the web
2. make some small changes here and there
3. install the latest windows version
4. open the same project in the windows version
5. See the error:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1883296/a877f9b5-21a4-456b-a6c5-15b27e1a20d2)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si8mB249Im8sA7q6JbflR/GUXNkB/bZIkscp/bxIgGIDzPOw+ZPXsSBNvTsu5d2w6PkSmmkwx0db0v4aXUvk7BEyaG5g7wc0Baw7jXn+uQZOBPJGWPnZBM8JmN2rH0J+JniRANvZfLk4GwE+IDe68TgPsCZjtIlFISq/LZO4=

### Context

Unable to load project in windows

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/1883296/51dadccc-ac14-486c-a2cc-32e66cc646d2

### Environment

```markdown
- FlutterFlow version: v4.1 released march 28, 2024 & windows 4.1.33
- Platform: web + windows
- Browser name and version: Edge 122.0.2365.92 (Official build) (64-bit)
- Operating system and version affected: windows 11
```

**Comment by TheoBouwhuis** [comment]
Experiencing the same after my colleague opened the project with an updated Mac version.

**Comment by MurfyJB** [comment]
I'm experiencing the same issue. 

The version reported by the FlutterFlow windows App is `windows 4.1.33` if that helps, and our project's is `1.4` (not sure how to display the patch version in web)

**Comment by areichmann76** [comment]
macOS App is updated to 4.1.35 (and works) so we are missing the update for windows 👎

**Comment by withinboredom** [comment]
I have a feeling this is one of those "you need to know someone at Google to get this fixed" kind of problem.

**Comment by gustavo-cycling** [comment]
That sound you hear is a group of Google engineers that spend their working hours posting disrespectful garbage on Memegen mocking other companies and their products instead of fixing this problem.

**Comment by sabatage3** [comment]
@withinboredom I guess they don't update the web app and desktop apps simultaneously, simply use flutterflow web in the meantime, is not a real issue, and right now windows app is working again, at least for me, you should close this issue which is duplicated by the way

**Comment by withinboredom** [comment]
> I guess they don't update the web app and desktop apps simultaneously

@sabatage3 yes, they do. Mac version was updated, but not Windows.

> simply use flutterflow web in the meantime, is not a real issue

If you are building native versions, it is a very real issue because you can't build windows apps on the web version.

> right now windows app is working again

yep, seems to be working.

> which is duplicated by the way

I think you mean to say that the issues posted after mine are duplicated? Not sure how that is my problem.
