### ISSUE TITLE
PathUrlStrategy Nested Paths not working

### ISSUE THREAD

**Issue by scottwyn13** [FlutterFlow/flutterflow-issues#2624]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to access a path with a trailing"/" such as ".../home/" or a nested path such as ".../home/test/" page does not load and error as follows in console.

Issue was reported on Flutter and seems to be fixed with Flutter 3.7 but still seems to be an issue in FlutterFlow (using Flytter 3.19.1)
[https://github.com/flutter/flutter/issues/116360](https://github.com/flutter/flutter/issues/116360)

> 

> flutter.js:3 Exception while loading service worker: DOMException: Failed to register a ServiceWorker for scope ('[http://localhost:50435/home/](http://localhost:50435/home/)') with script ('[http://localhost:50435/home/flutter_service_worker.js?v=](http://localhost:50435/home/flutter_service_worker.js?v=)'): The script has an unsupported MIME type ('text/html').

> Refused to execute script from '[http://localhost:50435/home/main.dart.js](http://localhost:50435/home/main.dart.js)' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### Expected Behavior

Should go to the path given:
/home" should go to the page with path "home"
/home/test/ should fo to the page with path "home/test"

### Steps to Reproduce

Create new app
Add page
Set route to home/test
Create Local Run on Chrome
Attempt to go direct to path with trailing "/" such as "[http://localhost:50435/home/](http://localhost:50435/home/)" or "[http://localhost:50435/home/test](http://localhost:50435/home/test)"
Console shows error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gobhA1pPIbsJAhQIgQ0QnU7gnlO1ucx4cCO/2OuxyPff4ZUNKT9OrTXNiA0yYrHgHwej9kt/1Gvc7Bw6Ab6pP0JVAZAzyWTmRb7maELi8YHJfIJ5YIWqG16u3hBBdJstac3w57F2TNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Unable to use apps that have nested paths or parameters in paths (i.e. ":username")

### Visual documentation

Provided in explanation

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.35
- Flutter version: 3.19.1
- Platform: Web
- Browser name and version: Chrome v123.0.6312.87
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by ignalauret** [comment]
Hey @scottwyn13 thanks for your report. I read the issue that you shared from Flutter and it should be fixed on the actual version that FlutterFlow uses. Are you still experiencing this problem?

**Comment by leighajarett** [comment]
Closing this issue since we haven't heard back from you, thanks!

**Comment by diegoserranobst** [comment]
Please reopen the issue. I have exactly same problem I am ussing version 
FlutterFlow v4.1.86+ released September 5, 2024
Flutter version is 3.22.2

If I add / before this lines in the index.html at build/web the problem fixed, but I have to doit each time I download the code with cli.
<script src="/flutter.js" defer></script>
entrypointUrl: '/main.dart.js',
serviceWorkerUrl: '/flutter_service_worker.js?v=',

**Comment by leighajarett** [comment]
Hi there! Thanks for filing, can you please create a new issue with your project information / bug report code so we can try and reproduce?
