### ISSUE TITLE
CRITICAL - Walkthrough BUG on Page Delete

### ISSUE THREAD

**Issue by apppbuilder** [FlutterFlow/flutterflow-issues#2626]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Built a test page, linked a walkthrough to it, and then, accidentally, deleted the page. Ok, since then the Walkthrough page is as displayed below.

Any new Walkthrough added is not being displayed. In this case, I created another to test 2 Walkthrough in the same page (both would start in different moments at the same page), but now I can't even delete the second after getting the error.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4be5ad59-7030-4d2c-9d94-63548eb98c87/87d7542e-cfa0-45a6-a89f-da6be4e07c00?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YmU1YWQ1OS03MDMwLTRkMmMtOWQ5NC02MzU0OGViOThjODcvODdkNzU0MmUtY2ZhMC00NWE2LWE4OWYtZGE2YmU0ZTA3YzAwIiwiaWF0IjoxNzExOTc4NDk2LCJleHAiOjMzMjgyNTM4NDk2fQ.uFYflH8tyk1N5qg4KnnEa4dHNElzQeGrlJiIQHR6YdA)

# **I can't build/deploy the app with the problems above.**

### Expected Behavior

After deleting the page linked to a walkthrough, both should be deleted at the same time.

### Steps to Reproduce

1. Create a page.
2. Link a walkthrough on it and link an action to start walkthrough on the page.
3. Delete the linked page.
4. Check walkthrough page to see the bug.

More steps:
5\. Create new walkthrough.
6\. No new walkthough is displayed because of the gray area caused by step 3.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CjPLlvJFIocte7q6JcMdVoCMvNlw2RYIw1+xEVg8cDZPOD+x/fMnBN1dUcMe9YAl+JWaGjToX/MrxiYaeKfZcBxyqY6JCwapMYD3hZGWiaLKtO663b3J8M/1mJlSC58K3phIkOvRoL2NgwEylNdmtUhbXH4DzC1g3NOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

Use walkthrough.

### Visual documentation

Already added in the section above.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by apppbuilder** [comment]
I found a way to "get off" of this bug, I searched for the name of the missing Walkthrough and found it, then I clicked to DELETE it and it started deleting the adjacents Walkthrough. Really?

Now I need to create every Walktrough again but how can I manage if it doesn't work?

**Comment by bozzoleandro** [comment]
Hi @apppbuilder, thanks for the report. we were able to replicate this issue and we're looking into it.

**Comment by sbis04** [comment]
This should be fixed in the next update!
