### ISSUE TITLE
Flutterflow version out of Date

### ISSUE THREAD

**Issue by jxhp7366** [FlutterFlow/flutterflow-issues#2627]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No ingresa al proyecto actualizado desde la web cuando he vuelto a trabajar en windows app

### Expected Behavior

Quisiera que hubiera un boton de refresh para solucionar el problema que sale.

### Steps to Reproduce

1. Upload asset List view on Windows App
2. Upload asset on List view on Web
3. Return to windows app and don't enter to project but other projects i can enter.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WzfHlvJR2od9G15SJccFsnjwXHEx8aIInksN9dwsjC4OuP5wPXfnRalhoTN+idGNqL0788WQx0/zJuNrIA+UqJTSaGKpG+pd2FALhVk+jaZPSEs2KQnwlJ+VJJVyD0JiJnRN4KrJvcVkj1F+QCtnIaAvsHZjJPFURO86iCJPXkXOrQ0SLb3kNh1JWeC/v

### Context

Estaba trabajando en windows con FlutterFlow cuando no pude subir un asset decidi trabajar via web pero despues de subir el asset para un listview me salio la siguiente imagen y ya no puedo entrar a trabajar en windows Flutterflow.

### Visual documentation

![outdate](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5ea3603f-055b-46e2-b2a6-fc9c47c898e5/a64dacd4-f58d-4306-b026-d36effac099e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ZWEzNjAzZi0wNTViLTQ2ZTItYjJhNi1mYzljNDdjODk4ZTUvYTY0ZGFjZDQtZjU4ZC00MzA2LWIwMjYtZDM2ZWZmYWMwOTllIiwiaWF0IjoxNzExOTc4NDY4LCJleHAiOjMzMjgyNTM4NDY4fQ.vq2FOqULqqiVu9vOox3TdQMLgaqgKNeSjgrgRye-Rdk)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.33+
- Platform: Windows Flutter 3.19.1
- Browser name and version: n/a
- Operating system and version affected: Windows
```

**Comment by sabatage3** [comment]
@jxhp7366 Esto ocurre cuando actualizan la plataforma de flutterflow, pero no actualizan el app de windows o mac simultáneamente. Cuando esto pase, simplemente debes trabajar en la web mientras actualizan la app de escritorio, por lo que he visto, solo les toma 1 o 2 días actualizar las apps, deberías cerrar esta issue, para que el equipo pueda concentrarse en errores mas urgentes

**Comment by leighajarett** [comment]
Hi there! Thanks for filing this issue. This should be resolved now.
