### ISSUE TITLE
uploading media to Flutterflow for Windows is not working

### ISSUE THREAD

**Issue by luizeduardofs** [FlutterFlow/flutterflow-issues#2628]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I'm on the development screen or the project's media screen, when I click to upload any media, it stays loaded all the time and doesn't upload the file

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46005008/821bced2-a4fa-4395-8cec-bc8f94aed09b)

### Expected Behavior

When I upload a file it will be available for use in the project

### Steps to Reproduce

1. Open FlutterFlow desktop on Windows
2. Create some example project
3. Go to media page in your app
4. tap in Upload Media button
5. And wait forever  :(

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

zsdfzsdvsd

### Context

Lorem ipsum dolor sit amet. In perferendis magni aut quidem asperiores aut quam sint aut Quis quia aut commodi molestias ut nobis veritatis? Sed nobis magni qui quibusdam voluptatem et illo vero sit sint molestiae sit numquam dolores. Ut saepe totam id voluptatibus blanditiis ea porro rerum sit facere maxime est reprehenderit autem!

### Visual documentation

Lorem ipsum dolor sit amet. In perferendis magni aut quidem asperiores aut quam sint aut Quis quia aut commodi molestias ut nobis veritatis? Sed nobis magni qui quibusdam voluptatem et illo vero sit sint molestiae sit numquam dolores. Ut saepe totam id voluptatibus blanditiis ea porro rerum sit facere maxime est reprehenderit autem!

### Environment

```markdown
- FlutterFlow version: 4.1.34+
- Platform: Windows 11 home
- Browser name and version: none
- Operating system and version affected:
```

**Comment by jazzedge24** [comment]
Same issue here.

**Comment by dabupk** [comment]
same issue here

**Comment by matheuspina** [comment]
Same issue here

**Comment by rzambroni** [comment]
Hi @Eduardo-Vitesse, thanks a lot for the report. We were able to replicate the issue and we will be taking a look. In the meantime, please consider using the WebApp as a workaround until this is fixed.

**Comment by luizeduardofs** [comment]
Thanks for the answer, I'll be eagerly waiting for the solution. Most grateful for your attention
