### ISSUE TITLE
Container implicit animation duration bound to opacity of the container

### ISSUE THREAD

**Issue by Titouan-Loeb** [FlutterFlow/flutterflow-issues#2629]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to add implicit animation to my container i can change the duration of the animation. The problem is that when I change the duration using the text field, the value of the duration is also applied to the value of the opacity of the same container and vice verse. When I change the opacity the value is applied to the duration of the implicit animation. Also the the slider for the duration of the implicit animation is not doing anything (it seems so).
So it is impossible for me to have a different value for the opacity and the duration of the implicit animation

### Expected Behavior

I think the expected behavior is obvious, the slider for the duration of the implicit animation should change the value of the duration and changing the value of the duration should not change the value of the opacity of the same container and vice versa

### Steps to Reproduce

1. Create a new project
2. Add a container in the already created column
3. Turn on the implicit animation of the container you just added
4. Change the duration of the animation using the text field
5. Check the value of the opacity
6. Change back the opacity
7. Check the value of the duration of the implicit animation
8. Don't be to harsh on the dev (especially if he is a junior) this stuff can happen, it is no big deal <3

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l7c92rsMA+KnuKvpanWURI0McWOdEl+tuZwgbIoznBux/fOP8ak9BcMOraVNcPFSbmlkezPzWiobQUvBdYQSbbbpi+LpqcQree2igRa6kPM2gWkB5O5lUfHK00bSNsBBAXLJvR04h2zn3Pt6vfC7DFOu/Zwh9f6PHaOI=

### Context

Well, I was trying to add an animation and I can't right now.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/77047599/cf88ba5a-ec14-4c6a-9872-130d03af1d56](https://github.com/FlutterFlow/flutterflow-issues/assets/77047599/cf88ba5a-ec14-4c6a-9872-130d03af1d56)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.34
- Platform: Web and Windows Desktop
- Browser name and version: Chrome version 123.0.6312.105
- Operating system and version affected: Windows 11, version 23H2, os build 22631.3155
```

**Comment by bozzoleandro** [comment]
Hi @Titouan-Loeb, thanks for the report, we were able to replicate it, we'll be taking a look.

**Comment by pyro32** [comment]
I'm experiencing this issue too and it's completely broken my app

**Comment by jhonier93** [comment]
I'm experiencing this issue too.

**Comment by sirian-m** [comment]
Same here!

**Comment by kalloszsolty** [comment]
Same here

**Comment by handri-santoso** [comment]
me too

**Comment by kalloszsolty** [comment]
I see it's fixed in the new Mac app

**Comment by pyro32** [comment]
How about on web and the windows app?
