### ISSUE TITLE
Display Names in App Details works strange.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#263]
## Expected behavior (required)
There should an error if I put the display name that is less than 4 characters.
And there is an error but when I go to another screen and comeback, the error disappears.

## Current behavior (required)
If there is an error, it needs to display an error message like what it does on editing.
Or if there is no error, it should not complain when editing.

## To Reproduce (required)

1. Input two characters on Display Name in App Details. And you will see error.
2. Go to App Assets screen.
3. Come back to App Details screen.
4. The error is gone.

So, the Display Name in two characters is working? or not?

## Screenshots / recordings

https://user-images.githubusercontent.com/5080329/209162178-0009f67c-77d6-455f-b172-868e5c0da6c4.mp4

## Your environment

* Version of FlutterFlow used: Flutterflow v3.0 released December 22, 2022 Flutter version is 3.3.4
* Platform: Web
* Browser name and version: Google Chrome Version 108.0.5359.124 (Official Build) (arm64)
* Operating system and version: macOS Ventura 13.0.1

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next release - FF won't save invalid values on the App Details page.
