### ISSUE TITLE
Webview Go Back is Navigating Back to Activity instead of Webpage

### ISSUE THREAD

**Issue by crossxsecure** [FlutterFlow/flutterflow-issues#2630]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In FlutterFlow, the 'Go Back' function in WebView is incorrectly navigating back to the Activity, instead of navigating back within the webpage itself. This issue has been tested with multiple websites and the behavior remains consistent across all tested sites. The issue has also been reproduced on multiple Android devices, indicating that it is not device-specific.

### Expected Behavior

The ‘Go Back’ function is expected to operate similarly to the webview.GoBack() method, which checks if there is a previous page available in the WebView’s history stack. If a previous page is available, it should navigate back within the website itself. If not, only then should it navigate back to the Activity. The current behavior suggests that the ‘Go Back’ function may be mistakenly linked to the Activity’s back stack instead of the WebView’s history stack.

### Steps to Reproduce

1. Open a WebView in FlutterFlow.
2. Navigate to a webpage.
3. Click on a link to navigate to a different page within the same website.
4. Use the 'Go Back' function.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkPLqx5BPsdhE0KXIYcJV/SowGUgXU4I3te5+d0shfLauE5lyOsjSTEtLYteLSm5qH2aWp3Ez0ejPvt/DKsA3GxGWGZxDyYRXQTrwd3O6RbqlBpG8OmtBBZ1Ufmak18PQvyVSGNFaSi0h6nGPNfCNG3qCf9qOYwx5e6fDbOY=

### Context

This issue interferes with user interactions, particularly when they are engaged in a multi-step business process within the webpage. When users tap ‘back’, instead of moving to the previous step within the process, they are unexpectedly exited from the webpage and returned to the FlutterFlow Activity.

### Visual documentation

NA

### Additional Info

NA

### Environment

```markdown
- FlutterFlow version: 4.1 Latest (Released on 28th March)
- Platform: Tested on Android
- Browser name and version:
- Operating system and version affected:
```

**Comment by crossxsecure** [comment]
Hi @hariprasadms @wenkaifan0720 @FlutterFlowEng could you please look into this issue? this has been reported 2 weeks ago but still has not be addressed yet. Hence, can you please go through the same?

**Comment by leighajarett** [comment]
Sorry about that! Taking a look now

**Comment by rzambroni** [comment]
Hi @crossxsecure, sorry about the delay in the answer, we are trying to get up to speed with every report 🙏

I was taking a look at your project, Just to confirm, what you are trying to achieve is to be able to navigate to the previous webpage inside the webview by using the Navigate Back action associated with the arrow? (see screenshots of one of your webview pages)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ded695e4-b062-40f3-8f9a-19bed92c7f29/454db40d-aa78-481f-a3d8-dd921afc5a3f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZWQ2OTVlNC1iMDYyLTQwZjMtOGY5YS0xOWJlZDkyYzdmMjkvNDU0ZGI0MGQtYWE3OC00ODFmLWEzZDgtZGQ5MjFhZmM1YTNmIiwiaWF0IjoxNzEyODgwOTU1LCJleHAiOjMzMjgzNDQwOTU1fQ.lMMpWpnicNKGfZJ4xCep4OOy5OLsquHvau9n7JCT0sA " alt="image.png" width="2556" height="1311" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/68068fad-59e3-4405-9516-6ca155f0e23d/a4513281-7f02-451f-9c1d-f648efd99bfc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ODA2OGZhZC01OWUzLTQ0MDUtOTUxNi02Y2ExNTVmMGUyM2QvYTQ1MTMyODEtN2YwMi00NTFmLTljMWQtZjY0OGVmZDk5YmZjIiwiaWF0IjoxNzEyODgwOTU1LCJleHAiOjMzMjgzNDQwOTU1fQ.0e6AImONCmTsOiXYR8M8EkQJWdwBb_ifS10DdBUUlNA " alt="image.png" width="1872" height="1002" />

If that is the case, unfortunately, it is not possible, since the navigation actions in FF are for pages within the app, not for the WebView. 

I'm not entirely sure if you could make a custom action to accomplish this behavior but i'll ask around to see if i can give you any other advise.

Thanks!

**Comment by crossxsecure** [comment]
Hey @rzambroni, I’ve implemented the explicit back button as a temporary solution. I encountered a problem where I was redirected back to the FlutterFlow activity rather than within the webpage. To address this, I deactivated the back button in the FlutterFlow activity and introduced a custom button for navigating back from the webview.

I’ve reactivated the back button to facilitate your navigation. Additionally, this issue can be reproduced in other projects as well.

<img width="1365" alt="Screenshot 2024-04-12 at 12 10 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/107629670/4ae75761-4541-4b6e-8f60-147d9b7783cb">

**Comment by rzambroni** [comment]
Hey @crossxsecure, thanks for the details. Would you mind sharing a blank project example so we can test this out isolated? Thanks!

**Comment by crossxsecure** [comment]
Hey @rzambroni, you can replicate the issue in both the projects, another project having the webview is project id 'car-assist-2c78jj' 

The issue is replicable on the Android devices.

<img width="1661" alt="Screenshot 2024-04-13 at 12 51 56 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/107629670/be7fb4ad-a69f-4b7a-8f50-0a80e4cfb3bc">

**Comment by rzambroni** [comment]
Hey @crossxsecure, thanks for sending over another example. At the risk of being obnoxious, one more question just to confirm what you are trying to achieve here. When you mention the "go back" function, are you referring to the FF action "Navigate Back"? Or the OS's action (in this case Android) to navigate back (pressing the arrow back on the Android bottom navigation bar for example). Or maybe something else?

**Comment by crossxsecure** [comment]
it's Android back button @rzambroni. The issue arises when we use the back button or the Android back swipe gestures to navigate. Instead of moving between webpages within the WebView, the app exits the WebView entirely. For instance, if you’re engaged in a multi-step business process, pressing the back button should ideally take you to the preceding webpage, if one exists. However, in this case it is exiting out from the webview.

Issue Tested In: OnePlus, Xiaomi, Oppo, Samsung devices.

**Comment by rzambroni** [comment]
Hey @crossxsecure, thanks a lot for the context. Yes, I figured that was the case. Unfortunately, due to the current implementation of the WebView in FlutterFlow, which uses an embedded WebView, it's not possible to control navigation inside it using OS controls. However, I agree that it would be beneficial to offer a choice between WebView types. I’ll create a feature request for this and add it to our internal backlog so the team can consider implementing it soon.

I'm also closing this issue since this tracker is intended for bugs and not feature/enhancement requests.

Thanks a lot for your feedback!

**Comment by crossxsecure** [comment]
Thank you @rzambroni for your attention to this matter. While it’s true that the current implementation in FlutterFlow relies on an embedded WebView but I'd like to emphasize that the inclusion of navigational features within webviews is not merely a feature request but rather a **critical necessity**. This behavior aligns with the common expectation for webviews, and any deviation from it should be considered as a **bug**.

When implementing a webview on any platform, the standard expectation is to include navigational features and without that there is no use of the same rather than having a single webpage. To illustrate, consider a straightforward scenario: embedding a Google search or YouTube URL within the FlutterFlow webview. Even in this case, if we press the back button at any moment, it will exit the webview frame.

Kindly prioritize addressing this issue promptly, recognizing its significance in ensuring a seamless user experience. Your consideration is greatly appreciated.

**Comment by leighajarett** [comment]
Totally understand. We've marked it as a high priority in our back log and will try and solve this as soon as possible. Thanks for the feedback - closing this issue as we are tracking as part of our feature backlog (I understand you think this should be classified as a bug, however this is simply how we track things in our internal systems). Thanks for understanding!

**Comment by crossxsecure** [comment]
I appreciate your response, @leighajarett, and I understand your point. However, the issue here is that even a basic operation like the Google search page navigational back button is failing in the webview. This makes the webview essentially ineffective beyond displaying a simple page. This isn’t a matter of requesting an additional feature - a feature implies an optional, subjective enhancement. Hence, it would be great if you consider it as a bug so that it can be prioritised for early deliverables otherwise as a feature request it might take several weeks/months to have the basic operation on a webpage.

**Comment by crossxsecure** [comment]
Hey Team, I would like to bring to your attention an issue that was initially raised two months ago. This issue, despite being a fundamental functionality, was categorised as a Feature Request and subsequently closed.

@leighajarett - This fix will not only benefit my project but also enhance the experience of anyone who is a FlutterFlow customer. They expect this as a bare minimum. It’s akin to navigating on Chrome browser on your mac, and as soon as you tap back button, you lose everything - a situation that is far from ideal.

Business Impact: 

In the current business landscape, many companies have started affiliating with other companies as it’s not feasible to have every service in-house. A prime example of this is Amazon and Flipkart, who have partnered with multiple third-party aggregators and offer third-party facilitation as part of their services, which includes SSO and other business purposes. Due to the back button issue, if an end user navigates to these services, the WebView fails to provide a seamless user experience. If they are on Page N, pressing the back button will exit the entire WebView and the whole business process then needs to be executed again.

I kindly request you to consider this issue either as a bug or an improvement based on your business labels, and prioritise it for early deliverables. Your understanding and support in this matter are greatly appreciated. As we all know, tickets requiring minimal effort can be prioritised based on their criticality. In this case, the basic functionality seems to be broken, which is a bit concerning. The issue primarily involves checking if the WebView can go back or not, for which I believe the fix effort is very low.

**Comment by techbuild360inc** [comment]
Hi @FlutterFlowEng Team, It’s been around 6 months waiting for this to release. Hence, could you please address this issue? It is a simple back button navigation failing request. the inclusion of navigational features within Webview is not merely a feature request but rather a critical necessity.
