### ISSUE TITLE
Redirection to the Same Tweet on Twitter When Clicking User Profiles

### ISSUE THREAD

**Issue by eloufraoui** [FlutterFlow/flutterflow-issues#2631]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The action of clicking on a user's profile results in being redirected to an external Twitter post in a new browser tab.

### Expected Behavior

Interacting with a user's profile within the testimonials section is anticipated to either expand on the user's testimonial within the website or not lead to any action, rather than redirecting to external platforms such as Twitter.

### Steps to Reproduce

1. Navigate to the FlutterFlow official website: https://flutterflow.io/
1. Proceed to the section that displays user reviews or testimonials.
1. Select any user profile box.
1. Notice that a new browser tab opens, which redirects to a Twitter post.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESicn1sIlgocQE16rIa8dAhQIgQ0QnU7gnlO1ucx4jB4CqO7MuOeLBU0NKTeGcYX5UE1f9oGQFwN7RiePhCcc3ISSsb7pZ0JVPETzwJXuhMsWyPaWCYHx5GfNhGGqk0aas2SRDPsphLyU1w0+LNq3qNleeY8aSfxBlZ7vfcPo=

### Context

This redirection issue has notably impacted my user experience and exploration of the FlutterFlow website. As a potential user evaluating FlutterFlow for my next project, I was interested in reading testimonials and learning more about the experiences of current users to better understand how FlutterFlow could fit into my development workflow. Specifically, I was looking for detailed user stories or case studies that would illustrate how FlutterFlow has been used in various projects and what benefits it offers.

### Visual documentation

[Screencast from 04-01-2024 01:48:24 AM.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/154367712/8cc7d2e0-cfaf-4770-855b-049dba6a8f51)

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: web
- Browser name and version: Version 122.0.6261.111 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 22.04.2 LTS
```

**Comment by leighajarett** [comment]
Thanks for this feedback! Makes sense 🙂 

We'll take it into consideration for some future website updates. In the meantime, I encourage you to check out the showcase page: [https://flutterflow.io/showcase](https://flutterflow.io/showcase)
