### ISSUE TITLE
Editor Font broken on native Mac App

### ISSUE THREAD

**Issue by HeikoKanzler** [FlutterFlow/flutterflow-issues#2633]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the recent update, the editor font is broken on the native Mac App, it looks and behaves like the iPad version and it pretty useless and hard to read.

### Expected Behavior

Monospaced font for the editor as it was before on native and is on web.

### Steps to Reproduce

Open any custom code on the native Mac version

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz8mA24VNodtK+KX+d+1WnSgUI0MBX5Ir1utvGUwcG5OvP7A2ds7EaXdCOM+fTVB5MVCjuGUe7t7zuPHtNPldIQurftR607hAcAv/RluXWqqJPM6wVGh8DdlUIXaB3KuvoSMnObBuV2QB62GLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

It makes editing harder

### Visual documentation

![Screenshot 2024-04-01 at 10 20 11](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f539cbeb-7053-49ff-95fa-412349bf5527/3bd55291-9fc2-4c74-b0da-0832b0f56e43?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNTM5Y2JlYi03MDUzLTQ5ZmYtOTVmYS00MTIzNDliZjU1MjcvM2JkNTUyOTEtOWZjMi00Yzc0LWIwZGEtMDgzMmIwZjU2ZTQzIiwiaWF0IjoxNzExOTc4MzkwLCJleHAiOjMzMjgyNTM4MzkwfQ.Ax40bkH1kTl5dV8bHBuo_AAVRkDd6l8ATFnJ5STvGXg "=932x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.35, Flutter version is 3.19.1
- Platform: Macintosh
- Browser name and version: Native
- Operating system and version affected: Mac OS 14.4
```

**Comment by leighajarett** [comment]
Thanks for filing this, this is a known issue and something we're thinking more about as we make a variety of enhancements to the code editor!

**Comment by HeikoKanzler** [comment]
> Thanks for filing this, this is a known issue and something we're thinking more about as we make a variety of enhancements to the code editor! 

Thanks for conforming, but are you going to fix the new issue introduced a few days ago before you're thinking about enhancements or do we have to live with this bug until a new editor will be developed? 🙃

**Comment by leighajarett** [comment]
I don't believe it was broken a few days ago, I thought this was always the case for the font in the macOS app?

**Comment by HeikoKanzler** [comment]
Definitely with the last release a few days ago on the Mac. 

Not sure what happened here, it's not only the font, but also the theme of the syntax highlighting has changed.

**Comment by leighajarett** [comment]
@takashi could you confirm by chance? I was under the impression this was always the case in the desktop apps?

**Comment by HeikoKanzler** [comment]
Short update: it appears to be only a bug on Arm machines. I just had the time to work on my main machine, a Intel MacBook Pro and the editor font is monospaced (both latest versions):

![CleanShot 2024-04-06 at 19 49 39](https://github.com/FlutterFlow/flutterflow-issues/assets/5279575/8634490b-7224-418a-9f0c-970d08c897f1)

**Comment by HeikoKanzler** [comment]
(btw, the Arm version also doesn't remember the main window state (position and size), it's a little bit annoying :-)

**Comment by leighajarett** [comment]
Ahh I see, okay I think that was always the case because I have an ARM machine and I believe it's always been the case for me. We are working on several updates to the code editor planned for later in the year so this will likely be bucketed within those changes. Thanks again for flagging!

**Comment by leighajarett** [comment]
Closing because this is already tracked as part of our planned work for the code editor roadmap project
