### ISSUE TITLE
Complete Firebase schema gets erased when firebase project id changes

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2635]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This has costed me three days of work. I have changed the firebase ID for the project and i have seen that the complete firebase schema i have created in project just got erased. Its a hell again to create the schema and fix the issues on all pages.

### Expected Behavior

The schema created in flutterflow should not get erased even when the firebase project id changes. The schema is managed from flutterflow and in this case if i have issues with my firebase project and just wanted to create a new project and point the flutterflow to that, the schema should not get erased.

### Steps to Reproduce

1. Create a flutterflow project
2. connect to firebase project
3. create a schema
4. change the firebase project id
5. See the hell break loose that your schemas are erased and your complete project is in errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjvLl4otNm8te7aqMLO9WpGY4KWI5R4c0sNobbxAjIoDoPJkUaeLBXElCTermTQltKEWJvFId7srJhuLyUfQnGxyCGqJE1ZNUag3wXT6/aoSlO83hR3ZCLJtMJhWm5Luv3yR5BNZvL1462GWbNejKbD3UNOb7Zwh9f6PHaOI=

### Context

Firebase and flutterflow

### Visual documentation

Try it

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by ignalauret** [comment]
Hey @task-win thanks for your report. Could you confirm what you refer to when you say "change the firebase project id"? You can't change the project id of an existing Firebase project. So, if you mean changing the Firebase project that is linked to your FlutterFlow app, then we have been able to do that and the Schemas are not erased. 
Also, I don't see any errors on your project, could you confirm if this issue still persists?

**Comment by task-win** [comment]
Hi,
   I think you have jus tried changing the id and connect with firebase. Now try using Firebase setup wizard after entering the firebase project id. The reason I did is that the config files did not adjust to new firebase project. Once you start the firebase setup wizard, you will notice this issue.


Thank you,

From: Ignacio Lauret ***@***.***>
Date: Wednesday, 3. April 2024 at 21:44
To: FlutterFlow/flutterflow-issues ***@***.***>
Cc: srinivas sanikommu ***@***.***>, Mention ***@***.***>
Subject: Re: [FlutterFlow/flutterflow-issues] Complete Firebase schema gets erased when firebase project id changes (Issue #2635)

Hey @task-win<https://github.com/task-win> thanks for your report. Could you confirm what you refer to when you say "change the firebase project id"? You can't change the project id of an existing Firebase project. So, if you mean changing the Firebase project that is linked to your FlutterFlow app, then we have been able to do that and the Schemas are not erased.
Also, I don't see any errors on your project, could you confirm if this issue still persists?

**Comment by leighajarett** [comment]
Since we haven't heard from you in a while, we are closing this issue. Please re-open if you run into the issue again!
