### ISSUE TITLE
Latest Windows desktop app: Sign in with Google not working

### ISSUE THREAD

**Issue by Sampath-Lokuge** [FlutterFlow/flutterflow-issues#2638]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot log in to the latest Windows desktop app using Google. But it is working fine with the web app.

### Expected Behavior

I need to use Google sign in workflow

### Steps to Reproduce

Windows 11

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Windows 11 with FF desktop app

### Context

FF Desktop app

### Visual documentation

![ff](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4cb2cc8e-0ae0-4004-9c7b-1bc984aa4ff5/5bd46f3c-9ed2-4540-81ca-ee1be8ef353e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80Y2IyY2M4ZS0wYWUwLTQwMDQtOWM3Yi0xYmM5ODRhYTRmZjUvNWJkNDZmM2MtOWVkMi00NTQwLTgxY2EtZWUxYmU4ZWYzNTNlIiwiaWF0IjoxNzEyMDYyMDUyLCJleHAiOjMzMjgyNjIyMDUyfQ.TyoI_w5x0VU2AF07ea8BDoT-6wo-RZ43rkqi5GrejQU)

### Additional Info

*No response*

### Environment

```markdown
Windows 11
```

**Comment by leighajarett** [comment]
This is a duplicate issue, but it's something we're working on! Thanks for flagging

https://github.com/FlutterFlow/flutterflow-issues/issues/2582
