### ISSUE TITLE
Api call doesn't working  properly in run mode

### ISSUE THREAD

**Issue by Hitisha14** [FlutterFlow/flutterflow-issues#2639]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a problem,every thing works properly in test mode but when I deploy my website,api calls doesn't work,what should I do?

What have you tried so far?
I checked everything and I don't have any bugs in test mode

Did you check FlutterFlow's Documentation for this topic?
yes

![Image_20240330_152709_652](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/766a1660-9c22-4b9d-8dbf-fac8035aa062/737bcb2a-52f5-4adc-8637-683e464182ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NjZhMTY2MC05YzIyLTRiOWQtOGRiZi1mYWM4MDM1YWEwNjIvNzM3YmNiMmEtNTJmNS00YWRjLTg2MzctNjgzZTQ2NDE4MmFjIiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.dlWmQHcV3_AfHtD1C7pk1o15BUrPdIxEOuVdg-tA7CU)

### Expected Behavior

I added default value in my api call to avoid null value,altough it doesn't give me error any more, I set the value of my text from json path and it returns null for them.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0eda80a9-4e4e-4f38-97da-035edd13dc64/d9235a69-a63e-490a-b526-f0e51ecf0786?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZWRhODBhOS00ZTRlLTRmMzgtOTdkYS0wMzVlZGQxM2RjNjQvZDkyMzVhNjktYTYzZS00OTBhLWI1MjYtZjBlNTFlY2YwNzg2IiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.ICAqdt1lWfnKt4O8jaresSul0hWqsNXcjnFkd3JwFlk)

### Steps to Reproduce

1. Added the api call
2. as suggested added the default value in api call to avoid null
3. although it is not giving error but as i set the value of my text from json path it returns null for them
4. you can refer to the screenshots

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d172491b-d7d6-4a69-9033-c95eaf56f379/142e3124-3adf-47fb-86ca-f3ea60c3ad33?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMTcyNDkxYi1kN2Q2LTRhNjktOTAzMy1jOTVlYWY1NmYzNzkvMTQyZTMxMjQtM2FkZi00N2ZiLTg2Y2EtZjNlYTYwYzNhZDMzIiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.XTBeDarQSpo2mZ16DRizDEP87HumfF1n8Xy55VtgpMM)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5213902c-43fd-4bb0-9af0-3a90e6c6be39/74d58edc-fee2-446f-b3bd-2d23eace43c9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MjEzOTAyYy00M2ZkLTRiYjAtOWFmMC0zYTkwZTZjNmJlMzkvNzRkNThlZGMtZmVlMi00NDZmLWIzYmQtMmQyM2VhY2U0M2M5IiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.Nh-KMIdLrEl-cbAW4k5J9B0lvXy0QQXEAWlgTZTsUHg)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8c0ee56a-6431-4a7a-a894-4bdf65eda5f0/c47e9e73-a435-48ed-80d6-6a47113757b5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84YzBlZTU2YS02NDMxLTRhN2EtYTg5NC00YmRmNjVlZGE1ZjAvYzQ3ZTllNzMtYTQzNS00OGVkLTgwZDYtNmE0NzExMzc1N2I1IiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.U9ep2a22a5SEquEzvzm4OBGrmYO0lmyDvLrIGBp9sRs)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WzsiA34Zgrsdc7s/UY8dFmikUJkx/aIJEl8N+ZxMaGLasOowPXfikSEpWZ9+kTHxcL1mJkngd+v+KuPzMA+UoNRWCQNk5wodtFxXwUkyQMLahCZe0Q2hPINJJJVy03ImnpR0nGONhWUVn1DiqFdy/VivcN4SxNTABFs6JMqz5pFWrQ0SLb3kNh1JWeC/v

### Context

i am trying to publish my website , when i am trying to delopy the code the pai is not working properly i asked in fluttercommunity as well but no one has repiled .

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f1f32303-a050-4ed3-a67a-80b200167483/47304baf-194e-4874-8fa2-8f67d31343a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMWYzMjMwMy1hMDUwLTRlZDMtYTY3YS04MGIyMDAxNjc0ODMvNDczMDRiYWYtMTk0ZS00ODc0LThmYTItOGY2N2QzMTM0M2ExIiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.QOmVmOKPNIg8bs3Vcie2E9hcmm-_NDoUviz5P-1dEcM)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/24e4ed23-ac42-4d4f-8f86-4b567fd73686/af911de6-55f6-420c-99e3-998eee5f43d1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNGU0ZWQyMy1hYzQyLTRkNGYtOGY4Ni00YjU2N2ZkNzM2ODYvYWY5MTFkZTYtNTVmNi00MjBjLTk5ZTMtOTk4ZWVlNWY0M2QxIiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.qlhS42I4ALzfLaumsPGOfCgy2gryz0VAb6mIlryJrU0)

![Image_20240330_152709_652](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4909023e-91ea-4a84-b1aa-fdba46ab5bc8/38f89141-2a84-4aef-b173-17edff96ee87?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80OTA5MDIzZS05MWVhLTRhODQtYjFhYS1mZGJhNDZhYjViYzgvMzhmODkxNDEtMmE4NC00YWVmLWIxNzMtMTdlZGZmOTZlZTg3IiwiaWF0IjoxNzEyMDcwOTEyLCJleHAiOjMzMjgyNjMwOTEyfQ.KBrLrt-In7DR6dW6sdGLcA9lC0e0-4UHhZwM5345pBM)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 (flutter 3.19.1)
- Platform: Web,Desktop
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: Windows 11
```

**Comment by ignalauret** [comment]
Hey @Hitisha14 thanks for your report. I'm checking your project but I can't find the Transfer section that you are showing. Is this happening for all of your API calls or just for that on? 
If you could please provide a Blank project with only one API call showing the bug that you are facing that would be great. That way I will be able to debug it better and maybe come up with a solution for you. 
Have a great day.

**Comment by Hitisha14** [comment]
Hi @ignalauret acutally i am facing issues with all api calls , the api calls is not working i am providing an api call list here which i have added so you can check and let me know.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/2388739e-28de-47bd-9363-c144d9cd366b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/3f24039d-886e-46db-b727-69db127c33b1)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/178d6571-3fe4-4c07-aac3-b452ea9fa7bd)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/f96447ea-4d8e-4013-84a5-97478be87bf7)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/c070c99b-d268-4947-ba92-457b64f6e0bd)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/5c703a39-23c8-4328-8b60-642f5c91e9ee)

on run mode getting null value 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/b5b5d4fd-d055-4b3a-95a9-f3b408fce8f9)
when i inspect this page it is showing me this: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/1a05ee2a-8959-42e7-b165-48feb222bd3d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/b9046822-ad7d-45dd-83d2-69f121dc3f47)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/c186b22c-16d7-4c4d-bfda-542fee348fdf)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/05eb2502-aa2d-479f-849c-30b331d14f02)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/5a98b4fc-6705-49f0-bd7f-e42922213eef)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/5761d6ee-e693-4ea8-bf2d-514fb055cd91)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/c08f13bb-bc99-42a3-95d4-c28196294f15)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146966745/dcdebbe9-c575-4642-ad7c-8a024f8fad35)

hope this will help you to understand my issue

**Comment by ignalauret** [comment]
Hey @Hitisha14 thanks for the extra info you provided. I just checked your API calls and all of them are working correctly except for "transfer" that is giving me a 500 Server Error. Please make sure to check your backend for any possible errors in your transfers endpoint, and make sure to test it going to your Api Calls -> Response & Test -> Test Api Call. <br>Have a great day!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, thanks!
