### ISSUE TITLE
Desktop app not syncing with updates made to the web even after 5 minutes

### ISSUE THREAD

**Issue by vidy01** [FlutterFlow/flutterflow-issues#2641]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I make an update to the web app. Then I try to use the desktop app so that I can test on my device. Even after five minutes, the desktop app still has older updates and not the newer updates. It does not sync.

This has been a problem in the past and I have lost a lot of changes. Some changes are in the new web version, and some changes remain on the desktop version and then I have to go back to snapshots and manually copy each and every change. This is extremely frustrating. 

Based on the conversation with one of the support specialists it must have been an issue with the Mac app, not updating the latest version. That also seems to be an issue. There is no way to find out.

### Expected Behavior

When I make an update to the web app i expect the  desktop app to be in sync. at least within a few minutes.

The desktop app needs to auto update its own version on the macOS.

### Steps to Reproduce

Make an update to your application on the web version.

Then open the desktop app and go to your application. 

The update is missing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlfLl/ot2m+ZE+arqL+5olSgwGUwbUOc7j9VEGAsjCeLnPJkyfcj4ahBBYuqHeWNiP1GLkk800P/IvfzPD8c4IQitfYhj/6pTUxDjcHutaJC6CJaoWnBfM/9Wfkyu0MGzuhFAJtFZWUYD7znyN9yAb3qCf9qOYwx5e6fDbOY=

### Context

The issue has affected me and made me lose at least two days of time and reworking because on the desktop app I started working on a different part of the application so I did not notice the lack of sync.

### Visual documentation

![Screenshot 2024-04-02 at 12 36 26 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/156584074/bf98a0b2-c129-409f-a3b2-a2ae538122d2)
![Screenshot 2024-04-02 at 12 36 20 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/156584074/6d429b12-bd73-4cda-a3ec-f8d087eb46b4)

as you can see the text box in the desktop has an underline and the webversion has a outline.

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: macos
- Browser name and version: Arc
- Operating system and version affected: MAcOS 4.1.35
```

**Comment by ignalauret** [comment]
Hey @vidy01 thanks for your report. The team will check why we are experiencing some delays on the updates between web and desktop and keep you updated on this thread.
Have a great day.

**Comment by Franco98404** [comment]
I have the same problem

**Comment by JoaquinMendoza28** [comment]
same problem here

**Comment by ImadBouirmane** [comment]
Yeah same problem also on **Windows Desktop App** 
Its serious issue need to be resolve especially for Windows users like me we prefer to use Desktop than Web the big different of performance.

**Comment by sabatage3** [comment]
I'm experiencing the same issue. It has been ongoing for 2 days now. When I access it from the web and from the Windows app, I see different versions of my app. It's not syncing at all

**Comment by captainjdi** [comment]
I'm seeing the same thing. In addition, I get "Aw Snap" crashing errors in the web (unrelated to this issue), but not being able to sync is slowing me down tremendously.

**Comment by gsleininger** [comment]
It happened to me too. The MacOS app opened a very old version of my app. It did not grab the latest version from the web version where I had been making updates. This is a serious error. Once you close the desktop app then go back to the web version, the old copy of the app then opens in the web version so you lose all that work. Then you have to find the right snapshot to revert back to.

**Comment by isegal** [comment]
@agreaves 

Try adding this in the beginning of main.dart right after firestore initialization:

```
  await initFirebase();
  FirebaseFirestore.instance.clearPersistence(); // <-- add this line.
```
This way when the desktop app launches it would pull the latest firestore state insteaf of potentially stale one from the cache.


We've observed in our own app that the native flutter builds of firestore prefer to cache a lot more than our web counterparts and it often happens transparently. If an app has been offline for a while and it is brought back online, it tries to catch up, but there is no easy way to globally determine whether the cache state is caught up. Offline persistence also tends to show stale data to users without them knowing.

Additionally we also limit our firestore cache as we've had performance issues in the past as the cache became too big.

Eg, to limit to 1mb, at the beginning of main.dart one could do:
```
  FirebaseFirestore.instance.settings = Settings(
    persistenceEnabled: true,
    cacheSizeBytes: 1 * 1024 * 1024,
  );
```

Caveats:
Clearing and/or limiting cache has a potentially impactful trade-off as it can increase the loading time and the amount of reads performed by Firestore (impacting your google cloud bill). In our case we didn't find a better solution and preferred this tradeoff over having to worry about recurring regressions.

**Comment by Maazkhalid47** [comment]
I have been trying to beat this by opening and closing flutterflow desktop app atleast 3 three times, to force sync it with the changes made on the browser version. But its not the same case when I save the work on the desktop app, it used to sync changes right away on the browser version but now saving on the desktop app or refreshing the browser on doesnt do anything.
