### ISSUE TITLE
Snack bar does not show in a bottom sheet (z-index issue)

### ISSUE THREAD

**Issue by mixart** [FlutterFlow/flutterflow-issues#2643]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I launch a snackbar from a bottom-sheet, it displays under the bottom sheet and not on top (so I don't see it unless I close the bottom sheet)

### Expected Behavior

snackbars should behave like alerts and always have the highest z-index.

### Steps to Reproduce

1. create a page
2. create a component for the bottom sheet
3. create a "snack bar" action on the bottom sheet component
4. launch the bottom sheet from the page
5. trigger the snack bar action from the bottom sheet

The snack bar will not appear (it appears under the component)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8sls/l6otPxLhY7c/McPpahSQXQz47ULhE0utuGAwafbLyBIYXe/T4TEpoQte5a1NEDWH8/TsJw/TKhuztBO1cGwWBRoNy/pNTQx7hdz6WManSPJCOfkdBO9tmFVSd0aS3pB5DBNpwd2wt12aPN+yREynbN5SwOlQdH/L9KoPAgXSRAnnRUxBW7xIIIHaaTI5ODEz25eKMrop5yfj/0w==

### Context

I am unable to trigger feedback to a user with an actions they take inside a bottom-sheet. I have had to use alerts and other components to get around it.

### Visual documentation

Project was created to illustrate this bug here:
https://app.flutterflow.io/project/bug-snackbar-on-bottomsheet-brattd?tab=widgetTree&page=HomePage

View the issue in this project: https://app.flutterflow.io/run/LI4VA49NdVJJIQlyQec7

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: all
- Browser name and version: chrome
- Operating system and version affected: Mac OS
```

**Comment by corsaro0** [comment]
+1 I have the same problem

**Comment by ignalauret** [comment]
Hey @mixart thanks for your report. I was able to reproduce your issue and I have elevated a ticket to the engineering team, they will keep you updated on this thread. 
Have a great day.

**Comment by Franco98404** [comment]
The problem also occurs with snack bars when uploading a file

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/bbeb38cb-8440-40f0-830e-fb0f2ee3cb90)

**Comment by leighajarett** [comment]
Hi there! Sorry you're facing this issue. I know it can be frustrating. We have suggested these workarounds: [https://github.com/FlutterFlow/flutterflow-issues/issues/946#issuecomment-1624226756](https://github.com/FlutterFlow/flutterflow-issues/issues/946#issuecomment-1624226756)

Unfortunately we won't be able to fix this issue as this time, as it would require a significant amount of re-architecting on our side
