### ISSUE TITLE
After Flutter update Dropdowns on IOS are Crashing

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#2644]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After updating Flutter in early March, Dropdowns stopped working in my application in many places.
When you open it, the application crashes.
At the same time, this happens only on iOS. Everything works on Android and the Web.

There are identical pages or components - and on one of them the Dropdowns are "broken", on the other - everything is OK. and I didn't find the logic for which Dropdown breaks.

### Expected Behavior

Dropdowns should work!

### Steps to Reproduce

I didnt find pattern, it just happen. Just like big bug with lost translations that I posted and dosens of poeple has it too.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis8GojnPO0ESs+lYldUOOKoT3N+OlmWpDgX/Mr2iYTpLME6OQmqbrk7zaVuWhfxeD6Xb4SrBpS3b0BPJ/tWBUvH1qeniB1SPtR2LmQd2Ez3COevTnTBJ4+yNUdMD+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

App is almost unusable.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/4b23284f-1223-4597-8d86-991877813a34

### Environment

```markdown
- FlutterFlow version: 4.1.35
- Platform: Mac
- Browser name and version: Chrome 123.0.6312.86 (Official Build) (arm64)i
- Operating system and version affected: iOS 17.3.1, iPhone 12 Pro Max
```

**Comment by DevKursat** [comment]
#2547 ...
