### ISSUE TITLE
PCI Compliance

### ISSUE THREAD

**Issue by socialhostpro** [FlutterFlow/flutterflow-issues#2647]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<html>
<body>

#274: PCI Compliance
--
We'll pick up your ticket soon
Submitted28 March | In progress | Resolved

Failed Scan. I need to address this server issues but have no whyt to do it. Please help. 7.80 FAIL 443 TCP www Script Src Integrity Check 5.80 FAIL 443 TCP www HSTS Missing From HTTPS Server (RFC 6797) 4.00 FAIL 443 TCP www SSL/TLS Recommended Cipher Suites (PCI DSS)
Can you please provide a video or screenshot of the issue? This enables the fastest troubleshooting experience.2024-03-28_1988996_11641913_FAIL.pdfProject URL (copy + paste from any page within your project)https://beta.flutterflow.io/project/chef-full-app-ma0g9zDo we have your permission to test this?Yes | Can you please provide a video or screenshot of the issue? This enables the fastest troubleshooting experience. | 2024-03-28_1988996_11641913_FAIL.pdf | Project URL (copy + paste from any page within your project) | https://beta.flutterflow.io/project/chef-full-app-ma0g9z | Do we have your permission to test this? | Yes
Can you please provide a video or screenshot of the issue? This enables the fastest troubleshooting experience. | 2024-03-28_1988996_11641913_FAIL.pdf
Project URL (copy + paste from any page within your project) | https://beta.flutterflow.io/project/chef-full-app-ma0g9z
Do we have your permission to test this? | Yes

</body>
</html>#274: PCI Compliance 
We'll pick up your ticket soon
Submitted
28 March
In progress
Resolved
Failed Scan. I need to address this server issues but have no whyt to do it. Please help. 7.80 FAIL 443 TCP www Script Src Integrity Check 5.80 FAIL 443 TCP www HSTS Missing From HTTPS Server (RFC 6797) 4.00 FAIL 443 TCP www SSL/TLS Recommended Cipher Suites (PCI DSS)
Can you please provide a video or screenshot of the issue? This enables the fastest troubleshooting experience.	[2024-03-28_1988996_11641913_FAIL.pdf](https://flutterflow.intercom-attachments-3.com/i/o/1005367560/30659a7ce1e186c22eeea916/2024-03-28_1988996_11641913_FAIL.pdf)
Project URL (copy + paste from any page within your project)	https://beta.flutterflow.io/project/chef-full-app-ma0g9z
Do we have your permission to test this?	Yes

### Expected Behavior

Pass security scan. This is going to effect everyone that host on your system. 

### Steps to Reproduce

Security Scan chefnicolemiami.com port 443
[2024-03-28_1988996_11641913_FAIL (2).pdf](https://github.com/FlutterFlow/flutterflow-issues/files/14852084/2024-03-28_1988996_11641913_FAIL.2.pdf)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lcr135JgodcB1rrPbfpajic5JjsnRJIe1+pBaCosfZT2BLMcec/RVERWTcO7TFVbfGf8+GoW0fz0iNn1GsFcGEmeG4R91ap+WwL/TlOnWrGYFJWvdXAlM+lRCFPD1KWJ2xNCVdhqcllm2mWABeuQfzDfH4T1PlQSDq/LZO4=

### Context

Cost me 180 a week starting the 23rd if not secured.

### Visual documentation

[2024-03-28_1988996_11641913_FAIL (2).pdf](https://github.com/FlutterFlow/flutterflow-issues/files/14852097/2024-03-28_1988996_11641913_FAIL.2.pdf)

### Environment

```markdown
FlutterFlow version: I made with the Beta FF (Work on everyday so current version)
Platform (e.g. Web, MacOS Desktop): All
Browser name and version (web): Chrome 35.145.8.98
Operating system and version (desktop): Windows 11
```

**Comment by takashiff** [comment]
Hi @socialhostpro, thanks for the bug report. What type of payment methods are you using when charging users? This most likely has a relation with PCI compliance. The built-in packages in FF for payments (i.e. Stripe, Razorpay) are PCI compliant, so I would suggest using those if the current payment handler you are using is not compliant. Thanks
