### ISSUE TITLE
Firebase data loading error on Android

### ISSUE THREAD

**Issue by MaelissPA** [FlutterFlow/flutterflow-issues#2648]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've deployed the application on IOS and Android. But on the latter platform, I have a recurring problem with the data coming from Firebase. 
There's often a bug in the synchronization of new data from the database (for example, a new document added to a collection). 

I've tried to stream all queries, but nothing works, the bug always appears. I haven't figured out what's clearly triggering it. My hypothesis is that there's a loss of connection to the database or to the device cache (I haven't set it up). 

### Expected Behavior

Automatic data update from firebase (as on IOS)

### Steps to Reproduce

1. Use a collection from firestore 
2. Use a stream component 
3. Release an Android version (I couldn't reproduce it in run version)
4. Launch the application 
5. Wait a while (this can range from a few hours to several days)
5. Add document to firestore collection 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfi8mAsIpgrsNc7q6Jb+xF/CgsKVscTIAFkuwacy8YGIytBu0IY8/sZVpuOdziaVNcPGGJnk4Dp/uLhdr9FsIpHEyaboR9+s5ybArOe2iXM77TPbjpVn9QBcZMCnKC37bQqxFdBO9aSiBl20OmNu+ya3XDBOu/Zwh9f6PHaOI=

### Context

The Android version is unusable as it is, the user has to disconnect/reconnect to correct the bug. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/161008323/e226644c-c705-43b8-9be0-8e11520ea1b2

### Additional Info

The only solution I've found that fixes the bug temporarily is for the user to log out and then log back in to the application. 

### Environment

```markdown
- FlutterFlow version: 4.1 (released April 2, 2024)
- Platform: Android
```

**Comment by ignalauret** [comment]
Hey @MaerlissPA thanks for your report! As you may expect, it's pretty difficult for us to replicate your issue. You could give me a better idea by answering a couple of questions: 

* After you add the document to the collection and it doesn't appear in the app (the bug), does closing the app and opening it back again make it appear?
* When you say wait a while, you mean with the app open? 

If you give us more info about your problem, we can maybe come our with a solution. 
Have a great day.

**Comment by MaelissPA** [comment]
Hey 
Thanks for your reply. Even if I close the application and open it, it doesn't solve the problem. The only solution is to disconnect/reconnect from the app. 

About the waiting, not necessarily. The application can be open in the background or completely closed.

**Comment by MaelissPA** [comment]
Hey, 
By keeping the app running for over an hour in debug and verbose mode, I managed to find the error, I think. From what I understand, the token expired on its own without refreshing it or disconnecting the user. 

`[ +192 ms] W/Firestore(22134): (24.10.1) [FirestoreCallCredentials]: Failed to get auth token: com.google.firebase.FirebaseException: An internal error has occurred. [ Requests to
this API securetoken.googleapis.com method google.identity.securetoken.v1.SecureToken.GrantToken are blocked. ].
[  +16 ms] W/Firestore(22134): (24.10.1) [WatchStream]: (6a035bf) Stream closed with status: Status{code=UNAUTHENTICATED, description=null,
cause=com.google.firebase.FirebaseException: An internal error has occurred. [ Requests to this API securetoken.googleapis.com method
google.identity.securetoken.v1.SecureToken.GrantToken are blocked. ]`

Maybe on IOS, there's an automatic mechanism? Also, I'm getting an error on app check (which I haven't activated): 
`[  +34 ms] W/LocalRequestInterceptor(30334): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider
installed.`


Could it be coming from there too? 

Thanks in advance!

**Comment by ignalauret** [comment]
Thanks for the info, the error message is really helpful. This seems to be an issue in your configuration, and sadly I can't access to check it out. Please try some of the best solutions I could find: <br>[https://stackoverflow.com/questions/48164248/bad-requests-in-token-service-api-when-using-firebase-auth](https://stackoverflow.com/questions/48164248/bad-requests-in-token-service-api-when-using-firebase-auth)<br>[https://stackoverflow.com/questions/70655155/firebase-auth-sdk-cannot-refresh-token-to-maintain-logged-in-status](https://stackoverflow.com/questions/70655155/firebase-auth-sdk-cannot-refresh-token-to-maintain-logged-in-status)<br>And if you have questions about how to implement it, our Customer Service can give you a better help than me.<br>Good luck!

**Comment by MaelissPA** [comment]
After further research, I realized that the problem came from the API authorizations where oken Service API was not selected 😅
