### ISSUE TITLE
Custom Widget Doesn't Show up in UI

### ISSUE THREAD

**Issue by atashkent** [FlutterFlow/flutterflow-issues#2649]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a custom text widget based on this package fast_rich_text: ^0.0.1 here ub.dev/packages/fast_rich_text. The widget compiled alright and works in preview and when I test run the app but it does not show up when you add it to the page. You get the container and all the values are there when you check the code but they simply do not render in UI.

The widget code:

`// Automatic FlutterFlow imports
import '/backend/sqlite/sqlite_manager.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:fast_rich_text/fast_rich_text.dart';

class FormattedText extends StatefulWidget {
  const FormattedText({
    super.key,
    this.width,
    this.height,
    this.tildeColor,
    this.caretColor,
    this.hashColor,
    required this.text,
    this.tildeSize,
    this.caretSize,
    this.hashSize,
    this.textColor,
  });

  final double? width;
  final double? height;
  final Color? tildeColor;
  final Color? caretColor;
  final Color? hashColor;
  final String text;
  final double? tildeSize;
  final double? caretSize;
  final double? hashSize;
  final Color? textColor;

  @override
  State<FormattedText> createState() => _FormattedTextState();
}

class _FormattedTextState extends State<FormattedText> {
  @override
  Widget build(BuildContext context) {
    return FastRichText(
      text: widget.text,
      useCustomParseSymbolsOnly: true,
      customSymbols: [
        SymbolParams(
          symbolCharacter: '~',
          style: TextStyle(
            color: widget.tildeColor,
            fontSize: widget.tildeSize,
            fontWeight: FontWeight.bold, // Make text bold
          ),
        ),
        SymbolParams(
          symbolCharacter: '^',
          style: TextStyle(
            color: widget.caretColor,
            fontSize: widget.caretSize,
            fontWeight: FontWeight.bold, // Make text bold
          ),
        ),
        SymbolParams(
          symbolCharacter: '#',
          style: TextStyle(
            color: widget.hashColor,
            fontSize: widget.hashSize,
            fontWeight: FontWeight.bold, // Make text bold
          ),
        )
      ],
      textStyle: TextStyle(
        color: widget.textColor,
      ),
    );
  }
}`

### Expected Behavior

I would explect to be able to see the widget and its contents. I would also appreciate if height and width were not required and the widget could take up the space provided by the parent.

### Steps to Reproduce

1. Create a custom widget using the code in the description.
2. Compile the widget.
3. Add it to the page.
4. Pass some text in the text field (or type in).
5. Pick the color for the text.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMr6w5dPxMtD+KXidcBvhio5KUc4U78/m8B7aCsofePrOpkAf8/7UFtUOcTgTQlqJlr9iT4X/MrpvtjtGsddZBKef4RyyKtIZxX/ZFmmeLKqCK63b3R6J9hgChSByqWvgAp5HNduWE4k1F6meuusSgzUK6bAOjM3AeaeXdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to format different pieces of the text in the text string differently using tags.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/93946585/6edda8f5-6e1b-4838-81a0-d2427692af7b

### Environment

```markdown
- FlutterFlow version: v.4.1
- Platform: MacOS Desctop (Windows behaves the same way)
- Browser name and version: Chrome Version 123.0.6312.87 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.4.1
```

**Comment by atashkent** [comment]
Btw. If you hardcode the text in the widget code then it shows up.

**Comment by ignalauret** [comment]
Hey @atashkent thanks for your report. I can see that the custom widget is appearing correctly on your video. Keep in mind that the Custom Widgets will only render when you run the app. 
Also, if you don't want to specify the height and width, you can uncheck the "Enforce Width and Height" checkbox at the bottom of the Custom Widget editor on the right panel. 
Have a great day.

**Comment by atashkent** [comment]
It would be awesome and so much easier and convenient to manage the layout if it actually showed up. Thank you.

**Comment by ignalauret** [comment]
Yes you are right! I will add it as a feature request to our engineering team. Thanks for the report.

**Comment by atashkent** [comment]
One more thing that deserves attention of the engineering team is that when you uncheck "Enforce width and height" and you don't define height of the custom widget, Flutterflow still recognizes it as an error and prevents you from running tests and compiling other widgets (as a result of unresolved errors). And when your widget content is variable (as with text), you definitely don't want to define height.

**Comment by leighajarett** [comment]
Great feedback, thanks sooo much!
