### ISSUE TITLE
Icon Color in ListTile set from conditional doesn't emit code.

### ISSUE THREAD

**Issue by crioux** [FlutterFlow/flutterflow-issues#265]
## Expected behavior (required)
Putting some conditions in the 'Icon Color' field of a ListTile to change the color of a tile based on the item data should emit the code for the color field.

## Current behavior (required)
The color setting dart code does not show up in the generated output.

## To Reproduce (required)

1. Create new page
2. Add a ListTile
3. Add a Leading Icon to the ListTile
4. Set the Icon Color to a conditional, with the condition as 'Is iOS' (or anything else), with the true case to be a color and the false case to be another color
5. Confirm
6. View the code for the page

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/819652/209222748-5ea01581-4cfb-4ca7-89a5-c96e3e3ebbb3.png)
![image](https://user-images.githubusercontent.com/819652/209222801-1ed1868c-cbcb-4387-b048-8d3fe2e5c4f7.png)
![image](https://user-images.githubusercontent.com/819652/209222818-115232da-465e-4e70-b921-3846bb0b963c.png)

## Your environment

* Version of FlutterFlow used: v3.0 12/22/2022
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome/latest
* Operating system and version (desktop or mobile): MacOS Monterey 12.6

## Bug code
IT4szfHl5YxNodxE7c/QccdB/ScXHDsgU5I0scp8WQgafIjLP4k+Y/WkcVpvXc+iYH9LfESmmlIHzP/Hjd/fLMdfPTScf48++Kl+eArNUmWXU8HfU/HUACkbeacOQSj6

**Comment by hariprasadms** [comment]
HI @crioux - I have tested this issue as per the steps you have described and I can see code is generated the code correctly. 

Is this still not working for you?. Refresh ( Ctrl+R) your web page and see if that can help you.

 
![image](https://user-images.githubusercontent.com/17435678/209368630-5af7ca04-e6b2-41aa-a682-04743f5ae3d6.png)

**Comment by crioux** [comment]
I reloaded. Still doesn't generate for me. My code right now uses a jsonpath, with a parameter from the component.

![image](https://user-images.githubusercontent.com/819652/209415748-5c22c0e5-ea05-402e-b3b7-e208087dfc88.png)
![image](https://user-images.githubusercontent.com/819652/209415750-14fe069c-d90f-4440-a8f4-d1c0cfccb440.png)

note the lack of code on the 'leading' icon:

![image](https://user-images.githubusercontent.com/819652/209415821-e0017950-9135-41ad-916f-d823b0d44a9b.png)

**Comment by agreaves** [comment]
Thanks @crioux for catching yet another bug! This will be fixed upon our next release 🙂.
