### ISSUE TITLE
Deployment to App Store / GPS sits in QUEUED for hours / days

### ISSUE THREAD

**Issue by xenomorph78** [FlutterFlow/flutterflow-issues#2651]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When submitting mobile deployment, it appears code magic is overwhelmed most of the time. Many users are reporting hours and days of 'queued' status. This is not sustainable development conditions.

### Expected Behavior

The deployment process would normally take 15 mins or so. Now, it's taking 6 to 20 hours to complete.

### Steps to Reproduce

1. Attempt to deploy an app.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhfHlzItOodtc0L6IKvp4imQ7KUMcTIMziNZ+exUbfaL1Bu0pdc/eUxZtcO28aVNcDWCb+XExp9aPiIbpFPIBAy2Zb747ycxyZjv0e2iiRpubCpaKWH96M+1MfEfF36bUrQpQXdF2ZVYDw3GmO+vKfDPDIuu/Zwh9f6PHaOI=

### Context

It's not feasible to use Flutter Flow in these conditions and test every other day. We need to be able to deploy and test the deployment within minutes.

### Visual documentation

![Screenshot 2024-04-03 at 8 48 56 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/74033405/b7a76270-d0de-4762-9206-e6ced787b042)

### Environment

```markdown
- FlutterFlow version: 4.1.34 
- Platform: Flutter Flow desktop for Mac
- Browser name and version: Chrome latest
- Operating system and version affected: Mac OS Sonoma 14.4
```

**Comment by leighajarett** [comment]
Thanks for filing this issue. Unfortunately this seems to be a delay that is outside of our control (happening on CodeMagic / AppStore Connect). Could you try making sure your configuration is setup correctly or contact their support? Thanks!
