### ISSUE TITLE
Merge function not working as it should, deleting Branch edits and worse

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#2652]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Two controlled experiment were run.

Experiment one.

1. Branch was merged into main
2. There was one conflict which involved an Action that had been changed on main. 
3. The main branch was selected as the truth. 
4. The issues were resoled
5. The merge took place
6. The main appeared to have got the edits form the branch
7. HOWEVER the branch inherited much (but not all) of the main edit, undoing about 24 hour work on the branch.

Experiment two.

1. Both the branch and main were reverted back to earlier versions so that the branch edits were restored, and not trusting the merge in the last test, so was the main
2. I deliberately changed a text field in main from "Trending Now" to "Trending Nowx"
3. We invoked the same merge from branch to main as above.
4. We got the same conflict on an Action, but this time we decided to accept the branch's version. 
5. The conflicts were resolved and the merge took place.
6. On inspection of the "Trending Nowx" field in the main, it had reverted to "Trending Now".

### Expected Behavior

1. That under no circumstances should a merge alter the edits in the branch. Only in the main.
2. That unless an edit is marked as a conflict, as in the change to the text field, the edit in the main should remain intact. 

### Steps to Reproduce

Tricky without tampering with  live project. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7l3WvfObhJUcN/mYXNiImL9nmQX/Mrzvt/DKO1fOTWBGIhJz5ZMURfgIWaRaaqhC663b3dAFppTfUicyKu3qhNCCNheWFoswziIBumuZA3DQJjQDEQzMOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Productivity. Rather than organize our team, it has thrown us into chaos!

### Visual documentation

xxx

### Additional Info

xxx

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Windows and online 
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by leighajarett** [comment]
So sorry you're running into this issue, and thanks for flagging! Would you be able to tell use which merge this was in your project so we can look into it further?

Specifically a screenshot of the merge history tab with the merge in question highlights, or the date + branch name that you merged into main.

Thank you sooo much, and once again we're really sorry!

**Comment by leighajarett** [comment]
Going to close this issue since we haven't heard from you. Please create a new issue if this persists!
