### ISSUE TITLE
Adding a parameter that is a custom data to a page results in compile failure

### ISSUE THREAD

**Issue by RickAtSavveLabs** [FlutterFlow/flutterflow-issues#2654]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Created new page in project. In that page, I added a parameter which is one of my custom data types. When starting a test run, just before compilation is done, I get a compilation error. When I delete the parameter, the test run is fine. If I add a parameter which is a standard type such as String or ImagePath, it compiles just fine. Note that the custom data types are valid are being used throughout the rest of the app.
![Screenshot of Safari at Apr 3, 2024 at 6_03_32 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/6e3020ec-83e0-429c-be60-519b4b27b81a)

### Expected Behavior

Compilation should complete just fine and the app should run.

### Steps to Reproduce

1. Add a new page to the project
2. Add a parameter
3. Define it to be a DataType and select a non-standard type that you define
4. Start a test run
5. Compilation then fails

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfLq0812pbxH1rr+bMB7/ToRHFw1bbgescp/bxIgGIDzPOw+ZPXsUBBtTde+Y0FqekSmmmAEwsHIhuOSU8c4OT+bbYM7z8x6TjvjQmaXQZOBBbqgSkR8BfxbFUfD5rS32xJvNuNodEY/2UOAHdiXXi/qQpy2IlFISq/LZO4=

### Context

I wish to show the details of a data type on a page.

### Visual documentation

![Screenshot of Safari at Apr 3, 2024 at 6_03_32 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/ae3dd070-9543-4cb3-88ad-79dc926d8765)

### Environment

```markdown
- FlutterFlow version: 4.1.35
- Platform:MacOS app
- Browser name and version:Safari 17.4.1
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by paul-dec** [comment]
<img width="924" alt="Capture d’écran 2024-04-04 à 03 36 48" src="https://github.com/FlutterFlow/flutterflow-issues/assets/33022684/3b31ee6f-77c5-4494-9d59-6196bb6c53b2">
I have the same issue

**Comment by bozzoleandro** [comment]
Hi @RickAtSavveLabs, thanks for your report, This is a duplicated issue : [https://github.com/FlutterFlow/flutterflow-issues/issues/2702](https://github.com/FlutterFlow/flutterflow-issues/issues/2702), I"m going to close this one!
