### ISSUE TITLE
Customer profile scrolling broken

### ISSUE THREAD

**Issue by jaggederest** [FlutterFlow/flutterflow-issues#2655]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When initially logging into FlutterFlow for the first time, there is a customer profile survey that shows up. It asks questions about position in the company etc.

If you select the "other" option about where you found FlutterFlow, the "complete" button is pushed down off the page and cannot be clicked.

### Expected Behavior

I expect to either be able to scroll the customer profile or not have it move such that the button is unclickable

### Steps to Reproduce

1. Sign up to FlutterFlow with a new email address
2. The customer profile will be displayed
3. Select options that cause the confirm button to move past the end of the page
4. You cannot click on the confirm button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40js/qx89gochE18/+bcBFtDw5JW56aK8R0et7aDYvCIyqOph/Yc6lT1VVZ7HjYWlhHFCGpFoK/sLevtrmFfI4OSWVb6Jg1LV+FgzMXXq8RrayCKieWURAQN5XFXae3JmzoiJCHPpaWE4s2mb6NueQZAXdN5+/Zwh9f6PHaOI=

### Context

I was trying to fill out the customer profile

### Visual documentation

None available

### Environment

```markdown
- FlutterFlow version: Current as of Apr 3 2024
- Platform: Mac OS arm64
- Browser name and version: Chrome 123.0.6312.59 (Official Build) (arm64)
- Operating system and version affected: Mac OS
```

**Comment by paul-dec** [comment]
<img width="924" alt="Capture d’écran 2024-04-04 à 03 35 58" src="https://github.com/FlutterFlow/flutterflow-issues/assets/33022684/2facca4a-3968-47b2-a30e-2e6d215a39f7">

I have the same problem

**Comment by ignalauret** [comment]
Hey @jaggederest thanks for your report. I was able to replicate the bug so now the Engineering team will take care of it.
Have a great day.
