### ISSUE TITLE
Web Audio Recording no longer works

### ISSUE THREAD

**Issue by kwkrass** [FlutterFlow/flutterflow-issues#2659]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i use the Action "Stop Audio Recording" on Web it does not work. It throws a "platform not supported" error in the console

### Expected Behavior

It should work. It worked before.

### Steps to Reproduce

1. Stop Audio Recording Action on button
2. Press Button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si/Hl249gobxc1pPqb8Br/So7HEA9ap0wscsZa0kdB4joPLJ/PuOkfhRvcMCqd0NhHFL9pF8H+anJudnpOPFfCxGYRrpP1qlQUhfhc3q8SqaxDKiwX2pRI9xXIGKs17SZoxFdPs12LEYM3E62Nu/JaBbfJ5+/Zwh9f6PHaOI=

### Context

For this app here: [https://medimentor.alldone.app/](https://medimentor.alldone.app/) - doctors can record their patient discussions but it no longer works on the web

### Visual documentation

![Bildschirmfoto 2024-04-04 um 12 27 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/796118e6-8409-4100-8599-cb1683f3acbe/8e0ca736-57b7-4d3b-92cd-612464ea847a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83OTYxMThlNi04NDA5LTQxMDAtODU5OS1jYjE2ODNmM2FjYmUvOGUwY2E3MzYtNTdiNy00ZDNiLTkyY2QtNjEyNDY0ZWE4NDdhIiwiaWF0IjoxNzEyMjQ1NTY4LCJleHAiOjMzMjgyODA1NTY4fQ.lhZufh2grQwMqK7Fgl-bz9UGzsxgXuU6cFyOZZOH_go)

Here a screenshot

### Additional Info

![Bildschirmfoto 2024-04-04 um 12 27 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/de6d3eed-a4c4-4f33-8a33-5649e8008134/9a888728-87a2-471a-aafc-0bec9aa960b3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZTZkM2VlZC1hNGM0LTRmMzMtOGEzMy01NjQ5ZTgwMDgxMzQvOWE4ODg3MjgtODdhMi00NzFhLWFhZmMtMGJlYzlhYTk2MGIzIiwiaWF0IjoxNzEyMjQ1NTY4LCJleHAiOjMzMjgyODA1NTY4fQ.Mfz9WQRuwrrPZswZVFBrJyIpyYbrsIz-Nv84P98r5C8)

### Environment

```markdown
FlutterFlow v4.1 released April 2, 2024
Flutter version is 3.19.1
 
medi-mentor-s6bkps
 
On a Mac with Chrome
```

**Comment by gentleVirus** [comment]
Same problem here.

I use audio messages in a chat and just tested it two days ago because there is also a problem with showing the audio player for iPhones in PWAs. Even though the audio file exists, the player just do not show up.

Anyways, for android it worked two days ago. Now, I checked the backend, the audio file is not even being created.

**Comment by ignalauret** [comment]
Hey @kwkrass thanks for your report! Sadly I can't test your web application following the steps that you mention. I've just created a blank project with a record and a stop button, and they are working correctly when I deploy them to web. Could you please try to replicate your issue from a blank project so I can test it? 
Also, are you sure that the Platform error is being thrown by the stopRecord function, and not by another of you custom or firebase functions?

**Comment by kwkrass** [comment]
Thanks for checking. Indeed it does work again.
Weird I swear it wasnt working yesterday .... looks like something has been updated somehow :) 

But great this is working again.

**Comment by ignalauret** [comment]
I'm glad your project is working again. Good luck!
