### ISSUE TITLE
Leading Icon 'set from variable' can't be used because variables can not be of Icon type

### ISSUE THREAD

**Issue by crioux** [FlutterFlow/flutterflow-issues#266]
## Expected behavior (required)
There should be a way to set a variable to have Icon type and return an Icon from a custom function or action or conditional

## Current behavior (required)
You can specify a Leading Icon on a ListView (or any other Icon field) as 'Set from Variable', but there's no way to make a variable of Icon type or return one from anything.

## To Reproduce (required)
Try to make an icon and set it from a variable. Or anything.

### Bug Report Code
IT4szfHl5YxNodxE7c/QccdB/ScXHDsgU5I0scp8WQgafIjLP4k+Y/WkcVpvXc+iYH9LfESmmlIHzP/Hjd/fLMdfPTScf48++Kl+eArNUmWXU8HfU/HUACkbeacOQSj6

## Context (required)
Trying to customize icons in a ListTile

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/819652/209227242-ca459ac3-09f3-43e5-aed1-906890a09c34.png)
valid return types from functions:
![image](https://user-images.githubusercontent.com/819652/209227309-45580272-1c4e-4c75-979c-0913debe8482.png)
local state field types:
![image](https://user-images.githubusercontent.com/819652/209227372-7b7b510e-ad9f-4184-8b9c-1debba46fd2d.png)

None of these are icons. 

## Your environment

* Version of FlutterFlow used: 3.0 December 22,2022
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: Chrome latest
* Operating system and version (desktop or mobile): Macos Monterey 12.6

**Comment by agreaves** [comment]
Hi @crioux, thank you for the feedback. I'm closing this as a feature request for now, but it's a great suggestion that we'll definitely consider adding in the near future!
