### ISSUE TITLE
Git Hub Auto Assign Fails

### ISSUE THREAD

**Issue by gentleVirus** [FlutterFlow/flutterflow-issues#2661]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Git Hub Auto Assign failed for me three times when I opened a new issue and I heard from others they are facing the same problem.

### Expected Behavior

Ever issue should successfully auto assign.

### Steps to Reproduce

Open a new issue.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejMrlvJNPj7xH+c/+c/lvrwMwJ0QlUIInj+0bWRMhfa3kB7QIeM/OdlRLYteFS39YBlmiknEHwvTpvuzlFvVfNRCafbpD/75XQQvvWnyRacWUDc6BOUYmN9hgCn3G36anhBV4ItdoSlo/3E+QfvCrG3qCf9qOYwx5e6fDbOY=

### Context

I don't know if this is the right place, as it is not a bug directly in flutterflow itself...
...but this bug seems to significantly increase the time until someone takes a look at your issue.

### Visual documentation

![autoassignBug](https://github.com/FlutterFlow/flutterflow-issues/assets/141834860/8163bca2-aa54-4654-a01d-d332e2e425ea)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by leighajarett** [comment]
Thanks for flagging! I've removed auto-assign so should be all good now
