### ISSUE TITLE
API Call Headers on FF for Windows Bug

### ISSUE THREAD

**Issue by pedr0h3nrique** [FlutterFlow/flutterflow-issues#2662]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to add headers to an API call in the FlutterFlow for Windows version, an alert appears saying that the fields are empty. In the same way, when I fill in a field and click on "+ Add Header", the filled field is deleted.

### Expected Behavior

When filling in the Header fields and clicking "Save", they should be saved. Just as, when filling in a field and clicking on "+ Add Header", the filled field should remain filled.

### Steps to Reproduce

1 Create an API Call
2 In "Additional Headers" fill in the first field
3 Click  the button "+ Add Header"
4 Fill in the second field
5 Click the button "Save"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/sorotrack-6e83qj?tab=apiConfig

### Context

I need to add Headres to my API calls so that it interacts correctly with my API that is being consumed in my application. If I cannot add these Headers, it will not be possible to use the API in my application.

### Visual documentation

![headers_issue](https://github.com/FlutterFlow/flutterflow-issues/assets/88064292/ffa0388b-8a00-4ad5-8b5a-2fb4db64a955)
![headers_issue2](https://github.com/FlutterFlow/flutterflow-issues/assets/88064292/e0801ad9-6590-4dfa-9ac0-a2a5997685a2)

### Environment

```markdown
- FlutterFlow version: v4.1.34+
- Platform: Windows Desktop
- Browser name and version:
- Operating system and version affected:
```

**Comment by pedr0h3nrique** [comment]
Solved!

**Comment by ignalauret** [comment]
Hey @pedr0h3nrique thanks for your report! I'm glad you were able to solve your problem. If you can paste your solution here it may be really helpful for anyone else that is having the same issue. 
Have a great day.

**Comment by capobecchino** [comment]
Today I still have the problem :( 

FlutterFlow v4.1.40 released April 21, 2024
Flutter version is 3.19.1

<img width="960" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1029470/cfb4b763-5bdb-4754-9ab4-d0e1323c8dd1">

**Comment by pedr0h3nrique** [comment]
I'm using the FF for Window, so I just updated the app and this bug disappeared.

**Comment by pedr0h3nrique** [comment]
This issue again.
FlutterFlow v4.1.41 released April 21, 2024
Flutter version is 3.19.1

![ffissue](https://github.com/FlutterFlow/flutterflow-issues/assets/88064292/847ebc09-ab06-4e36-b764-3495e8271d92)
