### ISSUE TITLE
Automated Tests: Find By Tooltip is not exported in code

### ISSUE THREAD

**Issue by pdamariana** [FlutterFlow/flutterflow-issues#2663]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When working with Automated Tests: when making an _Interact with Widget_ action I then try to Select Widget: **Find By Tooltip** in console seems to be ok. 
But when I export the code to my local through FlutterFlow CLI, this action is not being properly exported. A conflict appears because a parameter is missing in tap method:
`await tester.tap();`

**Automated Tests Console:**
![Screenshot 2024-04-04 at 11 22 45 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/157371619/de39fb8b-c27d-4574-a1eb-956520072a22)

**Exported Code:**
![Screenshot 2024-04-04 at 11 23 05 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/157371619/37e818c1-6114-4e34-866e-8903c41f1efc)

### Expected Behavior

When exporting tests to local code, this line `await tester.tap();` must contain the right parameter. In my example: `find.byTooltip("tooltip-example")`

**Expected:**
![Screenshot 2024-04-04 at 11 28 57 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/157371619/c41b7fe2-7cb7-4a32-8c9e-2d11fadb208f)

### Steps to Reproduce

1. Go to Automated Tests
2. Create new Test
3. Add a Step: _Interact with Widget_ and select _Tap_
4. _Select Widget: Find by Tooltip_ and enter your tooltip text
5. Save test
6. Export code using Flutterflow CLI

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClPHq25N1xd9Y+Kr2asJVmiURNlw1RYIKm9VtdwgYDZPTC7N/PPWkZRJCUsu9Sgl+MUSmmnEy+sqKieHXDcY6OSSrbLpj/5BubA/gQlyWa5OBOrW0OnFBHdxRClSg5LWj3RBBBOlZL2Rk606yf+uudDLtNozxImdISq/LZO4=

### Context

The exported code has a code conflict. 

### Visual documentation

![Screenshot 2024-04-04 at 11 22 45 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/157371619/e511a114-2934-4e55-9027-123565539821)

![Screenshot 2024-04-04 at 11 23 05 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/157371619/7a93121a-e767-4f8c-97a1-a80871afdb13)

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: MacOS Desktop
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by ignalauret** [comment]
Hey @pdamariana thanks for your report. I was able to replicate the bug with the generated code on a blank project, so now our engineering team will take care of it and keep you updated on this thread. 

Have a great day!

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @ignalauret. Unfortunately we can't make it work at the moment because we use `aligned_tooltip` rather than the standard Flutter tooltip. We'll remove the option to find a widget by tooltip in the upcoming update.
