### ISSUE TITLE
Flutterflow version out of Date - Desktop

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2667]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A new version of flutterflow desktop was released and i got a notification to update. I just downloaded the new version and installed. Now when i open the project, i see this pop up which does not go away. This forces me to use the browser version again.
It tells to refresh the page. But i am on desktop version. Is in it helpful that the software downloads and updates itself rather than download and reinstalling the applicatio

![Screenshot 2024-04-05 at 08 12 37](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e09c2b66-1fc8-4049-aa2f-e9822ea0bc55/f134c773-b2e8-424a-a355-2e3634277a0d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMDljMmI2Ni0xZmM4LTQwNDktYWEyZi1lOTgyMmVhMGJjNTUvZjEzNGM3NzMtYjJlOC00MjRhLWEzNTUtMmUzNjM0Mjc3YTBkIiwiaWF0IjoxNzEyMzM0MzY1LCJleHAiOjMzMjgyODk0MzY1fQ.-x3M8g4r7BXXCgyDUvhUeUqVH73meI6k1cSRbfM7SHA)

n

### Expected Behavior

Software should get downloaded and update itself and restart when needed.

### Steps to Reproduce

1. Use the flutterflow desktop
2. You will receive a pop up stating new version of flutterflow is available.
3. The link will take you to flutterflow website to download.
4. You download the software and install.
5. Open flutterflow again and you will see a popup mentioned in the description above.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlPLlvJV2otxE15DuY8BFmjoRMjs3bI0k0+xuZCs8GZT0B4kcYs+kfklUON/nTwlieFqjmj0X/MrRi9/xGME4IQerbb5G/rV+UxXgXk2RVJfSCpS3b3d5EftRJkixy7e7pxMnBPhecV4N2zv7DOfLfHXDQpjBDDInA+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

Working on desktop version and does not allow me to proceed.

### Visual documentation

![Screenshot 2024-04-05 at 08 12 37](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a1e294e0-1c0d-4a67-969c-0cd523e9994f/342b62b7-1e4f-41bc-9ccc-b9983df4f090?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMWUyOTRlMC0xYzBkLTRhNjctOTY5Yy0wY2Q1MjNlOTk5NGYvMzQyYjYyYjctMWU0Zi00MWJjLTljY2MtYjk5ODNkZjRmMDkwIiwiaWF0IjoxNzEyMzM0MzY1LCJleHAiOjMzMjgyODk0MzY1fQ.-wsZ-v46XLN3GtbUEPIOQJnYf01_5i4B5fwZJHiybyY)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by leighajarett** [comment]
Can you please send us the FlutterFlow desktop version number and platform?

**Comment by task-win** [comment]
Hi The flutterflow version is 4.1.35 and platform is Macos

Thank you,
Regards
Srinivas

From: Leigha Jarett ***@***.***>
Date: Friday, 5. April 2024 at 18:26
To: FlutterFlow/flutterflow-issues ***@***.***>
Cc: srinivas sanikommu ***@***.***>, Author ***@***.***>
Subject: Re: [FlutterFlow/flutterflow-issues] Flutterflow version out of Date - Desktop (Issue #2667)

Can you please send us the FlutterFlow desktop version number and platform?

**Comment by airamhany** [comment]
Any update on this issue. I have the same problem. It has been more than 3 days now. This happened when I added a new change on the web version. When I tried to use the desktop app after that, it kept giving me this same message: "FluterFlow o version out of date". I need to use the desktop app to test some changes that I can't on the web. Is there a timeline for when this will be fixed? Thanks

**Comment by task-win** [comment]
I just uninstalled the flutterflow and downloaded the latest from the site and reinstalled. This is a nasty work around.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leighajarett** [comment]
Hi there! The FlutterFlow desktop app should be updating automatically. But, macOS controls the exact timing of when the app updates automatically - which can mean there's a delay between when web gets updated and macOS gets updated. We've just put out a fix that will ask you to press a button to update if macOS is behind web. This should make it easier! That fix should be available in Thursday's release. 

Sorry I know it's super annoying, I've personally dealt with it myself. Hopefully this fix will make it much easier to deal with!

**Comment by airamhany** [comment]
Hey, I still have the same issue. I thought the fix was released last Thursday?

**Comment by leighajarett** [comment]
Hi - this should have been resolved in last Thursdays release. What version are you on? Can you please provide a screenshot of the message you see?

**Comment by airamhany** [comment]
Hi, It seems that I didn't have the latest version. I got it and tested the desktop app and its working. Thank you!
