### ISSUE TITLE
Web package update causing widespread dependency issues

### ISSUE THREAD

**Issue by Gosten** [FlutterFlow/flutterflow-issues#2668]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After yesterday update, I'm not able to compile or run custom code widget.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ba7561b6-a68b-4876-9993-a9c2d0d2f4a8/1a6a6094-f53b-4d16-a445-cca6a0994c72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYTc1NjFiNi1hNjhiLTQ4NzYtOTk5My1hOWMyZDBkMmY0YTgvMWE2YTYwOTQtZjUzYi00ZDE2LWE0NDUtY2NhNmEwOTk0YzcyIiwiaWF0IjoxNzEyMzIxMzg2LCJleHAiOjMzMjgyODgxMzg2fQ.z15wMYSRsZJTnhxlPByb-KzoNlIyDHzwyKZCWBjRHWw)

Widget is based on this pub.dev package:
[https://pub.dev/packages/image_editor_plus](https://pub.dev/packages/image_editor_plus)

and the issue seems to be dependency mismatch after last update.

However, when I download code and run it on VSCode, I get no issues or errors there.

Also, issue happens only when compiling to web. When I deploy local run to mobile, it works fine.

### Expected Behavior

Custom code should be able to compile and run without any errors.

It should behave same way on Flutterflow editor and VSCode

### Steps to Reproduce

1. Create custom code action
2. Add *image_editor_plus* dependency
3. Import:
   `import 'package:image_editor_plus/image_editor_plus.dart';`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XlcjfsIhPsdtJ+KruLcdFmiUvNlwkRYIRltZ+RRQ1F6rkEZoEPOP+T3JdZNPiSnw3PFu0rz4J7srNvfDtUeQHAxyeGqpc+rhuewHzUXGmWrWYPZCeVHFCDexXDkuV5omzrxUmCNpYLHwi7E2yIeuycDHYN5z3Nm4nGMmIKpDJjA+jAhm6Xn0Jg1ZSfCvr

### Context

I'm not able to run multiple apps to test/run mode, because code errors are blocking me

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9fed7aeb-6423-4a18-8875-54621b86f1d7/9a4f9243-0af3-4f5f-9091-735a712e3b59?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZmVkN2FlYi02NDIzLTRhMTgtODg3NS01NDYyMWI4NmYxZDcvOWE0ZjkyNDMtMGFmMy00ZjVmLTkwOTEtNzM1YTcxMmUzYjU5IiwiaWF0IjoxNzEyMzIxMzg2LCJleHAiOjMzMjgyODgxMzg2fQ.8E-Lq8qn9wpfFPBSt7pyaBCloM2JYOq6Focb6jkwIfM)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/48c07a66-65fe-4117-b15a-f9b508ab211f/5245ebb2-cfdf-4ed1-9be7-406d01894433?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80OGMwN2E2Ni02NWZlLTQxMTctYjE1YS1mOWI1MDhhYjIxMWYvNTI0NWViYjItY2ZkZi00ZWQxLTliZTctNDA2ZDAxODk0NDMzIiwiaWF0IjoxNzEyMzIxMzg2LCJleHAiOjMzMjgyODgxMzg2fQ.opgwk6TH5w5MhdkGizvTYMNEbGUZ8PoF20GgbeLAP68)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.36+
- Platform: Windows
- Operating system and version affected: Web
```

**Comment by leighajarett** [comment]
Oh no! That's not good! Thanks so much for flagging, taking a look!

**Comment by wenkaifan0720** [comment]
Hi @Gosten. Sorry for the confusion. We will be reverting the dependency update shortly since we realize that several pub.dev packages haven't been updated to use the latest web package. But if you want to fix the issue right now, you can use these dependencies on your custom widget.
![iScreen Shoter - Google Chrome - 240405105936](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/f18fe734-5501-4f17-b735-fcaa83f1b82b)

**Comment by leighajarett** [comment]
This should be resolved now!
