### ISSUE TITLE
Double field of DataType couldn't set to null

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#2669]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Double field of DataType couldn't set to null even if it specified to null explicitly.
I read [the document](https://docs.flutterflow.io/data-and-backend/custom-data-types), but there is no description about it.

### Expected Behavior

Double field of DataType set to null if it specified to null explicitly.

Whenever it not specified explicitly, I think it works as default as described in bellow.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/d79f89c8-65bc-42d4-8bd0-126ab481b5f9)

If fields in DataTypes must not accept null, Edit UI shouldn't accept null as value.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/68b2a349-bf57-4371-af18-68b39d34f200)

### Steps to Reproduce

1. Create new page
2. Create DataTypes that contains Double field. Stay blank default value and don't touch it.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/f9558eb3-e359-4746-9024-e315e221b4e5)

3. Declare page state of No.2 and another Double(for behaivior comparison)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/88c21231-ff1f-42c8-bfab-698595777c2a)

4. At initial load action, set null to No.3 states.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/d61e3be3-04a7-4f53-9013-726e81fef223)

5. Check they are inited as null using snack bars.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/27b81719-fc7a-4e5f-b8b6-2866f7046af6)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/8852e803-eb9a-4447-b470-6a0fc74d5184)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkufl049PxcMB7qX1bflGoGURQmE4TL07ttYbZxUjIuPtBJh/OuD8ahZVONe+Y1NhHFGJ8Ds0+MqLjeP2V8cnNSedfro+z7hudA2Vc3q8R62YDqmOOnB6QOZXIXab0qSzkQl+GMBhR3gG3GeyOem/aBbcGZ+/Zwh9f6PHaOI=

### Context

- I can't use DataType by state management like interaction with components, dialogs, etc..
- I am not sure about, but it may also affect to API response parsing into DataTypes behavior.
- It looks getter problem setting implicit default (line 43, 50) even if default value wasn't set in DataTypes UI Editor.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/2b4ecc9e-fbbf-4c0b-91c9-bef5aab13128)

- Without It is fixed, whole Firestore data strategy using datatypes as map is required to change .
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/e8c6abbe-5331-4891-a42c-718ff36ecd6f)
 

### Visual documentation

As in "Steps to Reproduce"

### Environment

```markdown
- FlutterFlow version: v4.1 - Flutter 3.19.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by paulperez-dev** [comment]
Hi @ryutosh, thanks for your report! The default value is the value you want the variable to have when reading it if the value was not set. A DataType can support null values and have a default value (or not).

It is expected to be able to set the value of the variable as null.<br><br>Let me know if this makes sense.

**Comment by ryutosh** [comment]
@paulperez-dev 
Yes. I understand the same as you.
Therefore, it is incorrect to evaluated as True at "Is Set" on "Steps to Reproduce #5".

**Comment by paulperez-dev** [comment]
@ryutosh it makes sense, a null value should return false to the condition 'is set'. 

I will pass it on to the team so they can take a look.

**Comment by br0nk** [comment]
Sounds like this behavior is working as intended.  Expected behavior is:

The UI for this can accept a null (or null via omission) as default for double/int numeric fields.

The generated getters will provide a non-nullable double/int and return 0 if the default value is null.

The user can use the generated has<fieldname> methods to check whether those fields had a null default value or were given an explicit default.  Those methods will return false if the default value was null.
