### ISSUE TITLE
Flutter: Error invalid source release: 17

### ISSUE THREAD

**Issue by guizostudios** [FlutterFlow/flutterflow-issues#2671]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to deploy my project (Metasano) to Play Store but I got an error. For App Store is working well.
The problem is related to android studio being out of date.

### Expected Behavior

Deploy the new version to Play Store

### Steps to Reproduce

1. You can access the project called metasano in my account
2. Open mobile deployment
3. Deploy to Play Store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Step 7 script `Build AAB with Flutter` exited with status code 1

### Context

I can't deploy my project on Play Store

### Visual documentation

Codemagic Deploy Output
Failed Step: Build AAB with Flutter

Resolving dependencies...
  _fe_analyzer_shared 61.0.0 (67.0.0 available)
  _flutterfire_internals 1.3.27 (1.3.28 available)
  analyzer 5.13.0 (6.4.1 available)
  badges 2.0.2 (3.1.2 available)
  chewie 1.7.1 (1.8.1 available)
  cloud_firestore 4.15.10 (4.16.0 available)
  cloud_firestore_platform_interface 6.1.11 (6.1.12 available)
  cloud_firestore_web 3.10.10 (3.11.0 available)
  cloud_functions 4.6.10 (4.7.0 available)
  cloud_functions_platform_interface 5.5.21 (5.5.22 available)
  cloud_functions_web 4.8.1 (4.9.0 available)
  easy_debounce 2.0.1 (2.0.3 available)
  file_picker 6.1.1 (8.0.0+1 available)
  firebase_analytics 10.9.0 (10.10.0 available)
  firebase_analytics_platform_interface 3.10.0 (3.10.1 available)
  firebase_analytics_web 0.5.6 (0.5.7 available)
  firebase_auth 4.18.0 (4.19.0 available)
  firebase_auth_platform_interface 7.2.0 (7.2.1 available)
  firebase_auth_web 5.10.1 (5.11.0 available)
  firebase_core 2.27.2 (2.28.0 available)
  firebase_core_web 2.13.0 (2.14.0 available)
  firebase_messaging 14.7.21 (14.8.0 available)
  firebase_messaging_platform_interface 4.5.29 (4.5.30 available)
  firebase_messaging_web 3.7.1 (3.8.0 available)
  firebase_performance 0.9.3+19 (0.9.4 available)
  firebase_performance_platform_interface 0.1.4+27 (0.1.4+28 available)
  firebase_performance_web 0.1.5 (0.1.6 available)
  firebase_storage 11.6.11 (11.7.0 available)
  firebase_storage_platform_interface 5.1.14 (5.1.15 available)
  firebase_storage_web 3.8.1 (3.9.0 available)
  fl_chart 0.55.0 (0.67.0 available)
  flutter_animate 4.1.1+1 (4.5.0 available)
  flutter_keyboard_visibility 5.2.0 (6.0.0 available)
  flutter_lints 3.0.0 (3.0.2 available)
  flutter_markdown 0.6.18 (0.6.22+1 available)
  flutter_svg 2.0.9 (2.0.10+1 available)
  font_awesome_flutter 10.6.0 (10.7.0 available)
  go_router 7.1.1 (13.2.2 available)
  google_fonts 6.1.0 (6.2.1 available)
  google_generative_ai 0.1.0 (0.2.3 available)
  google_identity_services_web 0.2.2 (0.3.1+1 available)
  google_sign_in 6.1.5 (6.2.1 available)
  google_sign_in_android 6.1.20 (6.1.22 available)
  google_sign_in_ios 5.6.4 (5.7.5 available)
  google_sign_in_platform_interface 2.4.2 (2.4.5 available)
  google_sign_in_web 0.12.1 (0.12.4 available)
! http 1.2.1 (overridden)
  image 4.0.17 (4.1.7 available)
  image_picker 1.0.4 (1.0.7 available)
  image_picker_android 0.8.8 (0.8.9+5 available)
  image_picker_for_web 3.0.1 (3.0.3 available)
  image_picker_ios 0.8.8+2 (0.8.9+2 available)
  image_picker_platform_interface 2.9.1 (2.9.4 available)
  intl 0.18.1 (0.19.0 available)
  iregexp 0.1.1 (0.1.2 available)
  js 0.6.7 (0.7.1 available)
  json_path 0.6.2 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.14.0 available)
  path_provider 2.0.14 (2.1.2 available)
  path_provider_android 2.0.25 (2.2.2 available)
  path_provider_foundation 2.2.2 (2.3.2 available)
  path_provider_linux 2.1.11 (2.2.1 available)
  path_provider_platform_interface 2.0.6 (2.1.2 available)
  path_provider_windows 2.1.7 (2.2.1 available)
  percent_indicator 4.2.2 (4.2.3 available)
  permission_handler 11.3.0 (11.3.1 available)
  petitparser 5.4.0 (6.0.2 available)
  pigeon 11.0.1 (18.0.0 available)
  provider 6.0.5 (6.1.2 available)
  purchases_flutter 6.0.0 (6.25.0 available)
  rfc_6901 0.1.1 (0.2.0 available)
  shared_preferences_foundation 2.3.4 (2.3.5 available)
  shared_preferences_platform_interface 2.3.1 (2.3.2 available)
  shared_preferences_web 2.2.1 (2.3.0 available)
  sign_in_with_apple 4.3.0 (6.0.0 available)
  sign_in_with_apple_web 1.0.1 (2.0.0 available)
  sqflite 2.2.6 (2.3.3 available)
  table_calendar 3.0.9 (3.1.1 available)
  test_api 0.6.1 (0.7.0 available)
  timeago 3.2.2 (3.6.1 available)
! uuid 4.3.3 (overridden)
  video_player 2.8.1 (2.8.5 available)
  video_player_android 2.4.10 (2.4.12 available)
  video_player_avfoundation 2.5.1 (2.5.6 available)
  video_player_platform_interface 6.2.1 (6.2.2 available)
  video_player_web 2.1.2 (2.3.0 available)
  vm_service 13.0.0 (14.2.0 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
90 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Upgrading build.gradle
Running Gradle task 'bundleRelease'...                          
Checking the license for package Android SDK Platform 34 in /usr/local/share/android-sdk/licenses
License for package Android SDK Platform 34 accepted.
Preparing "Install Android SDK Platform 34 (revision: 3)".
"Install Android SDK Platform 34 (revision: 3)" ready.
Installing Android SDK Platform 34 in /usr/local/share/android-sdk/platforms/android-34
"Install Android SDK Platform 34 (revision: 3)" complete.
"Install Android SDK Platform 34 (revision: 3)" finished.
Font asset "fa-regular-400.ttf" was tree-shaken, reducing it from 63348 to 1348 bytes (97.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1896 bytes (99.3% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 11724 bytes (99.3% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-solid-900.ttf" was tree-shaken, reducing it from 394668 to 1132 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Note: /Users/builder/.pub-cache/hosted/pub.dev/cloud_firestore-4.15.10/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/builder/.pub-cache/hosted/pub.dev/firebase_messaging-14.7.21/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/builder/.pub-cache/hosted/pub.dev/purchases_flutter-6.0.0/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package_info_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 56s
Running Gradle task 'bundleRelease'...                            177.6s
Gradle task bundleRelease failed with exit code 1

Build failed :|
Step 7 script `Build AAB with Flutter` exited with status code 1

### Environment

```markdown
- FlutterFlow version: v4.1 released April 4, 2024
Flutter version is 3.19.1
- Platform: android
- Browser name and version: edge
- Operating system and version affected:
```

**Comment by fabiodalazem** [comment]
We are having the same problem here!
![bug_image](https://github.com/FlutterFlow/flutterflow-issues/assets/18040604/d5edd12c-98d4-4b4a-98a5-939aeb2e7c5f)

**Comment by allyssons** [comment]
Having the same issue here!

```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':package_info_plus:compileReleaseJavaWithJavac'.
error: invalid source release: 17

```

**Comment by guizostudios** [comment]
The new version fixed the problem

**Comment by NikhilTAndroid** [comment]
Still facing the same issue with latest version of flutter flow app in mac os
