### ISSUE TITLE
Datatable Pagination

### ISSUE THREAD

**Issue by MarceCarcamo** [FlutterFlow/flutterflow-issues#2672]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I deactivate pagination in datatable it does not show me all the items of the query in the list.

### Expected Behavior

It should show the same query items in the list when I disable pagination.

### Steps to Reproduce

1. go to VentasDiaCliente page.
2. Select a date range of 2 or 3 days on the calendar so that it has several items.
3. clic search icon.
4. Disable pagination and repeat the same process.
5.  I added a text at the end of the page with the number of items in the query so you can compare.
![Captura de Pantalla 2024-04-05 a la(s) 10 18 09 a  m](https://github.com/FlutterFlow/flutterflow-issues/assets/103969028/5d13f801-73b2-4afb-a237-e57dc63e3452)
![Captura de Pantalla 2024-04-05 a la(s) 10 16 22 a  m](https://github.com/FlutterFlow/flutterflow-issues/assets/103969028/02d804b2-7a7c-444b-a303-a48a052a1681)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hvKB25N1xOpE1qqBcMJVtDw5JW45RLgrkdZBaBosCJzwP4lzZ8nRUEleTcPid21cIVqjsGcIp8mPvuPLVu5dAxCIQ75E/pBucTrNTkimRqaKOquSYHAmLJtYJkyM5rCOiiRBLuNYV14O7F2uOumtb3bcCZSwNTIFAvybJqT4o13hFSW+KThmtmNecCfn

### Context

My client does not want to see his reports with pagination. You want your datatable in a single list with vertical scrolling.

### Visual documentation

![Captura de Pantalla 2024-04-05 a la(s) 10 18 09 a  m](https://github.com/FlutterFlow/flutterflow-issues/assets/103969028/26b3fa33-30e9-4717-b40f-454cf394a51b)
![Captura de Pantalla 2024-04-05 a la(s) 10 16 22 a  m](https://github.com/FlutterFlow/flutterflow-issues/assets/103969028/140a5dcf-f981-4b4d-9abc-9c15e717e1e3)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: macOS Big Sur 11.7.10
```

**Comment by MarceCarcamo** [comment]
Url of the project: rctech-mobile-7o2elb

**Comment by ignalauret** [comment]
Hey @MarceCarcamo thanks for your report. Sadly I can't test your project running on a device, so please provide the steps to replicate the bug from a Blank Project so I can test it. 
Also, keep in mind that in the Paginated Data Table properties you can set the number of rows that are shown, maybe you can set up something there to make it work properly. 
Have a great day.
