### ISSUE TITLE
Filters that previously worked nicely, stopped working 

### ISSUE THREAD

**Issue by BalntadoreGR** [FlutterFlow/flutterflow-issues#2673]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So the filters that i use in my flutterflow app somehow aren't remembered when i use a list of the selected per choice chip filter category, but the actual filtering works (somehow... my other issue). The problem seems to started these last days, maybe with the last flutterflow updates. 

### Expected Behavior

 I have some categories of filters and choice chips. For every category i use a list of selected options of the choice chips selected for initializing the current filters choosed. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/e5091903-4707-4cf1-9c03-ec925021b528)

And when i use this selected list for initializing the chips, it doesnt remember them at all. Actually i think it remembers only the choice of the first conditional action of the choice chips, where i update the app state of the listSelected. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/99c0bd57-0591-4024-ad76-9c166b1075ab)

now as you see in the update app state, with the current logic (which i dont think is the one that we implement, because it wouldnt never run previously eitherway), the list filterPopulationSizeCategory gets updated with the option and not the the list filterPopulationSizeCategorySelected... and it doesnt make sense, why to change the first and not the second which is the obvious logic to do. And i think tha flutteflow had something to do at this specific point  to my structure with the new updates maybe. 

Next, i tried to solving it, by changing the list from filterPopulationSizeCategory to filterPopulationSizeCategorySelected as it was obvious to do, and then when i tested it, it kept only the first option "Zero" and lost the other options, as i mentioned previously. And this issue makes me think of the conditional actions, and that it can execute only the first conditional action and cant continue to others four options (=cond. actions)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/b1d334cc-84ee-4f07-9559-94c81b7d8fdb)

So maybe it has something to do with the parallel actions that you add ???  

### Steps to Reproduce

When i choose some filters, dismiss the filtering bottom sheet, and then open again the bottom sheet, the filters aren't remembered anymore.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oj8iA8ZdOm99K+KrydflV+CQXNlAjaLsrkspBczwYCOPuB+wQS8zRalVvO7y4Y2NEfWGJ8X4K/Pfqk/zLFvoDOU2rRbpO/6V+aQ7KTkS6brKoPpCzfW1fP/NgfmaX3JivmAhdItZuci0M3U6QPt6tEybAJrrjNm0nBcqLJdeK2SrDX1iXc2URm05KZDPz

### Context

The curious thing is that our logic doesn't seem to work based on what i see to my ff project, and it is obvious the filtering initialization not to work now. Based ie on this logic that i am seeing, the filtering wouldn never had to work neither in the past. So my question is, maybe the updates made to flutterflow affected somehow options in my project, because in my opinion, i think that some Lists arent there where they supposed to be. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/7e60aef1-7c34-4886-a876-75a8954e3604)
choose the filter option top right in the screen

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/c894851a-edbd-4c4b-bc5c-64d816290ea2)
choose a filter (for example zero from population) and then go back

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/bb5494bc-a710-4846-af30-9a4f45ded235)
as you can see the filters work, and it returns zero population items

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/444bfa19-14dd-45b2-ab68-f9537144ee67)
but it doesnt remembers the choices

### Additional Info

the other curious thing is that, either the returning of the right items shouldn't work based on our current logic, but i get the right filtering data. So these is another clue that something is going up with flutterflow and it's unstable. 

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version:Chrome, Version 123.0.6312.88 (Official Build) (64-bit)
- Operating system and version affected: everywhere
```

**Comment by BalntadoreGR** [comment]
so i solved the issue with the filters. I changed all of the logic behind the filtering. But i still think that some things (actions, conditions) disappeared and thats why i had to adapt my logic at first place, so ff team just check it out. 
Below is the new action chain, that solved my problem
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113988884/b25c28cb-3790-4f04-8b95-83328ac33e5b)

for any question i am here :)

**Comment by paulperez-dev** [comment]
Hi @BalntadoreGR! Thank you for the report and the additional details on how you resolved it. I will close this issue and internally inquire if any changes may have affected the logic to prevent it from happening again.
