### ISSUE TITLE
Create Account Auth Action with Set Fields not populating

### ISSUE THREAD

**Issue by cadufreeela** [FlutterFlow/flutterflow-issues#2674]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

During sign up, the following values are requested:

* Name
* Last Name
* Email
* Password
* Confirm password

ON the action options:

* Create Document is switched ON
* Collection is set to UserDetails (name of my collection in FF and Firestore)
* Set Fields:
* First Name (linked to Name)
* Last Name (linked to Last Name)
* is_provider (set to TRUE)
* latitude - calculated using a custom function with device location
* longitude - calculated using a custom function with device location
* rating - set to 5

User is created with email, UID and created_time (this is one of the custom fields set in the action), however when checking in FF > Firestore > Userdetails collection > Manage Content, I can see the "row" with just email, created_time and UID, the other custom fields are not populated

### Expected Behavior

All fields should be filled when user is signing up for the first time

### Steps to Reproduce

1. Create a new page
2. Add a form Container
3. Add a form and add the below text fields:

* add First Name text field
* add Last Name text field
* add password text field
* add confirm password text field

1. Add continue button
2. Create action flow in Continue button:
3. Validate form
4. Auth Create Account (Auth: Email , Email Field: email text field, Password Field: password field, Confirm Password Fied: confirm pw text field)
5. Switch ON Created Document
6. Select Collection UserDetails
7. Set Fields :

* First Name (linked to Name)
* Last Name (linked to Last Name)
* is_provider (set to TRUE)
* latitude - calculated using a custom function with device location
* longitude - calculated using a custom function with device location
* rating - set to 5

1. Show snack bar with any message

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksjf35N2ofVY+Krcc8ZsoCAXCUMfWLsr0utuGA0hNZ+tP+wMdsz8Yk1LYtfhTVdIM1KlpH4zwNmPkeztDu07MgWsGIB7z75XQRfhe3OWMKnWEZO8fkBQEdFXfxXC07unviUmHNVodXwZwE6qCvCNG3qCf9qOYwx5e6fDbOY=

### Context

Basic user sign up with all fields added to firestore

### Visual documentation

![2024-04-06_182143](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b5771dc0-c281-4acf-96eb-93288e6b2426/957e6ca9-1e86-46e8-bf93-a5024b6c6ca3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNTc3MWRjMC1jMjgxLTRhY2YtOTZlYi05MzI4OGU2YjI0MjYvOTU3ZTZjYTktMWU4Ni00NmU4LWJmOTMtYTUwMjRiNmM2Y2EzIiwiaWF0IjoxNzEyNDA0MDgzLCJleHAiOjMzMjgyOTY0MDgzfQ.SGXW9VWtFdnyNRUca6w44Dgrce3x7xZ9B-Uo1IbjBAc)

![2024-04-06_182227](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/96d9e973-d836-4815-bbd1-356c68f87bbc/1076642a-b1fc-48d4-a784-f4b690c31d86?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NmQ5ZTk3My1kODM2LTQ4MTUtYmJkMS0zNTZjNjhmODdiYmMvMTA3NjY0MmEtYjFmYy00OGQ0LWE3ODQtZjRiNjkwYzMxZDg2IiwiaWF0IjoxNzEyNDA0MDgzLCJleHAiOjMzMjgyOTY0MDgzfQ.fREP_t06TNVbTfzf6FeNFyheKnKRa0KHekNy3kPbN7Q)

![2024-04-06_182239](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f9ef48b9-571b-4147-b6bf-7f8d1e88dcab/f7e1964f-9b55-4f9d-bfd5-b75e7f7c60da?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOWVmNDhiOS01NzFiLTQxNDctYjZiZi03ZjhkMWU4OGRjYWIvZjdlMTk2NGYtOWI1NS00ZjlkLWJmZDUtYjc1ZTdmN2M2MGRhIiwiaWF0IjoxNzEyNDA0MDgzLCJleHAiOjMzMjgyOTY0MDgzfQ.tXHC5SCN2NlmxmVrWCRReY01F2QIfzsPcQbOC0iszzQ)

![2024-04-06_182255](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/86be1d9c-eca9-4c5a-b4cd-7cec0bc6ddc7/056ff4f7-309e-4e4a-b77f-b01ad4b8ff63?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NmJlMWQ5Yy1lY2E5LTRjNWEtYjRjZC03Y2VjMGJjNmRkYzcvMDU2ZmY0ZjctMzA5ZS00ZTRhLWI3N2YtYjAxYWQ0YjhmZjYzIiwiaWF0IjoxNzEyNDA0MDgzLCJleHAiOjMzMjgyOTY0MDgzfQ.T9wvuuNY8PebnDU5qbQC3_JakiQcUBRsV1kutDjAnD4)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: mac and windows
- Browser name and version: chrome 123.0.6312.87
- Operating system and version affected: Sonoma 14.3.1
```

**Comment by paulperez-dev** [comment]
Hi @cadufreeela, thanks for your report! I did open the "userDetail" collection after tapping on the Manage content button, but it is empty. Did you delete all the data? Also, I noticed that the first and last name are set to empty in your configuration.
