### ISSUE TITLE
Eternal Web publishing

### ISSUE THREAD

**Issue by VictorDesso** [FlutterFlow/flutterflow-issues#2677]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I need help from the team of flutterflow, to fix the web publihing from my app:
There is an eternal web publishing occuring,because of it i can't upload new features for my client, and flutterflow dosen't show any erros on my project. This is urgent, because the app is in production.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166244334/fe059038-abe2-4d5e-a8e0-fb1e86a4c9f2)
the publishing is loadind more than 12 hours

### Expected Behavior

If there is an error on my project, at leat the flutterflow should notice my, there is no logs area to see what is going on

### Steps to Reproduce

1. Go to my project;
2. Click on web publishing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lcr1z89goddA15Dtbfow9ScUJk87aJ0N08FuFBE8J5DaPOxzP/TBaldWUs+0TG9qeE2ZvD0ewNHemvOeLPcqPQ+YY6I6yM9IaA7KcF2VMoimCLrtYm5/DeRTG3Kw5KS3nhFCXetuWXwcwE6yOeqybB7YJZy3Om4/Pf6aMZCK2SrDX1iXc2URm05KZDPz

### Context

My project is in prodution, and i can't delivery new features for my client because of that

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166244334/a1cfc756-eb8e-4db8-96e4-bc77f9923870)

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Opera
- Operating system and version affected: Windoms
```

**Comment by ignalauret** [comment]
Hey @VictorDesso thanks for your report. I just looked at your project and everything seems to be fine. Are you still experiencing this issue or did it publish correctly?
