### ISSUE TITLE
Firebase queries are not pulling the most recent records

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#2679]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the firebase query to query a collection sorted by `desc` I am missing records that I can explicitly see in firebase directly.

However, when I run the query via an API call through the Firebase Admin SDK, I do get the correct records.

Here is the associated code for the query in Flutterflow:

```
// Generated code for this testCompactions Widget...
Title(
    title: 'testCompactions',
    color: FlutterFlowTheme.of(context).primary.withAlpha(0XFF),
    child: GestureDetector(
      onTap: () => _model.unfocusNode.canRequestFocus
          ? FocusScope.of(context).requestFocus(_model.unfocusNode)
          : FocusScope.of(context).unfocus(),
      child: Scaffold(
        key: scaffoldKey,
        backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
        body: SafeArea(
          top: true,
          child: Container(
            width: MediaQuery.sizeOf(context).width,
            height: MediaQuery.sizeOf(context).height * 1,
            decoration: BoxDecoration(
              color: FlutterFlowTheme.of(context).secondaryBackground,
            ),
            child:
                PagedListView<DocumentSnapshot<Object?>?, CompactionsRecord>(
              pagingController: _model.setListViewController(
                CompactionsRecord.collection // this looks like the query logic <====
                    .where(
                      'userCreated',
                      isEqualTo: currentUserReference,
                    )
                    .orderBy('createDateTime', descending: true),
              ),
              padding: EdgeInsets.zero,
              reverse: false,
              scrollDirection: Axis.vertical,
              builderDelegate: PagedChildBuilderDelegate<CompactionsRecord>(
                // Customize what your widget looks like when it's loading the first page.
                firstPageProgressIndicatorBuilder: (_) => Center(
                  child: SizedBox(
                    width: 50,
                    height: 50,
                    child: CircularProgressIndicator(
                      valueColor: AlwaysStoppedAnimation<Color>(
                        FlutterFlowTheme.of(context).primary,
                      ),
                    ),
                  ),
                ),
                // Customize what your widget looks like when it's loading another page.
                newPageProgressIndicatorBuilder: (_) => Center(
                  child: SizedBox(
                    width: 50,
                    height: 50,
                    child: CircularProgressIndicator(
                      valueColor: AlwaysStoppedAnimation<Color>(
                        FlutterFlowTheme.of(context).primary,
                      ),
                    ),
                  ),
                ),
                itemBuilder: (context, _, listViewIndex) {
                  final listViewCompactionsRecord = _model
                      .listViewPagingController!.itemList![listViewIndex];
                  return Container(
                    width: 100,
                    height: 150,
                    decoration: BoxDecoration(
                      color: FlutterFlowTheme.of(context).secondaryBackground,
                    ),
                    child: Column(
                      mainAxisSize: MainAxisSize.max,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          dateTimeFormat('yMMMd',
                              listViewCompactionsRecord.createDateTime!),
                          style: FlutterFlowTheme.of(context)
                              .bodyMedium
                              .override(
                                fontFamily: 'Plus Jakarta Sans',
                                letterSpacing: 0,
                              ),
                        ),
                        Text(
                          listViewCompactionsRecord.itemTitle,
                          style: FlutterFlowTheme.of(context)
                              .bodyMedium
                              .override(
                                fontFamily: 'Plus Jakarta Sans',
                                letterSpacing: 0,
                              ),
                        ),
                        Text(
                          listViewCompactionsRecord.videoId,
                          style: FlutterFlowTheme.of(context)
                              .bodyMedium
                              .override(
                                fontFamily: 'Plus Jakarta Sans',
                                letterSpacing: 0,
                              ),
                        ),
                        Text(
                          listViewCompactionsRecord.playlistId,
                          style: FlutterFlowTheme.of(context)
                              .bodyMedium
                              .override(
                                fontFamily: 'Plus Jakarta Sans',
                                letterSpacing: 0,
                              ),
                        ),
                        Text(
                          listViewCompactionsRecord.reference.id,
                          style: FlutterFlowTheme.of(context)
                              .bodyMedium
                              .override(
                                fontFamily: 'Plus Jakarta Sans',
                                letterSpacing: 0,
                              ),
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
          ),
        ),
      ),
    ))

```

Here is the code I use that correctly behaves (and now I have to use as an API call to do the same query):

```
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";

export default defineComponent({
  props: {
    firebase_admin_sdk: {
      type: "app",
      app: "firebase_admin_sdk",
    }
  },
  async run({ steps, $ }) {
    try {
      if (!getApps().length) {
        const firebaseConfig = {
          credential: cert({
            projectId: this.firebase_admin_sdk.$auth.projectId,
            clientEmail: this.firebase_admin_sdk.$auth.clientEmail,
            privateKey: this.firebase_admin_sdk.$auth.privateKey.replace(/\\n/g, '\n'),
          }),
          databaseURL: this.firebase_admin_sdk.$auth.customDatabaseUrl,
        };

        initializeApp(firebaseConfig);
      }

      const db = getFirestore();
      const userRef = db.doc(steps.trigger.event.body.userId);
      const limitString = steps.trigger.event.body.limit;
      const limitInt = parseInt(limitString, 10); // Convert string to integer

      console.log(limitInt);

      const querySnapshot = await db.collection('compactions')
        .where('userCreated', '==', userRef)
        .orderBy('createDateTime', 'desc')
        .limit(limitInt)
        .get();

      const documents = querySnapshot.docs.map(doc => doc.data());

      return documents;
    } catch (error) {
      console.error("Error fetching documents:", error);
      // Map Firebase error to HTTP status code as needed
      let statusCode = 500; // Default to internal server error
      if (error.code === 'permission-denied') {
        statusCode = 403; // Forbidden
      }
      // Add more error mappings as needed

      return { error: "Failed to fetch documents", details: error.toString(), statusCode };
    }
  },
});`
```

### Expected Behavior

I expect the behavior of the two codes -- the custom code making the API call via the SDK and the flutter flow UI -- but these are not the same

### Steps to Reproduce

1. Create a firebase query against my project's database `compactions` collection
2. sort by `createdDate`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

CAES6CtDaEZNYVhOMFZtbGxkMTlzTVRaaGJHUXdaUktCRndvU1EyOXVkR0ZwYm1WeVgzQjNkRzl2ZGpsdUV1Z1RDZ3hTYjNkZmIydDVNelF5WTJjU3hRWUtEME52YkhWdGJsOWpjM0V5TTNkbmRSTDVBUW9PU1cxaFoyVmZlV0prTUdZM2FHc1lCeUs0QVRKcENpSm9kSFJ3Y3pvdkwzQnBZM04xYlM1d2FHOTBiM012YzJWbFpDOHlPRFF2TmpBd0VBRVlBaUlMQ2drSkFBQUFBQUFBVkVBcUx3a0FBQUFBQUFBZ1FCRUFBQUFBQUFBZ1FCa0FBQUFBQUFBZ1FDRUFBQUFBQUFBZ1FDZ0NNUUFBQUFBQUFDNUFhUFFEbWdFN0NnSUdBU28xQ0FSQ0FoSUFTaGVDQVJRS0Vnb1FhWFJsYlZSb2RXMWlibUZwYkZWeWJJSUJFd29SVEdsemRGWnBaWGRmYkRFMllXeGtNR1g2QXdEeUJRa0pBQUFBQUFBQThEOWlBSW9CSkJJZUNnZ3djSE4wY1dGNU54SVN3Z0VFQ0FBUUFhb0NDREJtY1hkc05td3pHZ0lJQWNJQkFCS1ZCQW9NVW05M1gySXlZakY2YzNkNkVta0tEVWxqYjI1Zk1ERTVhbk00TkdJWUNDSkJPakFLSVFqanhRTVNEVTFoZEdWeWFXRnNTV052Ym5NZ0FESUtaM0poY0docFkxOWxjUkVBQUFBQUFBQXNRQ0lDRUFqNkF3RHlCUWtKQUFBQUFBQUE4RDg2RG1GMVpHbHZSWGgwY21GamRHVmtZZ0RDQVFBU2J3b05TV052Ymw4MmRHcGpPRzlwYnhnSUlrSTZNUW9pQ01uTUF4SU5UV0YwWlhKcFlXeEpZMjl1Y3lBQU1ndDBaWGgwWDJacFpXeGtjeEVBQUFBQUFBQXNRQ0lDRUFqNkF3RHlCUWtKQUFBQUFBQUE4RDg2RTNSeVlXNXpZM0pwY0hSRGIyMXdiR1YwWldSaUFNSUJBQkp3Q2cxSlkyOXVYMnh1ZFdNM05tODJHQWdpU0RvM0NpZ0k4OTRERWcxTllYUmxjbWxoYkVsamIyNXpJQUF5RVdOdmJYQnlaWE56WDI5MWRHeHBibVZrRVFBQUFBQUFBQ3hBSWdJUUNQb0RBUElGQ1FrQUFBQUFBQUR3UHpvT1kyOXRjR0ZqZEdsdmJrUnZibVZpQU1JQkFCSnZDZzFKWTI5dVgyVXpaWE42Y1hoNUdBZ2lTRG8zQ2lnSWtNb0RFZzFOWVhSbGNtbGhiRWxqYjI1eklBQXlFWEpsWTI5eVpGOTJiMmxqWlY5dmRtVnlFUUFBQUFBQUFDeEFJZ0lRQ1BvREFQSUZDUWtBQUFBQUFBRHdQem9OZG05cFkyVlZjR3h2WVdSbFpHSUF3Z0VBR0FNaU1ob05FQU1xQ1FrQUFBQUFBQUFVUUZvU0VRQUFBQUFBQUJSQUlRQUFBQUFBQUJSQStnTUE4Z1VKQ1FBQUFBQUFBUEEvT2d0emRHRjBkWE5KWTI5dWMySUF3Z0VBR0FRaUZ5SUdFQUVZQkRJQStnTUE4Z1VKQ1FBQUFBQUFBUEEvWWdEQ0FRQVN6d2NLRDBOdmJIVnRibDluZWpKdWFHNXdjUktWQndvU1EyOXVkR0ZwYm1WeVgySmtZV3hwYzNOa0Vxd0dDZzlEYjJ4MWJXNWZhVFoxT0dSdk9ESVNuUUVLRFZSbGVIUmZjV05oT0RSdWIya1lBaUtFQVJJb0NndElaV3hzYnlCWGIzSnNaQkVBQUFBQUFBQXNRQ2dETUFGQUJsQUJXRkJnQVpBQkFxZ0JBSElTQ1FBQUFBQUFBUEMvRVFBQUFBQUFBQUFBbWdFMENnSUNBU291Q0FSQ0FoSUFTaENDQVEwS0N3b0phWFJsYlZScGRHeGxnZ0VUQ2hGTWFYTjBWbWxsZDE5c01UWmhiR1F3WmZvREFQSUZDUWtBQUFBQUFBRHdQMklBd2dFQUV2Z0JDZzFVWlhoMFh6ZDVPVzExYW5NekdBSWkzd0VTSHdvTFNHVnNiRzhnVjI5eWJHUVJBQUFBQUFBQUpFQTZBaEFJUUFlb0FRQ2FBYXNCQ2dJQ0FTcWtBUWdLVXA4QkVqRVNMd2dFUWdJU0FFb1JnZ0VPQ2d3S0NuQnNZWGxzYVhOMFNXU0NBUk1LRVV4cGMzUldhV1YzWDJ3eE5tRnNaREJsRWpNU01RZ01RaTBpS3dvbkNodFpiM1YwZFdKbFVHeGhlV3hwYzNSRVlYUmhWSGx3WlV4cGMzUVNDR1poTlhabGRERTJFQUVhTlFvc1ptbHVaRlJwZEd4bFFubEpaR1p5YjIxWmIzVjBkV0psVUd4aGVXeHBjM1JFWVhSaFZIbHdaVXhwYzNRU0JXbHhkbmQwK2dNQThnVUpDUUFBQUFBQUFQQS9ZZ0RDQVFBU25nRUtEVlJsZUhSZmNqRmhOamw2YzNNWUFpS0ZBUklkQ2d0SVpXeHNieUJYYjNKc1pCRUFBQUFBQUFBa1FDZ0NRQWFvQVFDYUFWUUtBZ0lCS2s0SUNsSktDZ0FTRHdvTkVndHpiM0owU1c1a1pYZzZJQkkxRWpNSUJFSUNFZ0JLRllJQkVnb1FDZzV5Wlc5eVpHVnlVMjl5ZEV0bGVZSUJFd29SVEdsemRGWnBaWGRmYkRFMllXeGtNR1g2QXdEeUJRa0pBQUFBQUFBQThEOWlBTUlCQUJLK0FRb05WR1Y0ZEY5M1pUbHRjREV4WnhnQ0lxVUJFaFlLQzBobGJHeHZJRmR2Y214a09nSVFDRUFIcUFFQW1nRjdDZ0lDQVNwMUNBcFNjUW9BRW0wU2F3Z0tVbWNTQ1FvSEVnVjVUVTFOWkJJMUVqTUlCRUlDRWdCS0ZZSUJFZ29RQ2c1amNtVmhkR1ZFWVhSbFZHbHRaWUlCRXdvUlRHbHpkRlpwWlhkZmJERTJZV3hrTUdVYUl3b2FZMkZ6ZEVSaGRHVlVhVzFsVkc5R2IzSnRZWFJUZEhKcGJtY1NCV1ZwWjNaNitnTUE4Z1VKQ1FBQUFBQUFBUEEvWWdEQ0FRQVlCQ0lWSWdRWUJESUErZ01BOGdVSkNRQUFBQUFBQVBBL1lnRENBUUFZQVNKSkNpUUtDd29KRVFBQUFBQUFnRkZBRWdoQ0FoQUdXZ0JpQUNJQVNRQUFBQUFBQUZsQVVnQnlFZ2tBQUFBQUFBRHd2eEVBQUFBQUFBQUFBUG9EQVBJRkNRa0FBQUFBQUFEd1AySUF3Z0VBR0FRaUhTSUdFQUVZQkRJQWVnUVFBeGdCK2dNQThnVUpDUUFBQUFBQUFQQS9ZZ0RDQVFBUytnUUtEME52YkhWdGJsOTZZemx3TVhsbU9STHFBd29NVW05M1gzZHlkelp2YzJkc0VtOEtEVlJsZUhSZmFXOXlNbVkyZURJWUFpSlhFaDBLQzBobGJHeHZJRmR2Y214a0VRQUFBQUFBQUNKQUtBRkFCcWdCQUpvQkpnb0NBZ0VxSUFnRVFnSVNBRW9DR2dDQ0FSTUtFVXhwYzNSV2FXVjNYMnd4Tm1Gc1pEQmwrZ01BOGdVSkNRQUFBQUFBQVBBL1lnRENBUUFTekFJS0UwbGpiMjVDZFhSMGIyNWZPV2N6TldKcGIzUVlDeUtPQVZKOUNsVUtSZ2pDNGdNU0VFWnZiblJCZDJWemIyMWxVMjlzYVdRYUZHWnZiblJmWVhkbGMyOXRaVjltYkhWMGRHVnlJQUFxQ3dvSlpXeHNhWEJ6YVhOV01nbGxiR3hwY0hOcGMxWVJBQUFBQUFBQU1FQWlBaEFISWdJUUJURUFBQUFBQUFBMFFEb0NFQVZCQUFBQUFBQUFBQUNDQVFrSkFBQUFBQUFBUGtENkF3RHlCUWtKQUFBQUFBQUE4RDlpQUlvQm13RVNsQUVLQ0hvMGEzQmliemcyRW9jQkVub1FBUnBmRWtnS0JtbG9kM2g1Y3hJK0NoY0tEV052YlhCaFkzUnBiMjVTWldZU0JtbG9kM2g1Y3lJakNBUkNBaElBU2dXQ0FRSVFBWUlCRXdvUlRHbHpkRlpwWlhkZmJERTJZV3hrTUdVeUV3b1JVMk5oWm1admJHUmZkamRsYnpGek9HTWdBRm9UQ2hGVFkyRm1abTlzWkY5Mk4yVnZNWE00WTZvQ0NHOWlPWEJvTTJJekdnSUlBY0lCQUJnREloTWFBaW9BK2dNQThnVUpDUUFBQUFBQUFQQS9ZZ0RDQVFBU1dnb05TV052Ymw5MGFURm1hbXR6Y1JnSUlrSTZNUW9pQ016SkF4SU5UV0YwWlhKcFlXeEpZMjl1Y3lBQU1ndHdiR0Y1WDJOcGNtTnNaUkVBQUFBQUFBQWtRQ0lDRUFqNkF3RHlCUWtKQUFBQUFBQUE4RDlpQU1JQkFCZ0VJaGNpQmhBREdBUXlBUG9EQVBJRkNRa0FBQUFBQUFEd1AySUF3Z0VBR0FNaU9ob1BDQUFRQlNvSkNRQUFBQUFBQUM1QVdoUUpBQUFBQUFBQUpFQVpBQUFBQUFBQUpFQkFBWG9DR0FQNkF3RHlCUWtKQUFBQUFBQUE4RDlpQU1JQkFCZ0JJb01DQ2tjS0Znb0pFUUFBQUFBQUFGbEFFZ2tKQUFBQUFBQUFYa0FTSGhJVUNRQUFBQUFBQUM1QUtBSXhBQUFBQUFBQUxrQkNBaEFHV2dCaUFDSUFNQUZKQUFBQUFBQUFXVUJTQUZvSklRQUFBQUFBQUM1QW1nR1hBUW9EQVFJSktvOEJDQW95QkJvQ0VBUlNoQUVTSWhJZ0NBUkNBaElBU2dJYUFJSUJFd29SVEdsemRGWnBaWGRmYkRFMllXeGtNR1VTTHhJdENBd3lBeElCTUVJa0lpSUtIZ29TWTNWeWNtVnVkRkJzWVhsbGNrbHVaR1Y0RWdnMGJUUnlhR2cwTXhBQkVnWUtCQm9DRUFNU0Jnb0VHZ0lRQkJvZENoUmpiMjF3WVdOMGFXOXVTVzVrWlhoRGIyeHZjaElGYXpNMU1HZjZBd0R5QkFJS0FQSUZDUWtBQUFBQUFBRHdQMklBaWdGeUVtd0tDSGg1Y1dkMmN6QnNFbURpQVRaQ01Bb0tFZ2cwYlRSeWFHZzBNeElpRWlBSUJFSUNFZ0JLQWhvQWdnRVRDaEZNYVhOMFZtbGxkMTlzTVRaaGJHUXdaVkFDV0FHaUFobDFjR1JoZEdVZ1kzVnljbVZ1ZEZCc1lYbGxja2x1WkdWNHFnSUliM1Z5Wm5FME1qWWFBZ2dCd2dFQUdBWWlJa0lJQ0FFUUFpb0FNQUI2QWhnRCtnTUE4Z1FDQ2dEeUJRa0pBQUFBQUFBQThEOVNsZ0VLRXhBSEdnMEtDMk52YlhCaFkzUnBiMjV6SUFFU2ZRb05DZ3RqYjIxd1lXTjBhVzl1Y3hvVUNoQUtEbU55WldGMFpVUmhkR1ZVYVcxbEVBRWc5QU1vQUVJR0NBRVFNaGdCY2trS1J3cEZDaEFLRG1OeVpXRjBaVVJoZEdWVWFXMWxFQVpLTHdnS1Vpc1NCZ29FRWdJek1Cb2hDaGgwYjJSaGVVMXBiblZ6UkdGNWMwRnpSR0YwWlZScGJXVVNCV1l5ZHpaM09nQmlBSW9CcGdZU253WUtDR2RpYUhkdmRtTnJFdThCSXFzQlVwTUJDZzBLQzJOdmJYQmhZM1JwYjI1ekdoUUtFQW9PWTNKbFlYUmxSR0YwWlZScGJXVVFBU2dBY21vS0hRb2JDZzBLQzNWelpYSkRjbVZoZEdWa0VBRktDQWdDUWdRS0FnZ0lDa2NLUlFvUUNnNWpjbVZoZEdWRVlYUmxWR2x0WlJBR1NpOElDbElyRWdZS0JCSUNNekFhSVFvWWRHOWtZWGxOYVc1MWMwUmhlWE5CYzBSaGRHVlVhVzFsRWdWbU1uYzJkeEFCV2hNUUJ4b05DZ3RqYjIxd1lXTjBhVzl1Y3lBQjJnRVdjbVZtY21WemFFTnZiWEJoWTNScGIyNVJkV1Z5ZWFJQ0duRjFaWEo1SUVOdmJYQmhZM1JwYjI0Z1JtbHlaWE4wYjNKbHFnSUlkMmN5T0hOdVpIUXFvQVFLQ0d0dmNIQTJNMlV3RW9jRDRnRy9Ba0laQ2dvU0NHbzJNMkY2Ym1FMkVnc1NDUWdWUWdXYUFRSUlCRUtOQVFvS0VnZzVkalJqWW1ObGVSSi9FbjBJQ2xKNUVrY1NSUWdKUWloYUpoSVlDaFp5WldaeVpYTm9RMjl0Y0dGamRHbHZibEYxWlhKNUdnb0tDSGRuTWpoemJtUjBnZ0VUQ2hGTWFYTjBWbWxsZDE5c01UWmhiR1F3WllvQkFCb3VDaVZqYjIxd1lXTjBhVzl1VVhWbGNubE1hWE4wVkc5amIyMXdZV04wYVc5dVUzUnlkV04wRWdWNk9IVXhia0tOQVFvS0VnaHZhVFZuZUc1blpCSi9FbjBJQ2xKNUVrY1NSUWdKUWloYUpoSVlDaFp5WldaeVpYTm9RMjl0Y0dGamRHbHZibEYxWlhKNUdnb0tDSGRuTWpoemJtUjBnZ0VUQ2hGTWFYTjBWbWxsZDE5c01UWmhiR1F3WllvQkFCb3VDaVZqYjIxd1lXTjBhVzl1VVhWbGNubE1hWE4wVkc5amIyMXdZV04wYVc5dVUzUnlkV04wRWdWNk9IVXhibEFDV0FHaUFqWmpiR1ZoY2lCd2JHRjViR2x6ZERzZ2RYQmtZWFJsSUdOdmJYQmhZM1JwYjI1RVlYUmhPeUIxY0dSaGRHRWdabWxzZEdWeVpXU3FBZ2hvYTJkM2VtaGpNeXFKQVFvSVpHVnljbnAzZEdNU2Zhb0Jid3BIRWtVSUNsSkJDZ0FTR1FvWEVoVmhjSEJUZEdGMFpTQndiR0Y1YkdsemRFbGtPaUFTSWhJZ0NBeENIQ0lhQ2hZS0NuQnNZWGxzYVhOMFNXUVNDR28yTTJGNmJtRTJFQUVTQ2JJQkJnb0VHZ0lRQnlFQUFBQUFBRUN2UUNvR0lnUVNBaEFCTUFBNkJnb0VHZ0lRQXFvQ0NITnROSHAzYm1ZeEdnSUlDWW9CNHdFUzNBRUtDSEp3WldsamMzSTJFczhCb2dJSGNtVnZjbVJsY3FvQ0NHbGxjbTUwY2pkcDRnUzJBUXF6QVFvSWNuQmxhV056Y2pZU3BnSGlBWTBCUW9ZQkNnb1NDRzlwTldkNGJtZGtFbmdTZGdnS1VuSVNNaEl3Q0F4Q0xDSXFDaVlLR21acGJIUmxjbVZrUTI5dGNHRmpkR2x2YmtSaGRHRk1hWE4wRWdodmFUVm5lRzVuWkJBQkVnc1NDUWdjUWdYQ0FRSUlBUklMRWdrSUhFSUZ3Z0VDQ0FJYUlnb1pjbVZ2Y21SbGNrTnZiWEJoWTNScGIyNUVZWFJoVEdsemRCSUZlSEJrTVRoUUFsZ0JvZ0lIY21WdmNtUmxjcW9DQ0dsbGNtNTBjamRwR2dJSUc4SUJBQT09

### Context

My primary value of my app is to be able to display properly the records, especially the most recent records, for the user.  This has not been working for a full week and I have tried multiple things.

### Visual documentation

![Image 2024-04-06 at 1 23 21 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/f35cbeb0-be85-4d7a-9d26-3da63bfacb66)

![Image 2024-04-06 at 1 24 03 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/14055/ac072db7-1874-48e3-ac23-5eade3e22a61)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: MacOS 14.3 (23D2057)
- Browser name and version: Version 17.3 (19617.2.4.11.8)
- Operating system and version affected:  MacOS, but also IOS
```

**Comment by timfong888** [comment]
What's the user response you are looking for?  Here is a video of the same problem:

https://zight.fong888.com/xQuQB8n9

**Comment by ignalauret** [comment]
As I mentioned, I don't see a bug here, you have a difference between the two queries that you are expecting to behave the same, so you must have a misconfiguration in your Firebase query. 
If you need any help on how to implement what you are looking for, please contact our customer support and they will be happy to help you.

**Comment by timfong888** [comment]
This is the code I wrote:

```
      const querySnapshot = await db.collection('compactions')
        .where('userCreated', '==', userRef)
        .orderBy('createDateTime', 'desc')
        .limit(limitInt)
        .get();
 ```
 
 This is the code I generated using futterflow:

```
queryBuilder: (compactionsRecord) =>
                                          compactionsRecord
                                              .where(
                                                'userCreated',
                                                isEqualTo: currentUserReference,
                                              )
                                              .orderBy('createDateTime',
                                                  descending: true),
                                      limit: 50,
 ```
 
 These seem similar enough and yet are very different in results.

**Comment by timfong888** [comment]
@ignalauret I pulled out the relevant queries, put into a separate page to ensure there wasn't other code, and I still get the same result, missing things.  I am now going through firebase to remove certain records that don't conform to the schema, but that hasn't changed anything.

**Comment by timfong888** [comment]
I'm now testing what the issue is with FF query by changing the equality value of the filter -- I don't think it matters since I get the same problem even when I remove the filter and just look for the records ordered by `createDateTime` -- the FF still misses a meaningful number of records.

**Comment by timfong888** [comment]
I provided additional details and I still see the same issue.

**Comment by ignalauret** [comment]
Hey @timfong888 I'm sorry for the late response. Where you able to make your Firebase query work?
