### ISSUE TITLE
Compilation errors line numbers are wrong

### ISSUE THREAD

**Issue by crioux** [FlutterFlow/flutterflow-issues#268]
## Expected behavior (required)
Errors on the right line numbers.

## Current behavior (required)
Line numbers are off by 10.

## To Reproduce (required)
1. Create a custom widget
2. Put an error after the classes at the end, like an import directive that doesn't belong there.
3. Hit compile and look at the error line numbers.

## Context (required)
Trying to debug a custom widget.

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/819652/209241690-416e3ffb-9e17-4490-a994-a8aff8d37fba.png)

## Your environment
* Version of FlutterFlow used: 3.0 12/22/22

**Comment by agreaves** [comment]
Thanks for the heads up! This will be fixed upon our next deploy!
