### ISSUE TITLE
youtubeplayer URL data binding

### ISSUE THREAD

**Issue by vidy01** [FlutterFlow/flutterflow-issues#2681]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to bind the youtubeplayer URL to a remoteconfig string. FF won't let me bind the URL to any string, not even app state, not even the firebase remote config string

### Expected Behavior

URL binding should work like any other field??

### Steps to Reproduce

add a youtube player. Add a firebase remote config string data type. try to bind the URL of the youtube player to the remoteconfig string. FF Won't let you do it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkPLqy4hJpbxb7aXUY+9aliM6JmIia700tdh+GEkdB4z3BIgEfPTOak5vZryjT2x+eGaannwJxvfqj87mUMcrHw6dft1lyJYJTArJXnqibraDC5aVfW1TEdtbJ0iu0piRvxJdKtZvLHwM2zmQHOuvbBTsNYTVDjJFD8q1KdeK2SrDX1iXc2URm05KZDPz

### Context

i am trying to upload help videos to a help page and link them to youtube videos. But everytime i have an update to a specific video i do not want to deploy. Rather i'd like to update the URL remotely.

### Visual documentation

I think this is very easy to understand without images.

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Arc
- Operating system and version affected: MacOS
```

**Comment by ignalauret** [comment]
Hey @vidy01 thanks for your report. To use a dynamic URL on a youtube video, you need to tap on the icon that is at the right of "URL" title

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a544a57c-ff42-46fd-971d-db65169ddcfc/b9a858a6-09ef-47bf-a5d8-7b8d1df10cd3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNTQ0YTU3Yy1mZjQyLTQ2ZmQtOTcxZC1kYjY1MTY5ZGRjZmMvYjlhODU4YTYtMDllZi00N2JmLWE1ZDgtN2I4ZDFkZjEwY2QzIiwiaWF0IjoxNzEyNjA4Njc2LCJleHAiOjMzMjgzMTY4Njc2fQ.Z799KZzRFx8TGa2tC7rZdIgVaZjVTpRn_TQzRIoTAUk " alt="Screenshot 2024-04-08 at 5.35.23 PM.png" width="637" height="500" />

Then from there, you can get the data from Firebase Remote Config, a function that gets it from an API, etc. 
If you need more help, please feel free to contact our Customer Support, they will bring you info on how to implement what you are looking for.
Have a great day.

**Comment by vidy01** [comment]
Of course I tried that. Please let me know if it lets you select the remote config from the available options. It “reds” out the remote config value that I set.

￼

In the screenshot I cannot select the AppOverViewHelpURL. 

Its a string remote config value.

Hope that makes sense.

Regards,
Vidy

**Comment by ignalauret** [comment]
Hey @vidy01 I'm checking your project and I can see only one value for remote config 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e62df990-5cd0-4404-965a-888a6b82e026/6254b278-5b9c-4bc8-8fde-9948de488210?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNjJkZjk5MC01Y2QwLTQ0MDQtOTY1YS04ODhhNmI4MmUwMjYvNjI1NGIyNzgtNWI5Yy00YmM4LThmZGUtOTk0OGRlNDg4MjEwIiwiaWF0IjoxNzEzMjkyMTI2LCJleHAiOjMzMjgzODUyMTI2fQ.IKMZsJiPsS6i319Cgh_Tj3lK80Ow1XSlXwz6o0ekzjo " alt="Screenshot 2024-04-16 at 3.27.12 PM.png" width="630" height="497" />

"canAddPhotos" that is a boolean so I can't use it. Are you sure you have the AppOverViewHelpURL variable setup on your Remote Config?

**Comment by vidy01** [comment]
Oh I moved on from this issue. I abandoned that feature because this was not possible.

I recommend you try it on one of your sample apps.
Regards,
Vidy
