### ISSUE TITLE
Media assets missing - Blocker

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2682]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was working on the project. I worked partially on the desktop version, saved the project and worked again on the web version on chrome. To my surprise all the media assets got disappeared.  
I checked my media assets section in flutterflow and found that the media assets were missing. 
I reuploaded all the files again. But flutterflow has completely erased the mapping

[Missing settings asset #2498 ](https://github.com/FlutterFlow/flutterflow-issues/issues/2498) This was the similar issue reported earlier. But is closed. I have seen in the communities as well and people have faced this issue and is still open.
![Screenshot 2024-04-07 at 17 55 12](https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/de739a11-df0f-4ef7-b1ca-25e0fa2b026f)

### Expected Behavior

Media assets previously uploaded should not get deleted and their mapping should not miss.

### Steps to Reproduce

I am not sure if this can be reproduced with standard procedure. So, i will elaborate the steps i took.

1. Develop the pages with web version.
2. Try running the project from desktop version.
3. Got compiler errors which cannot be solved from flutterflow.
4. Opened the code from flutterflow application with android studio and checked the code. But closed again.
5. Closed the desktop and went back to web version.
6. Found that the media assets missing errors were reported
![Screenshot 2024-04-07 at 17 55 12](https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/116daca0-2389-4b42-a968-086dc3d16424)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlPLlvJV2otxE15DuY8BFmjoRMjs3bI0k0+xuZCs8GZT0B4kcYs+kfklUON/nTwlieFqjmj0X/MrRi9/xGME4IQerbb5G/rV+UxXgXk2RVJfSCpS3b3d5EftRJkixy7e7pxMnBPhecV4N2zv7DOfLfHXDQpjBDDInA+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

It is a blocker and i am unable to proceed with my testing and development

### Visual documentation

![Screenshot 2024-04-07 at 17 55 12](https://github.com/FlutterFlow/flutterflow-issues/assets/119512221/37399e92-ff24-4c69-9951-7b8982ef11db)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:Macos
- Browser name and version:Chrome
- Operating system and version affected:
```

**Comment by ignalauret** [comment]
Hey @task-win thanks for your report. I was able to see your project and I can only see 22 warnings and no errors. Do you sill have this blocker or were you able to figure it out?

**Comment by task-win** [comment]
The issue still exists.. 
For your reference.. adding another bug report code to access the project
ITFThcrl25RNsctE+Kn9KuxaqDwWI0MfWOdEket+EA0hNZerE6QcfczRXFRLYte/YH1EB02YoHIC+NL3j+OeKvkCIT6uc4Q7wpRXQQrJcFunaZClEbmCQnElHdFnI26v0MPYqh0kNrB2LloX7TmQO/CdG3qCf9qOYwx5e6fDbOY=

**Comment by task-win** [comment]
There are 8 media asset missing errors on the project

**Comment by ignalauret** [comment]
Oh I see, you shared the Bug Report code for another project. Let me review now the issue with your assets.

**Comment by leighajarett** [comment]
Closing this issue as the data loss problem between Windows and web has been resolved.
