### ISSUE TITLE
Error Saving Project

### ISSUE THREAD

**Issue by gabdreux** [FlutterFlow/flutterflow-issues#2685]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not saving changes. I noticed that this problem may be related to a specific project. So even though this topic already exists, I'm opening one for myself. Much tks! Project ID: monitor-13-gurq9c

### Expected Behavior

Save it.

### Steps to Reproduce

Just try to make any changes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi8mAvI9IsbRJ+Kn9Y+9VqGEWH096UK00sNobbxAjIoDoPJkUaeLSUEttZM/gY1ZpKEWLkmYEwPSLuePpU/lfHEiVGLlxycxIFgrjeHm/aoubCKqoPkFSP91UN0Ci5LaFogpRJupaWlo5116UC/CXFwncO7n6Zwh9f6PHaOI=

### Context

Trying to save my job!!

### Visual documentation

![bugSave01](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6c5c793a-c153-41dc-ab6b-a0a7bae3a4fe/a18e2a48-5a41-4f75-bbba-7b583cfa6785?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YzVjNzkzYS1jMTUzLTQxZGMtYWI2Yi1hMGE3YmFlM2E0ZmUvYTE4ZTJhNDgtNWE0MS00Zjc1LWJiYmEtN2I1ODNjZmE2Nzg1IiwiaWF0IjoxNzEyNTc3Njc1LCJleHAiOjMzMjgzMTM3Njc1fQ.d76MxNaQnsLSG2GqeE8UecxnxhjKai1t0YS-sV7csS0)

![bugSave02](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2a2bd054-e7a6-4634-8380-55f48f094daf/16dd5e92-9061-4008-9368-af89f8c53b22?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYTJiZDA1NC1lN2E2LTQ2MzQtODM4MC01NWY0OGYwOTRkYWYvMTZkZDVlOTItOTA2MS00MDA4LTkzNjgtYWY4OWY4YzUzYjIyIiwiaWF0IjoxNzEyNTc3Njc1LCJleHAiOjMzMjgzMTM3Njc1fQ.aF21Z1CDdRJI5rTTgbtoO2xLYMZLyhZ7ngm1wzXooTk)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.38+
Flutter version is 3.19.1
- Platform: Chrome, Edge and Windows.
- Browser name and version: Chrome Version 123.0.6312.106 64 bits
- Operating system and version affected: Windows 10
```

**Comment by ignalauret** [comment]
Hey @gabdreux thanks for your report. We have fixed some issues like yours before, so the technical team is going to check if yours is the same case or something different. We will keep you updated on this thread. 
Have a great day.

**Comment by gabdreux** [comment]
Thank you very much for your quick response and attention!!

**Comment by ignalauret** [comment]
Hey @gabdreux thanks for the information. The technical team thinks yours is a different bug than the ones solved before, so I'm submitting a ticket with your information. They will try to fix it and keep you updated on this thread.

**Comment by gabdreux** [comment]
Perfect! Much tks!!

**Comment by victoriahuang1** [comment]
@gabdreux is this the only project affected? Or are you experiencing this with all projects?

**Comment by gabdreux** [comment]
Hi, @victoriahuang1 ! Yes. This is the only project affected. And the duplicated one is saving just fine.

**Comment by victoriahuang1** [comment]
@gabdreux can I get permission to try saving your project on your behalf, in order to investigate further?

And in the meantime, if you have a firewall enabled or are using a VPN, you can try disabling them and see if that makes it work better

**Comment by gabdreux** [comment]
@victoriahuang1 sure! But now it is no longer necessary. 

I followed the project in the copy I had made.
The problem now is that the copy no longer saves either!

I tried to apply the same maneuver of duplicating the project but the new copies are also showing the same error!

I'm VERY close to finishing the project but now I'm completely unable to work on it.

I therefore ask that you turn your attention to the most up-to-date project:
ID: monitor-13-8955ij
FlutterFlow v4.1.47+ released May 6, 2024
Flutter version is 3.19.1

Considering how long they have been trying to resolve the problem with the first project, I believe this will take a long time and I really need to finish the project.
In the past I tried to download the project and upload it to github without success. Can you make it available on github so I can continue working? It's causing me a lot of problems!!!

Tks!!

**Comment by victoriahuang1** [comment]
@gabdreux I will take a look at your new project. As for GitHub, you can use our integration: https://docs.flutterflow.io/settings-and-integrations/integrations/github

**Comment by gabdreux** [comment]
@victoriahuang1 I've already tried pushing it to gitHub without success!! I don't remember if it returned an error or if it just kept loading forever. To download directly to my computer, I remember that it sat for about 10 hours at night without success and I canceled it so I could continue working.
I no longer have a Pro account because none of the features offered worked in my project...I was unable to download it, send it to GitHub or even run it in "local run"...so I went back to the free plan. Very frustrating :(

**Comment by leighajarett** [comment]
HI @gabdreux - we realized that the issue is coming from this page `InspecoesLvs` - there are over 5000 widgets in this page. Please consider creating reusable components instead of having thousands of widgets in a single page. If you still experience issues after refactoring, please reach out to our support team who can better assist you. Thanks so much, and sorry for the issues!
