### ISSUE TITLE
Display issues in test mode

### ISSUE THREAD

**Issue by jerfai** [FlutterFlow/flutterflow-issues#2687]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when running test mode, some part of the display are not showing on the right-hand side.

### Expected Behavior

the display should be whole without elements missing.

### Steps to Reproduce

1. run test mode
2. wait for test mode to appear.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPLqx892oflY+KrQcMJ4qDkQGUMdXOczitVEew4bCIj4OuwQfODsX1VCXfazaH1EBlSImmA00N7QveP1V/k6aE+tUYRGwpF6aBPPbFKuVaqqCpC0X0FfN+5VJ3644Jm02B1SWfFYSiFm2V6Lfe+RVT6Cf9qOYwx5e6fDbOY=

### Context

the issue is hampering testing because some elements are "cut off".

### Visual documentation

![Screenshot 2024-03-28 190933](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/231ad7c6-52a3-49e1-bb57-10cc0ffcb1a0/9816c6ec-1390-45dd-a029-b014910fbc64?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMzFhZDdjNi01MmEzLTQ5ZTEtYmI1Ny0xMGNjMGZmY2IxYTAvOTgxNmM2ZWMtMTM5MC00NWRkLWEwMjktYjAxNDkxMGZiYzY0IiwiaWF0IjoxNzEyNTg2MjAyLCJleHAiOjMzMjgzMTQ2MjAyfQ.SbD4z1XI-HD2JRspHEBRwooe6aNMAeuo1BnO-dxt5rQ)

### Additional Info

the issue dissapear if I select a different screen size but comes back if I navigate to a new page.

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Windows 11
- Browser name and version: Chrome 123
- Operating system and version affected: Test mode only.
```

**Comment by ignalauret** [comment]
Hey @jerfai thanks for your report. Sadly I can't test your app, so I will need you to give me some steps to reproduce it from a Blank project. What widgets are you seeing cut off? What type of widgets are them? Which are the settings?

**Comment by FlagshipPartners** [comment]
I am having the issue too only on Chrome - Chrome is up to date
Version 123.0.6312.123 (Official Build) (64-bit)

I have tested on Edge and I don't have the issue on there.

**Comment by JeromePS** [comment]
@ignalauret @FlagshipPartners if you clear the cache completely (all time) then it should work. it worked for me.

**Comment by FlagshipPartners** [comment]
@JeromePS I have cleared the cache completely (all time) and still the issue persists. I was advised by support to use Edge.

**Comment by leighajarett** [comment]
Can you try Ctrl + 0 (to reset the zoom)?

**Comment by FlagshipPartners** [comment]
@leighajarett That has resolved the issue for me, thank you!
