### ISSUE TITLE
Photo Library Permission Dialog Not Displaying on Android Devices

### ISSUE THREAD

**Issue by abbasvajihi** [FlutterFlow/flutterflow-issues#2688]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm encountering an issue in my Flutter app where the permission dialog for accessing the photo library is not popping up on Android devices. Despite correctly declaring the READ_EXTERNAL_STORAGE permission in the AndroidManifest.xml file and handling runtime permissions in my Flutter code, the permission dialog fails to appear when the app requests access to the photo library.

I've thoroughly reviewed my code, tested on multiple devices, and ensured that there are no logical errors or conditions preventing the permission dialog from being displayed. 

This is only occurring on Android. Works fine on iOS.

### Expected Behavior

Expect the permissions dialog box to appear in app when action executed to request permissions but nothing happens. Additionally, checking the app settings during an Android run shows that permissions don't even exist for the photo library/ gallery.

![Screenshot_20240409-001955](https://github.com/FlutterFlow/flutterflow-issues/assets/40188757/32a2f7c5-89f7-4732-90b0-18e8fe1ca741)

![Screenshot_20240409-002035](https://github.com/FlutterFlow/flutterflow-issues/assets/40188757/5a12032b-5b2d-4207-8db5-2f5021bea88b)

### Steps to Reproduce

1.  Go to Settings and Integrations > Permissions > Photo Library
2. Enable Photo Library (+ add Permissions Message)
3. Create a blank page
4. Add a column
5. Add a button
6. Action 1 - On Tap, Request Permissions: Photo Library
7. Local Run on Android device
8. When app is loaded, click the button
9. Additional verification that permissions is not requested - go to app settings in Device Settings > [App Name] > Permissions 
10. Observe that there are no permissions for Photo Library/ Gallery access despite it being enabled in the Settings Integrations in Flutterflow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

User Frustration and Engagement: Inability to upload images frustrates users, leading to decreased engagement and usage of your app.

Loss of Revenue: If users can't upload images, it hampers key functionalities and doesn't allow users to move forward from the onboarding processresulting in abandoned accounts. 

Negative Reviews and Ratings: Users experiencing issues may leave negative reviews, damaging your app's reputation and deterring new users.

### Visual documentation

[Visual Steps - Permissions.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/14913927/Visual.Steps.-.Permissions.pdf)

### Environment

```markdown
- FlutterFlow version: 4.1.38
- Platform:MacOS Desktop
- Browser name and version: Arc 1.34.0
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by paulperez-dev** [comment]
Hi @abbasvajihi, thanks for your report. Are you trying to prompt the permission without showing the photo library UI?

Can you take a look at [this](https://docs.flutterflow.io/actions/actions/utilities/upload-data/upload-save-media#adding-upload-save-media-action) documentation and let me know if it works for you?

**Comment by kallolbecs** [comment]
this is happenning with me as well @paulperez-dev . Exactly same issue . any resolution
