### ISSUE TITLE
Custom permission translation (localization) error on iOS because of missing key value

### ISSUE THREAD

**Issue by rpock** [FlutterFlow/flutterflow-issues#2689]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As you know there are some permissions on Android, which are not needed for iOS (p.E. android.permission.INTERNET). So when adding a custom permission only for Android, there is no iOS permission key entered or needed.
 
 
<img width="794" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63868258/ee5b5632-cbfb-4220-910b-6d638a782b54">

There is no problem to add an Android only permission and it is displayed correctly:
<img width="629" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63868258/24daa387-9ffb-4d1e-a35f-c9f4ef216b47">
 
 
 The problem is, that when the app is using multiple languages, the translation key is missing in the InfoPlist.strings file, so that the file get's invalid as you can see on the first line:
<img width="675" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63868258/4dcf165b-19a9-488d-9a16-9c184e261f7e">

### Expected Behavior

Please add a check, when no key value is present, that the localization string is not added to the file to prevent this issue.

### Steps to Reproduce

1.  Create Project
2. Add an additional app language
3. Add a custom permission for Android only with no iOS permission key
4. Generate the code
5. Take a look at the file generated InfoPlist.strings file in the /ios/Runner/[language].lproj/ directory 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekvLqw4t2pbxb0LrxYMcxpwMxJ1gjbJ0vhO1tbw4jfbGuE7MxbuvebVpBQu6oeVZHek6LhkME0+ztjYb+UMApEASEQ5REzbVqdznJfH2QMpfWCLjtfUBCLJlXCX6e0KejgR5CXcxuSU0tig/GSw==

### Context

It's not possible the compile the code because the InfoPlist.strings files are not valid because of the missing key value:

`Error (Xcode): validation failed: Couldn't parse property list because the input data
was in an invalid format
/Users/[user]/Documents/GitHub/[appName]/ios/Runner/pl.lproj/InfoPlist.strings:0:0`

### Visual documentation

See the images above for visual documentation

### Environment

```markdown
- FlutterFlow version: 4.1.38
- Platform: macOS
- Browser name and version: Chrome 123.0.6312.86
- Operating system and version affected: iOS Builds are affected
```

**Comment by bozzoleandro** [comment]
hi @rpock, thanks for your report, we were able to replicate this issue, we're looking into it.
