### ISSUE TITLE
is there possible to upload signature in supabase storage and get path

### ISSUE THREAD

**Issue by darshanavala** [FlutterFlow/flutterflow-issues#2690]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

signature upload option not available with supabase 

### Expected Behavior

i need to upload signature in supabase bucket

### Steps to Reproduce

add signature widget in screen 
try to upload this signature on supabase server

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghufl6otPxeFK0Lrube9WoGAUKUB6U600sdobTRYbIpyuOoYMY/WkVFRoOPWmS2xHMUSmmT8z/+DsuPGTFfBfGxGZftlizKpUEDnvfEWQa5OBEaizPnFCDcZYCkvD06S03RN+XdFhWFoBwDuuI+zLdDDdJLrzIlFISq/LZO4=

### Context

i am trying to upload signature to supabase server

### Visual documentation

![Screenshot 2024-04-05 at 6 00 00 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/131775081/8d084880-f09f-4434-b938-5bd909f19fd0)

### Environment

```markdown
- FlutterFlow version: v4.1.38
- Platform: web
- Browser name and version: chrome 123.0.6312.107
- Operating system and version affected: macos 12.6
```

**Comment by paulperez-dev** [comment]
Hi @darshanavala! This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
