### ISSUE TITLE
Page navigation gets slower and slower until the app crashes (on android)

### ISSUE THREAD

**Issue by rmf11048** [FlutterFlow/flutterflow-issues#2692]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the app I am building, I am noticing that the performance of the navigation between screens degrades as the app is used, up to a point that app actually crashes. This is happening in android, with release APK

### Expected Behavior

Application performance shouldn't be affected by the number of navigations between screens.

### Steps to Reproduce

I created a very simple application composed of 4 screens where each screen includes a component with 4 buttons that allow navigation to each screen. After building the APK, I notice a degradation in performance after each transition. That is noticeable immediately, as the animation doesn't even trigger. After many navigations, each tap in a button will take a 300ms or 400ms to complete. I am running the app in an middle range Android 10 smartphone - Samsung A40.

Public project that reproduces the issue:
[https://app.flutterflow.io/project/navigation-test-cc5rxx](https://app.flutterflow.io/project/navigation-test-cc5rxx)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not applicable

### Context

This issue is affecting me to a point where I am considering whether I should continue building the app in flutter flow, or move to other supplier. The app I am building is an offline field services app and I need top performance in the app.

### Visual documentation

Not applicable

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @rmf11048, thanks for your report. In your configuration, you add the same page multiple times to the page stack. When you navigate from **Page1** to **Page2** and then to **Page1** again, your stack is something like this: 

*Page1 -> Page2 -> Page1*

If you are on **Page2** and want to go to **Page1**, you should [navigate back](https://docs.flutterflow.io/actions/actions/navigation/navigate-back) instead of navigating forward.

Can you please let me know if changing the navigation the performance is not impacted?

**Comment by rmf11048** [comment]
Hey @paulperez-dev 
That solved my problem! thanks a lot.

With this I got to learn about the navigation settings at the Navigate to action.
In my drawer menu of the app I am building, I set all the navigations with the replace route option activated.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/132789882/85f9c8db-6fd3-495e-b57a-4619b51a5be1)
