### ISSUE TITLE
SQLite Database Schema Migration Without Data Loss ?

### ISSUE THREAD

**Issue by ShubhamHande99** [FlutterFlow/flutterflow-issues#2694]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using SQLite to store data locally. Currently, I have a version 1 database in use by the app and I want to change the database schema and upgrade it to version 2.

In Flutter's sqflite database, we have the onUpgrade method to handle schema migration.

How can I achieve this in FlutterFlow Without Data Loss?

### Expected Behavior

As I mentioned, in Flutter, we can use the **onUpgrade** method. Similarly, we need a built-in solution to manage data migration through FlutterFlow. Without this feature, it's a blocker for data migration through the FlutterFlow SQLite database.

### Steps to Reproduce

1.Enable the SQLite feature.
2.Create your database schema and upload the database.db version 1 file.
3.If you want to upgrade your database schema to version 2, there is no option to do this. Additionally, if we upload the database schema version 2 db file directly, we will lose the existing data.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not required.

### Context

How the issue is affecting me:
We require a built-in solution to manage database schema migration through FlutterFlow. Without this feature, it's a blocker for using the FlutterFlow SQLite database.

What I'm trying to accomplish:
When utilizing the SQLite database, we need to have a database schema migration feature. This enables us to make changes in our database schema without losing the existing data

### Visual documentation

Not required.

### Additional Info

Not required.

### Environment

```markdown
- FlutterFlow version: v4.1, 3.19.1
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @ShubhamHande99! This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
