### ISSUE TITLE
Interceptors UI incomplete in Team APIs

### ISSUE THREAD

**Issue by bbeckford** [FlutterFlow/flutterflow-issues#2695]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you add an interceptor to an API Group in a Team API, you can no longer edit that interceptor, it is not surfaced anywhere in the UI.

### Expected Behavior

When an interceptor is created in a team API, I'd expect a panel on the left to link to a list of interceptors that can be clicked and edited.

### Steps to Reproduce

1. Create a new Team API
2. Create a new API Group in the Team API
3. Go to Advanced Group Settings
4. Add an Interceptor
5. Save it
6. You can no longer edit that interceptor, it is not surfaced anywhere in the Team API UI

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kicnf349OsfpE7aqNcu9VhikvJj86UIJJltVuTU40NZjzG7YAQszOSBJaZ+m+Sgo2eGaZ8ToJ+aDFuNzIN/VdC0+VRYBi/81idAzyQl27VKqoDoeCeUZ6EtpKCn6d1KuRmwomIbZuc2Q721+AO+qXQh3cQ77BNWwdQ8mkUbzXjXfuQ0SLb3kNh1JWeC/v

### Context

This has affected my ability to use what looks to be a very useful feature in the way I need to use it.
Team APIs could use some love!

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f2c05442-c459-4032-bfdd-2dd0d83665e1/6c6d6ab8-db68-4902-ad36-bab14b76949d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMmMwNTQ0Mi1jNDU5LTQwMzItYmZkZC0yZGQwZDgzNjY1ZTEvNmM2ZDZhYjgtZGI2OC00OTAyLWFkMzYtYmFiMTRiNzY5NDlkIiwiaWF0IjoxNzEyNzU2OTQ0LCJleHAiOjMzMjgzMzE2OTQ0fQ.m7n2yXcgVUT6UiLt69gH_OZsKRSytP6moA_bT5yO9as)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1 released April 6, 2024
- Platform: Web
- Browser name and version: Chrome Version 123.0.6312.58 (Official Build) (64-bit)
- Operating system and version affected: (desktop) Ubuntu 23.10
```

**Comment by sharmilaccd** [comment]
I have faced the same issue too. Once you add an interceptor to an API Group saved and closed, not able to open or edit it after that!!

**Comment by jondspicer** [comment]
+1

**Comment by paulperez-dev** [comment]
Hi @sharmilaccd, thanks for your report! You can find interceptors under the **Custom Code** page on the left panel.<br><br>Let me know if this helps you!

**Comment by cmikekharris** [comment]
+1

**Comment by bbeckford** [comment]
Hi @paulperez-dev, I actually reported it. 

There is no custom code section when working on a **Team API**.

That's totally where you should add it though 👍

Thanks

**Comment by sharmilaccd** [comment]
> Hi @sharmilaccd, thanks for your report! You can find interceptors under the **Custom Code** page on the left panel.Let me know if this helps you!

@paulperez-dev, this happens when working on a Team API (@bbeckford has explained it with steps in detail) pls refer, thanks

**Comment by paulperez-dev** [comment]
Hi @bbeckford, @sharmilaccd and others. My bad, there is no option to edit an interceptor if it was created in the Team API. <br><br>I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!

**Comment by camopy** [comment]
Hi, was it implemented already? I have 2 projects with more than 30 Team API calls and couldn't find where to edit the interceptors.

**Comment by bbeckford** [comment]
Any word on this yet?
