### ISSUE TITLE
infinite scroll for list of documents passed via parameter or dynamic generated children

### ISSUE THREAD

**Issue by Anyaoha** [FlutterFlow/flutterflow-issues#2697]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The list view has the ability to provide an option for enabling Infinite Scroll while listening for changes (with page size).
But Infinite scroll options are not available for dynamic generated children nor list of documents passed to any other widget aside from a list view (IF THE LIST VIEW IS DIRECTLY BEING QUERIED WITH A QUERY COLLECTION TYPE). This becomes challenging because if a developer tries to pass a parameter a from a Query collection done in a separate page or component into a list view (which GENERATES CHILDREN FROM VARIABLE)

![Screenshot 04-10-2024 09 25 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4b93c968-2798-4775-a074-e5e74a79fa57/3ea909d7-1abe-41b1-9e20-f8babb7b56ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YjkzYzk2OC0yNzk4LTQ3NzUtYTA3NC1lNWU3NGE3OWZhNTcvM2VhOTA5ZDctMWFiZS00MWIxLTllMjAtZjhiYWJiN2I1NmFjIiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.6OrHsSpAg7Xhp9OzaBng10aLaUD6z4OVcFR0x8E1BDE)

![Screenshot 04-10-2024 09 26 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b52173f1-7794-40fb-a09d-373a0dd2702f/165e6643-7723-489e-a9ee-e4b1e4a8d7a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNTIxNzNmMS03Nzk0LTQwZmItYTA5ZC0zNzNhMGRkMjcwMmYvMTY1ZTY2NDMtNzcyMy00ODllLWE5ZWUtZTRiMWU0YThkN2ExIiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.eVLeraDGnJDrdZozOUDFBfk3B8y5YpluziYGJmCbkxs)

### Expected Behavior

The expected behavior is to have an infinite scroll available for list view even if it generates children dynamically.

![Screenshot 04-10-2024 09 25 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4ddf48ca-87de-40f0-a206-d9635aa93a45/11c438c7-b2d7-4968-98be-09891376fda3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZGRmNDhjYS04N2RlLTQwZjAtYTIwNi1kOTYzNWFhOTNhNDUvMTFjNDM4YzctYjJkNy00OTY4LTk4YmUtMDk4OTEzNzZmZGEzIiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.LumFqSv5eOz5MOVxeCd99gI2Sg8byAfkdN7LzDcw4M0)

### Steps to Reproduce

1. In a component, Create a parameter as a list of documents.
2. Add a list view and generate children from variable with the value being the 'list of document'(parameter).
3. In a new page Create a container
4. Create a Query Type from a query collection as list of documents. (THIS IS WHERE INFINITE SCROLL SHOULD BE AVAILABLE to be passed on to the component. But currently, its not)

![Screenshot 04-10-2024 09 26 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2ed9896c-3df7-4984-8d0c-03b85beebe37/fcf7aabe-351c-4077-aea0-1a303526135d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZWQ5ODk2Yy0zZGY3LTQ5ODQtOGQwYy0wM2I4NWJlZWJlMzcvZmNmN2FhYmUtMzUxYy00MDc3LWFlYTAtMWEzMDM1MjYxMzVkIiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.Z-SzN81Me-GivXaale5PozCbujm9bkTlbLBuwfPnUPA)

1. From the container add an Action that show the bottom sheet with the selected component from number 1.
2. pass the value of the parameter (list of document) from the container to the component.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not working as should be.

### Context

The list view has the ability to provide an option for enabling Infinite Scroll while listening for changes (with page size).
But Infinite scroll options are not available for dynamic generated children nor list of documents passed to any other widget aside from a list view (IF THE LIST VIEW IS DIRECTLY BEING QUERIED WITH A QUERY COLLECTION TYPE). This becomes challenging because if a developer tries to pass a parameter a from a Query collection done in a separate page or component into a list view (which GENERATES CHILDREN FROM VARIABLE)

![Screenshot 04-10-2024 09 25 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e2ca1e54-e343-4293-ade6-38b560aaa007/531b04f9-788a-4d95-b406-40a6d6d8aa53?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMmNhMWU1NC1lMzQzLTQyOTMtYWRlNi0zOGI1NjBhYWEwMDcvNTMxYjA0ZjktNzg4YS00ZDk1LWI0MDYtNDBhNmQ2ZDhhYTUzIiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.KlHrw1Dl6HWLS_w38DaoDBLvQHj3qEid1Y8g8SYuirg)

![Screenshot 04-10-2024 09 26 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/58ebc7a9-3270-47a5-b84b-b9849b375031/3864f539-a97e-431f-b761-2c5c24c6effd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81OGViYzdhOS0zMjcwLTQ3YTUtYjg0Yi1iOTg0OWIzNzUwMzEvMzg2NGY1MzktYTk3ZS00MzFmLWI3NjEtMmM1YzI0YzZlZmZkIiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.qL4EZxgjUuc6Y0g6NjSmeObdrJeL1uQ1U9ZTqxi3Xjc)

### Visual documentation

![Screenshot 04-10-2024 09 25 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdee052f-1501-4a47-bf37-6783db5dc915/d144735b-7652-496d-8b7d-dd45f432c5c5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGVlMDUyZi0xNTAxLTRhNDctYmYzNy02NzgzZGI1ZGM5MTUvZDE0NDczNWItNzY1Mi00OTZkLThiN2QtZGQ0NWY0MzJjNWM1IiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ.ecRyKEf6FuVE8Qvi7vwY4khXH7qz-WQG5O40e8QJaJ0)

![Screenshot 04-10-2024 09 26 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a93407bd-0914-49a0-a2c7-e61d31cc6fbf/b6b4be1d-27b6-4fbd-87e2-5cbd253929f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hOTM0MDdiZC0wOTE0LTQ5YTAtYTJjNy1lNjFkMzFjYzZmYmYvYjZiNGJlMWQtMjdiNi00ZmJkLTg3ZTItNWNiZDI1MzkyOWY2IiwiaWF0IjoxNzEyNzc3OTg3LCJleHAiOjMzMjgzMzM3OTg3fQ._wK7-RIJzFYrmRNp5664DfIssQgki8qJghwjUlkah1I)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.38
- Platform: Chrome and FlutterFlow for Windows
- Browser name and version: Chrome and FlutterFlow for Windows
- Operating system and version affected: all
```

**Comment by paulperez-dev** [comment]
Hi Anyaoha! Thanks for your report.<br><br>I will close this issue because is duplicated. This was originally reported on  [https://github.com/FlutterFlow/flutterflow-issues/issues/2692](https://github.com/FlutterFlow/flutterflow-issues/issues/2692)

**Comment by Anyaoha** [comment]
> Hi Anyaoha! Thanks for your report.I will close this issue because is duplicated. This was originally reported on #2692

Hey @paulperez-dev  I don't see the duplicate here as the issue you're referring to is dealing with a different issue than the one I submitted.

**Comment by paulperez-dev** [comment]
Hi @Anyaoha! My bad, I pasted the wrong link. This issue duplicates: [https://github.com/FlutterFlow/flutterflow-issues/issues/2254](https://github.com/FlutterFlow/flutterflow-issues/issues/2254)
