### ISSUE TITLE
Array contains Any - Not working - Compilation error

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#2699]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a query where i have i have put a filter to search for a list of strings from the list of documents in firestore. For this i used Array contains any criteria.
The flutteflow did not show any error. But when i compile the code in my IDE i see that there is an issue with filterArrayContainsAny method.

I am sure, this is a wrong generation of code.

![Screenshot 2024-04-10 at 23 16 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c15d0040-056f-428f-b43b-648e650a4e36/19e616d6-5833-4fd9-9ee1-06501af8ad21?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMTVkMDA0MC0wNTZmLTQyOGYtYjQzYi02NDhlNjUwYTRlMzYvMTllNjE2ZDYtNTgzMy00ZmQ5LTllZTEtMDY1MDFhZjhhZDIxIiwiaWF0IjoxNzEyNzg2ODM2LCJleHAiOjMzMjgzMzQ2ODM2fQ.YPP8sldEQiQvogjDal6TadCVZRsgyLuPHgFybOdzLYc)

![Screenshot 2024-04-10 at 23 04 49](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e02d4ceb-2710-4dee-a379-6eb338dd1f7d/04f68c5a-d1bb-4f0b-b2a2-50eaa021d949?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMDJkNGNlYi0yNzEwLTRkZWUtYTM3OS02ZWIzMzhkZDFmN2QvMDRmNjhjNWEtZDFiYi00ZjBiLWIyYTItNTBlYWEwMjFkOTQ5IiwiaWF0IjoxNzEyNzg2ODM2LCJleHAiOjMzMjgzMzQ2ODM2fQ.5YBWK0qwJQPyInLMjbUbC7nstyDh9w-35oyfUZQpcO0)

![Screenshot 2024-04-10 at 23 04 49](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0ca2df11-db15-45bd-974d-63db30affd16/eb32e439-b09f-44db-bbdf-201445dff80c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wY2EyZGYxMS1kYjE1LTQ1YmQtOTc0ZC02M2RiMzBhZmZkMTYvZWIzMmU0MzktYjA5Zi00NGRiLWJiZGYtMjAxNDQ1ZGZmODBjIiwiaWF0IjoxNzEyNzg2ODM2LCJleHAiOjMzMjgzMzQ2ODM2fQ.-1ACf0whB7hkT8F1kBI8S1Gwd8wI2oqqnssnWY_icDI)

### Expected Behavior

There should not be any compilation errors. The method should be properly generated.

### Steps to Reproduce

1. Setup a query for a collection which has a list of strings.
2. Create a filter which uses - Array contains any criteria and give another list to search for attributes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThcrl25RNsctE+Kn9KuxaqDwWI0MdXZIRmOtvewgjF774OoYUYMjOR1tpTsCzaHx2eVKloHMEzN7qv+HMVsAEaU+cc6ZY1LliYRPPbEyQMsWpDKiBPGt8RPtjBWrA5p+JvRMlJuxtcU0u2zuINee9Fj6Cf9qOYwx5e6fDbOY=

### Context

Query to firestore backend database.

### Visual documentation

![Screenshot 2024-04-10 at 23 04 49](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bb0929cc-3fd4-4607-baa3-4a13244740f5/3c57925c-e784-4235-ac3c-52241f8fed64?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYjA5MjljYy0zZmQ0LTQ2MDctYmFhMy00YTEzMjQ0NzQwZjUvM2M1NzkyNWMtZTc4NC00MjM1LWFjM2MtNTIyNDFmOGZlZDY0IiwiaWF0IjoxNzEyNzg2ODM2LCJleHAiOjMzMjgzMzQ2ODM2fQ.zG1QJcVxAG4l_I3sBYkr-bo6Zn2zDsyFkNq33KDLxHA)

![Screenshot 2024-04-10 at 23 16 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b049bec9-4ca7-4d87-a8cb-b729e99ac9cc/50e4b387-a1ef-4dec-abef-d03838e18ace?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMDQ5YmVjOS00Y2E3LTRkODctYThjYi1iNzI5ZTk5YWM5Y2MvNTBlNGIzODctYTFlZi00ZGVjLWFiZWYtZDAzODM4ZTE4YWNlIiwiaWF0IjoxNzEyNzg2ODM2LCJleHAiOjMzMjgzMzQ2ODM2fQ.OT8IUQJB-r0p4S7WJR6M2qiWm8qlN3nmv9hM9bXA11w)

![Screenshot 2024-04-10 at 23 32 55](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2b3e0dee-6e19-4bc9-9a8a-48b12099d37a/f594fe0e-730d-4c30-bdfe-5fae5327dc59?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYjNlMGRlZS02ZTE5LTRiYzktOWE4YS00OGIxMjA5OWQzN2EvZjU5NGZlMGUtNzMwZC00YzMwLWJkZmUtNWZhZTUzMjdkYzU5IiwiaWF0IjoxNzEyNzg2ODM2LCJleHAiOjMzMjgzMzQ2ODM2fQ.iRIXf8fBvPU0mRZdv8cvgUZELJi6M06QMR88raln0CQ)

### Additional Info

The method filterArrayContainsAny exists in backend.dart. But it is not invoked properly from the querying component. This is a code generation issue

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by task-win** [comment]
For further information, i faced this issue when i used multiple filters with OR criteria. I did not face this when i used AND criteria with the filters in query

**Comment by paulperez-dev** [comment]
Hi @task-win. I was able to reproduce the issue on my end, I will pass it on to the team so they can take a look!

**Comment by glgh** [comment]
I believe the bug was fixed a couple days ago, and I can no longer reproduce it. Closing the issue now - feel free to reopen if the problem persists!
