### ISSUE TITLE
Not able to delete an element from the widget tree

### ISSUE THREAD

**Issue by zerebral** [FlutterFlow/flutterflow-issues#270]
## Expected behavior (required)
The widget must get deleted from the page

## Current behavior
The widget remains on the page and on the widget tree, does not get deleted.

## To Reproduce
1. Log in to my project : https://app.flutterflow.io/project/around-uylr0f
2. Go to page Profile in the directory Profile
3. Open the widget tree
4. Select the widget named "NeedToDeleteThisONE"
5. Right click on it and click on Cut

### Bug Report Code
ITFXl8jfsM5Om9xE0KXUasBojj0wFjMLa+cF0+1+FB40IZOqPe0uZMn8bUNKTMuqS1FAfWagrEYCpK3OiODtJ/I7HyWqQNRyk/UwKlCvHAM=

## Context (required)
Trying to delete an element from the page from the widget tree by right clicking it and clicking on Cut option, but not able to.

## Screenshots / recordings
![Screenshot 2022-12-23 at 2 25 37 PM](https://user-images.githubusercontent.com/6294674/209305578-60b2a875-5f92-45bf-8bd2-5ccc86c3b4e5.png)

## Your environment
* Version of FlutterFlow used: v3.0 Dec 23 2022, Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Mac OS Desktop 
* Browser name and version: Chrome Version 107.0.5304.121 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Mac OS Monterey Version 12.5

**Comment by tothati90** [comment]
Make the widget visible by checking Show in UI Builder then you can delete/edit it.

**Comment by zerebral** [comment]
Works like a charm! Thank you.

One should be able to delete it even without this I guess. I can close this for now as I'm good.
