### ISSUE TITLE
Data Type is not an option for App State

### ISSUE THREAD

**Issue by CClark1720** [FlutterFlow/flutterflow-issues#2700]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Data Type is not an option for App State

![Screenshot 2024-04-11 024016](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e9477365-7ad0-41e6-8a15-a2ff9d0f251d/f9b98538-fd1d-4771-920d-cd6219c0d2d5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lOTQ3NzM2NS03YWQwLTQxZTYtOGExNS1hMmZmOWQwZjI1MWQvZjliOTg1MzgtZmQxZC00NzcxLTkyMGQtY2Q2MjE5YzBkMmQ1IiwiaWF0IjoxNzEyODY1MzkxLCJleHAiOjMzMjgzNDI1MzkxfQ.XO2jB8hLB-tDIPQXnbWFdXfNrjDl2AIZRNEuLvZ8Cmg)

### Expected Behavior

I expected for Data Type to be an option for app state variable

### Steps to Reproduce

Go to App State and see if Data Type an option. Its not showing up on my end.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ysnLuIt1ocNJ1s71bflvoGA5JkR+bedElcFRaCgofePtOol3evXsYlpoXeLhYGxIO0Smml4fzNrRiIaXGMIpBz6CQL06yJBUZjvKRnK6UZOBDbuSRHR5O/1TfH6k36SskAhNHPZZV1Fh7zqEOu68TjbtHbrAIndISq/LZO4=

### Context

I'm trying to call a custom function that is using a dataType

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9905dae8-90df-471c-a699-16c6e459e687/4c28d2ed-3049-47f3-889f-1abb4ec32119?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OTA1ZGFlOC05MGRmLTQ3MWMtYTY5OS0xNmM2ZTQ1OWU2ODcvNGMyOGQyZWQtMzA0OS00N2YzLTg4OWYtMWFiYjRlYzMyMTE5IiwiaWF0IjoxNzEyODY1MzkxLCJleHAiOjMzMjgzNDI1MzkxfQ.6ws3G-9g35ThymCKhGZ8t1nXnL4rDTMsEoLpNoltzKw)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 5, 2024
- Platform: Web
- Browser name and version: Chrome Version 123.0.6312.106
- Operating system and version affected: desktop Windows 11 Pro 22621.1702
```

**Comment by CClark1720** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/ebdf7893-2053-41f8-b9b5-887873a33324)

**Comment by paulperez-dev** [comment]
Hi @CClark1720, thanks for your report! I was trying to replicate it on a blank project so we could better isolate the issue with the component, but I was unable to do so. It is working well on my end.

<br>Are you able to reproduce this issue on a blank project? if so, could you please share the bug report code of that blank project?<br>It would help us a lot, so we can discard project-specific issues and better isolate the problem with the dropdown.

**Comment by CClark1720** [comment]
i was able to fix the issue. Enable deep linking fixed the issue.

**Comment by paulperez-dev** [comment]
Thanks for your confirmation!
