### ISSUE TITLE
Supabase Query Optional Filter

### ISSUE THREAD

**Issue by leobewater** [FlutterFlow/flutterflow-issues#2701]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a dropdown and a list view, I want to optionally filter the list view based on the selected dropdown option. But by default I want to show all items without any filter. It seems like there is an options for Firebase, but none for Supabase.

### Expected Behavior

Expect to either have condition options for filters or provide a similar option like Firebase.

### Steps to Reproduce

1. Create new Page
2. Add a dropdown with "All", "student", "vip"
3. Add a List view and set with Supabase Query
4. Select filters

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi8rl8Y1grt9c7a6JbMExnjwWCDs7bYIRicB+GSs8GqLuPe0UWMzBUBFUOcild1Fqek79jXMX/MqMv4TfU8YnCAqsbpRTzroJTjqUUnqhR6awEq63b2h6QMZjI0yG18PQnAlAWc5iL1Fn6meEJPCUa3LcQ67aO0cSRuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I'm still trying to find a way to solve this issue.

### Visual documentation

none

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.38
- Platform: MacOS Desktop
- Browser name and version: Local Iphone15 Simulator
- Operating system and version affected: All
```

**Comment by paulperez-dev** [comment]
Hi @leobewater! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue and the steps to reproduce are not detailed enough. Can you share some images pointing to the missing feature? With this information, I will raise a feature request to the team.

**Comment by paulperez-dev** [comment]
Closing this issue since we have not heard back
