### ISSUE TITLE
Compile error on generated code from FlutterFlow,  for programmer-defined Data Types

### ISSUE THREAD

**Issue by chrisatwyrth** [FlutterFlow/flutterflow-issues#2702]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The code generated by FlutterFlow for `createRouter(AppStateNotifier appStateNotifier)` in flutter_flow/nav/nav.dart has a compile error.

I am passing my own values of some of my data types as parameters to pages.

See my project Wyrth V6.

These become compiled into calls to `params.getParam(...)`,  indicating a `ParamType.DataStruct`, such as:
```
 FFRoute(
              name: 'funding_market_match_1',
              path: 'fundingMarketMatch1',
              builder: (context, params) => FundingMarketMatch1Widget(
                giftProgram: params.getParam(
                  'giftProgram',
                  ParamType.DataStruct,
                  false,
                  GiftProgramAPITypeStruct.fromSerializableMap,
                ),
                matchProgram: params.getParam(
                  'matchProgram',
                  ParamType.DataStruct,
                  false,
                  MatchingProgramAPITypeStruct.fromSerializableMap,
                ),
              ),
            ),
```
where in this example,  both `giftProgram` and `matchProgram` are data types which I defined,  using the Flutterflow UI builder.

However:: `params.getParam(...)` has a signature of:
```
 dynamic getParam<T>(
    String paramName,
    ParamType type, [
    bool isList = false,
    List<String>? collectionNamePath,
    StructBuilder<T>? structBuilder,
  ]) {
```
-- in particular it expects a `collectionNamePath`, possibly null.  

But:: the calls above are MISSING this argument!!!  They have 4 parameters,  not 5!   Which leads to a Dart compile error.....

If the generated code is amended to:
```
 FFRoute(
              name: 'funding_market_match_1',
              path: 'fundingMarketMatch1',
              builder: (context, params) => FundingMarketMatch1Widget(
                giftProgram: params.getParam(
                  'giftProgram',
                  ParamType.DataStruct,
                  false,
                  null,   // INSERT MISSING PARAMETER
                  GiftProgramAPITypeStruct.fromSerializableMap,
                ),
                matchProgram: params.getParam(
                  'matchProgram',
                  ParamType.DataStruct,
                  false,
                  null,   // INSERT MISSING PARAMETER
                  MatchingProgramAPITypeStruct.fromSerializableMap,
                ),
              ),
            ),
```
then the code compiles without error,  and seems to work fine (for my case).

Very curiously,  if you have a project which does not use FireStore,  then the signature of `params.getParam(...)` does NOT have `collectionNamePath` -- and so the calls above to `params.getParam(...)`  would work ---- i.e.  the error does not appear in projects which do not use Firebase...

I then tried creating a new simple project using Firebase,  but even then the signature of `params.getParam(...)` does not have `collectionNamePath`.  

So unfortunately,  I have not been able to recreate the issue with a simpler version of my own code (in my project Wyrth-v6). 

I am unsure what scenario causes Flutterflow to generate `collectionNamePath` in the signature of `params.getParam` -- and,  in my case,   manually inserting `null` for that parameter then seems to solve the problem.

### Expected Behavior

No compile errors in the generated code.

### Steps to Reproduce

1. Create a datatype
2. Create a page which expects as a page parameter a value of that data type
3. The compile error _may_ then appear in `nav.dart`
4. As I explained above,  it seems to be related to configuring use of Firebase;  and then only for complex projects,  rather than a simple test project using Firebase.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzM7qw89NtbwC+pSJL8Bvp2IWHEccTIMziNZ+exUbfaL1BqQqfvfCSFtWTteoaVNcGVL/gloKwcLRiOGSVPYpIQ2rfbZlzcxuZgzee2iVWq6tPpagbUFAO+5mCkC11KS3pxZ/AMt1ZV41w02EPNm/fB3DFOu/Zwh9f6PHaOI=

### Context

I am manually repairing the faulty generated code -- so overall,  the issue is a nuisance,  but has not stopped me working..

### Visual documentation

<img width="537" alt="Screenshot 2024-04-11 at 15 52 33" src="https://github.com/FlutterFlow/flutterflow-issues/assets/115186365/8c302f2b-2b6b-4518-8a80-8b1951dca984">

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: iOS
- Browser name and version: Version 123.0.6312.107
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by chrisatwyrth** [comment]
Much appreciated Paul!

**Comment by victoriahuang1** [comment]
Hi @chrisatwyrth, it looks like the code is generating fine now. Can you confirm if it is working for you now?
