### ISSUE TITLE
Custom Widget does not update nor refresh

### ISSUE THREAD

**Issue by dmslabsbr** [FlutterFlow/flutterflow-issues#2703]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a Custom Widget that is drawn on the screen normally with the given parameters.

When I change the month or year it correctly calls the callback and updates the variables that I defined to be updated.

However, when I change the a parameter value, in this case, using action "update page state" or "update app state" and request "rebuild current page", flutterflow does not call the widget again.

I´v created a mini app to test the Widget

[https://app.flutterflow.io/project/exemplo-tmp-y4plrf](https://app.flutterflow.io/project/exemplo-tmp-y4plrf)

At mode “preview widget” it works without problems. But that's because every time a parameter is changed it starts the widget from scratch.

Other users are having the same problem - [https://community.flutterflow.io/ask-the-community/post/custom-widget-does-not-update-nor-refresh-ldFtdVcvNnldOzI?highlight=pIByoLK1wENOrDT](https://community.flutterflow.io/ask-the-community/post/custom-widget-does-not-update-nor-refresh-ldFtdVcvNnldOzI?highlight=pIByoLK1wENOrDT)

### Expected Behavior

When changing one of the variables used to initialize the custom widget and giving the command to redraw the screen, my widget should be redrawn using the new parameters.

### Steps to Reproduce

1. Open my test project [https://app.flutterflow.io/project/exemplo-tmp-y4plrf](https://app.flutterflow.io/project/exemplo-tmp-y4plrf)

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/e99aa5aa-ac0d-4fad-9e47-4c4924f13670

2. Run app in 'Test Mode" and test it.
   a) the Widget appears to work normally.

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/b741fbed-6bca-4d10-8518-b2964d87534a

  b) But when I change one of the variables that should redraw the widget, nothing happens.

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/cb7b26be-e159-4282-8a7c-da381c380a2d

3. But, in preview mode when editing the widget, everything works as expected.

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/67984c19-ae4e-46d4-9782-3f3fcd75d0f8

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk87134tPsfVG+KXqbcBB/WU7OUg8argkscp/bxIgGIDzPOw+ZPWlbVptOObnY3w3O0SmmmEE/sLXvYTuUMcnHz+rG4Rd/5BIVgnMRnOnQZOBCJOCVWtQEflUfUiv58K4nh1/IbNvV3A12WCQGefKYBLbQZv4ImdISq/LZO4=

### Context

This issue has affected me by hindering the functionality of my Custom Widget within FlutterFlow. I'm trying to create dynamic updates to the Custom Widget based on changes in its parameters. However, despite correctly updating the parameters, the widget doesn't refresh or update as expected when using actions like "update page state" or "update app state" in FlutterFlow.

In summary, this issue with the Custom Widget not updating or refreshing as expected in FlutterFlow is impeding my progress in creating a dynamic and responsive user interface. I'm seeking a resolution to ensure that changes to the widget's parameters trigger the necessary updates and rebuilds, ultimately enabling me to achieve the desired functionality within my app.

### Visual documentation

 a) the Widget appears to work normally.

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/b741fbed-6bca-4d10-8518-b2964d87534a

  b) But when I change one of the variables that should redraw the widget, nothing happens.

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/cb7b26be-e159-4282-8a7c-da381c380a2d

3. But, in preview mode when editing the widget, everything works as expected.

https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/67984c19-ae4e-46d4-9782-3f3fcd75d0f8

### Environment

```markdown
- FlutterFlow version: 4.1 - Flutter 3.19.1
- Platform: WEB
- Browser name and version: Google Chrome Versão 123.0.6312.106 (Versão oficial) 64 bits
- Operating system and version affected: Microsoft Windows [versão 10.0.19045.3693] Microsoft Windows 10 Pro for Workstations
```

**Comment by paulperez-dev** [comment]
Hi @dmslabsbr, thanks for your report. You need to pass a new date variable to your widget (reading it from the state) so it shows the selected date.<br><br>Can you please try this approach and let me know if it worked?

**Comment by dmslabsbr** [comment]
Now it is working. It was a new newbee error.   I just put my function and checks into the build method.
