### ISSUE TITLE
uploading images not working in web 

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#2704]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upload images not working in web which was working previously. File picker not working

### Expected Behavior

File Picker Shall

![Screenshot 2024-04-12 at 12 15 43 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1231e1d4-5c86-42e0-9a3b-7293519b3bee/9a53a8b0-c9fd-4205-88d3-57d80f16878a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMjMxZTFkNC01Yzg2LTQyZTAtOWEzYi03MjkzNTE5YjNiZWUvOWE1M2E4YjAtYzlmZC00MjA1LTg4ZDMtNTdkODBmMTY4NzhhIiwiaWF0IjoxNzEyODY0OTM1LCJleHAiOjMzMjgzNDI0OTM1fQ.RdxC4bswFyosdLok40Osf_hND0vLAI2F6olEPjbH1WQ "=659x")

### Steps to Reproduce

Upload image Action Not working Create a button and add upload Image Acion on it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CiMjfsIh2rscA0a6Jd/panjwRQ0x6RYEwm8BuaxIjJ5PRDYl3Z/ekUERvYOHgTHNif1qZnWoW0cLFifzpLMYnE0maRaY5zZBiZQGWcDmlVcWhFJWgR0ZSP8RbGGqzy5mNhhFvB/puWUJhwF6ELvKtdBHsHrr6PlQsDq/LZO4=

### Context

Image Upload

### Visual documentation

Not Available

### Additional Info

FlutterFlow v4.1.38
Flutter version is 3.19.1

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @Mdmuzammil16, thanks for your report! A tool tip hides the log in the image you shared. Can you please re-upload the it where all the text is visible?

**Comment by Mdmuzammil16** [comment]
<img width="663" alt="Screenshot 2024-04-12 at 5 58 23 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/56119343/a48f71e5-7af5-43ad-a129-5625adde1845">

**Comment by Mdmuzammil16** [comment]
main.dart.js:4498 Uncaught Unsupported operation: The Permission.photos permission is currently not supported on web.

**Comment by Mdmuzammil16** [comment]
Hey do we have any update?

**Comment by paulperez-dev** [comment]
I'm going to close this issue since we have not heard back
