### ISSUE TITLE
Application Fails to Launch on Mac OS X 10.15.7

### ISSUE THREAD

**Issue by Marakase12** [FlutterFlow/flutterflow-issues#2706]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attempting to open the application on Mac OS X 10.15.7 results in no response. The application does not launch, nor does it display any error messages.

### Expected Behavior

I expected the application to launch successfully and operate normally on Mac OS X 10.15.7.

### Steps to Reproduce

1. Attempt to open the application on Mac OS X 10.15.7.
2. Observe the lack of any system reaction or error messages.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no

### Context

Unable to perform necessary tasks within the application due to its inability to launch on my current operating system.

### Visual documentation

no

### Additional Info

no

### Environment

```markdown
- FlutterFlow version: _(specify the version if known)_
- Platform: Web
- Browser name and version: _(specify your browser and version)_
- Operating system and version affected: Mac OS X 10.15.7
```

**Comment by Marakase12** [comment]
pls, fix

**Comment by paulperez-dev** [comment]
Hi @Marakase12, thanks for you report. I'm closing this issue as a duplicate in favor of already resolved => [https://github.com/FlutterFlow/flutterflow-issues/issues/2178](https://github.com/FlutterFlow/flutterflow-issues/issues/2178). <br><br>Please make sure to update to the latest version of MacOS.
