### ISSUE TITLE
Issue with Facebook Authentication in Web Application

### ISSUE THREAD

**Issue by flutterflowdevs** [FlutterFlow/flutterflow-issues#2709]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on the "Login with Facebook" button in my web application, nothing happens. There are no errors displayed in the browser console or network logs. 

### Expected Behavior

When i click on the "Login with Facebook" button in my web application, I should see Facebook authentication pop up and I should be logged in to my app.

### Steps to Reproduce

1. Create a Flutterflow Project and Integrate the Facebook Authentication with the help of Flutterflow Documentation.
2. Deployed the Flutterflow Project on Flutterflow Web Publishing.
3. Run the project and click on "Login with Facebook" button where you have added the Facebook Authentication action.
4. Nothing happen and there are no errors displayed in the browser console or network logs. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ol8nf/Y9Itbxd7ar2dcEw9SI5Jkx+bZIVju1HcwggfZyuP4l/euHBYk5BTfG9T0NHGVKgnjs006HKhIfEV/knFxeCGaU/3JVqdw6XfHqmRYyKOpeWSn9CJJhgN2XE156rvwhGA+FeSVYQ3GeMJuzLYAHaQrLADlUjOciaVYHMj3C9AB7dKiBJxQ4XEx7eTI5ODEz25eKMrop5yfj/0w==

### Context

Because of this issue, i am unable to login via Facebook Authentication.

### Visual documentation

<img width="1911" alt="Screenshot 2024-04-12 at 6 53 49 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126557523/8186660f-3f13-417b-a01e-eb1064650e48">

### Environment

```markdown
Flutterflow Version: v4.1-Flutter 3.19.1
Platform: Web
Browser name and version: Chrome and Version 123.0.6312.107 (Official Build) (x86_64)
Operating System and version affected: MacBook Pro
```

**Comment by paulperez-dev** [comment]
Hi @flutterflowdevs! Thanks for your report. I noticed a misconfiguration in your project, specifically on step 7 (create account instead of login). Can you please review the [documentation](https://docs.flutterflow.io/data-and-backend/firebase/authentication/facebook-sign-in#5.-enabling-facebook-authentication-in-flutterflow) and adjust your project? 

Please, let me know if this can help you!

**Comment by flutterflowdevs** [comment]
@paulperez-dev 
I have configured with both login and create account at step 7, but the problem stay same.

**Comment by paulperez-dev** [comment]
@flutterflowdevs sorry if I was unclear, I meant you selected to create an account instead of login. Can you please make this change and try again?

**Comment by flutterflowdevs** [comment]
@paulperez-dev 
Initially, I configured with the 'Create Account' and tested it, but nothing happen. Subsequently, I configured with the 'Login', but the error remains same.

**Comment by paulperez-dev** [comment]
Hi @flutterflowdevs, thanks for your confirmation. I will send this to the ENG team, so they can take a look.

**Comment by yokawaiik** [comment]
I confirm the problem.
The Facebook login integration does not work in the Android app either. It's likely the same with iOS.

The setup was done according to the instructions from the documentation.

Maybe there is someone who solved this problem? It is possible that some other points are not mentioned in the documentation or that there was an update from Facebook that the FF team does not know about.

**Comment by yokawaiik** [comment]
It turns out that the whole point is that if, for example, authorization with Google was previously completed, and then the user tries to authorize with Facebook, and this Facebook is connected to the Google mail for which authorization was previously made, then Firebase throws an error

```
firebase_auth/account-exists-with-different-credential
```

FF out of the box does not handle this exception and puts the error in the default Authorization error and reports it via snackBar. This may not be clear to the user, so now the error is normally thrown and displayed to the user:


I decided the problem with custom code.

<details><summary>The solution to this problem</summary>
<p>

Added into kTranslationsMap (internationalization.dart)

```
'account-exists-with-different-credential': {
      'en':
          'An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.',
      'YOUR CUSTOM LANGUAGEE':
          'CUSTOM DESCRIPTION',
    },
```

Update FirebaseAuthException body (firebase_auth_manager.dart)

```
  /// Tries to sign in or create an account using Firebase Auth.
  /// Returns the User object if sign in was successful.
  Future<BaseAuthUser?> _signInOrCreateAccount(
    BuildContext context,
    Future<UserCredential?> Function() signInFunc,
    String authProvider,
  ) async {
    try {
      final userCredential = await signInFunc();
      if (userCredential?.user != null) {
        await maybeCreateUser(userCredential!.user!);
      }
      return userCredential == null
          ? null
          : OutAndAboutFirebaseUser.fromUserCredential(userCredential);
    } on FirebaseAuthException catch (e) {
      debugPrint('-- FirebaseAuthException - error: $e');
      final errorMsg = switch (e.code) {
        'email-already-in-use' => FFLocalizations.of(context).getText(
            'mcap8i1h' /* Email already in use by anothe... */,
          ),
        // LINK TO YOUR CUSTOM DESCRIPTION
        'account-exists-with-different-credential' =>
          FFLocalizations.of(context).getText(
            'account-exists-with-different-credential',
          ),
        'INVALID_LOGIN_CREDENTIALS' =>
          'Error: The supplied auth credential is incorrect, malformed or has expired',
        _ => FFLocalizations.of(context).getText(
            'sz7qtz9f' /* Authorization error. */,
          ),
      };
      ScaffoldMessenger.of(context).hideCurrentSnackBar();
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(errorMsg)),
      );
      return null;
    } catch (e) {
      debugPrint('-- _signInOrCreateAccount - error: $e');
      return null;
    }
  }
```

</p>
</details>

**Comment by paulperez-dev** [comment]
Hi @flutterflowdevs! Sorry for the late response. The team looked into this and Facebook is working fine. Can you please verify all the steps from the [facebook documentation](https://docs.flutterflow.io/data-and-backend/firebase/authentication/facebook-sign-in#adding-facebook-sign-in)?<br><br>Also, you may be facing the same issue as yokawaiik, take a look at the previous response.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by kokosmedia** [comment]
@flutterflowdevs did you manage to solve this problem? I have the same situation as you - the Facebook login button does not respond at all - there is nothing in the console, no errors and I don't know how to deal with it.

**Comment by 00Rushabh00** [comment]
This issue still persists and flutterflow devs continue to ignore it.

**Comment by 00Rushabh00** [comment]
@paulperez-dev please have a look at this as Facebook login is very important for my webapp.
