### ISSUE TITLE
Unable to clear AppState with DateTime value

### ISSUE THREAD

**Issue by leobewater** [FlutterFlow/flutterflow-issues#2710]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a date is selected from a DatePicker, it updates the AppState variable. Initially the DateTime AppState variable is null. I added an icon clear button with an action to "Update App State" -> "Clear Value" but it keeps throwing the "Null check operator used on a null value" error. I also tried adding a condition to only clear the value only when it's set, but still not working.

### Expected Behavior

Clear the Datetime AppState variable to null without any errors.

### Steps to Reproduce

1. Create a new page
2. Create an AppState variable with DateTime type
3. Add a button on the page and set the action to DatePicker then chain another action to Set the "Date Picked" value to the App State.
4. Add an icon button and set the action to "Update App State" -> "Clear Value" for the AppState variable.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi8rl8Y1grt9c7a6JbMExnjwWCDs7bYIRicB+GSs8f7b0POxzTMnOVBJuOLC0SlFYfFr9jmIKzPPemvPPEMcDMgeeGrlz1LhIaRbwXkSXbpi4CpeeY25/AtJgIH6H4LSNoRNCWLNvdGA+31+mfeitdz7tCbrKO0YROsqLNZOK2SrDX1iXc2URm05KZDPz

### Context

I can't launch my app without clearing the DatePicked or AppState with DateTime value

### Visual documentation

none

### Environment

```markdown
- FlutterFlow version: v4.1.39
- Platform: Mac OS
- Browser name and version: Iphone 15 Pro max simulator
- Operating system and version affected:  all
```

**Comment by rzambroni** [comment]
Hi @leobewater, I attempted to replicate your issue but it seems to be working fine on my end (blank-project). Also when trying to replicate in the project you provided i couldn't find the DateTime AppState variable you were using. Would you mind sharing a blank-project example where you can replicate this? it would really help us isolate and identify the issue you are seeing.  Thanks!

**Comment by leobewater** [comment]
It turns out my custom function was causing the error message. Sorry for the confusion. Please close this ticket.

**Comment by rzambroni** [comment]
I'm glad you were able to solve it. Thanks for letting us know.
