### ISSUE TITLE
Code editor in FlutterFlow Windows desktop App is unusable

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#2711]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've recently installed FlutterFlow Windows desktop App and was quite disapointed in the functionality of the code editor. Neither code completion nor even basic things like Ctrl+Z work. 

### Expected Behavior

Code editor has at least the same functionality as it has in the web version of FF.

### Steps to Reproduce

1. Create custom code (widget, action).
2. Start writing code and you'll immediately experience all the issues.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wksmB34p2sdtJ14SJb+9V+CQvIjs9RL8VkdYbdCs8JJToPLAUZ8zBM05vZrykdwlqOE38kn8z/PfqieHpO/k6MgWcbKpZ1qpcSQ2UXn6gRJCuO6qVfW1SM/1MCmKj58Oz3B1+PtNeWnwb7WWUI/O9cBLDCZe2NUQvR8mLJdeK2SrDX1iXc2URm05KZDPz

### Context

I'm almost unable to write code in the desktop version of FF. I need either switch to web version or use Android studio and the copy the code to FF.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/56697c3a-eaf0-47d8-96b5-52fa22423b08)
Just a screenshot of the code editor

### Environment

```markdown
- FlutterFlow version:FlutterFlow v4.1.39+
- Platform: Windows
- Browser name and version:
- Operating system and version affected:  Windows 10
```

**Comment by leighajarett** [comment]
Thanks for filing this feedback. This is a known problem and we're working on redoing the custom code editing experience, please stay tuned for more updates!
