### ISSUE TITLE
Code library, custom widget/function/actions  and custom DataTypes, Documents and Document References, etc

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#2712]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Team Code library allows defining a custom widget.  When creating a parameter for the method or actions to be passed in, the UII allows selecting **DocumentReference**,**Document**, **Data Type**, **Enum**. and **SQLLite Row**. All of these are custom configurations that are unavailable in the Team Code library and are unable to be set.  

### Expected Behavior

There are several possible expected behaviors:

1. Do not allow these options to be selected until they are supported in the Team Code library in full.
2. Support these options in the Team Code library in full.
3. Support specifying a dynamic reference/type for these items and allowing the developer to take the risk of an exception.

### Steps to Reproduce

1. Create a new "Team Code Library"
2. Click Add
3. Choose Function or Widget
4. Click Add Parameters
5. Attempt to Select a **DocumentReference**,**Document**, **Data Type**, **Enum**. or **SQLLite Row**.
6. See the inability to choose the "type"

OR

Go to Settings for the Team code library.

See the inability to define any of the above.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

This is a bug in the application design, not in code.

### Context

I am trying to create a custom reusable widget with custom data types used by my application across multiple projects.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6088906/e0826db2-89da-4051-80e0-70381c6a3b42)

### Environment

```markdown
- FlutterFlow version: 4.1.38+
- Platform: web/desktop
- Browser name and version: all browsers
- Operating system and version affected: Windows / Mac OS
```

**Comment by rzambroni** [comment]
Hey @jonl-percsolutions-com,

Thanks a lot for the report, I was able to confirm this problem and will reach out to the team to define what's the best path forward.

Will keep you posted here.

**Comment by leighajarett** [comment]
Hi there! Leigha here from the product team. Thanks for flagging this issue - this is a known limitation, sorry it's holding you up. We have some stuff we're working on as part of our roadmap that will solve the problem they're running into. Stay tuned for more updates soon!
