### ISSUE TITLE
Window too small error message causes reload on resolution and loses changes

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#2713]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When resizing the page and the window gets too small, FlutterFlow displays the "Window too small" error message.  When re-expanding the window to not be too small, the whole application is reloaded and reset, which causes possible unsaved changes to be lost.

### Expected Behavior

Two possible expectations:

1. No "window is too small error" at all.  Resize gracefully, set minimum sizes of things and cut off or scroll the views as appropriate according to the minimum sizing
2. Keep the error, but show it as an overlay when the window is too small and the application is not reloaded so changes that may be in progress are not lost.

### Steps to Reproduce

1. create a custom widget or function that has to be saved.
2. write something in it
3. make the window small enough to trigger the window too small error
4. expand the window to remove the error
5. see the app reload and any unsaved changes are gone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Application issue

### Context

I just lost about an hours worth of work because I accidentally resized the window too small when moving it to look at something else.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/6088906/cc5dd142-554a-4655-8b8f-4c7d60342a66

### Additional Info

The IDE losing work is a completely unacceptable thing, especially for something that is supposed to reduce the amount ofwork.

### Environment

```markdown
- FlutterFlow version: 4.1.39
- Platform: Desktop and Web
- Browser name and version: all browsers
- Operating system and version affected: Windows / MacOS
```

**Comment by paulperez-dev** [comment]
Hi @joni-percsolutions-com, thanks for your report! I was able to reproduce the issue. I will pass it on to the team so they can take a look.
