### ISSUE TITLE
Null values are converted to 0 for double data types

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2714]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Data type double fields set a value of 0 when in reality they are receiving a null value.

This does not happen with other variables, such as when creating a page state of type double and assigning it the value null, it will retain that null value.

### Expected Behavior

In both cases the null value should be respected and not assigned a value of 0

### Steps to Reproduce

1. In a blank project, we create a datatype with a double field
2. We create a separate page state double on our main page
3. We create an app state with the datatype we created in step 1
4. We configure an action on a button. In this action, we assign null values to the page state and the app state. (this could be done in many other ways)
5. We carry out "is set" conditions for each one
6. Then an information dialog is shown, if it is TRUE the value is shown and if it is FALSE a message "Not set" is shown
7. We add some texts to show the value of the variables
8. the double of the app state is set to the value 0.
9. The double page state will not be set, as it has a NULL value

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITwgis/l8YxgrtdY1rXude9ajikXQ0A8U4JNltVuZ0ggF4irPZkQdeHBVFRoXc+hdGg/I2H8sDoyw6zLkuztDMY4IQiKTNVI/6VqEjqVIW2WRpiJOqqBOEdQFspEC2Kf4ZiCniRDD7BiR1IS2l73Cu+ufADvJYzBJGgNHM+HA5DXpHfgHCPdJyJW3SsMHnWvCsgTLAiho5PR0uoug5KMuYl8qBVXzoPSwtX1TBKTWVk=

### Context

This error arose when viewing the values that a slider received. The test failed because the double value it should display was null, but it saved it as a 0, causing it to fail due to the minimum value that was configured for the slider.

We also encountered the problem in the double text fields that showed a 0 when its column in the database was NULL

### Visual documentation

https://www.loom.com/share/6f54a57394e24a4d89a337e42e88642c

### Additional Info

Issue related:
https://github.com/FlutterFlow/flutterflow-issues/issues/2669

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404, thank you for your report. I was able to replicate the issue you are describing. I will send it over to the team so they can take a look.

**Comment by paulperez-dev** [comment]
Hi @Franco98404, we changed the status to `Won't do` because unfortunately, we do not have support for nullable fields in Data Types (this is true of all Data Type fields, not just doubles). However, you can achieve the desired behavior by using the `Has Field` option for the field of interest. This should allow you to detect when the field has been set/not and you can then use this logic in your app accordingly. 

I hope this helps you!
