### ISSUE TITLE
Inconsistent behavior with a NULL initial value of a slider

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2715]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a slider with a minimum value greater than 0 and setting null as the initial value, the following happens:

* In the test, upon receiving the value 0, an error occurs since it is outside the allowed range.
* In the deployment, this error is not detected and everything is displayed without problems. This behavior is incorrect since despite being outside the allowed range, it is displayed anyway.

### Expected Behavior

It should throw an error in both the test and the deployment as it is not within the range.

### Steps to Reproduce

1. Add a slider and set a minimum value greater than 0
2. Set the initial value to null and the default value to 0.
3. Make a deployment and run a test
4. In the test we will get an error and in the deployment we will not

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ois/l8Yxgod9G0KryavlR/WIsJnJ+U4ZN08EaUUoYfI/NGu4MPsneVFRuZryqTHx6eGKZ+TgKxvfqjuHXIPcpGzuef6ZCzZB+EgHxRkGRRaaUPM6JfW1QJ5tmN2mP3ImFohV+IthhSCEDwF62GeiAdArUJbn7OGsvGeW1LdeK2SrDX1iXc2URm05KZDPz

### Context

We encountered this error when trying to use a slider with our appstate. This value in the appstate we used the first time would always be NULL in the database since the user must assign a value to it. This is how we noticed that in our tests it failed but in the deploy it did not.

[Null values are converted to 0 for double data types #2714](https://github.com/FlutterFlow/flutterflow-issues/issues/2714)

### Visual documentation

[https://www.loom.com/share/fd1f472e0ee24883bcae429bfcf68c87](https://www.loom.com/share/fd1f472e0ee24883bcae429bfcf68c87)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404, thanks for your report! I was able to confirm this problem and will reach out to the team so they can fix it.

**Comment by paulperez-dev** [comment]
Hi @Franco98404! Assertions are disabled in release mode, so the error is not shown when you deploy. Closing this since it isn't a bug.

Reference: [https://docs.flutter.dev/testing/build-modes#release](https://docs.flutter.dev/testing/build-modes#release)

**Comment by Franco98404** [comment]
> Hi @Franco98404! Assertions are disabled in release mode, so the error is not shown when you deploy. Closing this since it isn't a bug.
> 
> Reference: https://docs.flutter.dev/testing/build-modes#release

@paulperez-dev Thanks for clarifying!
