### ISSUE TITLE
Swipeable stack: Removing 2nd to last item breaks list when looping

### ISSUE THREAD

**Issue by captainjdi** [FlutterFlow/flutterflow-issues#2716]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using the Swipeable stack widget with loop turned on. On a left swipe, I'd like to remove the current index item from the list. That works for all items except the second-to-last item. When the second-to-last item is deleted, the image turns grey and the swipeable stack experience breaks. 

It seems that the loop feature is smart enough to return to the start of the list when the last item is deleted, but when the second to last item is deleted, it shifts the index numbers in a way that leaves the swipeable stack unable to find the next item. This seems to be causing the break (although maybe I'm misinterpreting what I see). 

As a side note, is it possible to return the current item index on a swipe action? I can't seem to get that to work. 

### Expected Behavior

After deleting the second-to-last item in a stack with the loop feature enabled, I would expect to either see the last item in the stack, or for the loop to restart the stack and go back to the beginning. Either works, as long as it doesn't break. 

### Steps to Reproduce

1. Create a new page
2. Add Swipeable stack
3. Add an image to the swipeable stack where children items will live
4. Create an app state variable for an image path list
5. Add at least 4 image items to the image path list
6. Set the swipeable stack generating children area to the app state variable you created
7. Set the image in the swipeable stack to be from the generating children variable
8. Set the left swipe action update app state | select app state variable with image path | Select "Remove from list" update type | Remove the current index item 
9. NOTE: At this point, running in Test Mode and publishing to iOS device have two different results. In Test Mode, things seem to momentarily break when swiping left on the last item, but then it corrects itself. In iOS, it breaks when swiping left on the second-to-last item and doesn't correct itself. See attached videos for examples of each. It would be great if the behavior could be the same in each environment as part of this bug fix. 

https://github.com/FlutterFlow/flutterflow-issues/assets/133725139/eed3a64f-fa04-4e55-808e-7eb71371a760

https://github.com/FlutterFlow/flutterflow-issues/assets/133725139/07d3f132-f59a-4ffb-81c4-db7aceeca134

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40icn65YtPvttK+KqJb8FvmmU5JlgiUK8Viu57aCAsfL7uPZkQZ/T7fk5ZOde6dwl6L0yWkj8fwPDOkezAA+UqYU2Bb4RjyJBuaDnMLXGQVranC5C0WnZfP9FJJVy607e7sxRSOvV1ZVoH12eINd69VnHAGZDzOlQjBv6jIq7+nV2pQ0SLb3kNh1JWeC/v

### Context

I'm trying to remove items from a list while swiping without users running into a breaking issue. This is a P0, highly critical item for me. I've tried several workarounds, but I can't get anything to get around it. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/133725139/eed3a64f-fa04-4e55-808e-7eb71371a760

https://github.com/FlutterFlow/flutterflow-issues/assets/133725139/07d3f132-f59a-4ffb-81c4-db7aceeca134

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.39
Flutter version is 3.19.1
- Platform: iOS 
- Browser name and version: Chrome
- Operating system and version affected: iOS
```

**Comment by captainjdi** [comment]
UPDATE: While this is still an issue when using the Loop attribute, I found a workaround. Instead of removing items on a left swipe, I'm now appending them on a right swipe to the end of the list and not using the loop attribute. This gives me the desired behavior I was looking for.

**Comment by paulperez-dev** [comment]
Hi @captainjdi, thank you for your report! This is not a FlutterFlow issue per se. What happens is that the image list's current index gets out of sync because you are removing items from it.<br><br>I'm glad you have solved the problem, I will close this issue.

**Comment by orchard800** [comment]
Please don't close this. I'm having the same issue and the workaround doesn't work for me. I'm removing stack items programmatically and the user is left with the grey box and can't get back to the other stack items. Help!

**Comment by Ammar-Montaser** [comment]
Having the same issue here, tried using state but it didn't work.

**Comment by hackythoughts-ivyf** [comment]
I hope this can help, I was able to solve a similar problem: https://community.flutterflow.io/discussions/post/swipeablestack-solution-to-removing-items-during-swipe-VEpvmtTJxF2QN4F
