### ISSUE TITLE
Flutter Doctor Output not recognizing CHROME_EXECUTABLE variable when it's set for other Chrome based browsers (e.g., Brave)

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#2717]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting up Flutter for local testing, FlutterFlow is not recognizing the CHROME_EXECUTABLE variable when it's set for other Chrome based Browsers like Brave.

When running `flutter doctor -v` from the terminal, however, it works properly, but for some reason in FlutterFlow UI it fails.

### Expected Behavior

FlutterFlow UI runs Doctor Output with no errors or warning, regardless of whether I have Chrome or other Chrome based browsers installed, such as Brave.

### Steps to Reproduce

1. Set CHROME_EXECUTABLE variable to the desired browser on your terminal configuration file, such as .zshrc or .bashrc. In my case, it goes like `export CHROME_EXECUTABLE="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"` at the end of the file;
2. Follow the default steps for setting up Flutter for local testing on FlutterFlow, like explained [here](https://docs.flutterflow.io/deploying-your-app/testing-your-app/testing-on-mobile-device#use-local-run-in-the-flutterflow-desktop-app);
3. On the "Flutter Doctor Output" step, it should show a warning on the "Web development" item, saying that it "Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.";
4. Open your terminal and run the Doctor Output command from the same directory where FlutterFlow installs Flutter, as follows: `"/Users//Library/Application Support/io.flutterflow.prod.mac/flutter/bin/flutter" doctor -v`
5. It should mark the "Chrome - develop for the web" item with a green check, indicating that there are no issues.

For the sake of this explanation, I'm not taking into consideration any eventual issue with other platforms such as iOS or Android, only Web.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not specific to any project, but to FlutterFlow app itself.

### Context

There are other ways for testing my code locally, but I think it would be important to raise this issue here, since it's much more practical than commiting the project to GitHub and pulling it everytime, or having to set everything up manually (both Flutter and our project from FlutterFlow CLI).

### Visual documentation

Here are two evidences showing the behavior on the FlutterFlow app, and that Flutter Doctor actually recognizes CHROME_EXECUTABLE when ran form the terminal from the very same path where FF installs Flutter:

![Captura de Tela 2024-04-14 às 00 30 52](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4875dab0-9d46-4ca7-ab8a-652c243d566d/64aac6ee-5b0e-45ed-a289-4f827bd72325?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODc1ZGFiMC05ZDQ2LTRjYTctYWI4YS02NTJjMjQzZDU2NmQvNjRhYWM2ZWUtNWIwZS00NWVkLWEyODktNGY4MjdiZDcyMzI1IiwiaWF0IjoxNzEzMTA3ODI3LCJleHAiOjMzMjgzNjY3ODI3fQ.yravna41maIUv3-lQn-mtRa74Nc9re9sVxyLeFiNdbA)

![Captura de Tela 2024-04-14 às 00 43 39](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/db2c4b0a-2510-482d-890d-80f4ce752c75/50a9d125-8e58-41b1-af29-0354eff56aff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYjJjNGIwYS0yNTEwLTQ4MmQtODkwZC04MGY0Y2U3NTJjNzUvNTBhOWQxMjUtOGU1OC00MWIxLWFmMjktMDM1NGVmZjU2YWZmIiwiaWF0IjoxNzEzMTA3ODI3LCJleHAiOjMzMjgzNjY3ODI3fQ.6E1accM9SGz5sVKxmlIpe4-53Nq0AabiyMwJvwtJQIw)

### Additional Info

Below is the full Doctor Output obtained from FlutterFlow UI. Note that it's expecting CHROME_EXECUTABLE to be set to `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`, hence the error:

```
[!] Flutter (Channel stable, 3.19.1, on macOS 14.4.1 23E224 darwin-arm64, locale pt-BR)
    • Flutter version 3.19.1 on channel stable at /Users/vitoras
    ! The flutter binary is not on your path. Consider adding /Users/vitoras/Library/Application Support/io.flutterflow.prod.mac/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/vitoras/Library/Application Support/io.flutterflow.prod.mac/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (8 weeks ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vitoras/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 14.4.1 23E224 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Environment

```markdown
- FlutterFlow version: v4.1.39
- Platform: MacOS
- Browser name and version: Brave 1.64.122
- Operating system and version affected: macOS Sonoma 14.4.1
```

**Comment by paulperez-dev** [comment]
Hi @vitoras, thank you for your report! I will send it over to the team so they can take a look.
