### ISSUE TITLE
Custom code not saved after clicking save button

### ISSUE THREAD

**Issue by pyro32** [FlutterFlow/flutterflow-issues#2718]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Spend hours writing code. Click save several times. UI appears to save. Refresh window and saved changes disappear.

### Expected Behavior

Code saves when changes are made and save button is pushed.

### Steps to Reproduce

1. Spend hours writing code.
2. Click save several times.
3. UI appears to save.
4. Refresh window and saved changes disappear.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj8ncx891ofUF0LrUc8B7/GMQNm4mROdJscp/bxIgGIDzPOw+ZPWlVxBpZO7nd1VHeUSmml4G//DUkuztDPI4OU6YbqZBwbV6SA/gIWCtUZOBCZCOYHFDHeVgCkyx0abYnwhQFLRvdVFm3zmMJ+iubCjaGJjRImdISq/LZO4=

### Context

I've lost so much code because of this bug. Even worse, I don't know which pieces of my code didn't save so I hit extremely different to debug issues later as a result of partially saved code that I had updated or written.

I've tried to work around it by saving constantly, copying all code, reloading the browser UI, pasting the code, saving again. But this doesn't always work and often I notice the issue is more likely to occur when multiple

### Visual documentation

I don't think an image or video here is helpful or instantly reproducible. Can't figure out the exact bug trigger.

### Additional Info

There are a few potentially related bugs I've noticed. I'm going to stop using Flutterflow now because unfortunately there are too many bugs like this that cost me much more time than the time I save using Flutterflow.

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment]
Hi @pyro32 Thanks for your report, So sorry you are experiencing this issue. Even if the issue is not reproducible every time, a video with the steps you are following will help us replicate the bug and fix it.<br><br>Can you please attach a video with the steps you are following?

**Comment by paulperez-dev** [comment]
Closing this issue since we have not heard back
