### ISSUE TITLE
Project fails to open on both Web and Desktop after editing on iOS

### ISSUE THREAD

**Issue by critgames** [FlutterFlow/flutterflow-issues#2721]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I used the iOS flutterflow app and now both desktop and web versions of the app say "Flutterflow Version out of Date" You are on an older version of this project. Please refresh the page to use the latest version."

Refreshing the web app  as well as downloading and reinstalling desktop application don't fix . Basically it means I cannot open my application anymore except on iOS. This is very broken developer flow as I have no control over the project versioning and cannot downgrade or get back to a prior save state.

I can open the project on Flutterflow on iOS. When opening the project there, it says project is "FlutterFlow v4.1.39+5." Projects on web are Flutterflow "v4.1.39+" and web version says "FlutterFlow v4.1 released April 11, 2024". Seems like versioning across iOS / Desktop / Web are different.

Flutterflow, please fix!

### Expected Behavior

As a developer, I should be able to open my project on any platform Web, Desktop, and iOS. Edit. And then open on any other platform with the expectation that if the applications are up to date, it will open as expected.

### Steps to Reproduce

1. Opened existing project in iOS flutterflow app
2. Make a change
3. Attempt to open project on either web or desktop application --> this will give a prompt that the FlutterFlow Version is out of date, but there is no resolution path.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Project will not open

### Context

This has completely halted the development of our application. We can no longer open the project or edit on any other platform.

### Visual documentation

![Screenshot 2024-04-14 122101](https://github.com/FlutterFlow/flutterflow-issues/assets/20785113/5675ddf3-4e4d-4356-9ff2-a7d23c9cf065)

### Additional Info

I can create a fresh project on iOS and then open on other platforms. It seems to have killed the ability to open one particular project--but I can't imagine I'm the only person stuck in version hell with an inaccessible project. Copying the project does not fix anything.

### Environment

```markdown
- FlutterFlow version: v4.1.39+
- Platform: iOS, Web, Windows, MacOS
- Browser name and version: Chrome Version 123.0.6312.106 (Official Build) (64-bit)
- Operating system and version affected: Microsoft Windows 11 Pro Version 10.0.22631 Build 22631, macOS Monterey Version 12.4
```

**Comment by rzambroni** [comment]
Hey @critgames, I'm really sorry you're experiencing this issue. I've attempted to reproduce it on a couple of projects, but unfortunately, I haven't been successful, and without the bug report code to access your project, there isn't much I can do from my end to help troubleshoot.

Given the nature of the issue, I would recommend reaching out to our support team. Would you mind following up with them? You can contact them either by email at [support@flutterflow.io](mailto:support@flutterflow.io) or by using the in-app chat inside of FlutterFlow.

Thanks!

**Comment by critgames** [comment]
Unfortunately I can't get the bug report code as the project fails to load at all. I'll try direct contact. I'm sure I'm not the only one who has gotten into this state.

**Comment by wbacab** [comment]
I have the same problem. Yesterday I worked from the iPad and when trying to open it on the web or desktop I got this message:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12869289/56656ca9-0d92-4887-95b4-ee7dcd8949fa)

**Comment by amith-c** [comment]
Same issue here. I was working on my iPad, and later when I opened it on the web, it gave me this message. Soon after, it came on my desktop app too

**Comment by dylanfox22** [comment]
Hello FlutterFlow team, I have the same issue as well. Please resolve this ASAP - not sure how iOS can be more 'up-to-date' than the web browser application. Thank you @critgames for raising.

**Comment by AlchemyApps** [comment]
@rzambroni - I am having the same issue, but the form link indicates that I need an invitation.

**Comment by aburchfield** [comment]
> @rzambroni - I am having the same issue, but the form link indicates that I need an invitation.

Same for me!

**Comment by rzambroni** [comment]
@AlchemyApps & @aburchfield Sorry about that, form permissions are now fixed: https://forms.gle/C39E7p9R3Q6yuw53A

**Comment by lemmen6** [comment]
Same here, very dangerous bug and still not fixed.

**Comment by leighajarett** [comment]
Hi there, <br><br>First off, so sorry that you're dealing with the version issue from iPad being ahead of web. I can imagine this is so frustrating. As mentioned, this was a problem with our deployment process. We originally figured that we would add everyone to beta, however, we've decided we will deploy to web earlier than expected. So you should be able to access app.flutterflow.io as normal, within the hour. <br><br>Once again, I'm sooo sorry for this issue. I know that it can be extremely frustrating. Thank you for being a part of our community!

**Comment by xray7474** [comment]
I have the same problem but not an iPad user. I was using macOs and then went on web which was working. At some point I ended back on MacOs and now web no longer works.
