### ISSUE TITLE
Widget's Backend Query API call failure status crashes app

### ISSUE THREAD

**Issue by d6p2b** [FlutterFlow/flutterflow-issues#2722]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If a widget has a Backend Query which triggers an API call that ultimately fails (status != 200) the app crashes with a NoSuchMethodError because 'toList' is called on the null body.  This can easily happen in production if a server is not reachable or has some sort of internal error unrelated to the Flutter Flow app.

Note:  This is limited to the API call being made from the Backend Query of a widget (e.g. ListView) not as part of an action.

### Expected Behavior

Don't invoke the toList method on the null JSON body and offer a way to specify a component similar to the Empty List component which takes the place of the ListView in the widget tree for "non-200" status results.  Alternatively, return an empty list to the widget and trigger an action so the developer can warn the user appropriately.

### Steps to Reproduce

1. Create an API call with a damaged URL.  
2. Test the API call to make it returns an error status. (I used a damaged URL so my API server returns status=500)
3. Create a new page with a ListView widget whose children populate from the returned JSON data.
4. Bind the API call to the Backend Query of the Listview.
5. Navigate to the page for the red screen of death.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48k8jq349Psbxc1pPpbfowpDwsQ3k7UL8ZkOpuZxI8J5zKB+wAYvf7P1FWTLyqSnxleU2j8WQJ/Pfqi+PpDcFeFySZY6o9yodyZQqUez+5bJjSPaiVfW1fN8FPCUCB4baFoSRAOtdpSEIF3U2MGvO+dCjUNqb2NmosROSbLdeK2SrDX1iXc2URm05KZDPz

### Context

Any problems with the API server forces the user to restart the app when a failure status code could easily be reported and the user offered a chance to reload or take some other action. 

### Visual documentation

I think everyone's seen the red screen of death.  

### Environment

```markdown
- FlutterFlow version: v4.1.39
- Platform: MacOS (really all platforms)
- Browser name and version: iPhone 15 Simulator
- Operating system and version affected:  All
```

**Comment by paulperez-dev** [comment]
Hey @d6p2b, thanks for your report! I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
