### ISSUE TITLE
google maps widget does not load correctly from background on certain devices

### ISSUE THREAD

**Issue by ZandrePakwe** [FlutterFlow/flutterflow-issues#2724]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

currently, when the app is being opened from the background on some android devices the google map component only displays a grey background.

I have only noticed this behaviour on 2 separate Samsung galaxy S22 devices (SM-S901E/DS) 
One UI Version 6.0
Android Version 14
Kernel version: 5.10.168-android12-9-27760517-abS901EXXS7DXC2

it seems to only happen when the app is being opened from the background and not when the app is being launched without having the app open in the background. Navigating away from the main page and navigating back also seems to make the app draw again. however this is a bad user experience.

### Expected Behavior

the map should draw correctly regardless of how it gets loaded.

### Steps to Reproduce

1. create a new app
2. add google maps api keys to config for platforms (android is most relevant)
3. remove all components on default screen and drop in a google maps component
4. download code
5. build apk of app
6. install on device
7. open app, observe the map drawing correctly
8. minimize app
9. re-open app from task switcher
10. observe only a gray background instead of the google map being drawn on the screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/Lqy4Vgrt9c187pbcBoljoQJWY+TL03qu0bGBYbCIzQB4YEaePeTBFtUuqrSlZ9KEWJnXM0wPzti9nhCPQ7AAqsRqJnyapudTzhQl6/aouVEcyaekZAI/lXBXa/07TYpQlCOsxtc04E7F+uDN69QivZK4f6Zwh9f6PHaOI=

### Context

My app has got a google maps component on the home screen, which does not display anything when app is being reloaded from the background, for a significant subset of my userbase.

### Visual documentation

![Screenshot_20240415-133831_One UI Home](https://github.com/FlutterFlow/flutterflow-issues/assets/145122041/65b2291f-a4bc-4742-8553-14f185f51686)

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: android
- Browser name and version: N/A
- Operating system and version affected: Android version 14
```

**Comment by rzambroni** [comment]
Hey @ZandrePakwe, I'm sorry to hear you are having that problem with your app. I've tried to replicate the issue with several devices, including an S22 and an S24, but haven't been able to reproduce it on my end.

This seems to be a device-specific problem, which can make it challenging for our team to pinpoint and resolve. 

If at some point you have more information that could help us identify this problem please let us know.

Thanks.
