### ISSUE TITLE
Login Action Chain - Error

### ISSUE THREAD

**Issue by zakakatz** [FlutterFlow/flutterflow-issues#2725]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Login button does not work and an error is returned. 

### Expected Behavior

The action chain should execute and the user should be logged in and navigate to the home page

### Steps to Reproduce

1. Enter zak+april@embrevents.com for email from Login Page. Enter password Testing123
2. Click Login

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

AvXvnz2PhHgMd2RLdcC5HrsvsHppXY4gbj2CkU9H9Ca6

### Context

Login to my app. This is preventing me from being able to have my app approved by App Store. 

### Visual documentation

![Screenshot 2024-04-11 134755](https://github.com/FlutterFlow/flutterflow-issues/assets/13775340/66e556d5-3280-420e-8f64-e6b7ff835b6c)

https://github.com/FlutterFlow/flutterflow-issues/assets/13775340/13be87a4-fa68-4a5b-b557-b4975ea85dda

### Additional Info

i have removed all references to doubles in the action chain associated with that button on the login button so i have no idea what is causing this

### Environment

```markdown
- FlutterFlow version: 4.1.39+
- Platform: iPad
- Browser name and version: Any
- Operating system and version affected: iOS
```

**Comment by paulperez-dev** [comment]
Hi @zakakatz, thanks for your report! The bug report code seems to be incomplete. Can you please send us the code again?

**Comment by paulperez-dev** [comment]
Closing this issue since we have not heard back.
