### ISSUE TITLE
Unable to set initial value in text input widget from action output

### ISSUE THREAD

**Issue by kulpreet-mailbox** [FlutterFlow/flutterflow-issues#2726]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

unable to set initial value of text input widget from an action output value

### Expected Behavior

Initial value of text input can be set from a variable. and this variable can be action output.

### Steps to Reproduce

1. Create a page
2. create a local page state boolean name it showdata. Set default value is false
3. Add a button
4. create action to query a supabase row and set state "showdata" to true
5. add text input widget, set initial value of this widget from action output value. (set conditional visibility from "showdata" local state)
6. add text widget display action output value (set conditional visibility from "showdata" local state), (this is to confirm supabase row query is successful and data is fetched)
7. run the app and test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhefq0It1xPUB7ZSIKO1WqCEWJmUcTLkvjuphcz8YGIztBJh/dvT4aklvTfGiTFNhHGeLsEwd+PvIkt+SEfI7CEmcfIBayZFqbg3JQXq8RIyuOqiKfXdfM8VMf0yf1KarrxRSCNBfLHtk2l+uBfCsdCnZJ5+/Zwh9f6PHaOI=

### Context

trying to set initial value of text input widget from action output value

### Visual documentation

![bug1](https://github.com/FlutterFlow/flutterflow-issues/assets/129294189/42442394-d5f9-47bf-afb0-5c61dc113a16)
![bug2](https://github.com/FlutterFlow/flutterflow-issues/assets/129294189/c719b77b-2d24-4103-a238-bd601f39fea9)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: web
- Browser name and version: Brave Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by paulperez-dev** [comment]
Hi @kulpreet-mailbox! Thank you for your report. I was not able to find the configuration shown in the images inside the project provided via the bug report code. Can you please reproduce the issue in the project and let me know?<br><br>You can also consider to update the page state and set the initial value from there.

**Comment by kulpreet-mailbox** [comment]
This is the bug report of the page on which you can find the configuration. 
ITFfhefq0It1xPUB7ZSIKO1WqCEWJmUcTIMziNZ+exUbfaL1Bu0uPuOkblRpZ8ulaVNcAWCJjkgfw979vuOWCvY3ITSZUa0//7V6aA3Oe2ijaYjXDbqoSUZAFphjCm601Ji3oB0kKrFedUYawV6pN+u9Qh3DFOu/Zwh9f6PHaOI=

thanks for suggesting the work around. I just wanted to confirm if it is an actual bug then i can keep track of the work around which i implement now so that i can remove them in future when ever the bug is fixed.

**Comment by paulperez-dev** [comment]
@kulpreet-mailbox, I will be taking a look to this new bug code and let you know if it is a bug. Thanks!

**Comment by paulperez-dev** [comment]
@kulpreet-mailbox my bad, I meant you to create a blank project and share the bug report code from there after reproducing the issue. Can you please help me with that?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you, thanks!
