### ISSUE TITLE
IOS Text Zoom Settings

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#2729]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a User has the IOS Text Zoom feature enabled it can happen that the Text in the app will overflow because of the  textScaleFactor. There is no way in FlutterFlow to disable this behaviour globally.

It might not be best practice but having the possibility to set the textScaleFactor globally in the app would be greate. 
A easy fix would be to use a Material App Builder with Media Query like this:
MaterialApp(
  builder: (context, child) {
    return MediaQuery(
      child: child,
      data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
    );
   },
)

### Expected Behavior

Being able to control the text scale.

### Steps to Reproduce

1. Create app
2. add Text field
3. Set text zoom in IOS settings

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlcmB34hNodcF+KrqdcJslWQsCUMBW7hEm+1/GAkcIbbmBJk+Z8/EaXdfZ/2oe2xYeGKZpEcz+PSLitrhE/YCG0ycGrV607ViUAvJQXGlV6akEZDpZnFCAfJMf1Cn38C73R17ANpZcVI461+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

trying to make the app look exactly the same independet of the IOs settings

### Visual documentation

Na

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: IOs
- Browser name and version: - 
- Operating system and version affected: IOs probably android as well
```

**Comment by paulperez-dev** [comment]
Hi @nicmohr25! Preventing the text to scale will affect the accessibility of the app. Consider using the Auto Size toggle in the Properties panel.<br><br>If a widget do not support Auto Size, you can create a custom one. 

Let me know if these makes sense!

**Comment by nicmohr25** [comment]
But Using the Auto Size would probably result in the same outcome. 
But with the auto zoom i have to adjust every text element individually. With my proposal you could do it globally once. 

Also 'If a widget do not support Auto Size, you can create a custom one.' - is not a good solution for a low code app. We should be able to to it without the need to code.

**Comment by nicmohr25** [comment]
I also just checked it but using the Auto zoom feature doesnt work. The IOS Text Zoom doesnt respect die input and zooms anyways. 

Therefore there needs to be an option to set the TextScale Factor globally. At least to limit it by Factor X

**Comment by paulperez-dev** [comment]
@nicmohr25, can you try the following:<br><br>*In case of overflowing text, it's recommended that you wrap the Text Widget inside an Expanded widget. To do this, click on the Expand option in the alignment properties of the Text Widget.*

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you, thanks!
