### ISSUE TITLE
New Feature 'Image upload to API' not working.

### ISSUE THREAD

**Issue by irfan-ahmed-1982** [FlutterFlow/flutterflow-issues#273]
I have tried to upload the image to my Wordpress backend I have added a button with action to upload the image to local (Widget) state, next I have added another action to trigger API call with body data type Multipart / Local Image from widget state (uploaded image bytes). Unfortunately I receive the 'No data supplied' Error.

![image](https://user-images.githubusercontent.com/118018023/209448253-a530bd22-4bc6-46ca-ae5d-3a7d171c96b5.png)

Steps to Reproduce:

1. Create a new Button.
2. Add Action 1 > Upload Media > Upload Photo / Video >  
3. Select Upload Type > Local Image
4. Add another Action 2 > Backend Call > API
5. Select API Used for uploading media to Wordpress (Wordpress as checked by me, You may try with any other backend also).
6. Pass the variables Authentication Token and Local Image and inside the Local mage Variable select Uploaded Image Bytes ( You will have to Select Body of the API call as Multipart. and define the variable type as Local Image in API Call.
7. Now test it. (While testing I received 'No data supplied' Error

**Comment by agreaves** [comment]
Hi @irfan-ahmed-1982, could you please add a Bug Report Code to your issue? You can generate this by right clicking anywhere in the widget tree.

**Comment by irfan-ahmed-1982** [comment]
**Bug Report Code:** IT8Cls/l5Yx2sdtJ14SJd8BvoDs5KWk7apZNm8JAEBAdGL6vPe0Xe+D8R1tBY7TidHw7JWKJnVgVpPTVvoaSIcc3A02tGdlt+c5qUALKbD2XMKWDGbqWXURDP5lRIH6e37WzgyRNLftoWFIX7U2hNa3qNleeY8aSfxBlZ7vfcPo=

**Comment by victoriahuang1** [comment]
Hi @irfan-ahmed-1982 , we found a bug on our side and should now be fixed upon our next deploy!

**Comment by Neesan** [comment]
Hi @victoriahuang1 , this issue has started occurring again, on Friday 24th Feb a version of our app was making successful calls to our backend when uploading an image , the next day a new build of our APK with no changes made has stopped uploading the image , resulting in this error
