### ISSUE TITLE
Inconsistent button icon size

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2730]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The size of the icon is different between the FF Builder and Test or Deployment

### Expected Behavior

The size should be the same everywhere.

### Steps to Reproduce

1. Add a button
2. Go to Icon Properties
3. Add an Icon
4. Do a deployment or test and compare the icon size with FF Builder

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KnQcMB4nig4GUMfWLsr0utuGA0hfar0OqQlP/feahNLYte8YG1MJmajgkEd+fzsi+P9EfICAz6qRYh5+L5XQQLvRji5eLaIEc2oS3QmGcdgIX3H1sK3vQlQFO5sdV413GahfPCNG3qCf9qOYwx5e6fDbOY=

### Context

I want add an icon to a button

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3f853259-d7b7-4a37-a469-89c3bbbccf70/a5b99ed2-67fe-4b07-962e-291e088fb8b4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zZjg1MzI1OS1kN2I3LTRhMzctYTQ2OS04OWMzYmJiY2NmNzAvYTViOTllZDItNjdmZS00YjA3LTk2MmUtMjkxZTA4OGZiOGI0IiwiaWF0IjoxNzEzMjMwMDI5LCJleHAiOjMzMjgzNzkwMDI5fQ.If3vOd6NMxCyloQPFIcS3J9MSTEHJrtX9h4KlgnFbXM)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404!

I was able to reproduce the issue you are describing on a blank project. Will send this over to the team so they can take a look.

Thanks for your report!
