### ISSUE TITLE
Conditional action names are always kept at 1

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2732]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Conditional action names are always kept at 1

### Expected Behavior

Conditional action names should be incremented as they are added

### Steps to Reproduce

1. Create several conditional actions and you will see that they always remain at 1

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KnQcMB4nig4GUMdXOczitVEew4bCIj4PLQideP8YVVvXtCzaH9IOWKb8Xse+cL5uPzuUcEFAz6qfYRRwpZAURPPbGCQSp+YEpCVP3Z8L+9VGnKD05m3pRFDIbJvWEI1w2eyCOeART2Cf9qOYwx5e6fDbOY=

### Context

I want to create several conditional actions and be able to see the correct number to have better control

### Visual documentation

[https://www.loom.com/share/1fee7dc0598a4f609afdecf8165d3158](https://www.loom.com/share/1fee7dc0598a4f609afdecf8165d3158)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404! I was able to reproduce the issue on your project, thanks for the report!

**Comment by leighajarett** [comment]
We've just put in a fix for this, it should be available in the next week or so 🙂
