### ISSUE TITLE
Overflow in type names for Data Types and Enums

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#2735]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Creating a really long Data Type or Enum overflows the side panel in the UI.

### Expected Behavior

The IDE UI to gracefully handle long DataType / Enum names like it does Firebase schema names.

### Steps to Reproduce

1. Create a new data type or enum > \~32 characters
2. See that the type name overflows the column

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

UI Issue

### Context

Data types, enums and Firebase schema names all seem locked to 40 characters. However, while the Firebase schema names are gracefully handled by downsizing the font, the Data Type and Enums overflow the left panel.

### Visual documentation

* DataType - overflows :

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b753b963-4787-49dc-a5ee-8af169168122/0eddcc42-6c8b-4753-a7ca-81e179e6d795?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNzUzYjk2My00Nzg3LTQ5ZGMtYTVlZS04YWYxNjkxNjgxMjIvMGVkZGNjNDItNmM4Yi00NzUzLWE3Y2EtODFlMTc5ZTZkNzk1IiwiaWF0IjoxNzEzMjMyMDgyLCJleHAiOjMzMjgzNzkyMDgyfQ.7PJ2ONaAamnONcHQO_jmeIikATzXGjLJUPH0gfCwZkI)

* Enum:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/37bc1aaa-e9dc-4c48-a2c2-395d1ce8c289/7746423e-592d-4e72-b293-c2607d678725?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zN2JjMWFhYS1lOWRjLTRjNDgtYTJjMi0zOTVkMWNlOGMyODkvNzc0NjQyM2UtNTkyZC00ZTcyLWIyOTMtYzI2MDdkNjc4NzI1IiwiaWF0IjoxNzEzMjMyMDgyLCJleHAiOjMzMjgzNzkyMDgyfQ.HT7tRAWMBM5wHh4z_QYC8Kxp6Xi0mxg23SM-FUbqX_A)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.39+
- Platform: Web and Desktop
- Browser name and version: Chrome/Edge
- Operating system and version affected: Windows and MacOS.
```

**Comment by paulperez-dev** [comment]
Hi @joni-percsolutions-com, thanks for your report! I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
