### ISSUE TITLE
It is not possible to set different values for the start and end flip of a flip animation.

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2736]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is not possible to set different values for the start and end flip of a flip animation.

### Expected Behavior

I want to set different values for the start and end flip of a flip animation.

### Steps to Reproduce

1. Select a widget and add a flip animation
2. Try to set different values to start and end and you see is not possible

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KnQcMB4nig4GUMfWLsr0utuGA0hfar0OqQlP/feahNLYteYeGNEDmGZ+T0x0anyuPz1IMJdPQerGr45wZRXQQLvRji5eLaIEc2oS3QmGcdgIX3H1sK3vQlQFO5sdV413GahfPCNG3qCf9qOYwx5e6fDbOY=

### Context

I want to set different values for the start and end flip of a flip animation.

### Visual documentation

[https://www.loom.com/share/e2e3ba862a4b450f86a115f9d3263ce5](https://www.loom.com/share/e2e3ba862a4b450f86a115f9d3263ce5)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404! I was able to reproduce the issue on your project, it seems that the value is changed because it is shown correctly when the panel is collapsed. I will send this to the ENG team so they can work on this.

We do appreciate your feedback, thank you!
