### ISSUE TITLE
Dynamically generated item spacing is rendered even though the child is hidden

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2737]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dynamically generated item spacing is rendered even though the child is hidden

### Expected Behavior

Should not render item spacing if the child is hidden

### Steps to Reproduce

1. Create an app state and populate it
2. Go to a page and create a column
3. Generate dynamically children from the app state
4. Now add the child and try to hide using the conditional visibility
5. Go to a test and you see the item spacing in rendered anyway

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KnQcMB4nig4GUMfWOdEket+EA0hfernO5kiZsjOUFpLYte/eG4/e1ClsE8C0PztiM7hD/EqYQeeR4BhzZRXQQLvRji5eLaIEc2oS3QmGcdgIX3H1sK3vQlQFO5sdV413GahfPCNG3qCf9qOYwx5e6fDbOY=

### Context

I want hide some widgets dynamically

### Visual documentation

https://www.loom.com/share/f285453cba744a7581ca19d66db1e49b

### Additional Info

Maybe this can be related with this issue:
[Item spacing is not consistent between FF Builder and Test or Deployment #2734](https://github.com/FlutterFlow/flutterflow-issues/issues/2734)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404! This is likely to be a different issue. I will send it to ENG. Thanks for your report!
