### ISSUE TITLE
Right click in page or component list is unintuitive

### ISSUE THREAD

**Issue by crioux** [FlutterFlow/flutterflow-issues#274]
## Expected behavior (required)
Right click should pop up the 'vertical dots' context menu

## Current behavior (required)
Right click causes an item to swap with the next one in the list

## To Reproduce (required)
1. make a bunch of components
2. right click on the first one
3. observe that it moves instead of the obvious action of a context menu

## Your environment
* Version of FlutterFlow used: 3.0 Dec 23 2022
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 108.0.5359.124
* Operating system and version (desktop or mobile): macos monterey 12.6

**Comment by crioux** [comment]
Also, moving the items in the component list via left click/dragging on the 'hamburger icon' doesn't work. It works if you click/drag on the name of the component, but not if you click on the icon itself.

**Comment by agreaves** [comment]
Thanks for the bug report! This will be fixed upon our next release 🙂
