### ISSUE TITLE
APK does not unload, test mode does not work

### ISSUE THREAD

**Issue by Rustem555** [FlutterFlow/flutterflow-issues#2740]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

APK does not unload, test mode does not work. Gives an error message:
Error: Command failed: flutter build apk --no-pub --no-version-check
lib/payment/payment_widget.dart:264:36: Error: The getter 'containerUsersRow' isn't defined for the class '\_PaymentWidgetState'.

* '\_PaymentWidgetState' is from 'package:art_eco_fruit_s/payment/payment_widget.dart' ('lib/payment/payment_widget.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named 'containerUsersRow'.
                             if ((containerUsersRow!.cashback! > 0.0) &&
                                  ^^^^^^^^^^^^^^^^^
  Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
  Execution failed for task ':app:compileFlutterBuildRelease'.

> Process 'command '/sdks/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:

> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at [https://help.gradle.org](https://help.gradle.org)

BUILD FAILED in 32s
Gradle task assembleRelease failed with exit code 1

### Expected Behavior

It is required that the test mode works and the APK is unloaded

### Steps to Reproduce

I launched the test mode and unloaded the APK

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Error: Command failed: flutter build apk --no-pub --no-version-check lib/payment/payment_widget.dart:264:36: Error: The getter 'containerUsersRow' isn't defined for the class '\_PaymentWidgetState'. - '\_PaymentWidgetState' is from 'package:art_eco_fruit_s/payment/payment_widget.dart' ('lib/payment/payment_widget.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'containerUsersRow'. if ((containerUsersRow!.cashback! > 0.0) && ^^^^^^^^^^^^^^^^^ Target kernel_snapshot failed: Exception FAILURE: Build failed with an exception. \* What went wrong: Execution failed for task ':app:compileFlutterBuildRelease'. > Process 'command '/sdks/flutter/bin/flutter'' finished with non-zero exit value 1 \* Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. \* Get more help at [https://help.gradle.org](https://help.gradle.org) BUILD FAILED in 32s Gradle task assembleRelease failed with exit code 1

### Context

It is required that the test mode works and the APK is unloaded

### Visual documentation

![222](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9379f543-5975-472c-9f71-43da35d2f2ac/0770ceab-681c-4d18-8c8e-d37350975081?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85Mzc5ZjU0My01OTc1LTQ3MmMtOWY3MS00M2RhMzVkMmYyYWMvMDc3MGNlYWItNjgxYy00ZDE4LThjOGUtZDM3MzUwOTc1MDgxIiwiaWF0IjoxNzEzMjc1NDcxLCJleHAiOjMzMjgzODM1NDcxfQ.yuqgYvfNHVUUKNF1_-Nr0JIqYItjPBDU-TlYdzdiML8)

### Additional Info

![222](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f7227357-7deb-4487-ac46-08993d8f9c0a/86431431-31fc-40dc-a7af-dd282a878cd4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNzIyNzM1Ny03ZGViLTQ0ODctYWM0Ni0wODk5M2Q4ZjljMGEvODY0MzE0MzEtMzFmYy00MGRjLWE3YWYtZGQyODJhODc4Y2Q0IiwiaWF0IjoxNzEzMjc1NDcxLCJleHAiOjMzMjgzODM1NDcxfQ.JYHRfZUCF-KaV1C_t9GJ5ToDCOXq601qANFPiFkx_DE)

### Environment

```markdown
- FlutterFlow version: I dont know
- Platform: Internet
- Browser name and version:Chrome Версия 123.0.6312.123 (Официальная сборка), (64 бит)
- Operating system and version affected: Windows 10
```

**Comment by rzambroni** [comment]
Hey @rustem555, looking at the error log on your screenshot there is likely a project-specific issue or misconfiguration on your project. I could try taking a look at the project but you will have to provide a valid bug-report-code of one of your widgets so we can check, if you don't know how to create a bug-report-code please visit [this link](https://docs.flutterflow.io/troubleshooting/submit-bug-reports).

If you are having specific project issues, it would be better for you to follow-up directly with our support team. You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

Thanks a lot!
