### ISSUE TITLE
'waitForOnePageForListView' is already declared in scope

### ISSUE THREAD

**Issue by Executer13** [FlutterFlow/flutterflow-issues#2745]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the page is not getting build and show error:-
<img width="501" alt="bug" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94052423/a76c0bd3-cf91-4be2-bc14-d870a7312ba3">

### Expected Behavior

i am using the flutterflow refresh databse request in initialilization inside action callback as well as the in button action thus its creating duplicate methods. please rectify it to not create duplicate methods with same name:- 
<img width="335" alt="bug2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94052423/11c3383f-3646-4639-9f8e-b2e621efb20f">

### Steps to Reproduce

1. Create a Page
2. In initialization use the refresh database request in a callback
3. use it in a button in the page
4. run the code 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goeIB+6XfLOxAhQIgQ0QnU7gnlO1ucx43fJSqPZYqZ+POZUNKTs+LYHxmJlWJmlgD/vzRvvPpUvU3BwWcUYBF0JVAaQLiLT66MIjRBbuNOXxtM9pjCB260Jmzkx5/OrZ1LXAu7FOTN63qNleeY8aSfxBlZ7vfcPo=

### Context

i can build the project

### Visual documentation

<img width="501" alt="bug" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94052423/7ab8b3fb-3ef2-4df9-b67d-23254c39f8ea">
<img width="335" alt="bug2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94052423/bd14c6f5-d108-4df1-b5b2-746eb788fd3e">

### Environment

```markdown
- Flutter Flow version: v3.1
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: windows 10
```

**Comment by paulperez-dev** [comment]
Hi @Executer13, thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

**Comment by Executer13** [comment]
Hi @paulperez-dev , the issue is resolved! needed to recreate the page. The issue was flutter-flow creating a helper method for the refresh Database Request and not recognizing it next time that same method is called. This resulted in duplication of the helper method and thus the error persisted.

**Comment by paulperez-dev** [comment]
Hi @Executer13, thanks for the confirmation! I'm closing the issue.
