### ISSUE TITLE
Trying to add a component in a scrollable column produce an Invalid action

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2746]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a column is scrollable and some widgets are added and with those widgets a component is created, it is not possible to add it again or duplicate it.

The strange thing is that there is already a component added within the column that is precisely the one I want to duplicate and that does not produce an error

### Expected Behavior

Should be able to duplicate the component

### Steps to Reproduce

1. Create a column and set it as scrollable
2. Add a row with an icon button and rich text
3. Set the row with Space Between in the Main Axis Alignment

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjPLq5YlIrtxE7ZPud+9aniUQHGJ9a600sd4bGA0dCJzuPLMQdvWkVFdoTse7d1VDeESmmjgBwvuPj/PfJvYVGy6WfLZ6zpBxEjqWWXyga5OBBbWKP2htP8FMfVSx1MKNhSV5NbNoLkIAwE66I+qQbCbcHrWxIndISq/LZO4=

### Context

I want to create a component so I can use it and add parameters to customize it

### Visual documentation

https://www.loom.com/share/7ad78c5db3fa447db6bd4ecfd8cf0749

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 16, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404, thanks for your report! I followed your steps and was able to replicate the error, but I got a reason of the crash:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b21d5db6-e449-4731-b37d-08f27810d4cd/4bf09232-6f73-4825-b726-1aa7dd64059b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMjFkNWRiNi1lNDQ5LTQ3MzEtYjM3ZC0wOGYyNzgxMGQ0Y2QvNGJmMDkyMzItNmY3My00ODI1LWI3MjYtMWFhN2RkNjQwNTliIiwiaWF0IjoxNzEzMzIyMDE2LCJleHAiOjMzMjgzODgyMDE2fQ.2gITET8PNFKoC8AO8ld3oUpQ_zeva80qf_A9U6Zo9WQ " alt="image.png" width="1308" height="676" />

Can you please try again a couple of times and let me know if you can see the reason at least once?

**Comment by Franco98404** [comment]
I found 3 related errors:
1. In my case it never shows me the error message for the image you sent
2. When entering the project I can duplicate the component, but it does not render correctly (apparently when the component is duplicated the expansion is set to expanded, as your error message in the image shows)
3. When I want to duplicate again it is not possible and gives an error message

https://www.loom.com/share/5ef7c67833b54d1facc49b7692288e46

**Comment by paulperez-dev** [comment]
Hi @Franco98404, the bug I can notice and reproduce is that a component whose Expansion is set to default should not create a duplicate with the Expansion set to **expand**. This is the root of the issues we are facing, so the error shouldn't arise after the fix.

I will send this to the ENG team so they can work on this. Thanks for your very detailed and precise feedback!

**Comment by bgbraga** [comment]
![Screenshot_2024-07-24 14 41 45_B9kFjd](https://github.com/user-attachments/assets/25a7316a-dc0a-477b-aabb-cc25707ab2be)

@paulperez-dev I have a similar problem. Since I transform a ListView to a component I'm receiving the "Invalid Action" error when I open the page to edit (just opening).
At runtime the page is working fine. I just can't edit it. In my case there is no reason. Just "Invalid Action" generic message as we can see in the screenshot.
