### ISSUE TITLE
API Key Google Maps not added to AndroidManifest.xml

### ISSUE THREAD

**Issue by salex996** [FlutterFlow/flutterflow-issues#2747]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When downloading the code the android API Key is not being added to the AndroidManifest.xml

### Expected Behavior

The API Key for google Maps integration should be added

### Steps to Reproduce

1. Create a blank project
2. Add API KEY for android, ios and web
3. Add a custom widget that embebed a map
4. Download the code
5. Try to click on map
6. An exception appear saying that the API KEY should be added to the androidManifest in section application

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ez/Hqw4Z1rv1Y176Jc8Ew+CQWQlw4UII3iuwbdAwaCKKuP+0XP+j+TGZuOLDid2xiPFmWgm0e/tWLufzAGMY4GByJbNk5yLptFwvxZDiRR6qhCs2WeXAmI9lMCEi4zpuZvhRSFNVYW1Im2HGYGOTKfD7cGZTsIlYjPPmhKqLIgV3jHibkGn0Jg1ZSfCvr

### Context

I tried to implement the custom widget that I found in this youtube video: [https://www.youtube.com/watch?v=45B-TQoYeFE](https://www.youtube.com/watch?v=45B-TQoYeFE)
the video explains how to modify google maps markers,

At the beginning when I tried to test the widget in the web application the markers didn't change so I decided to download the code just in case the integration only worked with Android,

Indeed, when I opened the code with android studio two exceptions appeared and I couldn't see the map, when I went to the AndroidManifest I realised that the API KEY part was missing,

### Visual documentation

Screenshot of the API Key added manually

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2e920311-8437-4b05-9f31-81cf2aef5ad9/e1b23227-959c-4f14-ad9c-cf740210f294?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZTkyMDMxMS04NDM3LTRiMDUtOWYzMS04MWNmMmFlZjVhZDkvZTFiMjMyMjctOTU5Yy00ZjE0LWFkOWMtY2Y3NDAyMTBmMjk0IiwiaWF0IjoxNzEzMzIwODAwLCJleHAiOjMzMjgzODgwODAwfQ.ppKJ5F1RLy2ICzhtUf6lcruo_9Ppf1J-C8-mj46-TPM)

Screenshot of the API KEY added in flutterflow before I downloaded the code:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/faa66466-0c94-426d-b0b9-80cb2b7a61f5/1a0861de-c803-4b60-8d2c-4617deaf8990?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYWE2NjQ2Ni0wYzk0LTQyNmQtYjBiOS04MGNiMmI3YTYxZjUvMWEwODYxZGUtYzgwMy00YjYwLThkMmMtNDYxN2RlYWY4OTkwIiwiaWF0IjoxNzEzMzIwODAwLCJleHAiOjMzMjgzODgwODAwfQ.ihA7OeZb3tylC-a3du4rygqM-7GKSXSwWrHeGnAXjfc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Web
- Browser name and version: Chrome 123.0.6312.105
- Operating system and version affected:
```

**Comment by leighajarett** [comment]
Hi there! So sorry about the delay here. We took a look at this issue but we are unable to reproduce it. Are you able to share steps to reproduce from a blank project? Otherwise can you please reach out to support and they can help figure out if it's a problem with your project's configuration? Thanks so much!

**Comment by rpock** [comment]
I think what @salex996 meant was that he uses a custom widget as a map widget, here the API key is of course not taken over by FlutterFlow.
 
Simple solution for salex889:
Create a dummy-page in the project and place the FlutterFlow Maps widget in it. Then the API key will also be available for custom maps widgets.
 
For efficiency reasons, widget configurations and the like are not placed in the code if the widget is not used, even if you have entered it in FlutterFlow in the settings.
