### ISSUE TITLE
How to implement supabase authentication?

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#275]
1) In the Authentication tab, only firebase authentication is mentioned. 
2) I have activated email authentication in Supabase but can not see the supabase-authentication option in flutterflow action editor. Please provide documentation for using the Supabase Authentication system.

**Comment by organicnz** [comment]
Hi @siddharthadevops. Thank you for adding this issue 🙂
The FlutterFlow team is working hard to develop new features and documentation on Supabase Authentication will be published sooner rather than later, mate 🙂
