### ISSUE TITLE
FlutterFlow PdfViewer does not display all layers present on some PDFs

### ISSUE THREAD

**Issue by firecal-billy** [FlutterFlow/flutterflow-issues#2753]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When certain PDFs are loaded in PdfViewer, some layers that are present in the PDF file are not displayed.

![Layers Missing in FlutterFlow Android App](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/51b6eed2-202a-40ce-8dcf-b57fbd20ec0b/e14df8d3-89e8-4ef3-acba-b5e177a53525?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MWI2ZWVkMi0yMDJhLTQwY2UtOGRjZi1iNTdmYmQyMGVjMGIvZTE0ZGY4ZDMtODllOC00ZWYzLWFjYmEtYjVlMTc3YTUzNTI1IiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.HU8LNyYDGGa9s1klXUwvvkkgjvQ0JRthGoPT5KivCCA)

![Layers Visible in Other Android App](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdc66e4f-ce31-47df-9986-75268ea59ce7/e271924d-753f-42e2-8365-b5e137ccd312?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGM2NmU0Zi1jZTMxLTQ3ZGYtOTk4Ni03NTI2OGVhNTljZTcvZTI3MTkyNGQtNzUzZi00MmUyLTgzNjUtYjVlMTM3Y2NkMzEyIiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.GvdsQ25aUXdaVklzrphkAovXyvG7-yPHOmB3c6goVg0)

### Expected Behavior

All PDFs will display all layers present on the PDF file when displayed in PdfViewer.

### Steps to Reproduce

1. Upload this Completed Form PDF somewhere it can be loaded from a URL: [Test - Complete Form.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/15011488/Test.-.Complete.Form.pdf)
2. Create a new page
3. Add PdfViewer widget
4. Set PdfViewer to load the url for the Completed Form
5. Run Project in Test Mode, deploy to iOS App, deploy to Android App
6. Form layers with user entries will not be displayed in the FlutterFlow App
7. Opening the PDF URL in browser or downloading the PDF file from URL will show that the completed form layers are present on the file and display properly elsewhere

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slfHqw89gofVG7c/MdcBr/T8RQmI2a7g0scpFYxMjI4DuBIYiY876P1BVZPWrYAhmIGCmp14zwfzLvYX9DcAoBxaYc6JA+c51EwLwJX+uVbWTF7uNdXYmEfxgfWKE1p2nhBRdLs5uLy0862eqfNyRVnbXQ+P4Pno8Sq/LZO4=

### Context

Displaying PDFs is central to my app, in which users upload PDFs of Certifications and other documents relevant to their eligibility to work as Firefighters, EMTs, and other first responder roles. Often these documents are forms they've been required to complete, which require these layers to be visible for their supervisors.

### Visual documentation

![Layers Missing in FlutterFlow Android App](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7b0d7f19-e5c4-4001-afba-ce1e4192112f/9b0a0093-34d7-48f4-b54e-7352b55720a5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YjBkN2YxOS1lNWM0LTQwMDEtYWZiYS1jZTFlNDE5MjExMmYvOWIwYTAwOTMtMzRkNy00OGY0LWI1NGUtNzM1MmI1NTcyMGE1IiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.Ux065P9pyi2EzgnP7BVkZTi9hpeVt3FFwmUhFt9JzIw)

![Layers Missing on FlutterFlow iOS App](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdd0044e-bdcb-423d-bc68-dc80f5a856d7/8e31915c-1202-467f-8bfd-70ff5264b015?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGQwMDQ0ZS1iZGNiLTQyM2QtYmM2OC1kYzgwZjVhODU2ZDcvOGUzMTkxNWMtMTIwMi00NjdmLThiZmQtNzBmZjUyNjRiMDE1IiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.nvAAJ4sbAXOu_51lM163VAX26WKMfFxcRTvdHHO2oVo)

![Layers Visible in Other Android App](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4c75c02e-0b76-4a6a-a554-ced06b201e75/0f3945ac-ba84-4554-8189-4ff53b7daba5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80Yzc1YzAyZS0wYjc2LTRhNmEtYTU1NC1jZWQwNmIyMDFlNzUvMGYzOTQ1YWMtYmE4NC00NTU0LTgxODktNGZmNTNiN2RhYmE1IiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.YTvrM9Sl0zViNQCaqnnVxhMZEFx_5fGhT_2yOEEQAF0)

![Layers Visible on iOS Safari](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/56f1841f-683f-4fcf-82cf-9be656698ee7/e20903a5-6090-41f9-a3d6-59fb3a1ecf29?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NmYxODQxZi02ODNmLTRmY2YtODJjZi05YmU2NTY2OThlZTcvZTIwOTAzYTUtNjA5MC00MWY5LWEzZDYtNTlmYjNhMWVjZjI5IiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.aiTv7fE23oG3I2huB7j4bWU60RCG_HDxXxovNwwDs_M)

![Layers Visible on Mac Preview](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/333c0501-f39c-447e-8fe3-75c384e98386/6d3d957a-605d-4e4d-a8f9-ed093fc2ba37?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMzNjMDUwMS1mMzljLTQ0N2UtOGZlMy03NWMzODRlOTgzODYvNmQzZDk1N2EtNjA1ZC00ZTRkLWE4ZjktZWQwOTNmYzJiYTM3IiwiaWF0IjoxNzEzMzYxMTc0LCJleHAiOjMzMjgzOTIxMTc0fQ.U96ljhi19G28slUajdootKdnqzV5HdEp5A2_NcT6aiY "=1225x")

### Additional Info

In case it helps, for comparison, here are the blank and completed form PDFs:
[Test - Blank Form.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/15011638/Test.-.Blank.Form.pdf)
[Test - Complete Form.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/15011639/Test.-.Complete.Form.pdf)

### Environment

```markdown
- FlutterFlow version: 4.1.40
- Platform: Mac
- Browser name and version: Brave Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (arm64)
- Operating system and version affected: iOS, Android
```

**Comment by firecal-billy** [comment]
Can I get a link to follow along on the issue this duped?

**Comment by rzambroni** [comment]
Hey there! closing this as a duplicate, you uploaded the same issue twice: [https://github.com/FlutterFlow/flutterflow-issues/issues/2752](https://github.com/FlutterFlow/flutterflow-issues/issues/2752)

The triage of that issue will happen soon.

Thanks for the report.

**Comment by firecal-billy** [comment]
My bad, got a network error and didn't think it'd gone thru. Thanks!
