### ISSUE TITLE
Algolia search not working on test mode

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#2755]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when trying to search using Algolia integration in FlutterFlow I don't see any of the results returned (I do see them in a project run or when the app is in production/web release)

### Expected Behavior

i should be able to see the results even in test modes this issue is also found when the app is in internal testing from the google play store and apple stores

### Steps to Reproduce

 1. add firebase to project
 2. add algolia to project
 3. add a textfield
 4. add the search with algolia action onsubmit
 5. the search value should be the textfield widget
 6. add a list widget
 7. add the results of the search to the list
 8. launch a test version of the project
 9. launch a run version of the project
10. try searching on each version
11. on the test you should not see any results
12. on the run version you will see results

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89goctD7s+BasJViSQWOUAiR7hEmMpBay0jF7KuDLMqY8/RVERCOdOnd1VAeWGJhWoW08rQjvLhDcAqCAqtf4Bl1c1ATD3gWl6QMKqbFJWgeXEnL+5RJ37G1sKn3RElXcVucWQA32a2N+u8cDTaQ5z3OkgeDq/LZO4=

### Context

this is an issue i encounter that has made it slightly annoying when testing projects and releasing a project for beta testing i have made a custom action as a work around but it would be great to see this supported natively

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/276de40c-2858-40d0-a745-e688fdf267c2](https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/276de40c-2858-40d0-a745-e688fdf267c2)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.34+
- Platform:web/desktop
- Browser name and version:chrome
- Operating system and version affected: macos 14.4.1
```

**Comment by paulperez-dev** [comment]
Hi, @joekman990, thanks for your report. Did you import the existing documents into Algolia?

You can review the [documentation](https://docs.flutterflow.io/data-and-backend/searching-data/algolia-search) in case you don't know how to do it.

**Comment by joekman990** [comment]
sorry i see that the video did not catch the audio i will rerecord the documents are in algolia they will show in a run mode just not in a test mode

**Comment by joekman990** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/ed7f11f2-61f8-4c11-ae37-d6c2a120b676

thank you for the quick response!

**Comment by paulperez-dev** [comment]
Hi @joekman990, thanks for the video evidence! We will be looking into this!

**Comment by ignalauret** [comment]
Hey @joekman990 thanks for your report and all your help. Sadly we are able to see the Algolia results on the newest version on FlutterFlow following your steps, and I can't see anything wrong with your setup. So now the technical team is going to check it out, given that this looks like a project specific issue that you are having. <br>They will keep you updated on this thread, have a great day!

**Comment by joekman990** [comment]
🙏

**Comment by takashiff** [comment]
Hi @joekman990! Thanks for the bug report. We've taken an additional look at your project and can confirm that Algolia search is not working in Test Mode. However, we are still currently unable to reproduce it in our own blank project, which leads me to believe that this may be an issue with your Algolia project configurations. Could you confirm that you've completed [the following steps](https://docs.flutterflow.io/data-and-backend/searching-data/algolia-search#using-algolia-search) found in the documentation? Thanks!

**Comment by joekman990** [comment]
yes i did and what is interesting is that i was able to create a custom action that made the algolia call and did not have any issues it was only when i used the native FlutterFlow integration that i did not receive any results

**Comment by leighajarett** [comment]
I'm sorry but we are unable to reproduce this issue from a blank project, can you please reach out to support@flutterflow.io? They can better assist you with ensuring your project is configured correctly!
