### ISSUE TITLE
When entering a value in the Items from a constant list the expandable closes

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2757]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When entering a value in the Items from a constant list the expandable closes

### Expected Behavior

Should be able to continue writing without closing the expandable

### Steps to Reproduce

1. Create a constant list
2. Add some values to the list
3. After writing a value automatically, the expandible closes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olcmAvIVIsctF0L6JcMdVryQXH1w+RIEo18pBZywgfZzzBLN/fPfQP0ptOcTiY2x+eGGMp14e0s6KjYTtGvECG0+BbphDypBIFhXKIWSgVp+TF7qKPEFtONJbN0C915ivsx1CWdV1SmAC23GQAuesST7ZGIzsIXo4Sq/LZO4=

### Context

I want to set some values for a constant list

### Visual documentation

[https://www.loom.com/share/a91b82642c2449d49314cbeffb1fdeeb](https://www.loom.com/share/a91b82642c2449d49314cbeffb1fdeeb)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 16, 2024
- Platform: Web
- Browser name and version: Chrome 123.0.6312.107 (Official Build) (64-bit)
- Operating system and version affected: W11
```

**Comment by paulperez-dev** [comment]
Hi @Franco98404, thanks for your report! I was able to reproduce the issue, I'm sending this to the ENG team, so they can take a look.
