### ISSUE TITLE
DateTime send to supabase database lacks timezone details

### ISSUE THREAD

**Issue by darylpeter** [FlutterFlow/flutterflow-issues#2759]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is a follow on from DateTime send to supabase database lacks timezone details #2393. It was closed mentioning that it's a duplicate issue with [https://github.com/FlutterFlow/flutterflow-issues/issues/2125](https://github.com/FlutterFlow/flutterflow-issues/issues/2125) however this isn't the case. This is about saving records into supabase, they're always saved in UTC time no matter the time zone of the user saving it.

Here's an example of a record saved into Supabase - 2024-04-18T19:19:17.510148+00:00.

You can see it's saving it as UTC despite my time zone being +10, it's repeatable on a browser or iOS device.

### Expected Behavior

When saving into Supabase, it should append the correct time zone to the record saved as a timestamptz.

### Steps to Reproduce

1. Create a page with a button /action. that send datime time info to a supabase row
2. Create supabase table with timestamptz
3. Add a place holder time , using now() to create a specific time in supabase
4. Update the row with datetime from Fluterflow and observe the time zone is not sent

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grtRI+qr2Le56hQAkH1x/bZJEl9cacw8jIqmvPYoqeOr+VxFeOO3mTW5+JGelq3ID0cmOvofqGvFdKTKCQoNowod+Qw3dXkmmbrWYBs+Cf39tO5lXI0iF0benoRFCPs9eS3xmw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

It affects anyone wanting to have time zone compensation displayed.

E.g if I have users in two time zones, -8 and +10, and I'm displaying when a record that shows the time it was added, it's possible the record will display to the -8 user as being added in the future.

### Visual documentation

N/A

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Web or iOS
- Browser name and version: Edge Version 123.0.2420.97
- Operating system and version affected: Any
```

**Comment by Dbrrohof** [comment]
Hi @darylpeter, don' want to hijack this post, but comparing different timezones will be a hassle for your app in the future.
It is better pratice to use a default timezone for all data in your database, and then in the app display it in the users locale timezone.

Here is a more detailed explanation on the topic: https://dev.to/linhvuquach/how-to-save-datetime-data-that-is-relevant-to-multiple-countries-or-time-zones-54io

**Comment by mailbox4ashish** [comment]
I am running into the same issue reported here. Would be great if an update or solution can be shared on the post

**Comment by eccentrex** [comment]
I understand that this is something that can be "fixed" by workaround using different timezone adjustment within FlutterFlow.  How would this work for a user who changes time zones / travels.  Can FlutterFlow "identify" the timezone we are in?  

It seems that with the many other workarounds we have had to do in the last year or two, the flutterflow team has done a great job at incorporating much more complicated fixes and improvements.  

There has already been a great suggestion above by @Franco98404 .  I would be ok with that.  I would add that there could be a local variable where the timezone is set or linking with geolocation services to provide this info as a local variable.  Some provisions for daylight savings time could be a whole other conversation, first I would like to motion interest in this issue and finding a solution beyond user input.  

Some additional info for how I will be using this, I have users record their location as a city and country, I am able to assign timezones in my lookup table (backend, supabase), I would need something to use to reference them.  It is important to me that the timestamp in my backend is correctly recorded.

**Comment by MrRongoose** [comment]
I see this error as today. A date/time picked in the picker saves to Supabase as HH:MM:SS+0 despite my timezone being -5

**Comment by eccentrex** [comment]
Maybe we could get some feedback on whether this is something that should be looked at from the FlutterFlow side or are we expected to have to deal with it on our own end for the foreseeable future.  It would assist in planning for our apps!  Thanks ahead of time @paulperez-dev !

**Comment by paulperez-dev** [comment]
Hi everyone! Sorry for the late response! This is not a bug. Setting the table column as a `timestamptz` does not force the conversion from FF. The `Current Time` global property always returns the timestamp in local. You need to convert the value before sending it to Supabase.

**Comment by banza92** [comment]
Does anybody know what the solution to this is? Times in Supabase are being correctly recorded but in Flutterflow they display as off by a couple of hours. What do I do?
