### ISSUE TITLE
[SOLVED] Cannot upload image to Firebase

### ISSUE THREAD

**Issue by Mnsrff** [FlutterFlow/flutterflow-issues#276]
Hello,

Firebase is connected, working correctly (everything is okay with all of other functions in the project).

But instead of "Upload Media to Firebase" I can select "Upload to Local File" only.

The base rules are correct, the scheme is validated, the rules are deployed, the storage rules have been modified ("allow read, write: if false;" > "allow read, write: if true;"), image can be uploaded through "Manage Content" section with no problem.

But it doesn't work for some reason...

![upload-media](https://user-images.githubusercontent.com/80708492/209479698-79f48411-6fc8-467a-a367-39df7a8e9bdc.png)

**Comment by Mnsrff** [comment]
![fb-query](https://user-images.githubusercontent.com/80708492/209556876-f0d0ef6e-5320-4cc1-998c-9fd9b4ad9f8b.png)
![fb-scheme](https://user-images.githubusercontent.com/80708492/209556888-3a5581c7-05c4-4f30-bbfc-982c05abb6cc.png)
![fb-rules](https://user-images.githubusercontent.com/80708492/209556898-933377e9-280e-4185-af62-d1249b2279ea.png)
![storage-rules](https://user-images.githubusercontent.com/80708492/209556904-d0da5974-7dce-4917-a817-114f0997c1dc.png)

**Comment by agreaves** [comment]
Hi @Mnsrff, can you please include a Bug Report Code for your project (right click anywhere on the widget tree to generate)? Thanks!

Are there any project errors? My guess is that you haven't fully configured your project for authentication (i.e. haven't selected the Entry and Home pages of your app).

**Comment by Mnsrff** [comment]
> Hi @Mnsrff, can you please include a Bug Report Code for your project (right click anywhere on the widget tree to generate)? Thanks!
> 
> Are there any project errors? My guess is that you haven't fully configured your project for authentication (i.e. haven't selected the Entry and Home pages of your app).

THANK YOU SO MUCH!!

I turned it on here and everything works now:
![изображение](https://user-images.githubusercontent.com/80708492/209577556-ec3d0af4-5dc9-4cbc-9a27-1ff68019371e.png)

I just don't use authentification as it's my personal project :) First steps in FlutterFlow...
