### ISSUE TITLE
DatePicker to get only time do not accept 00:00 in keyboard mode - it shows Enter a valid time

### ISSUE THREAD

**Issue by luisaoba** [FlutterFlow/flutterflow-issues#2760]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello FlutterFlow Team,

I'm encountering an issue while using the 'IconButton' associated with the 'Date/Time Picker' action in my application. My intention is to type the time, using keyboard, however, upon clicking the button, I'm directed to a clock where I can see the hour and minute. I found a button that allows me to switch the input mode, represented by a keyboard icon. Upon selecting it, I'm taken to a screen with the time initialized as '00:00' and an "OK" button. The problem arises when I confirm the selection by pressing the "OK" button, receiving the error 'Enter a valid time'.

I would like to request a fix for this issue, as it is crucial for my application that the selected time is '00:00'. Thank you in advance for your attention and assistance.

Best regards,

![Captura de tela 2024-04-18 123425](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2468f145-7db5-4268-ab08-f743f4b10dc8/9b567c00-a3c4-4292-a913-ddd7aae0818f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNDY4ZjE0NS03ZGI1LTQyNjgtYWIwOC1mNzQzZjRiMTBkYzgvOWI1NjdjMDAtYTNjNC00MjkyLWE5MTMtZGRkN2FhZTA4MThmIiwiaWF0IjoxNzEzNDg1NDEwLCJleHAiOjMzMjg0MDQ1NDEwfQ.Tz08frxu6bM2P_sN-AZC9IMujg6jr-t4-nJVIbSydL0)

![Captura de tela 2024-04-18 123605](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/07b8ad93-4c0d-4329-a73f-9d57f8aba3a3/3666c810-2a7f-4eb6-b1df-f52bdd010f73?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wN2I4YWQ5My00YzBkLTQzMjktYTczZi05ZDU3ZjhhYmEzYTMvMzY2NmM4MTAtMmE3Zi00ZWI2LWIxZGYtZjUyYmRkMDEwZjczIiwiaWF0IjoxNzEzNDg1NDEwLCJleHAiOjMzMjg0MDQ1NDEwfQ.1-PUpYIHlZelAWM2sKR_RJPQe-S4OxpkaQBiG7QHAZg)

![Captura de tela 2024-04-18 123643](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/13bfe963-c382-41a7-93b5-8c10e0a85ff1/f7f5532f-b438-4ba2-812d-879518bb63bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xM2JmZTk2My1jMzgyLTQxYTctOTNiNS04YzEwZTBhODVmZjEvZjdmNTUzMmYtYjQzOC00YmEyLTgxMmQtODc5NTE4YmI2M2JiIiwiaWF0IjoxNzEzNDg1NDEwLCJleHAiOjMzMjg0MDQ1NDEwfQ.P2weIYVtdjw032DEPGDKqPX0tWyJh0g2OsURNpkd294)

### Expected Behavior

Accept time 00:00 in keyboard mode

### Steps to Reproduce

1. Create an iconButton and associate an action DateTime Picker and get only time.
2. Click in Test Mode
3. Click in the button (step 1) and click in the icon keyboard
4. Set to 00:00
5. Click OK.
6. Error - Enter a valid time

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

nocodeerror

### Context

It is an error during test mode.

### Visual documentation

![Captura de tela 2024-04-18 123425](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/80d3d452-35c4-44bf-9f9b-7f750ad0ff6a/c82b64e2-4380-4206-982c-d5d19e161349?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MGQzZDQ1Mi0zNWM0LTQ0YmYtOWY5Yi03Zjc1MGFkMGZmNmEvYzgyYjY0ZTItNDM4MC00MjA2LTk4MmMtZDVkMTllMTYxMzQ5IiwiaWF0IjoxNzEzNDg1NDEwLCJleHAiOjMzMjg0MDQ1NDEwfQ.oADb6Qne8KBgYfkQCQKssIGeOxvbCcvp8TFAIIH8vbk)

![Captura de tela 2024-04-18 123605](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/185cdcce-7014-4eca-99c9-65bdeb775d78/7faf097c-a7be-426f-8a9f-df6e02e0e833?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xODVjZGNjZS03MDE0LTRlY2EtOTljOS02NWJkZWI3NzVkNzgvN2ZhZjA5N2MtYTdiZS00MjZmLThhOWYtZGY2ZTAyZTBlODMzIiwiaWF0IjoxNzEzNDg1NDEwLCJleHAiOjMzMjg0MDQ1NDEwfQ.cz-i9icIworwzkpCkKdYGliC5UmAHMHtdze-O6LZVZw)

![Captura de tela 2024-04-18 123643](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/870fe69f-a438-4455-b78c-fbb3e10b0e83/b8f6d9f1-f774-4ba2-8b9e-cc216558d90a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NzBmZTY5Zi1hNDM4LTQ0NTUtYjc4Yy1mYmIzZTEwYjBlODMvYjhmNmQ5ZjEtZjc3NC00YmEyLThiOWUtY2MyMTY1NThkOTBhIiwiaWF0IjoxNzEzNDg1NDEwLCJleHAiOjMzMjg0MDQ1NDEwfQ.yNKZk0kyzWTvDWPPVoTCpy3n5Hm_XMvfa4ACthod8q0)

### Additional Info

Apart from the aforementioned issue, I've noticed another issue in a form containing a text field that is mandatory. FlutterFlow accepts whitespaces as input, allowing users to bypass the mandatory field validation by entering only whitespace characters. How can this be prevented?

### Environment

```markdown
- FlutterFlow version: 4.1.34 - 3.19.1
- Platform: PC
- Browser name and version: Chrome 124.0.6367.60 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11 PRO 10.0.22631 comp.22631
```

**Comment by paulperez-dev** [comment]
Hi @luisaoba, thanks for your report! I was not able to replicate the issue. Can you please confirm if you can reproduce the issue from a blank project? If so, please share the bug code report.

Also, the 00:00 is not a valid value, you should use 12:00 am or pm.

**Comment by luisaoba** [comment]
Hello @paulperez-dev . Thank you for your time. The hour 00:00 is a validade hour in Brazil, and in The datetime Picker (only time) when you not use keyboard, just mouse, to define the time. I describe the steps in a blank Project above. Also i can not define Am ou PM using This Interface. In Brazil we use from 00:00 tô 23:59 hour.

**Comment by rzambroni** [comment]
Hey @luisaoba, I'm also not being able to replicate this. However, i think that the web testing tool might be confused by the browser config and it is validating it as if it was a 12hs format, that's why 00:00 is throwing that error. Can you give it a quick try on a device? Here is an example i did:

[Simulator Screen Recording - iPhone 15 Pro Max - 2024-04-23 at 23.37.20.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/30e20e17-e667-4a19-b4fc-c89b3153e15a/255283c5-fcde-4e35-9e73-4a3302fd2fd7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMGUyMGUxNy1lNjY3LTRhMTktYjRmYy1jODliMzE1M2UxNWEvMjU1MjgzYzUtZmNkZS00ZTM1LTllNzMtNGEzMzAyZmQyZmQ3IiwiaWF0IjoxNzEzOTI2NjY1LCJleHAiOjMzMjg0NDg2NjY1fQ.6kCTCptPYs5Rp4fh334nqkRRy10zbGOXeLYcWUQO6nA)

**Comment by rzambroni** [comment]
Also, @luisoba, regarding the issue you are having with blank spaces on mandatory fields. <br>Here are a few solutions from the community that might come in handy: [https://community.flutterflow.io/ask-the-community/post/prevent-whitespaces-in-textfield-widget-L1JtFjjwcZoDak1](https://community.flutterflow.io/ask-the-community/post/prevent-whitespaces-in-textfield-widget-L1JtFjjwcZoDak1)
