### ISSUE TITLE
Textfield "On Focus Change" action issue

### ISSUE THREAD

**Issue by leobewater** [FlutterFlow/flutterflow-issues#2761]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The textField "On Focus Change" event does get fired when clicking on the empty space or hitting the Enter key after typing. It doesn't get fired after typing without hitting the Enter key and click a button right away.

### Expected Behavior

Expect the "On Focus Change" fired before clicking on other button

### Steps to Reproduce

Please look at my demo project [https://app.flutterflow.io/project/focus-issue-0d75j4](https://app.flutterflow.io/project/focus-issue-0d75j4) . The "On Focus Change" event is hooked in the ItemComponent TextField.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksmAx85Pj7xA1872KPlR/CcvNWl+aL8sscpFcxQcB4jZP4kQfPfQPhZpZMOiTGxUOE62p141wsr8vYbxUfU4AzOtY486/qVUZTrwfF66bpeTF7mSeX96BZ9jGEC455m3phQnIsB1LE4G1E+INfKvQgrYQ67tIVQ8Sq/LZO4=

### Context

It's a bug

### Visual documentation

none

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.40
- Platform: macOS
- Browser name and version: iPhone Simulator
- Operating system and version affected: all
```

**Comment by paulperez-dev** [comment]
Hi @leobewater, thanks for your report!

To better understand what you are facing:

\-Can you please provide us with a step-by-step on reproducing the issue?

\-Please provide context on what you are trying to do.

**Comment by leobewater** [comment]
1. Start a new project, set up a "Data Type" called "Item" with "title" as String
2. Add an App State variable "appItems" with the List<Item>

3. Set up a Component called "ItemComponent" with Index (integer) and ItemRow (Data<Item>) as component parameters.
![Screenshot 2024-04-19 at 4 12 59 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/10247575/09787c8a-52ab-489b-bd3f-3f357168e587)

4. Add a TextField in the ItemComponent with action "On Focus Change" to "Update App State"
![Screenshot 2024-04-19 at 4 12 01 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/10247575/aabce7f9-d1ea-4896-879c-4baeebffcc55)

5. In the Homepage, add a ListView and set up the dynamic children variable called "itemList" with value from the "appItems"
![Screenshot 2024-04-19 at 4 14 40 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/10247575/5e4a43f7-dc84-4219-80e5-2f6757e3c1e4)

6. In the ListView add the component "ItemComponent" as the children, assign the "Index in List" to the required component param "index" and "itemList->item" to the param "itemRow"  
![Screenshot 2024-04-19 at 4 16 46 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/10247575/fd73af6a-86f3-4bea-9c7d-58ebcf150738)

7. Add a "Add Item" button outside of the ListView with an action to "Update App State" and "Add to List" to the "appItems."

When typing the text in a the first textfield and hit "Enter", it does keep the text in the text field as the "OnFocusChange" kicked in. But if you type some text "ABCD" without hitting "Enter" and click the "Add Item" button, it adds a new row/item, but the text "ABCD" in the previous row is gone, the OnFocusChange never kicks.

Please look at https://app.flutterflow.io/project/focus-issue-0d75j4 .

thanks

**Comment by paulperez-dev** [comment]
Hi @leobewater, thanks for the detailed steps. The [OnFocusChange ](https://docs.flutterflow.io/widgets-and-components/widgets/form-elements-1/textfield#focus-change-event)event is used to know when the widget or component is selected. You should use the OnSubmit event that is fired when the user hits Enter. <br><br>Other things to consider:<br>-When updating the AppState, use the widget value, not the component value (which is empty), so the introduced value is saved.

\-Verify the component is receiving the correct value when loading, so it can be displayed.

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, thanks!
