### ISSUE TITLE
Listview using sort order, delete doc only deleting order field

### ISSUE THREAD

**Issue by pjc10** [FlutterFlow/flutterflow-issues#2762]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using a listview with a custom sort after following [this doc](https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/listview#reorder-list) using the firebase query instructions (all that works great).

Delete button/action it's deleting the 'order' field (A) in screenshot, not the whole document after double checking the results in firebase...

![Screen Shot 2024-04-18 at 1 55 37 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6a2ee8f-26fe-4c2a-9144-e5fe50a0b06c/68b216ab-8c9f-4b56-9ce6-a4dde87e1fb1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNmEyZWU4Zi0yNmZlLTRjMmEtOTE0NC1lNWZlNTBhMGIwNmMvNjhiMjE2YWItOGM5Zi00YjU2LTljZTYtYTRkZGU4N2UxZmIxIiwiaWF0IjoxNzEzNDgwNjMzLCJleHAiOjMzMjg0MDQwNjMzfQ.BpKk_wtT-x1lH6Sb9_4ixoLVJfC5o2_i47JvY4CJehk "=710x")

### Expected Behavior

Delete document/all fields, B in

![Screen Shot 2024-04-18 at 1 55 37 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f5fa3a15-e28e-419c-a92e-b1891f1fb4e7/bfa40ea8-9098-487d-805e-a2bd923c8268?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNWZhM2ExNS1lMjhlLTQxOWMtYTkyZS1iMTg5MWYxZmI0ZTcvYmZhNDBlYTgtOTA5OC00ODdkLTgwNWUtYTJiZDkyM2M4MjY4IiwiaWF0IjoxNzEzNDgwNjMzLCJleHAiOjMzMjg0MDQwNjMzfQ.gFEJviaXLoDSmcKirHA1sGEHGrBA-YJ9Sswg-NFk0V0 "=710x")

screenshot.

### Steps to Reproduce

Action on button click inside of listview item

On Tap - Backend Call: Delete Document

Reference to to delete
\-Set Variable, Type Doc Reference
Variable: TaskDocument - Reference
Available options: Get Document Property
Doc Properties: Reference

![Screen Shot 2024-04-16 at 8 20 24 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dd8ef2e2-7bab-4a15-921e-dd0c53a306fb/47cc7123-f5c8-4297-9740-14a4eb9463bc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZDhlZjJlMi03YmFiLTRhMTUtOTIxZS1kZDBjNTNhMzA2ZmIvNDdjYzcxMjMtZjVjOC00Mjk3LTk3NDAtMTRhNGViOTQ2M2JjIiwiaWF0IjoxNzEzNDgwNjMzLCJleHAiOjMzMjg0MDQwNjMzfQ.WuHdjl-d-MHLKGB_QOVmxwpvKGUEHWWPuZgUr5DTskc "=878x")

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfheflsYtPvsRE+a6JYPloqDg6JUscTOURiO0bFDsdF4iuPOxzaczsYhJuOPW8YGNHKEWGjnoFwfTVjuOWCvkCAyuVc7Z8/pd+cRbMWn2/aoTSBZeddEElM+JgJly60qa7ux5+BMBsdFIl7VymJeqtbHbYHY/7Zwh9f6PHaOI=

### Context

Cant delete entries

### Visual documentation

![Screen Shot 2024-04-16 at 8 20 24 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/02b0b2b3-0266-40e1-a79d-525e51cc470c/670f29a9-903d-4d8d-bea5-a338e9d46b49?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMmIwYjJiMy0wMjY2LTQwZTEtYTc5ZC01MjVlNTFjYzQ3MGMvNjcwZjI5YTktOTAzZC00ZDhkLWJlYTUtYTMzOGU5ZDQ2YjQ5IiwiaWF0IjoxNzEzNDgwNjMzLCJleHAiOjMzMjg0MDQwNjMzfQ.0hZ_6HfOk39f4E25bWfH4QIVsodzLG5INaiiFFFg25c "=878x")

![Screen Shot 2024-04-18 at 1 55 37 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/db093259-f6db-4d3d-a9ac-ce371435bbd7/aa2db4b7-61de-464a-99aa-3a0a6e7d5867?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYjA5MzI1OS1mNmRiLTRkM2QtYTlhYy1jZTM3MTQzNWJiZDcvYWEyZGI0YjctNjFkZS00NjRhLTk5YWEtM2EwYTZlN2Q1ODY3IiwiaWF0IjoxNzEzNDgwNjMzLCJleHAiOjMzMjg0MDQwNjMzfQ.k77ssgV487oYfDjaNV4ya2N1-u45WLOvw7nIgUw6lRE "=710x")

### Additional Info

already attached

### Environment

```markdown
- FlutterFlow version: 4.1.34 - flutter 3.19.1
- Platform: Mac
- Browser name and version: Chrome Version 123.0.6312.123 (Official Build) (x86_64)
- Operating system and version affected: macOS Monterey 12.7
```

**Comment by paulperez-dev** [comment]
Hi @pjc10, thanks for your report! I was trying to replicate the issue on a blank project so I could better isolate the issue with the component, but I was unable to do so. It is working well on my end.

Are you able to reproduce this issue on a blank project? if so, could you please share the bug report code of that blank project?

It would help us a lot, so we can discard project-specific issues and better isolate the problem with the component.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you, thanks!
