### ISSUE TITLE
Firebase not initializing when running windows

### ISSUE THREAD

**Issue by zeymermontes** [FlutterFlow/flutterflow-issues#2766]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to run local run a windows app using Firebase you get the following error

√ Built build\\windows\\x64\\runner\\Debug\\slot_f_b.exe.
\[ERROR:flutter/runtime/dart_vm_initializer.cc(41)\] Unhandled Exception: \[core/not-initialized\] Firebase has not been correctly initialized.

Usually this means you've attempted to use a Firebase service before calling `Firebase.initializeApp`.

View the documentation for more information: [https://firebase.flutter.dev/docs/overview#initialization](https://firebase.flutter.dev/docs/overview#initialization)

Also the project window opens but it never loads.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e40e0bb3-5aa2-4501-998b-466a48b6bc39/b2ab0539-2a98-49ca-ae4a-8e40a2513953?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNDBlMGJiMy01YWEyLTQ1MDEtOTk4Yi00NjZhNDhiNmJjMzkvYjJhYjA1MzktMmE5OC00OWNhLWFlNGEtOGU0MGEyNTEzOTUzIiwiaWF0IjoxNzEzNTM0NDA3LCJleHAiOjMzMjg0MDk0NDA3fQ.dNPn380V6FyCYGBEoQOhWSAwgUj7zeAflcyc_TaDMtk)

### Expected Behavior

Firebase initialize correctly and page loads content.

### Steps to Reproduce

1.Create a Project
2\. Add Firebase to the project
3\. Add a query to the project
4\. Local Run project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhcn1sM9godRE7ZSJKMJohiMXNWkcTL4zlO1HcxAYGO/yPbJ/YeDSUxFDTtOnd1NhHGaGq3Eepcruit/tJfVfOQWAY6pAz7ltWDvjRXq8R4yvOqqWYEckI9xjCky404m7rRZ+NrRpdVYa2lOuAOyWQi7vJ5+/Zwh9f6PHaOI=

### Context

Its imposible to test the app.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/170da94c-ab79-4d6f-ab7c-ee42e7d46364/dc176b94-8602-4241-8c72-3270cc947ff9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzBkYTk0Yy1hYjc5LTRkNmYtYWI3Yy1lZTQyZTdkNDYzNjQvZGMxNzZiOTQtODYwMi00MjQxLThjNzItMzI3MGNjOTQ3ZmY5IiwiaWF0IjoxNzEzNTM0NDA3LCJleHAiOjMzMjg0MDk0NDA3fQ.ru1JBufCN04XmgnnynYOhVNqzjkp1ix6ySjm4QeU0tA)

### Additional Info

solutions to the bug:
Solution 1:

Firebase now supports windows platform:
[https://youtu.be/ba1IvQU1kgo?t=104](https://youtu.be/ba1IvQU1kgo?t=104)

The command
flutterfire configure
Can be used for adding windows support and that will add windows to the default firebase config file then this can be used

await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);

Solution 2:

Since firebase is usign the same config as web its as easy as to modify the following in firebase_config.dart :

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'dart:io'; //add dart:io to the file

Future initFirebase() async {
  if (kIsWeb || Platform.isWindows) { // Add || Platform.isWindows to this conditional
    await Firebase.initializeApp(
        options: FirebaseOptions(
            apiKey: ".........",
            authDomain: ".........",
            projectId: ".........",
            storageBucket: "...........",
            messagingSenderId: ".......",
            appId: "..........",
            measurementId: "........"));
  } else {
    await Firebase.initializeApp();
  }
}

by adding this 2 lines windows projects will run with no problem

### Environment

```markdown
- FlutterFlow version: 4.1.38+
- Platform: windows
- Browser name and version: windows
- Operating system and version affected: windows
```

**Comment by rzambroni** [comment]
Hi @zeymermontes,

thanks a lot for the report, this was already reported a few days ago and was sent to engineering so they can take a look. 

I'm going to close this issue in favor of the older one, you can follow the status here: [https://github.com/FlutterFlow/flutterflow-issues/issues/2650](https://github.com/FlutterFlow/flutterflow-issues/issues/2650)
