### ISSUE TITLE
Undoing changes apparently due to a layout error when there is not one

### ISSUE THREAD

**Issue by alexjordi** [FlutterFlow/flutterflow-issues#2767]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

[https://github.com/FlutterFlow/flutterflow-issues/assets/129039815/7e715512-0c47-4fb7-b16f-a75c8e2810c0](https://github.com/FlutterFlow/flutterflow-issues/assets/129039815/7e715512-0c47-4fb7-b16f-a75c8e2810c0)

### Expected Behavior

Well it should clearly not do that.

### Steps to Reproduce

1. create a component to be used as a custom dialog
2. create an action on another page which brings up that custom dialog
3. change something on the custom dialog
4. use the top right return page button
5. you should see it undoing your component change for no reason

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xi8rlvI9OrttE+KXiafpVhiMvIjs4arhEiet+b0g1GKnkP5k2e/TET3JdOLyhSmw/PFu0ijky3NbIkdn1U+QHAzGtGrpM+LpIEgHyUkm5WrKJPZCoekF6J9FTNEuV0bSzmwp5COpsc2Q96jqyH+qtXgvdJITbC1gRLc+LOrLU+0mrAi+6Xn0Jg1ZSfCvr

### Context

Its a bad bug because it undoes changes randomly. its not always easy to know that your changes have been undone.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/129039815/81d78273-bcdb-4c0d-bf0c-ab6f9b2572c8](https://github.com/FlutterFlow/flutterflow-issues/assets/129039815/81d78273-bcdb-4c0d-bf0c-ab6f9b2572c8)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.41
- Platform: Windows
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hey @alexjordi, I attempted to replicate this issue on a blank project, but unfortunately, I couldn't. Could you please provide a blank project example where this issue can be replicated? This will help us isolate the problem from potential project-specific issues and troubleshoot it more efficiently.

Thanks.

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, thanks!

**Comment by alexjordi** [comment]
Hi

I haven't been able to replicate it yet on a blank project as I've been
working on an update. But it's continued to happen to me. When I have time
I will try to replicate it.

**Comment by leighajarett** [comment]
Sounds good, please submit a new issue when you have the steps to reproduce.
