### ISSUE TITLE
Color picker shows white box instead of gradient on iOS

### ISSUE THREAD

**Issue by smplfy** [FlutterFlow/flutterflow-issues#2770]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the color picker selector from a button on iOS the large color view showing a gradient to select shows a white box. When you touch different portions of that box you get flickering on the screen.

### Expected Behavior

Color picker should show a gradient to allow the user to select a color.

### Steps to Reproduce

1. Create a new button with the Color Picker action
2. Deploy or test on iOS device
3. Tap button to experience this behavior

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otIsdtK0LrUbPl7/GQ4OUgjbZ0kscsZa0kdB4joPLJ/Z86lTFBuZ9Oid1NhHFCIinkxpK3wkfL9A/E4JgqeG5xm1qhUeBf/e3q8RbKQPZCCYGt6MJlUGhGnyLuokSJCIsZYWk4O70+Tf+ytQh3dJ5+/Zwh9f6PHaOI=

### Context

This prevents the user from selecting the color by displaying a broken UX.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/1328771/b3a661dd-0f12-47cd-8292-698276b9ccc7](https://github.com/FlutterFlow/flutterflow-issues/assets/1328771/b3a661dd-0f12-47cd-8292-698276b9ccc7)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.40
- Platform: MacOS
- Browser name and version: NA
- Operating system and version affected: iOS 17.4.1
```

**Comment by rzambroni** [comment]
Hey @smplfy, thanks for the report, i was trying to replicate this issue but i'm unable to do so. Is working well on my end. Tested a couple IOS devices and both dark and light modes. Can you replicate this consistently? If so, could you share the details of the device you were using?

**Comment by smplfy** [comment]
Hi, thanks for the response. Yeah I see it consistently, in my primary app and the demo app I created for testing. I’ve also tested on multiple devices.Device 1: iPhone 15 Pro, iOS 17.4.1Device 2: iPhone 15 Pro Max, 17.4.1These were tested both in debug mode and through TestFlight. Each device is owned by a different person in different locations.Here’s a link to a video of the behavior in my primary app:1 Videoshare.icloud.comThanks again,DanielOn Apr 21, 2024, at 8:35 PM, rzambroni ***@***.***> wrote:﻿
Hey @smplfy, thanks for the report, i was trying to replicate this issue but i'm unable to do so. Is working well on my end. Tested a couple IOS devices and both dark and light modes. Can you replicate this consistently? If so, could you share the details of the device you were using?

**Comment by rzambroni** [comment]
Hey @smpify, will ask a few others to take a look since i can't replicate this. Will let you know when we have more info.

Thanks!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/439af9d3-3fd6-46dc-aae7-3b42f253cb78/10241227-5a94-433f-b8c3-3b13e0eadc6f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MzlhZjlkMy0zZmQ2LTQ2ZGMtYWFlNy0zYjQyZjI1M2NiNzgvMTAyNDEyMjctNWE5NC00MzNmLWI4YzMtM2IxM2UwZWFkYzZmIiwiaWF0IjoxNzEzNzk0Mjc4LCJleHAiOjMzMjg0MzU0Mjc4fQ.G9_aHB9CIZTUpD2owqxWwZNngnLMkptNjuz7fCoCvVE " alt="image.png" width="473" height="1038" />

**Comment by smplfy** [comment]
It does seem to work fine in the simulator, but not on device.

**Comment by smplfy** [comment]
I can confirm all TestFlight users on iPhone are experiencing this issue

**Comment by rzambroni** [comment]
Hey there, thanks for the additional context, i confirmed the issue and as you said it is happening on physical devices.

I Will send it to the team so they can take a look.

Thanks for the report!

**Comment by rzambroni** [comment]
Hey @smplfy, the team just told me that there is a fix already in place for this. It should be available on next week's release. 🙂

**Comment by smplfy** [comment]
Unfortunately, the update today did not change the experience for iPhone users. The color selector referenced in the release is the dev one inside FF I believe. Please let me know

**Comment by ranjithqaptive** [comment]
Currently I'm also facing this issue. Works fine on Simulator not on real device. I'm using this package "flutter_colorpicker: ^1.0.3". I've tried another one too. both didn't work. What package are you using.?

**Comment by SunFloat** [comment]
I have the same problem as ranjithqaptive describes, the color values ​​are adopted when a change is made, but the user still only sees a white frame

**Comment by blackdede** [comment]
Hello, any news on this issue ?
