### ISSUE TITLE
Feature Request - Ability to Clone into one of our existing project since we cannot copy pages/components across

### ISSUE THREAD

**Issue by unibum** [FlutterFlow/flutterflow-issues#2773]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Cloning or using marketplace creates new project, where we cannot copy/move the desired pages or components into our own project to enhance/use.

### Expected Behavior

Ideally, clone into a project of your choice. since you are logged in, generate list of your projects. pages and components etc are copied into a new folder of same name of clone so can easily find and move out pages etc as required for management.

a more preferred / scalable solution is to be able to copy between projects.. because you might want to reuse from another previous project and saving as templates doesnt appear to work/flexible enough and lose code/logic etc.. we want everything to copy across and not lose anything.

### Steps to Reproduce

there is none

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Makes clones and marketplace unusable..

### Visual documentation

na

### Additional Info

na

### Environment

```markdown
- FlutterFlow version: all
- Platform: all
- Browser name and version: all
- Operating system and version affected: win 11
```

**Comment by paulperez-dev** [comment]
Hey @unibum, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
