### ISSUE TITLE
Feature Request - as a privileged admin (separate email/login creds) ability to hide and/or restrict 'copy' of projects and/or pages/components when I share/invite 3rd party's to work on my project

### ISSUE THREAD

**Issue by unibum** [FlutterFlow/flutterflow-issues#2774]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Cant hide/restrict 3rd parties in enough details

### Expected Behavior

As a privileged admin (separate email/login creds) ability to hide and/or restrict 'copy' of projects and/or pages/components when I share/invite 3rd party's to work on my project. i.e. I may have something secret and I need help or some development on another page from a 3rd party..
A prefer a separate privileged admin role because maybe too many pages need fixing but have some you still want to hide.. so easier to change local password, give creds to 3rd party to fix, and then once done change creds back.. but 3rd party wont have ability to change visibility rules while logged in as you..

Ideally can ALSO create a new blank page and only assign visibility/access to it and any components etc they create.

privileged admin should use originally registered email acc (cannot change without password) in case 3rd party goes rogue and tries to hijack acc, can at least log back in as privileged and either change local email and password or password reset link to original email acc details, or contact you guys for support.

### Steps to Reproduce

NA

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

hard to trust/engage 3rd parties for development or for bug fixing..
Cannot hide commercially sensitive info or ideas from 3rs parties..

### Visual documentation

NA

### Additional Info

NA

### Environment

```markdown
- FlutterFlow version: all
- Platform: all
- Browser name and version: all
- Operating system and version affected: all
```

**Comment by paulperez-dev** [comment]
Hey @unibum, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
