### ISSUE TITLE
Feature Request - OpenStreetMap integration

### ISSUE THREAD

**Issue by unibum** [FlutterFlow/flutterflow-issues#2776]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Appreciate all the google plugins like maps, but great to have other 'free' options who dont want to be tied into cloud or vendor.
thank you for your consideration.

### Expected Behavior

Appreciate all the google plugins like maps, but great to have other 'free' options who dont want to be tied into cloud or vendor.
thank you for your consideration.
OpenStreetMap
long way down the line but some architecture patterns/apps other than just app direct to Db connectivity.. something we can click and deploy onto a host and have working.. some webserver, middleware and API layer in between, auth/jwt tokens, etc. for me, postgres is my target but supabase version has api throughput limitations and also APIs not what im wanting to use.. something dockerised (self hosting) preconfigured proper solution which we can just drop flutter files on and magic happens) is wishful thinking.. but something little more production/scalable ready than current db plugins would be great..

### Steps to Reproduce

NA

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

NA

### Visual documentation

NA

### Additional Info

NA

### Environment

```markdown
- FlutterFlow version: all
- Platform: all
- Browser name and version: all
- Operating system and version affected: all
```

**Comment by paulperez-dev** [comment]
Hi @unibum, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. 

Thanks for your feedback!

**Comment by Tobias1967** [comment]
Hello!
I would have just the same question!
On my other project, that I develop in Flutter (not Flow!) I have an working code with OpenStreetMaps and even an operating layer for satellite image. 
How could I integrate this in my Flutter FLOW app?
I would like to compare, if I can develop much faster with Flutter Flow, than coding everything by hand in VS-Code. Is there any way to copy code to Flutter Flow?
Best regards
Tobias Schorr (beginner)
