### ISSUE TITLE
Mask Problem Desktop MacOS

### ISSUE THREAD

**Issue by rcunhadf** [FlutterFlow/flutterflow-issues#2779]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When hot reloading in desktop macos and ther text field has mask like #### open message error

### Expected Behavior

works like Test Mode

### Steps to Reproduce

1. creat text field
2. choose a Mask default or custom
3. set custom mask like ####

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz8rlx412oeZE0LX+bvowgWUwGUAaU40V0t1ETRQbCIj4B7QlPszRYRZtOOKzaH1mBFSjpHo07s7nht+SGvEqGxWtQL5nypByUxPPbFq6V4SzPs6SYkZCDcVbIHXD4aSvhSJ4VeNuLnAD3E66e/Oscz6Cf9qOYwx5e6fDbOY=

### Context

cant hot reload

### Visual documentation

![Captura de Tela 2024-04-20 às 17 24 51](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/38640d36-225a-4b7a-b531-b4b739dfb5ff/f1917c4a-54e9-4caf-9375-9950cdb57f85?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zODY0MGQzNi0yMjVhLTRiN2EtYjUzMS1iNGI3MzlkZmI1ZmYvZjE5MTdjNGEtNTRlOS00Y2FmLTkzNzUtOTk1MGNkYjU3Zjg1IiwiaWF0IjoxNzEzNjQ3NTk5LCJleHAiOjMzMjg0MjA3NTk5fQ.ImmhnKeg2CqxueBybFzTWZE_QTsmOtmvOd1uB1YPhVw "=1710x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.40
- Platform:Desktop macos
- Browser name and version:none
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by rzambroni** [comment]
Hey @rcunhadf, i was not able to replicate the issue on my end. Are you still experiencing it? If so, could you provide a blank project example were this issue can be observed? That would help us isolate any possible project-specific problem.

**Comment by rcunhadf** [comment]
Ok! I’ll try and and report.

Rodolpho Cunha
+55 61 99686-6333


Em sáb., 20 de abr. de 2024 às 22:25, rzambroni ***@***.***>
escreveu:

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, thanks!
