### ISSUE TITLE
No infinite scroll at the page level?

### ISSUE THREAD

**Issue by dmk23** [FlutterFlow/flutterflow-issues#278]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

API Backend Query at the page level should be able to paginate/ infinite scroll, just like a query attached to a ListView

## Current behavior (required)

Right now pagination/ infinite scroll option/parameters are only available when the query is attached to a ListView, but not the top-level page. This is a problem for a number of reasons:

1) Only the queries at the top-level (page) get reloaded on page navigation (e.g. with back button)
2) I want to have one data query at the top level to feed multiple components over the page, not just one ListView (e.g. a separate component that will display stats/ counts, etc)
3) While page itself may not have the pagination stats/controls, it should be able to get them from a chosen sub-component (e.g. ListView or whatever else), which it cannot do right now

## To Reproduce (required)

Try to create an API Backend Query for any page. You'll see no infinite scroll/ pull to refresh options

## Context (required)

I want one master query at the page level that would feed multiple components of the page and make the page automatically reload on navigation as necessary. Pagination/ scroll params could be tied to a chosen component within the page

## Screenshots / recordings

Creating page-level backend query, seeing no scroll/refresh controls
![image](https://user-images.githubusercontent.com/1828444/209484780-c2d1b33e-414b-4160-89ae-83f97a7533ac.png)

## Your environment

* Version of FlutterFlow used: Latest
* Platform (e.g. Web, MacOS Desktop): N/A
* Browser name and version: N/A
* Operating system and version (desktop or mobile): N/A

**Comment by wenkaifan0720** [comment]
Hi @dmk23. This is more of a feature request instead of a bug report, so I will close it for now. 

I think currently pagination only works with the `PagedListView` widget. Your use case might require some workaround. I'll raise this feature request to our team. Thank you.

**Comment by dmk23** [comment]
> Hi @dmk23. This is more of a feature request instead of a bug report, so I will close it for now.
> 
> I think currently pagination only works with the `PagedListView` widget. Your use case might require some workaround. I'll raise this feature request to our team. Thank you.

Do you have any suggestions for a "workaround"? This is obviously a critical missing functionality

Paginated list views are useless if cannot be tied to page navigation. It looks like at the page level I cannot access the list view widget state, and from the list view widget I cannot create any actions on pagination either

Need an actual solution here
