### ISSUE TITLE
Test on Device: hot reload on iPhone issue

### ISSUE THREAD

**Issue by vidy01** [FlutterFlow/flutterflow-issues#2781]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you try to hot reload, i keep getting a notification on xCode " use version on disk" vs "use xcode version" when i select "use version on disk" it closed xcode and disconnect my session and kills the app on the phone

### Expected Behavior

hot reload should just work

### Steps to Reproduce

1. run the app on local decide from the flutter flow desktop app.
2. make changes and hot reload to an iphone
3. when xcode prompts to "use version on xcode" vs "use version on disk" select use version on disk.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkPLqy4hJpbxb7aXUY+9aliM6JmIia700sNtuTQIdCYDuBIYiaffSVxduOfW7dAk+KEWGgmYFwc3Ik+LiV/Q4BzSVfNk71aVybw3dXmC/aovRPqqROXMmBeBUG2aO0MPY3REkIuluc0IX22a6GuuXUjPDJKX7Zwh9f6PHaOI=

### Context

I cannot test on device. Even the hotreload on the web is very buggy and laggy this morning. "hot reload" on the web wont respond. I have to keep refreshing the page.

### Visual documentation

![Screenshot 2024-04-21 at 8 58 17 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/aefb8f4c-9a4b-46f8-8074-389b51fd2466/9afd1f64-1763-4170-b55a-0107ef72d4a5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZWZiOGY0Yy05YTRiLTQ2ZjgtODA3NC0zODliNTFmZDI0NjYvOWFmZDFmNjQtMTc2My00MTcwLWI1NWEtMDEwN2VmNzJkNGE1IiwiaWF0IjoxNzEzNzI0ODYwLCJleHAiOjMzMjg0Mjg0ODYwfQ.f0uNZzjWKqFxSqLcq7_FGx7qV3TDxNkzzqQBQxXA7Wc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.40
- Platform: MacOS
- Browser name and version: Desktop
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hey @vidy01, I was not able to replicate this issue on my end. Seems to be working as expected. Are you still experiencing it? If so, I would recommend reaching out to our support team, not sure if you could have any configuration that could be causing this.
