### ISSUE TITLE
Suspect "go_router upgrade" has broken deep/ dynamic links

### ISSUE THREAD

**Issue by jarjarbinx919** [FlutterFlow/flutterflow-issues#2783]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On testflight builds from 14/04/24, the dynamic links send the user to the specific event page as expected, however, I did not modify anything that should impact this on the new build and instead the dynamic link is just opening the app to the page that it was currently on (yes I have tried exiting out of the app). I reverted back to the old build that was working, and redeployed it again, and it did not work and just took the user to their current page instead of the specific event page that it was supposed to. The exact same build that works on the previous flutterflow version, no longer works, leading me to believe it is an issue with the recent update. Specifically the go_router.

### Expected Behavior

Deep links taking the user to the appropriate page.

### Steps to Reproduce

On an ios app, create a dynamic link to a page, and open the link, and observe not being taken to the appropriate page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giufqyItIsdtK0L6IYe9WliARQ1g6Roc0sd4bGA0dCJzuPLMQdvWkdlNtZ7CkS1ZHPkSmmlM0+dblkYX9MfkqZAStQap4+c5IZzzKZDm7QZOBEc+OYEd8HcFjf1fC0J+7kR0kPrJ1cXtnw1+uIu+tYHXdH7LjImdISq/LZO4=

### Context

I cannot release a new update until this is fixed as it is an important component of my app that has stopped working randomly after the last flutterflow update.

### Visual documentation

None required.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.34+
- Platform: Windows for development, IOS for testing
- Browser name and version: Chrome
- Operating system and version affected: IOS
```

**Comment by paulperez-dev** [comment]
Hi @jarjarbinx919, Thanks for submitting the issue. By 'redeployed' do you mean you build again with an old code version? Or that you reinstalled an old build?

I've also looked at your project, but a lot is going on. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Can you please provide this information?

**Comment by smn-snkl** [comment]
I can confirm the same things. Here's the line of code that broke dynamic links in `firebase_dynamic_links.dart`
```
/// Extracts the path from the dynamic link, and routes to it.
  void _handleDynamicLink(PendingDynamicLinkData linkData) {
    final link = linkData.link.toString();
    final host = linkData.link.host;
    final location = link.split(host).last;
    if (GoRouterState.of(context).uri.toString() != location) { // ERROR: GoError: There is no modal route above the current context
      widget.router.push(location);
    }
  }
```

Hence, all dynamic links just open the app at the moment but don't navigate anywhere

**Comment by smn-snkl** [comment]
Found a workaround @paulperez-dev. Not sure if it's the ideal solution, but I was able to do the following:
```
if (widget.router.routeInformationProvider.value.uri.toString() != location) { ... }
```
as the router is passed to the DynamicLinksHandler widget already anyways.

**Comment by vardarsezgin** [comment]
Same here, dynamic link redirects to the initial page.

**Comment by vgensw** [comment]
I am having the same issue. Interestingly, on Android it works but on iOS it always redirects the user simply to the home page.

**Comment by vinayakagw** [comment]
Definitely an issue with GoRouter. I was migrating from Firebase dynamic links to a branch for deep linking and for in-app routing. I tried to use GoRouter similar to its use with Firebase dynamic links and got the same error.

**Comment by isegal** [comment]
Having the same issue - regular URL (non dynamic) links on web app do not work. The app always goes to home screen and ignores anything past the # hash symbol.

**Comment by paulperez-dev** [comment]
Hi! The team is investigating this issue. We will keep you posted here. Thanks for the feedback!

**Comment by carsonzylicz** [comment]
Heres the solution:  

`'$_kDynamicLinksUrl${GoRouterState.of(context).uri.toString()}'`
change to 
`'${_kDynamicLinksUrl}${GoRouterState.of(context).uri.toString()}'`

**Comment by rzambroni** [comment]
Hi everyone! there is a fix in place for this issue. It should be available on next week's release. Thanks.
