### ISSUE TITLE
Web projects have a versioning pinning on some libraries and can't local run

### ISSUE THREAD

**Issue by Nic61** [FlutterFlow/flutterflow-issues#2785]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Pushing the project on github and then doing a local run (flutter run from terminal) results in a versioning failing because some libraries are pinned.

### Expected Behavior

Push the project to Github and be able to local run it as per FF tutorials on youtube

### Steps to Reproduce

1. Create a project
2. Push to Github
3. Local run on Mac on an Iphone emulator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

I'm trying to local run a project from a github repo. This is because I can't do it from the FF mac app anymore as its completely broken due to it having a different flutter version than the web one and, thus, is full of bugs.

### Visual documentation

![Screenshot 2024-04-22 at 12 47 50](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/033ef854-fa75-42b7-88b2-2c75d0007721/a3f23d22-d55b-4896-82cb-be04a985ec7b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMzNlZjg1NC1mYTc1LTQyYjctODhiMi0yYzc1ZDAwMDc3MjEvYTNmMjNkMjItZDU1Yi00ODk2LTgyY2ItYmUwNGE5ODVlYzdiIiwiaWF0IjoxNzEzNzk2MTk2LCJleHAiOjMzMjg0MzU2MTk2fQ.nr6hJZd6StCagjxeO7935jTxSl2r8KdXDRJbc-3sSlQ "=560x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hey @Nic61, could you share that tutorial you are talking about? so I have a bit more context of the procedure you are following?

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
