### ISSUE TITLE
Data type parameters are not working

### ISSUE THREAD

**Issue by szymonpodwyszynski** [FlutterFlow/flutterflow-issues#2790]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After i create parameter on my page with the type "Data type" and choose some data type, everytime i try to reload a session or start a new one, error will be shown on the screen. The parameter doesnt even have to be filled out on navigation action, it just has to be created. The FF editor wont show any error, but the test session will.

### Expected Behavior

After i create my parameter with the type "data type" it should work correctly, without showing errors. If thats a correct behavior, then data type should not even be an option to choose from.

### Steps to Reproduce

1. Create a new page
2. Create data type
3. Create parameter with the type "Datatype"
4. Try to open a test session

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wj+flvYtOmMNY1rruY+9VoCURNlw2a7g7kcN+GE4cF4ioE7YPXfikSEpWZ9+kTHxcL02Jgjge0+DWhc7AA+UqZCeBfJRx+ZZMUQ7KZGWgV8SYDLuwYWtQDcRJJVPC0MKzhBQlFM9ZLnA721+mAOe/dHHbHpy0O1Q/P/+iVYHIs1GqQ0SLb3kNh1JWeC/v

### Context

It forced me to use some other way than it should. It just doesn't work correctly.

### Visual documentation

<img width="537" alt="Screenshot 2024-04-23 at 14 48 59" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/0188ee58-025c-4a38-95e0-fbecaa97fdb6">
<img width="296" alt="Screenshot 2024-04-23 at 14 49 11" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/fc05e5b9-1d6b-4b71-8872-ee0eb7fd7920">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.40 released April 23, 2024
- Platform: MacOS and web
- Browser name and version: Version 124.0.6367.60 (Official Build) (arm64)
- Operating system and version affected: Version 14.4.1 (23E224)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @[szymonpodwyszynski](https://github.com/szymonpodwyszynski), i was trying to replicate this issue but unfortunately, I couldn't. Can you replicate this on a blank project? if so, please share the bug-report-code of that project. <br>

**Comment by fiveminutejob** [comment]
I've resolved this by checking that the data types are set up correctly. Looks something is set up as a list or not set up as a list or just as list of strings when it should goto another data type. If you've used the json to data type importer, just double check the arrays.

**Comment by fiveminutejob** [comment]
this was advise for op! apologies for the confusion

**Comment by szymonpodwyszynski** [comment]
Yes, it seems something was wrong with the configuration of my project and it was displaying errors when i tried to load a test session. Issue is fixed.
