### ISSUE TITLE
Trailing backslash on "API base URL" breaks retrievals with a 404 error in console -- but only once deployed as a Private API

### ISSUE THREAD

**Issue by mode80** [FlutterFlow/flutterflow-issues#2791]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'd pasted "https://www.googleapis.com/books/v1/" into the API Base URL field and that was working fine while developing my app in debug mode. Upon deploying to Web for the first time, CORS issues broke everything and I learned that I must now make my API "private". Upon doing this, the CORS errors disappeared but still the spice doth not flow. A new 404 error was appearing in the browser console. I hunted down the code for the cloud function on Firebase and found that the string getting appended to the Base URL already had a leading backslash. Removing the trailing backslash from my API Base URL fixed the problem. 

### Expected Behavior

Working app with "public API" was expected to continue working after deploying "private API". 

### Steps to Reproduce

see above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

404ErrorInConsole

### Context

This almost made be abandon FlutterFlow. It's an easy fix but a nasty bug. Everything works for me now, but I'm submitting this for the benefit of humanity. 

### Visual documentation

trust me brah

### Environment

```markdown
recent usual stuff
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @mode80 thanks for your report. Exactly as you mention, the URLs are expected to end with a character, not with a backslash, so when you append a subpath to it you do it like "/subpath". Also, if you want to add queryParameters, you just append "?queryParameter=value". <br>Thank you very much for creating this issue to help other users that fall onto the same problem. It can take a while to figure out something like this.<br>Have a great day!
