### ISSUE TITLE
Several crashes due to this bug

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2792]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FirebaseCrashlytics.recordFlutterFatalError
io.flutter.plugins.firebase.crashlytics.FlutterError - A RenderFlex overflowed by 6.0 pixels on the right.. Error thrown during layout.

### Expected Behavior

App would not crash this often

### Steps to Reproduce

1. Add app in test flight (can add an email)
2. Try using the app and going between applications within the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCsofePrOpkAf8/7UFtUONTgS1Y/JVqWkXEX/MmNjoSWG/Y7PTuAbYRmyqpQEwnKZDmmaLGaEa63b0ZPGZ5NGECby7ejuR1TOsBhdCEF1E6MPOvJYBDcQ6ayDEg/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Difficult to use the app / hurts user experience

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/2ecb9166-eba3-465c-bfb7-caf0ff279f76

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @lovestar18 thanks for your report. When you say crash, what are you referring to? The error that you are sharing here is an overflow in the UI, this will not crash your app. The worst that could happen is that you see some widgets one on top of the other, because it overflowed its available space. <br>If your app is closing or freezing, it's not because of that message. <br>If you need any help, please feel free to contact our customer support team, they will help you with your project. <br>Have a great day!

**Comment by lovestar18** [comment]
Thank you @ignalauret ! Would it be possible to please provide a little more detail into what an 'overflow of the UI' means and how to fix it?

Thank you!
