### ISSUE TITLE
Flutterflow Builder Issues

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#2798]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't build an app properly.
The builder is not registering shortcuts like hold shift to drop widget, duplicating components adds a container. 
Layout crashes when I'm respecting alignment rules. Also there is syncing issues with desktop apps which resulted in dataloss.

### Expected Behavior

.

### Steps to Reproduce

.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elMrqw5N1xd9G15PTbcFFoCoRNmY6U6xMiuxhYAw3IqLrPYoQYej+QHZVOMO/dFY3OlmI8HI1w6HOhvzLGvkXPiirfLZ8+qtIcwvgXmKibK6nPbisR0dAGfNUN0OHzbSzqyMnWfNsWHgS62GIG9yicB3UGY/7NjI/Hf2XNZD5nl6JLTLOXn0Jg1ZSfCvr

### Context

.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/35dda457-898d-45e0-a127-22592fbad40c

### Additional Info

Tested on Web only as Mac Desktop get's syncing issues resulting in data loss.

### Environment

```markdown
- FlutterFlow version: 4.1.34
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Web
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by leighajarett** [comment]
Hi there! Thanks for filing this issue. Unfortunately, it's very hard for us to figure out what's going on without more detail. <br><br>Please create one issue for each bug that you run into with bug report code + steps to reproduce the issue from a blank project. We cannot triage bugs without this information as we aren't able to reproduce the issue and figure out what is causing it. <br><br>Sorry, I know it can be a lot of work. Asking for this information upfront saves us all time with going back and forth - I hope you can understand. Thank you!
