### ISSUE TITLE
Can't download source code!

### ISSUE THREAD

**Issue by Charley-YH-Wu** [FlutterFlow/flutterflow-issues#28]
## Expected behavior (required)
Downloading the source code of the entire project. 

## Current behavior (required)
Our application has no bugs, but when we try to download the code, firebase config errors showed up (only shows when we try to download the code), and even after we reconfigured the files, it threw another error of package name miss match, and then it says fail to build and fail to download. We tried it several times and it was the same problem.
I know our application is 100% bug free, but whether there is error or not, we want to download the code immediately.

## To Reproduce (required)
1. Download source code, application has no errors 
2. Firebase config errors showed up
3. Reconfigure the files
4. Firebase config errors disappear
5. Package name mismatch showed up 
6. Reconfigure the files
7. Package name mismatch disppear
8. Build failed (download failed)

## Context (required)
We need the source code to test and deploy the app locally and on actual devices. 

## Your environment
* Version of FlutterFlow used: V3.0
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome 
* Operating system and version (desktop or mobile):Desktop

**Comment by bulgariamitko** [comment]
Do you have any custom code? Even if you don't have any errors sometimes when you have a custom code with errors inside you still will not be able to download the code.

**Comment by Charley-YH-Wu** [comment]
No, we have custom code, but i checked and there are no errors.



*Charley Wu*University of Southern California
B.S. Business Administration, 2022 | USC Marshall School of Business
***@***.*** | 647-970-6239

**Comment by Pepino-GR** [comment]
Do you use different machines or different browsers (or browser and Mac app)to work with the with the project?

**Comment by Charley-YH-Wu** [comment]
We use chrome (Mac and Windows) and only use the web version of
Flutterflow. We were able to download the code weeks ago, but not when we
tried today. This is urgent and we need it immediately!

Please let us know how to proceed

Thanks



*Charley Wu*University of Southern California
B.S. Business Administration, 2022 | USC Marshall School of Business
***@***.*** | 647-970-6239

**Comment by Charley-YH-Wu** [comment]
![IMG_9163](https://user-images.githubusercontent.com/105037202/19465069
![IMG_9161](https://user-images.githubusercontent.com/105037202/194650702-0be87c8c-c050-412e-a84a-ab95c756b964.jpg)
3-ff31ecb3-52c4-4e05-b47d-142821461560.jpg)

**Comment by Charley-YH-Wu** [comment]
Please call 650-835-3525 ASAP. We need the code today! Thank you

**Comment by bulgariamitko** [comment]
Duplicate the project and delete all custom code, disconnect FB and try to download the project and see if that works.

**Comment by Pepino-GR** [comment]
Can you please generate a Bug Report Code which you can get by right clicking any widget from the widget tree

**Comment by LeeSingChanYau** [comment]
Hello, me and my team still have this problem. We really need to get access to the code. I understand that its hard to reproduce the problem, but can you gives us a solution to download the code? Perhaps download it from another platform?

**Comment by Pepino-GR** [comment]
As we asked for three days ago, we need the Bug Report Code, not a new issue

**Comment by katherineqian** [comment]
Hi @Charley-YH-Wu and @LeeSingChanYau, 

This issue tracker is intended for general bugs that are applicable to all users. Because this bug appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance. 

If you do find a specific reason for the issues you are encountering in your project, please don't hesitate to open a new bug report with steps to reproduce.

Thank you!
