### ISSUE TITLE
Select SQLite database in FlutterFlow Desktop Version not possible.

### ISSUE THREAD

**Issue by ClausFalkenstein** [FlutterFlow/flutterflow-issues#2802]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Apparently you can't select a SQLite file in the FlutterFlow desktop version, the progress indicator is always spinning!
The problem persists even if the Flutterflow desktop version is started as administrator.

In the web version this is possible without any problems.

I have helped myself by selecting the DB in the web version,
later I can select the database from the assets in the desktop version.

### Expected Behavior

It is expected that it will also be possible to select an SQLite database in the desktop version of FlutterFlow.

### Steps to Reproduce

1. Open FlutterFlow Desktop
2. Try to select a SQLite database from your file system
3. You can now enjoy a spinning wheel for hours on end!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not available in this case

### Context

I have helped myself by selecting the DB in the web version,
later I can select the database from the assets in the desktop version.

### Visual documentation

-

### Additional Info

-

### Environment

```markdown
- FlutterFlow version: v4.1.41+
- Platform: Desktop Local Run / Android
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windwos 10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @ClausFalkenstein, I was able to replicate the issue you are mentioning. It is related to a few others where assets can't be uploaded to FF from the Windows Desktop app. Custom Fonts, Icons and Media are also affected.

I'll pass this to the team so they can take a look. <br>Thanks for the report!

**Comment by aemelyanovff** [comment]
Apologies for the late response. It was fixed a while ago.
