### ISSUE TITLE
Media assets

### ISSUE THREAD

**Issue by KelvemC** [FlutterFlow/flutterflow-issues#2803]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm having problems with media assets in the desktop version of Flutterflow, even though I add images, they are never added and only the loading icon appears. 

### Expected Behavior

The default behavior was whenever I added an image, it would load and I could use it at any time.

### Steps to Reproduce

First, I started a web project on flutterflow, giving the name and making the firebase settings. Then I went to the assets image tab to add local images to the app, when you click on upload the windows will open the file manager and you will have to select which image you want to add, when you select and click on upload, it just keeps loading.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48jMrlwItIm+FJ0LXuccFB/WMvJkM7R5EzisBtd0w8J5zKB+wAYvf7P1FWTLy4YEFUe2aWgmIf1vfqiOOWEccpNUyVQKVxwaVQYBbhRn6iMbqWEbW/fW1SMJlWIUCx18OviCJQItJeSloG1Du6C9myQj/YNYf4IWs/AM6lJdeK2SrDX1iXc2URm05KZDPz

### Context

It affected in a way that I can only get images from the web.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/84690441/8e2b436f-e702-412d-9459-0521c06130e6

### Environment

```markdown
- FlutterFlow version: v4.1.41+ Flutter 3.19.1
- Platform: systems operational windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [X] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @kelvemC, there is currently a known issue in windows and was previously reported ([https://github.com/FlutterFlow/flutterflow-issues/issues/2628](https://github.com/FlutterFlow/flutterflow-issues/issues/2628))

Is already on the backlog for the team to fix. Closing this as duplicate. Please refer to above ticket for updates.

Thanks!
