### ISSUE TITLE
API Call Post JSON App State issue

### ISSUE THREAD

**Issue by CClark1720** [FlutterFlow/flutterflow-issues#2806]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've noticed that, when I have a JSON app state variable and when I call that app state variable in my post API call from the app in test mode, it puts double quotes around all of the objects. Here is a glimpse of what my database looks like when I make the API call from flutterflow.  I should be able to take the JSON above as an app state variable and call it in the API without it putting double quotes around all objects. 

![Screenshot 2024-04-25 011033](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/3044cc39-21e3-406c-a95f-84b46d7d2b72)

After i execute the api call in TEST mode, this is how it looks. it executed but it put double quotes around my objects where they are not needed. 
![Screenshot 2024-04-25 010725](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/0c8cadf6-ac84-4418-a64b-3b7c590edf1c)

But when i execute from the Response & Test, it works perfectly!
![Screenshot 2024-04-25 010940](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/9efc3214-53cc-45db-ae84-6e12c0fad7a6)

### Expected Behavior

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/e550f7e5-6252-480c-a50a-73fd12da8108)

### Steps to Reproduce

1. take a json and successfully execute it from Response & Test
2. call an action to execute the api call with a json app state variable. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ysnLuIt1ocNJ1s71bflvoGA5JkR+bedElcFRaCgofePtOol3evXsYlpoXeLhYGxIO0Smml4fzNrRiIaXGMIpBz6CQL06yJBUZjvKRnK6UZOBDbuSRHR5O/1TfH6k36SskAhNHPZZV1Fh7zqEOu68TjbtHbrAIndISq/LZO4=

### Context

I want to be able to take a json app variable and pass it in a API call without having double quotes being added. 

### Visual documentation

![Screenshot 2024-04-25 011033](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/5a977f92-6dba-4f57-ac40-268a55186e0b)
![Screenshot 2024-04-25 013724](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/7d8111ca-99de-479a-a1d4-4b351f4920a4)

### Additional Info

i understand im using MongoDB as my database but however. it works perfectly when i execute the json from flutterflow Response and Test. It doesn't work when correctly when I execute from the app/test mode. 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.34+ released April 16, 2024
Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by CClark1720** [comment]
[TEST JSON.txt](https://github.com/FlutterFlow/flutterflow-issues/files/15123473/TEST.JSON.txt)

attached is a JSON file that you can use to try it out.

**Comment by ignalauret** [comment]
Hey @CCLark1720 thanks for your report. I understand the issue that you are having, but I think there is no bug on the Api call section, but a misconfiguration at the moment you are setting the JSON App State variable value. <br>Could you please provide me the steps to reproduce this from a Blank Project? Maybe using the DummyJson Api.<br>Sadly I can't decide if there is a bug or not if I'm not able to reproduce your issue. Thanks, have a great day!

**Comment by ignalauret** [comment]
It would be really helpful if you were able to replicate the issue from a blank project, using a public API (like [https://dummyjson.com/](https://dummyjson.com/)). Thanks!

**Comment by CClark1720** [comment]
I'd tried so many things and im still getting the same outcome. 
When my custom function produces a json value. I set that value to an app state as json. When i view the app state, its json valid. 

When i call the api to use the json app state variable, it doesnt work. i keep getting "Failed to insert documents: 'documents' field must be an array", but it is an array because i am able to copy and past the same json in the Response & Test and it works perfectly. 


 Here is a screenshot of the api call payload.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/f015d180-92f4-4496-bad6-7aea28e639c0)

**Comment by CClark1720** [comment]
What is the proper way of having a custom function that returns a json type and using the function to set  a json app variable and calling that app variable in a api call?

**Comment by CClark1720** [comment]
my custom function produces this, which is JSON app state variable. 

[{"date":"2024-05-01","calories":3172,"mealType":[[{"food":"TILAPIA FILLETS","grams":390,"calories":312,"protein":66,"carb":0,"fat":5},{"food":"SPINACH","grams":275,"calories":66,"protein":6,"carb":10,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":185,"calories":636,"protein":23,"carb":12,"fat":52},{"totalP":95,"totalC":22,"totalF":57,"TotalCalories":1014,"MealCalorieTarget":1057,"TotalScore":49,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":36,"CarbsRatio":25,"FatRatio":38}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"JASMINE RICE, JASMINE","grams":90,"calories":340,"protein":6,"carb":74,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":80,"totalF":51,"TotalCalories":1029,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"POTATOES","grams":90,"calories":321,"protein":6,"carb":71,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":77,"totalF":51,"TotalCalories":1010,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42,"DailyProteinTotal":205,"DailyCarbsTotal":179,"DailyFatTotal":159,"DailyCaloriesTotal":3053}]]},{"date":"2024-05-02","calories":3172,"mealType":[[{"food":"TILAPIA FILLETS","grams":390,"calories":312,"protein":66,"carb":0,"fat":5},{"food":"SPINACH","grams":275,"calories":66,"protein":6,"carb":10,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":185,"calories":636,"protein":23,"carb":12,"fat":52},{"totalP":95,"totalC":22,"totalF":57,"TotalCalories":1014,"MealCalorieTarget":1057,"TotalScore":49,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":36,"CarbsRatio":25,"FatRatio":38}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"JASMINE RICE, JASMINE","grams":90,"calories":340,"protein":6,"carb":74,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":80,"totalF":51,"TotalCalories":1029,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42}],[{"food":"CHICKEN BREAST","grams":185,"calories":265,"protein":26,"carb":7,"fat":17},{"food":"CREAM OF WHEAT, INSTANT HOT CEREAL, ORIGINAL","grams":185,"calories":660,"protein":20,"carb":132,"fat":0},{"food":"Ribeye Steak","grams":90,"calories":113,"protein":27,"carb":0,"fat":20},{"totalP":73,"totalC":139,"totalF":37,"TotalCalories":1037,"MealCalorieTarget":1057,"TotalScore":60,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":32,"CarbsRatio":32,"FatRatio":35,"DailyProteinTotal":223,"DailyCarbsTotal":241,"DailyFatTotal":145,"DailyCaloriesTotal":3080}]]},{"date":"2024-05-03","calories":3172,"mealType":[[{"food":"TILAPIA FILLETS","grams":390,"calories":312,"protein":66,"carb":0,"fat":5},{"food":"SPINACH","grams":275,"calories":66,"protein":6,"carb":10,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":185,"calories":636,"protein":23,"carb":12,"fat":52},{"totalP":95,"totalC":22,"totalF":57,"TotalCalories":1014,"MealCalorieTarget":1057,"TotalScore":49,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":36,"CarbsRatio":25,"FatRatio":38}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"JASMINE RICE, JASMINE","grams":90,"calories":340,"protein":6,"carb":74,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":80,"totalF":51,"TotalCalories":1029,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42}],[{"food":"CHICKEN BREAST","grams":185,"calories":265,"protein":26,"carb":7,"fat":17},{"food":"POTATOES","grams":185,"calories":660,"protein":13,"carb":145,"fat":0},{"food":"Ribeye Steak","grams":90,"calories":113,"protein":27,"carb":0,"fat":20},{"totalP":66,"totalC":152,"totalF":37,"TotalCalories":1037,"MealCalorieTarget":1057,"TotalScore":60,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":32,"CarbsRatio":32,"FatRatio":35,"DailyProteinTotal":216,"DailyCarbsTotal":254,"DailyFatTotal":145,"DailyCaloriesTotal":3080}]]},{"date":"2024-05-04","calories":2538,"mealType":[[{"food":"TILAPIA FILLETS","grams":390,"calories":312,"protein":66,"carb":0,"fat":5},{"food":"SPINACH","grams":275,"calories":66,"protein":6,"carb":10,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":185,"calories":636,"protein":23,"carb":12,"fat":52},{"totalP":95,"totalC":22,"totalF":57,"TotalCalories":1014,"MealCalorieTarget":1057,"TotalScore":49,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":36,"CarbsRatio":25,"FatRatio":38}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"JASMINE RICE, JASMINE","grams":90,"calories":340,"protein":6,"carb":74,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":80,"totalF":51,"TotalCalories":1029,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"SHRIMP POPPERS, SHRIMP","grams":185,"calories":529,"protein":18,"carb":53,"fat":29},{"food":"Ribeye Steak","grams":90,"calories":113,"protein":27,"carb":0,"fat":20},{"totalP":83,"totalC":53,"totalF":75,"TotalCalories":1020,"MealCalorieTarget":1057,"TotalScore":60,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":32,"CarbsRatio":32,"FatRatio":35,"DailyProteinTotal":233,"DailyCarbsTotal":155,"DailyFatTotal":183,"DailyCaloriesTotal":3063}]]},{"date":"2024-05-05","calories":2538,"mealType":[[{"food":"TILAPIA FILLETS","grams":390,"calories":312,"protein":66,"carb":0,"fat":5},{"food":"SPINACH","grams":275,"calories":66,"protein":6,"carb":10,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":185,"calories":636,"protein":23,"carb":12,"fat":52},{"totalP":95,"totalC":22,"totalF":57,"TotalCalories":1014,"MealCalorieTarget":1057,"TotalScore":49,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":36,"CarbsRatio":25,"FatRatio":38}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"JASMINE RICE, JASMINE","grams":90,"calories":340,"protein":6,"carb":74,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":80,"totalF":51,"TotalCalories":1029,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42}],[{"food":"TILAPIA FILLETS","grams":185,"calories":148,"protein":31,"carb":0,"fat":2},{"food":"CREAM OF WHEAT, INSTANT HOT CEREAL, ORIGINAL","grams":185,"calories":660,"protein":20,"carb":132,"fat":0},{"food":"WAGYU BEEF PATTIES, WAGYU BEEF","grams":90,"calories":203,"protein":14,"carb":0,"fat":16},{"totalP":65,"totalC":132,"totalF":18,"TotalCalories":1010,"MealCalorieTarget":1057,"TotalScore":60,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":32,"CarbsRatio":32,"FatRatio":35,"DailyProteinTotal":215,"DailyCarbsTotal":234,"DailyFatTotal":126,"DailyCaloriesTotal":3053}]]},{"date":"2024-05-06","calories":2538,"mealType":[[{"food":"TILAPIA FILLETS","grams":390,"calories":312,"protein":66,"carb":0,"fat":5},{"food":"SPINACH","grams":275,"calories":66,"protein":6,"carb":10,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":185,"calories":636,"protein":23,"carb":12,"fat":52},{"totalP":95,"totalC":22,"totalF":57,"TotalCalories":1014,"MealCalorieTarget":1057,"TotalScore":49,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":36,"CarbsRatio":25,"FatRatio":38}],[{"food":"RIBEYE STEAK","grams":185,"calories":379,"protein":38,"carb":0,"fat":26},{"food":"JASMINE RICE, JASMINE","grams":90,"calories":340,"protein":6,"carb":74,"fat":0},{"food":"BEEF BOLOGNA, BEEF","grams":90,"calories":310,"protein":11,"carb":6,"fat":25},{"totalP":55,"totalC":80,"totalF":51,"TotalCalories":1029,"MealCalorieTarget":1057,"TotalScore":62,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":39,"CarbsRatio":19,"FatRatio":42}],[{"food":"TILAPIA FILLETS","grams":185,"calories":148,"protein":31,"carb":0,"fat":2},{"food":"JASMINE RICE, JASMINE","grams":185,"calories":699,"protein":12,"carb":152,"fat":0},{"food":"WAGYU BEEF PATTIES, WAGYU BEEF","grams":90,"calories":203,"protein":14,"carb":0,"fat":16},{"totalP":57,"totalC":152,"totalF":18,"TotalCalories":1049,"MealCalorieTarget":1057,"TotalScore":60,"DailyCalorieTarget":3172,"ListIndex":3,"ProteinRatio":32,"CarbsRatio":32,"FatRatio":35,"DailyProteinTotal":207,"DailyCarbsTotal":254,"DailyFatTotal":126,"DailyCaloriesTotal":3092}]]}]

below is my api call.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/b595bef1-92c6-4709-81bd-6099572c52d0)

**Comment by CClark1720** [comment]
here is a screenshot of my custom function
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/166693885/360bf8d3-ddc1-4aad-ad20-83d2241592b9)

**Comment by CClark1720** [comment]
It seems to only work when i take the json and make it a default value in the app state variable and then call the api using the app state. 

when the custom function creates the json value, and i set that value to app state and call the api, it doesnt work. Am i missing something?

**Comment by CClark1720** [comment]
I was able to fix this. We can can close this out!
