### ISSUE TITLE
Kids app using ADMOB - Google replies app is not compliant with Google Play Policies 

### ISSUE THREAD

**Issue by RohitKanade** [FlutterFlow/flutterflow-issues#2807]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

KIDi: Moral Story Every Night

Its implemented as suggested in FF docs with Admob
But Google reply with following email: 
![Screenshot 2024-04-25 at 12 16 37 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/04d8b3b4-fd7e-4296-be4e-0b6ab2d082fb)
![Screenshot 2024-04-25 at 12 16 50 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/e5a85fcb-747d-4bd5-82ff-9142551e4729)
![Screenshot 2024-04-25 at 12 17 02 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/2c596c06-9f54-47ee-8fe0-eaad4e436b81)

Issue found: Families Data Practices

We’ve identified that your app or an SDK in your app transmits device identifier(s) from children or users of unknown age that do not comply with our [Families Policy](https://notifications.google.com/g/p/ANiao5pKjhlAu3Hzb8-1E-aeZ98cGrV4Qi2bJYPqx2BvqBqlrQk6NZVhUUBHpWk5q48MGFgfTyGAHMbs3NTo5v9ykbuW6AuRu5hJJ-eYOCWVP5WPzcFFfMEOTRGKcoJnNFv0FLLmxAjbpFMn_Cb7ElhqZOtkb4fqrETsrPcC-AFsnA8bCQ5lobngpRDjCEXMzFqTPovsTd_Ex75mitwJN1nB79TRdeJBziPxEiE0TA-Ua0JMeKB4C6rhc1uQ1w4hRI2Uxv4tp4g6UQemYCu0cxeXieXA).

These identifiers may include but are not limited to Advertising ID.
Your app may face additional enforcement actions, if you do not resolve this issue by May 06, 2024.
Issue details

We found an issue in the following area(s):

Code Analysis
About the Families Policy Requirements

Apps that solely target children should not transmit the following:

Android Advertising ID (AAID)
SIM Serial
Build Serial
BSSID
MAC
SSID
IMEI and/or IMSI
Apps that target both children and older audiences must not transmit the listed identifiers from children or users of unknown age.

### Expected Behavior

Admob implementation should be in line with Google Policies 

### Steps to Reproduce

Project Name: Kidi

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

added custom permission of android.permission.AD_ID

### Visual documentation

![Screenshot 2024-04-25 at 12 16 37 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/f0f16d91-24f7-445c-bde6-f2503d1317a4)
![Screenshot 2024-04-25 at 12 16 50 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/e0452dbb-3d41-4b04-a8ca-bfc04d16968a)
![Screenshot 2024-04-25 at 12 17 02 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/8c0a6e2d-a9c8-4506-885b-4cc4af842cab)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @RohitKanade, so sorry you are having this problem. 

The problem is that you should need to indicate to the ad request that you are targeting children as an audience, that way it doesn't transmit those parameters, and although the SDK that FlutterFlow uses should support this, there is not currently a way to do that from within FlutterFlow.

I will submit a feature request for this to be added to the configuration of the ads in the project.

In the meanwhile perhaps you could explore doing that on your own from the generated code. See: [https://developers.google.com/admob/flutter/targeting](https://developers.google.com/admob/flutter/targeting)

Will ask internally to see if we can provide more advise.

Thanks for the report!

**Comment by RohitKanade** [comment]
@rzambroni  is there any simple way to do it without taking project outside flutterflow?

**Comment by rzambroni** [comment]
I don't think there is, that's why i created a feature request for this to be added as a customization of the admob implementation.
