### ISSUE TITLE
Stripe Payment for Indian Merchant needs to pass Address (not covered in FF stripe)

### ISSUE THREAD

**Issue by RohitKanade** [FlutterFlow/flutterflow-issues#2808]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently for stripe payment we can not pass billing address which are compulsory for Indian Stripe Account Holder to accept international payments

https://docs.stripe.com/india-accept-international-payments

### Expected Behavior

Stripe FF should have one more field to accept address from user and pass to Stripe Action. 

### Steps to Reproduce

normal FF stripe 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

https://docs.stripe.com/india-accept-international-payments

### Visual documentation

![Screenshot 2024-04-25 at 12 36 16 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/2747fc2b-02f1-41e8-91c5-52013d6db4ca)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @RohitKanade, You're correct. I created a feature request for this.<br>I am closing this issue. As it will be tracked in our internal backlog and we will get to it as soon as possible. 

Thanks for flagging this!
