### ISSUE TITLE
Custom action boilerplate generate its code incorrectly.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#281]
## Expected behavior (required)

* The Boilerplate button in Custom action editor should generate proper codes based on the definitions.

## Current behavior (required)

* It generates broken codes like below. (Please, see the video below.)
![custom-action](https://user-images.githubusercontent.com/5080329/209555449-f7226f45-6c8d-4dd8-824b-78516f2fce4c.gif)

## To Reproduce (required)

1. Press the button of `+ Create new Action`
2. Define an action
3. Press `View Boilerplate Code`

### Bug Report Code

N/A

## Your environment
* Version of FlutterFlow used: Flutterflow v3.0 released December 24, 2022 Flutter version 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome - Version 108.0.5359.124 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): iMac, macOS Ventura 13.1

**Comment by agreaves** [comment]
Thanks for the bug report! This will be fixed upon our next deploy 🙂
