### ISSUE TITLE
Action deselects on any change

### ISSUE THREAD

**Issue by Sidies** [FlutterFlow/flutterflow-issues#2811]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the latest flutterflow update that happend today whenever I want to make changes to the bottomsheet the action deselects which basically makes me unable to use things like the color picker. I am using the Windows Desktop version of FlutterFlow.

### Expected Behavior

The action stays selected when making changes to its settings

### Steps to Reproduce

https://github.com/FlutterFlow/flutterflow-issues/assets/13236803/81bb587e-66cf-4dad-802e-6b302afb786b

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9VpD8QOUwlRoc0st5Hd0gdCOPrBqQIZPelRE5CZ7C9aVNcBWCGpD0x7tbFuNjPEu03NRyCRrZC1odbFgvke2iuVrquCKueWkF6DZhUGmq95raKkBQlJrJhLk4h3FOQO+uXUjLDIuu/Zwh9f6PHaOI=

### Context

The behavior is not intended and hinders the experience with the product.

### Visual documentation

Video is already attached above

### Environment

```markdown
- FlutterFlow version: 4.1.45
- Platform: Windows
- Browser name and version: /
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @Sidies, i was able to replicate the problem you are describing and wiill send it to the team so they can take a look. <br><br>As a small workaround it seems like you can still work normally when editing the bottomsheet from the sidebar instead of inside the action flow editor. hope it helps a bit.<br><br>This bug is also replicable on IOS Desktop and the Web app. 

Thanks for the report!

**Comment by takashiff** [comment]
Hi @Sidies, thanks for the bug report! We've put in a fix for this recently and it should be out by the next release. Thanks so much for your patience!
