### ISSUE TITLE
Error running flutter pub get

### ISSUE THREAD

**Issue by maverickLDR** [FlutterFlow/flutterflow-issues#2814]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I create a new project with next to nothing in it.  I create a simple custom action with next to nothing in it.
Then I just added "internet_connection_checker_plus: ^2.3.0" as dependency.
Then the custom action refuse to compile.

### Expected Behavior

It should compile. I have next to nothing in the project.

### Steps to Reproduce

1. create a custom action
2. add "internet_connection_checker_plus: ^2.3.0" as dependency
3. click refresh code editor with pubspec dependencies
4. click on the check/compile code on the upper right

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMrlvJFgrt9c187pbcZoqCIvJWZ7TL07ttYbZxUjIuPtBJh+O8mlbVhVXc++T3lhHFKWgXwB/+DvjdrtN/cEaUirbog7z5NIbRXwIHq8Ra6XPqueYEF7I/5RCXKkyKujrhVQVettS1Yc3Dmbfem9bArdCZ+/Zwh9f6PHaOI=

### Context

I cannot do a single thing now - I mean I have barely started writing any code!

### Visual documentation

<img width="383" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/109785618/496a55de-b140-4e1c-bfcc-2563ce892b99">
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/109785618/6aada04b-1676-4a0e-8baf-73e5fc3422bc)

### Additional Info

This is the code for the custom action:
```
// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

Future initPingTest(BuildContext context) async {
  // Add your function code here!
}
```

### Environment

```markdown
- FlutterFlow version: v4.1.45+
- Platform: Web
- Browser name and version: Chrome 124.0.6367.61 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @maverickLDR, 

This is actually the full error you are getting, is a bit hidden in the scroll:

```console
Error: Failed running flutter pub get...
The current Dart SDK version is 3.3.0.

Because custom_widget depends on internet_connection_checker_plus >=2.3.0 which requires SDK version >=3.3.1 <4.0.0, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Try using the Flutter SDK version: 3.19.6. 
* Consider downgrading your constraint on internet_connection_checker_plus: flutter pub add internet_connection_checker_plus:^1.0.1
```

As you can see, the specific version of that package you are trying to add a dependency for requires a higher version of Dart. You should be able to add a previous version of the package and have that issue resolved (e.g: `internet_connection_checker_plus:^1.0.1`)
