### ISSUE TITLE
Action as parameter with a custom datatype fails to compile project

### ISSUE THREAD

**Issue by Sidies** [FlutterFlow/flutterflow-issues#2815]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to pass an action which has a custom datatype as parameter the project is no longer able to compile.

### Expected Behavior

The project compiles and the custom datatype is passed to the action

### Steps to Reproduce

1. Create a new custom datatype
2. Create a component that accepts a action with this very custom datatype 
3. create a button that opens a dialog/bottomsheet with this component
4. Try to compile and test the project
5. It fails to compile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9VpD8QOUwlRoc0sd4bGA0dCJzuPLMQdvWkckpCOeHgTFY7MESmmmMyp8rQhuH+V/ICHxSbbIh41ZZ+ZAqWUkSXQZOBBameQHJBM/1mIFzF06SvoiRQB/toL15k1DqYOu+idDPYHqL3IlFISq/LZO4=

### Context

Unable to pass custom datatypes in actions.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/13236803/cd3b3995-8aa3-4c50-bf23-a47dc8f22325

### Environment

```markdown
- FlutterFlow version: 4.1.45
- Platform: Windows
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Sidies** [comment]
For anyone facing this issue, there is a workaround for this. 
Just add a parameter of the type of the custom datatype to the component. You don't have to use this parameter but if its there it seems FlutterFlow at least sets the imports right and the component now "knows" about the custom datatype.

So this leads me to believe that for action parameters the imports are not setup correctly for custom datatypes.

**Comment by rzambroni** [comment]
Hi @Sidies, This issue is replicable on our end and it was sent to the team so they can take a look.

Thanks for the report!

**Comment by MartinLockheart** [comment]
Any update on this? I'm running into this issue as well.
