### ISSUE TITLE
Flutterflow Supabase Table Dataloss

### ISSUE THREAD

**Issue by ruveydasevinc** [FlutterFlow/flutterflow-issues#2816]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot get updated tables in Supabase. I can see half of the tables in flutterflow, but I can't see half of them.When I do get schema, the tables are not updated and the incoming tables do not have any connections according to their creation time. I started experiencing this problem after enabling the auth feature with Google and Apple.

### Expected Behavior

I want it checked.

### Steps to Reproduce

I am having trouble viewing all tables in Supabase and keeping them up to date. For example, the last table I added does not appear in Flutterflow and I am having trouble viewing all tables.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

The project is completely inoperable because there is no database

### Visual documentation

<img width="319" alt="Ekran Resmi 2024-04-26 13 22 54" src="https://github.com/FlutterFlow/flutterflow-issues/assets/154506108/1b395272-880d-43b7-ba3c-9bfe76aecc7d">

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web / Local
- Browser name and version: Chrome / Safari
- Operating system and version affected:  macOS Sonoma
```

### General

- [X] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [X] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [X] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hi @ruveydasevinc, I am so sorry you are experiencing that issue. I tried to replicate this on a blank project but seems to be working as expected. Not much else we can do on our end to help without more context and information.

<br>Would you mind provide a bug-report-code and replicable steps?

If you need help checking what might be happening with your individual project configuration and given the nature of the issue i would recommend following up with our support team instead. You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by ruveydasevinc** [comment]
<img width="277" alt="Ekran Resmi 2024-04-27 19 20 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/154506108/b6f66e8d-ddf2-49d9-8de8-0182a2e7477d">
<img width="277" alt="Ekran Resmi 2024-04-27 19 20 53" src="https://github.com/FlutterFlow/flutterflow-issues/assets/154506108/0df93e8d-f02d-4b15-85b6-378e4dfd4cfd">
The current versions of the tables in Supabase are not available. For example, I deleted the table named ai_question, but it still appears in Flutterflow. Likewise, I added a new table named trialSupa, but it does not appear. Sometimes no painting arrives, sometimes half of it arrives. When I do get schema it sometimes appears completely empty. Or its outdated version.

**Comment by rzambroni** [comment]
Hey @ruveydesevinc, We understand the issue, but we don't really have a way to help you from here. Would you mind following up with our support team? Given the issue, they are our best chance to help you since it seems project-specific.<br><br>Sorry that you are dealing with that.
