### ISSUE TITLE
Error in test mode "Type "double" is not a subtype of type "int"

### ISSUE THREAD

**Issue by rmiagn** [FlutterFlow/flutterflow-issues#2817]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I receive two 'double' data points from an API representing a latitude and a longitude, and I want to convert them into a 'LatLng' data type in order to display them as a Google Maps map.

### Expected Behavior

Let the 'LatLng' data display my position on the map

### Steps to Reproduce

1. The data comes from the 'LongitudeLatitude' API. 
2. It is then transformed from 'double' to 'LatLng' by the custom function 'latLngbis'. 
3. The resulting data is displayed on the Google Maps map on the 'tracking' page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfHlx85Pm9hE18/ubMJV9Sk5JUQ1R4IRmtZRaCsrfePoBOw+Y/nBQFVUcMekYWNMMVqjknoX/MqLhuzxU/A3B02qRapcyKVcSQ3dRkeiVIzTPoS3b3xBL+JgGW7F0KSvryNCKsd2SHxiw1ylNtnJcHLUQpzBDEcFQ+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I want to display data that comes in the 'double' format from an API, and I want to display it in the 'LatLng' format on a Google Maps map.

### Visual documentation

<img width="857" alt="Capture d’écran 2024-04-26 à 14 42 51" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168136826/c60d0950-735c-44a9-ace9-004131d07c5a">

<img width="1420" alt="Capture d’écran 2024-04-26 à 14 43 27" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168136826/221829a0-7206-4b12-98eb-160c040d7af4">

<img width="350" alt="Capture d’écran 2024-04-26 à 14 43 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168136826/5952b417-b4c7-4fbc-bef5-38607ae5b569">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @rmiagn, i was trying to replicate this on a blank project, but it seems to be working fine on my end. I took a quick look at your project at and i would recommend using the action flow "on page load" to make the API Call -> Update a Page State Variable with the result of calling the custom function you made and then Updating the map center. You could associate the page the page state variable to the maps widget "marker location" property.

<br>Something like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/62b9839c-21f1-4805-b1bc-785d12954889/36250846-40ed-493d-b713-b478537a3f37?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MmI5ODM5Yy0yMWYxLTQ4MDUtYjFiYy03ODVkMTI5NTQ4ODkvMzYyNTA4NDYtNDBlZC00OTNkLWI3MTMtYjQ3ODUzN2EzZjM3IiwiaWF0IjoxNzE0MTQ1OTIyLCJleHAiOjMzMjg0NzA1OTIyfQ.AgScaBaINbHPgGt6yVbBm_XAKeS1FZzZewRKBrYPZTE " alt="image.png" width="487" height="690" />

This is for sure not an issue in FF but an issue on the logic for the feature you're trying to create. 

Hope it helps!

**Comment by rmiagn** [comment]
Hello rzambroni,

Thank you for your response.

I try to test several times but I have an error (in attachment).

Could you show me the detail of your backend call and App state ?

<img width="340" alt="Capture d’écran 2024-04-27 à 10 59 15" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168136826/25305555-32b9-4e87-a1d3-31747df804d1">

**Comment by rzambroni** [comment]
backend call is just a standard call to the same API you are usign:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c97c8ea6-fd80-4f44-89a8-72dd50eb150d/df06746f-6182-43cc-88d5-c2523ee8be81?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jOTdjOGVhNi1mZDgwLTRmNDQtODlhOC03MmRkNTBlYjE1MGQvZGYwNjc0NmYtNjE4Mi00M2NjLTg4ZDUtYzI1MjNlZThiZTgxIiwiaWF0IjoxNzE0MzQzMjQyLCJleHAiOjMzMjg0OTAzMjQyfQ.WvuoW9GoxxZdRspKoRflsC67z-khXb-ctXzVYrJLcpg " alt="image.png" width="353" height="513" />

the update state is basically updating the state variable by calling the custom function and passing as parameters the lat and long obtainer from the predefined json path

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2831debd-953d-49c2-a442-66005b620bff/c1c88224-8b14-4d40-9e97-d2eec42e4adc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yODMxZGViZC05NTNkLTQ5YzItYTQ0Mi02NjAwNWI2MjBiZmYvYzFjODgyMjQtOGIxNC00ZDQwLTllOTctZDJlZWM0MmU0YWRjIiwiaWF0IjoxNzE0MzQzMjQyLCJleHAiOjMzMjg0OTAzMjQyfQ.Fe9AVcjxWuioRyo5Nq3UXPe7nsx1SN9sWHsOEieHoK0 " alt="image.png" width="993" height="942" />

The map, of course is reading the marker location from that state variable.

Hope that helps.

**Comment by rzambroni** [comment]
Although I would love to help you further, I'm going to close this ticket, as this list is meant to house bugs of the platform and not project-specific issues. If you continue to need help, I would recommend asking on the[ community page](https://community.flutterflow.io/) or perhaps reaching out to support. <br><br>Thanks for understanding.
