### ISSUE TITLE
The Form widget fails validation of allowable emails that begin with capital letters

### ISSUE THREAD

**Issue by wolfhoundgelert** [FlutterFlow/flutterflow-issues#2818]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Form widget fails validation of allowable emails that begin with capital letters

### Expected Behavior

The Form widget doesn't fail validation of allowable emails that begin with capital letters

### Steps to Reproduce

1. Create a new proj
2. Add InputField
3. Wrap it in the Form widget
4. Turn on Automatically Validate switcher
5. Choose Text Validator -> Email
6. Run the Test mode
7. Input "a@gmail.com" - works good
8. Input "A@gmail.com" - warning about "Has to be a valid email address".

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk8nlz49OtbxZ+KXtbfl7/GQsJjJ+apI4sct8ew4aIuv4ELQcPuDSQFVWUsSzaHNMJWaGqzs0w+Dpv/HpG+1cGzOWfrZH1pFydBPPYzmlWqqvPaWaW0RQBeZWfHGP5LSVgBV/ObBZc0Uj33GIDfCicz+Cf9qOYwx5e6fDbOY=

### Context

New users with allowable emails like Joe.Biden@gmail.com or Donald.Trump@gmail.com can't pass a registration process.

### Visual documentation

![emailbug](https://github.com/FlutterFlow/flutterflow-issues/assets/17844779/05095610-5f2b-4900-b443-a511e1e49f80)

![emailbug2](https://github.com/FlutterFlow/flutterflow-issues/assets/17844779/fc5ab668-1304-4914-a39c-0fbf3ecdfeb6)

![emailbug3](https://github.com/FlutterFlow/flutterflow-issues/assets/17844779/28aeb5b9-8979-4b8b-9374-a4645d84ff3e)

### Additional Info

FF minimal project: email-b-u-g-8ao5pa

### Environment

```markdown
- FlutterFlow version: 4.1.45+
- Platform: WEB
- Browser name and version: Google Chrome 124.0.6367.92 (Official Build) (64-bit)
- Operating system and version affected: Win10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @wolfhoundgelert, i was able to replicate the issue you are mentioning and also noticed a few other patterns not working as expected.

Will send this to the team so they can take a look. 

Thanks for the report!
