### ISSUE TITLE
If you 'wrap widget' on an AppBar Title, it disappears and can't be restored without Undo

### ISSUE THREAD

**Issue by crioux** [FlutterFlow/flutterflow-issues#282]
## Expected behavior (required)
Either 'Wrap Widget' on the AppBar child (Title) should not be possible, or it should allow arbirary child trees in the appbar child, and work

## Current behavior (required)
Doing 'wrap widget' on an AppBar title causes it to disappear and can't be fixed without undo

## To Reproduce (required)
1. Create new page with an app bar
2. right click on title text widget
3. wrap widget with row
4. see it disappear, have to ctrl-z for undo

### Bug Report Code (required)
IT4szfHl5YxNodxE7c/QccdB/ScXHDsgU5I0sct/cxQcB4j4O4YcffSkbRJvXtCzaHxACk2ghj8d+fT8huLLFME6JSqeQLpD1qVqc1yjEA8=

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/819652/209588759-e6340426-4d0a-4cc3-9691-be154d09e95a.png)
![image](https://user-images.githubusercontent.com/819652/209588770-7bc8d43f-dbb1-456c-8e37-6cd0831bf32a.png)

## Your environment
* Version of FlutterFlow used: 3.0 12/26/22
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: Chrome latest
* Operating system and version (desktop or mobile): MacOS Monterey

**Comment by agreaves** [comment]
Thanks @crioux! This will also be fixed upon our next release! 🙂

**Comment by AlexFox63** [comment]
> Thanks @crioux! This will also be fixed upon our next release! 🙂

Looks like appbar doesn't work properly again. You can't add any of widgets to the appbar (only by using UI builder) if you remove the default text widget from it. And also I think you have problems with wrapping through the whole FlutterFlow. I'm talking about wrapping widgets into column or stack (maybe some more widgets)

Also I think it's important to have the ability to customise appbar buttons (leading and actions)
