### ISSUE TITLE
Youtube Video

### ISSUE THREAD

**Issue by Somimpkno** [FlutterFlow/flutterflow-issues#2822]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"I'll tell you that strange behavior is exhibited in every condition:

1. If multiple YouTube videos are added to any blank page in a list/column, the first index video loads while the rest do not initially. Usually, another index's video loads after some time but not the first.

2. If multiple YouTube videos are added to any blank page in a list/column, the first index video behaves correctly in full screen, but this doesn't work in other indexes. In other conditions, like wrapping the YouTube video list in a conditional builder, the full screen doesn't work on the first index.

3. Updating the YouTube video URL at runtime does not change it. (A person asked about this problem in the FlutterFlow community eight months ago, but no answer was given.)"

### Expected Behavior

We need normal behavior in YouTube videos, but we're encountering strange behavior here .

### Steps to Reproduce

1. Create new page

2. Add listview

3. Add youtubeplayer minimum 3

4. Run

5. Check all above behaviour one by one

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4szsj125dIsdtI0KruYMZR/TgRC1giROYsscp/bxIgGIDzPOw+ZPXsRFBoUs+/S2NLeUSmmmEDw/PGiOL1VPpdNRWdc6p41ahcZT3LVnKnUZOBCJCROHx8AcBUIXKu0p+JrApSKtpiLmQC2F+HfNi/dCvcHYDGImdISq/LZO4=

### Context

"The bug seems to be occurring at the first stage of the YouTube player, so there isn't an option to try anything. 
1. However, it has been observed that at least one video from the YouTube videos present in the listview loads correctly.
2. If there are many widgets in the listview and only one YouTube video, it loads at any index."

### Visual documentation

![IMG_20240427_195938](https://github.com/FlutterFlow/flutterflow-issues/assets/128114034/6ebf913c-6647-459c-b07f-63bbcc94c96c)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.45+ released April 26, 2024
Flutter version is 3.19.1
- Platform:all ( web ,ios .. ) 
- Browser name and version:chrome 124.0.6367.63 
- Operating system and version affected: windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @somipkno,

The problems you are mentioning are known issues of the [package ](https://github.com/sarbagyastha/youtube_player_flutter/issues/904)FlutterFlow uses under the hood.

There is already a request to revamp, but it is not an easy fix. I'm going to close this ticket as it is a known issue and being tracked internally. 

Thanks for the report.
