### ISSUE TITLE
Rightclick Menu goes offscreen

### ISSUE THREAD

**Issue by unibum** [FlutterFlow/flutterflow-issues#2825]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, right clicking so I can duplicate, the menu goes offscreen on laptop

### Expected Behavior

Can see entire menu (incl top part which I cannot on my 17inch laptop)

### Steps to Reproduce

right click a container for example

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

Cannot select the top menu options like back and forth, duplicate etc..

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8017480/f0c23a36-f246-4d34-af3f-cc597ba77558)

### Environment

```markdown
- FlutterFlow version: current
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: win 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @unibum! Thanks for reporting the issue. Can you please provide more information? 

\-Resolution of your device<br>-If the screen was resized or not <br>-Bug code from a blank project reproducing the issue

And any other information or extra context you want to share.

**Comment by unibum** [comment]
Hi Paul, appears it is due to default settings on screen resizing. at 100% it is not an issue.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8017480/778712e8-9c9a-4b34-a9e0-f80e9337c7a6)

**Comment by unibum** [comment]
Do you need any further information from me?

**Comment by paulperez-dev** [comment]
Hi @unibum! I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
