### ISSUE TITLE
Chat Message not sent if Send Icon is clicked, works if user hits Enter on keyboard

### ISSUE THREAD

**Issue by cadufreeela** [FlutterFlow/flutterflow-issues#2826]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On Chat flow, under chat_thread, when user writes a message and click on Send icon, the message appears, then dissappears and its not written in chat_messages in Firebase.

 If user writes a message and hits ENTER (keyboard when using FF emulator browser) or android Keyboard, the message is recorded in firebase and shown in the thread

**UPDATE**

I created a new copy of the icon button and copied the action chain into the new icon button and chat works now, and record is writting into the chat_messages collection in Firebase.

### Expected Behavior

On Chat flow, under chat_thread, when user writes a message and click on Send icon, the message appears, written in chat_messages in Firebase. (wheter the user click on Send Icon OR Enter on the keybaord)

### Steps to Reproduce

1. Import chat flow (basic - no bubbles)
2. Start a project
3. Go to chats
4. Invite an user to chat
5. Open chat thread
6. Write a message in textfield and click on Send Icon
7. Check message in thread and in firebase chat_messages

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksjf35N2ofVY+Krcc8ZsoCAXCUMbWoIzlO1Ca0kdB4joPLJ/evfsTFNtZ9fjS1NhHGeZ+UcF7trSiYSTGMJfZCeBbIhB1blUUALhf3q8RpSDEqrhYGpTL5hjfkyY5sKvnSJTPvptci1i2GCte+m+dA7cN5u/Zwh9f6PHaOI=

### Context

Trying to have a sucessfull chat flow working

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/163602905/a1cf3317-6e5b-4fcc-85a3-a14426b523a9

### Environment

```markdown
- FlutterFlow version: v4.1.45
- Platform: Web 
- Browser name and version: Version 124.0.6367.91 (Official Build) (64-bit)
- Operating system and version affected: Win11 and Android
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @cadufreeela thanks for your report. I just created a project with Chat Flow, and the Send button is working correctly. <br>Could you try replicating your issue from a blank project and tell me if your are getting the same behaviour? If you are able to, please send me the debug code for your blank project.

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
