### ISSUE TITLE
Action block always throws back if changing something in the callbacks

### ISSUE THREAD

**Issue by artemBobrov** [FlutterFlow/flutterflow-issues#2828]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If i have the callbacks in the action blocks and try to change any behavior inside the action block, i aq always thrown back to the initial parent action in the action flow editor.

### Expected Behavior

I should just be able to change the action without throwing back

### Steps to Reproduce

1. Create any component with some action with a component parametr
2. From any page call this component as a bottom sheet for example
3. Open action flow editor
4. Click the Set action for a callback action 
5. Try to do anything - like adding action inside the action flow editor
6. You would be thrown to the parent screen of the action flow editor immediately

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjPHlz5JPj7xY17X5bfpsvGI4JjJ8TLJMqNYbGA0hNZOvEIkUPcj4dhRLYte/YG1mGWaL+XE1w+D6ueDpKPkrBwWYfpQ7za5XQRWUTnynMJSIO86oSmpQJ95VGEePyMO3rCQnPsBfWXgTwUOUe/CdG3qCf9qOYwx5e6fDbOY=

### Context

I am trying to work with the callback actions.

### Visual documentation

Here is the video recorded
[https://share.vidyard.com/watch/9JbJiFicjF7oYkA851Lro3? ]

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: MacOS
- Browser name and version: Using Desktop App
- Operating system and version affected: MacOS Sonoma 14.4.1 (23E224)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Perlo34** [comment]
i confirm, using windows desktop app, every click i made on action pannel , like edit page state , click on a value , the action block was unselected

**Comment by cwangfr** [comment]
Same here, on Windows Desktop has problem, on the web is ok

**Comment by paulperez-dev** [comment]
Hi @artemBobrov, thanks for reporting the issue! We are keeping track of this issue on [https://github.com/FlutterFlow/flutterflow-issues/issues/2813](https://github.com/FlutterFlow/flutterflow-issues/issues/2813). 

I'm going to close this issue.
