### ISSUE TITLE
Search in API library acting wierd

### ISSUE THREAD

**Issue by leosteets** [FlutterFlow/flutterflow-issues#2829]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When searching for a api call the behavior don't make sense, with less character it doesn't find the api.

Evidence in the video below:
https://github.com/FlutterFlow/flutterflow-issues/assets/7843669/62b64930-2727-4e75-ad11-5a4c4150005e

### Expected Behavior

The search should match every substring with the same content.

### Steps to Reproduce

1. Upload a openAPI library 
2. search for a long API Call with the kebab-case

Example of openAPI library to upload
[openapi-asaas.json](https://github.com/FlutterFlow/flutterflow-issues/files/15143054/openapi-asaas.json)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Can't find fast the api's I need to change

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/7843669/cdff5724-109d-4047-a47d-75afedd8e831

### Environment

```markdown
- FlutterFlow version: 4.1.45+
- Platform: Win
- Browser name and version: Chrome 124
- Operating system and version affected: Win
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [X] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hi @leosteets, i was able to replicate the problem you are describing, will send this over to the team so they can take a look.

Thanks for the report!

**Comment by rzambroni** [comment]
Hey, @leosteets, I'm closing this ticket as it was added to our internal backlog as an enhancement request and we will be tracking it there. <br><br>Thanks!
