### ISSUE TITLE
Keyboard Hiding on Tap in Nested Bottom Sheets

### ISSUE THREAD

**Issue by rayan1005** [FlutterFlow/flutterflow-issues#2830]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the keyboard hides perfectly on tap when opening a bottom sheet directly, the same functionality does not seem to work as expected when opening a bottom sheet from within another bottom sheet.

### Expected Behavior

The keyboard should hide automatically when tapping outside any open bottom sheet, regardless of whether it is directly opened or opened from within another bottom sheet. This behavior ensures a consistent and intuitive user experience across the application.

### Steps to Reproduce

Create a FlutterFlow project with nested bottom sheets.
Ensure that the project includes functionality to open a bottom sheet from within another bottom sheet.
Open the first bottom sheet.
Within the first bottom sheet, trigger the opening of a second bottom sheet.
Observe the behavior of the keyboard when tapping outside the nested bottom sheets.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gostc+bn6LPlQhQMjNlx7bZAnktV+WRMhNZyrELMldsjBalhLYtTjelVHPlSJ/Xkdpq3SiIaTUuw6FASrbNlCzoRXQQ7LcEynVrnXCLioeHZRM+9hJ36s16bYnwlSBLJhS1oB60zzevCrG3qCf9qOYwx5e6fDbOY=

### Context

 impacted my development workflow and the overall user experience of the applications I am building.

### Visual documentation

aaaa

### Additional Info

aaaa

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): macOS Monterey 12.2.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [X] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @rayan1005 thanks for your report. I created a project with two bottomsheets with Text Fields inside. Bottom sheet1 can open bottom sheet 2 and I can see the keyboard behaving correctly in both of them. Could you please clarify:

* What is the behaviour your are expecting?
* What is the behaviour you are getting?

Also, if the setup I did is different, please send me the correct widgets that should go inside each bottom sheet so I can replicate your issue.

**Comment by rayan1005** [comment]
this image explained the issue 
![Group 2](https://github.com/FlutterFlow/flutterflow-issues/assets/19284896/77fee402-112c-485d-be3a-6774071d6e47)

**Comment by ignalauret** [comment]
Hey @rayan1005 thanks for the image. Could you just clarify where are you expecting to tap to close the keyboard on the second BottomSheet? Are you expecting the keyboard to hide but the BottomSheet to stay opened?

**Comment by rayan1005** [comment]
I'm attempting to simply tap on the screen to hide the keyboard, the bottomsheet stays open. Please watch the video where I had to open the drop-down menu to hide the keyboard."

https://github.com/FlutterFlow/flutterflow-issues/assets/19284896/24099670-2d73-4508-8fac-00643d44f865

**Comment by ignalauret** [comment]
Hey @rayan1005 I'm sorry for the late response. Where you able to achieve the behaviour you were expecting with the BottomSheet?
