### ISSUE TITLE
Action Panel is showcasing unexpected behaviour

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#2832]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to add actions on different action types, on Tap, PhoneShake, etc.
But the action panels behaviour is quite weird and doesn't register actions the way it should.

### Expected Behavior

.

### Steps to Reproduce

1. Simply open Action Block
2. Switch to Different Action Gesture
3. Add an Action
4. Switch Back to Another Action Gesture
5. Try Clicking on the Action Block
6. Weird Behaviour Continues On & Off

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEei/Hlz4xPj7xJ+qntKvowpwMxQUQ5a50rlu1FGQAdfIOvBKQqZ+PEaXdVcNOITXxHemaLnkEd7tGMk+zmU+0rBzirGqF607pqYDyVIXqjRZCkOpeSWERPI/FYJ32P3MGrgxFNOfhYSHAO7HGLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/e8bb35de-e9a7-4286-9974-826deeca0c2d

### Additional Info

.

### Environment

```markdown
- FlutterFlow version: 4.1.45+ (released April 26, 2024)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by victoriahuang1** [comment]
Hi @Dev-Muhammad-Junaid , thanks for the report. I have identified an issue on our end, which should be resolved once deployed.

**Comment by Dev-Muhammad-Junaid** [comment]
Thanks @victoriahuang1 for prompt response
