### ISSUE TITLE
Color changing when I publish website or view runmode in full screen

### ISSUE THREAD

**Issue by Nestifyapp** [FlutterFlow/flutterflow-issues#2834]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My project is changing colors when i publish to website or view run mode in full screen
![IMG-20240428-WA0007](https://github.com/FlutterFlow/flutterflow-issues/assets/134930709/904c3ebc-97fe-4e7c-8cd8-cbda04de29e9)
![IMG-20240428-WA0005](https://github.com/FlutterFlow/flutterflow-issues/assets/134930709/fe0636f1-9d01-4c53-befa-2e31d559e4be)
![IMG-20240428-WA0006](https://github.com/FlutterFlow/flutterflow-issues/assets/134930709/a93f01db-e26f-4e7b-81fc-c0a5b44f59ba)
![IMG-20240428-WA0004](https://github.com/FlutterFlow/flutterflow-issues/assets/134930709/3a004f13-8978-4d7c-b038-9e42de1e5c48)
![IMG-20240428-WA0002](https://github.com/FlutterFlow/flutterflow-issues/assets/134930709/7ce0caac-15ff-4483-917c-0bbd97dd51dd)
![IMG-20240428-WA0003](https://github.com/FlutterFlow/flutterflow-issues/assets/134930709/187a5de4-75cb-46d4-b23a-0a7aac71bfde)

### Expected Behavior

The colors are meant to remain the same 

### Steps to Reproduce

Colors change when I publish website or view runmode in full screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhsmAsJZOsdhE+bnQLPl4r2MwFnIca+YZhMBud00dJZD2P6QTbuvRYkhtYOngTUFLMWGYgXEFwfTHjdrqGMJcGzaEQ5RDyLpyTgyUcFGhVba6Bau8WGpAHtNUI3Ki57SNrBZANvtZWGMtig/GSw==

### Context

Not having the color i chose within the published website

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 4.1.45
- Platform:All
- Browser name and version: chrome, latest version
- Operating system and version affected: windows
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hi @Nestifyapp, so sorry your are dealing with that problem. I was able to replicate the problem you are describing only in your project, but I can't replicate this on a blank one. Can you try to do that? <br><br>This is very likely a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.<br><br>Thanks!

**Comment by Nestifyapp** [comment]
I have also realised that when I have an appstate then i log out without
clearing then I authenticate using a different user but using the same
device, the appstate is accessible in the user
Why is that?

**Comment by rzambroni** [comment]
Hey @Nestifyapp, if you are having an issue with the app state please file another issue with the specific steps to reproduce and the rest of required fields and we can follow up there, otherwise this thread will get messy and not helpful. 

Thanks for understanding.

**Comment by Nestifyapp** [comment]
Why is it closed and yet the color issue is not fixed yet?
