### ISSUE TITLE
Border width from variable dont work

### ISSUE THREAD

**Issue by Perlo34** [FlutterFlow/flutterflow-issues#2835]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I use a page state do define if the border width is equal to 1 or 3 but it always keep the default value i put (3)

### Expected Behavior

I want to change the border width conditionnal

### Steps to Reproduce

1. Create app or page state
2. Create Action to switch the value of page state
3. Create a container and set the value of border width from variable
4. Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhfKA4ot1mNhE7s/LYO5FliMwGUALa+dI0tZ+TQ0jF5D4P7Qid+DRbldCQsCzaHxpfFCihlEBpcrpidnLMe4EKROWfKY4zql2VRPPbHuWb8zRPbisWkEnEeVYC2KAy7WzmSJ/CNRsS11hw2eUHO6Xaz6Cf9qOYwx5e6fDbOY=

### Context

can't have the UI i want

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/f7c2907e-3ec5-4f67-9dff-b164af51c575](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/f7c2907e-3ec5-4f67-9dff-b164af51c575)

the color change but not border width

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3dc764ed-959b-46be-beea-b61362b52e12/2a869a66-afb5-4331-9236-37e95d1daf4b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zZGM3NjRlZC05NTliLTQ2YmUtYmVlYS1iNjEzNjJiNTJlMTIvMmE4NjlhNjYtYWZiNS00MzMxLTkyMzYtMzdlOTVkMWRhZjRiIiwiaWF0IjoxNzI4OTEyNDQwLCJleHAiOjMzMjk5NDcyNDQwfQ.5vIyeGh-v3G5IMGGYDWJ_PA-Yd8PgAtpcAw-W2ctas0)

I up the value to see clearly their are not difference

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f04e64fa-3a42-4343-9439-e5e69d237d76/7c8190f0-b49d-4067-a8a8-05d5f8eea382?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMDRlNjRmYS0zYTQyLTQzNDMtOTQzOS1lNWU2OWQyMzdkNzYvN2M4MTkwZjAtYjQ5ZC00MDY3LWE4YTgtMDVkNWY4ZWVhMzgyIiwiaWF0IjoxNzI4OTEyNDQwLCJleHAiOjMzMjk5NDcyNDQwfQ.4avPcXRIWpbdBSP9w3YM8DN2K4Ry6D2L4BSyMURAOIs)

the code generated

### Environment

```markdown
- FlutterFlow version: 4.1.45
- Platform: Windows
- Browser name and version:windows 11
- Operating system and version affected:
```

###

**Comment by paulperez-dev** [comment]
Hi @Perlo34, thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

**Comment by Perlo34** [comment]
This is the new Bug Code : IT4Kj8iBx852pbxZ1s7ycvlahSQRQ2YkbZIalut9SRUjG72tG7l/S8+kfhNuXbC0YWxUOlqj+XId3NHemvDAUPYoZE2sbNl6+pducg7LQmWgbpigC6uaXm5/DdtgIBTF57aVvyMlCMxhWVIiwE2QP9iQQhHZJ5+3ImwjJPiiLZOK2SrDX1iXc2URm05KZDPz

With a blank project

**Comment by paulperez-dev** [comment]
Hi @Perlo34, thanks for the code! I reported this issue to the internal team so they can take a look into this!

**Comment by ArachnaDigitalLtd** [comment]
Found this to be an issue today for me, any update on this @leighajarett ?

**Comment by TheSilverNimbus** [comment]
I seem to be having the same issue, @leighajarett, @paulperez-dev.

In my case, I have also tried directly putting an **IF** condition on the border width property directly. However, that doesn't change the border width either.

_(The details of the bug I'm experiencing---along with screenshots---can be in [this FlutterFlow Community post of mine](https://community.flutterflow.io/ask-the-community/post/how-can-i-update-the-textfield-border-width-on-focus-changed-oGCjsCn3cgUI8xn).)_

**Comment by paulperez-dev** [comment]
Hi @Perlo34,

This issue has been fixed in the latest build! Please verify on your end and let us know if you encounter any further issues. I’ll close this for now.

Thank you!
