### ISSUE TITLE
Crash: sign in with google during firebase setup

### ISSUE THREAD

**Issue by withinboredom** [FlutterFlow/flutterflow-issues#2839]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking "sign in with google" to create a firebase project and then the X causes a crash

### Expected Behavior

To not crash

### Steps to Reproduce

1. Create a new project
2. Create a new firebase project
3. Click sign in with google
4. Click the X
5. Crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40j8nf049Om+EA7q6JKcEwniY5JVA1aq8o0MJraCosfZT2BLMcec/RVERDTsfkS2xUMWCZu2oW0PTNheHDLPEVAAeaGd1nz6tyEBWWWn6mRpCsFJWgdXAkL+FXGm7FyMC3uhBdLvppciVn2GeHf/CRYA7ZNpj0IjISD6/LZO4=

### Context

Trying to create a new project...

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/1883296/0894e206-ceca-4f35-89ae-ec3ef04ce56e

### Environment

```markdown
- FlutterFlow version:  v4.1.45+ released April 29, 2024
- Platform: Windows
- Browser name and version: Native
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @withinboredom, i was able to replicate the issue and will send it to the team so they can take a look. <br><br>Looks like it is also failing on macOS but working fine on the web app. Please use that as a workaround for now.

<br>Thanks for the report!
