### ISSUE TITLE
ChipChoice displaying unwanted icon for selected chips

### ISSUE THREAD

**Issue by rocketlasagnabros** [FlutterFlow/flutterflow-issues#2841]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Apparently when using the ChoiceChips component, all selected chips have this check icon which it's impossible to remove and we have no control of which color to set (it seems it has it's own defaults for light/dark mode).
Other that the fact it's annoying not being able to remove it and no control over color, it's also overlapping existing selected icon in the case has been defined (see image) making the selected icon in the background and resulting in a very unpleasant mixup.

I think this might be related to the most recent Material 3 Theme, I think this wasn't happening before when using the Legacy M2.

![Screenshot 2024-04-30 142721](https://github.com/FlutterFlow/flutterflow-issues/assets/131388846/6e5b9135-30af-41fc-b496-c412f810603d)
![Screenshot 2024-04-30 142526](https://github.com/FlutterFlow/flutterflow-issues/assets/131388846/93a192f3-0fc1-4af1-a8de-2fc9b893076d)
![Screenshot 2024-04-30 142458](https://github.com/FlutterFlow/flutterflow-issues/assets/131388846/80e9fdce-8a4f-434a-8c3e-6a04db5b034f)

### Expected Behavior

This icon should NOT appear is the desired, if must appear then we should be able to decide if/how and all settings, and NOT overlap with existing icon.

### Steps to Reproduce

Just create a page with ChoiceChips component having the Material 3 them enabled.
You should be able to see this icon appearing once chip is selected, with/without the predefined option icon.
and verify that is not possible to control color of this, only light/dark mode has some influence.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olcr15YhgodsE7aqJbsFFmSQUHFgna4IK18pBczwYCOPuB+wQS8zRalVvO7zmTQk+eWGJpGMx1vfquODtEcEBMgSabIBh/rVqZA7zQlO6M5STC5bofW1SO9lRClCD1qS3uCUkJuhZdVYk3Wauf+ivaDPvHoTUO0QdGMqbKdeK2SrDX1iXc2URm05KZDPz

### Context

Just trying to display a nice and clean chip choice component and setup custom colors to be inline with my project

### Visual documentation

![Screenshot 2024-04-30 142721](https://github.com/FlutterFlow/flutterflow-issues/assets/131388846/d697d112-926d-41a5-9e1f-593749e155b3)
![Screenshot 2024-04-30 142526](https://github.com/FlutterFlow/flutterflow-issues/assets/131388846/dc38d2c5-ee71-4d85-82ef-169e25d94e91)
![Screenshot 2024-04-30 142458](https://github.com/FlutterFlow/flutterflow-issues/assets/131388846/708df1a6-7fd6-429d-a67c-d8e94f03fab6)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: any
- Browser name and version: any
- Operating system and version affected: any
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @rocketlasagnabros,

Thanks for the report, i was able to replicate the problem you are describing and will send it over to the team so they can take a look.

As you mentioned, this happen when you have Material Theme 3 enabled.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/47cbdb4c-53bc-481b-8f80-2f9e4ea8f814/fe3b8f4e-dc71-4f45-ba70-2edd12235a57?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80N2NiZGI0Yy01M2JjLTQ4MWItOGY4MC0yZjllNGVhOGY4MTQvZmUzYjhmNGUtZGM3MS00ZjQ1LWJhNzAtMmVkZDEyMjM1YTU3IiwiaWF0IjoxNzE0NDg3NTY3LCJleHAiOjMzMjg1MDQ3NTY3fQ.H_IlnPGd1GSCNkC_8JgBhz26GpA6tw6Iicm8XuFIFWE " alt="image.png" width="408" height="152" />

**Comment by rzambroni** [comment]
Actually, this bug was already identified and added to our internal backlog, I will close this as duplicated for now but we will add an update here once it is fixed.

Thanks!

**Comment by rocketlasagnabros** [comment]
When is this fix going to be released?

**Comment by sabatage3** [comment]
Are there any updates here? that check looks awful

**Comment by rocketlasagnabros** [comment]
I only found a manual workaround where I override the component and set the "showCheckmark" to false (seems not much effective) along with setting the "avatar" to NULL, which makes unable to use icons but at least I don't have glitches.
Also it requires me to do manual merge of downloaded code every time....

**Comment by dannymeese** [comment]
To fix the color issue, all the FF team would need to do is change _**purple**_ to the primaryColor from the theme (or uiColor, whatever they want to call this color in the FF theme), so that FF users can modify this UI color.
```
MaterialApp(
  title: appName,
  theme: ThemeData(
    // Define the default brightness and colors.
    colorScheme: ColorScheme.fromSeed(
      seedColor: Colors.**_purple_**,
      // ···
      brightness: Brightness.dark,
    ),
```

See flutter's own docs: https://docs.flutter.dev/cookbook/design/themes
