### ISSUE TITLE
not posting to wall

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2845]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when you try and write on someone's wall, the post should show up on that user's profile page

### Expected Behavior

post appears on wall when someone tries to write on that person's wall

### Steps to Reproduce

1. Go to test mode
2. Find a user and try to post on a user's wall

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCsofePrOpkAf8/7UFtUcOm4d0FieE6GmnwX/MrWvd71DscVOTOWRqFzz7tqEBX/fDqjbJihBpS3b0ZPGZ5NGECby7ejuR1TOsBhdCEF1E6MPOvJYBDcQ6ayDEg/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

can't push app live

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/1f84f575-2df2-453c-bfe3-ebb4683d1b6d

### Environment

```markdown
- FlutterFlow version: 4.1.45
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @lovestar18, it appears that the problem you are describing is an specific bug on your project/app, this tracker is meant for bugs replicable on a blank project and with clear steps to reprouduce. If you need help with your project i would advise reaching out to our support team: You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. 

I'm going to close this issue but if you think you found a bug in flutterflow that is replicable on a blank project please provide more context.

Thanks.
