### ISSUE TITLE
Admob Integration can not reverse/remove

### ISSUE THREAD

**Issue by RohitKanade** [FlutterFlow/flutterflow-issues#2846]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have added Admob in project KIDI, but as FF does not support child app admob, we decided to remove admob. but now FF gives error and force to add admob keys though we removed all reference/actions of admob

### Expected Behavior

need functionality to remove admob integration 

### Steps to Reproduce

1. add admob in project
2. use it in any actions 
3. then remove keys 
4. remove actions 
5. FF build fails. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

![Screenshot 2024-05-01 at 11 24 08 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/c28c5a3f-c580-40dd-9abb-0b00a9f07751)

### Visual documentation

![Screenshot 2024-05-01 at 11 24 08 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/8362944/655516a3-1ea1-42d0-a310-3eceb8ad896a)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
hey @RohitKanade, i was trying to replicate this issue on a blank project but it seems to be working fine on my end. I was able to make an app with AdMob integrated, show an add banner and an interstitial ad using an action and then i removed everything and the app is compiling.

You might be having a project specific issue, can you try replicating this problem on a blank project?

Thanks!

**Comment by RohitKanade** [comment]
@rzambroni Are you able to remove Admob Keys ?

**Comment by rzambroni** [comment]
Yes, as i mentioned on my previous comment i was able to add admob and rever the integration.
