### ISSUE TITLE
Page Upload is not loading all the functions, actions, etc.

### ISSUE THREAD

**Issue by Toninomex** [FlutterFlow/flutterflow-issues#2847]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I made a Two minutes loom video to show the problem... I believe its going to be easier and quicker.

https://www.loom.com/share/7c6311d6920c4f33996c48c0db84ae34?sid=e2554471-7647-4180-bfcb-e282af1e484d

The problem is that for the execution of some "things /functions /action" (random) I have to tap my screen once the page is loaded, when is supposed to load with those "things /functions /actions".

For example, it does work that the conditional visibility for the lower blocks is working when the page is loaded, which is linked to the boolean of the first block called "Does it happen", that is working!!!

But later when I enabled the rest of the blocks, as you can see, the two boxes below that are supposed to be shrunk only shrink when I tap any part of my screen.

This is not the first time I have faced this problem, in my algorithm page happens the same and I have to move custom functions to the button that allows me to navigate that page.

I think is an important problem because it is affecting the whole functionality of the page...

I do believe that the same happens when you try to tap on a current day of a calendar, you have to change the day to latter allowing you to tap the selected (focus) day.

Let me know when you fixed it or if I can fix it.

PD
I have made tests in Safari, Chrome, and Firefox and it does happen in all.

### Expected Behavior

When the page loads it recognize all the actions are supposed to be done.

### Steps to Reproduce

I made a two-minute video on Loom and left a description, it is going to be quicker that way. 

https://www.loom.com/share/7c6311d6920c4f33996c48c0db84ae34?sid=1d98ae62-1c96-4b30-a3ec-22960e3a6073two-minute

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/debug/ooqLBSWKoeA5f9N9as8w

### Context

I made a two-minute video on Loom and left a description, it is going to be quicker that way. 

https://www.loom.com/share/7c6311d6920c4f33996c48c0db84ae34?sid=1d98ae62-1c96-4b30-a3ec-22960e3a6073two-minute

### Visual documentation

I made a two-minute video on Loom and left a description, it is going to be quicker that way. 

https://www.loom.com/share/7c6311d6920c4f33996c48c0db84ae34?sid=1d98ae62-1c96-4b30-a3ec-22960e3a6073two-minute

### Additional Info

...

### Environment

```markdown
- FlutterFlow version: Last? where can I see that?
- Platform: Mac
- Browser name and version: Chrome, Safari, Firefox, the lastest of the three
- Operating system and version affected:all
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @Toninomex thanks for your report. I understand the unexpected behaviour that you are getting, but to check it out I need the Bug Report Code of your project so I can take a look into it. Please follow step 8 of this guide [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports) and share with me the code. <br>Have a great day!

**Comment by Toninomex** [comment]
Thank you Nacho

I believe this is the bug Report Code, let me know if you receive it.


ITESz8/624ZgobwE1pDicMdqhQIgQ0QnU7gnlO1ucx4cIuutE7AQZuCkU0NKQuGgT2x+IlWlgl8H+dLuvdjLL/ICCzGZUbpC0JVATjvxTjmhaYSkDKuaVnBQM8pnBW3H37uFphJACM9fSloA2kOpN63qNleeY8aSfxBlZ7vfcPo=

Antonio

**Comment by Toninomex** [comment]
https://www.loom.com/share/f0a12fa1ebf8439887c8eb84503048ca?sid=ef2d89f7-ff48-4b1f-b50a-56257e5ff7aa￼
Passing Parameters Dont Respect Boolean Status
loom.com

Nacho I recorder a Loom video to explain something it might be part of the same… In the video I said that I have this issue when passing parameters but after making testings is every time I try to navigate to the page (with the exception of navigation back). If I don’t pass parameters (even when the required check box is off) I get a null red code. How ever, it seems to be the same it seems to be a pre state behavior conflict vs the programmed behavior of a page when loading.

I hope this contributes

**Comment by ignalauret** [comment]
Hey @Toninomex I'm sorry for the late response. Where you able to figure out how to solve the delay on the loading? If not, please let me know so we can review it again.

**Comment by Toninomex** [comment]
Hola Nacho

I believe Is work fine, thank you.

Now I am having a biiiiiiiiiig trouble, con you help me:

Crazy Math started after tuesday June 25, incrementals and decremental erratic bejavior. #3266

I need to solve this quickly because I have to launch my app during the first week of July. I have spent 6 months building and this is the final stages where everything should be put together, all your assitance will be deeply appreciated.

**Comment by ignalauret** [comment]
Hey @toninomex that's great. Ok I will close this ticket then and follow up with you on the new one.
