### ISSUE TITLE
Image path by API call issue

### ISSUE THREAD

**Issue by rowFace** [FlutterFlow/flutterflow-issues#285]
If in API response SVG picture - image widget will fail to render image 'cause of `Image.network` instead of `SvgPicture.network`

1. Add an image widget
2. Set image source: Network
3. Set image Path from API call 
4. if in the response from the API call is the SvgImage link than:
Fail to render image 'cause of the wrong widget. Have to replace it from `Image.network` ===TO== >  `SvgPicture.network`

**Comment by agreaves** [comment]
Hi @rowFace, thank you for the feedback! At the moment, FlutterFlow does not explicitly support dynamically switching between `Image` and `SvgPicture` based on the input type, however this is a feature we may add in the near future.

In the meantime, if you expect the API call to consistently return an SVG, then one small workaround is to past in a `.svg` network path prior to setting it from a variable. FlutterFlow will interpret this as an SVG and use the `SvgPicture` widget to render it.

If, however, it truly is dynamic (sometimes requiring Image, sometimes SVG), then I'd recommend creating a custom widget that can toggle between the two based on the filepath.
