### ISSUE TITLE
Clicking "Assets" in desktop app crashes the app.

### ISSUE THREAD

**Issue by andrewdaniels** [FlutterFlow/flutterflow-issues#2850]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Click on the assets panel in the desktop app.

### Expected Behavior

You should be able to access the assets panel... the app crashes and closes out.

### Steps to Reproduce

1. Open project
2. Click on Assets in the left menu

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

4.1.45 released May 2, 2024 Flutter version is 3.19.1

### Context

This is the project it is happening in: https://app.flutterflow.io/project/a-r-q-backoffice-admin-o0g2zd?tab=widgetTree&component=modal_JewelryStyles

### Visual documentation

It isn't a huge bug and there for... not 

### Environment

```markdown
- FlutterFlow version: 4.1.45 released May 2, 2024 Flutter version is 3.19.1
- Platform: Desktop 
- Browser name and version:
- Operating system and version affected: Apple M1 iMac 2021
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [X] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [X] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @andrewdaniels, i'm trying to replicate this issue, but i'm unable to do so on a blank project or in any existing projects. Is this happening to you consistently? Can you replicate this in a blank project or is it only happening on that specific project?
