### ISSUE TITLE
whenever 'shimmer' animation is applied on page load, the container/item would not show up in test mode

### ISSUE THREAD

**Issue by cheungysophie** [FlutterFlow/flutterflow-issues#2857]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i have applied the shimmer animation effect for a container on page load. but when i run it in test mode, the entire container disappears and won't show up. 

### Expected Behavior

the shimmer animation to work on page load, and for the container to show up

### Steps to Reproduce

1. create a container
2. add the animation 'shimmer' on page load
3. run test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk/H134pgoctH176IKcIw+T06NVscTL4zlO1HcxAYGO/yPbJ/d+OkS1poOfXmY1NhHGC0hmYepPDKiuzpKfFfIgSdG5x8/5ZhVTzdWXq8R7rWPs6CX2t7HdFMGX6n06uzgRZBAPNpR0Y8w0ODe+Stfz/tJ5O/Zwh9f6PHaOI=

### Context

i am trying to make an interactive card game, and so would like the shimmer effect to work

### Visual documentation

wont show up in test mode:
<img width="383" alt="Screenshot 2024-05-04 at 2 05 19 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/80649756/32d5c779-f985-479e-a184-46b563836b86">
this is in preview mode: 
<img width="299" alt="Screenshot 2024-05-04 at 2 06 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/80649756/cf4f4f51-9335-4ce4-94ae-b7575f1048f3">

### Environment

```markdown
- FlutterFlow version: v4.1.47
- Platform: mac
- Browser name and version: brave
- Operating system and version affected: mac
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
hey @cheungysophie, i was trying to replicate the issue you are describing but I was unable to do so with the steps you provided. The shimmer effect seems to be working as expected on the container. Are you able to replicate this on a blank project and consistently?

Thank you!

**Comment by cheungysophie** [comment]
hi! 
my apologies, try this:
1. create a container
2. apply a fill color to it
3. apply 'shimmer' on page load
4. go to test mode -> it will not appear

ITESz/Hqx89gobRe+s/PbvpQhQMkQzM6bZI7ku1EdwEhfZesPYYDP8zBfldLYtSlTFVEHVaZ/WcH06mJj87DEMInEz+qQL5gyb5XQQn/fHmQbrXQCLWVPWt7N/1mCmK0yqSRryNSKfVYW3w81GGEN/CrG3qCf9qOYwx5e6fDbOY=

here's bug report code from a blank project

https://app.flutterflow.io/project/test-og7l0a

**Comment by rzambroni** [comment]
Hey @cheungysophie, In the test project you provided i can see the shimmer effect working as expected, the only thing that perhaps is confusing you is that it only appears once. If you want the shimmer effect to be continuous turn on the "Loop Animation" switch.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6fcc081e-e882-4a38-a75d-563459c066ad/f70aff82-27c7-4766-a12c-d7316bb4c0a3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZmNjMDgxZS1lODgyLTRhMzgtYTc1ZC01NjM0NTljMDY2YWQvZjcwYWZmODItMjdjNy00NzY2LWExMmMtZDczMTZiYjRjMGEzIiwiaWF0IjoxNzE1MTA2Nzg3LCJleHAiOjMzMjg1NjY2Nzg3fQ.PKQhZ2tNfWvjekHG4x9o_OW0iyqMr2oDYSVvJnNCa4I " alt="image.png" width="390" height="576" />

[Simulator Screen Recording - iPhone SE (3rd generation) - 2024-05-07 at 15.32.47.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7f3cb93e-4f7a-48d0-8ab1-a271b6e21caa/5661e789-b28e-4e48-8bb2-7c9484e43180?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZjNjYjkzZS00ZjdhLTQ4ZDAtOGFiMS1hMjcxYjZlMjFjYWEvNTY2MWU3ODktYjI4ZS00ZTQ4LThiYjItN2M5NDg0ZTQzMTgwIiwiaWF0IjoxNzE1MTA2Nzg3LCJleHAiOjMzMjg1NjY2Nzg3fQ.ebTVziFCRqCs801uNDfkAVMbRY6CbjIbY5Lb0P6Rayw)

**Comment by cheungysophie** [comment]
Hi, are you able to see my screenshots from the issues - that it doesn’t show up for me in Test Mode? On May 7, 2024, at 11:33 AM, rzambroni ***@***.***> wrote:﻿
Hey @cheungysophie, In the test project you provided i can see the shimmer effect working as expected, the only thing that perhaps is confusing you is that it only appears once. If you want the shimmer effect to be continuous turn on the "Loop Animation" switch.

Simulator Screen Recording - iPhone SE (3rd generation) - 2024-05-07 at 15.32.47.mp4

**Comment by cheungysophie** [comment]
> > Yes, i can see your screenshot, but i can't replicate on a blank project, we need to be able do that to confirm it and send it to the engineering team for a fix. Otherwise it might be a project specific issue.
> > Thanks.
> 
>  Screen.Recording.2024-05-09.at.10.12.55.AM-480p.mov 
> please see this video:
> 
> 1. i created a new project from scratch (this is the 3rd NEW project i've created that does not work - so i don’t believe it's a project issue)
> 2. added shimmer effect to a container
> 3. in test mode it is not displayed

https://app.flutterflow.io/project/shimmernotworking-s3sq8a here's the project link

**Comment by rzambroni** [comment]
@cheungysophie, yep i understand, i can see you can replicate on a blank project, i cloned your project and it doesn't replicate so i'm going to ask somebody else to give it a try.

**Comment by rzambroni** [comment]
Ok, another collaborator was able to replicate. Will send it to the team so they can take a look.

**Comment by cheungysophie** [comment]
Thanks so much! SophieOn May 9, 2024, at 11:57 AM, rzambroni ***@***.***> wrote:﻿
Ok, another collaborator was able to replicate. Will send it to the team so they can take a look.Thanks for the report!

**Comment by collie21** [comment]
I'm having the same issue, if i add the shimmer animation to anything and test the project you can see the shimmer work like in the images below, but once the page has loaded, it removes the images and leave a blank screen. any help on fixing this would be much appreciated.

![Screen Shot 2024-05-10 at 11 39 48 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/7255623/0c14a108-ece6-46e8-a450-00e937cfb4f3)
![Screen Shot 2024-05-10 at 11 40 31 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/7255623/37661863-33be-4c46-a59c-141015e57b52)
![Screen Shot 2024-05-10 at 11 42 13 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/7255623/6a503106-e20b-422c-ac45-91a20d4d57be)

**Comment by mmearly** [comment]
Hi all! The underlying problem here is that shaders are not currently compatible with the Flutter web HTML renderer. This is a [known issue in Flutter](https://github.com/flutter/flutter/issues/84984) and has been for some time. Unfortunately we use the HTML renderer in Test Mode, so we are not bale to properly display widgets with the shimmer or tint animations there.

A workaround would be to use Run Mode instead with CanvasKit instead of HTML rendering. Go to Settings > App Settings >  Web Publishing and enable Use CanvasKit. Then if you run your application in Run Mode (the dropdown next to the Test Mode button > the play button icon), you should be able to see your animations. Web Deploy with Use CanvasKit enabled should also work.

**Comment by SpirikleOfficial** [comment]
Also facing the same issue. Apply shimmer effect to a button. Then when we go to test it, the widget is invisible. We also enabled the CanvasKit option and tried again but still same issue.

**Comment by gspassky** [comment]
It seems shimmer effect discards container background, so if the shimmer color is white and container is gray - you won't see anything on white background. You should make the container white and the shimmer gray - then everything will work fine )

**Comment by codingraphub** [comment]
Same here as we are in february 2025, so the issue has not been solved yet

**Comment by kendrick-gs** [comment]
only workaround is wrapping the container in a stack and duplicate the container, one with animation one without, container with animation also must come after the one without in the widget tree. fill and childs doesnt show up as long as there is shimmer animation on top of container
