### ISSUE TITLE
Flutterflow web app not loading and software dont upload images

### ISSUE THREAD

**Issue by txoh01** [FlutterFlow/flutterflow-issues#2858]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Flutterflow web app is not loading and the software is not uploading images; the issues just started a few days ago.

### Expected Behavior

To load so i would be able to work on web.

### Steps to Reproduce

The Flutterflow webpage failed to load.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Nah

### Context

I can't load the web page, can't work at all, and even so, the software doesn't even upload images.

### Visual documentation

![Captureedw](https://github.com/FlutterFlow/flutterflow-issues/assets/140348161/fe42756d-48af-4bff-af1c-1232b0f63b3b)

### Additional Info

![Captureedw](https://github.com/FlutterFlow/flutterflow-issues/assets/140348161/20d79bfe-ecaa-4700-b020-23a18ea1b299)

### Environment

```markdown
FlutterFlow version:v4.1.47+ (released May 4, 2024)
Platform:windows
Browser name and version:chrome Version 124.0.6367.119 (Official Build) (64-bit)
Operating system and version affected: windows 10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [X] Data was not saved in a snapshot
- [X] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [X] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by txoh01** [comment]
![Capturesffvgd](https://github.com/FlutterFlow/flutterflow-issues/assets/140348161/41a4ef64-b44a-41a0-8719-77bd964bb7f9)
This screenshot of the flutterfow app not uploading but loading till forever

**Comment by rzambroni** [comment]
Hi @txoh01, I'm sorry you are dealing with this problem. I tried replicating the issue you are describing but the web app is loading fine on my end. Have you tried opening the web app in an incognito tab or cleaning your cache? 

The bug when uploading assets from the windows app was already reported and the team will be working on that soon. 

Thanks.

**Comment by txoh01** [comment]
That's in incognito mode, just loading and no response; the web app in Chrome just keeps loading; I can't log in to the to the web.

https://github.com/FlutterFlow/flutterflow-issues/assets/140348161/29f7ae86-9eec-4b1b-bc97-3ddc9f92e4c1

**Comment by rzambroni** [comment]
Unfortunately, there is not much we can do from here as it seems to be specific to your browser, would you mind following up with our support team? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by rzambroni** [comment]
Hey @txoh01, i saw a similar issue today and the problem for this user was that he didn't had the correct date and time on his computer configuration. That was causing the website to reject the connection. In case that helps.
