### ISSUE TITLE
Can not authenticate with google on android.

### ISSUE THREAD

**Issue by Doli05** [FlutterFlow/flutterflow-issues#2859]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I run my app on the browser, it lets me authenticate with google (I enabled email and password and google authentication), but if I run the app with my phone (FF preview app) it gives me the error: " Access blocked: Test App's request does not comply with Google's policies

Test App's request does not comply with Google's "Use secure browsers" policy. If this app has a website, you can open a web browser and try signing in from there. If you are attempting to access a wireless network, please follow these instructions You can also contact the developer to let them know their app must comply with Google's "Use secure browsers" policy. Learn more about this error

If you are a developer of Test App, see error details Error 403: disallowed_useragent"

### Expected Behavior

It should redirect me to Google's authentication page.

### Steps to Reproduce

-Create and authentication page
-Use google authentication on android FF preview app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlfLl8Y9gru5I1pDcKsJqhQAkH1x/bZJEl9dTTREYJbbxEYoQf+r+VHhCTcOefG1UGlajuEUE7tLmuOPPE/oEGw+qeINozZNUTgnwfEyiRpC7Dc+RPEZ8DcFhfmXG0KWC2BBQGNVaLHA5w1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I use email and password as my authentication providers, and it always works, but with google it doesn't because of that error.

### Visual documentation

![Screenshot_20240505_092714](https://github.com/FlutterFlow/flutterflow-issues/assets/166296512/a7cbeb6d-df31-47cc-85bd-60283cba18ec)

### Additional Info

https://community.flutterflow.io/ask-the-community/post/google-sign-in-issue-in-ff-preview-app-on-android-43yhIlOleO3Xpef
Here's another guy that reported the problem in the community page, same exact problem.

### Environment

```markdown
- FlutterFlow version: 4.1.47
- Platform: Android
- Browser name and version: FF preview 0.0.3
- Operating system and version affected: Android 14
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @Doli05 thanks for your report. Could you explain again how are you running the app to see this behaviour? You say Preview on Android, but the preview or test modes don't run on a physical device. We tried the Local Run on an Android device, but the Google Authentication is working correctly. <br>Please let me know how are you running the app so we can try to replicate it. Have a great day!

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
