### ISSUE TITLE
When I use run mode on the browser, some widgets in the authentication page disappear.

### ISSUE THREAD

**Issue by Doli05** [FlutterFlow/flutterflow-issues#2860]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the run mode on the browser, only in the authentication page every text just disappears. It looks like they don't even take space.
This happens 100% of the times I run the app.

### Expected Behavior

It should show all widgets in the page.

### Steps to Reproduce

Create an authentication page;
Run the app in run mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlfLl8Y9gru5I1pDcKsJqhQIgQ0QnU7gnlO1ucx40B7bqOqQIfvfCT0NKT9eqSmxUPU79rE8D0/zOhuzDJe4pOTeZc7ZM0JVAdT3wQkmVR6a3EKuwRHx9J9JWCmqM5rezuxFvOttoLk4m6jmbN63qNleeY8aSfxBlZ7vfcPo=

### Context

It doesn't allow a user to authenticate properly.

### Visual documentation

![communityPost](https://github.com/FlutterFlow/flutterflow-issues/assets/166296512/e69fd32d-865b-4219-b442-2808a5555b71)

### Environment

```markdown
- FlutterFlow version: 4.1.47
- Platform: Flutterflow app
- Browser name and version: Google 124.0.6367.119
- Operating system and version affected: Windows 10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @Doli05, i attempted to replicate this issue on a blank project but i'm unable to do so with the steps you provided. Can you replicate this consistently on a blank project?

Thanks.

**Comment by Doli05** [comment]
@rzambroni I tried on a blank project now, and you're right, I'm also unable to replicate the bug, BUT I also tried to duplicate my project, use another firebase project, and I get the same result you see on the screenshot I published, so I think this only happens to few projects. Honestly for me this bug isn't really a problem, but I'm afraid that when I publish the app on the app stores people are going to get the same result.

**Comment by myrodar** [comment]
Hey, I got the exact same problem as him. I also tried to reproduce it in another project, but it doesnt seem to work. 

Here is what I have:
![Capture d’écran 2024-05-07 134039](https://github.com/FlutterFlow/flutterflow-issues/assets/108596859/a7c4cfc4-d369-454a-99e2-b9ef7d0827d2)

For reference, in the google console when trying to troubleshoot, I get this when clicking on the missing text;
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/108596859/b11f2f7d-d1a5-480d-acfc-96e9d8a00e4a)

**Environment**
- FlutterFlow version: 4.1.48+
- Flutter version: 3.19.1
- Platform: Flutterflow app
- Operating system and version affected: Windows 10

Hope this helps!

**Comment by rzambroni** [comment]
Strange, i'm made a few more attempts but i can't get it to fail on a blank project. We need to be able to pinpoint how to replicate consistently before sending it to the engineers.

**Comment by myrodar** [comment]
I managed  to fix the issue. If you have more than one language, you need to translate to all language before running the test.

Here are the issues link: 
https://github.com/FlutterFlow/flutterflow-issues/issues/2010 
https://community.flutterflow.io/troubleshooting/post/no-texts-are-displayed-in-test-mode-FwD0sAZGccKnn7R
