### ISSUE TITLE
Superbes uplod media 403 error {"statusCode":"403","error":"Unauthorized","message":"invalid signature"}

### ISSUE THREAD

**Issue by JedarWex** [FlutterFlow/flutterflow-issues#2862]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've run into a problem that in the superbase database project that running with the 15.1.1.24 Postgres upgrade the image upload still works but in the projects running with the 15.1.1.44 Postgres upgrade to upload images I get this error: {"statusCode": "403", "error": "Unauthorized", "message": "invalid signature"}

Both have exactly the same baskets policy settings.
API exposed schemas public, storege, graphql_public.
There are no access problems with the tables.

### Expected Behavior

The ppvo project is the working project, the ppp project is the one that doesn't work. These projects, created to detect the bug, only contain image uploads. It would be nice if the ppp project worked like the ppvo project.

### Steps to Reproduce

1. create a new page, 2. add image element, 3. add action to widget, 4. select action to upload media, 5. select superbase option

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESiMj604lgodgF7rXqdcd6hQIgQ0QnU7gnlO1ucx42G5CqE7AiY86lU0NKQvWjfwtiHFf8uH0x/6HIiN/QVvk3EzubbJRe0JVAETzyYEWmWpTWCqmCTnJ5GphVGm6m58CF3CVNNfVoWUIc3DiXN63qNleeY8aSfxBlZ7vfcPo=

### Context

Image upload does not work with the newer superbase databases.

### Visual documentation

Not working project!!
![pppp](https://github.com/FlutterFlow/flutterflow-issues/assets/168984521/a97caa31-3139-41a8-81fd-ea70fe2dfa04)

Working project!!
![ppvo](https://github.com/FlutterFlow/flutterflow-issues/assets/168984521/bd45dce8-ccf7-4d5d-9026-c65c0349c24a)

### Environment

```markdown
- FlutterFlow version: 4.1.47+
- Platform: windos
- Browser name and version: crome 124.0.6367.119
- Operating system and version affected: windos
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by JedarWex** [comment]
I have also sent this reply to superbase:

Hi,
This may be an issue with how the previous version of your client library manages updates to authentication. Could you try updating your supabase client?

**Comment by JedarWex** [comment]
The issue was resolved in the superbase API settings for Exposed schemas not matching the order of the projects. I do not know why.

**Comment by TheOtherBrian1** [comment]
@JedarWex can you remove the name from the [comment](https://github.com/FlutterFlow/flutterflow-issues/issues/2862#issuecomment-2094901233)?

**Comment by Alezanello** [comment]
@TheOtherBrian1 Done!
