### ISSUE TITLE
Can't set form fields in page's action block

### ISSUE THREAD

**Issue by r-miljons** [FlutterFlow/flutterflow-issues#2867]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you have actions that set form fields and want to save yourself from tracking down every single place on a page where you are using said action by creating and action block... currently it's not possible, because "set form fields" action doesn't show up as a choosable action in the action block view.
Please fix because it will save a lot of wasted time and headaches from tracking duplicate code in multiple places!

### Expected Behavior

Action block should contain "set form field" as a choosable action

### Steps to Reproduce

Try to create an action block with a "set form field" action!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lvLl8c9goelG+KX6ccFvmiMUKUc7bY03kutTcxM8J5jbP4Ycf/fRUFtUcO6qSlZ2J2D9inIX/MrviuLxG8EDNRyuRoQ5wbhcYQrjVni5b4ywPr63b3JRHd1XfVCP1p+ngB5AVbFhW1oh2lyqGNmAfz7bGIzEPVUBMeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Please fix because it will save a lot of wasted time and headaches from tracking duplicate code in multiple places!

### Visual documentation

no need

### Environment

```markdown
- FlutterFlow version:  4.1.48
- Platform: Windows
- Browser name and version: -
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @r-miljons thanks for your report. Because the App Action Blocks can be used anywhere in the app, it makes sense that they should not be able to modify the state of the Widget (for example setting a Form Field). <br>However, I think it could be possible to enable this feature for the Page action blocks. I will send a request to our Technical team so they can let us know if it's possible to implement this or not.<br>For now, I would suggest you to create an Action block that generates whatever you need to set on the Form Field, and return it as output. This way, you can use everywhere the Action Block that generated the output (and modify it everywhere at the same time) and then have an action that Sets form field with that value. This last one shouldn't change if you change your logic, so you shouldn't need to check in every place you are using it if you change your action block.<br>I hope this was helpful, the technical team will update you in this thread when they have an answer. Have a great day!

**Comment by ignalauret** [comment]
The technical team has confirmed that is possible to implement the Set Form Field on the Page Action Block, so I'm creating a Feature request for this. Sadly that's not available right now, so I hope my workaround was helpful. They will let you know on this thread when the feature is available. Have a great day!

**Comment by Hipnagogi** [comment]
Do we know where page action block set form field feature will be enabled? Is it planned in the roadmap?

**Comment by Hipnagogi** [comment]
> an Action block that generates whatever you need to set on the Form Field, and return it as output. This way, you can use everywhere the Action Block that generated the output (and modify it everywhere at the same time) and then have an action that Sets form field with that value. This last one shouldn't change if you change your logic, so you shouldn't need to check in every place you are using it if you change your action block.
> I hope this was helpful, the technical team will update you in this thread when they have an answe

OK - can you elaborate how to use your walkaround. 
Can I assign set form field action once and trigger it from different part of the app?
A way to reload whole page would do the trick. But if you choose same page as you are in navigation trigger it won't reload.

**Comment by tiagosilveiransj** [comment]
Any updates on this @ignalauret? I have a page with a lot of TextFields. I've made the trick to have a custom action to generate the result, but i need to set all the form fields at the onFocusChange event of each formfield since an update in an formfield will result in an update at the others.
