### ISSUE TITLE
Unable to build custom Google Map Widgets even when the code contains no bugs

### ISSUE THREAD

**Issue by koushikraj96** [FlutterFlow/flutterflow-issues#2868]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Facing the following error during build:

Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

### Expected Behavior

A successful build since the code does not contain IDE errors

### Steps to Reproduce

Build the following custom widget

// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:google_maps_flutter/google_maps_flutter.dart' as gmaps;

class GoogleMapLocationPicker extends StatefulWidget {
  const GoogleMapLocationPicker({
    super.key,
    this.width,
    this.height,
    this.initialCamera,
    this.initialMarker,
    this.initialZoom,
  });

  final double? width;
  final double? height;
  final gmaps.LatLng? initialCamera;
  final gmaps.LatLng? initialMarker;
  final int? initialZoom;

  @override
  State<GoogleMapLocationPicker> createState() =>
      _GoogleMapLocationPickerState();
}

class _GoogleMapLocationPickerState extends State<GoogleMapLocationPicker> {
  gmaps.GoogleMapController? _mapController;
  gmaps.LatLng? _lastMapPosition;

  void _onMapCreated(gmaps.GoogleMapController controller) {
    _mapController = controller;
    _updateMapPosition(
        (widget.initialCamera ?? gmaps.LatLng(0.0, 0.0)) as LatLng);
  }

  void _onCameraMove(gmaps.CameraPosition position) {
    _lastMapPosition = position.target;
  }

  void _onCameraIdle() {
    if (_lastMapPosition != null) {
      FFAppState().update(() {
        FFAppState().selectedLocationGlobalState = _lastMapPosition as LatLng;
      });
    }
  }

  void _updateMapPosition(LatLng position) {
    _mapController
        ?.moveCamera(gmaps.CameraUpdate.newLatLng(position as gmaps.LatLng));
    FFAppState().selectedLocationGlobalState = position;
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: widget.width ?? MediaQuery.of(context).size.width,
      height: widget.height ?? MediaQuery.of(context).size.height,
      child: gmaps.GoogleMap(
        onMapCreated: _onMapCreated,
        initialCameraPosition: gmaps.CameraPosition(
          target: widget.initialCamera ?? gmaps.LatLng(0.0, 0.0),
          zoom: widget.initialZoom?.toDouble() ?? 14.0,
        ),
        markers: {
          if (widget.initialMarker != null)
            gmaps.Marker(
              markerId: gmaps.MarkerId('initialMarker'),
              position: widget.initialMarker!,
            ),
        },
        onCameraMove: _onCameraMove,
        onCameraIdle: _onCameraIdle,
        mapType: gmaps.MapType.normal,
      ),
    );
  }
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8r13It2xNtF1artbcdagSg7JnIiTL03qu0bGBYbCIzQB4YEacn7QFhuOLWoYXNtKEWGhjsFzNbvuN/TG/E5IRysbKJm1rtqZzqVIXu/aoS4PMy8OnwmO/lQBWXE3MCrqhJSBLFeSXAg2l+MJ9zKcCjaJ7H4Zwh9f6PHaOI=

### Context

I am trying to implement a location picker where I can help the user pick the coordinates for a given address on a google Map running on iOS or Android.

### Visual documentation

just building this widget in a blank app causes the following error,

![Screenshot 2024-05-07 at 9 23 23 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/33293930/9d7e2862-caf1-4135-8e6b-7202fe71b3a2)
![Screenshot 2024-05-07 at 9 23 53 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/33293930/10d62059-4ebf-4877-94a2-187c6183f333)

Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

### Environment

```markdown
- FlutterFlow version: 4.1.48
- Platform: Mac OS Sonoma
- Browser name and version: FlutterFlow App for MacOS
- Operating system and version affected:  MacOS Sonoma 14.4.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @koushikraj96<br>I was able to reproduce the issue. You need that the parameters type defined in your custom code to match the parameter type defined in your Widget Settings.<br><br>Currently, some properties, such as the initial camera are defined like this:<br><br>final gmaps.LatLng? initialCamera;<br><br>This takes the definition of LatLng implemented in the google_maps_flutter package. However, at the Widget Settings section it is defined as LatIng, which uses the definition implemented in FlutterFlow.<br><br>One possible solution to this is to receive a initialCamera value type as defined in FlutterFlow (as an LatLng and not gmaps.LatLng), and then make the conversion to the type used in the package as a variable. Take this as an example:<br><br>final initialCameraLatLng = gmaps.LatLng(widget.initialCamera?.latitude ?? 0, widget.initialCamera?.longitude ?? 0);<br><br>This should solve your issue.<br><br>Thanks for the report!

**Comment by koushikraj96** [comment]
Hello! Thanks for the prompt response to the issue. I have downloaded the project and fixed the issue manually in my ide.

// Automatic FlutterFlow imports
import '/backend/schema/enums/enums.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:google_maps_flutter/google_maps_flutter.dart' as gmaps;
import 'package:the_genie/flutter_flow/lat_lng.dart' as custom;

class GoogleMapLocationPicker extends StatefulWidget {
  const GoogleMapLocationPicker({
    super.key,
    this.width,
    this.height,
    this.initialCamera,
    this.initialZoom,
  });

  final double? width;
  final double? height;
  final LatLng? initialCamera; // Change to FlutterFlow's LatLng type
  final int? initialZoom;

  @override
  _GoogleMapLocationPickerState createState() =>
      _GoogleMapLocationPickerState();
}

class _GoogleMapLocationPickerState extends State<GoogleMapLocationPicker> {
  gmaps.GoogleMapController? _mapController;
  LatLng? _lastMapPosition;

  void _onMapCreated(gmaps.GoogleMapController controller) {
    _mapController = controller;
    _updateMapPosition(widget.initialCamera ??
        const LatLng(0.0, 0.0)); // Change to FlutterFlow's LatLng type
  }

  void _onCameraMove(gmaps.CameraPosition position) {
    _lastMapPosition = custom.LatLng(position.target.latitude, position.target.longitude);
  }

  void _onCameraIdle() {
    if (_lastMapPosition != null) {
      FFAppState().update(() {
        FFAppState().selectedLocationGlobalState = _lastMapPosition;
        print(FFAppState().selectedLocationGlobalState);
      });
    }
  }

  void _updateMapPosition(LatLng position) {
    _mapController?.moveCamera(gmaps.CameraUpdate.newLatLng(
        gmaps.LatLng(position.latitude, position.longitude)));
    FFAppState().selectedLocationGlobalState = position;
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: widget.width ?? MediaQuery.of(context).size.width,
      height: widget.height ?? MediaQuery.of(context).size.height,
      child: gmaps.GoogleMap(
        onMapCreated: _onMapCreated,
        initialCameraPosition: gmaps.CameraPosition(
          target: widget.initialCamera != null
              ? gmaps.LatLng(widget.initialCamera!.latitude,
              widget.initialCamera!.longitude)
              : const gmaps.LatLng(0.0, 0.0),
          zoom: widget.initialZoom?.toDouble() ?? 14.0,
        ),
        onCameraMove: _onCameraMove,
        onCameraIdle: _onCameraIdle,
        mapType: gmaps.MapType.normal,
      ),
    );
  }
}


but for the above code to work and handle conventions I would have to import 'flutter_flow/lat_lng.dart' which the UI does not allow. Any solutions?

**Comment by koushikraj96** [comment]
Thanks for the prompt response @msusviela.
