### ISSUE TITLE
Update Document by Increment not working

### ISSUE THREAD

**Issue by alearjun** [FlutterFlow/flutterflow-issues#287]
## Expected behavior (required)

Integer document field should increment by 1 as selected in FF. 

## Current behavior (required)

Action is set to increment by 1 and the document is not being updated. 

## To Reproduce (required)
1. Create a document where one field is a number. Set the number to 0 on document create.
2. Create a button that creates the document and sets the number equal to 0. 
3. Create a button that updates the document and increments the number field by 1 on click. 
4. Run the app. 
5. I am in firebase and the document is not being updated. 

### Bug Report Code (required)

```
await widget.userQuest!.reference.update(userCartUpdateData);
          final usersUpdateData = {
            'num_quests': FieldValue.increment(1),
          };
```

## Context (required)
I am trying to update a document to know which question users are on so they can return to the same question. This is the last feature needed before live deployment. 

## Screenshots / recordings
N/A

## Your environment

Arc and Chrome Browsers
MacOS

**Comment by agreaves** [comment]
Hi @alearjun, could you please generate and include the Bug Report Code? You can generate this by right clicking anywhere in the widget tree and clicking "Generate Bug Report Code". Thanks!

**Comment by alearjun** [comment]
Here it is: 

ITEeh8/l34VItbxG1antKcJKjQMxJEQnargvhNVxa00dIuLnB7MXbuvRQxBuTtereWNUGmCIhl4x/92LhdjlV/Y6CxLDJ+AHl/E0LlSrGAc=

**Comment by agreaves** [comment]
Thanks for this! Strangely though the code looks correct as do the Firestore rules.

You are trying to increment the `'num_quests'` field on the User correct? That is the part that is not working?

It looks like the only way for me to debug is to run the application, would you be ok with me running it and creating an account to recreate the issue?

**Comment by alearjun** [comment]
@agreaves Yes, I'd be ok with that. 

I reviewed the Flutter code as well, and it looked correct to me as well. That's why I was confused as to why it wasn't working.

**Comment by agreaves** [comment]
Hi @alearjun, the number is not being incremented when you suspect because this only occurs in the `true` branch of the conditional action (when it's the last question). When this occurs, the `'num_quests'` number is indeed incremented as expected. However, when the condition is false it will not.

**Comment by alearjun** [comment]
@agreaves sorry I gave the wrong information. The `currentQuestionIndex` is not being updated in the false condition was the issue I had.

**Comment by alearjun** [comment]
I tested this in run mode, test mode, and downloading the code and running it locally.

**Comment by agreaves** [comment]
Hmm, I'm also seeing the `currentquestionindex` field being incremented correctly. You can probably verify this in the Firebase panel. You are looking at the `user_cart` document correct? Everything seems to be working on my end.

**Comment by alearjun** [comment]
Hmm that's very strange. Let me try in a different browser and see what happens.

**Comment by alearjun** [comment]
@agreaves resolved! I had to delete my user account, user cart document, and user document. Once I created a new user it worked properly. Thanks!

**Comment by agreaves** [comment]
Awesome, glad it's working for you! 🙂
