### ISSUE TITLE
Can't add App Assets from the Windows App

### ISSUE THREAD

**Issue by IvanCalex** [FlutterFlow/flutterflow-issues#2871]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to set an image as the splash screen, but when I upload, it just keeps loading. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169065685/97f170be-fad7-468c-9905-f1ec73628ae6)

### Expected Behavior

Ability to upload a splash screen. 

### Steps to Reproduce

1. create new project
2. Go to assets
3. click on upload for splash screen
4. select image
5. keeps loading perpetually

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

I can't set a splash or a logo for my app. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169065685/3c06d831-12b3-4cb6-bcc0-0944b01cc0e7)

### Environment

```markdown
- FlutterFlow version: 4.1.48
- Platform: Laptop WIndows
- Browser name and version: Chrome 124.0.6367.119
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @ivanCalex, thanks for the report, yes, there are currently a few known issues related to upload assets from the windows app not working. Will add this to the list. 

As a workaround you can use the webapp to upload your assets for now. (custom icons, fonts, assets, splashscreen, app icon, etc)

Thanks.
