### ISSUE TITLE
Cannot Upload SVG files as assets into my windows flutterflow app

### ISSUE THREAD

**Issue by Donyashirazi** [FlutterFlow/flutterflow-issues#2873]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am having trouble with uploading my SVG file into the flutterflow windows app (svg files cannot be uploaded), while it works fine in the web version.

### Expected Behavior

the SVG files should be uploaded as an asset in the windows version as well, just like the web version.

### Steps to Reproduce

in the windows version:
1.Create a new page
2. Add Image widget
3. Choose image type "asset"
4. Try to upload svg images...

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kl/H605NOmN8B15DtbexaljoQH0A9TLJIqO1+ZxYjGeOvBJYTPsnSV1VtWOqHfwl6OWClkkcDpsKJkYSTV8EEKTuaRbk4yIdbUxDgZD6gbK6MCauVPUZQDeRnIXLH5rW3phZAWctvW3g73Fz7HNi+Y3qCf9qOYwx5e6fDbOY=

### Context

I am trying to upload an SVG into my project from the FlutterFlow windows app.

### Visual documentation

![flutterflow-bug](https://github.com/FlutterFlow/flutterflow-issues/assets/111065360/a71e0128-ee58-484b-91d2-5ba5d57d2117)

### Environment

```markdown
- FlutterFlow version: 4.1.47
- Platform: windows 11
- Browser name and version: 23H2
- Operating system and version affected: Windows 11 Home
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @Donyashirazi, thanks for the report, yes, there are currently a few known issues related to upload assets from the windows app not working. Will add this to the list.

see: 

* [https://github.com/FlutterFlow/flutterflow-issues/issues/2628](https://github.com/FlutterFlow/flutterflow-issues/issues/2628)
* [https://github.com/FlutterFlow/flutterflow-issues/issues/2871](https://github.com/FlutterFlow/flutterflow-issues/issues/2871)

As a workaround you can use the webapp to upload your assets for now. (custom icons, fonts, assets, splashscreen, app icon, etc).

Thanks.
