### ISSUE TITLE
Custom Icons from Icomoon Inconsistently Available

### ISSUE THREAD

**Issue by d6p2b** [FlutterFlow/flutterflow-issues#2876]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Imported a custom icon font from Icomoon which contains 2 glyphs.  One renders correctly while the other renders as a question mark.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4257088/45a7b0d5-849e-480a-ab4d-17a726b236f9)

### Expected Behavior

Both glyphs should be available as custom icons in the project.

### Steps to Reproduce

1. Create a new project.
2. Import the custom icon font (ttf) and dart files ( from the Icomoon export.  Zip attached)
3. Immediately notice one icon is not rendering.

[blackbuck-v1.0 (8).zip](https://github.com/FlutterFlow/flutterflow-issues/files/15255696/blackbuck-v1.0.8.zip)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfj/KAsIpgoccB7oSJYO1smWIXQ2EcTIMziNZ+exUbfaL1BuwPd8n4XFduON+iaVNcI1GJoGYHwMrOkd/hKe43FxydGYh5zqhtFhb0e2iXRbGVEc6aPHcnEdNQG3aw36WjoBIkPbJ1WHw/3WbzJvOQRXLDBOu/Zwh9f6PHaOI=

### Context

Trying to use a custom SVG based glyph as an icon in my project.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4257088/f001b190-6eb5-48d2-befa-4a23cf948732)

### Additional Info

I've used OpenType's glyph inspector tool ( https://opentype.js.org/glyph-inspector.html ) to confirm the TTF files contains the two expected glyphs.  I've also confirmed the SVG the missing/damaged glyph is based on is just simple paths.

### Environment

```markdown
- FlutterFlow version: 4.1.48
- Platform: macOS
- Browser name and version: 
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @d6p2b. I wasn't able to replicate this issue and the images are being shown correctly. Is this still happening?

**Comment by d6p2b** [comment]
Still happening with FF v4.1.49.  One icon is correct the other is the question mark placeholder.  I tried removing the custom icons from the project and reloading them with the same result.  

<img width="1216" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4257088/43f2db54-3841-4670-bd34-9ac6954dd8a6">

**Comment by msusviela** [comment]
Hey @d6p2b, Thanks for your report, So sorry you are experiencing this issue. We tried again and were not able to reproduce this issue. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by d6p2b** [comment]
Turns out the issue is the custom icons aren't correct in the FlutterFlow macOS app (question mark placeholder) but they are fine in a built project.  So.... maybe this is expected behaviour.  🤷🏻‍♂️
