### ISSUE TITLE
Multiple Execution of On Data Change Actions

### ISSUE THREAD

**Issue by satyadevshetty** [FlutterFlow/flutterflow-issues#2877]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

**- Firebase Query** - I see that the firestore query is executed only 2 times, 1 more time is from another QUERY which i have in the project
**- Multiple Alerts -** As you can see in the video i have configured pop ups for testing, these alerts should appear only once for 1 data change ; Currently each time I change the data field in Firestore Database the alerts seem to double for example: 

1. 1st time - I modify a database field the alerts show for 2 times
2. 2nd time - I modify a database field the alerts show for 4 times
3. 3rd time - I modify a database field the alerts show for 8 times

**- Data Change -** I have only change 1 data field once time only: stripe_subscription_status
**- Backend Query (Not Accessible in Actions) -** I cant seem to be able to choose the backend query which i have defined for the page. I have had to include a Firebase Query (One available in Actions) 

Questions:

Why am i getting multiple execution of the same actions? Looks like its going into a loop?

How do i make sure that the actions are executed only once ?

### Expected Behavior

- I should execute the Data Change Section only once for each change of data
- Its executing it multiple times
- Backend Query (For page) - Should be Accessible in Actions

### Steps to Reproduce

1. Firestore Database - Connect a Firestore Database to Project
2. Backend Query - Define a Backend Query on the page
3. On Data Change - Configure a informational alert , put anything in it
4. Run Mode - Launch the project in Run Mode
5. Change Field in Database - Change any field in Firestore Database, it should fire the On Data Change Actions
6. Alerts Multiply - Change field again , you should see the no. of alerts double i.e., if 1st time if no. of alerts were 2, 2nd time it will be 4

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8elcr1z89goe5E176JKe9anjwXKUg8UI0vjsN+TQ0jB4zkOpYMOuHORFtuOLSlSnxYME+Zpzky+d7Mv+buMPZdHxWVRrZ9+bpqRDrgQji7WrGVO8+RbWNRHZhUGmKG16eFgREmANZpLFoZwEOTN9m+QgXFG67YCkcjQciiEN/JjHCEGg/vMDhJ+xgAGE+hDuQUcgjWpMD4xPkT3ezrxw==

### Context

- I am building a SAAS application. 
- I am trying to Update the status of subscription on the buttons & In Status bar in Settings
- On Payment Failure or Subscription expiry - I want to show the user a pop up stating his subscription has failed & also update the subscription status section
- Multiple Alerts - The multiple alerts will annoy the user as he will have to keep clicking on OK in the alert to dismiss it

### Visual documentation

- Video which shows the issue with Multiple Execution of On Data Change Actions: https://drive.google.com/file/d/13whIB6yZfWo-8owWuhuhkR3GwnD-Vige/view?usp=drive_web
- You can see in below screenshot that I am using OnDataChangeCountTesting (Page State) to keep track of no. of executions of On Data Change. I have a alert in the Action chain which displays the value of the Page state
<img width="847" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/49232059/afd24994-f388-4c42-870b-88e0f3136f7c">

### Additional Info

Check This issue, seems related to my issue - https://github.com/FlutterFlow/flutterflow-issues/issues/2576 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.48+ released May 8, 2024 Flutter version is 3.19.1

- Platform: Web (this is a web app)
- Browser name and version: Firefox , Chrome  (Browser really doesnt matter)
- Operating system and version affected: windows 11 or 10 (OS doesnt matter)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @satyadevshetty thanks for your report. Sadly I'm not able to replicate your issue from a blank project. I followed your steps and I am getting only one pop up onDataChange. <br>Could you please try to replicate this on a blank project and share me the Bug report code? That way I can check out the behaviour and reproduce the bug. Thanks and have a great day!

**Comment by satyadevshetty** [comment]
I have created a blank project with the same issue, you can check it out: test-project-on-data-change-multiple-execution-vz7w0a

**Bug Report Code:** ITwwz/Hqx89grs9J1s/IdfoxnSQXQz47U5I70tZ6EBIYCJzrBOwTe8/OUFFoTemlTHxbPVmWoGcJp86PveOeF+83C0uBGI98wq9xcA2VWmOub6aUPbqKakclONxjFUyByKuKiAFQCO9aWkZm3V7zHd69QjPYNrG2C2o0APL8LrzRoUKJKg/RVRZs+2sJMWm0Cdk2TxGuhbTG0vYri5Klrc1c6TcjpPC42s3tVAqLQUE=

**Comment by satyadevshetty** [comment]
@ignalauret - Any update on this ? Were you able to have a look at the standalone project & replicate the issue with On Data Change executing multiple times? Please let me know as i am unable to proceed further with my project because of this issue

**Comment by satyadevshetty** [comment]
@ignalauret - I am not getting any response or updates about this issue. Is there anyone who can help me resolve this ? I am stuck on my project & its very important for me

**Comment by ignalauret** [comment]
Hey @satyadevshetty I'm sorry for the late response. Please let me know if you were able to make it work with the new versions of FF, or if you need me to review it again.
