### ISSUE TITLE
'Control Page View improperly set' when used in a callback action of a Custom Action

### ISSUE THREAD

**Issue by Hellie3** [FlutterFlow/flutterflow-issues#2878]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a custom function that takes an action as an argument. In calling the custom action, I need to pass the action 'Control Page View' as the argument, but after I set it up, the platform says 'Control PageView action improperly set.' even though it is set properly. Note that there is no problem with passing other actions as the argument.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e317b54d-2cde-4ebe-a823-67799c8e8143/b0d62862-de62-4279-ae62-400ac8530a69?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMzE3YjU0ZC0yY2RlLTRlYmUtYTgyMy02Nzc5OWM4ZTgxNDMvYjBkNjI4NjItZGU2Mi00Mjc5LWFlNjItNDAwYWM4NTMwYTY5IiwiaWF0IjoxNzE1MjY1NTI5LCJleHAiOjMzMjg1ODI1NTI5fQ.50i85cC6JGxQaGJCtr7tKI_9Jh3hDzUsyd_crKm-32g)

### Expected Behavior

I expect not to get this message, and that the app mobes to the expected pageview when the action is called.

### Steps to Reproduce

1. create a new page
2. add a Page View widget
3. add a button
4. create a custom function that executes a simple task and also takes an action as the argument
5. using the button, call the custom function
6. pass the control pageview action as the custom action's argument
7. se the error in Project Issues

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gouEE7Yf+bMFAhQAkH1x/bZJEl9cbaEk3COrmP4k1P+r+V1tZZN+kfAtte1D/hmMJpuDUhvzDK/pfaA6reINowZF+SzvLQT+mMpSWCpCSbUElBeJWCnKX56SN3BQkIut1LGQ/w2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I have used the flutter_tts package in creating a custom action for reading aloud some text in a quiz app. I need to execute certain actions only after all the text is read. The package supports this. To accomplish this, I have passed an action as one of the custom action's arguments. I call the custom action when needed, and successfully pass several actions (via the action flow editor). But one of the actions I need to pass is a "Control Page View' action to move to the next pageview, and that's where the error shows up, even though I set the pageview action as I have done successfully elsewhere in the app. The screenshots I share are from a test app, not where I have implemented the tts.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/acbdfc87-e164-46ad-90e1-9c371cc73c81/da42327d-c152-44f4-b711-7b08a190fae3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hY2JkZmM4Ny1lMTY0LTQ2YWQtOTBlMS05YzM3MWNjNzNjODEvZGE0MjMyN2QtYzE1Mi00NGY0LWI3MTEtN2IwOGExOTBmYWUzIiwiaWF0IjoxNzE1MjY1NTI5LCJleHAiOjMzMjg1ODI1NTI5fQ.dVHmuysRuF_NLntZYbWMo4EHJdaaDrDcPNZ5HM0nSXI)

[https://github.com/FlutterFlow/flutterflow-issues/assets/169204780/35d21764-d4ce-4c87-bf2c-92052902f119](https://github.com/FlutterFlow/flutterflow-issues/assets/169204780/35d21764-d4ce-4c87-bf2c-92052902f119)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.48+
- Platform: Web
- Browser name and version: Chrome Version 124.0.6367.119 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Version 10.0.22631 Build 22631
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] undefined\~100% of the time
- [ ] undefined\~50% of the time
- [ ] undefined\~10% of the time
- [ ] undefined\~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @Hellie3 thanks for your report. Sadly I'm not able to replicate your issue from a Blank Project, but I'm able to check it out on your project. I will send this to our technical team so they can take a look. They will keep you updated on this thread. Have a great day!

**Comment by Hellie3** [comment]
Hi
I forgot to include a step.
If you call the custom action on the first page of the pageview, then when
you try to set its callback as a Control PageView action, that option won't
be selectable on the list.
You have to call the custom action on the second page and then use a go to
next page pageView action on the first page.

**Comment by Hellie3** [comment]
Hey @ignalauret 
Did you see my previous remark?
This bug is causing a lot of problems for me, since I don't have a reliable way to move to the next pageView after the callback.

**Comment by ignalauret** [comment]
@Hellie3 thanks for the extra details. I'm still not able to reproduce your issue from a blank project, the Page View option is not available. I'm even opening your project, removing the Page View action that you have and trying to add it again, and I'm getting "The are no Page Views on this page.". I'm not sure how you got that action there in the first place, but I'm not sure it's something that is supported at the moment. <br>I can create a Feature request to add Page View interaction from a Component callback. Sadly that's the most I can do here given that this is not a bug I can reproduce from a blank project, but it's only appearing in your project.

**Comment by TahaHamad** [comment]
I'm getting the same exact issue as well!

**Comment by Hellie3** [comment]
The option to select 'control Page View' was available when I opened this report, but not it's not. I guess that it was unintentionally available.
However, I have come up with an efficient workaround for this: I put a countDown timer (with 10 ms) on the page that triggers the desired 'Control Page View' action, and from within the callback I start that timer when needed. 
But it would be nice just to have the option.
