### ISSUE TITLE
DatePicker doesn't accept a locale

### ISSUE THREAD

**Issue by NestManagementIT** [FlutterFlow/flutterflow-issues#2879]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the datepicker, if you click the pencil icon and type in a date like 01/05/2024 this is assumed to be en-US locale. When writing to a text box as format dd/MM/yyyy it will transpose to 05/01/2024 which is incorrect when my locale is en-GB.

### Expected Behavior

I would want the option to provide my locale to the datepicker control. I can manually add the code for Locale outside of flutterflow - I've manually added the locale parameter here and fixed my issue, the rest is generated from flutterflow:

```
await showDatePicker(
  context: context,
  locale: const Locale("en", "GB"),
  initialDate: getCurrentTimestamp,
  firstDate: DateTime(1900),
  lastDate: getCurrentTimestamp
```
Furthermore it should be an option to pick up the users Locale so US consumers would have the expected functionality as would UK based ones.

### Steps to Reproduce

1. Create a page
2. Add a text box
3. Add an icon button
4. Set icon button "On Tap" actions:
5. Action 1 is to show a datepicker
6. Action 2 is to set the textbox to display the Date Picked as format: dd/MM/yyyy
7. Run the app - note the textbox date is transposed. Note there are no locale options in project settings or datepicker settings.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfivHqx89goctH176Jd8dogiQRG0ccTL4zlO1HcxAYGO/yPbJ/d86lTFtvXsu6TUNhHE2WikgdpfzRiuDlFPI7HxCsf75/zKVQVQrKTXq8RZjUPcyNP2tBP5pMf1Ci5p6voxFvOsptS3Bn6kOhfuq8bHPcGZu/Zwh9f6PHaOI=

### Context

I'm UK based and the users of my app will also be UK based and expect a UK calendar. The calendar control works perfectly if you pick a date, but typing is producing egregious results.
I can manually add a locale in flutter very easily, but I'd have to do that for every calendar control in the app on every release.

### Visual documentation

I'm not sure this is necessary, en-US format is MM/dd/yyyy and en-GB is dd/MM/yyyy which is a very common problem. There's just nothing in-app for the locale:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/135339638/c211fe92-ddc2-4376-9cd6-fadbef7bc546)

### Environment

```markdown
- FlutterFlow version: v4.1.48
- Platform: Android/iOS
- Browser name and version: NA
- Operating system and version affected: All android + iOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by nicbyron** [comment]
@msusviela do we have any idea when this will be added? I have a client that this is important for.
