### ISSUE TITLE
Containe By issue for Supabase

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#288]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I want to filter rows using contained by

## Current behavior (required)

Query keeps loading 

## To Reproduce (required)

1. Connect supabase
2. Add Supabase query
3. Use Contained by

### Bug Report Code (required)

operator is not unique: bigint <@ unknown

Following error is thrown by Supabase

operator is not unique: bigint <@ unknown

## Context (required)

Trying to filter using contained by

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @SiraEnterprises, could you please include a project Bug Report Code? This can be generated by right clicking anywhere in the widget tree and selecting "Generate Bug Report Code". Thanks!

**Comment by SiraEnterprises** [comment]
> Hi @SiraEnterprises, could you please include a project Bug Report Code? This can be generated by right clicking anywhere in the widget tree and selecting "Generate Bug Report Code". Thanks!

IT40hcrqw5dgobRJ7s/+bMJVgio5JmY/ULsoletRaDcsfIj2B+wyafSlTxFCYNSrYFFpKEWL+UQF+cLlvc7xCfcEPU+BGdQ5wqphEjn/fFPkEuzyT+3IHDUHZbsSXTTm

**Comment by agreaves** [comment]
Thanks @SiraEnterprises! This too was a bug on our side and will now be fixed upon our next deploy! 🙂
