### ISSUE TITLE
if lottie animation is set as an action, this issue comes up when deploying app to app store

### ISSUE THREAD

**Issue by cheungysophie** [FlutterFlow/flutterflow-issues#2880]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a lottie animation that animates with an action. This works until I deploy my app to the app store. It fails to compile, but when I remove the action and have it auto animate, it works.

```
Codemagic Deploy Output
Failed Step: Flutter build ipa and automatic versioning

Found build number 5 from TestFlight version 0.0.2

Archiving com.willowcompany.eden...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: DZX7J85PYG
Running pod install...                                             915ms
Running Xcode build...                                          
Xcode archive done.                                         20.9s
Failed to build iOS app
Error (Xcode): lib/my_thoughts/discover_me/discover_me_card_picked_3/discover_me_card_picked3_widget.dart:53:13: Error: The getter 'fireworksLottieController' isn't defined for the class '_DiscoverMeCardPicked3WidgetState'.

Encountered error while archiving for device.


Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1
```

ChatGPT says that the issue is:

> The issue in your code stems from the scope of the fireworksLottieController and fireworksLottie2Controller. Currently, these controllers are defined inside the build method, which means they are local to this method and not accessible in the initState method where you're trying to use them.
>
> To fix this, you should define these controllers at the class level, so they are available throughout the class, including in your initState, build, and other methods. Here's how you can adjust your code

### Expected Behavior

It should deploy to the app store with success

### Steps to Reproduce

1. add a lottie file (asset)
2. turn off auto-animate
3. animate as an action
4. deploy app to app store
5. fail to deploy

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk/H134pgoctH176IKcIw+T06NVscTbkz0tZ+bwohfY/kBLMcPeLSVBBLYteDY2x+ME6KgjozwdL5kvHpUcdcOTGBfKo7z75XQQn/fHmQbrXQCLWVPWt7N/1mCmK0yqSRryNSKfVYW3w81GGEN/CrG3qCf9qOYwx5e6fDbOY=

### Context

i'm unable to deploy app, so i have currently removed this animation for now.

### Visual documentation

![Screenshot 2024-05-09 at 10 32 42 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/64fe9baf-a5de-4c43-bbeb-1b9d955b656e/71897193-e2d9-44ea-87cc-18b8efd1d02b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NGZlOWJhZi1hNWRlLTRjNDMtYmJlYi0xYjlkOTU1YjY1NmUvNzE4OTcxOTMtZTJkOS00NGVhLTg3Y2MtMThiOGVmZDFkMDJiIiwiaWF0IjoxNzE1MzUyMzk4LCJleHAiOjMzMjg1OTEyMzk4fQ.-E5VRWi4ILbI4Pc-wOJcOrmejf8iISw2gu2X5CwSCmo "=604x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.49+
- Platform: app store
- Browser name and version: Brave
- Operating system and version affected: Mac
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] \~100% of the time
- [ ] \~50% of the time
- [ ] \~10% of the time
- [ ] \~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @cheungysophie! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by gspassky** [comment]
Having the same problem with some "getter" for Lottie widget ((( Maybe you solved it?

**Comment by gspassky** [comment]
Finally I figured out that this error occurs when you try to initiate animation from Actions Editor. I used Actions Editor to run animation with a delay, but it seems there is a bug in FF
