### ISSUE TITLE
Unable to Navigate Away from API Screen Using Keyboard Shortcuts

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#2882]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When on the API screen, it's not possible to navigate to other screens using keyboard shortcuts. This issue is unique to the API screen, as navigation with the keyboard combination (Tab + number keys) works fine on other screens.

### Expected Behavior

Users should be able to navigate to other screens using keyboard shortcuts like Tab + 1, Tab + 2, etc., while on the API screen.

### Steps to Reproduce

1. Open a FlutterFlow project.
2. Go to the API screen.
3. Try navigating to any other screen using keyboard shortcuts (e.g., Tab + 1, Tab + 2).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kz/Hqx89gocNG1qX6acFFmSQvKUA2a+Y0lu1hSRE0C4CsG7l/S8+kfhNuXbC0SlY3eWCahnEezN3emvHLCscrHy2bbJQ5/6luSgHKRk+mRpi1PKiWXW5/Dd5WfX6z1pm72RQkKrZtLyUT22WyG+yXUj/YNYDxOzA/Av6HC5OK2SrDX1iXc2URm05KZDPz

### Context

Keyboard shortcuts do not work when trying to navigate away from the API screen.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/222722d2-31cd-4f46-aa1a-187579b2f7a0

### Environment

```markdown
- FlutterFlow version: 4.1.49
- Platform:macOS
- Browser name and version: chrome and desktop
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @joekman990 thanks for your report. I can confirm that all of the tabs can navigate correctly except for the API one. Thanks for noticing it! I will send this to our technical team so they can fix it for our next release. Have a great day!
