### ISSUE TITLE
Google Sign In Not Working in Android Actual Devices

### ISSUE THREAD

**Issue by techbuild360inc** [FlutterFlow/flutterflow-issues#2884]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello Team, I'm encountering an unusual problem where the Google Sign In feature isn't functioning on actual Android devices, but it works fine on both the Emulator and Web. I've tried multiple times, and while it does display all the Google IDs, it fails to authenticate any selected email address. I've also checked the Firebase Authentication portal and found that the email address isn't listed. Could you please help me understand why this is happening?

### Expected Behavior

Google Sign In should work in actual Android devices.

### Steps to Reproduce

1. Open the App
2. Choose Google Sign In
3. It won't authenticate in actual mobile devices.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehcr635ZNtbxa7rrbK8FVowMxQUB+bZ0vlO1FGAwcIZCrPZYiO8nUaXdpZsead2xUJ2aWoz8GpqGMv4TuUPEpCEyBfa1607ViVwyVcEe7V6a3PKm0YnZCHeBVCFyg06TVkxVCNu5vS0IO7WGLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Sign in failure blocks the entire app.

### Visual documentation

First page of the app is the sign in page

### Environment

```markdown
- FlutterFlow version: 4.1.49+
- Platform: Android
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by crossxsecure** [comment]
Hello @FlutterFlowEng, could you please help here?

**Comment by ESomnio** [comment]
Hey @ltechbuild360inc,

Thanks for submitting the issue. We've taken a look at your report and the Google login is working fine. It is probably a problem with your SHA1 key. We suggest that you regenerate the SHA-1 key, build a new version, and then try again.

Let us know if the problem persists.

**Comment by techbuild360inc** [comment]
Hi @ESomnio, thank you for your response. I tried creating a release of the app in the playstore and then copied the SHA1 and SHA256 keys from the Google Play console and then updated it in Firebase Project followed by Regenerating the Config file again in FlutterFlow but still my Login with Google button isn't working even though I have generated a new service account and updated it in mobile deployment credentials set.

**Comment by paulperez-dev** [comment]
Hi @techbuild360inc! I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.<br><br>Can you please provide the bug report code from a blank project?
