### ISSUE TITLE
Imposible to set TextField Height

### ISSUE THREAD

**Issue by JonathanG1702** [FlutterFlow/flutterflow-issues#2888]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Today I noticed that I can't set TextField height. It looks like the option to set it literaly dissapeared...
I remember that was possible a time ago but today I notice i can't do it.
If Im crazy tell me and close the bug, but I think something happened

![Captura de pantalla 2024-05-10 201158](https://github.com/FlutterFlow/flutterflow-issues/assets/66635579/7f4acdbd-15d4-457a-a349-f46e23dc473d)

### Expected Behavior

Just being able to set TextField height

### Steps to Reproduce

1. Just add a TextField to something, in my case a column
2. Try to set height

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClPHqx5VIocdJ7q6JasEwqCkXQz85RYINiu5Dew4dJ5PNCJkQO8nTXFJWXf25dglcJWaWjXMK0+jXm9z1UuwqGxGBbrU5z89AejrjRkmhV5CsPqWofHFuGshQBXKiyrujsSV5HLJfc2QR2jiPeuusbAXrNrrNNm4nA8mLBL3XrgfuQ0SLb3kNh1JWeC/v

### Context

What I mentione above

### Visual documentation

![Captura de pantalla 2024-05-10 201158](https://github.com/FlutterFlow/flutterflow-issues/assets/66635579/cabc503e-47d7-4d19-8453-5f96a112dab3)

### Environment

```markdown
- FlutterFlow version:  v4.1.49+
- Platform: Web
- Browser name and version: Chrome, last one
- Operating system and version affected:  Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @JonathanG1702 thanks for your report. The Textfield will take the height it needs depending on how many lines it has and the height of its parent. If you want it to have certain height, you can wrap it on a container and give the container the desired height. <br>I'm really not aware of how it worked before. If you have some UI that you are not able to implement because of this, please make sure you contact our Customer support team for help. Have a great day!
