### ISSUE TITLE
Toggle Icon Won't Accept Boolean Values From Custom Datatype In App State

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#2892]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list of boolean values in a custom data type in an app state variable. I attempted to tie these variables to some toggle icons, but I get an error. 

### Expected Behavior

There should be no error when assigning a boolean value in app state to a toggle icon.

### Steps to Reproduce

1. Create New Page
2. Add a toggle icon to the page
3. Create a custom datatype with a boolean field
4. Add that custom datatype to an app state variable
5. Link that variable to the toggle icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gj8mAvYt2obhe1aqNde9anjgWQ3k7a4I7l9Z+RRQbGIzrOp13fuLOUFppXu6BawpcP1n8rHgKwfTVvoaSBMYCAxeWGbZg1pBbQx7jRkSQVLKhDau0eHMlJ/JYfVCM1qaRhAomBPhwd2wf3zqyCOm+fA3aQJD3OzMRAvGJBJ3XgXOkLiXzUids5yY+MUyZTI5ODEz25eKMrop5yfj/0w==

### Context

I'm unable to effectively organize a set of boolean values in my app state and use them in toggle icons. 

### Visual documentation

![booleanAppState1](https://github.com/FlutterFlow/flutterflow-issues/assets/47302626/975348c7-beb3-4702-8557-32f3eee7ef0a)
![booleanAppState2](https://github.com/FlutterFlow/flutterflow-issues/assets/47302626/a27ce44e-7d19-45ef-88a3-70ead729ba70)
![booleanAppState3](https://github.com/FlutterFlow/flutterflow-issues/assets/47302626/4959ebcb-f000-41f7-84fe-8b1debb4e00b)

### Environment

```markdown
- FlutterFlow version: 4.1.49
- Platform: Browser
- Browser name and version: Chrome, 124.0.06367.119
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @MartinLockheart! I'm closing this issue because it duplicates [https://github.com/FlutterFlow/flutterflow-issues/issues/2534](https://github.com/FlutterFlow/flutterflow-issues/issues/2534). Please, refer to the answer we gave there.

**Comment by MartinLockheart** [comment]
Hey there! I'm a bit confused as to how this duplicates that issue... the fields I'm using in the app state variable are explicitly boolean data types. They are not conditionals "if document exists". 

In your response on #2534, you simply said that the toggle icon was limited - but I'm using strictly boolean data, so what is the limitation if it's not supposed to take true/false from a basic field?

**Comment by MartinLockheart** [comment]
Maybe this is a duplicate of #2833?
