### ISSUE TITLE
Desktop and Web in Windows or Mac are very slow and unusable, if the app grow more slow

### ISSUE THREAD

**Issue by JaimeNuup** [FlutterFlow/flutterflow-issues#2894]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My application should have more than 200 pages but as  application grows they become slower, I have tested it on Web, windows and on a Mac flutterflow desktop resulting in the same slowness in the response up to one click

### Expected Behavior

The flutterflow web site and the desktop must support larger app projects

### Steps to Reproduce

1. Create 70 pages with audio and images assets and 20 actions every page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l8j6w5NOm99c+Kr2dvpaniAXHDI7U+YZiO5TYxA8J5zKB+wAYvf7P1FWTL2rTEFMJ2KGjn407PfqheDtKu03C0+sUapHyId6FjndUk2uVJTXO5CzfW1QTPNXC0izyJ+42xJ/NsxvL2dgw1+IftyRcBPDQZD1OTI/MfmbLdeK2SrDX1iXc2URm05KZDPz

### Context

I can't work on my project that slowly, and I won't be able to finish it in the planned time. And I'm afraid it will collapse as it continues to grow.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169478796/9abdf770-1b2b-4e09-9616-ab9880bcf42c)

### Environment

```markdown
- FlutterFlow version: 4.1.49+
- Platform: Windows, Web or Mac (Sodoma)
- Browser name and version: Chrome 124.0.6367.201 (Build oficial) (64 bits)
- Operating system and version affected: Windows 11 and Mac OS Sodoma
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [X] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [X] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Jhandos** [comment]
Same problem. After each action, flutterflow checks for errors. Which slows down the development of the application after each action. It would be good if it were possible to disable this check and if it was possible to enable this check with a separate button.

**Comment by JaimeNuup** [comment]
How are they going to close the bug if there is no analysis or solution to it? The problem persists and is easily replicable

**Comment by msusviela** [comment]
Hi @JaimeNuup. Our team is looking into the issue.

**Comment by sabatage3** [comment]
I’m having the same issue, web app or desktop app, flutterflow has become unusuble for medium-large projects, too slow

**Comment by ozanbilgili** [comment]
same issue still going on, FF v4.1.85

**Comment by rzambroni** [comment]
Hello everyone,

Apologies for the delayed response.

With the launch of FlutterFlow 5.0, we've implemented several improvements specifically aimed at enhancing performance for medium to large projects. While we recognize there’s always room to grow, especially as new features are introduced, we believe these updates have made a noticeable difference in usability and overall performance.

Given these improvements, I’ll be closing this issue for now, as our testing with various example projects indicates significantly better performance. If you’re still experiencing any issues, please feel free to open a new ticket with details based on the latest version, and we’ll be happy to take a look.

Thank you all for your valuable feedback!
