### ISSUE TITLE
List Contains does not identify integer

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#290]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Filtering a list of integers

## Current behavior (required)

Cannot select integer value
## To Reproduce (required)

1. Connect supabase
2. Create an array field of datatype int8 for a table
3. Map the data type in flutterflow
4. Query the table on list
5. Try to add a filter on the array field with list contains
6. Unable to select the integer

### Bug Report Code (required, generate from Widget Tree)

IT4Shcrqw5dgobRJ7s/+bMJVgio5KVAja7gvlOxAEA43IZj0P4oLXOnQTFRoO7zgYHNYI2GWhXIx7Pfqjd+WF+4qYBCbfos6+rpqTBbNXmqQM67REpaNMS0ffaMKRSz+

## Context (required)

Unable to filter in supabase

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Thanks for the bug report @SiraEnterprises! This will be fixed upon our next deploy 🙂
