### ISSUE TITLE
File Loading Issue in FlutterFlow Windows Version

### ISSUE THREAD

**Issue by gerquali** [FlutterFlow/flutterflow-issues#2902]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the FlutterFlow version for Windows, when trying to load a file, whether it's an image or an SQLite database, it keeps loading indefinitely without completing. On the web platform, it works.

### Expected Behavior

In the FlutterFlow version for Windows, when trying to load a file, whether it's an image or an SQLite database, it keeps loading indefinitely without completing. On the web platform, it works.

### Steps to Reproduce

Try to load a file or database in the desktop version

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

qualquer widget funcionará

### Context

carregar arquivo ou banco de dados SQLite

### Visual documentation

In the FlutterFlow version for Windows, when trying to load a file, whether it's an image or an SQLite database, it keeps loading indefinitely without completing. On the web platform, it works.

### Additional Info

In the FlutterFlow version for Windows, when trying to load a file, whether it's an image or an SQLite database, it keeps loading indefinitely without completing. On the web platform, it works.

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [X] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] \~100% of the time
- [ ] \~50% of the time
- [ ] \~10% of the time
- [ ] \~1% of the time
- [ ] Very rarely or only encountered once in

**Comment by paulperez-dev** [comment]
Hi @gerquali, I was able to reproduce the issue, I will send it to the ENG team so they can work on this! 

Thanks for your feedback!

**Comment by leighajarett** [comment]
Thanks for flagging this, we're working on this issue (which seems to be caused by a bug in FlutterFire package). We hope to have a fix out soon
