### ISSUE TITLE
flutterflow version out of date

### ISSUE THREAD

**Issue by dlalancette** [FlutterFlow/flutterflow-issues#2903]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't use the desktop app. I am always ask to download most recent

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5972176/a9b28ff8-64b0-464d-9e13-3a199230219b)

### Expected Behavior

I would be able to open the app and test my flutter app

### Steps to Reproduce

1. Open the  desktop app
2. Create a new project in the desktop app
3. Got to the web version because the desktop app not working weel to add api- Add a API call
4. Return to the app
5. Get the message : flutterflow version out of date you are on an older version of flutterflow than the most recently edited version of this project please refresh the page to use the latest version

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not related to a widget

### Context

I can't use the windows app so I can't test on my android device

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5972176/e3e2c4a7-595e-4c87-9533-6a86ce9a111d)

### Additional Info

I've tried to reinstall the application - No result
I've tried to update the application - No result
I've restart my computer

### Environment

```markdown
- FlutterFlow version: 4.1.49
- Platform: Desktop app 
- Browser name and version: Google Chrome 124.0.6367.202
- Operating system and version affected: Window 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by leighajarett** [comment]
Hi there! Can you please let me know what version of macOS and web you see? Top left hand corner. 

Have you tried downloading the latest version? Sometimes auto-update is delayed on macOS (it's outside of our control) so you may need to manually redownload the latest version (+ remove the old app)

**Comment by dlalancette** [comment]
Hi!

I am not on macos and I don't have one. Like I said on Window 11. I tried to time with the latest install on the Flutterflow website
________________________________
De : Leigha Jarett ***@***.***>
Envoyé : 13 mai 2024 20:11
À : FlutterFlow/flutterflow-issues ***@***.***>
Cc : dlalancette ***@***.***>; Author ***@***.***>
Objet : Re: [FlutterFlow/flutterflow-issues] flutterflow version out of date (Issue #2903)


Hi there! Can you please let me know what version of macOS and web you see? Top left hand corner.

Have you tried downloading the latest version? Sometimes auto-update is delayed on macOS (it's outside of our control) so you may need to manually redownload the latest version (+ remove the old app)

**Comment by leighajarett** [comment]
Is the FlutterFlow version you provided the version on Windows or web?

**Comment by dlalancette** [comment]
Window

My web version is : 4.1.52

Dany Lalancette Guay
***@***.******@***.***>
________________________________
De : Leigha Jarett ***@***.***>
Envoyé : 13 mai 2024 20:16
À : FlutterFlow/flutterflow-issues ***@***.***>
Cc : dlalancette ***@***.***>; Author ***@***.***>
Objet : Re: [FlutterFlow/flutterflow-issues] flutterflow version out of date (Issue #2903)


Is the FlutterFlow version you provided the version on Windows or web?

**Comment by leighajarett** [comment]
Thanks for confirming, looking into it!

**Comment by leighajarett** [comment]
4.1.52 is the latest version, both web and desktop should be on the latest version. Can you please do a hard refresh on your browser?

**Comment by leighajarett** [comment]
Oh sorry I misread, I thought they meant web was 4.1.49. Thanks!

**Comment by leighajarett** [comment]
There may be a delay in auto-update on Windows. I tried manually downloading the windows app and it does should 4.1.52 - can you please try uninstalling and installing again?

**Comment by leighajarett** [comment]
Checking on iPad

**Comment by leighajarett** [comment]
Okay confirmed iPad is behind, so sorry about that! We are deploying a new update now and it should be available soon!

**Comment by GuglexLab** [comment]
@dlalancette, has the issue been solved, I am facing the same issue.

**Comment by dlalancette** [comment]
No problem since I got a new update on the desktop app

Dany Lalancette Guay
***@***.******@***.***>
________________________________
De : Guglex Technologies ***@***.***>
Envoyé : 15 mai 2024 17:41
À : FlutterFlow/flutterflow-issues ***@***.***>
Cc : dlalancette ***@***.***>; Mention ***@***.***>
Objet : Re: [FlutterFlow/flutterflow-issues] flutterflow version out of date (Issue #2903)


@dlalancette<https://github.com/dlalancette>, has the issue been solved, I am facing the same issue.

**Comment by btusca** [comment]
has the issue been solved? I am facing the same issue rn
