### ISSUE TITLE
 Firestore Data Manager not fuctioning properly

### ISSUE THREAD

**Issue by MemoriaM1** [FlutterFlow/flutterflow-issues#2904]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The circle just keep on turning and turning and no content and showing
![Screenshot 2024-05-13 193044](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/e97e1e74-1ffe-406a-85ed-abba6c6b2a41)

### Expected Behavior

should be showing all the data content

### Steps to Reproduce

go to firestore
manage content
3.and the firestore data manager pop up
the circle keep on spinning and no content showing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/HluIlPm+FY+KqIbflWlSkRQ1h6TLJEoetxc0gbfe/4PLQPPuCkaRZoZOKzaH9AJWGIkj4F0MGNj/HTCOwnNQesf4c6+ZBIVBPPbEeiaKqRDcySOWgkL8BXJhW60Z2noglRAMhsWl4C6meQCN6RHj6Cf9qOYwx5e6fDbOY=

### Context

I can't continue inputting the necessary data to run the app

### Visual documentation

![Screenshot 2024-05-13 204702](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/b5e8f258-2a2f-4cd2-92f2-e689fb42b1d4)

### Environment

```markdown
- FlutterFlow version: 4.1.49
- Platform: Web
- Browser name and version: Chrome 124.0.6367.157
- Operating system and version affected: none
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @MemoriaM1 thanks for your report. I can confirm that the Firebase Data Manager is working properly, so this must be a specific issue with your project. By the images you provided, I can see that it's not loading on Firebase console either. Could you confirm if that's the case?

**Comment by MemoriaM1** [comment]
I am not sure, can this be contribute by the coding within the data? or it is cause by data overload?

**Comment by MemoriaM1** [comment]
Hi yes, I can confirm now this is the case. I didn't fully know what you mean that time
![Screenshot 2024-05-20 160140](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/6e17f46b-837a-421d-992e-2735166c6ccc)

**Comment by ignalauret** [comment]
I'm sorry about this. Sadly it seams like an issue with Firestore, not with FlutterFlow. If you created the Firestore using the FlutterFlow Firebase Setup wizard let me know so I can submit a bug report for the Wizard. But now that it's already created, the bug is on Firestore. Could you please try creating a new firebase project and connecting it to your FF project? Sadly there is nothing I can do now since I'm not on the Firebase support.
