### ISSUE TITLE
Apply same duration & delay not working

### ISSUE THREAD

**Issue by JanikHalder** [FlutterFlow/flutterflow-issues#2906]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If i set the duration and delay using apply same duration & delay it still use the values set for each animation.

### Expected Behavior

Apply same duration & delay should overwrite the values.

### Steps to Reproduce

1.) Create an Animation with two animations (for example Scale & Fade)
2.) Select Apply same duration & delay
3.) Set the times to different values.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WivLq285PmM9Y15DLbcIwiikRQ1w6U5IrkcN9RREbB4yoE5wPXPykP1doTcOiTFZYMFv8mnkxp83GvvDpE+QHA0mAc60+ybpcTg2XbDi5Sr6RPs+SY3FtL/5WJEuV15+JvxNvNvdpSX9m2WeqC/CiRXbYJ7LpOlgzHf2aFKPPng+gAhm6Xn0Jg1ZSfCvr

### Context

Try to use two animations on the same widget with the same duration and delay.

### Visual documentation

<img width="280" alt="Bildschirmfoto 2024-05-14 um 17 13 07" src="https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/2a31c98e-0a27-4564-8576-4fc02497124b">

### Environment

```markdown
- FlutterFlow version: 4.1.52
- Platform: macOS Desktop
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @JanikHalder thanks for your report. I can confirm that if you follow your steps (first changing the animation times to different values), you are still seeing the animations with the values you set first after clicking on Preview. I will send this to our technical team and they will keep you updated on this thread. Have a great day!

**Comment by harrisonpinchieri** [comment]
Same here

**Comment by harrisonpinchieri** [comment]
The delay duration of the animation is not working, maybe is something with this bug resolution?

**Comment by mmearly** [comment]
Hi @JanikHalder! Sorry this got marked as not planned, that's a bug with our issue tracker. The fix for this has actually been implemented and will be included in the next release! Sorry for the delays and confusion.
