### ISSUE TITLE
Content not displayed on test session

### ISSUE THREAD

**Issue by kesioo84** [FlutterFlow/flutterflow-issues#2908]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Text content is not displayed in the test session but it is displayed in preview mode.

### Expected Behavior

Text content should be visible in any environment

### Steps to Reproduce

Simply enter a test session.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gosNY1bXubMBqhQIgQ0QnU7gnlO1ucx4YNZDwEZk+P/T8T0NKT/bmfW59M1aWikAe0fzJuNrmUMcCYDeYb6o50JVAexfwRkK7VJCOO7izPnAlJ9hNGHaO0qu02CNBOrNfSEI/7VOtNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I cannot test my application as the text required to properly visualize progress and interact with the application

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169833426/27d66603-f6d7-4923-9e2a-bda2d2cd84ea)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169833426/15a49d93-7313-4506-8570-cd1dd50355a6)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169833426/c1087a5a-6dd4-46f7-b170-65b5a60b29ac)

### Environment

```markdown
- FlutterFlow version: Flutter version is 3.19.1
- Platform: FlutterFlow v4.1.52+ released May 14, 2024
- Browser name and version: Brave, Safari or Chrom
- Operating system and version affected:  MacOS Sonoma 14.4.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @kesioo84 thanks for your report. I can see that you are having the same issue that this user had: <br>[https://github.com/FlutterFlow/flutterflow-issues/issues/2291](https://github.com/FlutterFlow/flutterflow-issues/issues/2291)<br>So please check the solution there, adding the translations for english that I can see that you are also missing. Closing this as duplicate, have a great day!
