### ISSUE TITLE
Checkbox is not working within a Supabase Query

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#291]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I should be able to check the widget

## Current behavior (required)

As soon as I click on a checkbox it becomes uncheck

## To Reproduce (required)

1. Create a column a do a Supabase Query
2. Add Checkbox or CheckboxListTile
3. Click on them and automatically is uncheck

### Bug Report Code (required, generate from Widget Tree)

ITESz/Hqx89gobUD0LXhKPlQhQokQ2IjUOcJi+0aSTUYF5SuCJkqfPfAP1FWXbSkdAliME2mp14epdLnvdnTU/c5A0+rRqpJ+ZYJdwmXWmehMZPfU/HUACkbeacOQSj6

## Context (required)

I want to check some users

## Your environment

* Version of FlutterFlow used: 26 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by agreaves** [comment]
Thanks for catching this as well @Franco98404! To get into the details, this is because we have not implemented `hashCode` for Supabase rows, which means we can't use them as keys in a Map. We've added an implementation of this so that it's fixed in the next release!
