### ISSUE TITLE
Wall post function not working

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2910]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to write a wall post, it doesn't come through. I've been working with support on this for 2.5 weeks and we still haven't been able to resolve it. Could you please help look into this?

### Expected Behavior

When an the "authenticated user" tries to write on a "users" wall that post then appears on the "users" wall

### Steps to Reproduce

1. Log in as a user username: flutterflow@gmail.com, password: flutterflow2024
2. Search for another user by going to the ForJew Page and then clicking the magnifying glass icon at the bottom
3. Click on a users profile
4. Write a wall post

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCgofePtOol3evWkaVpDXu3jY3x6f0SmmXMypMmOitj1A8YrPQmbG91x/qp2WzvwZzuie5OBPKW0OWpCEcZMCWam37W3qx1+WdNhWlon2DiEGO/KVnftO5zVImdISq/LZO4=

### Context

Has held me back for publishing my app for a few weeks

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/5e0acd94-8e72-4f67-8da4-1194813ae864

### Environment

```markdown
- FlutterFlow version: 4.1.52
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @lovestar18 thanks for your report. Sadly we can't help you with this kind of description here, this would be more for the Customer Support team. <br>I did a quick check of your project and everything looks to be correctly configured on the Post button. This sounds more like a Firebase misconfiguration that you are having. Could you please try to run this on the Web and check the console logs and network tab to see if you are getting any errors? <br>Sadly without an error message or a Blank project where you are able to replicate the issue, I can't help you.<br>Let me know if you are able to get any of those, have a great day!

**Comment by lovestar18** [comment]
Thank you very much @ignalauret ! I did run this on the web and I am getting a console error - please see below and let me know if I can provide any additional information


https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/6cef93ce-7df9-4bbf-b4c5-70c8601abbfe

<img width="532" alt="Screenshot 2024-05-15 at 11 18 04 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/a24a3614-34aa-47bd-addd-7328ae74c7f9">

**Comment by lovestar18** [comment]
@ignalauret - I did remove the buildship API to see if that would help, however; I'm still seeing errors / it's not working. Do you have any ideas on what I could do to fix this? thank you!

<img width="1269" alt="Screenshot 2024-05-16 at 8 11 38 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/4faca0c6-8d77-419f-b7bc-665a03e4890e">
<img width="545" alt="Screenshot 2024-05-16 at 8 11 55 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/ff7f04b5-3718-4442-88f0-ed06d4b2b20e">

**Comment by lovestar18** [comment]
Hi @ignalauret - this is now resolved. I do have one question I was hoping you might be able to help with.

The 'wall post' is currently set to have the handle / username and profile photo from the user document; however this does not pull the 'wall post' author's username and photo.

I've tried adding the author_handle and author_photo to the 'wall post' collection but am having trouble tying it back to the author of the wall post - do you have any advice here?

Thank you!

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/b65cf314-f7c1-47ac-8d41-b8eaaa1a6c1d

**Comment by lovestar18** [comment]
Figured it out - thank you for your help @ignalauret !
