### ISSUE TITLE
List View end spacing is not working with responsive values

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2914]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

End spacing is not working with responsive values

### Expected Behavior

End spacing should be changed dynamically depending for responsive values

### Steps to Reproduce

1. Add a list view
2. Go to end spacing and set the conditional values depending on the responding values
3. Go to a test and now you see that this doesn't work.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glsjf35dNxc9G1aqNKe9avCEvKVg6Rpc0sNtuTQIdCYDuBIYiac/BUE5WQuLiTHNtKEWKrEYdpq3nvobLF/A7FASVY6ZqwZdcewGWWl2/aoSJO7W7dmh6OJhRJn6y0qS3nBF/Os5tSVlk2kyULvCWVgDUCbX4Zwh9f6PHaOI=

### Context

I have an app that has a floating nav bar and I use a list view so I need to add end spacing to see properly all the items from the list view on mobile

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/c020ed46-e78f-47b9-8e7c-f88fd40dd1d2)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/e8ff1e71-7c2a-4551-8037-84c9623fb2c0)

### Environment

```markdown
- FlutterFlow version: FlutterFlow V4.1.52+ released May 14, 2024
- Platform: Web
- Browser name and version: Version 124.0.6367.202 (Official Build) (64-bit)
- Operating system and version affected: W11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @Franco98404! Thanks for the report. I was able to reproduce the issue, I will send this to the ENG team so the can take a look at this!

**Comment by Franco98404** [comment]
> Hi @Franco98404! Thanks for the report. I was able to reproduce the issue, I will send this to the ENG team so the can take a look at this! 

Thanks! I forgot to mention it, but I didn't investigate the root cause, it may be the response values, item spacing, list view, etc. I only replicated the problem and did not do in-depth research

**Comment by paulperez-dev** [comment]
Hi @Franco98404! Can you please try to reproduce the issue again? I can't replicate it in the latest version.

**Comment by Franco98404** [comment]
> Hi @Franco98404! Can you please try to reproduce the issue again? I can't replicate it in the latest version.

Hello @paulperez-dev  and @leighajarett, sorry for the delay, but I just tried and the same problem still exists :(

**Comment by Franco98404** [comment]
I just checked and it's fixed!

**Comment by paulperez-dev** [comment]
Thanks for the confirmation!
