### ISSUE TITLE
Failed publishing Android with CodeMagic

### ISSUE THREAD

**Issue by faustofonseca** [FlutterFlow/flutterflow-issues#2915]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to publish Android in the FF's settings (Codemagic) I'm always getting the error "Version code 2 has already been used". But I have version code +30 in my pubspec.yaml. I use github for the deployment. And I didn't change the Android's build.gradle, so it still gets it from the "flutter.versionCode" property. Where is it taking that 2? I ended up configuring my local repo to build locally and everything works as expected.

### Expected Behavior

I expect it to use the version code I put in my pubspec.yaml

### Steps to Reproduce

Publish to Android using the publishing in settings (Codemagic).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/1sIZNodtK+KnybPlVijoXCUMdXOczitVEew4bCIj4B4YlP+P8QFVVcMizaH1qGVn+gkIJ+PDsuPL2FcBcNSSWQIBI1qgBYBPPbDqiMKaTPqqJOXZQRZlXCFCj56bUpB1COuNuLyEB2zu2f+usRT6Cf9qOYwx5e6fDbOY=

### Context

I'm simply trying to publish to the play store without having to do it manually.

### Visual documentation

![bug3](https://github.com/FlutterFlow/flutterflow-issues/assets/47268546/599f5d2d-8a23-4bda-8a72-19ac85f3766e)
![bug2](https://github.com/FlutterFlow/flutterflow-issues/assets/47268546/fec62f8d-0982-47b9-9dee-3efee438709f)
![bug1](https://github.com/FlutterFlow/flutterflow-issues/assets/47268546/385e1242-83a9-4648-b8cf-3f1843f6dec8)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.52+ released May 13, 2024 Flutter version is 3.19.1
- Platform: Mac
- Browser name and version: Opera One(version: 109.0.5097.80) (arm64)
- Operating system and version affected: MacOS Sonoma 14.1.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @faustofonseca! The Bug Report Code you shared seems to be from a different project. Can you please verify?<br><br>Also, notice that the `buildNumber` is taken from the `/android/local.properties` file.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by faustofonseca** [comment]
Hello Paul.

Thank you so much for your response. I lost these notifications in my
emails for some reason.
I will create today a new github issue and try to see what was the issue
about the report code.

Thank you.

Fausto Fonseca
***@***.***
http://www.faustofonseca.com
