### ISSUE TITLE
Supabase Google Authentication

### ISSUE THREAD

**Issue by chances** [FlutterFlow/flutterflow-issues#2916]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
  - See also [https://github.com/FlutterFlow/flutterflow-issues/issues/2297](https://github.com/FlutterFlow/flutterflow-issues/issues/2297)
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no setting to "Enable Google Authentication", even though your [documentation claims to support it](https://docs.flutterflow.io:8443/data-and-backend/supabase/supabase-authentication/google-sign-in-supabase#id-3.-enable-google-auth-in-flutterflow).

(You have also exposed client secrets in your video documentation.)

### Expected Behavior

I expect to see a "Supabase Authentication" section in the Authentication settings:

![Untitled](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a7950dff-56dc-4807-a565-30f28f671700/ee33e121-1fab-455f-a678-76bd47549835?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNzk1MGRmZi01NmRjLTQ4MDctYTU2NS0zMGYyOGY2NzE3MDAvZWUzM2UxMjEtMWZhYi00NTVmLWE2NzgtNzZiZDQ3NTQ5ODM1IiwiaWF0IjoxNzE1ODMyMzMxLCJleHAiOjMzMjg2MzkyMzMxfQ.HMWxGCC0zjZBanBTC1Jachqs9mwHHuDWkJipHXsRFBg "=1439x")

### Steps to Reproduce

1. Create and configure a Google Cloud project.
2. Configure Google auth in Supabase.
3. In FlutterFlow, navigate to Setting and Integrations > App Settings > Authentication.
4. Observe there is no Supabase Authentication section.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slcr1sIZ2pbxa1br+YMdB/SARQmV/U4JNscpCbw4bIYj2P4lzY876PxRDQsOoS29DPlqcp14KwfDUhoTAVsArGw2cfaE5z856cgLKXkGlb4uTF7qCRkBRL8VUJ0yY38KzhyYkPvttWmAZ2Ez3e+fLSnfZNbrACkQ8Sq/LZO4=

### Context

I am trying to enable an authentication flow to log in a user via the Supabase Google Authentication integration.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7a8cf06a-e4e9-46b1-bb72-1f1c12159c32/a83a1e0e-d1d7-4595-aa58-358499bbdcb4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YThjZjA2YS1lNGU5LTQ2YjEtYmI3Mi0xZjFjMTIxNTljMzIvYTgzYTFlMGUtZDFkNy00NTk1LWFhNTgtMzU4NDk5YmJkY2I0IiwiaWF0IjoxNzE1ODMyMzMxLCJleHAiOjMzMjg2MzkyMzMxfQ.YC6vPO_Wbz5-kS32ri72jZ-Mov4nxIoIwtW-R1DivE8)

### Environment

```markdown
- FlutterFlow version: 4.1.52+
- Platform: MacBook Pro, 13-inch, 2017
- Browser name and version: Google Chrome Version 124.0.6367.62 (Official Build) (x86_64)
- Operating system and version affected: mac OS 13.6.6 (22G630)
```

**Comment by paulperez-dev** [comment]
Hi @chances! I was taking a look to your project and it seems that the [initial setup](https://docs.flutterflow.io/data-and-backend/supabase/supabase-authentication/initial-setup) of Supabase was not completed.

Can you please review it?

**Comment by chances** [comment]
@paulperez-dev That seemed to resolve my immediate issue.

Can you clarify how FlutterFlow's Supabase/Google Auth integration modifies the public schema user table?

**Comment by paulperez-dev** [comment]
@chances Glad to hear that!

I'm not part of the ENG team, but I guess that because you need to introduce the API URL and the Key, FF can modify the schema.

**Comment by chances** [comment]
@paulperez-dev Please update the docs to clarify why FlutterFlow requires a user table and what, if anything, the Supabase/Google Auth integration modifies in the Supabase public user table.
