### ISSUE TITLE
Options missing for supabase

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#292]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Update Row - For the action update row, there should be an option to update increment/decrement values for supabase
Row Exists - For the conditional action, there should be an option of "Row Exists" for Supabase
Add to List, Remove from List - For the data type array in supabase which is mapped as a <list>, these options are not available. 

## Current behavior (required)

Update Row - For the action update row, there are only two options available - "Specific Value" or "From Variable". "Update Increment/Decrement" option is missing
Row Exists - For the conditional action, there is no option of "row exists" for supabase
Add to List, Remove from List - For the data type array in supabase which is mapped as a <list>, these options are not available. 

## To Reproduce (required)

1. Connect Supabase
2. Connect Supabase Query with a list datatype and int/float datatype.

Update Row - Try to update int or float columns. Update Increment/Decrement is missing
Row Exists - Check the fields of connected supabase query. Row exists is missing. 
Add to List, Remove from List  - Try to add or remove some value from the list field

### Bug Report Code (required, generate from Widget Tree)

IT40hcrqw5dgobRJ7s/+bMJVgio5JmY/ULsoletRaCgoIYyuOpl/evXsak9uOM/nYFZle0SmmToK3NmMktnpIPACFzGuftlk/7gMEzrdczqhU8HfU/HUACkbeacOQSj6

## Context (required)

I have to figure out a different way which results in too many actions, resulting in low load page speed

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @SiraEnterprises, thank you for the feedback! I'm marking this as a "Feature Request" and closing as this issue tracker is purely for bug reports at the moment, but I'll address each of your ideas below. The high level summary is that some of these are simply not available for Supabase.

Update Row - Increment/Decrement does not exist out of the box for Supabase, see [this issue](https://github.com/supabase/supabase/discussions/909#discussioncomment-546117) which provides a (somewhat involved) solution.
**Row Exists** - This is a great idea and we can add it. However, this is also equivalent to the Condition if you select the Row and then use the condition "Exists and Is Not Empty"
Add to List, Remove from List - This operation does not exist in Supabase either out of the box.

Hope this helps, thank you for the feedback!
