### ISSUE TITLE
Infinite scroll doesn't update when variables change

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#2920]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Infinite scroll doesn't update when variables change

### Expected Behavior

The API call should work as if infinite scrolling is disabled, it should be update when the variables change

### Steps to Reproduce

1. Create an API call and set a variable to use as a search.
2. Add a text field
3. Create a list view and use the API call created previously
4. Do a test and you can see that it works. (The red screen can be ignored, it does not affect this issue)
5. Activate infinite scrolling
6. Refresh the test and it doesn't work, it just makes the initial call

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kj8nf049Om+EA7q6JY/oxhiYXNnI/a7geluphbwwgfL7nG7YAQszOSBJaZ+m+Sgo3P1n9gnod/t7Mv/bIN/EqYD+VR4Baz7piWBXgZD65RcWODc6SXXFBEtpKCnbG4YmskB5vCMlpdFoO1Fz3GPOvUhHbCYTPNVYaDvykOoTUs3fuQ0SLb3kNh1JWeC/v

### Context

I want to use a textField to search and have infinite scrolling enabled

### Visual documentation

https://www.loom.com/share/938504a233d14f29ac47987adc0aad23

### Environment

```markdown
- FlutterFlow version: FlutterFlow V4.1.52+ released May 14, 2024
- Platform: Web
- Browser name and version: Version 124.0.6367.202 (Official Build) (64-bit)
- Operating system and version affected: W11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @Franco98404 thanks for your report. Remember that the Infinite scroll doesn't work on it's own. It gives you the appropriate variables (for example "Number of Loaded Items") that are useful to implement your own pagination. You then add the pagination variables to your Backend Call (for example skip, or page and page_limit) and you implement your Pagination. <br>Hope this was useful. If you need any more help, please feel free to contact our Customer Support to get assistance on implementing you pagination. <br>Closing this issue because this is doesn't look like a bug on FF. If you still think there is a bug here, please let me know. <br>Have a great day!

**Comment by Franco98404** [comment]
Hi @ignalauret! I know the infinite scroll doesn't work on its own, to make it simple and easy to replicate I did that. A real case is this:
https://www.loom.com/share/4b8f310e3be645919f23dd27d0fcc5f5

In this case I use custom code and the API already has the headers ready for pagination but I did not want to show it when reporting this bug because it was going to make it complex, but there you can clearly see the problem. I hope this helps!

**Comment by ignalauret** [comment]
Hey @franco98404 I'm sorry for the late response. Were you able to make the infinite scroll work with the new versions of FF, or would you need me to review it again?

**Comment by Franco98404** [comment]
Hi @ignalauret I just checked and the error persists :(
