### ISSUE TITLE
Accessing FFAppConstants from within Team API call no longer works

### ISSUE THREAD

**Issue by bbeckford** [FlutterFlow/flutterflow-issues#2922]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using a reference to `FFAppConstants` in the "API Base URL" of a Team API Group, for example: `${FFAppConstants.SystemEndpoint}/api/whatever`, no longer substitutes in the `FFAppConstants` value.

Looking at the generated code it seems the dollar sign is now escaped (eg `'\${FFAppConstants.SystemEndpoint}/api/whatever'`

### Expected Behavior

Referencing `FFAppConstants` in this way has worked for months, my project is now completely broken unless I hardcode the system endpoint into the Team API - this makes Team API calls dramatically less useful.

### Steps to Reproduce

1. Create a Team API call
2. Attempt to use a constant `${FFAppConstants.SystemEndpoint}/api/whatever` in the API Base URL
3. Import and use the Team API Call in a project
4. Observe that in the generated code the `FFAppConstants` reference is now escaped

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kicnf349OsfpE7aqNcu9VhikvJj86UIJJltVuTU40NZjzG7YAQszOSBJaZ+m+Sgo2ek38knMzzNLRuObIN8A6G06Ac7piyLoIEBbJRnqmRpuVBpeaSXNfINpKCn6d1KuRmwomIbZuc2Q721+AO+qXQh3cQ77BNWwdQ8mkUbzXjXfuQ0SLb3kNh1JWeC/v

### Context

I have 3 different team APIs in use across multiple apps. I now need to go into all 3 Team APIs and change the endpoints every time I want to update an app - this makes Team APIs MUCH less useful.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2021072/2e5d2c5d-7a05-48e4-9702-49688aff6229)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2021072/c53ce8eb-e210-41c3-8e59-35adcd067b94)

### Additional Info

This along with [my other issue report](https://github.com/FlutterFlow/flutterflow-issues/issues/2695) (which has been inexplicably closed) regarding API Interceptors being forgotten about on Team APIs really makes the whole Team API feature in FlutterFlow feel like a second class citizen.

If you want businesses such as mine to use FF at scale, you need to prioritise features that help us maintain multiple apps. This kind of thing honestly makes me want to stop using FF, which would be a real shame as it has so much potential.

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Chrome Version 124.0.6367.60 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 23.10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by syg-eliseu** [comment]
We also started to experience this and I still haven't found a way around it. I use AppStates to define the values of the api group url, based on the environment the user is accessing: Development, Staging and Production. With the latest update, our app is no longer able to manage these environments.

**Comment by sharmilaccd** [comment]
We also started experiencing the same..... For several months, I have been successfully referencing FFAppConstants within Team API calls in my FlutterFlow project. Recently, this functionality has stopped working, causing my project to break unless I hardcode the system endpoint into the Team API. This change significantly reduces the flexibility and utility of Team API calls. 

Restoring the ability to reference FFAppConstants within Team API calls is crucial for maintaining the flexibility and manageability of projects that rely on this feature.

Awaiting for prompt attention to this issue.

**Comment by microprocessltda** [comment]
Same here with the AppStates too

**Comment by syg-eliseu** [comment]
@leighajarett You did not understand. There was no implementation for this but we found a method to use.

In the API Base URL field, instead of typing a definitive value like: "api.test.com" we used the value of an AppState like this: ${FFAppState().[variable name]}.

This way it was possible to use the dynamic value of AppStates in requests.

The problem is that in the latest updates you are forcing String for text input in the API settings.

Our request is that you remove this forcing of String in the API URL input field so that we can use AppStates and Constants as we always did.

Example of how we used it and it worked well:

![Captura de Tela 2024-05-22 às 14 21 44](https://github.com/FlutterFlow/flutterflow-issues/assets/88388127/8d6c3ec0-5560-46bb-8400-beae166e640a)

**Comment by marcosbarreto** [comment]
This is a feature very important and should works too on tab **"Response & Test"**
I whould like define my url in a AppState or AppConstants
Put ${FFAppState.MyUrlBaseState} or ${FFAppConstants.MyUrlBaseState} in API group or API call
this need works im run or teste mode and on API  **"Response & Test"** tab

**Comment by bbeckford** [comment]
For those searching, FF have now solved this via Group variables with square brackets, eg: [SystemEndpoint]/api/

![image](https://github.com/user-attachments/assets/041d3e23-ddb3-480f-98a6-441e6615c25f)


![image](https://github.com/user-attachments/assets/c25620c3-159d-40c7-b793-cb097ccda6ce)
