### ISSUE TITLE
Remote Config - "JSON" Type Is Missing

### ISSUE THREAD

**Issue by Lalimec** [FlutterFlow/flutterflow-issues#2924]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cant seem to find the json type whey i try to create a new parameter, instead there is "double". Here is a comunity post someone created about it 2 months ago https://community.flutterflow.io/ask-the-community/post/json-datatype-for-remote-config-oRoW1pAmkvSRMLH 

### Expected Behavior

There should be a json type instead of a double.

### Steps to Reproduce

Go to firebase settings and activate remote config. Then try to add a json parameter.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl+fl4otIsdtK0L6Jafoxq2EsKU8cTIMziNZ+exUbfaL1BqQUfc74V1hpQt+laVNcP2GjsHkB/8GKk+OWMfpfAz+BGrk/zJN+EAzee2i5aJuYDpG0SGhSEf1jGnKy4KaFnSZQD7ducWRi7FOMf9y9QgnDFOu/Zwh9f6PHaOI=

### Context

Just trying to add a json remote config to control content in the app.

### Visual documentation

![ss-240517231818](https://github.com/FlutterFlow/flutterflow-issues/assets/65521426/6ad45021-32aa-4092-bf0f-204ec0f73e8d)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.53+ released May 14, 2024
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @Lalimec, thanks for reporting this issue! I was able to replicate it. I will send this to the ENG team so they can work in this.

**Comment by Lalimec** [comment]
Turns out it was due to firebase not providing a get method for json type. I ve learned that it has to be handled by a custom function, but it would be nice to solve it in the ui.

**Comment by paulperez-dev** [comment]
@Lalimec thanks for the extra information. This tracker is only used for reproducible bugs, so I am closing this issue.

I will talk to the team and ask if this is possible.

**Comment by Lalimec** [comment]
I mean i didnt wrote it yet but i was gonna follow this article https://medium.com/@bhavesh.sachala/firebase-remote-config-in-flutter-app-with-json-b4217afcbcad . And im not a developer so it might take a while. A simpler version could be just passing the encoded json as a sting and parsing it as a json i guess. which is like a single line of code.
