### ISSUE TITLE
Duplicated API calls

### ISSUE THREAD

**Issue by MHorley** [FlutterFlow/flutterflow-issues#2927]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

API call to BuildShip is being sent 2/3/4 times within 15-20 seconds.

Testing in BS works as expected every time.
Testing in FF Response & Test screen works as expected every time.

When testing using FF TestMode or the Web Publish (safari and chrome browsers on mobile) it creates the 2-4 calls.

### Expected Behavior

A single API call from wherever sent.

### Steps to Reproduce

Not sure how to recreate.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lPLq4otOxdsA7qXxbfpajic5KWIhbYIVi9Z7aCosfZT2BLMcec/RVERBYMund1FUPk6kmWoW0N3HjeHXJcErNTKAbY871sxuVQuWfGWuRbawFJWgdkZ7I+ZYN3aO5p23sRBQIbZtW3wO3WGMGO/KXnHcQpj0C1UWDa/LZO4=

### Context

It has stopped my development in its tracks.

### Visual documentation

<img width="1128" alt="Screen Shot 2024-05-18 at 07 31 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/170160553/cb3601d6-080a-482d-88bf-e5d33338c506">

### Additional Info

I duplicated the project to test features. I then renamed both projects, effectively swapping the names them over. I think this has created some crossover in your severs. The reason I say this is because I decided to delete these incase this was the error. So when deleting "ProjectNamebackup" it deleted my assets from "ProjectName" and I had to reload, so there is obviously some kind of link somewhere when projects are duplicated.

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Web
- Browser name and version: Version 125.0.6422.60 (Official Build) (x86_64)
- Operating system and version affected: ??
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @MHorley thanks for your report. I understand that you are getting a correct execution from the API Test, and then on your implementation it's being called multiple times. Could you please share with me some steps to reproduce from a blank project how are you calling this API call? So I can replicate the behaviour that you are getting and better understand what's going on.

**Comment by ignalauret** [comment]
We haven't heard from you so I'm closing this issue. I hope you have been able to fix it already. If not, please feel free to open a new one, have a great day!
