### ISSUE TITLE
Passing parameters doesn't work for supabase

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#293]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Pass a supabase row from one page to another 

## Current behavior (required)

Gray Screen
## To Reproduce (required)

1. Connect supabase
2. Connect supabase query 
3. Set the parameter on the landing page as supabase row
4. Pass the parameter as supabase row while navigating to landing page
5. Use the passed parameter to set a value on the page

### Bug Report Code (required, generate from Widget Tree)

IT40hcrqw5dgobRJ7s/+bMJVgio5JmY/ULsoletRaCgofePtOol3evWkUFJBTd+4Y1FqJ0SmmT8GwNWMjeP1V/ZdZCmCf4hcwboBagzNRnymdcHfU/HUACkbeacOQSj6

## Context (required)

Unable to retrieve information on the page

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @SiraEnterprises, what page / widget does this occur on? Perhaps you're not actually passing the Row into the page, and when the page tries to access the value the row is null.

Would it be possible to also show a screenshot of the error in action? Thanks.

**Comment by SiraEnterprises** [comment]
https://www.loom.com/share/6854ff0d4eeb44b39fd1ba8cb03b985c

Created a video here on how I am passing the row and what error I am getting.

**Comment by agreaves** [comment]
Hi, thanks a lot for this. But can you show me the full error from when you are on the "Products" page and navigate to the "Product Details" page? This should give me some insight. You may want to start a fresh run (new debug session). Thanks!

**Comment by SiraEnterprises** [comment]
https://www.loom.com/share/70ff50417d4447719e19e786f57a24fe

HYG...I explained as well why I am sure this error is from Parameter.

**Comment by SiraEnterprises** [comment]
Just in case you need the exact bug error code for the name text widget

IT40hcrqw5dgobRJ7s/+bMJVgio5JmY/ULsoletRaDYvCIyqOph/ZeDBM1pDXu2mYFNhHFCZhk4109XFvtr+UvQBE0yYftg6+c9AewvJTTbkEuzyT+3IHDUHZbsSXTTm

**Comment by agreaves** [comment]
Thank you for this detailed view! I've identified the issue and fixed it our end. You should see this fix on our next release! 🙂
