### ISSUE TITLE
Cannot Delete Actions

### ISSUE THREAD

**Issue by David44357** [FlutterFlow/flutterflow-issues#2932]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In an action flow, I click on the three dots in the top-right of an action and click "delete action". A green alert box at the bottom then says "action deleted". However, the action is still there and cannot be deleted. Eventually I just disable the undeletable actions. 

I have several such undeletable actions sprinkled through my project. I can confirm at least two other users I went to for help have also experienced the same bug. However, for them, they were able to delete the actions after a reboot, whereas for me they are just stuck.

These actions also cannot be moved using the arrows or cut/paste. They can be copied and the copied action is deletable/movable.

### Expected Behavior

That the action be deleted and removed from the action flow when delete action is clicked.

### Steps to Reproduce

In my app: Go to Apps/SpecialtyScreens/Complaint Claims and open the action flow for the Create Documents button. The disabled action under Action 4 is one such undeletable action.
I do not know how to create an undeletable action consistently.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjcrlvJFgofVY0ISJdMJV+TgXMjs9aJ0k1upEESs9f5CvOpYUec/6P1NCTfW+TVZIJGGMp14y/97XkdnQUe04PQ2aGrZ5ybtIExXiQXynVq2TF7q0VkR9GeFmCn6h4Zm3sQhCNshtSFIS2l2yIuzJSiztNr6yDVQwSq/LZO4=

### Context

It clutters my action flows with disabled actions and makes me unsure whether the undeletable action is somehow causing problems when troubleshooting an action flow.

### Visual documentation

![Screenshot 2024-05-18 093431](https://github.com/FlutterFlow/flutterflow-issues/assets/12780258/9d463010-471f-4f51-90e3-80936046b50f)
![Screenshot 2024-05-18 093445](https://github.com/FlutterFlow/flutterflow-issues/assets/12780258/e2a5e1d4-2e4a-4f94-82d2-3545a04a0a70)
![Screenshot 2024-05-18 093457](https://github.com/FlutterFlow/flutterflow-issues/assets/12780258/429a6e50-a44d-40f4-9efc-bab25592c05e)

### Environment

```markdown
Same behavior across Mac, Windows, and Web
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by James5943314556** [comment]
I am having the same issue

**Comment by msusviela** [comment]
Hi @David44357, @James5943314556 So sorry for the late response. I was not able to reproduce this on the latest version of FlutterFlow. Are you still experiencing this issue?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
