### ISSUE TITLE
Run mode not working properly

### ISSUE THREAD

**Issue by bsuplicy** [FlutterFlow/flutterflow-issues#2936]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since Thursday, the run mode is not working properly - text doesn't appear, only the components.

### Expected Behavior

Appear all the information in the text mode

### Steps to Reproduce

1. Run mode 2. Observe that the information is not there, half of the page is blank

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojefl4otItbxc7pDuK/lahSQWJjM5bY0N0cpBazwbfe+uB4kqevfOTERpQvXid0FXe2f8v2oW0NaMjoTtLuw4Cw2Cfa5dys5cUTvxWkGjR4iDFJWgQHBTEeRYCFC/55mnrRBSH7FiR0Y93zv7eu69FxLrGKK0NW4sD6/LZO4=

### Context

i cannot test the app

### Visual documentation

<img width="298" alt="Screenshot 2024-05-19 at 11 05 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/170249426/26b5ced1-0e18-40f7-86d9-154e36fa4307">

### Environment

```markdown
- FlutterFlow version: v4.1.53+ 
- Platform: Web
- Browser name and version: Chrome 124.0.6367.208 
- Operating system and version affected: macOS Ventura 13.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by DavidII** [comment]
I am a New User and I am have the same issue with pre-built Auth templates .   I am unable to render under test or preview

**Comment by msusviela** [comment]
Hey @bsuplicy, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by bsuplicy** [comment]
Hi @msusviela , thanks for you reply! I emailed the support but haven't heard back yet. I really need to figure out what is going on to keep working on my project, it is really time sensitive. Can you help me with that, please?

**Comment by rzambroni** [comment]
Hey @bsuplicy, hope you got an answer from support by now, otherwise let us know and we can try to escalate it again. Going to close this issue since this list is meant for bugs replicable on blank projects and not project specific. Thanks!
