### ISSUE TITLE
Need Supabase package update

### ISSUE THREAD

**Issue by mdrashedbinkuddus** [FlutterFlow/flutterflow-issues#2940]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to add supabase linkedin login. but for that I need to update "gotrue" package. In that package there is a enum called "Provider" which is now "OAuthProvider" and for likedin OAuth they need to set it to "OAuthProvider.linkedinOidc". So previous code is `await SupaFlow.client.auth.signInWithOAuth(Provider.linkedin);`

To solve that issue I need to update 5 package

- functions_client: ^2.2.0
- gotrue: ^2.7.0
- storage_client: ^2.0.1
- supabase: ^2.1.3
- postgrest: ^2.1.2
- realtime_client: ^2.0.4

But when I do that I get error in table.dart file

### Expected Behavior

New code should be `await SupaFlow.client.auth.signInWithOAuth(OAuthProvider.linkedinOidc);`

### Steps to Reproduce

1. Create a Custom Function
2. Add package `gotrue` latest version
3. Add the following code
```dart

import '/backend/supabase/supabase.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart'; // Import widgets to access Uri.base

Future linkedInLogin(BuildContext context) async {
  // Add your function code here!
  Uri currentUri = Uri.base;
  String redirectUrl =
      '${currentUri.scheme}://${currentUri.host}:${currentUri.port}/';

  if (kIsWeb) {
    await SupaFlow.client.auth.signInWithOAuth(Provider.linkedin,
        redirectTo:
            redirectUrl); 
  }

  final completer = Completer<User?>();

  SupaFlow.client.auth.onAuthStateChange.listen((data) {
    final AuthChangeEvent event = data.event;
    if (event == AuthChangeEvent.signedIn) {
      completer.complete(SupaFlow.client.auth.currentUser);
    }
  });

  await Future.delayed(const Duration(seconds: 10));
  if (!completer.isCompleted) {
    completer.complete(null); // In case it times out, return null.
  }

  return completer.future;
}

``` 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ck+fqxIt2j7xY+KrTbcBvmicXQkB/RY0NiO1hUQkYN5POD7AQP8nRP1dUcMzgdHxYIGG0in4X/MrTj/HIVsIFORyuRrZzyMx2SxX/fDmmVpCJCoS3b3clRNFXGhWH0KSRnCJAFPFpR1o+3EOYHOuRVjXXQ6X7DDIeQ+a4XdeK2SrDX1iXc2URm05KZDPz

### Context

I want to implement Linkedin login using Supabase. Everything was working when I do it on my local dev. But when I use custom action I get the error

### Visual documentation

https://www.loom.com/share/a16018232f9b487794728eb66bad6824

### Environment

```markdown
- FlutterFlow version: v4.1.53+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows Desktop
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @mdrashedbinkuddus! This tracker is only used for bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!

**Comment by webdevppl** [comment]
I am also facing the same issue. Any updates on this? Still we can't use the "OAuthProvider.linkedinOidc".
