### ISSUE TITLE
Can't save the work on the project, keeps reverting my saved changes and prompting the "No Access" pop up.

### ISSUE THREAD

**Issue by mohanedsayed** [FlutterFlow/flutterflow-issues#2941]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="1440" alt="Screenshot 2024-05-20 at 2 28 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/29494033/8b7004a5-8e1d-408e-9bdd-c9cde9247e3b">

### Expected Behavior

it should be working and saving my changes.

### Steps to Reproduce

dont have any idea why its happening.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wzMrl8YxNoctE+KrcdcExhj4vIjt5bLszle5DYCs8JJToPLAUZ8zBM05vZr3mYwhUJ0yWijodxvfquOGXVsI4HzStfrk4/6hqbxWXcHGgb7a6C7mVfW1QEe9nBUiE4Le72hRCNu9sR1YZ2066P+iyZ3fXGbr1PW0zHOalLdeK2SrDX1iXc2URm05KZDPz

### Context

<img width="1440" alt="Screenshot 2024-05-20 at 2 28 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/29494033/83a6a071-75ce-4a62-871e-2e99214e4326">

### Visual documentation

the no access issue because of my network thing 
<img width="1440" alt="Screenshot 2024-05-20 at 2 28 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/29494033/a08d5a71-ed0c-45e3-b96e-9ffc7a58b585">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [X] 1 hour
- [X] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by jessieplaydatecare** [comment]
I have the same issue since Friday, no changes are saved or displayed in the test mode, please prioritize the fix, it's a blocker
