### ISSUE TITLE
After copying a list of data types from one app state var to another and then changing the list, the change will reflect in the BOTH the target and original app state var

### ISSUE THREAD

**Issue by wemmick** [FlutterFlow/flutterflow-issues#2942]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have one app state data type var called "crawlRuleset" and another called "activeCrawl". They are of different data types, but both have a property that is a list of data types (type: crawlScoreCategory).

When I start a new "activeCrawl", I copy the crawlScoreCategories from the crawlRuleset to the activeCrawl as a starting point. Then, as the user progresses, then modify the crawlScoreCategories within the activeCrawl app state var.

That part works fine. HOWEVER, I noticed that the changes the user made were ALSO being applied to the crawlRuleset app state var's list of crawlScoreCategories, corrupting it.  

I replicated it in a blank project. If you test my blank project, here's what to do:

- Hit the top button: copies the list of data types (crawlCategoryScores) from the "ruleset" to the "crawl" app var. You will see them both appear below with the score set to 0.

- Bottom button: modifies the "score" in the first crawlCategoryScore on the crawl object.  Notice that it updates the first score for BOTH the crawl object and the ruleset object. Weird, huh?

### Expected Behavior

I would expect changes to the activeCrawl's list of scores to ONLY affect that var, and no other var.

### Steps to Reproduce

1. Create a data type called crawlCategoryScore. Properties: name (string), score (int)
2. Create a data type called crawl. Properties: timestamp, scores (list of crawlCategoryScores)
3. Create a data type caled ruleset. Properties: name (string), scores (list of crawlCategoryScores)
4. Create an app var of type crawl. Give it a timestamp
5. Create an app var of type ruleset. Give it a name, and fill in a couple arbitrary names and scores for the crawlCategoryScores. 
6. Create a page that shows the data for the crawl and the ruleset and their crawlCategoryScores
7. Create a button that copies the "scores" property of the ruleset to the "scores" property of the crawl
8. Create a button that modifies the the scores property of the crawl
9. Test
10. Hit top button, then bottom button, and notice that the update to the crawl categories ALSO updates the ruleset categories

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goeYD1s76Y/lQhQAkKUg4WLg7m9cbFBMaC7HkEIkAOur+VEhaTfWzTVA7Clf+hkUH0/TGkeLLKe05Hy2YaINoz6VpEw3xQl2RaJiyPaqSfmtfP8pYJhWayru7sR5+XdBvZXAjw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Well, every time a user uses my app, they record many "crawls", and every time they start, I need the ability to set the default values, but currently every time I try this, I corrupt the ruleset itself, so the next crawl starts with the same scores as the last crawl.  No good.

### Visual documentation

Demo of my blank project running: 
https://www.loom.com/share/484e3cd7b06740d89125c66532b815ad?sid=338f1fd4-663b-4000-b39b-d556d0422996

### Environment

```markdown
- FlutterFlow version: v4.1.53
- Platform: MacOS Desktop
- Browser name and version: Chrome 124.0.6367.208
- Operating system and version affected: MacOS 14.4.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by IanCarrasco** [comment]
Hi @wemmick, thanks for reporting this along with the steps to reproduce. We've made note of it on the ENG team, currently this is a limitation in the builder as variables are currently passed by reference (vs passed by value, i.e. unlinked). We'll discuss how this could potentially be exposed in the UI. 

In the meantime, the approach that can be used would be to write a custom function that accepts a parameter that is the same data type of the one you are trying to copy (crawlCategoryScores) and return a value of the same type, which would then return a copy that will unlinked from the original variable.

**Comment by wemmick** [comment]
@IanCarrasco Thanks for getting back to me.  I worked around it (forgot exactly how) some time ago, but yeah, agreed that if this is something to be expected, it should be indicated somehow.
