### ISSUE TITLE
Flutterflow CLI doesn't download Assets

### ISSUE THREAD

**Issue by wunder-tuete95** [FlutterFlow/flutterflow-issues#2943]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using Flutterflow CLI, the downloaded asset folder is empty. This does not happen when I click "download code" instead.

### Expected Behavior

Flutterflow CLI should also download all Assets.

### Steps to Reproduce

Run flutterflow export-code --project [project] --include-assets --token [token]
Downloaded folder has no assets in asset folder.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfis/q24ZNobRF+ZSJKcJGp2UsHHkcTL4zlO1HcxAYGO/yPbJ/ffTsalppZ+nmSmlhHGCLsD0Kp979uOzEU8A5PTacRrZP1aVUVwziTXq8RpCMPc3tZmpBEf1XGhGm0qur3Al7AON1dGw1wDmuet6AZBXUJ5+/Zwh9f6PHaOI=

### Context

Cannot use Flutterflow CLI

### Visual documentation

None

### Environment

```markdown
- FlutterFlow version: v4.1.53+ 
- Platform: Mac OS terminal
- Browser name and version: Chrome
- Operating system and version affected: macOS Sonoma 14.4
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @wunder-tuete95 thanks for your report. I just downloaded a project with the Flutter CLI and the assets appeared correctly inside assets/images. Remember that the assets that are not being used will not be exported, are you sure you are using them on your application?

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by marcelo-azevedo-br** [comment]
Hi @ignalauret , I am having the same issue. In my case, doesnt matter if the assets are being used or not. The only image that appears is a flutter logo as a favicon.png inside asstes/images. Could you please reopen this ticket?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/159544805/c1913de6-9818-42f5-82dc-c2e03a915e3f)
