### ISSUE TITLE
The native app doesn't launch without Internet connection

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#2944]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a mobile app, but it doesn't launch without an internet connection. It just gets stuck on the loading screen (white screen on iOS and logo screen on Android).

### Expected Behavior

The mobile app launches on the Home or Welcome screen.

### Steps to Reproduce

It’s difficult to reproduce this error; it’s possible that some widget or package doesn’t work without an internet connection. I have several such projects, and some of them launch without an internet connection.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl+fq2ItOsbQC7q6JbsFv+SkQHHkcTIMziNZ+exUbfaL1BqQqdc78XFVvXcOhaVNcD0yKgkQJzN7QufHXC/EnPgqdfYhl/6hiTgz0e2i6b7GVELmOWGtPBexjC1S73KWC3R1TCNNZW1o/3zqDeu6iShLDFOu/Zwh9f6PHaOI=

### Context

This started happening in one of the projects a month ago. Now, more and more projects are behaving this way and don't launch without an internet connection.

### Visual documentation

[https://lh3.googleusercontent.com/j7rBnvYW0Fg0dDIt0RB2LbY8pW4iJ9LCYviaGsHCZ_BD62ZNmtdu2cFkC5G8M3v-Pu4y=s1048](url)

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: iOS, Android
- Browser name and version: Safari
- Operating system and version affected: macOS 14.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by leighajarett** [comment]
Hi there! Right now, this is a known part of our implementation. We hope to make the desktop apps work offline in the future. Thanks for understanding!

**Comment by oper2k** [comment]
> Hi there! Right now, this is a known part of our implementation. We hope to make the desktop apps work offline in the future. Thanks for understanding!

I mean the mobile apps that I created using FlutterFlow.

**Comment by leighajarett** [comment]
Oh I see, sorry for the misunderstanding! Someone else also reported this issue - we are actively looking into it - [https://github.com/FlutterFlow/flutterflow-issues/issues/2950](https://github.com/FlutterFlow/flutterflow-issues/issues/2950)

**Comment by ready4sea** [comment]
Just to add to the global picture, I also investigated the issue initially opened by @oper2k and have added additional elements in the comments here: https://github.com/FlutterFlow/flutterflow-issues/issues/2950#issuecomment-2301665839

Thanks @FlutterFlowEng for taking this request into consideration.
