### ISSUE TITLE
Firestore/Firebase App crashing on Apple only 

### ISSUE THREAD

**Issue by npschwab** [FlutterFlow/flutterflow-issues#2946]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After installing Xcode compiled app to a physical device the following error is reported on the log: 
`dyld[734]: Library not loaded: @rpath/FirebaseFirestore.framework/FirebaseFirestore
  Referenced from: <817C466B-91E7-314F-95D2-0966607D7E37> /private/var/containers/Bundle/Application/52463C64-3109-4B15-8DA3-D7163D23315C/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/FirebaseFirestore.framework/FirebaseFirestore' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FirebaseFirestore.framework/FirebaseFirestore' (no such file), '/private/var/containers/Bundle/Application/52463C64-3109-4B15-8DA3-D7163D23315C/Runner.app/Frameworks/FirebaseFirestore.framework/FirebaseFirestore' (no such file), '/private/var/containers/Bundle/Application/52463C64-3109-4B15-8DA3-D7163D23315C/Runner.app/Frameworks/FirebaseFirestore.framework/FirebaseFirestore' (no such file), '/usr/lib/swift/FirebaseFirestore.framework/FirebaseFirestore' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FirebaseFirestore.framework/FirebaseFirestore' (no such file), '/private/var/containers/Bundle/Application/52463C64-3109-4B15-8DA3-D7163D23315C/Runner.app/Frameworks/FirebaseFirestore.framework/FirebaseFirestore' (no such file), '/private/var/containers/Bundle/Application/52463C64-3109-4B15-8DA3-D7163D23315C/Runner.app/Frameworks/FirebaseFirestore.framework/FirebaseFirestore' (no such file)`

This only occurs on the apple version of the app. Android and web version function just fine.

### Expected Behavior

App can run without error just as it currently does on Web and Android versions.

### Steps to Reproduce

Compile apple version of app via Xcode and install to device. Error will be reported on startup of the app.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SjOfl3It2tbxZ1s/qLO9agjoRJnI4bZIRl9VQEQIbGKmuPaQLXOjASEhVXd+/TAl2Ilv9rDgz7sqJk/DPC+QHAzurbqFx1rVuYAqXRT+6R5iDPMyaVX8mGdhXNEuV38K7phBAOu1qLHwHw2eQN+etcCjBJ5juPjM7Qeb9CKTD+WDiAhm6Xn0Jg1ZSfCvr

### Context

I am attempting to create an apple version of the app that works equivalently to the web and android version.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/153056153/1f319a67-1518-4cf5-9e2b-c6a7c884306d)

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: MacOS
- Browser name and version: Safari 17.4.1 (19618.1.15.11.14)
- Operating system and version affected: 14.4.1 (23E224)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
