### ISSUE TITLE
I can't distribute because of Custom Widget! (I waited for you to bring a feature, but it didn't come)

### ISSUE THREAD

**Issue by DevKursat** [FlutterFlow/flutterflow-issues#2947]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm getting an error while deploying

### Expected Behavior

Successful deployment

### Steps to Reproduce

Try to deploy new version

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeyfLl05NPn7xJ16X1LccwmQMwGkQ5a7sviu5+FBQaI+P1BIkUe8zRYRJDWOqHS29AH1mbnmEz//CNhYbPJvFcNS6Vf65JzahhUxDhf3y5SqbQDJboe0Z9EcJYCWac5rSrkCNBKsdYdX9m3F6Le9iuY3qCf9qOYwx5e6fDbOY=

### Context

I hope to distribute the new version

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/141324500/ad539238-3a82-4868-ba30-7b186abc276e)

### Environment

```markdown
- FlutterFlow version: V.4.1.53+
- Platform: Web
- Browser name and version: Chrome, Microsoft Edge
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by leighajarett** [comment]
So sorry about this issue - code magic seems to be down so all deployments are failing. We are waiting for a response from the code magic team and hope to resolve this ASAP
