### ISSUE TITLE
 Firestore Data Manager not functioning properly

### ISSUE THREAD

**Issue by MemoriaM1** [FlutterFlow/flutterflow-issues#2949]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The circle just keep on turning and turning and no content and showing

![Screenshot 2024-05-13 193044](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/489d1767-f91a-42c4-be8c-47104791ccc7)

### Expected Behavior

should be showing all the data content

### Steps to Reproduce

go to firestore
manage content
3.and the firestore data manager pop up
the circle keep on spinning and no content showing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/HluIlPm+FY+KqIbflWlSkRQ1h6TLJEoetxc0gbfe/4PLQPPuCkaRZoZOKzaH9AJWGIkj4F0MGNj/HTCOwnNQesf4c6+ZBIVBPPbEeiaKqRDcySOWgkL8BXJhW60Z2noglRAMhsWl4C6meQCN6RHj6Cf9qOYwx5e6fDbOY=

### Context

I can't continue inputting the necessary data to run the app

### Visual documentation

![Screenshot 2024-05-20 160140](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/6e37d65d-b5aa-4796-b2b5-280432d75770)

### Environment

```markdown
FlutterFlow version: 4.1.49
- Platform: Web
- Browser name and version: Chrome 124.0.6367.157
- Operating system and version affected: none
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
I already answered on the other one. Closing because it's duplicated and we want to avoid confusion.
