### ISSUE TITLE
Markdown widget's quote block is unreadable in dark themes + more issues with markdown widget

### ISSUE THREAD

**Issue by itm154** [FlutterFlow/flutterflow-issues#2955]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Markdown quote blocks seems to be unreadable because of the background. And also a few issues with the markdown widget.

### Here's a comparison in light and dark mode [^1]

| Dark mode | Light mode | 
|---|---|
| ![Image 2024-05-21 at 13 12 53](https://github.com/FlutterFlow/flutterflow-issues/assets/67090166/20ee744a-d1f2-470d-a1be-3ba556d327e6) | ![mage 2024-05-21 at 13 12 52](https://github.com/FlutterFlow/flutterflow-issues/assets/67090166/d7f2c6d7-bb6a-4932-ab3a-212c139c85e7) |

Right now FlutterFlow does not have a way to define any properties for the markdown widgets except for its contents. Would be nice if you could fix and improve on the markdown widget because it feels pretty barebones and the rendering is pretty bad especially compared to Github's markdown.

> Maybe you can render quote blocks with a only a line on the side like this? [^2]

[^1]: Tables also does not rendered correctly in flutterflow
[^2]: I also tested footnotes and it also doesn't seem to work
``

### Expected Behavior

> Block quotes in markdown should be readable

### Steps to Reproduce

1. Create a new page
2. Add markdown widget
3. Paste in some raw markdown demo with quote blocks and other stuff ([i used this](https://markdown-it.github.io/))

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsmBw4p2obVE17XuasAwmSQRQml+a+cvi8pBZzYgF5DsBJl/PM/6PlVtXcOnTVFYJGecp14K+fCPhtrtA8EBEEiVf6Y7/pF6VT3MbECWb5eTF7W8dHR8TP1VJ36D1527uwklKshiLWQh2F2uNd/KfHXqQJ+zC3o8Sq/LZO4=

### Context

I am now pretty limited with what formatting I can use in markdown. Especially important since I'm making an app for articles

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/67090166/7fa07566-5ed4-47dc-9303-633635aff0d0

### Environment

```markdown
- FlutterFlow version: v4.1.53+ (released May 17, 2024)
- Platform: Android, Web
- Browser name and version: Brave Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) unknown (64-bit)
- Operating system and version affected: Linux (NixOs), Android, Windows
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @itm154 thanks for your report. I understand your complain with the markdown widget not being more flexible. There is already work being done on it, we will let you know when there is progress. For now, you can work with the background color of the MD to make it look the best possible, and using the MD elements that look best. <br>Closing this issue and creating an enhancement request, have a great day!
