### ISSUE TITLE
Allow marketplace items to be added from widget search menu

### ISSUE THREAD

**Issue by mhjb** [FlutterFlow/flutterflow-issues#2959]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't add Marketplace widgets to pages. Console error is:

`Uncaught TypeError: Cannot read properties of null (reading '$0')
    at main.dart.js:444451:9
    at jpi.a (main.dart.js:5200:63)
    at jpi.$2 (main.dart.js:177448:14)
    at Object.p (main.dart.js:5186:10)
    at il3.$0 (main.dart.js:444473:10)
    at c0r.aDT (main.dart.js:291522:14)
    at tear_off.<anonymous> (main.dart.js:3929:79)
    at Zl.bOs (main.dart.js:283053:9)
    at Zl.pe (main.dart.js:283057:21)
    at Zl.bN6 (main.dart.js:283484:14)`

### Expected Behavior

Widget should add to page

### Steps to Reproduce

1. Start new project
2. Attempt to add any Marketplace widget to page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grulA7rrcdcdKgSQRJkB/RJEzi8pBZywgfZzzBLN/fPfQP1dWUte4YH9PMGKmp14d+cGLvd/DUccCJUyVba1z1s52Wg7gIVigVYuTF7WoSn99I/FjGFTH08OngQlTKuxYR1IM7DiUHti8YD/vHq6xDWo8Sq/LZO4=

### Context

What I'd really like is to be able to control the standard VideoPlayer widget from buttons elsewhere on the page. That doesn't seem possible, so I'm now trying to use the Custom Video Player marketplace widget

### Visual documentation

<img width="1441" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1380991/e6049e30-df3a-4f04-b289-8dd6eb6ecff8">

### Environment

```markdown
- FlutterFlow version: v4.1.53+
- Platform: Web
- Browser name and version: Chrome latest + Safari Latest
- Operating system and version affected: macOS Sonoma 14.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @mhjb thanks for your report. I can confirm that I'm getting the same error when trying to add a MarketPlace widget. I will check with the technical team what's going on here and let you know on this thread. Have a great day!

**Comment by mhjb** [comment]
thank you!
