### ISSUE TITLE
Lottie Animation doesn't load the color

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#296]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Load the Lottie Animation properly with its color

## Current behavior (required)

On Android the Lottie Animation doesn't load the color

## To Reproduce (required)

1. Add a Lottie Animation
2. Build an APK and publish the app on the web too
3. See that have different behaviors

### Bug Report Code (required, generate from Widget Tree)

ITESz/Hqx89gobUD0LXhKPlQhQkhNjN/bZIRjt5+FAgbGJyuP4l/evWkdlVBcO6lSnNMIkSmmkQxw63OiobfLvUoJReCbbpjz7hqFhXvRmG5ZcHfU/HUACkbeacOQSj6

## Context (required)

I want load a Lottie Animation

## Screenshots / recordings

![Web](https://user-images.githubusercontent.com/36147203/209884238-004260fb-1f94-4b03-98a7-fd8db5237139.png)
![Android](https://user-images.githubusercontent.com/36147203/209884240-f0fd628d-88a8-49b0-a7ae-e917b6552198.png)

Web: https://test-o7tv5e.flutterflow.app/

## Your environment

* Version of FlutterFlow used: 26 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by skipper113-FF** [comment]
Hi,

I've created a sample project with a lottie animation file and have loaded it up on my android device.
I cannot replicate your color issue on my real android device.

Can you please point to the actual lottie json file that you're using?
Thank you.

**Comment by Franco98404** [comment]
Hello that is the Lottie Json:

[structure.zip](https://github.com/FlutterFlow/flutterflow-issues/files/10329270/structure.zip)

Hope you can find useful!

**Comment by hariprasadms** [comment]
Hello, Looks like we can't produce the issue. It should be related to configuration issue at user end. As there are no follow ups on this issue, we are closing the issue. Let us know if the issue still persists. We can re open the issue and start investigating.

**Comment by Franco98404** [comment]
Hi, still persists the error

**Comment by bulgariamitko** [comment]
Can you record a video of the issue?

**Comment by Franco98404** [comment]
Hi @bulgariamitko, here is the video, hope you can find useful

https://schoolfy365.tinytake.com/msc/ODEzODIxNF8yMTMyNTE5Mg

New Bug Report Code: IT4CjMmB289NodhE7aqNacFVimAUJjM6RY0w0MJDY0sgHZPHCpl/P8nRak5dXbCiTGxIeWKZ8X4Ip/TMkfzlFMECPk6IQ75azs9+ExXKIHGhVL2bEKioYmhQTOJbGkCMyqCOiglDOtZfSVok21OYLvDLdBTcNLLQIjBMBuWJKoXJp3jlGnrNNDhmtmNecCfn
