### ISSUE TITLE
Changing Network Path of PDF Viewer doesn't load the new PDF

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#2961]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the `PdfViewer` widget, if you change the Network Path to a new one, it shows a spinning wheel forever, even though the URL that is set is a valid PDF.

### Expected Behavior

`PdfViewer` should reload the new PDF and display it.

### Steps to Reproduce

1. Create a new page
2. Add a `PdfViewer`
3. Have it load the PDF from Network Path, and set the Network Path as some page state
4. Change the page state that it depends on upon click somewhere in the widget to a new, valid PDF URL
5. Initial load works - then click on the button to change the state and observe

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmB05NItb0E+YfyL8dvqwMwGkQ5a7sviu5+FBQaI+PzPJofdsnSREtpSOqHf1ZHMFH/kj0H063xi+OfVsc6YCScRYhRzpFhUxDhTkGjRciVBqq7dHx7N/JTJ3XDyqbYggolObZvWk0twV2EHeiAb3qCf9qOYwx5e6fDbOY=

### Context

I am trying to create a page where the user can upload multiple PDFs, and then can click between them to preview.

### Visual documentation

<img width="1189" alt="Screenshot 2024-05-22 at 9 29 20 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/4b29178e-513a-4f9a-81df-b384eb473b3b">

### Additional Info

I pushed the code locally and inspected it.
- it correctly sets a valid PDF url as the network path
- it rebuilds the pdf viewer widget
- yet it never finishes loading

### Environment

```markdown
- FlutterFlow version: v.4.1.53+
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @bloemy7 thanks for your report. I can confirm that the loading indicator never goes away after changing the PDF viewer. I will send this to our technical team so they can take a look and keep you updated on this thread. <br>Have a great day!

**Comment by koosdeklerk** [comment]
Any update on this issue? I experience the same.

**Comment by SkylerAspegren** [comment]
Any update here? This is similar to another issue that has also been open for months with no resolution.

**Comment by devjoter** [comment]
Here is my solution:

https://community.flutterflow.io/discussions/post/solution-to-pdfviewer-widget-issue-in-flutterflow-ihtqBnEfgH1CFaJ

If you want to use it as workaround please feel free to tag me and will be more than happy to help you.

Marcin.

**Comment by sbis04** [comment]
This issue should be fixed in the update next week!
