### ISSUE TITLE
Paginated DataTable based on stream Firebase query always loads with 5 rows per page even if there are many more items

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#2962]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you use a paginated `DataTable` that's based on a Firebase streamed query, it always loads with the default value of 5 rows per page, even if your query actually returns hundreds of items.
This creates an extremely bad user experience since it only shows 5 items per page and the user needs to scroll through the pages to see all of the following ones.

### Expected Behavior

Two options:
A. The possibility to customize what the pre-defined number of rows per pages is (this should be a parameter of the DataTable in Flutterflow!!!)
B. At the very least, correctly handle the stream query case, and have it display 10 rows per page when there are more than 10

### Steps to Reproduce

1. Create a new page
2. Add a DataTable
3. Have its data be dependent on a Firebase stream query that returns more than 10 values
4. Run the project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmB05NItb0E+YfyL8dvqwMyQEgnU+cRl9ZxcxQjCoj2OpkAWvTBTFFWXLyqdwlDeGCggnM0/PfqkvLEU/o5IS6YfL5/1ZFIeg3wTXK7WrKmDaWRfW1RL+FVChCB3KSCkR55LttqdUVhwV77JPDKc3PaNo/7IFYzJf61KdeK2SrDX1iXc2URm05KZDPz

### Context

This is one of the main screens in our project, and because of this bug it's causing issues since we want it to display more than 5 rows per page.

### Visual documentation

<img width="292" alt="Screenshot 2024-05-22 at 9 38 10 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/423210bb-9b6b-4b50-9730-105674a466c5">

### Additional Info

I have pushed the code locally to investigate what is happening, and it's as follows:
- the Firebase query seems to always return only 1 item, and then it returns the full number of items
- because of this, it first initializes the data table with 1 item, which causes it to initialize with 5 rows per page
- even though it then reloads the data table widget with the full number of items, which should change the numbers of row per page to 10, it does not do that

### Environment

```markdown
- FlutterFlow version: v.4.1.53+
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @bloemy7, could you provide me with more information about the Firebase query that you're using?

**Comment by bloemy7** [comment]
@msusviela it's basically a regular top level collection query, with 4 AND filter conditions.
First one is an "in" type filter, so one of the properties is "in" a list of given items.
The other ones are very simple boolean = false type filters.
Finally we limit the result to a 100 items.

**Comment by msusviela** [comment]
Hi @bloemy7. Sorry for the late response. There has been some fixes regarding DataTable in the last update. Is this still persisting to you?

**Comment by bloemy7** [comment]
@msusviela  This is still persisting, yes. It's not been fixed. We'd love some extra insight into this because it's really problematic. Thanks

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
