### ISSUE TITLE
Flutterflow CMS sets a enum field with the enum code and not the string of the enum

### ISSUE THREAD

**Issue by Nic61** [FlutterFlow/flutterflow-issues#2963]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Previously FF CMS would show a list of choices for an enum field on a collection. On choice it would set that field to the enum string. You can then build logic with this in FF (e.g. conditional visilibity if a document has a certain enum set).
However for some weird reason it now sets the enum to its unique identifiable code (at least I presume that that's what it is) and not the string anymore.
It broke my live app for quite some time, before O noticed.

### Expected Behavior

Set the enum to the string value

### Steps to Reproduce

1. Create a project
2. Connect firebase
3. Create an enum
4. Create a collection with a field set to an enum
5. Open FF CMS and create/modify a document and set the field to one of the enum values
6. You'll see it sets it as not its value but as a weird code.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Use enums in my project

### Visual documentation

na

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Web
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @Nic61 thanks for your report. This has already been addressed and the fix will be deployed on next release. Here the thread where it's being followed: [https://github.com/FlutterFlow/flutterflow-issues/issues/2546](https://github.com/FlutterFlow/flutterflow-issues/issues/2546)<br>Have a great day!

**Comment by Nic61** [comment]
Thanks @ignalauret
