### ISSUE TITLE
Login for local run on Mac fails

### ISSUE THREAD

**Issue by dennis-g** [FlutterFlow/flutterflow-issues#2964]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to login in the app under MacOS with my Google account. In the browser it says: "Credentials successfully verified.". However, back in the app this error appears: "Error: HandshakeException: Handshake error in client (OS Error: WRONG_VERSION_NUMBER(tls_record.cc:231))".

### Expected Behavior

I should be able to login with my Google account.

### Steps to Reproduce

1. Download app for macOS from https://flutterflow.io/desktop
2. Install it.
3. Run it. 
4. Click on: Sign in with Google
5. Enter your credentials
6. Go back to the app.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

I wanna run my Flutterflow app locally.

### Visual documentation

n/a

### Environment

```markdown
- FlutterFlow version: n/a
- Platform: n/a
- Browser name and version: Chrome 124.0.6367.119
- Operating system and version affected: MacOS: Sonoma 14.4.1 (23E224)
- Flutterflow App for Mac: Version 4.1.53 (4.1.53)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by microprocessltda** [comment]
Same here

**Comment by ignalauret** [comment]
Hey @dennis-g thanks for your report. I'm sorry you are not able to login with google into our Mac app. Would you feel confortable sharing me your Google email so we can check if there is something wrong with it? The Mac App seems to work fine for everybody else, that's why I would like to check your case. <br>Have a great day!

**Comment by dennis-g** [comment]
Hi Ignacio,

Thank you for investigating. My address is ***@***.***
It's a company address.

Kind regards!


Ignacio Lauret ***@***.***> schrieb am Do., 23. Mai 2024,
02:11:

**Comment by dennis-g** [comment]
Any news about the issue @ignalauret?

**Comment by ignalauret** [comment]
Hey @dennis-g I'm sorry for the late response. Were you able to login with your google account on the Mac app? Or did you continue using the Web app?

**Comment by dennis-g** [comment]
Hey @ignalauret. Thanks for asking! I had the same problem again. However, after several tries it worked finally.
