### ISSUE TITLE
Google Crashlytics Stopped Working

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#2966]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Crashlytics has detected a missing dSYM for version 2.3.3 (298)

### Expected Behavior

Works normally

### Steps to Reproduce

1. enable Crashlytics
2. deploy to app store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcr1z5R1obxY0LXTbfpWoCcXJVx+TL03pu0bFEggGLbrBIYMaeDRalVuONOiSnw2KEWGnlw1+vTzud/yGvpfCzaqbohRwap+SjyXWn+/aoSmO4eaWEFQP9JjIXK10MGJniVSCMtsW01lw06XfvCva3TcO4f7Zwh9f6PHaOI=

### Context

Crashlytics worked fine until the last deployment I am receiving the below error:
<img width="638" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/d3400ab5-b08f-42b6-9e0f-4ee160eb1a54">

### Visual documentation

<img width="601" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/fe462da0-98e9-4332-a681-efde48437840">

<img width="616" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/66eedbd9-b514-4e28-8a6a-6001b4630d15">

### Environment

```markdown
- FlutterFlow version: v4.1.53
- Platform: iOS
- Operating system and version affected: iOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @alih552! This message means that your configuration is missing the debug symbols. Please follow the following [guide](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#ios-locate-dsyms) and verify if you can upload the debug symbols.

**Comment by alih552** [comment]
Hi @paulperez-dev  FF used to handle this automatically, I don't need to use Xcode for this, it was working before.
