### ISSUE TITLE
Webview crash when keyboard opens on Android

### ISSUE THREAD

**Issue by Golicraft** [FlutterFlow/flutterflow-issues#2967]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When entering a textfield it tries to open my keyboard and then the page refresh. This is only in webview and happens only on Android, not IOS.

### Expected Behavior

I should be able to open the keyboard and write in the textfield.

### Steps to Reproduce

1. Make a webview
2. Add this URL example: [https://forms.gle/tsJu4hTk7Rq6KVuN9](https://forms.gle/tsJu4hTk7Rq6KVuN9)
3. Publish to web and enter the project on Android

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slsn15YpNj7xH7aqNdcFB/SAsQ0x5RoEkscpvRRQgI4DuBIYiacjeUxdVUvWgdAlhKEWJrGEJpM77idjpUu1eAxecfZxZ+rt2Eg/JfEy/aovQCpGeZnJBL+1YI36i5LSzsxMmLsRfWF0jw16UOPCyZHftCZf7Zwh9f6PHaOI=

### Context

I try to add forms into my app project. It's the sole purpose of my project. Without the ability to answer forms my project doesn't work.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/11066952/b87089c9-cd45-4944-a931-2f51f00ea3f7](https://github.com/FlutterFlow/flutterflow-issues/assets/11066952/b87089c9-cd45-4944-a931-2f51f00ea3f7)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.53+ released May 16, 2024
Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Chrome (I also tried web app)
- Device: Samsung S20
- Operating system and version affected:
```

### General                                                                                                                    

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] \~100% of the time
- [ ] \~50% of the time
- [ ] \~10% of the time
- [ ] \~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @Golicraft! I was not able to reproduce the issue. I tried it on Android 12. Which version of Android are you in? Also, please try to replicate the issue on a blank project and share the Bug Report Code again.

**Comment by Golicraft** [comment]
Hi. I'm testing on Android 13. I tried again on a blank project here is the bug report code: IT4szPHlw81NodsD+KryKPl7/Tg7Q3p7RoIascpvRRQgI4DuBIYiacn4QxNtTte7S3xtKEWIjlMx//zPj/HfKvQ4FymuQLY9zc9cVQ/Kfzi/aovQCpGeZnJBL+1YI36i5LSzsxMmLsRfWF0jw16UOPCyZHftCZf7Zwh9f6PHaOI=

Keep in mind that this is my settings on the Webview widget: 
<img width="143" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11066952/5e147685-bc39-4e42-8ed0-596a2ac6d336">

I need the height of the webview to cover the whole screen. If I for example to "PX 500" then the issue doesn't happen on Android but then not the whole screen is covered too. So I did "% 100" to cover it all. Please test again

**Comment by crossxsecure** [comment]
Hello Team, there seems to be an issue with the Webview back button. Suppose you navigate from Page A to Page C, and then press the back button. Regardless of the current state of the Webview, it exits the Webview activity and returns to the Flutterflow activity that initiated the Webview. This is not the expected behavior. Could you please look into this? Thanks.

**Comment by Franco98404** [comment]
I'm experimenting with the same problem:
https://www.loom.com/share/6f14bd3af3a34e248e092f8ae46f815b

You can test it here:
https://webview-82cpjw.flutterflow.app/

I'm on Android, but I'm doing it on a web page (I don't use a native app) on Motorola Edge 20 Pro with Android 13.

### Bug Report Code
ITFTzPHlw81NodsD+KnfYPoxjiERCUMfWLsr0utuGA0hNYD3O4k+fcj4bktLYtThT35iOVSIiT40wfDQveDPFPBeFyidbtQ7/75XQQLvRji5eLaIEc2oS3QmGcdgIX3H1sK3vQlQFO5sdV413GahfPCNG3qCf9qOYwx5e6fDbOY=

**Comment by paulperez-dev** [comment]
Hi everyone! If I open Franco's link I can see the issue on my Android 12, but when creating a new project I cannot replicate the bug. I tried with your links and opening the WebView inside a component, a different height size, but nothing worked.

Can you please try to reproduce this issue again from a blank project using the latest version of FF?

If the issue persists, please attach as much information about the configuration as possible, thanks!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
