### ISSUE TITLE
Can't back to previous page when editing a component

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#2969]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't back to previous page when editing a component

### Expected Behavior

Can back to previous page when editing a component

### Steps to Reproduce

1.Create a new project, automatically created HomePage, call as HomePageA
2.Create a new page as PageB
2.Create a new component as ComponentC
3.Place C to B
4.Edit C in B
5.Shown "Back to HomePageA", instead of "Back to PageB"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goddZ7qXcbe56hQIgQ0QnU7gnlO1ucx4YfL6oPIoEd8n7U0NKQtPgenxUDU2b/UYK3MLHhYf9NPQpBwuBG75Y0JVAShXwIHylWoyXO7uSYXAkP9hWC26x58KFqxJ5LttiS1pm2V+hNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I'm editing components whole days, so i hope this will be solved soon.

### Visual documentation

<img width="307" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/d9c4eaf1-2342-40f2-978b-247bf48e2b78">

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Mac
- Browser name and version:Chrome : 124.0.6367.208
- Operating system and version affected: macOS 14.4.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by leighajarett** [comment]
A fix for this issue should be out in the next week or two!
