### ISSUE TITLE
Using Current Time option to update a timestamp column from Supabase throw an error

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#297]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Update the column on Supabase

## Current behavior (required)

Nothing happens and throw an error

## To Reproduce (required)

1. On the Scaffold of the page Update a Row
2. Choose a timestamp column and try to update using the current time
3. Nothing happens and throw an error on Developer Console

### Bug Report Code (required, generate from Widget Tree)

ITESz/Hqx89gobUD0LXhKPlQhQIgQ0QnU7gnlO1ucx4YB7WtBLM+dc7eYUNKT/29fH1mOkyZpDoH/87QhoXXO/VcPkmdG6Zlk/UwKlCvHAM=

## Context (required)

I want update a column with the current timestamp. By the waym is there a way to show the error to the user instead to see it on developer console?

## Screenshots / recordings

Show that error on console of Developer Console
![image](https://user-images.githubusercontent.com/36147203/209912174-81f43ba7-27e7-4a71-b636-d65e65cd4b6f.png)
On Supabase is set as timestamp data type
![image](https://user-images.githubusercontent.com/36147203/209912367-73875d31-5b40-4b62-a024-9dff1a721229.png)

## Your environment

* Version of FlutterFlow used: 26 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by bulgariamitko** [comment]
Yes I saw that during our live session yesterday actually and the reason for that is that both FB and SB are using different types of timestamps. FB is using timestamp and SB is using timestampz so I don't know if this is a bug or a feature.

**Comment by Franco98404** [comment]
SB uses timestamp, timestamptz, date and time if I'm not wrong, but I have configured the database to use timestamp (without timezone) so looks like a bug, any news about this?

**Comment by Mktotoy** [comment]
Hi ! Same problem for me, i just opened an issue i didn t see there was already one : 
https://github.com/FlutterFlow/flutterflow-issues/issues/316

My initial subject was about : 

-I get my first timestamp from supabase db with the format 2022-01-01T12:34:56Z (with a Z at the end because it's in timestampz format)
-A custom function of my own generate timestamps from initial value with added durations
-A GridView show all these generates timstamps correctly at the default format (ending by Z) and also when i ask to timestamp format the output( HH:mm for example). The text output was always well shown.
- The problem occurs when i want to insert this timestamp to a supabase row where ive got the error "Error: Converting object to an encodable object failed: Instance of 'DateTime'"

I already try to parse and format the timestamps to remove the Z, but the error was still present : i can print the variable on the app, but i still have an error when trying to insert the value inside db. 
The same probleme occurs for DB field type "timestamp" or "timestampz"

**Comment by Franco98404** [comment]
I found a workaround but it is very complicated if you have a database configured. This simple function solves the problem but you need to take some extra steps.

1. Go to the SB table and modify your timestamp column and change for a varchar type
2. Get the SB schema on FF
3. Go to the SB again and change the column modified previously and change for timestamp again
4. Instead of using the Current Time from global properties, call this function and now it is works on SB.

The idea of this is trick the FF schema, to let us send a string instead of a timestamp, but we already modify the data type on SB so it won't be a problem

Some clarifications:

- I only tested with timestamp (without time zones)
- If you have a lot of tables (as in my case) you cannot modify the data type of a column on SB easily, because in my case it is used on a lot of views.

```
String newCustomFunction(DateTime timestampOriginal) {
  return timestampOriginal.toIso8601String();
}
```

**Comment by savioarruda** [comment]
I have this same problem. I can't update a timestamp field from Flutterflow to Supabase.

**Comment by agreaves** [comment]
Thank you all for the bug reports! As you've pointed out there's currently a serialization bug in the FF Supabase code which will be fixed upon our next deploy! Apologies for the inconvenience.

@Franco98404 The project in your bug report code also contained another code compilation error that I've also fixed 🙂, I'm not sure if you've reported it or not.

**Comment by Franco98404** [comment]
@agreaves Honestly, I don't remember which bug it was because in the last few days, I found other bugs and now I am creating a project for each bug to report it.

**Comment by savioarruda** [comment]
@agreaves When will be the next deploy? I have tested and the issue persists. 

![image](https://user-images.githubusercontent.com/93232036/211057708-3632f2a9-f80e-444c-b5aa-bc517d369d5c.png)

**Comment by Mktotoy** [comment]
A temporary solution for me was creating an "integer" field in my db, and send by the request the conversion of the timestamp to int from FF, and adding a trigger before insert with a function on the table

BEGIN
  NEW.start_at = TO_TIMESTAMP(NEW.start_at_int / 1000);
  RETURN NEW;
END;

It works and when the next deploy will be send, i'll just change my insertion and remove the trigger
