### ISSUE TITLE
flutterFlow desktop (mac version) restart every time you are not active for more then 20+ min.

### ISSUE THREAD

**Issue by valinometru** [FlutterFlow/flutterflow-issues#2972]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Every time I take a break or I'm not using flutter flow the desktop version restart it self so you basically have to rebuild the app on the sim every time. If the app is open and it's the last thing you used then is not doing this behavior only when you start using other apps on your desktop and it takes longer then 20+ min. This behaviour wasn't present 3-4 updates ago.... 

The most annoying part is that in order for the sim build to be successfuly compiled you have to close the flutter flow app, close (both) the sim (I'm using two for testing purposes) then start the flutter app fetch the devices, wait for the process to detect only Mac (desktop) and web, then launch the iOS sim from the flutter app (and after the first sim started start the second one in my case) then re-fetch the devices available select the two iOS devices and only then the build will be successful... 

I don't know... for me it's very annoying... 

### Expected Behavior

The expected behaviour should be the app not restarting it self every time I'm not using it for more then 20+min.

### Steps to Reproduce

1.Start your project 
2.Fetch the devices you want to test on (in my case two iso devices)
3.Compile for the build to test the app. 
4.Don't use the flutterflow desktop app for more then 20+min instead browse the web or use another app non correlated to flutter flow (not even the sim). 
5.Return to flutter flow desktop app, now the app will restart and you will be forced to rebuild the sim app so it's live. 
6.If you rebuild the compiler will fail. 
7.Completely Close flutter flow, Completely close the sim (both).
8.Start flutter flow again. 
9.Fetch the devices, wait so it detect only web and Mac desktop.
10. Launch the sim from the flutter app (then only after the first sim started start the second sim). 
11.Delete in both sim the app you previously built. 
12.RE-Fetch the devices.
13.Add the two devices on the build list. 
14.Build.... wait.... and now finally it works.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjsmAw4hOxcMA7qXxbe5GoCM7C2Z6TL07ttYbZxUjIuPtBJh/Zcj7flpBZOHnTGlhHFX9kn4d0vz6i+LPNvcEIRKcRqpAwahQZwzxTXq8R5fXEKm0PXNCGtFYG0Ci1MOZkyYlXcxuR1Y93UyqA+qiTTDvCZ+/Zwh9f6PHaOI=

### Context

It's time consuming and to be honest really annoying.... 

### Visual documentation

I can't reproduce it visually.... it takes forever... 

### Environment

```markdown
- FlutterFlow version: 4.1.53 (4.1.53)
- Platform: Mac
- Browser name and version: Chrome 124.0.6367.119
- Operating system and version affected: Sonoma 14.4.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @valinometru! I will close this report since it was reported on [https://github.com/FlutterFlow/flutterflow-issues/issues/2931](https://github.com/FlutterFlow/flutterflow-issues/issues/2931). 

Thanks for your feedback!
