### ISSUE TITLE
Action "Play Sound" not playing with "on Data Change" on Tablet Web

### ISSUE THREAD

**Issue by clickqcollect** [FlutterFlow/flutterflow-issues#2974]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The "Play Sound" Action is triggered whenever there is a change to a document.
Play Sound works flawlessly on Desktop but when used on Tablet (iOS and Android, various Versions) its not triggered properly.

### Expected Behavior

Play the Sound whenever there is a change to the document

### Steps to Reproduce

Create a Backend query on the root.
Add "Play Sound" action to "on Data Change" behaviour
Change something in the document of the backend query
Sound should play

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oi/Hqw5VNsctF0L6JbsFFimAvHDM2a4ZMkMIbSU40IYvNG4gIZfTBXE9uOP25dghHM02Wp3Mx+dKOm9z2G/YEITaCbIhYyLliUDuXcDilVLGbDquaSnNUGshMIWqj15272yR5PsF2WiFh2FOIOe+RTXbtCb70DWwaQ/j/Ub7XrgfuQ0SLb3kNh1JWeC/v

### Context

We have built an order dashboard.
For every new order a sound should be played to inform the kitchen staff about it.
Right now this is a major bug for us as the kitchen staff has no way to respond in a timely manner to incoming orders leading to customers canceling their order

### Visual documentation

<img width="1069" alt="SCR-20240523-nhoi" src="https://github.com/FlutterFlow/flutterflow-issues/assets/153713219/cb32c6a2-576d-400a-82f1-dce1b02b47e2">

See image attached

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: iOS & Android Tablet
- Browser name and version: all browsers
- Operating system and version affected: iOS & Android
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
