### ISSUE TITLE
My app is in blank screen on "Testflight" only 

### ISSUE THREAD

**Issue by dan-arki** [FlutterFlow/flutterflow-issues#2975]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When launching my app I have a blank screen on testflight only.
I don't have this blank screen on the web version published.
I don't have this blank screen on the run mode version.
I don't have this blank screen on the test mode version.

### Expected Behavior

When launching my app I except navigate to my "Entry page" or my "Logged in Page".

### Steps to Reproduce

Launch the app on testflight only

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skcjf35NOm9tJ+Kr+bsBB/WE7KW1+bYEescp/bxIgGIDzPOw+ZPWldhNoXeGgTXNEekSmmlg07tbeuOPhDfQ3OT6Ac74/+s5QSAz/WkGQUZOBC6mOSnR8GcFMI1SZ5LWFsRBCWdhudHAgwDiQDO+/aArsCYSxImdISq/LZO4=

### Context

I try to test my app on a real device

### Visual documentation

It works on web version :
https://github.com/FlutterFlow/flutterflow-issues/assets/100216647/fca5ab5b-9ce9-4b50-a7c6-d44ff9e5e623

The issue when launching on testflight : 

https://github.com/FlutterFlow/flutterflow-issues/assets/100216647/b05b87ac-6a8e-44d3-8965-489acc3369a5

### Additional Info

when you launching the

### Environment

```markdown
- FlutterFlow version: v4.1.53
- Platform: Iphone
- Browser name and version: Iphone 13 pro max
- Operating system and version affected: IOS 17
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
