### ISSUE TITLE
Error caused in functions due to recent update 

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#298]
<img width="1440" alt="Screen Shot 2022-12-30 at 12 58 12 AM" src="https://user-images.githubusercontent.com/121250616/210010485-dbb1ee4e-2e45-4600-8ad0-8ad0b7099a51.png">

**Comment by SiraEnterprises** [comment]
Please note I am receiving this error after the recent update. It shows these errors in a simple function which is a multiplication of two integers. When I delete this function, it shows the same errors in the other function.

**Comment by agreaves** [comment]
Thanks for the bug report, working on it and will deploy a fix shortly.

**Comment by SiraEnterprises** [comment]
> Thanks for the bug report, working on it and will deploy a fix shortly.

Fixed. Thanks

**Comment by agreaves** [comment]
Excellent! Thank you very much for the swift report, apologies for the inconvenience!
