### ISSUE TITLE
Video Player Widget - "Video Type" issue

### ISSUE THREAD

**Issue by theinrich22** [FlutterFlow/flutterflow-issues#2981]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Video Player widget does not contain the "Uploaded File" selection for "Video Type" in its properties settings. This makes it impossible to preview a video, after selecting a video on the local storage of the device, and before an upload from that device occurs.  The Image Widget allows this feature.

### Expected Behavior

The option of 'Uploaded File" should be added to the Video Player "Video Type" properties, allowing the video to be previewed from within that widget prior to an upload.

### Steps to Reproduce

1) Create a new page
2) Add a container of size capable of holding a local device video file (.mp4)
3) Add the Video Player Widget in the container widget
4) From the Video Player properties panel, select the "Video Type" drop down menu
5) Notice that the "Uploaded File" option is not present like it is in the Image Widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

It affects the ability of a user of our app to preview a selected video file, selected from their local device, prior to sending a social media post to our API servers. 

### Visual documentation

1) The first image shows the Video Type selection for the Video Widget as it exists today.
2) The second image shows the available options of the Video Type drop down selector.
3) The 3rd and 4th images show the same, except for the Image widget, which properly contains the "Uploaded File" selection.

![VideoPlayerWidget_1](https://github.com/FlutterFlow/flutterflow-issues/assets/91419436/da3ef746-7ed7-4b5a-b492-dbc77710912f)

![VideoPlayerWidget_2](https://github.com/FlutterFlow/flutterflow-issues/assets/91419436/98562ea9-ad97-42c2-b62a-8538e7a5b70f)

![ImageWidget_1](https://github.com/FlutterFlow/flutterflow-issues/assets/91419436/8a4d8d98-52a6-48c9-9ea8-10a6debf1500)

![ImageWidget_2](https://github.com/FlutterFlow/flutterflow-issues/assets/91419436/571399e9-8c16-42b4-b335-de122ba8cd81)

### Environment

```markdown
- FlutterFlow version: V4.1.47
- Platform: Windows local Flutterflow App 
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
@theinrich22 thanks for your report. I can confirm that there is no "Uploaded File" option for video, so you can't show a video from the Bytes that you have uploaded. I will ask our technical team if this is on our Backlog, or if there is a reason why it's not there. We will let you know on this thread. Have a great day!

**Comment by ignalauret** [comment]
Hey @theinrich22 I've confirmed this is something the team is looking into. I will link your issue to the feature ticket so they let you know when it's available. Closing this issue, have a great day!
