### ISSUE TITLE
Revenue Cat - Google Pay - India - Not recognise payment if email id is different in FF app and Google Pay email 

### ISSUE THREAD

**Issue by RohitKanade** [FlutterFlow/flutterflow-issues#2985]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not recognise payment if email id is different in FF app & Google Pay email 

### Expected Behavior

It should recognise payment irrespective of email but using its device IDs. (Actual payment / not test payment - India)

### Steps to Reproduce

1. Integrate Revenue Cat 
2. Pay using google play India using - different email in same device where app is installed but app has different email registered. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

Not recognise payment if email id is different in FF app & Google Pay email 

### Visual documentation

Not recognise payment if email id is different in FF app & Google Pay email 

### Environment

```markdown
new
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by RohitKanade** [comment]
any update?

**Comment by rzambroni** [comment]
Hi @RohitKanade,

I sincerely apologize for the delay in addressing this issue. Unfortunately, it got moved by mistake, and we lost track of it. Would you mind confirming that you are still experiencing this issue? It might be a bit tricky for us to replicate as it looks like it requires a specific setup and environment.

Thank you for your patience.

**Comment by RohitKanade** [comment]
Yes issue still there, and some more

1. If someone used email address logged in App & Google pay has different
email address - payment always gets failed (it’s android)

2. FF function of payment - did not wait for payment to compleye on
Apple/ios - gives failed status - today I raised and shared screen video as
well.

3. If payment is late (card slow) - payment always shows failed

Seems like FF RevinueCAT integration is not working for all cases, may be
not for prod uses & unfortunately i need to remove it to avoid customer
complaints.

This app has all setup -
https://play.google.com/store/apps/details?id=com.nine99.linkbuddy

https://apps.apple.com/in/app/linkbuddy-get-job-today/id6480404203


Thanks
Rohit

**Comment by rzambroni** [comment]
Hi Rohit,

Thank you for your response! Could you let us know where you shared the video?

Regarding the three issues you mentioned, they do seem to be separate and potentially tied to specific scenarios (e.g., the card being slow, which might indicate a timeout). To help us validate and troubleshoot effectively, it would be incredibly helpful if you could provide clear steps to replicate the issues. Even better, if you could share a blank project where the issue is consistently reproducible, that would give us a solid starting point for addressing and fixing them.

Thanks so much!

**Comment by RohitKanade** [comment]
All 3 issue appear in project (LinkBuddy) Which I shared in previous mail.

First issue - login using gmail and in gPay using different email - it
always fails

Second issue about ios app - video link is here -
https://drive.google.com/file/d/11LlVhVKEolLnFiDPEyNgv_dNhYyt-phj/view?usp=drivesdk

Third issue - may be timeout - but seems like FF does not handle payment
which may be little late (30sec)

**Comment by rzambroni** [comment]
can you share a bug-report-code of that project so we can investigate? thanks!
