### ISSUE TITLE
Test mode account creation with firebase Stop working after an unknown number of account creation a day. 

### ISSUE THREAD

**Issue by LacroixAdrien** [FlutterFlow/flutterflow-issues#2986]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Once create account button is clicked, the loading sign starts spinning for ever and no document is created.

### Expected Behavior

When clicking create account button it should move forward with the usual actions implemented and document creation.

### Steps to Reproduce

1. create Login/account creation page
2. create complex actions such as loop and conditions to create appropriate files on account creation
3. do user account creation many times

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skcmAz4x2sdtF+Kr+bsBB/SgQG1A4RLgwscsZa0kdB4joPLJ/PeLRXFdoTsvjSmlhHEyZ/X0Ew9Llkdj1FcIqC06BRY9xwodqSg7xQXq8R8WVPZa0VWglDdxQGUCd37SrmyVCVbFtL3xn7zmqPN6Ra3fsJ5+/Zwh9f6PHaOI=

### Context

Test mode Login with firebase Stop working after an unknown (rather low) number of account creation a day. 
I successfully created around 20 test accounts. 
Then at some point, when create account button is clicked, the loading sign starts spinning for ever and no document is created.
It happened twice recently. I spent hours trying to figure out what's wrong in my actions at account creation.
But the next day it works fine again with no modification done.

It seems that there is an invisible flutterflow and or firebase daily limit ?

### Visual documentation

<img width="300" alt="Capture d’écran 2024-05-25 à 12 44 31" src="https://github.com/FlutterFlow/flutterflow-issues/assets/47387898/c5614d7c-a5e8-495f-ad6a-8f54aaf081f6">

I d'ont have any screenshot of the spinning button as today it works fine again...

### Environment

```markdown
- FlutterFlow version: v4.1.53+ released May 16, 2024
Flutter version is 3.19.1
- Platform:Web
- Browser name and version: Chrome Version 125.0.6422.60 (Build officiel) (x86_64)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [X] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @LacroixAdrien! I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. <br><br>You can verify the limitations [here](https://firebase.google.com/pricing). Also, verify the **Usage and Billing** section, maybe limits are being hit when the logging stops responding.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/27afd2e5-2c6a-4111-82d4-3847c5861894/cb072edf-6e68-4637-9e96-5bb23b68419f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yN2FmZDJlNS0yYzZhLTQxMTEtODJkNC0zODQ3YzU4NjE4OTQvY2IwNzJlZGYtNmU2OC00NjM3LTllOTYtNWJiMjNiNjg0MTlmIiwiaWF0IjoxNzE2ODU3Nzk1LCJleHAiOjMzMjg3NDE3Nzk1fQ.6NRSGrlDFLJhQ7U2-_VaX6y74hETm19AD2pR2Q9gmA8 " alt="image.png" width="423" height="184" />

Hope some of this can guide you in the right way!

**Comment by LacroixAdrien** [comment]
Hi @paulperez-dev !

Thanks a lot for the help. It was indeed due to cloud firebase free plan quotas.
It is good to know where they stand. 

Have a nice day!
