### ISSUE TITLE
The homepage is causing the app to slow down significantly, making it unusable

### ISSUE THREAD

**Issue by subhan900** [FlutterFlow/flutterflow-issues#2987]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am experiencing issues with three queries in my app. Each of these queries involves a count operation, and they exhibit abnormal behavior. Specifically, they continue loading indefinitely until I interact with an item on the homepage (such as clicking a toggle button or a listview item). Additionally, the toggle button operation is extremely laggy, and scrolling throughout the homepage is sluggish. Initially, everything worked smoothly and efficiently, but after an update, the entire app has become unusable.
![loading](https://github.com/FlutterFlow/flutterflow-issues/assets/95876553/5d0a9285-a90f-4608-bb76-92f701a39215)

https://github.com/FlutterFlow/flutterflow-issues/assets/95876553/b53f67aa-1f28-4271-898f-31e34575be97

### Expected Behavior

The homepage should be smooth, the toggle button should perform its operation seamlessly, and scrolling should be fluid. Additionally, queries should load promptly without requiring interaction with items on the homepage.

below the attached video when it was working seamlessly in earlier apk  downloaded from flutterflow

https://github.com/FlutterFlow/flutterflow-issues/assets/95876553/7b46f64c-00ad-49b9-965e-d10c097a4ca2

### Steps to Reproduce

Whenever you run the app, the homepage becomes laggy. When you press the toggle button (which has a heart design), it operates too slowly and significantly impacts the overall behavior of the app from the very beginning.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTivHq7YhPm7RB+KqBbMJF+WUvM0MdXOczitVEew4bCIj4ELNydsmlRFtVcNCzaH9fMFKZqz8H0Nb9kuDpVu4oZA2eRqo51KtbExPPY3GgbK6UPLuwQ0FQTNlYIFCw55+N2xVvIsFpc3hm21yMJOqsRT6Cf9qOYwx5e6fDbOY=

### Context

The app's overall user experience has been negatively impacted, and I would like to achieve a smoother experience.

### Visual documentation

I have attached two files the one error.mp4 shows the issues and seamless.mp4 how it was working before the previous apk.

https://github.com/FlutterFlow/flutterflow-issues/assets/95876553/f197744d-da15-476c-be1b-b88b30f01d26

https://github.com/FlutterFlow/flutterflow-issues/assets/95876553/96f13b32-8726-4614-81a9-163689fb3f1b

### Environment

```markdown
- FlutterFlow version:4.1.53+
- Platform: Desktop , android
- Browser name and version: microsoft edge as well as apk is effected
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @subhan900! So sorry you are facing this issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. Thanks!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
