### ISSUE TITLE
Custom function no longer compiles, throwing error related to Supabase when project isn't using Supabase

### ISSUE THREAD

**Issue by cmelnyk** [FlutterFlow/flutterflow-issues#299]
My custom function (a simple subtraction function) no longer compiles and the web text editor says it has errors (no errors are highlighted).  This function worked until the FF update 30 minutes ago (12/29/2022 4PM EST) and is unchanged.

Here is my function:

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

double calculateWeightMargin(
  double maximumWeight,
  double cartWeight,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  double weightMargin = maximumWeight - cartWeight;
  return weightMargin;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

And here is the error:
![image](https://user-images.githubusercontent.com/51460135/210014037-891311a2-ce68-4dd6-927c-9511fc986fec.png)

Here are links to two other users on the FF forums reporting a similar issue:

1. https://community.flutterflow.io/c/bugs/error-since-last-update-29-12-22-the-method-mapequals-isn-t-defined-for-the-type-supabasedatarow
2. https://community.flutterflow.io/c/bugs/custom-code-error-after-last-update-dec-29

**Comment by cmelnyk** [comment]
I'd also like to add that this isn't a minor bug, this prevents users from compiling and testing the app in run mode.

**Comment by agreaves** [comment]
Hi @cmelnyk, can you include a Bug Report Code for this (generated from the widget tree)?

**Comment by cmelnyk** [comment]
This is the bug report code from the only widget that is using this custom function.

ITEelsn15YtPtbwC0KXbKu5GgQMzN0g2a+cZm9VxbwIoIpznBqQtPMz7P1RWUvWhaVNcDmClnkAJwdHFhdrtNO4oaQqeRoQ9+s1Udj3AKTbkEuzyT+3IHDUHZbsSXTTm

**Comment by singh-sp** [comment]
+1 -- same issue -- `supabase` is disabled for the project.

This function was working fine before today's update:

```
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

bool checkAnswer(
  String selectedAnswer,
  String questionType,
  QuestionDataStruct questionData,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  bool result = false;

  if (questionType == "MULTIPLE_CHOICE") {
    result =
        questionData.correctAnswers?.any((a) => a == selectedAnswer) ?? false;
  }

  return result;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```
<img width="401" alt="Screenshot 2022-12-29 at 2 07 42 PM" src="https://user-images.githubusercontent.com/6597802/210015563-0a6666e0-3721-446b-b1e8-a218dfc27e1c.png">

**Comment by agreaves** [comment]
Thank you for this report and information. Apologies for this issue, it has now been fixed and released! I will wait to close this issue until you can confirm.

**Comment by singh-sp** [comment]
It's working fine for me now! Thanks for fixing it.

**Comment by cmelnyk** [comment]
Looks like it's working now, thanks for the quick response!
