### ISSUE TITLE
Cannot perform a GET with OR in Supabase Query natively

### ISSUE THREAD

**Issue by leoweebt** [FlutterFlow/flutterflow-issues#2991]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The filters in the supabase query only works with AND operator, but a lot of times I need to use the OR operator.

<img width="500" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159651220/c5f451f3-bf99-4ec2-bbdc-ad858e1a6866">

In order to solve this I need to create a custom action, but the custom action cannot be automatically initiate after a Supabase Query in the root container.

First I get the parent element and them I need to load all the options in the select with a custom action.

<img width="877" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159651220/27b30154-1014-45bf-a57f-10ef107b83f8">

### Expected Behavior

It should be able to perform a OR Operator Query.

### Steps to Reproduce

1. Create a page
2. Add a Supabase query in the root container
3. Create a child container
4. Load a second Supabase query with a OR Operator Query, searching for the received Id of the root container and the userId of the active user

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4szPHl3ItPm9td7qXydflR/GUsKUg/RoI0scpCbw4bIYj2P4lzY876P1toZOHmTWxpM2CMp14D06nqvc7DUvkrAymZG90+1rlUEzyVRk+VRamTF7uCYXJ9EelMIW6e15i7vQlNKfhtR3gQwV6YHO6yYDXtN4TSO2o8Sq/LZO4=

### Context

I'm trying to create a clean flow with Supabase but without OR operator in filter it almost impossible.

### Visual documentation

<img width="500" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159651220/c5f451f3-bf99-4ec2-bbdc-ad858e1a6866">

<img width="877" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159651220/27b30154-1014-45bf-a57f-10ef107b83f8">

### Environment

```markdown
- FlutterFlow version: 4.1.53+
- Platform: Windows and Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by leoweebt** [comment]
If I could use the Custom Action as a Query Type it also be great.

**Comment by ignalauret** [comment]
Hey @leoweebt thanks for your report. I'm not really understanding all of the setup here. Currently you can't make OR filters on a Supabase query. I don't think it's because you are doing a second query inside another query. <br>So, could you confirm that you are not able to create an OR filter, and you are asking for it to be available? Or are you asking for something else?

**Comment by leoweebt** [comment]
I'm asking to create an OR filter, this is such a important feature.
