### ISSUE TITLE
Can't change CheckboxListTile background color

### ISSUE THREAD

**Issue by Chren** [FlutterFlow/flutterflow-issues#2992]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't change the background color of a CheckboxListTile; it's always transparent.

### Expected Behavior

The background color of CheckboxListTile should be configurable.

### Steps to Reproduce

1. create a CheckboxListTile and add to a column
2. set the tile color property to primary color
3. Observe that the tile color not changed on the builder
4. Click Run
5. Observe that the tile color not changed on the run mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oksrqx5BNobhe+Kryb8EwvyQvNjN9R40rlMpBTTwYCIz0P+wMecjTflJvOdeHT2x2JVv9kj4KptXGv4aeVuQHAz6sUbpdzpZQWgv/fEi7RpCLErW0RkQmP+hXDkuV5p64kQhNBMVfSFoa62aMGu+Wc3fYHpDyDW1AAv78JpvMs3fgAi+6Xn0Jg1ZSfCvr

### Context

I was trying to use CheckboxListTile to show a list of selectable tile.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/349182/ce9d1673-0e81-43fc-a0ab-e96e20cdc600)

### Environment

```markdown
- FlutterFlow version: v4.1.53+ released May 14, 2024
- Flutter version: 3.19.1
- Platform: Mac OS
- Browser name and version: chrome 124.0.6367.210
- Operating system and version affected: Mac OS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1a6f47a7-278a-46ef-9dac-423e7ec68037/95266eea-59f4-4337-a15f-f5de7795857a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYTZmNDdhNy0yNzhhLTQ2ZWYtOWRhYy00MjNlN2VjNjgwMzcvOTUyNjZlZWEtNTlmNC00MzM3LWExNWYtZjVkZTc3OTU4NTdhIiwiaWF0IjoxNzE2ODYyNzQ0LCJleHAiOjMzMjg3NDIyNzQ0fQ.w-yV_HccZj795QydxxtGTK9YjYdeQ81sd9JwfaG4Zt4 " alt="Screenshot 2024-05-27 at 11.17.57 PM.png" width="382" height="215" />

Hey @Chren thanks for your report. I just checked your project and I can see the ListTile has your primary color as the background. Are you still experiencing this issue or is it fixed?

**Comment by Chren** [comment]
> experiencing

Yes, the issue is still there. It only works when I change the container's fill color to transparent. You can check the latest project to see how it looks when I change the container's fill color's alpha to 50%. It seems to mess up the hierarchy when displaying tile color.
@ignalauret 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/349182/550cd291-b24d-4ae0-b57b-f907c502a234)

**Comment by GoCloudToday** [comment]
@ignalauret to confirm this issue happens with the normal ListTile as well, exactly as @Chren explained, when the container on an upper level is filled, the widget produces an error.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121566690/29ec9e9a-6d56-4c94-89ca-07df369e1320)

**Comment by GoCloudToday** [comment]
@ignalauret are there any updates on this issue?

**Comment by ignalauret** [comment]
Hey @GoCloudToday sorry for the late response. Did this background issue got fixed on the new version of FF? Or are you still experiencing this problem?

**Comment by Chren** [comment]
> Hey @GoCloudToday sorry for the late response. Did this background issue got fixed on the new version of FF? Or are you still experiencing this problem?

Yes, we are still experiencing this problem on the new version of FF

**Comment by GayaneKasparova** [comment]
Hello. I'm facing same issue with listTyle Items

<img width="1710" alt="Screenshot 2024-07-03 at 15 43 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/54121528/c9109a04-64fe-4232-be9c-479261b7e6e8">
<img width="1758" alt="Screenshot 2024-07-03 at 15 43 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/54121528/631caedd-390c-4e63-bd1c-df9cd7165957">

**Comment by Alezanello** [comment]
> Hello. I'm facing same issue with listTyle Items
> 
> <img alt="Screenshot 2024-07-03 at 15 43 08" width="1710" src="https://private-user-images.githubusercontent.com/54121528/345408429-c9109a04-64fe-4232-be9c-479261b7e6e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTAwMzIsIm5iZiI6MTcyMDAwOTczMiwicGF0aCI6Ii81NDEyMTUyOC8zNDU0MDg0MjktYzkxMDlhMDQtNjRmZS00MjMyLWJlOWMtNDc5MjYxYjdlNmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMjg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDkzNGM2OGM3M2ZkMDc3NDEyMjBkNmI3OWU0NWQzYTQwY2I4NTcyYTBhZmE1NzAxOTdiZGE5NWExNjFhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pg69wkBowZ10g0LFAWZzhdNvU4Qlc9ClYNWdICJ8Sdg"> <img alt="Screenshot 2024-07-03 at 15 43 29" width="1758" src="https://private-user-images.githubusercontent.com/54121528/345408436-631caedd-390c-4e63-bd1c-df9cd7165957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTAwMzIsIm5iZiI6MTcyMDAwOTczMiwicGF0aCI6Ii81NDEyMTUyOC8zNDU0MDg0MzYtNjMxY2FlZGQtMzkwYy00ZTYzLWJkMWMtZGY5Y2Q3MTY1OTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMjg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTAyMzNkMjkyNTEyMTk2MmQ3MzBjNmI2Y2Q5YjBmMThiNzRhMTNjOWY1MWViYTUwYWVlOTM0MjkwNmVjOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwPPilTHl7qpTI_nr2nsSmjeLzXGrtx0KELPN8733ik">

Hello @GayaneKasparova !

Can you share with me a Bug Report Code of your project to check similarities with @Chren and @GoCloudToday issues

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. We have tested and confirmed the errors reported by you and others.

We are escalating this issue to our engineering team for further investigation and resolution.

Best regards,<br>Azanello

**Comment by sbis04** [comment]
This should be fixed in the upcoming update!
