### ISSUE TITLE
Removing custom function argument wipes unsaved code

### ISSUE THREAD

**Issue by PadreMontoya** [FlutterFlow/flutterflow-issues#2994]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I add an argument from a custom function or remove an empty argument, the code editor wipes unsaved code.

### Expected Behavior

If I add an argument from a custom function or remove an empty argument, my current unsaved code should be preserved or I should be warned so I can copy my code to my clipboard before the code is destroyed.

### Steps to Reproduce

1. Create a custom function
2. Accidentally create an empty argument
3. Write code
4. Attempt to hit save and receive a warning about an empty argument
5. Remove the empty argument
6. Weep and gnash your teeth as the UI wipes the code you were not able to save.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiMmAuIl2sctb1oSJLe5ahjs4JmEcTIMziNZ+exUbfaL1Buw2YM7BaVpvONe7aVNcEFGZnmIxpcrSjc7LDu1fA0mrUao7/7pMbhbOe2iQVZDWCbiOS2glQN5VIUDD3KbQ2RZBNtJYLXgu7E+QGuuyVj/DFOu/Zwh9f6PHaOI=

### Context

Attempting to create a custom function and resolve the error before saving it.

### Visual documentation

Steps to reproduce are self explanatory.

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [X] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [X] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @PadreMontoya thanks for your report. I was able to reproduce your issue and I understand it can be frustrating. I will send this to our technical team so they can look for a solution, they will keep you updated on this thread. Have a great day!
