### ISSUE TITLE
Error getting access token from microsoft.com, OAuth2

### ISSUE THREAD

**Issue by spenagos93** [FlutterFlow/flutterflow-issues#2995]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to log in to Flutterflow using Microsoft login, it's throwing an error related to expired credentials.

### Expected Behavior

You should be able to log in to Flutterflow using Microsoft login

### Steps to Reproduce

1. Open https://app.flutterflow.io/
2. Click in "Sign in with Microsot"
3. Write your credentials and try to login
4. You can see the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Error getting access token from microsoft.com, OAuth2 redirect uri is: https://flutterflow-io-6f20.firebaseapp.com/__/auth/handler, response: OAuth2TokenResponse{params: error=invalid_client&error_description=AADSTS7000222:%20The%20provided%20client%20secret%20keys%20for%20app%20'2151ebdd-d144-454a-b71d-2ae7eb196d5e'%20are%20expired.%20Visit%20the%20Azure%20portal%20to%20create%20new%20keys%20for%20your%20app:%20https://aka.ms/NewClientSecret,%20or%20consider%20using%20certificate%20credentials%20for%20added%20security:%20https://aka.ms/certCreds.%20Trace%20ID:%20ee64907b-6886-4212-bc21-ab4fe325e500%20Correlation%20ID:%202ff54e9c-bf17-4bda-9a22-cffe09b89ca0%20Timestamp:%202024-05-27%2014:33:02Z&timestamp=2024-05-27%2014:33:02Z&trace_id=ee64907b-6886-4212-bc21-ab4fe325e500&correlation_id=2ff54e9c-bf17-4bda-9a22-cffe09b89ca0&error_uri=https://login.microsoftonline.com/error?code%3D7000222, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDurationJava=null, cacheImmutable=false, staleWhileRevalidate=null, filename=null, lastModified=null, retryAfter=null, crossOriginEmbedderPolicy=null, crossOriginOpenerPolicy=null, crossOriginResourcePolicy=null, permissionsPolicies=[], headers=HTTP/1.1 200 OK

### Context

I haven't been able to access the editor to view my projects and work on them. And if this is a general issue affecting everyone using Microsoft login

### Visual documentation

![Captura de pantalla 2024-05-27 101109](https://github.com/FlutterFlow/flutterflow-issues/assets/86723095/6046cb88-9e49-4a91-97dd-e260251f896a)

### Additional Info

N/A

### Environment

```markdown
- FlutterFlow version: v4
- Platform: web
- Browser name and version: Chrome Versión 125.0.6422.113 (Build oficial) (64 bits)
- Operating system and version affected: windows
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @spenagos93 thanks for your report. I can confirm that the Microsoft login is giving an error. I will send this with high priority to our technical team, they will let you know when it's working. Have a great day!

**Comment by DhananjayaReddy84** [comment]
Any update on this team? I have not been able to login since Saturday.

**Comment by leighajarett** [comment]
@DhananjayaReddy84 just to confirm, you were previously able to login with your Microsoft credentials, correct?

As a workaround, I think you should be able to click forgot password and change your authentication to standard email / password so you're unblocked while we look into this further

**Comment by DhananjayaReddy84** [comment]
Hello Leigha,

I have been using my Microsoft account to login to Flutterflow for almost 2 years.

Regards,
Dhananjaya

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leighajarett** [comment]
Got it, thanks!

**Comment by leighajarett** [comment]
This issue should be resolved now, so sorry about the hold up!

**Comment by spenagos93** [comment]
thanks!
