### ISSUE TITLE
Photo library permission is not asked on android

### ISSUE THREAD

**Issue by kallolbecs** [FlutterFlow/flutterflow-issues#2997]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

enabled permission for photo library in settings. (for downloading an image)
Requested permission on a tap action  but on real device the request permission dialgoue never opens and in application info the permission doesnt show as well

### Expected Behavior

it should open the dialogue to grant permission on android devices

### Steps to Reproduce

Go to Settings and Integrations > Permissions > Photo Library
Enable Photo Library (+ add Permissions Message)
Create a blank page
Add a column
Add a button
Action 1 - On Tap, Request Permissions: Photo Library
Local Run on Android device
When app is loaded, click the button
Additional verification that permissions is not requested - go to app settings in Device Settings > [App Name] > Permissions
Observe that there are no permissions for Photo Library/ Gallery access despite it being enabled in the Settings Integrations in Flutterflow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klOflwIt2sctD1rrtbcEwgmI7HDMjTL0zqNYbGA0oIYyuOpl/evWkXBJBQuaqYEFAPESmmnkKzNbnjuzLM/I5Gw2eQKo91atUVhXNUkate5OBEauOPkdRJ5tTI0zD35+NiBV/LsF1SiEt22GmJdi/Xi3XQLLJIndISq/LZO4=

### Context

im trying to same an image from url to device. i want to dowlad the image from my app to devices's gallery. 

### Visual documentation

[Visual.Steps.-.Permissions.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/15467484/Visual.Steps.-.Permissions.pdf)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by kallolbecs** [comment]
@msusviela , thanks for looking into it. can we make it a high severity bug pls? its a launch blocker for us and i believe for many others

**Comment by Maazkhalid47** [comment]
same issue

**Comment by mycirclehq** [comment]
How much longer is this issue going to take to fix? This is a big issue for us.

**Comment by caringan** [comment]
This is a huge blocker, is there any way this can be accelerated?

**Comment by leighajarett** [comment]
Thanks for flagging, we are actively looking into this - will try and get it fixed ASAP!!

**Comment by kallolbecs** [comment]
Is the fix released in prod?

**Comment by leighajarett** [comment]
Not yet - it's merged in and should be available in production in a week or two depending on testing

**Comment by kallolbecs** [comment]
Pls update the ticket once released

**Comment by leighajarett** [comment]
These tickets are hooked up to our continuous integration to automatically close when merged in, sorry for the confusion!

**Comment by Supertecnoboff** [comment]
Has this been fixed yet? Many apps need photo library access. Thanks for your time.

**Comment by leighajarett** [comment]
Yes this issue should be resolved and in the product. Are you still experiencing an error?
