### ISSUE TITLE
Supabase web URL on published site display way too much information

### ISSUE THREAD

**Issue by Golicraft** [FlutterFlow/flutterflow-issues#2999]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, I noticed when using the web feature with Supabase my URLs look like this when going into a "post"
[https://myappnamehere.flutterflow.app/spisestederDetaljer?spisestederSeMerSupa={%22Navn%22:%22Tacoblokka+B%C3%B8%22,%22Tags%22:[%22Ost%22,%22Brunost%22,%22Tunfisk%22,%22Tunfisk%22,%22Reker%22,%22Salami%22],%22Nettside%22:%22https://tacoblokka.no%22,%22Antall_likes%22:7,%22Forside_bilde%22:%22https://upload.wikimedia.org/wikipedia/commons/4/4b/McDonald%27s_logo.svg%22,%22reviews_bilder%22:[%22https://nhrtvceveqqjykyuvagu.supabase.co/storage/v1/object/public/Spisesteder/Reviews_bilder/1713547135848000.jpeg%22,%22%22],%22DateAdded%22:%222024-04-13T10:05:49+00:00%22,%22LokasjonString%22:%22B%C3%B8gata+32,+3800+B%C3%B8+i+Telemark%22,%22Lokasjon%22:null,%22samletvurdering%22:[3,2,3,2,2,3,3,3,3,2],%22LagtTilAv%22:%22ee09a766-a995-4364-a530-015fc3ab98fb%22,%22Publisert%22:true,%22smak%22:[3,5,5,3,3,0],%22utvalg_ny%22:[3,3,3,3,3,3,3,3,4,3,0,3,3,3,0],%22Antall_Reviews%22:22,%22spisested_id%22:986553321}](https://glutensmilsupa.flutterflow.app/spisestederDetaljer?spisestederSeMerSupa={%22Navn%22:%22Tacoblokka+B%C3%B8%22,%22Tags%22:[%22Ost%22,%22Brunost%22,%22Tunfisk%22,%22Tunfisk%22,%22Reker%22,%22Salami%22],%22Nettside%22:%22https://tacoblokka.no%22,%22Antall_likes%22:7,%22Forside_bilde%22:%22https://upload.wikimedia.org/wikipedia/commons/4/4b/McDonald%27s_logo.svg%22,%22reviews_bilder%22:[%22https://nhrtvceveqqjykyuvagu.supabase.co/storage/v1/object/public/Spisesteder/Reviews_bilder/1713547135848000.jpeg%22,%22%22],%22DateAdded%22:%222024-04-13T10:05:49+00:00%22,%22LokasjonString%22:%22B%C3%B8gata+32,+3800+B%C3%B8+i+Telemark%22,%22Lokasjon%22:null,%22samletvurdering%22:[3,2,3,2,2,3,3,3,3,2],%22LagtTilAv%22:%22ee09a766-a995-4364-a530-015fc3ab98fb%22,%22Publisert%22:true,%22smak%22:[3,5,5,3,3,0],%22utvalg_ny%22:[3,3,3,3,3,3,3,3,4,3,0,3,3,3,0],%22Antall_Reviews%22:22,%22spisested_id%22:986553321})

### Expected Behavior

It should only show https://myappnamehere.flutterflow.app/spisestederDetaljer (Like in Firebase)

### Steps to Reproduce

1. Make new project
2. Connect with Supabase
3. Connect a query/referance with different tables
4. Publish to web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

I can't use Supabase if this is normal. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11066952/52bcf553-d357-4476-8251-dd4c567a7663)

### Additional Info

I gave up contacting FF support on Mail. I gave up using the community tab. Haven't got any response which is sad. Therefore I'm not going to spend so much effort in this report since it's more like a support ticket/question if this is on purpose or if this is a bug. 

Referance: https://community.flutterflow.io/ask-the-community/post/supabase-web-url-on-published-site-DxzkaFBM2aZqVBI
As you can see another user have the same issue. 

### Environment

```markdown
- FlutterFlow version: Latest
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Golicraft** [comment]
Resolved! Check here for solution: https://community.flutterflow.io/ask-the-community/post/supabase-web-url-on-published-site-DxzkaFBM2aZqVBI

**Comment by paulperez-dev** [comment]
Hi @Golicraft! A param will always show in the URL. One solution is what **IdeaGarage** commented on your post. Another is to save the data in a **State** and read it from there on the new page.
