### ISSUE TITLE
"Build Your First App" never dismiss on desktop 

### ISSUE THREAD

**Issue by lequentz** [FlutterFlow/flutterflow-issues#3000]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Env : FF Desktop version on MacOS (FlutterFlow v4.1.53 released May 28, 2024)

Repro steps : 
- Open a projet
- You can see the "Build Your First app Screen" tutorial
- Dismiss or go to the 12th step
- Leave the projet
- Come back to the project
- You can see the "Build Your First app Screen" tutorial again. You can never dismiss it. 

![Capture d’écran 2024-05-28 à 15 54 01](https://github.com/FlutterFlow/flutterflow-issues/assets/50026344/8eba0edf-c84e-4a22-818f-e6d49cfc0c67)

### Expected Behavior

Repro steps : 
- Open a projet
- You can see the "Build Your First app Screen" tutorial
- Dismiss or go to the 12th step
- Leave the projet
- Come back to the project
**- You don't see the tutorial anymore.** 

### Steps to Reproduce

- Open a projet
- You can see the "Build Your First app Screen" tutorial
- Dismiss or go to the 12th step
- Leave the projet
- Come back to the project
- You can see the "Build Your First app Screen" tutorial again. You can never dismiss it. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NaN

### Context

I don't know what to try

### Visual documentation

![Capture d’écran 2024-05-28 à 15 54 01](https://github.com/FlutterFlow/flutterflow-issues/assets/50026344/045178b8-848c-4656-90ae-27f3f3834712)

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Desktop
- Browser name and version: NaN
- Operating system and version affected: MacOS 14.5 (23F79)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
