### ISSUE TITLE
User Document is not created after Firebase Auth Create Account

### ISSUE THREAD

**Issue by alma-biz** [FlutterFlow/flutterflow-issues#3001]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a new user is attempting to create an account, the authenticated user record is created in Firebase however, the user document creation fails, which halts the onboarding process.

**Firebase e-mail Auth** 
1) Setup per documentation

**FlutterFlow Action set up:**  
1) Auth Create Account with "Create User Document" toggle enabled in the users collection
2) Navigate Action to a follow up onboarding page (This step is not reached as the process seems to stop at the failed User Document creation)

**users Firestore Rules**
- Create: Everyone
- Read: Tagged Users
- Write: Tagged Users

**Exception**
When Firestore Rules are changed so that Create, Read, and Write are set to Everyone, the process works as expected. eg. Firebase Auth Record Created, User Document Created, Navigate Action Successful. This is a major security risk so I can't leave set up like this, but hopefully this may assist in troubleshooting?

Additionally, this was not the behavior when I created 2 test users in February. Upon seeing this behavior yesterday I rebuilt the 'Create Account' setup from scratch and am still seeing this behavior.

Other uses have reported this issue here: https://community.flutterflow.io/database-and-apis/post/create-account-doesn-t-create-user-document-XBW50B0qSGsdSXl

### Expected Behavior

When a user attempts to create an account, the process should:

1) Create the Firebase Authentication User Record
2) Create the corresponding user document in the users collection _(Not occurring)_
3) Navigate to the subsequent Onboarding page _(Not occurring)_

### Steps to Reproduce

1. Create Firebase Email Auth Setup and Associated Create Account Page
2. Create a users collection
3. Setup Email Auth Account Creation with user Document creation enabled
4. Access the Create Account Page as a new user
5. Enter Required Information
6. Click 'Create Account'

The process will hang from here with no move forward. Firebase User Auth record created but no further actions occur.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkcjc35Z1m+Fc+KrQbMIxiSoQM0McWOdEl+tuZwgbIoznBu0cPsjRTElWXcjgaVNcBGGlhlIdpqnpjYT+UfUnEzabc75lyLVuVw/Oe2iVaa6xBaWKQ3EmHelRCBTC556G2h1vJrFqZXwi3EOyeeuUSinDIuu/Zwh9f6PHaOI=

### Context

This is a huge issue for me. New users cannot be created so it's disrupting app launch :( 

### Visual documentation

**1. Create Account Action Setup:** 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169722470/93132c8d-4fc7-4d91-9236-5203dd2950cb)

**2. Create Account submission:**
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169722470/bae520bf-1587-4555-a076-f684a3aa8fd6)

**3.  Firebase Auth Record Created**
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169722470/8c45dc94-7a74-40af-b10d-e4b4bd7e59ce)

**4. User Document Not Created**
<img width="893" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/169722470/5973d8bd-8cfe-487f-80ea-9d6220c2c949">

### Additional Info

Please let me know if you cannot recreate, happy to hop on a screen share and walk through it together!

### Environment

```markdown
- FlutterFlow version: v4.1.53+ released May 16, 2024
- Platform: Web
- Browser name and version: Chrome Version 125.0.6422.113 and Safari Version 17.5 (19618.2.12.11.6)
- Operating system and version affected: macOS Sonoma 14.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @alma-biz! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. 

Also, did you try the suggested solutions from the community?

**Comment by alma-biz** [comment]
Hi @paulperez-dev - Thanks for the response, will get back to you soon!

**Comment by alma-biz** [comment]
Hi @paulperez-dev - Thanks again for your review of this. Since I don't have active data, I was able to resolve this personally by creating an entirely new Firebase project and connecting to that instead. 

However, I don't think that actually resolves the issue at large since multiple users have run into this issue. The suggested "solution" in the community post is extremely painful as it requires users to redo their collections and project setup.

**Comment by paulperez-dev** [comment]
Hi @alma-biz! I'm closing this issue. Please share any insights you want me to share with the ENG team!

**Comment by mtruebe** [comment]
I also have run into this exact same issue

**Comment by mtruebe** [comment]
Changing firebase rules from tagged user to "collection" for the user's collection solved this issue

**Comment by cs-mattdutter** [comment]
Changing firebase rules from tagged user to "collection" for the user's collection worked for me as well
