### ISSUE TITLE
IOS Phone Authentication - It is not redirecting to the logged in page

### ISSUE THREAD

**Issue by giovannicocco** [FlutterFlow/flutterflow-issues#3002]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm not a member of Apple's developer program yet, so I disabled push notification in FlutterFlow to test on iPhone. Because that I can't use silent push notification for phone authentication so I am redirected to recaptcha. After recaptcha I am redirected to the entry page again, but I should be redirected to the logged in page.

### Expected Behavior

After recaptcha should be redirected to the logged in page.

### Steps to Reproduce

1. Create a phone auth flow
2. Set Entry page and Logged page in Flutterflow auth settings
3. Add your test phone number in Firebase
4. Disable push notification in Flutterflow settings
5. Local run with iPhone device without push notification
6. Sign-in with your phone number
7. Redirect to Recaptcha
8. After recaptcha must redirect to logged page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlcr1z89gostK1aX2KMFAhQIgQ0QnU7gnlO1ucx43fIjkOolzYs/OaUNKT+mhT39EH2KZuEgzpuDouN/+GsInGyetRb5H0JVAUjnzcGWRacWLPKuoXHJ6IJ9PI0Cf5J7QuAp5Lup2R14hw2WtNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to auth with phone.

### Visual documentation

![Captura de Tela 2024-05-27 às 14 16 34](https://github.com/FlutterFlow/flutterflow-issues/assets/6585496/eb08d346-84d9-4e5a-afcf-65e619e3b791)

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: IOS
- Browser name and version: Testing with device
- Operating system and version affected: Sonoma MacOS 17.5.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @giovannicocco! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

**Comment by giovannicocco** [comment]
Hi @paulperez-dev! Thanks for reply!

I identified the behavior, ran several tests.

If I configure the entry page as the login with phone, everything works normally, the flow is: login with phone -> Recaptcha -> Phone verification page -> Home. It works.

However, when I have an entry page being something like the Welcome page where the user has the option of going to login or signup, the flow with recaptcha breaks.

Should be like this:
Welcome -> Login -> Recaptcha -> Phone Verification -> Home

But it does this:
Welcome -> Login -> Recaptcha -> Welcome

In the flow that works, I noticed that the recaptcha returns for seconds to the phone login page and redirects to the verification page. Maybe enable replace route? But I don't know if that's the case.

**Comment by giovannicocco** [comment]
This issue persist.

**Comment by rzambroni** [comment]
Hi everyone!

Apologies for the delayed response on this issue. A fix was released for it some time ago, but we missed posting an update here. I’ll be closing this ticket now. If anyone is still experiencing issues, please don’t hesitate to let us know.

Thank you for your patience!

**Comment by svscorp** [comment]
I am facing the same issue @rzambroni, tested just now. So two issues in the behaviour:
- welcome screen -> log in with the phone -> "verify you are not a robot" -> redirects to the initial welcome screen
- not redirected to the code input page

**Comment by svscorp** [comment]
Interestingly, when I am testing using the general debug/test mode (in the browser) everything works fine, and there is no "verify you are not a robot" intermediate page.

**Comment by thealbertodelrey** [comment]
I'm having the exact same issue. The one difference I have is I don't even get a code. This issue is still persistent. @rzambroni If you could help guide me, much appreciated.

**Comment by aaksa** [comment]
Hi @rzambroni  @Alezanello , I’m still experiencing the issue. Here’s what I’ve done so far: enabled Push Notifications, enabled App Check, and uploaded the APNs certificate to Firebase.
