### ISSUE TITLE
Dashboard unavailable

### ISSUE THREAD

**Issue by mario-angelino** [FlutterFlow/flutterflow-issues#3003]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to access my dashboard, but the wait icon keeps spinning, and nothing happens.

### Expected Behavior

access my dashboard

### Steps to Reproduce

1. Access: https://flutterflow.io/
2. click sign in
3. nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No code appears

### Context

It doesn't allow me to access my dashboard

### Visual documentation

No images

### Additional Info

No additional info

### Environment

```markdown
- FlutterFlow version: 3.19
- Platform: windows
- Browser name and version: Chrome and Edge
- Operating system and version affected: 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @mario-angelino, the issue you are describing seems to be specifically happening to you as we can't replicate it on our end. <br>Would you mind trying on either the macOS or Windows apps to see if this is something related to your browser? cleaning up the cache or trying to open FlutterFlow on incognito mode might also help.

Do you see any error logs on the developer console of your browser? that might also give us some clues about the issue.

Thanks./

**Comment by mario-angelino** [comment]
Thank you for your attention. 
It seems like everything is back to normal this morning.
