### ISSUE TITLE
Failed to upload assets anywhere in Windows Desktop Application

### ISSUE THREAD

**Issue by gghez** [FlutterFlow/flutterflow-issues#3004]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whatever the page where an asset needs to be uploaded, the button asking to choose a file from my computer disk when selecting the file, the loading indicator never stop spinning, nothing can be uploaded. It only works if I use the Web Application online.

### Expected Behavior

I think it should work...

### Steps to Reproduce

1. Go to Settings
2. Try upload favicon for application in Web Deployment for example
3. Choose image from disk
4. Load spinner never stop and image is never take into account

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

sdc

### Context

I am forced to switch back to Web Interface which is annoying for many reason including screen recording and other conveniance reason for my day to day work.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6266247/b3c90347-20fb-4b70-8347-4faf06ee47b4)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6266247/f052585f-3519-4981-9d78-81043a108a35)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6266247/54aac735-4d05-40b5-a0b9-c79b6dff019b)

### Environment

```markdown
- FlutterFlow version: v4.1.53+
- Platform: Windows Desktop
- Browser name and version: Desktop Application
- Operating system and version affected: Windows 11 Pro
```

### General

- [X] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by gghez** [comment]
I need to precise that I am in a Pro trial version and this kind of first release bug is not what I expected...

**Comment by rzambroni** [comment]
Hi @gghez, thanks for the report, this is a known issue and has been reported a few times already. It is already on the team's backlog to be fixed.

As a workaround you could use the web app to upload the assets. 

Thanks!
