### ISSUE TITLE
FlutterFLow RazorPay integration :  error message "Could not create the order", status: "ABORTED"

### ISSUE THREAD

**Issue by natarajinnavoto** [FlutterFlow/flutterflow-issues#3006]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Getting the below error "Could not create the order status ABORTED "
The request indeed has the below data
   {data: {amount: 2, currency: "INR", receipt: "12345", description: "Gratis Razorpay"}
     amount: 2
     currency: "INR"
     description: "Gratis Razorpay"
     receipt: "12345"
Response 
error : {message: "Could not create the order", status: "ABORTED"}
message: "Could not create the order"
status : "ABORTED"

Note: i do have asked the same community questions https://community.flutterflow.io/ask-the-community/post/flutterflow-integration-with-razorpay-in-processing-state-and-the-status-0wY84L5tWDfJOSF

### Expected Behavior

The Razorpay integration should succeed with the payment gateway interface but it is stuck in processing screen

### Steps to Reproduce

What have you tried so far?
1) ) In FlutterFlow enabled the Razor Pay Payments and Update the Test & Production API Credentials
2) Razorpay was configuted for payment and have UPI/credit/debit/QR code payment modes acticvated, tested with QR payments (earlier as well)
3) Razorpay : Have enabled TestMode and now the system shows that " YOU'RE IN TEST MODE"
4) I did try and look at the error and it's in this specific section of the code
5) In the front end the razorpay button is just in processing state for a long time.

The google cloud function testCreateOrder has a runtime of Nodejs 18

File : index.js

Code section of the issue : 

async function generateOrder(data, isProd) {
  const razorpay = new Razorpay({
    key_id: keyId(isProd),
    key_secret: keySecret(isProd),
  });
  //console.log(data.amount, data.currency, data.receipt);
  try {
    const order = await razorpay.orders.create({
      amount: data.amount,
      currency: data.currency,
      receipt: data.receipt,
    });

    return order;
  } catch (err) {
    //console.log(data.amount, data.currency, data.receipt);
    console.error(`${err}`);
    throw new functions.https.HttpsError(
        "aborted",
        "Could not create the order",
    );
  }
}

Updated the necessary screenshots in context

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcjfz89NrsBE0Jf9bflKoCERC182TLJEoetxc0gbfe/4E7MifuLSYRNVUtSzaHxmEEybjj4z/871iPD1KsAnMgqrbph9zbtybRPPbHugR7rRPLiKPEQkHcBUJ0iP4Z2FhhR4GO1oWWQQ3WaqHt6+dz6Cf9qOYwx5e6fDbOY=

### Context

I am not able to integrate RazaorPay as per the documentation given in flutterflow  . Apologies if i have missed any steps i thik i did review the steps more than once https://docs.flutterflow.io/actions/actions/integrations/razorpay-payment

![FlutterFlow-Payload](https://github.com/FlutterFlow/flutterflow-issues/assets/96973739/f27079ec-a225-4f5a-9a09-f5d7def415ea)
![FlutterFlow-Razorpayconfig](https://github.com/FlutterFlow/flutterflow-issues/assets/96973739/9b9c48fe-f115-44ac-b800-bff73f420c0a)
![Flutterflow-Razorpay-error](https://github.com/FlutterFlow/flutterflow-issues/assets/96973739/5552de11-3ab4-45ca-a018-8de6c18678a4)

### Visual documentation

https://docs.flutterflow.io/actions/actions/integrations/razorpay-payment
https://docs.flutterflow.io/actions/actions/integrations/razorpay-payment
https://docs.flutterflow.io/settings-and-integrations/in-app-purchases-and-subscriptions/razorpay
https://razorpay.com/docs/payments/payments/test-upi-details/
https://razorpay.com/docs/api/orders/create/
https://blog.flutterflow.io/accept-payments-in-your-flutter-app-using-razorpay/

### Additional Info

https://community.flutterflow.io/ask-the-community/post/flutterflow-integration-with-razorpay-in-processing-state-and-the-status-0wY84L5tWDfJOSF

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.53+ released May 16, 2024
- Flutter version is 3.19.1
- Project ID: gratis-v1-dyjw52
- Platform: Android
- Browser name and version: Google Chrome Version 124.0.6367.60 (Official Build) (64-bit)
- Operating system and version affected: Linux/Ubuntu 24.04LTS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by natarajinnavoto** [comment]
Has anybody able to look at this issue ?

**Comment by rzambroni** [comment]
Hi @natarajinnavoto, we were trying to replicate this issue but we are unable to do so, it seems to be working fine. We tested in Android, and IOS. Were you  testing on Web? I believe web is not yet advised for the integration with RazorPay but i'm checking.

**Comment by natarajinnavoto** [comment]
> Hi @natarajinnavoto, we were trying to replicate this issue but we are unable to do so, it seems to be working fine. We tested in Android, and IOS. Were you testing on Web? I believe web is not yet advised for the integration with RazorPay but i'm checking.

I did generate an APK and installed it on an Android 12 and then checked, let me check again and get back.

**Comment by abhibalani** [comment]
@natarajinnavoto Did it work with the APK?

**Comment by natarajinnavoto** [comment]
For me when i had built the APK  and tested this flow did not work for me. Even through i had given detailed inputs some how flutterflow team was not able to replicate the issue.

**Comment by abhibalani** [comment]
@rzambroni I tried with apk. It is not working. 

I thought google auth was the issue. But I downloaded the APK, added the fingerprints to firebase to make the auth work on phone. **But still getting "could not create order, aborted" error.** 

Here's the log from my phone (mirrored to android studio):

![Screenshot 2024-07-01 1940291](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/f256361c-ee9e-4f1a-91a6-5067c5f7d255)

Here's the error screenshot from running the product on local on desktop flutterflow app.

![Screenshot 2024-07-01 202120](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/154f56f0-0cb8-4e82-b1de-c11c6904a689)


Here's the log from the cloud funtion:

![Screenshot 2024-07-01 202542](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/119f347e-7215-4091-9aab-18a8d83a5674)

Please help resolving this. Development is blocked because of this.

**Comment by abhibalani** [comment]
I have tried calling the test order API from Razorpay API collection and by directly running the testCreateOrder cloud function curl with the same credentials. 

Same json works via razorpay API and fails from cloudfunction. There is some issue in the cloud function for sure.

**Comment by pratit989** [comment]
Has anyone found a resolution? I am facing the same issue
