### ISSUE TITLE
Designer shows old code and loose my work

### ISSUE THREAD

**Issue by cdorde** [FlutterFlow/flutterflow-issues#3007]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Last night I export application from web designer and publish app on web and mobile phone. This morning when I open desktop designer app code was from 24th of May not from yesterday.
I have all versions of app exported as zip file but I can not take back code to desginer.

### Expected Behavior

Designer should never loose code.

### Steps to Reproduce

1. it is imposible to reproduce issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk+fqx4ZPvsNC7a6Jc+5WjWEWOUMcTZM3lOsYGAocIbXmP7M+OuPUaXdtONe8S39EHFGlklo0zOjuk+HXIMY7GzSuGdx607tIbz3gXTmRabKnBbu8YUdQI+dmFXWM16WFuRNAPrdvWGQO70+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I loose my code and I have to do again same thing but it is hard to remember all changes. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6882306/a07cea1b-edf9-402f-a7b7-ff61f7aea536)

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Web, Mobile
- Browser name and version: 
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [X] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [X] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hi @cdorde, so sorry you had that issue. Given the fact that the problem is not replicable there is no much we can do from here, my recommendation is that you follow-up with our support team to see if the problem can be resolved.

You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

Thanks!

**Comment by lleo132** [comment]
I have the same problem, when making changes in the Windows version I later open the web version, the changes are lost. Working on collaborative projects is even worse
