### ISSUE TITLE
CheckboxListTile Fails to Toggle State with SQLite Backend in FlutterFlow

### ISSUE THREAD

**Issue by dadevarzan** [FlutterFlow/flutterflow-issues#3008]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When generating a dynamic list of CheckboxListTile widgets through a backend query from SQLite in FlutterFlow, tapping on the checkboxes does not update their state (i.e., they do not get checked). This issue does not occur when using the same widget configuration with a Supabase backend, where the CheckboxListTile functions as expected.

### Expected Behavior

The CheckboxListTile should toggle between checked and unchecked states upon user interaction, consistent with the widget's intended functionality. This behavior should be independent of the backend service used, whether it's SQLite or any other database.

### Steps to Reproduce

1. Start a new project or use the provided sample project: `test-checkbox-list-tile-438q5g`.
2. Create and populate a simple SQLite database with a basic table and sample records.
3. Enable SQLite integration and provide an appropriate identifier for the database.
4. Construct a read query for the SQLite database.
5. Design a blank page equipped with a ListView widget.
6. Insert CheckboxListTile widgets as children within the ListView.
7. Link the ListView to the SQLite read query via the backend query settings.
8. Execute the application on an Android device, specifically a Xiaomi Note 8.
9. Attempt to toggle the state of the CheckboxListTile by tapping on it.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tz/Hqx89gocNf7qr2a/pv9WQ5JnI/auYslutuTQsjHOquE6Qud+PBZXFJX/2iTQhcHmKZnjgI7t7ShvOTG+5cAE2IQ75j/6l6ZwzdfzuXeJjUPJOWOnJ6EeZRC2qB0JqOihNAObNfL3Mt3TuyB+i9cDXBNYTuNlcnB/GIBN75okq9HA/BUDhmtmNecCfn

### Context

This issue hinders the implementation of a multi-select list feature within the app. The expected functionality is crucial for user interaction, allowing for the selection of multiple options from a list.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/33172846/ba732af4-025f-4fcb-918b-f0c6d4882335

### Environment

```markdown
- FlutterFlow Version: v4.1.53 or later
- Platform: Mobile (Xiaomi Note 8)
- Operating System: Android 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @dadevarzan<br><br>I realized that the issue with your code is that you're not setting the actions for updating the values.<br><br>First, you'll need to set two update queries for updating the rows in your database.<br><br>Then, you'll need to associate those values with the actions of the CheckboxListTile (one for selecting the checkbox and the other for unselecting them).<br><br>Let me know if you have any questions.

**Comment by dadevarzan** [comment]
Thanks for the response @msusviela , I appreciate you looking into this!

While setting update queries for the database would work in certain scenarios, my specific use case doesn't involve directly modifying a Boolean field in SQLite.

Here's what I'm trying to achieve:

1. **Multi-select list:** I have a ListView populated with products from SQLite. I want users to be able to select multiple products using CheckboxListTile widgets and then add them to the cart.

2. **Group chat selection:** Similarly, I want users to be able to select multiple friends for adding them to a group chat via CheckboxListTile widgets.

In both cases, I need the CheckboxListTile states to reflect the user's selection but without necessarily persisting those selections in the SQLite database itself. 

Is there a way to achieve this behavior using CheckboxListTile widgets and potentially managing the selections locally within the app (e.g., in a separate list or state variable) instead of relying on the database boolean field?

I'd be happy to provide more details about my specific implementation if that helps.

**Comment by msusviela** [comment]
For that case, setting a local boolean variable should work.<br><br>You have to first load that variable with the sql call, maybe when you navigate to that page with the database value or by selecting a widget.<br><br>Then set the checkbox with that local variable.<br><br>Please then remember that you have to update the value of your database separately, maybe by having a save button that calls the update sentence
