### ISSUE TITLE
sodium_libs binding not supported in FlutterFlow

### ISSUE THREAD

**Issue by Hbz00** [FlutterFlow/flutterflow-issues#3009]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the sodium_libs package (version 2.2.0+10) in a FlutterFlow project, the application throws a JavaScript error when trying to initialize the Sodium library on an API interceptor. The error message is "Uncaught SyntaxError: Unexpected token '<' (at sodium.js:1:1)". This issue occurs on both Chrome and Edge browsers.

### Expected Behavior

The Sodium library should initialize correctly without any errors, allowing for the use of its cryptographic functions in the FlutterFlow project.

### Steps to Reproduce

1. Use this code on an API interceptor with the sodium_libs package (version 2.2.0+10)
@override
Future<ApiCallOptions> onRequest({
  required ApiCallOptions options,
}) async {
   debugPrint('test1');
    final sodium = await SodiumInit.init();
    debugPrint('test2');
}

2. Test it on test/run mode, both fail
3. Observe the JavaScript error in the browser console.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXzfLqx5dPm+ZE0KXId/lGpCUwFjMMbY0v0u0bFB40fe/tO7MxO+CkS0NKTNDnTH1LMGCgrGMDpcLFkd/qFfkoHyqCG6Zy0JVAdBbMUT+mVqqRDpeeVXBDM8dYI33C5MHYvCZvJslsWHAF7XGXNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to use the sodium_libs package to encrypt and decrypt data in a FlutterFlow project. However, the Sodium library fails to initialize, which prevents me from using its cryptographic functions.

### Visual documentation

![bug](https://github.com/FlutterFlow/flutterflow-issues/assets/85522322/69252d2a-9e68-4e16-8746-583664352cf7)

### Environment

```markdown
FlutterFlow version: v4.1.53+ (released May 17, 2024), Flutter version is 3.19.1
sodium_libs version : 2.2.0+10
Platform: Web
Browser name and version: Chrome 125.0.6422.60, Edge (latest version)
Operating system and version: Windows 10, build 19045.4412
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @Hbz00! Is the issue reproduced in the bug report code you shared? If you update the library to the latest version, the issue persists? Which action inside your app is throwing the exception?

**Comment by Hbz00** [comment]
Hello @paulperez-dev ,

The bug report code is not related to my problem, because I did not find a way to generate a bug report code concerning an API interceptor.

It is not possible to update sodium_libs, because it would require updating synchronized to a newer version than 3.1.0+1, and that is not up to me. I tried to downgrade sodium_libs, but the error reported in the report still occurs.

The action in the app that throws the exception is sending an HTTP POST request after clicking a button. I tried removing the API intercepor from the endcall API concerned, and the request is sent. The problem is therefore in the initialization of sodium_libs in the API interceptor

Thanks

**Comment by paulperez-dev** [comment]
Hi @Hbz00! I was looking into the package and found this: 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a5f6699f-aeb8-4fe4-826b-062f8210c455/c1f93fad-33cd-4db1-a25a-f3186252d6c7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNWY2Njk5Zi1hZWI4LTRmZTQtODI2Yi0wNjJmODIxMGM0NTUvYzFmOTNmYWQtMzNjZC00ZGIxLWEyNWEtZjMxODYyNTJkNmM3IiwiaWF0IjoxNzIwODgzNzQ2LCJleHAiOjMzMjkxNDQzNzQ2fQ.uMKD2q7VEsI9AfgO0X8gT0xJVnBAZIm9fjVzGi_f6gE " alt="image.png" width="799" height="238" />

Because at this moment we can't run commands in FF, you won't be able to run the app on a browser. Please try using local run on a smartphone or simulator and verify if the app runs.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
