### ISSUE TITLE
Custom Widget Compilation Error

### ISSUE THREAD

**Issue by vairagadeharshwardhan** [FlutterFlow/flutterflow-issues#3010]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After removing all errors in developing a custom widget in Flutterflow an unknown error comes. 

### Expected Behavior

Either tell me what is the error or update the compiler for more robust action. 

### Steps to Reproduce

1. Create a new custom widget 2. add boiler plate 3. compile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESjMmB+cpgrsQF0LncacZqhQMkQzM6bZI7ku1EdwEhfbaqELM2dsn8ZRNLYteET39EClmJuGYBp/DQkeOWGvcVOSWrR65S+r5XQQ3gYECibpSUDKuKekclMJlTIHbGyLWNoBZ7LuttWU5k1HGmG/CdG3qCf9qOYwx5e6fDbOY=

### Context

I can not live with it. It almost took 2 weeks to get one custom widget in FlutterFlow. I want to develop custom widgets.1 . date range picker 2. Google map Polyline route map.

### Visual documentation

![Screenshot 2024-05-30 093648](https://github.com/FlutterFlow/flutterflow-issues/assets/40453462/16351f00-c017-4310-84c4-eceb86335525)

### Environment

```markdown
- FlutterFlow version: 4.153+
- Platform:
- Browser name and version:
- Operating system and version affected: windows 10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by dennisdc** [comment]
same problem here

**Comment by msusviela** [comment]
Hi @vairagadeharshwardhan. I tried to replicate this from a blank project but couldn't reproduce the issue.

I checked your project, but the bug code you provided doesn't contain any custom widgets, so I could not check on that.

Can you provide me more insight into the custom widget that you're trying to implement? Does the issue still persist on the new version of FlutterFlow (4.1.54)

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
