### ISSUE TITLE
"Not In" Filter is not working in single query

### ISSUE THREAD

**Issue by abnercasallo** [FlutterFlow/flutterflow-issues#3011]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using a query with a "Not In" filter, it's a single filter, but I get the message: "You can't use the not-in operators in OR queries", which doesn't make much sense.

In my previous projects that already have the "not in" built in it works without problems.

### Expected Behavior

A single filter with "not in" should be able to be used without problems.

### Steps to Reproduce

1. Create a List View, 2. Add a Query Collection (List of Document Type) and add a single filter with "Not In"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekvHf8YlIj70E+qrXLPowrwMwJHI/auYvte5+d0shNb7pPe0cfcykTBdLYtSoTW1EIlD9nT4Dw637kvLtL/Y4ORCtbbU61oRXQTyXUmKmbrbQCZeCZXNBBfxhJnKe4bWFsCRCC7NhWEIs2U6QPvCrG3qCf9qOYwx5e6fDbOY=

### Context

I can't filter with "Not In" in Flutterflow, I've tried with different cases

### Visual documentation

![ISSUE NOT IN](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6da94ad-d89e-4d69-8b40-2bbd5c021ab1/aceb71a8-9457-434a-a5b0-43f60938ca09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNmRhOTRhZC1kODllLTRkNjktOGI0MC0yYmJkNWMwMjFhYjEvYWNlYjcxYTgtOTQ1Ny00MzRhLWE1YjAtNDNmNjA5MzhjYTA5IiwiaWF0IjoxNzE3MDc0NzUzLCJleHAiOjMzMjg3NjM0NzUzfQ.cQhroiQIlFJmvq-eAPEbA_w243Y6ENy1-rqdrbwAqKE)

### Additional Info

Not more

### Environment

```markdown
- FlutterFlow version: 4.1.5.3
- Platform:Web
- Browser name and version: Edge 125
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] \~100% of the time
- [ ] \~50% of the time
- [ ] \~10% of the time
- [ ] \~1% of the time
- [ ] Very rarely or only encountered once

**Comment by isaachamm** [comment]
Having the same problem here, can't find a workaround.

**Comment by waymorphood** [comment]
same

**Comment by victoriahuang1** [comment]
Hi all, we will be putting out a fix soon. For now, you can switch the "OR" to an "AND" and then apply the NOT-IN filter
