### ISSUE TITLE
Not able to upload media from the flutterflow desktop app in the assets tab.

### ISSUE THREAD

**Issue by pireslopesvinicius** [FlutterFlow/flutterflow-issues#3012]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to upload media assets file from the flutterflow desktop windows app it doesn't load.

### Expected Behavior

Be able to upload media files from the desktop version too, because in the web it works.

### Steps to Reproduce

1. Create project in desktop version
2. Try to upload media files

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raCsofePrOpkAf8/7UFtUOMDgd1VUeGKKknwX/Mr7joTtNPUCA02aGKplzpNTEQ3/d3K7RcnTBa63b3EnI/FbGkik1MO3ogkkHNtvLnMt22WmAd+tYBfBJp/1C0UdOeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Upload media files.

### Visual documentation

It's a simple bug, not much to show.

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hi @pireslopesvinicius, thanks for the report, this is a known issue and has been reported a few times already. It is on the team's backlog to be fixed.

As a workaround you could use the web app to upload the assets.

Thanks!

**Comment by pireslopesvinicius** [comment]
Okay, thank you!
