### ISSUE TITLE
Permissions messages in langages does not save changes

### ISSUE THREAD

**Issue by smkg75** [FlutterFlow/flutterflow-issues#3013]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I had a initial message that does fit with iOS permissions messages transparancy and when I try to change it in my app primary langages FlutterFlow doesn't save the change.
When I reload the FF page and when I deploy my app, the previous message is still there.
The message doesn't save even if we check the "fixed" value to prevent Google translate to erase the value.

### Expected Behavior

Save iOS permissions messages changes.

### Steps to Reproduce

1. Having a minimum of two langages (English primary, French second)
2. check the camera and the photo library permissions
3. Write the translation in iOS permissions langages
4. Try to change the english value after
5. Observe that it doesn't save

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tkc/qx891rtdc+Kr+bsBB/T0XQkM7bedEm+4bdwEaNuvxP+0APOLebXFITM+kSgo2fWKjpzgz0/SOvszIN/oEORKCQYQ9zbluWBbdXmelVc3WOqisRmt6AtpKCBzH4LbUqghCXe1Zc04H2GCUNe6tSjPbQLrSPjAFHfj/Ub/4jX/uQ0SLb3kNh1JWeC/v

### Context

This prevent me to publish my app to the App Store because of the App Store guidelines. It is really impactful because I cannot do any business right now !
![Screenshot 2024-05-30 at 13 58 12](https://github.com/FlutterFlow/flutterflow-issues/assets/146461253/88989b24-2f4d-45ac-9347-600db345bafc)
![Screenshot 2024-05-30 at 03 25 44](https://github.com/FlutterFlow/flutterflow-issues/assets/146461253/4eeb903b-63bc-4686-9b9a-721444568d97)

### Visual documentation

![Screenshot 2024-05-30 at 03 25 44](https://github.com/FlutterFlow/flutterflow-issues/assets/146461253/2f6a2892-f0f8-4da1-b633-9baa9fe3597f)

### Environment

```markdown
- FlutterFlow version: v4.1.53
- Platform: Web
- Browser name and version: Arc Browser Version 1.44.2 (50412) Chromium Engine Version 125.0.6422.112
- Operating system and version affected: macOS Sonoma Version 14.2.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @smkg75 thanks for your report. I'm able to change the language fine following your instructions. Could you please record a small video of how are you replicating this bug?

**Comment by smkg75** [comment]
Sure please see this loom video
https://www.loom.com/share/d5bed7b2bfb54a1c9e81b9e750207b9f?sid=4408a69c-ec19-4603-b5df-f07e1f043925
You can see that I reload the page and my changes are not saved. Same if I
deploy (web or appstore) before reloading the page

Kind regards
Sami Gomez

Le ven. 31 mai 2024 à 00:20, Ignacio Lauret ***@***.***> a
écrit :

**Comment by samimkg** [comment]
@ignalauret hi did you see the video?

**Comment by rzambroni** [comment]
hi @samimkg, 

I was able to replicate the issue you are describing. Will send it to the team so they can take a look.

Thanks for the report!

**Comment by smkg75** [comment]
Hi there, do you have any idea when this bug will be fixed?

I cannot publish on App Store and we are two weeks late because of this bug..

**Comment by smkg75** [comment]
Hi there, do you have any updates?

**Comment by lemon-software** [comment]
Hi, we are a member of Pro Plan,

We are rejected from iOS Submission because we can´t change the permission message for Camera and Photo Gallery, this is a BIG BUG, please we need resolve this.

@rzambroni @leighajarett

**Comment by Luditeker** [comment]
Hi, I have exactly the same issue. ios Messages for permission are written in 2 places : 
1st in App Settings / Permission. This text is not used in the app.
2nd in App Settings / Languages / iOS Permission Messages. This is the one that is used in the app. 

But When I change it, I leave the settings page and come back the new text is not saved and the old text is back. 

the issue is the same for each permission: Camera, Gallery, Location.

This is blocking my Apple review, so I cannot publish the App. Very problematic...

I need help.

<img width="1080" alt="Screenshot 2024-08-18 at 14 17 40" src="https://github.com/user-attachments/assets/0cb80f80-9811-4029-8f3f-86c343c40b9b">
<img width="1070" alt="Screenshot 2024-08-18 at 14 17 20" src="https://github.com/user-attachments/assets/4ca350ee-42ac-4e28-ac1b-9ec5bd4023d9">

**Comment by totalfootballyo** [comment]
we are pro plan users with the same issue. keep getting rejected. very frustrating. can you offer a workaround at least?
