### ISSUE TITLE
App state variable with enum property is not set

### ISSUE THREAD

**Issue by MrNaceja** [FlutterFlow/flutterflow-issues#3014]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an application that has an app level variable that is a datatype that has a property that is an enum, in the definition of this variable in the app state, even if you set one of the enum values, in the execution of the application the property is not defined.

### Expected Behavior

The property should be set since I set it manually by the app state, otherwise I'll have to do a workaround to set the enum property on the page's onLoad, which wouldn't be cool.

### Steps to Reproduce

1.Create an Enumerate with Two Options;
2. Create a datatype with a property of this type;
3. Create an app-level variable and set the value of this enum in the datatype property;
4. If you try to display the value on screen or toJson you will see that the property is not set.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTysmB389Iocdc+KnQb8dV/T06I0MdXOczitVEew4bCIj4BJYMYffCQFRtZMizaHNAfE2jhXIB+t7WjtnuG/cBITCrG6ZRyMxUZRPPbEyWMamYPqWNdnElO9FjCE/E36bQnyQkJvJZWk5g7DuHfNysQT6Cf9qOYwx5e6fDbOY=

### Context

I'm trying to create an application that has a datatyupe with an enumerable property and this variable should be set at startup because I use it to control the activation of a plan card.

### Visual documentation

![Captura de tela 2024-05-30 092422](https://github.com/FlutterFlow/flutterflow-issues/assets/71296941/d9527378-bbab-4d6c-8770-11edf7f522e3)
![Captura de tela 2024-05-30 092434](https://github.com/FlutterFlow/flutterflow-issues/assets/71296941/ef2de8af-3203-4190-854e-6890d1c7cd57)
![Captura de tela 2024-05-30 092459](https://github.com/FlutterFlow/flutterflow-issues/assets/71296941/df25ddeb-fd30-42ac-81c3-2c6f75e49ea4)
![Captura de tela 2024-05-30 092513](https://github.com/FlutterFlow/flutterflow-issues/assets/71296941/18e65223-80a6-42f7-9f37-55727abc5698)
![Captura de tela 2024-05-30 092547](https://github.com/FlutterFlow/flutterflow-issues/assets/71296941/c2cd169c-fe47-4c87-bcf9-22601fbed2be)
![Captura de tela 2024-05-30 092556](https://github.com/FlutterFlow/flutterflow-issues/assets/71296941/9850ee39-1b93-493f-b7ff-f223ceecb005)

### Environment

```markdown
- FlutterFlow version: v4.1.53+ released May 30, 2024
- Platform: Web
- Browser name and version: Microsoft Edge 125.0.2535.67
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hey @MrNaceja, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by MrNaceja** [comment]
According to the help of the support by email, it was verified that the problem was resolved. It's working properly again. Thank you for your attention 💜.
