### ISSUE TITLE
Audio recording breaks the compilation

### ISSUE THREAD

**Issue by ffmasterdev** [FlutterFlow/flutterflow-issues#3015]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

audio recording breaks apk compilation even in brand new project 

### Expected Behavior

audio recording actions must work as usual

### Steps to Reproduce

create new page, add start and stop audio recording ctions

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89godsG1qrxK8dAhQAkH1x/bZJEl9cbRgAgNZDzO7Qqeur+VEhaXt+7fXN+PVb8hlgf0t7siezPLcECBAeWQoNo/5FieArwc3GVWoyuCsy0eXB5J8pTIWrC0Z6C2RR+PvBvS1Vnw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I can't export apk for my existing project, where I use audio recording a lot

### Visual documentation

![2024-05-30 14 46 53](https://github.com/FlutterFlow/flutterflow-issues/assets/163732859/1ef550ae-3373-4686-9548-de8d8c48507e)

error code

### Additional Info

please update min sdk version to 23

### Environment

```markdown
- FlutterFlow version: 4.1.53+
- Platform: Web
- Browser name and version: Arc
- Operating system and version affected: macOs Sonoma 14.2.1 (23C71)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [x] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Deffer7** [comment]
++

**Comment by NikOlaiPRO** [comment]
I have the same problem in my project

**Comment by msusviela** [comment]
Hi @ffmasterdev<br><br>I wasn't able to reproduce the issue in the new version of FlutterFlow (4.1.54).

I saw you're using the the old version (4.1.53)<br><br>Can you let me know if this issue till persists for you?<br>If so, could you check the steps to reproduce you described and let me know if any detail is missing?

**Comment by sebastienetter** [comment]
same problem and error, unable to "Deploy to Play Store"

**Comment by msusviela** [comment]
Thanks @sebastienetter for the further information. I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by leighajarett** [comment]
So sorry you're dealing with this issue! Do you know when this issue started?

**Comment by sebastienetter** [comment]
@leighajarett May 29th

**Comment by leighajarett** [comment]
So you were previously able to export code with the audio recording action?

**Comment by Nikolausss1** [comment]
I faced the same problem. Previously, the APK was created, and on 30.05 it started giving an error. Even after creating a new project and adding an audio recording action, this problem persists

**Comment by sebastienetter** [comment]
@leighajarett i don't use "Export Code", just the button "Deploy to Play Store" which is broken...

**Comment by aakashnp** [comment]
I am facing the same issue here. I need to downlaod the apk it breaks the compliation. Previousy i had downloaded my apk more than 10 times and had no issue. Need to fix this issue asap. May be it becauase of your new update. I hope you guys are working for it.
![Screenshot 2024-06-02 153920](https://github.com/FlutterFlow/flutterflow-issues/assets/171484624/085fab1f-8c8d-4ad8-a6a8-0054688ce9d0)
![Screenshot 2024-06-02 153958](https://github.com/FlutterFlow/flutterflow-issues/assets/171484624/c1783a63-5838-4410-9b54-01a0fe6f22e6)

**Comment by Shyam2496** [comment]
> So you were previously able to export code with the audio recording action?

yes, it was working fine until May 29th, the issue started on may 29th
