### ISSUE TITLE
Text widget Max Lines set from variable doesn't work

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#3016]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I specify "Max Lines" value for Text from variable, then this valueis ignored. In generated code there is no maxLines parameter.

### Expected Behavior

Setting Max Lines from variable works.

### Steps to Reproduce

1. Create a page, add a Text component. Set Max Lines to variable

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2ad0abfb-a1bf-4229-878c-4aa60bb9a430/6c6f537c-6da5-46fd-839a-dc93f4f0ab5b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYWQwYWJmYi1hMWJmLTQyMjktODc4Yy00YWE2MGJiOWE0MzAvNmM2ZjUzN2MtNmRhNS00NmZkLTgzOWEtZGM5M2Y0ZjBhYjViIiwiaWF0IjoxNzE3MDg5Nzk0LCJleHAiOjMzMjg3NjQ5Nzk0fQ.rGCnHjf5ISCS4tKTWP_hx3OFhFrAKEt2-Z66NO-HjqA)

2. See the generated code. You'll see that no value is set for maxLines.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1525c898-c58c-4bff-a3ab-c95d5275842a/55592c30-6972-4d4b-9951-067539df9668?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNTI1Yzg5OC1jNThjLTRiZmYtYTNhYi1jOTVkNTI3NTg0MmEvNTU1OTJjMzAtNjk3Mi00ZDRiLTk5NTEtMDY3NTM5ZGY5NjY4IiwiaWF0IjoxNzE3MDg5Nzk0LCJleHAiOjMzMjg3NjQ5Nzk0fQ.85kuTMGBiDFcjJpHJzT5Yr7k6OQ9H2FMxlMpZH5YnTw)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEek8nqy89JpbxK7Yf6avpVnQMxJ1gjbJ0vhMIbWQ0jfL6tPJotbuvRanBVYN/iYAhID2CailsG+sL2j9nhK/Q4YA+EQ5RJzalqSg7gLU6RVaanCrWwRXF5P5pYGXaa07esnghSPbBfWGMsig/GSw==

### Context

I'm trying to implement "see more/see less" feature for long texts.

### Visual documentation

See "Steps to Reproduce"

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.53+
- Platform: Web, Android, IOS
- Browser name and version: Windows Desktop App
- Operating system and version affected: Windows 10
```

###

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by NLDylan** [comment]
Also have this issue on my projects.

**Comment by giladresisi** [comment]
I'm also experiencing this in my project, very annoying... And same for max characters BTW (haven't seen an open bug for it, using this one...)

**Comment by eduardmn** [comment]
i have the same bug. can you guys fixit?

**Comment by Alezanello** [comment]
Hello everyone,

It looks like this issue was resolved some time ago. Could you please confirm if everything is working fine on your end?

Thank you!
