### ISSUE TITLE
Transparent Widget Background NOT matching with Canvas Color - Version 4.1.54 (4.1.54)

### ISSUE THREAD

**Issue by darthcreator** [FlutterFlow/flutterflow-issues#3018]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Components with a transparent background have a persistent white background, regardless of the underlying canvas color.

### Expected Behavior

Widgets with a transparent background should show the underlying canvas color.

### Steps to Reproduce

1. Create a new project
2. Create a new component
3. Background of component will be white, regardless of canvas color

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89god8G+7XucMdQhQMkQzM6bZI7ku1EdwEhfIzqPIYUfc/ObltLYtenf21YIk2jgl0K+N7WuOHLCfI3NTeBUa49yZRXQTnzTmOnbq66PbiOS3J7M+5bfH6x5sHQqxIlHMpeSVof7zube/CNG3qCf9qOYwx5e6fDbOY=

### Context

This is very disorienting and makes it extremely difficult to develop a component with a container that has a white background color, because there is no boundary between the container background color and the widget container background color.

This occurred after downloading and installing the latest version 4.1.54 (4.1.54) on MacOS. It also appears to be affecting web.

### Visual documentation

![widget-annotated](https://github.com/FlutterFlow/flutterflow-issues/assets/44907769/ab9e6efc-9169-4fa8-ad9d-d669c7dd334b)
![widget-with-white-background](https://github.com/FlutterFlow/flutterflow-issues/assets/44907769/03b454ab-8d46-48c5-998f-00cadb010fcf)

### Environment

```markdown
- FlutterFlow version: Version 4.1.54 (4.1.54)
- Platform: MacOS and Web
- Browser name and version: Google Chrome Version 125.0.6422.77 (Official Build) (x86_64)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hey @darthcreator

I wasn't able to reproduce the issue. Is this still reproducible in yours? I tried to run the project with the bug code you provided but it's just an empty component. If the issue still persist, could you give me more context and check if you're missing any detail in the steps to reproduce? Like for example, what do you have inside the component (I tried creating a component with a Container with a column with a text and an image inside, but it worked fine).

**Comment by msusviela** [comment]
The issue persists while the component is being created as shown in the video or it also persists on run mode?
