### ISSUE TITLE
Nullable page state variable of custom type stopped working after today's FF update

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#3019]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I create a page state variable of custom data type and check "Nullable" on it, in the generated code this variable is not nullable, that leads to further crashes when I try to assign nullable page parameter (that is actually nullable) to this variable. It worked until this evening's update to 4.1.54+

### Expected Behavior

Nullable state variable of custom type is actually nullable (with question mark) in generated code.

### Steps to Reproduce

1. Create a custom data type.
2. Create a page with nullable state variable of this data type.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/a55723b3-0017-42c8-933d-aaec1935ba4a)

3. See the generated code (model):
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/17198994-faa0-4a37-826c-e169da0cd3ac)

The variable nullableState is not nullable...

When later I try to assign actually nullable page parameter to this variable, app crashes, if I pass null to the parameter:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/e6ed4956-334d-4b68-aee8-6ab28b93a3bf)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEek8nqy89JpbxK7Yf6avpVnQMwJ0QlUIInj+0bWRMhfYjyPewIPMylblRLYtegfWw/eFr+pEgG+crUv/HXCuwrMk2dQIs4+JRXQQnxQTutVK6UDbW0YXdRN59RCBGP4aS02R1DPfh2W3w/wGWQPPCrG3qCf9qOYwx5e6fDbOY=

### Context

This is a BLOCKING issue in my case because in many places I pass nullable parameters of custom types to pages and then assign them to "nullable" state variables which is now leads to many crashes across the application.

### Visual documentation

See above.

### Environment

```markdown
- FlutterFlow version: 4.1.54+
- Platform: all
- Browser name and version: FF windows desktop App. Chrome browser
- Operating system and version affected: Windows 10
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by vanya97-potapov** [comment]
Same here!

**Comment by MartinLockheart** [comment]
Dealing with the same issue.
