### ISSUE TITLE
Flutterflow Audio Recording Action Bug

### ISSUE THREAD

**Issue by Shyam2496** [FlutterFlow/flutterflow-issues#3024]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

apk build failure on adding an 'Audio recording action'

### Expected Behavior

the apk should be built without any issue when the audio recording action is used

### Steps to Reproduce

Create a new project, add an 'start audio recording' action to a widget. now try to download the apk.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l+fl4ot2obxY1arPbcBFoCMXQls7a50zicJTZw08J5TUB+x/evz4UBJoTbyndgk/PVr8uDsKzM7Im9z1U/ArAzGaG498/qttWjnieHm5Rr6nC8ywRWpUGshUC1SP56SnrRVSJbN2WVlhw2eHe/K9a3fcHrraDm0dA/n9CK7XvgfuQ0SLb3kNh1JWeC/v

### Context

apk build fails

### Visual documentation

![Screenshot 2024-05-gy](https://github.com/FlutterFlow/flutterflow-issues/assets/123336376/d4573953-b1ed-42c4-8ded-3417e68422dc)
![Screenshot 2024-05-31 0ghgh](https://github.com/FlutterFlow/flutterflow-issues/assets/123336376/40214afb-c2d4-4a51-a531-7463c16406cf)

### Additional Info

Removing the audio recording functionality temporarily to test if it resolves the build issue is a practical and logical troubleshooting step. This process, known as isolating the problem, can help confirm whether the `Record` library or related audio functionalities are indeed causing the configuration conflicts related to `minSdkVersion`.

### Steps to Proceed:

1. **Disable or Remove Audio Recording Features Temporarily**:
   - Temporarily comment out or remove the code blocks related to audio recording in your FlutterFlow project. This includes any widgets, functions, or references associated with starting or handling audio recording.

2. **Build the APK**:
   - After modifying the functionality, attempt to build the APK again. This will help determine if the issue was specifically associated with the audio recording capabilities and the `Record` library.

3. **Check the Build Outcome**:
   - If the APK builds successfully without the audio recording features, it's likely that the error is tied to these components or one of their dependencies needing a higher `minSdkVersion`.
   - If the error persists, it indicates that the problem might lie elsewhere in the Android-specific configurations or another unrelated dependency.

### If the Error Resolves:

- **Consider Alternative Libraries**: If you pinpoint that the `Record` library or similar is the cause, look for alternative packages that support a lower `minSdkVersion` if raising the `minSdkVersion` isn't an option for your user base.

- **Request Feature/Support from FlutterFlow**: Since FlutterFlow controls much of the configuration, asking them for a way to adjust the `minSdkVersion` or for any advice on handling such dependencies would be beneficial.

### If the Error Persists:
- **Further Debugging Required**: Continue investigating other areas that might cause the error, including other dependencies, and recheck the entire configuration through the FlutterFlow environment.

By following these steps, you should be able to clarify the cause of your build issues and decide on an appropriate solution. Good luck!

### Environment

```markdown
- FlutterFlow version: v4.1.5
- Platform: Android & iOS
- Browser name and version: Chrome Version 125.0.6422.112
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by sebastienetter** [comment]
Same problem on my project

**Comment by Shyam2496** [comment]
What should we do? It seems like the Flutterflow team is not gonna address this issue anytime soon. Please share if you have any alternative ideas to implement the same functionality and I will try it.

Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ShoyaHirata** [comment]
Same problem on my project.^^;;

**Comment by msusviela** [comment]
Closing this since it's a duplicate.<br><br>You can follow the issue here:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3015](https://github.com/FlutterFlow/flutterflow-issues/issues/3015)<br><br>We've been able to replicate this and currently our ENG team is looking into it.

**Comment by leighajarett** [comment]
We are actively working on resolving this issue!
