### ISSUE TITLE
iOS target version prevents app store upload

### ISSUE THREAD

**Issue by Lucheti** [FlutterFlow/flutterflow-issues#3025]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i cant upload to app store.

### Expected Behavior

i want to be able to upload to app store from within fluuterflow

### Steps to Reproduce

create a custom widget
add the dependency --> google_maps_flutter: ^2.0.0
create a bare simple map
try to publish to app store

Build fails with error:
[!] CocoaPods could not find compatible versions for pod "google_maps_flutter_ios":
  In Podfile:
    google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)

Specs satisfying the `google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

Build failed :|
Step 6 script `Install pods` exited with status code 1

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhcr15YhNoeZE1qnUL8JvmWEwGUALa+dI0tZ+TQ0jF5D4EIkuZOOkYhBvTeKzaHxcBmCGgnIB//T9v+LhLMEnBwyac6ZmyM1qVRPPbFq5R8XRBqWaT3EnM91XChGv0re7kyJTIu5ZZXg/7V+qBNy+az2Cf9qOYwx5e6fDbOY=

### Context

i have downloaded the files to my local, and went to do pub get. 
got an error stating that the target version of my ios app was off. 
went on to see and it was set up for iOS 13 (current 14.7)
bumped the target version to iOS 14 and it works like a charm but since i cant push any file to flutterflow is imposible for me to solve this other than deploying from out side flutterflow, but isnt that the whole point of the pro membership?

### Visual documentation

<img width="1726" alt="Screenshot 2024-05-31 at 3 29 22 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/32769818/4381b550-2249-4332-84b4-6303dd35c8fb">

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: mac os 14.4.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @Lucheti! Can you please trying using version **2.6.0** of the **google_maps_flutter** package? **2.0.0** is an old release and **2.6.1** is targeting iOS 14.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
