### ISSUE TITLE
Editor Errors not redirecting to the error widget/page upon click

### ISSUE THREAD

**Issue by Maazkhalid47** [FlutterFlow/flutterflow-issues#3026]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get errors on the editor, they are displayed by name and type of error when the dropdown is opened, but they donot redirect you to the part where the error is anymore, you have to check each page/parameter/action/widget if its red there.

### Expected Behavior

Redirect to the error page/parameter/action/widget

### Steps to Reproduce

1- Create a project
2-Create an action on the first page and leave it incomplete
3-Navigate away from the page
4-Click on the appearing error
5-The editor doesnt take you to the error making implementation

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi/Ll5Ypgrs9J1s/Ic/oxnSQUC24+aJE80spBZywgfZzzBLN/fPfQP1JoXd+hT2xiOGKMp14Hwe+NkfLpEvlePRKWc6Jq1bhyWAn/Ul6uMamTF7WORHJfEdJmJ2an0bu7gQp5C/pZdCVi2DuyAPDKXhTsGOfBDGowSq/LZO4=

### Context

Every project I am working on gives out errors which is obviously normal, but clicking on the error should navigate the editor to the error making widget, since that is not happening I have to check multiple each instance the error could refer to.
e.g. Custom action argument "businessLocations" is not set properly. Now I have to check the whole project for events that use this custom action.

### Visual documentation

<img width="330" alt="Screen Shot 2024-05-31 at 15 33 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76614672/16a82446-04c5-47f0-9523-968e3830944a">

### Environment

```markdown
- FlutterFlow version: v4.1.53+ 
- Platform: editor problem
- Browser name and version:Chrome
- Operating system and version affected: MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by icarusphoenixdragon** [comment]
Same issue.

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by icarusphoenixdragon** [comment]
Great. Thank you. When it's working, it's a great tool! Looking forward to resolution.

**Comment by leighajarett** [comment]
This should be resolved now!
