### ISSUE TITLE
Error: Undefined name 'FirebaseFirestore'.

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#303]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I am trying to work with reference documents in custom functions.  I get a compilation error when trying to test it using FF Test.

## Current behavior (required)

I get a red box: Error: Undefined name 'FirebaseFirestore'.

## To Reproduce (required)

```
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

DocumentReference? returnNonAuthfromPair(
  List<DocumentReference>? userPair,
  DocumentReference? authUser,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // return element from userPair that does not equal authUser
  if (userPair == null) {
    return null;
  }
  if (userPair.first == authUser) {
    return userPair.last;
  } else {
    return userPair.first;
  }

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

```

1.  Create the function
2.  Create a test with two values of User collection in the userPair, and one matching in the other
3. Run test
4.

## Context (required)

I need to perform additional queries because the FF / Firestore queries are limited.  In this case, I need to check if two different User Document References exist within a field that is of type LIST

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop):  Web on MacOS
* Browser name and version: Chrome 
* Operating system and version (desktop or mobile): Desktop

**Comment by skipper113-FF** [comment]
Hi,

Thank you for your inquiry.
On a blank slate project without any other functions, I am able to return a authUser match from a List? userPair.
Quite typically, bugs that exist in other custom functions within the same project can halt tests from finishing properly.
Please kindly reconfirm whether there are potential bugs hidden in other functions.

**Comment by hariprasadms** [comment]
Hi, Closing the issue as it is inactive for a long time. Thanks
