### ISSUE TITLE
Custom Data Struct Issue When set to Nullable

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#3031]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="307" alt="Screenshot 2024-06-01 at 12 01 48 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/56119343/9d148f6a-84af-46dd-9f9a-edd7306c1e98">
It is Asking to set the state variable even when it is set to Nullable

### Expected Behavior

It shouldn't ask to set a default data when set nullable. It was working few hours age

### Steps to Reproduce

Create a new Page
Create a Struct
add a page state of type of custom Struct
set it to nullable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4eiMjfsIh2rscA0a6Jd/panjwRQ0x6RY0vjuwacAw0IYOvB7McY+j+QHZVOMO/dFY3OlmI8Tsep/ONv+z2UfktPiisRqY9zs5pEgLyfF+gMKXXBquWRHNPM9FVGUeHzbaRnhZ4BOpqL0VmwVyqF/KuYBbYK72zPlYaQvGJNp/7kXyRASLOXn0Jg1ZSfCvr

### Context

Unable to Even Publish it to web and unable to download apk getting below errors
<img width="588" alt="Screenshot 2024-06-01 at 12 01 26 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/56119343/e9cdb625-f039-4975-b1e8-d917fe54ee29">

### Visual documentation

Not Available

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Desktop
- Browser name and version: Chrome
- Operating system and version affected: MAC OS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by malbrecht0792** [comment]
I'm getting this error too with the new FF update

**Comment by microprocessltda** [comment]
Same here

**Comment by ValetCEO** [comment]
Same here
![Uploading Screenshot 2024-05-31 at 19.52.43.png…]()

**Comment by MendesCorporation** [comment]
same here

**Comment by GamxXamg** [comment]
Broken here too !!!

**Comment by rzambroni** [comment]
Hey Everyone! thanks for the report, i sent this to the team so they can take a look, we will keep everyone posted here.

**Comment by fafa16** [comment]
same here too

**Comment by arniigreat1** [comment]
3rd this. I have this bug now too

**Comment by agreaves** [comment]
Apologies folks! This issue will be fixed within the next half hour.

**Comment by adriandcg** [comment]
I have the same issue in multiple projects that use Data Types, 13 hours ago all was working fine

![CleanShot 2024-05-31 at 13 52 46](https://github.com/FlutterFlow/flutterflow-issues/assets/42681941/a9b4f0fd-8ff1-489c-be7f-8090e49d2721)

**Comment by luxthecreator** [comment]
Same issue today.

**Comment by GamxXamg** [comment]
It looks good now, thx FF team !

**Comment by adriandcg** [comment]
The issue seems to have been solved, thank you very much

**Comment by taken35** [comment]
Hi, I think the bug continues. As I intent to update a field the ui shows this gray box.
<img width="329" alt="CustomDataTypeBug" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28500727/35b50e98-e906-4ef8-b9a5-7b72fb2f1c51">
