### ISSUE TITLE
API call variables do not set consistently and reset

### ISSUE THREAD

**Issue by dfedak-agileti** [FlutterFlow/flutterflow-issues#3033]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to set variable to send to an API call, the values 'flicker' and return to 'UNSET'.

### Expected Behavior

Variables persist and do not revert to 'UNSET'.

### Steps to Reproduce

1. Create API call action step
2. Set variable (e.g. selectedFranchiseCode from App State)
3. Add another variable
4. Set another variable (e.g. set FromDate from custom function)
5. Value set in step (2) reverts to 'UNSET'.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx89hpbxC1aXUa8Zv/AMxQFgnUL43iuxFGBQ3C4zwOqQMYcj+aXdvTNzheFVcGEyZjj8J+NKOjvHfOPlcCE6ZG6F607pATTvjcE6WRaagBc6CW3dCQNFUC0CByLe3sRB7NtNpWEJg2F+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Unable to progress project. I would classify this as a P2! Site isn't down, but definitely nothing else can progress.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/86153266/1945aa1f-6209-45e1-994a-c947afcc0825

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.54+ released May 30, 2024
Flutter version is 3.19.1
- Platform: Mac - both on Brave and Safari
- Browser name and version: Brave: Version 1.66.115 Chromium: 125.0.6422.112 / safari: Version 17.5 (19618.2.12.11.6)
- Operating system and version affected: Mac 14.5 (23F79)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by dfedak-agileti** [comment]
FYI this behaviour did not exist on Wednesday, which I assume is an earlier version of the UI.

**Comment by dfedak-agileti** [comment]
Now I'm also unable to revert to an earlier snapshot as the API action 'disappears'.

**Comment by msusviela** [comment]
Hi @dfedak-agileti. I could not reproduce the issue with the steps you provided. Is this still an issue for you?

**Comment by dfedak-agileti** [comment]
I've been able to reproduce it on a new project. On the page where the action is, force a layout error. While that error is still in the 'error state', any changes to action will exhibit this behaviour.

**Comment by msusviela** [comment]
Hi @dfedak-agileti. Could you provide a bug code for that blank project?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
