### ISSUE TITLE
All Components have white background instead of invisible

### ISSUE THREAD

**Issue by ebrammer** [FlutterFlow/flutterflow-issues#3034]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Suddenly in all my projects there is a background color (white) behind all the components where they were all invisible before.  This is only in the editor/app. When I've checked output using ios emulator - the normal invisible background is there.

### Expected Behavior

There shouldn't be a container color behind the components.

### Steps to Reproduce

Go to any the components in my prject

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Chc/135d2sddY187pbcBKhjgQJlw2RY0nlutteEkcHZPRC+0UZ/SkckRvONO4YFV+M2KgkWoW3MmOiPLLFcArHz+AfpRE1LpISAnKXmCgVbXXFJWgfXd8HftmfnLC16aV3RMmLvheSHdk21y1NtyWRXLZH4y3O0YkDq/LZO4=

### Context

I am unable to see my work properly.

### Visual documentation

<img width="2048" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5923757/ce9813d1-73e5-4ab5-ade1-74a94a19fa60">
<img width="2048" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5923757/56787a29-ff64-491b-9d6c-ce444b912fcd">
<img width="2048" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5923757/42c49e01-7d82-4d52-9553-ec685ef6b541">

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: MacOS Desktop
- Browser name and version: Mac App
- Operating system and version affected: macOS Monterey 12.7.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @ebrammer. This is a known issue. We are working on a fix. Closing this out as duplicate because it is already logged internally. Thank you for filing!
