### ISSUE TITLE
API call results missing

### ISSUE THREAD

**Issue by 408flutter** [FlutterFlow/flutterflow-issues#3037]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an API call to the same : url [https://012a-107-3-183-60.ngrok-free.app](https://012a-107-3-183-60.ngrok-free.app) and it comes back with status 200 but the result set is not available. I try the same call from postman and it shows up.

### Expected Behavior

I expect a token to show up

### Steps to Reproduce

Test the API call.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

dhiosahdhsahdasidsadasdasdada

### Context

Trying to setup authentication using API

### Visual documentation

None

### Additional Info

None

### Environment

```markdown
Current version trying out for 1st time
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] undefined\~100% of the time
- [ ] undefined\~50% of the time
- [ ] undefined\~10% of the time
- [ ] undefined\~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @408flutter Could you provide a valid Bug report code so we can check your project?
