### ISSUE TITLE
getting Uncaught (in promise)  during test / run/ published mode - (not because of my project issue, seems like flutterflow's appstate json issue)

### ISSUE THREAD

**Issue by ishanSiterecon** [FlutterFlow/flutterflow-issues#3039]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I currently open the test mode (which was working perfectly 2 days ago with the same configs)  - yesterday it was not working. Now that it is resolved somehow, the test build just not renders. It gives me error:

```javascript
Uncaught (in promise) Error
    at Object.throw_ [as throw] (dart_sdk.js:11914:11)
    at Object._parseJson (dart_sdk.js:59836:19)
    at JsonDecoder.convert (dart_sdk.js:57585:22)
    at JsonCodec.decode (dart_sdk.js:57280:48)
    at Object.jsonDecode (dart_sdk.js:59826:25)
    at new app_state.FFAppState._internal (app_state.dart:569:45)
    at get _instance (app_state.dart:11:44)
    at desc.get [as _instance] (dart_sdk.js:12520:17)
    at FFAppState.new (app_state.dart:14:12)
    at main$ (main.dart:20:20)
    at main$.next (<anonymous>)
    at dart_sdk.js:49722:33
    at _RootZone.runUnary (dart_sdk.js:49577:59)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:44704:29)
    at handleValueCallback (dart_sdk.js:45304:49)
    at _Future._propagateToListeners (dart_sdk.js:45342:17)
    at [_completeWithValue] (dart_sdk.js:45183:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:45217:35)
    at Object._microtaskLoop (dart_sdk.js:50026:13)
    at _startMicrotaskLoop (dart_sdk.js:50032:13)
    at dart_sdk.js:45573:9
throw_ @ dart_sdk.js:11914
_parseJson @ dart_sdk.js:59836
convert @ dart_sdk.js:57585
decode @ dart_sdk.js:57280
jsonDecode @ dart_sdk.js:59826
app_state.FFAppState._internal @ app_state.dart:569
get _instance @ app_state.dart:11
desc.get @ dart_sdk.js:12520
new @ app_state.dart:14
main$ @ main.dart:20
(anonymous) @ dart_sdk.js:49722
runUnary @ dart_sdk.js:49577
handleValue @ dart_sdk.js:44704
handleValueCallback @ dart_sdk.js:45304
_propagateToListeners @ dart_sdk.js:45342
[_completeWithValue] @ dart_sdk.js:45183
(anonymous) @ dart_sdk.js:45217
_microtaskLoop @ dart_sdk.js:50026
_startMicrotaskLoop @ dart_sdk.js:50032
(anonymous) @ dart_sdk.js:45573
Promise.then (async)
_scheduleImmediateWithPromise @ dart_sdk.js:45571
_scheduleImmediate @ dart_sdk.js:45577
_scheduleAsyncCallback @ dart_sdk.js:50047
_rootScheduleMicrotask @ dart_sdk.js:50229
scheduleMicrotask @ dart_sdk.js:49597
[_asyncCompleteWithValue] @ dart_sdk.js:45216
[_asyncComplete] @ dart_sdk.js:45198
complete @ dart_sdk.js:44580
(anonymous) @ storage_backend_js.dart:136
_checkAndCall @ dart_sdk.js:12169
dcall @ dart_sdk.js:12174
(anonymous) @ dart_sdk.js:119705
``` 

this seems some JSON issue with the app state but my app states were working completely earlier. and not forgot to mention that the app is not even initialized I believe? this clearly seems flutterflow's end issue. please look into it!

<img width="1437" alt="Screenshot 2024-06-01 at 9 39 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/144414632/30d834e0-2a22-4c86-ba3a-8bf13cce0f43">

### Expected Behavior

On using test mode, I should have been able to use my project's build to test and then start working on new requirements. 

### Steps to Reproduce

1. open my project https://app.flutterflow.io/project/estimation-app-634ajc?tab=appValues&appValuesTab=state
2. Go to test mode
3. open console log and see error before even the app correctly launched

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

My project id - estimation-app-634ajc

### Visual documentation

<img width="1430" alt="Screenshot 2024-06-01 at 9 41 51 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/144414632/8b527191-7a0a-4cd3-964b-c7f787882017">

### Additional Info

NA

### Environment

```markdown
FlutterFlow v4.1.54+ released May 30, 2024
Flutter version is 3.19.1
Chrome Version 125.0.6422.113 
Mac OS Sonoma 14.5 M1 8gb
```

### General

- [X] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by ishanSiterecon** [comment]
some thing is breaking internally for Flutterflow's test mode data loading phase. please check this, cannot work on my project  

<img width="1439" alt="Screenshot 2024-06-01 at 9 56 28 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/144414632/f4d4780f-aa89-4406-8a39-fbdf908327e2">

**Comment by paulperez-dev** [comment]
Hi @ishanSiterecon! We are unable to reproduce this issue. Can you please confirm us if it persists in the latest version?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
