### ISSUE TITLE
iOS build fails because of incompatible depedencies

### ISSUE THREAD

**Issue by BestRazer** [FlutterFlow/flutterflow-issues#3041]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I run `flutter build ipa` I get the following error: `
Because every version of flutter_test from sdk depends on collection 1.17.1 and landwege depends on collection 1.18.0, flutter_test from sdk is forbidden.
So, because landwege depends on flutter_test from sdk, version solving failed.
`

### Expected Behavior

I expect the ipa to be built successfully.

### Steps to Reproduce

1. Create a new project
2. Set up local run
3. Open in VS Code
4. Set up Xcode
5. run `flutter build ipa`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelMmBw5Jhn7xF7rXhYMdGpwMwJ0QlUIInj+0bWRMhfb3pB4oId8/RUFhLYteETXNAHVGbsGM0waGMjeLDKfADITObfJ84ypRXQQzjeEeuRc21C6ueP3R7BeVTGEi617SOniVvNvBeS0Ut1DiuIfCrG3qCf9qOYwx5e6fDbOY=

### Context

I'm trying to build my app for iOS devices and due to this error am unable to do so.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/65088083/aa6525b0-9990-42bc-b620-2ebce58ab7de)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.54 released June 1, 2024
- Platform: iOS
- Browser name and version: Chrome 125.0.6422.114
- Operating system and version affected: macOS Ventura 13.3.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Josefpa** [comment]
You might be using an incompatibilie version of flutter, right now FlutterFlow supports Flutter 3.19.1, check your current version with` flutter doctor` and try to downgrade / upgrade

**Comment by BestRazer** [comment]
That was exactly it, thanks very much! I thought it was supposed to use FlutterFlow's Flutter installation but for some reason it actually used flutter 3.10.
