### ISSUE TITLE
Facebook Auth With Firebase

### ISSUE THREAD

**Issue by Hong97** [FlutterFlow/flutterflow-issues#3044]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- After Click on Login With Facebook But no Response

https://github.com/FlutterFlow/flutterflow-issues/assets/19218808/1ee44c1b-4213-4740-a611-525ffb14eaed

### Expected Behavior

- Expected Login Success on Facebook with Firebase

### Steps to Reproduce

1) Create new project on Meta Console
2) Add Platform Google PLay Store
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/19218808/300de24c-40a2-4112-a1a9-15ce86c868fe)
3) Enable In Firebase
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/19218808/b9207cfc-d5e1-4e9d-b521-c5c00af8ed61)
4) Enable Email Testing in Meta Developer Console and Past valid Oauth Url
5) Add App name and app id into flutterflow config

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sl8iA+ot2xdtJ0K6JY8dKmjsvJj9/RYI7lexqEBEdferpELQtXOj9SFRuZNe6T2w7JWCi8T0K0N7LvdnUG+w9PiiuQaI6z5ZQQwrNRlu5Mq6zBoeKQGslEd5RCmGHzbSnoRRDKbd1ciEs2jiEGunIcBbYJbG2OlcvHs/9LdrX+nCpABzKXn0Jg1ZSfCvr

### Context

Not able to login with facebook

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/19218808/1ee44c1b-4213-4740-a611-525ffb14eaed

### Environment

```markdown
- FlutterFlow version: v4.1.54+ released June 2, 2024
- Platform: Web
- Browser name and version: (web): Chrome 125.0.6422.112
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Hong97** [comment]
Yes . This issue still persists

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jkminns** [comment]
I am having a similar issue. When downloading the code i can see the flutter_facebook_auth package isn't included in the pubspec.yaml and non of the facebook app name and id aren't included in the code including any ios/ or android/ files despite them being added into the flutterflow settings page & including a facebook login action.

**Comment by msusviela** [comment]
Hi. Sorry for the late response. We were still unable to reproduce this issues from a blank project. I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
