### ISSUE TITLE
Deploying Push Notifications is not working and showed Error 

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#3045]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

From the first time I tried to deploy the Push Notifications is shoewd error and the configuration needed is already set,

### Expected Behavior

I had other projects and its work fine with all the configuration needed excpet this one !

### Steps to Reproduce

1- upgrade Firebase project to Blaze 
2- Check the requirements need to deploy push notification
3- Deploy 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohcqBxIt1xPVc7aqNacFvryQsJUAhaLg018pBazwbfe+uB4kqevfOTERBOOGoTAhEf1n8p2oW0MqMveDDL/o7OUmaQKY4/pN2aBbicFqlaZiOFJWgY3B9P+lmCFClyqW7rx1vCLR1LyEu1GD3GdiQRT3BNu/xOkQWDa/LZO4=

### Context

Yeah, the client he waiting until now to fix the erros of Push Notificationns Triggers and still not deploying !

### Visual documentation

Deploy Error:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/920b276a-a266-4004-b00a-9fa6a834fd00)

Firebase Project:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/3b8c8c97-76eb-4807-9a3b-9946c64de7f4)

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/f2179b7f-c3c8-4ad4-b5a9-e125cb8ea43e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8468212/9cffc4e6-e09a-4dc8-ab5b-5eee3a1a4b66)

### Environment

```markdown
- FlutterFlow version: v4.1.54
- Platform: Web & Windows
- Browser name and version: Chrome Version 125.0.6422.114 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @ImadBouirmane<br>Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by ImadBouirmane** [comment]
No problem I undertood @msusviela !
I made for another existing project after we switch from supa to firebase and its work just last hour but for this project is not I will reach the support for sure.
Thanks
