### ISSUE TITLE
APK build fails because a FF error 

### ISSUE THREAD

**Issue by TobiShakur** [FlutterFlow/flutterflow-issues#3046]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

error while downloading apk.

### Expected Behavior

download apk correctly.

### Steps to Reproduce

1. download APK

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

dont have any

### Context

I am trying to build my apk to be able to use it but it is not being possible, the error code indicates that it has to do with code that is not possible to change within flutterflow and I would like to know if it is really an error in flutterflow or specifically in my project. my mistake I also saw that other users reported the same thing since May 30 and they do not have an answer to this bug yet.

### Visual documentation

Error: Command failed: flutter build apk --no-pub --no-version-check
Note: /opt/.pub-cache/hosted/pub.dev/cloud_firestore-4.15.7/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/purchases_flutter-6.0.0/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/tmp/ff_service_scratch/ZEazu89f5urLLzW33s1k/braiin/android/app/src/main/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [:record_android] /tmp/ff_service_scratch/ZEazu89f5urLLzW33s1k/braiin/build/record_android/intermediates/merged_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 23,
		or use tools:overrideLibrary="com.llfbandit.record" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 51s
Gradle task assembleRelease failed with exit code 1

### Environment

```markdown
- FlutterFlow version: v4.1.54+
- Platform: web
- Browser name and version: brave v1.64.122
- Operating system and version affected: windows 10
```

### General

- [X] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [X] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by leighajarett** [comment]
Thanks for flagging this issue! This is the same underlying cause as this issue, we are pushing out a fix ASAP. So sorry for frustration

**Comment by leighajarett** [comment]
[https://github.com/FlutterFlow/flutterflow-issues/issues/3015](https://github.com/FlutterFlow/flutterflow-issues/issues/3015)

**Comment by enecode99** [comment]
I've been facing the same problem. When can we expect the issue to be resolved? I understand it's hard to know exactly but can you please  an approximate time @leighajarett

**Comment by leighajarett** [comment]
This issue should be resolved now! Are you still experiencing the issue? Can you create a new github issue so we can try and reproduce to confirm it was the same cause?

**Comment by enecode99** [comment]
Hello @leighajarett  it now brings another error: something about the dependencies are incompatible with the Kotlin version "The binary version of its metadata is 1.9.0, expected version is 1.7.1". But when I view the Kotlin version in the Advanced Android Settings it shows is 1.7.10. So I'm not sure that error relates to the first issue or its the new one.

**Comment by leighajarett** [comment]
Can you please file a new issue so we can get the bug report code and such and figure it out?
