### ISSUE TITLE
Flutterflow - Toolbar - Bugs List Dropdown - Clicking on bug list item doesn't navigate user to where the bug is

### ISSUE THREAD

**Issue by FaludaAndIce** [FlutterFlow/flutterflow-issues#3047]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow - Toolbar - Bugs List Dropdown - Clicking on bug list item doesn't navigate user to where the bug is

### Expected Behavior

Flutterflow - Toolbar - Bugs List Dropdown - Clicking on bug list item navigates user to where the bug is

### Steps to Reproduce

1. Create a bug
2. Try to navigate to the bug from flutterflow toolbar bugs list

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skcjfsM5Om9xE0ZDuYMF7/TgUJUw5aLs8sctvaw4dfuLmP7AMOeLCX1VoWOqHe1FPe1H/oD41wsL0idnhU+0qC02eQL06+c5XUxDhfFKXVaa0C7qsZEclP+VgN0PH4LenhhMkANFYSkYtw2CQOuyub3qCf9qOYwx5e6fDbOY=

### Context

I've tried creating multiple new projects - seems to be a flutterflow UI issue. Cannot navigate to the bug

### Visual documentation

<img width="919" alt="Screenshot 2024-06-03 at 12 01 21 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/138960688/d38920f7-6bb7-41fe-9d1d-5bdfe9a2b574">

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): macOS Monterey 12.2.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @FaludaAndIce. This is a known issue. Our team is already working on this.<br><br>Thanks for your report
