### ISSUE TITLE
Over the past few days, Flutterflow shows orange exclamation mark instead of loading indicator

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#3049]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Up until a few days ago, everything was working fine. I had loading indicators in my pages, based on some boolean variables. Since a few days ago, instead of showing the loading indicators, an orange exclamation mark is being shown.

### Expected Behavior

Showing the loading indicator

### Steps to Reproduce

1. Create new project
2. Add new container
3. On a stack, add a lottie animation and a container with a column
4. Create a boolean variable. When the boolean variable is true, show the container and the column. When the boolean variable is false, show the lottie animation. The boolean variable is true when page loads, and false when all the API calls are succesful.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozMmBw412odtF+KrIccdviSQUC246becZkspBSTUbfIiuP4kQTc/7alZVUteiTAk7L2KGrH4e3NrHvfOXA+UoBAqrRrZJzc9MEgviWl25RrK0DoeCXXR8GdNJJVyM5rWvnCJCBPJZSi0611zzPuSQShbYNLrOOmwdGPKXNq3VkWurQ0SLb3kNh1JWeC/v

### Context

I am trying to show loading indicators and instead I am getting orange exclamation marks

### Visual documentation

<img width="1152" alt="exclamation mark" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11061846/9c47f2fc-3ce1-4eb4-8fca-8b6c609fde5f">

### Additional Info

<img width="1152" alt="exclamation mark" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11061846/a14b77cc-01a5-4960-ad24-3ddbac9615ff">

### Environment

```markdown
- FlutterFlow version: v.4.1.54+
- Platform: Web
- Browser name and version: Version 125.0.6422.142 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @adrfinance - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

Please check your lottie file that you're using. Is it rendering correctly? I tried with several lotties animations and worked fine for me. 

<br>Thanks!

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
