### ISSUE TITLE
"share" icon linked to wrong resource

### ISSUE THREAD

**Issue by tssma** [FlutterFlow/flutterflow-issues#305]
## Expected behavior (required)
"share" icon shows the icon from the preview

## Current behavior (required)
"share" icon does not show the icon from the preview but a different one

## To Reproduce (required)
1. Create new page
2. Add column widget
3. Add an icon widget
4. Set the "icon"-property of the icon-widget to "share" 
5. Result: The icon of the widget will not be the expected icon

Code can be included in this section if it is relevant to reproducing the bug. 
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
      body: SafeArea(
        child: GestureDetector(
          onTap: () => FocusScope.of(context).requestFocus(_unfocusNode),
          child: Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Icon(
                Icons.share,
                color: Colors.black,
                size: 24,
              ),
            ],
          ),
        ),
      ),
    );
  }
```

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/57814339/210182797-c8db46c7-7719-4770-a60e-d3f7b5a36975.png)

![image](https://user-images.githubusercontent.com/57814339/210182805-88087f07-dde8-485f-b73b-2e6bb1ebc9f5.png)

## Your environment

* Version of FlutterFlow used: v3.0 December 29, 2022 Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome Version 108.0.5359.125 (Official Build) (64-Bit)
* Operating system and version (desktop or mobile): Windows 10 desktop

**Comment by bulgariamitko** [comment]
This is how the icons behave. I think this is more of platform based issue. What I mean by that is the icons will be different from Android and iOS, but this is normal.
