### ISSUE TITLE
Missing font asset

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#3050]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All of a sudden, I am getting two 'missing font assets' errors in Flutterflow. Everything was working fine. I had the TTF files uploaded. Even after deleting the TTF files from the Typography & Icon custom fonts, I am still getting the same errors. How can we fix these issues?
<img width="1152" alt="fonts" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11061846/3af82e22-99f0-4854-ab69-307a7008f692">

### Expected Behavior

No errors

### Steps to Reproduce

1. Create new page
2. Get gilroy-regular and gilroy-bold ttf files. Add them to typography & icon in custom fonts

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozMmBw412odtF+KrIccdviSQUC246becZkspBZywgfZzzBLN/fPfQP0xpTumhS3xAe0yMp14BpMrXvuPfDuw5NkmYbLZTybVUdQ3/UkmiRaWTF7WWe3AlQJ5jCkiC0cGFgSVCHOt0SVYB7162HOq9Ti/qJo+3C0QwSq/LZO4=

### Context

I cannot run the project anymore

### Visual documentation

<img width="1152" alt="fonts" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11061846/98e8af84-4bbd-4ba3-9b97-a174e6116709">

### Additional Info

<img width="1152" alt="fonts" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11061846/de659ea3-9eb2-481f-909a-31e4bfb185db">

### Environment

```markdown
- FlutterFlow version: 4.1.54+
- Platform: Web + APK extraction
- Browser name and version: Version 125.0.6422.142 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 home
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @adrfinance. I tried replicating the issue from a blank project but I couldn't. <br><br>I checked your project and currently you don't have any custom font family. Can you check adding them again?<br><br>If the error persists, since it's project specific, our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by adrfinance** [comment]
hello, as you can see from the screenshot I attach, even when I delete the
fonts, the errors are still there. Can you please fix this?

[image: image.png]
