### ISSUE TITLE
Using Code expression for variable value assignment crashes Flutterflow App after the latest update.

### ISSUE THREAD

**Issue by akscienceltd** [FlutterFlow/flutterflow-issues#3051]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Opening Code expression option while trying to create/modify expression causes Flutterflow app to hang/crash.

### Expected Behavior

Code expression function must allow us to define/modify code expressions for variable value assignment,

### Steps to Reproduce

Create a widget/state variable. Try to update it value through the Code Expression feature. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/170185307/e58108c3-dcd4-45c5-9215-5dca834db89d)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz8jfz5VNj7xK1br+YMBB/GQXJmI8bJIascpFcxQcB4jZP4kQfPfQPhJWcOGlT1Y/Ime2p14Gpt7nv87hGvArAzGZRt0+/4d2TznJVXOjb7GTF7i0eHcnP/xjI0+MyKarsRZCFPVac3wO3WamP+e/SnfqNpOxDVQ8Sq/LZO4=

### Context

I'm trying to use code expressions for updating a state variable value.  
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/170185307/1502b0fa-243d-403c-b15f-ad7e32f8ac85)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/170185307/cc201f49-b0fe-43bc-bf98-0a072a7a0895)

### Additional Info

This issue wasn't occuring in the previous version and has happened after latest update.

### Environment

```markdown
- FlutterFlow version: V4.1.54+
- Platform: Windows Desktop App
- Browser name and version: Chrome 125.0.6422.114  
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [X] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @akscienceltd! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

Please provide the required information with more detailed steps to reproduce.

**Comment by akscienceltd** [comment]
Hi @paulperez-dev , This is a screen recording of the steps. Will this help? 

https://github.com/FlutterFlow/flutterflow-issues/assets/170185307/6c35b1f2-d5cd-4c64-a3ec-4059a138b8de

**Comment by akscienceltd** [comment]
Let me get back to you on this in a day or two.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
