### ISSUE TITLE
App reverse to previous version

### ISSUE THREAD

**Issue by porgokarim1** [FlutterFlow/flutterflow-issues#3053]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When building the app if you close the project and come back later to work on it , you may encounter that your most recent changes have been taken away or archived  and the previous work of like 2-3 days ago has ben made as current version. You will have to go to the version snapshots and reverse it to your last changes. And the scary(security) part is that it even update the published web to the previous one. so you will have to republish the web again. Been encountering this issue the past  2 weeks with different project. (In case you wondering if I was connected to the internet or saved my work before closing the project? Yes I am connected to internet that is why I can fetch back the changed versions when this bug happens)
![Screenshot 2024-06-03 150154](https://github.com/FlutterFlow/flutterflow-issues/assets/60364286/215e0856-e012-4754-a347-3f17c014bca2)

### Expected Behavior

When you open the project you should be seeing your most recent changes. Absolutely not the oldest ones

### Steps to Reproduce

1. Create project.
2. Work on it .
3. Close the project and come back work on it the second day.
4. Keep closing and coming back to check the project and make some changes . And then you may start seeing that your most previous changes haven't been saved. Well it is saved but a previous version of the app has been restored as current. To get your latest changes you have to go to version snapshots and pick the previous version and reverse it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8glsrlvI1gocNf7aXyacdKpyQUJj9/U403l9Zxcwgbfe/2PJ13Zc74UFpoUu6Ba21AI1qZkmYypuDUhIbtEfkoOgquQbo93JVqVgvwJX6uMrXSDaigdndRJ/1jGlyY0qS33AlsA+FuciFiwU6MH+qUSjbvH7LjO1gdOfmHNq3LpXjlHSbBNSFWs20XEx7eTI5ODEz25eKMrop5yfj/0w==

### Context

It affect my work progress. Before I realize I can fetch it back from the versions Snapchats, I was rebuilding everything again when i was first encountering these issue

### Visual documentation

![Screenshot 2024-06-03 150154](https://github.com/FlutterFlow/flutterflow-issues/assets/60364286/5842bab1-38fd-4b19-aacb-d754dff796b5)

### Additional Info

In case you wondering if it encounter this issue on the flutter app or the web. It is actually both platform.

### Environment

```markdown
- FlutterFlow version: V4.1.54+
- Platform: APP & Web
- Browser name and version: ??
- Operating system and version affected: windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [X] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [X] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [X] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [X] Very rarely or only encountered once

**Comment by MartinLockheart** [comment]
I've also been running into this issue across multiple projects. The other day, I made several bugfixes to one project and published to web. The next day, I had clients tell me that those bugs hadn't been fixed. 

After looking at the pages with issues, I found that all of the changes I made were gone. I had to revert to a snapshot and then publish again (and fortunately, the changes went live that time). 

This is very concerning for me, because unless I've made an obvious visual update, I don't know when I'm losing work, and I can't reliably know that my clients are getting updates.

**Comment by porgokarim1** [comment]
@MartinLockheart  yes absolutely. Without a visual changes it is hard to know where you left of. And what is unfair is the fact that it even changes the published web. This issue need to be addressed ASAP. When it fist happens to me I had to go back and write my whole custom codes and custom widgets. It was a real pain :).

**Comment by leighajarett** [comment]
Oh no, I am so so sorry this is happening to you. This is sooo frustrating. We've heard several instances of data loss, so we are in the process of refactoring a good portion of our codebase that we think is causing the underlying issue. We hope to have this released in the next few weeks.

**Comment by lleo132** [comment]
This problem gets worse when it comes to collaborative projects, when using the Windows version and my teammate accesses the web, everything I did is lost.

**Comment by leighajarett** [comment]
I'm so sorry 🙁 That is such a frustrating experience and is really unacceptable. This is the highest priority for our team at the moment

**Comment by bitgandtter** [comment]
Our team is currently stuck on this issue across different countries and different OS, web, and desktop apps. This is a blocker, and since we are paying for it, we are losing money by the hour @FlutterFlowEng please provide a resolution

**Comment by franfcb10** [comment]
Please, it is important to solve this problem, it does not allow us to advance our project. It's been 3 days with this problem. @FlutterFlowEng

**Comment by porgokarim1** [comment]
@leighajarett I may have figure out what is the root issue. I just experience the version reversing back again. This time It happened when I cleared my browser cookies and search data.(I cleared it because the RUN was taking too long to show the app). Hopefully this point you to the right direction if you are still searching the root cause. @FlutterFlowEng
