### ISSUE TITLE
Custom Function Validation Stuck .. Keeps Spinning

### ISSUE THREAD

**Issue by adityatalwalkar** [FlutterFlow/flutterflow-issues#3055]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My Custom Code suddenly stopped working... the custom code validator is just spinning and not returning any output.
see the attached image 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/18378344/c92d23fe-155b-4a8e-8d6c-627a3397e5dc)

The console displays following error - 

FlutterFlow Code Editor: [Error - 10:21:09 AM] Request textDocument/documentColor failed.
 FlutterFlow Code Editor:   Message: File is not being analyzed
  Code: -32007 
/tmp/ff_service_scratch/personalfinance-3uawg5/lib/custom_code/functions/format_rupee.dart
 Error from language server: 1 Request textDocument/documentColor failed.
 [main 2024-06-04T04:51:09.750Z] [monaco] provider FAILED
error @ monaco-code-editor-dart.bundle.js:2
error @ monaco-code-editor-dart.bundle.js:2
(anonymous) @ monaco-code-editor-dart.bundle.js:2Understand this error
 [main 2024-06-04T04:51:09.750Z] Error: File is not being analyzed
error @ monaco-code-editor-dart.bundle.js:2
error @ monaco-code-editor-dart.bundle.js:2
(anonymous) @ monaco-code-editor-dart.bundle.js:2Understand this error
monaco-code-editor-dart.bundle.js:2 Uncaught Error: File is not being analyzed

Error: File is not being analyzed
    at https://app.flutterflow.io/monaco-code-editor-dart.bundle.js:2:2232704
    at https://app.flutterflow.io/monaco-code-editor-dart.bundle.js:2:2232998
    at https://app.flutterflow.io/monaco-code-editor-dart.bundle.js:2:2233360

### Expected Behavior

The code should compile, or give a error message

### Steps to Reproduce

1. It suddenly stopped working. so no specific steps to reproduce. However my project has permanently stopped working .. here is the link to the project - 

https://app.flutterflow.io/project/personalfinance-3uawg5?tab=customCode&customCodeTab=functions

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No way to generate this .. 

### Context

The editor suddenly stopped working. Tried it from various browsers and desktop app too but same error continues.

### Visual documentation

attached above

### Environment

```markdown
- FlutterFlow version: v4.1.54+
- Platform:Web as well as Desktop
- Browser name and version: Chrome Version 125.0.6422.114 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.5 (23F79)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by martinbutt** [comment]
Also seeing this. Started about an hour ago.

**Comment by ibomds** [comment]
me too, please fix

**Comment by mulyameubel** [comment]
Saya Juga mengalam hal yang sama.

**Comment by msusviela** [comment]
Hi @martinbutt, @ibomds and @mulyameubel<br><br>I was not able to reproduce this issue (even with the code you provided). Is this still happening to you?

**Comment by adityatalwalkar** [comment]
It’s working now for me

Thanks,
Aditya Talwalkar

**Comment by martinbutt** [comment]
It's working again for me too. At that time, building APKs and starting a new test session were also stuck.

**Comment by leighajarett** [comment]
Yes that should be resolved now!
