### ISSUE TITLE
Custom Data Type Bug within Actions After the latest  FF update

### ISSUE THREAD

**Issue by taken35** [FlutterFlow/flutterflow-issues#3056]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="221" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28500727/1568cbf8-aa55-446f-9d30-05cae819ba58">

This is a nested custom data type structure, an infinite grey box appears instead of value section.

### Expected Behavior

Previously this was working fine. As I remove an add this custom data type again an infinite gray box appears.
<img width="224" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28500727/9de9db74-9f0a-45b9-a811-054a3a907423">

### Steps to Reproduce

In actions : 1.Update App State 2. Select Add to List 3. Value to Add= Create Data Type Object= select custom data type 4. Add Field. 5. If a nested custom data field selected is a list an Infinite gray box occurs, otherwise e.g an integer value can be updated normally.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi8rl7YZNobxc+KqIYMFWryg7CUMcWOdEl+tuZwgbIoznBu02ZMjOVFRvYMfnaVNcAGClgTgepsLRjeHPLfkoIkiqfqp+1KpyTgzOe2iVSrKQBpDpemhBJ9xgfHag556VgBN/LvZvZUYD16qevCiVnTDFOu/Zwh9f6PHaOI=

### Context

parts of the app wont work, can not progress 

### Visual documentation

<img width="224" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28500727/9de9db74-9f0a-45b9-a811-054a3a907423">
<img width="221" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28500727/1568cbf8-aa55-446f-9d30-05cae819ba58">

### Environment

```markdown
- FlutterFlow version: v4.1.54+ released June 4, 2024
- Platform:Windows Desktop/ Web
- Browser name and version: Chrome Version 125.0.6422.141 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @taken35. For some reason I as not able to run the app with the bug report code you provided. Could you generate this bug report code again so I can take a look further on how you defined the app state and the custom data type?

**Comment by taken35** [comment]
> Hi @taken35. For some reason I as not able to run the app with the bug report code you provided. Could you generate this bug report code again so I can take a look further on how you defined the app state and the custom data type?
Hi, I regenerate it:
ITFTi8rl7YZNobxc+KqIYMFWryg7CUMcWOdEl+tuZwgbIoznBu02ZMjOVFRvYMfnaVNcImabvF400anmuN7xG+0CJU+aboBH1s1ISQvke2iVSrKQBpDpemhBJ9xgfHag556VgBN/LvZvZUYD316qevCiVnTDFOu/Zwh9f6PHaOI=
