### ISSUE TITLE
Can't copy build logs

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#3057]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Refecencing "How to Identify Your Codemagic Error", deployment error can be copied, but can't copy.

### Expected Behavior

I can copy build logs

### Steps to Reproduce

1. build error
2. Try to copy

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz8mA/c5NsctA+KnbKcdFhmYWI0MdXOczitVEew4bCIj4OpocOcjCaktvYNSzaHNUE1aj8UAK0srTvvLPFcYEKROaG9lgybliEBPPbGO5VciVDqWoeUFRP8ZXfm6F0bWrriUkCMBuc1YN11+MfequRT6Cf9qOYwx5e6fDbOY=

### Context

Can't search error message easily

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/29b34282-ad67-4922-bfa3-0ec6db21f036)

### Environment

```markdown
- FlutterFlow version: V4.1.54
- Platform: Mac
- Browser name and version: Chrome 125.0.6422.113
- Operating system and version affected: macOS 14.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @idea-garage. Could you provide us with more info on how to replicate this error message?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
