### ISSUE TITLE
Build failed with message "error: Invalid source release: 17"

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#3058]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to deploy to play store, build failed with message "error: Invalid source release: 17".

### Expected Behavior

Build succeed

### Steps to Reproduce

1. create app
2. try to deploy to play store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz8mA/c5NsctA+KnbKcdFhmYWI0MdXOczitVEew4bCIj4OpocOcjCaktvYNSzaH9mCmGKr3MEpfzHjYaSKPU7NRGYRapAwZNUaxPPbGO5VciVDqWoeUFRP8ZXfm6F0bWrriUkCMBuc1YN11+MfequRT6Cf9qOYwx5e6fDbOY=

### Context

I already credentials have set, previous build was succeed.
I set Kotlin version to 1.9.0, due to version issue. if I leave Kotlin version default, build failed due to version 1.7.0.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/33186b36-38dd-4fc3-b5b5-e8b14b10c346)

### Environment

```markdown
- FlutterFlow version: v4.1.54
- Platform: Mac
- Browser name and version: Chrome 125.0.6422.113
- Operating system and version affected: macOS 14.5（23F79
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @idea-garage! The package `file_saver` is causing the build error. They released a new version to solve this problem, so upgrade the package version to at least `0.2.11` ([Reference](https://pub.dev/packages/file_saver/changelog)).

I am closing this issue.

**Comment by hidech** [comment]
@paulperez-dev Thanks for kindly information! I'll update it.
