### ISSUE TITLE
Running Test on Function shows compilation error about FirestoreFirebase unrelated to the function

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#306]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I expect the Test to return the value of a User collection Document Reference.

## Current behavior (required)

The test fails and I get this error: 
![CounterParty - FlutterFlow 2023-01-01 at 6 16 20 PM](https://user-images.githubusercontent.com/14055/210191101-4a976a60-9a47-41b2-838c-84ce2f49edaa.jpg)

It's about not being able to compile a Firebase Firestore in a custom function.  (If we can't do this, can the docs be clear somewhere?  I am getting competing information about whether a custom function can reference a Firestore Document)

## To Reproduce (required)

```
DocumentReference? returnNonAuthfromPair(
  List<DocumentReference>? userPair,
  DocumentReference? authUser,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // return element from userPair that does not equal authUser
  if (userPair == null) {
    return null;
  }
  if (userPair.first == authUser) {
    return userPair.last;
  } else {
    return userPair.first;
  }

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

```

1. Create a function as above
2. Create a test with parameters PairUsers with two User Document references (e.g. users/example1; users/example2
3. Put a value in the other parameter matching one of the values (users/example1)
4. Expect to return users/example2

## Context (required)

The function is intended to return, of the two User Document Reference in the list field UserPair, which one does NOT match the one input as the other Parameter.

I want to test this because I am getting errors when using it.  But testing fails.  

This is true about pretty much every function and action.  This limits ability to roll-out and triage custom code.

## Your environment

* Version of FlutterFlow used:   3.3.4
* Platform (e.g. Web, MacOS Desktop):  Web on MacOS Desktop
* Browser name and version:  Chrome Version 108.0.5359.124 (Official Build) (x86_64)
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
Hi @timfong888. I made a test project that could run this function: https://app.flutterflow.io/project/flutterflow-issue-306-h6fji7. Could you check what is being different?

**Comment by wenkaifan0720** [comment]
Due to inactivity of this thread, I'll close it for now.
