### ISSUE TITLE
FlutterFlow did not detect that my component was using a pageState instead of a componentState

### ISSUE THREAD

**Issue by EricVanin** [FlutterFlow/flutterflow-issues#3060]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was studying the FlutterFlow tool, when in the video the instructor made the error appear, and for me it hadn't appeared, but it was there. Then I realized that the bug occurred but was not being notified by the tool.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122339238/c66bb7fa-2bba-4e6c-a563-c091372402cf)

### Expected Behavior

I hope it is fixed, as this makes debugging easier.

### Steps to Reproduce

1. Create a LeftMenu, using a pageStates
2. Convert the LeftMenu to component
3. Solve the bugs, and you will see that there will be some that will not be pointed out, usually occurring with visual conditions, such as hovering over a text or icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

if (widget.parameter1 == '1')   Align(     alignment: AlignmentDirectional(0, 0),     child: Container(       decoration: BoxDecoration(),       child: Column(         mainAxisSize: MainAxisSize.max,         children: [           MouseRegion(             opaque: false,             cursor: MouseCursor.defer ?? MouseCursor.defer,             child: Container(               height: 40,               decoration: BoxDecoration(),               child: Row(                 mainAxisSize: MainAxisSize.max,                 children: [                   Icon(                     Icons.circle_sharp,                     color: _model.optionMouseRegion1Hovered!                         ? Colors.white                         : Color(0xFF9D9DA6),                     size: 6,                   ),                   Padding(                     padding: EdgeInsetsDirectional.fromSTEB(12, 0, 0, 0),                     child: Text(                       'Hello World',                       style: FlutterFlowTheme.of(context).bodyMedium.override(                             fontFamily: 'Readex Pro',                             color: _model.optionMouseRegion1Hovered!                                 ? Colors.white                                 : Color(0xFF9D9DA6),                             letterSpacing: 0,                           ),                     ),                   ),                 ],               ),             ),             onEnter: ((event) async {               setState(() => _model.optionMouseRegion1Hovered = true);             }),             onExit: ((event) async {               setState(() => _model.optionMouseRegion1Hovered = false);             }),           ),           MouseRegion(             opaque: false,             cursor: MouseCursor.defer ?? MouseCursor.defer,             child: Container(               height: 40,               decoration: BoxDecoration(),               child: Row(                 mainAxisSize: MainAxisSize.max,                 children: [                   Icon(                     Icons.circle_sharp,                     color: _model.optionMouseRegion2Hovered!                         ? Colors.white                         : Color(0xFF9D9DA6),                     size: 6,                   ),                   Padding(                     padding: EdgeInsetsDirectional.fromSTEB(12, 0, 0, 0),                     child: Text(                       'Hello World',                       style: FlutterFlowTheme.of(context).bodyMedium.override(                             fontFamily: 'Readex Pro',                             color: _model.optionMouseRegion2Hovered!                                 ? Colors.white                                 : Color(0xFF9D9DA6),                             letterSpacing: 0,                           ),                     ),                   ),                 ],               ),             ),             onEnter: ((event) async {               setState(() => _model.optionMouseRegion2Hovered = true);             }),             onExit: ((event) async {               setState(() => _model.optionMouseRegion2Hovered = false);             }),           ),           MouseRegion(             opaque: false,             cursor: MouseCursor.defer ?? MouseCursor.defer,             child: Container(               height: 40,               decoration: BoxDecoration(),               child: Row(                 mainAxisSize: MainAxisSize.max,                 children: [                   Icon(                     Icons.circle_sharp,                     color: _model.optionMouseRegion3Hovered!                         ? Colors.white                         : Color(0xFF9D9DA6),                     size: 6,                   ),                   Padding(                     padding: EdgeInsetsDirectional.fromSTEB(12, 0, 0, 0),                     child: Text(                       'Hello World',                       style: FlutterFlowTheme.of(context).bodyMedium.override(                             fontFamily: 'Readex Pro',                             color: _model.optionMouseRegion3Hovered!                                 ? Colors.white                                 : Color(0xFF9D9DA6),                             letterSpacing: 0,                           ),                     ),                   ),                 ],               ),             ),             onEnter: ((event) async {               setState(() => _model.optionMouseRegion3Hovered = true);             }),             onExit: ((event) async {               setState(() => _model.optionMouseRegion3Hovered = false);             }),           ),         ],       ),     ),   )

### Context

I was studying the FlutterFlow tool, when in the video the instructor made the error appear, and for me it hadn't appeared, but it was there. Then I realized that the bug occurred but was not being notified by the tool.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122339238/fde5977c-1ec7-4bfb-9b71-d2f9938426ca)

### Environment

```markdown
- FlutterFlow version: Free
- Platform: Web
- Browser name and version: operaGx  109.0.5097.108
- Operating system and version affected: 4.1.54
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [X] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [X] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [X] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @ErinVanin. Could you provide us with the bug report code for this so we can investigate further into the issue?  <br><br>You can generate one by clicking right into your widget tree and select the option "Generate bug report code"

**Comment by EricVanin** [comment]
Desculpe, mas eu já corrigi o problema aqui, agora não consigo reproduzi-lo
novamente, mas seu eu me deparar com ele novamente eu lhe enviarei por aqui.

Alias, eu havia anexado deixado o codigo do widget no report do github
antes de avançar no projeto aqui.

Em ter., 4 de jun. de 2024 às 16:31, Micaela ***@***.***>
escreveu:

**Comment by msusviela** [comment]
Hey @EricVanin, This tracker is only used for reproducible bugs, so I am closing this issue. If this happens again, please open a new issue.<br><br>Thanks for using FlutterFlow!

**Comment by EricVanin** [comment]
Of corse, thaks for support.l

Att
 Eric Vanin
