### ISSUE TITLE
Adding two filters in backend query (from within actions) defaults to OR condition. 

### ISSUE THREAD

**Issue by nvimalraj** [FlutterFlow/flutterflow-issues#3064]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Everywhere else in the flutterflow, the filter conditions defaults to AND condition. But adding second filter in backend query inside Action defaults to OR condition.

### Expected Behavior

Make it consistent so it defaults to AND everywhere. 

### Steps to Reproduce

Go inside Action, Add a Firestore Query, Query Collection, add second filter and it defaults to OR instead of AND like everywhere else.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlc/l3ItOm/VH+KXtY8ZsjmA7CUMdXOczitVEew4bCIj4BLAAPs/OTFZpZ8CzaH1qMFq0mjsJ/6HevYaSDu5dIgeuR498+ZZcFBPPYzu7Wq7QDquBdXNPBZpYfki917uJpiN7HMtoWnwb7ziEP+iQTT2Cf9qOYwx5e6fDbOY=

### Context

It creates unwanted time to debug and most of the time, it becomes very hard to debug as well, since the expectation is AND by default and OR is something we conciously choose. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68550576/34de073d-9a87-43eb-9660-2fa2947cfffa)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: All
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @nvimalraj, i'll submit an enhancement request for that so it can be improved. Closing this ticket since this list is meant only for bugs.

Thanks for the feedback!
