### ISSUE TITLE
Custom icons are not showing from the last 2-3 days

### ISSUE THREAD

**Issue by niral-design** [FlutterFlow/flutterflow-issues#3066]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="1710" alt="Screenshot 2024-06-05 at 9 37 05 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/171768756/b2ec0d51-2432-44f8-983e-f92bd712f394">

Custom icons are not working, they are not visible from the last 2-3 days. and because of that i can not work on my project

### Expected Behavior

custom icons should visible in the canvas and the UI of the app

### Steps to Reproduce

1. uploaded all the custom icons again
2. used them in the Ui and the components

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ok87624Z1pbxa1s76LO9aniYvNjM5a4ZNmsFxbxY3fJfNG7UIec/4VEptXbC+TVc2emKapHIx+eiLhtzIN+5dYA2Zfa5C+rtIbw6VUmG6SpipOrqzdXQnFtpKCHa637W7nx1QFPJZcV472HGmBOvLYADfQIz1C1c7O8+KCKXOo3PuQ0SLb3kNh1JWeC/v

### Context

If the I icons are not visible then, How can i design my app in the fluterflow, its nearly impossible to design things without icons. i am not able to work on my project from the last 3 days

### Visual documentation

<img width="1179" alt="Screenshot 2024-06-05 at 10 31 11 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/171768756/fa19c30e-e97c-4e91-a879-269856a27b31">

### Environment

```markdown
- FlutterFlow version: 4.1.54+
- Platform: web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOs
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [X] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @niral-design, so sorry you are experiencing that issue, would you mind sharing the custom icons files with me? i want to attempt to replicate this in a blank project, and a quick question, have you tried a different set of icons to check if the issue only persist with that particular set?

**Comment by niral-design** [comment]
yaa i have tried different icon set also, but custom icons are not working.
I have used phosphors icons from https://phosphoricons.com/ . please have a
look.

thanks,
NP

**Comment by rzambroni** [comment]
Sorry, i'm not very familiar with phosphoricons, how did you import the icons into FF? because i'm missing the dart file that should be accompanying the ".ttf" file and i don't see a way to generate it and the download all doesn't have it.

Tested other icon packs from icoonmoon and fluttericon and they work as expected, so i'm suspecting there might be something wrong with the source of your icons.

Thanks.

**Comment by niral-design** [comment]
Yaa to use phosphorus icons we have to convert them into .ttf using flutter
icon generator..

I have been using these icons for the last 2 months in flutterflow, but
suddenly it stopped working from the last 3 days

**Comment by rzambroni** [comment]
i see, would you mind adding the steps to reproduce from a blank project so we can try to replicate the exact issue? thanks.
