### ISSUE TITLE
Components in ListView | Remove from List at index not working

### ISSUE THREAD

**Issue by mhdrescher** [FlutterFlow/flutterflow-issues#3067]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to remove an item from a list at an index. Currently it always deletes the last item of the list. 

To make it easier I recorded a Loom Video of my problem. You can find it here:

https://www.loom.com/share/dcea83b856bb453c9f31d270f64b974a?sid=d5e78d2c-44b6-4f11-9e49-76c1d67275c4

It also extends to updating information at an index.

### Expected Behavior

When I remove an item at an index I would expect that Item to be removed and not always the last item of a list. 

### Steps to Reproduce

Please see the video for a detailed explanation of how to reproduce the bug. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ois/q24ZNrt9A1s+MbcdKhjgsQ34jarxMjetHcwI3C5PNGu4Iec/eUFZuZr2qYGNDeVqkrGIz1vfqjvD+FfAqCxybY4BizJZUVBXKLHGjb82WCJarfW1QHcZYfVzG0aSJmB54FO9ZLU4sw16QBuzLSgzsH5D0PXoRBeWbLdeK2SrDX1iXc2URm05KZDPz

### Context

I want the user to be able to change the ingredient composition of a meal, which translates to being able to remove, add and update items at a list index.

### Visual documentation

Again, please see my Loom video: https://www.loom.com/share/dcea83b856bb453c9f31d270f64b974a?sid=d5e78d2c-44b6-4f11-9e49-76c1d67275c4

### Additional Info

If there are any more questions, please feel free to reach out! Thank you!

### Environment

```markdown
- FlutterFlow version: v4.1.54+
- Platform:Web, iOS
- Browser name and version: Arc Version 1.44.3 (50502), Chrome Version 125.0.6422.142 (Official Build) (arm64)
- Operating system and version affected:  iOS 17.5.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by mhdrescher** [comment]
Further info can also be found in my community post https://community.flutterflow.io/ask-the-community/post/components-in-listview-remove-from-list-at-index-not-working-8EeeDk0ENwos0Iq

**Comment by msusviela** [comment]
Hi @mhdrescher. We're currently looking in to the issue. Thanks for the report

**Comment by mhdrescher** [comment]
Hi @msusviela, can you give me an update on the matter yet?

**Comment by mhdrescher** [comment]
Is there any update about this? Thanks.

**Comment by gCharilaou** [comment]
Hi, I have a similar issue when removing a data Struct item from a list.
The item is only removed if is added on that session. If is loaded before hand then is not removed

Any updates?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68695689/fadaa12b-fea6-484f-ba3b-d8ea9fe11ce4)

**Comment by msusviela** [comment]
I apologize for the late response. We're investigating this issue. @gCharilaou, cold you please provide a bug report code for that so we can check on that please?

**Comment by James5943314556** [comment]
I am also having the same issue

**Comment by msusviela** [comment]
@James5943314556, can you share a bug report code?

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, if you are still experiencing this issue feel free to reach out to us.

**Comment by buildthick** [comment]
The problem still exists.

**Comment by clickqcollect** [comment]
Issue continues to exist.

**Comment by buildthick** [comment]
The problem still exists, bug code report is:

IT4Wz8r15ZVNj7xa15DucsJanSQRNlw1bZZNmsNxTQE3F4urOowPXfnRalhoTN+idGNqL2H8kmYew9KNuNn2A+UnEzGBbL5a1LlcWj3jUnOiMrKOPLmRdHEmLNxJJVyg5JmC2yVCOtZiL1IM2U6qBuzISXfXHu/LPVUSDciJEK/Ao12pQ0SLb3kNh1JWeC/v

**Comment by buildthick** [comment]
Hello, any updates?

**Comment by TimothyWCTI** [comment]
The issue persists, please re-open this issue.

**Comment by noahgomz** [comment]
@TimothyWCTI, I think FF has given up on this thread but I created a new one they responded to _once_ last week.
Mind supporting here: https://github.com/FlutterFlow/flutterflow-issues/issues/4052

**Comment by TimothyWCTI** [comment]
Thanks @noahgomz, I've added my voice to the pile

**Comment by vinojko** [comment]
Hi, the problem in my case was because of not setting the correct Unique key.

it's not a FlutterFlow issue (at least in my case). Flutter might incorrectly match widgets to list items because it assumes the key represents the same widget. We need to set Unique Key not to index in a list but truly unique. I created a costum function which generated a uuid:

```
String? generateUUID() {
  /// MODIFY CODE ONLY BELOW THIS LINE

  const int length = 8;
  const String chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  final math.Random random = math.Random();

  final String uuid =
      List.generate(length, (index) => chars[random.nextInt(chars.length)])
          .join();

  return uuid;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```
and then used that as a unique key - keep in mind the component also needs to be assigned the same id.

![image](https://github.com/user-attachments/assets/f4d48707-e25b-4e00-a7e8-1647e658a8eb)

if someone knows of a better solution, welcome!
