### ISSUE TITLE
Dependency problem for intl package. flutter_localizations needs 0.19.0 while dash_chat needs ^0.18.0

### ISSUE THREAD

**Issue by yairpe** [FlutterFlow/flutterflow-issues#3068]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have Flutterflow chat in my project.

After downloading the code to Android Studio I cannot compile and run.

in pubspec.yaml
	intl: 0.18.1

Running pub get:

Resolving dependencies...
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because <myproject> depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because MYPROJECT depends on intl 0.18.1, version solving failed.

if I change manually in pubspec.yaml to
	intl: 0.19.0

I get another error:

Resolving dependencies...
Because MYPROJECT  depends on dash_chat from git which depends on intl ^0.18.0, intl ^0.18.0 is required.
So, because MYPROJECT  depends on intl 0.19.0, version solving failed.

So I see no way to bypass this dependency loop.

### Expected Behavior

Flutterflow is using an old version of chat (dash_chat v1)

In the github project for flutterflow chat (https://github.com/FlutterFlow/flutterflow_dash_chat) there's a message:
⚠️ V1 is not maintained anymore, check the V2 on: https://github.com/molteo-engineering-team/Dash-Chat-2 ⚠️

So the best way IMHO will be to upgrade the chat  to dash_chat_v2
The immediate fix may be to fix flutterflow chat to require intl ^0.19.0

### Steps to Reproduce

1. create a project with flutterflow chat pages
2. download the code to Android Studio
3. Try to compile or run pub get

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci/LqwIhjpbxb7aXqacFvryQsIjs/RYINiMEaRgIdJ5PMC+wIZ/f7XFRuTde0YwllPkyWo3Mxw/vemvOSUvA4YC6ufJxMzs5iSwmXfGO5WqqOC7mCSW5/DeBMf0/G0MCFhCZ5OtRiS3dm62eAAu6uQh3DNZzWDDIvAfykA5CK2SrDX1iXc2URm05KZDPz

### Context

I cannot create a mobile version

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/99516143-3299-4b8a-ad32-16e75905f2fa)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: Android
- Browser name and version: Chrome latest
- Operating system and version affected: Win 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @yairpe. I wasn't able to reproduce the issue. I tried the 2 existing flows that FlutterFlows provides for chat and none of them is using the dash_chat package.

Could you provide me more info on where to find the chat page you're using?

**Comment by yairpe** [comment]
I'm using the default 1-to-1 chat module of Flutterflow

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/20fb8675-3b3d-4880-bc99-d12e12f50c4f)

Here is what FF generates in pubspec.yaml:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8095933/441eb944-238e-4975-865e-3834826be5ea)

I don't have any chat related custom widgets

**Comment by yairpe** [comment]
I found the problem.
I've upgraded Android studio to a newer version   :(

The way to fix it on my Win 11 machine was:
cd C:\tools\flutter
git checkout 3.19.1
