### ISSUE TITLE
selecting local file option missing in api testing 

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#307]
when testing api and its response. if the variable has a local file selection then, there is no option to select the file
need this option to select the json path from response
![download](https://user-images.githubusercontent.com/37708853/210206264-4ac08444-d92f-4cc4-80f1-7c3d2d33320a.png)
![download](https://user-images.githubusercontent.com/37708853/210206279-d3e28ada-2067-4468-9f90-e42cc9090acc.png)

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

**Comment by bulgariamitko** [comment]
I am closing this as the user was not active in the last 2 weeks, but please feel free to open it again if you still have this issue.
