### ISSUE TITLE
Music App: All tracks play simultaneously when a call is recieved

### ISSUE THREAD

**Issue by playanything** [FlutterFlow/flutterflow-issues#3071]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For my published App [RAMSR-0](https://apps.apple.com/au/app/ramsr-0/id1667175093), there is a bug where all tracks are triggered, playing simultaneously when a call is recieved.

### Expected Behavior

The single track playing should resume when the call is rejected.

### Steps to Reproduce

1. Add container
2. Add Audio Player inside container
3. Upload MP3 as sound file
4. Repeat steps 1-3.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Significant impacy on usability.

### Visual documentation

![Screen Shot 2024-06-06 at 8 54 57 am](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/70f0e18c-c717-432f-814a-71dc762c95f4/9ff01fad-6ee7-4817-a9d2-289a620567db?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MGYwZTE4Yy1jNzE3LTQzMmYtODE0YS03MWRjNzYyYzk1ZjQvOWZmMDFmYWQtNmVlNy00ODE3LWE5ZDItMjg5YTYyMDU2N2RiIiwiaWF0IjoxNzE3NjI4MzcyLCJleHAiOjMzMjg4MTg4MzcyfQ.J0y3jLNgF1YDOz71QdTHfGmbz1rJhPv6v8ezgbticsQ)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @playanything<br><br>I wasn't able to reproduce this issue. We'll need further information from your side. What do you exactly mean by call? Which type of call is being received? Are you missing any details in the steps to reproduce?<br><br>We also need a bug report code so we can look into your project. You can generate that by clicking right on the widget tree and selecting the Generate bug report option.

Please let me know this details and if the issue still persists.

**Comment by playanything** [comment]
Hi Micaela,

Thanks for your reply

By call I mean a phone call.

The app has 4 pages, each with 10-15 audio tracks.

Here is the bug report
ITFThvLluIVPn7wA+KXcasd4oD8UI0MdXOczitVEew4bCIj4PZYuefT4aVpBTfKzaHw7IVX+/XkF+fSKv9r9MMIrPTKubr45zs9QWhPPbFigRJS3PpeKY3NQDZhbJ0yD17aFnQpNKs9aSU5l3Gaue9yUdz6Cf9qOYwx5e6fDbOY=

Kind regards
Carlin

**Comment by msusviela** [comment]
Hi @playanything. So sorry for the late response. Is this fixed for you in the latest version?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
