### ISSUE TITLE
FlutterFlow does not offer SEO and Sitemap features for subpage indexing on Google

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3076]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The platform lacks features for SEO and Sitemap, not to be confused with indexing! For example, in the FlutterFlow Marketplace, the SEO tags do not change when navigating between different items. This means that all pages share the same title and description, harming the visibility and effectiveness of SEO and inbound marketing. In contrast, other platforms like Bubble and Webflow allow for detailed and specific site maps for each page, ensuring better search engine optimization.

### Expected Behavior

FlutterFlow should provide Google with a complete site map, including titles, descriptions, images, and header hierarchy (H1, H2, etc.) for each page. This is essential to ensure that content is crawled and ranked correctly in search results, especially for ecommerces, blogs, and inbound marketing campaigns.

### Steps to Reproduce

1 Access the [FlutterFlow Marketplace](https://marketplace.flutterflow.io/home).
2 Inspect the page and look for "open graph & SEO tags". You will see:
title= "FlutterFlow Marketplace"
description= "Explore the FlutterFlow Marketplace for a curated selection of widgets, templates, and custom plugins tailored to suit your development needs."
3 Now, navigate through other subpages of the FlutterFlow Marketplace and inspect different pages. Notice that the SEO tags always remain the same as the home page, regardless of the subpage.
4 Observe that the title and description do not change when navigating between different items.
5 Take the title of any product within the marketplace and search it on Google. You will see that it is not found. Example: Search on Google: site:flutterflow.io "Digital Banking Assistant". You won't find anything.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Context

This issue has affected the visibility and ranking of my application's pages in search engines. I am trying to improve the SEO of my application to increase the visibility of each page of my blog, but the pages remain invisible in Google searches. Thus, no matter how much content I create, it becomes useless for organic searches and inbound marketing campaigns.

### Visual documentation

![img-print-bug](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2167a60d-06a0-4fd6-8eed-9c5f150c2bfa/dec985f5-25d9-4d52-b2b2-274476795f78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMTY3YTYwZC0wNmEwLTRmZDYtOGVlZC05YzVmMTUwYzJiZmEvZGVjOTg1ZjUtMjVkOS00ZDUyLWIyYjItMjc0NDc2Nzk1Zjc4IiwiaWF0IjoxNzE3Njg2MTQwLCJleHAiOjMzMjg4MjQ2MTQwfQ.ZD4rvEOnSYlx0EVJH7RTRs--L6AqBdnhRaLi8KBqZQ0)

### Additional Info

*No response*

### Environment

```markdown
FlutterFlow last version
Platform: Web
Browser name and version: Chrome 107.0.5304.110
```

**Comment by msusviela** [comment]
Hey @SauloSA, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
