### ISSUE TITLE
Custom Widget property tied to PageState receives null on change and cannot be checked for null

### ISSUE THREAD

**Issue by gams1976** [FlutterFlow/flutterflow-issues#3077]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a custom code widget, that has a String? property. On page, I tie this property to a String? Page State. When i change this state in code, the widget crashes (even tough I check for nulls, it gives a null check error). I have made experiments and if i reference the property, it crashes.

The code below causes the crash for null value:
String getGroup(String? groupType, ClientStruct client) {
    if (groupType != null) {
        return groupType;
    } else {
      return "null";
    }
}

Current widget definition:
class ClientGroupList extends StatefulWidget {
  const ClientGroupList({
    super.key,
    this.width,
    this.height,
    this.clients,
    this.onItemClick,
    this.groupType,
  });

final double? width;
  final double? height;
  final List? clients;
  final Future Function(ClientStruct client)? onItemClick;
  final String? groupType;

@override
  State createState() => \_ClientGroupListState();
}

### Expected Behavior

not crash if null checked

### Steps to Reproduce

create custom widget with property
create page state
attch widget proporty to state
Change page state with action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glcn15YpNpbxK1bqBKe9VqGIvKUh9bZc0r9pEGEshfJvmPJkhduDBTBFLYteLfVVUemCKimYy/86MjeLxJvA5EzmcGr5AyoRXQRbNWnqtaYTWDpGBOX9BBdlQIFOB4bWK3QokPvBvcnw46176e/CNG3qCf9qOYwx5e6fDbOY=

### Context

Avoiding using custom widgets

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f5e07e1d-fa2f-4606-9c09-7ef1026acec0/f232e794-909b-4077-a1d0-80212a6c14be?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNWUwN2UxZC1mYTJmLTQ2MDYtOWMwOS03ZWYxMDI2YWNlYzAvZjIzMmU3OTQtOTA5Yi00MDc3LWExZDAtODAyMTJhNmMxNGJlIiwiaWF0IjoxNzE3Njk1MzQyLCJleHAiOjMzMjg4MjU1MzQyfQ.PvZzrMR1VZPmo92-ODWMKcR7tW0oNvCe6591z6Rn7N4)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/acc4851f-84d9-4b9e-aa66-00d51e79673a/9b4c31af-e91a-4fec-b16d-f07109edc931?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hY2M0ODUxZi04NGQ5LTRiOWUtYWE2Ni0wMGQ1MWU3OTY3M2EvOWI0YzMxYWYtZTkxYS00ZmVjLWIxNmQtZjA3MTA5ZWRjOTMxIiwiaWF0IjoxNzE3Njk1MzQyLCJleHAiOjMzMjg4MjU1MzQyfQ.hcYUI0tIbKEah1sXA_7ZqWdPB1qleUQmiCPPiT_0l1E)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6c25da0f-c24e-4804-881d-76a044cde32b/af66421f-3a92-462e-90e7-bc70ed5c3422?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YzI1ZGEwZi1jMjRlLTQ4MDQtODgxZC03NmEwNDRjZGUzMmIvYWY2NjQyMWYtM2E5Mi00NjJlLTkwZTctYmM3MGVkNWMzNDIyIiwiaWF0IjoxNzE3Njk1MzQyLCJleHAiOjMzMjg4MjU1MzQyfQ.jPLrbr-Z6EfmBkDXwLRSwDCL_5vpiwA78O4P6sNOqMk)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/eeba3662-74dc-4668-8c61-4589b07cacec/e307093a-6748-4a58-9974-075db6dbae7e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZWJhMzY2Mi03NGRjLTQ2NjgtOGM2MS00NTg5YjA3Y2FjZWMvZTMwNzA5M2EtNjc0OC00YTU4LTk5NzQtMDc1ZGI2ZGJhZTdlIiwiaWF0IjoxNzE3Njk1MzQyLCJleHAiOjMzMjg4MjU1MzQyfQ.2-caiByCQHZSXfsWPbeJW0mnWEmA_ablBjcDUUFZaCc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.54+
- Platform: Chrome
- Browser name and version: Chrome Versão 125.0.6422.142 (Versão oficial) 64 bits
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment]
Hi @gams1976! I noticed that the JSON file you are loading inside the Lottie animation is causing the error. The file is stored in Supabase, review if only authenticated users can access the resource.

**Comment by gams1976** [comment]
@paulperez-dev doesn't make much sense but i deleted all the lottie animations and still the error is happening. 
The lottie animations where in a different page... And not related to the update state operation.

The problem happens in page HomePage When i change the page state "GroupingType".

**Comment by gams1976** [comment]
@paulperez-dev

**Comment by paulperez-dev** [comment]
Hi @gams1976! Sorry for the late response. Can you please share a new bug report code with your current configuration from the actual page where you are facing the issue?

Also, please make the Lottie file accessible to anyone on the internet.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
