### ISSUE TITLE
A local variable of a component that is used in a list view should be unique to every instance of the component in the list view.

### ISSUE THREAD

**Issue by BernhardRitz** [FlutterFlow/flutterflow-issues#3080]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a component with a local boolean variable. The component is used in a list view and when I change the local variable for one item in the list view then it is changed for every item in the list view (which would be the correct behavior for an app variable but not a local variable?)

### Expected Behavior

The local variable of the component that is used in the list view only changes the local variable for one individual instance of the component in the list view when change for that specific component is triggered. All other component instances should keep their local variable status.

### Steps to Reproduce

(1) create component myComponent with a local boolean variable
(2) add myComponent to a list view
(3) change local variable value for one instance of myComponent in the list view
(4) check if the other instances of the component have changed their local variable value --> they should not change because the variable should be local to the instance of the component (but they all do change :-))

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glMmAxItOtbxD+KqIY+9WgSkXG1wgR700sd4bGA0dCJzuPLMQdvWlalVWXf26S2w/MUSmmmIG+c7LvYbTO/lfZDisbN1l+KtIWjzjeHGna5OBCJbpSkElDeJPBW673KbYrCRCXbBpZXwd2jmmFe6USjTsJJv1ImdISq/LZO4=

### Context

I try to change to another icon in a component that is used in the list view and want to change it for only one item of the list view.

### Visual documentation

![BugReport](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0568297d-a100-4fb7-9aaf-700a27d18534/b0114327-a979-4a6c-9ec4-5558b537a481?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNTY4Mjk3ZC1hMTAwLTRmYjctOWFhZi03MDBhMjdkMTg1MzQvYjAxMTQzMjctYTk3OS00YTZjLTllYzQtNTU1OGI1MzdhNDgxIiwiaWF0IjoxNzE3NzYyMDA2LCJleHAiOjMzMjg4MzIyMDA2fQ.7gcIECZ_PQXKj21VFbJPFkSUN1WpjyaAtEPGF2ubmx8 "=1240x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: Windows 11
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @BernhardRitz

Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue and I wasn't able to reproduce it from a blank project. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by BernhardRitz** [comment]
I created a new test project and it behaves as expected (I tested it with a json list and not an API call as the original project).
