### ISSUE TITLE
Creating Subcollections in Firestore

### ISSUE THREAD

**Issue by devjoter** [FlutterFlow/flutterflow-issues#3083]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to create subcollections in Flutter Flow using Firebase Firestore. While creating a subcollection, for example "data," for different parent collections, such as "users" and "orders," Flutter Flow gives me an error: 'Name "data" already in use.'

This is major issue.

### Expected Behavior

In Firebase Firestore, I am able to create subcollections with the same name under different parent collections without any problem.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3386380/44b9e2c0-7033-4c2e-b8a8-c8a422ab1942)

### Steps to Reproduce

Steps to Reproduce
Open Flutter Flow and navigate to the section where you can create subcollections.
Create a parent collection named "users."
Under the "users" collection, create a subcollection named "data."
Create another parent collection named "orders."
Under the "orders" collection, attempt to create a subcollection named "data."
Observe the error message: 'Name "data" already in use.'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klsn1z4pNj7xY17X5bcEwhjkvQnomTL07ttYbZxUjIuPtBJh/ZeOlUxBvQu2mSmlhHFWbkT8H+dWNkeLhGOw7CxGBfrk4+LViZwKVUXq8RbqVDbqdPGtAI+FQI26X37WkkRVQXe5pSkIN2UyHfOSsbDTfCZu/Zwh9f6PHaOI=

### Visual documentation

![08 06 2024_15 49 26_REC](https://github.com/FlutterFlow/flutterflow-issues/assets/3386380/505e08c5-038b-4baf-b9e2-0e5bf577879d)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3386380/33ebb59e-0cd9-4006-a5b4-45a86618eab8)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3386380/e3ca2a1e-1a79-44d3-9605-d99dbeb69786)

### Environment

```markdown
- FlutterFlow version: v4.154+
- Platform:any
- Browser name and version:any
- Operating system and version affected:any
```

### Additional Information

I need to perform collection group queries over these subcollections. The ability to create subcollections with the same name under different parent collections is crucial for my data model architecture. This restriction affects my business operations as it limits how I can structure my data and perform efficient queries across subcollections.

**Comment by tomkosmita** [comment]
Same issue here.
It actually blocks my data architecture design not being able to use all Firestore capabilities as expected. :/

**Comment by lobo1111** [comment]
I have the same problem. Any chance for that feature?

**Comment by rzambroni** [comment]
Hey @devjoter, i was able to replicate the issue you are describing, i'm asking internally to determine if it is a bug or if there is a limitation on that feature. Will keep you posted. <br>Thanks for the report!

**Comment by tomkosmita** [comment]
> Hey @devjoter, i was able to replicate the issue you are describing, i'm asking internally to determine if it is a bug or if there is a limitation on that feature. Will keep you posted. <br>Thanks for the report!

Any news oh this one?

**Comment by rzambroni** [comment]
Hey guys, the team confirmed it was design that way for simplicity. I'll make a request to enhance the feature and not to restrict a valid way to name sub-collections.  

In the meanwhile, as a workaround you can prefix sub-collections so they have a slightly different name. I know it is not ideal but it might take a bit for the request to be prioritized and implemented.

Thanks!

**Comment by devjoter** [comment]
@rzambroni 
Thank You very much for response.

In my case I have to wait until it will be fixed.
This is one of the key ideas behind using firestore  subcollections and Collection Group Queries.
There is no workaround...

Please let know the team that this is major issue.

Thank you very mych for your support and Best Regards for all team for great work so far.
