### ISSUE TITLE
Start Recording Action does not work on a published iOS web app even after giving permissions

### ISSUE THREAD

**Issue by KhDu** [FlutterFlow/flutterflow-issues#3084]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Per title. Start/Stop recording action does not work on iOS web (tested on iPhone both Safari and Chrome). The microphone icon appears then quickly disappears. Prompting the user for permission does not fix the issue. Nor adding custom permissions (NSMicrophoneUsageDescription).

Tried playing with web setting nothing changes.

### Expected Behavior

Webapp ask for microphone permission. User click agree. recording icon appears and stop instantly (also the volume bar appears for some reason). Action fails.

### Steps to Reproduce

1. Clone this recorder project made by FF team (https://app.flutterflow.io/project/audio-recorder-app-mdwybo)
2. Enable web
3. Publish app in the web tab
4. open website on iOS device
5. Click record

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l/KAx5NOmNxE1qr+Y8dFmik5JkQmaI0o0O1BaCwqGJToPLUMPsneVFRuZrzmSmNiM038jn4exvfqhobhCcI6JSiBbLZ6zagBbgL/QXG5MIyyCpG7fW1QGe5TGFy017u3vyJCKtpoST2Ey2FueuYAPcHZy3OFcCD86LJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/27917475/facabd27-deef-454a-8d11-54cdb88d066a

### Environment

```markdown
- FlutterFlow version: v4.1.54
- Platform: Web (Specifically iOS Web)
- Browser name and version: Safari (iOS 17.5.1)
- Operating system and version affected: iOS 17.5.1
```

### Additional Information

Stopped me from progressing in my project which needs voice recording for a PWA

**Comment by paulperez-dev** [comment]
Hi @KhDu! That example was not meant to be deployed to web. Notice the following warning after enabling the web platform: 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3095ca40-54ae-4fa1-84c9-9fe97990c5b4/50e5b1e7-267f-49ba-9b47-a2023643442e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMDk1Y2E0MC01NGFlLTRmYTEtODRjOS05ZmU5Nzk5MGM1YjQvNTBlNWIxZTctMjY3Zi00OWJhLTliNDctYTIwMjM2NDM0NDJlIiwiaWF0IjoxNzE3ODg2NDU5LCJleHAiOjMzMjg4NDQ2NDU5fQ.7eLZNj-dt1o_7bl77QJ0nmh5N4Bwd67bmamOxwYN3UQ " alt="image.png" width="288" height="180" />

I'm closing this issue.

**Comment by KhDu** [comment]
Just wanted to say that it works fine on MacOS web. And the issue is not with the permission the action clearly starts on iOS but it stops immediately. If you remove the 'Request Permissions' action and manually give permissions on the web app it still won't work.

**Comment by arelventures** [comment]
@paulperez-dev Is there any way you could reconsider this? These exact steps work on Android Chrome web, work on most desktop browsers (or maybe even on all of them), and work on Mac OS Chrome web. The feature is almost perfect and ready for use, would just need to fix the odd behaviour on iOS.

Thank you!
