### ISSUE TITLE
Latest FF windows installer does not install at all

### ISSUE THREAD

**Issue by hughgallagher** [FlutterFlow/flutterflow-issues#3085]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Download the latest FF Windows installer in order to run FF locally on a Windows 10 laptop

### Expected Behavior

the installer should run but gets stuck in some kind of infinite loop --- spinning circle displays but does not stop... left it running for 30mins+

### Steps to Reproduce

1. Download the latest FF Windows installer in order to run FF locally on a Windows 10 laptop

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4996337/5d9d524b-130e-4151-8cf7-55158186e940)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: Windows 10
- Browser name and version: N/A
- Operating system and version affected: Windows 10
```

**Comment by paulperez-dev** [comment]
Hi @hughgallagher! I was able to install and open the latest release on my Windows machine. Can you please share more details like available storage space, if Windows 10 is up to date, if it was recently restarted, screen resolution, and any other useful information.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
