### ISSUE TITLE
Absurd Slowness

### ISSUE THREAD

**Issue by artur021218** [FlutterFlow/flutterflow-issues#3086]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attention FlutterFlow team, since 06/05/24 I've been experiencing absurd slowness when creating debug/run and especially when trying to create the app for the web, I've been at this for 3 days. Is there a problem? How to solve?
Note that I access pages from other sites/yt/speed tests and everything is ok, only with FF is the severe slowdown. Can you help me?

### Expected Behavior

solve this slowness

### Steps to Reproduce

open any app
click into generate DEBUG, very slow
click into generate RUN, very very slow
click into generate APP WEB, absurd slowness !!!!!

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no code reported

### Visual documentation

![slow](https://github.com/FlutterFlow/flutterflow-issues/assets/45536313/b2d06e7b-d1d4-4740-899c-f224db7e9bc9)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform:windows
- Browser name and version:crome
- Operating system and version affected: windows 11
```

**Comment by rzambroni** [comment]
Hi @artur021218, sorry to hear you are having performance issue while using FlutterFlow, we don't have any other reports at the moments that might be causing abnormal latency, have you tried using a different platform as an alternative? like the web-app for example.

<br>Unfortunately there is no much we can do on our end to help you, if you are still experiencing bad performance i would recommend following up with our support team, you can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. They are our best chance to the this type of issues sorted out.

Thanks!

**Comment by artur021218** [comment]
I will try, because today in the community, several claims also
Grateful Rzambren
