### ISSUE TITLE
Data schema field does not support for List<List<String>>

### ISSUE THREAD

**Issue by sonbui00** [FlutterFlow/flutterflow-issues#3088]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Data schema field does not support for data type `List<List<String>>`

### Expected Behavior

Data schema field support for data type `List<List<String>>` (maybe just allow JSON or Dynamic for data type)

### Steps to Reproduce

Data Schema > Data Types > Choose a data type or create new > Add field

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Visual documentation

Current support data type for Data schema
<img width="637" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6426576/19894c0e-f1f9-4973-84e6-98af3c8facd5">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @sonbui00, you can indicate that your datatype is a list of strings (or any other datatypes) when adding the field.

Is that what you were looking for?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/83ad90b7-bf54-4733-bf77-760c2f51c2e9/36e23561-32b8-4738-b2c1-3a09a6fcf34d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84M2FkOTBiNy1iZjU0LTQ3MzMtYmY3Ny03NjBjMmY1MWMyZTkvMzZlMjM1NjEtMzJiOC00NzM4LWIyYzEtM2EwOWE2ZmNmMzRkIiwiaWF0IjoxNzE4MDQ1NTMyLCJleHAiOjMzMjg4NjA1NTMyfQ.vhraaBy66cEnWX6aLpLQYtrQ49QQKChuONI1KiA5Krc " alt="image.png" width="500" height="406" />

**Comment by sonbui00** [comment]
@rzambroni your suggestion is `List<String>`
I'd like to have `List<List<String>>`
They are different

**Comment by MartinLockheart** [comment]
@sonbui00 I'm not a dev, but have you tried the following: 

1) Create a custom datatype with a field that is `List <string>`
2) Use that custom datatype as a list

That way you can have a list of lists of strings.

**Comment by sonbui00** [comment]
@MartinLockheart I know that way, but the json data from API, I'd like to parse the response data to a custom type

**Comment by rzambroni** [comment]
@sonbui00, have you seen this documentation: [https://docs.flutterflow.io/data-and-backend/api-calls/api-calls-101#create-custom-data-type-matching-to-json-structure](https://docs.flutterflow.io/data-and-backend/api-calls/api-calls-101#create-custom-data-type-matching-to-json-structure)<br>Perhaps it is helpful to solve your specific usecase.

**Comment by sonbui00** [comment]
@rzambroni the flutterflow does not have support for `List<List<String>>` for field type (only supported `List<String>`) -> the guide can't help

**Comment by rzambroni** [comment]
Yeah, i know it doesn't, just trying to provide a workaround that might be helpful to solve your use case, mainly because making a Feature request might take a while to be prioritized and implemented.

**Comment by sonbui00** [comment]
@rzambroni Thank you. I can handle anything with custom code. So just want to report the issue to the team

**Comment by rzambroni** [comment]
going to close this as it will be tracked in our feature/enhancement request backlog
