### ISSUE TITLE
Share Action doesn’t work on iPad

### ISSUE THREAD

**Issue by palletmouth** [FlutterFlow/flutterflow-issues#309]
the share button works fine on iPhone and Android devices, but doesn’t seem to work on iPad or iPad mini. The button animates and it looks like something is happening but nothing shows up. I need this to function because it’s the only thing that Apple are failing my app on

https://pub.dev/packages/share_plus

iPad
share_plus requires iPad users to provide the sharePositionOrigin parameter.

Without it, share_plus will not work on iPads and may cause a crash or letting the UI not responding.

To avoid that problem, provide the sharePositionOrigin.

For example:

// Use Builder to get the widget context
Builder(
  builder: (BuildContext context) {
    return ElevatedButton(
      onPressed: () => _onShare(context),
          child: const Text('Share'),
     );
  },
),

// _onShare method:
final box = context.findRenderObject() as RenderBox?;

await Share.share(
  text,
  subject: subject,
  sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size,
);

Cheers

Jim

**Comment by palletmouth** [comment]
Is there any chance this can be looked at, it's the ONLY thing that Apple have picked up on for Rejecting my App and I really want to get it published. please

Cheers

Jim

**Comment by palletmouth** [comment]
Hi, 

Thanks for that? So what is my best solution, my app is ready for publishing and the only thing that Apple have failed it on is that feature and annoyingly my app is all about sharing.

await Share.share(
text,
subject: subject,
sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size,
);

It looks to me that only 2 params are missing, could this be done as a custom function?

 await Share.share(
        '${'${FFAppState().shareURL}${listViewEventsRecord.eventId}'}');

**Comment by agreaves** [comment]
Hi @palletmouth, thanks for the bug report! This should be fixed in the next release (some time in the next few days), however in the meantime you could certainly make this work with a Custom Action instead of the Share Action.

Your Custom Action would just need to take in a `String` for the item you want to share, and then check "Include Build Context" so that you can use the above bounding box code inside the action.
