### ISSUE TITLE
Project no longer compiling after Flutterflow dependencies update

### ISSUE THREAD

**Issue by main-silva** [FlutterFlow/flutterflow-issues#3092]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All was working fine till few minutes ago when compilation was no longer working.

### Expected Behavior

No expected behavior unless a normal compilation.

### Steps to Reproduce

1. Access test mode for the page "UploadImage"

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT80z8r13ItPm9sC0KXyLO9ajikXQ1h+UOYslu0bFBEbfZznBJkqevfvN1FuYNyodEFpGkaYhmEJw8LSvobfCftdOResc745/qlyTx/PRk6iMb67DJOwSkZ6AdxRChGnyLSJvB0nGMtvTHs3w2aPNty9SgvqJp/4DkYvHv6JOr7DnguYHhDrFyJFzTc4DnmrEfljIVDq+f6QspZl1eTjzw==

### Visual documentation

![imagem](https://github.com/FlutterFlow/flutterflow-issues/assets/5722755/8c652788-9071-40f0-b553-6e5eb4e5a85b)

### Environment

```markdown
- FlutterFlow version: v4.1.54+
```

**Comment by zetabrands** [comment]
Also getting failures deploying to iOS now with the flutter upgrade necessary for CodeMagic to compile. Prob related to the same changes.

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by msusviela** [comment]
Hi @zetabrands. We need more info to replicate this issue. Could you please give us the steps to reproduce it from a blank project?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
