### ISSUE TITLE
When a DataType key is a "-1" or "+1" the build fails and you cannot test the project

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#3093]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when there is a datatype with a - or + in the key the project fails to build

### Expected Behavior

Either it should build without any issues or there should be a warning that if there is a - or a + in the key that will not compile

### Steps to Reproduce

1. create a project 
2. Add a dataType
3. try to export code or run a test mode
4. Get a Build Failed

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMn634Vgrt9c187pbcFGjiAXOVw+TLJEpu0bWUkbGO/4BIYDdsn8VFBBOdSzaH1EHFKYo3MF7vTKjtnTOPUnEzqeUYRD+sxbERPPbH6gMqanDJeCPHYmM59UfRWx0J2RvRZ4GPptWUIn2juIOuiyTT6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1916" alt="SCR-20240610-kfvj" src="https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/93989600-19b5-492a-af83-f5dd9ba6781c">
<img width="1920" alt="SCR-20240610-kfsn" src="https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/136c1838-d711-46bc-b710-33c8a15686b2">

### Environment

```markdown
- FlutterFlow version: v4.1.54+
- Platform: web and desktop
- Browser name and version: chrome 125.0.6422.142 
- Operating system and version affected: macOS Sonoma 14.5 (23F79)
```

**Comment by rzambroni** [comment]
hey @joekman990, i was able to replicate the issue you're describing. WIll send it to the team so we can improve the validation on the Field Name. Thanks!

**Comment by joekman990** [comment]
Thanks!!

**Comment by joekman990** [comment]
I believe this was resolved in the last update thanks!!
