### ISSUE TITLE
Multiple bugs to report

### ISSUE THREAD

**Issue by shadzic** [FlutterFlow/flutterflow-issues#3094]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

**1. I cannot manage content in flutterflow firestore: it does not work on Chrome but works on Firefox.** 
The message appears "could not create an account as firebase@flutterflow.io to your Firebase project. Make sure "Email sign-In" is turned on for your firebase project, and try again"

My current setup:

- [x] firestore authentication enabled
- [x] firebase setup and connected and config files generated
- [x] firebase@flutterflow.io is a user in Firestore Authentication
- [x] firestore security rules are deployed, the following is true for firebase@flutterflow.io 
```
match /{document=**} {
      allow create, read, write: if request.auth.token.email.matches("firebase@flutterflow.io");
    }
```

**3. Some changes I make to the app are not saved at all**
For example, I created a "is_test_user" flag both in user collection and during sign-up, passing page state parameters to the next page in order to flag test_users and this change has now 3 times been deleted from the app.
I read online that it might be due to having multiple browser sessions opened (which I have because of bug number 1), but even when I closed all other browser sessions and saved the project, the changes would be deleted the next time I log in

Here is some more details:

FlutterFlow v4.1.54+ released June 4, 2024
Flutter version is 3.19.1

=> This happened since the latest release of June 4th.

### Expected Behavior

1. Manage content from Flutterflow also from Chrome and not only from firefox
3. Changes made to the app should be saved

### Steps to Reproduce

I honestly don't know how to reproduce any of the bugs - exactly because it is supposed to work and does not.
I can provide more information about my configuration setup though

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wy8mB34p2vsBE1q6JK+9ajSQ4GDsibY08msJETis8GZT0B4kcYs+kfklUOPWkSglteWKZuDsX/MmPjYbTU/YrPTWtfqpxyqp2FgLwQjq6aL6wCr63b39tI/JWJn6n4cOZ2CMnPfpfc1466k2UCvO9fC3dNrL3IVQ3GOaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![FF_Issue1_Chrome_notworking_BLURRED](https://github.com/FlutterFlow/flutterflow-issues/assets/8168762/591e87c1-15c3-4a2c-8815-c9b545d057db)
![FF_iSSUE1_Firefox_working_BLURRED](https://github.com/FlutterFlow/flutterflow-issues/assets/8168762/c09877da-c150-4426-80f7-19042fe829f7)

### Environment

```markdown
- FlutterFlow version: 4.1.54+
- Platform: Web
- Browser name and version: Chrome Version 124.0.6367.91 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 20.04.6 LTS
```

### Additional Information

Issue1: I followed the steps described in the community forum: https://community.flutterflow.io/community-tutorials/post/could-not-create-an-account-as-firebase-flutterflow-io-to-your-firebase-hB3WXjnG7eMoiMZ

Issue2: followed the steps in the community: https://community.flutterflow.io/troubleshooting/post/test-run-modes-are-not-updating-FcDcwJLapUWwK9s

**Comment by paulperez-dev** [comment]
Hi @shadzic! So sorry you are facing these issues. For the first one, can you try creating a new project on Chrome, connect it to Firebase, and verify if it works?

Regarding the second issue, are the changes visible if you restart the session?

As you mentioned, this issue is caused by having multiple sessions open. Log out and clear the cache from the browser you won't use.

**Comment by shadzic** [comment]
Hi @paulperez-dev Thank you so much for your promptly reply!
Regarding the number 1: yes I have done this and I am able to see it! That's why I am very confused, why it does not work for the very first project that we have. Obviously, we already have some data in, that is why I cannot change.
Regarding number 2: so sorry, this was a mistake on my end, I have removed it
Regarding number 3: OK I will try to clear the cache. Because actually, at the moment I made the changes, I had only one session opened, which makes it confusing. I am now trying to "save" the project with ctrl-S: do you know if there could be a way for me to save progress with certainty i.e. without running into the risk of changes not being saved?
Kind regards,
Selma

**Comment by shadzic** [comment]
Hi @paulperez-dev 
We are facing again the same problem. I made changes to the app in FF. Then I logged out and asked my colleague to test the app. He tested the app and then logged out. Now I log in again and all the changes I have made are gone.

To clarify: is this single user behaviour based on the email address login or on the IP address (i.e. per computer) ?
If it is the latter, it means that we cannot share and work asynchronously on the same project as a team, without having a Team Plan.

The last assumption that we have is: the web version does not work properly and I will try to use the Windows Desktop App instead. 
If that last try does not work, it means that we cannot work with FF anymore, because we cannot afford to have our work erased all the time. I understand that the FF team wants to incentivise people to buy the Team Plan, however that is not something we are willing to do if the platform does not work with single user based on email address. Collaborative work is essential to what we are doing.

I hope this clarifies the context and that you can provide some answers.
Kind regards,
Selma

**Comment by paulperez-dev** [comment]
Hi @shadzic! Sorry for the late response, I missed the notification of your response. Is this behavior still present in the newest release?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by geanusksama** [comment]
Estou enfrentando o mesmo desafio da colega, tenho uma APP e uma aplicação web e na web consigo logar e criar contas, ms no APP não faz login e me da essa msg

Could not create an account as firebase@flutterflow.io to your Firebase project.

Make sure "Email Sign-In" is turned on for your Firebase project, and try again.
