### ISSUE TITLE
Reset Form Fields Action on Dropdowns with Multi Select allowed doesn't work.

### ISSUE THREAD

**Issue by vianneypercq** [FlutterFlow/flutterflow-issues#3095]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Following the “Reset form fields” action on a button, multiselect dropdown boxes are not unchecked.

### Expected Behavior

Multiselect dropdown boxes should be unchecked after the action on tap is done on the button.

### Steps to Reproduce

1. Create Dropdowns with Multi Select allowed
2. Create a button
3. Add an "on tap" action to the button with "Reset form fields" action and select the dropdowns to reset

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk+fqy5dOmMNc1qrubMdB/SoRQ0Q8R4IsscsZa0kdB4joPLJ/eeLBMhZWXuG8TWlhHGGimnwF7t7KiPGSUvc6YUyuG5hC+KtfFw3NUXq8RbqMO86OWWtPO5pWGmqe0qTUhgp5ObZ1W3dl6066Fe6yYDLfGZu/Zwh9f6PHaOI=

### Visual documentation

![CleanShot 2024-06-10 at 17 54 02@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/62253051/2e59828b-ae81-466c-b163-932f3c7190c7)
![CleanShot 2024-06-10 at 17 59 16@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/62253051/0be6fea1-96f2-44a3-b300-5c7126785390)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform:
- Browser name and version: Chrome 125.0.6422.114
- Operating system and version affected: Mac OS 14.5 (23F79)
```

**Comment by rzambroni** [comment]
Hey @vianneypercq, i'm not being able to replicate the issue you are describing, seems to be working fine on my end. Tested in a blank project. Is it happening consistently for all drop-downs in your project? have you tested on a blank project? i checked your project and the code generated and it seems to be fine.

**Comment by vianneypercq** [comment]
Hi @rzambroni 

Thanks for helping.
I confirm that it happens consistently in the project for all drop-downs with Multi Select allowed.
I haven't tested on a blank project.

Could the bug be due to the fact that the “Define options” and “Initial Options Values” of multiselect dropdowns are linked to a Supabase query backend? There is no Reset issue with NO multiselect dropdowns linked to a Supabase query backend.

Find attached a video screenshot.
Thanks for helping.

https://github.com/FlutterFlow/flutterflow-issues/assets/62253051/09c82505-64e4-465b-8b91-a34e1d625499

**Comment by vianneypercq** [comment]
Solution : by removing the initial option values, the multiselect dropdowns can be reset.
Thanks to [M.Junaid](https://community.flutterflow.io/member/sbNijOz5ZU)
https://community.flutterflow.io/c/bugs/post/reset-form-fields-action-on-dropdowns-with-multi-select-allowed-doesn-t-URdARrY5sjRF8M0

**Comment by vianneypercq** [comment]
Solution : by removing the initial option values, the multiselect dropdowns can be reset.
Thanks to [M.Junaid](https://community.flutterflow.io/member/sbNijOz5ZU)
[https://community.flutterflow.io/c/bugs/post/reset-form-fields-action-on-dropdowns-with-multi-select-allowed-doesn-t-URdARrY5sjRF8M0](https://community.flutterflow.io/c/bugs/post/reset-form-fields-action-on-dropdowns-with-multi-select-allowed-doesn-t-URdARrY5sjRF8M0)
