### ISSUE TITLE
Start Audio Recording Action Not Working on iOS PWA view

### ISSUE THREAD

**Issue by shawnsma** [FlutterFlow/flutterflow-issues#3096]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The "Start Audio Recording" action in Flutterflow is not functioning properly on iOS web views. When attempting to start a recording, the action stops itself within 2 seconds and does not record any audio. This issue has been reported by multiple users in the Flutterflow community.

### Expected Behavior

The "Start Audio Recording" action should start recording audio and continue until manually stopped or a specified duration is reached.

### Steps to Reproduce

1. Create a Flutterflow app with a "Start Audio Recording" action.
2. Deploy the app and access it through a web view on an iOS device (e.g., Safari or Chrome browser).
3. Trigger the "Start Audio Recording" action.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XzcmA5ZV2pbwA1oSJKflapGA5JlB+a7gz0u5+GA01F5+vO7M2OuDUT3BZOMu6dFZUP2GJmm0x3PTVvuDPU8EFCByJbaZ91KlUZAyWXlKVbLqrEaW0RUFSRMVgIBWgzpuZpSMlFLNpLyUZ3E6qBefJaALDN5DVNjMeD8+hBN/Uog/nKzLOGn0Jg1ZSfCvr

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/169686954/b1fbd8e7-3a88-4f68-b29b-6b7a1eb5d666

### Environment

```markdown
- FlutterFlow version: v4.1.54+
- Platform:Web
- Browser name and version:Safari 17.5.1 and Chrome 125.0.6422.145
- Operating system and version affected: iOS 17.5.1
```

### Additional Information

Several users have reported this issue in the Flutterflow community:

@HumsDev: "Having the same issue here. I have an app where tapping clicking a floating button triggers an action with the start audio recording action. Everything works fine on chrome on the web, but can not get it to work on browsers on iOS. Tried safari and chrome. Any advice would be appreciated."
@Rayane 69: "I have the same problem, audio recording is not working on Safari iPhone, it stops after 2 seconds."
@Barrett Nash: "While it doesn't work on iOS PWA... it does work on Android PWA."
https://community.flutterflow.io/ask-the-community/post/start-recording-in-ios-web-fSqSZKPv94z19A8?highlight=Rcxfz3d85BNfjhs

This issue impacts the functionality of audio recording on iOS web views for multiple users.

**Comment by rzambroni** [comment]
Hey @shawnsma, thanks for the report. Unfortunately this is a known issue of the package FlutterFlow uses under the hood for audio, it was reported previously along with other issues so i'll mark this as a duplicate. [https://github.com/FlutterFlow/flutterflow-issues/issues/87](https://github.com/FlutterFlow/flutterflow-issues/issues/87)

It doesn't seem like the issue will be fixed any time soon so a request to replace this package for a better one was added to the team's backlog.

Sorry about the inconvenience.

**Comment by World-Salon** [comment]
Will this problem persist in iOS web only or also on iOS native app? Thank you!

**Comment by pcshawn** [comment]
Hey @rzambroni, quick question: will this problem persist in iOS web only or also in iOS native app? Just asking since we are not launching in the near future. Thank you!

**Comment by rzambroni** [comment]
as far as i know there are no similar issues on IOS and Android, this issue is only replicable on web in IOS (Safari, Chrome, etc)
