### ISSUE TITLE
Custom function return type is not well detected (string instead of integer)

### ISSUE THREAD

**Issue by btusca** [FlutterFlow/flutterflow-issues#3097]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a custom function with integer return type:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15097129/06f819a2-1464-48ad-8513-17350c5b083e)
`  if (date1 == null || date2 == null) {
    return 0;
  }
  final start = DateTime(date1.year, date1.month, date1.day);
  final end = DateTime(date2.year, date2.month, date2.day);
  int difference = end.difference(start).inDays;
  return difference;`
When I used it in a condition, its return type was detected as string, so I can't use comparables like "greater than" or "less than". 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15097129/88e176ef-0f3d-4700-809c-633dd1e3a815)
I tried creating another custom function and the problem persist.

### Expected Behavior

After creating a custom function with integer return type,
While using it within a condition, it should be detected as a integer.

### Steps to Reproduce

1. Create a custom function with an integer return type and two datetime parameters. all nullable.
2. create a text widget.
3. Set Text value with a condition, where the first value of the condition is the custom function.
4. condition will detect the custom function return type as String instead of integer.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsJV2rsRE7a6Jae9VqDoUJkx8RK00rNlud0wdCeOtP+wIZ+DeQFdBYuqHYXNqOlWKjmMF09WOj/PTMfcqKSuBbaJz/6VbUxDvVXygVYSwBbq0fXRAEeVjGWa11qa72xFTAOl1LkYN1FOqe+uQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15097129/06f819a2-1464-48ad-8513-17350c5b083e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15097129/88e176ef-0f3d-4700-809c-633dd1e3a815)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.54+ released June 4, 2024 / Flutter version is 3.19.1
- Platform: All
- Browser name and version: Chrome 125.0.6422.142
- Operating system and version affected: Windows 10
```

### Additional Information

I want to show/hide components depending of the days between two dates.

**Comment by btusca** [comment]
Here is with a dummy custom function also:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15097129/d90a85b9-2074-4ec7-b3d1-7969dce153fc)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15097129/04e0b383-d629-43c8-b20a-962950e67ebb)

**Comment by paulperez-dev** [comment]
Hi @btusca! I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by btusca** [comment]
Excellent! Thanks Paul!

**Comment by btusca** [comment]
@paulperez-dev any updates on this one? are you going to release some fix in the next days? Thanks!

**Comment by paulperez-dev** [comment]
Hi @btusca! I got an answer from the ENG team. This is not a bug. When formatting an `int` value it changes the returned type to `String`. If you want to keep the value as `int`, please change the '**Available Options'** of the custom function to '**No Further Changes'**. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3830cb91-7291-4f70-8bd4-d420c1955867/ed38e146-1a78-4aef-83a3-af634c4f0927?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zODMwY2I5MS03MjkxLTRmNzAtOGJkNC1kNDIwYzE5NTU4NjcvZWQzOGUxNDYtMWE3OC00YWVmLTgzYTMtYWY2MzRjNGYwOTI3IiwiaWF0IjoxNzE4NjM0MTAwLCJleHAiOjMzMjg5MTk0MTAwfQ.MKuiU8oylVVOWEvs_KOlOpfnh-PjLi41P1CCznts3RU " alt="image.png" width="796" height="743" />
