### ISSUE TITLE
VideoPlayer - Chewie Controller was used after disposed

### ISSUE THREAD

**Issue by WellDunDun** [FlutterFlow/flutterflow-issues#3098]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It seems like if you try to rebuild the current page before the VideoPlayer pre-loads (during its splash state) then it will crash due to disposing of the Chewie Controller.

EDIT: Now it's doing it even if the video is fully loaded.

### Expected Behavior

Smooth rendering and navigation without crashing.

### Steps to Reproduce

1. Create a project
2. Add a page
3. Add a VideoPlayer widget
4. Add page state called "currentIndex", non-nullable, set initial filed to 0
5. Add 2 button widgets with update page state actions to control "currentIndex". First action to increment by 1 and the second to decrement by -1, with rebuild current page enabled on both
6. Create a Data Type called video with a videoPath field
7. Create an app state of the video Data Type called videosList and enable is List.
7. Manually add a few URLs to videosList App State variable (please supply your own)
8. Test by using the buttons to navigate through the list

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khc/1z4ZIvttH+rntbe1KjjkUKW48TL07ttYbZxUjIuPtBJh/Osj4TxJpTse8S1NhHE2JmXwdpd2Nj+OTGPkDBzKYQYhP/5diegKXY3q8RLbUBqi8e0RPBeZPCHae4aWRpyZ7AM1pLlIW6nGAediUaATvN5O/Zwh9f6PHaOI=

### Visual documentation

I recorded this video to show what's happening and what I'm doing to trigger it. Please let me know if you need any other details or have trouble viewing it. I hope this helps make things easier for y'all!

https://drive.google.com/file/d/1kZ46mCSlsByyLR4zVcwembV7k9qHcC1Z/view?usp=sharing

### Environment

```markdown
- FlutterFlow version: 4.1.5.4
- Platform: macOS
- Browser name and version: N/A
- Operating system and version affected: macOS Sonoma Version 14.4.1 (23E224)
```

### Additional Information

I'd love to have this bug fixed! 💜

**Comment by WellDunDun** [comment]
Edited original post: 
- Added steps to reproduce

Proof of reproducible bug:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45949032/5e759d87-a7b1-4a61-be2f-2e5fa9c22f44)

**Comment by paulperez-dev** [comment]
Hi @WellDunDun! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

**Comment by WellDunDun** [comment]
Hey @paulperez-dev ! Thanks for the reply.

I added the steps to reproduce but included the bug report code from the original project, which is probably what you checked.

Here's another bug report code from the project where I reproduced it:

IT5Xj+fl049Jtbxd+KricMdVqCo5JlA5arxMj+xEdxQ1GOvmO5kUd+PUT3BZOMu6dFZUP2GJmm0y+aCOuN7iU/o4FByJbqJe/6VISQzyYH+WRr7XBcyBPnF9O+dgJkijzpuZuiJ4KspYWHhi2k+ACuSicCbaJKa3O2sRJfqXA53/p0qpHiXgG30Jg1ZSfCvr

Please let me know if you need anything else!

**Comment by WellDunDun** [comment]
Hey @paulperez-dev ! Sorry for tagging you again but I noticed that the label from Linear never updated after I replied to you last (5 days ago - within an hour of your reply). I just wanted to make sure this issue doesn't get closed, or something, since the system isn't updating the labels.

**Comment by paulperez-dev** [comment]
Hi @WellDunDun! I will check the new code, thanks!

**Comment by paulperez-dev** [comment]
Hi @WellDunDun! I can't run the project from the Bug Code you sent. Can you please verify you can run the app?

**Comment by WellDunDun** [comment]
> Hi @WellDunDun! I can't run the project from the Bug Code you sent. Can you please verify you can run the app?

Wow, that's weird! I just tried again and it works in both Test Mode and Local Run. 

Here's another bug report code:

IT5Xj+fl049Jtbxd+KricMdVqCo5JlA5arxMj+xEdxQ1GOvmO5kUd+PUT3JdOLyhSmw/PFu0jmUx/vvFud7hCOQHAzGVf6Jg+pdcUBXzQkmgRLahCKqgP3x9P+dNHkuV0J2RgRUmLvJedGMj3EyEfuqRFzbrJuPKOlUzROaHENz5+XC8Ahm6Xn0Jg1ZSfCvr

Please let me know if that works for you or if you would like me to do anything else. Thanks!

**Comment by WellDunDun** [comment]
Hi @paulperez-dev ! I know you're very busy, but could you please look into this? I was hoping that the upgrade to Flutter 3.22.2 and the upgrades to the chewie and video_player might've fixed it, but unfortunately, the issue persists.

**Comment by paulperez-dev** [comment]
Hi @WellDunDun! I isolated the video configuration as you have it and changing the state value does not crash the app. What you are facing may be more related to how you configured other screens or widgets, not the player itself.<br><br>The error shown also happens in native flutter. Consider asking for help in the community.

I will be closing this issue since this is not a FF bug. Have a nice day!

**Comment by WellDunDun** [comment]
@paulperez-dev Thanks for looking into it! I'm confused by your reply though. How could I replicate it across projects and from a fresh project if it's unrelated to the player?

Could you let me know what error you saw exactly? Was it this or the Chewie Controller was used after disposed one?
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45949032/e87ec9f6-ee33-433e-b91f-24840f5a17e6)

It looks like this is a common issue when the code isn't correct as shown [here](https://github.com/fluttercommunity/chewie/issues/129) and [here](https://stackoverflow.com/questions/58955831/flutter-video-player-dispose) which are all related to the player.

Does this mean I should try to convert the video player to a component so it properly disposes and re-initializes better?

I don't think we should close this issue just yet, and if we can narrow it down, we could include an error/bug warning in the FF editor to help users avoid this same issue.

Any additional insight would be beneficial and greatly appreciated! 

PS I'm usually the one helping people in the community. Also, I already brought this to other experts and none of us were able to fix it.

CC @bulgariamitko @leighajarett

**Comment by paulperez-dev** [comment]
Hi @WellDunDun! It may be because your state variable is empty (the list from where the player set the video source).<br><br>The error I got was 'the controller was already disposed'.

An alternative to avoid this error is to have a page view (each page with its controller), and the source can be read from the state based on the page index.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
