### ISSUE TITLE
Confusion on API Access Key setup.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#310]
## Expected behavior (required)

- Should show some meaningful indication(message) if the developer set API Access Key for `Deploy to Play Store`.

## Current behavior (required)

- I helped one of my FlutterFlow study member.
- And he said to me he tried but failed to set up the API Access Key.
- I told him to press `Deploy to Play Store` and the deploy will fail. But he can download the AAB after building and upload the AAB manually onto the Play store console.
  - And he did many times.
  - Every time he did, there was an error message like `The version code is already exist`.
- I check if the version code is already exist. and it was really exist and I realized the `API Access Key` was properly set even if there is no indication. I think this is confusing.

## To Reproduce (required)

- After setting up the `API Access Key` from Play store console, there is no indication whether it is set or not unlike `App Store Key Setting`.

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

- It is really confusing. I really thought the `API Access Key` was not set.

## Screenshots / recordings
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/5080329/210244082-10e53808-d38b-41cf-813d-fc3a1eeec286.png">

## Your environment
* Version of FlutterFlow used: v3.0 December 30, 2022 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome, Version 108.0.5359.124
* Operating system and version (desktop or mobile): iMac 2020, macOS Ventura 13.1

**Comment by yoheisoito** [comment]
It would indeed be helpful to fix the link when the user clicks on the Instructions button. It currently returns a 404.

https://docs.codemagic.io/knowledge-base/google-services-authentication/

**Comment by wenkaifan0720** [comment]
Hi @thruthesky, @yoheisoito. I'll fix the link when the user clicks on the Instructions button. I don't understand which part of the UI is confusing. It is saying "Credentials Set" after you've uploaded your API key.

**Comment by wenkaifan0720** [comment]
Since this is not really a bug, I'll close it for now.
