### ISSUE TITLE
Missing demo data for sample apps

### ISSUE THREAD

**Issue by qbuchanan** [FlutterFlow/flutterflow-issues#3100]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Description:
Currently, FlutterFlow provides several very nice sample apps. However, when trying to use any of the sample apps, there are no included sample database data or assets to allow users to try out the features of the app. Additionally, there are no data editors to help upload any of the missing database information.

Example Issue:
In the Meal Planner sample app:
The sample app works and allows users to create a user account.
Users can select a diet they would like to follow.
When navigating to the suggested meals page, there is no data or meals to display because the database is empty.

### Expected Behavior

Request:
Include sample database data and assets in the provided sample apps.
Provide data editors to help upload any missing database information.
This would greatly enhance the user experience by allowing users to fully explore and understand the capabilities of the sample apps.

Impact:
Including sample data and assets will enable users to see the apps in action with real data.
Help users better understand how to implement similar features in their own projects.
Reduce the time and effort required to manually input data just to test the app features.
Thank you for considering this request. The inclusion of sample data and assets will make FlutterFlow's sample apps more user-friendly and practical for new and existing users.

### Steps to Reproduce

1. Create a new project in FlutterFlow using one of the sample apps templates
2. Connect App to Firebase
3. Test app
4. Look sad because there is no sample data and for more complex apps data dependencies are not well defined so order of creation of data can be confusing :-(

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9aliAUJVwhaK00rdx+EBAjfYz4BIkiZ+PCVFhtUu6zaHNMJWej/XIKpejsuN+WLfA6aQesG91myatIQxPPbHuuSrXRC83hQWh6J+9YfGKx1pmrviRDBPhaWUYl2kOmAtiucz2Cf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-06-11 at 4 10 14 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/10622041/36d17ff9-113a-4645-a937-b2e6045e5681)

### Environment

```markdown
- FlutterFlow version: 
- Platform:All
- Browser name and version:125.0.6422.142 (Official Build) (x86_64)
- Operating system and version affected: All

(its a missing data issue)
```

### Additional Information

It makes it difficult to properly evaluate features and progress through tutorials.  May be related to the firebase connection issues the eng team is currently working on.

**Comment by msusviela** [comment]
Hey @qbuchanan, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!

**Comment by qbuchanan** [comment]
Thank you :-)

**Comment by leighajarett** [comment]
Great suggestion! We will try and work on this 🙂

**Comment by qbuchanan** [comment]
Awesome, thank you so much!
