### ISSUE TITLE
Colors wrong

### ISSUE THREAD

**Issue by ilimpapps** [FlutterFlow/flutterflow-issues#3101]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i try to edit color from Colors page with dark mode switched on, when i click on light mode color it shows dark mode color.

[https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/ea5e7abb-60e5-4cd9-9d3c-7bd70fe8f8d2](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/ea5e7abb-60e5-4cd9-9d3c-7bd70fe8f8d2)

### Expected Behavior

colors are the same as in colors page

### Steps to Reproduce

Create project
Create custom colors
Switch on Dark mode theme
Click edit color in Light mode for these custom color

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksrq2ItOsctZ+KriLfpaij0UGUMdXOczitVEew4bCIj4E5oMdfT4aklpUuazaH1UHVCgjngCp83GkeOWNPIEGzKZG9g5z7V2TBPPbFmVR8WMCZa8ZncnJ8ZXf1SX5sKvpSNTHNFuSU46w16HNd+sfz6Cf9qOYwx5e6fDbOY=

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/7ea1f18c-31bf-456b-b1a1-40339451600c](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/7ea1f18c-31bf-456b-b1a1-40339451600c)

### Environment

```markdown
FlutterFlow v4.1.54+ released June 12, 2024
Flutter version is 3.19.1
Windows desktop version
```

### Additional Information

---

**Comment by rzambroni** [comment]
Hi @ilimpapps, thanks for the report and for the video with the demonstration. I'm not being able to replicate this on any platform with the steps provided (web, MacOs, Windows). Can you replicate this consistently? or just happened once randomly?

Thanks!
