### ISSUE TITLE
Flutterflow UI breaks when setting state variable by creating data type

### ISSUE THREAD

**Issue by r-miljons** [FlutterFlow/flutterflow-issues#3103]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Setting a data type state variable and choosing to create it, then selecting fields that are other data types the UI breaks with a grey block. 

<img width="501" alt="flutterflow_8elH5VtbjA" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102419692/eb330f63-dd0c-415a-9d27-3bf7d82eb636">

### Expected Behavior

Should be able to set that field to the desired variable

### Steps to Reproduce

I have a state variable set to a data type, I want to set it to a value by choosing create that data type, then I select the fields that I want to set for that data type, and when I choose a more complex data type, like a list of other data types, UI breaks, strings and simpler data types seem to work fine

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lvLl8c9goelG+KX6ccFvmiMUKUc7bY03kutTcxM8J5DaPOxzP/TBaldWUs+0TH9If1qghnIz08nemvDDMcE6GzWbG598/6huFhbyQT+XbJCROqmNOG5/DfJVCh2i1sCrohJCJupvLHA/wzn3Ady8fHTAGZzRPWsjMfj/NZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="501" alt="flutterflow_8elH5VtbjA" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102419692/478c0c0c-bf29-48e1-b44d-93fa01f3c76c">

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: PC
- Browser name and version:
- Operating system and version affected: Windows 11
```

### Additional Information

This is causing delays in pushing new features to our app, please fix asap thank you

**Comment by paulperez-dev** [comment]
Hi @r-miljons! I was unable to reproduce this issue. Can you please try to recreate the error in the latest version of the app? Also, your project is very complex, is it possible to reproduce the bug in a blank project?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
