### ISSUE TITLE
The new Debug Panel is crashing Safari tab

### ISSUE THREAD

**Issue by RickAtSavveLabs** [FlutterFlow/flutterflow-issues#3106]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I test my app and it is started with the panel displayed, after 30 sec or so, the Safari tab is closed with a message about it taking up too many resources. It automatically starts back up, but repeats. I have let this happen 3 times in a row before stopping.

While the app is starting up, I cannot select the "Close Debug Panel" button because nothing is yet selectable on the screen. I was able to eventually manually restart it and close the panel so that the app would run in test mode. But things are now slower.

### Expected Behavior

Debug Panel should run along side your app in test mode with little effect on the apps performance.

### Steps to Reproduce

1. Set Safari to be your default browser
2. Start test run from MacOS version of FlutterFlow
3. Your app will start with the Debug Panel open
4. Soon the tab will close and start back up again.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfLq0812pbxH1rr+bMB7/ToRHFw1bbgescp/bxIgGIDzPOw+ZPXsXE5oXf2lS2xmJkSmmTkepM7LkfDiUPFeFzubGd1ZwbgNZTuVYDqie5OBBbqgSkR8BfxbFUfD5rS32xJvNuNodEY/2UOAHdiXXi/qQpy2IlFISq/LZO4=

### Visual documentation

![Screenshot of Safari at Jun 12, 2024 at 1_51_07 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/602e7389-4a60-4f5e-82c8-ed85357a088f)

### Environment

```markdown
- FlutterFlow version: 4.1.59
- Platform:Mac version of FlutterFlow
- Browser name and version:Safari v 17.5
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by rzambroni** [comment]
Hey @RickAtSavveLabs, thanks for the reports, i've been doing some tests and i wasn't able to replicate the issue you are describing. A few questions:

* Does it happen after a certain amount of time or as soon as Safari opens?
* Is it happening with that specific project or even with a blank project?
* Works as expected with Chrome or any other browser?

Thanks!

**Comment by RickAtSavveLabs** [comment]
Hi @rzambroni , I just went through again and realized that it does not happen on the login screen (since I was already logged in). Once you are logged in and on the home page of the app, that's when the issue happens. Sorry for the late realization.

**Comment by rzambroni** [comment]
I don't have the necessary permissions to run/test your project, only preview. Does this happen only in that project or any project you open in safari? I'm suspecting this might be related to something specific in your project but we need to find our what it is so we can replicate in a blank project.

**Comment by RickAtSavveLabs** [comment]
Hi @rzambroni,
I just tried running another project in Safari, and that one runs fine. So it is specific to the first project. Not sure if a useful insight... when the home page is loading, it is doing a Firestore query and populating a list with items that contain both text and images from links (in my Firebase db). Note that the app that does work fine, also shows a list of items. The only real difference is that the image links are to Google Place. 
Is there anything else I can do to help give you the access you need to understand this further.
Thanks! Rick

**Comment by rzambroni** [comment]
Thanks for the context Rick. We will try to replicate and see if any of the mentioned integrations can be causing a crash.

**Comment by rzambroni** [comment]
Hey Rick, we were unable to replicate the issue.. it might be something specific to your project causing memory problems to safari, but that is just a wild guess. I'm closing this issue as it is not replicable and looks project specific. If you end up finding out what more about how to replicate feel free to file another issue.

Thanks.

**Comment by RickAtSavveLabs** [comment]
Thanks for the effort on this @rzambroni. I am hopeful that in the final release of this, there will be the option to turn it off entirely and not use any resources when the debug window is not show. Even when not showing the debug window, test mode has become unusable for me. Thanks again.
