### ISSUE TITLE
Conflict between Tooltip and MouseRegion causes crash and "fatal error" with red screen

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3109]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am building a sidebar (navigation drawer menu) and for each menu option I am adding a hover effect with the MouseRegion widget to define an area of the element that represents the button (consisting of an icon container and menu label). When the user hovers over this area, I want to highlight the button's background color. However, when I added a Tooltip widget (positioned as either a parent or child of the MouseRegion widget), it caused an error on the debug page. This happened when I hovered over the test page, causing the application to crash and then display a red screen with an error message.

### Expected Behavior

The Tooltip and MouseRegion widgets should work together without causing errors in the application.

### Steps to Reproduce

1. Create a new page.
2. Add a Container widget with an icon and a menu label text.
3. Add a MouseRegion widget as the parent of the Container to create a hover effect on this element.
4. Inside the MouseRegion, add a Tooltip widget to also display an instructional message about this element that acts as a button.
5. Run the application in debug mode.
6. When hovering over the element, observe that other elements with hover effects freeze and the screen turns red with an error message on the debug page.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no

### Visual documentation

Attached is a video of the issue.
![fatal error print](https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/05b94ab0-2c7f-4012-bd72-56ef76e4ca82)

https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/1ba7b07f-7e70-4e21-84f7-a3db3c77c46d

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform: Windows desktop
Browser name and version: Chrome last 
Operating system and version: windows
```

**Comment by SauloSA** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/63a7bf11-3b56-4e40-a11a-3590bf67fa4f)

I managed to resolve the issue after changing the Padding from Expanded to Default. Interestingly, this configuration only impacted when the Tooltip was added; it wasn't a problem before. Now that I've made this change, it is working fine.

**Comment by SauloSA** [comment]
Still in the context of the tooltip, I would like you to check if the Tooltip requires specific dimensions to calculate the position it will occupy on the screen. In the case of the sidebar, this is a problem.

**Comment by SauloSA** [comment]
Imagine a container with an icon widget and a text widget together forming a button for a sidenavbar. Neither the text nor the container can have the padding set to expanded, as this results in a red screen error. This is problematic because, in my case, it is common to use expand to fill all available space. I believe this issue occurs because the Tooltip needs to know the dimensions of the element beforehand to position itself correctly on the screen.

**Comment by msusviela** [comment]
Hi @SauloSA. <br><br>Thanks for filling in! I could reproduce the issue from a blank project and sent it to the ENG team. They will consider this issue for future work around improving layouts and similar issues in FlutterFlow

**Comment by SauloSA** [comment]
Nice! Thanks
