### ISSUE TITLE
Private API always have minimum instance on Google Cloud

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#3117]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying private API, minimum instance of 1 is set. Don't believe this is necessary and has cost implication

### Expected Behavior

It should have minimum instance of 0 per FF Cloud Function deployment

### Steps to Reproduce

1. Create API call
2. Deploy as Private APIs
3. Go to Google Console > select FFPrivateAPICall and view Detail. A minimum instance of 1 is set.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ez/Llw4x2pbwA7qqNbMJagSQUH1w6UOYvku0bFQwbCIDwE4oteOjxP2FoUtfiTAk7L1mkoD4dp9LShuzEA+UqYCqBbJ84+LtyTTuWUj+6V8mWDJDpfkZSL5tJJVPC0Z2zsQhRCPt2WGRk2lOMOPKiTgPdHu/uIVYwRPH/OoX4nVGpQ0SLb3kNh1JWeC

### Visual documentation

<img width="498" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/151034963/70c0b6d3-2ce1-4852-8240-3b415218366f">

### Environment

```markdown
- FlutterFlow version: 4.1.59
- Platform: Desktop Mac
- Browser name and version: Chrome 
- Operating system and version affected: MacOS
```

**Comment by rzambroni** [comment]
Hey @itsstevenliu, thanks for the feedback, i believe this report might be more suitable as an enhancement request, to be able to indicate some of the parameters associated with the cloud function you are deploying so it is configured appropriately depending on the user's need.

Will close this and replace it with an enhancement request on our internal backlog.

Thanks!

**Comment by greghesp** [comment]
How on earth is this a feature request?  Sorry, but this is a bug, plain and simple.
A public API has no minimum instance, but a private API has a minium instance.  Thats a bug.

A feature request would be to ask what minimum/maximum instance we want on deployment

**Comment by reghta** [comment]
Preferably these asks should not be transitioned to an internal backlog; we could subscribe ourselves here to show support for an ask and track implementation but can not with your internal backlog...
