### ISSUE TITLE
Copy to clipboard stop working on Flutterflow version 4.1.59

### ISSUE THREAD

**Issue by thesadic** [FlutterFlow/flutterflow-issues#3119]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I call the copy to clipboard action from a button, it does nothing. Until the previous version of flutterflow, it copied the text to the clipboard. After the update, it stopped working.

### Expected Behavior

Copy text to the clipboard

### Steps to Reproduce

1 create a page
2 add a button
3 associate the button to the action copy to clipboard and add a text
4 run the project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcnl5Yx2pbxY17X5bcFR/WA5JVA3a4Iz1+x7aDYqGJToPLJ/Yvf4RxJDQtzgTGlhHFX+hj80wc71iYTxO8ACFwyZfqZ+zatcVj3yWXq8R7atDs60OXN8L9lPJnKb052G2x1AOvtaSE4SwFyEJe7KFzfbJ5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67202472/a56e4212-4b37-435d-bb99-592279c24f42)

https://github.com/FlutterFlow/flutterflow-issues/assets/67202472/e1c34acf-1b5d-4a35-8b28-c7f53008f898

### Environment

```markdown
- FlutterFlow version: 4.1.59
- Platform: web
- Browser name and version: Chrome Version 125.0.6422.142 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma version 14.5
```

**Comment by rzambroni** [comment]
Hey @thesadic, i noticed that when testing the app on web is not working properly (the browser is blocking the execution of the copy action) but when testing on a device is working as expected. Is this the case for you as well? have you tried run mode or on a device?<br><br>According to [this ](https://github.com/FlutterFlow/flutterflow-issues/issues/1418)previous report the issue with test mode is not something the team could fix at the moment.

[Simulator Screen Recording - iPhone 15 Pro Max - 2024-06-13 at 11.47.35.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7c941331-6857-4147-8d15-09b69e02f18a/530d87b9-4bdd-4a49-87a3-0091d110fe9f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83Yzk0MTMzMS02ODU3LTQxNDctOGQxNS0wOWI2OWUwMmYxOGEvNTMwZDg3YjktNGJkZC00YTQ5LTg3YTMtMDA5MWQxMTBmZTlmIiwiaWF0IjoxNzE4MjkwMDgwLCJleHAiOjMzMjg4ODUwMDgwfQ.5iRly_zOu-9W9QaPzGJ20zFBcVWrXn1Z87NArpb2vw0)

**Comment by thesadic** [comment]
Hi @rzambroni thanks for your reply, after I enter the issue I test it on local device and it works as you show. I'm not sure why it worked on the web in the previous version, but in my case it's not necessary.

Thank you very much!
