### ISSUE TITLE
New issues with fluttflow Google Map widget

### ISSUE THREAD

**Issue by SoLexGrowth** [FlutterFlow/flutterflow-issues#3120]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the recent updates in flutterflow the Google map widget is now disturbing every of my project which is using Google app widget in flutterflow... Recently my project refuses to download which is two of my project which is using Google map widget in flutterflow so I deleted the Google man and it's started working when when I put it back the same error occurred again... 

### Expected Behavior

To work fine

### Steps to Reproduce

I don't understand it the thing is that the Google man is now have 🐞bugs check on it and see yourself

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekM/l25J2n7wC0bX2YccxqwMwJ0QlUIInj+0bWRMhNbLwO4kAes+lRxFLYteXf1ZbeGGWkmcC+aHWjc71FPI5B0mbGKZ9/r5XQTmXZD+7Vaa1DaqsVXFBGehVGkCx4auNpAlNJbZpdFpiwGGUGvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

I was asked to add project URL but I don't know how to do that so please create a blank project add Google map widget and you will see the error yourself

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

It's affecting me till now because my apo required Google map to work fine but because of the issue I can't use Google map again please try to check on this issue ASAP please🙏

**Comment by rzambroni** [comment]
Hey @SoLexGrowth, i'm not being able to replicate the issue you are describing, i created a blank app with google maps and it is working as expected, i was also able to download the code and test the app normally. 

Not entirely sure what might be the issue you are having but it might be specific to your project. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dace377b-d098-4d09-8cd8-8580a30d4d30/ab62c16e-8c99-4e0c-bdbf-b68dbf72b6ec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYWNlMzc3Yi1kMDk4LTRkMDktOGNkOC04NTgwYTMwZDRkMzAvYWI2MmMxNmUtOGM5OS00ZTBjLWJkYmYtYjY4ZGJmNzJiNmVjIiwiaWF0IjoxNzE4Mjg3NDYyLCJleHAiOjMzMjg4ODQ3NDYyfQ.-e0H96WYSFKh6qcwkVltbdglfikQetKYVptpLbZJDS8 " alt="image.png" width="402" height="851" />

**Comment by SoLexGrowth** [comment]
> Hey @SoLexGrowth, i'm not being able to replicate the issue you are describing, i created a blank app with google maps and it is working as expected, i was also able to download the code and test the app normally.
> 
> Not entirely sure what might be the issue you are having but it might be specific to your project.
> 
> <img alt="image.png" width="402" height="851" src="https://camo.githubusercontent.com/d934ca80ad820f8f5d123e43cef5a69bdb9fc4ae1f6157e8f4aed8de1e81b19e/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f64616365333737622d643039382d346430392d386364382d3835383061333064346433302f61623632633136652d386339392d346530632d626462662d6236386462663732623665633f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a53396b59574e6c4d7a63335969316b4d446b344c54526b4d446b744f474e6b4f4330344e54677759544d775a44526b4d7a4176595749324d6d4d784e6d55744f474d354f5330305a54426a4c574a6b596d5974596a59345a474a6d4e7a4a694e6d566a4969776961574630496a6f784e7a45344d6a67334e4459794c434a6c654841694f6a4d7a4d6a67344f4451334e44597966512e2d6530483936575953464b68367163776b566c746264676c66696b5165744b59567074704c625a4a44533820">

**Comment by SoLexGrowth** [comment]
@rzambroni try to download the apk app not the code

**Comment by rzambroni** [comment]
i was able to download the apk as well, keep in mind that if you are using the web-app the download might be blocked by the "popup block" functionality of your browser. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f4014814-1e71-46fd-bc54-f64e94c2dc49/d3c7cb58-8731-45af-9ba5-8183e7b4addb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNDAxNDgxNC0xZTcxLTQ2ZmQtYmM1NC1mNjRlOTRjMmRjNDkvZDNjN2NiNTgtODczMS00NWFmLTliYTUtODE4M2U3YjRhZGRiIiwiaWF0IjoxNzE4Mjg4MjU3LCJleHAiOjMzMjg4ODQ4MjU3fQ.gR_k3Qr7fuEVjuiKXIwjh5ZZKfQNyysZe8AXqE5NWak " alt="image.png" width="282" height="150" />

If you continue to experience an issue please let us know what's the exact error message or process to replicate this. 

Thanks.

**Comment by SoLexGrowth** [comment]
@rzambroni this is the error am receiving and I have added the map again and the same issue occurred

**Comment by rzambroni** [comment]
are you missing a screenshot?
