### ISSUE TITLE
Faulty inference of action parameter types of custom widgets (and actions) based on the given code

### ISSUE THREAD

**Issue by antondr02** [FlutterFlow/flutterflow-issues#3121]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a custom widget that takes an action _callback_ as a parameter which itself has an action parameter _ref_ of type (Firestore) DocumentReference the document type (collection that _ref_ belongs to) of the reference is not correctly inferred even when using the boilerplate code provided. This inevitably results in an 'Unset'-status of the type leading to issues further down the road (fields cannot be set in a backend call). I think a short video explains the problem more clearly:

https://github.com/FlutterFlow/flutterflow-issues/assets/114415405/403a76f0-b3a6-4045-973a-ff9bc21ed736

The error message "Parameters in the settings don't match parameters in the code editor. If you confirm, we will replace parameters in the settings with parameters in the code editor. Are you sure you want to proceed?" appears even though the parameters do match. One has to click 'Yes' in order for the widget to be saved. As far as I know, Dart does not support Firestore collection type annotation so in the code there is no way of stating explicitly that _ref_ corresponds to a certain collection. Therefore, the error message should not appear.

Note: The same issue exists with Custom Actions

### Expected Behavior

I expect no error message to show up when trying to save the changes to the custom widget. Moreover, the collection type that I specified should remain unchanged instead of being changed to 'Unset'.

### Steps to Reproduce

1. Create a new blank project
2. Use the default settings (Setup Firebase checked)
3. Let FlutterFlow setup Firebase for you, create two blank pages for entry and login (Authentication and User Collection enabled)
![Screenshot 2024-06-13 144925](https://github.com/FlutterFlow/flutterflow-issues/assets/114415405/34a85629-acf5-4c87-99e9-7d24f2250a73)
4. Follow the default steps to integrate Firebase https://docs.flutterflow.io/data-and-backend/firebase/firebase-setup
5. Finish the setup by following the wizard
6. Navigate to Custom Code
7. Follow the exact steps of the video provided in the section **Current Behavior** (Important: Select _users_ instead of _todos_, this collection should exist when the project was correctly set up)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Olc/qx89OxL1E7ar2KcJV9SU5JkB+U6xMm8JhTQ8gIbXNG7UIec/4VEptXbC+TVc3ImCkmXIy/tnHktzIN/UEJU6bfrZhz6tyVDnzXkeWb8WXO6medEBDEtpKCkCC0KbUrAkkJtB2LXAF62aYH+m9c3fsJZSzIW0RRv+iBKPUs3fuQ0SLb3kNh1JWeC/v

### Visual documentation

Error message in question
![Screenshot 2024-06-13 151130](https://github.com/FlutterFlow/flutterflow-issues/assets/114415405/5d9a2f26-00b4-448c-9331-62ebb106bd42)

Additional images and videos have already been provided in the above sections.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.59+ released June 12, 2024
- Platform: Web and Windows Desktop
- Browser name and version: Version 125.0.6422.142
- Operating system and version affected: Windows 11 Pro 23H2, OS build: 22631.3593
```

### Additional Information

Due to this issue I am unable to complete the integration of a custom calendar into our application, a beta feature we planned to release this week. It is frustrating that this relatively small bug prevents us from publishing.

**Comment by paulperez-dev** [comment]
Hi @antondr02! I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by antondr02** [comment]
When can I expect this bug to be fixed? I do not intend to be overbearing but this does not seem like the most difficult task. I am paying a fair bit of money each month so that my team can work with Flutterflow. I do not think that minor bugs like these should take that long to be corrected.

**Comment by paulperez-dev** [comment]
Hi @antondr02! I sent this issue to the ENG team and it is in the backlog. I don't know the ETA yet.

**Comment by paulperez-dev** [comment]
Hi @antondr02! Just want to let you know the fix is making its way to **QA**!
