### ISSUE TITLE
Project in read only mode for all developers except the owner, even with read only mode disabled

### ISSUE THREAD

**Issue by heitorcfelix** [FlutterFlow/flutterflow-issues#3122]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the last update, read-only mode was enabled for all project developers expect the owner. Before the update everyone had permission. We have already activated and deactivated the read-only option but there has been no change. Also, we have another collaborative project with the same developers that has not been changed and continues as normal

### Expected Behavior

All permissions working properly for all developers. And all developer without read-only access will be able to test, run, create version and publish in the main branch.

### Steps to Reproduce

1. Access our specific project.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzPHl3It1n7wA+KrUbexF9GIWI0MdXOczitVEew4bCIj4O7MUZ8mlQBZtXdCzaH1AM1WJu3EJ//zGvYaSV8ECHzidbL5H+LVicxPPbFyubpPRDqmCX3xCL+xXN3KOyMK33BZvAMVudHws7ziDf+nKEj6Cf9qOYwx5e6fDbOY=

### Visual documentation

![Captura de Tela 2024-06-13 às 12 11 09](https://github.com/FlutterFlow/flutterflow-issues/assets/19861216/c9eb56eb-2b46-4822-abdd-6385e5ae0257)

![Captura de Tela 2024-06-13 às 12 08 52](https://github.com/FlutterFlow/flutterflow-issues/assets/19861216/8680392c-0776-4887-bb21-c7a7766b822a)

### Environment

```markdown
- FlutterFlow version: v4.1.59
- Platform: All
- Browser name and version: Chrome 125.0.6422.142
- Operating system and version affected: macOS Sonoma 14.5 (23F79)
```

**Comment by rzambroni** [comment]
Hey @heitorcfelix, so sorry you are having this issue. I was taking a look at your project and it seems that all collaborators were removed. Are you still experiencing this issue? 

Seems an issue very specific to your project and it's permissions, have you tried reaching out to our support team?

**Comment by heitorcfelix** [comment]
@rzambroni The issue was resolved when I removed people's individual email from the project and turned project sharing off and on for my organization.

In fact it could have been resolved with support but when I clicked on the chatbot it suggested I come to Issues. Is there any other more direct way to contact support to resolve future problems? In any case, you can close or delete the issue.
