### ISSUE TITLE
Stripe Cloud Function Is Not Deploying

### ISSUE THREAD

**Issue by MajorHodl** [FlutterFlow/flutterflow-issues#3126]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have followed all of the support teams instructions as well as the instructions in the docs. The cloud function deployment constantly fails

### Expected Behavior

I expect the cloud function to deploy...

I don't know what else you want me to say here...

### Steps to Reproduce

Click the deploy button...

I don't know what else you want me to say here...

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Error: Unknown error. Please contact support@flutterflow.io.

### Visual documentation

![Screenshot 2024-06-11 000923](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/19482c71-e1b6-42e7-9321-0a125f6f6106)
![Screenshot 2024-06-10 232611](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/04b616a0-1c72-4417-b6be-d973c9b0eb91)
![Screenshot 2024-06-10 232510](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/9247e26e-7274-4df3-ae9f-ce9f41e951e6)
![Screenshot 2024-06-10 232412](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/d1baf1d8-351a-4e5d-aae9-3671a0d412d7)
![Screenshot 2024-06-10 232308](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/2179776f-777d-4935-b1a2-9409dd6ae629)
![Screenshot 2024-06-10 230629](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/e708afcb-19ac-4d81-8602-05581a94f6f3)
![Screenshot 2024-06-10 230547](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/8a3c962c-14e2-4ebd-bb9b-abd12b2bcaf0)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.54+ released June 4, 2024
Flutter version is 3.19.1
- Platform: Web + Windows
- Browser name and version: Google Chrome Version 125.0.6422.142 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro 10.0.22631
```

### Additional Information

I am experiencing an intolerable lack of customer service from the support team. 

I have another ticket that SHOULD be open that has gone unresolved for over TWO MONTHS.

Now I am being told that I must maintain this error in order for support to investigate.

So now I cannot work on my app because I am unable to test changes while I maintain an error.

PLEASE HELP!!!

**Comment by rzambroni** [comment]
Hey @MajorHodl, i tested the integration with stripe in a blank project and it seems to be working as expected. I'm assuming it might be an issue with your specific configuration that is blocking the deployment of the cloud function. Can you provide us with the bug-report-code so we can take a look and see if we can figure it out? here is how: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)

**Comment by MajorHodl** [comment]
@rzambroni there is no bug code for this... what I provided is what FF gives me, it is simply an error reading when you hover over the information icon next to the "Not Deployed" verbiage that appears after you try to deploy the function in the settings panel.
![Screenshot 2024-06-14 143350](https://github.com/FlutterFlow/flutterflow-issues/assets/115755916/8ea3c412-b41e-44e2-8996-66eba2eaf83c)

**Comment by rzambroni** [comment]
you can provide a bug-report-code anyway so i can get temporary access to your project and take a look.

**Comment by MajorHodl** [comment]
You can right click a widget in the widget tree as the Docs you sent suggest... you cant right click a setting panel item... so there is no way to get a bug-report-code.

**Comment by rzambroni** [comment]
right-click on any widget please, it doesn't has to be related to the stripe integration, it can be the scaffold

**Comment by MajorHodl** [comment]
ITEShs7qy89gruFI+qrhYPpQhR0gHDN8Ua8/lcFEEA0gfLKoGbYUScnQXxFVXtORdHxYC1SapGEBpN2KjuGSO8IGPh6bc4Bz+KhcUgKVZEK6RK2YPs2eZHR8L/xNGXHG3J2ruhBSWe92eClpig/GSw==

I am working on a potential issue on the Firestore side. Please leave the ticket open, let me see if I can fix things on my end of if the issue persists. I will get back to this ticket on Monday or Tuesday.

**Comment by andreasvonfeld** [comment]
Did you manage to resolve the problem because I have the same thing?

**Comment by HKTG** [comment]
same.. :(

**Comment by HKTG** [comment]
@MajorHodl if you found a solution, please provide it! 🙏
