### ISSUE TITLE
Error on try add recursive component

### ISSUE THREAD

**Issue by MendesCorporation** [FlutterFlow/flutterflow-issues#3127]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a component and trying to place the same component inside, the error returns cannot have recursive components structure

### Expected Behavior

Being able to create a recursive component

### Steps to Reproduce

1. Create a component
2. Add the same component inner

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8/q24lPm+FY1aX1bflFlSo4NjM9TLJEpu0bWUkbGO/4OqQIfc/7fkhtOdCzaHxXPlqluDkdwfDKj87lMcddBz6tQa06/6lQTBPPbDmubq7XPaqsVnxAM+NVGW7E06e7kBQmLtZecloO7E+EJOi+RT6Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137794353/f864f9e7-3629-41e1-bf2f-68197b7a29ac)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137794353/e9ec2d22-1b03-4920-8f0a-287b6188422b)

### Environment

```markdown
- FlutterFlow version: 4.1.59+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windowns
```

### Additional Information

The new recursion feature was released but it doesn't work, see the comments on the YouTube video and I tried to create it according to the documentation without success

https://docs.flutterflow.io/widgets-and-components/custom-components

**Comment by leighajarett** [comment]
Oh no! So sorry about this - fixing ASAP

**Comment by leighajarett** [comment]
Okay this resolved now! Once again so sorry, it might take a few more minutes on desktop. Thank you so much for filing
