### ISSUE TITLE
Duplicate Backend Query | DataTable | TabBar

### ISSUE THREAD

**Issue by nikolasbp** [FlutterFlow/flutterflow-issues#3129]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a Tab Bar, and each tab contains a table. I created each table in tabs using [this method](https://www.youtube.com/watch?v=uso6uUnUqjM) with Containers and variables. However, I got a warning about duplicating the backend query. 

Note that each tab on the tab bar contains a table that imports data from the same Firestore collection (query collection). Each table has a different sorting method according to a different field in the collection.

Description:

**Firestore collection**
Fields:
club | number of games played | number of wins | number of goals over 1.5 | number of goals over 2.5 | number of goals over 3.5

**Table 1**
club | number of games played | number of wins - sorting based on the _number of wins_ field (decreasing)

**Table 2**
club | number of games played | number of goals over 2.5 - sorting based on field _number of goals over 2.5_ (decreasing)

### Expected Behavior

Creation of a single query collection for all tables in tab bars with a sorting option for each table. Avoiding duplicate backend queries.

### Steps to Reproduce

I used [this method](https://www.youtube.com/watch?v=uso6uUnUqjM) for each table in each tab bar.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gksmAsM9grsMA7aXqY+9ajjk7Q082RIc0stluZxEoIpznBu0QefSlS1tVXse8aVNcClSb8XEK///Hv+DPOsAVOU6Bf6pezc12dTz0e2inMJ+YOpaKYHNSI+lWCB2w36S3pxJAKtBsc1lm7Duqeuu/cz/DFOu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot from 2024-06-13 22-41-11](https://github.com/FlutterFlow/flutterflow-issues/assets/38947987/ce130a14-2f48-4914-89e7-af802fe7c116)

### Environment

```markdown
FlutterFlow version: v4.1.59+ (released June 12, 2024)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Version 125.0.6422.141 (Official Build) (64-bit)
Operating system and version (desktop): Ubuntu 22.04.4 LTS
```

**Comment by paulperez-dev** [comment]
Hi @nikolasbp! I'm unsure if this is a bug (querying the same collection and only changing the sorting). I will ask the ENG team about this.

**Comment by nikolasbp** [comment]
> Hi @nikolasbp! I'm unsure if this is a bug (querying the same collection and only changing the sorting). I will ask the ENG team about this.

Hi Paul, thanks for the reply and information. Considering that I will have 7 pages, each containing a tab bar with 7 tabs, and each tab has a table, I will have 49 duplicates. So, I am wondering if this will negatively affect my application in any segment. Will the application slow down, will the FireBase database be overloaded (too many reads), and similar?

**Comment by paulperez-dev** [comment]
@nikolasbp it could happen. Consider querying using one sorting option and do the second sorting locally. That should be faster and solve the warning.

**Comment by nikolasbp** [comment]
Thanks for the advice, but I posted this problem here because I don't know
how to do that process, so I'd be grateful if you could explain it to me
step by step.

**Comment by paulperez-dev** [comment]
Hi @nikolasbp! This tracker is only used for reproducible bugs, so I am closing this issue. You can ask [the community](https://community.flutterflow.io/ask-the-community) for help or reach out to [support@flutterflow.io](mailto:support@flutterflow.io). 

Thanks so much!
