### ISSUE TITLE
Foreign keyboard switches to English in textfield with Keyboard Type: Email Address

### ISSUE THREAD

**Issue by ametaplus** [FlutterFlow/flutterflow-issues#3131]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a textfield with the "Keyboard Type: Email Address", e. g. a usually German keyboard in the app switches to English when that textfield is active. Moving on to the next textfield it switches back to German.
This is confusing to users, since e. g. with the German keyboard, "z" and "y" are switched.

### Expected Behavior

The language of the keyboard should stay the same, even when the keyboard-type is "Email address".

### Steps to Reproduce

1. Create a new page
2. Add 2 textfield
3. Set one textfield to "Keyboard type: Email address"
4. Test the app on a phone which is set to e. g. German

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx892m+Fc1rrpbcJaqCQUC1B/TL03t9VxSUgrIrbyPJkUaeD7VFVvTcviTXw6KEWIhTsBwtbSvvLLJcEpNk+VRa5Y+LlyczmXXTi/aoSqEKWZdnx5GeBMIHKz0qujryN+GO9hLHg+1GaUOenLcDLaJqH7Zwh9f6PHaOI=

### Visual documentation

![Screenshot_20240614_091940](https://github.com/FlutterFlow/flutterflow-issues/assets/156191665/98d6a027-23b9-40ad-91c9-d0cb79542cdc)
![Screenshot_20240614_091944](https://github.com/FlutterFlow/flutterflow-issues/assets/156191665/cac5c615-3d5b-4bf7-8a94-28b80fa52f2e)

### Environment

```markdown
- FlutterFlow version: 4.1.59+
- Platform: Windows
- Browser name and version: -
- Operating system and version affected: Android (Samsung Galaxy S21)
```

**Comment by msusviela** [comment]
Hi @ametaplus.<br>It is an issue regarding the OS of the device. Sadly it's out of FlutterFlow scope
