### ISSUE TITLE
Why did the system stop redirecting to the widget with an error?

### ISSUE THREAD

**Issue by Rustem555** [FlutterFlow/flutterflow-issues#3132]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I click on an error in the list of errors and expect to be redirected to a widget with this error, But nothing happens

### Expected Behavior

I click on an error in the list of errors and expect to be redirected to a widget with this error

### Steps to Reproduce

1. Create a project. 2. Create a second screen with a required parameter. 3. Create navigation from a button on the first sheet to the second sheet without specifying a required parameter. 4. See the error in the list of errors. 5. Click on the error and make sure that there are no redirects to the widget with the error.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

srthtyjrykuyu

### Visual documentation

![123](https://github.com/FlutterFlow/flutterflow-issues/assets/128481643/974d1e17-2b24-425c-8c95-88cad5b29002)
![123](https://github.com/FlutterFlow/flutterflow-issues/assets/128481643/026ac162-1daa-4bb8-930b-f175d59a87b3)

### Environment

```markdown
- FlutterFlow version: v.3.1. 
- Platform: windows
- Browser name and version: Google Chrome Версия 125.0.6422.142 (Официальная сборка), (64 бит)
- Operating system and version affected:
```

### Additional Information

This makes it difficult to correct errors

**Comment by msusviela** [comment]
Hi @Rustem555

I wasn't able to reproduce your error from a blank project. Could you please provide us with the following information?:

1. On which platform were you able to reproduce the error?
2. Could you provide us with the bug report code for this? (To generate a bug report code, click right on the widget tree and select the Generate bug report code option)

**Comment by Rustem555** [comment]
1. On which platform were you able to reproduce the error? **"FlutterFlow"**, Windows, GoogleChrome.**
2. Could you provide us with the bug report code for this? (To generate a bug report code, click right on the widget tree and select the Generate bug report code option). 

I can't copy the error code. I can not. And this error is not located in the widget, but is distributed throughout the entire platform. Ibol, once again, the problem is that clicking by mistake does not redirect to the widget with the error.
I uploaded a video demonstrating the error to a file hosting service using the link: https://dropmefiles.com/ZGrP7

**Comment by msusviela** [comment]
Hi. Sorry for the late response. We've been investigating this issue further and we were not able to reproduce it, even from blank. Today a new version of FlutterFlow was published, Is this still a issue for you in the latest version?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
