### ISSUE TITLE
Regarding the issue where FireBase database information is not displayed on the front end

### ISSUE THREAD

**Issue by Miyata19830610** [FlutterFlow/flutterflow-issues#3135]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I run test/production mode on the web, the data table and post page are not displayed.

The part created with flutterflow is displayed, but it seems that only the database information stored in firebase is not displayed.

### Expected Behavior

When I entered a code in a custom function, the behavior became strange, and I deleted the custom code, but the symptoms like this occurred after that.

### Steps to Reproduce

1. Create a new page

2. Select state management

3.Select add field, select type as document, select "is list", set database

4. Select action, select "firebase query", select database, select "list of document"

5. Open a new action and load the database set in step 4 from "Update page state"

6. Added the "Data Table" widget, selected "Generate Document Children", and loaded the database set with "Update page state" in the value section.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okuflsIp2rs9J1s/IdfoxnSQUG1t+U78njspBVSkgGL7uPLMAP/fBVGdVUte6eHxIIGGJnm007s3Ihtr9FvkBCByJb4BJzahPEg7iRT6XaL6IPZDpPnR5M5hbJ0yazpuW3B1RIttoSEY77ziAG+qvHy/bJIDMO0VMLvmLBLn+oguHLBzCGX0Jg1ZSfCvr

### Visual documentation

<img width="1012" alt="スクリーンショット 2024-06-14 20 36 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/a7f9a1e8-d2c4-4c70-a5fe-5c78e58f96a6">
<img width="1012" alt="スクリーンショット 2024-06-14 20 35 42" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/ead66570-6b47-4a2a-88a3-6f8ba59dac57">
<img width="1012" alt="スクリーンショット 2024-06-14 20 35 49" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/ba064016-d8d3-4521-a9e9-d4bfb8547685">
<img width="1012" alt="スクリーンショット 2024-06-14 20 36 36" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/08882774-bbaa-46c2-8fec-bb9aa8ba9953">
<img width="1012" alt="スクリーンショット 2024-06-14 20 36 23" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/a195734e-5bde-428f-ac33-c29838e78889">
<img width="1012" alt="スクリーンショット 2024-06-14 20 36 15" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/12a7ab70-86da-4ef5-801e-6384300085f9">
<img width="1012" alt="スクリーンショット 2024-06-14 20 36 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/754dc02a-4adb-45da-b05c-b30be58cc99e">

<img width="1012" alt="スクリーンショット 2024-06-14 20 36 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/3c645dab-6ce8-4172-b5b9-cabdafd80b56">

### Environment

```markdown
- FlutterFlow version:4.1.59
- Platform:macos
- Browser name and version:arc 1.47.1
- Operating system and version affected: macos sonoma 14.5
```

**Comment by paulperez-dev** [comment]
Hi @Miyata19830610! If you open the browser console, do you see the following error?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d040682e-82ee-4794-b6b7-a84d36ead97f/c59c1f6d-76b2-4f5a-a733-59ef537c3866?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMDQwNjgyZS04MmVlLTQ3OTQtYjZiNy1hODRkMzZlYWQ5N2YvYzU5YzFmNmQtNzZiMi00ZjVhLWE3MzMtNTllZjUzN2MzODY2IiwiaWF0IjoxNzE4NTk0MTQzLCJleHAiOjMzMjg5MTU0MTQzfQ.blE3zSMcUw_0SyaMHrlRD-LL1YB_828mB0_rGaxD6zQ " alt="image.png" width="535" height="91" />

**Comment by Miyata19830610** [comment]
Thank you for answering.

I tried various things and completed it myself.
