### ISSUE TITLE
Firebase's Delete Security Rules Not Being Invoked

### ISSUE THREAD

**Issue by mark-fran** [FlutterFlow/flutterflow-issues#3136]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've set the **Delete** security rule to **No One**, but still the document can be deleted by the front end action. The Read and Write security rules appear to be working fine.

![Screen Shot 2024-06-14 at 9 31 07 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/108987006/c79d2156-8469-47e4-966d-d832aaf04000)

>     match /company/{document} {
>       allow create: if /databases/$(database)/documents/users/$(request.auth.uid) in request.resource.data.administrators;
>       allow read: if request.auth != null;
>       allow write: if /databases/$(database)/documents/users/$(request.auth.uid) in resource.data.all_users;
>       allow delete: if false;
>     }

### Expected Behavior

No users shall be able to delete the document.

### Steps to Reproduce

Add an action to delete document. When action is triggered, the document gets deleted even if the security rule is set to No One.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Align(   alignment: AlignmentDirectional(1, 0),   child: InkWell(     splashColor: Colors.transparent,     focusColor: Colors.transparent,     hoverColor: Colors.transparent,     highlightColor: Colors.transparent,     onTap: () async {       if (columnCompanyRecord.administrators.contains(currentUserReference)) {         var confirmDialogResponse = await showDialog<bool>(               context: context,               builder: (alertDialogContext) {                 return AlertDialog(                   title: Text('Confirm Deletion'),                   content:                       Text('This will permanently delete this organisation.'),                   actions: [                     TextButton(                       onPressed: () =>                           Navigator.pop(alertDialogContext, false),                       child: Text('Cancel'),                     ),                     TextButton(                       onPressed: () =>                           Navigator.pop(alertDialogContext, true),                       child: Text('Confirm'),                     ),                   ],                 );               },             ) ??             false;         context.pushNamed(           'CompanyList',           extra: <String, dynamic>{             kTransitionInfoKey: TransitionInfo(               hasTransition: true,               transitionType: PageTransitionType.fade,               duration: Duration(milliseconds: 0),             ),           },         );         // Remove from List         await currentUserReference!.update({           ...mapToFirestore(             {               'company_list':                   FieldValue.arrayRemove([columnCompanyRecord.reference]),               'company': FieldValue.delete(),             },           ),         });         await columnCompanyRecord.reference.delete();       } else {         await showDialog(           context: context,           builder: (alertDialogContext) {             return AlertDialog(               title: Text('Action Denied'),               content: Text(                   'You do not have access right to perform this action. Contact your administrator.'),               actions: [                 TextButton(                   onPressed: () => Navigator.pop(alertDialogContext),                   child: Text('Ok'),                 ),               ],             );           },         );       }     },     child: Text(       'Delete Organisation',       style: FlutterFlowTheme.of(context).bodySmall.override(             fontFamily: 'Rubik',             color: FlutterFlowTheme.of(context).error,             letterSpacing: 0,             fontWeight: FontWeight.w600,           ),     ),   ), )

### Visual documentation

![Screen Shot 2024-06-14 at 9 31 07 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/108987006/8264fedd-e50f-48b0-b72a-4f37b36d1c40)

### Environment

```markdown
- FlutterFlow version: 4.1.59
- Platform:Mac OS
- Browser name and version: Chrome
- Operating system and version affected: 12.5 Monterey
```

### Additional Information

This would be a security issue if the data is not protected from unauthorised deletion. My SaaS is an enterprise SaaS, so data security is vital.

**Comment by mark-fran** [comment]
Update on this please?

**Comment by paulperez-dev** [comment]
Hi @mark-fran! Sorry for the late response. Sometimes having Firestore in dev mode can interfere with these rules. Is your db in dev mode?

**Comment by mark-fran** [comment]
Hi Paul, no, it is not on a dev mode.

**Comment by paulperez-dev** [comment]
Hi @mark-fran! Does this issue persist in the latest release? If so, please share the [bug report code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code) of your project.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
