### ISSUE TITLE
Nav Bar is not showing up on tablet ??

### ISSUE THREAD

**Issue by Lostbuttrying** [FlutterFlow/flutterflow-issues#3137]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have deployed several versions of my app to google play console over the last month or so.  All of the versions have had the Nav Bar on all sizes of screens, and all device types.  Yesterday I published a new version on 6/13/24.  Cell phone version for Android has the Nav Bar as it should, however on a Samsung tablet, the Nav Bar is not there at all, on any page.  I'm guessing this is a bug since the latest FF update???   

### Expected Behavior

Nav Bar should be on all screens no matter the size of the screen or device type.  

### Steps to Reproduce

create a few pages
add a nav bar for those pages
deploy it to google play or however you check
cell will show Nav Bar, a tablet screen will NOT show it

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

justfixit

### Visual documentation

pretty easy to understand the issue without pics

### Environment

```markdown
- FlutterFlow version: v4.1.59+ released June 12, 2024 Flutter version is 3.19.1
- Platform: Android
- Browser name and version:  I don't know all this crap, just fix the bug!!!!
- Operating system and version affected: Android Tablet size screens
```

### Additional Information

I'm about to finish integrating RevenueCat into my app so I can deploy a version to test the billing.  I'm just a few days away from being able to publish this app in production, so I'd say this is of extremely HIGH PRIORITY!!!!!!!!!

**Comment by paulperez-dev** [comment]
Hi @Lostbuttrying! Can you please share the Bug Report Code so we can help you?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
