### ISSUE TITLE
FlutterFlow Beta v4.1.60+ custom codes errors

### ISSUE THREAD

**Issue by ndigacin** [FlutterFlow/flutterflow-issues#3139]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All the custom code in my project are showing erros after I upgraded to FlutterFlow Beta v4.1.60+

### Expected Behavior

All codes were totally fine and working as expected until I install the latest FF updates

### Steps to Reproduce

open the project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz8jf5c1NochE18/ML8Zv+CkwGUwbUOc7j9VEGAsjCePzEYlyP8mkahduWOqHS3NMGWajhXEJwdbQi9ntF8FfaA2eGKZq/5ZxUxDiIUiXb5CYCaq8RnclBcBhGkC1yKbZkCVTJvhpSUIl3Ez6fN6Qb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-06-14 at 2 09 39 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/116641569/208f5e6f-96ad-4554-b2f8-6e90053afe28)

### Environment

```markdown
- FlutterFlow version: Beta v4.1.60+
- Platform: Mac OS
- Browser name and version: Both Desktop App And Google Chrome
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
HI @ndigacin, thanks for the report, the team is already aware of the issue and is working to solve it as we speak. I'll keep this issue open so we can inform when fixed.

Thanks.

**Comment by ndigacin** [comment]
@rzambroni Do you currently have an ETA for the fix?

**Comment by ndigacin** [comment]
@rzambroni 
Is there any updates on this? I can't build, I can't test, I can't run. Por favor

**Comment by ndigacin** [comment]
@FlutterFlowEng @asmengistu @bulgariamitko @rzambroni 
Did you guys forget about this? I lost 3 days I cannot work due to this issue. When is it going to be solved?

**Comment by rzambroni** [comment]
Hey @ndigacin, the fix for this bug was already deployed and other users have reported that it was fixed on their end, one of our engineers was taking a look at your specific project and he believes it might be a specific error on your code. Here is the feedback he provided that might help you find the error: 

> it is because the user is putting a main.dart file in one of their custom widget. We can't detect that right now, but is already giving a hint: 
>
> <br>\`Unknown error compiling custom code. A common cause is a custom '
>
> 'widget or action whose name in the code does not match the name '
>
> 'provided in the editor.\`

Hope that helps.

**Comment by ndigacin** [comment]
@rzambroni I noticed it is resolved now. But it was not resolved when I posted my last comment. And the issue was definitely not project-specific because all the error alerts are gone without me making any changes in the code.

Thank you

**Comment by rzambroni** [comment]
Ok good, no clue what happened but at least it is resolved. Thanks.
