### ISSUE TITLE
Type mismatch error when overriding 'DocumentReference.snapshots' in custom code 'convertLatLng'

### ISSUE THREAD

**Issue by organicnz** [FlutterFlow/flutterflow-issues#3141]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open my project it shows an error with the custom function: 

'FakeDocumentReference.snapshots' ('Stream<DocumentSnapshot<Object?>> Function({bool includeMetadataChanges})') isn't a valid override of 'DocumentReference.snapshots' ('Stream<DocumentSnapshot<Object?>> Function({bool includeMetadataChanges, ListenSource source})').

### Expected Behavior

The custom function should be compiled with no issues, as it did before when I opened my project.

### Steps to Reproduce

1. Open a project 
2. Navigate to issues
3. Click on the red error 
4. Navigate to the Custom Function panel
5. Try to compile
6. Observe an error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wksmAsJRPxOVY15Dtbfow9ScQIjsgU+YZi8JHaCs8JL7oPOwifPfDN0pvTLyrTX9DeU6ZvHox/PfqvYXXE8IVCz+rbbpJ1c9yagnKezqWb7anOqWNfW1SEf5UGFTEyJ2RqhFSVex1W0Y77UzyOOjLb3bAJLLoPTE3IeaLLdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1728" alt="Screenshot 2024-06-14 at 17 38 03" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4765090/2ae3dd59-d11b-4363-80e6-c4c7f685594a">

<img width="1728" alt="Screenshot 2024-06-14 at 17 25 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4765090/4357b009-d3cf-437b-be0a-287d9eb357b9">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.60 released June 14, 2024
Flutter version is 3.22.2
- Platform: Beta for macOS  
- Browser name and version: Arc Version 1.44.2 (50412)
- Operating system and version affected: MacOS 14.5 (23F79)
```

### Additional Information

- Project ID: foodshare-copy-hgwb2r

**Comment by zeymermontes** [comment]
<img width="412" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/66459565/6a19df5c-4b87-4984-a079-1b109b245664">


Same thing happens to my project and I cant run tests.

**Comment by louisdavidSpicyMind** [comment]
I get the same error : 'FakeDocumentReference.snapshots' ('Stream<DocumentSnapshot<Object?>> Function({bool includeMetadataChanges})') isn't a valid override of 'DocumentReference.snapshots' ('Stream<DocumentSnapshot<Object?>> Function({bool includeMetadataChanges, ListenSource source})').

Anyone found a solution?? @agreaves @organicnz

**Comment by NabilRFG12** [comment]
i have the same error , this happens when making some changes or creating new dataTypes

**Comment by alveskevinn** [comment]
Me too...

**Comment by cg-sitiouno** [comment]
same here!!

**Comment by launchInsighter** [comment]
same here!!  It was working moments ago.  The error persisted even after I restore previous working version of my app.  This is frustrating.

**Comment by max-h-silverman** [comment]
Getting this as well...

**Comment by juandps** [comment]
Same here, this seems like a live error that we are all having at the same time.

1. I tried restoring previous sessions and it's not working.
2. I added a custom function and I thought that was the problem but nope, even if I delete the file the error persist

**Comment by max-h-silverman** [comment]
This seems to be only affecting the desktop app, btw. I'm not seeing it on the web app.

**Comment by NabilRFG12** [comment]
its fixed Now ! but just in browser ,

**Comment by AcnoSaga** [comment]
Still getting this in the desktop app.

**Comment by AcnoSaga** [comment]
Surprisingly, Local Run on iOS is also giving an error (this did not exist like right before I changed a few actions):

```
The current Dart SDK version is 3.3.0.

Because excursia depends on video_player_android >=2.4.15 which requires SDK version >=3.4.0 <4.0.0, version solving failed.

```

**Comment by cg-sitiouno** [comment]
I think they've fixed it now..

**Comment by EnviousDetailingMarketing** [comment]
I am also getting this error. In browser and desktop app. I have also reverted to a different project version and deleted the function that is giving me the error. 
Please help!

**Comment by boadude** [comment]
Same here! Only in Desktop.

**Comment by juandps** [comment]
It's fixed in browser had to flush cache memory.

**Comment by boadude** [comment]
> It's fixed in browser had to flush cache memory.

Yes, in browser works but not in the desktops apps.

**Comment by EnviousDetailingMarketing** [comment]
Flushing the cache memory in browser worked, so I...
- uninstalled the desktop app
- redownloaded it
- deleted the flutterflow app cache in ~/Library/Caches (Mac Sonoma 14.0)
- reopened the desktop app. 

It worked. Back to normal in the desktop app, too.

**Comment by launchInsighter** [comment]
This works.  Thanks.

**Comment by EnviousDetailingMarketing** [comment]
> This works. Thanks.

Glad to hear it!

**Comment by juandps** [comment]
What a great community if someone wants to connect I'm creating a discord server https://discord.gg/ag8FQfvG so  we can connect when we are facing this type of issues.

**Comment by ch-Isaac** [comment]
> Flushing the cache memory in browser worked, so I...
> 
> * uninstalled the desktop app
> * redownloaded it
> * deleted the flutterflow app cache in ~/Library/Caches (Mac Sonoma 14.0)
> * reopened the desktop app.
> 
> It worked. Back to normal in the desktop app, too.

Thanks for that, fixed the issue for me!

**Comment by BrunoMakeDrive** [comment]
Same problem, but my Flutterflow desktop doesn't work, and I can only try it on Flutterflow web, which also doesn't work.
