### ISSUE TITLE
Using Code expression for variable value assignment crashes Flutterflow App [Related to #3051]

### ISSUE THREAD

**Issue by akscienceltd** [FlutterFlow/flutterflow-issues#3143]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Opening Code expression option while trying to create/modify expression causes Flutterflow app to hang/crash.

### Expected Behavior

Create a widget/state variable. Try to update it value through the Code Expression feature.

### Steps to Reproduce

Try to set any variable value of any widget using the Code expression feature - causes the app to freeze. Please check this video attached for an example behaviour of the same.

https://github.com/FlutterFlow/flutterflow-issues/assets/170185307/cdd1b28c-c994-43f9-98b1-1c0094e340f0

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sivHq6otPvsdG1ZDuc8dB/To7JWYhap0sscpCbw4bIYj2P4lzY876PxJCTe2iS1ZYeUyMp14y06HUjuH9CvApITaZbJhb/6VIeA7MWTuVMsSTF7i0eHcnP/xjI0+MyKarsRZCFPVac3wO3WamP+e/SnfqNpOxDVQ8Sq/LZO4=

### Visual documentation

I'm trying to use code expressions for updating a state variable value.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/170185307/4b325862-5d35-4bba-a8f8-a0c71d0b7f67)

### Environment

```markdown
- FlutterFlow version: 4.1.60+
- Platform: Windows App
- Browser name and version: Google Chrome V125.0.6422.142 
- Operating system and version affected: Windows 11
```

### Additional Information

This issue is a continuation of [#3051](https://github.com/FlutterFlow/flutterflow-issues/issues/3051) I'm not able to create custom code expressions for trivial things - I'm currently creating dedicated functions to replicate the same as a workaround.  Please fix this at the earliest. Thanks!

**Comment by paulperez-dev** [comment]
Hi @akscienceltd! So sorry you are experiencing this issue. I was unable to replicate the issue reported on a new project or yours (web version). I tried it on Windows and Chrome. Did you change something else on your project other than what is shown in the video?

**Comment by akscienceltd** [comment]
Hi @paulperez-dev , None unfortunately. A point to note is that the web version of the flutterflow app works fine. It just occurs in the desktop version (for my core project as well as the new project).

**Comment by paulperez-dev** [comment]
Can you please verify if this is still happening in the latest version?<br>If so, can you please share another video showing all the steps (including the project creation)? Maybe the bug is only reproducible following specific steps.

**Comment by akscienceltd** [comment]
@paulperez-dev Yep, it's still happening. And here you go, a new recording for the same - 
https://www.loom.com/share/fa7c7541dc224dd28a5fd98025eeab5a?sid=dc33c3b3-fe88-4dd7-907b-de27784fb11f

P.S. It used to work well and unfortunately for me, I have built some modules based on this FF functionality which  are now at risk unless I refactor them.

**Comment by akscienceltd** [comment]
@paulperez-dev The issue still persists after this new update. Is there any plan to fix it?

**Comment by paulperez-dev** [comment]
Hi @akscienceltd! Thanks for the video, I can see the issue happens on a new project. I'm still not able to replicate this behavior. Can you please share your Windows version and screen resolution? Do you have a different PC where you can test that feature?

**Comment by akscienceltd** [comment]
@paulperez-dev It's Windows 11, and the screen resolution is 1920x1080. Thanks for the support.  This issue is isolated to the Windows app.

**Comment by paulperez-dev** [comment]
Hi @akscienceltd! Can you confirm which scale you have selected? Monitor size?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/84725973-9b2c-41db-b6ee-7c3a0dff629e/2e2d1077-96be-40f3-a7a2-0482c147e2b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NDcyNTk3My05YjJjLTQxZGItYjZlZS03YzNhMGRmZjYyOWUvMmUyZDEwNzctOTZiZS00MGYzLWE3YTItMDQ4MmMxNDdlMmI3IiwiaWF0IjoxNzIxMDg4ODM5LCJleHAiOjMzMjkxNjQ4ODM5fQ.YYfq0DTnNDfUPwhdMlKYQDRvX5VI4LV2RDbrqOuqI4E " alt="image.png" width="1040" height="344" />

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
