### ISSUE TITLE
Dropdown fields not validating

### ISSUE THREAD

**Issue by atc6955** [FlutterFlow/flutterflow-issues#3145]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have three dropdowns inside a form element. I have selected the checkbox to validate each dropdown and defined the action. However, the user is able to submit the form without selecting a dropdown option, and an empty string is written to firestore for my document update

### Expected Behavior

I expect the user to be shown the error message and to be forced to make a selection before form submission

### Steps to Reproduce

1. Create a dropdown within a form
2. Create a validation on the form and dropdown
3. Submit the form and you will see that the user can continue without making a selection 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kl8n625dgrt9c7c/fbflv9Sk7Jn47TL07p+xEGA8rCOOtPLJ/f8mlX1pBTeGkdENhHGCWgkwxpvTpuNjXEfYFAwqAbJxi1KgNaw3wZ3q8Rq3TPriNPnFDM+lUN3ai5La3mBBdHNZaWCVm7zmENdivQnLdN5+/Zwh9f6PHaOI=

### Visual documentation

![Screenshot from 2024-06-15 18-43-12](https://github.com/FlutterFlow/flutterflow-issues/assets/102269444/f1673a93-e07e-434a-b91d-62e2be4f9610)
![Screenshot from 2024-06-15 18-43-01](https://github.com/FlutterFlow/flutterflow-issues/assets/102269444/477f83d6-a265-4137-bb52-1fc4af1a50e7)
![Screenshot from 2024-06-15 18-42-41](https://github.com/FlutterFlow/flutterflow-issues/assets/102269444/9a1b81ea-fa06-4bf2-88a2-9bf0a8781cf3)

### Environment

```markdown
- FlutterFlow version: 4.1.60
- Platform: Linux / PWA
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by rzambroni** [comment]
Hey @alta-atc, I was trying to replicate the issue you are describing but so fat I was not able to do so. I also checked your project and I couldn't find anything that might be misconfigured. Are you experiencing this consistently and in with all of te dropdowns? If that's the case, would you mind checking If this also happen on a blank project? Thanks.
