### ISSUE TITLE
Action builder: Action name not updating and more

### ISSUE THREAD

**Issue by crich04** [FlutterFlow/flutterflow-issues#3146]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Navigating from "Update Component State" to another "Update Component State", the action name does not update.  I believe it's happenening for other actions too - specifically the Bottom Sheet duration doesn't update when switching from one to another.  The workaround is to click in the blank area and then, click on the action again - repaints the properties window.

### Expected Behavior

I would expect that the name changes :)

### Steps to Reproduce

Create a workflow with two "Update Component State" actions.  Name them different.  Navigate back and forth and look at the properties - no name change.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Okufl0ItPxdtZ18/2YMJajmAUJjM6aqxMitZ9ZwIdCJfNGu4MPsneVFRuZrznYHx2fWeKmmIK7Pfqi/PtDfVfH0ydUYhZzbhIEj3zXlO6bIy4PaWdfW1fGehjf1Sz1KSKkwlQXe9hWFIe3WC2O9y/FyrsK5zuPDINGfmbLdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Screenshot 2024-06-15 193343](https://github.com/FlutterFlow/flutterflow-issues/assets/38697301/5efaa804-5491-4d61-82e5-3e0571a4770f)

### Environment

```markdown
- FlutterFlow version: Current
- Platform:Windows
- Browser name and version: Doesn't matter
- Operating system and version affected: Windows
```

**Comment by Coopertron1** [comment]
Hi @crich04 I am glad I am not the only one having this issue.  I am unable to update App State Variable lists. I replicated this issue in a different project suggesting that it might be software wide. Fingers crossed they are already working on a fix... as this action is pretty fundamental to most apps.  

<img width="318" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/172756480/5a6a861b-35fc-487c-8893-6b7e40806fdb">

**Comment by msusviela** [comment]
Hi @crich04. I wasn't able to reproduce the issue with the steps you provided. If the issue persist, could you please sent me more specific steps to reproduce the issue?<br><br>@Coopertron1 tagging you in this as well, maybe you could provide us with some extra information so we can tackle this as soon as possible.

**Comment by crich04** [comment]
In an Action editor screen, place two Actions on the screen (You don't even have to define them).  They will be something like "Action 1" and "Action 2".  Select Action 1 and change the name to "My Action" and click the check mark to confirm.  Then, click on "Action 2" and look at the properties.  It will still say "My Action".  It won't change to "Action 2".  In other words, the title of the Action in the properties does not update on the screen until you click away from the actions or click the edit button.

**Comment by crich04** [comment]
This same behavior happens on the duration property for a "Show Bottom Sheet".  If you put two "Show Bottom Sheet" actions on in your workflow, change the duration for the first one to 10 seconds.  Then, click to the second one and the duration will be 10 seconds instead of the actual default value.

**Comment by msusviela** [comment]
Hi. Sorry for the late response. A new version of FlutterFlow was launched today and the issue is no replicable from this version. Let me know if you're still experiencing this.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
