### ISSUE TITLE
Recent update breaks both of my projects

### ISSUE THREAD

**Issue by davisiqueira1** [FlutterFlow/flutterflow-issues#3148]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Some values of my project are being treated like empty or null (even if i set these variables). Before the debug panel update everything was working fine. Now all the queries that use these values as reference are crashing my apps.

### Expected Behavior

The values should not be trated as empty or null (because they are NOT empty or null)

### Steps to Reproduce

1. Login
2. Try to create a form
3. The firebase query will fail (because the ref value is null or empty)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olcmAvJJNrsdE7a6JccBKjSQXKWJ7aI03kcpBazwbfe+uB4kqevfOTERoTcjmdwliPmK0r2oW0878ifPtUsYqZDSBY4hy/6VuejmXXlO5VYiUFJWgVHFtM/xXCXah0bSZoRJ7CMt1dVpm7FOEHNnIYHHcJOPYOm0wDq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/93483437/51c5b6ce-8c45-4ba8-9b66-023d3bfeeb38)

### Environment

```markdown
- FlutterFlow version: v4.1.60 (released June 16, 2024)
- Platform: Web
- Browser name and version: Chrome 126.0.6478.57
- Operating system and version affected: Windows 10 Pro 22H2
```

### Additional Information

I have to deliver these projects at the end of the month, but at this state, i cant even develop it, please help

**Comment by rzambroni** [comment]
Hey @davisiqueira1, are you still experiencing this issue on the latest version? there were a few fixes released regarding the debug panel, if that was the case for you it might be already fixed. 

If not, and given the nature of the issue i would advise reaching out to support for a more in-depth analysis of your project as it can't be replicated in others.

You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

Thanks.

**Comment by ready4sea** [comment]
I wonder if this is linked to https://github.com/FlutterFlow/flutterflow-issues/issues/3111
In any case it looks similar, and happened at the same time.

**Comment by rzambroni** [comment]
it could definitely could be, if that's the case i believe the team already worked on that but i don't have an ETA on the release of a fix for it.

**Comment by ready4sea** [comment]
Believe it or not, not before next week 🤯
No comment.
