### ISSUE TITLE
[Listview] Listview misses items on first load

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#3149]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a firestore collection with about 3000 documents. The documents are getting queried by a list view with infinite scrolle and sorting. When the query is loaded there are items missing and/or they are not correctly sorted. If I scroll to the end of the list I am just seeing e.g. 1200 documents (I am displaying the list index).
If I go to another page in the app and open the page with the query again, it shows more documents (It loads the on the second try)

### Expected Behavior

I am expecting to see all the documents at the correct place in the list.

### Steps to Reproduce

1. Create a firestore collection and documents with a number field to sort them
2. query this collection with a list view with infinite scroll
3. compare the items shown in the list view with what should actually show

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

failed to copy

### Visual documentation

Please let me know if you need something. I could show the list on different devices showing different results but I guess it is unnecessary

### Environment

```markdown
- FlutterFlow version: v4.1.60
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @Jensoulus! Sorry for the late response. Are you still facing this issue in the latest version? If so, please share the bug report code of your project!

**Comment by Jensoulus** [comment]
Hi @paulperez-dev, Has there been a change that could influence this?

**Comment by paulperez-dev** [comment]
I'm not part of the ENG team, I don't have access to verify the changes.

**Comment by paulperez-dev** [comment]
@Jensoulus were you able to get the bug report code?

**Comment by Jensoulus** [comment]
Hi @paulperez-dev,
do you mean the generated bug report code of the list view? 
I always have trouble using safari but I can get it with chrome if that's what you mean

**Comment by paulperez-dev** [comment]
Do you mean that on Chrome the app behaves as expected?<br><br>I mean [this bug report code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code).

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
