### ISSUE TITLE
Going through the built-in tutorial "Travel App" showed a visual error when running it, as if the resources are not available

### ISSUE THREAD

**Issue by snowboarder** [FlutterFlow/flutterflow-issues#3150]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running the Travel app after going through the Travel App tutorial there were odd loading issues.    I also think there should be a way to pause the videos/animations in the tutorial.   Some of the instructions are not consistent across versions in the help area for example bug reporting icon was moved, but maybe thats the variations between windows and browser based apps i am not sure.

### Expected Behavior

Loading as shown

### Steps to Reproduce

1. Travel App tutorial
2.  Run app in test mode
3. Doesn't load correctly

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9WhjwUJW01ba00sNobbxAjIoDoPJkUaeD4dkltZMugT1ZbKEWLrF4xpcnHktnfFfk6ISysRYRg1ZZiVgLwIWO/aoSoOrWeP2gmGdhgG3aF0cKvgR1NPrJfL1Fm71yuN/OiZzDdJr37Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1418909/20451d21-f062-4a3a-be1b-cc9a3b292ff7)

### Environment

```markdown
FF 4.1.60+ For windows
windows 11
Chrome Browser Version 126.0.6478.61 (Official Build) (64-bit)
```

### Additional Information

learn the system and setup process

**Comment by rzambroni** [comment]
Hey @snowboarder, thanks for the report, do you mind adding me as a collaborator to your tutorial project so I can run it and see the problem in depth? (rzambroni@somniosoftware.com)

**Comment by snowboarder** [comment]
@rzambroni  ok your email was added
