### ISSUE TITLE
Error in console when using Icon as a component-parameter in test-mode

### ISSUE THREAD

**Issue by ametaplus** [FlutterFlow/flutterflow-issues#3151]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using an icon as a component-parameter, in the console we get the error:
`Error debug serializing parameter: TypeError: Instance of 'FaIcon': type 'FaIcon' is not a subtype of type 'String?'`

### Expected Behavior

That it doesn't give out an error.

### Steps to Reproduce

1. Create a component with an icon-parameter
2. Add an icon and set it to the parameter
3. Insert the component on the page and set the parameter
4. Run in test-mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx892m+Fc1rrpbcJaqCQUC1B/TL03pu0bFEggGLbrBIYMacneQE1vOO6qYFZ5KEWKilkG087Qi9/hLOwqPSmAfNlRwqtqdwrKbEy/aoSqEKWZdnx5GeBMIHKz0qujryN+GO9hLHg+1GaUOenLcDLaJqH7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-06-17 140330](https://github.com/FlutterFlow/flutterflow-issues/assets/156191665/dfa75ca1-be6f-475a-a8f2-36b870144a67)

### Environment

```markdown
- FlutterFlow version: 4.1.60+
- Platform: Browser
- Browser name and version: Edge Version 126.0.2592.56 (Offizielles Build) (64-Bit)
- Operating system and version affected: Test-Mode
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
