### ISSUE TITLE
Issue with Dynamic Values in Gradient Angle (degrees) Field

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3155]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the Angle (degrees) field for gradients dynamically, it seems to only allow a maximum variation of 90 degrees. I attempted to create a button that would rotate the gradient by 360 degrees on hover, but it did not rotate at all. I could achieve some effect with 270 degrees, but the result only rotated 90 degrees as shown in the attached video.

### Expected Behavior

The gradient angle should dynamically rotate up to 360 degrees as configured, providing a full rotation effect on hover.

### Steps to Reproduce

Configure the gradient Angle (degrees) field to use dynamic values aiming for a full 360-degree rotation on hover.
Observe that the gradient rotation does not exceed 90 degrees and does not achieve the desired 360-degree effect.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/d9d0b967-c66b-4199-8e88-783dbe988cf1)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/ef78a8b6-6c0f-44fe-8252-e936e13d4870

### Environment

```markdown
FlutterFlow version: last
Platform: desktop windows
Browser name and version: Chrome 107.0.5304.110
```

**Comment by msusviela** [comment]
Hi @SauloSA. 

The rotations are working fine and generating the correct code for that.

Please, check that you're setting correctly the angle you desire. I just checked rotating 90 and 270 degrees. Please note that they'll have similar rotations, but they will have the colors on opposite sides.

If you want to rotate the gradient so the colors show in different order, maybe you should try with 180. Using 360 will rotate the gradient to the same place and no effects on the UI will be shown.
