### ISSUE TITLE
Tooltip Visibility Rules Affect All Child Elements

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3156]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When configuring visibility rules for a tooltip, the expected behavior is that only the tooltip element itself should be hidden or shown based on the conditions. However, currently, applying visibility rules to a tooltip also affects all child elements, hiding them as well. This issue is problematic when dealing with multiple states, such as in a sidenavbar (side navigation menu).

For example, in a sidenavbar, one state displays the menu with button labels fully visible, making tooltips unnecessary. In this state, the tooltip should be hidden. In the collapsed state, where only icons are shown, tooltips should be displayed on hover. However, due to the current behavior, setting visibility rules for the tooltip ends up hiding not only the tooltip but also the child elements, which disrupts the intended functionality.

### Expected Behavior

Visibility rules applied to a tooltip should only affect the tooltip element itself and not its child elements. This allows for flexible UI states where tooltips can be shown or hidden as needed without affecting other components.

### Steps to Reproduce

Configure the sidenavbar to have two states: expanded (showing button labels) and collapsed (showing only icons).
Set visibility rules for the tooltips to hide them in the expanded state and show them in the collapsed state.
Observe that applying visibility rules to the tooltip hides all child elements, not just the tooltip.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

Not applicable

### Environment

```markdown
-FlutterFlow version: last
Platform: desktop
Browser name and version: Chrome 107.0.5304.110
```

**Comment by paulperez-dev** [comment]
Hi @SauloSA! [Conditional Visibility](https://docs.flutterflow.io/advanced-functionality/conditional-visibility) is set at a Widget level and by extension to all its descendants. This is not a [tooltip](https://api.flutter.dev/flutter/material/Tooltip-class.html) property, so it is the expected behavior. 

You can achieve the desired behavior using a custom widget, which receives the bool value and returns the desired widget with or without the tooltip.

I'm closing this issue.
