### ISSUE TITLE
Unable to Overlay Elements on Container with Background Image or Gradient

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3158]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a container has a background image or gradient, it is not possible to overlay any other elements on top of this image. This includes adding a semi-transparent layer to darken the image or creating a hover effect over the image. This limitation prevents applying necessary filters or visual effects to the background image or gradient.

### Expected Behavior

It should be possible to overlay elements, such as semi-transparent layers or additional widgets, on top of a container that has a background image or gradient. This would allow for greater design flexibility, such as darkening an image or creating hover effects.

### Steps to Reproduce

Not applicable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

Not applicable

### Environment

```markdown
Not applicable
```

**Comment by SauloSA** [comment]
https://www.youtube.com/watch?v=TImvKD3BUKA

**Comment by msusviela** [comment]
Hi @SauloSA. 

Could you provide the steps to reproduce this? 

I could replicate the issue by stacking two containers, one giving it a transparent color and the other one a background image. I just wanted to make sure if that's the issue you're describing.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
