### ISSUE TITLE
Base64 string to Image Box Population error

### ISSUE THREAD

**Issue by hughCar389** [FlutterFlow/flutterflow-issues#3161]
I have connected the $.Pic to the custom image box but when I try to use my customer function called "decodeImage" to convert the list of strings into image Paths it fails. What settings should I have to properly populate the image boxes? 

 Bug report code:   
ITFfkM/l7ZBgoctH176JKcJVvDgWH18cTb4RltZ+RRQhfe/1P7N/fc7OS1VLYtfhT39qPWGKhXEypKHvi97pJvo6ISqVRb5G+ZRXQQLNTl2Vb4TWEbW8RnQnQOFWIXHF3KaGkRQmNtVYZVVh3F+hNvCdG3qCf9qOYwx5e6fDbOY=

**Comment by hughCar389** [comment]
`//Widet:
import '/backend/api_requests/api_calls.dart';
import '/flutter_flow/flutter_flow_icon_button.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import '/custom_code/actions/index.dart' as actions;
import '/flutter_flow/custom_functions.dart' as functions;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import 'meet_the_surgeons_model.dart';
export 'meet_the_surgeons_model.dart';

class MeetTheSurgeonsWidget extends StatefulWidget {
  const MeetTheSurgeonsWidget({super.key});

  @override
  State<MeetTheSurgeonsWidget> createState() => _MeetTheSurgeonsWidgetState();
}

class _MeetTheSurgeonsWidgetState extends State<MeetTheSurgeonsWidget> {
  late MeetTheSurgeonsModel _model;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => MeetTheSurgeonsModel());

    WidgetsBinding.instance.addPostFrameCallback((_) => setState(() {}));
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _model.unfocusNode.canRequestFocus
          ? FocusScope.of(context).requestFocus(_model.unfocusNode)
          : FocusScope.of(context).unfocus(),
      child: Scaffold(
        key: scaffoldKey,
        backgroundColor: FlutterFlowTheme.of(context).secondary,
        appBar: AppBar(
          backgroundColor: Color(0xFF003057),
          automaticallyImplyLeading: false,
          leading: FlutterFlowIconButton(
            borderColor: Colors.transparent,
            borderRadius: 30,
            borderWidth: 1,
            buttonSize: 60,
            icon: Icon(
              Icons.arrow_back_rounded,
              color: Colors.white,
              size: 30,
            ),
            onPressed: () async {
              context.pop();
            },
          ),
          title: Text(
            'Meet Our Surgeons',
            style: FlutterFlowTheme.of(context).headlineMedium.override(
                  fontFamily: 'Poppins',
                  color: Colors.white,
                  fontSize: 22,
                  letterSpacing: 0,
                ),
          ),
          actions: [],
          centerTitle: true,
          elevation: 2,
        ),
        body: InkWell(
          splashColor: Colors.transparent,
          focusColor: Colors.transparent,
          hoverColor: Colors.transparent,
          highlightColor: Colors.transparent,
          onTap: () async {
            await _model.columnController?.animateTo(
              _model.columnController!.position.maxScrollExtent,
              duration: Duration(milliseconds: 1),
              curve: Curves.ease,
            );
          },
          child: SingleChildScrollView(
            controller: _model.columnController,
            child: Column(
              mainAxisSize: MainAxisSize.max,
              children: [
                FutureBuilder<ApiCallResponse>(
                  future: PhysiciansCall.call(),
                  builder: (context, snapshot) {
                    // Customize what your widget looks like when it's loading.
                    if (!snapshot.hasData) {
                      return Center(
                        child: SizedBox(
                          width: 50,
                          height: 50,
                          child: CircularProgressIndicator(
                            valueColor: AlwaysStoppedAnimation<Color>(
                              FlutterFlowTheme.of(context).primary,
                            ),
                          ),
                        ),
                      );
                    }
                    final listViewPhysiciansResponse = snapshot.data!;
                    return Builder(
                      builder: (context) {
                        final varPhysicians = getJsonField(
                          listViewPhysiciansResponse.jsonBody,
                          r'''$''',
                        ).toList();
                        return ListView.builder(
                          padding: EdgeInsets.zero,
                          shrinkWrap: true,
                          scrollDirection: Axis.vertical,
                          itemCount: varPhysicians.length,
                          itemBuilder: (context, varPhysiciansIndex) {
                            final varPhysiciansItem =
                                varPhysicians[varPhysiciansIndex];
                            return Container(
                              width: 100,
                              height: 100,
                              decoration: BoxDecoration(
                                color: FlutterFlowTheme.of(context)
                                    .secondaryBackground,
                                border: Border.all(
                                  color: FlutterFlowTheme.of(context)
                                      .primaryBtnText,
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.max,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(8),
                                    child: Image.network(
                                      functions.decodeImage(PhysiciansCall.pic(
                                        listViewPhysiciansResponse.jsonBody,
                                      )!
                                          .toList())[0],
                                      width: 100,
                                      height: 100,
                                      fit: BoxFit.scaleDown,
                                    ),
                                  ),
                                  InkWell(
                                    splashColor: Colors.transparent,
                                    focusColor: Colors.transparent,
                                    hoverColor: Colors.transparent,
                                    highlightColor: Colors.transparent,
                                    onTap: () async {
                                      await actions.launchApi(
                                        (getJsonField(
                                          varPhysiciansItem,
                                          r'''$.Link''',
                                          true,
                                        ) as List)
                                            .map<String>((s) => s.toString())
                                            .toList()!,
                                      );
                                    },
                                    child: Text(
                                      getJsonField(
                                        varPhysiciansItem,
                                        r'''$.ProviderName''',
                                      ).toString(),
                                      style: FlutterFlowTheme.of(context)
                                          .titleMedium
                                          .override(
                                            fontFamily: 'Poppins',
                                            color: FlutterFlowTheme.of(context)
                                                .secondary,
                                            letterSpacing: 0,
                                          ),
                                    ),
                                  ),
                                ],
                              ),
                            );
                          },
                          controller: _model.listViewController,
                        );
                      },
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
//Model:
import '/backend/api_requests/api_calls.dart';
import '/flutter_flow/flutter_flow_icon_button.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import '/custom_code/actions/index.dart' as actions;
import '/flutter_flow/custom_functions.dart' as functions;
import 'meet_the_surgeons_widget.dart' show MeetTheSurgeonsWidget;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

class MeetTheSurgeonsModel extends FlutterFlowModel<MeetTheSurgeonsWidget> {
  ///  State fields for stateful widgets in this page.

  final unfocusNode = FocusNode();
  // State field(s) for Column widget.
  ScrollController? columnController;
  // State field(s) for ListView widget.
  ScrollController? listViewController;

  @override
  void initState(BuildContext context) {
    columnController = ScrollController();
    listViewController = ScrollController();
  }

  @override
  void dispose() {
    unfocusNode.dispose();
    columnController?.dispose();
    listViewController?.dispose();
  }
}
//Custom Widget:
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

class Base64Imagebox extends StatefulWidget {
  const Base64Imagebox({
    super.key,
    this.width,
    this.height,
    required this.image,
  });

  final double? width;
  final double? height;
  final String image;

  @override
  State<Base64Imagebox> createState() => _Base64ImageboxState();
}

class _Base64ImageboxState extends State<Base64Imagebox> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
//Custom Function:
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/flutter_flow/custom_functions.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/auth/firebase_auth/auth_util.dart';

List<String> decodeImage(List<String> physicainsPhoto) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // must use files instead of uint8list use final
  final decodedImages = <String>[];
  for (final photo in physicainsPhoto) {
    final decodedImage = base64.decode(photo);
    decodedImages.add(utf8.decode(decodedImage));
  }
  return decodedImages;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}`

**Comment by hughCar389** [comment]
The issue is the custom code I think. When testing the custom code I get a (Invalid utf-8 byte at offset 0) Any advise or possible code editing?

**Comment by rzambroni** [comment]
Hey @hughCar389, as you mentioned the problem might be related to the custom function you're sharing. Unfortunately, we don't know how to best implement this feature and it is difficult to provide solutions and support on specific custom code.  I did a bit of research and the issue might be related to the fact you're trying to decode a binary file as a UTF-8 string. Since you are working with image data, you should not decode it as UTF-8. Instead, you should handle it as binary data.

Have you tried using UInt8List instead of UTF8?

Sorry for not being able to help further. You can also ask about specific implementations on the community page: [https://community.flutterflow.io/](https://community.flutterflow.io/)

**Comment by hughCar389** [comment]
@rzambroni  I have a possible solution to my previous issue. The only thing is my code is have a custom data type and native data type error. I am pretty sure adding [typed data](https://pub.dev/packages/typed_data) import should solve my issue. Is it possible in future updates to add imports to custom functions?

**Comment by rzambroni** [comment]
Hey, will share the feedback internally to see if we can include that on the roadmap (perhaps it is already there).

Thanks!
