### ISSUE TITLE
FlutterFlowChoiceChips does not respect padding selection

### ISSUE THREAD

**Issue by malbrecht0792** [FlutterFlow/flutterflow-issues#3163]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I had to create a new issue because the other one was closed:

https://github.com/FlutterFlow/flutterflow-issues/issues/3054

Using the ChoiceChips widget (FlutterFlowChoiceChips), and specifying values for the selectedChipStyle/unselectedChipStyle should generate a label padding in the code but it doesn't, so the padding selection isn't being respected

### Expected Behavior

When you set a padding for choice chips, it should apply the padding

### Steps to Reproduce

Add a ChoiceChips widget to a page
Apply a selectedChipStyle/unselectedChipStyle padding (one that isn't similar to the default padding - let's say 0 for all sides)
Run the app
See that the padding isn't applied
Download the generated code and notice it doesn't pass in the labelPadding property of selectedChipStyle/unselectedChipStyle

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CivHq6otIsdtK0L6JbsBv9SEvJkR/RY031NZTdA8YN5PLD+wueczBSE5dOO2iTXNAL1mKhnwJptbOv4b+A+UqGxGYc6Z4zrpMbALycGa5RKqSErW0XWpCDf1JJVy+5pm43R1QFMRaWVJg1FOyG/OvdBbsGYDMNWsdBOSaA9/UjFWqQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/21280213/a0b474c5-5157-4fbd-8f81-81e0a300f5d3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/21280213/5cbe2b5b-de45-4604-98b5-2021f2e73a13)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: Web/MacOS
- Browser name and version: Version 125.0.6422.78 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma Version 14.0 (23A344)
```

**Comment by malbrecht0792** [comment]
@msusviela To be more specific... This only happens if the padding you apply is less than the default padding (like 8 I think). It doesn't generate the labelPadding property for selectedChipStyle/unselectedChipStyle properties of FlutterFlowChoiceChips

**Comment by msusviela** [comment]
Hi @malbrecht0792. I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

Thanks for reporting this issue!

**Comment by malbrecht0792** [comment]
@leighajarett @msusviela what's the update on this?

**Comment by sbis04** [comment]
@malbrecht0792 This should be fixed in the upcoming update!
