### ISSUE TITLE
Can't set DragTarget to accept custom data type

### ISSUE THREAD

**Issue by zachary-ferioli** [FlutterFlow/flutterflow-issues#3164]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a component with the base widget being a DragTarget, the data type in the Drag Target Properties section can be set to a custom data type, but when the code is compiled in test mode, a compilation error occurs. However, a draggable component can be set to a custom data type without any errors.

### Expected Behavior

When a custom data type is selected as the data type for a DragTarget, the code should compile and function without issue.

### Steps to Reproduce

1. Create a new component
2. Add a DragTarget to the component
3. Create a new custom data type with any desired fields
4. Set the DragTarget data type to this custom data type by selecting "Data Type" in the first dropdown, and the created data type in the second dropdown within the DragTarget properties menu
5. Run a test-mode session to see that the app fails to compile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sz8jfz5R2rulA1pDpbfpVniQUJj47bZJElO1qEAg2CJTwP4YTXOj9SFRuZNe6T2w7JWCi8WUy+t7Xvs7LVsIXPiiAbIhM1ZBqeD3JcGGVR8WTBZagWURATP1jG0eHzbu7uSVACLZ2cU4d7TuMJdm+aBLrHbrNPm4nAPGLBKLJgWyFKiLCXn0Jg1ZSfCvr

### Visual documentation

<img width="824" alt="Screenshot 2024-06-17 160531" src="https://github.com/FlutterFlow/flutterflow-issues/assets/68446854/930c5bc2-aee1-40f7-bfb1-e5c27144bc27">
<img width="223" alt="Screenshot 2024-06-17 160510" src="https://github.com/FlutterFlow/flutterflow-issues/assets/68446854/0f6dfe24-535b-4d2b-9316-7cdd980a140d">
<img width="206" alt="Screenshot 2024-06-17 160427" src="https://github.com/FlutterFlow/flutterflow-issues/assets/68446854/0615b0ce-6c38-4860-9836-8045fcce5c84">
<img width="517" alt="Screenshot 2024-06-17 160345" src="https://github.com/FlutterFlow/flutterflow-issues/assets/68446854/a6e100df-a7c9-441e-a585-9dd0e94a6c07">

### Environment

```markdown
- FlutterFlow version: v4.1.60+
- Platform: Windows 11 Desktop
- Browser name and version:
- Operating system and version affected: Windows 11 23H2
```

### Additional Information

This is blocking a task for my team that I preferably need to have finished by the end of the week. I need to set a DragTarget to my custom data type called "StringTupple" to accept a draggable component I created that also is of custom data type "StringTupple". This will allow our app users to create 1:1 relations within the app's UI to connect ChatGPT API outputs with desired sections in an email body.

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by zachary-ferioli** [comment]
Thank you!
