### ISSUE TITLE
Windows Desktop Environment keeps crashing

### ISSUE THREAD

**Issue by YeramApp** [FlutterFlow/flutterflow-issues#3165]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Desktop App for developing on Windows keeps crashing instantly after launch. I have had this issue on this machine since trying to install it the first time a few versions ago. In other words, it has never run on this machine.

After fiddling around, I found out that the issue seems to be a log file inside the Firestore folder:
C:\Users\User\AppData\Local\firestore\[DEFAULT]\flutterflow-io-6f20\main

![grafik](https://github.com/FlutterFlow/flutterflow-issues/assets/168533807/7af20e56-5d47-4080-86e6-6ac99806acdd)

When I delete the 4-gigabyte log file, I can launch the app, which then creates that log file again and crashes after a few seconds of use.

### Expected Behavior

I expect, that the app launches normally.

### Steps to Reproduce

1.Install Flutterflow Windows
2.Launch it
3.Watch it crash instantly
4. Go to C:\Users\User\AppData\Local\firestore\[DEFAULT]\flutterflow-io-6f20\main and delete the large 0000x.log file
5. Relaunch
6. Be able to use the desktop environment for a few secounds
7. Watch it crash
8. Goto step 4.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

![grafik](https://github.com/FlutterFlow/flutterflow-issues/assets/168533807/88f46366-8bdd-4684-b3ec-e0488834be92)

### Environment

```markdown
- FlutterFlow version: Current Windows Environment (as of 18th June 2024)
- Platform: Windows
- Browser name and version: Desktop Environment 
- Operating system and version affected: Windows 10 19045.4291
```

**Comment by rzambroni** [comment]
Hey @YeramApp, so sorry you are having that issue, i'll ask internally to see if the log file you identified might be helpful to us to investigate further. Unfortunately, it is a bit tricky to solve bugs happening specifically on a computer. In the meanwhile my recommendation for you is to follow up with our support team so they can take a look at this problem more in depth. You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

Thanks.

**Comment by AlexHuertaM** [comment]
No, you are the only user with this problem, there are several with the same situation, could you help us solve this problem?
