### ISSUE TITLE
Images stored in the database cannot be displayed in production environment

### ISSUE THREAD

**Issue by Miyata19830610** [FlutterFlow/flutterflow-issues#3166]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I set up the database and widgets while watching tutorials on YouTube, but in the test environment, the images were displayed, but when I published them on the web, the images became invisible.

I checked to see if there were any errors in the setting method, and there appears to be no error.

What should I do in this case?

### Expected Behavior

A configuration error occurred when configuring the database from the widget.

### Steps to Reproduce

1. Create a page
2. Insert list view widget
3. Put a container widget in the list view and put an image widget inside it
4. Specify database collection for list view widget
5. Specify the database image storage destination for the image widget path

that's all.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okuflsIp2rs9J1s/IdfoxnSQUG1t+U78njspOFDIbGJzwBIh+duPsXFpucNOrTWlhHE6bgn8y0tbmvvHXUfc5Fw+sQKpk1pN2YAGUTXq8RpCJEsywRn9QHdlhC2qs0cGnux1AXc9vLnwRwDqIfemsaD/DJ5u/Zwh9f6PHaOI=

### Visual documentation

[本文を追加.pdf](https://github.com/user-attachments/files/15882173/default.pdf)

### Environment

```markdown
- FlutterFlow version: 4.1.60
- Platform:arc
- Browser name and version:1.47.1
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by rzambroni** [comment]
Hey @[**Miyata19830610**](https://github.com/Miyata19830610)**,** thanks for the report. Quick question, do you see any logs on your browser console? (f12)? if so, can you please share them.. hopefully, we have some clues there that can help us troubleshoot.

Have you tested on a real device or simulator to see if the issue is persistent there or only web-specific?

**Comment by Miyata19830610** [comment]
In the test environment, it is displayed, so it may be unique to the web, but as for the app, it has not been officially deployed, so I cannot confirm it.

Here is the console log.

<img width="390" alt="スクリーンショット 2024-06-20 11 46 02" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/0cd70a7e-2480-46e7-98eb-3536a0be2342">
<img width="390" alt="スクリーンショット 2024-06-20 11 46 15" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/c6d22dae-82d9-4390-9141-753821b77ef7">

**Comment by nvimalraj** [comment]
> In the test environment, it is displayed, so it may be unique to the web, but as for the app, it has not been officially deployed, so I cannot confirm it.
> 
> Here is the console log.
> 
> <img alt="スクリーンショット 2024-06-20 11 46 02" width="390" src="https://private-user-images.githubusercontent.com/168519605/341251111-0cd70a7e-2480-46e7-98eb-3536a0be2342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTYyNTksIm5iZiI6MTcxODg1NTk1OSwicGF0aCI6Ii8xNjg1MTk2MDUvMzQxMjUxMTExLTBjZDcwYTdlLTI0ODAtNDZlNy05OGViLTM1MzZhMGJlMjM0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwMzU5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2MzZDk2MDkxM2EyMjBiNDg5Y2QzNjM4MTA0MmMwMmRjOGU3OTQyNjMyZjMwNjZlN2MzOThkZDkwMTE1Y2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qx0fWbm-3CI5T4qDYo7ubyIOUEdbTmgfvwtXQ275p38"> <img alt="スクリーンショット 2024-06-20 11 46 15" width="390" src="https://private-user-images.githubusercontent.com/168519605/341251120-c6d22dae-82d9-4390-9141-753821b77ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTYyNTksIm5iZiI6MTcxODg1NTk1OSwicGF0aCI6Ii8xNjg1MTk2MDUvMzQxMjUxMTIwLWM2ZDIyZGFlLTgyZDktNDM5MC05MTQxLTc1MzgyMWI3N2VmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwMzU5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjY1MTA0NGM5YjdhZmFkODYxMzMzZmZiOWUwZWM3OGIzNTAwODI0ZjU4ZmViMGQyZDhjZDVlMTFiMjU1Y2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6RofvM45zq3ChWnA4jGHulpIzz4lXsJTJP3UH6FbrTI">

CORS error can be resolved by going to Project setup -> Platforms -> Advanced Web Settings -> CORS proxy for images -> Deploy with Firebase

Or if you can access the google cloud console, you can setup your own CORS.json directly. ==> This is more efficient while the above option is more convienent (and may incur cost as that uses cloud function).

**Comment by Miyata19830610** [comment]
thank you.

I changed the settings as shown in the image, but the situation remains the same.

<img width="920" alt="スクリーンショット 2024-06-20 13 23 37" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/494e3111-69c6-49c5-a08c-17da3fff4d0f">
<img width="377" alt="スクリーンショット 2024-06-20 13 23 05" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/6febb7ad-29a8-4151-bfea-cbb46a3f13b4">
<img width="377" alt="スクリーンショット 2024-06-20 13 23 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168519605/95e2a8c6-fff9-47af-ad7e-c1f22dd4b3c1">

**Comment by rzambroni** [comment]
The problem blocking the image is still the CORS error. If you are still experiencing the issue please contact our support team so they can take a look a little more in-depth to your project and configs.

You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow.

**Comment by Miyata19830610** [comment]
thank you for your kindness.

I contacted the support team and they asked me to post again on GitHub, so I will do so.
