### ISSUE TITLE
Build Failed variable already declared in scope

### ISSUE THREAD

**Issue by zeephonic** [FlutterFlow/flutterflow-issues#317]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Successful build of the application in RUN MODE

## Current behavior (required)

Build failed error message is displayed.

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/backend/api_requests/api_calls.dart:23:11: Error: 'couponsAll' is already declared in this scope.
    final couponsAll = _serializeJson(couponsAllList);
          ^^^^^^^^^^
lib/backend/api_requests/api_calls.dart:22:11: Context: Previous declaration of 'couponsAll'.
    final couponsAll = _serializeList(couponsAllList);
          ^^^^^^^^^^
Waiting for connection from debug service on Web Server...         57.5s
Failed to compile application.

## To Reproduce (required)

1. Launch current project
2. Click Run
5. Observe that project doesn’t build.

### Bug Report Code (required, generate from Widget Tree)

Error when generating Bug Report Code: "Failure to copy bug report code. Platform Exception..."

## Context (required)

I was attempting to test my application in RUN MODE. I am currently unable to do so and therefore not able to continue development.

The Variable referred to in the error message is an API list-JSON variable. Perhaps there is an issue with how FF is handling the JSON list variable.

## Screenshots / recordings

<img width="648" alt="Screenshot 2022-12-21 at 19 42 05" src="https://user-images.githubusercontent.com/33321746/210419386-35cb1c54-9c69-472a-b1be-27b433789bdd.png">

## Your environment

* Version of FlutterFlow used: Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Safari Version 16.1 (17614.2.9.1.13, 17614), Chrome Version 108.0.5359.124 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): Mac OS 12.5

**Comment by victoriahuang1** [comment]
Hi @zeephonic . JSON typed Lists are not supported, hence the errors in the generated code. However, lists _can_ be encoded by JSONs.

e.g. this is a valid JSON:
```
[
   {
      "foo":1
   },
   {
      "foo":2
   }
]
```

To fix your generated code, you should make sure that the JSON variable is _not_ a list. (You may need to switch the type to set "Is List" to `False`, before switching the type back to JSON).

JSON typed variables will also be ensured to not be set to Lists upon our next deploy.
