### ISSUE TITLE
2nd tab name is missing, but correct wording displays when tapping.

### ISSUE THREAD

**Issue by MaoCTajiry** [FlutterFlow/flutterflow-issues#3171]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I set tab with 3 tab names on the page, then after production publishing, somehow 2nd tab name is only missing.
But when tapping that 2nd tab, correct wording displays.

### Expected Behavior

2nd name should display like in test mode.
<img width="1470" alt="Screenshot 2024-06-19 at 9 13 36" src="https://github.com/FlutterFlow/flutterflow-issues/assets/173012973/2adabf2f-014d-4802-8e38-8bd98eaaaf5d">

### Steps to Reproduce

1. Create new page
2. Add conditional builder > tab bar (with 3 tab names) and set all
3. On test mode, normal view displays
4. After web publishing when viewing via Chrome/Safari in iOS, 2nd tab name is only missing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfi+fq0ItPtbwC+a6JcsZviig7JUccTIMziNZ+exUbfaL1Bu0QPs/CZRJpXu2/aVNcDlCl/X8d0euPiuDlUOw3BEyVRpxi+rVyaQnOe2ilV83UPoeKS3FSAtFhCB260aa7qxRvKtRpLkYFw2a6H+q8bD7DFOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/173012973/0c83fd35-143d-484c-bb8b-fce96cab4376

### Environment

```markdown
- FlutterFlow version: v4.1.60+ released June 15, 2024(Flutter version is 3.19.1)
- Platform: Web (iOS)
- Browser name and version: Chrome v126.0.6478.54 & Safari version 16.5 (18615.2.9)
- Operating system and version affected: iOS 16.5.1(c) iPhone 12 mini
```

**Comment by rzambroni** [comment]
Hey @MaoCTajiry, thanks for the report. It's a very strange issue to be honest. I could not replicate it on blank projects, so I suspect it might be something particular with yours. Have you tried on a blank project? Does it happen when the tab bar is outside the conditional builder?

**Comment by MaoCTajiry** [comment]
Hi @rzambroni-san, thanks for your analysis. Strangely I also couldn't reproduce the same **even if I set whole structure as same!!** 🤣
So let me mark as resolved. (I think something cause this issue but I don't want to analyze further as I have resolved one!!)

Thanks!

https://github.com/FlutterFlow/flutterflow-issues/assets/173012973/8f9c7560-ebd6-4662-b7be-3ae85435f55a
