### ISSUE TITLE
code download broken

### ISSUE THREAD

**Issue by PMFlis** [FlutterFlow/flutterflow-issues#3173]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Before yesterday update, I could download and build my code. Since the update files are missing from the archive and therefore It is impossible to build locally.

### Expected Behavior

All source files should be included in the archive like before the update.

### Steps to Reproduce

open the project storme, download the code archive, see that many files are missing.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/1sIZgobxc+Kn+bPlFmSkRCUMdXOczitVEew4bCIj4Ou0hOuClVFZWZNyzaH1qfU2Ko3wy0MLlhYXlCvArNReAfr5B1rpyTxPPbGGiMqqhPbqOOnNCO8BUG3aG0ImCkCRCGNNtWmAA3GaIFdm+RT2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1470" alt="Screenshot 2024-06-19 at 11 42 26" src="https://github.com/FlutterFlow/flutterflow-issues/assets/74993843/64b9be82-7308-4f97-9e0d-2c20d723ee94">
<img width="1470" alt="Screenshot 2024-06-19 at 11 42 33" src="https://github.com/FlutterFlow/flutterflow
<img width="1470" alt="Screenshot 2024-06-19 at 11 42 39" src="https://github.com/FlutterFlow/flutterflow-issues/assets/74993843/ad88805b-502f-43a7-98bd-913c28b5137d">
-issues/assets/74993843/06bd83b4-86ac-4d51-bfde-a23c29d02ca5">

### Environment

```markdown
- Project: Storme
- Project-Id: stor-me-1nde2w
- FlutterFlow v4.1.61+ released June 18, 2024
- Flutter version is 3.19.1
- Platform: ALL
- Browser name and version: Chrome
- Operating system and version affected: MacOs
```

### Additional Information

This is preventing me from delivering to my client.

**Comment by thomasallnice** [comment]
I have the same problem.

**Comment by GauthierDepierre** [comment]
Same issue here. 
![Présentation1](https://github.com/FlutterFlow/flutterflow-issues/assets/78860975/a1930b40-56da-4b6b-ae43-03ecfc2fafaf)
Preventing from any update for clients

**Comment by rzambroni** [comment]
Hi all, sorry about that, we are currently investigating the projects having this issues to see if we can find a pattern, @thomasallnice & @GauthierDepierre, would you mind sharing bug report codes with me?

**Comment by thomasallnice** [comment]
> Hi all, sorry about that, we are currently investigating the projects having this issues to see if we can find a pattern, @thomasallnice & @GauthierDepierre, would you mind sharing bug report codes with me?

Sure: IT4ok8/6x8pgrsdY1pDLbcdajSQWNUs4RL8/lspBZywgfZzzBLN/fPfQPlhCZOG/Y3w7PGeMp14D+MLuk+LhJ8ACCy2uc6ZNypZcFzz/UXG6M7GTF7m8Q3MmEcRgf2KZ1KS3sxYlFNFsWkIF6mCQC+eiQXLUHrn6DVQ8Sq/LZO4=

**Comment by rzambroni** [comment]
Thanks, will pass it over to the team so they can investigate further.

**Comment by joekman990** [comment]
I'm not sure if this is the same issue I was experiencing but i only have this issue on the desktop app  

https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/c8da4465-d592-43fe-b4d4-8e76a0baa886

**Comment by GauthierDepierre** [comment]
> Hi all, sorry about that, we are currently investigating the projects having this issues to see if we can find a pattern, @thomasallnice & @GauthierDepierre, would you mind sharing bug report codes with me?

Sure here it is ITFXhfKBw5N2oblE+arUY8FshigwGUwbUOc7j9VEGAsjCePsOpoXdePRalJtYuqHf1ZYHFH9uHkDzMLHid7tMsIpOTWuGbk6wqttUxDhZGOQWrq4O8+BPGpSRMNhJ3KG0MGV2iZ+GNJfWVof2mGqJd6+b3qCf9qOYwx5e6fDbOY=

**Comment by GauthierDepierre** [comment]
Ps: it is not always the same behavior, tonight on the webapp (chrome) on Mac OS I can download 2 over 3 widgets in the code, this morning it was only one. Same behavior regardless the usage of desktop or web app, on Mac OS.

**Comment by Brocoleta** [comment]
Same problem

**Comment by msusviela** [comment]
The fix for this is issue is already deployed and you should be able to download the code correctly. Please let me know if you face any inconvenience<br><br>@PMFlis @Brocoleta @GauthierDepierre @joekman990 @thomasallnice

**Comment by joekman990** [comment]
it is working for me now thanks

**Comment by PMFlis** [comment]
It works perfectly, thanks for sorting it out

**Comment by Brocoleta** [comment]
thank you!
