### ISSUE TITLE
Project broken - can't abort merge - can't load project

### ISSUE THREAD

**Issue by danielthedifficult** [FlutterFlow/flutterflow-issues#3178]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Following a complicated series of merges, our project (ID: VTDBpCzZQPVbZv3nZyRB) is now in an unstable/broken state.
1. The web UI only leads to the 'Branch Merge in progress' screen.
![Screenshot 2024-06-19 at 16 07 21](https://github.com/FlutterFlow/flutterflow-issues/assets/1290033/1b1485a0-50fc-4257-b2b5-3fcf31770c30)
2a. Clicking "Exit project" goes back to the project selection screen. Going back in to the project goes back to step 1.
2b. Clicking "Go to Branch" brings us directly back to step 1.

### Expected Behavior

I expect to be able to load the project, and hopefully merge my branches without losing any changes

### Steps to Reproduce

Here are the steps that led to this problem:

1. Branch 'main' into three separate branches, "Feature", "italian translation" and "turkish translation" with the intention of adding these two languages to the app.
2. Merge Italian first into main
3. Attempt to merge Turkish into main - the translation seems to 'merge' properly, after the merge it is not found in the main branch.
4. Add "Turkish" language to main with blank entries.
5. Attempt to merge Turkish into main **again** - the merge finishes, but now the code is 'broken' with Turkish declared twice in the app, but with no translations (from step 3) actually in the codebase. Project will not compile due to variable `trText` declared twice in `internationalization.dart`
6. Make some changes on 'feature' branch, attempt to merge back to main.
7. Flutterflow web platform is now stuck in 'merge' infinite loop.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

iCannotLoadTheProjectToBeAbleToGetThis

### Visual documentation

![Screenshot 2024-06-19 at 16 20 15](https://github.com/FlutterFlow/flutterflow-issues/assets/1290033/b25ad5da-769d-46a6-9462-46c5a47035d3)

https://github.com/FlutterFlow/flutterflow-issues/assets/1290033/ce27a5bd-f986-455f-9fce-608a20679f5c

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Multiple platforms, Web, Desktop, Mac/Windows
- Browser name and version: Multiple platforms, Web, Desktop, Mac/Windows
- Operating system and version affected: Multiple platforms, Web, Desktop, Mac/Windows

Neither the web javascript console nor network inspector show any relevant errors/issues.
```

### Additional Information

We are at a complete standstill for working on our project. We can't launch features and new languages we have been working on for weeks because of this.

**Comment by eusouoviana** [comment]
I'm having a similar issue right now on my project. Wasn't able to get support yet.

**Comment by msusviela** [comment]
Hi @danielthedifficult.

I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it or just the steps to reproduce it from blank. Without a bug report code (that I know that you can't generate because of the nature of the issue) is really difficult to know what's going on and to reproduce it.

If the issue is particular of this project, I'll suggest that you contact support by email [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. They can probably have a look at you project and maybe restore it.

**Comment by danielthedifficult** [comment]
@msusviela Thanks for the response. I know this is difficult to troublehoot.

I think a bug with repro steps would be:
1. Create two new branches
2. Add a different language to each of these new branches with some translations
3. Merge one language, then the other

I think the languages will not be merged properly.

**RE: contacting support:**
One of our devs contacted support Monday night and received this message this afternoon, and yes, we are still experiencing the same problem.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1290033/b88690c2-9eff-4ee3-961f-2b3af12d764d)

**I opened a second case myself (Case #3495), about 23 hours ago, with a follow up with additional information last night, no response yet.**

As for our 'larger' problem currently, **if you have any ability to restore our project to something pre-merge, I would be so un believably grateful...** I know it's not the dev's job but we're really stuck here and losing faith in our ability to rely on FF without support.

 Alternatively, if you can ping someone on the support team who can look at our case, it would be amazing.

 Our #1 priority is restoring access to the project, and we don't have any recent changes we need to save.

**Thank you in advance for any and all energy you can send our way!**

**Comment by msusviela** [comment]
I communicated your case with the ENG team. They suggested that it could be because you're on an outdated client. Please let me know if you're on the last version so we can troubleshoot it if it still happens as soon as possible.

**Comment by danielthedifficult** [comment]
We were using the web, and did not have any prompts to update.

Either way, it looks like someone restored about 40 mins ago, very glad we can access again.

We still need help with this tricky merge, but I'll continue with them for now.

**Comment by msusviela** [comment]
Great! If you still have problems with that please provide me with a new bug report (I'll need a new one because of the new changes) and I can send them to support if they need a manual overwrite
