### ISSUE TITLE
CMS can't connect to firebase

### ISSUE THREAD

**Issue by vardarsezgin** [FlutterFlow/flutterflow-issues#3179]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

CMS-Database editor is has a problem with connecting to firebase.

Nothing changed with my project, it didn't happen before also.

### Expected Behavior

connect and show data from firebase

### Steps to Reproduce

open cms

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozsiAz89gruFG1pDuKcJV/CQWNlN+bbs7kspBazwbfe+uB4kqevfOTERBZ+2qYG9PM2GGgWoW0tHFhdrDJ8ddOS6WfbY/zKhAawH/cDumSpjTFJWgVXMmJ9JQIECw06WFhBFQJvZZLUVk2DiIONi/SgLUJL76NUQeDa/LZO4=

### Visual documentation

<img width="780" alt="Screenshot 2024-06-19 at 17 27 06" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103498910/c8bf6c99-0b6b-4f5f-a941-4bfecc858b85">

### Environment

```markdown
- FlutterFlow version: Prod: 4.1.61 - June 18  / Beta: 4.1.61 - June 17
- Platform: Mac OS
- Browser name and version: Chrome 126.0.6478.61
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by rzambroni** [comment]
Hey @vardasezgin, thanks for the report, it seems like there is some misconfiguration on the Firebase side. This might vary from project to project but according to some instructions from our support team you could make it work by removing the [firebase@flutterflow.io](mailto:firebase@flutterflow.io) user from the auth list:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9be5fe51-9bec-488c-944d-58db349fca7f/971a87d6-fbc5-48a3-b7fa-b8561e386665?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YmU1ZmU1MS05YmVjLTQ4OGMtOTQ0ZC01OGRiMzQ5ZmNhN2YvOTcxYTg3ZDYtZmJjNS00OGEzLWI3ZmEtYjg1NjFlMzg2NjY1IiwiaWF0IjoxNzE4ODI0OTU0LCJleHAiOjMzMjg5Mzg0OTU0fQ.jhJNG5IhBeTYL5scFhiMJRDODS6VUjqPCqamKQ0BgRU " alt="image.png" width="1829" height="570" />

Once done, you should be able to refresh the CMS page, which should load. 

If not, then it's prob a Firebase / GCP config issue, and you should reach out to support so they can help you fix it. You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

Thanks.

**Comment by vardarsezgin** [comment]
Oh that's weird, it's fixed after your suggestion.

I don't recall I did something manually, but anyway **thanks so much!! @rzambroni**

**Comment by rzambroni** [comment]
glad you were able to solve it! thanks.
