### ISSUE TITLE
Checkbox UI not updating in realtime from firestore data

### ISSUE THREAD

**Issue by SalilHarit** [FlutterFlow/flutterflow-issues#3184]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/39475669/24099959-c7a8-47b5-a6ee-ad3fec772854)
I have 9 checkboxes with initial states connected to backend booleans for updating visibility on buyer's side for pricing options and i want to update the checkbox state unchecked or checked realtime from firestore two way binding essentially where i can change the data from checkbox and boolean value from firestore can update checkbox state currently it only happens when i exit and revisit the component which is not ideal behaviour and i had also added counter on checkboxes for limiting 3 choices at a time but that didn't work either 

### Expected Behavior

checkbox should update visual state from backend if changed from else where like the 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/39475669/ad805fa3-7e6d-4597-a805-1efe07d6fad9)
checkboxes from options above 

### Steps to Reproduce

1. build a component and add 3 checkboxes with firestore as backend and booleans attached for state control 
2. update the backend on the same page using another 3 checkboxes which are also connected to same fields as 3 checkboxes previously

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8iB24ZOj7wC1aX2KfpR/Tk6Nm04a+YsscpCbw4bIYj2P4lzY876P01VOMvkSkFAPFm2p14e0sLxuNnDO+5dJUuCfI9z1pAJZAvNWk+WVJ+TF7WCQnYnHfFUGHLGyJiVswhNBNVaS1416k2YHOmUb3PbQZjqIUQ8Sq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/39475669/35947a2c-d151-4572-9188-009451b90350)

https://github.com/FlutterFlow/flutterflow-issues/assets/39475669/b132e1df-9cf2-4565-bea5-3b21096f49be

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @SalilHarit. Just one question regarding this issue so I can look further into the problem:

The issue here is that you update the state from other checkboxes and they update correctly, but the other ones related to that field are not updating?

**Comment by SalilHarit** [comment]
yeah two checkboxes both connected to same boolean record in firebase that should update on front end like if on backend boolean is true and both are showing checked on inital page load after i uncheck one checkbox other also automatically become unchecked

**Comment by msusviela** [comment]
Ok, I see it. <br><br>As you have in your project, it'll only select and deselect on the widget you're selecting and not on the other related to it (The query will run in firebase to update it but regarding the user interface, it will only trigger the changes only on the checkbox you're interacting with).

My suggestion to fix this is to have maybe a page variable with the value (selected or deselected for that case) and then when you check that box, you'll need to trigger the backend call and also y change that variable. You should associate that variable to both checkbox to display that value.

The issue here is that when something is modified in the database, it'll only impact the database. The UI changes are related to the particular widget and how it's handling the state in the generated code, so that's why it's not updating in both cases.

Let me know if you have any questions.

**Comment by SalilHarit** [comment]
figured, working on it, thanks man ! my approach was bad ig :D

**Comment by SalilHarit** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/39475669/557405b7-ec7e-47b2-8aa7-5216d793495d)
there's 9 checkboxes that i want to track with counter and each counter as i mentioned before has initial value set from firebase but im confused how its not working correctly

**Comment by msusviela** [comment]
Hi @SalilHarit. So that issue is still persisting? Are you taking the same approach as you were when first opening this issue? <br><br>Can you share a new bug code with the new changes so we can check that?

**Comment by SalilHarit** [comment]
yes, i don't now i am just using your advice and using component state variable to update backend but the counter doesn't work 

IT4sl8iB24ZOj7wC1aX2KfpR/Tk6Nm04a+YsscpCbw4bIYj2P4lzY876P01VOMvkSkFAPFm2p14z+OiOhYX1DPpdFziAbLY9ypZbWAnxVlmXaKWTF7WCQnYnHfFUGHLGyJiVswhNBNVaS1416k2YHOmUb3PbQZjqIUQ8Sq/LZO4=

**Comment by msusviela** [comment]
I just checked your project. <br><br>I think that you're missing to connect the local variable to the other checkbox that you want to relate to the other. I just saw that on the checkboxes that are on top you are still only making the backend call but not associating them to the local variable

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
