### ISSUE TITLE
Enum Type dropdown is not responding when creating Enum field in Data Schema

### ISSUE THREAD

**Issue by HerreraCarlos81** [FlutterFlow/flutterflow-issues#3187]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a Data Schema, if you create an Enum field, the second dropdown that appears ("Enum Type") is unclickable, preventing you from concluding the field creation as this is a required field but is non responsive.

![Unclickable dropdown](https://github.com/FlutterFlow/flutterflow-issues/assets/66761818/b3d62a8e-855b-4246-aafb-87edf0330da2)

### Expected Behavior

The dropdown should display the options for Enum Type and allow the selection of one so that the user can then proceed with the creation of the field.

### Steps to Reproduce

1 - Create an app
2 - Go to the left side menu option: "Data Types"
3 - Add a new data type
4 - Name your new data type
5 - Add Field
6 - Give field a name
7 - Select "Enum" as the field's Data Type
8 - The broken dropdown called Enum Type is displayed but is unresponsive

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not a widget error

### Visual documentation

![Unclickable dropdown step 6-8](https://github.com/FlutterFlow/flutterflow-issues/assets/66761818/6ca3bdd1-a6ba-49fe-b724-1dcddef93040)
![Unclickable dropdown step 5](https://github.com/FlutterFlow/flutterflow-issues/assets/66761818/75208bda-b2f1-4490-8e0b-f69457e97066)
![Unclickable dropdown step 3-4](https://github.com/FlutterFlow/flutterflow-issues/assets/66761818/caf9dc58-d948-4c87-ab7f-2042982ab188)
![Unclickable dropdown step 1-2](https://github.com/FlutterFlow/flutterflow-issues/assets/66761818/f3e5312d-0de7-4093-af38-e6ddb47e08cd)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61+ released June 19, 2024
Flutter version is 3.19.1
- Platform: Windows App
- Browser name and version: Windows App
- Operating system and version affected: Windows 11
```

### Additional Information

Project: bug-report-project-tty5cz

**Comment by msusviela** [comment]
Hi @HerreraCarlos. 

Is this issue happening when you have created enums or just when you don't have any enums created in the app? <br><br>I was able to replicate this issue only when you don't have any enums created. Please, let me know this detail so we can look further into it

**Comment by kaparelosfilos** [comment]
Hello guys! I think I have the same issue, in a different way, I've recorded a very short video showing the case: https://www.loom.com/share/05727bf7e4384b2291d1ea410c2f872c?sid=68b3b98c-857a-4ffb-85f5-bb50a5edf52e

**Comment by HerreraCarlos81** [comment]
My perception is that the creation of the Enum field would trigger the creation of the Enum itself within the Data Type creation process. I had not created enums when attempting to register the Data Type field as an Enum field.

In this case, a simple message saying there are no enums created would settle the issue, right @msusviela ?

**Comment by msusviela** [comment]
Yes, sure. It's an improvement that we can make. I'll communicate that to the ENG team so they can check on that. Thanks for filling this!

**Comment by msusviela** [comment]
Hi @kaparelosfilos. This looks like an issue but seems to be unrelated to this. Can you open another issue with that details so we can look into it?<br>Thank you so much!

**Comment by hrugani** [comment]
I am facing the same problem. After selecting the enum type, I can't define the enum values.
The user interface doesn't offer any way to input the list of values.

**Comment by hrugani** [comment]
Sovled.
Since you defined the enum in the custom data option that the list of enum you defined will be shown in the schema definitions.
