### ISSUE TITLE
Clear text field behavior is different on compiled IOS app compared to desktop

### ISSUE THREAD

**Issue by piershare** [FlutterFlow/flutterflow-issues#3189]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page in my app called playground where, if I click on a button, we simply clear a text field widget. On web, the text field clears and the cursor goes away from the text field. On iOS, the cursor/text field widget stays active for the same behavior.

### Expected Behavior

The text field widget should clear on both platforms.

### Steps to Reproduce

1. Open app.
2. Click on go to playground from launch screen
3. Type into the text widget on the page
4. Press button
5. Notice different behaviors on both platforms.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMrl34ZPxOVY15Dtbe5sjjg4G1B7TLJEoetxc0gbfe/4E5l+d/fBNxBuXtCzaH1cImKGrFMGw/zRiODtUcYFNRWbc4c4+bhcZBPPYz+5eJSDPKqVPEFTM8ZbGky50LunqwpTOtt0SFI63Tn3BuitVT6Cf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/47877943/db97c900-8664-44c2-932b-ec2839c3f77d

### Environment

```markdown
- FlutterFlow version: 4.1.61
- Platform: iOS and MacOS
- Browser name and version: Arc 1.47.1
- Operating system and version affected: MacOS and iOS
```

**Comment by msusviela** [comment]
Hi @piershare.<br>Thank you so much for filling this. I have tested it and yet it's replicable, It's something that's coming from Flutter side (if you create a blank app using only Flutter and add a text controller, the same behavior is experienced (It behaves differently on web than on mobile)).

**Comment by piershare** [comment]
Ok understood thanks. So the behavior needs to be fixed on the flutter side and can't be addressed by Flutterflow? Do you think the upgrade to 3.22 would fix this?

**Comment by piershare** [comment]
I am sorry, this isn't a bug I confused it with another issue my apologies, thanks for your understanding.
