### ISSUE TITLE
Generate children from a variable throw a compilation error

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#319]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Generate children from a variable and be able to use his data

## Current behavior (required)

Throw a compile error

## To Reproduce (required)

1. Create a List of string in a Local State
2. Go to a page and a add this widgets structure

![image](https://user-images.githubusercontent.com/36147203/210669949-d68c91f8-cad1-4504-a9e6-54d4c897b4c1.png)

3. Generate children from the Local State

![image](https://user-images.githubusercontent.com/36147203/210714648-05b95871-90e6-4b17-a28f-0db84d8c5310.png)

4. Now try to compile but show an error.

### Bug Report Code (required, generate from Widget Tree)

ITESls/l7YVgos9c0anucu16hQAkQzM8bYJMl9dTcwwYB7b1E4oLP+r+VxNZTfGUY29DMVn8+UYE+tbnj4XtGu1cITGBatE2k/UwKlCvHAM=

## Context (required)

I want generate children from a List and use them. I use a local state in this example, but it happens using others ways like getting a Supabase Row on Scaffold and then use that row to generate children. 

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/210669980-238c8b52-876d-4700-83f7-e73b7a0f7177.png)

## Your environment

* Version of FlutterFlow used: 29 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by Pepino-GR** [comment]
Hi Franco98404,

as you noticed, I cannot reproduce it with a normal list from a local state. The problem with the Supabase row is already reported in issue #302.

**Comment by Franco98404** [comment]
Respect with to the local state, you were right, it works, but I was very surprised because FF wasn't updated recently So I started to investigate, and I realized when using "List" as a name the local state produces the bug and have more sense the compilation error.

![image](https://user-images.githubusercontent.com/36147203/210933108-f7b4f2ac-5df2-42f6-87d1-06c8d7b0957b.png)

I think that it is necessary to change the name and the body of the bug report.

**Comment by agreaves** [comment]
Hi @Franco98404, yes this does seem to cause issues so I've made sure it's no longer possible to set a field called "List" which will be present next release!
