### ISSUE TITLE
attempting to generate ai page returns different errors

### ISSUE THREAD

**Issue by snowboarder** [FlutterFlow/flutterflow-issues#3191]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Running AI page gen is returning various errors (see attached)

### Expected Behavior

create page

### Steps to Reproduce

1. generate page with AI page gen
2. returns error (see below for SS)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oj8nc05NOmN9G15PTbcFViiUsJm4jarxNm+1+GUo3B5fNG4gIZfTBXE9uOP25dghMfU6krz4Kw6zHm9z1LfUCByStf7pawpNuVwrxQXGuMpS4CZCKeHFEGshRFUyO4YmvsyVSXddZWi0A11yUf9myQgXAHrryDFQjAOaKDKDXrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

![2024-06-21_06-32-29](https://github.com/FlutterFlow/flutterflow-issues/assets/1418909/4d026ae1-81be-4cfc-a5b2-720b98062514)
![2024-06-21_06-33-46](https://github.com/FlutterFlow/flutterflow-issues/assets/1418909/9f31c175-8a81-4e88-9cbe-f20ec8bd2ffd)
![2024-06-21_06-39-00](https://github.com/FlutterFlow/flutterflow-issues/assets/1418909/afac08b6-89f9-4ccd-a00e-db8f36fbc4ef)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61+ released June 19, 2024
Flutter version is 3.19.1
- Platform:Windows
- Browser name and version: Chrome
- Operating system and version affected:  WIN11
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
