### ISSUE TITLE
Media Files not uploading

### ISSUE THREAD

**Issue by sparkwellnessapp** [FlutterFlow/flutterflow-issues#3193]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Media uploads are not working. Neither in the Image widget or the Customized Icon widger. It just keeps loading...

### Expected Behavior

Media files succesfuly uploaded

### Steps to Reproduce

1. create new page 
2. add image widget
3. Choose Image Type "Asset"
4. Upload image

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whcj1z4ZNj7wD7qrAasFvmioWCDt5bZ0Nje5DbCs9JLbqB4kiY/XsQExDXeaoSnxIIkSmmlMxpd6MjuD1FPU6Gy+Vb4hmybVydg/jfGSWe5OBDqi0fkFRN9NUGWqd08GzughdKrJfSnsu1GWmC+u+dDXYQJDYImdISq/LZO4=

### Visual documentation

![צילום מסך 2024-06-21 133353](https://github.com/FlutterFlow/flutterflow-issues/assets/165265738/611b887f-e155-40c5-bae4-196fd01bc62e)

### Environment

```markdown
- FlutterFlow version: V4.1.61+
- Platform: Desktp
- Browser name and version: 
- Operating system and version affected: (desktop) Windows 11 Home 23H2
```

**Comment by msusviela** [comment]
Hi @sparkwellnessapp I was not able to reproduce the issue. Have you tried with other images and got the same response? What's the extension of the file you're trying to upload?

Please, let me know if the issue still persists.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
