### ISSUE TITLE
Dynamic Link not working in IOS due to FirebaseDynamicLinksCustomDomains

### ISSUE THREAD

**Issue by azizirac** [FlutterFlow/flutterflow-issues#3195]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have setup dynamic link as documentation https://docs.flutterflow.io/advanced-functionality/deep-and-dynamic-linking by using the default URL "myapp.page.link" and it was working fine in both IOS and Android. After purchasing a new domain, I decided to use it for dynamic link URL as "link.myapp.com". After doing so, IOS stopped routing the clicks to the specific page, and instead to home page.

### Expected Behavior

Using my custom domain, the dynamic links should still work in IOS. I reported it in https://community.flutterflow.io/ask-the-community/post/dynamic-link-not-working-in-ios-due-to-firebasedynamiclinkscustomdomains-7tn88A4TnP4XxWn?highlight=EpC9IfGFhmtGqKT

### Steps to Reproduce

1. Buy custom domain like "mydomain.com"
2. Add a subdomain to hosting in Firebase like "link.mydomain.com" so it will not conflict with your webpage
3. Use your new domain as URL for dynamic link in FlutterFlow
4. Create a page in your app which has a button "Share" which uses dynamic link. You can add a parameter to your page "mypage/:id" to open specific details of your app.
5. Test the app in IOS. Create link, paste it to a chat group or Notes, then click on it. The app will open because Flutterflow uses the same URL as deep link, however your page path will not open because the firebase call to read the dynamic link fails.

I have tried everything and red all the posts. Then I used the debugging tools to see logs, and I found out that IOS was not able to resolve the dynamic link.

`NSLocalizedFailureReason "Universal link URL could not be parsed by Dynamic Links"`

Root cause: `FirebaseDynamicLinksCustomDomains` is missing in Info.plist as described in https://firebase.google.com/docs/dynamic-links/custom-domains#console. After downloading the code and adding it, it worked.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhs/lvM9NsdsC0K6Ja8dGliQ6JjocTeU30+thcw4bI+OtO5oceODSRE1CWOqHTAtEH2f9nl0K+tHIjvPXMvABBxGbR6U51s5fUxDhQXGiRcmxBpaddHFCRPFgI2nG1raZqiV7KtFuL0Jh616IB96ub3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="745" alt="Screenshot 2024-06-21 at 08 37 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11569373/e355ca70-7eee-41b8-bfdb-dea6023423aa">

### Environment

```markdown
- FlutterFlow version: v4.1.61
- Platform: MacOS
- Browser name and version: n/a
- Operating system and version affected: iPhone 12 with IOS 16.6 and iPhone 15 Pro with IOS 17.5.1
```

### Additional Information

Dynamic links are not working anymore in IOS with my custom domain. I have to add manually the config to Info.plist every time to make work.

**Comment by paulperez-dev** [comment]
Hi @azizirac! This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog (be able to edit the file or that FF add the configuration automatically) and we will get to it as soon as possible. Thanks for your feedback!

**Comment by azizirac** [comment]
@paulperez-dev thanks for the quick reply. Is there a way we can track the progress or have an ETA? I am launching soon my app in Prod, and would love to have some idea since this (dynamic link) is a critical component for the success of the app.

**Comment by paulperez-dev** [comment]
Hi @azizirac! Sadly there is not a public tracker for feature requests. There is no ETA for this feature yet.
