### ISSUE TITLE
Modifying English translation causes gray screen

### ISSUE THREAD

**Issue by danielthedifficult** [FlutterFlow/flutterflow-issues#3196]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.
Project ID: `time-left-lkfqib`

### Current Behavior

In the "Languages" area of "Project Setup", modifying the 'root' language (English) text results in a gray screen

### Expected Behavior

I expect to be able to modify the text cells without crashing.

### Steps to Reproduce

1. Open "Languages" section of "Project Setup"
2. Modify any 'English' text
3. Component goes gray

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

TheSettingsPageDoesNotHaveABugReportCode

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/1290033/0d804d17-6821-4e5c-b900-d4a4538d0bf8

### Environment

```markdown
- FlutterFlow version: 
- Platform: Web
- Browser name and version: Latest versions of Brave and Safari
- Operating system and version affected: MacOs Monterrey
```

### Additional Information

I'm trying to update the translations of our app for a launch in a new country... the UI is SO SLOW, buggy/crashing, and in order to modify the EN translations, I have to copy/paste in order to make the change 'all at once', as I can't edit in-place.

**Comment by paulperez-dev** [comment]
Hi @danielthedifficult! A fix is on its way! I will keep you posted here about any updates.

**Comment by danielthedifficult** [comment]
@paulperez-dev any updates/ is this fixed?

We're going to be adding two more languages, would love to know this won't be an issue :)

**Comment by paulperez-dev** [comment]
Hi @danielthedifficult! It should, please try again!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
