### ISSUE TITLE
Unable to auto create firebase db.  Login timeouts  FF crashes

### ISSUE THREAD

**Issue by snowboarder** [FlutterFlow/flutterflow-issues#3197]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"Let us Create a project for you" / Create project --> under firebase section has authentication issues when signing into google account as the popup screen goes white.   I was forced to switched from FF Win 11 to browser in order to use this feature. 

### Expected Behavior

Login and create Firebase db , but it Login timeouts  and then FF for windows crashes

### Steps to Reproduce

1. auto create firebase
2. login with google
3. white popup window as seen in picture/videos

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oj8nc05NOmN9G15PTbcFViiUsJm4jarxNm+1+GUo3B5fNG4gIZfTBXE9uOP25dghMfU6krz4Kw6zHm9z1G8cBITieGKZc1qpcbgLgUlyQV7amBbjhSHZEGshRFUyO4YmvsyVSXddZWi0A11yUf9myQgXAHrryDFQjAOaKDKDXrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

Screen recording reproducing error here:
https://youtu.be/XUD7CaXzwJU 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61+ released June 22, 2024
Flutter version is 3.19.1
- Platform:  WIN 11,  FF for windows
- Browser name and version: Chrome 
- Operating system and version affected:Win 11
```

### Additional Information

no additional info to report

**Comment by rzambroni** [comment]
Hey @snowboarder, thanks for the report, this is actually a duplicated of: [https://github.com/FlutterFlow/flutterflow-issues/issues/2839](https://github.com/FlutterFlow/flutterflow-issues/issues/2839)

The team is already aware of the issue and is currently assigned to an engineer to be fixed. Please refer to the original ticket for updates.

As a workaround i believe you can use the web version of FF (app.flutterflow.com) to create and connect the project and then continue in desktop if you want.
