### ISSUE TITLE
Failed to create Theme Widgets

### ISSUE THREAD

**Issue by hidech** [FlutterFlow/flutterflow-issues#3198]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to create a Theme Widget via Right Click menu, it doesn't be created. No theme widgets appeared.
But after that, when I try to create a  Theme Widget as same name as above, it shows "Name already used".

### Expected Behavior

I can create Theme Widgets via Right Click menu.

### Steps to Reproduce

1. Create a button
2. Right click and "Save as Theme Style widget"
3. Set a name and save

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMjf3It2xLVE0IfqdflKmiMwFjMMbY0v0u0bFB4cGJzrP4k2Y8/4U0NKT7CzS25IE2D8mmQE7tLvifHDUsIBAzitbrpE0JVAShXwIHylWoyXO7uSYXAkP9hWC26x58KFqxJ5LttiS1pm2V+hNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![スクリーンショット 2024-06-22 14 00 06](https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/af974cef-a3d1-40d8-b954-ca0952dd82c0)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/235ba42a-52a6-46fb-9c98-42c7da79429b)

### Environment

```markdown
- FlutterFlow version: 4.16.1+
- Platform:Mac
- Browser name and version:Chrome 126.0.6478.62
- Operating system and version affected: macOS 14.5
```

**Comment by paulperez-dev** [comment]
Hi @idea-garage! I can't reproduce. Can you please verify if this is happening to you in the latest release?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
