### ISSUE TITLE
Can't download code.

### ISSUE THREAD

**Issue by LeeSingChanYau** [FlutterFlow/flutterflow-issues#32]
Expected behavior (required)
Downloading the source code of the entire project.

Current behavior (required)
Our application has no bugs, but when we try to download the code, firebase config errors showed up (only shows when we try to download the code), and even after we reconfigured the files, it threw another error of package name miss match, and then it says fail to build and fail to download. We tried it several times and it was the same problem.
I know our application is 100% bug free, but whether there is error or not, we want to download the code immediately.

To Reproduce (required)
Download source code, application has no errors
Firebase config errors showed up
Reconfigure the files
Firebase config errors disappear
Package name mismatch showed up
Reconfigure the files
Package name mismatch disppear
Build failed (download failed)
Context (required)
We need the source code to test and deploy the app locally and on actual devices.

Your environment
Version of FlutterFlow used: V3.0
Platform (e.g. Web, MacOS Desktop): MacOS
Browser name and version: Chrome
Operating system and version (desktop or mobile):Desktop

**Comment by bulgariamitko** [comment]
Can you give us more detail instructions or a video because I cant reproduce this issue. Also do you have some custom code? Can you delete it and try again to download the code.
