### ISSUE TITLE
(CMS)Data Manager Import - New fields error (Can't separate new/existing fields)

### ISSUE THREAD

**Issue by vardarsezgin** [FlutterFlow/flutterflow-issues#3202]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When importing documents with data manager, it shows new fields at table correctly but after import it gives an alert about there are new fields and show all the fields as new and wants to import them.

this problem exists both in beta and prod.

### Expected Behavior

Separate new fields with existing ones and then just add new fields.

### Steps to Reproduce

import data with .csv
continue

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozsiAz89gruFG1pDuKcJV/CQWNlN+bbs7kspBazwbfe+uB4kqevfOTERoZ73iY39LPmK0r2oW0s2OiNrPMPVfOQ2AfbY4/5ZyFwvyXmGlMaaxFJWgVXMmJ9JQIECw06WFhBFQJvZZLUVk2DiIONi/SgLUJL76NUQeDa/LZO4=

### Visual documentation

<img width="1775" alt="Screenshot 2024-06-22 at 14 02 35" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103498910/4f128bbf-f5de-499d-9b2e-cf3eacaf8747">
<img width="1477" alt="Screenshot 2024-06-22 at 14 07 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103498910/1ab79af3-700c-4a18-a1b5-7965144fdc43">
<img width="743" alt="Screenshot 2024-06-22 at 14 10 08" src="https://github.com/FlutterFlow/flutterflow-issues/assets/103498910/39f6d151-a315-48e5-9048-cb89ab6f9923">

### Environment

```markdown
- FlutterFlow version: Beta: 4.1.62 - June 19
- Platform: Mac OS
- Browser name and version: Chrome 126.0.6478.61
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by paulperez-dev** [comment]
Hi @vardarsezgin! The text can be a little misleading, but the list shows the new structure of the collection. In [this video](https://www.loom.com/share/52e2f2afce104f63a87e1e935ebd8e1f?sid=08e7f9c3-8c05-4ec3-82f4-0f897d5d5ba6) from the documentation, you can validate that it is the expected behavior. I will create a ticket to change the text. Thanks!
