### ISSUE TITLE
Null in document field type Boolean, but query returns "False" (not null/empty)

### ISSUE THREAD

**Issue by YangWeiShao** [FlutterFlow/flutterflow-issues#3203]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a collection in which a field is Boolean data type. However, if a document in that collection has _null_ in that field and I query that field of that single document, the query returns _False_ rather than _null_.

### Expected Behavior

The return should be _null_.

### Steps to Reproduce

1. create a collection
2. add a field in data type: Boolean, named **"TestBoolean"**
3. create a document in that collection, but keep it empty (null)
4. in any page, create a widget (e.g., text widget) that the text is a varible of query collection -> single document -> get document property -> **"TestBoolean"** 
5. the widget will show _false_ but not empty/null

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goeUD+ZPiasJAhR4jNlx7bZNE0ux+UQAjNZzsBJwpWvilUG9YYbCmdHxqIE79uDgEwdLrv9/+UPE7FAyHbqo4/rtyURWXXl6neLK0OquZOH9tEcZhCkCa16uj2BYkJtp1S1lpig/GSw==

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10434125/4facf375-68d3-462d-8d2c-4fbadd74508e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10434125/3199a463-48bf-4eed-ac39-9e4b54ced0ef)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10434125/52993d16-1aa1-4cbc-b56a-aae60000d1ed)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61+ released June 18, 2024
Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Chrome Version 126.0.6478.63 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
Hi @YangWeiShao. I wasn't able to reproduce the issue from a blank project. A new version of FlutterFlow was out today. Could you please check if it's still persisting in your project? Thanks!

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
