### ISSUE TITLE
Duplicate Container Issue When Moving TextField to Higher-Level Column

### ISSUE THREAD

**Issue by vieiraes** [FlutterFlow/flutterflow-issues#3204]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I drag a TextField that is inside a Container and try to move it to a Column at a higher level, another Container is duplicated immediately below it. This duplication repeats as many times as I attempt to move the TextField.

I have attached images that illustrate the issue.

### Expected Behavior

When moving a TextField to a higher-level Column, it should be relocated without creating any additional Containers.

### Steps to Reproduce

Create a TextField inside a Container.
Attempt to move the TextField to a Column at a higher level.
Notice that an additional Container is duplicated immediately below the original.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8nqy4lPmNxE7c72K+9aliA4HD98a600st4bGAsdGOvrBuwpOs7ealtDXb3maVNcClK0pDk0/93Fv+HTV+wnHwuZGrZY+cxQbQn0e2i5bLqqDaioTnZfM9FhG266y7WNvxBdKvpscXg972b3B9yycBXDFOu/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5919134/3d28f936-b3e1-484f-85a9-bc809cceffcc)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5919134/5e07c11a-b567-4828-842f-391963f4df79)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61+ released June 18, 2024
Flutter version is 3.19.1
- Platform: Thinkpad L14 G2
- Browser name and version: chrome Version 126.0.6478.114 (Official Build) (64-bit)
- Operating system and version affected: Pop!_OS 22.04 LTS
```

**Comment by msusviela** [comment]
Hi @vieiraes. I was not able to replicate the issue from blank. Is it still happening to you? Does this issue don't allow you to move the textfield?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
