### ISSUE TITLE
Trying to authenticate with Firebase when creating new project fails

### ISSUE THREAD

**Issue by maxpraise** [FlutterFlow/flutterflow-issues#3205]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to create a new application. Once i click on the option to Create Project under Setup Firebase, I am taken to the Firebase Project Setting page and after entering the project name and selecting the region, tapping on the Signin with Google button loads a popup with the following error (captured in the attached screenshot): 
Error 400: redirect_uri_mismatch
Request Details: The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google. If you’re the app developer, make sure that these request details comply with Google policies.
flowName: GeneralOAuthFlow 

<img width="1496" alt="Screenshot 2024-06-23 at 1 27 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/8daae63d-0b9e-417f-aafc-b5ca94fb57e8">
<img width="597" alt="Screenshot 2024-06-23 at 1 27 52 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/a1a5cdec-1647-4e2d-b99d-cdb9de628d1f">
<img width="965" alt="Screenshot 2024-06-23 at 1 29 40 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/daac830d-59c7-4426-aa0c-e46b7ab2fb06">
<img width="978" alt="Screenshot 2024-06-23 at 1 29 47 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/540d0b8a-0233-4955-8a08-b36072e47d78">

### Expected Behavior

I expected to go through authentication through Google signin and return to complete synchronization and setup of a new Firebase project for my app.

### Steps to Reproduce

1. Create a new app and select option to add firebase
2. On project setup , select Create Project under Setup Firebase
3. On the Firebase Project Settings page, enter name of project, selection and tap on Signin with Google button
4. Popup loads with the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jOfl4otItbxa1s+NbPlVgmA5JUwnaJJEjdV7aCosfZT2BLMcec/RVERBTs+jTHxcIFqjp2oW0vD9ufOfV8IFFxWbGaZhzLtQcAmUeEaiMJCoFJWgWEBfJ/JNGWKx1Im7kRFDJvRicUZg2DmMF+i9TgvtQabEDDM4Dq/LZO4=

### Visual documentation

<img width="1496" alt="Screenshot 2024-06-23 at 1 27 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/72e5217d-2618-4d9b-8c3b-3ac25d90e41a">
<img width="636" alt="Screenshot 2024-06-23 at 1 27 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/56aa14aa-dbc1-43f0-87a2-4d21835eea25">
<img width="597" alt="Screenshot 2024-06-23 at 1 27 52 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/3b3f3989-9b0b-44f8-9b44-3e281b60e574">
<img width="965" alt="Screenshot 2024-06-23 at 1 29 40 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/695b0cb7-bca0-4b04-97b1-1d7cf4a510de">
<img width="978" alt="Screenshot 2024-06-23 at 1 29 47 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/661180/51d2438e-bcb8-4b94-9037-21c61b7f7b56">

### Environment

```markdown
- FlutterFlow version: 4.1.53 (4.1.53)
- Platform: MacOS Desktop
- Browser name and version: Chrome 125.0.6422.142 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.4.1
```

### Additional Information

This has affected automatically creating firebase project and connecting to my application

**Comment by rzambroni** [comment]
Hey @maxpraise, thanks for the report, this is actually a duplicated of: [https://github.com/FlutterFlow/flutterflow-issues/issues/2839](https://github.com/FlutterFlow/flutterflow-issues/issues/2839)

The team is already aware of the issue and is currently assigned to an engineer to be fixed. Please refer to the original ticket for updates.

As a workaround i believe you can use the web version of FF (app.flutterflow.com) to create and connect the project and then continue in desktop if you want.
