### ISSUE TITLE
WidgetTree Does Not Retain Resized State After Exiting and Returning to Edit Screen

### ISSUE THREAD

**Issue by vieiraes** [FlutterFlow/flutterflow-issues#3206]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I resize the widgetTree to the desired size, upon exiting and returning to the edit screen, the widgetTree is resized back to its normal size, not saving the previously resized state.

No attachments necessary.

### Expected Behavior

The widgetTree should retain its resized state even after exiting and returning to the edit screen, saving the previously defined state.

### Steps to Reproduce

Resize a widgetTree to the desired size.
Exit the edit screen.
Return to the edit screen.
Notice that the widgetTree has resized back to its normal size and did not retain the previous resized state.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8nqy4lPmNxE7c72K+9aliA4HD98a600sNobbxAjIoDoPJkUac/eSE5CcO3nYWw+KEWLkloBp9LrvuPfUPI4A02AbbZdwcxyaAHKRnq/aoubPKi8SnZ8M+JhFWqO0JiS2RBDOttYR1I161yIPt+RQijqJZP7Zwh9f6PHaOI=

### Visual documentation

No attachments necessary.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61+ released June 18, 2024
Flutter version is 3.19.1
- Platform: Thinkpad L14 G2
- Browser name and version: chrome Version 126.0.6478.114 (Official Build) (64-bit)
- Operating system and version affected: Pop!_OS 22.04 LTS
```

**Comment by rzambroni** [comment]
Hey @vieiraes, thanks for the feedback, this might be more of an enhancement request rather than a bug, but could you clarify what the "edit screen" you are referring to? i want to understand your feedback fully.

**Comment by vieiraes** [comment]
I mean the main screen, not a specific screen. If you adjust the size of the widgetTree, it does not stay saved if I go to another screen and then come back. About this case not being a bug, I agree. I just need to know where to open the tickets for this because in the feedback menu there is no way to track them.

**Comment by rzambroni** [comment]
Ok, got it! I'll submit the enhancement request my self. We track them internally. Closing this issue as it is meant for bugs. 

Thanks for the feedback!

**Comment by vieiraes** [comment]
What??

this is the same error as I report https://github.com/FlutterFlow/flutterflow-issues/issues/3240 and Its issue was flagged as bug.

You need to improve the issue triage process. With weak triage like this, it does not motivate me to do dedicated QA work to help everyone in the community and to increase the trust in the platform.

**Comment by rzambroni** [comment]
Nice, even better! I’m marking this one as a duplicate in favor of the other, more complete ticket. Sometimes there is a slight difference between a bug and an enhancement request, and my colleague might have used different criteria to triage the issue. However, in both cases, the issue or enhancement was going to be implemented. There is always room for improvement on both sides, I believe.

Thanks for the report.
