### ISSUE TITLE
Some content (especially ICON / CONTAINER) won't show in compiled app or test mode

### ISSUE THREAD

**Issue by polingsays** [FlutterFlow/flutterflow-issues#3207]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Some of the APP content from template or some icon / containers won't show during test mode / run mode, and the complied APP. Not as shown as the editor does.

### Expected Behavior

The output code / UI should be the same in the UI builder, and it should not DISAPPEAR.

### Steps to Reproduce

1. Create a page from template
2. Execute test mode to test, I am using AUTH PAGES TEMPLATE.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlcjfuYtij7wG+KnfLcdsqCIWM0MdXOczitVEew4bCIj4B+0iPMn4alFVXeKzaH5EBk6arFgHwtLHhtnhNuwoaA6rQNk51s9uVxPPbD6QSpTWEpDtTnBAJ5hUfxG15ImjuxJSFO9vdHga2U+YDOuRQT2Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/64358420/f688b63c-b3f1-4e78-ae6b-cd21b7d0156b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/64358420/86d6af9a-5874-4fd6-ba12-ab9a08647a0b)

### Environment

```markdown
- FlutterFlow version: v4.1.61+ released June 19, 2024 / Flutter version is 3.19.1
- Platform: Web
- Browser name and version: ARC Version 1.48.2 (51225) / Chromium Engine Version 126.0.6478.115
- Operating system and version affected: MacOS Sonoma
```

**Comment by polingsays** [comment]
IT WAS CAUSED BY ANIMATION, WHICH MEANS "**ANIMATION**" MIGHT CAUSE ERROR

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
