### ISSUE TITLE
Setting App State Default Value Not Saved

### ISSUE THREAD

**Issue by kaymasse** [FlutterFlow/flutterflow-issues#3208]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set default values for an app state variable, save it, and then open the app state again, the default value has been reverted to "unset".

### Expected Behavior

I expect the app state to keep the default values previously saved.

### Steps to Reproduce

1. Create a new FlutterFlow project
2. Create an Enum with several values (eg. _Direction_ with values _North_, _South_, _East_, _West_)
3. Create an App State variable, for eg. _DirectionList_, which is a list of Enum Type _Direction_
4. Set several default values for the list _DirectionList_
5. Press CMD+S to save project
6. Navigate elsewhere 
7. Open the default values again of _DirectionList_ to see that the default value are set back to _Unset_

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xz/Hqx89Nobhe+KrqdflvimEXOVs7bbg7ket+dwI1F4+qBOwiPeP+T3BZOMu6dFZUP2GJmm0Jp9WOktrhFMEFEByJbb47zJBqcQviJWeXbLqVBajhQEEmJ+lgG0/GzpuZkBR+IulqZXAd2V+ACefKUhfXJL2yNWo7OOWiBLrOjFKWKyXKGn0Jg1ZSfCvr

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/144909175/a42ca919-7db0-4664-a9c3-e05d5f26bbc7

### Environment

```markdown
- FlutterFlow version: v4.1.61  
- Platform: MacOS Desktop
- Browser name and version:
- Operating system and version affected: macOS Sonoma version 14.5
```

### Additional Information

I need this to set the default values in the educational application I am building.

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by kaymasse** [comment]
Tested it on my end and looks all good 👍 Thank you guys ❤️
