### ISSUE TITLE
Translations with different languages not being saved after copying

### ISSUE THREAD

**Issue by szymonpodwyszynski** [FlutterFlow/flutterflow-issues#3209]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i have more than 1 language in my FF project, put some text and manually translate to all languages and copy/paste this text, the translation is not being saved at all. Translations not saving is pretty common in more complex projects even without copy/pasting elements. Sometimes its needed to deploy an app couple of times to see if all the translated texts are saved, because in editor it shows with correct translations but in app translations are missing (editor needs CTRL + SHIFT + R many times before the translation is really saved).

### Expected Behavior

After i duplicate an element, it should be duplicated with already translated texts. If i have many languages its expected to not be a problem with saving translations on elements

### Steps to Reproduce

1. Create new app
2. Add at least 2 languages
3. Create text on page
4. Add some text with translation
5. Duplicate text
6. Refresh the page if needed (CTRL+SHIFT+R)
7. See that its not translated

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8jfz4pPxPVY0LrUb8FsgSQ7OUAja4Er0spOEC0jF7KuBqQqf8ylQBRVXumkaVNcJVairEYz+t7njvDhA8BdIRebGYBS+KVyZhb0e2i7RLK3BZasQXFQTPNjC2HF0Z6zrCJ5JutedCQt3Dv3Oue/RXLDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="227" alt="Screenshot 2024-06-24 at 14 39 05" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/95a69f18-d496-4f4d-abe5-120e9d62da80">
<img width="225" alt="Screenshot 2024-06-24 at 14 39 14" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/78327b7b-078d-4eac-96d7-194f169fd25c">

### Environment

```markdown
- FlutterFlow version: v4.1.61+
- Platform: Web (on mac version it works awfully worse)
- Browser name and version: Version 126.0.6478.63 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.4.1
```

### Additional Information

It really slowed down my workflow, because i need to deploy my app multiple times with the same translations fixed couple of times and pray to God that it works.

**Comment by rzambroni** [comment]
Hey @szymopodwyszynski, this is very likely related to a known issue the team is already working on. [https://github.com/FlutterFlow/flutterflow-issues/issues/2346](https://github.com/FlutterFlow/flutterflow-issues/issues/2346)
