### ISSUE TITLE
URGENT!!! Create[customDataType]Struct is missing a import parameter if declared as a List

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#321]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When i create two custom datatypes (cdt_a and cdt_b) and cdt_a contains a List of cdt_b as an attribute, i should be able to set them in the createCdtAStruct() Method.

## Current behavior (required)

I'm not able to set a List as an attribute in the method, only simple datatypes. 

## To Reproduce (required)

1. Create two Custom Data Types
2. One custom Data type is a attribute of the other but as a List
3. create Custom Action
4. call Method createCustomDTStruct()
5. Not able to import a List as import parameters, only simple datatypes

### Bug Report Code (required, generate from Widget Tree)

is not needed, only custom action code. 

## Context (required)

Trying to simplify the process with custom data types 

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/120254395/210821629-85a2b848-e486-426e-a8f7-cf7bf31ad075.png)
![image](https://user-images.githubusercontent.com/120254395/210821754-4bcf4e6e-9882-449c-8af7-f5ec983abeac.png)
![image](https://user-images.githubusercontent.com/120254395/210823024-22ef8f82-093c-4861-9d43-5f0dd4abe7e8.png)
![image](https://user-images.githubusercontent.com/120254395/210823097-a39590ac-88bd-454b-ae76-2043c49e4f92.png)
![image](https://user-images.githubusercontent.com/120254395/210823494-5ac962b4-2867-46fc-97d0-a217c187afb2.png)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 108.0.5359.124 (Offizieller Build) (x86_64)
* Operating system and version (desktop or mobile): MacOS Monterey 12.5.1

**Comment by bulgariamitko** [comment]
This happens sometimes I think, but can you try to delete this Action and try to create it again. Do you get the same issue?

**Comment by nicmohr25** [comment]
I have already tried to delete the action as well as the custom data type itself and create them again. Unfortunately no difference in behavior.

**Comment by mravani2** [comment]
I think that this may be related to my issue: https://github.com/FlutterFlow/flutterflow-issues/issues/326

My project didn't compile if my structure has a DataType field that has another DataType field with Lists.

**Comment by mravani2** [comment]
![image](https://user-images.githubusercontent.com/122111577/211383298-9f7d4f21-073d-42eb-9293-e2af577c6bee.png)

I have a similar problem if I try to create Dynamic Childs from a Column using conditionals + List DataType. The exact same structure works well if I use a common List field instead of a DataType.

`IT4kzOfluYtPj7xY17X5bcFKjjo4KWYiTLJEpu0bWUkbGO/4EIYidc+lXFdtZ72zaH1qJlCIjT8d/t6OjeLXIMIpCwSBR6p41aV5ElyjEA8=`

**Comment by bulgariamitko** [comment]
@mravani2 I think in your case you get a null value and that's why you get this error. Please check your data to make sure you don't return a null value

**Comment by mravani2** [comment]
> @mravani2 I think in your case you get a null value and that's why you get this error. Please check your data to make sure you don't return a null value

Nope, the support chat has checked with the Dev team, and it has been confirmed as a bug. He said they have fixed and I should see this working on the next update.

**Comment by agreaves** [comment]
Hey @mravani2, apologies for the late reply. I'm glad your second issue is resolved!

For the original issue, you cannot pass in List<Data> directly, however there is still an easy way to create the object. If you have `DataTypeA` and `DataTypeB`, and `DataTypeA` has a field `List<DataTypeB> bList`, then you can do the following:

```
final dataABuilder = createDataTypeAStruct(
 // Pass in all the other regular arguments.
).toBuilder();
dataABuilder.bList.addAll([
  // Add all of your DataTypeB objects.
]);
final dataA = dataABuilder.build();
``` 

Hope this helps! Closing the issue for now as it should be resolved.
