### ISSUE TITLE
Deleting/Updating existing enum values causes custom functions to no longer compile correctly.

### ISSUE THREAD

**Issue by wwchiang** [FlutterFlow/flutterflow-issues#3212]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After trying to update an existing enum set, all custom function code no longer compiles correctly, and always errors and prevents the project from being tested/launched.

### Expected Behavior

Changing the enums through the FlutterFlow UI should not lock my app into any state where it no longer compiles.

### Steps to Reproduce

1. Take any widget which has a custom function attached to it, and the custom function utilizes an enum (either to check a string value, deserialize a matching enum, etc)
2. Update the enum in an "unexpected" way (eg, by deleting rows, moving them around, saving blank rows, etc. Basically, not the "happy path".)
3. Attempt to compile the custom function code.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi87huI11obhJ1a6JbvpVuyQXC0M3R5Ir18pBazwbfe+uB4kqevfOTERpTcPjYHN+J2ej8GoW0snHkfD+V/U5GxCCR65d+btqbgqWcFK6Wq6IFJWgXkYmI59MIXLD0Luk2xJQWLJpWXtm3VyqBeSvcBPdNZD7CzAeDq/LZO4=

### Visual documentation

This was my enum **prior to updating**:

![Screenshot 2024-06-24 175530](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b66e67e0-0a1d-40fe-93e2-5fdc624485b2/a9acfd1b-4e03-4ee4-baee-d132cdd7292d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNjZlNjdlMC0wYTFkLTQwZmUtOTNlMi01ZmRjNjI0NDg1YjIvYTlhY2ZkMWItNGUwMy00ZWU0LWJhZWUtZDEzMmNkZDcyOTJkIiwiaWF0IjoxNzE5NTE0MzczLCJleHAiOjMzMjkwMDc0MzczfQ.PPmsWfUntisxDXbB1dqmAn9Jfve17DricEkHsDcIsG4)

And this was my enum afterwards:

![Screenshot 2024-06-24 175405](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ef8d8fe1-3253-48bc-861e-81dbf0132cd0/1cdd83cf-78eb-4252-a271-260cc4093608?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZjhkOGZlMS0zMjUzLTQ4YmMtODYxZS04MWRiZjAxMzJjZDAvMWNkZDgzY2YtNzhlYi00MjUyLWEyNzEtMjYwY2M0MDkzNjA4IiwiaWF0IjoxNzE5NTE0MzczLCJleHAiOjMzMjkwMDc0MzczfQ.zNvmGDVImVvsc3XgxyjMJChA9y3721W6jPan2V6TL7E)

When updating, I had deleted some of the existing enums in the UI using the trash can icon, before adding in new ones. Visually, nothing appeared to be wrong, but I began to run into code compilation problems.
Issue 1: **The enum which was updated was no longer able to be located in the codebase, despite being visible from the UI.**

![Screenshot 2024-06-24 175354](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2997e3a0-19ba-48bf-ad54-390bc5924096/a5fcbe70-7a91-4226-89f8-a5e84a0f27cd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yOTk3ZTNhMC0xOWJhLTQ4YmYtYWQ1NC0zOTBiYzU5MjQwOTYvYTVmY2JlNzAtN2E5MS00MjI2LTg5ZjgtYTVlODRhMGYyN2NkIiwiaWF0IjoxNzE5NTE0MzczLCJleHAiOjMzMjkwMDc0MzczfQ.NfDBqGEqKFLiRLtvpVqDDTrCB_iiqSc9RtWKmRlxAVs)

Issue 2: **Other enums were also affected, and the** `deserializeEnum` was also unable to be located.

The workaround I found was to **revert to an earlier version** where I had not altered the enums, and this time I specifically made sure not to delete any existing values. only modifying existing ones or adding new ones.

![Screenshot 2024-06-24 180139](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9b5d06cd-1144-4c55-9f74-e00b229713e5/590e394b-8dde-41cb-a32b-4437223b1f79?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YjVkMDZjZC0xMTQ0LTRjNTUtOWY3NC1lMDBiMjI5NzEzZTUvNTkwZTM5NGItOGRkZS00MWNiLWEzMmItNDQzNzIyM2IxZjc5IiwiaWF0IjoxNzE5NTE0MzczLCJleHAiOjMzMjkwMDc0MzczfQ.z0dX_6iMiys-EzK-Ee8StQ4T1haSJx9PAKQnLalCI2A)

### Environment

```markdown
- FlutterFlow version: 4.1.61+
- Platform: Windows Desktop
- Browser name and version:
- Operating system and version affected: Windows 10 Home
```

### Additional Information

*No response*

**Comment by paulperez-dev** [comment]
Hi @wwchiang! I was unable to reproduce this behavior. I also looked into your project and I couldn't see the error you are reporting. Were you able to compile the function?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
