### ISSUE TITLE
Chatpage is grey during development on Flutterflow

### ISSUE THREAD

**Issue by nachiketspoton** [FlutterFlow/flutterflow-issues#3213]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While on the flutterflow app, the chat page is grey, similar to when a value becomes null during testing. However, it works normally when the app is deployed. We need to make changes to the page, and would prefer to have the page appear normal when we are developing. Any suggestions?

### Expected Behavior

The ChatPage widget, which is an in-built widget in flutterflow, should show up during development.

### Steps to Reproduce

1. Create new page
2. Add the ChatPage widget to the page.
3. Deploy

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wls/l25RJpbwB176JdcBshiYWGDp8R+cwm9ZEQis8GpTxB4YUXvTBYk5UcNzhSmN+PGGkmmIX/MrtiuPPFcIrEzSBQNVY+cx6Sg6VQjmlbL6hEK63b0FCTZlhJ26fyJ7R2SN5CLR2V1Y42WCEC9m/SgXDGYDFO0YdA+aeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

How it is

![Screenshot from 2024-06-24 17-01-18](https://github.com/FlutterFlow/flutterflow-issues/assets/158576489/b0352066-bd96-4d10-a037-d114a209e0e1)

How it's supposed to look like:

![WhatsApp Image 2024-06-24 at 5 09 42 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/158576489/6b806ec8-9ef6-4ee1-a234-205dcaefbe30)

### Environment

```markdown
- FlutterFlow version: 4.161
- Platform: Android and Ios
- Browser name and version: Google Chrome 123.0.6312.105
- Operating system and version affected: Ubuntu 18.04.5 LTS (Also developed on Windows 10 Pro)
```

### Additional Information

Note: We suspect that this problem may have occured due to the widget having been deprecated in favour of the newer chat flows, but we thought it was odd that it stopped functioning properly so soon. If this is solvable, please help.

**Comment by rzambroni** [comment]
hey @nachiketspoton, we don't currently support any chat widget as default, is it possible that you're using a marketplace custom widget?

**Comment by nachiketspoton** [comment]
It is part of the earlier prebuilt chat flow on flutterflow.

It is not from the marketplace.

I had added it using the add new page - chat page - now it is not showing up in add new pages list. I can only see chat with bubbles or chat with threads.

Hope this clarifies

**Comment by rzambroni** [comment]
Oh yes, now i understand. The old chat page was deprecated because it was old and buggy, My advice would be to start replacing it at your earliest convenience because there will be no further fixes or improvements for the old chat page. Sorry about the inconvenience.

**Comment by ingsistempro** [comment]
Hello . I have the problem, does anyone know how to fix it?
