### ISSUE TITLE
Test and debugging unsuccessful

### ISSUE THREAD

**Issue by Neefemee** [FlutterFlow/flutterflow-issues#3214]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. I am trying to test and debug my app , but it keeps displaying an error on the home page.
<img width="956" alt="Screenshot 2024-06-23 201115" src="https://github.com/FlutterFlow/flutterflow-issues/assets/48500180/ce929178-07c7-461a-b307-1ebe141b4bb3">

2. My app is always displayed on dark mode while testing my app, and i never implemented a dark mode. 

3. All expected actions are not successful, i'm unable to successfully login into my app.
4. 

### Expected Behavior

I am expecting an exact display of my actual implementation.

### Steps to Reproduce

I don't understand.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48iMjf35ZIoeFD7r6JcflshiAsQ087U+cJk8Jtd008J5zKB+wAYvf7P1FWTLzjS2xEeE78o3wx/PfqiYbtE8EqFzeqQKpdwZFhVTzKRT67RqqnEpe7fW1QJ95XCHKO356JsyJTNthZV0YD2E+ENt7KHnfXQrLwNm0FHcibJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

[Uploading Screenshot 2024-06-23 201115.png…]()
](url)
<img width="956" alt="Screenshot 2024-06-23 201115" src="https://github.com/FlutterFlow/flutterflow-issues/assets/48500180/597a1caa-54bf-4d1a-9c84-e103199da866">
<img width="956" alt="Screenshot 2024-06-23 201115" src="https://github.com/FlutterFlow/flutterflow-issues/assets/48500180/5ba9af08-b6f1-4d25-860f-806ba19a001c">
<img width="936" alt="Screenshot 2024-06-25 094023" src="https://github.com/FlutterFlow/flutterflow-issues/assets/48500180/9cc849ff-b23e-442c-b6f5-01f740e90f1d">
<img width="885" alt="Screenshot 2024-06-25 094040" src="https://github.com/FlutterFlow/flutterflow-issues/assets/48500180/7fbf7556-8176-4d34-b15b-3cf55b6cb375">

### Environment

```markdown
- FlutterFlow version:  FlutterFlow v4.1.61+ released June 24, 2024
Flutter version is 3.19.1
- Platform: Web
- Browser name and version: 126.0.6478.114
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
Hi @Neefemee - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

If it's not reproducible from blank, I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. They can better assist you with ensuring your project is configured correctly!

Thanks!
