### ISSUE TITLE
Dependencies with version numbers including uppercase letters cannot be imported into custom code

### ISSUE THREAD

**Issue by famenft** [FlutterFlow/flutterflow-issues#3215]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently you cannot enter uppercase letters into the dependency field of Pubspec Dependencies section within custom code.

### Expected Behavior

You can enter uppercase letters into the dependency field of Pubspec Dependencies section within custom code. Version numbers should follow the semantic versioning specs which allow upper case letters (https://semver.org/spec/v2.0.0-rc.1.html)
Example: https://pub.dev/packages/ffmpeg_kit_flutter/versions/6.0.3-LTS

### Steps to Reproduce

1. Goto custom code section
2. Add new custom widget
3. Add dependency to the right under Pubspec Dependencies

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcmAvJJNoe5E17Xyb8JvmjoRMjp6a78/ke5HdCs8GZT0B4kcYs+kfklUcOGjd1FqO0yJrGYX/MrTkYbxMvAVE02eRqJlzaoJEBbyeH2jSpSoCK63b0RRINJYN0i81JjQpR15BMloWGwRwV+IO/Oufz/tH5DIPEYsR+aoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150256712/ec73769a-9faf-4ea5-932f-ab38ea8ca017)

### Environment

```markdown
- FlutterFlow version: 4.1.61+
- Platform: All
- Browser name and version: Chrome latest
- Operating system and version affected:  Windows
```

**Comment by msusviela** [comment]
Hi @famenft. I had no issue adding this dependency to a custom widget. Could you provide me with more information on how you're adding the dependency in the Pubspec dependency section so I can check that?

**Comment by famenft** [comment]
Hi @msusviela, if you copy/paste it from pub.dev it cuts off the "LTS" part, leaving you with "ffmpeg_kit_flutter 6.0.3-". If you try to enter the dependency by keyboard, as soon as you try to enter an uppercase letter, it won't take it.

**Comment by msusviela** [comment]
Try with this:<br>ffmpeg_kit_flutter: ^6.0.3<br><br>Let me know if it works for you

**Comment by famenft** [comment]
Thanks you for the quick reply, that would be an option if the android minSdkVersion would not be fixed in flutterflow, i.e. not changeable., as the proposed version requires version 24 (https://github.com/FlutterFlow/flutterflow-issues/issues/1809). Having said that, i would still consider this issues as a bug.

**Comment by msusviela** [comment]
You're right. I misunderstood the issue. I'll send it to the ENG team so they can work on this! Thanks for your report!
