### ISSUE TITLE
Timestamp relative format always displays "A moment ago"

### ISSUE THREAD

**Issue by tbelgrave** [FlutterFlow/flutterflow-issues#322]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When using relative, expected to display such messages as "An hour ago", "6 days to" or similar

## Current behavior (required)

When choosing Relative, the timestamp will only display "A moment ago"

## To Reproduce (required)

1.
2.
3.
4.

## Context (required)
As an end user experience, I'm unable to let the user know how long ago or how many days left to an event for example

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

**Comment by tbelgrave** [comment]
> 

Apologies, new to this, I've updated the original post

**Comment by bulgariamitko** [comment]
Please include the Reproducable steps and the Bug Report Code as well. those are imported in order to debug the issue.

**Comment by bulgariamitko** [comment]
I am closing this as the user was not active in the last 2 weeks, but please feel free to open it again if you still have this issue.
