### ISSUE TITLE
Color palet not working on iPad

### ISSUE THREAD

**Issue by Krysbe** [FlutterFlow/flutterflow-issues#3224]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I don’t see the color palet on iPad

### Expected Behavior

The color palet

### Steps to Reproduce

Open project on iPad
Open color palet to select a color
=> Black screen 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESk/KA/YlgottC+bn+YflAhQUkQ2I5aIIzjt4bSQgaB5T4E4kMdcjObhJuOMizaH1mGFH+sEICpt2PuOLtFcYnNS2Ac4RZ+pNyZRPPYziiR8XTPs6WSUZDHfNbJhWB056ruCN5HPJhLXAb6lyQediyZz+Cf9qOYwx5e6fDbOY=

### Visual documentation

![IMG_0670](https://github.com/FlutterFlow/flutterflow-issues/assets/47786830/881659b7-9cc6-4dd0-afdc-c41879404fb8)

### Environment

```markdown
- FlutterFlow version: 4.1.61
- Platform: iPad
- Browser name and version:
- Operating system and version affected: iOS 17.5.1
```

**Comment by rzambroni** [comment]
Hi @Krysbe, i couldn't replicate the issue you are describing, are you still experiencing it? if that is the case, I see you are also on an older version of FF for iPad, could you make sure you are on the latest and try again? The latest version is 4.1.64.

Thanks!

**Comment by Krysbe** [comment]
When I posted the bug 4.1.61 was the latest version. 

It's fixed with the .64 

Thanks 

Chris
