### ISSUE TITLE
iOS compilation failed due to wrong Dart SDK version.  

### ISSUE THREAD

**Issue by launchInsighter** [FlutterFlow/flutterflow-issues#3226]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was recompiling a previously working app on a local run for iPhone (iOS) and encountered a compilation error:  "Because snap_insighter depends on video_player_android >= 2.4.15 which requires SDK version >=3.4.0 <4.0.0, version solving failed."   I checked my pubspec.yaml and it showed 

environment:
  sdk: ">=3.0.0 <4.0.0"

What is causing the change in the compiler and what I need to do to fix this?

### Expected Behavior

It should compile just as before.

### Steps to Reproduce

1. Run my project on desktop app
2. Open local run and select iPhone 15 Pro Max
3. Observe the compilation error.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khefl4otPxMsC7qrpbcd4oCQUNW5+TLJEoetxc0gbfe/4E+0pO8z8akxWOPazaHNmJFmJpEIK+NnGjdntN8A7Hw2uUYhTzrl9FhPPYzqWSoygDqqdP0d7L8NVCECmyqavuiNDNrZ2WUVg3E6QFtiWaz6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="800" alt="Screenshot 2024-06-25 at 11 41 56 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/171405857/5e6e1469-8c23-4af9-8913-3fda68adcc16">

### Environment

```markdown
- FlutterFlow version: 4.1.61
- Platform: MacOS
- Browser name and version: 
- Operating system and version affected: macOS Sonoma 14.4.1
```

**Comment by rzambroni** [comment]
Hi @launchInsighter, sorry about that issue, it looks like it was caused by the macOS app being a bit behind. I'm marking this as a duplicate in favor of a previous ticket: [https://github.com/FlutterFlow/flutterflow-issues/issues/3225](https://github.com/FlutterFlow/flutterflow-issues/issues/3225)

Please refer to that ticket for updates.

Thanks.
