### ISSUE TITLE
Flutterflow and Github Repo not syncronizing

### ISSUE THREAD

**Issue by mikkelandersendev** [FlutterFlow/flutterflow-issues#3227]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am currently working on a project that requires customised code. As such, the project is hooked up to a Github Repo using the FlutterFlow Github feature (image attached) and followed the steps in terms of setting up the FlutterFlow Github App.

However, the branches that are created in the browser version of flutterflow cannot be seen on Github and vice versa. I have tried various ways of cloning the repo, but the issue persists. 
Futhermore, regardless of wheter I push code changes from my local branch from Github to the main branch or the flutterflow branch, no code changes occurs in the app (image attached).

Is it not meant for me to download the codebase, make changes locally, and push them back to Flutterflow? 

### Expected Behavior

I use the built-in FlutterFlow feature to create the Github repo based on the code FlutterFlow has generated.
I use Github Desktop to create a new local branch and VS Code to change some files.
I commit the changes to the branch and merge the changes with the main branch. 
The changes I made are now reflected in the FlutterFlow app, and I can see the changes in the browser (FlutterFlow.io).

### Steps to Reproduce

1. I make an app using FlutterFlow
2. Using the Pro plan, I attach a Repo using FlutterFlow built-in feautre
3. I clone the repo to my local machine
4. I use Github Desktop to create a branch based on either flutterflow or main (does not matter, I tried both, no difference)
5. (I see that the branches I create on FlutterFlow.io and the branches I create on Github are not the same.)
6. I use VS Code to make some changes. 
7. I save the files that has been changed
8. I add the changed files and commit the changes with a message.
9. I make a Pull Request to main and merge.
10. Github updates the files correctly. However, no changes occurs in my app on FlutterFlow.io

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

notTiedToASpecificWidgetButAGeneralProblem

### Visual documentation

The Repo is attached/synched to Github
<img width="774" alt="Screenshot 2024-06-25 at 12 55 19" src="https://github.com/FlutterFlow/flutterflow-issues/assets/22214398/78fceae9-0739-42ee-8709-8242b5f3cd20">

The changes I made to the file locally. This is how the file looks after merge to the main branch.
<img width="1065" alt="Screenshot 2024-06-25 at 21 00 54" src="https://github.com/FlutterFlow/flutterflow-issues/assets/22214398/4cb808c2-a2f0-4521-9ac7-0876df9d8174">

In FlutterFlow.io, this is how it looks. The changes I made are not reflected.
<img width="1451" alt="Screenshot 2024-06-25 at 21 01 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/22214398/cb9be96f-5692-47c1-9d44-16a1ce04ef9b">

These two images shows that the branches in FlutterFlow.io does not match those found on the corresponding Github repo.
Branches on Github:
<img width="897" alt="Screenshot 2024-06-26 at 11 20 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/22214398/434ec389-8423-4556-b4d4-de3eb9fa9945">

Branches on FlutterFlow.io:
<img width="1453" alt="Screenshot 2024-06-26 at 11 20 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/22214398/9dfeebd2-ddd8-45ed-b3e9-811557baf79c">

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: MacOS Laptop
- Browser name and version: Chrome 126.0.6478.62 (Official version) (arm64)
- Operating system and version affected: Sonoma Version 14.2.1 (23C71)
```

### Additional Information

I am not able to continue work on my clients' project. The complete the project, custom code must be integrated. I already made all the code and tested that it works locally on-device. Now I just need to upload it to FlutterFlow so that it can be re-tested and launched.

**Comment by rzambroni** [comment]
Hey @mikkelandersdev, unfortunately, the issue you are describing is because it is not supported by the current integration between FF<>GH, there are plans to improve it and there is already a feature request for it on the team's backlog. We hope they can get to it as soon as possible.

Thanks.
