### ISSUE TITLE
Having 2 columns Generated from Variable inside a row only show the first one

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#323]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Show the two columns as is shown when isn't generated from a variable

## Current behavior (required)

Only the first column is shown when is Generated from Variable

## To Reproduce (required)

1. Create a String List on Local State section
2. Do this widget structure

![image](https://user-images.githubusercontent.com/36147203/210935072-615cbe76-3a29-4885-a9c3-331560f61499.png)

3. In the row do the following:
![image](https://user-images.githubusercontent.com/36147203/210935143-54480d16-ee21-4171-add5-816fd24cf7fc.png)

### Bug Report Code (required, generate from Widget Tree)

ITEelcr1z4ZItbxY1ZP+asdFnQMxN0A5beRElMJuTg8jCK7tPIwpWuOnX1pBZ+Gfe21MBVejoF0yp9L2iNjpCvUnOkDDJ+AHl/E0LlSrGAc=

## Context (required)

I want to show a message list of a chat. Every row is the message and one column is for my messages and the other is for the rest. Originally that was the idea but I realized that it is necessary other another widget structure and I did another project but anyway this is a bug because it should repeat all the columns inside a row.

## Screenshots / recordings

https://schoolfy365.tinytake.com/msc/Nzc0OTgwOV8yMDc4MDQwNw

## Your environment

* Version of FlutterFlow used: 29 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by kjoyceee** [comment]
The warning that pops up tells you it will only show the first child (the first column in this case)

<img width="1322" alt="Screenshot 2023-01-05 at 11 08 41 PM" src="https://user-images.githubusercontent.com/115580022/210949367-2272e824-31cc-4306-ba49-2c94a0567357.png">

To get around this you need to Wrap your Row in a Column/Row/List

**Comment by Franco98404** [comment]
You are right! I think the warning message should be with other color because when you Generate Children from Variable look identical and as is a very common do that most times, I don't read that. So, to be more eye-catching for the user, having another color for this case would be great!

**Comment by aemelyanovff** [comment]
Closing the issue.

I agree with @Franco98404 that the warning text should be more visible, will update it.
