### ISSUE TITLE
Error in debug mode

### ISSUE THREAD

**Issue by emerson-almeida** [FlutterFlow/flutterflow-issues#3230]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

o outro erro de compilação foi resolvido. mas agora, qualquer alteração no projeto não reflete no modo de execução de teste (debug mode).

### Expected Behavior

espero que as mudanças/atualizações no construtor sejam refletidas no modo teste

### Steps to Reproduce

editando qualquer widget, essa alteração nao é compilada no modo teste.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT88lfLqy49IsctD+Krqde9ajikvJjs/a+YwluxqEAg1F73qB4l3Z8/7VEpAXsThYGxteU22gUUG086LuPKfVsInIUusRtQ4+r9XdzniWTu6MMmUPpCSVUd9GcZVG0isyKSVqyZ/NfNzWVJk7HGmDeeyQjHDH4TjPTIvRuSLC9j4nFKeKxzjAiRtwR0PHmreTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

neste exemplo, atualizei o widget TEXT.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/104561907/27d5a3b6-7cbc-4d72-96e4-2166bb59aca7)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/104561907/29907672-ba46-445c-85ef-cf836e4f99ec)

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: web
- Browser name and version: Chrome
- Operating system and version affected: windows 11
```

**Comment by msusviela** [comment]
Hi @emerson-almeida. I was not able to replicate the issue. Is this still happening to you with the latest update?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
