### ISSUE TITLE
Can't update or create enum fields in CMS

### ISSUE THREAD

**Issue by Nic61** [FlutterFlow/flutterflow-issues#3231]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I create any a new document and if I fill in an enum it doesn't work. Also modifying an existing document with filling an enum doesn't work.

### Expected Behavior

I should be able to create a new document (like it used to be not so long ago) with a field set to an enum type.

### Steps to Reproduce

1. Create a project with Firebase
2. Create an enum
3. Create a collection with some fields and a field with the enum type
4. Try to create a document and fill the enum with any of its value. It won't work.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: NA
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by Nic61** [comment]
Hi, why did it get closed? Any info?

**Comment by Nic61** [comment]
@msusviela

**Comment by msusviela** [comment]
Hi @Nic6q. It was a known issue so the team was already working on this. They marked it as a duplicate.

**Comment by Nic61** [comment]
Thank you

**Comment by Nic61** [comment]
Would you mind sharing the already open issue?

**Comment by msusviela** [comment]
Sure. [https://github.com/FlutterFlow/flutterflow-issues/issues/2546](https://github.com/FlutterFlow/flutterflow-issues/issues/2546)

**Comment by Nic61** [comment]
Thank you @msusviela . That issue talks about enum being set wrongly (which did also happen to me back in the days) but doesn't even store/ do anything. Is it still the same?

**Comment by msusviela** [comment]
Yes, the ENG team already checked for this issue and validated that it's the same. They are already working on the fix for this and the fix would be put into production when they solve it. I'll let you know if i have any update on it

**Comment by Nic61** [comment]
Thanks @msusviela it's quite urgent personally
