### ISSUE TITLE
Remote config causes test mode not working

### ISSUE THREAD

**Issue by xxTesafilmxx** [FlutterFlow/flutterflow-issues#3232]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,

I'm new to flutterflow and building my first app.

Backend is firebase.

Now I wanted to pass two parameters from firebase via remote config:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/c67490de-d5e4-452d-b15c-c9ea1e456bb5)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/08b5fb98-5bd1-4ed7-98bf-0301e6fab4e2)

As soon as I create the parameter in FF, my ap is not working anymore. The Testscreen stays almost empty, only the App-State is read in debug panel:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/f11e2a43-aa6c-4592-ba62-165fa0d84297)

In the console, a lot of errors are occuring:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/a563a8ab-14e6-4a20-8d8b-b26254705685)

### Expected Behavior

remote control working and test mode, too. 

already remmoved the underliner from the variable - issue still there.

### Steps to Reproduce

1. execute test mode - working
2. end session
3. create remote control parameter in firebase (tuseewarnung as string with default value)
4. activate in ff remote control
5. create new parameter in ff(name e.g. tuseewarnung as string, default in FF <empty>)
6. run test mode

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SkPLluJNOsbhc15SJKfpamjoUOVAjargrku1AEAk3JZjsP7AfXOmmTBNoQtekTFc3eGeguHMe+fCKk+bIN8c6FzmAf7Zi1rhiWDmVYGelVq6vC5e8X0R8GtpKCUCz1MPQoB14IulvcVYB2DulNd7JbBDXQJj4IjA/Js6JMq/+jXPuQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/bad7df43-7013-4bf3-a303-f16eb853044a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/93edb7bb-86a2-4627-a6e7-ba339cc231d3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/4ecb4031-c842-419a-b519-0ee135a4736f)

### Environment

```markdown
- FlutterFlow version: FF online V4.1.63+
- Platform: test mode 
- Browser name and version: Google chrome Version 126.0.6478.115 and ms edge
- Operating system and version affected: windows11,
```

### Additional Information

removed the underline (_) from parameter as suggested in first try to solve issue ( https://community.flutterflow.io/ask-the-community/post/remote-config-causes-test-mode-not-working-p0ndFnB1qfC5Amc?highlight=rRR4SYqrIPHVZlE )

**Comment by xxTesafilmxx** [comment]
Here the updadet parameters for testing/reproduction:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113818824/e0f9db6c-cfc6-4c62-b7ba-ad78ae3ef076)

**Comment by ignalauret** [comment]
Hey @xxTesafilmxx thanks for your report. Sadly I can get the RemoteConfig to work as expected with minimal steps from a blank project. I can suggest you to: 

* Check that the name that you are using on RemoteConfig console and FF console match. 
* Confirm that you have Published your changes on Remote config. You must click the Publish button for them to apply.
* Verify that you can show a text on your home screen with the value brought from Remote config. This way you will see if the error is on the value you are bringing, or how you are actually using it. 

I hope this helped. If you are still having troubles using your Remote Config value please let me know. Have a great day!
