### ISSUE TITLE
Bugged pubspec.yaml from FlutterFlow CLI

### ISSUE THREAD

**Issue by Coldzer0** [FlutterFlow/flutterflow-issues#3234]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The generated pubspec.yaml is bugged and can't compile it.

First, I exported the project using the Flutterflow CLI tool.

And I got this msg 

```
Resolving dependencies...
Because test_project depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.dev), version solving failed.
```

The pubspec.yaml has 

```
flutter_web_plugins: any
```

### Expected Behavior

The `flutter_web_plugins: any` should be 

```
  flutter_web_plugins:
    sdk: flutter
```

The CLI tool was working fine before the last update

### Steps to Reproduce

```
flutterflow export-code --project test-project-s36a8b --include-assets --token xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx --dest HelloWorld --no-parent-folder --fix

cd HelloWorld

flutter build web --web-renderer auto --release --suppress-analytics 
```

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grs9J1s/IdfoxnSQWC0d9UIEVi8pBZywgfZzzBLN/fPfQP1NCTcO/YFZ2f06cp14C0ajGheHpFvknHwmCRt1M1c9IVwGVcEGRb8iTF7meS3FTN+JYN3az4aaJvyZ+IvZudFpg7DuLN96vYCbUJpCwPGo4Sq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6647006/3778cab1-2609-443f-9026-1948f67f754c)

### Environment

```markdown
- FlutterFlow version: v4.1.63+ released June 26, 2024
- FlutterFlow CLI Version: 0.0.18
- Platform: Web
- Browser name and version: Version 126.0.6478.115 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro 23H2 Build 22631.3737
```

**Comment by Coldzer0** [comment]
The problem happens when I use --fix

**Comment by paulperez-dev** [comment]
Hi @Coldzer0! That dependency does not exist in the project you shared. Can you please verify?

**Comment by Coldzer0** [comment]
> Hi @Coldzer0! That dependency does not exist in the Project you shared. Can you please verify?

The Project is a new blank project I didn't modify anything I just exported the code using the CLI.

**Comment by paulperez-dev** [comment]
Hi @Coldzer0! You mentioned that the `pubspec.yaml` file has the dependency in it, right?

**Comment by Coldzer0** [comment]
> Hi @Coldzer0! You mentioned that the `pubspec.yaml` file has the dependency in it, right?

Only when dart fix is used.
I tested it on multiple projects and gives the same problem.

**Comment by paulperez-dev** [comment]
I also used --fix but I can't find that dependency. Which version of the CLI are you using?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
