### ISSUE TITLE
Missing HTML view widget

### ISSUE THREAD

**Issue by dlugi91** [FlutterFlow/flutterflow-issues#3235]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While adding new component I can't choose HTML view widget. All the views that were using it aren't working. Application stopped compiling (after recent update)

### Expected Behavior

It should show HTML view widget when searching.
Pages already using HTML view should work
Application should compile

### Steps to Reproduce

1. Create new page
2. Choose widget pallete
3. Search for HTML view 

or

1. Enter any view that has HTML view widget already used
2. Try to select anything in visual editor 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi8mB25NIrsdc0LX2dcFsgSQQNlM2a50VicpOWSsbfL74OpoMYvTsXFNWZOqzaHxEBWeGhlEx+fzVi9rhDfQ4AxGBfLk7/qoJFBPPbHGVVZCKDs+8dmpADf9XGkyO4J67oyNQB7NZcXg93zquPdy8QT6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="289" alt="Zrzut ekranu 2024-06-26 o 00 35 51" src="https://github.com/FlutterFlow/flutterflow-issues/assets/3720875/b53e4131-73e0-4cfc-a655-bb4cfd835f8c">
<img width="775" alt="Zrzut ekranu 2024-06-26 o 00 39 51" src="https://github.com/FlutterFlow/flutterflow-issues/assets/3720875/f056fad0-723e-41b2-9261-28d10d3bcb89">

### Environment

```markdown
- FlutterFlow version: 4.1.64 (released Jun 25, 2024)
- Platform: Any
- Browser name and version: Flutterflow app
- Operating system and version affected: macOS 15.0
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by dlugi91** [comment]
We have switched to WebView so it's no longer an issue for us.

**Comment by msusviela** [comment]
Hi @glugi91.

I have an update from the ENG team. Currently the HTMLView widget is being deprecated. Users should be using the webview widget in html mode instead.

**Comment by dlugi91** [comment]
That should be described in docs then, or at least in this post https://community.flutterflow.io/c/whats-new-in-flutterflow/post/what-s-new-in-flutterflow-june-25-2024-MNd3u70ipLLlMKa perhaps?

**Comment by isegal** [comment]
@FlutterFlowEng 
Please don't remove HtmlView. It is a useful feature of FlutterFlow.

HtmlView can support dynamic sizing based on its content. HtmlView is also more lightweight. For example, we display HtmlView widgets in a list of hundreds of elements without breaking a sweat.

Others have ran into issues with dynamic sizing as well:

https://community.flutterflow.io/ask-the-community/post/dynamic-webview-height-sDXL6NpzqOXlIbc
