### ISSUE TITLE
Duplicate Collection for Subcollection

### ISSUE THREAD

**Issue by eriklueth** [FlutterFlow/flutterflow-issues#3237]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to duplicate a firebase subcollection schema in flutterflow it currently duplicates the schema as a new subcollection of the current parent collection. The "Is Subcollection" toggle in the duplication menu seems not to work.

### Expected Behavior

The toggle should work and allow me to duplicate a subcollection as a new main collection or as a subcollection of a different parent collection.

### Steps to Reproduce

1. Firestore Tab
2. Create Collection and Subcollection
3. Try to duplicate the subcollection to be a normal collection

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPLqx5BPsbRA1pPpbcdsgmMRH24iTL03pu0bFEggGLbrBIYMaeLCYhNBUtPhTWNbKEWJvDsC0dbsi+LLO/ddAwqAb6Y41al6SALKbH+/aoShDKisXUYnBZlRN2mO05+zoyMmHOhtc3gc3TuHfu+vEx3YNrn7Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12431981/779ab64c-a04d-47a6-a2ac-ebcf99360c26)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12431981/0acbec76-b0e2-4f7e-8003-84a0f05cb6b5)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/12431981/bde105ee-5f11-4db4-80f3-26ce927c1e7b)

### Environment

```markdown
- FlutterFlow version: v4.1.64
- Platform: Windows
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
