### ISSUE TITLE
New Lines with API breaks

### ISSUE THREAD

**Issue by altayevrim** [FlutterFlow/flutterflow-issues#3246]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use a text field that can has multiline, the system sends the payload ends up like this.

```
{
  "order_date": "null",
  "title": "DenemeDen",
  "description": "Den
Den
Den
Den"
}
```

I fixed the issue by creating a custom function like this and clearing new lines but, well this only makes things messy and not acceptable since if I have to clear multi lines, why I should allow multi lines in the first place? You can check my project I don't know If I did anything wrong. I do not want to provide the full project ID here but it ends up with -jsy8ho.

### Expected Behavior

-

### Steps to Reproduce

-

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gk8jf/ZdPvs9d15P2du9VvCoQJWIga600sdlud0wdCoDuBIk+ZPXsXxNCZN/mTHNiPESmmnIxp9HGkYfDLvIFMkyuGpxd+JYBSQ/JXkyie5OBC7iKOkZ6Hp9VG2ai0bSvpAlQWbZqdCVk12CHNvOUbDHbQ4zrImdISq/LZO4=

### Visual documentation

https://shottr.cc/s/1ukC/SCR-20240626-pp5.png

It ends up like this https://shottr.cc/s/1mV1/SCR-20240626-ppm.png

API Name: SikayetEkle
API Variables: https://shottr.cc/s/1VlX/SCR-20240626-pqt.png
API Body: https://shottr.cc/s/1s0X/SCR-20240626-pr9.png

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.63+ released June 26, 2024
Flutter version is 3.22.2
- Platform: MacOS Sonoma Version 14.5
- Browser name and version: Chrome Version 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected:
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by altayevrim** [comment]
Thank you very much!

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue.
We are adding a setting to "Escape variables in request body". It'll be enabled by default for all new endpoints. It will be released in a couple of weeks.
