### ISSUE TITLE
New Deployed Web App Becomes Laggy, Especially During Scrolling

### ISSUE THREAD

**Issue by pavankumar5135** [FlutterFlow/flutterflow-issues#3247]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The newly deployed web app exhibits severe lag during scrolling, with noticeable stuttering and delays.

### Expected Behavior

The web app should have smooth scrolling and responsive interactions, similar to the behavior observed in the previous deployment.

### Steps to Reproduce

1. Develop and test a Flutter Flow web app with multiple screens and interactive components.
2. Deploy the app.
3. Access the newly deployed web app via a standard browser (e.g., Chrome, Firefox, Safari).
4. Navigate through the app and observe the scrolling behavior.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/167440161/f679c5ff-6201-476c-9635-999e1e4afadb)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

### Additional Information

This morning, I deployed my Flutter Flow web app, and it worked fine. However, for the newly deployed version, the app has become noticeably laggy, particularly when scrolling. The scrolling experience is jerky and slow, which was not an issue with the previous deployment.

1. The issue is specific to the new deployment; the previous version was smooth and responsive.
2. There are no console errors or warnings in the browser’s developer console.

**Comment by ignalauret** [comment]
Hey @pavankumar5135 thanks for your report. Could you provide me your deployed site URL or a project Bug Report Code so I can check what's how does this laggy scrolling behaviour looks like?

**Comment by pavankumar5135** [comment]
Hey @ignalauret,

You can view the deployed site at https://elevate-healthforce-f6h23.flutterflow.app/activityFeedPage (dev url) which was laggy

**Comment by pavankumar5135** [comment]
Also you can compare production site https://careslink.com/activityFeedPage, which was not laggy

**Comment by ignalauret** [comment]
I see, it looks like all of this elements are being rendered all the time. This could be because you are using a Column or a ListView with shrink wrap. Keep in mind that if you want to show a lot of complex elements on a list, it will require heavy computation, so to have a good performance you need to render them on demand. To achieve this, you just need to put them inside a ListView and Flutter will take care of the rest. <br>If this is not the case, please send me a Bug report code of your project so I can check out what could be causing this lag on the scroll.
