### ISSUE TITLE
Issue with the latest flutterflow update

### ISSUE THREAD

**Issue by SoLexGrowth** [FlutterFlow/flutterflow-issues#3251]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Error in most of my custom function

After the recent flutterflow update all my custom function is now having error and here is the error message ( 'FakeDocumentReference.snapshots' ('Stream<DocumentSnapshot<Object?>> Function({bool includeMetadataChanges})') isn't a valid override of 'DocumentReference.snapshots' ('Stream<DocumentSnapshot<Object?>> Function({bool includeMetadataChanges, ListenSource source})').

And this occurred in many of my simple custom function 

### Expected Behavior

To have no errors

### Steps to Reproduce

1.create a new project 
2. Add a custom function that that return anything such as if text is 0 return 1
3. Save the code and check for error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekM/l25J2n7wC0bX2YccxqwMwGkQ5a7sviu5+FBQaI+LnELATP8z8UBZCcuqHewpMf06ZjmAD0N3GhobfEfUqHzCsGL5jyJZbUxDgYECRRpCPCZaOfnJSRPFTIUiY15233BNROvt0Wk4Q62Gbfuu+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

![IMG-20240627-WA0001](https://github.com/FlutterFlow/flutterflow-issues/assets/156712790/d7e4817c-2d15-48f3-8b66-12c9681a1780)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

Please help me check this issue it's affecting all my flutterflow project

**Comment by SoLexGrowth** [comment]
Found a solution

**Comment by sanjeevbishnoi** [comment]
@SoLexGrowth  Please share  the solution, we are facing the same with custom code

**Comment by SoLexGrowth** [comment]
@sanjeevbishnoi  you have to clear your browser cookies, cache on windows... Delete all and login back to flutterflow
