### ISSUE TITLE
FlutterFlow's Desktop Application is crashing, hindering the development

### ISSUE THREAD

**Issue by ESG-Global-Partners** [FlutterFlow/flutterflow-issues#3253]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have the latest version of desktop app and it is crashing after 10-12 seconds of opening the project. It has hindered my development process, flutter webapp can't handle big project. Please rectify

### Expected Behavior

It should not crash

### Steps to Reproduce

Open the FlutterFlow Desktop App
Open the first project
Once we start working on the project within 10-12 sec desktop app is crashing

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

xasas

### Visual documentation

dfsdfsd

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi, thanks for the report, it would be nice to know a few more details:

* What desktop version are you using? MacOS? Windows?
* Does it happen when opening a specific project or with every project?
* Is the OS showing any errors or logs after the crash?

Thanks.

**Comment by charliefabley** [comment]
I am currently unable to get into flutterflow desktop Windows at all. just keeps spinning

**Comment by rzambroni** [comment]
Hi,

Sorry for the delayed response. Are you still experiencing issues with the Windows app? We are currently unable to replicate the problem and might need more information to assist you further.

Could you please let us know if the OS shows any errors or logs after the crash?

Thanks!
