### ISSUE TITLE
Google OAuth doesn't work for firebase configuration on desktop 

### ISSUE THREAD

**Issue by lequentz** [FlutterFlow/flutterflow-issues#3254]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I start a new project then immediately jump to Firebase admin menu to create firebase project. 
The Google Oauth windows show error message : Error 400 redirect_uri_mismatch 

### Expected Behavior

Just auth me with google

### Steps to Reproduce

1. Create a new FF project (on desktop version)
2. go to firebase
3. click on create project
4. click on google signin 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lPHlx4lPmNdc7q6JccAxgiAWQls7a5IK18FTRUo8KOvLBIYuP/WkN1huXde9S1VqPESmmkcD/97Tj/zMG8EDAyqZGIBfzLpMdAv/VnmgQZOBEbuSYURfBedQG2bD3J6JrgolCONqLEY/62WEH+7JczDZGOPzImdISq/LZO4=

### Visual documentation

<img width="1670" alt="Capture d’écran 2024-06-27 à 11 02 34" src="https://github.com/FlutterFlow/flutterflow-issues/assets/50026344/03c52564-aff9-4bcd-948a-85fa6939c512">

### Environment

```markdown
- FlutterFlow version: 4.1.64
- Platform: Desktop
- Browser name and version: Desktop version
- Operating system and version affected: MacOS
```

**Comment by rzambroni** [comment]
Hey @lequentz, thanks for the report, we are aware of the issue and it is already on the backlog for the team to fix. I'm closing this issue as duplicated of the original one. [https://github.com/FlutterFlow/flutterflow-issues/issues/2839](https://github.com/FlutterFlow/flutterflow-issues/issues/2839)

You can use the web version to workaround the issue and then continue to work on desktop normally.

Thanks.
