### ISSUE TITLE
DatePicker Date Pulling Current Date and Not Selected Date

### ISSUE THREAD

**Issue by pietertpt** [FlutterFlow/flutterflow-issues#3255]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the Date and Time Picker from FlutterFlow it keeps getting the current date when displaying in a textfield or using it for a backend API call, even when a text field shows the selected date as per the FlutterFlow documentation.

It looks like when the API or what ever calls the widget state for the date picked, it pulls the current system time, event if different or initial date is selected.

In the picture and the video can be seen how the date changes, from the displayed date of the date picker versus get the date at the time later for API call.

### Expected Behavior

That the date we selected, can be pulled and sent with the API call to our backend system at any point of time, that the date picker maintains the date required.

### Steps to Reproduce

Building:
1. Create a button with the DatePicker action
2. Set up API call to get the date selected from the DatePicker

Usage:
1. Select a required date
2 Make the API call, see that current date being pulled in instead of the selected date.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozsnf5c92osgE+b6JccBKjSQRH0wiU4IO08pOGDsdF4iuPOxzaeDSRBJWOPLhd1FPKEWLgkYDpPTsjeP1CvADNQirGd1fzqV+TQviXju/aoTXO7uSQ2t5LJlQGECk5LbZkRJCCNB2Wmw86jiyIOvKEyzdQZ/7Zwh9f6PHaOI=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/20624392/57b86590-0fbe-4719-aabc-c8a23b313c65

![Screenshot 2024-06-27 at 10 58 47](https://github.com/FlutterFlow/flutterflow-issues/assets/20624392/b1c11c95-010e-4c9a-9ca8-b27bc542a2ac)

### Environment

```markdown
- FlutterFlow version: v4.1.63+ released 25 June 2024, Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome 126.0.6478.126
- Operating system and version affected: macOS Sonoma 14.5, M1 Pro
```

### Additional Information

We are try to build a app and seeing what the advantages are of switching to FlutterFlow. All the bugs and issues we have with lack date functionality is hindering us a lot. This has caused a delay of more than 2 weeks on our project in figuring out work arounds for things not working.

**Comment by ignalauret** [comment]
Hey @piertertpt thanks for your report. I just created a project with a date picker that saves the value to a state variable and I can see the date being saved correctly. <br>I'm not getting why you are talking about "Set up API call to get the date selected from the DatePicker". Could you explain to me where are you storing the selected date to later send on the API call you are doing? <br>If it's easier for you, you can also create a blank project and implement your date picker so I can see what are you trying to do here. <br>Thanks, have a great day!
