### ISSUE TITLE
custom widget web view fails to work

### ISSUE THREAD

**Issue by cyberlion-ops** [FlutterFlow/flutterflow-issues#3257]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i made a custom widget web view where it accepts a parameter for a url to execute. when compiling it throws an unknown error.
i managed to compile the code without the unknown error by hardcoding the url. but when testing the custom web view widget it shows the red error page. I have copied and tested multiple other codes of other people and it presented the same errors as my code.

### Expected Behavior

the web view to function and display a web view of the passed url.

### Steps to Reproduce

1. create a custom widget.
2. make a web view widget.
3. pass the url through a parameter.
4. will encounter an unknown error when compiling.
5. remove url parameter and hard code a url.
6. compile and run the custom widget you will encounter red error page.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEek8rl24V1j70F1brbK+5V9AMwGkQ5a7sviu5+FBQaI+P1E4l+PsjOYlFCcuqHdG5qKFCaoEQy/+jtjdjpKPU4HxOZGaJc+YdpUxDjTmW7RbqnBpaodXdSEftnCFy058KFrghQWdJYSmxiw2CQH+iAb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-06-26 192811](https://github.com/FlutterFlow/flutterflow-issues/assets/174012416/e467428d-c1ee-44db-89ce-66e26d350c95)
![Screenshot 2024-06-26 192914](https://github.com/FlutterFlow/flutterflow-issues/assets/174012416/86e4fd6c-6684-4477-a0d0-9a6f211ecea4)
![Screenshot 2024-06-26 193242](https://github.com/FlutterFlow/flutterflow-issues/assets/174012416/409f9d77-1dbd-4f29-b696-a4c280974e9a)

### Environment

```markdown
- FlutterFlow version: v4.1.64+
- Platform: windows Desktop, web
- Browser name and version:chrome  126.0.6478.63
- Operating system and version affected: windows 11  23H2
```

### Additional Information

display a web view in order to register a user into a website

**Comment by ignalauret** [comment]
Hey @cyberlion-ops thanks for your report. I see that you are trying to use this package [https://pub.dev/packages/flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)<br>Keep in mind that this package has configuration that must be done for it to work, for example "To make it work properly on the Web platform, you need to add the `web_support.js` file inside the `<head>` of your `web/index.html` file:"<br>Sadly I can't help you here to configure the package, but please feel free to contact our Customer Support so they can help you configuring this. <br>Have a great day!
