### ISSUE TITLE
StaggeredView: Prevents scrolling and blinks constantly

### ISSUE THREAD

**Issue by mravani2** [FlutterFlow/flutterflow-issues#326]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

1) I should be able to scroll touching anywhere on the screen;
2) As the StaggeredView is loading a single-time query, it should just load once and then wait for an action or change to reload;

## Current behavior (required)

1) If I touch the title or anywhere outside the StaggeredView I'm able to scroll. If I touch anywhere inside the StaggeredView, I can't scroll;
2) The StaggeredView keeps loading and crazily blinking every time, even if I just touch around him.

## To Reproduce (required)

To reproduce:

1. Click the tab Orders
![image](https://user-images.githubusercontent.com/122111577/211056844-11e1c8ab-58f2-4055-a8a7-e0ef4010f807.png)

2. Click the Order 00000002
![image](https://user-images.githubusercontent.com/122111577/211057036-774f6dc3-8e01-45e3-8145-6216744d1e26.png)

3. Try to scroll (using the click to simulate the touch if you're not testing on a mobile device)

### Bug Report Code (required, generate from Widget Tree)

`IT4kzOfluYtPj7xY17X5bcFKjjo4KWYiTL0ntutuZxYjfYznBIkUWMzBUBFUOfXiT39mP1mKgjkX/MmLifPDCe4oNkiYbKU5zLtQVQrgczu7RYyMDqzlMS0ffaMKRSz+`

## Context (required)

I'm just trying to show a list of items inside a StaggeredView and scroll through it. Important to say that I wasn't facing any of these problems while using other widgets like ListView or Wrap

## Screenshots / recordings

Original project link: https://app.flutterflow.io/project/w-m-s-app-lpc1yf
Video example: https://flutterflow.intercom-attachments-8.com/i/o/646744493/7476bd5e5b2a7aad8bb76a65/screencast-docs.google.com-2023.01.05-11_54_31.webm?expires=1673022553&signature=9bcf46429d589e0e813456ac6d78cb192c5a63c2058ca2b3aae4477e461c9fb3

I have also created a new and simple project just to simulate the scrolling issue:
Test project Link: https://app.flutterflow.io/project/teststaggeredview-cwhyie
Video example: https://flutterflow.intercom-attachments-8.com/i/o/647499593/70b1a614aee59bbe5c775c2c/screencast-docs.google.com-2023.01.06-12_57_06.webm?expires=1673024312&signature=d2f70a23efbe3fd589758cc38df219fb94fd4e323222bf104d3b45bd49c79a5b

## Your environment

* Version of FlutterFlow used: 
![image](https://user-images.githubusercontent.com/122111577/211058148-a1b20ddf-f86a-4ad8-a52e-ce2c20c0af1d.png)

* Platform (e.g. Web, MacOS Desktop): 
Web

* Browser name and version: 
![image](https://user-images.githubusercontent.com/122111577/211058267-409ef882-33af-4397-8a87-180cf9b6907e.png)

* Operating system and version (desktop or mobile):
Desktop, Windows 11

**Comment by victoriahuang1** [comment]
Hi @mravani2 thanks for the report. I have been able to reproduce the scrolling issue but not the blinking one.
Could you upload the videos to github (as opposed to links), as the links aren't working for me.

If you also have a simple test project to demonstrate the blinking issue, or instructions on how to reproduce the issue using your project, that also be very helpful.

**Comment by hariprasadms** [comment]
@mravani2 - Thanks for posting this issue. 
Considering the age of the issue and no response for @victoriahuang1's earlier message, looks like this issue has been fixed in latest updates and working fine for you. Hence, we will close the issue. 

Let us know if you still seeing the same behaviour, we can re-open the issue and start investigating, Thanks
