### ISSUE TITLE
Project Fail to Build despite no bug recorded

### ISSUE THREAD

**Issue by futurefluxes** [FlutterFlow/flutterflow-issues#3260]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For the past three days, my FlutterFlow project failed to build despite there being no bug. I have tried all means but it is still not building and there was no specific error message to indicate where the problem originated. Here is an image of the error message I have been receiving each time I run the project.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/168538673/1259d3de-b2d1-4871-b883-e7974ebd9264)
being

### Expected Behavior

When I run the project I expect it to run since there is no error message in the development environment

### Steps to Reproduce

1. Added a scroll to logic on the landing page
2. Make the landing page text selectable
3. Run the project and
4. Observed that the project doesn't build

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l+fqxIt1pbwA+Kr+c/pVnjwXKWE7becnj8FTSQo8J5zKB+wAYvf7P1FWTL3gd1Z6J1qaij801vfqkuPtGPJcPTCbbYBNyZBUFwqXeD6uV66UCJGVfW1fI+BRChW9552JuhEnIutpWmQN22GYeu/LQhXUQ6X4IXoRFsmLJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/168538673/feb09fa1-6a2d-4ccc-b325-9b2f9f53d2d3)

### Environment

```markdown
- FlutterFlow version: v4.1.64+, (released June 27, 2023) 
- Platform: web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 11
```

### Additional Information

nill

**Comment by ValetCEO** [comment]
Have you got a webview in your project?

**Comment by futurefluxes** [comment]
@ValetCEO Yes, I have a webview, could it be the cause?

**Comment by ValetCEO** [comment]
> @ValetCEO Yes, I have a webview, could it be the cause?

Yes, it's causing issues with mine too and it's reproducible with a blank project with just a webview in it. Struggling to get hold of anyone at Flutterflow to discuss tho.

![365d231a-8b24-4c16-90c3-070cc2752b19](https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/55af77ea-5f66-46dc-8f1e-c78bb620cecd)

**Comment by futurefluxes** [comment]
Thank you @ValetCEO I will remove the webview page and run it to see if it takes care of the issue.

**Comment by ValetCEO** [comment]
Let me know if that fixes it

**Comment by futurefluxes** [comment]
Ok, i will get back as soon as possible

**Comment by futurefluxes** [comment]
Still did not work after removing the webview
Here is the error message I got
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/168538673/dd5b3015-f3c9-4b5c-a249-de6837f09708)

**Comment by rzambroni** [comment]
Hello @futurefluxes, this might be related to the version upgrade of  flutter to 3.22.2 on the latest Flutterflow release. Some of the dependencies in your custom code might need to be fixed to be compatible.<br><br>We had quite a few reports with the same problems: <br><br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3244](https://github.com/FlutterFlow/flutterflow-issues/issues/3244)<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3229](https://github.com/FlutterFlow/flutterflow-issues/issues/3229)
