### ISSUE TITLE
[URGENT TOO] Crazy Incremental Decremental and Math Behvior started after tuesday June 25.

### ISSUE THREAD

**Issue by Toninomex** [FlutterFlow/flutterflow-issues#3266]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My logic is not working stable. In a collection I obtain the expected behavior while in other collections, exactly the same logic, has erratic behavior.

### Expected Behavior

I am incrementing a 0.5 value if a boolean is true, using conditional expression, and incrementing 1 in other variables. While in the collection called "areas" the logic is working fine, in users, or projects collection is erratic. Sometimes I am receiving twice the value, other times I receive three times de value, and the same happens when I want to decrement values.

### Steps to Reproduce

1.  Query to find the collection I want to increment 1 or fixed value from a conditional
2. Update document based on the Query
3.  Choose variables to increment 1
4.  Choose variables to increment from conditional values that come from a widget (boolean)
5. That´s it!
---
And the same happens when I want to decrement buy using uncheck box in a TabBar. Area´s works fine, other collection don´t.

It does work fine on Area Collection that was programed before June 25, and then after June 25,  User Collection (or other collection) that increments crazy values.

Here is a loom video showing the whole sequence 

https://www.loom.com/share/df068b2121e943e8b929769a440a5ae2?sid=2ce58b95-a69b-47f0-b379-6e7fc5d2e7cc

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kleflsJNgocNG15P5bflKpCc7Q1AnTL07ttYbZxUjIuPtBJh/Oc/OZVtoXcyodGlhHGH9kl8FpqmKk/z9EO07MkmYQLpd+Kt+dgnNWXq8RaqaCZOCX3FSI+FXC0in3KWR3SR/OulfLyEG3Du6fuzLaArrJ5O/Zwh9f6PHaOI=        ////   (this is from the o014UpDateCoe page) //// and from the  (o011Calendar page is this) -> /////   IT4kleflsJNgocNG15P5bflKpCc7Q1AnTL07ttYbZxUjIuPtBJh/f/f4YlJtTdO9d1NhHGKgik4f3NGKj/LXUfEoJkibfLpcyKVUVAviJHq8RaqaCZOCX3FSI+FXC0in3KWR3SR/OulfLyEG3Du6fuzLaArrJ5O/Zwh9f6PHaOI=

### Visual documentation

https://www.loom.com/share/df068b2121e943e8b929769a440a5ae2?sid=2ce58b95-a69b-47f0-b379-6e7fc5d2e7cc

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: MacIOS
- Browser name and version: Chrome /Safari
- Operating system and version affected:  IOS / version of the app 21 (believe)
```

### Additional Information

I don´t get it why is working fine in one collection and why not in others.

Extra:
After you implement the Debug Panel, my App (copy to clipboard) functions stopped working on Chrome... they do work on Safari

**Comment by paulperez-dev** [comment]
Hi @Toninomex! From your video, I noticed that the values on the user collection are being updated more than once at the same moment (A value goes from 5 to 4 and then to 3 in less than a second). The problem may not be in the logic but in the event trigger. Please verify how you call those actions (rebuilding the page is sometimes the root of this behavior).

I'm going to close this issue.

**Comment by Toninomex** [comment]
Hi Paul, can you help me a little bit more please before closing the issue? Please consider I am not a programmer.
I am calling the through:

1.  Query Collection/ simple document...  
2. And then Updating the data on that collection.

Let me check how is behaving the "rebuilding" and come back to you.

If I make another query call to another collection, following exactly the same steps as the Areas Collection (working fine), it happens the same problem...  I guess that if the problem was on my side I would have erratic behaviors on all the collections, but instead, the first one I did (areas) is working fine, and the rest are not (I deleted two collections to focus only on two, instead of four) but happens the same with those I deleted.

And finally, it doesn´t always follow the same behavior. Sometimes it changes after unchecking the box on the calendar page, and other times since I made the first update... it's crazy. As a collaborator of FF you are able to go inside the project right?

**Comment by Toninomex** [comment]
So in the photograph you can see that the only action with a rebuild option is the Update AppState that I believe doesn´t has to do with the problem.  Farther than that I need your because then I am no understanding your advise.


<img width="1370" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/54413435/e5cdece5-a5e3-40a0-a142-1ec63bdc4e6e">

**Comment by Toninomex** [comment]
The rest of the actions has no "rebuild pages" option.

**Comment by Toninomex** [comment]
This is the button I am using. There are no querys involve, and the rest of the actions have to deal with calling components rather than updating the users collection. 

I don´t have a clue about why this is happening. And as you can see in the video, when I try to decrement it follows the same problem.

<img width="455" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/54413435/05e499fc-7198-420b-b4a9-119eaa16d1b5">

**Comment by Toninomex** [comment]
Hola Paul

I answer you at GitHub. Please we please don´t close the issue until we are sure what is causing the problem?

Can you help me a little bit more to understand what you are trying to say?

**Comment by Toninomex** [comment]
PD...
I keep working and FF has really a problem.  At this time I am asking to drecrement 1 (solid number) on the task and the value is ignored when is the only variable that is has to be decrement, but when are other values, it does rest 1.

**Comment by Toninomex** [comment]
Paul I recorded a new video using a function to obtain values but is not working either. I will try to add the Incremental function to the function but however I think this must be addressed as a bug

https://www.loom.com/share/403227069e6e4ad9a440e34a58a7ab53?sid=2fbeab9e-0727-4d6f-a904-7622212c8d6c

**Comment by Toninomex** [comment]
Paul I recorded a new video using a function to obtain values but is not working either. I will try to add the Incremental function to the function but however I think this must be addressed as a bug

https://www.loom.com/share/403227069e6e4ad9a440e34a58a7ab53?sid=2fbeab9e-0727-4d6f-a904-7622212c8d6c

**Comment by Toninomex** [comment]
Last Status
The bug is on the incremental and decremental function of FF. 
I made a custom function and it works fin (so far).

**Comment by paulperez-dev** [comment]
Hi @Toninomex! So sorry but I can't help you here. Please reach out to the [community ](https://community.flutterflow.io/ask-the-community)for assistance.
