### ISSUE TITLE
Colors not updated in Windows FlutterFlow App

### ISSUE THREAD

**Issue by Xeladrane91** [FlutterFlow/flutterflow-issues#3267]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Today, I updated colors (theme setting) throught the web. Tonight, I go in the Windows app but colors are not updated in the settings. 

### Expected Behavior

Updated colors in the Windows application.

### Steps to Reproduce

1. Update colors on the web
2. Open Flutter Flow Windows App and go to the theme settings 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkvLluI9OvuFK+KricPpagic4M0MCXLhE0dcbFBAjIZz2OqQieur+VFpCOvGVd1A3fVK0pGIzwNLKktrhFsInFzmBUoNozahQSBbybD6hb4iRDs+WRHd5Ed9jCnKs38G73RMlJft1L04Dw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67551039/60188ff7-6148-4a6c-b3a3-9b4bed0f3c61)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67551039/c42c1adc-4915-40d4-a0f4-cca71e722f93)

### Environment

```markdown
- FlutterFlow version: v4.1.63+ web and v4.1.64 (windows)
- Platform: web and windows app 
- Browser name and version: chrome 126.0.6478.127
- Operating system and version affected: Windows 11 and Windows 10
```

**Comment by rzambroni** [comment]
Hey @Xeladrane91, thanks for the report, i was trying to replicate the issue you are describing, but so far I have not been able to do so, is the issue persisting?

**Comment by Xeladrane91** [comment]
Hey @rzambroni, I did a new test, now it works but I have to restart the app to update colors (maybe close project). It is fine for me. Have a good day
