### ISSUE TITLE
Branching Permissions erasing the permission 

### ISSUE THREAD

**Issue by leoweebt** [FlutterFlow/flutterflow-issues#3268]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I click to change the permission of one person it works, but when I chose the second, the first one disappears and then nothing else works in the branching permission. 

https://github.com/FlutterFlow/flutterflow-issues/assets/159651220/ec6c4105-e373-4e17-a609-c6f9926d697f

### Expected Behavior

I should be able to choose who can have permissions.

### Steps to Reproduce

1. Create project
2. Add team members
3. Disable "grant all users full access" in Collaboration settings
4. Click to change the permission of "can merge into main"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzPHl3It1n7wA+KrUbexF9GIWI0McX5Ir1utsewgjGKL1BqQcYsjCUBZoXeG4aVNfMWaIjT8zzPuNjvzDL8cnPUiBbYRh/qt+dQn0e2iib6aDEc2dPnB6M+xQIWnH5qevvyJAIbdpc14d7Vy2OPO/HwjDFOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159651220/1e12cffc-f9a1-4d33-be26-de89948db7ad

### Environment

```markdown
- FlutterFlow version: 4.1.63
- Platform: Web
- Browser name and version: Chrome 126
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
