### ISSUE TITLE
Flutterflow Build Failed Package Info Plus 4.2.0

### ISSUE THREAD

**Issue by cadufreeela** [FlutterFlow/flutterflow-issues#3271]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Build failed message when trying to run in TEST or RUN mode.

Check the following Custom dependecies: package_info_plus ^4.2.0

Because wakelock_plus >=1.2.4 <1.2.5 depends on package_info_plus >=6.0.0 <8.0.0 and wakelock_plus >=1.2.2 <1.2.4 depends on package_info_plus ^6.0.0, wakelock_plus >=1.2.2 <1.2.5 requires package_info_plus >=6.0.0 <8.0.0.
And because wakelock_plus >=1.2.5 depends on package_info_plus >=6.0.0 <9.0.0 and chewie >=1.8.1 depends on wakelock_plus ^1.2.2, chewie >=1.8.1 requires package_info_plus >=6.0.0 <9.0.0.
So, because freeela depends on both chewie 1.8.1 and package_info_plus ^4.2.0, version solving failed.

### Expected Behavior

App should build and be able to run in test mode

### Steps to Reproduce

1. Create new page
2. Add a custom function that uses the following libraries:

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/flutter_flow/custom_functions.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';

3. Once function is ready, this is the issue I am receiving:

Target of URI doesn't exist: 'package:cloud_firestore/cloud_firestore.dart'.

this is happening to all functions that requires the above dependencies

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksjf35N2ofVY+Krcc8ZsoCAXCUMfWLsr0utuGA0hNYzvP5l3ZvfSUFdLYtemfFFMEE2gqzkd+PTUkYbtCPUrPROWUYRBwq5XQRfhe3OWMKnWEZO8fkBQEdFXfxXC07unviUmHNVodXwZwE6qCvCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/163602905/eb6f4fe2-aef3-4e0f-8d94-3c8a4a2a81ff)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/163602905/281131ba-2ff6-4a90-a537-d86a6fc3af4d)

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: Web
- Browser name and version:Version 126.0.6478.116 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

### Additional Information

No changes have been done to any widgets, all my custom functions that require dependencies are showing the same URI error

**Comment by rzambroni** [comment]
Hello, your custom code dependencies might need to be fixed as the error message suggests. 

The latest version of FlutterFlow upgraded the flutter version to v3.22.2 so it is expected for projects with custom code and imported dependencies.

[Here](https://www.youtube.com/watch?v=8Y1uyCC_dXE) is a quick video that might come in handy.

Thanks!

**Comment by cadufreeela** [comment]
Hello,

thanks for the prompt response, this issue was not happening 3 days ago,
and now all my custom functions are having the same issue: As you can see
below the imported dependencies here are from you such as
package:flutter/material.dart

How can I resolve this across the many functions I have, now I am stuck and
cannot test any changes?

Also there is the issue stated at Buidl Failed screen:
[image: image.png]


mport 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/flutter_flow/custom_functions.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';
