### ISSUE TITLE
Unable to Create App State with Data Type Document Reference in Version 4.1.63

### ISSUE THREAD

**Issue by Miyotch** [FlutterFlow/flutterflow-issues#3272]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since upgrading to Version 4.1.63, it has become impossible to create an App State with the Data type Document reference. The "Create" button is grayed out and cannot be clicked.
As far as I have verified, this issue is occurring for multiple users and on different PCs.

The issue was not present in Version 4.1.61.

### Expected Behavior

Users are able to create  an App State with the Data type Document reference. 

### Steps to Reproduce

1. Open the App State view.
2. Create  an App State with the Data type Document reference. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjMmA7Y9On7wA7qX2Ke9ajWMWHGIjapc0sNtuTQIdCYDuBIYiaeLSSxdDTeLhYwlfKEWGrHo10/DGi+LIGMJdaAicGqJY1KpyWgzdXlm/aoS6EqmdOXdAJJtXGFS43MKkkQpSXbFhL0IG2U2yPd6AbBTcJI/6Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/171346424/6d99ce8e-f609-41d0-b8df-2538d4a9b055)

### Environment

```markdown
- FlutterFlow version: 4.1.63
- Platform: Web
- Browser name and version: Chrome126
- Operating system and version affected: Windows11
```

**Comment by msusviela** [comment]
Hi @Miyotch. Thanks for filling in. This is a known issue and the ENG team already worked on a fix for this, that's why I'm closing this issue. The fix should be up for next update.
