### ISSUE TITLE
 Missing Rebase Option in Branch Management

### ISSUE THREAD

**Issue by mubarismubi** [FlutterFlow/flutterflow-issues#3273]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm experiencing an issue where the "Rebase" option is missing in the branch management section , although the "Merge" options are available. Any insights or solutions to resolve this would be greatly appreciated.

### Expected Behavior

In the branch management section of FlutterFlow, "Rebase" options should be available. The rebase option should be accessible alongside the merge options to ensure flexible and efficient branch management.

### Steps to Reproduce

1. go to test branch 
2.try to rebase
3. check if there is rebase option

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40q/qC4bp/nf5K1s2IYfFFqCknHFAdWpM3rNVRaCgofePtOol3evWkS1hWZNCoSlZ5MESmmj8EwdLvuOHpDPY3PS6rc4h6/6pqUzzwYGCnUZOBBbi0S2pAO+dYCkyf5KbZ2RElWLJfR0Y5606UNeeXSnLvJLrWImdISq/LZO4=

### Visual documentation

![Screenshot (141)](https://github.com/FlutterFlow/flutterflow-issues/assets/75472223/dc62820c-2660-45ea-979e-13a96d04fbe5)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @mubarismubi. Thanks for filling in!<br><br>This feature was replaced with the ability to merge main into your branch, which accomplishes the same thing.<br><br>Let me know if you have any questions!
