### ISSUE TITLE
Document reference app state variable can't be created on web app

### ISSUE THREAD

**Issue by MomentumAppsLLC** [FlutterFlow/flutterflow-issues#3275]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to create an app state variable of document reference type, the create button is disabled on FF web app. Works fine on the desktop app.

### Expected Behavior

Variable should be created with no issues.

### Steps to Reproduce

1. Open FF on web
2. Go to app state variable tab
3. Create new app state variable
4. Enter name
5. Select 'Document Reference' type
6. Select collection
7. Create button will be disabled

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Visual documentation

<img width="444" alt="Screenshot 2024-06-28 at 12 46 33 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/162045588/f58824f7-1454-40cb-af00-c331b2b96058">

### Environment

```markdown
- FlutterFlow version: v4.1.63+ 
- Platform: Web
- Browser name and version: Arc Version 1.44.3 (50502)
- Operating system and version affected: MacOS
```

**Comment by msusviela** [comment]
Hi @MomentumAppsLLC. Thanks for filling in. This is a known issue and the ENG team has already worked on a fix for this, that's why I'm closing this issue. The fix should be up for the next update.

**Comment by MomentumAppsLLC** [comment]
Thanks FF team! 🙏
