### ISSUE TITLE
FlutterFlow CLI has no method to determine if newer code is available

### ISSUE THREAD

**Issue by sbarber-dsi** [FlutterFlow/flutterflow-issues#3277]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have a build pipeline that pulls the UX code from FlutterFlow and right now the only way we can tell if there is newer code that needs to be built is if we pull it and compare code trees.
This is excessive for both our efforts to build our entire project and load on FlutterFlow servers.

### Expected Behavior

Some CLI interface that users can call, e.g. flutterflow check-rev --project <SLUG>, that returns anything usable to fingerprint the code would be great (e.g. a git hash or an auto-incrementing revision #).

Please take care to ensure it can be done atomically meaning somehow the export-code command must provide the same hash/rev as this envisioned check-rev command so we can compare what we have to what is available. e.g. include it in a .hash or .rev file or some such thing.

We could provide the last has/rev to the export-code command and it could elide the export if the hash/rev matches.

### Steps to Reproduce

Either a
`flutterflow get-rev --project <SLUG> --hash`
command or something integrated into the export-code command
`flutterflow export-code --project <SLUG> --existing_hash $(cat <PROJDIR>/.revision)`
`flutterflow export-code --project <SLUG> --skip_if_not_newer`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlPLq25dPxc9c7qrpbcJR/Sc5Jls7aqxMkMFhcwE3C7HNG7UIec/4VEptXbC+TVc3IWH8/X8d0P/FhebIN+4qIS+VR5xj1c5QZxbLZHOVbIy4CbjtOnxPNNpKC2qb56aw2yUnWPtiZUYB612Qft/IbDfcNOfqDTIBRv3+IqX+s3PuQ0SLb3kNh1JWeC/v

### Visual documentation

flutterflow
-t, --token    API Token
-h, --help     Help
Available commands: export-code, deploy-firebase.

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: Linux
- Browser name and version: Any
- Operating system and version affected: Linux
```

### Additional Information

Missing feature causes excessive pulls of the code from FlutterFlow

**Comment by Alezanello** [comment]
Hey @sbarber-dsi  !

This tracker is only used for reproducible bugs, so I am closing this issue. 

I've added this as a feature request in our internal backlog and we will get to it as soon as possible. 

Thanks for your feedback!
