### ISSUE TITLE
Code Analyzer stop working

### ISSUE THREAD

**Issue by TidoGarnier** [FlutterFlow/flutterflow-issues#3282]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The code analyzer is a program that performs critique during code construction. It identifies errors by underlining commands that are problematic. However, recently, it has been highlighting nearly all sensitive commands as if they are incorrect. This issue persists even after exiting and re-entering FlutterFlow, although it temporarily seems resolved. It appears that the analyzer intermittently flags substantial portions of the code, possibly due to fluctuating analysis configurations or environmental factors.

### Expected Behavior

The expected behavior of a code analyzer is to provide constructive feedback during code development. It identifies errors and potential issues by highlighting problematic commands or structures, helping developers improve code quality and correctness. Ideally, it should accurately pinpoint areas that need attention without excessively marking valid code. Consistency in its feedback ensures developers can rely on it for reliable error detection and improvement suggestions throughout the coding process.

### Steps to Reproduce

I entered the custom code section.
Clicking on any previously saved code, red underlined lines already appear

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lsrLuJdPmN9c+Kr2b8FvmjoRNk87U7g71utHTUo8J5DaPOxzP/TBaldWUs+0S2xqeVmWnmQyw/vemvHIGvE4OTuqRbpB+KgBZxbKfD+6eL6RDpeeXG5/Df9gfGK41MGJnApQKtRhWi0E216EHt+tUgDcNO/ADFgzRM6YUJKK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16886771/8214d4e1-61ad-4251-a14d-fd77667faa9f)

### Environment

```markdown
- FlutterFlow version:  v4.1.63+
- Platform:Web
- Browser name and version:Chrome Versão 126.0.6478.61 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
Hi @TidoGarnier. I just checked your project and I didn't get the analyzer errors. I also tried with a blank project but wasn't able to reproduce it. Is this still an issue for you?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
