### ISSUE TITLE
"Add Elements beta" panel appears when pressing ctrl

### ISSUE THREAD

**Issue by TidoGarnier** [FlutterFlow/flutterflow-issues#3283]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to paste a parameter into the parameter panel on the right, pressing the Ctrl key to perform the paste action triggers an "Add Elements beta" panel to appear above the parameter panel. This overlay prevents pasting the data into the parameter panel. I tried dragging the "Add Elements" panel to the left, but when attempting to paste the data into the parameter, pressing Ctrl shifts the focus back to the "Add Elements" panel, preventing the use of Ctrl for any other action.

### Expected Behavior

When pressing the Ctrl key, it doesn't bring up any screen and simply proceeds to change the subsequent key!

### Steps to Reproduce

Go to Properties Panel.
Try to paste some data to some string property.
On pressing CTRL the "Add Elements beta" panel appears.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lsrLuJdPmN9c+Kr2b8FvmjoRNk87U7g71utHTUo8J5DaPOxzP/TBaldWUs+0S2xqeVmWnmQyw/vemvOeG/koH0icbKY7zs9ibTv/WnilbLXRDpeVe25/Df9gfGK41MGJnApQKtRhWi0E216EHt+tUgDcNO/ADFgzRM6YUJKK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16886771/aa02ea8c-86bf-4590-a90a-697109686e65)

### Environment

```markdown
- FlutterFlow version:  v4.1.63+ 
- Platform:Web
- Browser name and version:Chrome Versão 126.0.6478.61 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11
```

**Comment by TidoGarnier** [comment]
For some reason, this issue stopped occurring. For now, everything is okay!

**Comment by msusviela** [comment]
Thanks @TidoGarnier. I'm closing this issue since i couldn't replicate it and you indicated that it is no longer happening to you. <br><br>If the issue persists, please let us know.<br><br>Thanks for using FlutterFlow!
