### ISSUE TITLE
Firestore Settings "Users Collection" sometimes un-toggled

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#3284]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am not sure what the trigger is, but sometimes the "Users Collection" toggle is removed even though it is not touched.
(You usually don't touch it after the first time.)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/38127aaf-9ed0-48db-99a0-b3915e82781b)

The last time I did before this issue happen, I added a page for re-logging in (not the first time login). Not sure if this is related.

### Expected Behavior

Stay toggle on.

### Steps to Reproduce

I don't know.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfKB35ZJpbwG1c7qcsJWiQMwJ0QlUIInj+0bWRMhfZD1OooIYuPCQxNLYteFeApIEU2ihn4x7tLmjoflKvleGE+VRYBywoRXQQrjWkm6WoyxPZagX3NQL/FYBWHE1sOnhSJDKsVsci0Z3zqACPCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

attached in "current behavior".

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform: web
- Browser name and version: chrome Version 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected: mac sonoma
```

### Additional Information

This bug makes developer panic because "Authenticated user's reference" erased.
"User Reference (Doc Reference)" under "Autenticated User" in attached image disappears and procedures using it gets error.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/9e3a2ca3-eb75-4aed-b55c-380cec115785)

Worse, it is difficult to deduce from this error report the Firebase configuration problem I reported.

**Comment by msusviela** [comment]
Hi @ryutosh. I wasn't able to reproduce this issue from blank. Please let me know if this still happens to you

**Comment by ryutosh** [comment]
Hi, @msusviela 
It occured again yesterday while I also touching login-process.
I still don't know what is the trigger. Please imagine that you don't need care about errors while you are in process of a making of an action. And you will notice there is problem because there is still errors even if I finished up making an action.
That is why I can't tell you exact condition of reproduce.

If you are not relying on reproducible information from the user, you may be able to find (grep) the condition where to turning off in the FF program.

**Comment by msusviela** [comment]
Hi. We were trying to reproduce this issue but we were unsuccessful. A new version of FlutterFlow was released today. If the problem still persists, could you please let us know? We are so sorry for not being able to reproduce this error yet. We're still trying to replicate this but I just wanted to mention the update that might contain some related changes.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
