### ISSUE TITLE
Unable to create an App state using documnet referance

### ISSUE THREAD

**Issue by Sri-Annaamalai** [FlutterFlow/flutterflow-issues#3288]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When tried to create an app state using document reference the create button is disabled it is also when it is change to data types too.

![Screenshot 2024-06-30 170252](https://github.com/FlutterFlow/flutterflow-issues/assets/126306777/7c8a2a97-6f57-4224-b317-41a58578f0a4)
![Screenshot 2024-06-30 170758](https://github.com/FlutterFlow/flutterflow-issues/assets/126306777/7d93be1f-aa64-4623-820f-08a85f1d060e)

### Expected Behavior

If the document referance is also enabled for creating app state it will be esay to use for referance 

### Steps to Reproduce

![Screenshot 2024-06-30 170758](https://github.com/FlutterFlow/flutterflow-issues/assets/126306777/45948eae-0a9b-44e9-93bb-6d2de26e099d)
![Screenshot 2024-06-30 170252](https://github.com/FlutterFlow/flutterflow-issues/assets/126306777/112c456b-e8b2-45dd-9775-bc190535710c)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Okufl2It2m7RG7r6JcvlVtCARHFw2bIZN0e5xaxAjCLHNG7UIec/4VEptXbC+TVc3OlqWgmYJ/s6NhszIN/IDNU6cUYQ5zs9QQzrLVmKRVbXSCbqsPnF6QdpKCkCM052FsxZ5NfttLkIa3WCEHeqia3PAJKL2DUYFJPj8IprDnXPuQ0SLb3kNh1JWeC/v

### Visual documentation

video proof of the bug video taken at 30/06/2024 5:33PM
https://github.com/FlutterFlow/flutterflow-issues/assets/126306777/683eab75-e4e7-48fa-9a9c-ed0aaf07a98b

### Environment

```markdown
- FlutterFlow version: v4.1.65+
- Platform:Web
- Browser name and version: Chrome 126.0.6478.127 
- Operating system and version affected: Windows 11, version 23H2
```

**Comment by msusviela** [comment]
Hi @Sri-Annaamalai. Thanks for filling in! This is a known issue and our ENG team is already working on a fix for this. I'm closing this since it's a duplicate of an existing issue in our backlog.  A fix for this should be put into production soon.

**Comment by taggxyz** [comment]
Any idea when this will be pushed? It's preventing us from releasing an update.
