### ISSUE TITLE
fcm_token not generated in users collection on Android OS 13 Devices

### ISSUE THREAD

**Issue by daynis-olman** [FlutterFlow/flutterflow-issues#329]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When i create new firebase auth account in the app made with flutterflow i except fcm_tokens collection to be automatically created.

## Current behavior (required)
On Google Pixel 7 Pro running OS 13 and Google Pixel 6a running OS 13 on new firebase auth account creation, the user is created and user collection is populated correctly however it is missing fcm_tokens collection. This appears to be affecting all Android Devices with OS 13 - however tested on a handful of real Google Pixel Android devices running OS 13 in AWS Device Farm.

## To Reproduce (required)
1. Install an app built with flutterflow on Google Pixel 7 Pro or Google Pixel 6a (both OS 13)
2. Create new account within the app (firebase auth) 
3. Login to firebase console and locate this account in users collection
4. check whether fcm_tokens is present (it isn't)

## Context (required)
fcm_token for individual users is required to send direct real time push notifications to users individually

## Screenshots / recordings
[https://www.dropbox.com/s/6817v3ty7uzhhb4/fcm-token-test.pdf?dl=0
](url)

## Your environment
* Version of FlutterFlow used: 3.0 Dec 30 2022 Flutter 3.3.4
* MacOS 
* Google Chrome

**Comment by Pepino-GR** [comment]
@wenkaifan0720,

could you please reproduce it with an android device?

**Comment by wenkaifan0720** [comment]
Hi @Pepino-GR. Yes, I actually have a couple of Android phones running Android 13. I'll try to reproduce.

**Comment by daynis-olman** [comment]
@wenkaifan0720 @Pepino-GR 
I have gone ahead and replicated the bug with on below physical device (using AWS Device Farm)

Please can you review this video of the bug and let us know how to proceed further?
https://www.loom.com/share/5699d2edf0de4badb602a38d21e1a44f

**Name: Google Pixel 7 Pro
OS: 13
Manufacturer: Google
Model: 13
Chipset: arm64-v8a   1803 MHz
Memory: 128000000000
Heap: 512000000
Display: 1080 * 2340**

**Comment by wenkaifan0720** [comment]
Hi @daynis-olman. I can confirm this is indeed the case and the reason is due to the Android 13 update of a specific permission. I'll look into this further and find a solution.

**Comment by wenkaifan0720** [comment]
Hi @daynis-olman. On Android 13, the user can manually enable the push notification permission in the app settings and the fcm token would been generated afterwards. A temporary solution would be to prompt the user to go to enable this permission.

**Comment by daynis-olman** [comment]
@wenkaifan0720 Thank you! Would you mind sharing a screenshot and more information on this extra manual workaround ?

**Comment by wenkaifan0720** [comment]
@daynis-olman, I was just about to post these steps! Thank you. 

This is how it looks on a Samsung S22.

![Screenshot_20230116_102036_Permission controller](https://user-images.githubusercontent.com/112435854/212585629-757b0dc9-9509-427b-908f-ccfa36fa3985.jpg)
![Screenshot_20230116_102043_Settings](https://user-images.githubusercontent.com/112435854/212585641-317a128c-ee0f-489e-9358-ed2a84a90b9c.jpg)
![Screenshot_20230116_102055_Settings](https://user-images.githubusercontent.com/112435854/212585643-186b2c85-c71c-4071-9c1b-3999108c487c.jpg)

**Comment by daynis-olman** [comment]
Above instructions work on some OS13 Android devices but not on others. Any idea on the timeline for the official flutterflow fix for this issue? Our production Android app is live in GooglePlay however, unusable by a large number of end-users as FCM Tokens are still not created in some cases.

**Comment by wenkaifan0720** [comment]
Hi @daynis-olman. I am working on this issue. But I am not sure how long a fix would take, as it could be either small (adding a new type of permission request), or very involved (changing how permission is handled altogether on Android 13).

**Comment by wenkaifan0720** [comment]
Hi @daynis-olman. I did some more digging around and here are my findings. 

The only difference between Android 12 and 13 is that 12 grants the notification permission by default whereas 13 does not. If you disable the notification permission of the app in either Android 12 or 13, then the fcm token would not be generated. But once that permission is allowed, the fcm token would be generated automatically on the user's next login. Even if you somehow get a fcm token, without the notification permission, you can not push notifications to the end user. In short, the fcm token and the push notification are linked together. 

And we can not ask for notification permission during app launch/running (see https://pub.dev/packages/permission_handler). It is controlled by the end user in the system settings. The best thing to do that I can think of is to state in your app that notification is useful for the end user and how to enable it.

**Comment by daynis-olman** [comment]
@wenkaifan0720 Would you mind having a look at the breking change in "permission_handled" v 10.0.0 as per below screenshot? Seems flutter handled issue already? Are we using this version in flutterflow? 
<img width="847" alt="Screenshot at Jan 23 20-11-37" src="https://user-images.githubusercontent.com/20358284/214002988-779036a4-a555-4248-be10-807f7de9f32c.png">

**Comment by daynis-olman** [comment]
@wenkaifan0720 Would you mind letting me know why i am unable to find the "permission_handler" you mentioned above in the pubspec.yaml of the codebase generated by flutterflow? Thank you!

**Comment by wenkaifan0720** [comment]
Hi @daynis-olman . I dont think we are using this package right now for permission handling. I am just giving an example for why the notification permission can not be asked within the app in Android 13. I![Screenshot_20230123_200730_Chrome.jpg](https://user-images.githubusercontent.com/112435854/214036362-88922ff3-1981-4c79-8433-661ac712c67a.jpg)

We might be able to directly take the user to the permission setting page. But that is more involved and should take longer to implement.

**Comment by daynis-olman** [comment]
@wenkaifan0720 We currently have FF generated android app running in production on over 30 devices now. Every 3rd Android OS13 device - even when Notification instructions are followed - will not create FCM token. We are in big trouble and need help to save this contract. I am not sure what to do going forward. Please can you provide some suggestions for going forward? Thank you!

**Comment by daynis-olman** [comment]
@wenkaifan0720 is there a way i can manually modify Android code, to ensure we force FCM token generated - as a workaround?

**Comment by wenkaifan0720** [comment]
Hi @daynis-olman. I am so sorry for your experience. This week I'll be constantly travelling so I really dont have a lot of time for debugging. I will look into this issue as soon as I get back home. 

My question is, is the fcm_token needed elsewhere and so critical? If the user choose to not allow notification in Android 12, then the fcm_token would not be generated as well.

**Comment by wenkaifan0720** [comment]
Are you suggesting that for some Andriod 13 device, even when the notification permission is granted, will still not generate the fcm_token? This feels more like a vendor specific problem to me. Are there more details about those devices?

**Comment by daynis-olman** [comment]
@wenkaifan0720 We use FCM to send push notifications to users. The issue being experienced is that on some devices running iOS 13, despite the user giving permission for the app to send push notifications, the FCM token is not being generated. This is preventing the app from sending push notifications to those users.

**Comment by wenkaifan0720** [comment]
I understand. The weird thing is that this is only happening on some devices. I need more details about those devices in order to identify the issue. Are they from the some specific brand?

**Comment by freya-hickman** [comment]
Hi @wenkaifan0720 @daynis-olman did you find a resolution to this? We are having the same issue.

**Comment by wenkaifan0720** [comment]
Hi @freya-hickman. I think my final conclusion is: if the user doesn't allow notification, then generating the fcm token would not be of any use (and that is why firebase is not generating it). If the user allows notification, the fcm token will be generated automatically. So there's not much we can do here, except convincing the user to manually allow notification for your app.

**Comment by freya-hickman** [comment]
Hi @wenkaifan0720 we have tried this and it still does not generate the token, despite logging out and logging in and notification permissions being granted already to the app on the phone

**Comment by wenkaifan0720** [comment]
I tested on a Samsung s22 and android 13 and it was working as I have described. Could you provide more information about the device that you are testing on (preferably in the original issue you raised)?

**Comment by agreaves** [comment]
Managed to reproduce and find a solution! As per [this Flutter issue](https://github.com/firebase/flutterfire/pull/9348) and [this PR](https://github.com/firebase/flutterfire/pull/9348), this a known issue and the fix simply requires upgrading up to `targetSdkVersion 33`. This may affect app behavior for some, so we'll have to run thorough testing first, but you should see it either upgraded or include an option to set `targetSdkVersion` by the time we deploy later this week! Thanks for reporting! 😊

**Comment by freya-hickman** [comment]
Thank you Alex.

Where can we see it upgraded or find the option to set the targetSdkVersion
 ?

Many thanks :)


*Freya Hickman*
Founder & CEO

email: ***@***.***
web:   www.remindhealth.io



Remind Health Ltd is a company registered in England and Wales - company
number: 12839662. Registered address: Remind Health Ltd, C/O Health
Foundry, Canterbury House, 1 Royal Street, London, SE1 7LL

**Comment by freya-hickman** [comment]
Thank you Alex.

Where can we see it upgraded or find the option to set the targetSdkVersion ?

Many thanks :)
