### ISSUE TITLE
Cannot set properties of undefined (setting 'nativeCommunication'

### ISSUE THREAD

**Issue by Hipernova-dev** [FlutterFlow/flutterflow-issues#3290]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Não estamos conseguindo executar alguns projetos Flutterflow e, em todos eles, dá a seguinte mensagem de erro, e não aparece nenhuma das telas iniciais:
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
    at InAppWebViewFlutterPlugin.registerWith (web_platform.dart:36:5)
    at Object.registerPlugins (web_plugin_registrant.dart:37:29)
    at web_entrypoint.dart:27:24
    at initialization.dart:37:9

### Expected Behavior

Que a página inicial aparecesse.

### Steps to Reproduce

1. Executar o sistema.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8iBy49PsbRJ0Lr+au9aiiEXHFh/bJc0sNobbxAjIoDoPJkUaePSUE9BQtPkYwhDKEWL/Dkywt76k/LXUfkVH0yAba1y/5F6TwL/ZHG/aoSKOrrsP3R9P91YIFSi0J2vpBZ5B/VuSHxn2WGMIuiQfDTfQbH7Zwh9f6PHaOI=

### Visual documentation

![Captura de tela 2024-07-01 074248](https://github.com/FlutterFlow/flutterflow-issues/assets/174332450/3aace315-ba41-4a61-9e8c-ce9780419b2c)

### Environment

```markdown
- FlutterFlow version: v4.1.65+
- Platform: Web
- Browser name and version: Chrome - Versão 126.0.6478.127 (Versão oficial) 64 bits
- Operating system and version affected: Windows 10 64bits
```

### Additional Information

Nenhum dos projetos executam, inclusive o ispiportal-qjndtx. Em todos aparecem esta mensagem no console do navegador e não aparece nenhuma das telas, inclusive o index.

**Comment by Alezanello** [comment]
Hello! <br>Thank you for reaching out. I attempted to replicate the issue on a blank project but was unable to do so, indicating this might be specific to your project. <br><br>One potential solution you can try is to call the web_support.js from the index.html header. You can do this by adding the following script tag in the 'Web Publishing' section of your FlutterFlow Project: <br><br><script type="application/javascript" src="/build/flutter_assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer></script><br><br> This approach aligns with the recommendations provided in the documentation of the flutter_inappwebview package, as mentioned in the Readme section.<br> For your reference, you can find more details here: [https://pub.dev/packages/flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) <br><br>Please let us know if this resolves your issue or if you need further assistance, You can reach at support@flutterflow.io. <br><br>Best regards, <br>Azanello

**Comment by sergedahdouh** [comment]
hello, i have same issue since last update when i push a new version of my web app 
ITFXk/KA4YlgrupE1Yf1YOxavGIwGUwbUOc7j9VEGAsjCePyPbAQecn8VEpvWOqHTAt+eWakoHsGpt7yhoX1F8EBEySdQNlTypFpUxDgbEOVMbaKEKu0SX8lO/hnJky41MHQnB1RLvheSkIQ2F6uf9iub3qCf9qOYwx5e6fDbOY=

Failed to load resource: the server responded with a status of 404 ()
Rejecting promise with error: Error: Cannot set properties of undefined (setting 'nativeCommunication')
(index):78 Uncaught (in promise)
$1(a){return this.a.warn(a)},

**Comment by Hipernova-dev** [comment]
O erro estava sendo causado pelo componente HMTL_editor_enhanced.
 Foi retirado. Investigando alternativa para edição de HTML na aplicação.
 Erro parcialmente resolvido.
