### ISSUE TITLE
Downloaded code throws errors

### ISSUE THREAD

**Issue by thomasallnice** [FlutterFlow/flutterflow-issues#3291]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Once I open a downloaded project in VS Code I get a lot of errors. I reported a similar problem before. I got fixed, but meanwhile I came back.

https://github.com/FlutterFlow/flutterflow-issues/issues/3173

https://community.flutterflow.io/c/bugs/post/bug-is-back-vs-code-throws-tons-of-errors-all-of-a-sudden-uris-missing-sW2ICHAnmU5Z5FW

### Expected Behavior

there shouldn´t be any issues

### Steps to Reproduce

download code
open in vs code
execute

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Once I open a downloaded project in VS Code I get a lot of errors. I reported a similar problem before. I got fixed, but meanwhile I came back.

### Visual documentation

<img width="787" alt="Bildschirmfoto 2024-07-01 um 16 13 03" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6171130/3b29e2d0-b9e5-4386-866e-6473ff0d441e">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @thomasallnice. I wasn't able to replicate it from a blank project. I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by thomasallnice** [comment]
I received an email meanwhile, sorry for not getting back to you here. issue seems to be solved.
