### ISSUE TITLE
Can't switch branch in iPad app

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#3296]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While I can access other branches in the desktop app or in a browser, I can't access other branches in the FF iPad app. You can create a new branch in the iPad app but then you can't go back to the main branch or any other.

### Expected Behavior

Be able to switch to a different branch in the iPad app

### Steps to Reproduce

Create a different branch then try to access it on the iPad app

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40qebf36pho8tc57XQavdv9WM7HUgmR74R1t1RaCsofePrOpkAf8/7UFtUOdO6YX9XfGaJpDoX/MnHvuLxGPI4BxObGKo61pBqYArvZGS6M4yyPZS3b3dBN+1bFUeP0qaRpBZAVdJaS1Fk11yUC++tUT3DK6b6O2sFAuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 4.1.64
- Platform:iPad
- Browser name and version: N/A
- Operating system and version affected: iPad OS
```

### Additional Information

*No response*

**Comment by rzambroni** [comment]
Hello, thanks for the report, i was able to replicate the issue you're describing.

It seems like it is not updating the UI, if you tap on the branch you want to switch to and then close the project and come back it will be switched to that branch.

Will send it to the team so they can take a look.

Thanks.
