### ISSUE TITLE
App does not load but there are no errors in the project

### ISSUE THREAD

**Issue by jordan-jakisa** [FlutterFlow/flutterflow-issues#3297]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have a problem with the VerAInt project on FlutterFlow, in the project there are no errors, in test mode it is not running and when published as well it is not loading.

### Expected Behavior

The app should be able to load atleast or show a grey screen

### Steps to Reproduce

Here is a link to the project: https://app.flutterflow.io/project/verein-rebirth-giyymn

Here is a link to the deployed web app: https://verain.flutterflow.app/

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wzfHqw5NNoblE15DucMJahmAUMjshaI0R1+1+FSs8GZT0B4kcYs+kfklUONejTHNbM0yWuGYX/MqLj87hF8EpIRGuRtVByYdiTwHwdzuWRcmtPK63b3Z8RPhXGX6a5LTZkxQnJbJvdE4d23GPN+q/UgPBK4DXDEcRGeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72340216/fcf6f3bd-56e8-4925-a4c4-25262c59f3d9)

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Windows
- Browser name and version: Google Chrome 
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I accessed the web you shared, and it is loading correctly without any issues. <br><br>Is this problem resolved on your end? <br>Did you change anything or redeploy the web after submitting this issue?

Best regards,<br>Azanello

**Comment by jordan-jakisa** [comment]
Yes please,

I did delete a custom widget which was causing the error and the web app
was able to load without any issues.

Thank you very much!
Please, if there is any other way i can help you prevent this bug from
happening to other users, please let me know.

**Comment by Alezanello** [comment]
Hi Jordan!

We've encountered several issues similar to yours. To clarify, did the custom widget you deleted include the `html_enhancer_editor` package?<br><br>To be sure is the same package that is making this issues

**Comment by jordan-jakisa** [comment]
Hello,


Yes please, i don't know if you mentioned the same package but yes, it is called `html_editor_enhanced`

Here is the link to it's pub dev page
https://pub.dev/packages/html_editor_enhanced

**Comment by Alezanello** [comment]
My apologies, I meant the `html_editor_enhanced` package. This package was affected after upgrading Flutter to version 3.22.2.

This is a project-specific situation and not related to a FlutterFlow error. We highly recommend finding another package that meets your project's needs.

**Comment by Alezanello** [comment]
I found a temporary workaround within the community that might help you continue using the package. Please check the first comment on this post: [Rich Text Editor Custom Widget](https://community.flutterflow.io/app-showcase/post/rich-text-editor-custom-widget-FwwEg9LJxy3i1EJ).

I hope this solution works for you in the meantime!

Best regards,<br>Azanello

**Comment by jordan-jakisa** [comment]
Alright, thank you!
