### ISSUE TITLE
Assets in the project vanishes after a day of upload

### ISSUE THREAD

**Issue by saumyahelms-24** [FlutterFlow/flutterflow-issues#3299]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I uploaded all my assets in flutterflow, but after a day, all the assets vanished. Since then have not got them back, i had to re-upload all the assets again

### Expected Behavior

All the assets should be there once uploaded

### Steps to Reproduce

1. Upload asset to Media Assets section
2. Save project
3. checked after some time
4. all the reference to it lost and asset vanished

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

blank

### Visual documentation

blank

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Windows
- Browser name and version: Chrome v126.0.6478.127 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello @saumyahelms-24 !

I'm sorry to hear you faced this issue. Could you please confirm whether this issue occurred on FlutterFlow Windows or Web?

Additionally, could you generate a Bug Report Code from your project by right-clicking any widget in the Widget Tree and share it with us? This will help us investigate the issue more effectively.

Thank you for your cooperation.

Best regards,
Azanello

**Comment by saumyahelms-24** [comment]
I am using FlutterFlow windows

Bug report : IT4SiPLlvYtOodtb1ar2ccFB/T8vJnI7audMiu1AEQEafa7wE4YLXOjASEhVXd+/TAl2Ilv9jjkd3PDJvdmWGuQHAwWAfIB51KhuERXKTTinb5S2DqqVPWtBONNVHkuV3JiruBQnVc1eR045w02bNumATT7YNoTsDmo7B+WiJtvXnmyYAi+6Xn0Jg1ZSfCvr

**Comment by Alezanello** [comment]
Hello!

I apologize for the delayed response. Does this issue still occur for you after latest FlutterFlow update?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
