### ISSUE TITLE
setState called in a defunct state when handling push notification

### ISSUE THREAD

**Issue by siddharthadevops** [FlutterFlow/flutterflow-issues#33]
## Expected behavior (required)
Backend should use a live state widget to handle push notifications.

## Current behavior (required)
Backend shouldn't use a defunct state to handle push notifications.

## To Reproduce (required)
Down't know why this widget is removed from the widget tree.

Code can be included in this section if it is relevant to reproducing the bug. 

  ```
Future _handlePushNotification(RemoteMessage message) async {
  setState(() => _loading = true); <- HERE
    try {
      final initialPageName = message.data['initialPageName'] as String;
      final initialParameterData = getInitialParameterData(message.data);
      final pageBuilder = pageBuilderMap[initialPageName];
      if (pageBuilder != null) {
        final page = await pageBuilder(initialParameterData);
        await Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => page),
        );
      }
    } catch (e) {
      print('Error: $e');
    } finally {
      setState(() => _loading = false);
    }
  }
```

## Context (required)
Receiving a push notification.

## Your environment
Stack Trace:
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1078:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1113:6)
#2      _PushNotificationsHandlerState._handlePushNotification (package:acim/backend/push_notifications/push_notifications_handler.dart:39:5)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)

**Comment by siddharthadevops** [comment]
The code above is been generated by yours, it's not my code. I downloaded de full app code from FlutterFlow and just executed in debug mode. The code is in the file .../../lib/backend/push_notifications/push_notifications_handerl.dart

In some occasions the widget state is defunct when a notification arrives and an exception is thrown. So, the landing page specified in the notification is never launched.

You can see the stack when the exception was thrown above.

**Comment by organicnz** [comment]
Could you clone the project and try it on a new one?

**Comment by wenkaifan0720** [comment]
I have an idea of how to fix this issue. When calling `setState()` in async functions, we should first check if the widget is still `mounted`. So we need to add that check in the generated code.

**Comment by organicnz** [comment]
> I have an idea of how to fix this issue. When calling `setState()` in async functions, we should first check if the widget is still `mounted`. So we need to add that check in the generated code.

Please describe your idea step by step to make it reproducible for the testers :)

**Comment by wenkaifan0720** [comment]
@organicnz The problem should be fixed by now.
