### ISSUE TITLE
Supabase Integration:  List types and custom types now completely non-functional

### ISSUE THREAD

**Issue by buyblvd-ryan** [FlutterFlow/flutterflow-issues#330]
Previously, upon importing the Schema, FF would complain that the List type was <Unset> and let me manual define it.  Now though, FF throughs all the same errors but the button to set the type in the FF schema view is gone.  Clicking on the errors brings you to the schema page, but there's nothing there that solves the problem.

The error reads something like:  Supabase Setup:  Data type missing for [table.column].  Data type must be specified for Array fields in Supabase.  But Supabase shows the types correctly.  This is a problem I'm encountering both with Lists of built in types (like VarChar) as well as Lists of custom composite types I've created (which can basically be handled like JSONs).

**Comment by Franco98404** [comment]
@buyblvd-ryan maybe this issue can be helpful for you:

https://github.com/FlutterFlow/flutterflow-issues/issues/267

**Comment by buyblvd-ryan** [comment]
Hi @Franco98404 

Small update, the problem is not what I originally experienced.  Your issue linked is definitely the behavior I was encountering previously, but this is a recent development where (I thought) FF was no longer allowing me to manually define the column types.  After reviewing the issue today, it's apparent that FF does still allow this, but the Supabase table view page in FF doesn't seem to be displaying properly, such that it seemed the button to manually set the type was gone.  Screenshots are attached below.

![image](https://user-images.githubusercontent.com/117312895/211675095-d5d664db-b823-455f-884b-4d50ca40ac8a.png)

![image](https://user-images.githubusercontent.com/117312895/211675200-41012a6d-578b-4ad5-8aa5-8e8cf2cd1d98.png)

As you can see, upon entering the page, it seems like the "Click to set Array type" button has disappeared.  In actuality, you have to click and drag on the table to see that the whole column is actually hiding several hundred pixels away.  This isn't a page width issue, as the browser window is in fullscreen on a 3440x1440 display.  So, I've got a workaround for now, but this page needs different behavior.

**Comment by wenkaifan0720** [comment]
@katherineqian, any thoughts on this issue?

**Comment by katherineqian** [comment]
Thanks @wenkaifan0720 and all above, should be fixed on next release.
