### ISSUE TITLE
Error when deploying from GitHub

### ISSUE THREAD

**Issue by FilliTech** [FlutterFlow/flutterflow-issues#3301]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I deploy from the main branch of github I get the following error:

Failed Step: Flutter build ipa and automatic versioning

Archiving it.bestiebite.app...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: 6U6SQSM724
Running pod install...                                              3.4s
Running Xcode build...                                          
Xcode archive done.                                         149.6s
Failed to build iOS app
Error (Xcode): Undefined symbols:

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Encountered error while archiving for device.

Build failed :|
Step 11 script `Flutter build ipa and automatic versioning` exited with status code 1

### Expected Behavior

It should deploy to apple store as it also did before.

### Steps to Reproduce

1. Create a project
2. Push the code to Github
3. Deploy to the apple store from the github branch (main)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slvHqx89NodhE7ZDUKflR/WY4C0t7R404sctvaw4dfuPqPZYLPcn8REhuSOqHYX5XeVekrH0e0fTWj+z9E8A6Bz6bbohI+qpTUxDgIUOhb66WPKmaYWhAO/Fhfkij1ruF2B57Lsl1WXgG2GC2IN6Ab3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="662" alt="Screenshot 2024-07-02 at 18 11 42" src="https://github.com/FlutterFlow/flutterflow-issues/assets/110170895/8787e3ea-2389-41c7-9b78-317335ce8b29">
<img width="655" alt="Screenshot 2024-07-02 at 18 11 49" src="https://github.com/FlutterFlow/flutterflow-issues/assets/110170895/54df4fc3-c998-455b-ad2f-48ab60075374">

### Environment

```markdown
- FlutterFlow version: v4.1.65+
- Platform: Any
- Browser name and version: Chrome
- Operating system and version affected: Any
```

### Additional Information

I can deploy from flutterflow with no problems, and I deployed from github many times the same project before but now it gives this error. 
I have not changed the things in github, it adds the integration with meta_sdk that I can not add from flutterflow.

**Comment by msusviela** [comment]
Hi @FillTech.<br>You can try by incrementing your build (or version) number. Each deploy must have a higher build number.<br><br>This community post can help you:<br>[https://community.flutterflow.io/database-and-apis/post/step-11-script-flutter-build-ipa-and-automatic-versioning-exited-with-7NpyCXgjnUJqvbH](https://community.flutterflow.io/database-and-apis/post/step-11-script-flutter-build-ipa-and-automatic-versioning-exited-with-7NpyCXgjnUJqvbH)<br><br>If the issue still persists, I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by FilliTech** [comment]
Hi @msusviela 
I incremented both, I used to deploy in the same way the app from github without any issue, now I get this error and I haven't changed anything in the deployment process.

I will try to reach out to flutterflow support, thank you.
