### ISSUE TITLE
[NEED HELP] Build faild

### ISSUE THREAD

**Issue by dr-shoe** [FlutterFlow/flutterflow-issues#3303]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tried a test run and deployment to the App Store, but I encountered the following error and could not proceed. 

There are no bugs in the FlutterFlow UI, and I am unsure how to resolve this issue. 
If anyone knows the solution, could you please share it with me?

Thanks in advance!

-------------------------------------------------------------------------------------------

87 packages have newer versions incompatible with dependency constraints.

Try flutter pub outdated for more information.

Launching lib/main.dart on Web Server in debug mode...

Waiting for connection from debug service on Web Server...

Warning: In index.html:51: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.

Warning: In index.html:74: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.

lib/pages/home/timeline/post_detail/post_detail_widget.dart:883:127: Error: The getter 'conditionalBuilderPostLikesRecord' isn't defined for the class '_PostDetailWidgetState'.

- '_PostDetailWidgetState' is from 'package:ABC/pages/home/timeline/post_detail/post_detail_widget.dart' ('lib/pages/home/timeline/post_detail/post_detail_widget.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'conditionalBuilderPostLikesRecord'.

firestoreBatch.delete(conditionalBuilderPostLikesRecord.reference);

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

lib/pages/home/community/community_post_likes_count/community_post_likes_count_widget.dart:313:45: Error: The getter 'conditionalBuilderCommunityPostLikesRecord' isn't defined for the class '_CommunityPostLikesCountWidgetState'.

- '_CommunityPostLikesCountWidgetState' is from 'package:ABC/pages/home/community/community_post_likes_count/community_post_likes_count_widget.dart' ('lib/pages/home/community/community_post_likes_count/community_post_likes_count_widget.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'conditionalBuilderCommunityPostLikesRecord'.

conditionalBuilderCommunityPostLikesRecord

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Waiting for connection from debug service on Web Server... 58.9s

Failed to compile application.

### Expected Behavior

It should deploy or run test mode as it was before. 

### Steps to Reproduce

1. To run test mode or deploy.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Get Bug Report Code

### Visual documentation

![スクリーンショット 2024-07-02 232334](https://github.com/FlutterFlow/flutterflow-issues/assets/143674727/a64b9aa4-bded-4fb7-af08-df6279310458)
![スクリーンショット 2024-07-03 000812](https://github.com/FlutterFlow/flutterflow-issues/assets/143674727/167491fb-07be-4024-ac45-c05355903859)

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform:Web
- Browser name and version:126.0.6478.115
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
<br>Hello!

I'm sorry you're experiencing this issue while trying to deploy the app. To help us identify the root cause, we need to reproduce the bug.

Could you please share the Bug Report Code for your project? You can generate it by right-clicking any widget in the Widget Tree menu of your FlutterFlow project.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0a91a582-89c0-46e8-ab14-57e17580a904/21e2a821-7ad4-4864-aa29-fa396c2615d2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYTkxYTU4Mi04OWMwLTQ2ZTgtYWIxNC01N2UxNzU4MGE5MDQvMjFlMmE4MjEtN2FkNC00ODY0LWFhMjktZmEzOTZjMjYxNWQyIiwiaWF0IjoxNzIwMDA4OTY5LCJleHAiOjMzMjkwNTY4OTY5fQ.Lp4t0cCGoIvZrcA_7C89sFjjGD8Q4tN9KVykc6r2Glc " alt="image.png" width="481" height="342" />

Thank you for your cooperation.

Best regards,<br>Azanello

**Comment by dr-shoe** [comment]
The bug report code is below.
Thanks in advance!

**Comment by Alezanello** [comment]
@dr-shoe 

I looked into this error and found that your query in the Conditional Builder is returning a list, but the delete document operation expects a single document, not a list.

Could you please change the query type from "List of Documents" to "Single Document" in the Conditional Builder?

Here’s how to do it:

Component: communityPostLikesCount
Conditional Builder Query: Change from "List of Documents" to "Single Document"
Let me know if this works for you. In the meantime, I will try to replicate this issue on a blank project.

Best regards,
Azanello

**Comment by dr-shoe** [comment]
Thank you!
I tried  your advice and it seems to be fixed.

Previously, if I selected List of documents or Single document incorrectly, it would show an error indicating there was a bug. However, it did not appear this time. Is this a bug?

**Comment by Alezanello** [comment]
Hello again @dr-shoe !

It looks like you uncovered an unusual issue. While I'm not entirely sure if it's a bug, I was able to replicate it easily. I'll escalate this to the engineering team for further review and analysis.

Thank you again for bringing this to our attention!

Best regards,
Azanello

**Comment by dr-shoe** [comment]
I still have another bug for sometimes.
Is this related to the bug above?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/143674727/446dd04f-60d7-4da2-a6f2-6e80bd2f5722)
