### ISSUE TITLE
Missing Font Asset

### ISSUE THREAD

**Issue by dashapps** [FlutterFlow/flutterflow-issues#3304]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All of a sudden I am getting the following errors. There were no errors previously. I had the TTF files uploaded. Even after deleting the files from Typography & Icons custom fonts, I am still getting the same errors. How can we fix these errors?

Symptoms:

	1.	When duplicating the project, the interface shows no errors, but compilation ends with a red error screen (see attached screenshot).
	2.	With these errors, the project does not compile at all, and when I click on the error, it takes me to the assets page where I can only change loading graphic elements like logos, icons, etc. I deleted the font and set the base font, but this doesn’t fix the error; the error seems stuck.
	3.	The error occurs even after clearing the fonts and setting the default fonts as the primary and secondary.
	4.	I receive “Missing Font Asset” errors indicating that “TochkaBlack.ttf” and “TochkaBold.ttf” are missing, even though they were previously loaded (see attached screenshot).
![Monosnap Загрузки 2024-07-03 01-21-32 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/bedd64bc-b689-4484-a72c-670793d2b7cd)
![Monosnap Загрузки 2024-07-03 01-21-54 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/83daf1d7-69ba-4182-ac79-69083400688a)

I found that this issue matches exactly with a bug reported in the FlutterFlow community: [Missing Font Asset](https://community.flutterflow.io/c/bugs/post/missing-font-asset-sO6mSajpwNINH0j).

I would appreciate your assistance in resolving this issue, as it is hindering further progress on the project.

### Expected Behavior

The build should compile without any errors, and the custom font files should be recognized correctly. If the custom fonts are disabled, the project should fall back to the default fonts without any issues. Additionally, the font files should be visible and manageable in the assets section. The pubspec.yaml file should reflect the inclusion of the fonts.
![Monosnap copicrm - FlutterFlow 2024-07-03 01-32-52 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/63e21e7f-ade1-4796-90f1-e59db3adb764)
![Monosnap crmtochka - FlutterFlow 2024-07-03 01-37-19 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/c1866672-e406-443d-b5cf-c580d67511a0)

### Steps to Reproduce

	1.	Initially, the project compiled without any errors and custom fonts were recognized correctly.
	2.	Suddenly, the errors started occurring.
	3.	Attempted to fix the errors by deleting the custom font files from Typography & Icons, but the errors persisted.
	4.	Created a duplicated project where the fonts were reset, no errors were shown, but the project compiled with the same error as shown in the screenshot.
	5.	In the original project, the errors prevent compilation completely.
	6.	Clicked on the error, which directed me to the assets page where only loading graphic elements like logos and icons could be managed.
	7.	The font files do not appear in the pubspec.yaml file.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8mAx5BNxMhE7c7ybe9aqGERKVA+a5c0sd4bGA0dCJzuPLMQdvWkN1VVOdDnTXxDekSmmkEHwdbFvofLFcc6CxCaftl4+M1ibjvgIXOua5OBC5aOTnclM+hgGh2j1qSskx1AWdB1cmQMwziIANi8cHPqGJDJIndISq/LZO4=

### Visual documentation

![Monosnap crmtochka - FlutterFlow 2024-07-03 01-37-19 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/484f901b-5a4c-4f34-af93-c6121bb9bb42)
![Monosnap Загрузки 2024-07-03 01-21-32 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/5213d1b5-5668-4865-bf54-7abb6f0aace6)
![Monosnap Загрузки 2024-07-03 01-21-54 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/96581fa0-8353-4ff9-a37d-6875113e315c)
![Monosnap copicrm - FlutterFlow 2024-07-03 01-32-52 1](https://github.com/FlutterFlow/flutterflow-issues/assets/121200111/0fc68787-e6ef-4987-82ec-fc7964f2d139)

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: MacOS Desktop, Web
- Browser name and version:Chrome 126.0.6478.127
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by msusviela** [comment]
Hi @dashapps. I couldn't replicate the issue from a blank project (the assets in the .yaml file are being generated correctly).<br><br>I downloaded your project and it's also generating correctly:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/eae6ed86-e476-44cb-94ef-a9d5fbfad3e3/aef57de6-1ddf-4bcf-8d40-d01fe2762275?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYWU2ZWQ4Ni1lNDc2LTQ0Y2ItOTRlZi1hOWQ1ZmJmYWQzZTMvYWVmNTdkZTYtMWRkZi00YmNmLThkNDAtZDAxZmUyNzYyMjc1IiwiaWF0IjoxNzIwMDEyODUzLCJleHAiOjMzMjkwNTcyODUzfQ.N7x_uW6om-4j7wmcERm5v-nLkfIuytPVPyp2ZI6pHXA " alt="image.png" width="422" height="172" />

<br>I tried in both environments - web and desktop.<br><br>Please, let me know if the issue persists. If it persists, I'll suggest reaching out to our support team: [support@flutterflow.io](mailto:support@flutterflow.io). They can better assist you with ensuring your project is configured correctly!
