### ISSUE TITLE
font awesome not up to date

### ISSUE THREAD

**Issue by arroyoDev** [FlutterFlow/flutterflow-issues#3305]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

trying to add a font awesome icon for x-twitter.   (easily found on the site fontawesome.com.   however not available in flutterflow

### Expected Behavior

up to date icon list 

### Steps to Reproduce

try to add x-twitter as an icon

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not needed

### Visual documentation

<img width="406" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/699333/226a5bc6-76d1-40ff-a9f6-f609e4a7cc3d">

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform:web
- Browser name and version: safari
- Operating system and version affected:  macOS
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!<br>I'll let you know as soon as I have an update.

I'll suggest that in the meantime it takes to fix it, you use a custom icon for this.<br><br>Thank you so much for your report!
