### ISSUE TITLE
Test Mode page in FlutterFlow does not load and Publish button does not work

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3306]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to access the Test Mode page in FlutterFlow, the screen remains blank with no content displayed. Additionally, the Publish button is also not functioning, preventing any projects from being published. This issue started recently as both were functioning correctly last week.

### Expected Behavior

The Test Mode page should load normally, displaying the available tools and options for testing.
The Publish button should allow the publication of projects.

### Steps to Reproduce

1. Open FlutterFlow.
2. Navigate to the "Test Mode" section.
3. Observe that the page does not load any content.
4. Try using the Publish button to publish a project.
5. Observe that the button does not perform any action.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CjMrqx891pbxb7q6JbflahjosJlg5RYIziNVtdwEjHZPMC+wIZ/f7XFRuTde0T3w3PVmgkj8d7s3emvHTF8crC0mCf758zZZiFhbhZD65MKqzCcy0Vm5/DeRXIFSd06u72xNABMthclog2U2mHeeyQnLvQ5zAO0g3A/r9UJKK2SrDX1iXc2URm05KZDPz
### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/381d3313-2fb9-4c26-b8ce-baed7f70f2ef)

### Environment

```markdown
- FlutterFlow version: last
- Platform: web
- Browser name and version: last
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. Could you please provide me with the Bug Report Code from your project? You can easily generate it by right-clicking on any widget in the Widget Tree menu.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f8eccbda-2d6b-4d99-8d69-21981cb75716/3d10789b-2bec-4b34-8537-942b05794d03?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOGVjY2JkYS0yZDZiLTRkOTktOGQ2OS0yMTk4MWNiNzU3MTYvM2QxMDc4OWItMmJlYy00YjM0LTg1MzctOTQyYjA1Nzk0ZDAzIiwiaWF0IjoxNzIwMDE1NTQwLCJleHAiOjMzMjkwNTc1NTQwfQ.jtjeFDokoSpRhZ8Ckq7e41XflaFp85U1gge9OPxT68U " alt="image.png" width="481" height="342" />

Additionally, try opening the debug panel, and once the page loads completely, close the debug panel or change the resolution using the buttons at the top. <br><br>This might help trigger the app to load correctly.

Thank you for your cooperation.

Best regards,<br>Azanello

**Comment by SauloSA** [comment]
Bug Report Code
IT4CjMrqx891pbxb7q6JbflahjosJlg5RYIziNVtdwEjHZPMC+wIZ/f7XFRuTde0T3w3PVmgkj8d7s3emvHTF8crC0mCf758zZZiFhbhZD65MKqzCcy0Vm5/DeRXIFSd06u72xNABMthclog2U2mHeeyQnLvQ5zAO0g3A/r9UJKK2SrDX1iXc2URm05KZDPz

**Comment by Alezanello** [comment]
Hello again @SauloSA !

We've encountered several issues similar to yours. Did you have any custom widget that includes the html_editor_enhanced package?

To be sure is the same package that is making this issues

**Comment by SauloSA** [comment]
Yes, I am using the html_editor_enhanced package in my project. It is indeed very frustrating that FlutterFlow has not yet provided a native alternative.

There is a community within the Bubble platform that continues to use Bubble because they find nothing better in FlutterFlow. The most frustrating part for users is the lack of justification or updates on the status of this highly anticipated widget within the FlutterFlow community. It is such a basic functionality.

**Comment by SauloSA** [comment]
What should I do? How long will my application be down?

**Comment by Alezanello** [comment]
Thank you for sharing your feedback and expressing your concerns. <br><br>I understand how frustrating it can be to work without a native alternative to the `html_editor_enhanced` package in FlutterFlow.

Regarding your application's downtime, unfortunately, because the `html_editor_enhanced` package has been deprecated with the latest Flutter upgrade, it will not function correctly. <br><br>This means that your application will remain impacted until an alternative solution is implemented.

We recognize the importance of having such basic functionality, and we appreciate your patience as we work towards providing better solutions.

We strongly recommend searching for an alternative package that meets your project’s requirements to minimize downtime.

We are committed to improving FlutterFlow and value the insights from our community. <br><br>Your feedback is invaluable, and we will continue to push for updates and enhancements based on user input.

If you have any further questions or need assistance, please don’t hesitate to reach out.

**Comment by SauloSA** [comment]
In the update "What's New in FlutterFlow | April 18, 2024," it was mentioned that the Rich Text Editor was in progress under "New Features We're Working On 🏗️ Rich Text Editor."

However, we haven't received any further updates since then.

Could you please check internally for an update on this? Are you still working on this feature, or has it been paused? What is the priority level of this feature? Do you have any estimated timeline?

**Comment by Alezanello** [comment]
There are many ongoing projects and feature requests being handled by the engineering team, and unfortunately, I don't have an estimated timeline or release date for this particular feature.

In the meantime, I found a temporary workaround within the community that might help you continue using the package. Please check the first comment on this post: [Rich Text Editor Custom Widget](https://community.flutterflow.io/app-showcase/post/rich-text-editor-custom-widget-FwwEg9LJxy3i1EJ).

I hope this solution works for you in the meantime!

Best regards,<br>Azanello

**Comment by SauloSA** [comment]
The lack of transparency about the current status of the rich text editor is very frustrating.

Currently, there are two alternatives for the rich text editor: quill_html_editor and html_editor_enhanced. However, as mentioned in the tutorial [Rich Text HTML Editor for FlutterFlow Apps](https://community.flutterflow.io/c/community-custom-widgets/post/rich-text-html-editor-for-flutterflow-apps-psYBqr7mpwcuonH), the latest versions of these alternatives also have incompatibilities with FlutterFlow.

It is frustrating to see that there is no demonstration or communication from the FlutterFlow team to address this issue, which only increases our anxiety.

Unfortunately, the temporary solution suggested by the community did not work for my specific case. I am still facing problems with the integration of html_editor_enhanced and the lack of native support is causing significant impacts on my project.

Could you please share the status or what are the challenges with the Flutter language to resolve this?

**Comment by SauloSA** [comment]
I am writing to express my sincere concerns regarding the lack of a native Rich Text Editor widget on the FlutterFlow platform.

Currently, there are two alternative text editors available for use with custom code in FlutterFlow: quill_html_editor and html_editor_enhanced. However, as mentioned in the tutorial Rich Text HTML Editor for FlutterFlow Apps, the latest versions of these alternatives also have significant incompatibilities with FlutterFlow.

I would like to clarify the major challenges faced by those who need this widget. For both packages, the latest versions are incompatible, necessitating the use of outdated versions with bugs. For instance, the recommended version for the quill_html_editor package is ^2.1.9, while the latest version is 9.5.12. Furthermore, the html_editor_enhanced package became incompatible after the recent Flutter update to version 3.22.2.

This leaves us in a delicate situation, as the absence of an integrated rich text editor poses a significant obstacle for the development of FlutterFlow applications with advanced text editing requirements, such as blogs, copywriting, and especially generative AI applications with text editing.

The most frustrating aspect is the lack of transparency regarding the progress of this widget. In the What's New in FlutterFlow | April 18, 2024 update, it was mentioned that you were working on a new feature for a rich text editor. However, we have not received any further updates, and the community remains without a clear statement. The absence of native support is causing critical impacts on our projects, with constant risks of crashes and bugs.

The greatest frustration is the lack of clarity on whether we can expect a native solution soon and the estimated timeline, which significantly increases our anxiety as we are unable to plan our next steps in hopes of finding a solution.

I greatly admire the work you and your team have done so far. I fear that this delay in offering a rich text editor may be related to limitations of the Dart/Flutter language, which might be beyond the FlutterFlow team's capacity and may require a solution from Google, who are responsible for the Flutter language.

I respectfully request that the FlutterFlow development team provide a detailed update on the status of the rich text editor, including the specific technical challenges being faced. Better understanding these challenges would help us be more patient, collaborate more effectively with the team, and plan alternatives for our applications.

I believe that more open and transparent communication on this issue would benefit the entire FlutterFlow community and help build a more collaborative and productive development environment.

Thank you in advance for your attention and for the continuous work to improve the platform. I remain available to provide further information or discuss possible solutions.

Sincerely,
Saulo Assis

**Comment by leighajarett** [comment]
Hi there, <br><br>Thank you so much for this feedback. You're very right on transparency, we should have done a better job here. I will post in the community forum after responding here. <br><br>We implemented a rich text editor and released it for beta testing several months ago. However, we found numerous issues and lack of customizability. This feedback meant that it would actually be worse for users then not launching anything at all. These issues were with the underlying package we used and would have taken a lot of effort to fix within the underlying Flutter code before even making it available in FlutterFlow. We have been investigating other alternatives but haven't found anything suitable.<br><br>We are still hoping to support this feature - but we don't have a specific timeline because we need to significantly change the underlying Flutter code, which is complex and time consuming. I know how disappointing this can be, we are doing our best to prioritize this work as soon as possible. Thank you so much for understanding and we hope to have more information soon!

**Comment by SauloSA** [comment]
I understand, and thank you for the response.

Now, imagine if it is difficult for the FlutterFlow team, even after receiving millions in funding and having a capable technical team, imagine how difficult it is for simple users.

I believe that a simplified version of the Rich Text Editor could help a lot, with basic functions like bold, italic, underline, text alignment, and getSelection being interesting. These basic functionalities would already meet many use cases and could be a significant step forward while a more robust solution is developed.

I would also like to reinforce that a good argument for dedicating more efforts to the Rich Text Editor is the fact that we are in the hype of generative Artificial Intelligence, which fundamentally works with text. You are missing the opportunity to offer a valuable resource for thousands of applications that could work with text editing. I would really like you to seriously consider taking this argument to the FlutterFlow product team.

And, watching in the desperation of someone who needs this functionality, I confess that a "Where is the Rich Text Editor?" campaign is valid [laughs]. 😂

Thank you again for your attention and for the continuous effort to improve the platform. I hope we can see progress in this regard soon.

Sincerely,
Saulo Assis

![giphy (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/56657406/decba0bf-473d-4d9b-8a69-331963101517)

**Comment by leighajarett** [comment]
Hahaha totally fair, we will definitely take this into consideration! Love the gif 🙂

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
