### ISSUE TITLE
Copy-pasting action chain that contains action output variable names results in errors

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#331]
## Expected behavior (required)
Copy pasting an action chain that includes action output variable names (say, apiResult1, apiResult2, etc.) into a different widget's action tree should just work without errors.

Suggestion for improved functionality: Automatically append the action output names with a number in order to avoid duplicates while copy/pasting.

## Current behavior (required)
Copy pasting an action chain that includes action output variable names (say, apiResult1, apiResult2, etc.) into a different widget's action tree causes all references to the action output variables to invalidate, forcing the user to re-set any instance in the chain that uses those action outputs.

## To Reproduce (required)
1. Create action with an action output variable name

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1. Make an action chain that includes an action output name
2. Use that action output name within the action chain
3. Copy the chain
4. Paste it in a different widget

### Bug Report Code (required, generate from Widget Tree)

I don't see that option when right clicking.

## Context (required)

If I have a button that does a chain of 3 different API calls / custom functions, I cannot copy that action chain into an IconButton without having to manually change every single part of the action tree (including all the JSON paths).

## Your environment

* Version of FlutterFlow used: December 29th
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by Pepino-GR** [comment]
Hi DanielEdrisan,

I can reproduce your issue, but I think, we need to handle it as a Feature request, because the insert works as designed.

**Comment by aemelyanovff** [comment]
Hi Daniel! I'm happy to see you using FlutterFlow :-)

I agree with @Pepino-GR, this is closer to a feature request than to a bug. I'll bring it up in the next PDC. Happy building!

**Comment by DanielEdrisian** [comment]
Thanks @aemelyanovff  ! Ok I understand! Just to note, though: even changing the action output name to a different name doesn't automatically fix the reference within the tree, the same way say changing a widget's state name changes its name throughout the widget tree. This is therefore more of an expected behavior based on the other mechanics already in place, rather than a feature.

**Comment by aemelyanovff** [comment]
Added in the next release.
