### ISSUE TITLE
Component in Component and Widget State when selecting a variable dont show the name of the component

### ISSUE THREAD

**Issue by nickwood2009** [FlutterFlow/flutterflow-issues#3313]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you use multiple components of the same type on another component or page and then try to use the state of one of those components as a variable, the varable selector shows a list of all of the same default component names, not the custom names given so there is no way to distinguish between them when selecting

### Expected Behavior

When you change the name for the used component on the parent it will show that in the list for the component or widget state so you know which instanct you are selecting

### Steps to Reproduce

1. Create a new component with component state variable
2. Try to use it from the calling component where there are more than one child component of the same type
3. Rename the components to a custom name on the parent component
4. Try to use the component state for an action on the calling parent component

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhfKA0ItInMhE7ZDQcMFVliUwGUALa+dI0tZ+TQ0jF5D4EZk2OePBMxRtTdSzaHNtPlaGmTkEwc7WjuPTO8YEITmdR4hhyZZUUBPPbEyhMabWPLW0PGtDI51WIB260Lan3yQmOtBvZVIZ61yxe+fKQT2Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1969372/3a1fabd1-6684-4e19-b212-b889924fb910)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1969372/1d5daf22-02c3-4957-af72-7ce7bb055327)

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Chrome
- Browser name and version: any
- Operating system and version affected: any
```

### Additional Information

none

**Comment by Alezanello** [comment]
Hello!

First of all, thank you for reaching out to us!

I wasn't able to replicate the issue in a blank project. Could you please provide more information about the steps you took to achieve the issue? Alternatively, you could create a blank project, replicate the issue there, and share the Bug Report Code with us.

Best regards,<br>Azanello

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c5f1bd5f-fb60-46dc-84f3-086cdf94a3a0/91759cbb-7e21-4aa8-a485-83d817f5f094?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNWYxYmQ1Zi1mYjYwLTQ2ZGMtODRmMy0wODZjZGY5NGEzYTAvOTE3NTljYmItN2UyMS00YWE4LWE0ODUtODNkODE3ZjVmMDk0IiwiaWF0IjoxNzIwMDk3OTgyLCJleHAiOjMzMjkwNjU3OTgyfQ.2odqJ9qYHMimKexuSYT0AHtf9aEBoOOS-oTmhQONb8M " alt="image.png" width="1613" height="820" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. <br><br>If you are still facing the problem please submit a new issue. <br><br>Have a great day!
