### ISSUE TITLE
Unable to use Windows desktop. It doesn't open. Not worked for about 4 days. 

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#3315]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

But no particular reason Windows desktop stopped working. I have uninstalled it and reinstalled it, and even removed any traces of the directory, but still when I try and open it up, I simply just get the spinning wheel as seen below. 

### Expected Behavior

That the application would open. 

### Steps to Reproduce

Install Windows desktop, and then try and open it. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YMS8+kMxJVXemndGNEL2H9oDkzwN7PvdnMA+UnMkiCG4Bc1ZNqSQ/xcEyuaKnTCai0Q39TJ9lJJVyw34m3rRRCIfpfSl4a1Dque+TJYz3tGL7MIkUeDcj+Jp3XnGOqQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/153652817/735d6b65-6e88-4a87-8ece-1b7386d33811)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Windows
- Browser name and version:na
- Operating system and version affected: Windows 12
```

### Additional Information

I thought it might be something to do with my Google account, but I've waited four days to see whether it would fix itself and tried everything. In our studio tonight Nicola Sturgeon she was the one who said

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue.

Could you please try deleting the folder at this directory: `C:\Users\<user_name>\AppData\Roaming\FlutterFlow\flutterflow` and then run your FlutterFlow application as an administrator?

Best regards,<br>Azanello

**Comment by rzambroni** [comment]
Hi, additionally, could you check if you have your date/time correctly configured in your PC? I have seem some issues related to that. (It's a long shot  could work).

Sorry we can't do much more from here, it is very difficult to pinpoint this type of issues happening on certain platforms.

**Comment by snowboarder** [comment]
My date and time are correct.  Hopefully this gets resolved soon because I have started to like testing my app on local run.

**Comment by Alezanello** [comment]
Hey Snowboarder, did you tried to delete the folder i told you 2 comments up from this one?

**Comment by charliefabley** [comment]
This did not work for me. I deleted the directory, and uninstalled FF. The
first time I did it I thought it had worked because at least it got as far
as asking me for my credentials. I went through the system of
authenticating my credentials which is Google by the way, and then I got
back to the same position. Flutterflow wood hang when starting up in the
image that I provided. So maybe that's a clue, that we managed to get it to
behave differently by deleting some directories, but ultimately it got
itself back into the same situation. Why it's now not asking for
credentials again when it did the first time must be something that perhaps
you can work out.

**Comment by charliefabley** [comment]
BTW here is another clue. Google Authentication goes through Okta.

**Comment by charliefabley** [comment]
And finally my colleague is on my team and does not have this issue
although she authenticates in the same way. But she never got herself into
the situation either, it just kept working.

**Comment by Alezanello** [comment]
I've done everything I could to help resolve this issue, but at this point, the best course of action is to open a support ticket directly. Please contact support via the in-app chat or email at [support@flutterflow.io](mailto:support@flutterflow.io). <br><br>They will be able to take a deeper look into this issue and help you find a solution.

**Comment by charliefabley** [comment]
Thank you, I will do that.

**Comment by Alezanello** [comment]
Perfect! I'm going to close this issue. I hope the support team resolves your problem. If you encounter any other issues, please don't hesitate to open a ticket. We are here to make FlutterFlow the best product for you.

Best regards,<br>Azanello
