### ISSUE TITLE
FlutterFlow on iPad: Unable to type content in the "Combine text" expression popup on latest iPad Pro 13 (M4)

### ISSUE THREAD

**Issue by ARVdevFlostate** [FlutterFlow/flutterflow-issues#3316]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On the FlutterFlow for iPad app, I am unable to type (or view existing) content in the combine text expression popup on iPad Pro 13-inch (M4). The same works fine using the Mac OS and web app. 

Refer to the attached screenshot for more details.

### Expected Behavior

It should work the same way as the Mac OS and web app version.

### Steps to Reproduce

1. Create a blank page
2. Add a local page state variable of String type
3. From Page-> Actions-> On Page Load, Open Action Editor and click on Add Action
4. Select Action-> State Management-> Update Page State
5. Click Add Field, Select your Page State Field
6. Under Set Fields, Select update type select Set Value
7. Click the icon next to Value to set and click on Combine Text
8. Observe that the input under Text 1 does not show the data that is entered
9. There my friend you have successfully reproduced the issue :)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz/Hqx891m9tb+Kr9bcJR/SEUHD8+aoE8scsZa0kdB4joPLJ+POPOUBdBTfGjYGlhHFH+pEIG7t75k+zLO8YEOQmaY4Bn+KpcaTvyd3q8RaatC5GKQXJCEZhMCh2X0KezhhRQFOxoWHge22b3fdi8Th3AJ5+/Zwh9f6PHaOI=

### Visual documentation

![IMG_0006](https://github.com/FlutterFlow/flutterflow-issues/assets/139889075/dacd3c26-8082-4f40-835b-f5d1684546ce)

### Environment

```markdown
- FlutterFlow version: 4.1.64
- Platform: iPad OS 
- Browser name and version: NA
- Operating system and version affected: iPad OS ver 17.5.1
```

### Additional Information

I was trying to use my iPad Pro as my device for FlutterFlow app development. This issue didn't allow me to complete my development task. Had to find a desktop to complete the task.

**Comment by rzambroni** [comment]
Hi @ARVdevFlostate, thanks for the report, unfortunately there are a few issues with the iPad app and specific devices/aspect ratios. I'll pass this to the team but keep in mind it might not be prioritized very soon.

Thanks again.

**Comment by sbis04** [comment]
This should be fixed in the upcoming update!
