### ISSUE TITLE
Build Failed after Flutter upgrade

### ISSUE THREAD

**Issue by yassirLio** [FlutterFlow/flutterflow-issues#3318]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,

After the last Flutter Upgrade, there was so many errors in my project, the last one I can't resolve is when I run the test mode I have this error:

93 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
Warning: In index.html:51: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:66: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
lib/custom_code/widgets/test_syncfusion.dart:450:42: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/sdks/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
                color: Theme.of(context).backgroundColor,
                                         ^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         63.7s
Failed to compile application.

![Build Failed](https://github.com/FlutterFlow/flutterflow-issues/assets/153300227/ca89b6da-5ce2-4b8a-a46e-38b58cf5c87b)

### Expected Behavior

Project test mode must  run since there is no error

### Steps to Reproduce

Project test mode don't run, even if there is no error in the project. It come after the Flutter Upgrade

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

93 packages have newer versions incompatible with dependency constraints. Try `flutter pub outdated` for more information. Launching lib/main.dart on Web Server in debug mode... Waiting for connection from debug service on Web Server...       Warning: In index.html:51: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead. Warning: In index.html:66: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead. lib/custom_code/widgets/test_syncfusion.dart:450:42: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.  - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/sdks/flutter/packages/flutter/lib/src/material/theme_data.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.                 color: Theme.of(context).backgroundColor,                                          ^^^^^^^^^^^^^^^ Waiting for connection from debug service on Web Server...         63.7s Failed to compile application.

### Visual documentation

![Build Failed](https://github.com/FlutterFlow/flutterflow-issues/assets/153300227/cbb75825-052f-4440-9dec-d3e6322513c5)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.65+ released June 28, 2024 . Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  desctop
```

**Comment by rzambroni** [comment]
Hey @yassirLio, it seems like you must be facing a custom code dependency issue that needs to be fixed. FF upgraded the Flutter version to 3.22.2 on the latest release and that might be the reason they are showing up right now.  <br><br>In case it is helpful here is a quick guide on how to fix dependency issues: [https://www.youtube.com/watch?v=8Y1uyCC_dXE](https://www.youtube.com/watch?v=8Y1uyCC_dXE)

Since the issues are the same i'm closing  issue in favor of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3229](https://github.com/FlutterFlow/flutterflow-issues/issues/3229)

(The specific solution might depend on the dependency you are using but please take a look at the thread on the above issue, there are several solutions that you might use as reference)

**Comment by yassirLio** [comment]
Hello,

This have No relation with what you shared in the video.. I'm using the correct dependecies for the custom widgets I'm using and I double checked with what you sahred.. all seems good.

Note That I have no error in my project, only the problem occure when I build to test mode.

Also, the error after some investigations come from the costum widget "testSyncfusion" witch is "syncfusion_flutter_calendar widget". But all the dependecies I'm using are correct as per the version of Flutter used in FF: 
- syncfusion_flutter_calendar: ^26.1.40+1
- syncfusion_flutter_datepicker: ^26.1.40
- timezone: ^0.9.3

To be sure that it's not related to the dependencies, I tried all possibilites of previous dependencies but no good result.

Regards
