### ISSUE TITLE
FlutterFlow MultiSelectDropDown Issue

### ISSUE THREAD

**Issue by saddamhussaints** [FlutterFlow/flutterflow-issues#3319]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using FlutterFlowMultiSelectDropDown, in this i can select multiple items at a time, but i'm unable to select all and unselect all options at a time....this should be implemented i guess

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/88323519/9cd01f61-1d60-4e3d-8763-8c46decada77)

### Expected Behavior

Need a option to select ALL and unselect ALL so that all the checkboxes need to select and unselect

### Steps to Reproduce

You can try flutterflow new versions

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

qwerty

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/88323519/5f61cf9e-abd0-4aa6-8054-4149ab6e7a4d)

### Environment

```markdown
You can try flutterflow new versions
```

**Comment by msusviela** [comment]
Hey @saddamhussaints, currently it's no implemented. This tracker is only used for reproducible bugs, so I am closing this issue.

 I've added this as a feature request in our internal backlog and we will get to it as soon as possible.

 Thanks for your feedback!
