### ISSUE TITLE
Wrong Custom Firestore Database Support

### ISSUE THREAD

**Issue by DamnBlack99** [FlutterFlow/flutterflow-issues#3320]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

'Custom Firestore Database URL' is not what Firestore supports.
Firestore does not support URLs for its Databases.
I will attach an image of the error.

### Expected Behavior

We should put in there, for example, directly, 'The Name Of The Database', and done: For example 'Lara Croft'.
Instead of The URL of The Lara Croft Database.

### Steps to Reproduce

1) Go To Settings.
2) Go To Firebase.
3) Find 'Firestore Database URL'.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

This is not about a widget

### Visual documentation

<img width="960" alt="Snap 2024-07-05 at 08 43 15" src="https://github.com/FlutterFlow/flutterflow-issues/assets/174799727/1fade2d0-8b2a-4ee0-8b81-b7f608cdbf1b">

### Environment

```markdown
- FlutterFlow version: 4.1.65+.
- Platform: All Of Them.
- Browser name and version: Chrome.
- Operating system and version affected: Windows.
```

### Additional Information

Please solve this bug as fast as possible!.

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out to us. <br><br>I will consult with the technical team regarding this matter and get back to you with a more specific answer.

Best regards,<br>Azanello

**Comment by DamnBlack99** [comment]
Please pay attention to this bug and don't close the thread without checking about it.
Thank you.

**Comment by DamnBlack99** [comment]
Do not leave it in status stale.
This is a very important issue.

**Comment by DamnBlack99** [comment]
Hi?.

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. I will get back to you soon with an answer regarding this issue.

**Comment by DamnBlack99** [comment]
Hi?.
This shouldn't be closed.
FIRESTORE DOES NOT SUPPORT URLS AS YOU ARE ASKING FOR IN SUCH IMAGE'S TEXT FIELD.

**Comment by DamnBlack99** [comment]
Let's make it simple.
Try to actually implement A FlutterFlow Project with A Firestore Database different than 'default'.
YOU WILL NOT BE ABLE TO IMPLEMENT IT VIA THAT 'Firestore Custom Database URL' Text Field!.

**Comment by Alezanello** [comment]
Hello DamnBlack99!<br><br>Is marked as Done because the engineer team took take issue and resolve it.<br><br>It will be implemented in the next production release!
