### ISSUE TITLE
Add App state variable doesn't work for Document Reference data type

### ISSUE THREAD

**Issue by PMFlis** [FlutterFlow/flutterflow-issues#3323]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am not able to create the app state variable with data type document reference as the Create button is disabled; it works for all other data types but doc ref;

### Expected Behavior

to be able to create the app state of doc ref type

### Steps to Reproduce

go to the app values and tap on the button Add app state variable, then add name and from the dropdown menu choose document reference, then choose the reference type, the button Create is disabled ;

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/1sIZgobxc+Kn+bPlFmSkRCUMdXOczitVEew4bCIj4PIYQd87OS1VVUu6zaHxEfVr+mmEF0NaPv/HLLO4qFyybbqE4watyTBPPbGGiMqqhPbqOOnNCO8BUG3aG0ImCkCRCGNNtWmAA3GaIFdm+RT2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1470" alt="Screenshot 2024-07-06 at 01 22 06" src="https://github.com/FlutterFlow/flutterflow-issues/assets/74993843/afab496c-3b27-469c-a868-19bd6d6cbf8c">

### Environment

```markdown
- Project: Storme
- Project-Id: stor-me-1nde2w
- FlutterFlow v4.1.64
- Flutter version is 3.22.2
- Platform: ALL
- Browser name and version: Chrome
- Operating system and version affected: MacOs
```

**Comment by rzambroni** [comment]
Hello @PMFlis, thanks for the report, this issue was reported several time this week and it is already fixed, the next version will very likely include the correction.

Marking this ticket as duplicate.

Thanks again.
