### ISSUE TITLE
Cannot upload 2 signatures on the same page

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#3327]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently a page has 2 signature boxes and an action chain to upload both of them. However it is throwing an error because it is not producing 2 unique uploaded URL

`"FlutterLoader.load" instead.
lib/pages/home_page/home_page_model.dart:30:10: Error: 'uploadedSignatureUrl' is already declared in this scope.
  String uploadedSignatureUrl = '';
         ^^^^^^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:29:10: Context: Previous declaration of 'uploadedSignatureUrl'.
  String uploadedSignatureUrl = '';
         ^^^^^^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_widget.dart:286:25: Error: 'signatureImage' is already declared in this scope.
                  final signatureImage = await _model.signature2Controller!
                        ^^^^^^^^^^^^^^
lib/pages/home_page/home_page_widget.dart:241:25: Context: Previous declaration of 'signatureImage'.
                  final signatureImage = await _model.signature1Controller!
                        ^^^^^^^^^^^^^^
lib/pages/home_page/home_page_widget.dart:300:25: Error: 'downloadUrl' is already declared in this scope.
                  final downloadUrl = (await uploadData(
                        ^^^^^^^^^^^
lib/pages/home_page/home_page_widget.dart:255:25: Context: Previous declaration of 'downloadUrl'.
                  final downloadUrl = (await uploadData(`

### Expected Behavior

In the widget state, uploading 2 signatures should show 2 separate Uploaded Signature URL (like having multiple upload photo buttons). This is not the case.

### Steps to Reproduce

1. Create new page
2. Have 2 signature boxes for signing
3. Create an action chain to upload 2 signatures

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48iOfl2It2n7xe7qqNdcBvimAXQkM7RII00+saaxQ8J5DKP4kievTOVBNvZ9O0Y3NMIVq0kXwKw8HemvHXOvcqaDCVfpRjwaVqUTqXWTuVV5SXBpGodW5/Ap9WI3auyreFkApSHLJvR1ojwVOqC+6XHyvAJZOxNTAvGMmbC5CK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151034963/f0452e7d-6b24-4622-8adb-0f6e71e8d896)

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform: Web
- Browser name and version: Chrome 126.0.6478.127 
- Operating system and version affected:  MacOS 14.5 (23F79)
```

### Additional Information

Signatures are frequently used for signing. Imagine a real life document app between parties to sign.

**Comment by Alezanello** [comment]
Hello!!

Thank you for bringing this issue to our attention!

I was able to replicate the problem and have gathered all the necessary information. I will forward this to the Engineering team for further action.

I kindly ask for a little patience as we work to address this issue in future releases.

Thank you, 

Azanello

**Comment by cooldude1010** [comment]
@Alezanello Any update on when this bug will be fixed?
