### ISSUE TITLE
No way to unmute video player by default

### ISSUE THREAD

**Issue by launchInsighter** [FlutterFlow/flutterflow-issues#3328]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am working on a project that requires the video to be played with sound as soon as the video player widget is loaded.  However, there's no way to turn on the sound by default in the control panel. I will be loading short videos one by one, and each time, the user has to turn on the sound, which is annoying.

### Expected Behavior

There should be a toggle to mute and unmute audio in the control panel.

### Steps to Reproduce

1. add VideoPlayer widget to page.
2. observe that there's no toggle to unmute/mute audio in the widget control panel.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cz8jfz49On7xE7q6Jc/lV+WAWHEw8RYEw1+xERkoYN5PLCLMqZPfBP3NuTcPndGNEL1m0mXIyp/CNvezEA+UoYDaabpRBzqt+ZgyVeEyQMa2aCrieP0dBHehJJVPH57uRqxZCKbFZc0482U6mH/KvaBTqJYy2IkYkQ/mKMrP/pXeqQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="889" alt="Screenshot 2024-07-06 at 10 43 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/171405857/c92b6093-6e31-4a85-8306-93b91ec14dfa">

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform:  macOS
- Browser name and version:  Chrome
- Operating system and version affected: macOS, iOS, Android
```

**Comment by msusviela** [comment]
Hey @launchInsighter, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!
