### ISSUE TITLE
Editing a translation in the Language menu, it shows a grey rectangle

### ISSUE THREAD

**Issue by pnaa** [FlutterFlow/flutterflow-issues#3332]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When editing a translation from the "default/main" language form screen, it shows a grey rectangle 

### Expected Behavior

Don't show anything aside from the screen we are editing

### Steps to Reproduce

1. Go to language tool
2. translate any string from the first column (default language)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ysmAuJdPxOVA+KX2acdKnjwWH0c7RK87iet+Tg88KOvLBIYuP/WlV1VCOLykTXNEM0SmmXwdptb1k/H2UfU6GAqAfa06+rlibDvMZHmVUZOBCamwWUFtL91WClSX056FgBJ4JuhpSloS2zmmNu6UZD/UJKL4IlFISq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/28980882/329177db-2c0e-4ba1-8657-f884e3875199)
****

### Environment

```markdown
FlutterFlow v4.1.65+ released June 28, 2024
Flutter version is 3.22.2
- Platform: desktop and web
- Browser name and version: chrome (latest version)
- Operating system and version affected: (macOS latest version)
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
