### ISSUE TITLE
Add support to edit the code in flutterflow

### ISSUE THREAD

**Issue by YugaSolutions** [FlutterFlow/flutterflow-issues#3334]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Today, user can just view the code and download it. User cannot edit the code in FF.
Can you allow users to edit the code and build on top of it?

### Expected Behavior

User should be able to edit the code in flutterflow widgets and pages and all possible code paths.

### Steps to Reproduce

Navigate to "View Code". Try to make any changes and user wont be able to modify the code.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

Try the steps mentioned in previous section

### Environment

```markdown
- FlutterFlow version: v4.1.65+
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hey @YugaSolutions, This tracker is only used for reproducible bugs, so I am closing this issue. At the moment, you can create Custom actions and Custom widgets that can cover your needs for more personalization. 

 I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!

**Comment by YugaSolutions** [comment]
@msusviela, can you get this feature soon? Any ETA?
