### ISSUE TITLE
IPad app - information buttons don’t work

### ISSUE THREAD

**Issue by adichirita** [FlutterFlow/flutterflow-issues#3336]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking on information buttons (usually small round buttons with the small letter “i” on it next to various areas in the app) such as the information button next to the “Page Parameters” label on the right hand side (or any information button next to the widget attributes such as “Visibility”, “Opacity”, “Page (Scaffold) Properties” and so on. 
The only information button that worked, in the whole FlutterFlow application was the information button next to the project name, in the top left corner of the app. 

### Expected Behavior

Tapping on information buttons next to various controls in the app should open a hint window with some useful hints/info about that control.

### Steps to Reproduce

1. Open the FlutterFlow app on an iPad (see details about the device in the environment section)
2. Tap Create New to create a new project
3. Enter project name as test123 and choose “Blank”
4. Skip further project setup by tapping on Skip
5. On the top right corner of the window tap on the small “info” button to the right of the “Page Parameters” label. Nothing happens. Repeat this for any other info button in this screen or any other screen of the FlutterFlow app with the same result.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grs9a0aqNbuxAhQIgQ0QnU7gnlO1ucx4YG7LtOrAQPs7CR0NKT9+5fUFMOU38mToK+PDwuNj1KvBePTeWRrpi0JVASjrwQl+XMZjQEbiwWkRfEdFUC2HH57uzphVSBMBtcloQ6kyXNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="332" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/42970680/7133eefb-510e-4705-abc7-8ded452ab364">

### Environment

```markdown
- FlutterFlow version: 4.1.64
- Platform: iPadOS v17.5.1
- Browser name and version: N/A (using the FlutterFlow app on iOS)
- Operating system and version affected: iPadOS v17.5.1
- device iPad Pro (12.9 inch) (6th generation)
```

### Additional Information

This affects the productivity of any new adopter of FlutterFlow through the FlutterFlow app since they cannot learn what each field of the app that has an info button does.

**Comment by rzambroni** [comment]
Hello @adichirita,

Thank you for the report. I was unable to replicate the issue you described.

Please note that on an iPad, the correct gesture to show the info tooltips is to "long-press."
