### ISSUE TITLE
Firebase Create User document

### ISSUE THREAD

**Issue by elisabethmoon123** [FlutterFlow/flutterflow-issues#3337]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Yesterday, I was able to add users from the create account to my firebase through the testing feature on flutterflow, and today when I went to test creating another user to the documents, it won't update in firebase (I have also not changed firebase rules on permissions, I just added a seek function to the project on a different page that I created) - and it won't even navigate to the next page when I select create

### Expected Behavior

I would expect that when you create a user document fopr it to create a user document in firebase and then navigate to the next page 

### Steps to Reproduce

1. Auth create account button on page 2. proper parameters to be entered (email, pass, etc) - as well as the create user document option to be selected 3. Test feature to create account 4. when pushing the create account button for the create user document to be created

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci8mAsIpgobxG1s+NY+9V/CQXIjs4RYEZ1NZ9bwAaHZPMC+wIZ/f7XFRuTde0Y1FMfE2juH000NHemvDhCfdeFwyuUao5zs99EQLwfE67VK6rCqmCSW5/De1TGlyF5JiJnh17LfVsV14Y1E2bf9yUYz/sHrLBPW0GDv+bA5CK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Screenshot 2024-07-08 at 15 27 38](https://github.com/FlutterFlow/flutterflow-issues/assets/175022612/87589f62-96a1-435d-b9f3-1cd4829eea68)

### Environment

```markdown
- FlutterFlow version: v4.1.65+
- Platform: MacOS
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I successfully created two users in your project (testing@testing.com & testing2@testing.com), but as you mentioned, it doesn't move to the next page. After examining your rules more closely, I suggest changing the read permission on the 'users' collection to 'Users Collection'. Currently, it can create and write, but the project needs to read it to get the user information and query data within your project. This might be the reason for the issue.

Please try changing that specific rule and let me know if it works!

Best regards,<br>Azanello

**Comment by elisabethmoon123** [comment]
Thank you, sorry I knew it must've been something small but I was going crazy for a minute 

All good now :)

**Comment by Alezanello** [comment]
Hey!

No worries, we're here to help. Did changing the rule fix the issue?

**Comment by elisabethmoon123** [comment]
Yes it fixed the issue! I'm seeing it in the database and it is moving to the next page

**Comment by Alezanello** [comment]
That’s great news!

I’m going to close this issue as it was project-specific. If you encounter anything else, please feel free to open a new issue!

Best regards,<br>Azanello
