### ISSUE TITLE
Conditional actions rremoved 

### ISSUE THREAD

**Issue by robbiestokes21** [FlutterFlow/flutterflow-issues#3338]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when loading up my project my Conditional actions are now improperly setup. I have 32 bugs with the same bug report code

### Expected Behavior

Conditional actions i have are Doc Ref to my auth user, it only show's the basic ref. I have my firebase store the same and all the fields are their. but it won't let me ref the use name like before.  User name is gone with my other fields. 

### Steps to Reproduce

I don't know on how you can Reproduce it. All i did is open my project and none of my doc Ref are their anymore.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkfLluJNgrulc+KnhY8BagWIWM0MfWLsr0utuGA0hfJDwBJYUO8nsQ1VLYteYfHN+H1CIiTkBpPTvvvPLD+4BCzSrfY8//pRXQQ3hWmWmVqqDPLu8WWpBJ+Nmf0y60Z+O2CNdJvBuWmNl2U+me/CrG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-07-08 112830](https://github.com/FlutterFlow/flutterflow-issues/assets/20848619/cb28d627-bd72-4b96-85ce-6ddf09a95fde)
![Screenshot 2024-07-08 112721](https://github.com/FlutterFlow/flutterflow-issues/assets/20848619/ae5fec54-bde7-42f3-807c-68638687075e)

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform:windows
- Browser name and version: using the desktop app
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're facing this issue. I just accessed your project, and everything seems to be working fine at the moment. Did you find a fix or do anything to resolve it?

Please make sure that the "Users Collection" in the Firebase Settings is enabled.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f0cfb64d-263b-44da-8cb9-0b8fa1236fd1/2106598b-44d0-407e-9184-6e37ed5b4e6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMGNmYjY0ZC0yNjNiLTQ0ZGEtOGNiOS0wYjhmYTEyMzZmZDEvMjEwNjU5OGItNDRkMC00MDdlLTkxODQtNmUzN2VkNWI0ZTZhIiwiaWF0IjoxNzIwNDU5OTAwLCJleHAiOjMzMjkxMDE5OTAwfQ.Bdk0y0cBfxn8w4ZSw4uEbmFhjL5mIm5DlW5Gn_ex1Yg " alt="image.png" width="1684" height="354" />

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
