### ISSUE TITLE
LanguageSelector widget has lowercase options in it

### ISSUE THREAD

**Issue by deiu** [FlutterFlow/flutterflow-issues#3339]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The LanguageSelector widget lists most languages using uppercase (e.g., English, German, etc.) except for French (e.g, français).

![Screenshot 2024-07-08 at 17 13 06](https://github.com/FlutterFlow/flutterflow-issues/assets/346820/6d780bf8-7fc5-473d-ab18-7f9c9457e031)

### Expected Behavior

All language options in the dropdown menu should start with an uppercase letter.

### Steps to Reproduce

1. Enable several languages besides English -- i.e. German, French, Italian.
2. Create a LanguageSelector widget.
3. Tap the selector and it will display "français" using lowercase "f" letter.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojPHqw4pOj7xK0Lr+cMFFmSQUH1w/bYIs0spBTTUgGO/wOokAYffASE5uTdO4Snw3MFv88WMz+taOvuz9DuQHAyecQbpEwZN+ehfgRnOubKbQBpOBe3BRHZ1TNEuV06TRkSRAWfhhci0d7TmIPemuSgrXQ+KxPVdAIeSYKt/4gXSpAi+6Xn0Jg1ZSfCvr

### Visual documentation

![Screenshot 2024-07-08 at 17 13 06](https://github.com/FlutterFlow/flutterflow-issues/assets/346820/6d780bf8-7fc5-473d-ab18-7f9c9457e031)

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: MacOS
- Browser name and version: N/A
- Operating system and version affected: iOS 17.5 /Android (API 35)
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by VictorAndCo** [comment]
I have the same issue, would be great if it's fixed soon.

**Comment by ni-rom** [comment]
+1 for this fix request. It should literally take 5 seconds to correct.
Line 310 in flutter_flow_language_selector.dart ;)

**Comment by ibiolm** [comment]
This problem has been there for ages now. It should be easy to fix?

**Comment by VictorAndCo** [comment]
For me it's been fixed already for French
