### ISSUE TITLE
Pie Chart Legend Bottom Overflow

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#334]
## Expected behavior (required)
The whole legends section should be visible.

## Current behavior (required)
The legends section floats down from the chart widget and obscures the section below it.

## To Reproduce (required)

1. Create a new page
2. Add Chart Widget
3. Select Pie Chart
4. Use any kind of source for values and labels
5. Add more then two Pie Chart Colors
6. Set the Show Legend to true
7. Add 1 or two more widgets below the chart
8. Run in run mode or in test mode

### Bug Report Code (required, generate from Widget Tree)
ITESz/Hqx89gruEG+bn+Ke16hR8kQ2InarsvhO4bRRIaF7LmEJYtbuvRdndbQt+RfVFIJln9kkUFw87ej4fDNew5BxPDJ+AHl/E0LlSrGAc=

## Context (required)
Trying to show the legends for all the values of the pie chart

## Screenshots / recordings
![piechart](https://user-images.githubusercontent.com/103430937/211567778-126f7ccb-b119-492b-a302-5b033e793707.png)
![piechartsettings](https://user-images.githubusercontent.com/103430937/211567794-024c568c-f798-48f4-b912-39cf4d7a167c.png)

## Your environment
* Version of FlutterFlow used: 3.0 dec 29th
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): Win11

**Comment by agreaves** [comment]
Hi @tothati90! Thanks for the report. In this case, this is because the Legend height is too small for the items it contains. Within the "Legend Properties" you can configure the height to an appropriate value which will fix this issue. Hope this helps!
