### ISSUE TITLE
Bug in FF Color System ?

### ISSUE THREAD

**Issue by VIA-SOFTWARE-GMBH** [FlutterFlow/flutterflow-issues#3340]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In ThemeSettings/Color I have selected or entered an RGB value.
The selected color is displayed (in the Color Editor), but later not used in the UI.

If you open the color dialog again, the RGB value that was there before is displayed again, the new value is lost.

What I just noticed is that even if I want to change the FillColor in the TextBox in the "Object-Inspector" on the right (in Pages), 
this happens also , only in the Color Editor, which appears when you click on the button next the RGB TextField, it seems to work.

I think, the problem was not there before the last update or was not so noticeable.

P.S: Maybe the person who fixes this could also take care of sorting the colors by name, that would be a gain for FlutterFlow. :-)

![S1](https://github.com/FlutterFlow/flutterflow-issues/assets/168002461/9de955ce-f524-4153-b0af-966b061f7914)

### Expected Behavior

If I select a color in the color picker or enter it manually in the TextField as RGB value,
the new value should replace the former value.

### Steps to Reproduce

1. Goto ThemeSettings/Colors
2. Click on a Custom Color area
3. Change the color with the picker or type #FAFBFA e.g. in the TextField
4. Press Return
5. Open the same color again and watch the value. It is not the value you entered before.
6. Same seems to happen in the Page ObjectInspector at right side. (e.g. "FillColor" of a Container)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not available in this case

### Visual documentation

![S1](https://github.com/FlutterFlow/flutterflow-issues/assets/168002461/0ed6c397-fe0b-4956-9294-ebfdf28f4ff7)

### Environment

```markdown
- FlutterFlow version: Latest Pro Version (Desktop), but it also happens in Web Version
- Platform: Windows
- Browser name and version: Chrome / Edge
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello!

I've been trying to replicate this issue extensively on both the Windows and Web versions without any success. I tested every widget that allows setting a fill color, and the new value always remained. I also checked the Theme Settings Colors menu, and the new value persisted there as well.

Could you please record a short video showing the exact steps to reproduce the issue?

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by VIA-SOFTWARE-GMBH** [comment]
https://github.com/user-attachments/assets/691eafaa-ca85-4473-ba7e-c127f7aeb2c4

I hadn't contacted you for a few days because the error no longer occurred. Now, strangely enough, it's back again! 
(see video)

As I said, the color is e.g. blue (#0000FF)
I click on it and change it to red (#FF0000)
After closing the editor, everything looks fine at first, it seems to have taken on “red”.

When I open the editor again, however, either the old value appears 
(#0000FF) or the old value with transparency (#300000FF)
or a completely different value, e.g. yellow.

Very strange ...

In any case, I can no longer work with FlutterFlow (if it continues to exist).
Since we are creating a project for a customer (and he wants “his” colors and not some random colors) 
this is understandable, don't you think? 

Best regards
