### ISSUE TITLE
"On Data Change" listeners do not get removed on dispose

### ISSUE THREAD

**Issue by smn-snkl** [FlutterFlow/flutterflow-issues#3341]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a Backend Query and adding a "On Data Change" action, the code gets compiled to:
```
stream: Record.getDocument(...)..listen((doc) async {
  // Handle on change
});
```

However, the listener reference is not stored anywhere and, hence, the listener never gets cancelled. In our case this means that every time the user opens the Page containing the listener, an additional new listener gets created. This creates lots of issues when "On Data Change" updates e.g. the page state even though the page was already unmounted / disposed.

### Expected Behavior

The reference should get stored and on the widget's dispose call, the listener should get cancelled.

### Steps to Reproduce

1. Create a new page
2. Add a new "Backend Query" to e.g. an empty Container widget
3. Add "Update Page State" action to the "On Data Change" listener
4. Open the page multiple times
5. Change the data
6. All the listeners from all the page opens will be called at once

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl8/luI9Oj7xZ7aryLO9Vq2IWNU9+apc0sd4bGA0dCJzuPLMQdvWkTFBtOemlSkFYPESmmlsB+N7TiITfE/cpCwusG9lDwboNWzzdd3GQa5OBPKuBPmsnO59UfHas5KWO2xN5D/Vhc3wRwGemIdzIFz7DQeOyImdISq/LZO4=

### Visual documentation

The listener here is causing the issue and should not be added with a cascading operator:
<img width="1223" alt="Screenshot 2024-07-08 at 19 39 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/fc4edc90-77b8-42d8-b7ca-6a5a1a48e537">

It might be a better solution to add an additional StreamSubscription like for the "_keyboardVisibiltySubscription" to store the StreamSubscription and cancel it on dispose:
<img width="543" alt="Screenshot 2024-07-08 at 19 41 59" src="https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/6958f8ed-be58-4a97-8949-ae124ebb985b">

### Environment

```markdown
- FlutterFlow version: v4.1.64
- Platform: MacOS, Web
- Browser name and version: n/a
- Operating system and version affected: n/a
```

### Additional Information

Issue creates a memory leak of endless listeners being generated

**Comment by Alezanello** [comment]
Hello!

I've been trying to replicate this issue using a new blank project without any success. The images you shared are very detailed in explaining how to prevent this, but first, I need to validate that this is not a project-specific issue.

Could you please create a new blank project, reproduce all the steps, and share the bug report code with us? Alternatively, if you prefer, you could record a small video showing exactly the memory leak caused by this issue.

Thank you very much in advance!<br>Azanello

**Comment by smn-snkl** [comment]
I can't create a new Firebase project from the FF UI at the moment, getting this error OAuth error
![Screenshot 2024-07-10 at 11 23 34](https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/af0c0023-312f-4c85-b921-23e482df731e)

In the new project you created, you do see though that there's a listener added to the Firebase StreamListener using cascading notation `..listen`, right?

And the problem is just that this listener never gets cancelled anywhere. So every time the widget is initialized, a new listener gets created

**Comment by rzambroni** [comment]
@smn-snkl, that error when creating the Firebase project is a known issue on the desktop apps. You can still create a new firebase project from [the WebApp](https://app.flutterflow.io/)

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by azizirac** [comment]
I found the same issue. On data change adds a "listener" which is not disposed when user changes pages and creates memory leak. I am using it in my custom nav bar to update the notification counts in my app state. Each time I change page, there is a new instance of navbar and so the page that contains it.

**Comment by LeCause** [comment]
I am facing the same issue when implementing a chat functionality. The chat window itself has an on data change listener to mark incoming messages as read when having the chat open. Navigating back to the overview of chats or any other page (or even changing to another app; android), all incoming messages are still marked as read as the on data change listener remains active.
