### ISSUE TITLE
Signature URL widget variable cannot be set multiple times on the same page without crash

### ISSUE THREAD

**Issue by cooldude1010** [FlutterFlow/flutterflow-issues#3343]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an app that requires multiple signatures on the same page. Unfortunately, this causes the app to crash. Renders my entire app useless, as this is a feature that all competing apps have already implemented and is necessary to the app.

There is no way to set a different signature URL variable for each different signature widget, nor is there any workaround using actions(not that I could find at least)

### Expected Behavior

Multiple people should be able to sign on the same page, and all signature urls should be able to be uploaded into the same document.

### Steps to Reproduce

1. create new page
2. add multiple signature widgets
3. set up actions to upload the signature urls to document one at a time
4. test app
5. app crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kk+fl+YlIrsdF7arPbe1Fq2AXNkw2TL03pu0bFEggGLbrBIYMaeClXxFVOdO+YWxDKEWJrE4Dw+DVi/PxGsIpMgeafbpfzZNySgLMQmO/aovTDaW0enJ7EdFWN2Ki0p+NpSZCAO9ZSC0S206UBt+QaDfsO5P6Zwh9f6PHaOI=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/69475579/b0773fc2-4c83-4112-813f-054bb9199ff9

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Web
```

### Additional Information

I know other people have had similar problems, and this is a huge issue as it makes the signatures widget completely useless in so many cases. This bug should be an easy fix, and it should be a priority.

If anyone has encountered this issue and found a workaround, please let me know.

**Comment by Alezanello** [comment]
Hello!

We are sorry you are currently facing this issue. The good news is that someone else recently reported the same problem, and we have added it to our backlog to fix it!

We will close this issue as a duplicate, but if you encounter anything else, please let us know. Any updates regarding the fix will be posted here: [FlutterFlow Issues #3327](https://github.com/FlutterFlow/flutterflow-issues/issues/3327).

Thank you for your understanding.

Best regards,<br>Azanello
