### ISSUE TITLE
Platform Error on Devices 

### ISSUE THREAD

**Issue by Aging-Developer** [FlutterFlow/flutterflow-issues#3347]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the below is thrown on physical devices, when a user navigates through app quickly (up and down the navbar):

PlatformException(error, No active stream to cancel, null, null). Error thrown .
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:648)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at EventChannel.receiveBroadcastStream.<fn>(platform_channel.dart:688)

It seems to be when trying to dispose of something when it is already disposed or not completed, I have a suspicion it may be App State. 

It doesn't happen in debug, it doesn't happen in Android Studio, but does on physical devices, if I attach Android studio to physical device it doesn't happen... so only on physical devices (all of them).  I have enabled Crashylics on every action to see if its just in one place, but it is not, it appears to caused by speed of navigation, not a single page/widget.

If the user navigates up and down the navbar like a xylophone, then it happens.

### Expected Behavior

For these error not to be thrown.

### Steps to Reproduce

Create a complex app, and build on Stores, navigate up and down the navbar like a xylophone, then it happens.

stack trace:

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, No active stream to cancel, null, null). Error thrown .
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:648)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at EventChannel.receiveBroadcastStream.<fn>(platform_channel.dart:688)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8shsrqx5NgoctZ1s7ide9VoGA5KW4/bZIaluwadw8gGJD2PewTe+D4RFNWUu7ma1NIHVr8jmYK+aHMhvKeUO0FExWsfJhh1oVXdwz/Vj6lVK2YOpOWZ3AmGtFTJhWz5J6rsBFAJfNzWE4S62aMH/CvQgzaQJjrNm1AG/mZNqbPs3yQAnrdUxZr4ygMDmreTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

It appears to be related to:  

https://github.com/flutter/flutter/issues/91782  
https://stackoverflow.com/questions/49387571/stream-subscription-throwing-an-error-in-dart-in-flutter-app

I wish I could give you more to go on, I have been trying for over a week to find a way around it. Any help would be greatly welcome, the guys on support chat were as confused as I am.

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

Throwing of these errors will cause Stores to identify app as low quality and may reject/remove app if not resolved. So for me this is business critical.

**Comment by paulperez-dev** [comment]
Hi @Aging-Developer! I tried running your app on a local device but got a different error: "**Null check operator used on a null value".** It was caused by the following element: 'Price String'.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4d16e7cf-815a-4e2e-9d7f-e66735967369/d12d2562-ccff-467b-93c4-1f9e835ad742?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZDE2ZTdjZi04MTVhLTRlMmUtOWQ3Zi1lNjY3MzU5NjczNjkvZDEyZDI1NjItY2NmZi00NjdiLTkzYzQtMWY5ZTgzNWFkNzQyIiwiaWF0IjoxNzIwNTc2ODA2LCJleHAiOjMzMjkxMTM2ODA2fQ.S-KYs12RrMtEsbieRSxilfi7nK7OAYQcZiyLdn1ioKc " alt="image.png" width="1062" height="560" />

Can you please verify it?

**Comment by Aging-Developer** [comment]
@paulperez-dev Hi, That pricing will show as not from google store, i have changed your account so you dont see that again.  The issue (which is only seen on devices running app from Play store) is:

PlatformException(error, No active stream to cancel, null, null). Error thrown .
at StandardMethodCodec.decodeEnvelope(message_codecs.dart:648)
at MethodChannel._invokeMethod(platform_channel.dart:334)
at EventChannel.receiveBroadcastStream.(platform_channel.dart:688)

An doesn't happen all the time, more when navigating fast around the app, or can be reproduced by navigating away from the Homepage after its been left for 10 minutes.

**Comment by paulperez-dev** [comment]
Hi @Aging-Developer! Do you mean the error is only happening on the released (prod) app?

**Comment by Aging-Developer** [comment]
@paulperez-dev   As far as I can tell (there might be ways of testing I don't know of, I am not a mobile/flutter guru, I am sure a guru could fix it), what I do know is its stopping app from going live (Google would either pick it up in review, or pull it for poor code quality) I have spend more than 12 months developing this app, so its something I need to resolve.

By the patterns of the error occurrences, I think to has something to do with flutter_flow_video_player.dart not disposing correctly when:

1. navigating away from a page that has video (asset) playing after user leaves it dormant for a while........ (something has cleared/stopped)
2. Navigating away from page with video (asset) playing, to another page with video (asset) playing......... (maybe multiple instances)

**Comment by paulperez-dev** [comment]
Thanks for the extra info! There is another report related to videos, let me check if this is related.

**Comment by Aging-Developer** [comment]
Hi, Any update on this?

**Comment by Aging-Developer** [comment]
@paulperez-dev Hi, Any update on this?

**Comment by Aging-Developer** [comment]
Almost definitely an issue with the disposing of video in  flutter_flow_video_player.dart.  To prove the point i changed the FF code to this:

  @override
  void dispose() {
    try {
      if (_subscribedRoute) {
        routeObserver.unsubscribe(this);
      }
    } on PlatformException catch (e) {
      String message = e.toString();
      if (message == "No active stream to cancel") {
        //print("No active stream to cancel");
      }
      else
        {
          rethrow;
      }
      _disposeCurrentPlayer();
      super.dispose();
    };
  }

And the issues are no longer logged by crashlytics, so would really suggest  the error is in the way videos are disposed of.

HOWEVER, This isn't resolving the issue, just covering up an issues, and will cause other issues later, so please can you investigate why this happening in the FF code.

**Comment by paulperez-dev** [comment]
Hi @Aging-Developer! Sorry for the late response. Thanks for the insights! Let me check on this and send it to ENG if applicable.

**Comment by Aging-Developer** [comment]
@paulperez-dev Hi, can you change it to the correct status then please, it is not "waiting for user response"

**Comment by paulperez-dev** [comment]
Hi @Aging-Developer! From your code the issue may be here: 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/77d3332c-3d28-4a26-8e7c-1f8d0ab4500a/47a88406-6836-4e17-97dd-001a3a831256?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83N2QzMzMyYy0zZDI4LTRhMjYtOGU3Yy0xZjhkMGFiNDUwMGEvNDdhODg0MDYtNjgzNi00ZTE3LTk3ZGQtMDAxYTNhODMxMjU2IiwiaWF0IjoxNzIyMzEwOTcwLCJleHAiOjMzMjkyODcwOTcwfQ.oHYdRu-yqEZmPQkfJv3cFzPiIg-c4DzWooDY_1_G94o " alt="image.png" width="744" height="346" />

Try disposing the widget differently (like disposing both controllers).

**Comment by Aging-Developer** [comment]
HI @paulperez-dev It does:

![image](https://github.com/user-attachments/assets/5accd04e-14f3-4454-968b-63e1cf70c520)

![image](https://github.com/user-attachments/assets/e644c233-1f0e-495f-93c9-73955b8a69da)

All the try blocks were added recently to 
try to stop the issue and to discover other issues with video player.  It used to just simply dispose of both controllers but the issue was there then, and still is.

**Comment by Aging-Developer** [comment]
it isn't stale, you are just ignoring it.

**Comment by Aging-Developer** [comment]
Typical FF support, ignoring it and hoping it goes away.

**Comment by paulperez-dev** [comment]
Hi @Aging-Developer! I'm not able to reproduce this issue. Are you able to get the same behavior from a blank project?

Note: The stale message is from a bot, it won't close the issue automatically.

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
