### ISSUE TITLE
Add App State Button disabled for Doc Reference Types

### ISSUE THREAD

**Issue by AhmedBashon** [FlutterFlow/flutterflow-issues#3348]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

on my project i want to use app state document reference to my cart page 
the create button is disabled and cann't create it 
![Screenshot 2024-07-07 130226](https://github.com/FlutterFlow/flutterflow-issues/assets/116435259/9367a474-fd50-45f7-8fe0-61b2e5dcea65)
  

### Expected Behavior

to create app state document reference 

### Steps to Reproduce

1. click on app state 
2. add app state variable 
3. select name for the app state
4. select data type (in this case is document reference)
5. select the source 
6. can not click on create because it is disabled

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lcn1z4VPxcdG1s+Ibfpajic5JW58ROY0m8JraCosfZT2BLMcec/RVERvOfW4Y1ZAOlqjp2oW0M7ouNjpGvldISWdfphM+odUdhXJTnuQR8nSFJWgfEd8Be9gCmqg56azgRJRNfVsc04C7F6mNtm9UgvdHpzLOFUaDq/LZO4=

### Visual documentation

![Screenshot 2024-07-07 130226](https://github.com/FlutterFlow/flutterflow-issues/assets/116435259/5c123e2e-4e19-4ffd-ae23-8ba5b3dab937)
the 
![Screenshot 2024-07-07 130400](https://github.com/FlutterFlow/flutterflow-issues/assets/116435259/a26539fa-4fe7-4ba6-972b-c68754e16f9a)
difference between two sitoution 

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: windows
- Browser name and version: google chrome
- Operating system and version affected: windows 11
```

### Additional Information

it lates me on my project 10 days so far

**Comment by Alezanello** [comment]
Hello!

This is a known issue that was introduced in the last release. The good news is that it will be fixed in the next release, which is expected to happen either tonight or tomorrow morning. We kindly ask for a little more patience.

I will close this issue as it is a duplicate report. If you encounter any new issues, please feel free to create a new report!

Thank you for your understanding.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Is working now!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/42e92131-2304-4d1e-ab7f-79f558069644/1d14d10a-3ac3-4dce-a31b-7e3c71d928be?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MmU5MjEzMS0yMzA0LTRkMWUtYWI3Zi03OWY1NTgwNjk2NDQvMWQxNGQxMGEtM2FjMy00ZGNlLWEzMWItN2UzYzcxZDkyOGJlIiwiaWF0IjoxNzIwNTQ4NzU3LCJleHAiOjMzMjkxMTA4NzU3fQ.2IoaezgZzL9FkDR7h9NdqEiVbmxwPqj1KqHH-4smXbM " alt="image.png" width="475" height="491" />
