### ISSUE TITLE
FlutterFlowCheckboxGroup Scrolling Issue

### ISSUE THREAD

**Issue by digitlab-techteam** [FlutterFlow/flutterflow-issues#335]
I have a CheckboxGroup in a column and the column is set to scroll. However when a user tries to scroll the page when holding their thumb over the CheckboxGroup the CheckboxGroup tries to scroll instead of the column.

It's happening on mobile devices, for Apple, Android and PWA's.

## Expected behavior (required)
The CheckboxGroup has no scroll thus I would expect the page to scroll even when a user holds his/her thumb over the CheckboxGroup and scrolls.

## Current behavior (required)
When holding your thumb over the CheckboxGroup the CheckboxGroup tries to scroll instead of the page.

## To Reproduce (required)
1. Create a page
2. Add a Column make it scrollable
3. Add a container to the column
4. Add a CheckboxGroup to the container (This step can be omitted)
5. Add options to the CheckboxGroup
6. Add extra content to the page so that the page is longer than the screen height
7. Download the project
8. cd into the project
9. Build the project to a connected device (flutter run)
10. Navigate to the page
11. Place thumb anywhere on the page other than the CheckboxGroup, scrolling will work as expected
12. Place thumb over CheckboxGroup and scroll, the CheckboxGroup itself will try to scroll instead of the page.

### Bug Report Code (required, generate from Widget Tree)
IT4ki/Hq24lOn7xY17X5be1F9SkXNUN9TLJEpu0bWUkbGO/4P+wAfvT8YRBDQsCzaH5IDVKjhTkxpq3FiYflNPUEPgqCY65a1KtuaVyjEA8=

## Context (required)
Users are experiencing the UX as broken because they feel they should be able to scroll whether they have their thumbs over the CheckboxGroup or else where on the page.

## Screenshots / recordings
https://user-images.githubusercontent.com/112875533/211571840-f82c0375-afc8-46f9-b384-bc4b43d0d56f.mp4

## Your environment
* Version of FlutterFlow used: V3.0 December 30, 2022 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome Version 108.0.5359.124 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Desktop: MacOS Ventura 13.0 Mobile: iPhone 13 iOS 16.1.1

**Comment by yoheisoito** [comment]
@digitlab-techteam thank you. Yes we have confirmed this issue on web and on iOS. 

@agreaves: 
We can consider resolving this by adding NeverScrollableScrollPhysics in FlutterFlowCheckboxGroup.

  Widget build(BuildContext context) => ListView.builder(
        physics: const NeverScrollableScrollPhysics(),

**Comment by digitlab-techteam** [comment]
@yoheisoito do we maybe have a ETA on the resolve of this?

**Comment by yoheisoito** [comment]
@mravani2 unfortunately, I am not able to give you a determined ETA on this. 

@agreaves Do you think you can include NeverScrollableScrollPhysics in FlutterFlowCheckboxGroup? 
As @mravani2 suggest, I'd assume that this is the assumed behavior.

[in FlutterFlowCheckboxGroup]
Widget build(BuildContext context) => ListView.builder(
physics: const NeverScrollableScrollPhysics(),

**Comment by wenkaifan0720** [comment]
Hi @yoheisoito. I think adding a `NeverScrollableScrollPhysics` is the way to fix this issue. I'll create a PR for it. Thank you!

**Comment by digitlab-techteam** [comment]
All sorted, thank you for fixing.
