### ISSUE TITLE
Edit text translation on component parameters inside a Walkthrough is broken

### ISSUE THREAD

**Issue by joaocordeiro-dotted** [FlutterFlow/flutterflow-issues#3350]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unable to edit the translation options for a text passed as a parameter in a component used in the walkthrough. The error 'error encountered finding translations' is displayed.

### Expected Behavior

It should be possible to edit the available translations for the given parameter. In my example, English and Portuguese

### Steps to Reproduce

1. Create a component with a string parameter
2. Create a walktrhough
3. Add a new step using the component created
4. Pass parameter
5. Mark Edit translations option

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlMmB2892odxE7rrIK8ZvnjwwGUALa+dI0tZ+TQ0jF5D4OrMUY86lXFptTb2zaHx+M1r+uzoxpvD0i/zyUvJcGAqVfqZG1pNQFBPPbH+XbKnSCbqWVUclI99bGB2e1JiZrx15PtBpLXAN2FOMe9myfz+Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1016" alt="Captura de Tela 2024-07-09 às 14 01 34" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168860662/fbaba72b-2203-4b5e-bbb7-f239360b3f9d">

### Environment

```markdown
- FlutterFlow version: 4.1.69
- Platform: Desktop
- Browser name and version: Google Chrome
- Operating system and version affected: MacOs
```

### Additional Information

I'm trying to finally use the walkthroughs, but got this problem, unfortunately.

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
