### ISSUE TITLE
Flutterflow freezing randomly after the update 30 mins ago

### ISSUE THREAD

**Issue by ValetCEO** [FlutterFlow/flutterflow-issues#3351]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the update about 30 mins ago I've been getting Flutterflow freezing and becoming unresponsive. I don't get an unresponsive notification but the whole page is frozen. Not really a reproducible bug but wanted to alert as it only started happening after the recent update.

### Expected Behavior

Not freezing

### Steps to Reproduce

Unable to reproduce with any specific action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcrqw5VOsdhE7c+BbPowoDwWHG4jRYEn1usbGAk0N5PNCJkQO8nTXFJWXf25dkFmfU2JpD4e063Qm9z1FPAnOQSdY7pbzKtyEgrMeHimWrKwPKisekRUGshUfGqe5p2juBVDNvBoWEZg7XGMO+7IEnfrN5DEC0dMDs//DJvXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

Unable to provide any as it's the same screen as usual just frozen

### Environment

```markdown
- FlutterFlow version: 4.1.69
- Platform: Mac (web)
- Browser name and version:Chrome
- Operating system and version affected:
```

**Comment by ValetCEO** [comment]
Update on this one - It just happened again but this time the whole screen just went grey (dark grey) - Again it didn't crash the browser tab just Flutterflow (This Is the editor I'm talking about in case it wasn't clear in the original message)

**Comment by ValetCEO** [comment]
<img width="1680" alt="Screenshot 2024-07-09 at 20 14 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/ae819ad6-4794-4756-b140-5c5742ed42a5">

**Comment by alex-bk-brl** [comment]
We are facing a similar issue since we were forced to update the FlutterFlow Mac client. Our App is very slow and laggy in the local test mode (started from the Mac client) - same issue also happens when we are using the web app (even worse). But when we publish our version to our domain, there are no such issues. We also downloaded the code and tested it through IntelliJ - also no issues. We strongly believe that there is no issue within our code - it all started with the update.

Update: We just tested locally using macOS from the device selector. Works perfectly fine as well - might be an issue with Chrome?

**Comment by bloemy7** [comment]
We are seeing the same issue - test mode is extremely slow, but when we push it to deploy it works. Can this be investigated? Thanks!

**Comment by ValetCEO** [comment]
Is anyone looking into this???

**Comment by tiagosilveiransj** [comment]
i've just opened a Ticket, maybe we are talking about the same issue. Open your devtools and check if you see an error similar to **TypeError: Instance of 'SOME_TYPE'>': type SOME_TYPE' is not a subtype of type 'X'** or something like "**Assertion failed: file:///sdks/flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart:200:12 dart_sdk.js:37972 Error debug serializing parameter: NoSuchMethodError: 'toDebugSerializableMap' method not found Receiver: Instance of 'JSArray<SOME_TYPE>' Arguments: []**"

https://community.flutterflow.io/ask-the-community/post/error-debug-serializing-parameter-nosuchmethoderror-DWIkRuaj3sPQBms

**Comment by tormundgerhardsen** [comment]
> We are facing a similar issue since we were forced to update the FlutterFlow Mac client. Our App is very slow and laggy in the local test mode (started from the Mac client) - same issue also happens when we are using the web app (even worse). But when we publish our version to our domain, there are no such issues. We also downloaded the code and tested it through IntelliJ - also no issues. We strongly believe that there is no issue within our code - it all started with the update.
> 
> Update: We just tested locally using macOS from the device selector. Works perfectly fine as well - might be an issue with Chrome?

Same issue here, with an extremely slow and laggy app in iOS simulator after the update. No changes to the app itself. Before I saw this issue, I also reported this on the community pages: https://community.flutterflow.io/c/bugs/post/extremely-slow-test-mode-after-v4-1-70-upgrade-nRtiZVJtE1T6q7n

**Comment by paulperez-dev** [comment]
Hi @ValetCEO! So sorry you are facing this issue. Can you please share the console log?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
