### ISSUE TITLE
Many errors when using LottieAnimation for Web

### ISSUE THREAD

**Issue by SebyOnGitHub** [FlutterFlow/flutterflow-issues#3352]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Today I updated FlutterFlow, now I can't run Test Mode anymore because of the Error.
Plus there are serval deprecated warning when creating a new Project.

### Expected Behavior

Should run like the previous versions.

### Steps to Reproduce

1. Create a new Project
2. Enable Web on Platforms
3. Run Test Mode for Chrome (will still run Test Mode but will give the following warnings)
-> Warning: In index.html:66: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
-> Warning: In index.html:51: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.

4. Add a LittieAnimation into the column
5. Run Test mode for Chrome (no longer compiles)
-> lib/pages/home_page/home_page_widget.dart:1:8: Error: Error when reading 'lib/flutter_flow/flutter_flow_lottie.dart': The system cannot find the specified file.
+ Many more errors, see screenshot

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lPHqy4Z2ocNY0Lrucu9anjwWQls7U5IrmOsbFA08J5zKB+wAYvf7P1FWTLy/YAk/PGK0mmAz/PfqiuHXOMICGxKcbbV8zKtQFAzvcGShbqXRO5GBfW1SL5hXIEyl56SrhyVSPs1hdFpl72aYNequSjLdQ+fGPUYZGcqbJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Here is the bug report code:
(the german part means: The system cannot find the specified file.)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121340272/e0069b70-7a91-43c2-8735-bea4225f7881)

### Environment

```markdown
- FlutterFlow version: v4.1.69+ released July 9, 2024
- Platform: Windows (But compiled for Web)
- Browser name and version: 122.0.6261.129
- Operating system and version affected: Win10
```

**Comment by FCMHUB** [comment]
Same here

**Comment by jakubmichalski** [comment]
I can confirm the issue occurs during compilation of iOS and Android: flutter_flow.lottie.dart No such file or directory
FlutterFlow v4.1.69 released July 9, 2024
Flutter version is 3.22.2, on macOS 14.5 23F79 darwin-arm64

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by ayjayem** [comment]
Issue here too.

**Comment by viniciusgersen** [comment]
Same issue here.

**Comment by ken604** [comment]
Same here.

**Comment by laughingbuddha24** [comment]
I have this issue too. Urgent fix needed pleaese as I can't load local run testing or browser testing.

**Comment by byrondowns** [comment]
Same issue here, wont build to ios simulator

**Comment by rajika97** [comment]
Same issue here. Can't do local run on both android and iOS

**Comment by nvimalraj** [comment]
Problem seems to be because Web generated code is using import 'package:lottie/lottie.dart'; while the MacOS is using import '/flutter_flow/flutter_flow_lottie.dart';

And in MacOS the flutter_flow_lottie.dart is missing in the lib. 

This is impairing the planned development

**Comment by ken604** [comment]
An annoying workaround for now is to remove all Lotte components during testing and re-add them back before deployment.
Only feasible if you have only a few animations.

**Comment by vetxi** [comment]
Same here

**Comment by vetxi** [comment]
Same here. Also happening in ios local run.

Error (Xcode): lib/user/folder/page/page_widget.dart:9:8: Error: Error when reading 'lib/flutter_flow/flutter_flow_lottie.dart': No such file or directory

Could not build the application for the simulator.
Error launching application on iPhone 15.

**Comment by KevDev99** [comment]
Same here. 
flutter_flow/flutter_flow_lottie.dart: No such file or directory
<img width="751" alt="Screenshot 2024-07-10 at 11 15 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/9c789272-99a9-4e05-8c27-4a3ae6ba00d4">

**Comment by Abdulexjr** [comment]
Same here

Flutter_flow_lottie.dart is missing in latest update.
