### ISSUE TITLE
File missing in ios/Runner in download code

### ISSUE THREAD

**Issue by PMFlis** [FlutterFlow/flutterflow-issues#3353]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i try to run the downloaded code in vs code i get the error that a file  ios/Runner.xcodeproj/project.pbxproj is missing. The issue appeared after latest update. 

### Expected Behavior

To have all the files in the downloaded zip

### Steps to Reproduce

- download the code
- try to sign and build on ios :
open ios/Runner.xcworkspace ( an error should appear)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/1sIZgobxc+Kn+bPlFmSkRCUMdXOczitVEew4bCIj4Ou0hOuClVFZWZNyzaHxEImH+u3EJ7s7rvuPpLfY5PgSbRoBNzbpUWBPPbGGiMqqhPbqOOnNCO8BUG3aG0ImCkCRCGNNtWmAA3GaIFdm+RT2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1470" alt="Screenshot 2024-07-10 at 00 34 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/74993843/1276320c-b683-4381-a7cb-f0702b4ac158">

### Environment

```markdown
- Project: Storme
- FlutterFlow v4.1.69+ 
- Flutter version is 3.22.2
- Platform: ios
- Browser name and version: Chrome
- Operating system and version affected: MacOs
```

**Comment by msusviela** [comment]
Hi @PMFlis. I downloaded your project and could make a build on ios.<br>Have you tried with the following commands in the VSCode terminal:

```
flutter clean 
flutter pub get
```

If it doesn't work, please try with this in the terminal:<br>pod install

Running `pod install` is a common step in iOS development to ensure that all CocoaPods dependencies are installed correctly.

Let me know if the issue still persists for you

**Comment by PMFlis** [comment]
Hi @msusviela, I run all of that above and the error about missing file persists. I sent the zip to my colleague to try to build it and he encountered the same problems; here is his summary:

- open the folder with vscode
- edit pubspec.yaml for the right build version
-> version: 1.0.0+48

- open ios/Runner.xcworkspace
To select my certificate to sign the app for ios we get the message:
Failed to load container for document at url: file:///Users/gregoireriviere/Downloads/storme47/ios/Runner.xcodeproj

Same error if i try to do a:
flutter clean
flutter pub get

Note that this error is only happening since the last update of flutterflow. 

When we try to run pod install we get the error:
[!] The plist file at path `/Users/gregoireriviere/Downloads/storme47/ios/Runner.xcodeproj/project.pbxproj` doesn't exist.
We always build the same way and we never had this problem before the yesterday's update;

**Comment by caringan** [comment]
I am encountering the same issue as well where the /project.pbxproj doesn't exist in Runner.xcodeproj in downloaded code, make it not possible to run it locally. 

I have encountered the issue 2 weeks ago, (at some point 50% of the build downloaded has this issue, and 50% of the build works fine, it almost seems intermittent which is kinda annoying). Support told me it was fixed and it worked great for the past week but the issue is coming back again. 

<img width="385" alt="Screenshot 2024-07-10 at 4 01 23 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/68417491/9c98be66-3d1a-49e3-ac38-95943a4e17ca">

**Comment by AnandNeo87** [comment]
Tried downloading the code, ios/Runner.xcodeproj/project.pbxproj doesn't exist.

**Comment by caringan** [comment]
I downloaded the FF desktop app and run Local Run to bypass the issue. If anyone's still stuck on this :)

**Comment by PMFlis** [comment]
I am using as well the Local Run so I can go ahead an develop the app but cannot build the ios and ship to the apple store as these files are required to sign and build. At least no troubles with android.

**Comment by adamblanchard** [comment]
I just got hit with this bug too. Seemingly out of nowhere. Now my downloaded code seems to be missing these files. I've also tried the suggested clean commands and am stuck.

**Comment by PMFlis** [comment]
@caringan @adamblanchard @AnandNeo87 @msusviela just to let you know that with the new version of FF v4.1.71, the bug is gone and the file project.pbxpro is not missing anymore.
