### ISSUE TITLE
Wrong calc

### ISSUE THREAD

**Issue by gabdreux** [FlutterFlow/flutterflow-issues#3354]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Button that calculates the value of the Pressure (MPa) X Volume input (M³).
When I enter 10 (MPa) x 10 (M³) it returns 100 correctly. But when I pass, for example, 0.09 x 10, it is returning 0.89 instead of 0.9

Project ID: monitor-13-8955ij

### Expected Behavior

Should return 0.9

### Steps to Reproduce

On the "Equipamentos" page, filter by "Tubulação Interligando Vaso de Pressão". Click on the blue "house" icon that shows the text "Iniciar Aplicabilidade da NR13" when hovering.

Answer everything "Não" until the Pressure and Volume fields appear. Put pressure of 0.09 MPa and volume of 10 M³

Observe the result in the "PV" field.

![Captura de tela 2024-07-09 200610](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/d07c0ad9-bfcb-4405-9e0f-f63ace6be340)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/58b4737d-706a-4a65-ba66-318f2ec56381)

![Captura de tela 2024-07-09 200912](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/5dc7125a-68d0-4419-8959-461987f93d75)

![Captura de tela](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/0866da81-68b2-49f3-b299-ae9ba45aa00e)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/39261a73-9613-4802-8a37-2bde8fbd0a14)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi8mAvI9IsbRJ+Kn9Y+9Wq2U7JVw/aL00st5Hd0gdCOPrBqQuPPfRcktpYNegaVNcD06Ljns13PTpjYfPN/I6HxOtfb0/z6lidjz0e2iiVrmbDs2OY2skGe1jf2rA0KeN2B14HPJZSVom2lyUHe/IaDDDFOu/Zwh9f6PHaOI=

### Visual documentation

![Captura de tela 2024-07-09 200610](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/d07c0ad9-bfcb-4405-9e0f-f63ace6be340)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/58b4737d-706a-4a65-ba66-318f2ec56381)

![Captura de tela 2024-07-09 200912](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/5dc7125a-68d0-4419-8959-461987f93d75)

![Captura de tela](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/0866da81-68b2-49f3-b299-ae9ba45aa00e)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87443135/39261a73-9613-4802-8a37-2bde8fbd0a14)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.64+ released July 9, 2024
Flutter version is 3.22.2
- Platform:web
- Browser name and version: Versão 126.0.6478.127 (Versão oficial) 64 bits chrome
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Code Expressions allow for quick mathematical calculations without needing more complex code like functions. In this case, to get a more specific result, you need to round the result of a double. In Flutter, the best way to achieve this is by using the `toStringAsFixed` method on the double result of the calculation.

I recommend the following function:

```dart
// Perform the multiplication
double result = var1 * var2;

// Round the result to 1 decimal place
double roundedResult = double.parse(result.toStringAsFixed(1));

// Return the rounded result
return roundedResult;
```

Here is an image showing how it should be implemented:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/305ce5a3-9931-4eb7-bdf2-5149c0f48ebc/84d1cf4e-6d45-4402-b0cb-b8fa8404320d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMDVjZTVhMy05OTMxLTRlYjctYmRmMi01MTQ5YzBmNDhlYmMvODRkMWNmNGUtNmQ0NS00NDAyLWIwY2ItYjhmYTg0MDQzMjBkIiwiaWF0IjoxNzIwNjE1MzQ5LCJleHAiOjMzMjkxMTc1MzQ5fQ.lFeOck0lU1CMLYQgWzY4jB0mIVPMMg1XDv5QSGLx9CM " alt="image.png" width="1548" height="847" />

And the Test Results:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c9ce467f-2618-4bb1-9214-70dce20814dc/e749ca55-4ba9-41ee-a4fc-66950c0d19f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jOWNlNDY3Zi0yNjE4LTRiYjEtOTIxNC03MGRjZTIwODE0ZGMvZTc0OWNhNTUtNGJhOS00MWVlLWE0ZmMtNjY5NTBjMGQxOWYyIiwiaWF0IjoxNzIwNjE1MzQ5LCJleHAiOjMzMjkxMTc1MzQ5fQ.C16oDa7TqVn6Px8skhbAY_cr8SCvn7Wc0niv6dwj4KI " alt="image.png" width="846" height="601" />

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
