### ISSUE TITLE
Build fails anytime I include a simple search (No Project Errors)

### ISSUE THREAD

**Issue by MrMCostello** [FlutterFlow/flutterflow-issues#3355]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Any time I include a simple search in my app and it in try test mode the build fails. It works fine in the when I run it as a web app. 

### Expected Behavior

Everything should be working fine. I have tried simple searches in many different ways and it reproduces the same outcome. 

### Steps to Reproduce

1. Add simple search to current page.
2. Launch Test Mode
3. Build Failed
4. Launch web version
5. Search works
6. Create new page
7. Create simple search of different information
8. Build Failed
9. Launched web version
10. Search works

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

63 packages have newer versions incompatible with dependency constraints. Try `flutter pub outdated` for more information. Launching lib/main.dart on Web Server in debug mode... Waiting for connection from debug service on Web Server...         Error: Couldn't resolve the package 'text_search' in 'package:text_search/text_search.dart'. lib/exper/exper_widget.dart:9:8: Error: Not found: 'package:text_search/text_search.dart' import 'package:text_search/text_search.dart';        ^ lib/exper/exper_model.dart:10:8: Error: Not found: 'package:text_search/text_search.dart' import 'package:text_search/text_search.dart';        ^ lib/exper/exper_widget.dart:283:54: Error: The method 'TextSearch' isn't defined for the class '_ExperWidgetState'.  - '_ExperWidgetState' is from 'package:dollar_auction/exper/exper_widget.dart' ('lib/exper/exper_widget.dart'). Try correcting the name to the name of an existing method, or defining a method named 'TextSearch'.                         _model.simpleSearchResults = TextSearch(                                                      ^^^^^^^^^^ lib/exper/exper_widget.dart:286:45: Error: The getter 'TextSearchItem' isn't defined for the class '_ExperWidgetState'.  - '_ExperWidgetState' is from 'package:dollar_auction/exper/exper_widget.dart' ('lib/exper/exper_widget.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextSearchItem'.                                 (record) => TextSearchItem.fromTerms(                                             ^^^^^^^^^^^^^^ Unhandled exception: Null check operator used on a null value #0      IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:233) the Dart compiler exited unexpectedly. Waiting for connection from debug service on Web Server...         35.9s Failed to compile application.

### Visual documentation

![build failed](https://github.com/FlutterFlow/flutterflow-issues/assets/175166518/3ab9be68-00d6-4d0b-8a46-0bcca6cb0505)
![simple search](https://github.com/FlutterFlow/flutterflow-issues/assets/175166518/edbbc842-1043-45a9-a717-767c08ee8e84)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.69+ released July 9, 2024
  Flutter version is 3.22.2
- Platform: App
- Browser name and version: Chrome or app
- Operating system and version affected: Windows and Mac
```

**Comment by MrMCostello** [comment]
Oh and I also want to add that their are no project errors
![no errors](https://github.com/FlutterFlow/flutterflow-issues/assets/175166518/60e47244-19e8-41e6-b377-e29e5498506c)

**Comment by Alezanello** [comment]
Hello!

I will take a look at the issue by trying to replicate it in a new blank project. In the meantime, could you generate a Bug Report Code so we can access your project to see if this issue is project-specific?

To do this, please go to the page where you have set the Simple Search, right-click on the Scaffold (base page widget), and select "Bug Report Code."

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2b21afa6-13e4-4d1e-ad01-02580f54ab29/001b7572-3ca0-4429-b8b7-7e9d5feb4870?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYjIxYWZhNi0xM2U0LTRkMWUtYWQwMS0wMjU4MGY1NGFiMjkvMDAxYjc1NzItM2NhMC00NDI5LWI4YjctN2U5ZDVmZWI0ODcwIiwiaWF0IjoxNzIwNjE1NjA2LCJleHAiOjMzMjkxMTc1NjA2fQ.N7X1sAXJ724Nye-OZbpfFdn9rZBn54EgjS6zCGOzsrY " alt="image.png" width="398" height="343" />

Thank you!

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Hello again!

I wanted to let you know that I was unable to replicate the issue despite trying various methods. In Test mode, Web Publish, and local runs, everything works fine for me. I also created pages rapidly to check for any delay in adding the package to the project, but encountered no issues.

Could you please send me the Bug Report Code at your earliest convenience so I can check the project more thoroughly?

Thank you!

**Comment by MrMCostello** [comment]
IT4wlMmA8Yx1rsRE7aXuc8dFoCYXGDo1argomMEaQis8GZT0B4kcYs+kfklUOO2rdwhUJ1mkrHgX/MrmjvOSGvY6NSScGL1zzaV6UhbMQmK7Ra6rEK63b3J6BcdVBXXF1quRmhN5JrNpdU0j7U2ALuqvEj/fH5jwOm4RNea4XdeK2SrDX1iXc2URm05KZDPz

**Comment by MrMCostello** [comment]
Above is the bug report code

**Comment by gameskysite** [comment]
Same For Me.

**Comment by Alezanello** [comment]
Perfect!<br><br>Going to take a look on it!

**Comment by Alezanello** [comment]
Hello!

I just ran the project you provided without any issues. Has this been fixed after the latest FF update? Is everything working fine on your end now?
