### ISSUE TITLE
Existing Alert Dialogs No Longer Show Selected Components to Display

### ISSUE THREAD

**Issue by ayjayem** [FlutterFlow/flutterflow-issues#3356]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Existing actions to display alert dialog components no longer show the selected components, per the screenshot below. My project still appears to build and run just fine in web app testing though, so maybe this is just a UI issue (given the Lottie animation bug currently outstanding, I can't test this behavior on a real device).

### Expected Behavior

Should see the selected component in existing alert dialog actions.

### Steps to Reproduce

1. Open an existing project.
2. Navigate to an action to display a component to see that it fails to show the previously-selected component.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlfLqy4ZNocNc+KXqc8cxpGU7M0McWOdEl+tuZwgbIoznBqQlO878ahdoXsuiaVNcHE2kgmIxwtmPj4XDEPQpCxaBbL5G1sx6Sg/0e2iWV5fTPZC7dnRCIJ5mIECv14mjogl5HLNuWk4G2zmUOtivYALDBOu/Zwh9f6PHaOI=

### Visual documentation

<img width="1239" alt="Screenshot 2024-07-09 at 8 56 48 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16900187/2604022a-15be-4702-a010-126ac0bdea8c">

### Environment

```markdown
- FlutterFlow version: 4.1.69+
- Platform: Web
- Browser name and version: Chrome 123.0.6312.58 
- Operating system and version affected: macOS Sonoma 14.3.1
```

**Comment by guillediazru** [comment]
I can confirm this, this also happens on the desktop windows app and web, i can not longer see the selected custom dialog. Seems to be "working" because i can test it as webapp.

**Comment by khomya** [comment]
I have the same bug on all of my custom dialogs.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this issue to our attention!

I checked previous test projects where I had components selected, and it appears that the visual indication of the selected component is missing. However, the variables sent to the component are still intact.

I am forwarding this issue to the engineering team so they can work on a fix.

Thank you again for your help!

Best regards,<br>Azanello
