### ISSUE TITLE
Creating a branch from main is not using latest version of main's code

### ISSUE THREAD

**Issue by patescher** [FlutterFlow/flutterflow-issues#3357]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In FF web interface, while I'm in Main branch, I select Create New Branch. After naming it, the new branch opens, but it appears to be an old version of my main branch, because it's missing many custom functions/actions/widgets compared to the Main branch. Tried deleting the new branch and repeating workflow with the same end result.

### Expected Behavior

Expected new branch to be an exact copy of the main, including all custom code.

### Steps to Reproduce

1. Select Main branch
2. Create new branch
3. Name new branch
4. Load new branch
5. Check Custom code
6. Identify that custom code is missing functions that appear in Main branch

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ki+flzItNpbxK7c7yafpvmSQXIjt9RY08lsEbbww2GO/rG7YMS8+kMxJVXemndGNEL2ejhn81+trKhs7mA+UqBzSac6p6+bhuTAuUUT+hWpSsCpaSeUdtJ+hJJVyD0LSrhBRTHPJhWVYE2V+qB9i9fAvvGITbOFgFQ8qkOtj7n12qQ0SLb3kNh1JWeC/v

### Visual documentation

N/A (custom code is confidential)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.69+ released July 10, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome Version 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.5 (23F79)
```

### Additional Information

Severe impact - Unable to use branching feature which is having significant impact on speed of development

**Comment by kiptoomm** [comment]
I have experienced a *similar* issue where the new branch is set up as a new project. This causes some problems:

* The new branch is disconnected from GitHub - it seems to require me to set up a new integration. When when I click on the "Developer Menu" -> "Connect GitHub Repo" option, the mouse action on the text field is actually disabled
* Web publishing doesn't work anymore. The alert error is raised: `'Error reserving subdomain: Subdomain "<my-project-subdomain-name>" is already used by another project'`

Naturally, I reached out to the FF support through the in-app chat, but I haven not received any meaningful help on there. The support person has ignored my messages or doesn't seem to understand what is going on :( @FlutterFlowEng please help

**Comment by Alezanello** [comment]
Hello @patescher  !

Thanks for bringing this issue to us, i'll take a deep look and return with (bad/good) news!

@kiptoomm  Your case seems to be very different from the main one, is more likely in how to use or not the branchs, to have a deeper look to this and help you in your specific case, could you please generate a new Github Issue with ALL the details like the Bug Report Code generated from your project? 

Thank you !!

**Comment by Alezanello** [comment]
Hello again!

I successfully replicated this issue. <br>Thank you very much for bringing it to our attention. <br><br>I will escalate this to the engineering team as an urgent matter for them to fix.

Best regards,<br>Azanello

**Comment by tomkosmita** [comment]
@Alezanello 
More insight from my side - perhaps this will help also:

In my case I noticed that primarily collections has definitions that looks like from months ago - meaning data models are old nad some attributes are different or missing comparing to MAIN branch.

Tried several times with different settings it looks like that branch has consequently the same wrong collections definitions from past (its not random).
This completely blocks application development and requires urgent attention please.
Tom

**Comment by patescher** [comment]
@leighajarett can you please clarify why this was closed as 'not planned'?

**Comment by mordskerl1974** [comment]
I have the same problem. Why was this ticket closed? 
branching is useless as long as this issue is present
@leighajarett

**Comment by leighajarett** [comment]
Hi! This issue was closed because we fixed a duplicate issue (we marked as duplicate in our internal system, which for some reason shows up as "Not Planned" here). Sorry it wasn't more clear!

This issue has been resolved. If you are experiencing an issue can you please create a new one with your project details so we can reproduce? 

Thank you so much!
