### ISSUE TITLE
Video player not work (Chewie package is not found)

### ISSUE THREAD

**Issue by aaksa** [FlutterFlow/flutterflow-issues#3358]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot use video player

### Expected Behavior

i can run the test mode for displaying video player

### Steps to Reproduce

create new page, create video player widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8/f34ZOobRJ7q6JL/pvlWU7G0McT5MnktVudw4sCKL2O4kQdvWkM01CZ9+4SnxqPUSmmnIK+tbwivLpEMECHzucbKZb1c92cQ3NfH6XUZOBBZOeeXAlM5tYfxCO5LWK3CRSXc9YWFIa7U66Cum9dD/sH7rrImdISq/LZO4=

### Visual documentation

<img width="905" alt="Screenshot 2024-07-10 at 22 46 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/61930109/2b8b549b-5c74-41a7-a848-48a2999a9875">

### Environment

```markdown
- FlutterFlow version: v4.1.69+ released July 10, 2024
- Platform:Web
- Browser name and version: Chrome (Version 126.0.6478.127 (Official Build) (arm64))
- Operating system and version affected:  MasOS 14.5 (23F79)
```

**Comment by msusviela** [comment]
Hi @aaksa. I wasn't able to reproduce the issue neither from blank or from your project. I saw in the environment issues that you are using the v.4.1.69+. Now the v4.1.70+ version was launched with some fixes regarding missing package dependencies that could be related to that. Can you please reopen FlutterFlow with the new version and check if it works for you?

**Comment by aaksa** [comment]
Hi I reload the flutterflow but i still got the error.

**Comment by msusviela** [comment]
We are still not able to replicate this on your project, it's building correctly for us. Had you tried cleaning the caché (Command + Shift + R on Chrome)?<br><br>If the issue is still there, could you please tell me if that widget works on a blank project for you?
