### ISSUE TITLE
API groups showing the long gray screen of death 

### ISSUE THREAD

**Issue by NickMalonzo** [FlutterFlow/flutterflow-issues#3359]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In all of my projects, inside of an API Group, when clicking the Advanced Group Settings, it shows a big gray screen and not the actual settings like it should. This seemed to only happen after I updated to the latest version. Possibly the new API streaming update.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/171990046/865b2909-f798-4d38-bfeb-4298f9a6c194)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/171990046/081fd710-41b0-4952-b595-5b0b239ff3de)

### Expected Behavior

It should show the Advanced Settings as it would before. 

### Steps to Reproduce

1. Go to API Calls
2. Create or View an Existing API **Group**
3. Click Advanced Group Settings
4. Then it shows a big gray screen

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fivHlsMxOxcdC+KrqdcAwoD4XGDs1a+cF0+tuTQ4bIZfqPOx+PMzRdktJYsOGdwlIJFmj8XgK0qHLk/DPFMY4AE2qeYNe+ahiawrdfDqQMZS7CauSSWt6BfxbflS11J+omA9RIupuc0FhwGWPeuiQShXfQoTWPm4/Nc+JOp3Ln3CBGQDWVyZrwmNecCfn

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/171990046/865b2909-f798-4d38-bfeb-4298f9a6c194)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/171990046/081fd710-41b0-4952-b595-5b0b239ff3de)

### Environment

```markdown
- FlutterFlow version: 4.1.70
- Platform: Windows/FlutterFlow Desktop
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
