### ISSUE TITLE
Calling Zapier Webhook Fails 

### ISSUE THREAD

**Issue by sdschroeder** [FlutterFlow/flutterflow-issues#3365]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created an API call for a Zapier webhook and tested it within FF, Postman and webhook.site with success, but when I call it from an app it fails every time. It doesn't send an actual payload.

### Expected Behavior

I expect it to send the payload defined in the API call

### Steps to Reproduce

- Create a Zapier "catch" webhook step
- Create API call with variables, using the URL provided byZapier
- Add an action to a widget that calls the API and passes defined variables
- Test action in test mode or publish to web
- Review Zap runs in Zapier

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkufl0It2sdtZ0KrbbcdvvGM4Q2YkTL07ttYbZxUjIuPtBJh/dvfRU1huOPHkYENhHGGjnnwBpdrGv4XxOO4qGz+bGIM6+s0MFhXwIHq8RKbSCcyKP0dtL+1QG1SZ36aZhCRQAOtuSiVk7VyyCuiRHxXYJ5+/Zwh9f6PHaOI=

### Visual documentation

<img width="1158" alt="zapier-webhook-post-success" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118094992/48dc9728-997d-4b46-a389-ec0cd494048c">
<img width="660" alt="zapier-webhook-post-body" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118094992/b20e848d-ad26-4823-ace3-8f3475167a40">
<img width="646" alt="zapier-webhook-post" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118094992/9468a38f-d004-4ba1-9c4b-3c89b99594da">

### Environment

```markdown
- FlutterFlow version: 4.1.69
- Platform: Web
- Browser name and version: Brave 1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64)
- Operating system and version affected: Built in MacOS FF
```

**Comment by guillediazru** [comment]
Try it again but make the API call private within FF. I had issues with API in the past and solved it by making it private.

**Comment by Alezanello** [comment]
Hello!

I was able to reproduce the issue from your project. Just to be sure, can you open the Inspect tool in your browser, go to the Console section, and click "Resend Welcome Email" to see if you get the same error I'm seeing?

Currently, I'm getting a CORS issue. Making the API call private, as suggested by @guillediazru, can help prevent this kind of issue.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by sdschroeder** [comment]
Thanks for the tip on making a private call @guillediazru! This solved my issue!
