### ISSUE TITLE
You should be able to cancel the change of email address by deactivating the sent email or something else 

### ISSUE THREAD

**Issue by DanielCyran** [FlutterFlow/flutterflow-issues#3368]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a project based on FlutterFlow and Firebase.

There is one logical error when changing the email address in the user's profile.
The option to cancel the email address change before it is confirmed is missing.

### Expected Behavior

Why is this a threat? The user may enter an incorrect email address, and someone else could confirm it, leading to the user losing their account and someone else gaining access to it.

### Steps to Reproduce

The problem occurs after changing the current email address in the user's profile

There is no option to cancel this operation

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

d

### Visual documentation

everything was described above

### Environment

```markdown
FlutterFlow v4.1.65+ released June 29, 2024
Flutter version is 3.22.2
```

**Comment by Alezanello** [comment]
Hello!

This is a very valid point, and I will forward this to the engineering team as a feature request or improvement for our email change security system.

Thank you very much for bringing this to our attention.

Best regards,<br>Azanello

**Comment by DanielCyran** [comment]
@Alezanello  what can't you recreate? After all, when changing the e-mail address in the application, we cannot cancel the e-mail change

**Comment by Alezanello** [comment]
Hello Daniel!

I didn't say I couldn't recreate it; I mentioned that this is a Feature/Enhancement Request. I have already generated a ticket in the engineering team's backlog for this.

Best regards,<br>Azanello

**Comment by DanielCyran** [comment]
I thought you canceled the topic :)

![image](https://github.com/user-attachments/assets/1b03586f-0afd-4358-9b38-43d2d95baabd)

**Comment by Alezanello** [comment]
I closed the issue because this tracker is intended for bug reports, not Feature or Enhancement Requests. However, I did take your request and passed it directly to the appropriate team. I assure you that it is being addressed 😃

Best regards,<br>Azanello

**Comment by DanielCyran** [comment]
oki :D thank you :)
