### ISSUE TITLE
WebView error on Windows Local Run

### ISSUE THREAD

**Issue by KovalenkoAnton** [FlutterFlow/flutterflow-issues#3369]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I got a extreamly long error "A platform implementation for `webview_flutter` has not been set. Please ensure that an implementation of `WebViewPlatform` has been set to `WebViewPlatform.instance` before use. For unit testing, `WebViewPlatform.instance` can be set with your own test implementation.
'package:webview_flutter_platform_interface/src/platform_webview_controller.dart':
Failed assertion: line 26 pos 7: 'WebViewPlatform.instance != null'"

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72733870/a6bfafbc-9b95-4459-be53-1c398dfa32da)

### Expected Behavior

I was expecting a html widget with a simple "123" text for testing purposes
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72733870/0a92d5b7-f608-47a3-9c46-c50c21a27ec7)

### Steps to Reproduce

1. install **desktop** FlutterFlow app
2. add WebView widget
3. set there "load content from html"
4. enter "123" to Webview HTML Content
5. configurate Local Run for Windows
6. start local run for windows
7. open the page with WebView widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oismB05dgrt9J7ar2a/lahSQRH3o8aJ0ZkspBYyAjGJDJP4kQPPWkYRZpYMTiS2x6eESmmn4y+vzWhd/PJfEVBwqtRqZazYdQVRbKbF+ia5OBBs2wQ3NDMJ5TN36i5qbUqyVAGPJadV4Y32b2f97JdA3vNYzQImdISq/LZO4=

### Visual documentation

what is see in editor
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72733870/e76d0a2f-b891-48db-bb05-fce8e78d1e1a)

### Environment

```markdown
- FlutterFlow version: 4.1.71
- Platform: windows desktop
- Browser name and version: Opera One (111.0.5168.61)
- Operating system and version affected: windows 11 (23H2)
```

### Additional Information

I've tried to add "webview_win_floating: ^2.2.5" to \AppData\Roaming\FlutterFlow\flutterflow\ <project name>\pubspec.yaml and got a bit different error: "LateError (LateInitializationError: Local 'widgetParams' has not been initialized webview", but in this case I really don't know how to fix that.

p.s. I see "123" in web run mode, but web debug mode is throwing me a "Build failed" error

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by msusviela** [comment]
Hi @KovalenkoAnton. After further investigation, we found out that it's expected behavior.  It's because we use [this package](https://pub.dev/packages/webviewx_plus) and it only supports Android, iOS, and Web.

**Comment by KovalenkoAnton** [comment]
> Hi @KovalenkoAnton. After further investigation, we found out that it's expected behavior. It's because we use [this package](https://pub.dev/packages/webviewx_plus) and it only supports Android, iOS, and Web.

Hi! Got you. Should I expect any solution or it's imposible to add any another package to use webview (htmlview) for Win and MacOS?

**Comment by msusviela** [comment]
It's not planned at the moment. We'd filled file a feature request for that.
