### ISSUE TITLE
Name a table as "table" in Supabase produce a compilation error

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#337]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Build the project without problems

## Current behavior (required)

Produce a compilation error

## To Reproduce (required)

1. Create a table on Supabase and name as "table"
2. Get the schema on FF
3. Go to build o test the app and have a compilation error

### Bug Report Code (required, generate from Widget Tree)

IT4wz/Llw4x2pbxK0KX6cfpviiovIjsnbbs3kOpEbCs8GZT0B4kcYs+kfklUOdOnT39If2aggnEX/MrXiPDDUcdcPSiYRtx8zbpfWjyWTT6WV8XREZrlMS0ffaMKRSz+

## Context (required)

I want to have a table named as "table"

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/211619533-88507706-a12b-4835-9cc8-5c038f794c36.png)

## Your environment

* Version of FlutterFlow used: 29 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by bulgariamitko** [comment]
I think "table" is reserve name

**Comment by Franco98404** [comment]
Yep, I think the same. This is similar to this issue.

https://github.com/FlutterFlow/flutterflow-issues/issues/319

**Comment by agreaves** [comment]
Hi @Franco98404, thanks for the report! For now, I'm just adding a project error to tell the user they are using a reserved word if their table is called "table". This will be present next deploy.
