### ISSUE TITLE
In Firestore Schema Screen, duplicating sub-collection into top level collection forced to sub-collection

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#3371]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Open Firestore schema screen
2. Dupplicate users/someCollection
3. Name it and stay "Is Subcollection" un-toggled, push Create button
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/6b3cb619-7933-4081-a6e2-7f6979bab0bd)
4. Created under same collection, ie. "users/otherCollection"

### Expected Behavior

At current behavior #4. Created as top level collection, ie. "otherCollection"

### Steps to Reproduce

same as Current behavior

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfKB35ZJpbwG1c7qcsJWiQMxN0A5beRE1+1xRQkaNZD0EJwpWs+kalFtOPHiTwlUAVGZvDs1/87NvYflDfQ5GAyHbr1xyqluFA3KIUahbq6PCKqKdGt8AelYFUik15+RnxNQItNpdV1pig/GSw==

### Visual documentation

in Current behavior

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS Sonoma
```

**Comment by msusviela** [comment]
Hi @ryutosh. I noticed that you're using an outdated version of FlutterFlow. This issue is fixed in the latest version. Please make sure you're using the last one (4.1.70) and let me know if the problem still persists.

Thanks!

**Comment by ryutosh** [comment]
Hi, @msusviela 
Thanks for your reply. After I leave & re-enter editor screen, FF version was updated.
And now I can it is fixed in leatest version.
