### ISSUE TITLE
Package Not Resolved : share_plus.dart

### ISSUE THREAD

**Issue by botroad** [FlutterFlow/flutterflow-issues#3372]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While creating a new function with import 'package:share_plus/share_plus.dart';
// test mode getting failed with error // Error: Couldn't resolve the package 'share_plus' in 'package:share_plus/share_plus.dart'.
lib/custom_code/actions/s123.dart:13:8: Error: Not found: 'package:share_plus/share_plus.dart'
import 'package:share_plus/share_plus.dart';
       ^

### Expected Behavior

It should run in normal case, I have created new app and added package and its working perfectly, just issue with this specific project.

### Steps to Reproduce

// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/backend/schema/enums/enums.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:share_plus/share_plus.dart';

Future s123() async {
  // Add your function code here!
}
just creating this action is causing issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Si8/l24Z1pbxE1aXqYPpR/ScsKUB/a7grm+xQEBE3GIOvEJotXOjASEhVXd+/TAl2Ilv9gj00+vTThvPXCeQHAwWCc6I+/rVccTrgeEGQSpiUPaWORXBSQNNXJEuVy6WnrxZ4B/taR3Bm7DmYAeStfBTrJbn4OTM7Pf+YOp/XnWyyAi+6Xn0Jg1ZSfCvr

### Visual documentation

![eror](https://github.com/FlutterFlow/flutterflow-issues/assets/162829003/970b9d03-b178-407d-aefd-7e60fe401d6a)

### Environment

```markdown
- FlutterFlow version: v4.1.71+
- Platform:Desktop & web
- Browser name and version: Google Chrome
- Operating system and version affected: DESKTOP Windows 10 Pro
```

**Comment by botroad** [comment]
Even Action is compiled in Editor, Still getting error in test mode. However, APK File is getting generated without error.
![ScreenShot of Action](https://github.com/FlutterFlow/flutterflow-issues/assets/162829003/f3a84fbb-992d-4298-a8b5-7aee0dbe9e98)

**Comment by Alezanello** [comment]
Hello!

Custom Functions are designed to work without allowing additional packages. For situations where you need to add packages, we have Custom Actions.

To use a package in Custom Actions, you need to do two things:

1. Add the import at the top of your code.
2. Add the dependency in the "Pubspec dependencies" section on the right menu with the version of the package you want to install, like this: `share_plus: ^9.0.0`.

   <img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/252cd512-5570-41eb-bb3d-58eee0c48cc1/ff4ee926-effe-4f81-afaf-b843a872e368?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNTJjZDUxMi01NTcwLTQxZWItYmIzZC01OGVlZTBjNDhjYzEvZmY0ZWU5MjYtZWZmZS00ZjgxLWFmYWYtYjg0M2E4NzJlMzY4IiwiaWF0IjoxNzIwNzM1MzE3LCJleHAiOjMzMjkxMjk1MzE3fQ.Fyn2TVP3C7UmpDQ7BdW_CvvoyndpRH166i0uTrMB8x8 " alt="image.png" width="365" height="247" />

Best regards,<br>Azanello

**Comment by botroad** [comment]
Yup.. That's correctly updated and showing in pubspec.yaml file of project. Also Custom Action is compiled. Still getting error.
I have tried updating package with different version and even deleting custom action and recreating several times. Project is working perfectly, if i remove this custom action. 

![PUBSPEC YAML](https://github.com/user-attachments/assets/20fa3f24-1aeb-4f78-a675-6d641d4a5174)
![Action Compiled In Editor](https://github.com/user-attachments/assets/3214748a-cdab-4e9c-9ba4-00141d9f741f)

**Comment by botroad** [comment]
Hi, This is correctly added. Still getting error.

[image: PUBSPEC.YAML.jpg]
[image: Action Compiled In Editor.jpg]

**Comment by botroad** [comment]
Finally, Got issue resolved, You need to delete Flutterflow desktop app and everything, Clean your system with all temp files, and reinstall All.. Its Package catch, which is causing problem.
