### ISSUE TITLE
Changes are not saving!!!

### ISSUE THREAD

**Issue by Joremando** [FlutterFlow/flutterflow-issues#3373]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Anything I'm trying to do is not being saving even if I name the version. Redoing all the designs again and again and again and I'm losing all my work. Check the flags inverted, for example.
<img width="2757" alt="Screenshot 2024-07-11 at 7 33 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/175346079/885f12d6-58cf-47eb-adc5-fe1f7a2144b7">

### Expected Behavior

Save my work!

### Steps to Reproduce

1 Create a row
2 Add text
3 Ad image
4 reorder the row elemnts
5 check in preview
6 nothing works

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl/H1uI9On7xH7aqNdcFB/CoWG1B9R4EoscpCbw4bIYj2P4lzY876P1ZvUum+SglHfGKcp14E0trwi/PhLcFeAyubc6ZT+ZdiSg7wQkCQRbGTF7WeY0BTP9hVBUyH1sPYhwklOfVtc3xn2k2bN9+AaADDQZzADkQ8Sq/LZO4=

### Visual documentation

<img width="2757" alt="Screenshot 2024-07-11 at 7 33 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/175346079/80eed1f8-cf2e-4753-8e2d-afce28ca11e6">

### Environment

```markdown
- FlutterFlow version: v4.1.70+
- Platform: MacOS, Web
- Browser name and version: Chrome Version 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.5
```

### Additional Information

<img width="2757" alt="Screenshot 2024-07-11 at 7 33 42 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/175346079/a6ce7431-53af-4317-b8f7-dfe0cc3617c8">

**Comment by Joremando** [comment]
I confirmed that this bug is only affecting Mac, my employee is using his Team account on Windows and it's working normally.

**Comment by joaocordeiro-dotted** [comment]
It's happening with me too! I'm using a Mac.

**Comment by agreaves** [comment]
Hi @Joremando, we're currently looking into this issue. Is there any additional information, such as, does this occur in other projects or mainly in the project you added the bug report code for?

@joaocordeiro-dotted, could you add a bug report code too so we can investigate your issue as well?

**Comment by Joremando** [comment]
Any project, it's just not saving any change I try to do.
Now I'm trying in a Windows laptop. I'll let you know if that works...

**Comment by joaocordeiro-dotted** [comment]
Actually, I'm not sure if my problem ir the same. I have a problem with the Allow translation options. If I set some text in a certain widget, it's changing the translation for other widgets. Really annoying problem. 

I'm not sure how to reproduce it, I'm just changing the text, I go to other widget and its original translation is replaced.

**Comment by Joremando** [comment]
Now I tested on Windows, same problem. Apparently is related to my account. I'm the owner.
I need help, I can't work...

**Comment by Joremando** [comment]
![Screenshot 2024-07-11 234324](https://github.com/user-attachments/assets/d37c0767-b08f-43dd-bbee-748ba243b8a5)

**Comment by Joremando** [comment]
I'm going to create a new document from scratch, this was a template and maybe a version issue is not working there. I guess...

**Comment by br0nk** [comment]
What kind of changes are you making to your project that are failing to save?

**Comment by br0nk** [comment]
Also, are the changes disappearing specifically when you do a certain action, such as opening Preview?

**Comment by br0nk** [comment]
Are you still experiencing this issue?   From our end it looks like there are successful edits occurring in your project, but happy to hop on a call to figure this out if you're still running into this.

**Comment by Joremando** [comment]
The problem happens when I try to move, create, add, copy any element. If I preview or Test it's automatically reversed to the original position. It's a template from the Marketplace, so maybe it's an old version causing just me this problem.
However, there is a problem every tie we open the projects, we have to be sure to dave a version and the other user has to open and restore to that version, if not,  FF creates a new version overwriting and deleting all the past work.

**Comment by Joremando** [comment]
> Are you still experiencing this issue? From our end it looks like there are successful edits occurring in your project, but happy to hop on a call to figure this out if you're still running into this.

I would appreciate that, thank you!

**Comment by br0nk** [comment]
Ok, I've sent an email to the account you have registered with Flutterflow to sync up on this.  Thank you for your patience and willingness to help us get to the bottom of this.

**Comment by brunoconceicao** [comment]
I'm having the same problem, it seems like it's not saving changes, including texts. I made a video that shows me changing a text and a few seconds later it goes back to where it was. Sometimes I move a widget around and it goes back by itself. It also happens when I change something in the Firebase config, when I create a new table and need to upload the new rules, then they come back as if they hadn't been uploaded.
I'll put the video here, watch it until the end.
Windows 11, Google Chrome and also in the Flutterflow application installed.
[flutterflow_bug_save.webm](https://github.com/user-attachments/assets/7dfe43b3-bb85-48a9-9700-b7b18c53b774)

**Comment by brunoconceicao** [comment]
I had to delete the widget and create it again, next time i will delete cache and cookie to see if it impacts anything

**Comment by br0nk** [comment]
It looks like the version of Flutterflow cached by the web browser you are using may be out-of-date, which is causing problems when making changes after switching between snapshots/versions of the project as we recently changed some of the functionality related to this.  This is a bug on our end, but as a way to resolve this issue, try either:

1\. Clearing your browser cache and reloading Flutterflow.

2\. Downloading and using one of the Flutterflow desktop apps.

You should see the following version information for Flutterflow when you hover over the project name in the top left corner:

FlutterFlow v4.1.72+ released July 12, 2024<br>Flutter version is 3.22.2

**Comment by Joremando** [comment]
Hi Ruben:
I deleted the cache, the Mac App, Chrome and tried again. Still the same
problem.
I attach a video to show you how it modifies the project once I test or
preview.
When I go back to the Mac app you can see how the component goes back to
its initial position.
*I don't know what to do and I do need to work urgently.*
 Screen Recording 2024-07-16 at 4.47.41 PM 2.MOV
<https://drive.google.com/file/d/1ValhCse3AUrXhPsydEQScJ-0nvqoGvP5/view?usp=drive_web>
[image: Screenshot 2024-07-16 at 4.31.52 PM.png]

**Comment by br0nk** [comment]
Some of the edits made using hotkeys may not be saving correctly (and thus not appearing in the test/preview modes or after refreshes).  Specifically the "shift + arrow" commands for changing ordering appear to be affected.  We're working on a resolution for this, but in the meantime you should be able to make ordering changes by dragging elements around in the page or widget tree.
