### ISSUE TITLE
Kotlin version update required

### ISSUE THREAD

**Issue by fnavarro-ff** [FlutterFlow/flutterflow-issues#3375]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't run an app with stripe integration in emulator

### Expected Behavior

Run the app to test stripe

### Steps to Reproduce

1. run the app

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

icant

### Visual documentation

![image](https://github.com/user-attachments/assets/1f5f0067-0557-4cdf-b165-ef101b3996bc)

### Environment

```markdown
- FlutterFlow version: 4.1.71
- Platform: Android
- Browser name and version: Pixel 4 XL API 34
- Operating system and version affected: Android API 34
```

**Comment by rzambroni** [comment]
Hi @fnavarro-ff, 

Thank you for reaching out to us. Unfortunately, the ticket you submitted does not contain enough information for us to effectively work on resolving the issue. To help us assist you better, please ensure your ticket includes a bit more detail:

* Exact steps to replicate.
* Bug-report-code so we can investigate.
* Other relevant information described on the bug report template that could help us troubleshoot. 

If you don't know how to get the bug report code, [here](https://docs.flutterflow.io/troubleshooting/submit-bug-reports) is a quick guide, thanks.
