### ISSUE TITLE
Issue with Braintree Integration Preventing iOS Deployment to TestFlight

### ISSUE THREAD

**Issue by rayan1005** [FlutterFlow/flutterflow-issues#3376]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

got an error while trying to deploy the app to TestFlight 

### Expected Behavior

The app should deploy to TestFlight without errors.

### Steps to Reproduce

Enable Braintree integration in FlutterFlow.
Attempt to deploy the app to TestFlight.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Enable Braintree integration in FlutterFlow. Attempt to deploy the app to TestFlight.

### Visual documentation

![image](https://github.com/user-attachments/assets/a2841930-bb6a-437a-894e-1b6796768d57)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

error text

<body style="background-color:#14161C">
<style>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}
</style>
<h4>Failed Step: Install pods</h4>
<div style="white-space: pre-wrap;line-height: 1.5">
╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies...
Downloading packages...
+ _fe_analyzer_shared 61.0.0 (72.0.0 available)
+ _flutterfire_internals 1.3.33 (1.3.39 available)
+ analyzer 5.13.0 (6.7.0 available)
+ archive 3.6.1
+ args 2.5.0
+ async 2.11.0
+ auto_size_text 3.0.0
+ boolean_selector 2.1.1
+ cached_network_image 3.3.1
+ cached_network_image_platform_interface 4.0.0
+ cached_network_image_web 1.2.0
+ characters 1.3.0
+ checked_yaml 2.0.3
+ cli_util 0.4.1
+ clock 1.1.1
+ cloud_firestore 4.17.3 (5.1.0 available)
+ cloud_firestore_platform_interface 6.2.3 (6.2.9 available)
+ cloud_firestore_web 3.12.3 (4.0.3 available)
+ cloud_functions 4.7.4 (5.0.3 available)
+ cloud_functions_platform_interface 5.5.26 (5.5.32 available)
+ cloud_functions_web 4.9.4 (4.9.10 available)
+ collection 1.18.0 (1.19.0 available)
+ convert 3.1.1
+ cross_file 0.3.4+1
+ crypto 3.0.3
+ csslib 1.0.0
+ cupertino_icons 1.0.8
+ dropdown_button2 2.3.9
+ fake_async 1.3.1
+ ffi 2.1.2
+ file 7.0.0
+ file_picker 8.0.3 (8.0.6 available)
+ file_selector_linux 0.9.2+1
+ file_selector_macos 0.9.4
+ file_selector_platform_interface 2.6.2
+ file_selector_windows 0.9.3+1
+ firebase_auth 4.19.5 (5.1.2 available)
+ firebase_auth_platform_interface 7.2.6 (7.4.2 available)
+ firebase_auth_web 5.11.5 (5.12.4 available)
+ firebase_core 2.31.0 (3.2.0 available)
+ firebase_core_platform_interface 5.0.0 (5.1.0 available)
+ firebase_core_web 2.17.0 (2.17.3 available)
+ firebase_performance 0.9.4+5 (0.10.0+3 available)
+ firebase_performance_platform_interface 0.1.4+33 (0.1.4+39 available)
+ firebase_performance_web 0.1.6+5 (0.1.6+11 available)
+ firebase_storage 11.7.5 (12.1.1 available)
+ firebase_storage_platform_interface 5.1.20 (5.1.26 available)
+ firebase_storage_web 3.9.5 (3.9.11 available)
+ fixnum 1.1.0
+ flutter 0.0.0 from sdk flutter
+ flutter_animate 4.5.0
+ flutter_braintree 4.0.0-dev.1 (4.0.0 available)
+ flutter_cache_manager 3.3.1 (3.3.2 available)
+ flutter_google_places 0.4.0 from git https://github.com/ShehanYjoz/flutter_google_places.git at 52ddef
+ flutter_launcher_icons 0.13.1
+ flutter_lints 4.0.0
+ flutter_localizations 0.0.0 from sdk flutter
+ flutter_plugin_android_lifecycle 2.0.20
+ flutter_rating_bar 4.0.1
+ flutter_shaders 0.1.2
+ flutter_staggered_grid_view 0.7.0
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ font_awesome_flutter 10.6.0 (10.7.0 available)
+ from_css_color 2.0.0
+ geolocator 12.0.0
+ geolocator_android 4.6.0
+ geolocator_apple 2.3.7
+ geolocator_platform_interface 4.2.3 (4.2.4 available)
+ geolocator_web 4.0.0
+ geolocator_windows 0.2.3
+ glob 2.1.2
+ go_router 12.1.3 (14.2.0 available)
+ google_api_headers 2.0.3 (4.1.2 available)
+ google_fonts 6.1.0 (6.2.1 available)
+ google_identity_services_web 0.2.2 (0.3.1+1 available)
+ google_maps 7.1.0
+ google_maps_flutter 2.6.1 (2.7.0 available)
+ google_maps_flutter_android 2.8.1 (2.12.0 available)
+ google_maps_flutter_ios 2.6.1 (2.10.0 available)
+ google_maps_flutter_platform_interface 2.7.1 (2.8.0 available)
+ google_maps_flutter_web 0.5.7 (0.5.8 available)
+ google_maps_webservice 0.0.20-nullsafety.5 from git https://github.com/ShehanYjoz/google_maps_webservice.git at 1588c2
+ google_sign_in 6.1.5 (6.2.1 available)
+ google_sign_in_android 6.1.20 (6.1.27 available)
+ google_sign_in_ios 5.6.4 (5.7.6 available)
+ google_sign_in_platform_interface 2.4.2 (2.4.5 available)
+ google_sign_in_web 0.12.1 (0.12.4+1 available)
+ html 0.15.4
! http 1.2.1 (overridden)
+ http_parser 4.0.2 (4.1.0 available)
+ image 4.0.17 (4.2.0 available)
+ image_picker 1.0.4 (1.1.2 available)
+ image_picker_android 0.8.8 (0.8.12+4 available)
+ image_picker_for_web 3.0.1 (3.0.4 available)
+ image_picker_ios 0.8.8+2 (0.8.12 available)
+ image_picker_linux 0.2.1+1
+ image_picker_macos 0.2.1+1
+ image_picker_platform_interface 2.9.1 (2.10.0 available)
+ image_picker_windows 0.2.1+1
+ infinite_scroll_pagination 4.0.0
+ intl 0.19.0
+ intl_phone_field 3.2.0
+ iregexp 0.1.2
+ js 0.6.7 (0.7.1 available)
+ js_wrapping 0.7.4
+ json_annotation 4.9.0
+ json_path 0.7.2
+ leak_tracker 10.0.4 (10.0.5 available)
+ leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
+ leak_tracker_testing 3.0.1
+ lints 4.0.0
+ logging 1.2.0
+ matcher 0.12.16+1
+ material_color_utilities 0.8.0 (0.12.0 available)
+ maybe_just_nothing 0.5.3
+ meta 1.12.0 (1.15.0 available)
+ mime 1.0.5
+ mime_type 1.0.0
+ nested 1.0.0
+ octo_image 2.0.0
+ package_config 2.1.0
! package_info_plus 8.0.0 (overridden)
! package_info_plus_platform_interface 3.0.0 (overridden)
+ page_transition 2.1.0
+ path 1.9.0
+ path_provider 2.1.3
+ path_provider_android 2.2.5 (2.2.7 available)
+ path_provider_foundation 2.4.0
+ path_provider_linux 2.2.1
+ path_provider_platform_interface 2.1.2
+ path_provider_windows 2.3.0
+ permission_handler 11.3.0 (11.3.1 available)
+ permission_handler_android 12.0.7
+ permission_handler_apple 9.4.5
+ permission_handler_html 0.1.1
+ permission_handler_platform_interface 4.2.1
+ permission_handler_windows 0.2.1
+ petitparser 6.0.2
+ pigeon 11.0.1 (20.0.2 available)
+ platform 3.1.5
+ plugin_platform_interface 2.1.8
+ pointer_interceptor 0.10.1 (0.10.1+1 available)
+ pointer_interceptor_ios 0.10.1
+ pointer_interceptor_platform_interface 0.10.0+1
+ pointer_interceptor_web 0.10.2
+ provider 6.1.2
+ pub_semver 2.1.4
+ quiver 3.2.1
+ rfc_6901 0.2.0
+ rxdart 0.27.7 (0.28.0 available)
+ sanitize_html 2.1.0
+ shared_preferences 2.2.2 (2.2.3 available)
+ shared_preferences_android 2.2.1 (2.2.3 available)
+ shared_preferences_foundation 2.3.4 (2.4.0 available)
+ shared_preferences_linux 2.3.2
+ shared_preferences_platform_interface 2.3.1 (2.3.2 available)
+ shared_preferences_web 2.2.1 (2.3.0 available)
+ shared_preferences_windows 2.3.2
+ sign_in_with_apple 4.3.0 (6.1.1 available)
+ sign_in_with_apple_platform_interface 1.0.0 (1.1.0 available)
+ sign_in_with_apple_web 1.0.1 (2.1.0 available)
+ sky_engine 0.0.99 from sdk flutter
+ sliver_tools 0.2.12
+ smooth_page_indicator 1.1.0 (1.2.0 available)
+ source_span 1.10.0
+ sprintf 7.0.0
+ sqflite 2.2.6 (2.3.3+1 available)
+ sqflite_common 2.5.4
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ stream_transform 2.1.0
+ string_scanner 1.2.0 (1.3.0 available)
+ synchronized 3.1.0+1
+ term_glyph 1.2.1
+ test_api 0.7.0 (0.7.3 available)
+ text_search 1.0.1 (1.0.2 available)
+ timeago 3.6.1 (3.7.0 available)
+ tuple 2.0.2
+ typed_data 1.3.2
+ url_launcher 6.2.5 (6.3.0 available)
+ url_launcher_android 6.3.0 (6.3.3 available)
+ url_launcher_ios 6.2.5 (6.3.0 available)
+ url_launcher_linux 3.1.1
+ url_launcher_macos 3.2.0
+ url_launcher_platform_interface 2.3.2
+ url_launcher_web 2.3.1
+ url_launcher_windows 3.1.1
! uuid 4.4.2 (overridden)
+ vector_math 2.1.4
+ video_player 2.8.6 (2.9.1 available)
+ video_player_android 2.4.16 (2.5.2 available)
+ video_player_avfoundation 2.6.1
+ video_player_platform_interface 6.2.2
+ video_player_web 2.3.1
+ vm_service 14.2.1 (14.2.4 available)
+ watcher 1.1.0
+ web 0.5.1
! win32 5.5.1 (overridden)
+ xdg_directories 1.0.4
+ xml 6.5.0
+ yaml 3.1.2
Changed 197 dependencies!
78 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Analyzing dependencies
Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `10.25.0`
cloud_firestore: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
cloud_functions: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

CocoaPods 1.15.0 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0

[!] CocoaPods could not find compatible versions for pod "google_maps_flutter_ios":
  In Podfile:
    google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)

Specs satisfying the `google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

Build failed :|
Step 6 script `Install pods` exited with status code 1
</div>
</body>

**Comment by rayan1005** [comment]
![brain](https://github.com/user-attachments/assets/962e4134-57e6-47eb-999d-8b7528012ace)
The error occurs regardless of whether I include an Apple Merchant ID or not, or if I add a payment action or not. The only way to resolve the issue is to disable the Braintree payment option.

**Comment by rayan1005** [comment]
The error occurs regardless of whether I include an Apple Merchant ID or not, or if I add a payment action or not. The only way to resolve the issue is to disable the Braintree payment option.
![brain](https://github.com/user-attachments/assets/7e12453f-5ff0-43cf-9806-c7dd0ef96538)

**Comment by rayan1005** [comment]
im still waiting

**Comment by msusviela** [comment]
Hi @rayan1005. Sorry for the late response. We've been checking your case with the ENG team and currently BrainTree is going to be deprecated in upcoming versions of FlutterFlow. I'll advice you to use another integration for payments. FlutterFlow offers integrations for Stripe, RevenueCat and RazorPay. I'm so sorry for any inconvinience that it can be causing.
