### ISSUE TITLE
Playing sound requires microphone access permission in iOS

### ISSUE THREAD

**Issue by bob-reus** [FlutterFlow/flutterflow-issues#3377]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I'm trying to compile the iOS version of my app, I receive an email with the following error message:

> **ITMS-90683: Missing purpose string in Info.plist** - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Runner.app” bundle should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources. 

Someone raised this on the community site as well: 
https://community.flutterflow.io/ask-the-community/post/itms-90683-missing-purpose-string-in-info-plist-for-Pc7jTvrfNZRZdJr

### Expected Behavior

I expect to be able to play sounds without needing microphone access permissions. 

### Steps to Reproduce

1. Create a new project
2. Add a sound asset
3. Add the _play sound_ action to _on page load_
4. try to deploy the app to App Store

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8j1vJN1pbwA1aqJdcBr/TkRJW4iR5EWscp/bxIgGIDzPOw+ZPXsTFRpTbSgSlFHM0SmmmEJ+M7wvuL1CccnByesGaJOzKpudxbdeE66a5OBBbqWZURCAppjIW7H38GJgwkkAPVfSCU82mGIGevKHjDsO5TQImdISq/LZO4=

### Visual documentation

The `audio_session` package documentation proves that microphone access is required by default, and that the user should modify the build process: https://pub.dev/packages/audio_session#ios-setup

This is not possible in FlutterFlow at this time. 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.71+ released July 12, 2024
- Flutter version: 3.22.2
```

### Additional Information

Sound playback is a requirement in our app, but we also want to leave a trustworthy impression on our users. Requesting microphone access and not using it will lead to raised eyebrows for some of our users for sure.

**Comment by msusviela** [comment]
Hi @bob-reus. Had you tried enabling the Microphone permissions in the App Settings -> Permissions?<br><br>That would add that line to the Info.plist and won't ask for access if you don't trigger the action to ask for access.

**Comment by bob-reus** [comment]
I could, but that would still show the permission on the app store page, right?

**Comment by msusviela** [comment]
I think that you should have it either way. If you have a permission set on the .plist file but you don't have it declared for the app store to show, they'll reject your app from submition

**Comment by bob-reus** [comment]
But that is exactly the issue: I have to set a permission for microphone usage, and users will see the permission for microphone usage in the app store, even though we don't access the microphone. We play a sound file.

15 Jul 2024 22:59:35 Micaela ***@***.***>:

**Comment by bob-reus** [comment]
What is the status on this? Could you confirm that microphone access to play audio files required, and that it is undesirable?

**Comment by msusviela** [comment]
Hi @bob-reus. Currently in FlutterFlow is not possible to specify that microphone access is not necessary when compiling, but in the documentation of the package it's a possibility. I've filled an internal feature request for that so the team can work on this. At the moment you have to have that permission if you want to deploy, even though I know that it might not be desirable.  <br>I'll close this issue since the feature request was created, but will keep you updated.<br><br>Thanks!

**Comment by arya-coding** [comment]
Was this solved ? I'm having the issue.

**Comment by oliver-the-uap** [comment]
> Was this solved ? I'm having the issue.

same here.

**Comment by anatoliyfedorenko** [comment]
Same here :( and it is clearly not resolved.
