### ISSUE TITLE
URGENT: Can't see document properties from parameters after the last update (Jan10)

### ISSUE THREAD

**Issue by mravani2** [FlutterFlow/flutterflow-issues#338]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When I load a document inside a component using a parameter, I should be able to access its properties

## Current behavior (required)

I can't see the properties list anymore

## To Reproduce (required)

1. Create a Component
2. Create a Document Parameter inside de component
3. Try to load any property of the document
4. You won't see the options

### Bug Report Code (required, generate from Widget Tree)

`IT4kzOfluYtPj7xY17X5bcFKjjo4KWYiTLJMt9VxSUghfYCuEIl+dvT4YktLYteZeghIBmaikkMep9bJjeDhKvUFCzOtQKp/zZoFH1yjEA8=`

## Context (required)

I'm loading a document inside a component. This document has several properties that I want to use inside my component. This was working before today's update.

## Screenshots / recordings

I should be able to select a color field
![image](https://user-images.githubusercontent.com/122111577/211638615-796cacb3-dde0-46e6-b10a-426cbe8568d9.png)

I should be able to select a text field
![image](https://user-images.githubusercontent.com/122111577/211639135-bd2656ce-afd4-486e-b2dc-016f93639865.png)

I've also noticed the same behavior in Actions. Here I should be able to see my dataType field before the Select Field
![image](https://user-images.githubusercontent.com/122111577/211645024-ae9fb4f7-5b14-4167-b8e2-6c6ff9500eb7.png)

## Your environment

* Version of FlutterFlow used: 
![image](https://user-images.githubusercontent.com/122111577/211639348-9feb1852-0c2a-49ab-98c0-e00897ce48ef.png)

* Platform (e.g. Web, MacOS Desktop): 
* Desktop
* Browser name and version: 
* Microsoft Edge
* Operating system and version (desktop or mobile):
* Desktop Windows 11

**Comment by agreaves** [comment]
Hi @mravani2, thanks for the report! Can you please include the Bug Report code for your project? It's now required for new issues and makes reproducing the issue much easier. If we have that we can hopefully fix this behavior for you soon 🙂

**Comment by mravani2** [comment]
@agreaves, I just updated the post with the bug report. I appreciate the fast response, I'm stuck here without this hahaha.

**Comment by mravani2** [comment]
@agreaves I have just updated FF, and it's all working again. Thank you so much, you guys are the best! 😁😎🎉

**Comment by agreaves** [comment]
Awesome!! No problem, thanks for reporting the issue 😊
