### ISSUE TITLE
FlutterFlow Desktop App on windows crashes

### ISSUE THREAD

**Issue by Gawwad-Tech** [FlutterFlow/flutterflow-issues#3383]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow always crashes on desktop 

### Expected Behavior

i expect it to work without crashing

### Steps to Reproduce

just work some time on the app and it will crash, here is a recorded video of a sample of what is happening

https://www.loom.com/share/a3520585c13147159c1f66c21a2b2489?sid=88997887-40dd-4f41-a959-2752023221a7

the problem happens in new blank projects as well, but it takes some times or actions that varies every time, for example it may crash once on run another in making new api group etc

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si/Lq+Zd2scsA+KqNdcd7/GI7OXp7a7goscp8WQgafIjJP4kQPPWldlhuXtDid29YOESmmnMe3MGPjezlDu45OSqsba5T/5BPEQvKYFiVQZOBCamCZX9tIJtmfFS75qbUrSMlA/tsc2Q17V2APtyyaHTqJJDFImdISq/LZO4=

### Visual documentation

https://www.loom.com/share/a3520585c13147159c1f66c21a2b2489?sid=88997887-40dd-4f41-a959-2752023221a7

### Environment

```markdown
- FlutterFlow version: 4.1.71
- Platform: windows desktop
- Browser name and version:no browser
- Operating system and version affected: windows 10
```

**Comment by Alezanello** [comment]
Hello!

I just saw the video and I'm very sorry you're experiencing this issue with the FlutterFlow Windows app. Let's try to dive in a little deeper.

Could you please share your machine specifications, such as RAM, CPU, Windows version, and VRAM? You can access this information by pressing WINDOWS + R to open the RUN window, then typing "dxdiag" to display the details.

Thank you!

Best regards,<br>Azanello

**Comment by Gawwad-Tech** [comment]
@Alezanello Thanks, 
I tested it on two laptops, and the problem occurred in both.

![Dell Lap Spec](https://github.com/user-attachments/assets/968192f6-09fa-40c7-90be-04ae93b84aa6)
![hp lab spec](https://github.com/user-attachments/assets/aa8fb396-103e-40fc-a6fc-deed19ebd561)
h

**Comment by Gawwad-Tech** [comment]
Hi, any news about this issue!

**Comment by Alezanello** [comment]
Hello!!<br><br>We launched a new update yesterday, could you check if this still happening after updating to the newer version, and just double checking the video, why are you launching the FF App trough a .bat?

**Comment by Gawwad-Tech** [comment]
Hi @Alezanello,

Thank you for your reply.

Unfortunately, the problem still exists after installing the new version. Regarding the batch file, as shown at the beginning of the video, attempting to open the app directly from the app icon doesn't work at all. One of the solutions I found in your community is to create a batch file that automatically deletes Firestore data on startup, like this:
 `@echo off
rd /s /q "C:\Users\[user name]\AppData\Local\firestore"

"c:\program files\flutterflow\flutterflow.exe"`

Thanks.

**Comment by Gawwad-Tech** [comment]
any news

**Comment by Gawwad-Tech** [comment]
Is there any update regarding this issue?

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. Before we proceed further, did the latest FlutterFlow updates resolve your issue?

**Comment by Gawwad-Tech** [comment]
Hello!

Unfortunately, the issue still exists even after the latest updates.

**Comment by Alezanello** [comment]
Hello again,

At this point, I'm lacking the right tools to help you with this issue. I'll keep this issue open in case I find anything that might help, but in the meantime, I recommend you contact support directly via the in-app chat or at support@flutterflow.io for a more specific solution to your situation.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
