### ISSUE TITLE
Issue when reading / deleting Firestore collections/documents

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#3384]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am having issues in some pages with respect to accessing/deleting documents/collections of Firestore. I am getting 'Error fetching collection collectionName: [cloud_firestore/permission-denied] Missing or insufficient permissions.' in some cases. In some cases, I am getting an error 'POST 400'. The error happens when enabling/disabling authentication, as well as when changing the firestore rules from 'authenticated only' to 'everyone'.

### Expected Behavior

I should be able to read/write/delete my firestore documents/collections.

### Steps to Reproduce

1. Create new page
2. Add a firestore collection
3. Try to read/write/delete firestore documents/collections

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kzcrqx49IsbRJ+KqJccFvij4vJjsja7sslu5DTUw0C4/mG7YAW/SkQE9WZ7yhdH02ME788HIxw+zKvfbIN/E6H0utRt06ypBichbjcGaXeJCqPqmdP3Z8HtpKBWqB0MHU3CZSAPZvLXA87FyyJvKsZBLvJqLROEcdH8+aOd/+jX/uQ0SLb3kNh1JWeC/v

### Visual documentation

![error new](https://github.com/user-attachments/assets/62984846-8486-4c80-9a6b-b10d1a1a216e)

### Environment

```markdown
- FlutterFlow version: 4.1.71+
- Platform: Web, Windows PC (laptop)
- Browser name and version: Chrome Version 126.0.6478.127 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home Version 10.0.22631 Build 22631
```

**Comment by Alezanello** [comment]
Hello!

After a quick review of your Firestore rules, it appears that, aside from your users collection, every other collection does not grant users permission to Write/Delete. This prevents them from updating or deleting any documents in those collections.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1135d6e8-94e6-4424-a967-efca6f52e1bd/8c3879ba-d341-4475-8f3e-c777d87fd347?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMTM1ZDZlOC05NGU2LTQ0MjQtYTk2Ny1lZmNhNmY1MmUxYmQvOGMzODc5YmEtZDM0MS00NDc1LThmM2UtYzc3N2Q4N2ZkMzQ3IiwiaWF0IjoxNzIwNzkwNjM5LCJleHAiOjMzMjkxMzUwNjM5fQ.VlgMh_s8SQfdGB3QnhwhiMjzFpJxC8nRkfdHyr0xDZ0 " alt="image.png" width="910" height="333" />

Best regards,<br>Azanello

**Comment by adrfinance** [comment]
Do you know what happens? I change the rules to 'Everyone', and then they change on their own to 'No one'. What is going on?

**Comment by Alezanello** [comment]
Are you deploying the rules to Firestore after changing it?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6dce1952-ca14-42bb-b4d3-122cfa445d48/0e76615c-ce86-4f22-b90e-278cfd7ac90e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZGNlMTk1Mi1jYTE0LTQyYmItYjRkMy0xMjJjZmE0NDVkNDgvMGU3NjYxNWMtY2U4Ni00ZjIyLWI5MGUtMjc4Y2ZkN2FjOTBlIiwiaWF0IjoxNzIwNzkxNDUyLCJleHAiOjMzMjkxMzUxNDUyfQ.SybYfftS-E6ynUZHxsm1zy_kqRP8o6syo0WsP2F9T8g " alt="image.png" width="1108" height="182" />

**Comment by adrfinance** [comment]
I deploy the rules and then FF seems to be making changes to the rules on its own. I set everything to 'Everyone' for example, then FF changes some to 'No one' or something. Very weird?!?

**Comment by Alezanello** [comment]
i just created a new project and settled collection to Everyone and deployed the rules without any issues.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c9810129-bc33-49b9-96e7-3120c892bf02/2edda81a-3e5b-4297-9c4b-bbdb6a09ce9f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jOTgxMDEyOS1iYzMzLTQ5YjktOTZlNy0zMTIwYzg5MmJmMDIvMmVkZGE4MWEtM2U1Yi00Mjk3LTljNGItYmJkYjZhMDljZTlmIiwiaWF0IjoxNzIwNzkyMDIxLCJleHAiOjMzMjkxMzUyMDIxfQ.x9OOsGLv-EYtlHo4AkODUM3ehBTb9WPDfI1shCUArVg " alt="image.png" width="1142" height="368" />

Can you access to the Firebase project directly, go to the Firestore Database and Rules and check the acitivity? if there is any new deploy or changes in the rules there?

**Comment by adrfinance** [comment]
I am deploying the rules in my FF project as well, and then I see 'Deployed' and the green arrow and everything. I never said the rules are not deployed. I am saying the rules are deployed and then FF does its thing and it shows as 'Out of Date' again without me doing anything.
Yes there is plenty of activity in the Firebase activity as you can see from the image I upload:
![image](https://github.com/user-attachments/assets/40a3c4ad-90c4-4465-ab7b-9d92dcbb728a)

**Comment by Alezanello** [comment]
Let's do this, set everything in "Everyone", and the jsut copy the rules and put them directly to the Firestore website and then after doing that refresh your FlutterFlow page doing CTRL + F5 or Ctrl+Shift+R 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/db661d4d-3f02-4260-b9fa-d4f5ef2de84e/fe7f4395-d314-4ca0-8eda-9f74a7dc07d1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYjY2MWQ0ZC0zZjAyLTQyNjAtYjlmYS1kNGY1ZWYyZGU4NGUvZmU3ZjQzOTUtZDMxNC00Y2EwLThlZGEtOWY3NGE3ZGMwN2QxIiwiaWF0IjoxNzIwNzkzMDIyLCJleHAiOjMzMjkxMzUzMDIyfQ.HPNTm_gyxnpy5Ecc8kvmuNqfMrYqmU2kZdbaT4SGKjc " alt="image.png" width="1141" height="576" />

**Comment by adrfinance** [comment]
Hello, I did what you said. Still the same issue. The rules at FF are changing on their own for some reason. Can  you check my project? I gave you permission to do so when creating the ticket.

**Comment by Alezanello** [comment]
I'm sorry to hear you're still facing this issue. Unfortunately, this goes beyond my capabilities. I can only replicate issues from a blank project or check some particular settings in your project. This issue should be addressed by our support team via in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io). They have the necessary tools and expertise to assist you further.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
