### ISSUE TITLE
`badges` package: "No named parameter with the name 'shape'"

### ISSUE THREAD

**Issue by prossm** [FlutterFlow/flutterflow-issues#3386]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I successfully got my app into TestFlight previously, but now for some reason the code that is being generated by FlutterFlow keeps throwing an error whenever I try to build in XCode.

To reiterate: I did not write this code, "the machine" did. Attached is a screenshot of the part of the code that is throwing the error in XCode (create_contact_widget.dart, line 285, "shape: ...").

Also included is a screenshot of the error XCode gave:

lib/pages/create_contact/create_contact_widget.dart:285:41: Error: No named parameter with the name 'shape'.

Also included are screenshots of the badge settings in the Flutterflow UI.

### Expected Behavior

No errors should be thrown. `shape` is a valid modifier of the badges package (as per the documentation - https://pub.dev/packages/badges ), but something about the formatting that was created by FlutterFlow is confusing XCode and blocking the build.

### Steps to Reproduce

1. Create a FlutterFlow app for iOS
2. Use a badge widget
3. Download code
4. Try to build in Xcode

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gksjf5ZNOm9xE1rqBd+9almAsC1g7bJc0rd5EZxMjfYz4Ouw1dffRMlVpXu6zaHNMfGGLklgE0M6MktrpDvddPRyAbr5kzc1MZhPPY3OlVratO6iweHRtM5lVGhGj0rS7pAolA/VuW1oF1FyQPOe+TT2Cf9qOYwx5e6fDbOY=

### Visual documentation

![create_contact_widget](https://github.com/user-attachments/assets/37534142-ec3e-4ad2-862a-29d2896de94b)
<img width="894" alt="XCode_error" src="https://github.com/user-attachments/assets/a3a51d72-fccd-4b5f-a780-a5f362125eee">
<img width="1280" alt="Screenshot 2024-07-12 at 11 53 08 AM" src="https://github.com/user-attachments/assets/0c5133ee-e8bb-4cae-ab44-413f7ca1179b">
<img width="307" alt="Screenshot 2024-07-12 at 11 53 26 AM" src="https://github.com/user-attachments/assets/91954893-539c-4f4d-b445-f023ebd2e8cc">
<img width="307" alt="Screenshot 2024-07-12 at 11 53 29 AM" src="https://github.com/user-attachments/assets/5b7052a5-ee4c-4231-a5a1-2c8a590d42f0">

### Environment

```markdown
- FlutterFlow version: v4.1.71+ released July 11, 2024
- Flutter version: 3.22.2
- Platform: iOS / XCode
- Browser name and version: Chrome (issue is not in the browser though)
- Operating system and version affected: MacOS Sonoma 14.5 (23F79)
```

### Additional Information

I'm unable to create an archived version of my app and therefore cannot put it into TestFlight to move forward with my product launch.

**Comment by paulperez-dev** [comment]
Hi @prossm! I was unable to reproduce this issue. I couldn't find the badge widget on your project.

Can you please try to reproduce this issue on a blank project and share the bug report code?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by prossm** [comment]
Sorry, I changed the code to remove the badge widget, since it was broken. I'm having a different issue now ;) but I'll do separate research on that one
