### ISSUE TITLE
Crash when clicking in the button branch on desktop version

### ISSUE THREAD

**Issue by pireslopesvinicius** [FlutterFlow/flutterflow-issues#3387]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When clicking in the button of branch in the desktop version of flutterflow it just crash, while on web it works fine.

### Expected Behavior

It should not crash, like in web.

### Steps to Reproduce

1. Create a project and in one of the paid plans(desktop version)
2. Click on the button branch
3. Crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raCsofePrOpkAf8/7UFtUOOriYAhcPU20pHEX/MrvvofxGPA4CyyaQYB6z85UcRWWWmqjbpvSPK63b3EnI/FbGkik1MO3ogkkHNtvLnMt22WmAd+tYBfBJp/1C0UdOeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

It's already described in the text above.

### Environment

```markdown
- FlutterFlow version: v4.1.71+
- Platform: Desktop
- Browser name and version: Desktop
- Operating system and version affected: Windows 10 64 bits
```

**Comment by paulperez-dev** [comment]
Hi @pireslopesvinicius! I was unable to reproduce this issue. Can you please test again in the latest release ( v4.1.72+)?

**Comment by pireslopesvinicius** [comment]
Hi! Yes, I had been solved in this new version apparently. Thanks

**Comment by paulperez-dev** [comment]
Thanks for the confirmation!
