### ISSUE TITLE
Firestore Manage Content is Not Working 

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#3389]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Email is already enabled and Fireabase is connected properly with FF project but still not showing !

### Expected Behavior

It was working and I procced based on your Guide and still not showing !
Should to be work so there's something there on your backend.

### Steps to Reproduce

- Connect Firebase project 
- Enable AUth + Email
- Fill some data in firestore 
- Lunch Content Manager 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kMmB25NOtb0A+KX2ccJagiYXH0c7a+crjMBxZwA8J5zKB+wAYvf7P1FWTL3mS1FIJU38oHox7PfqkvLxE8IoIUmqfJRnzZF2YBfyYEyhRbaYEKudfW1QHfhPJmLG1sKo3BF+Oux1LHtn2mWMIumWcHHACZu2OzINJuW1LdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/9e8a14e5-6f10-464f-8f3c-ad666c8e1b93)
![image](https://github.com/user-attachments/assets/86d69c89-dba8-4682-bc22-1cb70918dd88)

### Environment

```markdown
- FlutterFlow version: 4.1.71+
- Platform: Web 
- Browser name and version: Chrome 126
- Operating system and version affected: Win 11 Home
```

### Additional Information

Yeah the client need it to manage his data on Firestore and don't need to waste money on other tools !

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by ImadBouirmane** [comment]
Please if you can to make it as priority because my client is really waiting it for it 🙏

**Comment by giladresisi** [comment]
Same here. I see this issue was passed to the eng team almost 2 months ago, anything new?

**Comment by wenkaifan0720** [comment]
Hi all. Sorry for the delayed response. Could you check if there is already a `firebase@flutterflow.io` user created under `Authentication -> Users`? If so, you probably need to delete this user, and then try connecting again.

**Comment by SkiSamaBinLaden** [comment]
upvote.  In addition to this, my FireBase Databases are all empty.

**Comment by ImadBouirmane** [comment]
@wenkaifan0720 Adding FF email firebase is always set but I will close this issue now because its work on majority of the projects !
