### ISSUE TITLE
infinite test mode and does not work

### ISSUE THREAD

**Issue by andreasvonfeld** [FlutterFlow/flutterflow-issues#3393]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I press test mode, the loading screen is infinite and shows nothing

### Expected Behavior

I would like to be able to test my application

### Steps to Reproduce

1. open the project on flutterflow
2. click on test mode
3. the app ui will never show up and will be loading forever.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeksrq05NPj7xa1rXUKsFGpwMwJ0QlUIInj+0bWRMhNYjkPJl2PM7SUFtLYtTnTUFYEE2YkXIEwNKPufzXKO0CZCibc6E+yL5XQT3/UlGjVLa3CaisVUB6M5pVJlPH58G02wlSFLBfR1Is2U6xevCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/8550151a-cac9-4812-96de-43e4aecb798d

### Environment

```markdown
- FlutterFlow version: jul 13
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
Hi @andreasvonfeld. Test mode is working at the moment. Is this still an issue for you?

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
