### ISSUE TITLE
I can't add any CSV file to any collection.

### ISSUE THREAD

**Issue by Doli05** [FlutterFlow/flutterflow-issues#3397]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have this collection, where I have a list of exercises for a workout app. Since putting the data in manually would take me too long, I made a csv file to upload. I had this problem months ago, and it let me put the file in FF but it would give me an error at the end. Even the most simple file with like 2 rows and just letters wouldn't work. Now I tried again and it tells me the headers are wrong, but I checked and they're all correct. I tried adding manually one document to the collection and it when I upload it, it doesn't do anything. The only way I could add one was from firebase. I tried to validate my CSV in different sites and they all told me it was valid, and I also made a new collection with the same fields and it still gives me the same exact error. I also tried to add it as a TSV file instead, and it still doesn't work.
I also have another project to test things (like this bug) and it gives me the same error.

Edit: I tried to create a new csv file with 2 fields and it looks like this
ciao ciaoa
abc abcd

I created another schema in FF with the same fields and this time the error isn't there anymore, but it gives me the error "Upload failed please try again". With 1 record it doesn't work. 
(btw I also asked my cousin who has been a developer for many years and she has no idea why this doesn't work)

### Expected Behavior

It should let me put the data from the CSV file in the collection.

### Steps to Reproduce

1. Create a new collection. 2 Create a CSV file. 3. Open the manage content page. 4. Add the CSV file to the collection.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

It's not specific to a widget or a page

### Visual documentation

![tfthisevenmean](https://github.com/user-attachments/assets/ffbc2a32-a27b-4391-b56d-e0f33f2ae3ef)
![error](https://github.com/user-attachments/assets/8e4b7da9-d550-4e09-b97d-f49e7fd9b5d3)

### Environment

```markdown
- FlutterFlow version:v4.1.72 
- Platform: Windows
- Browser name and version: Chrome Version 126.0.6478.127
- Operating system and version affected: Windows 10
```

### Additional Information

I need this CSV in flutterflow or else I can't test anything in my app and I can't build it. This CSV (since it's for exercises) is needed to make 90% of the pages to work.

Edit 2: I got the csv into flutterflow with FireFoo, but with flutterflow it doesn't work.

**Comment by Alezanello** [comment]
Hello!

First of all, I'm sorry you're facing this issue.

Could you please generate a Bug Report Code from your project? You can easily do this by right-clicking on any widget and selecting "Generate Bug Report Code" from the pop-up menu.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/86338246-c2a5-41ec-a7d9-8d8a5e5c0863/a811f9b8-d032-44e4-8d91-645702ba821c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NjMzODI0Ni1jMmE1LTQxZWMtYTdkOS04ZDhhNWU1YzA4NjMvYTgxMWY5YjgtZDAzMi00NGU0LThkOTEtNjQ1NzAyYmE4MjFjIiwiaWF0IjoxNzIxMDUxMzc1LCJleHAiOjMzMjkxNjExMzc1fQ.EWWtivpYXOKJ4sGyBrYX-hHP2sGgU2ZXjlIcMJvSaqk " alt="image.png" width="400" height="339" />

Thank you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
