### ISSUE TITLE
Vital bug with number of seats

### ISSUE THREAD

**Issue by MahamadKanabi** [FlutterFlow/flutterflow-issues#3398]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have paid for only two seats but using a trick the number of seats can be increased without paying for it

### Expected Behavior

The number of seats should not be increased without paying for it

### Steps to Reproduce

https://github.com/user-attachments/assets/c0834eee-df42-4654-aba0-4bd2bd9cda6d

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlPHqx492xLlE1rrUcMBviikQIjs3bec7lOpEGSs8f4yqPZkAevfRQEtuTdO0T29IJU6apDk07v/emvLtVMEoKTmVbYR4+sxcZTvNQnqhWqaUCKuwQ25/Ap9YCUid0LaJsBVAKslvLnAX7GayHfPIVi/bQ5C0IVQ/If+1C5CK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Untitled](https://github.com/user-attachments/assets/19937020-f01a-4161-8b3f-a7d08a43564b)

### Environment

```markdown
- FlutterFlow version: Last Version
- Platform: Windows 
- Browser name and version: All emulators
- Operating system and version affected: NO
```

### Additional Information

Such a bug deserves a reward, we hope you don't forget our good intention twards the application.

**Comment by rzambroni** [comment]
Hi @MahamadKanabi, thanks for the report and honesty, this is, unfortunately, a known bug that the team already has on their backlog to fix. 

Will mark it as a duplicate since this is being tracked internally already.

Thanks again.
