### ISSUE TITLE
Can't vote nor dismiss the dialog

### ISSUE THREAD

**Issue by atn832** [FlutterFlow/flutterflow-issues#34]
## Expected behavior (required)
I should be able to vote, or if I don't want to vote, dismiss the popup.

## Current behavior (required)
I can't vote nor dismiss the popup. I can however refresh the page so that the popup disappears.

## To Reproduce (required)
The vote dialog popped up when I was testing my app. Once it appears, I can click anywhere on the page and nothing will happen.

## Screenshots / recordings

https://user-images.githubusercontent.com/3399854/195107057-4f744af0-58eb-4e99-8a33-a2ba31b20bb0.mov

## Your environment
* Version of FlutterFlow used: 
* <img width="206" alt="image" src="https://user-images.githubusercontent.com/3399854/195107191-3f3fb243-ef4e-447f-8c21-e0557dfd6af3.png">
* Mac OS on a Mac Mini
* Latest Chrome

**Comment by Pepino-GR** [comment]
Hello atn832,

can you reproduce the issue? Does it always pop up, when you start testing your app?

**Comment by atn832** [comment]
This popup has not showed up again since.

**Comment by agreaves** [comment]
Thanks for this @atn832, this one would be hard to reproduce but I believe we know the fix. Thank you for reporting it!
