### ISSUE TITLE
The keyboard is closed automatically when is touched a textField from a component

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#340]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When the textField from a component is selected should appear the keyboard

## Current behavior (required)

The keyboard is closed automatically when is touched a textField from a component

## To Reproduce (required)

1. Create a List of String as Local State
2. Create a new page
3. Add a column and generate from variable from the Local State created previously
4. Add a textField in this column and convert into a component
5. Outside of the column add a TextField
6. You should have this structure

![image](https://user-images.githubusercontent.com/36147203/211691908-75c902b7-1be3-4aed-bbad-7457b5148e79.png)

### Bug Report Code (required, generate from Widget Tree)

IT4olMjfsIh2sbQD1pSJcMdVryQ4Q1AmbZJI0spBazwbfe+uB4kqevfOTERDUs+nYAliIFmakWoW3P/FuNnDLvE4CySqQKpHyZBcETvwXmejb7bSU/HUACkbeacOQSj6

## Context (required)

Link to the webpage:
https://dropdown-bug-3fbtnt.flutterflow.app/

I want have a textField generated from a Supabase Query, so I created a component to do this
![image](https://user-images.githubusercontent.com/36147203/211691762-94b0f76b-47fe-44fc-9760-ca3d263f8dea.png)

## Screenshots / recordings

As you can see the keyboard is closed automatically when is touched the textField from the component

https://user-images.githubusercontent.com/36147203/211691955-5cddfc8a-d367-462d-8820-294af3329885.mp4

To solve the problem is necessary to touch the textField that is not a component so the problem is solved but it has another problem. When the focus is in the textField from the component when I use the android navigation system to go back the keyboard does not close and instead is changed the focus to the other textField

https://user-images.githubusercontent.com/36147203/211692138-6b7f18ec-e830-4fec-94e0-fd18d613a74b.mp4

## Your environment

* Version of FlutterFlow used: 10 January
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by fafa16** [comment]
Hi, I have the same bug and I am stucked with it... dynamically generated textField in a component makes the keyboard pops out/in.....
It worked fine before having to put the textField into a component...

**Comment by Pepino-GR** [comment]
Hi Franco98404,

I can reproduce this issue and set it as a bug.

**Comment by wenkaifan0720** [comment]
Hi all. I think this issue is related to this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/391 and this one: https://github.com/FlutterFlow/flutterflow-issues/issues/279. I have pushed a fix for it but it is not live yet.

**Comment by Franco98404** [comment]
Ok, thanks. I will check in the next update to check and close the ticket if it is solved!

**Comment by Franco98404** [comment]
Now I have tested and it is solved! Thanks
