### ISSUE TITLE
Warnings on deprecated functions for function load methods (web)

### ISSUE THREAD

**Issue by Alpay8** [FlutterFlow/flutterflow-issues#3400]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When building our company application on the web using FlutterFlow, the automated FlutterFlow tool overwrites the index.html file, including the JavaScript onPageLoad methods, which causes us to have these warnings in the console_ Warning: In index.html:52: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:67: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.

### Expected Behavior

To build the application without version / use of deprecated function errors, since this can be a security vulnerabilty and might  lead to problems in the future.

### Steps to Reproduce

1. Update the serviceWorkerVersion: serviceWorkerVersion -> {{flutter_service_worker_version}}
2. Update the Flutterloader.load function: FlutterLoader.loadEntrypoint -> FlutterLoader.load

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-1

### Visual documentation

Just a warning

### Environment

```markdown
- FlutterFlow version: Most recent
- Platform:Web
- Browser name and version: Edge
- Operating system and version affected: Mac (but all OS effected)
```

**Comment by msusviela** [comment]
Hi @Alpay8. We well need more context to reproduce the issue. Please provide a bug report code for this. You can generate one by clicking right on the widget tree and selecting the option to generate one. Also, we will need to know when this issue is triggered. Without this information it's impossible for us to reproduce this issue and fix it.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
