### ISSUE TITLE
Test Mode and Run mode do not show any updated changes

### ISSUE THREAD

**Issue by JassonSpecno** [FlutterFlow/flutterflow-issues#3401]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If i make a change in the dev environment , the change is not reflected in the Test or Run Mode

### Expected Behavior

Once a change has been made it should be reproduced in run or test mode

### Steps to Reproduce

1. Make a change on any page, eample change button text on the login page (LandingPageClient)
2. Open Test mode or Run mode and see if your change has reflected

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESkMmAsItgoelZ0KX9KPpqhQIgQ0QnU7gnlO1ucx40fIvkP4kce+ClR0NKTMCleGxDfWL9jnkdpd7okeDlDfU5AEyZbJRN0JVAEArKcGamMpeYEsyoPXNTHptQJ3Kny4mv2hBRLvBqLlIB1EyLNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/92736bd4-e6ce-41c0-b108-2f177e95f419)
![image](https://github.com/user-attachments/assets/8ac530f6-247d-4fa8-90dc-590866ea3a33)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.72+ released July 12, 2024
- Platform:Web
- Browser name and version: Edge Version 126.0.2592.87
- Operating system and version affected: Windows 11
```

### Additional Information

i cant test any projects

**Comment by paulperez-dev** [comment]
Hi @JassonSpecno! I was unable to reproduce this issue. Notice that in `run mode` you can't reload, you should close the run session and start a new one. In test mode, after making changes, tapping the `instant reload` button updated the UI in my case.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
