### ISSUE TITLE
Flutter Flow FFUploadedFile Crash

### ISSUE THREAD

**Issue by syedmurtaza108** [FlutterFlow/flutterflow-issues#3402]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutter is giving this error:

```
Converting object to an encodable object failed: Instance of 'FFUploadedFile')
```

### Expected Behavior

No crash

### Steps to Reproduce

1. Upload an image to a server from picker image
2. Allow All Exception in debug mode in VS Code
3. You will see a crash in the given code (see screenshot)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohvLlvJR1pbxZ7qrqccJahSQsH2k2U5EvmMpOGDsdF4iuPOxzafekcRNBXe25TFFHKEWLsHkKw6H0vvDyVvoFNRyCGdlqyJdbWA/zdzq/aoSpC7uePEEmEcVTfUy/3J7Q2yJSXbJZSHdlwzqUHPCUYAHtHb37Zwh9f6PHaOI=

### Visual documentation

See this

![Screenshot 2024-07-15 at 16 10 35](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/18074f0f-5e8e-45a2-be12-bd90c165c01e/a7283425-e59a-4c2e-b7ee-71f9c6ee28b4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xODA3NGYwZi01ZThlLTQ1YTItYmUxMi1iZDkwYzE2NWMwMWUvYTcyODM0MjUtZTU5YS00YzJlLWI3ZWUtNzFmOWM2ZWUyOGI0IiwiaWF0IjoxNzIxMDUzNjgzLCJleHAiOjMzMjkxNjEzNjgzfQ.w2RxMOXUCk7qd4sGBlQjA8K1V2Q7j4fg_cLNMmXJc54)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform:Android
- Browser name and version: Desktop App Mac OS
- Operating system and version affected: Mac OS
```

### Additional Information

*No response*

**Comment by msusviela** [comment]
I'm sorry but we are unable to reproduce this issue from a blank project, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with ensuring your project is configured correctly!
