### ISSUE TITLE
Stripe without Firebase

### ISSUE THREAD

**Issue by andreasvonfeld** [FlutterFlow/flutterflow-issues#3403]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I have had a problem for several days that is blocking me in my project. I'm building a mobile app on Flutterflow and trying to implement payments with Stripe except I'm using Xano as my database. Can you help me implement Stripe without using Firebase.

### Expected Behavior

I would like to use Stripe widget without Firebase

### Steps to Reproduce

1. Go to Stripe settings

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeksrq05NPj7xa1rXUKsFGpwMwJ0QlUIInj+0bWRMhfevzBIkqfs77alZLYteGTUFUeEyKpHkHwejKhezLLfE4PgWtQYhO1a5XQT3/UlGjVLa3CaisVUB6M5pVJlPH58G02wlSFLBfR1Is2U6xevCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Capture d'écran 2024-07-15 141013](https://github.com/user-attachments/assets/4068b83f-85a1-4d52-9c4f-3fee7cd6d858)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform: Web
- Browser name and version: Google Chrome
- Operating system and version affected: Windows
```

### Additional Information

I want to use Stripe without using Firebase

**Comment by andreasvonfeld** [comment]
![image](https://github.com/user-attachments/assets/8c12b2e6-7479-4930-9f8d-065ad468e07c)
here are the errors

**Comment by rzambroni** [comment]
Hi @andreasvonfeld, 

Unfortunately, what you're trying to accomplish is impossible at the moment on FlutterFlow. Because FF uses [Firebase Cloud Functions](https://firebase.google.com/docs/functions) to process a transaction using the Stripe payment provider.

I'll ask internally if we can add this as a feature request and let you know. 

Thanks for the feedback.
