### ISSUE TITLE
Currently, when I try to scroll using the stylus or finger in interfaces such as widget menus, widget trees, and widget panels in my FlutterFlow project, the system does not scroll as desired. Instead, dragging elements is triggered unintentionally, resulting in an unwanted relocation of these elements within the interface.

### ISSUE THREAD

**Issue by julian03280** [FlutterFlow/flutterflow-issues#3404]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, when I try to scroll using the stylus or finger in interfaces such as widget menus, widget trees, and widget panels in my FlutterFlow project, the system does not scroll as desired. Instead, dragging elements is triggered unintentionally, resulting in an unwanted relocation of these elements within the interface.

### Expected Behavior

 I expected that when using the stylus or finger to scroll in the mentioned areas, the page or panel would scroll vertically in a similar way to how it is done with a mouse, without interfering or modifying the position of the elements within the interface . It doesn't help me to scroll with 2 fingers, since I use the touch pen or just 1 finger, but specifically it is urgent to be able to do it with the touch pen.

### Steps to Reproduce

Access the widgets dashboard in FlutterFlow.
Use a touchscreen device to try to scroll through the widget list or page tree.
Try to scroll vertically using the stylus or finger.
Notice that instead of scrolling, the widgets move or reorder without intention.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NEW

### Visual documentation

https://github.com/user-attachments/assets/97335168-fadf-4ffb-8e1d-41618e69f42f

https://github.com/user-attachments/assets/edc9b642-f64c-4b55-b02d-211d177cf96a

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: 

The problem is in the web version I use the Google Chrome browser I also tried with Firefox I also tried with Microsoft edge etc... In all browsers the problem persists
in the desktop version of Windows the problem is exactly the same
```

### Additional Information

This issue significantly impacts my ability to efficiently develop and manage applications in FlutterFlow. It is crucial for the continuity of my work that this behavior is corrected, as it prevents the efficient use of the platform's functionalities.

I appreciate your attention and prompt collaboration to solve my problem, thank you very much.

My name is Julián David Contreras,

I have been a PRO member for several months.

Contact: julian.linux0328@gmail.com
flutteflow user: julian.linux0328@gmail.com

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I can confirm this behavior, as I also have a touch screen laptop with a stylus and have experienced similar issues while working on personal projects.

Although this issue tracker is intended for specific FlutterFlow bugs that block users from developing their projects and can be replicated in a new blank project, as mentioned in the README of this GitHub repository, this seems more like an enhancement/feature request.

I will pass this along to the engineering team's backlog as a feature request/enhancement.

Best regards,<br>Azanello
