### ISSUE TITLE
why can't i use the flutterflowtheme package when i upgrade the version to the latest version 3.0.1

### ISSUE THREAD

**Issue by Enchantedwyf** [FlutterFlow/flutterflow-issues#3405]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

why can't i use the flutterflowtheme package when i upgrade the version to the latest version 3.0.1

### Expected Behavior

why can't i use the flutterflowtheme package when i upgrade the version to the latest version 3.0.1

### Steps to Reproduce

why can't i use the flutterflowtheme package when i upgrade the version to the latest version 3.0.1

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Undefined name 'FlutterFlowTheme'. Try correcting the name to one that is defined, or defining the name

### Visual documentation

![2f7fe12ae976e033dcf3b042e6b4bd2](https://github.com/user-attachments/assets/9aaf42d3-515e-4758-83ae-148dfd21369b)
![67a039b3f3d6f1a5dc695d54d505947](https://github.com/user-attachments/assets/ba282d6d-fe5c-4392-9e40-b42b9468bae8)

### Environment

```markdown
- FlutterFlow version: 3.0.1
- Platform:windows
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: win 10
```

**Comment by msusviela** [comment]
Hi @Enchantedwyf. Thanks for filling in but it's necessary that you provide more information so we are able to look into it from our side. Please, provide the steps to reproduce the issue from a blank project and also a bug report code. You can generate it by clicking right on the widget tree and selecting the Generate bug report option. This guide might help you: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)<br>Without the necessary information it would be impossible for us to pinpoint the issue.<br>Thanks!

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by 0x384c0** [comment]
FlutterFlowTheme was removed at [33aa005](https://github.com/FlutterFlow/flutterflow-ui/commit/33aa00515b9430af80879467679809a0d89cf033#diff-2a0661bc3dc226c293b94c422307ff3dbcdc2019fd34699bcd3377062fd95a42L637)
Could find better solution but copying code for FlutterFlowTheme manually back to project and using it for now.

**Comment by Elansari-Jaafar** [comment]
Hi @0x384c0 please how can i do that i searched everywere for the FlutterFlowTheme class in flutterflow

**Comment by 0x384c0** [comment]
`FlutterFlowTheme ` can be found in one of the old versions of file [flutter_flow_theme.dart](https://github.com/FlutterFlow/flutterflow-ui/blob/9eba90363c9b230d5b9b4558696a35a014306f51/lib/src/flutter_flow/flutter_flow_theme.dart)
