### ISSUE TITLE
Max char in text field doesn't reflect variable value

### ISSUE THREAD

**Issue by caringan** [FlutterFlow/flutterflow-issues#3407]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attach a variable to maxChar of Text. Did not get the variable value.

### Expected Behavior

maxChar should reflect value in the variable instead of the static value.

### Steps to Reproduce

1. create a text widget
2. attach a variable to the maxChar field
3. variable value did not reflect in the text widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XlcmA04lIobhb7qXxbcFVimAsQ207a4JEi+5+WRQ1GLb3E+wcefT+T2xaTdPmSn03MWCJ/Wcep+jFvszIN8IBAxaWGJx91pByZwHKfzmXMq67Dbu8W2tDNNpKCB2g1rarqxFDANFYV3gZ3DmmfOzIYAvUJ4DTO0U7GP6KFKnXs3fuQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="552" alt="Screenshot 2024-07-15 at 10 32 02 PM" src="https://github.com/user-attachments/assets/f14048ba-4174-4f79-9aac-af41547d5171">
<img width="227" alt="Screenshot 2024-07-15 at 10 32 15 PM" src="https://github.com/user-attachments/assets/e4f20d76-68b7-4a9a-9289-730638de61a7">

### Environment

```markdown
- FlutterFlow version: v4.1.72
- Platform: MacOS Desktop
- Browser name and version: -
- Operating system and version affected: macOS
```

**Comment by Alezanello** [comment]
Hello!

We're sorry you're facing this issue, and thank you for sharing it with us!

The good news is that this is a known issue, and the engineering team already has it in the backlog for a fix. You can subscribe to the first post to get the latest updates on the progress of this fix: [FlutterFlow Issue #3016](https://github.com/FlutterFlow/flutterflow-issues/issues/3016).

I will close this as a duplicate.

Best regards,<br>Azanello
