### ISSUE TITLE
Write vs. Update Confusion in Firestore Rules

### ISSUE THREAD

**Issue by Tyg-g** [FlutterFlow/flutterflow-issues#3409]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the `Firestore Rules` section, setting the rules under the `Write` column applies an `allow write:...` rule for the given collection.

### Expected Behavior

It should apply an `allow update:...` rule.

The documentation explicitly states that the `Write` column rules are about updating the document: https://docs.flutterflow.io/data-and-backend/firebase/firestore-database-cloud-firestore/firestore-rules

Since the generated security rules always include the `Create` and `Delete` fields, in the end it works as expected probably in all cases, but: 1. It can create confusion about what rules are applied and how, 2. It can cause a problem in the future if some rules are changed manually or if your product changes how the security rules are applied.

### Steps to Reproduce

None.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: v4.1.72+
- Platform: Web
- Browser name and version: Opera 112.0.5197.24
- Operating system and version affected: all
```

**Comment by msusviela** [comment]
Thanks for the report! Since it works as expected we're not considering that as a bug, but I've created a feature enhancement request so the team can check on this!
