### ISSUE TITLE
SwipeableStack 'Flicker' Issue and FlippableCard in SwipeableStack Retains Flip Position

### ISSUE THREAD

**Issue by jryankennedy** [FlutterFlow/flutterflow-issues#3410]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

BUG 1:
When swiping through a stack, the background "flickers" from the previous card back to the current card design. See video recording. See also: https://community.flutterflow.io/widgets-and-design/post/swipeablestack-flicker-L0oIwoPMOLCJ1pI

BUG 2:
Normally, when Ising a FlippableCard inside of a SwipeableStack, a user can flip a card over, swipe the card away, and the newly presented card is facing forward. The bug I have now is keeping the 'back' flipped state. So, if a user flips a card over, then swipes it away, the newly presented card is flipped to the 'back' side. I am creating a trivia app, so this breaks the app's functionality entirely by showing the user the answer before they can see the question.

### Expected Behavior

BUG 1:
Cards should retain their design and not flicker to the previous design for a moment.

BUG 2: 
FlippableCards should either always present themselves as facing forward, or there should be an option inside of FlutterFlow to control the card's flip orientation. (I recommend both)

### Steps to Reproduce 'Flicker' Issue (Bug 1)

1. Create page
2. Add SwipeableStack
3. Wrap the SwipeableStack in a Container
4. Backend query some data from the Container
5. Generate children from variable on the SwipeableStack
6. Add a FlippableCard to the SwipeableStack
7. In the FlippableCard, add a Backend query to query another collection that uses a filter to match the previous query collection.

### Steps to Reproduce FlippableCard Flip Position Error  (Bug 2)

Create page
Add SwipeableStack
Backend query some data from the SwipeableStack
Add a FlippableCard to the SwipeableStack
Display that data in the FlippableCard

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz8jf5c1NochE16XxKcEwuCIwGVAIa5IRlexuZxEbCIzaB4YMZPWkXBBvXteiTGxqPkSmmns1+fzqhuP9KcE3B0udbKp/zcxqWwzhXmKtUZOBBqisZXZ7I51QFUCy0cGJoRMkCMdsdCUH2WCqCfCydA/cN7L4IlFISq/LZO4=

### Visual documentation

Bug 1:
https://github.com/user-attachments/assets/8304e79c-e75e-4c3f-b429-35b4182d2db6

Bug 2:
https://github.com/user-attachments/assets/9adb86e8-b66f-4b01-81af-890aac5912a3

### Environment

```markdown
- FlutterFlow version: v4.1.72 Synced
- Platform: MacOS Desktop
- Browser name and version: N/A
- Operating system and version affected: All
```

### Additional Information

Bug 1: I am trying to create a simple trivia app with cards, but this flickering issue is not a good user experience and is preventing me from releasing the app.

Bug 2: I can't release a trivia app that shows answers first :(

**Comment by msusviela** [comment]
Hi @jyrankennedy<br> I was not able to replicate the issues from blank. I'll suggest to reach out to [support@flutterflow.io](mailto:support@flutterflow.io). They can better assist you with ensuring your project is configured correctly.
