### ISSUE TITLE
Firebase Remote Config deletes the wrong config if filtered by text

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#3411]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you search/filter by text your Firebase remote configs and you delete one, it uses the index wrongly and deletes other config than intended.
After deleting it, you still can see the previous ones, but the wrong one was deleted.

### Expected Behavior

Delete the right config.

### Steps to Reproduce

Add many firebase remote configs, filter by text and try to delete one in particular. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMmBx89PsctJ0LXube9VvCYRKUA6U40WlsFuUQobfJTxG7l3WvfObhJUcN/gYH9EJFn8+XMX/MqPiuD1UccoKTasQaI5+c1udxbMZFqWRrqgPr63b3BTN/FXChG9yrSnvhRDHMhfdXwA2jn7O+utf3XXGITyO2oZReaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1885" alt="Captura de pantalla 2024-07-16 a la(s) 2 15 43 p  m" src="https://github.com/user-attachments/assets/3047e960-50e0-4f2f-93d9-afa4e5a9b3c1">

### Environment

```markdown
- FlutterFlow version: v4.1.72+
- Platform: Web
- Browser name and version: Chrome v. 126.0.6478.127 (Build oficial) (arm64)
- Operating system and version affected: Mac
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by pstatile** [comment]
Awesome, thank you so much!
