### ISSUE TITLE
FlippableCard in SwipeableStack Retains Flip Position (Instead of resetting to the front position)

### ISSUE THREAD

**Issue by jryankennedy** [FlutterFlow/flutterflow-issues#3412]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Normally, when Ising a FlippableCard inside of a SwipeableStack, a user can flip a card over, swipe the card away, and the newly presented card is facing forward. 

The bug I have now is keeping the 'back' flipped state. So, if a user flips a card over, then swipes it away, the newly presented card is flipped to the 'back' side.

I am creating a trivia app, so this breaks the app's functionality entirely by showing the user the answer before they can see the question.

### Expected Behavior

FlippableCards should either always present themselves as facing forward, or there should be an option inside of FlutterFlow to control the card's flip orientation. (I recommend both)

### Steps to Reproduce

1. Create page
2. Add SwipeableStack
3. Backend query some data from the SwipeableStack
4. Add a FlippableCard to the SwipeableStack
5. Display that data in the FlippableCard 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz8jf5c1NochE16XxKcEwuCIwGVAIa5IRlexuZxEbCIzaB4YMZPWkXBBvXteiTGxqPkSmmTkH0fDKkYXPO8Y6G0yuR75g+YdubwHycGeta5OBBqisZXZ7I51QFUCy0cGJoRMkCMdsdCUH2WCqCfCydA/cN7L4IlFISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/9adb86e8-b66f-4b01-81af-890aac5912a3

### Environment

```markdown
- FlutterFlow version: v4.1.72 July 16 2024
- Platform: MacOS, Web
- Browser name and version: N/A
- Operating system and version affected: All
```

### Additional Information

I can't release a trivia app that shows answers first :(

**Comment by Alezanello** [comment]
Hello!

Thank you for your message. I noticed that you posted another issue regarding the same topic. To keep things organized, I will close this issue as a duplicate. You can continue to follow updates on your original issue here: [Issue #3410](https://github.com/FlutterFlow/flutterflow-issues/issues/3410).

Have a great day!
