### ISSUE TITLE
Adding markdown widget results in build error

### ISSUE THREAD

**Issue by uxmaggiexu** [FlutterFlow/flutterflow-issues#3414]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! When I add a markdown widget, I get this build error in both test and run mode:
Because markdown depends on flutter_markdown 0.6.23 which depends on markdown ^7.1.1, markdown ^7.1.1 is required.
So, because markdown is 1.0.0+1, version solving failed.

Test and run modes work fine when markdown widget is removed.

### Expected Behavior

View markdown text in test and run mode with no error.

### Steps to Reproduce

1. Drag markdown widget into default column of blank project
2. Click test or run mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfi/Lqw412sbQD1pSJYcFvoDg7NjIcTIBMiuxEVRMbfL7rBqQIP8neSxNpZMCqaVNcAlebsH8E0fD7udrtKccCPQysfKJnyblQeArke2i6b4TQBc28fGt7LNNTfH6a5sKF2RNAHNZiSlIS3GaYC+iAZD7DIuu/Zwh9f6PHaOI=

### Visual documentation

<img width="678" alt="image" src="https://github.com/user-attachments/assets/fc839b43-0911-4411-99b3-ae2d4ec09966">
<img width="1361" alt="image" src="https://github.com/user-attachments/assets/703da0e5-c1af-4276-9207-c7f60f495afc">

### Environment

```markdown
- FlutterFlow version: v4.1.72+ released July 12, 2024
- Platform: Web, MacOS Desktop
- Browser name and version: Chrome 126.0.6478.127
- Operating system and version affected: macOS Monterey 12.4
```

### Additional Information

I was trying to incorporate markdown text in another project to better format content but was getting an error. I tried adding a markdown widget to a blank project to troubleshoot and got the error reported above. Thanks!

**Comment by paulperez-dev** [comment]
Hi @uxmaggiexu! So sorry you are facing this issue. I was unable to reproduce this error. I added the markdown and tested it: all ok. Changed the text to the one you have in your project and tested it again: all ok.

Did you change any property/configuration on your project other than adding the markdown?

**Comment by uxmaggiexu** [comment]
Thank you for checking! For whatever reason the issue resolved itself this morning without me doing anything. Thank you for your time!

**Comment by paulperez-dev** [comment]
Hi @uxmaggiexu! Thanks for the confirmation!
