### ISSUE TITLE
Can't clear "Hint Text" from an "EditField"

### ISSUE THREAD

**Issue by esiemann** [FlutterFlow/flutterflow-issues#3415]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When assigning a "Hint Text" to a TextField in FlutterFlow, multiple empty fields for translation are automatically generated in the languages screen. However, there is no direct way to delete these empty translations if a value is later entered in the original text field. The only workaround found so far is to recreate the EditField.

### Expected Behavior

FlutterFlow currently doesn't allow disabling translations for empty "Hint Text". It would be helpful if it ignored empty translations or provided a button labeled "Disable translations of this text" to disable the translation option for specific fields. As a workaround, I had to recreate the TextField.

### Steps to Reproduce

1. Create a new Project

2. Add 2 languages

3. Create a new Page

4.  Add an EditField to a Home with 2 languages:

![screenshot50](https://github.com/user-attachments/assets/db995ca1-94a2-4cdb-9ced-6701bfa1b83b)

5. The languages ​​screen correctly shows translated texts:

![screenshot47](https://github.com/user-attachments/assets/64c1d57f-babf-4400-a63e-14a407af1e19)

6. Then fill in the "Hint Text" with some value:

![screenshot51](https://github.com/user-attachments/assets/142cba38-1191-4f4c-aca7-cdbd3368087e)

6. Delete the "Hit Text":

![screenshot52](https://github.com/user-attachments/assets/27961f96-ac20-4c8d-83f0-20fb51f471b7)

7. Go to languages screen,  an empty field is shown:

![screenshot55](https://github.com/user-attachments/assets/dbae0ce9-2b94-4e8d-8524-8bff6bcbd831)

If you repeat the same process, there are still many empty translations:

![screenshot60](https://github.com/user-attachments/assets/cfad770f-528b-422f-a9ee-14c58db0ed64)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89godtE17XqLO9VliMRNnI+aoc0sdlud0wdCoDuBIk+ZPWlbhNWOdfhd2x6P0SmmTsx0s7zvofiGvE3FzaBfoBk1KVQWA3hWnuua5OBCcyKS3BRN5hnIWLA1MPQuxNSWfdpcVIu7E+MfOjKTXbvQpzBImdISq/LZO4=

### Visual documentation

![screenshot60](https://github.com/user-attachments/assets/5fd7117e-a941-44da-bae5-98cc79a31e23)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform: Web
- Browser name and version:  Chrome 126.0.6478.126, Firefox 128.0
- Operating system and version affected: Linux Ubuntu 22.04
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I was able to replicate the issue and understand the inconvenience it causes. I will forward this to our engineering team for review and a possible fix, including the addition of the delete button as you suggested.

Thank you again!
