### ISSUE TITLE
Mac Local Run does not support carousel

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#3416]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When testing in Simulator on Mac, it throws an error. Surprisingly works fine in Test mode. 
<img width="788" alt="image" src="https://github.com/user-attachments/assets/5a068c00-4f8d-4caa-b9df-2aa20d3a5024">

### Expected Behavior

Should run OK in Simulator

### Steps to Reproduce

1. Create new page
2. Add carousel
3. Local run to test in iOS simulator on Mac

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohcrq4c9JpbxK0LXyb8FvryQ7OUw8bIEvmspBZzwgF5DoOoYIY8/QP01BXdenS1VifWC2p14K7sr7iPLxLvkoOU2Ab4dx+M56ahbhQTmQMIuTF7mwQ0FRFp9Mfm2B5J2zpyQmLbdeWlof7DmXfuiuQincHr72IFQ4Sq/LZO4=

### Visual documentation

<img width="788" alt="image" src="https://github.com/user-attachments/assets/5a068c00-4f8d-4caa-b9df-2aa20d3a5024">

### Environment

```markdown
- FlutterFlow version: 4.1.72 
- Platform:Mac
- Browser name and version: Chrome Version 126.0.6478.127
- Operating system and version affected: MacOS 14.5 (23F79)
```

**Comment by Alezanello** [comment]
Hello!!<br><br>Did you try it with the last updated FlutterFlow Mac version?<br>At least from my side i just created the new project, added carousel and worked fine in Simulator

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/740de4ab-e8ec-4692-abfe-92e2ade49886/c724e114-ffcb-419d-8782-d1c9e7d1532f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NDBkZTRhYi1lOGVjLTQ2OTItYWJmZS05MmUyYWRlNDk4ODYvYzcyNGUxMTQtZmZjYi00MTlkLTg3ODItZDFjOWU3ZDE1MzJmIiwiaWF0IjoxNzIxMzkyODA2LCJleHAiOjMzMjkxOTUyODA2fQ.TJ0o1889aNqASaHB50bjWkFLZ2J7HbhGuIVmFG1SzFQ " alt="Imagen de WhatsApp 2024-07-19 a las 09.38.20_a18f0d06.jpg" width="1280" height="800" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
