### ISSUE TITLE
I can't save any changes

### ISSUE THREAD

**Issue by fdelgadofocus** [FlutterFlow/flutterflow-issues#3417]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm getting a network disconnected screen.
with a message "The project is not currently connected to our servers".....

### Expected Behavior

Every time I do a change and try to save it with ctr+s it doesnt save, or if I need to a an action on any action chain it shows me the same scrren

### Steps to Reproduce

1. Open an existing page
2. Look for any action chain 
3. Try to add a new action on that chain.
4. Th error appears

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I CANT GET IT

### Visual documentation

![NETWORKDISCONNECTED](https://github.com/user-attachments/assets/85279ff2-3834-4fb6-ae99-9dc7fb31d68f)

### Environment

```markdown
- FlutterFlow version: v4.1.72+
- Platform: Windows
- Browser name and version: edge
- Operating system and version affected: Windows 11
```

### Additional Information

I have not been able to continue working since friday. 07/12/2024

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. I noticed that you are using the Desktop Version. Have you tried checking if the same error occurs in the Web Version?

**Comment by Alezanello** [comment]
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/79ddf68d-8d1c-4991-84fa-b67108053577/f12259f4-506c-4226-b3df-2cabf346eb40?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83OWRkZjY4ZC04ZDFjLTQ5OTEtODRmYS1iNjcxMDgwNTM1NzcvZjEyMjU5ZjQtNTA2Yy00MjI2LWIzZGYtMmNhYmYzNDZlYjQwIiwiaWF0IjoxNzIxMjE4ODc5LCJleHAiOjMzMjkxNzc4ODc5fQ.TE0vlhfsB_5fMIf0NtILv5Uf9CV579JSce0vNvhEEC0 " alt="image.png" width="1919" height="1028" />

n the meantime, I checked the FlutterFlow Windows Version and didn't encounter any issues. I was able to save without any problems. Could you please generate a Bug Report Code from your project so we can determine if this is a project-specific issue?

To generate a Bug Report Code, right-click on any widget in the widget tree and select the option to generate it.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/85972d76-a706-4706-92d7-0e14abe4b39d/26175e2d-5745-4637-9e9f-b3057c49b3e6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NTk3MmQ3Ni1hNzA2LTQ3MDYtOTJkNy0wZTE0YWJlNGIzOWQvMjYxNzVlMmQtNTc0NS00NjM3LTllOWYtYjMwNTdjNDliM2U2IiwiaWF0IjoxNzIxMjE4ODc5LCJleHAiOjMzMjkxNzc4ODc5fQ.cXQBtmfFmBzu1Bfw2C0la40yadaCiUXn6mnWeA3QvX4 " alt="image.png" width="632" height="464" />

**Comment by fdelgadofocus** [comment]
![image](https://github.com/user-attachments/assets/10df5ecc-b544-415c-8787-527d519080ff)

**Comment by fdelgadofocus** [comment]
Same error on the web version.
today I updated the version and still doesnt work

**Comment by fdelgadofocus** [comment]
Actually is project specific because I created a new blank project and that one doesn't have any problem, the project I have issues with is NandoApp

**Comment by fdelgadofocus** [comment]
But I also duplicated the project with issues and even in the duplicated one doesn't let me do anything, it is really frustrating I've been almost one week without being able to advance on anything because of this issue.

**Comment by fdelgadofocus** [comment]
I lost a client already because I didn't show any advance, I'm about to loos 2 more, because I'm not able to continue with this project,

**Comment by fdelgadofocus** [comment]
nothing works, Im convinced FF is not at all a pro platform, this would never happen in a real development environment, that everything get freeze and unable to fix the issue since everything is on the cloud.

**Comment by Alezanello** [comment]
Hello,

I'm so sorry for the late response. I haven't been able to replicate this issue, and with the tools I have, I can't further diagnose the problem, especially since you can't generate the Bug Report Code. This needs to be addressed by support. Please contact them via the in-app chat or at support@flutterflow.io. They have the right tools for these cases.

This GitHub Issue tracker is intended for issues that can be replicated from a new blank project, and this seems to be a more project-specific case. I'm sorry I can't help you further with this issue.

Best regards,<br>Azanello

**Comment by fdelgadofocus** [comment]
https://drive.google.com/file/d/1oO9thPfZXCGNaS9UG4u6Ztv7lbvqLMZM/view?usp=drive_link

here is the link of an screencast i shared with ***@***.***

You will see what is happening to my project, I don't know what realy 
happened since everything was working good and from one moment to the 
other everything stop  working, tha app runs but since I have some 
actions disable for testing purposes I cant enable them back since it is 
not saving anything.

On 2024-07-22 08:18, Alezanello wrote:

> Hello,
> 
> I'm so sorry for the late response. I haven't been able to replicate 
> this issue, and with the tools I have, I can't further diagnose the 
> problem, especially since you can't generate the Bug Report Code. This 
> needs to be addressed by support. Please contact them via the in-app 
> chat or at ***@***.*** They have the right tools for these 
> cases.
> 
> This GitHub Issue tracker is intended for issues that can be replicated 
> from a new blank project, and this seems to be a more project-specific 
> case. I'm sorry I can't help you further with this issue.
> 
> Best regards,
> Azanello
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/FlutterFlow/flutterflow-issues/issues/3417#issuecomment-2242817590
[2]

**Comment by fdelgadofocus** [comment]
Any word on this issue, it has been more than a week unable to do any changes to the project, is there a real solution for this or what are the options I have, I've been on the Software industry for 28+ years using all kinds of tools and I have never had any experience like this one , unable to make changes to my project becaue the tool IDE doesn't handle the its own error codes,

**Comment by fdelgadofocus** [comment]
Any word on this they told me today everything was going to be ok but it is 7:00 pm and I can't do anything yet, it has been 15 days since I did the last edition to my project, I need to know if this is a JOKE or what again, it is not possible that due to the IDE I'm not able to edit my project.
I already sent more than 5 videos so far but nobody solves the issue, so I need to know if someone is even checking the problem I have.

**Comment by fdelgadofocus** [comment]
here it is the bug code that is being generated
IT4kivLlvJROj7xY17X5be5KvCcRJUs4TLIFse0aRR4gIo/mELMQPvekV0NKT8vmdws/I06YmTkD+t7shePLDfA5NSicba5I0JVAaQzwfH6XRc23CqWCP3wnHcdVG2Kl08OVnQp5BMxqLE4E7GClNq3qNleeY8aSfxBlZ7vfcPo=

**Comment by fdelgadofocus** [comment]
IT4kivLlvJROj7xY17X5be5KvCcRJUs4TLIFse0aRR4gIo/mELMQPvekV0NKT8vmdws/I06YmTkD+t7shePLDfA5NSicba5I0JVAaQzwfH6XRc23CqWCP3wnHcdVG2Kl08OVnQp5BMxqLE4E7GClNq3qNleeY8aSfxBlZ7vfcPo=

**Comment by rzambroni** [comment]
Hey @fdelgadofocus,

Sorry about the delayed answer, we are currenty not able to replicate but i'm asking internally to see if we can get this investigated by an engineer as it might be something very specific to you or your project or configuration.

Thanks for the patience.

**Comment by fdelgadofocus** [comment]
My patience is over 16 days without a solution, open my project and try 
to erase the form called BOORA_SALDOS, THEN SAVE THE PROJECT AND OPEN IT 
AGAIN IT DOESNT SAVE ANYTHING, THEN IF YOU TRY TO ADD ANY ACTION TO ANY 
FORM  IT NEVER SHOWS THE SYNCED MESSAGE IT ALWAYS SHOWS YOU THE NOT 
SYNCED STATUS.

THE SAME HAPPENS TO ANY WEB OR LOCAL VERSION,

THE ANSWER YOU ARE GIVING ME IS THE SAME ANSWER I HAVE RECEIVED SINCE I 
REPORTED THIS ISSUE I NEED SOMEONE IF IT IS POSSIBLE CALL ME AND SEE IF 
HE OR SHE CAN SOLVE THIS TODAY.

On 2024-07-31 13:14, rzambroni wrote:

> Hey @fdelgadofocus [1],
> 
> Sorry about the delayed answer, we are currenty not able to replicate 
> but i'm asking internally to see if we can get this investigated by an 
> engineer as it might be something very specific to you or your project 
> or configuration.
> 
> Thanks for the patience.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/fdelgadofocus
[2] 
https://github.com/FlutterFlow/flutterflow-issues/issues/3417#issuecomment-2260990957
[3]

**Comment by fdelgadofocus** [comment]
It never get SYNCED so it is not saving any change to any component .

On 2024-07-31 13:14, rzambroni wrote:

> Hey @fdelgadofocus [1],
> 
> Sorry about the delayed answer, we are currenty not able to replicate 
> but i'm asking internally to see if we can get this investigated by an 
> engineer as it might be something very specific to you or your project 
> or configuration.
> 
> Thanks for the patience.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/fdelgadofocus
[2] 
https://github.com/FlutterFlow/flutterflow-issues/issues/3417#issuecomment-2260990957
[3]

**Comment by fdelgadofocus** [comment]
I there anyone available to solve it today?

On 2024-07-31 13:14, rzambroni wrote:

> Hey @fdelgadofocus [1],
> 
> Sorry about the delayed answer, we are currenty not able to replicate 
> but i'm asking internally to see if we can get this investigated by an 
> engineer as it might be something very specific to you or your project 
> or configuration.
> 
> Thanks for the patience.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/fdelgadofocus
[2] 
https://github.com/FlutterFlow/flutterflow-issues/issues/3417#issuecomment-2260990957
[3]

**Comment by rzambroni** [comment]
I understand the issue you're facing, but since we don't have write permissions, we're unable to replicate it on our end. That's why @azanello recommended that you reach out to support for a more in-depth analysis.

I understand your frustration and am inquiring internally to see if anyone can assist further. However, the best course of action is to contact support directly for a resolution.

**Comment by fdelgadofocus** [comment]
That is whay IM TRYING TO DO.

On 2024-07-31 13:22, rzambroni wrote:

> I understand the issue you're facing, but since we don't have write 
> permissions, we're unable to replicate it on our end. That's why 
> @azanello [1] recommended that you reach out to support for a more 
> in-depth analysis.
> 
> I understand your frustration and am inquiring internally to see if 
> anyone can assist further. However, the best course of action is to 
> contact support directly for a resolution.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/azanello
[2] 
https://github.com/FlutterFlow/flutterflow-issues/issues/3417#issuecomment-2261003360
[3]

**Comment by fdelgadofocus** [comment]
The project is public now so you can access it .

https://app.flutterflow.io/project/nando-app-0zpu00

On 2024-07-31 13:22, rzambroni wrote:

> I understand the issue you're facing, but since we don't have write 
> permissions, we're unable to replicate it on our end. That's why 
> @azanello [1] recommended that you reach out to support for a more 
> in-depth analysis.
> 
> I understand your frustration and am inquiring internally to see if 
> anyone can assist further. However, the best course of action is to 
> contact support directly for a resolution.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/azanello
[2] 
https://github.com/FlutterFlow/flutterflow-issues/issues/3417#issuecomment-2261003360
[3]

**Comment by Alezanello** [comment]
Hello!

The engineering team has notified us that this issue should be fixed in the latest FlutterFlow update. Could you please confirm if everything is now working as expected?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
