### ISSUE TITLE
Firestore query: You can't use the not-in operators in OR queries.

### ISSUE THREAD

**Issue by Gosten** [FlutterFlow/flutterflow-issues#3418]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to use _Not-in_ filter in firebase query, I get error:
You can't use the not-in operators in OR queries.

Error suggests that I'm using OR condition, which I'm not. See screenshot.
![image](https://github.com/user-attachments/assets/881d3f85-ace3-48b8-9a0d-c07fb160a7ff)

### Expected Behavior

Query not-in filter should work without any errors

### Steps to Reproduce

1. Create firebase query on page (no matter if it's on widger or in action flow). Eg. query users collection
2. Create temporary page state list, eg. _emptyList_, type _list(String)_. It will be used for filtering purpose
3. Add filter to query: email not-in _emptyList_ page state (created in point 2).

After adding filter from point 3, we get error like described above

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hfLlvJR1m7QE+KqNb+9VgiYvNl87aI0R0utubw08J5zKB+wAYvf7P1FWTLyoY1Z6PkyJgnMx1vfqktntEsYEFyiqQNQ+/qVySD3Kf3OnRaq2DqmNfW1fOJtQGEDF08Cv3SUnFONhLkZl7DqTNt+XbHfvNK7rDDAdOMqbJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Loom walkthrough:
https://www.loom.com/share/0703004f6e6d49fe97ab61aa5c464194?sid=39909cf1-37ce-4683-857e-c1e4cd9c0e36

Action error:
![image](https://github.com/user-attachments/assets/0fbd2df1-fd34-425b-b85b-ab13dbe3c268)

Query error:
![image](https://github.com/user-attachments/assets/3b9a89db-a2e6-4f48-93ca-966eb77ee56c)

### Environment

```markdown
- FlutterFlow version: v4.1.72+
- Platform: Web editor. Windows app too
- Browser name and version: Brave browser
- Operating system and version affected: Not relevant
```

**Comment by Alezanello** [comment]
Hello!

I have confirmed this issue and found a workaround while our engineering team investigates and fixes it. When a Query collection is created, it seems to default to "OR". To resolve this, add a second filter, select "AND", and then delete the second filter before generating the Query.

**Comment by Gosten** [comment]
Oh, now that error description makes sense!
Thanks for workaround, I'll test it.
