### ISSUE TITLE
Team Design Library - Theme widgets not saving changes

### ISSUE THREAD

**Issue by Brandborne** [FlutterFlow/flutterflow-issues#3419]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I make changes to a theme widget in my team design library and click save, the changes don't actually save.

### Expected Behavior

When I click save the changes should save.

### Steps to Reproduce

1. Open the widget from the project within the team design library
2. Make any property change
3. Click the save button

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N1obwB+KnQaPlKnSoRI0MdXOczitVEew4bCIj4E7MMf8jCUFtVcMyzaH5cIk2LmkMypNGKhYbfL8E7BzqYbap++c8MFxPPYzmVR822CLWwYH9SRJtYGFzC4cCvkB5BItdhW1Ji7UyYeuSicz+Cf9qOYwx5e6fDbOY=

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: Version 4.1.72 (4.1.72)
- Platform: MacOS App & Browser
- Browser name and version: Safari - Version 16.5 (18615.2.9.11.4)
- Operating system and version affected: MacOS 13.4 (22F66)
```

**Comment by Brandborne** [comment]
Just tried this same on theme widgets from within my app and the same is happening.

**Comment by msusviela** [comment]
Thanks for the report. I'm closing this issue because it's a duplicate of this: [https://github.com/FlutterFlow/flutterflow-issues/issues/3392](https://github.com/FlutterFlow/flutterflow-issues/issues/3392).<br>The ENG team is already working on a fix for this.
