### ISSUE TITLE
Dismiss Custom Dialog not working as expected: it teleports randomly to another page.

### ISSUE THREAD

**Issue by pireslopesvinicius** [FlutterFlow/flutterflow-issues#3420]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Structure of widgets to get the error:
  - A separate component (this is a menu dialog that opens in mouse hover in another component)
  - Which have a mouse region: on the action on mouse exit put a dismiss dialog
  - Add a button bellow the mouseregion and when pressing this button it also should dismiss dialog
 When trying to dismiss from the button it navigates to a random page for no reason.

### Expected Behavior

It should dismiss normally from the on mouse exit or the button click

### Steps to Reproduce

1. Create a separate component (this is a menu dialog that opens in mouse hover in another component in another page)
2. Which have a mouse region: on the action on mouse exit put a dismiss dialog
3. Add a button bellow the mouseregion and when pressing this button it also should dismiss dialog
4. When trying to dismiss from button it navegates to random page.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raC0tGOOvPewQXPfBYlJuOLC0Y2xmJWeammYe/vvemvP9K/EVOTKrQbZ8+bp1ED3ieE26WpiIDquCfm5/DftQG0ie5KWnrRVAA7Fsc3wE2U+IHNnKFzPXJu63Pmo3R/iKUJOK2SrDX1iXc2URm05KZDPz

### Visual documentation

Not needed.

### Environment

```markdown
- FlutterFlow version: v4.1.72+
- Platform: Desktop
- Browser name and version: Desktop
- Operating system and version affected: Windows 10 64 bits
```

### Additional Information

It also seems to happen in other contexts, but I cannot tell the exactly condition, but there is a problem in dismiss custom dialog.

**Comment by pireslopesvinicius** [comment]
Probably need some pages in the project as well

**Comment by pireslopesvinicius** [comment]
Another thing, I've done a workaround which is having a callback function that calls the dismiss not directly in the mouse region on mouse exit and by the function it worked, so, problem something related to the mouse region on mouse exit

**Comment by Alezanello** [comment]
Hello!

First of all, I'm glad you found a workaround in the meantime.

I've been trying to replicate this issue without success. Could you please help me find the root of the issue by creating a new blank project and setting up the exact widgets to replicate the behavior?

Best regards,<br>Azanello

**Comment by pireslopesvinicius** [comment]
Hello, I'll try to reproduce it from blank project

**Comment by pireslopesvinicius** [comment]
I'll send it the bug report link, so you can access it right? Because explaining it's kind hard to explan all the steps to get to it.
But check the project if possible, appreciate the help.

So the steps to get the error by testing the project is:
1. Run the project
2. Hover on the button "Hover here"
3. It opens a popup menu, then click on the first option of the menu (that should close the popup with dismiss popup), then it sends to random page, or to blank page at all.

ITEez/Hqx892pbwF+qrxK8IwpwMwGkQ5a7sviu5+FBQaI+PoOpYcdcnCbklvWOqHT29UBGabpF8H/8Lti9+TV8deBwWabN1IyKoIUxDiLU2jVbqSCqiWSnZ9EcpVCB2vyJ+r2hNCXepvZXgXw0OQBumub3qCf9qOYwx5e6fDbOY=

**Comment by pireslopesvinicius** [comment]
It's a blank project that I created and send it the report bug, if needed I can share the project with you if needed.

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. I ran the project you sent me, and indeed it gives me a blank page. It seems to be related to both the Mouse Hover and the Container being clicked, which dismisses the dialog at the same time. One is updating the navigator context later than the other, causing this error:

`The following assertion was thrown while finalizing the widget tree: Assertion failed: file:///C:/flutter/packages/flutter/lib/src/widgets/navigator.dart:3878:12 !_debugLocked is not true`

Let me try a few more things to pinpoint the issue and see why this is happening.

Best regards,<br>Azanello

**Comment by pireslopesvinicius** [comment]
Okay, thank you very much.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
