### ISSUE TITLE
Still Issue with FlutterFlow Color System

### ISSUE THREAD

**Issue by VIA-SOFTWARE-GMBH** [FlutterFlow/flutterflow-issues#3421]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I already posted an Bug report about the Color adjustment in FlutterFlow.

Color is e.g. Blue, I open the editor, change it to Red - after closing the color editor all seems to be OK, it shows Red.
But after opening the editor again, it shows the former Blue again.

I hadn't contacted you for a few days because the error no longer occurred. Now, strangely enough, it's back again!
(see video)

As I said, the color is e.g. blue (#0000FF)

https://github.com/user-attachments/assets/857ee62d-1f21-40b2-869a-4b1d1792091d

I click on it and change it to red (#FF0000)
After closing the editor, everything looks fine at first, it seems to have taken on “red”.

When I open the editor again, however, either the old value appears
(#0000FF) or the old value with transparency (#300000FF)
or a completely different value, e.g. yellow.

Very strange ...

In any case, I can no longer work with FlutterFlow (if it continues to exist).
Since we are creating a project for a customer (and he wants “his” colors and not some random colors)
this is understandable, don't you think?

Best regards

### Expected Behavior

A well-functioning FlutterFlow color adjustment

### Steps to Reproduce

1. Select Theme Setting / Color
2. Click on a color (e.g. RED #FF0000)
3. In the color editor select BLUE (#0000FF)    
4. Close the color editor
5. All seems to work, the color area now shows BLUE
6. Open the color editor again, and it shows the former vale RED again.

This also happens when I enter the colors manually as hex values, not only with the color picker (mouse)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not possible in this case

### Visual documentation

https://github.com/user-attachments/assets/a38b1c92-393d-456b-a32b-ee280089bb7d

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @ClausFalkenstein. I was not able to reproduce this error from blank.<br>Could you please share the version of FlutterFlow you're using, if you're using the desktop or web version of FlutterFlow, and the operating system you're on?  This info is important for us so we can replicate the issue. Thanks!

**Comment by VIA-SOFTWARE-GMBH** [comment]
Hello,

Operating System:  Windows 10  Pro    Version 22H2 (Build 19045.4651)

FlutterFlow Desktop v4.1.72+ Synced       (Pro Version)     

(I just checked it, the problem also exists if I use your Website version. https://app.flutterflow.io/ )

If you like, you can also try it out directly in my project. I think I have authorized access to it when I posted the bug report.
If not, please let me know what I need to do to give you access.

The project is called “TimeTracker V6” (Edited a few minutes ago today)

Thank you very much for your efforts, I am a SW developer myself and I know 
that the greatest and most inexplicable mistakes can creep in when the day is long.

Best regards
Claus Falkenstein

**Comment by VIA-SOFTWARE-GMBH** [comment]
---------------------------------------------------------------------------------------------------------------------------------------

THIS MIGHT BE AN IMPORTANT HINT THAT COULD HELP TO LOCALIZE THE FAULT:

Incidentally, the whole problem only occurs with newly added (“Add Color”) colors. The whole thing does not happen with the existing colors, everything seems to work!
And I have just noticed that there is a connection between the Light and Dark palettes:

---------------------------------------------------------------------------------------------------------------------------------------

If I change a color in the “Dark Mode Theme”, it works correctly there. After reopening the editor, the previously set color is displayed there, and the hex value is also correct.

If I do this with the “Light Mode Theme” above, it does not work. It is rather the case that the color and the hex value of the color (same name) from the dark mode is always displayed there.

Example:

- “MyColor” is yellow at the bottom in Dark Mode and green at the top in Light Mode.
- Now I change “MyColor” from yellow to blue in DarkMode.
- Light mode then no longer displays green, but blue as well, i.e. the same color as was set in dark mode.

When opening the “Light Mode” Color Editor, the wrong color, namely that of the “Dark Mode”, is probably simply transferred to the dialog.

![Colors](https://github.com/user-attachments/assets/f63b8f03-abbe-4237-b293-664820214218)

**Comment by paulperez-dev** [comment]
Hi @ClausFalkenstein! I could not reproduce any reported issues in the latest Windows version (**v.4.1.74**). Can you please verify how it behaves to you in the newest version?

**Comment by ryutosh** [comment]
@paulperez-dev 
I'm in similar issue in my current project now, and I'm working on web platform, mac os and chrome browser.

**My Light mode colors**
![image](https://github.com/user-attachments/assets/1b949927-db6c-4e21-a54a-7c5b8b07ba49)

**My Dark mode colors**
![image](https://github.com/user-attachments/assets/c0a70fe9-bcd5-48d9-8855-20612c735245)

**Tap color of "Error Container" in Light mode**
It shows wrong value.
![image](https://github.com/user-attachments/assets/65172ed8-4430-4dee-8c8e-bc317f6c89e8)

**Tap same color in dark mode, too**
it's ok.
![image](https://github.com/user-attachments/assets/4402f07b-047c-4c31-a822-9add5f9c1e54)

**Tap color of "On Error Container" in Light mode**
It shows wrong value.
![image](https://github.com/user-attachments/assets/d3235b0a-0013-4b8d-87eb-333647ab175a)

**Tap same color in dark mode, too**
it's ok.
![image](https://github.com/user-attachments/assets/6a426e71-7bdc-4549-90bf-3fd5b9d4ded1)

---

This is my but report code for some page in the project.
ITEehfKB35ZJpbwG1c7qcsJWiQMwJ0QlUIInj+0bWRMhNYzkE5kAYMnBbRJLYteYYWNMGmGZsDgCw/Tqhd/yU/YqA0iubaZj+oRXQQrjWkm6WoyxPZagX3NQL/FYBWHE1sOnhSJDKsVsci0Z3zqACPCdG3qCf9qOYwx5e6fDbOY=

**Comment by paulperez-dev** [comment]
Hi everyone! On the web is easier to reproduce, I will send this to the ENG team so they can work on this.

Edit: It is only reproducible on your project @ryutosh. Can you please try to replicate the issue on a new project and let me know?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
