### ISSUE TITLE
GoogleMap widget Update Page On Move property

### ISSUE THREAD

**Issue by monocat** [FlutterFlow/flutterflow-issues#3425]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have enabled **Update Page On Move** GoogleMap property in order to load documents related to current screen map view.

### Expected Behavior

Load or "filter" documents with LatLngs that are associated to geographics coordinates of current screen map view.

### Steps to Reproduce

1. Create new page
2. Add GoogleMap widget
3. Configure widget to accept multiple markers based on a collection that includes LanLngs.
4. Enable Update Page on Map Move
5. Run to test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Ti/LqyItIrs9b7aXqde9ajjgvQ187a+dJlu1+GEojHOv3PZoQZczSYXFJYeGkTAlqOlmb+WMz0qHRueDyGO4rAwWtU4Ne1KtcSDuVWk66RZPRCpeSYmtTGf1Mf3LG4KuOmA9SVc5hck4gwUzzeuutUirfJJDTClU7Bf3+BLLLpUqcFXnVJDpFxmNecCfn

### Visual documentation

![loading all docs in googlemap widget](https://github.com/user-attachments/assets/f1ccc76a-79e4-4f50-b20e-cd5ee0e9b404)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform: Web, MacOS Desktop
- Browser name and version: Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (x86_64)
- Operating system and version affected: macOS Sonoma 14.5
```

### Additional Information

Project: Map Update Page on Move

**Comment by Alezanello** [comment]
Hello!

Could you try changing the Marker Type from 'Documents' to 'LatLng'? In Marker LatLngs, select the locations Documents, then select the Map List Items, then select Item in List, Get Document Property, and finally select the location field of the document.<br><br>it should end like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7ea68fce-0cb2-4ee7-b415-c9fc7805fd76/82c23060-921a-4a75-9139-b78125f2f2d4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZWE2OGZjZS0wY2IyLTRlZTctYjQxNS1jOWZjNzgwNWZkNzYvODJjMjMwNjAtOTIxYS00YTc1LTkxMzktYjc4MTI1ZjJmMmQ0IiwiaWF0IjoxNzIxMzA3NzMyLCJleHAiOjMzMjkxODY3NzMyfQ.bvQxNqVm_Ka4dMxgMzo8trvOb4Ph97RBXyUSWcqQK2Q " alt="image.png" width="279" height="408" />

<br>Tell me if these works for you!

**Comment by Alezanello** [comment]
At least for me it worked this way

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e78399c7-649f-4815-bda8-3fbfbb93aecb/993a9668-dfd4-41fb-aeeb-ac7b97ed6440?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNzgzOTljNy02NDlmLTQ4MTUtYmRhOC0zZmJmYmI5M2FlY2IvOTkzYTk2NjgtZGZkNC00MWZiLWFlZWItYWM3Yjk3ZWQ2NDQwIiwiaWF0IjoxNzIxMzA4MDQ3LCJleHAiOjMzMjkxODY4MDQ3fQ.2_KwZIvXN3Rbuq5miPMtEdpMPYjtUJIjJjetiw4cB4Q " alt="image.png" width="1146" height="812" />

**Comment by monocat** [comment]
Thanks for the tip @Alezanello Tried that method, but unfortunately, all docs are still loading.

**Comment by Alezanello** [comment]
How did you set the filters for only related location?

**Comment by monocat** [comment]
Please ignore the word "filter". I don't think I was clear enough.

Here's my basic setup.

In the parent widget, I created a Query Collection:
- Collection: "collection name"
- Query Type: List of Documents
- Limit: 32

In the GoogleMap widget:

- Num Markers: Multiple
- Marker Type: Document
- Marker Documents: Document List from the Query

As mentioned, the expectation is that only the documents pertaining to the visible google map on the screen should be loaded, and as I move the map around, the map is rebuilt and corresponding docs are loaded. At least that's my understating of how the Update Page on Map Move should work.

**Comment by monocat** [comment]
@Alezanello Did you have a chance looking into this? Is there an example where this feature is being utilized successfully. I also [asked in the community](https://community.flutterflow.io/ask-the-community/post/how-to-use-googlemap-widget-update-page-on-move-property-Bwy5pZngcx4R9zp) if you can share the example. Would appreciate it.

**Comment by monocat** [comment]
@Alezanello or anyone else. See my previous comment.

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. <br><br>The "Update Page on Map Move" feature refreshes the queries made on the page where the map is located and sets the documents you marked as markers on the map. <br><br>However, to achieve what you are aiming for, you need to have a filter in the specific view. <br><br>For example, only retrieve from the Firebase collection all the documents that are near the center of the map's lat/lng based on the zoom level. <br><br>This process is more complex and requires additional configuration, including custom actions or custom widgets.

Best regards,<br>Azanello

**Comment by monocat** [comment]
No worries @Alezanello Thanks for the reply. I figured that's the case. Seems the documentation needs to reflect that. I will see what I can dig up to achieve this since I'm not a dev. If there are tuts you're familiar with, please do share the links. In the meantime, I guess this issue can be closed for now.

**Comment by ShaneVC01** [comment]
How can this bug be closed? At the moment, by enabling the "Update Page On Map Move" for a GoogleMap widget does not do anything. There is no "On Page Update" or similar events that is added to the page to handle this. I only get "On Page Load", "On Phone Shake" & "On Shortcut Press".

I just need the ability for a user to update the exact location by moving the marker. So if there was a "marker moved" event, even better (this could improve the Place Picker also to pick LatLong instead of address). But seems dragging the map and getting the new centre is the only option.
