### ISSUE TITLE
Assets Missing Error

### ISSUE THREAD

**Issue by cskonstantyn** [FlutterFlow/flutterflow-issues#3426]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I download the project with local run and try to run it with any browser on local environment it gave me error the font is missing I reupload it but error was still there! When I try to publish the project with flutterflow web publish I get 24 errors which saying that ALL my assets are missing even though they are still there and I cant even change them it give me no change in the error. I also try to download the code with downlaod code button when I got it the asset folder was empty! I

### Expected Behavior

Assets should not be missing??? I dont know what to say here if I had them in a few days ago and project was working and assets were connected and project had no issue why no it is saying they are missing. I see them in galery in font section but the flutteflow dont see it for some reason? T_T Snapshot to 3 days ago to fix it did not help either......

### Steps to Reproduce

Its the only project so far I experience this issue with and thaks god it is a smaller of my projects. For bigger projects it would be much much worth. Take a look at it please because I am sure people have much much bigger project then mine and if they have same error it will be a very bad experience for them.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Olcr1z89grsNH1s7pbccwmjkWQ2Z/U4ZM0tVHURI0B5/NGu4Iec/eUFZuZrygdHxYfVqgmTkK/PfqjYaWIO4EJTKrGIBm/5d5EQ3iXkWWbK6TDc+NfW1fONJbN2aZ06aVmBRDPtNeV3AiwGGYF+m+aBDdQ5j7OzMjPf+lKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://www.loom.com/share/366953fb7953433ea5ace96e08b658af?sid=59827d0f-0e88-463c-a3c4-033a8522543e
I attached video that shows the errors. 

### Environment

```markdown
- FlutterFlow version: 4.1.73
- Platform: All platforms have issues
- Browser name and version: Chrome, Edge I tried all T_T
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello!

First of all, I'm very sorry you're facing this issue.

To address this issue, I strongly recommend contacting our support team. You can reach them via the in-app chat or at support@flutterflow.io. They have more tools to handle issues like missing assets and related problems. This GitHub tracker is intended for bugs that can be replicated in a new blank project.

Please contact our support team using one of the methods mentioned above so they can help determine the cause and possible fix for your issue.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
