### ISSUE TITLE
Trial plan

### ISSUE THREAD

**Issue by JobaBoba** [FlutterFlow/flutterflow-issues#3428]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Inability to order a PRO plan

### Expected Behavior

After the cancellation of the Plan to cancel its trial version.

### Steps to Reproduce

1. Free plan.
2. Enabling the "Standard" plan. We will enable the Standard Plan for you from the first of August, and until the first of August there will be a trial version of the Standard Plan.
There are not enough options, I am canceling the Standard plan.
3. Trying to turn on the PRO plan - nothing happens, it just hangs.

Most likely, it is not possible to include a plan for the project due to the Trial version of the “Standard” plan.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Visual documentation

Just watching this picture until the end of time on earth
[image](https://github.com/user-attachments/assets/43b46dac-482d-48ae-aa32-15cf1aafc891)

### Environment

```markdown
FlutterFlow v4.1.73+ released July 17, 2024
Flutter version is 3.22.2
win 11, chrome
```

### Additional Information

Good mood to you all

**Comment by JobaBoba** [comment]
The trial is not cancelled.
[image](https://github.com/user-attachments/assets/f1dc7af3-6f9c-4060-b751-a2788dd9786d)
Because of this, it is not possible to enable pro.

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. For cases like this, you need to contact support directly via in-app chat or at support@flutterflow.io. This issue tracker is intended for issues that can be replicated in new blank projects, and your situation seems to be more related to billing than to FlutterFlow development.

I strongly recommend reaching out to support directly, and they will find a solution for your situation :)

Best regards,<br>Azanello
