### ISSUE TITLE
Local Run Now No Longer Runs Latest Version Of App

### ISSUE THREAD

**Issue by ayjayem** [FlutterFlow/flutterflow-issues#3434]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using local run on a device now runs a version of my app saved as of this morning. It does not apply new changes made since then.

### Expected Behavior

Local run should run app as most recently updated in FF.

### Steps to Reproduce

1. Update app.
2. Use local run to run on device.
3. Doesn't show latest version of app on device.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlfLqy4ZNocNc+KXqc8cxpGU7M0McWOdEl+tuZwgbIoznBuwIdvSkbVpWQs++aVNcDlaGkl8epPzsvobhOvQCBxKWftlO/6pyWw/ke2iWV5fTPZC7dnRCIJ5mIECv14mjogl5HLNuWk4G2zmUOtivYALDBOu/Zwh9f6PHaOI=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 4.1.73+
- Platform: MacOS
- Browser name and version: Chrome 123.0.6312.58
- Operating system and version affected: macOS Sonoma 14.3.1
```

### Additional Information

Project is completely blocked as I can't test on a local device.

**Comment by ayjayem** [comment]
More information to help diagnose: in attempting to push to Github from the web app, I get a failure notification that a button I most recently added is a failing widget.

Neither this button nor anything else in my project show any build issues on either the web app or the desktop app; and in simplifying the button to perform any action, I in fact get the same failure notification. If I remove all actions from the button, I can successfully push to Github, and my local run works, running the latest version of the app.

So this seems to amount to: actions on this button break my project... but strangely new actions on other buttons don't, and even actions on a container on this page don't.

Upshot is that as a workaround I can use containers with text to serve as buttons for now, so I'm unblocked practically speaking.. but this is not a great long-term workaround.

**Comment by msusviela** [comment]
Hi @ayjayem. I wasn't able to replicate this from blank, could you provide more information about the specific actions that are breaking this?<br><br>In the meanwhile I'll suggest that you contact the support team: [support@flutterflow.io](mailto:support@flutterflow.io)<br>They can better assist you with ensuring your project is configured correctly

**Comment by ayjayem** [comment]
Thanks - I think somehow the subject widget got corrupted; the rest of the app seems to be working fine. I'll close this issue.
