### ISSUE TITLE
Project freezes when UI has too many Youtube Videos and can't restore to older version

### ISSUE THREAD

**Issue by safesecurely** [FlutterFlow/flutterflow-issues#3435]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Project freezes when UI has too many Youtube Videos and can't restore to older version.

### Expected Behavior

On the main dashboard, being able to restore to a prior version of the project or duplicate from a prior version to continue working on it.

### Steps to Reproduce

1. Save a version.
2. add several youtube video widgets to a recursive component within a container larger than screen size until it freezes.
3. can no longer work on project or revert to a previous saved version before I made these changes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89gruFG0KXqKPpvmSQ6Jm4/RoIrm8pOGDwbfaKvPIlzac/BflBWXfWoS3xfKEWLkl0C+sqKi9niG+wqC06abtlHzpBfEQKVeHy/aoSTPLuaRnQnQMdPIX613J2KkCMlPs9qcngswDm6FumRHwHrJu77Zwh9f6PHaOI=

### Visual documentation

<img width="721" alt="Screenshot 2024-07-18 at 6 54 33 PM" src="https://github.com/user-attachments/assets/5a0b26b6-075e-49f1-85a2-db3a7accf65a">

### Environment

```markdown
- FlutterFlow version: 4.1.74+
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

### Additional Information

I realize that this was quite overboard, but was hoping that if saving prior to causing the project to freeze, that I could revert / load from a prior version from the Home Dashboard to help restore the project.  Thanks and Best Regards to the team at FlutterFlow.
<img width="721" alt="Screenshot 2024-07-18 at 6 54 33 PM" src="https://github.com/user-attachments/assets/fc49e45e-3bbc-4a87-b755-74b2ca8d830f">

**Comment by Alezanello** [comment]
Hello,

I'm sorry to hear you're experiencing this issue. Unfortunately, I don't have the necessary tools to assist you directly. This GitHub Issue tracker is intended for replicating bugs from a new blank project and forwarding them to the engineering team for fixes. For this type of issue, I highly recommend contacting support via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io).

The support team has the right tools to help you resolve this issue.

I hope it gets fixed soon.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
