### ISSUE TITLE
Grey page in porperties of listview quering api call !!

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#3436]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It was working last two days but after its become grey, after querying an api call as list.
The thing is working properly on test mode.

### Expected Behavior

I excpeted to keep as usual like other projects becasue some one of my projects its 100% by API Calls and is not caused this issue !

### Steps to Reproduce

1- query an api call on a list view
2- confiigure the variables
3- after check if its caused the issue

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kMmB25NOtb0A+KX2ccJagiYXH0c7a+crjMBxZwA8J5zTP4YIP/v7ak5oO7ynSlFYIGKjuHwxxvfqiePqU8I5GE+cQL58+LlxEBXLQXGlb7q1Dqq7fW1QHfhPJmLG1sKo3BF+Oux1LHtn2mWMIumWcHHACZu2OzINJuW1LdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/36ed106a-d740-4e79-892a-e168a0ae8cf6)

### Environment

```markdown
- FlutterFlow version:  v4.1.74+ 
- Platform: Web
- Browser name and version: Chrome 126
- Operating system and version affected: Won 11
```

### Additional Information

I want to add other options on properties and now we're stuck !

**Comment by msusviela** [comment]
Hi @ImadBouirmane. I wasn't able to replicate this issue from blank and I didn't find it in your code.

Could you please tell me what's the API call that it's causing the issue (just the name, I can check it from your code), where it's triggered, and the name of the screen where the issue can be found? Thanks!

**Comment by ImadBouirmane** [comment]
Hi @msusviela 
Its **GET Place Reviews** API Call !

**Comment by msusviela** [comment]
Please, tell me where it's call that it's casing the issue (in which page)

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
