### ISSUE TITLE
Unable to Git push to Repository 

### ISSUE THREAD

**Issue by TStone45** [FlutterFlow/flutterflow-issues#3437]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Git push to online repository not working. I have no errors.

Project name: Appi App

![no bugs](https://github.com/user-attachments/assets/33662f19-a78b-465f-bc09-c73e88b97fed)

I have had to manually cut copy paste raw txt files across thats the only folder in the repo associated. 

![image](https://github.com/user-attachments/assets/5a3bbd23-ba01-4695-b9cf-c0b010613809)
![no push to repo](https://github.com/user-attachments/assets/45f4be50-55ba-405f-865b-694ef23758de)

### Expected Behavior

I am not seeing my code folders appear as in the available directions online:

![image](https://github.com/user-attachments/assets/6e4a23a7-5e6e-489c-ac88-1c7a151a8678)
![expected behaviour](https://github.com/user-attachments/assets/90b0894e-b7c8-40d8-aa07-f99e3e57d793)

### Steps to Reproduce

1. Open Project, 
2. Attempt Gitpush
3. Successfully pushed message displayed
4. No change to repo/.
5. I've done this 5 times now.
6. It is the FIRST time i am using this functionality

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8j6y49goctH176JavpvoDw4HEccTIMziNZ+exUbfaL1Bu0fOs/BX1hVXt/naVNcAE3+hl4Gw8LujtrDIPoFGEmubbZA+qlbWALke2iuMbGbELuRdnckM8RXCkC94cKJvx17OvBeV1Et61yEN96iZDHDIuu/Zwh9f6PHaOI=

### Visual documentation

![expected behaviour](https://github.com/user-attachments/assets/ec2ca83a-521c-48de-816e-4faf45901b5f)
![no bugs](https://
![expected behaviour](https://github.com/user-attachments/assets/7d3a989b-bd7f-4aeb-afbc-5c51af9e2a68)
github.com/user-attachments/assets/99c8d233-e89b-4034-8d4f-428970004c2a)
![no push to repo](https://github.com/user-attachments/assets/afef5d7f-9c76-476e-ae63-56c5d6ab6251)

### Environment

```markdown
- FlutterFlow version: 
- Platform: Web & Desktop tried both
- Browser name and version: Version 126.0.6478.127 (Official Build) (64-bit)
- Operating system and version affected: windows
Edition	Windows 11 Home
Version	23H2
Installed on	‎21/‎06/‎2024
OS build	22631.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0
```

### Additional Information

Trying to protect my IP by deploying it into github as I am working with Developers tomorrow

**Comment by msusviela** [comment]
Hi @TStone45.<br>Thanks for filling in but it's necessary that you provide more information so we are able to look into it from our side. Please, provide the steps to reproduce the issue from a blank project and also a bug report code. You can generate it by clicking right on the widget tree and selecting the Generate bug report option. This guide might help you: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)<br>Without the necessary information it would be impossible for us to pinpoint the issue.<br>Thanks!

**Comment by TStone45** [comment]
Hi just to be clear I believe this is a Flutterflow issue potentially:

But if you are able to help that would be most appreciated.


Bug report code is already attached above ITFfl8j6y49goctH176JavpvoDw4HEccTIMziNZ+exUbfaL1Bu0fOs/BX1hVXt/naVNcAE3+hl4Gw8LujtrDIPoFGEmubbZA+qlbWALke2iuMbGbELuRdnckM8RXCkC94cKJvx17OvBeV1Et61yEN96iZDHDIuu/Zwh9f6PHaOI=

All I can tell you is I have followed the instructions of downloading the Github extension allowing flutterflow to publish to the Repo. 

I am reading successful messages stating this is being successfully published. 

![showing successfully pushed message](https://github.com/user-attachments/assets/4369ccaf-965d-428b-9fc8-843b4faaf786)


And no files are pushed just a README....

Bit stuck

**Comment by msusviela** [comment]
Thanks for the clarification. I was able to reproduce this and I'll send it to ENG so they can work on this.

**Comment by msusviela** [comment]
Hi @TSSone45. The data should be uploaded to a FlutterFlow branch and not to main, is this working fine for you?

**Comment by TStone45** [comment]
Hi @msusviela thank you for your prompt professional assistance, I value your guidance. 

Yes it appears that I am trying to push to the 'main' or the branch of the repo is set as 'main'. 

I have set the correct branch. 

![image](https://github.com/user-attachments/assets/ed6acea4-a5c8-4aaa-9525-a565e74731af)

I am very new to Github
Kindest Regards 
Taz
