### ISSUE TITLE
We cannot work on FlutterFlow UI Builder

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#344]
## Expected behavior (required)

- Multiple users can edit the project at the same time.

## Current behavior (required)

- Users who added as collaborator cannot edit anymore.

## To Reproduce (required)

1. Add two Pro users as collaborator.
2. Open same project
3. And to something.

## Context (required)

Me and my team uses Pro accounts. and we work together as collaborator (Not as a team).

And there was an update today, and this happens.

## Screenshots / recordings

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/5080329/211705293-f6c66dbd-c0e5-48a3-976f-8daed49ea792.png">

## Your environment

Version of FlutterFlow used: v3.0 December 30, 2022 - Flutter 3.3.4
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version: Google Chrome, Version 108.0.5359.124
Operating system and version (desktop or mobile): iMac 2020, macOS Ventura 13.1

**Comment by agreaves** [comment]
Hi @thruthesky, this is correct. As of the most recent update, only Team members can collaborate simultaneously on the same project. Apologies for the inconvenience, however we encourage teams collaborating on projects to work on the same FlutterFlow team. Simultaneous collaboration was originally intended for this use case but at the time we didn't have a Team plan.

Please keep in mind you can still collaborate on projects without being on the same FF Team! Just not simultaneously.
