### ISSUE TITLE
Listview need refresh when new document add to Firebase

### ISSUE THREAD

**Issue by ozanbilgili** [FlutterFlow/flutterflow-issues#3440]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Listview just listen changes for existing screen record. 

### Expected Behavior

Listeview need to listen for new documents too.

### Steps to Reproduce

1. Add Listeview
2. Add Firebase collection
3. Add new document to collection
4. Check list view 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Visual documentation

.

### Environment

```markdown
- FlutterFlow version: 4.1.74+
- Platform:macOS, Web
- Browser name and version:Safari, Native App
- Operating system and version affected: All of them
```

**Comment by msusviela** [comment]
Hi @ozanbilgili. 

Thanks for filling in but it's necessary that you provide more information so we are able to look into it from our side. Please, provide a bug report code. You can generate it by clicking right on the widget tree and selecting the Generate bug report option. This guide might help you: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)<br>Also, please make the steps to reproduce more specific. How are you retrieving the data from firebase to display it on the listview?<br>Without the necessary information it would be impossible for us to pinpoint the issue.<br>Thanks!

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
