### ISSUE TITLE
Text format as currency leads to either 1 or 3 digits for decimal places when it should be 2

### ISSUE THREAD

**Issue by piershare** [FlutterFlow/flutterflow-issues#3441]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Text format as currency leads to either 1 or 3 digits for decimal places when it should be 2

### Expected Behavior

If you format a text as a currency, it should automatically be 2 digits for the decimal place regardless of the double in the DB

### Steps to Reproduce

1. Text format as currency
2. See 1 or 3 digits

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMrl34ZPxOVY15Dtbe5sjjg4G1B7TLJMt9VxSUghfaLqO5k1PPSlXFJLYte+THxmPWeLuHgD+MrSkezxEMA6JUmWGpxgyZRXQRfjWT+jbLqIEbWJdH96M8RWIWaO1KejvxBRAOphL2Ah3U2EPfCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 4.1.73 
- Platform:All
- Browser name and version:Arc
- Operating system and version affected: Mac
```

**Comment by msusviela** [comment]
Thanks for the report! I was able to replicate the issue, I'll send it to ENG so they can work on this.

**Comment by piershare** [comment]
Thanks!

Best,

Jonathan Timianko
