### ISSUE TITLE
the flutterflow app doesn't interact with keyboard after going to t.me links if flutterflow project is a telegram mini app

### ISSUE THREAD

**Issue by Neeshker** [FlutterFlow/flutterflow-issues#3445]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My Flutterflow project is a telegram mini app. When user goes to a telegram channel from the app by launchUrl and back, the user can niether open a keyboard nor interact with it (coping doen't work). Also, when user goes to telegram channel, app instantly closes on pc.

### Expected Behavior

coping works, keyboard can be opened, mini app on pc doesn't closes

### Steps to Reproduce

1. Create a blank project and new page
2. Create 2 buttons
3. Create AppState "refLink" (and write smth there as a default value)
4. Add actions to buttons: launch url to any telegram channel. Example: https://t.me/tethehbdjejdh5hhfudue on the first and copy refLink on the second
5. Enable web publishing. Publish to web
6. Install Python on your local pc (add python to path if needed), write in cmd "pip install aiogram"
7. Go to Telegram, search for @BotFather and create new bot. Copy token
8. Write simple telegram bot with mini app support, replace token and link to actual ones:

import asyncio
from aiogram import Bot, Dispatcher
from aiogram.filters import CommandStart
from aiogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton

bot = Bot(token='your token') # Replace token to your actual one here
dp = Dispatcher()

@dp.message(CommandStart())
async def cmd_start(message: Message):
    keyboard = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="Open web app", web_app={"url": "https://example.com"})] # Replace link to your site URL after publishing to web
    ])
    await message.answer('Hi!', reply_markup=keyboard)

async def main():
    await dp.start_polling(bot)

if __name__ == '__main__':
    asyncio.run(main())
    
9. Start the bot with /start command and open web app.
10. Push the first button. It will close if you are on pc. It will collapse if you are on a smartphone.
11. On smartphone, click the second button and see that refLink doesn't copies

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gobRY15P+Ku56hQIgQ0QnU7gnlO1ucx4YC7LsPLM2fM77aUNKTfWdfG9APmaar3ME+d7QjeDpD/QEFAeZboRx0JVAWguVfGWQaJSoDKiCdnF9LJ9XIHay1rurmyMlFMxfWiFl2FOlN63qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/c9f810bf-60dc-44cb-b9f1-087e43655a58

### Environment

```markdown
- FlutterFlow version: web
- Platform: pc and phone
- Browser name and version: telegram mini app
- Operating system and version affected: ios, android, windows, probably macOS and linux. all systems that has telegram
```

### Additional Information

i have another project with the same logic, but copying works there (but animation for copying doesn't)

**Comment by Neeshker** [comment]
sorry, here is the code for a simple bot with telegram mini app support:
`import asyncio
from aiogram import Bot, Dispatcher
from aiogram.filters import CommandStart
from aiogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton

bot = Bot(token='your token') # Replace token to your actual one here
dp = Dispatcher()

@dp.message(CommandStart())
async def cmd_start(message: Message):
    keyboard = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="Open web app", web_app={"url": "https://example.com"})] # Replace link to your site URL after publishing to web
    ])
    await message.answer('Hi!', reply_markup=keyboard)

async def main():
    await dp.start_polling(bot)

if __name__ == '__main__':
    asyncio.run(main())`

**Comment by Neeshker** [comment]
[simplebot.txt](https://github.com/user-attachments/files/16321686/simplebot.txt)
simple bot with mini app support

**Comment by Neeshker** [comment]
forgot about textfield in the stps to reproduce. Here is updated project with textfield: https://app.flutterflow.io/project/test-oarqw3

**Comment by Alezanello** [comment]
Hello!

I checked the test project you shared, and it was working fine on my phone. Is there something specific I might not be doing to replicate the issue? I've shared a video for your reference.

[Video de WhatsApp 2024-07-22 a las 09.25.57_e4b977a0.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/380e4102-ce9c-4b1d-9848-64060094282c/8b313f6c-4e65-4f35-ba68-ed8e6bad9f82?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zODBlNDEwMi1jZTljLTRiMWQtOTg0OC02NDA2MDA5NDI4MmMvOGIzMTNmNmMtNGU2NS00ZjM1LWJhNjgtZWQ4ZTZiYWQ5ZjgyIiwiaWF0IjoxNzIxNjUxNTQ5LCJleHAiOjMzMjkyMjExNTQ5fQ.ulpCSOZOCZyMXGGHZOEF4o9DyYmodx8gjiymm-AiniE)

**Comment by Neeshker** [comment]
пн, 22 июл. 2024 г., 16:49 Roman Pukhov ***@***.***>:

**Comment by Neeshker** [comment]
Hello. It should be opened in Telegram mini app (telegram is a messenger,
there is an app of it in play market). Not in the default browser. To get
the error, you need to create a bot in botfather (bot for creating bots in
telegram). Code for a bot is in the 1st comment in github in the txt file.
You need to copy code, download python, install aiogram liabrary, paste
your token from botfather... The complete guide is in the video in the next
email

пн, 22 июл. 2024 г., 15:32 Alezanello ***@***.***>:

**Comment by Neeshker** [comment]
Hello. It should be opened in Telegram mini app (telegram is a messenger,
there is an app of it in play market). Not in the default browser. To get
the error, you need to create a bot in botfather (bot for creating bots in
telegram). Code for a bot is in the 1st comment in github in the txt file.
The complete guide is in the video in the next email

пн, 22 июл. 2024 г., 15:32 Alezanello ***@***.***>:

**Comment by Neeshker** [comment]
Hello. I send videoguides by gmail but it seems that github haven't sent files from gmail. I'll dublicate them here. 

https://github.com/user-attachments/assets/ff7056cb-6225-4288-974c-efd435ddc6f8


https://github.com/user-attachments/assets/f2863b5b-0a34-4d37-9b83-bc338737d1d0

**Comment by Alezanello** [comment]
Hello again,

Sorry for the late response. At this point, I'm lacking the right tools to help you with this issue. I'll keep this issue open in case I find anything that might help, but in the meantime, I recommend you contact support directly via the in-app chat or at support@flutterflow.io for a more specific solution to your situation.

Best regards,<br>Azanello

**Comment by Neeshker** [comment]
Hello. I tested this issue again. Seems like it was fixed by Telegram:) You
can close it

вт, 6 авг. 2024 г., 16:06 Alezanello ***@***.***>:

**Comment by Alezanello** [comment]
Hello again!

I'm glad to hear the issue has been fixed.. <br>I'll close this issue for now. If it happens again, please don't hesitate to create a new one!

Best regards,<br>Azanello
