### ISSUE TITLE
I can't save any changes

### ISSUE THREAD

**Issue by fdelgadofocus** [FlutterFlow/flutterflow-issues#3446]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unable to save any new form, new action, new label in the whole project

### Expected Behavior

Write anything new to the project

### Steps to Reproduce

1 edit any page in my project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I cant reproduce it

### Visual documentation

no network

### Environment

```markdown
- FlutterFlow version: 74+
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

this is the second time I write this issue the first time it was not solved

**Comment by rzambroni** [comment]
Closing this ticket in favor of your original ticket: https://github.com/FlutterFlow/flutterflow-issues/issues/3417
