### ISSUE TITLE
 Unable to access index when attempting to assign a list to a list variable.

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#3447]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The at Index List option is not present for datatypes with lists within them

https://github.com/user-attachments/assets/74cd2fc4-89f0-4d23-aa54-f3787658cbd3

### Expected Behavior

For datatypes with sub lists to have an option to select an index, 

For example: you have a list of lists and you want to acess the second list in that list

### Steps to Reproduce

Create a data type with a list of a type
![image](https://github.com/user-attachments/assets/52cb3d24-76ab-40e5-9a14-bc7d3574d175)
then create an app state for example that is a list 

![image](https://github.com/user-attachments/assets/b2de4c3a-d53c-480a-a470-6310d7f3b1ba)

Try to access the sub list at index 1 within a list variable 
![image](https://github.com/user-attachments/assets/e474ec4a-1ca4-4dd3-976e-3f741c0c0340)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTk871z4tPsfVc+KrMbcIxqDg6I0MfWI0/ld5EZwEhfYivEYk2PsjRVE5LYtfnS2NqHEybjjsJwN6LkfGSFvYnAEmVQb56yJRXQQ3hRj6RbrqJBpawT3dCQdxjGEyc0qu4kQklCLNhcXga31zzI/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

List<String> example = FFAppState().ExampleListrStruct**[index].**anExampleList;

List<String> ExampleListrStruct is a list of lists

and List<String> example expects a list

but we are looking for the list at index 1 only to pass to the list variable 

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Thanks! @Josefpa. I was able to repicate the issue and I'll send it to the ENG team so they can work on this.
