### ISSUE TITLE
Changes keep reverting back

### ISSUE THREAD

**Issue by MohitKandu25** [FlutterFlow/flutterflow-issues#345]
## Expected behavior (required)
The changes that are made should persist and clicking on test button should load a test session.

## Current behavior (required)
Data is getting reverted. Even the smallest changes aren't saving. Also, clickingon the test button keeps spinning forever and doesn't load a new session.  I do make sure to keep saving often.

## To Reproduce (required)
1. Make some changes in code.
2. Press ctrl + s to save
3. Press the test button
4. It spins forever.
5. Refresh the page hoping the button works now
6. Changes get reverted

## Context (required)
I am not able make any progress whatsoever in my app. I have been trying for 1.5 hrs now!

## Screenshots / recordings
changes keep reverting
https://user-images.githubusercontent.com/104911624/211822431-93496377-4d12-4602-b3c8-aae0a1745763.mp4

test button not working
https://user-images.githubusercontent.com/104911624/211822745-c59c5b23-b4e9-4491-8a1e-e66bb09979cd.mp4

## Your environment
* Version of FlutterFlow used: v3.0 January 11, 2023 - Flutter 3.3.4
Browser name and version: Google Chrome 103.0.5060.134 (Official Build) (64-bit)
Operating system and version: Ubuntu 20.04.4 LTS

**Comment by yoheisoito** [comment]
@MohitKandu25 Thank you for your post.
1) I am unable to replicate your issue on a simple project with a component with a few parameters, saving the project, then deleting the parameters then saving.
2) The spinning test button may be related to hidden errors in one of your custom widgets. Do you have any widgets where you are excluding from compilation?

It would be very helpful if you can try replicating the issue by creating a dummy simple project and see whether the issue persists. Also, can you try downloading your project and see if there are any outstanding errors that would prohibit your project from getting into test / run mode? Thanks!

**Comment by MohitKandu25** [comment]
Hello @yoheisoito. Thank you for your response. This issue existed at the time I had posted it. Apparently there was some database issue with flutterflow. It has been fixed. But this happens often. I have the following screenshot which might help. Please take a look.
![firebase quota error](https://user-images.githubusercontent.com/104911624/212600515-c6798bd6-e858-4f17-a5d6-b07e8c6d2c45.png)

**Comment by hariprasadms** [comment]
Closing this issue as it is not re producible. This should be fixed in latest FF builds.
