### ISSUE TITLE
Text widget bug

### ISSUE THREAD

**Issue by DanVincii** [FlutterFlow/flutterflow-issues#3453]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When image widget added above text widget the text gets compressed. The other way around works fine. Sometimes a divider helps but does not fix the issue. This goes for carousel widget. When a carousel widget is added below a text widget it tends to compress the text above.
Tried different settings, fonts and text sizes on text widget, placed text in containers and rows and tried settings on those widgets too.
placed image in containers, cards, rows, columns and by it self, also tried different settings.

This issue is only visible when performing a test run on mobile

### Expected Behavior

The expected behaviour is for the text to remain readable after adding images to any page.

### Steps to Reproduce

1. Create page
2. Add text widget with 2 or more words
3. Test on Phone
4. Add image widget above text 
5. Test on Phone

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

![Screenshot_20240721_143519](https://github.com/user-attachments/assets/b8e38522-151d-4fbd-9b3a-da9821d300c6)
![Screenshot_20240721_154726](https://github.com/user-attachments/assets/db3af4d1-ba4d-4691-aca5-01605e04ea6b)
![Screenshot_20240721_155053](https://github.com/user-attachments/assets/7468ad9e-4ee8-4315-abcd-6f113be7347c)
![Screenshot_20240721_155134](https://github.com/user-attachments/assets/f99529af-2359-4eed-a646-5873cb659533)
![Screenshot_20240721_155258](https://github.com/user-attachments/assets/6f52737a-6228-4510-a6b8-90fa229aef0f)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 11
- Test run is performed on Android phone through flutterflow testing app
```

### Additional Information

Feel free to create a new page and try the steps mentioned above.

**Comment by msusviela** [comment]
Hi @DanVincii. <br>I was unable to reproduce the issue from blank. Can you please share the bug report code for this? <br>You can create one by clicking right on the widget tree and selecting the option to generate a bug report code. This guide can help you to generate it: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)<br><br> This can help us to see any details that might be causing this. Thanks!

**Comment by DanVincii** [comment]
Hi Micaela,

Thank you for your reply.

I will only be able to provide a bug report code later in the day, as I'm
at work at the moment.

This issue/bug is only visible once I test it on mobile. It appears to be
fine when testing on web.

If you don't mind me asking, did the text widgets behave as normal? If so,
how did you test it, web or mobile?

Please see this topic, where I ask for help in the forum.

https://community.flutterflow.io/ask-the-community/post/crammed-text-PWYh5XNQ2INGD1A?highlight=2RrOzpIicwUuVDb

I've tried different fonts but unsuccessfully.

Many thanks
Daniel

A segunda, 22/07/2024, 21:24, Micaela ***@***.***> escreveu:

**Comment by msusviela** [comment]
I tested on mobile. We will need the bug report code so we can also check if there's any other widget affecting this (like a container or any wrapped widget). Without this information is very difficult for us to know exactly what's going on.

**Comment by DanVincii** [comment]
Hi, 

Please find the bug report code below,

ITFXkPLlw49IvsBE+rryKcZsqDswGUwbUOc7j9VEGAsjCePxB4oqZsn4alhpSOqHYXNUfU2ZpDox3M2Kht/LE8EDBweYRqk6zpZXUxDvfF+WM63QDc3hOUF9GfNQC0Cdy8Ck2BFNIsReWF4k7Wa1evOub3qCf9qOYwx5e6fDbOY=

Many thanks
Daniel

**Comment by msusviela** [comment]
Hi, we were unable to reproduce the issue from our side. Yesterday a new version of FlutterFlow was deployed. Did it fix it for you?

**Comment by DanVincii** [comment]
Hi, the issue is still ongoing.

**Comment by msusviela** [comment]
I'm still unable. Could you share the resolution and the model of the phone? Does it happens in every device you're testing or just a particular case?

**Comment by DanVincii** [comment]
Hi Micaela,

Apologies for the late reply.

I have only tested in on my phone. Samsung A54, resolution - 1080 x 2340
pixels 19.5:9 ratio (\~403 ppi density).

Many thanks
Daniel

A quarta, 31/07/2024, 01:12, Micaela ***@***.\*\*\*> escreveu:

**Comment by rzambroni** [comment]
Hi @DanVincii,

I'm sorry you're having this issue. It seems similar to a [known issue](https://github.com/flutter/flutter/issues/111352) in Flutter where overlapping occurs, but some of the conditions differ. We continue to investigate, but it has proven difficult to replicate.

Is this issue happening only in the specific project you shared? If possible, could you try with a blank project to see if it is replicable there?<br><br>Thanks in advance for the help and patience.

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
