### ISSUE TITLE
suddenly got 103 bugs

### ISSUE THREAD

**Issue by divingjoker** [FlutterFlow/flutterflow-issues#3454]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in test mode, first i can not login, so i  try to find out what when wrong, i only try different setting of the firestore rules.
and great things happen, it suddenly got 103 bugs, what can i do to fix it, it seem lots all the working, and i have to set it up again

### Expected Behavior

i did not expected it happen

### Steps to Reproduce

try different rules

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

nothing work now

### Visual documentation

<img width="369" alt="螢幕截圖 2024-07-22 20 44 51" src="https://github.com/user-attachments/assets/88771008-9af3-4594-97c9-f6a623967ce9">

### Environment

```markdown
- FlutterFlow version: 4.1.74
- Platform: MacOS
- Browser name and version: chrome
- Operating system and version affected: sonoma 14.4.1
```

### Additional Information

no

**Comment by Alezanello** [comment]
Hello!

You can revert or view the previous state of your project from the Snapshot section. This allows you to go back to a version of your project without those errors.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1a80d3e7-e357-429b-991b-b46ba6849382/853d0f3b-7ad9-4418-b60a-1293d3f3e93d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYTgwZDNlNy1lMzU3LTQyOWItOTkxYi1iNDZiYTY4NDkzODIvODUzZDBmM2ItN2FkOS00NDE4LWI2MGEtMTI5M2QzZjNlOTNkIiwiaWF0IjoxNzIxNjU0MDIyLCJleHAiOjMzMjkyMjE0MDIyfQ.VAoA-TzMICXkSQm8LoH_pssG7zCDmEL9Ho0gbXnLA18 " alt="image.png" width="757" height="446" />

Best regards,<br>Azanello

**Comment by divingjoker** [comment]
thanks very much, you are my life saver, if fix the bug problem, but still can not fix the login error in test mode, should i go back a bit more early ?

**Comment by Alezanello** [comment]
In order to see the login issue more closely could you please generate a Bug Report Code from your widget tree?<br><br>Just go to any Page, Right click on any widgets from the Widget Tree and select the option "Get Bug Report Code" and share it with us

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/931406bd-363d-4a54-81fb-e3024e7f0950/8b0f89ab-b201-4f00-939d-7af8f46ba9b8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MzE0MDZiZC0zNjNkLTRhNTQtODFmYi1lMzAyNGU3ZjA5NTAvOGIwZjg5YWItYjIwMS00ZjAwLTkzOWQtN2FmOGY0NmJhOWI4IiwiaWF0IjoxNzIxNjU2MDkwLCJleHAiOjMzMjkyMjE2MDkwfQ.ev-SLhqSU2-0JK7Aqzrjfnre4DkB_Rw-tI91cILnT9Y " alt="image.png" width="368" height="419" />

**Comment by divingjoker** [comment]
where can i see and share the report >

**Comment by divingjoker** [comment]
<img width="554" alt="螢幕截圖 2024-07-22 22 04 16" src="https://github.com/user-attachments/assets/e7bcc3e3-ace0-4412-98e3-a03bdc4c47b0">

**Comment by divingjoker** [comment]
<img width="578" alt="螢幕截圖 2024-07-22 17 59 21" src="https://github.com/user-attachments/assets/020c9b3a-0239-41b8-8ec3-0106dfb0685d">

**Comment by Alezanello** [comment]
I need you to generate the bug report code as I mentioned above and paste the code here!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9943a87b-73db-4839-bd66-3517f68e543f/0a657cfe-25ce-4c62-af95-ed6f00d667eb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OTQzYTg3Yi03M2RiLTQ4MzktYmQ2Ni0zNTE3ZjY4ZTU0M2YvMGE2NTdjZmUtMjVjZS00YzYyLWFmOTUtZWQ2ZjAwZDY2N2ViIiwiaWF0IjoxNzIxNjc3NDMwLCJleHAiOjMzMjkyMjM3NDMwfQ.LOa-hYn74EJ7S2UGaDhdmL6zhA9_L37XtOws-u9eEiY " alt="image.png" width="459" height="522" />

**Comment by divingjoker** [comment]
IT4sifKA35dOn7xH15CAbcZB/Cg4JUg9UL80scp/bxIgGIDzPOw+ZPWkclNCXfGjTVFXPkSmmkMB/6H8ueDpOPBdHzWqbIBB+ZNUWAriWkiVe5OBDamJPHMkEf1hf2Km4Z+JgxRdCLNeW3g67zuINe6+YCvbH5T0IlFISq/LZO4=

**Comment by Alezanello** [comment]
Hello again!<br><br>I could check the same issue, just to verify basic setup, do activated email sign-in on firebase project?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/16e9136e-573b-4c62-a0d6-12ab1f811cda/3e745096-561a-41ad-b162-947558b63a9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNmU5MTM2ZS01NzNiLTRjNjItYTBkNi0xMmFiMWY4MTFjZGEvM2U3NDUwOTYtNTYxYS00MWFkLWIxNjItOTQ3NTU4YjYzYTljIiwiaWF0IjoxNzIxODI1NDg3LCJleHAiOjMzMjkyMzg1NDg3fQ.Oq6ikP69dxrF4Cwg7HxYjnteE2MR1Z1aLAUVj_OfrSA " alt="image.png" width="2718" height="1062" />

**Comment by divingjoker** [comment]
<img width="2048" alt="螢幕截圖 2024-07-24 21 13 46" src="https://github.com/user-attachments/assets/984f7add-97fc-41a5-8d7f-088c81bcc830">

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. Did the latest FlutterFlow updates fix your issue?

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
