### ISSUE TITLE
Reorder child generated from supabase query - jumping object

### ISSUE THREAD

**Issue by rafal-kobeszko-kobengi** [FlutterFlow/flutterflow-issues#3455]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When reordering object generated from supabase query the object is jumping back to the oldIndex for 1/10 sec, and then jump to proper posiotion (newIndex).
The same results we can get by reordering big objects like data type list.
The animations doesn't work because even if i have animation as first step in action flow when reorder the object still jumps, and then animation starts.

### Expected Behavior

The object should not jump. Should wait for action end (can be parameter).
Or give it delay before back (parameter in ms).

### Steps to Reproduce

https://www.youtube.com/watch?v=EsMT-nMS9j4&ab_channel=AlbertBarth
I have different solution for that (supabase database function) but result is the same.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi8rlx4ZOj7xa1br+Y/lahSQ4QkAiarso08pBZzUYF5SuCLMqY8mnPxJVUu28TAlUf1qmp14ezOiJkoaWFe1fNQqBc6pi+ZNpWgLKJX6QRL2TF7jhZHRBEeNYI2KP0ra7hBNTLbFpSkYW22eUOfOtHj/qNbX6DFQ8Sq/LZO4=

### Visual documentation

1. https://www.youtube.com/watch?v=EsMT-nMS9j4&ab_channel=AlbertBarth  (after 3:03)
2. On this slow motion video You can see that the jump is first then starts animation with initial visibility 0.

https://github.com/user-attachments/assets/1664d0dc-155e-42ba-8c89-75a8c2174e9c

### Environment

```markdown
- FlutterFlow version: 4.1.74+
- Platform: Web
- Browser name and version: Wersja 126.0.6478.183 (Oficjalna wersja) (64-bitowa)
- Operating system and version affected: Win 11
```

**Comment by rafal-kobeszko-kobengi** [comment]
What is the status of?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
