### ISSUE TITLE
Localization feature is not working properly

### ISSUE THREAD

**Issue by a-urel** [FlutterFlow/flutterflow-issues#3458]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Localized text is not displayed on design canvas. Also, localizations are not saved in this case. 
And sometimes when I add a new Label, English text is Hello World, and Turkish text is 'Not' (not empty, a text that I don't know where came from).

### Expected Behavior

Localized texts should be saved and displayed accordingly.

### Steps to Reproduce

1. Add a label
2. Try to localize

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ksn1z4hgrsdc187qccdahjgXH1s7RL8V0e1hdEk8KOvLBIYuP/XsQBFWQt+lSlZAMESmmnkz+vDKj/OSV+0FEzeBc7ZJ1LhiVQzybH+hUZOBPLu0fkZ5HdlmGFSy5JjQgRVSBMZtLSBm7E6HNtm9UjfdGLqyImdISq/LZO4=

### Visual documentation

<img width="794" alt="Screenshot 2024-07-23 at 13 37 49" src="https://github.com/user-attachments/assets/1aa46e8a-92ed-4799-a0f5-32c1aac88805">
<img width="794" alt="Screenshot 2024-07-23 at 13 45 43" src="https://github.com/user-attachments/assets/adb06782-8121-4f51-9f34-eed628b25874">

### Environment

```markdown
- FlutterFlow version: 4.1.74
- Platform: N/A
- Browser name and version: N/A
- Operating system and version affected: MacOS 15 Beta
```

### Additional Information

I've been experiencing localization issues for a long time. It's too buggy.

**Comment by msusviela** [comment]
Thanks @a-urel for filling in. This is a duplicate issue, so I'm closing this one. You can follow the original issue here:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3457](https://github.com/FlutterFlow/flutterflow-issues/issues/3457)
