### ISSUE TITLE
Issues using the Mapbox_Maps_Flutter Package

### ISSUE THREAD

**Issue by millienmax** [FlutterFlow/flutterflow-issues#3459]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am creating a custom widget using the official Mapbox_Maps_Flutter package but when I go to test the app the widget loads but the map inside the widget never loads.

### Expected Behavior

I expect the widget to load with the specified map and style. 

### Steps to Reproduce

1. Create a new custom widget to generate a map using steps from the official Mapbox_Maps_Flutter [website](https://pub.dev/packages/mapbox_maps_flutter)
2. Download the code and add the required dependencies for token credentials
3. Launch a test of the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5flfLluIhgrsdY0JDubO9VuCUXQ0M7apI7mOwaYw4aIYvqPOx3OcykflZJYs+WTAk7eVqZpH4KzNLZkYbDFu0oNQ+BQaVq3bgNUwzyZGS6b4iwCKWOVURDJ/JWIFSC4KezmAx9G/pidCUYwUyICu+UbBHZHZDONjINH8qkWNvOnFaWLgDRVydGzidecCfn

### Visual documentation

![image](https://github.com/user-attachments/assets/1bb91f53-a881-4cfc-b1aa-67f66bc4ea75)

`// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/enums/enums.dart';
import '/actions/actions.dart' as action_blocks;
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:developer';

import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart' as mb;
import 'package:latlong2/latlong.dart' as ll;

class MapboxMap extends StatefulWidget {
  const MapboxMap({
    super.key,
    this.width,
    this.height,
    this.point,
    required this.startingPoint,
    required this.startingZoom,
    required this.accessToken,
  });

  final double? width;
  final double? height;
  final LatLng? point;
  final LatLng startingPoint;
  final double startingZoom;
  final String accessToken;

  @override
  State<MapboxMap> createState() => _MapboxMapState();
}

class _MapboxMapState extends State<MapboxMap> {
  mb.MapboxMap? mapboxMap;

  _onMapCreated(mb.MapboxMap mapboxMap) {
    this.mapboxMap = mapboxMap;
    log('Map created successfully');
  }

  @override
  Widget build(BuildContext context) {
    log('Building map with starting point: ${widget.startingPoint}, zoom: ${widget.startingZoom}');
    return Scaffold(
      body: mb.MapWidget(
        key: ValueKey("mapWidget"),
        onMapCreated: _onMapCreated,
        styleUri: 'mapbox://styles/ravenknobit/cltjnprwj00mw01qpgclec0ky',
        cameraOptions: mb.CameraOptions(
          center: mb.Point(
            coordinates: mb.Position(
                widget.startingPoint.latitude, widget.startingPoint.longitude),
          ),
          zoom: widget.startingZoom,
        ),
      ),
    );
  }
}`

### Environment

```markdown
- FlutterFlow version: v4.1.74+ released July 18, 2024
- Flutter version is 3.22.2
- Platform: Android and iOS
- Browser name and version: FlutterFlow desktop app Version 4.1.74 (4.1.74)
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by paulperez-dev** [comment]
Hi @millienmax! If you are downloading the code and running the app outside of FF the issue may be related to your configuration, it is not a FF bug.

Look at your console and verify if there is no error logged. I'm going to close this issue.
