### ISSUE TITLE
Firebase Advance Settings

### ISSUE THREAD

**Issue by coploy-ia** [FlutterFlow/flutterflow-issues#3460]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Firebase database URL
We are using the key to configure the firestore environment, we have the default key (prod) and a coploy-hml(hml), but we are no longer able to use the hml one, when downloading the code we saw that the function that flutterflow has is deprecated I don't know if this has any influence but we are getting a gray screen error, do you have any idea what it is?

### Expected Behavior

When configuring the database, it ran normally with data from the firestore pointed to.

### Steps to Reproduce

1 create project 2. configure firebase > advanced settings > firestore database url.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClcmBy4xOxeZE15Duc8BsmiARNlw2RYJE0dV+dE02DZPOD7AQP8nRP1dUOPHiSlVieGeGgn8X/MrPkd7LDflfPQeaY6pEzJF6ewrgfESXeLawPa63b3cnM5pWJhWZ3Ku7uhBQWLdhc3A+3zuHfN+9TXLDQZztOzAjQeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Configuracoes, vai em firebase > configuracoes avancadas > firestore database

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): macOS Monterey 12.2.1
```

### Additional Information

We are using this process, this is impacting our development, as the hml environment is off due to the problem

**Comment by Alezanello** [comment]
Hello!

I'm trying to figure out how to replicate this issue exactly. What was the exact value you had set in the Firebase Database URL that was working before but isn't now?

Could you create a new blank project and set the Firebase project with this Firebase Custom URL value so I can look into it more closely?

Best regards,<br>Azanello
