### ISSUE TITLE
Local run status stuck in "initializing"

### ISSUE THREAD

**Issue by airamhany** [FlutterFlow/flutterflow-issues#3462]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The local run status is stuck on "initializing" for all projects. Previously, the local run was working fine. This issue began after an update for the local run. I have tried "resetting" the Flutter folder inside the app and reinstalling it. I also updated to the latest version of FlutterFlow. When I run `flutter doctor -v`, I don't see any issues.

<img width="476" alt="Screenshot 2024-07-23 at 3 07 27 PM" src="https://github.com/user-attachments/assets/b0a7008c-8041-4ba0-8d34-8985311054a0">

### Expected Behavior

I want to test it locally on a device. 

### Steps to Reproduce

1- I updated the local Flutterflow
2- I tried to test one of the projects locally.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klOflvYt1pbxY17X5bcExgiIRQnp+TL07ttYbZxUjIuPtBJh/PMmkP01tTe2md1NhHFCj8XMy/+jVv87EUPI5PQ2dc65OyIdcSRWXd3q8RKrQDqqCRUB8ONxmJlCb4aaK3CVAGPZYSGwm2GD2fumWaDDtJ5O/Zwh9f6PHaOI=

### Visual documentation

<img width="476" alt="Screenshot 2024-07-23 at 3 07 27 PM" src="https://github.com/user-attachments/assets/7161312c-79ec-4379-b272-ea678f343008">

### Environment

```markdown
- FlutterFlow version: v4.1.74 released July 23, 2024
- Platform: MacOS Desktop
- Browser name and version:Chrome
- Operating system and version affected: macOS Sonoma Version 14.5
```

### Additional Information

I am trying to test an app locally in preparation for its release, but this issue is affecting our launch timeline. Please let me know the next steps. Thank you!

**Comment by paulperez-dev** [comment]
Hi @airamhany! Can you please confirm if the issue is present in blank projects? I'm unable to reproduce the issue.

**Comment by airamhany** [comment]
This issue is present with all projects. I have observed it in a couple of apps I have been working on, and even with a newly created blank project.
Note: I am not sure if this is related, but I believe this issue started before the second-to-last FlutterFlow release. I currently have the latest release, and the issue persists.

**Comment by airamhany** [comment]
Any updates?

**Comment by paulperez-dev** [comment]
Hi @airamhany! I tested with the version released today and can't replicate this issue. Can you please try removing the app and installing it again? If the issue persists please reach out to [support@flutterflow.io](mailto:support@flutterflow.io). They can better assist you with ensuring your project is configured correctly!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by WellDunDun** [comment]
@paulperez-dev @airamhany This happened to me today on the MacOS app!

I switched to VSCode and ran flutter doctor -v

It returned "Waiting for another flutter command to release the startup lock"

So I ran killall -9 dart then restarted

Everything was back to normal

Hope this helps y'all fix local run mode!
