### ISSUE TITLE
Debug panel miss informations

### ISSUE THREAD

**Issue by DanyNaumann** [FlutterFlow/flutterflow-issues#3467]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Some options disappear from the debug panel. For example, I no longer have the Page State option. It seems that when I go to another page, the information inside the debug panel doesn't refresh.

### Expected Behavior

The debug panel refresh when navigating in the pages and all informations are visible.

### Steps to Reproduce

1. Launch Test Mode
2. Open the Debug Panel

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wksrlvJRgruFG0KXxbcdFmjgXIjs1U7hIl8B9aCs8GZT0B4kcYs+kfklUcOm4TVVMfWK0nmIX/Mr2i9r2GMFePQ6WfpRf+qt9FwyUQl6hRLq6PL63b3BAI/tVGmK00ZiVgSV5NbdtWV4C1DqYe/CtHnLfQoOzPFUCD+aoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/9270c5f7-814f-4dd4-836a-1d3c8620bc27

### Environment

```markdown
- FlutterFlow version: 4.1.75+
- Platform: Web
- Browser name and version: Chrom Version 126.0.6478.127
- Operating system and version affected: Windows 10
```

**Comment by DanyNaumann** [comment]
From the console in the browser, I have these messages

![image](https://github.com/user-attachments/assets/af4399f6-1699-463e-bcb6-721b4924c7b4)

**Comment by msusviela** [comment]
Hi @DanyNaumann. As for the debug options, I wasn't able to replicate it from blank. Debug is working fine for 4.1.75. The app state variable are appearing (only when i have page variables defined) and it's refreshing properly. Could you tell us if this is still an issue for you and if that happens in all your projects?<br><br>Regarding the second issue,  some users have already reported the same. The ENG team already worked on a solution for that and it's being passed over QA at the moment. You can follow that here:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3366](https://github.com/FlutterFlow/flutterflow-issues/issues/3366)

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
