### ISSUE TITLE
Bug in widget Text

### ISSUE THREAD

**Issue by emerson-almeida** [FlutterFlow/flutterflow-issues#3471]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

todos os widget de texto simples estão desconfigurando aleatoriamente. no construtor, o widget tem uma infomação, mas no preview de teste run e também na publicação web, os valores sãoalterados, para o valor do último widget d etexto incluido nas páginas

### Expected Behavior

espero q o resultado seja o desenvolvido no construtor

### Steps to Reproduce

acesse apenas o endereço loja.capitalapp.com.br, crie uma conta e veja o q acontece

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT88lfLqy49IsctD+Krqde9ajikvJjs/a+YwluxqEAg1F73qB4l3Z8/7VEpAXsThYGxteU22gVsBpqHMuOOWF/tdIUiqc7p4wql+Sx/PRXGtM6abDM2KYEFTPNxjGHa6yLuzpRF4OrFoXHs321OQOfPKYCzqQe77OUYFP/GhNd7VnWCnHA3/Ujsw+x0PH2mwEfljIVDq+f6QspZl1eTjzw==

### Visual documentation

![image](https://github.com/user-attachments/assets/87662ec4-3e73-4a01-b1a9-1ec671f0078e)
![image](https://github.com/user-attachments/assets/1b4f1ae0-4baa-470c-80a7-ec114bdd0d90)

### Environment

```markdown
- FlutterFlow version: 4.1.75+
- Platform:web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by LeandroFerreira1** [comment]
Estamos com o mesmo problema, começou após a atualização de ontem. Acontece também em modal, campos somem ou são alterados por outros de modals diferentes. vai alem de TextField.

**Comment by leoleo-s** [comment]
Eu estava com o mesmo problema e resolvi deletando os text widgets com problema e colocando novos no lugar. As minhas traduções estavam completamente erradas antes, aparecendo campos de um texto em outro.

**Comment by emerson-almeida** [comment]
obg leoleo-s... resolveu aqui tbm!

**Comment by emerson-almeida** [comment]
resolvido. tem q trocar todos os widgets q estao com bug e por um novo no lugar
