### ISSUE TITLE
Text widget and Rich text widget breaking the page when retrieving info from Revenuecat

### ISSUE THREAD

**Issue by leoleo-s** [FlutterFlow/flutterflow-issues#3472]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to retrive info from Revenuecat (e.g. Price string), the text and rich text widget will cause a red screen on Test Mode, Grey Screen on run mode and web. On a real device it works (tested on iOS only).
I'm aware that Revenuecat only works on native version, but the test, run and web shouldn't be broken. It should at least show the default variable value instead of a red or grey screen. This turns testing much more difficult.

<img width="498" alt="Screenshot 2024-07-24 at 11 12 08" src="https://github.com/user-attachments/assets/39e66c01-98d0-46ea-b537-6e694b461808">
<img width="498" alt="Screenshot 2024-07-24 at 11 12 25" src="https://github.com/user-attachments/assets/0328512a-685b-4665-81a5-0e9e576a4f30">

### Expected Behavior

Text and Rich text widget should retrieve the info and show as it would normally. Due to platform compatibility, it should at least show the default variable value instead of breaking the app.

### Steps to Reproduce

Create a page, put a text and rich text widget, retrieve info from variable (revenuecat > price string), open test and run mode, navigate to the page. 

https://github.com/user-attachments/assets/cecc1cb3-fb3c-4460-abee-7d388ced38d5

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lPHqx5d2m+FG+KryafpvtCAsQzI7a7s8mMFtbA88KOvLBIYuP/XsRFFBUuaoTWw3PkSmmTgCwvTMj+LXGPcpE06Aft1q1pZISBbhVjmhe5OBDaiwX2hDJ91MClC40p+Rnh4lWfhsWC0a7GCEe/K9Qh/tGO/xImdISq/LZO4=

### Visual documentation

<img width="498" alt="Screenshot 2024-07-24 at 11 12 08" src="https://github.com/user-attachments/assets/47c13f8a-eba0-4159-ae5e-c2a962d74450">
<img width="498" alt="Screenshot 2024-07-24 at 11 12 25" src="https://github.com/user-attachments/assets/79fba6d0-a550-4048-8959-126d55798650">

### Environment

```markdown
- FlutterFlow version: 4.1.75+ Synced
- Platform: Web (test, run, and web)
- Browser name and version: Chrome 126.0.6478.183 (Official Build) (x86_64)
- Operating system and version affected: MacOS Ventura 13.6.7
```

### Additional Information

This turns testing much more difficult as I need to deploy to TestFlight to test it out.

**Comment by Alezanello** [comment]
Hello!

The RevenueCat integration can only be tested via Emulator or Real Devices, as explicitly stated in the documentation: [RevenueCat Testing](https://docs.flutterflow.io/settings-and-integrations/in-app-purchases-and-subscriptions/revenuecat#id-6.-testing).

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6397a1f7-b7df-486e-b159-3fe2aea70981/89e60a5d-1848-4c9f-8441-18387281e3ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82Mzk3YTFmNy1iN2RmLTQ4NmUtYjE1OS0zZmUyYWVhNzA5ODEvODllNjBhNWQtMTg0OC00YzlmLTg0NDEtMTgzODcyODFlM2FjIiwiaWF0IjoxNzIxODUxNDY1LCJleHAiOjMzMjkyNDExNDY1fQ.3dcdChOFuEXotiERgVuFDJn_8F4MUxxJ8pUEptlbdOw " alt="image.png" width="1007" height="273" />

One thing you can do is run your app locally using FlutterFlow's MacOS app or through VS Code after downloading the code, depending on your preference. This approach improves your testing process without having to wait for the TestFlight deployment.

Best regards,<br>Azanello

**Comment by leoleo-s** [comment]
This is really bad =(

**Comment by leighajarett** [comment]
Sorry that this isn't working as you expected 🙁 <br><br>Were you able to try testing with local run? Check out this documentation for more info: [https://docs.flutterflow.io/deploying-your-app/testing-your-app/testing-on-mobile-device](https://docs.flutterflow.io/deploying-your-app/testing-your-app/testing-on-mobile-device)
