### ISSUE TITLE
The changes in the project is not being updated on the emulator. I am unable to develop anything. 

### ISSUE THREAD

**Issue by pratik3211** [FlutterFlow/flutterflow-issues#3475]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to make basic changes on the app like text changes, modifying the UI or anything. It doesn't update on the emulator or simulator... I tried multiple devices, both physical and in-app simulators. 

### Expected Behavior

I expected the changes to show up on hot reload or when I restarted the project, but it didn't work. I thought its an issue with me hitting the project limit but this is not the case. 

### Steps to Reproduce

Not sure this can be reproduced for everyone, but simply making any changes on the app is not being reflecting on any of the devices connected or simulators... 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/luIt1rscF+KrpKvl4oCgRGUMCXLhE0ddTRUo0fbKoPJoTOur+VGhbZ/3kfQtiPE2jkl8e3OiNhobMFfpdJk+bQoNo+c9MTQ7KYEy7VpSwCquWVUFCP95RfWK717bUkBZCKrBfSFplw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

This is the output on emulator, which is incorrect. 
<img width="967" alt="Screenshot 2024-07-25 at 1 30 47 PM" src="https://github.com/user-attachments/assets/164f87c8-2943-43d5-8782-11ccb3c4a7f2">

This was suppose to be the output on emulator, see I've changed the text... 
<img width="519" alt="Screenshot 2024-07-25 at 1 15 53 PM" src="https://github.com/user-attachments/assets/3da7b89c-bd04-439d-bd02-5151279e04dc">

### Environment

```markdown
- FlutterFlow version: 4.1.76+
- Platform: Mac OS
- Browser name and version: Chrome: 126.0.6478.183 (Official Build) (arm64)
- Operating system and version affected: Mac OS Sonoma 14.5
```

### Additional Information

NA

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. I can't reproduce it on my end. I created a new blank project, added a button, and it showed up in the iOS Simulator within 2 seconds. I'll share the video as proof. Could you record your interaction with your current project to help determine if this is a project-specific issue?

[Screen Recording 2024-07-25 at 9.30.40 AM.mov](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2dee51c1-b1a4-4daa-8558-b5145d4d81d3/1e998f60-d468-4101-8dd3-f254d19f9ddc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZGVlNTFjMS1iMWE0LTRkYWEtODU1OC1iNTE0NWQ0ZDgxZDMvMWU5OThmNjAtZDQ2OC00MTAxLThkZDMtZjI1NGQxOWY5ZGRjIiwiaWF0IjoxNzIxOTEwODkyLCJleHAiOjMzMjkyNDcwODkyfQ.dxB_0RGHZXZJhMBx_zMpCaxb9TlBD-xB5mNGI61uRyA)

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
