### ISSUE TITLE
In Flutterflow teams all the things we do disappear and we are not connected

### ISSUE THREAD

**Issue by rafaelmorenoescamilla** [FlutterFlow/flutterflow-issues#3476]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow does not work in general. It undo what is done, the things one member of the team does do not appear in the other

### Expected Behavior

That it works as always

### Steps to Reproduce

Do whatever

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeksrq25dNpbxJ16rydflViQMwJ0QlUIInj+0bWRMhfeKqOpkQeOClVBJLYteLS2x+G2f9hmUe+vDVvfHtV8cBAzOZfoB8yoRXQQLJVmOubJClEKWWWnJBP51bIWKcy7aRnyMnOu11S3wD72WlevCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

There is not visuals

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @rafaelmorenocamilla. I understand your concern but without basic information about the issue, it's impossible for us to replicate your issue and to investigate into it.  
Could you please provide more information on the issue? We need to know exactly what's failing.

Please, provide the steps to reproduce from blank.

Thanks!

**Comment by rafaelmorenoescamilla** [comment]
All is failing in general. Every thing you add, every action you build in
matter of minutes is undone.
Also my teammate and I were sharing screens to see if we were synchronized
and he had 8 bugs and I had 4 in the same project which meant something was
really wrong.
I can not give any specific way to reproduce the bug because simply the Flutterflow app
does not work. Also a pop up saying the project wasn't connected to your
servers appeared

**Comment by msusviela** [comment]
Are you using web or desktop and which version of FlutterFlow are you and your team using? On which operative system are you working?<br><br>Also, by team are you reffering to a project with collaborators or the projects here:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f88081ee-36d0-4cde-b88e-28f06bba83d7/28ec8a22-eb1a-42a7-8c35-6419e6016a10?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mODgwODFlZS0zNmQwLTRjZGUtYjg4ZS0yOGYwNmJiYTgzZDcvMjhlYzhhMjItZWIxYS00MmE3LThjMzUtNjQxOWU2MDE2YTEwIiwiaWF0IjoxNzIxOTA0OTA0LCJleHAiOjMzMjkyNDY0OTA0fQ.NE7fx1aCai2VWPpxfI5DkkTynHQStofo7S6HRA6gzg0 " alt="image.png" width="189" height="197" />

**Comment by rafaelmorenoescamilla** [comment]
We are using Flutterflow Windows and Flutterflow IOS as well as Flutterflow Web to Run Tests.
We are an organization formed by two members one with a Mac and the other with a Windows computer.
The version is the latest you uploaded this morning.
v4.1.76+

**Comment by msusviela** [comment]
Hi @rafaelmorenoescamilla. The team already worked on a fix. it should be up for next release.
