### ISSUE TITLE
WebApp Custom Domain : Cannot add custom domain whereas i have premium account

### ISSUE THREAD

**Issue by Mktotoy** [FlutterFlow/flutterflow-issues#348]
![image](https://user-images.githubusercontent.com/11921259/212141705-27477aff-0c61-4f1f-a7ca-77817d24a882.png)

I already have another app which is already using a custom domain.

I try to add a custom domain for web publish another application, on a different url (sure)

But i cant connect because FF ask me to be premium.

Regards

**Comment by wenkaifan0720** [comment]
Hi @agreaves. I forgot what our current policy is regarding custom domains. Can the user add multiple custom domains right now?

**Comment by organicnz** [comment]
> Hi @agreaves. I forgot what our current policy is regarding custom domains. Can the user add multiple custom domains right now?

Would be good to know, guys :)

**Comment by aemelyanovff** [comment]
A user can only connect one custom domain across all projects at the moment. Connecting multiple custom domains is work in progress.

This looks like a bug anyway - even though it should not connect a custom domain if the user already connected a domain to another project, the message it shows is just plain wrong.

@Mktotoy Thanks for reporting the issue. Please follow the bug report template next time :-)

**Comment by wenkaifan0720** [comment]
I'll set this issue to low priority now. As it would probably be fixed by our next update on custom domains.

**Comment by wenkaifan0720** [comment]
I think this now supported in FF. I'll close this issue.
