### ISSUE TITLE
Some Text, Tool Tip, and Button label fields values not showing updated values in Test Mode

### ISSUE THREAD

**Issue by gwatkins1957** [FlutterFlow/flutterflow-issues#3481]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After changing the values of some text fields in the builder those changes are not showing up in Test or Web Publishing run mode. I am seeing this happen with text fields, tool tips, and button labels.

### Expected Behavior

Changes to text values should show up in Test mode and on the web.

### Steps to Reproduce

1. Create new page
2. Add text field widget
3. Set text field value
4. Run test mode
5. Check text field value updated

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SzuflvYtOj7xE7qXyc8JFiiURMjslRY00lu16EAAbG4/kOok1XOnAVE5pQte0YGxqeU39kjofw8HemvHhEvYrH0mbfbpawpBpExXKbGWueL6qCbWWWW5/Df1XFUif4ZiVugpSOrdtV0ID12GlfPCXH3PbNJzxOm0NJ86aD5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/bfd7287d-d21e-4669-ba0c-d7f182db5856)
![image](https://github.com/user-attachments/assets/fd04a7e9-25eb-4e1f-bdbd-a08bf3b1668a)

### Environment

```markdown
- FlutterFlow version: 4.1.76+
- Platform: Web
- Browser name and version: Chrome 127.0.6533.72
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello!

To rule out any issues that could be related to network speed or other factors, could you please share a short video showing this behavior? This would help us a lot, as I can't replicate this behavior on my end, but I see other users reporting similar issues. We need all possible data to understand and resolve this issue.

Thanks in advance!

Best regards,<br>Azanello

**Comment by gwatkins1957** [comment]
I will see what I can do. Also, I think this may be related to using a template because the text that is displayed is the original text that was in the template.
 
Greg Watkins
Digital Speech Systems
email:  ***@***.***> ***@***.***
direct: 972-235-2999 ext. 133
cell: 214-455-4814

**Comment by gwatkins1957** [comment]
Here is a link to a video that shows when it happens. The weird thing is that it seems to be entirely random when it doesn’t work. I tried it with a new page and a new component and they both worked just fine, but on some pages or components it never works even though it worked before and on other pages it always works. On the ones that don’t work they always fail on any text change. This seemed to start happening earlier this week after one of the updates. I just installed the latest update and it still has the same issue. Very weird.
 
unknown_2024.07.26-09.08.mp4 <https://1drv.ms/v/s!At9LUTsa6kSyk7014dflHbtiZ0huxA?e=jFd9fI> 
 
Greg Watkins
Digital Speech Systems
email:  ***@***.***> ***@***.***
direct: 972-235-2999 ext. 133
cell: 214-455-4814

**Comment by gwatkins1957** [comment]
Any update on this issue?
 
Greg Watkins
Digital Speech Systems
email:  ***@***.***> ***@***.***
direct: 972-235-2999 ext. 133
cell: 214-455-4814

**Comment by Alezanello** [comment]
Hi there!

I wanted to check in and see if this issue has been resolved with the latest updates?

**Comment by gwatkins1957** [comment]
Yes, it looks like the issue was resolved. 
 
Thanks
 
Greg Watkins
Digital Speech Systems
email:  ***@***.***> ***@***.***
direct: 972-235-2999 ext. 133
cell: 214-455-4814

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
