### ISSUE TITLE
Text shows "Hello World" on device but not in FlutterFlow builder

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#3482]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the FlutterFlow ui some of my text widgets show the desired text. But some of the texts show "Hello World" or nothing at all in the text widget.

### Expected Behavior

The value entered in FlutterFlow ui shows the correct value defined in the text widget.

### Steps to Reproduce

1. Create Text widget with text
2. Launch app on device

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lsn635NIsbRG0LrfbcBB/SY5Jkc7ao0S0NVtaA88KOvLBIYuP/XsR1poXu2odwhte0Smmn4EwcLFhvLPOsAoHw6Yf755yJd2Eg3KXTqgUZOBPc+/PXd6J8JjCFSc5LS0kBEkBMR0SGQ51GeMDNzJQh3sK5DrImdISq/LZO4=

### Visual documentation

Flutterflow ui:
<img width="79" alt="Bildschirmfoto 2024-07-25 um 21 29 27" src="https://github.com/user-attachments/assets/dad41624-27da-4bff-82f5-a9ddab7bcd2b">

device:
<img width="82" alt="Bildschirmfoto 2024-07-25 um 21 29 47" src="https://github.com/user-attachments/assets/ce71ef9b-cbd1-443b-bb7f-ca8c4ff7ff93">

### Environment

```markdown
- FlutterFlow version: v4.1.76+
- Platform: Android/iOS
- Browser name and version: Safari/Chrome
- Operating system and version affected: MacOs
```

**Comment by Alezanello** [comment]
Hello!

To rule out any issues that could be related to network speed or other factors, could you please share a short video showing this behavior? This would help us a lot, as I can't replicate this behavior on my end, but I see other users reporting similar issues. We need all possible data to understand and resolve this issue.

Thanks in advance!

Best regards,<br>Azanello

**Comment by Jensoulus** [comment]
Hi @Alezanello ,

i am not sure how a video would help and what you want to see in the video. Could you please clarify?

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. Before we proceed further, did the latest FlutterFlow updates resolve your issue?

Best regards,<br>Azanello

**Comment by Jensoulus** [comment]
Hi @Alezanello,
yes - It seems that the error is gone. I will close this topic

**Comment by king-anna** [comment]
I have this issue: not only text but fields and buttons. When I deploy again, even more elements are affected.
