### ISSUE TITLE
It's not saving the Automatically Validate of the forms. Every time I open and close Flutterflow, I have to configure it again and it gives an error in Issues and in my app...

### ISSUE THREAD

**Issue by johnivy1** [FlutterFlow/flutterflow-issues#3487]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It's not saving the Automatically Validate of the forms. Every time I open and close Flutterflow, I have to configure it again and it gives an error in Issues and in my app...

### Expected Behavior

I want to set it up once and not have to keep fixing it, imagine having to redo the app every time

### Steps to Reproduce

1. just save what was done

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

i don know

### Visual documentation

![Screenshot 2024-07-26 084631](https://github.com/user-attachments/assets/f8bb165c-1536-4aea-a309-0b27aa19e7d7)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SebyOnGitHub** [comment]
I have the same problem (But by opening a snack bar on error)

**Comment by msusviela** [comment]
Hi @johnivy1

With the information you provided, I'm unable to replicate this from a blank project.

Could you please tell us the steps to reproduce it from a blank project?, also could you please share the bug report code for this?  You can create one by clicking right on the widget tree and selecting the option to generate a bug report code. This guide can help you to generate it: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)

**Comment by johnivy1** [comment]
It's just a form that isn't saving the Automatically Validate settings. That's all, and there are other people with the same problem. You configure it and add the Issue, then it returns as if it wasn't adjusted...

**Comment by msusviela** [comment]
We're still unable to replicate this from our side, could you tell us which type of validation are you trying to do (what are the conditions to validate, the widget you're validating)? I see that in your project you have textfields and dropdowns, does this happen with every type of widgets?

**Comment by msusviela** [comment]
What I think it might be causing it, it's that you have a button inside the form. Can you tell us if it works without the button in the form?

For example, if the widget tree looks like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3116fedc-5fcd-41ec-8183-b4ebff43fa50/c421b9a8-5455-4090-8de9-833f388ef041?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMTE2ZmVkYy01ZmNkLTQxZWMtODE4My1iNGViZmY0M2ZhNTAvYzQyMWI5YTgtNTQ1NS00MDkwLThkZTktODMzZjM4OGVmMDQxIiwiaWF0IjoxNzIyMDMwNzYyLCJleHAiOjMzMjkyNTkwNzYyfQ.Yqmaukn8IHznazZJVd6axQMDOyq0wEoU2YIpe-4wPI0 " alt="image.png" width="179" height="131" />

Try moving out the button out of the form like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/125d054b-0a66-43d9-b71c-b5cf4115a5fd/14d7b247-30a1-422f-8962-93b346917a22?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMjVkMDU0Yi0wYTY2LTQzZDktYjcxYy1iNWNmNDExNWE1ZmQvMTRkN2IyNDctMzBhMS00MjJmLTg5NjItOTNiMzQ2OTE3YTIyIiwiaWF0IjoxNzIyMDMwNzYyLCJleHAiOjMzMjkyNTkwNzYyfQ.kPt2tVmMcW2EjyYe9-lV1a4V6Y1aMJVefexd2MymEIE " alt="image.png" width="205" height="197" />

Please, try this workaround and tell me if it's what's causing the issue. That's a known issue regarding forms that our team is currently working on.

If not, please share the **bug report code** so we can check the form you created and try to replicate this from our side. Maybe we're missing some widget that might be broking it and it'll be very helpful.<br><br>@johnivy1

**Comment by SebyOnGitHub** [comment]
@msusviela 
This bug is very easy to get. There is no button needed to break it.
Just use a DropDown and thats it.

Here I created this from a blank project: (Feel free to take a look, you just need to set the action type inside the Form to e.g. "Show Snack Bar", and write some text in it, close the project and reopen it)
IT4ozfLl8Y92scsA7q6JcMdVryQ6JUA2bZIvjMpBZywgfZzzBLN/fPfQP1BCcObhY1FUPE2cp14d3NbJivPxF/kBNSiCG7o51KpQEz3heEynRbGTF7iCP3B6HfhgGm6Y57Szph1+IrNack4u2V+uOu7KFwPcNbrsDlQwSq/LZO4=

**Comment by msusviela** [comment]
Thanks. I was able to replicate it. The issue is within dropdowns. I'll send it to the ENG team so they can work on that.
