### ISSUE TITLE
Web publishing doesn't work

### ISSUE THREAD

**Issue by dr-shoe** [FlutterFlow/flutterflow-issues#3489]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have used both a custom domain and a site URL for web publishing, but nothing is displayed regardless of which URL I access; the page is blank. The mobile app is functioning correctly.

### Expected Behavior

When I search the URL, the /signin page is displayed.

### Steps to Reproduce

To search the URL.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMmAx89gofVA1pDLbcFvnikXJno1TL07ttYbZxUjIuPtBJh/fc7ebk1tOPbmTENhHFCZ+XkJ+tr0hvLxFcYnHAeAfLpDyLhcWArKUXq8R6bTPrmKWHJBBeFXCWai5MG3sCZ7LvtZSmAd7VyUNe+vYCnrN5+/Zwh9f6PHaOI=

### Visual documentation

![スクリーンショット 2024-07-27 005052](https://github.com/user-attachments/assets/dede353b-3f28-49cf-a66b-bb946e95031b)

### Environment

```markdown
- FlutterFlow version: 4.1.76
- Platform: Web
- Browser name and version: Chrome, Safari
- Operating system and version affected:
```

**Comment by bmw559** [comment]
Hey, I have the same experience it seems they onboard a bug with the latest build on 26.07
Hopefully it will be soon resolved ..

**Comment by leighajarett** [comment]
We're taking a look, thanks!

**Comment by bmw559** [comment]
Any news regarding this ? I think its pretty high impact bug for the flutterflow clients, its not working in general or only few projects are impacted by this ?

**Comment by victoriahuang1** [comment]
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/84cfbc67-edcd-4206-a8ab-f5dce8b8afd8/d5aa7e7e-091f-4bdd-b440-c83ad5034273?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NGNmYmM2Ny1lZGNkLTQyMDYtYThhYi1mNWRjZThiOGFmZDgvZDVhYTdlN2UtMDkxZi00YmRkLWI0NDAtYzgzYWQ1MDM0MjczIiwiaWF0IjoxNzIyNDQ3Nzk3LCJleHAiOjMzMjkzMDA3Nzk3fQ.Smw2InBMndrBN3OyXeiXIg1x0NuqDYjBaDMBJiHu6cU " alt="Screenshot 2024-07-31 at 10.42.41 AM.png" width="1890" height="1032" />

This looks like it's working for me.

**Comment by bmw559** [comment]
> <img alt="Screenshot 2024-07-31 at 10.42.41 AM.png" width="1890" height="1032" src="https://camo.githubusercontent.com/77994f58268331f67220b7e0b4940ae16672f557468dd18022ec7b765ab269b3/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f38346366626336372d656463642d343230362d613861622d6635646365386238616664382f64356161376537652d303931662d346264642d623434302d6338336164353033343237333f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a5338344e474e6d596d4d324e79316c5a474e6b4c5451794d445974595468685969316d4e57526a5a5468694f47466d5a4467765a4456685954646c4e3255744d446b785a693030596d526b4c5749304e444174597a677a595751314d444d304d6a637a4969776961574630496a6f784e7a49794e4451334e7a6b334c434a6c654841694f6a4d7a4d6a6b7a4d4441334e7a6b3366512e536d7732496e424d6e6472424e334f795865695849673178304e757144596a4261444d424a69487536635520">
> 
> This looks like it's working for me.

Did you try to publish with the latest flutterflow build ?

**Comment by victoriahuang1** [comment]
@bmw559 I did not publish, but just opened the link that @dr-shoe published to.

@bmw559 this is a project specific issue, and you are likely facing a different issue than the user that posted the original issue. As such, please open a new Github issue with all your info (project ID, bug report code), so that we can investigate further. The original issue seems to be resolved.

**Comment by bmw559** [comment]
> @bmw559 I did not publish, but just opened the link that @dr-shoe published to.
> 
> @bmw559 this is a project specific issue, and you are likely facing a different issue than the user that posted the original issue. As such, please open a new Github issue with all your info (project ID, bug report code), so that we can investigate further. The original issue seems to be resolved.

Will do, but I had exactly the same issue mobile apk is working perfectly but published web doesnt work even deployed on custom hosting.

**Comment by victoriahuang1** [comment]
@bmw559 it's likely due to some package that your project is using, that the project in this particular issue isn't. But there are a lot of packages out there, so it's hard to say for sure what's going on without more info.
