### ISSUE TITLE
Pie Chart: Rounding the section label value instead of exact values. Feature or Bug?

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#349]
## Expected behavior (required)
Using a pie chart I would like to show exact number values for the different sections

## Current behavior (required)
At the pie chart only rounded numbers show up for the sections. Is this a feature or bug?

## To Reproduce (required)
1. Create new page
2. Add Chart widget
3. Select Pie Chart
4. For section values use a local state (list of doubles) with relatively big numbers like 213023. See my screenshot.
5. At the Pie Chart properties for Section Label Type select Value
6. Run mode or test mode
7. Observe that the section label values are rounded.

### Bug Report Code (required, generate from Widget Tree)
ITESz/Hqx89gruEG+bn+Ke16hR8kQ2InarsvhO4bRRIaF7LmEJYtbuvTQHtuO9fiYH1qC1eJkkwyws2Mv9/tN/EoOS/DJ+AHl/E0LlSrGAc=

## Context (required)
Trying to show sum of revenue for different type of events, and would be crucial to show exact numbers.

## Screenshots / recordings
![pieprops](https://user-images.githubusercontent.com/103430937/212296548-fca53678-e368-44c8-9bd1-ddddc4e69428.png)
![localstate](https://user-images.githubusercontent.com/103430937/212296571-a6700571-a9e0-4e93-ada9-d0770acf02d4.png)
![piechartres](https://user-images.githubusercontent.com/103430937/212296580-6a7f9c57-e8da-44b3-8eac-541eddb34268.png)

## Your environment

* Version of FlutterFlow used: 3.0 January 12
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): Windows 11

**Comment by Pepino-GR** [comment]
hi tothati90,

I can reproduce this issue. Thanks for reporting

**Comment by shelpert** [comment]
Hello,

This wasn't quite a bug but we agree that it is not ideal! We've added the option to choose the number format of labels on the pie chart and line and bar chart axes so that you can customize your formatting. Labels will originally be set to the default formatting (two significant digits) until you change them, so keep an eye out for this new feature in an upcoming release!
