### ISSUE TITLE
unknown error after check for errors of 2 custom actions in flutterflow v4.1.78

### ISSUE THREAD

**Issue by maxi376** [FlutterFlow/flutterflow-issues#3491]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After checking for errors in 2 custom actions I keep getting unknown error which is very wierd because in previous iterations of the deleteItemsFromShoppingCartBatchDelete I didnt get this error. And previously to this custom action I didnt get this unknown error at all I think I am not 100% sure.

### Expected Behavior

I expect there to be some sort of error,even if it is extremly general

### Steps to Reproduce

1.Write my deleteItemsFromShoppingCartBatchDelete action
2.And then after some sort of change in the code you should get unknown error after checking the acton for errors.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9VliIvKUA+R600st5Hd0gdCOPrBux3PvTBdhdDXb3maVNfMWGl/U8E0a3tidjPFMADAEitR7Vxz5Z+Sw3ee2iiV4iuBauWdGtCIJ9NG0yG1p6zuxFNItBiSXg/62Cbe+u/HzLDIuu/Zwh9f6PHaOI=

### Visual documentation

no images

### Environment

```markdown
- FlutterFlow version: v4.1.78
- Platform: web
- Browser name and version:chrome 126.0.6478.185
- Operating system and version affected: windows 10 KB5040427
```

### Additional Information

Cannot complete my custom action.

**Comment by paulperez-dev** [comment]
Hi @maxi376! Can you please send a video showing how to reproduce the issue?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
