### ISSUE TITLE
Set fields from JSON-Path on login disappears after saving version or reload

### ISSUE THREAD

**Issue by Valerzen88** [FlutterFlow/flutterflow-issues#3493]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using custom auth with json path for set user data in user data obj (data type). But since 4.1.76-78 it will be erased each time I save or reload app (see video).

### Expected Behavior

I expect, that data, I put into action from json path will state there and dort disappear after saving or reloading the page.

### Steps to Reproduce

Login btn -> add action for auth - log in -> set data -> set data from json path -> reload page or save version.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lsrq25JIobhb7qrpbcdR/SA5KUd9UL83mMFRaCgoIYyuOpl/evWkXxNDXfW+YAk3OESmmlE1+sLoiuzEFe44FxCsf7Zf+bhUbwHzQlihe5OBBZbheHx7J+NWN3aayqbYsSJQWLBYW3wl3ziUffCsbHHcGYTwImdISq/LZO4=

### Visual documentation

video in as dropbox link: https://www.dropbox.com/scl/fi/j0z2lc3tx2b0mrbdnyvhn/Bildschirmaufnahme-2024-07-27-um-13.15.28.mov?rlkey=nzqaifu35chwd8c2csnxwqhot&st=3jymdzey&dl=0

### Environment

```markdown
- FlutterFlow version: 4.1.78
- Platform: Web
- Browser name and version: Chrome 126.0.6478.183
- Operating system and version affected: MacOS 14.5
```

**Comment by msusviela** [comment]
Hi @Valerzen88. I was able to replicate the issue. I'll send it to ENG so they can work on this

**Comment by Valerzen88** [comment]
that is not issue #3506 it is in action editor, but has something to do with "Set Data".
