### ISSUE TITLE
Razor pay integration does not work for web after publishing the app.

### ISSUE THREAD

**Issue by sumitmodi84** [FlutterFlow/flutterflow-issues#3494]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Razor pay integration does not work on web after publishing. During development testing phase it works.
Reason for this is that it tries to download **src/razorpay_checkout.js** which returns **404** and all the subsquent call fails.

### Expected Behavior

**src/razorpay_checkout.js** should not return 404...

### Steps to Reproduce

create a web project with razor pay integration
publish the project
launch razor pay....it will stuck and in console it print self.checkout undefined.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klcjhuItJpbxG+KrtbcB4qGAXQ0QgTLJEoetxc0gbfe/4Ouw2Z8mlbRduXsizaHw7G1aJoFMJp8rwudrhKPQEAE2dRqJiwahqWBPPbE65VYTRBpCVPEZfP8NYfH2MyJjR2BJRANNidVku712MGOTJYz+Cf9qOYwx5e6fDbOY=

### Visual documentation

Can not share

### Environment

```markdown
- FlutterFlow version: 4.1.78
- Platform: web
- Browser name and version:chrome
- Operating system and version affected: all
```

**Comment by paulperez-dev** [comment]
Hi @sumitmodi84! I noticed that your project is not [configured for production](https://docs.flutterflow.io/settings-and-integrations/in-app-purchases-and-subscriptions/razorpay#id-4.-releasing-to-production):

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/35e12993-1d79-4a36-acff-749d624a872c/2e35272b-4113-4f94-a96d-e35b77a3de8c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNWUxMjk5My0xZDc5LTRhMzYtYWNmZi03NDlkNjI0YTg3MmMvMmUzNTI3MmItNDExMy00Zjk0LWE5NmQtZTM1Yjc3YTNkZThjIiwiaWF0IjoxNzIyMzAzMjM1LCJleHAiOjMzMjkyODYzMjM1fQ.PRbnDkhXdKklXQWFmK2MmExCViph_VdwzrBDrbIH6EM " alt="image.png" width="1614" height="630" />

I'm closing this issue.

**Comment by sumitmodi84** [comment]
Yes, but it is in testing phase.
@paulperez-dev  Do you mean that for Razor pay testing, it needs to be production, It can not be tested with published URL....?

**Comment by arpit786shukla** [comment]
I am having the same issue. I contacted the support and they told Razorpay Payments is not supported in web. Is it the case? If so then how can I allow web app to integrate with Razorpay inside flutterflow?

**Comment by sumitmodi84** [comment]
@arpit786shukla Yes, they have mentioned it on there website but i think they have not updated the same from 2023. Razor pay works on most of the website. They might have some issues in few o fhte countries.
To resolve the issue, if you are hosting the website on your domain, make sure src/checkout.js is accessible. It seems like flutterflow domains are not allowing it to download the file and hence, razor pay integration is not triggered.
If you are not hosting it on your own domain, you can copy the contents of sre/checkout.js and include it as part of your meta tags on the flutterflow app. This will trigger the flow.
