### ISSUE TITLE
ChatPage1 gray screen

### ISSUE THREAD

**Issue by ingsistempro** [FlutterFlow/flutterflow-issues#3495]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding the "ChatPage1" component to my app in FlutterFlow, the screen turns completely gray and blocks the display of other widgets. If I remove the "ChatPage1" component, the other widgets display correctly. This issue occurs in the FlutterFlow development environment.

**Actual Behavior:**
The implementation of "ChatPage1" causes the entire screen to turn gray, blocking the display of any other widgets on the page.

### Expected Behavior

**Expected Behavior:**
When adding the "ChatPage1" component, it should display correctly alongside other widgets on the page without blocking the entire screen.

### Steps to Reproduce

**Steps to Reproduce:**
1. Open FlutterFlow and load your project.
2. Add the "ChatPage1" component to one of  app's pages.
3. Save the changes and preview the screen in the development environment.
4. Observe that the screen turns completely gray, and no other widgets are displayed.
5. Remove the "ChatPage1" component.
6. Save the changes again and preview the screen.
7. Observe that the other widgets now display correctly.

**Possible Cause:**
There may be an issue with the configuration of the component "ChatPage1" component that is interfering with the rendering of the page.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcmAvM91rs9H+YSJdcBKmiQ6NkccTIAzjdZxcykgGL7yBu0DOvTCZRZvXu28aVNcIFKlnkUF0975hobXFsc4GASZbaZ+zapiUDn0e2iXRa6mO4eOYHJPMJ5UCkyYyrSznyJ7HLR2ck4k61yQe++XXjbDIuu/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/46068da0-924c-4e87-bf42-f16a4c7dadae)
![image](https://github.com/user-attachments/assets/5c746b6f-83ac-4dc5-9bbc-e1cf4d0b81f3)

### Environment

```markdown
- FlutterFlow version: 4.1.78
- Platform:Windows 
- Browser name and version:Versión 124.0.6367.119 (Build oficial) (64 bits)
- Operating system and version affected: Windows 10 Pro
```

**Comment by rzambroni** [comment]
Hey @ingsistempro, thanks for the report, unfortunately, the chatpage is  deprecated because it was old and buggy. marking this ticket as a duplicate in favor of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3213](https://github.com/FlutterFlow/flutterflow-issues/issues/3213)
