### ISSUE TITLE
Custom Action name "unset" after renaming function

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#3497]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After renaming a custom action, the action name shows "unset" in the editor

### Expected Behavior

Should show the new name

### Steps to Reproduce

1. Create a custom action
2. Add a custom action to any flow
3. Change the name of the action
4. view in the editor

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87lx4lgoddA1rrtbcExvCo4H245TLJEoetxc0gbfe/4EOx/Y8ykUFRVcOKzaH1EClW0nToe0dGNueDtJPldKTSac6pczJZ+bBPPbFu5MbqaC7WCPWpPL+1WIHKzyMOw3CYmLsRpV04m2juyeei9Ej+Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="790" alt="Screen Shot 2024-07-28 at 1 00 04 PM" src="https://github.com/user-attachments/assets/c27f1e97-c3c6-435b-8fb8-818a4594555e">

### Environment

```markdown
- FlutterFlow version: 4.1.78+
- Platform: macOS
- Browser name and version: Chrome latest
- Operating system and version affected: macOS Monterrey
```

**Comment by rzambroni** [comment]
Hey @max-h-silverman, thanks for the report, i was able to confirm the behavior you are mentioning. The reference is being lost due to the name change, will ask internally to see if the references can be refactored/replaced when the function is saved.

**Comment by leighajarett** [comment]
When we went to resolve this issue, we realized it's already been fixed. Thanks for reporting!
