### ISSUE TITLE
Text is displayed twice when inputting multiple lines of Japanese in TextField.

### ISSUE THREAD

**Issue by stny-0518** [FlutterFlow/flutterflow-issues#3499]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you enter Japanese text into a TextField that allows line breaks, the input cursor position is displayed one paragraph below on a PC, while on iOS and Android the text you are entering is displayed twice.
Also, on iOS and Android, the overlapping gets worse as you add more paragraphs.

■PC
![タイトルなし](https://github.com/user-attachments/assets/577e49c6-f292-49ec-9d4b-460326148a37)

■ iOS and Android
![20240729-120736](https://github.com/user-attachments/assets/6cf77b6c-ad7c-4b52-b957-677ceee848dd)
![20240729-120745](https://github.com/user-attachments/assets/e6c63a18-66e4-4e52-acc6-0ca0259f2a17)
![20240729-120750](https://github.com/user-attachments/assets/b0ea2a9f-163b-46d8-82e3-1cb1c82eb5e9)

### Expected Behavior

■ PC
I want to prevent the cursor position from becoming a paragraph while I'm typing

■ iOS and Android
I want to prevent characters from being displayed twice

### Steps to Reproduce

1.Create new page
2.Add TextField
3.Clic Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grs8E7qruae1QhQIgQ0QnU7gnlO1ucx42C4jzEIl3PffeT0NKTMunS3NAHU6buGMC0MGKk+H9N/JdCy6cGdVl0JVATAKWQmq6RpCYDpaSdURfGd9PfUOM16ujgRV+PtVhSi0gwUOLNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

■PC
![タイトルなし](https://github.com/user-attachments/assets/a964f42f-dbc8-42b8-8abf-ba9eb17019fd)

■iOS and Android

https://github.com/user-attachments/assets/103defed-a295-4c1b-99ac-dbeb814c22ce

### Environment

```markdown
- FlutterFlow version: v4.1.78+ released July 27, 2024Flutter version is 3.22.2
- Platform:Web
- Browser name and version: Chrome 127.0.6533.64
- Operating system and version affected: Android version 10
```

### Additional Information

■ PC
I want to prevent the cursor position from becoming a paragraph while I'm typing

■ iOS and Android
I want to prevent characters from being displayed twice

**Comment by rzambroni** [comment]
Hey @stny-0518, thanks for the report. I was not able to replicate exactly that behavior. On my end it only writes one character and is not being duplicated. But I can see the cursor being placed below the character.

[screen-20240729-174741.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1cccd74e-1894-45df-8665-bf44c642140c/abd67bef-f322-482e-a654-e6f853fce67c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xY2NjZDc0ZS0xODk0LTQ1ZGYtODY2NS1iZjQ0YzY0MjE0MGMvYWJkNjdiZWYtZjMyMi00ODJlLWE2NTQtZTZmODUzZmNlNjdjIiwiaWF0IjoxNzIyMjg3MTMzLCJleHAiOjMzMjkyODQ3MTMzfQ.9G_iJ_1fnpQi9S5rv7Fgsm9ERy3Uw7d5ooSSsdu9UCg)

Is it happening on Android - Web only? Were you using chrome?

**Comment by stny-0518** [comment]
Hey rzambroni, thanks for your reply.
I'm having problems with both Android and iOS, Chrome and Safari.
When I view it on Chrome on my Android device,

 the text is displayed double, but when I view it on Safari on another iOS device, the cursor position is shifted and the blue band is also shifted, just like in the video rzambroni attached.

When I enter text in a normal app, it behaves like the video below.


https://github.com/user-attachments/assets/e214eef3-1a8b-4176-9f85-0123d566d0c6

**Comment by rzambroni** [comment]
Hmm, interesting, thanks for the additional details. 

I tried on both Android and IOS using Chrome and Safari respectively, and also the IOS app on the emulator with the same results. 

Will make a few more tests and will as another team member to give it a shot.

Since the project you shared is a blank project, would you mind adding me as a collaborator? That will allow me to run it locally and test a few more things.<br>my email: rzambroni@somniosoftware.com

**Comment by stny-0518** [comment]
Understood.
I just added it to the collaboration.

Thank you

**Comment by Alezanello** [comment]
Hello!

I downloaded the code from the test project you shared with Renzo and tried everything to replicate the issue, but I wasn't successful. Could it be something on your phone that shows possible writings in Japanese?

[Screen_Recording_20240731_174226.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fbe240d4-6217-47bb-b0c4-16a0e83bc332/d465ed71-845b-467d-88ae-6720f1ba1da2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYmUyNDBkNC02MjE3LTQ3YmItYjBjNC0xNmEwZTgzYmMzMzIvZDQ2NWVkNzEtODQ1Yi00NjdkLTg4YWUtNjcyMGYxYmExZGEyIiwiaWF0IjoxNzIyNDU4Nzc0LCJleHAiOjMzMjkzMDE4Nzc0fQ.6MYvJSsDbrtbZRkqwhkM1Y3BlGQc5vOfXLNUITVUVcc)

Best regards,<br>Azanello

**Comment by stny-0518** [comment]
Hello Alezanello
I don't think it's the phone that's causing this.
Because when I tried it on a different employee's phone, sometimes the characters were doubled, or the input cursor was shifted even though the characters weren't doubled.

■Video of other employees in action
IOS
safari

https://github.com/user-attachments/assets/f88d1ed0-dedf-497a-8093-712bde031dc3


I also recently discovered that if you type without a paragraph or character in the TextField, the character will be doubled or the input cursor will be shifted, but if you put a paragraph first and then type from where there is already a paragraph, you can type normally.


https://github.com/user-attachments/assets/7d1342fc-d216-4124-9bce-286ebfcef59b

**Comment by Alezanello** [comment]
Hello,

I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

Best regards,<br>Azanello

**Comment by stny-0518** [comment]
Hello Alezanello

I checked the following versions and it's not fixed.

FlutterFlow v4.1.81+ released August 7, 2024
Flutter version is 3.22.2

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
