### ISSUE TITLE
MediaDisplay Widget - Cannot set uploaded file as current variable

### ISSUE THREAD

**Issue by abhibalani** [FlutterFlow/flutterflow-issues#3501]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a create social media page where I am allowing user to upload picture or video in their post and I am showing the preview image/video in the media display widget. 
But I cannot set the current value of MediaDisplay from the uploaded local file. 

### Expected Behavior

I should be able to set the current value of MediaDisplay from the uploaded local file just like we can do in Image widget. 

### Steps to Reproduce

1. Create new page
2. add a button for upload media
3. add action for upload media (image or video) on that button
4. create a MediaDisplay widget
5. In the media path for media display widget, try to set the uploaded local file

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9VoD0sQzN+aJc0sNobbxAjIoDoPJkUaff7TxFocMDgTGxbKEWLhmEGzN6PiYfAU+4FNQSYQaJd/pFiWwGUUli/aoSpEbuSSHcmO+9bG3KC36eFmRJ+Pvp0V1Ig1zuIJezJaBXfK7n6Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/cc7b31d8-6ef3-4129-a2e4-8f358a86359a)

### Environment

```markdown
- FlutterFlow version: 4.1.78+
- Platform: Desktop
- Browser name and version: Chrome 126.0.6478.185
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment]
Thanks! I was able to replicate the issue. I'll send it to ENG so they can work on this

**Comment by Leopoldorj** [comment]
I'm experiencing the exact same issue, there is no way I can upload a photo from the app to a collection, no matter the way I try. It will always come yo the: Current variable is not valid. message
![image](https://github.com/user-attachments/assets/21023fca-dbf2-424b-8e92-76c6291b9f0a)

**Comment by abhibalani** [comment]
@msusviela It has been 3 weeks. What is the expected TAT from your side for major breaking issues bug fixes?

**Comment by Leopoldorj** [comment]
It was great! The response was fast and the fix worked amazing!

Leopoldo Rodriguez-Jurado

CEO

Orion Agriculture
630170866
***@***.***
orionagriculture.com
[image: facebook] <https://www.facebook.com/orionagriculture>
[image: linkedin]
<https://www.linkedin.com/in/leopoldo-rodriguez-jurado-queipo-de-llano-16ba9547/>
[image: instagram] <https://www.instagram.com/orion_agriculture/?hl=es>

**Comment by abhibalani** [comment]
@Leopoldorj WHAT?

**Comment by victoriahuang1** [comment]
@abhibalani This is the expected behavior. Please see in your screenshots, where the `MediaDisplay` is asking for a _path_. An uploaded file does not have a path -- it is only bytes. Paths and bytes are different types, and cannot be used interchangeably.

We can put this down as a feature request, but we will not address it as a bug.

**Comment by Leopoldorj** [comment]
Hi Victoria, you're sending this to me as well! I don't think this is
supposed to go for me :)

Leopoldo Rodriguez-Jurado

CEO

Orion Agriculture
630170866
***@***.***
orionagriculture.com
[image: facebook] <https://www.facebook.com/orionagriculture>
[image: linkedin]
<https://www.linkedin.com/in/leopoldo-rodriguez-jurado-queipo-de-llano-16ba9547/>
[image: instagram] <https://www.instagram.com/orion_agriculture/?hl=es>
