### ISSUE TITLE
401 Error: API keys are not supported by this API.

### ISSUE THREAD

**Issue by Benediktherlt** [FlutterFlow/flutterflow-issues#3502]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I’m experiencing a common issue where, after adding the “Create Account” action in FlutterFlow, and then creating a new user on the login page, no user document is created in the user collection, and there’s no navigation to the next page. However, in my case, I encounter an unusual error message that I haven’t seen in the FlutterFlow community or on GitHub before

**Problem:**

- Error Message: “API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials 
   that assert a principal.”

- Details: It appears that the client-server communication is failing.

 **Steps Taken So Far:**

1. I’ve already posted about this issue in another community post here: [Community Post]
(https://community.flutterflow.io/ask-the-community/post/authentication-problems-no-site-navigation-no-user-document-written--roRT7khZZwxddn9).

2. Upon further investigation, I discovered that the 401 error message is the root cause, indicating an authentication issue between my FlutterFlow app and Firebase.

As you can see from my other community post, I’ve already done everything I can think of to fix the problem, but unfortunately it still does not work properly.

There is also this cross-origin error message shown in Firebase -> Authentication. I don’t know whether this could be related to my issue.

At this point, I have the feeling that something is wrong with my Google account, as I can no longer log in to Edge with my current FlutterFlow credentials, but only in Chrome. It’s really strange.

### Expected Behavior

The “Create Account” action should create a user document in the user collection and navigate to the next page without any errors.

### Steps to Reproduce

1.	Create a new page.
2.	Add the “Create Account” action.
3.	Attempt to create a new user on the login page in FF test mode.
4.	Observe the 401 error message and lack of navigation to the next page.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gzPHlwIt1rs9H+Kr9bcJR/ToXQzs4a5IRiu1EbxQ1GO/yOqd3ds/8SE1BXcyBagtEeGeGmn0y+KDFvdnhEcICFxSseYNe1LtydgzyeEe6R5iRPpGKS2t8M+lmBXac38OCmA9SANpidGw53F77JtyWZC3YJoTLDW4vFub/OdvInHyDHCXjLCJrwmNecCfn

### Visual documentation

![error_message](https://github.com/user-attachments/assets/ec753e27-407b-40db-bb4a-45f95a91f698)
![firebase_warning](https://github.com/user-attachments/assets/b107ba35-ee10-4d26-9df7-e52d9e89d40e)

### Environment

```markdown
- FlutterFlow version: latest 
- Platform: MacOs/Windows (tried on both)
- Browser name and version: Arc Browser on MacOs(latest), native Chrome Browser on Windows (latest)
```

**Comment by paulperez-dev** [comment]
Hi @Benediktherlt! I was able to run your project and create a new account. Did you fix the issue? 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7ecc1a5b-b7fb-4c05-a1ef-b41837836117/b65c77c1-00d7-493d-be6a-58421231b119?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZWNjMWE1Yi1iN2ZiLTRjMDUtYTFlZi1iNDE4Mzc4MzYxMTcvYjY1Yzc3YzEtMDBkNy00OTNkLWJlNmEtNTg0MjEyMzFiMTE5IiwiaWF0IjoxNzIyMzA4ODAyLCJleHAiOjMzMjkyODY4ODAyfQ.dL5HmtzdG8FeGFaz0UaspzcbmyGtj0O-kBDAKo3XnZk " alt="image.png" width="552" height="838" />

**Comment by Benediktherlt** [comment]
@paulperez-dev yes, i was able to fix the issue. You can mark this as resolved.

**Comment by msusviela** [comment]
Thanks for the update @Benedikthelt. I'll close the issue since you could solve it. Have a great day!
