### ISSUE TITLE
Default Error image fails to load

### ISSUE THREAD

**Issue by charliewaller7** [FlutterFlow/flutterflow-issues#3503]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On my app, I use image URLS from my external database. When these images return non 200 status codes, I expect the default error image set in in FlutterFlow to be displayed. However, when making a request for this asset in test mode, I can only see the [object Event] error.

I can see from the network requests in test mode that the request to .../appspot.com/error_image.png is made and returns a 200 response, however the contents are empty.

I have also validated that the media asset 'error_image.png' exists, by setting another image on the site to that asset directly.

### Expected Behavior

I expect that when image requests return non-200 status codes, the default error_image.png asset is used instead.

### Steps to Reproduce

- Upload an image to the Media Assets called 'error_image.png'
- Go to settings > App Assets and select the uploaded image as the default Error Image
- Create a page with an image widget
- Set the image type to Network, and use an invalid url, e.g. 'https://www.google.com/invalidurl.png'
- Select Show Error Image on Failure

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sz8r13It1xPVY1872afp7/WIsJnJ+U400lsJAEBEbfZPmB+wLXOn9alZVXeG+dkFfPmGkoHky+anTm9z1Du5fNTiCR6pAz4d2EjrgWTquRIy1O8yRPXR+GshXN2qh4KanuyJ5IulqSFJm3WGEfNmUYAztJr7JO1QvHeaLKpPXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

![Screenshot 2024-07-29 at 10 20 36](https://github.com/user-attachments/assets/4487244e-a018-48d6-8497-ee943e29c926)

### Environment

```markdown
- FlutterFlow version:  v4.1.78+
- Platform: MacOS Desktop and Web
- Browser name and version: Brave Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (x86_64) and Chrome 126.0.6478.183
- Operating system and version affected: macOS Ventura Version 13.6.7 (22G720)
```

**Comment by rzambroni** [comment]
Hi @charliewaller7, thanks for the report. I was able to confirm the issue you are describing, will send it over to the team so they can take a look.

**Comment by charliewaller7** [comment]
Hi @rzambroni  - Is there any update on this issue?

**Comment by sgardoll** [comment]
I've had the same issue @charliewaller7 - thanks for following up
