### ISSUE TITLE
Action Editor. When Copying & Pasting an Action with references to an API Response all nesting response references break

### ISSUE THREAD

**Issue by jdspeyer** [FlutterFlow/flutterflow-issues#3506]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Was working on a small project and noticed a really odd behavior. I essentially have an API call action block that I want to wrap in a condition (specifically I want the API call to be in the false flow. However, when I go to copy and paste the action into the false flow, all internal logic of the API Call action breaks (see video). It is essentially delinking the references I had and I have to go in and redo those references again. I attached a video that explains this in full detail.

### Expected Behavior

When I copy and paste an API action block (or any action block for that matter) I would assume that all functionality would be maintained from copy to paste.

### Steps to Reproduce

1. Setup an API of some sort that you can reference from the action editor.
2. Create an API Action call block (streaming) and add an onMessage, onError, or onClose action response chain.
3. Within this chain, add a block that references some field within the JSON generated by the API (Action Parameter).
4. Close out, and then copy and paste the API Action block.
5. Go back inside the onMessage, onError, or onClose response chain.
6. The reference you made to the JSON will now be errored and say that it does not exist and you'll have to relink it to the exact same thing again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMj1wItPmNtD7qryb8dB/Cg4Q346a5IKscp/bxIgGIDzPOw+ZPXsYVhuQurgYGxEMUSmmlwdzM7riuHtOPQEJUyCRo85zs0NFgLvZGeXa5OBCbmOYkZfM+5mGlPFyrWCkxBQJutYSHhm32b7e+m9YALXGO/wImdISq/LZO4=

### Visual documentation

https://community.flutterflow.io/ask-the-community/post/copying-api-action-blocks-breaks-all-json-variable-references-inside-it-dHAi7cOrrDcV02m?highlight=PeYxg1R29iJqZyr

There is a video attached to this Flutter Flow Community post.

### Environment

```markdown
- FlutterFlow version: v4.1.77 released July 26, 2024 (Flutter version is 3.22.2)
- Platform: Desktop
- Browser name and version: N/A (Desktop)
- Operating system and version affected: MacOS 14.5 (23F79)
```

**Comment by abhibalani** [comment]
+1

**Comment by msusviela** [comment]
Thanks! I was able to replicate the issue. I'll mark as a duplicate since the same issue of data loss has been reported here:<br><br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3493](https://github.com/FlutterFlow/flutterflow-issues/issues/3493)

I internally added this issue to that one so the ENG team knows this is also a case.

**Comment by abhibalani** [comment]
> Thanks! I was able to replicate the issue. I'll mark as a duplicate since the same issue of data loss has been reported here:#3493
> 
> I internally added this issue to that one so the ENG team knows this is also a case.

That's not the same issue.,
