### ISSUE TITLE
Google Sign in Not Working

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#3508]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Popup Doesn't show the account to Select the google profile which shall be used to logged in and when checking details either showing empty values or previous logged in user values. The Pop up only show the accounts list only for the first time i also have tried clearing browser cache but didn't worked
<img width="412" alt="Screenshot 2024-07-29 at 23 53 38" src="https://github.com/user-attachments/assets/d67171f7-4493-43f0-9fe2-b634656db914">
<img width="1002" alt="Screenshot 2024-07-29 at 23 53 47" src="https://github.com/user-attachments/assets/f51cb775-9087-4941-b721-dc90ac857a23">

### Expected Behavior

The Popup should show the account to loggin and the auth user email, firstName,lastName should be updated Accordingly

### Steps to Reproduce

Just take a action to Login using google

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4eiMjfsIh2rscA0a6Jd/panjwRQ0x6RY0vjuwacAw0IYOvB7McY+j+TGZuOLDid2xiPFmWgm0dzMLRvfztDsIFCByJb6JnzodpEDzMID65MpSgC5bpdkZCMJlmC26hzpuZoiRQJu1iSloRwGGuIOuATT/bNYC3IVUzFuSYMrz4pFarHhzeGn0Jg1ZSfCvr

### Visual documentation

![Uploading Screenshot 2024-07-29 at 23.53.47.png…]()

### Environment

```markdown
- FlutterFlow version: v4.1.78
- Platform: MAC OS
- Browser name and version: CHROME
- Operating system and version affected: ALL
```

**Comment by Alezanello** [comment]
Hello!

The logout action before the login is not necessary because when Firebase Auth logs in with a current session, it automatically drops the older user information to access the new one. Try removing the logout action and let me know if it works.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
