### ISSUE TITLE
Close Branch Button missing

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#3510]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no close branch button in the latest version of the application.

This is happening for all editors and owners.

### Expected Behavior

Per documentation, there should be a close branch button in the branch dialog when on that branch.

As the owner of the workspace I should be able to close any opened branch.

https://docs.flutterflow.io/getting-started/ui-builder/tool-bar/branching

Step 9:

![image](https://github.com/user-attachments/assets/e3c5b725-ffd7-4107-8e21-57aa2863d72f)

### Steps to Reproduce

1. Create a new branch, or switch to an existing branch
2. Open the branch dialog
3. See missing close button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zvLqw8tIms980Lv9bvZVtCQjN2YEaoM/0Np7aCosfZT2BLMcec/RVERCQu2iTGw3MGaahWoW0vzTvfDmUPEDFwieRb5AzblyeAmXfDimMbqSFJWgeXJ8Ep9MBXKF1sKz3RMlJtViSHtg60+qF9nIEj7sQeL1Clc4Dq/LZO4=

### Visual documentation

I am the owner

![image](https://github.com/user-attachments/assets/8c923bf0-d6a5-45ae-89da-1f7280813249)

No close branch button:

![image](https://github.com/user-attachments/assets/6c60f753-149d-4b61-823f-a2d6a1f5ae90)

### Environment

```markdown
- FlutterFlow version: 4.1.78+
- Platform: All Platforms
- Browser name and version: Chrome/Edge
- Operating system and version affected:  All Windows/MacOS/Linux
```

### Additional Information

Can't clean up old branches.

**Comment by rzambroni** [comment]
Hey @jonl-percsolutions-com, thanks for the report.

I think the[ branching documentation](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar/branching) is not updated with the latest changes that the team has been doing to the branching feature in FF. 

The close branch feature is now under the following menu:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a3e4f43b-c6c4-4593-a732-64700b4842b2/a366d6c4-f298-47bd-914e-d7bcfcb9267b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hM2U0ZjQzYi1jNmM0LTQ1OTMtYTczMi02NDcwMGI0ODQyYjIvYTM2NmQ2YzQtZjI5OC00N2JkLTkxNGUtZDdiY2ZjYjkyNjdiIiwiaWF0IjoxNzIyMzEyMTI3LCJleHAiOjMzMjkyODcyMTI3fQ.HJWFM4x86UEOmfGRfr_nGSrUniXjG4KnMQCjClqerJ0 " alt="image.png" width="539" height="404" />

I'll make sure to submit a request so the documentation is adjusted with the latest changes.

Sorry about the confusion and thanks again.

**Comment by jonl-percsolutions-com** [comment]
@rzambroni I swear that the close button was not under that menu either yesterday. With todays update to 4.1.79+, I am now seeing the close button in the pictured location.

**Comment by rzambroni** [comment]
I'm glad that you are now able to see it. 

I am closing this issue. 

Thanks.

**Comment by jonl-percsolutions-com** [comment]
> I'm glad that you are now able to see it.
> 
> I am closing this issue.
> 
> Thanks.

Are ya'll going to update the documentation, or continue to leave it stale?

Also, seeing it doesn't matter much at this point because the whole merging process appears to be broken : https://github.com/FlutterFlow/flutterflow-issues/issues/3177

**Comment by rzambroni** [comment]
Yes, i submitted a request to update the documentation. It will be updated as soon as our technical writters have a chance. 

The merge issue you are mentioning is already assigned to an engineer to be fixed. 

Thanks.
