### ISSUE TITLE
Missing require auth on page routes available on previouse version

### ISSUE THREAD

**Issue by Sudarshan519** [FlutterFlow/flutterflow-issues#3511]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Page requesting auth when not authentication set,
Unable to navigate to pages after removing authentication project

### Expected Behavior

Navigation should work. There is no option for single page to add authentication and cannot disable which are previously added

### Steps to Reproduce

 
https://community.flutterflow.io/authentication/post/acction-requieres-autherntification-to-be-enabled-for-the-project-8Medv7eTLrYPbKR

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KhsmAx41Pxd9Y15SJcvpagj8sHDMnargsltZTYxQgIrbuG7l/S8+kfhNuXbC0YwlYIWH9kmAJ+dXemvPpCvc3NQ6CfNlmz6hiWwndVka5MsmDC8yaS25/Df9QCnGP3MOVuRFAPtNtZVoT3GaIItm9Vg7fK4T3NUUCQ+SYB5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://community.flutterflow.io/authentication/post/acction-requieres-autherntification-to-be-enabled-for-the-project-8Medv7eTLrYPbKR

### Environment

```markdown
- FlutterFlow version: v4.1.76
- Platform: ALL
- Browser name and version: ALL
- Operating system and version affected: ALL
```

### Additional Information

Issue with basic navigation

**Comment by Alezanello** [comment]
Hello!

I just checked your project, but it seems there isn't any page asking for authentication. Which page specifically is asking you for this?

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
