### ISSUE TITLE
Container doesn't adapt to the minimum button height

### ISSUE THREAD

**Issue by Zaaap180** [FlutterFlow/flutterflow-issues#3512]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have buttons inside containers so the buttons can have shadows without blur. The style is similar to the Duolingo buttons.
I use the containers because buttons have elevation but not a shadow I can control.
It works fine for big buttons but not for the small ones.

### Expected Behavior

The container should adapt the height to the inside button so the shadow looks like part of the button and it escalates when the user has a big text size in their device.

### Steps to Reproduce

1. Create a page
2. Add a column to the page
3. Add a container with neither weight nor height and elevation 0, shadow Offset X: 2.0, Offset Y: 2.0
4. Add a button inside the container with neither weight nor height, and elevation 0, Border Width: 2.0, Button Padding 16.0, 8.0, 16.0, 8.0
5. I had to increase the vertical Button Padding to 14.0 so it the shadow is not smaller than the button, but it's not the look and feel I want.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slc/qw4Z2obgA+KXtbcJR/Tg7G0M1RJEkscpCbw4bIYj2P4lzY876PlVWZ/2+YHNUJU6cp14f0cLTvuLtLPpcByesQIh4+JFxVTzjTlqjVciTF7uCdkdTLJlMJhGD18PYiCZACM9vS14M12C6G9m/Xj7UQ4P7Imo8Sq/LZO4=

### Visual documentation

![bug](https://github.com/user-attachments/assets/1d7bab0b-1926-4d89-ae84-0d17808dc7e0)

### Environment

```markdown
- FlutterFlow version: 4.1.77
- Platform: Mac
- Browser name and version: Mac App
- Operating system and version affected: macOS Sonoma 14.5
```

### Additional Information

I had to change the look and feel of the small buttons on my dialogs.
It would be great to have the containers issue solved, and it would be even better to be able to add shadows to the buttons so I can even remove the shadow in the press state.

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue; it seems to be working fine on my end. I'll share the public project link for you to check and see if I missed anything.

Here is the link: [QA-1585 Project](https://app.flutterflow.io/project/qa-1585-8xvx2r)

Best regards,<br>Azanello

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ac523ced-1f52-454e-8b56-c260dca2e1d7/354c5bd6-b67a-438a-ad81-be4953f48652?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYzUyM2NlZC0xZjUyLTQ1NGUtOGI1Ni1jMjYwZGNhMmUxZDcvMzU0YzViZDYtYjY3YS00MzhhLWFkODEtYmU0OTUzZjQ4NjUyIiwiaWF0IjoxNzIyMzQzNjk1LCJleHAiOjMzMjkyOTAzNjk1fQ.S2VhRRXxB9L8NYx7q0AQkRoUShysqcAnKLyRS4sPDtA " alt="image.png" width="874" height="489" />

**Comment by Zaaap180** [comment]
Thanks a lot, Azanello.
I happened to me on Friday. I was waiting some time before trying again, but it may have been solved in today’s release.

I really appreciate you were able to test it so soon

**Comment by Zaaap180** [comment]
Hi, Azanello.

I’m afraid it fails. Find attached how your project looks when running local on iPhone.
Sorry I didn’t mention that I see the button correctly at Flutterflow but not on local run or when deploying.

I also tried again in my project and I keep getting the same result when the Button Padding height is 8.0 and the weight is 16.0

BR
Luis



￼

**Comment by Zaaap180** [comment]
Hello.
Could you check my feedback? I don’t know if you are considering this bug or if there’s any other option to solve it

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response. I'll check this directly on my phone to observe the behavior.

**Comment by Zaaap180** [comment]
Hi
I received this message, but I think the bug is not solved. I didn’t try again because I was waiting for an update from Alezanello.

**Comment by Alezanello** [comment]
Hi there!

I wanted to check in and see if this issue has been resolved with the latest updates?

**Comment by Zaaap180** [comment]
Hi, Alezanello.

I’m afraid I tried again and I got the same result in local run. It doesn’t look good.
I had just updated to the last version of Flutterflow before re-trying.

Sorry for the delay replying, we are releasing to production this week and it’s a crazy moment.

Regards,
Luis

**Comment by sbis04** [comment]
@Zaaap180 It seems like Flutter actually treats the button height differently on web and other platforms, but there a way to get around that. If you specify a specific button height then it should render it consistently on all platforms. Let me know if it solves the issue.

<img width="1007" alt="Screenshot 2024-10-03 at 12 29 04 PM" src="https://github.com/user-attachments/assets/f711502e-4536-48a9-9da4-bcf333ad80f3">

(BTW, I love the design language used in the app! 🙂)

**Comment by sbis04** [comment]
@Alezanello closing the issue for now since the above solution seems to be solving it, but feel free to reopen if it still doesn't work for you.

**Comment by Zaaap180** [comment]
Hi.
Sorry for not replying sooner. We made a workaround so we don’t use those buttons in any main screen. It affects our look and feel a bit, but It’s not a big deal anyway.

The proposal you made doesn’t work because it lacks accessibility. If we hardcore the button height, it doesn’t work for those who use a bigger custom font size on their devices.

Buttons are a bit of a pain in FlutterFlow (for Mac) because the preview is not related to how they look on mobile, but we can check it with local run anyway.
Fine with me about closing the issue. As you can see, it’s not my priority right now.

BTW, yesterday I found 2 bugs that you may want to consider. I’ve already solve the issue on my side:
- You have a title (text) inside a row, among other items inside a column. You right-click on the row and select Remove Widget. It allows you to do it, no warning, but it will fail on local run.
- You column inside a column, but with scroll checked as main scroll. Again, no warning but it will fail on local run.

Thank you for your attention.
Regards,
Luis
