### ISSUE TITLE
Cannot generate StickyHeader headers

### ISSUE THREAD

**Issue by FlamboD** [FlutterFlow/flutterflow-issues#3514]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the StickyHeader widget to generate children and using those children to set the headers, the build fails when I try to run test mode.

Looking at the generated code, the variable being used within the header has the wrong variable name.

```
Builder(
	builder: (context) {
                // The variable name generated here is ranStr
		final ranStr = List.generate(
			random_data.randomInteger(5, 10),
			(index) => random_data.randomString(
				  3,
				  8,
				  true,
				  true,
				  false,
				)).toList();

		return StickyHeader(
		  overlapHeaders: false,
		  header: Container(
			width: double.infinity,
			height: 50,
			decoration: BoxDecoration(
			  color: FlutterFlowTheme.of(context).primaryBackground,
			),
			alignment: AlignmentDirectional(-1, 0),
			child: Align(
			  alignment: AlignmentDirectional(-1, 0),
			  child: Padding(
				padding:
					EdgeInsetsDirectional.fromSTEB(16, 0, 0, 0),
				child: Text(
				  ranStrItem, // The variable used here is ranStrItem
				  style: FlutterFlowTheme.of(context)
					  .titleLarge
					  .override(
						fontFamily: 'Outfit',
						letterSpacing: 0,
					  ),
				),
			  ),
			),
		  ),
...
```

Here is the settings I used to generate the children
![image](https://github.com/user-attachments/assets/a227a979-5d3a-427d-8548-1b34f44476e5)

### Expected Behavior

The StickyHeader should generate children using the data provided, and test mode should be able to run afterwards.

### Steps to Reproduce

1) Create a new page
2) Add a Scrollable Column
3) Add a Sticky Header within the column
4) Set the sticky header to generate children from a list of strings (generating children using any list causes the same problem)
5) Set the heading of the sticky header to the child generated
6) Click run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gos8D1br1YMZqhQIgQ0QnU7gnlO1ucx40GLbsBJoUdc+kT0NKT8CqfwhAGFCj/T4C+vyOkeOSJPknEzSec4hS0JVAbQKUTlG7WpiIPLu8Yn97J+VhfEDG4Z2joglQWfF1LUIt3GC1Nq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/a227a979-5d3a-427d-8548-1b34f44476e5)
![image](https://github.com/user-attachments/assets/470dd0b0-a9ba-4e9c-9d46-9e2073cc923a)

### Environment

```markdown
- FlutterFlow version: v4.1.7.8+
- Platform: Web
- Browser name and version: Chrome Version 127.0.6533.73 (Official Build) (64-bit)
- Operating system and version affected: Windows 7
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue; it seems to be working fine on my end. I'll share the public project link for you to check and see if I missed anything.

Here is the link: [QA-1587 Project](https://app.flutterflow.io/project/qa-1587-9n1nh5)

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
