### ISSUE TITLE
"! Is On-screen Keyboard visible" not working

### ISSUE THREAD

**Issue by GavinRF** [FlutterFlow/flutterflow-issues#3519]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

! Is On-screen Keyboard visible is not working on certain pages. When any text field on the page has focus the element that should be hidden is still visible.

This is a revival of bug #2864 which was closed
https://github.com/FlutterFlow/flutterflow-issues/issues/2864 

I have tried many fixes for this and nothing seems to reset it. I tried
- wrapping the component in a container and making that the conditionally visible object
- duplicating the page and rerouting the navigation
- wrapping the text elements in containers
- changing the text input theme style (unset to a themed widget)
- changing the file structure
- copying everything I did on the pages that do work
- removing the on-focus event on the inputs
- and others...

### Expected Behavior

Hide the element when on-screen keyboard is visible. 

### Steps to Reproduce

Hard to determine because the issue appeared at an unknown point and no amount of fiddling has made any noticeable change (I spent two days trying)

I built a blank project to reproduce but was unsuccessful. Linked anyway.
https://keyboard-viz-u8akoi.flutterflow.app/

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fk876y5NPm+Fc1pD2de9VhmEUJnIkU400lu16EEo1F5vqEZl3Os6lSExJYs+WTAk7eVqZpH4KzNLZkc7lV8FcAxSAf49q3bpbWjyWTlmQaK60PpaoZEZDIJhMJmrH4LWrnwx9FMpoSiUH3VytN9mRRXXbJJjYOEUzMPqYMqzVnnC8LQ7jEiR74CdecCfn

### Visual documentation

<img width="941" alt="Screenshot 2024-07-30 at 11 27 42 PM" src="https://github.com/user-attachments/assets/2f522dad-9120-4255-b0f2-afb4bffa40d2">
![Screenshot_20240729_141400_Chrome](https://github.com/user-attachments/assets/87807ca6-aedf-4c28-b485-7831bb8bcaaa)
![Screenshot_20240730_222851_Chrome](https://github.com/user-attachments/assets/53f41829-f65a-4b6d-a4d4-bb5c28c03f69)

### Environment

```markdown
- FlutterFlow version: 4.1.79+
- Platform: Web, Phone
- Browser name and version: Firefox 128.0.3 and Chrome 127.0.6533.64
- Operating system and version affected: Android 14
```

### Additional Information

Sadly, it makes for such a poor user experience that I cannot launch my app.

**Comment by Alezanello** [comment]
Hello!

I just checked the link to the new project from my device, and as you said, it's working fine on my side. This GitHub Issue Tracker is mainly for bugs that can be replicated from a new blank project. Since both new blank projects (the one from the other issue you shared) and this one are not replicating the bug, it must be a project-specific issue. In this case, it would be better to contact support directly via the in-app chat or at support@flutterflow.io, as they have more advanced tools to help you.

Best regards,<br>Azanello

**Comment by GavinRF** [comment]
Sounds good.
