### ISSUE TITLE
Update Local State does not rebuild any page.

### ISSUE THREAD

**Issue by irfan-ahmed-1982** [FlutterFlow/flutterflow-issues#352]
## Expected behavior (required)

I have an action attached to image to upload the image to supabase from custom API as FlutterFlow does not support Supabse authentication yet. It updates the local state with the Image URL (Public URL), but after uploading the current page has to be updated with URL in a text field instead it does not rebuild at all.

## Current behavior (required)
The current page does not rebuild even after I select the rebuild all pages or rebuild current page. I have to navigate to previous page and come back to the current page again to see the updated URL in the text field.

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1. Add a button and attach an action to it.
2. on clicked action upload media to API
3. Use any API backend (Supabase preferred) 
4. Update Local state with any name and String variable select rebuild current page
5. Add the Text field and set the initial value from local state variable.
6. Hit Run and observe that the text field never change its value
7. Use back button and navigate to previous page
8. navigate again to that page where you have the text field with local state variable
9. Notice the text field displays the correct values.

### Bug Report Code (required, generate from Widget Tree)
IT8Cls/l5Yx2sdtJ14SJd8BvoDs5KWk7apZNm8JAEBAdGL6vPe0Xe+D8R1tBY7TidHw7JWKJnVgV+MrTufz1JcI4Bw6VbdV7wbpMUwGVIWe5UJO3PYeROUdRO9tYBX6X3J6Zux1THLd2V1Zmw2CHcq3qNleeY8aSfxBlZ7vfcPo=

## Context (required)
I need it to update the listing with the uploaded image URL. Please Note the supabase image upload will not work for me to grab the uploaded image URL because I need the storage policies not to be public.

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/118018023/212470425-296e9a50-640f-4548-9710-547f000de884.png)

## Your environment

* Version of FlutterFlow used: 3.3.4 (13 January 2023)
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Google Chrome
* Operating system and version (desktop or mobile): Windows 11

**Comment by bulgariamitko** [comment]
Can you share your actions so we can see how you set up your actions?   
Also try to use the rebuild all pages option.

**Comment by irfan-ahmed-1982** [comment]
Please find as requested:

![image](https://user-images.githubusercontent.com/118018023/212736699-a8049aca-d891-4ab1-b3dd-338b6017fbba.png)


**Text Field in the bottom called File name is updated from the local state please see below:**
![image](https://user-images.githubusercontent.com/118018023/212737689-e15cb66f-beb4-4087-96fd-b64cba9032ef.png)


![image](https://user-images.githubusercontent.com/118018023/212736795-f10c851b-2dfd-42ff-8029-bd55e8ad43de.png)

![image](https://user-images.githubusercontent.com/118018023/212736895-ce162c33-6b73-4bc2-9a42-2092ef25bb78.png)

**Comment by bulgariamitko** [comment]
I can't reproduce this issue, but I will let the FF team try and reproduce it as well.

**Comment by aemelyanovff** [comment]
You can't update initial value of a text field once it's initialized at the moment.

I can't think of a workaround off the top of my head. I can only suggest asking advice on https://community.flutterflow.io/ or creating a feature request for updating text field initial value.
