### ISSUE TITLE
Apostrophe in App Display Name incorrect in info.plist for iOS

### ISSUE THREAD

**Issue by nvimalraj** [FlutterFlow/flutterflow-issues#3522]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the App's Display Name is set as App's Name, it is stored in info.plist under iOS foder as App\'s Name. And the installed App name in the iOS device shows it as App\'s Name instead of App's Name.

### Expected Behavior

The info.plist should have stored as App&apos;s Name (converting ' to &apos; ). 

### Steps to Reproduce

Create a new project
Set the App Display Name as "App's Name" 
Deploy to App Store Connect
Download from Test Flight
Installed App shows as "App\'s Name"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcnez8x5vuV55rXccPRHoGYhH3oLa5Ar0tpBaCgoF5jpD7MAdvWlbhZDUtCoY0FmO0SmmnkK0cGKiuLxNMYoByydbapJz7ltWhXveEyRQZOBEbm0PEF8M/xPIXLA4aSF3BR+PrZvcU5i3U6qBumXUj/vJZ+3IndISq/LZO4=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: v4.1.79+
- Platform: MacOS Desktop
- Browser name and version: Chrome 
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry, but I can't fully understand the issue. I don't see any difference between "App's Name" and "App's Name". Could you please provide more information or screenshots to clarify the issue?

Best regards,<br>Azanello

**Comment by nvimalraj** [comment]
With the apostrophe, the info.plist shows it as App\\’s Name instead of App’s Name

App (slash s) Name

**Comment by Alezanello** [comment]
Hello!

When it compiles, does it show correctly? I'm sorry, but I'm not fully understanding the issue or problem. Could you provide more context?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
