### ISSUE TITLE
Character Limit does not work if there is a condition or a variable.  

### ISSUE THREAD

**Issue by zein1016** [FlutterFlow/flutterflow-issues#3523]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Character Limit only works if you add  constant integer 

### Expected Behavior

It should work when there is a variable, for example a specific value based on screen width 

### Steps to Reproduce

Add a text widget 
Add a condition where the Character Limit changes based on screenwidth 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si8rq24p2rsNK+Kr+bsBB/WUsKWIlaLgssct/cxQcB4j4PIkAPOLRTxNvQtSzaH1YGlKkkkME0s7Sk/PqG/YoIUmtG5Rj/852ERPPYzuuV4uVBZeaXUcnGfxUGB2A0cKN2hB4PsBtWUYY7FyMBOyAaz2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="157" alt="Screenshot 2024-07-31 at 13 24 14" src="https://github.com/user-attachments/assets/e5ad1603-1f9d-460d-8473-b4792014860a">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

You are right, and thank you very much for bringing this to our attention. I was able to easily replicate the issue and will forward it to the engineering team for a fix!

Best regards,<br>Azanello
