### ISSUE TITLE
Error in Mobile Deployment (dependencies error) - youtube_player_iframe_web

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#3525]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, I have an error while building the app in mobile Deployment. It has the following error:

+ youtube_player_iframe 4.0.4 from git https://github.com/FlutterFlow/youtube_player_flutter.git at 4c9c39 in packages/youtube_player_iframe
+ youtube_player_iframe_web 2.0.2 (3.0.2 available)
Changed 212 dependencies!
99 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Analyzing dependencies

### Expected Behavior

Publish without problems

### Steps to Reproduce

1. Deploy to the app store

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMmBx89PsctJ0LXube9VvCYRKUA6U40WlsFuUQobfJTxG7l3WvfObhJUcN/gYH9EJFn8+XMX/Mrtic7hMvY5By+ZQNg7zpF2EzrjcFKnMrKvCa63b3BTN/FXChG9yrSnvhRDHMhfdXwA2jn7O+utf3XXGITyO2oZReaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="2240" alt="image" src="https://github.com/user-attachments/assets/aa3a5bbb-e7d6-4d95-acd2-215542d11cf6">

### Environment

```markdown
- FlutterFlow version: 4.1.79+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Chrome MacOS
```

**Comment by Alezanello** [comment]
Hello!

Could you please share with me which page or component in your project uses any YouTube player?

Best regards,<br>Azanello

**Comment by pstatile** [comment]
Hi! You can check the Page called 'Top8PostpartumPelvicFloorExercises'.

Now I could build OK, but if you are able to check the versions, better to
avoid future problems.
Thanks!
Pablo

**Comment by Alezanello** [comment]
Perfect! I created a new blank project with a YouTube player widget, and it built fine. I'm glad it worked on your side as well. I'll keep this issue open for a few days in case someone else experiences the same problem. If it happens again to you, please comment here immediately so we can investigate further.

Best regards,<br>Azanello

**Comment by pstatile** [comment]
Great Thanks!El 31 jul 2024, a la(s) 17:07, Alezanello ***@***.***> escribió:﻿
Perfect! I created a new blank project with a YouTube player widget, and it built fine. I'm glad it worked on your side as well. I'll keep this issue open for a few days in case someone else experiences the same problem. If it happens again to you, please comment here immediately so we can investigate further.
Best regards,Azanello

**Comment by pstatile** [comment]
Hi Alezanello,
I'm facing the same error (not always), saying this at the end of the stack
trace:

+ youtube_player_iframe_web 2.0.2 (3.0.2 available)

Could you check if the default dependencies doesnt have the latest version?
Thanks! Pablo

**Comment by Alezanello** [comment]
Hello,

I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

Best regards,<br>Azanello

**Comment by pstatile** [comment]
HI! It was not fixed, but it does not always happen... Can you check in
terms of dependencies (related to image of the original error) if FF uses
2.xxx or 3.xxx ? Maybe if it works, better to have the latest version
Thanks!

**Comment by pstatile** [comment]
Please have a look, check if the dependencies are fixed on an old version
or if they do use the latest version of the youtube player.
Thanks!

**Comment by Alezanello** [comment]
Hi there!

I wanted to check in and see if this issue has been resolved with the latest updates?

**Comment by pstatile** [comment]
Hi! I haven't experienced it again so far, so I hope it is definitely
resolved. Thanks!
Pablo

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
