### ISSUE TITLE
I can't save any change to my project  (I have been 15 days without being able to save anything from adding or deleting a form to adding an action)

### ISSUE THREAD

**Issue by fdelgadofocus** [FlutterFlow/flutterflow-issues#3526]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It doesnt let me save anthing on my project , any change I do to my project at the end it says NOT SYNCED

### Expected Behavior

Simply let me save any change to my project 
- Add or delete forms.
- Add or delete action inside forms.
-  Edit any component inside the forms.
- 

### Steps to Reproduce

1. Open the project
2.  try delete any form on the project
3. try adding any action inside any form

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kivLlvJROj7xY17X5be5KvCcRJUs4TLIFse0aRR4gIo/mELMQPvekV0NKT8vmdws/I06YmTkD+t7shePLDfA5NSicba5I0JVAaQzwfH6XRc23CqWCP3wnHcdVG2Kl08OVnQp5BMxqLE4E7GClNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

Please dont ask me again to do it I have another issue open with the same problem I Already posted more than 5 videos and no solution yet.
It is symply unacceptable that an issue caused for the IDE doesn't let me continue, I have been on the software development industry for more than 28 year and I had never had this kind of problems.

### Environment

```markdown
- FlutterFlow version: v4.1.79+
- Platform: WEB VERSION , WINDOWS , MAC (ALL OF THEM HAVE THE SAME PROBLEM)
- Browser name and version: EDGE, CHROME, SAFARI, FIREFOX, 
- Operating system and version affected: WINDOWS 11, MAC OS
```

### Additional Information

I need help since the problem is not being resolved neither addressed

**Comment by rzambroni** [comment]
Closing this ticket in favor of your original ticket: [https://github.com/FlutterFlow/flutterflow-issues/issues/3417](https://github.com/FlutterFlow/flutterflow-issues/issues/3417)

Will follow up there.

Thanks.
