### ISSUE TITLE
Query Filter banishes

### ISSUE THREAD

**Issue by Leopoldorj** [FlutterFlow/flutterflow-issues#3529]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am practicing creating a search bar. I added a button next a textfield and added an action to do query collection with two filters, the second filter repeatedly banishes out of the blue, so it reports the bug even though I set the value over and over again.

![image](https://github.com/user-attachments/assets/a427cefd-617f-477b-ac46-6f0dd8e16cdc)

### Expected Behavior

It should refresh the list bellow the button but it doesn't because it goes away (I've got it to work just once)

### Steps to Reproduce

1. Create new page
2. Add row with textfield and Iconbutton
3. Add a listview with some text and image
4. Add action to iconbutton > on tap > Backend/Database > Firestore > Query Collection (Usuarios) > Query Type: List of Documents > Filters OR > Filter 1: Collection field Name: (nombre) > Equal to > Value: TextField (buscar por nombre o mail) > Filter 2: Collection field Name: (mail) > Equal to > Value: TextField (buscar por nombre o mail)
5. Add Listvew Query colleciton Query Collection (Usuarios) > Query Type: List of Documents > Filters OR > Filter 1: Collection field Name: (nombre) > Equal to > Value: TextField (buscar por nombre o mail) > Filter 2: Collection field Name: (mail) > Equal to > Value: TextField (buscar por nombre o mail)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcn1z4V2pbxa1br+Ke9VryQWMjt/RYIZlcFESkggN5POD+x/fMnBN1dUOPbhTAlUIU6GoHwX/MrVv4TuFfo5GzmuQa071LhTExbxc3GuVYyOPK63b3dQI+JQCkuM5JizpSQkPtdZWkIh3V73Oum9Xh/dNYTUIlgFPea4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/926a1f6e-9378-4e03-b333-2d7069a26a06)

In the second image you can see that the value is empty, well, every time I click away of the app, it banishes, even for a screenshot.
![image](https://github.com/user-attachments/assets/3723ae9f-309a-4b70-8b0d-083319834cbd)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Desktop app
- Browser name and version: chrome 127.0.6533.73 
- Operating system and version affected: Windows 10 Home 22H2
```

**Comment by msusviela** [comment]
Thanks! I was able to replicate the issue. I'll send it to ENG so they can work on this

**Comment by isegal** [comment]
Having the same issue here. Any workarounds? This has halted one of our projects.

**Comment by isegal** [comment]
Additional bug report code from our project, if it's any help:

IT4ghcnfz5Fgobhc0bXuY+9amiE7KXp8aK00sd4bGA0dCJzuPLMQdvWlTEhVXb2rYGx+JkSmmkYxwezVheHfCMcqKUuAb6I61ZF9EDn/VTihQZOBBs2WbX98HZ5hCnXD4bbQsBB4GPB2c1oFw12MGeqQdDLYN7WxImdISq/LZO4=

**Comment by agreaves** [comment]
Hi @Leopoldorj and @isegal, apologies for this issue! That's super frustrating. We've managed to identify the issue and provide a fix, which is now deployed on web! (will be deployed to desktop in the next few days)

**Comment by Leopoldorj** [comment]
Thank you so so much!! For the time, the tools and the fix. There is
another issue with the chart widget, should I create another issue at
GitHub?

Again thank you so much for everything!

Leopoldo Rodriguez-Jurado

CEO

Orion Agriculture
630170866
***@***.\*\*\*
[orionagriculture.com](http://orionagriculture.com)
\[image: facebook\]
\[image: linkedin\]

\[image: instagram\]

**Comment by msusviela** [comment]
Hi @Leopoldorj. Sure, you can create another issue for that. Thanks!

**Comment by Leopoldorj** [comment]
Great! Thank you very much :)

Leopoldo Rodriguez-Jurado

CEO

Orion Agriculture
630170866
***@***.\*\*\*
[orionagriculture.com](http://orionagriculture.com)
\[image: facebook\]
\[image: linkedin\]

\[image: instagram\]
