### ISSUE TITLE
download button

### ISSUE THREAD

**Issue by achrafouni007** [FlutterFlow/flutterflow-issues#353]
hello , how i can make a "download pictures button" in flutterflow , it mean when user click on this button he can save picture from "project media / assets" to phone galery

**Comment by Pepino-GR** [comment]
Hi achrafouni007,

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by Pepino-GR** [comment]
This is the wrong place for asking HowTo questions. Please go to  https://community.flutterflow.io
