### ISSUE TITLE
The permission of "photo library" is not working 

### ISSUE THREAD

**Issue by nadeen-bsh** [FlutterFlow/flutterflow-issues#3531]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding the action of require permission of "Photo Library", It's Not Working.

Not Displaying when click on the button

here's my Rules of firebase storage.
![image](https://github.com/user-attachments/assets/0e100807-9210-4be0-bbf7-9ea924be1bc4)

and showing like that in Debugging.
![Screenshot 2024-07-30 153010](https://github.com/user-attachments/assets/5f792ed2-7115-4424-bb37-9b94b6e8628b)

### Expected Behavior

The Pop up of permission would Open but it's not work for this permission.
I have tried location and camera but it work fine.

### Steps to Reproduce

1- created button
2-  add the action
2- action of "request permission" of photo library
3-  try build and test on mobile or with APK on mobile 
4- It's not Responds acts like that the button has an action and no pop up opens
5- viewed the troubleshooting by f12 these errors are shown
![Screenshot 2024-07-30 153010](https://github.com/user-attachments/assets/42b32a1e-5fe3-48c2-9a87-89be689ae80e)
6- when viewing bugs for the other permissions like "location" theses bugs does not shown

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shvHlz4xgodtK0Lr+KflR/CkWOU9+R+dJscpCbw4bIYj2P4lzY876P1FtcNzjSlV+fVmMp141//+OvvDDLvc6PTedQIQ//7hiQwrybGOXMsyTF7WOP3NCTJlTGBWi0J6JphV4ALNiLlYY2lymOumiVjTdHufuIFQ4Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/fb43a8f2-50b2-4b37-aad7-feb1752cdeaa)
![Screenshot 2024-07-30 153010](https://github.com/user-attachments/assets/44d21947-028e-476d-b050-fdb39bdf93fe)
![image](https://github.com/user-attachments/assets/35462fe3-007b-4a86-ae5d-9b8377c958e2)

### Environment

```markdown
- FlutterFlow version: 4.1.79+
- Platform: web, Mobile "android"
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: windows 10
```

**Comment by msusviela** [comment]
Thanks Nadeen-bsh. I was able to replicate the issue.<br>Just one more question, is it working on iOS for you? I tried and the issue appeared only on Android to me. I want to confirm this so we can do a better follow up of the issue. Thanks!

**Comment by nadeen-bsh** [comment]
Hello,
I don't test it on iOS, Only tested on android

**Comment by nadeen-bsh** [comment]
I've tested on iOS but also not worked

**Comment by nadeen-bsh** [comment]
> Thanks Nadeen-bsh. I was able to replicate the issue.Just one more question, is it working on iOS for you? I tried and the issue appeared only on Android to me. I want to confirm this so we can do a better follow up of the issue. Thanks!

Is it Solved?

**Comment by msusviela** [comment]
Hi @nadeen-bsh. Our team is working on a fix.

**Comment by nadeen-bsh** [comment]
> Hi @nadeen-bsh. Our team is working on a fix.

Ok, Thank you Keep me updated please
