### ISSUE TITLE
Upload/Save Media does not match Permissions

### ISSUE THREAD

**Issue by bek2d** [FlutterFlow/flutterflow-issues#3532]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using https://docs.flutterflow.io/actions/actions/utilities/upload-data/upload-save-media to upload photo to the app, the widget Save/Upload media asks to choose a source to upload from Gallery or from Camera or from "Either Camera or Gallery" (meaning both)

The bug is: even if we choose Gallery, meaning Camera is not needed, in Flutterflow Permissions, Camera is mandatory

### Expected Behavior

Widget options should align with permissions. Thus if Camera is not used as media source, it should not make it mandatory.
So 3 cases:
Save/Upload media WHERE media source is Gallery → Only Gallery permission is mandatory
Save/Upload media WHERE media source is Camera → Only Camera permission is mandatory
Save/Upload media WHERE media source is "Either Camera or Gallery" →  Camera and Gallery permissions are mandatory

### Steps to Reproduce

1. Create new page and add a button
2. Add to button actions Save/Upload media
3. In media source drop down, change default "Either Camera or Gallery" to Gallery only
4. Open Setting and Navigate to Permissions
5. You can see that Camera access is mandatory eventhough media source is Gallery only

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lPHlw852j7xH15CBaPlVgmA5KU9/U78w18JBaCgoIYyuOpl/evWlXxFoXemoS39EOkSmmnoEwNLvjYTXFfleNRydGZhj+rhMTgGVTTm5QZOBDbWzdWpfEd9UGX615LS7hxUmCPtvL3NgwU+bfeqvYz7cJufIImdISq/LZO4=

### Visual documentation

![Снимок экрана (3)](https://github.com/user-attachments/assets/16a0637b-0b9c-4858-afb4-1d06422e2076)
![Снимок экрана (4)](https://github.com/user-attachments/assets/df4ba929-4b5f-4757-880a-f22c7486148d)
![Снимок экрана (5)](https://github.com/user-attachments/assets/63c03261-a280-4f11-9afd-423f07bed9d8)

### Environment

```markdown
- FlutterFlow version: v4.1.79+ released July 30, 2024
- Platform: Ios and Android
- Browser name and version: Chrome 127
- Operating system and version affected: Windows 10
```

### Additional Information

Because of this bug, after each code export, I have to manually edit Flutter code to remove unecessary Permissions request

**Comment by msusviela** [comment]
Hi @bek2d. This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible.

 Thanks for your feedback!
