### ISSUE TITLE
Firestore update allows to use inequality filters on multiple fields but Flutterflow block it

### ISSUE THREAD

**Issue by armanddebesse** [FlutterFlow/flutterflow-issues#3533]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I want to add multiple inequality filters on the backend query of my list view, I got this error : `You can only use <, <=, >, >=, !=, and not-in operators on one field per query.`  
Firebase can now handle this, since they released an update for this problem : https://www.youtube.com/watch?v=qMZ_q-iHqsU

### Expected Behavior

As firestore has been updated to support multi inequality filters, I expect flutterflow to stop blocking this behavior.  
The error `You can only use <, <=, >, >=, !=, and not-in operators on one field per query.` prevents me to use this usefull feature released by Firebase.

### Steps to Reproduce

1. Create a project with firestore as backend DB
2. Create a list view
3. Add a backend query on a list view with multiple inequality filters on different fields.
4. Click on "confirm"
5. You will get the error message `You can only use <, <=, >, >=, !=, and not-in operators on one field per query.`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi8mAw49OsdhE7aX6bu9WhiYsH1g3bIc0sNtuTQIdCYDuBIYiacz4RxdVZMyodGNhKEWLpDs0wNLUvdnDL8I7G02ZbqI5yZYNQxXvXTi/aoS0Cs+eWkdDM/phJ2HG0p+n3AhSNu9pWV4O6mb7Fum/TgLbQo/7Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/c1e2b721-cdb0-4b1c-b3b9-8874bc6579e7)

### Environment

```markdown
- FlutterFlow version: 4.1.79
- Platform: desktop / web
- Browser name and version: Chrome 127.0.6533.89
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

You are right, but this is more of an enhancement request than a bug. I'm going to pass it directly to the engineering team so they are aware of it and can determine a deadline for improvement. Thank you very much for bringing this to our attention!

Best regards,<br>Azanello

**Comment by armanddebesse** [comment]
Hello,
You are right it's not really a bug..
Thanks a lot for your answer and for all the work made by Flutter flow team !

Have a great week.
________________________________

**Comment by Alezanello** [comment]
No problem, and thank you for bringing this to our attention. I've already generated a ticket and added it to the engineering team's backlog. :)

Have a nice weekend!

Best regards,<br>Azanello

**Comment by AnkitaMalik22** [comment]
Hello @Alezanello !

**Comment by AnkitaMalik22** [comment]
Hello @Alezanello,

Do you have any updates on this? I'm currently facing the same issue.
Or is there any alternative approach we can try for now?

**Comment by npanagop** [comment]
This is issue is closed but the feature is not implemented. Are there any updates?

@AnkitaMalik22 The only workaround I found is to make a query with a single range filter and then add more filters in the Generate Dynamic Children tab of the ListView. Use the most "restrictive" filter in the query to reduce reads and cost.
