### ISSUE TITLE
Setting the "Testing" -> "Value Key" property on VideoPlayer widget causes build to fail

### ISSUE THREAD

**Issue by acb-bweaver** [FlutterFlow/flutterflow-issues#3534]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you set the Testing -> Value Key property on a VideoPlayer widget, the following error is reported when attempting to Run the project:
```
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
lib/pages/home_page/home_page_widget.dart:51:17:
Error: No named parameter with the name 'key'.
```

### Expected Behavior

Should build and run without error.

```
FlutterFlowVideoPlayer(
                key: ValueKey('ThisCausesDartError'), // this line causes a compilation error
```

### Steps to Reproduce

1. Create a new blank project
2. Put a VideoPlayer widget on the home page
4. Set the Testing -> Value Key property on the VideoPlayer widget to any non-empty value
5. Tap Run in upper right corner
6. Build will fail with the following error:

```
Error: No named parameter with the name 'key'.
                key: ValueKey('ThisCausesDartError'),
                ^^^
lib/flutter_flow/flutter_flow_video_player.dart:21:9:
Info: Found this candidate, but the arguments don't match.
  const FlutterFlowVideoPlayer({
        ^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
```

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xzcrl25NOj7xH1rr+LPlahSQUQ1x6RYIRmOwadxQ1G72qE+0MPM7+T3daZ+m5dGw3GGGJjj4KzNLZv/PLE/o3PQqub71q3bhQURXgXl2ueJiKBbuefnZREtFTf2q9556vogx9FM1aLkIR3HGuIt+RUnXbHo/4Om07Avj/WaDM+2iJK3nNDTtr3idecCfn

### Visual documentation

![image](https://github.com/user-attachments/assets/9fefee04-e85d-4ce2-89b3-286078fb1eec)

### Environment

```markdown
- FlutterFlow version: 4.1.78
- Platform: Web, MacOS Desktop
- Browser name and version: Microsoft Edge 27.0.2651.74, but does it in any browser
- Operating system and version affected: Mac OS Sonoma 14.5 Apple M1 Pro 16 GB
```

### Additional Information

Evaluating FlutterFlow for use in busines. Emitted code must support common testing tools, which means supporting semantic labeling and automated testing. Testing means we need specific ID value for every widget that appears in the app we create.

**Comment by msusviela** [comment]
Thanks @acb-bweaver. I was able to reproduce the issue. I'll send it to ENG so they can work on this!
