### ISSUE TITLE
Issue while deploying to (iOS) App Store with Meta SDK

### ISSUE THREAD

**Issue by AnirudhGoel** [FlutterFlow/flutterflow-issues#3539]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I followed the steps given in this tutorial - https://community.flutterflow.io/discussions/post/tutorial-add-meta-sdk-to-your-app---step-by-step-tutorial-2sNvqO3yavNJoqk?highlight=e97ORt3URpW0rwm

I'm facing the same issue that other people have also reported facing within the last month or so. The Play Store deployment works fine, I've tested it. While deploying for App Store, I receive the following error:

```
Failed Step: Flutter build ipa and automatic versioning

Found build number 76 from TestFlight version 2.3.1

Archiving green.spoon.app...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: QRK58NGDHT
Running pod install...                                              3.2s
Running Xcode build...                                          
Xcode archive done.                                         122.3s
Failed to build iOS app
Error (Xcode): Undefined symbols:

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Encountered error while archiving for device.


Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1
```

My first impression after seeing the error message was that this might be a versioning issue (cz when you deploy from a repository, FF starts depending on the version in the pubspec.yaml file). However, that does not seem to be the case. I branched the code from the `flutterflow` branch into another branch and deployed it a couple of times without changing the version number in it, it went fine. It was deployed without any errors while the release number was being updated automatically.

I also tried to deploy after updating the build.gradle file to sign in release mode (as the FF docs suggest) and that also works fine.

It is when we do the changes to include the Meta SDK we receive the above error.

### Expected Behavior

The deployment should proceed without any errors.

### Steps to Reproduce

1. Follow the steps given in this tutorial to add the Meta SDK - https://community.flutterflow.io/discussions/post/tutorial-add-meta-sdk-to-your-app---step-by-step-tutorial-2sNvqO3yavNJoqk?highlight=e97ORt3URpW0rwm
2. Using the "deploy via repository" option, deploy using a custom branch
3. You should receive the above error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlc/qx4V2rscA+KX+b8AwtGMRCUMdXOczitVEew4bCIj4E5l/YM/OVBNuXdSzaH52A1GZ8XEK+dLpkdnPNvUFEwyrfoRZ1qp9WBPPbGq6MrrQDJOSYnFRL+hXI0fD4LuNnhVNIvVZL3xl7U+mFeitbz6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1512" alt="Screenshot 2024-08-02 at 11 16 58 PM" src="https://github.com/user-attachments/assets/71a2214a-b7f6-4e2e-95a9-346306be5af5">
<img width="1512" alt="Screenshot 2024-08-02 at 11 17 10 PM" src="https://github.com/user-attachments/assets/6995ce01-54ff-4cab-96c1-dd7527e4300f">

### Environment

```markdown
- FlutterFlow version: v4.1.79+
- Platform: Web
- Browser name and version: Chrome 126.0.6478.127
- Operating system and version affected: macOS Sonoma 14.4.1
```

**Comment by Alezanello** [comment]
Hello!

I just checked your project but couldn't find anything related to the Meta SDK in your FlutterFlow project. Could you please specify where you added it?

Best regards,<br>Azanello

**Comment by AnirudhGoel** [comment]
Hello @Alezanello, the last 4 commits in the `main` branch are my custom changes commits - https://github.com/Cussert/CussertApp/commits/main/

All the Meta SDK changes are done in this one - https://github.com/Cussert/CussertApp/commit/77914810341e007a90a6cd3a81aef8375e5d8526

I’ve provided you with read access to the repo.

**Comment by Alezanello** [comment]
It seems you need to add `FBSDKCoreKit` to your Podfile so it can read the `Info.plist` additions of `FacebookAppId`, `FacebookClientToken`, and `FacebookDisplayName`.

Please try adding that to your Podfile and then deploy again.

**Comment by AnirudhGoel** [comment]
Hey @Alezanello, I added the line `pod 'FBSDKCoreKit', '~> 17.0.2'` to my Podfile and redeployed, but got the same error.
https://github.com/Cussert/CussertApp/commit/75d9e532f7c118495472fd8fa78adaa4a322be95
<img width="774" alt="image" src="https://github.com/user-attachments/assets/7eaef1ec-d8b5-4d3f-aa43-440b66f8df91">
<img width="773" alt="image" src="https://github.com/user-attachments/assets/6382c596-8d80-4256-8576-595a99038cca">

**Comment by AnirudhGoel** [comment]
Hello @Alezanello, can you please have a look? :)

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
