### ISSUE TITLE
Custom Font View text overflow

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#354]
## Expected behavior (required)

Show the titles of the uploaded font files.

## Current behavior (required)

The titles overflow into the dropdown, making it difficult to understand what it's saying.

## To Reproduce (required)

N/A

## Context (required)

It's hard to make out what it's saying. I had to go to each file and individually cut it so that it fits the size.

## Screenshots / recordings

<img width="1263" alt="Screenshot 2023-01-14 at 11 14 49 AM" src="https://user-images.githubusercontent.com/11810973/212492288-66ca5267-83c5-4e4c-8174-27b23cdc258b.png">

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
I have pushed a fix for this. Thanks for your keen eye.
