### ISSUE TITLE
Values in Action Flow editor not updating

### ISSUE THREAD

**Issue by ant-codez** [FlutterFlow/flutterflow-issues#3540]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Opening Action flow editor and setting a variable shows as updated. However after closing out of the action flow editor the bugs still appear in the project issues button. I am unable to make changes as they are not saving and I cannot run my application. After a minute or so the changes are reverted showing that no changes were made.

### Expected Behavior

After making a change in the action flow editor, it is expected to see changes saved and errors removed from the project issues button.

### Steps to Reproduce

1. Open Action Flow editor
2. Change a Variable in the action flow editor
3. Close out of Action flow editor
4. View Project issues tab to confirm changes have fixed bugs

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87huJVNrsda1rrtbe1WimMRNkd8TL07ttYbZxUjIuPtBJh/P87BXExuQu26TUNhHFeGgXEFwMLrj4T1F8cCNSqBb65hzLVIcTvzc3q8RKWaO6u8RUBBP51jfki53MKzuRQnBMVYL1493VOtevOvbDLtCZO/Zwh9f6PHaOI=

### Visual documentation

![bug](https://github.com/user-attachments/assets/b5a6f906-4e28-4625-b886-b5ebf6d9aad4)

### Environment

```markdown
- FlutterFlow version: v4.1.79+ released August 2, 2024
- Platform: Web / Windows / MacOS
- Browser name and version: Brave Browser Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 / MacOS Sonoma 14.4
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're facing this issue. After you make these changes, could you check if the "Syncing" or "Synced" message is displayed at the top-left corner? 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/176a0fa2-50d8-420b-b996-9e94b7e827c6/8bc5fc08-f499-4fcc-94ee-b6bd54a597e0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzZhMGZhMi01MGQ4LTQyMGItYjk5Ni05ZTk0YjdlODI3YzYvOGJjNWZjMDgtZjQ5OS00ZmNjLTk0ZWUtYjZiZDU0YTU5N2UwIiwiaWF0IjoxNzIyNjM2NTY3LCJleHAiOjMzMjkzMTk2NTY3fQ.vVKQoNzX3zjmqAo8tjn1-5cdl_oNnrK1LLvYklAVqBA " alt="image.png" width="241" height="140" />

<br><br>Have you tried pressing CTRL (CMD) + S after making some changes to save the project and see if the bug reports still show and if the changes are not saving as expected?

Best regards,<br>Azanello

**Comment by ant-codez** [comment]
No problem, things like this happen. The message displays "Synced" after making changes and pressing CRTL (CMD) + S after making a change. Seems to revert the change faster after saving, rather than taking a minute to revert the change on my end. 
![image](https://github.com/user-attachments/assets/e749929b-f4a1-4f14-97b6-87ccf55bd152)

**Comment by Alezanello** [comment]
I understand it's hard to capture this specific issue, but could you possibly record a video showing the behavior for the engineering team to review? I was able to replicate it once, but it's not happening anymore on my end.

**Comment by ant-codez** [comment]
Steps are the same as the GIF. I set each value that is giving an error to the "userProfile" page parameter. Then save using CMD + S and it doesn't appear to fix the error. Afterwards I close and reopen the application to see the changes reverted back to its previous state. The top left also has the word "Synced" as well.

https://github.com/user-attachments/assets/a23e6e5e-4e35-44c4-a3be-3ad8e100de45

**Comment by ant-codez** [comment]
Deleting and remaking the actions seems to have solved the issue 🤷

**Comment by agreaves** [comment]
Hi @ant-codez, apologies for this issue, that's super frustrating! I've managed to reproduce the issue and it should be fixed and deployed on web within the next day.

**Comment by agreaves** [comment]
Fix deployed on web!
