### ISSUE TITLE
Theme Style Unset not getting deleted

### ISSUE THREAD

**Issue by saurabhqaengineerfp** [FlutterFlow/flutterflow-issues#3541]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After applying theme style to a button, textfield or a container if I want to delete the theme style and I click on delete icon, it does nothing. I cannot delete theme style once it is applied.

### Expected Behavior

Once you click delete "theme style" icon, it should delete the applied theme style and revert back to original form.

### Steps to Reproduce

1. create a theme widget such as container or button or textfield.
2. create a blank page
3. add button or container or textfield
4. apply theme style to any of these
5. click delete icon in front of "widget styling"

expected result - theme styling should be deleted
actual result - theme styling is not getting deleted

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez8mA24lhn71K15PXK/lonQMwGkQ5a7sviu5+FBQaI+PnOpkUZc+kbkhtcuqHYEFYClKYqzsC08LWiuz+GMAnNRWsc7Y/+bhLUxDvTmKhMIyIPbW/PUZtM+VhIUCl1MOW2iNRJbFfLk4j1176Nuuub3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="941" alt="Screenshot 2024-08-02 at 22 45 34" src="https://github.com/user-attachments/assets/3594570b-40f6-4275-abcf-ab95bfbbcc5d">

### Environment

```markdown
- FlutterFlow version: web version
- Platform:mac
- Browser name and version:chrome 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected: macOS sonoma 14.4.1
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue on either the Mac or Web app. Where did you test it exactly? Could you share a video or GIF to help us understand the issue better?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6349141d-65f0-4d55-a110-e8a658d2fcab/08b15703-2264-4ec1-b782-0922b1788caa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MzQ5MTQxZC02NWYwLTRkNTUtYTExMC1lOGE2NThkMmZjYWIvMDhiMTU3MDMtMjI2NC00ZWMxLWI3ODItMDkyMmIxNzg4Y2FhIiwiaWF0IjoxNzIyNjM5NDI5LCJleHAiOjMzMjkzMTk5NDI5fQ.pSrDGx6dA5Ew4vBPA4An4D4xhbDWY9iUBS4CoH-1zKI " alt="theme style.gif" width="705" height="296" />

Best regards,<br>Azanello

**Comment by saurabhqaengineerfp** [comment]
Thanks for responding. Please check after clicking the delete icon that your widget/component goes back to how it was before applying widget styling. For example if you apply a widget style to a button and then delete the widget style, ideally your button should go back to how it was before applying the styling. In the gif you have uploaded I don't see your container, all I see is that you are able to click on delete icon after applying the style. Please share the full screen so that I can see that your container goes back to how it was after clicking delete.

I am uploading a video with bug reproduction. You can see in the video that I applied pink colour to the container but after I click delete icon the container still remains pink.

[https://github.com/user-attachments/assets/83861d61-b675-45ba-9fe9-b37be114ac95](https://github.com/user-attachments/assets/83861d61-b675-45ba-9fe9-b37be114ac95)

Please check. Thanks

**Comment by Alezanello** [comment]
Oh, I thought the delete button wasn't working for you and that you couldn't remove the theme style. Once the theme is set and then removed, it doesn't revert to the previous theme. You need to manually change the colors again. This is not a bug; it's the expected behavior when deleting the theme style of a widget.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
