### ISSUE TITLE
Integer is initialized as 0 despite being not set

### ISSUE THREAD

**Issue by reghta** [FlutterFlow/flutterflow-issues#3542]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In Users collection I have a field called credits. This field is not filled at the time of user creation. I am checking this field to see whether the user is a new user or not, if a new user I would take a specific action. However it turns out FF is considering integer value as 0 even when a field is not set so I can not take the expected action. 

### Expected Behavior

The field is set shoud return false. There is a difference between 0 and is not set. The same issue does not happen when data type is something else e.g. when string non-set fields display as null. 

### Steps to Reproduce

1- Create a new integer field in Users collection
2- Start Test mode
3- Check User values and see that the new field is displayed as 0

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeicqB35RIpbxJ17rQa+xapwMxJ1gjbJ0vhOt+FEgjGKKtEZk1buvTSHpZTczgfGxiJFCYoHIK0dbsj97hCMI4KU2EQ5RiwaV+SAuVRkStabaxCZaWXGpSO/1RIWKF5Imnqx54BMdqZXMuig/GSw==

### Visual documentation

<img width="902" alt="Screenshot 2024-08-03 at 9 39 16 AM" src="https://github.com/user-attachments/assets/a9c1b564-c7a8-4357-bb73-4f5eb52005c4">
<img width="1308" alt="Screenshot 2024-08-03 at 9 40 55 AM" src="https://github.com/user-attachments/assets/19ec6955-9e79-4c15-bcc1-ac6bfaec2675">
<img width="810" alt="Screenshot 2024-08-03 at 9 39 36 AM" src="https://github.com/user-attachments/assets/b7cc69f2-3e58-4638-930c-f44e52dbe749">

### Environment

```markdown
- FlutterFlow version: v4.1.79
- Platform: Test mode & Web
- Browser name and version: Chrome  Version 124.0.6367.201 (Official Build) (arm64)
- Operating system and version affected: Building on MacOS
```

**Comment by msusviela** [comment]
Thanks! I was able to replicate the issue.<br>I'll send it to ENG so they can work on this.

**Comment by wenkaifan0720** [comment]
Hi @reghta. This is what the code looks like:
```
  // "intTest" field.
  int? _intTest;
  int get intTest => _intTest ?? 0;
  bool hasIntTest() => _intTest != null;
```

If you try to use the value, it will return 0 (as is what debug panel is showing). If you want to check if the field is set (remotely), then it will check if the private field is null or not.

I know this is a bit confusing, but this behavior is consistent with/without debug panel. You can still check `hasIntTest()` if you want to know whether the private field (remote data) is set or not. And we will come up with new UI/UX in the future to make this less confusing.
