### ISSUE TITLE
Create Project (under Settings-> Firebase) seems to be broken

### ISSUE THREAD

**Issue by ARVdevFlostate** [FlutterFlow/flutterflow-issues#3544]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Create Project under Settings-> Firebase seems to be broken. It does not allow to authenticate with Google any more.

See attached screenshot for details.

Is it just me or everyone else is facing similar issue while creating a Firebase project through FlutterFlow?

**My environment details:**
OS - MacOS Sonoma 14.6
FlutterFlow Desktop App - v4.1.79
Browser - Google Chrome, Version 127.0.6533.89 (Official Build) (arm64)

### Expected Behavior

Settings-> Firebase-> Create Project should be able to authenticate with Google and create a corresponding project on Firebase. 

### Steps to Reproduce

1. Create a blank project in FlutterFlow
2. Navigate to Settings-> Firebase and click on "Create Project" button
3. In the dialog, Click on Authenticate with Google

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89gocdc7r6IKPlvmiQUOU8cTeUzlO1hdwwbI+KsBIYuZPfBfkhpSOqHTFZAJU2j8VEDpMqLvoXLUvAqJQycY71y+LhTUxDgTkSgbq6vCKi8P2tQTMpXGXaZ1raZhxRSAMhuciFm602qFfOub3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1819" alt="Screenshot 2024-08-03 at 13 16 23" src="https://github.com/user-attachments/assets/757c3561-758f-4021-9cee-51c79db56cc1">

### Environment

```markdown
- FlutterFlow version: v4.1.79
- Platform: FlutterFlow Desktop App
- Browser name and version: Google Chrome, Version 127.0.6533.89 (Official Build) (arm64)
- Operating system and version affected: MacOS (Apple Silicon) Sonoma 14.6
```

### Additional Information

Unable to create Firebase linked project.

**Comment by rzambroni** [comment]
Hello @ARVdevFlostate, thanks for the report, the issue you are describing is a known issue on desktop versions, it is already on the team's backlog to be fixed.

As a workaround you can use the[ web-app](https://app.flutterflow.io/) to create the project and continue later on the desktop version if you want.

Marking this ticket as a duplicate in favor of the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/2935).

Thanks.
