### ISSUE TITLE
Action disappearing after adding action on action flow 

### ISSUE THREAD

**Issue by SoLexGrowth** [FlutterFlow/flutterflow-issues#3545]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open the flutterflow action builder and add my action after adding the action it's disappear immediately after 5 seconds. It's stated happening after the recent updates made yesterday

### Expected Behavior

To save and not to revert or disappear and my project is 99℅ percent done 🤦‍♂️

### Steps to Reproduce

1. create a new page
2. add a button
3. query a collection 
4. filter by not in or in 
And try saving the action

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekM/l25J2n7wC0bX2YccxqwMxN0A5beREi+sbTgEbfYzxOpwpWuDQRFpCXunjfXNcGFqlvGAEptbyjvHyUfQ4OgyHbJhA/rlUTw7MQnmjR824DpG0Ynd5I55WCXKPyra7rSJ/NbNtW11pig/GSw==

### Visual documentation

![ScreenShot Tool -20240803130224](https://github.com/user-attachments/assets/15fde13d-9f79-409a-bb11-fdcd31678cc0)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

it's affecting me so badly because my project is 98% done

**Comment by celiostat** [comment]
I have the same issue. Or say i change the parameter of a component. It will comes back to previous states when opening the action panel again.

**Comment by SoLexGrowth** [comment]
This is not a good one... I have reported this issue over 10 hours ago but no response till now

**Comment by agreaves** [comment]
Hi @SoLexGrowth, I've been looking into this issue but I can't seem to be able to reproduce it. Could you please send me a video of this occurring so I can follow along exactly? Thanks, and sorry for the issues!

@celiostat could you also add a video and bug report code for what you're experiencing?

**Comment by agreaves** [comment]
Wait nevermind! I just managed to reproduce it, seems it only happens when you're setting In/Not In to a variable, not a set value. Hopefully this is a quick fix!

**Comment by SoLexGrowth** [comment]
Okay sure 👌👌 please we look forward for updates please

**Comment by agreaves** [comment]
Fix is in! Should be deployed on web shortly and on desktop within the next few days
