### ISSUE TITLE
Something strange is happening with my application. The deployment is not working, and the ios test launch is not working

### ISSUE THREAD

**Issue by DevioGit** [FlutterFlow/flutterflow-issues#3546]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the application is deployed, it issues an error, the report is not clear why and how to solve it using flutterflow, as if the problem is on the server side. Also, it is not possible to launch the application in the ios simulator, when the application is launched, it (the application) freezes and does not load, there are no envelopes.

![CleanShot 2024-08-03 at 22 02 34@2x](https://github.com/user-attachments/assets/3fba84b6-c8f7-46b5-b519-2c952eb9fbce)

Ios deploy:
![CleanShot 2024-08-03 at 22 02 58@2x](https://github.com/user-attachments/assets/34842c2b-6af4-4c05-a8cc-4b499f164f8c)

android deploy:
![CleanShot 2024-08-03 at 22 03 31@2x](https://github.com/user-attachments/assets/37141503-caed-4c81-b13f-6b907ff52b39)

Я попытался продублировать проект, что бы хотя бы запустить приложение в симуляторе, но ничего не вышло (

### Expected Behavior

The application should start in the simulator, and the deployment should be successful since all keys and IDs are specified correctly, and there is nothing that would prevent the deployment.

### Steps to Reproduce

Problem 1: Open the project, run the test in the ios simulator

Problem 2: Open the application settings, the deploy tab, click deploy to

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlcjfsIV1m+EA+KXcYPlKhjgQM0MdXOczitVEew4bCIj4PJouPsn7blBoZMizaH9AOlCahnoB+ejviODtJvAqGwqsG7lxzrt+bRPPbEymeKrQPqWoZkBQQdJbI2Kd5pi7gyZSOvRtWmAu716ueu6tcz6Cf9qOYwx5e6fDbOY=

### Visual documentation

![CleanShot 2024-08-03 at 22 10 03@2x](https://github.com/user-attachments/assets/89077186-971f-4e9a-b5ae-e7f09b1e811e)
![CleanShot 2024-08-03 at 22 10 17@2x](https://github.com/user-attachments/assets/b54c16cf-e59c-43d1-8215-9b86069ea80d)
![CleanShot 2024-08-03 at 22 10 43@2x](https://github.com/user-attachments/assets/4ed7d0bf-bc56-46db-a694-f98c5fb94997)

### Environment

```markdown
- FlutterFlow version: 4.1.79 synced 
- Platform: MacOs Desktop
- Browser name and version: app
- Operating system and version affected: macOS sonoma 14.5
```

**Comment by DevioGit** [comment]
Project id — crosbit-wrdrax

**Comment by DevioGit** [comment]
![CleanShot 2024-08-04 at 23 38 31@2x](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/aa095175-0793-4c77-9093-da87f4632e49/eecb41a8-0a0d-497f-91e7-bd0df523a215?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYTA5NTE3NS0wNzkzLTRjNzctOTA5My1kYTg3ZjQ2MzJlNDkvZWVjYjQxYTgtMGEwZC00OTdmLTkxZTctYmQwZGY1MjNhMjE1IiwiaWF0IjoxNzIyODAzOTg0LCJleHAiOjMzMjkzMzYzOTg0fQ.MR5D4cm0JMKC3i2BC9bcNmHjyc5B-szJ08RRpt-Sc8g)

It seems the problem is because of this, how do I remove FirebaseMessaging?

**Comment by Alezanello** [comment]
Hello!

I just checked your project, and as soon as I opened it, I encountered an error regarding the Firebase config files. Could you please try regenerating the files from the Firebase configuration menu inside FlutterFlow and then try to compile your app again?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/421849fa-82fb-4a22-9ccc-df748a840510/a824132d-4d03-464b-ae2d-f6cd5adeb13b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MjE4NDlmYS04MmZiLTRhMjItOWNjYy1kZjc0OGE4NDA1MTAvYTgyNDEzMmQtNGQwMy00NjRiLWFlMmQtZjZjZDVhZGViMTNiIiwiaWF0IjoxNzIyODYwOTI5LCJleHAiOjMzMjkzNDIwOTI5fQ.hepx0cCnGK9QGPR8CT48_qVQGMXkZ1dKPk8liGU4e6U " alt="Imagen de WhatsApp 2024-08-05 a las 09.24.57_18eba934.jpg" width="606" height="486" />

Best regards,<br>Azanello

**Comment by DevioGit** [comment]
> Hello!
>
> I just checked your project, and as soon as I opened it, I encountered an error regarding the Firebase config files. Could you please try regenerating the files from the Firebase configuration menu inside FlutterFlow and then try to compile your app again?
>
> ![Imagen de WhatsApp 2024-08-05 a las 09.24.57_18eba934.jpg](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/377e6326-89c0-49c6-aec0-cbb69bc9daf5/9feaeee9-5322-46f5-ba03-6e0dfca3b8da?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNzdlNjMyNi04OWMwLTQ5YzYtYWVjMC1jYmI2OWJjOWRhZjUvOWZlYWVlZTktNTMyMi00NmY1LWJhMDMtNmUwZGZjYTNiOGRhIiwiaWF0IjoxNzIyODYxMjY5LCJleHAiOjMzMjkzNDIxMjY5fQ.Kz9iJKwu0IS0ZAKg1LUD-v16dg6CRqSCU9OGzBImb0w "=606x")
>
> Best regards,Azanello

Yes, I just did it, and there are no mistakes anywhere. But the problem remains

**Comment by Alezanello** [comment]
Hello again,

Sorry for the late response. At this point, I'm lacking the right tools to help you with this issue. I'll keep this issue open in case I find anything that might help, but in the meantime, I recommend you contact support directly via the in-app chat or at support@flutterflow.io for a more specific solution to your situation.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
