### ISSUE TITLE
Won't navigate automatically after create a user on Firebase.

### ISSUE THREAD

**Issue by leoleo-s** [FlutterFlow/flutterflow-issues#3547]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The "navigate automatically" won't work after creating a user on firebase. It does create a user successfully, but won't navigate to the logged in page. I even tried to disable the "navigate automatically" toggle and put a navigate action after creating the user, it did not work either. 

I'm on the deadline of this project and this is preventing me from launching the app. It's crucial for my purchase flow.

It was tested on web and iOS.

### Expected Behavior

Navigate to the logged in page after creating the user.

### Steps to Reproduce

Set firebase auth login page and logged in page. Create a page, put any widget, set an action to create a user on firebase, mark the "navigate automatically" toggle. Test it.

Alternatively create the firebase user with the "navigate automatically" toggle disabled. Set a navigate action after. It won't work either.

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lPHqx5d2m+FG+KryafpvtCAsQzI7a7s8mMFtbA88KOPdOoYUP8+kM0RucM/nS3xEP2KWnWoW0+DXhobAFcdfJQ6bY7pTypB+TjnwLT6nWr6qFJWgSnZRPNNMChzG5MPQiBB7LuhvcVoN7DvzOuyiQXPUQrL7OzICDq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/dcccaac5-a121-4615-8f77-843d0725ef7c

### Environment

```markdown
- FlutterFlow version: 4.1.79+ Synced
- Platform: Web and iOS
- Browser name and version: Chrome 127.0.6533.89 (Official Build) (x86_64)
- Operating system and version affected: MacOS 13.6.8 Ventura
```

### Additional Information

The app is pretty much done and this functionality is crucial for my purchase flow. It's preventing me from launching the app.

**Comment by leoleo-s** [comment]
Turned out the problem was the Firebase Rules. I managed to get it working by setting it up correctly. Sorry about that.

**Comment by msusviela** [comment]
Thanks for the update! I'll be closing this issue since you solved it. If you're still experiencing this, feel free to open another issue. 

Thanks for using FlutterFlow!
