### ISSUE TITLE
Web app not properly initialized once user is logged in

### ISSUE THREAD

**Issue by bmw559** [FlutterFlow/flutterflow-issues#3548]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I would like to ask you this question: I haven't made any changes to my main page in the last few months, but I have noticed inconsistencies when loading this page. Upon the very first load, it does not validate the conditions correctly under the user collection. On this page, the relevant items are displayed depending on whether the user is an admin or not. Upon the initial login, for some reason, it shows the isAdmin condition as false for an administrator user. On the page, I also display this variable, which is false for a while and then turns true. I have a similar experience with the validation of another variable, welcomeIntro, which behaves similarly to what I described for isAdmin. Can anyone advise me on what is going on, whether it is some kind of bug, or what is actually wrong? Because I can't think of anything anymore, really. A condition is a condition, it's either met or not... It seems to me as if the conditions don't wait for the user collection to fully load, and the page starts building. It feels like FlutterFlow doesn't wait for the data to fully load.
This problem is replicable when closing the browser and reloading the page; it always behaves the same way. If the page is already loaded, then it builds correctly for a while, but after a few hours, the same problem occurs again.

Havent experienced this issue so far with APK only on web on multiple devices and browsers include smartphones.

### Expected Behavior

1. Initial page once the user is logged in properly builded based on the user conditions

### Steps to Reproduce

1. User with admin rights needs to logged in
2. Close the Browser
3. Open the Browser again and Load an app
4. The page should be builded with not valid conditions
5. Click anywhere in the app and the page should be finally builded as expected

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi+fl/otItbxc0KXyb8BFmSQvJnp+RLhMkcpBZywgfZzzBLN/fPfQP1BvTcOlT0FIOGacp14H//zok/L9NsJdAy+YQa5JzKhUag/zUk2QVZ+TF7uCPkB5O8NXfXa/yJ+rswlSJu9ocmw17F+IPvCXaBbDQpe2ClQwSq/LZO4=

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.79+ released August 4, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome, Edge
- Operating system and version affected: Windows, Mobile - web
```

**Comment by bmw559** [comment]
Will add an video showing the issue in 1-2 hours

**Comment by bmw559** [comment]
[https://github.com/user-attachments/assets/ef62b98a-2bf9-4fa9-bb79-53eab851286f](https://github.com/user-attachments/assets/ef62b98a-2bf9-4fa9-bb79-53eab851286f)

**Comment by bmw559** [comment]
Note: The items have been hidden by myself due to confidential data

**Comment by Alezanello** [comment]
Hello!

It seems that you are filling all the information directly from the Authenticated User variables. These variables are set **after** checking or refreshing the Firebase Token Session, so the information on your page may not update immediately. Once you move to another page, all the Auth User variables are properly set.

One recommendation is to query the user collection where `uid = User ID` variable from the Authenticated User, and use that User query to fill all the information on your pages. You can also do the query and save the document information in AppState as a `UserInfo` DataType to have constant access to it, which is useful if you only need to query it once.

Best regards,<br>Azanello

**Comment by bmw559** [comment]
> Hello!
> 
> It seems that you are filling all the information directly from the Authenticated User variables. These variables are set **after** checking or refreshing the Firebase Token Session, so the information on your page may not update immediately. Once you move to another page, all the Auth User variables are properly set.
> 
> One recommendation is to query the user collection where `uid = User ID` variable from the Authenticated User, and use that User query to fill all the information on your pages. You can also do the query and save the document information in AppState as a `UserInfo` DataType to have constant access to it, which is useful if you only need to query it once.
> 
> Best regards,Azanello



> Hello!
> 
> It seems that you are filling all the information directly from the Authenticated User variables. These variables are set **after** checking or refreshing the Firebase Token Session, so the information on your page may not update immediately. Once you move to another page, all the Auth User variables are properly set.
> 
> One recommendation is to query the user collection where `uid = User ID` variable from the Authenticated User, and use that User query to fill all the information on your pages. You can also do the query and save the document information in AppState as a `UserInfo` DataType to have constant access to it, which is useful if you only need to query it once.
> 
> Best regards,Azanello

Yes, but this type of query is not streamed so the user data will not be up to date in case of any updates, the query is initiated and you dont have access for the latest informations in case of any updates, why is there the user details directly from flutterflow if they are not sure that they were properly loaded, it not make any sense to me..

**Comment by bmw559** [comment]
I would like to highlight that I have never experienced this issue in the past with the same setup of my app, and it’s also not happening in the APK version.

**Comment by bmw559** [comment]
Does anyone check that as possible bug ? As described earlier I never experienced this kind of issue in my web app previously and the code of my app is same as before, its only not "working" as expected only for Web application apk is working as expected.

Patrik

**Comment by Alezanello** [comment]
Hello,

I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by bmw559** [comment]
> Hello,
> 
> I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

No still experiencing the same issue.

**Comment by Alezanello** [comment]
Hello again,

Apologies for the delayed response. Could you please try using the Test Mode and the Debug panel on the left to check if the Authenticated Users populate correctly after logging in and if they load properly when the page loads?

**Comment by bmw559** [comment]
> Hello again,
> 
> Apologies for the delayed response. Could you please try using the Test Mode and the Debug panel on the left to check if the Authenticated Users populate correctly after logging in and if they load properly when the page loads?

Hey I never experienced this in test mode only in the live app for Web App other platforms(Apk) are working as expected.

**Comment by bmw559** [comment]
@Alezanello hey was the issue already fixed ? In which version I can expected this bug solved ?

**Comment by Alezanello** [comment]
Hello!

It seems like the issue might be related to how the data is loading in your project. Here's a suggestion: try adding an "Update App State" action with an empty configuration and include a "Rebuild All Pages" step in the `On Page Load` actions of your home page. You might also want to add a short delay before the rebuild step to ensure it happens after all authentication data has fully loaded.

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
