### ISSUE TITLE
Error running Flutter Pub Get

### ISSUE THREAD

**Issue by orchard800** [FlutterFlow/flutterflow-issues#355]
## Expected behavior (required)
When I create a boilerplate custom widget and add the dependency 'qr_flutter' and import 'package:qr_flutter/qr_flutter.dart'; This works perfectly everywhere except in this project.

## Current behavior (required)
Currently I get this error when I compile code:
![image](https://user-images.githubusercontent.com/84687635/212521742-90172e14-9deb-46c7-947b-4c936983c259.png)

## To Reproduce (required)
1. Create a new custom widget with boilerplate code.
2. Add qr_flutter dependency and associated import statement: 
3. Click refresh code editor with pub spec dependencies button.  
4. Click Save
5. Click compile code button.

### Bug Report Code (required, generate from Widget Tree)
ITEelsrq24xJpbxb1rXfKMBv9AMwGkQ5a7sviu5+FBQaI+PkB4oqOuDBdhRuWOqHe1ZYJVD/pFsF/vzmvd79FMErBEmufphd/85xH1yjEA8=

## Context (required)
I am trying to build a custom widget using the qr_flutter package from pub.dev. This all works perfectly in other projects of mine but not this one.

## Your environment

* Version of FlutterFlow used: 
![image](https://user-images.githubusercontent.com/84687635/212521972-1a83533f-3444-45ea-9ce8-ec511536e174.png)

* Platform (e.g. Web, MacOS Desktop): Web, iOS & Android
* Browser name and version: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 fully updated

**Comment by orchard800** [comment]
Note: This is the same pub.dev package working in another project of mine.
![image](https://user-images.githubusercontent.com/84687635/212522047-2874eee0-f82c-4920-894b-9ba432925f80.png)

**Comment by wenkaifan0720** [comment]
Hi @orchard800. I have followed the steps but could not reproduce the error. It might be a temp server issue. Could you try it again?

![iScreen Shoter - Google Chrome - 230116135820](https://user-images.githubusercontent.com/112435854/212608437-72a0ee45-e313-40c0-b3d1-7f64006076f2.jpg)

**Comment by orchard800** [comment]
Hi Wenkai,

I have tried again but got the same issue. I've even flushed my cache and
refreshed my project - done all the troubleshooting steps.

I think there's something awry with either Flutterflow or my account. My
other (test) project now says no errors in the code but won't run in test
mode (see below). But the project runs fine in normal run mode.
[image: image.png]
[image: image.png]

Until recently I was using qr_flutter in my projects with no issues. Other
projects all still run ok.

**Comment by orchard800** [comment]
Any update on this?

**Comment by wenkaifan0720** [comment]
Hi @orchard800. Could you provide your project link? I need to reproduce the issue first.

**Comment by orchard800** [comment]
Hi @wenkaifan0720. Yes, it's https://app.flutterflow.io/project/bitly-dlx5ro. Please note this app is now in production so I've had to remove the offending code until the issue is resolved. Thanks.

**Comment by orchard800** [comment]
Is anyone still looking into this? This is now a production app that I'm unable to progress - despite paying a monthly subscription for Flutterflow. I shouldn't be getting this error with a very basic custom action:
![image](https://user-images.githubusercontent.com/84687635/214009552-54f37efa-e810-4677-9804-7eb2d7ff3188.png)
Please help!

**Comment by wenkaifan0720** [comment]
Hi @orchard800 . I am so sorry for the delay. Yes I am still looking into this. However this week I am constantly traveling so I dont have much time debugging. Rest assured we will get your issue resolved.

**Comment by wenkaifan0720** [comment]
Hi @orchard800. I know what is causing the issue now. It is not because your account or FF is broken. But rather due to the fact that this project depends on the [barcode_widget](https://pub.dev/packages/barcode_widget)

**Comment by orchard800** [comment]
Hi, ok could you elaborate on that for me. How come it needs that dependency? Thanks!
-------- Original message --------From: Wenkai Fan ***@***.***> Date: 24/01/2023  14:33  (GMT+00:00) To: FlutterFlow/flutterflow-issues ***@***.***> Cc: orchard800 ***@***.***>, Mention ***@***.***> Subject: Re: [FlutterFlow/flutterflow-issues] Error running Flutter Pub Get (Issue #355) 
Hi @orchard800. I know what is causing the issue now. It is not because your account or FF is broken. But rather due to the fact that this project depends on the barcode_widget

**Comment by wenkaifan0720** [comment]
Hi @orchard800. Flutter packages can depend on other packages to speed up development, making them not standalone anymore. If every package you use is always up to date, then things should be fine. In this case however, we have the `qr_flutter` package (which is almost 2 years old) and the `barcode_widget` package (that the Barcode widget in FlutterFlow requires) both depending on the `qr` package but on different versions. So when Flutter runs `pub get` to download the packages, it can not determine which version of the `qr` package to get.

My suggestion is to remove the `qr_flutter` package completely and switch to the `barcode_widget` package. You can still plot QR code with this package.

**Comment by orchard800** [comment]
Hi @wenkaifan0720 Thanks for this explanation. It does make sense. However the who purpose of my app is to allow the user to customise their QR code. How can I do this with barcode_widget. The documentation on pub.dev is very minimal :-)

PS. Can you guys please update your documentation? eg this is only 8 months old but totally out of date now if there's the conflict you mention above. 
https://blog.flutterflow.io/qr-code-generator/

**Comment by wenkaifan0720** [comment]
Oh it should be even simpler now as FF directly supports the Barcode widget now.  

![iScreen Shoter - Google Chrome - 230128094357](https://user-images.githubusercontent.com/112435854/215235231-252f7d85-a6bb-4957-8987-b97aab9d2391.jpg)

Just fill the `Barcode Value` field in the Barcode widget settings.

I apologize for the outdated info in our blog. I am not sure if we will update it considering the fact that it is really a blog instead of documentation. Information that is related to platforms outside of FF can get out of sync as we are not notified about these breaking changes unless our team or our users notice them. So we really appreciate your effort for creating this issue and notify us 😃. I'll discuss with our team to find a better way to describe the dependency conflict so our user understand what is going on.
