### ISSUE TITLE
Network Disconnected / Project no Synced

### ISSUE THREAD

**Issue by VargasPiensa** [FlutterFlow/flutterflow-issues#3551]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dear FlutterFlow Support Team,

I would like to report a critical issue we're experiencing with our project. When attempting to make new updates, we notice that after every two actions, or even fewer, the project disconnects or desynchronizes, preventing us from saving the changes made. This is blocking our progress, and we cannot move forward with the development of the project, which we urgently need to complete.

This issue is not isolated, as other team members have reported the same problem. We would appreciate a prompt resolution or guidance on how to address this situation, as it is significantly affecting our workflow.

Thank you for your attention, and we look forward to your prompt response.

Best regards,

Daniel Vargas
Sailer App CEO

![photo_5001359880434593618_x](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7e41075d-9ec3-42d0-9bb2-fe76bfc52166/fa1f5440-69cd-40b6-bd90-4e453155362c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZTQxMDc1ZC05ZWMzLTQyZDAtOWJiMi1mZTc2YmZjNTIxNjYvZmExZjU0NDAtNjljZC00MGI2LWJkOTAtNGU0NTMxNTUzNjJjIiwiaWF0IjoxNzIyODMxODcyLCJleHAiOjMzMjkzMzkxODcyfQ.I8dbJCVrEWC1tdSCPKzEFGRYa27Wo-ua5vGOeDR8Xz8)

![Captura de pantalla 2024-08-04 131613](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e3fa4f7a-7553-451f-950c-b45c7ab15f7e/b6626045-688f-4be7-9e6b-534644316567?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lM2ZhNGY3YS03NTUzLTQ1MWYtOTUwYy1iNDVjN2FiMTVmN2UvYjY2MjYwNDUtNjg4Zi00YmU3LTllNmItNTM0NjQ0MzE2NTY3IiwiaWF0IjoxNzIyODMxODcyLCJleHAiOjMzMjkzMzkxODcyfQ.AX8l9EjmERk7dBuRSpKiugAxAn1MoL5LsAT6LSNyQZM)

### Expected Behavior

The expected behavior of our project is for it to operate regularly and stably within FlutterFlow. This means that we should be able to perform any action available on the platform without issues, including creating components and widgets, as well as adding information to the project.

It is crucial that the project maintains a continuous and uninterrupted connection, allowing us to save changes and updates smoothly. Every action, from the simplest to the most complex, should be able to be completed without the project disconnecting or desynchronizing.

We hope this issue can be resolved so we can efficiently continue our development tasks.

Thank you in advance for your assistance.Thank you in advance for your assistance.

### Steps to Reproduce

Just try to perform more than 4 actions and you will see that it is not possible.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hfLl5Yx2rsRE7ZPuY8JV+TwWQkc7bbg4mOtEFAg8J5DaPOxzP/TBaldWUs+0YEFYfE78hnsxw+vemvzXDfo7AwmcfaZHwahIWg3wIVGVb5iaPrqOR25/Df9TGGGP57SNpRJRAMdicXgd7DiQGO+XcAndH5juPXonD/mID5KK2SrDX1iXc2URm05KZDPz

### Visual documentation

![photo_5001359880434593618_x](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2547fe5b-58b7-4858-9e78-b9f106d0de54/7c39d014-a8bd-4650-b0e4-0b29b8b3fcc8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNTQ3ZmU1Yi01OGI3LTQ4NTgtOWU3OC1iOWYxMDZkMGRlNTQvN2MzOWQwMTQtYThiZC00NjUwLWIwZTQtMGIyOWI4YjNmY2M4IiwiaWF0IjoxNzIyODMxODcyLCJleHAiOjMzMjkzMzkxODcyfQ.52lAaU1Qr-FbMksUODVDhAdn\_-ljckp8A5f2jBEa990)

![Captura de pantalla 2024-08-04 131613](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/826c8222-fb11-40c7-8839-0e68fa483f76/69312aaf-263a-4913-b84c-fcd2263fd88a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MjZjODIyMi1mYjExLTQwYzctODgzOS0wZTY4ZmE0ODNmNzYvNjkzMTJhYWYtMjYzYS00OTEzLWI4NGMtZmNkMjI2M2ZkODhhIiwiaWF0IjoxNzIyODMxODcyLCJleHAiOjMzMjkzMzkxODcyfQ.2BQkzKUWwoxePAgtOEG3RBhdtLSA85gmGeuNBsBlyhs)

### Environment

```markdown
- FlutterFlow version: v4.1.79+ released August 4, 2024 Flutter version is 3.22.2
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected:
```

### Additional Information

*No response*

**Comment by VargasPiensa** [comment]
In addition to this I want to comment that the project has been working really slowly to be able to make any changes.

**Comment by agreaves** [comment]
Hi @VargasPiensa, so sorry for this issue! I believe we've just made a fix that should allow you to continue to edit the project, but I'd like to be sure before closing the issue. Please let me know! And apologies once again.
