### ISSUE TITLE
NULL Error when using Conditional Value with a Boolean

### ISSUE THREAD

**Issue by SebyOnGitHub** [FlutterFlow/flutterflow-issues#3555]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the Backend we have a Bool, which can be TRUE, FALSE and NULL.
When using Flutterflows IF ELSE Conditional tools, it works, when the Bool is True or False.
But when the Bool is NULL (which is still a sentinel value) nothing works anymore.

### Expected Behavior

Everything should still execute, because NULL is still a sentinel value, which is important to know for business logic.
(For example using only the is set or is not set condituional logic, it still works. Only the IF ELSE logic is broken)

### Steps to Reproduce

Step 0.
Add a Bool with TRUE, FALSE and NULL. In our case we are using Supabase. But this bug should be replicable with other backends as well.
![image](https://github.com/user-attachments/assets/f77a37ac-0f22-4efe-9e39-f3eb3ce72c8b)

1. In Flutterflow create a new page

2. Add text field with which we query a row
(In this example, the filtering the row by this dropdown is for easier demonstration, but is not necessary to get the bug)
![image](https://github.com/user-attachments/assets/862d9ee0-df43-433a-9178-68032f8cce64)

3. For the text itself, set up a "Condotional Value (If/Then/Else)"
(I also added a conditional "This is unset" instead of just using the "This is ELSE", but this is **not necessary for this bug**).
![image](https://github.com/user-attachments/assets/cceb2a9a-de7b-4fab-9450-22bf0369ae28)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wksrl8c92rsRE187ubvpVhjgWQ187ULsrjMN+GUkdF5D1P5wPX/ykP1FoXbSndglEOlqjmnox3NrIm9z1K/A6AwSsfaJ/yKt2YQLiUkGQR7KmBsy8X3FUGshQI0Cl5LWrnR54CPFhWiE53ziUPueUaB3BJOPOO1U7MvyYBJrXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

To remind ourself, what the bool values are, for the following test:
![image](https://github.com/user-attachments/assets/f77a37ac-0f22-4efe-9e39-f3eb3ce72c8b)

When running this, we can see, getting the Bool from Row with ID 1 it returns the correct IF condition:
![image](https://github.com/user-attachments/assets/65d626ac-441f-4ec9-9cb1-2d780a12d014)

Getting the Bool from Row with ID 2 it returns the correct IF condition:
![image](https://github.com/user-attachments/assets/f68c950e-66ad-40a3-b698-f3832f286fdc)

Getting the Bool from Row with ID 3, it stopps working:
![image](https://github.com/user-attachments/assets/7c581c18-2548-4150-846a-8318284593ae)

On test 3 we should either get a "This is not set" or a "This is ELSE" from the conditional tool.

### Environment

```markdown
- FlutterFlow version: v4.1.80+
- Platform: Windows
- Browser name and version: Chrome 122.0.6261.129
- Operating system and version affected: Windows 10
```

### Additional Information

If it is helpful to see this example in a real environment, rather than this isolated/simplified example, please let me know.

**Comment by Alezanello** [comment]
Hello!

I just tested your project. Could you please add me as a collaborator to try some solutions? If not, I can forward this to the engineering team for a fix. My email is azanello@somniosoftware.com.

Best regards,<br>Azanello

**Comment by SebyOnGitHub** [comment]
Sure, i have added you to the Project. Feel free to try out.

Additionally, i have also added another test, which only uses the is set and is not set logic, without an if else statement, if that helps. (But you need to make the if else text invisible to see the new test working)
To showcase, that the conditional logic „is set“ and „is not set“ is working, and the problem lies in the if else logic.

**Comment by SebyOnGitHub** [comment]
Hi @Alezanello, if you still need more information, please post your questions because this issue still has the label waiting for user response?

**Comment by SebyOnGitHub** [comment]
Hi @Alezanello What is the status of this bug? Do you need more information, when can we expect a fix for this bug?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by SebyOnGitHub** [comment]
Hi, with the latest FlutterFLow of today, when getting the NULL value, the error still occurs. (Selecting 1 and 2 still works, but selecting 3, which is the NULL bool, still throws an error) And Please keep in Mind, that 3 is the BOOL with NULL.
![image](https://github.com/user-attachments/assets/3c5cb6e4-8011-4126-a916-c6445d9aba81)
![355056483-f77a37ac-0f22-4efe-9e39-f3eb3ce72c8b](https://github.com/user-attachments/assets/dfb6accc-754b-4705-8fc9-abe357e2af8d)

**Comment by SebyOnGitHub** [comment]
Hi @Alezanello 
This Bug report is still status waiting for user response, is this true? I would like to know what is the real status of this report?

**Comment by Alezanello** [comment]
Hello again, and apologies for the delayed response. I’ve looked into the issue and can confirm it. I tried several approaches, but it appears that the most efficient solution at the moment is to query your data from Supabase through a custom function that handles null values and returns only valid data.

Currently, FlutterFlow doesn’t have built-in support for this, so it would be more appropriate to consider this as a feature enhancement request rather than a bug, as this functionality has never been implemented.

I will forward this ticket to our engineering team's backlog to prioritize improving how FlutterFlow handles null values from Supabase. Thank you for bringing this to our attention, and we appreciate your patience.

**Comment by SebyOnGitHub** [comment]
Hi @Alezanello 
Now that we are getting Supabase updates, I wanted to ask if this is getting closer to be worked on?
