### ISSUE TITLE
HTML View widget not displaying image tags with inline style, specifically sizing.

### ISSUE THREAD

**Issue by ranmitch99** [FlutterFlow/flutterflow-issues#3557]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

HTML View widget not displaying image tags with inline style, specifically sizing. For example an image tag with <img src="https://someimage.png" style="height:90%; width:90%" /> will display nothing in the HTML View widget but <img src="https://someimage.png/" /> will display the image. This worked until recently.

### Expected Behavior

The image should at least display and honor the sizing. This has worked in the past.

### Steps to Reproduce

Create an app page, add HTML View widget, add image tag with a style attribute that includes sizing.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTj8+BxIthssxI+KX2d8AxgigUGUMdWp0vlu1vewgjF774O5kMe8mkSxNBXeKzaHxiP2KGpEMHw/Tpv4XpCPYnBxGuGLo7wqtqchPPYziWR4SoPbmSOUdAAfxWGEPE07WrviVSPvZfcXws2zmEDe6iRT+Cf9qOYwx5e6fDbOY=

### Visual documentation

![no_size](https://github.com/user-attachments/assets/f3aded53-76e5-4bb5-a294-e5da89377b2c)
![with_size](https://github.com/user-attachments/assets/9799a3c0-8ddb-40a4-90c3-832b708390d6)

### Environment

```markdown
- FlutterFlow version: 4.1.79
- Platform: MacOS Desktop and Web
- Browser name and version: Chrome 126
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @ranmitch99. So sorry you're experiencing this. The HTMLView widget was deprecated recently. You can use WebView instead, selecting the HTML option:<br>[https://docs.flutterflow.io/concepts/navigation/webview/#load-content-from-html](https://docs.flutterflow.io/concepts/navigation/webview/#load-content-from-html)<br><br>Let me know if that solves the issue for you.

**Comment by ranmitch99** [comment]
This is what I thought may have happened. My main concern is the HTML View expands and contracts to the space needed to display the HTML included. For example, if you have text followed by and image, then followed by more text, if the image is tall or wide with the right HTML it can fit inside the area allowed without scrolling. This does not seem to be possible with the Web View widget. What am I missing is this possible?

**Comment by msusviela** [comment]
Hi @ranmitch99.<br>This should be solved by removing the height here:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d4b4e6c1-d932-4aab-9c8c-bc234fb9505a/5ab492b1-19c6-4c17-b9dc-573ce2767c17?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNGI0ZTZjMS1kOTMyLTRhYWItOWM4Yy1iYzIzNGZiOTUwNWEvNWFiNDkyYjEtMTljNi00YzE3LWI5ZGMtNTczY2UyNzY3YzE3IiwiaWF0IjoxNzIzNDU3Njk1LCJleHAiOjMzMjk0MDE3Njk1fQ.3vRb6Tb0s0Ma7tjq3w0wrvluTYSNdrCgKasQQBMUQkU " alt="image.png" width="199" height="183" />
