### ISSUE TITLE
More pie charts with different section colors

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#356]
## Expected behavior (required)
Adding two different pie charts with different section colors will run smoothly

## Current behavior (required)
Build failed with this error
`Running "flutter pub get" in test...                             2,974ms
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/home_page2/home_page2_widget.dart:35:11: Error: 'pieChartColorsList' is already declared in this scope.
    final pieChartColorsList = [
          ^^^^^^^^^^^^^^^^^^
lib/home_page2/home_page2_widget.dart:29:11: Context: Previous declaration of 'pieChartColorsList'.
    final pieChartColorsList = [
          ^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         40.2s
Failed to compile application.`

## To Reproduce (required)
1. Create new page
2. Add column widget
3. Add the 1st pie chart
4. Add some colors (i used the default ones)
5. Add the 2nd pie chart
6. Add some different colors (i used the default ones but after that deleted the 2nd one)
7. Run mode / Test mode

### Bug Report Code (required, generate from Widget Tree)
ITESz/Hqx89gruEG+bn+Ke16hR8kQ2InarsvhO59Rko3Iqr1PLQTbuvRXFZoTbSGeH9qHGabrEcd7tGLiuPLDcApHxbDJ+AHl/E0LlSrGAc=

ITESz/Hqx89gruEG+bn+Ke16hR8kQ2InarsvhO1teAE0fLL1EOwLbuveXEpoOLSfTApMBWCirzsJ+c2Mj97xLfE5AyfDJ+AHl/E0LlSrGAc=

## Context (required)
Trying two show different data with some pie charts.

Btw I know this is more of a feature request, but it would be nice to be able to choose colours based on variables.

## Your environment

* Version of FlutterFlow used: 3.0 jan 13th
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome latest version
* Operating system and version (desktop or mobile): Windows 11

**Comment by hariprasadms** [comment]
Hi @tothati90 - Thanks for reporting the issue. I can test it and now its been fixed above error. Hence we can close the issue.

https://user-images.githubusercontent.com/17435678/218100916-1cfcbbf1-b692-4fde-ad8f-f90b889fd2a3.mp4
