### ISSUE TITLE
FlutterFlow Work Not Saving

### ISSUE THREAD

**Issue by paulVu** [FlutterFlow/flutterflow-issues#3561]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Work done in FlutterFlow is not saving, requiring frequent rework. The issue primarily occurs in the Action section, despite multiple attempts to save and ensure a stable internet connection.

### Expected Behavior

Changes made in the Action section should save successfully and persist after saving.

### Steps to Reproduce

Open FlutterFlow in Google Chrome.
Navigate to the Action section.
Make changes or add new actions.
Attempt to save changes using "Command + S".
Wait a few minutes and observe if changes persist.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEezMr134Z2pb0F7pP2bO5omQMxQUB+bZ0vlO1FGA0bG4DyEOwudePUaXdfOdTjTQtme060iT4e0uj7ufPxNfI3HwqqY61607thWz3wfFOWaJSnEbqsXXAkMNJjIECX4LSnoB1SD7ZhLlIs3GGLcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation
<img width="1276" alt="Screenshot 2024-08-06 at 10 45 22 AM" src="https://github.com/user-attachments/assets/2644cfd1-5964-4c51-9816-fe878633b67f">

1 min later: 
<img width="1296" alt="Screenshot 2024-08-06 at 10 46 30 AM" src="https://github.com/user-attachments/assets/3b3f4ce6-ed2d-4fd3-8ca1-3365347f01d1">

Actual Result:
Changes made in the Action section do not save. After a few minutes, the work reverts, requiring rework.

Frequency:
Occurs frequently.

Troubleshooting Steps Taken:

Checked and ensured a stable internet connection.
Tried using "Command + S" to save changes.
Monitored the application for a few minutes to see if changes persisted.
Impact:
High – This issue significantly disrupts workflow and productivity, causing frustration and repeated rework.

### Environment

```markdown
Browser: Google Chrome
Internet Connection: Multiple networks tested, including VPN and non-VPN connections
```

### Additional Information

The issue appears to be isolated to the Action section.
The problem persists despite stable internet and multiple save attempts.

**Comment by agreaves** [comment]
Hi @paulVu, sorry to hear about the issues you're facing.

Could you provide any additional info, such as what types of changes to actions go missing, or even better a screen recording of it happening (even once)? That would help us tremendously.

Thanks! And apologies again, we'll definitely try to fix as soon as we can.

**Comment by paulVu** [comment]
Thanks for your response, in this video, you can see that is undo my work after few mins, after I go to check the internet. 

https://github.com/user-attachments/assets/4dc8bf3c-58fe-485c-9f8b-177948b6a7bd

**Comment by Jhenao03** [comment]
I'm having the same issue, when i set a variable it doesn't display any changes i have to do it multiple times, but recently i noticed that even after 6 times inserting a variable in a code expression or a text widget it doesn't update, however if i exit the project and reenter the new variable is there, so this appears to be a editor or sync problem, it happens in desktop apps and browser too

**Comment by agreaves** [comment]
Hi @Jhenao03, we've made some changes today that should have fixed this particular issue. Can you confirm whether it's fixed for you? If not, could you also include just a quick video? Thanks!

**Comment by paulVu** [comment]
thank @agreaves It's work now. so appreciate your support.

**Comment by paulVu** [comment]
I think I have an issue like this, but at the Deployment Source. I see the version after deploy to mobile iOS app not look like "test mode". @agreaves
