### ISSUE TITLE
FF Google search results misdirect

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3562]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi Team, 

Its a bug but i am not sure where I should have put it, hence sharing it. apologies if its wrong.

I was searching for an article on Google, here is the search link: 
https://www.bing.com/search?pglt=163&q=how+to+show+alerts+in+flutterflow&cvid=c77af4914d224590a6377f97359a5586&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQABhAMgYIAhAAGEAyBggDEAAYQDIGCAQQABhAMgYIBRAAGEAyBggGEAAYQDIGCAcQABhAMgYICBAAGEDSAQg0NzEwajBqMagCALACAA&FORM=ANNTA1&PC=LCTS

Please find 'Alerts/Notifications | FlutterFlow Docs' on the page and click. it redirects to main page, instead of the dedicated/expected search page.

Also, just a concern for creators of FF doc(off topic): new doc is not at all helpful. content wise and search wise, its not helpful for non-tech people like myself. I learned FF from old doc, if I had this doc with me earlier, i wouldnt be able to understand the FF i know today.
If you can't rollback, that's fine but please bring back the old as 'Legacy Doc' if possible.

### Expected Behavior

Search results links should redirect users to relevant pages on the FF Doc.

### Steps to Reproduce

search for a FF topic on any search engine.
look for results from official FF doc.
click on it- it would take you to just Home oage of FF Doc.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPvsdG1ZDuc8dB/TkQJUw8U508scp/bxIgGIDzPOw+ZPXsUFFWTc+5dAk6e0SmmlsJwdL1it7hMe5cNQqYQYhnwapybA/iXjuia5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

No images available

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.78+ released July 29, 2024Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2
```

**Comment by msusviela** [comment]
Thanks for submitting this. I'll send it to FlutterFlow's team so they can check on this.

**Comment by PoojaB26** [comment]
Hi @coach1990, thank you for reporting the issue! we will check this. 
About the feedback about new docs, can you please specify, what is not helpful for you 'content wise or search wise'? More details will help us improve the docs for everyone. Thanks!

**Comment by coach1990** [comment]
Hello @PoojaB26 
Ill prepare and record all cases and share it with you. I would like to say that, I completly understand the hard word and efforts you all put into creating a new doc and we all love it. Feedbacks are just a way to make products better.

**Comment by PoojaB26** [comment]
@coach1990 Absolutely, and we want the feedback from you all to improve this further! Will be waiting for your feedback note. Meanwhile, please check the same link you were trying earlier for Alerts. You should be able to open it now! Or you can always find it from the docs search (top right)
