### ISSUE TITLE
Conflicts not merging from branch to main

### ISSUE THREAD

**Issue by outerly** [FlutterFlow/flutterflow-issues#3564]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to merge our development branch (dev) into our main branch (main). I reconciled all conflicts (in favor of dev) and merged the branch, but then I go to merge the branch again and it says all of the conflicts I just resolved are now still there.

### Expected Behavior

The dev branch merges into the main branch, and then there are no conflicts upon immediate merge again.

### Steps to Reproduce

1. Go to dev branch
2. Merge dev into main
3. Resolve all conflicts in favor of dev 
4. Complete merge
5. Merge dev into main again
6. View 100+ conflicts that you just resolved

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43zf314oZ9mM9z1ZbMKMFavDk4Gnp8bZIZpdxraDYqGJToPLJ/P/TOYhZpYOmmYENhHGCLhXwKwejuvoXxJPQ6YQeaQKZGzblyVw7/e3q8RJfWCKWJe39CLJpTGX6g1KbQvREnNvpYV1IC7F2qJ+SvfDPdN5+/Zwh9f6PHaOI=

### Visual documentation

https://www.loom.com/share/aa3c865505c343569a5c31ad39aa2b0f

### Environment

```markdown
- FlutterFlow version: 4.1.79
- Platform: All
- Browser name and version: Chrome 127.0.6533.89
- Operating system and version affected: Mac OS Sonoma 14.4.1
```

### Additional Information

We can't merge our dev branch into main! This is CRITICAL to our ability to ship new features. We are unable to do so at the moment.

**Comment by Alezanello** [comment]
Hello!

I'm sorry you are facing this issue. We deployed a hotfix last night. Could you please check if this resolves your situation?

Best regards,<br>Azanello

**Comment by outerly** [comment]
I tried merging all the conflicts this morning and the same thing happened
as in the video I submitted -- none of the changes registered and I was
still stuck with 107 conflicts after reconciling everything.

Right now we can't ship any new updates because we've been doing all our
work in dev (the branch) and cannot send to main (where we ship our
updates). Can you please advise?

**Comment by Alezanello** [comment]
Hello again,

At this point, I'm lacking the right tools to help you with this issue.<br><br> I recommend you contact support directly via the in-app chat or at support@flutterflow.io for a more specific solution to your situation.

Best regards,<br>Azanello

**Comment by outerly** [comment]
This is definitely a bug and not a customer service issue.

**Comment by Alezanello** [comment]
I understand your concern. <br>However, this GitHub Issue Tracker is meant for issues that can be replicated from a new blank project. <br><br>I wasn't able to reproduce this issue from a new blank project. Support via chat or email, as mentioned in my last comment, has the right tools to address more project-specific issues and can help determine why it is not merging as it should.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
