### ISSUE TITLE
Images not appearing in APK

### ISSUE THREAD

**Issue by Adventure-Hunt** [FlutterFlow/flutterflow-issues#3565]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

APK builds appear to be no longer including assets. Build at 15.00 GMT were ok, at 1800 GMT they are not. Link to web images (Firebase) are also not appearing in the build.

The failed APK is also approx 5MB smaller than expected.

### Expected Behavior

Images should appear

### Steps to Reproduce

Open app on the first page. The should be a scroll background behind the text

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wl/H605NOmN8B15DtbcJKmiURMjs8aI0vie5TYCs8GZT0B4kcYs+kfklUOcPiT2xYemKkpGYX/MrFuN7qUMA6H0iqbIBGyqpqbxXKQXyVRLnQCYS3b3NSHedQGlyk0ZmFmQlDJtV0Slku2FymGOmXQTDfQaLXNWoRR+aeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Its really simple. Open the app. It advances to the test page (from Splash). It should have images, but it doesn´t.

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform: Android 
- Browser name and version:
- Operating system and version affected:
```

**Comment by TheDescar** [comment]
It is the same for web, assets are disconnected from the project, it says: "This asset is not directly used in this project." Even if I reupload asset - the problem persist. Please Help!

**Comment by Adventure-Hunt** [comment]
> It is the same for web, assets are disconnected from the project, it says: "This asset is not directly used in this project." Even if I reupload asset - the problem persist. Please Help!

At least its not just me. I think I will give them a few hours to resolve this.

**Comment by Adventure-Hunt** [comment]
It seems jpg images are appearing but only very few png ones. Not sure if its related to filename length or file size, though for a network asset I can´t see how that can be an issue.

The images all work fine in the build from 1500, which I reloaded to test the issue, so we can rule out the bucket that the images are sitting in.

**Comment by Dentiphoto** [comment]
Same problem.

**Comment by isegal** [comment]
This is likely related:

https://github.com/FlutterFlow/flutterflow-issues/issues/3568

@agreaves you guys are moving too fast and breaking things. I was about to troubleshoot the other iOS crash issues but now I'm blocked by this.

**Comment by FCMHUB** [comment]
It completely broke our local development after last update. We cannot use the app locally since no assets are being exported.

**Comment by msusviela** [comment]
Hello. Thanks for all the reports. So sorry you're experiencing this. Our ENG team is deploying a solution for this and this solution will be put into production as soon as possible.

**Comment by msusviela** [comment]
Hi all. The fix is already deployed. If the assets are gone in your APK, you'll need to export their APK again for the assets to show. If it's web you will need to re-publish your web app.

Let me know if you're still facing this.

**Comment by TheDescar** [comment]
Thank you, for the update, now in the web looks ok 👍

**Comment by 4SandyD** [comment]
Mine is  not fixed.

**Comment by gspassky** [comment]
I have an issue with web assets - they are working in web (test), but don't load in APK. Maybe you found the solution?

**Comment by Adventure-Hunt** [comment]
Mine is working now. I did nothing, Flutterflow rolled out the fix and it worked for me.

**Comment by 4SandyD** [comment]
Mine's not working either. It's actually telling me I have an image widget
error on a page that has no image widget. Very strange and frustrating and
Support has been silent on this so far.

**Comment by TheDescar** [comment]
Hello, mine also working, 4SandyD did you try to to Publish again or redeploy?

**Comment by gspassky** [comment]
Finally I found out that my problem exists only if I use SVG images. @4SandyD Try using jpg or png

**Comment by 4SandyD** [comment]
I'm a rank newbie. I thought Publish and deployment was for going live. I'm
working in development mode, not production. Should I try to publish anyway?

**Comment by 4SandyD** [comment]
I've uploaded both png and jpg. Errors persist.

**Comment by EduardoGascaAP** [comment]
I have this error as well

**Comment by LaVanguard** [comment]
Same issue here.
