### ISSUE TITLE
Border radius is not working

### ISSUE THREAD

**Issue by Joremando** [FlutterFlow/flutterflow-issues#3566]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to have specific border radius top and different bottom radius it doesn't work, only if I apply same value to all borders.

### Expected Behavior

Every radius can be any different number from other.

### Steps to Reproduce

1. Create container
2. Add different borders values
3. Not working, only same radius to every border.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeifHl34xOj70B0arIdMdolQMwGkQ5a7sviu5+FBQaI+KsO5oLO8zsXxdtWOqHf25tMVb8jXMG08mNv4aWLfo5Mk2ubaJD1ZZfUxDvUmSRRraRCLWwfXYnTMVMfXGB05+J2hNTNfpZZVoTwzmIDdy+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1770" alt="Screenshot 2024-08-06 at 7 48 07 PM" src="https://github.com/user-attachments/assets/a323afcc-3d77-4ee2-92f6-1eab6ac7d2fe">

### Environment

```markdown
- FlutterFlow version: 4.1.81 (today's update)
- Platform: Mac / Chrome
- Browser name and version: Chrome Version 127.0.6533.89 (Official Build) (x86_64)
- Operating system and version affected: Sonoma 14.6
```

**Comment by msusviela** [comment]
Hi @Joremando. <br><br>I wasn't able to replicate it from blank, however, I entered your project and could see the issue. I copied the widget into my project and the incorrect borders were gone. Could you try coping it into a new component and let me know if it worked for you?

**Comment by Joremando** [comment]
Yes, it works. But it's something started after I updated to the last
version.

*Thanks.*
