### ISSUE TITLE
Colours of Project are keep getting changed 

### ISSUE THREAD

**Issue by uelkuesara** [FlutterFlow/flutterflow-issues#3567]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As opening the Project the Color Theme and Custom Icons seem to disappear and the Project gets reseted to their default colors. And if I upload the Custom Icons again it keeps getting deleted

### Expected Behavior

Not changing 

### Steps to Reproduce

1. Open the Project 
2. Go to Peek for yesterday to see the colors 
3. go to project now and see changes 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Failed 

### Visual documentation

<img width="333" alt="Bildschirmfoto 2024-08-06 um 19 59 28" src="https://github.com/user-attachments/assets/b7ed10da-6196-4083-bbab-48fceac963a0">

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: MacOS Desktop
- Browser name and version: Safari Version 17.1 (19616.2.9.11.7)
- Operating system and version affected:
```

**Comment by robwilliams74** [comment]
I have exactly the same thing happening, Mac desktop, latest version .81

**Comment by agreaves** [comment]
Hi @robwilliamsav, could you add a Bug Report Code to help me investigate? If you could record and share a video that would be even _more_ incredibly helpful! Thanks!

**Comment by agreaves** [comment]
Hi @uelkuesara, could you also add the above info if you get the chance? Thanks! Hoping to fix this ASAP :)

**Comment by uelkuesara** [comment]
Hi The size is to big, I uploaded it here: https://www.transfernow.net/dl/20240807zu3XhKBx

**Comment by robwilliams74** [comment]
@agreaves I’m out today but will try… further info… just updated to .82 same issue… the colours, fonts and custom fonts / icons all reset.

interestingly you can restore them from backup, then just sit on the colours screen and wait a minute or so, and they automatically refresh back to their defaults without you taking any action…

**Comment by agreaves** [comment]
Really strange... But yes thanks for the info. I do need the Bug Report Codes for your respective projects when you get the chance though. It's crucial for me to investigate, so I'd really appreciate it.

**Comment by uelkuesara** [comment]
Hi @agreaves, there is no bug report code to copy, because the project does not show that there is a bug, at least for me

**Comment by agreaves** [comment]
hey @uelkuesara, sorry for the misunderstanding. You can generate a Bug Report Code by right clicking anywhere in the widget tree and clicking "Get Bug Report Code".

<img width="458" alt="image" src="https://github.com/user-attachments/assets/d417ee88-ad6d-4c40-8236-7b15bb41cdad">

 This just generates a string that allows us to get details on the project to help debug. Thanks!

**Comment by uelkuesara** [comment]
@agreaves I get this error by trying to copy the code 
<img width="694" alt="Bildschirmfoto 2024-08-07 um 22 20 57" src="https://github.com/user-attachments/assets/0a787cf4-2804-4fd0-abf5-30ba8d4d8a66">

**Comment by uelkuesara** [comment]
@agreaves I get this error by trying to copy the code
<img width="694" alt="Bildschirmfoto 2024-08-07 um 22 20 57" src="https://github.com/user-attachments/assets/a47d1621-ddfe-4599-bfc6-beb83a044e22">

**Comment by agreaves** [comment]
I see, you may need to enable Clipboard permissions for `app.flutterflow.io` in your Chrome (or other browser) settings. It's possible you hit "Don't Allow" when we first asked for the permission.

**Comment by robwilliams74** [comment]
IT4kkPHq4otPxd9G1c/tbcd4niQXNm4gTLJItutuZxIYfuOrBJkfOsnRakhpSOqHdGN+DlWWoEQFptGLi/HiGPA4ZBaYRYg/zJBXUxDjcES5VLaNCamWekZQTMZPG3ai5J+RmxZCAOhYcXw171y1fOyAa3qCf9qOYwx5e6fDbOY=

**Comment by robwilliams74** [comment]
@agreaves was that the right code?

**Comment by agreaves** [comment]
That's perfect, thank you!

**Comment by agreaves** [comment]
Hey folks, just pushed a change that should fix this for everyone. Sorry for the issue, and thank you all for your patience!
