### ISSUE TITLE
Impossible to use FF after update

### ISSUE THREAD

**Issue by FCMHUB** [FlutterFlow/flutterflow-issues#3569]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the last update, some users on our team can no longer use FF due to the following error:

**Project in use**
It looks like the project is being edited by another user.
Multiple users can't edit the same project at this time unless you are on the same team.

We have a team license, and everyone is on the same team, as always.

### Expected Behavior

Be able to use FF.

### Steps to Reproduce

Just open FF and try to use...

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ss+D5bZ6xtd30bXUdsIyoGAQNlAla5BEs9xBaCsofePrOpkAf8/7UFtUOLDiYEFfMGCjmnsX/Mr3uePQG/E4IQiYfKJi+JZ2bjvLXkGmabLREa63b3BAHeFXf0yd0Im3oxVCKtR1SmwH1zqEfO7IdDDUO5D1OmwvPeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="515" alt="image" src="https://github.com/user-attachments/assets/c2e3afce-a29c-4dc0-b36a-502270a3d51f">

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform: MacOS and Web
- Browser name and version: Chrome
- Operating system and version affected: -
```

**Comment by FCMHUB** [comment]
This is absolutely critical, we cannot work.

**Comment by msusviela** [comment]
Hi @FCMHUB. We're sorry you're experiencing this.<br>I was not able to reproduce this on a blank project.

I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. They can check if something went wrong with your team configuration. This tracker is only used for reproducible bugs and we don't have the right tools to check for the permissions.

Thanks so much!

**Comment by agreaves** [comment]
Hi @FCMHUB, are you still blocked? I see the cause and it looks like it may be resolved now (it was team specific). Can you confirm that you're now able to work simultaneously?

**Comment by FCMHUB** [comment]
Hi @agreaves.
We are still blocked.

<img width="241" alt="image" src="https://github.com/user-attachments/assets/46f24d30-7b58-42f5-a28a-072062e68e1b">

**Comment by FCMHUB** [comment]
@msusviela @agreaves

**Please, someone, help us!** 
We have been unable to work for 2 days. The support team started addressing our case (just today), said they would check it, and hasn’t responded for 3 hours!
Sometimes it’s possible to work for about 10 minutes, and then the message appears again, preventing us from using it.
For some reason, FF is not recognizing our subscription.
There is an active trial on our account that was granted by you, please cancel this trial to see if it resolves the issue.
We cannot remain idle for 2 days waiting!

**Comment by monocat** [comment]
My issue could be related as well. I think there's something off with the latest updates.

https://github.com/FlutterFlow/flutterflow-issues/issues/3574

**Comment by FCMHUB** [comment]
The support team (at our request) canceled our subscription, and we renewed it. So far, we haven't had any more issues.

**Comment by FCMHUB** [comment]
No issues after 2 hours of use.

**Comment by msusviela** [comment]
Thanks for the update!
