### ISSUE TITLE
Web publishing run extremely slow than run mode

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#357]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The app is running so slow on a web publish

## Current behavior (required)

Should run as run mode (fast and smooth)

## To Reproduce (required)

1. Go to Web Publish and publish it
2. Go to Run mode and run it
3. Compare the speed and the smooth and you see the run mode is very faster and smooth than web publish

### Bug Report Code (required, generate from Widget Tree)

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp14BpuzFvezDDO44JgStftVg/7oNahWXXlymVL3fU/HUACkbeacOQSj6

## Context (required)

My big problem is the same as this user of the community:

> I can not introduce my site to anyone because afraid of the speed performance of my web after publishing to subdomain.flutterflow.app (or main custom domain), while it is working and scrolling smoothly on FF default run mode.

Some post from community:
- https://community.flutterflow.io/c/discuss-and-get-help/web-on-subdomain-flutterflow-app-or-custom-domain-extremely-slow-laggy-but-very-fast-and-smooth-scrolling-on-default-run-mode
- https://community.flutterflow.io/c/discuss-and-get-help/web-publishing-on-custom-domain-is-slow

## Screenshots / recordings

N/A

## Your environment

* Version of FlutterFlow used: 13 January
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 108.0.5359.126 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 Pro - 22H2 - OS build: 22621.1105

**Comment by Pepino-GR** [comment]
@victoriahuang1
Hi Victoria,
 I think this is to validate by the FF Team

**Comment by aemelyanovff** [comment]
@Franco98404 Thanks for reporting the issue. Can you add a run mode link and a published link for the project where you experience the issue?

**Comment by Franco98404** [comment]
Yes, here are the links.

https://schoolfy365-dev.flutterflow.app/
https://app.flutterflow.io/run/Kd6tvLMXa1vPM7yimdv1

Probably you need the credentials to enter the app, in this case, where can I share the credentials privately?

**Comment by aemelyanovff** [comment]
It would be very helpful if you could create another project that does not require auth, ideally with only one page :-) I'm reluctant to troubleshoot a big existing project I know nothing about.

I don't see significant difference in scrolling performance between web publishing and run mode in my projects.

**Comment by Franco98404** [comment]
Bug Report Code:
IT5TzPHlwItPvttZ1rrUY8JB/WIWCDs2bYJJlu1+GBMjHOvrBIYqOsnBbXFIOsukTHNYPWGi8Xgz086Kk+P1DcEHPiiBf74+/qtpWxbwLT2Qb4SaCpeRdnElTdJPN3HLlePx+VcFfJIrDwREnhvSXw==

https://web-publish-vs-run-mode-neyyui.flutterflow.app
https://app.flutterflow.io/run/4ShABpqOaTPdvAeDEdxt

Especially on Android the web page run so slow, I have and good smartphone but the experience is very laggy. Instead, the native app works smoothly.

**Comment by aemelyanovff** [comment]
Thanks for the info!

Both links are about equally laggy on my machine actually... And the reason they are laggy is that you load 50 images over the network, each image is about 1MB. This will be slow, especially if the internet connection is not great. Once images are loaded, everything scrolls pretty fast.

One thing you can do is set width and height for the random image. Then image sizes transferred over the network will be much smaller, and everything will load much faster.

![Screenshot 2023-01-23 at 2 59 35 PM](https://user-images.githubusercontent.com/92294640/214138112-a22e5284-d5a2-4b40-aa8c-2b9e7e4b5718.png)

**Comment by Franco98404** [comment]
@aemelyanovff What about Android? After the images are loaded, they are still laggy.

Thanks for your advice, I will apply it!

**Comment by aemelyanovff** [comment]
> 

Native apps will always run much faster than web apps. I don't have an Android device to verify - I can only try in an emulator and it's pretty much always laggy - but I don't see evidence that web publish to subdomains runs noticeably slower than run mode, so I'm closing this ticket.

My best advice here is to reduce the size and/or the number of images on the page, then it should be faster.
