### ISSUE TITLE
One of my projects can't import any packages, other projects work fine. "uri_does_not_exist"

### ISSUE THREAD

**Issue by smerkley** [FlutterFlow/flutterflow-issues#3571]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In all custom code on one of my projects I get errors like the following:
```
Target of URI doesn't exist: 'package:flutter/material.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
```

Other projects of mine work fine, and this one used to work fine until this started happening. I duplicated the project and the duplicate works fine.

### Expected Behavior

Packages should import

### Steps to Reproduce

Create new custom code on my project, attempt to compile code, it fails

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klfLqx5N1xLQB1pPpbe1V9TkvC0c4TL07ttYbZxUjIuPtBJh+PuP4SxdWZOLjdFNhHGaIklwd0fz4v+GfUvADNSiefIBc+M9uYRfxXXq8SrakCs6wR0ZSGfxWG36n0LSnoiVCPupacV447E2QBui/VjPqN5O/Zwh9f6PHaOI=

### Visual documentation

![Screenshot_20240806_125819](https://github.com/user-attachments/assets/3bd727b4-98c6-42e8-a52f-22a3f9dc4dd5)

### Environment

```markdown
- FlutterFlow version: v4.1.81+ 
- Platform: Web
- Browser name and version: Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) unknown (64-bit)
- Operating system and version affected: Fedora Linux 39
```

**Comment by Alezanello** [comment]
Hello!

The error in your custom code is not related to the package, although it may show as red or missing. The issue is in the sort function. It seems to be due to the lack of null safety, which might lead to a nullable return. You may need to fix that to make it functional. Try something like this:

```dart
switch (sortIndex) {
  case 0:
    listToSort.sort((a, b) => a.id?.compareTo(b.id ?? 0) ?? 0);
    break;
  case 1:
    listToSort.sort((a, b) => a.itemName?.compareTo(b.itemName ?? '') ?? 0);
    break;
  case 2:
    listToSort.sort((a, b) => (a.perishable ?? false).compareTo(b.perishable ?? false));
    break;
  default:
    break;
}
return listToSort;
```

<br>I don't say that this snippet code will work but you may try it and change according of your needs!

Best regards,<br>Azanello

**Comment by smerkley** [comment]
Thanks you're right it was a null safety issue. Very strange how it caused the other errors in the import statements, even across other custom functions, and when I duplicated the project the import errors didn't show up right away.
