### ISSUE TITLE
My web app is not rendering lottie animations after published today

### ISSUE THREAD

**Issue by brunomeneghel** [FlutterFlow/flutterflow-issues#3572]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My web app is not rendering lottie animations after published today, with an yellow warnig simbol replacing it

### Expected Behavior

Lottie animations should work properly

### Steps to Reproduce

Acces app.somosunit.com.br, create an account and see the error.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzsnf5c9goctH176Jd/oxgWUvOUccTpAFlOthcwgjGpzrP4l3Z8nRalRuZryqSnxbM1m0pHk1xvfqjoXlKvZfNgeZY4hnzs9qFAv/ZGenRYiXBauNfW1fN+ZMGFyv4ba3hglDOtZZWC1n62GHOOzIFnPBNYzvOjIjFvyLKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/f4b521e9-0768-49a9-9077-6e5306182ea5)

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform: Web
- Browser name and version: Chrome 127.0.6533.89
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hi @brunomeneghel, sorry for this issue! This should now be fixed if you redeploy, can you confirm? Thanks.

**Comment by brunomeneghel** [comment]
Yes, it's ok now! Tks!
