### ISSUE TITLE
MAJOR Caching, Bottom Sheet Dismissal, Navigate To issues after upgrades

### ISSUE THREAD

**Issue by monocat** [FlutterFlow/flutterflow-issues#3574]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Was experiencing issues on my main project all day. Just tested on a fresh project, the issues persisted. When testing, previous saved versions are loading. Regardless, experiencing issues with Bottom Sheet Dismissals and Navigate To actions. More details about issues of main project is posted in the community: 
https://community.flutterflow.io/ask-the-community/post/bottom-sheet-dismissal-navigates-to-previously-viewed-page-6Lqi1MQvzDQZCKM

### Expected Behavior

Test should show latest changes. Bottom Sheet dismissal to just dismiss without navigating to previous viewed page. When button clicked to Navigate To a page, it should.

### Steps to Reproduce

- Create new project
- Add button and apply Bottom Sheet open/dismiss actions.
- Add button with action to Navigate To another page
- Test actions
- Change button locations and run test again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsmB289OxL1E18/QdflanSQQKXohUOYNlspBZywgfZzzBLN/fPfQP0loOM+qTHw3ImKcp14K+tL1vYfhMfEVF06sQLp9+alhExb/UniiM72TF7rhQH96L99NChXD06SVhBZCKtNeSlom2DqmF+yWVgjUQoTFIEQ4Sq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/da9183bc-613c-421c-923c-1a5f5724172b

### Environment

```markdown
- FlutterFlow version: 4.1.81+ (web) 4.1.82 (macos desktop app)
- Platform: Mac
- Browser name and version: Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (x86_64)
- Operating system and version affected: MacOS Sonoma 14.5
```

### Additional Information

Couldn't do much all day. Couldn't test new updates. Received two (2) updates on MacOS FF desktop app. Issues persisted.

**Comment by agreaves** [comment]
Hey @monocat, thanks for the report! Regarding the syncing issue, I think there might be some confusion about which page is being updated, since you have both a `Home` and `HomePage` page, and I believe you may be editing a different one than what is displaying in the Test Mode page.

But it sounds like there's another navigation issue here with Bottom Sheets? Could you add any additional information about that? We're happy to investigate and get to the bottom of it. Thanks!

**Comment by monocat** [comment]
Hi @agreaves Thanks for chiming in. The issue resolved itself the following day. I believe it was some kind of caching issue during the recent FF updates. Either the active cache wasn't "transferred" or there was a delayed cron job. I'm no dev, but that's my best guess. I'll leave the issue open for you to investigate, unless you think it was a one-off thing—in which case, feel free to close it.

By the way, I'm really enjoying building with FF. It took me a while to find a tool that would help me build something on my own with decent control to extend it to my liking. I'm excited to see what I can create!

UPDATE: Noticed how this was resolved. Soooo, cache 🤷 😁 
https://github.com/FlutterFlow/flutterflow-issues/issues/3569

**Comment by msusviela** [comment]
We're closing this issue since it was solved. Thanks for the update!
