### ISSUE TITLE
Cant deploy app

### ISSUE THREAD

**Issue by EduGod0y** [FlutterFlow/flutterflow-issues#3576]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been trying to deploy my app multiple times to testflight with different app versions and build numbers and all of them "successfully" work but the new version dont appear in the App Store Connect 

### Expected Behavior

I expect when its finish to appear on the AppleStore connect

### Steps to Reproduce

1. Deploy to App Store

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx892pbwF1s7tbflFmioWMjsnaOYRk9VueCs9GYjyO5YUaeOldlFCTd/kTXNlKEWJmnkBzOiNuITuFfpfIk2cQaU6ybVUFz3gfDm/aouYPpbhOXNTEcZWfmqd0LaZmwlSVfBuLk4g7V+AIt+uZBTcNZf7Zwh9f6PHaOI=

### Visual documentation

![Captura de tela 2024-08-07 111048](https://github.com/user-attachments/assets/fb37a5d4-5a97-4b6d-9f19-12d46a80abe9)
![Captura de tela 2024-08-07 111023](https://github.com/user-attachments/assets/699ebdaa-40fa-4117-896b-bc332246e4dc)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

This issue goes beyond the FF playground as the app is already deployed to the App Store. Since the time you created this issue, does the latest app deployment show correctly in App Store Connect?

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
