### ISSUE TITLE
Flutter flow performance - Chrome

### ISSUE THREAD

**Issue by sapostu** [FlutterFlow/flutterflow-issues#3577]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the Flutter flow computer application, performance is fine and everything works. When I use Flutter flow on Chrome, the platform barely works at all. For some reason, chrome Flutter Flow performance is inferior than the app version. This has been a consistent issue since the latest updates. It wasn't like this before

### Expected Behavior

Chrome and App. versions of Flutter Flow work the same.

### Steps to Reproduce

None. Read what I read above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkfLluJNgoeFd0a6JKMFolj04QmkcTIMziNZ+exUbfaL1Buw2euLOTExtYMe9aVNfemKgoEcGpdKNuISWA8ABHwuCG6lx1Lp+bwnOe2inMrKNDbi0OWhPGplYC1SF5p+joRQnXelucixg2zuUHuq9TXLDBOu/Zwh9f6PHaOI=

### Visual documentation

None. Read what I read above. The chrome version of flutterflow just sucks with performance.

### Environment

```markdown
- FlutterFlow version: latest version
- Platform: Chrome, mac app
- Browser name and version: Chrome
- Operating system and version affected: Chrome
```

### Additional Information

Chrome version of flutter flow just sucks to use. makes me consider my membership

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. There haven't been any recent changes that should directly affect FlutterFlow's performance in Chrome. Could you please share the RAM usage of the app by hovering your mouse over it to show how much RAM FlutterFlow is consuming on your end?<br><br>Like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/68a8febd-c31f-48b4-b309-e2b356091571/d06c68d1-b8f4-4fc5-b2fb-be770f78fcf5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82OGE4ZmViZC1jMzFmLTQ4YjQtYjMwOS1lMmIzNTYwOTE1NzEvZDA2YzY4ZDEtYjhmNC00ZmM1LWIyZmItYmU3NzBmNzhmY2Y1IiwiaWF0IjoxNzIzMDY3MjI2LCJleHAiOjMzMjkzNjI3MjI2fQ.kxx8XGuqHpH36fWiozeqGnCejT5UJyOQe2ETteW6qw8 " alt="image.png" width="321" height="185" />

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
