### ISSUE TITLE
Super slow performance using the editor on web.

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#358]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Should work very fast and smooth, like when start a new project

## Current behavior (required)

Super slow performance using the editor on web.

## To Reproduce (required)

1. Do anything in a big project on FlutterFlow

### Bug Report Code (required, generate from Widget Tree)

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp14BpuzFvezDDO44JgStftVg/7oNahWXXlymVL3fU/HUACkbeacOQSj6

### Most common user's problems from different posts:

> My project has 70 pages, and each mouse click takes about 8 seconds

> I experience similar issue on projects with more than 15 screens. Switching tabs to other webpages loads & navigates smoothly but returning to FF builder it takes more than 5 seconds for an action to respond.

> going up and down the widget tree is really slow, and the scaffold panels are slow to render.

> When you have e big action workflow that's worse

> Click..1...2...3...4 THEN the action/response occurs. No matter which action it is. It is so motivation robbing and super unproductive.

> It seems that flutterflow just can't work with projects with lots of pages and actions.  

> It feels so bad, its like working on a 4gb Intel Pentium 2 Pc ;( I thought these times are gone!

> Today all pages (with few widgets) are very slow and sometimes the page crashes.
> I already cleaned the cache and restarted the pc. But, it continues slowly.

> I have the same problem in my account and client account 

> Simple changes such as adjusting the padding might take 20-30 seconds to be reflected if at all

### As you can see a lot of users have a good computer

> All of my laptops have 32gb {thinkPad 10 year edtion} My rig has 64gb, the RTX3090 , 1000Mbits connection and I have the same performance results that you have. 

> I have an i7 9700k, 32GB RAM, and RTX 3090 (I think it isn't being used) and I have a lot of lags

> I have a lot of pages with many actions and api calls and my browser cant handle it, even though the ram usage wont reach its limitations. (I7 7700k, 16gb ddr4 etc.)

> Processor: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz, 3000 Mhz, 6 Core(s), 6 Logical Processor(s)
> Installed Physical Memory (RAM) 16,0 GB

> My whole PC is unstable in the meantime, despite only running chrome, having GPU acceleration, 4GB VRAM, 16GB RAM.

> Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz 2.11 GHz
> 16.0 GB (15.8 GB usable)

> Performance is generally slow for me on my 2019 Intel i9 MacBook Pro.

### I tried to find some posts from community about this problem:

- https://community.flutterflow.io/c/bugs/unbearable-3-5-second-lag-on-larger-projects
- https://community.flutterflow.io/c/bugs/slow-browser-performance-when-editing-in-ff
- https://community.flutterflow.io/c/discuss-and-get-help/brave-lag
- https://community.flutterflow.io/c/discuss-and-get-help/big-lag
- https://community.flutterflow.io/c/bugs/insane-lag-after-update
- https://community.flutterflow.io/c/suggestions-and-feedback/chrome-lagging-on-windows-not-mac
- https://community.flutterflow.io/c/community-tutorials/observation-lag-on-longer-pages-with-nested-widgets-workaround
- https://community.flutterflow.io/c/bugs/the-amount-of-lag-is-insane-and-makes-it-almost-impossible-to-work
- https://community.flutterflow.io/c/bugs/suggestions-for-reducing-builder-interface-lag
- https://community.flutterflow.io/c/discuss-and-get-help/editor-going-slow
- https://community.flutterflow.io/c/bugs/slow-problem
- https://community.flutterflow.io/c/bugs/slowing-issue
- https://community.flutterflow.io/c/bugs/since-the-update-insane-slow
- https://community.flutterflow.io/c/discuss-and-get-help/slow-problem-for-windows-users-like-me
- https://community.flutterflow.io/c/bugs/ff-slows-down-when-project-grows
- https://community.flutterflow.io/c/bugs/slow-while-moving-mouse-on-any-widget
- https://community.flutterflow.io/c/bugs/slow-browser-performance-when-editing-in-ff
- https://community.flutterflow.io/c/discuss-and-get-help/unusable-flutterflow-editor-dashboard-frustrating

## Screenshots / recordings

See some posts from above with videos
https://community.flutterflow.io/c/bugs/insane-lag-after-update
https://community.flutterflow.io/c/bugs/the-amount-of-lag-is-insane-and-makes-it-almost-impossible-to-work
https://community.flutterflow.io/c/bugs/suggestions-for-reducing-builder-interface-lag
https://community.flutterflow.io/c/discuss-and-get-help/slow-problem-for-windows-users-like-me
https://community.flutterflow.io/c/bugs/slow-while-moving-mouse-on-any-widget
https://community.flutterflow.io/c/discuss-and-get-help/unusable-flutterflow-editor-dashboard-frustrating

## Your environment

* Version of FlutterFlow used: 13 January
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 108.0.5359.126 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 Pro - 22H2 - OS build: 22621.1105

**Comment by Franco98404** [comment]
I think these issues can be related to this one:

https://github.com/FlutterFlow/flutterflow-issues/issues/357
https://github.com/FlutterFlow/flutterflow-issues/issues/222

**Comment by cleanspacedev** [comment]
I have been dealing with slow performance  for a while. It seems to be linked to how many objects you have in a page and how many actions you have linked in the page. 

I also think there may be a small memory leak or something similar,  such as it is not scrubbing the cache when you switch from page to page. After a while, it crashes for me, with "Not enough Memory" and I have to refresh and reload FF. 

I am running the latest version of Chrome, and I am on a 2021 Gamming PC, with plenty of memory. 

This may be a limitation of Chrome, although, I do not think they memory cap tabs anymore, (I have looked into it). 

The quick testing option works pretty good, it does take much longer then the 2 minutes suggested, but it makes since if your project is large. 

All in all, if there is something that can be done, please let us know, or simply tell us, it is the limits of Chrome,. Maybe the FF desktop app could be better. Although, when I last looked it was just an extension of Chrome also.

**Comment by Franco98404** [comment]
About this "Not enough Memory". It happens to me and I have 32GB RAM so that is so strange. Maybe it is about the Chrome limits that you said.

Using Chrome is unusable because it is very slow. With my team we took the decision to switch to Brave, that is not unusable like Chrome but is very frustrating anyway.

Unfortunately, the Instant Reload takes more than 2 minutes (10 seconds is supposed the expected). Is very slow and produce unproductivity as said [@thruthes](https://github.com/thruthesky) in his issue: [#222 - Instant reload takes too much](https://github.com/FlutterFlow/flutterflow-issues/issues/222)

**Comment by Real-Experienes** [comment]
Thank you Franco for creating this Issue on here. This has been a persistent issue for over a year now. The reaction/response time seems to be holding steady at around 4 -7 seconds. Regardless of which browser I use the performance is the same.
I am so frustrated that I am now thinking of breaking down and purchasing a MacBook Pro--even though I cannot truly see this alleviating the problem. I hope that FF takes some corrective actions soon
.

**Comment by OldFred2023** [comment]
I use a high performance windows workstation 96GB RAM,  Dual i7 (16 cores), with the latest version of chrome, over a 900gb internet connection, so it isn't hardware, even Visual Studio is fast.

The editor i have to wait a few seconds for the editor to respond to a click in the widget tree.

The debug session is dreadful, i have to wait 6-8 minutes for it to start, and the instant reloads is about 2 minutes.... 

Performance is the one thing that will push me away from using FF for other projects.

**Comment by sl985** [comment]
I've Xeon E3-1120 v3 3.1Ghz, 32GB RAM, Windows 10. The standard load generated by flutterflow is 7-15% CPU, but when I open "Set from Variable" and choose "Code expression" CPU load increase to 44-60% - the FF application interface then also lags. This is a new feature, and I suspect it may require some small optimization.

In general, the FlutterFlow application sometimes lags, but it is usable all the time (the largest application has about 15 screens). Has anyone tried running FF on an Apple with an M1 or M2 processor? If so, does it run more responsively?

**Comment by aemelyanovff** [comment]
Web editor performance indeed is not great. We are planning to work on this in the near future.

If you experience poor web editor performance, please reply with:
* A link to your project (if you don't want to share it publicaly - generate a Bug Report Code from anywhere in your project)
* What exactly is slow (dragging widgets, updating properties, scrolling widget tree, etc.)

In the meantime:
- If you have a Mac, use our desktop app - it's much faster.
- Try to reduce the size of the project. For example, if you have several similar pages, try to extract the common part into a component.

Also, test/run mode startup and web publishing performance are entirely separate issues.

**Comment by Franco98404** [comment]
I already shared my Bug Report Code but I leave it here again
IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp14BpuzFvezDDO44JgStftVg/7oNahWXXlymVL3fU/HUACkbeacOQSj6

In our case, the entire project is slow, there isn't a specific part, whatever you do is slow, but when more time spend on the editor is worse, so I need to close the browser and open again and works better.

At the beginning:
![image](https://user-images.githubusercontent.com/36147203/213338548-b5f4baa1-03e7-4b20-b0f1-46786f814989.png)

After 30 minutes:
![image](https://user-images.githubusercontent.com/36147203/213338530-8f3c13ee-d40b-462e-a706-217db0d0dde1.png)

> We are planning to work on this in the near future.

Sorry to be anxious but can you provide a more specific date or month?

**Comment by funtikar** [comment]
Hi,
I have a **feeling** there are two camps in the slow performance / lag issues of FlutterFlow.

**1. Windows/Browser bug**
(Only windows user experience this) 
this one is insanely laggy , even just drag and dropping elements in and an empty project will already show the lag.

**2. The generally slow FlutterFlow** 
(MacOS users and those few lucky Windows users)
this doesn't have the issue in 1. but people generally feel FlutterFlow is slow, some people just ignore this because mainly it still works.


### Hi , this is my dual boot Intel 4th gen i5 machine
![Screen Shot 2022-12-16 at 11 15 27 PM (2)](https://user-images.githubusercontent.com/3684644/213355816-e754fab4-6b59-4b7a-9f4f-97f5ac26c033.png)

I have both MacOS and Windows installed on here with it I experienced both issue no 1. and 2.
** Using the native app on MacOS is definitely smoother in UI and responsiveness but the workflow of opening a new Chrome tab is better if you are working in Chrome itself

**Comment by aemelyanovff** [comment]
> Sorry to be anxious but can you provide a more specific date or month?

We are some performance improvements in the next release, but I can't say when it'll happen at the moment. I also can't guarantee how much difference it'll make to you - it depends on many factors: the project, the usage, the machine...

**Comment by aemelyanovff** [comment]
We released a number of performance improvements today. It's still far from perfect, but better.

If you experience slow FF UI builder performance, please report it either using the built-in feedback form or on https://community.flutterflow.io/ This issue tracker is not the best place for it.

**Comment by funtikar** [comment]
wow its ACTUALLY fixed... thanks @aemelyanovff and team.

**Comment by Eloks7** [comment]
@aemelyanovff Please I am still having the same performance issue above and I am using a good PC that isn't being used to capacity.

I use a windows PC and Brave browser, please help. Something similar to the problem here [Franco](https://github.com/FlutterFlow/flutterflow-issues/issues/358#issuecomment-1396351641).

**Comment by Real-Experienes** [comment]
Hi Eloks, Chrome is the browser of choice when using FluterFlow. Brave is a great, powerful browser though.
Unfortunately the issue you are experiencing will not be properly addressed adjusted or corrected any time soon as the Devs, clearly, do not care about non-apple users. It seems that their servers are not powerful enough and they are in over their heads or they could simly not care less about the concerns of non-apple users. It is as simple as that. 

I am very sorry dude but do not expect any meaningful assistance from the FF Devs on this issue.

**Comment by Eloks7** [comment]
@Real-Experienes I am using Brave because Flutterflow has lots of issues running on Chrome on my PC.

Having an OS bias doesn't make any sense at all.

**Comment by Eloks7** [comment]
I still need help on this issue.

**Comment by Franco98404** [comment]
@Eloks7 I would recommend that you contact support and send the link to this issue for a response. Unfortunately, they take a long time to respond but at least you have an answer about your problem, maybe FF has a plan for this issue in the near future and you can share it with us here
