### ISSUE TITLE
Tab bar doesn't show inital tab properly

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#3580]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page with a tab bar and always load at tab of index 1, the second one. I want oit to open with the index 0 tab. I read the documentation and made what is informed, I put 0 at initial tab index in the configuration but it doesnt work. BTW, this page came from a template of yours.

### Expected Behavior

I want the page to load and show tab 1 (index 0).
![Screenshot_1](https://github.com/user-attachments/assets/294bd1b3-e239-417d-9156-6d7ca1bec03f)

### Steps to Reproduce

0- Open my app in Flutterflow named PetStars
1 - on logged initial page click on any of the two Pet images
2- on the next page click on the user container
3- you are in the problem page, see the tab from the right is the initial, should be the left one
![Screenshot_2](https://github.com/user-attachments/assets/773314b6-9d50-4656-8d38-db601a6d321c)
![Screenshot_3](https://github.com/user-attachments/assets/874afe34-f51b-4c10-8d27-2a8818425a8d)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPHq2491xLRF+KnxYcFarygUCUMfX5I7i95EZwEhfJTmOuwyec7eVxJLYtekdGNUP06InXIywt7WiIbhU/Q7ByqBR7pEyIRXQRaXbHuVRpi7DKu0YmpRN/1NBWKYyJivqgpQC7dsW1IO61OqO/CrG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot_2](https://github.com/user-attachments/assets/ab06b28e-5a67-47c9-9529-d2857d07228b)
![Screenshot_3](https://github.com/user-attachments/assets/8904d9c1-700f-4037-8684-e338c619f218)

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform: dont know
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment]
Hello!

I just checked your project, and on the page you mentioned, the tab index is set to 1, which means it opens the second tab as expected. You need to change that value to 0 to open the first tab when the page loads.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/75de9ae3-2a21-4f17-a4af-364aaffba442/640c4f24-0d94-4395-ad2b-249d0c57df0a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NWRlOWFlMy0yYTIxLTRmMTctYTRhZi0zNjRhYWZmYmE0NDIvNjQwYzRmMjQtMGQ5NC00Mzk1LWFkMmItMjQ5ZDBjNTdkZjBhIiwiaWF0IjoxNzIzMDczNjE3LCJleHAiOjMzMjkzNjMzNjE3fQ.2FlZfJuuN4Grt-9H3tiSaJYIjl5QKPB0NqGUi5fHjPc " alt="tabindex.gif" width="1113" height="762" />

Best regards,<br>Azanello

**Comment by ghost** [comment]
Thank you Azanello, I see the problem now, I was editing another identical
page and expecting results in this one.
Sorry for taking your time and thank you for helping,
