### ISSUE TITLE
Database connection to auth users list

### ISSUE THREAD

**Issue by Basely-dev** [FlutterFlow/flutterflow-issues#3585]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when trying to create an action that uses information of the authenticated user the list is not populated with the fields of the database. i regenerated the config files for fire2base and that didnt resolve the issue, i have 37 errors each of them use data grabbed from the authenticated user dropdown

![image](https://github.com/user-attachments/assets/3c7e6a4b-20b2-499a-ac56-5aa417358423)

### Expected Behavior

![image](https://github.com/user-attachments/assets/36513293-fc3d-4b1b-b5c9-746ebdf1b2a8)
should be populated with fields of the database but is just set for default

### Steps to Reproduce

im not quite sure

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlvLqx5NOvuZE15DXK8EwuD0wFjMMbY0v0u0bFB4YIu/uEIoQfuD4X0NKTc/ieWNYJFf9uGMKwtLvkYT1LvI5NkybR6Z70JVAcQrwIX2RR5SpBZCeVH97BeRPFWWB18Co3RYnXbN1ZVllwDmbN63qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

no idea how it happend

### Environment

```markdown
- FlutterFlow version: v4.1.81 (released aug 7, 2024)
- Platform: web
```

### Additional Information

this issue has halted the entire applications production as nothing can be tested without these actions, and that hinders my educational progress

**Comment by Alezanello** [comment]
Hello!

To resolve this issue, please try activating the "Users Collection" toggle in your Firestore settings. Let me know if this fixes the problem!

Best regards,<br>Azanello

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/21eb4512-5234-46cd-9e13-9a2b12e15e1a/a543e027-a9bf-4d32-b024-5297e28b6a17?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMWViNDUxMi01MjM0LTQ2Y2QtOWUxMy05YTJiMTJlMTVlMWEvYTU0M2UwMjctYTliZi00ZDMyLWIwMjQtNTI5N2UyOGI2YTE3IiwiaWF0IjoxNzIzMTIyOTc2LCJleHAiOjMzMjkzNjgyOTc2fQ.9ByJcFJoZyklb4O31sajiDjnJTqFFYjKCqTvAxDcEGs " alt="image.png" width="1117" height="850" />

**Comment by Basely-dev** [comment]
@Alezanello thank you that did work, the only reason we couldn't find it is because no one had touched that hence the confusion

**Comment by Alezanello** [comment]
I'm glad it worked!<br><br>Time to time the project may desync and cause this, we are working to prevent this for happening, we are sorry for the inconvenience
