### ISSUE TITLE
Navigation will not work in Run or Test Mode

### ISSUE THREAD

**Issue by tdefrancisci** [FlutterFlow/flutterflow-issues#3586]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot get my app to navigate when in run or test mode. It does work in preview mode.

### Expected Behavior

When the app is in run or test mode, I expect it to function as normal. I would like to be able to click on the buttons I have put in and the app bring me to those pages associated with the buttons. 

### Steps to Reproduce

I have followed these steps and found that the test page does work, however my app does not.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkPLq+Yt1rtxE15D2d/lVoCgwGUwbUOc7j9VEGAsjCePsPaQMZuLeYlNVcuqHY1dMPWKZkmAdpc7FieLxLPYEYDSZY6p6zbtbUxDgQXGRVLa1Bai0On99N/hMI2KmyqSRuh1NLsVpWi0jwDv7Gu6+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

I have tried to show this through a video and screen shot.
![Screenshot 2024-08-08 104102](https://github.com/user-attachments/assets/d51869ff-5e24-4d97-9be3-b0c0e1163438)

https://github.com/user-attachments/assets/d81a8b40-ae50-4cfb-8883-607e183ecd59

### Environment

```markdown
- FlutterFlow version: v4.1.81+
- Platform: Web and desktop app
- Browser name and version: Microsoft Edge 127.0.2651.74
- Operating system and version affected: Windows 11 v22H2
```

### Additional Information

When I was attempting to publish this app to the Apple Store, I was informed by the development team that it is not functional. I would like this to operate as intended so I can get this in the hand of my employees.

**Comment by Alezanello** [comment]
<br>Hello!!

I noticed in your project that there's an "On Page Load" action set to navigate to the same page you're currently on. This creates a loop where the HomePage keeps reloading itself repeatedly.

I suggest removing this action to see if it helps resolve the issue.

Best regards,<br>Azanello

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2c3555dd-06c1-4430-9a57-2b7db707d13f/d535906a-6350-4ddf-be61-c2e73661ed26?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYzM1NTVkZC0wNmMxLTQ0MzAtOWE1Ny0yYjdkYjcwN2QxM2YvZDUzNTkwNmEtNjM1MC00ZGRmLWJlNjEtYzJlNzM2NjFlZDI2IiwiaWF0IjoxNzIzMjA1ODQzLCJleHAiOjMzMjkzNzY1ODQzfQ.FAOjaRQthFNrW81g5cxHomSzyciOQDtbSmk_qVVhJlc " alt="image.png" width="1115" height="770" />

**Comment by tdefrancisci** [comment]
Alezanello,

That worked! Thank you very much.
