### ISSUE TITLE
Preview App, option misdirect

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3588]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I preview any page through 'Preview App' option and, come back, the control takes me to Widget palette and some random page. It takes away 5-10 seconds from the Back button press. also, if we have so many pages with different names, it takes more seconds to find that page in the list. If it's not too much trouble, can we correct this behavior please?

### Expected Behavior

If the control can take us back to the same original page, of which we wanted to see the preview in the beginning. that would be great. thanks

### Steps to Reproduce

create atleast 10 pages (enough so we can see the pattern of page lock when we come back)
Click on Preview App option on any random page. (if any from the bottom, the better)
Click on your Project Name, while you're on the Preview Page.
Once, you are back on the Canvas. You would see Widget Palette first
Go to Widget Tree section
Here, you would have to find the same page, you were on earlier.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPvsdG1ZDuc8dB/TkQJUw8U508scp/bxIgGIDzPOw+ZPWkXFBpYNe/Smw7OESmmnMD+Oj8jezXD/JeORasfb5lzod+SwvKWTuQUZOBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

Uploading Untitled video.mp4…

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.82+ released August 7, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2
```

**Comment by coach1990** [comment]
Video link: https://github.com/user-attachments/assets/e6362107-80e6-4703-a4c7-ac9a62ddaab3

**Comment by Alezanello** [comment]
Hello!

I understand this might be a bit confusing. When you click on "Preview," it opens a new tab, and when you return to your project by clicking the button, it doesn't navigate to a random page—it actually takes you directly to the page you’ve set as your Entry Page in the settings.

To clarify, I’ve created a video to visually explain how this works. Apologies if my English isn't perfect; it's not my native language!

[BugProject - FlutterFlow - Google Chrome - 9 August 2024](https://www.loom.com/share/ba322c7f3f254cc780ce2c1005d75120)

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
