### ISSUE TITLE
Set color by variable released on 5th October is incomplete

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#359]
The October 5th 2022 release had set colors from variables, however it is not complete, as:

- The set color by variable on dropdowns are ignored (bug)
- Colors in snack bar cannot be set by variable
- in the choice chip control, you cannot set the color by a variable 
- The Icon widget color cannot be set from a variable 
- cannot set page background color by variable

Its only a half of a solution that has been implemented, and so kind of pointless unless an entire App can be customised with variables, this is limiting the amount of customisation and therefore limiting the use of FF as a suitable platform for high end customised apps.

**Comment by wenkaifan0720** [comment]
Hi @OldFred2023. The set color by variable feature was focusing on the most frequently used widget properties. And we will update this feature in the future with support for more widget properties. 

As for the bug regarding the dropdown widget, I can confirm that this is a bug and will push a fix soon. 

Thank you!

**Comment by katherineqian** [comment]
The feature requests made in this issue have been addressed and should be deployed in the next couple of versions.
