### ISSUE TITLE
None of my to components in my Bottom sheet component Display in running or editing mode

### ISSUE THREAD

**Issue by mepowerleo10** [FlutterFlow/flutterflow-issues#3591]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Yesterday my bottom sheet was showing with no issues, but suddenly later when I opened the component it shows a white empty bottomsheet component, while in the widget tree I can see the components. When I select the widgets straight from the widget tree or edit them in any way, all my changes get reset immediately.

Further inspecting the network logs, all I get is a stream of network calls to `registerEvent` in the networks tab. Here is a 

### Expected Behavior

I should be able to make changes to my widget tree items, and the components in the widget tree must show in the preview window.

Also, if there's any error occurring some message must be shown. Silent debugging wastes a lot of development time.

### Steps to Reproduce

1. Open the `CustomerSearchSheet` component
2. Try Changing anything in the widget tree
3. Nothing gets displayed or the changes reset and a loop of `registerEvent` calls is seen in the network inspector

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lMrZuJF1oeVd4arybsBuoycRJn4ubLsruu17aCsofePrOpkAf8/7UFtUOcjhdEFiMWegpGcX/MrevYTtM+03OTGbGZRO/5BUUwmWfHygRJSJPb63b0dtM9tNGUDG4Zm3kR1DPvVsS1og21ymI+euTh/YJZD6DFgzA+aeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/8f2bab08-7e6d-4807-8f3f-b32fed4f51d1)

When I run the app and open the bottom sheet, this is what I see
![image](https://github.com/user-attachments/assets/15d57b40-01f2-4ef1-9ded-c208a936dc0b)
When I click the back button in my browser after the sheet has opened and navigate to the previous page, the whole application becomes unresponsive even though the previous page has rendered.

### Environment

```markdown
- FlutterFlow version: 4.1.81+
- Platform: x86_64
- Browser name and version: Google Chrome 126.0.6478.126 
- Operating system and version affected: Fedora 39
```

### Additional Information

I am just trying to show a bottom sheet. Please help, I have lost a whole day of work trying to figure this out. Every change I make gets reset it is becoming impossible to work here.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. It appears to be very specific to the logic you’ve set up in that bottom sheet. Since this GitHub Issue Tracker is primarily for bugs that can be replicated in a new blank project, I wasn’t able to find a way to assist you directly.

For a more tailored solution, I strongly recommend reaching out to our support team via the in-app chat or by emailing support@flutterflow.io. They’ll have the right tools and insights to help you resolve this issue.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
