### ISSUE TITLE
Unable to unsubscribe or remove subscribed channels from Supabase realtime

### ISSUE THREAD

**Issue by czsday** [FlutterFlow/flutterflow-issues#3592]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, the realtime subscribe/unsubscribe does not work properly for me. I have read through all the available supabase/flutterflow documents and youtube videos regarding this. seems like a bug.

When subscribe to supabase realtime event, command with supabaseClient works for me (I am able to include API url, key and accessToken when initialize the subscribe instance). SupaFlow.client would not work (I have set RLS for realtime policy to public).
 
For unsubscribe code, I can't test with supa.flow because I am not able to subscribe with SupaFlow.client. By using supabaseClient with the same API url, key, accessToken, it does not unsubscribe. The wierd thing is if I append unsubscribe command to end of subscribe code, unsubscribe will work. if separate into two custom code actions (subscribe and unsubscribe), unsubscribe won't happen.

### Expected Behavior

Since I have already set up supabase connections, SupaFlow.client should work for subscribe (supabase realtime policy set broadcast to public)

According to supabase doc, I should be able to kill all channels with supabaseClient.removeAllChannels();  But in flutterflow, it only remove channels when I append it to subscribe. I feel it probably couldn't find the corresponding channel if I add it into a separated custom action.

### Steps to Reproduce

1. Test mode, sign in with test3@gmail.com password is 000000, load "messages" page
2. run API calls named loginAPI (test API Call with variables email: test4@test.com, password: 0000), then copy the access token from Test Response.
3. go to newMessageAPI, and paste accessToken into variables and enter anything in the message_text variable, then click Test API call
4. In Test mode "messages" page, if you see the new message, that meams the custom code "unsubscribe" did not work.
5. In Action Flow Editor in "messages" page, if you switch Custom Action subscribe to subscribeSupaFlow and unsubscribe to unsubscribeSupaFlow.
6. set action arguments table to message, accessToken to App State accessToken, callbackAction to ShowSnackBar
7. repeat step 1~4, you will see the ShowSnackBar never happen, because Custom Action subscribeSupaFlow would not work.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkvLluYtPxd9Y0a6JaPlKp2EUOVMcTL4zlO1HcxAYGO/yPbJ/ZcneZVtCXcO5SmlhHFb/rzoHw/z2j/DhC/UFBweBQa46/pFtEg7JVXq8SoyrBau0bXNAL+RRFWqg5LerviVRBMpedF4EwEyqJuu9VhLACZu/Zwh9f6PHaOI=

### Visual documentation

subscribe (works):
![subscribe](https://github.com/user-attachments/assets/5b20b3be-c884-4e04-b1ca-b8302f4f5616)

unsubscribe (2 methods, doesn't work):
![image](https://github.com/user-attachments/assets/83766096-6b9c-4646-9dc1-867252efb8f7)

works if append unsubscribe to subscribe (combine into one custom action):
![image](https://github.com/user-attachments/assets/8dc03273-c0eb-42a0-ac1e-cbb0a59c7b70)

subscribeSupaFlow (subscribe does not work even with supabase integrated in Flutterflow)
![image](https://github.com/user-attachments/assets/cfcf7c2a-3e6f-436a-a0ba-e9a15d2dc96d)
![image](https://github.com/user-attachments/assets/08dfa869-8028-4610-b4c2-25b014149324)

unsubscribeSupaFlow (don't know if it works or not because not able to subscribeSupaFlow)
![image](https://github.com/user-attachments/assets/668c07d7-04a1-4c32-b5c0-69d88992a71f)

Supabase realtime policies open to public for select and insert:
![image](https://github.com/user-attachments/assets/20c09dfd-bd1f-4a08-a840-ffdaba00d230)

### Environment

```markdown
- FlutterFlow version: v4.1.81+
- Platform: Windows
- Browser name and version:Chrome v127.0.6533.90
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
