### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by gabdreux** [FlutterFlow/flutterflow-issues#3593]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Returning error:

Uncaught (in promise) Error
    at Object.throw_ [as throw] (dart_sdk.js:11994:11)
    at Object.nullCheck (dart_sdk.js:12343:30)
    at MappedListIterable.new.<anonymous> (schema_util.dart:75:62)
    at MappedListIterable.new.elementAt (dart_sdk.js:32832:25)
    at ListIterator.new.moveNext (dart_sdk.js:32650:55)
    at JsIterator.next (dart_sdk.js:13192:21)
    at List.of (dart_sdk.js:134313:18)
    at MappedListIterable.new.toList (dart_sdk.js:32467:30)
    at Object.getDataList (schema_util.dart:75:61)
    at [_initializeFields] (users_record.dart:115:16)
    at new users_record.UsersRecord.__ (users_record.dart:16:5)
    at UsersRecord.fromSnapshot (users_record.dart:127:77)
    at users_record.dart:125:41
    at _RootZone.runUnary (dart_sdk.js:46938:59)
    at _FutureListener.then.handleValue (dart_sdk.js:42334:29)
    at handleValueCallback (dart_sdk.js:42938:49)
    at _Future._propagateToListeners (dart_sdk.js:42976:17)
    at [_completeWithValue] (dart_sdk.js:42817:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:42851:35)
    at Object._microtaskLoop (dart_sdk.js:47394:13)
    at _startMicrotaskLoop (dart_sdk.js:47400:13)
    at dart_sdk.js:43200:9

### Expected Behavior

Login

### Steps to Reproduce

Create 2 input fields, a button and set "login action".

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMjf5YpIvuJE+pDMccAxgWMwFjMMbY0v0u0bFB4gNZz2O5YUdvT7dUNKTd/jelVYH2Klhk4DwMrsiuP9A/EnIT+ec7ZP0JVAVxfybFOtWrKwPc2SWHBTN+BUIGLE1sGngSV+BNR2Sk44wFy1N63qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/830bfb20-2164-418c-bde8-a04f054f00f7)
![image](https://github.com/user-attachments/assets/03f3e311-d00e-4f17-a9f6-67333bee56ce)
![image](https://github.com/user-attachments/assets/c8e1313a-a7b4-44fe-8b1d-92245bc8052c)
![image](https://github.com/user-attachments/assets/3bcbb0df-6615-44b1-81c0-f66f775c5cf0)

### Environment

```markdown
- FlutterFlow version:  FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2
- Platform: web
- Browser name and version: chrome Versão 127.0.6533.100 (Versão oficial) 64 bits
- Operating system and version affected:
```

### Additional Information

Project ID: printz-6kass7

Returns the same error trying to log in from authorized ulrs.

![image](https://github.com/user-attachments/assets/0509b804-5822-4c14-af07-e55064b4d817)

It "logs" the user but cannot fetch the user's data
![image](https://github.com/user-attachments/assets/406e2722-59b0-4db1-b433-30cce33a76b4)

**Comment by Alezanello** [comment]
Hello!!

After taking a quick look at your project, it seems you have multiple `navigateTo` actions set up in your login flow. This could be causing some performance issues. I strongly recommend using a multiple condition validator to determine the correct destination for the user after login. This approach will help streamline the process and improve overall performance.<br><br>From this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1594ce12-9f73-4344-a179-1b84bf21f53b/8ae110ab-ffa4-43e2-bd0b-20e06ce704b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNTk0Y2UxMi05ZjczLTQzNDQtYTE3OS0xYjg0YmYyMWY1M2IvOGFlMTEwYWItZmZhNC00M2UyLWJkMGItMjBlMDZjZTcwNGI3IiwiaWF0IjoxNzIzMjExMzIzLCJleHAiOjMzMjkzNzcxMzIzfQ.rIGVmmPqwl6UpXWOPVI-qLrdSjRvyE2xUBAigclRQZg " alt="image.png" width="287" height="653" />

To this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1c2e4d6b-6a6e-4501-8254-bc7eebc40e70/0bf4079a-e569-4f2f-81df-e7c39e44b45c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYzJlNGQ2Yi02YTZlLTQ1MDEtODI1NC1iYzdlZWJjNDBlNzAvMGJmNDA3OWEtZTU2OS00ZjJmLTgxZGYtZTdjMzllNDRiNDVjIiwiaWF0IjoxNzIzMjExMzIzLCJleHAiOjMzMjkzNzcxMzIzfQ.ZesEGM0PuPzb1VyyXDdhPvme4WNZJl3nHH6KFzbePi0 " alt="image.png" width="1491" height="518" />

<br>Please let me know when you change this behavior and test it if this solve your issue!<br><br>Best regards,<br>Azanello

**Comment by gabdreux** [comment]
hello @Alezanello! 

I eliminated all actions leaving just the login and it still returns the same error.
And I removed the login from the component, using it directly on the home page. Still doesnt work.

![image](https://github.com/user-attachments/assets/ee0d6ccb-851c-4289-8ced-7cd2b145c921)
![image](https://github.com/user-attachments/assets/5fe59f5e-97e7-401b-9970-f576a296533f)


It also does not load the logged in user's information, just the email.
![image](https://github.com/user-attachments/assets/e21551e5-21b7-4a8f-a831-d21c73a55cb3)

**Comment by Alezanello** [comment]
Hello again!

I noticed that you've changed the login process, and it now logs in successfully. However, it doesn't navigate to another page after login. I was able to create the email [testing@testing.com](mailto:testing@testing.com) successfully, but you’ll need to set up navigation to direct users to the appropriate page after they log in.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c45f5e74-943b-4058-a67c-871666054b0f/a3d03a93-1f47-45f1-8fa6-145e940bdfa6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNDVmNWU3NC05NDNiLTQwNTgtYTY3Yy04NzE2NjYwNTRiMGYvYTNkMDNhOTMtMWY0Ny00NWYxLThmYTYtMTQ1ZTk0MGJkZmE2IiwiaWF0IjoxNzIzMjIwMTE2LCJleHAiOjMzMjkzNzgwMTE2fQ.huI80hBzk-W9qdVkc_brxalAZGDTkeCjIpfOwvpJazU " alt="image.png" width="1036" height="450" />

**Comment by gabdreux** [comment]
The login happens, but it still does not load the logged in user's information.

Could you navigate to "user-area" by clicking on the user icon in the header to add information and check?
![Captura de tela 2024-08-09 131910](https://github.com/user-attachments/assets/169fc28d-7e11-41e4-a7a3-b48cfc0430ec)

![image](https://github.com/user-attachments/assets/f1a86c07-d55d-4242-bf1e-736e4ad7a955)




The "Navigate "Automaticaly" also doenst work.

goiascopias.adm@gmail.com
pass: admin@admin


Much tks! @Alezanello

**Comment by Alezanello** [comment]
Since the registration process only required an email, no additional information is being displayed. One solution is to set up a Document Reference query in the container where "dados" is shown, using the Authenticated User Reference. Then, use the results of that query to display the relevant data. This should ensure that the data loads correctly, even if it doesn’t appear immediately on the first load.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e92e6c63-3ab1-41bb-8ed3-3dc85ea92560/8fd4e1c5-cd3b-4248-8f32-80d01c2f8cf7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lOTJlNmM2My0zYWIxLTQxYmItOGVkMy0zZGM4NWVhOTI1NjAvOGZkNGUxYzUtY2QzYi00MjQ4LThmMzItODBkMDFjMmY4Y2Y3IiwiaWF0IjoxNzIzMjIwOTg2LCJleHAiOjMzMjkzNzgwOTg2fQ.3x2Ge_-ThDBdu8NCLZSG8xzC30t1HLXlI5Wlo4E-bEk " alt="image.png" width="1422" height="696" />

**Comment by gabdreux** [comment]
![image](https://github.com/user-attachments/assets/989a3819-b645-4940-8d62-e156e7fc48f2)


![image](https://github.com/user-attachments/assets/95072de3-c12c-483c-9f49-39bf9545fc39)


![image](https://github.com/user-attachments/assets/78ece1bf-f874-4037-b3da-f06c9fe8e4ae)

**Comment by gabdreux** [comment]
Very weird response.

![image](https://github.com/user-attachments/assets/99c923ff-e87c-45ae-8791-657c41355b60)

![image](https://github.com/user-attachments/assets/1291ec1f-53db-41be-bebf-22b9829becf4)

![image](https://github.com/user-attachments/assets/e5854a0d-265b-40ed-8f48-31845b7cd920)

**Comment by Alezanello** [comment]
Is any problem for you if you can give me collaborator access to try some stuff? azanello@somniosoftware.com

**Comment by Alezanello** [comment]
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/95492630-4d63-46b7-95df-30205d052622/9f7c505f-96d7-4405-bfcd-91e26864a567?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NTQ5MjYzMC00ZDYzLTQ2YjctOTVkZi0zMDIwNWQwNTI2MjIvOWY3YzUwNWYtOTZkNy00NDA1LWJmY2QtOTFlMjY4NjRhNTY3IiwiaWF0IjoxNzIzMjIxODc0LCJleHAiOjMzMjkzNzgxODc0fQ.yFzspTmYfO9Yx4tD6BM40PuPX3JUmdxtr9AoWrwrSGg " alt="image.png" width="1448" height="751" />

**Comment by Alezanello** [comment]
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cecb1b05-2915-40c1-b1b5-1aab6bd9c23e/892af6de-a9cc-4ef6-8cb6-4884a36a2518?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZWNiMWIwNS0yOTE1LTQwYzEtYjFiNS0xYWFiNmJkOWMyM2UvODkyYWY2ZGUtYTljYy00ZWY2LThjYjYtNDg4NGEzNmEyNTE4IiwiaWF0IjoxNzIzMjIxOTIzLCJleHAiOjMzMjkzNzgxOTIzfQ.8sPM50PY3CXjAvwX5b3h7TzJKSvU3lVdzy6qpspmQwM " alt="image.png" width="1457" height="747" />

I saved the information and is showing correclty

**Comment by Alezanello** [comment]
testing@testing.com<br>Testing123!

**Comment by gabdreux** [comment]
The error seems to be in the user "goiascopias.adm@gmail.com"
Anyway, I added you as a collaborator.
Feel free to carry out tests. Thank you very much!!

**Comment by gabdreux** [comment]
@Alezanello Now it seems that the user you created is also having the same problem...it simply stopped pulling information. very weird  :(


Can I help you in any way? Do you Need any information?

**Comment by gabdreux** [comment]
I'm using the login action over one widget. Is that ok?
![image](https://github.com/user-attachments/assets/fc21dd46-49e9-484c-b9de-38bc9fe472bd)

FF won't let me use more than one creation action. But apparently login is allowed.

Just passing possibly relevant information.

**Comment by gabdreux** [comment]
Now pulling random information but not all...... broooooo

![image](https://github.com/user-attachments/assets/a3740859-02e4-49e2-a3d0-12a8fa943063)

**Comment by gabdreux** [comment]
Its working again.........tks @Alezanello

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
