### ISSUE TITLE
Images from the network can't be shown dynamically

### ISSUE THREAD

**Issue by gspassky** [FlutterFlow/flutterflow-issues#3594]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no way to use any dynamic data as a Network Image path parameter. When testing in the web everything works fine, but when downloading APK the image won't load. The problem is in ImagePath data type. There are several issues with it:
1. There is no way to make a variable of this type in custom code
2. There is no way to convert string to this type
3. If you try to make a Custom Function with result type ImagePath - it's not correctly set in the code (it's set to String)
If you type the image path directly as a string in FF interface - it works. But if you use a variable for that, even if it's initially has correct ImagePath data type, it doesn't work in downloaded APK. Also, if you try to build an Image path with Combine String operation in FF interface - it won't work in APK

### Expected Behavior

Image must be shown both in test mode and in downloaded APK

### Steps to Reproduce

1. Create an App Constant of a type ImagePath
2. Create an Image Widget and use this constant as a value of its path
3. Download APK
4. You'll see that the image is not loaded

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlM7lvJdOoeFa+KrUbfpVqDwWCDsmbYIelsIbZAAdCO+sG7lzRc/BQExWXL2oTHNYIWakjnEfxvfqktnDGvA4Hw+cGLpF+pBiVz3NUmSRRaqtC4ezfW1SP+xTfmrD1MGFvyZ+ANVhZVYewEOIJPK9QnLbQoS2PDMdRc6bJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![apk-test](https://github.com/user-attachments/assets/3b314831-92f6-4e96-b482-6fb6054736a6)
![web-test](https://github.com/user-attachments/assets/f8d726d9-e7d4-48b5-91e1-1f21228c59ac)

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

I spent several hours trying different techniques, but in vain. My app doesn't use Firestore, so I didn't test only this way. All other ways (constants, custom code) don't work

**Comment by gspassky** [comment]
Finally I found the problem. It was happening because of SVG images. I've created 5 different Image Widgets:
- Cached SVG image from the variable
- Simple SVG image from the variable
- Simple PNG image from the variable
- Cached PNG image from the variable
- SVG image path without variable (plain text in path parameter in FF UI)
And here is the code I got:
`
                Align(
                  alignment: AlignmentDirectional(0, 0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(8),
                    child: CachedNetworkImage(
                      fadeInDuration: Duration(milliseconds: 500),
                      fadeOutDuration: Duration(milliseconds: 500),
                      imageUrl: FFAppConstants.imgSVG,
                      width: 300,
                      height: 200,
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                Align(
                  alignment: AlignmentDirectional(0, 0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(8),
                    child: Image.network(
                      FFAppConstants.imgSVG,
                      width: 300,
                      height: 200,
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                Align(
                  alignment: AlignmentDirectional(0, 0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(8),
                    child: Image.network(
                      FFAppConstants.imgPNG,
                      width: 300,
                      height: 200,
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                Align(
                  alignment: AlignmentDirectional(0, 0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(8),
                    child: CachedNetworkImage(
                      fadeInDuration: Duration(milliseconds: 500),
                      fadeOutDuration: Duration(milliseconds: 500),
                      imageUrl: FFAppConstants.imgPNG,
                      width: 300,
                      height: 200,
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                Align(
                  alignment: AlignmentDirectional(0, 0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(8),
                    child: SvgPicture.network(
                      'https://eq-math-game.web.app/assets/0/0.svg',
                      width: 300,
                      height: 200,
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
`
First two Widgets won't work in APK.
As you see, in the last item, special SvgPicture.network call used, while in the others Image.network is used. That's why dynamic SVG images are not displayed correctly.
So, FlutterFlow can solve the problem adding one more parameter in the UI: image type, which changes used function in the generated code.
Finally, I created an Image Widget with path made of concat strings - constant + string:
`
// Generated code for this Image Widget...
Align(
  alignment: AlignmentDirectional(0, 0),
  child: ClipRRect(
    borderRadius: BorderRadius.circular(8),
    child: CachedNetworkImage(
      fadeInDuration: Duration(milliseconds: 500),
      fadeOutDuration: Duration(milliseconds: 500),
      imageUrl: '${FFAppConstants.stringPath}cover.png',
      width: 300,
      height: 200,
      fit: BoxFit.cover,
    ),
  ),
)
`
Despite imageUrl here doesn't have ImagePath type, it works!
**So, currently, dynamic images of SVG type are not supported.** Needs improvement, of course...

**Comment by msusviela** [comment]
Thanks for the insight. I'll send this feedback to the ENG team.
