### ISSUE TITLE
Unable to rename a folder

### ISSUE THREAD

**Issue by Engineersticity** [FlutterFlow/flutterflow-issues#3597]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to rename a folder in my project. I created a folder and wanted to change its name but whenever I right click and inout a new name, the folder retains the former name.

https://github.com/user-attachments/assets/9ea3a217-c439-472d-97c4-b1a24b9f7f30

### Expected Behavior

I expect that when I rename a folder, the name of the folder gets updated.

### Steps to Reproduce

1. In your project, create a new folder and add pages to it
2. Try to rename the folder by right clicking on it and selecting "Rename folder"
3. Observe the behaviour.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8jf34VIsdtJ+KX2dsExjSQRC2l8aJE3jspBZywgfZzzBLN/fPfQPxZuZ9+rTWxIelmMp14H0cL1vvDtM/QrCE2tGIBiwZducTzMbGKtMIuTF7uodH8nDZthfkjH0KeFsCYlNs5vSmQ/w0OYAe/IEyvAQ4zOPUQ8Sq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/74f1cf71-7daa-47d5-8b7e-b7cf10c7bdb5

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.81+ released August 7, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome Version 127.0.6533.100 (Official Build) (arm64)
- Operating system and version affected: Mac OS Sonoma Version 14.5
```

### Additional Information

I am trying to organise my project before involving a larger team for further development.

**Comment by msusviela** [comment]
Hi @Engineersticity. I could rename folders without any issue (v 4.1.81+ on web), can you please check that's working for you?
