### ISSUE TITLE
UI Elements/Widgets Failing To Populate On Screen

### ISSUE THREAD

**Issue by cgeddes3** [FlutterFlow/flutterflow-issues#3598]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Certain widgets/elements aren't populating on the screen after I create them. (They show in widget tree) Secondly, if/when they do populate, clicking on them doesn't show the properties panel. Rather, I need to find each widget that I want to adjust on the widget tree itself which is a pain.

### Expected Behavior

I'd expect to be able to click on specific elements within the screen itself to make changes efficiently.

### Steps to Reproduce

1. Navigate to page selector
2. Click on folder labeled: "Hub"
3. Select "Service Menu" Screen
4. Try to select a element of your choosing
5. You'll see certain elements aren't populating that appear in the widget tree

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ailure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Visual documentation

[](https://www.loom.com/share/bfdc6098a1c943358a4b66efe2df692f?sid=2645fe95-4580-4321-823b-8a3ebfb75064)

### Environment

```markdown
- FlutterFlow version: v4.1.81
- Platform: Mac OS and Web (issue is happening on both)
- Browser name and version: Chrome 127.0.6533.100 (Official Build) (arm64)
- Operating system and version affected: (desktop): macOS Sonoma 14.5
```

### Additional Information

It's affecting my ability to successfully build out my app.

**Comment by msusviela** [comment]
Hi @cgeddes3. 

Thanks for filling in but it's necessary that you provide more information so we are able to look into it from our side.

Please, provide the steps to reproduce the issue from a blank project and also a bug report code. You can generate it by clicking right on the widget tree and selecting the Generate bug report option. This guide might help you: [https://docs.flutterflow.io/troubleshooting/submit-bug-reports](https://docs.flutterflow.io/troubleshooting/submit-bug-reports)

<br>Without the necessary information it would be impossible for us to pinpoint the issue.<br>Thanks!
