### ISSUE TITLE
AppBar unexpected additional padding

### ISSUE THREAD

**Issue by kjoyceee** [FlutterFlow/flutterflow-issues#36]
## Expected behavior (required)
A collapsable UI like the one shown in the recent 'New Features For You' email

## Current behavior (required)
When I add an app bar and toggle the SliverAppBar to add collapsibility functionality it adds a bunch of blank space underneath. This happens with 'Add bottom section' disabled, even tried adding it with 0px height still same issue. Appears normal in the builder but in preview, run, run on device I get the extra padding

## To Reproduce (required)
1. Add AppBar to page
2. Toggle 'Collapsible (SliverAppBar)' to on
3. Preview/Run app

## Context (required)
Creates an unpleasant view for the user.

## Screenshots / recordings

Expected view:
<img width="359" alt="Screen Shot 2022-10-11 at 10 41 49 AM" src="https://user-images.githubusercontent.com/115580022/195162324-94b40237-dfb6-4810-9ff9-13ca3c0c7ea0.png">

Actual result when ran:
<img width="411" alt="Screen Shot 2022-10-11 at 10 41 58 AM" src="https://user-images.githubusercontent.com/115580022/195162367-2abf8e32-6273-4bb9-b8de-5defa4060f2b.png">

## Your environment

* **Bug Report Code: ITFTl/GA6otNm7QF+KnUKsFsr2IsGUMfWI0/ld5EZwEhfIitE5k+Zs/RPhJLYtfgT25cHWKZrDoCptLtv/DLIMECGxOqbJR/zawFH1yjEA8=**
* Version of FlutterFlow used: v.1.1.10
* Platform (e.g. Web, MacOS Desktop): MacOS
* Operating system and version (desktop or mobile): MacOS 12.6

**Comment by agreaves** [comment]
Thanks for the bug report! This was an issue with Safe Area, which we were not handling correctly in Preview mode. This has been fixed on our end, which will be reflected upon our next deploy.

For now, to get around this, simply turn off Safe Area for the given page.
