### ISSUE TITLE
Timer On End Event called by Reset Timer

### ISSUE THREAD

**Issue by technoclectic** [FlutterFlow/flutterflow-issues#3600]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the timer ends and the OnTimerEnd action is fired I need to reset that timer and run it again.
So I call a Reset Timer action to set the timer again to the time that I want followed by a Start Timer to start the timer. 

The Reset Timer action however triggers the OnTimerEnd to fire again. This means that all actions in the chain are duplicated if you are running a timer more than 1 time.

So I need to know how to detect if it is the true timer ending (the timer hits 00:00) OR if it is the OnTimerEnd triggered by the Reset Timer.

### Expected Behavior

OnTimerEnd to only be called when the timer actually ends. Said another way, the Reset Timer action should NOT fire the OnTimerEnd event

### Steps to Reproduce

1. New page
2. Add timer
3. Add page state variable as a counter and bind a text field to it so that you can see what's happening.
4. Add the following actions to timer's OnTimerEnd event.
4a. Update Page State variable by +1
4b. Reset Timer to 10s
4c. Start Timer

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClefqwItOpbxJ7qX2bsEw+SoUKVAjRYE70e5HdxEaN5PRCJkqe/fOTERpXsSlTFV+OmKkjWoW0ejni/DhUuw3PU6ZY4hhyapySTrgXk65R7XTFJWgZ2hfHe9jI3K05MONuh14KsRfdCEB2jn3fe6iYA3vQaX6Omo4Da/LZO4=

### Visual documentation

https://support.technoclectic.com/conversations/51e675d5-5364-53e9-95e1-e658e5fa3079

### Environment

```markdown
- FlutterFlow version: 4.1.82
- Platform: Desktop app
- Browser name and version: Local Run testing
- Operating system and version affected: All versions
```

### Additional Information

This unexpected behavior is causing many delays in my project. Trying to find workarounds or ways to detect if the OnTimerEnd event is called by the timer reaching 00:00 ms versus the Reset Timer action calling it. Is there a way to add a boolean to the Reset Timer say "don't trigger OnTimerEnd" when resetting?

**Comment by technoclectic** [comment]
Here is  a workaround:
Add page state variable type: boolean
Set to False by default
Add a conditional first step in Action chain of the OnTimerEnd event
Set the condition to the Page State variable
In the true branch update your counter variable to decrement by 1 (-1)
In the false branch put your logic.

this is a very inelegant workaround and shouldn't be considered a solution.

**Comment by Alezanello** [comment]
Hello!

I was able to get the counter running smoothly without the need for the decrement workaround you suggested. The key is to adjust the order of operations slightly:

Instead of:

1. Update page state
2. Reset timer
3. Start timer

You should try:

1. Reset timer
2. Update page state
3. Start timer

   <img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c26027cd-f4fe-4a6b-a8ae-532ef02a0d51/09eb6dd9-8199-4ca7-8354-f72da29a242f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMjYwMjdjZC1mNGZlLTRhNmItYThhZS01MzJlZjAyYTBkNTEvMDllYjZkZDktODE5OS00Y2E3LTgzNTQtZjcyZGEyOWEyNDJmIiwiaWF0IjoxNzIzNTg0MjcyLCJleHAiOjMzMjk0MTQ0MjcyfQ.ndN2XKhViK4m4agX2y6RE2X19b4jwo17NsSRav3532o " alt="image.png" width="1203" height="513" />

This sequence should work without any issues!

**Comment by Alezanello** [comment]
Example: [https://app.flutterflow.io/run/mGolZzaYGPwWA5z4ywxw](https://app.flutterflow.io/run/mGolZzaYGPwWA5z4ywxw)

**Comment by technoclectic** [comment]
I’m unable to load this project, not sure if it has expired or what. I will try your solution to move the action shortly and let you know.

**Comment by technoclectic** [comment]
Hi,
I notice that you don’t have any type of looping or conditional actions in your code flow. This would be needed to accurately represent my use case. I am attaching what I have that is working and I thought was laid out in the video on the issue.

You will notice 3 conditional blocks.

1. Determines if this is a duplicate and should be ignored (the workaround)
2. Only runs on the initial counter (3,2,1,Go!) and has a roundCounter of 0. There is no increment in this conditional block.
3. Should run for each subsequent iteration and increments the roundCounter on each completion until the rounds variable is matched.

<img width="616" alt="Screenshot 2024-08-15 at 11 39 30" src="https://github.com/user-attachments/assets/32417745-d19f-4b45-8880-9d580a4f5d3d">


I’m happy to drill into any of these actions but the result was the same when I tried your suggestion.

Thanks
Gary

**Comment by technoclectic** [comment]
Issue is still open. Getting warnings that it’s stale?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by technoclectic** [comment]
I am away on holiday at the moment and cannot check. Please leave the issue open until I have an opportunity to review.

**Comment by technoclectic** [comment]
I don't see that anything has changed for the timer firing the ontimerend event on reset.
