### ISSUE TITLE
Error (Xcode): Plugin pointer_interceptor

### ISSUE THREAD

**Issue by ozan-celebi** [FlutterFlow/flutterflow-issues#3601]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After exporting the code to my Mac directory I run the flutter project and receive the following error on the Terminal.

Could not build the precompiled application for the device.
Error (Xcode): Plugin pointer_interceptor:ios provides an implementation for
pointer_interceptor_platform_interface and also references a default
implementation for pointer_interceptor_ios, which is currently not supported.
Ask the maintainers of pointer_interceptor to either remove the implementation
via `implements: pointer_interceptor_platform_interface` or avoid referencing a
default implementation via `platforms: ios: default_package:
pointer_interceptor_ios`.

Error launching application on Ozan’s iPhone.

### Expected Behavior

This makes the build fail and I cant run on a physical device when I download the code. I have tried to edit the pubspec.yaml and remove the plugin pointer_interceptor from the dependency but that didnt help one I ran the project again. 

However, The app can run on a physical device when doing a Local Run from the FF desktop apr for Mac.

### Steps to Reproduce

Export the project. flutter run -d "(a real device)". The compiler exits. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

<img width="742" alt="image" src="https://github.com/user-attachments/assets/dceb76d1-1288-4fd5-95ea-2e9292377130">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.82
- Platform: iOS
- Browser name and version: N/A
- Operating system and version affected: N/A
```

### Additional Information

Can you please provide a solution on how to avoid this error? I couldn't find a solution online.

**Comment by Alezanello** [comment]
Hello!!

I’m sorry to hear that you’re experiencing this issue. To help us take a deeper look, could you please share a Bug Report Code from your project so we can verify that the dependencies are correctly set?

You can generate the Bug Report Code by right-clicking on any widget in the Widget Tree and selecting "Get Bug Report Code" from the dialog that appears.

Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c27d16ec-8a96-4cf4-abba-5f08da2d9a3b/aa70279f-8833-41a1-8567-70af48aba04f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMjdkMTZlYy04YTk2LTRjZjQtYWJiYS01ZjA4ZGEyZDlhM2IvYWE3MDI3OWYtODgzMy00MWExLTg1NjctNzBhZjQ4YWJhMDRmIiwiaWF0IjoxNzIzNDY2NTc3LCJleHAiOjMzMjk0MDI2NTc3fQ.hWJv1hHk-T23N6hlsOE0OpeIRjVKbNNO3varCCCZwDE " alt="image.png" width="476" height="388" />

**Comment by Doopin** [comment]
I have this same issue since more than 5 days.
It started when I upgraded to **Xcode 15.4**

> Plugin pointer_interceptor:ios provides an implementation for pointer_interceptor_platform_interface and also references a default implementation for pointer_interceptor_ios, which is currently not supported. Ask the maintainers of pointer_interceptor to either remove the implementation via `implements: pointer_interceptor_platform_interface` or avoid referencing a default implementation via `platforms: ios: default_package: pointer_interceptor_ios`.

![image](https://github.com/user-attachments/assets/327a0b38-1272-4bd6-b959-8cf5f7f07d71)


I have even tried to manually removed every package that references **pointer_interceptor** and even removed **pointer_interceptor: 0.10.1** itself.

- flutter clean
- flutter pub get
- cd ios
- rm Podfile.lock
- pod install / pod update

No chance! Am stuck and no way to release my latest changes

**Comment by ozan-celebi** [comment]
Hello, 

The issue isn't related to a bug in a widget. I think its related to the pubspec.yaml file that comes when exporting the code for the project. 

However, I am providing a Bug Report code for the Home Page of my project below:

ITEeysmBz4dNpbxI17XxbvlGrwMwJ0QlUIInj+0bWRMhfJSoEIkUZ+ClZRBLYteDeFFbe1SWikYFpc7eis71NcI4NQmsRpRRwoRXQTzLUTihR8mmO7qKQnQlO+lTI0C70LTYoSYmOfV2S3g5w02MAvCdG3qCf9qOYwx5e6fDbOY=

**Comment by ozan-celebi** [comment]
@Doopin At least Im not the only one then :)

**Comment by hepnn** [comment]
Hi, I also had this issue, seems the newest version of  pointer_interceptor caused this, try overriding it for now, while it's not fixed. fyi this is not a FlutterFlow specific issue.

```
dependency_overrides:
  pointer_interceptor: ^0.10.1+1
````
Alternatively you can downgrade flutter build version from 3.24

**Comment by Doopin** [comment]
@hepnn your answer has saved me. THank you alot.
This below was enough to fix the issue:

> dependency_overrides:
  pointer_interceptor: ^0.10.1+1

**Comment by Alezanello** [comment]
Hello again!

Please keep in mind that FlutterFlow currently operates on Flutter v3.22.2. If you’re using a later version locally, such as v3.24, it could lead to several dependency issues.

**Comment by cyberlion-ops** [comment]
whats the solution for this ? . i disagree with @hepnn it is a flutterflow issue as i wanted to deploy my project i get an error related to vm_service and if move that to the dependency_overides it gives the errors mentioned above and get a message about the flutter version not being up to date. you can check the issue mentioned by @Alezanello for more details. now i am just stuck not being able to publish my app to the appstore.is there an actual solution because this is definitely a flutterflow issue, i had exported and published my project multiple times without this issue this issue is new which might be related to one of flutterflow updates.

**Comment by hepnn** [comment]
> whats the solution for this ? . i disagree with @hepnn it is a flutterflow issue as i wanted to deploy my project i get an error related to vm_service and if move that to the dependency_overides it gives the errors mentioned above and get a message about the flutter version not being up to date. you can check the issue mentioned by @Alezanello for more details. now i am just stuck not being able to publish my app to the appstore.is there an actual solution because this is definitely a flutterflow issue, i had exported and published my project multiple times without this issue this issue is new which might be related to one of flutterflow updates.

It is related to the newest version of pointer_interceptor, which got released alongside of flutter version 3.14. pointer_interceptor is a transitive dependency which got automatically updated running flutter pub get, so because you are using an older version than 3.14 and pointer_interceptors newest version is made for 3.14, you get this error

**Comment by cyberlion-ops** [comment]
@hepnn thanks for the reply. doesn't flutterflow uses flutter version 3.22.2. i even tried moving the pointer_interceptor to the dependency_overrides i still get a different issue with this error
lib/edit_listing_page/edit_listing_page_widget.dart:485:67: Error: The argument type 'CarouselController' can't be assigned to the parameter type 'CarouselSliderController?'.
which i don't know how to even fix that. which seems to me like it's definitely a flutterflow issue as that is something done in flutterflow with no errors or modification. maybe chip in on this @Alezanello

**Comment by andrewjneumann** [comment]
> whats the solution for this ? . i disagree with @hepnn it is a flutterflow issue as i wanted to deploy my project i get an error related to vm_service and if move that to the dependency_overides it gives the errors mentioned above and get a message about the flutter version not being up to date. you can check the issue mentioned by @Alezanello for more details. now i am just stuck not being able to publish my app to the appstore.is there an actual solution because this is definitely a flutterflow issue, i had exported and published my project multiple times without this issue this issue is new which might be related to one of flutterflow updates.

I added to my pubsec.yaml and it fixed it
dependency_overrides:
  vm_service: ^14.2.4

**Comment by andrewjneumann** [comment]
> Hello again!
> 
> Please keep in mind that FlutterFlow currently operates on Flutter v3.22.2. If you’re using a later version locally, such as v3.24, it could lead to several dependency issues.

Is there a way to know what versions of the build chain FF is using-- is this documented anywhere?

**Comment by fabienbranchel** [comment]
Not using to FlutterFlow at all but it's the only issue I found on the subject.

In a context of update all dependencies of my project, delete `pubspec.lock` then execute `flutter pub get` did the trick for me.

**Comment by Alezanello** [comment]
Hi there!

I wanted to check in and see if this issue has been resolved with the latest updates?

**Comment by cristaloleg** [comment]
Have subscribed to this thread few days ago 'cause had the same problem. Downgrade to v3.22.2 works perfectly.

**Comment by Alezanello** [comment]
Downgrading to version 3.22.2 should be your go-to solution until FlutterFlow upgrades to 3.24 or a newer version. Make sure to always run or compile using the same version that we have locally for consistency.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b33eb774-f6a8-47f5-ad26-dd924b66c4f6/f8460fd2-75c6-42d3-9581-2981238ea4ec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMzNlYjc3NC1mNmE4LTQ3ZjUtYWQyNi1kZDkyNGI2NmM0ZjYvZjg0NjBmZDItNzVjNi00MmQzLTk1ODEtMjk4MTIzOGVhNGVjIiwiaWF0IjoxNzI1MzY4OTk5LCJleHAiOjMzMjk1OTI4OTk5fQ.D4td8PbQiujKDSv5hh2hpFFuoq2j9oS9Q8ZN6rxaHHU " alt="image.png" width="271" height="142" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by hubentom** [comment]
i am having this issue today Oct 30 - how could this be closed?
