### ISSUE TITLE
CarouselController prevents from compiling and build code locally

### ISSUE THREAD

**Issue by ALaiFF** [FlutterFlow/flutterflow-issues#3606]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

lib/home/home_components/currency_selector_55/currency_selector55_model.dart:7:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'package:flutter/material.dart';
^^^^^^^^^^^^^^^^^^
lib/home/home_components/currency_selector_34/currency_selector34_model.dart:7:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'package:flutter/material.dart';
^^^^^^^^^^^^^^^^^^
lib/home/home_components/currency_selector_44/currency_selector44_model.dart:7:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'package:flutter/material.dart';
^^^^^^^^^^^^^^^^^^
lib/advisors/advisors_components/service_advisors_summary/service_advisors_summary_widget.dart:368:31: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
                              CarouselController(),
                              ^^^^^^^^^^^^^^^^^^
lib/home/home_components/currency_selector_55/currency_selector55_widget.dart:164:17: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
                CarouselController(),
                ^^^^^^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:48:15: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
            : CarouselController() as CarouselControllerImpl,
              ^^^^^^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:62:15: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
            : CarouselController() as CarouselControllerImpl,
            : CarouselController() as CarouselControllerImpl,
              ^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^

### Expected Behavior

As proposed and used to be up to date—the code compiling and run

### Steps to Reproduce

1. Export code by CLI
2. Compile and run locally in IDE

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XzsnbuJd2vtRE7c/AaflV+WA5JUN/RYE80MN9YEo1GJCtE6QHP+D+T3FdOLynSnxIOWGjnnII7tLQhvP1FO4rFwuIQ745zZZMbhXgLXKuMsTQPrrtYnYkJJlnJnam54qOiiZSKbJ0WHg/3HGUBvCWa3LfQr7tNmwwRcqkLpvAnlHhKh/RFjhmtmNecCfn

### Visual documentation

<img width="946" alt="01" src="https://github.com/user-attachments/assets/66144ec4-b7fb-4798-9407-edf288ff2d86">

### Environment

```markdown
- FlutterFlow version:
FlutterFlow v4.1.81+ released August 7, 2024
Flutter version is 3.22.2

- pubspec.yaml:
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  carousel_slider: 4.2.1
---
IDE environment:
Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651]
```

**Comment by Alezanello** [comment]
Hello!!!

I was able to compile the project locally without any issues. After reviewing your report, I noticed that your IDE environment indicates you’re currently on Flutter Channel Stable v3.24. We are using Flutter v3.22.2.

Please try downgrading your Flutter version to 3.22.2 and then attempt to compile again.

**Comment by ALaiFF** [comment]
Thank you for your clarification, I fugured out it as the only reason eather. When you are planning to allighn Flutter versions to up to date one (3.24)?

**Comment by ALaiFF** [comment]
Yes, I have downgraded it and all the issues gone. Thank you
