### ISSUE TITLE
Not able to see the button in order to generate the config files for firebase.

### ISSUE THREAD

**Issue by Humair741** [FlutterFlow/flutterflow-issues#3608]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not able to see the button in order to generate the config files for firebase, button is not visible on viewport, tried zooming out but that doesn't work on the particular window.
<img width="960" alt="FlutterFlow_error" src="https://github.com/user-attachments/assets/76da5e08-f88a-42b4-86aa-b17d64f0e3a2">

### Expected Behavior

I expected to see the generate button in order to generate my config files.

### Steps to Reproduce

-In the settings, after clicking on firebase, After completing the required setup of firebase I get a button to auto generate config files, after clicking on it a pop-up appears but the button is not visible on the viewport.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi87huJdIrt9f+KrAaPpWqCgUGUMdXOczitVEew4bCIj4OrQMYffsXFtoOLWzaH1EEE6ihmA13Nrzi+DtUPI7HE+ZbNVgyqlybBPPbDmRR5S4BaWZdEdQBfNXFUyl5ImjghVAPfhodCQs2HGYCt+8TT6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="960" alt="FlutterFlow_error" src="https://github.com/user-attachments/assets/b225cede-b41e-4518-b418-daaa27f945fd">

### Environment

```markdown
- FlutterFlow version: online
- Platform: Web
- Browser name and version: Brave v 1.68.137
- Operating system and version affected: windows 10
```

**Comment by Alezanello** [comment]
Hello!!<br><br>did you tried to Zoom out using the Brave Menu?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1771edf2-d2e9-4588-b0c3-2b07f897c4db/1dad05cc-4239-49ec-9d9e-392be20cf720?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzcxZWRmMi1kMmU5LTQ1ODgtYjBjMy0yYjA3Zjg5N2M0ZGIvMWRhZDA1Y2MtNDIzOS00OWVjLTlkOWUtMzkyYmUyMGNmNzIwIiwiaWF0IjoxNzIzNTU0NDc3LCJleHAiOjMzMjk0MTE0NDc3fQ.AmQJGQpk3STZ3gtOeX8n0IoOK3h0t_ZCg-gz6WnQrqU " alt="image.png" width="1555" height="963" />

**Comment by Humair741** [comment]
Done, thanks.I was trying to do it by mouse and it wasn't working but this helped.Thank you so much.Sent from my iPhoneOn Aug 13, 2024, at 9:08 AM, Alezanello ***@***.***> wrote:﻿
Hello!!did you tried to Zoom out using the Brave Menu?
