### ISSUE TITLE
Resetting Searchable Dropdown State Triggers 'onSelected' Action Unintentionally

### ISSUE THREAD

**Issue by adidahl** [FlutterFlow/flutterflow-issues#3609]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a searchable dropdown populated with data from Firebase, the selected item remains highlighted after navigating to another page and returning. To reset the dropdown, I expanded the action to reset the dropdown widget state after navigating. However, upon resetting, the 'onSelected' action is triggered again unintentionally. This results in the application navigating to another page with a random or default ID instead of the expected behavior.

### Expected Behavior

Resetting the searchable dropdown widget state should clear the selected item without re-triggering the 'onSelected' action. The dropdown should remain unselected, and no further navigation or actions should occur unless a new item is selected.

### Steps to Reproduce

- Create a searchable dropdown and populate it with a list from Firebase.
- Add an 'onSelected' action that fetches a document from Firebase based on the selected item and sets a filter where the collection field name matches the selected name.
- Use the variable to retrieve an ID and navigate to a new page, passing the ID.
- Enable the back button on the new page and ensure it works correctly.
- On returning to the dropdown page, expand the 'onSelected' action to reset the dropdown widget state.
- Observe that the 'onSelected' action is triggered again upon resetting, leading to unexpected navigation to a new page with a random or default ID.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghvLlw5dIvt9C1s/qde9Vhj04JUN/aL00sN1haw4aCojoOuxzaeDebVppZ8PjSgllKEWGhnke+fOMjuLlOPYFPROZY4BYzYd2Zg7yf3y/aoSgCbmJPGh5N8BhIG6Z07W3gRN7OvhedCVl316UIenIYCbvHub6Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/6491b8fe-0070-417f-bbc9-bbe983f4ec94

https://github.com/user-attachments/assets/8da93082-2c42-473a-8358-5705c1885b71

### Environment

```markdown
- FlutterFlow version: 4.1.82
- Platform:MacOS
- Browser name and version: Safari and Chrome
- Operating system and version affected: All
```

**Comment by paulperez-dev** [comment]
Hi @adidahl! Can you please share the console log? Is the app throwing an exception?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
