### ISSUE TITLE
Single time query not functioning as stated

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#361]
A single time query should not refresh when the underlaying data is changed, however it does refresh:
![image](https://user-images.githubusercontent.com/122821259/212761352-88621f15-bfe5-49bc-8006-819e741df355.png)

If you create a list with a single time query, the data should not change, however it does change if the underlaying data is changed, and therefore it has a snapshot listener in firebase (which it should not have).

This can cause the project owner additional costs in firestore that they are unaware of, as there could be un-necessary reads being performed.

**Comment by victoriahuang1** [comment]
Hi @OldFred2023 , thanks for the report. Could you generate a bug report code for this issue (you can do so by right clicking the offending widget in the widget tree)?

**Comment by OldFred2023** [comment]
it is easy to reproduce, bound a list to a query with "single time query" enabled, run it... change the data in firestore and the data in the list changes in front of your eyes, and go to firestore usage tab, and you will see the snapshot listener count has increased.

**Comment by victoriahuang1** [comment]
I could not reproduce this with my own projects. Could you share your bug report code, so that I can take a look at yours?

**Comment by victoriahuang1** [comment]
Closing due to inability to reproduce. Feel free to open if there is additional information to help with reproducing.
