### ISSUE TITLE
Custom Widget Icon Paramater Issue

### ISSUE THREAD

**Issue by imne** [FlutterFlow/flutterflow-issues#3610]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm creating a custom widget and one of the paramaters is a list of icons, instead of the List<IconData> or List<Icon> being generated, flutterflow generates a List<Widget>

### Expected Behavior

generate a List<IconData> when the paramater is a list of icons

### Steps to Reproduce

1. Create a Custom Widget
2. Add a paramater of type icon and make it a list
3. generate boilerplate code

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Visual documentation

![Screenshot 2024-08-12 at 22 06 44](https://github.com/user-attachments/assets/7614d543-b255-4f95-9e63-6f32a3a35841)

### Environment

```markdown
- FlutterFlow version: 4.1.81+
- Platform: Web
- Browser name and version: Chrome 127.0.6533.100
- Operating system and version affected: MacOS
```

**Comment by paulperez-dev** [comment]
Hi @imne! From the capture you shared the code generated is correct. What is the issue you are facing?

**Comment by imne** [comment]
> Hi @imne! From the capture you shared the code generated is correct. What is the issue you are facing?

The library I'm using is expecting the type to be IcanData instead of a widget

**Comment by paulperez-dev** [comment]
Try accessing the `icon` property of the `Icon` class, which is of type `IconData`. Parsing the widget to an Icon may be needed.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
