### ISSUE TITLE
Simulator specific navigation error (works when running locally)

### ISSUE THREAD

**Issue by lcundiff** [FlutterFlow/flutterflow-issues#3611]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In flutterflow simulator, any navigate to action will crash upon navigating to the page with the error below, even if the page is empty. The only pages that work are the ones I can get to using the toolbar. When I export the code, and run it locally, everything works as expected, so it must be an issue with flutterflow simulator or my flutterflow project navigator is somehow been modified, although I am not sure how that would be possible since the navigator code is not exposed on flutterflow. 

<img width="297" alt="image" src="https://github.com/user-attachments/assets/3c1fbd9e-ec3e-4289-abdb-04fd7c3f6afd">

### Expected Behavior

I should be able to navigate to pages within the simulator outside of only the toolbar pages.

### Steps to Reproduce

(I have tested this only in my project and on firefox and chrome)
1. Create two blank pages
2. Add button on one page to navigate to the other page.
3. Test in browser simulator. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OjMrl05Ngocta1brUdcdvmiQvJj9/aqxN1+19Y000F4vNGu4MPsneVFRuZrykSnw7OWeZuH41/PfquOH9O8JcIQ2VbaJ/zrtyezrMbEaneKqPOqiJfW1RM8NVG2GOy8PV2iNQVetadCEe1Dm6CO69HynYH72yOVg3NPqbKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Here are 2 blank pages, one with a button that has action to navigate to the other. And then the error that appears when clicking on it. 
Blank page with nav button
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/5bea5521-8591-435e-8a9c-e2ee27438cce">
Blank page it navigates to
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/a5d024f6-7f2a-4c9b-aea8-a169547f7110">

Error that appears when clicking on button ONLY in simulator - works fine when ran locally.
<img width="306" alt="image" src="https://github.com/user-attachments/assets/6fb5f3be-6e46-4a21-9cd2-7d9ab142d795">

### Environment

```markdown
- FlutterFlow version: 4.181+
- Platform: Flutterflow simulator
- Browser name and version: Firefox and chrome LTS
- Operating system and version affected: Windows and Mac
```

### Additional Information

I cannot test my project in the simulator anymore.

**Comment by paulperez-dev** [comment]
Hi @Icundiff! I'm sorry but we are unable to reproduce this issue from a blank project, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with ensuring your project is configured correctly!

**Comment by lcundiff** [comment]
I reached out to support, and they were able to fix the issue. It wasn't specified how it was fixed, but something under the hood of my project.
