### ISSUE TITLE
Flutterflow web app in Chrome goes to full grey screen on startup.

### ISSUE THREAD

**Issue by edieckert** [FlutterFlow/flutterflow-issues#3613]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As of 6p Central Time on 8/12/2024, I am getting a gray screen when I go to flutterflow.io in chrome Version 127.0.6533.100 (Official Build) (64-bit) on Windows 10.  The full windows install with version 4.1.82+ loads fine as a stand alone app.  The installed PWA also goes to full grey screen. 
![image](https://github.com/user-attachments/assets/ecfc944a-b3e4-430c-a8aa-66a82433dc78)

### Expected Behavior

I should see the UX for flutter flow and be able to select a project.

### Steps to Reproduce

Just start it up with that version of Chrome and it goes grey.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

None, cant get to the UX

### Visual documentation

![image](https://github.com/user-attachments/assets/7c7fc80a-c0aa-4850-9a10-406d531f8688)

### Environment

```markdown
- FlutterFlow version: Cant tell but it is probably 4.1.82+
- Platform: Windows PWA/Browser with chrome.
- Browser name and version: chrome Version 127.0.6533.100 (Official Build) (64-bit) on Windows 10
- Operating system and version affected: Windows 10 Version	10.0.19045 Build 19045
```

### Additional Information

I can't see or load any projects after login to flutterflow.io

**Comment by edieckert** [comment]
Additionally: I can sometimes get the project screen list to come up properly.  When I do, the same grey screen happens when I load any project either big or small.  

Another note: The site will load fine in firefox latest version.

**Comment by Alezanello** [comment]
Hello!!

I’m sorry to hear that you’re experiencing this issue. To help us take a deeper look, could you please share a Bug Report Code from your project so we can verify that the dependencies are correctly set?

You can generate the Bug Report Code by right-clicking on any widget in the Widget Tree and selecting "Get Bug Report Code" from the dialog that appears.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b2d26e33-ae72-46c0-9b0e-e8148367bae5/8c363b31-96a9-4533-b741-9fad099f0bec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMmQyNmUzMy1hZTcyLTQ2YzAtOWIwZS1lODE0ODM2N2JhZTUvOGMzNjNiMzEtOTZhOS00NTMzLWI3NDEtOWZhZDA5OWYwYmVjIiwiaWF0IjoxNzIzNTU1NzcxLCJleHAiOjMzMjk0MTE1NzcxfQ.4p3O5K-JI1a152W0pwNgWeNd1S4RGE6pA9AnRoeekbM " alt="image.png" width="475" height="342" />

Thank you!

**Comment by FutureWildOne** [comment]
I am experiencing the same behavior, on MacOS. Chrome shows a grey screen on opening a project. 
This started after a Chrome update. Safari works fine.

Chrome: Version 127.0.6533.100 (Official Build) (arm64).
MacOS: 14.5 (23F79)

**Comment by lechu131313** [comment]
I have the same issue. Is there will be any response?
The same version of Chrome on Win11

**Comment by ghost42-prog** [comment]
I have the same issue. sometimes I can access but my projects won't load. 

Chrome Version 127.0.6533.120
Windows 11, version 23H2

However it works on Microsoft Edge

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by ghost42-prog** [comment]
.Hello,

it works fine now. thank you for the heads up.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
