### ISSUE TITLE
Item at Index (First, Last, Specific) on empty collection throws No Element error

### ISSUE THREAD

**Issue by jhfeps** [FlutterFlow/flutterflow-issues#3615]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using Item at Index with the option being set to First (or Last) on a list / collection that is empty (e. g. when an applied Filter did filter every element) an error "No Element" is being raised.

The underlying code that FlutterFlow generates in that case comes down to "list.first" which obviously throws an error, in case there are no elements.

![Screenshot 2024-08-13 131054](https://github.com/user-attachments/assets/685f1177-5eb6-4a2a-81b4-b0b79ab7d416)

### Expected Behavior

When using Item at Index with the option being set to First (or Last) on a list / collection that is empty (e. g. when an applied Filter did filter every element) a null value should be returned using Darts builtin function list.firstOrNull and the null coalescing operator for subsequent operations.

The underlying code that FlutterFlow generates should come down to "list.firstOrNull?" which allows the app to still function in case there are no elements.

### Steps to Reproduce

1. Create new app state of name **list1** and of type **String** and enable **Is List** 
2. Create new page
3. Add text widget on the newly created page
4. Select the text widget and set its text to be set from a variable 
5. Select the list1 app state variable
6. In _available options_ choose **Item at Index** and **First** as _List Index Options_
7. Run the app in Test Mode
8.  This will result in an error  

![Screenshot 2024-08-13 132247](https://github.com/user-attachments/assets/074e5f01-d867-4d4e-a071-ec42583a4f81)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9Wljs4KUN+UL00sNobbxAjIoDoPJkUacnOdlpCcMznd2NPKEWGnkMB/s7RifHPJfEVEw+rfoRY+cxQFwuXYDu/aoSoBZOwf38lHZhjIH2O0rarpBFSVbBfWCUb7U+MfvK/cHbqHo/7Zwh9f6PHaOI=

### Visual documentation

App State:
![image](https://github.com/user-attachments/assets/b6c4b49d-dbcd-4b4f-b8fe-af85fec9f33b)

Text Widget:
![image](https://github.com/user-attachments/assets/db0b2a22-3f8c-419f-ae82-01794387295c)

Preview:
![image](https://github.com/user-attachments/assets/8e7c016c-3f24-4cd2-aa4a-8fd719b99f3d)

Test Mode:
![Screenshot 2024-08-13 132247](https://github.com/user-attachments/assets/48c0d231-cb69-49c7-94e7-a81543e0e880)

### Environment

```markdown
- FlutterFlow version: v4.1.81+
- Platform: Web, iOS
- Browser name and version: Microsoft Edge for Business Version 127.0.2651.98 (64-Bit)
- Operating system and version affected: Web, iOS
```

### Additional Information

This issue throws a hard error for an edge case that could be handled by FlutterFlow itself and makes working with lists using Item at Index way too cumbersome, as one would need to wrap this in a conditional widget etc, whereas FlutterFlow could simply make use the specificed Default Value of a widget property

**Comment by Alezanello** [comment]
Hello!

I see the issue you're encountering. This can be managed by setting a default value after selecting the first item from the list, which modifies the code generated by FlutterFlow.

Change the code from:

```dart
Text(
  FFAppState().testingList.first,
  style: FlutterFlowTheme.of(context).bodyMedium.override(
    fontFamily: 'Readex Pro',
    letterSpacing: 0.0,
  ),
),
```

To:

```dart
Text(
  valueOrDefault<String>(
    FFAppState().testingList.first,
    'Test Title',
  ),
  style: FlutterFlowTheme.of(context).bodyMedium.override(
    fontFamily: 'Readex Pro',
    letterSpacing: 0.0,
  ),
),
```

This approach ensures that if the list is empty, the default value ('Test Title') is used, which you can set in the FlutterFlow UI Builder.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a06bf2f0-26ad-4da1-974b-a8b6fbaab091/3ef2c771-9727-4307-aacc-f00d9f0b0cb1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMDZiZjJmMC0yNmFkLTRkYTEtOTc0Yi1hOGI2ZmJhYWIwOTEvM2VmMmM3NzEtOTcyNy00MzA3LWFhY2MtZjAwZDlmMGIwY2IxIiwiaWF0IjoxNzIzNjM3MTM0LCJleHAiOjMzMjk0MTk3MTM0fQ.repYs8epk1Z5W9ejw4MPvPr3Xh2vBQX27XTYc9jCRR4 " alt="image.png" width="1128" height="562" />

**Comment by jhfeps** [comment]
Hello Alezanello,

thank you for your response.

We've tried your approach already and just to double check I did try it again, which still fails with a hard error "No Element". I'm pretty sure this is due to accessing a list's .first item while the list is empty will throw (?) in Dart. See below for screenshots.

The following is a minimal sample code is using valueOrDefault with accessing an empty list's first item and demonstrates it as well (you can run it at https://dartpad.dev f.e. )
```dart
// Implementation https://pub.dev/documentation/flutter_conscent_plugin/latest/paywalls_flutter_flow_flutter_flow_util/valueOrDefault.html
T valueOrDefault<T>(T? value, T defaultValue) =>
    (value is String && value.isEmpty && value == "") || value == null ? defaultValue : value;

void main() {
  final List<String> empty = [];
  print(valueOrDefault<String>(empty.first, "No Data")); // will throw No Element error
}
```


---------------------------
![image](https://github.com/user-attachments/assets/ef517e83-a9ab-4868-9b00-fe5d36745bbd)

<img width="400" alt="image" src="https://github.com/user-attachments/assets/13b561e9-7a29-4cdd-a18b-df4c92506f13">

![Screenshot 2024-08-14 165711](https://github.com/user-attachments/assets/aaaf22c0-8851-4a16-95de-c3504e859167)

**Comment by tweeksoft** [comment]
Hello, I am experiencing the same issue as described in the mentioned ticket. Could this problem be resolved?
Thank you and best regards

**Comment by jhfeps** [comment]
Hello Alezanello,

I think you might have missed my previous response.

First of all thanks for your response.

We've tried your approach already and just to double check I did try it again, which still fails with a hard error "No Element". I'm absolutely certain this is due to accessing a list's .first item while the list is empty will throw an exception "Bad State: No Element" in Dart. See below for screenshots.

The following is a minimal sample code and equivalent to the code you posted using valueOrDefault with accessing an empty list's first item to demonstrates it. (you can run it at https://dartpad.dev f.e. )
 
```dart
// Implementation https://pub.dev/documentation/flutter_conscent_plugin/latest/paywalls_flutter_flow_flutter_flow_util/valueOrDefault.html
T valueOrDefault<T>(T? value, T defaultValue) =>
    (value is String && value.isEmpty && value == "") || value == null ? defaultValue : value;

class Obj {
  final String name;
  Obj({required this.name}) {}
}

void main() {
  final List<String> empty = [];
  final List<Obj> emptyObjs = [];
  // print(valueOrDefault<String>(empty.first, "No Data")); // will throw No Element error
  // print(valueOrDefault<String>(emptyObjs.first.name, "No Data")); // will throw No Element error
  // print(valueOrDefault<String>(emptyObjs.firstOrNull?.name, "No Data")); // will work, optional chaining null coalescing for deep property
}
```

![image](https://private-user-images.githubusercontent.com/126243893/357878033-ef517e83-a9ab-4868-9b00-fe5d36745bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDIyNDAsIm5iZiI6MTcyNDE0MTk0MCwicGF0aCI6Ii8xMjYyNDM4OTMvMzU3ODc4MDMzLWVmNTE3ZTgzLWE5YWItNDg2OC05YjAwLWZlNWQzNjc0NWJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwODE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWJiZTQ5MTlhOTE5MmFhZGVhY2Q2Yzk4YjBjZTU4ZjljMmFkMzIxMWVmOWY3OTUxZGQ1ZWQ4NDRkYzM3YWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RyRuFtC36Ta4h1CLrwGgMzjGsrkTpWTOHUXsjsuWOFk)

<img alt="image" width="400" src="https://private-user-images.githubusercontent.com/126243893/357876233-13b561e9-7a29-4cdd-a18b-df4c92506f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDIyNDAsIm5iZiI6MTcyNDE0MTk0MCwicGF0aCI6Ii8xMjYyNDM4OTMvMzU3ODc2MjMzLTEzYjU2MWU5LTdhMjktNGNkZC1hMThiLWRmNGM5MjUwNmYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwODE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2JjOTUwNDlhZmJhZTI2MTUwOTIxNjhkODE4NWNiMzlmODdmMjJjMzI4YjQ4YjQxMjQ3ODMyNTBiYzA1ZTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XBsEAG36YTa5X8nJ4A3jqhg4RTaxloum1gmyW3ALpyY">

![Screenshot 2024-08-14 165711](https://private-user-images.githubusercontent.com/126243893/357876471-aaaf22c0-8851-4a16-95de-c3504e859167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDIyNDAsIm5iZiI6MTcyNDE0MTk0MCwicGF0aCI6Ii8xMjYyNDM4OTMvMzU3ODc2NDcxLWFhYWYyMmMwLTg4NTEtNGExNi05NWRlLWMzNTA0ZTg1OTE2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwODE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTY0MjVmOTg4MWYxY2VmMWFhODhmNDJmYmM2Mzg3N2VhNDZhMTJkMjFiNmIzYzQ0ZGVhMWIwYjA3YjhjMTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mZ37G2p9-867iPz-3RaX2uFZuP30tTPb9_f_mWmtJVI)

**Comment by tweeksoft** [comment]
https://community.flutterflow.io/ask-the-community/post/bad-state-no-element-cLiyySLZiBr0xJt
https://community.flutterflow.io/ask-the-community/post/cLiyySLZiBr0xJt
https://community.flutterflow.io/ask-the-community/post/5gS4iPz6Wf3iEeD
https://community.flutterflow.io/ask-the-community/post/1krrOSwTTFiD1S4
https://community.flutterflow.io/troubleshooting/post/2fztJ2pemU8ilhi

**Comment by tweeksoft** [comment]
Hello, this issue is affecting multiple people. It’s unacceptable that this problem persists. Please fix it immediately

**Comment by jhfeps** [comment]
Please check my previous comment. Thank you.

**Comment by Wojtek-G** [comment]
Hi, I have same issue on one of my projects. I get this error, but when I restart the app (hard close on production or refresh local test) the error is gone.

**Comment by Wojtek-G** [comment]
> Hi, I have same issue on one of my projects. I get this error, but when I restart the app (hard close on production or refresh local test) the error is gone.

I've already tried so many things, both with conditionals, show after load, refresh, clear ... same issue.

**Comment by Alezanello** [comment]
Hello everyone,

First, I sincerely apologize for the delayed response to this issue. I want to assure you that I will escalate this to the engineering team for a fix, as I can confirm the problem exists. Even with a default variable value, it still appears as if no element is present.

Once again, I'm truly sorry for the time that has passed, and I appreciate your patience.
