### ISSUE TITLE
Conditional builder & multiple conditions window UI overflow

### ISSUE THREAD

**Issue by Mattmannn** [FlutterFlow/flutterflow-issues#3617]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you add more than a dozen conditions to the conditional builder or in multiple conditions window (for example when you want to add variable icons, but not exclusively), the condition UI elements overflow to the point at which the scroll bar doesn't cover the entire column height and you are unable to scroll down enough to click "add another condition".

### Expected Behavior

The scroll bar should cover the entire column height, leaving some end spacing to ensure users can add as many conditions as they wish.

### Steps to Reproduce

1. Add a conditional builder to a page or set multiple conditions in any circumstance (conditional visibility, variable etc.)
2. Keep adding conditions until you see that the column content keeps getting shorter and in the end gets short enough you're not able to add another condition

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SlcmAvJRNrt9A1s+NccFB/SYRHFw2U7gFlOtQEAo3G4PpBLQTXOqmSFRuZ9eiSnxiP2GjjngB+s7PvvP1DsADaU6WGLlz+YdiEDr1e16gWraMPLisSEF9O8JjfRG85MC7mR1QKs5idU0lxkyHNe7KEnLcJZz3PVUvIf+kCLP/nXCLKiWyNhQx/zUOImmsCsoXIVDq+f6QspZl1eTjzw==

### Visual documentation

![screenshot ff](https://github.com/user-attachments/assets/7b998dbb-97b0-4c41-af23-beaf46fdf951)

### Environment

```markdown
- FlutterFlow version: 4.1.82
- Platform: 
- Browser name and version: N/A
- Operating system and version affected: Windows 11 23H2 64-bit
```

### Additional Information

It is most likely due to some hard-coded px margin in some part of the condition UI component or a lack of scrollable end spacing in the column - i.e. a simple fix.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I was able to replicate the issue easily. I'll be forwarding this to the engineering team for a potential fix.
