### ISSUE TITLE
Widget Action Not Working - Unable to Sign up New Users

### ISSUE THREAD

**Issue by daisyramos317** [FlutterFlow/flutterflow-issues#3618]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unable to sign up new users with unique emails. App buffers and stays stuck at the Sign Up screen. User is created in Firestore but the app doesn't proceed to the next action which is the Onboarding flow then Home screen

### Expected Behavior

User is able to sign up and proceed to the Onboarding flow actions followed by the home page

### Steps to Reproduce

1. Try to sign up as a new user
2. Select Get Started
3. App buffers and stays in a stale state
4. Select Get Started again 
5. Notice this error - `Error: The email is already in use by a different account`

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SlvLlx411xLQB1pPqYMZR/TkvJkx+bZIRjuxQEEkYC5DxP5ktXOjASEhVXd+/TAl2Ilv9oD4K+t2Mv979E+QHAy6Bb4Q7wc9uWAyXLWWWM7rXCaisVkZCTZhnJEuV4Jmvgx1NLtF2dU4C3FyQHdysbBTaGJDvCkgdRvijItvUnkK9Ahm6Xn0Jg1ZSfCvr

### Visual documentation

![Screenshot 2024-08-13 at 3 44 58 PM](https://github.com/user-attachments/assets/62953207-b405-454e-82af-91666badad6a)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: iOS 17.5.1
- Browser name and version: Chrome Version 126.0.6478.183 (Official Build) (x86_64)
- Operating system and version affected: iPhone 12 Pro, iPhone 15
```

### Additional Information

cc: @elliefrost15

**Comment by Alezanello** [comment]
Hello!

This issue appears to be related to your Firestore rules. Please check the Firestore Database to see if the user you just created has a document with all the expected information.

If the document is missing the information you set during the "Create Account" action, you may need to adjust your Firestore rules. Try changing the rules for the collection from "Authenticated User" to "Users Collection" to ensure the data is correctly written.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f314e011-cb02-46ba-9375-de8ee5484dc9/11925c52-dcab-4b19-9ecc-aa58edda9482?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMzE0ZTAxMS1jYjAyLTQ2YmEtOTM3NS1kZThlZTU0ODRkYzkvMTE5MjVjNTItZGNhYi00YjE5LTllY2MtYWE1OGVkZGE5NDgyIiwiaWF0IjoxNzIzNTg1ODI0LCJleHAiOjMzMjk0MTQ1ODI0fQ.MjQhaf9zIKzrWj-ZAfVr0dLBkLhba8NmSsM1kku_2eo " alt="image.png" width="514" height="112" />

**Comment by daisyramos317** [comment]
thanks for the quick reply @Alezanello from taking a look at our setup, this seems to match what you suggested

<img width="1144" alt="Screenshot 2024-08-13 at 4 17 35 PM" src="https://github.com/user-attachments/assets/44dc1dd2-22df-4b74-8876-fff05966ac3b">

**Comment by Alezanello** [comment]
Hello!

The screenshot I shared was taken directly from your project, which is why it matches. You need to change the Firestore rules from "Authenticated Users" to "Users Collection." Currently, if only authenticated users can write to the "beauties" collection (where your users are created), then anyone who is not authenticated cannot create a document in that collection.

As a result, when a new account is created, it only creates the credentials for access (which is why you see that the user's email is already registered) but doesn’t create the corresponding document in the correct collection. This is why the app remains on the same screen after you click "Get Started."

**Comment by elliefrost15** [comment]
Making the change but it does make the user document in Firebase and it
updates the record with the uid as a string right after being created.

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
