### ISSUE TITLE
SocialFeed doesnt show data correctly

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#3623]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using the flutterflow social template. When showing story and posts feed, it is showing evey user stories and posts.

### Expected Behavior

It should be presented only stories and posts from user that the authenticated user is following.

### Steps to Reproduce

Go to main_feed page (just click on the first icon of the navbar)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPHq2491xLRF+KnxYcFarygUCUMdXZIRmOtvewgjF774B7AtOuP8YhFCTuKzaH1iIE2jkno1//TLj+D1DsEDHzSbf6pM/6VqEhPPYzigRZCNEcywRnJAFp9XC3HC5qSCkBYlJfVoW3gNw12ueti9Fj+Cf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot_5](https://github.com/user-attachments/assets/bcdc6c93-2f0b-4cd1-a1d0-3b0a9369fcd7)

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform:windows
- Browser name and version:chrome
- Operating system and version affected:
```

### Additional Information

I believe in the list view query should have a filter to filter only folowee. I can do it if you instruct me how

**Comment by Alezanello** [comment]
Hello!

To achieve the desired result, you need to filter the query based on the followers. Currently, you’re only ordering the results, but not applying a filter. You should filter the stories so that only those where the user reference is in the current user's list of followers are shown.

**Comment by ghost** [comment]
I see it, but I dont quite know how to do. the follow system is make of a friends table with follower and followee, I understand i should filter for postuser only who belongs to a friends that exist a document being as folowee and follower as the auth user, but how to do it in practice? I tryed getting from a collection the friends documents that have auth user as follower, and in the flter, posts as userpost are IN the friends as followee, but it didnt work.

**Comment by ghost** [comment]
Thank for your help, I am asking here only because it is a template. As you can see in the picture, I am trying to filter only posts as userpost in IN the friends as followee, this friends query is a previous query of friends collection with filter on auth user as a follower. What could be wrong with this approach?

![Screenshot_8](https://github.com/user-attachments/assets/448bc917-3782-426b-852b-774246bf54bf)

**Comment by Alezanello** [comment]
Hi there, and sorry for the late response!

I believe there are several similar approaches to what you’re trying to achieve available in our community or even in the marketplace as free items. I recommend taking a look at those to understand the best way to implement this logic. Since I haven’t personally done it before, I’d rather not steer you in the wrong direction. It’s better to learn from the experts in our community! :)
