### ISSUE TITLE
Query Changed automatically

### ISSUE THREAD

**Issue by rgiraldo** [FlutterFlow/flutterflow-issues#3624]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a query on an action with AND operator. But later, this query appears with OR operator.
![image](https://github.com/user-attachments/assets/ae9d7163-63d8-4f78-b590-e561bbc3d656)

### Expected Behavior

I want my query as defined in the action. I want my query keeps thw AND operator.

### Steps to Reproduce

add action
add query to action
add filters with AND operator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjM/q25NPvsdG+Kr+bsBB/CkRHG43R7s4scsZa0kdB4joPLJ+Osn8TxdWTtDmdENhHGaWhlEBwMLQiePLO/FePTGtfJh+zalqSg/xe3q8R5SzDMyWPmhARP9WGlSh5LWjhhBAPbJpR1Fg12WYGNnJYCnvGZO/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/ac880fa8-dae8-442c-a3e1-f5399dd12152)

### Environment

```markdown
FlutterFlow version FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2
Platform Android, WEB, IOS
Browser name and version (web): Chrome
Operating system and version (desktop) windows 10
```

### Additional Information

It is very stressfull change the queries each time i want to generate the app

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue in a new blank project. Have you tried removing the query action and creating a new one from scratch? It’s possible that recent updates may have caused the action not to save correctly, so creating a new action might help override any lingering issues.

**Comment by rgiraldo** [comment]
Hi, thanks for your feedback,
I noted that this situation arises when I have two queries in a chain
actions. I replicated this scenario in other project and a query was
changed when I go away to another page or other project.

Please, try with two o more queries in the same chain actions.

Regards,

Raúl

**Comment by rgiraldo** [comment]
It's working now.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
