### ISSUE TITLE
Unable to Get Original File Name of Photo/Video/Pdf which is being uploaded 

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#3629]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

giving current timestamp + extension 

### Expected Behavior

Need the correct file name which is saved in mobile

### Steps to Reproduce

Add Upload Media Action and send to Api

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NO

### Visual documentation

NO

### Environment

```markdown
- FlutterFlow version: v4.1.82 
- Platform: WEB
- Browser name and version: chrome
- Operating system and version affected: WEB / ANDROID / IOS
```

**Comment by paulperez-dev** [comment]
Hi @Mdmuzammil16! Can you please provide the steps to reproduce, the bug report code and give a little more context? Without these details it is hard for us to identify the issue.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
