### ISSUE TITLE
Bug with Monthly vs. Annual Billing

### ISSUE THREAD

**Issue by MaggieThomann** [FlutterFlow/flutterflow-issues#363]
## Expected behavior (required)
I should be able to easily switch my account from monthly to annual billing.

## Current behavior (required)
When I attempt to cancel my monthly plan (so that I can instead sign up for annual billing), I see an error message:

"Something went wrong. We've been notified of this issue. We will make sure to cancel your subscription or issue a refund if it fails to go through."

## To Reproduce (required)
Navigate to the "McMack Media" organization page and attempt to cancel the plan.

### Bug Report Code (required, generate from Widget Tree)
N/A to Widget Tree

## Context (required)
On December 10th, I tried to upgrade our plan to be billed annually, rather than monthly. Instead, my account reverted to a "Standard" plan and I was charged $204.45. My husband was somehow removed from the team and then I was billed $321.41 on December 26th.

When I reached out to Support on December 26th to have the $204.45 charge refunded and to fix our account so that it was annually billed, it took Support 17 days to respond to my inquiry. Then, Support refunded the $321.41 charge and informed me that my subscription was cancelled and that I'd no longer have chat access. My intent all along has been clear: I wanted the $204.45 charge refunded and my subscription changed to be billed annually for a Team Pro plan (with my husband on the plan).

Additionally, I no longer have access to the Stripe page where I can see my billing schedule and history. At this point, I have no understanding of when I will be billed, how much I will be billed for, and why my husband's current access level is Pro when I don't see him as a part of my Team at all.

### 2022-12-26: Screenshot of attempting to upgrade to Pro. 
<img width="1076" alt="Screenshot 2023-01-17 at 10 57 22 PM" src="https://user-images.githubusercontent.com/15825518/213021309-662ac80c-2c3a-45df-89e2-ee6f0214b770.png">

### 2022-12-26: Screenshot of my account when I initially reached out to support. Note the 2/1 seats used (??)
<img width="1653" alt="Screenshot 2022-12-26 at 11 51 13 AM" src="https://user-images.githubusercontent.com/15825518/213020902-afbe2fc4-b14b-4c22-9495-52089e186787.png">

### 2023-01-17: Screenshot after I attempted to cancel plan
<img width="1509" alt="Screenshot 2023-01-17 at 10 46 31 PM" src="https://user-images.githubusercontent.com/15825518/213019400-88d74dee-a2ca-4a38-b9ce-f1547465bae8.png">

### 2023-01-17: Screenshot of Michael's account, which shows him as a team member
![michael-account-screenshot](https://user-images.githubusercontent.com/15825518/213019997-2f029b1b-fa84-48fd-90d9-0376337e55ec.jpg)

### 2023-01-17: Screenshot of my account, which does not show Michael as a team member
<img width="1432" alt="Screenshot 2023-01-17 at 10 50 27 PM" src="https://user-images.githubusercontent.com/15825518/213020059-c975496f-dead-41e5-8419-b50e61267e01.png">

**Comment by asmengistu** [comment]
Sorry about this nasty bug – should be fixed now.  Thanks so much for the detailed report!
