### ISSUE TITLE
FF crashes a lot with every action made when building my app

### ISSUE THREAD

**Issue by plansagro** [FlutterFlow/flutterflow-issues#3630]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

During the process of building my app, FlutterFlow hangs on every action we do for a few seconds. 
This has been happening for weeks. 

We have already used the desktop version on Mac, and have also tested it on several browsers.

The problem remains.
It is very difficult to perform any activity on the system.

### Expected Behavior

We expected the system to respond normally as it was before.
And we could complete the creation of our application in a fluid way and without the tool crashing.

### Steps to Reproduce

Crashes occur in any activity we do when building the app.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMjfsJJ1rv1c1pDqccB7/WAWKWE4UK84scp/bxIgGIDzPOw+ZPXsUFhvTumiSlZYIUSmmnsFwvzei97xG/A6JQ6dG9VazLhLFzzjUkChQZOBDKuoWERRBZlMCGq018GJriV5CNdhZVIh602yP9yucHTBJLrtImdISq/LZO4=

### Visual documentation

Everything freezes, there is no way to get an image of it.

### Environment

```markdown
- FlutterFlow version: v4.1.81+
- Platform: Web and MacOS Desktop
- Browser name and version: Chrome 127.0.6533.101 (But we test on several other browsers)
```

### Additional Information

This problem is harmfully impeding the continued development of our app.

**Comment by Alezanello** [comment]
Hello!

Are you experiencing crashes on the web as well, or is it just a bit laggy? We do have a known issue on macOS where using `ctrl+z` after the project syncs can cause a crash. Could you confirm if this happens specifically when you perform that action, or is it more random or tied to certain tasks?

For the web version, what’s your experience like? Is it stuck on an infinite loading screen, or does it also crash?<br><br> Any details you can provide will help us better understand the issue.

**Comment by plansagro** [comment]
Crashing happens all the time, in any action.
This happens in both versions: desktop or web.

It crashes a lot during the entire app creation process.

**Comment by Alezanello** [comment]
Could you please try to record a video crashing the Web<br>and share the Crash Logs of the MacOS?

**Comment by plansagro** [comment]
I can't record the video, but I'll explain better what happens.

With every click we make, whether on screens, in settings, or to add new components, we have to wait a few seconds for the action to happen. 
This waiting time varies, sometimes 2 seconds, other times 5 or more. 

This same slow response to each action occurs in the desktop version, as well as on the web.

(We tried to install the desktop version on Windows, but it doesn't run there, another error occurs. When FF is opened, it closes automatically.)

**Comment by MartinLockheart** [comment]
I've been dealing with the lagging response times periodically as well, and there have been a lot of times where I select a variable for an action and it says unset after I confirm it. Sometimes after navigating away from and back to the page it's there, sometimes it's not. It's been very odd, and it's not consistent at all. I currently only use the Web version.

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
