### ISSUE TITLE
doctor output reports incorrect error on cocoapods; prevents setup for local run 

### ISSUE THREAD

**Issue by xmatthewx** [FlutterFlow/flutterflow-issues#3634]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am setting up for local testing. Flutterflow's doctor output reports: 

> CocoaPods 1.11.3 out of date (1.13.0 is recommended).

However, running flutter doctor via terminal correctly reports

>  CocoaPods version 1.15.2 

I have unintalled cocoapods via gem and brew, and manually deleted any lingering files. I reinstalled via brew. I have run brew link --overwrite cocoapods to ensure it is properly linked. 

### Expected Behavior

Fluttflow's Doctor output should match flutter's doctor. Cocoapods should show as version 1.15.2. 

### Steps to Reproduce

1. Update xcode on M1 mac with macOS 14.6.1
2. run gem uninstall cocoapods
3. run brew uninstall cocoapods
4. run brew install cocoapods
5. run brew link --overwrite cocoapods
6. tap to setup local run in flutterflow 
7. tap install or confirm flutter sdk
8. view doctor output 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ki8mB05Ngrt9f7q6Jc/pahSQUNjM6U40WltYbUU4jNb7nG7YAW/SkQE9WZ7yhdH03Jk788WcK0NqMhtzIN8IEHwmeUaZxzqhtWjzvVT+jb7qPBc6WS3ZQLNpKCECF0Ym7gBF+D7JuLyE52l2lN+6tXj3dNqLTDHo/MM+YGJ7UjXPuQ0SLb3kNh1JWeC/v

### flutterflow doctor output

```
[!] Flutter (Channel stable, 3.22.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/matthew/Library/Application Support/io.flutterflow.prod.mac/flutter
    ! The flutter binary is not on your path. Consider adding /Users/matthew/Library/Application Support/io.flutterflow.prod.mac/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/matthew/Library/Application Support/io.flutterflow.prod.mac/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/matthew/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ! CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### flutter doctor output

```
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/matthew/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/matthew/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

```

### Environment

```markdown
- FlutterFlow version: 4.1.82
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 127.0.6533.101
- Operating system and version affected: MacOS 14.6.1 (23G93)
```

### Additional Information

I can't test locally. Blocks me from publishing.

**Comment by paulperez-dev** [comment]
Hi @xmatthewx! Can you please try reinstalling the FlutterFlow app?

If the issue persists, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with this behavior since version 4.1.82 should come with CocoaPods v.1.15.2!

**Comment by xmatthewx** [comment]
Thanks @paulperez-dev. I deleted and reinstalled the app, but it did not fix the issue. I will reach out to support. 

When I attempt to test on the iOS simulator, it fails to launch. The log includes the following: 

``` 
CocoaPods 1.15.0 is available.
To update use: `gem install cocoapods`

[!] Failed to download 'FirebaseFirestore': [!] `FirebaseFirestore` requires CocoaPods version `>= 1.12.0`, which is not satisfied by your current version, `1.11.3`.

Running pod install...                                          
Warning: CocoaPods recommended version 1.13.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

Error running pod install
Error launching application on iPhone 15 Pro Max. 
```

**Comment by xmatthewx** [comment]
I am confident that my setup is correct. I believe the problem is coming from flutterflow's export of the project. 

I accessed my exported project and opened it in xcode. When I run it from xcode... 
- xcode reports that `/Users/matthew/Library/Application Support/io.flutterflow.prod.mac/car/ios/Flutter/Debug.xcconfig:1:1 could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths.`  
- I looked in the project's ios directory. I see `podfile` and `Pods` directory, but the directory just has 3 empty folders, no files, no hidden files.  
- The flutterflow export does not seem to be exporting all the necessary files

There is no version 1.11.3 installed on my machine. The must be coming from flutterflow. 
- I fully removed all versions of cocoapods and then reinstalled via homebrew
- Xcode and Command line tools are fully up to date (15.4). 
- In terminal, running `pod --version` reports version 1.15.2 for cocoa pods
- In terminal, running `flutter doctor` reports CocoaPods version 1.15.2 
- Flutterflow still reports that CocoaPods 1.11.3 out of date
- I removed the flutterflow app and reinstalled

Here is [my project](https://app.flutterflow.io/project/move-the-car-honey-cjzg7r?tab=uiBuilder&page=Welcome).

**Comment by paulperez-dev** [comment]
Hi @xmatthewx,

Were you able to resolve the issue, or is it still occurring in the latest version (5.0)? Please let me know, and I’d be happy to assist further if needed.

**Comment by xmatthewx** [comment]
Thanks @paulperez-dev for following up. Yes, the problem is now resolved. I am not certain what the fix was in the end. 

For anyone who comes along reading this later, I suggest that you make sure to manually remove anything lingering in the following directories before you reinstall any requirements. 

- `/opt/homebrew/Cellar/cocoapods/`
- `~/.cocoapods`
