### ISSUE TITLE
Dynamic Links does NOT work

### ISSUE THREAD

**Issue by dr-shoe** [FlutterFlow/flutterflow-issues#3635]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using this link on iOS, it redirects to the App Store even though the app is already installed

https://appName.page.link/?link=https://appName.page.link/homeAbout&apn=com.mycompany.appName&ibi=com.mycompany.appName&ifl=https://apps.apple.com/jp/app/appName/id&afl=https://play.google.com/store/apps/details?id=com.mycompany.appName&efr=1

### Expected Behavior

To get to the link (https://appName.page.link/homeAbout)

### Steps to Reproduce

To test the link.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMmAx89gofVA1pDLbcFvnikXJno1TLJMt9VxSUghfZDuOuwcYfekP05LYte9dH9iB1GbsD4CwtrKi97xVu4DGzSCQaJI1q5XQQrJQmS6RLK4CJa0XWhRO9lYG0yH5rurnRQlBPphR1oS31yme/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/02cd277f-6656-4ae0-a2f9-44fffee1bf48)

### Environment

```markdown
- FlutterFlow version: v4.1.8
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

This issue isn't specific to FlutterFlow but rather how Firebase Dynamic Links behave on iOS, which is a known issue. Unfortunately, Dynamic Links don't always work correctly on iOS. We have an enhancement request in place to allow modifications to the `info.plist` file to address this. You can follow the discussion and updates on this issue here: [GitHub Issue #3195](https://github.com/FlutterFlow/flutterflow-issues/issues/3195).

**Comment by dr-shoe** [comment]
Thank you!
I read #3195 and how to solve this issue is to manually change info.plist.
If downloading the code and modifying the info.plist file makes it work, doesn't that indicate that the issue lies with FlutterFlow? It would mean that users relying solely on FlutterFlow wouldn't be able to use Dynamic Links.

I dont use custum domain for dynamic links, so why did it happen and is there any solutions FF only user can have?
