### ISSUE TITLE
Debug Built failed (no errors)

### ISSUE THREAD

**Issue by NBo-uniNL** [FlutterFlow/flutterflow-issues#3639]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With no explanation on why the built failed, I am a bit stuck here. 

### Expected Behavior

a debuggable version would be nice :)

### Steps to Reproduce

debug 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhvHl5YpIm9tF0L6JdPl4pCcRC08cTIMziNZ+exUbfaL1Bu02Os/CYhBBTdThaVNcDmaJjT4Cw8L9kdrhOPYnBzmdRpx9+JBXWDvke2iQR7KSEZaSYkdABZlWG26F35ivpxJ5IfttS3wu6kymfd++b3fDFOu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-08-16 180407](https://github.com/user-attachments/assets/198c7e40-2526-4af1-ba55-fd4c3c34ce97)

### Environment

```markdown
- FlutterFlow version: 4.1.8.1+
- Platform: Windows (web)
- Browser name and version: chrome 127.0.6533.100 
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!<br><br>You are right, there is no build error, I also tried to download the code to see if something happens but got the same error.<br><br>I recommend reaching out to support via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io) so they can take a closer look at this specific project issue.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
