### ISSUE TITLE
ios pod fails to install

### ISSUE THREAD

**Issue by cyberlion-ops** [FlutterFlow/flutterflow-issues#3640]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when deploying project to apple appstore, i am deploying from github i get an error: 
Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐ │ A new version of Flutter is available! │ │ │ │ To update to the latest version, run "flutter upgrade". │ └─────────────────────────────────────────────────────────┘ ╔════════════════════════════════════════════════════════════════════════════╗ ║ Welcome to Flutter! - https://flutter.dev/ ║ ║ ║ ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║ ║ statistics and basic crash reports. This data is used to help improve ║ ║ Flutter tools over time. ║ ║ ║ ║ Flutter tool analytics are not sent on the very first run. To disable ║ ║ reporting, type 'flutter config --no-analytics'. To display the current ║ ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out ║ ║ event will be sent, and then no further information will be sent by the ║ ║ Flutter tool. ║ ║ ║ ║ By downloading the Flutter SDK, you agree to the Google Terms of Service. ║ ║ The Google Privacy Policy describes how data is handled in this service. ║ ║ ║ ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and ║ ║ crash reports to Google. ║ ║ ║ ║ Read about data we send with crash reports: ║ ║ https://flutter.dev/docs/reference/crash-reporting ║ ║ ║ ║ See Google's privacy policy: ║ ║ https://policies.google.com/privacy ║ ║ ║ ║ To disable animations in this tool, use ║ ║ 'flutter config --no-cli-animations'. ║ ╚════════════════════════════════════════════════════════════════════════════╝ Resolving dependencies... Because every version of flutterflow_debug_panel from git depends on devtools_app_shared 0.2.1 which depends on pointer_interceptor ^0.9.3+3, every version of flutterflow_debug_panel from git requires pointer_interceptor ^0.9.3+3. So, because my_app depends on both pointer_interceptor ^0.10.1 and flutterflow_debug_panel from git, version solving failed. Build failed :| Step 6 script `Install pods` exited with status code 1

before this i got a different one so i moved the vm_service in the dependency_overrides. so i am guessing it's not a fix i can go through rather a flutterflow issue.
![Screenshot 2024-08-16 045156](https://github.com/user-attachments/assets/d8fa0aeb-5171-4f08-9ac1-72d81bee00cb)

Resolving dependencies... Note: vm_service is pinned to version 14.2.1 by flutter_test from the flutter SDK. See https://dart.dev/go/sdk-version-pinning for details. Because every version of flutter_test from sdk depends on vm_service 14.2.1 and my_app depends on vm_service 14.2.4, flutter_test from sdk is forbidden. So, because my_app depends on flutter_test from sdk, version solving failed.

### Expected Behavior

pods install should succeed and flutter version should be up to date and not out of date.

### Steps to Reproduce

project was exported to add capabilities from xcode (Apple sign in, Apple pay, notification, background modes).
project has both Supabase as backend and oauth, firebase for the notification. before the step above firebase was configured in the android studio. project pushed to a github branch different from the main flutterflow branch. deploy project from github to appstore. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEek8rl24V1j70F1brbK+5V9AMwJ0QlUIInj+0bWRMhfanmPe0uecjSTFtLYte5egt2DWf8vFkGp/DOj/P1Fe47PQqeGZhHya5XQRbKdz+tV66LDJOSSXcnTJ9WCGKA08O43RN+VfpvV3st3E77G/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-08-16 045156](https://github.com/user-attachments/assets/137a5380-1a2a-4e4a-80fc-90bb1f02746f)

### Environment

```markdown
- FlutterFlow version: v4.1.82+
- Platform: ios
- Browser name and version: chrome Version 127.0.6533.120
- Operating system and version affected: windows 11
```

### Additional Information

i also downloaded project to run on xcode and had the same errors when installing pods. i have done this multiple times before but this is the first time i encounter this error.

**Comment by Alezanello** [comment]
Hello!

After closely reviewing your logs, it appears that the error is related to the `pointer_interceptor` after resolving dependencies. This issue is primarily addressed here: [GitHub Issue #3601](https://github.com/FlutterFlow/flutterflow-issues/issues/3601).

Please ensure that you are compiling Flutter at version 3.22.2 in GitHub and that your `pubspec.yaml` dependencies are correct.

I’ll close this issue as a duplicate so we can follow up on the error in the other thread.
