### ISSUE TITLE
Markdown does not format streaming responses correctly

### ISSUE THREAD

**Issue by alma-biz** [FlutterFlow/flutterflow-issues#3641]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using a Markdown widget to house the response from ChatGPT API. When the response is returned from a non-streaming API, the Markdown widget works perfectly. However, when leveraging the streaming API, Markdown does not correctly format paragraphs. 

The first screenshot is the response from a non-streaming API:

<img width="307" alt="image" src="https://github.com/user-attachments/assets/98d84d05-4036-48ca-8994-4f2bba815d08">

This second screenshot is the same component with a streaming response:

<img width="317" alt="image" src="https://github.com/user-attachments/assets/f90f162c-7236-42b5-851d-3616de87ea27">

### Expected Behavior

Markdown should process paragraphs for streaming responses.

### Steps to Reproduce

1) Create a ChatGPT streaming API
2) Tie the response to a Markdown widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkcjc35Z1m+Fc+KrQbMIxiSoQM0MdXYI7m+4bcw4dfe/4O7MUZ+D4UFJuYNyzaH46PmGWnT4F0/TOhYbTNPECKTiac5w5zZZqexPPbHqmRLaOO7jtXHJSM+JWGUyD5LeFhwp7CMZ0WC0R62WyGNitRT+Cf9qOYwx5e6fDbOY=

### Visual documentation

In this video, the first response is tied to a non-streaming API, which makes the response format correctly. The second question is tied to a streaming response, where you can see that the response is not formatted correctly, specifically, there are no paragraph breaks.

https://github.com/user-attachments/assets/731af61d-d5f0-4dc1-b624-c2d3bea5bb4d

### Environment

```markdown
- FlutterFlow version: v4.1.82
- Platform: MacOS Desktop
- Browser name and version: N/A
- Operating system and version affected: Sonoma 14.5
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to reproduce this issue in a new blank project; everything in the markdown appears to be working fine. I also tested the Gemini Template, and the chat response works correctly as Markdown.

I recommend copying the free Gemini Template from the marketplace and integrating your API response to see if the issue persists: [Gemini Template](https://marketplace.flutterflow.io/item/IU338gwt7GuhIkdIUfsd).

**Comment by bags307** [comment]
I am also having the same issue.

**Comment by alma-biz** [comment]
Hi @Alezanello - I was able to recreate this in a blank project, see video below.

The Markdown widget is tied to an app state string list which is updated with the API response at each index. Screenshots of a simple setup updating just index 0 below:

**Video:**
https://github.com/user-attachments/assets/8565b06a-f3c6-48e3-9ed4-9af1b3f46ef1

**Blank Project Simple Set Up:**

**App state**
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/d5cd29eb-c024-4718-8e73-79e37ca694c2">

**API Setup**
<img width="952" alt="image" src="https://github.com/user-attachments/assets/42fe68c5-9e30-4793-84b4-1b6561c89c21">

**onMessage Setup**
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/97be1583-12af-45bd-bfdf-068cf96c6a8a">

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/43d6e56b-8c7e-44f6-8c92-fad4ac82beb6">

**Comment by bags307** [comment]
Turn off "rebuild component" it will stream as expected.

**Comment by Alezanello** [comment]
Hey alma-biz, did the suggestion of bags307 worked for you?

**Comment by alma-biz** [comment]
Thanks for the feedback @bags307 . @Alezanello , I'm going to be reviewing today, I'll let you know.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
