### ISSUE TITLE
Action output section disappeared from insert row for Supabase

### ISSUE THREAD

**Issue by mardadi-live** [FlutterFlow/flutterflow-issues#3643]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The action output section has mysteriously disappeared so I cannot get the info on inserted row for supabase anymore. This is causing error in my application. It was working before. I cannot proceed with development now due to this. Please review and fix at earliest. 

FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/4a32b341-6016-4480-9e9c-59a7baa73a87">

### Expected Behavior

Action output section is available for Define Action in Insert Row.  

### Steps to Reproduce

1. Connect to Supabase
2. Define action to Insert row 
3. In Define Action modal, Action output is missing 

FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeiPLq5YtOj7xG17nUaMBolQMwJ0QlUIInj+0bWRMhNb7rBIoXOsn4YkpLYteITVVUJ1H+8UE00+uKkezlKvU6Hwisc4B6yL5XQTvyIVy5WrKIDs+sREd7BfhmCGnCyqSNqwhTKtVYSl0sw2WuIvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="921" alt="image" src="https://github.com/user-attachments/assets/6daa3e1d-76c3-43fe-964c-65627743fb87">
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/abb36b45-f25d-45da-b416-26fe6a87751b">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2
- Platform: Apple MacOS
- Browser name and version: Flutterflow native app, web app
- Operating system and version affected: MacOS
```

### Additional Information

I was trying to retrieve the Id of rows just inserted to use in next step for data insertion in another table. This was working before.

**Comment by paulperez-dev** [comment]
Hi @mardadi-live! I saw a variable name on that field. The field is there now, right?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/be4a30f4-fc5b-490e-a627-d9cd9d60c4ef/d3b7afcc-b90a-41f6-a15e-9fe277382384?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZTRhMzBmNC1mYzViLTQ5MGUtYTYyNy1kOWNkOWQ2MGM0ZWYvZDNiN2FmY2MtYjkwYS00MWY2LWExNWUtOWZlMjc3MzgyMzg0IiwiaWF0IjoxNzI0MDE4OTY5LCJleHAiOjMzMjk0NTc4OTY5fQ.50ZYIRT3muZSihOthJ4FhSaNt2_o5Njbv96dTxo-QVg " alt="image.png" width="1587" height="814" />

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
