### ISSUE TITLE
App Settings / Languages / iOS Permission Messages not saved

### ISSUE THREAD

**Issue by Luditeker** [FlutterFlow/flutterflow-issues#3646]
Hi, I have exactly the same issue. ios Messages for permission are written in 2 places : 
1st in App Settings / Permission. This text is not used in the app.
2nd in App Settings / Languages / iOS Permission Messages. This is the one that is used in the app. 

But When I change it, I leave the settings page and come back the new text is not saved and the old text is back. 

the issue is the same for each permission: Camera, Gallery, Location.

This is blocking my Apple review, so I cannot publish the App. Very problematic...

I need help.

<img width="1080" alt="Screenshot 2024-08-18 at 14 17 40" src="https://github.com/user-attachments/assets/0cb80f80-9811-4029-8f3f-86c343c40b9b">
<img width="1070" alt="Screenshot 2024-08-18 at 14 17 20" src="https://github.com/user-attachments/assets/4ca350ee-42ac-4e28-ac1b-9ec5bd4023d9">

_Originally posted by @Luditeker in https://github.com/FlutterFlow/flutterflow-issues/issues/3013#issuecomment-2295241240_

**Comment by agreaves** [comment]
Hi @Luditeker, sorry to hear about this issue! Could you please add a Bug Report Code (right click anywhere in the widget tree to see the create bug report code option) to help us debug this issue for your project?

Edit: Also if it's not too much trouble, if there's any chance you could record this issue happening that would be _extremely_ helpful as well. Thanks! Hope to fix this quickly.

**Comment by Luditeker** [comment]
Bug Report code : IT4klcn135dOn7xH7qrtbe1vqCIRNlh5TL03pu0bFEggGLbrBIYMaePObhZvUuLidGxHKEWGjXw0+fzTj+DpDfEBNS2VGIRawpdQEhXwTn6/aoSkDs6wWHMnPJlhGGKk0Lu73RJTKtp2cnADwGeqH+iAZCbAGJ/4Zwh9f6PHaOI=

Here are the steps : 

1. The text in "Language / iOs messages" for "Camera" is : "cleanPee would like to access your camera"
2. The text in "Permissions" for "Camera" is : "To add photo to your reviews Clean Pee requires access to your camera"
3. I copy the text form "Permissions"
4. I paste that text to "Languages / iOS Messages". The test is now : "To add photo to your reviews Clean Pee requires access to your camera"
5. After a few seconds, the text revert "by itself" to : "cleanPee would like to access your camera"
6. In the running app, it is always that text that appears :"cleanPee would like to access your camera"

I noticed that the rollback of the text occurs every 60seconds (sharp).

Here is the video as well : 

https://github.com/user-attachments/assets/0363758a-cd18-499b-bd93-fd9e7e62912d

![Simulator Screenshot - iPhone 13 mini - 2024-08-19 at 09 35 03](https://github.com/user-attachments/assets/81ed8c0e-34d6-4660-b3f6-a7badda5aaec)

I have the same issue with "Location" and "Photo Library".
Thank you.

**Comment by Luditeker** [comment]
hi, 
@agreaves : do you have any feedback for me ? I have to deploy this App as soon as possible. I am blocked right now.
Thanks for your help.

**Comment by Luditeker** [comment]
Today FlutterFlow has been updated to version 4.1.83 : it has solved this bug.

**Comment by rzambroni** [comment]
Thanks for letting us know. Closing the issue.
