### ISSUE TITLE
Issue with Chart Configuration Resetting to Unset in FlutterFlow

### ISSUE THREAD

**Issue by potatohunter69** [FlutterFlow/flutterflow-issues#3647]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 X and Y axes are disappearing after set

### Expected Behavior

Should not reset

### Steps to Reproduce

Issue with Chart Configuration Resetting to Unset in FlutterFlow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Visual documentation

<img width="311" alt="Screenshot 2024-08-19 at 14 37 40" src="https://github.com/user-attachments/assets/45484fc3-12b9-4518-a307-d5c68891ee9c">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.81+ released August 7, 2024
Flutter version is 3.22.2
- Platform:
- Browser name and version: Safari and Chrome latest
- Operating system and version affected: MacOs latest
```

**Comment by Alezanello** [comment]
Hello!

This issue is currently being addressed here: [FlutterFlow Issue #3553](https://github.com/FlutterFlow/flutterflow-issues/issues/3553).

I’ll close this issue as a duplicate. Any new updates or information will be provided in the thread linked above.

Thank you for your understanding!
