### ISSUE TITLE
Supabase database query not updated when navigate back when deploy using GitHub

### ISSUE THREAD

**Issue by Jeffcyw** [FlutterFlow/flutterflow-issues#3648]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list view querying to supabase database, on Github deployment (without changing any code at all), when I navigate back after updating my database, the database won't be updated nor re-query to the new database update.

### Expected Behavior

I have a list view querying to supabase database, on normal deployment, it works fine where when I navigate back after updating my database, it will automatically re-query the database and return the updated value.

### Steps to Reproduce

1. Deploy a version directly from Flutterflow and deploy another version from Github (without changing anything in the code)
2. In the app, go to Transaction page and edit any transaction record in it.
3. Compare the 2 app difference. You will see that everything works fine when you deploy from Flutterflow (database automatically updated on back navigation), whereas deployment from Github will not have the data updated.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPXfikSEpWZ9+kTHxcL2H8sGMd/tLKvc7qA+UoMkydfIBx1YdhEDriZEKiaJ+bBqjhTnBSQJpJJVyP152jmCUkOsBYL04O2EymJ9nKSj/rJpzbDlcNGf/+D9vA+VmqQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/c778b896-093b-41e3-9e56-085cda57b298

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment]
Hello!

It's quite strange that the behavior changes based solely on the deployment. It should remain consistent unless there are specific commands in the compile process or something in the GitHub actions that could alter the app's behavior.

Sometimes, using "Navigate Back" might not trigger a new query or refresh an existing streaming query. I recommend trying "Navigate To" instead, selecting the same page, to see if that resolves the issue.

**Comment by Jeffcyw** [comment]
I've created my apps with the navigate back function so that it works well with Android back button too. Everything is fine as it is when I deploy from Flutterflow. However, just with deploying in Github, without changing a single thing, these queries doesn't work anymore. Would you able to give it a try in my app and you'll see this issue happening. Thanks.

**Comment by Jeffcyw** [comment]
Do we have any update on this? Please

**Comment by Jeffcyw** [comment]
Following up on this...

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
