### ISSUE TITLE
Copy/Paste on Web Doesn't Work

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#365]
## Expected behavior (required)
Copy/Paste on web

## Current behavior (required)
Nothing

## To Reproduce (required)
1. Apply Copy/Paste Action to anything
2. Run/Test Mode

### Bug Report Code (required, generate from Widget Tree)
ITESzcrlvJNgofVB7aXuY+1AhQAkH1x/bZJEl9caSU4gIovmO4oAd+r+VxFZOv2afHxfMVGbpzoewd2MhtntMu0CIROrTNE2k/UwKlCvHAM=

![image](https://user-images.githubusercontent.com/77738205/213208830-efc48086-b574-4edf-b030-8295f6a211fa.png)

## Context (required)
Can't test if copy/paste is working correctly. This is happening because of a cors issue with the copy api in iframes. I think we can just add the following attributes to the iframe `allow="clipboard-read; clipboard-write"`. You can see the issue described here:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

Solution:
https://web.dev/async-clipboard/#permissions-policy-integration

## Your environment
* Version of FlutterFlow used: 3.3.4)
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: 108
* Operating system and version (desktop or mobile): Mac OS Monterey

**Comment by organicnz** [comment]
Hi @johnbhiggins7. Thank you John for adding this issue 🙂

I can reproduce this problem on my app in test mode as well. However, when deploying on the web, everything works fine :)

Kind regards,
Tarlan Isaev

**Comment by shelpert** [comment]
Hi John,

We aren't going to fix this bug because it works on Run Mode and when deploying to web. I've added it to the 'Known Issues' in test mode and informed users to test on run mode.
