### ISSUE TITLE
API Calls that contain a JSON array of objects are improperly formatted 

### ISSUE THREAD

**Issue by bags307** [FlutterFlow/flutterflow-issues#3650]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A properly formatted JSON array of objects (e.g. [{"type":"text","text":"foo bar"},{"type":"text","text":"foo bar"}] will be formatted by the API call as ['{type:text,text:foo bar},{type:text,text:foo bar}'], even when properly stored in an app variable in the proper format

### Expected Behavior

this list should be passed [{"type":"text","text":"foo bar"},{"type":"text","text":"foo bar"}]

### Steps to Reproduce

Add an API variable of JSON and "isList" checked.  Pass properly formatted array.  Array will be reformatted.  This happens regardless of formatting of the JSON being passed in.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlPHluIlgobUE+ZPTKe16hQMkQzM6bZI7ku1EdwEhfL7zOux3ZOClUE5LYteieFFIB1SkoE4zpK30vfPhO8cpFyycbpQ41ZRXQTrLc3KQbKqoELudP0R7Fp9RCWrD0rSRuBZ4JthYSHAg7WCyOPCrG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://www.loom.com/share/76ff5a6c11f14e00873c9c7181830610?sid=13d43663-49ca
<img width="1411" alt="Screenshot 2024-08-19 at 11 03 49 PM" src="https://github.com/user-attachments/assets/4d90ee73-0517-4d7f-b066-3fd770658b3a">
-40dd-87af-9e12703542b9

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: all
```

### Additional Information

Mission critical blocker of the app

**Comment by paulperez-dev** [comment]
Hi @bags307! It may be only how the preview is presented to the user. Does this affect the behavior of your app?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
