### ISSUE TITLE
Not able to upgrade my account

### ISSUE THREAD

**Issue by saibhaskardevatha** [FlutterFlow/flutterflow-issues#3651]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to upgrade my account to Pro Plan, but it shows some processing error.

![CleanShot 2024-08-20 at 12 06 42](https://github.com/user-attachments/assets/ff72a547-fca3-4b5f-9e20-1efe14dd072f)

### Expected Behavior

It should open up the payment page.

### Steps to Reproduce

1. Open the dashboard
2. Left Bottom Corner, click on Upgrade
3. Once the modal opens, click on Upgrade

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Visual documentation

![CleanShot 2024-08-20 at 12 06 42](https://github.com/user-attachments/assets/71c2865d-46ea-4c25-9d6b-dfaa0e581e02)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. For cases like this, I recommend reaching out directly to support via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). This Issue Tracker is primarily for bugs that can be replicated using a new blank project.

Thank you for your understanding!

**Comment by saibhaskardevatha** [comment]
Hey @Alezanello

I have tried reaching out to support via email & in-app chat, but no response in either of these channels. I need to release the app soon. Is there any other way I can get to them?

**Comment by Alezanello** [comment]
Hi there!

Apologies for the late response—did support manage to fix the issue for you?

**Comment by saibhaskardevatha** [comment]
Yes, this is fixed now. Thanks!
