### ISSUE TITLE
[Listview] Listview misses items on first load

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#3652]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is the recovery of the following ticket because the new update did not fix the issue: https://github.com/FlutterFlow/flutterflow-issues/issues/3149

I have a firestore collection with about 3000 documents. The documents are getting queried by a list view with infinite scrolle and sorting. When the query is loaded there are items missing and/or they are not correctly sorted. If I scroll to the end of the list I am just seeing e.g. 1200 documents (I am displaying the list index).
If I go to another page in the app and open the page with the query again, it shows more documents (It loads the on the second try)

### Expected Behavior

I am expecting to see all the documents at the correct place in the list.

### Steps to Reproduce

1. Create a firestore collection and documents with a number field to sort them
2. query this collection with a list view with infinite scroll
3. compare the items shown in the list view with what should actually show

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glvH6wItIsbQB15DubO9WmjoRNkQ1Roc0sNtuTQIdCYDuBIYiaeD7PxNVYMOmTQhHKEWLrDgD/+iOivOWEfcoHzeqc6py1qhQExbJeEa/aoSIELigS2hDL/lUIEid0ra3sRMmHMlYLngs3TquPOjJSnXtJOL6Zwh9f6PHaOI=

### Visual documentation

Please let me know if you need something. I could show the list on different devices showing different results but I guess it is unnecessary

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @Jensoulus! Thanks for the bug report code and linking previous report. I will be looking into this.

**Comment by paulperez-dev** [comment]
Hi @Jensoulus! JensoulusI've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

**Comment by Jensoulus** [comment]
Hi @paulperez-dev,
thanks for taking a look into the project! Is it also possible to create a new page with just one list and test there first or do you really need a blank project? Since this app is in production I am quite sensitive in connecting other sources to firebase.

**Comment by paulperez-dev** [comment]
Hi @Jensoulus! We can go with a new page on the same project.

**Comment by Jensoulus** [comment]
Hi @paulperez-dev,
i have created the page in the project which only contains one list view. I have tested the scrolling and querying behavior and missing elements are still appearing. Possibly not as often as before. Does it help for your analysis?

The debug code of the list view is the following:
IT4glvH6wItIsbQB15DubO9WmjoRNkQ1Roc0sNtuTQIdCYDuBIYiaeDOSFhCOO2+YwllKEWJnTgxpPT5jYSeOvUVEASaGohe1aVxEw7KbF2/aoSIELigS2hDL/lUIEid0ra3sRMmHMlYLngs3TquPOjJSnXtJOL6Zwh9f6PHaOI=

Thanks for taking care!

**Comment by Jensoulus** [comment]
This issue should not be closed since it is still under testing if I am not mistaken, @paulperez-dev ?

**Comment by Jensoulus** [comment]
Is it possible to get a current status, @paulperez-dev ?

**Comment by paulperez-dev** [comment]
Hi @Jensoulus! Sorry for the late response, let me dig into your last response.

**Comment by paulperez-dev** [comment]
Hi @Jensoulus,

I’m unable to run your project due to some errors. Could you please resolve those issues and then share a new bug report code?

**Comment by Jensoulus** [comment]
Hi @paulperez-dev,

you should be able to test it now.
Here is a new code: IT4glvH6wItIsbQB15DubO9WmjoRNkQ1Roc0sNtuTQIdCYDuBIYiaeD7PxNVYMOmTQhHKEWJpFgDzPCNkuDPA8YpNSmbY4R6wbhATQ7zcEC/aoSIELigS2hDL/lUIEid0ra3sRMmHMlYLngs3TquPOjJSnXtJOL6Zwh9f6PHaOI=

**Comment by Jensoulus** [comment]
Hi @paulperez-dev ,
Did you had the chance to check?
Thanks!

**Comment by rzambroni** [comment]
Hi Jensoulus,

Apologies for the delay in getting back to you—we're working hard to get up to speed with everything.

I’m currently unable to run your project locally. Since this issue seems relatively quick to replicate and you already have the collection set up, would it be possible for you to create a blank project where this issue is reproducible and add me as a collaborator? (my email is rzambroni@somniosoftware.com) It would help us tremendously to replicate the issue on our end and work toward a fix more efficiently.

Thank you for your understanding and support!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
