### ISSUE TITLE
Execution failed for task ':shared_preferences_android:parseDebugLocalResources'.

### ISSUE THREAD

**Issue by NS-InStrand** [FlutterFlow/flutterflow-issues#3656]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to run local run and getting this error:
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDubug'....

Failure: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared_preferences_android:parseDebugLocalResources'.
> Could not resolve all files for configuration ':shared_preferences_android:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: C:\Users\EastBlade\AppData\Local\Android\sdk\platforms\android-33\android.jar.
         > C:\Users\EastBlade\AppData\Local\Android\sdk\platforms\android-33\android.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

Get more help at https://help.gradle.org/

BUILD FAILED in 7s
Running Gradle task 'assembleDebug'... 8.0s
Error: Gradle task assembleDebug failed with exit code 1`

I have tried to run my project and a new project with just a text widget but they have the same error.
I have also tried to connect a physical phone for local run but it has the same error too.
During local setup it all checks out from setup flutter>doctor output>configure ide>code export.

### Expected Behavior

To have a local run on android simulator and physical devise. So that I could test my app on mobile.

### Steps to Reproduce

1. Install Flutterflow for windows
2. Install local run > set up local run
3. Create new project
4. Add text widget
5. Run android studio and run virtual mobile devise / connect physical phone
6. Select android device either emulator/physical phone
7. Hit test run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

![local_run_bug](https://github.com/user-attachments/assets/e80d9cc7-d68a-493d-8a9e-5219646f4de3)

### Environment

```markdown
- FlutterFlow version: v4.1.83+
- Platform: Windows
- Browser name and version:
- Operating system and version affected: Windows 10
```

**Comment by paulperez-dev** [comment]
Hi @NS-InStrand! Can you please share the bug report code of your project?

**Comment by NS-InStrand** [comment]
> Hi @NS-InStrand! Can you please share the bug report code of your project?

Hello @paulperez-dev where do I find bug report code? during testing I only get from the local debug run. Here is the latest test I did.
![image](https://github.com/user-attachments/assets/2e5b1c1e-f880-4038-a513-a2a8f65c4296)
PS: I'm a beginner in flutterflow.
Thank you

**Comment by paulperez-dev** [comment]
Hi @NS-InStrand! In the widget tree (second tap) right click on any widget and there you will find the 'Get bug report code' option.

**Comment by NS-InStrand** [comment]
Hello @paulperez-dev Apologies for the late reply. This is resolve, I have found a GitHub post with similar issue, It said to download jar file into android folder.

**Comment by NS-InStrand** [comment]
Hello @paulperez-dev Apologies for the late reply. This is resolve, I have found a GitHub post with similar issue, It said to download jar file into android folder.

**Comment by paulperez-dev** [comment]
Hi @NS-InStrand! Thanks for the confirmation!
