### ISSUE TITLE
Private API call fails if it uses "params" as a variable

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#3658]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you create an API call which has `params` as a variable, and then deploy it as a private API call, it will fail because the generate `ffPrivateApiCall` code redefines `params` as a variable, which creates a collision.

### Expected Behavior

Should be able to use `params` as a variable name in a private API call.

### Steps to Reproduce

1. Create a new API call with `params` as a variable
2. Set it to Private in the settings
3. Deploy

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmB05NItb0E+YfyL8dvqwMwJ0QlUIInj+0bWRMhfa7nEIYtdePsYhZLYte+e352MVG0o3wFpsrPit7lL8YoaC2eR7pn1K5XQQ7MeFKWaL6KBYeeZXBRHehMCU/D0cGwkxVBBM9pdV1h212EG/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

This issue is not related to a specific endpoint. It's happening to all endpoints. I'll illustrate it better here: you will not be able to reproduce it in my project since I manually go and fix it in Google Cloud.

In every cloud function that is privately deployed to `ffPrivateCall`, the following parameter is automatically added by Flutterflow:
<img width="142" alt="Screenshot 2024-05-22 at 9 02 16 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/9f88df25-6f0f-4a4b-99a5-559c7da5244f">
it's a `params` variable, which is then used in the actual API call.

Now the problem is, if one of the parameters in an API Call in Flutterflow is _also_ called `params`, it fails, because the names collide, and this second empty one overrides the initial one!

So now every time I deploy my API I have to manually change my Google Cloud `ffPrivateCall` function as such:
<img width="262" alt="Screenshot 2024-05-22 at 9 03 47 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/7e4fe123-28bf-4d4f-b22c-b17f9aaad978">
i.e I need to rename the Flutterflow variable to `emptyParams` instead.

### Environment

```markdown
- FlutterFlow version: v.4.1.82
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

### Additional Information

This is really simple to fix on your end - just use another parameter as your default. We cannot use something else than "params" here because this is required by the API we are consuming. Just use "_params" as your own one, for instance.
For now I need to workaround this by changing it manually - can we please get this fixed?

**Comment by Alezanello** [comment]
Hi there,

Thank you for bringing this to our attention! We appreciate your input. This issue is already on our radar and is being tracked for resolution. You can follow any updates on the main issue here: [Issue #3484](https://github.com/FlutterFlow/flutterflow-issues/issues/3484).

I'll be closing this issue as a duplicate to keep things organized.

If you have any other questions or concerns, feel free to reach out. Have a great day!
