### ISSUE TITLE
Date Time Format gets error when datetime was null

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#3659]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to "Date Time Format" Option on datetime field and it was null, gets runtime error.

However FlutterFlow Util's code **accepts null** as in bellow(1), but generated code(2) **forces null**.

1. FlutterFlow Utils
`String dateTimeFormat(String format, DateTime? dateTime, {String? locale}) {
  if (dateTime == null) {
    return '';
  }
  ...
}`
2. Generated Code
`Text(dateTimeFormat("yMMMd",equipmentEquipmentsRecord.firstUseDate!, locale: FFLocalizations.of(context).languageCode,)`

### Expected Behavior

Returns "" when it was null as in FlutterFlow utils.

### Steps to Reproduce

1. Create firestore document that has datetime field
2. Set widget using 1 and set option "Date Time Format"

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfKB35ZJpbwG1c7qcsJWiQMxJ1gjbJ0vhMIaUUoYB5TyPLMXbuvTP1JbQu2ZTG5cC078+T0JwvDMieLqG/YFNS2EQ5RO1s19Ez3LXn6gRLa3BZG0Z0ZDL+dTGnLD0Ka7iCUlFMZuWk0tig/GSw==

### Visual documentation

Widget
![image](https://github.com/user-attachments/assets/1f55b117-2f0f-4bcb-8759-e5b32c9218dd)

Error
![image](https://github.com/user-attachments/assets/cb154674-a597-42e8-a6af-d12378df8a71)

### Environment

```markdown
- FlutterFlow version: 4.1.83
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected: Mac OS Sonoma
```

**Comment by Alezanello** [comment]
Hi there!

To prevent this issue, you can use conditional visibility to hide the widget, ensuring it doesn't get built when unnecessary. Additionally, setting a default value in the section you shared can help with null safety, which is crucial to avoid red screen errors.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/548590ad-b6bf-4b8c-8bd1-5cd4bba05488/c80ec8a4-f8ad-493d-8a11-48238d5b6983?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NDg1OTBhZC1iNmJmLTRiOGMtOGJkMS01Y2Q0YmJhMDU0ODgvYzgwZWM4YTQtZjhhZC00OTNkLThhMTEtNDgyMzhkNWI2OTgzIiwiaWF0IjoxNzI0MjQwMzc2LCJleHAiOjMzMjk0ODAwMzc2fQ.yJurXpAsEXEk49uc1-DUuNlJLLx6CeX_vxlsqwAuAYI " alt="image.png" width="391" height="758" />

**Comment by ryutosh** [comment]
@Alezanello 
Thanks for your response.
> To prevent this issue, you can use conditional visibility to hide the widget, ensuring it doesn't get built when unnecessary.

Yes, I know. But it is so unproductive and I am avoiding it with my custom function, not FF's.

> Additionally, setting a default value in the section you shared can help with null safety, which is crucial to avoid red screen errors.

No, this default value affects when the response of DateTimeFormat was null, not filed was null.
And I already set empty string (invisible in capture).

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
