### ISSUE TITLE
Deleting firebase collection keeps code referencing it causing errors

### ISSUE THREAD

**Issue by bertke** [FlutterFlow/flutterflow-issues#366]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I would expect that deleting a firebase collection (data table) would remove references to that collection.  

## Current behavior (required)

I have errors that cannot be corrected when I pull the code from github to run it local.  The errors are referenced in the schema folder, file name serializers.g.dart.  The code shows an 'add' line referencing the old collection. Removing this line locally removes the error but obviously no way to push this change back to Flutterflow.

### Bug Report Code (required, generate from Widget Tree)

Error is not shown in Flutterflow ui

## Context (required)

I am unable to get a clean compile on my local machine

## Your environment

* Version of FlutterFlow used: current
* Platform (e.g. Web, MacOS Desktop):  Mac Web
* Browser name and version: Chrome - current version
* Operating system and version (desktop or mobile): Mac OS - latest version

**Comment by victoriahuang1** [comment]
Hi @bertke , thanks for the report. Did you delete the Firebase collection via the Flutterflow UI, or did you directly delete it on the Firebase console?

And if you deleted the collection via the Flutterflow UI, did you run
```
flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs
```
?

**Comment by bertke** [comment]
So I was not familiar with the second command but have tried that and have the same basic issue which is that the next push from FF re-creates this file.  I'm assuming you would have me run this locally.  When I do that, it does remove the offending code but as soon as I make a change in FF, push to Github and pull to local, the serializers file has been modified to include the reference to the deleted collection causing errors.

**Comment by bertke** [comment]
Sorry, didn't answer the first question.  Yes, I deleted the collection via the FF UI (as well as in Firebase). So according to FF, this collection does not exist yet it still writes that line in the serializer.g.dart file.

**Comment by victoriahuang1** [comment]
Hi @bertke , do you see this issue when downloading code directly or is it only present when pushing to Github?

**Comment by bertke** [comment]
I downloaded the code and yes the offending line is still in the project ({project}/lib/backend/schema/serializers.g.dart).  When I run the commands you provided earlier (flutter pub get and flutter ...'delete conflicting') it fixes the issue.  But again this only fixes it local so the next pull of code (or the next push to github) creates the problem again.

**Comment by victoriahuang1** [comment]
Thanks for verifying. I can't reproduce this issue with my own projects. Could you generate a Bug Report Code so that I can look into what's happening in your project?

**Comment by bertke** [comment]
I'm assuming this is something I can do within the FF UI to somehow flag my project for you to view but I don't see how to do this.  Can you help me with what you meant by that?

**Comment by victoriahuang1** [comment]
You can right-click on any widget in the widget tree, and it should give you the option to generate a bug report code.

**Comment by bertke** [comment]
got it.  I'm hoping that any widget will do as the issue here is related to something I'm trying to remove from my project.  What I did was generate the below code from a widget that is hitting another table. Let me know if this doesn't work or wasn't what you were looking for.


IT4gzM7l24VIscsA0KX1YO9VoDs6Jj86bIc0sNtuTQIdCYDuBIYiaeLSSExBUsOmSn9lKEWKhn0xwejMht7xCvACITmBR7441s9QewGUXljkEuzyT+3IHDUHZbsSXTTm

**Comment by victoriahuang1** [comment]
Hi @bertke , thanks for the update. It looks like when you try to download code, it tells you to run:
```
flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs
```,
which is the expected behavior. Unfortunately, we are not planning on automating running those commands on our end. However, you can set up your own CI/CD to automatically run them to make the experience less annoying.

Hope this helps!

**Comment by bertke** [comment]
This is unfortunate.  Now to iterate and test code I have to discard local changes (because running the script makes local changes), pull from github, run these scripts, re-start the app and then I can test. Before I changed the data structure in Firebase steps 1 and 3 weren't necessary.  It really seems FF should not continue to generate code for deleted connections.
