### ISSUE TITLE
Custom icons not showing correctly in FlutterFlow MacOS app IDE

### ISSUE THREAD

**Issue by Brandborne** [FlutterFlow/flutterflow-issues#3661]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have two sets of custom icons in my project. When I open the project in Chrome the IDE displays the correct icons but when I open the project in the MacOS app the icons are not correct. It appears as though the icon references get scrambled somehow.

Correct fonts.
<img width="1608" alt="image" src="https://github.com/user-attachments/assets/fb86ff2f-c322-490a-b2a3-235c7cd0bf9c">

Incorrect fonts
<img width="1608" alt="image" src="https://github.com/user-attachments/assets/b791b233-efee-4c92-a20a-d8485d03a968">

### Expected Behavior

I expect the icons the be same across platforms.

### Steps to Reproduce

1. Open the project in Chrome
2. Open the project in MacOS

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz/Hqx89gosRE0JDccu1omiEwGUALa+dI0tZ+TQ0jF5D4OokqdsjRP1dWZMSzaHx6EFa0jkkewPT9kvPLN/oDOU2dGL5ZyalyYRPPYzmVR822CLWwYH9SRJtYGFzC4cCvkB5BItdhW1Ji7UyYeuSicz+Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1608" alt="image" src="https://github.com/user-attachments/assets/5f579ec8-b5c8-4eeb-8a71-c5e7ebd22be4">

### Environment

```markdown
- FlutterFlow version: 4.1.83
- Platform: Mac
- Browser name and version: Chrome  127.0.6533.120
- Operating system and version affected: MacOS 14.6.1
```

**Comment by rzambroni** [comment]
Hey @ClintonPaulYoung, thanks for the report, 

I attempted to replicate the issue you are describing but i was unable to do so. Seems to be working as expected on my end. I guess it might be specific to either your project or the icons you are using, but it is an strange issue. 

Could you share with me the icon pack you are using? i want to test with that on a blank project. 

Thanks in advance.

**Comment by matlin76** [comment]
@rzambroni The Same thing happens to me.

Web UI
![Screenshot 2024-08-27 at 13 23 23](https://github.com/user-attachments/assets/1230dfca-b179-41c1-9575-4afd7e66400c)

Mac App UI
![Screenshot 2024-08-27 at 13 23 34](https://github.com/user-attachments/assets/65f6798b-3a42-486d-b074-af00469d9e76)

Web UI
![Screenshot 2024-08-27 at 13 24 02](https://github.com/user-attachments/assets/190e182c-0a10-497d-af5d-c0aa0e19c2f1)

Mac App UI
![Screenshot 2024-08-27 at 13 24 27](https://github.com/user-attachments/assets/bb3b06e0-48f6-426d-be23-e9450f8d2005)

**Comment by rzambroni** [comment]
can you please share that icon pack so we can test if this is specific to certain custom icons?

Thanks in advance.

**Comment by Brandborne** [comment]
Sorry for the delay, I have been busy.
 
Please see icon files attached.
 
Here are some additional images showing the issue.
 
Project open in Chrome – showing correct icons.
<img width="1608" alt="image" src="https://github.com/user-attachments/assets/5ab91a45-bbef-4211-be64-5c94cdf1aa99">

 
Same project and page open in the FF MacOS app – showing incorrect icons.
 
<img width="1608" alt="image" src="https://github.com/user-attachments/assets/fc81b27a-1c0f-436b-8a60-accb69a089e6">


You can see in the properties the icon names are the same but the images are different.
 
Below are how the fonts look in the Theme Settings in Chrome
 
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/6affcb0f-440c-486a-bcdc-6ffb9796eb40">
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/57deac6d-c35e-418a-9463-c3c0480d44c1">

 
This is how they look in the FF MacOS app
 
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/1c84a5ed-ef05-479b-9696-b714fd9ad279">
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/14826816-a49f-4a9d-98f7-46bb7d0df462">

 
 
It would also be great to have a feature where I can easily update a custom icon set.

**Comment by Brandborne** [comment]
Fonts Icons
[streamu-icons-line-03-v1.0.zip](https://github.com/user-attachments/files/16835522/streamu-icons-line-03-v1.0.zip)
[streamu-icons-solid-03-v1.0.zip](https://github.com/user-attachments/files/16835524/streamu-icons-solid-03-v1.0.zip)

**Comment by rzambroni** [comment]
Thanks so much for the additional details, i'll take another look.

**Comment by rzambroni** [comment]
Hey @ClintonPaulYoung,

I attempted to replicate the issue you're experiencing, but unfortunately, I haven't been able to do so, even with the icon packs you provided. I also tested it both by uploading from a Mac and through the web.

MacOS vs Web

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3e730b5c-4df6-44c3-9220-216a1999bcf9/b569718c-aaee-4f4e-80f3-c7ba74baba63?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zZTczMGI1Yy00ZGY2LTQ0YzMtOTIyMC0yMTZhMTk5OWJjZjkvYjU2OTcxOGMtYWFlZS00ZjRlLTgwZjMtYzdiYTc0YmFiYTYzIiwiaWF0IjoxNzI1Mzc0NDgyLCJleHAiOjMzMjk1OTM0NDgyfQ.Yv_wUpYIZz1-JNk4kXCTSnHu3S7rA4uXNivvy-iZOUI " alt="image.png" width="2494" height="1032" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/157a42ba-a963-42f7-bd01-4fde442c9716/0fa22b0f-ec6d-4a1c-88bb-1382aa141e7d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNTdhNDJiYS1hOTYzLTQyZjctYmQwMS00ZmRlNDQyYzk3MTYvMGZhMjJiMGYtZWM2ZC00YTFjLTg4YmItMTM4MmFhMTQxZTdkIiwiaWF0IjoxNzI1Mzc0NDgyLCJleHAiOjMzMjk1OTM0NDgyfQ.z-EiquZUK_ELqNPHds620qP6-shD45kPPhiqxk4Gjr8 " alt="image.png" width="2206" height="824" />

I'm not sure what might be causing the problem on your end. Have you tried deleting and re-importing the icons to see if that resolves the issue?

**Comment by Brandborne** [comment]
I'm wondering if the issue is because the icon fonts changed as I added more icons to the set.

**Comment by Brandborne** [comment]
I'm hesitant to change the icons again as I will need to go through the entire app and reassign all the icons.

**Comment by rzambroni** [comment]
Maybe you could try importing the icon packs again in a blank project to see if the issue is resolved that way before committing to do it in your main project.

**Comment by Brandborne** [comment]
The icons are fine in Chrome though. Is there a way to reset the MacOS app. Perhaps it is caching the last fonts.

**Comment by rzambroni** [comment]
You could try deleting the content of this folders:<br>`/Users/<user_name>/Library/Caches/io.flutterflow.prod.mac`

`/Users/<user_name>/Library/Application Support/io.flutterflow.prod.mac`

Alternatively, reinstalling the app might also help.

**Comment by Brandborne** [comment]
Deleting the contents of the folders has worked. Thanks

**Comment by rzambroni** [comment]
Great! Glad to hear that.
