### ISSUE TITLE
Not able to add imports in functions

### ISSUE THREAD

**Issue by DanielvdBerg95** [FlutterFlow/flutterflow-issues#3662]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created this BugReportProject to show what is happening. 

I can add any import statements to the custom functions. For example in the code below I am trying to add typed_data
import 'dart:typed_data' show Uint8List;

However when I create a new function and add it, as soon as I save it removes the import statement, and it also does not give me the option to save the code when editing the function again. 

### Expected Behavior

We should be able to add import statements and add dependencies to our code. This has always been the case till today after the new flutterflow update. This is breaking all of my projects. 

### Steps to Reproduce

1. Create new Custom function
2. Name it whatever you want
3. Provide arguments and return value
4. Add an import for a specific package to be used
5. Save the function

It will then remove the import statement once you save and it cannot be added again afterwards. The save option does not become available when you try

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kls/l6otPm9tH1s7yKe9ajikXQ3ojUOYslu1HZA8bC72rG7l/TMnOVBJuOLC0YXxmJE20jn8dw6jemvDlIfU4FwidbbpOyZNudA3NfEagV8WgPrmKXm5/AplXCFyZ55irvh15BPhtSVog20ODONmuZDLqQrLzO0URJMn+C5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/df305825-d8d1-4f45-aead-133dae62e79e

### Environment

```markdown
- FlutterFlow version: v4.1.83+
- Platform: All
- Browser name and version: Chrome, Brave and Desktop app! 
- Operating system and version affected: Windows 10 and Ubuntu
```

### Additional Information

All of my projects running on custom functions are now filled with errors, costing me time that I now need to spend on going through this once you resolve the issue to add all the imports again. I cannot give you access to any of the client apps, so please don't even ask.

**Comment by Alezanello** [comment]
Hi there!

Custom Functions do not support adding imports. If you need to include imports, classes, or have multiple functions calling each other, you'll need to create a Custom Action instead. Custom Actions allow you to add whatever you need to the code, giving you the flexibility to return exactly what you need for your project.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1df21b92-83b4-4e85-859a-300fff751191/cfbdb22b-08ab-4fce-9f43-e8926e98a187?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZGYyMWI5Mi04M2I0LTRlODUtODU5YS0zMDBmZmY3NTExOTEvY2ZiZGIyMmItMDhhYi00ZmNlLTlmNDMtZTg5MjZlOThhMTg3IiwiaWF0IjoxNzI0MjQ0MTgzLCJleHAiOjMzMjk0ODA0MTgzfQ.0ctHuiVSrFxXi2ep4xmYgz4no9OBHyZxKubo-bIAMpA " alt="image.png" width="697" height="497" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
