### ISSUE TITLE
textfield with passing argument doesnt work for password type

### ISSUE THREAD

**Issue by mranjeet** [FlutterFlow/flutterflow-issues#3663]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i am unable to use the passed bool params to be used for defining the common widget i used 

### Expected Behavior

it is expected the widget i have define commonly should use the variable value to define weather the widget is of type password or not

### Steps to Reproduce

import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import 'label_with_text_box_model.dart';
export 'label_with_text_box_model.dart';

class LabelWithTextBoxWidget extends StatefulWidget {
  /// this widget is for text along with input
  const LabelWithTextBoxWidget({
    super.key,
    required this.label,
    required this.placeHolder,
    bool? isPassword,
  }) : this.isPassword = isPassword ?? true;

  final String? label;
  final String? placeHolder;
  final bool isPassword;

  @override
  State<LabelWithTextBoxWidget> createState() => _LabelWithTextBoxWidgetState();
}

class _LabelWithTextBoxWidgetState extends State<LabelWithTextBoxWidget> {
  late LabelWithTextBoxModel _model;

  @override
  void setState(VoidCallback callback) {
    super.setState(callback);
    _model.onUpdate();
  }

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => LabelWithTextBoxModel());

    _model.textController ??= TextEditingController();
    _model.textFieldFocusNode ??= FocusNode();
    _model.textFieldFocusNode!.addListener(() => setState(() {}));
  }

  @override
  void dispose() {
    _model.maybeDispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsetsDirectional.fromSTEB(8, 0, 8, 0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            widget!.label!,
            style: FlutterFlowTheme.of(context).bodyMedium.override(
                  fontFamily: 'Readex Pro',
                  letterSpacing: 0,
                ),
          ),
          Align(
            alignment: AlignmentDirectional(0, 0),
            child: Padding(
              padding: EdgeInsetsDirectional.fromSTEB(0, 2, 0, 0),
              child: TextFormField(
                controller: _model.textController,
                focusNode: _model.textFieldFocusNode,
                autofocus: true,
                textCapitalization: TextCapitalization.none,
                textInputAction: TextInputAction.done,
                obscureText: false,
                decoration: InputDecoration(
                  labelStyle: FlutterFlowTheme.of(context).bodyMedium.override(
                        fontFamily: 'Readex Pro',
                        letterSpacing: 0,
                      ),
                  hintText: widget!.placeHolder,
                  hintStyle: FlutterFlowTheme.of(context).labelMedium.override(
                        fontFamily: 'Readex Pro',
                        letterSpacing: 0,
                      ),
                  enabledBorder: OutlineInputBorder(
                    borderSide: BorderSide(
                      color: FlutterFlowTheme.of(context).alternate,
                      width: 2,
                    ),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderSide: BorderSide(
                      color: FlutterFlowTheme.of(context).primary,
                      width: 2,
                    ),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  errorBorder: OutlineInputBorder(
                    borderSide: BorderSide(
                      color: FlutterFlowTheme.of(context).error,
                      width: 2,
                    ),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  focusedErrorBorder: OutlineInputBorder(
                    borderSide: BorderSide(
                      color: FlutterFlowTheme.of(context).error,
                      width: 2,
                    ),
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                style: FlutterFlowTheme.of(context).bodyMedium.override(
                      fontFamily: 'Readex Pro',
                      letterSpacing: 0,
                    ),
                validator: _model.textControllerValidator.asValidator(context),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l8j14ot1xMtD1r6JcvlV/SY5JjJ8bLhN0cJraCsvCIyqOpscf/fBfklUOenjYwhYJWKjjjgX/MrHkd/pOvQEBwuabYBj1KVcUArMTmK7Rq6JEr63b2hSL8JbGU+M0J2jgSNDHLFYSVoQwDmqJ96ATXfvCZv4Nms7Pua4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/c9831544-5f67-4677-9817-58cfe4b21184)

### Environment

```markdown
- FlutterFlow version: v4.1.83+ released August 20, 2024
- Platform: iOS
- Browser name and version: Google chrome
- Operating system and version affected: macOS Sonoma 14.6.1
```

**Comment by Alezanello** [comment]
Hi there!

To better understand the issue, are you passing a boolean parameter to another component, and the component isn't recognizing the value? Could you clarify the main problem?

**Comment by mranjeet** [comment]
Hello Thanks for your response,

yes the exact issue is what you have explained in above. When i am passing the boolean value the my common component i am using for displaying Textfield the params i am using is isPassword field and i am passing where i am using it but unable to set it inside the Textfield itself. Let me know if you need anything else

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by NaimRodriguez1** [comment]
@Alezanello Hello my friend, i have the same problem, i'm using a boolean variable. That variable value is true, but when i assign it to the property, it doesn't work.

**Comment by GersonFuentes** [comment]
@Alezanello Same problem here, the Password Field property of a Text Field, is not working if you set the value dinamically
![image](https://github.com/user-attachments/assets/b089af69-070a-4aac-be00-86954241d79a) 
![image](https://github.com/user-attachments/assets/6e370180-bbe1-4b55-a0a9-2b8546bbc918) 
![image](https://github.com/user-attachments/assets/1883b923-b1aa-4059-9567-893de8bfe8de)

Result: 

![image](https://github.com/user-attachments/assets/4c983976-9a59-485f-858e-792f8e57b437)
![image](https://github.com/user-attachments/assets/5accc734-90ce-421e-bbb5-ef353cf52d9e)

**Comment by Alezanello** [comment]
Hello, and I apologize for the delayed response.

Thanks to the latest contribution from GersonFuentes, I was able to successfully replicate the issue. I'll now be forwarding this to the engineering team for further investigation and a fix.

Thank you for your patience, and please let me know if you have any additional information or questions!

**Comment by GersonFuentes** [comment]
@victoriahuang1 @Alezanello what does "not planned" mean?
After 3 months waiting, and even when other users have been able to reproduce the issue and verify is a confirmed bug, you just simply close the issue?
