### ISSUE TITLE
API Call loss parameters when doing cut chain, paste actions on a multi step action flow chain

### ISSUE THREAD

**Issue by oliversl** [FlutterFlow/flutterflow-issues#3665]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you select cut chain from the upper most action flow, and do paste action, in some API Call the parameters are missing. When you select again the parameter, you need to select twice since the first one does not work.

### Expected Behavior

All the chain get copied with all the API Call parameters, you don't need to re enter all the parameters in any API Call action

### Steps to Reproduce

1. create an action flow, information message
2. create a condition to have 2 branches, true and false
3. in the false branch, create this: API Call, set state, API call, set State, API Call, set state
4. Each API Call has parameters
5. select the upper most action, from the false branch, select cut chain
6. outside the black, select the plus sign, then past chains
7. check all the API Call parameters, some are missing

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMjfsIh2ofpE1q6JK+9ajSo5Jn4+UK8k0cBraCosfZT2BLMcec/RVERtTt+5d2xlMWCJq2oW3PzqveP1Kvc7Eyucfohk/6tyazzwfzm7V5i3FJWgTnFPPJ9MBW690au3qxInOvhZWmwC1zmletiyaAXbK5TyIFYWDq/LZO4=

### Visual documentation

<img width="316" alt="image" src="https://github.com/user-attachments/assets/e9b78097-a155-4aa0-ac61-672a314f66ec">

<img width="339" alt="image" src="https://github.com/user-attachments/assets/5f8ad2a6-a1e7-404d-a131-8b781a798fc9">

### Environment

```markdown
- FlutterFlow version: 4.1.81+
- Platform: MacOS Sonoma
- Browser name and version: Microsoft Edge
- Operating system and version affected: on development stage
```

**Comment by paulperez-dev** [comment]
Hi @oliversl! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
