### ISSUE TITLE
Team subscription changes to Free with no reason

### ISSUE THREAD

**Issue by pdamariana** [FlutterFlow/flutterflow-issues#3666]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My development team is currently having many issues with our Team subscription. Early today, I was able to work with my flutter flow projects but now it appears as a _Free Plan_, so I cannot work properly.
It seems like the subscription changes every time for no reason. Sometimes I have the Team subscription, and a few minutes later it changes to Free.
This is happening everyday and many times in one day. 

### Expected Behavior

We have already subscribed and paid for team features, so it must not change to Free.

### Steps to Reproduce

1. Enter Flutterflow Dashboard
2. In the subscription information it says Free and Upgrade.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClPHq25N1xd9Y+Kr2asJVmiURNlw1RYIKm9VtdwgYDZPQCJkQO8nQP0hCUtPiSmxpMGKMp14ewaHTiOOeD/QqZBCdY6U51Kl9ExbjcFy5RciTF7WwOUB8RPJhCEyH06SJuCJTB7ZhWC0f6kOqBNm8c3fsHZTFDUQ8Sq/LZO4=

### Visual documentation

<img width="274" alt="Screenshot 2024-08-21 at 7 03 50 PM" src="https://github.com/user-attachments/assets/46df6bbd-284e-4ac7-ac1b-f933764e758c">
<img width="384" alt="Screenshot 2024-08-21 at 7 04 13 PM" src="https://github.com/user-attachments/assets/cc752c1e-0106-4a99-a4c6-cd0c9b51b8ec">

### Environment

```markdown
- FlutterFlow version: 4.1.83
- Platform: Web, Desktop
- Browser name and version: Chrome Version 127.0.6533.120
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by rzambroni** [comment]
Hey @pdamariana, so sorry about that, our team is aware of the issue and working to resolve it as soon as possible. 

Will keep this issue open in case it is useful to other users to know. 

Thanks.
