### ISSUE TITLE
Checkbox Widget Reverts to Default State When Used in Dynamic List with the "Generating Children from Variable" feature

### ISSUE THREAD

**Issue by proptechbex** [FlutterFlow/flutterflow-issues#3667]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- The Checkbox reverts to its default state regardless of user interaction.
- In test mode within a blank project, selecting or deselecting one checkbox affects all checkboxes in the list, selecting or deselecting them all.

### Expected Behavior

- The Checkbox should retain its state when toggled. If selected, it should remain selected, and if unselected, it should remain unselected. 
- Additionally, each checkbox should operate independently without affecting the state of other checkboxes in the list.

### Steps to Reproduce

1. Create a dynamic list using "Generating Children from Variable".
2. Add a Checkbox widget within each item of the dynamic list.
3. Run the app.
4. Try toggling the Checkbox on and off.
5. Test the behavior in a blank project in test mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMjc35N1m8hE+6XtLcZGpGUwGUwLaJIriO4baw4cCePrOuwqesjCbhZVWOqHfVFlfFWihl8H+d6MiOz1DcI6FE6BGqp7wpZTUxDgXk+VMpeVBpG0WEF9L/NUJkyu1J2rph1CPrJoSGNh1DqqB9mub3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/bf033523-d690-426a-9856-058ccb866e9e)

https://github.com/user-attachments/assets/d789a415-a1cb-4e45-b943-1c974f718ab9

### Environment

```markdown
- FlutterFlow version: 4.183+
- Platform:Web
- Browser name and version: Chrome 127.0.6533.120
- Operating system and version affected: Windows
```

### Additional Information

Since the last update, the "Checkbox" widget is exhibiting unusual behavior. When I toggle it, it momentarily changes state but then immediately reverts to its default state. For example, if the default state is checked and I uncheck it, it reverts back to checked. Conversely, if the default state is unchecked and I check it, it reverts back to unchecked.

Additionally, I tested this issue in a blank project using the test mode, and the behavior was different. When I select any of the checkboxes within the dynamic list, all checkboxes get selected. Similarly, when I deselect any checkbox, all of them get deselected.

I've noticed that these issues specifically occur when the checkbox is used within a dynamic list generated with the "Generating Children from Variable" feature.

**Comment by paulperez-dev** [comment]
Hi @proptechbex? I'm sorry you are facing this issue. Can you please try running the project locally and let us know how it behaves?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
