### ISSUE TITLE
Failed to compute merge conflits 

### ISSUE THREAD

**Issue by joaocordeiro-dotted** [FlutterFlow/flutterflow-issues#3668]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot merge any of my branches back into Main in the FlutterFlow builder. I initiate merge, the spinner pop loads, then a red error message replaces it with "cannot compute merge conflicts

<img width="1512" alt="Captura de Tela 2024-08-21 às 21 26 33" src="https://github.com/user-attachments/assets/8f60a86b-ac76-45a9-a495-12fd9fbefdd9">

### Expected Behavior

I expect to be taken to the Merge Conflicts page and merge the branch changes into Main.

### Steps to Reproduce

To Reproduce from within my specific project

Create a branch
Make any change
Attempt to merge
You will see the "failed to compute merge conflicts" errror
*I cannot reproduce this from a blank project, it works on a blank project. My project has gotten into some broken state and I need the FlutterFlow team to help identify the issue and solve it.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43zs7kx6lIrstH+qv2K/FKnmQnGnIWaJBIldhraCorB5DoPZsUecmkM0RocOHmS2NqIU2kjWoW0PzRvoSSV8EpByiAfr04+IdhWgLweEORb62bFJWgeEZ5IJtUCmqv58G3nR5AVepqdGwS1GeQHe/IQh7YK5i2C0gsD6/LZO4=

### Visual documentation

<img width="1512" alt="Captura de Tela 2024-08-21 às 21 26 33" src="https://github.com/user-attachments/assets/f4b92a92-472e-4cec-9d83-70fae097e6e3">

### Environment

```markdown
- FlutterFlow version: v4.1.83+
- Platform: MacOS Desktop / Web
- Browser name and version: Google Chrome
- Operating system and version affected: macOS Sonoma 14.2
- Project ID: 5ySUuqp5SvDtxFLXhNpX
```

### Additional Information

- Project ID: 5ySUuqp5SvDtxFLXhNpX

**Comment by rzambroni** [comment]
Hello,

I apologize for the inconvenience. As you mentioned, the issue seems to be specific to your project since it's working as expected on blank projects. I'm reaching out internally to see if an engineer can take a closer look and help identify the root cause of the issue.

Thank you for your patience.

**Comment by victoriahuang1** [comment]
This will be resolved upon the next deploy.
