### ISSUE TITLE
Flutterflow Misidentifies '.edu.eu' as a Subdomain, Resulting in Incorrect DNS Lookup

### ISSUE THREAD

**Issue by bgnltd** [FlutterFlow/flutterflow-issues#3669]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow incorrectly identifies '.edu.eu' as a subdomain rather than recognizing it as an effective top-level domain (eTLD). When attempting to verify DNS records for a domain like abc.edu.eu, the service mistakenly searches for DNS records under the edu.eu domain instead of the intended domain abc.edu.eu. This causes the service to be unable to locate the correct DNS records for the domain.

### Expected Behavior

Flutterflow should recognize '.edu.eu' as an effective top-level domain (eTLD) and correctly identify abc.edu.eu as the main domain. The service should perform DNS lookups directly under abc.edu.eu instead of treating abc.edu.eu as a subdomain of edu.eu, thereby allowing it to find the correct DNS records.

### Steps to Reproduce

1. Enable Web Publishing:
- Go to Settings and Integrations > Project Setup > Platform.
- Toggle on the Web option.

2. Access Custom Domain Settings: Navigate to Settings and Integrations > Project Setup > Web Publishing > Custom Domain.

3. Enter Custom Domain: Input your custom domain URL (e.g., abc.edu.eu) into the provided field.

4. Set Up DNS Records: Configure the required DNS records for your abc.edu.eu domain according to the provided instructions.

5. Attempt to Connect: Click on the Connect button to verify and establish the connection with your custom domain.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xlefq3ItIsdtY7c/QacFvryQsQzM6bZ03itYacwI1GO+sPOwAOfTET3FdOLynSnxIOWGjnnIIpt7UkuDLG8IoKQSIQ75+wbtuZhXLVXOjRrqgPpeaQEZPNNxjBW694ZqOiiNCAM1vc14B1FymJeusfC3qGIzJPms7Q+akEKz+okKZFQzRJDhmtmNecCfn

### Visual documentation

Not applicable. 

### Environment

```markdown
- FlutterFlow version: v4.1.83
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're encountering this issue. I'll have our engineering team take a look, and I'll get back to you as soon as possible.

**Comment by leighajarett** [comment]
This should now be resolved, thank you for flagging!
