### ISSUE TITLE
Unable to run android emulator from FF desktop app due to the manifest merger conflict

### ISSUE THREAD

**Issue by PMFlis** [FlutterFlow/flutterflow-issues#3672]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am not able anymore to run the android emulator from FF desktop app as there is a manifest merger conflict. I get this error: Error:
    Attribute uses-permission#android.permission.WRITE_EXTERNAL_STORAGE@maxSdkVersion value=(32) from AndroidManifest.xml:7:79-105
    is also present at [:camera_android_camerax] AndroidManifest.xml:16:9-35 value=(28).
    Suggestion: add 'tools:replace="android:maxSdkVersion"'

I don't understand why now in android manifest for the permission WRITE_EXTERNAL_STORAGE, there is a maxSdkVersion specified? I have checked the code I have downloaded a few days ago, and in the android manifest, I have only the permission WRITE_EXTERNAL_STORAG but without specified maxSdkVersion. But the code I downloaded yesterday have the maxSdkVersion specified in AndroidManifest and it causes conflict with my custom camera widget that uses a package camera: ^0.11.0+2 that uses the package camera_android_camerax that has maxSdkVersion specified as 28. As i don't have access to android manifest in FF app so I cannot override that so I cannot test on android using the FF desktop app.

### Expected Behavior

I would like to be able to test app on android using the ff desktop app.

### Steps to Reproduce

1. get the ff desktop app
2. open android studio and launch the virtual device
3. Run app locally on android device

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/1sIZgobxc+Kn+bPlFmSkRCUMdXOczitVEew4bCIj4OplzY+ClQFVCXsyzaHNUM02ignw1w9beueHxA/EFAE+rc6Y/+pdyVRPPbGGiMqqhPbqOOnNCO8BUG3aG0ImCkCRCGNNtWmAA3GaIFdm+RT2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1232" alt="Screenshot 2024-08-22 at 16 47 48" src="https://github.com/user-attachments/assets/87255318-f0de-4a9d-8db2-f27321e0c161">
<img width="839" alt="Screenshot 2024-08-22 at 16 45 18" src="https://github.com/user-attachments/assets/6bfa0f15-1dd0-4e26-95e4-8d5b06e7a3bc">

### Environment

```markdown
- FlutterFlow version: v4.1.83
- Platform: android
- Operating system and version affected: ios
```

**Comment by paulperez-dev** [comment]
Hi @PMFlis! So sorry you are facing this issue. Did you update the camera dependency recently? Or is it the same version as the first project download you mentioned?

**Comment by PMFlis** [comment]
Hi @paulperez-dev, thank you for you reply. The problem occured while I was using camera: ^0.11.0+1, and I had this version for several weeks and I had no problem to use android emulator. Once the problem occured, I have updated the dependency to camera: ^0.11.0+2 hoping that it will resolve the problem but it didn't. I looked at both versions of camera and they both use the same version of camera_android_camerax. And as I mentioned in my first message, maxSdkVersion is now specified in the AndroidManifest for WRITE_EXTERNAL_STORAGE, and before there was no version specified. The only thing that I worked on, on the day when the issue appeared, was push notifications that I have enabled for my app.

**Comment by adnanmur** [comment]
i have the same issue here, altought not related to camerax but intercom messenger.

 What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute uses-permission#android.permission.WRITE_EXTERNAL_STORAGE@maxSdkVersion value=(32) from AndroidManifest.xml:9:79-105
  	is also present at [io.intercom.android:intercom-sdk-ui:15.10.1] AndroidManifest.xml:10:9-35 value=(28).
  	Suggestion: add 'tools:replace="android:maxSdkVersion"' to <uses-permission> element at AndroidManifest.xml:9:5-107 to override.

**Comment by paulperez-dev** [comment]
Hi @PMFlis and @adnanmur! The ENG team suggests using the [camera awesome package](https://pub.dev/packages/camerawesome) instead to avoid these conflicts! I will be closing this issue.

**Comment by adnanmur** [comment]
I am not using the camera package, i am using flutter intercom package

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=YWRuYW5tdXJhdG92aWNAZ21haWwuY29t>

**Comment by paulperez-dev** [comment]
Hi @adnanmur,

Are you still encountering this error? If so, could you please file a new issue with all the details and include a bug report code from a blank project?

**Comment by adnanmur** [comment]
support already has determined that the intercom package is not compatible with flutterflow because of this error. removing the package app works fine., but unfortunately core ove the app is intercom

**Comment by eziopelle** [comment]
I have the same problem as you with the intercom package:

Attribute uses-permission#android.permission.WRITE_EXTERNAL_STORAGE@maxSdkVersion value=(32) from AndroidManifest.xml:9:79-105
	is also present at [io.intercom.android:intercom-sdk-ui:15.12.0] AndroidManifest.xml:10:9-35 value=(28).
	Suggestion: add 'tools:replace="android:maxSdkVersion"' to <uses-permission> element at AndroidManifest.xml:9:5-107 to override. 

Were you able to find a solution @adnanmur please ?

**Comment by adnanmur** [comment]
no i have not found a solution for this. You can run the app by changing some setting in the code but then again the intercom wont run as there is a conflict with some firebase dependencies. Contact the support, they will provide what you need to change in the android manifest, but i dont think it would run
