### ISSUE TITLE
Custom Function not allowing additional import

### ISSUE THREAD

**Issue by Rodriq** [FlutterFlow/flutterflow-issues#3673]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This has been the behavior for the past two days with just custom functions. Custom widgets and actions are fine.

When I try adding any library import on my custom function, it doesn't allow for it.

### Expected Behavior

Allow my import to stay just like it's always been.

### Steps to Reproduce

1. Create a simple custom function and try to 
2. import any build in library like `import 'dart:typed_data';` 
  - If that is the only additionmade to the function, you won't be able to save it
  - If you make it alongside other changes, when you click on Save, it removes the import

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Custom function

### Visual documentation

Custom function

### Environment

```markdown
- FlutterFlow version: 4.183+
- Platform: Web and Desktop
- Browser name and version: Chrome latest
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment]
Hi @Rodriq! You can't have imports in a[ custom function](https://docs.flutterflow.io/concepts/custom-code/custom-functions/#faqs). To be able to add imports, consider using a [Custom Action](https://docs.flutterflow.io/concepts/custom-code/custom-actions).

I'm closing this issue.
