### ISSUE TITLE
On Custom Dialog Box, Icon Parameters Resets

### ISSUE THREAD

**Issue by nipunanr** [FlutterFlow/flutterflow-issues#3675]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After setting a Icon at Action Flow Editor, the icon properties reseting after going back.

![image](https://github.com/user-attachments/assets/b3fbdaba-8b47-4353-a582-aa06535afd0c)
(Initially, the Icon is present.)

![image](https://github.com/user-attachments/assets/6e52b61d-ad62-4cb4-92c5-287e6291f034)

(But after few seconds, the icon is Gone)

### Expected Behavior

Need to Keep the Icon when it is set.

### Steps to Reproduce

1. Create a Custom Dialog Box with Icon
2. Use that Custom Dialog box in a Action and  Set the Icon Parameter
3. After few seconds of inactivity or Clicking other place and reclick on Cusom Dialog (Alert Dialog) the Icon is disappeared.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8khfHlzIt2m7RG7r6JbsBv9CQXNjMlUIIKlu1uTRcYGO/uEokUY+OkPlhtYsyCf1VYeWeJ8X4Ip/TIufDtE+4rB0mIQ75izJF9EAzibECmb5iRC5eOQWtPIJ5NCFCH57COihB+FNpidGA93V+MGO+8ZAPZN4TsC1cjD+SIVbD/o1HiKh7VKjh2tmNecCfn

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: v4.1.83+ released August 20, 2024
- Platform: Web
- Browser name and version: Edge Version 127.0.2651.105 (Official build) (64-bit)
- Operating system and version affected: Window 11
```

**Comment by paulperez-dev** [comment]
Hi @nipunanr!

Thank you for reporting this issue. The Engineering team has released a fix for it. Could you please check and confirm if the issue is still occurring on your end?

Thanks for your help!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
