### ISSUE TITLE
Chart bar Issue on border Radius

### ISSUE THREAD

**Issue by Betta-Mula** [FlutterFlow/flutterflow-issues#368]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I am  supposed to be able to view the editor for the border radius on Chart Bar

## Current behavior (required)

I cannot See the Entire editor for the border Radius. I tried using a wider monitor instead of my laptop bur ran to the same problem See attached screenshots for the issue
## To Reproduce (required)

1.Add a Chart bar on any screen
2.Try adjusting the radius for the top left and right borders
3.You will see for the left border the input for editing is hidden. May be its an overflow
4.

## Context (required)

![Screenshot_20230119_010354](https://user-images.githubusercontent.com/119172050/213307628-3b408508-f2de-46a7-8195-5ebe63842e00.png)
![Screenshot_20230119_010522](https://user-images.githubusercontent.com/119172050/213307632-f682496b-9339-4ab1-aea7-a20449de58cf.png)

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by Pepino-GR** [comment]
Hi Betta-Mula,

the end of the row is missing. Thanks for reporting

**Comment by shelpert** [comment]
Hi! I have fixed this issue and it will be in the next release!
