### ISSUE TITLE
CORS error just for POST APIs

### ISSUE THREAD

**Issue by parkos123** [FlutterFlow/flutterflow-issues#3683]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Error: ClientException: XMLHttpRequest error., uri=htt....

We added to calls Access-Control-Allow-Origin = * and it fixed the problem for GET APIs but it consented fot POST apis. In Test mode when I turn on the "Use proxy for the test" it is working fine, but on deployment and without testing proxy it is not working. Any solution on your mind?

### Expected Behavior

It should call the POST request as the GET request.

### Steps to Reproduce

I cannot provide the exact API because it has JSON body with secret authTokens but you can probably see it in the project.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

It is not in the widget tree it is in Api builder

### Visual documentation

![image](https://github.com/user-attachments/assets/7a7f3801-6080-464d-8ee2-7c474ae24b01)
![image](https://github.com/user-attachments/assets/3065a804-ce78-4622-99aa-d069b5b93d89)
![image](https://github.com/user-attachments/assets/6907ce6e-53ad-44cb-996c-cf5d337e1a06)

### Environment

```markdown
- FlutterFlow version: 4.1.83+
- Browser name and version: Microsoft edge
```

**Comment by Alezanello** [comment]
Hi there!

I recommend setting up a proxy for your API. You can create one yourself or use a service like Heroku. This article might be helpful: [Understanding API Calls, CORS, and FlutterFlow's Implementation](https://intercom.help/flutterflow/en/articles/8036270-understanding-api-calls-cors-and-flutterflow-s-implementation).

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
