### ISSUE TITLE
Storyboard does not renew itself

### ISSUE THREAD

**Issue by falcorrus** [FlutterFlow/flutterflow-issues#3684]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For weeks now, when I move parts in the storyboard, they go back after a few seconds.
It happens in all projects.

### Expected Behavior

I move screens in the storyboard and they stay in a new place not going back

### Steps to Reproduce

1. Go into any project
2. In Storyboard move any screen(s)
3. go other tab for 5 seconds
4. return to Storyboard

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcr1sIhgrt9c1qX6avpanjw5KWIiR7szkuxBaCosfZT2BLMcec/RVERtUsCodwlAP2aZgWoW0NrvjdmeV/lcEE2qbIRS/7tydDzJfDigVcmXFJWve0YlAcRhG2HE0bSs2x1dCLRaSi0u3Tn3OvPJZATqJbr2NUQ4Dq/LZO4=

### Visual documentation

<img width="614" alt="2024-08-25_FlutterFlow" src="https://github.com/user-attachments/assets/66a98451-6d6a-4979-9cf0-3ede6ad83e55">

### Environment

```markdown
- FlutterFlow version: 4.1.83
- Platform: MacOS Desktop
- Browser name and version: Chrome 127.0.6533.120
- Operating system and version affected: mac os
```

### Additional Information

It used to be fine but started a 2-3 weeks ago
it happens on web Flutterflow also

**Comment by Alezanello** [comment]
Hi there!

I couldn’t replicate this issue in a new blank project, so it seems to be related to the number of pages you have. According to the documentation, this feature is still in Beta and optimized for projects with up to 30 pages. Since you have more than 40 pages/components, this might lead to issues with saving or syncing changes correctly.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
