### ISSUE TITLE
Chart Widget X and Y axis values are resetting

### ISSUE THREAD

**Issue by turisouza** [FlutterFlow/flutterflow-issues#3685]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the Chart widget and I set the X-axis and Y-axis to the desired fields from an array of objects, the dropdowns for each axis reset to "unset" after a few seconds.

### Expected Behavior

I expected the Char's axis dropdowns to remember what I entered into them.

### Steps to Reproduce

Create a page.
Add a Chart widget to that page.
Set the X and Y axis dropdowns to values from a collection of objects.
Observe the dropdowns (after a short amount of time, they will reset to "unset").

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/HluIhgoeEG0bqJLMZAhR8kQ2InarsvhOpDTUoaF5SuE5kLbuvSXBFVcMOIewhmKGL9jXMGpMLQkoXPU/UrFzWEQ5Rf1rlxWzniQmOXMoSrBs60fmpSI9tjI0C/4Jmn2BVTJvJ2ZXMtig/GSw==

### Visual documentation

https://github.com/user-attachments/assets/91f154b1-9235-44be-befe-bb697292802c

### Environment

```markdown
- FlutterFlow version: v4.1.79
- Platform: MacOS Laptop
- Browser name and version: Chrome 127.0.6533.89
- Operating system and version affected: macOS 14.5 (23F79)
```

### Additional Information

I'm replicating bug #3553 that you closed without resolving.

<img width="825" alt="Captura de Tela 2024-08-25 às 13 44 16" src="https://github.com/user-attachments/assets/0b821f2e-c702-461d-b897-b0ea601a2924">

**Comment by antoniobno1** [comment]
Please help us solve this issue. It has been raised multiple times but the problem persists. It's quite critical for my project to have functioning graphs.

https://github.com/FlutterFlow/flutterflow-issues/issues/3619
https://github.com/FlutterFlow/flutterflow-issues/issues/3553
https://community.flutterflow.io/discussions/post/issue-with-chart-configuration-resetting-to-unset-in-flutterflow-9JVHLEh57UcvM7M?highlight=Dsk0EpHPFXj8Dft

**Comment by GabrielFelix10** [comment]
Yes, guys, there are a lot of threads about this problem, my app goes to production Friday for the first time and I can't release a dashboard screen because this problem still happens

**Comment by binaverse** [comment]
Also experiencing this issue... doesn't matter what type of chart I select... line, bar or pie. I've triple checked my dataTypes in firestore and they are correct. It's a simple table with string and count but the chart widget keeps resetting regardless.

**Comment by GabrielFelix10** [comment]
Nothing yet ?

**Comment by paulperez-dev** [comment]
Hi @GabrielFelix10!

I’m really sorry to hear you’re facing this issue. As you mentioned, other users have reported the same problem, and the Engineering team has been working on it. Could you please confirm if it’s still happening on your end?

Thank you for your patience!

**Comment by DanLika** [comment]
I have an issue with resetting label interval.

**Comment by GabrielFelix10** [comment]
Now it's working here @paulperez-dev 

Thanks so much !!

**Comment by paulperez-dev** [comment]
Thank you for the confirmation, @GabrielFelix10! I’ll go ahead and close this issue now.
