### ISSUE TITLE
Custom function that uses enum fails in compilation and test mode is unavailable - URGENT

### ISSUE THREAD

**Issue by chesskiss** [FlutterFlow/flutterflow-issues#3688]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The test does not compile. See the error below.
![Screenshot 2024-08-24 at 6 34 12 PM](https://github.com/user-attachments/assets/90254576-8850-4959-bca6-26b1aeffeecf)

Please see the recording I made below that recreates the error.

### Expected Behavior

Should compile and run in test mode

### Steps to Reproduce

1. Create a custom function that takes a string list and returns an enum list. You can leave the function empty and return an empty enum list. 
2. Create a widget that calls it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelPHlw852j70E0Ln+de5FlQMwGkQ5a7sviu5+FBQaI+OtE7N3Ps/7aldBYuqHf1dte1L/nk0GpdbNiNj9VsInEzqcbLZ5+M5fUxDjXj2uMKagPIe0SmhtL/pgFWa70qbUoSRAPvBqR3wC7Dn7Ft6Ab3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://drive.google.com/file/d/1lY3o9tRpp54PxDxCpFTbPBBA6zTetVhV/view?usp=sharing

### Environment

```markdown
- FlutterFlow version: v4.183+ (synced)
- Platform: Web
- Browser name and version: Version 127.0.6533.89 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.5 (23F79)
```

### Additional Information

I intend to launch this app in the upcoming days, and now the project is stuck because I cannot test it properly. This is the most crucial time of my startup, so it is very urgent for me to resolve this. If I don't, I'll just copy the code to a local environment, and will, unfortunately, have to continue this project without FF (which was very convenient until now)

**Comment by chesskiss** [comment]
For some reason, it doesn't upload the video?...

**Comment by Alezanello** [comment]
Hi there!

I wasn’t able to replicate the error in a new blank project. Here’s what I did:

1. Created an enum with two values.
2. Created a function that receives a list of strings and returns an empty list of enums.
3. Created a button that calls the function and returns the number of enums in the list.

   <img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3c290df7-856c-4fc5-95f3-4bf2f56fb78a/ea29bed6-c6e3-4650-818c-880f11b6ca1b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYzI5MGRmNy04NTZjLTRmYzUtOTVmMy00YmYyZjU2ZmI3OGEvZWEyOWJlZDYtYzZlMy00NjUwLTgxOGMtODgwZjExYjZjYTFiIiwiaWF0IjoxNzI0NzA1NTQ1LCJleHAiOjMzMjk1MjY1NTQ1fQ.Nezd7mXt0Dawxq_M0KxZgRd56xTDincIHai9k0lb1u0 " alt="image.png" width="1559" height="511" />

   <img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7f0a48c8-ddae-4830-ba2d-35aa1fdc2d00/28511664-cf5e-4768-99ec-fd2eaebbfde0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZjBhNDhjOC1kZGFlLTQ4MzAtYmEyZC0zNWFhMWZkYzJkMDAvMjg1MTE2NjQtY2Y1ZS00NzY4LTk5ZWMtZmQyZWFlYmJmZGUwIiwiaWF0IjoxNzI0NzA1NTQ1LCJleHAiOjMzMjk1MjY1NTQ1fQ.sToHf5c0AmvWhMFO72YPT06lkGrsB7WGq2Pku492W7w " alt="image.png" width="1084" height="799" />

   <img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/33373578-8426-49ad-8a69-d25746eb65d1/cc1c09b2-a667-44c2-9694-f68d18056210?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMzM3MzU3OC04NDI2LTQ5YWQtOGE2OS1kMjU3NDZlYjY1ZDEvY2MxYzA5YjItYTY2Ny00NGMyLTk2OTQtZjY4ZDE4MDU2MjEwIiwiaWF0IjoxNzI0NzA1NTQ1LCJleHAiOjMzMjk1MjY1NTQ1fQ.PL6kdmaj77fV3NcdoQ_MGgQnezY5z429w6kxZBj3cGY " alt="image.png" width="573" height="848" />

**Comment by chesskiss** [comment]
@Alezanello  please see the video below on how I did it (I update firestore):
https://drive.google.com/file/d/1lY3o9tRpp54PxDxCpFTbPBBA6zTetVhV/view?usp=sharing

**Comment by chesskiss** [comment]
@Alezanello Ok seeing I'm not getting any answers, which I feared would happen since you didn't change the status back or try again after my clarification, I'll have to repost it again.

**Comment by Alezanello** [comment]
I'm sorry for the late response, I'll try to replicate what you have in the video just need a little more patience.<br>I'll close the new post as duplicated and follow this as the original one

**Comment by Alezanello** [comment]
I found the issue, though a bit late—it’s related to how custom functions are serializing enums. As a workaround, I was able to achieve the desired outcome using custom actions instead of custom functions. Here’s the code I used:

```dart
extension EnumTestExtension on EnumTest {
  String serialize() {
    return this.toString().split('.').last;
  }
}

Future<List<EnumTest>> enumTestAction(List<String> list) async {
  return [];
}
```

With this approach, I successfully created the document in Firestore by using the action output result list as the field value.<br><br>So first you create an extension of the enums to serialize the strings and then execute the function<br><br>here is the public project in case you want to clone it or check it: [https://app.flutterflow.io/project/qa-1817-nqezfl](https://app.flutterflow.io/project/qa-1817-nqezfl)

**Comment by chesskiss** [comment]
@Alezanello Thank you very much!!! I will try it!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by chesskiss** [comment]
@Alezanello Oh sorry, forgot to inform you- problem was resolved! Thank you!
