### ISSUE TITLE
Mux Livestream bugs

### ISSUE THREAD

**Issue by sirwes** [FlutterFlow/flutterflow-issues#369]
There are a bunch of incorrect naming, package calls, etc. that are just wrong in the mux broadcast widget code & the flutter flow implementation.

Additionally, it does not have support for the web, which is necessary for me.

https://community.flutterflow.io/c/bugs/mux-livestreaming-bugs

**Comment by brucevz** [comment]
We also reached out to support about this. Can't build in test mode or run mode.

Package version needs to be updated I believe.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. Fixed to a few Mux-related bugs were deployed yesterday. If the issue persists, please open another issue, and please follow our bug report template next time :-)
