### ISSUE TITLE
Chart that no longer applies modifications

### ISSUE THREAD

**Issue by julien-hetic** [FlutterFlow/flutterflow-issues#3692]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 I’m trying to change the interval label on all my graphs, but none of them are applying the change. After a few seconds, they automatically revert to their original state without any action on my part. I’ve tried on both the desktop and web versions, and I also cleared the cache, but nothing works.

### Expected Behavior

I want to be able to update the interval labels

### Steps to Reproduce

Try updating an interval label on one of the charts in the graphStat component.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXyfHhuJFJob1E1aXicvpvmmMwFj8LaJI7m+tvGBA2GK7vOpkMZMjEaXdZX9TmYX1UOlmgmn0CwfzqjvPhUfECAySufNR607V+VhWVWl66b4S1Cc2CYERBL/hVG0yhy7uJnSZ+VLNfSUIDw0+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

Uploading Enregistrement de l’écran 2024-08-26 à 18.23.37.mov…

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.83 released August 20, 2024 Flutter version is 3.22.2
- Platform: Web & MacOS Desktop
- Browser name and version: Chrome Version 127.0.6533.89 (Build officiel) (arm64)
- Operating system and version affected: Sonoma 14.0
```

**Comment by Alezanello** [comment]
Hello!!<br><br>This is a known issue and will be fixed in next deploy to production!<br><br>Follow this issue for any updates: [https://github.com/FlutterFlow/flutterflow-issues/issues/3553](https://github.com/FlutterFlow/flutterflow-issues/issues/3553)<br><br>I'll close this issue as duplicated!
