### ISSUE TITLE
White screen on app restart after termination

### ISSUE THREAD

**Issue by arthit666** [FlutterFlow/flutterflow-issues#3695]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

white screen when terminate app and restartAfter terminating the app and restarting it, the screen appears white with no content visible.

### Expected Behavior

The app should load normally and display the last viewed screen or the home screen.

### Steps to Reproduce

1.Run the app normally
2.Use the app (login if necessary)
3.Terminate the app completely (force close or remove from recent apps)
4.Restart the app
5.Observe white screen instead of expected conten

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozPHlwItIm+Fc0ISJccBKjSQROUx9a4IvkspBZywgfZzzBLN/fPfQP1pVYMDhY1Vle2CMp14D/6nSj+DtD8YoZE6uY4h+yal2ETvjczulVJOTF7uoZ2pfM/1WIWqZ56u7vyNNBLN1dCUT3GD2fefLQXXfQ4zQDFQwSq/LZO4=

### Visual documentation

normally 
![Screenshot 2024-08-27 165210](https://github.com/user-attachments/assets/ab1ae65e-fbe7-4d9c-aadf-25a974904001)
![Screenshot 2024-08-27 165256](https://github.com/user-attachments/assets/e11810f7-4d6d-4551-be9b-d9754cc188cb)
when terminating  and restart
![Screenshot 2024-08-27 165359](https://github.com/user-attachments/assets/50f8a1bb-d4fb-435b-8c76-43a19475748a)
menu page but white UI

### Environment

```markdown
- FlutterFlow version: 4.1.83+  
- Platform:Mobile
- Operating system and version affected:Windows 11 Pro
```

**Comment by paulperez-dev** [comment]
Hi @arthit666 are the logs showing some info?

**Comment by arthit666** [comment]
@paulperez-dev Sample ui

https://github.com/user-attachments/assets/d254632f-bd03-48f1-88c3-4d6b406f55c1

**Comment by paulperez-dev** [comment]
Hi @arthit666,

I’m unable to recreate the issue on my end. Could you please check with the latest version of FlutterFlow or try using a different simulator? Also, does this issue occur on a real device?

Let me know what you find!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
