### ISSUE TITLE
Flutterflow Status Down

### ISSUE THREAD

**Issue by GeoffroyMeunier** [FlutterFlow/flutterflow-issues#3696]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow Status seems to be down

### Expected Behavior

This page should works: https://status.flutterflow.io/

### Steps to Reproduce

Visit https://status.flutterflow.io/

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

---

### Visual documentation

<img width="455" alt="flutterflow status" src="https://github.com/user-attachments/assets/bee81554-3bb5-496b-be00-8ebb61ad8f4f">

### Environment

```markdown
- FlutterFlow version: na
- Platform: na
- Browser name and version: na
- Operating system and version affected: na
```

**Comment by rzambroni** [comment]
Hey Geoffroy, thanks for the report, will send it to the team so they can take a look.

**Comment by rzambroni** [comment]
@GeoffroyMeunier, according to our team, it seems there is an issue with the service we're using on that subdomain to track server status. However, we were wondering why you were visiting the status website in the first place—were you experiencing any service interruptions or issues?

**Comment by GeoffroyMeunier** [comment]
Data no longer load on our app and we didn't change anything. It started around 12h30 EST (~2 hours ago). Everything seems fine on our side, so we were trying to figure out if it's an issue with Fluttflow or Firebase.

Our app: https://yurai.co/discover
You should see series and images on this page

In Flutterflow we see this: 
![CleanShot_2024-08-27_at_13 58 12](https://github.com/user-attachments/assets/728ea97d-2378-4941-8620-a21943200430)
![CleanShot_2024-08-27_at_13 39 56](https://github.com/user-attachments/assets/a4156360-3ca8-45f8-97a3-3d2b9c537243)

But everything seems to be fine on our side, so we don't understand where the issue comes from.

**Comment by rzambroni** [comment]
can you please share the bug-report-code so we can investigate further? You can do so by left clicking on any widget on the widget tree. Thanks!

**Comment by GeoffroyMeunier** [comment]
We don't have any bug-report-code or error. That's why we don't understand the situation. 😕

**Comment by GeoffroyMeunier** [comment]
miss clicked. The issue is still ongoing.

**Comment by rzambroni** [comment]
The bug report code is just a code you can generate so we can have access to your project to investigate.

Right click on any widget in the widget tree and click on get bug-report-code

**Comment by GeoffroyMeunier** [comment]
Oh ok, sorry! Here's the bug-report-code:

ITEeys/qw5dNpb0E+aXbbu1arwMwGkQ5a7sviu5+FBQaI+PvEOx3Zc74T1pvYuqHd2NUA1n+vHwJ/vDHuOzPDPc5OT+afKJNyYd5UxDgLHyleJS2Ec2CdXNPJ8BWJ0isyrevrQl+AOhZS04f7E+qC++Aa3qCf9qOYwx5e6fDbOY=

**Comment by agreaves** [comment]
Hi @GeoffroyMeunier, thanks for the report and the additional information. Can you describe a bit more the issue you're seeing? I understand the issue you're facing with the CMS and schema validation, is that the extent of the issue? We've started to look into that, but wanted to check if the issue is bigger than that since you said "data no longer load on our app" which seems worse (hoping it's just CMS).

Let me know! Thanks.

**Comment by GeoffroyMeunier** [comment]
Hi, thank you for your quick response time, it's really appreciated!

Users can still login on our app, which is a good sign I think. But when it comes to elements like: comments, likes, series (digital comics), and any other type of content, there's nothing displayed in the app.

Here's what we see now:
![Screenshot_20240827-173345](https://github.com/user-attachments/assets/4c16e77a-887b-471c-b2f2-1db0c940c9ff)

And here's what we are supposed to see (screenshot from a couple days ago):
![Screenshot_20240823-070134](https://github.com/user-attachments/assets/9f26469c-dc98-4bed-bddb-9e4f38e4e976)

My colleague demonstrates in this screenshot that the elements are called correctly via the API, but nothing is displayed.
![APICallImages](https://github.com/user-attachments/assets/c633b406-e7e5-4cf4-90a3-89fe1a4bc982)

In Debug mode, all documents IDs are correctly loading, but not displayed.
![DebugMode](https://github.com/user-attachments/assets/a14fc7a1-84f9-445f-b5d2-abfd67158066)

We don't understand the problem since everything seems to be fine, but as you can see, the result is not what is intended.

**Comment by GeoffroyMeunier** [comment]
We might have found the cause of the issue. We are working on something and we'll share with you if it's the solution or not.

**Comment by agreaves** [comment]
Ok good to know, thanks Geoffroy. I'll await your response but will continue to investigate in the meantime.

One other follow up, is it information from the documents that appears to be missing (e.g. title, comment) or image assets or both? From the screenshot at the very least the images didn't seem to be loaded but wanted to check on the others.

**Comment by GeoffroyMeunier** [comment]
So what we believed to be the cause was indeed the source of the issue. We fixed the issue and all the data immediately showed up in all our apps as intended.

What happened: A user generated data of a type that had never been generated before. The data type was the wrong one, which seems to have created an error for everything related to series (the affected document type in Firebase). However, on our platform, almost everything is related to series, so it affected the entire platform.

The issue was on our side and we are really sorry for the trouble. Thank you very much for trying to resolve the issue with us. We were sure at first that the problem was with Flutterflow since we had an error on the status page, but it was just a coincidence.

Thanks again and take care!
