### ISSUE TITLE
Actions without content cause publish issues, but do not flag as errors.

### ISSUE THREAD

**Issue by bsturdy** [FlutterFlow/flutterflow-issues#3697]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you define an action in flutterflow (for example, an on tap action), if you do not add anything to this action but keep it alive and empty, your publishing will fail with a message 'Unsupported operation: Attempted to change a read-only message (flutterflow.FFActionNode)'. However, this is not picked up as a warning or error inside of flutterflow, which could make debugging difficult on larger projects.

### Expected Behavior

An error or warning should appear when you leave an action empty but alive.

### Steps to Reproduce

1. Add an action
2. Do not add content to the action, just leave it empty
3. Try to publish your project (i tested with IOS)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiPHq2It1xOVY0L6Ja8dsqCAUJmkcTL4zlO1HcxAYGO/yPbJ/PuD4VBRBTtejTXlhHE6Lgk4d0N7ljdnxM+wqFxeafKZA/qpccQ6UUXq8R4iPCquKZ3JSHftRCXasyru7kwl/Jspoci0h7GCXfui9aCvfJ5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/4c1e39ab-d062-4882-b6fc-dabcf23eadca)

### Environment

```markdown
- FlutterFlow version: 4.1.84
- Platform: Chrome development, IOS publishing
- Browser name and version: Chrome
- Operating system and version affected: Win 10
```

**Comment by Alezanello** [comment]
Hi there!

I wasn’t able to replicate this issue. I created a container, added both On Tap and On Double Tap action flows without any actions inside, and deployed it successfully to both the web and an iOS simulator without encountering any problems.<br><br>(Tested on Web and MacOs App)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e00f52a7-22e6-49ab-aeb4-bb1a984f2373/79e53a57-0be8-4948-b0b4-3c17258ed8d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMDBmNTJhNy0yMmU2LTQ5YWItYWViNC1iYjFhOTg0ZjIzNzMvNzllNTNhNTctMGJlOC00OTQ4LWIwYjQtM2MxNzI1OGVkOGQ2IiwiaWF0IjoxNzI0ODQzOTIzLCJleHAiOjMzMjk1NDAzOTIzfQ.6Vfy7DJ_mxAtF6-Yndzijp48dSoOkqaDiAsUVw1hnAE " alt="ableToDeploy.gif" width="1901" height="826" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/76b2bd08-f4ee-4bfc-8694-375675df0bbd/1e50936f-5397-4a4b-a53d-fc811dd4bdd9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NmIyYmQwOC1mNGVlLTRiZmMtODY5NC0zNzU2NzVkZjBiYmQvMWU1MDkzNmYtNTM5Ny00YTRiLWE1M2QtZmM4MTFkZDRiZGQ5IiwiaWF0IjoxNzI0ODQzOTIzLCJleHAiOjMzMjk1NDAzOTIzfQ.WvEKxKa7fLE8PaebWdaVwqpCEL0FFCrQSzDlKR90WeI " alt="Imagen de WhatsApp 2024-08-28 a las 08.17.24_fa7cce4a.jpg" width="1280" height="726" />

**Comment by bsturdy** [comment]
Hi,

Try it on mobile deployment rather than web deployment. You should
encounter a code magic compile error.

**Comment by Alezanello** [comment]
It also compiled successfully to the iOS Simulator, following the same procedure as mobile deployment.

**Comment by bsturdy** [comment]
Interesting, I will test this again later on my system and let you know.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
