### ISSUE TITLE
APK build fails under certain conditions with periodic timer and terminate action

### ISSUE THREAD

**Issue by SamVdvd** [FlutterFlow/flutterflow-issues#370]
## Expected behavior (required)
APK build fails under certain conditions 

## Current behavior (required)
APK build fails when "periodic action", "terminate" and "api call" are combined in the "on page load" logic.

## To Reproduce (required)

1. Create new page
2. Add the logic as depicted in the screenshot to the "on page load" actions
3. Try to build the APK

## Screenshots / recordings
![2023-01-19 16_47_21-Dashboard - FlutterFlow](https://user-images.githubusercontent.com/121506272/213489608-a6a2eb06-b3d8-4e0f-8009-6272958f6a4a.png)

![2023-01-19 16_45_19-Dashboard - FlutterFlow](https://user-images.githubusercontent.com/121506272/213489649-09010cc6-27fa-426b-a106-5af2b5e4f8bb.png)

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: Chrome 109.0.5414.75
* Operating system and version (desktop or mobile): windows 11

**Comment by bulgariamitko** [comment]
Can you please include the Bug Report as well?

**Comment by bulgariamitko** [comment]
I am closing this as the user was not active in the last 2 weeks, but please feel free to open it again if you still have this issue.
