### ISSUE TITLE
Deleting action will create an action with no actions in it, and cause the application to fail to compile

### ISSUE THREAD

**Issue by iq-charlie** [FlutterFlow/flutterflow-issues#3704]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On several occasions since the last recent update, if I delete the final action in an action tree, an arrow continues to appear in the widget tree and if you hover over it it'll say there are zero actions in it. The real problem with this is that once that has happened the application will fail to compile in test mode. The only solution I've had so far is to delete the entire widget and program it again. 

https://github.com/user-attachments/assets/b89642ca-db85-47c8-9d05-15e25df009ef

### Expected Behavior

The expected behavior is that a deleted action would delete and the widget tree would not show the little green arrow and certainly would not show an action with zero actions in it

### Steps to Reproduce

Since the last update, if you delete the last action in an action tree where the expectation is that the entire action is removed from the widget tree, it still remains with zero actions in it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YMS8+kMxJVXemndGNEL2KagmIz/v+NkfDAA+UqNUutfaJB+bt+cj3iLXiVeK6qDqigf0BTJ9xJJVyw34m3rRRCIfpfSl4a1Dque+TJYz3tGL7MIkUeDcj+Jp3XnGOqQ0SLb3kNh1JWeC/v

### Visual documentation

A video has been posted above

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform:W11 Desktop and Chrome
- Browser name and version: Chrome
- Operating system and version affected: W11
```

### Additional Information

It is clearly slowing us down and particularly work so if the bug occurs in a piece of work that has taken a reasonable length to achieve and that the bug is unnoticed for a while so that a revert is not possible

**Comment by paulperez-dev** [comment]
Hi @iq-charlie! This is the expected behavior. If you want to remove the event (like an OnTap) tap on delete in the left panel (on the Action Flow Editor).

I'm closing this issue.
