### ISSUE TITLE
Auth Page Setup redirect

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3705]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we get this error: Auth Page Setup (Auth action requires authentication to be enabled for the project.), upon click it should take me to Setting-> Authentication page. However, it shows General->App details page, which may leave users confused what to do next. 
![image](https://github.com/user-attachments/assets/544f8587-7055-4c20-b0d9-8ba4ba2f5f2d)

### Expected Behavior

Upon click, it should open the Settings->Authentication page, as show in image
![image](https://github.com/user-attachments/assets/319a4476-8066-4138-bbdb-4c2a81d6f744)

### Steps to Reproduce

You may Disable "Enable Authorisation" button in the Authorisation Section in Settings. Once you see this error, click on it-it would redirect you to "General->App details page"
Also, please access my project to replicate.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq2ItOodhE7rXyccd7/WYXC217beYescp/bxIgGIDzPOw+ZPXsbRBtXsviTWNMMUSmmj4z0uiKj4bLM8ABFzeYbph7zs9Abg3vRkSVa5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

images attached

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 27, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2

Project: letMeDraw
Project ID: let-me-draw-zo88ww
```

**Comment by Alezanello** [comment]
Hi there!

Thank you for bringing this to our attention. I’ve just confirmed this behavior, and it’s definitely not the expected one. I’ll forward this ticket to the engineering team for a fix.

Thanks again for your help!
