### ISSUE TITLE
TextField unexpectedly autofocuses after initial focus when dismissing a bottom sheet or navigating to another page and returning.

### ISSUE THREAD

**Issue by bdonovan858** [FlutterFlow/flutterflow-issues#3707]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am encountering an issue with the TextField widget in my FlutterFlow project. Although I have explicitly set the autofocus property to false for my TextField, the widget behaves as if autofocus is enabled under **specific scenarios**. After initially focusing on the TextField and dismissing the keyboard by tapping outside (using a tap gesture recognizer set to dismiss the keyboard), if I perform an action such as opening a bottom sheet or navigating to a different page and then return to the original page, the TextField unexpectedly regains focus, causing the keyboard to appear again.

This issue occurs despite the autofocus property being disabled in the widget settings. Note, this behavior was not present in previous builds of FlutterFlow (approximately 4 weeks ago).

### Expected Behavior

The TextField should not autofocus after the initial focus is dismissed and the bottom sheet is dismissed, or the user navigates back to the original page.

### Steps to Reproduce

1. Navigate to a page containing a TextField (autofocus OFF).
2. Tap on the TextField to focus on it. The keyboard appears as expected.
3. Dismiss the keyboard by tapping outside the TextField.
4. Perform an action that either i) opens a bottom sheet, or ii) navigates to another page.
5. Dismiss the bottom sheet or navigate back to the original page (using a navigate back action).
6. Observe that the TextField unexpectedly regains focus and the keyboard appears again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lsmAz4Z2scdY0a6JaMdVtGU4G1M7aLg7i9UaYws8J5DLBIYuP//7ak5uTde0S39iJmCJoHgepuvemvHxCe4BE02sbNV5z81UZALJWj6jR7qSPaqORm5/AptUGWK41qSC2yZDJvtuclJg2l72Nu+XYB/YJqW2NlYFHv3/C5CK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/741cc89d-4d80-4dcb-89a2-56037ffcb470

### Environment

```markdown
- FlutterFlow v4.1.85+ released August 27, 2024, Flutter version is 3.22.2
- Platform: iOS
```

**Comment by paulperez-dev** [comment]
Hi @bdonovan858! So sorry you are facing this issue. We are tracking this issue here: [https://github.com/FlutterFlow/flutterflow-issues/issues/3612](https://github.com/FlutterFlow/flutterflow-issues/issues/3612)<br><br>I will be closing this issue as duplicate.

**Comment by bdonovan858** [comment]
Thanks @paulperez-dev, I'll track the other issue.
