### ISSUE TITLE
Reset password action with bottom sheet shows error underneath keyboard and bottom sheet

### ISSUE THREAD

**Issue by halvorot** [FlutterFlow/flutterflow-issues#371]
## Expected behavior (required)
Expect error (e.g. Error: the email address is badly formatted) to be shown on bottom sheet. 

## Current behavior (required)
I currently have to close the bottom sheet (quickly before the error disappears) to see the error at the bottom of the screen. I would like it to show above the keyboard on the bottom sheet itself.

This happens both in the app and in run/test mode

## To Reproduce (required)
1. Create new page
2. Add button to open bottom sheet
3. Add bottom sheet
4. Add input field for email and a button
5. Add reset password action to button on tap
6. Run the app
7. Enter an invalid email

### Bug Report Code (required, generate from Widget Tree)
IT4ozMrqx5BOseFK0L6JccBKjSQ4Ql9+bZIalcpOGDsdF4iuPOxzac7RVE9WXdOrSnxfKEWKoHME0ezuuOzmUfQqGEyAbJh71s1cSQHwID/kEuzyT+3IHDUHZbsSXTTm

## Screenshots / recordings
![Skjermbilde2](https://user-images.githubusercontent.com/36247551/213525974-8c8344c6-6be6-4abf-b0a8-e9f9a40fd931.PNG)

![Skjermbilde3](https://user-images.githubusercontent.com/36247551/213525986-7f86d53f-c1ad-45fd-9249-6223dca87f1b.PNG)

![Skjermbilde4](https://user-images.githubusercontent.com/36247551/213525994-e2eb086e-315c-4341-9bf0-77fd57e2657f.PNG)

## Your environment

* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: chrome
* Operating system and version (desktop or mobile): windows, desktop

**Comment by Pepino-GR** [comment]
Hi halvorot,

the easiest way is to use a bottom padding(40) for the bottom sheet.

**Comment by halvorot** [comment]
Thank you for your suggestion. Yes that would solve the problem of viewing the error, however it does look not very good (see image). Ideally it would add a padding of 40 when an error is shown and then remove it when not. Even more ideal would be to set the error as the "top layer" somehow so that it shows on top of everything.

**Comment by Pepino-GR** [comment]
You can do all of the stuff with custom code. If you want to set the position of the Error Code yourself, I can initiate a feature request.

**Comment by halvorot** [comment]
I imagine this is a common problem when using bottom sheets and I believe it should be default behavior without custom code. So I would appreciate if you could make a feature request, that would be great.

**Comment by agreaves** [comment]
Hi @halvorot, thanks for the bug report. This is indeed an issue, however unfortunately, this is an issue at the Flutter level and there are no easy workarounds for this particular issue... Sorry about this!

I'll have to close this issue for now until there is a viable alternative solution.
