### ISSUE TITLE
I can't change the string for camera and photo gallery permission request.

### ISSUE THREAD

**Issue by turisouza** [FlutterFlow/flutterflow-issues#3710]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When configuring the upload option, I can't find a field to update this string, even though Apple is asking me to make this change by making the request more explanatory.

### Expected Behavior

In the photo/video upload field there should be a field where I can change the authorization string

### Steps to Reproduce

1 - I configure the image upload action on a button
2 - I can't find the option to edit the authorization string
3 - Apple is denying my application because I can't edit it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

if ((_model.uploadedFileUrl == null || _model.uploadedFileUrl == '') &&     (currentUserPhoto == null || currentUserPhoto == ''))   AuthUserStreamWidget(     builder: (context) => FlutterFlowIconButton(       borderColor: FlutterFlowTheme.of(context).primary,       borderRadius: 100,       borderWidth: 1,       buttonSize: 80,       fillColor: FlutterFlowTheme.of(context).accent1,       icon: Icon(         Icons.upload,         color: FlutterFlowTheme.of(context).primaryText,         size: 24,       ),       onPressed: () async {         final selectedMedia = await selectMediaWithSourceBottomSheet(           context: context,           maxWidth: 130.00,           maxHeight: 130.00,           imageQuality: 51,           allowPhoto: true,         );         if (selectedMedia != null &&             selectedMedia                 .every((m) => validateFileFormat(m.storagePath, context))) {           setState(() => _model.isDataUploading = true);           var selectedUploadedFiles = <FFUploadedFile>[];           var downloadUrls = <String>[];           try {             selectedUploadedFiles = selectedMedia                 .map((m) => FFUploadedFile(                       name: m.storagePath.split('/').last,                       bytes: m.bytes,                       height: m.dimensions?.height,                       width: m.dimensions?.width,                       blurHash: m.blurHash,                     ))                 .toList();             downloadUrls = (await Future.wait(               selectedMedia.map(                 (m) async => await uploadData(m.storagePath, m.bytes),               ),             ))                 .where((u) => u != null)                 .map((u) => u!)                 .toList();           } finally {             _model.isDataUploading = false;           }           if (selectedUploadedFiles.length == selectedMedia.length &&               downloadUrls.length == selectedMedia.length) {             setState(() {               _model.uploadedLocalFile = selectedUploadedFiles.first;               _model.uploadedFileUrl = downloadUrls.first;             });           } else {             setState(() {});             return;           }         }       },     ),   )

### Visual documentation

<img width="227" alt="Captura de Tela 2024-08-29 às 16 57 51" src="https://github.com/user-attachments/assets/e6ec8b2a-74f8-4d2f-9fbc-8f59f2cdcbb0">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 28, 2024
Flutter version is 3.22.2
- Platform: MacOS
- Browser name and version:Versão 127.0.6533.120 (Versão oficial) (arm64)
- Operating system and version affected: MacOS SONOMA 14.5 (23F79)
```

### Additional Information

Apple is denying my app because of this issue

**Comment by rzambroni** [comment]
Hello, thanks for taking the time to reach out. <br><br>Have you seen the App Settings > Permissions Page?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/32e62d4b-b08d-46d6-9be2-c808b169e80d/7f847c16-8bf5-408a-8c8a-3208fd9ae627?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMmU2MmQ0Yi1iMDhkLTQ2ZDYtOWJlMi1jODA4YjE2OWU4MGQvN2Y4NDdjMTYtOGJmNS00MDhhLThjOGEtMzIwOGZkOWFlNjI3IiwiaWF0IjoxNzI0OTYzMjQ5LCJleHAiOjMzMjk1NTIzMjQ5fQ.-_-pujBrqxwsvKnE8ityAs1QepMar0aZb8nO9A-iZYg " alt="image.png" width="1409" height="892" />

<br><br>There you can customize the default messages.<br>[Here](https://docs.flutterflow.io/resources/projects/settings/project-setup/#permissions) is the full documentation too.

Hope that helps.

**Comment by turisouza** [comment]
Very Thanks!
