### ISSUE TITLE
Actions Flow Editor Crashing in Components

### ISSUE THREAD

**Issue by sdschroeder** [FlutterFlow/flutterflow-issues#3711]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When opening the actions flow editor, the left pane for the triggers is gray and the flow shows 1 action that isn't used. No idea where it came from. It doesn't show the 8 actions that are assigned to the button.

Also, when searching the triggers tab, it crashes the window going all gray. This worked fine yesterday.

### Expected Behavior

I would expect to see the 8 actions on my button in the flow.

### Steps to Reproduce

Go to an existing widget with actions on it in a component.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kPLqy4hJpbxD7arqcvlahio5KVh9bLg7j+1BaCgoIYyuOpl/evXsUxJuZPWoTQlHMUSmmnEd+dWOj+HhJ/AqGw6ZR4h61Yd9Ez3yJWGQQZOBCZOKVHNfEd1MJnKw0p6JhRNSNvVoSF4G2lOQN9yRdBTaQpDUImdISq/LZO4=

### Visual documentation

![action-flow-editor](https://github.com/user-attachments/assets/6d9becff-92da-4182-a14a-478f05076162)
![action-flow-gray](https://github.com/user-attachments/assets/d8713e84-f171-4c3c-b955-5b2da355ea1f)
![btn-add-post](https://github.com/user-attachments/assets/6c57d284-ea02-4cc5-8f19-4806bc0361d8)

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: Mac OS and Web
- Browser name and version: Brave/Chrome
- Operating system and version affected: Mac OS 14.6.1
```

**Comment by ExPrLtd** [comment]
Hi @Alezanello, any progress on this? I'm currently stuck with issues I can't resolve because the actions flow editor won't show actions on a pre-existing component. Do I need to rebuild the flow on this button to get past this issue?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by sdschroeder** [comment]
Hi @Alezanello , no, still experiencing the issue on existing action flows. New ones seem to be fine. I'm on v4.1.91.

**Comment by Alezanello** [comment]
Could you please specify which actions are causing the issue and where they are located in your project? This will help me better understand and assist you in resolving the problem.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by sdschroeder** [comment]
Hi @Alezanello, sorry for not getting back to you. I went ahead and recreated my actions flow to get things working again, but I did just check the one with the issue and it was working. I believe this has been resolved.
