### ISSUE TITLE
Validation Successful, but Reverting to Previous State

### ISSUE THREAD

**Issue by Lulzsec1900** [FlutterFlow/flutterflow-issues#3712]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm facing issues with a bug when trying to validate the Firebase schema. I’ve configured the rules in Firebase, and when I try to validate them in FlutterFlow, they are validated successfully. However, after switching pages, the configurations I just made revert to their previous state, as if I hadn’t validated them. This is preventing me from accessing the profiles in my app. This "bug" or error has been occurring since the latest FlutterFlow update. Does anyone have a solution?

### Expected Behavior

I just need to validate the Firebase rules in FlutterFlow so that my app returns to normal, but this is preventing me, and I don’t know what to do anymore.

### Steps to Reproduce

1. Go to page firestore
2. Firestore Settings
3. Try to validate
4. Change page and return to Firestore Settings, Schema not Deployed

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Visual documentation

https://github.com/user-attachments/assets/2c33c039-82a8-4619-88ac-0179d64c79eb

![Captura de tela 2024-08-28 191344](https://github.com/user-attachments/assets/8649f639-05d5-45c3-85b9-67a39685c397)
![Captura de tela 2024-08-29 054354](https://github.com/user-attachments/assets/ca490393-2d6c-455d-b139-611f11d2cf12)
![Captura de tela 2024-08-29 054448](https://github.com/user-attachments/assets/a28558ef-04c3-499e-99bc-a6f88078ac52)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:browser
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hi there!

Thank you for bringing this to our attention. I want to let you know that this is a known issue, and the engineering team has already prepared a fix, which will be deployed in the next release. In the meantime, I'll mark this as a duplicate.

Thanks again for your help!
