### ISSUE TITLE
Error due to invisible Media Upload Actions

### ISSUE THREAD

**Issue by BenReim** [FlutterFlow/flutterflow-issues#3713]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can not run my project as the following error is shown:
```
Cannot have multiple upload files in the same node.
```
Note that i have only a single upload action node, and I'm unable to fix the error in flutterflow. 
There seems to be a upload action that is defined, but not shown in the flutterflow editor.

When looking at the `Page > Model` code, I can see that the generated code contains redundant variable declaration.

```flutter
  bool isDataUploading1 = false;
  List<FFUploadedFile> uploadedLocalFiles1 = [];

  bool isDataUploading1 = false;
  List<FFUploadedFile> uploadedLocalFiles1 = [];

  bool isDataUploading1 = false;
  List<FFUploadedFile> uploadedLocalFiles1 = [];
```

### Expected Behavior

FF UI should show all existing action definitions

### Steps to Reproduce

I believe this error occured after cut & pasting an upload action to a different node. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klvHl3412odtH7qXxbe1WlmYvQ1M3TL03pu0bFEggGLbrBIYMaeDsSExvOe2/YG9DKEWLgnEH3MGOitmWEMAEGzOuf75N+bpIWDmWcD6/aoSlCYewWXB8TN1NBUyC0LbUhhRAA7BsSC1h31ymG/KvbD/vJ7X7Zwh9f6PHaOI=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @BenReim! So sorry you are facing this issue. I was unable to reproduce it.

I copied and pasted the action but the variable name changed each time. Generated code: 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/591984cb-145f-4b42-a19e-fdb841657fd9/ae264683-7715-4a40-bb91-0af02b723a9b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81OTE5ODRjYi0xNDVmLTRiNDItYTE5ZS1mZGI4NDE2NTdmZDkvYWUyNjQ2ODMtNzcxNS00YTQwLWJiOTEtMGFmMDJiNzIzYTliIiwiaWF0IjoxNzI1MDI3NzUyLCJleHAiOjMzMjk1NTg3NzUyfQ.V7OdHzN0cIlQTEB4Q87AxSwXqMY_QubiG0x1hH3nKmo " alt="image.png" width="391" height="162" />

Can you please try removing all the actions and creating a new one? You can copy/paste this new action and it should work.

**Comment by BenReim** [comment]
Hi @paulperez-dev , thanks for taking a look! I already tried deleting all the actions, however it did not change the error. 

The only way left was deleting the entrie page and starting from a blank page again. 
After that, I did not face the error again. As I'm now also unable to reproduce the bug, i will go ahead and close the issue.
