### ISSUE TITLE
A bunch of errors when running locally on iOS. Everything is fine on Android Apk.

### ISSUE THREAD

**Issue by Deviocom** [FlutterFlow/flutterflow-issues#3714]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A bunch of errors when running locally on iOS. Everything is fine on Android apk. I've tried everything, but I can't solve this problem in any way, I even recreated the project from scratch. I'll try to show it in the screenshots.

It's currently hanging on an empty screen. as in the first screenshot.

There are no bugs and errors in the project.

### Expected Behavior

The iOS simulator should be running. It's currently hanging on an empty screen. as in the first screenshot.

### Steps to Reproduce

Just run locally on the ios simulator

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlcjfsIV1m+EA+KncYMFsnSc4GUMcWOdEl+tuZwgbIoznBux3OczOVFFDXd+raVNcJVqginIH/9KMjYbXM/kEFxKrfJRGzc9idgLee2imaZ/TO5C0OnwkHd5PIG6O37urrh4nBO5ZLkYY7TmuBdivSivDFOu/Zwh9f6PHaOI=

### Visual documentation

![CleanShot 2024-08-30 at 16 24 48@2x](https://github.com/user-attachments/assets/0b7a35a3-9eed-4629-a9d7-c11395b87a7c)
![CleanShot 2024-08-30 at 16 26 04@2x](https://github.com/user-attachments/assets/e698f32a-273a-423a-a73a-d7524d880d8e)
![CleanShot 2024-08-30 at 16 26 21@2x](https://github.com/user-attachments/assets/c19bef83-8283-4c22-9da0-fe39c7d677bb)
![CleanShot 2024-08-30 at 16 26 44@2x](https://github.com/user-attachments/assets/6265509d-c113-464f-969c-6994148ae4cd)
![CleanShot 2024-08-30 at 16 27 06@2x](https://github.com/user-attachments/assets/a97b9c7f-3bc9-4d83-bcfb-2050458099a5)

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: MacOs
- Browser name and version: MacOs
- Operating system and version affected: Sonoma 14.5 (23F79)
```

### Additional Information

This greatly violated the deadlines of the project, which caused problems in the business. I hope for a quick solution to the problem

**Comment by paulperez-dev** [comment]
Hi @Deviocom! So sorry you are facing this issue.

Based on the captures you shared, the issues seem to be related to an overflow in the UI (maybe that's why the screen remains white in the simulator). 

Can you please try to show a very basic screen on the simulator? This way we can confirm it is working as expected.

Also, please try to solve those warnings before testing again, it may be the root of the main issue.

**Comment by Deviocom** [comment]
> Hi @Deviocom! So sorry you are facing this issue.
> 
> Based on the captures you shared, the issues seem to be related to an overflow in the UI (maybe that's why the screen remains white in the simulator).
> 
> Can you please try to show a very basic screen on the simulator? This way we can confirm it is working as expected.
> 
> Also, please try to solve those warnings before testing again, it may be the root of the main issue.

Thanks for the quick response!  I don't understand how to solve this problem yet, I tried to delete the content on the test pages, but it didn't help. And what do you mean by the word show a simple screen?. The authorization screen is working. But it freezes after authorization .

**Comment by Deviocom** [comment]
> Hi @Deviocom! So sorry you are facing this issue.
> 
> Based on the captures you shared, the issues seem to be related to an overflow in the UI (maybe that's why the screen remains white in the simulator).
> 
> Can you please try to show a very basic screen on the simulator? This way we can confirm it is working as expected.
> 
> Also, please try to solve those warnings before testing again, it may be the root of the main issue.



### Hi! How are you? 
What do you say, this has a very bad effect on the timing of our project ((

**Comment by paulperez-dev** [comment]
Hi @Deviocom! Where you able to solve the overflow issues?

A simple screen is a screen with only a button without any additional actions or widgets. But you confirmed that the emulator shows the login screen, so this is no needed anymore.

**Comment by Deviocom** [comment]
> Привет@Deviocom! Где вы смогли решить проблемы с переполнением?
> 
> Простой экран — это экран только с кнопкой без дополнительных действий или виджетов. Но вы подтвердили, что эмулятор показывает экран входа, так что это больше не нужно.

Greetings! Yes, that's right, the emulator shows the login screen. But it freezes after logging in. 

Have you managed to find out anything about this problem? to this day, I can't find the reason why this might be the case. I even asked in groups, but to no avail.

**Comment by Deviocom** [comment]
> Привет@Deviocom! Где вы сможете решить проблемы с затруднением?
> 
> Простой — это экран только с кнопкой, без дополнительных действий или виджетов. Но вы подтвердили, что эмулятор показывает экран входа, так что большего и не нужно.

Greetings! Yes, that's right, the emulator shows the login screen. But it freezes after logging in. 

Have you managed to find out anything about this problem? to this day, I can't find the reason why this might be the case. I even asked in groups, but to no avail.

**Comment by paulperez-dev** [comment]
Hi @Deviocom! It seems like all signs are pointing to overflow issues. Were you able to resolve them?

**Comment by Deviocom** [comment]
> Hi @Deviocom! It seems like all signs are pointing to overflow issues. Were you able to resolve them?

Hi! Unfortunately, no, I can't figure out what's the matter. Everything worked with exactly the same content before the error appeared. And I don't understand what kind of overflow we are talking about? Thanks!
