### ISSUE TITLE
Deploy cloud function issue

### ISSUE THREAD

**Issue by mynameisung** [FlutterFlow/flutterflow-issues#3715]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi
I got message 'Error: Unknown error. Please contact support@flutterflow.io.' from Cloud function.
please check my 'kakaoAuthCallback' of Cloud function.

i'd like to make cloud function that can handle kakao login api

### Expected Behavior

deployed

### Steps to Reproduce

1. it can't be deployed

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Please contact support@flutterflow.io.

### Visual documentation

<img width="371" alt="Snipaste_2024-08-31_01-08-39" src="https://github.com/user-attachments/assets/4f8de08a-1bb9-4c08-9fb9-5dd6b1c4b2c2">

### Environment

```markdown
- FlutterFlow version:newest
- Platform:newest
- Browser name and version:newest
- Operating system and version affected: newest
```

**Comment by Alezanello** [comment]
Hello!

To help us fully investigate whether this is a replicable bug, we kindly ask that you follow the proper steps for submitting a bug report. This will provide us with the necessary details to better assist you.

Please refer to the following link for guidance: [https://docs.flutterflow.io/misc/submit-bug-report/](https://docs.flutterflow.io/misc/submit-bug-report/)

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
