### ISSUE TITLE
Disappearing Field and Variable Values

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#3717]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Field values are disappearing, often while typing or after changing focus (to select the datatype, for example). The same thing is happening when attempting to set variable values - Flutterflow acts as if I didn't set them, even after selecting them.

I've attached a video for the first issue, I haven't recorded a video of the second issue yet. 

### Expected Behavior

Field names should stay when entered. Selected variables should remain when selected. 

### Steps to Reproduce

Attempt to add a new field to a database collection. Try to set a variable value that requires multiple steps to set. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

These issues aren't happening at every moment, but they are happening so often that development is miserable. This issue has come up before, but this is my first time reporting it.  This is probably the sixth or seventh time an issue has massively impacted my ability to develop with Flutterflow within the past 4 months. I've had projects delayed by weeks and months, and when they aren't delayed, it's a slog having to set variables again, input a field name again, make sure that something I saved actually saved. I'm sorry, I've been incredibly patient throughout the past several months of terrible bugs and slow support response times, but this is getting absolutely exhausting. 

### Visual documentation

https://github.com/user-attachments/assets/a2c21dee-8682-4b5a-928e-40aeacb03f76

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: Windows Desktop App
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### Additional Information

These issues aren't happening at every moment, but they are happening so often that development is miserable. This issue has come up before, but this is my first time reporting it.

This is probably the sixth or seventh time an issue has massively impacted my ability to develop with Flutterflow within the past 4 months. I've had multiple projects delayed by weeks, some over a month - and when they aren't delayed, it's a slog having to set variables again, input a field name again, make sure that something I saved actually saved. 

It feels like I have more days with problems than days where the software actually works properly. I'm sorry, I've been incredibly patient throughout the past several months of breaking bugs and slow support response times, but this is getting absolutely exhausting.

**Comment by Alezanello** [comment]
Hello!

I’m sorry you’re encountering this issue, but the good news is that it’s a known problem, and we already have an internal ticket to address it. Our team is actively working on delivering a fix as soon as possible!

Since this is a duplicate, I’ll close this issue to avoid dividing our efforts. Rest assured, I’ve linked your report to the internal ticket, so everything is connected.

Thank you for your understanding!
