### ISSUE TITLE
Test Mode broken with dependencies?

### ISSUE THREAD

**Issue by Saaamir** [FlutterFlow/flutterflow-issues#3718]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am stuck in the following Screen when starting Test mode and cannot test my App anymore:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c302cce3-0357-48c8-80de-dcb984d39599">

Although, Run Mode works. It is just the Test Mode that does not work. I get the following errors in the console:

![image](https://github.com/user-attachments/assets/ce30e0b6-d160-4da1-b8a5-0dcda2d79cb3)

Thsi started when I imported the following packages: xml2json and json2xml. Although I have tried to remove the dependencies and all the code related to it without sucess. Also reverting to an older version did not work.

### Expected Behavior

Test Mode should finish loading as usual.

### Steps to Reproduce

Not entirely sure. In another App it tells me that the imports are wrong and it works after removing.

1. Create an App
2. Create a custom action
3. Import dependencies related to XML

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48k/Lqx8pgodtY0LX1bfow9SksJn07U5E/08F9Y0w8J5zKB+wAYvf7P1FWTLyndwlcJU60pDoe/Pfqkdn1LfY5IQqcUaZ7yblqSQvjcFi6bLq0OrqrfW1fI8NUGWKD4cCrnglROtVfSHAN3UyqNfCsdBLvQ5DtPVUFH+W1KdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="539" alt="image" src="https://github.com/user-attachments/assets/97776f8d-3b32-4e77-aea2-ee0db555a608">

Text from that error message:

```
dart_sdk.js:56 Uncaught 
TypeError: Cannot read properties of undefined (reading 'Symbol(_privateNames)')
    at dart.privateName (dart_sdk.js:56:24)
    at load__packages__just_audio__just_audio_dart (just_audio.dart:37:1)
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at callGetModule (require.js:1203:63)
    at Object.completeLoad (require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (require.js:1717:29)
```

### Environment

```markdown
- FlutterFlow version: v4.1.85+
- Platform: Web
- Browser name and version: Google Chrome - 127.0.6533.120
- Operating system and version affected: MacOs Sonoma - Version 14.5 (23F79)
```

### Additional Information

I am willing to get any information needed to resolve this issue as it keeps me from testing my application.

**Comment by Saaamir** [comment]
Update: The error is caused by the "play sound" action since the latest update. It needs fixing

**Comment by AlexWrench** [comment]
Same issue, since yesterday evening, however fortunately can still use localrun to see my project in action.
![image](https://github.com/user-attachments/assets/10981223-4ebe-4c7c-8c29-85a3ffbae216)

**Comment by AndyWerder** [comment]
Exact same issue here - Test Run not working but deployment to iOS with XCode works flawlessly.

**Comment by jupiter80** [comment]
Same issue. Worked all day yesterday in online Test, local run, and online Run modes. Today works in local run, online Run mode, but never loads the first screen in online Test mode. 
- tried setting new first page
- tried changing pub spec dependencies
- tried other process of elimination. 
- the JavaScript debug has a 404 error now and there is a cache error. Happy to share

**Comment by Saaamir** [comment]
Fixed this by removing the "play sound" action.

Hope it helps you all aswell!

**Comment by Alezanello** [comment]
Hello everyone!

I've confirmed the issue, and I really appreciate the insight regarding the Play Sound action that's causing the error. I've already informed the team so they can investigate and resolve it. Thank you so much for your help!

**Comment by AndyWerder** [comment]
> Hello everyone!
> 
> I've confirmed the issue, and I really appreciate the insight regarding the Play Sound action that's causing the error. I've already informed the team so they can investigate and resolve it. Thank you so much for your help!

It looks like Test & Run is working again without the error - thanks FF team for fixing it!
