### ISSUE TITLE
"Is On-Screen Keyboard Visible" causes Error

### ISSUE THREAD

**Issue by alma-biz** [FlutterFlow/flutterflow-issues#3719]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi - I'm trying to adjust the content on my page to move up when the on-screen keyboard is displayed. To do so, I've tried adding the "Is On-Screen Keyboard Visible" property as a Visibility condition to a "filler" container, as well as a Padding condition, and in both circumstances, I'm receiving the included error.

The error appears when I try to reload my local run. I'm not sure if the issue is specific to the local run or if it's a broader error which only triggers an error message when I try to reload.

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/18bb4e4c-1990-421f-ae96-007c1be2281a">

### Expected Behavior

I should be able to use the "Is On-Screen Keyboard Visible" property without error.

### Steps to Reproduce

1. Have Local Run running, in my case it is an iPhone 15
2. Add a "filler" container beneath a text field. Make the container conditionally visible based on the boolean property "Is On-Screen Keyboard Visible".
3. Try to hot reload the project. Error appears.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkcjc35Z1m+Fc+KrQbMIxiSoQM0McWOdEl+tuZwgbIoznBu0MYc/BU1htONzjaVNfeE2ZuFMe/6HQkdrDCsEoAymdfa5myM11ERXOe2iVaa6xBaWKQ3EmHelRCBTC556G2h1vJrFqZXwi3EOyeeuUSinDIuu/Zwh9f6PHaOI=

### Visual documentation

<img width="781" alt="image" src="https://github.com/user-attachments/assets/13fdff25-a5fc-4e33-837c-42a2f1cc5c82">

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/2c2cc96f-5c5d-4091-a79d-dd12fe756af4">

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/25009190-9f88-4469-8926-42d88d36156b">

### Environment

```markdown
- FlutterFlow version: v4.1.83
- Platform: MacOS Desktop
- Browser name and version:
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by paulperez-dev** [comment]
Hi @alma-biz! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

**Comment by alma-biz** [comment]
Hi @paulperez-dev - Thanks for taking a look at this. I was able to resolve separately. Have a good weekend!
