### ISSUE TITLE
Custom Action Removes Return Value When Saved

### ISSUE THREAD

**Issue by groupsiteapp** [FlutterFlow/flutterflow-issues#372]
## Expected behavior (required)
You can add return values to custom actions. 

## Current behavior (required)
When you click save the return value goes away

## To Reproduce (required)
Create a custom action with a return value. Hit save, see the return value disappear. Seems to work with any datatype

### Bug Report Code (required, generate from Widget Tree)

**Not specific to this widget but included one anyways**
`IT4okcjfsM5PvsNA0LrtbcdohSQXNUwkbYEzjspBZzUYF5SuCLMqY8mnP1NpUsvhTVVIIGacp14K+amKvvP1NvI6aAqrbYBc+rVbEBXMRnGQMo/fU/HUACkbeacOQSj6`

## Context (required)

I cannot build my app because i rely on this custom action having an output value

## Screenshots / recordings

https://user-images.githubusercontent.com/99777437/213634376-20ed1726-fb8f-4da6-8180-499cf476932f.mov

## Your environment
Macbook pro, Google Chrome

**Comment by Pepino-GR** [comment]
Hi groupsiteapp,

I cannot reproduce your issue. Can you please show us the complete custom action?(Not only the Action settings)
