### ISSUE TITLE
Failed Step: Install pods / Mapbox

### ISSUE THREAD

**Issue by B4sti3n** [FlutterFlow/flutterflow-issues#3723]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying my FlutterFlow project to the Apple App Store via CodeMagic, I encounter a CocoaPods installation error specifically related to the MapboxCommon package. The error is an HTTP 401, indicating that the package could not be downloaded due to an authorization issue. My code, which is relatively simple, aims to display a Mapbox map with a few markers. 

The error prevents successful deployment to the App Store, despite the map rendering correctly in the web version of FlutterFlow. I am using the latest mapbox_maps_flutter plugin version 2.1. Below is a snippet of the error:

Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘

[!] Error installing MapboxCommon
[!] /usr/bin/curl -f -L -o /var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/d20240901-1899-m0
59sp/file.zip https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/24.2.0/MapboxCommon.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.2 cocoapods-downloader/2.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   179    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401

### Expected Behavior

The application should publish to the Apple App Store without errors, and the deployment process should complete successfully without encountering any issues related to CocoaPods or Mapbox dependencies.

### Steps to Reproduce

Go to Settings and Integrations.
Select Mobile Deployment.
Click on Deploy to App Store.
This sequence results in the described error.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkvHq05NOmNxE+ZD2cMIxjikwGUALa+dI0tZ+TQ0jF5D4PZl/dfekSFZWXeKzaHxcG038jkkd0vTuieDyG/YEHzuZb7Z5wbt+FhPPbGG6RZSVDMyoOX8lBZlbfRWx07TRkSYmPtFfSGAB716Qetm/Yz2Cf9qOYwx5e6fDbOY=

### Visual documentation

I have attached visual documentation, including screenshots and the full code, to provide further context for the error encountered.

[https://www.swisstransfer.com/d/d5f826f5-a84d-4881-917d-abeff8b3b6a9](url)

### Environment

```markdown
FlutterFlow Version: 4.1.85
Browser Name and Version: Google Chrome, Version 128.0.6613.85
Operating System: macOS Sonoma, Version 14.6.1
```

**Comment by paulperez-dev** [comment]
Hi @B4sti3n! So sorry you are facing this issue. Are you able to make an iOS build locally?

**Comment by B4sti3n** [comment]
Hi Paul, unfortunatly It always worked like that. Since 1 month stopped working with the deployment in Flutterflow... I am really stuck here because i do not want to deploy it outside FF. I did a really easy code in my Custom MapBox Widget so you can see what is causing that. Did you re-produce the bug ? Is that an update that FF has to be done with their packages ?

**Comment by B4sti3n** [comment]
@paulperez-dev  :)

**Comment by paulperez-dev** [comment]
Hi @B4sti3n,

The error seems to be related to an issue with your access token. Could you please review your configuration to ensure everything is set up correctly?

**Comment by B4sti3n** [comment]
Dear @paulperez-dev ,

The problem isn't related to the token itself, my token works perfectly. The issue lies in where the token is expected to be placed. The widget now requires the access token to be stored in the user's `«USER_HOME»/.gradle/gradle.properties` file, which is linked to the user's root directory.

I tested this on my side by downloading the code and placing the file in the correct root location on my computer (in the userhome directory with my username), and everything worked fine. So the core issue is that FlutterFlow doesn't seem to have a mechanism or directory structure to place the file in this required root location. This is why the widget can't retrieve the token from there when deploying to the Apple Store or Google Play.

It looks like this is something that needs to be addressed within FlutterFlow. The platform should provide a way to store the token in the correct directory, as the widget now relies on this setup for Mapbox to function correctly. Currently, FlutterFlow doesn't offer this solution, and that's why the Mapbox widget is failing.

Could you please patch this so that the token can be correctly placed, or provide an alternative solution? 

https://pub.dev/packages/mapbox_maps_flutter

**Comment by DanLika** [comment]
Hey, I have a similar issue with FlutterFlow and Mapbox. The same grey screen in run mode and on the web. 

![etyeteryeryeywer](https://github.com/user-attachments/assets/3d423e40-45f6-42e5-bbaa-bd21a0d3a8b1)
 
![dhdyerywrywr](https://github.com/user-attachments/assets/52ffb977-f457-43f7-8f00-13b0656e71e3)

**Comment by B4sti3n** [comment]
@paulperez-dev :)

**Comment by paulperez-dev** [comment]
Hi everyone,

I’ll review the latest messages closely and will respond as soon as possible. Thank you for your patience!

**Comment by B4sti3n** [comment]
@paulperez-dev Any news please ?

**Comment by paulperez-dev** [comment]
Hi Everyone,

Thank you for bringing this to our attention and for your patience! I’m moving this to the ENG team.

**Comment by B4sti3n** [comment]
it has been patch in the new update.

**Comment by paulperez-dev** [comment]
Hi @B4sti3n,

Thank you for confirming that this issue has been resolved. Since everything is now resolved, I’ll go ahead and close this issue.
