### ISSUE TITLE
Action icons appearing without any actual action on the Widgets

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3724]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Action icons appearing without any actual action on the Widgets

### Expected Behavior

Action icons shouldnt appear without any actual action on the Widgets

### Steps to Reproduce

please refer the attached video

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq2ItOodhE7rXyccd7/WYXC217beYescp/bxIgGIDzPOw+ZPXsbRBtXsviTWNMMUSmmkcF/9bTi9+eVMBfNk+cY4R7yLhqVAndeHyVe5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/6372c98a-7697-4284-8a93-e4f1e913dec6

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 27, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2

Project: letMeDraw
Project ID: let-me-draw-zo88ww
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I’ll check with the engineering team to see if this behavior is expected due to the recent updates in the Action Builder. As you mentioned, while there is no action set, the fact that an action trigger is selected on the widget suggests there should be an action configured.

**Comment by Alezanello** [comment]
Hello,

Thank you for your patience, and I apologize for the delayed response. The behavior you noticed was expected for some time, but we’ve now hidden it to prevent any confusion.
