### ISSUE TITLE
APK Build failed (minSdk cannot be smaller than version 23)

### ISSUE THREAD

**Issue by jseandr** [FlutterFlow/flutterflow-issues#3726]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Cannot download APK

### Expected Behavior

Can download APK

### Steps to Reproduce

1. Click Developer Menu
2. Click Download APK

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcr1sIhPseFF7oSJc/pahmA5JUh9R5IWmu1raDYvCIyqOph/dczRUBJtcNSrd1NhHFGgmkgE/vSKv9/XG8E5EE6aGYhgzqhfWzrjc3q8RLKqCs+eS3Z9L+NmGHasy5iNkQp7OsFtL2AB11OYBe++aHfUGZO/Zwh9f6PHaOI=

### Visual documentation

![apk build failed](https://github.com/user-attachments/assets/da9032f1-5235-4455-975f-344f988628e1)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

The app is working in both webapp and test mode. When tries to download APK, this error message shows.

**Comment by Alezanello** [comment]
Hello!

It looks like some packages in your project require a minimum Android SDK version of 23. You can easily update this by going to the "Platform" menu in your settings, navigating to "Advanced Android Settings," and setting the Minimum SDK Version to 23. After making this change, try downloading the APK again!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/17f73613-a479-479f-9fb5-faeda55d62e3/825134f4-f5cd-4e6b-9b34-6e8329118801?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xN2Y3MzYxMy1hNDc5LTQ3OWYtOWZiNS1mYWVkYTU1ZDYyZTMvODI1MTM0ZjQtZjVjZC00ZTZiLTliMzQtNmU4MzI5MTE4ODAxIiwiaWF0IjoxNzI1Mjg1OTQ4LCJleHAiOjMzMjk1ODQ1OTQ4fQ.-cwaXg9WQddHr4EzGl4OttzLAYdG7rR5pRELVbpARgs " alt="image.png" width="968" height="819" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
