### ISSUE TITLE
ListTile Widget Content 0 Padding Assumed as Null

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#373]
When using a ListTile widget in a ListView and setting the left and right padding to 0, it behaves correctly in the editor but comes up with an arbitrary padding in the run view.

If on the other hand the padding is set to 1, it appears as expected in the run view. 

This leads me to assume that when values are set to 0 they are beign interpreted as null and the flutter widget is then displaying based on its defaults. But I could be wrong.

This also happens with the SwitchListTile widget. 

Also I've seen such behaviours with other widgets that I can't recall right now which lets me believe it's a general issue with the way the flutterflow code interprets 0 properties in widgets in the editor.

## Expected behavior (required)
WHen 0 content padding is set there should be no padding.

## Current behavior (required)
When 0 content padding is set an arbitrary amount of padding is shown.

## To Reproduce (required)

1. In a page create a List Tile widget containing a few ListTiles.
2. Run the app. You will see some padding. That's ok.
3. Set the content padding to 0, you will see the same padding as before. That's the issue.
4. Set the padding to 1, you will see that reflected. No issue here.

## Your environment

Latest flutterflow as of today on app or web.

**Comment by wenkaifan0720** [comment]
Hi @davhad. You are absolutely right. This is a bug on our end. We try to minimize the generated code and thought the default content padding is zero (which is not true for `ListTile` and `SwitchListTile`). I believe we have fixed some of them in the past and will continue to investigate into this matter. Thank you for raising this issue!
