### ISSUE TITLE
Error on filter map document firebase

### ISSUE THREAD

**Issue by MendesCorporation** [FlutterFlow/flutterflow-issues#3730]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When filtering a map to return data, an error occurs:

ib/discovery_v2/scouts/meus_scouts_helio/meus_scouts_helio_widget.dart:718:67: Error: The getter 'tipoAcao' isn't defined for the class 'GameSetsRecord'.
 - 'GameSetsRecord' is from 'package:my_performance/backend/schema/game_sets_record.dart' ('lib/backend/schema/game_sets_record.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'tipoAcao'.
                                                                e.tipoAcao ==
                                                                  ^^^^^^^^

### Expected Behavior

data filter with success

### Steps to Reproduce

1.Create a collection in firebase
2.put a field as datatype
3.create a text
4.put the text value as a firebase map filter

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sl8j6yItIm+FY7s/ubMB7/WARKVg5argRiu1qEA4gGJ+tBKQXXOnAVE5pQte0Y1VMMVqahTge+vPemvLhVPpdC0+aGqZI/rVUSjyXRkWWWpeYDYeeS25/DZlYIXbD56SVsx5CKspsS15m2F+YNu7JZBPrHpjYDUQzHP6LA5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/cc1a1066-2339-447e-ad14-f29074c802a0)
![image](https://github.com/user-attachments/assets/59329bfd-1647-4905-a8ef-b287ff9f3797)
![image](https://github.com/user-attachments/assets/824b2974-8c9d-4b81-96cc-a1e94e7beafb)
![image](https://github.com/user-attachments/assets/f6efaeb2-d32f-44b6-a923-c333127075e1)

### Environment

```markdown
- FlutterFlow version: v4.1.85+
- Platform:Web and Desktop
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @MendesCorporation! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

Based on the error shown in the capture, the code is looking for the `tipoAcao` in this scheme.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dc9a1168-4ced-4bd2-92fb-21ebab77ec40/37845438-b327-4966-ba06-d17d266ec22f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYzlhMTE2OC00Y2VkLTRiZDItOTJmYi0yMWViYWI3N2VjNDAvMzc4NDU0MzgtYjMyNy00OTY2LWJhMDYtZDE3ZDI2NmVjMjJmIiwiaWF0IjoxNzI1MzYxNzI5LCJleHAiOjMzMjk1OTIxNzI5fQ.y1QgQ5LKlvRzbBhWfzsTpRGif58_ZGwLempqX4a_PN4 " alt="image.png" width="714" height="356" />

**Comment by MendesCorporation** [comment]
For some reason today the map option no longer appears as it did yesterday.

yesterday:

![image](https://github.com/user-attachments/assets/be6f6c2c-25b4-4e20-b072-ecb1469a1017)

Today:

![image](https://github.com/user-attachments/assets/93a1f337-a95c-4a10-badb-5da6b3046ad9)


The error no longer occurs

**Comment by paulperez-dev** [comment]
Hi @MendesCorporation! Do you mean I can close this issue?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
