### ISSUE TITLE
USer location doesn't show on Android in Google Maps

### ISSUE THREAD

**Issue by alexandremartens** [FlutterFlow/flutterflow-issues#3733]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When loading a Google Map with a marker and selecting ‘Show User Location’ in the Google Map Widget of our application (FF), the current user location (indicated by a blue circle) is displayed correctly on iOS devices. However, on Android devices, the user’s current location is not shown. Even when enabling the ‘Show Map Toolbar’ option, the issue persists on Android.

### Expected Behavior

The user’s current location (blue circle) should be visible on the map for both iOS and Android devices when the ‘Show User Location’ option is enabled in the Google Map Widget. Only IOS works, not Android. This has been tested in the android play store tracks too.

### Steps to Reproduce

1.	Create a new page in the application.
	2.	Add a Google Map widget to the page.
	3.	Enable the ‘Show User Location’ option in the widget settings.
	4.	Optionally, enable the ‘Show Map Toolbar’ option in the widget settings.
	5.	Deploy or preview the application.
	6.	Access the page on an iOS device and observe that the user’s current location is displayed as a blue circle on the map.
	7.	Access the same page on an Android device and observe that the user’s current location is not displayed on the map.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CzPLlvJR2ofVA1pDbbfpshmEvQ24jRYIz19VtewwbJ5PNDOx/efekfk5YXcOldghmPmGZrH40+eyNm9z1N/BeFwSrRo9xzroJbxWUWnitaLa7EqjoPHJUGshVGFyk1quvhBJAFO1qcnwuwDmQIu/JZB/rH77KDGonPv+IENjXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

![WhatsApp Image 2024-09-03 at 14 18 11](https://github.com/user-attachments/assets/a04c91b0-c949-4b12-9afa-bf1972ddead2)
i was standing 100m from the marker. 
![image](https://github.com/user-attachments/assets/d57d56d1-eaa5-4ce1-ac6d-04fa50dccee5)

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: macos desktop
- Browser name and version: NaN
- Operating system and version affected: 14.6.1 (23G93) sonama
```

### Additional Information

IMPORTANT: For stripe paywall, it is in test mode, use: 4242 4242 4242 4242 as card number and 01/30 for expiration date and 123 as ccv

**Comment by paulperez-dev** [comment]
Hi @alexandremartens!

I ran your app locally on Android, but I couldn't access the page you shared due to a paywall. Could you please try reproducing the issue in a blank project and share the bug report code? This will help us better identify and resolve the issue.

Thank you for your help!

**Comment by alexandremartens** [comment]
> Hi @alexandremartens!
> 
> I ran your app locally on Android, but I couldn't access the page you shared due to a paywall. Could you please try reproducing the issue in a blank project and share the bug report code? This will help us better identify and resolve the issue.
> 
> Thank you for your help!

For the stripe paywall, it is in test mode, use: 4242 4242 4242 4242 as card number and 01/30 for expiration date and 123 as ccv

**Comment by paulperez-dev** [comment]
Hi @alexandremartens,

For the option to work correctly, the initial location must be set from the device's location. Please refer to this section of the documentation for more details:

[https://docs.flutterflow.io/integrations/google-maps/google-maps-widget#show-user-location](https://docs.flutterflow.io/integrations/google-maps/google-maps-widget#show-user-location)

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
