### ISSUE TITLE
"Search For Widget" text not getting clear

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3735]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

text we type to search for widgets (as shown in the attached video) is not getting cleared by Backspace and Delete button. Only, clear (x) icon works

### Expected Behavior

text should clear with keys

### Steps to Reproduce

please refer attached video

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq2ItOodhE7rXyccd7/WYXC217beYescp/bxIgGIDzPOw+ZPXsbRBtXsviTWNMMUSmmkcF/9bTi9+eVMBfNk+cY4R7yLhqVAndeHyVe5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/312fc1f8-15a5-4573-a3ff-826384d1c4ea

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 27, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2

Project: letMeDraw
Project ID: let-me-draw-zo88ww
```

**Comment by Alezanello** [comment]
Hello!

Thanks for reaching out! I tried replicating the issue, but I wasn't able to—I was able to delete and use backspace after typing the widget name without any problems. I tested it on both the Web and Desktop App.

Let me know if there’s anything else you’d like me to check!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2147bf4c-16ad-4602-a13e-f6bd26202de2/89e1561a-09ec-4fbb-90b1-bd5466093330?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMTQ3YmY0Yy0xNmFkLTQ2MDItYTEzZS1mNmJkMjYyMDJkZTIvODllMTU2MWEtMDllYy00ZmJiLTkwYjEtYmQ1NDY2MDkzMzMwIiwiaWF0IjoxNzI1NDUwMTUzLCJleHAiOjMzMjk2MDEwMTUzfQ.lqSGf9wGSSEefjSvleWeEL3JuMscCmNmWmft8Ijy5z0 " alt="backspace.gif" width="1606" height="714" />

**Comment by coach1990** [comment]
i dont know whats and where is wrong, my delete key and backspace works fine everywhere, but not in search widgets. am i missing any settings?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by coach1990** [comment]
@Alezanello late response is all okay.
yes please its still there. but its no big deal, i can manage without it. you may close this issue, thanks for help.
