### ISSUE TITLE
Publishing stuck

### ISSUE THREAD

**Issue by Sudarshan519** [FlutterFlow/flutterflow-issues#3739]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Publishing not working on my project

### Expected Behavior

#Publishing not working on my project
![Screenshot 2024-09-04 at 17 08 51](https://github.com/user-attachments/assets/7b68c863-c4f8-4fe4-a37f-6c4dda4e744f)
 
![Screenshot 2024-09-04 at 17 08 51](https://github.com/user-attachments/assets/171b5dd2-78e2-4bde-ae67-0843a64f065a

### Steps to Reproduce

Click on publish button 

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8kivHq6ot1mMdY1pDqacFvryQXQ1M7auc7kdVxbAwgHOvuEooQf8nsZRJoYsyBfwk3PGeJjnsy+c7GhIflV+4rHxeVQaJl3JVqZguXXkGRR5isC5a0QXBQHf1VC2aGyKSr3xN8A+FuL0Y4w2aMA+nLcALbNbX4PWsvHvGhMpvJjHzjLSXVLjpF5zEXEx7eTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

![Screenshot 2024-09-04 at 17 08 51](https://github.com/user-attachments/assets/16e0e8db-4b70-46c6-b025-ae51426ccce0)

### Environment

```markdown
- FlutterFlow version: Tried from os and web
- Platform: Web
- Browser name and version: All
- Operating system and version affected: All
```

### Additional Information

Issue on publishing

**Comment by Alezanello** [comment]
Hi there! <br>To help us thoroughly investigate whether this is a replicable bug, could you please follow the proper steps for submitting a bug report? <br><br>This will give us all the details we need to assist you more effectively. <br><br>You can find the guidelines here: [https://docs.flutterflow.io/misc/submit-bug-report/](https://docs.flutterflow.io/misc/submit-bug-report/) <br><br>Thanks for your help!

**Comment by Sudarshan519** [comment]
Publishing is not workibg on my project

**Comment by Sudarshan519** [comment]
And latest message comes as publishing

**Comment by Alezanello** [comment]
I understand your frustration, but it seems the ticket was opened without providing the bug report code, which is essential for us to investigate your project. That’s why, in my initial response, I requested the necessary information to help us look into the issue more thoroughly.

**Comment by Sudarshan519** [comment]
I have included bug report code

**Comment by Sudarshan519** [comment]
Can it be because of uploaded assets.How can i debug  this.where issue come
from.It is woking on debug and run

**Comment by Alezanello** [comment]
I don't believe the issue is related to the assets, as I tested your project and it compiles correctly. <br><br>Could you try removing the Web platform from your project and then adding it back? <br><br>After that, please try publishing it again to see if the issue is resolved.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0e40bb3c-37d2-4a9c-8721-35115903c096/3cde1c00-2c44-431a-bbda-70b39267d0ca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZTQwYmIzYy0zN2QyLTRhOWMtODcyMS0zNTExNTkwM2MwOTYvM2NkZTFjMDAtMmM0NC00MzFhLWJiZGEtNzBiMzkyNjdkMGNhIiwiaWF0IjoxNzI1NDUzNDI2LCJleHAiOjMzMjk2MDEzNDI2fQ.2iF7r1CjcOq1oCyOD0dBRZy5K5labSV_JEPcIneXdjw " alt="image.png" width="658" height="428" />

**Comment by Sudarshan519** [comment]
Ok let me try

**Comment by Sudarshan519** [comment]
It didnt work

**Comment by Alezanello** [comment]
I'm very sorry this solution didn't work. Unfortunately, I don't have the right tools to assist with this particular issue, as the GitHub Issue Tracker is intended for issues that can be replicated in a new blank project. For project-specific cases like this, please reach out to our support team via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io). They have the appropriate tools to help resolve this issue for you!

**Comment by Sudarshan519** [comment]
Thank you for your response.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
