### ISSUE TITLE
Removed page state keeps coming back even after deleted

### ISSUE THREAD

**Issue by Jeffcyw** [FlutterFlow/flutterflow-issues#3740]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a callback function that updates my page state, after that I updated the page state type and now when I remove the page state field, it just keeps coming back no matter what, can never be deleted. (See image, I've tried removing this a lot of times and no matter what it just keeps coming back after a few minute)
![image](https://github.com/user-attachments/assets/d015aeb3-75f8-45a4-a68e-ac87ab568a1d)

### Expected Behavior

Field removed and not coming back by itself again

### Steps to Reproduce

Remove the field and wait, it will come back again

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPQvj7PxFUcNfjTH9qIWL8knwX/MqKhtnfLsICAySdGb5CzbVQYRfzeDqjRpClPYS3b0d5EflVIFSs0MCnkwlCPuhsR11n3U73DfCvFxLDN72xNUcdNea4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/d8ff3b90-d23d-4ec2-a24b-5ccc63f3a646)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @Jeffcyw,

I attempted to replicate the issue you're experiencing, but I wasn’t able to reproduce it on my end—both in my existing projects and in blank ones.

I did notice there are a few errors in your project, which may be affecting the behavior and possibly causing certain actions to roll back.

Would you be able to create a quick blank project and check if the issue persists there? This will help us isolate the problem and ensure we can properly troubleshoot it.

Thanks for your help, and we’re eager to get this sorted out for you!
