### ISSUE TITLE
Disconnection of firebase database

### ISSUE THREAD

**Issue by LaVanguard** [FlutterFlow/flutterflow-issues#3744]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow gives initially error the firebase project is disconnected.
But after a second removes this error.
Flutterflow project and firebase connection were working before and nothing was changed.
When trying to regenerate config files - information that the firebase project doesn't exist.

### Expected Behavior

Firebase connection working like it should.
Ability to sync new changes with the firebase.

### Steps to Reproduce

1. Go to the project.
2. Try to connect to regenerate config file.
3. Look that there is a connection and setup is complete (above)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk876y4x1oeFF+Kr+acBr/SoXJm4+ap0SscpCbw4bIYj2P4lzY876PhdtUsOrY2NUMGe2p14EpfTpv9/LIcArAweeGYBE1qVcZhaVZD6jbqmTF7maYXZfBdpWCGKE57WRhiJQPvRqSFIB7Ez3P++RbHTbO5jLIkQ8Sq/LZO4=

### Visual documentation

![Report issue](https://github.com/user-attachments/assets/804c60d0-5ece-4b39-8ad7-54d7f286c778)
![image](https://github.com/user-attachments/assets/3f7388b9-eaf3-48f6-b195-5c3d0524144e)
![image](https://github.com/user-attachments/assets/c5b4c051-ee17-4ade-9c42-4f8e9e51508e)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 4, 2024 Flutter version is 3.22.2
- Platform:Web PC Windows and Desktop App
- Browser name and version: Chrome Version 128.0.6613.114 (Official) (64-bit)
- Operating system and version affected: Windows 11 Pro 23H2
```

**Comment by pstatile** [comment]
Same here!

**Comment by pstatile** [comment]
<img width="1682" alt="image" src="https://github.com/user-attachments/assets/ae761135-deef-417a-9ecb-c501dfd1dd86">

Happened since v. 4.1.86+

**Comment by LaVanguard** [comment]
You got a good solution for that? What has helped in the past apart from what I did?

**Comment by fabricenana** [comment]
I have the same problem, but it gives me an error message: Project uses Firebase Auth (+3 other Firebase features) but Firebase config files are not uploaded.
![bug](https://github.com/user-attachments/assets/6677aa90-38ea-4dcd-b6e9-dfdbf0989c27)

**Comment by uelkuesara** [comment]
Hi Same here, tried also setting up firebase again, I have 46 errors...
<img width="1433" alt="Bildschirmfoto 2024-09-04 um 19 50 23" src="https://github.com/user-attachments/assets/0bcf6265-ad94-49f7-8f00-e2474032cd4b">

**Comment by lukaspivarnik** [comment]
Hi, I am unable to access Manage Content as it says the Firebase project is not configured. Yesterday, everything worked as it should. There were no changes made to the projet and I have 0 errors.

<img width="1206" alt="Screenshot 2024-09-04 at 20 23 43" src="https://github.com/user-attachments/assets/8d76a5e0-9dbd-4ebd-9db8-c4fb2be5ee32">

**Comment by rafael-drinx** [comment]
Problems here too.
<img width="1436" alt="Screenshot 2024-09-04 at 4 05 40 PM" src="https://github.com/user-attachments/assets/d87e11c1-29fd-4487-8e02-9d105ff081ba">

**Comment by rzambroni** [comment]
Hi everyone,

Apologies for the inconvenience! The issue has been forwarded to the engineering team for review. We’ll keep you updated here as soon as we have any new information.

Thank you for your patience!

**Comment by agreaves** [comment]
Hey folks, we've identified the main issue here and I believe have fixed the root cause. However, there may be some outstanding issues so want to keep this open.

In particular, @rafael-drinx and @uelkuesara could you confirm whether you still see the Firebase configuration errors and if so please add a Bug Report Code?

And @lukaspivarnik are you on the most recent version of FlutterFlow on the web (and desktop)?

Thanks! We'll continue to monitor this issue closely.

**Comment by rafael-drinx** [comment]
@agreaves It's working. Thank you!

**Comment by fabricenana** [comment]
> Hi everyone,
> 
> Apologies for the inconvenience! The issue has been forwarded to the engineering team for review. We’ll keep you updated here as soon as we have any new information.
> 
> Thank you for your patience!

Yes, it's true that there are excuses, but I've lost a large part of the work I've already done, and I've been forced to start again, even though my customer was expecting delivery today.

**Comment by lukaspivarnik** [comment]
@agreaves Yes, I am on the most recent version, but it still does not work.

**Comment by rafael-drinx** [comment]
On CMS running still does not work. Sending here FYI:

<img width="1440" alt="Screenshot 2024-09-04 at 7 04 29 PM" src="https://github.com/user-attachments/assets/6c097380-bd8a-4072-8ceb-8c2a8bbc00fc">

**Comment by fabricenana** [comment]
And it's starting again for me. In my opinion, it's since I updated to the latest version that this bug started
![bug](https://github.com/user-attachments/assets/a11f3ca6-1f37-4456-b217-4e0968b32f62)

**Comment by agreaves** [comment]
@lukaspivarnik @rafael-drinx could you please add a Bug Report Code to help me debug (right click anywhere on the widget tree)? It provides all the necessary info.

@fabricenana this issue looks different, could you describe what you're facing? And what work did you lose?

Apologies again for the issues folks.

**Comment by fabricenana** [comment]
I have a problem with my firebase requests.
In Test mode, sometimes the data is displayed, sometimes it isn't, and this has been the case since the latest version was updated.
I also have a collection that is no longer in sync with firebase.

**Comment by lukaspivarnik** [comment]
@agreaves Here is the bug report code: IT4kksn15ZVNj7wA7qr1bcJar2EUKWF7TL07ttYbZxUjIuPtBJh/dcmkMhZWOM/hYFNhHGCipD8H06GNhYflL8E7B02tb7pk+KhIVwuVJHq8Soy2CbuCdXNCM5hPIFynyqurohBCIs1Zc0YF6lyme96tUiraCZ+/Zwh9f6PHaOI=

**Comment by alanbrff** [comment]
Same error here since last FF update. Manage Content says the Firebase project is not configured

**Comment by fabricenana** [comment]
@agreaves Thanks for fixing this problem, now even the user can't connect to the application.
Looks like the bug is spreading.
Entire pages no longer displayed 
Hours of work lost

**Comment by uelkuesara** [comment]
Hi @agreaves, still not working: here is my Bug Report Code: IT4gi87huM9Pm8tA1pDuYO9VmigQH2YlbJc0sNobbxAjIoDoPJkUac/OXFFVONziTGNbKEWJnkwe+vzViYbDJu4DAwSaUaZj+c9UVwrzf3y/aoSzC7m0SGpQEfpTGHK10J+JnRInKsBuSiEH3UOqe9mAZDXDJOL7Zwh9f6PHaOI=

**Comment by rafael-drinx** [comment]
@agreaves 

My Bug Report Code:
IT4wlMjf5YpJtbwA7qX2KflR/Cc4IjsgRK8rj+t+Ris9f5CvOpYUec/6PxdCZ7XhYAhUJWKmp14H3NaNktj9KO0VHy2uGYhmzpBQSgHzf3G6aZeTF7WaTkRAAtJbI0/G0cGrvhB+IsxuSCQu3EOAHdmtH3LDK5eyDWowSq/LZO4=

We're also having a lot of trouble with Cron Cloud Functions sending push notifications. It's not a problem with FlutterFlow. It seems the Firebase team is dropping the ball in several areas, unfortunately. The community is really unhappy with them.

**Comment by agreaves** [comment]
Hi @uelkuesara, in your case it looks like you toggled off the Users collection, that's why you see so many errors. To fix just turn this back on! It's in the Firestore settings page.
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/cbde60f5-dfd9-4da8-854b-099f5f58fd74">

It does look like your config files went missing too, which looks like a FlutterFlow error. Can you try regenerating these files?

**Comment by agreaves** [comment]
@lukaspivarnik @uelkuesara looks like this is a rare issue where the project didn't auto update and you happened to not make any edits (which is the other thing that triggers an update).

We'll roll out a fix to make sure this doesn't happen in the future, but in the meantime, you should make sure you're on the latest version of FlutterFlow, and then make even a single edit to the project. After that, CMS should work just fine.

If not, please let me know and I can take another look. I'll leave this issue open until then.

**Comment by lukaspivarnik** [comment]
@agreaves That resolved the issue for me. Thank you.

**Comment by alanbrff** [comment]
> @lukaspivarnik @uelkuesara looks like this is a rare issue where the project didn't auto update and you happened to not make any edits (which is the other thing that triggers an update).
> 
> We'll roll out a fix to make sure this doesn't happen in the future, but in the meantime, you should make sure you're on the latest version of FlutterFlow, and then make even a single edit to the project. After that, CMS should work just fine.
> 
> If not, please let me know and I can take another look. I'll leave this issue open until then.

@agreaves Can you help my project please? Still getting the message: firebase project not configured

**Comment by agreaves** [comment]
@alanbrff sure, can you add your Bug Report Code? And have you tried any of the above steps to possibly fix?

**Comment by alanbrff** [comment]
> @alanbrff sure, can you add your Bug Report Code? And have you tried any of the above steps to possibly fix?

A single edit on the project just solved the problem. Thanks!

**Comment by LaVanguard** [comment]
Wanted to thanks for support as it helped me. Keeping fingers crossed for everybody else to get the same result.

**Comment by uelkuesara** [comment]
Hi @agreaves Thank you for fixing, it all works now! You said my configuration files went missing, but I dont have an error or anything shown, how did you see that they were removed?

**Comment by BaseD-75** [comment]
After two weeks without changes to my two projects on FF, today I cannot run my projects anymore (they worked just fine two weeks ago). I'm getting this error: Project uses Firestore (+1 other Firebase features) but Firebase config files are not uploaded.

The strange thing is that I don't even need Firebase (switched to Supabase). I tried to remove everything and also to reconnect everything. Also made some minor changes which was recommended in this thread. Nothing removes te error. 

Bug reportcode:
IT4WjMrl05NgocsA1aqBbO9agmEWNkwmUI0zjsN+EUwbIuqrEIwPXfikSEpWZ9+kTHxcL06Wjjkd+trXkt7AA+UqHz6VbJRj+bpUEzuVLXKuRravO7isVn9RBdpJJVyD37ezmiR4CNJpdFoc1GCqGe7KHnbAJoy3DUgWD+SIGNn/gXOqQ0SLb3kNh1JWeC/v

Please advice.

EDIT (after 3 hours): I don't know who did what, but my error is resolved. Thanks! I think :-)

**Comment by fernandofmn** [comment]
I'm having the same problem. Here the bug code. I need support ASAP :(, my app broken.
@agreaves  Could you help me?

IT4el8j6yItNobxG7ZSJbsBv9ScWHGYjbZI7m+5+GQwjIZj3OpoEduj+QHZVOMO/dFY3OlmI8Xgx0+DMvvOfG+4XPiiqQaJlzah2ZTvifGOiMM2XCLm0SHYmI/xgGnWHzbSw2Qp7LvFoW1otw2eyIeiXUj/dQbrBDkU/GOSLDNnJj3y9HhzKXn0Jg1ZSfCvr

**Comment by fernandofmn** [comment]
Hi guys!!!

Is there any way I can set up Firebase manually? Or can you do it for me?
I have an app in production and I need to update it. I can't run the application, I need it urgently, please help me.

**Comment by fabsi88** [comment]
Same here... suddenly stopped to work with Firebase. No chance to remove and readd the project.
ITEel/GAsIZ1pbxI1rn6auxVmQMwJ0QlUIInj+0bWRMhNYDyEIoHO8/CTBJLYtSldFZEHk2apEIJzNqKhuzhOsYENSuCGbZy1pRXQQ/gXlu7R7a2OpDhPXYmN5tTG0uO17SRghR+GM5hSVYi71OUO/CrG3qCf9qOYwx5e6fDbOY=

Btw: Updated a lot in my project on the latest version but this is not fixing it.
Cannot remove the FB project / reconnect

**Comment by fernandofmn** [comment]
Hi everyone, how are you?

I really need your help. I planned, I made an investment to participate in an event, I'm changing my app for this event and right now I can't even test the changes, much less publish them.

I really need your help so that I can move forward and not lose this investment. The event is on Friday and I still need to code a lot of things, but I can't move forward.

@agreaves @rzambroni @wenkaifan0720 @FlutterFlowEng

**Comment by wenkaifan0720** [comment]
Hi @fernandofmn. Sorry for the trouble. We just released a new version that should fix this issue. Could you try to connect again?

**Comment by fabsi88** [comment]
fixed with new release. THANK YOU!!!

**Comment by fernandofmn** [comment]
It works, thanks guys, thanks a lot!!!

**Comment by KittipochSae** [comment]
It works perfectly on the new update. Thank you so much.
