### ISSUE TITLE
"Set Form Field" action stopped working

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3750]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't select a field in set form field if it is inside a child component.

### Expected Behavior

Well, it was working. Just want to set the value of a field inside a component. It is a very basic function.

Almost all of my projects are down with errors, and i cant work on them because of this issue.
I hope I don't have to redevelop what I've already done. 

### Steps to Reproduce

1. create a text field in a component
2. use the component in a page, then use set form field

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfHq25JOxcdE7qXyYMExhSQUHFt7aOcwlcpOGDsdF4iuPOxzaeLCU1VBQtO5YHx5KEWInjoD3M7suIbXN/BfNgWCR5xA1ZNiEwrLVlG/aouVDpOoWnclBcFgGh2E0cCO3SMmLuh0Wngd12GYGdnJbDfrN5/4Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/1510d251-6f36-4cf6-a150-55c83c0ed1df)

### Environment

```markdown
- FlutterFlow version: 4.1.86
- Platform: Web
- Browser name and version: Google Chrome 128.0.6613.114 
- Operating system and version affected: Win 11
```

### Additional Information

Yesterday everything was ok, today those errors appears.

**Comment by ALaiFF** [comment]
The same issue was encountered right after the most recent update...

**Comment by rzambroni** [comment]
Hello @nev-21,

Thank you for the report. I will mark this ticket as a duplicate of a [previous report](https://github.com/FlutterFlow/flutterflow-issues/issues/3748) that is currently under analysis.

Feel free to follow up on the progress there.

Best regards,

**Comment by MahamadKanabi** [comment]
We're really dependent on this functionality, and the issue is preventing us from moving forward. It's quite surprising that such a significant problem was introduced, especially considering how vital form actions are to most apps.

**Comment by brrrrsimplydev** [comment]
Getting the same issue after the 4.1.86 update. We cant proceed with the development without this being fixed. I tried all the workarounds I could possibly think but no luck.

**Comment by flutterdevcodiste** [comment]
The same issue occurred right after updating to the latest FlutterFlow version. With 1.5 million users, it's crucial to ensure every release is stable. A single issue from your end is causing delays for many, including my work.
