### ISSUE TITLE
Cannot close a branch

### ISSUE THREAD

**Issue by sivertigo** [FlutterFlow/flutterflow-issues#3751]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Before the update, we were able to select "close branch" from the branch icon, but now, selecting it doesn't trigger any action.

<img width="499" alt="スクリーンショット 2024-09-05 17 12 06" src="https://github.com/user-attachments/assets/6072e01d-bf7f-421b-917b-73c270094131">

### Expected Behavior

The expected behavior is that after selecting "close branch," the corresponding branch would be deleted and the transition would move to the main branch.

### Steps to Reproduce

1. Create a branch
2. Select Branch Icon (Above the panel)
3. Select the Branch Icon (located to the left of the current branch name)
4. Select "Close [branch name]"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43iMjk4bpisN9c7pPtK8ZajiMUJ2IMX+U3i91BaCgofePtOol3evWkYRBoYMe7TGxpMESmmkEBwcqNuNjtO/ACIRGtRoc/zql6ZRWXUmKme5OBEqjgdXx9J5lWFWK55JjQhRV4AONhWmAlwGeEDOivbAPAQJOwIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/2260ad61-fdaf-4c61-8e03-bf08c71c1bec

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform:Web
- Browser name and version: Google Chrome (127.0.6533.120)
- Operating system and version affected: MacOS
```

**Comment by rzambroni** [comment]
Hi @sivertigo,

We’re closing this issue as it aligns with a [previous report](https://github.com/FlutterFlow/flutterflow-issues/issues/3745) that the team has already addressed. The fix is in progress and should be released soon.

Thank you for taking the time to report this!
