### ISSUE TITLE
Positions of conditions in Conditional Builder revert after moving

### ISSUE THREAD

**Issue by TeferiHero** [FlutterFlow/flutterflow-issues#3754]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I move conditions in "Conditional Builder" to change their evaluation order, they revert back to how they originally were - sometimes spontaneously, and always after closing and reopening the project. Saving the project doesn't seem to affect this behaviour.

### Expected Behavior

I expect the conditions not to revert after changing their positions.

### Steps to Reproduce

1. Create a new project
2. Create a Conditional builder.
3. Add a condition ('else if') to the conditional builder
4. Give different conditions to the 'if' and 'else if' (putting widgets inside is optional)
5. Switch their positions around by dragging and dropping in the Conditional Builder properties (NOT in the widget tree).
6. Close the project and reopen it.
7. See the conditions are back in their original places

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8glcmAvJRNrt9A1s+NccFB/TkRJmY8U5Irm8NxcxQafIvqE7d2O/ekSE5BZ9SBaQtAP2Gjmns00/TJvtnhEfIBBw2tbL5n+JEAWznvVmGQWp+bPpW3WUdRBd9YBXXE0rWvvxZBIuN1LXg4wGeIH/O8RTbGO5TNPlcNB/+lDLr4pXiGKx22OSFWsgYPR22TPawmRDiNuMP9xN9U3ezrxw==

### Visual documentation

![image](https://github.com/user-attachments/assets/8d2d4354-9ed4-4702-b956-e1fd6aeb2da9)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 4, 2024
- Platform:
- Browser name and version: Version 128.0.2739.63 (Official build) (64-bit)
- Operating system and version affected:
```

### Additional Information

Moving the 'if', 'else if' conditions in the widget tree seems to work fine. I'll use this as a workaround

**Comment by paulperez-dev** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this! 

Thanks for you report!
