### ISSUE TITLE
Can't create a Firebase application from FlutterFlow Desktop (Windows)

### ISSUE THREAD

**Issue by L0rdS474n** [FlutterFlow/flutterflow-issues#3756]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Tried many times, when I try to create a Firebase project through FlutterFlow Desktop it just shows me a white square, if closed FlutterFlow will force quit.
![image](https://github.com/user-attachments/assets/1654a96e-a46a-43f4-8b62-9d25717ce8d5)

### Expected Behavior

As for the web version I expect it to Login with google and create that Firebase as normal

### Steps to Reproduce

1. Create a new project
2. Go though setup and enable Firebase
3. Try to create a Firebase within FlutterFlow Desktop
4. Enjoy the white screen of death.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gruoB16X2ccJAhQAkQzM8bYJMl9caTUo3B5SuPbQHPer+VEhtT8+IS3xAJlCIinwd7tLpiPLDGvFeHyeueINozJANbgvycF2uM66yPbuaYGhAMNxMGHKl0YmzsQpSHM1eSGAtw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

Not more than the one in current behaviour

### Environment

```markdown
Latest FluttreFlow Desktop
Windows 11
Windows Bitdefender running (can't shut this down)
```

### Additional Information

I'm not going to pay until I can work as I want to work.

**Comment by rzambroni** [comment]
Hello @port513, thanks for the report, the issue you are describing is a known issue on desktop versions, it is already on the team's backlog to be fixed.

As a workaround you can use the[ web-app](https://app.flutterflow.io/) to create the project and continue later on the desktop version if you want.

Marking this ticket as a duplicate in favor of the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/2935).

Thanks.
