### ISSUE TITLE
Custom component parameters are not saved in page action blocks.

### ISSUE THREAD

**Issue by syg-eliseu** [FlutterFlow/flutterflow-issues#3758]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using bottom sheets, custom alert dialogs, the parameters passed are not saved, I add the values ​​and in a few seconds it reverts my change. This is regardless of whether the parameter is required or not.

### Expected Behavior

I hope that when filling in the parameter values ​​they are saved correctly without reversing.

### Steps to Reproduce

1 - Create a new project

2 - Create a component with 2 parameters

3 - On a page, create a page action block

4 - In the created action block action flow, add a customized alert dialog with the previously created component and pass the parameters.

5 - Note that after adding the values ​​in a few seconds they are reversed and lose the added value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z/Hqx89god9A7arAb/l7/TkRJmk7aoJN0OxhZ0s8KOvLBIYuP/WlbVpvQtfjT39Le0SmmlMD3NWKhs7tJcFcHy6dRtxyzZFIWArNQkGtUZOBBpOwWER5L/NgCGqz0cGw3SYkHNJfcVYn20+bOOysTjbbCbqzIlFISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/f0534452-74ab-4b05-9d4d-bf03b788f4fb

### Environment

```markdown
- FlutterFlow version: 4.1.86 (Mac), 4.1.86+ (Web)
- Platform: MacOs
- Browser name and version: Chrome 128.0.6613.115
- Operating system and version affected:
```

### Additional Information

Without this working correctly, I have to create alternatives that mess up the project, having to create the same flow of actions on the page several times where I need them so that the components can be called and their parameters passed, so any change in the flow has to be modified in all the locations.

**Comment by paulperez-dev** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

Thanks for the report!

**Comment by NestManagementIT** [comment]
I'm having the same issue.
Page Action Blocks - cannot set the parameters on "Navigate To" action. The "Pass" parameters section closes itself shortly after opening with no changes.
Failed both on Flutterflow v4.1.86+ web app and an updated windows desktop Flutterflow app.
Deleted the long standing Navigate To action created it again, but cannot set any parameter for it without the Pass section closing itself in the "Define Action" sidebar after a few seconds.

**Comment by paulperez-dev** [comment]
Hi @syg-eliseu, @NestManagementIT,

The issue has been fixed. Could you please verify if you are able to replicate it in the latest version?

Best regards,
