### ISSUE TITLE
Can't add Actions new Action Editor

### ISSUE THREAD

**Issue by marioprego** [FlutterFlow/flutterflow-issues#3759]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the new action editor after selecting the onTap trigger I cannot add any action or condition.

### Expected Behavior

After selecting a trigger you should be able to add actions or conditions to the action workflow.

### Steps to Reproduce

1. Select the button widget
2. Select actions tab in widget properties window
3. Open the action editor
4. Select the onTap trigger
5. Click in Add Action

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kksjfz4t2rulG15DLbe5agjkvHFg/TLJEoetxc0gbfe/4E4kpd+LCQE1uOPazaHNAG1GIhlMH0NaKivLXC/UEBwiVR7ZG+odychPPbD2hRa61PMyKP0Z9L+9WGky1152jnxBTLu5aLXdhwziYB9y/QT2Cf9qOYwx5e6fDbOY=

### Visual documentation

![flutter](https://github.com/user-attachments/assets/781819f8-f4bc-462d-824c-fcec35698366)

### Environment

```markdown
- FlutterFlow version: v4.1.86 released September 4, 2024
- Platform: MacOS Desktop
- Browser name and version:
- Operating system and version affected: macOS Sonoma 4.6.1 (23G93)
```

**Comment by rzambroni** [comment]
Hi @marioprego,

Thank you for your report! We appreciate you taking the time to bring this to our attention. I wanted to let you know that this issue has already been identified, and our team is actively working on a fix. I'll go ahead and mark this as a duplicate of the [previous report](https://github.com/FlutterFlow/flutterflow-issues/issues/3749).
