### ISSUE TITLE
TextField > AutoComplete - Build error for local iphone 15 simulator

### ISSUE THREAD

**Issue by keithchilek** [FlutterFlow/flutterflow-issues#3761]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have added TextField to a screen.
Activated the Autocomplete option
Click Hot Reload to test the new screen on my simulator

While building. I receive the following error:

Local Run iPhone 15:
lib/flutter_flow/flutter_flow_autocomplete_options_list.dart:68:28: Error: The method 'SubstringHighlight' isn't defined for the class 'AutocompleteOptionsList'.
 - 'AutocompleteOptionsList' is from 'package:vinny/flutter_flow/flutter_flow_autocomplete_options_list.dart' ('lib/flutter_flow/flutter_flow_autocomplete_options_list.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SubstringHighlight'.
                    child: SubstringHighlight(
                           ^^^^^^^^^^^^^^^^^^
<img width="505" alt="Screenshot 2024-09-05 at 3 36 58 PM" src="https://github.com/user-attachments/assets/7cf2f3e8-a0c6-416b-8682-491ca3fdde59">

### Expected Behavior

I would expect not to see this error

### Steps to Reproduce

1. Add TextField to a page.
2. Activated the Autocomplete option
3. Click Hot Reload to test the new screen on my simulator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEezcrlvIpJpb0A0bqILe5VpwMwHVgjbJ0vpe5+dwsjCeLnOuw1Pc7eQFJCcuqHdHNMI2aljXM10sGLkuOTG+43GxacR4hH+KtxUxDvRninMbKtC5bsOGhDM/JWFXbD0auz3CR/B/hedHAR1DqyCeyAa3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="945" alt="Screenshot 2024-09-05 at 3 39 05 PM" src="https://github.com/user-attachments/assets/1be37f63-b8f1-418a-b544-df49aef849b6">
<img width="945" alt="Screenshot 2024-09-05 at 3 39 24 PM" src="https://github.com/user-attachments/assets/91bb9239-1430-472d-bada-59500fc88003">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.87 released September 5, 2024
Flutter version is 3.22.2
- Platform: MacOS Desktop
- Browser name and version:
- Operating system and version affected: Sonoma 14.4
```

**Comment by Alezanello** [comment]
Hello,

Thank you for your message! I tried to replicate the issue you’re facing, but I’m unable to create an account in your app to reach that part of the process. Could you please provide a demo account or credentials so I can better investigate the behavior?

I appreciate your help!

Best regards,<br>Azanello

**Comment by janiator** [comment]
I had the exact same issue while using the iPhone 15 Pro simulator. Works after stopping the app and recompiling it for test. It seems that the error occurs if you try to hot-reload after initially enabling autocomplete.

**Comment by keithchilek** [comment]
I also found that if I work using the web version and then just like the hot reload on the desktop version it seems to work.  Which obviously isn't ideal.

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
