### ISSUE TITLE
The project is not currently connected to our servers issue

### ISSUE THREAD

**Issue by ZhivotenkoAlex** [FlutterFlow/flutterflow-issues#3762]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a group of api calls and I need to update one of them with additional variable.
After I updated it, I tried to add this variable to the action for api call but got the following error message "The project is not currently connected to our servers" and updates not save. The issue I got in both the web version and the desktop application

But another one of my projects seems to work well.
I tried duplicating the project but got an error response "Unavailable".
I'm strongly sure that this issue occurs after I updated FF the day before yesterday.

### Expected Behavior

The updates should be saved

### Steps to Reproduce

1. Go to the API Calls page
2. Create new apiCall in the group
3. Go to any of pages and add api call to the page onload
4. Got an error 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Thereareerrorwithgenerationbugreport

### Visual documentation

<img width="1535" alt="image" src="https://github.com/user-attachments/assets/e618bc9b-c78c-427e-8f97-b69295790b43">

### Environment

```markdown
- FlutterFlow version: Web 4.1.86 / Desktop: 4.1.87
- Platform: Web / Desktop app
- Browser name and version: Safari Version 17.6 & Chrome 128.0.6613.115
- Operating system and version affected: MacOS Sonoma 14.6.1
```

### Additional Information

I tried to duplicate the project but got an error ( other my projects duplicates successfully )
clean cockies and cash
tried to do the same in the incognito mode of the browser
reinstalled MacOS application
I did not find information on this problem in the documentation
tried to generate a bug report but got an error "failed to generate bug report code" with 'unavailable" response

**Comment by Alezanello** [comment]
Hello,

Thank you for reaching out, and I’m sorry to hear about the issue you’re experiencing. I attempted to replicate the problem by following the steps you mentioned in a new project, but I wasn’t able to reproduce it. This suggests that the issue may not lie within the API Call section.

However, I noticed that your report didn’t include a bug report code or project ID, which would help us better understand the context of the issue. Please keep in mind that this GitHub Issue Tracker is primarily for problems that can be consistently replicated in a new, blank project.

For more specific or complex issues like yours, I recommend reaching out to our support team through the in-app chat or by emailing support@flutterflow.io. They have the necessary tools to assist you with these types of behaviors.

Thank you for your understanding!

Best regards,<br>Azanello<br><br><br>The video trying to replicate it:

[Projects - FlutterFlow - Google Chrome - 6 September 2024](https://www.loom.com/share/b28535b367a2456687f34441e9b439bd)

**Comment by ZhivotenkoAlex** [comment]
Thank you. I will write to the support team

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
