### ISSUE TITLE
Deploy from Github Repo not working if Repo is private

### ISSUE THREAD

**Issue by JanikHalder** [FlutterFlow/flutterflow-issues#3763]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get a Server Timeout if i try to deploy my app from my private repo using the FF deploy feature. I tried it also with a project and a public repo, than everything is working.

### Expected Behavior

Deploy from private repo

### Steps to Reproduce

Deploy project from github repo using FF mobile deployment

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WivLq285PmM9Y15DLbcIwiikRQ1w6U5IrkcN9RREbB4yoE5wPX/zORFVdZ8OrdglUOmL8+WcepvePm9z1A+4BCzmcRohSzpZISRbzTlmgMZOYDpC0VXR+GshQIUyg0Ym7nBVDB7Bsc3wQw1OhfuuuQizbK5DoOVUBPv6YVZnXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="1171" alt="Bildschirmfoto 2024-09-06 um 13 42 26" src="https://github.com/user-attachments/assets/e43d7903-dc3d-4778-91b7-5ae99b8b4f44">

### Environment

```markdown
- FlutterFlow version: v4.1.87 released September 5, 2024
- Platform: MacOS
- Browser name and version:
- Operating system and version affected:
```

**Comment by arniigreat1** [comment]
I'm deploying from github repo as well actually. And it's stuck in queue. I reported this issue in another string, but this may be related

**Comment by JanikHalder** [comment]
@paulperez-dev Hi Paul, any updates on this?

**Comment by paulperez-dev** [comment]
Hi @JanikHalder,

I was able to successfully publish from a private repository. Could you please check with the latest release and let me know if it works for you?

Thank you!

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
