### ISSUE TITLE
Voice messages in chats are not visible for other user

### ISSUE THREAD

**Issue by principiumOne** [FlutterFlow/flutterflow-issues#3765]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I built a function in my chats to send also voice messages next to normal text. I can also send the voice message and the audio get stored in firebase. Everything is fine. But I can just see my own voice message, the other user cant see the audio. And the audio is also working, I checked up everything already. 

Seems to be a matter of visibility to audio data.
<img width="513" alt="Bildschirmfoto 2024-09-06 um 18 00 21" src="https://github.com/user-attachments/assets/40d1f43f-3285-4802-938b-1b502000b66d">

### Expected Behavior

The voice message should be visible for both users. Same like in whatsapp. But it only appears in the chat, when I am the one how sent it.
![WhatsApp Image 2024-09-06 at 18 10 05](https://github.com/user-attachments/assets/533c5d7b-9892-4053-b13c-a08c843d5215)

### Steps to Reproduce

Here is a short tutorial on how I built the widget for voice messages. Maybe just a small bug, but I cant find the cause:

https://www.loom.com/share/5dffa5f053084507b892a0a5867c8c5c?sid=85633f02-9915-49e7-b580-6a610f6aaa57

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjf5Yp1xOFH1aXube9WjigsJjs1bL00sd4bGA0dCJzuPLMQdvWkTEhoXearT0FpeUSmmno1+s7mhYbLDfFdNS6sft1Y+Mx5EQ3jfFm6QZOBC8+CX3NCTJthFXLA57SvmCVAVbRqLWAM1Eybf+e+YALUQ7LtImdISq/LZO4=

### Visual documentation

https://www.loom.com/share/5dffa5f053084507b892a0a5867c8c5c?sid=0e9af853-6db2-4b1f-ad85-be46d6258481

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 6, 2024
- Platform: Android, local apk, also in debug
- Browser name and version: /
- Operating system and version affected: /
```

### Additional Information

I want to make the chat function work. Great feature to send voice messages within the app. I have never seen a project on templates, youtube or in community which had the feature of sending voice messages like in whatsapp, telegram, e.g. 

Would be great to make it run, so you could use this process to make a template for community or do a short tutorial on how to implement this for the communities own projects.

**Comment by Alezanello** [comment]
<br>Hello,

Thank you so much for recording and explaining everything in your video! I have a question that I hope you can help clarify. I'm a bit confused about how the reference of the other user is sent in the chat messages. Specifically, in the `OtherMessagesUserRecord`, it seems to be showing the same reference as yours. However, in the chat list, it displays different references for `user_a` and `user_b`. Could this be where the issue lies?

I would appreciate it if you could guide me through this part. Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2a385bdd-bebc-4787-9c68-f1f47664004c/2b2873f9-f93d-463f-945a-a60be1881e9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYTM4NWJkZC1iZWJjLTQ3ODctOWM2OC1mMWY0NzY2NDAwNGMvMmIyODczZjktZjkzZC00NjNmLTk0NWEtYTYwYmUxODgxZTljIiwiaWF0IjoxNzI1NjQ3MjI5LCJleHAiOjMzMjk2MjA3MjI5fQ.VjaKAjR3kdv7YNJU5GvIgAH6d1SRwJCDwRVcOyfwIlw " alt="image.png" width="484" height="637" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a645708d-8598-4def-bbfe-82aa2015f117/8cdb7157-f261-4dd4-9f03-051af4ba359e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNjQ1NzA4ZC04NTk4LTRkZWYtYmJmZS04MmFhMjAxNWYxMTcvOGNkYjcxNTctZjI2MS00ZGQ0LTlmMDMtMDUxYWY0YmEzNTllIiwiaWF0IjoxNzI1NjQ3MjI5LCJleHAiOjMzMjk2MjA3MjI5fQ.eleudTTlCPAbTTqcPqe_IPJPL-ah1K0O5iVSCiiDK2o " alt="image.png" width="413" height="479" />

**Comment by Alezanello** [comment]
On another note, I reviewed your Firestore rules. Could you try changing the rules for the `chatMessage` collection to "Everyone" for testing, to see if that resolves the issue? You can also try setting it to "Tagged users" as an alternative.

**Comment by principiumOne** [comment]
I took another review for you:

*Troubleshooting Chat Message Display Issue 👩‍💻* - Watch Video
<https://www.loom.com/share/ad31ccbb471e4aeb92e86fee6d6a8c60>
<https://www.loom.com/share/ad31ccbb471e4aeb92e86fee6d6a8c60?utm_medium=gif>

Hey team, in this video, I walk you through the process of troubleshooting
an issue with chat message display. I explain how I modified the rules for
chat messages, encountered a problem with chat references, and demonstrated
the steps to resolve the issue. Pay attention to the details as I navigate
through chat documents and user references to identify the root cause. Your
feedback on the solution provided is appreciated!

Maybe you find a solution for this bug.

Am Fr., 6. Sept. 2024 um 20:32 Uhr schrieb Alezanello <
***@***.***>:

**Comment by principiumOne** [comment]
The audio data get stored within firestore database and get converted to
that.

Do you think have I have configure something on that? Text is displayed,
cause its saved in the document.

Feels like this is causing the error.

Am Sa., 7. Sept. 2024 um 14:43 Uhr schrieb Adrian Schmidt
***@***.***>:

**Comment by Alezanello** [comment]
The data of the audio is Stored in Firestore Database or Firebase Storage? maybe the issue is with the rules within the Firebase Storage!

**Comment by principiumOne** [comment]
I think the audio file is stored in firestore database. How exactly can I
check this?

I push the audio file within the "create document" action to firebase.

I send you some attachments. Can you tell me how I change the rules for the
audio files? Or is this synchronized with the rule settings of "chat
messages"?

This is how the file path looks like:
/data/user/0/principium.one/app_flutter/audio_1725712891474.m4a

Am Sa., 7. Sept. 2024 um 23:54 Uhr schrieb Alezanello <
***@***.***>:

**Comment by principiumOne** [comment]
I think the audio is just stored locally. Seems different like the images,
that I upload to firebase via action.

Do you have an idea on how to upload the audio files to firebase like the
images? I dont know on how to set up this in the action. I just stop the
time and use the action output for the document.

Here is the link to the action:
https://app.flutterflow.io/project/principium-0qamsz?tab=widgetTree&component=chat_new_message

Am So., 8. Sept. 2024 um 15:33 Uhr schrieb Adrian Schmidt
***@***.***>:

**Comment by principiumOne** [comment]
I didnt get any answer till now from team.

Am Mo., 16. Sept. 2024 um 04:01 Uhr schrieb github-actions[bot] <
***@***.***>:

**Comment by Alezanello** [comment]
Hello, and apologies for the delayed response.

I noticed that you're using a custom action to upload the file to Firebase. Just to let you know, FlutterFlow also offers a built-in action that allows you to handle file uploads natively!

Feel free to give it a try!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1ff95707-4100-46e9-b58c-5eefeaa2f82d/a497eb92-bfe2-4962-93b0-e5d9f2d5b541?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZmY5NTcwNy00MTAwLTQ2ZTktYjU4Yy01ZWVmZWFhMmY4MmQvYTQ5N2ViOTItYmZlMi00OTYyLTkzYjAtZTVkOWYyZDViNTQxIiwiaWF0IjoxNzI2Nzc0MDY2LCJleHAiOjMzMjk3MzM0MDY2fQ.M5UeyAMhTSKBn943TBvMa9m-bBvzCAEEdiEaxd8WSEM " alt="image.png" width="1782" height="736" />

**Comment by principiumOne** [comment]
Thanks for the tip! I will Check this Out. Havent Seen that I can also
Upload mp3 natively.

Alezanello ***@***.***> schrieb am Do., 19. Sept. 2024, 21:28:
