### ISSUE TITLE
Unable to deploy to App Store

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#3768]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am not able to deploy to App Store since a few minutes ago.

### Expected Behavior

Deploy ok to the app store

### Steps to Reproduce

Deploy to the app store

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMmBx89PsctJ0LXube9VvCYRKUA6U40WlsFuUQobfJTxG7l/TMnOVBJuOLC0dGNAMGCZ+Ts10+/emvDpKvo6IRSBG706zqV+cw3yTk26eKa0EriWZ25/DfpPC0in55iO3R5DNshsdHhmwU2MH9/IFxHUGYzrPUcZOOSXOZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1559" alt="Captura de pantalla 2024-09-06 a la(s) 3 39 10 p  m" src="https://github.com/user-attachments/assets/8d7f0d7f-b649-4400-8fca-1729e2b41932">

### Environment

```markdown
- FlutterFlow version: v4.1.86+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac OS
```

**Comment by Daniellamm** [comment]
I am having the same issue

**Comment by LeonardoPiel** [comment]
Same problem here too. With app store and play store.

**Comment by andrewjneumann** [comment]
Also getting same issue, for Google and Apple deploys.

FlutterFlow v4.1.87 released September 5, 2024
Flutter version is 3.22.2

**Comment by sergevb** [comment]
Same issue for me with App Store.

FlutterFlow v4.1.87 released September 5, 2024
Flutter version is 3.22.2

**Comment by FreshLocalApp** [comment]
Same issue 9/6/2024

**Comment by rzambroni** [comment]
Hi Everyone!

Thank you for reaching out. We're aware that Codemagic experienced an outage earlier, which was causing deployment failures. At the moment, we're checking to see if the issue has been fully resolved.

We'll keep you updated as soon as we have more information. In the meantime, please feel free to let us know if you're still encountering any issues on your end.

Thanks for your patience!

**Comment by pstatile** [comment]
Seems to be working OK

**Comment by rzambroni** [comment]
We’re closing the issue as it appears to be resolved. If you continue to experience any related problems, please don’t hesitate to reach out.

Thanks for your patience!
