### ISSUE TITLE
Project error for conditional visibility does not open the property that has issue

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#377]
## Expected behavior (required)

When you see "Boolean property not properly set in Container", clicking it should open the conditional visibility variable setting.

## Current behavior (required)

Clicking the error only opens the widget, but does not open the conditional visibility variable setting. Instead it may open an unrelated tab like the query tab.

## Context (required)

N/A

## Screenshots / recordings

<img width="633" alt="Screenshot 2023-01-20 at 3 29 42 PM" src="https://user-images.githubusercontent.com/11810973/213823224-1ca8a663-a99e-40e7-8d8e-67ded9ec9fb8.png">

## Your environment

* Version of FlutterFlow used: 01/20/2023
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, Daniel!

The best I can do at the moment is navigate to the right tab (included in the next release). Auto-expanding the conditional visibility section or something is not possible right now.
