### ISSUE TITLE
Firebase Project Setting issue: FF falsely keeps connecting the old Firebase project

### ISSUE THREAD

**Issue by KittipochSae** [FlutterFlow/flutterflow-issues#3774]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have the same issue. I started having a problem with my Firestore database rule, so I tried to update the Firestore database rule and then I encountered this bug loophole:
- When I update the Firestore rule, I get an error Firestore is not connected.
![image](https://github.com/user-attachments/assets/e4c30b66-4879-4f34-be4b-b5f1b5e60de1)
- When I see my Firestore project it is connected. So, I tried to disconnect to reconnect but I got an error FlutterFlow project not associated with this Firebase project.. But this project is currently associated with this project, it's connecting, and when I try to do an action like authenticating the record is presented on the Firebase project.
![image](https://github.com/user-attachments/assets/8e0c26d4-59d7-4104-bef0-98c237a5786b)
### Some information that might be helpful:
- The project was originally connected with the Firebase project that FF created, but I manually connected it with my custom project a long time ago. The old project is deleted but FF still keeps a link to the old project in this session.
![image](https://github.com/user-attachments/assets/7756e7dc-abd6-416d-8d7b-46afc21420c7)
- I was trying to fix a problem with the Firestore database rule that when I create an account with Log in with Google the account is presented on the Authentication service but cannot create a record in the users collection in the Firestore database.
- When I clicked Manage Content, FF redirected me to the content management system of the old project deleted a long time ago. Obviously, it ran into an error.
![image](https://github.com/user-attachments/assets/4cd1ef87-8470-45b9-a436-4a57500ccf89)

I assume there's some function in FF that falsely keeps connecting the old Firebase project or maybe there's some bug in the Firebase project setting.

### Expected Behavior

- Manage Content section should link the new project.
- The Firebase project should be able to be unlinked.
- FF should recognize the project manually connected by user.

### Steps to Reproduce

1. Let FF create Firebase project automatically
2. Connect with a Firebase project that created by users
3. Try Manage Content
4. Try unlink the Firebase project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Visual documentation

https://github.com/user-attachments/assets/4e37ffba-1de2-40bd-87a2-7aeb40f54c7b

### Environment

```markdown
- FlutterFlow version: v4.1.86+ released September 7, 2024
- Platform: Web Application
- Browser name and version: Chrome Version 126.0.6478.183 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.5 (23F79)
```

### Additional Information

FF operated properly 2 weeks ago, but right now this setting is broken.

**Comment by Alezanello** [comment]
Hello everyone,

We apologize for the difficulties you're experiencing with your projects. We've seen similar issues reported by other users and are actively working on resolving them. Could you please review this issue and follow the provided instructions to see if it resolves your problem?

Issue link: [GitHub Issue #3744](https://github.com/FlutterFlow/flutterflow-issues/issues/3744)

Thank you for your understanding and cooperation!

Best regards,<br>Azanello

**Comment by KittipochSae** [comment]
It is the same issue. However, with the latest version of FF, I have made changes to the project and it is still not working.

### Environment
```
- FlutterFlow version: v4.1.88 released September 7, 2024
- Platform: MacOS App
- Operating system and version affected: MacOS 14.5 (23F79)
```

**Comment by Alezanello** [comment]
In this case, since it's the same issue, the best approach would be to provide all your details and the bug report code directly in the main issue thread: [https://github.com/FlutterFlow/flutterflow-issues/issues/3744](https://github.com/FlutterFlow/flutterflow-issues/issues/3744). This will help the engineering team focus on finding a fix more efficiently!

I’ll go ahead and close this ticket as a duplicate so all efforts can be directed towards resolving the main issue. Thank you for your understanding and patience!
