### ISSUE TITLE
Can't Setup New Firebase Project Through Flutterflow

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#3775]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attempting to add a new Firebase project through Flutterflow fails and crashes the app. 

### Expected Behavior

I should be able to create a new Firebase project and connect it in Flutterflow. 

### Steps to Reproduce

1. Create a new project
2. Attempt to create a new Firebase project from inside Flutterflow
3. Google login fails to load, and the client crashes when the login window is closed. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol+fl4ot1xOVY1aqMbfpsmiAXNlgjarxMk8FTawsYC5/NG4gIZfTBXE9uOP25dkFmOWGZrzkx0PzGm9z1Cu1fBwqtG75+ypZ2TTuVbFm5RbqqPM+ebXFEGshRJmqX15iW2xRAVfpZdC1n7GaQF96+ZD7DNKbwC1UvB8iXMqHXvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/f8c5deef-9ace-4805-8abe-e8328c2d74df

### Environment

```markdown
- FlutterFlow version: 4.1.88
- Platform: Windows Desktop
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### Additional Information

I can't connect my new project to Firebase, which slows down my development and testing.

**Comment by rzambroni** [comment]
Hi @MartinLockheart,

Thank you for the report. Unfortunately, this is a known issue that the team already has in the backlog for a fix.

As a workaround, you can use the WebApp ([app.flutterflow.io](http://app.flutterflow.io)) to create the project and continue working on it from the platform of your choice.

You can refer to the original ticket for updates: [https://github.com/FlutterFlow/flutterflow-issues/issues/2935](https://github.com/FlutterFlow/flutterflow-issues/issues/2935)

**Comment by MartinLockheart** [comment]
Ah, I missed that, my apologies! Thanks.
