### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by linux4me2** [FlutterFlow/flutterflow-issues#378]
## Expected behavior
When clicking on Run mode should show the application

## Current behavior
I am getting a Build failed although in editor there are no issues at all

## To Reproduce
1. Have an application with Supabase connected
2. Run test mode

![image](https://user-images.githubusercontent.com/68695689/213867649-41772d15-714a-4c11-a707-7fec20568840.png)

## Your environment
* Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Windows Desktop through Chrome web browser
* Browser name and version: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Desktop windows 11

**Comment by linux4me2** [comment]
Issue has been resolved at least to run in test mode. It was caused by a custom icon which had 3 parameters. Bg_color, color and icon
It was placed in another 3 components as a custom component icon. Icon and color parameters were set manually but Bg_color through some conditions. 
There were no issues in builder but after removing each component manually, finally that was the one causing the run to fail

**Comment by wenkaifan0720** [comment]
Hi @linux4me2. Was it a custom component or custom widget that you wrote? If you believe this might be a bug on our end, could you provide us with more details (and possibly the project link)? Thank you!

**Comment by linux4me2** [comment]
Hi @wenkaifan0720.
It was a custom component not a widget. I am sure its a bug from FF side because it was tested couple days ago and was working. Nothing changed since then.
Unfortunately, I am not able to provide access to the project but I can create a new project with the component and share you in the next days

**Comment by wenkaifan0720** [comment]
Hi @linux4me2. Any updates? Are you still experiencing build failures?

**Comment by wenkaifan0720** [comment]
Closed due to inactivity of more than two weeks.
