### ISSUE TITLE
Unable to produce details from query on front-end

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#3780]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! My app will have a section titled 'something like a Word of the Day', wherein every day, a new affirmation needs to be updated on 'Dashboard'. I am trying to query the collection, however, nothing is visible. I have added few entries in the collection to check and then will upload a complete csv. 

![image](https://github.com/user-attachments/assets/881ac12d-118e-4266-a9e3-8af74a18cdef)

![image](https://github.com/user-attachments/assets/ea02f57d-65ab-4995-bb91-8a9301c85da9)

### Expected Behavior

The text widget should fetch the data from backend query.

### Steps to Reproduce

1) Add Query collection to Text widget which needs to be updated daily
2) The text widget should be automatically updated basis the data provided in the collection

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn15YVPj7xE7q6JccBKjSQWOUAlbLgO0cpBczwYF5D0PJkQRc/BQExWXLyjd2NbeWaZuGYe1vfqiITPKO4CPUiqQIs7/qp2FAn/Vj2nMs2mCJaRfW1QO5lXI2Kz58ONrhFQJtNpWXgl3GemGty+fBTsNYTAIEgjPMmlKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/1808b1e2-8900-49ce-96fc-58263b348a03)

![image](https://github.com/user-attachments/assets/84aaef2c-63bb-42cb-b6c5-ae3a85c9af99)

![image](https://github.com/user-attachments/assets/bd5a68bc-9595-4136-9ac0-0306603eff2d)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Chrome 1.28
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment]
Hi there!

After reviewing your project, you are absolutely right—you do have a query set up, but no variable has been selected in the "Text to Show" field. To display text in the widget, you'll need to select a variable. In this case, the variable you're looking for is inside the document returned by the query and is named "Affirmation" (a string variable).

Here’s a GIF that shows how to do this.<br>(Don’t worry, I only have read-only access, so no changes were made to your project!)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9940bc48-3e9d-4cab-8151-d949f3600c95/171819b4-cdb8-4adc-9a98-5b8dcddc9396?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OTQwYmM0OC0zZTlkLTRjYWItODE1MS1kOTQ5ZjM2MDBjOTUvMTcxODE5YjQtY2RiOC00YWRjLTlhOTgtNWI4ZGNkZGM5Mzk2IiwiaWF0IjoxNzI1ODg2MDM5LCJleHAiOjMzMjk2NDQ2MDM5fQ.gulvhWswnyjOSeWT8OQe1sPTmjtvihGzkuYq02H1IIM " alt="querytext.gif" width="1100" height="898" />

Hope this helps!

**Comment by plannedlivingjournal** [comment]
Hi @Alezanello, Thanks for your support and will try it once. If it doesn't work will seek your help again.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
