### ISSUE TITLE
Setup local run stay inactive when configure it until i restart windows app

### ISSUE THREAD

**Issue by Digitpixels** [FlutterFlow/flutterflow-issues#3783]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/64b9a9c9-b942-49e7-835f-6f79852fc4c7)
It make active only when i restarting Windows app

### Expected Behavior

I want to configure local run

### Steps to Reproduce

1. Launch windows app
2. configure local run
3. do all 4 step 
4. you can retry to configure many times
5. When i restart app status pass to active

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

xxxxxxxxxxxxxxxxxxxxxxxx

### Visual documentation

![image](https://github.com/user-attachments/assets/20be61be-90ad-45d8-86ff-64b19ddd9cb2)

### Environment

```markdown
- FlutterFlow version: 4.1.88
- Platform: Windows
- Browser name and version: Windwos desktop
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue. Does this behavior occur every time you try to run the Local Run, or did it only happen the first time, with subsequent attempts working correctly?

**Comment by Digitpixels** [comment]
I have this issue at Avery New update

Le mar. 10 sept. 2024, 13:20, Alezanello ***@***.***> a
écrit :

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Digitpixels** [comment]
I don't have any new update since my last message so i can't anwser you now , at next update i will notify here

**Comment by Alezanello** [comment]
Hello,<br> Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
