### ISSUE TITLE
Implicit animation is not triggered on alignment change

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#3785]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a container for a switch. I enable implicit animation for it. I set the alignment per an app state variable, which changes the alignment between left and right (X=-1, X=1). 
However the animation is not triggered on alignment change.

### Expected Behavior

Transition should be smooth with animation.

### Steps to Reproduce

1. Add a container in a bigger stack
2. Set the alignment per variable
3. Change the variable per action 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I don't see such an option.

### Visual documentation

Here is a video. The container that moves right and left ist set to animate. But it doesn't. It moves immediately.
 
https://github.com/user-attachments/assets/29c8351f-9a71-4117-9a43-7bf83208f73c

Here is how I set the alignment:
<img width="464" alt="image" src="https://github.com/user-attachments/assets/4dba10eb-383f-4918-b95b-accb402aeab7">

Here is the implicit animation setting:
<img width="294" alt="image" src="https://github.com/user-attachments/assets/7b871cff-63c4-477a-9f37-8c66b6a45f36">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.88 released September 6, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome 128.0.6613.120 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.6 (23G80)
```

**Comment by kantarse** [comment]
Here is the generated code for the moving container:
```

// Generated code for this tempSwitch_button Widget...
Align(
  alignment: AlignmentDirectional(
      valueOrDefault<double>(
        FFAppState().tempCelcius ? 1.0 : -1.0,
        1.0,
      ),
      0.0),
  child: AnimatedContainer(
    duration: Duration(milliseconds: 1000),
    curve: Curves.easeInOut,
    width: 27.0,
    height: 27.0,
    decoration: BoxDecoration(
      color: FlutterFlowTheme.of(context).secondaryBackground,
      boxShadow: [
        BoxShadow(
          blurRadius: 4.0,
          color: Color(0x430B0D0F),
          offset: Offset(
            0.0,
            2.0,
          ),
        )
      ],
      borderRadius: BorderRadius.circular(30.0),
      shape: BoxShape.rectangle,
    ),
  ).animateOnActionTrigger(
    animationsMap['containerOnActionTriggerAnimation']!,
  ),
)

```

**Comment by Alezanello** [comment]
Hello!

I’ve been trying to replicate the issue on my end, but everything seems to be working fine. Could you please share the **Bug Report Code** so we can investigate directly within your project?

If you'd prefer not to share your project, you can also create a new blank project, replicate the issue there, and generate a **Bug Report Code** from that.

To generate the code, go to the **Widget Tree**, right-click on the **Scaffold**, and select **"Get Bug Report Code."**

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b8f02273-3740-46d2-a3ed-c7cf662e6cb0/42561bf4-1294-44f4-a589-d0f4d99bcdb3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iOGYwMjI3My0zNzQwLTQ2ZDItYTNlZC1jN2NmNjYyZTZjYjAvNDI1NjFiZjQtMTI5NC00NGY0LWE1ODktZDBmNGQ5OWJjZGIzIiwiaWF0IjoxNzI2MDU2MDQ1LCJleHAiOjMzMjk2NjE2MDQ1fQ.WCfFR8L3Sp3dhykl4-qyJtXFVi3zW07j0krcYfRtXXM " alt="image.png" width="440" height="351" />

Thank you!

**Comment by kantarse** [comment]
Hi @Alezanello, 
here is the bug code from the container where the animation should play: 
ITFfzPHq24VIscsA14SJc+0w9TgROUccTL4zlO1HcxAYGO/yPbJ+Os6kXBJvONeoSlNhHFC0mXIJwezXuOD9EPU4CE+WR6JdyLpUeDr/d3q8R8m7C7irOXcnRZlgfVCh07aF2gklIvhaV04g2nGmOOfIbHLYJ5+/Zwh9f6PHaOI=

**Comment by kantarse** [comment]
Hi @Alezanello, any progress here?

**Comment by kantarse** [comment]
This issue is "waiting for user response". What response is needed?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by kantarse** [comment]
It probably does still persist but since it's been over a month and I needed to move on in my project, I solved it via a workaround (I used a switch widget, which was my second option, as it's not customizable enough)
