### ISSUE TITLE
Button icon link to incorrect page thought the correct page is linked

### ISSUE THREAD

**Issue by principiumOne** [FlutterFlow/flutterflow-issues#3786]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to link from the chat button to the group chat with participants. But it seems to like to another page than the one I set up in the action on tap. 

Here is a review for this bug. Never seen something like this before:
https://www.loom.com/share/be237074fde54e91a6f43c2c10f35711

### Expected Behavior

Linking to the group chat page without a null value error. All the necessary fields are available and it should be loading the page. 

### Steps to Reproduce

Review for the bug:
https://www.loom.com/share/be237074fde54e91a6f43c2c10f35711?sid=723851b9-be8b-42de-8e86-481230582929

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjf5Yp1xOFH1aXube9WjigsJjs1bL00ttx+bw4bJJCvOpYUec/6P01CXde+d29UPWaMp141wa3WufLlO/AVNTuVR749+al6egzwdzmlbpOTF7jhYXB7I/tmBWLH4J6ZgyZ4XdJedFom2DmQIvO9dz/cNLLKDkQ8Sq/LZO4=

### Visual documentation

https://www.loom.com/share/be237074fde54e91a6f43c2c10f35711?sid=723851b9-be8b-42de-8e86-481230582929

### Environment

```markdown
- FlutterFlow version: v4.1.86+ released September 7, 2024
- Platform: Debug mode, android, ios
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I'll take a look at your project, but in the meantime, could you let me know if the navigation to **chatDetailedGroup** was previously set to navigate to **chatDetailsPrivate**?

Have you tried deleting the existing "navigate to" action and creating a new one to ensure there's no leftover configuration from the previous setup?

Also, did you try running the app locally or starting a new session in test mode to see if the issue persists?

**Comment by Alezanello** [comment]
I created an account to test the app, but i don't have access to a group chat in the events, if you can set it to me, my email is azanello@somniosoftware.com

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/181e8b64-3107-4450-a00e-4d05a2fdb438/8c78efc4-68b7-4d04-8cad-a8dadfde32b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xODFlOGI2NC0zMTA3LTQ0NTAtYTAwZS00ZDA1YTJmZGI0MzgvOGM3OGVmYzQtNjhiNy00ZDA0LThjYWQtYThkYWRmZGUzMmI3IiwiaWF0IjoxNzI1OTcyMDgwLCJleHAiOjMzMjk2NTMyMDgwfQ.8wjXx2X29p3STkSKj_8MZdJkP9QHsMJbkM9cGltodlg " alt="image.png" width="611" height="969" />

**Comment by principiumOne** [comment]
Hi. Now you have access to an event and the group chat for this event.

Before I navigated to private chat and then I changed it. I also deleted
the action and set up new. Also I started a new test session, but there are
no changes.

Am Di., 10. Sept. 2024 um 14:41 Uhr schrieb Alezanello <
***@***.***>:

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by principiumOne** [comment]
Its already fixed.

Thank you.

Alezanello ***@***.***> schrieb am Di., 1. Okt. 2024, 23:54:

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
