### ISSUE TITLE
Navigation after authetication doesn't work

### ISSUE THREAD

**Issue by LaVanguard** [FlutterFlow/flutterflow-issues#3788]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a button which autheticates and navigates the user to a selected page.
It logs the user via google, but doesn't navigate him.

### Expected Behavior

User is navigated after authetication like the flow says.

### Steps to Reproduce

Go to Admin Login
Click Sign In
Select google account which user has userLevel Enum as Admin.
Get signed in but not navigated.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk876y4x1oeFF+Kr+acBr/SoXJm4+ap0SscsZa0kdB4joPLJ+d8jRYldBYM/gTENhHGel8T4ep9bFhdntNfI4G0+WRr541apAFwvMQXq8Rp/TDKW8WXMnJ/xgN36a1KS3rwlACM5qZUYjw12QIeTIShfrJ5O/Zwh9f6PHaOI=

### Visual documentation

The flow
![image](https://github.com/user-attachments/assets/84220151-fc62-47cd-965d-98a57c7dd29e)

### Environment

```markdown
- FlutterFlow version: 4.1.88+
- Platform: Windows 11 Pro 23H2
- Browser name and version: Chrome 128.0.6613.120 64 bit
- Operating system and version affected: Windows 11 Pro 23H2
```

**Comment by Alezanello** [comment]
Hello!

I can see the **admin_login** page, but I wasn't able to locate the workflow shown in your screenshot. Has the issue been resolved, or did you find an alternative solution to achieve what you needed?

**Comment by LaVanguard** [comment]
Hi. I have edited this flow but still the flow on admin page after authenticating doesn't navigate to the next page.

**Comment by LaVanguard** [comment]
Hi. Even with this flow it still doesn't work. No matter where I build it.
Login works, but navigation never.
![image](https://github.com/user-attachments/assets/6e6740dd-0132-432b-a537-03acb26760cd)
![image](https://github.com/user-attachments/assets/2c1454b1-dfaf-4813-ae36-7f68f843487e)

**Comment by Alezanello** [comment]
Hello, and apologies for the delayed response.

I’ve reviewed everything, and it looks fine, but I’m not sure why it’s not working as expected. I’ve also checked the generated code, and it appears to be correct. Would it be possible for you to provide a test admin user so I can further investigate the behavior?

Thank you!

**Comment by LaVanguard** [comment]
How can I create you an account?

**Comment by Alezanello** [comment]
Just any demo account could work for example Admin/Admin123 just for test the AdminLogin

**Comment by LaVanguard** [comment]
I have created you an account: MrTestUser with admin privilliges. But don't now how to help you as this is the google login page. So maybe you can try with random google account as I will allow the not registered users to use it.

**Comment by LaVanguard** [comment]
If there is anything else I should do. Tell Me.

**Comment by LaVanguard** [comment]
mrtestuser@user.com = you can use this one if you wish.

**Comment by felipemontero** [comment]
Looks like when using Google sign in, after getting the authenticated token you are automatically redirected to the logged in page (does the app reload with the authenticated user when receving the token and therefore skip to the logged in page?), even if you state other flow by disabling the automatic navigation. I'm having the same issue, and that's the only conclusion I'm able to arrive.

**Comment by LaVanguard** [comment]
It's really bad to be honest. I tried to like FF, and I admit Flutter is very fast mobile software in general. But when bubble makes their native mobile, never ever will I touch this thing.
You build a flow and it doesn't work, there are no professional full end to end courses, many flows do not work even thou they should. There are multiple ways to get to the same goal, but 90% do not work. Debugging is atrocious (go to bubble and check their inspector).

**Comment by Alezanello** [comment]
Hello, and I apologize for the delayed response. I’ve attempted to reproduce the issue on my end but was unable to. I was able to successfully log in, navigate the user to Page X, and then proceed to another page without any issues.

To assist further, here is the public project link so you can test, clone, and modify it to see if you can replicate the behavior: [Project Link](https://app.flutterflow.io/project/qa-1952-tv4qdq).

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
