### ISSUE TITLE
Textfield autocomplete from firebase collection not working

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#379]
## Expected behavior (required)
Using a textfield with autocomplete on when the values are coming from from firebase collection. It should let the user to choose from the given values.

## Current behavior (required)
When the user starts to write to the textfield, the options are not shown.

## To Reproduce (required)
1. New Page
2. Add a Container with a firebase query. In my case its a list of countries ordered by country name
3. Add a textfield inside the container
4. Set the textfield autocomplete to on
5. Autocomplete options: Documents from the container query -> Map List Items -> countries
6. Run

### Bug Report Code (required, generate from Widget Tree)
ITFfl8/625NOm99D15SJYMcxniE4NW0cTLkvjuphcz8YGIztBJh+PeClQBNWZ72rTVNhHFmJsF4d0srQj4XlV8A4aC6sf6p6wqoJawzyXTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)
I want to use a textfield with autocomplete on to let the user select his/her country. The autocomplete options are coming from a firebase collection.

## Your environment
* Version of FlutterFlow used: 3.0 20th january
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome latest
* Operating system and version (desktop or mobile): windows 11

**Comment by Pepino-GR** [comment]
Hi tothati90,

I cannot reproduce your issue. If I set it as described, when I type a letter, it shows the options from my firebase collection. Have you redeployed your Firestone Indexes?

**Comment by tothati90** [comment]
@Pepino-GR 
My mistake, had a typo in my collection. Sorry for the inconvenience!
