### ISSUE TITLE
Query Caching Not Working on App Level or Page Level

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3790]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Query Caching does not work at both App Level & Page Level. The query only works as a regular Query (Accessible exclusively from child elements within the same parent where the query was done). 
<img width="1920" alt="Variabels" src="https://github.com/user-attachments/assets/b356132d-ace5-4337-8e4c-deaa1a665b55">
<img width="1920" alt="Actions" src="https://github.com/user-attachments/assets/833c872c-e26a-4f90-8455-4c460eb7ffd1">

### Expected Behavior

To have accessible the "Cached" query results at both App & Page Level. However currently only accessible at child of the queried element like a regular query.

### Steps to Reproduce

1. Create new project
2. Create full accessible by everyone collection
3. Created query on element and applied caching at app level.
4. Tried to access from other element within the page.
5. Not able to.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oksn6389IsdtJ+KriasExryQsH1whaqxM0MIbEQIaIpPNG7UIec/4VEptXbC+TVc3I2C0oHEdwNLWv/bIN/IVCyqAY7Z4/5N+Qz3xeFO6b5/WDbrpPEB6GtpKCEPC57uskxQmKthiLXA/3GC6GOquZ3bbNJzHNnoWD/mKWZLPjXPuQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="1920" alt="Variabels" src="https://github.com/user-attachments/assets/02d1b2a7-7741-41f2-b99d-0ced46c6a5e2">
<img width="1920" alt="Actions" src="https://github.com/user-attachments/assets/00655788-66b1-4009-b063-1e2f0a0530bc">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 7, 2024
Flutter version is 3.22.2
- Platform: Web & Native
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

It’s not possible to access cached data directly from actions. Instead, you’ll need to query the collection again on the other page, using the same cached data variable you set up initially.

Here’s an example:

Let’s say you have two pages: Page A and Page B.

1. On **Page A**, you query the collection “products” (using a single-time query), enable caching, and assign a cache name like “CachePageA.”
2. Then, on **Page B**, you query the same “products” collection (again using a single-time query). This time, when enabling caching, you’ll see the option for “CachePageA” in the dropdown. Select that, and you’re all set!

Now, Page B will use the cached data from Page A.

[2024-09-11 08-26-42.mkv](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7328c7d0-3753-4b8f-b0ef-4d091cc7b268/e244b385-988b-4871-a956-f167f709b5b5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MzI4YzdkMC0zNzUzLTRiOGYtYjBlZi00ZDA5MWNjN2IyNjgvZTI0NGIzODUtOTg4Yi00ODcxLWE5NTYtZjE2N2Y3MDliNWI1IiwiaWF0IjoxNzI2MDU0NDg3LCJleHAiOjMzMjk2NjE0NDg3fQ.q-gfjKkNBSfGGXaa76Yzcr5oq9R_FX0SiPZC4tC45S8)

**Comment by Kato-Official** [comment]
Hi @Alezanello thanks for the reply and taking the time to create the video. Great, I did not know that I had to recreate the query and then select the previously created. Thanks. Cheers mate

**Comment by Kato-Official** [comment]
Issue solved. Appricciated.

**Comment by Alezanello** [comment]
To be fair, I never used Cache before, so we learned together!<br><br>Happy to know everything is ok now 😀
