### ISSUE TITLE
Walkthrough not working when any back end query is made.

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3791]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding any backend query the walkthrough no longer works. 
![Not Working](https://github.com/user-attachments/assets/1548c2e4-284d-441c-9951-1061755727b8)
![Working](https://github.com/user-attachments/assets/faf90873-fda1-4a5e-9bcf-3a3d0e71a0a4)

### Expected Behavior

Expecting the walkthrough to always work regardless if you make any back end query (FYI: The firebase backend query is done to a document which is readable and editable by anyone).

### Steps to Reproduce

1. Create new project
2. Created 2 walkthrough to demonstrate, one with backend query and one without.
3. Run both to demonstrate the issue.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oksn6389IsdtJ+KriasExryQsH1whaqxM0MIbEQIaIpPNG7UIec/4VEptXbC+TVc3M2KkhngJ+srShtzIN/cEYAmCQIB4+s9Aagr/cGWtV4imEc6efEZPEtpKCEPC57uskxQmKthiLXA/3GC6GOquZ3bbNJzHNnoWD/mKWZLPjXPuQ0SLb3kNh1JWeC/v

### Visual documentation

![Not Working](https://github.com/user-attachments/assets/2afbf5d6-f995-4901-9543-91efafbe06fc)
![Working](https://github.com/user-attachments/assets/ecc44426-b996-4fa0-b250-b8b8d89242ef)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 7, 2024
Flutter version is 3.22.2
- Platform: Web & native
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by paulperez-dev** [comment]
Hi @Kato-Official!

I was unable to reproduce the bug. It seems that when the query doesn't return a document, the widget isn’t displayed, which is why the walkthrough doesn’t have a target widget.

You can try adding a widget beneath the column but outside the container (where the query is), and then target this new widget for the walkthrough. You should see it working after that.

Let me know if this solution works for you! I'll go ahead and close this issue since it's not a bug.

Thanks for your understanding!

**Comment by Kato-Official** [comment]
Hi, not that was not the issue. I solved by simply adding a time delay wait of 2 seconds before running the walkthrough, the alternative is to wait to have fetched the entirety of any of the previous call from Firebase regardless of how far are from the current widget. So if you need to use the walkthrough for example on a widget which is nested in the middle of your page the time delay increases and not great UI wise. I have opted eventually to create and overlay on the widget itself and simply display or not based on conditions (which has also the added benefit of being able to tap the actual widget and execute actions.) Thanks anyways for looking into it. Cheers mate
