### ISSUE TITLE
Firebase does not show pictures anymore 

### ISSUE THREAD

**Issue by uelkuesara** [FlutterFlow/flutterflow-issues#3793]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have pictures loaded in my database (firebase) under the collection exercises, and they were displayed correctly in my app. Since a few days these images dont seem to display correctly anymore. When checking if the file is still in the storage I see it under the url but still the picture is not shown. 
Same is when I navigate to see specific exercises I only get a black screen.

### Expected Behavior

Display correctly and navigate correctly 

### Steps to Reproduce

1. Go to exercises (2 Tab in Nav Bar)
2. click on Kraft und core Übungen 
3. Some exercises are shown some pictures are missing 

 1. Go to exercises (2 Tab in Nav Bar)
 2. click on mobility exercises
 3. black screen 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi87huM9Pm8tA1pDuYO9VmigQH2YlbJc0sNobbxAjIoDoPJkUaczCX1pWZ8vgYEFbKEWGpzsF7tHIkuDDLfA6Fxasb6p5/6oJFz3NRjm/aoSzC7m0SGpQEfpTGHK10J+JnRInKsBuSiEH3UOqe9mAZDXDJOL7Zwh9f6PHaOI=

### Visual documentation

<img width="368" alt="Bildschirmfoto 2024-09-10 um 10 12 54" src="https://github.com/user-attachments/assets/77f065ba-fc7f-4774-b4d5-7f2bfe9b63a9">

### Environment

```markdown
- FlutterFlow version:  3.22.2
- Platform:
- Browser name and version:Chrome Version 128.0.6613.120
- Operating system and version affected: MAC IOS
```

**Comment by Alezanello** [comment]
Hello!

I checked your **PreSelectCategory** and noticed that your images are being sourced from a different site rather than Firestore. If you did this as a temporary workaround, I recommend reviewing your Firebase Storage rules to see if that’s the root cause of the issue with accessing the images. Some default rules can prevent users from retrieving images outside of their designated path. Please double-check the Firebase Storage rules and try again!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
