### ISSUE TITLE
Streaming API -> onMessageInput not working properly inside the Action Block

### ISSUE THREAD

**Issue by yadaniyil** [FlutterFlow/flutterflow-issues#3794]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

onMessageInput is not working as expected while using the stream API response in the page action block. Everything works fine while not using the action blocks. When trying to construct the data type object from the action block streaming API response I do not see the appropriate drop downs that are needed to finish the action. The video attached is much better for understanding the issue.

### Expected Behavior

I expect the Streaming API actions -> onMessageInput to work the same way as it works outside of Action Block. The video attached is much better for understanding the issue.

### Steps to Reproduce

1. Using the project from Bug report code 
2. Go to the actions of the single button at the center of the page.
3. See the predefined Backend Streaming API call. In StreamingResponseActions go to onMessage.
4. In onMessage try to create the datatype object from Action Parameters onMessageInput.
5. See new dropdown appear after picking "As data type" option. (All good).
6. While doing all above from Action Block the dropdown do not appear after picking the "As data type" option (not good).

The video attached is much better for understanding the issue.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ohc/6w5N1obxA1pDbbfpajiA5JkB+U6xMku5tbw40F4/NGu4MPsneVFRuZr3jSmw3JWL8jXI1xvfqjvDqUPI4aAutfIRZzZBccQz/eHKQb7HRBqiNfW1SOJ9nGHKG352G2RZ4Ks11SXwY1DiIetmibAnAHufJDGtEAOalKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/e5c2c72c-bd2d-48bd-925e-35de938d3c71

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 7, 2024. Flutter version is 3.22.2
- Platform: All
- Browser name and version: Google Chrome Version 128.0.6613.113 (Official Build) (arm64)
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

I watched your video and tested it in your project, and it definitely seems like a blocking bug. I'll escalate this to the engineering team so they can take a closer look and work on a possible fix. In the meantime, we'll see if there's a workaround that can help.

Thank you for your patience!

**Comment by InnerSky** [comment]
I'm also having the same issue, the same action chain when copied to a action block, the JSON path parser doesn't work anymore! Please help fix this! Thank you @yadaniyil for raising the issue.

**Comment by Unity2Blender** [comment]
Please look into this bug for the Action block.

Although in the meantime, try @InnerSky @yadaniyil try accessing it via a Custom a function or a Custom Action while passing the onMessageInput (action parameter) as an argument for whatever custom code u use. Best of Luck.
