### ISSUE TITLE
pro account entire 28 minutes not able to load testing environment

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#3795]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

see headline

### Expected Behavior

not headline

### Steps to Reproduce

MacOS desktop app
press test button

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi87huJFIruFK+KXicsdonjwRCUMcWOdEl+tuZwgbIoznBu0UOs74YVpVON/jaVNfPlGlmj8D/9bxjvOWJuwqHw6afNlOzZdcSw3ke2iiRr3SCJCWSXJCBZ5NCn6l5J+vhAkkAMVocnAfwzm6P+SuYz/DFOu/Zwh9f6PHaOI=

### Visual documentation

dfghjkl

### Environment

```markdown
- FlutterFlow version: latest
- Platform: web testing environment
- Browser name and version: chrome
- Operating system and version affected: latest mac desktop
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re facing this issue. Could you please provide more details about what’s happening?

I was able to access your project without any problems and didn’t notice any issues. Also, could you clarify what you mean by "Testing Environment"? This will help us better understand the situation and assist you more effectively.

Thank you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
