### ISSUE TITLE
com.google.android.gms.permission.AD_ID not being removed from codebase when removing permission string from FluterFlow

### ISSUE THREAD

**Issue by NathanGell** [FlutterFlow/flutterflow-issues#3796]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After removing the com.google.android.gms.permission.AD_ID permission string from FlutterFlow and disabling Google Analytics in FlutterFlow, then deploying to the Goggle Play Store, the following error is returned:

```
{
    "error": {
        "code": 400,
        "message": "This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.",
        "status": "INVALID_ARGUMENT"
    }
}
```

### Expected Behavior

The com.google.android.gms.permission.AD_ID permission should be removed from the FlutterFlow codebase and not inserted at build time.

App should successfully deploy to Google Play Store.

### Steps to Reproduce

1. Add the com.google.android.gms.permission.AD_ID string as a custom permission in FlutterFlow.
2. Enable Google Analytics in FlutterFlow
3. Set Advertising ID declaration in Google Play Console to Yes.
4. Deploy to Google Play Store
5. Remove com.google.android.gms.permission.AD_ID permission string in FlutterFlow
6. Disable Google Analytics in FlutterFlow
7. Set Advertising ID declaration in Google Play Console to No.
8. Deploy to Google Play Store

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kMjkz41jstdj1anQTcdUlhciHWY8aLsVi+pBaCosfZT2BLMcec/RVERoUt+hTGNcIk6WkWoW0vzXjc7PDfQ4GE6dfqpa1c5ySgvibF66SqayFJWgfkdQEdlPGWqk4Z+GkR5ACPVhWWQ81GCQPd69FnbYH7WwOUceDq/LZO4=

### Visual documentation

```
== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact app-release.apk
Publishing artifact app-release.apk
Publishing artifact app-release.aab
Publishing artifact release_mapping_mapping.txt

Publishing app-release.aab to Google Play
Published app-release.aab to track internal
Google Play failed to upload artefacts. This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.: {
    "error": {
        "code": 400,
        "message": "This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.",
        "status": "INVALID_ARGUMENT"
    }
}

Build failed :|


Publishing failed :|
Google Play failed to upload artefacts. This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.: {
    "error": {
        "code": 400,
        "message": "This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.",
        "status": "INVALID_ARGUMENT"
    }
}
```
![CleanShot 2024-09-11 at 10 58 27](https://github.com/user-attachments/assets/28b1afc2-fec5-4aa0-b90b-6302b5c5684d)
![CleanShot 2024-09-11 at 10 58 17](https://github.com/user-attachments/assets/3c4bd418-7591-4c85-81fc-60f2f9cee4d5)
![CleanShot 2024-09-11 at 10 58 22](https://github.com/user-attachments/assets/cbe6ac26-31e7-4ea6-9e00-93d9275d0152)

### Environment

```markdown
- FlutterFlow version: 4.1.89+
- Platform: Web
- Browser name and version: Arc Version 1.59.0 (53388)
- Operating system and version affected: MacOS Sequoia Developer Beta
```

### Additional Information

Unable to deploy future versions of my app.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're facing this issue. Could you let us know if you're deploying to the Play Store directly from FlutterFlow, or through GitHub or another provider?

I downloaded the code from your project, and I didn’t find any `AD_ID` permission in the generated code. It’s possible that old permission information is being cached somewhere. You might want to download the code locally and check if there’s any reference to `AD_ID` within it.

Additionally, there are similar discussions in the community that could help you resolve this issue. You can check out this thread:<br>[Google Analytics and Advertising ID Declaration](https://community.flutterflow.io/project-settings/post/google-analytics-and-advertising-id-declaration-Qbq7wq9aHSwf8Gk).

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
