### ISSUE TITLE
Flutterflow Latency and action auto cancellation

### ISSUE THREAD

**Issue by devlesorcier** [FlutterFlow/flutterflow-issues#3798]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Website and Windows 11 app is very slows and every action I perform is cancelled and I have to do it 2 times...

My configuration:
Intel Core i7-11700F @ 2.50GHz 2.50 GHz
32 Go RAM
Nvidia GeForce RTX 3080

Note that I only have Flutterflow open.... Until 1 month ago, it didn't do that...

### Expected Behavior

Not cancel my last action and dont freeze every 12 sec. (it freeze like fo a 0.5 sec)

### Steps to Reproduce

It's everywhere

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z8r13It2xeFE+KX6avpV+SUvKUM7U78nkdZTeEg8J5zKB+wAYvf7P1FWTLy9Y1FmJGH8kjoJ/PfqudnTM/o6FAWqfYR81LpIVg/wQkehV8m4DIe/fW1fO+lbfVSdy7aznhJ4KuNhdXA621+uAe6XUgDbQbr7O244RM+lKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/987c80e3-cce8-4c85-95f1-8c5621bc4b1e

You can see in the video 2 little freeze and action cancellation : First when I expand the column it work and when I want to change the text color, the Expansion cancelled. When I want to add a gradient it freeze for a second. 

Please note I have 80 screens and components

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 10, 2024
Flutter version is 3.22.2
- Platform: Windows 11 Google Chrome
- Browser name and version: Version 128.0.6613.137 (Build officiel) (64 bits)
- Operating system and version affected: Windows 11
```

### Additional Information

I have like 80 screens and components

**Comment by paulperez-dev** [comment]
Hi @devlesorcier,

So sorry you're experiencing this issue!

The action being rolled back is currently being tracked internally (team is working on this issue). This can happen when values are changed during the project syncing process.

Regarding the latency issue, I’ll check internally for more information, as it’s also related to the syncing process.

Thank you for your patience, and I’ll keep you updated!

**Comment by devlesorcier** [comment]
Thank you for all the work you doin to give us Flutterflow. Keep it up sir!

**Comment by paulperez-dev** [comment]
Thanks!!

Also, ignore the bot 👀

**Comment by devlesorcier** [comment]
Any news on this ? With the great FF5 is still here... Please note that with new app I don't have these bugs. My app have 50 screens and 200 daily user, like 10 of Custom Code and Page State

Thank you and oplease have a great day

**Comment by devlesorcier** [comment]
ANY NEWS ON THIS SIR ?

**Comment by paulperez-dev** [comment]
Hi @devlesorcier!

The fix should have been deployed to production yesterday. Could you please confirm if it's resolved on your end? Be sure to update to the latest version! 😀

Thank you!

**Comment by devlesorcier** [comment]
Sir,

I'd like to thank you for your hard work in providing the best possible no-code tool.

I would like to inform you that this problem is now SOLVED. This latest update is really incredible, and will greatly speed up my app development.

Thank you again for everything
