### ISSUE TITLE
Backend Query from widget is triggered once for each time you've navigated to a page

### ISSUE THREAD

**Issue by dmosdallas** [FlutterFlow/flutterflow-issues#38]
## Expected behavior (required)
When I navigate to a page that has a widget whose data is derived from an api query ([as described here](https://docs.flutterflow.io/data-and-backend/backend-query/api-call-query#2.-showing-query-data-in-ui-element)), I expect one request sent to the api backend to populate the widget.

## Current behavior (required)
If I navigate to a page N times, the Nth time I go to the page, *N* queries are triggered for the widget. Additionally, any action that causes the page to redraw, N more queries are triggered for each redraw. It's really easy to cause this behavior -- and also appears to happen in the flutterflow app itself, from any project page (e.g., https://app.flutterflow.io/project/$YOUR_PROJECT). In chrome, you can open the network inspector, resize the window, and see the mountain of queries sent to firebase.

## To Reproduce (required)
Create an app with two pages, one of the pages having a widget that is derived from an api call. Navigate back and forth between the pages a few times and then open up the network inspector (assuming chrome web). Each time you navigate to the page with the api-backed widget, instead of a single request, you will see one request for each time you've navigated to the page. What's worse, if you resize the network inspector, all those queries get retriggered each time the page is redrawn.

I was able to quickly trigger 1000+ queries to firebase from your app just by clicking between pages and then resizing the window a couple of times.

## Context (required)
This causes clients to issue _massively_ more queries than they need to, easily beating up backends handling expensive queries.

## Screenshots / recordings
![flutterflowQueryMountain](https://user-images.githubusercontent.com/96317410/195994480-f4450a80-b171-420b-88a9-0b0e71704f23.png)

^ above, I cleared the network inspector in chrome and resized the window for a few seconds and caused over 600 queries to hit your firebase backend.

## Your environment
* **Bug Report Code:**
* Version of FlutterFlow used: v3 October 5, 2022
* Platform (e.g. Web, MacOS Desktop):  web (chrome)
* Browser name and version: chrome (106, but appears to be any recent version). Looking at the generated code, I expect this to happen on all platforms.
* Operating system and version (desktop or mobile): windows 11

**Comment by bulgariamitko** [comment]
I dont get it when you navigate to a page in FF or in a normal page in Chrome you still generate a request. This is normal behavior.

**Comment by dmosdallas** [comment]
Right, I expect that it should be creating a single request each time I load a page.

Currently, if you navigate to a page 3 times, the first time you navigate to a page, it creates 1 request (as expected), the second time it creates 2 requests, the 30th time it creates 30 requests (eek!), etc. 

Playing around with this more, I think there are actually two things happening here. First is what I'm describing above which seems clearly wrong.

The other is that the backend query(s) seems to be re-issued each time the page is redrawn (e.g., you resize a window). I'm not sure if that's really a bug, but it seems a bit silly to trigger a database query for each intermediate frame when the window is resizing.

With these two behaviors combined, if I navigate back and forth 30 times and then resize a the window (which causes a few repaints), then I trigger _hundreds_ of queries by just resizing the window which seems really suboptimal.

**Comment by dmosdallas** [comment]
Ah, okay, reading over the generated code, I think I'm sort of understanding it now.

This amplification behavior only happens when I navigate with the 'allow back navigation' setting enabled (looks to translate to context.pushNamed in the code). When I disable back navigation, the query only gets triggered once each time I go to the page (irrespective of the number of times I've navigated to the page). 

I'm not super familiar with the internals of flutter's navigator, but is it possible that build (and the query within) is still triggered for every page in the navigator's history, even for pages not currently visible?

**Comment by organicnz** [comment]
@dmosdallas could you pls record your screen with [Loom](https://www.loom.com/)?

**Comment by bulgariamitko** [comment]
@dmosdallas , I am not a FF dev, but I am assuming that when you go to a page like I said it must trigger the request again. When you click on the back button it is just a back to the screen and it is not loading the screen again so that's why it is not sending the request again.

**Comment by bulgariamitko** [comment]
Can you show us a screenshot of your widget tree please as well?

**Comment by dmosdallas** [comment]
@bulgariamitko, here are screenshots of the two pages in FF. Widget tree is on the left and the onTap action for the 'this page' button is pulled up on the right:

### This is the page that's configured to make an api call to populate the second text object.
![apiCallPageWidgetTree](https://user-images.githubusercontent.com/96317410/196459947-f4a0f975-90b0-4a03-9446-24b97612b7e4.png)

### This is the page that is configured to make no api calls.
![staticPageWidgetTree](https://user-images.githubusercontent.com/96317410/196459954-628e9bd8-4f4b-47f0-94c7-3098de0b0d79.png)

lmk if there's anything else you want to see to recap. Thanks!

**Comment by bulgariamitko** [comment]
I still believe this is a normal behaviour. I will say why. It is normal each time you visit the page to trigger the query as the data has to come from somewhere and it is coming from the query. Also when you resize the window the query is executed every time because it is loading each time as there needs to be check if the size is ok with the screen you are viewing the page in. I hope that make sense, but it is not up to me to decide. Let's see what will the FF team decide. 🤔

**Comment by dmosdallas** [comment]
So, from their documentation on [Backend Queries](https://docs.flutterflow.io/data-and-backend/backend-query), they say:

> Backend Query gets triggered automatically as soon as the user navigates to the page containing the query.

It does not mention the backend query is actually triggered every time you navigate to _any_ page (using the default navigation action config) after you've visited the page with the backend query. This behavior is at least extremely surprising.

**Comment by shelpert** [comment]
I have not been able to reproduce this with Firestore, but it does happen for API calls. Unfortunately, it is not actually a bug in Flutterflow, since we give the user the tools to avoid it. 

If you turn off 'Allow Back Navigation' or turn on 'Replace Route' on the Navigate Action settings, you will find that the API calls no longer multiply. You can also fix this problem by making the second page 'Navigate Back' instead of 'Navigate To First Page', which I would say is the correct approach for this simple two-page use case.

Unfortunately the takeaway here is just that it is important to set up navigation in your app wisely. Hopefully at some point in the future Flutterflow will be able to advise users the best navigation settings based on their use case!

**Comment by bulgariamitko** [comment]
I am re-opening this issue as I just manage to confirm it and I would like to have an official statement from FF team about this issue. Essentially if you go to one page and then go to other and you have only API calls in your App all your API calls gets executed from all pages which is a bad behavior void and if it can be fix/avoided I would prefer that.
