### ISSUE TITLE
Issues with PushNotification after Firebase "disconnect" issue

### ISSUE THREAD

**Issue by fabsi88** [FlutterFlow/flutterflow-issues#3800]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was affected by the Firebase Disconnect issue https://github.com/FlutterFlow/flutterflow-issues/issues/3744. Since the issue got fixed, new versions of my App are not receiving push notifications anymore. It worked before. Devices with old version in the field are still receiving the Push Notifications

What I did already:
- Firebase project was disconnected and reconnected again
- Config files regenerated 
- Cloud Functions removed and redeployed
- Checked again on permission and logs
- Build new version and installed via TestFlight
- Checked User entry in Firestore for FCM Token - it exists (it was created a week ago with the old version)

### Expected Behavior

Push Notifications should work for all devices.

### Steps to Reproduce

1. Try to send Push Notification to users with new App Version installed
2. They wont get them (Of course the App is not running!)
3. The Entry for the push notification shows that it succeeds but num_sent is = 0 - so no FCM Tokens are found? Targeting users with old version is showing num_sent = 1.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEel/GAsIZ1pbxI1rn6auxVmQMxQUB+bZ0vlO1FGBM2C5DqB7MAe+DEaXdvTc+9YW46fFf/nkAz08qNhePfCfcEYCWqfYt607tQSwzdfEihMYyUO6isXUFSM8pPGHaH37aRpRQnOtNZLXhl7F+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="693" alt="image" src="https://github.com/user-attachments/assets/1d483bac-dac1-49b1-9369-4eb895502728">
<img width="922" alt="image" src="https://github.com/user-attachments/assets/9caad798-6ef5-4eb0-b9c0-bcddf052a45d">
<img width="939" alt="image" src="https://github.com/user-attachments/assets/26c6907c-602b-44b7-9d25-ec3653aa40dd">
<img width="669" alt="image" src="https://github.com/user-attachments/assets/3cf286d3-0019-4105-b89f-0469bd71630e">
<img width="747" alt="image" src="https://github.com/user-attachments/assets/e92ce166-e60c-47fe-a10a-2ba4fa823ba1">

### Environment

```markdown
- FlutterFlow version: 4.1.90
- Platform: iOS
- Browser name and version: Google Chrome (latest)
- Operating system and version affected: MacOS latest
```

**Comment by fabsi88** [comment]
I did some more tests and recognized that SOME messages get through - 1/5 roughly.... so I guess it's related to the same issue as in #3802

**Comment by paulperez-dev** [comment]
Hi @fabsi88,

I'm really sorry you're facing this issue! We've received similar reports and are actively looking into it. I'll keep you updated as soon as I have more information.

Thank you for your patience!

**Comment by monocat** [comment]
➕ 1️⃣

**Comment by vetxi** [comment]
Same here. Everything was working perfectly before and it suddenly stopped working as for the rest.

**Comment by vetxi** [comment]
I hope you can please help us sort this out fast, as it Push Notifs are critical for our app.

I've been doing more tests:

- When notification is triggered manually from FF Dashboard, same happens - the notification appears in Firebase but sent to 0 devices:
<img width="607" alt="Screenshot 2024-09-12 at 9 55 24 a m" src="https://github.com/user-attachments/assets/6ce4a5f5-4e02-47aa-b93e-d3b5cbc819d2">
<img width="444" alt="Screenshot 2024-09-12 at 9 57 37 a m" src="https://github.com/user-attachments/assets/4583466f-c13e-4f41-8092-67d974806515">

- When the notification is triggered directly from the Firebase console it works fine

- When the notification is triggered from the App same happens, appears in Firebase but sent to 0 devices:
<img width="450" alt="Screenshot 2024-09-12 at 9 59 55 a m" src="https://github.com/user-attachments/assets/5ed054d5-e089-4c57-b1e1-18476ddecce7">

In my case I already had the app installed on my device and it was working fine a couple of days ago, something must have changed with last updates maybe on Firebase Messaging side and a missing update on FF side.
Now push notifications:
- App installed on device not received anymore
- App in development same, not working anymore and having not touched anything related to push notifications

Looking forward to hearing from you, thanks!

**Comment by vetxi** [comment]
I hope you can please help us sort this out fast, as it Push Notifs are critical for our app.

I've been doing more tests:

- When notification is triggered manually from FF Dashboard, same happens - the notification appears in Firebase but sent to 0 devices:
<img width="607" alt="Screenshot 2024-09-12 at 9 55 24 a m" src="https://github.com/user-attachments/assets/617a2fa1-932e-47a9-9676-0353f0a49d99">

- When the notification is triggered directly from the Firebase console it works fine

- When the notification is triggered from the App same happens, appears in Firebase but sent to 0 devices:
<img width="458" alt="Screenshot 2024-09-12 at 10 08 57 a m" src="https://github.com/user-attachments/assets/395a2f7b-2741-4d55-aba8-86156220f9d0">

- In my case I already had the app installed on my devices (iOs and Android) and it was working fine a couple of days ago, something must have changed with last updates maybe on Firebase Messaging side and a missing update on FF side.

Now push notifications:
1. App installed on device not received anymore
2. App in development same, not working anymore and having not touched anything related to push notifications

Looking forward to hearing from you, thanks!

**Comment by bdonovan858** [comment]
Credit to, MahmoudIsmail and Ahmed I. Nour in the FlutterFlow community - here's a workaround for this bug.

https://community.flutterflow.io/ask-the-community/post/push-notification-not-always-successful-SXqYjnhJdSHKjd3

**Comment by fabsi88** [comment]
Thanks for this! Given the documentation there I expect a fast and
supported fix in the Cloud function by FF.

bdonovan858 ***@***.***> schrieb am Do. 12. Sept. 2024 um
18:18:

**Comment by vetxi** [comment]
Many thanks @bdonovan858 !!

Seems that it has been fixed. Just need to re-deploy push notifications.

**Comment by fabsi88** [comment]
Fixed with new FlutterFlow version and redeploy of PushNotifications CloudFunctions

**Comment by paulperez-dev** [comment]
Thanks for the confirmation guys!
