### ISSUE TITLE
comments don't get saved in action flow editor

### ISSUE THREAD

**Issue by Hellie3** [FlutterFlow/flutterflow-issues#3801]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In action flow editor. I write a comment on an action and save. It looks ok, but after a while it disappears, especially when I add another comment to another action.

### Expected Behavior

write comment, click save, the comment is saved

### Steps to Reproduce

go to action flow editor
ass a  couple of actions.
comment one and save
comment another one
look at the first one disappear
if it doesn't happen, close he editor and come back after a while

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkPHl8YxNrupE7aX6bu9V9SM7HGV/RJc0sd4bGA0dCJzuPLMQdvWkP1VpQvWid2Nle0SmmTkC0fOPjdj1OvQpEzSVQa5/yatyeg/gUk2XUZOBBZGeZUZ7IJ9QfUyC0J6riCMnHMtvWEI17Fyueu7LaC7AQKbpImdISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/8d7d4c86-ed05-4a00-9e1b-2eb149d71a44

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.90+ released September 10, 2024
Flutter version is 3.22.2
- Platform: Windows 11
- Browser name and version: not in browser, in FF desktop app
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @Hellie3,

Thank you for your report! This issue is being tracked internally, and we’ll keep you updated on any progress.

We appreciate your patience and will reach out as soon as there’s an update.

Thanks again!
