### ISSUE TITLE
Push Notifications not working

### ISSUE THREAD

**Issue by Joremando** [FlutterFlow/flutterflow-issues#3802]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In my chat app when I send a message the push notification is intermittent, that is, only every 5 to 10 messages only 1 or maybe 2 reach the recipient.

### Expected Behavior

Every message trigger it's respective push notifications to recipients.

### Steps to Reproduce

1. Test the Notification test Page
2. Fill the fields
3. Press "Send Notification" (preconfigured to send to my user)
4. Try it many times and only 1 message received every 5-10 tries.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeifHl34xOj70B0arIdMdolQMwHVgjbJ0vpe5+dwsjCeOsP4YqZcykchdWSOqHeAlUBVr8sEcEwNnHj/HpMu0EFE+aQbpE/5dhUxDvUmSRRraRCLWwfXYnTMVMfXGB05+J2hNTNfpZZVoTwzmIDdy+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="783" alt="Screenshot 2024-09-11 at 4 01 03 PM" src="https://github.com/user-attachments/assets/b300225a-1248-493a-932b-6f866b914147">

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: MacOS
- Browser name and version:Chrome Version 128.0.6613.121 (Official Build) (arm64)
- Operating system and version affected: web & mobile
```

### Additional Information

My chat app urgently needed to send push notifications. I've been struggling with this for the past few weeks.

**Comment by fabsi88** [comment]
Same problem here - but it's new for my app. Just did some more pushs and recognized that roughly 1/5 comes through...that's bad...

**Comment by fabsi88** [comment]
I also did some log analysis on the Cloud Functions but it always exits with 'ok'. It's really weird. I am targeting 1 user in my tests and sometimes the num_sent is 0, sometimes num_sent is 1 but no push popping up and a few times num_sent is 1 and a push was received. I fear there is an issue with the Cloud Function?

**Comment by Joremando** [comment]
Same, definitely it's a bug with FlutterFlow

**Comment by bdonovan858** [comment]
I can confirm, I'm running into the same issue as @fabsi88 and @Joremando.

This inconsistency only occurs when notifications are triggered through the app. When sending push notifications through the Firebase console directly, they are always delivered with num_sent = 1, which leads me to believe it's a FlutterFlow issue not a Cloud Function problem.

What have you tried so far?

- Checked FCM tokens, which are generating correctly. Users receive notifications just inconsistently, maybe 1 in 5 or so.
- Checked network connectivity and battery levels on recipient devices. I’m aware that iOS can prioritize deliverability based on certain device-specific settings, but I’ve ruled this out as a potential cause.
- Deleted and redeployed the cloud function.
- Sent messages directly from the Firebase console (works great).
- Checked Google Console Logs, which come up clean, no errors.
- I've tested this in both background and terminated state and the bug persists.

**Comment by Joremando** [comment]
@bdonovan858  describes the whole painful process we went through until we decided to come here. It's FlutterFlow, period.

**Comment by paulperez-dev** [comment]
Hi everyone,

I’m closing this issue as it duplicates #3800. Please refer to that issue for any further updates.

Thank you for your understanding!
