### ISSUE TITLE
main branch being edited directly even with edit protection

### ISSUE THREAD

**Issue by heitorcfelix** [FlutterFlow/flutterflow-issues#3804]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/548bc1ce-b3c5-4882-ba05-14c483097611)
My main branch is protected against direct edits but even so, all users are able to edit main directly without having to merge another branch.

### Expected Behavior

Main should be protected and not editable, or, edits made should not be saved, but they are. Edits should only occur through merging from other branches.

### Steps to Reproduce

1. Create a project.
2. Share a project with a team.
3. Protect the main branch.
4. Make edits to the main branch.
5. See if the changes appear to other users or persist after closing and reopening the project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzPHl3It1n7wA+KrUbexF9GIWI0MdXOczitVEew4bCIj4O7MUZ8mlQBZtXdCzaHNIIVWKglwCw9bFkvL9FfUCaCmBbb5Dyod+VBPPbECWV823BZGSfUFDN8ZbGh2+y7WJgiQnWfFZS01l7FOmHOmRQT2Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/762d581e-e5f4-43eb-abf5-e0f6d5bf5dee)
![image](https://github.com/user-attachments/assets/aa7f55cc-020e-4fa9-8ade-9cb3b5639e49)

### Environment

```markdown
- FlutterFlow version: 4.1.90
- Platform: All
- Browser name and version: Chrome 128.0.6613.120
- Operating system and version affected: macOs Sonoma 14.6.1
```

**Comment by paulperez-dev** [comment]
Hi @heitorcfelix,

Apologies for the late response! The behavior we observed is that changes made by other users were only visible to them, while the main branch remained unchanged. Could you please verify if this issue is still occurring in the latest version?

Thank you for your help!

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
