### ISSUE TITLE
supabase GetSchema results in HTTP 400

### ISSUE THREAD

**Issue by michaelbarnes** [FlutterFlow/flutterflow-issues#3805]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've enabled Supabase within my FF project and want and set the API URL and Anon key, however when I select the Get Schema button it fails to load the schema with an error message:
![Screenshot 2024-09-11 at 3 45 44 PM](https://github.com/user-attachments/assets/2172c949-79b5-4709-88dc-08d048ec6fb6)
Looking at the console logs in the browser, the request fails with status 400 (Bad request)
![Screenshot 2024-09-11 at 3 46 38 PM](https://github.com/user-attachments/assets/89925f0b-e8a0-497b-b378-e7c597c67c9b)

### Expected Behavior

When I click the Get Schema button it should load the database schema.

### Steps to Reproduce

1. Create a new app
2. Enable Supabase
3. Create a Supabase project
4. Copy and paste the API URL and Anon Key
5. Select Get Schema

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gksn6389IsdtJ+KriasExryQWOVwma5IRmO5qEBYdGLb1BI13Os7RSEttTeKBagtAP2GGnn8y+KHNudn1Gu1daU2sQ4NeycxqdTvKcDmhaLKrBpCoOEBDGdtQIW3C0KWGmA9SCOpfcnwaw2GQPe6iYCzDK7H6PVVND8iLC5L5gWCeASb3UDhrwmNecCfn

### Visual documentation

https://www.loom.com/share/d7527ace888e43bbba96c5196b5bd85e

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. I accessed your project and tested it by clicking "Get Schema," and everything appears to be working fine on my end. It's possible that there was a temporary issue with Supabase yesterday that prevented the schema from loading correctly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cdba0691-e510-4488-85ac-9468206d81aa/71f22737-24ea-4de0-8914-31d583676f43?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZGJhMDY5MS1lNTEwLTQ0ODgtODVhYy05NDY4MjA2ZDgxYWEvNzFmMjI3MzctMjRlYS00ZGUwLTg5MTQtMzFkNTgzNjc2ZjQzIiwiaWF0IjoxNzI2MTQ2OTIwLCJleHAiOjMzMjk2NzA2OTIwfQ.5Wp1Dpwx0TFsPQyuej1c3cIgrfdBQnccKAN0fSEUMBE " alt="image.png" width="1038" height="494" />

Could you please try it again and let me know if it's working for you now?

**Comment by michaelbarnes** [comment]
I can confirm it's working as expected now.
