### ISSUE TITLE
Can't Set Complex Variables Due To Overflow

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#3807]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm currently unable to set complex variables in many cases due to the selection list overflowing out of bounds of my window. 

### Expected Behavior

I should be able to select variables and set them without overflow issues. 

### Steps to Reproduce

1. Use a widescreen monitor and set Flutterflow to fullscreen view
2. Create a component with a long set of inputs.
4. Go to set a variable and select an "If/Then" statement
5. Set the condition to filter a list of data based on a condition and try to select an option further down the list (like "is Set and Not Empty")

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekcjf35VOj7wE7qnQdcJvuwMwJ0QlUIInj+0bWRMhfYDyO4kfPs/8XBBLYteBY1ZYfVql/Hwd06mNkt/XLfUqJT+Zf6061pRXQQvMWmqmaYvQDKjhdEd8TJhgIHau5rejkApSHPBfSk4k7VOQBPCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/f0f45d1b-ccca-4d07-a65b-cdfdc4354f97

https://github.com/user-attachments/assets/7b3170ca-867e-4b80-bbf9-bc3e159f3f6b

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: Windows Desktop
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### Additional Information

I have to resize my window to set complex variables at times, which is wasting time. And after all of that, sometimes the variable doesn't even get set (which is another issue I've been dealing with for nearly two weeks now).

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. Have you tried increasing the size of the Variable Menu? You can do this by holding the left-click button here and dragging the menu upwards.

Let me know if this helps!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0867e33c-8c75-401e-9331-755cc69d1449/9d9b8523-d3d6-4046-8784-74560f730073?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wODY3ZTMzYy04Yzc1LTQwMWUtOTMzMS03NTVjYzY5ZDE0NDkvOWQ5Yjg1MjMtZDNkNi00MDQ2LTg3ODQtNzQ1NjBmNzMwMDczIiwiaWF0IjoxNzI2MTQ3MjE0LCJleHAiOjMzMjk2NzA3MjE0fQ.TSxPze48bkAX5_3MTozd7fYk2KZZl91pGFkGkhZEyjc " alt="image.png" width="471" height="323" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/878f404b-d0e1-46ab-b3b9-255058beee69/a35f5988-330c-4bb3-904a-ebb02a443930?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NzhmNDA0Yi1kMGUxLTQ2YWItYjNiOS0yNTUwNThiZWVlNjkvYTM1ZjU5ODgtMzMwYy00YmIzLTkwNGEtZWJiMDJhNDQzOTMwIiwiaWF0IjoxNzI2MTQ3MjE0LCJleHAiOjMzMjk2NzA3MjE0fQ.OPPhN9-wlUEju0viUF22wOmlCYMgFLiWU90NJtPUK84 " alt="increaseSize.gif" width="716" height="851" />

**Comment by MartinLockheart** [comment]
Haha, well, I didn't even realize that was a thing. You're awesome, thank you.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
