### ISSUE TITLE
Exceptions inside FF VideoPlayer widget

### ISSUE THREAD

**Issue by dmk23** [FlutterFlow/flutterflow-issues#3808]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am testing a VideoPlayer widget and added it to my project with a simple video and plenty of space on the page

In browser debug here is what I see in the console. Seems to be the bug is somewhere inside the FF widget code

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
dart_sdk.js:37972 The following assertion was thrown during layout:
dart_sdk.js:37972 A RenderFlex overflowed by 25 pixels on the right.
dart_sdk.js:37972 
dart_sdk.js:37972 The relevant error-causing widget was:
dart_sdk.js:37972   Row Row:file:///opt/.pub-cache/hosted/pub.dev/flutter_spinkit-5.2.0/lib/src/three_bounce.dart:49:16
dart_sdk.js:37972 
dart_sdk.js:37972 The overflowing RenderFlex has an orientation of Axis.horizontal.
dart_sdk.js:37972 The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
dart_sdk.js:37972 black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
dart_sdk.js:37972 Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
dart_sdk.js:37972 RenderFlex to fit within the available space instead of being sized to their natural size.
dart_sdk.js:37972 This is considered an error condition because it indicates that there is content that cannot be
dart_sdk.js:37972 seen. If the content is legitimately bigger than the available space, consider clipping it with a
dart_sdk.js:37972 ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
dart_sdk.js:37972 like a ListView.
dart_sdk.js:37972 The specific RenderFlex in question is: RenderFlex#5338d OVERFLOWING:
dart_sdk.js:37972   creator: Row ← SizedBox ← Center ← SpinKitThreeBounce ← SizedBox ← Column ← ConstrainedBox ←
dart_sdk.js:37972     Container ← FittedBox ← FlutterFlowVideoPlayer ← Column ← _SingleChildViewport ← ⋯
dart_sdk.js:37972   parentData: <none> (can use size)
dart_sdk.js:37972   constraints: BoxConstraints(w=50.0, h=50.0)
dart_sdk.js:37972   size: Size(50.0, 50.0)
dart_sdk.js:37972   direction: horizontal
dart_sdk.js:37972   mainAxisAlignment: spaceEvenly
dart_sdk.js:37972   mainAxisSize: max
dart_sdk.js:37972   crossAxisAlignment: center
dart_sdk.js:37972   textDirection: ltr
dart_sdk.js:37972   verticalDirection: down
dart_sdk.js:37972 ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
dart_sdk.js:37972 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Expected Behavior

There should be no exceptions

### Steps to Reproduce

1. Add VideoPlayer to a column
2. Set width/height to 200 and use sample URL: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
3. Open the page in debug and see the error in browser console

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi/Lqw412rt8D1brUdPlsgSQWQ319apEo0cpBazwbfe+uB4kqevfOTERpXuLnY3xlfGeju2oW0+iKiN+eC+45F0usRY841al1WhbdfGOiVrq4FJWgZEd5Gd9PCh2F1sO3mB5vBLNqLk4d11OtON+/Hx/UJIOyNVceDq/LZO4=

### Visual documentation

Output in browser console posted above

### Environment

```markdown
- FlutterFlow version: v4.1.89+ released September 11, 2024
- Platform: Windows 10
- Browser name and version: Chrome Version 128.0.6613.138 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by rzambroni** [comment]
Hello @dmk23,

Thank you for bringing this to our attention. After reviewing the exception, it appears that the issue is related to the widget not having sufficient horizontal space to accommodate its content due to the fixed dimensions (200x200). I would recommend adjusting the size to provide more space, which should resolve the problem.

**Comment by dmk23** [comment]
@rzambroni thanks for responding

I already conducted the tests you are suggesting. The VideoPlayer appears in an unbounded Column filling up the unbounded Container/BottomSheet on a 428x926 screen. I get the same error if the VideoPlayer is sized inf/inf, 100%/100% and 80%/80%

If you look into the actual stack trace I believe it suggests the sizing problem inside the VideoPlayer implementation

Could you please take a closer look?

**Comment by Alezanello** [comment]
Hello!

Thank you for sharing the steps to reproduce the issue. I’ve followed them closely but was unable to replicate the problem on my end.

Additionally, I attempted to check the behavior directly in your project, but it seems that accessing the page requires login credentials. Do you have a demo user account I could use to test further?

For reference, here is the public project I created to replicate the issue. It’s a new, blank project where I added the video player inside a column, using the example video you provided.<br>[https://app.flutterflow.io/project/qa-1979-6ruxkn](https://app.flutterflow.io/project/qa-1979-6ruxkn)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/982d90b0-e2ee-45e9-9a42-c5d65ce3af16/5ef6c4eb-3e51-4724-82f7-ade47d212a06?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ODJkOTBiMC1lMmVlLTQ1ZTktOWE0Mi1jNWQ2NWNlM2FmMTYvNWVmNmM0ZWItM2U1MS00NzI0LTgyZjctYWRlNDdkMjEyYTA2IiwiaWF0IjoxNzI2NTc0MDk2LCJleHAiOjMzMjk3MTM0MDk2fQ.H1rD5TVs9EwZSLVVWOvJZ6uQuZhDHCmkSzJXobJn8W4 " alt="image.png" width="1916" height="828" />

Looking forward to your response!

Best regards,<br>Azanello

**Comment by dmk23** [comment]
Thanks for checking this out. I'm travelling this week and when I am back will re-test with FF 5.0 and try out your example

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
