### ISSUE TITLE
StickyHeader causing issues when scrolling to the bottom

### ISSUE THREAD

**Issue by petrmolek** [FlutterFlow/flutterflow-issues#3809]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When scrolling down in a list with a sticky header and reaching the bottom, the sticky header is "jumping", not staying at the top and behaving weirdly

### Expected Behavior

The sticky header should stay sticked to the top

### Steps to Reproduce

1. Create a new project
2. Add a scrollable column
3. Add a sticky header to the column
4. Add some content to the header and content
5. Run
6. Scroll to the bottom using **touch** (when using scroll wheel on web, it behaves OK) and observe the behavior

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Khc/15ZVNxeZE1brucflFmik5KVgjauYslupDdw8afb7wG7YQW8nRakhtOembdGxIIlmWgm0xw/SJuPPLDOwoBByJbKJJ1qVbEAzLfD6WMoyXDJC0PUBBONxMf3KkzpuZmhBQANdsSkUt60yMPOeAdBPDQpzpDXozH/39FKXOgXvnLRDsG30Jg1ZSfCvr

### Visual documentation

[https://youtu.be/Th8PxKRFY7U](https://youtu.be/Th8PxKRFY7U)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 11, 2024, Flutter version is 3.22.2
- Platform: iOS, Android, Web
- Browser name and version: Arc 1.59.0
- Operating system and version affected: iOS, Android, Web, all versions
```

### Additional Information

Project link: [https://app.flutterflow.io/project/sticky-header-test-z5psgg](https://app.flutterflow.io/project/sticky-header-test-z5psgg)

**Comment by paulperez-dev** [comment]
Hi @realpetrmolek,

I wasn’t able to reproduce this issue on an iOS device (using the touchscreen). Could you please provide additional steps to help replicate it? It would also be helpful to know if it's occurring on a specific platform. Additionally, could you share some details about your testing device (brand, model, polling rate, etc.)?

Thanks for your help!

**Comment by tonylkc** [comment]
@paulperez-dev I have similar issue. It was happening on Android only in my case.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!<br><br>@tonylkc, Your issue may be different. Feel free to open a new issue and attach the relevant information. Thanks for your cooperation!
