### ISSUE TITLE
Can't set variables, new editor dropdown bug! (Unable to set dynamic variables)

### ISSUE THREAD

**Issue by r-miljons** [FlutterFlow/flutterflow-issues#3810]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the field resets itself when selecting a field, selecting a data structure field, does not reset the field.
![flutterflow_iRIndhO7bQ](https://github.com/user-attachments/assets/f45b3a94-da79-4080-8f2d-916fdb5a12f6)

### Expected Behavior

selecting a variable and moving on

### Steps to Reproduce

try to set a variable

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lvLl8c9goelG+KX6ccFvmiMUKUc7bY03kutTcxM8J5DLBIYuP//7ak5uTde0dwhAP0yKiT4d+dXemvPfMu5cFy+sRb5TzKhcTjnNQlimaLbRDs/tPG5/DfJVCh2i1sCrohJCJupvLHA/wzn3Ady8fHTAGZzRPWsjMfj/NZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

![flutterflow_iRIndhO7bQ](https://github.com/user-attachments/assets/22cc0ba6-c294-41a9-a078-a1c86844952c)

### Environment

```markdown
- FlutterFlow version: v4.1.91+ released September 11, 2024. Flutter version is 3.22.2
- Platform: Desktop
- Browser name and version: --
- Operating system and version affected: Windows 11
```

### Additional Information

Please fix urgently, thank you

**Comment by r-miljons** [comment]
my understanding is that this produces an error state when selecting a field whose type doesn't match the expected, previous version behavior reflected that in the available options dropdown, but I had this happen when there are other available options that are valid

**Comment by Alezanello** [comment]
Hello!

Thank you so much for bringing this to our attention. I can confirm that this is indeed a bug, and I will be escalating it to our engineering team for a fix.

The main issue seems to be that incompatible variables aren't highlighted in red when you're trying to assign them. As a result, all variables appear in white, and some may not be set correctly.

We appreciate your patience while we work on this!
