### ISSUE TITLE
Audio files are not uploading in assets folder anymore.

### ISSUE THREAD

**Issue by zein1016** [FlutterFlow/flutterflow-issues#3811]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you upload in an audio, it is not being uploaded to assets file.

### Expected Behavior

to be added to assets/audio

### Steps to Reproduce

Add audio and download code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si8rq24p2rsNK+Kr+bsBB/WUsKWIlaLgssct/cxQcB4j4PIkAPOLRTxNvQtSzaH1YGlKkkkME0s7Sk/PqG/YoIUmtG5Rj/852ERPPYzuuV4uVBZeaXUcnGfxUGB2A0cKN2hB4PsBtWUYY7FyMBOyAaz2Cf9qOYwx5e6fDbOY=

### Visual documentation

...

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: 
Web
```

### Additional Information

...

**Comment by zein1016** [comment]
Hi, so the mp3 files are being mistaken for videos instead

**Comment by rzambroni** [comment]
Hi there, thank you for sharing the report! I’ve tried to replicate the issue on my end by uploading an MP3 file and using it in a sample app with the Audio Player widget, and it worked as expected.

Could you please provide a bit more detail? Specifically, which platform you’re using, and does this happen with every MP3 file you try to upload? Any additional information will help us investigate further!

**Comment by zein1016** [comment]
So if I upload an mp3, it is being saved in the videos asset instead of audios. I downloaded my code to check, and every new mp3 added in being saved in the videos folders. Also the mp3 files (newly uploaded ones) are showing as video thumbnail on assets section instead of audio. Please check attached photo as an example
<img width="293" alt="Screenshot 2024-09-12 at 16 22 48" src="https://github.com/user-attachments/assets/06f48e1e-562d-4425-b793-a073d9cc49aa">

**Comment by rzambroni** [comment]
Hey @zein1016, thanks for providing the additional details! Could you please specify which version of FlutterFlow you're using: the web app, macOS app, or Windows app?

**Comment by zein1016** [comment]
No problem! I'm using the latest version on the web

**Comment by rzambroni** [comment]
Hmm, that’s strange, I’m unable to replicate the issue—it seems to be working as expected on my end. Would you mind sharing one of the MP3 files you’re having trouble with? I’d like to check if it’s specific to certain files. Thanks in advance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2d96d84b-4190-46b6-9840-ef92a198ea56/f1fb8c85-00c1-4d6d-b9ec-c50231bd02fa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZDk2ZDg0Yi00MTkwLTQ2YjYtOTg0MC1lZjkyYTE5OGVhNTYvZjFmYjhjODUtMDBjMS00ZDZkLWI5ZWMtYzUwMjMxYmQwMmZhIiwiaWF0IjoxNzI2MTY2MDUyLCJleHAiOjMzMjk2NzI2MDUyfQ.bG1MVvatz8zudDlQpQfOq2TmT7LdNwjxHEIwnzHFcDo " alt="image.png" width="409" height="344" />

**Comment by zein1016** [comment]
I can't upload an mp3 file for some reason on github

**Comment by zein1016** [comment]
Hi, now I can't even upload mp3 on flutterflow as well. Before it was being mistaken for videos but now it's saying wrong extension

**Comment by zein1016** [comment]
It is working now normally.

**Comment by rzambroni** [comment]
Hi, Can you upload the sample mp3 to Google drive / Dropbox and share a link?

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
