### ISSUE TITLE
Unable to make rating bar interactive

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#3812]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! My app will have a section titled Feedback page, wherein I have added a rating bar widget and have kept default rating as 3.
I have made it interactive as well, however, in test mode nothing happens.

![image](https://github.com/user-attachments/assets/52583cff-786c-41b3-9f7e-b5d1c5621483)

![image](https://github.com/user-attachments/assets/18fa8748-8919-4c2f-9045-4372d4fb9bda)

### Expected Behavior

The rating bar widget should be interactive.

### Steps to Reproduce

Add Rating bar widget. Make it interactive and then test.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn15YVPj7xE7q6JccBKjSQWOUAlbLgO0cpBaysgF4juPLMiTPTOTERDTdPjYFZEM2e0nWoW09LvjtjPL8cnAy6VGYRNypB9WA2XfEGiVLKSFJWgZkF7P9NQCh2815+zqhJQPthadE4M2EylfeiXXhLfJ76zPG1BDq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/e58ed153-a12a-4b76-92fd-63c0efeab31c)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Chrome 1.28
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment]
Hi @plannedlivingjournal,

Could you please confirm if this is the same issue as reported in #3806? It seems to be working fine for me on Chrome (Windows).

Thanks for clarifying!

Best regards,

**Comment by plannedlivingjournal** [comment]
Hi @paulperez-dev, I think its the same issue. The rating bar is not interactive and I can't select or de-select the selected star in test mode.
So, here I have put default rating as '3' and it shows the same in Test mode. I am unable to click 4 stars or reduce it to 2 stars.

**Comment by paulperez-dev** [comment]
Hi @plannedlivingjournal,

Thanks for the confirmation. I’m closing this issue as a duplicate. Please refer to #3806 for further updates.
