### ISSUE TITLE
Error when running boolean check against two properties of LatLng Type

### ISSUE THREAD

**Issue by monocat** [FlutterFlow/flutterflow-issues#3815]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to run a boolean check to assigned latlng page state against current googlemap center, I keep receiving **Current Variable is not valid** error message.

### Expected Behavior

Since both types are latlng, I expect no errors.

### Steps to Reproduce

1. Create new page
2. Create page state named **currentMapCenter** and assign type LatLng
3. Add GoogleMap widget
4. Add Button
5. Enable Button's condition visibility and add the following condition: Page State: currentMapCenter Not Equal To Widget State: Current GoogleMap Center

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

[IT5fls/l6otOscsA1rqNd+9VhiYXQ3IjUIJJltYbSRQgfanqP4YAeM+lQ1pJbbyRSmNceWH8/W0J+sqLuNnfDMECYRyJboR4zpFqTAKVYFKgWr6KBaqSQGglRZlbGH7EzpuZnxQnNu9ZS3wg612UPeeRYC/bO7rGDjERL/3/KovOpF6GHSLgGX0Jg1ZSfCvr](IT5fls/l6otOscsA1rqNd+9VhiYXQ3IjUIJJltYbSRQgfanqP4YAeM+lQ1pJbbyRSmNceWH8/W0J+sqLuNnfDMECYRyJboR4zpFqTAKVYFKgWr6KBaqSQGglRZlbGH7EzpuZnxQnNu9ZS3wg612UPeeRYC/bO7rGDjERL/3/KovOpF6GHSLgGX0Jg1ZSfCvr)

### Visual documentation

![bug latlng boolean check](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6a63a491-7951-49f8-b1ff-d1347fcd5baf/df782a1a-285c-4794-a7b8-f0c45edd1431?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YTYzYTQ5MS03OTUxLTQ5ZjgtYjFmZi1kMTM0N2ZjZDViYWYvZGY3ODJhMWEtMjg1Yy00Nzk0LWE3YjgtZjBjNDVlZGQxNDMxIiwiaWF0IjoxNzI2MjUzOTMzLCJleHAiOjMzMjk2ODEzOTMzfQ.TKjTkhISbT1rliYT1IQ2Neookyhcl-vDniWJasuQ7DY)

### Environment

```markdown
- FlutterFlow version: web 4.1.89 / mac app 4.1.90
- Platform: Mac OS
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

*No response*

**Comment by cragroc** [comment]
I hit this too in my app, I am just comparing two app state LatLng variables and it won't work with the same error. 
Even in an action condition it won't work.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/8743d746-b017-4a96-b4ca-6808aa5d8ab1">

**Comment by paulperez-dev** [comment]
Hi @monocat! I noticed that you deleted your comment but reacted positively to @cragroc's suggestion. Were you able to resolve the issue? If not, feel free to share your project's Bug Report code, and I'll investigate this issue further!

**Comment by monocat** [comment]
Hi @paulperez-dev Not resolved. Don't recall deleting a comment. I was just agreeing with @cragroc

**Comment by monocat** [comment]
@paulperez-dev sorry. Didn't notice the Bug Report code comment. Fixed it. Thanks @cragroc for pointing it out.

**Comment by paulperez-dev** [comment]
Thank you for the confirmation, @monocat! I’ll go ahead and close this issue now.

**Comment by monocat** [comment]
@paulperez-dev I think we had a misunderstanding here. The issue remains. I just fixed the URL link that I had pasted in the Bug Report Code section instead of the required code. Again. The issue remains. :)

**Comment by monocat** [comment]
@paulperez-dev @pooja-ff @Alezanello @agreaves @leighajarett  Please reopen this since the issue hasn't been resolved. Thanks.

**Comment by paulperez-dev** [comment]
Hi @monocat,

Could you please confirm if the issue still persists in the latest version (5.0)?

Thank you for your help!

**Comment by monocat** [comment]
hey @paulperez-dev Yes. It's still persists. And it was confirmed in https://github.com/FlutterFlow/flutterflow-issues/issues/3863 I created a new report since I couldn't reopen this. Thanks for checking in.
