### ISSUE TITLE
Scandit Matrix

### ISSUE THREAD

**Issue by rich-chicken-logistics** [FlutterFlow/flutterflow-issues#3817]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project is currently unable to build due to an error related to the Scandit Matrix. The error specifically indicates issues with a custom widget called ScanditMatrix.

It's important to note that:

- No changes have been made to this custom widget or its functions.
- The project has been building successfully every day until now, but suddenly, without any modifications, the build process fails.

Please advise on how we can resolve this issue.

### Expected Behavior

Project not able to build, even downloaded code is not able to compile. Built with error.

### Steps to Reproduce

Integrate scanditMatrix into project for user to scan barcode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohefl6otPm9sC1oSJKe9V/CQQHE83aI0k0spOGD0aIpytBIYMacnCbkpDUt+7dGx5KEWLrEkD/vDxuPLmG8cpA0ueGKJqyIdiaz3LfEC/aoSnEbWof0BQPJhVGXLH0cOvnhNCOspedEIB22aMAt+XEz7sNbn7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-09-13 145555](https://github.com/user-attachments/assets/0324e5b7-7ca8-418a-8d75-aecdab1da448)

### Environment

```markdown
- FlutterFlow version: v3.22.2
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

### Additional Information

nil

**Comment by paulperez-dev** [comment]
Hi @rich-chicken-logistics! I'm really sorry you're experiencing this issue. The error seems to be related to the following class not being found: `BarcodeTrackingAdvancedOverlayListener` (possibly due to a missing import?). 

Could you please check the dependencies and changelogs to see if there have been any recent changes? ce!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
