### ISSUE TITLE
User getter in auth_util.dart returning empty despite information being available

### ISSUE THREAD

**Issue by smn-snkl** [FlutterFlow/flutterflow-issues#3819]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In `lib/auth/firebase_auth/auth_util.dart` the getters often return an empty string from the `currentUserDocument` getters instead of falling back to the `currentUser` getters as the `currentUserDocument` getters always return an empty string if the value is missing. Hence, e.g. the email getter
```
String get currentUserEmail =>
    currentUserDocument?.email ?? currentUser?.email ?? '';
```
will not return `currentUser?.email` if `currentUserDocument` exists, but it has no `email` field.

### Expected Behavior

The getters should check if the field exists on `currentUserDocument` and is not an empty string first and only then return it, otherwise fallback to the currentUser getter

### Steps to Reproduce

1. Create a new project
2. Open `auth_util.dart`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl8/luI9Oj7xZ7aryLO9Vq2IWNU9+apc0sNobbxAjIoDoPJkUac74TFtocNPnS2NDKEWKklEFpvzTkd/fJvApFyicbJRx+pAJaxfgQn6/aoSaCZeBP3QkHfNUC0iG0pm7phFvLu9sWkVm2DmmPd+ibz3sHYf7Zwh9f6PHaOI=

### Visual documentation

<img width="968" alt="Screenshot 2024-09-13 at 15 04 33" src="https://github.com/user-attachments/assets/61131c4a-1b96-4416-9310-7d644916dd7f">

### Environment

```markdown
- FlutterFlow version: v4.1.91
- Platform: any
- Browser name and version: any
- Operating system and version affected: any
```

**Comment by paulperez-dev** [comment]
Hi @smn-snkl,

I’ve added this as a feature request to our internal backlog, and we’ll address it as soon as possible. Thank you for your feedback!

Best regards,
