### ISSUE TITLE
Missing NSPhotoLibraryUsageDescription in Info.plist leads to Apple App Store rejection (ITMS-90683)

### ISSUE THREAD

**Issue by daynis-olman** [FlutterFlow/flutterflow-issues#3820]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying and compiling the app using FlutterFlow’s built-in Codemagic pipeline, the app builds successfully but is rejected by Apple with an ITMS-90683 error. The Info.plist is missing the NSPhotoLibraryUsageDescription key, which causes the app to fail review.

### Expected Behavior

The deployment pipeline should automatically include any necessary usage descriptions in the Info.plist file (e.g., NSPhotoLibraryUsageDescription) to ensure compliance with Apple’s guidelines and avoid app rejection.

### Steps to Reproduce

Deploy latest version from FlutterFlow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable - not widget

### Visual documentation

![Screenshot 2024-09-14 at 1 18 09 am](https://github.com/user-attachments/assets/0ad81ddb-49c0-4577-96b3-61eebdd21eb6)

### Environment

```markdown
FlutterFlow v4.1.89+ released September 13, 2024
Flutter version is 3.22.2
```

**Comment by paulperez-dev** [comment]
Hi @daynis-olman,

Have you added the permission message in your app configuration? This might be required for the issue you're facing.

**Comment by daynis-olman** [comment]
<img width="575" alt="image" src="https://github.com/user-attachments/assets/a1d8cc89-3a5d-4424-8a83-7a4f437bbfad">

Attempting to resolve this error message by adding manual iOS Permission Key  
`iOS Permission Key: NSPhotoLibraryUsageDescription`

**Comment by daynis-olman** [comment]
@paulperez-dev Thank you yes -> this has resolved the issue. AppStore wasn't displaying the NSPhotoLibraryUsageDescription error just until last month.

**Comment by paulperez-dev** [comment]
Hi @daynis-olman, 

Thanks for the confirmation! Glad to hear it was fixed.
