### ISSUE TITLE
Merging resets parameters, values, arguments and fields

### ISSUE THREAD

**Issue by ready4sea** [FlutterFlow/flutterflow-issues#3821]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a feature "stuck" on a branch, which can't be merged into main, because logic is lost in the process: parameters, values, arguments and fields which appear in the selected side of the conflict resolution disappear in the merged version. There are other smaller issues, but this is the single biggest problem.

This is the way the branch feature looks like before merging and before conflict resolution:
![image (2)](https://github.com/user-attachments/assets/8bb545d2-6e69-4238-919e-30a12ffc87ad)

After selecting this side during conflict resolution, this is the way the accepted (merged) version looks like:
![image (3)](https://github.com/user-attachments/assets/4f5c8fa4-dcd7-4e6c-8470-ea6e8a629452)

There are many many such occurrences which have the same pattern: the values are not carried over in the merged version. As a result, I would need to recreate my entire actions and logic in the merged version, which clearly defeats the purpose of branching, merging and conflict resolution.

This issue is not a one-off. In my case, I end up having nearly 70 such conflicts in the merged version, where arguments, parameters and fields are "not properly set" or "not specified" or do "not exist":
![image (1)](https://github.com/user-attachments/assets/ca554e51-9afa-491b-9305-ee371613d6df)

### Expected Behavior

I expect the accepted (merged) version to reflect what was selected during conflict resolution, and that version to show up once the merge completes.

### Steps to Reproduce

1. Launch merge
2. Conflict resolution
3. Select feature as accepted version
4. Look at accepted version
5. It's broken

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43hc/k07J+o/kG5c3iUsBKmj8UQEg8RIIV0dp7aCsrfePoBOw+Y/nBQFVUOMzhYGNIJVmGp3EX/MrlvfztLPU3EAWZb7ZjzZdfWgHxQn6ubLqLPJS3b0dAHcNQC0Cx0cGo2RVDNttuLkUj2WCIet+tbDXsHoToDFUWDea4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image (2)](https://github.com/user-attachments/assets/8bb545d2-6e69-4238-919e-30a12ffc87ad)

![image (3)](https://github.com/user-attachments/assets/4f5c8fa4-dcd7-4e6c-8470-ea6e8a629452)

![image (1)](https://github.com/user-attachments/assets/ca554e51-9afa-491b-9305-ee371613d6df)

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: MacOS
- Browser name and version: MacOS app and same on Chrome Version 128.0.6613.121
- Operating system and version affected: MacOS 14.6.1 (23G93)
```

### Additional Information

I am opening this ticket here at the request of support after encountering merge issues since last June.

This has been the subject of 5 tickets opened with support (# 1506, 4335, 4885, 6080 and 6747). At the request of support, I had also posted this information as a comment in #3177.

I have a feature "stuck" on a branch, which can't be merged into main, because logic is lost in the process: parameters, values, arguments and fields which appear in the selected side of the conflict resolution disappear in the merged version. There are other smaller issues, but this is the single biggest problem.

This is not an isolated issue: when merging, there are 70 such conflicts in the merged version, where arguments, parameters and fields are "not properly set" or "not specified" or do "not exist" in the accepted version. If it were juste a single occurrence, I would have done it manually long ago and merged. But a large part of the logic of my feature disappears when attempting to merge. This has hindered me from actually merging the feature over the last 3 months.

This issue begs for swift resolution.
@leighajarett @FlutterFlowEng

**Comment by Alezanello** [comment]
Hello!

Thank you so much for bringing this to our attention! I’ve also linked this issue internally to [Issue #3821](https://github.com/FlutterFlow/flutterflow-issues/issues/3821), so the engineering team working on the fix has access to this additional data for testing and identifying patterns.

I’ll go ahead and close this issue on GitHub to avoid duplicating tickets, allowing us to focus all efforts on the main one.

Thanks again for your help, and feel free to follow the main issue for updates!

**Comment by ready4sea** [comment]
Thanks for the reply @Alezanello.
Pretty puzzled at 2 things:
- #3821 is this issue, so wondering which "main issue" you are talking about.
- also, this issue has been raised in June, so surprized this hasn't been brought to your attention before. But better late than never, as they say.

**Comment by Alezanello** [comment]
Sorry I meant the Issue #3177!<br> [https://github.com/FlutterFlow/flutterflow-issues/issues/3177](https://github.com/FlutterFlow/flutterflow-issues/issues/3177)<br><br>And for the second point, everything new information is very welcome! So everything your bring to our attention is an improvement to finally fix this behavior in the branching feature!

**Comment by ready4sea** [comment]
@Alezanello, that sounds slightly better indeed, thanks.

However, that other issue, #3177, is stale 🤔
