### ISSUE TITLE
Not able to select available values

### ISSUE THREAD

**Issue by II-ricky-bobby-II** [FlutterFlow/flutterflow-issues#3822]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I press on available values and they deselect. 

### Expected Behavior

I should be able to select available values.

### Steps to Reproduce

1. Create component.
2. Create variable for Max Height
3. Attempt to get "Number of Items" 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slPLl5YxJpbxK1brudcdB/T47JUQjRLswscpCbw4bIYj2P4lzY876PxJCXf28Y1Z6JU62p14KwNGPudnLIccBNRSrbp9xzKpQaw/heEWjaciTF7WwdkclM/9gFXas1J6VhRJNKvNvWEJn6k+qHPOUZCnbN4SzO3o8Sq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/45e4af9b-be20-46ea-9e12-773f58cccf21

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

This behavior just started with the new update.

**Comment by Alezanello** [comment]
<br>Hello,

Thank you for bringing this issue to our attention, and I'm sorry for any confusion caused. It seems this is related to a known issue with the new UI, where all items in the list are displayed as available, even when they aren’t. We’re currently working on a fix for this.

In the meantime, to resolve your issue, please note that the number of items should appear in red and should not be clickable. If you are trying to use the number of items in a condition, you should use a **Single Condition** where you can set parameters like "greater than" or "less than" for the number of items. However, it appears you may be trying to directly set the number of items in a condition that expects a **True/False** value (such as "Is set" or "Is not empty").

I hope this helps clarify the situation, and we appreciate your patience as we work on the UI fix. Let us know if you need further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e2a146da-adc4-443f-bb4a-9a3477271b79/98ed281b-306a-425f-8e28-54fbc8f5eaa6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMmExNDZkYS1hZGM0LTQ0M2YtYmI0YS05YTM0NzcyNzFiNzkvOThlZDI4MWItMzA2YS00MjVmLThlMjgtNTRmYmM4ZjVlYWE2IiwiaWF0IjoxNzI2NDkyMzUzLCJleHAiOjMzMjk3MDUyMzUzfQ.n57rgz0ByODyohGCDc2nsE37EpGG3UvP8FCWcozJLzM " alt="image.png" width="1059" height="534" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
