### ISSUE TITLE
Progress bar crashes on Android version

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#3823]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a progress bar in my project and it works weel on all tests and in the web published version, but it crashes on android version.
![Screenshot_3](https://github.com/user-attachments/assets/a74a8216-17d8-4d27-96b8-654f7d5ff987)

### Expected Behavior

It should work the same way in both versions
![WhatsApp Image 2024-09-13 at 17 16 00](https://github.com/user-attachments/assets/1de09d41-5f2e-4ca2-8a15-f08507fc667f)

### Steps to Reproduce

1-Go to petstars.app (the web version of the app)
2-Create an account in my app
3-Login
4-Go to perfil_conquistas page (clicking in the very right button in the navbar)
Take a look in the page and see the proper work
5-Go to google Play Store and search for the app com.bestbots.petstars (the draft version of the app)
6-go to perfil_conquistas page 
Take a look and see it crashing

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPHq2491xLRF+KnxYcFarygUCUMaXJ03lNUaaxQafJTdB4YMaczsXExVZOLjT3NXKEWJpGME06nVkYSeCew4ZE2sGapN+KVqdA3MIDq/aovRC7q0Y2smHeFVGkfC0LW03SRCD/tqL10j3U+uFvCsSnLrNOb6Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/46401058-01c5-4e9c-a25c-42d7dd668764)

### Environment

```markdown
FlutterFlow v4.1.89+ released September 10, 2024
Flutter version is 3.22.2- FlutterFlow version: 
- Platform: windows, Android
- Browser name and version: Chrome
- Operating system and version affected: Android
```

**Comment by ghost** [comment]
As an adittional information, I checked all compontents of the page and problem is in the progress bar, when I use dinamic value for the progress. When I leave it fixed (in the 0.5) it does NOT crash. The problem is with the dinamic determination of the progress bar, but only on the android version, in the web version is works nicely.

**Comment by paulperez-dev** [comment]
Hi @ricardocgs,

I’m sorry to hear you’re facing this issue. Could you please run your app in debug mode and share the logs with us? The exception details will help us pinpoint the problem more effectively.

Thank you for your help!

**Comment by ghost** [comment]
The debug mode doesnt show any errors, only on the smartphone it crashs. You have to run on android to see the issue

**Comment by ghost** [comment]
I am still waiting this solution to launch the app

**Comment by ghost** [comment]
After a lot of tests, I figured out what is the problem. Xano sends the dinamic values to the progress bar, it should be double, but in the cases which the number is 0 or 1, the android version was not accepting, as it was integer. For the web version it is not a problem.

I solved it by a workaround, inserted in the output of xano, if number is 0, change to 0.0001 and when is 1 change it to 0.9999 and it worked.
