### ISSUE TITLE
GitHub Push Error

### ISSUE THREAD

**Issue by Emvipy** [FlutterFlow/flutterflow-issues#3825]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I manage several projects in Flutterflow and I need to send the code to GitHub, but with this project I get an error.
With other projects it works fine.
Attached is Loom showing how to create the repo on GitHub and how I connect to FF. 
After 10 minutes trying to send the code I get the error that I attach in screenshot.

### Expected Behavior

That the code is correctly sent to the repository.

### Steps to Reproduce

Push to GitHub

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPHl05NOm9tJ7s7TbflvgScQH0c3TL03pu0bFEggGLbrBIYMacjOdhNtZ8O4T2NhKEWL/VEz0d7Oi972V/A7EweYRoRayqt6dQzMbH+/aoS3BqWaQ3ZSO5ljI26x06uJoiNvPttvLlJl7066J+e/Ej/DJo/7Zwh9f6PHaOI=

### Visual documentation

https://www.loom.com/share/d8ba7ecbacb847d58c2ebf7c81ab1b7f?sid=4ea26737-eeb9-4948-a172-e9e429148141
![Screenshot 2024-09-13 at 16 07 14](https://github.com/user-attachments/assets/c1347183-0fce-4613-8ce5-270dde530c0f)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 12, 2024
- Platform:Web and MacOs Desktop
- Browser name and version:Chrome Version 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: Mac OS Sonoma 14.6.1 (23G93)
```

**Comment by Alezanello** [comment]
Hello,

I’m sorry you're facing this issue. I reviewed your video and noticed that you followed all the steps perfectly to set it up, and everything in your project seems to be in order. Unfortunately, I’m not sure why this error is occurring.

In this specific track, we don’t have the necessary permissions to perform actions or gain deeper insights into individual projects. This track is focused on reproducible bugs from new, blank projects, and I wasn't able to replicate the issue you're experiencing.

I highly recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They’ll have the right tools and access to assist you further and help resolve this issue.

Thank you for your understanding, and I hope the support team can get this resolved for you quickly!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
