### ISSUE TITLE
Can't select the Database field from Actions

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#3826]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to select the firebase field as showing in the video but can't select it as it gets unselected right away. This seems to be happening with the new update.

### Expected Behavior

.

### Steps to Reproduce

1. Add Action - Query Collection
2. Select Firebase Field from Dropdown
3. It fails to select and gets unselected right away

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hvHl2ItOsdtY7pSJc8Ewlj0vJl87UI07m9VHUQ08J5zKB+wAYvf7P1FWTL3jT2xIJGKknjgd1vfqkYTtVPACFwqZfaZDzLlUZQnzczqWSoybCJCJfW1QJ+lmfxGH0rSNryJ/JtZaR0IO1GGbNuTIbC3YK4P4DFcRLcm1KdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

A Short video showing the bug
https://github.com/user-attachments/assets/6d4f5125-b850-43b1-9694-c0cbd4b16a4a

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 12, 2024
- Platform: MacOS + Chrome
- Browser name and version: Chrome
- Operating system and version affected: MacOS Sonoma, Chrome
```

**Comment by Alezanello** [comment]
Hello,

I’m sorry to hear you're experiencing this issue. This appears to be related to the new UI, which is currently showing all items in the list as available, even though they may not be. We’re aware of the problem and are actively working on a fix.

From the video you shared, it looks like you're trying to set the email, display name, and other fields into the **Reference**. Please note that the **Reference** field can only accept a **Document Reference** data type (in this case, the reference to a document), not individual values like emails or names.

I hope this helps clarify the issue. Please feel free to reach out if you need further assistance, and thank you for your patience as we resolve the UI problem.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6808f453-33b9-4015-abe9-3aec96c4173e/5bf7c748-d992-4eaf-a971-ccd0ea1bf34d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ODA4ZjQ1My0zM2I5LTQwMTUtYWJlOS0zYWVjOTZjNDE3M2UvNWJmN2M3NDgtZDk5Mi00ZWFmLWE5NzEtY2NkMGVhMWJmMzRkIiwiaWF0IjoxNzI2NDkyNjYwLCJleHAiOjMzMjk3MDUyNjYwfQ.asj_qrO3qr6xGQrU_MBBSBnLOUmv_1FmYQ4YdNZYErM " alt="image.png" width="896" height="811" />

**Comment by Dev-Muhammad-Junaid** [comment]
Oh Yes , I thought I closed this, Before that we have Red Indicator on the variable which was easier to know if this field can be mapped. But I got it now, Thanks
