### ISSUE TITLE
Non-existent error continues showing in project issues

### ISSUE THREAD

**Issue by ops-srgopalrao** [FlutterFlow/flutterflow-issues#3827]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is an image widget in my project which uses an asset that I created and uploaded but I see an error in the project issues which says "Missing Widget Asset: Widget uses non-existent asset "photo-1573497019940-1c28c88b4f3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60". Please re-upload or select a different asset, or run the project again to check if the issue persists."

The error is displayed even when I change the asset or remove it altogether. It doesn't cause any issues when I run the app but the error has been persistent for the last few weeks.

<img width="894" alt="Screenshot 2024-09-14 at 2 09 12 PM" src="https://github.com/user-attachments/assets/cab22b1a-e66e-40fa-8f58-c344f761dd54">

### Expected Behavior

The error message must not be displayed.

### Steps to Reproduce

1. Just open the project.
2. You should be able to see the error message.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhcjf7YZgodtJ176JcPlaliAvJn0cTb4RltZ+RRQhfbauP4ktO86kfhRLYtegf21IDmD/uEgzp8GNiobpM8cqYAWaRtU5woRXQQLNVlOQM76MPbiOYXBRO+hQJ3Kv57SJmxFAVddvZU4u6lymF/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

Like I said, you just have to start this project and you will see it in the project issues. I cleared cache and all that jazz, didn't work.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 12, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.6.1
```

**Comment by Alezanello** [comment]
Hello,

I’m sorry to hear you’re experiencing this issue. Have you tried removing the widget (without deleting the asset), then recreating it and setting it back up as it was? This can sometimes help resolve unexpected issues.

Let me know if that works or if you need further assistance!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
