### ISSUE TITLE
conditional action always nagivate to flase action chain

### ISSUE THREAD

**Issue by vebhapvt** [FlutterFlow/flutterflow-issues#3828]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in Dashborad screen i want to navigate to preference page incase Authenticated User profile country is not set. 
But even when country is set it always nagiavating on launching the app. 

### Expected Behavior

Expected is to Navigate only when the parameter is not set. 

### Steps to Reproduce

please refer to my app you can run it login and it will always navigate to Preference post login and need to set each time. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi87huIxOxMtF+KqAK+xWjiUXGUMdXOczitVEew4bCIj4ELMMPMneTE9VcOKzaHNcPmGGhkUCwfTqkvP9CfU7Nk2ZfKJNzrt6VhPPbH+7R5SKCLq8PndTM+VXC0DF54mokxRSBMpuWnAH3GauCeqtUT6Cf9qOYwx5e6fDbOY=

### Visual documentation

ITFTi87huIxOxMtF+KqAK+xWjiUXGUMdXOczitVEew4bCIj4ELMMPMneTE9VcOKzaHNcPmGGhkUCwfTqkvP9CfU7Nk2ZfKJNzrt6VhPPbH+7R5SKCLq8PndTM+VXC0DF54mokxRSBMpuWnAH3GauCeqtUT6Cf9qOYwx5e6fDbOY=

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): WidosMonterey 12.2.1
```

### Additional Information

sdf

**Comment by Alezanello** [comment]
Hello,

After reviewing your project, one possible solution might be changing the "AND" condition to "OR" in case **FirstTime** is already true, but the country has not been selected yet. This would ensure that it redirects to the **EditProfile** screen either way.

If that doesn’t resolve the issue, try running your project in test mode and checking the **Authenticated Users** variable in the Debug Panel. Sometimes, if the login process happens too quickly, the variables might not be fully set by the time the Dashboard is loaded. This can cause issues with conditions that rely on those variables.

To address this, you can add a short **wait** action (around 200–300ms) at the start of the Dashboard action chain. This will give the variables enough time to initialize before the conditions are evaluated, preventing any related issues.

Let me know if this helps, and feel free to reach out if you need further assistance!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by vebhapvt** [comment]
Yes you can close . The issue is resolved after I closed when I deleted the
condition and created it again .. seems some caching issue in flutterflow

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!

**Comment by vebhapvt** [comment]
Thank you and I will.
