### ISSUE TITLE
Listview stuttering and jumps when scrolling up

### ISSUE THREAD

**Issue by Joremando** [FlutterFlow/flutterflow-issues#3829]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a chat app so when I scroll up the chats start jumping and don't scroll smoothly.

### Expected Behavior

Same expected behavior when you scroll down within the chat.

### Steps to Reproduce

1. Create a listview
2. Add text, image, and video widgets for dynamic content
3. Try adding random content
4. Scroll up and see the problem

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeifHl34xOj70B0arIdMdolQMwGkQ5a7sviu5+FBQaI+P0EJYhdfTsZVVvYuqHe1ZIBlCiuE0JwfD6uezXCPoEBxOtfKU6zs59UxDvUmSRRraRCLWwfXYnTMVMfXGB05+J2hNTNfpZZVoTwzmIDdy+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/27add779-3928-49cf-a716-224556f262f3

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: MacOS
- Browser name and version: Chrome Version 128.0.6613.121 (Official Build) (arm64)
- Operating system and version affected: web, iOS & Android
```

### Additional Information

I need a smooth scrolling experience like in any chat app.

**Comment by itsstevenliu** [comment]
Check out an existing issue submitted and possible solution...
https://github.com/FlutterFlow/flutterflow-issues/issues/2683

**Comment by Joremando** [comment]
Thanks @itsstevenliu , it hasn't been fixed as far as I know. My chat has dynamic content, I'm not able to fix the height in any way.

**Comment by itsstevenliu** [comment]
Correct, it isn’t fixed per the other GitHub issue status (ie open). There are just hacky solutions offered by members. FF team do not recommend creating another issue if there is an existing issue

**Comment by Joremando** [comment]
Got it! What's the solution? I've tried every possible solution... and I still have a horrible experience when scrolling through the chat app.

I'm not asking for new features, I'm just asking for the current ones to work well. A chat is almost essential in every app these days. Please, FF!

**Comment by Alezanello** [comment]
<br>Hello!

I reviewed the video and understand the issue you're facing. After comparing the post with your app, it seems the main problem occurs when you have conditional builders inside the list. Another potential issue is not converting each item in the list into a component.

In your project, I noticed you have a column with four containers, each based on a conditional. I recommend using a **Conditional Builder** to ensure only the necessary content is built, which will improve performance. Additionally, converting each container into a **Component** will offload the initialization process from the page to the component itself, further enhancing performance when displaying the items.

There are more helpful tips like this in the GitHub issue mentioned by @itsstevenliu in the comment above, so I’d suggest checking that out as well.

Let me know if you have any further questions or need more assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/13c5f713-7fc4-4e6a-9e0e-b8097b96e693/1cd532f5-f132-4e24-ba3e-c0501717e4bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xM2M1ZjcxMy03ZmM0LTRlNmEtOWUwZS1iODA5N2I5NmU2OTMvMWNkNTMyZjUtZjEzMi00ZTI0LWJhM2UtYzA1MDE3MTdlNGJiIiwiaWF0IjoxNzI2NDk0NjI1LCJleHAiOjMzMjk3MDU0NjI1fQ.CuYM7UvbtBEWRBaPYxRh9fJi3MZPTb5J1v5xw5CBCV0 " alt="image.png" width="350" height="216" />

**Comment by Joremando** [comment]
@Alezanello Thanks for your suggestion, I'll check what you explained me and let you know if the experience has improved. The developer and I have been struggling with this for weeks.

**Comment by Joremando** [comment]
@Alezanello We followed all your recommendations and the problem is still there. Can you please review my project again? What am I missing now?

**Comment by Joremando** [comment]
@Alezanello We put almost everything in containers, min height at 100, 50, just tried all the solutions discussed in the other post and still nothing, scrolling experience is annoying to say the least.

**Comment by Joremando** [comment]
@Alezanello Any solution?

**Comment by Joremando** [comment]
@Alezanello It's been 1 week, please.

**Comment by Joremando** [comment]
@Alezanello Hello? At least one word so we know what's going on please.

**Comment by Alezanello** [comment]
Hello!

I apologize for the delayed response. We're actively tracking this issue internally to explore ways to enhance the performance of the infinite scroll in the list view.

In the meantime, have you had a chance to try this solution? [Link to issue](https://github.com/FlutterFlow/flutterflow-issues/issues/2683#issuecomment-2209420312)

**Comment by Joremando** [comment]
Hi, @Alezanello We have tried all the possibilities. It's strange because in 1:1 chat it works perfectly. We don't know what else to try.  We applied "custom loader" to every block, one yes not the other, all with loaders... well, you got the idea.

**Comment by Alezanello** [comment]
Hello again,

I apologize for the delayed response. I’ve been working to get this issue reviewed by the engineering team. It appears that this is more of a Flutter issue than a FlutterFlow-specific one, related to how things are rendered. I'll be closing this ticket as a duplicate to streamline tracking and focus our efforts on the main issue.

We’ll continue to explore ways to resolve this, along with other users facing the same challenge, in the main thread here: [GitHub Issue #2683](https://github.com/FlutterFlow/flutterflow-issues/issues/2683).

Thank you for your understanding, and feel free to reach out if you have any further questions!
