### ISSUE TITLE
Number Formatting issue

### ISSUE THREAD

**Issue by masterboltdev** [FlutterFlow/flutterflow-issues#383]
Found a small issue when combining text with currency number formatting.  (I'm US) It added the decimal, comma and $ but if the argument variable didnt have 2 decimal places, it returned 1.  For example: 1.7 should be $1.70.  Returns as $1.7.  I believe the reason is that you left the call to simpleCurrency() out - only calling NumberFormat().

I'm using this as a custom function as a workaround.

String formatAsCurrency(double amt) {
  final formatCurrency = new NumberFormat.simpleCurrency();
  return formatCurrency.format(amt);
}

**Comment by yoheisoito** [comment]
Hi @masterboltdev,
Thanks for raising this issue. @asmengistu: I've replicated this and can confirm this as a bug. 

We will try to incorporate the fix on our next update.
Thank you very much for point this out!

**Comment by masterboltdev** [comment]
thanks!

Dave
