### ISSUE TITLE
Disconnection of firebase database

### ISSUE THREAD

**Issue by GregKoziol1** [FlutterFlow/flutterflow-issues#3831]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't deploy firebase rules, indexes etc. The firestore seems to be general disconnected for the project.
<img width="896" alt="Zrzut ekranu 2024-09-15 o 20 23 55" src="https://github.com/user-attachments/assets/15711233-f3db-470d-8f3c-2ce2423ff189">

### Expected Behavior

Firebase connection working.
Ability deploy rules and to sync new changes with the firebase.

### Steps to Reproduce

Go to the project.
Try to connect to regenerate config file.
Look that there is a connection and setup is complete (above)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40uPiCz7d+o9dH4szuU/dumgogHDs7a7g309VRaCosfZT2BLMcec/RVERoXd/kY29UMWeGkWoW0NmNvtrDNe0CAE6cfYBezpd2Wg/MWk6RVKWVFJWgSEEkO9xgG3af36aNvB4nOutvWmQgwzqmGem/dDLYJOL6ITAwDq/LZO4=

### Visual documentation

<img width="783" alt="Zrzut ekranu 2024-09-15 o 20 24 53" src="https://github.com/user-attachments/assets/d1f81703-98fd-43df-8216-575b29a5df6d">
<img width="338" alt="Zrzut ekranu 2024-09-15 o 20 39 29" src="https://github.com/user-attachments/assets/7b025a52-64dc-4a7f-9ade-a5499bdbae06">

### Environment

```markdown
- FlutterFlow version: 4.1.89+
- Platform: 3.2.22
- Browser name and version: Chrome
- Operating system and version affected: ios
```

### Additional Information

the recommendation from #3744 applied, situation hasn't changed

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. From the bug report code you shared, it looks like you’re working from a branch other than the main one. Please note that some actions are restricted in branches outside of the main branch.

I recommend switching to the main branch or merging your changes into it to see if you can successfully deploy the rules and indexes from there.

Let me know if that helps or if you need further assistance!

**Comment by GregKoziol1** [comment]
Hi, thank you for the prompt analysis. Unfortunately due to my lack of knowledge and some actions I did meaning closing previous branches from which I created the current branch I'm working on "version_1_8" I have no option to merge to main branch.  Is there a way to merge the 1_8 to main branch or create main branch from 1_8? In simple words I can move back to main branch - to many changes/bug fixes etc. were made in the branches. Many thanks for your support. Btw I made an experiment and created new branch based on the main branch - the issue with firebase is also visible on this newly created branch - so I assume the problem will be still visible.

**Comment by Alezanello** [comment]
I’m sorry to hear that you’re unable to merge **version_1_8** into the main branch. Unfortunately, in this track, we don’t have the necessary permissions to attempt the merge or identify why it’s not working. I highly recommend reaching out to our support team via the in-app chat or by emailing support@flutterflow.io. They have the appropriate tools to assist you with the merge.

Regarding the new branch you created, as mentioned earlier, branches other than the main one don’t have the necessary permissions to deploy rules or indexes. Any Firebase-related actions can only be triggered from the main branch.

I hope this helps, and please let me know if you have any further questions!

**Comment by GregKoziol1** [comment]
many thanks for the information, I will contact flutterflow support
