### ISSUE TITLE
Upgrade Flutterflow dependency 'url_launcher_ios' for Xcode 16

### ISSUE THREAD

**Issue by jryankennedy** [FlutterFlow/flutterflow-issues#3834]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using the new Xcode 16, which releases tomorrow, and am getting an error preventing from using Local Run for my app. 

I did some digging and I narrowed it down to the 'url_launcher_ios' needing to be updated to 6.3.1

Error:

/Users/jordankennedy/.pub-cache/hosted/pub.dev/url_launcher_ios-6.2.5/ios/Classes/Launcher.swift:22:1: error: type
'UlApplication' does not conform to protocol 'Launcher' extension UlApplication: Launcher{}
UlKit.UlApplication:24:15: note: candidate has non-matching type '(URL, [UlApplication.OpenExternalURLOptionsKey :
Any], (@MainActor @Sendable (Bool) → Void)?) → Void'
open fun open(_ url: URL, options: [UlApplication.OpenExternalURLOptionsKey : Any] = [:], completionHandler
completion: (@MainActor @Sendable (Bool) → Void)? = nil)
/Users/jordankennedy/.pub-cache/hosted/pub.dev/url_launcher_ios-6.2.5/ios/Classes/Launcher.swift:22:1: note: add
stubs for conformance extension UlApplication: Launcher {}

Potential solution: 
https://github.com/flutter/flutter/issues/151467

### Expected Behavior

Flutterflow apps should compile in Xcode 16

### Steps to Reproduce

Try running any app that used the 'url_launcher_ios' dependency in Xcode 16.

See:
https://github.com/flutter/flutter/issues/151467

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz8jf5c1NochE16XxKcEwuCIwGUwbUOc7j9VEGAsjCePrOpYDOuPeUElpWOqHeglceFX9kXEzwfTKjdnUG/knOROVQbZgz5ZLUxDgUketaYy0OpaOP3QnTMRQfR2u17WRpxJ5HMtpS1Zk3DuTfN6AY3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="824" alt="Screenshot 2024-09-15 at 4 01 23 PM" src="https://github.com/user-attachments/assets/fa8ab621-641a-49c1-8a25-552dc1e049c4">
<img width="763" alt="Screenshot 2024-09-15 at 3 58 07 PM" src="https://github.com/user-attachments/assets/83d10dfe-2bb1-4cfd-9e0a-0831e1c18a2c">

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: Mac
- Browser name and version: N/A
- Operating system and version affected: MacOS Sequoia / Xcode 16
```

**Comment by asomervell** [comment]
This fixes the issue in projects outside of FlutterFlow, has made using FlutterFlow impossible.

**Comment by paulperez-dev** [comment]
Hi @jryankennedy,

Thank you for flagging this! I’ll inform the engineering team so they can work on a fix as soon as possible.

**Comment by pedromamare** [comment]
Thank you! Looking forward to it.

**Comment by rickybrown** [comment]
Glad to stumble across this so I didn't waste any more time troubleshooting my environment since Xcode auto-updated. I've previously requested that requested url_launcher be upgraded to 6.3 for other reasons that were blocking me, and I assumed it wouldn't happen any time soon but now with not being able to run with Xcode 16 it looks like we have no choice but to move the url_launcher version along :)

Thankful for the team working on this, will be watching for updates to test as soon as its available

**Comment by geret1** [comment]
This is how I solved it.

Create `pubspec_overrides.yaml` with the following packages
```
dependency_overrides:
  url_launcher_ios: ^6.3.1
  devtools_app_shared: ^0.2.2
  devtools_extensions: ^0.2.1
  pointer_interceptor: ^0.10.0
```

Then I need to set "**Yes**" into Xcode "Allow Non-modular Includes in Framework Modules" to make it work or edit Podfile with the following snippet
```
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
```

P.D.: Also for Firebase users it would be good to add in the beggining of the Podfile to manage better Firebase versioning
```
$FirebaseSDKVersion = '10.25.0'
```

**Comment by MamadAsap** [comment]
Hi ! Same issue for me I can no longer use local run :( . @geret1 these actions can be done from Flutterflow UI ?

**Comment by geret1** [comment]
> Hi ! Same issue for me I can no longer use local run :( . @geret1 these actions can be done from Flutterflow UI ?

Unfortunately no. I made all this changes on VSCode plus XCode :(

**Comment by guidomarangoni** [comment]
> This is how I solved it.
> 
> Create `pubspec_overrides.yaml` with the following packages

Ciao,
I have the same problem...in which directory did you create pubspec_overrides.yaml file?
Where is "Allow Non-modular Includes in Framework Modules" option in XCode?
Thank you

**Comment by geret1** [comment]
> > This is how I solved it.
> > Create `pubspec_overrides.yaml` with the following packages
> 
> Ciao, I have the same problem...in which directory did you create pubspec_overrides.yaml file? Where is "Allow Non-modular Includes in Framework Modules" option in XCode? Thank you

At same level that `pubspec.yaml` and the XCode attached screenshot.

<img width="1149" alt="Screenshot 2024-09-18 at 12 41 31" src="https://github.com/user-attachments/assets/31e7e70e-d837-4abe-a5ab-e0b4168927c2">

**Comment by PanSalut** [comment]
Same issue here right now.

**Comment by NDM01** [comment]
Same issue here.

**Comment by guidomarangoni** [comment]
Works!
Thank you @geret1 👍

**Comment by gianniginom** [comment]
Same issue !

**Comment by MamadAsap** [comment]
Hi @guidomarangoni , what's in your pubsec_overrides file? 
Just the 4 dependencies?  How is it structured ?

**Comment by guidomarangoni** [comment]
Ciao @MamadAsap ,
exactly as indicated by @geret1 

> Create pubspec_overrides.yaml with the following packages

```
dependency_overrides:
  url_launcher_ios: ^6.3.1
  devtools_app_shared: ^0.2.2
  devtools_extensions: ^0.2.1
  pointer_interceptor: ^0.10.0

```

**Comment by oleksii-it** [comment]
Same issue. Does anybody have solution via FF UI?

**Comment by lemmen6** [comment]
Same issue.

**Comment by ken-umamii** [comment]
Same issue too.

**Comment by dmk23** [comment]
Running into the same issue

I have added `url_launcher_ios: ^6.3.1` via FF UI (custom action dependencies) and now this is the error:

```
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/1m/kgwq7_rn1sl6zdrswfw58fww0000gn/T/flutter_tools.Kr12uU/flutter_ios_build_temp_dir7SYYaf/temporary_xcresult_bundle

    /Users/dmitriykruglyak/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.1/ios/url_launcher_ios/Sources/url_launcher_ios/URLLauncherPlugin.swift:22:26: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
        UIApplication.shared.keyWindow?.rootViewController?.topViewController
                             ^
    /Users/dmitriykruglyak/.pub-cache/hosted/pub.dev/sign_in_with_apple-4.3.0/ios/Classes/SignInWithAppleError.swift:99:13: warning: switch must be exhaustive; this is an error in the Swift 6 language mode
                switch code {
                ^
    /Users/dmitriykruglyak/.pub-cache/hosted/pub.dev/sign_in_with_apple-4.3.0/ios/Classes/SignInWithAppleError.swift:99:13: note: add missing case: '.matchedExcludedCredential'
                switch code {
                ^
```

Does `sign_in_with_apple` need to be upgraded too?

**Comment by lemmen6** [comment]
I hope we can increase the priority on this issue, as all iOS development is halted.

**Comment by geret1** [comment]
> I hope we can increase the priority on this issue, as all iOS development is halted.

Agree :( 

Investing at least 3 days for a critical, or high-prio issue (because some service levels cannot be offered, i.e. local testing) requires a clear communication about it.

I would invest more time with a proper priority tagging for customers, define some kind of service levels and escalation procedures. On the tech side, FF should provide more provide more freedom from FF UI to edit/override low-level parameters such as Podfile or pubspec.yaml.

**Comment by rikyscara** [comment]
> > This is how I solved it.
> > Create `pubspec_overrides.yaml` with the following packages
> 
> Ciao, I have the same problem...in which directory did you create pubspec_overrides.yaml file? Where is "Allow Non-modular Includes in Framework Modules" option in XCode? Thank you

Hi, be sure to select `All` in Build Settings. I had `Basic` selected by default and the setting wasn't s showing up

![Screenshot 2024-09-19 at 09 39 36](https://github.com/user-attachments/assets/887b6609-261f-44a2-8e83-33cd0b1049d6)

**Comment by Coder-Pranav** [comment]
> This is how I solved it.
> 
> Create `pubspec_overrides.yaml` with the following packages
> 
> ```
> dependency_overrides:
>   url_launcher_ios: ^6.3.1
>   devtools_app_shared: ^0.2.2
>   devtools_extensions: ^0.2.1
>   pointer_interceptor: ^0.10.0
> ```
> 
> Then I need to set "**Yes**" into Xcode "Allow Non-modular Includes in Framework Modules" to make it work or edit Podfile with the following snippet
> 
> ```
> post_install do |installer|
>   installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
>     configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
>   end
> end
> ```
> 
> P.D.: Also for Firebase users it would be good to add in the beggining of the Podfile to manage better Firebase versioning
> 
> ```
> $FirebaseSDKVersion = '10.25.0'
> ```
Just a question but whenever we try running locally the changes we made will be overwritten right?

**Comment by halituzun** [comment]
aynı sorun :(

**Comment by geret1** [comment]
> > This is how I solved it.
> > Create `pubspec_overrides.yaml` with the following packages
> > ```
> > dependency_overrides:
> >   url_launcher_ios: ^6.3.1
> >   devtools_app_shared: ^0.2.2
> >   devtools_extensions: ^0.2.1
> >   pointer_interceptor: ^0.10.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I need to set "**Yes**" into Xcode "Allow Non-modular Includes in Framework Modules" to make it work or edit Podfile with the following snippet
> > ```
> > post_install do |installer|
> >   installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
> >     configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
> >   end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > P.D.: Also for Firebase users it would be good to add in the beggining of the Podfile to manage better Firebase versioning
> > ```
> > $FirebaseSDKVersion = '10.25.0'
> > ```
> 
> Just a question but whenever we try running locally the changes we made will be overwritten right?

From `pubspec_overrides.yaml` no, your changes will remain because it is out of scope FF but not for Podfile. I have requested to FF team this considerations [here](https://github.com/FlutterFlow/flutterflow-issues/issues/3844).

**Comment by vianneypercq** [comment]
Hi there 👋 
I'm not sure but do I have the same issue?

I am using the new Xcode 16 and I can't make a local run neither on a real device nor on the simulator.
I have done a new clean Xcode installation and I have deleted all the files in the IOS folder to let Flutterflow generate new ones by launching local run. 
All Doctor Output items are green.

Here is the log screenshot:

![CleanShot 2024-09-19 at 13 11 32@2x](https://github.com/user-attachments/assets/621d1142-a60f-474d-8dfd-9e60f7eb7662)

Is-it the same issue?
Thanks for helping.

**Comment by lemmen6** [comment]
@vianneypercq yes, this is the same issue.

**Comment by smplfy** [comment]
Same, completely blocked.

**Comment by alexanderchw** [comment]
Same here....

**Comment by max-h-silverman** [comment]
I ran into this issue trying to build on a physical device in xcode but I was able to run local test (Chrome) and on a physical Android device. The mobile deployment to App Store worked as well. In case that's helpful to anyone...

**Comment by jryankennedy** [comment]
Could we get an Engineering update on when they estimate this will be fixed and pushed to production?

**Comment by timdcochran** [comment]
> This is how I solved it.
> 
> Create `pubspec_overrides.yaml` with the following packages
> 
> ```
> dependency_overrides:
>   url_launcher_ios: ^6.3.1
>   devtools_app_shared: ^0.2.2
>   devtools_extensions: ^0.2.1
>   pointer_interceptor: ^0.10.0
> ```
> 
> Then I need to set "**Yes**" into Xcode "Allow Non-modular Includes in Framework Modules" to make it work or edit Podfile with the following snippet
> 
> ```
> post_install do |installer|
>   installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
>     configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
>   end
> end
> ```
> 
> P.D.: Also for Firebase users it would be good to add in the beggining of the Podfile to manage better Firebase versioning
> 
> ```
> $FirebaseSDKVersion = '10.25.0'
> ```

This was great help, thanks!

In addition to the above, I had to disable Crashlytics and then Performance Monitoring under Firebase setup as both were producing errors like this:

 /Users//Library/Application Support/io.flutterflow.prod.mac//build/ios/Debug-iphonesimulator/firebase_performance/firebase_performance.framework/Headers/FLTFirebasePerformancePlugin.h:5:9: error: include of non-modular header inside framework module 'firebase_performance.FLTFirebasePerformancePlugin': '/Users//Library/Application Support/io.flutterflow.prod.mac//ios/Pods/Headers/Public/Firebase/Firebase.h' [-Werror,-Wnon-modular-include-in-framework-module]
        5 | #import <Firebase/Firebase.h>
          |         ^
    1 error generated.

But once disabled, local run is working so happy days!

**Comment by sebointruz** [comment]
What helped me:
1. Update flutter to [3.24.3] along with dart 3.5.3
2. Update firebase_* packages to latest if you have
3. Update cocapods
4. pod: deintegrate, repo update, setup, install 


Hope it will help also to you.

**Comment by geret1** [comment]
> What helped me:
> 
> 1. Update flutter to [3.24.3] along with dart 3.5.3
> 2. Update firebase_* packages to latest if you have
> 3. Update cocapods
> 4. pod: deintegrate, repo update, setup, install
> 
> Hope it will help also to you.

I think is not related with the current issue.

I've also seen a relative distance between latest firebase packages and those that FF uses, pubspec and pods, dependency management is not good in FF I guess.

**Comment by lemmen6** [comment]
I suppose this isn't an easy fix as FlutterFlow is not providing any updates and letting us wait for 5 days!! Platform broken?

**Comment by InceeChun** [comment]
same issue

**Comment by abuzzahra** [comment]
perhaps they are busy with FFDC

**Comment by kellvembarbosa** [comment]
> I suppose this isn't an easy fix as FlutterFlow is not providing any updates and letting us wait for 5 days!! Platform broken?

I believe more that they want to comply with their roadmap, because on the adapty docs page it says that the release of flutterflow 5.0 will be on Tuesday:
![CleanShot 2024-09-20 at 14 17 28@2x](https://github.com/user-attachments/assets/c66a0e83-0583-4dbe-9fdf-aaca3b42bcf9)

You can check it out: https://adapty.io/docs/flutterflow

I just think it's cruel to make people wait and keep posting videos on YouTube with the broken platform, our app is on the deadline until the 22nd and we will be removed and we won't be able to update the app because of that;

Anyway,
I love FlutterFlow, but I think this time they stepped on the ball with my team :( @FlutterFlowEng

**Comment by webinti** [comment]
Hello same issue here.

I have reinstalled all Xcode, i thought It was something broken in my Mac, but apparently no. Just a FF bug.

Will stay updated

**Comment by caneyglobal** [comment]
same problem here, whats the finally soluction?,  flutterflow team repair that?

**Comment by tensoralex** [comment]
Here is another temporary workaround to get everything building on IOS (including firebase_performance and crashlytics) - install XCode 15.4 alongside with XCode 16.

1. Download Xcode 15.4 from https://developer.apple.com/download/applications/
2. Rename it and put into Application folder (in my case I named it Xcode_15.4 and moved it into Applications folder).
3. Switch to Xcode 15 as active `sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer`
4. Verify that it switched 
```
xcode-select -p
/Applications/Xcode_15.4.app/Contents/Developer
```

5. Cleanup and reinstall pods:
```
flutter clean
flutter pub get
cd ios
rm -rf Pods && rm -rf Podfile.lock && pod cache clean --all 
pod install --repo-update
```

6. Go back to the parent folder and try to build/run it:
```
cd ..
flutter run --release -d <your IOS device>
```
For now it seems to work.

P.S. I hope that FlutterFlow team updates dependencies soon, especially Firebase SDK versions. However, there are quite a few versions of FIrebase packages are currently behind. So I suspect that will be not straightforward. XCode 16 made quite a few changes as I am reading. I hope their FF 5.0 release next week would fix this.

**Comment by kellvembarbosa** [comment]
> Here is another temporary workaround to get everything building on IOS (including firebase_performance and crashlytics) - install XCode 15.4 alongside with XCode 16.
> 
> 1. Download Xcode 15.4 from https://developer.apple.com/download/applications/
> 2. Rename it and put into Application folder (in my case I named it Xcode_15.4 and moved it into Applications folder).
> 3. Switch to Xcode 15 as active `sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer`
> 4. Verify that it switched
> 
> ```
> xcode-select -p
> /Applications/Xcode_15.4.app/Contents/Developer
> ```
> 
>  5. Cleanup and reinstall pods:
> 
> ```
> flutter clean
> flutter pub get
> cd ios
> rm -rf Pods && rm -rf Podfile.lock && pod cache clean --all 
> pod install --repo-update
> ```
> 
>  6. Go back to the parent folder and try to build/run it:
> 
> ```
> cd ..
> flutter run --release -d <your IOS device>
> ```
> 
> For now it seems to work.
> 
> P.S. I hope that FlutterFlow team updates dependencies soon, especially Firebase SDK versions. However, there are quite a few versions of FIrebase packages are currently behind. So I suspect that will be not straightforward. XCode 16 made quite a few changes as I am reading. I hope their FF 5.0 release next week would fix this.

This worked well for me, without any change in the project, just follow the step by step that is success!

  ❤️💙

Thanks @tensoralex

**Comment by webinti** [comment]
Did you notice that images in assets do not display correctly on Local Run? I have always Exception Asset not found.

![Capture d’écran 2024-09-21 à 03 42 08](https://github.com/user-attachments/assets/1c727cca-f753-464b-8b4c-e37a2f00f169)
![Capture d’écran 2024-09-21 à 03 42 37](https://github.com/user-attachments/assets/e27e8768-eb09-4ea3-8b76-741c5feee5ac)

**Comment by lemmen6** [comment]
@webinti let's keep it on topic!! for your problem is an easy fix, for this isn't clearly!!

**Comment by webinti** [comment]
no problem, i found the fix :)

**Comment by cadufreeela** [comment]
Funny that new features get all the attention but getting the basic support for me ios is put in backlog. Hard to rely on a platform that should treat this as P1 Sev 1

**Comment by iamnabink** [comment]
Don't worry these issue can be solved with:

1- Upgrade your project to recent flutter stable
2- Upgrade your dependencies if some new xcode 16 related issues with
```
dependency_overrides:
  url_launcher_ios: ^6.3.1
# or some giturl
```
4- follow @rikyscara 's answer [set "Yes" into Xcode [Build settings] "Allow Non-modular Includes in Framework Modules" to make it work]
3- Clean Project and update pod dependencies

**Comment by geret1** [comment]
> Don't worry these issue can be solved with:
> 
> 1- Upgrade your project to recent flutter stable 2- Upgrade your dependencies if some new xcode 16 related issues with
> 
> ```
> dependency_overrides:
>   url_launcher_ios: ^6.3.1
> # or some giturl
> ```
> 
> 4- follow @rikyscara 's answer [set "Yes" into Xcode [Build settings] "Allow Non-modular Includes in Framework Modules" to make it work] 3- Clean Project and update pod dependencies

Worth mentioning that dependency upgrade should be placed on `pubspec_overrides.yaml` otherwise is not gonna work because FF will replace on any potential update. 

Same with Xcode but in this case you need to freeze your code or change it again on any FF update.

Downgrading Xcode (proposed by @tensoralex) seems the "most feasible" option taking into account that here there is no good options because all we're just tweaking our systems to make FF work. Sounds a bit crazy yes taking into consideration that Xcode 16 was launched 10th June...

Hope that FF 5.0 fix all these issues but time is only increasing the issues (i.e. `firebase_*` dependencies)

**Comment by cadufreeela** [comment]
Agree, it's just a bandaid fix, however this should be fixed asap as Apple
review process tests in ios 18 already so FF needs to be compliant with ios
18

**Comment by abuzzahra** [comment]
<img width="317" alt="Screenshot 2024-09-23 at 3 40 24 PM" src="https://github.com/user-attachments/assets/dcf18019-bc7c-43f6-89fb-b77446c0ea41">
 
 this week they will release new update

**Comment by geret1** [comment]
Thanks @abuzzahra for the "out of the record" update. However, I would appreciate that FF team answer the current issue with a short explanation of the implemented fix. Otherwise, why do they need this repo?

**Comment by lemmen6** [comment]
Thank you for the fix but I cannot understand why it was not possible to update us the status on this issue right here? (and also to be fair, xCode 16 is out since June.. it’s time to reflect at FF HQ..)

**Comment by vianneypercq** [comment]
Issue fixed! Thanks FF Team.

**Comment by geret1** [comment]
Thanks for the fix team! However, I would want to keep an eye on `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` as exposed on https://github.com/firebase/flutterfire/issues/13323#issuecomment-2368991665 and maybe start thinking and working on more granular proposal like this https://github.com/firebase/flutterfire/issues/13323#issuecomment-2370463105

what do you think @leighajarett ? I can create a new issue from my own side.

**Comment by tensoralex** [comment]
Hmm, FF5 didn't fix it for me. I dont see any files for ios even modified after FF5 update. 
Are there any particular actions to activate the fix?

**Comment by NDM01** [comment]
Also for me didn't fix, I am facing issues and the logs always ask this "note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')" and sometimes takes 4/5 times to run...

**Comment by sbis04** [comment]
@tensoralex @NDM01 sorry to hear that the fix didn't work for you, mind sharing a bug report code from the project you are facing iOS compilation issues?

**Comment by YannickDesjardinsHapbee** [comment]
> --repo-update

I did this, but I still get the error.

When I do my pod install  --repo-update I noticd that it is installing 0.0.1

![image](https://github.com/user-attachments/assets/185ace05-7d5f-48f2-8cc3-dd1ca248d488)

But flutter pub get got the right one:
! url_launcher_ios 6.3.1 (overridden in ./pubspec_overrides.yaml)

**Comment by tensoralex** [comment]
> @tensoralex @NDM01 sorry to hear that the fix didn't work for you, mind sharing a bug report code from the project you are facing iOS compilation issues?

We were able to resolve this issue on our own. One needs to get a "clean" iOS folder from the FF (code download) (after the FF5 release) and disable any package of file overrides if they were present for IOS. 
After that, the IOS build on Xcode 16 was successful from FF5.
(if you do additional downstream modifications to the XCode project outside FF (as we do) - you have to reapply any customizations back after it builds on pure FF code )

**Comment by byrondowns** [comment]
I have this issue too, is this only way around this the workaround to force install url_launcher 6.3.1 or is this meant to be properly fixed, i can't tell in this thread

**Comment by conformtojesus** [comment]
I'm having the same issue too since upgrading my MacBook, I've upgraded to the latest Flutterflow but it still doesn't work when I try to local run from the app. This is just part of the error code, the full thing is very long.

Could not build the precompiled application for the device.
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/xs/6k0956fx68n8d9xfhgfvzgnr0000gn/T/flutter_tools.nUYuwX/flutter_ios_build_temp_dirYp2jHF/temporary_xcresult_bundle

    /Users/daleoshea/.pub-cache/hosted/pub.dev/sign_in_with_apple-4.3.0/ios/Classes/SignInWithAppleError.swift:99:13: warning: switch must be exhaustive; this is an error in the Swift 6 language mode
                switch code {
                ^
    /Users/daleoshea/.pub-cache/hosted/pub.dev/sign_in_with_apple-4.3.0/ios/Classes/SignInWithAppleError.swift:99:13: note: add missing cases
                switch code {
                ^
    /Users/daleoshea/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.1/ios/url_launcher_ios/Sources/url_launcher_ios/URLLauncherPlugin.swift:22:26: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
        UIApplication.shared.keyWindow?.rootViewController?.topViewController

**Comment by vdevc** [comment]
Same problem here. Problem appeared today as yesterday was working pretty fine. 
I only tried to setup run on device

FlutterFlow App `5.0.7`
XCode `16`

```
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `10.25.0`
firebase_analytics: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
Downloading dependencies
Installing FMDB (2.7.12)
Installing Firebase (10.25.0)
Installing FirebaseABTesting (10.29.0)
Installing FirebaseAnalytics (10.25.0)
Installing FirebaseCore (10.25.0)
Installing FirebaseCoreExtension (10.25.0)
Installing FirebaseCoreInternal (10.29.0)
Installing FirebaseFirestore (10.25.0)
Installing FirebaseFirestoreAbseilBinary (1.2024011601.0)
Installing FirebaseFirestoreBinary (10.25.0)
Installing FirebaseFirestoreGRPCBoringSSLBinary (1.62.1)
Installing FirebaseFirestoreGRPCCPPBinary (1.62.1)
Installing FirebaseFirestoreGRPCCoreBinary (1.62.1)
Installing FirebaseFirestoreInternalBinary (10.25.0)
Installing FirebaseInstallations (10.29.0)
Installing FirebasePerformance (10.25.0)
Installing FirebaseRemoteConfig (10.29.0)
Installing FirebaseRemoteConfigInterop (10.29.0)
Installing FirebaseSessions (10.29.0)
Installing FirebaseSharedSwift (10.25.0)
Installing Flutter (1.0.0)
Installing GoogleAppMeasurement (10.25.0)
Installing GoogleDataTransport (9.4.1)
Installing GoogleUtilities (7.13.3)
Installing PromisesObjC (2.4.0)
Installing PromisesSwift (2.4.0)
Installing firebase_analytics (10.10.5)
Installing firebase_core (2.31.0)
Installing firebase_performance (0.9.4-5)
Installing flutter_barcode_scanner (2.0.0)
Installing flutter_secure_storage (6.0.0)
Installing leveldb-library (1.22.5)
Installing nanopb (2.30910.0)
Installing path_provider_foundation (0.0.1)
Installing pointer_interceptor_ios (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sqflite (0.0.2)
Installing url_launcher_ios (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 13 dependencies from the Podfile and 39 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Running pod install...                                           1,875ms
Running Xcode build...                                          
Xcode build done.                                           29.6s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:BF3D24A8-FA84-4B94-B284-3C744C9AC920, OS:18.0, name:iPhone 16 Pro }
    { platform:iOS Simulator, id:BF3D24A8-FA84-4B94-B284-3C744C9AC920, OS:18.0, name:iPhone 16 Pro }
    ** BUILD FAILED **

```

**Comment by Rocke1001feller** [comment]
> Don't worry these issue can be solved with:
> 
> 1- Upgrade your project to recent flutter stable 2- Upgrade your dependencies if some new xcode 16 related issues with
> 
> ```
> dependency_overrides:
>   url_launcher_ios: ^6.3.1
> # or some giturl
> ```
> 
> 4- follow @rikyscara 's answer [set "Yes" into Xcode [Build settings] "Allow Non-modular Includes in Framework Modules" to make it work] 3- Clean Project and update pod dependencies

You are the man, save my life.

**Comment by sbis04** [comment]
Mainly this issue was caused if you have some custom code that's using a different version of `url_launcher_ios` (which might be overriding our default version). Hope this is solved for everyone, closing this for now!

**Comment by HaShingThang** [comment]
@geret1

**Comment by HaShingThang** [comment]
@geret1 
Is this the same issue I'm facing? I'm using FVM with Flutter 3.13.0 and url_launcher: ^6.2.4. How can I fix this in this version?

![Image](https://github.com/user-attachments/assets/e684df57-52b2-495e-af79-e96e5098c60d)
