### ISSUE TITLE
Button Action Flow Does Not Work After Supabase Auth Create Account Action

### ISSUE THREAD

**Issue by morethanlikelyMatt** [FlutterFlow/flutterflow-issues#3835]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am creating a simple page to create an account. When clicking the button to create account the account is created on the Supabase side but no other actions in the button's action flow work eg. navigate to page or alert dialog. The navigate action does not work with "Navigate Automatically" selected or deselected.

### Expected Behavior

Click button to create account and it would perform any following actions in the action flow eg. navigate to page or alert dialog. 

### Steps to Reproduce

1. Add supabase as authentication
2.  Create Page
3. add button 
4. add Auth Create Account action
-Email as auth provider
5. Add navigate to action to button action flow
6. select any other page
7. Test Page
8. enter email and password
9. click button to create account

Note: This also didn't work with "Navigate Automatically" selected

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olcrq2492rsBE7ZPuacFKnSQWC0gkR4IN18pOGDsdF4iuPOxzac6lXxdWTtOgY29tKEWJ/UIBpMmNvs7xFu4oAE+CbLZGzpdyVzr/Ul6/aoSNDZeRdn9STPJhfmXC35mnuiJ7CPVeV3wb1EOQDN69VnXqNOL7Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/2fcca595-5a0b-4b9d-8600-fb2eb059d37b)
![image](https://github.com/user-attachments/assets/edb76ffc-0a06-400a-86e9-4ff3b798db34)
![image](https://github.com/user-attachments/assets/f3bb1495-1823-40e1-aeee-93e9a3b9a169)
![image](https://github.com/user-attachments/assets/c296ce99-ccdb-4438-8de6-0103016b4eda)
![image](https://github.com/user-attachments/assets/10d227c0-b40d-49a4-a1a2-5dc5d210dee5)
User created in Supabase

### Environment

```markdown
- FlutterFlow version: v4.1.89+ 
- Platform: Web
- Browser name and version: 128.0.6613.138
```

### Additional Information

Makes it impossible to do the very simple task of communicating to the user that they have created an account.

**Comment by paulperez-dev** [comment]
Hi @morethanlikelyMatt,

I’m sorry to hear you’re experiencing this issue. Could you please check if the 'Confirm email' option is enabled in Supabase? This might be causing the problem.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/632ba0a3-fff8-4fd8-b2f0-69e4da89b527/23f4e1a5-83f5-4b6b-9df0-2ff4b2cb5b62?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MzJiYTBhMy1mZmY4LTRmZDgtYjJmMC02OWU0ZGE4OWI1MjcvMjNmNGUxYTUtODNmNS00YjZiLTlkZjAtMmZmNGIyY2I1YjYyIiwiaWF0IjoxNzI2NTIyNTQwLCJleHAiOjMzMjk3MDgyNTQwfQ.e8so2E7ryTBs0CdLmHvlL-CaKz3DEFb8pYjKxxV8_TU " alt="image.png" width="879" height="592" />

**Comment by morethanlikelyMatt** [comment]
@paulperez-dev Yes, it is enabled. The account is created and the email is sent. The issue is that any subsequent actions like navigating to another page do not run.
![image](https://github.com/user-attachments/assets/9abc8c90-a7c5-4852-b400-0582889ceacd)

**Comment by paulperez-dev** [comment]
Hi @morethanlikelyMatt,

This won’t work because the user isn’t authorized yet. You’ll need to confirm the email first, then return to the app and handle that scenario—perhaps by showing a popup or navigating back to the login page.

I’ll be closing this issue now.

**Comment by morethanlikelyMatt** [comment]
@paulperez-dev I'm trying to tell the user to check their email to confirm their account and navigate them away from the create account page. It wouldn't make sense for them to confirm their email first and then ask them to confirm their email.

**Comment by earlgreycoder** [comment]
> @paulperez-dev I'm trying to tell the user to check their email to confirm their account and navigate them away from the create account page. It wouldn't make sense for them to confirm their email first and then ask them to confirm their email.

this exactly. Why was this closed? This is still not resolved.
