### ISSUE TITLE
The cursor position option does not work in the set form field action

### ISSUE THREAD

**Issue by digideasagencia** [FlutterFlow/flutterflow-issues#3836]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to use the set form field action, it has an option to set where the cursor will be in the text field, whether at the end, beginning, or selected. I have tried all 3 options and in fact none of them work.

### Expected Behavior

When setting a textfield with this action, the focus should remain and the cursor should be in the selected position, whether at the end, beginning or selected.

### Steps to Reproduce

1. Add a text field
2. Add a button
3. Give the button the action to set form field
4. Select some of the cursor position options in the action.
5. Execute the button action.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmB05NItb0E+YfyL8dvqwMxQUB+bZ0vlO1FGQ8aC4DvPJoteODEaXdoUsuUegtAD1aKgnID+tLWidnUVvkEJTSZbal607oNdhWXbEOQR7q4ErqCX0B7J9NUGEeO0cHYqhV4IshvZVIHw1+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/09560193-086c-450a-b80f-6b33107569cb

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: MacOS Desktop / Web
- Browser name and version: chrome 127.0.6533.120
- Operating system and version affected: MacOS 14.6.1 (23G93)
```

**Comment by paulperez-dev** [comment]
Hi @digideasagencia,

I was able to reproduce the issue and will forward it to the engineering team so they can work on a fix.

Thank you for your report!

**Comment by GP-Ninja** [comment]
I really need a solution for this too!!

**Comment by jimbo43211** [comment]
Ah I thought it was just me!

**Comment by jimbo43211** [comment]
It would be great if this could be sorted - pretty crucial for my app!

**Comment by timdcochran** [comment]
Is this really not going to get fixed @leighajarett? If not, we'll probably need to look into building our own text field as this is pretty important to the usability of our app.

**Comment by mmearly** [comment]
Hey @timdcochran and others -- sorry for the mixup, we're just moving our tracking of this to [this issue](https://github.com/FlutterFlow/flutterflow-issues/issues/4609). A fix is in the works!

**Comment by timdcochran** [comment]
Ah wonderful... thanks and following!

**Comment by mmearly** [comment]
Fix released! See [issue 4609](https://github.com/FlutterFlow/flutterflow-issues/issues/4609)
