### ISSUE TITLE
'Push to Repository' feature and 'Download Code' feature is unavailable.

### ISSUE THREAD

**Issue by sjwoo1999** [FlutterFlow/flutterflow-issues#3838]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

'Push to Repository' feature and 'Download Code' feature is not working at all.
I've terminated flutterflow and relaunched it several times, and I've tried reconnect to my Git-Repository, but I couldn't resolve my problem.

### Expected Behavior

Successfully push codes to github and download codes.

### Steps to Reproduce

Just click 'Push to Repository' and 'Download Code'.
There will be errors.
This is the only thing I hope you to test.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slfLq25VNtbxK17rUa/lR/SovJkwkRpI0scp/bxIgGIDzPOw+ZPWkbk5uZ/29dwlAJkSmmj4d/9Lzv9rDDPA3EzCZbaVywqhqVxaWXmCge5OBELWCXUBTEcVgfVSz0Z6GkRRRJuxfLUIAwDmIe/PKdA3fQ+PuImdISq/LZO4=

### Visual documentation

<img width="645" alt="Screenshot 2024-09-17 at 09 27 59" src="https://github.com/user-attachments/assets/ba051d19-4d2d-415c-8f71-bd316b3f8d12">

<img width="634" alt="Screenshot 2024-09-17 at 09 28 30" src="https://github.com/user-attachments/assets/ec1f26e1-de51-4427-b721-f3c09d84c7ad">

### Environment

```markdown
- FlutterFlow version: FlutterFlow 4.1.91
- Platform: Android and iOS
- Browser name and version: Chrome 128.0.6613.120
- Operating system and version affected: MacOS
```

### Additional Information

I don't know which account should I have to invite to my project. If you let me know, I'll immediately invite your account to my project.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. As you mentioned, there seems to be an error within the project, but no issues are appearing in the top-right corner. To get the best assistance, I highly recommend reaching out to our support team either via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They have the right tools to help you resolve this.

Just a quick note: this GitHub Issue Tracker is mainly for bugs that can be reproduced in a new, blank project. In this case, I wasn't able to determine the cause of the issue.

Thank you for your understanding!

**Comment by sjwoo1999** [comment]
I've send e-mail but I didn't get respond. I hope to get response soon.

Thanks.
