### ISSUE TITLE
XCode 16 - Allow non-modular includes in framework modules

### ISSUE THREAD

**Issue by geret1** [FlutterFlow/flutterflow-issues#3844]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Firebase is not working properly in XCode 16 by generating the following error on build

```
firebase_storage/firebase_storage.framework/Headers/FLTTaskStateChannelStreamHandler.h:13:9: error: include of non-modular header inside framework module 'firebase_storage.FLTTaskStateChannelStreamHandler'
```

### Expected Behavior

Complete build process and run the app.

### Steps to Reproduce

Run an app with Firebase and Xcode 16.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Ll8ZNIvulA187pbfowtDg7Q1g/TL07ttYbZxUjIuPtBJh/fuDsUxFpQtOldFNhHE6kpGICpuD4jtr9GscqIROsfL04wpFcUwzNRXq8Sq64ELuafHEkJJpWGhGZ1qaJ3xJ/AO5qLkYM12CQIOjIEzfcGZ+/Zwh9f6PHaOI=

### Visual documentation

<img width="757" alt="Screenshot 2024-09-18 at 09 21 12" src="https://github.com/user-attachments/assets/b110831c-2fb1-4e8c-9abc-f30b0e388c73">

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: MacOS Desktop
- Browser name and version: Desktop
- Operating system and version affected: macOS Sonoma 14.5
```

### Additional Information

Related https://github.com/FlutterFlow/flutterflow-issues/issues/3834

**Comment by komineyuki** [comment]
I'm having the same problem. I did the following but the same error occurs.

Podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
```

By doing the above, the error no longer occurs for other packages such as Auth and Firestore, but for some reason only the storage error occurs.

**Comment by geret1** [comment]
Thanks for taking care of the issue. Could you explain a bit the fix?

**Comment by jimff** [comment]
![Screenshot 2024-09-23 at 15 34 13](https://github.com/user-attachments/assets/1420d2f0-36bc-410c-800d-a250b684be39)
![Screenshot 2024-09-23 at 15 59 03](https://github.com/user-attachments/assets/3bc6d438-19ef-43fb-ba60-474edc6c7453)

Having the same issue with Xcode 16 on Flutter 3.22.2 on macOs Sequoia 15.0 with the Desktop version. I have to manually change it to yes to be able to build my project that uses firebase messaging.

**Comment by sbis04** [comment]
Just wanted to update about this, we have a fix but the update is still not released, should be fixed in tomorrow's release if everything works fine!

**Comment by jimff** [comment]
Great to hear!  Is there also a workaround for setting this from within FF?  So the push notification capability.  I have to export, change and then build instead of being able to just build from FF. 
<img width="713" alt="Screenshot 2024-08-25 at 08 17 16" src="https://github.com/user-attachments/assets/e4f3ec7a-4240-4f41-a281-c74117b8c239">

**Comment by geret1** [comment]
FYI. Related: https://github.com/firebase/flutterfire/issues/13323#issuecomment-2368991665

**Comment by jimff** [comment]
> Just wanted to update about this, we have a fix but the update is still not released, should be fixed in tomorrow's release if everything works fine!

This update fixed the issue.  Tx.  Tested it and it works now. @sbis04
