### ISSUE TITLE
Map markers stop showing bottom sheets if the map is in a PageView and you navigate away from it

### ISSUE THREAD

**Issue by Olaf697** [FlutterFlow/flutterflow-issues#3845]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tested a FlutterFlow prebuilt bottom sheet with two maps in a PageView, using only the device location for the markers and no other data. I tried navigating both through actions and by swiping. Once you navigate away from the page, the markers can no longer be tapped, or at least they stop showing bottom sheets. Also worth noting if the pageview page you navigate to contains a map with markers that will work as expected until navigated away from.

### Expected Behavior

The marker to show the bottom sheets even though the pageview change pages

### Steps to Reproduce

!.crate a page 2 crate a page view 3 create a map with markers 4 set a bottom sheet to the marker or markers 5 navigate between the pageview pages and try to open the bottom sheet

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khc/6w5dOm+lc15P1bexVtCk6NjN+TL07s9Z+RRQvIrbyOu9+PPf4QBZCZMOhY1NhHFf/jjo00NLWjeDxLPFfaDOcGbZR+LlyFw/vRXq8RrK2CbmwQHd6AeJjBUyb08CG3CR+PtNuLncuwUOLNt6vcBLfCZ+/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/ad423447-bd8b-48d1-957e-fa4ddcd225de

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: web
- Browser name and version: Google Chrome
- Operating system and version affected: win 10 and 11
```

### Additional Information

Well the project dosent work without it

**Comment by Alezanello** [comment]
Hello!

I’ve been trying to replicate the issue but haven’t had any success. I also noticed that the test page no longer exists in your project. Would it be possible for you to create a new blank project and follow the steps you mentioned to see if the issue persists?

Thank you!

**Comment by Olaf697** [comment]
@Alezanello Hey i dont know if you can open it but here is a completly fresh project with the same issue: https://app.flutterflow.io/debug/grVYQBckRf867k1jDnaj.
only thing i reused was the api key

**Comment by Olaf697** [comment]
Here is a new recording of it 

Uploading Test Mode - test - Google Chrome 2024-09-19 09-18-29.mp4…

**Comment by Olaf697** [comment]
As you can see this issue apereas after the pageview page is navigated away from in the page view

**Comment by Olaf697** [comment]
I find it very strange that it cant be replicated? did you navigate to another page in the pageview or another page entirety I might have been unclear as the problem only accrues if you navigate in the pageview pages. The only other explanation would be that is connected to the api key which sounds very unlikely

**Comment by Cosaxo** [comment]
Still here

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?
