### ISSUE TITLE
Problem with changing mode (dark and light)

### ISSUE THREAD

**Issue by Emvipy** [FlutterFlow/flutterflow-issues#3847]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When switching from dark to light mode or vice versa, for some reason and not always, 2 things happen, either the screen remains grayed out or you are kicked out of the app and sent to the Welcome page. 
This also happens if you change the dark or light mode from iOS (not from the app).
This happens on both iOS and Android but does not happen in test mode from FF.
Attached videos made in iOS

### Expected Behavior

Continue to use the app normally after the change..

### Steps to Reproduce

change mode in native app

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPHl05NOm9tJ7s7TbflvgScQH0c3TLJEtusbTUggfbL4Ook2OeLRYlZuYNyzaHNhM2aIiXEC3NGNvvP1VPc4KQ2tRaY/zalhFhPPYz6WeJClC8/gP0FAMNFXBX6w3KujuRBSANBYWkYj3U2QF+SXFj+Cf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/16cde316-86a1-405f-bacd-0d1812a11044

https://github.com/user-attachments/assets/436f884d-f767-46e4-8dc5-eacd8ae56ded
![Screenshot 2024-09-18 at 18 2
![Screenshot 2024-09-18 at 18 25 37](https://github.com/user-attachments/assets/fd5111c6-5374-4412-b9a2-89769b8086ad)
5 29](https://github.com/user-attachments/assets/a7920b38-c737-4b03-9156-5f55bc0e26a2)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.91 released September 11, 2024
Flutter version is 3.22.2
- Platform:Mac
- Browser name and version:
- Operating system and version affected: iOS & Android
```

**Comment by paulperez-dev** [comment]
Hi @Emvipy,

I was able to change the app theme on my end. Could you please provide more context about the issue you’re experiencing? It would be helpful if you could include the steps to reproduce the problem and share the bug report code for your project.

Thank you!

**Comment by Emvipy** [comment]
Hello, the problem is not that it does not change the subject, it is that after doing so, if I click on any link such as going to the Home, it happens what is shown in the videos....
As it only happens in native app, I can't debug but it seems like all the state variables are deleted or something similar.

**Comment by Emvipy** [comment]
> Hi @Emvipy,
> 
> I was able to change the app theme on my end. Could you please provide more context about the issue you’re experiencing? It would be helpful if you could include the steps to reproduce the problem and share the bug report code for your project.
> 
> Thank you!

I think I found the problem, I think it's a query to Xano, but I'm going on a trip and I won't be able to check it thoroughly until next week, can you leave this ticket on stand by and next week I'll let you know?

**Comment by Emvipy** [comment]
Yes, It was a query to Xano.
Sorry

**Comment by paulperez-dev** [comment]
Hi @Emvipy,

Thanks for the confirmation!
