### ISSUE TITLE
ios deployment "missing compliance" for encryption

### ISSUE THREAD

**Issue by halvorot** [FlutterFlow/flutterflow-issues#385]
## Expected behavior (required)
Automatic deploy without any errors

## Current behavior (required)
When I deploy my app to the app store I get a "missing compliance" warning regarding encryption. This warning is shown for each build in AppStore Connect. I then have to manually go through the steps to fix this warning and get the app deployed. I believe this should be set by flutterflow as encryption is handeled by the flutterflow and firebase/supabase integration.

## To Reproduce (required)
1. Deploy app to app store
2. Go to appstore connect and see warning for build
3.
4.

## Context (required)
I believe this could be fixed by adding som code to a info.plist file like described here: https://stackoverflow.com/questions/35841117/missing-compliance-status-in-testflight

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by organicnz** [comment]
Hi @halvorot. Thank you Halvor for adding this issue 🙂

I did reproduce this issue with my app on the Apple Dev account :)

Kind regards,
Tarlan Isaev

**Comment by agreaves** [comment]
Hi @halvorot, thanks for the bug report! This is indeed a thing some apps have to deal with on the iOS store, and is quite common for Flutter apps (especially with Firebase).

Strictly speaking this is more of a feature request than a bug (as everything works fine it's just an extra step in the AppStore), so I'm closing this for now. However, the good news is we have plans to allow folks to add custom code to their `Info.plist` in the not too distant future, so you'll be able to fix this down the line.
