### ISSUE TITLE
Cannot use the IA copilot to create function.

### ISSUE THREAD

**Issue by Syrius-x** [FlutterFlow/flutterflow-issues#3850]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi !
For the past few hours, I've been trying to use Copilot to create a custom function, but even the simplest requests aren't working.

### Expected Behavior

Just see the copilot working.

### Steps to Reproduce

Try to create new function.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzsiA34Zgrt9c187pbfp4mWIQJWF9TLJEoetxc0gbfe/4PLN/fcz8R1puZ8CzaHNPeWakjnsezNWKiIbtEfk4YEmsGaJh/6VhFxPPbGeibpiPBZGaSGsnO9lYCFCx0bev2iJ7NvN1c0YQ71+hevCiST6Cf9qOYwx5e6fDbOY=

### Visual documentation

![retourFlutterFlow](https://github.com/user-attachments/assets/37647cb0-e2d9-4076-a9d7-25a9233de17e)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hello @Syrius-x,

Thank you for bringing this to our attention. I've confirmed that Code Copilot isn't responding at the moment. I'll reach out to the internal team to investigate if there are any ongoing outages affecting this service.

I'll keep you updated as soon as I have more information.

**Comment by rzambroni** [comment]
Hello again,

Our engineering team has confirmed that there was an outage earlier today due to the use of a deprecated model. The issue has since been resolved, and everything should be functioning as expected now.
