### ISSUE TITLE
Can't emulate my flutterflow app with downloaded code on XCode after MacOS and iOS update. 

### ISSUE THREAD

**Issue by valentinoerrandonea** [FlutterFlow/flutterflow-issues#3853]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't emulate my app after updating to the new OS. License agreements have been accepted but im not able to build the app. 

### Expected Behavior

It should build and emulate on my iPhone as it always does. 

### Steps to Reproduce

1. Download or clone repo 
2. Install flutter dependencies
3. Install Pods
4. Build the iOS app
5. Open the runner on XCode
6. Build
7. Build Fails due to an error 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not bug report

### Visual documentation

It says that the build failed 

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89
- Platform: iOS
- Browser name and version: Arc (Latest)
- Operating system and version affected: MacOS Sequoia
```

**Comment by tensoralex** [comment]
@valentinoerrandonea check this thread https://github.com/FlutterFlow/flutterflow-issues/issues/3834

**Comment by paulperez-dev** [comment]
Hi @tensoralex,

I’m sorry to hear you’re facing this issue. We are currently tracking it under #3834, so I’ll be closing this report as a duplicate.

Thank you for your understanding!
