### ISSUE TITLE
Screen becomes blank while working ... 

### ISSUE THREAD

**Issue by prithvi438** [FlutterFlow/flutterflow-issues#3854]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello FlutterFlow team, While working in Flutterflow I have been facing an issue which is the screen becomes blank while working in fluttterflow.

Below is the Screenshot of the scrren which becomes blank while working.
 
![WhatsApp Image 2024-09-20 at 10 01 51](https://github.com/user-attachments/assets/e5cfb4e6-acea-4b7d-8de7-b38eb70a0f63)

Thankyou for resolving this issue.

### Expected Behavior

I want the Flutterflow to work more optmize and the above mentioned issue should be resolved.

### Steps to Reproduce

I was creating a screen with around 200 checkboxes and while binding those checkboxes with API the screen becomes blank.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITSlwkemrw.,erl

### Visual documentation

below is the screenshot of the issue
![WhatsApp Image 2024-09-20 at 10 01 51](https://github.com/user-attachments/assets/1df3e11b-6da0-4fc1-9a89-1063adf99081)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @prithvi438,

Could you please share your environment details along with the bug report code for your project? This will help us investigate the issue further.

Thank you!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
