### ISSUE TITLE
MarkDown bug widget 

### ISSUE THREAD

**Issue by PavelPanferov** [FlutterFlow/flutterflow-issues#3856]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I send data from the API (JSON) to the MarkDown widget and it does not output it. If I display this data simply in a text widget, then the data comes.

### Expected Behavior

The widget should show data from the API

### Steps to Reproduce

Create a MarkDown widget, connect to Data, several languages ​​and substitute the key value from the API into the language path. MarkDown will be empty

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkPHlz4xIsepE+artYO5FmmAwGUwBUI03kNVuGEsbI+PvP+wcfMneVxJBWOqHT31+CmaJuFID+vCMkeLxKPoCAwucQIBbyJdfUxDjcEmibpCuC82oZH9CAfhMN36X56uv2BV7A7dZcUVg1DqMDd+Ab3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="639" alt="Снимок экрана 2024-09-20 в 17 07 31" src="https://github.com/user-attachments/assets/5656cd23-be74-41e7-9e00-04fbfc0e4aa0">
<img width="691" alt="Снимок экрана 2024-09-20 в 17 07 38" src="https://github.com/user-attachments/assets/b2d26cee-ed31-407c-8f36-b1a568e3c802">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.91 released September 12, 2024
Flutter version is 3.22.2
- Platform: WEB&Desctop
- Browser name and version: CHROME
- Operating system and version affected: MAC
```

**Comment by Alezanello** [comment]
Hello!

It looks like you might be referencing a similar issue reported on GitHub. Could you please check out this [link to the issue](https://github.com/FlutterFlow/flutterflow-issues/issues/3641) to see if the solution provided by another user there works for your case?

Let me know if it resolves your issue, or if you need further assistance. I'm here to help! 😊

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
