### ISSUE TITLE
Chart axis options resetting automaticaly

### ISSUE THREAD

**Issue by LucasTormina** [FlutterFlow/flutterflow-issues#3857]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After I changed an option in the axis of my chart widget (I created a new one to try again and it continued), after some seconds it reverts back to its predefined state, like for example, if i change the "Label Interval" to 1, so i can show from 1 to 10, it will come back to the original 10, showing only 1 and 10, but not in between, like 2 and 9, same for the rest of the options.

![Captura de tela de 2024-09-20 10-11-04](https://github.com/user-attachments/assets/ede40aa6-44fc-4ca9-94bd-9a5945f863da)

Is there something else? Because the professor in the video didn´t had it changed.

### Expected Behavior

I expected the value to stay after I set it, not change back

### Steps to Reproduce

1. Create a project.
2. Add a chart widget.
3. Create 2 variables (one named axisX and another named axisY for example) of type integer, mark then as list and add 4 values (1, 2, 3, 4).
4. in the chart widget select the "Numbers List" as its data, then pass the according variables as the chart axis data (axisX for axis X and axisY for axis Y).
5. change the axis's "Interval Value" to 1 and click the "Test Button".
6. If youŕe quick enough it may load the project with the "Interval Value" still as 1, but once you come back to the project screen it will have changed to 10 again.
7. This auto-reset happens to anything I change in this axis's properties.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slPLqx5B1m7RY15Dpbe5r/ScWHEAlRLsSsctCbxcgF5CuBuwPPOLBYVhvZ9+raVNcDFKboE0xpsr5iODxUe44IRCZG4Bez7t6Fw/ke2iXMs2qO8y8YUB9N/9NCBWP0bWJrAlCPtBtcXA83VymN+nKFj3DBOu/Zwh9f6PHaOI=

### Visual documentation

![Captura de tela de 2024-09-20 10-11-04](https://github.com/user-attachments/assets/792b5010-230f-4e27-9239-4212d61e7d5d)

### Environment

```markdown
- FlutterFlow version: 
- Platform: Web
- Browser name and version: FireFox
- Operating system and version affected: Linux
```

**Comment by Alezanello** [comment]
Hi there!

I'm sorry to hear you're experiencing this issue. I tried to replicate it on my end but wasn't able to. It doesn't seem to reset any values for the X/Y axis or properties like the interval. Would you mind recording a video of the behavior so we can investigate further?

Thank you!

**Comment by LucasTormina** [comment]
https://drive.google.com/file/d/1pg2FHCXABcr8CRqRcYd2we9Y1d85BA39/view?usp=sharing

Em seg., 23 de set. de 2024 às 09:38, Alezanello ***@***.***>
escreveu:

**Comment by Alezanello** [comment]
Hello again!

We've received additional reports of this issue, and the team has already added it to the backlog for a fix. I'll keep you updated here with any progress. Thanks for your report and for your patience!

**Comment by sirifb** [comment]
Hello
I experience the same problem. I see that the issue has status "Closed" - does that mean that it won't be fixed?

**Comment by LucasTormina** [comment]
they said it is on their list, but nothing more.

Em sex., 11 de out. de 2024 às 06:26, sirifb ***@***.***>
escreveu:

**Comment by machinefriendly** [comment]
I'm facing the same issue, 10 is not usable for our case, we need unit of 500 as interval, before this bug is fixed, we cannot launch the project as label is necessary to read data, and given 10 persists, labels shows as mess. Please help fix it ASAP. Thanks.

**Comment by Kernelpanic24** [comment]
i have the same issue. i can change the y Axis label intervall many times, but it changes back always to 10.
in the x axis i use actually a manual label. (take every 20,30x Index and show it underneath the xaxis. but in dynamic no fixed seriesdata this isn`t possible for the Y Axis.
right now we are thinking about the possible way to implement external Charts over custom Flutter Code.

So this Problem is an urgent and also the only one which i am facing in my work with flutterflow.

Best Michael
![image](https://github.com/user-attachments/assets/56ea2765-c0e9-4399-aa33-3d98731a6b30)

**Comment by kinyuajoe4** [comment]
Facing the same issue.I need a label interval of 500 and above but it keeps re-adjusting to 10 making the graph so messy on the y-axis.

**Comment by kinyuajoe4** [comment]
Facing the same issue.I need a label interval of 500 and above but it keeps re-adjusting to 10 making the graph so messy on the y-axis.
