### ISSUE TITLE
Animation Bug: Apply same duration & delay

### ISSUE THREAD

**Issue by ryanmish** [FlutterFlow/flutterflow-issues#3860]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an animation has already been created, and the toggle for _Apply same duration & delay_ is selected, it doesn't apply. The UI reflects a change to the duration and delay but in test mode it doesn't apply.

### Expected Behavior

When animations are already created and the user selects _Apply same duration & delay_, it should overwrite whatever settings the individual animations had and follow the new selection.

### Steps to Reproduce

1. Insert a text widget
2. Add an animation to the widget
3. Select _Apply same duration & delay_ and change the duration and delay from what the animation had set on itself
4. Duplicate the text widget, turn off _Apply same duration & delay_ and set the animation and delay to match the top text widget in the animation itself, without _Apply same duration & delay_
5. Enter test mode and see that they display differently.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/15ZVNxOFc+KXxYcJWgj8vGUMcWOdEl+tuZwgbIoznBuwAO8/4UBBWYMemaVNcD1eZuE4109b9j9/PD8I4NkmtbaZFwcxbWDzee2iQRLbTCsyafmhSL9pgfHad54mzvAknXLZqcWQf3WWqINmidCnDFOu/Zwh9f6PHaOI=

### Visual documentation

https://vid.pinpointinteractive.com/conversations/649d64b5-432d-5300-99fb-ea4b738c63ab

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 12, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Version 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: MacOS 12.6.5
```

### Additional Information

This makes creating complex animations difficult but I can work around it for now.

**Comment by paulperez-dev** [comment]
Hi @ryanmish,

Thank you for reporting this issue! I was able to replicate it on my end. I'll be passing it along to the engineering team so they can start working on a fix.

Your help is much appreciated!

**Comment by ryanmish** [comment]
Hi @leighajarett, was this not able to be replicated or was this resolved? (cc @paulperez-dev)

**Comment by paulperez-dev** [comment]
Hi @ryanmish,

This issue has been identified as a duplicate of a previously resolved one. However, I revalidated it, and it’s still occurring. I’ve informed the team for further review.

**Comment by ryanmish** [comment]
Hi @paulperez-dev, will this be reopened?

**Comment by paulperez-dev** [comment]
Hi @ryanmish,

The fix should now be live in Production. Could you please check if the issue is resolved on your end? If it’s still occurring, I’d be happy to reopen the issue. Just let us know!

Thanks for your help in confirming!
