### ISSUE TITLE
'Set from variable' option missing in Component Parameters

### ISSUE THREAD

**Issue by TerrorTeake** [FlutterFlow/flutterflow-issues#3861]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When working with an Icon widget u can set Icon size/-color from variable. But when you have a custom component that has an Icon as 'Component Parameter', you cannot set the size/color from variable.

![Screenshot 2024-09-20 183355](https://github.com/user-attachments/assets/8eeb43dc-429b-4f5d-ae4a-3bfb39425813)

### Expected Behavior

When having an icon as Component Parameter, be able to 'Set from variable' on the size/color.

![Screenshot 2024-09-20 183226](https://github.com/user-attachments/assets/a7333d43-2ea7-4235-bb2c-ea108ae9b8fb)

### Steps to Reproduce

1. Create custom component widget
2. Add Component Parameter of type Icon
3. Add that custom component widget to a page
4. Select the custom compnent widget and under the component properties there should be an icon property, in which you cannot set size/color from variable

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hv6CvMt4oeoE4YfTLcFVoCMWJWF8Rp0SmtVRaCsofePrOpkAf8/7UFtUOdendHxmeFn8mXIX/MrsiN/+UcYrHzSqf4d8zpABVjzzUnm5bqqQDK63b2pBOJlgCEyH0aWv2yV5D7ZoZV4Y7GCyDeyAb3PdHb7KNjERMua4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/ee8075d2-3749-481b-8631-43faaf46e513

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Desktop
- Browser name and version:
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hi there!

I was able to replicate the issue on my end. I'll forward it to our engineering team for further investigation and implementation. Thank you so much for bringing this to our attention!

**Comment by Alezanello** [comment]
Hello again!

The engineering team has clarified that this is not a bug but rather the expected behavior. This ticket should be considered a feature or enhancement request.

The good news is that the team is currently working on making all properties dynamic, so this issue should be resolved soon!

**Comment by emilbarmen** [comment]
Hi, found this issue and this now seems to work, however I have got a related issue: If I add an icon parameter, I am then unable to set the icon color independently of the icon parameter. For instance I would love to specify one color if the current component has a boolean parameter or state "active" and use another color if the component is "inactive" regardless of chosen icon.

![Screenshot 2024-11-08 at 09 30 16](https://github.com/user-attachments/assets/f1d3aec2-a1bd-4cd0-99ab-07076fcb1f8d)

![Screenshot 2024-11-08 at 09 32 25](https://github.com/user-attachments/assets/1b4cc415-9754-49bf-9c5c-cebfa0a86ed2)

If I now try to pass in the icon as a parameter from another component, I am still unable to set the icon color from a parameter or state of that component
![Screenshot 2024-11-08 at 10 49 36](https://github.com/user-attachments/assets/f3c71ad6-dd36-4ca9-accf-2a42e8bbfcee)
