### ISSUE TITLE
Logged in user close tap and open webapp main domain shows 404 error

### ISSUE THREAD

**Issue by yuehanjohn** [FlutterFlow/flutterflow-issues#3862]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When user are logged in using email, close the tap, and return to main domain (example.com), are directed to error page 404

### Expected Behavior

when user are logged in using email, close the tap, and return to main domain (example.com) they should be directed to logged in user main page. 

### Steps to Reproduce

1. Create a basic project with email authentification function, login page, redirect page, user1 page, user2 page. 
2. Set not logged in main page to sign up page, set logged in user main page to redirect page.
3. Add redirect action on redirect page depends on usertype
<img width="749" alt="image" src="https://github.com/user-attachments/assets/ff9bfe34-07c0-40de-acaf-75021f3a16d2">
4. Publish to web domain.
5. Sign up and login.
6. close the tap.
7. go to main domain again (example.com)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Visual documentation

<img width="599" alt="image" src="https://github.com/user-attachments/assets/d1373053-781b-408c-82d1-4c35fae5ff47">

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: All operating system
- Operating system and version affected: Multiple system
```

### Additional Information

I have over 100 users from all around the world, multiple users reported this issue.

**Comment by Alezanello** [comment]
Hi there!<br><br>To help us thoroughly investigate whether this is a replicable bug, could you please follow the proper steps for submitting a bug report? This will give us all the details we need to assist you more effectively.<br><br>You can find the guidelines here: https://docs.flutterflow.io/misc/submit-bug-report/<br><br>Thanks for your help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
