### ISSUE TITLE
Error when running boolean check against two properties of LatLng Type

### ISSUE THREAD

**Issue by monocat** [FlutterFlow/flutterflow-issues#3863]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

#3815 Reopening.
When attempting to run a boolean check to assigned latlng page state against current googlemap center, I keep receiving **Current Variable is not valid** error message.

### Expected Behavior

Since both types are latlng, I expect no errors.

### Steps to Reproduce

1. Create new page
2. Create page state named **currentMapCenter** and assign type LatLng
3. Add GoogleMap widget
4. Add Button
5. Enable Button's condition visibility and add the following condition: Page State: currentMapCenter Not Equal To Widget State: Current GoogleMap Center

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fls/l6otOscsA1rqNd+9VhiYXQ3IjUIJJltYbSRQgfanqP4YAeM+lQ1pJbbyRSmNceWH8/W0J+sqLuNnfDMECYRyJboR4zpFqTAKVYFKgWr6KBaqSQGglRZlbGH7EzpuZnxQnNu9ZS3wg612UPeeRYC/bO7rGDjERL/3/KovOpF6GHSLgGX0Jg1ZSfCvr

### Visual documentation

![bug latlng boolean check](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6a63a491-7951-49f8-b1ff-d1347fcd5baf/df782a1a-285c-4794-a7b8-f0c45edd1431?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YTYzYTQ5MS03OTUxLTQ5ZjgtYjFmZi1kMTM0N2ZjZDViYWYvZGY3ODJhMWEtMjg1Yy00Nzk0LWE3YjgtZjBjNDVlZGQxNDMxIiwiaWF0IjoxNzI2MjUzOTMzLCJleHAiOjMzMjk2ODEzOTMzfQ.TKjTkhISbT1rliYT1IQ2Neookyhcl-vDniWJasuQ7DY)

### Environment

```markdown
- FlutterFlow version: web 4.1.89 / mac app 4.1.90
- Platform: Mac OS
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hi there!

I was able to replicate the issue on my end. I'll forward it to our engineering team for further investigation and implementation. Thank you so much for bringing this to our attention!
