### ISSUE TITLE
Launch visibility and animation of a widget in a same action doesn't work.

### ISSUE THREAD

**Issue by Syrius-x** [FlutterFlow/flutterflow-issues#3864]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi!
I will refer to my images:
I click on the blue square to: make the red square visible and launch an animation of the red square (with the same click).
BUG: The animation doesn't launch. In another project, the red square won't even be visible.

The solution I found: On the button action (when I click on the blue square), I need to add a delay (even 1ms) to make both the visibility change and animation work. **However**, if I put a delay (even 500ms) in the animation itself, the animation doesn't start.

It's simple, but I spent time finding my solution. I can see that flutterflow users had experienced the same problem that is still not resolved.

### Expected Behavior

When I launch a action to make visibility + animation in the same time, I want that all works.

### Steps to Reproduce

I detailed them.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzsiA34Zgrt9c187pbfp4mWIQJWF9TL03pu0bFEggGLbrBIYMacnSTxJDXfW7Y29pKEWIijsHzMLQiOPTJ/knFyWubIB91c9IcRXvcHK/aoSOCZG8YX97N+9MfWqE37aVrhNRIrFecU4lwGeQC9yuRXLDK7n7Zwh9f6PHaOI=

### Visual documentation

![report2_flutterflow](https://github.com/user-attachments/assets/b357b8c3-95f2-4177-8cf7-df92df8d3669)
![report_animation_flutterflow](https://github.com/user-attachments/assets/2543713f-0f16-4478-8e17-85bcabffe378)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!!<br><br>I'm sorry you are experiencinf this issue, and sorry for the late response.<br>Before taking any action, did you tried to enable the "Hide before Animating" option?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/df751c77-39ab-4464-89df-469baed0b976/453c4935-04b1-4030-a53c-aa06294eae91?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZjc1MWM3Ny0zOWFiLTQ0NjQtODlkZi00NjliYWVkMGI5NzYvNDUzYzQ5MzUtMDRiMS00MDMwLWE1M2MtYWEwNjI5NGVhZTkxIiwiaWF0IjoxNzI3MTIxMjcyLCJleHAiOjMzMjk3NjgxMjcyfQ.XtIQVyTUvJ4G0tKmEt1HLrV4pfGCGyrYLg2ErVHHzoo " alt="image.png" width="389" height="408" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
