### ISSUE TITLE
New FlutterFlow v4.1.91 build failed.

### ISSUE THREAD

**Issue by oleksandr-sainidi** [FlutterFlow/flutterflow-issues#3866]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to build my app, but get the list of errors. I can't use the older version of the desktop app because of the app ask to update to the latest one. 

### Expected Behavior

I want to build my app and continue working on.

### Steps to Reproduce

Try building on any device with iOs.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjMrlvJFOj7xe7qqNaflR/GEvH0d7U7hFscp/bxIgGIDzPOw+ZPWkdkpCUvWrSlZYM0SmmkQ1wtrqkYf9OsInPTKubbpx1KpMdjzwUTuna5OBCLmSSH98INNUCky1yJ+rviMmNvBZV1oR2mD6fOeia3XXJpzNImdISq/LZO4=

### Visual documentation

<img width="780" alt="Screenshot 2024-09-21 at 12 37 04" src="https://github.com/user-attachments/assets/13a5388e-3f07-4eac-b43b-cd2a65e5d13c">
<img width="786" alt="Screenshot 2024-09-21 at 12 37 13" src="https://github.com/user-attachments/assets/01c97593-451b-404d-8a79-e82cf0fc3289">

### Environment

```markdown
- FlutterFlow version: v4.1.91 
- Platform: iOs
- Operating system and version affected: macOS Sequoia 15.0
```

**Comment by healemdrapp** [comment]
I've been going around in circles thinking I have a problem at my end, I even uninstalled Xcode and installed everything back again. Hopefully it will get addressed soon!

**Comment by Alezanello** [comment]
Hi there!

I'm sorry you're facing this issue, but the good news is we're already aware of it and actively working on a fix. The issue is related to the `url_launcher_ios: 6.2.5` package and its compatibility with the latest Xcode version.

Thank you for your patience!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
