### ISSUE TITLE
Potentially breaking update from Google regarding photo and video permissions policy

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#3867]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

About a year ago, Google has released a statement regarding an upcoming change on Google Play's photo and video permission policy.

More details can be found on their [support page](https://support.google.com/googleplay/android-developer/answer/14115180), but the worrying part is that they have set a deadline for all developers to review their need to remain using either READ_MEDIA_IMAGES or READ_MEDIA_VIDEO permission in Android devices, based on the frequency of use and whether it's part of the core functionality of their apps, through a declaration form. This deadline expires on October 31st, and Google Play will block anyone who fail to comply with the new policy after that.

As far as I know, all photo and video permissions usage in FlutterFlow come from the Upload Data action, so we are not totally able to switch to another form of picking those types of media unless with custom code, which may not be feasible for everyone. Therefore, in order to not have a breaking impact for all Android users, I believe there must be an update in FF so that it uses another selector for media, or at least it gives us an option to choose between the default picker (which uses those permissions) or a different one.

### Expected Behavior

As far as I know, all photo and video permissions usage in FlutterFlow come from the Upload Data action, so we are not totally able to switch to another form of picking those types of media unless with custom code, which may not be feasible for everyone. Therefore, in order to not have a breaking impact for all Android users, I believe there must be an update in FF so that it uses another selector for media, or at least it gives us an option to choose between the default picker (which uses those permissions) or a different one.

### Steps to Reproduce

1. Create button
2. Set action to Upload Media
3. Choose any option under Media Source

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ki/Hl2491pbxH7qXybcJagioUJjM6aqxMiu1EcwEbfbb1EokIfcnBM1BCSMyCf1VYeWeJ8X4Ip/TRhvP9C8EFG02IQ75yyJNQFAzKXjulb8yaELi0eHRtEtFTGEyz4bCOiiJNPft1W05i216MGOqvEj7qHabMOVVEI/2YJrnDpFK9HiLRVThmtmNecCfn

### Visual documentation

There is no visual documentation

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: MacOS Desktop
- Browser name and version: Brave v1.70.117
- Operating system and version affected: macOS Sonoma 14.6.1
```

**Comment by paulperez-dev** [comment]
Hi @vitoras,

Thank you for the heads-up! I'll check with the team to see if they're already working on this and will keep you updated as soon as I have more information.

**Comment by pierrecorbay** [comment]
+1, following the issue

**Comment by sergedahdouh** [comment]
i have same issue

**Comment by laughingbuddha24** [comment]
Why is this issue closed with no explanation? I too have this issue and the deadline is approaching quickly.
![Screenshot 2024-10-10 133439](https://github.com/user-attachments/assets/15b32b4a-563d-4cc5-8473-8d0b81d74ed8)

**Comment by isegal** [comment]
Also having this issue. Built from latest FlutterFlow today. @agreaves this may have been erroneously closed.

**Comment by isegal** [comment]
I see that FF started generating these permissions about 2 months ago:

<img width="807" alt="image" src="https://github.com/user-attachments/assets/38191178-b4bc-41c6-859d-c428f1b4a3de">

It also coincided with this change in flutter_flow_util.dart

<img width="588" alt="image" src="https://github.com/user-attachments/assets/1251086c-f96a-4abb-b6bb-d51e9af56f5c">

Google recommends switching to Android Photo picker: https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html

The current version of image_picker uses Android Photo picker under the hood.
https://pub.dev/packages/image_picker

It could be that FlutterFlow's image_picker version is too old (v1.0.4 in FlutterFlow versus 1.1.2 current).

The package vendor mentions that Android Photo Picker is an opt-in feature in versions up to 1.1.1 where it becomes enabled by default for Android 13+.

**Comment by isegal** [comment]
NOTE: It is not possible to upgrade to the latest image_picker_* packages without Flutter 3.24
```
Resolving dependencies...
The current Dart SDK version is 3.4.3.

Because image_picker_android 0.8.12+15 requires SDK version ^3.5.0 and no versions of image_picker_android match >0.8.12+15 <0.9.0, image_picker_android ^0.8.12+15 is forbidden.
So, because snag_delivery depends on image_picker_android ^0.8.12+15, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Try using the Flutter SDK version: 3.24.3. 
* Consider downgrading your constraint on image_picker_android: flutter pub add image_picker_android:'^0.8.12+12'


Build failed :|
Step 5 script `Get Flutter packages` exited with status code 1
```

**Comment by isegal** [comment]
Update:

The following combination builds for Android in Flutter 3.22:

  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+12

**Comment by solkennedy** [comment]
Having this issue

**Comment by SeabirdReader** [comment]
Any update?

**Comment by solkennedy** [comment]
My app is being rejected now because of this issue

**Comment by DentalRx** [comment]
Our app has also been rejected because of this issue

**Comment by DentalRx** [comment]
### **_Edit: this fix has worked for our app, including allowing android file picker_**

We are attempting a solution by modifying the AndroidManifest.xml file in FlutterFlow's custom code section:

<img width="733" height="699" alt="Image" src="https://github.com/user-attachments/assets/2b59be96-6661-4b28-aead-fbd7a7d159e4" />

<img width="1091" height="516" alt="Image" src="https://github.com/user-attachments/assets/83128172-4ad1-4217-bc61-3db5f3aab73a" />

This snippet must be added: 

`
<service android:name="com.google.android.gms.metadata.ModuleDependencies" android:enabled="false" android:exported="false">
    <intent-filter>
        <action android:name="com.google.android.gms.metadata.MODULE_DEPENDENCIES" />
    </intent-filter>
    <meta-data android:name="photopicker_activity:0:required" android:value="" />
</service>`

Additionally, we removed `android: requestLegacyExternalStorage="true"`

**Comment by ssaikat074** [comment]
For me, it was the `open_filex` package that added those permissions during the build, even though they weren't listed in the `AndroidManifest.xml` file. So, I added the following code to the `AndroidManifest.xml` file, which solved the issue:

```
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" tools:node="remove"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" tools:node="remove"/>
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" tools:node="remove"/>
```

This code instructs the build system to exclude these permissions.
