### ISSUE TITLE
Supabase - When passing parameters from screen A to screen B and navigating to screen C, it is not possible to return to screen A when pressing the back button on the cell phone, the page closes on screen B.

### ISSUE THREAD

**Issue by LeandroGowes** [FlutterFlow/flutterflow-issues#3868]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Supabase - When passing parameters from screen A to screen B and navigating to screen C, it is not possible to return to screen A when pressing the back button on the cell phone, the page closes on screen B.

### Expected Behavior

The correct thing would be to be able to return to screen A by pressing the button, this problem does not occur if you press to return using the navbar for example and I also do not have this problem with projects that use firebase.

### Steps to Reproduce

1.create page
2.Pass the supabase row parameter page B
3.navigate to page B and then to page C
4.Back to page B
5.Try to go back to page B and you will see that it does not work to go back to page A

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhc/qy5d1m8tK7q6IKMdanj0sQkccTOURiO0bFDsdF4iuPOxzac+kMxduTunhdGxHKEWIgTsdpPCJjeHXC/dfISWtc6JZwc59WgzicEW/aoubCs6wdUYnI5hmGnKg3KWnuAhTIrFYLWQO2mWmG+6AZAvZJqH7Zwh9f6PHaOI=

### Visual documentation

![Captura de tela 2024-09-21 155025](https://github.com/user-attachments/assets/cf269219-df98-4aad-a815-bbbd4061880a)
![Captura de tela 2024-09-21 155105](https://github.com/user-attachments/assets/f38ae4e7-839d-4a2b-9d02-4337f5590d7b)
![Captura de tela 2024-09-21 155210](https://github.com/user-attachments/assets/e0c7b760-eadf-483c-877a-5285b0594fa2)

https://github.com/user-attachments/assets/9e6e3c3c-aa6d-4faf-b6d6-9e3a662c14ad

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 12, 2024 Flutter version is 3.22.2
- Platform: Testing only Web
- Browser name and version: Testing only on android Browser 
- Operating system and version affected: Testing only on android
```

### Additional Information

At first I thought it was a bug on the page, I created a new page and the problem continued, I created some new projects and the same thing, I thought it was some character that was causing the problem, but as you can see it is happening with plain text, so I don't know what it could be.

**Comment by paulperez-dev** [comment]
Hi @LeandroGowes,

I wasn't able to reproduce the behavior you're seeing. Have you considered disabling the Android back button on those screens?

**Comment by LeandroGowes** [comment]
When passing parameters to other screens and back, do I have to do something extra to avoid problems? If this didn't happen to you, I must be doing something wrong.

**Comment by paulperez-dev** [comment]
Hi @LeandroGowes,

Not exactly. This behavior can vary depending on the device manufacturer and the Android version or customization layer.

Were you able to resolve the issue by disabling the back button (by toggling the option in FlutterFlow)?

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
