### ISSUE TITLE
flutterflow iPad iOS ui builder keyboard dropdown issue

### ISSUE THREAD

**Issue by HugoLeGoff** [FlutterFlow/flutterflow-issues#3870]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm currently building an app in the iOS iPad FlutterFlow application. Since the last update, I'm facing an issue with the dropdown button in the UI builder. When I tap on it, the keyboard appears, preventing me from selecting an option. If I tap to hide the keyboard, the dropdown closes.

### Expected Behavior

I expect to be able to close the keyboard and then choose the dropdoxn option. So if you know a setting or if I ll have to xait the next update of flutterflow

### Steps to Reproduce

Open any dropdown of ui builder

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i/LlvJdPvs9D1a6JbsBv9Ts5JWI3U7g7ku5RaCosfZT2BLMcec/RVERWXtO4YWNcOVqZp2oW08qMvfHtVPFfKTOrb4Q4+rhQFDnwRXK6brbTFJWgW3NBHp5WCkyu0qSkkx1TLsledCFm3zvzAt6UQnTdHqK0IlQ4Dq/LZO4=

### Visual documentation

Exemple with a backend query :

<img src="https://github.com/user-attachments/assets/64894f57-2147-4cb7-882b-7582790cc9b7" alt="backend query example" width="300"/>

When I tap on equal to, keyboard shows and if i hide it, it closes the dropdown like the first picture : 

<img src="https://github.com/user-attachments/assets/098c7f7c-93eb-4ad4-a1ec-7321fd0ca2ae" alt="dropdown closing example" width="300"/>

### Environment

```markdown
- FlutterFlow version: last
- Platform: iOS iPad
- Operating system and version affected: iPad air
```

**Comment by zhenyu-hong** [comment]
Are you editing in the ipad's browser?

**Comment by HugoLeGoff** [comment]
> Are you editing in the ipad's browser?

Thanks for your reply, no i'm editing in the flutterflow app from the app store, but before the last update it wasn't like this, I think they put the dropdowns searchable so now it shows the keyboard.

**Comment by HugoLeGoff** [comment]
I find the solution, it works if I put the small iPad keyboard
