### ISSUE TITLE
Deploy to AppStore is not working from last 2 days. 

### ISSUE THREAD

**Issue by vebhapvt** [FlutterFlow/flutterflow-issues#3871]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unable to push to app store failling with issue as mentioned below.

</x-turndown>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}

#### Failed Step: Flutter build ipa and automatic versioning

Archiving com.mycompany.myloan...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: G7NN2TTRMF
Running pod install... 2,455ms
Running Xcode build...
Xcode archive done. 7.2s
Failed to build iOS app
Error (Xcode): Provisioning profile "Allows to track you lending along with interest ios_app_store 1727012395" doesn't support the Push Notifications capability.
/Users/builder/clone/ios/Runner.xcodeproj

Error (Xcode): Provisioning profile "Allows to track you lending along with interest ios_app_store 1727012395" doesn't include the aps-environment entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update.
/Users/builder/clone/ios/Runner.xcodeproj

Error (Xcode): Signing for "ImageNotification" requires a development team. Select a development team in the Signing & Capabilities editor.
/Users/builder/clone/ios/Runner.xcodeproj

It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.
Encountered error while archiving for device.

Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1

### Expected Behavior

publish to be working as normal as used to be before.

### Steps to Reproduce

just click on the publish to appstore on mobile deployment tag.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi87huIxOxMtF+KqAK+xWjiUXGUMcX5Ir1utsewgjGKL1BqQTPcj4YhduTfbmaVNcJlKaq3Mdp/OMkuzDNcJcCzOubb5czZd+Sg/0e2iWVpSrBquwYkF8JNNWG2au4cHZkAolBO1pLlYc22CYP++sSjTDFOu/Zwh9f6PHaOI=

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform:web
- Browser name and version: chrome
- Operating system and version affected: windows
```

### Additional Information

Unable to push to app store failling with issue as mentioned below.7

**Comment by Alezanello** [comment]
Hi there!

From the logs you shared, it looks like the issue is related to the Push Notification configuration in your iOS project. To resolve this, you'll need to configure your keys in the Apple Developer Console by following the steps outlined here: [iOS Push Notification Configuration Guide](https://docs.flutterflow.io/concepts/alerts-notification/push-notifications/#only-for-ios-configuring-ios-app).

Let me know if you need any further assistance!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
