### ISSUE TITLE
Local Run: Resolving Dependencies: Because every version of flutterflow_debug_panel from git depends on url_launcher 6.2.5 and app_name depends on url_launcher 6.3.0, flutterflow_debug_panel from git is forbidden.

### ISSUE THREAD

**Issue by rodseventup** [FlutterFlow/flutterflow-issues#3873]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Resolving dependencies...
Because every version of flutterflow_debug_panel from git depends on url_launcher 6.2.5 and midnight depends on url_launcher 6.3.0, flutterflow_debug_panel from git is forbidden.
So, because midnight depends on flutterflow_debug_panel from git, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on url_launcher: flutter pub add url_launcher:^6.2.5

### Expected Behavior

works

### Steps to Reproduce

Test Local Run with  Launch URL inside app

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i8rl24pNoelf0L6JYPpVgiAXHGk7R7gk0+puWQo8J5DaPOxzP/TBaldWUs+0YX9MemKGinoyp//emvPDGPlfIgeaRoB5/85xWDnveGq5acWTC7ueYm5/DfpMGFyn5MCrhyRAFOxickVh6lyMI9iXHybbQrLVPUUNQ+WZNZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="798" alt="Captura de Tela 2024-09-22 às 21 38 39" src="https://github.com/user-attachments/assets/099ccd91-e403-45ab-a0a8-35d3913aac58">

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform:All
- Browser name and version:All
- Operating system and version affected: All
```

***

# RESOLVED Until FF Fix it!!

## Creates Dependency on Custom Code:
url_launcher: ^6.2.5

<img width="1710" alt="Captura de Tela 2024-09-23 às 16 33 05" src="https://github.com/user-attachments/assets/b309893b-982e-4145-8393-f1415b2e3214">

**Comment by hugojardim** [comment]
i'm having the same issue

**Comment by Harryuxd** [comment]
i'm having the same issue.

**Comment by Luigibro26** [comment]
Same issue for android local run

**Comment by Rak4u** [comment]
Having the same issue Sent from my iPhoneOn Sep 22, 2024, at 21:36, Jaidyn ***@***.***> wrote:﻿
Same issue for android local run

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/FlutterFlow/flutterflow-issues/issues/3873#issuecomment-2367096095",
"url": "https://github.com/FlutterFlow/flutterflow-issues/issues/3873#issuecomment-2367096095",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mpayetta** [comment]
Having the same issue as of today

**Comment by BinitKumarMahato** [comment]
I am also facing the same dependency issue.

**Comment by fabiodalazem** [comment]
Same issue for android local run

**Comment by brrrrsimplydev** [comment]
I literally just took a quick nap and woke up having this issue. LOL! Any workaround or fix? thank you!

**Comment by musubime** [comment]
I'm having the same issue.

**Comment by sunilkeshver** [comment]
I added "url_launcher: ^6.2.5" in custom actions Pubsec dependencies and it's working for me now.

**Comment by brrrrsimplydev** [comment]
thanks @sunilkeshver , now I'm curious why the latest version `6.3.0` isn't recognized anymore?

**Comment by Harryuxd** [comment]
> I added "url_launcher: ^6.2.5" in custom actions Pubsec dependencies and it's working for me now.

Thanks @sunilkeshver 
what was your step by step?
It doesn't seem to work on my end

**Comment by brrrrsimplydev** [comment]
Same, it reverts back to `6.3.0` whenever I try rebuilding the application.

**Comment by kitmansohk** [comment]
![Screenshot 2024-09-23 at 11 16 10 AM](https://github.com/user-attachments/assets/635cf55c-a332-4ccd-8e13-6f19037e1159)

Just add add url_launcher: ^6.2.5 as dependencies in any one of custom actions in your ff project. It will override the version added by flutterflow.

**Comment by Alvigo** [comment]
Same issue for android local run

**Comment by kitmansohk** [comment]
@Alvigo 

Is adding dependencies not working on andriod local run? cause it works on iOS local run

**Comment by ak2003** [comment]
I got the same issue, previously working well without any changes.

**Comment by SimonSoftware** [comment]
Same issue

**Comment by ashish-swami-22** [comment]
Turn off the "Enable Debug Logging" from Local run configuration menu > code export.

**Comment by grosscoding** [comment]
@kitmansohk This just adds another issue, because the action pubspec is invalid now

**Comment by AxelSwiip** [comment]
> I added "url_launcher: ^6.2.5" in custom actions Pubsec dependencies and it's working for me now.

Thanks for your help, it works for me !

**Comment by ghost** [comment]
i have same issue

**Comment by squirrel-o** [comment]
> ![Screenshot 2024-09-23 at 11 16 10 AM](https://private-user-images.githubusercontent.com/11441800/369743157-635cf55c-a332-4ccd-8e13-6f19037e1159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzk0NzksIm5iZiI6MTcyNzA3OTE3OSwicGF0aCI6Ii8xMTQ0MTgwMC8zNjk3NDMxNTctNjM1Y2Y1NWMtYTMzMi00Y2NkLThlMTMtNmYxOTAzN2UxMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4MTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODQ2OTViYTAwMTU0YjU1NjJjZTM4ODgyMWE5NGFiODhjOTkwNWY0MDI2M2RiZTY2N2VhZWJkZjNkMDBlNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dpDLB9qp0VmMexRZVeAi6atbXF3YiUzh96EDWHO9Gj8)
> 
> Just add add url_launcher: ^6.2.5 as dependencies in any one of custom actions in your ff project. It will override the version added by flutterflow.

thanks this solved it for me!

**Comment by rsstevearend** [comment]
adding add_url_launcher: ^6.2.5 to any custom action worked for me too.  Thank you

**Comment by sanjayelate** [comment]
I have the same issue

**Comment by rodrigonunz** [comment]
Same issue here

**Comment by wygud** [comment]
> I added "url_launcher: ^6.2.5" in custom actions Pubsec dependencies and it's working for me now.

this works on the windows desktop app local run for me

**Comment by mpayetta** [comment]
Worked for me, android device local run. Thanks!

**Comment by kantarse** [comment]
Same issue, please fix.

**Comment by Alezanello** [comment]
Hi there!

I'm sorry you're facing this issue, but the good news is we're already aware of it and actively working on a fix. The issue is related to the `url_launcher_ios: 6.2.5` package and its compatibility with the latest Xcode version.

Thank you for your patience!

**Comment by anthonyguzmanlo** [comment]
Agregar la dependencia url_launcher: ^6.2.5, en Custom Code soluciona el problema.

![solucion](https://github.com/user-attachments/assets/64c664f6-dd1d-4919-8914-8637032e7187)

**Comment by rodseventup** [comment]
> i'm having the same issue

Until FF fix it, i resolve adding dependency at Custom Code.
<img width="1710" alt="Captura de Tela 2024-09-23 às 16 33 05" src="https://github.com/user-attachments/assets/c881d77d-2f9b-4877-85a5-4240f88ef19d">

**Comment by rodseventup** [comment]
RESOLVED Until FF Fix it!! 

Creates Dependency on Custom Code:
url_launcher: ^6.2.5

<img width="1710" alt="Captura de Tela 2024-09-23 às 16 33 05" src="https://github.com/user-attachments/assets/6cdc9159-1767-4e4c-b879-7ee8a6386fc6">

**Comment by tizum** [comment]
I'm having the same issue here. It happened after updating the FlutterFlow desktop to the latest version; it was working fine before.
![image](https://github.com/user-attachments/assets/1906629b-a576-41e5-904f-3a12a15c13d2)

**Comment by hugojardim** [comment]
> Agregar la dependencia url_launcher: ^6.2.5, en Custom Code soluciona el problema.
> 
> ![solucion](https://private-user-images.githubusercontent.com/54418702/369993369-64c664f6-dd1d-4919-8914-8637032e7187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMjIxMjAsIm5iZiI6MTcyNzEyMTgyMCwicGF0aCI6Ii81NDQxODcwMi8zNjk5OTMzNjktNjRjNjY0ZjYtZGQxZC00OTE5LTg5MTQtODYzNzAzMmU3MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDIwMDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZDZkMDkzYTllYTZhY2ZhMDEwY2NjYmE5NGQ5NjRiZjQ5Njk2YzkxMjZiMzU2MjU0NWQwZWM5MjFhYzNmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zogqYiQ3P4R98giyI4SfOgDJWCUSiUprfCpQNxtO6Kg)

Gracias! Lo ha arreglado de esta manera

**Comment by radardovinho** [comment]
Same error here. The workarroung works fine too.
Thanks!

**Comment by rodseventup** [comment]
> I'm having the same issue here. It happened after updating the FlutterFlow desktop to the latest version; it was working fine before. ![image](https://private-user-images.githubusercontent.com/6773491/370028348-1906629b-a576-41e5-904f-3a12a15c13d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzcyNTEsIm5iZiI6MTcyNzEzNjk1MSwicGF0aCI6Ii82NzczNDkxLzM3MDAyODM0OC0xOTA2NjI5Yi1hNTc2LTQxZTUtOTA0Zi0zYTEyYTE1YzEzZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDAxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU2MWVjMjczMzhkNjZiYWY3MjNiOTZjYTM4NDlmNzhiODcxOTI1ZjRlZDA5MjliZTQxZjdjN2QyZWQ0ZGM1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IbzSlAHO7bPacukXZzdh-MSh2sIY-CAKHqsK4VERSi0)


RESOLVED Until FF Fix it!!

Creates Dependency on Custom Code:
url_launcher: ^6.2.5

<img width="1710" alt="Captura de Tela 2024-09-23 às 16 33 05" src="https://github.com/user-attachments/assets/cf440169-d345-4bfb-9b98-a7e5aafaa3b9">

**Comment by shadroic** [comment]
same issue atm

**Comment by akscienceltd** [comment]
+1 to the issue!

**Comment by ip6941** [comment]
The problem is deeper, because now in all custom codes I have the same pubscec dependencies. When i added url_launcher: ^6.2.5 is NewCustomAction for overwriting the required version, in all custom codes I have is url_launcher: ^6.2.5 and it overwrote the added dependencies that were there :(

**Comment by Alezanello** [comment]
Hi everyone,

We wanted to let you know that a fix will be deployed shortly to address the issues you’ve been experiencing. Thank you for your patience and understanding as we work to resolve everything!

**Comment by xiaoyaoyun** [comment]
Where can I find the previous version of the FF desktop? Would rolling back to the previous version solve the problem?

**Comment by ryanc4ai** [comment]
FWIW, I just downloaded FF Desktop (5.0.0) and I don't see the issue any more. I removed the workaround described in this issue and started a local test with Chrome which was failing before. Anyone seeing as fixed?

**Comment by ishenko** [comment]
New problem in version 5.0.
**Hot reload** and r**estart app** in local run works on the twentieth try. All members of our team are having this problem on macos. Please fix this

**Comment by akscienceltd** [comment]
After the latest update, the issue seems to be gone. I'm able to have my project do a local device run without the temporary fix. So I guess the issue is resolved.

P.S. I have the Windows FF app V.5.0.0
