### ISSUE TITLE
Walkthrough doesn't focus on my appbar widgets

### ISSUE THREAD

**Issue by giladresisi** [FlutterFlow/flutterflow-issues#3874]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The walkthrough doesn't focus when selecting a widget from the appbar, see the attached video. For other widgets in the page it works fine

### Expected Behavior

I'd expect that for appbar widgets it'll work fine as well

### Steps to Reproduce

Not reproduced on a fresh new project, see the attached video for repro in my current project.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

CAESgAFDZzFVWlhoMFgyWnRkemRxYm5FNUdBSWlSeEkyQ2dwUVlXZGxJRlJwZEd4bEVRQUFBQUFBQURaQU9nWUkvLy8vL3c5QUF0b0JDUWtBQUFBQUFBQTJRT0lCQ0FvR0NQLy8vLzhQK2dNQThnVUpDUUFBQUFBQUFQQS9ZZ0RDQVFBPQ==

### Visual documentation

https://github.com/user-attachments/assets/8a366d48-5709-448e-a31e-0278efcf2365

### Environment

```markdown
- FlutterFlow version: 4.1.89+
- Platform: Web
- Browser name and version: Chrome 128.0.6613.138
- Operating system and version affected: Windows 11 Pro
```

**Comment by Alezanello** [comment]
Hi there!

I just reviewed the project you shared regarding the components. It already includes a walkthrough for the AppBar widget, and it appears to be working perfectly. I haven’t encountered any errors.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a92a1c77-63d9-49da-9cc1-9e0113af5ca8/05ef764a-fc66-4b4f-9cfe-d6890dfc23c8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hOTJhMWM3Ny02M2Q5LTQ5ZGEtOWNjMS05ZTAxMTNhZjVjYTgvMDVlZjc2NGEtZmM2Ni00YjRmLTljZmUtZDY4OTBkZmMyM2M4IiwiaWF0IjoxNzI3MTgxOTExLCJleHAiOjMzMjk3NzQxOTExfQ.QMr6Wtwj-rvXYV4OsVhO4-Qw1B0ggBkQ4L7gZ_yLE1g " alt="image.png" width="1277" height="970" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
