### ISSUE TITLE
Walkthrough doesn't let focusing on widgets within components

### ISSUE THREAD

**Issue by giladresisi** [FlutterFlow/flutterflow-issues#3875]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a walkthrough I can only select a page it'll run on and not a component (which makes it impossible to run walkthrough on dialogs and bottom sheets), and even when selecting a page I can only select widgets which reside directly in that page (which makes it impossible to focus on widgets that reside within components included in that page).
See the attached screenshot which shows I cannot select the text widgets within the selected component in the page.

### Expected Behavior

I'd expect to be able to start a walkthrough on a component and focus on widgets within it, regardless if this component resides within a page or by itself (as a dialog or bottom sheet).

### Steps to Reproduce

1. Create new page.
2. Create new component with at least one widget inside it.
3. Add that component to the page.
4. Create a walkthrough, select this page, add a step and see that the widget within the component cannot be selected.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KzPLl8Y1IseVJ1s7ud8JB/SAWQkR+U40wlsJ9SQEbfbaoG7YMS8+kMxJVXemndGNEL2eGhn4z0+zOkuDMA+UoCxabG6pl+ZdcUQ//RmKmRrnRCpaOXH9RN5tJJVya56WJgyVCWbFZW0Is11OuA/C8cHXDGZDaDTA/J/+JLp3MnGOqQ0SLb3kNh1JWeC/v

### Visual documentation

![WhatsApp Image 2024-09-23 at 09 14 28_a5e8df4c](https://github.com/user-attachments/assets/c76091ec-0be0-468c-b03b-4489da5cfcf0)

### Environment

```markdown
- FlutterFlow version: v4.1.89+
- Platform: Web
- Browser name and version: Chrome 128.0.6613.138
- Operating system and version affected: Windows 11 Pro
```

**Comment by Alezanello** [comment]
You can select the component directly from the Walkthrough menu, and if needed, you can even create a new one!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/194c746a-30a2-4f6c-8385-27a2f83e61d0/884a2001-eff4-430d-8d9d-bf9c191bd74e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xOTRjNzQ2YS0zMGEyLTRmNmMtODM4NS0yN2EyZjgzZTYxZDAvODg0YTIwMDEtZWZmNC00MzBkLThkOWQtYmY5YzE5MWJkNzRlIiwiaWF0IjoxNzI3MTgyMTIwLCJleHAiOjMzMjk3NzQyMTIwfQ.k19zFCjbuxkzElk16zey_jgqRiTUMOcCZbABcw4EItc " alt="chooseComponent.gif" width="1830" height="924" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
