### ISSUE TITLE
Data Types fields require 2 characters, but Firebase supports 1 character

### ISSUE THREAD

**Issue by eiriknh** [FlutterFlow/flutterflow-issues#3878]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Data Schema -> Data Types -> Field name require 2 characters, but Firebase requires only 1 character.
Gives error: Name must be at least 2 characters long.

This is similar to Firebase Collection types, that was changed from 2 to 1 character last year. But to recreate maps and arrays of Firebase-collection one needs Data Types. Those field-names require 2 characters, even though Firebase supports 1 character field names. Which makes it impossible to recreated the Firebase-structure if there is 1 character fields.

Similar issue that was fixed (for Firebase Collection Field name):
https://github.com/FlutterFlow/flutterflow-issues/issues/1438

### Expected Behavior

Data Schema -> Data Types -> Fields should only require 1 character, as Firebase map/json fields can be 1 character. 

### Steps to Reproduce

1. Enter Data Schema tab
2. Data Types tab
3. Add Data Type
4. Add Field
5. Add Field name of one character
6. Error message: Name must be at least 2 characters long.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ek8jcw4lPn7xJ7qX6b8BsnSQRNlw1bZZMiuxhYAwYfIjpE5YEeej+QHZVOMO/dFY3OlmI8Xg109aKuOPDVPktPiiBY65iyc9iFznKJDimVrKhEaiOdUB6AZ9mG2WHzbunhxN+OsxtSVEt1GCyHOfIHyzqHZTPNWo7Pv/9GLzNp3yBLBzCXn0Jg1ZSfCvr

### Visual documentation

Data Types:

![Skjermbilde 2024-09-23 kl  13 31 16](https://github.com/user-attachments/assets/8170ebdb-8a07-4a3e-92c7-8c7270d20e61)

Add Field:

![Skjermbilde 2024-09-23 kl  13 30 49](https://github.com/user-attachments/assets/7206d683-1eeb-4cad-a4cc-0fedbdb9e757)

### Environment

```markdown
- FlutterFlow version: v4.1.89+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  macOs Sonoma
```

### Additional Information

Short field names are often used for positioning (like x and y) of multiple shapes/objects inside a Firebase-document. Thats currently not supported because of the limit.

**Comment by Alezanello** [comment]
Hi there!

Thank you so much for pointing this out. While this isn’t classified as a bug, I’ll close this issue as a feature or enhancement request. Don’t worry, I’ll create an internal ticket to notify the product and engineering teams about your suggestion. We aim to keep the GitHub Issue Tracker focused on reproducible bugs, but your feedback is greatly appreciated!

Thanks again for bringing this to our attention!

**Comment by eiriknh** [comment]
Hi @Alezanello 
Thanks for bringing this to the engineering team. Any news about the status for this internal ticket?

**Comment by eiriknh** [comment]
Hi @Alezanello @wenkaifan0720 @SameerShahzad99 
Any updates on this issue? Where FlutterFlow limits Data Type field name to 2 characters, but Firebase allows 1 character in arrays and maps. Impossible for us to import large project as of now, where some maps in Firestore include x and y field names.
