### ISSUE TITLE
Bug on deployment from GitHub 

### ISSUE THREAD

**Issue by jeffcyw95** [FlutterFlow/flutterflow-issues#3879]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In order to allow user to return back to previous page, I've made all the data to be retrieved by supabase backend query. It works very well as when user go from page A to page B, added some new data, then navigate back to page A, all the query in page A will now be updated automatically.

However, due to the recent problem with Google login on Android in Flutterflow. I am forced to made some adjustment in GitHub and then deploy it from GitHub. However, when you deploy from GitHub, the backend query will not automatically be updated anymore as it should. This makes editing code on GitHub and deploy totally unusable. Hopefully this bug can be fixed.

### Expected Behavior

The backend query should be automatically updated just like how it was in Flutterflow and also normal Flutterflow deployment 

### Steps to Reproduce

Deploy from GitHub and you'll get the same issue

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

GitHub deploy

### Visual documentation

Deploy from GitHub and you'll get the same issue

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: Android and iOS when deploy from GitHub
```

**Comment by Alezanello** [comment]
Hi there!

The code in GitHub should match the code in FlutterFlow. However, since there’s no bug report code provided, I’m unable to check how you've set up the GitHub push. Could you confirm whether the Dart Fix is activated or deactivated?

If it’s currently activated, try deactivating it and deploying again. If it’s deactivated, try activating it and then deploy again.

**Comment by jeffcyw95** [comment]
Hi there, 

Thanks for replying. Yes you're right! It's having the dart fix on that is causing the issue. May I know if there will be any implications when the dart fix is turned off?

**Comment by rzambroni** [comment]
Per the FF Documentation:<br><br>**Run "dart fix"**: Enabling this will run the `dart fix` command when downloading the code. This makes the generated code cleaner and potentially more performant.

More information at the Flutter documentation site: [https://dart.dev/tools/dart-fix](https://dart.dev/tools/dart-fix)
