### ISSUE TITLE
Custom Functions Testing Array/List Documents Bug

### ISSUE THREAD

**Issue by cleanspacedev** [FlutterFlow/flutterflow-issues#388]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When testing your function and one of the vars is a document list, you should be able to add and fill in the documents as you could do before. 

## Current behavior (required)

Cannot edit documents in list. 

## To Reproduce (required)

I cannot test any functions with a list in them. 

## Screenshots / recordings

![Screenshot 2023-01-22 143057](https://user-images.githubusercontent.com/107013961/213936355-8156f076-7ee6-4114-86e3-6b046f6a5f2f.png)

## Your environment

* Version of FlutterFlow used: 
* Platform Windows
* Browser name and version: Chrome Latest, or any browser
* Operating system and version Desktop

**Comment by cleanspacedev** [comment]
Also, on further review, it seems that even when given live documents as an array you cannot access them and it sees it as having nothing.

**Comment by hariprasadms** [comment]
Hi @cleanspacedev - Thanks for sharing the issue details. I can reproduce the issue.

https://user-images.githubusercontent.com/17435678/214638574-9ce49695-6ec7-4dde-ad4e-a8d8f991cb32.mp4

**Comment by cleanspacedev** [comment]
Good to hear. Looking forward to it getting fixed.

**Comment by timfong888** [comment]
I had the same problem and logged a ticket I believe four weeks ago.

**Comment by agreaves** [comment]
Hi @cleanspacedev, thanks for this bug report and sorry for the issue! I've fixed this issue and it should go live on the next deploy!
