### ISSUE TITLE
Stuck on Loading Screen when re-opening app after Apple Sign-In

### ISSUE THREAD

**Issue by godsoninikori** [FlutterFlow/flutterflow-issues#3880]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After iOS users successfully sign in via Apple, then back out of the app, and then try to pull it back up, they get stuck on an indefinite loading screen. Some users have been able to 'Force Close' the app and re-open it just fine, but others have to completely uninstall and reinstall the app. 

https://github.com/user-attachments/assets/0b05bb31-7134-4020-b5a1-a145c0d214ba

*Again, the issue isn't with Apple Sign-In alone, but _after_ trying to re-open the app when already signed in via Apple, and it has happened on all iPhones we've witnessed test the app so far, so we can confirm it is not device or configuration specific. 

### Expected Behavior

We expect iOS users to be able to sign in via Apple and re-open the app with no issues (taken straight to the home page with minimal loading). This works fine for Android devices or anyone signing in via Google.

### Steps to Reproduce

1. Sign in via Apple
2. Close the app
3. Re-open the app (may have to give it some time ~30 min or try re-opening it multiple times, the issue may not occur immediately but will eventually occur)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wh8/l5ZVNxOlJ7qrqaflV+WAWCDp8ULsV09VtcCs8GojnPO0ESs+lYldUOPGod1FpMWKWhT4X/MqNveLLIPYqGwyVb7ZD1rl1VRbwXkWXRJfWEb63b39RP95Mf2qd5LSrqyRQWPVvLV5l3DuPffCUVh7dQLLYOkU8D+a4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/0f3bf61d-e394-4cf6-9c97-be1f912dd0a2

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Mobile
- Browser name and version: N/A
- Operating system and version affected: iOS (version agnostic thus far)
```

### Additional Information

All of our iPhone users (which of course is the majority of our userbase) are prone to this issue if not experiencing it already, and it basically throws a major wrench in the UX as users have to either Force Close the app and reopen it or uninstall and reinstall (we definitely don't want to risk uninstalls as a startup)

**Comment by paulperez-dev** [comment]
Hi @godsoninikori,

Thank you for submitting the issue! I’ve reviewed your project, but due to the complexity, it’s been difficult to identify the exact problem. To help us investigate more effectively, could you set up a blank project with the specific issue steps? Having these details will make it much easier for us to pinpoint and resolve the problem.

We appreciate your understanding and cooperation!

**Comment by godsoninikori** [comment]
Hey Paul,

The issue happens when you try re-opening our app after a successful Apple
Sign-In. So should I create a new project with just Apple Sign-In
implemented? A little confused on what you mean by 'blank project'

Godson Inikori
Founder
(346) 481-9920
***@***.*** ***@***.***>*


*Dine out without doubt*℠

Houston, TX
w. https://quickgredients.com

**Comment by godsoninikori** [comment]
Could you please clarify what you mean by setting up a blank project? This
issue is *very urgent*, we're getting messages from our iOS userbase about
being stuck on the loading screen.
[image: image.png]

Godson Inikori
Founder
(346) 481-9920
***@***.*** ***@***.***>*


*Dine out without doubt*℠

Houston, TX
w. https://quickgredients.com

**Comment by godsoninikori** [comment]
Here's the project ID of a blank project with just the Apple-Sign In steps
configured:
apple-sign-in-issue-6x6bev

Godson Inikori
Founder
(346) 481-9920
***@***.*** ***@***.***>*


*Dine out without doubt*℠

Houston, TX
w. https://quickgredients.com

**Comment by godsoninikori** [comment]
Hi Support,

Sorry I know I've sent a lot of emails but wondering if it would be
possible to schedule a call to troubleshoot this post-Apple Authenticator
issue? It's really impacting our userbase and we cannot afford this as a
startup.

Re-referencing the project ID of a blank project with just the Apple-Sign
In steps configured, per request:
*apple-sign-in-issue-6x6bev*

Godson Inikori
Founder
(346) 481-9920
***@***.*** ***@***.***>*


*Dine out without doubt*℠

Houston, TX
w. https://quickgredients.com

**Comment by paulperez-dev** [comment]
Hi @godsoninikori,

Apologies for the delayed response. I’ll go through your messages and let you know if I’m able to reproduce the issue.

**Comment by godsoninikori** [comment]
Thanks Paul. If possible, I can hop on a scheduled call just to help guide
through the steps to reproduce the issue.

Godson Inikori
Founder
(346) 481-9920
***@***.*** ***@***.***>*


*Dine out without doubt*℠

Houston, TX
w. https://quickgredients.com

**Comment by godsoninikori** [comment]
So we found a support engineer on Reddit & deduced the loading screen issue
is an iOS glitch where iOS doesn't always reload a screen, so the vendor
list API Call doesn't always execute (screenshot)


He's proposed a few solutions, 1 being to just have an intermediary entry
page that automatically redirects to the vendor list page so iOS
likely/should reload on a page redirect.

Another, which we're trying, is a GPT-generated custom widget that forces
the refresh for iOS. I think the first one is easier and more clean.

Godson Inikori

University of Houston | C.T. Bauer College of Business

MS Management Information Systems, Dec '22

☆ Bauer Excellence Initiative Scholar ☆

***@***.*** | (346) 481-9920

**Comment by paulperez-dev** [comment]
Hi @godsoninikori,

I ran your project, but I wasn’t able to log in… it’s showing an error: "configuration not found." Could you please double-check the setup on your end?

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
