### ISSUE TITLE
Images Fail to Load on Template "List13PropertyListview"

### ISSUE THREAD

**Issue by thetommyjun** [FlutterFlow/flutterflow-issues#3881]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The images will not populate in the template "List13PropertyListview".

### Expected Behavior

The embedded images should show up.

### Steps to Reproduce

1. Create project
2. Add premade template
3. Add "List13PropertyListview" template

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Version 129.0.2792.52 (Official build) (64-bit)

### Visual documentation

Just need to reproduce the steps and it will not populate images.

### Environment

```markdown
- FlutterFlow version: Most Recent as of 23 Sep 2024
- Platform: iPhone 13
- Browser name and version: Edge - Version 129.0.2792.52 (Official build) (64-bit)
- Operating system and version affected: Windows
```

### Additional Information

Just trying to get some pictures working

**Comment by rzambroni** [comment]
Hello @thetommyjun, thank you for bringing this to our attention. I wasn't able to locate the specific template you mentioned. Could you please share the bug report code? You can find it by right-clicking any widget in the widget tree. This will help me investigate further. Looking forward to your response!

**Comment by rzambroni** [comment]
Hi there,

We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue, and we’ll be happy to assist you further.

Thank you
