### ISSUE TITLE
Dependency error when building in local test mode or in vscode. The dependencies are built in ff ones.

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#3882]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The application will not build either in local desktop mode or if you download the code and try to build it in vs code. Same errors each time. The application will build in web based test mode, the Lightning symbol, or in Run mode.

![image](https://github.com/user-attachments/assets/48e1bf7b-3e33-4d61-8d4b-c3fb598686a7)

### Expected Behavior

The application should build.

### Steps to Reproduce

Try to use the desktop Local run.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YAW/SkQE9WZ7yhdH03Jk2WmmcK+a3VvtzIN/YEJS2uGq1xyLtyZA3LfEenMpSDEs3pXHx7EtpKCHKYy6avox5vKrNqdCU62VOqJd6uaD7dNub1PFQ7Df6XIZLIo3PuQ0SLb3kNh1JWeC/v

### Visual documentation

The bug code is not relevant by the way as it is not specific to any part of the application.

### Environment

```markdown
- FlutterFlow version: Desktop Latest and Windows VSCode
- Platform: Windows 12
- Browser name and version: Chrome and Edge latest
- Operating system and version affected: All
```

### Additional Information

I noticed that the vs code version was the first to begin to fail about two or three days ago. It seemed OK in the desktop local run mode, and as far as I can remember the errors looked very similar, a conflict of version numbers of the dependencies.

**Comment by Alezanello** [comment]
Hi there!

I'm sorry you're facing this issue, but the good news is we're already aware of it and actively working on a fix. The issue is related to the `url_launcher_ios: 6.2.5` package and its compatibility with the latest Xcode version.<br><br>(A workaround in the meantime is to add the `url_launcher: ^6.2.5`  in a Custom Action)

Thank you for your patience!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
