### ISSUE TITLE
Provisioning profile error?

### ISSUE THREAD

**Issue by lsole** [FlutterFlow/flutterflow-issues#3884]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Today I'm getting this error when publishing to the Apple Store (internal test). It does not seem related to any change from my side... any idea?

Error (Xcode): Provisioning profile "xxx ios_app_store yyy" doesn't support the Associated Domains capability.
/Users/builder/clone/ios/Runner.xcodeproj

Error (Xcode): Provisioning profile "xxx ios_app_store yyy" doesn't include the com.apple.developer.associated-domains entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update.
/Users/builder/clone/ios/Runner.xcodeproj

### Expected Behavior

It should build correctly

### Steps to Reproduce

1. Normal build for iOS

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXicr1z4pNochE+c71LfkwpGQwGUwbUOc7j9VEGAsjCeOuPZk2OuLOQBJDWOqHfHNUPlKkikwG+vzmkuzPKvA4FwyBGKZn+LtxUxDid3OWVL6mC4e0SnZ5L/NRI0il5Jm4nh0nBMVec2QR3E2MPOSQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![ff_error](https://github.com/user-attachments/assets/a8100d93-ca36-4d5d-8e76-21bef2333b16)

### Environment

```markdown
- FlutterFlow version: 4.1.89
- Platform: macOS
- Browser name and version: iOS native app
- Operating system and version affected: all
```

**Comment by Alezanello** [comment]
Hello!

It looks like the issue you're facing is related to the Provisioning Profile in your Apple Developer account. To resolve this, you’ll need to add the entitlement for Associated Domains. This is not specifically a FlutterFlow issue, but I’m happy to guide you.

You can follow the steps outlined in this documentation to get it set up: [Adding Associated Domain Capability](https://docs.flutterflow.io/concepts/navigation/deep-dynamic-linking/#22-adding-associated-domain-capability-to-app-store).

Please let me know if you need further assistance!

**Comment by lsole** [comment]
Thank you very much for your help. So I realize this is because of adding deep and dynamic linking. OK, I'm going to do as suggested. I think the issue can be closed.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
