### ISSUE TITLE
Push Notifications Continuous Out of Date Issue when switching desktop to web app

### ISSUE THREAD

**Issue by monocat** [FlutterFlow/flutterflow-issues#3886]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Push Notification reverts to Out of Date after deployment when reopening in a different app. i.e. reopen on desktop app after deploying in web app, vice versa.

### Expected Behavior

Push Notification should remain Deployed unless changes have been made.

### Steps to Reproduce

1. Login to FF Web
2. Set up Push Notification settings,
3. Deploy
4. Exit project
5. Reopen project in Mac OS Desktop

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4eiM/qx5BgobhG0LrUdO9VhmEvCDs2U40/lOxHcAwbCLmrPO0HPuj+QHZVOMO/dFY3OlmI8D4J/vuPv4bLFMc9PiisG9xxwc1uSxXgZF+5MMW7PrqCeXFRI+NTGGmHzbTYpR14NvZ0WCVh2Fy2IuytYBbrJpjwOTERL/qjEKXA+GiUAAzKXn0Jg1ZSfCvr

### Visual documentation

![image](https://github.com/user-attachments/assets/4ae09c65-6544-4cc0-95c5-8dfb1528f947)

### Environment

```markdown
- FlutterFlow version: v4.1.89+ (web), v4.1.90 (desktop app)
- Platform: Mac OS, web
- Browser name and version: Brave Version 1.69.168 
- Operating system and version affected:
```

**Comment by laughingbuddha24** [comment]
I have this issue too

**Comment by Alezanello** [comment]
Hi there!

I'm sorry you're experiencing this issue. I’ll be closing this as a duplicate, so please refer to the following issue for any updates or follow-ups: [https://github.com/FlutterFlow/flutterflow-issues/issues/3883](https://github.com/FlutterFlow/flutterflow-issues/issues/3883)

Thank you for your understanding!
