### ISSUE TITLE
Team code library sync issue with Team Design Library and Project

### ISSUE THREAD

**Issue by RutujaGole1827** [FlutterFlow/flutterflow-issues#3888]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The changes made in Team Code Library yesterday have not reflected in the Team Design Library and the project in which Team Design Library is getting used.
**Changes made in code ** -  added Phospher icon package and library and fontfamily used for icon widget replaced with phosphorIcons from MaterialIcons.
changes made at Time - 11:25 PM (23-Sep-2024)

![image (2)](https://github.com/user-attachments/assets/61e7416b-d173-4237-a449-04b0e396bb52)

![image (1)](https://github.com/user-attachments/assets/36837f67-1231-4d7b-a3eb-e64487d56807)

This above is one example but its same for all other custom code also, the changes made in team code doesn't get reflected in design library.

### Expected Behavior

The changes made in the Team code library must be reflected in the Team design library within 1-2 mins.

### Steps to Reproduce

1.Develope a custom widget in team code library
2. Add the created widget in team design library.
3. Make some changes in already developed custom code in the team code library.
4. use the same team code in any team design library
5. check whether original code has been replaced with the new changes made in team code, with new updated dependancies and packages.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMn6xItNocNA7c/TbcZvoycUNmJ5TL03pu0bFEggGLbrBIYMaffRcVVtYN+8TFVfKEWKpGMGw+zQjeGWGsBfPTecfL45yLVxWAmVc3O/aoTQPqW8f396TO9mGUiZ06SRhglvOthsWU5i1FyqH+ivf3LZJ5v4Zwh9f6PHaOI=  

### Visual documentation

![image (2)](https://github.com/user-attachments/assets/d63e9e6b-92cd-44cc-b3ad-be980bbfd690)
![image (1)](https://github.com/user-attachments/assets/ba0acce1-76b2-4468-bc75-678b67ead3fc)
![image (3)](https://github.com/user-attachments/assets/55e49fb0-8f8d-4753-8b09-ca7836460faf)

### Environment

```markdown
- FlutterFlow version: 4.1.86+
- Platform: Web/Desktop
- Browser name and version: 129.0.6668.59 
- Operating system and version affected: Windows 11 Enterprise 23H2
```

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by RutujaGole1827** [comment]
Hi,
It still there sometimes. When we add a lager code then also the
flutterflow gets hang. Again and again window becomes unresponsive.
