### ISSUE TITLE
visual artifacts in action flow editor when changing actions

### ISSUE THREAD

**Issue by Mar10Ru** [FlutterFlow/flutterflow-issues#3889]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever I change a conditional action in a specific action flow, the background and other UI elements change color and visual artifacts cover parts of the flutterflow UI making it impossible to make changes of action settings.

### Expected Behavior

No visual artifacts appear when working in the action flow editor.

### Steps to Reproduce

1. select specific widget
2. open action flow editor
3. navigate to specific condtional action
4. enable action
5. visual artifacts appear

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hvHl34x1rt9c+KqIbcdr/Sc5KWI1RpIJ0exRaCorB5DoPZsUecmkM0RtOOG5YH9mO1mgp2oW0dbvjezLKPACA02Zbt181rVycDuVbEG5Sr61FJWgemgkBdtUCFS/36u33R1+NvRiLHBi2juqCunIfA/vJoTbOzM0Dq/LZO4=

### Visual documentation

<img width="928" alt="{61EBC513-4AB3-4675-9B29-B441331B91C6}" src="https://github.com/user-attachments/assets/0cb7cdfc-06e8-40ea-b627-9931ba9382a9">

### Environment

```markdown
- FlutterFlow version: v4.1.91+ (released Sep 12, 2024)
- Platform: Desktop
- Browser name and version: desktop client
- Operating system and version affected: Windows 11 Home (23H2)
```

**Comment by Alezanello** [comment]
Hi there!

I'm sorry you're experiencing this issue. Could you help us by recording a video that shows exactly how to trigger the problem? This will help us replicate it more effectively.

**Comment by Mar10Ru** [comment]
Hi there. Thanks for the prompt reply. Please find enclosed the screen recording. As you can see from the recording, I can reproduce the visual artifacts only for one specific conditional action.

https://github.com/user-attachments/assets/be065c83-4ebe-4705-8b99-5d6929383f18

**Comment by Alezanello** [comment]
Hello,

I apologize for the delayed response. If you're still experiencing this issue, please reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They have the appropriate tools to help debug and resolve the situation for you.

**Comment by Mar10Ru** [comment]
My solution was to delete the entire action flow. I haven't been able to reproduce the visual artifacts in FF version 5.0.2.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
