### ISSUE TITLE
Check Errors button "wont click" when supabase enabled and custom function present

### ISSUE THREAD

**Issue by kyle-wils** [FlutterFlow/flutterflow-issues#389]
Since V 3.0 Jan 20 2023 - Flutter 3.3.4 -- my custom function returns error and it wont let me check errors (click button and nothing happens)

I discovered it happens if my supabase settings are enabled.  I have attached screenshot to assist in resolving bug. Hope this helps as i'm looking forward to testing out supabase but I must deactivate until resolved so my custom functions still work.  Can't wait to see built in supabase auth or some clear steps to move to that as well for auth!

<img width="864" alt="jdu58fkjhbsqzp0bxbjmuusclu08" src="https://user-images.githubusercontent.com/93795296/213937527-82bf8e5b-f872-4eb3-9476-a5c494ff3987.png">
<img width="864" alt="batn9qou5goh5erupyyci137zdjb" src="https://user-images.githubusercontent.com/93795296/213937530-0c6d83ea-eb1f-42ca-9e73-cc0c0d571c6c.png">
<img width="864" alt="qhv75tnkc4ie0e7kf9qftcg2mg1n" src="https://user-images.githubusercontent.com/93795296/213937533-331d1320-1119-4d7a-b808-baae97596fef.png">
<img width="864" alt="064hgpse523h1ade3uvcn42pb6b5" src="https://user-images.githubusercontent.com/93795296/213937534-e059eb90-0f11-4ce2-ac1b-3c3e1be36d66.png">

**Comment by victoriahuang1** [comment]
Hi @kyle-wils , thanks for the report. Could you include a bug report code to make it easier to debug? You can do so by right clicking any widget from the widget tree panel.

**Comment by kyle-wils** [comment]
> Hi @kyle-wils , thanks for the report. Could you include a bug report code to make it easier to debug? You can do so by right clicking any widget from the widget tree panel.

IT4gz8nLuJROj7xZ7qXqce9aiiEXKUQ3R700sNobbxAjIoDoPJkUaffCTEtpXtzjSmNLKEWJgmA1+N7OkuHfE/YCNk6CG9g6wc8JcBbjXl3kEuzyT+3IHDUHZbsSXTTm

**Comment by victoriahuang1** [comment]
Hi @kyle-wils , I just fixed a bug related to Supabase and custom code. It should be related to this issue. It should be fixed once it is deployed
