### ISSUE TITLE
Querying subcollection fails when selecting a user reference other than authenticated user

### ISSUE THREAD

**Issue by laughingbuddha24** [FlutterFlow/flutterflow-issues#3890]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I query a subcollection for a single user selected with the Users Reference 
1. it succeeds when the reference is the authenticated user
2. it fails for any other user reference. 

### Expected Behavior

The query should complete whether the Users Reference is the authenticated user or another user.

### Steps to Reproduce

1. query the users collection in any way that enables you to select a single user ref from the returned results
2. create a second query for a subcollection under the users collection and set the Users Reference from a variable from the first users collection query
3. try to output a value from the subcollection query

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shcmAx491ofpE0LruY8dB/WIUH198RoE8scp/bxIgGIDzPOw+ZPWkcltWYM/nYHw/fESmml8ew/T2i+PhGvUVFzCWf6I++ZNUYAz/RkCna5OBEpCwen95BeFRBW6DyqWRnxRCIuhqdVY72Du6BOmUZ3TfHpy0ImdISq/LZO4=

### Visual documentation

![query-bug](https://github.com/user-attachments/assets/fb9e09c2-7ae6-442e-8c38-41706189994b)

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: Android / iOS
- Browser name and version: Chrome 128.0.6613.139
- Operating system and version affected: Windows 11 Home Version 23H2
```

### Additional Information

I have tried this with both queries triggered in an action and queries set on a container. I have tried setting the Users Reference from a document, action output and page state and in every case the query fails.

**Comment by Alezanello** [comment]
Hi there!

After reviewing your Firestore rules, it looks like you’ve set the User and User subcollections to allow only the authenticated user to access their information. To make this data accessible to others, you can adjust the rule to "Users Collection" or "Everyone," depending on your desired access level.

**Comment by laughingbuddha24** [comment]
You're right it was the rules. The error log didn't indicate that so I'll need to find some way to identify that as a cause.

Thanks
