### ISSUE TITLE
Issue at firestore indexes deployment

### ISSUE THREAD

**Issue by RaulTridi** [FlutterFlow/flutterflow-issues#3891]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

basically, i cant deploy the firestore indexes on my project, even if everything is right set, my users permissions on firebase already have the firebase@flutterflow.io set as user and still have the issue. I tried others firebase projects too and the problem persist, the error showed on the deploy try is "Error: Failed to create server directory. Please contact support@flutterflow.io"

### Expected Behavior

on click of the deploy button, i expect that firestore indexes was deploy, but it was not

### Steps to Reproduce

1. Create new project 
2. Set firebase authentication on config
3. Create a firebase project on firebase site
4. Set firebase@flutterflow.io as a editor on users setting of your firebase project
5. Get project code on firebase, then paste it on firebase project setup from Flutterflow
6. Click "deploy" button on firestore indexes
7. Error show

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx892pbxC+pDILO1snQMwGkQ5a7sviu5+FBQaI+PvP7QIZuPCUxJoSOqHTXNUCk6KrzgdwNLFvdriV8I4ZBOrbNw/zJZXUxDiLU2jVbqSCqiWSnZ9EcpVCB2vyJ+r2hNCXepvZXgXw0OQBumub3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Captura de tela 2024-09-24 090252](https://github.com/user-attachments/assets/fa2317ff-ad61-4e20-9d4a-b039ced4e9a3)
![Captura de tela 2024-09-24 090152](https://github.com/user-attachments/assets/c0a1f1a0-584d-475f-b1f8-c0d2aa1e29b6)

### Environment

```markdown
- FlutterFlow version: v4.1.91+ (released September 11, 2024)
- Platform: Web, Windows Desktop 
- Browser name and version: Chrome Versão 128.0.6613.138 (Versão oficial) 64 bits
- Operating system and version affected: Windows 10 Pro Versão 22H2
```

### Additional Information

Im from Brazil, sorry for the bad english

**Comment by Alezanello** [comment]
Hi there!

After connecting your Firebase database, did you click on "Regenerate Config Files"? It's important to do this before attempting to deploy the indexes and rules. Have you tried that yet?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d0c86596-92f4-42e7-a567-3aea4032743b/886982a3-6539-4e73-9968-1c60d5f05df4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMGM4NjU5Ni05MmY0LTQyZTctYTU2Ny0zYWVhNDAzMjc0M2IvODg2OTgyYTMtNjUzOS00ZTczLTk5NjgtMWM2MGQ1ZjA1ZGY0IiwiaWF0IjoxNzI3MTg0MTU5LCJleHAiOjMzMjk3NzQ0MTU5fQ.y4kXnaSV4Zvk8ddvM6DnqiaFo57UTqLk86_XXvnCWoY " alt="image.png" width="670" height="140" />

**Comment by RaulTridi** [comment]
yes, i've already tried this but the problem continue
