### ISSUE TITLE
All FlutterFlow apps do not support scrolling on new "iPhone Mirroring" macOS feature

### ISSUE THREAD

**Issue by John-DreamLabs** [FlutterFlow/flutterflow-issues#3895]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Scrolling does not work on FlutterFlow apps inside the "iPhone Mirroring" tool introduced with macOS Sequoia. I have tested with a number of apps I have personally built as well as the FFDC app. 

### Expected Behavior

Scrolling should work. All other apps I have tested, that are not built through FlutterFlow, are working as expected. 

### Steps to Reproduce

1. update your mac
2. connect to iPhone mirroring
3. open any app made with FlutterFlow
4. try to scroll

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

macOS

### Visual documentation

[https://www.loom.com/share/b2f5dfb931184f7bb5046544bee3514a?sid=600c5bef-eb6a-4551-b7c6-e1ee6e2d9e0f](url)

Video shows me opening an app not made in FlutterFlow, scrolls in every direction. Then app in FlutterFlow, does not scroll. 

### Environment

```markdown
- FlutterFlow version: whatever version the FFDC app is
- Platform: macOS
- Browser name and version: n/a
- Operating system and version affected: Sequoia 15.0
```

**Comment by paulperez-dev** [comment]
Hi @John-DreamLabs,

The Flutter team will need to address this issue and release a new version. Once that happens, we'll need to migrate to the updated version.

For reference, you can track the issue here: [Flutter GitHub Issue #152711](https://github.com/flutter/flutter/issues/152711).

Closing this for now.

**Comment by John-DreamLabs** [comment]
@paulperez-dev Looking at the issue you linked, it seems like there is a fix from their side. 
https://github.com/flutter/engine/pull/55285

**Comment by paulperez-dev** [comment]
It seems that it hasn’t been released in a version yet. Once it is, we’ll also need to support that version.
