### ISSUE TITLE
Chart widget 'Label Interval' property reverts to default

### ISSUE THREAD

**Issue by wagerwiseadmin** [FlutterFlow/flutterflow-issues#3896]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On the chart widget the 'Label Interval' property for the Y axis reverts to the default value of 10 whenever changed. I have only tested this on the line graph option. 

### Expected Behavior

The updated value to remain and be correctly reflected on the UI.

### Steps to Reproduce

1. Add Chart Widget, select line graph and add use Numbers List as the data source
![Screenshot 2024-09-25 at 7 17 44 pm](https://github.com/user-attachments/assets/29f40008-004c-48eb-82b5-92b7f38595a1)

2. Change the Label Interval on the Y axis to any value other than 10 and either wait a few seconds or click off the widget and check the Label Interval value (it reverts to 10)
![Screenshot 2024-09-25 at 7 20 35 pm](https://github.com/user-attachments/assets/e79814b3-b28f-4770-b2f9-029d62515af2)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l7c92rsMA+KrqKMBaiigRI0MAWOcViuxHcx4YIZDpP+xzZc7BbUNKT8O+fAlcJE6Wkjozpc3IjYfqUfpfCziCbph/0JVASQ/gQky6b5iaCJaWbXF8TZ9hGGKFyImnnRQlNsFpWGw11GeHNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/169fc1e2-1b5c-4c15-804d-56e4e53e7299

https://github.com/user-attachments/assets/3d693725-a44c-42e9-b623-c1de512d7765

### Environment

```markdown
- FlutterFlow version: v5.0.0+
- Platform: Web
- Browser name and version: Chrome 128.0.6613.138
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. The good news is that it's a known problem, and the team is already working on a fix! I'll close this issue as a duplicate and continue to track updates under the main issue here:<br>[Main issue link](https://github.com/FlutterFlow/flutterflow-issues/issues/3857)

**Comment by leostaclara** [comment]
I have exactly the same problem in Flutterflow when I use 
I use the chart and try to define it in the chart properties Y Axis > Properties
label interval the value is not defined, returning to 10. The records are dates in the format M/d H:mm
