### ISSUE TITLE
Images disappears when scrolling. Web App on iOS (Android is OK)

### ISSUE THREAD

**Issue by JuraskiBart** [FlutterFlow/flutterflow-issues#3897]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I’ve published to the web my app stage version. And when scrolling down, some images, text and buttons disappears
Can you check why?
I’ve tested it on Androind, and there is no issue there. Only iOS. 
Tested on ios 18.0. Iphone 12 mini

![Olie-notOK](https://github.com/user-attachments/assets/d90a3161-27fe-4be9-9a59-b47ee575c7bb)
![Olie-ok](https://github.com/user-attachments/assets/7dd2a210-262c-4875-a491-393628e62e59)

### Expected Behavior

Images, text nad buttons should be visible all the time.

### Steps to Reproduce

1. Go to https://olie-app.flutterflow.app
2. login as test user: juraski+olietest@gmail.com (P: 123456)
3. scroll down to see images disappears  

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESicn15ZNgod9Y7rX6bsd6hQIgQ0QnU7gnlO1ucx43JbKuPIYhO8/4YUNKTNOjfW5Yf2GIhXMB+NbwvvD1F/cnAAqafL5M0JVAaDnwRmquMqqlDbuaP3JAQN5Yf0vEyLaJkBN+Xdp0Slo412DyNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/1c61dfe4-7b7e-4b04-9dfc-fc605103ab22

### Environment

```markdown
- FlutterFlow version: 5.0.0.
- Platform: iphone 12 mini, iOS 18
- Browser name and version: safari on iOS 18
- Operating system and version affected: iOS 18
```

**Comment by paulperez-dev** [comment]
Hi @JuraskiBart,

Could you kindly verify if enabling the Canvas Kit resolves the issue?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ae959810-0b66-41be-a178-e35112040ba3/44eb8697-8de5-4e03-8bc1-5a15daaa4a0f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZTk1OTgxMC0wYjY2LTQxYmUtYTE3OC1lMzUxMTIwNDBiYTMvNDRlYjg2OTctOGRlNS00ZTAzLThiYzEtNWExNWRhYWE0YTBmIiwiaWF0IjoxNzI3NDQ5MTI2LCJleHAiOjMzMjk4MDA5MTI2fQ.m4TYKGTsjo2cEIxdjTlYEtc-pDruM-desRmYXTr_pYQ " alt="image.png" width="1608" height="428" />

**Comment by JuraskiBart** [comment]
Yes it does! Thank you 👌
