### ISSUE TITLE
Null Check issue in calling the function

### ISSUE THREAD

**Issue by vairagadeharshwardhan** [FlutterFlow/flutterflow-issues#3898]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom function testing in Flutterflow is working but when I test the app in browser testing the same function is not working properly.
![image](https://github.com/user-attachments/assets/46638ac9-82ee-40f7-af07-8014d7ec4001)
![gmapURLWaypointFunctionTesting](https://github.com/user-attachments/assets/fff022c5-35ef-49b4-9d9f-3c04af45054c)

### Expected Behavior

It should launch the URL, in the browser or in the mobile app.

### Steps to Reproduce

Create a custom function to get Google Map launch URL as a string
Then given waypoints as strings via a function which takes lat lan as input for waypoint stops.
and call the function in a button action to launch the URL.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESjMmB+cpgrsQF0LncacZqhQAkH1x/bZJEl9caZAEgIZTxPYkDPOr+V1hCX/2QS35qMFWWkmMHweDxud/LEcYBITeBQoNozrpMaQ7LfH2nVK6UPc+dPnR6J5tPC0i/1J2jgBFTNrJhZXAAw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![wayPointConsolSS](https://github.com/user-attachments/assets/6c32a515-aabb-42dc-8610-660f90ff0606)

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Web
- Browser name and version: opera
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!

Everything looks good, and the screenshot showing how the `LaunchURL` function is being called is perfect. Could you please send a video demonstrating what happens when you launch the URL? How does it display? It might be necessary to encode the waypoints.

You could try:

```dart
String encodedWaypoints = Uri.encodeComponent(waypoints);

String url = 'https://www.google.com/maps/dir/?api=1&origin=$origin&destination=$destination&waypoints=$encodedWaypoints';
```

<br>At the end of the function to encode the waypoints

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
