### ISSUE TITLE
Bug with security rules inside FF

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#3899]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to change the security rules. More precisely, I want to change the "Tagged User" field in a few collections. The field is currently set to "LimitedTo" and I want to change it for "Ref". Everytime I change the field, after a few seconds, it automatically reverts back to the previous field (i.e., after changing the field for "Ref", it reverts automatically to "LimitedTo"). 

I can deploy the new rules in the 3-4 seconds it takes before the field reverts to the prior value, but the field reverts back anyway in FlutterFlow after the deployment. 

### Expected Behavior

I should be able to select the fields I need and deploy the new rules without the fields automatically reverting back to their prior value. 

### Steps to Reproduce

Create collections, try changing the fields for "Tagged users" under Read (I suspect the same problem would occur for Create, Write and Delete).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A, the bug is not in the widget tree

### Visual documentation

See this video of the bug :
https://vimeo.com/1012834105/312123e460?share=copy

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: I use the FF desktop app
- Browser name and version: N/A
- Operating system and version affected: Windows 11 Home
```

### Additional Information

PLEASE DO NOT try changing the security rules inside my project since we are in production.

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. Could you please share a bug report with us? It doesn't matter if it's from the widget tree—having that information will help us better understand and debug the issue you're facing.

**Comment by Alexandre-Lemyre** [comment]
Hi. How can I generate a bug report if I am not in the widget tree? In the widget tree, I can right click on any element and generate the bug report. In the Firestore settings (see the video), I have no idea how I should proceed. 
Thank you.

**Comment by Alezanello** [comment]
Generate the Bug Report Code from the widget tree don't worry 🙂

**Comment by Alexandre-Lemyre** [comment]
Here it is : IT4KivHq389Pm8tD1aXIccdFoCYXGDsnRYIoltVDYwkbCJCsG7YAW/SkQE9WZ7yhdH03O2eZoz4z7vTLkczIN8EqNRauc5xcwbl+bhXxQTi5aYysDbW3dn97HtpKC2Kl356ZoBR4FOhuL3wC1EOuPe7LThfBN4+xO0g3Jc+YFJP5o3/uQ0SLb3kNh1JWeC/v

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
