### ISSUE TITLE
FAB throw error when setting from ChoiceChips

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#390]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Text widget in extended FAB should be able to be set to ChoiceChips

## Current behavior (required)
When text widget in extended FAB is set to ChoiceChips it throws a "Unexpected null value." --> even though "Initial Option" is set already.

## To Reproduce (required)
1. Create new page
2. Add container widget - choicechip and FAB
3. Set choicechip initial option to Option 1
4. Put text widget in FAB and link it to choiechip
5. Click Run
6. "Unexpected null value" is thrown

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1.
2.
3.
4.

### Bug Report Code (required, generate from Widget Tree)
IT8kzsnf05dNrsRE1rruccBv+SAXHGk7UIIv0NZ+FEggGL7yEoouZM/STFhuYsyHfwlmP2KZhmcBpvDPv/zpBPkFGxCBGZxnwqVpQx7jcGqRacmmPJDgPXcmGflQC1Sg4Kuw3QlvKsYzFxxchgPKRw==

## Context (required)
just trying to change the text on the FAB to what the user chose in the choicechips

## Screenshots / recordings

![Screenshot 2023-01-23 at 3 53 52 AM](https://user-images.githubusercontent.com/110169434/213937772-1f26b2f1-1e7a-47f6-bc48-5c9e8ea5da75.png)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop):  web
* Browser name and version: chrome latest
* Operating system and version (desktop or mobile): mac latest

**Comment by victoriahuang1** [comment]
Hi @Zack1010OP , thanks for bringing this bug to our attention. Unfortunately, we will not be prioritizing fixing this bug at the moment.
But, there is a work around. In general, it's best practice to include a default value when using variable values. You can do so by inputting a value here:
<img width="651" alt="Screenshot 2023-02-01 at 5 08 48 PM" src="https://user-images.githubusercontent.com/16326980/216113704-e4709cf8-8976-41e2-b385-665298c23253.png">

Hope this helps!

**Comment by Zack1010OP** [comment]
Thank you Victoria!Warmest regards,IsaacOn 2 Feb 2023, at 1:13 AM, Victoria Huang ***@***.***> wrote:﻿
Hi @Zack1010OP , thanks for bringing this bug to our attention. Unfortunately, we will not be prioritizing fixing this bug at the moment.
But, there is a work around. In general, it's best practice to include a default value when using variable values. You can do so by inputting a value here:

Hope this helps!
