### ISSUE TITLE
Custom Icons Broken on Desktop App

### ISSUE THREAD

**Issue by timothynice** [FlutterFlow/flutterflow-issues#3901]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom Icons show as question boxes on desktop app, works perfectly on the web version of flutterflow.

### Expected Behavior

I'd expect to see all the icons properly on desktop app

### Steps to Reproduce

1. Import custom icons on desktop app (sometimes all of them were wrong, sometimes only some of them were wrong, names were mismatched)
2. See the issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ksmBw5NIm9tJ+Krib8BsqDgWHFs7UOYrksJTdwg8KOvUB+x/evWkQBRoQvXmS1VYPESmmk8f0+vHvt/1Lfo5OS6rbqk6zrgNZTyXXni5e5OBPsywWEZfBZ5mC0Cby5jQgRZ4VchZc1Zg702yfeStTjfAJZi2ImdISq/LZO4=

### Visual documentation

Desktop (Issue)
<img width="1138" alt="desktop" src="https://github.com/user-attachments/assets/35e07b5c-36e5-4fe7-832a-f6185ba75efd">

Web (No Issue)
<img width="1230" alt="web" src="https://github.com/user-attachments/assets/5a9e68ae-5c6d-4de6-b211-b294857be8c9">

### Environment

```markdown
- FlutterFlow version: latest as of 9/25/24
- Platform: Mac Desktop
- Browser name and version: Chrome Latest
- Operating system and version affected: Mac OS 14.6.1
```

**Comment by paulperez-dev** [comment]
Hi @timothynice,

Could you kindly verify if the solution mentioned here works for you?

[Custom icons not showing correctly in FlutterFlow MacOS app IDE · Issue #3661 · FlutterFlow/flutterflow-issues](https://github.com/FlutterFlow/flutterflow-issues/issues/3661#issuecomment-2327168709)
