### ISSUE TITLE
Cant create custom widgets

### ISSUE THREAD

**Issue by JacquesvanWyk** [FlutterFlow/flutterflow-issues#3903]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/d65c3d17-affe-41ae-88ec-3f8d6d9f5629)

When trying to create a new custom widget I am getting errors and seems like nothing can be imported. Also can add to pubspec.

### Expected Behavior

Expected to be able to just create new widget and have no errors when starting

### Steps to Reproduce

1. Create custom widget

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TiMrlsIp2odtJ+KqJacAxgiAXQz81RYI7j+xETRIgHOusEOwQPsz8bXFJXMu4d2xUJGH8sGAI7tLSvuDPUcYBEwqIQ75NyLpUczmVQXK7V4zQPKuKdEQnM9JmIH690KCOiiMlANd1ckYH1GWACum9bD/BNYDBIFgdNM6iWZ3Ojk6lAnnBKzhmtmNecCfn

### Visual documentation

![image](https://github.com/user-attachments/assets/e150a6bb-5ed9-4ca7-9b40-41a2d719d9f8)

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by rzambroni** [comment]
Hi, Thank you for your report and for bringing this to our attention.

I attempted to replicate the issue on a few projects, but I was able to successfully create custom widgets and add custom dependencies without any problems.

However, while reviewing your project, I noticed that the name of your custom widget has been changed, but the code is still referencing the default name. Could you try re-adding the boilerplate code so it aligns with the updated widget name? This may help resolve the issue.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/484d252d-fdd7-4d6b-adc6-50db64a3dc43/54702ec4-a3d0-44a9-867c-e655c90be793?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODRkMjUyZC1mZGQ3LTRkNmItYWRjNi01MGRiNjRhM2RjNDMvNTQ3MDJlYzQtYTNkMC00NGE5LTg2N2MtZTY1NWM5MGJlNzkzIiwiaWF0IjoxNzI3Mjk1NDkyLCJleHAiOjMzMjk3ODU1NDkyfQ.VoFY3jME9IrnGn9S0kfC9A9-OI5BhraKVBlbsr6RZ1Q " alt="image.png" width="1615" height="718" />
