### ISSUE TITLE
Tagged users in Firestore security rules are not working

### ISSUE THREAD

**Issue by hannahjkn23** [FlutterFlow/flutterflow-issues#3904]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently if I select the field where my user/my users are tagged in in Flutterflow or try to setup this manually in firestore (resource.data.field) I can just the a loading widgets but have no access to the documents anymore.

### Expected Behavior

The expected behaviour would be that the user can exactly see the documents they are tagged in. 

### Steps to Reproduce

1. Setup Firebase with Authentication
2. Sign up a user
3. Create a new collection with the field owner and another field like name
4. create page where you can create a document in that collection or create the document manually, important: set the field owner to the users uid
5. create a page to view the document(s) of that collection
6. go to the security rules in flutterflow and for read (in the new collection) select tagged user -> owner 
7. deploy and try to read the newly created document(s)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHl3It2ocsG0a6JKO0wvyk7OWEcTOURiO0bFDsdF4iuPOxzacnsZRduTsO/TVVXKEWGrEAFp8Llkt7xDcADFEirfqJ6+ZNUWg7yeEi/aouVBZe0QEBCQZljIFSs356rpRYlNtphSkIFw2WqI96AbB7sNZv7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-09-25 203824](https://github.com/user-attachments/assets/bc21f161-cf8c-40b2-8cf2-6c08bc7338bc)

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: Windows, MacOS
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?
