### ISSUE TITLE
List Name Doesn't Display When Certain Options Are Selected

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#3905]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting conditional values like "List is set and not empty" or "list contains item", the name of the selected list disappears. This doesn't happen for every type of conditional selection, only some of them - and it doesn't seem to happen on backend queries. Only page state and app state variables (from what I can tell). 

### Expected Behavior

The name of the list I'm using when setting variables should remain visible. 

### Steps to Reproduce

1. Create a new page
2. Create a new page state list
3. Add conditional visibility to a component, select the page state list, and select "list is set and not empty" or "list contains item". 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiufqxIt2xcdG0KX5bcZFnjoUOXolTL07ttYbZxUjIuPtBJh+PODRalhCOO2hYHlhHFn8/X8H0N7vvdr1OscqF0icR65FyLpIVDzKe3q8R4ymCJaCQWt8GfthGhGm4cHUghEmLfVYdVYl7ziUCNyiYHfdGZu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/90dabbb1-cb27-47c6-99e3-0e72ff641abe

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: Windows
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### Additional Information

While this may seem minor, not being able to see the name of the list I've selected for a variable can significantly slow down development, especially on more complex projects. It makes it especially difficult to go back to old projects (that I may not remember every detail of) and make updates, because I can't be sure which page state is being referenced, and I may have to reset it just to find out.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. Your feedback is valuable, especially when it comes to improving what is displayed in certain circumstances. However, this seems more like a feature or enhancement request rather than a bug. I’ll go ahead and close this issue, but I’ll label it as a Feature Request and pass it along to our engineering team for consideration in future updates.

**Comment by MartinLockheart** [comment]
I thought that since the list name was being displayed for other list selection options that it was a mistake to leave it out of some of them. But if that's not the case, then I understand, thank you.
