### ISSUE TITLE
Variables Aren't Setting

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#3906]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On many occasions, I will try to set a variable and it will fail to set after clicking confirm. 

This issue isn't perfectly reproduceable. However, with more complex variables, if it fails to set the first time, it will continue to fail until I have clicked elsewhere on the page and then clicked on the variable to set it again.

### Expected Behavior

I should be able to click "confirm" when setting a variable, and the variable should be set.

### Steps to Reproduce

1. Attempt to set a complex variable (one that requires an if/then statement or one that requires filtering a listview)
2. The variable may be empty after clicking "confirm" 

This is not perfectly reproduceable, but might be more likely to occur after shifting focus to another window on the PC, then shifting back to Flutterflow. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiufqxIt2xcdG0KX5bcZFnjoUOXolTL03pu0bFEggGLbrBIYMaePSQBZWTsjiY0FpKEWJnkAJ/tGKhc7DLvc5Hy2BG4tz1aV6bwzjXnm/aoSpDsyoS3FTL+FWfmKD0cCFnB1TCPV2V10j72a2fu+XSj/qNrn4Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/1bceba5b-ba22-4ee8-9726-0957a9f75c9e

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: Windows Desktop
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### Additional Information

This issue has been going on for at least a month now. It's slowly down my work because I have to redo things over and over again - and I never know for sure when or why the variable will fail to set.

**Comment by MartinLockheart** [comment]
Here is another video from a few minutes after I uploaded this one. It's been a month of this (at least), and last time I submitted something about this, I was told that the issue was under investigation. No updates, and this is what I'm dealing with on a regular basis. 

https://github.com/user-attachments/assets/9d9fdb48-93f8-45f8-8b64-55105ad93beb

**Comment by John-DreamLabs** [comment]
+1 on this

**Comment by mscott-redshift-tech** [comment]
+1 on this, we see it from time to time, especially on move complex vars.  Basically everyone has been trained to assume ti will fail and do it a second time.  Seems to primarily occur on the second of the 2 vars in a condition, but has occurred other places as well such as in parameter lists for actions or for detailed steps off a list item.

**Comment by nev-21** [comment]
It is happening to me too.

Please fix it.

**Comment by nev-21** [comment]
It is still happening, maybe not a big deal, but it is a bad developer experience and productivity, like @mscott-redshift-tech said it, sometimes happen in complex var, so it has to be made again.

A defensive practice is to copy and then paste on complex logic, but this is time consuming too.

**Comment by MartinLockheart** [comment]
Yeah, if I'm setting a complex variable and the UI doesn't remove from the
red "unset" warning on the main variable when I'm done, I copy and paste
it. If I don't, everything I did disappears 100% of the time.

**Comment by MartinLockheart** [comment]
Any update on this? It's been a few months (at least) that I've been dealing with this issue.

**Comment by MartinLockheart** [comment]
I don't know if this is helpful, but I've noticed it happening most often when I'm setting a variable and I type into the search. It seems to reset 99% of the time I do that.
