### ISSUE TITLE
Visualization problem using Pageview

### ISSUE THREAD

**Issue by mircozamprogno** [FlutterFlow/flutterflow-issues#3907]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi,
I have a page with a pageview set of 7 pages. In the first three pageview I visualize data from a supabase table.
I have two queries to load this data, the first one from the "On page load" action, the second one is from a "Search" icon function.
I have two outputs from this query so I cannot set the value as output from a query.
The problem is that the first page is correctly visualized but the second and the third is not the first time I run the query.
I tried two different ways to setup the values of these fields but the problem stay the same.
The first method is to use a Set Form FIeld for each field after the query, the second is to setup a page state variable and select the value from the page state.
The problem does not change, I am stuck on this.
I produce a video to describe the problem otherwise it is impossible to believe only from the description.
Thanks for your support and I am available to produce other details.

Mirco

### Expected Behavior

I am expecting that the values in the input fields are always correctly visualized regardless the supabase query I am using.

### Steps to Reproduce

1. Create a set of pages inside a pageview
2. Query a table with all the data to be distributed across the three pages
3. From the query use the Set Form Field to set the data for all the pages
4. Check if the visualization of the data are correct.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oz8/q289OxMtH17qBY8dF9CQvJkw1bIZMlepudw4YJZPNG4gIZfTBXE9uOP25dghif1qZjnIxzPCPm9z1EcFdGAqZUaU7+altEQ3dXnmlVYSKPLrtOEdEGshWJh3H0MOJuRBCPslpWU413FOyevO/aBLXJ7roC2oZIeajMqfXrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

I have uploaded a video witht the description of the problem, I hope you can download it in time, it will be easier to understand the problem instead of pictures.

[https://we.tl/t-yH5PgFPJzA](https://we.tl/t-yH5PgFPJzA)

### Environment

```markdown
- FlutterFlow version: 5.0.0 24.09.24
- Platform: Web
- Browser name and version:
  Chrome Version 128.0.6613.139 (Official Build) (arm64)
  Safari 17.5
  Firefox 128.0
- Operating system and version affected: Mac OS Sonoma 14.5
```

### Additional Information

This issue is blocking me to proceed with the development of the application, in this way my application is not reliable and usable.

**Comment by mircozamprogno** [comment]
Hi, I would like to confirm that the problem is in the Pageview, I define a new page without the pageview using exactly the same Set Form in one page and everything is working fine. Thanks

**Comment by paulperez-dev** [comment]
Hi @mircozamprogno,

Thank you for sharing your project! I’ve reviewed it, but due to the complexity, it’s been difficult to pinpoint the exact issue. To help us investigate further, could you set up a blank project with the issue steps clearly laid out? This will make it much easier for us to troubleshoot effectively.

Without these details, it might be challenging for us to fully resolve the problem.

Thank you for your understanding!

**Comment by mircozamprogno** [comment]
Hi Paul, it is not so easy to isolate the topic because in the background there are several interaction with other part of the application and supabase tables, it requires some time.
What if I give you a special account to test only the part that is interested, there is only one page involved in the problem (autoContracts) and I can tell you how to login and visualize the problem.
Let me know what you think.
Thanks

**Comment by paulperez-dev** [comment]
Hi @mircozamprogno,

I’m okay with that approach if the issue cannot be replicated on a blank project.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
