### ISSUE TITLE
Branching, commit source dropdown list is grey.

### ISSUE THREAD

**Issue by Unity2Blender** [FlutterFlow/flutterflow-issues#3908]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

New Branch -> Advanced options -> Commit Source

-> The Dropdown list of latest commits appears to be grey filled and names not visible.

Although on clicking on Dropdown item, it does select the commit name but still the User experience is terrible.

### Expected Behavior

The list of latest commits made on a branch should be visible in the Dropdown

### Steps to Reproduce

New Branch -> Advanced options -> Commit Source

-> The list pops up.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40s8j15a1PoOVg7qXyUsZXvAAnNn58bbsRoNtraCosfZT2BLMcec/RVERVXs+4TwlEeGG0q2oW3OjOuIXXFPE4NTOCbLZ+/7VQSAGVYF6RRcmXFJWgWkFTO99RI0eB5MOZoR4nIftpZVob3WeYOd/KTXTACZOwIkceD6/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/e18cbc45-7009-4080-b474-3ceb7b7711b7)

### Environment

```markdown
- FlutterFlow version: 5
- Platform: Windows 11
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @Unity2Blender,

Thank you for bringing this to our attention! I’ve confirmed the issue you’re describing and will escalate it to the engineering team so they can start working on a fix.

We appreciate your report and will keep you updated!

**Comment by Unity2Blender** [comment]
Thanks @rzambroni ,

Will look forward to seeing it get fixed.

**Comment by Unity2Blender** [comment]
Hi @sbis04, Although this bug has been marked as completed, The Dropdown list still appears as grey.

Please look into it.

**Comment by sbis04** [comment]
@Unity2Blender the fix will be included in next week's release.
