### ISSUE TITLE
Dynamically generated  Textfields wont allow inputing 

### ISSUE THREAD

**Issue by nigelmsipa** [FlutterFlow/flutterflow-issues#391]
![untitled](https://user-images.githubusercontent.com/62001350/213940686-821adc59-944b-4099-9c2b-ba4b823c4725.gif)
![untitled__1__AdobeExpress](https://user-images.githubusercontent.com/62001350/213940707-945e795a-2572-4176-8ae7-04f09f830890.gif)
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When the text input is selected, one should be able to select a value to input, the keyboard should not disappear, and the page should not refresh. 

## Current behavior (required)
When text input is selected the page refreshes and the keyboard disappears before one is able to input a value.

## To Reproduce (required)

1. Create a new page
2. Add a column widget
3. add a text input widget 
4. make the text input widget into a component 
5. query from the parent column to dynamically generate the text inputs 
6. set the initial text widget from the query value 
7. download apk 
8. Observe that the project does not allow inputting text to dynamically generated text fields, the keyboard disappears and the page refreshes. 

## Context (required)

Much of my app requires the text input fields to be dynamically generated, I cannot input into these text fields, hence I cannot release my app until this issue is resolved. 

## Screenshots / recordings

![untitled](https://user-images.githubusercontent.com/62001350/213940668-a44c6967-fca8-45eb-aa99-4cd852b41681.gif)## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
Hi @nigelmsipa. I think this issue is related to this one: https://github.com/FlutterFlow/flutterflow-issues/issues/279.

**Comment by hariprasadms** [comment]
Hi @nigelmsipa - I have seen this issues as well. As @wenkaifan0720 mentioned, this should be related to #279. and also related to accessibility and semantic label. As per latest release, if you have enabled semantic feature, disable it and try how it goes. 

![image](https://user-images.githubusercontent.com/17435678/214642389-66ebe9f2-ffd4-4c1d-a46c-fc6af8981917.png)
