### ISSUE TITLE
Dev Enviroments not working at Run mode sessions

### ISSUE THREAD

**Issue by Rasochii** [FlutterFlow/flutterflow-issues#3910]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using "Dev Enviroments" in a project as a way to differentiate urls from production and approval APIs. When running in "Test mode" the "apiUrl" variable that I use works with the url that I entered, but in "Run mode" this variable is empty and my requests end up not working.

### Expected Behavior

I hope to be able to use "Dev Enviroments" regardless of whether it is "Run mode" or "Test mode". I also hope it works in deployment cases.

### Steps to Reproduce

1. Start a "Run mode"

2. Open DevTools and look at Network

3. Enter the following data in the "CPF" and "Senha" (Password) fields: 544.250.170-05 and 123

4. Click on the green button labeled "Entrar" to try to log in

5. View the request url. It will be empty where the apiUrl should be

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i/Hq3ItOocsA7qXxbflFmiA5KW4lUIInjtVRaCosfZT2BLMcec/RVERtZ9PgTUFqJGD8v2oW0630juD9A/UnNRSWRaZk+YdhEhfxc3GXRKavFJWgWEB6J8RbFUjD3Jmj2RB+NvhqckZh3Tmqe+6yQjTvNu71CkcsDq/LZO4=

### Visual documentation

![Captura de tela 2024-09-26 110128](https://github.com/user-attachments/assets/6bc72a49-f98f-45db-9668-677dcd5184c7)

### Environment

```markdown
- FlutterFlow version: v5.0.0+
- Platform: Web
- Browser name and version: Brave v1.70.119
- Operating system and version affected: Win11
```

**Comment by Alezanello** [comment]
Hello!

I took a quick look at your project, and it seems that the **apiUrl** variable is not being set in your actions. You'll need to assign the **apiUrl** variable from your environment variables to the API call for it to work properly.

Let me know if you need further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/39160f90-502e-41d4-938c-0867d84605d8/9722ecff-536a-46bd-98cc-2e170f1ffdb5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zOTE2MGY5MC01MDJlLTQxZDQtOTM4Yy0wODY3ZDg0NjA1ZDgvOTcyMmVjZmYtNTM2YS00NmJkLTk4Y2MtMmUxNzBmMWZmZGI1IiwiaWF0IjoxNzI3MzgzNzEwLCJleHAiOjMzMjk3OTQzNzEwfQ.VP-MK0_GhEoItwzZ9-i22RMg7CMxVQtBewKf7s6U6Wg " alt="image.png" width="666" height="370" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/09744770-57c9-4c54-9160-938e92660c84/f4e3b445-18ac-4429-84b9-bf3627660719?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wOTc0NDc3MC01N2M5LTRjNTQtOTE2MC05MzhlOTI2NjBjODQvZjRlM2I0NDUtMThhYy00NDI5LTg0YjktYmYzNjI3NjYwNzE5IiwiaWF0IjoxNzI3MzgzNzEwLCJleHAiOjMzMjk3OTQzNzEwfQ.QY056FXvFj2gtQ5quDfq1XnVvYX81QwhAH26bAnJxhU " alt="image.png" width="629" height="591" />

**Comment by Rasochii** [comment]
Hello!

I thought I wouldn't need to add it to the actions since it already has a default value, being the **apiUrl** of the **Environment Values**. In test mode and downloading an apk it works normally without needing to add a value.

**Comment by Alezanello** [comment]
Correct!<br>However, the default value may vary between environments, so it’s preferable to set it using environment variables. Have you tried doing that?

**Comment by Rasochii** [comment]
So, my two environments have the apiUrl filled in, so it wouldn't make much sense in run mode for it to be empty. But, I tried to use the way you suggested and it still doesn't appear haha

I'm going crazy about this already, man

I think it's not working because I'm not able to compile my custom codes (specifically, Actions and Widgets). I don't know if it has something to do with it, but at the moment, it's what makes me have a little hope that it will work.

I'm getting a bug every time I try to compile (Unknown error compiling custom code), but I'm seeing it with FF support

**Comment by arnaud-penet** [comment]
Hi, we are facing similar issue with Dev Environment and Run mode.
see https://community.flutterflow.io/ask-the-community/post/dev-environments-not-working-as-expected-flutterflow-5-0-mR3KPVsFQPr4PL2

**Comment by Alezanello** [comment]
Hello!

We’re sorry for the inconvenience you’ve experienced with the run mode. The good news is that our team is already aware of this issue and has an internal ticket tracking it. It’s scheduled to be fixed in the next production release.

I’ll link this GitHub issue to the internal ticket and close it as a duplicate, so the team can focus their efforts on resolving the main issue. Rest assured, this is being addressed.

Thank you for your understanding, and we appreciate your patience!

**Comment by arnaud-penet** [comment]
:wave:  when is this issue to be solved ? 
Souldn't 'closed:duplicate' indicate what is the duplicated issue ?

**Comment by icestormpure** [comment]
> 👋 when is this issue to be solved ? Souldn't 'closed:duplicate' indicate what is the duplicated issue ?

It's fixed now
