### ISSUE TITLE
FF Windows Stable: Saving Auth Credentials + Setup Local Run not save in the system !

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#3911]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Now I need for every launch of my windows system to re sign and re-setup the local run and also sometimes working in FF Desktop and when there's crash I need to do that again and again !!!

### Expected Behavior

Its should save the auth credentials in the system and local run because sometimes I just wasting time on this.

### Steps to Reproduce

Restart the syetem
Make something really heavy like custom widget or huge widget tree for crash FF app because its happen many time 
Then you will need to do waht I said again

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeifHf05NPn71K0KXcLMZV/AMwJ0gnU+crte5+d0shfJD2BIoUfs74SxdLYtehT1BDPk6L/XgD0PvFjofPKcAoGw2BQNhx+IRXQTnhXXKlWq6uCpe0W3dAFphnJ0C55sG7phFNA7F2ZXwE7E2DfPCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/4b5371ef-d31f-4d53-81c1-b5db80a7dcb6)
![image](https://github.com/user-attachments/assets/ae69020a-f7d9-463d-a82a-79917894673e)
![image](https://github.com/user-attachments/assets/31c85fa9-536d-4085-9ec6-09cf91bc7ae9)

### Environment

```markdown
- FlutterFlow version: v5.0.0
- Platform: Windows
- Browser name and version: Chrome 125
- Operating system and version affected: Win 11
```

**Comment by paulperez-dev** [comment]
Hi @ImadBourmane,

I wasn’t able to replicate the issue on my end. Could you please try reinstalling the app and see if that resolves the problem?

Let me know how it goes!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
