### ISSUE TITLE
Project Dependencies -> Can't build APK if imported Lib has a Streaming API call definition.

### ISSUE THREAD

**Issue by Unity2Blender** [FlutterFlow/flutterflow-issues#3913]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have imported my Project Library which contains an API Call definition of Gemini API using streaming.

Now when I import this Library into the project in subject, It throws an error while building apk **because Flutterflow isn't generating *api_streaming.dart* in the imported library package of this project**. This further leads to a compile time error as one of my screen's widget & model dart files import it automatically because Flutterflow has imported it.

### Expected Behavior

Exported package's API_streaming.dart should be also imported with the Project code as it throws a compile time error because an import statement depends upon it in investigation_result's widget and model file.

### Steps to Reproduce

Try to Build/Generate APK from the Developer Menu.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CkvLl/ZNgobhc0M71bcdvmikUJlB6RYINldVuSUsYJ5PMC+wIZ/f7XFRuTde0S1FiPGGJ+XoK08nemvHxLu1cNU2uQYBawbhyWwHJXkK6RZSSC7rpZW5/Df1mCWqC1p2CniYlFMpiLVkt3HGMAO6WfDHsQ72xIXowReaIC5KK2SrDX1iXc2URm05KZDPz

### Visual documentation

Here you can see that *api_streaming.dart* is being imported from my Library along with *api_calls.dart*.

![image](https://github.com/user-attachments/assets/7da723f2-3301-438c-87bc-82f2b0da03cd)

Here you see that bug that *api_streaming.dart* is not added to the Project's code while api_calls.dart is present and compiles just fine.

![image](https://github.com/user-attachments/assets/36e22254-9078-4254-ad9c-30ec05661b58)

Here finally due to the absense of *api_streaming.dart*, It leads to this error when I try to **Build APK**.

![image](https://github.com/user-attachments/assets/cd7c1805-7427-4547-a368-13372b35892c)

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: Windows 11
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello,

While attempting to replicate the issue, I encountered a similar (or possibly related) problem. Unfortunately, I wasn’t able to debug it, as I’m unable to download the code, publish to the web, or view the code directly from FlutterFlow — it results in a grey screen.

Here are the steps I followed:

1. Created a new project using the **Gemini Chat** from the Marketplace (to test the Streaming API with libraries).
2. Published that project as a library.
3. Created a new project and imported the project library.
4. Set up a button to trigger the Streaming API call from the library.

At this point, everything crashes.<br><br><br>Library Project: [https://app.flutterflow.io/project/qa-2108-t-j5o1i4](https://app.flutterflow.io/project/qa-2108-t-j5o1i4)<br>Real Project: [https://app.flutterflow.io/project/qa-2108-c-utth3a](https://app.flutterflow.io/project/qa-2108-c-utth3a)

**Comment by Alezanello** [comment]
Hello,

While trying to replicate the issue, I encountered a similar (or possibly related) problem. 

I'll escalate this ticket as high priority to the engineering team for a deeper investigation and possible fix. Thank you so much for bringing this to our attention!

**Comment by Unity2Blender** [comment]
Hi, what's the status of this issue, I am still facing it in my workflow.

**Comment by AnushaFF** [comment]
Thanks for reporting the issue! The fix will be released in the upcoming releases.
