### ISSUE TITLE
Branches can only use the Production environment

### ISSUE THREAD

**Issue by MTzukanov** [FlutterFlow/flutterflow-issues#3914]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When in a branch, I cannot choose on any other environment except Production.

Quote from page: https://docs.flutterflow.io/testing/dev-environments/

> If you are building new features, you should consider using [Branching](https://docs.flutterflow.io/testing-deployment-publishing/branching-collaboration/branching.md). You can develop and test new features on a new branch by selecting a development environment. Once tested, you can merge the branch into main and switch to the Production Environment to go live.

In practice I cannot choose an environment, effectively this defeats the purpose of environments/branches.

### Expected Behavior

In a branch, I can choose any environment.

### Steps to Reproduce

1. Switch to a branch
2. Try switching environment

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjcmA/Y9Itb1K+KnqdMExmmIRM0MdXOczitVEew4bCIj4P5oAeszRXBdCTdCzaH5peFSIhk4ypfT7uPLhK+w3NRKcb7pfwbV6bxPPbFOtMbGYCKiBPnNPPNJjC26k4beJ2hZ7AMZaSC0C702IBefJZz6Cf9qOYwx5e6fDbOY=

### Visual documentation

![20240927_132329](https://github.com/user-attachments/assets/e35291a7-637a-4152-94c7-06aed799cbf6)

### Environment

```markdown
- FlutterFlow version: 5.0.0+
- Platform: Any
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment]
Hi @MTzukanov,

I wasn’t able to find the quote you mentioned on the documentation page. The cursor behavior for that option is intentional at this time. I'll check with the team to see if support for this is planned in the near future.

Thank you for your patience!

**Comment by MTzukanov** [comment]
Hi @paulperez-dev , thank you for your reply. 

The quote is from FAQ, here is a screenshot:
![image](https://github.com/user-attachments/assets/bc13a2eb-8464-4289-bd5b-90a8f443760d)

I don't really see how it can be intentional, I am hugely puzzled. I don't think the idea is that you intentionally can develop on only on production...

I would expect the default environment to be Dev/Development and not Production, then it would could make sense, but can't see it the other way around.

**Comment by leighajarett** [comment]
Sorry about that! Working on a fix!

**Comment by thesadic** [comment]
I have the same problem.

**Comment by ready4sea** [comment]
Could this be linked to the fact that downloading the code through the flutterflow_cli command line does not work anymore ? (taking ages and eventually failing on a project where I set up a development environment)
#3951

**Comment by leighajarett** [comment]
No it's not related, we just missed removing the restriction to only allow changing environments on the main branch during the launch. We are working on a fix and hoping to have it in the  release next week.

**Comment by MTzukanov** [comment]
@leighajarett, I highly appreciate your and all the team's work!

Apparently you already released a fix for this issue, but I am still not able to use the envs properly. I found a couple more issues with environments, not sure if I should open new tickets, but listing here anyways:

- The original environment (that is called Production now), had previously generated a Firebase project for me (before envs), and it is now somehow forever linked with that environment, even if I replace the Firebase project with a new one. This link always takes me to the old Firebase:
![image](https://github.com/user-attachments/assets/4071fabb-b834-4654-9ecc-ae6c46531caf)
Nevertheless, I seem to be able to work with the new environment, but only on main. When I switch branch, I get all kinds of error like Firebase not connected/not found or just "error". This prevents me from using branches for production deployment. For now I abandoned this env and created a new one called Prod.

- When I switch an environment on main, it is switches for other team members as well.  So I cannot deploy to Production from main either, because other people might be working and need the Dev env.

- I switched to a branch and created a new environment - this environment exists only on this branch and not on main. I found it weird, looks like a bug to me. I did not find it to be part of the code. If it is intended, then maybe you can document it.

- Currently I cannot connect one Firebase project to two environments. I find this to be useful sometimes, because the environment variables are different, even though Fb is the same, so maybe you can rethink this limitation, if there is no real issue preventing this.

- Stripe integration desperately needs to use the environments as well. For now I still need to switch it manually for production :)

I am just about to launch the project to prod and your env feature came out at a perfect moment, so that I can try to use it and also help FF team debug it.

For now I came up with this:
- the main branch would be my trunk and the latest dev version is here, developers can use branches
- when I want to deploy to prod, I create a release branch, switch to Prod env, go to Stripe integration to change it to prod, then deploy (maybe deploy to Staging first).

Maybe you can describe in the documentation how you envisioned the workflow with environments.
