### ISSUE TITLE
Android AAB file doesn't build with the increased build number

### ISSUE THREAD

**Issue by henrroga** [FlutterFlow/flutterflow-issues#3916]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I do a mobile deployment for Android and download the AAB file, I cannot do a release in Play Store because it tells me you already have released this build, although I increased the build number in FlutterFlow.

### Expected Behavior

The release in Play Store should work correctly getting the new build number from FlutterFlow.

### Steps to Reproduce

1. Deploy to Internal track in Play Store
2. Download the AAB file
3. Upload it in Play Store
4. Check the version code

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThcj6389Om+FC+KriL8BKqDssGUMdXOczitVEew4bCIj4OqQLO8z7M0xuTdyzaH9Yf1qgkl0dpKGOk/DxDsFdCzGuR7pC1odqYBPPbEK5brqbEZaNOGpCRZ9WGkyA17SRpCYkKtpvWCEHwUyMO+i9Fj6Cf9qOYwx5e6fDbOY=

### Visual documentation

![CleanShot 2024-09-27 at 16 01 06](https://github.com/user-attachments/assets/331c25a9-a627-4310-ba8d-aeff17f7a3b8)
![GYd2U7mWkAATjUI](https://github.com/user-attachments/assets/4597f5b9-5cda-42c3-b801-f8fb9f2b80c0)

### Environment

```markdown
- FlutterFlow version: v5.0.0+ (released Sep 27, 2024)
- Platform: Web
- Browser name and version: Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.1.1
```

### Additional Information

I cannot release an update to Android, this seems really urgent!

**Comment by paulperez-dev** [comment]
Hi @henrroga,

It looks like the issue is related to the KeyStore file. The AAB file isn’t being generated, and the one being downloaded is from the previous version. Could you please verify your KeyStore file and try again? Let me know if you need any further assistance!

**Comment by henrroga** [comment]
Hey @paulperez-dev, you were right! I was inputting the wrong keystore password. I should've checked the logs, but the flow has always been to see a Failed (VIEW LOGS) error and downloading the AAB file to proceed with manual release in Play Store. It would be helpful if there was no AAB download if an error like this were to occur, or created at time for the files.
