### ISSUE TITLE
Conditional Statements broken in 5.0.1 always reports Conditional action must have a True or False action.

### ISSUE THREAD

**Issue by mscott-redshift-tech** [FlutterFlow/flutterflow-issues#3920]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Adding a Conditional Action always reports an error of _Conditional action must have a True or False action_, regardless of the value included.  I have tried created a new project, and putting the constant True into the condition, as well as the a single condition of Random Int Equals Random Int.  In all cases the error still flags (see screens)

<img width="756" alt="Screenshot 2024-09-27 at 3 45 10 PM" src="https://github.com/user-attachments/assets/b711629c-b589-47a2-85a7-d2eed2d4aac1">

<img width="712" alt="Screenshot 2024-09-27 at 3 45 26 PM" src="https://github.com/user-attachments/assets/33c9b6a7-1757-4167-ad14-4a226e0a78de">

<img width="751" alt="Screenshot 2024-09-27 at 3 45 17 PM" src="https://github.com/user-attachments/assets/0ab6eda9-04c1-4527-9da0-3bb71268f1c8">

And trying with Random Int.  
<img width="1072" alt="Screenshot 2024-09-27 at 3 42 38 PM" src="https://github.com/user-attachments/assets/6fde7aae-c9c6-4ff2-bd02-40489ec0ae15">

<img width="1068" alt="Screenshot 2024-09-27 at 3 42 47 PM" src="https://github.com/user-attachments/assets/afb350c5-65d4-4145-9080-0755a7d9d795">

We see this issue on Mac Desktop and on Web since the 5.0.1 release.  Basically any conditional added causes an error regardless of the condition. We have tried this across both new and existing projects.

### Expected Behavior

A boolean value should be accepted. Prior to 5.0.1 this was always the case.

### Steps to Reproduce

1. Create a project
2. Create a page
3. Add a button
4. Add an action (i.e. Navigate Back)
5. Open the action editor
6. Add a conditional action
7. Try putting any boolean/condition into the conditional action.  The error will flag regardless of what is in there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlsjfsI12oblE7c+BbPlFoGAUJjM6UIIKltVuEA8YfIOrG7YAW/SkQE9WZ7yhdH03OWD8mn00/tKNkdzIN/A6Ok2YbN1Iz7lqcAvgUkmXbKbQC6i8empfONpKC3a60Ji3rSVNBPBqSWQM32aIDezIc3PBJ5CzIVUzAsqINqnPs3PuQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="756" alt="Screenshot 2024-09-27 at 3 45 10 PM" src="https://github.com/user-attachments/assets/538033e1-53f7-47db-8f5a-20f223cbc2fe">

<img width="712" alt="Screenshot 2024-09-27 at 3 45 26 PM" src="https://github.com/user-attachments/assets/8204ff37-238d-4d9d-8ddb-418461c4a699">

<img width="751" alt="Screenshot 2024-09-27 at 3 45 17 PM" src="https://github.com/user-attachments/assets/22d494a2-e66f-4ab2-b4cb-beac0c5a7939">

And with Random Int instead

<img width="1072" alt="Screenshot 2024-09-27 at 3 42 38 PM" src="https://github.com/user-attachments/assets/d47ce531-99cb-4b71-be7b-1e1999ddaea1">

<img width="1068" alt="Screenshot 2024-09-27 at 3 42 47 PM" src="https://github.com/user-attachments/assets/f69e0577-5f52-47e1-93e7-8dc1d511f45a">

### Environment

```markdown
- FlutterFlow version: 5.0.1
- Platform: Web and Mac Desktop
- Browser name and version: Chrome
- Operating system and version affected: Mac Sonoma 14.6.1, but all I suspect
```

### Additional Information

No work can be done without a basic Conditional Action.  The entire team is unable to work and we have an upcoming release.

**Comment by rzambroni** [comment]
Hi there,

Thank you for your report!

The error message you're seeing, "Conditional Action must have a True or False Action," means that the system requires instructions on what to do when the condition is met. You'll need to specify the actions to be performed in both the True and False cases for the conditional action to work properly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5293965d-76a5-4824-9f12-7e3094ea6fb0/a0f13b48-d53a-4086-90e0-f3710764b01f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MjkzOTY1ZC03NmE1LTQ4MjQtOWYxMi03ZTMwOTRlYTZmYjAvYTBmMTNiNDgtZDUzYS00MDg2LTkwZTAtZjM3MTA3NjRiMDFmIiwiaWF0IjoxNzI3NDY5ODIxLCJleHAiOjMzMjk4MDI5ODIxfQ.Smq9BsKxVSeiCoH48wtjtP_7JrRdS6cQ-j9Si7iF7-4 " alt="image.png" width="1059" height="550" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/52b1c4fb-58fc-4642-ae41-e4393f3ef9a6/558c1197-3e75-4077-a6e6-3e4b70200d48?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MmIxYzRmYi01OGZjLTQ2NDItYWU0MS1lNDM5M2YzZWY5YTYvNTU4YzExOTctM2U3NS00MDc3LWE2ZTYtM2U0YjcwMjAwZDQ4IiwiaWF0IjoxNzI3NDY5ODIxLCJleHAiOjMzMjk4MDI5ODIxfQ.dkC3o2cO2wqrVKocI5DhSPdopl2zo4sNA5ugvrtfTjI " alt="image.png" width="611" height="568" />

**Comment by mscott-redshift-tech** [comment]
Interesting.  It works with just the false option filled.
This seems to be new as previously no one on our team had noticed this behavior.  Thank you
