### ISSUE TITLE
Custom widgets and action code deemed valid, but all package imports and associated code redlined in (custom action) editor.

### ISSUE THREAD

**Issue by rsktaker** [FlutterFlow/flutterflow-issues#3922]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Code is redlined, when actually valid and deemed valid by the code checker. Specifically, it is the package imports and associated code. This makes it unclear what are my actual errors. 

Sometimes these redlines show and sometimes they do not. Here is an example:

<img width="1440" alt="Screenshot 2024-09-27 at 1 39 14 PM" src="https://github.com/user-attachments/assets/775b8554-d3eb-424c-9deb-97d6223d17df">

### Expected Behavior

I expect the code checker and the error messages in the editor to align.

### Steps to Reproduce

1. write custom action (with image picker dependency?)
2. validate with code checker
3. observe redlining

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gks/l8YxgrsMA7ar2a+9WmSkWQ3I4aL00st5Hd0gdCOPrBqQMP87sUFVBZ8vmaVNcA1WjrEcx0/D5itrlNsFeB06dfNVFyqVQSQr0e2iiVaa1CZGaT3EnI5tYG2LE1p2s2iJBNvJ0V1oR7F+QPeuUVgHDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="1440" alt="Screenshot 2024-09-27 at 1 39 14 PM" src="https://github.com/user-attachments/assets/d61a8d9b-e6af-49fc-9c10-14a28e8c9c6b">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

This error often occurs when the project becomes unsynced with the server. However, you should still be able to build and test all changes you've made. Even though certain parts may be redlined, they should still work as expected!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
