### ISSUE TITLE
Debug panel not showing all page states

### ISSUE THREAD

**Issue by squirrel-o** [FlutterFlow/flutterflow-issues#3923]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've added a few page states to a page but when opening the debug panel I don't see those states. They should be there even if empty but they're not 

### Expected Behavior

I expect to see all page states in the debug panel, even if they're null 

### Steps to Reproduce

Go to compSubCrudJob page and open debug panel. Compare to list in UI 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjufq5ot1rs9H+KX6LcJao2QRI0MdXOczitVEew4bCIj4OrMMPff7dRFBXuKzaH5HfWKbsEECpujTvfPAG+4BAAWAY7Z++s1AbxPPbFuiaa6kEruOdnMkHeJUCn6k1p+3mAlTPuxvLyEH2mCQf9i9QT6Cf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-09-28 at 01 17 07](https://github.com/user-attachments/assets/7d9817ed-6464-4036-ab02-cd725eddb0c2)
![Screenshot 2024-09-28 at 01 17 22](https://github.com/user-attachments/assets/1b685d68-560e-4147-b711-1b5286d0994c)

### Environment

```markdown
- FlutterFlow version: v5.0.1
- Platform: Web
- Browser name and version: Chrome Version 128.0.6613.138
- Operating system and version affected:  macOS Sonoma 14.6.1
```

**Comment by squirrel-o** [comment]
ah never mind, I realised it was because the local run wasn't updating due to an error in a custom function. 

It's kinda annoying that the desktop app lets you do a run when there are errors (also not told in the UI) when it's not taking the latest changes into account. If it doesn't use the latest changes it shouldn't let me do a run

**Comment by Alezanello** [comment]
Hello!

I'm glad to hear the debug panel is working as expected now. We are aware of the issue with local running, and our engineering team is actively working on a fix. Thank you for your patience!
