### ISSUE TITLE
Library clear app_state variable

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3924]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When clear a library state variable from the consuming project, it doesnt call the correct FFAppState():

```dart
FFAppState().deleteProjvar();
FFAppState().Projvar = '...';

FFAppState().deleteLibvar(); <----- here
testlib_app_state.FFAppState().Libvar = '';
```

### Expected Behavior

```dart
FFAppState().deleteProjvar();
FFAppState().Projvar = '...';

testlib_app_state.FFAppState().deleteLibvar(); <----- here
testlib_app_state.FFAppState().Libvar = '';
```

### Steps to Reproduce

1. create a lib and a varriable "Libvar" in its appstate, publish the lib
2. create proj, and add the library
3. create a button, add action to clear "Libvar" of lib appstate.
4. download the code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89PvsdG1ZSJdvoxmiMRNmkcTeU30+thcw4bI+PuPZYiPuLBTE9uSOqHemxqfVeYkn4ypdKOht7xKfE4ZQeVQIBSwbV9UxDjVkiRbqqqPpCWeEclAftnJ0zF5rSs3RRABOt1c0Jn7Waue/CQa3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/f4e1eb3b-3ff7-4e3e-b1e9-6c08f28af963)

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Web
- Browser name and version: Chrome 129.0.6668.71
- Operating system and version affected:  Win 11
```

**Comment by paulperez-dev** [comment]
Hi @nev-21,

Could you please provide the bug report code for the other project? That will help us investigate the issue further.

Thank you!

**Comment by nev-21** [comment]
Yes of course,

Project:
ITFfz/Hqx89PvsdG1ZSJdvoxmiMRNmkcTeU30+thcw4bI+PuPZYiPuLBTE9uSOqHdwhEPlf8uFwy+anHiobTOsAqHxWaRr5f+bgIUxDjVkiRbqqqPpCWeEclAftnJ0zF5rSs3RRABOt1c0Jn7Waue/CQa3qCf9qOYwx5e6fDbOY=

Lib:
ITFTz/Hqx89OseFZ+KnQcu0xiiQUI0MfWOdEket+EA0hfamuEIYMf87BflRLYteje3x9e1SjpzkKw+vGj+GeJfApA0uBbt1Mz65XQRXiXj2iV5iTBs/pekQnTJ1NBUCB3ImJoxRSJbBtR3At71OlNvCNG3qCf9qOYwx5e6fDbOY=

**Comment by nev-21** [comment]
hi, @paulperez-dev please were you able to verify this issue? If it is necessary i can make a video of it

**Comment by nev-21** [comment]
Hello @paulperez-dev please is this considered a bug? we cannot clear library app-state variables

**Comment by paulperez-dev** [comment]
Hi @nev-21,

Thank you for providing the bug report codes! I’ll look into the projects and will get back to you soon with more information.

**Comment by hutomosaktikartiko** [comment]
Same here

![Screenshot 2024-10-25 at 21 39 29](https://github.com/user-attachments/assets/ec0b52a7-e989-4c36-aa15-88d5131a0a89)

**Comment by nev-21** [comment]
Hi @paulperez-dev please any news?

**Comment by Alezanello** [comment]
Hello!

I’ve recreated this scenario as follows:

1. Created a library with an **AppState** variable named `Libvar`.
2. Created a consuming project with an **AppState** variable named `Projvar`.

To differentiate between them, you can use `import as` for separation, as shown in the example below.

To clear the value, you can use `FFAppState().Projvar = '';` or `lib.FFAppState().Libvar = '';`.

For example, if you create a button, set its **On Tap** action to **Update App State**, select `Projvar`, and choose **Clear Value with No Rebuild**, then view the code for the button, you’ll see the same result as described above.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7e42c7cc-e394-4b62-ad38-f63e77685461/e7ce27f1-6d4c-436c-94f9-bac020e1ef2b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZTQyYzdjYy1lMzk0LTRiNjItYWQzOC1mNjNlNzc2ODU0NjEvZTdjZTI3ZjEtNmQ0Yy00MzZjLTk0ZjktYmFjMDIwZTFlZjJiIiwiaWF0IjoxNzMwMTQyMjg3LCJleHAiOjMzMzAwNzAyMjg3fQ.ZXO7_Ey0dfvDxfgLJF1KwTa-9MVEeLfJnWTy9j4l90o " alt="image.png" width="587" height="300" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3c9fa261-5f0e-4ec1-be51-f815f54ca428/e9099d63-6d31-41a8-af86-c2141d07d9fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYzlmYTI2MS01ZjBlLTRlYzEtYmU1MS1mODE1ZjU0Y2E0MjgvZTkwOTlkNjMtNmQzMS00MWE4LWFmODYtYzIxNDFkMDdkOWZlIiwiaWF0IjoxNzMwMTQyMjg3LCJleHAiOjMzMzAwNzAyMjg3fQ.QRrYDohH5LASCvKmDiGCXBBpB5anq53v7chX68KHCNM " alt="image.png" width="1122" height="535" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4833e93f-d0b3-40a4-b29f-f1d4b7dc005f/dffa41ce-6465-4671-82b8-aebc69404fce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ODMzZTkzZi1kMGIzLTQwYTQtYjI5Zi1mMWQ0YjdkYzAwNWYvZGZmYTQxY2UtNjQ2NS00NjcxLTgyYjgtYWViYzY5NDA0ZmNlIiwiaWF0IjoxNzMwMTQyMjg3LCJleHAiOjMzMzAwNzAyMjg3fQ.6P6C0dGK6iZ4vz-ZN0h0cHIK9bsy0qi6cmWlbGIiMt4 " alt="image.png" width="1646" height="500" />

**Comment by nev-21** [comment]
Hi @Alezanello thanks for your review.

I think there is a confusion here. I'm not using custom action code. I'm using "Update App State" action to "Clear Value" of Libvar. That where the error is. These are the steps to reproduce (better explained):

1. create a lib, add an appstate variable "Libvar", publish 
2. create proj, and import the library
3. add a button
    3.1. add "Update App State" action 
    3.2. select "Libvar"
    3.3. in "Select Update Type" choose the "Clear Value" option
4. execute test mode the app will crash
5. open the code (or download the code) and you will see a missing code
    (FFAppState().deleteLibvar(); doesn't has "testlib_.._app_state" before it)

![image](https://github.com/user-attachments/assets/c0eea666-390f-40e3-b525-4eb7ed37ecde)

![image](https://github.com/user-attachments/assets/ed361369-b3b5-45cb-a737-b860f86e6545)

**Comment by Alezanello** [comment]
I followed the steps you mentioned and replicated the setup without using custom code to clear the AppState value from the library. I didn’t experience any crashes, and on reviewing the code, I don’t see any `.deleteLibVar()` calls.

Could you confirm whether your AppState variable is a single string or a list of strings? This detail might help identify any differences in behavior.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/27cc8804-dca6-4753-b111-2f8d6ae767a6/e789ad52-8039-4031-be7b-c940a6c98966?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yN2NjODgwNC1kY2E2LTQ3NTMtYjExMS0yZjhkNmFlNzY3YTYvZTc4OWFkNTItODAzOS00MDMxLWJlN2ItYzk0MGE2Yzk4OTY2IiwiaWF0IjoxNzMwMjEyMTMyLCJleHAiOjMzMzAwNzcyMTMyfQ.dm0Z6JdV_hixmwxmRF_Zgk9rqlY46x2ER_JUox5HHb4 " alt="image.png" width="1194" height="444" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cc4811c6-edcb-4be9-b877-85b1c885475a/6fc21b1e-2785-44a7-87d8-bb0ca382ff1d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jYzQ4MTFjNi1lZGNiLTRiZTktYjg3Ny04NWIxYzg4NTQ3NWEvNmZjMjFiMWUtMjc4NS00NGE3LTg3ZDgtYmIwY2EzODJmZjFkIiwiaWF0IjoxNzMwMjEyMTMyLCJleHAiOjMzMzAwNzcyMTMyfQ.pzx3fY41_9td6jXnO_XD7UqpNM35RX09JEe1YtIGrDQ " alt="image.png" width="1422" height="643" />

**Comment by nev-21** [comment]
It is a string variable. (not a list)

I tested on this version and is still happening.
v5.0.8+ released October 25, 2024

![image](https://github.com/user-attachments/assets/fabf4859-7585-448a-b8fc-07a8e68a76f2)

**Comment by nev-21** [comment]
> I didn’t experience any crashes, and on reviewing the code, I don’t see any .deleteLibVar() calls.

I think you have other FF version? why you can't see it?

**Comment by nev-21** [comment]
@Alezanello I already know why it doesn't appear to you.

You must turn on "Secure persisted fields" in the **_Project_**
(For this, you need to create a foo variable in the project).

![image](https://github.com/user-attachments/assets/235e276f-ceb9-4715-93de-257f0308f396)


So, the steps to reproduce are:

That where the error is. These are the steps to reproduce (better explained):

1. create a lib, add an appstate variable "Libvar", publish
2. create proj, and import the library
3. add an appstate variable "ProjVar", and enable "secure persisted fields"
4. add a button
    4.1. add "Update App State" action
    4.2. select "Libvar"
    4.3. in "Select Update Type" choose the "Clear Value" option
5. execute test mode the app will crash
6. open the code (or download it) and you will see missing code
(FFAppState().deleteLibvar(); doesn't has "testlib_.._app_state" before it)

**Comment by Alezanello** [comment]
Hello again!

Yes, I’m now able to reproduce the error—this was the missing piece! I’ll pass this along to the engineering team for further investigation.

Thank you for your patience!
