### ISSUE TITLE
Flutter dependencies are outdated

### ISSUE THREAD

**Issue by Everyond** [FlutterFlow/flutterflow-issues#3928]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The dependencies are outdated, when downloading the code and wanting to compile it to be able to publish it on my servers it is not possible because the dependencies that Flutterflow exports are not updated to the latest available dependencies and it does not allow the Flutter web build to be done.

<img width="575" alt="Captura de pantalla 2024-09-29 155911" src="https://github.com/user-attachments/assets/8bce7c60-ae7e-40d5-ab53-2c757cf89212">

### Expected Behavior

Flutterflow must update its dependencies to the latest version.

### Steps to Reproduce

I have to deliver a project today and I can't compile it because of this outdated error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

i dont know

### Visual documentation

<img width="575" alt="Captura de pantalla 2024-09-29 155911" src="https://github.com/user-attachments/assets/e70174e5-23ed-4077-a192-ff2bbbb4dc6e">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Everyond** [comment]
<img width="651" alt="Captura de pantalla 2024-09-29 160732" src="https://github.com/user-attachments/assets/199f7c2c-2af6-44c2-9f0b-44b51350df56">
<img width="596" alt="Captura de pantalla 2024-09-29 160714" src="https://github.com/user-attachments/assets/b0566262-22ca-41ad-936a-92eed79a4dc0">

**Comment by Alezanello** [comment]
Hello!

Just a friendly reminder that FlutterFlow currently uses Flutter version 3.22.2. To avoid dependency errors, please make sure your server is set to compile with this version. Compiling with a newer version of Flutter may result in issues.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
