### ISSUE TITLE
Algolia results not visible on mobile app

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#3929]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi!

I've been using Algolia in my app for over a year without any issues. However, after the latest deployment, I noticed that the search results aren't displaying on mobile devices.

At first, I thought there was an issue with the integration. So, I reinstalled the Firebase extension, generated a new API key, and went through the entire integration process again following the documentation.

It works fine in run mode on my browser, but the problem persists on my phone after deployment.

After testing on mobile, I checked the logs in Algolia and confirmed that the search is returning the correct response. However, the results still aren't appearing in my app. Instead, I just see a loading animation and a blank page where the list view should be.

### Expected Behavior

It should be the same on mobile after deployment as in the run mode in the browser.

### Steps to Reproduce

1. create a textfield
2. onchange action: Algolia
3. create a listview -> generate children from variable -> value: Algolia search result.
4. run: see the results
5. deploy to mobile: see that the results are not displayed

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8/625NOm99D15SJYMcxniE4NW0cTIAFkuwacy8YGIytBuwMOuPsU1tBTe2kaVNceE2apGcBzN6JkfPfMOw5PRSeR5xzyKhIUTzOe2ileL7WDZOKT0dtHppYIVS118OJkBMnFLJhWnBl1GCYIeiQRT/DBOu/Zwh9f6PHaOI=

### Visual documentation

![algolia response](https://github.com/user-attachments/assets/b8c1f2e1-0f7c-4a59-9bd4-0c4cde9d88a8)
![mobile app](https://github.com/user-attachments/assets/f5a86960-e51e-4a8f-b185-b93d00e01cbc)
![run mode](https://github.com/user-attachments/assets/9032b398-5fec-421c-a437-a7ce02431a1f)
![action](https://github.com/user-attachments/assets/b51813d2-28ec-4334-b082-0b098c916e38)
![listview](https://github.com/user-attachments/assets/a3464cec-0330-473d-9fe2-9d7b7ea81972)

### Environment

```markdown
- FlutterFlow version: 5.0.1+
- Platform: Windows Desktop
- Browser name and version: Firefox 130.0.1
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment]
Hi @tothati90,

Could you please share the phone logs with us? That would help in investigating the issue further.

Thank you!

**Comment by tothati90** [comment]
Hi @paulperez-dev 

I just found out the problem was caused by using enums in the searched documents. See [here](https://github.com/FlutterFlow/flutterflow-issues/issues/3464)
Would be great if that error would be fixed.

**Comment by paulperez-dev** [comment]
Hi @tothati90,

I’ll be closing this issue for now. Please refer to the mentioned ticket for any further updates.

**Comment by asifmasroor** [comment]
this is still an issue for me. both duplicate and original tickets are closed without providing any solution
