### ISSUE TITLE
The custom action create button is not working as expected.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#393]
## Expected behavior (required)

- Should open when I press the Custom Code `[ + Add ]` button. but it's not working.

## Current behavior (required)

- The Custom Code `[ + Add ]` is not working in some cases.

## To Reproduce (required)

1. Press the `Custom Code [ + Add ]` button as in the video.

### Bug Report Code (required, generate from Widget Tree)
N/A

## Context (required)

- I want to add a custom action. But it's not working.

## Screenshots / recordings

https://user-images.githubusercontent.com/5080329/213999366-27f64a52-cbb6-493a-8259-bf83f9267727.mp4

## Your environment

* Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by hariprasadms** [comment]
Thanks for the details @thruthesky. Are you still experiencing this issue? I'm not able to re-produce the issues. 
Meanwhile can you please refresh the page and see how it goes.

**Comment by thruthesky** [comment]
Hi, @hariprasadms 
It's still the same. I updated new version of FF - Jan 24, 2023. You can see it in the video.

https://user-images.githubusercontent.com/5080329/214291287-6086b622-01de-441e-90a8-a417b36cfafe.mp4

**Comment by hariprasadms** [comment]
Hi @thruthesky - Looks like I can re produce this issue. However it does not happen frequently. But in my case it started working after ctrl+refresh. 

Close the browser and clear the browser cache and try again. I hope this time it should work.

https://user-images.githubusercontent.com/17435678/214627804-d9777888-5366-408c-8b51-b66a2c05d8c3.mp4

**Comment by hariprasadms** [comment]
Hi, It should be fixed with FF latest updates. Hence closing the issue.
