### ISSUE TITLE
Lib actions disappear in consuming Project, and "edit button action" doesnt show code

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3930]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- The name of the action disappear, and 
- "edit custom action" button doesnt allow to see the action code .

### Expected Behavior

That action dont dissapear.
The button "edit" should show the code

### Steps to Reproduce

1. create a library with an action, publish it
2. create a project and call the action from a button
3. refresh the page and see how it dissapear
4. cilck "edit custom action", you will see empty screen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89PvsdG1ZSJdvoxmiMRNmkcTeU30+thcw4bI+PtELMpOuLRcktWYuqHT2xiGVqZjkQBp97vjvHXMvkoZBebbLpxwqppUxDjVkiRbqqqPpCWeEclAftnJ0zF5rSs3RRABOt1c0Jn7Waue/CQa3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/558ae813-ff0e-4808-b0fd-7dc7b3b75bf9

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Web
- Browser name and version: Chrome Versión 129.0.6668.71 
- Operating system and version affected: win 11
```

**Comment by rzambroni** [comment]
**Hey nev-21,**

I was able to replicate the issue you mentioned. There does seem to be something unusual happening with the imported actions. I’ll escalate this to the team so they can investigate further.

Thanks for the report!

**Comment by AnushaFF** [comment]
Thanks for reporting the issue! The issue has been identified and the fix will be released in the upcoming releases.

**Comment by nev-21** [comment]
Thank you @AnushaFF
