### ISSUE TITLE
Custom code compilation errors, xx isn't a type

### ISSUE THREAD

**Issue by PrenSJ2** [FlutterFlow/flutterflow-issues#3931]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently getting a couple errors when compiling custom code.

1. "The name 'IngredientStruct' isn't a type, so it can't be used as a type argument. Try correcting the name to an existing type, or defining a type named"

however as you can see below that the Ingredients datatype does exist.

![Screenshot 2024-09-30 at 00 56 49](https://github.com/user-attachments/assets/f81f68d9-5c1f-470b-a173-a9eee93af92a)

![image](https://github.com/user-attachments/assets/4932a7c0-676f-4b0e-8f44-69eb4951c619)

2. "The name 'CocktailsRecord' isn't a type, so it can't be used as a type argument. Try correcting the name to an existing type, or defining a type named "

as you can see below the Cocktails Record does exist

![image](https://github.com/user-attachments/assets/d7c24e00-f498-474f-a92c-be6ee70de180)
![image](https://github.com/user-attachments/assets/47b342f1-0b48-436f-bb1e-4cd530ed85f8)

### Expected Behavior

Compilation to work for these specific items, as they do exist. 

### Steps to Reproduce

1. Compile project
2. errors

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4szcmB34x2ruJE0JCBKMB7/GUWC2J6bbs8scsZbw4bB4zqPLJ/Z8zSRBNoZMOrdGlhHEyJpEgFpt7HvuL9DPYrPUyCfL5P+cxQEgmVRXq8RZSTBbWZdHElQJ1Tf3ae4J2rpSZBKtZeWGAH1F2QBeeAZA7dGZu/Zwh9f6PHaOI=

### Visual documentation

above

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released September 26, 2024
- Platform: Web and Mac
- Browser name and version: Chrome
- Operating system and version affected: Mac

Flutter version is 3.22.2
```

**Comment by paulperez-dev** [comment]
Hi @PrenSJ2,

Thank you for bringing this to our attention! We’re currently tracking this issue internally, and I’ll keep you updated as soon as we have any news.

**Comment by PrenSJ2** [comment]
Hi, as of yesterday at about 9pm GMT the code recompiled when I performed a large refactor.

Thanks

**Comment by paulperez-dev** [comment]
Hi @PrenSJ2,

Thanks for the update. I'm closing this issue.
