### ISSUE TITLE
is_checked is a forbidden constant that shouldn't be able to be part of a datatype

### ISSUE THREAD

**Issue by nabkawe** [FlutterFlow/flutterflow-issues#3932]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tried diagnosing an issue for a friend who had is_checked as a boolean.

### Expected Behavior

the error can't find the getter for is_checked kept showing up instead of working like normal

### Steps to Reproduce

name a data type boolean as is_checked.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

12414

### Visual documentation

![image](https://github.com/user-attachments/assets/0cbc73a8-6316-42c0-8fca-c3131d0b0860)

### Environment

```markdown
- FlutterFlow version: 5
- Platform: android
- Browser name and version: android
- Operating system and version affected:  21
```

### Additional Information

block it from being added to the datatype.

**Comment by Alezanello** [comment]
Hello!

Based on the information you provided, I was able to create the 'is_checked' variable inside a DataType without any issues. Is there any additional detail or step I might be missing to help me replicate the issue you're experiencing?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/621de3ae-a588-4609-aac5-2b3ac6ebcebc/178ea506-676a-4bb8-be9f-59b1d0791839?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MjFkZTNhZS1hNTg4LTQ2MDktYWFjNS0yYjNhYzZlYmNlYmMvMTc4ZWE1MDYtNjc2YS00YmI4LWJlOWYtNTliMWQwNzkxODM5IiwiaWF0IjoxNzI3NzAzNTcwLCJleHAiOjMzMjk4MjYzNTcwfQ.fHRSmUXO_CcOhFllyDIqjpoOaW-hU8zeeAI2OPcu9GA " alt="image.png" width="1871" height="334" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
