### ISSUE TITLE
Cloud Functions Firebase Sync and Code Analyzer issues

### ISSUE THREAD

**Issue by geret1** [FlutterFlow/flutterflow-issues#3937]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Code Analyzer enters into an infinite loop without analyzing the code or providing any kind of errors. Aside, I've also experienced some sync issues between deployments in firebase.

### Expected Behavior

Code analyzer working effectively and 1:1 sync within firebase.

### Steps to Reproduce

1. Create a cloud function 2. Validate that code analyzer works. 3. Deply multiple times on Firebase and check if code is mirrored between Firebase and FF.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Ll8ZNIvulA187pbfowtDg7Q1g/TL07ttYbZxUjIuPtBJh/fuDsUxFpQtOldFNhHGL9jkEJpPDFuPzqV/UFE0yrRohJzYd6VxfvVXq8Sq64ELuafHEkJJpWGhGZ1qaJ3xJ/AO5qLkYM12CQIOjIEzfcGZ+/Zwh9f6PHaOI=

### Visual documentation

<img width="1287" alt="Screenshot 2024-09-30 at 09 50 03" src="https://github.com/user-attachments/assets/cca61fa4-64ae-41cb-9918-460079c84036">

### Environment

```markdown
FlutterFlow v5.0.0+ released September 27, 2024
Flutter version is 3.22.2
Web (Chrome) and Desktop (OSX)
```

**Comment by geret1** [comment]
Also, it is not possible to re-deploy once the previous deployment has completed successfully. Make sense in a normal use-case scenario but in this weird behaviour it is also needed.

**Comment by rzambroni** [comment]
Hello @geret1,

Thank you for bringing this issue to our attention!

I attempted to replicate the problem you mentioned, but everything seems to be functioning correctly on my end. The code analyzer is working as expected and is detecting syntax issues without any problems.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/836340e3-eb88-4d2d-ba13-62f48325849b/7d8f6148-fd7b-42cc-8445-c891741008fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MzYzNDBlMy1lYjg4LTRkMmQtYmExMy02MmY0ODMyNTg0OWIvN2Q4ZjYxNDgtZmQ3Yi00MmNjLTg0NDUtYzg5MTc0MTAwOGZlIiwiaWF0IjoxNzI3ODA0MjMyLCJleHAiOjMzMjk4MzY0MjMyfQ.qsEeQ2MjNHJoFwsDt6_Za0UrcEXFbG-iFp70PTlJwfU " alt="image.png" width="604" height="329" />

Could you please confirm if you're still experiencing the issue, or if it may have been a temporary outage? <br><br>Regarding the sync issue, could you provide a bit more context? Are you noticing that the cloud function consistently fails to update on the Firebase side after every deployment, or is it happening more sporadically?

Thanks so much!

**Comment by geret1** [comment]
It's still happening with new and existing cloud functions. Is there any way to debug the existing behaviour?

On the other hand, cloud function updates fails in a consistent way. I usually need two deployment versions to make changes effectively. The way I tested it is:

1. Save changes on FF.
2. Deploy changes.
3. Go to GCP console > Cloud Functions  and check new revision is created.
4. Wait until new deployment finished
5. Check source code.

**Comment by geret1** [comment]
@rzambroni do you have any update to triage what's happening on my project about code analyzer with cloud functions?

**Comment by rzambroni** [comment]
Hi @geret1,

Thank you for following up, and I apologize for the delay in getting back to you. Unfortunately, we’re still unable to replicate the issue on our end, and it hasn't occurred in our tests. Given the situation, I’d recommend reaching out to FlutterFlow support so they can take a deeper look at your project and help identify the cause of the problem.

Would you mind following up with them via email at [support@flutterflow.io](mailto:support@flutterflow.io) or through the chat feature within the app? They’ll be in a better position to assist you further.

I’m sorry I couldn’t resolve this for you, and I appreciate your understanding.
