### ISSUE TITLE
App state variable not being saved from API response

### ISSUE THREAD

**Issue by tsizzybots** [FlutterFlow/flutterflow-issues#3938]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The windowNotes2 app state variable within my app is not being saved after an API response call has been received for window two. This is working for window 1 based on the exact same setup.

### Expected Behavior

After the API call response has been received, I update all relevant AppState variables. The windowNotes2 variable should be updated from the API response JSON path. $.window2Notes

### Steps to Reproduce

1. Start a new test session on the home screen
2. Select 'Yes' for question 5 on window 1 & click continue to navigate the window 2
3. Select 'Yes' for question 1 on window 2 & click continue to execute the attached action. The app stage variable should be updated at this stage, however, is remaining empty

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMjf34V1xcdA7ZDUY8B7/T8vG1A7a+YascsZa0kdB4joPLJ/ZuP8SFpoTeG7THlhHE3/pHoG+trVjoSXV8Y4aBebRbY7yc9uSz3/VXq8SrWbDc2KfX9SAe1mCB2ly5ivmgkkPfVuR3gd22CQet7IdA/cN5+/Zwh9f6PHaOI=

### Visual documentation

![SCR-20240930-kedk-2](https://github.com/user-attachments/assets/cd6030fd-b21f-413c-a118-89e6ef4e0774)

### Environment

```markdown
- FlutterFlow version: I'm not sure where to find this
- Platform: Web
- Browser name and version: Chrome Version 129.0.6668.60
- Operating system and version affected: MacOS Sonoma 14.2
```

### Additional Information

Currently, this is the only issue holding me back from progressing the app build, and I'm on quite a tight schedule, so I really need to get this fixed ASAP.

**Comment by paulperez-dev** [comment]
Hi @tsizzybots,

I’m really sorry you’re facing this issue. Could you please try changing the JSON Path to a Predefined Path and select "Notes" from the dropdown? Let me know if this helps or if you need any further assistance!

**Comment by tsizzybots** [comment]
Hi @paulperez-dev,

I've given this a go and the app state variable is still not updating when using a predefined path.

<img width="1206" alt="SCR-20241001-hmwc" src="https://github.com/user-attachments/assets/c2c8a248-cd85-4f83-bde3-7b6f9984f65a">

Note: When testing this, if I change the app entry page to this page (page 2), the notes are saved correctly. This issue only seems to take place when the user has come from page 1, makes a selection (the first dropdown box) on page 2, and then clicks the continue button. Additionally, all of the other app state variables which I am updating within this action are being updated correctly. It's just this one which seems to have an issue.

**Comment by tsizzybots** [comment]
Hi @paulperez-dev, is there any update on this? I'd really appreciate a prompt response/solution to this, as the project is time-sensitive, and this is the only thing not working as needed.

**Comment by tsizzybots** [comment]
Please could I get an update on this?

**Comment by tsizzybots** [comment]
Hi, I'm not sure why this issue is labeled as 'waiting for user response' as I've responded 3 times above since hearing back.

**Comment by paulperez-dev** [comment]
Hi @tsizzybots,

Apologies for the delayed response! I’ll review your comments and get back to you with my findings as soon as possible.

Thank you for your patience!

**Comment by paulperez-dev** [comment]
Hi @tsizzybots,

If changing the entry page is updating the state, it might indicate that the API isn't being called at the correct time or isn't being triggered as needed. Could you please check if that’s the case?

**Comment by tsizzybots** [comment]
Hi @paulperez-dev 

I've checked this in the action builder, and can confirm the API is being called prior to the database update:

<img width="947" alt="SCR-20241028-kvnd" src="https://github.com/user-attachments/assets/29252570-8cb2-40b8-b179-2b56e9fe7356">

I've also confirmed the notes are being returned by the API call:

<img width="1263" alt="SCR-20241028-kwnl" src="https://github.com/user-attachments/assets/21a3a757-5fce-4850-8a21-74c370ce2679">

**Comment by rzambroni** [comment]
Hi @tsizzybots,

Apologies for the delay in getting back to you. Paul was off for a couple of weeks, and the ticket slipped through the cracks.

I currently don’t have the rights to run your project, and when I tested it in a separate project, attempting to do something similar, it worked fine on my end. Would it be possible for you to create a quick blank project where this issue is replicable? This would help us immensely in troubleshooting the problem more effectively.

Thank you for your help!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by tsizzybots** [comment]
Hi, I've duplicated the project to gihub, however, it's sensitive (under an NDA) so can I invite you to the repo? Please advise how I can do this so we can progress with resolution to this.

**Comment by rzambroni** [comment]
Hello, To help us investigate this further, it would be great if you could recreate the issue in a blank project and share it with us. This will allow us to focus specifically on the bug and provide a quicker validation & resolution.

**Comment by tsizzybots** [comment]
@rzambroni I've created a blank project, and am unable to recreate the issue of the appstate not updating (for one of the two instances it's not updating). In the existing app I've built, the appstate does not update for this notes value after the API call, however, in the blank project, it does update as required. 

Note: It does update correctly if I set the start page to this window (however, we need the app to start on a different window).

<img width="1497" alt="SCR-20241206-olrl-2" src="https://github.com/user-attachments/assets/6fa63e62-93c8-46de-b9d9-c9d134567920">

There is a second part of the app where the appstate does not update also (detailed above in my original issue), which I have not recreated yet (both issues seem to be the same core issue).

Please advise why the behaviour could be different in the blank project vs the existing project I've built (both include the same actions when the button is clicked).
