### ISSUE TITLE
Unable to save custom action to schedule.

### ISSUE THREAD

**Issue by duuetdev** [FlutterFlow/flutterflow-issues#3939]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After writing down my custom action for scheduling notifications regularly, I'm not able to save it. I've attached a video on how it's behaving below.

https://github.com/user-attachments/assets/35efabef-c312-476a-95bf-6c67fb9d0244

### Expected Behavior

Upon saving the custom action, it should save or it should tell me that there's some issue in the complier, neither are happening.

### Steps to Reproduce

1. Go to Custom actions and add this as a custom action.

`import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

Future<void> scheduleDailyNotification({
  required String title,
  required String body,
  required int hour,
  required int minute,
}) async {
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  // Define Android-specific details
  const AndroidNotificationDetails androidDetails = AndroidNotificationDetails(
    'daily_notification_channel_id', // channel ID
    'Daily Notifications', // channel name
    channelDescription: 'Channel for daily notifications',
    importance: Importance.max,
    priority: Priority.high,
    showWhen: false,
  );

  // Define iOS-specific details
  const DarwinNotificationDetails iosDetails = DarwinNotificationDetails();

  // Combine platform-specific details
  const NotificationDetails platformDetails = NotificationDetails(
    android: androidDetails,
    iOS: iosDetails,
  );

  // Schedule the notification
  await flutterLocalNotificationsPlugin.zonedSchedule(
    0, // Notification ID
    title, // Notification Title
    body, // Notification Body
    _nextInstanceOfTime(hour, minute), // Scheduled Time
    platformDetails,
    matchDateTimeComponents: DateTimeComponents.time, // Daily repetition
    uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
  );
}

// Helper function to get the next instance of the specified time
tz.TZDateTime _nextInstanceOfTime(int hour, int minute) {
  final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
  tz.TZDateTime scheduledDate =
      tz.TZDateTime(tz.local, now.year, now.month, now.day, hour, minute);
  if (scheduledDate.isBefore(now)) {
    scheduledDate = scheduledDate.add(const Duration(days: 1));
  }
  return scheduledDate;
}`

2. Try to save it with the required arguments & dependencies.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/q35NItbxb+bnQKMFGiQMwGkQ5a7sviu5+FBQaI+PyO7QfePf4QFhBWOqHTQhMDFCZ/X0y/976hofmU/Y4GAeBY64+/5FxUxDvfECXVc2bBbmeYXMkGflMGEi15ruvpgpCIbFiLlZh2WeIBui+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/4535a2cd-5036-4411-bae4-6b926b0cd235

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ (released September 27, 2024)
- Platform: MacOS & Web
- Browser name and version: Arc Browser-Version 1.61.2 (54148)
- Operating system and version affected: MacOS Sequoia 15.0
```

**Comment by Alezanello** [comment]
Hello!

Could you try making this change:

From:

```dart
Future scheduleDailyNotification({
  required String title,
  required String body,
  required int hour,
  required int minute,
})
```

To:

```dart
Future scheduleDailyNotification(
  String title,
  String body,
  int hour,
  int minute,
)
```

This should help resolve the issue you're experiencing. Let me know if you need further assistance!

**Comment by duuetdev** [comment]
Hey actually, I tried it and I tried making them nullable as well, but I'm still getting the same issue.

**Comment by duuetdev** [comment]
I was able to do it by starting with the boiler plate code first.
