### ISSUE TITLE
JSON component parameter must have "required" modifier or an explicit non-'null' default

### ISSUE THREAD

**Issue by Mejoraminegocio** [FlutterFlow/flutterflow-issues#394]
## Expected behavior (required)

Code dosent compile. It is easily solved downloading the code and including the required modifier in the component parameter. But I cant see a way to solve this within FF.

## Current behavior (required)

Error:
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/components/choose_bank_widget.dart:19:10: Error: The parameter 'banksJSON' can't have a value of 'null' because of its type 'List<dynamic>', but the implicit default value is 'null'.
 - 'List' is from 'dart:core'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
    this.banksJSON,

## To Reproduce (required)

1. Create a component
2. Add a JSON List parameter
3. Use that component as a Botton Sheet in a page
4. Compile / Run or web deploy the code

### Bug Report Code (required, generate from Widget Tree)
ITEeksrlx5B1pbxG1pPtKvlorwMwGkQ5a7sviu5+FBQaI+PzBJkcYMzSVFNtcuqHfW5AGVGbrzkGpMrPvt7xCe46C0mcba5IyJBTH1yjEA8=

## Context (required)
I cant deploy from FF (I can download the code, add the required modifier and work with it outside FF)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: Chrome Versión 109.0.5414.75 (Build oficial) (64 bits)
* Operating system and version (desktop or mobile):

**Comment by Mejoraminegocio** [comment]
class ChooseBankWidget extends StatefulWidget {
  const ChooseBankWidget({
    Key? key,
    this.banksJSON,   // ---------------------------------> this needs to be:      required this.banksJSON,
  }) : super(key: key);

  final List<dynamic> banksJSON;  // ---------------------------------> or this:      final List<dynamic>? banksJSON;

  @override
  _ChooseBankWidgetState createState() => _ChooseBankWidgetState();
}

**Comment by yoheisoito** [comment]
Hi @Mejoraminegocio,

Thanks for raising this issue.
I've followed what you did on a dummy project --- it runs okay on test mode as well as run mode.

Please check the video, and if possible, please explain a bit further on how you're setting your JSON List (do they have default values? Are you feeding them directly from local states / shared preferences, or using some custom code to generate your JSON from custom actions?)

https://user-images.githubusercontent.com/115172813/215790062-082be0fd-4604-437e-aed3-ba86967c53c1.mov

**Comment by Mejoraminegocio** [comment]
Y created a public project to show it:
https://app.flutterflow.io/project/pass-j-s-o-nparam-6zq266

error
Error: Command failed: flutter build web  --web-renderer html --no-pub --no-version-check
Target dart2js failed: Exception:
lib/components/newcomponentt_widget.dart:10:10:
Error: The parameter 'jsonParam' can't have a value of 'null' because of its type 'List<dynamic>', but the implicit default value is 'null'.
 - 'List' is from 'dart:core'.
    this.jsonParam,
         ^^^^^^^^^
Error: Compilation failed.

Exception: Failed to compile application for the Web.

**Comment by yoheisoito** [comment]
@Mejoraminegocio,

Thank you for clarifying this.
As you say, when trying to pass a List<dynamic> JSON as a component, it gives you the error that you had mentioned.
We will try to fix this -- in the meantime, please consider passing the json through temporary local state variables to render your bottom sheet. Thank you.

**Comment by Mejoraminegocio** [comment]
@yoheisoito Yeah, with the local state workaround works perfectly, much more convenient than downloading and modifiying the code. Thanks!!

**Comment by Franco98404** [comment]
@yoheisoito I think this issue should be open because is not solved, because is causing problem for the users
