### ISSUE TITLE
Data Types & Enums created in a library are not displayed in the project into which the library is imported

### ISSUE THREAD

**Issue by TheFriendsDevs** [FlutterFlow/flutterflow-issues#3941]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created the library. This library contains some DataTypes and Widgets.
One widget has dataType as a parameter. However, I can't pass this parameter because that dataType doesn't appear in my main project. Only in the lib project

### Expected Behavior

My main project has to get all dataTypes from the lib to use this 

### Steps to Reproduce

1. Create a new project as a Library
2. Create a datatype in this project
3. Create a widget with this datatype as a parameter
4. Publish the Lib
5. Import this lib to any other project
6. Try to use this widget
7. Try to pass the datatype
8. Get the error (You can't do that)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

library

### Visual documentation

![Снимок экрана 2024-09-30 в 19 39 44](https://github.com/user-attachments/assets/d19c9cd4-1aed-4d90-8838-fe7e34ffe315)
![Снимок экрана 2024-09-30 в 19 42 16](https://github.com/user-attachments/assets/cbcb1dcf-c02a-4464-bfc0-aa88c088ffe9)

### Environment

```markdown
- FlutterFlow version: v5.0.0+ released September 27, 2024
- Platform: Web
- Browser name and version: Chrome - last
- Operating system and version affected: MacOS Sonoma 14.5
```

**Comment by rzambroni** [comment]
Hi @TheFriendsDevs,

Thank you for bringing this to our attention. I was able to replicate the issue you're describing, and it appears to be a limitation within the current library functionality. I will escalate this to the engineering team for further investigation.

We'll keep you updated as soon as we have more information.

**Comment by AnushaFF** [comment]
Thanks for reporting the issue! We've identified and fixed the issue and you should see it live in the product in 1-2 weeks!

**Comment by acertaloterias** [comment]
This issue has happened again in FF v6.0.5.
