### ISSUE TITLE
Lib component with "widget builder" param, make consuming project crash at compile time.

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3943]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- the project doesnt compile (cannot enter the test mode) even when everything is without errors (all checks are green)
- the app is broken internally.

### Expected Behavior

- that the project works and can be tested on test mode.

### Steps to Reproduce

1. create a lib
2. create a component "test" with 1 param: the new "widget builder" param
3. publish the lib
4. create a project and consume the lib
5. use the "test" lib component and pass another component as argument
6. run "test mode"
7. error message appear

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTyc7c+YhPm7RB+Kn2ae1VuCoWI0McWOdEl+tuZwgbIoznBuwlPeP7TBZtOMCoaVNcPlmgjj0GwvD9vt7lIPcoYE+qY6JH1Lp1EDvOe2i5R7bUCai8fXwlRN1jfR3AyruFnh5vBMhoWF1m2FOmNtyiQT7DBOu/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/946d6211-a890-442f-9974-03640bbae29d)

![image](https://github.com/user-attachments/assets/d81768a2-8bf1-48d3-bbfb-fbf40e31620c)

![image](https://github.com/user-attachments/assets/19440f09-4507-47b4-94e1-768f3a750aeb)

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Web
- Browser name and version: Chrome 129.0.6668.71 
- Operating system and version affected: Win 11
```

### Additional Information

Project Bug Report Code:
ITFTyc7c+YhPm7RB+Kn2ae1VuCoWI0McWOdEl+tuZwgbIoznBuwlPeP7TBZtOMCoaVNcPlmgjj0GwvD9vt7lIPcoYE+qY6JH1Lp1EDvOe2i5R7bUCai8fXwlRN1jfR3AyruFnh5vBMhoWF1m2FOmNtyiQT7DBOu/Zwh9f6PHaOI=

Library Bug Report Code:
ITESyc7c5odgotdA+rr9YflAhQMkQzM6bZI7ku1EdwEhNYyqBJlyd8jBUEpLYtfmTVV+f1mGnXwG+d3Ii+HhUvUnCy6bG6Z+zpRXQRXiXj2iV5iTBs/pekQnTJ1NBUCB3ImJoxRSJbBtR3At71OlNvCNG3qCf9qOYwx5e6fDbOY=

**Comment by nev-21** [comment]
Please fix this issue, 

The DRY principle enforced in version 5.0 is lost, when "widgets builder" params can't be used in a library.

**Comment by rzambroni** [comment]
Hello @nev-21,

Thank you for the report! I was able to confirm the issue you're experiencing and will escalate it to the team for further investigation.

Apologies for the inconvenience, and we'll make sure to keep you updated on any progress here.

Best regards,

**Comment by leighajarett** [comment]
We've fixed this issue, it should be live in the product in the next release. Thank you for flagging!

**Comment by nev-21** [comment]
Thank you for the quick response!

**Comment by nev-21** [comment]
Hi @leighajarett this should be working in the 4-oct release? 

I just checked and it doesn't work yet.

**Comment by leighajarett** [comment]
No it should be in tomorrow's release, sorry for the confusion!

**Comment by nev-21** [comment]
Great, thank you
