### ISSUE TITLE
Deleting team button is not working.

### ISSUE THREAD

**Issue by rabarijaona** [FlutterFlow/flutterflow-issues#3944]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the organization menu, When I confirm the deletion of my team with "delete" in the popin, my team is not deleted.

### Expected Behavior

In the organization menu, When I confirm the deletion of my team with "delete" in the popin, my team should be deleted.

### Steps to Reproduce

1. Connect to your FF account
2. Go to organization menu
3. Create a team
4. Click on the icon to delete the team
5. Confirm with the word delete
6. Click on yes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released September 27, 2024
- Platform: any
- Browser name and version: any
- Operating system and version affected: any
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue on my end. If you're still encountering this error, please reach out to our support team via the in-app chat or by emailing support@flutterflow.io, and they'll be happy to assist you further.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f5c6bf0a-7cfa-4729-b481-682ac43df39c/ce7cec4f-668b-43e1-905d-eb57c90cf1ff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNWM2YmYwYS03Y2ZhLTQ3MjktYjQ4MS02ODJhYzQzZGYzOWMvY2U3Y2VjNGYtNjY4Yi00M2UxLTkwNWQtZWI1N2M5MGNmMWZmIiwiaWF0IjoxNzI3ODE2NjgwLCJleHAiOjMzMjk4Mzc2NjgwfQ.EVlrMD9oLx0QfgmjOXpsT0oILAN1OiFuM0vo6Ov5dew " alt="teamtesting.gif" width="1673" height="864" />

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
