### ISSUE TITLE
Can't compile custom actions when using lib component

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3946]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot click the compile button for "custom actions" when using a library component.

This error appear on chrome debug console:
"Uncaught Error: Null check operator used on a null value"

### Expected Behavior

that action compiles and checks code normally 

### Steps to Reproduce

1. create a lib project
2. create a component X in the library
3. publish the library
4. create a project and import the library
5. use lib X component in any place (like home page)
6. create a custom action and save it
7. try to click the compile button, nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTh8jqz4hPm7RB+KX6b8ZFhmMUGUMcWOdEl+tuZwgbIoznBqQAesn7QEhBXeGhaVNfe06LhlkG09byi+DPL+04YBWeRbZqybt6UAvke2i5R7bUCai8fXwlRN1jfR3AyruFnh5vBMhoWF1m2FOmNtyiQT7DBOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/4a8652f8-996f-4307-8152-743808b678ce

![image](https://github.com/user-attachments/assets/ab1151fd-e9f0-4622-842a-1777e21ea053)

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: web
- Browser name and version: chrome 129.0.6668.71 
- Operating system and version affected: win 11
```

### Additional Information

project bug report code:
ITFTh8jqz4hPm7RB+KX6b8ZFhmMUGUMcWOdEl+tuZwgbIoznBqQAesn7QEhBXeGhaVNfe06LhlkG09byi+DPL+04YBWeRbZqybt6UAvke2i5R7bUCai8fXwlRN1jfR3AyruFnh5vBMhoWF1m2FOmNtyiQT7DBOu/Zwh9f6PHaOI=

library bug report code:
ITESh8jqzIdgofVd1ZPub+5QhR4jNlx7bZNEjtZ+FA8cB5OrOpwpWv/BYnRvcM+rdG9LeVSZu3Ix+PTmkfDAU/Y5MgyHb65I/pFuajnKWn+WMIiyOpewP0ZQOJ9RGEyfy5+32iR4ALZ2dVlpig/GSw==

**Comment by nev-21** [comment]
Please help!

I made some libraries, there are a lot of errors, we can't advance with these critical issues.

**Comment by rzambroni** [comment]
Hi @nev-21,

Thank you for bringing this to our attention, and we sincerely apologize for the inconvenience. I've confirmed the behavior you're experiencing and have escalated the issue to our engineering team for further investigation.

We’ll keep you updated here as soon as we have more information. Thanks again for your patience and understanding!

**Comment by nev-21** [comment]
ok thanks, please could you check this issue too #3943 (maybe related)

**Comment by leighajarett** [comment]
We've fixed this issue and you should see it live in the product in 1-2 weeks!
