### ISSUE TITLE
Question mark showing instead of custom icons

### ISSUE THREAD

**Issue by maximvlasyuk003** [FlutterFlow/flutterflow-issues#3947]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After opening a page we will see question mark

### Expected Behavior

After opening a page we will see arrows icons.

### Steps to Reproduce

1. Add a custom icon
2. Run app
3. See question mark

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXjs/l5ZV2odxE1s/MK+5alj0wGUwbUOc7j9VEGAsjCeLpO5kfPc/ebltvYuqHeVZXelSJuEYCpMrtjeHyGMcCYAqVR75D1c0IUxDgTlO6aJuVErrtSnJBM/FWJhWh56WOkSVQGPFiS3AS23GmIeqQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![1](https://github.com/user-attachments/assets/1118721b-4caa-4af5-8416-b7dbc03625fc)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @maximlasyuk003,

Thank you for your report! Could you please take a look at [this](https://github.com/FlutterFlow/flutterflow-issues/issues/3661#issuecomment-2327168709) previous issue? It seems like you're encountering something similar, and I believe it might be helpful for you as well.

Let me know if that resolves the problem.

Thanks.

**Comment by maximvlasyuk003** [comment]
Hi, @rzambroni . We fixed that by adding icomoon.ttf to the custom fonts. I don't know exactly what broke it.
