### ISSUE TITLE
iPad Keyboard covering

### ISSUE THREAD

**Issue by bjones7043** [FlutterFlow/flutterflow-issues#3948]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Keyboard covers everything when clicking any drop-down

### Expected Behavior

No keyboard unless searching

### Steps to Reproduce

Click any drop-down 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiM/qw5NgoeVY15CJb8FspyQ7Nm43aq8ZkMpBZzUYF5SuCLMqY8mnPlhuZNejY2NffFqmp14Cp97viOPxDfYnGzuBUa5EyIdqcxbyfESQbp+TF7u8RUEnEfNmIGHF0buNvRRROsdtSHBm11ymO96sZDLaJr7BIno8Sq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/1b8262e4-5008-431c-a54f-42f6dfe8fac8

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: IPad
- Browser name and version:FlutterFlow app
- Operating system and version affected: Ipad
```

### Additional Information

It’s horrible , there’s other bugs too but this is a big one

**Comment by rzambroni** [comment]
Hi @bjones7043,

Thank you for bringing this issue to our attention, and we sincerely apologize for the frustration you're experiencing with the iPad app. We understand how inconvenient this must be, and I will escalate this internally to ensure the team is aware. We'll look into potential updates or improvements that could address this.

Thanks again for your patience and understanding. We truly appreciate your feedback.

**Comment by leighajarett** [comment]
We've fixed this issue and you should see it live in the product in the next 1-2 weeks!
