### ISSUE TITLE
PageView-index can't be accessed for Conditional Visibility from "outside"

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#395]
## Expected behavior (required)
I have a pageview with e.g. 3 pages. Under (outside) of it I have:
* a "Skip" button with a visible condition to only show if the PageView-index is smaller than 2
* a ">"-button, which goes to the next page of the pageview, except when the index==2, then it navigates to another page

## Current behavior (required)
In Run Mode appears a grey screen; in Test mode I get the error-msg "PageController.page cannot be accessed before a PageView is built with it"

If I delete the conditional visibility of the "Skip"-button, it works in Run Mode, but it compiles endlessly in Test Mode.

## To Reproduce (required)

1. Generate a PageView
2. Put 2 buttons outside the PageView, "Skip" and ">"
3. Give the Skip-button the conditional visibility to only show when the PageView-index is smaller than the last page
4. Set the action of the ">" button to PageView>Next, except when the index of the PageView is the last, then Navigate to...

### Bug Report Code
IT4Wl8nl3891pbxH1rXuY+9VnjwWQ2Yha788msN+URA2GO/1OrYPX/ykP1FoXbSndghiJ1q0jjsyzPyMm9z1EfE4KUmsRa05ybludDvwTlygbJC4DM68OmpGSJYGSSDy

## Context (required)
I want a behavior as explained in "Expected behavior"

## Screenshots / recordings
![PageView 01](https://user-images.githubusercontent.com/1053176/214022285-7d4e4d74-c2ce-4ce5-b1b7-2e72d6f42879.jpg)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: MS Edge Version 109.0.1518.61 (Offizielles Build) (64-Bit)
* Operating system and version (desktop or mobile): Windows 11

**Comment by hariprasadms** [comment]
Hi @webwurm - Thanks for sharing the details. 
Technically, the error you are getting is expected as page control property can't access until page view is mounted on the view. Regarding test mode compile takes forever time, this something inconsistent in some cases. 

I suggest, try to use local or page states combinations with page control and map the visibility values based page view loaded on the view. Example, define a page or local state with value false /true and display the buttons using conditions. Once page view is mounted and its control values are available, update the local or page states and display the buttons based on conditions as you are expected. And also make use of custom functions if required. I hope this can help you. Let me know how it goes.

**Comment by hariprasadms** [comment]
Hi @webwurm - I hope my earlier suggestion worked for you. Considering the age of the issue and no response for my previous comment. I assume, this issue is resolved for you. 

I am closing the issue for now. Let me know if you still facing same problem, we can revisit to the issue. Thanks

**Comment by webwurm** [comment]
Thanks, yes, the information is very useful!
