### ISSUE TITLE
Don't work test and run mode

### ISSUE THREAD

**Issue by Azat90210** [FlutterFlow/flutterflow-issues#3950]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

test and run modes do not work. The browser opens and constantly loads. Works only the web publish . There are no errors in project. I checked on my other projects, it is the same situation. What to do?

### Expected Behavior

load the project ft test and run modes

### Steps to Reproduce

1. Click on run or test mode 2. Long loading 3. click web publish, it is work 4. downloaded Apk don't work too

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

GestureDetector(   onTap: () => FocusScope.of(context).unfocus(),   child: Scaffold(     key: scaffoldKey,     backgroundColor: FlutterFlowTheme.of(context).primaryBackground,     body: SafeArea(       top: true,       child: Stack(         children: [           ClipRRect(             borderRadius: BorderRadius.circular(8.0),             child: Image.network(               'https://picsum.photos/seed/112/600',               width: double.infinity,               height: double.infinity,               fit: BoxFit.cover,             ),           ),           Column(             mainAxisSize: MainAxisSize.max,             mainAxisAlignment: MainAxisAlignment.spaceBetween,             children: [               Expanded(                 flex: 10,                 child: Column(                   mainAxisSize: MainAxisSize.max,                   children: [                     Container(                       width: double.infinity,                       decoration: BoxDecoration(                         color:                             FlutterFlowTheme.of(context).secondaryBackground,                       ),                       child: Padding(                         padding: EdgeInsets.all(10.0),                         child: Row(                           mainAxisSize: MainAxisSize.max,                           children: [                             Icon(                               Icons.arrow_back,                               color:                                   FlutterFlowTheme.of(context).secondaryText,                               size: 35.0,                             ),                             Container(                               width: 60.0,                               height: 60.0,                               clipBehavior: Clip.antiAlias,                               decoration: BoxDecoration(                                 shape: BoxShape.circle,                               ),                               child: Image.network(                                 'https://picsum.photos/seed/760/600',                                 fit: BoxFit.cover,                               ),                             ),                             Text(                               'Hello World',                               style: FlutterFlowTheme.of(context)                                   .bodyMedium                                   .override(                                     fontFamily: 'Suisse',                                     fontSize: 20.0,                                     letterSpacing: 0.0,                                     useGoogleFonts: false,                                   ),                             ),                           ].divide(SizedBox(width: 10.0)),                         ),                       ),                     ),                     Expanded(                       flex: 13,                       child: ListView(                         padding: EdgeInsets.zero,                         reverse: true,                         shrinkWrap: true,                         scrollDirection: Axis.vertical,                         children: [                           BarcodeWidget(                             data: valueOrDefault<String>(                               'unitap://uni-tap.ru${GoRouterState.of(context).uri.toString()}',                               'https://uni-tap2-r2u56p.flutterflow.app/[uid]',                             ),                             barcode: Barcode.qrCode(),                             width: 200.0,                             height: 200.0,                             color: FlutterFlowTheme.of(context).primaryText,                             backgroundColor: Colors.transparent,                             errorBuilder: (_context, _error) => SizedBox(                               width: 200.0,                               height: 200.0,                             ),                             drawText: true,                           ),                           Stack(                             children: [                               Align(                                 alignment: AlignmentDirectional(-1.0, 0.0),                                 child: Padding(                                   padding: EdgeInsetsDirectional.fromSTEB(                                       7.0, 2.0, 7.0, 2.0),                                   child: Material(                                     color: Colors.transparent,                                     elevation: 2.0,                                     shape: RoundedRectangleBorder(                                       borderRadius:                                           BorderRadius.circular(10.0),                                     ),                                     child: Container(                                       width:                                           MediaQuery.sizeOf(context).width *                                               0.7,                                       decoration: BoxDecoration(                                         color: FlutterFlowTheme.of(context)                                             .primaryBackground,                                         borderRadius:                                             BorderRadius.circular(10.0),                                       ),                                       child: Padding(                                         padding:                                             EdgeInsetsDirectional.fromSTEB(                                                 10.0, 7.0, 7.0, 7.0),                                         child: Text(                                           'Hello World',                                           maxLines: 10,                                           style: FlutterFlowTheme.of(context)                                               .bodyMedium                                               .override(                                                 fontFamily: 'Suisse',                                                 color: FlutterFlowTheme.of(                                                         context)                                                     .primaryText,                                                 fontSize: 16.0,                                                 letterSpacing: 0.0,                                                 fontWeight: FontWeight.w300,                                                 useGoogleFonts: false,                                               ),                                         ),                                       ),                                     ),                                   ),                                 ),                               ),                               Align(                                 alignment: AlignmentDirectional(1.0, 0.0),                                 child: Padding(                                   padding: EdgeInsetsDirectional.fromSTEB(                                       7.0, 2.0, 7.0, 2.0),                                   child: Material(                                     color: Colors.transparent,                                     elevation: 2.0,                                     shape: RoundedRectangleBorder(                                       borderRadius:                                           BorderRadius.circular(10.0),                                     ),                                     child: Container(                                       width:                                           MediaQuery.sizeOf(context).width *                                               0.7,                                       decoration: BoxDecoration(                                         color: Color(0xFFDCF8C6),                                         borderRadius:                                             BorderRadius.circular(10.0),                                       ),                                       child: Padding(                                         padding:                                             EdgeInsetsDirectional.fromSTEB(                                                 10.0, 7.0, 7.0, 7.0),                                         child: Text(                                           'Hello World',                                           maxLines: 10,                                           style: FlutterFlowTheme.of(context)                                               .bodyMedium                                               .override(                                                 fontFamily: 'Suisse',                                                 color: FlutterFlowTheme.of(                                                         context)                                                     .primaryText,                                                 fontSize: 16.0,                                                 letterSpacing: 0.0,                                                 fontWeight: FontWeight.w300,                                                 useGoogleFonts: false,                                               ),                                         ),                                       ),                                     ),                                   ),                                 ),                               ),                             ],                           ),                         ],                       ),                     ),                   ],                 ),               ),               Expanded(                 flex: 1,                 child: Row(                   mainAxisSize: MainAxisSize.max,                   children: [                     Expanded(                       child: Padding(                         padding: EdgeInsetsDirectional.fromSTEB(                             10.0, 7.0, 7.0, 7.0),                         child: TextFormField(                           controller: _model.messageFieldTextController,                           focusNode: _model.messageFieldFocusNode,                           autofocus: false,                           obscureText: false,                           decoration: InputDecoration(                             labelStyle: FlutterFlowTheme.of(context)                                 .labelMedium                                 .override(                                   fontFamily: 'Suisse',                                   letterSpacing: 0.0,                                   useGoogleFonts: false,                                 ),                             hintText: 'Message',                             hintStyle: FlutterFlowTheme.of(context)                                 .labelMedium                                 .override(                                   fontFamily: 'Suisse',                                   letterSpacing: 0.0,                                   useGoogleFonts: false,                                 ),                             enabledBorder: OutlineInputBorder(                               borderSide: BorderSide(                                 color: Color(0x00000000),                                 width: 0.0,                               ),                               borderRadius: BorderRadius.circular(30.0),                             ),                             focusedBorder: OutlineInputBorder(                               borderSide: BorderSide(                                 color: Color(0x00000000),                                 width: 0.0,                               ),                               borderRadius: BorderRadius.circular(30.0),                             ),                             errorBorder: OutlineInputBorder(                               borderSide: BorderSide(                                 color: Color(0x00000000),                                 width: 0.0,                               ),                               borderRadius: BorderRadius.circular(30.0),                             ),                             focusedErrorBorder: OutlineInputBorder(                               borderSide: BorderSide(                                 color: Color(0x00000000),                                 width: 0.0,                               ),                               borderRadius: BorderRadius.circular(30.0),                             ),                             filled: true,                             fillColor: FlutterFlowTheme.of(context)                                 .primaryBackground,                           ),                           style: FlutterFlowTheme.of(context)                               .bodyMedium                               .override(                                 fontFamily: 'Suisse',                                 letterSpacing: 0.0,                                 useGoogleFonts: false,                               ),                           cursorColor: FlutterFlowTheme.of(context).primary,                           validator: _model                               .messageFieldTextControllerValidator                               .asValidator(context),                         ),                       ),                     ),                     Padding(                       padding:                           EdgeInsetsDirectional.fromSTEB(0.0, 0.0, 10.0, 0.0),                       child: FlutterFlowIconButton(                         borderColor: Colors.transparent,                         borderRadius: 50.0,                         borderWidth: 1.0,                         buttonSize: 50.0,                         fillColor: FlutterFlowTheme.of(context).primary,                         disabledColor: Color(0xFF5C52A7),                         hoverColor: Color(0xFF3F27FF),                         icon: Icon(                           Icons.send_sharp,                           color:                               FlutterFlowTheme.of(context).primaryBackground,                           size: 30.0,                         ),                         onPressed:                             (_model.messageFieldTextController.text == '')                                 ? null                                 : () {                                     print('IconButton pressed ...');                                   },                       ),                     ),                   ],                 ),               ),             ],           ),         ],       ),     ),   ), )

### Visual documentation

![image](https://github.com/user-attachments/assets/ba6425f2-7180-4d6a-a494-d6c8403cf551)

### Environment

```markdown
- FlutterFlow version: 5.0.2.
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hi there!<br><br>To help us thoroughly investigate whether this is a replicable bug, could you please follow the proper steps for submitting a bug report? This will give us all the details we need to assist you more effectively.<br><br>You can find the guidelines here: https://docs.flutterflow.io/misc/submit-bug-report/<br><br>Thanks for your help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
