### ISSUE TITLE
Command line fails to download project with a dev environment connected to firebase

### ISSUE THREAD

**Issue by ready4sea** [FlutterFlow/flutterflow-issues#3951]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Downloading a project fails once a development environment has been set up and that dev environment has been connected to a firebase project.
It seems this could also affect the local run feature.

### Expected Behavior

I expected to be able to download the project code in the usual way that worked until now and that works again once the firebase project has been removed from the dev environment.

### Steps to Reproduce

1. Create a project
2. Connect it to a firebase project (no need to enable auth)
3. Create a dev environment
4. Download the project code using the command line (example: `flutterflow export-code --project test-env-firebase --include-assets`). This works
5. Now connect the dev environment to a second firebase project
6. Attempt to download the project code via the command line again. This fails

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oz/Hqx89godtF0JSJdMJahjwsHEw1U4ZMmtZ9aEoYJYvNG4gIZfTBXE9uOP25dgk3Jk2amj00w9KNm9z1NvJcISysc6lz1bpUZgnyZzinVYyKDKiCfHxEGshgGkye17WFrhMnJbJpSU4N2zqTOOqRbHLsJJzwDW0nHciaA5DXvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="268" alt="image" src="https://github.com/user-attachments/assets/67e52fb2-ec4d-4aed-8a05-6b88c7f8c28f">

### Environment

```markdown
- FlutterFlow version: 5.0.2
- Platform: Web and MacOS Desktop
- Browser name and version: Chrome 129.0.6668.60
- Operating system and version affected: MacOS Sequoia 15.0
```

### Additional Information

Downloading the code locally is the way I work to test my changes. This has greatly hindered my work until I realized it was due to the newly deployed environment feature.

**Comment by ready4sea** [comment]
FYI, it's now even more painful to download the code via the CLI. Even having removed the dev firebase project and the dev environment itself, the CLI takes ages and fails.

**Comment by Alezanello** [comment]
Hello,

I was unable to reproduce the issue you're experiencing. I created a new blank project, set the Firebase project to **Production**, and downloaded the code without any problems. Then I added a **Dev** environment, linked a different Firebase project (not the same as the Production one), and again downloaded the code successfully. It seems the problem isn't related to the Dev environment but may be something else in your project that's preventing the code from downloading.

**Comment by leighajarett** [comment]
Note that right now the CLI is pulling the code from the _current_ environment you've selected - we're working on adding a flag for the environment so you have more control! Perhaps there was a project issue in the environment you selected when you pulled the code from the CLI? @ready4sea 

We're also considering switching the behavior so the CLI only pulls from your production environment. Is that the behavior you would expect @ready4sea ?

**Comment by ready4sea** [comment]
Hi @Alezanello and @leighajarett,

As you may have seen with the debug code I sent, that project was a fully blank project, so there wasn't really anything special : it was brand new, and certainly no errors ! I just retried it now and indeed it does work now on that blank project, so something has changed since yesterday.

However, on my project, I still can't download correctly, and that has been happening since 5.0. It was flawless before. And I can't see any error in my project. So I'm pretty out of options here.

And to answer your last question, @leighajarett, the behavior is certainly not to only pull from production environment, otherwise what's the point of the other environments ? I pull code to develop and test, and I'd say once it becomes reliable, I would hardly ever pull the production code. Only when publishing, actually. The rest would have to be on dev environments.

**Comment by ready4sea** [comment]
I'm having a thought here @leighajarett : even after fully deleting the Dev environment, I still can't download.

Deleting that Dev environment required right clicking and selecting Delete. Behind the scenes, would that select the Dev environment, hence setting the download configuration on that Dev environment, and then remove it ? Would the command line then be trying to download the Dev environment which does not exist anymore ?

**Comment by ready4sea** [comment]
Hi again, additional information : after restarting my computer, I managed to download the project code once. But after making a very slight change in my project, the exact same command won't download anymore.

The fact that I was able to download tells me that there is nothing wrong with the project.
Apparently it looks as though the command breaks something in the local dart environment. Perhaps is the 5.0 version somehow incompatible with the 2-month old pub.dev `flutterflow_cli` package ?

If you need me to beta-test a newer version, feel free to ask.

**Comment by leighajarett** [comment]
Sorry typo on my end  haha - didn't mean to say *only* - mean to say *default* behavior (so if no environment flag has been supplied, CLI pulls from *production* as opposed to whatever the "currently" selected environment in the app is)<br><br>You would still be able to pull code for any environment using the flag in the CLI (coming next week).<br><br>As for the other comments - appreciate the additional information. Let me do some digging and will get back to you

**Comment by ready4sea** [comment]
Phew, ok, that sounds better !
Indeed, as of now, production should be the default environment because it's the only one that exists for sure. Plus, different users working on the same project could elect to view the project in a different environment, so then which one would the command line pull ? It needs to be specified.
However, another option could be to have a "command line default environment" selector set in App Settings > Project Setup > Dev Environments. That would enable pulling the dev environment without having to specify it. Could be nice.

**Comment by wenkaifan0720** [comment]
Hi @ready4sea. Could you provide a bug report code from your own project that is still having this trouble? 

I can see that you had three attempts at downloading the code from this project (test-env-firebase-qa26j4) and they all succeeded on the backend. So I am not sure if it is something on the frontend that is failing. Could you also provide the error log you see? Thanks!

**Comment by ready4sea** [comment]
> Hi @ready4sea. Could you provide a bug report code from your own project that is still having this trouble?
> 
> I can see that you had three attempts at downloading the code from this project (test-env-firebase-qa26j4) and they all succeeded on the backend. So I am not sure if it is something on the frontend that is failing. Could you also provide the error log you see? Thanks!

Hi @wenkaifan0720 , actually there were more attempts than 3, just around the time that I opened this ticket. I retried this afternoon and then it succeeded.

However, that is a blank project for the purpose of documenting this ticket. But I am still encountering issues on my main project. Here is a bug report code for that project : IT4khvHlz5RJot9K7qr9bcFaij47G0B+TL07ttYbZxUjIuPtBJh/PcnBYhBWUsPgSkNhHFeGrGY0wtrriN/fVsIpEAqAfIB6/6t6WhXgd3q8Rc2NBqiKVHd8TMJMCHKh0rWvvApTHMFeSCU97zn3JOTJYA/DCZu/Zwh9f6PHaOI=

On this one, about one in 4 requests succeds, the others just do not respond for a long time until they fail. For example I launched one around 20:37 UTC and it ended unsuccessfully at 20:45 UTC. It looks as though the requests succeed only when I have not asked a download for a long time. But there after if I ask another one, it doesn't work. Maybe worth noting that I generally ask for a download after I have made changes. Is the server still processing something which blocks the download ?

Sadly there is no error output helping me see what is wrong. When I interrupt the command it seems to produce a 254 error code. And when I let it run until it fails, the error code looks like it's 1.

![image](https://github.com/user-attachments/assets/55e73ac0-9d72-4cd7-9a75-9e81bd7711d1)

**Comment by wenkaifan0720** [comment]
I still don't see anything wrong from our backend. And I just tried downloading the code via CLI a couple of times and has been successful. The downloads shouldn't block each other. I tried both your command options and the default options copied from the developer menu. <br><br>Could you try emptying the folder and run the command? And when the command fails, see if there is anything downloaded into the folder?

**Comment by ready4sea** [comment]
Hi @wenkaifan0720 ,

I have tried to download into another (empty) folder. There is absolutely nothing downloaded in the folder, not a single file.

I have even tried uninstalling and reinstalling the flutterflow CLI. And tried revoking my API token and creating another one. And also I duplicated the project and tried downloading that other project. I have even tried to connect on another network. In all cases, it now fails consistently every single time, after about 5-7 minutes. Not a single successful attempt over the last 14 hours. It would be interesting to see if on your side you see any success during this time period, because clearly on my end there was nothing successful.

**Comment by ready4sea** [comment]
Here's a additional piece of information : while trying to download the code from the Mac desktop app, it also times out.
<img width="627" alt="image" src="https://github.com/user-attachments/assets/28a94cc4-6743-4897-9e21-4818ca941463">

Could there be an issue with your code server being somehow unreacheable from some places / IPs ? A DNS problem of some sort perhaps ?

**Comment by ready4sea** [comment]
OK, I think I found the answer : following the latest MacOS update, it seems the built-in firewall is blocking the FF code download !

**Comment by wenkaifan0720** [comment]
Ah. Glad you figured this out!

**Comment by ready4sea** [comment]
This made it possible to work in the FF desktop app :
![image](https://github.com/user-attachments/assets/e9b573c5-3cc5-430c-aa7c-79f151b4a5c5)

However I tried this with the command line and didn't get it work :
![image](https://github.com/user-attachments/assets/d76411da-5200-4f9b-ba53-3541d22cef39)
Any clue if there is any other binary executable which needs to be allowed ?

**Comment by wenkaifan0720** [comment]
I don't think so. Does it work when you turn off the firewall?

**Comment by ready4sea** [comment]
Yes, turning off the firewall, it works.

**Comment by wenkaifan0720** [comment]
The flutterflow cli tool could also be called `flutterflow-cli`. But other than this I don't think we are using other executables.

**Comment by ready4sea** [comment]
Despite also adding flutter and dart binaries in the allowed list, I can't get it to work.
Seems like other apps are affected :
https://support.mozilla.org/en-US/kb/firefox-blocked-macos-15-sequoia-firewall-what-you
Guess I'll have to disable the firewall in the short run.

**Comment by wenkaifan0720** [comment]
Sounds good. We will keep an eye on it as well. Thanks for looking into this issue with us.

**Comment by ready4sea** [comment]
Yep, sorry I initially thought it was due to FF. Apple's major release came pretty much at the same time as yours, that caused the mix-up. I'll close the issue since it's not due to FF.
