### ISSUE TITLE
Actions restore themselves / cannot be deleted

### ISSUE THREAD

**Issue by wemmick** [FlutterFlow/flutterflow-issues#3953]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FF's error notification alerted me that "Action refers to action block that does not exist."

So I click on the error, and it leads me to a flow I don't fully recognize.  Per the screen, it seems to be an "onClose" event under the "Ask" screen, but that screen does not have an onClose event, nor do any screens afaik. I am not able to navigate to this flow except by clicking on the bug notification.

In this flow are 4 actions. If I try to delete any of them, after a few seconds they pop right back in. One of them refers to an Action Block that no longer exists (which is what the error refers to), so I tried creating an Action Block for it to point to, but once I do, after a few seconds it reverts to its original state (pointing to an Action Block of "Unset.")

Note: this mystery flow looks suspiciously similar to an old version of the onClose callback flow on the action I use to handle a streaming API. It looks to me like it somehow got duplicated but unattached from streaming API action and just attached itself to the screen instead?  Just a theory, but I seem to be unable to do anything about it either way. 

Here's a link to a video: 
https://www.loom.com/share/fb991f5418014e728f71e4e979502527?sid=80967530-5e57-4021-a30d-11f611cfb0a1

I showed the behavior to Leo in Support, and he recommended I post the details here.

Any help would be much appreciated - I can't get the error to clear, so I can't test/launch my project.  Thanks!

### Expected Behavior

I would expect to be able to delete these actions.

### Steps to Reproduce

1. Open my **RC Ai Mechanic** project (I have no idea how I'd recreate this in a new project)
2. Click on the error notification
3. See the mystery flow
4. Delete actions, and see them reappear

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ChuflxIt1pbxA+KqJdfowpDgXHGYlRY03kupDYxcaDZPMC+wIZ/f7XFRuTde0S1ZIJU2goDgx7t3emvPhGMBfIQqqRY9yz5NIVQzgWn6jWpS4DM3tS25/DeVmCXKk06W33wklVfZicmdk7WeyIumtc3PqH7LrO1YzJ+X8IZKK2SrDX1iXc2URm05KZDPz

### Visual documentation

Video: https://www.loom.com/share/fb991f5418014e728f71e4e979502527?sid=80967530-5e57-4021-a30d-11f611cfb0a1

### Environment

```markdown
- FlutterFlow version: 5.0.2
- Platform: Mac
- Browser name and version: Chrome 129.0.6668.60
- Operating system and version affected: Mac
```

**Comment by Alezanello** [comment]
Hello!

I can confirm the issue, but I'm unable to replicate it in a new blank project. Since this Issue Tracker is primarily for issues that can be consistently reproduced, I recommend reaching out to support via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They’ll be able to assist you further and help determine the root cause of this specific issue.

**Comment by wemmick** [comment]
@Alezanello I already talked with support - they recommended I file a bug here because they couldn't help fix it. I would very much appreciate someone taking ownership here, as I can't test/launch my app until this is resolved.

**Comment by wemmick** [comment]
Support was finally able to help me figure out how to resolve this, so we're good here.
