### ISSUE TITLE
Using a DocumentReference property in a DataType throws _debugIsValidParameterType when passing it as parameter to Cloud Function

### ISSUE THREAD

**Issue by pnaa** [FlutterFlow/flutterflow-issues#3954]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a DataType with a property of type DocumentReference it throws _debugIsValidParameterType when passing it as parameter to Cloud Function.

### Expected Behavior

Pass the parameter and properly execute the cloud function.

### Steps to Reproduce

1. Create DataType
2. Add DocumentReference property (or a List)
3. Call a cloud function passing the data structure as a parameter

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ysmAuJdPxOVA+KX2acdKnjwWH0c7RK87iet+Tg88KOvLBIYuP/XsVFZVZ/HkSghLekSmmk8F7srnv4fhEfQ3GAqdG58++ZF+EDr/XnKhe5OBCamwWUFtL91WClSX056FgBJ4JuhpSloS2zmmNu6UZD/UJKL4IlFISq/LZO4=

### Visual documentation

Error output in browser console.

### Environment

```markdown
- FlutterFlow version: 5.0.2
- Platform: Android / Web
- Browser name and version: Chrome (latest)
- Operating system and version affected: Web
```

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out. I’ve followed the steps to try and reproduce the issue but was unable to replicate it.

Here are the steps I took:

1. Created a new blank project.
2. Connected it to Firebase.
3. Created two collections: "users" and "products."
4. Created a DataType that includes a ProductRef (Document Reference from the Products collection).
5. Added the DataType to a Cloud Function.

Could you please confirm if I’m missing anything in these steps? Additionally, could you let me know which specific Cloud Function in your project is generating the error? I’d like to double-check it to help resolve this.

Looking forward to your response!

**Comment by isegal** [comment]
I've ran into this issue in the past and if I recall correctly it is because the serialization code is missing for DocumentReference types (a FlutterFlow issue).

**Comment by rzambroni** [comment]
Hi @pnaa, <br><br>We're closing this issue as we haven't received a response. If the problem persists, please feel free to open a new issue.<br><br>Thanks!
