### ISSUE TITLE
MacOS app is crashing very often

### ISSUE THREAD

**Issue by kamiloxl** [FlutterFlow/flutterflow-issues#3955]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I am using an app I have crashes and app is turning off after 5-10 minutes of usage. It is impossible to use it like that. Problem occurred after last update.

### Expected Behavior

No crashes...

### Steps to Reproduce

1. open app
2. go to project
3. do changes
4. start ios simulator

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8nl5ZV1ocdD7q6JYO5V9SYWNWkcTYARiO0bFB4gG5vkBIkuZs7BZUNKTOmYe29MDFCLrEMG+sLehd71J8cpCy+bGq1z0JVAYQqXJUOtM7axBpeKRXxARO9jCm600cOnhwlSANttLlI/1DiTNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/86be40d6-6b10-4076-8779-14a5ee2ec425/32b47638-6fe7-4e5f-9a0f-676733fc075a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NmJlNDBkNi02YjEwLTQwNzYtODc3OS0xNGE1ZWUyZWM0MjUvMzJiNDc2MzgtNmZlNy00ZTVmLTlhMGYtNjc2NzMzZmMwNzVhIiwiaWF0IjoxNzI3ODc5NDgxLCJleHAiOjMzMjk4NDM5NDgxfQ.jAI7ydx29vIb9eI1A54hrCbVzeXVfhaoJXu8XvsE6CM " alt="image.png" width="1483" height="1277" />

### Environment

```markdown
- FlutterFlow version: 5.0.2
- Platform: macOS
- Browser name and version: desktop app
- Operating system and version affected: macOS 15.0 (24A335)
```

### Additional Information

*No response*

**Comment by rzambroni** [comment]
Hello @kamiloxl,

Thank you for your report! I followed the steps you mentioned but was unable to replicate the issue. To assist you better, could you please share the full crash logs in a .txt file instead of the screenshot? Having the complete trace will allow our team to troubleshoot the problem more effectively.

Looking forward to your response, and we appreciate your patience!

**Comment by kamiloxl** [comment]
> Hello @kamiloxl,
> 
> Thank you for your report! I followed the steps you mentioned but was unable to replicate the issue. To assist you better, could you please share the full crash logs in a .txt file instead of the screenshot? Having the complete trace will allow our team to troubleshoot the problem more effectively.
> 
> Looking forward to your response, and we appreciate your patience!

[RTF to TXT error.txt](https://github.com/user-attachments/files/17240094/RTF.to.TXT.error.txt)

**Comment by kamiloxl** [comment]
Hey @rzambroni and @victoriahuang1 I spotted this problem on multiple different projects now.

**Comment by rzambroni** [comment]
Hello @kamiloxl,

Thanks for the follow-up. Victoria reviewed the logs you provided, but unfortunately, there isn't much information there that we can use to investigate further.

Have you noticed any patterns related to when the app crashes? For example, does it happen when accessing specific parts of the app or performing certain actions?

Your insights could help us narrow down the issue.
