### ISSUE TITLE
Custom dialog action crash flutterflow when selecting the middle up square of dialog alignment

### ISSUE THREAD

**Issue by pireslopesvinicius** [FlutterFlow/flutterflow-issues#3956]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When calling the action custom dialog and selecting the dialog alignment to the middle up square after some seconds it just crash flutterflow out of the blue.

### Expected Behavior

Well, It should not crash in any situation.

### Steps to Reproduce

1. Create a component
2. Call a custom dialog in somewhere (I used a button)
3. Select the middle up square in dialog alignment
4. Wait some seconds
5. Crash!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raCgoIYyuOpl/evWkbkhVZ9fiYWNbfUSmmkEF+ujrjvHfFsABGyWtf75kzqpyawvdeDihQZOBC82OVnxAGflTfXK9y8KRsBMkC/tucXAa7FyEH/KvbzDqNr7MImdISq/LZO4=

### Visual documentation

I described it above, so image not required.

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: Windows Desktop
- Browser name and version: Not applicable (used desktop version)
- Operating system and version affected: Windows 10 64 bits and Windows 11 64 bits
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. I’ve tried to replicate it by clicking on all alignments and waiting 10 seconds before selecting a new one, but I haven't encountered any crashes. Could you please provide a recording or video showing the exact steps you take leading up to the crash? This will help us better understand the problem.

**Comment by pireslopesvinicius** [comment]
https://github.com/user-attachments/assets/013f52c3-5589-4ea8-8793-8f449469df31


In the end of the video it crashed and stopped the video.

But also, when not crashing, it doesn't let me define the middle up square in custom dialog.

**Comment by pireslopesvinicius** [comment]
And when selecting the middle up square with the editor reduced it crashes

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by pireslopesvinicius** [comment]
I think so, or at least it was something specific to my project, I tried it again and It's not happenning again.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
