### ISSUE TITLE
Charts Issue

### ISSUE THREAD

**Issue by MuhammadAbdullah577** [FlutterFlow/flutterflow-issues#3957]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i put the charts widget on my screen and enter the required values and test the app the build is failed. I have test it on the new project there it was working fine.
![Screenshot 2024-10-02 191300](https://github.com/user-attachments/assets/6a40fb8b-2e67-4dd5-b286-fe3171495d12)
![Screenshot 2024-10-02 191332](https://github.com/user-attachments/assets/1cc1c429-68c5-4228-8c11-06057a1a1fb4)![Screenshot 2024-10-02 191421](https://github.com/user-attachments/assets/43a373e2-7bc0-40dd-ac5f-52ec5267947d)
![Screenshot 2024-10-02 191400](https://github.com/user-attachments/assets/cd09577e-86f4-47f1-bd40-c1c00054e093)

### Expected Behavior

There will be a chart on the screen just like the new project.

### Steps to Reproduce

1 Add chart widget to the adminDashboard page
2 at chart widget run a query to get my monthlyOrders list of documents
3 Select and firestore documents option and enter bar Labels & bar Values.
4 Run the Project but build is failed.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oj/KA4ZN2n7xY7rqJacFr/ScsJj8ja5ZMlutETk03NZ/NGpgMecmnPxdWcNOrTGNDe06mp14FpKjFkez9Ee4oPSyYfthyyLVpEAvgfD+XR8iTF7irPmh6AplQJ2KD15iZvhFDCNZoL3xk1EOyPeitTg7YGKbpOno8Sq/LZO4=

### Visual documentation

![Screenshot 2024-10-02 191421](https://github.com/user-attachments/assets/b3274f21-f77d-4832-a0bb-cc5c69a2a2f3)
![Screenshot 2024-10-02 191400](https://github.com/user-attachments/assets/28829e39-f11b-493c-9390-12bb6010af2d)
![Screenshot 2024-10-02 191332](https://github.com/user-attachments/assets/ca948fef-b49b-43f4-8f86-2ee2c036f608)
![Screenshot 2024-10-02 191300](https://github.com/user-attachments/assets/fd972869-cae1-45c6-87da-8fb29d82ebd7)
![image](https://github.com/user-attachments/assets/73149991-2fae-4a8e-84d6-1692aa9d90da)
the last One is the new project where it is working.

### Environment

```markdown
- FlutterFlow version: v5.0.2
- Platform: web
- Browser name and version: web Chrome 129.0.6668.60
- Operating system and version affected: hp Elitebook
```

**Comment by paulperez-dev** [comment]
Hi @MuhammadAbduliah577,

I hope you're doing well!

I wasn't able to reproduce the issue on my end. Could you please try to reproduce it on a blank project?

Thanks!

Best regards,

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
