### ISSUE TITLE
FlutterFlow Windows is missing some buttons available on FF Browser.

### ISSUE THREAD

**Issue by thesaadullahkhan** [FlutterFlow/flutterflow-issues#3958]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

These Appbar and Navbar Buttons are Not available on FlutterFlow Windows.

![FF Windows vs Chrome](https://github.com/user-attachments/assets/f40b5f3e-4d03-4cfd-a822-c4755ef070b0)

### Expected Behavior

.

### Steps to Reproduce

.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

.

### Visual documentation

.

### Environment

```markdown
.
```

### Additional Information

.

**Comment by paulperez-dev** [comment]
Hi @thesaadullahkhan,

I wasn’t able to reproduce the issue on my end. Could you please try updating the app and check again? Let me know if the problem persists!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
