### ISSUE TITLE
Lib emptyListWidget not recognized in consuming project

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3959]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a lib component into ListView "empty list widget" an error appear.

```Widget's empty list widget is set to a non-existent component.```

### Expected Behavior

The error should not appear when I use a lib component.

### Steps to Reproduce

1. create a lib, and a component with a text inside
2. publish the lib
3. create a proj and import the lib
4. create a component and put a ListView inside
5. create a variable of string list type
6. generate dynamic children with the variable
7. enable the empty list widget option in listview  
8. use the lib component in the empty list widget
9. error should appear

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTyc7c+YhPm7RB+Kn2ae1VuCoWI0MdXZIRmOtvewgjF774EIkAY+DsZVppZNyzaHxHeVmkmmId0NGOudrXKsdeCwybbr5yyJYNWBPPY3ylbIy0Dc+oZkdATNlWfkvC4cCjgwhQAMtidU4C6jiIP9i+bz2Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/076bafe8-2fcd-40cd-8cd0-45446b67b6df)

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: Web
- Browser name and version: chrome 129.0.6668.71
- Operating system and version affected: win 11
```

### Additional Information

Project bug code
ITFTyc7c+YhPm7RB+Kn2ae1VuCoWI0MdXZIRmOtvewgjF774EIkAY+DsZVppZNyzaHxHeVmkmmId0NGOudrXKsdeCwybbr5yyJYNWBPPY3ylbIy0Dc+oZkdATNlWfkvC4cCjgwhQAMtidU4C6jiIP9i+bz2Cf9qOYwx5e6fDbOY=

Library bug code
ITESyc7c5odgotdA+rr9YflAhR4jNlx7bZNFmu1tRRA3fJutBKYpWvT6XxdBXcDiTQtYJlWYrH4FpcrOj4XDMOw5GAyHb65I/pFuajnKWn+WMIiyOpewP0ZQOJ9RGEyfy5+32iR4ALZ2dVlpig/GSw==

**Comment by rzambroni** [comment]
Hey @nev-21,

Thank you once again for flagging another library-related issue. I was able to replicate it on my end using the steps you provided. I’ll be forwarding this to the engineering team so they can work on a fix.

We really appreciate your contribution reporting this issues.

**Comment by nev-21** [comment]
Thank you @rzambroni, I'm actively working with libraries, if I find more issues I will report them.

**Comment by nev-21** [comment]
Hi @rzambroni, any news about this issue?
