### ISSUE TITLE
Supabase schema not updated

### ISSUE THREAD

**Issue by dhurbhat** [FlutterFlow/flutterflow-issues#396]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When I change Supabase schema and refresh FF, I should be seeing the new table definitions - this doesn't happen.

## Current behavior (required)
Either FF doesn't show any tables, or when some event requires a repaint, for example, opening Browser Debug Console, only 4 tables show - when in fact the Supabase REST Schema as executed in cURL shows there are 10 tables and 1 view.

## To Reproduce (required)
1. Go to sample app: https://app.flutterflow.io/project/test-supabase-issue-jblz4y
2. Navigate to Settings -> Supabase AND Click Clear Schema
3. Click Get Schema
4. Notice that nothing shows up... OR you may see only 4 tables shown
5. Open Browser debug console... 
6. Now you'll see 4 tables... AND 
7. Notice that there is an error in the console on `main_dart.js` line number 6861 in what seems to be ofuscated or minimized method: `itO`.

`[Error] 
	itO (main.dart.js:6861)
	itP (main.dart.js:7153)
	$0 (main.dart.js:122468)
	iOa (main.dart.js:5706)
	iOQ (main.dart.js:5708)
	$1 (main.dart.js:121058)
	jod (main.dart.js:4392)
	(anonymous function) (main.dart.js:4400)`

### Bug Report Code (required, generate from Widget Tree)

Not sure what this is... there's no widget and there's no menu item or something with "Get Bug Report Code".

## Context (required)

1. I've reported this issue >10days ago on Discord & Community.
2. Waited for any response - zilch
3. After 4-5 days, and trying *dozens* of times with removing Supabase, recreating Supabase connections, and failing to see any resolution, I upgraded to Pro - thinking it might be some guardrail.  
4. Then after facing the same issue, reported it via Chat help... on Jan 17th
5. Shared all of the above details 
6. Also shared the cURL query and response with Chat participant David - please leverage this info from Support Chat... 

The Supabase API is returning all the tables in the schema - FF is simply not refreshing it.

## Screenshots / recordings
See the Support Chat for screenshots - also attached here.

**NOTE** - there was one time when a JSON parsing error showed up in the console - as you can see from the cURL output, the resulting JSON from Supabase is *very well formed*.

You can pick up the Supabase URL from the Support Chat (don't want to include it here) OR ping me to DM the URL; NOTE: the JSON output of Supabase Schema url is also in the Support Chat.

<img width="1261" alt="Screen Shot 2023-01-20 at 1 57 18 PM" src="https://user-images.githubusercontent.com/109981480/214149740-b372c4f4-167a-46ef-8ab9-73de8479573d.png">
<img width="1496" alt="Screen Shot 2023-01-20 at 1 42 20 PM" src="https://user-images.githubusercontent.com/109981480/214149744-2a221572-17a2-4edd-a705-93695ad3b005.png">

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): Web, MacOs Desktop
* Browser name and version: Safari, Version 16.0 (17614.1.25.9.10, 17614)
* Operating system and version (desktop or mobile): MacOS version 12.6

**Comment by dhurbhat** [comment]
In the meantime, could I programmatically add the additional tables to my code in Github so I'm not BLOCKED?
If so, how would I go about doing that?

**Comment by hariprasadms** [comment]
Hi @dhurbhat - I have tested this issue and can see working fine for me. I can see below tables and views.
Are you still facing the issues ?

![image](https://user-images.githubusercontent.com/17435678/214675969-9ed1c75f-fd82-49a9-ba4f-0cfc837101ad.png)

**Comment by dhurbhat** [comment]
Yup - still happening.  @hariprasadms 

See attached video

https://user-images.githubusercontent.com/109981480/214726341-09c3bde2-eb8e-457e-9728-5a8cb21976fe.mov

**Comment by dhurbhat** [comment]
@hariprasadms  - can we get on a video call and screen share?

**Comment by dhurbhat** [comment]
**NOTE** - I've switched browsers to Google Chrome on MacOS and now the tables do show up.

This issue seems to be on **MacOS Safari browser**.  Lost 20 days of dev on this silly thing!

**Comment by hariprasadms** [comment]
Hi @dhurbhat - Thanks, for letting us know. Good to see it is working fine for you now.

**Comment by dhurbhat** [comment]
@hariprasadms I think your statement of "... its working for you now... " is not entirely correct.
1. I had to figure out to switch to Chrome - and it works in Chrome
2. It **still does not** work in Safari.

**Comment by agreaves** [comment]
Thanks for the bug report! This was a strange one, as it appears somehow Regexes in Flutter behave differently between Chrome and Safari. The bug will be fixed in Safari next deploy 🙂.
