### ISSUE TITLE
Not sure a bug but needed feature

### ISSUE THREAD

**Issue by abbadabbatech** [FlutterFlow/flutterflow-issues#3960]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently you added the ability to capture key press and handle an action.  However you did not give a way to prevent the default behavior of a key.  i.e. if I use F5 as my key because of replicating an older console, then unless you directly focus back on the page the next time you click F5 it refreshes the page if its a webpage.

### Expected Behavior

It seems that you would have an added method to prevent default so that yours will work without issue.

### Steps to Reproduce

use key event for F5

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i+flwIt1n7xK+Kr2b8FsgiYXNl87aIIJmOtueEo8J5zKB+wAYvf7P1FWTL3jT2xYelmZhjgy1vfqiN7PGMAqOResRaY51ZduTwzgfEShVJ+VPLu7fW1RP/lQJmrD4bS3nSNBBOhtR1Etw2GqAvOvQXXbHbrqOVgkDc6lJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Its self explanatory, not an issue to see reproduced.

### Environment

```markdown
- FlutterFlow version: 5+
- Platform:web
- Browser name and version:chrome
- Operating system and version affected: mac or windows, tested both
```

**Comment by Alezanello** [comment]
Hello!

Thank you for your feedback! This is clearly a feature or enhancement request. If you don’t mind, I’ll pass it along to the engineering team as a feature request and close this issue to keep the GitHub Issue Tracker focused on bugs.

Thanks again for taking the time to share this!
