### ISSUE TITLE
MacOS FF crashed on Branching

### ISSUE THREAD

**Issue by caringan** [FlutterFlow/flutterflow-issues#3965]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Desktop app crashes when trying to click into Branching option

### Expected Behavior

No crash.

### Steps to Reproduce

1. Open Desktop app, open project
2. Click on Branching

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XlcmA04lIobhb7qXxbcFVimAsQ207a4JEi+5+WRQ1GLb3E+wcefT+T3JdOLyhSmw/PFv8sGUdpujRkob9G+QHAweVR75m1rtIZzrLWluXRpSUEZbpYHd8QMphNEuV0cK3oBZ+KtRsSV4j6166B+fJQgPXJqLuIVY3Ovr9CLvJ+XOpAj+6Xn0Jg1ZSfCvr

### Visual documentation

[Have a video but file size is 39MB]
<img width="1069" alt="Screenshot 2024-10-02 at 3 55 59 PM" src="https://github.com/user-attachments/assets/8c7614fd-4191-4001-8e83-eae6579c1593">

### Environment

```markdown
- FlutterFlow version: v5.0.2
- Platform: MacOS
- Browser name and version: - 
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by Alezanello** [comment]
Hello!

First of all, I’m sorry you're experiencing this issue. The good news is that we already have an internal ticket for this, and it’s on our track to be fixed!

With that said, I’ll be closing this ticket as a duplicate to focus our efforts on the main one. Don’t worry, I’ll link this issue internally to ensure everything is tracked properly.
