### ISSUE TITLE
Lib custom action can't be used in main.dart of a consuming project

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3969]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a custom action in a lib, i want to use it in main.dart in a project that doesn't have any custom action. After adding the custom action to main.dart the save button doesn't work, this error appear on chrome debug console:

```Uncaught Error: Unsupported operation: Attempted to change a read-only message (flutterflow.FFCustomCode)```

### Expected Behavior

Lib custom actions should be allowed to be added in main.dart of a project which doesn't any custom action.

### Steps to Reproduce

1. create a lib, add a custom action, publish
2. create a project, add lib action to main.dart final actions
3. click save, and nothing happens
4. check browser debug console, an error appear

NOTE: I noticed that if you create an action in the new consuming project, then you can use lib action in main.dart. It is like the new project enable something after create an action. After this the error doesn't appear again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiMj6y4hPm7RB+KqAKvpVliI4M0MBX5Ir1utvGAsjfLbpB7Qcfc7UaXdfOMOQdFVADEyWr3wK3PDvvYaSKMdfAyyZGrV607l6YT3LQkOVb7KWPc+sXEB9HZhhCmnC1qaJgAl5OrFYcnhgw2GPcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/fb8da119-e33b-452b-a03e-30a460ab89a2

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

_**(in this project, try to add the lib action to main.dart and save)**_

Project Bug code:
ITFTiMj6y4hPm7RB+KqAKvpVliI4M0MBX5Ir1utvGAsjfLbpB7Qcfc7UaXdfOMOQdFVADEyWr3wK3PDvvYaSKMdfAyyZGrV607l6YT3LQkOVb7KWPc+sXEB9HZhhCmnC1qaJgAl5OrFYcnhgw2GPcq3qNleeY8aSfxBlZ7vfcPo=

Lib Bug code:
ITESiMj6yIdgrt9f1pD2LPlQhR4jNlx7bZNEkcF9bAAcGJOvOpwpWvv7NhFDQs+UeGNbM1Wl+WQ0wezskuOfVvApOgyHb65I/pFuajnKWn+WMIiyOpewP0ZQOJ9RGEyfy5+32iR4ALZ2dVlpig/GSw==

**Comment by Alezanello** [comment]
Hello!

Thank you so much for bringing this to our attention. I’ve confirmed the issue on our end and will forward it to our engineering team for further investigation. We really appreciate your patience, and we'll keep you updated on the progress.

Thanks again!

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @nev-21. The fix will be released in a couple of weeks.

**Comment by nev-21** [comment]
Thank you!
