### ISSUE TITLE
Creating new parameter from variable menu changed local state Key name

### ISSUE THREAD

**Issue by digiecho** [FlutterFlow/flutterflow-issues#397]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

to be able to create a bottom sheet parameter from the variable menu with same name as the local state variable that the variable menu has been launched through

## Current behavior (required)

the local state variables name is updated to that of the name entered for the new bottomsheet parameter when setting a variable field for an update Local State Variable action.

## To Reproduce (required)

1. add action to button on a bottom sheet that updates a localstate 
2. set variable of action to new bottom sheet parameter from the variable menu
3. name the new parameter and hit save
4. See that the local state variable name has changed

## Context (required)

it renamed my local state variable i was updating and thus broke a few things

## Your environment

* Version of FlutterFlow used: lastest
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: chrome lastest
* Operating system and version (desktop or mobile): windows 10 dell xps 7590

**Comment by organicnz** [comment]
Hi @digiecho. Thank you for adding this issue, mate 🙂

Could you pls clarify exactly where you caught the change? It would be very helpful if you could add a little more detail, screenshots or a video clip on Loom :)

Kind regards,
Tarlan Isaev

**Comment by aemelyanovff** [comment]
@organicnz I can repro the bug.

@digiecho Thanks for reporting the issue! It'll be fixed in the next release.
