### ISSUE TITLE
FF doesn't connect to Firebase in dev environment

### ISSUE THREAD

**Issue by evzq** [FlutterFlow/flutterflow-issues#3973]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Copy the project ID
Click "connect"
Message received: Firebase project already associated with this project.
Bug notification is still shown saying firebase is not connected. 

I'm on a branch "feature" and setting up the Dev environment
I gave the necessary permissions to firebase@flutterflow.io

### Expected Behavior

Connect to Firebase

### Steps to Reproduce

Go to firebase
Copy the project ID: cirkle-dev-f0db5
Click "connect"
Message received: Firebase project already associated with this project.
Bug notification is still shown saying firebase is not connected. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40rfLey8l5rv1C5s3MdvRHgWMnH0QhROQZkth7aCosfZT2BLMcec/RVERoXfHnd1FHPmGKq2oW0fDOht+XVsdcC0maGIBi1KoNYTzyJV6jbLWbFJWgWGgkEdpgGHLDy5iskRNABNd2WCE72FyTe9+/SnfUJbW2CkU4Da/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/11cf40a0-586b-4810-b6f5-80b7b6c35288

<img width="940" alt="Screenshot 2024-10-03 at 22 19 27" src="https://github.com/user-attachments/assets/661a9c08-f476-411f-9ae9-c8f53a63d872">

### Environment

```markdown
- FlutterFlow version: web
- Platform: web
- Browser name and version: N/a
- Operating system and version affected: n/a
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry you're facing this issue. I tried to replicate it by adding Firebase in my development environment with a new blank project, and it worked without any problems. This seems to be a project-specific issue. I highly recommend contacting support via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) so they can assist you in resolving this.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by mravani2** [comment]
@evzq did you manage to make this work? I'm facing the same problem here.
