### ISSUE TITLE
Page Not Rebuilding on App State Change with Widget Builder Parameter

### ISSUE THREAD

**Issue by mackaby** [FlutterFlow/flutterflow-issues#3974]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I’m passing in a custom page-specific toolbar (to a global menu) for each page in my app using a widget builder parameter. Inside the toolbar, there’s an IconButton that toggles a boolean value in the app state. This boolean controls whether a sidebar section on the containing page is shown or hidden. However, when the boolean is toggled, the page does not rebuild, and the sidebar’s visibility does not update as expected.

### Expected Behavior

When an app state is updated (boolean toggled in my case), the containing page should rebuild if that is selected in the action.

### Steps to Reproduce

1. Create a page that contains a widget that should show/hide based on app state boolean.
2. Set up a component-A (for example a "Main Menu"), that takes in a widget builder as parameter (for example a page specific menu toolbar).
3. Component B should contain a widget that can toggle the app state boolean and that should rebuild the containing page.
4. See if you can containing page to refresh.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcqA5YxOsd9J1s75bccwmjk5JkB+U+Yz1+xBaCsofePrOpkAf8/7UFtUOP3kYHNYIU6Z/XsX/MrKj9npM+1cEE6sbNVJz81yUQLJeEWWaKqWOpS3b0YlIJtQf3WP4J6OkxNQXe5vWloa22D3Iee9bDXYJ5TXDEURNea4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Sreen recording:
https://app.screencast.com/joABiHAa4iWUT 

### Environment

```markdown
- FlutterFlow version: 5.0.2
- Platform: web
- Browser name and version: Chrome
- Operating system and version affected: MacOS Sonoma 14.6.1
```

### Additional Information

I would like to use the widget builder to pass in page specific menus instead of using conditional builder and passing in page index. Contct me and I can share specific projects where I want to do this.

**Comment by Alezanello** [comment]
Hi there!

Thank you so much for sharing the video and project, it really helps to get a closer look at the issue. Before we dive deeper, I wanted to ask—have you tried using the "Rebuild All Pages" option to see if it achieves what you're aiming for?

**Comment by mackaby** [comment]
Rebuilding all pages works.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
