### ISSUE TITLE
The Stripe Apple Pay is not working.

### ISSUE THREAD

**Issue by yuriidevelopment** [FlutterFlow/flutterflow-issues#3975]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an error and can't pay with Apple Pay. In Stripe, the payment is incomplete.

The card payment method works well.

### Expected Behavior

The Apple Pay payment method should work and allow the payment to proceed.

### Steps to Reproduce

1.Create an order.
2.Tap the "Purchase Now" button.
3.Tap the Apple Pay button.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l+fqwItPpbxB7qXcdcFKhmU5Jn5/bJI7jNZ7aCsofePrOpkAf8/7UFtUOO27Y1Z+f2eKhnoX/Mrtv+PpLcIrFy+rfr1z/5ZyaBbLQnujSq6wCoS3b3YnIJpPFWWB4KTQvREkKsteWHwD72eEI+qtYD3BJbGyDVgZPOa4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![IMG_7392](https://github.com/user-attachments/assets/d9f610b3-c97e-46b6-88cf-295972386523)

### Environment

```markdown
- FlutterFlow version: 5.0.2 
- Platform: MacOS Desktop
- Operating system and version affected: macOS Sonoma 14.4
```

### Additional Information

Logs:

StripePaymentSheet/PaymentSheet+API.swift:141: Fatal error: An error occurred in PaymentSheet. Attempted Apple Pay but it's not supported by the device, not configured, or missing a presenter
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: An error occurred in PaymentSheet. Attempted Apple Pay but it's not supported by the device, not configured, or missing a presenter
    frame #0: 0x0000000185425ebc libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x185425ebc <+0>: ret    
libswiftCore.dylib`:
    0x185425ec0 <+0>: b      0x185425ebc               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x185425ec4 <+0>: adrp   x8, 461988
    0x185425ec8 <+4>: ldrb   w0, [x8, #0x2dc]
Target 0: (Runner) stopped.

**Comment by Alezanello** [comment]
It seems like your app is having trouble presenting Apple Pay. This can happen if something in the configuration is missing or incorrect, or if the device you’re using doesn’t support Apple Pay. Let’s go through a few steps to troubleshoot and get this resolved:

### Check if the device supports Apple Pay:

First, ensure the device you’re testing on actually supports Apple Pay. Remember, Apple Pay is only available on certain Apple devices, and it must be set up in the Wallet app.<br><br>You can also check if Apple Pay is supported in your app by creating a **Custom Action** with a return value of "Boolean," and then add the following code:

```dart
return Stripe.instance.isApplePaySupported();
```

This will return `True` or `False`, letting you know if Apple Pay is supported on the app/device.

### Apple Pay setup in your Stripe account:

Go to your Stripe Dashboard and verify that Apple Pay is enabled. Navigate to **Settings > Payment methods** to confirm that Apple Pay is properly set up.

### Testing on a real device:

If you’re using a simulator, keep in mind that Apple Pay won’t work in that environment. Make sure to test on a real device that has Apple Pay configured.

**Comment by yuriidevelopment** [comment]
> It seems like your app is having trouble presenting Apple Pay. This can happen if something in the configuration is missing or incorrect, or if the device you’re using doesn’t support Apple Pay. Let’s go through a few steps to troubleshoot and get this resolved:
> 
> ### Check if the device supports Apple Pay:
> First, ensure the device you’re testing on actually supports Apple Pay. Remember, Apple Pay is only available on certain Apple devices, and it must be set up in the Wallet app.You can also check if Apple Pay is supported in your app by creating a **Custom Action** with a return value of "Boolean," and then add the following code:
> 
> ```dart
> return Stripe.instance.isApplePaySupported();
> ```
> 
> This will return `True` or `False`, letting you know if Apple Pay is supported on the app/device.
> 
> ### Apple Pay setup in your Stripe account:
> Go to your Stripe Dashboard and verify that Apple Pay is enabled. Navigate to **Settings > Payment methods** to confirm that Apple Pay is properly set up.
> 
> ### Testing on a real device:
> If you’re using a simulator, keep in mind that Apple Pay won’t work in that environment. Make sure to test on a real device that has Apple Pay configured.


1. Check if the device supports Apple Pay:
The function returned `True`
2. Apple Pay setup in your Stripe account:
The merchant certificate has been set up.
<img width="1235" alt="Screenshot 2024-10-04 at 5 34 46 PM" src="https://github.com/user-attachments/assets/f4f3a43b-6844-4d52-9bab-521850826071">
4. Testing on a real device:
Apple Pay was tested on a real device, the iPhone 11, running iOS 17.6.1

**Comment by xenomorph78** [comment]
I'm having this same issue with Stripe and Apple Pay. Same error: An error occurred in PaymentSheet. Attempted Apple Pay but it's not supported by the device, not configured, or missing presenter

This is an issue on 2 of my apps that accepts apple pay, where apple pay used to work, but no longer does.
This is on a iPhone 14, Stripe is in Production Mode, credentials are set in Stripe, Merchant ID is set in flutterflow>Stripe settings.

@Alezanello any update on this or are you still having this issue?

**Comment by xenomorph78** [comment]
!!! RESOLVED (FOR ME) !!!
In the FF stripe settings under MERCHANT COUNTRY CODE, I had 'USA'. 
After reading some documentation, I realized this was only supposed to be a 2-character entry ('US'). I changed it to US and re-deployed the stripe config, then re-deployed the app to the app store and BINGO! It worked!
@FlutterFlowEng, you could save a lot of headache to users if you made this field only accept 2 characters. Just say'n.
@Alezanello, let me know if this resolves your issue!
![Screenshot 2024-10-10 at 9 39 48 AM](https://github.com/user-attachments/assets/4062b449-c82d-4e56-b0e8-1455db4303f8)
