### ISSUE TITLE
Lib text-field cannot be used with set form field or reset form fields

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3976]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't use "set form field" or "reset form field" with a text-field inside of a lib component

### Expected Behavior

Set form field and reset form field should work with lib field widget

### Steps to Reproduce

1. create a lib, add a component and inside add a text field, publish
2. create a project, add the lib component to home page
3. add a button and try to "set form field" to the textfield, it doesnt appear
4. also if you want to reset form field, it will not appear. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzs/q34hPm7RB+KqMYe5WgjssI0MfWLsr0utuGA0hNYzqEIkuds77QFJLYte9TQt2GVWLhT8H3MrKkez1K+0BPTetGqU/ya5XQRXiXj2iV5iTBs/pekQnTJ1NBUCB3ImJoxRSJbBtR3At71OlNvCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/c2dc4150-c72c-4c08-a634-607819e21b07)

![image](https://github.com/user-attachments/assets/ae67964e-5cb5-401b-99c7-3603f087e4bb)

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform:web
- Browser name and version:chrome 129.0.6668.90
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
ITFTzs/q34hPm7RB+KqMYe5WgjssI0MfWLsr0utuGA0hNYzqEIkuds77QFJLYte9TQt2GVWLhT8H3MrKkez1K+0BPTetGqU/ya5XQRXiXj2iV5iTBs/pekQnTJ1NBUCB3ImJoxRSJbBtR3At71OlNvCNG3qCf9qOYwx5e6fDbOY=

Lib bug code:
ITFXzs/q34xNocRE17ridccwliEwGUAaU40V0t1ETRQbCIj4PO0uPMzBQBJBXsSzaH5IH1eJglkH+cnFi/LDUfJeFxCaRtVEzpZMehPPY3ylbIy0Dc+oZkdATNlWfkvC4cCjgwhQAMtidU4C6jiIP9i+bz2Cf9qOYwx5e6fDbOY=

**Comment by nev-21** [comment]
Please help @Alezanello @rzambroni these kind of error don't let us work. Thank you

**Comment by Alezanello** [comment]
Hello!!

Thank you so much for bringing this to our attention. I’ve tested the issue with Renzo, and I can confirm it’s a bug. I’ll be forwarding this to the engineering team for a fix. We really appreciate your patience, and we’re sorry for the inconvenience!
