### ISSUE TITLE
Tutorial shown everytime I reload/open project

### ISSUE THREAD

**Issue by priteshkumbhare** [FlutterFlow/flutterflow-issues#3977]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I reload the project, I see a tutorial which I have to skip to proceed to my work

### Expected Behavior

It shouldn't be shown

### Steps to Reproduce

This is the project link: https://app.flutterflow.io/project/travel-app-l9fvz4?tab=widgetTree&page=WinzTrade

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9Vu2UvH1B5R5c0sNobbxAjIoDoPJkUaeLBQFJVUte7S3xLKEWL8X8K0aHtj9nTO8FcFE6sQKJ6zc52TArid3y/aoSrDZOCS2hSL9NgGGq638OroiRRBPRqLyQj1GaIH+vIEwnDJYP7Zwh9f6PHaOI=

### Visual documentation

<img width="899" alt="Screenshot 2024-10-04 at 8 29 40 PM" src="https://github.com/user-attachments/assets/807aa749-6eb9-497d-934c-96f0aac18885">

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

### Additional Information

None

**Comment by Alezanello** [comment]
Hello!

I’ve discussed this issue with the engineering team, and it appears that this behavior only occurs in the demo project that’s automatically created when you first start using FlutterFlow. However, this won’t happen in any new projects you create—so it’s actually expected behavior and not a bug.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
