### ISSUE TITLE
Text Field Hover Glitch

### ISSUE THREAD

**Issue by ryanmish** [FlutterFlow/flutterflow-issues#3978]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When hover color and fill color are set to the same color and user moves mouse over a text field, it flashes with a dark grey color.

### Expected Behavior

There should be no change to the field fill color. 

### Steps to Reproduce

1. Add Text Field
2. Set fill to theme color
3. Set hover to same theme color

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESismBw5dgodtH+rXyc8FQhQMjNlx7bZAnktV+WRMhfL7tEZkDdeD4aVpLYteqfQs/DWKjhk4y/87zi9nhO/cpGxGeGZQ+wa5XQTzhXjqhM76QEriCfUcmJ8BgN3ajy8HR3RZ7HMlocXw76lOQIfCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://vid.pinpointinteractive.com/conversations/29e45f1c-17cd-579c-81bb-c442464eb97c

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.2+ released October 4, 2024
- Platform: Web
- Browser name and version: Version 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: MacOS 12.6.5
```

**Comment by paulperez-dev** [comment]
Hi @ryanmish,

I hope you're doing well!

I wasn't able to reproduce the issue on my end. Could you try recreating it on a blank project and see if it still occurs? That would help us pinpoint the problem more easily.

Thanks for your efforts!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
