### ISSUE TITLE
Barcode Config - Barcode value can not be empty (QR-code)

### ISSUE THREAD

**Issue by rodseventup** [FlutterFlow/flutterflow-issues#3980]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Everything is filled out correctly, but if you add a variable it sees it as empty, but if you manually fill in the field as defalut it does not show an error. Happens on Desktop and Web

### Expected Behavior

Works

### Steps to Reproduce

1. add barcode
2. change Barcode Value to a dynamic value
3. show error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8/fsYthnMxJ+r6JccdWmWMUH0ccTJA3iuxEbw4jCIz4BIoQZM/8Yk5VZNCzaH1mO1SGuFo07vz2kuLpUvQCBy6cf4Bnz88JYRPPbFq6V4SzPs6SYkZCDcVbIHXD4aSvhSJ4VeNuLnAD3E66e/Oscz6Cf9qOYwx5e6fDbOY=

### Visual documentation

![Captura de Tela 2024-10-05 às 13 50 09](https://github.com/user-attachments/assets/954b8062-f789-4272-aafb-1cbcea033436)

### Environment

```markdown
- FlutterFlow version:  v5.0.2+
- Platform: Desktop and Web
- Browser name and version: Chrome
- Operating system and version affected: Mac OS Sequoia 15.0
```

**Comment by rzambroni** [comment]
Hello @rodseventup,

Thank you for the report.

I wasn't able to replicate the issue you're describing using the provided steps. Everything seems to be working as expected on my end.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b7b1b776-6a3f-4cfe-9f54-fd8d68b1a444/f1a896e7-c7fc-4e16-ba98-72c82b62db31?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iN2IxYjc3Ni02YTNmLTRjZmUtOWY1NC1mZDhkNjhiMWE0NDQvZjFhODk2ZTctYzdmYy00ZTE2LWJhOTgtNzJjODJiNjJkYjMxIiwiaWF0IjoxNzI4MzE5ODUxLCJleHAiOjMzMjk4ODc5ODUxfQ.mGV_r_ERUBXuyMJiUKsKVUXckRG-BBIC6UTWkGT9s04 " alt="image.png" width="727" height="1158" />

Are you still experiencing the issue? It's possible that there was a delay in the Project Errors popup recognizing the value change and clearing the error.

Thanks!
