### ISSUE TITLE
Flutterflow AI Tools: New Page Creator: Page Generator Error: Node does not have richtext property 

### ISSUE THREAD

**Issue by rodseventup** [FlutterFlow/flutterflow-issues#3981]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Doesnt works with any prompt

### Expected Behavior

works

### Steps to Reproduce

1. try use page generator
2. put your prompt
3. error: Node does not have richtext property 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8/fsYthnMxJ+r6JccdWmWMUH0ccTeUzlO1hdwwbI+PqEJkAfuClVEpVWOqHTVZYA1SZ+UgFpvD9vtr9D/lfIQSWGIBaz4dxUxDhVTqgRL6QPJC8dHFQEcJYCUjH3MG33yUkHNZtLk4R2kOlfuuub3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Captura de Tela 2024-10-05 às 14 45 23](https://github.com/user-attachments/assets/e692b8a8-d70f-43b0-afdf-e7079ce91c00)

### Environment

```markdown
- FlutterFlow version: 5.0.3 Desktop and 5.0.2+ Web
- Platform: Desktop and Web
- Browser name and version:Chrome
- Operating system and version affected: MACOS Sequoia 15.0
```

**Comment by rzambroni** [comment]
Hello @rodseventup,

Thank you for the report. I attempted to replicate the issue, but everything seems to be working fine on my end. Are you still experiencing this? It’s possible there was a temporary service outage that caused the issue.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d00969a6-f603-4897-801d-4f5d471d57ac/78d637cd-a71e-4f83-a401-e8e29fcd6cb8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMDA5NjlhNi1mNjAzLTQ4OTctODAxZC00ZjVkNDcxZDU3YWMvNzhkNjM3Y2QtYTcxZS00ZjgzLWE0MDEtZThlMjlmY2Q2Y2I4IiwiaWF0IjoxNzI4MzIwMzcyLCJleHAiOjMzMjk4ODgwMzcyfQ.nVLgWuqFqmxyHy2Dm5pUYg-5JRjQwhVxzxClFMl0TLE " alt="image.png" width="446" height="374" />

Please let me know if it persists.

By the way, here is the page that was generated on my end using the prompt you shared:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1324b817-5d0b-498d-907f-7d411e60b344/f9c16a89-a258-4e73-b5b3-5dd5c95ffeeb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMzI0YjgxNy01ZDBiLTQ5OGQtOTA3Zi03ZDQxMWU2MGIzNDQvZjljMTZhODktYTI1OC00ZTczLWI1YjMtNWRkNWM5NWZmZWViIiwiaWF0IjoxNzI4MzIwMzcyLCJleHAiOjMzMjk4ODgwMzcyfQ._f8O_jOGFKs9TSphzcU6Aml6QkXPiwvFMHX55FyDIi0 " alt="image.png" width="504" height="836" />
