### ISSUE TITLE
Persistent Error: "TypeError: Instance of 'FunctionNameCallCloudFunctionCallResponse'" in Cloud Function

### ISSUE THREAD

**Issue by nexagoai** [FlutterFlow/flutterflow-issues#3982]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm encountering a recurring issue within my Cloud Function where the following error consistently appears:

Error debug serializing parameter: TypeError: Instance of 'FunctionNameCallCloudFunctionCallResponse': type 'FunctionNameCallCloudFunctionCallResponse' is not a subtype of type 'String?'
Despite extensive troubleshooting, I've been unable to resolve this problem. To isolate the issue, I've simplified my code to its most basic form, and the error persists.
![Screenshot 2024-10-06 at 06 42 20](https://github.com/user-attachments/assets/4994f324-a4c6-4900-9669-37ffcc59c9f3)
<img width="1583" alt="Screenshot 2024-10-06 at 06 46 56" src="https://github.com/user-attachments/assets/70a32b12-e626-4a59-8234-7eb3d9aff775">

### Expected Behavior

The Cloud Function should execute successfully without the specified error.

### Steps to Reproduce

1. Create a new cloud function.
2. Define name, parameters and return.
3. Save function
4. Deploy it
5. Run 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

aiAgentsCall

### Visual documentation

![Screenshot 2024-10-06 at 06 42 20](https://github.com/user-attachments/assets/cbeb308c-b1a7-4b53-b44d-86d8871c62c8)
<img width="1583" alt="Screenshot 2024-10-06 at 06 46 56" src="https://github.com/user-attachments/assets/70a32b12-e626-4a59-8234-7eb3d9aff775">

### Environment

```markdown
FlutterFlow v5.0.2+ released October 4, 2024
Flutter version is 3.22.2
- Browser name and version:Chrome 129.0.6668.90 (Official Build) (arm64)
- Operating system and version affected: macOs Sonoma version 14.5
```

**Comment by paulperez-dev** [comment]
Hi @nexagoai,

Could you kindly provide us with the bug report code for your project? This will greatly help us in identifying and resolving the issue more quickly.

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
