### ISSUE TITLE
Self-hosted dependencies not recognized correctly and throws error in FF

### ISSUE THREAD

**Issue by rpock** [FlutterFlow/flutterflow-issues#3984]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I encountered an issue while using the new Visual Studio Code extension from FlutterFlow to add dependencies via Code Push. Specifically, when adding a self-hosted dependency (in this case, the Isar package) through the extension, it results in the following error in the FlutterFlow App:
 
 `Project has an invalid pubspec dependency: "isar: {hosted: https://pub.isar-community.dev, version: ^4.0.3}".
`
<img width="302" alt="image" src="https://github.com/user-attachments/assets/0810f861-c89f-4454-994b-703e16b991b5">

### Expected Behavior

FlutterFlow should correctly recognize and handle self-hosted dependencies when added via the Code Push feature and it should also be possible to add self-hosted dependencies directly in FlutterFlow. 
 
FlutterFlow should successfully resolve the custom-hosted package  from the specified repository URL without any errors. 

### Steps to Reproduce

1. Use Visual Studio Code with your project
2. Add a custom dependency with self hosting like isar community edition
`dart pub add isar:^4.0.3 isar_flutter_libs:^4.0.3 --hosted-url=https://pub.isar-community.dev`
3. Push the Code back to your FF Project
4. You can see the error as described before
<img width="304" alt="image" src="https://github.com/user-attachments/assets/216b302e-8b7b-4ad5-8c8c-e88dd8b60c2f">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekvLqw4t2pbxb0LrxYMcxpwMwJ0QlUIInj+0bWRMhfZ/nPIk2YPf7XxNLYtThYFBEIWaIrEgDwvPHvuLhLPcoaCSbGKJI1b5XQQzLRjuiRYzWPc68RmpRHeRjI0ixy5+g2x5DKfViSFIg2l2EGPCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="828" alt="image" src="https://github.com/user-attachments/assets/495687a0-6e75-4659-9ec5-1a5dc74900c1">

<img width="328" alt="image" src="https://github.com/user-attachments/assets/7ac8411c-7a02-4118-b85d-ad606ffaf5c8">

Everything works fine in VS Code, but FF can't manage dependencies with custom urls at the moment.

### Environment

```markdown
- FlutterFlow version: 5.0.3
- Platform: MacOS App (not using Web App)
- Browser name and version: Safari 17.6 (19618.3.11.11.5) 
- Operating system and version affected: Sonoma 14.6.1 (23G93)
```

**Comment by Alezanello** [comment]
Hello!

This appears to be the expected behavior at the moment. It seems like this could be a feature or enhancement request. If a package cannot be added directly in the FlutterFlow app, attempting to add it locally will yield the same result.

The code export feature is designed to streamline your workflow and avoid duplication of effort, but it doesn’t allow modifications that would break the project. Essentially, it mirrors what’s possible within the FlutterFlow app (Web/MacOS/Windows).

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
