### ISSUE TITLE
App State List Items Disappear in Flutterflow backpanel

### ISSUE THREAD

**Issue by gtork21** [FlutterFlow/flutterflow-issues#3985]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the App Values section, when I add an app state variable, with data type list, boolean, persisted, then click on the list to add list items, (I added 5 list items ) the list items disappear if I refresh the browser page or go to a different area in Flutterflow. I tried in Google Chrome and Opera on a clean project

### Expected Behavior

I expected the list items that I added to remain in the flutterflow back-panel after refreshing the page, or moving away from that page. 

### Steps to Reproduce

1. go to App Values section
2. click + Add App State Variable 
3. Name it (checkboxes) - Field Type = boolean  is list (on) persisted (on) - create
4. Click the new list called "checkboxes" 
5. + Add Item 
6. Add 5 items
![created](https://github.com/user-attachments/assets/42167336-c6b0-4de0-8788-3ff656fd2dc3)
7. refresh browser, or click away from this page
8. return to this page and the list items that were created are no longer there
9. ![gone](https://github.com/user-attachments/assets/45e77c2b-d5ee-4ddd-80bf-e7f65f784ee0)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcr135VNj7xZ1s7QdcB7/WAvKUR/RYJMi+sbRRE0N5POD+x/fMnBN1dUONPkY1ZEemeZgnEX/Mr2j9nXEfpePQeaQa1yzKpUajrjUlGtVbqLPYS3b3RBO+RWG26G1sGZnCRDLrNfLng7312UFum9QT7YQJDvOEc/A+aeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![created](https://github.com/user-attachments/assets/42167336-c6b0-4de0-8788-3ff656fd2dc3)
![gone](https://github.com/user-attachments/assets/45e77c2b-d5ee-4ddd-80bf-e7f65f784ee0)

### Environment

```markdown
- FlutterFlow version: dont see where this is but I signed up on Oct 4th 2024
- Platform: ?
- Browser name and version: Google Chrome and Opera
- Operating system and version affected: Windows 10
```

### Additional Information

can't make checkboxes that work... so it's a problem.

**Comment by rzambroni** [comment]
Hello @gtork21,

Thank you for the report.

There seems to be something unusual happening. I was able to replicate the issue once, but after further testing with a non-persisted list and then changing it to persisted (after creation), the issue resolved itself, and now I can’t replicate it anymore.

Could you please check if this applies to your case as well?

1. Add App State Variable (type: boolean, is list: ON, persisted: OFF)
2. Add default values.
3. Click away and come back to App Variables.
4. Check if the values are removed
5. Edit the app state variable and add the Persisted to ON.
6. Click away and come back to App Variables.
7. Check if the values are removed

Thanks in advance for checking this!

**Comment by gtork21** [comment]
This seems to solve the issue. The added list items did not disappear if persisted was OFF when creating the list. Navigate away from page, return and list items were available as expected. Then, turned Persisted ON, and list still available as expected.

**Comment by gtork21** [comment]
To add, similar to your experience, after having done it successfuly once, I can no longer recreate the problem. The list now saves with Persisted ON before adding list items.

**Comment by rzambroni** [comment]
It is very unusual. I’ll check internally on our side as well to see if we can catch the bug. I'm glad it's working on your end for now! Let me know if anything else comes up.

Thanks,
