### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by Maoie86** [FlutterFlow/flutterflow-issues#3986]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying Push Notification in my project and I have already have a firebase project with a Blaze Plan.  I get an error wheneven i click on deploy which say to contact flutterflow support. 

### Expected Behavior

I expect to be able to deploy successfully

### Steps to Reproduce

1.  Create a new project
2. Add firebase support. 
3. Add firebase project ID and click connect. 
4. Enable Push Notification 
5. Click deploy.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iM/qx5B2rsRE1pCBKcJVlmU5JW57aIIrjuxBaCosfZT2BLMcec/RVERpXc+odEFUemegjWoW0/TNvoXtC8crFzabG4M6wbhUYQKXXT6gacm6FJWgbWglP8BTGFS65rTUrR4lXPhZcmQg1zqYDPOvdzDsGJj6DVcaDq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/a5742775-cc78-4ba0-accf-416fef00d0b8)

### Environment

```markdown
- FlutterFlow version: v5.0.2
- Platform:Web
- Browser name and version:Brave 1.70.123
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello!

I’ve reviewed your project and didn’t find anything that would prevent you from enabling Push Notifications. I also couldn’t reproduce the issue in a new blank project. Given this, I recommend reaching out to FlutterFlow support, either via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io), as the image suggests. They’ll be able to assist you further.

**Comment by Maoie86** [comment]
ok, thanks. will reach out to them
