### ISSUE TITLE
Custom Widget is wrapped with "ghost" Container 256x256

### ISSUE THREAD

**Issue by stepanic** [FlutterFlow/flutterflow-issues#3987]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a custom widget called SuperDragAndDrop, and it is used inside the component, which is shown in Custom Dialog.

![image](https://github.com/user-attachments/assets/b51ea0d1-69a6-4b69-a23e-e4c1e6c86aa9)

When Dart source is generated around `SuperDragAndDrop` it is generated Container with 256x256, which is nowhere visible inside of FlutterFlow Editor.

![image](https://github.com/user-attachments/assets/a0af340c-cf63-4a4f-8046-922769726c88)

This is the solution without a parent Container of Width=512
![image](https://github.com/user-attachments/assets/4a44b120-9e88-422e-b7cb-c8121504b501)

So, in every case, some "ghost" Container with constraints 256x256 is appearing in the generated Dart code.
![image](https://github.com/user-attachments/assets/4bcf3a85-cf68-4ef0-a2ee-1dd305a10873)

### Expected Behavior

To have generated a custom widget without that "ghost" parent wrapper 256x256, or without defined width and height constraints, just as an empty widget.

### Steps to Reproduce

1. create custom widget
2. put custom widget inside of the component

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ehcmB34p2tbxK1rr+KflR/TsvKVAja5JEldVxaAwafIPmOqQIduj+TGZuOLDid2xiPFmWgm0KpqnVhvzhEsACCByJY6ZCyLhyZzn/eEWjVYSVCs6KSHFQP8FPfEihzpuZhhEkAMpfdV4D602qDeqUSXPAQqboPmtAIsmlBLnDnXyVGnroG30Jg1ZSfCvr

### Visual documentation

![image](https://github.com/user-attachments/assets/6dc026fa-f203-498c-91ab-11f19dad3650)

![image](https://github.com/user-attachments/assets/0f132b8a-87e2-4c04-895f-eeffe6ec4d47)

### Environment

```markdown
- FlutterFlow version: v5.0.3
- Platform: MacOS
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

I have had that issue for the last three months, but I have been ignoring that with a local Dart modification/workaround, where I modify the Dart source with that
![image](https://github.com/user-attachments/assets/18bdb0ea-68e1-4850-acb4-dfb972c94fe1)

But it is annoying to resolve GIT issues whenever I modify anything in the related parent widget tree :))

**Comment by Alezanello** [comment]
Hello!

The "ghost" container is automatically created and mimics the width and height you set for the Custom Widget. For example, if you set the Custom Widget to 256x256, the container will adopt the same dimensions. If you set the width and height to "infinite" in your Custom Widget, the container will also mimic this and have infinite dimensions.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dd00a830-2475-4c97-80d6-ce9358e534e7/a9a8b354-9836-4936-a99b-52ababe69265?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZDAwYTgzMC0yNDc1LTRjOTctODBkNi1jZTkzNThlNTM0ZTcvYTlhOGIzNTQtOTgzNi00OTM2LWE5OWItNTJhYmFiZTY5MjY1IiwiaWF0IjoxNzI4MzkxNTA4LCJleHAiOjMzMjk4OTUxNTA4fQ.KRdmVOU8jrgqn6pc-v5S5pVL9T2JC-vCpHpIMXOyp7k " alt="image.png" width="1640" height="698" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1cc0f3b9-7f9a-4af8-9eff-2d08108b3c41/44df1b55-6b54-4a76-a15b-08bc6214a085?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xY2MwZjNiOS03ZjlhLTRhZjgtOWVmZi0yZDA4MTA4YjNjNDEvNDRkZjFiNTUtNmI1NC00YTc2LWExNWItMDhiYzYyMTRhMDg1IiwiaWF0IjoxNzI4MzkxNTA4LCJleHAiOjMzMjk4OTUxNTA4fQ.fIzcvSRp5M6ftfFmdgcSSmdDaLztgrsO7sTLZGcIvIA " alt="image.png" width="1153" height="825" />

**Comment by stepanic** [comment]
@Alezanello thank you for the response, but my Widget's implementation looks like this, it is full empty and completely implemented locally outside of the FlutterFlow, so I did not put 256x256 constraints anywhere.

![image](https://github.com/user-attachments/assets/04eb7cfd-9f1d-42ea-92ff-45533afb2142)

**Comment by stepanic** [comment]
@Alezanello, I tried to modify the custom widget source and recompile it, but I didn't get any error; there was only a warning about the dependency, so I resolved that and recompiled (but everything stayed the same).

![Screenshot 2024-10-09 at 09 31 01](https://github.com/user-attachments/assets/a85d7e39-2a0b-432a-b027-3c442518e84f)

It seems that on page UploadTracks the CustomWidget.SuperDragAndDrop lost the reference from the custom widget implementation
![image](https://github.com/user-attachments/assets/fef2ece0-ff2f-4480-a072-08be57f414e1)

Because when I use the FF option `View Code,` a completely different source is visible, but when I use `Go to implementation` in VS Code, the correct Dart file opens.

![Screenshot 2024-10-09 at 09 22 09](https://github.com/user-attachments/assets/28cb5c57-d90f-494f-aafe-a4fc7c3f7b09)

But the implementation of Custom Widget SuperDragAndDrop is different
![image](https://github.com/user-attachments/assets/fad0c68c-7c74-4eeb-b246-a34eea47b64b)


My only idea to fix this is to delete SuperDragAndDrop from the widget tree of the UploadTracks page and insert it again, can you suggest some other option?

This widget is complex because of a lot of custom callbacks, but I didn't get any compilation error from FF
![image](https://github.com/user-attachments/assets/8ca18d8d-5230-4eb0-85e6-005437f79d98)

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?
