### ISSUE TITLE
[PAGEVIEW] Index indicator bug with API CALL Infinite scroll

### ISSUE THREAD

**Issue by Thesergiolg99** [FlutterFlow/flutterflow-issues#3988]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- When creating a pageview with api call infinite scroll on, when swtiching on the indicator on first load it shows lots of indexes (wrong, there are not as much), and when first swipe, it changes and shows the correct indexes.
Example:
on first load:
<img width="29" alt="Captura de pantalla 2024-10-07 a las 12 16 18" src="https://github.com/user-attachments/assets/29dd3b59-8b14-4462-9c8d-f9c7d5297061">

after page swipe:
<img width="23" alt="Captura de pantalla 2024-10-07 a las 12 16 42" src="https://github.com/user-attachments/assets/0d6322b8-feb8-4980-8c33-77677cafd16a">

### Expected Behavior

Show the correct indicator from the very first time

### Steps to Reproduce

1. Create a pageview
2. Add an API CALL with infinite scroll
3. Create child on the PV with that api results
4. activate show indicator on the PV
5. First load: lots of indexes
6. On first swipe: Shows correct indexes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkvHqx89NodcF+KnQK8FGiWAUGUMcWOdEl+tuZwgbIoznBqQEOvfebkxtYOmgaVNcBmGipE0x3MrHi9/LDvZdIkyab7VxzJN2FAL0e2itbLqbEs20RWtPP5tMfHaD0quRkAklNtthSVI12EOYF9y/YDXDIuu/Zwh9f6PHaOI=

### Visual documentation

Uploaded before

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Every platform
- Browser name and version: ARC os X
- Operating system and version affected: OS X SEQUOIA
```

**Comment by Alezanello** [comment]
Hello!

To help us investigate, could you please share the initial response from the endpoint when it’s triggered? This will allow us to understand why so many indexes are being expanded. I've been trying to reproduce the issue but haven’t had any success so far.

Another suggestion is to try running the API call on component load or triggering an app state update to rebuild the component after the API call completes.

**Comment by Thesergiolg99** [comment]
The responde looks okay is just a jsonList which i parse as datatype with native FF api options and then generate childs, the API CALL is done in the pageview because i use FF native infinite scroll check so it must be done in the PV not on page load.

Thanks for your help in this

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
