### ISSUE TITLE
Phone auth doesn't link

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#3989]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Different authorisation methods with the same user email should be linked in FirebaseAuth. This works for Google, Apple and Email sign in but not for phone sign in so you end up with a separate account..

There's a link credentials feature in firebase auth that could be executed as a custom action but it requires a verfificationID to be passed as an input variable, from the output of the send verification code action of the phone auth flow. Flutterflow doesn't provide anyway to get this.

### Expected Behavior

Using phone sign in with the same email address as an existing auth user, should merge link the phone number to the same auth account

### Steps to Reproduce

Tried creating a custom linkcredentials action but needs to pass the verificationID from the send verification code action which the Flutterflow auth phone sign in action doesn't provide.

Tried creating a custom action for phone sign in action that requests an sms verification code so I can pass the verificationID but get an "app delegate swizzling is disabled" error.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTIMziNZ+exUbfaL1BuwIfMnRNltVYMSlaVNcHVqlvHwK/srJhvPPCcBdC0+uR4hl1od+Qwvee2imVL6kBqW7dXJCBeZTGB2m5Kek2R5COsZpSGMuw1OyN+mRVjLDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/5b597c13-68bc-4a01-864c-76c4c8edd5d1">

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: iOS app and android
```

**Comment by Alezanello** [comment]
Hi there!

I came across a post in the community that successfully addresses this using a custom action. You can check it out here:<br>[How to Add a Phone Number to an Existing Email Account](https://community.flutterflow.io/authentication/post/how-to-add-phone-number-to-existing-email-account-r7mmce07ZTLY4uB).

I hope this helps! Let me know if you need any further assistance.

**Comment by sanjayelate** [comment]
I've tried this method. It doesn't work due to the issue described in the ticket. 

flutter: Verification failed: If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotificaton: method.

Send code:
ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTeU30+thcw4bI+PmOrMUPcn7dhduWOqHYwk/fFb9rD0xzMGOkuPTDccBPRSZfZw7+c59UxDiQlqmVbrREpG0R3FSM/tWf0+Oy7SnhRYlOvF2ZVJi7V73BN+Qb3qCf9qOYwx5e6fDbOY=

Link account:
ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTeU30+thcw4bI+PqBIYUOffOQFRBWOqHSnNAP2L8vE0G+fTNifOSMsFfFxOtQYhkwodbUxDiQlqmVbrREpG0R3FSM/tWf0+Oy7SnhRYlOvF2ZVJi7V73BN+Qb3qCf9qOYwx5e6fDbOY=

**Comment by sanjayelate** [comment]
@Alezanello Can you please come back to me on this

**Comment by sanjayelate** [comment]
Hello?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
