### ISSUE TITLE
Test Mode slow and not update realtime

### ISSUE THREAD

**Issue by williamgh2019** [FlutterFlow/flutterflow-issues#399]
## Expected behavior (required)
Inside app has API call to display Product Title, Price and images, when I click on Test Mode it run find but instand reload fail not update.

## Current behavior (required)
During I edit app UI or correction error or data update the Instant Reload click 1 time does not update unless 2 time to update.

In Builder UI I have make image Border Radius 20px round 
<img width="550" alt="image" src="https://user-images.githubusercontent.com/17005582/214211320-affbbd1e-0ba8-4f58-8085-898f9a16f073.png">

Then on Test Mode 1 click on Instant Reload it does not update.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/17005582/214211714-bc7695fb-bdfa-46f2-a2e5-971ff2391304.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/17005582/214211539-66f90970-3ff9-47c8-9a1a-87085e30ade4.png">

If I want to see the result I need to click on Instant Reload 2 to 3 times to see update result.

This action lead me to troubleshoot error, sometime I have correct error ready but click on Instant Reload the result is not update make me feel the app still error.

**Comment by yoheisoito** [comment]
Hi @williamgh2019 
Thanks for raising this.
Are you still seeing this issue? I was not able to replicate what you've described.
Please see the created demo.

I am closing this for now, but please feel free to open it again if you still see the same issue.
I can try to investigate further.

Thanks!



https://user-images.githubusercontent.com/115172813/215786684-8ba1dd83-910a-40eb-a732-d6195f8058fc.mov
