### ISSUE TITLE
Lib component can't be selected when we set a widget builder param in consuming project

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3992]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Lib components can't be selected (are not displayed) when the dropdown to select the widget param is opened.

### Expected Behavior

Lib components should be selectable when setting a widget param.

### Steps to Reproduce

1. create a lib
2. create a component B with a widget param, and put that widget param on its widget tree
3. create a component C, with a hello world text
4. publish the lib

5. create a project
6. create a new component X, and put component B inside
7. in the B component, open the widget param selection
8. component C doesnt appear in the dropdown

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slPHl/Yt2rupI17Xyb8Jr/TosC1w7bZIOscpCbw4bIYj2P4lzY876PhdBTfG+Y3xifGCcp14x0fDujYaSMPdcBzWbf4By+qpuchbddzmlVqmTF7maT0B7I+NjIGqC58GVuSJ/BLFYWFlg3V6qJvOWcHTtHrq2Imo4Sq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/a1f54790-366d-45b4-83e3-6da00c74fdc8

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT4slPHl/Yt2rupI17Xyb8Jr/TosC1w7bZIOscpCbw4bIYj2P4lzY876PhdBTfG+Y3xifGCcp14x0fDujYaSMPdcBzWbf4By+qpuchbddzmlVqmTF7maT0B7I+NjIGqC58GVuSJ/BLFYWFlg3V6qJvOWcHTtHrq2Imo4Sq/LZO4=

Lib bug code:
IT4glPHl8Yt2rupI1rrUcO9aiWUvNk82aIc0sd4bGA0dCJzuPLMQdvWlYVVpUsemT1ViO0Smmk40+vzQvdriUsYCJUybf6E+ws5ucQ7LeFule5OBEriSOnNCEdpbfxWA5MPY3whdCPViZXwe3UyLfeuiQj7vK7H7IndISq/LZO4=

**Comment by nev-21** [comment]
I have noticed this also happen with component in consuming project:

- if you create a component similar to compB **but inside the project**, 
- and then create a new component "X2" wich uses the project-comp-B, 
- then you also cannot select any library component when trying to select a component for the widget param

**I mean, no matter where compB is defined (proj or lib), when you want to set a widget param you can't select a lib comp.**

**Comment by Alezanello** [comment]
Hello!

I was able to reproduce the issue without any trouble. Thank you so much for the clear explanation and the video—it really helped me pinpoint the problem quickly!

I'll pass this ticket along to the engineering team for a fix.

**Comment by leighajarett** [comment]
This issue has been resolved and should be in today's release!

**Comment by nev-21** [comment]
Thank you!

**Comment by nev-21** [comment]
Hello @leighajarett @wenkaifan0720, the lib components now can be select, but now the app Crash!

We can't work, it is useless to be able to select a libcomp if the app breaks at compile time!

Should I make a new issue, or you can reopen this issue?
.

![image](https://github.com/user-attachments/assets/c1bd3ffa-f0d4-4bc3-a5d4-ccf74617afee)

**Comment by wenkaifan0720** [comment]
Hi @nev-21. Sorry for the inconvenience. Could you provide another bug report code? I'll look into this. Looks like a missing import bug and should be easy to fix.

**Comment by nev-21** [comment]
Yes @wenkaifan0720 please help

Project bug report code:
IT4slPHl/Yt2rupI17Xyb8Jr/TosC1w7bZIOscpCbw4bIYj2P4lzY876PhdBTfG+Y3xifGCcp14ywcrrkePEU8EnFzGsRZx9+JNuQzrJe3ynaYuTF7maT0B7I+NjIGqC58GVuSJ/BLFYWFlg3V6qJvOWcHTtHrq2Imo4Sq/LZO4=

Lib bug report code:
IT4glPHl8Yt2rupI1rrUcO9aiWUvNk82aIc0rNlud0wdCeOoOrAqP8+lYVtWWOqHenw/AVX9kmI0pM7UiuHAFfIENTSbQYR51LlbUxDjVkiRbqqqPpCWeEclAftnJ0zF5rSs3RRABOt1c0Jn7Waue/CQa3qCf9qOYwx5e6fDbOY=
