### ISSUE TITLE
Lib component can't be used twice with different names in consuming project 

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3993]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a lib component in a project, they must have the same name of its lib component, if not the app crashes at compile time (test mode).

This only happen when you use 2 or more lib components in the same widget tree.

### Expected Behavior

The lib components can have any name, even if it is used twice or more.

### Steps to Reproduce

1. create lib, add a component "libComp", publish
2. create project, add "libComp" twice to home page
3. change the names of the component to libComp1, libComp2
4. test mode, the app crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z8+A5ZV2pbxa1s+Jbu9ajikXQ2U7RoERk+1TRRQ8J5DaPOxzP/TBaldWUs+0Twhie02grGUK3PfemvPTUPoDEzWAfJ851LludDvgYzqjaL63BpaSYm5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/489b75aa-4d10-4109-a68d-a3d5632281a6

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform:web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT48z8+A5ZV2pbxa1s+Jbu9ajikXQ2U7RoERk+1TRRQ8J5DaPOxzP/TBaldWUs+0Twhie02grGUK3PfemvPTUPoDEzWAfJ851LludDvgYzqjaL63BpaSYm5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

Lib bug code:
IT4wz8+A5ZV2pbxa1s+Jbu9VtCAsGDt6UK8a1uwbFSs8JJToPLAUZ8zBM05vZry5TH9DemKGinMK/PfqkfPpKfA4BzCrGbp+yc9qZwz/XjiRR83TBpO7fW1TN+hnIXK+5J6vnSUnGNJedXxn7UyPe+6vTi7AH4CxDG0ZQ+alLdeK2SrDX1iXc2URm05KZDPz

**Comment by rzambroni** [comment]
Hi @nev-21,

I was able to confirm the issue you're describing and will pass it along to the team for further investigation.

Thanks again for bringing this to our attention!

**Comment by AnushaFF** [comment]
Thanks for reporting the issue! We have identified and fixed the bug. The fix will be releases in 1-2 weeks!
