### ISSUE TITLE
Custom widget dependencie error

### ISSUE THREAD

**Issue by francco93** [FlutterFlow/flutterflow-issues#3994]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A few hours ago i try to import a custom widget from the marketplace, but it didn't fit to my needs so i delete it, now i try to compile the project and it return the erron in the preview picture #2, the error refers to a empty name on a dependecie as shows on the preview #1 picture, but as you can see on the preview #3 image i have not any custom code un my project. So i friendly ask you tht please give me a solution as quick as you can, becouse tomorrow i have a presentation and my project isn't compliling as it should. Thanks in advance.
![preview #3](https://github.com/user-attachments/assets/3d87c185-8785-4bfd-904e-8ef72ca8f54f)
![preview #1](https://github.com/user-attachments/assets/6334166d-d5c1-47ad-ad9d-11ba92d07584)
![preview #2](https://github.com/user-attachments/assets/d3359af9-d66e-4adc-a2e1-d7244c13fdd7)

### Expected Behavior

well the spected behavior would be that i can delete or modify the custom dependencies that i import to my project

### Steps to Reproduce

1. run the project on run(to see the specific error) or test mode(you can not see the error returned, you just know that something went wrong).
2. go tu my project depencies tab on configuration of my project TOPAL, and at the end of the list you'll see there is a dependendi added that have no name
[Error flow preview.webm](https://github.com/user-attachments/assets/70243e39-6ded-411a-8351-654fab3b7909)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NO CODE, BECOUSE IT ISN'T A WIDGET ERROR

### Visual documentation

[Error flow preview.webm](https://github.com/user-attachments/assets/03a6d1d7-c356-48ed-ab7e-c9bd15ed9634)
![preview #3](https://github.com/user-attachments/assets/c77345e9-337f-4bc2-affd-713ab4c384af)
![preview #1](https://github.com/user-attachments/assets/6f717656-1e1d-4a62-9e16-c0f3a73a52b5)
![preview #2](https://github.com/user-attachments/assets/8b2074ef-f749-4b36-911b-49d570caf7b5)

### Environment

```markdown
- FlutterFlow version:  v5.0.2+ released October 4, 2024 Flutter version is 3.22.2
- Platform: WEB
- Browser name and version: Versión 129.0.6668.90 (Build oficial) (64 bits)
- Operating system and version affected: WIN 11
```

### Additional Information

I CAN COMPILE MY PROJECT, PLEASE HURRY AS MUCH AS YOU CAN. THANKS

**Comment by Alezanello** [comment]
Hello,

Thank you for bringing this to our attention! I can confirm that this is a known issue, and it’s already in our backlog with an internal ticket assigned for resolution. To streamline our efforts, I’ll mark this issue as a duplicate, but I’ll make sure to link it to the internal ticket so we can use your evidence during testing. We really appreciate your help—thank you!
