### ISSUE TITLE
Lib component "name" in consuming project is lost on renaming, and its link doesnt work

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3995]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we use a lib-component in a project, we usually change its name, but on renaming the widget the original name is changed too, so we dont know anymore what is the original lib widget. 

![image](https://github.com/user-attachments/assets/d176a8e9-59eb-4a60-a651-7d2bbfb87533)

Also, when we click the link it goes to a nonexisting component (the url query param has the edited name, not the lib component name).

![image](https://github.com/user-attachments/assets/60bd89a5-e963-4068-9c58-7783e48a8cfb)

### Expected Behavior

- The name of the original component (the name in the link) must be the original lib component name.
- The link should redirect to the existing lib component (of the lib version that is currently used).

### Steps to Reproduce

1. create a lib, add a "libComp" component, publish
2. create project, import the lib
3. add the "libComp" to home page
4. change its name to "libComp1"
5. you can see the original name change, and the link doesnt work correctly.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z8+A5ZV2pbxa1s+Jbu9ajikXQ2U7RoERk+1TRRQ8J5DaPOxzP/TBaldWUs+0TQhIO02GoGM0psHemvzLA/c5C0+dRoA7zs8JUxaVeEKhWoy3O6iSVG5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/699203dc-19e5-4943-90fe-b049be998d2e

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: Chrome Versión 129.0.6668.90
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT48z8+A5ZV2pbxa1s+Jbu9ajikXQ2U7RoERk+1TRRQ8J5DaPOxzP/TBaldWUs+0TQhIO02GoGM0psHemvzLA/c5C0+dRoA7zs8JUxaVeEKhWoy3O6iSVG5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

Lib bug code:
IT4wz8+A5ZV2pbxa1s+Jbu9VtCAsGDt6UK8a1uwbFSs8JJToPLAUZ8zBM05vZry5TH9DemKGinMK/Pfqkd7PL8dfCwWsGdVjwZZiSznMJX+VR7aTEquVfW1TN+hnIXK+5J6vnSUnGNJedXxn7UyPe+6vTi7AH4CxDG0ZQ+alLdeK2SrDX1iXc2URm05KZDPz

**Comment by nev-21** [comment]
Maybe related with #3993

**Comment by AnushaFF** [comment]
Thanks for reporting the issue! We have identified and fixed the bug. The fix will be releases in 1-2 weeks!

**Comment by nev-21** [comment]
Hi, @AnushaFF thank you for the fix.

In the 5.0.8+ (oct-22) release I think something is missing: the clickable link of the lib component has a redundant name, this hyperlink should have the name of the lib component (the origin) not the consumer name. It is a little difficult to understand which lib component I'm using if the original name is changed. Sorry if I didn't explain well in this issue.

![image](https://github.com/user-attachments/assets/17820571-9f04-45c2-ac7b-bdf1986863e7)

**Comment by AnushaFF** [comment]
@nev-21 Thanks for pointing out. Will re-open the issue!

**Comment by nev-21** [comment]
@AnushaFF also i noticed in other projects that when click the link, it redirects to a "commit" in which the lib component doesn't exist.

project bug report code:
IT4Cj8nf5c9NoctD+KruYMBr/ScWHDM+RYE00sFTdxQdN5PND+x/esnRQFJuZ9OrdghPM1m0o3EJ/smPm9z1CcAECzmdY4BB+s0JdD3KWmGnV6WbCquOYHdUGshPCG7A06aFmB4nXfRaLy1iwUOmOOSATg3dNJ+wOVgRDsqXB5PXvgfuQ0SLb3kNh1JWeC/v

library bug report code:
IT48j8nf5c9NoctD+KruYMBr/SMUJkM7a68zk9VEFBY8J5DaPOxzP/TBaldWUs+0YFZlM0yJ/Dkx/vPemvz+G/YEGAesb7ZTwqlUdDyXTkeibqnQEZeaT25/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

**Comment by AnushaFF** [comment]
> @AnushaFF also i noticed in other projects that when click the link, it redirects to a "commit" in which the lib component doesn't exist.

@nev-21 That is being tracked internally as a part of a related issue and would be addressed separately from this fix
