### ISSUE TITLE
Conditional padding is not working as expected.

### ISSUE THREAD

**Issue by mikemaxwell413** [FlutterFlow/flutterflow-issues#3997]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am attempting to add conditional padding to a container inside of a row to change based on the screen width. When I add a constant value, the padding will be added to the container or row. The condition will recognize the default value but not change based on whether the condition is true or false. I have tried the conditions as well on visibility settings and other properties such as minimum width but have had no luck with it functioning properly.

Condition w/o default value: https://snipboard.io/IeUFfn.jpg
Condition w/ default value: https://snipboard.io/euh9Vy.jpg
Constant value: https://snipboard.io/NvB6QI.jpg
Widget tree: https://snipboard.io/XelfMo.jpg

### Expected Behavior

When the condition of the screen width is true, the padding should add the desired value.

### Steps to Reproduce

1. Add a column widget.
2. Add a row widget.
3. Add a container.
4. Add a condition based on screen width to the padding of the widget to the desired value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkPLlw492sbVE0JDTYMd4iiowGUALa+dI0tZ+TQ0jF5D4EKQiZvfsakhtTtCzaH43PGKkjlwD0NbWuNnLNfY6FE+qfqU+ypZySRPPbHOjbqqTDc6ze0RABdpUIUCGyKuC2B4nHNBiZXxm3U2qIdnKST6Cf9qOYwx5e6fDbOY=

### Visual documentation

The screenshots should provide the information needed to troubleshoot the issue.

### Environment

```markdown
- FlutterFlow version: Was unable to find this information.
- Platform: Web
- Browser name and version: Norton Private Browser Version 128.0.5819.138 (Official Build) (arm64)
- Operating system and version affected: MacOS Sequoia Version 15.0
```

**Comment by Alezanello** [comment]
Hello,

Have you had a chance to test this in both Test Mode and Run Mode? In the UI Builder, conditional values don’t fully display their behavior until the app is compiled. Also, I noticed that all the values seem to be the same (20). Could you double-check that as well?

Let me know if you need further assistance!

**Comment by mikemaxwell413** [comment]
I downloaded the code from FlutterFlow and ran the project within xCode. When running the app on a simulator, the conditional padding is working as intended! Thank you so much!
