### ISSUE TITLE
Using a Widget as a parameter with a data JSON parameter causes a build error in the library.

### ISSUE THREAD

**Issue by davidcast95** [FlutterFlow/flutterflow-issues#3998]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We create a library that using Widget as parameter with a data JSON parameter.
Then we use library on other project. 
Build error occurred with listed below:
![image](https://github.com/user-attachments/assets/9390b5c9-84c6-47dd-b34f-55f6ac495f67)

### Expected Behavior

Run project properly and success to build

### Steps to Reproduce

Build the project below.
https://app.flutterflow.io/project/project-error-17iiaz
Error occurred.

Widget that related is in this page.
https://app.flutterflow.io/project/project-error-17iiaz?tab=widgetTree&page=Orders

On OrderTableViewProfessional

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMjfsI52ocMA+KruYMBv9Sk5JU98aIIRiupBaCsofePrOpkAf8/7UFtUOeaoTUFAP0yKrH8X/MnFhdmWDPJfISmVft1Z+al+ZALwUjmVb6auCL63b3JfI8dhGn6/y56ZuRF5BONfL0YY2GCqBumQYDDvJO/0NjAdR+aoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Same step above

### Environment

```markdown
- FlutterFlow version: v5.0.2+ 
- Platform: Web
- Browser name and version: Flutter Run Cloud
- Operating system and version affected: Flutter Run Cloud
```

**Comment by wenkaifan0720** [comment]
Hi @davidcast95. This should be fixed in our next release. Thank you!

**Comment by davidcast95** [comment]
> Hi @davidcast95. This should be fixed in our next release. Thank you!

hi @wenkaifan0720 thank you so much. means a lot for next project to build
