### ISSUE TITLE
The caller does not have permission to execute the specified operation in adding dependences screen

### ISSUE THREAD

**Issue by kamiloxl** [FlutterFlow/flutterflow-issues#3999]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I am trying to add dependency in project settings I always got error "The caller does not have permission to execute the specified operation". I tired from 2 different accounts connected to the project and always the same problem. I am using desktop app on mac m2.

### Expected Behavior

Dependencies should work :) 

### Steps to Reproduce

1. Go to settings
2. Project Dependencies
3. Add dependency
4. try to add dependency 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8nl5ZV1ocdD7q6JYO5V9SYWNWkcTL4zlO1HcxAYGO/yPbJ/fODBSFppTs+lSnlhHGCYjkYd0tb5heHtIPlcBwutRoM51ZFhETrJXXq8R7aqC6i8ZnB7P8JMCEye56avhh5+KtJqSHdk712qF+itdCnqN5+/Zwh9f6PHaOI=

### Visual documentation

![Zrzut ekranu 2024-10-8 o 10 18 08](https://github.com/user-attachments/assets/2440921c-766f-4e8f-bd4e-400e42fcb1f6)

### Environment

```markdown
- FlutterFlow version: 5.0.3
- Platform: desktop app on macOS
- Browser name and version: desktop app on macOS
- Operating system and version affected: macOS 15.0 Sequoia (Chip M2)
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. Would it be possible for you to share a video showing how you're trying to add the dependency? Just a quick reminder: the dependency must be a published library project.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
