### ISSUE TITLE
[CRITICAL PROBLEM.  Fix ASAP].  Widget tree jumps by itself and extends a node on single click.

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#40]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When selecting a widget the tree should not scroll by itself.  Especially in complex designs the widget structure is an important visual context.  It should not move or change by itself. 
A parent widget should not expand or collapse on single click.  First click should select a widget.  A second click should expand or collapse it.

## Current behavior (required)

Currently when selecting a widget in the middle of the visible tree the whole tree scrolls up for some reason. It should not.   
Until recently the expand/collapse worked properly.   Today i created a new project and all of a sudden a single click on an unselected widget both selects and expands/collapses it.  wtf.   This is absolutely not a standard behavior.  Please revert back to normal.

## To Reproduce (required)

1.  Open a page with a complex structure
2.  Scroll to the middle/end of the tree
3.  Click on an unselected widget with children
4.  The tree scrolls up
5.  The clicked widget selects and collapses/expands

## Context (required)

It makes working in the widget tree extremely slow and frustrating.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

Kubuntu, Chrome Version 105.0.5195.125 (Official Build) (64-bit)

[tree-bugs.webm](https://user-images.githubusercontent.com/1024870/196397789-1939e5b9-d5e7-44b2-8c55-be41fb7e0d46.webm)

**Comment by bulgariamitko** [comment]
Is this not a normal behavior? I mean the widget is collapsed and then you Expanded it and that is why the whole widget tree moves like that.

**Comment by bulgariamitko** [comment]
I just in the community there is other user having the same issue
https://community.flutterflow.io/c/bugs/widget-tree-buggy

**Comment by KirilOkun** [comment]
two separate issues here:
1. expanding and collapsing should happen only below the widget.  the whole tree should not randomly jump.  in the screen video you can see that the clicked widget is jumped to the top of the tree.  that should not happen.   the only time when the tree auto-scrolling is appropriate is when a widget is selected on the canvas and it's not visible in the tree.  so the tree would scroll to show that widget.  

2.  expanding a collapsing should not happen on the first click since selection of a widget has its own semantic meaning, i.e. changing the properties panel.   so expand/collapse should happen on click of an already selected widget and not an unselected one.

i did see the jumping problem a month ago or so but it was quickly fixed.  it's back again.   the collapsing/expanding used to work as well.  this new problematic behavior is very recent.  
apologies if i'm not explaining it well.  let me know if you have any questions.

**Comment by KirilOkun** [comment]
Also just noticed that selecting a widget in the canvas does move the widget tree, but only sometimes.  At other times the tree does not move to show the selected widget. So even the desired auto-scrolling behavior is not consistent.   In my experience in UX it is rarely a good idea to change the user's visual context automatically.  It's very disorienting and should be avoided unless there's a very good reason or the user explicitly chose that behavior.  Keep things where the user expects them to be.  Don't move them around randomly.

**Comment by KirilOkun** [comment]
What's the status on this?   The tree still jumps around on every click on a widget making a user go hunt for it.  Somehow i don't think that FF should behave as a video game. This is a critical problem that was introduced in the last week.  If the fix is too long please roll the recent changes back as none of them are more important than having a stable widget tree.

**Comment by bulgariamitko** [comment]
@KirilOkun this infor was added from one of the users in the community. Can you confirm this information? 

> I tried to narrow down what was happening with this. I think I found something that might help as you dissect it. It seems like a listview that has basic components does fine with the scrolling - no glitch there. The issue only shows up when the list view contains a widget that has another query attached to it. In my case there is a “document from reference” query on the message containers that shows the users profile of the person who sent the message. If the picture or the name is visible on the list then the entire list freaks out like what is shown in the video above. If it is not visible and there is not a “sub” query, then the list does fine.

**Comment by agreaves** [comment]
Hi @KirilOkun, thank you very much for reporting this and apologies for not responding sooner! This issue was fixed in our release two days ago, I'm going to close this ticket as fixed but please let me know if you are experiencing it again or something similar!

**Comment by KirilOkun** [comment]
@agreaves   Thank you very much.  It's fixed indeed.  Being a stickler for UX I'll be happy to help testing future widget tree changes or any other UI features.  Just let me know.

@bulgariamitko    I saw that issue happening even when neither the listview nor any of its children had any queries at all.
