### ISSUE TITLE
Ipados 16 external mouse scroll not working in flutterflow

### ISSUE THREAD

**Issue by flyingboy007** [FlutterFlow/flutterflow-issues#400]
I have an M2 Ipad and I always do flutterflow on it as it's more powerful & faster than my other intel machine. Almost everything works except the external mouse scroll. When we try to scroll using the mouse's scroll wheel, it won't scroll in the flutterflow website. Virtually all other sites I tested work fine without any issues, so not an iPados bug. But in flutterflow, if we select any input field (like component/page search field/or whatever triggers a keyboard) then the scroll works as expected. It is frustrating to work with as of now as we need to trigger the keyboard somehow for the scroll to work.  I tried safari, chrome & firefox & all behaved the same on iPad.

**Comment by hariprasadms** [comment]
Hi @flyingboy007 - 
Thanks for sharing the details. I see you are using ipad to access flutter-flow. As per my experience using flutter-flow, flutter-flow on desk gives more productivity and good user experience. As of now I think flutter-flow more compatible to desktop browsers than ipad or smaller screen devices. However, we can mark this issue as feature requirement for future versions of Flutter-flow. I hope this can help you. 
Thanks

**Comment by katherineqian** [comment]
Hi. Unfortunately, because FlutterFlow does not officially support iPad, we will need to consider this as a feature request rather than a bug. Thank you for your contribution!
