### ISSUE TITLE
Local run not performing action blocks

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#4000]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running an iOS simulator in Local run, no action blocks are performed. 

### Expected Behavior

When an action is triggered, action blocks should run in the same manner as standard page actions

### Steps to Reproduce

Create page with actions
Create action block
Add to actions on page
Test in local run

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTL4zlO1HcxAYGO/yPbJ/eszeS1htTdOmYWlhHE7/oGEfw97Gvt+TGMIVHzGZY4hI1qp1WBXyd3q8R6qzDaqeP2h7GeBWCGKm0cGKkQlSKu5qL0Inw3GEed6vEwzsGZ+/Zwh9f6PHaOI=

### Visual documentation

No relevant image

### Environment

```markdown
- FlutterFlow version: 5.0.3 (building on Mac)
- Platform: iOS
```

**Comment by rzambroni** [comment]
Hi @sanjayelate,

Thank you for your report! I tried to replicate the issue on my end but everything seems to be working as expected. I created a quick action block, and it performed well in the iOS 18 simulator.

I also reviewed the code you shared but couldn’t find any use of action blocks on the "Personality" page.

Would it be possible for you to create a quick example in a blank project? This would help us narrow down the issue and troubleshoot it more effectively.

Looking forward to your update!

**Comment by sanjayelate** [comment]
The action block on the personality page are on the save changes button. I've created another bug report code to that exact button: IT40rMjmx6l5osda0Mz2K/Fp/RwhOUM1RJA3tdVBaCgoIYyuOpl/evWkNlVvcMekYX9mIESmmmEH0vzujdrLUMYEBxauY4M4wZdqSRbLXkWge5OBDauaSnxPFtJVGFS71KbYuSZBKbJiSEIQ3Fy1NfCiVj/aGKb3ImdISq/LZO4=


It's only with the simulator, it works fine if I run a build on my physical device or on the production app.

**Comment by rzambroni** [comment]
It seems like this issue isn't affecting every action block, but rather it’s specific to the one you're using there.

Since I don’t have the necessary permissions to run your project, it’s difficult for me to recreate the issue. Could you confirm if this happens with other action blocks, perhaps simpler ones, or if it’s just isolated to this one?

We'll need to narrow down the issue a bit more, and ideally replicate it on a blank project so the engineering team can investigate further.

**Comment by sanjayelate** [comment]
It happens with every action block. Is there anything to indicate why it happens with the simulator and not on a physical device?

Here's another example page:

ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTIMziNZ+exUbfaL1Bux+dcjOblNtQu2/aVNfM1GWjl0zpKHJvd7LLO45PTCVboRSwsxUURf0e2imVL6kBqW7dXJCBeZTGB2m5Kek2R5COsZpSGMuw1OyN+mRVjLDFOu/Zwh9f6PHaOI=

**Comment by rzambroni** [comment]
Have you experienced the same behavior even in a blank project with a simple action block?

I’m not aware of any issues like this at the moment, but I’m checking internally to see if anything might be related.

**Comment by sanjayelate** [comment]
I have tried a blank project with just a single change to a boolean app state. It worked fine but not sure if that was because it wasn't calling any kind of database or api. It's hard to recreate the complexity of the action blocks in my main project. However, they were working fine before and I've even rolled back to previous versions I know worked to check and even they don't work in the simulator now

**Comment by rzambroni** [comment]
I believe our issue might be related to another one that came up today: [GitHub Issue #4001](https://github.com/FlutterFlow/flutterflow-issues/issues/4001).

It seems the action blocks may be executing, but the backend calls are being blocked on the simulator.

A colleague is currently working on that issue, and I’ll keep you posted on any findings.

**Comment by sanjayelate** [comment]
@rzambroni Do you have an update yet? It's affecting both Android and iOS simulators which is stopping my Play app from being approved.

I could be wrong but these issues all might be related:

https://github.com/FlutterFlow/flutterflow-issues/issues/4000
https://github.com/FlutterFlow/flutterflow-issues/issues/4001
https://github.com/FlutterFlow/flutterflow-issues/issues/4047
https://github.com/FlutterFlow/flutterflow-issues/issues/4048

**Comment by rzambroni** [comment]
Hi @sanjayelate,

Apologies for the delay in getting back to you. I’ve forwarded this to the engineering team for further investigation. As you mentioned, the issues do seem related, but we’re still working on finding a reliable way to replicate them. I will keep you updated as soon as we have more information.

Thank you!

**Comment by rzambroni** [comment]
Hi @sanjayelate, I just wanted to follow up and check if this issue has been resolved for you. It looks like the other related issues you mentioned earlier have been closed, and our team was unable to replicate this specific issue on our end. Please let us know if you're still experiencing any problems or need further assistance.
