### ISSUE TITLE
Local Run : Pending API Call

### ISSUE THREAD

**Issue by MamadAsap** [FlutterFlow/flutterflow-issues#4001]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an issue with a custom calls ( PUT/POST and GET request ) ,
when i set my calls and try it everything is ok i have responses but
when I test it from the local version of Flutterflow it works but when I use the local run the call remains pending...

### Expected Behavior

calls should return responses as when i preview and  test 

### Steps to Reproduce

1. Create a custom call 
2. Add this custom on a page 
3. Launch the simulator
4. Check the debug tool / Network tab

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8iAz4hgoctH176Jc/pV+TsUJlgnbZZMju5xaEo0G5fNGogUY8jeVERoTu3idFFifWeKo2oW0vT9kof1Kfk3EweCfYBDzLpyeg3hXkKnbrqIFJWgQkBBO5hWJm6y58PUuBFQC/V2R1If2juQAOetaHHtK5D1PVUkDq/LZO4=

### Visual documentation

![Local Run Pending API](https://github.com/user-attachments/assets/8dc103bb-b56e-4818-828a-1448f442f692)

### Environment

```markdown
- FlutterFlow version: 5.0.3
- Platform: Desktop
- Browser name and version:
- Operating system and version affected: Mac OS Sequioa 15.0
```

**Comment by Alezanello** [comment]
Hi there!

I wasn’t able to replicate the issue, but I have a theory and could use your help in testing it. I suspect the problem might be related to Supabase API calls in the iOS simulator. Could you try adding another API call in your project to see if it’s just the Supabase API calls, or if all API calls are not working on the iOS simulator?

For example, I used this GET API call for testing:<br>[https://jsonplaceholder.typicode.com/posts](https://jsonplaceholder.typicode.com/posts)

Let me know how it goes or if you need further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/71c75fc0-27ed-43b6-93c0-84159c7565ae/b2d67c96-a191-4045-bf02-39101ee594b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MWM3NWZjMC0yN2VkLTQzYjYtOTNjMC04NDE1OWM3NTY1YWUvYjJkNjdjOTYtYTE5MS00MDQ1LWJmMDItMzkxMDFlZTU5NGI3IiwiaWF0IjoxNzI4NDI0MTk2LCJleHAiOjMzMjk4OTg0MTk2fQ.9EoL0bR3To8aOcgp0jLfHHDnBksRemNjQTSizIlP9Ss " alt="image.png" width="1280" height="725" />

**Comment by MamadAsap** [comment]
Hi @Alezanello no, in fact my supabase calls work perfectly, my problem is with calls that are stored on a personal domain. the call stay in pending status and there is no timeout...

**Comment by MamadAsap** [comment]
any news regarding this issue ? 
Here this  errror  in my 

`ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HttpException: Failed to parse header value [undefined]
#0      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:1063:7)
#1      new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:983:5)
#2      new Cookie.fromSetCookieValue (dart:_http:862:20)
#3      _HttpClientResponse.cookies (dart:_http/http_impl.dart:632:28)
#4      _HttpProfileData.startResponse (dart:_http/http_impl.dart:160:39)
#5      new _HttpClientRequest.<anonymous closure> (dart:_http/http_impl.dart:1440:21)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#8      Future._propagateToListeners (dart:async/future_impl.dart:772:9)
#9      Future._completeWithValue (dart:async/future_impl.dart:652:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_responseTimeline@14463476' has not been initialized.
#0      _HttpProfileData._responseTimeline (dart:_http/http_impl.dart)
#1      _HttpProfileData.finishResponse (dart:_http/http_impl.dart:201:5)
#2      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:722:21)
#3      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#7      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
#8      _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
#9      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#10     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#11     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#12     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#13     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#14     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#15     _Uint8ListConversionSink.close (dart:_http/http_impl.dart:895:13)
#16     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#17     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#18     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#19     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#20     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#21     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#22     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#23     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#24     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:53:11)
#25     _FilterSink.close (dart:io/data_transformer.dart:532:11)
#26     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#27     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#28     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#29     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#30     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#31     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#32     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
#33     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
#34     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#37     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#38     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#39     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#40     _StreamController.close (dart:async/stream_controller.dart:640:5)
#41     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1172:18)
#42     _HttpParser._doParse (dart:_http/http_parser.dart:827:11)
#43     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#44     _HttpParser._onData (dart:_http/http_parser.dart:887:5)
#45     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#49     _StreamController._add (dart:async/stream_controller.dart:658:7)
#50     _StreamController.add (dart:async/stream_controller.dart:606:5)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:2449:41)
#52     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#56     _StreamController._add (dart:async/stream_controller.dart:658:7)
#57     _StreamController.add (dart:async/stream_controller.dart:606:5)
#58     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1116:19)
#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#62     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)`

**Comment by MamadAsap** [comment]
In addition when i try a basic GET call like like this one : https://jsonplaceholder.typicode.com/posts

Everything is okay but when i try a GET call from Nuxt i have this pending issue....

**Comment by sanjayelate** [comment]
Having a similar issue where my app doesn't execute action blocks with api/backend actions when testing on either android or iOS simulator.

I could be wrong but these issues all might be related:

https://github.com/FlutterFlow/flutterflow-issues/issues/4000
https://github.com/FlutterFlow/flutterflow-issues/issues/4001
https://github.com/FlutterFlow/flutterflow-issues/issues/4047
https://github.com/FlutterFlow/flutterflow-issues/issues/4048

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
