### ISSUE TITLE
Lib group apicall with variable, can't be used in projects

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4005]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we want to use the library api call (that is inside a group with variable), an message error appear on "confirm" click.

![image](https://github.com/user-attachments/assets/fae4e234-7a59-4a6f-a880-942c719d7fbf)

### Expected Behavior

There should not be error when using an apicall with group variable.

### Steps to Reproduce

1. create a lib
2. add a group with a variable
3. add an apicall to the group.
4. publish the lib
5. create project, import the lib
6. try to use the apicall in home page (with the variable)
7. message error appear on confirm click.

NOTE: if you dont use the variable, the error doesnt appear.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l8j14ot1xMtD1r6JbsBv9SE5KVt/R50njOpBaCgofePtOol3evXsVxduOc/mTXw7J0SmmmAezMryieHDLu05G0+VboB/+pN+SAqXYzmRUZOBEriSOnNCEdpbfxWA5MPY3whdCPViZXwe3UyLfeuiQj7vK7H7IndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/36cba4c2-3b7b-49a2-96a6-dd45a85bb3b5

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT40l8j14ot1xMtD1r6JbsBv9SE5KVt/R50njOpBaCgofePtOol3evXsVxduOc/mTXw7J0SmmmAezMryieHDLu05G0+VboB/+pN+SAqXYzmRUZOBEriSOnNCEdpbfxWA5MPY3whdCPViZXwe3UyLfeuiQj7vK7H7IndISq/LZO4=

Lib bug code:
IT4sl8j15ZV1ofVD+KrAafpr/WEXQz8+bIIWscsZbw4bB4zqPLJ+duDeQBZvXemlTGlhHE6jmng1w+DPjuDhMu5dORyAbLZF+KVXEznhQXq8Rr6hOpGORER6O99gf1Cm4JmJ2iRSIbZoSnw9wGeUfN6XSnPDGZu/Zwh9f6PHaOI=

**Comment by paulperez-dev** [comment]
Hi @nev-21,

I wasn't able to reproduce this issue in the latest version. Could you please update the app and try again? Let me know how it goes!

Thank you!

**Comment by nev-21** [comment]
Hello, yes this issue is fixed. The error doesn't appear when I set the variable.

Thanks @paulperez-dev
