### ISSUE TITLE
Lib apicall crash the app when refreshed on action callback

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4006]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a component that has an action param, is used inside a widget with backendquery, it crashes the app at compile time (test mode). The action callback refresh the api call.

![image](https://github.com/user-attachments/assets/0edf48ec-6aec-489d-b591-4b93f32b7211)

### Expected Behavior

Action callback which has refresh action inside, should not crash the app.

### Steps to Reproduce

1. create a lib, add an apicall A, publish
2. create project, import the lib
3. create a new component X with an "action" parameter
4. put X inside the column in home page
5. add A to the column as backend query
6. inside the X action callback, use "refresh database request" selecting the column as target.
7. execute test mode, you will see the error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cl8j14otPm9td15DuY8JB/ScWHDM+RYIam8JTbwEaJ5PND+x/esnRQFJuZ9OrdghiJFn8nT8y0NqJm9z1Nu0VF0udUaJMyagIWzzvUXGnRr6lDLigeGhuGshPCG7A06aFmB4nXfRaLy1iwUOmOOSATg3dNJ+wOVgRDsqXB5PXvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/b8e8289d-d6a9-4c01-a5f1-352c295b0e6a

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT4Cl8j14otPm9td15DuY8JB/ScWHDM+RYIam8JTbwEaJ5PND+x/esnRQFJuZ9OrdghiJFn8nT8y0NqJm9z1Nu0VF0udUaJMyagIWzzvUXGnRr6lDLigeGhuGshPCG7A06aFmB4nXfRaLy1iwUOmOOSATg3dNJ+wOVgRDsqXB5PXvgfuQ0SLb3kNh1JWeC/v

Lib bug code:
IT48l8j14otPm9td15DuY8JB/SMUJkM7beYZl+pDSUk8J5zKB+wAYvf7P1FWTLy+TH9qPWL8oz407PfqvdmfGO06AyerQKZB1Kt6FBaVQjimMISYDKuNfW1TN+hnIXK+5J6vnSUnGNJedXxn7UyPe+6vTi7AH4CxDG0ZQ+alLdeK2SrDX1iXc2URm05KZDPz

**Comment by nev-21** [comment]
Hello, @Alezanello @rzambroni this issue breaks the apps. It was hard to find the cause.

Please help.

**Comment by paulperez-dev** [comment]
Hi @nev-21,

I wasn't able to reproduce this behavior. Could you please try using the latest version and let us know if the issue still persists?

Thank you

**Comment by nev-21** [comment]
Hi @paulperez-dev, yes I confirm the bug is fixed in the last release.

Thank you
