### ISSUE TITLE
Lib apicall crashes the app when using "Next page index" in ListView backend query

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4012]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using "next page index" (of listView infinite scroll) in a library apicall variable, the app crashes at compile time (test mode).

### Expected Behavior

The app should not crash when we use "next page index" or other related variables in a library apicall.

### Steps to Reproduce

1. create a lib, add an apicall with an integer variable
2. publish the lib
3. create project and import the lib
4. add a listView widget in home page
5. in its backend query add the apicall (and enable infinite scroll)
6. put the "next page index" in the api call variable 
7. set the "generating children from variable"
8. run the app in test mode
9. you will see the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wivHq4c9grs9Y7s/tbcBKhiYUGDo2bYIWmNVHeCs8GqLuPe0UWMzBUBFUOPXhd0FYJGego3wX/Mr6v+PXUfkCAwWubYhy1KlTEA3JVmCQVanRCJS3b2hSP51UGECH3MHQnyYlVbR0V3Aj13GqBe69b3XYK7L7DlgSDua4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/6f9cf0ce-26c6-4836-b7ab-a0987057423a

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT4wivHq4c9grs9Y7s/tbcBKhiYUGDo2bYIWmNVHeCs8GqLuPe0UWMzBUBFUOPXhd0FYJGego3wX/Mr6v+PXUfkCAwWubYhy1KlTEA3JVmCQVanRCJS3b2hSP51UGECH3MHQnyYlVbR0V3Aj13GqBe69b3XYK7L7DlgSDua4XdeK2SrDX1iXc2URm05KZDPz

Lib bug code:
IT40ivHq4c9grs9Y7s/tbcFFoDk5Jk98a687mOtRaCgofePtOol3evWkUFttOP27TwhpPkSmmnEy0N7zitrlCMcCOkmbc6Z9yod2cQqWXlmQa5OBEriSOnNCEdpbfxWA5MPY3whdCPViZXwe3UyLfeuiQj7vK7H7IndISq/LZO4=

**Comment by Alezanello** [comment]
Hello!

Thank you so much for bringing this to our attention. I’ve confirmed the issue and will be forwarding it to the team for a fix. We appreciate your patience and will keep you updated on the progress!
