### ISSUE TITLE
PUSH Notifications not working

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#4014]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have activated the push notifications. i have deployed the cloud functions. Given permissions as stated - allUsers -Cloud function invoker.  Still when i try to get the notification, i am not getting any. The fcm_tokens collection is not getting created as subcollection to users. 

### Expected Behavior

the fcm_tokens should get created when the user installs and logs into the app and a token should be placed.  The notification should be triggered when triggered manually.

### Steps to Reproduce

1. Go to flutterflow.
2. push notifiations in settings of the project
3. Manually trigger notification
4. Enter blah blah
5. Send notification.
🤷 Nothing happens and just says notification sent to 0 devices..

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/LluJdgrt9Y18/LbcBojj4sQmE2TL03pu0bFEggGLbrBIYMaczeYhZBQuLhS2NPKEWInjgy+M70k+OTU/Y6CEydbqE6zZF2EgmUWkW/aoSlO83hR3ZCLJtMJhWm5Luv3yR5BNZvL1462GWbNejKbD3UNOb7Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/2cb7c44a-2651-4e1b-ad89-1e5d16ff0955)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

As, usual, the status will be triage, need more information and then will be closed. There were two tickets that were closed not indicating what is the issue and at least 5 community posts crying for help.  But still creating this ticket knowing nothing happens.

**Comment by task-win** [comment]
![Screenshot 2024-10-09 at 13 57 56](https://github.com/user-attachments/assets/3ea528be-98e7-475b-a596-d18cb468387a)

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you are facing this issue. Have you tried deleting the cloud function, deactivating it in FlutterFlow, and then reactivating it so FlutterFlow can reinsert the Cloud Function?

If this doesn't resolve the issue, it may be very specific to your project. In that case, I recommend contacting support directly, as I haven't been able to replicate this issue in different projects.

You can contact support through the in-app chat or via email at support@flutterflow.io for further assistance.

Best regards,<br>​Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
