### ISSUE TITLE
Storyboard rolls back on any form of screen movement

### ISSUE THREAD

**Issue by helitito** [FlutterFlow/flutterflow-issues#4015]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Any and all adjustments to the Storyboard is undone, and is impossible to adjust for better visualization or organization

### Expected Behavior

it should not refresh

### Steps to Reproduce

1. Open the storyboard
2. Modify anything
3. zoom out or move the page
4. it undoes all changes and refreshes the page

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skvLl8ZdgocNG1qrUd8F7/SIWQ3p+aJI4scp/bxIgGIDzPOw+ZPWlXFpWQuKqTHNYJ0SmmXwBpvDqhuHPVvk4aCyYboc5zqV+VgyWXlmua5OBCLmKSEFTNJpbfEC84aS3qhRSVdtqSU4G2DmyH+usaC/cJYTXImdISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/7ed1abc2-f46d-455f-b6b8-5af76cab3c37

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: web
- Browser name and version:Chrome 129.0.6668.90
- Operating system and version affected: windows 11
```

### Additional Information

I am unable to organize and present my project

**Comment by rzambroni** [comment]
Hi @helitito,

Thank you for bringing this to our attention. I’ve been able to replicate the issue you described, and I’ll escalate it to our engineering team for further investigation. We appreciate your patience while we work on this.

**Comment by helitito** [comment]
Thank you!
