### ISSUE TITLE
Place Picker widget does not have an option to use the county value

### ISSUE THREAD

**Issue by cooldude1010** [FlutterFlow/flutterflow-issues#4018]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The options for the place picker widget output are:

LatLng
Name
Address
City
State
Country
Zip Code

### Expected Behavior

Google API returns more information than what flutterflow gives access to, including county. Here is an example of an api response from the google places api:

`/**/_xdc_._ip5rjb && _xdc_._ip5rjb( {
   "html_attributions" : [],
   "result" : 
   {
      "address_components" : 
      [
         {
            "long_name" : "10551",
            "short_name" : "10551",
            "types" : 
            [
               "street_number"
            ]
         },
         {
            "long_name" : "West Maple Street",
            "short_name" : "W Maple St",
            "types" : 
            [
               "route"
            ]
         },
         {
            "long_name" : "Wichita",
            "short_name" : "Wichita",
            "types" : 
            [
               "locality",
               "political"
            ]
         },
         {
            "long_name" : "Sedgwick County",
            "short_name" : "Sedgwick County",
            "types" : 
            [
               "administrative_area_level_2",
               "political"
            ]
         },
         {
            "long_name" : "Kansas",
            "short_name" : "KS",
            "types" : 
            [
               "administrative_area_level_1",
               "political"
            ]
         },
         {
            "long_name" : "United States",
            "short_name" : "US",
            "types" : 
            [
               "country",
               "political"
            ]
         },
         {
            "long_name" : "67209",
            "short_name" : "67209",
            "types" : 
            [
               "postal_code"
            ]
         }
      ],
      "adr_address" : "\u003cspan class=\"street-address\"\u003e10551 W Maple St\u003c/span\u003e, \u003cspan class=\"locality\"\u003eWichita\u003c/span\u003e, \u003cspan class=\"region\"\u003eKS\u003c/span\u003e \u003cspan class=\"postal-code\"\u003e67209\u003c/span\u003e, \u003cspan class=\"country-name\"\u003eUSA\u003c/span\u003e",
      "formatted_address" : "10551 W Maple St, Wichita, KS 67209, USA",
      "geometry" : 
      {
         "location" : 
         {
            "lat" : 37.678738,
            "lng" : -97.46473399999999
         },
         "viewport" : 
         {
            "northeast" : 
            {
               "lat" : 37.6800888302915,
               "lng" : -97.46326031970848
            },
            "southwest" : 
            {
               "lat" : 37.6773908697085,
               "lng" : -97.4659582802915
            }
         }
      },
      "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png",
      "icon_background_color" : "#7B9EB0",
      "icon_mask_base_uri" : "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
      "name" : "10551 W Maple St",
      "place_id" : "ChIJw1hsB2reuocRyAjwkaEAhx8",
      "plus_code" : 
      {
         "compound_code" : "MGHP+F4 Wichita, KS, USA",
         "global_code" : "8694MGHP+F4"
      },
      "reference" : "ChIJw1hsB2reuocRyAjwkaEAhx8",
      "types" : 
      [
         "street_address"
      ],
      "url" : "https://maps.google.com/?q=10551+W+Maple+St,+Wichita,+KS+67209,+USA&ftid=0x87bade6a076c58c3:0x1f8700a191f008c8",
      "utc_offset" : -300,
      "vicinity" : "Wichita"
   },
   "status" : "OK"
} )`

The administrative_area_level_2 (county) should be available as an option. Many companies in the real estate/title industry rely on County information for rate and fee calculations, so it would be nice to have this as an option. This would also be extremely easy to implement since the data is already there, flutterflow just doesn't make it easy to access this information

### Steps to Reproduce

1. create project
2. add placepicker widget
3. try to select "county" as a widget output option

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z8rq24x2pbwA1s+BasIwoGA5Jno9arsvmOtBaC0sCKL2B+wQXszBSFBWUs+0S39ieFmZ8WQ03M3emvDxKe07PRycG4R8wbl6ZzuVRky6b82XEKjpVm5/AppQFUiA0p+FkxNvKtZsc3gY71yuIt+tHwHbNoDLDWo7B8mHJZKK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/1564347e-bcd2-486a-9bae-2e15992fb96c

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention! However, this issue tracker is specifically for reporting bugs, not feature requests. No worries—I've created an internal ticket for your feature request and added it to the team’s backlog so they are aware of it.

We appreciate your input!
