### ISSUE TITLE
iOS "Allow Paste" prompt bug when copying from clipboard

### ISSUE THREAD

**Issue by stesancri** [FlutterFlow/flutterflow-issues#402]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Paste a text from clipboard into a TextFormField in iOS should work without firing the "Allow Paste" prompt every time

## Current behavior (required)
Every time i paste a text from clipboard into a TextFormField in iOS16 the system asks if I allow the action.
If I agree, the same prompt is fired after another paste action

## To Reproduce (required)
1. Create a TextFormField
2. Run the app on a iOS device running iOS16+
3. Copy a text from another app (e.g. Safari)
4. Paste the text in the TextFormField
5. A prompt should be fired saying "Sample App" would like to paste from "Safari"
6. Click on "Allow Paste"
7. Redo the actions from point n.3 with different text
8. Watch the same prompt firing again

### Bug Report Code (required, generate from Widget Tree)

IT4wkcrl089Pn7xd1aXydfpviiovIjsnbZIVksFuESs8I4jyO5YUSMzBUFFWTL3iTFZDe06GkngKxvfqudn9F/AoOQmaUb5YybpcezuVcDiiV5fWPJa/MS0ffaMKRSz+

## Context (required)
I want my users to be able to paste urls without issues in my app

## Your environment

* Version of FlutterFlow used: v3.0 January 20, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): on physical device and iOS simulator
* Device: iPhone 11
* Operating system and version (desktop or mobile): iOs16

**Comment by wenkaifan0720** [comment]
Hi @stesancri. Is this something specific to iOS 16? I found a bunch of posts related to this matter: https://www.ultfone.com/ios-16/allow-paste-pop-up-ios-16.html#1 https://www.macrumors.com/2022/10/17/ios-16-1-paste-from-other-apps-settings/.

**Comment by bulgariamitko** [comment]
Unfortunately I can't test this I do not have iOS so I will mark it as can't reproduce

**Comment by stesancri** [comment]
> Hi @stesancri. Is this something specific to iOS 16? I found a bunch of posts related to this matter: https://www.ultfone.com/ios-16/allow-paste-pop-up-ios-16.html#1 https://www.macrumors.com/2022/10/17/ios-16-1-paste-from-other-apps-settings/.

I've tested only with iOS 16 so I can't confirm it's not happening on other versions as well.
The bug seems exactly the one described in the article you posted tho.

Thanks

**Comment by wenkaifan0720** [comment]
Hi @stesancri. Right. So if you go to settings for this app and set `Paste From Other Apps` to `Allow`, then the prompt would not show up anymore. 

I'm afraid there's nothing we can do here. It is basically Apple's decision. 😌
