### ISSUE TITLE
App will no longer boot in Run Mode? [Fails after Firebase initialisation]

### ISSUE THREAD

**Issue by nathan2580** [FlutterFlow/flutterflow-issues#4021]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

##Update: Upon checking main.dart order of operations, I'm even more confident its external/FF related as the custom actions execute AFTER the initFirebase call and I added a print statement on the first line of my custom action and as per the below screenshot it doesn't print, indicating the error is coming from initFirebase

Not sure if what I'm reporting is the same as #4019 but essentially I went to work on my app this evening, I added a custom action to enable web based offline persistence for Firebase and added in this in main.dart. It booted just fine and everything was working as expected.

I then made a change to my custom widget (compiled successfully) but every subsequent run mode didn't boot/load the app and upon inspect of the console log, I keep getting the same error code which appears after some firebase initalisations:

main.dart.js:3607  Uncaught Error: TypeError: Instance of 'minified:ain': type 'minified:ain' is not a subtype of type 'minified:J'
    at Object.l (main.dart.js:3607:19)
    at Object.cJ0 (main.dart.js:4362:18)
    at ov.d5E [as a] (main.dart.js:4357:3)
    at baz.b7 (main.dart.js:77331:14)
    at Object.cVo (main.dart.js:8704:44)
    at main.dart.js:219035:56
    at a.<computed> [as O] (main.dart.js:21:35)
    at main.dart.js:46582:5
    at coN.a (main.dart.js:5006:63)
    at coN.$2 (main.dart.js:62573:14)

I wasn't sure if it was related to my firebase custom action so I fully removed this (and it from main.dart) but it still gives the same error. I then restored to a working FF version from last Sunday and tried run mode, but again, no boot and the same error as above.

As such, I can only think it is something outside of my own control as even restoring to a working version (on a new browser with no cache etc) yields me exactly the same error.

I really hope this is the case as currently panicking that my project is permenately broken. 

### Expected Behavior

I expect the app to boot/load as all previous versions have. I believe the issue to be external/FF related as the error message did not appear on my last Sunday version and so the code has not changed to give there a reason to produce that type error.

### Steps to Reproduce

1) Hit 'run' to load a run-mode version on browser
2) Wait, screen will stay blank after initial compiling and inspecting the console shows the error message above, every single time
3) Presume linked to firebase so, would have to be imported cloud firestore / firebase packages etc

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l+fl4ot2xNtF+KX6YMEwvDwsQls7RI0Nl8Bhd0o8J5zKB+wAYvf7P1FWTLy8YAliJWKaq3wy/PfqiYSWFfpfJSiqfb5kws9UEDvLRkmlM5DUDcy/fW1RO/hYFWKO0Z+NpyZ5AO9scnAX7WGuA+uvUnTdNufQDWwzJPmlLdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Console Print](https://github.com/user-attachments/assets/1434a1af-8f2c-4a59-8f96-01906fdbb222)

### Environment

```markdown
- FlutterFlow version:  FlutterFlow v5.0.0+ released October 9, 2024
Flutter version is 3.22.2
- Platform: Web (creating for IOS/Android)
- Browser name and version: Chrome 129.0.6668.90
- Operating system and version affected: Windows 10
```

### Additional Information

Impacting me massively as cannot run any versions of my App so has stalled my progress and paused until this issue is fixed.

**Comment by Alezanello** [comment]
Thank you for reporting this issue! We are currently tracking it in the following link: [GitHub Issue #4019](https://github.com/FlutterFlow/flutterflow-issues/issues/4019).

To ensure we can focus all efforts on resolving it, I’ll mark this as a duplicate and close this ticket. Please feel free to follow the progress on the linked issue.

Thanks again for your understanding and support!
