### ISSUE TITLE
Flashing grey screen and slow performance after latest FlutterFlow update

### ISSUE THREAD

**Issue by dario-1996** [FlutterFlow/flutterflow-issues#4024]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Flashing grey screen: When I make changes to the UI, the screen turns grey, covering only the FlutterFlow interface (it doesn't affect browser tabs or other parts of the screen). This issue temporarily goes away when I reload the page, but reappears when I make further edits.

2. Slow editing performance: Changes I make to the UI are applied very slowly. The response time when editing is considerably longer than before the update, which impacts workflow.

### Expected Behavior

1. Fluid UI: When making changes to the FlutterFlow UI, I expect the interface to update quickly and smoothly without rendering issues, without a gray screen appearing. The editing experience should be instant and seamless.

2. Quick responses to changes: When modifying components or widgets, there should be an immediate response in the preview. Editing and layout changes should be reflected in an agile manner, allowing for an efficient workflow.

### Steps to Reproduce

1. Open the project in FlutterFlow: Log in to FlutterFlow and open the project where the issues are occurring.

2. Access the action editor: Navigate to the actions section of your project. This is where you configure your app's interactions and logic.

3. Add or configure an action: Try adding a new action or configuring an existing one, specifically around backend calls or actions that require an internet connection.

4. Observe the screen: When you want to make changes to the action configuration, you notice that the screen suddenly turns completely gray, indicating that there is a problem with the rendering of the interface.

5. Test UI changes: After experiencing the issue in the action editor, try making changes to any part of the UI (such as adding, removing, or modifying widgets).

6. Evaluate performance: You notice that the changes you make are applied extremely slowly. Sometimes, changes may even roll back or not be reflected at all, affecting your workflow.

7. Reload the page: When you reload the page, you may notice that the grey screen issue temporarily goes away, but it may reappear as you make further edits.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oj8nc05NPmN9G15D2b8BKpyQUHGV7aOcvjMpBZywgfZzzBLN/fPfQP1duXu6oTEFmPE6cp14f0f+NkoafGMEBHymZQJx4/7tcUArJTmOgMpuTF7uKf0Z5HeRWfxXF08PYhiJAWfJuc0YG2V6YBdmuZz7YHpjMNVQ8Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/935f538f-55b9-4c02-9a20-3f7b2ca38c00)
![image](https://github.com/user-attachments/assets/4bc0429c-f44d-4680-8d40-f1d09bb94323)

### Environment

```markdown
- FlutterFlow version: v5.0.0+ released October 9, 2024
- Platform: Web
- Browser name and version: Chrome 129.0.6668.90 (Build oficial) (64 bits)
- Operating system and version affected: 64-bit operating system, x64-based processor
```

**Comment by holcz** [comment]
Same here. Can you please investigate?

**Comment by Alezanello** [comment]
Hello,<br><br>We sent a fix yesterday. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by holcz** [comment]
Hi @Alezanello ,

thanks for the fix.
For our project, the issue seems to be fixed.
I would say the editing performance is bit more snappy than before the latest major update.

**Comment by GoCloudToday** [comment]
@Alezanello do you have any ETA when this update will be propagated to the Windows version? The web version seems to work much better now, but the Windows one still has the same problems.

**Comment by holcz** [comment]
@Alezanello Unfortunately the issue is back / not fully resolved on web either.
The performance is better, but we started to experience the grey screen more frequently.

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
