### ISSUE TITLE
"Upload media to Local File" action only resizes image in portrait mode

### ISSUE THREAD

**Issue by SamVdvd** [FlutterFlow/flutterflow-issues#403]
## Expected behavior (required)
resize of picture happens in portrait and landscape mode

## Current behavior (required)
the picture is only resized when taken in portrait mode. If it is taken in landscape the original size is preserved

## To Reproduce (required)
add "upload media to local file" action
set "max width" to eg "2000 pixels"
take a picture in portrait and landscape mode and check the size of the images

the portrait-picture will be resized, the landscape-picture not.

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: chrome 109.0.5414.75
* Operating system and version (desktop or mobile): W11

**Comment by hariprasadms** [comment]
Hi @SamVdvd, Thanks for adding this issue details. I have tested this issue and I can see that it is working fine for both portrait and landscape mode(On run and mobile browser mode). 

Can you confirm,  are you seeing this issue in real devices or web run mode?

I have tested it on both Web run and mobile browser mode for now ( Both the places I can see that image upload and resizing according to settings, working fine ). but not tested on real device yet.

**Comment by hariprasadms** [comment]
Hi, I have tested it on mobile device - iOS. It works fine. I can see that uploaded images re resized as per the size given in the properties section.

**Comment by SamVdvd** [comment]
You’re right, I had multiple “upload media to local file” actions in my project, resize wasn’t configured on one of them.
By chance I had taken all of the landscape pictures with this particular action.
I’m embarrassed, my apologies…

Van: Hari ***@***.***>
Verzonden: woensdag 25 januari 2023 12:10
Aan: FlutterFlow/flutterflow-issues ***@***.***>
CC: Sam Vandevelde ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [FlutterFlow/flutterflow-issues] "Upload media to Local File" action only resizes image in portrait mode (Issue #403)

EXTERNE MAIL: Open enkel attachments of hyperlinks indien u de afzender vertrouwt.


Hi, I have tested it on mobile device - iOS. It works fine. I can see that uploaded images re resized as per the size given in the properties section.

**Comment by hariprasadms** [comment]
No worries. Good to see it is working for you.
