### ISSUE TITLE
Slider won't update its position dynamically.

### ISSUE THREAD

**Issue by leoleo-s** [FlutterFlow/flutterflow-issues#4033]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I’m building an audio player using native flutterflow widgets and just_audio only for actions (play, pause, stop, etc). 

I want a slider to act as a progress bar of the audio, as I can position it manually and trigger an action on change end.

On the initial value of the slider, I bound an app state called currentAudioPosition. On the maximum property, I bound another appstate called audioDuration. Both are doubles.

The expected behavior would be: When the appstate currentAudioPosition changes, the actual position of the slider would change aswell, but it's not happening. 

Just for debug purposes, I removed all the custom actions (there's no custom code on the app), and added buttons to just update the appstate value and see if it moves, and it doesn't. You can clearly see values changing on the debug panel, but the slider won't move.

The update app state actions is rebuilding the component (the audio player is a component).

### Expected Behavior

The slider should change its position based on the initial value.

### Steps to Reproduce

Create a page, put a slider on it, bind an state to the initial value, change the state value. The slider won't move.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klsn134VPxOFG+KnxbcZFvDsXC0A4TLJEtu1uTRMjF5D4EJYfds/7cldvTtSzaHxiHmGZhk0zpd7vj/PLE8A5C06Cf4h5zJN2YRPPbE2nRLWaEbrgPEQnRMpVI2ac0Z2vsCUlXfdqR3Ng1DqmNunIUT6Cf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/4f2aeb68-421c-4805-b77e-2918ccc14d31

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released October 9, 2024
- Platform: MacOS 13.7
- Browser name and version: Chrome Version 129.0.6668.91
- Operating system and version affected: MacOS 13.7
```

### Additional Information

I cannot build the player if the slider won't move, as it's crucial on an audio player.

**Comment by Alezanello** [comment]
Hello!

In Flutter, the Slider widget is static and only updates when the user interacts with it. It’s not designed to be dynamic, like the behavior you're expecting from an audio player. What you're describing sounds more like a Progress Bar with interaction, which goes beyond the current functionality of FlutterFlow.

However, a great package that you can easily integrate as a custom widget is [audio_video_progress_bar](https://pub.dev/packages/audio_video_progress_bar). This might be just what you need!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
