### ISSUE TITLE
custom icons suddenly disappeared

### ISSUE THREAD

**Issue by ak2003** [FlutterFlow/flutterflow-issues#4034]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

two days ago I added a custom icon, today we got crash flutterflow, and after i open again, the customer icon is gone.
and get error like 
`Widget references custom icon family that no longer exists. Please re-select it.`customer

### Expected Behavior

custom icon still there, because we don't remove

### Steps to Reproduce

this happen when I close branch after that FF crash suddenly and needs to reopen. After reopen, I get some error about icon family that no longer exists.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ShcqAsJVNpbxE7qXyc8JFiiURMjs4aJJEl9V6EUsgF4PkP6QPXOmmSFRuQtOmTFc2emGWij0dwN3IktzIN8JdZBaYY4tx+JYJZg3LeHijVZCpOqirdXFCBtpKCGKA4J6knh4nHMB1LFYN2l6UIOvJaBHXGIDoOnozB/L8DJj5nXPuQ0SLb3kNh1JWeC/v

### Visual documentation

can't be reproduced because suddenly FF crashes and needs to reopen.

### Environment

```markdown
- FlutterFlow version: 5.0.5
- Platform: desktop macos
- Browser name and version: 
- Operating system and version affected: macos sonoma Apple M1 pro
```

**Comment by ALaiFF** [comment]
Face the same issue so far in 50% of my projects. The only solution I found so fat was to reinstall custom icons .ttf files that was missed by no reason due to the latest (5.0.5) update

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. I wasn't able to replicate it using a new blank project, which suggests it might be specific to your project after the recent update. In this case, I highly recommend reaching out to support via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). This issue tracker is primarily for bugs that can be reproduced in new blank projects.

Thank you for your understanding!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
