### ISSUE TITLE
Push Notifications Suddenly Stopped Working – No FCM Tokens Generated

### ISSUE THREAD

**Issue by vegas331993** [FlutterFlow/flutterflow-issues#4036]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi everyone, I’m having an issue with push notifications in two apps. Up until last week, everything was working fine, and I haven’t made any changes related to notifications—I’ve just continued working on the app development. The other day, I decided to test the notifications again, and I noticed that not only am I no longer receiving them, but the FCM tokens aren’t being generated anymore either.
I’ve spent the last 6 days trying to fix this, following every guide and piece of advice I could find, but still no luck. 
Also, I should mention that the two apps were created under two different accounts, and now neither of them generates FCM tokens. I’ve even considered the possibility of an issue related to the Blaze Plan, but everything seems fine on that front.

**checking the logfile of "addFcmToken" I noticed this following error:**

error 400:

![errore2](https://github.com/user-attachments/assets/307cffb1-c9ff-4491-8832-63fdb86cbd5e)

**What have you tried so far?**

- Regenerated the config files.
- Validated the firebase users 
- Re-deployed Firestore rules.
- Deleted and re-deployed push notifications.
- Checked the Cloud Functions region (europe-west6) to ensure they match across the board.
- Reviewed the permission firebase@flutterflow.io has access, and that “cloud functions invoker” permissions are set to “all users.”

I even duplicated the project and recreated the Firestore database from scratch.

Still, nothing works, and I can’t figure out what’s causing the issue.

### Expected Behavior

Generate a FCM token for new users

### Steps to Reproduce

see above problem description.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NOT HAVE

### Visual documentation

![errore3](https://github.com/user-attachments/assets/ec365268-0a6e-4e6b-917d-6f419d2ac4e2)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: android
- Browser name and version: chrome
- Operating system and version affected: windows 10
- Device version affected: Android 14
```

### Additional Information

I would like to point out that it worked before, in fact some accounts already registered before a few weeks ago already have the token generated.

I'm testing push notification on a real device.

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you are facing this issue. Have you tried deleting the cloud function, deactivating it in FlutterFlow, and then reactivating it so FlutterFlow can reinsert the Cloud Function?

If this doesn't resolve the issue, it may be very specific to your project. In that case, I recommend contacting support directly, as I haven't been able to replicate this issue in different projects.

You can contact support through the in-app chat or via email at support@flutterflow.io for further assistance.

Best regards,<br>​​Azanello

**Comment by vegas331993** [comment]
Hi Alezanello. 
How is it possible that in two different Firebase accounts and in two different projects they stopped creating the token? Today I'll try to see if it's a problem with the European region. I mean, it has always worked on every project I've done. I've already tried everything, as I mentioned, I even duplicated the project and opened a new database from scratch. Nonetheless, it doesn't work. I've already contacted the FlutterFlow team and I'm waiting for their response.

**Comment by vegas331993** [comment]
I don't know how it's possible, after 7 days of dismantling the project piece by piece, trying to figure out the cause, and recreating the database a couple of times from scratch, this morning it magically started working again on both applications I developed. At this point, it's clear that there were issues not caused by me, since until yesterday I was still getting errors in the logs. It would have been helpful to know that earlier, instead of having to tear everything apart, but oh well, the important thing is that it's working now. Next time, I won't touch anything and just wait for it to fix itself.

A useful tip for anyone facing the same issues: **follow all the advice you can find online, and if you've done everything suggested, just wait it out. Sometimes things resolve on their own.**
