### ISSUE TITLE
Make expandable on image widget throws compile error

### ISSUE THREAD

**Issue by iainmcfall** [FlutterFlow/flutterflow-issues#4037]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have enabled Make Expandable on an Image widget. When I try to compile (hot reload in local test) the compile fails with the following error:

Performing hot reload...                                        
Error: Couldn't resolve the package 'photo_view' in 'package:photo_view/photo_view.dart'.
lib/flutter_flow/flutter_flow_expanded_image_view.dart:2:8: Error: Not found: 'package:photo_view/photo_view.dart'
import 'package:photo_view/photo_view.dart';
       ^
lib/flutter_flow/flutter_flow_expanded_image_view.dart:28:22: Error: The getter 'PhotoView' isn't defined for the class 'FlutterFlowExpandedImageView'.
 - 'FlutterFlowExpandedImageView' is from 'package:epicor_a_r_m/flutter_flow/flutter_flow_expanded_image_view.dart' ('lib/flutter_flow/flutter_flow_expanded_image_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'PhotoView'.
              child: PhotoView.customChild(
                     ^^^^^^^^^
lib/flutter_flow/flutter_flow_expanded_image_view.dart:33:23: Error: The method 'PhotoViewHeroAttributes' isn't defined for the class 'FlutterFlowExpandedImageView'.
 - 'FlutterFlowExpandedImageView' is from 'package:epicor_a_r_m/flutter_flow/flutter_flow_expanded_image_view.dart' ('lib/flutter_flow/flutter_flow_expanded_image_view.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PhotoViewHeroAttributes'.
                    ? PhotoViewHeroAttributes(tag: tag!)
                      ^^^^^^^^^^^^^^^^^^^^^^^
Try again after fixing the above error(s).

### Expected Behavior

I expect it to compile with no errors

### Steps to Reproduce

1. Add an image widget to any page
2. Enable Make Expandable
3. Run Local Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ok8j15ZVOxcRE7a6JYO9V/CQWJVg9U50n1MpOFDIbGJzwBIh/Z8zsYkhpUu2kYGlhHGaghl0dw9LXvuDtJPI5F02bbL5S+LoBUQrjVXq8SqbWPM2oTnN6M91nCmqn5razogp7BNZpck4S2GCIJtm9VjHAGZu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-10-11 at 11 12 37 PM](https://github.com/user-attachments/assets/35034409-9cde-4eee-b73b-a2398b652303)

### Environment

```markdown
- FlutterFlow version: Version 5.0.5 (5.0.5)
- Platform: MacOS Desktop
- Browser name and version: n/a
- Operating system and version affected: 14.6.1 (23G93)
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue using a new blank project with the following steps:

1. Create a new project.
2. Add an image.
3. Enable "Make expandable."
4. Run in Test Mode.

You can clone and test the public project I’ve created here: [Project Link](https://app.flutterflow.io/project/qa-2265-1500hu). Feel free to modify it if I’m missing anything.<br><br>Also I was able to download and compile your project without any issue, if you still facing this issue please contact support via in-app chat or support@flutterflow.io !

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by iainmcfall** [comment]
Please remove the image of my app's login page from the comments,

**Comment by iainmcfall** [comment]
Also please refer to the original ticket details. This occurs when trying to compile and run using Local Run on a physical device. Not in Test Mode.
