### ISSUE TITLE
Error in custom functions when using "Dev Environments" with Supabase

### ISSUE THREAD

**Issue by esiemann** [FlutterFlow/flutterflow-issues#4038]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Errors that do not exist are displayed when using "Dev Environments" with Supabase. The application cannot be compiled because of the error that the FFDevEnvironmentValues ​​are missing in the function validation.

### Expected Behavior

Create a supabase configuration for each environment.

### Steps to Reproduce

1. Create any custom function, example:
String? newCustomFunction(String? text) {
  /// MODIFY CODE ONLY BELOW THIS LINE
  return text;
  /// MODIFY CODE ONLY ABOVE THIS LINE
}
2. Create a "Dev Environment"  with 2 values "supabaseUrl" and "supabaseAnonKey"
3. Use both environment values ​​in supabase settings
4. Click on "Get Schema"(important: if you do not load the schema the error does not occur) 
5. Errors will now be shown on a random custom function

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89godtE17XqLO9VliMRNnI+aoc0sNobbxAjIoDoPJkUaePObRJtOMOndFFlKEWJhk4e+eCPuODlJfIDHAeWG9Q4yM9LWBfvRkO/aoS6CbiCXXBfEZ1XFVSy0aWnpCV4WcVYR1onwzimG+6ucDXbGJ/7Zwh9f6PHaOI=

### Visual documentation

1. Create any custom function,example:
String? newCustomFunction(String? text) {
  /// MODIFY CODE ONLY BELOW THIS LINE
  return text;
  /// MODIFY CODE ONLY ABOVE THIS LINE
}
![screenshot18](https://github.com/user-attachments/assets/daf2a8f2-bdb3-49f2-9aab-273ce2b61c10)

2. Create a "Dev Environment"  with 2 values "supabaseUrl" and "supabaseAnonKey"
![screenshot12](https://github.com/user-attachments/assets/05af9741-73c8-48d9-a7e2-7507b69d110b)

3. Use both environment values ​​in supabase settings
![screenshot13](https://github.com/user-attachments/assets/2df1203d-2a5e-435d-a628-9788668c4b7c)

4. Click on "Get Schema"(important: if you do not load the schema the error does not occur) 
![screenshot14](https://github.com/user-attachments/assets/1728bf45-cfd5-4741-9ddb-e3d10920dfb3)

5. Errors will now be shown on a random custom function
![screenshot19](https://github.com/user-attachments/assets/c1dd9ebb-962e-4e04-a3fe-e7eef3e6edf5)

### Environment

```markdown
- FlutterFlow version: v5.0.0+ released October 9, 2024
- Platform: Ubuntu 24.04
- Browser name and version: Chrome 129.0.6668.100 64 bits
- Operating system and version affected: Any
```

**Comment by Alezanello** [comment]
Thank you so much for the detailed explanation! <br><br>I was able to replicate the issue easily and will now forward it to the engineering team for further investigation and a fix.

**Comment by gianniginom** [comment]
Hi, same error here !

**Comment by gianniginom** [comment]
Hello, I am currently stuck, as I can no longer publish versions or run tests. How can I resolve this situation? Thank you.

**Comment by mravani2** [comment]
Guys, this was set as completed… I re-do all the proccess I had rolled back a few days ago but the error persists :( @mmearly

**Comment by mmearly** [comment]
Hey everyone -- very sorry about this issue and the communication around it. Our issue tracking system marks issues as closed when fixes are written and approved, but this is almost always well before a release happens that actually includes the fix. This makes the "X closed this as completed" messages very misleading, I will talk to the team to see what we can do about changing the timing of these messages to be more useful.

In this particular case, a solution was written that appeared to resolve the issue when testing it with our internal tools, but it has now come to our attention that it will not work when deployed to all projects. We are currently investigating a new fix. Thank you for your patience.

**Comment by mmearly** [comment]
Updated fix is ready, will close once merged in

**Comment by mravani2** [comment]
Hey @mmearly is there any ETC to push this fix to production?

**Comment by mmearly** [comment]
The fix has been merged in now! 🥳 The error should go away when you recompile your custom code.
