### ISSUE TITLE
dependOnInheritedWidgetOfExactType Issue with a component

### ISSUE THREAD

**Issue by launchInsighter** [FlutterFlow/flutterflow-issues#4039]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I ran my application in test mode. When I navigate to a page with a component, instead of showing the component, I get the error message below. I published my application to the web, and it worked fine in production. Also, I restored a working older version of my software, and it still showed the error, which led me to believe that it's related to your debugger.  

I searched online for related FlutterFlow issues reported by other people. I found a [similar issue](https://community.flutterflow.io/ask-the-community/post/dependoninheritedwidgetofexacttype-localizationsscope-error-kDVvDUg1mbzwX8P), but it was no resolution.

This is now critical for me because I couldn't debug at all and I am launching my product next week.  Please help.

  `dependOnInheritedWidgetOfExactType<DebugFlutterFlowModelContext>() or dependOnInheritedElement() was called before _RoleplayDialogueWidgetState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.
    at Object.throw_ [as throw] (errors.dart:296:3)
    at framework.dart:5720:9
    at framework.StatefulElement.new.dependOnInheritedElement (framework.dart:5762:14)
    at framework.StatefulElement.new.dependOnInheritedWidgetOfExactType (framework.dart:4779:14)
    at DebugFlutterFlowModelContext.maybeOf (debug_util.dart:34:19)
    at get rootModel (flutter_flow_model.dart:93:38)
    at get isRouteVisible (flutter_flow_model.dart:98:40)
    at Object.debugLogWidgetClass (debug_util.dart:248:23)
    at set isRecording (roleplay_dialogue_model.dart:87:5)
    at roleplay_dialogue_widget._RoleplayDialogueWidgetState.new.<anonymous> (roleplay_dialogue_widget.dart:64:7)
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:127:5)
    at roleplay_dialogue_widget.dart:61:53
    at [_invokeFrameCallback] (binding.dart:1392:7)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (binding.dart:1326:11)
    at [_handleDrawFrame] (binding.dart:1171:5)
    at Object.invoke (platform_dispatcher.dart:1404:5)
    at _engine.EnginePlatformDispatcher.new.invokeOnDrawFrame (platform_dispatcher.dart:307:5)
    at initialization.dart:187:36
    at Object._checkAndCall (operations.dart:426:37)
    at Object.dcall (operations.dart:431:39)
    at ret (js_allow_interop_patch.dart:17:11)`

### Expected Behavior

The Test Mode component should appear as if it is in production.

### Steps to Reproduce

1. log in (use gmail to avoid sign up.  but you can also sign up)
2. go through "Get Started" and select a skill like Negotiation.
3. go to home page (Home), click on the Negotiation tile.
4. generate an idea.
5. save the idea.
6. run a simulation and you will see the error message.
For a tutorial on how to run a simulation, you can check out [here](https://app.storylane.io/share/jgrid9wxurqt)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cz8jfz49On7xE7q6Jc/lV+WAWHEw8RYEw1+xERkoYN5PND+x/esnRQFJuZ9OrdghiI1n8hT8K0PCJm9z1VMc5ByysG7Z9+KtidwLjUn25RaqDDM6CfHdUGshMGlzA1KangQknWdViSXwc2nGuC+iUcBDrN5TXIEUnMvyHEL7XrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

Screen with error in test mode.
<img width="1579" alt="Screenshot 2024-10-11 at 2 38 02 PM" src="https://github.com/user-attachments/assets/9df43669-e977-46ea-97b5-935b3b1ed08f">

Same screen in production.

<img width="1676" alt="Screenshot 2024-10-11 at 2 38 22 PM" src="https://github.com/user-attachments/assets/f1105d24-e1bd-4698-9c28-f77a35f7747b">

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: Web
- Browser name and version:  Chrome
- Operating system and version affected: Sonoma 14.4.1
```

**Comment by MartinLockheart** [comment]
Came here to see if this was reported yet. We really need this one fixed as well.

Edit For Additional Context: This seems to be related to having switches inside a component (and that appears to be the same with @launchInsighter as well).

**Comment by corsaro0** [comment]
Same problem here

**Comment by Virtualizei** [comment]
Same problem here too

**Comment by Alezanello** [comment]
Hello everyone!

I’m about to start testing the issue, and it would be really helpful if you could share your bug report codes with me.

This will greatly assist in my investigation and allow me to share the details with the engineering team.

Thank you!

**Comment by cadufreeela** [comment]
Same here, luckily my app is on the closed test track and haven't pushed this version there. Please fix asap

**Comment by launchInsighter** [comment]
> Hello everyone!
> 
> I’m about to start testing the issue, and it would be really helpful if you could share your bug report codes with me.
> 
> This will greatly assist in my investigation and allow me to share the details with the engineering team.
> 
> Thank you!

I included the error in the original post.  Let me know if you need anything else from me.

**Comment by juanpenuelasPalletways** [comment]
![image](https://github.com/user-attachments/assets/4c8a6350-0f76-41e3-90a9-61f9aa1bb6e4)

**Comment by Virtualizei** [comment]
Closed without a solution?

**Comment by Alezanello** [comment]
Hello everyone!

The engineering team has closed this issue because it’s linked to an internal ticket, which is considered the main one. The fix is scheduled to be delivered in the next production release.

Thank you for your patience!

**Comment by juanpenuelasPalletways** [comment]
Could you please confirm the scheduled date for the next production release?

**Comment by Bolt8743** [comment]
As already asked, please confirm the next production release date. 

This is a significant issue for my project which will require a complete rework as I used the methodology of create once, use often with using components and my components have switches. Having to switch to a different widget type, waiting for resolution, or rebuilding without a component removes benefit of continued use of the product.

**Comment by MartinLockheart** [comment]
From what I can tell, the issue isn't on live if you publish it. Only in
test mode/run mode.

**Comment by Bolt8743** [comment]
@MartinLockheart Thank you for this information. However, this isn't an option as the app is for mobile devices only and uses SQLite.

**Comment by MartinLockheart** [comment]
For testing purposes, as a temporary workaround, perhaps you could publish
to web and use it as PWA?

**Comment by Bolt8743** [comment]
@MartinLockheart 
I have already made adjustments by changing the switches to checkboxes and updating the logic that surrnded the given widgets. However, this is also concerning as I feel that it is likely that I will need to do this again after another update breaks the checkbox in a component.

There seems to be a quality issue with releases and it is making me lean towards moving away from FlutterFlow. I have lost 3+ days from recent updates breaking functionality that appears to me would be basic checks for a no code/low code platform with the primary appeal being aimed at non-programmers. But that decision is still a pending one.

**Comment by MartinLockheart** [comment]
I've been losing a lot of time as well, so I get that.

**Comment by dustinkerstein** [comment]
I'm still able to replicate a similar issue. Has anyone else been able to confirm this has been fixed? Any updates would be appreciated. Thanks!

**Comment by MartinLockheart** [comment]
I actually haven't run into this issue in quite some time! You might need
to open a new ticket if something similar is happening, because it's
probably new.

**Comment by dustinkerstein** [comment]
Thanks @MartinLockheart - I created a new issue https://github.com/FlutterFlow/flutterflow-issues/issues/5010
