### ISSUE TITLE
Creating a document and then updating it via the action reference in the *same* action stopped working.

### ISSUE THREAD

**Issue by kskirilov** [FlutterFlow/flutterflow-issues#404]
As per title, creating a document and then updating it via the action reference stopped working.

Recreation is self-explanatory.

**Comment by yoheisoito** [comment]
Hi @kskirilov,

Thanks for raising the issue.
I was able to create a document on a collection, then use that reference to update a field as my subsequent action.
Please see the pasted screenshot per below.

Please reopen the issue if you are not able to achieve this on a blank project, or I am missing your point.

Thanks!





<img width="1160" alt="Screen Shot 2023-01-29 at 10 31 49" src="https://user-images.githubusercontent.com/115172813/215299105-be5195aa-5316-4e44-a56f-959d870fbe0a.png">

**Comment by kskirilov** [comment]
Hey @yoheisoito , I created a blank project and the following action fails
<img width="1080" alt="Screen Shot 2023-02-05 at 9 34 20 PM" src="https://user-images.githubusercontent.com/45692073/216847364-1ca45cc0-fe84-4f90-b2e3-61b4c506cd1e.png">
<img width="1048" alt="Screen Shot 2023-02-05 at 9 35 11 PM" src="https://user-images.githubusercontent.com/45692073/216847401-0ead3500-31f4-4793-aa2b-afa75e09fcfd.png">

I see no reason why it should be failing and used to work before, so it's pretty clear it's an FF bug since it happens exactly the same way in 2 projects for me. I really hope the internal team at FlutterFlow is on code red for all the issues that have creeped up in the past weeks because it's causing a lot of pain. I know it happens, but I really hope it's being dealt with internally as the first priority.

**Comment by kskirilov** [comment]
Here is more detail on my issue
I create a space (and an action output)
I create a channel (and an action output)

I try to update the space (via the action output), setting it's defaultChannelRef to the channel (via the action output)

Maybe it's something to do with updating an action output with another action output? Not sure, but this anyhow used to work before.

**Comment by wenkaifan0720** [comment]
Hi @kskirilov. Could share with me the bug report code?

**Comment by kskirilov** [comment]
Hey, here it is
ITFXksn1z49Pm9hE15D1LMZGgmIwGUwbUOc7j9VEGAsjCePnP7QqduClYk5ocuqHTW46MVb8jTgD/tryud+eD8I5BzCAc6ZhwapLH1yjEA8=

Thank you

**Comment by wenkaifan0720** [comment]
Could you share with me the test project you created? It should be easier to test in there.

**Comment by kskirilov** [comment]
Hey @wenkaifan0720 

<img width="996" alt="Screen Shot 2023-02-06 at 6 52 01 PM" src="https://user-images.githubusercontent.com/45692073/217059502-3dba9b71-32e6-4de8-9af1-bba34615dc86.png">

Another strange use case. I create a new text message and the rest of the actions after that won't execute when it comes to updating documents. 

<img width="1014" alt="Screen Shot 2023-02-06 at 6 54 00 PM" src="https://user-images.githubusercontent.com/45692073/217059857-e4f8ffab-8a83-4fdb-a7d2-dc205c1628f2.png">


In this case I'm choosing the document to be updated from a local state, if that is the cause.


Can we jump on a 15-minute call regarding those issues? It's been 3 weeks since I'm trying to solve those issues here and with support and it's been extremely painful given that I'm fully depdendent on the FF team at this point and I'm worried things aren't being resolved fast enough :(
 My email is krasimirkirilov.b@gmail.com - it would really mean a ton to help resolve this sooner.

**Comment by wenkaifan0720** [comment]
Sure. What's your time zone? I am currently in GMT+8.

**Comment by kskirilov** [comment]
Thank you. I'm in London (GMT). Typically available 8AM to 11PM, which would be after 4PM your time. Would that work? Any day is fine.

**Comment by kskirilov** [comment]
@wenkaifan0720 if you have any time until the end of today, that would work too.

**Comment by wenkaifan0720** [comment]
I've scheduled a meeting. Let me know if the time works for you.

**Comment by kskirilov** [comment]
Hey @wenkaifan0720 , thank you. I just accepted the invite and the time works.
