### ISSUE TITLE
Suddenly unable to log in, register, or query data.

### ISSUE THREAD

**Issue by xiaoyaoyun** [FlutterFlow/flutterflow-issues#4047]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My application has been working fine for a long time with registration and data retrieval, but now I am unable to log in, register, or retrieve data. The login action doesn't proceed to the next step, and I haven't made any related changes. All necessary configurations, such as adding fingerprint authentication and setting up Firestore, were completed earlier, but now the issue has arisen.
I encountered this issue while testing the local run on an Android physical device. It's not clear yet whether other platforms have the same problem.
When I reopen the app, I can see the account information, but data related to Firestore cannot be retrieved.
![5371728782771_ pic](https://github.com/user-attachments/assets/a7406561-6d60-430d-81da-d6a3ed950931)

### Expected Behavior

User login, registration, and data retrieval should all function normally. However, I am currently unable to log in, register, or retrieve data.

### Steps to Reproduce

I haven't changed any settings here, but now there's an issue.
<img width="1264" alt="截屏2024-10-13 09 28 28" src="https://github.com/user-attachments/assets/ae3276ef-1156-4585-9ccf-5b2d87a2bc33">

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWsct/cxQcB4j4E4oiduClXxJWZMCzaHxYGVa0pDgy/+D3ktr1V+0EaCmYfIBizKVUERPPbGCtb5StDKu8ZUZfEfhYGB26yLSZhRRCGPFfLS0t2HGQJNivVT6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1264" alt="截屏2024-10-13 09 28 28" src="https://github.com/user-attachments/assets/ae3276ef-1156-4585-9ccf-5b2d87a2bc33">

### Environment

```markdown
- FlutterFlow version: v5.0.5 or v5.0.6
- Platform: macOs
- Browser name and version: chrome or flutterflow desktop
- Operating system and version affected: macOs ventura 13.5
```

**Comment by xiaoyaoyun** [comment]
IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWscsZa0kdB4joPLJ/P+P7N1VCTe2/SkNhHE7/oGYHzNbGuNjpLPU6BEycGLZS1LhIFxfzVXq8Ra6LPrjtRnMlP9xmfG6a0cOSniVSOshaLWxn7DiIF/O9dHLdCZ+/Zwh9f6PHaOI=
Please use this bug report code.

**Comment by Alezanello** [comment]
<br>Hi there!

I was able to register, validate my email, and sign in without any issues. Everything looks fine on my end, and I didn't notice any problems in your project. Are you still experiencing the issue?

Let me know!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/36fd19b2-c31b-400b-b986-befb709e16e6/d4975ff5-f3ce-4b76-8a64-ffb212bd1629?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNmZkMTliMi1jMzFiLTQwMGItYjk4Ni1iZWZiNzA5ZTE2ZTYvZDQ5NzVmZjUtZjNjZS00Yjc2LThhNjQtZmZiMjEyYmQxNjI5IiwiaWF0IjoxNzI4OTA3NDQwLCJleHAiOjMzMjk5NDY3NDQwfQ.dILS4M_ZjQuEKVzSYrElg7DX-Q9B6_EfCyR7TGGP2cA " alt="image.png" width="1195" height="969" />

**Comment by xiaoyaoyun** [comment]
Maybe I didn't express it clearly. This issue occurred when I tested the Android device using FlutterFlow Desktop. Could you please test an Android phone using FlutterFlow Desktop?

**Comment by sanjayelate** [comment]
Hey, is this an issue when trying to test via Local run? Or is it the same with any simulator?

If so I think it might be related as I'm experiencing the same across both iOS and Android simulators.

I could be wrong but these issues all might be related:

https://github.com/FlutterFlow/flutterflow-issues/issues/4000
https://github.com/FlutterFlow/flutterflow-issues/issues/4001
https://github.com/FlutterFlow/flutterflow-issues/issues/4047
https://github.com/FlutterFlow/flutterflow-issues/issues/4048

Seeing a pattern where action blocks and/or api calls aren't being executed

**Comment by xiaoyaoyun** [comment]
This issue occurs when trying to test via Local Run: the actions in the button are not actually executed.
