### ISSUE TITLE
Switch Issue Model Default Value only in Local Device Test Run. - Not Web RUN mode

### ISSUE THREAD

**Issue by cadufreeela** [FlutterFlow/flutterflow-issues#4049]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a menu drawer which is providing the following error, this issue is not happening in RUN mode, only Local Run mode

[errorLog.txt](https://github.com/user-attachments/files/17358954/errorLog.txt)

### Expected Behavior

Menu drawer should render on screen

### Steps to Reproduce

1. create new page
2. add a new menu drawer
3. add a containter
4. add a switch inside a container, defaul value should be attached to the authenticad user available=true flag
5. run locally in device: Android

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksjf35N2ofVY+Krcc8ZsoCAXCUMfXOYZkutubxchfbKoEYYHPuLBVBJLYteQS29mI2KWnns03NLXjYX1UPEBPTSufYhxz65XQRfhe3OWMKnWEZO8fkBQEdFXfxXC07unviUmHNVodXwZwE6qCvCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

Local Device Run
![image](https://github.com/user-attachments/assets/1e418b70-a022-432d-8ab4-1af2f0105b07)
![image](https://github.com/user-attachments/assets/78ebfee2-2880-4199-ae36-96ad7a4f4096)

Web Run:
![image](https://github.com/user-attachments/assets/7dca07e8-7169-434a-a5e4-671e669cf207)

### Environment

```markdown
- FlutterFlow version: 5.0.6
- Platform:MacOS Desktop
- Browser name and version:
- Operating system and version affected: MacOS 14.6.1
```

### Additional Information

When checking on DevTools during localrun I can see the swtAvailableValue=false

**Comment by Alezanello** [comment]
Hello!

It seems there’s an issue with the switch when placed inside a component. We already have an open ticket for this here: [GitHub Issue #4039](https://github.com/FlutterFlow/flutterflow-issues/issues/4039), where others are sharing their experiences.

I’ll close this ticket as a duplicate so we can focus all efforts on the main issue.

Thank you for your understanding!
