### ISSUE TITLE
Creating a document in subcollection not working

### ISSUE THREAD

**Issue by kskirilov** [FlutterFlow/flutterflow-issues#405]
This used to work before, and seems to have stopped recently.

I have implemented my own chat with messages being a subcollection of channels.

As I try to create a new document in channels, the UX briefly attempt to create a new document and it all looks as if a new document was successfully created, but in less than a second that document disappears and the action flow breaks at the document creation. 
<img width="1039" alt="Screen Shot 2023-01-24 at 5 19 00 PM" src="https://user-images.githubusercontent.com/45692073/214362736-1eca6220-48ae-4bfb-a65c-56c10e6d0399.png">

^See screenshot of the exact setup causing the issue.

The flow doesn't get to Action 2 (clear text field), breaking at the first action in a strange way given that the UX reflects a new document creation for about 0.3 second, as I mentioned.

**Comment by hariprasadms** [comment]
Hi @kskirilov  - Thanks for sharing the issue details. Are still seeing this issue ? I just tested and can see that create documents under sub collection working fine. In the above given screenshot, it is a bit difficult to find out whats going on with the issue while creating document. Can you please share a short video which can show exact issue while creating document. and also confirm that fire-store rules are correctly set and deployed. Please share rules settings screenshots as well.

**Comment by kskirilov** [comment]
Hi Hari, here is a video 

https://user-images.githubusercontent.com/45692073/215357859-4bd371ea-ba12-4fce-9d5f-5d233a5357e8.mov

And here is a photo from that channel's document in the DB
<img width="1101" alt="Screen Shot 2023-01-29 at 9 53 47 PM" src="https://user-images.githubusercontent.com/45692073/215357876-9adc6141-6e8d-4437-90cf-0d15350c7a7c.png">


As you can see, no subcollection or messages get created (which is how it used to be, with the channels having a chat_messages subcollection that contains the documents.

**Comment by kskirilov** [comment]
@hariprasadms p.s. just redeployed all firebase rules and the issue is still the same. Also I can't see anything I've done in the last 3 weeks that would have broken this flow as it used to work previously

**Comment by yoheisoito** [comment]
Hi @kskirilov, are you still seeing this issue? One possibility is that some of your indices need to be recreated. As a test, can you try turning off orderBy or filters on your query and see whether you'd see the similar blanking out screen? Alternatively, you can check to see in your firebase indices whether the orderBy and the filter combinations are actually set up. Thanks!

**Comment by filipe-agrinsk** [comment]
Hello! Was having exactly the same issue, here's the solution:

After reconfigurating your Deployment rules in FF, copy and past them (the code below the rules), to your Firebase Console > Firestore Database > Rules, and then Publish

Somehow is lacking this automatic integration for some cases

Hope it helps.

**Comment by filipe-ak** [comment]
Hello! Was having exactly the same issue, here's the solution:

After reconfigurating your Deployment rules in FF, copy and past them (the code below the rules), to your Firebase Console > Firestore Database > Rules, and then Publish

Somehow is lacking this automatic integration for some cases

Hope it helps.

**Comment by kskirilov** [comment]
@yoheisoito I am not sure how the ordering matters since those documents don't even get created?

**Comment by kskirilov** [comment]
The bug no longer persists in a new project. This case can be closed. Thank you.

**Comment by hariprasadms** [comment]
Thanks for letting us know @kskirilov
