### ISSUE TITLE
Unable to Push with VSCode Extension

### ISSUE THREAD

**Issue by Rodriq** [FlutterFlow/flutterflow-issues#4050]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have successfully installed and configured the FlutterFlow Visual Studio Extension. After pulling my code, starting an editing session, and making some changes,

I tried pushing back but I got this error

Unable to sync with FlutterFlow. Please take a look at the problems panel for more details.

Please has anyone experienced this?

```
The supplied phased action failed with an exception.
A problem occurred evaluating settings 'android'.
C:\Users\ComputerCare\Desktop\Work\ff\test-error-ds4xja\android\local.properties (The system cannot find the file specified)
```
But I have my Flutter and Android SDK pointing in the right location.
Note: local.properties file is read only

### Expected Behavior

Push Successfully the modified code to FlutterFlow
I am simply just printing Hello World 

### Steps to Reproduce

1. Make sure you have your local environment setup to run FLutter
2. Install the FlutterFlow Visual Studio Extension
3. Setup your access token
4. Download code from FlutterFlow
5. Start a Code Editing session
6. Modify or Edit an existing custom code 
7. try pushing back to FLutterFlow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

nothingtoShow

### Visual documentation

![image](https://github.com/user-attachments/assets/93015dd4-9c86-4dc2-a904-4149ded8011c)

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Windows 11/VSCode, Cursor
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by Hipnagogi** [comment]
Have the same error but in web development

**Comment by Alezanello** [comment]
Hello,

Thank you for reaching out, and I’m sorry to hear you’re experiencing this issue. I’ve tried to replicate the problem on my end but haven’t been able to. Would you mind recording your entire process, from downloading the code, making changes, and then pushing it? This will help us track down any potential issues more effectively.

I appreciate your help with this!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ae088956-73c7-4409-a2f3-97e0093de5f0/07d6ac52-6903-4874-8e44-3bedf1ecd59f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZTA4ODk1Ni03M2M3LTQ0MDktYTJmMy05N2UwMDkzZGU1ZjAvMDdkNmFjNTItNjkwMy00ODc0LThlNDQtM2JlZGYxZWNkNTlmIiwiaWF0IjoxNzI5MTAxODU0LCJleHAiOjMzMjk5NjYxODU0fQ.q3Z96hGCFXCZPzoxWjdkbqGyPReO5OBZ6uj7raXddW0 " alt="image.png" width="1919" height="1026" />

**Comment by Rodriq** [comment]
@Hipnagogi @Alezanello Here is a video recording showing it
https://github.com/user-attachments/assets/12ac0f0a-0d5e-43f6-8b55-d02fb2bf00b2

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Rodriq** [comment]
As of today, Custom function can push but custom actions and widgets
doesn't.

If I try creating a new custom action/widget I didn't get the boilerplate
code as mentioned in the extension description and documentation.

Everything is up to date including the extension

**Comment by Hipnagogi** [comment]
I confirm, this issue still occures. Btw is there a way to use this extension on main branch?

**Comment by ggillon** [comment]
I have the same problem, also I find it annoying that the customer code functions are not in individual files

**Comment by Kemerd** [comment]
Same problem, I cannot push to flutter flow, pulling works just fine. Please fix

**Comment by Alezanello** [comment]
Hello everyone!

We’ve made several updates since this issue was first reported. Could you please confirm if it’s still occurring on your end?

Thank you, and we appreciate your feedback!

**Comment by marvinbr** [comment]
Hello Everyone!

I am still seeing the same issue.  Download works but upload does not. I have an action I am trying to push and the error consistently says .. custom function not found but I am trying trying push from lib/custom_code/actions .. Thoughts?

**Comment by Kemerd** [comment]
Still happening. Download works fine. Pushing does nothing. My code never updates. No errors of any kind. Even says it successfully pushed. I never see any of my changes in Flutterflow update. Please fix this, this workflow is completely unusable and I am a paying customer who has to copy and paste the entire file every time I make an edit

**Comment by rzambroni** [comment]
Hi everyone,

Thank you for your patience, and I apologize for the delay in responding. I’ve managed to replicate the issue you described and will now escalate this to the engineering team for further investigation.

I appreciate your understanding, and I’ll keep you updated as soon as I have more information.<br><br>Thanks.

**Comment by Kemerd** [comment]
Thanks, looking forward to getting this working, would save my workflow from lots of suffering
