### ISSUE TITLE
Unable to download code to VSCode

### ISSUE THREAD

**Issue by MindContact** [FlutterFlow/flutterflow-issues#4051]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Installed and configured the extension for VSCode, but fails to download the code, even from a blank/new project.

### Expected Behavior

It should download the project code.

### Steps to Reproduce

1. Install FlutterFlow VSCode extension
2. Setup with API Token
3. Try to download code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zefqxIt1xLRb7q6JKflagmA5KU96bZIZiMJraCosfZT2BLMcec/RVERoOP24THw7OVqZ8GoW3NLHvfD1LPE4FwiVRa591ZFqTwmWczmhSrHSFJWve2hRJ/1YfR26y8O7kxJ5Nvt1SE4Q3TmqCue/QjDXCYT0C1cgDq/LZO4=

### Visual documentation

![Schermata_20241014_140049](https://github.com/user-attachments/assets/25632a43-b443-4cc7-a8a2-6d7163380900)

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: Web
- Browser name and version: Chrome 129.0.6668.100 x64
- Operating system and version affected: Linux x64 6.11.2-4-MANJARO
- VSCode:
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.11.2-4-MANJARO

- FF VSCode Extension v1.0.8

```

**Comment by Alezanello** [comment]
Hello,

Thank you for reaching out, and I’m sorry to hear you’re experiencing this issue. I’ve tried to replicate the problem on my end but haven’t been able to. Would you mind recording your entire process, from downloading the code? This will help us track down any potential issues more effectively.

I appreciate your help with this!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b8fa5bcf-22e4-4102-a7c7-73790afb7d88/ed6fe0e8-b494-4e09-ac47-614ac19257e0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iOGZhNWJjZi0yMmU0LTQxMDItYTdjNy03Mzc5MGFmYjdkODgvZWQ2ZmUwZTgtYjQ5NC00ZTA5LWFjNDctNjE0YWMxOTI1N2UwIiwiaWF0IjoxNzI5MTAyMTE3LCJleHAiOjMzMjk5NjYyMTE3fQ.zkBakVVmf5xVoawDI1HRgZVXqS-sND1vfIQb7gHPNa8 " alt="downloadVsCode.gif" width="1905" height="1004" />

**Comment by MindContact** [comment]
Good morning and thanks for the reply, I made a screencast of what happens to me.
I checked that I have set the API Key correctly and I also tried to reinstall the extension and delete the VSCode extension cache, but unfortunately the result is the same.
[Kooha-2024-10-19-07-57-39.webm](https://github.com/user-attachments/assets/ca0fbf66-1ac7-4931-88fb-9e75bbb37e2c)

**Comment by MindContact** [comment]
Hi, this issue also happening with the new FF extension v1.0.13

**Comment by MindContact** [comment]
@Alezanello Do you have any updates on this issue?

**Comment by rzambroni** [comment]
Hello! I wasn’t able to replicate the issue on macOS using the VSCode extension either. I suspect this might be related to a compatibility issue with Linux, but unfortunately, I don’t have access to a Linux environment to confirm.

Would you be able to test on a Windows or another macOS machine to see if the issue persists? That could help determine if it’s specific to Linux.<br><br>Thanks!

**Comment by MindContact** [comment]
Good morning!
I tried on a Win10LTSC machine with the latest version of VSCode, and indeed I was able to download the project.

So I can assume that the problem exists and that it is a problem with the extension on Linux. I have not tried using other Linux distributions besides Manjaro. I am downloading Lubuntu to do more tests.

**Comment by rzambroni** [comment]
Please let me know how that went! I can inform the team about any specific Linux distributions that are not working properly. However, I want to be transparent that I’m not sure how soon this will be prioritized.
