### ISSUE TITLE
Lib component error when using initial value

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4053]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A library component that a widget "initial value" set from a calculation or variable, makes the component crash:

![image](https://github.com/user-attachments/assets/75ec6003-f364-4c05-a1a2-4dd6b92237f7)

### Expected Behavior

The components should not crash when setting initial value.

### Steps to Reproduce

1. Create a lib 
2. create a component "swComponent" with a parameter "initialValue"
3. add a switch to "swComponent" and set its initial value with "initial Value"
4. create a component "wrapper" and add "swComponent" to it.
5. set the "initial value" of swComponent with a single condition ("Random integer" > 0) 
6. publish the lib
7. create a project and import the lib
8. add the "wrapper" component to home page 
9. execute test mode
10. you will see the error

NOTE: also, it seems there is a FF error when you set "Random Integer >0", as you see in the video, it is necesary to copy paste.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cj8nf5c9NoctD+KruYMBr/ScWHDM+RYE00sFTdxQdN5PND+x/esnRQFJuZ9OrdkFDMWKWpHof0N7Gm9z1Je47OU2cY4s5+bphEwGWRTi6RIyIEZCWXHFEGshPCG7A06aFmB4nXfRaLy1iwUOmOOSATg3dNJ+wOVgRDsqXB5PXvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/71233ea3-3ccb-412a-bab8-c53322e14b15

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project Bug code:
IT4Cj8nf5c9NoctD+KruYMBr/ScWHDM+RYE00sFTdxQdN5PND+x/esnRQFJuZ9OrdkFDMWKWpHof0N7Gm9z1Je47OU2cY4s5+bphEwGWRTi6RIyIEZCWXHFEGshPCG7A06aFmB4nXfRaLy1iwUOmOOSATg3dNJ+wOVgRDsqXB5PXvgfuQ0SLb3kNh1JWeC/v

Lib bug code:
IT48j8nf5c9NoctD+KruYMBr/SMUJkM7a68zk9VEFBY8J5DaPOxzP/TBaldWUs+0YFZlM0yJ/Dkx/vPemvHTCfJeBzSWGdlz+rtuVAziUn+lMrrWC82NdG5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

**Comment by nev-21** [comment]
I tested with switch widget. Don't know if it happens with other widgets, It would be great if this issue was addressed in other widgets as well.

**Comment by Alezanello** [comment]
Hello!

It seems there’s an issue with the switch when placed inside a component. We already have an open ticket for this here: [GitHub Issue #4039](https://github.com/FlutterFlow/flutterflow-issues/issues/4039), where others are sharing their experiences.

I’ll close this ticket as a duplicate so we can focus all efforts on the main issue.

Thank you for your understanding!
