### ISSUE TITLE
Custom Code Navigation Controller Scrolling, header scrolls off screen

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#4054]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not really project specific, more about the ide.  Behavior is just buggy seeming, but currently working as implemented.  On the Custom Code view, the scroll is the whole column instead of the sub column of items.  If you have a lot of custom actions/functions/widgets, this can grow unwieldy.

### Expected Behavior

I would expect the sub column of code to grow and the header w/ the search and add buttons to remain fixed so that they were available no matter where you are scrolled.

### Steps to Reproduce

1. Go to custom code.
2. Create enough widgets, actions or functions to force scrolling.
3. scroll the custom code nav panel.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not a widget issue, IDE issue

### Visual documentation

Not scrolled:
![image](https://github.com/user-attachments/assets/4483fccb-4e1d-4fd4-8e8c-30ca54e9ae56)

Scrolled:

![image](https://github.com/user-attachments/assets/cc56e85f-7838-4b34-a6ef-d067aa9b6dbc)

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: N/A
- Browser name and version: Chrome
- Operating system and version affected: Windows / Mac
```

**Comment by Alezanello** [comment]
Hello, and thank you for your feedback!

It sounds like you're requesting a feature/enhancement to make the search bar function similar to a Sticky Header, correct? I’ll create an internal ticket for this request, but I’ll close this issue to keep the Issue Tracker focused on bugs, if that’s okay with you.

Rest assured, the team will add this request to the backlog!

Thank you again!
