### ISSUE TITLE
"Publish" lib button redundance

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4055]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you want to publish a library, you click button "commit changes and publish", you commit, then it appears again, you commit this second time, then publish button appear. In the end, I made several commits and several publications!!!

This issue make difficult to control versions.

### Expected Behavior

If I commit and publish, the button publish shouldn't appear. There should be only one commit and one publish per version.

### Steps to Reproduce

1. create a project
2. make some change (add a text to home page)
3. Go to "Publish as Library"
4. Click "Commit changes and publish" set message and accept
5. wait a few seconds the "commit changes and publish" appear again.
6. Click "commit changes and publish" again it let you commit again
7. wait few seconds. 
8. Publish button appear and it let you publish again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siM/lw4xNrsNf+KrAafpr/TgUKUA9RpE4sct/cxQcB4j4P+x+O8+kUFFBcMCzaHxcG1mlpE4e7vzxiIXPD/EpNSuYY4RS/qVuahPPY3ylbIy0Dc+oZkdATNlWfkvC4cCjgwhQAMtidU4C6jiIP9i+bz2Cf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/a5d4d05c-b1e3-4227-9868-8f23f845e525

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

**Comment by Alezanello** [comment]
Hello!

After the first "Commit changes and publish," everything should work perfectly. There’s no need to click multiple times. Once you commit and publish, the version updates automatically without any further action required!<br><br>If you check your video everything is fine after the first time you did it!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/81fdcab8-f139-438a-a103-308a74eee953/621e89fc-3c91-4d8b-a34c-efbd2cee30e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MWZkY2FiOC1mMTM5LTQzOGEtYTEwMy0zMDhhNzRlZWU5NTMvNjIxZTg5ZmMtM2M5MS00ZDhiLWEzNGMtZWZiZDJjZWUzMGU0IiwiaWF0IjoxNzI4OTQyNDc1LCJleHAiOjMzMjk5NTAyNDc1fQ.GEloEOu9EaigcGO9s5EgKj0me5_LoiEyoaEOLCCZXZg " alt="Text Alignment.gif" width="1905" height="848" />

**Comment by nev-21** [comment]
Hello @Alezanello,

Ok thank you I understand better now.
I think it would be helpful if the button is disabled when there are no changes to commit/publish.

**Comment by Alezanello** [comment]
Noted! I’ve passed this along to the product team. Thank you for your feedback!

I’ll go ahead and close this issue, but if you need further assistance, please don’t hesitate to reopen it.
