### ISSUE TITLE
Can't set variables after confirm

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4056]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set a variable or parameter, after click confirm the value or logic is not set. It seems this doesn't happen always.

### Expected Behavior

When we set a variable anywhere, it should be set.

### Steps to Reproduce

1. create a project
2. create a component with a bool parameter
3. add the component to home page
4. set the variable/parameter with "RandomInteger > 0" single condition
5. click confirm.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlfLlvM9grsNc0L6JK/pahiAsJkA8U40wluxuFQ83C4joG7YMS8+kMxJVXemndGNEL1r8pD4fw9KPkePEA+UpB0+aRaZ9wZNtEw3JUl65Va6WPcyOX0RRO91JJVOB1J2RvxUnHOhZSC0m2jite9nJZC3BNrrLNmovIc/8Kpr/jXOpQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/c0b7c0e4-2d5a-488f-b189-952f21a3d864

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. We already have an open ticket for this case, which you can track here: [GitHub Issue #3906](https://github.com/FlutterFlow/flutterflow-issues/issues/3906).

I’ll close this ticket as a duplicate, so please follow the provided link for any updates.

Thank you for your understanding!
