### ISSUE TITLE
Custom Icon issue

### ISSUE THREAD

**Issue by bsmenda14** [FlutterFlow/flutterflow-issues#4059]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All of my custom icons are now a grey 'x' (see image). This was a purchased UI kit from flutterflow marketplace so I cannot just reupload the icons.

<img width="1093" alt="Screenshot 2024-10-14 at 11 48 30 PM" src="https://github.com/user-attachments/assets/8b6ffc9f-f02c-498b-96a6-ef30a440a3aa">

### Expected Behavior

I just expect my icons to be back to what they were. I have hundreds if not thousands in this UI kit.

### Steps to Reproduce

1. go to theme settings
2. go to typography and icons
3. scroll to custom icons
4. open them and see they are all a gray 'x'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEezPLq0811pbwA16Xcae4whQMwQWYla+dIoetxc0gbfe/4OokIfszSbVtDTsyzaHxcBGKbpE8B+N7Nj97uVvpcEwycbNVkys9qSBPPbFumM7aWDquaPmpPEexYBWK05sHQkSZvIvhaLHAC7WeYHNi/Yz2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1457" alt="Screenshot 2024-10-15 at 12 01 59 AM" src="https://github.com/user-attachments/assets/44b708c0-c08f-4c83-bf8d-add8540e6dc4">

### Environment

```markdown
- FlutterFlow version: v5.0.6+ released October 12, 2024
- Platform: web, MacOS Desktop
- Browser name and version: chrome Version 128.0.6613.138
- Operating system and version affected: desktop macOS Sonoma 14.2.1
```

### Additional Information

I use a lot of icons so it affects the UI of my app greatly

**Comment by Alezanello** [comment]
Hello, and we’re sorry to hear you're experiencing this issue. Could you please reach out to our support team directly via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io)? They’ll be happy to assist you further.

Thank you!
