### ISSUE TITLE
Auth action stopped working

### ISSUE THREAD

**Issue by kskirilov** [FlutterFlow/flutterflow-issues#406]
Auth action stopped working

<img width="938" alt="Screen Shot 2023-01-24 at 7 41 26 PM" src="https://user-images.githubusercontent.com/45692073/214392379-ef17ded9-76a6-4b04-a485-17b53af76563.png">

Screen stays stuck on this page and fails to execute write action

**Comment by bulgariamitko** [comment]
Please fill all the information from the issue template, but what I am thinking is that when there is an successful Auth FF logic will always continue to the login page that you define in your settings and ignore all other actions I am not sure if this is your case, but that is what I will guess.

**Comment by kskirilov** [comment]
## Expected behavior: the action after auth should also execute, and it used to be the case for months until a recent update

## Current behavior: the action after auth is not executing at all.

## To Reproduce
1. Create a phone auth flow
2. On the code page, add an action to write data to the authenticated user *after* auth
3. Attempt to run it 
4. The actions afterwards won't work


### Bug Report Code (required, generate from Widget Tree)
ITESz/Hqx89goeZI0arpLe5AhQAkH1x/bZJEl9dTewobfb7mEO0qeur+VFNoX/W8fXx6OmL+oFkF7trxhoaWEvkDISetetE2k/UwKlCvHAM=


## Context (required)
Trying to sign up as a user, unable to


## Screenshots / recordings
Already attached

## Your environment
Using MacOS, Chrome browser, latest version of FF


Thanks for the help. Happy to also set up a call if it may be easier to debug it. My email is krasimirkirilov.b@gmail.com

**Comment by isegal** [comment]
@kskirilov is your action referencing a the current user reference? Eg `currentUserReference` in the generated code ?

@FlutterFlow, I was chasing down a rare authentication issue where `currentUser`/`currentUserReference` may not be getting properly set and found the following generated snippet:

`firebase_user_provider.dart`:

```
MyProjectFirebaseUser? currentUser;
bool get loggedIn => currentUser?.loggedIn ?? false;
Stream<MyProjectFirebaseUser> myProjectFirebaseUserStream() =>
    FirebaseAuth.instance
        .authStateChanges()
        .debounce((user) => user == null && !loggedIn
            ? TimerStream(true, const Duration(seconds: 1))
            : Stream.value(user))
        .map<SnagNexusFirebaseUser>(
      (user) {
        currentUser = SnagNexusFirebaseUser(user);
        return currentUser!;
      },
    );
```
Could this debounce in theory drop a legitimate authentication message?

In `auth_util.dart` we see the authStateChanges() being handled differently, without the debounce:

```
AdminsRecord? currentUserDocument;
final authenticatedUserStream = FirebaseAuth.instance
    .authStateChanges()
    .map<String>((user) => user?.uid ?? '')
    .switchMap(
      (uid) => uid.isEmpty
          ? Stream.value(null)
          : UsersRecord.getDocument(UsersRecord.collection.doc(uid))
              .handleError((_) {}),
    )
    .map((user) => currentUserDocument = user)
    .asBroadcastStream();
```
The above seems to indicate that `currentUserDocument` global is likely being set more reliably than `currentUserReference`

If the goal is to filter out duplicate messages from firebase as a result of a bug, would using `.distinct()` be a more reliable alternative than a `.debounce()`?

**Comment by wenkaifan0720** [comment]
Hi @agreaves. Do you have a quick idea about why this might be happening? I don't know what has changed recently for user auth.

**Comment by kskirilov** [comment]
@wenkaifan0720  I decided to move the actions to the page after as a workaround, but there is one issue I still have open which may be relevant to you too (updating a document via action reference doesn't seem to work anymore) -> https://github.com/FlutterFlow/flutterflow-issues/issues/404

@agreaves I'm pretty concerned if those issues are being dealt with with the urgency they deserve internally? I've been experiencing major issues for weeks now and I've not seen the team communicating what is happening and how much longer this is going to last. I'm having to let customers down and it's been quite severely negative. I know it happens but I and others would appreciate to know what is happening and when this will be sorted.

**Comment by wenkaifan0720** [comment]
Hi @kskirilov. I am sorry for your experience. The FF team has been occupied by the Flutter Forward event and a company trip (which focuses on usability) for the past few weeks. I'll look into your issue right away.

**Comment by wenkaifan0720** [comment]
I just made a test project: https://app.flutterflow.io/project/flutterflow-issue-406-d0vxej. And the update field action after auth still works. I really need to look into the code of your project to see if anything is wrong.

**Comment by bulgariamitko** [comment]
@wenkaifan0720 the bug report code is posted, here it is 
ITESz/Hqx89goeZI0arpLe5AhQAkH1x/bZJEl9dTewobfb7mEO0qeur+VFNoX/W8fXx6OmL+oFkF7trxhoaWEvkDISetetE2k/UwKlCvHAM=

**Comment by kskirilov** [comment]
@wenkaifan0720 Can you please try to resolve the #404 issue I shared too? I suspect this is at the core of what has been causing me a lot of the other issue (perhaps including this one). Thank you.

**Comment by wenkaifan0720** [comment]
Figured out the issue was improper firebase rules.
