### ISSUE TITLE
Debug panel error when Build in FlutterFlow switch widget is present

### ISSUE THREAD

**Issue by juanpenuelasPalletways** [FlutterFlow/flutterflow-issues#4060]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After a Monday morning FlutterFlow update (14/October/2024) I get this error out of no where in pages/Components with a **FF build in Switch widget** when running 
- "test mode" in the browser  
- "local run" in my physical device from Flutter flow, 

![image](https://github.com/user-attachments/assets/062b532d-d82a-4f54-8c75-476364bb69b0)

The problem DOES NOT happend when I 
- run the app from VScode in debug mode in my physical device with the latest code from the main branch.
- Execute the APK generated from FlutterFlow

All branches of the proyect even the ones that have not been modiffied for more than 2 weeks get now the same exact problem

All the pages and components with a switch through the exact same error.
The error is not shown in pages/components without any switch widget but when I add it from scratch (no action or anything) the error comes up, I tried assigning colors to active/inactive/disable states but the error still appear.

### Expected Behavior

No error should be shown

### Steps to Reproduce

1. add a FF Switch widget to any page or component
2. run in test mode or local run

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT9TiPLl8Yx2rt8D7aXUY+9ajiMRKUc7U7gRm9V+axAafY/qB4YXe87VNxFAUserTAl+JVr9mX8fzNaLuOPtFeYIaCmrGYA7ws9QRDngITmuRqnXBqmJbWNfO+ZUG2Ka4Z2NoyV5BNZvWiE1wF2MOuSvTg3FG6GxPG0zJcqZKqbNn3ipLg/BVhZHxSo5RmWvPfAXZA+gs6jJjMMR3ezrxw==

### Visual documentation

![image](https://github.com/user-attachments/assets/9e7285c8-d671-47d5-8ffc-3c13c717dcb7)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.6 released October 12, 2024
Flutter version is 3.22.2
- Platform: Mac 
- Browser name and version: Chrome browser Versión 129.0.6668.100 (Build oficial) (x86_64)
- Operating system and version affected: MacOS 13.6.9 (22G830)
```

### Additional Information

I cannot use the test mode as many of my pages have a switch

**Comment by Alezanello** [comment]
Hello!

It seems there’s an issue with the switch when placed inside a component. We already have an open ticket for this here: [GitHub Issue #4039](https://github.com/FlutterFlow/flutterflow-issues/issues/4039), where others are sharing their experiences.

I’ll close this ticket as a duplicate so we can focus all efforts on the main issue.

Thank you for your understanding!

**Comment by juanpenuelasPalletways** [comment]
Great! Thanks!
