### ISSUE TITLE
FlutterFlow Desktop app crashes unexpectedly while merge is in progress

### ISSUE THREAD

**Issue by Maazkhalid47** [FlutterFlow/flutterflow-issues#4061]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been experiencing the same bug for months now, whenever i try to merge a new branch or resolve conflicts the desktop app shuts down unexpectedly, then I have to restart the app, and this happens 2-3 times atleast, then I mostly head to browser app to merge it 

### Expected Behavior

 I should be able to merge the branch and resolve conflicts without the app shutting down

### Steps to Reproduce

1.Create a project
2.Create a page and add a container
3.Create 2 branches
4.Edit the same container with both the branches to create a conflict.
5.Try to merge 

the desktop app should crash

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43zPLqw4h1xdtH0KXqafdKngERQlwKao0amsBraCosfZT2BLMcec/RVERVOd+/SnNPe1majWoW0/zTjuLuGMIFNTOdRqU4ysxqcwzyUTiibpjSFJWgPXcmHZhhI32B0LaZ2x5BJtt2SCEa62emBOmQaArbHuPMPm48D6/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/d62f2cf2-c441-4898-8786-dd7d0faeb21f)
![image](https://github.com/user-attachments/assets/0c77bd7d-72b8-4f2d-9d85-eda9a1fb9e66)
![image](https://github.com/user-attachments/assets/63a729cd-573f-4ffa-9822-12b38cb9f17f)
![image](https://github.com/user-attachments/assets/dbc1d4de-0964-403b-9a1c-9453860d720b)

and it just closes

### Environment

```markdown
- FlutterFlow version:  v5.0.5
- Platform:Desktop windows
- Browser name and version:Chrome 129.0.6668.100
- Operating system and version affected: Windows 11
```

### Additional Information

I have to repeat the same process atleast 3-4 times in order to merge a single branch and seldom reach completion, mostly I have to head to the browser app to merge it.

**Comment by max-h-silverman** [comment]
I'm seeing this as well. It woks on web but causes the desktop app to crash.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. If you don't mind, could you please record a video showing the steps you take before merging and when the crash occurs? I’ve been trying to replicate it, and it seems others are facing the same issue, but we haven't been able to provide the engineering team with a video for them to review.

Thank you for your help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
