### ISSUE TITLE
Environmental variables are not appended to API calls in run mode

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#4062]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you set the environmental variables so that for instance the url looks like this:- [https://myapicall.dev/dev](https://myapicall.dev/dev) where dev is set using \[Endpoint\] so in FF it actually looks like this [https://myapicall.dev/\[Endpoint\]](https://myapicall.dev/%5BEndpoint%5D) The environmental variable is left off the api call only in RUN mode. So rather than calling [https://myapicall.dev/dev](https://myapicall.dev/dev), It calls [https://myapicall.dev/](https://myapicall.dev/)

In test mode there is no issue, it correctly appends the environmental variable to the api url. It is because of this that I believe that the project is correctly set up, and that this is a bug.

### Expected Behavior

The expected behavior is that the run would work in the same way as the test which would be to append the environmental variable to the url. The absence of such a variable means that the application fails to function. The workaround, which is extremely annoying and time consuming, is that each time before a run is made so that the rest of the company can see the progress, I need to hard wire in the actual endpoint appendage, run it, and then set it back again. With over a half a dozen different apis I have to do that for each one.

### Steps to Reproduce

Add an environmental variable to be used in an api endpoint. Test the endpoint in test mode, and find that it all works. Test exactly the same thing in run mode and find that the apis all fail.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43h/Lm5ZR/nMQD5s/IQ8FupAIvHHIHWuYk0NlraCsofePrOpkAf8/7UFtUcN/iY1Y7OU2GrGQX/MrwidmeGsYrNS+qc7ZH+KgAFhX/XmeXaJiLCZS3b3dAFppTfUicyKu3qhNCCNheWFoswziIBumuZA3DQJjQDEQzMOaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bc137ad0-5347-440a-a2e9-642a717cd03f/6b64c9bd-c272-4a34-8118-9dc05cb1320b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYzEzN2FkMC01MzQ3LTQ0MGEtYTJlOS02NDJhNzE3Y2QwM2YvNmI2NGM5YmQtYzI3Mi00YTM0LTgxMTgtOWRjMDVjYjEzMjBiIiwiaWF0IjoxNzQzNTE0NTYwLCJleHAiOjMzMzE0MDc0NTYwfQ.B7qivcygWm6nzbQFt-9bbfDC8-uWOzV6ZapF88xZ1Uc)

### Environment

```markdown
- FlutterFlow version: Desktop most recent
- Platform: WIndows
- Browser name and version: Chrome
- Operating system and version affected: All
```

### Additional Information

It slows down development and is somewhat chaotic!

**Comment by Alezanello** [comment]
Hello,

I’ve been able to replicate the issue and can confirm it’s a bug. I’ll be forwarding this to the engineering team for further investigation and a fix. Thank you so much for bringing this to our attention!
