### ISSUE TITLE
Gray screen of death on merging branches.

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#4063]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It's hard to say exactly what the current behavior is, only that we are still crashing with gray screens which makes in my opinion the whole feature completely unusable. There are two places which it crashed. In one place it was simply that we had merged a branch into development. That worked. And then we wanted to merge development into main. At that point we got a gray screen of death as seen in the images attached below. The entire flutterflow desktop application just crashed. However prior to that there is another gray screen of death which is simply in the merge history, and I noticed that that was there right at the onset. Which makes me think that the whole thing was bugged before we even started the process.

### Expected Behavior

The expected behavior would be not to crash. A problem with the crash is that we simply just don't trust the merge. We used it a couple of months ago,  and gave up on it then because we just couldn't get it to do anything except mess up our code.

### Steps to Reproduce

Going to our project and try and merge anything into main. We would obviously prefer if you didn't do that, because this is a production version . But if you want me to show you how,  I'm perfectly happy to do that.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YAW/SkQE9WZ7yhdH03PFr8jmAepvDQkfbIN/Y6IRGVGdVHzqhqFgmVUn+XSr6wBauSQWtQBtpKCHKYy6avox5vKrNqdCU62VOqJd6uaD7dNub1PFQ7Df6XIZLIo3PuQ0SLb3kNh1JWeC/v

### Visual documentation

![crash merge](https://github.com/user-attachments/assets/8a9ed190-b9a3-4b9f-8ab0-aba78ddfd118)
![image](https://github.com/user-attachments/assets/854e398f-9253-4ca6-8314-b9e1c7086748)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Desktop latest Windows
- Browser name and version: chrome
- Operating system and version affected: all
```

### Additional Information

Still can't use branching.

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. Unfortunately, I wasn't able to replicate the problem in a new blank project. In this case, I recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They will be able to assist you further with resolving this issue.

Please let me know if there's anything else I can do to help!

**Comment by charliefabley** [comment]
Hold on a second, four of the most 7 recent bug reports on Github are to do
with Branching. At the very least could you please go into my project and
correct whatever corruption you've got in the database to which I have no
access which is causing the grey screen when I look at my merge history. It
simply is not something that I can do. No one is saying that every
single time one merges that it happens ,  but what I am saying if you look
at my project it is broken  and there's nothing I can do to reverse it
without your assistance.

**Comment by Alezanello** [comment]
Hello Charlie,

Apologies for the delayed response. Unfortunately, we don’t have access to the database either. For more specific issues like this, the support team is best equipped to assist. The GitHub Issue Tracker is primarily for reporting bugs that can be reproduced from a new, blank project.

I’m really sorry we can’t help directly from here, but I hope the issue gets resolved soon with support’s assistance. Thank you for your understanding!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by Kemerd** [comment]
Also getting this issue
![image](https://github.com/user-attachments/assets/d748552d-5879-49be-8fa6-af251720c0c3)
