### ISSUE TITLE
Lib component state and widget state can't not be accesed if it is used as widget builder parameter

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4064]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A lib component state and widget state is not accessible from consuming project when it is used as a parameter in a widget builder parameter.

### Expected Behavior

The component state and widget state should be accessed even when a lib component is used as widget param.

### Steps to Reproduce

1. create a Lib
2. create a component "libComp" with a local variable, and a form field (like checkbox or text field)
3. publish the lib
4. create a project and import the lib
5. create a component "xComp" with a widget builder param "xWidget"
6. create other component "yComp" and use "xComp", put "libComp" into "xWidget"
7. use "yComp" into homepage
8. add a Text widget, and when you set its value try to access libComp state or its checkbox state

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ohc/1z892pbwD1arqd/lanSQWOUA5aLxN1sBhUQs0C5/NG7UIec/4VEptXbC+TVc3PGKajXwx/v+KhvbIN+1fAAeaGpxmyaVUSQ7weGSlMba6C6rgdGtTPNpKCWa14J+3oSZ4IvZZLWAE62GqfN69a3PdJr7rIWwjRMiiDN7Xo3fuQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/76d74796-327b-4246-94e1-077f07f02bd9

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug code:
IT4Ohc/1z892pbwD1arqd/lanSQWOUA5aLxN1sBhUQs0C5/NG7UIec/4VEptXbC+TVc3PGKajXwx/v+KhvbIN+1fAAeaGpxmyaVUSQ7weGSlMba6C6rgdGtTPNpKCWa14J+3oSZ4IvZZLWAE62GqfN69a3PdJr7rIWwjRMiiDN7Xo3fuQ0SLb3kNh1JWeC/v

Lib bug code:
IT4Chc/1z892pbwD1arqd/lanSQXNmYmRY0njMBxTk00HZPMD+wuY/SkcktuOe20TXNYemH88X8z+e/emvPAFfQEAw6eGohBwqVycwLgXnqjSqrSPKm0T25/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

**Comment by nev-21** [comment]
Hi, @paulperez-dev @Alezanello can i get an update on this issue? 

Please we can't work yet due to these issues.

**Comment by nev-21** [comment]
Hello @leighajarett @paulperez-dev please could you review this issue, it has been 2 weeks without news.

**Comment by Alezanello** [comment]
Hello!

Thank you for your patience, and I apologize for the delayed response. I’ll be taking over this issue from here.

I appreciate the video you shared—it made it much easier to replicate the issue. To be transparent, I’m not certain if this behavior is expected or if it’s an area where the Widget Builder could be improved. This behavior isn’t limited to library components; the same result occurs if the component with the TextField or Checkbox is created within the same project.

For reference, here’s a similar project example: [Project Link](https://app.flutterflow.io/project/q-a-2301-v2-pkzy7b).

I’ll pass this along to the team to confirm if this is indeed the intended behavior. If it’s not, I’ll mark it as a bug; otherwise, it will be treated as an enhancement request.

Thank you!

**Comment by sgardoll** [comment]
I'm experiencing similar issues with this project but with parameters fed dynamically into a component within a library: https://beta.flutterflow.io/project/card-based-flow-da3dja

Bug code report (library project): IT48lfLqw5RgocdY18/ucu9VliMXQmk7U5I4mNVuURA8J5DaPOxzP/TBaldWUs+0Sgk7I02goDo0wNnemvP9E/U6AziqRYRM/rVqUgmUXmenVLqTEcywT25/DfpYG2641qeFuhV/NvNudGwE2E+mHdyXXi7UQqb2PTMdRvGHJZKK2SrDX1iXc2URm05KZDPz

Bug code report (client project): IT8skfLqw5ROxPVD+Kr2dsBvoCoRNjsnaqxMiO0bbwodCJzuPJYLe8zRfhFoZ7Dja1NEDWH8/TsJw/TKhuztBMY7NRGrRpxm+M8AQx7geziiaJikPZG0ZHd6HeNYJhWB5J+j2BR/Lu1wd2wF1F2IAe6uQhTcGYzzOmsNJ/2LBLj7pEK6FXn3Fycy428APGabTI5ODEz25eKMrop5yfj/0w==

**Comment by wenkaifan0720** [comment]
Hi all. This is something very hard to achieve (and I don't think it is a good practice). The widget builder parameter is passed in dynamically at run time, so we don't store the passed component's internal state in the parent page. And we should really discourage usages like this, which creates a deep coupling between components. You can use either callbacks or state management to modify states. Or if you really want to, you can still directly use the component on the page.

**Comment by nev-21** [comment]
Thanks for your answer.

**Comment by nev-21** [comment]
Thank for your answer @wenkaifan0720, I'm agree, I don't like coupling too. 

But the only thing It doesn't make too much sense to me is: 

If I have a comp X with a textField widget inside, and X is used in a widget param, and we know the textField has an internal state (on its own); when I want to access textField state from outside, lets say the containing page, I should use a page variable and a comp X callback to update that page variable. That callback maybe is called on text change event. This is necessary because they are decoupled which is good.

But there are cases when the page variable may be changed by some kind of logic (for example the variable can be cleared from other action in the page), so if that happen the variable has changed but the textField widget inside compX doesn't change, this is the strange thing, how can sync the textField internal state with the page variable state? It doesn't make sense to call "Set form field" from page because of decoupling, also doesn't work if component X would have an input param (where we pass the page variable) because components doesnt have a way to change textField value when an input param change. 

**Please @wenkaifan0720 what will be the solution for this?**I think there are many approaches:

1) FF should allow to use an "action flow" when some desired component param change. Inside that flow we could call "Set form field" 

2) Components action blocks should allow to call "Set form field", so I can made a block to set textfield, And component actions blocks should be allowed to be called from outside the component. I think this is good because we can encapsulate behaviour.

Please let me know if I should open an issue to address this related problem—I'm happy to do so.

**Comment by nev-21** [comment]
Thank for your answer @wenkaifan0720, I'm agree, I don't like coupling too.

But the only thing It doesn't make too much sense to me is:

A component X contains a TextField widget (which has its own internal state) and X is used as a widget builder parameter. So, when I want to access the TextField's state from an outside page, requires a page variable and a compX callback that updates this page variable. For instance, this callback might be triggered on the TextField's text change event. This way X and page are not coupled, which is good.

However, a challenge arises when the page variable needs to be modified by other logic on the page (for example, an action that clears the variable). In such cases, the page variable’s value changes, but the TextField inside component X doesn’t update accordingly. This leads to a disconnect between the TextField's internal state and the page variable’s state.

How can both be in sync? It doesn't make sense to call "Set form field" from page because of decoupling. Also, It doesn't work if component X would have an input param (where we pass the page variable) because components doesn't have a way to change TextField value when a component param change.

**Please @wenkaifan0720 what will be the solution for this?** I think there are many approaches:

1. FF should allow to use an "action flow" when some desired component param change. Inside that flow we could call "Set form field".

2. Components action blocks should support to call "Set form field", so I can made a block to set textfield, and "component actions blocks" should be allowed to be called from outside the component. 

3. Make components like "TextField", "ListView", etc presentational components (dumb components), so it is possible to control their states with external variables passed as component params. This will require to add more events to ListView specially (to control infinite scroll for example)


Please let me know if I should open an issue to address this related problem.
