### ISSUE TITLE
Missing Scroll Bar when having both horizontal and vertical scoll

### ISSUE THREAD

**Issue by zeymermontes** [FlutterFlow/flutterflow-issues#4065]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

tif you have a Row with scrolling activated and inside a column that also allows scrolling. The scroll bar will only appear on the column. Scrolling is still working on mobile or with trackpad, but with the mouse this is not posible.

### Expected Behavior

having 2 scroll bars one on the column and other on the row.

### Steps to Reproduce

1. Create a Row with multiple elements. 
2. Allow scrolling on the row
3. Add a column inside the row with multiple elements
4. Allow scrolling on Column

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cl/H15cl2rsBE7rr+Y8JFhiYsKUAkRYEk0+4bGBc3HZPTC7N/PPWkVBJWOLy6T2x2I0SmmlEG/9LzhdjMU+1cAzCefJRI/pdQVA7yTmS5a5OBDJagOXwlI91mFWaZ5LbQsQl+IsFpcWQTw07zAdivEwTYQZzyImdISq/LZO4=

### Visual documentation

<img width="1433" alt="Screenshot at Oct 15 15-18-10" src="https://github.com/user-attachments/assets/89b0b688-aaa9-4b6f-82da-d1845b6cfdcd">

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: All Platforms
- Browser name and version: All browsers
- Operating system and version affected: All
```

**Comment by paulperez-dev** [comment]
Hi @zeymermontes,

I was able to scroll both horizontally and vertically using the mouse.

In The **SingleChildScrollView (used for scrolling)**, the scroll bar only appears for vertical scrolling, which is the default behavior in Flutter.

**Comment by Franco98404** [comment]
A solution to this can be add a property to check an option to always show the scrollbar on columns and rows, can you add it as a feature request?

**Comment by paulperez-dev** [comment]
Hi @Franco98404,

Sure! I will go ahead and request the addition of the `ScrollBar` widget. Thank you for your valuable suggestion!

**Comment by kantarse** [comment]
> Hi @Franco98404,
> 
> Sure! I will go ahead and request the addition of the `ScrollBar` widget. Thank you for your valuable suggestion!

@paulperez-dev can you share the reference to this request so I can get information about the progress? I'm waiting for this addition.

**Comment by paulperez-dev** [comment]
Hi @ercanyuz,

Feature requests are added to an internal backlog, so the ticket isn’t visible to users. Apologies for any inconvenience.
