### ISSUE TITLE
Commit or discard uncommitted changes on branch main

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#4068]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Created a new branch, tried to merge and it gives the error "Commit or discard uncommited changes on branch main". However there are no changes and no uncommitted changes. 
![image](https://github.com/user-attachments/assets/a949459d-e6f8-4f59-85df-c4fcc74f7165)
![image](https://github.com/user-attachments/assets/49bec073-497c-4f0e-855d-95d0626d3a22)

### Expected Behavior

Should give ability to merge from branch to main. 

### Steps to Reproduce

1. Create app
2. Committ main branch
3. Create new branch
4. Merge

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMmBw891ofVZ0KXIL+9V+TwQOVs7bb80lsEaTUgaF4zyG7l/TMnOVBJuOLC0TX9MPGCkrz4x0NHemvzAV/I6MkyuGoRByM1IeBXzRn2hb4SwEpCKeG5/Ap9WI3auyreFkApSHLJvR1ojwVOqC+6XHyvAJZOxNTAvGMmbC5CK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/a949459d-e6f8-4f59-85df-c4fcc74f7165)
![image](https://github.com/user-attachments/assets/49bec073-497c-4f0e-855d-95d0626d3a22)

### Environment

```markdown
- FlutterFlow version: 5.0.6
- Platform: MacOS
- Browser name and version: Chrome Version 129.0.6668.91 
- Operating system and version affected: MacOS 15.0.1 (24A348)
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. Unfortunately, I wasn't able to replicate the problem in a new blank project. In this case, I recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They will be able to assist you further with resolving this issue.

Please let me know if there's anything else I can do to help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by monocat** [comment]
@Alezanello I'm running into the same issue. The last time I merged a branch was almost a month ago, before @itsstevenliu reported this issue. 

Btw- how can one check to see which commits haven't been processed? Or how to discard them? Since like @itsstevenliu I don't see any pending.

**Comment by cadufreeela** [comment]
Same issue here, checked in github and my changes are there but FF still says I have uncommitted changes before I try a merge into main.

**Comment by practicalPixel** [comment]
@cadufreeela In my case, I ran a commit in the Main branch and it worked. Not sure though what I was committing. I couldn't figure out how to confirm.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/4e525f66-4e7e-4d7c-b027-cada3100db4f">

**Comment by cadufreeela** [comment]
Hi thanks for getting back to me, how did you commit?

Developer Options > Push to Repo?

I've been doing it and it says successfully pushed to github, but if I
check Branch history tab it doesn't show the latest one.

**Comment by practicalPixel** [comment]
@cadufreeela Per my last screenshot, just click **Create Commit**, add a commit note in the next prompt, and click the **Commit** button.
