### ISSUE TITLE
FlutterFlow crashes when deleting branch

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#4070]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Crashes when deleting new branch

### Expected Behavior

Shouldn't crash.

### Steps to Reproduce

1. Create app
2. Create branch
3. Go to new branch 
4. Delete branch and enter name in prompt.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMmBw891ofVZ0KXIL+9V+TwQOVs7bb80lsEaTUgaF4zyG7l/S8+kfhNuXbC0d1VIM2Ggnnsy3PvemvOSNfApCEyuRos7+LpqawHJRjqnWqaTEc+gQG5/Ap9WI3auyreFkApSHLJvR1ojwVOqC+6XHyvAJZOxNTAvGMmbC5CK2SrDX1iXc2URm05KZDPz

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 5.0.6
- Platform:MacOS
- Browser name and version:Chrome Version 129.0.6668.91 
- Operating system and version affected: MacOS 15.0.1
```

**Comment by Alezanello** [comment]
Hello,

Thank you for bringing this to our attention, and we sincerely apologize for the inconvenience. I’ve confirmed the issue and will be forwarding it to our engineering team for a fix. We appreciate your patience and understanding!

Best regards,<br>Azanello
