### ISSUE TITLE
Action editor error for components with two widget builder parameters of the same type passed in

### ISSUE THREAD

**Issue by borisrybar** [FlutterFlow/flutterflow-issues#4071]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When components gets two (or more) widget buider parameters and same widget type (copmponets) are passed into such component, action editor for individual passed widgets fails. Please see my project ActionEditorError. 

1. I have created component MyButton, with Action parameter cparOnTap which should be called as callback when user taps on button.
2. Then I have created another component DoubleButton with two widget builder parameters cparButton1 and cparButton2.
3. Then I have placed DoubleButton component on HomePage and wish to pass two MyButton widgets into it
4. Then I have created action for button1 in action editor. Because whole button is passed as widget I have created that action as a parameter of passed widget. It is simple action showing alert message from button1
5. Finally when I try to setup action for button2 same way action is already there. It seams lik action editor do not distinguishes between widgets but takes the action based on widget type. And because same widget type (button1) is already there it shows its actions.

I am not quite sure if this is an error or feature but in general I would like to use widget builder nesting approach if possible because it allows me to do more abstract components with better reusability. However problem mentioned above is avoiding me to do so. 

### Expected Behavior

Each widget should have its own actions available for edit independently

### Steps to Reproduce

Please see Current behavior section I have described it there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl/KB249OxLlE7qrqacdF9Sk5Jlw2arhEm8N+dAAaC5CrBLYPXPykP1doTcOiTFZYMFv8sD4xp9LIkuPXU+QHAwutRqpazZBAbjnMTnKiMrKmDbmwPkckL51mNEuVyJ6nhRJNANhpc3As2EyqP/O/EwHtQ+/6PmwnDfqlIrL4+3CAAi+6Xn0Jg1ZSfCvr

### Visual documentation

<img width="1723" alt="Snímka obrazovky 2024-10-16 o 16 42 18" src="https://github.com/user-attachments/assets/a2a29190-2328-4b8a-9706-6e3ff72e4bbd">

### Environment

```markdown
- FlutterFlow v5.0.6 released October 12, 2024
- Flutter version is 3.22.2
- MacOS 14.6.1 (23G93), but tested also via web with seme behavior
- Chrome 129.0.6668.100 (arm64)
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I can confirm this behavior and will be forwarding it to the engineering team for review. They will assess whether this is the expected behavior or if it's a bug. We appreciate your help in identifying this!

**Comment by borisrybar** [comment]
Hello, I have received notification this issue is closed as completed. Since it is my first issue can you provide me more information about what it means? Is there a fix available or what is the state/next steps. Kind regards Boris

**Comment by Alezanello** [comment]
It means this fix was just sent to production!

**Comment by borisrybar** [comment]
Thank you Alezanello for reply, but if you mean Version 5.0.10 (5.0.10) problem still persists

**Comment by borisrybar** [comment]
Hi there, I'm bit confused now because also in 5.0.11 problem also persists. I don't want to bother you so is there a way how a I can know in which version problem is fixed or what is a provided solution? Regards Boris
