### ISSUE TITLE
My application doesn't appears on Test Mode

### ISSUE THREAD

**Issue by 00davidsarago00** [FlutterFlow/flutterflow-issues#4072]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It's quite simple, when I start a new test mode it doesn't load never!

### Expected Behavior

# **Normal test mode usage to debug and use my app.**

![CleanShot 2024-10-16 at 13 27 03@2x](https://github.com/user-attachments/assets/ebd1cf2d-92bf-4c54-99f9-0930bf01ee05)

### Steps to Reproduce

1. Start a new test mode

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giPLl8ZVOj7xH1rr+LO9Wr2A7G2I3bb00sNobbxAjIoDoPJkUaff4blpWZ/GnYEFLKEWJuGQH/87nvuzDV8c7By2eGK5c+ZBAZxbMXmO/aoS6DZeWR3dAP+dnGn600aSS2yJBIvp2S14f7UOMAuSUfB3vO7H7Zwh9f6PHaOI=

### Visual documentation

![CleanShot 2024-10-16 at 13 27 03@2x](https://github.com/user-attachments/assets/ebd1cf2d-92bf-4c54-99f9-0930bf01ee05)

### Environment

```markdown
- FlutterFlow version: 5.0.6 
- Platform: Web and MacOS
- Browser name and version: Chrome 130
- Operating system and version affected: MacOS Sequoia 15.1
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. I tried replicating it in a new blank project but wasn't able to. Sometimes, switching the resolution using the icons at the top (mobile, landscape, or web) can help trigger the load. You can also try using the "Instant Reload" option, as it often resolves similar problems.

Let me know if this helps!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by DonPimento** [comment]
HI, i have the same problem, do you find any solution ?
