### ISSUE TITLE
I cannot delete a page anywhere on the platform for all my projects

### ISSUE THREAD

**Issue by plau13** [FlutterFlow/flutterflow-issues#4073]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to delete pages and I cannot within the web or app. It is so incredibly frustrating as your documentation says right click or backspace and I do but NOTHING HAPPENS. Please fix such a simple error.

### Expected Behavior

That I can delete a page.

### Steps to Reproduce

1. Go to any of my projects
2. Open pages
3. Try to delete a page (any of them)
4. You can't

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89Nobhe+KnxbcFvhjsQJWZ7TLIFse0aRR4dF4zxPJYAdcnRNkNKTbCfT3NMfU2GmkwDpPznk/HLO/QpAwqaRohe0JVPEz3hc3ORVZCzPc+gY3EmJ51PClCh1raRsRRQIvphSnAC1zmHNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="1792" alt="Screenshot 2024-10-16 at 2 29 56 PM" src="https://github.com/user-attachments/assets/e9ada170-0216-4d98-87e5-cbfcebfd8ee3">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, MacOS Desktop
- Browser name and version: Chrome
- Operating system and version affected: macOS Monterey 12.2.1
```

### Additional Information

I can't delete any pages and it is incredibly frustrating to try and keep things together. Please fix this as this should be so simple on y'alls end.

**Comment by Alezanello** [comment]
Hello,

I wasn’t able to replicate the issue in your project or any other projects. If you're still experiencing this problem, I highly recommend reaching out to our support team through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) for further assistance.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/934004ac-bbf1-47b3-a846-2befbdc4e367/934c5e90-e616-4471-9394-887480ba40a6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MzQwMDRhYy1iYmYxLTQ3YjMtYTg0Ni0yYmVmYmRjNGUzNjcvOTM0YzVlOTAtZTYxNi00NDcxLTkzOTQtODg3NDgwYmE0MGE2IiwiaWF0IjoxNzI5MTcwMjk3LCJleHAiOjMzMjk5NzMwMjk3fQ.foXf6WLqLHwaq1eV67Oaq_4wI_MKAJvgi_5TaqpBGE8 " alt="deletePage.gif" width="1178" height="602" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
