### ISSUE TITLE
App crashes and reloads when attempting to view the Storyboard screen

### ISSUE THREAD

**Issue by fabioaanthony** [FlutterFlow/flutterflow-issues#4076]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When working in the storyboard screen in the mac os app (tab+4) it will randomly flash gray screen and the entire app will crash and reload back to the same screen. 

Also notice zoom in OR out and panning around the canvas appears to be flawed or just poorly implemented. 

### Expected Behavior

1. Screen should not flash gray and app crashes and reloads
2. UI for working with the canvas should be improved. Features like panning, zoom etc should work seamless  

### Steps to Reproduce

1. Open mac app
2. Open / create a project
3. Make a screen or two
4. Click into the storyboard 
5. Try to zoom in/out and/or pan around the canvas
6. Observe app crash and reload

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTks/l34x1m7RZ+KruKOxaqCEsCUMdXOczitVEew4bCIj4E+0qY/f7UFFBZ+qzaH5+DlSb8UcKwNLtv/LpMsYBEw2BRbpz+pBxEBPPbFymRpSoEamBPGgnI+NbJhXF36SvsApAJfpaR1oR72GuBt+RST2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/7795952b-bfef-458e-aaaf-5dd3befd7b0e">

### Environment

```markdown
- FlutterFlow version: Version 5.0.6 (5.0.6)
- Platform: Mac
- Browser name and version: N/A
- Operating system and version affected: Mac OSX 15.0.1 (24A348)
```

### Additional Information

App crashing is a P0 imo

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I’ve confirmed the behavior you mentioned and will pass this along to our engineering team for a fix. We’ll keep you updated on the progress.

Thank you for your patience!
