### ISSUE TITLE
Problema ao rodar tests no FlutterFlow

### ISSUE THREAD

**Issue by LeandroDuarte28** [FlutterFlow/flutterflow-issues#4077]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to run a project in test mode, the project loads but the screen goes white and the components don't load, it stays for a long time and doesn't work. It is impacting the sequence of my project, I ask for urgent help. Pro Plan and I can't use the platform

### Expected Behavior

When I try to run a project in test mode, the project loads but the screen goes white and the components don't load, it stays for a long time and doesn't work. It is impacting the sequence of my project, I ask for urgent help. Pro Plan and I can't use the platform

### Steps to Reproduce

![erro ff](https://github.com/user-attachments/assets/d658e236-9ce9-493f-884a-2d2c94ead3d3)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

não gera codigo de erro

### Visual documentation

![erro ff](https://github.com/user-attachments/assets/c1d419a1-031e-478d-9771-6865a7166f57)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry you're facing this issue. I tried to replicate it in a new blank project but couldn't reproduce the problem. In this case, I recommend reaching out to our support team through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io), so they can take a closer look and assist you further.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
