### ISSUE TITLE
Private Api Calls from Library Not working

### ISSUE THREAD

**Issue by blueprin4** [FlutterFlow/flutterflow-issues#4078]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using FlutterFlow's shared library feature with Firebase Functions, API calls from the shared (dependent) library stop working if the primary app and the shared library use different Firebase project IDs. Specifically:

1. When both the primary app and shared library use the same Firebase project ID, all API calls function correctly.
2. Upon changing the Firebase project ID for the primary app (to separate concerns and API calls), the API calls defined in the shared library cease to function.
3. The api call with fail.  The firebase logs will show:
TypeError: Cannot read properties of undefined (reading 'status')
4. Reverting both projects to use the same Firebase project ID resolves the issue, but prevents the intended separation of API calls between the primary and dependent apps.
5. The issue persists even after regenerating configuration files and redeploying the project.

This behavior suggests a problem with how FlutterFlow handles Firebase configurations for shared libraries, potentially not updating or correctly applying the configuration for the dependent app when the primary app's Firebase project is changed.

### Expected Behavior

When using FlutterFlow's shared library feature with separate Firebase projects, the expected behavior is:

The primary app and the shared library should be able to use different Firebase project IDs without conflicts.
API calls defined in the shared library should continue to function correctly, regardless of changes to the primary app's Firebase project ID.
When the primary app's Firebase project ID is changed, FlutterFlow should either:
a) Automatically update the necessary configurations for the shared library to maintain its connection to its original Firebase project, or
b) Provide clear options and guidance for developers to manually update the shared library's Firebase configuration.
Firebase Functions defined in the shared library's project should be callable from the primary app, even when using different Firebase project IDs.
The Firebase logs should show all API calls being initiated, regardless of which Firebase project they originate from.
Changes to the primary app's Firebase configuration should not impact the functionality of the shared library unless explicitly intended.

### Steps to Reproduce

Steps to Reproduce

Create a new FlutterFlow project (Project A) with Firebase integration.

Set up Firebase Functions for this project.
Create at least one API call.
Do not Make Call Private

Create a second FlutterFlow project (Project B) intended to be used as a shared library.

Set up Firebase Functions for this project.
Create at least one API call using Firebase Functions.
Make Call Private

In Project A, add Project B as a shared library dependency.

Add Project B as a shared library.

Ensure both projects are using the same Firebase project ID initially.

Test API calls:

Deploy Api call
In Project A, make an API call defined in Project B (shared library).
The shared library api call will work.

Change the Firebase project ID for Project A:

Update the Firebase project ID to a different, valid Firebase project.
Save changes and allow FlutterFlow to regenerate necessary configuration files.

Test API calls again:

In Project A, make an API call defined in Project B (shared library).

Check Firebase logs:

Verify that logs for the API call from Project A appear in its Firebase project.
The api call with fail.  The firebase logs will show:
TypeError: Cannot read properties of undefined (reading 'status')

Revert Firebase project ID:

Change Project A's Firebase project ID back to match Project B.
Verify that all API calls now work correctly again.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89goctH176JbcdGmmYWC2kcTeU30+thcw4bI+LkB+0pPsmkcldpSOqHTX9cJVWgkToG0PD4keD1O+43FwmCf7k7+Zd5UxDjXka5abK2O86SPURPGeZMI1TF1reF3CZRAOtodUZiw02yOdi+Y3qCf9qOYwx5e6fDbOY=

### Visual documentation

![1](https://github.com/user-attachments/assets/1ee4608c-6807-42a2-89c4-9f826e727439)

### Environment

```markdown
- FlutterFlow version:  3.22.2
- Platform: MacOS Deskto
- Browser name and version: Safari 17.3
- Operating system and version affected: macOS 14.3 (23D56)
```

**Comment by paulperez-dev** [comment]
Hi @blueprin4,

Thank you for sharing your project with us. It seems there are some errors present, but we weren’t able to reproduce the bug using the code from the bug report you provided. Could you please double-check and ensure that the bug is still occurring before generating the bug report code

**Comment by blueprin4** [comment]
Hey I will add back the firebase projects today.   Thanks for follow up.

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
