### ISSUE TITLE
Typo error in Import Colors

### ISSUE THREAD

**Issue by codestellar** [FlutterFlow/flutterflow-issues#4079]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="942" alt="image" src="https://github.com/user-attachments/assets/e570ec6f-ca3b-4b38-8a2d-920bb7d3548e">
The colors spelling in Import Colors is incorrect

### Expected Behavior

The spelling of Colors should be correct

### Steps to Reproduce

1. Create New Project
2. Go to Design System
3. Go to Colors
4. Observe the spelling of Colors in Import from Colors
<img width="942" alt="image" src="https://github.com/user-attachments/assets/f1bc47f3-ef1d-41f1-be26-3ee3b52e5025">

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Visual documentation

<img width="942" alt="image" src="https://github.com/user-attachments/assets/d9498283-b54a-46bd-b622-d8ffdd7080f1">

### Environment

```markdown
- FlutterFlow version: v3.24
- Platform: Web
- Browser name and version: Chrome 129.0.6668.91
- Operating system and version affected: mac
```

### Additional Information

This is not impacting. It is a simple typo error

**Comment by Alezanello** [comment]
Hello!!<br><br>This isn't a Typo error, Coolors is a provider of theme where you can import them into FlutterFlow [https://coolors.co/](https://coolors.co/)
