### ISSUE TITLE
Tagged Users Not Working.

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#4080]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a collection where you give any type of access (create, read, edit, delete) to any "tagged_users". The query will brake/not work.

### Expected Behavior

Is to give access to any collection and documents where the "tagged_users" rule to allow this users to access the collection as the current "expected behaviour".

### Steps to Reproduce

1. Create new project with Firebase and Auth.
2. Create a subcollection called "tagged_users" with a single filed called "tagged_users" which is a list of document references of type users (bascially all the users you want to give access to this document).
3. Deploy the rules (for testing purposes) of read -> tagged_users -> select the "tagged_users".
4. Create a subcollection into your users collection called "tagged_users" with a filed called "tagged_users" which is a list of references type users and add your user in this list.
5. Query this colleciton.
6. Does not work!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oksn6389IsdtJ+KriasExryQsH1whaqxM0MIbEQIaIpPNG4gIZfTBXE9uOP25dgk7P2GJo3IezPPFm9z1UvE6KQucRpg4/7hiEArdXT+gb6nQDKWeVERUGshRCUyF5omvpSRDAOhhLUYT2k2YFfC+cBbXGIToIXozMv/8JrvXrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

Please see the full video. https://dummy-1d799.kxcdn.com/videos/Tagged%20Users.mp4

FYI: To see the video you will need to simply copy paste the above link in your browser, if you do click it directly from Github it will not work.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.6 released October 12, 2024
Flutter version is 3.22.2
- Platform: All
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

### Additional Information

Notes: Please if somthing wrong was executed during this video and there is a way to make it work, please screen record the exact same action and steps to make it work.

**Comment by Alezanello** [comment]
Hello, and I’m sorry to hear you’re experiencing this issue. We currently have an open ticket addressing this problem ([https://github.com/FlutterFlow/flutterflow-issues/issues/3904](https://github.com/FlutterFlow/flutterflow-issues/issues/3904)), so I’ll go ahead and close this issue as a duplicate. We'll focus all our efforts on resolving it in the existing ticket.

**Comment by Kato-Official** [comment]
@Alezanello ok, thanks. Appricciated mate. Cheers
