### ISSUE TITLE
AI Page Generation - code is displayed, but it is not visible and not interactable

### ISSUE THREAD

**Issue by Rhobyte** [FlutterFlow/flutterflow-issues#4082]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Sometimes when generating code through AI of a page, the preview displays nothing graphically, but when you check the code there is code. Sometimes inserting the page results in the controls being visible and you are  able to continue (although it is a risk as it counts against the page insertion and you might not get what you envisioned, but have no way of viewing it).

![2024-10-17 12_01_28-Clipboard](https://github.com/user-attachments/assets/14dce1b9-88f6-402f-80ba-cdad0b616666)

Recently though, this has gone to another step in that while the page has been inserted, I am not able to view the controls and when you run it in test mode, it behaves as if nothing is there either: 

![Screenshot 2024-10-17 121741](https://github.com/user-attachments/assets/f2fb5157-a174-49fb-be7c-4268b6cd8589)

### Expected Behavior

It is expected (and has happened in the past) that the preview shows the AI generated page and that should a user insert it, they should be able to interact with the controls and continue with the page creation

### Steps to Reproduce

1. Click Create Page
2. Click from AI
3. Enter a description
4. Click to Generate
5. ... Screen image should generate reflecting the generated code
6. Click insert page
7. Click on object - they should be selectable
8. Click Test Run
9. Objects should be displayed and interactable

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CzOfl4ot1od9E1aqMbcBF9SkRNkw8RY0N0tVHRQIdJ5PMC+wIZ/f7XFRuTde0S1Y+M1qkhnMz+fvemvOWEcE3HASqf4hR/pd2UDnMJWKlaJCNPqWZOG5/DcpPFWK706bQpCRNNfVhSXwd7U7zP9iyVg7aHZzKClUZMOSbKZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Screenshot 2024-10-17 121741](https://github.com/user-attachments/assets/9f55dc0c-5bbe-43de-89e2-715405875b5a)
![2024-10-17 12_01_28-Clipboard](https://github.com/user-attachments/assets/9193d513-c6bf-4b53-aeee-da2bbe4ef8bd)

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: Web and Desktop
- Browser name and version: Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Operating system and version affected: Win 11
```

**Comment by Alezanello** [comment]
Hello!

I’ve created 10 pages using the generation tool, but I wasn’t able to reproduce the error. Could you please share the prompt you used that resulted in a blank page? This will help us investigate further.

Thank you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by Rhobyte** [comment]
Hi,
Apologies - I responded via email on the 19th with the issue happening as well as the 22nd (all below) as I thought that the email response would have updated the ticket : 

19th
Hi,

Sure - I have just had it happen in a new project.

The request was :
Create a Patrol screen which has a map of the users location, displays the co-ordinates and presents a logout button. It should also have the time the screen as displayed.

The result was :
![iLHPhK0UtMpjdlRj-1](https://github.com/user-attachments/assets/aa80561a-4412-4ed2-84a2-a33aeaaa5f0e)


the rating page button is displayed, but not interactable :
![qfBiy8QQvbRiuPwz-1](https://github.com/user-attachments/assets/9beee009-5a5e-4139-99c7-4147132355de)


and if I click as far outside the display as possible, the screen is returned:
![6CmbTJRIEfpRvkqg](https://github.com/user-attachments/assets/156b41d0-7660-47ec-b16d-be2ff0b75b17)

Fortunately this time, the screen is OK, but the preview display was not working as with the screens in the other 3 projects.

Hope that helps,

Mike

and the 22nd:
Hi,

Here is a second instance :
Request : creation of a landing page which displays some recent messages for a patroller to be aware of, a button to Start Patrol and list of any recent incident that have been raised by other patrollers
![q9avSs0QqZ0s06DY](https://github.com/user-attachments/assets/375aaaf4-1edb-45f8-924b-b76392ddd733)



The page ranking option was disabled :
![I6EQWbmhPahLVaYg](https://github.com/user-attachments/assets/84297aff-3333-4e25-9334-fee04654ef05)


and the resultant page was basically empty this time with the exception of the app bar which is a bit of a waste of the AI Page insertion :
![Q1lmDh1pMiMF0RRA](https://github.com/user-attachments/assets/e8e4027e-2b93-4662-a3fd-6f9d17387df9)


Mike
