### ISSUE TITLE
Notification (Custom text) Permission Problem

### ISSUE THREAD

**Issue by valinometru** [FlutterFlow/flutterflow-issues#4088]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I modified the notification permission text to reflect the apple guidelines/google play store and i notice that first of all as soon as i start the app (on the simulator or on my device from test flight) i'm getting the permission pop up for the notification even if i did not make anything inside the app (this occurs only when you activate the push notification) and second but more importantly if you change the permission text with the text that you need in order to be compliant with apple and google store it doesn't change! it just show you the default message and that's it...you can't change it anywhere. I tried in language and in permission, this are the only two places where you can change the text... for the photo and camera it's showing correctly... but for the notification it's not changing.... Now, i can't submit the app because i will get rejected again because is not compliant with the guidelines for the notification...

### Expected Behavior

it should change the default pop up message and put my custom test from the permission panel. 

### Steps to Reproduce

1. Go to settings
2. Click on permissions
3. Enable notifications
4. Write your custom text 
5. Compile and test it on a local simulator or on your device 
6. Even if you change the permission text for the notification the default one will show up. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjsmAw4hOxcMA7qXxbe5GoCM7C2Z6TL07ttYbZxUjIuPtBJh/e8zCYhNvYO3iS2lhHFG0pDkH+MrQjuP9M+4DNUybGog7yLthWzrLQXq8R5fXEKm0PXNCGtFYG0Ci1MOZkyYlXcxuR1Y93UyqA+qiTTDvCZ+/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-10-17 at 15 50 55](https://github.com/user-attachments/assets/268fa11b-7da3-4443-9503-94523174879b)
![Screenshot 2024-10-17 at 15 49 53](https://github.com/user-attachments/assets/58dca87c-52b7-42b8-a6a8-4313cde9d5fa)
![Screenshot 2024-10-17 at 15 49 12](https://github.com/user-attachments/assets/63438834-ba67-4abc-a352-e5c20250cdd1)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: v5.0.6
- Browser name and version:
- Operating system and version affected: MacOS Sonoma 14.6.1
```

### Additional Information

This behavior is only present on the notification permission the photo and camera are working fine.

**Comment by Alezanello** [comment]
Hello!

I’ve reviewed your **Info.plist** file, and everything is set up correctly. While there isn’t a custom dialog directly shown to the user, the guidelines required by the App Store and Play Store have been properly addressed. You can rest assured that your app won’t be rejected for this!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/86456baa-c8e8-4c9c-9b6d-453ef0c6de30/75a32b6c-26e7-4dc5-94b1-192dc7a3f82e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NjQ1NmJhYS1jOGU4LTRjOWMtOWI2ZC00NTNlZjBjNmRlMzAvNzVhMzJiNmMtMjZlNy00ZGM1LTk0YjEtMTkyZGM3YTNmODJlIiwiaWF0IjoxNzI5MjU0NDg0LCJleHAiOjMzMjk5ODE0NDg0fQ.zRLc3nbGWYM0CbSEvh7uUozU1o-ebbcKI6sV4YMjRDA " alt="image.png" width="991" height="585" />

**Comment by valinometru** [comment]
just curios then why i still see the default message? i did check what you just checked before writing this bug on git... and yeah it's showing correctly but inside the app when u test it it's a different story :) 

I'm getting this message even if i set up the permission that is the point!! In the info.plist is right, OK... but when you start the app on a simulator or on your device it display this:
 
![Screenshot 2024-10-17 at 15 49 12](https://github.com/user-attachments/assets/ee93de8b-4d6e-4f75-a33b-69cf78a22150)

Please tell me what else is there for me to test cz i'm running out of ideas ?

**Comment by Alezanello** [comment]
To implement a custom notification permission dialog, you'll need to include a **UsageDescription** in the **Info.plist**. Currently, FlutterFlow does not automatically add or modify this field; it only adds the required keys for App Store guidelines.

If you have access to the code on GitHub and want to add it manually, it should look like this:

```
<key>NSUserNotificationsUsageDescription</key>
<string>Your description goes here.</string>
```

**Comment by valinometru** [comment]
Thanks a lot!

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
