### ISSUE TITLE
Duplicate and Copy/Paste Data Types Doesn't work

### ISSUE THREAD

**Issue by iainmcfall** [FlutterFlow/flutterflow-issues#4099]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the Duplicate or Copy then Past Data Type, the fields from the origin data type are not copied.

I have tested this on 4 projects. All with the same result.

### Expected Behavior

The fields from the origin Data Type should be duplicated/copied to the new Data Type

### Steps to Reproduce

1. Select Duplicate Data Type from an existing Data Type
2. Enter provide a name for the new Data Type
3. Click OK

- or -

1. Select Copy Data Type from an existing Data Type
2.Select Paste Data Type 
3. Enter provide a name for the new Data Type
4. Click OK

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gouVc0artKMZqhQAkQzM8bYJMl9caRQAdGKnmE4YIPer+VHVCUu2De2xIJE2Z+D4F3N7PufLxCPc4FzmrQoNo/5NQWAvMUlytVcXWBsyae3dSGtJnC2qx35i3vhZ4JrJacixmw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

n/a

### Environment

```markdown
- FlutterFlow version: Version 5.0.6 (5.0.6)
- Platform: MacOS
- Browser name and version: Chrome
- Operating system and version affected: 14.6.1 (23G93)
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I can confirm the behavior, and I’ll forward this to our engineering team for a fix. We really appreciate your help!
