### ISSUE TITLE
When deleting a user from Project Sharing page is not updating.

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#41]
## Expected behavior (required)
When I delete a user I expect the page to be refreshed or the data and to see the user gone

## Current behavior (required)
The user is still sitting there and when you refresh the page and go back to Project sharing the user is gone.

## To Reproduce (required)
1. Go to a project that you are sharing
2. Go to Settings - Project Sharing
3. Delete one of the users
4. The user is still there

## Context (required)
I do not know if the user is really deleted or not. It is user misleading.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web 
* Browser name and version: Chrome 106
* Operating system and version (desktop or mobile): desktop

**Comment by hariprasadms** [comment]
I can reproduce this. At present on page refresh, the changes is reflecting. It should be handled through set-state. so that user no need to refresh the page.

**Comment by Pepino-GR** [comment]
I can reproduce it also. But the user is unable to work with the project anymore, if you delete the sharing. The behavior is also the same, if you use the FlutterFlow Mac App. The functionality is available and after a refresh of the page on both sides, you will see the changes. Maybe it is not a bug, it is a feature request.

**Comment by bulgariamitko** [comment]
I don't believe this is a feature request. I believe this is a bug 😂🤖

**Comment by aemelyanovff** [comment]
Fixed next release!
