### ISSUE TITLE
Sometimes there is "Choose file" section when page loads in Web

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#410]
## Expected behavior (required)
Show loader while loading and then page should load normally

## Current behavior (required)
Sometimes there is a section with an upload option is shown on the browser.

## To Reproduce (required)

This issue started to appear a month ago in my already existing project so I am not sure about the steps to reproduce it. I can only guess.

1. Add upload image action on the page
2. Host and run via firebase hosting
3. Notice the upload section showing before page loads(happens sometimes so might have to try several times).

## Context (required)

Causes bad user experience.

## Screenshots / recordings

![2023-01-25 14_00_35 864](https://user-images.githubusercontent.com/102008213/214515514-1ecd6dc7-9ce1-4ad8-9f14-2b90a72bad56.png)

## Your environment

* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Safari
* Operating system and version (desktop or mobile): All

**Comment by wenkaifan0720** [comment]
I sometimes also see this page. ✋

**Comment by Pepino-GR** [comment]
@wenkaifan0720, so how do we go forward?

**Comment by hariprasadms** [comment]
Hi, This is mostly related to server responses at times and also we do not see this issue in latest FF updates. Hence we can close the issue. we can re-open the issue if this becomes more consistent again. Thanks

**Comment by Shubham-VE** [comment]
Hi, I am still seeing this issue in the latest FF build.
