### ISSUE TITLE
Github push in desktop is not active

### ISSUE THREAD

**Issue by task-win** [FlutterFlow/flutterflow-issues#4100]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have opened an old project in Flutterflow desktop - Mac and tried to use the push to repository. It is showing - Connect with repository.
I clicked on connect and on the Github page, it does not allow me to add the github url.

I navigated to the web and did the same with the same project and was able to push. Why i could not do it on the FF-desktop .

### Expected Behavior

I should be able to push Flutterflow desktop as well.

### Steps to Reproduce

1. Go to ff desktop version of mac.
2. Try to push to repository- May be old projects
3. Connect to Github is shown
4. Navigate to page - The block symbol comes not allowing to add the github.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zuXI4Y5Om8tb46XQcPFagiIUN24/UOYs0tVraCgofePtOol3evXsSxdBcN+gT3xUP0SmmnoCptKLkvPDGMcCAyysfZxyzZNcWAvMQnq7UZOBDZO8XHZ8GexMCX640cGJkyJ7JttuLy0X1DqYffDLaATtQYT2ImdISq/LZO4=

### Visual documentation

<img width="416" alt="Screenshot 2024-10-18 at 07 26 17" src="https://github.com/user-attachments/assets/9e5a9e69-99a1-440f-9124-72626f8b949b">
![Screenshot 2024-10-18 at 07 26 00](https://github.com/user-attachments/assets/e4c0a002-9caf-4c49-a5e7-462dcd6fbbc4)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by task-win** [comment]
![Screenshot 2024-10-18 at 07 26 00](https://github.com/user-attachments/assets/85b50075-60f8-4aea-b3e2-310fd73e73d7)

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue after testing with three different projects, both old and new. All of them successfully pushed to GitHub through the macOS app. If you’re still experiencing this issue, please reach out to our support team via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io).

Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/94dc55cd-3538-4e6f-9679-96b4dac57e5e/ce9769a2-f1b7-46fc-a6a5-4fd3bb24d273?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NGRjNTVjZC0zNTM4LTRlNmYtOTY3OS05NmI0ZGFjNTdlNWUvY2U5NzY5YTItZjFiNy00NmZjLWE2YTUtNGZkM2JiMjRkMjczIiwiaWF0IjoxNzI5MjY3NjI5LCJleHAiOjMzMjk5ODI3NjI5fQ.V-nWTOcegAjcU_o5ruPL6gC7ZCox0gtw9jzlH_Rffd0 " alt="Imagen de WhatsApp 2024-10-18 a las 13.05.26_203dd271.jpg" width="1280" height="725" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
