### ISSUE TITLE
Calendar widget issues: can't choose today date, can't disable days

### ISSUE THREAD

**Issue by gspassky** [FlutterFlow/flutterflow-issues#4101]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Current date is not clickable (and no event is fired accordingly), even if the initial date is set to some other day
2. There is a styling setting for "inactive days", but no option to define which days are inactive

### Expected Behavior

1. Any active date in calendar must be clickable and date change event must be fired
2. There must be some settings to define the days which will be "inactive". For example, you can block dates before or after some date or more flexible - by using a condition

### Steps to Reproduce

1. Create new page
2. Add Calendar widget
3. Set On Date Selected event (for example, show an Alert)
4. Try to press on the current date (today) - Alert won't be shown

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjfHl34h2rsRE7c/+Y8JB/So4HEAmROdNscp8bxAbCIzrBJkAdvWlVFNoYMfgTFFMIUSmmmMx7sGKv87tCPlcNgeaGdlDzJYBUQvvfzihUZOBDpaCSEYkGe9YfHKH1qW7hwpQB7JYckVg1DiuG+uyTgvrO4y3IlFISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/ea057bbb-f8a0-4fee-924f-2ee4d2d0e55d)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Windows
- Browser name and version: Chrome Latest
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue. I was able to click the date and see an alert dialog displaying the selected date. Here are the steps I followed:

1. Added a **Calendar** widget.
2. Created a **DateTime** variable in **AppState** to store the selected date.
3. Set an action in the **On Selected Date** trigger to update the **AppState** variable with the chosen date.
4. Added an **Alert Dialog** to display the value of the **AppState** variable.

Could you double-check these steps in your setup to see if there’s anything missing?<br><br>Here is the Public Project for you to check it: [https://app.flutterflow.io/project/qa-2346-xve7u2](https://app.flutterflow.io/project/qa-2346-xve7u2)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/364886a2-b26f-44e6-a729-84db6c2b083c/f9b9a8a4-fff3-47fc-9b5b-e2d993992117?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNjQ4ODZhMi1iMjZmLTQ0ZTYtYTcyOS04NGRiNmMyYjA4M2MvZjliOWE4YTQtZmZmMy00N2ZjLTliNWItZTJkOTkzOTkyMTE3IiwiaWF0IjoxNzI5MjY4MzUzLCJleHAiOjMzMjk5ODI4MzUzfQ.kS4QfADp9Qw44ugHny0mgJJCZBisZppnFZeP6lNNmIY " alt="daySelected.gif" width="1900" height="942" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
