### ISSUE TITLE
Bolding in rich text does not work properly

### ISSUE THREAD

**Issue by brnchr0m** [FlutterFlow/flutterflow-issues#4104]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On random points bolding the rich text just makes it slightly bold (less than its supposed to) on the screen. It is visibly less than the ones that have worked when compared side to side. Further, when I actually open it on the test mode it is not bolded so it is not just a flutterflow editor issue.

### Expected Behavior

When I bold I expect the text to be... bold.

### Steps to Reproduce

1. Create a new rich text
2. Add some text spans, try bolding some. At some point it should just not bold as much as it should
3. Try copying a text from outside flutterflow and pasting it in a text span and then bolding it (not sure if this is the exact cause but might be contributing somehow)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfjPHq05NOtbwB176Ja/par2QUHEMcT4M3ktYbSS0jF7KuC+0EZ8/6PhBtXse+SmxDfGKmp14KpejLit7PFOw4JQeufIM+yqhQexXvRlGjR5eTF7qOYXFAHptRf1Cc5pjYuiYkBM9ucXgc7zn7CeqUfC/dJu/bPmo4Sq/LZO4=

### Visual documentation

<img width="889" alt="Screenshot 2024-10-18 at 10 56 37" src="https://github.com/user-attachments/assets/dd757121-9ae5-4f9c-8e36-e1cc67f04cca">
<img width="935" alt="Screenshot 2024-10-18 at 10 56 45" src="https://github.com/user-attachments/assets/4b2e1867-b421-4477-a878-46d9d912ff40">

### Environment

```markdown
- FlutterFlow version: v5.0.6
- Platform: Desktop
- Browser name and version:
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment]
Hello!

I’ve been trying to replicate the issue, but I may not fully understand it, as everything seems to be working as expected in both the Builder and Run/Test Mode. Could you record a short video (like a Loom) to explain the issue in more detail?

From what I can see in your project, everything looks fine as well.

Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f9820960-41b9-4a33-ad9e-86f955e03f9a/20cd671f-18bd-4bbe-9145-caad3c80f291?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOTgyMDk2MC00MWI5LTRhMzMtYWQ5ZS04NmY5NTVlMDNmOWEvMjBjZDY3MWYtMThiZC00YmJlLTkxNDUtY2FhZDNjODBmMjkxIiwiaWF0IjoxNzI5MjY2ODA0LCJleHAiOjMzMjk5ODI2ODA0fQ.i2ntgmZ3_yTR_n_4ZBc6RgyuWZzTghgBD1cPtWstxBg " alt="image.png" width="556" height="691" />

**Comment by brnchr0m** [comment]
Hey man I tried to send a video but gave me an error here. On my project as
I said there is literally no causation. I just add a text field and at some
point it just doesn't work

**Comment by brnchr0m** [comment]
The issue is still happening fyi
