### ISSUE TITLE
GRPD not showing any information in EU

### ISSUE THREAD

**Issue by fafa16** [FlutterFlow/flutterflow-issues#4105]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm currently using Admob on an app, the ads are loading and everything is fine except for the user consent banner for EU users. Simply not showing. I've checked the options, the 'GDPR Dialog' is enabled. I've testes on a real device. The app is also published on Play Store, but it didn't show the dialog.

### Expected Behavior

Dialog should appear

### Steps to Reproduce

1.turn on this option
2. run the app in EU

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

No bug report

### Visual documentation

![image](https://github.com/user-attachments/assets/0214b50a-b34c-4312-b65b-d22cefd54122)

### Environment

```markdown
- FlutterFlow version: latest
- Platform:App in production on store
- Browser name and version:
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment]
Hi @fafa16. Have you added a consent dialog in your Admob console (in Privacy & messaging -> European regulations, see https://support.google.com/admob/answer/10113207)?

**Comment by Sr-MDev** [comment]
> Hi @fafa16. Have you added a consent dialog in your Admob console (in Privacy & messaging -> European regulations, see https://support.google.com/admob/answer/10113207)?

That's was what i missed! There's no mention on to that in to the FF Admob doc's. Thanks @wenkaifan0720

**Comment by wenkaifan0720** [comment]
No problem! Our documentation is a little behind but we are working on adding this information soon.

**Comment by fafa16** [comment]
> Hi @fafa16. Have you added a consent dialog in your Admob console (in Privacy & messaging -> European regulations, see https://support.google.com/admob/answer/10113207)?
Hello @wenkaifan0720 
Thank you so much. I missed this configuration.It works now!!
