### ISSUE TITLE
Failure To Build

### ISSUE THREAD

**Issue by chooito** [FlutterFlow/flutterflow-issues#4109]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Project is failing to build

### Expected Behavior

I expect to be able to build my project

### Steps to Reproduce

Open Project
Select any option to build it, the all fail
![BuildError 2024-10-19 011254](https://github.com/user-attachments/assets/27a8c483-0a85-4c4e-9cb0-edc114e10fd6)
 N.B. I've never used github on my project, I'm a sole developer.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzMmB28lgobRF+KXQb+xGlWA4GUMdXOczitVEew4bCIj4BJY2PMjRSFBDTbWzaH1qe0yIjkUxpuDTj4TpLe5fKTKqfJR6/6lQbxPPbHmhbJSxEZOCQUFDL8dVCBXD4abYpiN5A7NtWUYC3XGIBtnKTT6Cf9qOYwx5e6fDbOY=

### Visual documentation

![BuildError 2024-10-19 011254](https://github.com/user-attachments/assets/af0623c4-597f-42e8-b928-115472b34c3c)

### Environment

```markdown
- FlutterFlow version: 5.05+
- Platform: Desktop
- Browser name and version: Chrome & Brave
- Operating system and version affected: Windows 10 & 11
```

### Additional Information

I cannot continue development

**Comment by q8harpoonSolution** [comment]
I am facing the same issue , 
I downloaded the code and it seems related to core library video_player_android

**Comment by chooito** [comment]
I restored my project to a previously built and working version, but the error persists. Project fails build on web 5.06+ and desktop Run Test & Download APK, Brave Browser, Chrome Browser, Windows10 & Windows 11 with the same error.

**Comment by paulperez-dev** [comment]
Hi guys, I'm looking into this!

**Comment by celiostat** [comment]
this issue happens to me too. No error indicated in FF UI, but build fails

**Comment by serenamoonx** [comment]
It's happened to me too. It was fine last night. Today there was a failure to build. Thankfully it told me the page and I found that Flutterflow deleted a necessary field (my audio path) and it was causing a build failure. I have noticed over the past couple of weeks that I make a change and Flutterflow deletes the change and I have to redo it. So I'm not surprised. Every update seems to be making Flutterflow more unstable to use.

**Comment by celiostat** [comment]
I totally second the second part '' over the past couple of weeks, when i make a change, ff deleted it and I have to redo it '' happens to me on eacb action. Very frustrating

**Comment by chooito** [comment]
Yeah this is happening to me too, started in the collection editor,  I did
a video of it, they said it was happening to a small group of people, 4
weeks later I literally can't achieve anything without doing it twice over
sometimes 3 or 4, sometimes it undoes my change and if I leave it for 30 or
40 seconds it puts it back, sometimes it doesn't. I'm 90% done with this
project but I'm starting to doubt if I'll finish it with the amount of
effort I'm now having to put in to get anything done. Won't be recommending
it anytime soon...

**Comment by celiostat** [comment]
Is there an open issue already for this one above ?

**Comment by chooito** [comment]
No I opened it originally, they said it was going to be fixed and they
closed it, but the only thing that was better was the collections editor,
since then the reversal of my actions problem has got steadily worse, I
feel like they just want to put all their effort into demoing non-sensical
AI features instead of concentrating on giving us a solid platform to
develop in. At their recent seminar that "puff" guy said he had several
pages of items causing friction, since then I've only seen it get worse.
Seems to me like we're paying to be their software testers....  It's a
great pity because if it worked properly I'd be a big advocate.

**Comment by paulperez-dev** [comment]
Hi everyone,

Could you please confirm if you are still encountering this issue? I’ve tried to replicate it but haven’t been able to do so.

Thank you!

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
