### ISSUE TITLE
Chart widget: timestamp format on X axis + "show labels" makes FF crash

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#411]
## Expected behavior (required)
Each day, the user completes a sleep journal. I record the day for which the journal was completed (timestamp variable: dateYesterday). I want to offer the users the possibility to visualize their progress across time in relation to sleep variables. To do so, I am using a chart widget. On the Y axis, I have sleepOnsetLatency, an integer variable that corresponds to the number of minutes it takes to fall asleep each day. On the X axis, I have the dateYesterday variable. 

I also have two buttons with the action "select date/time". On the first button, the user has to choose the "start date" and on the second button, they have to choose the "end date".

The chart is in a container that has a backend call. There are two filters: one filters specifies that "dateYesterday" must be greater than or equal to the selected start date, whereas the second filter specifies that "dateYesterday" must be lower than or equal to the selected end date. 

If I do not select the option "show labels" for the X axis, the widget works as expected. However, when this option is selected, the app crashes (freezes) when the user selects the "end date" with the second button.

What I am expecting is to see two dates (labels), for the beginning and end of the X axis. 

## Current behavior (required)
App freezes. 

## To Reproduce (required)
1. Create a list of documents with two fields: "dateYesterday" (timestamp) and "sleepOnseltLatency" (integer). The dateYesterday variable should be incremented by one day in each document (e.g., January 1, January 2, January 3, and so on).
2. Create two buttons: a "date start" button and a "date end" button. Each button should have a "date/time picker" action. 
3. Create a container with a backend call to the list of documents that you created. The container should have two filters. Filter 1: dateYesterday is greater or equal to "date picked 1" (the start date). Filter 2: dateYesterday is lower or equal to "date picked 2" (the end date). 
4. Insert a graph widget into the component.
5. On the Y axis, select "sleepOnsetLatency". On the X axis, select "dateYesterday". 
6. Run the app: it should work fine. Then activate the "show labels" option for the X axis: the app should crash when you select the end date.

See above.

### Bug Report Code (required, generate from Widget Tree)
N/A

## Context (required)
I can't have labels on the X axis. This is frustrating, since the user will expect to see the time interval for the X axis.

## Screenshots / recordings
Full example: https://www.loom.com/share/518ce3b208e64bc695301d0fbb48f409
Simplified example: https://www.loom.com/share/b98cd59a8176469bb841a63e0a811e68

## Your environment
Windows 11, Chrome, FF 3.3.4

**Comment by bulgariamitko** [comment]
Can you include the Bug Report Code as well please.

**Comment by Alexandre-Lemyre** [comment]
Where can I find the procedure for getting a bug report code?
Also, no "project issues" is flagged in the FF builder, the app is just crashing in test mode (as shown in the video). 

Thank you.

**Comment by bulgariamitko** [comment]
Just click on the right side of the Widget that is crashing and click Bug Report Code

**Comment by Alexandre-Lemyre** [comment]
I apologize, but I still do not understand. Do you mean "right clicking"? Also, should I do it in the developer window or in test mode? If in test mode, should I do it before or after the crash? The ideal would be to send me a screenshot or short video showing how it is done. 

Thank you.

**Comment by bulgariamitko** [comment]
There you go 
![whats-new-FlutterFlow (2)](https://user-images.githubusercontent.com/7221384/215218892-d98bdaa6-eb1f-4d64-aad6-26dd9653192b.png)

**Comment by Alexandre-Lemyre** [comment]
Thank you for the screenshot. 

Here is the bug report code for the chart widget. 

IT4KivHq389Pm8tD1aXIccdFoCYXGDsnRYIoltVDYwkbCJCsG7lzS8zRQFtoTLzhY3NAM2G0jngz1vfqjt/xE/UBFzCYc6JY1cxIYDrdTma6RqqqDsyZMS0ffaMKRSz+

**Comment by wenkaifan0720** [comment]
Hi @Alexandre-Lemyre. We have identified the source of this bug and is looking for the optimal fix for it. In the meantime, I suggest disable axis label when the data is of type `DateTime`.

**Comment by shelpert** [comment]
Hello, unfortunately right now labels are not supported with datetime data on line charts. We have plans to update this as an option in the future, but it requires more work than a simple bug fix. I recommend using bar charts instead, as those labels can be whatever you want them to be!
