### ISSUE TITLE
Banner ads not loading on iOS

### ISSUE THREAD

**Issue by Gorgon-Cyber** [FlutterFlow/flutterflow-issues#4110]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Banner ads are loading perfectly on Android, but get stuck on "Ad Loading.." on iOS. This behaviour blocks my app from being approved by Apple for the App Store. I am not the only one with this issue. Please also see here:

https://community.flutterflow.io/ask-the-community/post/ad-loading-admob-IjZXl3e8fNHpqlm

and the same here:

https://community.flutterflow.io/ask-the-community/post/admob-ads-not-showing-ads-on-ios-stuck-on-ad-loading-woRj5JaQzY72oi2

As you can see below, adMob shows that my requests are coming through, but there are zero impressions:

![image](https://github.com/user-attachments/assets/b46ab2c9-5816-4619-a218-734f04faa4b1)

This proves that my configuration is correct within FlutterFlow. The only thing that I have been able to find that looks strange in the code when downloaded from FlutterFlow is that the plist.info file only contains a single entry:

![image](https://github.com/user-attachments/assets/c1439543-37c9-47ba-9b49-c9807bd412ed)

Whereas Google has a rather extensive list that supposedly needs to be in there, as discussed here:

https://developers.google.com/admob/ios/quick-start

I don't know if that info.plist information is helpful, but at the moment it is all I have. 

### Expected Behavior

The banner ads should load on iOS. They load in test mode, but not for real ads.

### Steps to Reproduce

1. Set up an iOS ad unit within adMob
2. Create an App within the App Store
3. Set the required App Store keys and identifiers in the Mobile Deployment settings of a new project.
4. Add an adMob banner widget to the project home page
5. Perform all the required steps to set the right iOS values in the project settings and against the banner as outlined in the FlutterFlow documentation
6. Deploy App to the App Store from within FlutterFlow
7. Test App with TestFlight
8. Ads do not load

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESzM+A+ZRgof5J7anUKe5qhQIkJlgMUIJIl9Vxax4bIrWrP5oMd8nCQ0NKTbCcdGx6A060glgGpcmPvofDE/Y5F0iaGKpC0JVAUTzvWkahVbaYOriddHx8AtJnJna+1MPZkR57CPB2R3gj12axNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/6fb6c601-4b77-4b63-9afc-c799a86163b4)

### Environment

```markdown
- FlutterFlow version: 5.0.6
- Platform: iOS Mobile Deployment
- Operating system and version affected: iOS, all versions
```

### Additional Information

This issue blocks my app from being approved by Apple for the app store. It has effectively put my project on complete hold. Here is the report from Apple:

![image](https://github.com/user-attachments/assets/575a8042-5edf-4a6e-8421-d7a5ffbef707)

**Comment by Alezanello** [comment]
I’ve reviewed your project code, and everything looks correct on our end. The issue seems to be related to AdMob not retrieving your ads as expected. I recommend checking the AdMob Developer forum or reaching out to their support team for further assistance: [https://groups.google.com/g/google-admob-ads-sdk](https://groups.google.com/g/google-admob-ads-sdk).

**Comment by Gorgon-Cyber** [comment]
Hi Alezanello, thanks for checking. However, it would appear that everything is correct on the adMob side too. The one thing that really bothers me is the complete absence of SKANetworkIdentifiers in the info.plist file. The Apple and adMob documentation is very clear that unless the full approved list is provided, adMob advertisers will not be able to track attributions and can deprioritize my ads to the point where ads will not show. Which would appear to be happening here.

The info.plist file provided by FlutterFlow in /ios/Runner contains only the single entry I listed above. According to Google, info.plist **must (or at least should)** contain all the items listed below, which is substantially different. So unless FlutterFlow does some magic and completes the file correctly on Deployment (unfortunately I don't know how I can check that), the lack of identifiers in this file can result in poor revenue and failed adMob impressions according to both Apple and Google. So can you at least please confirm if FlutterFlow includes all the below identifiers upon deployment to the App Store?

`
<key>SKAdNetworkItems</key>
<array>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>cstr6suwn9.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>4fzdc2evr5.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>2fnua5tdw4.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>ydx93a7ass.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>p78axxw29g.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>v72qych5uu.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>ludvb6z3bs.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>cp8zw746q7.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>3sh42y64q3.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>c6k4g5qg8m.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>s39g8k73mm.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>3qy4746246.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>hs6bdukanm.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>mlmmfzh3r3.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>v4nxqhlyqp.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>wzmmz9fp6w.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>su67r6k2v3.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>yclnxrl5pm.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>7ug5zh24hu.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>gta9lk7p23.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>vutu7akeur.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>y5ghdn5j9k.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>v9wttpbfk9.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>n38lu8286q.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>47vhws6wlr.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>kbd757ywx3.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>9t245vhmpl.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>a2p9lx4jpn.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>22mmun2rn5.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>4468km3ulz.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>2u9pt9hc89.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>8s468mfl3y.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>ppxm28t8ap.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>uw77j35x4d.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>pwa73g5rt2.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>578prtvx9j.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>4dzt52r2t5.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>tl55sbb4fm.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>e5fvkxwrpn.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>8c4e2ghe7u.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>3rd42ekr43.skadnetwork</string>
  </dict>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>3qcr597p9d.skadnetwork</string>
  </dict>
</array>`

**Comment by Gorgon-Cyber** [comment]
I should probably add that we are a Linux shop. We're doing this project as a charity for a friendly customer. We do not have MacBooks, so we can't debug this issue outside of FlutterFlow, and FlutterFlow does not offer any way to obtain error messages from the adMob SDK. So this is a true no-code situation. We can't add or check any of the code before it hits the App Store.

**Comment by Gorgon-Cyber** [comment]
Hi Alezanello, I've now figured out why the ads are not loading and why I couldn't get the app approved. My ads are now finally loading and have been approved by Apple after I hacked the FlutterFlow banner implementation through deployment via Github instead of the normal approach. I've submitted it as a feature request, but I'm also asking if you are interested in the details on this entry? There's definitely several misconfigurations and bugs with respect to the FlutterFlow banner ad widget and the launch of a new app with the app store.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!

**Comment by MickaMalko** [comment]
What remains incredible is that the author of the post must have figured it out on their own to find a solution, tinkering and leaving it to chance. It worked by some strange magic, so the response was, 'Hop, it's good, everything works for you!!! We’re closing your topic!!! Hihaaaa!' While absolutely no one understood anything. So if someone encounters the same problem, they will have absolutely no solid foundation for solving it.

**Comment by Ajris** [comment]
@Gorgon-Cyber can you please provide the info of how did you resolve it?

**Comment by Gorgon-Cyber** [comment]
Sure Hubert @Ajris,

I exported my project to github (see https://docs.flutterflow.io/exporting/push-to-github/), and added the info.plist entries shown above to get all the ad networks. Then I also made the following modifications:

/android/app/build.gradle - I changed the signing key to be .release. This only matters for Android, but I needed both:

![Image](https://github.com/user-attachments/assets/515056f0-fe3a-48c5-a194-723b8626f138)

/flutter_flow_ad_banner.dart - I commented out the "Ad Loading" part of the widget:

![Image](https://github.com/user-attachments/assets/50f67853-4825-4ce4-bd2a-a332dabe3736)

I did this, because the App Store will not approve an app with a page that says "Ad Loading..". Apple considers this bad UX and rejects it. The above modification only shows the ad when it is available and Apple approves that just fine. 

Once everything is in Github, you need to fix the version number and can build and deploy from within FlutterFlow. See this article: https://docs.flutterflow.io/deployment/deploy-from-github/

That allowed me to get the App listed in the App Store and I could go ahead and get the AdMob approvals to show ads. After that, things came to life (although it took a couple of weeks to get the full sets of ad impressions from AdMob - it eventually did happen).

Good luck!

**Comment by Gorgon-Cyber** [comment]
@MickaMalko - good point. I've added the solution as requested by Ajris.
