### ISSUE TITLE
"Minus" sign without spaces breaks code expressions

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#412]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Projects with code expression must build.

## Current behavior (required)

Using the "-" sign breaks code expressions in some cases.

## To Reproduce (required)

1. Create new page
2. Add new page parameter `intParam`, type Integer.
3. Add text widget
4. Set its value from Variable/Code Expression.
5. Add 2 arguments, var1 and var2, set them both from `intParam`.
6. Set return type = Integer.
7. Set expression: `var1-var2`
8. Click check errors. Observe that it says "No Errors".
9. Observe the preview. It shows `var1-var2`. Expected: `widget.intParam-widget.intParam`
10. Save the variable. Try building the code.
11. Observe that it fails with `Undefined name 'var1'`

Also observe that it builds if you:
- Replace the `-` with a `+`: `var1+var2`
- Add spaces: replace `var1-var2` with `var1 - var2`.

### Bug Report Code (required, generate from Widget Tree)

ITESi8rqx5Vgrstf1rXxK8JqhR4jNlx7bZNEmsFTRQoYJZj2PYwpWs7CYmdVOdene2xiBWL9nj0E0fz7iuLLEfpeBEDDJ+AHl/E0LlSrGAc=

## Context (required)

Code expressions not working, project not building.

## Screenshots / recordings

![Screenshot 2023-01-26 at 7 20 00 PM](https://user-images.githubusercontent.com/92294640/214979459-c1c634d1-099d-412b-8f95-e8ee47ea6aa0.png)

## Your environment

* Version of FlutterFlow used: January 25, 2023
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by wenkaifan0720** [comment]
Hi @aemelyanovff. I have pushed a fix for this. Nice catch!
