### ISSUE TITLE
flutter flow util datetimeformat not honoring locale

### ISSUE THREAD

**Issue by jeanseb29** [FlutterFlow/flutterflow-issues#413]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

need to be able to format date time using locale but there is no option in text formatting to pass the locale and the function itself would not be using it  : String dateTimeFormat(String format, DateTime? dateTime, {String? locale}) 

## Current behavior (required)

String dateTimeFormat(String format, DateTime? dateTime, {String? locale}) {
  if (dateTime == null) {
    return '';
  }
  if (format == 'relative') {
    _setTimeagoLocales();
    return timeago.format(dateTime, locale: locale);
  }
  return DateFormat(format).format(dateTime);
}

## function changed to at least support locale
//getting local from app locale then added optional ,locale to the DateFormat call

String dateTimeFormat(String format, DateTime? dateTime, {String? locale}) {
  locale = FFLocalizations.getStoredLocale().toString()??'fr';
  print('ttt');
  print(locale);
  if (dateTime == null) {
    return '';
  }
  if (format == 'relative') {
    _setTimeagoLocales();
    return timeago.format(dateTime, locale: locale);
  }
  return DateFormat(format,locale).format(dateTime);
}

Cheers,

**Comment by Pepino-GR** [comment]
Hi jeanseb29,

we do FlutterFlow issue support in our issue tracker.(not Developer support). You have provided only code segments inside your issue description. Maybe we have to use it as a Feature request?
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by jeanseb29** [comment]
Hi, sorry this code is coming from your code it is the dateTimeFormat function in flutter_flow_util.dart it seems I missed to specify it when I opened the issue.
it has an optional locale parameter which can't be added in the UI  which would be one aspect of the issue
and a bug in the function itself as this local parameter is then not used when calling the DateFormat function

**Comment by Pepino-GR** [comment]
Can you please show me, in which context or widget do you use it?

## To Reproduce (required)


Steps to reproduce the behavior:
1.
2.
3.
4.
