### ISSUE TITLE
FlutterFlowDropDown does not update to show new value

### ISSUE THREAD

**Issue by TzuTech** [FlutterFlow/flutterflow-issues#414]
## Expected behavior (required)
The FlutterFlowDropDown should update its value when its initial value property is updated.

## Current behavior (required)
The DropDown's Initial Option Value is set to a Local State Variable. When the local state variable is updated, the dropdown does not update to reflect the variable's new value.

## To Reproduce (required)

1. Create a custom function that returns a random number within the range of options that will be available to the dropdown.
2. Add a button with an action to call the custom function and use the value to update a local state variable that will be read by the dropdown. Set update type to **Rebuild All Pages**
3. Add a dropdown with a set range of options. The initial option value should read from the local state variable.

Setup:

![image](https://user-images.githubusercontent.com/122278327/215163256-63744b4d-8c59-4c6c-81d1-843425abce6e.png)

4. Click the button on the left. The dropdown will not update to the value of the local state variable.

## Bug Report Code
IT4oz/LlsYtIsdhE7c/QacFvryQ7NV98R7gJkcpBay0jF7KuDLMqY8/RVERWXbzjYFZEfGD9p2oW0dLXi+D1U8E5NQyZfNg++Kl6UAuVWnuQV82bU/HUACkbeacOQSj6

## Context (required)
The goal is for the randomizer button to return a number and then set the value of the dropdown to the corresponding number.

## Your environment
* Version of FlutterFlow used: V3.0 January 25, 2023 - Flutter 3.3.4
* Platform: Web, iOS 
* Browser name and version: 
* Operating system and version (desktop or mobile): macOS and iOS

**Comment by bulgariamitko** [comment]
Can you please add the bug report as well?

**Comment by TzuTech** [comment]
@bulgariamitko unfortunately, the app is not throwing any errors so I'm not able to provide a bug report. Or at least I am not finding it. I did, however, capture a screen recording showing the behavior. The layout is as follows:

- Left chevron decrements a local state variable called **defaultPassageNumber**
- The 4 is in a **TextFormField**. I removed the dropdown as I had to move on, hoping that the "bug" would not be present on the **TextFormField**. Unfortunately it is.
- Right chevron increments **defaultPassageNumber**
- The 6 is a **Text Widget** that reads defaultPassageNumber.
- Then comes the randomizer button
- Finally a button for bookmarks.

https://user-images.githubusercontent.com/122278327/215369783-fb9d0b7e-6e92-4da6-9440-3c3772a9e868.mov

As you can see in the video, decrementing, incrementing, and randomizing **defaultPassageNumber** clearly works as the Text Widget correctly updates to the new value. The **TextFormField**, however, never updates. The only way to have it update is by moving to another tab and then returning. As seen here:

https://user-images.githubusercontent.com/122278327/215371143-d98052c2-d1d3-4c0c-8358-241b25b76f03.mov

Given that I cannot provide a bug report, would it be helpful if I provide with access to the project or project Id?

Un fortunately, there is no way we can rollout the app until this is sorted or we find a workaround.

Thank you so much for helping me look into it.

**Comment by bulgariamitko** [comment]
Thank you for your post. Sorry I was not clear enough. You need to provide Bug Report Code this is how you can get it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)

**Comment by TzuTech** [comment]
@bulgariamitko  Thank you for that. Here it is:

IT4oz/LlsYtIsdhE7c/QacFvryQ7NV98R7gJkcpBay0jF7KuDLMqY8/RVERWXbzjYFZEfGD9p2oW0dLXi+D1U8E5NQyZfNg++Kl6UAuVWnuQV82bU/HUACkbeacOQSj6

I also updated the issue description to help out with readability.

**Comment by TzuTech** [comment]
@bulgariamitko I keep running into this issue throughout different features of the app I'm working on. 

Do you have any suggestions on how to work around this issue? Or do you know what's the likelihood of this issue being resolved in the short term?

**Comment by bulgariamitko** [comment]
@TzuTech Unfortunately I can't give you a date when this issue will be fixed. But I can give you a few ideas you can try.  You can try to implement to update your local state in the code itself and update the value of the dropdown from the local state itself. 

This is a demo code how you can do that 

FFAppState().update(() {
  FFAppState().foo = bar;
});

**Comment by TzuTech** [comment]
@bulgariamitko, if I call the text property of the controller directly, it works:

```
FFAppState().update(() {
  FFAppState().defaultPassageNumber =
      subtractedPassageNumber!;
  chapterTextFieldController?.text =
      FFAppState().defaultPassageNumber;
});
```

I do not, however, want to lose the ability to deploy from the FF dashboard. If I create a custom action, could I somehow pass the controller and update from there?

**Comment by bulgariamitko** [comment]
@TzuTech I don't think you can do that :/

**Comment by TzuTech** [comment]
All right. Good old coding it is.
