### ISSUE TITLE
"Item at Index" list operations not working on API responses

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#415]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

"Item at Index" list operations work on API list responses.

## Current behavior (required)

Generated code fails to compile.

## To Reproduce (required)

1. Create new API endpoint. API URL = https://api.sampleapis.com/coffee/hot
2. Test the API call. Add JSON Path = `$..title`, call it "title". Observe a list of strings in "Response Preview".
3. Create a new page.
4. Attach a backend query calling this API to the Scaffold.
5. Add new text widget.
6. Set from variable: JSON Body -> JSON Path -> Title -> Item at Index -> First.
7. Save
8. Try building the project. Observe that it fails to compile with `The getter 'first' isn't defined for the type 'String'.
Try importing the library that defines 'first', correcting the name to the name of an existing getter, or defining a getter or field named 'first'.`

The generated code looks like this:
```dart
Text(
  CoffeeCall.title(
    page2CoffeeResponse.jsonBody,
  ).toString().first,
  style: FlutterFlowTheme.of(context).bodyText1,
),
```
The `.toString()` should not be there.

### Bug Report Code (required, generate from Widget Tree)

ITESi8rqx5Vgrstf1rXxK8JqhR4jNlx7bZNF0OsbawkgNbHmO5wpWvv7fmZdZ+mzfHNffVKbo3w1wdL9i+DtIfVfIkDDJ+AHl/E0LlSrGAc=

## Context (required)

Can't use list operations on API responses.

## Screenshots / recordings

![Screenshot 2023-01-27 at 7 04 40 PM](https://user-images.githubusercontent.com/92294640/215228273-09a83c59-d663-4175-a9a5-4315f677476d.png)

![Screenshot 2023-01-27 at 7 07 57 PM](https://user-images.githubusercontent.com/92294640/215228300-5dc70178-c046-4b6b-a44f-337fef5feea6.png)

## Your environment

* Version of FlutterFlow used: January 25, 2023
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by agreaves** [comment]
Fixed next deploy! 🙂
