### ISSUE TITLE
Badge Widget Causing Builds to Fail

### ISSUE THREAD

**Issue by strongishdeveloper** [FlutterFlow/flutterflow-issues#416]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Successful build when using the Badge widget

## Current behavior (required)
My build is now throwing the following error:

`
lib/staff_asset_list/staff_asset_list_widget.dart:158:28: Error: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.
                    child: Badge(
`

This page has remained unmodified, and builds were successful with the exact Badge widget, only started failing today.

## To Reproduce (required)

1. Create new page
2. Add a Badge widget to App Bar
3. Push to Github
4. Rebuild app in Codemagic
5. Observe that project doesn’t build

### Bug Report Code (required, generate from Widget Tree)

IT4Cl8iBx5NItbxa1s+JbsFFoDgXHEQjRY0viNV+RUkdDZPRD7MAZPekUERCYOKqYAk/PWGGhWoW0NqPkuH9KfQoPQesG6pyzrp9WgyXTn+meLauU/HUACkbeacOQSj6

## Context (required)

Unable to build app

## Screenshots / recordings

![Capture](https://user-images.githubusercontent.com/71303826/215304880-456c2ab4-d270-418a-8357-2afbac98720f.PNG)

## Your environment

* Version of FlutterFlow used: 3.3.4

**Comment by wenkaifan0720** [comment]
Hi @strongishdeveloper. This is due to the recent Flutter 3.7 update which introduces a built-in `Badge` widget that conflicts with the current `Badge` widget FF uses. I have pushed a fix for this. Thank you!
