### ISSUE TITLE
Variables in api groups do not work

### ISSUE THREAD

**Issue by oliverweaver** [FlutterFlow/flutterflow-issues#417]
If you create an API group, you should be able to use variables in it, for example Bearer tokens in headers, or simply url variables as the api groups' base url.

Despite this dynamic variables do not work in API groups, but they do in API requests. For example, if you specify [apiUrl] in the base url of an API group and define this variable in an API request, it will not work. It will work in flutterflow's built-in API tester, but in the browser's element inspector, for example, you may notice that it sends the request to [apiUrl]/test endpoint instead of https://testapi.com/test.

To Reproduce:
1. Create new api group
2. Define a variable as a parameter (for example, the base url as [apiUrl])
3. Click Run
4. Observe that the api requests won't work, because it does not replace the variable with it's value, but instead the name of the variable itself

* Version of FlutterFlow used:  V3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome Version 109.0.5414.120 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 10 Pro desktop

**Comment by hariprasadms** [comment]
Hi @oliverweaver - Thank for sharing the issues details. 
Looks like you are trying to use variables at group level not at individual requests level ( Correct me If I am wrong).
 In FF, at the moment, variables can be defined at individual but not at group level. The variables are to pass dynamic values to api endpoints at individual endpoints level in run time. Considering base url remains same for most the endpoints, having variables at base-url level does not give more benefits. I hope this explanation helps you. Let me know if you need more informations.

**Comment by hariprasadms** [comment]
Hi, @oliverweaver - I just updated by earlier comment to give more details. Let me know if you need more details. Thanks
