### ISSUE TITLE
List type variables not visible to pass the data from a page

### ISSUE THREAD

**Issue by hariprasadms** [FlutterFlow/flutterflow-issues#42]
## Expected behavior (required)
Users should be able to define list type variables and while passing the data from another pages, variables should be visible to select and pass the data. 

## Current behavior (required)

Where pages got list type variables, the data ( list type ) is not able to pass to the page from another page as variables are not showing up. This happens only when page got variables with list type.

## To Reproduce (required)

1. Create Page1 and Page 2
2. Define a variable with list type in Page 2. Example List<String> names; 
3. From Page1 add a 'navigateTo' action to Page 2.
4. Try to pass the data to variable name - 'names' from Page2 -
At this point, you can see the variable name 'names' not showing up to pass the data. Now, you can change the 'names' variable type from list to just normal type. then you can see variable start showing up. 

## Context (required)
Not able to define list type variables and pass the data from pages.

## Screenshots / recordings
https://drive.google.com/file/d/1FfT5NuqcNwPAWr6G9UTja8yDCqxbPiY4/view?usp=sharing

## Your environment
* Version of FlutterFlow used: **v3.0 October 17 - flutter 3.34**
* Platform (e.g. Web, MacOS Desktop): **Web editor**
* Browser name and version: **Chrome Incognito mode**
* Operating system and version (desktop or mobile): **MacOS**

**Comment by hariprasadms** [comment]
Hello, This issue is happening consistently for me. Please re-test and confirm.

**Comment by agreaves** [comment]
Fixed!
