### ISSUE TITLE
Variables in Headers on API Group is not recognized

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#420]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The variables on Headers should be recognized

## Current behavior (required)

When the API is tested on FF editor is working fine, but in the test or run mode is not working (See the screenshots)

## To Reproduce (required)

1. Go to Supabase and copy the anon public key
2. Create a Local State and paste it as default value
3. Go to API Call and create a group
4. Set the variable in the header

![image](https://user-images.githubusercontent.com/36147203/215396123-3bdbe7f8-fea4-4f74-b9e7-1e7433d11547.png)

5. Create the variable on the API Call
![image](https://user-images.githubusercontent.com/36147203/215396177-4aa5ee59-47f7-4bf8-8d39-8235415cec54.png)

6. You can test pasting it the anon public key
![image](https://user-images.githubusercontent.com/36147203/215396272-ae0ddc4a-3822-4702-94c0-82ea2c704704.png)

7. Now run a test and doesn't work

### Bug Report Code (required, generate from Widget Tree)

IT4gkPHlz5R2rsRE7ZPud+9VvGI7JlB8U5c0st5Hd0gdCOPrBu0AY8n8SFpuZNeraVNfelD8hlof08LKk+PLGsACPkiafbZk/8x6bznQKTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)

I want use Local State to store the api key but using API Group Calls

## Screenshots / recordings

Using API Group
![image](https://user-images.githubusercontent.com/36147203/215396934-8028a480-c128-442c-a093-afb2813cdd3d.png)
Using API Call
![image](https://user-images.githubusercontent.com/36147203/215395755-58668065-f40a-4867-8896-7d37a239b38f.png)

## Your environment

* Version of FlutterFlow used: 26 January
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 109.0.5414.120 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 Pro - 22H2 - OS build: 22621.1105

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Thanks for sharing the issues details. 

In FlutterFlow, at the moment variables can't be used at group level. It can be used at individual request endpoints level. 
I would suggest, keep base url and not changing headers details are at group level. Anything changing or dynamic values define them in individual requests so that it can keep api configurations easy and simple. 
I hope it can help you to achieve what you are expecting.

Let me know if you need more details.

**Comment by hariprasadms** [comment]
Hi @Franco98404, I just double checked the issue and i can re produce it in my projects. I have updated my earlier comment. Marking the issue as bug. Thanks

**Comment by aemelyanovff** [comment]
Duplicate: https://github.com/FlutterFlow/flutterflow-issues/issues/229
