### ISSUE TITLE
ChoiceChip value set to Local State, when Local State changes to another ChoiceChip option, ChoiceChip selected doesn't change

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#422]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
ChoiceChip value set to Local State, when Local State changes to another ChoiceChip option, ChoiceChip selected should change

## Current behavior (required)
ChoiceChip value set to Local State, when Local State changes to another ChoiceChip option, ChoiceChip selected doesn't change

## To Reproduce (required)
1) Create new page
2) Put ChoiceChip with values "Option 1" and "Option 2"
3) Set ChoiceChip to Local State
4) Create 2 buttons "Button 1" and "Button 2"
5) Set up "Button 1" to change Local State to "Option 1" and corresponding action for "Button 2"
6) Click the buttons. Local State changes but ChoiceChip selected doesn't.

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1) Create new page
2) Put ChoiceChip with values "Option 1" and "Option 2"
3) Set ChoiceChip to Local State
4) Create 2 buttons "Button 1" and "Button 2"
5) Set up "Button 1" to change Local State to "Option 1" and corresponding action for "Button 2"
6) Click the buttons. Local State changes but ChoiceChip selected doesn't.

### Bug Report Code (required, generate from Widget Tree)
1) Create new page
2) Put ChoiceChip with values "Option 1" and "Option 2"
3) Set ChoiceChip to Local State
4) Create 2 buttons "Button 1" and "Button 2"
5) Set up "Button 1" to change Local State to "Option 1" and corresponding action for "Button 2"
6) Click the buttons. Local State changes but ChoiceChip selected doesn't.

## Context (required)
Cannot let user see what they have previously chosen

## Screenshots / recordings
Please see https://community.flutterflow.io/c/discuss-and-get-help/how-to-set-choicechip-from-local-state#comment_wrapper_15261109

have discussed this at length with Koushik Vaidhinathan and Dimitar Klaturov 

## Your environment

* Version of FlutterFlow used:  3.3.4
* Platform (e.g. Web, MacOS Desktop):  web
* Browser name and version:  chrome latest
* Operating system and version (desktop or mobile): mac latest

**Comment by bulgariamitko** [comment]
Can you please provide a Bug Report Code as well. Thank is how you can create it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)
