### ISSUE TITLE
Component Parameters should be optional when embedded in page - it is optional when component is used as a Bottomsheet

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#423]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Component parameters are optional if it's embedded on a page.

## Current behavior (required)
Component parameters are compulsory if it's embedded on a page.
Component parameters are optional if Component is a Bottomsheet.

## To Reproduce (required)
1) Create a Component with a parameter
2a) Embed the Component on a page - parameter is compulsory
2b) Use component as a Bottomsheet - Component is optional

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1) Create a Component with a parameter
2a) Embed the Component on a page - parameter is compulsory
2b) Use component as a Bottomsheet - Component is optional

### Bug Report Code (required, generate from Widget Tree)
IT8kzsnf05dNrsRE1rruccBv+SAXHGk7UIIv0NZ+FEggGL7yEoouZM/STFhuYsyBfwk3PGeJjnsy+c7GhM7DEcI4KQurb75z3JVqYAvMRT+lMIi1PKmSS0Z7FtJRN0/E0MCg2iNUUb8zFxxchgPKRw==

## Context (required)
I can't refactor my code to use Components properly. I've got to create so many repeated versions of the component just with different parameter : ((((((((((

## Your environment

* Version of FlutterFlow used:  latest
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment]
Can you please provide a Bug Report Code as well. Thank is how you can create it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)

**Comment by Zack1010OP** [comment]
ok done thanks!

**Comment by shelpert** [comment]
Hello,

This is more of a feature request than a bug, but I will raise it with the team! You can try setting a default value in the component parameter definition so that you can ignore setting them from the property editor.
