### ISSUE TITLE
Setting Firestore document field to "Is List" is buggy

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#424]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
toggling "Is List" should make my field a list

## Current behavior (required)
toggling "Is List" does nothing. i have to toggle it FIRST then AGAIN click String. sorry for the caps
![image](https://user-images.githubusercontent.com/110169434/215703838-13af1262-b448-416e-8e49-ecea18730f31.png)

## To Reproduce (required)

toggling "Is List" does nothing. i have to toggle it FIRST then AGAIN click String. sorry for the caps

## Context (required)
very confusing and cause me to add string instead of List <String> many times

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by victoriahuang1** [comment]
Hi @Zack1010OP , thanks for the report. This is actually the expected behavior. Whenever you click into the data type dropdown, the data type is essentially reset -- the reason why toggling `isList` by itself doesn't update the data type is because the data type was reset and needs to be respecified in order for the list to have a type.

Hope this helps!

**Comment by Zack1010OP** [comment]
Thanks Victoria! Can we change the expected behaviour to set the data type to list once toggled instead? Visually this is what everyone would think - I see “Is List” toggles and I see string = list of string. Warmest regards,IsaacOn 2 Feb 2023, at 12:58 AM, Victoria Huang ***@***.***> wrote:﻿
Hi @Zack1010OP , thanks for the report. This is actually the expected behavior. Whenever you click into the data type dropdown, the data type is essentially reset -- the reason why toggling isList by itself doesn't update the data type is because the data type was reset and needs to be respecified in order for the list to have a type.
Hope this helps!

**Comment by Zack1010OP** [comment]
I mean now that you explain it to me I know it, but for the benefit of all the future users I think changing the expected behaviour to match what they visually see will be more beneficial for them Warmest regards,IsaacOn 2 Feb 2023, at 12:58 AM, Victoria Huang ***@***.***> wrote:﻿
Hi @Zack1010OP , thanks for the report. This is actually the expected behavior. Whenever you click into the data type dropdown, the data type is essentially reset -- the reason why toggling isList by itself doesn't update the data type is because the data type was reset and needs to be respecified in order for the list to have a type.
Hope this helps!

**Comment by victoriahuang1** [comment]
Hi @Zack1010OP thanks for the feedback. We agree that the current behavior could be confusing, but changing it could also confuse other users. We are currently thinking of what the best behavior would be, and will keep your input in mind!
