### ISSUE TITLE
Can not deploy to android as soon as I add adMob

### ISSUE THREAD

**Issue by amosvizer** [FlutterFlow/flutterflow-issues#4242]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a fairly large and complex project. everything is working fine and deploys perfectly.
Deploy to android no longer works once I add the keys to adMob (hence the dependency is added by flutterflow (as it should)).
Even if I dont add any pages that include the adMob functionality. 
I tried it on a smaller project, there was no issue adding adMob.
The issue is that adMob significantly increases the required heap memory during the aab build. 
without adMob it requires about 1,750mb
with adMob, it increases to 7,700mb and fails.
I tired setting org.gradle.jvmargs to any value between -Xmx4608m to -Xmx12288m in gradle.properties and deploy using github but it seems that the max memory is locked to 2gb by some sort of a flutterflow override value. 

### Expected Behavior

adding adMob should not break the deployment...

### Steps to Reproduce

1. take any large project where deployment to android play store works
2. add adMob keys to it
3. deploy to play store again
4. it will fail with a message stating 'out of memory'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8/134ZOm7xc1q6JY+5vgmMUJmUcTL4zlO1HcxAYGO/yPbJ/PM/BQBBWUu2qY3lhHE6YoDsd06Hnv+HpJsBeByedc75Sys8NahXNQXq8RYSyPruNdXBBBfFYN36a36uJoCRNPbJicXw87FOAFeyvbATqJ5+/Zwh9f6PHaOI=

### Visual documentation

build prior worked perfectly. only added adMob and here is the relevant part of the build output

JVM Memory Info during Release Build:
Max Memory: 2048 MB
Total Memory: 2048 MB
Free Memory: 843 MB
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR:R8: java.lang.OutOfMemoryError: Java heap space

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete
   
   

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: Win 11
- Browser name and version: edge
- Operating system and version affected:
```

### Additional Information

Help  , urgent... I can not deploy my final app to the play store

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. For cases like this, please reach out to our support team through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They have the right tools to help find a solution for your issue.

This GitHub Issue Tracker is primarily for bugs that can be replicated in a new, blank project, and your issue seems to be more specific to the size and complexity of your project.
