### ISSUE TITLE
Can't access or save lottie files. 

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#4246]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Firstly I used to have several Lottie files but many are gone. If I try an load a Lottie file as an asset the lists is empty even though I have uploaded some. The upload icon does not work either. 

### Expected Behavior

To be able to select Lottie assets. 

### Steps to Reproduce

Create Wrap
Create container
Create Lottie Animation
Select Lottie. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YuQs+lVBJtXdOQTFZiPVqWmnsypq3Zktn1CscFG0+Cf7Vq3bVITQzKe3y6aJSbPpaoRHQkHf5jGW7D5Ku42Ax9FMRhZUIQ3VyPN9mvbAnUQrq2NjMwDcikCKTXjFGpLHnBFDhU0idecCfn

### Visual documentation

![image](https://github.com/user-attachments/assets/0eae9b9b-440d-49b4-ade4-bdff71605e5c)

### Environment

```markdown
- FlutterFlow version: latest Desktop
- Platform: Desktop Windows
- Browser name and version: Chrome latest
- Operating system and version affected: Windows and web
```

**Comment by paulperez-dev** [comment]
Hi @charliefabley,

I wasn’t able to reproduce the issue on my end. Could you please check if there’s a new desktop version available and try again? If the issue persists, it would be helpful to test it on an empty project and let me know how it behaves.

Thanks for your help!

**Comment by serenamoonx** [comment]
My lottie files are gone too. They are in my library. But i can't access them from the widget. They appear to not exist. Flutterflow has dropped the ball on lottiefiles. My issue from a month ago still hasn't been fixed and it's only getting worse.

**Comment by nunezal** [comment]
I'm having the same problem with a new project on a newly downloaded desktop app. FlutterFlow won't let me change the Lottie animation.

**Comment by paulperez-dev** [comment]
Could you please try reimporting the library and check if that resolves the issue? Also, please share your current version and share a video if possible.

**Comment by nunezal** [comment]
@paulperez-dev Not sure what you mean by reimport the library. But here's a video and a screenshot of the version I'm using.
<img width="283" alt="Screenshot 2024-10-25 at 2 05 01 PM" src="https://github.com/user-attachments/assets/4420af89-d29e-4780-9faa-d9d80289bb71">
[Screen Recording 2024-10-25 at 2.02.18 PM.zip](https://github.com/user-attachments/files/17521762/Screen.Recording.2024-10-25.at.2.02.18.PM.zip)

**Comment by rzambroni** [comment]
Hi @Nunezal,

Apologies for the delayed response on this – it seems this one slipped through the cracks, but we’re working to catch up now.

Could you confirm if this issue is still occurring on your end?

I attempted to replicate the issue but wasn’t able to. Just to confirm, are you using .json-based Lottie files?

If the issue persists, you might try deleting and re-adding the Lottie widget to see if that resolves it. Alternatively, deleting and re-adding the asset itself could also help.

Let me know how it goes, and thanks for your patience!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
