### ISSUE TITLE
`Test Function` is not working as expected.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#425]
## Expected behavior (required)

- The test function should work as expected in the custom function editor.

## Current behavior (required)

- It produces errors and gives a wrong result.

## To Reproduce (required)

- I don't know how to reproduce. It's just happening one of my project.
- I created the same function in a new project and tested it. It's working fine.
- Here is the code and see the video below.
```dart
int pageOffset(
  int? page,
  int limit,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  page ??= 1;
  if (page < 1) page = 1;
  page = page - 1;
  return page * limit;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

N/A

## Screenshots / recordings

https://user-images.githubusercontent.com/5080329/215751010-342f95b4-f677-4e8c-bebc-af7ab81f4ec0.mp4

## Your environment

* Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by mravani2** [comment]
@aemelyanovff Is there any workaround for this?

**Comment by bulgariamitko** [comment]
Use Custom Action instead :dango:

**Comment by aemelyanovff** [comment]
> @aemelyanovff Is there any workaround for this?

Not that I know of. Well, short of removing/commenting out functions that use `FirebaseFirestore` while testing other functions.

**Comment by bulgariamitko** [comment]
@aemelyanovff , if you add a document as an argument will that not add FirebaseFirestore in the custom function and you should be able to use it?

**Comment by aemelyanovff** [comment]
In today's release we fixed tests failing when a different function uses `FirebaseFirestore`.
