### ISSUE TITLE
Accept-Encoding: gzip, deflate

### ISSUE THREAD

**Issue by hmesfin** [FlutterFlow/flutterflow-issues#426]
Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Return API GET requests with **_Accept-Encoding: gzip, deflate, br_** header parameter.

## Current behavior (required)
Currently Accept-Encoding is considered 'unsafe' header and is refused to be set. As such GET requests with such heading crash FlutterFlow.

## To Reproduce (required)
1. Create a new API Call
2. Use https://api-demo.mlsgrid.com/v2/Property?$filter=OriginatingSystemName%20eq%20%27northstar%27%20and%20ModificationTimestamp%20gt%202020-12-30T23:59:59.99Z&$expand=Media,Rooms,UnitTypes for with GET method
3. Set Authorization (you will need your own credentials, as I cannot share mine publicly)  and Accept-Encoding: gzip, deflate, br headers.
4. Go to Response & Test, and run API

## Context (required)
Trying to build a web and mobile app that primarily serves data from this API, and could not proceed forward without having solved this issue.

## Screenshots / recordings
Network screen shot: ![accept_encoding_unsafe](https://user-images.githubusercontent.com/11250345/215816410-ef532c92-db42-4fb3-9375-432e9a6847cd.jpg)

Screen recording: https://www.awesomescreenshot.com/video/14249715?key=62a77adbd1d7c1bcb2e764a754ae3b48

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): MacOs and Windows 11
* Browser name and version: Chrome Version 109.0.5414.120 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): MacOS and Windows 11

**Comment by yoheisoito** [comment]
Hi @hmesfin,

Thanks for submitting an issue. Unfortunately, I am not able to test and confirm whether this is a bug in Flutterflow, as this issue may potentially be API specific that may arise from improper setup of the headers or CORS settings on your API. That being said, I would be curious in the response when:

1) What would happen if you leave out the accept-encoding line altogether? 
2) Have you tested this using cURL or via other web based API testing services? Do you get successful responses?
3) Have you tested this code from iOS/Android platforms? Do you get similar responses?

Thanks.

**Comment by hmesfin** [comment]
Hi @yoheisoito ,

The accept-encoding header is required by the API, and without it, it will still do the same…crash.

I have tested the API using Postman, and it runs flawlessly. But, no I have not tested it from iOS/Android platforms.

Hope that helps!

**Comment by yoheisoito** [comment]
@hmesfin Thanks. While I am not being able to test your particular API, can you also try to see if your responses change when you unset User Proxy for Run / Test Mode?

Thanks!

![Uploading Screen Shot 2023-02-01 at 12.06.13.png…]()

**Comment by hmesfin** [comment]
Hey @yoheisoito I ran it a few times with proxy for run/test disabled. I am no longer seeing the forbidden network result for accept-encoding. However, the page still crashes once 200 status code is displayed, where, I am assuming, when the API starts sending back results.

Also, I'm happy to add you as a collaborator to the FF project I am running this API on, so you can test it yourself. Nothing much to break in there, as I have not made any progress while awaiting resolution for this issue. If that's acceptable with you, please share email .

**Comment by yoheisoito** [comment]
Hi @hmesfin,

I am glad that you're starting to see some progress!
As much as I'd like to help, the purpose here is to pin-point bugs on Flutterflow, and at this point cannot determine whether your issue comes from your particular API, CORS settings or is indeed FF-dependent. If you encounter obvious risks where you're certain that comes from bugs on FF, please let us know. I will be closing this for now, but please feel free to reopen the case if you see obvious bugs coming from FF.

Thanks for your understanding!

**Comment by hmesfin** [comment]
Progress? There is none. The API call is still crashing FF.
