### ISSUE TITLE
Can't export code after setting default values for component Color parameters

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#428]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Component parameters of type Color can have default values.

## Current behavior (required)

Setting default color _to some values_ breaks code exports.

## To Reproduce (required)

1. Create new component
2. Add component parameter. Type=Color, name = whatever.
3. Set default value to FFFFFF.
4. Save.
5. Try building or exporting code. Observe that it fails.

## Context (required)

Can't set default values for color parameters.

## Screenshots / recordings

![Screenshot 2023-01-31 at 5 25 30 PM](https://user-images.githubusercontent.com/92294640/215897678-cc1c4412-76dd-4730-82b3-2866b0be71df.png)

## Your environment

* Version of FlutterFlow used: January 25, 2023
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by wenkaifan0720** [comment]
Hi Anton. This seems to be working on the main dev/beta.

**Comment by aemelyanovff** [comment]
> Hi Anton. This seems to be working on the main dev/beta.

I don't think so... Check out this tiny project reproducing this bug - https://app.flutterflow.io/project/default-color-b632hx It won't build neither in prod nor with the latest FF codebase.

**Comment by wenkaifan0720** [comment]
Ah I figured it out. I wasn't testing with the same color (aka White) as in your example. Turns out we have special codegen treatment for some colors (e.g. white will turn into Colors.white, not Color(0xFFFFFFFF), but I stilled added a `const` modifier in front of it and it caused the issue). I'll push a fix for this.

**Comment by agreaves** [comment]
Great catches. Closing as fixed!
