### ISSUE TITLE
Cannot check if list is null

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#429]
## Expected behavior (required)

Be able to add null check on Lists like we can on other types. When the returned value from a bottom sheet, functions or actions is of type List then there is no way to check if the list is null.

## Current behavior (required)

Cannot add null check on variables of the type List. Thought local variables of type List are non-nullable list values returned by bottom sheets, functions or actions can be null but there is no way to check if the returned value is null.

## To Reproduce (required)

1. Create a variable of type list or return a list from bottom sheet
2. Try to add a null check to the list.

## Context (required)

Bottom sheet with return expected to be of list type returns null on dismissing by tapping barrier/background(or pressing close icon with action to dismiss bottom sheet) but I cannot add null check on returned value to see if the returned value is null. I prefer to keep bottom sheet dismissable as its good for UX so making it non-dismissable is not an solution. This issue is also applicable on functions and actions which return nullable lists.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by aemelyanovff** [comment]
@Shubham-VE This is not a bug. If you want to propose nullable list support, please use the built-in feature request form.
