### ISSUE TITLE
Angolia search not working when you haven't connect it to Firestore

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#43]
## Expected behavior (required)
When I create a collection manually I should be able to select it from the DropDown in Algolia Search in Backend Query

## Current behavior (required)
The DropDown says Unset and I can't select my collection.

## To Reproduce (required)
1. Create a new project in FF
2. Don't connect it to FB
3. Go to Firestore create a new collection called Demo
4. Go to a Column Widget (or any widget) click on Backend Query
5. Click on Algolia Search 
6. The Collection DropDown it says 'Unset' and you can't select your collection Demo that you just created.

## Context (required)
Can't implement and test Algolia Search and also test some other bugs that are reported involved Algolia Search.

## Your environment
IT4olvHq25dgrs9J1s/IdfoxnSQXH0h7bedIkcpOGDwbfaKvPIlzaeClRFRDTuKrT2xtKEWLrzo0/6nPv/zEFe4nBxKZbb4/+ahcTw7dXn7kEuzyT+3IHDUHZbsSXTTm
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: Chrome 106
* Operating system and version (desktop or mobile): desktop

**Comment by Pepino-GR** [comment]
Before you can use a Algolia query, you have to enable Algolia, set the Application ID, set the Search API  key and select Demo as the Indexed Collection. The scenario doesn't make sense for me, because there are some other steps to go.

**Comment by bulgariamitko** [comment]
Yes you are probably right but as a stupid user I probably don't know that and I expect the platform to guide me and give me some kind of error. It is not a typical issue, but for me a way where a user hits a wall is a issue. But let's FF team decide

**Comment by organicnz** [comment]
@bulgariamitko yeah, that's true enough, mate!

**Comment by Pepino-GR** [comment]
I reopened the Demo Project with FF October 21,2022 and the behavior changed. The project shows 5 issues all related to Firebase, the Backend Query allows Query Collection ... Albolia Search and the Configure Algolia Search shows me, that the Collection is unset. You have to configure Algolia and then you can go on.  For me, this is the expected behavior.
