### ISSUE TITLE
Problem with custom widget (SfDateRangePicker)

### ISSUE THREAD

**Issue by TemplarDesign** [FlutterFlow/flutterflow-issues#430]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I want to use the SfDateRangePicker the custom widget: 
https://community.flutterflow.io/c/community-custom-widgets/date-range-picker
Expected behavior is that the widget compiles successfully and is able to be used in the app.

## Current behavior (required)

I copied the custom code from this page:
https://community.flutterflow.io/c/community-custom-widgets/date-range-picker
and maybe you see my post on the thread. When I try to use that custom code in an app with Supabase, it has errors. In a blank app, it does not have errors. I reached out to Jorge, the person that wrote the post and he also faced the same issue within my app.
The only difference that I see is the 2 lines of code that get automatically added since I am using Supabase
See screenshot: https://nimb.ws/9ATkjw

## To Reproduce (required)

import 'package:syncfusion_flutter_datepicker/datepicker.dart';

class SfCalendar extends StatefulWidget {
  const SfCalendar({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);

  final double? width;
  final double? height;

  @override
  _SfCalendarState createState() => _SfCalendarState();
}

class _SfCalendarState extends State<SfCalendar> {
  void _onSelectionChanged(DateRangePickerSelectionChangedArgs args) {
    // TODO: implement your code here
    setState(() {
      if (args.value is PickerDateRange) {
        FFAppState().startDate =args.value.startDate; [//Create](https://create/) a localState of type Timestamp called start Date
        FFAppState().endDate = (args.value.endDate ?? args.value.startDate); [//Create](https://create/) a localState of type Timestamp called endDate
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: SfDateRangePicker(
        view: DateRangePickerView
            .year, [//You](https://you/) can use year or month view
        monthViewSettings: DateRangePickerMonthViewSettings(
            firstDayOfWeek:
                1), [//Choose](https://choose/) the first day of the week in the MONTH view 1 Monday, 2 Tuesday...
        selectionMode: DateRangePickerSelectionMode.range,
        onSelectionChanged: _onSelectionChanged, [//Single](https://single/), multiple o range mode
      ),
    );
  }
}

1. Use an app that has Supabase integration
2. Add startDate and endDate local state timestamps
3. Copy and paste the code snippet, name, and dependency from here: https://community.flutterflow.io/c/community-custom-widgets/date-range-picker
4. Attempt to compile.

### Bug Report Code (required, generate from Widget Tree)

See screenshot: https://community.flutterflow.io/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JwckE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ba4fbd886b869cd02c9b8dfa8d5d8a673511d8e/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MWm05eWJXRjBTU0lJY0c1bkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNITUdrQ09BUTZDbk5oZG1WeWV3WTZDbk4wY21sd1ZBPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--cfda350175ba87e768b4e96e935a8171fc679bec/Screen%20Shot%202023-01-30%20at%205.44.25%20AM.png

## Context (required)

I'm unable to use the date range picker. It's an important feature for the booking process in the app.

## Screenshots / recordings

https://komododecks.com/recordings/HobtN39uDOfPRRMopY0M
^ This link is a screen recording provided by Jorge with the recommendation to contact FlutterFlow support.
This one is from me recording it: https://www.loom.com/share/ed1d40aa4cec431b8465ce4d95ae1bfc

## Your environment

* Version of FlutterFlow used: I don't know, whichever loads in the browser
* Platform (e.g. Web, MacOS Desktop):  MacOS Desktop
* Browser name and version: Chrome Version 109.0.5414.119 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): desktop, mac, iMac

**Comment by wenkaifan0720** [comment]
Hi @TemplarDesign. I just created this test project (https://app.flutterflow.io/project/flutterflow-issue-430-fzh7jo) with Supabase enabled and is able to compile. You have to import this specific version (20.2.44) of the syncfusion package as newer packages have conflicts with the Flutter version FF is using.

**Comment by TemplarDesign** [comment]
I copied and pasted the function from the test project that you created:

<img width="1639" alt="Screen Shot 2023-02-03 at 5 59 49 AM" src="https://user-images.githubusercontent.com/116034778/216609539-74693652-2084-48e9-b469-da2beec71086.png">
@wenkaifan0720

**Comment by wenkaifan0720** [comment]
Have you clicked on the refresh button next to `Pubspec Dependencies`? It looks like the code editor is complaining about the `datepicker` package not being imported.

**Comment by TemplarDesign** [comment]
Yeah, many times with no success.

**Comment by TemplarDesign** [comment]
@wenkaifan0720 
 
https://www.loom.com/share/083e62be895c4c08836056d9b8d5b7ea

**Comment by wenkaifan0720** [comment]
That's a bit odd. Could you share with me the error report code, or your project link? I need to compile it locally to see more details of the error message.

**Comment by TemplarDesign** [comment]
https://app.flutterflow.io/project/the-platinum-paw-6q5l8i

**Comment by wenkaifan0720** [comment]
I've downloaded the project and is able to compile locally. I really don't know what is causing the issue now... I'll reach out to our team and see if they can help.

**Comment by TemplarDesign** [comment]
😅 yeah, I'm not sure at all. I'm new to FlutterFlow and I'm not familiar with this code language yet.
I appreciate your help, truly. Thank you @wenkaifan0720

**Comment by TemplarDesign** [comment]
I have removed Supabase from the app and the custom widget works.

**Comment by Krystian95** [comment]
Hi, "status: wontfix" could be a problem for us FF users, because in the near future we could incur into issues related to an old version of the sfDateRangePicker (20.2.44) incompatibility with new Flutter standards (solved by the newer version of sfDateRangePicker).
