### ISSUE TITLE
Issue with Firebase Login: Stuck on Loading After Popup Closes in Web Application

### ISSUE THREAD

**Issue by diogo-garcia** [FlutterFlow/flutterflow-issues#4309]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After configuring everything needed to log in via the web application, the expected result does not occur. I created a new project from scratch with only two screens: a home screen and a restricted screen. On the home screen, I added a simple login button, and on the restricted screen, I added a simple logout button. I published the project and tested the functionality. The login process proceeds normally until I select the user and the popup closes. After that, the login button stays in a loading state forever, and nothing happens. Monitoring the console, I noticed the repeated error message:

`Cross-Origin-Opener-Policy policy would block the window.closed call.`

Additionally, Firebase Console Authentication shows that the user I attempted to log in with has been registered there, and there is a message stating:

Cross-origin redirect sign-in is no longer supported in many browsers. Update your app to ensure your users can continue to sign into your app.

However, no user document or collection has been created in Firebase or FlutterFlow's data visualization tool. If I refresh the page, I am redirected to the restricted area, indicating that the login was successful, but the final redirection and user creation were not completed.

### Expected Behavior

The expected behavior is for the user to log in successfully, be redirected to the restricted area automatically after the popup closes, and have their user data stored in Firebase (user collection and document creation).

### Steps to Reproduce

Steps to Reproduce:

1- Create a new FlutterFlow project from scratch and use the step by step configuration method.
2- Create two screens: a home screen and a restricted screen.
3- Add a simple login button on the home screen and a logout button on the restricted screen.
4- Publish the project and test the login functionality using Firebase Authentication.
5- Complete the login process via the web, selecting a user in the popup.
6- Notice that the login button stays in a loading state after the popup closes, with errors in the console (Cross-Origin-Opener-Policy and Cross-origin redirect sign-in is no longer supported).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMmA249OmN9c1r6JbsBv9Ts5JmImbLsvmO1RaCgoIYyuOpl/evXsbRBoOeHgdwlLfESmmlEBpcKJjYXLV8I7Aw2VY4R/ysxqEhXMbH+5QZOBBcySZHEkEZpPfUyb4aWvgCZCXLJvLVIQ3DqAfOuRdB7qK5OxIndISq/LZO4=

### Visual documentation

Vídeo recorded:
https://github.com/user-attachments/assets/f2043a27-bc95-4191-8f22-01a803b95b03

### Environment

```markdown
- FlutterFlow version: v5.0.6+ (Released October 18, 2024) Flutter Version: 3.22.2
- Platform: Web
- Browser name and version: Chrome Versão 129.0.6668.101
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment]
Hi @diogo-garcia,

I wasn’t able to reproduce the issue on a blank project. Could you please verify the following:

* Ensure all steps in the Firebase authentication setup are completed, especially the initial setup (refer to [Initial Setup Guide](https://docs.flutterflow.io/integrations/authentication/firebase/initial-setup)) and Google OAuth ([Google OAuth Login Setup](https://docs.flutterflow.io/integrations/authentication/firebase/google-oauth-login)).
* Regenerate the Firebase configuration files after making any configuration changes.

Let us know how it goes!
