### ISSUE TITLE
If/Then/Else Not working with fill colors

### ISSUE THREAD

**Issue by kjoyceee** [FlutterFlow/flutterflow-issues#431]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Use I/T/E to display a color depending on the outcome

## Current behavior (required)
the values I set in the box are not updating the code

![output](https://user-images.githubusercontent.com/115580022/216133085-91813b7e-930d-4994-a210-f31e7517790b.PNG)
![input](https://user-images.githubusercontent.com/115580022/216133088-cbe56bda-4b8e-429c-b4e5-f9c702a04c1b.PNG)

**Comment by kjoyceee** [comment]
Exporting code and using in an ide changes nothing.

**Photo 1: See I selected the button and the current colour is secondary text.**

<img width="480" alt="1" src="https://user-images.githubusercontent.com/115580022/216502329-cbc8e5ff-1822-40b2-aba8-f3a16c88fa5e.png">

**Photo 2: I set a very simple bool condition**

<img width="574" alt="2" src="https://user-images.githubusercontent.com/115580022/216502335-47c72240-7f30-42d8-a3d1-90501a47917c.png">

**Photo 3: Showing the condition is set for colour**

<img width="635" alt="3" src="https://user-images.githubusercontent.com/115580022/216502337-a5a0b71f-056d-44a3-8ff1-b41e01a08117.png">

**Photo 4: Result of the code after the condition is set, you can see it is still trying to set it to Secondary Text colour.**

<img width="546" alt="4" src="https://user-images.githubusercontent.com/115580022/216502338-c394ee0d-8052-49f5-8633-a6a50c4fdc35.png">

**Comment by kjoyceee** [comment]
I have used this function in past projects and never used to have a problem

**Comment by wenkaifan0720** [comment]
This is a bug on our end. The temporary solution is to first set a base color for the property then set the variable color. We will push a fix soon. Thank you!

**Comment by wenkaifan0720** [comment]
This should be fix in our next update. Thank you for raising this issue.
