### ISSUE TITLE
Bug Report: Issues with Persist Auth Session and Token Handling in APK Build

### ISSUE THREAD

**Issue by ibnuaji20** [FlutterFlow/flutterflow-issues#4311]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to report a bug that I encountered while building the APK for my application. During testing on a smartphone, I noticed the following issues:

The Persist Auth Session feature, which has been activated in the authentication settings, does not seem to function properly. Despite enabling it, the user session is not being maintained as expected.

Additionally, I have observed an intermittent bug where the authentication token fails to be recognized even though it is stored in the app state. This results in the app not being able to access user data that should be readily available.

I have double-checked the settings and configuration, and everything appears to be set up correctly. However, these issues persist and are affecting the functionality of my application.

Please advise on how to proceed to resolve these issues. Any help or guidance you can provide would be greatly appreciated.

Thank you for your support.

### Expected Behavior

i hope the content in my App remains there and not blank when I close the App and when the App still has a session token

### Steps to Reproduce

1. open the App
2. after successfully logging in, then close the App
3. re-open the App

after opening again, the content suddenly blank and i want to fix this problem

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XiMmBw891ofpE176Jae9ajSQWIjt9RY0zju4aaxQ1GJeuB4oqf8jUT3BZOMu6dFZUP2GJmm007s7RvdrDUMc4HByJbKpd1odxEzvyJHytMsWsPpDtZHJQAftWI3aizpuZvhVdIbJZLWRk7E2pOOi9fArrN72wIjJND/GhBKP+nGC/LjLgGX0Jg1ZSfCvr

### Visual documentation

![1](https://github.com/user-attachments/assets/239bb9cf-3817-431e-bc69-c74276b6f5ce) - After login
![2](https://github.com/user-attachments/assets/76b312a8-05c5-4f09-9328-73e6df7603ad) - After reopen the app

### Environment

```markdown
- FlutterFlow version: v5.0.6
- Platform: Web & desktop
- Browser name and version: chrome Version 129.0.6668.101
- Operating system and version affected: windows Windows 11 Home Single Language 23H2
```

**Comment by paulperez-dev** [comment]
Hi @ibnuaji20,

When the request fails, is the token still active? It’s possible that the session expired due to a period of inactivity. Additionally, is this issue occurring during testing? If so, could you please share the logs for further investigation?

Thank you!

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
