### ISSUE TITLE
FlutterFlow Desktop force close after close branch

### ISSUE THREAD

**Issue by ak2003** [FlutterFlow/flutterflow-issues#4312]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get FlutterFlow force close when I close a branch

### Expected Behavior

back to main branch without close application

### Steps to Reproduce

1. checkout in branch want to close.
2. Close the branch
3. FF force close

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfqD5Y5NoNt/17qBV/lUgh0nQHoEX+QnktVBaCsofePrOpkAf8/7UFtUOem6SkFmM2eZoGcX/MrQvd/pKsY7AzCZfoBB1rtUVQuXfzugMbaJPoS3b3RATJ1bGWac5Jik2iRTBMxpSHwM7TqUJu+taBPDJLroClcBD+aoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Screenshot 2024-10-21 at 09 01 13](https://github.com/user-attachments/assets/41e77c5a-6acd-402b-9678-6d058800accd)

### Environment

```markdown
- FlutterFlow version: v5.0.7
- Platform: MacOS
- Browser name and version: Google Chrome
- Operating system and version affected: macos sonoma version 14.3.1
```

### Additional Information

Process:               FlutterFlow [15141]
Path:                  /Applications/FlutterFlow.app/Contents/MacOS/FlutterFlow
Identifier:            io.flutterflow.prod.mac
Version:               5.0.7 (5.0.7)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-21 08:59:52.5547 +0700
OS Version:            macOS 14.3.1 (23D60)
Report Version:        12
Anonymous UUID:        2C0C0AF3-6583-9560-E4EE-14079CA6D281

Sleep/Wake UUID:       EF3CC578-229D-45E8-B718-9DFB84D1B8BE

Time Awake Since Boot: 430000 seconds
Time Since Wake:       1425 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   FlutterFlow [15141]

Application Specific Information:
abort() called

**Comment by paulperez-dev** [comment]
Hi @ak2003,

I’ll be closing this issue since it is already being tracked under #4070.

Thank you for reporting it, and feel free to reach out if you have any further questions!
