### ISSUE TITLE
FlutterFlow Preview App (Android)

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#432]
The Preview App crashes when trying to retrieve a list of recent links (run links).  It could be a useful tool in the SDLC but at the moment it isn't worth installing.

**Comment by hariprasadms** [comment]
Hi @OldFred2023  - Thanks for reporting this issue. In order to take this issue further, could you please update the issue details as per the issue template advised. 

Please share quick video/image/error snippets which can help us to quickly investigate the issue. 

Thanks

**Comment by OldFred2023** [comment]
What other information is needed !!!!, it crashes out and Android reports it has stopped, so apart from a screen shot of a mobile with "app stopped working" there is nothing else to give.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @OldFred2023.

How many run links are there in the project, approximately? My best guess is that the problem is that you have too many.

Also, next time please follow the bug report template :-)

**Comment by aemelyanovff** [comment]
Fixed the issue where FF Preview app can crash when there are too many Run Mode links.
