### ISSUE TITLE
"Undefined name '_shouldSetState'" error in periodic actions

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#433]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Everything I can do in "regular" actions should work in periodic actions as well.

## Current behavior (required)

Certain action chains in periodic actions result in build failures.

## To Reproduce (required)

Sorry the steps are a little convoluted. I was unable to find simpler steps.

1. Add "On Page Load" action trigger to a page.
2. Add "Start Periodic Action" action.
3. Add Backend Call/API action. It can call any API, doesn't matter.
4. In one of the branches after the API result condition, add Terminate action.
5. Save.
6. Try building the project. Observe the `Undefined name '_shouldSetState'` error.

### Bug Report Code (required, generate from Widget Tree)

ITESi8rqx5Vgrstf1rXxK8JqhQIgQ0QnU7gnlO1ucx4bG5T2BKQAYMzeaUNKQvWfTws/e0yGhkw13PPFiuOXV8c4BEicfa55k/UwKlCvHAM=

## Context (required)

This is a frequent source of build failures.

## Screenshots / recordings

![Screenshot 2023-02-01 at 5 30 05 PM](https://user-images.githubusercontent.com/92294640/216178550-df863d23-6d14-4d4d-9f2a-af5274bd5fd1.png)

![Screenshot 2023-02-01 at 5 31 16 PM](https://user-images.githubusercontent.com/92294640/216178737-c0f62b7e-bd46-4dc3-8e4f-ac132705ddc9.png)

## Your environment

* Version of FlutterFlow used: January 25, 2023.
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by wenkaifan0720** [comment]
Should be fixed in the next update.
