### ISSUE TITLE
Firebase User Deletion Function Deletes User Table Completely

### ISSUE THREAD

**Issue by syg-eliseu** [FlutterFlow/flutterflow-issues#435]
A while ago, by indication of apple, I added the delete user account action to my app, but all my users were deleted from the firestore. I didn't understand why until today.

Today I manually deleted a user from the Firebase "Authentication" page, and all users were deleted from Firestore again.

When studying the reason, I identified that the problem was in the function generated by FF in Firebase that deletes the user record in Firestore when the user is deleted in Authentication.

This caused me a big problem because the app is in production.

![image](https://user-images.githubusercontent.com/88388127/216194985-3e77b724-3a05-4c6d-8856-2ab97bc666f8.png)

**Comment by agreaves** [comment]
Hi @syg-eliseu, that's quite an unfortunate event, I'm sorry this happened to you! However FlutterFlow does not install this Firebase extension for you, nor do we even recommend it anywhere. Do you use any other services that access your Firestore or Cloud Functions on your behalf? Or do you have anyone else on the project that installed it?
