### ISSUE TITLE
Editing persistent app state temporarily changes document queried from backend

### ISSUE THREAD

**Issue by brnchr0m** [FlutterFlow/flutterflow-issues#4356]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. I am setting an app state variable to be equal to a value from a backend document
2. I then open a bottom sheet where I edit this app state variable, and then dismiss it by swiping down
3. The backend document, in the run mode, test mode as well as debug variables in test mode appears to have changed with the changes of the app state variable, even though no action is taken to adjust the document AND the document is unchanged when I look at the firebase storage

### Expected Behavior

I expect the document queried from the backend to not change when I edit an app state variable set from a variable from that document

### Steps to Reproduce

1. Create a custom data type that exists both in a document in a backend and as a persistent app state variable
2. Set app state variable to the field from the backend document
3. Open a bottom sheet where you can adjust the custom data type
4. Dismiss the bottom sheet, check if backend document appears to have changed (won't change in firebase but will in the editor / test mode / run mode)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfjPHq05NOtbwB176Ja/par2QUHEMcTL4zlO1HcxAYGO/yPbJ/dsnObhJWXfKoY1NhHGGZuFoH3PDoiYfMG8IVEwyrG5x/ypNyEDuWf3q8RaqPC6qzPHYlAcFhJh2l5MKJpBJ7AMpaLS0S2WWYJ+6vHx7fGZu/Zwh9f6PHaOI=

### Visual documentation

Can't because I have since fixed the issue by clearing the cache when I dismiss the bottom sheet

### Environment

```markdown
- FlutterFlow version: 5.0.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Could you let me know which specific widget in your project is triggering the action? This will help me replicate the issue in a new project and identify any potential errors.

**Comment by brnchr0m** [comment]
Hello,

It's in the startWorkoutComponent, when I change the "exercise" say adding
a set, or replacing it, it also appears to have changed the backend
document it draws it from. In the current version it is fixed by clearing
the cache after entering a workout though

Best,
Robin

**Comment by Alezanello** [comment]
Hello,

I sincerely apologize for the delayed response. Would it be possible for you to replicate this issue in a new blank project with just the necessary actions to reproduce it? Unfortunately, I haven’t been able to reproduce it on my end.

Alternatively, has this issue already been resolved?

Thank you for your understanding, and I appreciate your help in troubleshooting this!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
