### ISSUE TITLE
UTF-8 icon characters (Unicode) are not displayed properly in Mac desktop app.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#436]
## Expected behavior (required)
- UTF-8 icons are broken. It should show the same icon as in the UI builder of web browser.
- The image below shows the icons.
- 
<img width="303" alt="image" src="https://user-images.githubusercontent.com/5080329/216207662-8ca93994-dc43-4922-a0b5-eb891bd6dd04.png">

## Current behavior (required)

- The icons are broken like below in Desktop editor (Not the UI builder in web browser)

<img width="907" alt="image" src="https://user-images.githubusercontent.com/5080329/216207611-dbdcb79a-86f7-40a2-a545-608763b060ee.png">

## To Reproduce (required)

N/A

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

N/A

## Screenshots / recordings

<img width="907" alt="image" src="https://user-images.githubusercontent.com/5080329/216207611-dbdcb79a-86f7-40a2-a545-608763b060ee.png">

## Your environment

* Version of FlutterFlow used: FlutterFlow v.1.1.41 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Browser name and version: N/A
* Operating system and version (desktop or mobile): desktop

**Comment by agreaves** [comment]
Hi @thruthesky, thank you for the bug report! Unfortunately this is simply a limitation of the code editor that is available on MacOS. We hope to update it eventually to be on par with the web code editor. For now I'm closing this as "won't fix" but will keep that in mind as we look for alternative code editors.
