### ISSUE TITLE
Custom Code editor does not provide proper boilerplate.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#437]
## Expected behavior (required)

- The `required` directive is missing and produce error. I am not sure when it started to happen or if it's the only it happens. But it happens. Please see the screenshot and video.

## Current behavior (required)

- The custom widget editor does not add `required` directive in its boilderplate.

## To Reproduce (required)

1. Create a custom widget.
2. Add a parameter with the Document type.
3. Click the boilerplate icon and apply.
4. And you will see an error due to missing `required` directive.

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

- Developers may have hard time to fix the error when the boilerplate gives a wrong code.

## Screenshots / recordings
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/5080329/216214157-4cc2298a-4c7c-4f89-aac1-273c789d2c05.png">

https://user-images.githubusercontent.com/5080329/216214175-6d9bd38a-900d-4f1b-aa50-9350a4288bd0.mp4

## Your environment

* Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by victoriahuang1** [comment]
Hi @thruthesky this should be fixed with the next deploy!
