### ISSUE TITLE
Navigation bar fails to load in run mode and after deployment

### ISSUE THREAD

**Issue by nshah25** [FlutterFlow/flutterflow-issues#438]
## Expected behavior (required)
The navigation bar to be at the bottom of every page it is enabled for and for it be responsive.

## Current behavior (required)
The nav bar fails to load and the user is stuck on the main page unable to interact with the other pages

## To Reproduce (required)
1. Create new project
2. Enable the nav bar toggle in settings with default settings
3. Create multiple pages
4. Enable the nav bar toggle on each individual page at the bottom and select "show this page on the nav bar"
5. Run the project
6. Observe that the nav bar does not compile during the build and the user can only interact with the home page

### Bug Report Code (required, generate from Widget Tree)
ITFTzPHl25RNobhe+KrMcu1Wij8vI0MdXOczitVEew4bCIj4B+wIf+DCV1toOdCzaHw/PWL8gnkFptbOitnTJMIqaDirY4RcypNQdFyjEA8=

## Context (required)
Cannot test the app functionality as a whole and this has slowed down the development timeline. Is a blocker as the user cannot use the app at all until the issue is resolved

## Screenshots/recordings
![Screenshot 2023-02-01 224820](https://user-images.githubusercontent.com/68348722/216234242-a724d90f-2367-445c-b923-89fd8e3c798f.png)
   Red area circled is the bottom of the app page where the nav bar is expected to be

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Windows desktop, using emulator for android and iOS testing
* Browser name and version: Chrome, 109.0.5414.120
* Operating system and version (desktop or mobile): desktop

**Comment by hariprasadms** [comment]
Hi @nshah25 - Thanks for posting this issue. Can you please share preview and run mode of the page where you see navigation bar is missing.

**Comment by aemelyanovff** [comment]
Closing as inactive. @nshah25 please feel free to reopen the issue if you add the details.
