### ISSUE TITLE
Custom Function creates an error when testing

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#440]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When testing my custom function expect to see a url encoded URL.

## Current behavior (required)

I get this error, which looks like it comes from a different function:

Compilation error: Info: Compiling with sound null safety
lib/main.dart:441:12:
Error: Undefined name 'FirebaseFirestore'.
    return FirebaseFirestore.instance.doc('users/$userid');
           ^^^^^^^^^^^^^^^^^
lib/main.dart:486:12:
Error: Undefined name 'FirebaseFirestore'.
    return FirebaseFirestore.instance.doc('contexts/$contextId');
           ^^^^^^^^^^^^^^^^^
Error: Compilation failed.

## To Reproduce (required)

String urlEncode(String qrUrl) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  String encoded = Uri.encodeFull(qrUrl);
  return encoded;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

1.
3.
4.
5.

### Bug Report Code (required, generate from Widget Tree)

Can't find this button

## Context (required)

Need to use the share dynamic liink which is a key functionality, but need to url encode since I create the link manually.

## Your environment

* Version of FlutterFlow used:  3.3.4
* Platform (e.g. Web, MacOS Desktop):  web
* Browser name and version: chrome Version 109.0.5414.119 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): macos

**Comment by hariprasadms** [comment]
Hi @timfong888 - Thanks for sharing the issue details. 

Just need a bit more information to see whats going on here. Looking at the error, I can guess that you got another function which is talking to fire-store. Is that correct?. If yes, have you compiled this function successfully?. While checking for the error, it should work without showing any errors. However while testing the function using 'test function' it shows below error. I think it is something expected as test function engine does not test the functions if they got firebase services. 

Please confirm above details. 

Meanwhile, you can test calling this function in run mode and see what how it works. 

![image](https://user-images.githubusercontent.com/17435678/216407454-b442d8d5-d29d-46f0-bde1-762113725041.png)

**Comment by hariprasadms** [comment]
Hi, Custom functions with firestore calls can not be tested in custom functions test. Hence closing the issue.
