### ISSUE TITLE
Unable to download AAB for Google Play Store

### ISSUE THREAD

**Issue by timfong888** [FlutterFlow/flutterflow-issues#441]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I want to be able to download the AAB from the Flutterflow UI.

## Current behavior (required)

{"error":"FORBIDDEN","message":"You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."}
## To Reproduce (required)

1.
5.
6.
7.

### Bug Report Code (required, generate from Widget Tree)

none
## Context (required)

Deploy to Google App Store TODAY!

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: chrome latest update 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment]
I think this is fix?

**Comment by hariprasadms** [comment]
Hi, This should be fixed in latest updates. and also there are no follow up recently, we assume this has been fixed in your project in latest FF updates. Hence we are closing the issues. Let us know if this issue persists. We can re-open the issue.
