### ISSUE TITLE
UI issues in list view when removing item from list

### ISSUE THREAD

**Issue by MohitKandu25** [FlutterFlow/flutterflow-issues#442]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Upon deleting an item from list, the list should be updated with this particular item removed from it 

## Current behavior (required)
According to UI, the last item in list is removed and not the particular item which was removed (even though the local state is updated properly)

## To Reproduce, I have added a video with the following steps as a followup from issue#279 (required)
-The page contains 3 level nested list views.
- First list view is called session
- Second one is called Activity
- Third one is called Sub activity
- Each list view contains a text field on which "onChange" action is defined which updates a local state binded to it. 
1. Add the session details in first session item (session name and activity name). In the video I have added "Session 1" and "Activity 1".
2. Add another session by clicking on "Add another session" button
3. Add some details in second session item (session name and activity name). In the video I have added "Session 2" and "Activity 2".
4. Delete the first session item which should leave the second item only.
5. In the UI we see second item getting removed and first item remain.

## Context (required)
I am unable to create lesson plan in my app because the list view items are shown weirdly after removing items from list view.

## Screenshots / recordings
https://user-images.githubusercontent.com/104911624/215021209-763f544e-0da0-45f6-9357-6bfbd71729a8.mp4

## Your environment
Version of FlutterFlow used: v3.0 February 3, 2023 - Flutter 3.3.4
Browser name and version: Google Chrome 103.0.5060.134 (Official Build) (64-bit)
Operating system and version: Ubuntu 20.04.4 LTS

**Comment by wenkaifan0720** [comment]
Hi @MohitKandu25. As I said in your previous issue post, this bug should be fixed in a coming update.

**Comment by hariprasadms** [comment]
Hi @MohitKandu25 -As @wenkaifan0720 mentioned that this issue is already fixed and will be available in next update. We can close this issues.
