### ISSUE TITLE
Duplicating a project creates functional custom code errors

### ISSUE THREAD

**Issue by CreativeWorkflow** [FlutterFlow/flutterflow-issues#443]
Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
After duplicating my project, I expected both projects to work correctly and being able to compile codes and preview/run the project.

## Current behavior (required)
Instead, there are errors for a custom code (widget) that was entirely valid and functional before project duplication.

## To Reproduce (required)
1. Have at least one project with custom code(s) and duplicate it
2. Try running or previewing either of the two projects
3. Optional: Try building an APK aswell, which -might- fail.

### Bug Report Code (required, generate from Widget Tree)
ITFflcjf35dIseEC7a6IK/kw+Ck7Qm0cTL4zlO1HcxAYGO/yPbJ/Os/SSBRBUs+hTWlhHGeJ/UUE+fDpjtrtEvQ6aAusfrk5+pN+FxbKJDbkEuzyT+3IHDUHZbsSXTTm

## Context (required)
The custom widget, developed by an independent Flutter developed, worked totally fine until I duplicated the project (to work on another version of it). I'm now unable to preview or run the project via FF, and I can't build the APK either. Please note that I downloaded the code, built it via Android Studio and tested the app on both emulator and real device: it worked perfectly.

## Screenshots / recordings
![screenshot-app flutterflow io-2023 02 03-12_57_27](https://user-images.githubusercontent.com/124360906/216598016-342a6ffe-d0a5-4e56-aed0-d33a66aa825f.png)

## Your environment
* Version of FlutterFlow used: 3.0 (latest)
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome (109.0.5414.120)
* Operating system and version (desktop or mobile): Windows 11, Desktop

**Comment by hariprasadms** [comment]
Hi @CreativeWorkflow - Thanks for sharing this issue details.

It can reproduce the issues. It is mostly happening when apps got firebase integrations and also when users collection got additional fields apart from defaults fields. 

The projects which are no firebase configured, all works fine. 

Below image showing a common error in this particular scenario.

![image](https://user-images.githubusercontent.com/17435678/216792307-d0235e11-58dc-47d4-878b-7136b0fc5ac6.png)

**Comment by agreaves** [comment]
Hi @CreativeWorkflow, thanks for the bug report! In this case, it actually does not have to do with the duplication of the project as this custom widget would never have properly compiled in the first place (unless it was "Excluded from Compilation").

However, I've made a fix that should include `auth_util.dart`, which you are currently using and is currently missing. This will be fixed next deploy! 🙂
