### ISSUE TITLE
Action flow OnTap works, but not on OnPageLoad

### ISSUE THREAD

**Issue by tnbt-tech** [FlutterFlow/flutterflow-issues#4435]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have made an action flow, I run when i OnTap a button. It works fine.
When I take the exact same action flow, OnPageLoad, I get error when I run test or publish.
I get no errors before I run the test/publish.
![image](https://github.com/user-attachments/assets/710015f8-3f50-46af-9760-d90858907118)
![image](https://github.com/user-attachments/assets/7aee9ccc-cfbc-4281-b8d6-53a782b28e1f)

### Expected Behavior

I expected no problems with the builld

### Steps to Reproduce

1. Open my project: Spilldugnad Shop
2. Open the page test
3. Look at the actions on page and on the button, this should be similar. Just one on tap and on on page load
4. Run test
5. I get Build Failed when I use OnPageLoad. If I remove the action OnPageLoad, everything works fine
6. This is the error I get: 
![image](https://github.com/user-attachments/assets/92b44f63-5ccb-4c16-861d-1a725c47b389)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shcj15YxOsd8B7s+NcflB/CgXQlg/R5E8scp/bxIgGIDzPOw+ZPWkaRJBOLCodFVhM0Smmn013MrTkYaSGvYDNkmuQaphyYd2cgHKcHuhe5OBDLq8PHJ8TPFjJn6i36WFpBZDKrF1dVoTwFymOtmuQXLvO5zHIndISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/d5c4cb90-9ed0-4067-b1f8-3654004e64c4)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.6+ released October 18, 2024
Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Google Chrome Versjon 129.0.6668.101 (Offisiell delversjon) (arm64)
- Operating system and version affected: MacOs 14.6.1 (23G93)
```

**Comment by Alezanello** [comment]
Hello!

From what I can see in your project, the API call is being triggered based on the result of a query that's located in the scaffold. However, the API call isn't able to access the query result because the **OnPageLoad** event triggers first, before the query is completed.

As a result, the API call body is empty since the query hasn’t been executed yet. To resolve this, you can move the query into the **OnPageLoad** event so that it runs first, and then populate the API call with the query's output.

**Comment by tnbt-tech** [comment]
Thank you so much for your help 👍
