### ISSUE TITLE
Flutterflow vm_service 14.2.1 dependency error out of the blue

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#4439]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On compiling the app, we get the following error.

![image](https://github.com/user-attachments/assets/d020d1a1-6481-41fa-9239-3caf4d2ac611)

### Expected Behavior

The application would compile..

### Steps to Reproduce

No need to actually do anything to replicate the error, except to compile the application.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YAW/SkQE9WZ7yhdH03PFr8jmAepvDQkfbIN/kBBxaBRaJc+M0NbjrKZD6RV66mCqmwQXFTONpKCHKYy6avox5vKrNqdCU62VOqJd6uaD7dNub1PFQ7Df6XIZLIo3PuQ0SLb3kNh1JWeC/v

### Visual documentation

Image supplied above.

### Environment

```markdown
- FlutterFlow version: Desktop.
- Platform: Windows
- Browser name and version: Not applicable.
- Operating system and version affected: windows
```

### Additional Information

The error came completely out of the blue, we were doing some minor alterations on a page state, when this suddenly happened.

**Comment by Alezanello** [comment]
Hello!

FlutterFlow has just updated to Flutter version 3.24.2. To ensure compatibility, please update your local SDK to the latest version or adjust any custom code dependencies to match this update.

Feel free to reach out if you need any help with the process!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/93bea10c-a6ba-4b1e-ac8b-b05c7f660887/226eaa89-85fa-48dc-9452-dc2fd51d9a09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85M2JlYTEwYy1hNmJhLTRiMWUtYWM4Yi1iMDVjN2Y2NjA4ODcvMjI2ZWFhODktODVmYS00OGRjLTk0NTItZGMyZmQ1MWQ5YTA5IiwiaWF0IjoxNzI5NjE0MzQ0LCJleHAiOjMzMzAwMTc0MzQ0fQ.7D3golt4xRFgKcj6mhZ-TfjxuHseTdEcLz-IzORMz4I " alt="image.png" width="262" height="55" />

**Comment by charliefabley** [comment]
Yes thank you that fixed it. We can close this ticket.
