### ISSUE TITLE
Error: Failed running flutter pub get because custom_widget depends on flutter_native_splash 2.4.1 which depends on image ^4.2.0, image ^4.2.0 is required

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#4440]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Getting this error since today's update which is stopping my app from compiling. I've tried manually updating the image dependancy but whenever I edit it, the field clears completely

### Expected Behavior

Shouldn't show this error

### Steps to Reproduce

Try and compile a new custom action or a build with the updated flutterflow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTeU30+thcw4bI+LnP5kQZ/fBdRdpSOqHe1Zbe2akrH8ewvPGkezlMMcpNUyeRtU9/7lpUxDiQlqmVbrREpG0R3FSM/tWf0+Oy7SnhRYlOvF2ZVJi7V73BN+Qb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-10-22 at 17 04 07](https://github.com/user-attachments/assets/b8b54900-cabc-4c9a-81f5-afee98a01136)

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: Web and Desktop
- Operating system and version affected: iOS
```

**Comment by Alezanello** [comment]
Hello!

FlutterFlow has just updated to Flutter version 3.24.2. To ensure compatibility, please update your local SDK to the latest version or adjust any custom code dependencies to match this update.

Feel free to reach out if you need any help with the process!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/738a4e61-2f23-446e-9048-37e33d6316d3/d1e988bf-4d0b-4fd7-9ce2-2d8bcf701d0c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MzhhNGU2MS0yZjIzLTQ0NmUtOTA0OC0zN2UzM2Q2MzE2ZDMvZDFlOTg4YmYtNGQwYi00ZmQ3LTljZTItMmQ4YmNmNzAxZDBjIiwiaWF0IjoxNzI5NjE0Mzc5LCJleHAiOjMzMzAwMTc0Mzc5fQ.mnitUwhirqDXz5iDKOHhsvCUSKgBoaxbhzuXzQJEvUI " alt="image.png" width="262" height="55" />

**Comment by sanjayelate** [comment]
How do I update my local sdk?

**Comment by sanjayelate** [comment]
> Hello!
> 
> FlutterFlow has just updated to Flutter version 3.24.2. To ensure compatibility, please update your local SDK to the latest version or adjust any custom code dependencies to match this update.
> 
> Feel free to reach out if you need any help with the process!
> 
> <img alt="image.png" width="262" height="55" src="https://camo.githubusercontent.com/84d1f3d4e3e2472d95e5125f024cccb2d3bb8a2092e0311a2703171dcefb5554/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f37333861346536312d326632332d343436652d393034382d3337653333643633313664332f64316539383862662d346430622d346664372d396365322d3264386263663730316430633f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a5338334d7a68684e4755324d5330795a6a497a4c5451304e6d55744f5441304f43307a4e32557a4d3251324d7a45325a444d765a44466c4f546734596d59744e475177596930305a6d51334c546c6a5a5449744d6d5134596d4e6d4e7a41785a44426a4969776961574630496a6f784e7a49354e6a45304d7a63354c434a6c654841694f6a4d7a4d7a41774d5463304d7a633566512e6d6e697455776869727144587a3569444b4f486873764355534b67426f617862687a75587a514a4576554920">

How do I update my local sdk?

**Comment by sanjayelate** [comment]
Updated flutter via the Local run
