### ISSUE TITLE
Assets suddenly stopped working on Local Run after update

### ISSUE THREAD

**Issue by NickMalonzo** [FlutterFlow/flutterflow-issues#4442]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello! After getting the new update 5.0.8, my local run has not been loading any assets/images. 

After updating, I went into one of my apps and started a local run on Chrome and it didn't load any of the assets. It would only load ones that were linked through via Network.

It works fine on the Test Run version, but not Local Run for some reason. Maybe it's me?

![image](https://github.com/user-attachments/assets/44933a31-1ade-44d1-be9f-999d15a463af)

![image](https://github.com/user-attachments/assets/bffb810c-cc1a-4403-89e8-28c4a7ae2eda)

### Expected Behavior

It should show uploaded assets on image widgets.

### Steps to Reproduce

1. Create a page
2. Add an image widget
3. Upload an asset
4. Start a local run on Chrome or Edge
5. Can't see the asset

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gruYF0LnpK/pqhQIgQ0QnU7gnlO1ucx4jIrarBLAEeM7OX0NKQsvjd21qGlaKnkgzwfzwj/H9LfFePTCdG6Zk0JVPWAHxXl27VqaYEKuROXBCO/5XfW6P1KuzviRQKtFuSUZkwU6tNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

This is also is happening from a blank project.

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: Windows Desktop
- Browser name and version: Chrome 129.0.6668.101
- Operating system and version affected: Windows 11
```

### Additional Information

This affects all of my apps.

**Comment by luxthecreator** [comment]
The same issue after updating to 5.0.8

Run mode for web and android studio yields the same results.

**Comment by dannymeese** [comment]
Is there any way to downgrade / stay in the old version? I didn't account for having to replace dependencies randomly on a Tuesday. Flutter shouldn't be required to update for flutterflow to still work.

**Comment by Digitpixels** [comment]
same issue , but every time i launch local run i get error "failed to export code"

**Comment by eriklueth** [comment]
Same here, all assets are not showing up on local run since the update. In test mode on web it is working with no issues.

**Comment by Alezanello** [comment]
Hello everyone!

I just tried launching the project that NickMolanzo shared using the bug report code, and it compiled successfully. If you're still experiencing the issue, please share your project's bug report code with me so we can investigate further.

Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/435c02c5-9ff0-4162-962b-8187a1bf999a/d688bbbe-35aa-4e2a-b4fa-f9617511c04e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MzVjMDJjNS05ZmYwLTQxNjItOTYyYi04MTg3YTFiZjk5OWEvZDY4OGJiYmUtMzVhYS00ZTJhLWI0ZmEtZjk2MTc1MTFjMDRlIiwiaWF0IjoxNzI5Njk3MDkzLCJleHAiOjMzMzAwMjU3MDkzfQ.5c68qBQX2ljClmkaj1LLlItWl99qgQou4R-tX_IE6xA " alt="image.png" width="1919" height="1020" />

**Comment by luxthecreator** [comment]
To Whom It May Concern, 

Recently updated Android Studio to the latest version without knowing it would create FF compatibility issues. Before downgrading Android Studio back to Koala, 

I uninstalled the FF Application and the folder at C:\Users\username\AppData\Roaming\FlutterFlow\flutterflow\myapp to allow FF to rebuild data and start from scratch. (Done this on other occasions without issue)

After reinstalling and allowing FF to rebuild, everything downloaded from the cloud just fine, except for items contained in the assets folders. Images, audio, video, rive animation etc. 

@Alezanello 

Later I downloaded the image of my logo from FF cloud and dropped it into the Images folder contained in assets at C:\Users\username\AppData\Roaming\FlutterFlow\flutterflow\myapp\assets and the logo reappeared in Run Mode just fine after hot reloading my app.

Should I be downloading my Assets one at a time from FF cloud and dropping them into these folders this way, or should this be an automated process that is now not working?

**Comment by univermal** [comment]
Same thing, I too had to manually download the code and populate the assets/images folder. 

The build also gave other problems, like the fonts folder did not have all the fonts, even in the downloaded code zip. My project did not have any custom fonts, these are all standard fonts that went missing suddenly. I downloaded the required fonts from https://fluttergems.dev/icons/, placed them in assets/fonts folder and things worked fine after that. Something seems to be broken on export side, the local and remote code are not in sync. 

Another problem that I am noticing is that the hot reload is failing almost every alternate time with "failed export code" and then it fails to compile the code with following stack trace:
![image](https://github.com/user-attachments/assets/174af242-0c21-4353-84eb-088ba6753d06)

**Comment by akscienceltd** [comment]
Facing the same isssue with my project too! +1

**Comment by eriklueth** [comment]
Hey @Alezanello,

here is my Bug Report code so you can try here again:
IT4klPLqx5BPsbRA1pPpbcdsgmMRH24iTL07ttYbZxUjIuPtBJh/eeLRdlZpTtfgS1NhHFD8hl400PzUi9jtJPYqGw2ZfNw6yaVuWhfyc3q8R7aoDMyadnZ5L+dPN2Kh07aN2iJ4ItVsSnAY31+UCemWShLdGZ+/Zwh9f6PHaOI=

This is how it looks with local run on android, the upper functioning image is my profile image loaded from network:

![WhatsApp Bild 2024-10-24 um 15 45 16_98f5a728](https://github.com/user-attachments/assets/3c0d0928-60fe-4f9b-adad-7027264eead0)

**Comment by cindernet** [comment]
Hi Im having the same issue and after reading the comments above seems like a whole lot of unknown variables to work with. I am not a dev so having to deal with all these android studio and asset restructuring is not what I signed up for. The whole point of FlutterFlow was to handle all these for us. Is there a fix/solution to this at the moment??

**Comment by NickMalonzo** [comment]
> Hi Im having the same issue and after reading the comments above seems like a whole lot of unknown variables to work with. I am not a dev so having to deal with all these android studio and asset restructuring is not what I signed up for. The whole point of FlutterFlow was to handle all these for us. Is there a fix/solution to this at the moment??

Local Run seems to work fine on Mac, but I've just been using the web test mode as a substitute in the meantime. It's slower but you gotta work with what you've got for now!

**Comment by eriklueth** [comment]
I would say that the process of copying the assets from the google cloud bucket where there are stored when you upload them in flutterflow into the code that gets downloaded and build with local run got screwed up with the 5.0.8 update. Iam using flutterflow for windows, maybe this might be windows specific as @NickMalonzo suggested depending if this process is on backend or client of flutterflow.

**Comment by cmregazzo** [comment]
Good afternoon,

Here I also use Windows and I have the same problem.

After updating to version 5.0.8 of FlutterFlow, when trying to run the APP via Local Run, several errors regarding Grandle are displayed in the log, in addition to not exporting the Assets (customized images and icons), when using Hot Reload it is displayed an error message saying Failed to export code.

Waiting for the correction.

Thanks.

**Comment by dheereshGits** [comment]
Yep, same issue here as well. Started right after yesterday's update!

**Comment by NickMalonzo** [comment]
Looks like 5.0.9 fixed all of this for me! Thanks FlutterFlow team.
