### ISSUE TITLE
flutter_web_plugins package doesn't exist NOT CUSTOM CODE

### ISSUE THREAD

**Issue by staplKody** [FlutterFlow/flutterflow-issues#4444]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I attempt to deploy to either store, I get a code magic error that states 
Resolving dependencies...
Because growerapp depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.dev), version solving failed.

Build failed :|
Step 6 script `Install pods` exited with status code 69

### Expected Behavior

As far as I am aware, this package wasn't added by a developer and is instead generated code. So, I wouldn't expect to receive any errors on this package. 

I do deploy our app from a github repo so all of the changes are tracked. This package was present at the earliest commit we have, so I am assuming this is generated code. I have also verified that creating a blank project also has this package imported. 

### Steps to Reproduce

1. Create a project
2. observe that flutter_web_plugins is used in the main.dart file
![image](https://github.com/user-attachments/assets/bc033521-7840-439c-9282-4ebde620d352)

3. try deploying and see that code magic returns an error on this file. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcjfsMx2rsdY17X5be5Fv2UUQlAgTLIFse0aRR4cGICuELAQfMzsX0NKQuLiTFBiPFGGimUe/srMv87xDMY4FxasG5RM0JVAZhfxZFO5VZfXCYewen8lTN1XI0iP37SRsBNCWLdtWF4c6k+pNa3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/fb2c23bf-8537-49ec-a4f2-668fb5b29925)
![image](https://github.com/user-attachments/assets/3b3e18ce-bd99-4967-846d-6b60e3244e43)

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

### Additional Information

This blocks me from publishing my app which halts my development progress. I am not sure of the implications of removing this package. I am open to sharing the repo's code as well, but there isn't any differences related to this package that I am noticing.

**Comment by dannymeese** [comment]
Is there any way to downgrade / stay in the old version? I didn't account for having to replace dependencies randomly on a Tuesday. Flutter shouldn't be required to update for flutterflow to still work.

**Comment by staplKody** [comment]
not that I am aware of. We were given a heads up about the upgrade, but I didn't expect a generated package import to cause me issues.

**Comment by rzambroni** [comment]
Hi @staplKody, thanks for the report! I've forwarded this issue to the team for review. In the meantime, removing the `flutter_web_plugins` dependency should serve as a workaround.

I'll keep you updated.

**Comment by tensoralex** [comment]
The issue with flutter_web_plugins is because after 10/22/24 FF update, flutter_web_plugins: any appears in the pubspec.yaml.
This is (flutter_web_plugins) actually part of flutter SDK and should not have been added to pubspec.yaml.
Removing flutter_web_plugins: any from pubspec.yaml would fix the issue with flutter_web_plugins error as a workaround.

**Comment by doublerr** [comment]
FWIW, I tried just removing it from `pubspec.yaml` but received more errors:

```
Because XYZ depends on flutter_google_places from git which depends on google_maps_webservice from git, google_maps_webservice from git is required
...
```

So will all these cause issues?

```
http_parser: any
google_api_headers: any
google_maps_webservice: any
```

Edit: I removed these just as a test and a build / deploy succeeded. I'm not recommending this to others just an FYI and will defer to FF team.

**Comment by jasonsears** [comment]
I found this suggested fix and could build and run my application locally. Update the pubspec.yaml with the following in place of flutter_web_plugins: any

  flutter_web_plugins:
    sdk: flutter
    
Unfortunately, my production deploy is via github action and it's failing.

**Comment by RhysAi** [comment]
I also managed to deploy my webapp to firebase hosting with this change:
flutter_web_plugins:
sdk: flutter

However, once successful the standard hosting screen "Welcome to Firebase Hosting" appears and my deployment only consists of three files.

**Comment by quintusvw** [comment]
I have the same issue as @jasonsears but I use the place picker from FlutterFlow. Seems the latest version of FlutterFlow has introduced a couple of breaking changes (5.0.8 released October 23, 2024 - Flutter version is 3.24.2).

I hope the FF team can get this resolved as our development and deployment is quite dependent on this functioning.

**Comment by iwanwmys** [comment]
I have the same issue, I (temporarily) resolved it using the reply on Kody's community post. https://community.flutterflow.io/ask-the-community/post/flutter-web-plugins-doesn-t-exist-jqsPj4LVwwFR3Je

But would prefer not to do this. Hope the FF team can get this resolved ASAP. Thanks!

**Comment by malhakeem** [comment]
It seems like I have the same issue as well

**Comment by Thesergiolg99** [comment]
Having the same issue when deploying from github

**Comment by Jensoulus** [comment]
same issue here

**Comment by Spixz** [comment]
My error was the following (due to the FF 22/10/2024 update):

`The current Dart SDK version is 3.4.3.
Because xxxxx depends on webview_flutter_wkwebview >=3.15.0 which requires SDK version >=3.5.0 <4.0.0, version solving failed.`

Before the flutterflow update, the flutter version used by FF was 3.22.2 which used Dart SDK version 3.4.3. The new update uses flutter version 3.24.2.

To run the project locally, you'll need to update your flutter version to 3.24.2.

If you're using fvm, you can use the following command: `fvm global 3.24.2`

After that I get a second error `Resolving dependencies...
Because xxxxxx depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at [https://pub.dev](https://pub.dev/)),
version solving failed.`

So I commented out the following line `# flutter_web_plugins: any` in the pubspec.yaml.

My app then launched correctly.

**Comment by drdevinhopkins** [comment]
Same issue here, able to build on web now after I commented out "flutter_web_plugins: any" in my pubspec.yaml

**Comment by sachax** [comment]
I have the same issue:

`Because xxxxxxxx depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at
  https://pub.dev), version solving failed.`

**Comment by staplKody** [comment]
I see this has been marked as closed. Obviously because I am deploying from github I can comment out the import myself, but what needs to happen to remove it from the generated code that's housed in flutterflow?

**Comment by PrenSJ2** [comment]
@agreaves I think you might need to reopen this one 🫠 

This is also happening for me


Edit: temporary solution https://github.com/FlutterFlow/flutterflow-issues/issues/4444#issuecomment-2432579191


Edit 2: if just pushed my latest code from flutterflow, and they fixed the issue

**Comment by sachax** [comment]
I am stil getting the issue and just downloaded the code for compiling.
pubspec.yaml has: 
  flutter_web_plugins:
    sdk: flutter
    
`The current Dart SDK version is 3.4.4.

Because xxxxx depends on webview_flutter_wkwebview >=3.15.0 which requires SDK version >=3.5.0 <4.0.0, version solving
  failed.`

**Comment by kamleshwebtech** [comment]
I have added "flutter_web_plugins: any" under dependencies in my `pubspec.yaml` but getting following errors in the output:

```
Resolving dependencies...
Because testflutterapp depends on `flutter_web_plugins` any which doesn't exist (could not find package `flutter_web_plugins` at https://pub.dev), version solving failed.
Failed to update packages.
exit code 69
```

Issue not solved yet. Kindly check and help. Thanks.

**Comment by kamleshwebtech** [comment]
Hi, please add below code inside your `pubspec.yaml` file:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
```

It solved my problem, hope you will also be able to solve your problem. Thanks.
