### ISSUE TITLE
ChoiceChips, Certain Font Sizes Have Gradient Over Text

### ISSUE THREAD

**Issue by Luzzotica** [FlutterFlow/flutterflow-issues#4447]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After updating to the new version of the app, my choice chips suddenly had gradients over them.

![Screenshot 2024-10-22 at 5 40 39 PM](https://github.com/user-attachments/assets/167c3a81-e9b9-423c-b4b7-e5fccdb4cfa6)

Testing revealed that it was related to the font and font size.

Here is an example, roboto font, size 15:
![Screenshot 2024-10-22 at 5 38 47 PM](https://github.com/user-attachments/assets/0a258f39-03ef-4ec0-924a-e0c9c48bc079)

Roboto font, size 14:
![Screenshot 2024-10-22 at 5 39 01 PM](https://github.com/user-attachments/assets/b4a85922-6c37-4bbc-93e5-25c98bf665a3)

### Expected Behavior

I don't want a gradient over text on my chips.

### Steps to Reproduce

I'm not sure if this is an issue localized to my project, or there's steps to reproduce.

Ideally, you can reproduce by creating a new project, adding a chip in, and setting font to roboto.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8kisnLuJVOxN9c+KX2b/lsnmMsKUAjRY0zju1udxIdCOPnEooLOuPBdRBvWMyHfwlmP2KZhmcBpvDPv/zpBMEBCw+Cb7Y+1aoIQx7vXkeQV8msCZDpYUR7I+JQCUyy0bSv2hNvAMxwd2wa3WaYPuSifA3qQ6LbOkcdDuX+IpjPnkqrAh7dVhZZzQ0PRGaZTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

Roboto, font size 15:

![Screenshot 2024-10-22 at 5 38 47 PM](https://github.com/user-attachments/assets/e02e2485-e62e-4975-83dc-7431fffc4512)

Roboto, font size 14:

![Screenshot 2024-10-22 at 5 39 01 PM](https://github.com/user-attachments/assets/3d42626c-9fb0-4633-ab78-f17b06debd3e)

### Environment

```markdown
- FlutterFlow version: v5.0.8
- Platform: MacOS Desktop
- Browser name and version: Arc 1.65.0
- Operating system and version affected: macOS Sonoma 14.6.1
```

**Comment by paulperez-dev** [comment]
Hi @Luzzotica,

I wasn’t able to replicate this behavior on either the native MacOS app or the web. Are you able to reproduce it from a blank project on your end?

Thank you!

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
