### ISSUE TITLE
Pubspec Dependencies issue in custom code editor.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#445]
## Expected behavior (required)

- When I change the Pubspec Dependencies in one custom code, the pubspec dependecies in other custom code had removed and replace with the one that I changed in the custom code. See the video below.

## Current behavior (required)

Let's say
- A custom code named A has a dependency of Adep
- A custom code named B has a dependency of Bdep

When I change the dependency of A to AnewDep, the depdency of custom code B follows. (changed to AnewDep also).

## To Reproduce (required)

1. Add some custom codes with dependencies that has no version.
2. Change some of the dependencies to another without version.

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

N/A

## Screenshots / recordings

In the video, all of the widget has dependency of `fireflow` and when I change the dependency on one widget, all others follow to change their dependencies.

https://user-images.githubusercontent.com/5080329/216740562-c49a9613-ca9c-43b1-ac40-ac3b88e759df.mp4

## Your environment

* Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by Pepino-GR** [comment]
Hi thruthesky,

I can now reproduce your issue. Thanks for reporting

**Comment by agreaves** [comment]
Hi @thruthesky, thanks for the bug report! I can confirm this is now fixed. Please let me know if this is still occurring in your project!
