### ISSUE TITLE
Toggling Flutterflow Environment isn't changing which firebase project the built in AUTH commands point to, even after removal of the "stuck" environment. 

### ISSUE THREAD

**Issue by josiahbones** [FlutterFlow/flutterflow-issues#4452]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have (had...) 4 firebase projects set up for different environments. Even after fully removing them and attempting a firebase rebuild of all firebase elements in FF, built in FF commands for creating a user with Firebase is pointing to the wrong project, even after the environment carrying that project has been deleted, FF rebooted, removal of test app from phone etc. Essentially, production environment is now completely broken, and all Auth calls out of FF are pointing to a completely incorrect point. 

### Expected Behavior

Changing environment in FF should, at worst, resolve all built in FF Firebase Auth API calls to the related Firebase project. Ideally, we would have a toggle to set Production as the master auth channel for simplicity if desired, but as it stands right now. 

### Steps to Reproduce

Unknown. FF Project is stuck pointing to a completely removed environment. Removing the associated environment was attempted as a last ditch resolution to no avail. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESks/l8Yxgrv1e+s/xbsFQhQIgQ0QnU7gnlO1ucx4YB5jtE5YIY+LRQ0NKTdfkfQtmOk6KoGUz0fTIi+PxIcIEGEirUbZj0JVATjmVbGWQRYi7CpeSfnwnGcFhJ2WO4aS73whDCM5ucmAO6jqtNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

Proof of the bug is present on the (now removed) associated firebase project auth page, where I can fill it with Create User attempts, despite this firebase project not even being related to my project any longer, and all full resets/reinstalls to related testing software. 

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: MacOS Desktop
- Browser name and version: Mac app
- Operating system and version affected: Mac Sequoia 15.0.1
```

**Comment by josiahbones** [comment]
I have isolated the problem to an Android local run build. The web build still points in the right direction, but local builds do not, they seem to get stuck in an FF environment even if deleted later. Deleting the project folder and forcing a rebuild that way fixed the issue, but this is a serious problem with toggling and testing.

**Comment by Alezanello** [comment]
Hello, and I'm sorry you're experiencing this issue. I have a few questions to better understand the situation: Is this compilation issue happening in run mode, test mode, local run, or after you've downloaded the code and are using VSCode or the CLI locally?

Your answers will help us identify the problem more accurately. Thank you!

**Comment by josiahbones** [comment]
This was with a Local Run, run through FlutterFlow, testing on Android 14 to an actual phone.

**Comment by cindernet** [comment]
Hi can I add (and I'm not sure if it will create any issues) is after adding an environment, it cannot be removed at all. I haven't tried adding all the database parameters and syncs but after adding an environment it cannot be deleted.

**Comment by Presslive** [comment]
Same for me. https://community.flutterflow.io/ask-the-community/post/firebase-backend-switch-SSq4zuapUqjgOb7
Did you find an alternative?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Presslive** [comment]
Yes it still persist.

**Comment by Alezanello** [comment]
Hello!

I apologize for the delayed response. I’m still unable to replicate the issue on my end. I created three additional environments, bringing the total to four Firebase projects as you described. After deleting all except the production one, the app correctly authenticated with the appropriate Firebase project during compilation.

If you are still experiencing this issue, I recommend reaching out to FlutterFlow support via the in-app chat or by emailing **support@flutterflow.io**. They can check your project configuration directly to identify why this might be happening.

Thank you for your patience, and let me know if there’s anything else I can assist with!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
