### ISSUE TITLE
Flickering issue

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#446]
## Expected behavior (required)

Not flicker

## Current behavior (required)

Flickers. See video:

https://user-images.githubusercontent.com/11810973/216794111-d8e92452-7cf2-4172-9385-278e6812ce1d.mov

## To Reproduce (required)

1. I suppose this is web view related so just open the custom code view page

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

Custom code

## Your environment

* Version of FlutterFlow used: Feb 2
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by hariprasadms** [comment]
Hello @DanielEdrisian - Thanks for reporting this issue. I just tested it in my projects, but I'm not able to re produce it. If you have not tried it yet, could you try below steps and confirm the results.

1. Refresh the page ( Ctrl+ R)
2. Run in incognito mode  
3. Close and re open FF editor in a new browser instance.

Thanks

**Comment by DanielEdrisian** [comment]
I need to close and re-open my browser every time I want to fix it. The problem is I have to do that every time I open the custom codes page

**Comment by hariprasadms** [comment]
Ok. Thanks. One more a bit lengthy video ( min 25 seconds) showing navigating few pages through custom functions can help us to understand when exactly it appears.

**Comment by DanielEdrisian** [comment]
Ok it's not happening now, I will send a video later when it happens again. I don't know if that would be helpful because I may not necessarily be aware of what I did before that happened.

You could possibly look at my event logs before 3:35 PM and see what the pattern was?

**Comment by DanielEdrisian** [comment]
Ok it's not happening now, I will send a video later when it happens again. I don't know if that would be helpful because I may not necessarily be aware of what I did before that happened.

You could possibly look at my event logs before 3:35 PM and see what the pattern was?

**Comment by hariprasadms** [comment]
Thanks for letting us. As it is working fine for you now, we will mark this issue has closed. We can revisit to it, if it is persists again. Thanks

**Comment by DanielEdrisian** [comment]
Here it is again, happening in the firestore page:

https://user-images.githubusercontent.com/11810973/216853886-f04a14a1-8f4c-4f1b-94f3-42e254938d91.mov

**Comment by DanielEdrisian** [comment]
@hariprasadms
