### ISSUE TITLE
Error in action chain does not show in the project errors, causes code gen failure

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#449]
## Expected behavior (required)

All errors in action chain should reflect in the project errors view

## Current behavior (required)

One error in an API call did not show in the project errors view and caused a failure to push to github.

## To Reproduce (required)

1. Make an API call with some params
2. Call that API somewhere and pass all those params
3. Remove one param from the API definition
4. Push to github

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

N/A

## Screenshots / recordings

<img width="400" alt="Screenshot 2023-02-05 at 4 16 23 PM" src="https://user-images.githubusercontent.com/11810973/216854868-3e0152d3-95bc-4df2-91ca-c30358de87d9.png">
<img width="500" alt="Screenshot 2023-02-05 at 4 16 16 PM" src="https://user-images.githubusercontent.com/11810973/216854869-7d505d65-00c0-49cc-8f4f-dc0b210cf91c.png">
<img width="400" alt="Screenshot 2023-02-05 at 4 14 50 PM" src="https://user-images.githubusercontent.com/11810973/216854870-6f34b8cc-8512-476c-89ff-515aac10ea14.png">

## Your environment

* Version of FlutterFlow used: Feb 2
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): MacOS

**Comment by hariprasadms** [comment]
Hi @DanielEdrisian - It should be fixed now. Please check and confirm. And also while removing any parameters which are in use in api section, there should be a validation. Validations looks like below 

![image](https://user-images.githubusercontent.com/17435678/218113407-cc18994b-cc86-40d4-8507-84c9fb4d85dd.png)

Please check and confirm. If this issue still persists, please share bug report code as well. Thanks
