### ISSUE TITLE
Translation times out on Desktop (MacOS) app

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#45]
## Expected behavior (required)
Under Settings and Integrations -> Languages clicking either Translate All or Translate Page should fill the fields with translated text.

## Current behavior (required)
The expected popup that informs user that translation appears but is then replaced with an error message that service has timed out.

## To Reproduce (required)
1. Click Settings and Integrations 
2.  Click Languages
3. Click either Translate All or Translate Page
4. Wait for timeout

## Context (required)
It requires me to open a browser when I prefer the desktop app since it is better performant

## Your environment
* MacOS Desktop

**Comment by organicnz** [comment]
@ampapplarsen could you try the translation tool in the Chrome browser? Currently, this feature does not work on the desktop version of macOS. Hope for your understanding :)

**Comment by ampapplarsen** [comment]
> @ampapplarsen could you pls try the translation tool in the Chrome browser? Currently, this feature does not work on the desktop version of macOS. Hope for your understanding :)

Thanks for your reply! Yes, works as it should in the browser (I love this feature).

**Comment by organicnz** [comment]
> > @ampapplarsen could you pls try the translation tool in the Chrome browser? Currently, this feature does not work on the desktop version of macOS. Hope for your understanding :)
> 
> Thanks for your reply! Yes, works as it should in the browser (I love this feature).

Thank you for letting me know :)
