### ISSUE TITLE
Cloned projects allow symbol characters in name (but doesn't actually build)

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#450]
## Expected behavior (required)

Project clone validates name and disallows symbols (just like creating normal projects)

## Current behavior (required)
Popup allows symbols and gets stuck on cloning project. If you go to your projects you'll see it but it won't open.

## To Reproduce (required)

1. Clone project
2. Use ; in name
3. Confirm

### Bug Report Code (required, generate from Widget Tree)
N/A

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): Desktop

**Comment by hariprasadms** [comment]
Hello @johnbhiggins7 - I do not see cloning a project steps asking project name popup. Can you please share an image or a quick video of the issue.

**Comment by johnbhiggins7** [comment]
https://share.descript.com/view/SEo9pXpu0qc

**Comment by hariprasadms** [comment]
Hi @johnbhiggins7 - Thanks for sharing video clip. 
I can try the steps and see there is a validation message for special /symbol characters. It is not allowing to clone the project.

See below video,
https://user-images.githubusercontent.com/17435678/217946729-efa0f2fa-9747-49bd-ba10-2818d6ac0bf3.mp4

**Comment by johnbhiggins7** [comment]
Me neither anymore. Must've been fixed 👍
