### ISSUE TITLE
Error messages not being shown

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#451]
## Expected behavior (required)

If any, Errors should be shown.

## Current behavior (required)

Errors messages are not being shown when even when there are errors present after the update on 21 Jan, except for some custom functions, actions, and widgets related errors.

## To Reproduce (required)

1. Define a reference parameter on the page.
2. Use it to query doc form reference.
3. Then remove the parameter from the page and observe that no error is being shown but when you open the query the place parameter used is marked as red means there is an error.
4. This issue is present for all other types of errors except custom functions, actions, and widgets.

## Context (required)

Cannot find errors.

## Screenshots / recordings

<img width="1236" alt="Screenshot 2023-01-24 at 2 08 09 PM" src="https://user-images.githubusercontent.com/102008213/217201828-9352e200-c6c1-4506-b4e8-41cad601c7f9.png">
 Notice that there is an error present but no error messages are being shown

<img width="76" alt="Screenshot 2023-01-24 at 3 10 12 PM" src="https://user-images.githubusercontent.com/102008213/217202002-1ad4b79c-44ff-48d6-951b-0e05e1c9790b.png">

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
Hi @Shubham-VE. Could you provide the error report code?

**Comment by wenkaifan0720** [comment]
Hi @hariprasadms. Are you still experiencing such an issue? Could you provide a test project or an error report code?

**Comment by hariprasadms** [comment]
Hi @wenkaifan0720 - I have tested it and it is working fine now. I think we can close this issue.

https://user-images.githubusercontent.com/17435678/219947650-7578fc5f-0ee6-4b3f-8afe-485bd4730775.mp4
