### ISSUE TITLE
[Supabase] - Problem with querying list of integers by setting LocalState integer value

### ISSUE THREAD

**Issue by Swistu93** [FlutterFlow/flutterflow-issues#452]
## Expected behavior (required)
I want to query column "provider_services_array" which is type List(integer) for find any rows that matches LocalState which is single integer value

## Current behavior (required)
When i load page, there is never ending rolling indicator, and nothing happens. I've checked supabase responses status, this API call returns error code 400

## To Reproduce (required)

1. Create new page
2. Add container widget
3. Add backend query
4. Set filter query to column type List(integer), value from variable, set LocalState value which is single integer value
5. Run app

##Code can be included in this section if it is relevant to reproducing the bug.

Here is fragment of api call url

"search": "?select=*&provider_services_array=cs.10",
"url": "https://my_database_adress/rest/v1/providers?select=%2A&provider_services_array=cs.10"

response:

  "status_code": 400

### Bug Report Code (required, generate from Widget Tree)
 ITESz8mA249goeFe0LrycMFqhQMkQzM6bZI7ku1EdwEhfIznO7AAYuP4V1VLYteUT1BUC1qZvEU13NrOieP9VvU5OT+uG6U4yawFH1yjEA8=

## Context (required)
This bug is blocking me, i've found work around but its not good enough. i've used a other list with one integer value inside and changed type of filter relation to: "List contains any", then it's working, but its hard to handle properly when user is moving through app and want to change for example category of available services.

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/124684960/217246985-31b05671-5af6-4bf9-8fc1-f6d39d856575.png)
![image](https://user-images.githubusercontent.com/124684960/217247079-5a800818-0f24-4e20-b568-b106e8ed6744.png)

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
Hi @katherineqian. I used the `List Contains` filter and it does not seem to give the desired result (hangs indefinitely). `List Contains Any` works but we can't easily assign variables to the filter list right now. Do you have an idea of how to best resolve this issue?

**Comment by aemelyanovff** [comment]
Sorry for the slow response. It was fixed a while ago.
