### ISSUE TITLE
Custom functions - can't edit code since yesterday

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#4520]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since yesterday, when I try to edit the code of a custom function, it automatically moves my mouse pointer away from the edit code area

### Expected Behavior

Expected behavior is to be able to create and edit custom function code

### Steps to Reproduce

1. Create new page
2. Create custom function
3. See that you can not edit the code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kzcrqx49IsbRJ+KqJccFvij4vJjsja7sslu5DTUw0C4/mG7YASs77P1VeTbzhTFc3Imf9jmUd+sLGufbIN+06ZE+CY6Zg+rtiWgKXQj+7RZS3Dau0XWtPLNpKBWqB0MHU3CZSAPZvLXA87FyyJvKsZBLvJqLROEcdH8+aOd/+jX/uQ0SLb3kNh1JWeC/v

### Visual documentation

Impossible to capture visually, can be checked very easily

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 22, 2024
- Platform: Web
- Browser name and version: Version 129.0.6668.101
- Operating system and version affected: Windows 11
```

### Additional Information

Cannot create and edit custom functions since yesterday

**Comment by paulperez-dev** [comment]
Hi @adrfinance,

I wasn’t able to replicate the behavior you’re reporting. Could you please share a video of the steps you are following? This might help us better identify what’s triggering the issue on your end.

Thank you!

**Comment by paulperez-dev** [comment]
We’re closing this issue as we haven’t heard back from you. If you’re still experiencing the problem, please feel free to submit a new issue.

Have a great day!
