### ISSUE TITLE
NavBar disappearing when parameters in URL

### ISSUE THREAD

**Issue by younicornsJH** [FlutterFlow/flutterflow-issues#454]
## Expected behavior (required)
NavBar displayed on all pages where it is enabled, regardless of page parameters in URL

## Current behavior (required)
NavBar displayed on all pages where it is enabled ONLY IF no page parameter present in URL

## To Reproduce (required)
1. open on mobile https://foryou.flutterflow.app/influencers (no parameter in URL) --> nav bar showing
2. open on mobile https://foryou.flutterflow.app/influencers?platform=all (1 parameter in URL) --> nav bar not showing

### Bug Report Code (required, generate from Widget Tree)
ITFXksmBw8pOxdhE14fcc+1olmEwGUwbUOc7j9VEGAsjCePxP6QLPMz4XxBoSOqHeAhYBFD/jmQGpsr6k+HXJsYEGwicboh9zYdTH1yjEA8=

## Context (required)
Trying to provide my users with a consistent experience throughout the app: when viewing a page, always show the nav bar

## Your environment

* Version of FlutterFlow used: 3.3.0
* Platform (e.g. Web, MacOS Desktop): all
* Browser name and version: all
* Operating system and version (desktop or mobile): Windows / Linux / MacOS

**Comment by agreaves** [comment]
Hi @younicornsJH, thanks for the bug report! This is definitely a bug, which will be fixed on the next deploy!
