### ISSUE TITLE
The method 'showAlignedDialog' isn't defined for the class '_HomePageWidgetState'.

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#4546]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="993" alt="Screenshot 2024-10-23 at 10 57 22 AM" src="https://github.com/user-attachments/assets/4ecaa17e-58d0-4eaa-8ce5-a373436f8171">

https://www.loom.com/share/734051531eb04b9ab73d7cb459626ae3

### Expected Behavior

https://www.youtube.com/watch?v=7Qc7qLrdYj4&t=1s&ab_channel=KaleoDesignxNoCodeUIFlutterFlowTraining

### Steps to Reproduce

create page
add button to page
add component to page
button>>custom dialog>>open component normally works
add "align with the target widget" and the whole thing breaks
<img width="1010" alt="Screenshot 2024-10-23 at 10 53 59 AM" src="https://github.com/user-attachments/assets/15789b8c-2bca-465e-9186-0f6bfc726059">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z/Hqx89god9J1s76csExqCU5JnoibZ03m9ZRaCgoIYyuOpl/evXsUBFCZ8O6dwhYO0Smmk8ywNrwjYbxO/Y6IRSZfJxIz4dQWA7hQn26a5OBEbmeY3R5I/5XJ0ym57bUqwhQKvpvW0IG2k+YOuyXVhXqQJv1IndISq/LZO4=

### Visual documentation

https://www.loom.com/share/734051531eb04b9ab73d7cb459626ae3

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: mac os desktop app latest
```

### Additional Information

https://www.loom.com/share/734051531eb04b9ab73d7cb459626ae3

**Comment by rzambroni** [comment]
Hi @chaggmuffin,

Thank you for bringing this to our attention! I was able to confirm the issue you're describing and will forward it to the team so they can take a closer look.

We appreciate your report.

**Comment by rzambroni** [comment]
Hm i believe this might be related to your [other issue](https://github.com/FlutterFlow/flutterflow-issues/issues/4548) about using local-run with components and then hot-reloading, if i restart the local-run test session it works on my end.

**Comment by ghost** [comment]
> Hm i believe this might be related to your [other issue](https://github.com/FlutterFlow/flutterflow-issues/issues/4548) about using local-run with components and then hot-reloading, if i restart the local-run test session it works on my end.

sup rz thanks for taking a look

I suspect it is but not sure how exactly

I started projects from scratch and had the problem for a bit and then when I restarted my machine the align dropdown problem has kinda gone away for me intermittently? I havent found the problem

The local run crashing when a component is added is still happening and pretty insanely disruptive to workflow.

**Comment by sbis04** [comment]
Basically, it's happening because aligned dialog adds a new Flutter dependency but there's no `flutter pub get` command after that. I'll update to add that command whenever a hot restart is done (will keep the hot reload as it is for now). Once the fix is deployed, it should be solved while doing a Hot Restart.
