### ISSUE TITLE
Cannot create library -> Custom domain issue

### ISSUE THREAD

**Issue by yadaniyil** [FlutterFlow/flutterflow-issues#4547]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to create the library but cannot press the "publish" button because of the error "projects deployed to custom domains cannot be published as a library".

### Expected Behavior

It's newly created project, no custom domains used, I reckon library should be publishable

### Steps to Reproduce

1. Create new project
2. Add some update to the project, like adding any widget
3. Commit the progress
4. Try to deploy as a library but see the "projects deployed to custom domains cannot be published as a library" on button hover

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89gofVA7ZPyccBspyQ7OWk3U5Io18pOEC0jF7KuBuw2euD4UBJBTfWjaVNcHGeLoF8KpN71v9/fGvQrCyeqfaZ4yqVqVRXke2ileJTXDaq0YUBTJ+hbGBDH0raVhyR7ALNYdCRm7F6yNumiZz7DFOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/d72e3d62-a295-4f89-9ac7-c60b36c4d623

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: macOS Web
- Browser name and version: Google Chrome Version 129.0.6668.90 (Official Build) (arm64)
- Operating system and version affected: macOS Sequoia 15.1 Beta (24B5070a)
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue, but the good news is that we’ve already tracked it internally. I’ll link your report to the existing internal ticket to ensure it's addressed, and I’ll close this one as a duplicate so we can focus all efforts on resolving it. Thank you for your understanding!

**Comment by leighajarett** [comment]
The issue has been resolved internally and should be fixed in next weeks product release, so sorry about this!
