### ISSUE TITLE
[Edit] Adding ANY component breaks local run... web test environment fine (Late initialization error)

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#4548]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/8646fa79a8bf418c953bc38eff449079

### Expected Behavior

Not that

### Steps to Reproduce

new page
delete top bar
add button
local run mac desktop -this works
convert button to component
hot reload
breaks

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89gocNG1qX6b8FvmiURMjslR78Zlu1TdCs8GZT0B4kcYs+kfklUcOKlTwhMeVr9nmIX/MrLjvzXJsEoYU2rfYhc+ahMEDnJZD+VeJCbO4S3b2tTM8RTI3Kj0JmJuSVQWcB0WlIs2k+UHem+fDLfHqbQCzM4AOa4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://www.loom.com/share/8646fa79a8bf418c953bc38eff449079

### Environment

```markdown
- FlutterFlow version: latest
- Platform: mac
- Browser name and version: na
- Operating system and version affected: macOS
```

### Additional Information

https://www.loom.com/share/8646fa79a8bf418c953bc38eff449079

**Comment by ghost** [comment]
Additional information

Doesnt only happen when converting a component

Seems more fundamental

https://www.loom.com/share/8dfe18f92a154db884d51ee71b044141

Seems like simply adding a component to the page and it breaks

But if you then relaunch the local run then it works

So it is insanely annoying but potentially not critical

**Comment by rzambroni** [comment]
Hi @chaggmuffin,

Thanks for your report and detailed video, I was able to replicate the issue you're describing. I will send it over to the team so they can take a look.

Thanks!

**Comment by ghost** [comment]
> Hi @chaggmuffin,
> 
> Thanks for your report and detailed video, I was able to replicate the issue you're describing. I will send it over to the team so they can take a look.
> 
> Thanks!

Ok cool thanks!

Excited to get this resolved since it is quite disruptive to the workflow of this project since it is SQLite project and needs local run

**Comment by leighajarett** [comment]
Hi there, sorry for the delayed response. This actually seems like a Flutter thing, not necessarily a FlutterFlow thing. I think you just need to make sure you're doing a hot restart as opposed to a hot reload when you add a new component. It has to do with the way Flutter handles state.
