### ISSUE TITLE
5.0.8 introduced bug: Transient dependency crash the app (apicall+listview)

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4554]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a lib "B" with an api call that is used in a listview, when i consume it in a project it works, but if I add a transient dependency (add lib A to lib B) the consumer project crash at compile time (test mode) with this bug:

![image](https://github.com/user-attachments/assets/b5f99643-608d-49dd-af95-80ac373cda61)

### Expected Behavior

The app should not crash if a transient dependency exist.

### Steps to Reproduce

1. create lib A, publish
2. create lib B:
    2.1. import lib A
    2.2. add an api call (with any content)
    2.3. create a component "mylist", add a listview
    2.4. use apicall on listview (with infinite scroll and generate-dynamic-children)
    2.5. publish lib B
3. create project
    3.1. import lib B
    3.2. create a component "wrapper", add "mylist" lib component
    3.3. add "wrapper" to home page
    3.4. execute test mode, you will see the error.
    
IMPORTANT NOTE:
You can delete the "lib A" dependency from "lib B" and the project will run without bugs.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l8j14otOseFK0L6JbsBv9SE5Jl81RJIN1NZRaCsofePrOpkAf8/7UFtUOLCrTHNMPmeaimQX/MrTufDxDPAnNTuZbtVR/rl6EjrMZzqWVJStBoS3b2hSP51UGECH3MHQnyYlVbR0V3Aj13GqBe69b3XYK7L7DlgSDua4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

BUG:

https://github.com/user-attachments/assets/e2915859-ba6e-4f67-bf49-8ef1a1365088

.
.
.
WITHOUT TRANSIENT DEPENDENCY THERE IS NOT BUG:

https://github.com/user-attachments/assets/1b1ba178-a41a-4694-be35-830f480d2039

### Environment

```markdown
- FlutterFlow version: 5.0.8+ (october 22)
- Platform: Web
- Browser name and version: chrome 130.0.6723.60 
- Operating system and version affected: Win 11
```

### Additional Information

Project bug report code:
IT40l8j14otOseFK0L6JbsBv9SE5Jl81RJIN1NZRaCsofePrOpkAf8/7UFtUOLCrTHNMPmeaimQX/MrTufDxDPAnNTuZbtVR/rl6EjrMZzqWVJStBoS3b2hSP51UGECH3MHQnyYlVbR0V3Aj13GqBe69b3XYK7L7DlgSDua4XdeK2SrDX1iXc2URm05KZDPz

Library B bug report code:
IT4wl8j14otOseFK0L6JasJVhSQsGDsgauYomMB9Qis8GqLuPe0UWMzBUBFUON+6TQlqJGCjhXMX/Mr9v+HxJsAnOkmufqJyzaoBYA7JfGOnMrK1Ca63b2hSP51UGECH3MHQnyYlVbR0V3Aj13GqBe69b3XYK7L7DlgSDua4XdeK2SrDX1iXc2URm05KZDPz

Library A bug report code:
IT4wl8j14otOseFK0L6JasJVhSQsIjp/bIEwmu59bCs9f5ToPJYQe8/6PxdoUtO6Twl6JmGcp14e3POLuOLhL/YrGw6cGqJ6zZFuZg3gWnujb8yTF7maT0B7I+NjIGqC58GVuSJ/BLFYWFlg3V6qJvOWcHTtHrq2Imo4Sq/LZO4=

**Comment by nev-21** [comment]
Hello @leighajarett @Alezanello, **_please help_** all the projects stop working with the new release, we can't execute test mode.
It took me a while to realize what the problem was.

**Comment by Alezanello** [comment]
Hello Nev-21!!!<br><br>I wasn't able to replicate it at all, I followed every step carefully and everything worked as expected, let me share you the public projects in order for you to see them if I missed something<br><br>LibA - [https://app.flutterflow.io/project/q-a-2717-lib-a-5z3olk](https://app.flutterflow.io/project/q-a-2717-lib-a-5z3olk)<br>LibB - [https://app.flutterflow.io/project/q-a-2714-lib-b-ysso8t](https://app.flutterflow.io/project/q-a-2714-lib-b-ysso8t)<br>Consuming Project - [https://app.flutterflow.io/project/qa-2717-8litg0](https://app.flutterflow.io/project/qa-2717-8litg0)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f510e70a-4e7c-4be7-b256-318b71394e8a/d563a946-31f7-4b46-b818-07e7673f9c77?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNTEwZTcwYS00ZTdjLTRiZTctYjI1Ni0zMThiNzEzOTRlOGEvZDU2M2E5NDYtMzFmNy00YjQ2LWI4MTgtMDdlNzY3M2Y5Yzc3IiwiaWF0IjoxNzI5NzI1OTAwLCJleHAiOjMzMzAwMjg1OTAwfQ.83TL5R4koxVQpd2vMjefkycVzvyBSec2qvUGZ3a0Ng8 " alt="image.png" width="1918" height="963" />

**Comment by nev-21** [comment]
I cloned the projects, and after import them in order, they crash:

![image](https://github.com/user-attachments/assets/2eb430c5-69cb-4695-9d58-3bff3da719c7)

**Comment by nev-21** [comment]
I have tested 2 things:

1. In the public project, when you want to download the code, an error appear

![image](https://github.com/user-attachments/assets/4c2dd26f-aa8c-4bd3-9a05-aafd8f600902)

2. I clone the project, the download works, I checked the code, it seems that the public Lib A is not recognized, that is why it works to you, maybe you have to put a component in your Lib A and use it in Lib B in order FF recognize the Lib A in the generated code. (when FF recognize lib A then it should crash)

![image](https://github.com/user-attachments/assets/b466cd21-e7e1-426d-9c81-d271f9aaee86)

**Comment by nev-21** [comment]
Hi @Alezanello please could you check it? 

In case you need I send you how I reproduce the bug starting from the public link you shared:

1. clone libA libB and the project
2. publish cloned libA
3. inside libB:  
    - delete the import of original-libA,
    - import cloned libA,
    - publish
4. inside the project:
    - delete import of original-libB,
    - import the published cloned libB
    - in "WrapComponent" delete "Container" add "ListOfApiCall"
    - execute testmode **_you will see the error_**

If the bug is not appearing to you, maybe you have to create a component in libA, and consume it in libB.

Please, let me know if you need something more from our side.


Bug report code:

- Cloned project
ITFTh/LhuYZijMgD+KrycsEwtGMRGUMcWOdEl+tuZwgbIoznBu0QY+LeaRFBTtOkaVNcM06Ljk8G+dbqhs7LJ/kpPQ6bR4s71KpucwrOe2i5R7bUCai8fXwlRN1jfR3AyruFnh5vBMhoWF1m2FOmNtyiQT7DBOu/Zwh9f6PHaOI=

- Cloned libB
IT4wh+flzIthnO5I+r6JasJVhSQsGDs+apIrjupuESs8GqLuPe0UWMzBUBFUOM+qY2x2ImCgmnEX/MmOvuL1NPFeNTSaG6U6yqlhEgnMUXKiRczQPIS3b2hSP51UGECH3MHQnyYlVbR0V3Aj13GqBe69b3XYK7L7DlgSDua4XdeK2SrDX1iXc2URm05KZDPz

- Cloned libA
IT4wh+flzIthnO5I+oSJasJVhSQsIjt7RL87m+1uRis9f5ToPJYQe8/6PhNuOc/mS2xqPmGMp140082PvuPDKPcrFyWqba5J/rlbWwLKQj2WVpuTF7maT0B7I+NjIGqC58GVuSJ/BLFYWFlg3V6qJvOWcHTtHrq2Imo4Sq/LZO4=

**Comment by Alezanello** [comment]
Hello, I apologize for the delayed response. It appears that adding a component to Library A has triggered an error in the consuming project of Library B. I will escalate this issue to our engineering team for further investigation. Thank you for your patience.

**Comment by nev-21** [comment]
Thanks, please help us asap, this is critical as I can't execute the projects!
