### ISSUE TITLE
It is not possible to use a callback parameter in a component action block

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#4555]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is not possible to use a callback parameter in a component action block

### Expected Behavior

Should be possible to use a callback parameter in a component action block

### Steps to Reproduce

1. Create a component and add an action parameter
2. Create an action block at the "Component Level"
3. Try to add the callback and it's not possible

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITwSlfLl8Yx1m8ta1YSJbvpahjgXJlx/U400lu5+FQwgHOv2B+0Uf8+kMlZVZ/2kdwl9PVr88X8z06HKhuOSUu84KRGrRrp416VITjrKWXy5QLWxDs/heUFQM9tgIHKP3cCvmSRdPup1WC04yWOQOO+9bA7aGYzHDUc/AP/9Op3Nn3inHDLCUDho5D0APHHQEeQUdhLWhbXNj/YFu4S28spd7lEJm+uuha+vPVDuKnqmUl65KdAaIiJ1tekQ8OAS

### Visual documentation

https://www.loom.com/share/9a881f8564c44c73af6d8b50552939cc

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 22, 2024 - Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Version 130.0.6723.58 (Official Build) (64-bit)
- Operating system and version affected: W11
```

### Additional Information

Found it in another issue

https://github.com/FlutterFlow/flutterflow-issues/issues/2501#issuecomment-2156378836

**Comment by Alezanello** [comment]
Hi there!

I watched your video and tried to replicate the issue. Currently, it's not possible to manually add an action callback inside an Action Block. You attempted to achieve this by copying it, but as the builder indicates, executing an action callback within Action Blocks isn’t supported at the moment.

This limitation isn’t specific to Component Action Blocks—it applies even if you create an App-Level Action Block, such as on the homepage, where you’ll encounter the same restriction.

However, you can execute the callback *after* the Action Block is completed. The Action Block can return information to the Action Flow, allowing you to retrieve any data you need and then trigger the callback, passing the required parameters.

**Comment by Franco98404** [comment]
> However, you can execute the callback after the Action Block is completed.

That is the current solution I am using right now, but it is not practical because it creates duplication of actions. An example is that if you click a button or press the enter key, you have the same flow of actions, but doing that can lead to errors because I can make changes in one part and not in the other.

Could you put it as an improvement request?

**Comment by Alezanello** [comment]
Of course! we already tracked this internally for development. While I can't provide an exact timeline for when it will be implemented, I can assure you that our engineering team have it on their radar.

**Comment by Franco98404** [comment]
Related to this, it is also not possible to use Auth actions inside an action block. Can you also add this as an enhancement request or should I create a new issue?

**Comment by Alezanello** [comment]
In this case could you create a new issue? We already have it tracked but maybe with your issue created I can link to it, so far no user asked for it, we only have it tracked internally, so with this I may push a little more to the engineer team with your request linked to it

**Comment by Franco98404** [comment]
Perfect, I just created the new issue:

https://github.com/FlutterFlow/flutterflow-issues/issues/4662

**Comment by Alezanello** [comment]
Thanks a lot, I'll close this one too as a feature request, I already make sure the team to have knowledge about this to improve the capacities of the action blocks!
