### ISSUE TITLE
Infinite scroll with a reversed Listview doesn't work as expected

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#458]
I want to make a custom chat page with an infinite scroll. Currently, if I enable infinite Scroll for a ListView with the reverse option enabled it will eventually be sorted top to bottom and not reverse.

## Expected behavior (required)
The list starts from the bottom to the top and if I scroll up the listview loads the documents. 

## Current behavior (required)
enabling the reverse option the infinity scroll is not ordering the items in the correct way. It loads the documents from top to bottom. And the list doesn't start with the latest document. 

## To Reproduce (required)

1. Create new page
2. add a listview
3. get a fireabase backend query from chat messages 
4. add filter: timestamps decreasing
5. enable infinite scroll
6. Enable the reverse option on the listview widget
7. Observe that the the listview loads the documents from top to bottom
- turning off the infinite scroll enabled option, the listview works as expected

### Bug Report Code (required, generate from Widget Tree)
IT40jM/q4c5PmOZE7rr+KcJV+T45KWJ5a7gr0MFraCotCLbkOpgcf/fOYkRBXubhdAhqeU6kgWoW0cmKuITUVscoOQ+Yc7pRwc9yTDnhWTqiWq3SU/HUACkbeacOQSj6

## Context (required)
I want to make a custom chat page with an infinite scroll. Currently, if I enable infinite Scroll for a ListView with the reverse option enabled it will eventually be sorted top to bottom and not reverse.

**Comment by hariprasadms** [comment]
Hi @kicsijohn - Thanks for posting this issue. In the steps point 4, you have mentioned that _" add filter: timestamps decreasing "._ decreasing or increasing order can be controlled in ordering property not in filter property. Correct me if I am wrong in understanding the issue. However, I have assumed the property '_ordering_' in-place of _'filter'_ and investigated the issue. 

There are two pints to highlight. 

 1. I can agree, there is an issue, where ListView widget is not listing the data properly when reverse and infinite scroll properties are on. Refer below video clips.

Example, 
Listview widget with order-by selected as decreasing and infinite scrolling is on. 

Expected result is, data should be in order - 1,2,3,4.....40
Actual result is, data displaying in the order - 40,39,38......3,2,1

https://user-images.githubusercontent.com/17435678/217840371-5bb7f6bb-3f7f-47bc-9b1b-38d6b15e5744.mp4

But when infinite scrolling is disabled. The data displays as below.

https://user-images.githubusercontent.com/17435678/217842700-96849ee0-d300-445a-b45e-7edaaeb892a4.mp4

2. However,  the kind of data listing you are trying to achieve can be done having a ListView with increasing order + infinite scroll on. I hope you have already tried this.  If not, try this configuration and let me know how it goes.

**Comment by realimposter** [comment]
I noticed this same issue where reverse doesn't work in combination with infinite scrolling. The Reverse option is necessary for bottom up scrolling chat feeds like discord/messaging etc. Reversing the database query order doesn't work if you have a large number of documents, and you need the 10 newest for example. My current work around is loading only 100 documents and disabling infinite scroll, but its limiting to the user and is causing some performance issues

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. The fix will be released in the next update (most likely some time next week).
