### ISSUE TITLE
Wrapper leave extra space for conditionally hidden elements

### ISSUE THREAD

**Issue by tannakartikey** [FlutterFlow/flutterflow-issues#459]
Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When some elements are rendered are dynamically using the Wrapper widget, if an element is conditionally hidden, the spacing for that element should not be rendered. 

## Current behavior (required)
Let's say I am rendering 5 elements with spacing between each of them set to 10. Out of 5 elements 2nd and 3rd are not rendered because of the conditional visibility setting. In this case the spacing between 1st and 4th element will be 30 instead of 10.

## To Reproduce (required)

1. Create a new page
2. Add Wrapper widget
3. Add an element with a small width. Let's say an image or a button 30px wide
4. Render 6-7 elements with noticeable spacing, let's say 25px
5. Hide an element or multiple elements using conditional visibility. Just set "false" value to condition
6. Observe the empty spacing left for the element even though they are hidden.

### Bug Report Code (required, generate from Widget Tree)
```
Expanded(
  child: Wrap(
    spacing: 25,
    runSpacing: 25,
    alignment: WrapAlignment.start,
    crossAxisAlignment: WrapCrossAlignment.start,
    direction: Axis.horizontal,
    runAlignment: WrapAlignment.start,
    verticalDirection: VerticalDirection.down,
    clipBehavior: Clip.none,
    children: [
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Visibility(
        visible: false,
        child: Image.network(
          'https://picsum.photos/seed/246/600',
          width: 50,
          height: 50,
          fit: BoxFit.cover,
        ),
      ),
      Visibility(
        visible: false,
        child: Image.network(
          'https://picsum.photos/seed/246/600',
          width: 50,
          height: 50,
          fit: BoxFit.cover,
        ),
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
      Image.network(
        'https://picsum.photos/seed/246/600',
        width: 50,
        height: 50,
        fit: BoxFit.cover,
      ),
    ],
  ),
)

```

## Context (required)

![image](https://user-images.githubusercontent.com/422544/217574489-8eedb2a7-6c1a-4faa-8cda-ae33be58ec78.png)

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Hi @tannakartikey - Thanks for posting this issue. 

This is issue mostly related to wrapper widget spacing is not considered while using conditional display. Mostly to do with  UI of FF editor. Otherwise, It works fine in run mode, rendering images inside wrapper widget while using conditional display.

Below is the quick vide for developer debugging info.

https://user-images.githubusercontent.com/17435678/217852898-1c9e5ea0-1eed-4914-b2f2-38ea93f44c63.mp4

**Comment by tannakartikey** [comment]
@hariprasadms I have faced in the issue in rendering as well and not just in the builder UI

Here is the screenshot from the Debug screen

![image](https://user-images.githubusercontent.com/422544/218256459-0a268a9e-18ba-4bd8-b03c-e79440c41d63.png)

Here you can see the components and the settings on the Wrap element (notice two elements are hidden with `false` constant)

![image](https://user-images.githubusercontent.com/422544/218256485-d1cc2834-46a1-4ec3-889d-acfa1e7400ec.png)

**Comment by hariprasadms** [comment]
Hi @shelpert - Do we have any updates on this bug please.

**Comment by shelpert** [comment]
Hi,

This is unfortunately not a bug, but rather the way that the `Wrapper` widget works. In the code example above, the `Visibility` widgets are still children of the `Wrapper`, so even if the `Visibility` widget returns an empty container when its child should not be visible, the `Wrapper` will still put space between them.

The solution to this problem is to generate the children of the `Wrapper` dynamically from a list, and filter that list based on your condition. In general, it's best practice to generate children dynamically anyways when you have this many. Hope this helps!
