### ISSUE TITLE
Firebase Dynamic Links don't work when using a Custom Domain

### ISSUE THREAD

**Issue by asmengistu** [FlutterFlow/flutterflow-issues#46]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

Reported on FlutterFlow community: https://community.flutterflow.io/c/bugs/firebasedynamiclinkscustomdomains-in-info-plist-bug

## Expected behavior (required)
iOS App should be able to open dynamic link with a custom domain and direct user to the appropriate screen correctly.

## Current behavior (required)
When clicking the dynamic link, the iOS app just redirects users to the home screen of our app. The only way to get the dynamic link to work is by adding FirebaseDynamicLinksCustomDomains to our Info.plist file with the custom domain as the value.

## To Reproduce (required)
1. Use a custom domain scheme in Firebase dynamic links.
2. Try to open a dynamic link using that URL scheme on iOS and it won't work.
3. Open the Info.plist and add FirebaseDynamicLinksCustomDomains as an array with the value being the custom domain (for example: https://links.appname.app/, where in our case, appname is our app's name [we own [appname.app](https://appname.app/) and we have a subdomain properly set up at [links.appname.app](https://links.appname.app/)]).
4. Try to open the dynamic link again on iOS and it will work this time because of the Info.plist change.

## Context (required)
We do have our custom URL Scheme defined properly in App Details > Deep Linking & Routing in Flutterflow. We have another app that doesn't use custom domains for Firebase dynamic linking and just uses the Google provided .[page.link](https://page.link/) one and dynamic linking works correctly on that app without any changes to Info.plist.

## Your environment
* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 106.0.5249.119 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): iPhone 14 Pro on iOS 16.0

**Comment by Pepino-GR** [comment]
So if we want to enable and set the Dynamic Links in FlutterFlow and set the value FirebaseDynamicLinksCustomDomains in FF, then it's a feature request.

**Comment by MaggieThomann** [comment]
Thank you for looking into this! Makes sense it's a feature request -- any idea on timeline for it?

Sidenote: I applied to FlutterFlow's founding engineer position last week and would love to work on adding features like this 😜

**Comment by Pepino-GR** [comment]
I do not have any idea of the timeline. Welcome on board. Yes, please implement ...  Greetings from Germany

**Comment by MaggieThomann** [comment]
Haha just waiting to hear back on my application at this point. Aber grüße aus Bayern!! 😄 @Pepino-GR
