### ISSUE TITLE
:app:minifyReleaseWithR8 error

### ISSUE THREAD

**Issue by rapiddev-ff** [FlutterFlow/flutterflow-issues#4605]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Еhe app has stopped building for Android while Flutterflow doesn't show any error. Have been seeing the error related 'Build failed' related to minifyReleaseWithR8. iOS build don't have any errors and builds correctly

### Expected Behavior

Have ability to make a build for Android

### Steps to Reproduce

Push the build to Google Play. It shows failed logs. Here is the screenshot of the logs.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khfLl5YpItbxY17X5bcZvvGE7H0d9TLJEpu0bWUkbGO/4OrMcPMn7NxdoZ9CzaH4/HFH+vEEH/+DWiPDxVsEqaE6VGIhD/7lUdhPPY3GRaaaVDLuVe0RDP55YCBGG4ZiRph1+Wct1L2wg2FOXftiUZz6Cf9qOYwx5e6fDbOY=

### Visual documentation

https://www.loom.com/share/7108663ee1184695bc2190f14fc53ebd?sid=ae50edd9-783e-4aef-8aff-e00d32e2e334

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform: Web
- Browser name and version: Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Version 23H2 (OS Build 22631.4317)
```

### Additional Information

It stopped working yesterday and didn't work for 2 days already. We can't make changes in the live app.

**Comment by Alezanello** [comment]
Hello!

First of all, I’m sorry you're experiencing this issue. It seems this specific error is already being tracked in another report: [GitHub Issue #4602](https://github.com/FlutterFlow/flutterflow-issues/issues/4602). To streamline our efforts, I’ll close this ticket as a duplicate and focus our attention on the main issue.

In the meantime, I recommend checking your local dependencies to ensure they are up-to-date, as this might be causing the problem with the latest update.

Thank you for your understanding, and feel free to follow the progress on the linked issue.
