### ISSUE TITLE
App State Data Type Lists not saving multiple additions

### ISSUE THREAD

**Issue by scottwyn13** [FlutterFlow/flutterflow-issues#4608]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Wehn adding multiple items to an app state list the list items do not save. When adding a sinle item to an app state list it does save.

### Expected Behavior

Should save list items whether it is a single item being added or multiple.

### Steps to Reproduce

Create app state variable
Set type to Data Type
Set Is List to True
Add multiple items to list
Navigate to another page
Return to app state variables
List will be empty

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40k/rY26Zhm9th5pfydPZGpGYmKXp9R4ANscJ7aCsofePrOpkAf8/7UFtUOM+qT29YO2GkjnwX/MrNveDtJe0qG0+qR75l1c8BTQ3yUlulV4ibPpS3b3dCRO9MI1SeyKeJoR1DBLN0SE4A716UfueWTj7dNKbbNW1EIuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/e8712c01-cf2f-4462-a893-c46c211879ae

https://github.com/user-attachments/assets/099b6c61-4f28-4015-9618-0af215c1d5bb

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: MacOS Desktop App
```

**Comment by Alezanello** [comment]
Hi there!

Thank you so much for bringing this to our attention. I’ve confirmed the issue and will be forwarding it to our engineering team for a fix. We’ll keep you updated on the progress!
