### ISSUE TITLE
"Cursor position" setting has no effect in Set Form Field Action 

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#4609]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set the "Cursor position" property in Set Form Field Action to **End** or **Highlight**, it has no effect.

<img width="392" alt="image" src="https://github.com/user-attachments/assets/df115225-c8d8-4978-b8f0-75efea6bbad6">

### Expected Behavior

It must put the cursor to the end as described in the info button:

<img width="265" alt="image" src="https://github.com/user-attachments/assets/4d66209c-f81e-48dd-873d-b04ef3414b92">

### Steps to Reproduce

1. Create new Page
2. Add a Text field
3. Add a button
4. Set on Tap action of button to "Set Text Field", enter a "Test" as value and choose **End** as Cursor Position.
5. Test the button.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KhfHq2ItIsdsE0L6JdMJVmiMvMjsmbYIelsB+WRAgIrbxG7YMWvfObhJeZ+m+THxcL1n8gXE1zNqJv4bqA+UnGyyZGKpPyJYIEBbvZEauVYipEc6CZEEmO9xJJVy50raZpQhACMx1ci0Y2GeQB9mAQgPtQb6wDVVNRMiIBIP/n2+qQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="392" alt="image" src="https://github.com/user-attachments/assets/df115225-c8d8-4978-b8f0-75efea6bbad6">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8 released October 22, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome
Version 130.0.6723.59 (Official Build) (arm64)
- Operating system and version affected: MacOS
```

### Additional Information

A button should set the contents of a textfield, which the user should be able to type the rest.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I can confirm that this is not the expected behavior, and I will forward it to the engineering team for review and a possible fix.

**Comment by mmearly** [comment]
Hi all, the fix for this has been released! We have also added a new boolean property here (Focus Field When Set) to make it possible to set the form field without without clicking into it.

**Comment by timdcochran** [comment]
Hi @mmearly I just tested this with a fresh project. Set Form Field -> Cursor Position -> Start and End work, but Highlight does not. Looking at the code, I can see for Start and End options, FF is generating TextSelection objects that make sense:

Start:
            WidgetsBinding.instance.addPostFrameCallback((_) {
              _model.startTextController?.selection =
                  const TextSelection.collapsed(offset: 0);
            });

End:
            WidgetsBinding.instance.addPostFrameCallback((_) {
              _model.endTextController?.selection = TextSelection.collapsed(
                offset: _model.endTextController!.text.length,
              );
            });

But Highlight doesn't create a selection:

Highlight:
        if ((_model.highlightFocusNode?.hasFocus ?? false)) {
          safeSetState(() {
            _model.highlightTextController?.text = _model.value3;
            _model.highlightFocusNode?.requestFocus();
          });


Here's the bug report code: IT8kkMrl7ZBOseFe1bXpbflv9SkXIjsiaIIrkdVqEEgjF5SuEok+ePekblpuYsyBeHxYfWeLknsKw+DUhIbUVvk7GASBRtw/3JVqUznKbD6WR6aOEpCWenRtHdJUf1yE5KuzvxF8A+F0WGQH7DmEf/OAThXXH7rEOzMRDv2jDIb5ngOkGx7dLDtHzTcXEx7eTI5ODEz25eKMrop5yfj/0w==

Do I need to raise this as a new issue or can this one be reopened?

**Comment by mmearly** [comment]
Hi @timdcochran, thanks for the callout. In my testing, the default behavior when requesting focus on the text field without specifying a text selection had been to highlight the entire body of the field, but I now see that this behavior is not universal across platforms. I'll go ahead and add an explicit text selection in this case. No need to raise a new issue.

**Comment by mmearly** [comment]
@timdcochran This has been fixed in the latest web release of FlutterFlow and will be included in other platforms with next scheduled release! 🥳

**Comment by timdcochran** [comment]
Thanks @mmearly we use this action throughout our project and I noticed yesterday it was working! 🥳
