### ISSUE TITLE
Execution failed for task ':app:minifyReleaseWithR8' Hi, I write here because my report was closed because of duplicate. We check dependencies in our app and added latest versions. But the bug still exists

### ISSUE THREAD

**Issue by rapiddev-ff** [FlutterFlow/flutterflow-issues#4611]
Hi, I write here because my report was closed because of duplicate. We check dependencies in our app and added latest versions. But the bug still exists

_Originally posted by @rapiddev-ff in https://github.com/FlutterFlow/flutterflow-issues/issues/4602#issuecomment-2436258238_
            
![ff - bug report](https://user-images.githubusercontent.com/186096988/379923260-3810385f-994a-4881-a6e1-b889842118e6.png)

Bug report code: IT4khfLl5YpItbxY17X5bcZvvGE7H0d9TL0rse5+bxcvCIyqOpgIePTBM0RDXse8S29iO0yJjWoW0873i/zlD8dcPTOqRtV5yZdQaDyVQTmXSpCDFJWvdkB8L9xRC2mB5Ker3B1QWfJfdGQb1GD3BvPKXjPYK4OzCm40Dq/LZO4=

**Comment by Alezanello** [comment]
Hello again!

Thank you for following up! I marked your previous issue as a duplicate so we can keep track of all updates related to this specific error in one place. This helps us focus our efforts effectively. When two issues are related, we typically keep the first one open and mark the others as duplicates, linking them internally for streamlined follow-up.

The bug has been fixed on our end, but it hasn't been deployed just yet. We're currently testing to ensure everything is working smoothly and will release the hotfix as soon as possible!

Thank you for your patience!
