### ISSUE TITLE
Can't Push to Repository (Github)

### ISSUE THREAD

**Issue by sockpapi** [FlutterFlow/flutterflow-issues#4612]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when I push my code to github, I am getting this error (this happens on mulitple FF apps) 
<img width="603" alt="Screenshot 2024-10-22 at 8 05 29 PM" src="https://github.com/user-attachments/assets/179cfb8e-cc34-45ab-8338-0e176c059ba6">

### Expected Behavior

- successful push to github 

### Steps to Reproduce

1. Push to Github

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fhsmAsJJPrttG0LruY+9VpCYXJlw5bedIjuxAEBAaB5vqOqQIYs7Rbk1JYsOGdwlIJFmj8XgK0qHIvdr1EsddOkysQ4Ne+MxuYAziQj+VRYyJC6WKX2ttO5phC0PD056wmA9dA7BqLlZk6ly6C+uRfBHsJbLuIFg3RcqYKp/IkWCULA7BMiZFxmNecCfn

### Visual documentation

here is a loom video of me trying to push to github and screenshot of the console log and network. 

https://www.loom.com/share/4452164d024d4ad0ba6ff223fed5336e?sid=97fd7833-9399-47ba-bb31-d34309583ca4
<img width="1517" alt="Screenshot 2024-10-24 at 9 55 23 AM" src="https://github.com/user-attachments/assets/39bb9a73-44d0-4648-accd-4948ab048f77">
<img width="1564" alt="Screenshot 2024-10-24 at 9 55 19 AM" src="https://github.com/user-attachments/assets/9936deaa-756d-457c-9adf-a276f0778452">
<img width="1492" alt="Screenshot 2024-10-24 at 9 54 57 AM" src="https://github.com/user-attachments/assets/8eb5922e-0c51-4396-b1e9-8bfea2c4fa3b">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8 released October 22, 2024
- Platform: Webapp and Mac App
- Browser name and version: Google Chrome Version 130.0.6723.60 (Official Build) (arm64)
- Operating system and version affected: Mac OS Sequoia 15.0.1 (24A348)
```

### Additional Information

This is happening on multiple projects: 
Project ID: roofquotes-homeowner-app-w3fphh
Project ID: rq-partner-app-p2bwbm

**Comment by Alezanello** [comment]
Hello!

I didn’t find any issues in your code. I was able to download and compile it without any problems. Are you still experiencing the error on your end?

**Comment by finallyfit** [comment]
I'm experiencing the same exact issue with my project. Widgets that haven't been touched in months are suddenly failing and preventing a push to GitHub. It's completely random.

It's completely random, too. I had a ToggleIcon widget that failed, so I replaced that with a regular icon. A few hours later, that icon widget failed, so I replaced it with a ToggleIcon, and now it works fine again.

**Comment by sockpapi** [comment]
Hey @finallyfit ,


I solved it by:

1. Disconnecting to repo
2. Deleting repo from GitHub
3. Create repo in GitHub (same name) 
4. Reconnecting flutter flow 
5. Push repo

**Comment by finallyfit** [comment]
@sockpapi you're awesome, thank you for letting me know! I'll do this next time I encounter this error. Much appreciated!

EDIT: it happened to me again. Just based on this instance, it seems that disconnecting the repo from FlutterFlow then reconnecting it seems to get rid of the issue. No need to delete the repo on GitHub. Will report again if it comes up.
