### ISSUE TITLE
Unable to use Toggle or Checkbox 

### ISSUE THREAD

**Issue by sahawnehwajdi** [FlutterFlow/flutterflow-issues#4614]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

build failed for all toggle and checkboxes in the project when both trying to run in Test Mode and Web Deployment

### Expected Behavior

it should not fail!!

### Steps to Reproduce

Issue surfaced after October 22, 2024 FF update

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlPHluIlhsshE+6nbKe5Gp2AwGUQaa+cZjO1udzIgfePrBux2d8/4SBdtTuGqaVNcGVaIjmQG/9LHiPz9FfkoIUmVfr5HyaVcVQ7ee2ilVJeVDbqoYXBAJ5hPGBGD55iW2glCVcteci0EwEOXf9mRH3bDFOu/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/f17a9e00-b46d-4d00-978c-77c0d9af69b5)
![image](https://github.com/user-attachments/assets/9538a16b-1751-46ae-bfa0-4e8a25248ca3)

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform: Web
- Browser name and version: Microsoft Edge Version 130.0.2849.56 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Pro version 10.0.26100 Build 26100
```

### Additional Information

Unable to Test the app or do Web deployment

**Comment by Alezanello** [comment]
Hello!

I reviewed your project and noticed you replaced the toggle icons with simpler icons. Did this solution work for you? I also tried replicating the setup on a new project with toggle icons and checkboxes, and I was able to compile it successfully, so it seems this may not be a general issue.

If the error persists, please reach out to our support team through the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io) for more personalized assistance.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ed461734-1918-4250-8a3a-0c42ba2999d8/b1c2ec0a-981f-42cb-b734-6b72ffa4fd00?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZDQ2MTczNC0xOTE4LTQyNTAtOGEzYS0wYzQyYmEyOTk5ZDgvYjFjMmVjMGEtOTgxZi00MmNiLWI3MzQtNmI3MmZmYTRmZDAwIiwiaWF0IjoxNzI5ODI0MTU2LCJleHAiOjMzMzAwMzg0MTU2fQ.-DuudkXgpxbRxdJ3TlToOo7euPrC6Mj-tYhe4ozVAP0 " alt="image.png" width="1289" height="227" />

**Comment by leighajarett** [comment]
Hi there, this should be resolved now! Please let me know if you are still experiencing the issue
