### ISSUE TITLE
[PAGEVIEW] smooth_indicator  method not found,  compilation error

### ISSUE THREAD

**Issue by StayTips** [FlutterFlow/flutterflow-issues#4615]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

during compilation of desktop mac app the compilation error appear if page indicator is enabled; does not appear if is disabled

### Expected Behavior

page compile normally

### Steps to Reproduce

1. create a page
2. add page view component
3. enable page indicator
4. select local device for testin
5. run app

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glfLq2It1xPVA7qqNKe9aqCQvJj43Rpc0sNpuZxYjGYDuBIYiaczBP0tpZNSlYFFXKEWGgl4KpfzwiuPLGMABBxWtQbZgzpBcVgv/Xn2/aovTOpaJPkd5N8FYGXKZ0cOJuBUnFPV2R0IZ7DiIBN+RfCrrNO77Zwh9f6PHaOI=

### Visual documentation

https://www.loom.com/share/f354ff28c09e4514af832cd08d815bcb

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: MacOs
- Browser name and version: NA
- Operating system and version affected: MacOs Vewntura 13.7
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. I wasn’t able to replicate it on my end, and it looks like the PageView widget in your project may have been replaced with another widget. We also deployed a fix to production yesterday, so could you please check if the issue persists for you?

Thank you!

**Comment by StayTips** [comment]
issue resolved
thanks
