### ISSUE TITLE
Debug panel no longer appears in DevTools during local run

### ISSUE THREAD

**Issue by timdcochran** [FlutterFlow/flutterflow-issues#4616]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Debug panel no longer appears in DevTools during local run

### Expected Behavior

Debug panel appears ni DevTools during local run

### Steps to Reproduce

1. Create a new blank app.
2. Local run the app.
3. Open DevTools.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClPHlw852j7xH7aqNdcFB/WAvKUR/RYI7le1hRQ8aHZPOD+x/fMnBN1dUOcylYXx+fFm0jjkX/MrIvtjEUPQDFxyuR4hyzrhUcQnNUXynVZiaDoS3b2pQBfhgf2LGy4mJux55AMRvLHAt2GeuI96tHzDaJYzNIUYzHuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/7e46d539-7963-4e55-a2cf-847463d0dfc7)

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: macOS Desktop
- Browser name and version: Arc Version 1.66.0 (55166)
- Operating system and version affected: macOS 15.0 (24A335)
```

### Additional Information

More difficult to debug

**Comment by rzambroni** [comment]
Hi @timdcochran, thank you for the report! That’s unusual—I attempted to replicate the issue, but I can see the debug panel as expected.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9b8bf7a1-7f0e-42c3-9658-8d4e0df4f589/70a79d47-96df-43db-993e-005955ba480f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YjhiZjdhMS03ZjBlLTQyYzMtOTY1OC04ZDRlMGRmNGY1ODkvNzBhNzlkNDctOTZkZi00M2RiLTk5M2UtMDA1OTU1YmE0ODBmIiwiaWF0IjoxNzI5ODg4NTk1LCJleHAiOjMzMzAwNDQ4NTk1fQ.O-ee_0jZF68uRcQZCCHzz8KZzyqxb6U2i8ri2L7rLNw " alt="image.png" width="1392" height="657" />

Does this happen in all your projects, even blank ones? I tested on macOS using a local run on an iOS Simulator; was that the setup you were using as well?

Also, there’s a new version of FlutterFlow released today (v5.0.9). It might be worth trying with the latest version to see if that resolves the issue.

Thanks again!

**Comment by timdcochran** [comment]
HI @rzambroni yeah this is happening for all projects including blank ones. Some additional things I've now tried:

- Moved Application Support/io.flutterflow.prod.mac and let  FlutterFlow rebuild it.
- Installed v5.0.9
- Tried Safari and Chrome

Issue persists.

**Comment by rzambroni** [comment]
Hi Tim, 

I'm reaching out to our internal team to see if someone can replicate the issue, as I haven't been able to reproduce it on my end. I'll keep you updated on any findings. In the meantime, could you confirm if you're running locally on macOS and using an iOS simulator, or if your setup differs?<br><br>It would be really great If you can also share a video of the process you are following until opening the devtools. 

Thanks for your help.

**Comment by timdcochran** [comment]
Hey @rzambroni just wanted to let you know I ended up rebuilding my Mac from scratch and the problem is now solved. There must have been some corruption somewhere in my Flutter install causing the issue.

**Comment by rzambroni** [comment]
Thanks for letting us know Tim!
