### ISSUE TITLE
Invalid Action reverts last valid action.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#462]
## Expected behavior (required)

- When working on UI Builder, `Invalid action` error must revert the invalid action only. Not the valid action.

## Current behavior (required)

- The UI Builder reverts the valid action when the Invalid Action happens.

## To Reproduce (required)

1. Add a row
2. Add two container as the children of the row.
3. Give color red on the last container.
4. Add a Spacer as a child of the row.

Since there is no size bound on the row and it's parent of the row, Adding `Spacer` is an invalid action. But it will revert the color of the last container.

### Bug Report Code (required, generate from Widget Tree)

ITFTk871z4tPsfVc+Krycu0xmjgWI0MCXLhE0dcadEkYC4+tPYkqO+r+VBZvOualT25qP1SYoEgE7tr7i9jpCfQpAAerTNE2k/UwKlCvHAM=

## Context (required)

N/A

## Screenshots / recordings

https://user-images.githubusercontent.com/5080329/217997253-d75e1a2b-2eda-4c2e-a3ea-32a6f72d7c72.mp4

## Your environment

* Version of FlutterFlow used: FlutterFlow 3.0 Feb 10, 2023. Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: Chrome Version 109.0.5414.119 (Official Build) (arm64)
* Operating system and version (desktop or mobile): MacOS Ventura 13.0.1

**Comment by hariprasadms** [comment]
Hi @thruthesky - Thanks for posting the issue. I can reproduce this issue. 

https://user-images.githubusercontent.com/17435678/218111818-707890d7-b69e-4493-ade0-56f70e272a1e.mp4

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @thruthesky! Extra thanks for the clear and succinct steps to reproduce.

This will be fixed in the next update.
