### ISSUE TITLE
Firebase Phone Authentication Pincode Dispose Error

### ISSUE THREAD

**Issue by tas246** [FlutterFlow/flutterflow-issues#463]
## Expected behavior (required)
A simple phone authentication with firebase, on the Pincode screen, when the verify Pincode action is run, user is directed to the logged in page.  

## Current behavior (required)
This results in perfect behavior running in simulated mode on FlutterFlow, but run on iPhone hardware results in a error on dispose indicating the Pincode controller widget was still in use

## To Reproduce (required)

1. Create new phone login page for firebase authentication 
2. Create phone verify pin page.  Both pages have one Submit button
3. Run on iPhone hardware 
4. On verification of Pincode submit button press, receive runtime error indicating dispose issue as Pincode widget is still active 

## Your environment
* Version of FlutterFlow used: latest
* Platform (e.g. Web, MacOS Desktop): iPhone 
* Browser name and version: chrome latest
* Operating system and version (desktop or mobile): iOS 16.3

**Comment by bulgariamitko** [comment]
Can you please provide a Bug Report Code as well. This is how you can create it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)

**Comment by tas246** [comment]
When I do that bug report code on the button that causes the issue, I get this:

Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

**Comment by tas246** [comment]
Bug Report Code:

IT4ki87huIpOxd9A7pDTbcBaiik4HHI4TLJEoetxc0gbfe/4BO0UZM7eUE9ocNCzaHxEB1r8nnwH/s72iePTE8cCaUiYQJxm+rl+ZVyjEA8=

**Comment by bulgariamitko** [comment]
Can you also include the runtime error that you get and the actions that you use

**Comment by tas246** [comment]
The action is simply a button that runs "Auth Verify SMS Code", with the PinCode field as the passed in controller.

Attached is the exception:

![Screenshot 2023-02-14 at 8 50 52 PM](https://user-images.githubusercontent.com/3086611/218914920-eae4fc24-09e1-4423-9f92-1a110b19ccd0.png)

**Comment by victoriahuang1** [comment]
This may be a Flutter related bug, since this is only happening on iOS

**Comment by tas246** [comment]
It seems like, as this only happens on the generated flutterflow code, and only when using the pincode widget, there should be something that can be done from the flutterflow end as a workaround.  I'm sure I could hack some changes together in VScode to patch this, but I don't think that's the mission of FlutterFlow.

**Comment by wenkaifan0720** [comment]
Hi @tas246. You are right. This will be fixed in our next update. Thank you.
