### ISSUE TITLE
Deep Linking - Android - Login after enable deep linkig

### ISSUE THREAD

**Issue by luisangellpz** [FlutterFlow/flutterflow-issues#464]
## Expected behavior (required)

When I enable deep linking for my project and generate the APK from FF, After I install the file on a device and login the app should start in the home page.

## Current behavior (required)

After the login, the app doesn't load the home page. The app successfully login but the home never finishes the load. It seems that the app can't find a parameter. The app only starts after I click the back button. 

## To Reproduce (required)

1. Enable deep link function
2. Download the APK file
3. Install the file on an Android device
4. Login
5. wait for the load of the home page

This error only seems when the app is freshly installed.

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1. Enable deep link function
2. Download the APK file
3. Install the file on an Android device
4. Login
5. wait for the load of the home page

### Bug Report Code (required, generate from Widget Tree)

IT40zMmAsJJgoddJ1arubPlFtGU5JnI7U68a0O1RaCosfZT2BLMcec/RVERBOce6dFFDeFmKiWoW0/yKvvD9EfUENTaBc4RD/roJZw2Vfz+XRKaSU/HUACkbeacOQSj6

## Context (required)

I can't post my app in the play store and use share buttons for android devices.

## Screenshots / recordings

https://youtube.com/shorts/_8tufs-ViWY?feature=share

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): Android

**Comment by hariprasadms** [comment]
Hi @luisangellpz - Thanks for posting the issue. 

We may need more information to understand the issue. Could you please tell us what happens when you launch the app in run mode and also installing apk without deeplinking enabled.

**Comment by luisangellpz** [comment]
When I run the app in run mode (with and without the deep linking enabled), the app only takes a few seconds loading then starts downloading the content of the page

https://www.loom.com/share/f858b609b4714fada63a99ec6989d346 

and 
When I install the apk without deeplinking enabled. The app works correctly and loads the home page components without the first loading.

**Comment by aemelyanovff** [comment]
I'm unable to reproduce the issue.

@luisangellpz Can you try reproducing the issue in a new project? If you can repro it this way, please update the steps with more detail (what pages you created, what type of auth did you use, what's on your home page, etc.)

If it can't be reproduced in a new project, I suggest reaching out to FlutterFlow support.

**Comment by aemelyanovff** [comment]
Closing as inactive. @luisangellpz please feel free to reopen the issue if you add steps to reproduce the issue in a new project.
