### ISSUE TITLE
Local Run Unable to Export Code after update to version 5.0.8

### ISSUE THREAD

**Issue by chimbangquaot** [FlutterFlow/flutterflow-issues#4640]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After updating to version 5.0.8, hot reload fails to export the code, not reflecting the changes made and the IDE shows that it is not up to date. I tried to create a new project to validate if there was a problem with my project or dependencies, but the same problem occurred.

### Expected Behavior

After updating to version 5.0.8, hot reload fails to export the code, not reflecting the changes made and the IDE shows that it is not up to date. I tried to create a new project to validate if there was a problem with my project or dependencies, but the same problem occurred.

### Steps to Reproduce

After updating to version 5.0.8, hot reload fails to export the code, not reflecting the changes made and the IDE shows that it is not up to date. I tried to create a new project to validate if there was a problem with my project or dependencies, but the same problem occurred.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

After updating to version 5.0.8, hot reload fails to export the code, not reflecting the changes made and the IDE shows that it is not up to date. I tried to create a new project to validate if there was a problem with my project or dependencies, but the same problem occurred.

### Visual documentation

After updating to version 5.0.8, hot reload fails to export the code, not reflecting the changes made and the IDE shows that it is not up to date. I tried to create a new project to validate if there was a problem with my project or dependencies, but the same problem occurred.

### Environment

```markdown
After updating to version 5.0.8, hot reload fails to export the code, not reflecting the changes made and the IDE shows that it is not up to date. I tried to create a new project to validate if there was a problem with my project or dependencies, but the same problem occurred.
```

**Comment by Alezanello** [comment]
Hi there!<br><br>To help us thoroughly investigate whether this is a replicable bug, could you please follow the proper steps for submitting a bug report? This will give us all the details we need to assist you more effectively.<br><br>You can find the guidelines here: https://docs.flutterflow.io/misc/submit-bug-report/<br><br>Thanks for your help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
