### ISSUE TITLE
 unable to locate asset since last update (24/10)

### ISSUE THREAD

**Issue by fafa16** [FlutterFlow/flutterflow-issues#4646]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to run locally on edge as I do everyday.But since yesterday's update, I have: Launching lib\main.dart on Edge in debug mode... Error: unable to locate asset entry in pubspec.yaml: "assets/fonts/Inter-Light.ttf". Failed to compile application.

I didn't change anything
What should I do?

### Expected Behavior

launch local app on Edge

### Steps to Reproduce

Start local run on Edge

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEezcrl5ZZPn71I+s/IcPlVrwMwJ0QlUIInj+0bWRMhNZjtO5kuOc/8YlhLYtfjYH56JGKKjkUJwPDeuIX1Nu46FyeVbrZaz4RXQT3JRj2QMbaWCLi/PERAHd1gfRW/58CnhBElBNNuZVo1712ALvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/c0c58add-7dd4-4028-8fd6-ecd504a6ae96)

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform:pc
- Browser name and version:Edge Version 130.0.2849.46
- Operating system and version affected: windows 10
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry you're experiencing this issue. The good news is that it's a known problem, and we're already working on a fix: [GitHub Issue #4442](https://github.com/FlutterFlow/flutterflow-issues/issues/4442). I’ll close this as a duplicate; please refer to the linked issue for any updates!
