### ISSUE TITLE
Animate changes for Icons (...feature request system is a black hole)

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#4650]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/50020bd59eb74c59b987c00e61c8f3ad

### Expected Behavior

ability to animate changes on icons

(...or ability to follow progress on feature requests)

### Steps to Reproduce

new project
create icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8sl8nf5Yt1rt9c+Kr2dvpV+T4vKUc7bZJFlutud0wdDOv3Ookle8jRbVtVZ8Dha1NIHVr8jmYK+aHMhvKeVvlcGxWCGZhl/5VXdxfwYzqnWrarDpCwdnEmLJ9MN2KF0ZiFrR1TPfNzW0Us706Ifuu8b3PaQa7NPlQdNciaF9vPnE3hLSPNEiBZ7yQXMG7eTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

https://www.loom.com/share/50020bd59eb74c59b987c00e61c8f3ad

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

https://www.loom.com/share/50020bd59eb74c59b987c00e61c8f3ad

**Comment by Alezanello** [comment]
Hello!

Have you tried adding the animation through the animation menu within the icon's properties? In FlutterFlow, every widget has the option to add animations, either for **On Page Load** or as an **Action Trigger**. Let me know if this helps!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d36ccd14-23c5-434c-a566-67a1e8672210/7ffd14d2-2145-45e0-a764-5b390ea82089?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMzZjY2QxNC0yM2M1LTQzNGMtYTU2Ni02N2ExZTg2NzIyMTAvN2ZmZDE0ZDItMjE0NS00NWUwLWE3NjQtNWIzOTBlYTgyMDg5IiwiaWF0IjoxNzMwMDgyNzI0LCJleHAiOjMzMzAwNjQyNzI0fQ.SXdyWnBTKNgvmOuzHGahs4RxtD1zX--QBpeADmw9FYI " alt="image.png" width="1137" height="804" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
