### ISSUE TITLE
Cannot Load Test Mode

### ISSUE THREAD

**Issue by UmmZoubayr** [FlutterFlow/flutterflow-issues#4652]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, since this morning, I've been trying to launch the test mode, but I keep encountering this error. I've added all the necessary domains in Firebase. I also did some research on Google but couldn't find a solution.

Also, on the web I have this error (see img)

### Expected Behavior

Test mode is supposed to work :/

### Steps to Reproduce

What have you tried so far?

- reconfig firebase file
- adding domains in flutterflow
- reupload firebase rules
- Try with VPN

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiPLq+ZdPschE+aXybMEwmicwGUwbUOc7j9VEGAsjCeKtEYkDP+DCXFtVcuqHT1V+GlX9oE4dwd6Oi9r9GsA3IS6CQKU4+c1xUxDjcEamR6qSDZOSW3BPM/xhCnam4ZiRmxYlHNVtV14uwF2Ee+mQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

Already Upload Img

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform: MacOS web
- Browser name and version:Chrome&Safari
- Operating system and version affected: macOS Monterey 12.7.4
```
<img width="440" alt="Capture d’écran 2024-10-24 à 11 26 04 AM" src="https://github.com/user-attachments/assets/ac7ad74f-45e9-4739-be7c-023546a86f09">
<img width="553" alt="Capture d’écran 2024-10-24 à 11 22 46 PM" src="https://github.com/user-attachments/assets/3d412273-1c07-4b31-9413-da1a249bcc70">

**Comment by rzambroni** [comment]
Hello @UmmZoubayr, thank you for the report! It looks like the image or screenshot you uploaded is broken or corrupted, so I'm unable to view the error you're describing. Could you please try re-uploading the image or, if possible, copy and paste the error message as text? This will help us take a closer look and assist you further.

**Comment by UmmZoubayr** [comment]
I have re-uploaded them, I think you can see them now @rzambroni

**Comment by UmmZoubayr** [comment]
I have the solve the test mode error, I had to use a VPN.
But I  still have the error in the console

**Comment by rzambroni** [comment]
Given the error and the fact that using a VPN resolved it, it seems likely you’re experiencing a DNS-related issue. While I’m not an expert, trying a different DNS provider, like Google’s (8.8.8.8, 8.8.4.4) or Cloudflare’s (1.1.1.1), might help stabilize the connection.

As for the console log, it's hard to say without more details—it could stem from a variety of issues, potentially specific to your project setup.

A few questions that might help narrow it down:

* Does the error occur at a specific moment, like during loading or a particular action?
* Do you see the same issue across other projects, or is it limited to the one you mentioned?

These details could help pinpoint the cause. Let me know if changing the DNS makes a difference or if any patterns emerge.
