### ISSUE TITLE
White screen before splash screen

### ISSUE THREAD

**Issue by nickydlt** [FlutterFlow/flutterflow-issues#466]
When I open my app, for some reason it initially flashing a white screen. The first thing the user sees should be the splash launch screen I've selected. I've seen other users on the forums express a similar frustration but a solution has never been provided.
I've also noticed some other apps built in flutterflow have the same issue, such as one that you guys featured a couple months ago in one of your mass emails - "Awair"

My project is https://app.flutterflow.io/project/catholicam-umn4m9

Here is a screen recording of the issue:
https://user-images.githubusercontent.com/112821773/218103956-831af666-cb27-44d6-9475-ae41faff8742.MP4

**Comment by thruthesky** [comment]
I agree. It takes a longer on white screen before the splash than the apps built with flutter.

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

**Comment by nickydlt** [comment]
@bulgariamitko I'd be happy to. I wasn't aware of a template (it's my first report). Where can I find the template?

**Comment by bulgariamitko** [comment]
@nickydlt you can find the template at the Read me section here 
https://github.com/FlutterFlow/flutterflow-issues

**Comment by crossxsecure** [comment]
Hi Team, I'm also experiencing the same white screen issue with the splash screen and on the verge of it when the device isn't connected with Internet it sticks to the white screen only.

Note: We're using Firebase Sign In here so I believe it might checks the user authentication and for that operation it may seeks for the internet which isn't available hence it sticks on the white screen.

**Comment by niklasgee** [comment]
Hi, I am having the same issue with all my FlutterFlow apps. A short White screen before the splash screen shows.
@nickydlt should we add a new bug report by using the template? Or is this one recognized by the team?

**Comment by katherineqian** [comment]
Hi @niklasgee and above - yes, this is recognized by the team as a feature request. It's related to how Flutter Web works, but we can add a splash screen to replace the white screen before the web app loads.

**Comment by niklasgee** [comment]
@katherineqian How is this possible? I have a splash art set, but the white screen still shows right before the splash art shows up. Its the same in all of my apps made in Flutterflow.

**Comment by smostovoy** [comment]
This is big issue for me on a dark theme. I had to change black logo to white to make it less obvious. On iOS it's a blank page before the spash page, on android first one with a small logo on a white background, second one - normal splash.
