### ISSUE TITLE
It is not possible to use Auth actions in an action block

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#4662]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is not possible to use Auth actions in an action block

### Expected Behavior

Should be possible to use Auth actions in an action block

### Steps to Reproduce

1. Create a new Login Page.
2. Enable Authentication and select Custom Authentication.
3. Configure the initial page settings.
4. Create a new Action Block.
5. Notice that the Custom Authentication option is not available in the Action Block. Additionally, if you copy an auth action from another location and paste it, it won’t work either.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol8/q25Bgocta0LrUb8FsgSQ4H0w1RLgomMpBZywgfZzzBLN/fPfQP1VBTsu/YAhUMVm2p14yw+jNkvDlNPApHwiZbYM++rhUSTnMTT+WabmTF7qKPEFtONJbN0C915ivsx1CWdV1SmAC23GQAuesST7ZGIzsIXo4Sq/LZO4=

### Visual documentation

https://www.loom.com/share/9cb293a07f10429c9101d19e9f5edc23

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 22, 2024 - Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Version 130.0.6723.58 (Official Build) (64-bit)
- Operating system and version affected: W11
```

### Additional Information

It's very helpful for me to update the Auth Token, Refresh Token, and Token Expiry Time using the "Update Authenticated User" action within an action block, as it allows me to reuse it across the app. For example, if I receive a database error indicating that the auth token has expired, I can trigger the action block to renew the token and reuse it throughout the application.

**Comment by Alezanello** [comment]
Thank you for bringing this up! You’re correct; this feature isn’t supported at the moment. The good news is that we’ve already tracked this request internally, and I’ll link your issue to it so the engineering team knows there’s additional interest. I’ll close this issue as a feature/enhancement request for now, but rest assured, the engineering team will be aware of it!
