### ISSUE TITLE
flutterflow_cli: export-code returns with no error but no code is there

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#4663]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I run the exact command given on my branch to export code locally, yet once it returns, there is no code in the folder I am executing the command from.

### Expected Behavior

The exported code should be there.

### Steps to Reproduce

1. Run the `flutterflow export-code` command from a folder, exactly as given in the Flutterflow UI
2. Wait for it to complete, observe no code

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43y/Lk085IosNm7s3iSfFWlhs7OWY5RI0zl9t7aCosfZT2BLMcec/RVERBTcylYGx2JGeGo2oW0v+Kk/GSEPpcISyWfrpPzql2URfifziWMZObFJWgW3ZBHd5PCmKYyKSruBBQJbJ0S3gE1E+MCfK/XgDDGbrQOlY4Dq/LZO4=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. We recently encountered a similar bug and deployed a fix two days ago. Could you check that you’re using the latest version?

To update, run the following command:

`dart pub global activate flutterflow_cli`

Please make sure it’s updated to version 0.0.24.

**Comment by bloemy7** [comment]
@Alezanello hey, I just upgraded, it now gives me a nice message saying `Downloading code with the FlutterFlow CLI...`, but ultimately code is still not there. Feels like it's going somewhere but I can't tell where. I'm not giving it any `--dest` parameter so it should be in the working directory. Any ideas? Quite urgent for me. Thanks!

**Comment by Alezanello** [comment]
In this case, try downgrading by running:

`dart pub global activate flutterflow_cli --version 0.0.22`

This should help as a temporary solution since it’s urgent. I’ll double-check on my end as well!

**Comment by bloemy7** [comment]
I was actually running `0.0.22` before - and I was already having this issue. So I'm not really sure what is happening here, but it's either already there prior to `0.0.22` or something that's on my end, though I'm just running the command verbatim @Alezanello

**Comment by Alezanello** [comment]
Then stay to the most updated version (`dart pub global activate flutterflow_cli)` and let me check !<br>Do the folder your are trying to download have any spaces in the path?<br>Like<br>C:/User Me/Local Folder/

**Comment by bloemy7** [comment]
No, simply “~/Downloads/“ basically on MacOS.

**Comment by Alezanello** [comment]
In my case I was able to download the code using the last version (0.0.24)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/eb574f7f-2420-4d65-a9f7-4b9f1e1810db/19a06410-ec26-46ff-8fc1-7436a186edd5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYjU3NGY3Zi0yNDIwLTRkNjUtYTlmNy00YjlmMWUxODEwZGIvMTlhMDY0MTAtZWMyNi00NmZmLThmYzEtNzQzNmExODZlZGQ1IiwiaWF0IjoxNzI5ODkxMjU1LCJleHAiOjMzMzAwNDUxMjU1fQ.znqBco6yhSnYffTYb2WmSEyD5muwobFGPNgTTPJSTJM " alt="image.png" width="550" height="118" />

Did you type the command manually, or did you copy it directly from the FlutterFlow app?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4c3d314a-bfaa-4645-9f3c-5c672af489dd/6a2af38f-3a44-4bd7-b12f-560e3953d757?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YzNkMzE0YS1iZmFhLTQ2NDUtOWYzYy01YzY3MmFmNDg5ZGQvNmEyYWYzOGYtM2E0NC00YmQ3LWIxMmYtNTYwZTM5NTNkNzU3IiwiaWF0IjoxNzI5ODkxMjU1LCJleHAiOjMzMzAwNDUxMjU1fQ.DXIPYx1_02SJdWbLIOvakdUhn7G-KNrYRyRkAVxp5qM " alt="image.png" width="361" height="338" />

**Comment by bloemy7** [comment]
I copied it from there. It never gets to the Downloading assets… 
Part for me in the CLI. Simply returns after the “Branch:…” line.

**Comment by bloemy7** [comment]
@Alezanello any ideas? I really need the code and am unable to get it.

**Comment by bloemy7** [comment]
@Alezanello this is really mission critical for us - I've been trying all possible commands, and nothing is working right now.

**Comment by bloemy7** [comment]
When I try to download manually from the `Download Code` button, it ends up having a Server Timed out error. So it seems like that's also what's happening using the cli? but I don't get any error message or anything else to help diagnose.

**Comment by bloemy7** [comment]
It just worked after updating to Flutterflow 5.0.9 (on the desktop app) and copying the download code from there - not exactly sure what the difference was there...

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!<br><br>About the command we added the Environment<br><br>Like this: flutterflow export-code --project \[PROJECT\] --project-environment Production --include-assets --token \[TOKEN\]
