### ISSUE TITLE
Custom Bottom Navigation Bar component on Flutterflow

### ISSUE THREAD

**Issue by Michaelsegooa** [FlutterFlow/flutterflow-issues#4664]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've created a custom Bottom Navigation Bar on Flutterflow.  After 3 clicks (of any Icon Button), the custom component is no longer visible. It disappears. I've tried everything, it seems like there might be a bug.

### Expected Behavior

The on-click event should navigate to a desired page of the app. However, the component disappears everytime after it's been clicked 3 times.

https://github.com/user-attachments/assets/c299afbc-d5a5-4488-bd63-ac5a13aec9b9

https://github.com/user-attachments/assets/0da438a1-2d4c-498f-bf4c-a99ec3cce7a7

### Steps to Reproduce

1. Create a custom Bottom Navigation Bar component.
2. Insert custom component to app pages (Home,User, Settings etc.)
3. Run/preview
4. Click Icon Buttons on the Navigation Bar compent
5. On-click function, the app should navigate to desired page
6. The custom component disappears after 3 clicks, instead of navigating

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXifHcx8pOm8BE+rXubu1sqycwGUALa+dI0tZ+TQ0jF5D4BIocYMzRN0toYMyzaH1MHU6WpGodwM73vt7hFO0rEzuVfphi+s51WhPPbHmgVpi1O6jtOnJAQPlWGHamyLuRrSJSXfRfV3gC7zqYCPOudz2Cf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/a9c20208-2674-47cd-96d3-44cfe06ac0c2

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 25, 2024
Flutter version is 3.24.2
- Platform: MacOS Desktop (Web)
- Browser name and version: Google Chrome Version 130.0.6723.70 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.6.1 (23G93)
```

### Additional Information

I cannot navigate to a page as the custom bottom bar navigation disappears after 3 clicks everytime.

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue, either in your project or in a new one. Could you please try to reproduce the issue in a new, blank project with just two pages and the custom navigation bar? This will help us see if the problem still occurs.

Thank you!

**Comment by Michaelsegooa** [comment]
https://github.com/user-attachments/assets/5313145f-3a5b-43f8-bbff-4f97af41ce64

**Comment by Michaelsegooa** [comment]
import '/flutter_flow/flutter_flow_icon_button.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import 'custom_nav_bar_model.dart';
export 'custom_nav_bar_model.dart';

class CustomNavBarWidget extends StatefulWidget {
  const CustomNavBarWidget({super.key});

  @override
  State<CustomNavBarWidget> createState() => _CustomNavBarWidgetState();
}

class _CustomNavBarWidgetState extends State<CustomNavBarWidget> {
  late CustomNavBarModel _model;

  @override
  void setState(VoidCallback callback) {
    super.setState(callback);
    _model.onUpdate();
  }

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => CustomNavBarModel());
  }

  @override
  void dispose() {
    _model.maybeDispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360,
      height: 100,
      decoration: BoxDecoration(
        color: FlutterFlowTheme.of(context).secondaryBackground,
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              FlutterFlowIconButton(
                borderRadius: 8,
                buttonSize: 40,
                icon: FaIcon(
                  FontAwesomeIcons.home,
                  color: FlutterFlowTheme.of(context).primary,
                  size: 24,
                ),
                onPressed: () async {
                  context.goNamed('HomePage');
                },
              ),
            ].divide(SizedBox(height: 16)).addToStart(SizedBox(height: 16)),
          ),
          Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              FlutterFlowIconButton(
                borderColor: Colors.transparent,
                borderRadius: 8,
                buttonSize: 40,
                icon: FaIcon(
                  FontAwesomeIcons.apple,
                  color: FlutterFlowTheme.of(context).tertiary,
                  size: 24,
                ),
                onPressed: () {
                  print('IconButton pressed ...');
                },
              ),
            ].divide(SizedBox(height: 16)).addToStart(SizedBox(height: 16)),
          ),
          Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              FlutterFlowIconButton(
                borderColor: Colors.transparent,
                borderRadius: 8,
                buttonSize: 40,
                icon: FaIcon(
                  FontAwesomeIcons.cloud,
                  color: Color(0x4DBA006F),
                  size: 24,
                ),
                onPressed: () {
                  print('IconButton pressed ...');
                },
              ),
            ].divide(SizedBox(height: 16)).addToStart(SizedBox(height: 16)),
          ),
          Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              FlutterFlowIconButton(
                borderColor: Colors.transparent,
                borderRadius: 8,
                buttonSize: 40,
                icon: FaIcon(
                  FontAwesomeIcons.userAlt,
                  color: Color(0xFFFF000E),
                  size: 24,
                ),
                onPressed: () async {
                  context.goNamed('Profile');
                },
              ),
            ].divide(SizedBox(height: 16)).addToStart(SizedBox(height: 16)),
          ),
        ],
      ),
    );
  }
}

**Comment by Michaelsegooa** [comment]
Uploading Screen Recording 2024-11-01 at 17.57.27.mov…

**Comment by Alezanello** [comment]
Hello,

I apologize for the delayed response. This issue is quite unusual, and I haven’t been able to replicate it on my end. I also accessed your project again to try copying the widget you created, but it seems there isn’t one available.

Could you share the custom widget code with me so I can attempt to reproduce the issue again?

Thank you for your cooperation, and I look forward to your response!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
