### ISSUE TITLE
Firebase Image Path Issue: Visualization Error After Successful Upload

### ISSUE THREAD

**Issue by ambience-kim** [FlutterFlow/flutterflow-issues#4666]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image_01](https://github.com/user-attachments/assets/694965cc-96e8-4cf6-b8ea-ead4e7ff15ca)
![image_02](https://github.com/user-attachments/assets/c544d543-35e2-4ed3-8ab0-7f7a9be06ce8)
![image_03](https://github.com/user-attachments/assets/19c1cc0e-acc2-4b27-874d-56e5a8ee684c)
![image_04](https://github.com/user-attachments/assets/9b5f13a4-e95d-4331-a8e8-bba6c4b57bfe)
![image_05](https://github.com/user-attachments/assets/afd4c73f-09f2-43d4-9c50-a87fd87a219e)
![image_06](https://github.com/user-attachments/assets/e6d2ec27-2f4d-4df3-b73c-3d705a89dc48)
![image_07](https://github.com/user-attachments/assets/2fb8bb31-bc99-425f-b418-c78849e476cf)

### Expected Behavior

Photos uploaded to firebase should be displayed normally.

### Steps to Reproduce

Please refer to the attached video.

https://github.com/user-attachments/assets/aa74a71c-22dd-410f-b7ac-3cafd6bb0979

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I don't see the "Get Bug Report Code" menu in the widget tree.
Please refer to the image for additional information.

### Visual documentation

[bug_report_20241026.pdf](https://github.com/user-attachments/files/17528765/bug_report_20241026.pdf)

### Environment

```markdown
- FlutterFlow version: latest version (update today)
- Platform: macOS, Desktop App
- Browser name and version: Chrome version 130.0.6723.59(official build) (x86_64)
- Operating system and version affected: macOS Venture 13.7
```

### Additional Information

![스크린샷 2024-10-26 오후 12 06 53](https://github.com/user-attachments/assets/f43510ec-501d-4570-9553-3e44131d56e9)

**Comment by Luca-Stoll** [comment]
Same problem here! Display of firebase image results in error "object progress event".

**Comment by Alezanello** [comment]
Hello!

Just to confirm, is this issue only occurring in Test Mode? Are Run Mode, Local Run, or any other tests working as expected?

**Comment by Luca-Stoll** [comment]
For me personally the error just vanished yesterday. I dont know why it was there and why its gone again (bc I did not change anything), but i have no issues with this anymore.

**Comment by ambience-kim** [comment]
### 1. Test Results
- Unfortunately, I am still experiencing this issue in test mode.
- I tested this issue by deploying it on both the web environment and the Android app (apk).
Additionally, no issues were observed in either the web or Android environments.

### 2. My Assumptions
If my memory is correct, this issue began occurring after I changed the Firebase settings as follows:

- When initially configuring Firebase, I set the Firestore server location to `asia-northeast3` (Seoul).
- For Storage, I chose the "Default" location, which displayed as `asia-northeast3` (Seoul) on the screen.
- As a result, I also chose the "Default" location for the Cloud Function server. (At that time, the Default location wasn’t displayed on the screen, but I assumed it to be `asia-northeast3` (Seoul).)
- However, I noticed the API response time was slower than expected. After verifying the API server location, I discovered that the Default location for Cloud Functions was `us-central1`, not `asia-northeast3` (Seoul).
![스크린샷 2024-10-29 오전 11 46 19](https://github.com/user-attachments/assets/5b31769e-a1f8-4799-a4b9-70908d27ae85)

- To resolve this, I reviewed the Firebase settings and found that I could change the Cloud Function region to `asia-northeast3` (Seoul), so I made the change.
![스크린샷 2024-10-29 오후 12 26 26](https://github.com/user-attachments/assets/43f01de1-60a9-4783-a8df-4ed525cf51bb)

- However, changing the region only updated the location for functions called through Private APIs after redeployment. For other functions (Push Notifications, Delete User Reference, etc.), deployment errors occurred, and their locations did not change.
- Therefore, I reverted the Cloud Function server location back to the Default setting.

### 3. Additional Testing
- Created a new project in FF + connected it to a new Firebase project ==> No issues.
- Created a new project in FF + connected it to the Firebase project with the issue ==> No issues.
- Based on this, I believe the issue is related to Firebase settings in FF.

**Comment by ambience-kim** [comment]
@Alezanello 
Please let me know if there’s any information I can provide to help resolve this issue. I’ll be happy to run additional tests and share the results with you.

**Comment by ambience-kim** [comment]
@Alezanello 
I am sharing the results of my tests up to today.

### Test Mode
- Image does not display (shows an Object ProgressEvent)
![스크린샷 2024-11-01 오후 2 02 31](https://github.com/user-attachments/assets/7102601f-8319-44dd-8dd1-92a13e226e7f)

### Run Mode
- Image does not display (simply not visible)
![스크린샷 2024-11-01 오후 2 01 45](https://github.com/user-attachments/assets/5c29183f-30ec-4bd4-ae94-84168b2bd4a9)

### Deploy (Web)
- No issues

### Deploy (Android)
- No issues

**Comment by ambience-kim** [comment]
@Alezanello 
Just as a note, I had completed the CORS settings in Firestore previously.
![스크린샷 2024-11-01 오후 2 16 07](https://github.com/user-attachments/assets/dc08ea08-0401-4a5a-bc05-6f8587ab6c4a)

**Comment by tyler4i234** [comment]
Are you still experiencing this issue, I having the same problem. If you fixed it i would love to know what you did!

**Comment by ambience-kim** [comment]
@tyler4i234 

I am still experiencing this issue. I created a new project in Firebase yesterday to test it, but the problem persists.

The only solution I've found so far is to create an entirely new project in FF and connect it to a new project in Firebase. However, this would mean giving up everything I've developed so far, so it's not an option.

**Comment by tyler4i234** [comment]
@ambience-kim, this problem really sucks. My project was working just fine and suddenly this is issue occured. This has to be a bug from the new update right?

**Comment by ambience-kim** [comment]
@tyler4i234 

To determine whether this issue is a bug or not, I believe we first need to establish a definition of what constitutes a bug.
That's why I asked ChatGPT the following questions:
![스크린샷 2024-11-05 오전 11 31 44](https://github.com/user-attachments/assets/0287426b-535e-4ca2-9bff-e655a56ac8a0)

I believe that the FF team would reach the same conclusion.

**Comment by ambience-kim** [comment]
@Alezanello 
I raised this issue about two weeks ago, and I was wondering if you could share any updates on its progress. 

As I mentioned before, I’m fully prepared to conduct any tests necessary to help resolve this issue, so please feel free to let me know if there’s anything your team needs from my side. I’d be happy to assist with anything.

**Comment by tyler4i234** [comment]
@ambience-kim I found a solution that worked for me. You need to disable CanvasKit (beta) Render in App Settings > Web Deployment > General Information. After you turn that off reload everything and you should be fine.

**Comment by rzambroni** [comment]
Hi everyone,

Apologies for the delay in following up on this. We’re actively working to get up to speed. Were you able to resolve the issue by disabling the CanvasKit beta?

If the issue persists, would it be possible for you to share a blank project where the issue can be reproduced? Unfortunately, we haven’t been able to replicate it in our own test projects, and having your example would greatly help us troubleshoot more effectively and speed up the resolution process.

Thank you for your patience and understanding!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
