### ISSUE TITLE
Nesting widgets visually does not work anymore

### ISSUE THREAD

**Issue by philipgertsch** [FlutterFlow/flutterflow-issues#467]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When I drag a widget under another in the widget tree - and wait for a few seconds - the dragged widget gets nested into the widget I dragged it under (hope it's clear what I mean :-))

## Current behavior (required)
No matter what I do, the widget NEVER gets nested, but instead the widget places itself just under the other widget (but on the same level).
https://www.veed.io/view/0f2f2589-885b-40d0-9dbb-4f9b7f58e4d1?sharingWidget=true&panel=share

## To Reproduce (required)
1. Create a page
2. Create two widgets
3. Try to nest one widget into the other by just visually drag the widget in the widget tree (not by pressing Ctrl+B!)

### Bug Report Code (required, generate from Widget Tree)
No bug report, as the app does not recognize this as bug.

## Context (required)
Well, it used to work, and like that I have to recreate every widget when I want to change the level of hierarchy.

## Your environment

* Version of FlutterFlow used: current
* Platform (e.g. Web, MacOS Desktop): does not matter, it happens inside the IDE
* Browser name and version: Edge
* Operating system and version (desktop or mobile): Windows 11

**Comment by victoriahuang1** [comment]
Hi @philipgertsch , thanks for the report. Notice how there is the loading circle when you drag widgets. While it's orange, dragging and dropping will nest the widgets. However, if you hold for a long enough time, the loading circle will complete and turn purple -- at this point, dragging and dropping will result in the widgets being at the same level.
Hope this helps!

**Comment by philipgertsch** [comment]
Hi @victoriahuang1, before you close the issue, have a look at the video I posted above. I did what you mentioned, but it just does not work the way you describe ... at least on my side. Try nesting a text inside a form .. or any other combination for that matter ;-)

**Comment by philipgertsch** [comment]
btw: When you try to nest a text inside a form, the circle never gets orange ... thanks for looking into it and keeping the issue open as this is really cumbersome

**Comment by philipgertsch** [comment]
Update: it seems to work now in most cases - thanks! :-)

**Comment by victoriahuang1** [comment]
Hi @philipgertsch I found a bug affecting certain cases. The fix should be going out with the next deploy :)
