### ISSUE TITLE
DocumentReference links are not displayed correctly

### ISSUE THREAD

**Issue by Ellweb3** [FlutterFlow/flutterflow-issues#468]
## Expected behavior (required)
There is a List<DocumentReference<Music>> in the application stack. I make an action to add the current reference to this list. I choose add to List option, select from Music Document - Reference. 

## Current behavior (required)
Now the reference can't be added. Instead the DocumentID parameter appeared, which is also impossible to retrieve without code.

## To Reproduce (required)

IT4kz/Hqx89grt9G7rqAbccw+Cg7NkQ3TLJMqNYbGA0hfIjwO5kqd/T7YhNLYteqTW9mI1GGpEkK09Lwj/HLIPYEOSiWGJxEz5oFH1yjEA8=

## Context (required)
I have a lot of things tied to lists in the local state - playlists, lists of mixed albums - lists of downloaded tracks and other

## Screenshots / recordings

![Screenshot (15)](https://user-images.githubusercontent.com/95847507/218153250-70a5c903-9ce3-400c-b43b-aa0932355696.png)

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): Web, IOS
* Browser name and version: Chrome Version 110.0.5481.77 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Ventura 13.1

**Comment by agreaves** [comment]
Should be fixed as of the latest deploy, thanks for the report!
