### ISSUE TITLE
scan barcode/qr code camera view stretched on Android

### ISSUE THREAD

**Issue by madrenderman** [FlutterFlow/flutterflow-issues#4687]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a problem with scan barcode/QR code action. I have set a button in my app to scan qr codes. It seems to work fine but when I test it on android (with apk export) and press the qr code scan, the camera view looks distorted in height, the image that the camera captures is stretched and consequently qrcode is not recognised because its shape is not seen correctly. I'm attaching some images to explain better.
![scan barcode problem](https://github.com/user-attachments/assets/b8d70a47-254f-4f2c-ab09-3ee444423d11)

### Expected Behavior

The camera view shouldn't be stretched
![scan barcode problem](https://github.com/user-attachments/assets/895e5b70-31ed-4a29-8a05-2ec4ce187d38)

### Steps to Reproduce

1. create a button
2. on the new button add an action
3. search for "Scan barcode/QR code" action and add it
4. test the app on an Android device (apk download)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oh8jbuJVOxN9c+KXqdcAxnSQ6NUx/bIIJkspOGDsdF4iuPOxzac+kUBdWTtDnS3xLKEWLkns0wveLhvL9JvYqaCScG4M6zKliewriJUC/aoTXBbqJdWtSTPpgGmK435izqiNTNspqdCEgw2GMA+6Qfz7bQJv7Zwh9f6PHaOI=

### Visual documentation

![lui](https://github.com/user-attachments/assets/713d1a98-a63d-4573-96c9-5b3d62f2da33)

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: Web
- Browser name and version: Chrome 130.0.6723.70
- Operating system and version affected: Windows 11
```

**Comment by rzambroni** [comment]
Hello @madrenderman,

Thank you for bringing this to our attention. I've noticed similar image distortion on Android with the QR scanner. However, it still seems capable of accurately reading a wide range of QR codes. This distortion seems to stem from the underlying package FlutterFlow uses for the scanner, `flutter_barcode_scanner`.

If you have specific cases where a QR code successfully scans on iOS but fails on Android, that could indicate a potential bug in the package or possibly an issue with the QR code generation. Any additional details or examples would be helpful for further investigation!

Thank you!

**Comment by madrenderman** [comment]
Hello @rzambroni , actually it looks like you're right. I had the chance to run some tests, and even though the camera view appears stretched, the QR code scan works. So it's not a big issue, just an "aesthetic" problem.
Thank you :)

**Comment by rzambroni** [comment]
great to hear! thanks!
