### ISSUE TITLE
Generate APK action is loading forever

### ISSUE THREAD

**Issue by mravani2** [FlutterFlow/flutterflow-issues#469]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The APK generation should take 2-4 minutes to be completed.

## Current behavior (required)

Since yesterday I noticed that the APK generation took much more time than expected, sometimes 15 - 20 minutes. Today I'm trying to generate it, but until now, it just keeps loading without any error message, even in the browser console.

## To Reproduce (required)

1. Open the project
2. Click Download APK

### Bug Report Code (required, generate from Widget Tree)

`IT4kzOfluYtPj7xY17X5bcFKjjo4KWYiTLJItutuZxIYfuLnE6QMds+lUEltYuqHSm5AfFel+WQJwfzXi/HpV/I7Awmsbpx5+rV5H1yjEA8=`

## Context (required)

I'm trying to download the APK

## Screenshots / recordings

<img width="245" alt="image" src="https://user-images.githubusercontent.com/122111577/218164562-262b4660-d926-427e-b950-45c8d1e98bbc.png">

## Your environment

* Version of FlutterFlow used: 
<img width="141" alt="image" src="https://user-images.githubusercontent.com/122111577/218164772-02e34b00-3924-4373-8736-70d9c6fb0a16.png">
* Platform (e.g. Web, MacOS Desktop): 
Web
* Browser name and version: 
Chrome 110.0.5481.77
* Operating system and version (desktop or mobile):
Windows 11

**Comment by hariprasadms** [comment]
Hi @mravani2 - Thanks for posting this issue. Yes, I agree there is bit delay comparatively in apk's download. However, apk download is working. We should be able to rectify this shortly.

**Comment by hariprasadms** [comment]
Hi, It is fixed in latest FF updates. So closing the issue.
