### ISSUE TITLE
Issue with Local Run After Recent Update

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#4693]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the latest update, the local run is not functioning. It gets stuck on "initializing" for hours without progressing.

### Expected Behavior

The local instance should initialize within a reasonable timeframe.

### Steps to Reproduce

1. Update to the latest version.
2. Attempt to start the local run.
3. Observe it getting stuck on "initializing."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gobQF+c+MKfpQhQAkQzM8bYJMl9caUQAaB5jmP4lzYer+VFhbZ7zkTwk3e0yKmmcy/s7rj9rlGscqGxCuQoNozc1iYQzzTlmhM76mPbjhW0ckN/hRGB2k156W3RVvJthuWE4nw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="448" alt="Screenshot 2024-10-25 at 8 17 39 AM" src="https://github.com/user-attachments/assets/8969fab3-5c4c-4bdc-ab49-0286993d7e74">

### Environment

```markdown
- FlutterFlow version:  3.24.2
- Platform:MacOS 
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Could you please let me know which version of macOS you have installed? Additionally, have you tried reinstalling your local setup to see if it resolves the issue?

**Comment by ghost** [comment]
I have macOS Version 15.0.1 (24A348) installed. I’ve also reinstalled it multiple times to try and resolve the issue, but it hasn’t helped.

**Comment by Alezanello** [comment]
I'm sorry I meant the MacOS version of FlutterFlow App

**Comment by ghost** [comment]
FlutterFlow v5.0.9 released October 25, 2024
Flutter version is 3.24.2

**Comment by ghost** [comment]
I replied within seconds, yet my report has been marked as 'waiting for user response' for two days.

**Comment by rzambroni** [comment]
Hello @hulum-io,

Thank you for your patience with this issue. We haven’t been able to replicate it on our end, so it seems specific to your local environment.

Here’s what I recommend:

1. Try deleting your local cache files and reinstalling FlutterFlow to see if that helps.
2. The two folders to delete are:
   * `/Users/<user_name>/Library/Caches/io.flutterflow.prod.mac`
   * `/Users/<user_name>/Library/Application Support/io.flutterflow.prod.mac`

If this doesn’t resolve the issue, I’d suggest reaching out to our support team directly—they’ll be the best resource for resolving local environment-specific problems like this. You can do that either by email (support@flutterflow.io or using the chat inside the app)

Thank you.

**Comment by ghost** [comment]
> Hello @hulum-io,
> 
> Thank you for your patience with this issue. We haven’t been able to replicate it on our end, so it seems specific to your local environment.
> 
> Here’s what I recommend:
> 
> 1. Try deleting your local cache files and reinstalling FlutterFlow to see if that helps.
> 2. The two folders to delete are:
>    
>    * `/Users/<user_name>/Library/Caches/io.flutterflow.prod.mac`
>    * `/Users/<user_name>/Library/Application Support/io.flutterflow.prod.mac`
> 
> If this doesn’t resolve the issue, I’d suggest reaching out to our support team directly—they’ll be the best resource for resolving local environment-specific problems like this. You can do that either by email ([support@flutterflow.io](mailto:support@flutterflow.io) or using the chat inside the app)
> 

Yes! That resolved the issue. Thank you!
