### ISSUE TITLE
API call error (google distance matrix)

### ISSUE THREAD

**Issue by lckwoventone** [FlutterFlow/flutterflow-issues#4696]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I made a query using a get to google distance matrix to calculate distance.
In the debug panel I see that there is a 200 status of the response, with a response body like this:

{
   "destination_addresses" : 
   [
      "Mt Washington, 110 Judge John Aiso St, Los Angeles, CA 90012, Stati Uniti"
   ],
   "origin_addresses" : 
   [
      "W 34 St & 5 Av, New York, NY 10001, Stati Uniti"
   ],
   "rows" : 
   [
      {
         "elements" : 
         [
            {
               "distance" : 
               {
                  "text" : "4.497 km",
                  "value" : 4496713
               },
               "duration" : 
               {
                  "text" : "1 giorno 17 ore",
                  "value" : 146960
               },
               "status" : "OK"
            }
         ]
      }
   ],
   "status" : "OK"
}

however, in the textfield where I want to show the $.rows[:].elements[:].distance.text --> "4.497 km"
I always have the "default" value returned...

### Expected Behavior

the right string selected from the JSON Path should be returnef

### Steps to Reproduce

1 - GO in My Trip
2 - create a new trip
3 - create 2 stages/stops
4 - in each stop set the location (by searching with google maps picker and then clicking on the lens icon to set the location)
5 - save
6 - in the second stage, below the map, the string of the distance should appear
7 - If ths string is always the same (e.g. "0 km NA") then the issue is reproduced (the expected value should be the real distance)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi87huM9Pm8sC7qrPbcBFtDgXGDt9a5IZmtVhRis9GYjyO5YUaeOlQ1tDXs/hTFFLKEWJ8V0G087lktnMFfFcExSrfJRnz8xiaz3/Xlm/aoSkBqjte3FtFppNCX6D0cOruyRAJtJ1Wi0m2zimBtyWQnXYNpP7Zwh9f6PHaOI=

### Visual documentation

the involved page is "chain_block"

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Web
- Browser name and version: Chrome 130.0.6723.70
- Operating system and version affected: Windows
```

### Additional Information

thank you

**Comment by Alezanello** [comment]
Hello!

I noticed that your text variable is currently set to the API response "Get Response Header." To retrieve the KM value correctly, it should be set to one of your predefined JSON paths instead.

Let me know if you need further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/81dbab6d-3192-424e-a5c8-c5e2dcc76fd3/11651abb-3d9e-46ca-a57d-d29b363d2b89?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MWRiYWI2ZC0zMTkyLTQyNGUtYTVjOC1jNWUyZGNjNzZmZDMvMTE2NTFhYmItM2Q5ZS00NmNhLWE1N2QtZDI5YjM2M2QyYjg5IiwiaWF0IjoxNzMwMDgzNjc1LCJleHAiOjMzMzAwNjQzNjc1fQ.Kuk4zLIX9_ZEWH3cmxBXRjdWMXM7tOGbhyCoBFAjHnI " alt="image.png" width="509" height="461" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/652271cf-b849-44c6-9f25-bb567ee0eb55/7c255d5c-17cb-4fb7-963d-959366f855e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NTIyNzFjZi1iODQ5LTQ0YzYtOWYyNS1iYjU2N2VlMGViNTUvN2MyNTVkNWMtMTdjYi00ZmI3LTk2M2QtOTU5MzY2Zjg1NWU5IiwiaWF0IjoxNzMwMDgzNjc1LCJleHAiOjMzMzAwNjQzNjc1fQ.Hi5IjLY8VAmaYhIjXQm32DqqnIoeB0wLZWmwEWgIUYo " alt="image.png" width="564" height="497" />

**Comment by lckwoventone** [comment]
Hi, it was probably a trial i made, but even with predefined path is the
same

[image: image.png]
[image: image.png]
[image: image.png]


In test mode I have the right response in the debug panel

[image: image.png]

In the API section if I test I have the correct path and result

[image: image.png]

However it is always displayed the default value once the app runs live


Thank you

Luca

Il giorno lun 28 ott 2024 alle ore 03:48 Alezanello <
***@***.***> ha scritto:

**Comment by Alezanello** [comment]
Hello!

I’m sorry, but I’m unable to view the images. If you sent them by email, they might be link-encoded. Could you try sending them again or providing a direct link?

Thank you!

**Comment by lckwoventone** [comment]
here a link with a wetransfer of the images

https://we.tl/t-CjbDl1rREm

I also attach them here as files

Thank you

Luca

Il giorno ven 1 nov 2024 alle ore 20:50 Alezanello ***@***.***>
ha scritto:

**Comment by lckwoventone** [comment]
Hello,
were you a le to see the linked images?

Thank you

Luca

Il mar 5 nov 2024, 22:20 Luca Marchetti ***@***.***> ha
scritto:

**Comment by lckwoventone** [comment]
Hi, do you have news?

Thanks

Luca

Il giorno lun 11 nov 2024 alle ore 09:04 Luca Marchetti <
***@***.***> ha scritto:

**Comment by Alezanello** [comment]
Hello again,

I’m still unable to replicate the issue you’re experiencing. Can you confirm if the default value showing when the app goes live is on the web?

If so, it could be related to a CORS issue. To resolve this, you may need to add a proxy to your API calls to ensure they work without any problems. Let me know if you’d like further guidance on setting this up!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
