### ISSUE TITLE
Migration to Null Safety is deleting custom codes.

### ISSUE THREAD

**Issue by syg-eliseu** [FlutterFlow/flutterflow-issues#47]
![Captura de Tela 2022-10-20 às 02 10 52](https://user-images.githubusercontent.com/88388127/196861775-41fee62d-20c8-40f1-98dd-01802994e7fc.png)

I've tried several times using the migration button but I always see this problem, my code always shows as deleted.

**Comment by bulgariamitko** [comment]
This is hard to reproduce, but for the most part the migration have to be already happened for the most users so I do not believe this should be fix. I believe FF team should remove or leave the option as it is as when you create a new project right now it is null safety by default. 

And to answer your special problem i guess you want to decode the URL?
The right code for me will be

texteUrl = texteUrl ?? ''; // null safety
textUrl = Uri.encodeFull(textUrl);
