### ISSUE TITLE
Lists aren´t handling data correctly after update

### ISSUE THREAD

**Issue by zeymermontes** [FlutterFlow/flutterflow-issues#470]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When you have a List, you should be able to add, remove, or set values of the list.

## Current behavior (required)
The issue is that right now it doesn´t matter the type of List it expects only Integers.

![image (3)](https://user-images.githubusercontent.com/66459565/218198137-4f62b554-c8eb-4808-a016-27e5c70a556c.png)

## To Reproduce (required)
1. Create an App state variable or a Page State Variable  of type List<String> 
2. Add a button to the page
3. Add an action to add to list or remove from list
4. FF won´t let you add anything other than an Int

### Bug Report Code (required, generate from Widget Tree)
IT4kzsnf7ZF1pbxd+KrxbfpopDg4Jm45TLJEoetxc0gbfe/4EJYfO87sQBRtXuazaH9DfVSj8T0ewNKJv+OSMO47Gy+ZftlF1KoBclyjEA8=

## Context (required)
I can´t continue with my codding. I use that function in basicaly the whole app.

## Your environment

* Version of FlutterFlow used:  V3.0
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version:  Chrome  110.0.5481.77
* Operating system and version (desktop or mobile): Windows desktop

**Comment by magusfabius** [comment]
Same problem here. I'm trying to add a DocumentRef into a local state list but the type is int. I've tried with different collections and different list type and the problem persists

**Comment by hariprasadms** [comment]
Hi @magusfabius - This issue should be fixed now. Please check and confirm.

**Comment by magusfabius** [comment]
Thank you @hariprasadms everything is working now
