### ISSUE TITLE
[ListView Reverse issue] there is no "true" (Desktop apps)

### ISSUE THREAD

**Issue by workpodsjun** [FlutterFlow/flutterflow-issues#471]
Hi Team,

I appreciate if you would add the code below to work reverse in ListView.
In the desktop apps, "Reverse" doesn't work in ListView.

[Add below]
reverse: true,

[Example link below]
https://community.flutterflow.io/c/discuss-and-get-help/listview-scroll-on-button-click

[As same, I posted FF community]
https://community.flutterflow.io/c/bugs/listview-reverse-there-is-no-true-desktop-site

**Comment by hariprasadms** [comment]
Hi @workpodsjun - Thanks for posting the issue. We need issues details to be updated as per advised issue template formate. Once issue details are updated, we can consider this issue for triage. Thanks

**Comment by hariprasadms** [comment]
Hello, As there is no follow on this issue and no enough details provided as per standard template, we are closing the issue. Please add the details, we can re-open and investigate the issue if this persists again. Thanks
