### ISSUE TITLE
Using YouTubePlayer widget in Bottomsheet throws a bug

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#472]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
YouTubePlayer widget should work in bottomsheet (so users can have a preview of the link they uploaded)

## Current behavior (required)
Using YouTubePlayer widget in Bottomsheet throws a bug

## To Reproduce (required)

1) Create new project
2) on the homepage Add a YouTubePlayer widget
3) convert it into a component
4) add a button on the homepage
5) add an action to open bottomsheet
6) run app in "Test" mode
7) you'll see that the homepage shows the YT widget properly but when you click the button to open the bottomsheet with the SAME YT widget just as a component, it crashes

### Bug Report Code (required, generate from Widget Tree)

IT9Xz/Hqx89Nobhe+KXUb8dR/WARJkAjRY0/kdZxTRQaJuvuPLd3Zs+lVBJuOLSoT3xYJWeN+WUd/vzHk/D2MeUDPQurc746wpBuczrgUj6uWraEPqWaY2h9FtJjfmWXw7SC2yJ7OvNvSWQO2U77Ady+QnTvGYztPVcgRK/LZO4=

## Context (required)

see above

## Screenshots / recordings

see the sample project i created for yall

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Hi @Zack1010OP - Thanks for posting the issue. I can re produce the issue. Adding below screenshot for development team debugging.

![image](https://user-images.githubusercontent.com/17435678/218325835-b377ba91-6b63-42be-8362-a6431f6f520e.png)

**Comment by agreaves** [comment]
Hi @Zack1010OP, thanks for catching this! Confirmed this is a bug and identified a fix so this should be fixed upon our next deploy!
