### ISSUE TITLE
Run & Test mode

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#473]
I've a project that working in Run mode but not in Test mode
I see this error:
<img width="462" alt="FF-testMode-bug" src="https://user-images.githubusercontent.com/1261851/218270049-389a40fb-8b00-43ee-9d1f-52b270260691.png">

**Comment by organicnz** [comment]
Hi @blondie63. Thank you John for adding this issue 🙂

It looks like you assigned an integer type to a boolean expression. Could you accidentally change it? :)

**Comment by blondie63** [comment]
Mr. Barry have access to my project..

**Comment by aemelyanovff** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. I'm closing the issue for now, but please feel free to when the necessary information is provided.
