### ISSUE TITLE
FlutterFlow Desktop app crashes unexpectedly while merge is in progress

### ISSUE THREAD

**Issue by Maazkhalid47** [FlutterFlow/flutterflow-issues#4735]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been experiencing the same bug for months now, whenever i try to merge a new branch or resolve conflicts the desktop app shuts down unexpectedly, then I have to restart the app, and this happens 2-3 times atleast, then I mostly head to browser app to merge it
This is the second time I am opening this issue as the previous one was closed due to no response from me, but I have provided the video now take a look at the bug.

### Expected Behavior

I should be able to merge the branch and resolve conflicts without the app shutting down

### Steps to Reproduce

1.Create a project
2.Create a page and add a container
3.Create 2 branches
4.Edit the same container with both the branches to create a conflict.
5.Try to merge

the desktop app should crash

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT43zPLqw4h1xdtH0KXqafdKngERQlwKao0amsBraCosfZT2BLMcec/RVERVOd+/SnNPe1majWoW0/zTjuLuGMIFNTOdRqU4ysxqcwzyUTiibpjSFJWgPXcmHZhhI32B0LaZ2x5BJtt2SCEa62emBOmQaArbHuPMPm48D6/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/8395ae82-37be-45c7-b505-e5cc0de65c95

### Environment

```markdown
- FlutterFlow version:  v5.0.5
- Platform:Desktop windows
- Browser name and version:Chrome 129.0.6668.100
- Operating system and version affected: Windows 11
```

### Additional Information

I have to repeat the same process atleast 3-4 times in order to merge a single branch and seldom reach completion, mostly I have to head to the browser app to merge it.

**Comment by Alezanello** [comment]
Hello!

I can confirm this issue. I'll escalate it to our engineering team for review and a possible fix. Thank you so much for bringing this to our attention!

**Comment by Alezanello** [comment]
Hello!

Sorry for the delayed response. Did the latest Flutterflow updates resolve the issue for you?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
