### ISSUE TITLE
FlutterFlow generates wrong code when `Document Exists` option is used.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#474]
## Expected behavior (required)

- `Document Exists` option in the document of Backend query should work as expected.

## Current behavior (required)

- The FlutterFlow generates some code like below that the `return Container();` makes the `Document Exists` option un-rechable.

```dart
if (snapshot.data!.isEmpty) {
  return Container();
}
final titleGetPostPostsRecord =
    titleGetPostPostsRecordList.isNotEmpty
        ? titleGetPostPostsRecordList.first
        : null;
```

## To Reproduce (required)

1. Do Firestore backend query with Collection Query and Single Document Option. And the query should result without getting any document.
2. Display a text on the Conditional Value with the condition of `Document Exists`.
3. Since the document does not exists, the second value should be displayed on the text. But it isn't.

Because if the document does not exists, `if (snapshot.data!.isEmpty)` becomes true and the rest codes are un-rechable.

### Bug Report Code (required, generate from Widget Tree)

ITFTiMr14otOsbQC+KXbK8FFoGE7CUMBX5Ir1utvGBc3GLL2BJkMO+DuaXdaO8PgYFVPfVeLhngJw+zzhobpDMc7HAWBf6E2k/UwKlCvHAM=

## Context (required)

I want to display a text of "post not exists" when the document does not exist. But I can't.

The `Document Exists` does not work. Not only for the Collection Query, but also Document Query also.

## Screenshots / recordings
<img width="728" alt="image" src="https://user-images.githubusercontent.com/5080329/218271887-c5dfdd52-6794-47c5-8191-0191f0781bfe.png">

<img width="980" alt="image" src="https://user-images.githubusercontent.com/5080329/218271884-4cf41255-fde0-4ccb-838e-35ef8cf730bd.png">

## Your environment

Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by agreaves** [comment]
Hi @thruthesky! Thanks for the bug report. In this case, this is because the "Hide Widget if No Match" option is selected for this widget, which makes it behave exactly as you described. If you want to handle this logic manually, make sure to uncheck this in the query.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/7757399/218334324-7650e8c8-dd16-4791-b2a9-a4f925dddb6f.png">

Hope this makes sense!
