### ISSUE TITLE
`Update Page On Change` is not working from a Component.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#475]
## Expected behavior (required)

- Update the Page on Change when `Update Page On Change` option is set.

## Current behavior (required)

- It does not update the page on change when it should.

## To Reproduce (required)

1. Create a component.
2. Add a TextField.
3. Enable `Update Page On Change` and run.
4. The page is not being updated on change.

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

I want to update the containing page of the component as it is stated.
If it's going to update the containing page, the label should be `Update Component On Change`.

## Screenshots / recordings

Shouldn't it be `Update Component On Change`?

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/5080329/218272050-c40f68e2-1750-49f1-9e21-c03cb5ee30a7.png">

## Your environment
Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by hariprasadms** [comment]
HI @thruthesky - Thanks for posting this issue. - I have verified this issue. I think it is working as expected. 

I have create an example. Refer below videos.

1. When text field is defined in a component ( Eventually component is a widget on its own ) and its on change values can affect widgets instantly which are defined inside the component. 

2. Text filed value can access outside component using widget state but on change behaviour will have no affect to widgets  which are at page level.

https://user-images.githubusercontent.com/17435678/218322434-5357568a-e778-4418-9b2f-5419c2fca9b6.mp4

3. Take help of app state alone or page state and app state combinations to update the page leave widgets states when component leave text filed values changes ( use change action ). I have updated the same example by using app state. You can see page leavel text widget can update its value when component text field value is changes. See the result of it in below video.

https://user-images.githubusercontent.com/17435678/218323043-ac90fcc9-78f0-483b-bc0e-f528e07f66fb.mp4

Regarding 'Update page on change' checkbox label, I think we should change this to 'Update component or page' based on text field where it is used. I can check this with development team. Hi @agreaves, please advise.

**Comment by agreaves** [comment]
Hi @thruthesky, good catch! This is indeed the intended behavior, however you're correct that this should say "Update Component On Change" when the TextField is inside of a component. We'll make this fix!
