### ISSUE TITLE
WidgetBuilder stays in Widget Tree after removed

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#4753]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

WidgetBuilder parameter stays in the Widget Tree after it was removed. And it produce error while running(building)

### Expected Behavior

- Widget builder parameter should not be removed if it's in use
- Or it should produce a number in the error indicator badge

### Steps to Reproduce

1. Add a widget builder as a parameter in a Component
2. Add the widget builder in the Widget tree.
3. Delete the widget builder from the Component parameter list
4. You will see the widget builder still stays in the widget tree without any error indicator.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/qy5NPn7xD1aryYPpahmU5JVw7U+cFidV7aCsofePrOpkAf8/7UFtUOOmlSmxUP06jmnEX/Mr9v+z1LPYFHxKAY6pDwbl6SgzwRTugb6aaPa63b2hCQOBQGnKd0rS43QlSCMdiSFlm72b7J+mWVgjAQqayIWo3HuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Add a builder and delete it.
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/1e1e594e-a5e3-4b07-b253-5b7471e477b3">

And you see the deleted builder stays in Widget Tree.
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/bbbd9040-d706-4469-bebf-304428fca889">

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: MacOS
- Browser name and version: Chrome Version 130.0.6723.70 (Official Build) (arm64)
- Operating system and version affected: Sequoia 15.0.1 (24A348)
```

### Additional Information

I have a custom widget of ListView and I want to give a preview on it.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention!

I’m not entirely sure if this behavior is intended, but I was able to replicate it and have recorded a video to share with the engineering team for further review. In the meantime, you can try removing the widget by right-clicking on it in the Widget Tree and selecting “Delete.”

Thanks again for your help in identifying this!

**Comment by rzambroni** [comment]
Thank you for reaching out about this! We’ve noticed there’s already an existing ticket addressing this issue, so I’ll go ahead and close this as a duplicate. The solution is currently under review and should be available soon.

Thanks!
