### ISSUE TITLE
DataTable index

### ISSUE THREAD

**Issue by fnavarro-ff** [FlutterFlow/flutterflow-issues#4755]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i have 9 items in a table, the index shows 10, then i change to show 5, i can't go to show 10 again

### Expected Behavior

show 10 again

### Steps to Reproduce

1. table with 9 items
2. change to show 5
3. change to show 10 again

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ej8ncx85Pm8tF7c/tbfpVniERKUR/a4Irl+thbAwaJbLyB7QMZOj+cnNVXeGiTFZIeVmZmk4JzMrXivPhC8EoBxuBfJRgwalUTQHKUWqyRZSKDoeKOHBSL/FYChG056WF2hEkJrRfW1ICxWO6I9+sZ3brJoO2DG0NNP6kVYf/jHS8AQ/rJRZr2RQIIRKtCK81ZVDq+f6QspZl1eTjzw==

### Visual documentation

https://github.com/user-attachments/assets/064564e0-194a-4db0-b8cb-50e71162c025

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform: web
- Browser name and version: Chrome 130.0.6723.70
- Operating system and version affected: Windows 10 home / mac
```

### Additional Information

is not a priority

**Comment by Alezanello** [comment]
Hello!

You’re absolutely right! Thank you for noticing this and bringing it to our attention. I’ve confirmed the issue and will be passing it along to the engineering team for a fix.

Thanks again for your help!

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. Here’s what’s happening: if you have, for example, 9 items, the option to view 10 items initially appears when the DataTable first loads. However, once you switch to viewing 5 items, the option to go back to 10 is no longer available because there are fewer than 10 items in the DataTable.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
