### ISSUE TITLE
Dynamic Link Does Not Open Specific Page After App Install on iOS

### ISSUE THREAD

**Issue by ahnsunnyyoung** [FlutterFlow/flutterflow-issues#4756]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app opens to the default start page, not the specific page from the Dynamic Link. (Android works fine, **ONLY IOS**)

### Expected Behavior

The app should open directly to the specified page (in this case, a profile page of specific user) after installation.

### Steps to Reproduce

1. Ensure the app is not installed on an iOS device.
2. Click on a[ Dynamic Link](https://iraaveshare.page.link/?link=https%3A%2F%2Firaaveshare.page.link%2FprofileDetailPage%3FuserRef%3DRNXuBtHWOzVUmx8P5ZmNvuGDkyv1&apn=com.iraave.app&isi=6502949908&ibi=com.iraave.app&efr=1) that should open a specific profile page in the app. 
3. Install the app via the redirected App Store link.
4. Open the app after installation.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj+fqw5d1rtdc+KqJK8BB/GAQJjt9bLsascpCbw4bIYj2P4lzY876P1VWXdelSnx2J2ecp14D+d7Nv+DxKPJeBxKdG4R6+ZFXVQ6VZFOXMZeTF7WZOWslOJhYBWaA0auNuREkAOpsS0I+3F2MAuiUVjTvJr7BDUQ8Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/0f406314-d93c-4975-81f5-6dc26238f010)
This should appear from first open.
But default is opened.
![image](https://github.com/user-attachments/assets/176084e2-a2a5-4e3d-8f36-671149b0b406)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform:ios
- Browser name and version:Chrome 126.0.6478.127
- Operating system and version affected: Windows 11 Home
```

**Comment by jagdishjadeja** [comment]
+1. 
I am also facing similar issue.

**Comment by Alezanello** [comment]
Hello!

This issue isn't specific to FlutterFlow but rather how Firebase Dynamic Links behave on iOS, which is a known issue. Unfortunately, Dynamic Links don't always work correctly on iOS. We have an enhancement request in place to allow modifications to the `info.plist` file to address this. You can follow the discussion and updates on this issue here: [GitHub Issue #3195](https://github.com/FlutterFlow/flutterflow-issues/issues/3195).

**Comment by ahnsunnyyoung** [comment]
I guess it's just about modifying info.plist. I don't really understand that during 1 year, will flutterflow really not going to add any solution on this issue.

**Comment by ahnsunnyyoung** [comment]
Also, tried to add info.plist and deploy manually,

               
               <key>FirebaseDynamicLinksCustomDomains</key>
               <array>
                 <string>https://iraaveshare.page.link</string>
                 <string>https://iraaveshare.page.link/profileDetailPage</string>
               </array>
**But still not working.**
