### ISSUE TITLE
Tabbar Unselected Label Text Color bud

### ISSUE THREAD

**Issue by cnrsbtogll** [FlutterFlow/flutterflow-issues#4761]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I choose black as the label color for the unselected tab bar, but when I transfer it to the code, an incorrect value appears.

### Expected Behavior

Unselected tab text color should be fixed.

### Steps to Reproduce

create a tabbar. give a tab text color for the unselected tab. eg: black.
start the test. the text color of the unselected tab comes from the text color of the selected tab.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzcmA38lOxLhc+Kn6a8JoiWMvI0MfX5I7i95EZwEhNZDkOrQuPczCbhdLYte6eXx6C039kTsDpfDuk+zhJvEqZCiWfaJdz75XQQvMUkOiVaaMOrq8T3FCQdFPIX6g0cOrnxQkOrFfLXwc21ylfvCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1657" alt="unselectedlabelcolor" src="https://github.com/user-attachments/assets/dea7f196-5134-4ee0-ab90-354d896b8dfe">

### Environment

```markdown
- FlutterFlow version: 3.2.24
- Platform: android-ios
- Browser name and version: chrome
- Operating system and version affected: ios - android
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue on my end. The code appears to be generated correctly, with the Tertiary color set as "Selected" and the Primary color as "Unselected." Both the code output and the visual result are as expected.

Please let me know if there are any additional details or specific steps I might be missing to help reproduce this issue.<br><br>Here is the public project, you can clone it and test it: [https://app.flutterflow.io/project/qa-2910-lxgiat](https://app.flutterflow.io/project/qa-2910-lxgiat)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b38e7ef2-4120-4c0d-88de-491b71a548dc/43148da8-f469-4c74-a74c-685d1cb91fb4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMzhlN2VmMi00MTIwLTRjMGQtODhkZS00OTFiNzFhNTQ4ZGMvNDMxNDhkYTgtZjQ2OS00Yzc0LWE3NGMtNjg1ZDFjYjkxZmI0IiwiaWF0IjoxNzMwMjI4Nzc5LCJleHAiOjMzMzAwNzg4Nzc5fQ.X--Bzdygz8yojGJN12i7t5aO5ERYm7xfmg3B1UWirNQ " alt="image.png" width="1116" height="624" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6ec42ee5-bcb1-4a0f-abcd-7b7cf13d4e37/f92e3d6b-c1ee-4fc2-be10-349886dc0d59?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZWM0MmVlNS1iY2IxLTRhMGYtYWJjZC03YjdjZjEzZDRlMzcvZjkyZTNkNmItYzFlZS00ZmMyLWJlMTAtMzQ5ODg2ZGMwZDU5IiwiaWF0IjoxNzMwMjI4Nzc5LCJleHAiOjMzMzAwNzg4Nzc5fQ.mxUZw4Fhp8ioOJq0jLzKEGj7We-1f1at7IViECUaYQc " alt="image.png" width="1216" height="681" />

**Comment by cnrsbtogll** [comment]
report code: ITFTzcmA38lOxLhc+Kn6a8JoiWMvI0MfX5I7i95EZwEhNZDkOrQuPczCbhdLYtTidGxmME6bgj8EpK35iYbDVsA6Cw6ZRphH+IRXQQvMUkOiVaaMOrq8T3FCQdFPIX6g0cOrnxQkOrFfLXwc21ylfvCNG3qCf9qOYwx5e6fDbOY=

tabbar style: should be "Button".
FlutterFlow v5.0.8+ released October 25, 2024 Flutter version is 3.24.2

**Comment by flavioacm** [comment]
I´m having the same problem. Using Toggle Button style.

**Comment by Alezanello** [comment]
@cnrsbtogll Even with the Button Style is everything working as expected 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a7eed9f9-fc0b-4b8a-b845-8a59aa74cfc5/e209dfdf-3cb7-4ffa-8c4b-6122f9ee8360?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hN2VlZDlmOS1mYzBiLTRiOGEtYjg0NS04YTU5YWE3NGNmYzUvZTIwOWRmZGYtM2NiNy00ZmZhLThjNGItNjEyMmY5ZWU4MzYwIiwiaWF0IjoxNzMwMjk2NzU0LCJleHAiOjMzMzAwODU2NzU0fQ.L4kyYFi4Knn7zVM6rk2C5S3gDmg7v-HrhxYYtIdw3nQ " alt="buttonStyle.gif" width="1875" height="948" />

**Comment by Alezanello** [comment]
Even with the Toggle Button Style @flavioacm 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fbcdfa60-db3e-4708-bebc-ad408b5faabd/9ee74e1a-3597-4cc2-8d4e-f13109351e3f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYmNkZmE2MC1kYjNlLTQ3MDgtYmViYy1hZDQwOGI1ZmFhYmQvOWVlNzRlMWEtMzU5Ny00Y2MyLThkNGUtZjEzMTA5MzUxZTNmIiwiaWF0IjoxNzMwMjk2ODQ2LCJleHAiOjMzMzAwODU2ODQ2fQ.5q8GuFdQ8WOVgh_UHZL7gW3DcWgAfZn4mlKTHSyco5c " alt="TogglebuttonStyle.gif" width="1875" height="948" />

Here is the public project, you can clone it and test it:<br>[https://app.flutterflow.io/project/qa-2910-lxgiat](https://app.flutterflow.io/project/qa-2910-lxgiat)

**Comment by cnrsbtogll** [comment]
The custom selected label style switch was closed. It was fixed when I activated the switch. Thanks for your help.
<img width="589" alt="custom unselected label" src="https://github.com/user-attachments/assets/63b6fffa-82ef-4e02-96b3-5b63177b9046">

**Comment by flavioacm** [comment]
This behavior is different from before.

Now you need to mark the “custom selection label style”, and then the "unselected color" works.

This difference is generating issues in the projects made with old versions.
