### ISSUE TITLE
Update App State (Rebuild All Pages)

### ISSUE THREAD

**Issue by lblinformatica** [FlutterFlow/flutterflow-issues#4766]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,
I have a custom widget (Google Maps) that receives a JSON file with latlng coordinates to draw polygons.
The list of coordinates is updated to an App State.
{"polygons": [{"id": "354780905000020P", "points": [[-23.6646109989999,-46.525249],[-23.66396438899988,-46.52592296499989],[-23.6646361903201,-46.52655044413108],[-23.665249999,-46.52715799999999],[-23.66551036920731,-46.5268110644817],[-23.6661636954268,-46.5274132608231],[-23.6665471695122,-46.52691048368899],[-23.66682554329271,-46.52658382057918],[-23.6661921009146,-46.52597026204259],[-23.66558564375001,-46.52532971829271],[-23.6648599989999,-46.52494899999991],[-23.6646109989999,-46.525249]]}]}

When adding Action to update App State and selecting the Rebuild All Pages option, the current page is not reloaded.

Can you help me solve this please?
![image](https://github.com/user-attachments/assets/bc5e85b1-8e1b-4f6b-a93c-a536b7978801)

### Expected Behavior

After select a item, the map must be refreshed:
![image](https://github.com/user-attachments/assets/ca651958-33c0-48c6-a7db-b321388bf64d)

### Steps to Reproduce

1. Create new page
2. Add custom widget MapWithPolygons
3. Add DropDown widget
4. Select item
5. Map should be refreshed

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OiMjfsI52rt9G+KXqdcAxnjw5JnIma5ZMju5uZxcgIrHNG7UIec/4VEptXbC+TVc3OGakinkewNKPhdzIN+46B0mcbIBi+M5uaQGVc3GXabqVEaiOSHFBINpKCkiYyKWF3CVTLtdaWWQGw2CECOuydDfdJLrNDVYRB/+kLpDJnXPuQ0SLb3kNh1JWeC/v

### Visual documentation

After select a item, the map must be refreshed:
![image](https://github.com/user-attachments/assets/ca651958-33c0-48c6-a7db-b321388bf64d)

### Environment

```markdown
- FlutterFlow version: v5
- Platform:Android
- Browser name and version:Chrome 130.0.6723.70 
- Operating system and version affected: Windows 11
```

### Additional Information

I need this functionality to improve the user experience

**Comment by Alezanello** [comment]
Hello!

To achieve your goal, I strongly recommend making the API call directly within the Custom Widget code. This way, you can handle the refresh there with the newly provided information.

**Comment by lblinformatica** [comment]
Hi Alezanello

Ok, i´ll do that

Thank you
