### ISSUE TITLE
Flutter material.dart Error - package:flutter/material.dart URI doesn't exists 

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#477]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I was trying to compile a custom Widget that worked perfectly a week ago. Now even if I delete it and create a new one I get the error that the material.dart package URI doesn't exist. Even when creating a completely new widget without any custom code, the error occurs. I haven't changed anything or added anything to the package imports.

The strange thing is that it only appears in one of my projects. The other one is perfectly fine and is running on the same FF version. 

1. Create a new Custom Widget
2. Check for Errors

### Bug Report Code (required, generate by right clicking inside Widget Tree and clickig "Get Bug Report Code")

N/A

## Context (required)

Trying to create a custom widget

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/120254395/218309774-3af3200f-efae-43b9-abef-862d3e817d4b.png)

## Your environment

* Version of FlutterFlow used: Flutterflow v3.0 released 11.02.23 - Flutter 3.3.4 
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 109.0.5414.119 (Offizieller Build) (x86_64)
* Operating system and version (desktop or mobile): macOS Ventura v13.1

**Comment by hariprasadms** [comment]
Hi @nicmohr25 - I just tested this and I can see it works fine for me with no error. Screenshot below.
Try refreshing the page ( Ctrl+R) and create again. Sometime It could be because of network issue as well. Please check and confirm.

![image](https://user-images.githubusercontent.com/17435678/218314081-dbf81ae1-0e31-4d5a-9f2d-3603a431071f.png)

**Comment by nicmohr25** [comment]
Hello, thanks for checking but i already tried reloading, clearing the cookies as well as using a different browser. As I said the error only occurs in one of my projects. Also, it's not specific to one widget. All custom Functions and Actions won't work. 
![Bildschirm­foto 2023-02-12 um 14 45 32](https://user-images.githubusercontent.com/120254395/218314778-a9f3b9cd-8aa4-49e5-9a23-0c80d14e36c7.png)

**Comment by hariprasadms** [comment]
Thanks for confirming. Please share bug report code. We should be able to fix it for you in sometime. Thanks 

In widget tree, right click on one of the widgets to get the bug report code. Thanks

![image](https://user-images.githubusercontent.com/17435678/218315178-79136da5-f34b-4e0f-8527-1b0e5c218be3.png)

**Comment by nicmohr25** [comment]
I added a custom widget to the widget tree and copied the Bug Report from there. But as I said it is affecting all Widgets, Actions, Functions

Bug Report Code: IT48lcmB34hNodcF+Kr2b8FajjgXH2E7aLszkOxxRUs8J5DaPOxzP/TBaldWUs+0S1FMfU2agnoKzN3emvDtKsFdGE2sRtlkzJZcbQnxRnOXVbqJPamKOS0ffaMKRSz+

**Comment by hariprasadms** [comment]
Thanks. We will update you once it is fixed. Thanks

**Comment by nicmohr25** [comment]
Oh, i see. Thanks for the detailed explanation. I could make it work after updating the dependencies. 
'Excluding from compilation' just saves a ton of time when building custom widgets/actions because compiling the code in ff takes a while. Especially when i'm just testing a few new lines compiling actions, widgets and functions are just pretty time-consuming. 
But now i now for the future!

Thanks again.

**Comment by aemelyanovff** [comment]
After the next release, the code editor will show a warning when it fails to run `flutter pub get`.
