### ISSUE TITLE
AutoComplete textfield error

### ISSUE THREAD

**Issue by Digitpixels** [FlutterFlow/flutterflow-issues#4777]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a package error

Error: Couldn't resolve the package 'substring_highlight' in 'package:substring_highlight/substring_highlight.dart'.
D/EGL_emulation( 9049): app_time_stats: avg=501.71ms min=498.66ms max=504.77ms count=2
lib/flutter_flow/flutter_flow_autocomplete_options_list.dart:3:8: Error: Not found: 'package:substring_highlight/substring_highlight.dart'
import 'package:substring_highlight/substring_highlight.dart';
       ^
lib/flutter_flow/flutter_flow_autocomplete_options_list.dart:68:28: Error: The method 'SubstringHighlight' isn't defined for the class 'AutocompleteOptionsList'.
 - 'AutocompleteOptionsList' is from 'package:trickin_sport/flutter_flow/flutter_flow_autocomplete_options_list.dart' ('lib/flutter_flow/flutter_flow_autocomplete_options_list.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SubstringHighlight'.
                    child: SubstringHighlight(

### Expected Behavior

I want to use the autocomplete option from the textfield

### Steps to Reproduce

1. ADD textfield
2.  actice autocomplete
3. Active 'SubString style same as textfield

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89gobxY17X1bcJFgikUHHI9TL03t9VxSUgrIrbyPJkUafSkXBJVOe2rSlZfKEWKmn4Gpv/HktntD+0pMgqafqJlyZdcTDnLUnm/aoSSPZDoP0dSAf1mfUC437WnnwlTPvJedXAC2V+LevCWcBTdHpv7Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/9c8cd4c5-8bcf-435b-85f7-a58e861ded6e)

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform: Desktop
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello!

When you added the new package, did you have the local run already open?

Adding a new package often requires a full restart rather than just a hot reload. This is especially true when adding a new widget that includes additional packages. You’ll need to restart the local run to ensure the `flutter pub get` command executes, downloading the necessary packages for the project.
