### ISSUE TITLE
Android App Crash on Open - Debug works

### ISSUE THREAD

**Issue by adnanmur** [FlutterFlow/flutterflow-issues#4780]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

iOS deployment works fine, no issues there. Android test mode - debug works, release does not open and the errors caught in crashlytics is this. 

Exception java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'L.n1' (declaration of 'L.n1' appears in /data/app/~~wDvgiQVxTU_93yqL-FW5ZQ==/com.mycompany.hulum-HkxmhC-TzDtfUKa9JFUA1Q==/base.apk) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.RestrictedComponentContainer.get (RestrictedComponentContainer.java) at com.google.firebase.appcheck.FirebaseAppCheckRegistrar.lambda$getComponents$0 (FirebaseAppCheckRegistrar.java) at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0 (ComponentMonitor.java:12) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java) at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java) at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:67) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:72) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java) at android.content.ContentProvider.attachInfo (ContentProvider.java:2451) at android.content.ContentProvider.attachInfo (ContentProvider.java:2421) at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:13) at android.app.ActivityThread.installProvider (ActivityThread.java:7508) at android.app.ActivityThread.installContentProviders (ActivityThread.java:7019) at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6790) at android.app.ActivityThread.-$$Nest$mhandleBindApplication at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2132) at android.os.Handler.dispatchMessage (Handler.java:106) at android.os.Looper.loopOnce (Looper.java:201) at android.os.Looper.loop (Looper.java:288) at android.app.ActivityThread.main (ActivityThread.java:7918) at java.lang.reflect.Method.invoke at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

### Expected Behavior

App should open on android as it opens on iOS

### Steps to Reproduce

1. Create apk
2. Install apk on phone and it does not start
3. Testing from playstore, same behaviour, i can upload AAB but once opened it crashes immediatelly.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Exception java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'L.n1' (declaration of 'L.n1' appears in /data/app/~~wDvgiQVxTU_93yqL-FW5ZQ==/com.mycompany.hulum-HkxmhC-TzDtfUKa9JFUA1Q==/base.apk) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.RestrictedComponentContainer.get (RestrictedComponentContainer.java) at com.google.firebase.appcheck.FirebaseAppCheckRegistrar.lambda$getComponents$0 (FirebaseAppCheckRegistrar.java) at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0 (ComponentMonitor.java:12) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java) at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java) at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:67) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:72) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java) at android.content.ContentProvider.attachInfo (ContentProvider.java:2451) at android.content.ContentProvider.attachInfo (ContentProvider.java:2421) at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:13) at android.app.ActivityThread.installProvider (ActivityThread.java:7508) at android.app.ActivityThread.installContentProviders (ActivityThread.java:7019) at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6790) at android.app.ActivityThread.-$$Nest$mhandleBindApplication at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2132) at android.os.Handler.dispatchMessage (Handler.java:106) at android.os.Looper.loopOnce (Looper.java:201) at android.os.Looper.loop (Looper.java:288) at android.app.ActivityThread.main (ActivityThread.java:7918) at java.lang.reflect.Method.invoke at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

### Visual documentation

No videos.

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Android
- Browser name and version:
- Operating system and version affected: Android
```

### Additional Information

Im trying to release the app on Playstore

**Comment by amicable-io** [comment]
https://community.flutterflow.io/discussions/post/apk-crash-after-3-24-2-flutter-update-6iWn5tXbN1gpYvA

**Comment by Alezanello** [comment]
Hello!

I’m sorry you’re experiencing this issue, but the good news is that a hotfix is already on the way! You can follow updates on the original post here: [GitHub Issue #4750](https://github.com/FlutterFlow/flutterflow-issues/issues/4750).

I’ll close this issue as a duplicate to keep all efforts focused on a single ticket.

**Comment by adnanmur** [comment]
great thanks everyone
