### ISSUE TITLE
Custom Authentication

### ISSUE THREAD

**Issue by ricardocosta43** [FlutterFlow/flutterflow-issues#4781]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Associate login with firebase, be able to disable user creation automatically and still have access to the Authenticated User Variables

Why do I need this?

I have two apps that share the same firebase project.
However, if a user created an account with their email in one app, they cannot create an account in the other app.

Disabling the automatic creation of the Users collection at login disables the Authenticated User variables

### Expected Behavior

Being able to create the Users collection at another time and still have the Authenticated User variables available

### Steps to Reproduce

1 - Create app
2 - Configure authentication with Firebase (it can just be email)
3 - Create the authentication flow
4 - Disable user collection creation
5 - Right below, create an action to create the user's collection
6 - Check on another screen that the Authenticated user variables are available

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiMjfsJJNrsNK1aqBbPpVuyQ4G1t6a7gFlMpOGDsdF4iuPOxzacykaRZpUvWnTAhbKEWKjmox0MLzhePLJ+0EOU2rf75z/6h+cQrLRly/aoSoDc+7dHcmGe1MGEii0JjQuCUkNsdoW0FhwV2AHt6vFwrvJu77Zwh9f6PHaOI=

### Visual documentation

![Captura de Tela 2024-10-30 às 03 59 32](https://github.com/user-attachments/assets/becce421-08f1-472a-95c4-d8bedd95f16f)
![Captura de Tela 2024-10-30 às 04 00 42](https://github.com/user-attachments/assets/ade2e8b3-285f-45b9-89b9-3d01a15be0cd)
![Captura de Tela 2024-10-30 às 04 01 46](https://github.com/user-attachments/assets/6f5e2f2d-7015-4e47-ab7a-82fd23a8cf07)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 25, 2024
Flutter version is 3.24.2
- Platform: MacOs Sonoma
- Browser name and version: 130.0.6723.71
- Operating system and version affected: MacOs Sonoma
```

**Comment by Alezanello** [comment]
Hello!

This is the expected behavior. When you disable the "Create User Document" option on login or account creation, it also disables the "Users Collection" setting in Firestore Settings.

I’ve created a 4-minute video explaining the situation and a workaround you can use!

[Screen-Recording (33).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/68e7ca07-7eca-4235-8c47-e7c7122ba8b8/d0213e9a-adcf-4daf-8f31-d83e7300ab93?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82OGU3Y2EwNy03ZWNhLTQyMzUtOGM0Ny1lN2M3MTIyYmE4YjgvZDAyMTNlOWEtYWRjZi00ZGFmLThmMzEtZDgzZTczMDBhYjkzIiwiaWF0IjoxNzMwMjk4MDgxLCJleHAiOjMzMzAwODU4MDgxfQ.eVGKiWEuLeJvmWnfR_XW93ACsb1dgDwzE3QVOYC4PjM)

**Comment by ricardocosta43** [comment]
@Alezanello Alezanello hello
Thank you very much for the explanation.
I understood completely and also understood your point.
You showed how I get around this by sending my docReference to appstate.
This would work great in an app I'm starting today

However, I have a very very large app already completed and I need to change the authentication method to the way you explained.

I can't go to the 300 places where I use Authenticated User and change them one by one.
This is totally out of the question

I sent this issue precisely to see if the flutterflow team can find a solution.

Example.. Create a rule where the user can create the users collection wherever he needs and this is reflected in the Authenticated User variables

And I don't have to change my entire project because flutterflow is limited in this regard.

**Comment by ricardocosta43** [comment]
My pain is as follows

I have two apps using the same base
I just need to test if a user already has an account in an app before flutterflow tries to create a user within the other app and vice versa

Both apps are 100% ready, I just need to adjust it

If you have any alternative to my pain I will be completely grateful.

I'm trying my best not to export to git and mess around manually
