### ISSUE TITLE
CORS error of place picker in Web app when hosted on firebase

### ISSUE THREAD

**Issue by FilliTech** [FlutterFlow/flutterflow-issues#4786]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I attempt to select a location using the flutterflow place picker, a CORS error occurs.

### Expected Behavior

It should work properly as it does if hosted on flutterflow.

### Steps to Reproduce

1. Create a web page with place picker widget.
2. Connect the project with firebase
3. Download the code locally
4. Host the website in firebase hosting
5. Try to select the location using place picker

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4eiPLqw4t1pbxH7qXxbcFFiSQvHEw7aIIZke5+ZAwbG4z1PbNzY+j+TGZuOLDid2xiPFmWgm00/vDJk/PxD8c4FByJbbZjzJdcbgH/Qj2VeJClBs+sYUFCQOdhJmKOzpuZnBUkJulZR1Ej1GGEJeqiaHLYNr6xC1c/APilMrDPn2CfLgDKGn0Jg1ZSfCvr

### Visual documentation

<img width="326" alt="Screenshot 2024-10-30 at 18 23 07" src="https://github.com/user-attachments/assets/0425dce2-f99a-4724-8304-3ddc51948960">

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: web
- Browser name and version: any
- Operating system and version affected: any
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue on my end. It looks like you're hosting the project on Firebase rather than FlutterFlow. In that case, you'll need to add a proxy to the Place Picker API call within your code before deploying it to Firebase hosting.

When hosted on FlutterFlow, this feature works as expected. Here’s a link to a recently published project via FlutterFlow where you can test it:<br>[https://qa-2935-99mbtu.flutterflow.app/](https://qa-2935-99mbtu.flutterflow.app/)

**Comment by FilliTech** [comment]
The project is hosted on Firebase, on FlutterFlow it works as expected. The problem is that I am using the flutterflow place picker component so I can not, as of my knowledge, add a proxy to the api call.

**Comment by Alezanello** [comment]
Hello, and I apologize for the delayed response. In your Firebase project code, you can navigate to `/lib/flutterflow/flutter_flow_place_picker.dart`. Within this file, add the proxy to the `baseUrl` before `widget.proxyBaseUrl`.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1c301043-f25f-40d4-9059-cdf5edb0d42e/044356cf-cb46-4e10-93a8-d0b201ce9878?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYzMwMTA0My1mMjVmLTQwZDQtOTA1OS1jZGY1ZWRiMGQ0MmUvMDQ0MzU2Y2YtY2I0Ni00ZTEwLTkzYTgtZDBiMjAxY2U5ODc4IiwiaWF0IjoxNzMxNjk4NzY5LCJleHAiOjMzMzAyMjU4NzY5fQ.tMvYDEm6U2mid0jUcJqwswWwQ0ahKcPoRQvwU4RtW40 " alt="image.png" width="665" height="133" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
