### ISSUE TITLE
Unable to test toogle icon feature in flutterflow

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#4787]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a save feature wherein if someone 'hearts' a text, it gets saved. I have to include the action yet, however, I just wanted to test whether the toggle icon is working or not. When I test toogle icon, it just blinks and doesn't stay as 'On Icon'.

### Expected Behavior

In test mode, the toogle button/icon should remain 'On' or colored till the time it is not clicked again. It should not blink.

### Steps to Reproduce

1. Add a grid view and add card to it with a text and toogle icon
2. Add a backend query to the grid view
3. Add style and variable in toogle button
4. Test the same. It should not blink when clicked. If you have liked, it should show the on icon settings.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

CAESZENnMVhjbUZ3WHpRM1pUTmlOMjQzR0RjaU11SURIZ2tBQUFBQUFBQWtRQkVBQUFBQUFBQUFBQmdHSUFNb0FqQUdPQUZBQXZvREFQSUZDd2tBQUFBQUFBRHdQeG9BWWdEQ0FRQT0=

### Visual documentation

![image](https://github.com/user-attachments/assets/d99ebf19-9979-4f21-8b9a-f901cfe02380)

### Environment

```markdown
- FlutterFlow version: 5.08
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by plannedlivingjournal** [comment]
Hi, please don't refer to the error mssg in the screenshot. It was just showing when trying to generate bug code and is not relevant to the query raised. The query is to view this screen and test the toogle icon. It just blinks once and doesn't stay in its 'On feature' settings as expected.

**Comment by Alezanello** [comment]
Hello!

I couldn’t access the issue as the bug report code appears to be incorrect or incomplete. Could you please generate a new one?

Additionally, I followed the steps you mentioned but wasn’t able to reproduce the blinking behavior you described. If possible, could you try recreating the issue in a new blank project? This would help us debug it more effectively.

Thank you for your assistance!

**Comment by plannedlivingjournal** [comment]
Hi @Alezanello please find the correct code:
IT4olsn15YVPj7xE7q6JccBKjSQWOUAlbLgO0cpBZywgfZzzBLN/fPfQPltWTtO+Snxie06mp141/t70kePXD8FfMk2Bf7ZY+od6bjnyUlG6VZOTF7qWPnB5M+5gfUix07aruBVTAPNpc3AB70+YHN+8dAXBO4DJDWo8Sq/LZO4=

Also, I tried creating a new page with same backend query and using the toogle icon, however still facing the same issue.

**Comment by Alezanello** [comment]
**Hello!**

I’m sorry, but I’m still unable to replicate the issue you’re experiencing. Please keep in mind that FlutterFlow automatically toggles the icon for you, so there’s no need to add any additional actions manually.

To help you further, I’ve created a public project showcasing how I achieved this functionality: [View Project](https://app.flutterflow.io/project/qa-2936-op5hp0).

One important note: ensure that you assign a unique key to the components in your lists. This can help prevent unexpected behavior.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3295cbea-a55c-455a-80d9-f9163332304e/a75ee3ef-0a8a-48fc-bc30-0e9b60f84f38?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMjk1Y2JlYS1hNTVjLTQ1NWEtODBkOS1mOTE2MzMzMjMwNGUvYTc1ZWUzZWYtMGE4YS00OGZjLWJjMzAtMGU5YjYwZjg0ZjM4IiwiaWF0IjoxNzMyMTk4MDM4LCJleHAiOjMzMzAyNzU4MDM4fQ.a77_baaUmTxNzlNQptn1h3wPjyxn2MzmmTgzo27pEIo " alt="image.png" width="1150" height="157" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
