### ISSUE TITLE
error in costum widget just after update of FF last thursaday

### ISSUE THREAD

**Issue by evebeauty** [FlutterFlow/flutterflow-issues#479]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

i just want to have all my widget works fine , as it was before the update.

## Current behavior (required)

just after the update of FF of the last Thursday , all my widget shows errors ,with no message in errors log 
I tried to copy paste these widgets into another project, it worked very well, I tried to delete my widgets and reinstall them, but it still doesn't work.
here the project link :https://app.flutterflow.io/project/pamper-you-76cpnu.
and in the other side the  test projects link where it working fine:https://app.flutterflow.io/project/testwidget-ttgiiy

## Context (required)

 it's been blocking me enormously since Thursday, currently I'm very disappointed, because after your updates problems in our projects appear and we have to spend the week asking your help to solve them and it makes us waste a lot of time

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: GoogleChrome
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Hi @evebeauty - Thanks for posting the issue. We can look into this issue shortly. To consider this issue for debugging, can you please add details as per issues template. 

And also share bug report code. You can find here.

![image](https://user-images.githubusercontent.com/17435678/218463940-121ad770-c4bd-4e0b-88a4-27ad48f0bf56.png)

**Comment by evebeauty** [comment]
hello,
here the debug code :

IT4giPLluIh2rsRE0aqBKO9Wr2IsQkg6bYc0sd4bGA0dCJzuPLMQdvWkUEhWXeriTAlXM0SmmT40wMLuhvHQUPU6KQmVY7Z4z5NQdgLLcH+5ZcHfU/HUACkbeacOQSj6

Best regards,
________________________________

**Comment by agreaves** [comment]
Hi @evebeauty, thanks for the bug report! I have confirmed the issue and fixed locally so this should be fixed in our next deploy!
