### ISSUE TITLE
Widget Builder Parameter Issue - Cannot access action parameters of child component as part of widget parameter component

### ISSUE THREAD

**Issue by carsonzylicz** [FlutterFlow/flutterflow-issues#4790]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

See video documentation below:

When accessing a child component as part of a parent component with a widget as parameter, you cannot access the child's action parameters. 

### Expected Behavior

See video documentation below:

When accessing a child component as part of a parent component with a widget as parameter, you should be able to access the child's action parameters. 

### Steps to Reproduce

1. Create parent component which has a widget builder as parameter
2. Create child component which has an action and action parameter
3. Place parent component on page and select child component as the widget for the widget parameter
4.  See that you cannot access action parameters of child when using childs action.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESls/l7YVgot9c+pCNdcB6hQMkQzM6bZI7ku1EdwEhfZyrPex3Zc/8VFJLYteqdFZbe1n+uH8DpvyJjuHfU+wnOQ2dG4t8/4RXQQKXWnqXMoi2Ps6NP3B8TMdQfna/yqunhB4lGMluLng52Uy6GPCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

[Screen Recording Explanation](https://us06web.zoom.us/clips/share/qjSLjMeNrVkdcJuhQxdTe6d6iUpqCmgRCvvGbcr4rFXtwujo36A3xRl5UAkiGoIkzfEHA1sS3ZcEjRlKjBPuq1Vo.yRlJBBApI_vWjBqb)

### Environment

```markdown
- FlutterFlow version: v5.0.9
- Platform: macOS
- Browser name and version: N/A
- Operating system and version affected: Sequoia 15.0.1
```

**Comment by Alezanello** [comment]
Hello!!

Thank you for bringing this up! I'll reach out to the engineering team to confirm the expected behavior for this issue.

**Comment by Alezanello** [comment]
Hello again!

I just reviewed this, and it appears to be the same issue as [Issue #4003](https://github.com/FlutterFlow/flutterflow-issues/issues/4003). To streamline efforts, I’ll close this as a duplicate so we can focus on resolving it within the original report.

Thank you!
