### ISSUE TITLE
Remote Config parameters can only be strings, booleans, integers or doubles

### ISSUE THREAD

**Issue by filippopassante** [FlutterFlow/flutterflow-issues#4793]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Remote Config parameters can only be strings, booleans, integers or doubles.

Other data types are not allowed.

### Expected Behavior

I expected other data types to be allowed, given that, as FlutterFlow's [documentation](https://docs.flutterflow.io/integrations/firebase/remote-config#2-add-parameter-in-firebase-console) itself confirms, Firebase Remote Config allows for that.

### Steps to Reproduce

Create a blank project or visit the [documentation](https://docs.flutterflow.io/integrations/firebase/remote-config/#3-add-parameter-in-flutterflow).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhfLluIhOsdhE1s+JbMFWpCEwFjsaU40V0tcbTUs0fZDoELQLd+r+VxFaYO2FTX5heVH9oGQf3MKKkfHPCvBdHzmZeINoz5ABbTnxQnmVRLK1DZGWWHZCP+lgGnXF3MC03SVABMVodXwbw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/46149293-8cd6-44b2-9b13-aaabe94aca48

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform: MacOS Desktop
- Browser name and version: not applicable
- Operating system and version affected: macOS 15.0
```

### Additional Information

I wanted to use Remote Config to store the app's terms of service, which seemed handy since Remote Config enables you to set default values which can be deployed together with new app versions.

Using Firestore together with static files can do the same thing and may even be more reliable at scale, but I'm not sure why FlutterFlow doesn't allow you to have Remote Config parameters of custom data types.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention! This looks more like a feature/enhancement request rather than a bug. I’ll create an internal ticket for the engineering team to consider this improvement.

In the meantime, I’ll close this issue to keep the GitHub Issue Tracker focused on reproducible bugs. We appreciate your understanding and patience!
