### ISSUE TITLE
The same thing happends when you parse data to a datatype, null values are being transformed into empty string, this is a problem, specially when dealing with uuid values.

### ISSUE THREAD

**Issue by pireslopesvinicius** [FlutterFlow/flutterflow-issues#4795]
The same thing happends when you parse data to a datatype, null values are being transformed into empty string, this is a problem, specially when dealing with uuid values.

_Originally posted by @tiagosilveiransj in https://github.com/FlutterFlow/flutterflow-issues/issues/2246#issuecomment-2449829442_

**Comment by Alezanello** [comment]
Hello!

This issue is being closed as it duplicates an existing feature request already in the team’s backlog. I’ll close this issue now, and please feel free to continue any discussion in the original post.

Thank you!
