### ISSUE TITLE
Could not find an option named "project-environment"

### ISSUE THREAD

**Issue by brunoconceicao** [FlutterFlow/flutterflow-issues#4796]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi everyone,

when I try to download the application with the code generated in the flutterflow cli, I get this error

FormatException: Could not find an option named "project-environment".

I created another environment called Homolog and it has an environment variable

### Expected Behavior

Download code

### Steps to Reproduce

1. Click em developer menu
2. Copy FlutterFlow cli command
3. In a folder I open the terminal and paste the cli code and press enter

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXl/LYyIhisshE+c72ce1ogiUwGUwbUOc7j9VEGAsjCePxOooqZc7RU1ttcuqHdFZXM1KYuFoz+NbuufGfUfZdNQ2bfYhJ1c91UxDvWnu6Vqq4OpG0WHxtEcdhfxWy1MGwkQlTIvRZLU4d2E2IFfOQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Captura de tela 2024-10-30 115614](https://github.com/user-attachments/assets/8cc051b6-5f03-40e3-9820-d127d12300b2)

### Environment

```markdown
- FlutterFlow version: 5.0.9+
- Platform: 3.24.2
- Browser name and version: Windows Application and Google Chrome
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello!

Could you confirm if you have the latest version of the FlutterFlow CLI installed?<br><br>`dart pub global activate flutterflow_cli`

If so, the command should be as follows:

`flutterflow export-code --project [PROJECT_ID] --project-environment [ENV_NAME] --include-assets --token [API_TOKEN]`

Let us know if you have any questions!

**Comment by brunoconceicao** [comment]
Work, tks!!!!
