### ISSUE TITLE
unable to update calendar date to app state automatically

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#4797]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a calendar widget (hidden) and want to use the 'selected date' as an app state. Hence, everyday when the calendar's present date changes, the app state should also update, since throughout app I have added backend queries in which info will be extracted depending upon today's date.
However, the update app state only happens when a user clicks on calendar, but in my app calendar is hidden from user since I wish to only use the current date to extract information from back-end. I tried using 'Current time', however, it takes exact time and there is no way in which the date can be extracted.

### Expected Behavior

Everyday when calendar date changes, app state should be automatically updated without user input

### Steps to Reproduce

1. Add calendar widget, however make its opacity 0 since its not required from user
2. Create an app state

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn15YVPj7xE7q6JccBKjSQWOUAlbLgO0cpBZzwgGKLyPLMUZ876P0hWUse4S3xAJWaMp14D0+DWj/LlVO0pAEycRp9yyM0NVgrjRmK7RqmTF7qWPnB5M+5gfUix07aruBVTAPNpc3AB70+YHN+8dAXBO4DJDWo8Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/574db996-51df-4e64-ab58-45962433a73d)

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment]
Hello!

I apologize; I’m not fully understanding the use case here. Would you be able to provide a video demonstrating what you’re trying to achieve or some more detailed steps to reproduce the issue? Alternatively, if possible, creating a new blank project with just the necessary widgets and variables would help us pinpoint where the bug might be.

Thank you for your help in clarifying!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
