### ISSUE TITLE
Scroll inside the page (in column) doesn't work in desktop app.

### ISSUE THREAD

**Issue by kinnnky** [FlutterFlow/flutterflow-issues#48]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## To Reproduce (required)

1.
2.
3.
4.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
HI @kinnnky - In order work on this issue, we required a detailed reproduce steps. It hard to understand and work in the issues which does not have enough details to reproduce the issue. Please add more details.

**Comment by agreaves** [comment]
Thank you for reporting this, this is now fixed!
