### ISSUE TITLE
Calendar in week view not select the selected date

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#480]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

- When do a scroll and select a date that date should be selected
- When you are scrolling the month should be updated

## Current behavior (required)

- When do a scroll and select a date is moved to the current day instead to select the selected date
- When you are scrolling the month is not updated

## To Reproduce (required)

1. Add a calendar widget
2. Do a scroll and you see the month won't be updated
3. Do a scroll and select a date and is moved to the current day (*)

(*) Only happens on week view

### Bug Report Code (required, generate by right clicking inside Widget Tree and clickig "Get Bug Report Code")

ITFflfLl8ZNOm99Y15SJKvkwnj0WNm0cTIAziu1udw0jCJznBu0PPMzBNxBWOdOnaVNcOFKjnkYypMLLifH1VsYFFE2Cf4g5/rgNcznAKTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)

I want select a past date on week view

## Screenshots / recordings

https://schoolfy365.tinytake.com/df/13fa692?&salt=Nzg2ODIzM18yMDk0ODYyNg

## Your environment

* Version of FlutterFlow used: 11 February
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 109.0.5414.120 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 Pro - 22H2 - OS build: 22621.1105

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Thanks for posting this issue. I just verified it and can see that is working as expected. Scrolling is not a implemented feature. To move next-week/month page you should use arrows. 

See below video.

https://user-images.githubusercontent.com/17435678/218544315-e34183fd-0d7f-40cb-9e2a-6eef975f6d8e.mp4
