### ISSUE TITLE
Blocking error on local run since FF v5.0.9: deprecated @UIApplicationMain attribute, updating

### ISSUE THREAD

**Issue by kaymasse** [FlutterFlow/flutterflow-issues#4801]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the FF update v5.0.9, the local run is failing (both on iPad simulator and on real iPad) on the app I am building. Note that it works if I create a blank project. I will explain below.

When I use the local run, I get a popup with the error:
<img width="760" alt="Error 1" src="https://github.com/user-attachments/assets/93dacb8f-88ee-426d-add2-1b09acea1e1b">

And then I get a second series of popups:
<img width="1030" alt="Error 2" src="https://github.com/user-attachments/assets/d670839a-0043-464a-a403-e46a5ce82c08">

Note that in the case of my project, it fails to run. If I use a blank project, I get only the first error popup (not the others) and then it runs successfully.

Here are the device logs when running on the simulator device:
```
Updating local specs repositories

CocoaPods 1.16.1 is available.
To update use: gem install cocoapods

For more information, see https://blog.cocoapods.org/  and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.1

Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing app_links (0.0.1)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sign_in_with_apple (0.0.1)
Installing sqflite (0.0.3)
Installing url_launcher_ios (0.0.1)
Installing video_player_avfoundation (0.0.1)
Installing wakelock_plus (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 11 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target Runner to Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig or include the Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig in your build configuration (Flutter/Release.xcconfig).
Launching lib/main.dart on iPad (10th generation) in debug mode...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Running pod install...                                          ios/Runner/AppDelegate.swift uses the deprecated @‌UIApplicationMain attribute, updating.
862ms
Running Xcode build...
Xcode build done.                                            7.4s
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.

Could not build the application for the simulator.
Error launching application on iPad (10th generation).
```

### Expected Behavior

I would expect the local run to run without errors.

### Steps to Reproduce

1. Select iPad simulator device
<img width="422" alt="device selection" src="https://github.com/user-attachments/assets/871df79a-6446-40ed-8b2c-35a6684a92a3">

2. Click on 'Test'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48k876y4xOxcdA1pDbbcdvmiURKUc7R4INie5hSUs8J5zKB+wAYvf7P1FWTLyjSghYOkyWgnIx/Pfqj9rxL/YBAzGVGKZ71KtcehXwZz6iRbKXBbm7fW1fP+BTf3ayy8OJswpQOuxoLy0871+QIvDKEnXUQ+/PPEUnRfK1KdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/3ab54785-fe2f-487a-bb1d-2a02f83f26a0

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform: MacOS Desktop 
- Browser name and version: Simulator with iPad 10th generation, iOS 17.5 
- Operating system and version affected: macOS Sequoia 15.0.1
```

### Additional Information

I am completely stuck in my development and waiting for a way to solve the issue.

**Comment by Alezanello** [comment]
Hello!

This issue has already been addressed, and you can find the solution here: [GitHub Issue #4458](https://github.com/FlutterFlow/flutterflow-issues/issues/4458).

Thank you!
