### ISSUE TITLE
Cannot use Team Library Actions as a custom action in main.dart

### ISSUE THREAD

**Issue by 18mstalberg** [FlutterFlow/flutterflow-issues#4803]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have added a project that I published as a Team library as a dependency for my project. I can correctly access the custom actions within the normal action flow editor and within the app normally, but the actions are not available as options in the custom code Initial Actions or the Final Actions for `main.dart`. 

I have a configuration action that has no parameters that is valid for using in main.dart as an Initial Action, but it does not appear as an option when trying to add an Initial Action.

### Expected Behavior

After publishing a team library with a parameterless custom action, when you attempt to add a custom action as an "Initial Action" or "Final Action" in main.dart, under the "Custom Files" section of custom code, the custom action from the library should appear as an option.

### Steps to Reproduce

1. Create a new Project.
2. Add a custom action with no parameters.
3. Publish project as a library.
4. Create or select a different project.
5. Import the project as a dependency
6. Navigate to custom code tab.
7. Select main.dart from the `Custom Files` section
8. Select the plus + button in the Initial Actions or Final Actions.
9. Observe that the action is not available as an action to use.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A and can't find where widget tree referred in the instructions is. No documentation on that either.

### Visual documentation

<img width="1485" alt="Screenshot 2024-11-01 at 11 42 44 AM" src="https://github.com/user-attachments/assets/323e8245-bdc0-4c44-bdea-29d92843a91e">

### Environment

```markdown
- FlutterFlow version: v5.0.9
- Platform: N/A
- Browser name and version: N/A
- Operating system and version affected: N/A
```

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out. This is a known issue, and the team is actively working on a fix. You can track the progress here: [GitHub Issue #3969](https://github.com/FlutterFlow/flutterflow-issues/issues/3969). I’ll go ahead and close this issue as a duplicate.

Thank you for your patience!
