### ISSUE TITLE
Can't access library values in consumer project

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#4805]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/d13c7581a2c141b3b1130fca11497f5c
<img width="340" alt="Screenshot 2024-11-01 at 8 31 38 PM" src="https://github.com/user-attachments/assets/b2874d72-552d-4d83-b194-82ab5dd3110b">

### Expected Behavior

<img width="386" alt="Screenshot 2024-11-01 at 8 28 49 PM" src="https://github.com/user-attachments/assets/0230bcbe-c913-49aa-b343-e21ebe53cf39">

### Steps to Reproduce

import library as dependency works
values appear in the dependencies tab
can't access the variable anywhere

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elsjfsI12oblE7rr+KfpR/WAQKUgjRY0ziutEdAw0Ibb1PLNydujxN3dWUu3idghLe039ij0KzPeLm9z1MsAqOUuubtU5zahbEzzMYFiXR8WhEc2WZ0REGshMCWKZ1J23vBJ/BNJZWiEWwU6EN+m+cBXaN4z3Pm0FJc/8LZ3XvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

https://www.loom.com/share/d13c7581a2c141b3b1130fca11497f5c

### Environment

```markdown
latest flutterflow, chrome or desktop app same problem
```

### Additional Information

https://www.loom.com/share/d13c7581a2c141b3b1130fca11497f5c

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I can confirm this is a bug, and I’ll pass it along to the engineering team for a fix. We appreciate your help in improving the platform!

**Comment by leighajarett** [comment]
Hi there, this is expected behavior. Library values are created to pass values back to the Library project. <br><br>Can you tell me a little bit more about your use case and why you would want to access Library Values in the consumer project?

**Comment by chuggmuffinReturns** [comment]
Hi Leigha!
Much appreciated for the heads up.

I think I get what library values are intended to do now which is kinda
sweet! Seems a lot like passing parameters into a component.

But there are a couple situations that I am a bit confused about.

1) why have the "library values" dropdown in the consumer project if the
consumer project is not a library
2) why there are limitations on the dynamic nature of the library value

I made a video that is marginally if not quite rambly that sorta shows this
:)

https://www.loom.com/share/e272b7bfa266496c99ad97490fdbbe2b

Thanks!

Brian

**Comment by leighajarett** [comment]
Thanks! 

1. You're totally right - this is a bug and needs to be removed, will get that removed ASAP
2. Yes it's correct to assume it's like a parameter - but the intended use is for things that are constant values, not dynamic fields. So you could use your example with App State and instead replace it with a constant and that will work. We made this design decision because the use cases in mind were for things like API keys and configuration settings, not dynamic properties. If you have a specific example of why you would want to dynamically pass in something at the library level (note you can send in dynamic variables for things like function / action inputs and component / custom widget inputs), then I'd be curious to learn more!

**Comment by chuggmuffinReturns** [comment]
@leighajarett 

1. fascinating... OCD is triggering that the label of "confirmed not a bug" is still on the issue. Not a personal score keeping thing for me but more a "i hope it doesn't slip through the cracks accidentally" thing. 

2. I think as I better wrap my brain around what Library Values are for versus creating library components with dynamic variables I'd be able to tell you... 

...especially since you can import "library app state" variables I imagine that likely covers sorta kinda what was brewing in ye'ole' noggin...

...but if I come up with something that would be useful for a dynamic library variable Ill be sure to let you know :)

**Comment by leighajarett** [comment]
We already fixed 1, will be deployed in next release! We already had another internal bug tracking it

**Comment by chuggmuffinReturns** [comment]
Gotcah ok cool! Thanks for the update :)
