### ISSUE TITLE
Orphaned subcollections throw errors for Firestore setup

### ISSUE THREAD

**Issue by henryweimd** [FlutterFlow/flutterflow-issues#4809]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Blocking error appears when subcollections are still present but parent collections were deleted.
Error text:
Collection "[name of collection]" is a subcollection but the parent collection no longer exists. Tap here to delete it.

Tapping on the error just brings to the Firestore tab, but does not offer any way to remove or delete the orphaned subcollection or else resolve the error issue.

### Expected Behavior

Tapping on the error should offer any way to remove or delete the orphaned subcollection or else resolve the error issue.

### Steps to Reproduce

1. Create a collection
2. Create a subcollection
3. Delete the parent collection

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Visual documentation

![Screenshot 2024-11-03 at 3 49 37 AM](https://github.com/user-attachments/assets/592ae9d8-0a51-4a32-92ae-420a4b010ac2)

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Web
- Browser name and version: Chrome Version 130.0.6723.92 (Official Build) (arm64)
- Operating system and version affected: macOS Sequoia
```

**Comment by Alezanello** [comment]
In this case, have you tried re-adding the parent collection name, then deleting the subcollections, and finally deleting the parent collection?

**Comment by henryweimd** [comment]
It wound up needing me to delete the parent collection entirely — somehow
the sub collection was orphaned and not the parent, then as I deleted all
the collections eventually an interface showed an option to clean up and
delete the orphaned subcollection.  Odd!

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
