### ISSUE TITLE
error importing library

### ISSUE THREAD

**Issue by cristiangiroon** [FlutterFlow/flutterflow-issues#481]
I was using the syncfusion_flutter_pdf 20.4.49 library and with the latest updates error comes out when importing the library

## Expected behavior (required)
I can´t import and use the library  syncfusion_flutter_pdf 20.4.49

## Current behavior (required)
this error ----- > Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.<-----------------------

THE CODE -----> 

## To Reproduce (required)

import 'package:intl/intl.dart' as intl;
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
Future shareDocumento(
) async {
final PdfDocument document = PdfDocument();
document.pages.add().graphics.drawString(
    'Hello World!', PdfStandardFont(PdfFontFamily.helvetica, 12),
    brush: PdfSolidBrush(PdfColor(0, 0, 0)),
    bounds: const Rect.fromLTWH(0, 0, 150, 20));
final file = File('${directory.path}/my_file.pdf');
await file.writeAsBytes(await document.save());
document.dispose();
}

## Context (required)

i can´t use the library  syncfusion_flutter_pdf 20.4.49 in my project 

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by aemelyanovff** [comment]
@cristiangiroon Please add a bug report link from anywhere in the project.

**Comment by aemelyanovff** [comment]
Closing as inactive. @cristiangiroon please feel free to reopen if you add a bug report link.
