### ISSUE TITLE
Can't create custom code

### ISSUE THREAD

**Issue by LoginPanel07** [FlutterFlow/flutterflow-issues#4810]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Im trying to create a custom action and function, but none of them are getting saved even though im pressing the Save Function button.

### Expected Behavior

It should just save and stay in it's category

### Steps to Reproduce

1. Add a custom action or function
2. Write something in it
3. Press save

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Icannotextractbugreportcode,nothinghappenswhenirightclickafterchoosingapage

### Visual documentation

![image](https://github.com/user-attachments/assets/7281784e-3d76-4f0b-b101-2dc932423538)
![image](https://github.com/user-attachments/assets/853c2f3e-763e-41d4-a2d3-a3c9e8056ff9)

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: PC browser and app
- Browser name and version: Chrome 130.0.6723.92
- Operating system and version affected: Windows 11
```

**Comment by chuggmuffinReturns** [comment]
@LoginPanel07  the action name and the function need to have the same name

**Comment by chuggmuffinReturns** [comment]
ie not called newCustomAction but paseSiteMapXML

**Comment by LoginPanel07** [comment]
But i can’t create either of them

chuggmuffinReturns ***@***.***> (időpont: 2024. nov. 3., V,
19:57) ezt írta:

**Comment by LoginPanel07** [comment]
So i should leave it newcustomaction and it will work?

chuggmuffinReturns ***@***.***> (időpont: 2024. nov. 3., V,
19:58) ezt írta:

**Comment by LoginPanel07** [comment]
[image: image.png]
As you can see I cannot create any actions or functions. The problem is
definitely not that their names are not the same cause there is not a
single one to have the same name with, as i cannot create a single function.

chuggmuffinReturns ***@***.***> ezt írta (időpont: 2024. nov.
3., V, 19:58):

**Comment by Alezanello** [comment]
Hello!

As chuggmuffinReturns mentioned, to save an action correctly, you need to set a name for the action in the title field. It looks like the images you shared in your follow-up comments aren’t visible—this may be due to replying via email. Could you please upload the images directly here on GitHub? Alternatively, a short screen recording (e.g., using Loom) showing the issue would be very helpful. A brief clip will work; just a quick walkthrough of the steps you’re taking.

Thank you!<br><br>P.S: Here is the documentation with a lot of videos on how to do it properly: [https://docs.flutterflow.io/concepts/custom-code/](https://docs.flutterflow.io/concepts/custom-code/)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/98676eab-60ed-4bb5-b5f6-d87813ae52db/7e5cd318-e370-4b29-b316-2163ce81f0bf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ODY3NmVhYi02MGVkLTRiYjUtYjVmNi1kODc4MTNhZTUyZGIvN2U1Y2QzMTgtZTM3MC00YjI5LWIzMTYtMjE2M2NlODFmMGJmIiwiaWF0IjoxNzMwNzMxMjgzLCJleHAiOjMzMzAxMjkxMjgzfQ.GGKSwpF_ywGea3UhkzSg7hrx47fyIoYSAowasg-1H2U " alt="image.png" width="900" height="648" />

**Comment by LoginPanel07** [comment]
![image](https://github.com/user-attachments/assets/470a7d69-7c35-40db-bb56-a2a09f6f0dda)
Here is the picture, as you can see they are the same name

**Comment by Alezanello** [comment]
In this case, you need to add the Arguments (the string you expect to receive) and the Return Value.

**Comment by Alezanello** [comment]
Please do not set this as a Function but as an Action

**Comment by LoginPanel07** [comment]
Yeah sorry, i did it like that first, but i thought i was doing it wrong. As you can see on the picture, It is not saved, even though i clicked on save and confirmed it. It says i saved it, but as you can see on the left there are still 0 custom actions, and when i click away from there the code doesn't disappear, but it says it's an unsaved code that it restored.(all i need is the series list, and i set a return for it at the end, as well as there is an Argument (String xmlData))
![image](https://github.com/user-attachments/assets/62d91b2d-654a-46c2-8812-f3868323adaa)
![image](https://github.com/user-attachments/assets/c742c70c-5d7a-4066-9759-32636e18c36e)
![image](https://github.com/user-attachments/assets/35633990-86a3-4832-b6f0-5e600f3fc8fd)

**Comment by LoginPanel07** [comment]
Oh, im sorry, i didn't see the sidebar with the define arguments and return value. I'm guessing i should have set those up too, and that's what you are saying?

**Comment by LoginPanel07** [comment]
I set them up, and saved, however the same problem still persists:
![image](https://github.com/user-attachments/assets/2cc8471d-5b4b-4e59-86df-6f20483c58af)

**Comment by LoginPanel07** [comment]
Can you create the custom action with the following action, save it and have it stay? Here is the code:
```
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
import 'package:xml/xml.dart' as xml;

List<Map<String, dynamic>> parseSitemapXML(String xmlData) {
  final document = xml.parse(xmlData);
  final urls = document.findAllElements('loc');
  final List<Map<String, dynamic>> seriesList = [];

  for (var url in urls) {
    final pageUrl = url.text;
    if (pageUrl.contains('chapter')) {
      final trimmedUrl = pageUrl
          .replaceAll('https://spiderscans.xyz/', '')
          .replaceAll('/', '');
      final parts = trimmedUrl.split('-');

      final chapterNumber = parts.removeLast();
      final seriesName =
          parts.join(' ').replaceAll('-', ' ').replaceAll('Chapter', '').trim();
      seriesList.add({
        'name': seriesName,
        'chapter': chapterNumber,
        'url': pageUrl,
      });
    }
  }
  return seriesList;
}
```

**Comment by chuggmuffinReturns** [comment]
@LoginPanel07 I think the problem is in your return type not being a custom data type.

https://www.loom.com/share/d38f4c7a6d2f41d0930d725daf7d369d

Get ChatGPT to walk you through it... I started here a bit but didnt get to the end but may offer some hints

https://www.loom.com/share/daecc04b42dc4455912e8b74ef2a4275

**Comment by LoginPanel07** [comment]
Thank you very much for your help, i was finally able to save(and ChatGPT fixed my code after trying to use the map type 4 times again XD), however i found some problems. The first is that it won't let me choose the custom data type, and instead automatically changes to json when saving(not sure if it's a problem and interferes with the program or not, i have created the the custom data type properly though, 3 strings with list attributes), the other problem is that it does not recognize the xml import, the third is that it just randomly out of the blue(it didn't have any troubles with it checking it multiple times), it does not recognize parse. Once again im very thankful for your help Bryan.
![image](https://github.com/user-attachments/assets/3960f395-0e97-4da1-bea2-a46968593912)
Code(if needed):
```
// Automatic FlutterFlow imports
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:xml/xml.dart' as xml;

List parseSeriesNames(String xmlData) {
  final document = xml.parse(xmlData);
  final urls = document.findAllElements('loc');
  
  final List names = [];
  final List chapters = [];
  final List links = [];
  
  final baseUrl = "https://spiderscans.xyz/";

  for (var url in urls) {
    final pageUrl = url.text;

    if (pageUrl.contains('chapter')) {
      final trimmedUrl = pageUrl.replaceAll(baseUrl, "").replaceAll('/', '');
      final parts = trimmedUrl.split('-');

      final chapterNumber = parts.removeLast();
      final seriesName = parts.join(' ').replaceAll('-', ' ').replaceAll('Chapter', '').trim();

      names.add(seriesName);
      chapters.add(chapterNumber);
      links.add(pageUrl);
    }
  }
  return [names, links, chapters];
}
```

**Comment by chuggmuffinReturns** [comment]
Missing a super key point about how this works... @LoginPanel07 

https://www.loom.com/share/9d05fe7886e1407682745f68135e294f
