### ISSUE TITLE
Inconsistent Behavior of Dropdowns and Text Fields in FlutterFlow App on Safari Browser

### ISSUE THREAD

**Issue by guilhermebpm** [FlutterFlow/flutterflow-issues#4827]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am experiencing issues with the functionality of dropdowns and text fields in my FlutterFlow app when accessed via Safari. Specifically, dropdowns do not support search, and text fields are unresponsive or do not accept input. These components work as expected on Google Chrome and in the Safari environment when directly on the page. However, when these elements are nested within a component inside a page, they fail to function correctly on Safari.

### Expected Behavior

Dropdowns and text fields should work consistently across browsers. In both Chrome and Safari, dropdowns should support search functionality, and text fields should accept user input, whether directly on the page or nested within components.

### Steps to Reproduce

1. Open the "Vendas" page in the FlutterFlow application.
2. Click on the "Cadastrar Vendas" button located at the top right corner of the page.
3. In the "Cadastrar Vendas" form, click on "Cadastrar Produto" to open the product registration component.

Note: Ensure you’re testing this flow on both Chrome and Safari for an accurate comparison of behavior.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8j6yItPxOFK0LrubPpR/ScUNjM6U4ZNmu1xZ00jIZ/NG7UIec/4VEptXbC+TVc2fVmJmmMx0+DJkubIN/cCNRGZb6Zb1c9uZRXdd3KXb4+YBqqgXHMmNNpKChDE0qW3kx0kNtBeR1YN71yIIuevUgHYCYz3NlgvOeaIUYf4s3PuQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/36eacf49-2be1-4f25-946d-7038ffca5072

https://github.com/user-attachments/assets/7f67df6a-682b-48c1-b2d2-494cd3d871c3

### Environment

```markdown
- FlutterFlow version: v5.0.9+
- Platform: Web
- Browser name and version: Safari 17.0
- Operating system and version affected: macOS
```

### Additional Information

I have already tried disabling CanvasKit and switching from Bottom Sheet to Custom Dialog. This issue is critical as it is essential for the functionality to be consistent across both browsers. Any assistance in resolving this would be greatly appreciated.

**Comment by Alezanello** [comment]
Hello!

This seems to be more of a Flutter rendering issue rather than something specific to FlutterFlow. Have you checked the Flutter GitHub repository to see if there are similar reports?

It looks like this issue has been observed before: [Flutter Issue #136006](https://github.com/flutter/flutter/issues/136006). Since this is a core Flutter issue, it would likely require a fix from Flutter itself through future updates, rather than a change within FlutterFlow.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
