### ISSUE TITLE
Unable to add project dependencies

### ISSUE THREAD

**Issue by spanishpy** [FlutterFlow/flutterflow-issues#4828]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to add a project dependency, I get an error message stating 
> Error: The caller does not have permission to execute the specified operation.

### Expected Behavior

I would expect the dependency to be added with no issues.

### Steps to Reproduce

1. Go to Settings -> Project Dependencies
2. Add a dependency (e.g: flutter_stripe)
3. An error banner shows up (screenshot attached)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi8rl5YpIrtxE7aX6bu9apGU4C2IgU4c0sd4bGA0dCJzuPLMQdvWkfhJBOMvkTX9XfUSmmmAK06nUhuPTGPBcPSmZRoBM+bVyUw2UfGaRQZOBErm0W3ZQEZ9gJh2F5J+O2CRCIbBfcnAh72aYOPPJcBbXQqawImdISq/LZO4=

### Visual documentation

<img width="576" alt="Captura de pantalla 2024-11-04 a las 20 30 33" src="https://github.com/user-attachments/assets/870d60d3-2eab-411c-9a43-57ebb40b9e1f">

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform: Mac
- Browser name and version: Desktop app
- Operating system and version affected: MacOS Sonoma 14.4.1
```

**Comment by Alezanello** [comment]
Hello!

To add a dependency to your project, please go to the Custom Code section. You can add it within any Custom Action, even if it’s just a placeholder that won’t be used in your app.

Please note that the Project Dependencies section only supports libraries provided directly via FlutterFlow Projects and published as library.

Hope this helps! Let us know if you have any questions.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
