### ISSUE TITLE
Conditional Visibility + Animations = problem

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#483]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Can use all 3 together
- Conditional Visibility
- Animation: On Page Load
- Animation: On Action Trigger

## Current behavior (required)
Cannot use all 3 together - user must click on the choice chips twice
- Conditional Visibility
- Animation: On Page Load
- Animation: On Action Trigger

## To Reproduce (required)

kindly see the test project i've created for yall

### Bug Report Code (required, generate by right clicking inside Widget Tree and clickig "Get Bug Report Code")
ITwCl/KB249OxLlE7aqNacFVimAUJjM6RYI309VQEEsYF4jxEokIec/7VFJoTemkTFZIOk+WknszpvTWvePfEscnOgmAf7p/1qlTWB3PRk+VRcWSBs+OSERQGdxhfBzG4be3hR57PvJYXXsBw0OLfuvIfCjfQZjXCzEzPfKiLoLNjlK/AnvGXn0Jg1ZSfCvr

## Context (required)
kindly see the test project above

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by joshensongric** [comment]
@Zack1010OP - thanks for reporting this - could you please provide more details / steps to reproduce (and or the link to the test project you kindly created) - thanks! :-)

**Comment by Zack1010OP** [comment]
hi @joshensongric ! oops sorry i forgot to put the link to the public project! here it is!

https://app.flutterflow.io/project/action-animation-bug-with-conditional-visibility-95m193

it's quite long to type out all the steps so i've created each scenario for you already, i think you'll understand when you see it. if you're not clear on any of it just let me know and i'll expand on it here k? thanks!!!!

**Comment by wenkaifan0720** [comment]
Hi @Zack1010OP. Thank you for the detailed explanation and examples in your linked project! I have identified the issue, and is working on a fix.

**Comment by Zack1010OP** [comment]
谢谢你 Wen Kai!!Warmest regards,IsaacOn 19 Feb 2023, at 4:57 PM, Wenkai Fan ***@***.***> wrote:﻿
Hi @Zack1010OP. Thank you for the detailed explanation and examples in your linked project! I have identified the issue, and is working on a fix.

**Comment by wenkaifan0720** [comment]
Hi @Zack1010OP. The problem with conditional visibility + animation is that when the animation starts at the same time the widget becomes visible, the animation don't know what to animate. Could you add a 50/100ms delay before you start the animation? That should fix the problem. Otherwise, we need to make some significant change to our framework to handle such a tricky situation.

**Comment by Zack1010OP** [comment]
Ok sounds good!I was wondering if backend the animation was firing first or the visibility was that was why the problem was being caused, but yea makes sense the animation doesn’t know what to animate. Thanks again WenKai!!Warmest regards,IsaacOn 23 Feb 2023, at 8:54 AM, Wenkai Fan ***@***.***> wrote:﻿
Hi @Zack1010OP. The problem with conditional visibility + animation is that when the animation starts at the same time the widget becomes visible, the animation don't know what to animate. Could you add a 50/100ms delay before you start the animation? That should fix the problem. Otherwise, we need to make some significant change to our framework to handle such a tricky situation.

**Comment by Zack1010OP** [comment]
Argh WenKai - it did what you said and it works perfect but when I try to also add in On Page Load it all messes up.

Conditional Visibility and On Page Load causes the widget not to show up.

Basically my objective is just to make the app feel more premium - on page load the list view fades in, then when buttons are pressed it also fades.

Any luck getting the On Page Load to work with Conditional Visibility?

I tried setting the delay to 1ms for Action Trigger and it works, On Page Load I tried different settings from 1ms to 100ms and all doesn’t work.

Lastly I also think that the wording for “Apply same duration & delay” should be changed to “Apply DIFFERENT duration and delay” cause  when we toggle on the switch then it becomes different = )

**Comment by wenkaifan0720** [comment]
Hi @Zack1010OP. Sorry for the late reply. I looked into the code and I don't think on page load can work with conditional visibility. Because when the page is loaded, the widget is not even there to begin with, so animation wouldn't make sense. If you want to make on page load work, you should specify the initial option of the dropdown in this case.
