### ISSUE TITLE
Phone Auth does not correctly navigate to VerifyCode page

### ISSUE THREAD

**Issue by PrenSJ2** [FlutterFlow/flutterflow-issues#4830]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. enter phone number
2. gcaptura successful
3. I received text with code
4. 11.2.0 - [FirebaseAnalytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "deep_link_id" = "https://voulez-vous-97921.firebaseapp.com/__/auth/callback?authType=verifyApp&recaptchaToken=03AFcWeA4Hel5RWKH2wNJpEtwD6WteoAjyjcOePpuGnL3P_dqD6_DiA7OAbaCypIAs1NZfl8oRSU5SYzlAHVAmf9S4_hdquHfhg_XAtHcPQUsLONKegACr4Aou24sTz-j4nK_XEtfD4W5PPYPZoioBlEF6TyX0_EBOm7neeQ8HZUZXXnVy--fmgYeqG73wPGdi724oj-SRhJQnFEhUETrqluwwhs4kh9EDOpCG0jPsXlREOKlrcz0PKAm_YTUk_3guQCtdc9YvTpT4Pube5gpRUyg1Pa6okX6CzOZJ8fOLuqyJ6UqN19XhVD5HVBuJsTl6mXkyh6SP0wBmx4-w0v0v6S8E8nxBmn4MXD1ipRnMeNtk1QJa24Y7H4IQNChX5QJrd2B5XI1VONq8IWqTzZDoNiLAzIEPdWkML8nnnMVQVpo2r4HNUXix6k3SBanT_k80Dk3JUgA--rhzwfiPr-3bo34UCOyPkEk1oJTiq4yWkr4UobpTxz1FtYrT19C74TfD3COcQHXIDtAgHhChVnhk6_cT4WvGkKqF2D7px9JFVyHRXaBfrp7ChDAEkaoGGNp5cYxjlRe5t_4X8dSpcr2NM9Gku1o8Iy7cj3Q9JExpYxRnBKXmUAugouhgi9Va_-bJ0t4wFW9SJ8ll3xfLicjCpsWCu3x63WSahZ-AywOKZbhJYUCRPw6IGfaeymJ-MI4fL6fD89bZnjHpLT5gbUENZnNFlrqWRjYI_EgfR5SsFeH04C648ecvcjhsTH70l8VzgzNed9uYoJllIbX-T5inA1sdTv5l0uKKIpfZxnWTxd4Ffu5BkN2UEyjEO570RffofN4suTpPgLrP2qgbIhnET-fBJWqoUCsGkjbpRJI6LiWREVTt1B1HxUaqBcBqOZACNfKGnosMmE3kavG1Oj0T_Cxve6chUcp-H23gFWX0Tp6dD0WKIymGN-U&eventId=WSBVGMVLDA";
    
5. App redirects to login page and not VerifyCode page

### Expected Behavior

redirection to the VeridyCode page

### Steps to Reproduce

above

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4szcmB34x2ruJE0JCBKMB7/GUWC2J6bbs8scsZa0kdB4joPLJ/P+P8TFBCcM+kTENhHFeb/UkD0vDHvvPfLMA7NQ+qQap9yLgBcBXvVXq8RZSTBbWZdHElQJ1Tf3ae4J2rpSZBKtZeWGAH1F2QBeeAZA7dGZu/Zwh9f6PHaOI=

### Visual documentation

![peek_3](https://github.com/user-attachments/assets/6352208c-1abc-4e0b-b88b-bf2d9fa015b0)
![image](https://github.com/user-attachments/assets/793a7f75-b99f-4e3b-abca-09be492b854a)
![image](https://github.com/user-attachments/assets/b0312ec6-9e52-48c8-b31e-9cae30e264fd)
![image](https://github.com/user-attachments/assets/aed2190d-2179-4f40-b403-d8c171e89d4d)
![image](https://github.com/user-attachments/assets/16e2d517-2108-4ab1-961d-0cfc2c7208d4)
![image](https://github.com/user-attachments/assets/07bcaa70-ef5d-4515-b371-d60baf83d04b)

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform:
- Browser name and version: 
- Operating system and version affected: iOS 18.1 iPhone 14 Pro
```

### Additional Information

I am unable to get my phone auth working,

**Comment by Alezanello** [comment]
Hello!

It looks like this issue may be related to how your project is configured in Firebase and your Apple Developer entitlements. I recommend checking out this StackOverflow discussion for potential solutions: [iOS requires reCAPTCHA every time with Firestore Auth in Flutter](https://stackoverflow.com/questions/60766258/ios-requires-recapcha-every-time-w-firestore-auth-flutter).

**Comment by JSkins** [comment]
Good work Seb! Is the triage still in process?

**Comment by arjusmoon860** [comment]
I am facing the same issue. Any luck in fixing it? @PrenSJ2

**Comment by PrenSJ2** [comment]
@arjusmoon860 I am still having an issue with this, please let me know if you figure It out

**Comment by Alezanello** [comment]
Hello everyone,

Although I haven’t been able to replicate the issue on my end, I encourage you to reach out to support via the in-app chat or by emailing **support@flutterflow.io**. They’ll be able to assist you further in resolving this issue.

Thank you for your patience and understanding!
