### ISSUE TITLE
Android Permission READ_MEDIA_IMAGES not directly related to app`s core purpose

### ISSUE THREAD

**Issue by Lars2024** [FlutterFlow/flutterflow-issues#4833]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Google Play gave me the feedback that the permission "READ_MEDIA_IMAGES" is not directly related to my app`s core purpose and that I should remove these permissions from all version codes. I appealed to this decision. Google Play however still decided on a policy violation.

I saw there is an issue #3867 which is similar to this issue but has the status closed without a solution being available. This is a show stopper for my recently published app because I can not start my marketing campaigns as planned with partners.
I would assume that this becomes a show stopper for all apps that need access to the FF image picker widget.

![Screenshot](https://github.com/user-attachments/assets/45f421f3-0707-4de5-a9ad-e7b09b7c427b)

### Expected Behavior

Flutterflow should provide a code base without the need for the Android permission "READ_MEDIA_IMAGES". If possible the Android photo picker should be used in the FF standard without the need for a board based permission to the image gallery or camera.

### Steps to Reproduce

I appealed to the Google Play team against the decision and received the following feedback:

Hi Lars,

Thanks for your patience.

Status: Latest app update available on Google Play with policy violations

We’ve reviewed your appeal request and found that your app Deine Lieblings-Weine (com.mycompany.lieblingsweine), has been conditionally approved but **is not compliant with Google Play’s Photo and Video Permissions policy. Please make sure your app is brought to compliance within the given timeframe emailed to you, or your app may face additional enforcement actions.**

Step 1: Review the policy violation with your app

We found that your app, (App Bundle Version: 22, Track: Production and App Bundle Version: 21, Track: Closed Testing) is not compliant with the [Details on Google Play's Photo and Video Permissions](https://support.google.com/googleplay/android-developer/answer/14115180?hl=en) policy, or we were unable to review and verify your in-app experience for compliance with this policy.

READ_MEDIA_IMAGES/READ_MEDIA_VIDEO is a restricted permission and apps must only declare this permission if their core functionality requires broad access to all photo or video files on the device. Apps that request this restricted permission are subject to review, and those that do not meet the acceptable use case criteria will be disallowed from publishing on Google Play.

We’ve reviewed your appeal request and found that your app does not qualify for use of READ_MEDIA_IMAGES/READ_MEDIA_VIDEO for the following reasons:

Permission use is not directly related to your app’s core purpose

We found that your app is not compliant with how the READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permissions are allowed to be used. Your app only requires one-time or infrequent access to media files on the device. Only apps with a core use case that require persistent access to photo and video files located in shared storage on devices are allowed to use photo and video permissions. Please see here for more [Details on Google Play's Photo and Video Permissions](https://support.google.com/googleplay/android-developer/answer/14115180?hl=en) policy requirements.
Next Step:

Please remove the use of READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permission from all version codes within the submission (includes both production and testing tracks), remove the permissions and use the [Android photo picker](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html).
For additional help, you can review the following resources:

[Photo and Video Permissions](https://support.google.com/googleplay/android-developer/answer/14115180?hl=en) policy
[Android Photo Picker](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html)
Please update your app to fix this issue. You may also want to double check that your app complies with all other [Developer Program Policies](https://play.google.com/about/developer-content-policy/).

Please resolve this issue within the timeframe displayed in Play Console.

Step 2: Submit a compliant update or remove permissions

Make the necessary updates to address the issue(s) identified above.
Double-check that your app is compliant with all other [Developer Program Policies](https://play.google.com/about/developer-content-policy/).
Sign in to your [Play Console](https://play.google.com/apps/publish/) and submit the update to your app.
Please make sure to deactivate any noncompliant APKs. To do this, you can create a new release and upload a compliant APK to each track containing the noncompliant APKs. Be sure to increment the APK version code and set the release to 100% rollout.
If you are located in the EU, you may have additional redress options. Learn more about those potential options in the [EU Out-of-Court Dispute Resolution Help Center](https://support.google.com/european-union-digital-services-act-redress-options/answer/13535501). Routing ID: ZLFS

Please let us know if you have any other questions. Thanks for working with us to fix the policy issue and for your continued support of Google Play.

Regards,
Fujiko
The Google Play Team

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not available

### Visual documentation

![Screenshot](https://github.com/user-attachments/assets/ac898217-a2e9-4a5d-975d-0cf07e4f413b)

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: Web
- Browser name and version: Apple Safari 17.6
- Operating system and version affected: macOS Sonoma 14.6.1
```

### Additional Information

I published my app for IOS and Android end of October and want to start marketing campaigns with partners to increase the user base and subscription numbers. With the risk of new releases being banned and even the app being delisted on the Google Play Store this endangers the success / monetisation of my app.

**Comment by Alezanello** [comment]
Hello!

This GitHub issue tracker is intended for bugs that can be replicated on a new, blank project. For assistance with this type of situation, please reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io).

Thank you!

**Comment by Lars2024** [comment]
Hi Alezanello,
why do you think that this issue can not be replicated on a new blank project? Just add an image picker widget similar to my app on a new project and you will encounter the same issue if you send it to Google Play for production approval. Therefore I think that this issue will affect thousands of flutter flow customers sooner or later. 

I am open for your arguments but closing as support requests seems very easy for you and does not solve the problem.

**Comment by Lars2024** [comment]
The issue relates to the use of an „upload media to Firebase“ action for Media Source „either camera or Gallery" like I did in my app. The upload media action is used to upload images of wine labels and wineries (see enclosed screenshot). 
![PastedGraphic-1](https://github.com/user-attachments/assets/ca8ed9c3-8470-413c-90f2-9ee9ac3a6c79)

**Comment by solkennedy** [comment]
Same issue. App is being rejected for the same reason. App also uses "upload to firebase" function.

**Comment by Lars2024** [comment]
Hi solkennedy,
the issue is still open with the flutter flow support. My contact at the FF support team is Steve who investigates the problem. You might want to reference Steve and myself when you contact support@flutterflow.io

**Comment by ssaikat074** [comment]
Is there any update on this? My app is still getting rejected..

**Comment by Lars2024** [comment]
The flutter flow support passed the issue to development last year. A new FF release solved the issue in Nov. 24. It works fine for me now with no policy violation issue from Google Play. Maybe you can check if you have the newest FF release. If yes download your code and the permission issue should be gone.

**Comment by solkennedy** [comment]
My app is also being rejected

**Comment by ssaikat074** [comment]
For me, it was the `open_filex` package that added those permissions during the build, even though they weren't listed in the `AndroidManifest.xml` file. So, I added the following code to the `AndroidManifest.xml` file, which solved the issue:

```
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" tools:node="remove"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" tools:node="remove"/>
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" tools:node="remove"/>
```

This code instructs the build system to exclude these permissions.

**Comment by Somaya23** [comment]
Did you ever find a solution to this issue? I am experiencing the same error, and image upload is an essential feature of my app.
