### ISSUE TITLE
Parameters selection bugs

### ISSUE THREAD

**Issue by zein1016** [FlutterFlow/flutterflow-issues#4834]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When there are multiple paramters in the action callback parameters, it is only taking the first one. The other ones are not being passing. so when i select let's say the 3rd option, it is taking the first option. 
<img width="705" alt="Screenshot 2024-11-05 at 13 27 21" src="https://github.com/user-attachments/assets/fb06deaf-df99-407d-8450-899bb8fddb1f">

### Expected Behavior

Pass the selected parameter 

### Steps to Reproduce

create a custom widget with 3 callback action parameters, try to pass the 2nd or 3rd option. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Column(   mainAxisSize: MainAxisSize.max,   children: [     Container(       width: MediaQuery.sizeOf(context).width,       height: MediaQuery.sizeOf(context).height * 1,       child: custom_widgets.CombinedMetricsAndCards(         width: MediaQuery.sizeOf(context).width,         height: MediaQuery.sizeOf(context).height * 1,         onMetricsTap: (id) async {           await showModalBottomSheet(             isScrollControlled: true,             backgroundColor: Colors.transparent,             enableDrag: false,             useSafeArea: true,             context: context,             builder: (context) {               return GestureDetector(                 onTap: () => FocusScope.of(context).unfocus(),                 child: Padding(                   padding: MediaQuery.viewInsetsOf(context),                   child: Container(                     height: MediaQuery.sizeOf(context).height * 0.8,                     child: LogtheweightDetailsWidget(),                   ),                 ),               );             },           ).then((value) => safeSetState(() {}));         },         onMetricsMoreTap: (id) async {           await showModalBottomSheet(             isScrollControlled: true,             backgroundColor: Colors.transparent,             enableDrag: false,             useSafeArea: true,             context: context,             builder: (context) {               return GestureDetector(                 onTap: () => FocusScope.of(context).unfocus(),                 child: Padding(                   padding: MediaQuery.viewInsetsOf(context),                   child: Container(                     height: MediaQuery.sizeOf(context).height * 0.8,                     child: NewWeightMetricsCardWidget(),                   ),                 ),               );             },           ).then((value) => safeSetState(() {}));         },         onCardTap: (id, title, cardType) async {           await showModalBottomSheet(             isScrollControlled: true,             backgroundColor: Colors.transparent,             enableDrag: false,             context: context,             builder: (context) {               return GestureDetector(                 onTap: () => FocusScope.of(context).unfocus(),                 child: Padding(                   padding: MediaQuery.viewInsetsOf(context),                   child: Container(                     height: MediaQuery.sizeOf(context).height * 0.8,                     child: ExerciselogsWidget(                       exerciseID: id,                     ),                   ),                 ),               );             },           ).then((value) => safeSetState(() {}));         },         onCardMoreTap: (id, title, cardType) async {           await showModalBottomSheet(             isScrollControlled: true,             backgroundColor: Colors.transparent,             enableDrag: false,             context: context,             builder: (context) {               return GestureDetector(                 onTap: () => FocusScope.of(context).unfocus(),                 child: Padding(                   padding: MediaQuery.viewInsetsOf(context),                   child: Container(                     height: MediaQuery.sizeOf(context).height * 0.8,                     child: CardActionSheetWidget(                       cardId: id,                       cardType: id,                     ),                   ),                 ),               );             },           ).then((value) => safeSetState(() {}));         },       ),     ),   ], )

### Visual documentation

<img width="705" alt="Screenshot 2024-11-05 at 13 27 21" src="https://github.com/user-attachments/assets/18cefd0d-0e2c-44ec-a672-f05d460ec6ed">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue on my end. Could you please generate a Bug Report Code from the widget where you're experiencing the problem? This will help us investigate further.

To generate the Bug Report Code, simply right-click on the widget and select the option from the menu.

Thank you! Let us know if you have any questions about this process.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/341bdbc3-157f-4a7a-8777-16200de9265d/6e50ea1f-3b1d-43e3-b0f4-79648af562bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNDFiZGJjMy0xNTdmLTRhN2EtODc3Ny0xNjIwMGRlOTI2NWQvNmU1MGVhMWYtM2IxZC00M2UzLWIwZjQtNzk2NDhhZjU2MmJkIiwiaWF0IjoxNzMwODMyMTUzLCJleHAiOjMzMzAxMzkyMTUzfQ.88J_igRXbepvrAgGrhHwLJyStU1rECqV2oBTd4991d0 " alt="image.png" width="1168" height="834" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
