### ISSUE TITLE
Chart Widget X and Y axis values are resetting 

### ISSUE THREAD

**Issue by turisouza** [FlutterFlow/flutterflow-issues#4835]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the Chart widget and I set the X-axis and Y-axis to the desired fields from an array of objects, the dropdowns for each axis reset to "unset" after a few seconds.

### Expected Behavior

I expected the Char's axis dropdowns to remember what I entered into them.

### Steps to Reproduce

Create a page.
Add a Chart widget to that page.
Set the X and Y axis dropdowns to values from a collection of objects.
Observe the dropdowns (after a short amount of time, they will reset to "unset").

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/HluIhgoeEG0bqJLMZAhR8kQ2InarsvhOpDTUoaF5SuE5kLbuvSXBFVcMOIewhmKGL9jXMGpMLQkoXPU/UrFzWEQ5Rf1rlxWzniQmOXMoSrBs60fmpSI9tjI0C/4Jmn2BVTJvJ2ZXMtig/GSw==

### Visual documentation

https://github.com/user-attachments/assets/4a399e0b-1aaa-4b52-8484-00d76533dad9

### Environment

```markdown
- FlutterFlow version: v5.0.8+ released October 30, 2024
- Platform: MacOS Laptop
- Browser name and version: Chrome 127.0.6533.89
- Operating system and version affected: macOS 14.5 (23F79)
```

### Additional Information

You closed this bug without resolving it (#3685, #3553), several users keep posting complaints and you are ignoring them. Please resolve this issue.

**Comment by Alezanello** [comment]
Hello!

I’m sorry you’re experiencing this issue. The good news is that our team is already tracking it internally. I’ll link this GitHub issue to our main internal report and close it as a duplicate to consolidate efforts on the primary thread.

Thank you for your patience, and please feel free to reach out if you have any further questions!
