### ISSUE TITLE
Build failed on test mode when use specific widget

### ISSUE THREAD

**Issue by Nathanael-Rayapin** [FlutterFlow/flutterflow-issues#4837]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is a very strange bug that appeared just last week. I can no longer build my application in test or run mode, every time I get an error related to either an “iconButton” widget or a “checkbox” widget.

![image](https://github.com/user-attachments/assets/20621561-5c91-4d27-abf7-43767f32f8fa)

Most of the pages with these widgets have not been modified and are also affected by this bug. 
No problems are detected before the build.

![image](https://github.com/user-attachments/assets/50c29c61-de25-4dff-9e6c-de49e1cf2ce9)

### Expected Behavior

I should be able to use the checkbox and iconButton widgets

### Steps to Reproduce

1. Create a page
2. Add the iconButton widget or checkbox widget
3. Build in run or test mode

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9WlWEvHGF6ba00ttx+bw4bJJCvOpYUec/6P1RCTsOndG9UJWCmp14E7t73i9j1FewnOTucb7451KVqbRbdeGKlWrGTF7maTkEnL9lnCEy85JmJsSUlNrFYV3gj3GeYHeuiVhPrNuPVDUQwSq/LZO4=

### Visual documentation

It's not a problem of space, nor of variable (I reproduce the crash with only the widget (iconButton or checkbox) and nothing else next to it, for example : 

```
GestureDetector(
  onTap: () => FocusScope.of(context).unfocus(),
  child: Scaffold(
    key: scaffoldKey,
    backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
    body: SafeArea(
      top: true,
      child: FlutterFlowIconButton(
        borderRadius: 8.0,
        buttonSize: 40.0,
        fillColor: FlutterFlowTheme.of(context).primary,
        icon: Icon(
          Icons.arrow_back,
          color: FlutterFlowTheme.of(context).info,
          size: 24.0,
        ),
        onPressed: () {
          print('IconButton pressed ...');
        },
      ),
    ),
  ),
)
```

![image](https://github.com/user-attachments/assets/308e59b6-cbf7-4079-b15d-87da603f143e)

### Environment

```markdown
- FlutterFlow version: v5.0.9+ released October 25, 2024
- Platform: Web and Desktop
- Browser name and version: Chrome 130.0.6723.70
- Operating system and version affected: Windows 10
```

### Additional Information

I tried to create a new project by copying and pasting the page containing the widget in question, but no build problems (if it were the case I would have very quickly found another topic on the problem I think). The problem seems to be related to my specific project, but I can't use this as an alternative because 1) I'd like to avoid having to configure everything and 2) using this option without knowing the cause means taking the risk of it happening again.

**Comment by Alezanello** [comment]
Hello!

I’ve been trying extensively to replicate the issue, but it appears to be specific to your project. If the problem persists on your end, please reach out to support through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) so they can assist you directly.

**Comment by Nathanael-Rayapin** [comment]
> Hello!
> 
> I’ve been trying extensively to replicate the issue, but it appears to be specific to your project. If the problem persists on your end, please reach out to support through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) so they can assist you directly.

Hello !  Thanks for your feedback 
Yes, it doesn't seem reproducible elsewhere (which is a good thing). I'll send a message to support :)

**Comment by wonderous957** [comment]
Hello! I've had the same issue. It's just started in the last couple of days. I've been using this project for months and the page in question hasn't changed for ages. It also fails on an IconButton. If I delete that IconButton it fails on the next IconButton in the project.

![image](https://github.com/user-attachments/assets/26973aea-7718-4e7b-9503-c5b693d8e09c)

**Comment by iTroca** [comment]
Estou tendo um problema similar.
Pediu pra remover iconButon, slider, checkbox e agora ratingBar!

Fui removendo um de cada vez e o problema muda de componente.

<img width="1792" alt="Captura de Tela 2024-11-08 às 13 43 32" src="https://github.com/user-attachments/assets/c59f17c9-e4ee-4a6e-8005-bad55768ea45">

**Comment by wonderous957** [comment]
I have somehow fixed it - I just reverted to a previous version. I'm pretty sure it had nothing to do with the icon button for me, i'd been playing with lots of custom actions.

**Comment by iTroca** [comment]
Não tenho como reverter, estou fazendo atualização do meu app.
Isso começou depois da ultima atualização do Flutterflow.

**Comment by Nathanael-Rayapin** [comment]
Problem solved for me !
The problem came from a missing Data Type in my configuration that was used by other components, but this missing data type was not caught by FlutterFlow (I don't explain why it was a widget error that was raised instead).
