### ISSUE TITLE
Error: The caller does not have permission to execute the specified operation. when updating project deps

### ISSUE THREAD

**Issue by hcw2016** [FlutterFlow/flutterflow-issues#4838]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am getting the following error: 

`Error: The caller does not have permission to execute the specified operation.`

whenever I try to add dependencies in Flutterflow Mac application. 

I am running on an M3 Apple Macbook Pro. Flutterflow version is up to date 

### Expected Behavior

I expect to be able to add dependencies 

### Steps to Reproduce

1. Navigate to Project Dependencies
2. Attempt to add a package 
3. Observe Error: The caller does not have permission to execute the specified operation.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: Version 5.0.9 (5.0.9)
- Platform: MacOS
- Browser name and version: Desktop Application
- Operating system and version affected: MacOS 14.3
```

**Comment by Alezanello** [comment]
Hello!

In Project Dependencies, you can only add FlutterFlow projects that are published as libraries. If you would like to add a specific package, such as one from pub.dev, please use the Custom Code section to integrate it.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by hcw2016** [comment]
Hello. Can we please not close this after 2 days of inactivity? I am aware to use packages from pub dev. However, when I attempt to add them in the Project Dependencies I get the error message above. 

I saw several reports of this in the past, but it appears that there was no resolution

**Comment by Alezanello** [comment]
Hello!!<br><br>Like I said in my previous response "If you would like to add a specific package, such as one from pub.dev, please use the Custom Code section to integrate it." the Project Dependencies can ONLY allow FF Projects as Packages
