### ISSUE TITLE
FlutterFlow UI builder shows grey app screen

### ISSUE THREAD

**Issue by AmeedGhouri** [FlutterFlow/flutterflow-issues#4840]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The FlutterFlow UI builder shows grey app screen, also the properties panel gets grey.

### Expected Behavior

It shows proper UI buider and properties panel.

### Steps to Reproduce

No Steps to reporduce, it happens suddenly and unexpectedly.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40h8n236l4nOlC47n9KMdFuDsROXo8a5EzpNtRaCosfZT2BLMcec/RVERDQtTnT3xqOWGar2oW09LvhoXyV/cBEyytc4Bh+KtyeAnLRmqXMK2VFJWgPXcmHZhhI32B0LaZ2x5BJtt2SCEa62emBOmQaArbHuPMPm48D6/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/333a640f-be43-47b7-9966-271d356fe062)

### Environment

```markdown
- FlutterFlow version: v5.0.8+ released October 31, 2024
- Platform: Web
- Browser name and version: Chrome 129.0.6668.90 
- Operating system and version affected: Windows 10
```

**Comment by TimothyWCTI** [comment]
I have had this happen before as well, and was not able to figure out how to reproduce it. 
I also had something similar where the whole page went grey.
I had to refresh the page to fix it.

**Comment by Alezanello** [comment]
Hello!

I accessed your project and did not encounter any issues. Did you take any specific actions before the grey screen appeared that might help us replicate the issue? Is it still occurring at certain times? If it happens again, could you please try recording the moment it triggers and explain what you did leading up to it? This would help us better understand and resolve the problem.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
