### ISSUE TITLE
API call not found in API configuration

### ISSUE THREAD

**Issue by Uamee** [FlutterFlow/flutterflow-issues#4841]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/f5ba884a-c46a-4243-b24b-4cc49aa913c5)
API call not found in API configuration error.

![image](https://github.com/user-attachments/assets/c63a04c7-feba-4a7b-8a02-d7eefc9835a8)

But the api call surely exists:

![image](https://github.com/user-attachments/assets/2deab77a-61a0-4a77-b69d-b13f9ba34831)

### Expected Behavior

Is expected that this error do not apear:

![image](https://github.com/user-attachments/assets/b1d2da74-93af-478b-b6dc-6f580d5ef293)

### Steps to Reproduce

1. create a on page load action
2. add an api call

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

![image](https://github.com/user-attachments/assets/f5ba884a-c46a-4243-b24b-4cc49aa913c5)

![image](https://github.com/user-attachments/assets/c63a04c7-feba-4a7b-8a02-d7eefc9835a8)

![image](https://github.com/user-attachments/assets/2deab77a-61a0-4a77-b69d-b13f9ba34831)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Windows desktop
- Browser name and version: Arc browser (latest)
- Operating system and version affected: Windows (latest)
```

### Additional Information

This project has a short deadline and that error is an impediment

**Comment by Alezanello** [comment]
Hello,

Thank you for reaching out!

To help us take a closer look at your project, we kindly request that you share a Bug Report Code. This can even be generated from the Widget Tree. Once we have the code, we can better investigate why this issue is occurring.

I attempted to replicate the issue in a new blank project but was unsuccessful. Your Bug Report Code will help us understand and resolve this more effectively.

Looking forward to your response!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
