### ISSUE TITLE
Code Expression setting in actions broken

### ISSUE THREAD

**Issue by Rishay97** [FlutterFlow/flutterflow-issues#4842]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I am setting a value and I click ‘Code Expression’, i define my variables and type the code, for example list..add(user)
And click confirm. All is fine, But after running the code, the code expression disappears and is actually blank when I go back to look at the action flow. It might have something do do with me referencing a supabase row query, because I’ve noticed that this happens when I am using supabase.

![IMG_4959](https://github.com/user-attachments/assets/e374f551-87c8-460a-8357-3c105169b638)

### Expected Behavior

my code expression value should not be blank after adding it in. It should remain.

### Steps to Reproduce

Have a supabase row, query the row in the page.
Click on a button to bring up action flow
Set the action to ‘update supabase row’
And filter to select the relavent row,
Under value: select code expression
In code expression: set variable 1 to be a list string that is from the supabase row
Set variable 2 to be another string
Set the code expression to be var1..add(var2)
And save the custom code. It should save (sometimes it doesnt)
But after running the code, the code expression dissappears.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Test 

### Visual documentation

test

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I attempted to replicate the issue, but I'm unable to save the code expression. There might be something I'm overlooking.

Here are the steps I followed:

1. Create a new project.
2. Add Supabase to the project.
3. Query a Supabase row.
4. Create an action to update the row.
5. In the field for the list of strings in the row, set it to add a value.
6. For the value, create a code expression that expects two variables:
   * 6.1: A list of strings, representing the queried row.
   * 6.2: A string to add to that list.
7. In the code expression, use: `var1..add(var2)`

However, I'm unable to save this configuration. Could you share a short recording via Loom or another tool to show exactly how you're managing to save it? This would help me better understand and assist further.

Thank you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
