### ISSUE TITLE
Remove from list leaves a an empty string instead of deleting field

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#4843]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For example:
 - updating a page state variable that is List <Image Path>
 - Remove from list action deletes the string but leaves a blank / empty string in firestore like so: ""
 

### Expected Behavior

It should delete the entire field

### Steps to Reproduce

- Create a page state and set it to List <Image Path>
- Upload Image via firebase via a button
- Update page state action & add to the list "Uploaded File URL"
- Select the state & select the remove from list action "Uploaded File URL"
- Check Firestore

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShfLl05dgotdc7ofQLflAhQMkQzM6bZI7ku1EdwEhfLHnPIkuPM7sUBNLYtTneGx9elKYozse0s75iN7LE/A3HymeG754zYRXQQmUd3yhMa6LPJCoWnR7O8RhClyY1rWG2wlBLsR1S1IQwDuQf/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/d52831fa-4d01-4b33-9818-a34f256b6a86)

### Environment

```markdown
FlutterFlow v5.0.9+ released October 25, 2024
Flutter version is 3.24.2
```

### Additional Information

I'm not sure if this is specific to only image path list or to all kinds of lists

**Comment by Alezanello** [comment]
Hello!

I’ve been trying to replicate the issue, and it appears that the list does not leave any blank or empty strings when an item is removed. This suggests that the issue might be related to the "rebuild" type configuration in your project, potentially causing data to be saved or sent to Firebase incorrectly.

To help clarify, I’ve attached a video below that demonstrates the behavior of the list on my end.

I hope this helps! Please let me know if you have any questions or need further assistance.

[Screen-Recording (37).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e3a6a4e9-4423-4142-a20d-e20306d8f856/40c462df-c5a6-406a-8bcf-614fb14e5062?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lM2E2YTRlOS00NDIzLTQxNDItYTIwZC1lMjAzMDZkOGY4NTYvNDBjNDYyZGYtYzVhNi00MDZhLThiY2YtNjE0ZmIxNGU1MDYyIiwiaWF0IjoxNzMwOTkxOTA1LCJleHAiOjMzMzAxNTUxOTA1fQ.UQZ30e-HjPr03zy6bhyt98mgTcQhjF1VG_bLuk7jXsU)

**Comment by alih552** [comment]
@Alezanello thanks for the video, I will re-test & get back to you.
Note: rebuild is set to no rebuild
![image](https://github.com/user-attachments/assets/faf420e7-c232-47b1-ad0f-997b2d4f0d1f)

**Comment by Alezanello** [comment]
Hello Alih, is this has been solved by the steps I gave you?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
