### ISSUE TITLE
Initial Value for Radio Group in Component not working

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#485]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
I can pass value to Component parameter and set the Radio Button's initial value from that Component Parameter

## Current behavior (required)
I cannot pass value to Component parameter and set the Radio Button's initial value from that Component Parameter. It ignores that Component parameter and initial value is not set.

## To Reproduce (required)

kindly see the test project i created for yall

### Bug Report Code (required, generate by right clicking inside Widget Tree and clickig "Get Bug Report Code")

ITwej8nf5c9NoctD+KXiccFKmjw5JlA5arxMm9Z+cwgbNuv3OoYUP8+kM1hAXemnYmxcMFqWrGcz/anKvof2FsddaASuGYB+wYQJSxXjWmeRRrWxGpaWekd5J8NjGhGa5p/Z2QpBBO91ZXw91FmtGuuUdD3qCb7HCkUdRvj8KpnLnVaXLR/jLCBW/GNecCfn

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Thanks @Zack1010OP  for posting this issue. I can re-produce the issues. There is an existing issue around radio button initial value assign from variables. Team is working on it. it should be fixed in next updates. No worries. 

This is related to #2 

Thanks

**Comment by Zack1010OP** [comment]
Thanks Hari for all your help and hard work! Hope to make Flutterflow an even more wonderful app together!!Warmest regards,IsaacOn 14 Feb 2023, at 10:19 PM, Hari ***@***.***> wrote:﻿
Thanks @Zack1010OP  for posting this issue. I can re-produce the issues. There is an existing issue around radio button initial value assign from variables. Team is working on it. it should be fixed in next updates. No worries.
This is related to #2
Thanks

**Comment by victoriahuang1** [comment]
Hi @Zack1010OP , I have found and fixed a bug on our end. The fix should go out with the next deploy!

**Comment by Zack1010OP** [comment]
Woo!!! Thanks Victoria!!! Warmest regards,IsaacOn 17 Feb 2023, at 1:28 AM, Victoria Huang ***@***.***> wrote:﻿
Hi @Zack1010OP , I have found and fixed a bug on our end. The fix should go out with the next deploy!
