### ISSUE TITLE
Firebase Performance Monitoring simply not working

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#4850]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Enabled "Firebase Performance Monitoring" in the settings for my Web project. But no requests are being sent to firebaselogging.googleapis.com

### Expected Behavior

When I visit the published website, it needs to send performance monitoring requests to firebaselogging.googleapis.com

### Steps to Reproduce

1. Enable Performance Monitoring
2. Publish
3. Visit the website
4. Check for request to firebaselogging.googleapis.com

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzPHq24VIscsA14SJc+0w9TgROUccTIMziNZ+exUbfaL1BuwMfuD8UBdBcOmgaVNcfU2KnjgE/tXFj9/tO8c4NgWrY65Z/rtQbhXke2igbpSvDIe0RHFDL91RfH6j18CC2hYmIu1fciUEwDiAIeSUShHDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/62d10f9b-04d5-4845-9eda-334dd45a1802">
<img width="581" alt="image" src="https://github.com/user-attachments/assets/28afc35a-b201-42e0-9667-9ed267104d0c">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.9 released October 25, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome Version 130.0.6723.117 (Official Build) (arm64)
- Operating system and version affected: MacOS 15.0.1 (24A348)
```

### Additional Information

Other people having same issue since over a year:

https://community.flutterflow.io/integrations/post/how-to-add-firebase-performance-monitoring-resolved-2X8NYzlgmKwrFig

**Comment by Alezanello** [comment]
Hello!<br><br>Thank you for bringing this to our attention! I can confirm that the Firebase Performance package is correctly installed, but it appears it is not being executed as expected. I’ll escalate this to the engineering team so they can work on a fix.

Thank you again for highlighting this!

**Comment by Alezanello** [comment]
Hello!

Sorry for the delayed response. Did the latest Flutterflow updates resolve the issue for you?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
