### ISSUE TITLE
Could not generate launcher icons

### ISSUE THREAD

**Issue by hcw2016** [FlutterFlow/flutterflow-issues#4852]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am attempting to deploy my FF application to the IOS App Store (not Google Play Store for now). When I click "deploy" in FF (using Mac desktop application), I get an error indicating that launcher icons could not be generated. Specifically, the "Creating default icons for Android" is failing on Script step 9 

### Expected Behavior

I would expect that since I am only deploying to the App Store on iOS that there is no Android references in failed build output. 

### Steps to Reproduce

1. Go to Mobile Deployment in FF
2. Attempt to deploy to App Store (iOS) 
3. Observe the following stacktrace 

```
<body style="background-color:#14161C">
<style>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}
</style>
<h4>Failed Step: Generate Launch Icon</h4>
<div style="white-space: pre-wrap;line-height: 1.5">
════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android

✕ Could not generate launcher icons
RangeError (index): Index out of range: index should be less than 666240: 666240


Build failed :|
Step 9 script `Generate Launch Icon` exited with status code 2
</div>
</body>
```

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Mobile Deployment

### Visual documentation

<body style="background-color:#14161C">
<style>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}
</style>
<h4>Failed Step: Generate Launch Icon</h4>
<div style="white-space: pre-wrap;line-height: 1.5">
════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android

✕ Could not generate launcher icons
RangeError (index): Index out of range: index should be less than 666240: 666240

Build failed :|
Step 9 script `Generate Launch Icon` exited with status code 2
</div>
</body>

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.9 released October 25, 2024
Flutter version is 3.24.2
- Platform: MacOS Desktop
- Browser name and version: Sanoma 
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!<br><br>Thank you for reaching out!

I wasn't able to replicate the issue, either from a new blank project or your specific project when compiling locally. Since we don't have the necessary permissions to deploy your project directly to CodeMagic, this appears to be a project-specific issue.

Could you please reach out to our support team via in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io)? They will be able to closely investigate the situation and work towards a resolution.

Thank you for your understanding!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
