### ISSUE TITLE
Several push notification errors including Unknown error on sending.

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#4860]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have two databases set up one for production and one for development and they both show the same issues. Quite simply we can configure the push notifications without issue, but when it comes to actually sending a push notification we get a send error. See image. This however was preceded by some very unexpected behavior, which was that when it was working, which was only forty-eight hours ago, I discovered that sending a push notification would alter the permissions of the entire database so that, for instance, images would stop showing on the application. I would have to redeploy the firebase permissions before the images would return, and then if I sent another push notification,  the permissions for it again be altered. However today having deactivated push notifications and reactivated them in one project, I now get an unknown error. If I return to the other database where I made no changes I get the same unknown push notifications error.

Looking at the console logs to determine what might be causing this, it appears that the error reported has something to do with firebase rules which is managed by Alex@Flutterflow.io. See the image below for that log. This indicates to me that we are genuinely talking about some kind of permissions issue, although at first I thought that that seemed improbable, all the indications are that that symptom could indeed be the root cause of the issue.

### Expected Behavior

There would be no errors and push notifications would be received. 

### Steps to Reproduce

Go to settings and push notifications and attempt to send a push notification.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7YMS8+kMxJVXemndGNEL2H8/WI0/tqJudmXA+UoHyytRaJcwZBUawrKIXm5acmWEKmOPGtRL+NJJVyw34m3rRRCIfpfSl4a1Dque+TJYz3tGL7MIkUeDcj+Jp3XnGOqQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/user-attachments/assets/76b0d01d-65a1-428f-88e9-3d92df2bdedf)
![image](https://github.com/user-attachments/assets/a82edeb3-2f04-408d-866d-0b1ac373adc9)
![image](https://github.com/user-attachments/assets/90b07744-74c2-4626-af76-8079b0f89878)

### Environment

```markdown
- FlutterFlow version: Lates
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: NA
```

### Additional Information

The bug report code provided points to a place where we use push notifications comment but it is not where the error occurs. It is not possible to get  a bug report code if we are in the setting section where the bug is apparent.

**Comment by Alezanello** [comment]
Hello!<br><br>Thank you for reaching out!

I was unable to replicate this issue on a new blank project, which suggests it may be specific to your project. Could you please reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io)? They will be able to investigate the specific details of your project and help resolve the issue.

Thank you for your understanding!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
