### ISSUE TITLE
Issue with VSCode extension

### ISSUE THREAD

**Issue by ggillon** [FlutterFlow/flutterflow-issues#4861]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to update a custom action I consistantly get the error message that the function cannot be found "Custom Function xxx not found in project". I don't get any issues with customer code.

### Expected Behavior

I would expect it to work 

### Steps to Reproduce

1. Create a custom action
2. Download code and pull in vs code
3. Edit function code
4. try to push update

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Visual documentation

not available

### Environment

```markdown
- FlutterFlow version: 5
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello!<br><br>Could you please share a recorded video showing the steps you take to make this push, or provide a snippet of the code so we can check for any potential issues?

Have you also tried pushing with a simple code snippet to confirm whether the extension allows the push? This could help determine if the issue lies within the entire code or something more specific.

Thank you!

**Comment by AlexP-cyber** [comment]
reproduces for me as well . FlutterFlow v5.0.12 , VS 1.95.3

I download FF code -> start code editing session-> make an update in custom function -> push to flutterflow.
and it says : custom FUNCTION (not ACTION) 'my custom action name' not found in project.
I open FF and looking for changes - nothing were applied,
Sometimes after a few manipulation to pull and push I receive successful sync but in FF there are only new strange dependancies looking at me and that's it. 

As for code I'm trying to change :  just replacing this line with 'null' . 

![122](https://github.com/user-attachments/assets/981dc564-e4e5-4ffa-b73c-421022924210)

![1333](https://github.com/user-attachments/assets/62202435-1de2-4e0c-8952-8a0f069ea0de)

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by AlexP-cyber** [comment]
Hi, still actual for me on FlutterFlow v5.0.12

**Comment by Alezanello** [comment]
Hello again, and apologies for the delayed response! I just tried the exact same steps you mentioned, and everything worked perfectly on my end. Would it be possible for you to record a short video (like with Loom or a similar tool) showing the steps you're taking? This would help us identify if there’s something we might be missing to replicate the issue. Thank you!

**Comment by AlexP-cyber** [comment]
sure, here it is : https://www.loom.com/share/85c75e0cb02a447abca212d76d86f8ba

**Comment by Alezanello** [comment]
Hello again, and apologies for the delayed response!

While I wasn’t able to replicate the issue you’re experiencing, we have confirmed a related bug where, in some cases, the code is successfully uploaded but doesn’t result in any changes on the FlutterFlow side. This might be connected to your issue.

To streamline the process, I’ll close this ticket as a duplicate so we can focus all VS Code extension-related issues under a single thread. I’ve linked this ticket internally to the main issue to ensure the team has visibility into both cases and can work towards a unified solution.

You can track progress on the main issue here:<br>[GitHub Issue #4050](https://github.com/FlutterFlow/flutterflow-issues/issues/4050)

Thank you for your understanding and patience!

[Screen-Recording (60).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/48a1b088-cc90-4039-b24b-618d663077e7/e53b35a9-c9ba-4d57-96c1-5779bc9d77b8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80OGExYjA4OC1jYzkwLTQwMzktYjI0Yi02MThkNjYzMDc3ZTcvZTUzYjM1YTktYzliYS00ZDU3LTk2YzEtNTc3OWJjOWQ3N2I4IiwiaWF0IjoxNzMzNDI0NDExLCJleHAiOjMzMzAzOTg0NDExfQ.k73w04jJjr45fiarybc6OcR0m8H7s3jQbGCDNdV6R20)
