### ISSUE TITLE
Items on the listview do not hold state when exiting the screen

### ISSUE THREAD

**Issue by corsaro0** [FlutterFlow/flutterflow-issues#4863]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the video you can see that I like the first post.

When I scroll down and come back up, the like is no longer there.

If you refresh the page, the like is correctly inserted.

Before the flutterflow update this problem didn't exist and I didn't make any changes.

### Expected Behavior

I expect that when I like, if I scroll down and go back up again, the like will maintain its status and remain marked.

I want to point out that before the flutterflow update this problem was not present.

### Steps to Reproduce

1. Create a infinite scroll listview with API CALL
2. Insert a toggle item
3. Change the state of the toggle
4. Scroll down and go back up again.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl8nf5ZZ1rsNc+KX1K/pvr2QQI0McWOdEl+tuZwgbIoznBuwuYuCkfkhBQt+5aVNce078vFg0/6Hwid7pDvUnOTCabI86+LhUUjnke2i6Mpi6BYewQXNAI/lhfEym1KuvowpCGPpvSUJk12euHvO9XnLDIuu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/c6293bcc-382f-4f05-8d29-06af932f12f2

### Environment

```markdown
- FlutterFlow version: v5.0.8+ released October 30, 2024
Flutter version is 3.24.2
- Platform: WEB
- Browser name and version: CHROME Version 130.0.6723.117 (64 bit)
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!

I’ve reviewed your project and identified two issues:

1. There are private cloud functions that have not been deployed.
2. The Like button references a component named "LikeButtonCommunityPost," which does not exist in your project. This is why the area appears grayed out. After searching through the project components and pages, I couldn’t locate a component by that name, so I’m unable to review its logic.

On our end, there haven’t been any changes to how information is retrieved via API calls. However, I recommend checking if you have “Cache API Result” enabled on the API call you were testing, as it may affect the results.

I hope this helps clarify things!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
