### ISSUE TITLE
Animation with mouseRegion action trigger- active ticker dispose error

### ISSUE THREAD

**Issue by Jaspie88** [FlutterFlow/flutterflow-issues#4864]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a classic desktop dashboard page with a sideNav component. The navlinks in the sideNav  are comprised of these widgets in descendant order:
MouseRegion
Container
Row
Icon
Text

When MouseRegion hovered it triggers a scale animation on the container, off-hover reverses the animation. The container on click navigates to another page. Both the animation and the navigation work great until clicking to navigate again, on the next page navigation is when the console receives an exception:

'Tickers used by AnimationControllers '
'should be disposed by calling dispose() on the AnimationController itself. '
'Otherwise, the ticker will leak.',

 

### Expected Behavior

Ability to use a NavBar animated links with no dispose errors when navigating between pages in the app.

### Steps to Reproduce

1. Add two pages
2. Create component with two containers with text children.
3. set on trigger animations on both containers. Scale is what I chose. 
4. Wrap each in a MouseRegion and set on and off hover actions to trigger animation on the containers.
5. Set onclick action to the container to navigate between pages. Replace route option.
6. Run app and try navigating a few times between pages with the device logs open.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol8nl5ZFOj7xK1aqJbsFFmSQUQ2J+RoEzjspBazwbfe+uB4kqevfOTERDXfW6YG9cOU2gp2oW063wvePXD+0EAEyVR74/+LtqdRWWeEK5b7KtFJWgPHNSAfNTGnLF5rW3ohJ7Ou1odXge70+LNuiXXivDQoSxPHoSDa/LZO4=

### Visual documentation

![FF Animation dispose error](https://github.com/user-attachments/assets/53568a48-cfb1-42b1-b779-416bd80299d0)

### Environment

```markdown
- FlutterFlow version: 5.0.9+
- Platform: Web, Windows
- Browser name and version: Chrome 130.0.6723.117 (Official Build) (64-bit)
- Operating system and version affected: Win 11
```

### Additional Information

Trying to have a classic scale effect  on mouse hover but the state management of the animation won't allow multipage navigation without filling the console with exceptions.

**Comment by Alezanello** [comment]
Hello!

Have you tried adding a "Stop Animation" action before the "Navigate To" step, similar to how you would handle an off-hover event? This way, when you click, the animation stops just before navigation, and this should prevent any errors from occurring.

**Comment by Jaspie88** [comment]
> Hello!
> 
> Have you tried adding a "Stop Animation" action before the "Navigate To" step, similar to how you would handle an off-hover event? This way, when you click, the animation stops just before navigation, and this should prevent any errors from occurring.

I've tried stop action but still after second navigate press the active ticker dispose errors roll in.

**Comment by Alezanello** [comment]
You could try adding a small **Wait** action (around 200ms) after the **Stop Animation** and before the **Navigate To** action. This slight delay can help ensure everything processes smoothly
