### ISSUE TITLE
APK downloaded crashing fron Flutter flow

### ISSUE THREAD

**Issue by UasDevelope** [FlutterFlow/flutterflow-issues#4865]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Project ID: travel-app-1ep5i7
Project Name: KatastarPRO

I'm facing an issue with the Google Map polygon on the map screen. I’ve identified the problem as being related to the map configuration in the AndroidManifest.xml file, which I have fixed after downloading the code. However, when I run the app in FlutterFlow, the polygon works, but when I download the APK, the app crashes. The issue seems to be related to the configuration, even though the Google Map setup has been completed. Please help me resolve this. Thanks!

### Expected Behavior

Needed to work after the download the of the apk file from the flutter flow
https://app.flutterflow.io/project/travel-app-1ep5i7?tab=pageSelector&page=GoogleMapScreen
this is the screen on the flutter flow is working but when. I downloaded the APK this screen is crashing.!

### Steps to Reproduce

https://app.flutterflow.io/project/travel-app-1ep5i7?tab=pageSelector&page=GoogleMapScreen
this is the screen on the flutter flow is working but when. I downloaded the APK this screen is crashing.!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

PolyGon Screen or customwidget code

### Visual documentation

https://app.flutterflow.io/project/travel-app-1ep5i7?tab=pageSelector&page=GoogleMapScreen
this is the screen on the flutter flow is working but when. I downloaded the APK this screen is crashing.!

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: 
Andriod APK
Latest Version
```

### Additional Information

https://app.flutterflow.io/project/travel-app-1ep5i7?tab=pageSelector&page=GoogleMapScreen
this is the screen on the flutter flow is working but when. I downloaded the APK this screen is crashing.!

**Comment by Alezanello** [comment]
Hello!

Do you have any logs that you could share from running the app locally? This would help us understand why this event is occurring and assist in identifying the issue more effectively.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
