### ISSUE TITLE
Page titles not working properly

### ISSUE THREAD

**Issue by Delazeri** [FlutterFlow/flutterflow-issues#4866]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I access certain sections of the platform, such as the “Times” section, the title of the browser tab takes a while to update or is only updated after an interaction with the page, such as clicking on an element. For example, on the screen where the tab should display the title “E-Hub Platform - Times”, the browser displays the title of the previous tab, such as “E-Hub Platform - List of operations”.

### Expected Behavior

When I visit the pages, the tab title should change

### Steps to Reproduce

1. Add page title
2. Navigate between pages

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fk8nf7Y9Om9tc15DUbPl7/T8RJkM7apIFiutuew4aIurqPKQIYcnSRE5JYsOGdwlIJFmj8XgK0qGJhoaSGOwrB0mBU4NewZF9WjnNeFGVabbQDaWKSnNBGftVGnWO56SSmA9QXex1LXg562GmC+qXYB/DGKb1CzMFRv+iUbn4+WikLgDoVjpFxmNecCfn

### Visual documentation

https://github.com/user-attachments/assets/65fdd879-a36c-4c6f-b7ae-d9513d978b70

<img width="225" alt="Captura de tela 2024-11-11 101909" src="https://github.com/user-attachments/assets/87e8dc08-038d-4d00-acd9-7562443c02fb">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 30, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome Version 130.0.6723.116 (Official Build) (arm64)
- Operating system and version affected: Windows 10 Pro
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue on my end. To help you test further, I've shared a public project at the end of this message that you can clone and experiment with. Additionally, I've provided the URL used for testing so you can see that no additional clicks were made other than navigating to the page.

Public Project: [https://app.flutterflow.io/project/qa-3011-oscn37](https://app.flutterflow.io/project/qa-3011-oscn37)<br>Testing URL: [https://testingroute.flutterflow.app/](https://testingroute.flutterflow.app/)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0b0b80af-e49e-47ff-a098-2b777c83e045/4a21c26f-6e91-48f6-bd12-b6ff71797ae5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYjBiODBhZi1lNDllLTQ3ZmYtYTA5OC0yYjc3N2M4M2UwNDUvNGEyMWMyNmYtNmU5MS00OGY2LWJkMTItYjZmZjcxNzk3YWU1IiwiaWF0IjoxNzMxMzU3ODE3LCJleHAiOjMzMzAxOTE3ODE3fQ.6PXu--qDtcEkzPkT-4uZiWbGRlaNwdJWsQ3jLwQxOUM " alt="navigation.gif" width="1903" height="948" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
