### ISSUE TITLE
No red errors in project that cause a build to fail, but build fails without giving any error message

### ISSUE THREAD

**Issue by dimamuzei** [FlutterFlow/flutterflow-issues#4867]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have no errors showing on my project, but I can't download the code, or test the project.

### Expected Behavior

The build should run 

### Steps to Reproduce

Click Test run, Project fails.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEei8/q+ZNNpbxe+7XQbflFowMxGmY7UIIZjtcbUkwaIZvnB+02eur+VHtuZ7yregtqAFH88Ug0/+DHjc7LGu44YU6CaINo+aVcUTvMeGCuR5jUPLu8SXJSMNxXI3K/17bQsBNSNtdpcU1gw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![issue2](https://github.com/user-attachments/assets/88c2dead-31f9-4a82-81fe-a022b3ff37a0)
I am unable to download the code as well.

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Web
- Browser name and version: Chrome Latest
- Operating system and version affected: Windows 10
```

### Additional Information

I need to continue this project. Its very important to me and my well being

**Comment by Alezanello** [comment]
Hello!

I hope you're doing well. I was able to successfully download the code from your project using both the FlutterFlow CLI and the .zip option. Are you still experiencing this issue? If so, please let me know, and I'll be happy to assist further!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7207f9c4-710b-4d34-9315-c7063a347f5b/fd98fee3-8a46-41f6-bb61-6aeda8d54fc5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MjA3ZjljNC03MTBiLTRkMzQtOTMxNS1jNzA2M2EzNDdmNWIvZmQ5OGZlZTMtOGE0Ni00MWY2LWJiNjEtNmFlZGE4ZDU0ZmM1IiwiaWF0IjoxNzMxMzU3MTM0LCJleHAiOjMzMzAxOTE3MTM0fQ.8EBz_odSjViFnUx2SYmn--flr4XXyVHNOO9FIQHLgfs " alt="image.png" width="484" height="97" />

**Comment by corsaro0** [comment]
I also have the same problem. Sometimes the test mode stops even if it is already active and build failed appears
