### ISSUE TITLE
List not showing items properly on navigating back and forth

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#487]
## Expected behavior (required)

I have a listview in a tab bar that shows a list of tasks and on clicking a task the app navigates to the task details page. But when I navigate back from the Task details page I notice that the list loads items again and sometimes it is stuck with showing only a few items instead of all items. On refreshing/loading the page containing the list again the list is loaded normally.
This issue is also present on most pages having a single list on the page without any tabbar. 
Other related issues are:
1) When clicking on a list item the list seems to reload for a very brief time which leads to bad UX.
2) This issue is also there on opening a bottom sheet and closing it.

## Current behavior (required)

Pages and bottom sheets should load and exit normally with any reloads.

## To Reproduce (required)

1. Create a page and add a list to it.
2. Add backend query to fetch list of items from firebase.
3. add navigation action on tapping a list item.
4. notice unwanted reloads on tapping items.

## Context (required)

BAd UX. Not sure if this issue costs more reads.

## Screenshots / recordings

Before navigating to Task details page:
<img width="1285" alt="Screenshot 2023-02-14 at 3 03 55 PM" src="https://user-images.githubusercontent.com/102008213/218698322-2c51a9e4-9809-463b-b048-154ba63337b5.png">

After navigating back from Task details page:
<img width="1281" alt="Screenshot 2023-02-14 at 3 03 45 PM" src="https://user-images.githubusercontent.com/102008213/218698295-50b8bd82-64b8-4c08-a256-2cda713a4874.png">

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: On all browsers

* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Hi @Shubham-VE - Thanks for posting this issue. Can you please share bug report code. So that we can see whats happening in your project. If you could share a quick video of these issues that would be great. Thanks

**Comment by Shubham-VE** [comment]
Bug Report:
IT40z/Hqx89gocNf7aXpbfpajic5KVgjbY0nlutRaCosfZT2BLMcec/RVERoOdzjS3NUe0yWgWoW097GiPPxJPQpBzGeGKZ9zs9uVDrgIV2jRJSrU/HUACkbeacOQSj6

https://user-images.githubusercontent.com/102008213/218945923-c600cc48-797e-4cb6-92f2-22273d4815b3.mov

In the video you can see that how the list loads again whenever I navigate back and sometimes the list is stuck showing only a few items which I could not capture as it is rare and random behavior.

https://user-images.githubusercontent.com/102008213/218947291-036d08e3-9b1a-4c40-8611-357138dbe7a5.mov

The list in above video is in other page which also has some items missing when navigating back form other page. This list is reversed with enable infinite scroll with a page size of 20.

My questions:

1. Why are they reloading when we are just navigating back?
2. Will this cost me read queries every time there is a setState/list reloads? If yes, then I don't want extra cost just for navigating back from a page.
3. The reload is not done properly as there are items missing. How to resolve this?

**Comment by Shubham-VE** [comment]
Another list-related issue I found.

https://user-images.githubusercontent.com/102008213/222417455-805d4676-a8be-413a-b984-8bad2da42a9e.mov

Issue Explanation:
I have created a custom chat with a checkbox option that updates the "isDone" field in the Activity collection. As visible in the video, whenever I click the check box the list is scrolled down to the bottom which is one of the issues. The other issue is the bad UX of rebuilding the chats list like the above lists issues.

**Comment by Shubham-VE** [comment]
Hi, @hariprasadms @katherineqian.
I tested with lasted build of my project on 14 April. Point 2 of the issue has been resolved and now the list doesn't reload when the bottom sheet is opened on the page. But point 1 of the issue still persists, i.e, the page queries still reloads on navigation.

**Comment by Shubham-VE** [comment]
> Hi @Shubham-VE,
> 
> Apologies for the delay. This appears to be a duplicate of #520 - note how both of these issues are appearing on navigation between pages with paged infinite scrolls. Was "Listen for Changes" enabled on the queries that were causing issues?

@katherineqian Yes "Listen for Changes" was enabled on list queries. But infinite scroll was not enabled as you mentioned.

**Comment by Shubham-VE** [comment]
I have disabled "Listen for Changes" and infinite scroll is enabled as it is essential since there are thousands of records. Whenever there is a setState used, it causes issue with the listview be it in bottom sheet closure of navigating back from a page.
