### ISSUE TITLE
Likely visual bug in API call area

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#4873]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"Including" api variable does the opposite. Likely a visual bug

https://www.loom.com/share/4e200c14365b4cb79844c9e6b3677381

### Expected Behavior

opposite

### Steps to Reproduce

insert api variable
test it

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhcrluIhPm7VE0M/ucMJF9SYUCDt/U40z0sN+d0ogIpPmPaYPXfikSEpWZ9+kTHxcL2f9pzoep+jMv/PEA+UoZEmabqFy+bhyQzrgZFGtV666Pqm8XXB9JNJJJVPGyKSJqiNDPtF0Wi0n2mCHe+yiYArAJZDPIW1ANMqjJtn5s3upQ0SLb3kNh1JWeC/v

### Visual documentation

https://www.loom.com/share/4e200c14365b4cb79844c9e6b3677381

### Environment

```markdown
mac desktop version
```

### Additional Information

confusing

**Comment by Alezanello** [comment]
Hello!

This is actually the expected behavior. Since you have set a default value for the token variable, it will display this default value when testing if you don’t provide a new one. When you click on "Include," it expects a value to be set on the left side of the toggle. This is where you should assign an actual value to the token. If you toggle to "Include" but do not set a value for the variable, it will display as empty, as shown in your example.

**Comment by chuggmuffinReturns** [comment]
> Hello!
> 
> This is actually the expected behavior. Since you have set a default value for the token variable, it will display this default value when testing if you don’t provide a new one. When you click on "Include," it expects a value to be set on the left side of the toggle. This is where you should assign an actual value to the token. If you toggle to "Include" but do not set a value for the variable, it will display as empty, as shown in your example.

ohhhhhhhhhhhhhhhhhhhhhhh kkkkkkkkkkkkkkkkkk

I think I get it...

So you set up the call and all that jazz with the "default" value and the include/exclude thingy area is for mucking about with values that AREN'T the "default"

Hmmmm...

Maybe something "Production Variable" is better than Default and "Testing Variables" of "Testing Values" would be clearer?

Cool feature tho! I like the setup and agree that this is how it should be set up from a technical perspective! Very cool.
