### ISSUE TITLE
Content manager in firestore endlessly loading

### ISSUE THREAD

**Issue by shimahsn** [FlutterFlow/flutterflow-issues#4878]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on Manage Content, it shows the loading icon but nothing loads. However, when I try to update any field of that collection, it does not get updated.

### Expected Behavior

loading the data

### Steps to Reproduce

1. go to the fire store
2. click on manage content
3. the Fire data manager open
4. data won't show and loading Icon run endlessly

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

there is no code 

### Visual documentation

![Screenshot 2024-11-13 183024](https://github.com/user-attachments/assets/a3e1054f-6f00-411f-9cbe-cd25fce9edb7)

### Environment

```markdown
- FlutterFlow version:last one
- Platform: windows app
- Browser name and version: Microsoft edge
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!

Could you please generate a Bug Report Code so we can access your project and investigate the situation?

In the meantime, here are a few potential solutions that may help resolve the issue:

1. Deploy Firestore Rules.
2. Add **firebase@flutterflow.io** as an editor in your Firebase project.
3. If steps 1 and 2 are completed but the issue persists, go to the Authentication section of your Firebase project, find the user **firebase@flutterflow.io**, delete it, and then try reopening the CMS.

**Comment by shimahsn** [comment]
Thank you so much @Alezanello for reaching out. I found that I did too many reads and writes requests while testing the app and reached the Firestore free limits

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
