### ISSUE TITLE
ClipRect wrapping Blur widget by default

### ISSUE THREAD

**Issue by davidoort** [FlutterFlow/flutterflow-issues#488]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Blur widget FF with backdrop checked, should apply blur checked and no border radius set translates to 
BackdropFilter(
        filter: ImageFilter.blur(
          sigmaX: <>,
          sigmaY: <>,
),
child: ...

## Current behavior (required)

Blur widget FF with backdrop checked, should apply blur checked and no border radius set translates to 
ClipRect(
child: BackdropFilter(
        filter: ImageFilter.blur(
          sigmaX: <>,
          sigmaY: <>,
),
child: ...
)
## To Reproduce (required)

1. Create a new page
2. Create a blur widget with backdrop enabled
3. Check the code to see it's wrapped in a ClipRect widget

## Context (required)

I'm creating a bottomsheet with a blurred background with Drag enabled. With the cliprect wrapping the blurred background, when I drag the bottomsheet down to dismiss it I see the edge of the blurred region. If I remove the ClipRect widget the blur stays until the bottomsheet is fully dismissed which is the behavior I want.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @davidoort for the bug report! The Clip is part of the functionality of the Blur widget, especially when a border radius or circular clip is selected. However, we've added the ability to turn off the clip for now, which will be reflected in the next release!

**Comment by davidoort** [comment]
Perfect, thanks a lot!

**Comment by davidoort** [comment]
Hey! Thanks for fixing this :) Unfortunately the new feature you've added has created a new issue in the code preview:
![image](https://user-images.githubusercontent.com/21220927/223212338-17857801-e149-4e0a-84f9-24b8ac5ed4ab.png)

**Comment by davidoort** [comment]
Let me know if I should open a new issue @agreaves
