### ISSUE TITLE
All "Ul Builder Display Values" vanished after update 5.0.10 !

### ISSUE THREAD

**Issue by MickaMalko** [FlutterFlow/flutterflow-issues#4880]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After quickly accepting the latest version 5.0.10 and rebooting first the FF software, then my PC, I find that all the 'UI Builder Display Values' in my application no longer display on my interface. It’s very frustrating to always have to wait for feedback from other users to be sure that updates can be done safely.

### Expected Behavior

The 'UI Builder Display Values' in my application have to display on my interface.

### Steps to Reproduce

Update the app to "5.0.10" version and voilaaaa.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

There is no error code.

### Visual documentation

I wont show you a [1] instead of a "Andrew".
My explanation is enough.

### Environment

```markdown
- FlutterFlow version: 5.0.10
- Platform:PC
- Browser name and version:No browser
- Operating system and version affected: Windows 11 pro
```

**Comment by Alezanello** [comment]
Hello!

Could you please generate a bug report code from the Widget Tree so we can investigate the situation in your project? This issue appears to only affect certain fields, correct? Specifically, it seems that the Display Value in the UI Builder may have disappeared randomly, but the actual variables set for the text remain intact. Is that right?

**Comment by MickaMalko** [comment]
Hello,

Yes, this issue is affecting certain text fields specifically. The
variables have indeed remained in place and have not been reset.

Here is the bug report code as requested:
IT4klsrq5ot2m/VG7c/LbcFapCUQJWInTLJMt9VxSUghfYCuPYYcevfRbRFLYteVYwlEC2KLhkczzMmKveDPM/U5GyuBbpx8zJRXQQribGq6M67SBbW0XEZQJ+BUCHbEy5mvuBElXdBZWVoc2kyQLvCdG3qCf9qOYwx5e6fDbOY=

Thank you for looking into this!

Le mer. 13 nov. 2024 à 19:25, Alezanello ***@***.***> a
écrit :

**Comment by MickaMalko** [comment]
Additional information: it’s likely that this issue specifically affects
dynamic values embedded within "text combinations."

**Comment by chris-PearlIT** [comment]
I am finding the same problem, when importing a custom widget from my project library, the right hand side of the screen where the variables are declared is grey. Same thing you'd see in your app if there was an null error.
![Screenshot 2024-11-13 193551](https://github.com/user-attachments/assets/eb0ae672-3b4b-424f-8eac-e70615363ac2)

**Comment by Alezanello** [comment]
Hello, I sincerely apologize for the delayed response. Has this issue been resolved for you?

**Comment by MickaMalko** [comment]
> Hello, I sincerely apologize for the delayed response. Has this issue been resolved for you?

Solved. Thks.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!

**Comment by MickaMalko** [comment]
Hello

Here is my new MAJOR bug report.

At this point, my app creation process is stopped.

https://community.flutterflow.io/ask-the-community/post/flutterflow-s-translation-system-is-a-disaster-XIsxHYcTkEUd24z

Here is a bug report code
: IT4klsrq5ot2m/VG7c/LbcFapCUQJWInTLJMt9VxSUghfbGrPZktPszSUBZLYteUfXNiClL+8Vkdw6GMvuHTJ/YpGE2BGaZM+IRXQQribGq6M67SBbW0XEZQJ+BUCHbEy5mvuBElXdBZWVoc2kyQLvCdG3qCf9qOYwx5e6fDbOY=

If you could try to find a solution, it would be greatly appreciated. As
things stand, I’m seriously considering abandoning my project. Thank you.

Michael


Le mar. 19 nov. 2024 à 19:24, Alezanello ***@***.***> a
écrit :
