### ISSUE TITLE
Recent upgrade of flutterflow

### ISSUE THREAD

**Issue by klamki24pl** [FlutterFlow/flutterflow-issues#4881]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

variables are not anymore visible if supabase connection is being used

### Expected Behavior

variables should be visible, prior to recent update of flutterflow app

### Steps to Reproduce

install a new version of mac application, or
use the recent version of flutterflow online
it applies to supabase v1 or v2

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wjcn1z4tNxOZJ+r6JcO5vhSQWNjM2bZI7kcN+FBE0CLb0EKYPXfj7akhtTNe+S3NcL1mJ8Xgyp+jQvuP+A+UqNQ6dc6Jf1pBIYQ3vZGemb5C7Pcy3PXB8DeJJJVyA1J6JqhElKsdqLHAR22CyP9mAQT3ZJpzVIlVEGc6YUdvUpFWqQ0SLb3kNh1JWeC/v

### Visual documentation

red area - supabase - it's not working anymore since recent update
api call - this part didn't change, variables visible, all good

<img width="260" alt="Screenshot 2024-11-13 at 19 31 58" src="https://github.com/user-attachments/assets/35d119cc-fce3-4623-845d-2d9f9bdd0e40">

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Just a quick question—does it not work at all, or is it only the UI in the Builder that isn’t displaying the variables correctly?

Could you check if there are any errors in the console log when you run the app? Any additional details you can provide about the issue would be helpful!

**Comment by klamki24pl** [comment]
A the first sight – it looks like the UI issue. We had rebuild the app a few times and we are able to see it finally. Nevertheless, the issue remains in the flutterflow view.
When we run application the data is visible properly, surprisingly. Yesterday there was no problem with that.

we do not want to lose our recent development that’s we had created a ticket.

Is that sufficient?

***@***.***

From: Alezanello ***@***.***>
Date: Wednesday, 13 November 2024 at 20:02
To: FlutterFlow/flutterflow-issues ***@***.***>
Cc: Admin ***@***.***>, Author ***@***.***>
Subject: Re: [FlutterFlow/flutterflow-issues] Recent upgrade of flutterflow (Issue #4881)

Hello!

Just a quick question—does it not work at all, or is it only the UI in the Builder that isn’t displaying the variables correctly?

Could you check if there are any errors in the console log when you run the app? Any additional details you can provide about the issue would be helpful!

**Comment by Alezanello** [comment]
Hello, I sincerely apologize for the delayed response. Has this issue been resolved for you?

**Comment by klamki24pl** [comment]
no, the issue continues...
<img width="509" alt="Screenshot 2024-11-19 at 19 54 34" src="https://github.com/user-attachments/assets/41562f6e-c6b1-4a13-978b-bd14ae8f56b6">

**Comment by Alezanello** [comment]
In this case, I recommend reaching out to FlutterFlow support directly. You can contact them through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They will be able to assist you in checking and possibly reverting the changes to your project.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
