### ISSUE TITLE
Authentication tokens no longer stored > Causes user to log out

### ISSUE THREAD

**Issue by bicoastalapp** [FlutterFlow/flutterflow-issues#4882]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

App no longer stores authentication tokens from supabase, resets and clears all user details

### Expected Behavior

Prior release behavior:
As of the latest app update:
- User enters splash screen
- User clicks 'sign up'
- User enters credentials
- User enters createProfile screen

### Steps to Reproduce

As of the latest app update:
- User enters splash screen
- User clicks 'sign up'
- User enters credentials
- App redirects to create profile screen
- App refreshes, logs out users, and clears auth tokens

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi/Lqw812oblE0JDUb+xF/TkwGUwbUOc7j9VEGAsjCePsP4oAY8ylQFttSOqHYHNcDleammQe+vzLvt/LO8EqAzKCb6Zf/ql1UxDiIV+7VLKpCruKXHx5EcZUCW6i3MCzvyZNC7JhL2A5wF+ICN6+Y3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://wmbicctluzjkxmxestxg.supabase.co/storage/v1/object/public/assets/Screen%20Recording%202024-11-13%20at%2011.38.34%20AM.mp4

### Environment

```markdown
- FlutterFlow version:  v5.0.10+
- Platform: Mac
- Browser name and version: Arc v1.67.2
- Operating system and version affected: All
```

### Additional Information

Can no longer create an account to QA my application

**Comment by Alezanello** [comment]
Hello!

We've identified some issues with using Supabase in Test Mode. Have you tried running it locally or in Run Mode to see if the behavior remains the same?

**Comment by bicoastalapp** [comment]
Had the same issue in run mode, after reviewing the status page to see if
there were any errors. How does one identify these issues from version
updates?

**Comment by bicoastalapp** [comment]
Any updates?

**Comment by bicoastalapp** [comment]
@alezanello any updates?

**Comment by bicoastalapp** [comment]
@FlutterFlowEng @Alezanello any reason this ticket is still in, "Waiting for user response"?

**Comment by glgh** [comment]
hi @bicoastalapp, thanks for the bug report -- I checked the project but seems there are some existing project errors. Could you either fix the project errors, or share a new project where this issue can be reproduced?

**Comment by bicoastalapp** [comment]
These errors occurred just now from closing my supabase connection to test
another app builder. Will follow up if we continue to pursue flutterflow

**Comment by glgh** [comment]
no problem - let us know if there's anything we can do to help fix the issue!

**Comment by rzambroni** [comment]
Closing this issue for now since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by bicoastalapp** [comment]
Thanks, we have to move platforms due to this issue
