### ISSUE TITLE
Circular progress bar UI issues

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#4883]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Circular progress bar is displaying the background color around the outer edges (iOS and Android) and on iOS only the slice is not displaying cleanly.

### Expected Behavior

Circular progress bar should only show background color in the area not filled by the progress slice, and the slice should be centered and have clean, linear boundaries.

### Steps to Reproduce

1. Create a page and place a 30px circular progress bar with 15px thickness
2. Run on iOS device

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87lx4lgoddA1rrtbcExvCo4H245TL0vs+xEGBYaIozkPe4MZ876P1FtOM+iTGx9eU6mp14zpM7oifzxIfpeFy+Ab75T/89AdQmUUjmRRZOTF7jgdkZPM+ZmI3HD4Zi3ph1APfhpW3gm7U6UCtmXUhfdHabTDWowSq/LZO4=

### Visual documentation

![IMG_5379](https://github.com/user-attachments/assets/64a818c6-0d51-49eb-abca-da4edce3d1d3)
![IMG_5380](https://github.com/user-attachments/assets/63da6a1f-758a-4f0e-a656-69ca7875fec1)
![IMG_5381](https://github.com/user-attachments/assets/7af1562f-63c7-4f02-9cce-81f02ce2898a)

### Environment

```markdown
- FlutterFlow version: 5.0.10
- Platform: macOS
- Browser name and version: n/a
- Operating system and version affected: iOS 17
```

**Comment by Alezanello** [comment]
Hello!

I was unable to replicate this issue on Web, Android, or iOS. Here is the public project link for you to clone and test on your end to see if I might be missing any steps.<br><br>Public Project: [https://app.flutterflow.io/project/qa-3029-xnwrq3](https://app.flutterflow.io/project/qa-3029-xnwrq3)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9878b8ad-8cbc-44e5-a4ac-0165429f5f29/eff692b1-09a8-4c0d-bb0c-e5e048a65597?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ODc4YjhhZC04Y2JjLTQ0ZTUtYTRhYy0wMTY1NDI5ZjVmMjkvZWZmNjkyYjEtMDlhOC00YzBkLWJiMGMtZTVlMDQ4YTY1NTk3IiwiaWF0IjoxNzMxNTg4MjIzLCJleHAiOjMzMzAyMTQ4MjIzfQ.ma6NXRpBXKS3JihMBRBt1xic2cNv9k6JK1dwCRjQHUQ " alt="image.png" width="1919" height="696" />

**Comment by max-h-silverman** [comment]
@Alezanello You can see one of the two issues in the screenshot you provided (there is orange from the bg showing through around the edges of the circle. Also, I just reproduced this in another test project and ran it on my iPhone and am seeing the misshapen slice. Please test it on an actual device not an virtual one and look closely at what's being displayed.

![IMG_5385](https://github.com/user-attachments/assets/0ed31bf1-9d62-479c-a0b3-400463adfd7c)

**Comment by Alezanello** [comment]
Yes it seems there is a little error on iOS directly, I'm going to check if this is something that depends on FlutterFlow directly or is some issue with the package itself!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f4af7fbb-9e3e-4718-ad2f-8ee3bac941a5/d6b00651-1788-4683-9bd5-0c2224d48fca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNGFmN2ZiYi05ZTNlLTQ3MTgtYWQyZi04ZWUzYmFjOTQxYTUvZDZiMDA2NTEtMTc4OC00NjgzLTliZDUtMGMyMjI0ZDQ4ZmNhIiwiaWF0IjoxNzMyMjAyNzk2LCJleHAiOjMzMzAyNzYyNzk2fQ.si_vlImm_tanmLEw1F8dhGrnUuX7KNDkWAjeCQAnSqQ " alt="image.png" width="360" height="778" />

**Comment by Alezanello** [comment]
**Hello!** 

Apologies for the delayed response regarding this issue. The widget in question is not developed by FlutterFlow—it is part of a third-party package called **percent_indicator** ([link to package](https://pub.dev/packages/percent_indicator)). Unfortunately, this means FlutterFlow cannot modify how it is displayed or address errors that may occur under certain configurations.

For now, we recommend either waiting for the package maintainers to release a fix or creating a **custom widget** using an alternative package that better suits your needs.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
