### ISSUE TITLE
Grey variable box in Update 5.0.10+

### ISSUE THREAD

**Issue by chris-PearlIT** [FlutterFlow/flutterflow-issues#4884]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When importing a custom widget from my project library the variable box on the right is grey.
This behavior also exists in the browser version.
When using a duplicate custom widget from within my project and not from library. the variables display as expected.
I have deleted the project library dependency and re installed it : still a grey variable box.

UPDATE. the release of 5.0.11 has not solved this issue. I have also updated my library by doing a commit : no change.

### Expected Behavior

Variable display as always so they can be assigned.

### Steps to Reproduce

Start project
Add your project library as a dependency.
Make a blank page
Add any custom widget from project library.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESisn1x4VgrtwC7ofQde1qhQMkQzM6bZI7ku1EdwEhNbboB+wxPODBYRJLYtThTUFlfWCJsGQx0+zOv4XXUvA4Jk2abqE+wb5XQQ7yQli5MIiIBZagY0EmJJ9PfWKvyMK7viZDLtpoSGNl1Geyf/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot 2024-11-13 193551](https://github.com/user-attachments/assets/3c9298e9-9bbb-4beb-9359-45eb46481728)

### Environment

```markdown
- FlutterFlow version: 5.0.10+
- Platform: Windows PC
- Browser name and version: Chrome and Egde
- Operating system and version affected: Windows 11 Pro
```

### Additional Information

With the complete farce that was your last update, I would have hoped you'd learned a lesson. We who use and pay for your platform dread seeing the "Update FlutterFlow" button. I am a staunch supporter of FF but your quality control is starting to shake my confidence.

**Comment by Alezanello** [comment]
Hello,

I’m sorry to hear about your experience, and thank you for bringing this to our attention. I can confirm this issue and will escalate it to the engineering team as an urgent matter for a fix.

**Comment by blueprin4** [comment]
I was just about to report this.  Thanks for already reporting it.  When I copy the code from the library and add as a widget it works.  So I am going that route until it fixed.

**Comment by ALaiFF** [comment]
I face the similar issue… Grey screen, no option to move further
FlutterFlow v5.0.13 released November 20, 2024
Flutter version is 3.24.2

**Comment by leighajarett** [comment]
This issue is fixed and will be resolved in the release on Tuesday - so sorry about this!
