### ISSUE TITLE
App in local run not responding after update to 5.0.10.

### ISSUE THREAD

**Issue by uxpropl** [FlutterFlow/flutterflow-issues#4885]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After updating FF to the latest version 5.0.10, the application running locally ceases responding after a short period following the build process. Additionally, for no apparent reason, one of the input fields is automatically focused, even when the autofocus option is not selected for that particular input. Furthermore, the keyboard display overrides all other elements, and there is no option to close it and or type in a text. No bug in device logs.

### Expected Behavior

The application should function as intended. Another update has introduced bugs... Please prioritize investing in qa.

### Steps to Reproduce

1. Run app in Local run

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40k+fqxItNpbxE+KqIbcdr/Sc5KUQ7aOcw0up7aCosfZT2BLMcec/RVERpZM+hdGw+fFqZgWoW0M7IifHpIPoVAxWdbapxyLoBdDyWVXytb6qrFJWgRHdPEdxQIXKz5qun2xJ5Nu5hLSEn7WeUft7IYHfDQoOwCmtNDq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/18b87249-f2c9-41da-b02c-5e8f52b891f7

### Environment

```markdown
- FlutterFlow version: 5.0.10
- Platform: MacOS Desktop
- Operating system and version affected: Sequoia 15.1 (24B2082)
```

**Comment by Alezanello** [comment]
Hello!

I’m unable to replicate this issue on a new blank project. Could you please clarify which specific TextField is being focused, even though it does not have autofocus enabled?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
