### ISSUE TITLE
Fail Deploy To Appstore Cocoapods

### ISSUE THREAD

**Issue by TheBestLevel** [FlutterFlow/flutterflow-issues#4886]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I receive a Fail deploy to appstore:

</x-turndown> body {   color:#C8C8C8;   overflow-x: hidden;   padding-top: 0px;   padding-right: 5px;   padding-bottom: 5px;   padding-left: 5px;   font-family: monaco; } h4 {   margin-bottom: 4px;   font-weight: bold;   color: #DF3F3F; }

#### Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐ │ A new version of Flutter is available! │ │ │ │ To update to the latest version, run "flutter upgrade". │ └─────────────────────────────────────────────────────────┘ Resolving dependencies... Downloading packages...

* \_flutterfire_internals 1.3.44 (1.3.46 available)
* algolia 1.1.1 (1.1.2 available)
* aligned_dialog 0.0.6 (0.0.7 available)
* aligned_tooltip 0.0.1
* ansicolor 2.0.3
* archive 3.6.1
* args 2.6.0
* async 2.11.0 (2.12.0 available)
* auto_size_text 3.0.0
* badges 2.0.2 (3.1.2 available)
* boolean_selector 2.1.1 (2.1.2 available)
* cached_network_image 3.4.1
* cached_network_image_platform_interface 4.1.1
* cached_network_image_web 1.3.1
* characters 1.3.0 (1.3.1 available)
* checked_yaml 2.0.3
* chewie 1.8.5
* cli_util 0.4.2
* clock 1.1.1 (1.1.2 available)
* cloud_firestore 5.4.4 (5.5.0 available)
* cloud_firestore_platform_interface 6.4.3 (6.5.0 available)
* cloud_firestore_web 4.3.2 (4.3.4 available)
* cloud_functions 5.1.3 (5.1.5 available)
* cloud_functions_platform_interface 5.5.37 (5.5.39 available)
* cloud_functions_web 4.10.2 (4.10.4 available)
* collection 1.18.0 (1.19.1 available)
* cross_file 0.3.4+2
* crypto 3.0.6
* csslib 0.17.3 (1.0.2 available)
* cupertino_icons 1.0.8
* date_count_down 3.0.0
* dbus 0.7.10 ! device_info_plus 10.1.2 (overridden) (11.1.1 available) ! device_info_plus_platform_interface 7.0.1 (overridden)
* dropdown_button2 2.3.9
* easy_debounce 2.0.1 (2.0.3 available)
* equatable 2.0.5
* expandable 5.0.1
* extension 0.6.0
* fake_async 1.3.1 (1.3.2 available)
* ffi 2.1.3
* file 7.0.1
* file_picker 8.1.2 (8.1.4 available)
* file_selector_linux 0.9.3+1
* file_selector_macos 0.9.4+2
* file_selector_platform_interface 2.6.2
* file_selector_windows 0.9.3+3
* firebase_analytics 11.3.3 (11.3.5 available)
* firebase_analytics_platform_interface 4.2.5 (4.2.7 available)
* firebase_analytics_web 0.5.10+2 (0.5.10+4 available)
* firebase_auth 5.3.1 (5.3.3 available)
* firebase_auth_platform_interface 7.4.7 (7.4.9 available)
* firebase_auth_web 5.13.2 (5.13.4 available)
* firebase_core 3.6.0 (3.8.0 available)
* firebase_core_platform_interface 5.3.0
* firebase_core_web 2.18.1
* firebase_messaging 15.1.3 (15.1.5 available)
* firebase_messaging_platform_interface 4.5.46 (4.5.48 available)
* firebase_messaging_web 3.9.2 (3.9.4 available)
* firebase_performance 0.10.0+8 (0.10.0+10 available)
* firebase_performance_platform_interface 0.1.4+44 (0.1.4+46 available)
* firebase_performance_web 0.1.7+2 (0.1.7+4 available)
* firebase_remote_config 5.1.3 (5.1.5 available)
* firebase_remote_config_platform_interface 1.4.44 (1.4.46 available)
* firebase_remote_config_web 1.7.2 (1.7.4 available)
* firebase_storage 12.3.2 (12.3.6 available)
* firebase_storage_platform_interface 5.1.31 (5.1.33 available)
* firebase_storage_web 3.10.2 (3.10.5 available)
* fixnum 1.1.1
* flutter 0.0.0 from sdk flutter
* flutter_animate 4.5.0
* flutter_braintree 4.0.0
* flutter_cache_manager 3.4.1
* flutter_fortune_wheel 1.3.1 (1.3.2 available)
* flutter_hooks 0.18.6 (0.20.5 available)
* flutter_inappwebview 5.8.0 (6.1.5 available)
* flutter_keyboard_visibility 6.0.0
* flutter_keyboard_visibility_linux 1.0.0
* flutter_keyboard_visibility_macos 1.0.0
* flutter_keyboard_visibility_platform_interface 2.0.0
* flutter_keyboard_visibility_web 2.0.0
* flutter_keyboard_visibility_windows 1.0.0
* flutter_launcher_icons 0.13.1 (0.14.1 available)
* flutter_lints 4.0.0 (5.0.0 available)
* flutter_localizations 0.0.0 from sdk flutter
* flutter_native_splash 2.4.1 (2.4.2 available)
* flutter_plugin_android_lifecycle 2.0.20 (2.0.23 available)
* flutter_rating_bar 4.0.1
* flutter_shaders 0.1.3
* flutter_staggered_grid_view 0.7.0
* flutter_test 0.0.0 from sdk flutter
* flutter_web_plugins 0.0.0 from sdk flutter
* font_awesome_flutter 10.7.0 (10.8.0 available)
* from_css_color 2.0.0
* go_router 12.1.3 (14.6.0 available)
* google_fonts 6.1.0 (6.2.1 available)
* google_identity_services_web 0.3.1+5
* google_sign_in 6.2.1 (6.2.2 available)
* google_sign_in_android 6.1.30 (6.1.33 available)
* google_sign_in_ios 5.7.7 (5.7.8 available)
* google_sign_in_platform_interface 2.4.5
* google_sign_in_web 0.12.4+2 (0.12.4+3 available)
* html 0.15.4 (0.15.5 available) ! http 1.2.2 (overridden)
* http_parser 4.0.2 (4.1.1 available)
* image 4.2.0 (4.3.0 available)
* image_picker 1.1.2
* image_picker_android 0.8.12+13 (0.8.12+17 available)
* image_picker_for_web 3.0.5 (3.0.6 available)
* image_picker_ios 0.8.12 (0.8.12+1 available)
* image_picker_linux 0.2.1+1
* image_picker_macos 0.2.1+1
* image_picker_platform_interface 2.10.0
* image_picker_windows 0.2.1+1
* in_app_review 2.0.9
* in_app_review_platform_interface 2.0.5
* infinite_scroll_pagination 4.0.0 (4.1.0 available)
* internet_file 1.2.0
* intl 0.19.0 (0.20.0 available)
* iregexp 0.1.2
* json_annotation 4.9.0
* json_path 0.7.2 (0.7.4 available)
* leak_tracker 10.0.5 (10.0.8 available)
* leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
* leak_tracker_testing 3.0.1
* lints 4.0.0 (5.1.0 available)
* logging 1.3.0
* lottie 2.7.0 (3.1.3 available)
* matcher 0.12.16+1 (0.12.17 available)
* material_color_utilities 0.11.1 (0.12.0 available)
* maybe_just_nothing 0.5.3
* meta 1.15.0 (1.16.0 available)
* mime 1.0.6 (2.0.0 available)
* mime_type 1.0.0 (1.0.1 available)
* nested 1.0.0
* octo_image 2.1.0
* package_info_plus 8.1.1
* package_info_plus_platform_interface 3.0.1
* page_transition 2.1.0
* path 1.9.0 (1.9.1 available)
* path_provider 2.1.4 (2.1.5 available)
* path_provider_android 2.2.10 (2.2.12 available)
* path_provider_foundation 2.4.0
* path_provider_linux 2.2.1
* path_provider_platform_interface 2.1.2
* path_provider_windows 2.2.1 (2.3.0 available)
* pdfx 2.8.0
* permission_handler 11.3.1
* permission_handler_android 12.0.12 (12.0.13 available)
* permission_handler_apple 9.4.5
* permission_handler_html 0.1.3+2
* permission_handler_platform_interface 4.2.3
* permission_handler_windows 0.2.1
* petitparser 6.0.2 ! photo_view 0.15.0 (overridden)
* pin_code_fields 8.0.1
* platform 3.1.6
* plugin_platform_interface 2.1.8
* provider 6.1.2
* quiver 3.2.2
* rfc_6901 0.2.0
* rxdart 0.27.7 (0.28.0 available)
* share_plus 10.0.2 (10.1.2 available)
* share_plus_platform_interface 5.0.0 (5.0.1 available)
* shared_preferences 2.3.2 (2.3.3 available)
* shared_preferences_android 2.3.2 (2.3.3 available)
* shared_preferences_foundation 2.5.2 (2.5.3 available)
* shared_preferences_linux 2.4.1
* shared_preferences_platform_interface 2.4.1
* shared_preferences_web 2.4.2
* shared_preferences_windows 2.4.1
* sign_in_with_apple 6.1.2 (6.1.3 available)
* sign_in_with_apple_platform_interface 1.1.0
* sign_in_with_apple_web 2.1.0
* simple_gesture_detector 0.2.1
* simple_gradient_text 1.2.3 (1.3.0 available)
* sky_engine 0.0.99 from sdk flutter
* sliver_tools 0.2.12
* smooth_page_indicator 1.1.0 (1.2.0+3 available)
* source_span 1.10.0
* sprintf 7.0.0
* sqflite 2.3.3+1 (2.4.1 available)
* sqflite_common 2.5.4+3 (2.5.4+5 available)
* stack_trace 1.11.1 (1.12.0 available)
* stop_watch_timer 3.0.2 (3.2.1 available)
* stream_channel 2.1.2
* stream_transform 2.1.0
* string_scanner 1.2.0 (1.4.0 available)
* substring_highlight 1.0.33
* synchronized 3.3.0+3
* table_calendar 3.1.1 (3.1.2 available)
* term_glyph 1.2.1
* test_api 0.7.2 (0.7.3 available)
* timeago 3.6.1 (3.7.0 available)
* typed_data 1.4.0
* universal_file 1.0.0
* universal_io 2.2.2
* universal_platform 1.1.0
* url_launcher 6.3.0 (6.3.1 available)
* url_launcher_android 6.3.10 (6.3.14 available)
* url_launcher_ios 6.3.1
* url_launcher_linux 3.2.0 (3.2.1 available)
* url_launcher_macos 3.2.1
* url_launcher_platform_interface 2.3.2
* url_launcher_web 2.3.3
* url_launcher_windows 3.1.2 (3.1.3 available) ! uuid 4.5.1 (overridden)
* vector_math 2.1.4
* video_player 2.9.2
* video_player_android 2.7.13 (2.7.16 available)
* video_player_avfoundation 2.6.2
* video_player_platform_interface 6.2.3
* video_player_web 2.3.2 (2.3.3 available)
* vm_service 14.2.5 (14.3.1 available)
* wakelock_plus 1.2.8
* wakelock_plus_platform_interface 1.2.1
* web 1.1.0 ! win32 5.5.1 (overridden) (5.8.0 available)
* win32_registry 1.1.5 (2.0.0 available)
* xdg_directories 1.1.0
* xml 6.5.0
* yaml 3.1.2 Changed 216 dependencies! 102 packages have newer versions incompatible with dependency constraints. Try `flutter pub outdated` for more information. Analyzing dependencies Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.2.0` cloud_firestore: Using Firebase SDK version '11.2.0' defined in 'firebase_core' cloud_functions: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_analytics: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_auth: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_core: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_messaging: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_performance: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_remote_config: Using Firebase SDK version '11.2.0' defined in 'firebase_core' firebase_storage: Using Firebase SDK version '11.2.0' defined in 'firebase_core' Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/` \[!\] CocoaPods could not find compatible versions for pod "FirebaseFirestore": In Podfile:   FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.2.0`)

Specs satisfying the `FirebaseFirestore (from `[https://github.com/invertase/firestore-ios-sdk-frameworks.git\`](https://github.com/invertase/firestore-ios-sdk-frameworks.git%60), tag `11.2.0`)\` dependency were found, but they required a higher minimum deployment target.

Build failed :| Step 6 script `Install pods` exited with status code 1

### Expected Behavior

Normal codemagic deploy via Flutterflow

### Steps to Reproduce

Deploy to appstore

I can not give more detail, this is a proyect issue that i dont know how to solve.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wl/Llz5d1octY7ar+cfpVijgsIjp/RLhEmsFueCs8GZT0B4kcYs+kfklUONOhdAhce2KKjj0X/MqOj/OSOvUENU+qbLo5z5ZLEBXMZFKnWrKDCJS3b2tfJJ9jJky65re3sCQnOvt2LF492U6YCN6sZCjtNJP4NVYnAuaeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7cffbb8d-8a0f-4a4d-b9ef-19f57c6537c5/8a55ea85-76aa-434e-b224-d2f3618427dc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83Y2ZmYmI4ZC04YTBmLTRhNGQtYjllZi0xOWY1N2M2NTM3YzUvOGE1NWVhODUtNzZhYS00MzRlLWIyMjQtZDJmMzYxODQyN2RjIiwiaWF0IjoxNzQ0ODgyMTQ3LCJleHAiOjMzMzE1NDQyMTQ3fQ.lUsZw-AmOSGGSdSztxEvuZ2kGn2NtEmpQrJ25ujLksY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/94bba965-3fb3-4f30-9ae2-c97a15bab628/ac28d782-078b-43c8-a01c-80d4c6851e9b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NGJiYTk2NS0zZmIzLTRmMzAtOWFlMi1jOTdhMTViYWI2MjgvYWMyOGQ3ODItMDc4Yi00M2M4LWEwMWMtODBkNGM2ODUxZTliIiwiaWF0IjoxNzQ0ODgyMTQ3LCJleHAiOjMzMzE1NDQyMTQ3fQ.lhXkpA8k0GKOwG1g9leq9PeAMvJBEs-ODRH1GkyHfrE)

### Environment

```markdown
- FlutterFlow version: v5.0.10+ released November 13, 2024
- Platform: Web
- Browser name and version:Versión 130.0.6723.117 (Build oficial) (64 bits)
- Operating system and version affected: Desktop Windows 10
```

### Additional Information

I tried to deploy to appstore. I never had trouble and i deployed like 80 times. This time yet i have this issue that i have not been able to solve

**Comment by Alezanello** [comment]
Could you please generate a Bug Report Code for your project?<br>To do this, simply go to the Widget Tree, right-click on any row or column, and you should see the option to generate the code.

**Comment by TheBestLevel** [comment]
> Could you please generate a Bug Report Code for your project?To do this, simply go to the Widget Tree, right-click on any row or column, and you should see the option to generate the code.

IT4wl/Llz5d1octY7ar+cfpVijgsIjp/RLhEmsFueCs8GZT0B4kcYs+kfklUONOhdAhce2KKjj0X/MqOj/OSOvUENU+qbLo5z5ZLEBXMZFKnWrKDCJS3b2tfJJ9jJky65re3sCQnOvt2LF492U6YCN6sZCjtNJP4NVYnAuaeXdeK2SrDX1iXc2URm05KZDPz

**Comment by Alezanello** [comment]
Hello!<br><br>Did last FlutterFlow update solved this issue for you?

**Comment by TheBestLevel** [comment]
It is solved, but it was not the update that solved it. There was a custome code with app messaging that was creating the error. I delted that code and started working

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
