### ISSUE TITLE
Grey Textfield

### ISSUE THREAD

**Issue by tiago-owl** [FlutterFlow/flutterflow-issues#4887]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All textfield widgets are grey in my projects..
![Captura de tela 2024-11-14 071822](https://github.com/user-attachments/assets/b774d5dd-c80a-45bf-9caf-0054920cdd78)

### Expected Behavior

be ok :)

### Steps to Reproduce

Open Project, go to "editPage" or "edtitContent" components and you'll see.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KjfHl34hIxOFK7q6Jcvpagj8sHDMnargslsJERRQcB5jtG7YMWvfObhJeZ+m+THxcL1r9mmIx+anXvdnIA+UnEyeuGdU9zKlbEwqUfF+6V6qQC6rsdHJCJ95JJVzC4cPYoCN7IfhZLFIS2zmMHt7LYHbDGO/XOG4nJfL+DKb7gVWrQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/1a8ac2df-e9be-4925-a109-f1e74402e350

### Environment

```markdown
- FlutterFlow version: v5.0.11+
- Platform: Desktop
- Operating system and version affected: Windows
```

### Additional Information

Can't proceed with the project..

**Comment by Alezanello** [comment]
Hello!

I was able to replicate the issue and identified the bug. It occurs when Autocomplete is enabled, and the "Cursor Color" is set using a variable. I will forward this to the team for a fix. Thank you for bringing this to our attention, and I apologize for the inconvenience!
