### ISSUE TITLE
TextInputAction.next switches to next FocusNode, but Textfield is not focused

### ISSUE THREAD

**Issue by PhillipMahlke-flour** [FlutterFlow/flutterflow-issues#4888]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a `TextField` with a `TextEditingController` and the `textInputAction` set to `TextInputAction.next`, if you use `FFAppState().update()` in the `onSubmitted` callback of the TextField, the next TextField does not get Focused like it should.

The TextInput is selected, but no cursor is visible.
Writing a Letter while in this state, focuses the TextField, places the Cursor at the front of the existing Input string and inserts the typed letter.
Writing a Number while in this state, does not focus the TextField and the input gets ignored.

### Expected Behavior

It should behave like flutter does with its setState() functionality. Meaning it should focus the next TextField correctly and set the cursor at the end of the input string.

### Steps to Reproduce

1. Create new Custom Widget
2. add a TextInput via Code
5. add a `FFAppState().update()` to the `onSubmitted` callback. 
6. set `textInputAction` of the TextField to `TextInputAction.next`
7. add a `TextEditingController` to the TextField.
8. Add multiple instances of the widget to a page.
9. Test the App
10. Submit the first TextField and you will see the issue of the next TextField not being in Focus. Upon entering a letter, the TextField gets focussed, but the cursor appears at the start, not the end of the string, somewhat resolving the issue. However, If your first try to enter a Number, the input gets completely ignored and the focus is not set. this is prominently visible, if the keyboardType is set to number.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tkcrq25BIocRE1aX2Y8dVmSQWHFw4arhEiet+bxQaJuvuEJkxP8n8Q3FJYcukTFVcIWKZ/Wcz+KHVkfzDVvldFxOCaYNe1KlQTz3JWkWjWqaLOrueZEF8MJlmJ3LEy7ukmA9RCMFfSCRk70+uGOmyZCbtNoTVDDAvQ+aIKt/P+GyKAA2+Ey97zmNecCfn

### Visual documentation

Not really Necessary, since it is easily reproduced. For easier testing, here some dummy code of a custom Widget, that produces the Issue.

```
class NewCustomWidget extends StatefulWidget {
  const NewCustomWidget({
    super.key,
    this.width,
    this.height,
  });

  final double? width;
  final double? height;

  @override
  State<NewCustomWidget> createState() => _NewCustomWidgetState();
}

class _NewCustomWidgetState extends State<NewCustomWidget> {
  @override
  Widget build(BuildContext context) {
    return TextField(
      onSubmitted: (value) {
        FFAppState().update(() {
          FFAppState().debug = true;
        });
      },
      controller: TextEditingController(text: ""),
      textInputAction: TextInputAction.next,
    );
  }
}
```

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Android
- Browser name and version: - 
- Operating system and version affected: Android 12, Android 14
```

**Comment by PhillipMahlke-flour** [comment]
Additional Information: Flutter itself has a similar problem using the setState() function instead of FFAppState().update(), but that can be resolved by specifying a key on the TextField, that was initialized in the initState() Function. This does not fix the issue in the case of FlutterFlow.

**Comment by Alezanello** [comment]
Hello!

I was unable to replicate the behavior you described. When I submit, it transitions directly to the next node with focus, and I am able to start typing without any issues.<br><br>Public project: [https://app.flutterflow.io/project/qa-3034-8lsasw](https://app.flutterflow.io/project/qa-3034-8lsasw)

[Screen-Recording (44).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3dda75c6-737b-45bc-993c-48191a8be99f/219e8485-3507-4654-bdfc-ae7e237798f0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zZGRhNzVjNi03MzdiLTQ1YmMtOTkzYy00ODE5MWE4YmU5OWYvMjE5ZTg0ODUtMzUwNy00NjU0LWJkZmMtYWU3ZTIzNzc5OGYwIiwiaWF0IjoxNzMxNTg3MzE4LCJleHAiOjMzMzAyMTQ3MzE4fQ.OPFcwaKG2-3p2X4dDhN5SMgfthD9AqhPDVH4IBaCDbY)

**Comment by PhillipMahlke-flour** [comment]
As stated in the Report, Platform is Android. Running a Local Test (via the FlutterFlow Desktop App) on a connected android device produces the described issue.

The public Project you linked doesn't load for me, so i cannot test it in that. But a new Project using the exact same code produces the error when running it on an android device

**Comment by Alezanello** [comment]
Hello!

I’m still unable to replicate the issue on both iOS and Android devices (virtual & physical). Everything seems to be working as expected—when the submit button is pressed, it correctly moves to the next field.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/21eeb3f8-c2f2-4dcd-9390-8dda8fba80fa/e80c8618-a45d-4482-8d07-d3fe491d4ad5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMWVlYjNmOC1jMmYyLTRkY2QtOTM5MC04ZGRhOGZiYTgwZmEvZTgwYzg2MTgtYTQ1ZC00NDgyLThkMDctZDNmZTQ5MWQ0YWQ1IiwiaWF0IjoxNzMyMjAwMDcxLCJleHAiOjMzMzAyNzYwMDcxfQ.goYQjboW6YXvtfDKDW7rRC6DBy-HN_0BzeJT0OIi9Fk " alt="textfie.gif" width="1717" height="888" />

**Comment by PhillipMahlke-flour** [comment]
Thank you for taking your time to test this issue,

it seems like some other things are messing it up then. The only difference i can see, is the usage of the desktop app instead of the exported code in visual studio, but i doubt that makes a difference. I will test it again and try to make the issue reproducable.

**Comment by Alezanello** [comment]
Hello again!

Just checking in—were you able to replicate the issue? Let me know if there’s anything else I can assist you with!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, if you are still experiencing an issue feel free to open a new one. Thanks.
