### ISSUE TITLE
local run is not updating after restarting, hot reloading or even stopping and starting the app again. The project is not being updated.

### ISSUE THREAD

**Issue by dbfcode** [FlutterFlow/flutterflow-issues#4889]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

local run is not updating after restarting, hot reloading or even stopping and starting the app again. The project is not being updated.

### Expected Behavior

make this work

### Steps to Reproduce

1. make changes
2. try to update the project (hot reload, restart...)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzPHl3It1n7wA+KrUbexF9GIWI0MdXOczitVEew4bCIj4PZoqZsn7S1tvXsizaH5+JGekij0e0ayMi97pCPoBAzWYf6pFzbVUYBPPbHyWbqqpEqWzP3x8TZ5UIFy54Z+rqwhSXbR2V1Y87DulNtiiST6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="872" alt="image" src="https://github.com/user-attachments/assets/0985c794-8066-430b-947a-73bc945ca882">

### Environment

```markdown
- FlutterFlow version: 5.0.11 (also happening since the 5.0.10)
- Platform: desktop (local run - cause your supabase v1 only allows to use localrun now)
- Browser name and version: chrome
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello!

I was unable to replicate this issue on my end. Could you please reach out to support through the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io)? This will allow us to investigate further and determine if there is something specific within your project that might be causing this behavior.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
