### ISSUE TITLE
MapPicker issue 

### ISSUE THREAD

**Issue by ahmedkameelha** [FlutterFlow/flutterflow-issues#489]
![1 map](https://user-images.githubusercontent.com/117951533/218715812-c8ec0792-38e8-444e-9251-6cff6c29ddc5.png)
![2 map](https://user-images.githubusercontent.com/117951533/218715830-a57d3942-0525-46e6-872c-f07e4432a322.png)
![3 map](https://user-images.githubusercontent.com/117951533/218716377-b6f51653-9110-4b6d-8c81-c85d708b6a52.png)
![4 map](https://user-images.githubusercontent.com/117951533/218716938-11fa304b-f7b6-4fb3-a711-a6feb34d2ef0.png)
![5 map](https://user-images.githubusercontent.com/117951533/218716441-b4194f9e-f231-4a42-b26a-e28cf7b20210.png)
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

there is Unknown Error ( this MapPicker widget should to make the user pick any location from the map  by the pin ) 

## Current behavior (required)

there is unkoownerror 
## To Reproduce (required)
import 'package:geocoder/geocoder.dart'; //import geocoder to get address line from coordinates
import 'package:google_maps_flutter/google_maps_flutter.dart';
// ignore: import_of_legacy_library_into_null_safe
import 'package:map_pin_picker/map_pin_picker.dart';

/// Map picker is controlled with MapPickerController. Map pin is lifted up
/// whenever mapMoving() is called, and will be down when mapFinishedMoving()
/// is called.
/// MapPicker widget is main widget that gets map as a child.
/// It does not restrict user from using maps other than google map.
/// [MapPicker] is controlled with [MapPickerController] class object
class MapPicker extends StatefulWidget {
  /// Map widget, Google, Yandex Map or any other map can be used, see example
  final Widget child;

  /// Map pin widget in the center of the screen. [iconWidget] is used with
  /// animation controller
  final Widget? iconWidget;

  /// default value is true, defines, if there is a dot, at the bottom of the pin
  final bool showDot;

  /// [MapPicker] can be controller with [MapPickerController] object.
  /// you can call mapPickerController.mapMoving!() and
  /// mapPickerController.mapFinishedMoving!() for controlling the Map Pin.
  final MapPickerController mapPickerController;

  const MapPicker({
    Key? key,
    required this.child,
    required this.mapPickerController,
    this.iconWidget,
    this.showDot = true,
  }) : super(key: key);

  @override
  _MapPickerState createState() => _MapPickerState();
}

class _MapPickerState extends State<MapPicker>
    with SingleTickerProviderStateMixin {
  static const double _dotRadius = 2.2;

  late AnimationController animationController;
  late Animation<double> translateAnimation;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 300),
    );

    widget.mapPickerController.mapMoving = mapMoving;
    widget.mapPickerController.mapFinishedMoving = mapFinishedMoving;

    translateAnimation = Tween(
      begin: 0.0,
      end: 1.0,
    ).animate(CurvedAnimation(
      parent: animationController,
      curve: Curves.ease,
    ));
  }

  /// Start of animation when map starts dragging by user, checks the state
  /// before firing animation, thus optimizing for rendering purposes
  void mapMoving() {
    if (!animationController.isAnimating && !animationController.isCompleted) {
      animationController.forward();
    }
  }

  /// down the Pin whenever the map is released and goes to idle position
  void mapFinishedMoving() {
    animationController.reverse();
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        return Stack(
          alignment: Alignment.center,
          children: [
            widget.child,
            Positioned(
              bottom: constraints.maxHeight * 0.5 - 10,
              child: AnimatedBuilder(
                  animation: animationController,
                  builder: (context, snapshot) {
                    return Stack(
                      alignment: Alignment.bottomCenter,
                      children: [
                        if (widget.showDot)
                          Container(
                            width: _dotRadius,
                            height: _dotRadius,
                            decoration: BoxDecoration(
                              color: Colors.black,
                              borderRadius: BorderRadius.circular(_dotRadius),
                            ),
                          ),
                        Transform.translate(
                          offset: Offset(0, -15 * translateAnimation.value),
                          child: widget.iconWidget,
                        ),
                      ],
                    );
                  }),
            ),
          ],
        );
      },
    );
  }
}

1.
2.
3.
4.

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: google chrome 
* Operating system and version (desktop or mobile):windows 64-bit

**Comment by wenkaifan0720** [comment]
Hi @ahmedkameelha. Could you add the error report code? Thank you.

**Comment by wenkaifan0720** [comment]
Issue closed due to inactivity. If you are still experiencing this issue. Please reopen it.
