### ISSUE TITLE
Flutterflow - showing white square box instead of push notifications icon (upper left screen)

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#4890]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In some devices, instead of showing the push notifications icon on the upper left side of the screen, a white square box appears

### Expected Behavior

The expected behavior is to see the proper push notifications icon

### Steps to Reproduce

1. Create an event that would cause the push notification to be triggered
2. See the white square box instead of the push notifications icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TzMmBw412odtF+Kr9bcJR/SAXH1gjargzjuxhcw4aJurmP7QMPsj8ZXFJXMu4d2xUJGH8sGAIpvyLk+PfVvpcCEmIQ75Az5F6ZDvNXmKhV4ihPpeKRGt6M95QBXayyqCOiiQmLtZZcXg771zzH+fIYDPvHp+3OkYnB/j+KrP7jnziHSLrUzhQtmNecCfn

### Visual documentation

![icon notifications](https://github.com/user-attachments/assets/f4900bfc-6eb7-44de-8203-f8ea8c29479b)

### Environment

```markdown
- FlutterFlow version: 5.0.10+
- Platform: Web
- Browser name and version: Chrome Version 131.0.6778.70 (Official Build) (64-bit)
- Operating system and version affected: Windows 11. the issue seems to appear on Android smartphones. E.g. the version in my phone is Xiaomi HyperOS 1.0.20.0.UNREUXM
```

### Additional Information

I am trying to see proper push notifications icons and instead I see a white square box

**Comment by Alezanello** [comment]
Hello!

Thank you for the clarification. Just to confirm, when you mention this issue occurs on certain devices, are you experiencing it in production or when compiling in debug mode?

**Comment by adrfinance** [comment]
@Alezanello I am extracting the APK via Flutterflow, then testing it in my smartphone. So it's release mode.
Here is what confuses me: Flutterflow gives options for Splash Screen, App Launch Icon etc. Why doesn't it give the option to upload push notification icons? I read online that these need to have transparent background to work, or else you get a square white box.

**Comment by Alezanello** [comment]
The Push Notifications icons are generated with flutter_launcher_icons package so it uses the App Launch icon to generate it

**Comment by adrfinance** [comment]
@Alezanello how can you have a proper push notification if the App Launcher icon has a non-transparent background color?

**Comment by Alezanello** [comment]
In this case, it seems like this might be a feature request—to allow for the use of different push notification icons. Would you like me to proceed with submitting this request to the team?

Let me know, and I’d be happy to help!

**Comment by adrfinance** [comment]
Yes

**Comment by Alezanello** [comment]
Perfect! I’ll go ahead and create an internal feature request ticket for this. In the meantime, I’ll close this issue to keep the tracker focused on bugs.

Thank you so much for your valuable feedback!

**Comment by azzar227** [comment]
Hi, 

I would like to make the case that this is not an enhancement request but a bug: the notification icon is not working on some android phones (see screenshots)

There has been a discussion around this issue in the expo community [here](https://github.com/expo/expo/issues/24844)

Would it be possible to implement the same fix ? Or to document to non-technical users how we can self-implement the fix in the context of FlutterFlow ?

Many thanks for your help

![Image](https://github.com/user-attachments/assets/97253466-4378-469f-96bc-bef581135aac)
