### ISSUE TITLE
Unable to open public projects

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#4891]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I open a link to a public project (and others do too), it just keeps loading endlessly.

### Expected Behavior

The project should load and I should be able to clone it

### Steps to Reproduce

1, create a blank project
2, make it public
3, copy the link
4, open an another browser or incognito mode
5, login into a different FlutterFlow account and try to open the link

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siM/lw4xNocBE0LruY8dB/WERJVgmRoEescp/bxIgGIDzPOw+ZPWkMhZBcO7gdH9mfUSmmnod/9L2iIXyUO0DOSysfb5MzZFqZgzLWlmWa5OBCbqge3dtEd5Uf0C538K7nRNCHNttV1oh6mWbf/PLdHPAQeOyIlFISq/LZO4=

### Visual documentation

![CleanShot 2024-11-14 at 16 45 52](https://github.com/user-attachments/assets/88590b8d-0fcb-4933-a703-33a1a355689f)

### Environment

```markdown
- FlutterFlow version: v5.0.11 
- Platform: Mac app and web
- Browser name and version: Chrome, Safari, Brave
- Operating system and version affected: MacOS 15.1
```

### Additional Information

I have some templates available for free and some for sale. However, people have been reaching out to let me know that the projects aren’t opening

**Comment by Alezanello** [comment]
Hello!

You’re absolutely right—this behavior is a bit unusual. I’ll forward it to the engineering team for further investigation!

**Comment by leighajarett** [comment]
Thanks so much for filing this, we're working on it!

**Comment by Unity2Blender** [comment]
While I am also facing the same issue, when I inspected the console while loading the Project url, these errors are encountered. I believe it's an internal issue but do have a look at it.

![image](https://github.com/user-attachments/assets/b8d3dc92-39bd-474a-95fa-28074edbb4be)

**Comment by leighajarett** [comment]
The fix for this will be deployed in the next few hours
