### ISSUE TITLE
null error on filters for fields that don't exist (date time fields specifically)

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#4892]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using a filter to get a number of items from a list of documents. This is a new field in my app so not all documents have this field in firebase. However, instead of the filter conditions defaulting to false when I set the default values, I get a null and the page has a giant red error screen breaking the UI.

### Expected Behavior

If the fields dont exist, the filters should return false without resulting in a breaking change

### Steps to Reproduce

1. add a text widget
2. query a list of documents that have a date time field somewhere
3. set the text to be equal to the number of items returned in a filtered set of documents
4. set the filter to check if the date time field in the list of documents is greater than the date time field in the users document (this is my use case, though even if I compare it to a static date time like the global property current time I still get the error)
5. for testing, make sure both of those date time fields don't exist
6. even with default variable to false, still get the null error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0rNlud0wdCePpEYkXds/CSxJtSOqHTH5YHmH9hk40+ujIjYSWKvZdNTWWQbpM/pBfUxDiIVGRVZS6BqiSQUcnJ+RnIBWD5re3rwhAVfFtL0I16mWUCdiuY3qCf9qOYwx5e6fDbOY=

### Visual documentation

visual of the error

![IMG_2416](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b9a05918-a16d-4c4d-99a3-3981a077816c/2de39a7d-c06a-49b8-b1cc-e2e20a657ad8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iOWEwNTkxOC1hMTZkLTRjNGQtOTlhMy0zOTgxYTA3NzgxNmMvMmRlMzlhN2QtYzA2YS00OWI4LWIxY2MtZTJlMjBhNjU3YWQ4IiwiaWF0IjoxNzMzNDI4MzExLCJleHAiOjMzMzAzOTg4MzExfQ.MlsnL306Hm6kQN9UeKWGD36EG-6ExVR5DT2MGMm7zYY)

The following \_TypeError was thrown building StreamBuilder(dirty, state:
\_StreamBuilderBaseState>#015e9):
Null check operator used on a null value

visual of how the the setup looked for the filter in widget tree

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bad2f7db-6126-4f41-8566-ec3574de6936/8c87b797-b9e4-451f-a6d9-0db98aebb6e1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYWQyZjdkYi02MTI2LTRmNDEtODU2Ni1lYzM1NzRkZTY5MzYvOGM4N2I3OTctYjllNC00NTFmLWE2ZDktMGRiOThhZWJiNmUxIiwiaWF0IjoxNzMzNDI4MzExLCJleHAiOjMzMzAzOTg4MzExfQ.GGi90fuJgSP3meCvBbEJX2e9FEvc2d5KWBoHxmtMtII " alt="Screenshot 2024-11-14 at 8 11 04 AM" width="1252" />

### Environment

```markdown
- FlutterFlow version: 5.0.11
- Platform:Mac Desktop App
- Browser name and version: Chrome latest
- Operating system and version affected: Iphone IOS 18.0
```

### Additional Information

if ever a field is null in the database and a page references that field, results in a complete break in the UI of the app

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this issue to our attention. I will pass it along to the engineering team for review and a potential fix.

**Comment by aaronmt93** [comment]
bumping since stale

**Comment by Alezanello** [comment]
Hello again,

Apologies for the delay in updating you on this issue. While the behavior was previously confirmed, we are currently unable to replicate it. To help clarify and allow further testing, I have created a small project that you can clone and test yourself.

In this project, even if a document contains or does not contain the **X field**, it is still possible to filter those documents and count how many have the **X field**.

You can access the project here:<br>[https://app.flutterflow.io/project/eng-4549-y4o7z3](https://app.flutterflow.io/project/eng-4549-y4o7z3)

Additionally, I have included a short video demonstrating the process. In the video, I add documents with all fields and others with fewer fields, showing how we can filter by the missing fields to retrieve accurate counts.

[Screen-Recording (68).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/13fece0a-def5-4236-8be1-109d9421bf81/99ae2557-829d-4398-834b-3ad37749ee7e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xM2ZlY2UwYS1kZWY1LTQyMzYtOGJlMS0xMDlkOTQyMWJmODEvOTlhZTI1NTctODI5ZC00Mzk4LTgzNGItM2FkMzc3NDllZTdlIiwiaWF0IjoxNzM0NDYxMzk5LCJleHAiOjMzMzA1MDIxMzk5fQ.8mH8JEzDKt_S3pvo5DUK21btMKWogqyq1-VYPkZeWBE)

Please let me know if you need any further clarification or assistance!

Best regards,<br>Alezanello

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
