### ISSUE TITLE
Not authorized to leave project

### ISSUE THREAD

**Issue by MendesCorporation** [FlutterFlow/flutterflow-issues#4894]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In a project that was invited, it is not possible to leave

### Expected Behavior

Leave project

### Steps to Reproduce

1. To be invited a project
2. Leave project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cl8j6yItIvsdA0b6JcvlagjgvHGY5RYIN0cIbcxAYHZPMC+wIZ/f7XFRuTde0Y1VYJ2ejsDsJzN3emvHhEMc6BzedGZhg/81QdQ6WRnm6RLHQO8+0em5/DZlYIXbD56SVsx5CKspsS15m2F+YNu7JZBPrHpjYDUQzHP6LA5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/9237cac9-4f09-42eb-ab15-156717381c13)
![image](https://github.com/user-attachments/assets/7ff43193-91cf-4877-8180-c1f9d310fa02)

### Environment

```markdown
- FlutterFlow version: 5.0.11+
- Platform: Desktop, PWA, Web
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @MendesCorporation,

Thank you for the report! This is a known issue, and it's already on the team's backlog for future work. Please feel free to follow updates on the [original ticket.](https://github.com/FlutterFlow/flutterflow-issues/issues/3698)

Thanks again!
