### ISSUE TITLE
Incompatibility with Supabase .eq Method in SupabaseStreamBuilder with Streaming Enabled

### ISSUE THREAD

**Issue by absolutitecinfo** [FlutterFlow/flutterflow-issues#4895]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello FlutterFlow Support Team,

I’ve encountered an issue after the recent update in FlutterFlow. I’m using a Supabase query with the “Equal To” filter on my table, as shown in the attached image, and I need this query to work with streaming enabled. However, when I run the project, I get a compilation error stating that the .eq method is not defined for the SupabaseStreamBuilder class in the current version of the supabase package (version 2.3.0).

It seems that recent changes in the Supabase package may have removed or modified the .eq method, which is now causing this error with FlutterFlow-generated code when using streaming filters. This issue prevents me from applying filters to streamed data effectively.

Could you please update FlutterFlow to ensure compatibility with the latest Supabase methods for streaming? Alternatively, any guidance on how to resolve this issue within the current setup would be greatly appreciated.

![image](https://github.com/user-attachments/assets/3128724d-2e97-4b66-8197-cec935673ec3)

Thank you for your assistance!

### Expected Behavior

I want to be able to filter my Supabase table that has Realtime

### Steps to Reproduce

n/a

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESk8iA35FgofVG0brqa8d6hQMkQzM6bZI7ku1EdwEhfJysB7QiZMn7ahFLYteafH9AE1Gajnw0/+z3j/HIV/FdPQuVftlYzb5XQQLdeHiuaYzXCrjpOnJ7L+ZRJmqw5p+zvxVCOvt1LlJk3HGICfCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

Hello FlutterFlow Support Team,

I’ve encountered an issue after the recent update in FlutterFlow. I’m using a Supabase query with the “Equal To” filter on my table, as shown in the attached image, and I need this query to work with streaming enabled. However, when I run the project, I get a compilation error stating that the .eq method is not defined for the SupabaseStreamBuilder class in the current version of the supabase package (version 2.3.0).

It seems that recent changes in the Supabase package may have removed or modified the .eq method, which is now causing this error with FlutterFlow-generated code when using streaming filters. This issue prevents me from applying filters to streamed data effectively.

Could you please update FlutterFlow to ensure compatibility with the latest Supabase methods for streaming? Alternatively, any guidance on how to resolve this issue within the current setup would be greatly appreciated.

![image](https://github.com/user-attachments/assets/bf20f0db-cc31-402d-8fb6-38a194b39612)

Thank you for your assistance!

### Environment

```markdown
- FlutterFlow version: v5.0.11 (Launch 13-nov-2024)
- Platform:
- Browser name and version: Google Chrome
- Operating system and version affected:
```

### Additional Information

![image](https://github.com/user-attachments/assets/6f23f175-afd8-48aa-9c64-4a7986766eb0)

**Comment by mmorrison12345** [comment]
I'm experiencing the same error

**Comment by jakals37** [comment]
Same errors.

**Comment by Alezanello** [comment]
Hello!

Thank you for reporting this issue. I wanted to let you know that just before this issue was created, another issue with the same error was submitted: [Issue #4893](https://github.com/FlutterFlow/flutterflow-issues/issues/4893). To ensure we can focus all efforts on resolving this, I will close this issue as a duplicate. I’ll also link both issues so we can maintain proper tracking and keep you updated. No need to worry—we’ve got it covered!
