### ISSUE TITLE
Grey box showing after latest update

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#4896]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/823f8c84-57b6-4e2d-af3e-174c122419d0)

### Expected Behavior

to work

### Steps to Reproduce

..

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcr1z5R1obxY0LXTbfpWoCcXJVx+TL0vsdZ+cwgbf5CvOpYUec/6P1JDXs+9SmxHemKMp14zpt6LuezlVPJdG02rfIRlzJd9WjvhcH26MqmTF7iWP2hRO5tbI26H06arvSZdLvFhL3wNwGGXOO+ucz/fCbLHC0Q8Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/141d948f-bdf0-427c-82c7-b33805c03e2b)

### Environment

```markdown
FlutterFlow v5.0.11+ released November 13, 2024
Flutter version is 3.24.2
```

**Comment by icestormpure** [comment]
![bug1](https://github.com/user-attachments/assets/45796519-965a-4ae7-a29f-1c15554693f1)
Experiencing the same

**Comment by Alezanello** [comment]
Hello!

We released a hotfix about 6 hours ago. I’ve checked your project and did not see any grey boxes. Could you please confirm if this issue has been resolved on your end as well?

**Comment by alih552** [comment]
Hi @Alezanello  same issue still grey box is appearing
![image](https://github.com/user-attachments/assets/0c08bd02-b346-4d59-8263-38f66d7584d8)

**Comment by icestormpure** [comment]
> Hello!
> 
> We released a hotfix about 6 hours ago. I’ve checked your project and did not see any grey boxes. Could you please confirm if this issue has been resolved on your end as well?

It was fixed on my end. Thank you
