### ISSUE TITLE
My labels and values reset to null

### ISSUE THREAD

**Issue by anliben** [FlutterFlow/flutterflow-issues#4898]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I need help, my applications are used in production, this causes serious harm to my customers. help

https://www.loom.com/share/306958cb13244b4f85fb668f6b67a3c3

### Expected Behavior

I open my application and it is normal, as I left it, so I can continue programming

### Steps to Reproduce

1. open any projetct
2. https://www.loom.com/share/306958cb13244b4f85fb668f6b67a3c3

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

all widgets, all labels

### Visual documentation

https://www.loom.com/share/306958cb13244b4f85fb668f6b67a3c3

### Environment

```markdown
- FlutterFlow version: v5.0.10+ released November 13, 2024
Flutter version is 3.24.2
- Platform: Web and Android
- Browser name and version: Chrome - 130.0.6723.116
- Operating system and version affected: Ubuntu 24.04.1 LTS x86_64
```

**Comment by Alezanello** [comment]
Hello,

I’m sorry to hear you’re experiencing this issue. For situations like this, please reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They will be happy to assist you further.
