### ISSUE TITLE
Add info icon next to the "Download APK" button in FF desktop app (enhancement)

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#4899]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It downloads the APK but some users might be confused where it was downloaded so I suggest adding an info icon next to it that displays the path where it was downloaded.

### Expected Behavior

add info icon

### Steps to Reproduce

download apk

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShfLl05dgotdc7ofQLflAhR4mJkQ5a7lFle1TaAA3F4zwEJwpWvnSTHpbZseqT1ZlemGKmlgF+vPGkofxUPBcHAyHbqI41rt2EgHJXnqiV7a2PrWaf38nHfJMJ3GB16e0kRZvCMdfW11pig/GSw==

### Visual documentation

![image](https://github.com/user-attachments/assets/c8629a98-5861-42ad-8298-4a74a884695d)

### Environment

```markdown
FlutterFlow v5.0.11+ released November 13, 2024
Flutter version is 3.24.2
```

**Comment by Alezanello** [comment]
Hello!

The file is downloaded to the folder you’ve specified as your browser’s download location. This behavior is determined by your browser settings and is not controlled by FlutterFlow. The download will go to the folder you’ve chosen for all your browser downloads.
