### ISSUE TITLE
Backend query loading widget can't select component

### ISSUE THREAD

**Issue by jeffcyw95** [FlutterFlow/flutterflow-issues#4900]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When choosing component in backend query loading widget, I am not able to select a component that I want to use.
![image](https://github.com/user-attachments/assets/c9e032a9-855d-48ce-be35-d5e08c1e08db)

### Expected Behavior

Should be able to select a component to be use for backend query loading widget

### Steps to Reproduce

Create a backend query and change the loading widget to component and choose a component

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPXfikSEpWZ9+kTHxcL2CJvGUyw8KNhePAA+UoFE6qY7p7wc9+exXweF+7RL6kOrioT0Z9NNFJJVy41sCFvh4nBMlhdV4C1GGUA/DKXg/sJYTsNlQkD+WYWZLOp3+qQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/user-attachments/assets/6f246f02-7a15-469a-a17c-d08228487426)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue on my end. There is an option labeled “Select Component,” and when you tap on it, a dropdown menu should appear with all possible components.

**Comment by jeffcyw95** [comment]
Hi there,

Yes there is option to Select Component and it does shows all possible c

https://github.com/user-attachments/assets/ccb1d383-6dc2-4bad-b914-744b8145f330

omponent. But it just can't be chosen and return error when you choose any of them. I have attached a video of the process.

**Comment by abtris-lab** [comment]
We also have faced the same issue after the latest update of flutterflow.
Basically we want to show a custom loader component in backend query loading widget.
But after selecting the component, nothing happens and if you copy the element and paste it, it's showing unset. So the components are not getting selected in backend query loading widget.

**Comment by ibiolm** [comment]
We also have the same problem.

**Comment by lleo132** [comment]
I have this problem too in all my projects

**Comment by PoojaB26** [comment]
Just FYI, this is a duplicate of #4922 and you can track the status of this issue from the other ticket.
