### ISSUE TITLE
Flutterflow ui crashes in the editor

### ISSUE THREAD

**Issue by Maazkhalid47** [FlutterFlow/flutterflow-issues#4901]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The flutterflow ui crashes in the editor and shows grey screens on widgets and as well as action flo properties panel.

### Expected Behavior

The flutterflow ui should show the widgets properly

### Steps to Reproduce
THESE ARE THE STEPS TO REPRODUCE ACTION FLOW PROPERTIES PANEL CRASH ONLY
1. Create a new page
2. Define POST API call with variables
3. Call the api onPageLoad of created page
4.Attach API response to some widget
5. Disable api call

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehvH1z492tbxZ+rXyKu4xgQMwJ0QlUIInj+0bWRMhfYzmEYoTd+PRflpLYte+THx2MFCjqzkJw9LUjYX1KPAnCzGWQNQ++ZRXQTzycFKQMbbQEruaQUF6MNJVCWKD0auRsRR+WPhvWV4h2l6INvCrG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/bd90f4ba-711d-4ce6-8b47-ad53f93e9a23)
![image](https://github.com/user-attachments/assets/d6bc843d-4320-437d-9047-bb700e587027)
![image](https://github.com/user-attachments/assets/c64c2f9a-cb08-4831-af10-76d020573d62)
<img width="1280" alt="qqq" src="https://github.com/user-attachments/assets/b531bcc8-6365-428f-9c9e-eec801938e8d">

### Environment

```markdown
- FlutterFlow version: 5.0.11
- Platform:Desktop windows and MacOs 
- Browser name and version:N/A
- Operating system and version affected: Windows 11 & macOs monterey v12.5
```

### Additional Information

The app compiles successfully but ui creation gets disturbed like this, you gotta remove the widgets and add them back to overcome this problem.

**Comment by Alezanello** [comment]
Hello!

We released a hotfix about 6 hours ago. I’ve checked your project and did not see any grey boxes. Could you please confirm if this issue has been resolved on your end as well?

**Comment by Maazkhalid47** [comment]
The grey boxes were not always here they appeared this morning, also the flutterflow ui stopped crashing since I submitted the issue, but the action flow's properties panel is still having that grey screen upon disabling actions, just like I have shown in the visual documentation above

**Comment by Maazkhalid47** [comment]
NOTE: THIS IS ONLY HAPPENING WITH FLUTTERFLOW UI NOT IN THE ACTUAL APP, APP WORKS FINE
The issue hasn't been fixed yet, as you can see in the images

![image](https://github.com/user-attachments/assets/2ec0f7dd-231d-4ff6-805b-bbce9c6123b2)

this is a list of dynamically generated components here, here is what the component looks like

![image](https://github.com/user-attachments/assets/7e02091d-b680-41e0-a04e-bc5fbaa4c0ae)

The greyed part is basically a list of dynamically generated radiobuttons, with the options taken from the components parameter, converted to a custom data type, then accessed.

![image](https://github.com/user-attachments/assets/eb8610ad-2ee1-4cda-a9ad-11e73d290e75)

Here is the setting on this radio button widget

![image](https://github.com/user-attachments/assets/0caec3e1-7fb6-4786-b740-33ca3af5853a)

And this is the state when I removed the dynamic values
![image](https://github.com/user-attachments/assets/dffee8a7-6ab0-48e0-a396-30aee2d4be67)
@Alezanello

**Comment by Alezanello** [comment]
Hello!

We deployed a more recent fix yesterday afternoon. Could you confirm if this issue is still occurring in your project?

If it persists, please reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They’ll be able to review your project more closely to identify and resolve the issue.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
