### ISSUE TITLE
Supabase Streaming for ListView stops streaming with a single filter

### ISSUE THREAD

**Issue by the-digital-pro** [FlutterFlow/flutterflow-issues#4903]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Simple ListView which has a non-single query. Without a filter streaming works perfectly. As soon as I add a filter. i.e booked=true realtime updates do not update.

### Expected Behavior

I would expect to see the ListView updated with any changes within the realtime Supabase database.

### Steps to Reproduce

1. Setup Supabase project and table with sample data
2. Enable realtime on your table
3. Setup FlutterFlow for Supabase v2
4. Add a ListView
5. Add a query and filter on 1 table column
6. Delete row in the database

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT9XiuflxIt1pbxK0KX6cfpviiovIjt9RLxMm9V+ZwsdCLbqBI13P/TBTFFWWbS/T2w7IWGN+WcepqyOvdrIMeY5HxeWfLZm+c9ASQCVJWOWbJSJErWJPmJ/J+hhflS/yre3pgpCWepucVIi7XGQAunKFyvaMLnhIkczAMqaOdjU+VKYLSTrMTpZwW07HxPXBtgcZhOxxJPK6asBlI/S/ol8qBVXzoPSwtX1TBKTWVk=

### Visual documentation

No visual needed

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Mac M3 Pro
- Browser name and version: Google Crome but using Local Run ios Simulator
- Operating system and version affected: Sequioa 15.0.1
```

**Comment by the-digital-pro** [comment]
Just want to add that I am seeing no errors. It simply just does not update.

**Comment by jakals37** [comment]
I have same issue.

**Comment by SlvrB** [comment]
I have same issue

**Comment by Alezanello** [comment]
I can confirm this issue and will escalate it to the engineering team for a fix.

**Comment by glgh** [comment]
hi @the-digital-pro - does this happen only when deleting an existing row, but not when inserting a new row? If so this is a known limitation with the Supabase streaming API: [Delete events are not filterable](https://supabase.com/docs/guides/realtime/postgres-changes?queryGroups=language&language=js&queryGroups=database-method&database-method=dashboard#delete-events-are-not-filterable).

**Comment by the-digital-pro** [comment]
@glgh I'm puzzled to why you have closed this issue. If I have a row in my database which is boolean and it is set to true. InFF, I have a standard filter on my query which returns back all records that are true then you would expect to see these in your listview. If I then go in Supabase and mark one of these records as FALSE you would expect to see this one record removed from the ListView. This is not the case. It remains there.

**Comment by glgh** [comment]
hi @the-digital-pro, I appreciate the detail you shared - unfortunately this is a supabase streaming API limitation and it affects both 1) deleting rows and 2) updating rows such that it no longer meets the filter condition (<- this part is not clearly documented unfortunately) -- in each case the row would remain even though the expected behavior is it will go away. This also affects both their [stream](https://supabase.com/docs/reference/dart/stream) API and [realtime channel](https://supabase.com/docs/guides/realtime?queryGroups=language&language=dart) API in our internal testing. 

This is only a limitation when filters are enabled -- without filters it should work fine.
