### ISSUE TITLE
Code Expressions multiple conditions issue 

### ISSUE THREAD

**Issue by vinaykoulur** [FlutterFlow/flutterflow-issues#4906]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://github.com/user-attachments/assets/2ae756bb-925f-4908-9b8a-f76f2cf03b8f

OR(||) operation behaving as AND(&&) and vice versa may be true.

### Expected Behavior

Expected behavior has to be exactly opposite of the current behavior.

### Steps to Reproduce

refer video

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESl/Llz5dgrsNB17XTKuxQhQAkH1x/bZJEl9cbaEkcF7b2BJYXOur+VExuT9SqTVZYMGCKkmAKpdWNuNrXUvk4FzGWeINo+rluSjnLfGW6MaaQBpGzdHFtHtxhIVSB0cGzoyVdNvZoLy0Aw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

refer video from current behaviour.

### Environment

```markdown
- FlutterFlow version:  v5.0.10+ released November 14, 2024
- Platform: any
- Browser name and version: chrome latest today
- Operating system and version affected: web win 11
```

**Comment by vinaykoulur** [comment]
multiple conditions within code expression OR(||) operation behaving as AND(&&) operation.

**Comment by Alezanello** [comment]
Hello!

Everything appears to be working as expected. I created a small project demonstrating the conditional logic with random strings, which you can review using your example. In the scenario shown in your video, it seems you may be using the "OR" condition, but it looks like "AND" might be more appropriate.

Project: [https://app.flutterflow.io/project/qa-3052-pjae22](https://app.flutterflow.io/project/qa-3052-pjae22)

Video:

[Screen-Recording (50).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f8c84ce6-930b-4297-b8fb-919c501fd1d8/45e65f46-763b-4456-bf5b-2b0021e64ba9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOGM4NGNlNi05MzBiLTQyOTctYjhmYi05MTljNTAxZmQxZDgvNDVlNjVmNDYtNzYzYi00NDU2LWJmNWItMmIwMDIxZTY0YmE5IiwiaWF0IjoxNzMxNzA3NDU5LCJleHAiOjMzMzAyMjY3NDU5fQ.xg16rWaLf4EaQvBccQxdMQ_KOBoJvTOZ4nnAWRVJJic)

**Comment by vinaykoulur** [comment]
sorry I'm not talking about single conditions in code expressions. I think you have not understood the issue .Watch the video again ,everything is mentioned in the video try to reproduce as it is and I also have given access to project. ,Try again.

**Comment by Alezanello** [comment]
My video also have multiple conditions in code expression, only the first two are single conditions, you can clone the project I shared and change as you please to show the error you have

**Comment by vinaykoulur** [comment]
Got it. Button gets disabled only if the code expression returns Boolean value "true". I thought in flutter flow disable button feature ,the code expression should return "false" in order for the button to get disabled. Sorry I'm from programming background and we usually keep button disabled until the necessary conditions becomes true. Once conditions are true we enable the button. Think I should use a not operation. Thanks and let me know if I've understood it correctly.

**Comment by Alezanello** [comment]
That's correct!<br><br>The button will disable if the condition that you set is True!
