### ISSUE TITLE
Error message "value is not properly set" on non-required component parameters

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#4908]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This issue is almost identical to #1348.
The ticket is closed as "fixed", but it is not.
Flutterflow complains if a component parameter is not set, even when the parameter is set to be **not required**. 

### Expected Behavior

It should build without an error message.

### Steps to Reproduce

1. Create a component with a non-required parameter
2. Use it in your page
3. Leave parameter empty
4. See the error "parameter not set properly"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzPHq24VIscsA14SJc+0w9TgROUccTL4zlO1HcxAYGO/yPbJ/OeClXBFCcNe5YWlhHFaZgj4zpqHTiuOWIOwpNQ2BG75MzKp2cAzwXXq8R8m7C7irOXcnRZlgfVCh07aF2gklIvhaV04g2nGmOOfIbHLYJ5+/Zwh9f6PHaOI=

### Visual documentation

<img width="564" alt="image" src="https://github.com/user-attachments/assets/e5b11952-3b70-4044-85a2-86e2972f07a8">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.12 released November 15, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: MacOS Sequoia
```

**Comment by Alezanello** [comment]
I'm sorry, but I wasn't able to replicate the issue. I created two components that request parameters, none of which were marked as required.

In the first component (compX), I did not use the parameters, while in the second component (compY), I utilized the parameters within text widgets, with default values set in case the parameters were null. In both cases, it did not prompt me to fill in these values.

You can review it here: [Project QA-3054](https://app.flutterflow.io/project/qa-3054-2teew3)

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
