### ISSUE TITLE
A Firebase-field, that stores the timestamp as number, stops listview etc from working

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#491]
## Expected behavior (required)
When displaying a firebase-collection in FF without filter it should show all the documents, e. g. in a listview. Incompatiblity-issues (like a timestamp-field being actually a number in firebase should only not show this field.

## Current behavior (required)
When a field in a firebase-collection is set up as "Timestamp" in FF, but somehow it has a number in it (e. g. through the function Date.now(), in my case in Rowy, which stores the timestamp as a number), FF doesn't display this document in the listview - or just partly.

## To Reproduce (required)
1. Create documents in a firebase-collection with a field that get's the current date with the javascript-function "new Date()"
2. Define this collection in ff and give this field the datatype "Timestamp"
3. Create a listview and show all the fields

This problem is easily reproduceable and happens every time.

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")
IT4Wl8nl3891pbxH1rXuY+9VnjwWQ2Yha788msN+URA2GO/1OrYPXfnRalhoTN+idGNqL2eKmnky/tbMkobuA+UpNS+uGr5JzqlqSz3gTkmub6a7O7maXXEmJ8UGSSDy

## Context (required)
I want every document to show in the listview and not that the field breaks ff.

## Screenshots / recordings
![Unbenannt](https://user-images.githubusercontent.com/1053176/218788071-931180d1-d4a9-4dd0-99d0-fb3c9af43659.JPG)

## Your environment

* Version of FlutterFlow used: current (2023/02/27)
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Edge Version 110.0.1587.57 (Offizielles Build) (64-Bit)
* Operating system and version (desktop or mobile): Windows 11

## Workaround (kind of)
My solution was - with the help of the Rowy-team - to write the timestamp into Firebase like so:
```
  const date = new Date()
  const ms = date.getTime()
  const { Timestamp } = (await (async () => await import("@google-cloud/firestore"))())
  return Timestamp.fromMillis(ms)
```

**Comment by aemelyanovff** [comment]
@webwurm Please update the issue according to the bug report template (with steps to reproduce, bug report template, etc.)

**Comment by webwurm** [comment]
I provided addition info in the original post.

**Comment by aemelyanovff** [comment]
This is working as intended - when FF can't deserialize a record because of a type mismatch or any other reason, it ignores it. It shouldn't guess what value to use when the actual value can't be deserialized.

I can only suggest avoiding situations when a timestamp "somehow it has a number in it" :-)
