### ISSUE TITLE
Custom Domain not working for www subdomains

### ISSUE THREAD

**Issue by geret1** [FlutterFlow/flutterflow-issues#4913]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When user with a custom domain try to access www.mydomain.com redirects to mydomain.com instead of keep in www

### Expected Behavior

Keep www subdomain.

### Steps to Reproduce

1. Create a custom domain with www support
2. Configure DNS records as suggested in FF (even proxy CNAME configuration that is not explained in the docs).
3. Try

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Ll8ZNIvulA187pbfowtDg7Q1g/TL07ttYbZxUjIuPtBJh/f8/BP01oQvW7dENhHFGLjToH0MLRkvDhDvA6aDeZR4B51od2TwvNTXq8Sq64ELuafHEkJJpWGhGZ1qaJ3xJ/AO5qLkYM12CQIOjIEzfcGZ+/Zwh9f6PHaOI=

### Visual documentation

<img width="232" alt="Screenshot 2024-11-16 at 09 30 24" src="https://github.com/user-attachments/assets/6598ccd6-c5ca-4bc1-a58f-1391c0fa77bc">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.10+ released November 15, 2024
- Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome (latest)
- Operating system and version affected: OS X
```

### Additional Information

Documentation and UI is very poor here explaining actually nothing so users cannot help on that task.

**Comment by Alezanello** [comment]
Hello!

You can set up the custom domain directly with the **www** subdomain. This means the A record in your DNS settings would be [**www**](http://www)**.<yourdomain>.com**, and you won’t need to configure a CNAME record.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ea33d0ea-fc5b-42c5-bd27-2bb41552a525/0af11560-643a-42c5-a8b8-9c8c62056dba?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYTMzZDBlYS1mYzViLTQyYzUtYmQyNy0yYmI0MTU1MmE1MjUvMGFmMTE1NjAtNjQzYS00MmM1LWE4YjgtOWM4YzYyMDU2ZGJhIiwiaWF0IjoxNzMyMTExNzQ5LCJleHAiOjMzMzAyNjcxNzQ5fQ.TMDWQr90RgOOYUMX4_BgKtwsPAG114WL99dRiQNSwbU " alt="image.png" width="623" height="203" />

However, please note that even with this setup, the browser might display the domain without the **www** prefix until you double-click on it. I’ll share a GIF below to demonstrate this behavior.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a0f1a344-10d3-49d1-8272-7f7ccfc3b595/42bba48b-60fe-4d51-9421-9d6e141b46ec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMGYxYTM0NC0xMGQzLTQ5ZDEtODI3Mi03ZjdjY2ZjM2I1OTUvNDJiYmE0OGItNjBmZS00ZDUxLTk0MjEtOWQ2ZTE0MWI0NmVjIiwiaWF0IjoxNzMyMTExNzQ5LCJleHAiOjMzMzAyNjcxNzQ5fQ.cCE0xARGRGVE11CAzCzCH4pVWXEACcsy0VXqHr6csas " alt="domain.gif" width="1420" height="889" />

Best regards,<br>Azanello

**Comment by geret1** [comment]
Unfortunately developer tools are saying a different thing (screenshot attached). 
<img width="1685" alt="Screenshot 2024-11-20 at 23 21 03" src="https://github.com/user-attachments/assets/8425abfc-4a41-4d8f-a7cb-d8d8ffe63c13">

An initial request is made to www subdomain then, a 301 response code redirects to the A record. FF seems configured properly considering www subdomain (screenshot attached)

<img width="711" alt="Screenshot 2024-11-20 at 23 26 44" src="https://github.com/user-attachments/assets/9736f97b-d944-4348-9fd8-90703b8fafe3">

However, I don't understand why FF suggest to create a CNAME record that points out to [*].custom-domain-proxy.flutterflow.app. Why do you need a proxy there?

**Comment by geret1** [comment]
Any updates here?

**Comment by paulperez-dev** [comment]
Hi @geret1,

Apologies for the delayed response. We’re taking a closer look into this and will share our findings as soon as possible.

**Comment by paulperez-dev** [comment]
Hi @geret1,

After reviewing your report, it appears the issue may be related to the absence of an SSL certificate for your domain.

You might find this reference helpful: [Nginx WWW Redirect to Non-WWW Throws Cert Error](https://stackoverflow.com/questions/54411912/nginx-www-redirect-to-non-www-throws-cert-error).

**Comment by geret1** [comment]
So you are telling me that, FlutterFlow implements Custom Domain functionality (screenshot attached) with support to www subdomains, with the intention to force learning and using reverse proxies to avoid SSL certs mismatch issues... and all that after 3 weeks... haha got it!

<img width="1397" alt="Screenshot 2024-12-04 at 07 28 12" src="https://github.com/user-attachments/assets/ea23367e-94e5-4097-8837-ffc63116a84a">

P.S.: TLD domain works perfectly with a SSL certificate provided by FlutterFlow by using Let's Encrypt :)

**Comment by paulperez-dev** [comment]
Thank you for your feedback! I’ll share it with the team to help improve the experience. Let me know if you have any other concerns.

**Comment by geret1** [comment]
Fix the issue that you really have.

https://www.ssllabs.com/ssltest/analyze.html?d=taletwin.com&latest 

There is no SAN (Alternative Name) in the generated certificate that you provide to customers so there is no option to use www subdomains with a valid certificate.

Just to inform you that Let's Encrypt supports multidomain certificates and able to use SAN with www subdomain. It's free.
