### ISSUE TITLE
Deployed web app malfunctioning - supabase null filters

### ISSUE THREAD

**Issue by Xupdawg** [FlutterFlow/flutterflow-issues#4914]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the recent supabase update, some page on the web app shows blank white pages when they clearly work before. This is the debug error it comes up it. Checked the custom action, there seems to be no problem at all.
The flutterflow UI also seems to be having a problem. All variables are not showing

### Expected Behavior

All pages should be working like they were before.

### Steps to Reproduce

1. Open any page

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gzMrq25BIm9tF7rqBYO9almUvOUQ8R700sd4bGA0dCJzuPLMQdvXsRExWXumkd2xLekSmmXMF/vDnidnTDvI5BzWcfKY61qhMeDnJQmK6a5OBPamadHcnHe9XIUeP5J+zkB17KrNZLXwl7DqACdy/QjLUNu63IndISq/LZO4=

### Visual documentation

1

### Environment

```markdown
- FlutterFlow version: v5.0.11
- Platform:Web
- Browser name and version: Chrome 130.0.6723.117
- Operating system and version affected: Windows 22H2
```

### Additional Information

The app has been deployed for public use. This error hinders customers.

**Comment by paulperez-dev** [comment]
Hi @Xupdawg!

Thank you for bringing this issue to our attention. Could you please provide a test account along with the list of screens where you’re encountering this error? This will help us investigate the problem more effectively.

Thanks so much for your cooperation!

**Comment by Xupdawg** [comment]
Hello @paulperez-dev @wenkaifan0720 I'm still relatively new to Flutterflow, how do I provide a test account to you directly. Or do you mean login details

**Comment by paulperez-dev** [comment]
Yes, login details and the screens where you are facing the issue.

**Comment by Xupdawg** [comment]
@paulperez-dev Can this be sent privately to you? If yes, through which means

**Comment by glgh** [comment]
Update - this has been fixed and will be released soon
