### ISSUE TITLE
The dashboard doesn't loading  just show the Flutterflow logo

### ISSUE THREAD

**Issue by osmamog** [FlutterFlow/flutterflow-issues#4917]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The dashboard doesn't just show the Flutterflow logo
![Screenshot (366)](https://github.com/user-attachments/assets/fbd2ffa8-c17b-4cc5-acd0-e0686446a6dd)
![Screenshot (369)](https://github.com/user-attachments/assets/73011634-7500-47a5-85e3-1b2bfbf93746)

### Expected Behavior

The dashboard doesn't just show the Flutterflow logo

### Steps to Reproduce

The dashboard doesn't just show the Flutterflow logo
dont show any thing 
error
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

16T13:34:52.381Z]  @firebase/firestore: Firestore (10.11.1): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds. This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

### Visual documentation

The dashboard doesn't just show the Flutterflow logo

Uploading ‪FlutterFlow - Google Chrome‬ 2024-11-11 17-22-27.mp4…

### Environment

```markdown
- FlutterFlow version: last verison
- Platform:flutterflow
- Browser name and version:chrome + firfox
- Operating system and version affected:
```

### Additional Information

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by paulperez-dev** [comment]
Hi @osmamog! Are you still experiencing this issue? The error says it was a connection timeout.
