### ISSUE TITLE
Choice Chips Filter + Listview + Supabase

### ISSUE THREAD

**Issue by wesleylopes** [FlutterFlow/flutterflow-issues#4919]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created two tables and then a view linking them on Supabase to retrieve some information. When I apply a filter using contains in the query along with Choice Chips, I get an error, and I can't make the ListView work at all. It shows a red screen. Can someone help me?

### Expected Behavior

The ListView should display the filtered results based on the contains query applied with the Choice Chips input. The filtering should work smoothly without errors.

### Steps to Reproduce

created collumn
added row and choice chips
added column and listview with filter contains chip choices
Error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

r

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/368a65ff-2d68-4cc3-aeee-2e5492ce6970/6178930a-38ef-47d6-8998-0296cbbd1135?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNjhhNjVmZi0yZDY4LTRjYzMtYWVlZS0yZTU0OTJjZTY5NzAvNjE3ODkzMGEtMzhlZi00N2Q2LTg5OTgtMDI5NmNiYmQxMTM1IiwiaWF0IjoxNzMxOTU5MDU3LCJleHAiOjMzMzAyNTE5MDU3fQ.HrA2nDWjig9fNFYD7HMeZ8heyBHzz6SEHCxpT2kWFLo)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1ab067aa-01e9-4b6f-997b-925aac9d1b23/c69cba8d-5917-4804-8444-64087ea2b69d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYWIwNjdhYS0wMWU5LTRiNmYtOTk3Yi05MjVhYWM5ZDFiMjMvYzY5Y2JhOGQtNTkxNy00ODA0LTg0NDQtNjQwODdlYTJiNjlkIiwiaWF0IjoxNzMxOTU5MDU3LCJleHAiOjMzMzAyNTE5MDU3fQ.qq6y0V9ofnmI0-q9lb38JirJgGA6rwOtIWxMQdrF7GY)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0e04292b-2bba-4161-85e7-b63f68875c67/359bacd4-15d8-4aa5-bd64-1f16a5ecc859?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZTA0MjkyYi0yYmJhLTQxNjEtODVlNy1iNjNmNjg4NzVjNjcvMzU5YmFjZDQtMTVkOC00YWE1LWJkNjQtMWYxNmE1ZWNjODU5IiwiaWF0IjoxNzMxOTU5MDU3LCJleHAiOjMzMzAyNTE5MDU3fQ.pxLtxjdLlwEpf3UD23L4XeI0ZCdHUAsA6RnHe3LBcao)

### Environment

```markdown
- FlutterFlow version:
- Platform:
- Browser name and version:
- Operating system and version affected:
 
- FlutterFlow v5.0.10+ released November 15, 2024
- Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome
Versão 130.0.6723.117 (Versão oficial) (x86_64)
- Operating system and version affected: MacOs Sequoia 15.0.1
```

### Additional Information

*No response*

**Comment by wesleylopes** [comment]
.

**Comment by paulperez-dev** [comment]
Hi @wesleylopes! It looks like the issue is related to the generated code. I’ll escalate this to the engineering team for further review. Thank you for bringing this to our attention!

**Comment by paulperez-dev** [comment]
Hi @wesleylopes! Do you have any testing credentials I could use to verify the issue on my end?

**Comment by wesleylopes** [comment]
> Hi @wesleylopes! Do you have any testing credentials I could use to verify the issue on my end?

Hello @paulperez-dev  supabase or flutterflow?

**Comment by paulperez-dev** [comment]
To access the app created in Flutterflow, not the Flutterflow credentials.

**Comment by wesleylopes** [comment]
> To access the app created in Flutterflow, not the Flutterflow credentials.
https://shema.flutterflow.app user: infor@infor.com pass: dd03mm02

**Comment by wesleylopes** [comment]
https://app.flutterflow.io/project/shema-app-2nkjbb?tab=pageSelector&page=agendas

**Comment by wesleylopes** [comment]
Hello

**Comment by rzambroni** [comment]
Hi @weslseylopes,

Thanks for reporting this!

We reached out to our engineering team for clarification, and it seems that the Supabase filter can no longer be null. To address this, you’ll either need to set an initial value (e.g., by assigning a default option for the choice chip) or conditionally build the query to handle this case.

Hope that helps!
