### ISSUE TITLE
API Calls - Default variable values not used during testing

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#492]
## Expected behavior (required)
The default values set in the variable to be used when testing the api.

## Current behavior (required)
Default value is not used

## To Reproduce (required)

1. Create api call
2. Create variable
3. Test it
4. See that it's not there

## Context (required)
Test api calls with defaults

## Your environment

* Version of FlutterFlow used: Beta 3.1
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome 110
* Operating system and version (desktop or mobile): Desktop

**Comment by organicnz** [comment]
Hi @johnbhiggins7. Thanks, John for adding this issue 🙂

Could you pls provide more details about which API endpoint you're using? Also, a widget tree, screenshots or a video clip would be very helpful :)

**Comment by aemelyanovff** [comment]
Fixed in the next release.
