### ISSUE TITLE
App doesn't show in large screen

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#4920]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app bar in one particular page doesn't appear in large screens
![Screenshot_2](https://github.com/user-attachments/assets/b0be5d62-f475-4ef1-a5a0-df1fb351807a)

### Expected Behavior

It should appear
![Screenshot_3](https://github.com/user-attachments/assets/a54ba0c2-1396-4141-8738-78a059a7fc6b)

### Steps to Reproduce

1-Login in the app
2-Click in the Bell icon in the home appbar
3-Put the app in large screen
![Screenshot_4](https://github.com/user-attachments/assets/68314232-a86a-4fb7-9e8c-0f573c63bf08)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPHq2491xLRF+KnxYcFarygUCUMfWI0/ld5EZwEhfJSvBLQhd87RUxNLYtejTQhleE2ipFsz3PzIifHPJvQqB02sbKJOyK5XQRaXbHuVRpi7DKu0YmpRN/1NBWKYyJivqgpQC7dsW1IO61OqO/CrG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot_4](https://github.com/user-attachments/assets/6d01555d-5155-4fe4-bb41-1a643b26d1cd)

### Environment

```markdown
FlutterFlow v5.0.10+ released November 15, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @ricardocgs! It looks like the app bar is currently disabled for large screens in your configuration. Could you please review your settings to ensure everything is set up as expected?

Ref: 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f656752c-c58e-4a48-b89c-a6a06bbfc4df/5ab964c6-11de-4c64-a5d2-c325e13b8b44?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNjU2NzUyYy1jNThlLTRhNDgtYjg5Yy1hNmEwNmJiZmM0ZGYvNWFiOTY0YzYtMTFkZS00YzY0LWE1ZDItYzMyNWUxM2I4YjQ0IiwiaWF0IjoxNzMxOTgyMjk4LCJleHAiOjMzMzAyNTQyMjk4fQ.DeYxYkGDoDnZEyGHE29zczP1_SEhgT8WNphQ7_RHNl4 " alt="image.png" width="676" height="338" />
