### ISSUE TITLE
iOS Screenshot size is wrong

### ISSUE THREAD

**Issue by abhibalani** [FlutterFlow/flutterflow-issues#4924]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

App store expects screenshot size in 1320 x 2868px, 2868 x 1320px, 1290 x 2796px or 2796 x 1290px sizes. 

Currently the 6.7 inch screenshot generated by flutter flow is of size 1288x2794. The screenshots are getting failed to upload to appstoreconnect.

The name of the directory of the screenshot is iPhone 6.7_ Display - 1290x2796.

Same is try for 6.5 inch screenshot sizes.

### Expected Behavior

The screenshot size for 6.7 and 6.5 should be from  1320 x 2868px, 2868 x 1320px, 1290 x 2796px or 2796 x 1290px 

### Steps to Reproduce

Create a new page
Export it as iphone screenshot

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9VoD0sQzN+aJc0sd4bGA0dCJzuPLMQdvWkYk9WZOHnTQk7I0Smmk8Dps7Gj4fhMvddaEisRapZzLhuEjnLfEaWa5OBDJeKX3QnEf9Tf2Kg56S02iZDJsdYS3ws7FyMDOTKaD3bJpC0IlFISq/LZO4=

### Visual documentation

![Screenshot 2024-11-18 173553](https://github.com/user-attachments/assets/bf8fd109-a8f9-4159-b8cc-055caed9aeea)
![Screenshot 2024-11-18 173546](https://github.com/user-attachments/assets/37878fd5-14c6-4de1-830c-5c47f3ea5dab)

### Environment

```markdown
- FlutterFlow version: iPhone 6.7_ Display - 1290x2796
- Platform: Web
- Browser name and version: Chrome 
- Operating system and version affected:  Windows 11
```

**Comment by paulperez-dev** [comment]
Hi @abhibalani! Thanks for bringing this to our attention. I’ll forward this to the Engineering team.

**Comment by abhibalani** [comment]
Just FYI it is happening for all iOS screenshots. @paulperez-dev

**Comment by paulperez-dev** [comment]
Hi @abhibalani! I’m closing this issue as it is already being tracked here: [GitHub Issue #3962](https://github.com/FlutterFlow/flutterflow-issues/issues/3962). Please refer to that ticket for updates.

**Comment by abhibalani** [comment]
@paulperez-dev  That 1.5 months old bug is still open.  Any ETA for the fix?

**Comment by paulperez-dev** [comment]
Not at the moment, unfortunately.
