### ISSUE TITLE
JSON is broken when modified by a function

### ISSUE THREAD

**Issue by SebyOnGitHub** [FlutterFlow/flutterflow-issues#4925]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a state (JSON 1) is set to another JSON state (JSON 2), the first JSON state (JSON 1) is also changed.
While we are setting JSON 2, we are changing the JSON a little bit with a function. 
But the changes from that function also change JSON 1, even if we are only using a set state for JSON 2.

### Expected Behavior

The state of JSON 1 should not be changed, only JSON 2 should be changed because we are only setting the state of JSON 2.

### Steps to Reproduce

1. New Project / New Page
2. Create two JSON page states. You can name them jsonState1 and jsonState2.
![image](https://github.com/user-attachments/assets/a9798a54-abb9-4c4c-af65-7eed6fd3be6d)

3. Create logic to set jsonState1 (I did this by using a TextField and a button that inserts the string into jsonState1).
![image](https://github.com/user-attachments/assets/dc7a0778-2112-422a-b5cf-ecdead0e6a03)

4. Create another button that inserts the value of jsonState1 into jsonState2.
It is important that we use a function in between that changes something. This example function removes the key "name".
Here we can see that we only change the state jsonState2. Later we will see that not only this state is changed.
![image](https://github.com/user-attachments/assets/37d19d5e-8f52-4498-a0c6-d5ff14450b52)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTls/l7c92rsMA+KrQYexKpDgWGUMdXOczitVEew4bCIj4BLMQOuD7fk1uUuqzaH1EBFCWrHgCptbHj/DPEe1dBy2ZRoBJ/6tIWBPPbEyQM7aNCpDpZX8lDcBWIH6y4aSRhCQkB7dZdGAa3zuQFefITT+Cf9qOYwx5e6fDbOY=

### Visual documentation

Here is what happens when we use this example:
After compiling it looks like this, both States are empty.
![image](https://github.com/user-attachments/assets/23e9b5a8-ca0b-4e55-bc25-4947bc70e69a)

Then insert a sample JSON like this:
![image](https://github.com/user-attachments/assets/45bebbd2-3f58-4d96-a923-f8589fca3853)

Then press the first button and notice that jsonState1 has changed:
![image](https://github.com/user-attachments/assets/037b8b4e-4739-485e-b668-cfb26e96c15b)

So far, everything is working as expected. Now when we press the second button and try to insert jsonState1 into jsonState2. This also works, it first removes the key "name" and then sets it into jsonState2.
**But jsonState1 is also changed. jsonState1 should stay unchanged, this is wrong behaviour.**
The jsonState1 should remain unchanged and keep the key name.
![image](https://github.com/user-attachments/assets/784e5829-fc2e-4511-aca3-d61d9090e09a)

### Environment

```markdown
- FlutterFlow version: v5.0.11+
- Platform: Windows
- Browser name and version: 122.0.6261.129
- Operating system and version affected: Windows 10
```

### Additional Information

This has been tested when compiled for the web, not on different platforms.
However, the functions used here can easily be viewed in the Function Editor.
Both functions are kept extremely simple to illustrate the problem/bug.
This whole example project is just an extremely simplified example to demonstrate this misbehaviour.
If needed, we can show this problem on a larger scale in a real project.

**Comment by Alezanello** [comment]
Hello!

I see what you’re pointing out, and this might actually be the expected behavior when using Page State variables. Page State variables are essentially variables declared in the model of the page. For example:

```dart
dynamic jsonState1;
dynamic jsonState2;
```

So, when you run code like this:

```dart
if (input is Map<String, dynamic>) {
    // Remove entries where the key is 'name'
    input.remove('name');
}
```

It modifies the variable directly as well.

**Comment by SebyOnGitHub** [comment]
Hi, thanks for having a look.
I also created another page that does the same thing, but uses a string instead of JSON. Here you can see that the second string state is only edited and the first string state remains unchanged:
![image](https://github.com/user-attachments/assets/54668022-da91-4c23-8763-da43de216b10)

![image](https://github.com/user-attachments/assets/5a8a6dea-c537-4a6f-96b7-c624806eb488)

You can try it yourself, the second page is in the same project.
As we can see, this scenario behaves unpredictably.
The JSON on the first state should remain unchanged. The function only returns a different value and should never change a page or component state.

**Comment by Alezanello** [comment]
Hello!

As I mentioned in my previous comment, this is the expected behavior. **Page or State Components** are essentially variables tied to the page, so if you have a function that modifies them, they will update accordingly. This is different from **AppState variables**, which function in a different way.

**Comment by SebyOnGitHub** [comment]
Hi, it seems that it is still not clear which bug is being presented here. To make it clearer, I have created a view that shows the JSON variant and the string variant, please watch the full video to the end. As you can see, they behave differently. If this is the expected behaviour, then one of them must be a bug because they both behave differently:

https://github.com/user-attachments/assets/57ed3eab-f926-4097-b4b6-693069a1b460

**Comment by Alezanello** [comment]
The issue occurs because **maps in Dart are mutable**, so modifying a map directly (e.g., using `.remove()`) changes the original object, affecting all references to it. In contrast, **strings are immutable**, so operations like `.replaceAll()` return a new string without altering the original.

To fix the map issue, create a copy of the map before modifying it. This ensures the original map remains unchanged, avoiding unintended side effects. Here's an updated function:

```
dynamic jsonRemoveName(dynamic input) {
  if (input is Map<String, dynamic>) {
    final Map<String, dynamic> output = Map<String, dynamic>.from(input);
    output.remove('name');
    return output;
  }
  return null;
}
```

**Key Difference**: Strings are immutable (operations create a new instance), while maps are mutable (operations alter the same instance).

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
