### ISSUE TITLE
[Supabase] FutureBuilder not fetching data correctly for multiple columns in Kanban

### ISSUE THREAD

**Issue by MendesCorporation** [FlutterFlow/flutterflow-issues#4927]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a FutureBuilder inside a Kanban-style layout with multiple columns, only the data for the first column is being fetched correctly from the database. Subsequent columns do not execute their respective queries and display incorrect or no data.

This issue seems to occur because the same Completer instance is being reused for all columns, causing only the first query to complete successfully. Each column should have its own Completer to handle independent queries and data fetching.

### Expected Behavior

Each column in the Kanban layout should fetch its data independently and display the corresponding results.

### Steps to Reproduce

1. Create a Kanban-style layout with multiple columns.
2. Use a supabase query to fetch data for each column.
3. Ensure the query for each column is distinct (e.g., filtering by etapa or stage).
4. Observe that only the first column fetches and displays data correctly.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olfLqx5BOvuZE7YSJYO9V/CQWNVB6aIE818pBazwbfe+uB4kqevfOTERvZ9/hT3N+ImD9p2oW0ejruM7+G8FfJQSeR4R41s1ISQriWT6teJSOFJWgPn97J55gGlCs3KSnoRBBJrBtS04t3TiAG9iXaB3sN5DpOkQWDq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/fa86b841-ad89-4bc7-80e6-3addaa3b3155)
![image](https://github.com/user-attachments/assets/7cd10fa5-ede9-46bc-94f3-8e7141f2c4f2)

### Environment

```markdown
- FlutterFlow version: v5.0.11+ 
- Platform: desktop
- Browser name and version:
- Operating system and version affected: windows 11
```

**Comment by Alezanello** [comment]
Hello, and thank you for bringing this to our attention. Would it be possible for you to recreate this issue in a small project containing just the necessary information to replicate it? I have not been able to replicate the issue on my end.

Testing within a new blank project, containing only the essential elements to demonstrate the problem, might help us identify the cause more effectively.
