### ISSUE TITLE
IOS Deployment Failed with Error Saying New Flutter Version is Available

### ISSUE THREAD

**Issue by piershare** [FlutterFlow/flutterflow-issues#4928]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

IOS Deployment Failed with Error Saying New Flutter Version is Available

### Expected Behavior

Proper Deploy

### Steps to Reproduce

1. Deploy app
2. View error code

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IOS Deployment Failed with Error Saying New Flutter Version is Available

### Visual documentation

See attached screenshot

<img width="755" alt="Screenshot 2024-11-18 at 3 30 22 PM" src="https://github.com/user-attachments/assets/f412bfdc-426a-4e83-830b-2e2eb979fd62">

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Mac Desktop
- Browser name and version: Mac Desktop
- Operating system and version affected: MacOS Sequoia 15.1
```

### Additional Information

Project ID: piershare-2pa26x

**Comment by paulperez-dev** [comment]
Hi @piershare! Thanks for reaching out. The Flutter version message is an info log, you can omit it. The issue is with the pods of your project.

Could you please share the **bug report code** of your project so we can take a closer look?

This will help us investigate the issue further. Thanks!

**Comment by piershare** [comment]
Hi Paul thanks!

Bug report code from home page is 

IT4kiMrl34ZPxOVY15Dtbe5sjjg4G1B7TL07ttYbZxUjIuPtBJh+Psn8ahBpZ/WhTFNhHGGGpGIJwejquM7qFfk4YDKCQL5hwc9MVjvvQXq8RpuYELuodHxtJ5tPGn6e5LbUuCRAKfVtSXNh11ymA9+RThXvCZ+/Zwh9f6PHaOI=

**Comment by paulperez-dev** [comment]
Hi @piershare! It looks like the issue may be related to a misconfiguration in the deployment process. Could you double-check that you’ve followed all the steps outlined in our [documentation](https://docs.flutterflow.io/deployment/apple-app-store-deployment/)?

If the error persists, please share the full logs so we can assist you further.

**Comment by piershare** [comment]
Hi Paul,Thanks for your continued help. I don’t think it’s a deployment configuration issue. I have done 42 deployments to TestFlight on this app previously and I didn’t change anything in my Apple account.How do I access the full logs so I can share what you need to see?Thanks,JonathanOn Nov 18, 2024, at 9:28 PM, Paul Pérez ***@***.***> wrote:﻿
Hi @piershare! It looks like the issue may be related to a misconfiguration in the deployment process. Could you double-check that you’ve followed all the steps outlined in our documentation?
If the error persists, please share the full logs so we can assist you further.

**Comment by paulperez-dev** [comment]
Maybe a new dependency was added? <br><br>In the image you shared, there is a copy icon in the top-right corner.

**Comment by piershare** [comment]
Got it thanks! Logs pasted below:

<body style="background-color:#14161C">
<style>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}
</style>
<h4>Failed Step: Install pods</h4>
<div style="white-space: pre-wrap;line-height: 1.5">
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Resolving dependencies...
Downloading packages...
+ _flutterfire_internals 1.3.44 (1.3.46 available)
+ aligned_tooltip 0.0.1
+ ansicolor 2.0.3
+ archive 3.6.1
+ args 2.6.0
+ assets_audio_player 3.1.1
+ assets_audio_player_web 3.1.1
+ async 2.11.0 (2.12.0 available)
+ auto_size_text 3.0.0
+ boolean_selector 2.1.1 (2.1.2 available)
+ cached_network_image 3.4.1
+ cached_network_image_platform_interface 4.1.1
+ cached_network_image_web 1.3.1
+ characters 1.3.0 (1.3.1 available)
+ checked_yaml 2.0.3
+ chewie 1.8.5
+ cli_util 0.4.2
+ clock 1.1.1 (1.1.2 available)
+ cloud_firestore 5.4.4 (5.5.0 available)
+ cloud_firestore_platform_interface 6.4.3 (6.5.0 available)
+ cloud_firestore_web 4.3.2 (4.3.4 available)
+ cloud_functions 5.1.3 (5.1.5 available)
+ cloud_functions_platform_interface 5.5.37 (5.5.39 available)
+ cloud_functions_web 4.10.2 (4.10.4 available)
+ collection 1.18.0 (1.19.1 available)
+ cross_file 0.3.4+2
+ crypto 3.0.6
+ csslib 0.17.3 (1.0.2 available)
+ cupertino_icons 1.0.8
+ dart_geohash 2.1.0
+ dbus 0.7.10
+ device_info_plus 10.1.2 (11.1.1 available)
+ device_info_plus_platform_interface 7.0.1
+ dropdown_button2 2.3.9
+ easy_debounce 2.0.1 (2.0.3 available)
+ equatable 2.0.5
+ fake_async 1.3.1 (1.3.2 available)
+ ffi 2.1.3
+ file 7.0.0 (7.0.1 available)
+ file_picker 8.1.2 (8.1.4 available)
+ file_selector_linux 0.9.3+1
+ file_selector_macos 0.9.4+2
+ file_selector_platform_interface 2.6.2
+ file_selector_windows 0.9.3+3
+ firebase_analytics 11.3.3 (11.3.5 available)
+ firebase_analytics_platform_interface 4.2.5 (4.2.7 available)
+ firebase_analytics_web 0.5.10+2 (0.5.10+4 available)
+ firebase_auth 5.3.1 (5.3.3 available)
+ firebase_auth_platform_interface 7.4.7 (7.4.9 available)
+ firebase_auth_web 5.13.2 (5.13.4 available)
+ firebase_core 3.6.0 (3.8.0 available)
+ firebase_core_platform_interface 5.3.0
+ firebase_core_web 2.18.1
+ firebase_messaging 15.1.3 (15.1.5 available)
+ firebase_messaging_platform_interface 4.5.46 (4.5.48 available)
+ firebase_messaging_web 3.9.2 (3.9.4 available)
+ firebase_performance 0.10.0+8 (0.10.0+10 available)
+ firebase_performance_platform_interface 0.1.4+44 (0.1.4+46 available)
+ firebase_performance_web 0.1.7+2 (0.1.7+4 available)
+ firebase_storage 12.3.2 (12.3.6 available)
+ firebase_storage_platform_interface 5.1.31 (5.1.33 available)
+ firebase_storage_web 3.10.2 (3.10.5 available)
+ fixnum 1.1.1
+ flutter 0.0.0 from sdk flutter
+ flutter_animate 4.5.0
+ flutter_cache_manager 3.4.1
+ flutter_driver 0.0.0 from sdk flutter
+ flutter_google_places 0.4.0 from git
https://github.com/ShehanYjoz/flutter_google_places.git at 52ddef
+ flutter_launcher_icons 0.13.1 (0.14.1 available)
+ flutter_lints 4.0.0 (5.0.0 available)
+ flutter_localizations 0.0.0 from sdk flutter
+ flutter_native_splash 2.4.1 (2.4.3 available)
+ flutter_plugin_android_lifecycle 2.0.20 (2.0.23 available)
+ flutter_rating_bar 4.0.1
+ flutter_shaders 0.1.3
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ font_awesome_flutter 10.7.0 (10.8.0 available)
+ from_css_color 2.0.0
+ fuchsia_remote_debug_protocol 0.0.0 from sdk flutter
+ geolocator 13.0.1 (13.0.2 available)
+ geolocator_android 4.6.1
+ geolocator_apple 2.3.7 (2.3.8+1 available)
+ geolocator_platform_interface 4.2.4
+ geolocator_web 4.1.1
+ geolocator_windows 0.2.3
+ go_router 12.1.3 (14.6.0 available)
+ google_api_headers 2.0.3 (4.2.6 available)
+ google_fonts 6.1.0 (6.2.1 available)
+ google_generative_ai 0.4.6
+ google_identity_services_web 0.3.3
+ google_maps 8.0.0 (8.1.1 available)
+ google_maps_flutter 2.9.0 (2.10.0 available)
+ google_maps_flutter_android 2.14.7 (2.14.11 available)
+ google_maps_flutter_ios 2.13.0 (2.13.1 available)
+ google_maps_flutter_platform_interface 2.9.2 (2.9.5 available)
+ google_maps_flutter_web 0.5.10
+ google_maps_webservice 0.0.20-nullsafety.5 from git
https://github.com/ShehanYjoz/google_maps_webservice.git at 1588c2
+ google_sign_in 6.2.1 (6.2.2 available)
+ google_sign_in_android 6.1.30 (6.1.33 available)
+ google_sign_in_ios 5.7.7 (5.7.8 available)
+ google_sign_in_platform_interface 2.4.5
+ google_sign_in_web 0.12.4+2 (0.12.4+3 available)
+ html 0.15.4 (0.15.5 available)
! http 1.2.2 (overridden)
+ http_parser 4.0.2 (4.1.1 available)
+ image 4.2.0 (4.3.0 available)
+ image_picker 1.1.2
+ image_picker_android 0.8.12+13 (0.8.12+17 available)
+ image_picker_for_web 3.0.5 (3.0.6 available)
+ image_picker_ios 0.8.12 (0.8.12+1 available)
+ image_picker_linux 0.2.1+1
+ image_picker_macos 0.2.1+1
+ image_picker_platform_interface 2.10.0
+ image_picker_windows 0.2.1+1
+ integration_test 0.0.0 from sdk flutter
+ intl 0.19.0 (0.20.0 available)
+ iregexp 0.1.2
+ json_annotation 4.9.0
+ json_path 0.7.2 (0.7.4 available)
+ leak_tracker 10.0.5 (10.0.8 available)
+ leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
+ leak_tracker_testing 3.0.1
+ lints 4.0.0 (5.1.0 available)
+ logging 1.3.0
+ lottie 2.7.0 (3.1.3 available)
+ mask_text_input_formatter 2.9.0
+ matcher 0.12.16+1 (0.12.17 available)
+ material_color_utilities 0.11.1 (0.12.0 available)
+ maybe_just_nothing 0.5.3
+ meta 1.15.0 (1.16.0 available)
+ mime 1.0.6 (2.0.0 available)
+ mime_type 1.0.0 (1.0.1 available)
+ nested 1.0.0
+ octo_image 2.1.0
! package_info_plus 8.0.2 (overridden) (8.1.1 available)
! package_info_plus_platform_interface 3.0.1 (overridden)
+ page_transition 2.1.0
+ path 1.9.0 (1.9.1 available)
+ path_provider 2.1.4 (2.1.5 available)
+ path_provider_android 2.2.10 (2.2.12 available)
+ path_provider_foundation 2.4.0
+ path_provider_linux 2.2.1
+ path_provider_platform_interface 2.1.2
+ path_provider_windows 2.2.1 (2.3.0 available)
+ percent_indicator 4.2.2 (4.2.3 available)
+ permission_handler 11.3.1
+ permission_handler_android 12.0.12 (12.0.13 available)
+ permission_handler_apple 9.4.5
+ permission_handler_html 0.1.3+2 (0.1.3+4 available)
+ permission_handler_platform_interface 4.2.3
+ permission_handler_windows 0.2.1
+ petitparser 6.0.2
+ photo_view 0.15.0
+ pin_code_fields 8.0.1
+ platform 3.1.5 (3.1.6 available)
+ plugin_platform_interface 2.1.8
! pointer_interceptor 0.10.1+2 (overridden)
! pointer_interceptor_ios 0.10.1 (overridden)
! pointer_interceptor_platform_interface 0.10.0+1 (overridden)
! pointer_interceptor_web 0.10.2+1 (overridden)
+ process 5.0.2 (5.0.3 available)
+ provider 6.1.2
+ record 5.1.2 (5.2.0 available)
+ record_android 1.2.6 (1.3.0 available)
+ record_darwin 1.1.2 (1.2.2 available)
+ record_linux 0.7.2
+ record_platform_interface 1.1.0 (1.2.0 available)
+ record_web 1.1.3 (1.1.4 available)
+ record_windows 1.0.3 (1.0.4 available)
+ rfc_6901 0.2.0
+ rxdart 0.27.7 (0.28.0 available)
+ sanitize_html 2.1.0
+ share_plus 10.0.2 (10.1.2 available)
+ share_plus_platform_interface 5.0.0 (5.0.1 available)
+ shared_preferences 2.3.2 (2.3.3 available)
+ shared_preferences_android 2.3.2 (2.3.3 available)
+ shared_preferences_foundation 2.5.2 (2.5.3 available)
+ shared_preferences_linux 2.4.1
+ shared_preferences_platform_interface 2.4.1
+ shared_preferences_web 2.4.2
+ shared_preferences_windows 2.4.1
+ sign_in_with_apple 6.1.2 (6.1.3 available)
+ sign_in_with_apple_platform_interface 1.1.0
+ sign_in_with_apple_web 2.1.0
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.10.0
+ sprintf 7.0.0
+ sqflite 2.3.3+1 (2.4.1 available)
+ sqflite_common 2.5.4+3 (2.5.4+5 available)
+ stack_trace 1.11.1 (1.12.0 available)
+ stop_watch_timer 3.0.2 (3.2.1 available)
+ stream_channel 2.1.2
+ stream_transform 2.1.0
+ string_scanner 1.2.0 (1.4.0 available)
+ sync_http 0.3.1
+ synchronized 3.3.0+3
+ term_glyph 1.2.1
+ test_api 0.7.2 (0.7.3 available)
+ timeago 3.6.1 (3.7.0 available)
+ tutorial_coach_mark 1.2.11 (1.2.12 available)
+ typed_data 1.4.0
+ universal_io 2.2.2
+ url_launcher 6.3.0 (6.3.1 available)
+ url_launcher_android 6.3.10 (6.3.14 available)
+ url_launcher_ios 6.3.1
+ url_launcher_linux 3.2.0 (3.2.1 available)
+ url_launcher_macos 3.2.1
+ url_launcher_platform_interface 2.3.2
+ url_launcher_web 2.3.3
+ url_launcher_windows 3.1.2 (3.1.3 available)
! uuid 4.5.1 (overridden)
+ vector_math 2.1.4
+ video_player 2.9.2
+ video_player_android 2.7.13 (2.7.16 available)
+ video_player_avfoundation 2.6.2
+ video_player_platform_interface 6.2.3
+ video_player_web 2.3.2 (2.3.3 available)
+ vm_service 14.2.5 (14.3.1 available)
+ wakelock_plus 1.2.8
+ wakelock_plus_platform_interface 1.2.1
+ web 1.1.0
+ webdriver 3.0.3 (3.0.4 available)
+ webview_flutter 4.9.0 (4.10.0 available)
+ webview_flutter_android 3.16.7 (4.0.2 available)
+ webview_flutter_platform_interface 2.10.0
+ webview_flutter_wkwebview 3.15.0 (3.16.2 available)
+ webviewx_plus 0.5.0
! win32 5.5.1 (overridden) (5.8.0 available)
+ win32_registry 1.1.5 (2.0.0 available)
+ xdg_directories 1.1.0
+ xml 6.5.0
+ yaml 3.1.2
Changed 224 dependencies!
114 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Analyzing dependencies

――― MARKDOWN TEMPLATE
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/builder/.rbenv/versions/3.0.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.16.1
        Ruby : ruby 3.0.4p208 (2022-04-12 revision 3fa771dded)
[arm64-darwin21]
    RubyGems : 3.5.22
        Host : macOS 14.3.1 (23D60)
       Xcode : 15.3 (15E204a)
         Git : git version 2.42.1
Ruby lib dir : /Users/builder/.rbenv/versions/3.0.4/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @
b1adf5a2882d3dd43486b1095202108409563fb2

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
$FirebaseAnalyticsWithoutAdIdSupport = true
# Uncomment this line to define a global platform for your project
platform :ios, '14.0.0'

# CocoaPods analytics sends network stats synchronously affecting flutter
build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' =&gt; :debug,
  'Profile' =&gt; :release,
  'Release' =&gt; :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..',
'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're
running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}.
Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin',
'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'GoogleUtilities'
  use_frameworks! :linkage =&gt; :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FirebaseFirestore', :git =&gt; '
https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag =&gt;
'11.2.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        # dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

         # dart: [PermissionGroup.location, PermissionGroup.locationAlways,
PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

        # dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        # dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

         # dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=1',

        # dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end

target 'ImageNotification' do
  use_frameworks! :linkage =&gt; :static
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'
end
```

### Error

```
RuntimeError - [Xcodeproj] Type checking error: got `PBXFileReference` for
attribute: Attribute `files` (type: `to_many`, classes: `["PBXBuildFile"]`,
owner class: `AbstractBuildPhase`) - 6436409A27A31CD800820AF7
&lt;Nanaimo::Dictionary {"isa"=&gt;"PBXFileReference", "name"=&gt;"en",
"path"=&gt;"en.lproj/InfoPlist.strings", "sourceTree"=&gt;"&lt;group&gt;",
"lastKnownFileType"=&gt;"text.plist.strings"}&gt;
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object_attributes.rb:142:in
`validate_value'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object_list.rb:205:in
`block in perform_additions_operations'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object_list.rb:202:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object_list.rb:202:in
`perform_additions_operations'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object_list.rb:76:in
`&lt;&lt;'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:301:in
`block (2 levels) in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in
`block in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in
`configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:272:in
`new_from_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:350:in
`object_with_uuid'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:300:in
`block (2 levels) in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in
`block in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in
`configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:272:in
`new_from_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:350:in
`object_with_uuid'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:300:in
`block (2 levels) in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in
`block in configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in
`configure_with_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:272:in
`new_from_plist'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:213:in
`initialize_from_file'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:113:in
`open'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer/analyzer.rb:1194:in
`block (2 levels) in inspect_targets_to_integrate'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer/analyzer.rb:1193:in
`each'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer/analyzer.rb:1193:in
`block in inspect_targets_to_integrate'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/user_interface.rb:64:in
`section'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer/analyzer.rb:1188:in
`inspect_targets_to_integrate'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer/analyzer.rb:107:in
`analyze'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer.rb:422:in
`analyze'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer.rb:244:in
`block in resolve_dependencies'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/user_interface.rb:64:in
`section'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer.rb:243:in
`resolve_dependencies'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/installer.rb:162:in
`install!'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/command/install.rb:52:in
`run'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in
`run'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/lib/cocoapods/command.rb:52:in
`run'
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.1/bin/pod:55:in
`&lt;top (required)&gt;'
/Users/builder/.rbenv/versions/3.0.4/bin/pod:25:in `load'
/Users/builder/.rbenv/versions/3.0.4/bin/pod:25:in `&lt;main&gt;'
```

――― TEMPLATE END
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Type+checking+error%3A+got+%60PBXFileReference%60+for+attribute%3A+Attribute+%60files%60+%28type%3A+%60to_many%60%2C+classes%3A+%60%5B%22PBXBuildFile%22%5D%60%2C+owner+class%3A+%60AbstractBuildPhase%60%29+-+6436409A27A31CD800820AF7+%3CNanaimo%3A%3ADictionary+%7B%22isa%22%3D%3E%22PBXFileReference%22%2C+%22name%22%3D%3E%22en%22%2C+%22path%22%3D%3E%22en.lproj%2FInfoPlist.strings%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%2C+%22lastKnownFileType%22%3D%3E%22text.plist.strings%22%7D%3E&amp;type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly
submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Searching for inspections failed: undefined method `map' for nil:NilClass
Looking for related issues on cocoapods/cocoapods...


Build failed :|
Step 6 script `Install pods` exited with status code 1
</div>
</body>

**Comment by paulperez-dev** [comment]
Did you add a new dependency or package recently?

**Comment by piershare** [comment]
Hi Paul,No I did not. I did create a new custom action though using the code copilot in Flutterflow though. The action was simple which was to convert a double to an integer. Should I maybe roll back and restore my project to before that custom action was added and try to re deploy and see if it works?Best,JonathanOn Nov 19, 2024, at 7:43 AM, Paul Pérez ***@***.***> wrote:﻿
Did you add a new dependency or package recently?

**Comment by piershare** [comment]
Hi Paul,

Just an FYI I was able to get through a successful build just this morning,
so something must have happened on your guys’ end that got fixed. Obviously
I don’t have this issue anymore so you can feel free to close this report,
but did I do anything on my end wrong that you can see to prevent this
issue again?

Thanks for your help!
