### ISSUE TITLE
Flutterflow shared project links not loading

### ISSUE THREAD

**Issue by Unity2Blender** [FlutterFlow/flutterflow-issues#4929]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For this and several other Flutterflow shared project links, they are getting stucked on Flutterflow logo's loading animation.

https://app.flutterflow.io/project/f-f318-in-app-purchase-4a4vfs

### Expected Behavior

The Project should load and give option to Clone.

### Steps to Reproduce

Open any Flutterflow Project link.
- Do Login via Google or any auth provider 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Bug not specific to Project environment.

### Visual documentation

![image](https://github.com/user-attachments/assets/1ec39e0d-f018-4d5e-8a83-41c915d014f9)

### Environment

```markdown
- FlutterFlow version: 5.0.10
- Platform: Windows 11
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out, and I'm sorry you're experiencing this issue. The good news is that this is a known issue, and our team is actively working on a fix. It will be deployed soon!

For more details, you can track the progress here: [https://github.com/FlutterFlow/flutterflow-issues/issues/4891](https://github.com/FlutterFlow/flutterflow-issues/issues/4891)

Thank you for your patience!

**Comment by Unity2Blender** [comment]
Please deploy the fix as soon as possible, It's affecting one of my key feature's development schedule.
