### ISSUE TITLE
API Calls in Team Design Library Are Not Able to Access Team API Library

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#493]
## Expected behavior (required)
I would expect to be able to access the api calls that I set up in the Team API Library when I'm binding api calls in the action flow editor in the Team Design Library.

## Current behavior (required)
Team API Library calls inaccessible. 

## To Reproduce (required)
1. Set up an API Call in the Team API Library
2. Go into Team Design Library and set up an api action
3. See that nuthin' exists

## Your environment

* Version of FlutterFlow used: 3.1
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome 110
* Operating system and version (desktop or mobile): Monterey

**Comment by organicnz** [comment]
Hi johnbhiggins7. Thanks, John once again 🙂

It's not accessible from [Team Design](https://www.loom.com/i/1ae41082e26e4851857ea5975d535f2a) if I'm not mistaken. However, you can add the Team API from the library to your project.

**Comment by hariprasadms** [comment]
Hi @johnbhiggins7 - I see team api's not accessible in team design library. I think this is as per design as I do not see api module in a team design library projects. Team api's can be accessible in a normal project as the project eventually a deployable app not design library project.

**Comment by johnbhiggins7** [comment]
It works now. Thanks.
