### ISSUE TITLE
Custom widget import error

### ISSUE THREAD

**Issue by victor-kiptoo-001** [FlutterFlow/flutterflow-issues#4930]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Import custom widgets to other custom widgets

### Expected Behavior

The custom widget does not compile

### Steps to Reproduce

1 .Create new custom widget
2.Create another custom widget and import the earlier created custom widget
3. Compile
4. The code compiles but does not show an error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkvLqw4tgoeZE0L6IYMJ4lmU7OWkcTL4zlO1HcxAYGO/yPbJ/esnBflVvTbyiT1NhHGeWuF41+tHHjYbDIewoGEiBGZty/5BcEQ3/VXq8RqrWPJaSQ3xCPJhMI0Cj0La7oRZ5HNtZSkYBwFOqPOetHxXcGZ+/Zwh9f6PHaOI=

### Visual documentation

![FlutterflowError](https://github.com/user-attachments/assets/0503f9f9-f62f-492a-9352-ec57b1a7d71d)

### Environment

```markdown
FlutterFlow version:v5.0(released Sep 24, 2024)
Platform: Web
Browser name and version: Google Chrome 126.0.6478.182
Operating system and version affected: Ubuntu 22.04.4 LTS (Jammy)
```

### Additional Information

Im trying to import two different  custom widgets

**Comment by Alezanello** [comment]
Hello!

It’s interesting that the error isn’t displaying as expected. I’ll ensure the team is aware of this issue. In the meantime, could you let me know which widget you were trying to include within another widget?

**Comment by victor-kiptoo-001** [comment]
Hello.
I want to import the FieldInfoPage to DrawPolygon widget

**Comment by Alezanello** [comment]
Hello! Apologies for the delayed response. Have you tried enabling the **"Exclude from Compilation"** option to see if the app builds correctly afterward?

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, if you are still experiencing an issue feel free to open a new one. Thanks.
