### ISSUE TITLE
URGENT: Issue with 'Hide widget if no match' functionality

### ISSUE THREAD

**Issue by 24n1** [FlutterFlow/flutterflow-issues#4934]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm experiencing a critical issue with the 'Hide widget if no match' feature. Even when this option is turned OFF, the widget still remains hidden when there's no data. This behavior should only occur when the option is turned ON.
- Widget remains hidden with no data (both when option is ON and OFF)

### Expected Behavior

- Widget should only hide with no data when option is ON
- Widget should remain visible with no data when option is OFF

### Steps to Reproduce

1. Create a widget with data binding
2. Set 'Hide widget if no match' to OFF
3. Load page with no matching data
4. Widget incorrectly remains hidden despite setting being OFF

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

The bug is not to any widgets. It occurs when product is deployed.

### Visual documentation

![Screenshot_20241120_125301_Samsung capture](https://github.com/user-attachments/assets/651cf762-bba4-4e63-8e6b-21f30ec6ca1a)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: Web
- Browser name and version: chrome latest
- Operating system and version affected: ios 18.1.1
```

### Additional Information

This is blocking our new version deployment and requires immediate attention. Please investigate and fix this functionality so that widget hiding only occurs when explicitly enabled. Please prioritize this issue as it's preventing our production deployment.

**Comment by Alezanello** [comment]
Hello!

I couldn’t replicate this issue on my end. Could you please share a bug report code for the widget where you’re calling this query? Alternatively, you can try replicating the issue in a new project and share the bug report code from that project.

Thank you for your help!
