### ISSUE TITLE
Error accessing Flutter SDK Version

### ISSUE THREAD

**Issue by azharbinanwar** [FlutterFlow/flutterflow-issues#4937]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Screenshot 2024-11-20 130337](https://github.com/user-attachments/assets/1699ff21-218c-457c-9662-6a266b00cd91)
![Screenshot 2024-11-20 130325](https://github.com/user-attachments/assets/1a8dc5e5-7389-4723-b9d7-32006f520de4)

I am experiencing persistent issues while installing the FlutterFlow SDK on my local machine. Despite multiple attempts, the problem remains unresolved.

Steps Tried:

- Reinstalled FlutterFlow.
- Waited for new versions for some days and installed the latest, but the issue persists.
- Deleted C:\Users\user\AppData\Roaming\FlutterFlow multiple times and reinstalled.
- Followed all solutions from similar issues reported in the community:
--  [Community Issue 1](https://community.flutterflow.io/ask-the-community/post/error-accessing-flutter-sdk-version---windows-local-run-odDZS29ShnS2F5b)
-- [Community Issue 2](https://community.flutterflow.io/ask-the-community/post/error-accessing-flutter-sdk-version-tpazPSd42SLE26A)
- Found a similar issue closed by marking as COMPLETED in this repository ([Issue #2615](https://github.com/FlutterFlow/flutterflow-issues/issues/2615)), but no response has been provided even after months.
- Buy FlutterFlow PRO subscription but not helpful

### Expected Behavior

I want to test my app using a local run.

### Steps to Reproduce

![Screenshot 2024-11-20 133249](https://github.com/user-attachments/assets/5633fd8a-29e5-46ba-8b26-2837c4e8eeca)
I'm trying to **Setup Local Run**

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr6w4lOobVE7rrUd8JanjgXMjs+aoIk0OtxQis8GZT0B4kcYs+kfklUOce5T2NmJ06j/XkX/Mr3j+GfVsIrCE+sUaJ9wahPWhfxdzmjR5ShEYS3b2h9EdxmI0yu0quj2ApAVdpuLWws2lzyfOmAYD/rJITuOkc4QuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Screenshot 2024-11-20 133249](https://github.com/user-attachments/assets/a2e37118-739c-48b5-a278-2bfd8a52ffd0)

### Environment

```markdown
- FlutterFlow version: 5.0.11 and its previous version
- Platform: Window 11
- Browser name and version: Google Chrome
- Operating system and version affected: Local Run (5.0.11 and its previous version)
```

### Additional Information

I hope to hear from the FlutterFlow team before my subscription ends, as this issue involves a paid feature.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear about your experience. I’ve tried to reproduce the issue on my end but couldn’t replicate it. It does seem like a bug that needs to be resolved on your side.

Could you please reach out to FlutterFlow support via the in-app chat or by emailing **support@flutterflow.io**? They’ll be able to assist you further with this issue.

Thank you for your understanding!

**Comment by aminnayel** [comment]
@Alezanello  Again, this happens only when the Widows Local Username has a space in it. As you can see in Azhar's screenshot, his Windows Local Username is "**Azhar Ali"** (has a space) (C:\Users\Azhar Ali)


I've opened the same bug report here: https://github.com/FlutterFlow/flutterflow-issues/issues/4958


Thank you!

**Comment by aminnayel** [comment]
@Alezanello

**Comment by azharbinanwar** [comment]
Thanks @aminnayel  for your contribution.

**Comment by Alezanello** [comment]
Thank you, @aminyanel, for reporting this issue! I’ve already confirmed it, and the team has prioritized it for a fix.

I’ll close this as a duplicate and link it to the main issue here: [https://github.com/FlutterFlow/flutterflow-issues/issues/4958](https://github.com/FlutterFlow/flutterflow-issues/issues/4958), as the team was able to replicate the problem there.

Thank you again for bringing this to our attention!
