### ISSUE TITLE
Firebase Push Notifications is not working when the page has a Supabase Row as parameter

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#494]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

A push notification should be sent

## Current behavior (required)

After sent the push notification nothing happens

## To Reproduce (required)

1. Create a button
2. Configure all the parameters "Trigger Push Notification" action
3. Select in "Initial Page" a page that contains Supabase row as parameter
4. Set the Supabase row in the parameter section
5. Build the project and nothing happens

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpOGDsdF4iuPOxzafekYhZuXtfjTFVbKEWLjmEF0srtivOTUvQoOgSaG5hBzql+EQLgYHzkEuzyT+3IHDUHZbsSXTTm

## Context (required)

I want send a push notification to a page that has a supabase row as parameter

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/218939090-29d7787a-78f9-40aa-b693-11d3d6300eff.png)

## Your environment

* Version of FlutterFlow used: 11 February
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome - Version 109.0.5414.120 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 Pro - 22H2 - OS build: 22621.1105

**Comment by shelpert** [comment]
Hi,

This issue has been fixed, and the fix will be released in a future update!
