### ISSUE TITLE
plobleme play stop audio player personalized

### ISSUE THREAD

**Issue by Welcome97** [FlutterFlow/flutterflow-issues#4941]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a stop and play button with icons that I assigned the action of playing and stopping a sound. In general, everything works fine. When I click play the sound plays and still stays on the same page, I click stop the sound stops. But if I activate the game and navigate to the other pages with the sound in the background, I go back to the player page, click stop, the sound does not stop.

### Expected Behavior

Being able to stop the sound even if I return from browsing various pages of the application

### Steps to Reproduce

1) click play
2) navigate to another page
3) return to the player page
4) click stop

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfismBw5RgodRE1q6JasFsmioXJmEcTOURiO0bFDsdF4iuPOxzacn7chJpXtPmYWxlKEWLoGY1063WjeLxFMEqYAiqQJRN/6pMWDrjeF+/aouaBbuNe3dRI+VmI0ya0cCnhyZCCNRYW14+2GaYFt/KVjXfHY/6Zwh9f6PHaOI=

### Visual documentation

![Capture d’écran 2024-11-20 à 14 48 59](https://github.com/user-attachments/assets/54d4c01f-1542-4bf8-be97-bdca06f967a8)
![Capture d’écran 2024-11-20 à 14 49 28](https://github.com/user-attachments/assets/834dbcaf-a190-4660-908e-16826d210605)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

I don't use the FF AudioPlayer widget because I don't like it and you can't customize it, which is why I preferred to create a simple one from icons with actions.

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue on my end. Could you confirm whether your test was conducted on web, Android, or iOS?

Additionally, could you try reproducing this issue in a new blank project and share a bug report code from that project with only the necessary setup to replicate the issue? This will help us investigate further.

Thank you!

**Comment by Welcome97** [comment]
Hello,
To answer your first question, the test was carried out on the 3. web, such
as IOS, such as Android.

Concerning the second, I will do it on a new project but how can I debug it
and send you the report? Sorry but I'm not a developer.

Rodrigue,




Le mer. 20 nov. 2024 à 16:04, Alezanello ***@***.***> a
écrit :

**Comment by Welcome97** [comment]
Hi,
I created a new project with just 2 pages. one with my own drive and the
second completely blank. So the same problem repeats itself: the radio
stream sound plays on play, we navigate to page 2 and return to page 1; the
sound does not stop.
SO; how to send it to you or can you access the project?

Rodrigue

**Comment by Welcome97** [comment]
I'm sorry, I forgot.

player-jwtj2s

Project ID Flutterflow.

**Comment by Alezanello** [comment]
Hello again!

Good news! Our engineering team was able to replicate the issue. Moving forward, please follow updates on this thread: [https://github.com/FlutterFlow/flutterflow-issues/issues/4946](https://github.com/FlutterFlow/flutterflow-issues/issues/4946).

I’ll close this as a duplicate to consolidate all communications in one place. Let us know if you have any further questions!
