### ISSUE TITLE
New Collaboration Feature - Read Only Access not working as expected

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#4944]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I just tried the new collaboration feature 
**Give all FlutterFlow users Read-Only access**
however, it don't enable the feature, I'm on a manager role, but weird thing is it made my project public and I can't make it private anymore.

### Expected Behavior

Expected to change the role of all users with editor role to be Read-Only

### Steps to Reproduce

1. Go to Collaboration
2. Add members
3. Toggle "Give all FlutterFlow users Read-Only access"
4. Project Link Becomes Public

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ejOfluYtPj7xK7aXucsJR/TgWOUs7bZZMi8N+FQwgIbbrO5kPdej+QHZVOMO/dFY3OlmI8XE10/fFuN71UcAtPiisfrZqzqh+Zw3MbDm7Srq3PJGSPGpDM5ljCFOHzbSzqyMnWfNsWHgS62GIG9yicB3UGY/7NjI/Hf2XNZD5nl6JLTLOXn0Jg1ZSfCvr

### Visual documentation

<img width="663" alt="Screenshot 2024-11-21 at 3 37 30 PM" src="https://github.com/user-attachments/assets/789b64ff-11b9-4145-9971-5f172cacf219">
<img width="598" alt="Screenshot 2024-11-21 at 3 37 26 PM" src="https://github.com/user-attachments/assets/b16e9eac-e27c-4e48-b8e4-f82155c6a42c">

### Environment

```markdown
- FlutterFlow version: v5.0.13
- Platform: MacOS Desktop
- Browser name and version: Chrome
- Operating system and version affected: Seqouia 15.1 (24B83)
```

**Comment by Alezanello** [comment]
Hello!

This is the intended behavior of the tool. The **"Read-Only Access"** option is designed to grant all FlutterFlow users access to your project, effectively making it public. It’s not limited to invited users or team members.

If you want to share the project only with specific individuals, you’ll need to invite each user individually and assign them the desired role for the project.

Disabling the **"Give all FlutterFlow users Read-only access"** option will make your project private again.

I hope this helps clarify things! Let me know if you have any further questions.

**Comment by Dev-Muhammad-Junaid** [comment]
Got it, but somehow its not working as expected, the toggle never switches and not getting disable as well.
I also believe the language gets more clear as it means making your project public not just making existing collaborator read only.

**Comment by Alezanello** [comment]
Hello again!

You can verify whether your project is set to public or private and ensure the changes are applied correctly by using the "Share Project" option located in the top-right icon section. Let me know if you need further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bfe41262-b10a-4a46-a834-04e6f40c6be9/d6b06a21-58a2-4f35-ac28-ccf58c3394fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZmU0MTI2Mi1iMTBhLTRhNDYtYTgzNC0wNGU2ZjQwYzZiZTkvZDZiMDZhMjEtNThhMi00ZjM1LWFjMjgtY2NmNThjMzM5NGZkIiwiaWF0IjoxNzMyMjE0MjEwLCJleHAiOjMzMzAyNzc0MjEwfQ.Rie07nSN2Di6oOUP_Xs8NGsIB5Eypr8HJEB0_TIK3W4 " alt="publicprivate.gif" width="1592" height="498" />

**Comment by Dev-Muhammad-Junaid** [comment]
https://github.com/user-attachments/assets/12a277d8-a802-4ac7-8202-19c5c8a55208
Yup however, in my case the toggle never switches but the states get updated and when I come back to the toggle it never shows active state, which is a bug.

**Comment by Alezanello** [comment]
Based on the video you shared, everything appears to be working as expected. When you click "Share," it enables public access, and when you disable public access and then click "Share" again, it re-enables public access. The toggle seems to be functioning correctly.

**Comment by Dev-Muhammad-Junaid** [comment]
Except its not, my project is still public, the boolean is still switched off for me and Making Private is not making it private for me. Sorry check again. The boolean also never toggles in the video

**Comment by Alezanello** [comment]
Hello!

I tested this and had no issues setting it to private again. If your project is still public after you’ve set it to private, please reach out to support via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io). We’re here to help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
