### ISSUE TITLE
costum Function don't  accept supabase package 

### ISSUE THREAD

**Issue by evebeauty** [FlutterFlow/flutterflow-issues#495]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

i want to edit a cosutm function with supabase , but it tells me undefined name supabase , i imported the package from supabase but it does not support it , and when i exit the function and i return i find that the line of the supabase package import removed

## To Reproduce (required)

1.
2.
3.
4.

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")

debugcode:IT4giPLluIh2rsRE0aqBKO9Wr2IsQkg6bYc0sNobbxAjIoDoPJkUac7edlFCUszjdFZlKEWIrFgE0fzqj4bXVMEDISiaG70+zKt2EgmVXmLkEuzyT+3IHDUHZbsSXTTm

## Context (required)

i want to edit a cosutm function with supabase 

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by evebeauty** [comment]
I already have an argument Supabase in my function  , but is still have an error :Undefined name 'supabase'.
otherwise , I have already worked with a function that does the same thing with firbase , and I imported the firebase package without problem , why does it not work the same way with supabase , I think it's a bug that you can see to stare

**Comment by katherineqian** [comment]
Hi @evebeauty, 

This thread may be helpful to you. 
https://community.flutterflow.io/c/discuss-and-get-help/supabase-custom-actions#comment_wrapper_15999676

Please try adding this import to your function:
`import 'package:supabase_flutter/supabase_flutter.dart';`

I will close this issue for now, but we will add this import to our documentation on Supabase. You can feel free to comment and tag me if this does not resolve the issue for you.
