### ISSUE TITLE
Blank screen when using test mode

### ISSUE THREAD

**Issue by hausky** [FlutterFlow/flutterflow-issues#4950]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not able to run my project in test mode, only getting a blank screen.

### Expected Behavior

To run my app/project in test mode.

### Steps to Reproduce

Pressing the test mode button (lightning icon in the upper right corner).

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/debug/8sb77hI5u2N1oXQ09Wgb

### Visual documentation

![image](https://github.com/user-attachments/assets/2a748f63-233f-4f72-ab81-f8bb96f9a1f3)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released November 20, 2024
Flutter version is 3.24.2
- Platform: Chrome
- Browser name and version: Chrome Version 131.0.6778.86 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 23H2
```

**Comment by Alezanello** [comment]
Hello!

This is a known issue, and the team is actively working on improving the test mode. In the meantime, you can try hitting "Instant Reload" again or adjusting the size at the top to force the page to refresh properly and load the test.

Thank you for your patience as we work on enhancing this experience!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
