### ISSUE TITLE
Library Issue - Using a component in dynamically created list with a unique key crashes

### ISSUE THREAD

**Issue by NickMalonzo** [FlutterFlow/flutterflow-issues#4951]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello team!

I found a bit of a bug while working on my actual projects which persists in a brand new project with a brand new library.

When using a component from a library in a list with dynamically generated children, there is a Unique Key property that I would usually set (because I get a warning for it.)

![image](https://github.com/user-attachments/assets/58ebe631-fbf0-4136-a9ba-9bed25a51dd7)

So when I would set it to a unique parameter like an Index in List or uuid from a Supabase table, it would crash my Chrome Local Run and produce this error:

Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...          
lib/pages/home_page/home_page_model.dart:17:8: Error: Type argument 'LibraryTestCustomComponentModel' doesn't conform to the bound 'FlutterFlowModel<Widget>' of the type variable 'T' on 'FlutterFlowDynamicModels'.
 - 'LibraryTestCustomComponentModel' is from 'package:library_publish_testing_0sj6kl/components/library_test_custom_component_model.dart' ('dependencies/library_publish_testing_0sj6kl/lib/components/library_test_custom_component_model.dart').
 - 'FlutterFlowModel' is from 'package:library_testing/flutter_flow/flutter_flow_model.dart' ('lib/flutter_flow/flutter_flow_model.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
  late FlutterFlowDynamicModels<
       ^
lib/flutter_flow/flutter_flow_model.dart:102:32: Context: This is the type variable whose bound isn't conformed to.
class FlutterFlowDynamicModels<T extends FlutterFlowModel> {
                               ^
lib/pages/home_page/home_page_model.dart:27:45: Error: Method not found: 'FlutterFlowDynamicModels'.
        library_publish_testing_0sj6kl_util.FlutterFlowDynamicModels(() =>
                                            ^^^^^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Chrome...             22.3s
Failed to compile application.

### Expected Behavior

Components in dynamically generated lists should be able to have Unique Keys assigned to them. Judging from the error that gets produced from trying to load up the app in Local Run, it seems to be a Library only thing.

### Steps to Reproduce

1. Create a library with a component, publish it, and add it as a dependency in another FlutterFlow app.
2. Create a page
3. Add any component that can generate dynamic children; column, row, etc.
4. Generate children, in my real app I used a Supabase API call body but the error occurs with any list of things.

![image](https://github.com/user-attachments/assets/5998b810-6593-4337-83bf-c25153c2d5ee)

5. Add a component from the library into the column/row, and set the Unique Key to a unique value, like Index in List.
6. Launch Local Run, this example I was on Chrome.
7. It says Starting App... Then force closes and produces the error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48jMrlw4Z1rscF+KXqdcAxniAXHGk7RK8nlNYbawk8J5zKB+wAYvf7P1FWTLy4S2xfMWKaozoJxvfqiIfPFME6YDqbfapcyJNcVBbNdzmWV8ibPamBfW1TO8NXIXHDy52s3BJ/ANBqLkYA32WIDdm8fDDfJZzQOUgkQ/ilKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

See the above fields.

### Environment

```markdown
- FlutterFlow version: 5.0.12 - Nov 20, 2024
- Platform: Windows PC, Local Run
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Thank you so much for bringing this issue to our attention! I can confirm that this is not the expected behavior, and I’ll be passing it along to the engineering team for a fix.

**Comment by Unity2Blender** [comment]
I am also facing this same issue.
