### ISSUE TITLE
Revenuecat conditional action not happening

### ISSUE THREAD

**Issue by jeffcyw95** [FlutterFlow/flutterflow-issues#4952]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a conditional action on pagestate to determine whether is it monthly, yearly or lifetime, then each condition calling its respective offering. After that, I have a condition that says if any of these action is TRUE, then it will do some actions. However, for some reason, this conditional action never happened, neither true or false. It somehow just stucked there after the purchase completed - Note: the purchase does still goes through but its just the following conditional check is not working. 
![Screenshot 2024-11-22 234612](https://github.com/user-attachments/assets/3fbc807c-5c00-4704-9df8-9961f8c12916)

### Expected Behavior

It should goes to the conditional action - either true or false.

### Steps to Reproduce

As mentioned

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPX/z4UBJoTbyndgl+I2CWjnwywMLXm9z1LvBdAAWtY65NyLlQSgLKJHOiVpubCKiwOmtuGshWC3awy8CR2wlCAOluSVYiwziyHumvF3HtJoTuOzE/Bf+XMrLXrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

![Screenshot 2024-11-22 234612](https://github.com/user-attachments/assets/8a1021ec-26bb-4b77-91b9-f1c6dbf1fa81)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I reviewed the generated code for your conditional, and everything seems to be working correctly. It’s possible that the issue isn’t with the conditional itself but rather with the subsequent steps it triggers.

To troubleshoot further, you can try simplifying the next steps by replacing them with an alert dialog to confirm if the conditional is functioning as expected.

Here’s the code for the conditional:

```dart
(_model.purchaseSuccessfulMonthly! ||
 _model.purchaseSuccessfulYearly! ||
 _model.purchaseSuccessfulLifetime!)
```

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
