### ISSUE TITLE
Flutterflow Desktop for Windows won't open

### ISSUE THREAD

**Issue by syg-eliseu** [FlutterFlow/flutterflow-issues#4956]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to use the desktop version for Windows but I'm unable to do so, from one update onwards the application doesn't load after login, it keeps loading infinitely. It doesn't matter with a Google login or email and password. I can't access the Dashboard.

I've already restarted the machine, uninstalled FF, cleaned the system files, downloaded the most current version, but nothing solved my problem.

### Expected Behavior

I hope FlutterFlow opens correctly on Windows and I can use the features available in FlutterFlow Desktop.

### Steps to Reproduce

There are no steps to reproduce; some users I spoke to experience this issue, while others do not.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Without the bug code, the system won't even open.

### Visual documentation

https://github.com/user-attachments/assets/2d65c181-8506-4f39-9489-44a39e6ccc05

### Environment

```markdown
- FlutterFlow version: released 11/20/2024
- Platform: Windows Desktop
- Browser name and version:
- Operating system and version affected: Windows 11 Pro
```

**Comment by Alezanello** [comment]
**Hello!**

Thank you for reaching out, and I’m sorry to hear you’re experiencing this issue. Let’s try the following steps to ensure the cache is completely removed:

1. Close the FlutterFlow application.
2. Navigate to `C:\Users\<your_username>\AppData\Roaming` and delete the FlutterFlow folder.
3. Uninstall the FlutterFlow application.
4. Reinstall FlutterFlow and try running it again.

If the issue persists, you can also reset the application using the built-in reset feature on Windows 10 and 11. Here’s how:

1. Open **Settings** on your computer.
2. Go to **System** > **Apps** > **Apps & Features**.
3. Locate FlutterFlow in the list, then click on **Advanced Options**.
4. Select **Reset** to restore the app to its default state.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
