### ISSUE TITLE
Enums in library project cause duplicate extension method to import in FFAppState.

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#4959]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Creating an enum in a library and importing that library into a project with enums causes an error in FFAppState due to FFEnumExtensions being generated by both projects and the enums.dart exposing this method.

 

### Expected Behavior

I would expect that these common extension methods would get generated into the ff_commons instead of into to enums.dart of each project.

### Steps to Reproduce

1. Create a library project with an enum.
2. Create a project with an enum.
3. Try to build said project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fk8nc34tgrsNc15DUccFFoGYsKVg/a+dJltVxawEbfJPqB7QIZMnOYlZJYsOGdwlIJFmj8XgK0qCOhePIGMEoH02AeYNezrgJZxWXXluVMaq3CaWKPnwlJ/lQI36Y0Jm0mA9SWeNoW3Nk6ly6A+uyThffH4zqDmodQ+SJBNn4o3ClLSLFVix7wmNecCfn

### Visual documentation

"A member named 'serialize' is defined in extension 'FFEnumExtensions' and extension 'FFEnumExtensions', and none are more specific."

![image](https://github.com/user-attachments/assets/609722ce-94fe-4dfa-9b14-b4e7f6d2729f)

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Web/Mobile/Desktop
- Browser name and version: Chrome
- Operating system and version affected: Windows/MacOS
```

### Additional Information

I spent about a day moving some code around to make it accessible between two projects to reuse widgets and models and this bug has wasted that time and effort because now I have to duplicate it again in the target project.

**Comment by Alezanello** [comment]
Hello,

Thank you for reaching out!

I wasn’t able to replicate the issue on my end. Both the library and the consuming project have enums, and I was able to add the library to the project and compile it without any errors.

If you'd like to review my implementation, here’s the public project link for your reference:<br>[https://app.flutterflow.io/project/qa-3106-8dwed9](https://app.flutterflow.io/project/qa-3106-8dwed9)

Let me know if you have further details or steps that could help in reproducing the issue.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by jonl-percsolutions-com** [comment]
@Alezanello,

I was on PTO when you responded and did not get a chance till now to cycle back.

The key difference between your test case and mine is that I have attempted to use a library enum as an app state variable.  You have no app state, so the error would not present.

Also, I can not verify based upon you test project because I am not authorized to download your code.

Did you review my test library and project that were linked?

https://app.flutterflow.io/project/enum-library-0wfvkv
https://app.flutterflow.io/project/enum-serialization-error-b3duwm
