### ISSUE TITLE
Build fails with 'TapGestureRecognizer' isn't defined for the class" when added action to RichTextSpan

### ISSUE THREAD

**Issue by abhipsaSam** [FlutterFlow/flutterflow-issues#496]
After adding the RichText widget in project and  providing action to RichTextSpan build gets fail with error "After adding RichText widget in project and  providing action to RichTextSpan"

## Expected behavior (required)
Project should build and RichTextSpan should perform provided action by clicking on it

## Current behavior (required)
Bild fails with error The method 'TapGestureRecognizer' isn't defined for the class"

1. Added RichText on a page which by default comes with RichTextSpan
2.Added action in the RichTextSpan
3.Proceed with testing
4.Observe that project doesn’t build

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/113416729/219011281-bb3e0782-840c-4832-a62a-1361f047c34b.png)

**Comment by wenkaifan0720** [comment]
Should be fix in the next update. Thank you for raising this issue.
