### ISSUE TITLE
assets downloads missing

### ISSUE THREAD

**Issue by cnrsbtogll** [FlutterFlow/flutterflow-issues#4960]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

hello, I downloaded the project using the flutterflow vscode extension, but I saw that the fonts and images in the assets folder did not download.

### Expected Behavior

hello, I downloaded the project using the flutterflow vscode extension, but I saw that the fonts and images in the assets folder did not download.

### Steps to Reproduce

hello, I downloaded the project using the flutterflow vscode extension, but I saw that the fonts and images in the assets folder did not download.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzcmA38lOxLhc+Kn6a8JoiWMvI0MAWoJMitUbdx4YfYOqPewxPMzOU0NKT/GDeApiO1GJ8TgKw8qMvt71L/ldNRWbUaFy0JVAaQnycF2ub5jWBc2SQnF9ONJUIXKm1J7YpRFNCLFaWnAG70+XNa3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

hello, I downloaded the project using the flutterflow vscode extension, but I saw that the fonts and images in the assets folder did not download.

### Environment

```markdown
- FlutterFlow version: 
- Platform:hello, I downloaded the project using the flutterflow vscode extension, but I saw that the fonts and images in the assets folder did not download.
- Browser name and version:
- Operating system and version affected:
```

**Comment by AdrKacz** [comment]
Did you use the `-include-assets` flag? By default the `import-code` uses `--no-include-assets`.

**Comment by Alezanello** [comment]
Hello!

While the direct code download option is available, we encourage using the FlutterFlow CLI ([https://docs.flutterflow.io/exporting/ff-cli/](https://docs.flutterflow.io/exporting/ff-cli/)) for more customization during the download process. This allows you to include or exclude specific elements as needed.

Additionally, it’s possible that the images you’re referring to aren’t being used directly in the project. To ensure they’re included in the download, you may need to enable the option in **Settings → App Details → Download Unused Project Assets**.

**Comment by cnrsbtogll** [comment]
<img width="737" alt="2" src="https://github.com/user-attachments/assets/91ed3ed1-17f5-44e8-8299-852f3c32e859">
<img width="870" alt="1" src="https://github.com/user-attachments/assets/8717f745-9d98-475d-8121-5a500a7f1245">

I did what you said. Settings → App Details → Download Unused Project Assets.

then I re-downloaded the code using the vscode extention but my application icons or fonts did not come. The application could not be built because the fonts were not there.

**Comment by Alezanello** [comment]
I just tested on Windows and was able to download the assets. One thing to check is that you probably want to update the cli package by running `dart pub global activate flutterflow_cli`.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
