### ISSUE TITLE
 Dynamic Text Uneditable in Screenshot Mode

### ISSUE THREAD

**Issue by AhmedWagdi1** [FlutterFlow/flutterflow-issues#4961]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to edit dynamic text while in screenshot mode after clicking on it.

### Expected Behavior

Previously, I used screenshot mode to create visuals for the App Store and Play Store. I could easily edit dynamic text placeholders, displayed as variables (e.g., [varName]), by simply clicking on them and entering real data. This allowed the screenshots to appear complete and realistic.

### Steps to Reproduce the Issue:

1. **Create a New Page:**  
   Start by creating a new page in the project.  

2. **Add Dynamic Text:**  
   Insert some dynamic text linked to any variable, even a simple concatenated text.  

3. **Enter Preview Mode:**  
   Click on the **Preview** icon located in the top-right corner of the interface.  

4. **Activate Screenshot Mode:**  
   Select the **Screenshot Mode** option.  

5. **Attempt to Edit Dynamic Text:**  
   Try clicking on the dynamic text to edit it. You should observe that it is uneditable in this mode.  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40icrZ8b1Px98D1rrIdfpvmik7NmU3Ro0zt9t7aCsofePrOpkAf8/7UFtUOemhSm9IIGeZjmIX/Mrlk+DlGMEqKRObf4BY+bVqYD3KYzijaZi3PL63b3MmN+NTG2ac15mrkSZDAMVvWWQ/7XGUNeytYC7YCYezPlc7BuaeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/1373342a-5704-4899-8001-2b9fe3293558)
![image](https://github.com/user-attachments/assets/a892fe03-39c8-4424-81b2-1b6c84e9e775)
![image](https://github.com/user-attachments/assets/9e6f5ff6-77df-4ecf-abc7-ef08d1a72250)

### Environment

```markdown
- FlutterFlow version: 5.0.12+
- Platform: all
- Browser name and version: using flutterflow desktop app
- Operating system and version affected: win 10
```

### Additional Information

I recently encountered a bug with a dynamic text element in my project while in screenshot mode.

**Comment by paulperez-dev** [comment]
Hi @AhmedWagdi1,

Thank you for bringing this up! This issue is already being tracked under ticket #3390. Please refer to that ticket for updates and a workaround while the team works on a fix.

I’ll go ahead and close this as a duplicate,
