### ISSUE TITLE
Device Logs Console is very frustrating

### ISSUE THREAD

**Issue by atc6955** [FlutterFlow/flutterflow-issues#4962]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to use the device logs console to debug my app when I am running it on an android simulator. 

I see an error appear in the logs window. Great. I want to read it since its many lines. I cant, because every second a new line prints to the console log and then the log windows auto-scrolls to the newest line. 

It is literally impossible to use the console to actually read the errors and see whats going on.

### Expected Behavior

When I am not at the "most recent line" in the debug console, I dont want the window to auto-scroll to the newest line. 

This would allow me to read the error, copy/paste it etc to other apps. 

It should only scroll to the newest line when I am at the bottom of the console view.

### Steps to Reproduce

1- Enter debug mode for local run 
2- have some kind of error in your app 
3- scroll up to the error and try to read it
4- the window will automatically scroll to the bottom

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Visual documentation

https://github.com/user-attachments/assets/c7f7506f-b158-4051-a149-2be13b78d86c

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Windows app
- Browser name and version: N/A
- Operating system and version affected:  Windows 11
```

### Additional Information

This is incredibly frustrating. I consider it a bug since I cannot use the console to debug my code as it is intended to do. I have to very quickly screen capture and then look at a static image, or go into the browser and use the browser debug.

**Comment by Alezanello** [comment]
Hello!

Have you tried clicking on the logs to make them stay static where you clicked?

Let me know if this helps or if you need further assistance!

**Comment by atc6955** [comment]
Clicking on lines, highlighting lines etc has no impact, the console will scroll to the bottom automatically regardless. Similar to what I showed in my video. 

In the video I was manipulating the scroll bar, but i just tried clicking on lines and highlinging -- the same thing happens.

**Comment by atc6955** [comment]
I still consider this to be a bug despite it being tagged as 'not a bug'

**Comment by Alezanello** [comment]
Hello!

Sorry for the late response.<br><br>At the moment, this isn’t considered a bug, as it doesn’t prevent the app from being deployed successfully. It seems more like a feature or enhancement request, as mentioned earlier.

If you’d like, I can go ahead and create a feature request/enhancement proposal for this. <br>Let me know how you’d like to proceed!

**Comment by atc6955** [comment]
Are you saying that the intended functionality for this feature is that the user should not be able to scroll through and read the log entries?

**Comment by Alezanello** [comment]
Hello!!

I understand your concern! While not everything may be working exactly as intended, some issues fall more into the category of improvements or enhancements rather than critical bugs. Serious, blocking bugs are those that completely prevent users from deploying or developing their app. In this case, the issue seems more like a Quality of Life improvement since the logs aren’t actually blocking your ability to develop or deploy the app.

That said, I’ll go ahead and create an enhancement request and forward it to the engineering team so they can track and prioritize it appropriately. Thank you for bringing this to our attention!
