### ISSUE TITLE
After updating app on web, no update visible in PWA and on browser

### ISSUE THREAD

**Issue by Golicraft** [FlutterFlow/flutterflow-issues#4963]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i update my app on FF and refresh the web-version or PWA version on phone the changes wont appear. I need to go into incognito everytime and not refresh the app as how it was before. Even if I close the PWA on my phone and open it again (tried 5 times) the changes won't appear. 

### Expected Behavior

The app should show the new version when it refresh

### Steps to Reproduce

1. publish app on web
2. refresh the app and see if the changes appear, check the same on PWA phone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slsn15YpNj7xH7aqNdcFB/Tk4QkN/U7s8scpCbw4bIYj2P4lzY876P1JCOObgTQhte2Gcp14GpqiMitrpIMErNRWrfaJx+rpiShfvQlitMZ+TF7q8SHNPEdJPN2KXyraJswp+Xe5pclIW6k6tfezLZAPaJb7yC3owSq/LZO4=

### Visual documentation

Not possible. 

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Chrome, microsoft edge, safari
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

I don't need to provide personal details here as this is a global bug and not only for me. I'm surprised no one else have reported this. 

If I clear my cache the new version shows, but I can't do that everytime I update the app. This worked fine before. Recognized this issue after I come home from holiday (was away for 3 weeks)

**Comment by JonathanG1702** [comment]
It happened to me too. I have to delete cookies and also create a commit every time I test...

**Comment by Alezanello** [comment]
Hello!

This behavior is likely related to how your browser handles caching. If you’re using a web browser, try pressing **CTRL + F5** for a hard refresh to ensure the page fully reloads. On mobile, similar caching issues may occur depending on how the browser saves data.

This is a known behavior on the Flutter side, as highlighted in issues like this one: [Flutter GitHub Issue #112236](https://github.com/flutter/flutter/issues/112236).

**Comment by Golicraft** [comment]
> Hello!
> 
> This behavior is likely related to how your browser handles caching. If you’re using a web browser, try pressing **CTRL + F5** for a hard refresh to ensure the page fully reloads. On mobile, similar caching issues may occur depending on how the browser saves data.
> 
> This is a known behavior on the Flutter side, as highlighted in issues like this one: [Flutter GitHub Issue #112236](https://github.com/flutter/flutter/issues/112236).

Hello, this has not been an issue before. I believe this is on the FlutterFlow side and should be investigated...

**Comment by Alezanello** [comment]
Hello!

As mentioned earlier, nothing has changed on our end regarding this issue. You might consider setting up a Custom Action that checks for differences and triggers an instant reload to ensure the app always fetches the latest version. This approach can also help users who never close the app always stay up-to-date.

Here’s a related post from a year ago that discusses a similar issue: [How to refresh page using FlutterFlow on click action in a web app](https://community.flutterflow.io/actions-logic/post/how-to-refresh-page-using-flutterflow-on-click-action-in-web-app-UTEeHIEUeNDFIP4).

As the post explains, this is likely a browser-side caching issue.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
