### ISSUE TITLE
CheckBoxListTile value does not get updated when its binded state updates

### ISSUE THREAD

**Issue by MohitKandu25** [FlutterFlow/flutterflow-issues#497]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When I click a button that clears the checkbox value, it should update the UI thereby clearing the checkbox.

## Current behavior (required)
The local state does update but the checkbox in UI does not update along with it.

## To Reproduce (required)
1. Add a new page
2. Add a checkbox list tile widget
3. Add a local state which binds to this widget
4. Add another button below this widget called "clear"
5. Add a custom action it to which clears the local state
6. run the app
7. check the checkbox widget
8. click on the clear button
9. local state updates but checkbox doesn't update

## Context (required)
Although the functionality works, the UI not updating confuses the user thinking it is not actually working

## Screenshots / recordings
https://user-images.githubusercontent.com/104911624/219050477-1f8b477a-f0cf-4db0-b498-5b4351291fd8.mp4

## Your environment
Version of FlutterFlow used: v3.0 February 12, 2023 - Flutter 3.3.4
Browser name and version: Google Chrome 103.0.5060.134 (Official Build) (64-bit)
Operating system and version: Ubuntu 20.04.4 LTS

**Comment by hariprasadms** [comment]
Hi @MohitKandu25 - Could you please share re check this with latest FF updates. If this issue still persists, please share bug report code with us. Thanks

**Comment by MohitKandu25** [comment]
Hi @hariprasadms. Tested with latested FF update and the issue is still there. Here's the bug report code:
IT48lcmAz5VNseFF7oSJc/lV+WAvKUM7aJEZiO1+exI8J5zKB+wAYvf7P1FWTLyiYWxIO1mWgjsexvfqk+PhA8c7HAqaUYhC+bhiQw//TlmgM7KKPaqrMS0ffaMKRSz+

**Comment by aemelyanovff** [comment]
@MohitKandu25 How do you "Add a local state which binds to this widget"?  If it's the "Checkbox Initial Value" then changing it shouldn't update the checkbox once it's created (that's why it's called "Initial Value").

**Comment by sumit5101992** [comment]
@aemelyanovff How can we reset the checkbox value to its initial state when a user clicks on the "clear" button?

**Comment by MohitKandu25** [comment]
Hello @aemelyanovff. By binding I mean that the checkbox shows the value from a local state and also updates the same state when the checkbox value changes.
Okay but please correct me if I am wrong here but doesn't updating the local state with the option "Rebuild current page/component" cause the widget to be rebuilt causing the initial value to be "re-initialized"?
If not, can you please suggest a solution to achieve what @sumit5101992  has asked?

**Comment by aemelyanovff** [comment]
@MohitKandu25 @sumit5101992 

> Okay but please correct me if I am wrong here but doesn't updating the local state with the option "Rebuild current page/component" cause the widget to be rebuilt causing the initial value to be "re-initialized"?

No. The word "rebuild" is used in the Flutter sense, i.e. we just call `setState()`. It doesn't re-initialize the widget. It's not a bug, it's working as intended.

> Now, he wants to clear all 20 brands. How can we achieve this functionality?

I can't think of a solution off the top of my head, unfortunately. I can only suggest:
* Creating a feature request for an action to clear checkboxes.
* Asking on https://community.flutterflow.io/ if someone knows a workaround.

**Comment by sumit5101992** [comment]
@aemelyanovff Can you please explain the three options that flutterflow is providing while updating the local state as mentioned in the below image?
<img width="311" alt="Screenshot 2023-02-22 at 3 48 53 PM" src="https://user-images.githubusercontent.com/119568349/220592340-a8d7d9a6-5b98-46e1-951d-e729f2969a5b.png">

**Comment by sumit5101992** [comment]
@wenkaifan0720 Can you please take a look into it?

**Comment by aemelyanovff** [comment]
> @aemelyanovff Can you please explain the three options that flutterflow is providing while updating the local state as mentioned in the below image? <img alt="Screenshot 2023-02-22 at 3 48 53 PM" width="311" src="https://user-images.githubusercontent.com/119568349/220592340-a8d7d9a6-5b98-46e1-951d-e729f2969a5b.png">

https://docs.flutterflow.io/actions/actions/backend-database/update-app-state

**Comment by sumit5101992** [comment]
@aemelyanovff Fluttterflow says: Rebuild All Page: This will redraw the UI of active pages in your app. Use this option when other pages depend on this variable to reflect the new changes. This ensures that the UI is always up-to-date and responsive to user interactions.

But, in this case, this is not happening.

**Comment by aemelyanovff** [comment]
That's why we call it "**_Initial_** Value" :-)

You can submit a feature request for an action updating checkbox value.
