### ISSUE TITLE
Scrollbar not showing despite setting "always visible"

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#4970]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Scrollbar for a scrollable row is not shown even when I set "Thumb Alway Visible" toggle in Design System settings. Not only that, it doesn't even show when scrolling.

### Expected Behavior

Scrollbar should respect the setting and show allways.

### Steps to Reproduce

1. Create a blank page
2. Insert a scrollable row
3. Add a few  dummy containers
4. Go to Design System and enable "Thumb Always Visible". 
5. Set the thumb color to a distinguishable color
6. Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfKBw4lOsfVZ7aXxbfpsmj45JVw5a4IviO57aDUsIuOtBqQUfOPRVFJoZ9+9aVNcG2Ggrzsz+cqPjePPUfUqOTGrbKZbz81ySAH0e2igbpSvDIe0RHFDL91RfH6j18CC2hYmIu1fciUEwDiAIeSUShHDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/56fd8c3d-20bf-4d07-9262-c65c9fcc3fde">

Test:
![2024-11-25_12-52-44 (1)](https://github.com/user-attachments/assets/d9cef3e8-5a59-4c67-b580-89419910281c)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.13 released November 20, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrom Version 131.0.6778.86 (Official Build) (arm64)
- Operating system and version affected: MacOS Sequoia
```

### Additional Information

There are multiple threads in Community forum from many months ago that mention similar problems. E.g. https://community.flutterflow.io/widgets-and-design/post/make-horizontal-scrollbar-visible-web-EnWnPoNhLpwEsKh

**Comment by paulperez-dev** [comment]
Hi @ercanyuz,

This issue has already been reported, and an internal feature request has been created. I’ll go ahead and close this as a duplicate.

Reference: #4065
