### ISSUE TITLE
Unable to change parameters in screenshot mode

### ISSUE THREAD

**Issue by adachoinw** [FlutterFlow/flutterflow-issues#4971]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I need to take screenshots of some pages in the app, but
I'm unable to change any text in screenshot mode.

### Expected Behavior

I was able to change texts in screenshot mode before, now I couldn't.
This issue started happening a few days ago.

### Steps to Reproduce

1. Click preview app
2. Click screenshot mode
3. Go to the page that you want to add texts to
4. Try to change texts

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT9XiuflxIt1pbxY1872acAxnjgXH1s7auYrldZ+axAafY/qP5kqdcnRP1tpWbS/T2w7IWGN+Xse06COkdnyMeY5HxeWfLZm+c9ASQCVJWOWbJSJErWJPmJ/J9FbI37H0KeruRR5PttfWVIi3EyhOOesTXTtMLnhCm1BD/6hOpzXnkrnKiTGVjpG0SsPLGGtP9k2cwuhr4DJ0+IalI/S/ol8qBVXzoPSwtX1TBKTWVk=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: released Nov 20 2024
- Platform: Windows, Web
- Browser name and version: Chrome
- Operating system and version affected:  Windows 11
```

**Comment by rzambroni** [comment]
Hi @adachoinw,

Thank you for reporting this! This is a known issue, and the team already has it in their backlog for resolution. We truly appreciate your patience, and we hope it will be addressed soon. In the meantime, you can refer to the[ original ticket ](https://github.com/FlutterFlow/flutterflow-issues/issues/3390)for any updates.

Thanks again for bringing this to our attention!
