### ISSUE TITLE
Flutterflow Error "Collection: _____ is a subcollection but the parent collection no longer exists

### ISSUE THREAD

**Issue by jacefoddrill** [FlutterFlow/flutterflow-issues#4972]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to test my FlutterFlow code a debugging error Is present that states: "Collection "UserRatingsrating" is a subcollection but the parent collection no longer exists. Tap here to delete it." After clicking on the error message as instructed I am taken to the Firebase collections screen where there is no collection named "Ratings" present.

"Ratings" was a previous collection that was make with AI and i didnt need the componenent anymore so I deleted it before completely deleting the subcollection. 

The primary issue is that the subcollection is orphaned because the parent has already been deleted. Even after manually deleting the collection from the Firebase console, it is still being recognized as an error on Flutterflow UI builder.

Same issue as this: https://github.com/FlutterFlow/flutterflow-issues/issues/1024

<img width="1374" alt="Screenshot 2024-11-25 at 8 48 26 AM" src="https://github.com/user-attachments/assets/164a74a2-0855-41f0-be69-b61578ad9acc">
<img width="310" alt="Screenshot 2024-11-25 at 8 48 44 AM" src="https://github.com/user-attachments/assets/905425e4-419b-4390-9076-49f05e8fd303">

### Expected Behavior

I expected that If I were to click on the error message that states:

"Collection 'userRatingsRating is a subcollection but the parent collection no longer exists. Tap here to delete it." it would remove the Firebase collection and the error would go away. However, upon clicking the error, nothing happens other than being brought to the main "Firebase collections" screen in FlutterFlow.

I also called a cloud function to delete all subcollections in my firebase console and no document, collections, or subcollections are found. 

### Steps to Reproduce

Create a Firebase Collection within FlutterFlow
Create a Firebase Subcollection within the previously mentioned collection
Delete the Primary Collection and not the subcollection
Create a new Collection with a subcollection
Add elements to this collection as well as backend functionality
Click the "Test" button to test the project (Should not work as a result of the present error)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8rl34VgoctH176ILOxFvCE7Ql8cTIMziNZ+exUbfaL1Bu0QYff8QxFBTc+raVNce1eZhmA0+vSOjeHpDvdfJTmuG7ZB+s5QVjzOe2igWq6pCc+zdEBAJ8NTJhCO1J2RpRJAOsZhc148w02ufvOWVjLDFOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/issues/1024

See video here. 

### Environment

```markdown
- FlutterFlow version: v5.0.13 (Released November 20, 2024)
- Platform: MacOS Desktop
- Browser name and version: Version 131.0.6778.86 (Official Build) (arm64)
- Operating system and version affected: 15.0.1 (24A348)
```

### Additional Information

I cannot move forward with my project because I am unable to run tests due to the bug error.

**Comment by Alezanello** [comment]
Hello!

To resolve this issue, you’ll need to recreate the deleted Firestore collection. Once that’s done, ensure you properly delete the subcollection within it first, and then delete the main collection you initially deleted.

**Comment by jacefoddrill** [comment]
I tried this but it will not let me create a new collection with the name "rating" as another main collection, because it is saying it is already being used. Which is true but I can't see it or access it because it was deleted. I also tried creating the orphan sub-collection first and adding it to a parent but it says the same thing. 

<img width="684" alt="Screenshot 2024-11-26 at 3 52 33 PM" src="https://github.com/user-attachments/assets/a88e1288-8ae2-44a1-a76c-d9a1f540fa89">
<img width="690" alt="Screenshot 2024-11-26 at 3 54 34 PM" src="https://github.com/user-attachments/assets/ae4d9b60-953a-498e-ace3-aa506875c8ff">

**Comment by jacefoddrill** [comment]
<img width="1378" alt="Screenshot 2024-11-26 at 4 02 19 PM" src="https://github.com/user-attachments/assets/4d6d4864-f41e-4266-8cfc-586d0bce20e0">
<img width="686" alt="Screenshot 2024-11-26 at 4 02 32 PM" src="https://github.com/user-attachments/assets/5f5138df-bd74-482c-bd03-1c3d4e799731">
I also created a duplicate of my project and deleted all the other collections. one I deleted them all the default showed up as shown above. I tried deleting this one as well but it wont go away.

**Comment by jacefoddrill** [comment]
https://github.com/user-attachments/assets/100a7417-48a7-46cd-a790-ec31fa26c8c0

@Alezanello 

So I recreated the Main collection "userRatings" and the subcollection "UserRatingsrating" automatically comes back with it. 

However, there seems to be a bug within Flutterflow because it is attaching the sub-collection "UserRatingsrating" to a whole different collection "UserProfile" in my project and whenever I delete the sub-collection or its fields, it deletes all of the info in the other collection as-well causing a massive amount of errors in my project.

**Comment by Alezanello** [comment]
In this case, please reach out to our support team via in-app chat or email at [support@flutterflow.io](mailto:support@flutterflow.io). They will assist you with properly deleting the collection from the system.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
