### ISSUE TITLE
Dynamic variable icon exists in typography section but doesnt do anything

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#4973]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

click dynamic button. nothing happens

### Expected Behavior

something to happen or it not exist (strong preference to something happening!!! :D )

### Steps to Reproduce

go to typography section in design system. click icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tlsjf5ZdOmMBE7pDAKMdKnjwWHFA8a+YeltZHdxYaNuv1PLAuPePsZXFIOsukTHNYPWGi8X000PzTkuOeGu0tPiiBY7Z4ysxiFhb/fGSnMqqSBbi0Y3ckN/FjGBSHzbewkSZQJrNtWV1g2jm6AOyuTgXtJqGzOlUCRcmkKpvPkV6pAgzKXn0Jg1ZSfCvr

### Visual documentation

https://www.loom.com/share/89a475e0ebdc4f679e40c04fcb212bfe

### Environment

```markdown
Chrome and mac desktop app
```

**Comment by Alezanello** [comment]
Honestly, <br>I’m not sure why that’s there! 😊 <br>It’s possible the team has plans for it, but for now, I’ll mark it as a bug and send it to the team for review. <br><br>They can decide whether to remove it, hide it, or ensure it works as intended.<br><br>Thanks a lot!

**Comment by chuggmuffinReturns** [comment]
would be amazing if we could get access to it! Would make setting up whitelabeling like 1000% easier

**Comment by chuggmuffinReturns** [comment]
:(
