### ISSUE TITLE
Screen suddenly stays completely blank

### ISSUE THREAD

**Issue by Empirome** [FlutterFlow/flutterflow-issues#4974]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The startup screen of the app stays completely blank, I cannot see any widgets. It hasn't been the case until just recently. I tried in test mode on Safari and Google Chrome, as well as in Android Studio with the iOS simulator. Same behavior. Here's how it looks:
![blank_screen](https://github.com/user-attachments/assets/94521d21-58fa-42f6-bfa3-d45b11bef523)

In Safari, FlutterFlow won't allow me to produce a bug report code for any widget either. If I try to generate a bug report code I get this error message:
![error_message](https://github.com/user-attachments/assets/4d42c51e-cb2e-4e1f-a029-e7ce19c7d6b9)
In Chrome it worked generating the bug report code.

### Expected Behavior

The widgets on the screen should be displayed.

### Steps to Reproduce

Test the app in test mode.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfh8/lsM92ofVD1oSJcPpVtCgWOV8cTIMziNZ+exUbfaL1BqQie86lRBNuYNyraVNfe1GZpEUxp8L4uePpOsA7HxOVY60/z5BqTgrOe2ihSpSYPKuWP3RDGf9gGkDC58CrgRBRBLZoSF4WwVy2B/OAQnXDFOu/Zwh9f6PHaOI=

### Visual documentation

![blank_screen](https://github.com/user-attachments/assets/1b6212b6-262f-4ee5-99b4-0db16e073fd4)

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: Web
- Browser name and version: Safari 17.6 and Chrome 131.0.6778.85
- Operating system and version affected: macOS Sonoma 14.6.1
```

### Additional Information

I cannot test or compile the app, so in essence it's basically useless right now.

**Comment by Empirome** [comment]
The provided bug report code is outdated. Please use this one: ITFfh8/lsM92ofVD1oSJcPpVtCgWOV8cTIMziNZ+exUbfaL1Bu0teOLRM0xBcOm+aVNcGE2ImjgGpMrtk/HpFMJfAyurGd1+1Kl2SAL0e2ihSpSYPKuWP3RDGf9gGkDC58CrgRBRBLZoSF4WwVy2B/OAQnXDFOu/Zwh9f6PHaOI=

**Comment by Alezanello** [comment]
Hello,

I was able to download the code and run it without any issues. Are you still experiencing this problem?

If the issue persists, please reach out to our support team via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io) so they can investigate why it’s not working for your project.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/31f05ad5-bd46-4955-96ea-4e645aa85972/46e1e976-7e6d-4969-939a-c6bf3fb5a083?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMWYwNWFkNS1iZDQ2LTQ5NTUtOTZlYS00ZTY0NWFhODU5NzIvNDZlMWU5NzYtN2U2ZC00OTY5LTkzOWEtYzZiZjNmYjVhMDgzIiwiaWF0IjoxNzMyNjQ3Njg3LCJleHAiOjMzMzAzMjA3Njg3fQ.ena_-BbP5xMDkTh5pVz__mPSFtcmu7NnfCzsCuVuv4U " alt="image.png" width="1191" height="735" />

**Comment by Empirome** [comment]
Thank you for your response. If you tap the skip button from that screen it will navigate to the next page. That’s the page where no widgets are shown, although the page has a container with a list view.

**Comment by king-anna** [comment]
I have the same issue, though when you publish an app to the web, you can see all the elements.

**Comment by Empirome** [comment]
I rebuilt the entire app from scratch and now it works. Thank you for your support.

**Comment by king-anna** [comment]
did you rebuild it as a new project or in the same?

**Comment by Empirome** [comment]
I have created a new project.
