### ISSUE TITLE
API POST : not possible to upload a file now 

### ISSUE THREAD

**Issue by rolrop1** [FlutterFlow/flutterflow-issues#4975]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I use Leonardo AI and to get an init Image ID, i need to upload an image, its not possible in flutterflow anymore, only image path, but it doesnt match with my Leonardo API... 

### Expected Behavior

https://www.youtube.com/watch?v=7D-GKQeurCc

Put back the uploaded fil as in this video at 1:30

### Steps to Reproduce

Nothing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

useless

### Visual documentation

Not necessary

### Environment

```markdown
- FlutterFlow version: last
- Platform: not necessary
- Browser name and version:not necessary
- Operating system and version affected: not necessary
```

### Additional Information

Bug report are too tough to send ..

**Comment by Alezanello** [comment]
Hello!

To send a file via an API POST request, you need to set the request body to **Multipart**. Once that’s done, the variable can be set to **Uploaded File**.

Here’s the documentation to guide you through the process: [https://docs.flutterflow.io/resources/backend-logic/rest-api/#multipart-format](https://docs.flutterflow.io/resources/backend-logic/rest-api/#multipart-format)

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
