### ISSUE TITLE
Pages are blank in test

### ISSUE THREAD

**Issue by king-anna** [FlutterFlow/flutterflow-issues#4982]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't see elements on pages when running test mode but they are present when built and deployed to the web.

### Expected Behavior

To see elements on the page when testing

### Steps to Reproduce

It's hard to understand what exactly breaks it because if you start from scratch it will be visible, but then few elements after, few containers or column after, it disappears.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi8mAvJNIschE1s7xLcBGqD8wFjMLa+cF0+1+FB43Ip+vEJohdeD8YUNKTcOZdHNAI2L+gjgE0c7NheDhOsAoCzaYRpxx0JVASA7gLUK5Mb6mEpOSfHNQHcdbI3Kk0JiC3RNBKtJoR3hn21z6Nq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![Screenshot 2024-11-27 at 10 13 56 AM](https://github.com/user-attachments/assets/e896c167-2347-4dbd-bca6-3001855e3eb6)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by thejaredscott511** [comment]
Im having similar issue! I can see the elements when it is in "run mode" but not in test mode, or when i test on device

**Comment by Alezanello** [comment]
Hello!

It seems you're encountering the same issue as in your previous post: [https://github.com/FlutterFlow/flutterflow-issues/issues/4981](https://github.com/FlutterFlow/flutterflow-issues/issues/4981).

I'll close this as a duplicate. Please refer to the original issue for all the details and solutions.
