### ISSUE TITLE
Cannot add componnet

### ISSUE THREAD

**Issue by king-anna** [FlutterFlow/flutterflow-issues#4983]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dragging a component to an existing or new page and nothing happens

### Expected Behavior

Component is in the page

### Steps to Reproduce

Create a new page, drop a component

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

CAMSqAJDZ2g2ZG5rMWF6SjJOQnJSQVJwSkNnZzBhV2QwYzJSNGVSSTlFakFRQVJvVk1oTUtFVk5qWVdabWIyeGtYekV4T0RCbloyazNJQUJhRXdvUlUyTmhabVp2YkdSZk1URTRNR2RuYVRlcUFnaGxjSGsyZEcxb2RpSjRDaXNLS1FnS1VpVVNIUkliQ0FKQ0Z3b1ZDQWtTRVFvUFUzUnlhWEJsVUdGNWJXVnVkRWxFRWdBaUFnZ0hFa2tLQ0dRNGVubHZiSEYyRWowU01CQUJHaFV5RXdvUlUyTmhabVp2YkdSZmNHbzBkMjU0ZG1FZ0FGb1RDaEZUWTJGbVptOXNaRjl3YWpSM2JuaDJZYW9DQ0hSeWIySTVjMkZ0S0FBNkNEVTBPR2h5TW1OMg==

### Visual documentation

https://www.loom.com/share/c37eddef52d3479392546d96cda458fb

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

The top section is designed for organizing components or pages into folders, providing a better organizational view.

To add a component to the Widget Tree, follow these steps:

1. Click on the square icon with a plus sign next to the widget where you want to add the component (e.g., a Column). This will open a menu.
2. In the menu, click on the diamond icon to access your components.

Alternatively, you can use the first icon at the top of the left toolbar. From there, you can drag the component directly into the UI Builder.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cdaaa302-bcd8-4cc2-a569-738b6f745c92/f320a64d-68d7-4066-9177-f620c97c694a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZGFhYTMwMi1iY2Q4LTRjYzItYTU2OS03MzhiNmY3NDVjOTIvZjMyMGE2NGQtNjhkNy00MDY2LTkxNzctZjYyMGM5N2M2OTRhIiwiaWF0IjoxNzMyNzMwMDgzLCJleHAiOjMzMzAzMjkwMDgzfQ.5LdRHwqePGkEfo3vSOblDFHmHszC6CebRZbxB-tlgNU " alt="component.gif" width="1215" height="804" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
