### ISSUE TITLE
Textfield execute big amount of API Requests, and also renderize the window.

### ISSUE THREAD

**Issue by saruskas** [FlutterFlow/flutterflow-issues#4988]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am developing a web chat application. I have a listview listing the messages and a textfield to input a new message. When I tap in the textfield, a lot of api calls are executed, even the textfield only have "OnSubmit" action, and disable all the updates (component on focus change & component on text change).
Also if I renderize the window a lot of requests are also executing.

### Expected Behavior

The textfield to execute an api call only OnSubmit.
Not execute api calls when renderize the window.

### Steps to Reproduce

1. Create a new page
2. Add a stack
3. Add column backend query with dynamic children
4. Inside the column add a row with another backend query
5. Add a text field (stack parent). 
6. Configure the text with Clear Field Icon and Autofocus.
7. When you tap the textfield api calls are executed.
8. When you renderize the window a lot of api calls are executed.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89gocNf7aXpbcAwiiksIjp8RJJM1MJ+GSs8JJToPLAUZ8zBM05vZrznY1ZEOE2Z/Xwexvfqiuz1VO43HzWsfI9yzKpUWwvhXXyWaa3XCs2rfW1TL+BMfR2j35mniApNCNhvcnwl32D3LuescDbYNJy3DEg7M8ibJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/54c18804-5d4a-463c-a510-6d8e3108410c

### Environment

```markdown
- FlutterFlow version: v.5.0.12+ (released nov. 20 2024)
- Platform: Web
- Browser name and version: Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

### Additional Information

My company can not afford with a huge amount of api calls that shouldnt been call.

**Comment by paulperez-dev** [comment]
Hi @saruskas!

Could you please share credentials so I can access the app and try to identify the issue? I tried creating a new account but I was getting an error.

Additionally, it would be great if you could provide a list of the unwanted calls the app is making.

Looking forward to your response!

**Comment by saruskas** [comment]
Hi! Thanks for your answeare. At this moment, our backend is suffering a bug, so credentials are not working. I will let you know when it solved, sorry.
By the other hand, all the api calls the app is making while I type are unwanted calls. While I write the message in the textfild I do not want any api call to be executed, as occurs.
Regards

**Comment by saruskas** [comment]
Hi, the error is solved. Please, can you try it?

User: vasken@brand4impact.com
Password: password

Thanks

**Comment by paulperez-dev** [comment]
I’ll close this issue for now, but please feel free to reopen it once the backend issue is resolved and you can provide more details.

**Comment by saruskas** [comment]
Hi Raul,
I just have reopened it, I really create a new one due I did not see an
option to reopen. I addedd the credentials.
Let me know if is correct.
Thanks
