### ISSUE TITLE
Screenshot Generator for App Store - Adding Values for Variable not working anymore

### ISSUE THREAD

**Issue by Robmania** [FlutterFlow/flutterflow-issues#4989]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating screenshots for the App Store I used to be able to select [variables] which used to popup a dialog box where you could enter the Screenshot value of that [variable].  This does not seem to be working anymore, I do not get a pop up for any text widget.

### Expected Behavior

When creating screenshots for the App Store you can select [variables] which would popup a dialog box where you could enter the Screenshot value of that [variable]. 

### Steps to Reproduce

Create new page
Create Text widget bound to a backend value and a textfield widget whose initial value is bound to the backend
For steps 3-7 follow the steps to generate screenshots as shown here: https://docs.flutterflow.io/deployment/pre-checks-before-publishing/
Click the Eye icon to preview App in the upper right corner
Enter the screenshot mode
Select the variable and enter screenshot values for the text widget and textfield widget but **popup dialog does not appear.**

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oh8/l5YZNxeJE7aX6bu9V/SYsHGY8U4ZMlMJhewkbCLXNGIgMf/SkbndWUu3iewhMIWGi8Xwdp8rLkuzyFcIHPiiqfqVzyqgJVQqVWmWQaYSgCc3hYEZ7GZlPIGGHzbSJrhNAItdocmA1207zHPOXaAHZJoTOPTAgAMi1Kq3M+QuqATLKXn0Jg1ZSfCvr

### Visual documentation

https://github.com/user-attachments/assets/f567a5b3-5d6a-4987-ad76-9a8bf218e8c9

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.12+ released November 20, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Microsoft Edge 131.0.2903.51
- Operating system and version affected: Windows 11 Home Single Language 22631.4460
```

### Additional Information

I am unable to use the screenshot feature in order to provide app screenshots for the App Store

**Comment by rzambroni** [comment]
Hello, thank you for bringing this to our attention! We’re sorry for the inconvenience this issue may have caused. It’s a known issue, and we’ve already added it to the team’s backlog for resolution. We hope to address it soon. Thank you for your patience and understanding!

You can refer to the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/3390) for updates.
