### ISSUE TITLE
RevenueCat not working - Out of Date Purchases Version

### ISSUE THREAD

**Issue by jgill2023** [FlutterFlow/flutterflow-issues#499]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

On click, the RevenueCat bottom sheet paywall should appear.

## Current behavior (required)

Bottom sheet is gray, no data is pulled or referenced.

## To Reproduce (required)
 In the purchases_flutter version in the pubspec.yaml file is 3.7.0 and it needs to be updated to 4.0.0.
In the pubspec.yaml flutterflow file that purchases_flutter version is set to 3.7.0 to resolve this issue RevenueCat said that the new package had to be downloaded and added and the purchases_flutter version needed to be 4.0.0. After doing that locally (instead of through the FF builder) and changing a few other references in the code it is working as it should be. Confirming that the issue is with the purchases_flutter version currently being used in FlutterFlow.

1. See above

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")

Unable to check RevenueCat entitlements: missingpluginexception(no implementation found for method getPurchaserInfo on channel purchases_flutter

## Context (required)

Trying to implement the paywall for the app, but it does not allow that to happen since the paywall bottom sheet is gray.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): ios, google
* Browser name and version: 
* Operating system and version (desktop or mobile):

<img width="1512" alt="Screenshot 2023-02-13 at 12 29 44 PM (2)" src="https://user-images.githubusercontent.com/125486479/219087561-0dd06fd0-7afc-4826-a04e-430f0e7b16ed.png">

**Comment by jgill2023** [comment]
Has there been any movement on this issue?

**Comment by aemelyanovff** [comment]
We'll upgrade `purchases_flutter` in the next release.

It won't work in the Run Mode though - `purchases_flutter` is not supported on web.

**Comment by jgill2023** [comment]
> We'll upgrade `purchases_flutter` in the next release.
> 
> It won't work in the Run Mode though - `purchases_flutter` is not supported on web.

Ok, do you have an ETA on when that release will be? I understand it won't work in run mode, but it should work for testing through TestFlight (with sandbox testing), correct? Also, will the bottom sheet appear in run mode so that I can see the layout and any overflow issues that might be present?

**Comment by aemelyanovff** [comment]
> Ok, do you have an ETA on when that release will be?

Most likely this week, but I can't promise anything.

> I understand it won't work in run mode, but it should work for testing through TestFlight (with sandbox testing), correct?

Yes.

> Also, will the bottom sheet appear in run mode so that I can see the layout and any overflow issues that might be present?

It'll fail in run mode because it's not supported on web.

There's a global variable "Is Web", I suggest adding a conditional action to do different things on web (where RC doesn't work) vs mobile (where it works).

**Comment by aemelyanovff** [comment]
`purchases_flutter` was upgraded to `4.10.0` in the last update.
