### ISSUE TITLE
Unable to upload image assets

### ISSUE THREAD

**Issue by designsbykeevs** [FlutterFlow/flutterflow-issues#4990]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Uploading PNG file results in infinite loading circle that doesn't resolve. I have tried on Safari, Chrome, Brave.

<img width="1706" alt="Screenshot 2024-11-27 at 7 51 51 AM" src="https://github.com/user-attachments/assets/2e9596be-1f7a-4fe0-90b6-ed1f5bbba92b">

### Expected Behavior

An image or media file is uploaded with no problem

### Steps to Reproduce

Try to upload any file type

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlvLqx412rt9Z7arAau9ViicWMjp+bbsz1+ptYCs8JJToPLAUZ8zBM05vZryrSmNUPGKajmIy/PfqudrxFcdfZDWdUb5Sz6oNVQ7iRl6hM76aCpDofW1QAphmI0Ca4J6vhBV7CNVaV2Qa212Ee+qvfHHANbLqOEdBD8mbKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1706" alt="Screenshot 2024-11-27 at 7 51 51 AM" src="https://github.com/user-attachments/assets/93252023-07ba-4a5f-bce7-e3c0d503aa3e">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.13+ released November 26, 2024
Flutter version is 3.24.2
- Platform: Web and MacOS Desktop App
- Browser name and version: Current: Version 131.0.6778.86 (Official Build) (x86_64);I have tried in the latest versions of Safari and Brave as well
- Operating system and version affected: Sequoia 15
```

### Additional Information

I cannot upload files to my project. This is a big issue as I will need to find alternative solutions to build if i cannot use my own media

**Comment by MishackTP** [comment]
I’m experiencing the same issue. Has there been any update on whether this has been resolved or is being addressed?

**Comment by designsbykeevs** [comment]
@MishackTP no update as of yet. For now, I'm using the Network option and putting in placeholders until I finish building. Hopefully by then there's some resolve, or I'll have to look for another long-term solution.

It doesn't look like the FF team has successfully resolved this in over a year unfortunately

**Comment by rzambroni** [comment]
Hello, and thank you for sharing the details of this issue! I’ve been trying to replicate it on my end, but so far, everything seems to be working as expected.

Could you please confirm if this issue occurs only in the mentioned project? To check, you can try creating a quick blank project and uploading an asset there.<br><br>Thanks.

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thanks.
