### ISSUE TITLE
Issues with file extensions when uploading audio recordings to Supabase

### ISSUE THREAD

**Issue by tonari-ryota** [FlutterFlow/flutterflow-issues#4992]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

First of all, thank you to the FlutterFlow community!
My app is web-based, and the issue is occurring in this context.

Previously, when recording audio and uploading it to Supabase storage, the file would be saved with the .mp3 extension. However, now it is being saved with the top-level domain of the deployed domain as the extension.

For example:

Previously: bucket1/path1/173224820642000.mp3
Now: bucket1/path1/173224820642000.app/f96a3d91-529d-457d-a680-ae9b7d184202
This change in behavior is unexpected.

### Expected Behavior

Save the file with the .mp3 extension as it was before.

### Steps to Reproduce

This issue can be reproduced using FlutterFlow's recording feature and uploading to Supabase.
It has also been confirmed in another project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gis/l8YxgocNf7qr2a+9WniARKUg3RL00st5Hd0gdCOPrBu0QZuD7NhJWON/haVNcDVGKhjoBpuj8i+HUUO4oBy2afKI4+atuczrke2i6MpTWDsy8eHxPHdFMIUya1J6zrAp/B/ppcmAG312mCOq/Hx3DFOu/Zwh9f6PHaOI=

### Visual documentation

![スクリーンショット 2024-11-28 15 26 45](https://github.com/user-attachments/assets/2c9d325d-543c-4d74-a009-59e8c13f742f)
![スクリーンショット 2024-11-28 15 27 08](https://github.com/user-attachments/assets/1bcf591e-0184-48b0-86fc-9b43a50d16ca)

### Environment

```markdown
- FlutterFlow version:  v5.0.13+ released November 28, 2024
- Platform:web
- Browser name and version:chrome
- Operating system and version affected:

- Flutter version is 3.24.2
```

### Additional Information

I hope the issues with FlutterFlow and Supabase can be resolved, leading to an even better service!

**Comment by Alezanello** [comment]
Hello, and sorry to hear you're experiencing this issue. The good news is that this is a known, duplicate issue, and the engineering team is already working on a fix. You can track the progress here: [GitHub Issue #4946](https://github.com/FlutterFlow/flutterflow-issues/issues/4946).
