### ISSUE TITLE
Unable to upload assets onto projects.

### ISSUE THREAD

**Issue by MishackTP** [FlutterFlow/flutterflow-issues#4994]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For some time now, I’ve been unable to upload assets (e.g., GIFs, images, PDFs, etc.) to the Flutterflow projects I’m working on. While I work with a team, none of them are experiencing this issue—it seems to only affect me. When I try to upload assets, they remain stuck in an infinite loading state. As a result, I’ve had to rely on my team to upload assets for me, which is far from ideal.

![Screenshot 2024-11-28 at 08 31 19](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ba306622-6ea6-4324-a241-6c5b750cb318/c868da95-e279-475e-b71b-c5238d950075?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYTMwNjYyMi02ZWE2LTQzMjQtYTI0MS02YzViNzUwY2IzMTgvYzg2OGRhOTUtZTI3OS00NzVlLWI3MWItYzUyMzhkOTUwMDc1IiwiaWF0IjoxNzMyODAyNDgzLCJleHAiOjMzMzAzMzYyNDgzfQ.q0lFcT8vh_eIEWv9ngpz2BGO2uGNY0Z7jUXEty-6mp0 "=1406x")

Is there a specific reason why this issue is only happening to me? And is there a solution for it?

To troubleshoot, I created a new project myself and found I could upload assets without any problems. This leaves me confused—does this mean I’m unable to upload assets to team projects created by our CEO? For context, our CEO sets up the projects for each client, and we don’t create them ourselves. As you can imagine, this issue is a significant inconvenience for both me and the team.

Any guidance or solutions would be greatly appreciated!

### Expected Behavior

The assets to upload successfully to projects instead of getting stuck in an infinite loading loop.

### Steps to Reproduce

I don't believe you will be able to reproduce this issue with your own account.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8whfLlvM92rsdF1oSJK8Janjg5KUQlUIJJltZ+cwwYGO7qPZkAevfBcVZCXu2hdG9UPkap/UEyw97RhuKfV/pdZAqsRtk4/pVXdwndc3KVMaaqCc/pOnd6BeljG2aFyJiw3SR/LfNzWl4s6mGmGOi8cDfqNpjYPHozH/j+JpjAnGzhAR3JES8z8xIVIGreTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

[https://github.com/user-attachments/assets/ee6e7483-7753-4392-93d9-663ebabda12c](https://github.com/user-attachments/assets/ee6e7483-7753-4392-93d9-663ebabda12c)

[https://github.com/user-attachments/assets/389d5c88-ba80-4b12-b230-381ce77e0465](https://github.com/user-attachments/assets/389d5c88-ba80-4b12-b230-381ce77e0465)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.14 released November 28, 2024
Flutter version is 3.24.2
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

*No response*

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. As you’ve already mentioned (and I noticed your comment), this is a duplicate issue. I’ll link these issues internally so the team reviewing them can reference the videos you shared. However, I’ll close this thread to consolidate efforts and ensure the focus remains on a single report. Thank you for your understanding!<br><br>Main issue: [https://github.com/FlutterFlow/flutterflow-issues/issues/4990](https://github.com/FlutterFlow/flutterflow-issues/issues/4990)
