### ISSUE TITLE
Desktop macOS app doesn't update automatically

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-issues#4996]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever a new update is available, the Desktop application invite me to go on the web to download the new version. So I have to manually delete the old version and replace it with the new one.

### Expected Behavior

As advertise in the documentation and website, I expect the application to automatically update once installed.

### Steps to Reproduce

1. Download the desktop app
2. Wait for an update
3. Verify it doesn't update automatically

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

<img width="572" alt="Screenshot 2024-11-28 at 08 31 31" src="https://github.com/user-attachments/assets/087f4575-0c72-4d87-8d02-9c2c0d472362">

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Desktop
- Browser name and version: Not applicable
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment]
Thank you for bringing this to our attention! I'll escalate this to the team so they can work on a fix.

**Comment by Alezanello** [comment]
Hello!!

Currently, automatic updates only work on Windows. On macOS, this behavior is expected until the team uploads the app to the App Store. While it's uncertain if that will happen, for now, you can update by simply downloading the new version and replacing the old one in your Applications folder. That’s all you need to do!

**Comment by AdrKacz** [comment]
<img width="614" alt="Screenshot 2024-11-28 at 12 35 45" src="https://github.com/user-attachments/assets/6b44e805-6dc1-4ddb-bbaf-4e22d8e989c0">

Thank you, I understand. Maybe you want to update your website then (https://www.flutterflow.io/desktop) as the information there is slightly wrong for now.

**Comment by Alezanello** [comment]
Thanks for that!<br><br>Before I answered you I did a check because you mentioned and definitely is something we are going to change!<br><br>Already sent a message to the team!<br><br>Thanks a lot!

**Comment by AdrKacz** [comment]
@leighajarett I see you closed the issue but your website still state incorrect and misleading information?

Is the update in your release pipeline or did you decide to keep incorrect information advertised?
