### ISSUE TITLE
Media is not uploaded into assets and not found in apk then 

### ISSUE THREAD

**Issue by markusbecher** [FlutterFlow/flutterflow-issues#4997]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![problem ff1](https://github.com/user-attachments/assets/d92bfd62-7255-4fd7-a21b-9fd4b0a865dc)

### Expected Behavior

media is saved into assets in flutter code

### Steps to Reproduce

https://www.loom.com/share/e5b5c84598534a9a80b9a25ae799ef1b -    image is not loaded

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlfLIwIhhnNxE+s/yY8dvliEwGUwbUOc7j9VEGAsjCeLkEYoEYfTsXBJWcuqHd1BEKFKiimMCpMLxiOPLUcJdaBWufbp8zrpTUxDvVj+RRcWqC6mWSXN6GfxhfEPC5MO3nyVCKsxtc0Et62eECty+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://www.loom.com/share/e5b5c84598534a9a80b9a25ae799ef1b

### Environment

```markdown
- FlutterFlow version:  5.0.13
- Platform: windows
- Browser name and version:chrome
- Operating system and version affected: windows
```

### Additional Information

I need images in my app !!  
![problem ff1](https://github.com/user-attachments/assets/08f95634-4fd4-4fe9-8e66-d9c6dfb87c77)

**Comment by Alezanello** [comment]
Hello!!

Are you using GitHub, the VSCode extension, or the FlutterFlow CLI? Any additional information you can provide, such as download logs or other relevant details, would be incredibly helpful in diagnosing the issue. Thank you!

**Comment by markusbecher** [comment]
wow  - that was fast !!

Sorry, was missing.
I am using VSCode extension ( actually using Cursor , but this is the same )

there are no logs beside the one of the screenshot...

thanks for your support !!

BR


Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: Alezanello ***@***.***>
Gesendet: Donnerstag, 28. November 2024 12:53
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; Author ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


Hello!!

Are you using GitHub, the VSCode extension, or the FlutterFlow CLI? Any additional information you can provide, such as download logs or other relevant details, would be incredibly helpful in diagnosing the issue. Thank you!

**Comment by Alezanello** [comment]
Perfect! Could you try downloading it via the CLI to check if the assets are missing for you as well?

You can follow the installation steps in the documentation here: [FlutterFlow CLI Installation Guide](https://docs.flutterflow.io/exporting/ff-cli/).

**Comment by markusbecher** [comment]
great- it is there with CLI...
can continue working

HUGE THANK YOU !
BR



Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: Alezanello ***@***.***>
Gesendet: Donnerstag, 28. November 2024 13:22
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; Author ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


Perfect! Could you try downloading it via the CLI to check if the assets are missing for you as well?

You can follow the installation steps in the documentation here: FlutterFlow CLI Installation Guide<https://docs.flutterflow.io/exporting/ff-cli/>.

**Comment by markusbecher** [comment]
thanks for the excellent support...!

**Comment by markusbecher** [comment]
well great it works with CLI.... but the normal download from VS extension is not picking it up....  and  this is what I finally need.....( as working with cursor and pull / Push with FF....  could you have a look at why asset/images are not being picked ?

**Comment by markusbecher** [comment]
Hi, just wanted to ask whether there is an update here. ?  I still don't receive the images if I download the code the VS..... but there is push / Pull works.... while when I am using the CLI I receive the images, but push is not working proberly   
![image](https://github.com/user-attachments/assets/6fb927ec-5432-494f-8747-f042eb03cbbd)
Please have a look at it again

**Comment by rzambroni** [comment]
Hello,

Apologies for the delay in getting back to you. I was able to replicate the issue you described. Since the VS Code extension is quite new, it’s unclear whether the assets download feature hasn’t been implemented yet or if this is an error.

I’ll escalate this to the Engineering team for further investigation and resolution. Any updates will be shared here as soon as they’re available.

Thank you for bringing this to our attention and for your patience!

**Comment by rzambroni** [comment]
Hi, sorry for the delay on getting back to you. 

I was not able to replicate the issue you are describing. When downloading the code using the VS Code Extension it downloads the assets that are in use correctly into the `assets/images`  folder.

Assets that are not in use will not be downloaded. 

Are you still experiencing the issue?

Thanks.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b2c975cf-3f95-458e-a33c-1d0d5f475d9f/81df221e-ea63-4570-9d98-af4cbdfb869d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMmM5NzVjZi0zZjk1LTQ1OGUtYTMzYy0xZDBkNWY0NzVkOWYvODFkZjIyMWUtZWE2My00NTcwLTlkOTgtYWY0Y2JkZmI4NjlkIiwiaWF0IjoxNzMzMzI1NjQ0LCJleHAiOjMzMzAzODg1NjQ0fQ.bJBQcPyh2KHKDDA0S6lp5pctKksvSEBVu7jrZHhcwr8 " alt="image.png" width="634" data-linear-height="582" />

**Comment by markusbecher** [comment]
Hi,
[cid:aeccdc6e-cb30-4b9d-a9a1-7b126b962685]

it is downloaded, but outside...

can't you take my project  cc20247-vymhs5...??

thanks for your help




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: rzambroni ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 16:21
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; State change ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


Hi, sorry for the delay on getting back to you.

I was not able to replicate the issue you are describing. When downloading the code using the VS Code Extension it downloads the assets that are in use correctly into the assets/images folder.

Assets that are not in use will not be downloaded.

Are you still experiencing the issue?

Thanks.

[image.png]<https://camo.githubusercontent.com/720b993600386842cd24008a668aeb29d8be4866c14ab4742169c171c674035c/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f62326339373563662d336639352d343538652d613333632d3164306435663437356439662f38316466323231652d656136332d343537302d396439382d6166346362646662383639643f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a5339694d6d4d354e7a566a5a69307a5a6a6b314c5451314f47557459544d7a597930785a44426b4e5759304e7a566b4f5759764f44466b5a6a49794d5755745a5745324d7930304e5463774c546c6b4f5467745957593059324a6b5a6d49344e6a6c6b4969776961574630496a6f784e7a4d7a4d7a49314e6a51304c434a6c654841694f6a4d7a4d7a417a4f4467314e6a513066512e624a425163507968324b484b4444413053366c70357063744b6b73765345425675376a725a48686377723820>

**Comment by rzambroni** [comment]
I tried, but i could't get access to it

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/eb8b51ff-4981-4c83-b352-5a86be60f144/7b7e2232-81b8-4085-979f-322293d2fd25?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYjhiNTFmZi00OTgxLTRjODMtYjM1Mi01YTg2YmU2MGYxNDQvN2I3ZTIyMzItODFiOC00MDg1LTk3OWYtMzIyMjkzZDJmZDI1IiwiaWF0IjoxNzMzMzQ0NDQzLCJleHAiOjMzMzAzOTA0NDQzfQ.PTX-pxfhRB1S6oUmfPRykr1RvC_4EqgQ5mXT6iya-ZM " alt="image.png" width="752" data-linear-height="763" />

`Error downloading project: status: 404 Message: Project not found`

**Comment by markusbecher** [comment]
sorry... now it is public.

https://app.flutterflow.io/project/cc20247-vymhs5
FlutterFlow<https://app.flutterflow.io/project/cc20247-vymhs5>
FlutterFlow - Build Mobile Apps With Ease
app.flutterflow.io




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: rzambroni ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 21:34
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; State change ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


I tried, but i could't get access to it

[image.png]<https://camo.githubusercontent.com/447d4f624c2041c0a8381a65e300fdc76acdf9de91891c33cb392760067aed17/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f65623862353166662d343938312d346338332d623335322d3561383662653630663134342f37623765323233322d383162382d343038352d393739662d3332323239336432666432353f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a53396c596a68694e54466d5a6930304f5467784c54526a4f444d74596a4d314d69303159546732596d55324d4759784e4451764e3249335a5449794d7a49744f4446694f4330304d4467314c546b334f5759744d7a49794d6a6b7a5a444a6d5a4449314969776961574630496a6f784e7a4d7a4d7a51304e44517a4c434a6c654841694f6a4d7a4d7a417a4f5441304e44517a66512e5054582d7078666852423153366f556d665052796b72315276435f3445716751356d5854366979612d5a4d20>

Error downloading project: status: 404 Message: Project not found

**Comment by markusbecher** [comment]
and.... I have an issue with Google Auth as well....https://www.loom.com/share/fac3c117b20f4f5c8f091a030ed209a2

[https://cdn.loom.com/assets/img/og/loom-banner.png]<https://www.loom.com/share/fac3c117b20f4f5c8f091a030ed209a2>
Test Mode - CC20247 - Google Chrome - 4 December 2024<https://www.loom.com/share/fac3c117b20f4f5c8f091a030ed209a2>
Use Loom to record quick videos of your screen and cam. Explain anything clearly and easily – and skip the meeting. An essential tool for hybrid workplaces.
www.loom.com

and I am wondering why the image is visible in the web & local Chrome version.....  but of course it is not visible in the apk ( as it is not in assets...)




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: rzambroni ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 21:34
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; State change ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


I tried, but i could't get access to it

[image.png]<https://camo.githubusercontent.com/447d4f624c2041c0a8381a65e300fdc76acdf9de91891c33cb392760067aed17/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f65623862353166662d343938312d346338332d623335322d3561383662653630663134342f37623765323233322d383162382d343038352d393739662d3332323239336432666432353f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a53396c596a68694e54466d5a6930304f5467784c54526a4f444d74596a4d314d69303159546732596d55324d4759784e4451764e3249335a5449794d7a49744f4446694f4330304d4467314c546b334f5759744d7a49794d6a6b7a5a444a6d5a4449314969776961574630496a6f784e7a4d7a4d7a51304e44517a4c434a6c654841694f6a4d7a4d7a417a4f5441304e44517a66512e5054582d7078666852423153366f556d665052796b72315276435f3445716751356d5854366979612d5a4d20>

Error downloading project: status: 404 Message: Project not found

**Comment by rzambroni** [comment]
Worked well on my end with the Project you provided. The files you have on your assets are correctly downloaded to the `assets/images` folder.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ac504e12-eba2-4894-9e3e-15bc046739fe/8f824a37-e76a-4619-8616-bc23505e6c8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYzUwNGUxMi1lYmEyLTQ4OTQtOWUzZS0xNWJjMDQ2NzM5ZmUvOGY4MjRhMzctZTc2YS00NjE5LTg2MTYtYmMyMzUwNWU2YzhlIiwiaWF0IjoxNzMzNDI3NjQ4LCJleHAiOjMzMzAzOTg3NjQ4fQ.7UqDgMyR4NGahw5JafRyRnuGi_pljL3LDr3RIjQgKt0 " alt="image.png" width="1102" data-linear-height="888" />

**Comment by rzambroni** [comment]
Regarding the other issue, it is completely separate from this one. If you are still encountering it, please submit a separate issue with detailed information and steps to replicate. This will allow us to address it independently and ensure it’s resolved effectively.

Thank you for your understanding!

**Comment by markusbecher** [comment]
With cli. Or with download?
Von meinem iPhone gesendet

Am 05.12.2024 um 20:43 schrieb rzambroni ***@***.***>:

﻿

Regarding the other issue, it is completely separate from this one. If you are still encountering it, please submit a separate issue with detailed information and steps to replicate. This will allow us to address it independently and ensure it’s resolved effectively.

Thank you for your understanding!

**Comment by rzambroni** [comment]
Using code download from the VSCode extension. I haven't tested with CLI because you guys mentioned that wasn't the problem.

Regards.

**Comment by markusbecher** [comment]
Hi,
well that is really strange.... are you using a Mac ?

I did it on 2 Laptops today... some result..
on one I installed VS and Flutter newly...

[cid:f739e24c-4102-48de-9550-c1919c303b37]


https://www.loom.com/share/5a234a721e974bb9b51a8a0cbceea927
[https://cdn.loom.com/assets/img/og/loom-banner.png]<https://www.loom.com/share/5a234a721e974bb9b51a8a0cbceea927>
Visual Studio Code - settings.json - cc20247-vymhs5 - Visual Studio Code - 6 December 2024<https://www.loom.com/share/5a234a721e974bb9b51a8a0cbceea927>
Use Loom to record quick videos of your screen and cam. Explain anything clearly and easily – and skip the meeting. An essential tool for hybrid workplaces.
www.loom.com




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: rzambroni ***@***.***>
Gesendet: Donnerstag, 5. Dezember 2024 20:41
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; State change ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


Worked well on my end with the Project you provided. The files you have on your assets are correctly downloaded to the assets/images folder.

[image.png]<https://camo.githubusercontent.com/3ad3800aaa3a9976885e7062fdcee922a548e11378957d644cee381bd36e97ed/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f61633530346531322d656261322d343839342d396533652d3135626330343637333966652f38663832346133372d653736612d343631392d383631362d6263323335303565366338653f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a533968597a55774e4755784d69316c596d45794c5451344f5451744f57557a5a5330784e574a6a4d4451324e7a4d355a6d55764f4759344d6a52684d7a63745a546332595330304e6a45354c5467324d545974596d4d794d7a55774e575532597a686c4969776961574630496a6f784e7a4d7a4e4449334e6a51344c434a6c654841694f6a4d7a4d7a417a4f5467334e6a513466512e37557144674d7952344e47616877354a61665279526e7547695f706c6a4c334c44723352496a51674b743020>

**Comment by markusbecher** [comment]
I moved the files to assets and could build apk , which has got the correct image...
so better we close this, as I have a working solution-.

best



Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: Markus Becher ***@***.***>
Gesendet: Freitag, 6. Dezember 2024 10:28
An: FlutterFlow/flutterflow-issues ***@***.***>; FlutterFlow/flutterflow-issues ***@***.***>
Cc: State change ***@***.***>
Betreff: AW: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)

Hi,
well that is really strange.... are you using a Mac ?

I did it on 2 Laptops today... some result..
on one I installed VS and Flutter newly...

[cid:f739e24c-4102-48de-9550-c1919c303b37]


https://www.loom.com/share/5a234a721e974bb9b51a8a0cbceea927
[https://cdn.loom.com/assets/img/og/loom-banner.png]<https://www.loom.com/share/5a234a721e974bb9b51a8a0cbceea927>
Visual Studio Code - settings.json - cc20247-vymhs5 - Visual Studio Code - 6 December 2024<https://www.loom.com/share/5a234a721e974bb9b51a8a0cbceea927>
Use Loom to record quick videos of your screen and cam. Explain anything clearly and easily – and skip the meeting. An essential tool for hybrid workplaces.
www.loom.com




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: rzambroni ***@***.***>
Gesendet: Donnerstag, 5. Dezember 2024 20:41
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; State change ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Media is not uploaded into assets and not found in apk then (Issue #4997)


Worked well on my end with the Project you provided. The files you have on your assets are correctly downloaded to the assets/images folder.

[image.png]<https://camo.githubusercontent.com/3ad3800aaa3a9976885e7062fdcee922a548e11378957d644cee381bd36e97ed/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f61633530346531322d656261322d343839342d396533652d3135626330343637333966652f38663832346133372d653736612d343631392d383631362d6263323335303565366338653f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a533968597a55774e4755784d69316c596d45794c5451344f5451744f57557a5a5330784e574a6a4d4451324e7a4d355a6d55764f4759344d6a52684d7a63745a546332595330304e6a45354c5467324d545974596d4d794d7a55774e575532597a686c4969776961574630496a6f784e7a4d7a4e4449334e6a51344c434a6c654841694f6a4d7a4d7a417a4f5467334e6a513466512e37557144674d7952344e47616877354a61665279526e7547695f706c6a4c334c44723352496a51674b743020>

**Comment by markusbecher** [comment]
adding to assets it works
