### ISSUE TITLE
Blank screen on native versions

### ISSUE THREAD

**Issue by leoleo-s** [FlutterFlow/flutterflow-issues#4999]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've finally deployed my app to the iOS testflight, but when you tap to open it, it just shows a completely blank screen. It doesn't even show the splash screen, it's like the app is not even opening. On test mode, run mode and deployed web app, everything is fine. There aren't any erros or warnings on the project.

I've tested on 2 iOS devices and on a Android device. I get always the same blank screen with no splash.

### Expected Behavior

I expected the app to at least open.

### Steps to Reproduce

Deploy a build of my project, install and try to open. Or build an APK, install and try to open.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klsn134VPxOFG+KnxbcZFvDsXC0A4TL07ttYbZxUjIuPtBJh/P874RBNpTb3hdENhHFGGnT4e0NLSkdn+UvUqORGdR4Nx+MxUZTzgIHq8R6qrCpedPEdtJ9lWG1SX5rSvpiQkBPRvSCEW60+qIevJbBfsN5+/Zwh9f6PHaOI=

### Visual documentation

![IMG_2951](https://github.com/user-attachments/assets/140a965f-d00b-4863-b253-4cb9ac4d2ae2)

### Environment

```markdown
- FlutterFlow version: v5.0.13+
- Platform: macOS Ventura 13.7.1
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Android and iOS
```

### Additional Information

I can't even test my app on native versions.

**Comment by leoleo-s** [comment]
Turned ou that custom actions added as final actions on the main.dart was causing the issue. Sorry about that. This can be closed

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
