### ISSUE TITLE
bug related to cursor position

### ISSUE THREAD

**Issue by tonari-ryota** [FlutterFlow/flutterflow-issues#5001]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is no issue when the max lines is set to 1. However, when it is set to 2 or more, the cursor position and the position of the predictive text are not displayed correctly.

"This issue does not occur when entering English characters, but it happens when inputting Japanese."

### Expected Behavior

The cursor should be displayed in the correct position.

### Steps to Reproduce

Set the max lines to 2 or more and input Japanese.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gis/l8YxgocNf7qr2a+9WniARKUg3RL00sdlud0wdCoDuBIk+ZPWkNlVtZ7XjYX9HPkSmml4f0Nrukdn9IPBfZCWYRqZm+s9cTTndVj2ja5OBEc2wOHQmEd9bFUyMy5+JhRZ4Psd2dX8s3Ga2HeysQgDZNu/YImdISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/8eb97e11-7ad1-46a9-a2af-a0d66a7b6be9

### Environment

```markdown
- FlutterFlow version: 5.0.14 released November 28, 2024
- Platform:web
- Browser name and version:chrome
- Operating system and version affected: macOS
```

**Comment by Alezanello** [comment]
Hello,

Thank you for reporting this issue, and I’m sorry for any inconvenience it’s causing. The team is already aware of this and has it prioritized in the engineering team’s backlog for a fix. Unfortunately, I don’t have an estimated timeline for resolution at the moment. To streamline our efforts, I’ll close this ticket as a duplicate, but rest assured, I’ll link your report internally to ensure the team is aware of your experience.

You can track updates on the original issue here: [GitHub Issue #4058](https://github.com/FlutterFlow/flutterflow-issues/issues/4058).

Thank you for your understanding!
