### ISSUE TITLE
splash background color

### ISSUE THREAD

**Issue by fafa16** [FlutterFlow/flutterflow-issues#5004]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when opening my app, the initial background is blue.It is set up  as white and used to work before last FF update.

### Expected Behavior

White background with the initial splash image
![image](https://github.com/user-attachments/assets/61c159ab-04af-481b-9a24-07314de76316)

### Steps to Reproduce

1. Set up a white background an dpre_loading color
2.Open the apk

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no bug id

### Visual documentation

![image](https://github.com/user-attachments/assets/cc0a17e3-926b-4da0-9d2f-c5fbcdd8f398)
![image](https://github.com/user-attachments/assets/432ca6cb-958f-41e4-86ea-987dc82369b7)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform:pc
- Browser name and version:
- Operating system and version affected: apk
```

### Additional Information

Used to work before,stop working with the last update

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue on my end. Could you please share a bug report code generated from the widget tree? This will help us better understand why this is happening in your project.

You can easily do this by right-clicking on any widget in the widget tree. From the pop-up menu, select "Generate Bug Report Code."

Thank you for your help!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
