### ISSUE TITLE
using own dataTypes in Customer function is not working proberly

### ISSUE THREAD

**Issue by markusbecher** [FlutterFlow/flutterflow-issues#5006]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have defined a datatype called  cardsDoc with some attribut of type string.
I have a customer function which filters from a listofCardsDoc  (input) and write in to reurn list of  cardsDoc ( own data structure). 
it works in code in cursor, but FF gives me an error. "invalid type

### Expected Behavior

https://www.loom.com/share/2a3f82bcbf3546c98754ed0b39a1230a

### Steps to Reproduce

https://www.loom.com/share/2a3f82bcbf3546c98754ed0b39a1230a

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlfLIwIhhnNxE+s/yY8dvliEwFjMLa+cF0+1+FB4aJZCqPLAuZPTOS0NKQumfewhlelWKjjoG0d6Mhd/LLfU6YDSCGohM0JVAVT3vfH2mMsyYDbuCfHN5O/JNClCw58HQgRNDNtR2cWQG3EylNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://www.loom.com/share/2a3f82bcbf3546c98754ed0b39a1230a

### Environment

```markdown
- FlutterFlow version:  5.0.13
- Platform: windows
- Browser name and version: Chrome
- Operating system and version affected: Chrome
```

### Additional Information

https://www.loom.com/share/2a3f82bcbf3546c98754ed0b39a1230a
![image](https://github.com/user-attachments/assets/c625da81-c67f-44d4-be4b-3705334d0dac)

**Comment by Alezanello** [comment]
Hello!

I checked the project, but it seems the custom function is missing, so I couldn’t review it directly alongside the video you provided.

Sometimes, the IDE editor fails to retrieve files from their correct paths, as shown in your video where all imports are displayed as errors. If the import fails (e.g., importing the struct), the struct will be marked as unknown and appear as an invalid type.

Could you try re-adding the custom function and saving it? This will allow us to double-check if everything is set up correctly. Let me know once that’s done, and we’ll take another look!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c06081fb-af0b-47cc-b02c-f9c79acf8734/fae34c07-1ec6-46f0-b8b6-6c1a364c19ef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMDYwODFmYi1hZjBiLTQ3Y2MtYjAyYy1mOWM3OWFjZjg3MzQvZmFlMzRjMDctMWVjNi00NmYwLWI4YjYtNmMxYTM2NGMxOWVmIiwiaWF0IjoxNzMyOTEwNjM3LCJleHAiOjMzMzAzNDcwNjM3fQ.orlisZCafnZ7jlN_pZ5jZ8275acPNBfn7p2_I8KmF0U " alt="image.png" width="435" height="142" />

**Comment by markusbecher** [comment]
OK, I copied this project into a new one and now everything is working... Good to know, that is the trick. Thanks for help
