### ISSUE TITLE
Issue in Choose a plan section

### ISSUE THREAD

**Issue by anuj1o0** [FlutterFlow/flutterflow-issues#5008]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i click on upgrade plan and go to choose plan each plan have some of features and when i scroll down few of them goes out of the card div 

### Expected Behavior

 all the features should stay inside the card section of each plan

### Steps to Reproduce

Go to my project
click on upgrade plan 
scoll down on pop up

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klvHhuJZ2rt8A7qXxbcZomiE7HG49TL07ttYbZxUjIuPtBJh+O+D7SBJvOdPkYFNhHFGLpHsH0fPGudjPN/YFOSmrbpRMys9QFxfwe3q8RbHQPs2efUYmGdxPC2qj3J7YoiZSGPd1L11g2jmbfd7KdBPAN5u/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-11-30 180245](https://github.com/user-attachments/assets/af2631f3-4fb2-4790-aea0-1efae896241f)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: windows 11
```

**Comment by paulperez-dev** [comment]
Hi @anuj1o0,

Thank you for reporting this! This issue is already being tracked in #4923, so I’ll close this as a duplicate. Feel free to follow the original thread for updates.
