### ISSUE TITLE
Expanding and Collapsing Translation Button Creates Extra Lines in Languages Section

### ISSUE THREAD

**Issue by vieiraes** [FlutterFlow/flutterflow-issues#5011]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am experiencing an issue in the Languages section of my project settings. When I expand or collapse the button for translations, it creates an extra line on the screen, replicating the last line, which looks quite strange. Please see the attached screenshots for reference.

### Expected Behavior

No extra lines should be created when expanding or collapsing the translation button.

### Steps to Reproduce

1. Navigate to the Languages section in the App Settings.
2. Click the expand/collapse button for translations.
3. Observe that an extra line is created each time.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4syfLqyItOoctF7arcdcBr/WMRJUwgRo0wscp/awggfbLLBIYuP/WkP0ttQubmY0FYIkSmmnIDpK3VkuzPE8IqCzKubKZ/+c0BWjqWWjuRa5OBEpOeRHdCBelRBWKM5qWrpQlTANRsV1Is2WWuJtyXEw/vO4DQImdISq/LZO4=

### Visual documentation

![Screenshot from 2024-12-01 03-38-16](https://github.com/user-attachments/assets/7dd0598f-81f9-4c8f-a183-e5902244cdc6)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.13+ released November 27, 2024
Flutter version is 3.24.2
- Platform:  Pop!_OS 22.04 LTS
- Browser name and version: Brave Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) unknown (64-bit)
- Operating system and version affected: Pop!_OS 22.04 LTS
```

**Comment by paulperez-dev** [comment]
Hi @vieiraes,

I’m unable to replicate this behavior. Could you please confirm the version you’re using?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
