### ISSUE TITLE
Firebase Messagin getToken not working in IOS - Android OK

### ISSUE THREAD

**Issue by cadufreeela** [FlutterFlow/flutterflow-issues#5013]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When app is running in ios simulator and real device, my map doesnt load.
  firebase_messaging: 15.1.3

In real device the app crashes. In simulator I get the below error:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
<asynchronous suspension>
#4      Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart:796:7)
<asynchronous suspension>
#5      _BufferingStreamSubscription.resume (dart:async/stream_impl.dart:200:3)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
<asynchronous suspension>
#4      getFcmToken (package:freeela/custom_code/actions/get_fcm_token.dart:35:21)
<asynchronous suspension>
#5      _DashBoardScreenWidgetState.initState.<anonymous closure>.<anonymous closure> (package:freeela/pages/logged/dash_board_screen/dash_board_screen_widget.dart:56:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/f<…>

### Expected Behavior

my custom getFCMToken action provides me the token required to send FCM notification to all devices. It should work as expected. the getFCMToken is loaded on PageLoad event and stores the token in a firestore user collection.

### Steps to Reproduce

1. create a page
2. add on page load event 
3. create an action that retrieveds a FCM token from Firebase

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksjf35N2ofVY+Krcc8ZsoCAXCUMAXOYvitYbVR4YfY/mB7AMYePeQ0NKTMOKeVB2Ik6ailkxwN78v/HtNO06CxObbtU50JVPFg/NUn2uVpvQO8+sOH8kO/9gFUyj5qW7nyJ5Nsl0WmNk3U6TNa3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="1245" alt="Screenshot 2024-12-01 at 11 12 10 pm" src="https://github.com/user-attachments/assets/901b0032-4354-4026-8bb3-e47826cb1e54">

### Environment

```markdown
- FlutterFlow version: 
- Platform: MacOS desktop
- Browser name and version:
- Operating system and version affected: 15.1.1

FlutterFlow v5.0.14 released November 28, 2024
Flutter version is 3.24.2
```

### Additional Information

[!] Flutter (Channel [user-branch], 3.24.2, on macOS 15.1.1 24B91 darwin-arm64, locale en-AU)
    ! Flutter version 3.24.2 on channel [user-branch] at /Users/carloslinares/Library/Application Support/io.flutterflow.prod.mac/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! The flutter binary is not on your path. Consider adding /Users/carloslinares/Library/Application Support/io.flutterflow.prod.mac/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/carloslinares/Library/Application Support/io.flutterflow.prod.mac/flutter/bin to your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 4cf269e36d (3 months ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/carloslinares/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.95.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 16 (mobile)              • E052A64D-9B8D-4C74-B0D1-B666F2019846 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by cadufreeela** [comment]
Any updats on this? its crashing not only simulator but real device as well. I need to deploy this to PROD soon as I have a big event where I will showcase the app and it only works in Android, not IOS devices (iphone and ipads). please help!!!!

**Comment by paulperez-dev** [comment]
Hi @cadufreeela,

Have you tried building the prod version of app and installing it on an iOS device? If so, could you share the results?

Based on the logs, it seems the issue might be related to your local Flutter setup. Could you please try reconfiguring the local environment and running it again?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
