### ISSUE TITLE
ca not access project main branch

### ISSUE THREAD

**Issue by hfzd3v** [FlutterFlow/flutterflow-issues#5016]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://github.com/user-attachments/assets/91e1f112-18e6-4e53-98df-fd5810f33874

i can not access main branch - ask me to abort merge or continue merge - both failed as in the recording

### Expected Behavior

when click main branch should direct to main

### Steps to Reproduce

1. open project (name 'eInvoice')
2. open main branch 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

wqdqwdqd

### Visual documentation

https://github.com/user-attachments/assets/ac7f72d5-3da0-499c-a3ec-50dc3b6bed41

### Environment

```markdown
- FlutterFlow version: v5.0.14
- Platform: web, mac
- Browser name and version: safari 18.1.1
- Operating system and version affected: macOS
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. For assistance, please reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They will be happy to help resolve this for you.
