### ISSUE TITLE
Unable to scroll on DataTable if the cursor or finger is on data

### ISSUE THREAD

**Issue by icestormpure** [FlutterFlow/flutterflow-issues#5018]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can only scroll horizontally when you put your mouse/finger on part that doesn't have data, if you try to scroll on part that have data it will get stuck (see video)

### Expected Behavior

Should be able to scroll smoothly even if your cursor and finger is on the data

### Steps to Reproduce

1. Create datatable
2. Wrap to row and set it to scrollable
3. Put data on datatable
4. Scroll on part that have data, you will get stuck. You can only scroll on whitespace

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsM9Oxd8F17rtKe9Wnj8vC096R5c0r9pEGEshfb3nP5oEPPSkaltLYtelS1dEM1Sl/XMxw87vi/OeDsY6YBycb4Raz5RXQT3MJDmVWq6gEpOoYWtBIJtQGEjG356zhRQlG/tfWmQj3DmHffCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/e1576f2d-2afb-490d-9741-92b8b0c50c5a

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Web
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Windows 10
```

### Additional Information

I believe this is quite an important bug to fix because users wouldn't be able to scroll on parts that have data

**Comment by Franco98404** [comment]
In my case I have the same problem but with the textfields:

In my case it only happens in the web version on Android, on desktop the web works properly
https://www.loom.com/share/e4c1d4ca15a04a7c8125e054ae1c4110

**Comment by Alezanello** [comment]
The reason you can only scroll in the whitespace is that the scroll functionality is applied to the Row. Since the DataTable itself doesn't support scrolling, the "whitespace" you’re scrolling is actually the Row.

**Comment by icestormpure** [comment]
> The reason you can only scroll in the whitespace is that the scroll functionality is applied to the Row. Since the DataTable itself doesn't support scrolling, the "whitespace" you’re scrolling is actually the Row.

So is there a workaround to this?

**Comment by Alezanello** [comment]
At the moment there isn't sorry about that, maybe you can create a simil of datatable and use listview horizontal scroll

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
