### ISSUE TITLE
DataTable displays incorrect data or continues loading indefinitely using conditional builder

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#5019]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The DataTable behaves inconsistently. In some cases, it keeps loading indefinitely, while in other cases it displays incorrect data.

### Expected Behavior

The DataTable should:
1. Properly fetch and display data from the API based on the provided parameters.
2. Avoid infinite loading loops.
3. Display the correct information consistently across all conditions.

### Steps to Reproduce

1. Create an API Call and add parameters, for example, itemsPerPage,I give the API used in the video
2. https://reqres.in/api/users?per_page=7&page=1
3. Add a choice chips
4. Add a conditional builder
5. Add a datatable to each condition of the conditional builder and deactivate the "Paginated" option
6. Wrap each datatable with a container and in this container add an API call
7. Now run the test and probably have one of two problems, or the datatable keeps loading infinite or show incorrect info

1. Create an API call with parameters, such as `itemsPerPage`. For example, use the following API:  
   `https://reqres.in/api/users?per_page=[itemsPerPage]&page=1`
2. Add a Choice Chips to toggle between conditions.
3. Add a Conditional Builder.
4. Inside each condition of the Conditional Builder, add a DataTable and deactivate the "Paginated" option.
5. Wrap each DataTable in a container, and in this container, add the API call.
6. Run the test.  
   - You will likely encounter one of two issues:  
     a) The DataTable keeps loading infinitely.  
     b) The DataTable displays incorrect data.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lPLq25dIsctZ1rrtbfpsmj45Jn45R40n08FraBoofePrBJkqP8zBP1dVXf2RSmxiOlmJnnII7tLMhuz1Gu4FOQ+IQ75iz7lUeBXLeF6teKq3EaiSRHdtHZthfUyH37COih1dPrF2ZV4+wDuyCOzLSivsH4+zPDEjI+WKGIbNo3CyHSXkUDh2tmNecCfn

### Visual documentation

https://www.loom.com/share/60b0821d946841f998ff1f768efe5661

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.13+ released November 27, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: W11
```

**Comment by rzambroni** [comment]
Hi Franco,

Thank you for taking the time to submit this report.

This issue is actually a known one, and our team has already added it to our backlog for resolution. You can keep an eye on the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/3211) for any updates as we work on it.

We appreciate your patience and understanding!

Best regards,
