### ISSUE TITLE
reorder pages not working

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#502]
## Expected behavior (required)
when in the pages view on a project (where there is a list of app pages on the left side of the screen) i am able to drag a page to a new position and it is suppose to stay at its new position

## Current behavior (required)
when in the pages view on a project (where there is a list of app pages on the left side of the screen) i am able to drag a page to a new position but it will just snap back to its original position

## To Reproduce (required)
1. open an existing project and go to the option on the left most menu where there is a icon with three horizontal lines with dots before them
2. try to take a screen and reorder it 
### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")
i don't believe a bug report code is relevant

## Context (required)
i want to reorder my pages to keep the project organized

## Screenshots / recordings

https://user-images.githubusercontent.com/72816439/219714298-95be9fdb-6bbb-4a23-932f-2c77b6627d6d.mov

## Your environment

* Version of FlutterFlow used: v3.1
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment]
Thanks @joekman990 for posting this issue. I can re produce this issue.

**Comment by aemelyanovff** [comment]
@joekman990 Thanks for reporting the issue. The page menu will be completely redone in the next update, so I don't think it's worth it to fix this issue now.
