### ISSUE TITLE
Component state variables from bottom sheet are not accessible in debug panel

### ISSUE THREAD

**Issue by Gosten** [FlutterFlow/flutterflow-issues#5023]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open bottom sheet dialog, I can't access component state variables in debug panel.
![image](https://github.com/user-attachments/assets/65ef8630-42d9-4673-b85b-7ffcda75af05)

![image](https://github.com/user-attachments/assets/64e303d9-df07-4314-9047-1cf8c5e1a139)

I can access component states places in the widget builder (eg. _adminSideNav_), but I can't access dialogs displayed as popups.

### Expected Behavior

Every dialog (bottom sheet, custom dialog, drawer) should have its component state variables accessible from FF debug panel

### Steps to Reproduce

1. Create new component
2. Add component state variable
3. On page, create action: _Bottom Sheet_ -> select component from step 1.
4. Launch test mode
5. Open bottom sheet in test mode
6. Check debug panel for app - component state of bottom sheet is missing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fisnLuJVOxLxH1s+NdcFsnSQWQlgnbZIolu5xbwIdGI/qPbAIYc+lUxZJbbyRSmNceWH8/W0xp9nFv9nDCfkrMhyJbNlxzrpUEwLgTn+iRL60O5C8P0dQQPhVIBDCzpuZkwlQOspfLnAu60z7POqXQhLqJO/XIm1AHs+ICJnDp3SaGyXsG30Jg1ZSfCvr

### Visual documentation

![image](https://github.com/user-attachments/assets/65ef8630-42d9-4673-b85b-7ffcda75af05)

![image](https://github.com/user-attachments/assets/64e303d9-df07-4314-9047-1cf8c5e1a139)

### Environment

```markdown
- FlutterFlow version: 5.0.12+
- Platform: Web
- Browser name and version: Brave Browser v 1.73.91
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. I can confirm this issue and will pass it along to the engineering team for review and a potential fix.
