### ISSUE TITLE
FlutterFlow Closing Constantly

### ISSUE THREAD

**Issue by Tridi-Mari** [FlutterFlow/flutterflow-issues#5025]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My team and I, consisting of four developers, use FlutterFlow extensively. Recently, we've been encountering a bug that is significantly hindering our work. FlutterFlow has been closing unexpectedly and frequently for all of us. Often, we're in the middle of a task when it shuts down, causing us to lose progress and redo our work, which disrupts our deadlines and productivity.

The most critical issue is the frequency—it happens every few minutes, seemingly at random. We've attempted to identify a specific "trigger" or action that might be causing the crashes, but to no avail. There doesn't appear to be any consistent reason; it just closes, sometimes even when we're not actively using it.

This issue is making it extremely challenging to maintain our workflow.

### Expected Behavior

We expect FlutterFlow to investigate and resolve this issue as soon as possible, ensuring platform stability to prevent unexpected closures and allowing our team to work without interruptions.

### Steps to Reproduce

We are unable to provide steps to reproduce the issue, as there is no specific reason or action that triggers it. The crashes occur randomly, without any identifiable pattern

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raCsofePrOpkAf8/7UFtUOLynSmNiPk6JvGIX/MqJhvzlOOw6JROdGoREzZBiTQnKQl+RRKqXO4S3b3EnI/FbGkik1MO3ogkkHNtvLnMt22WmAd+tYBfBJp/1C0UdOeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

FlutterFlow is crashing out of blue in desktop version

### Environment

```markdown
- FlutterFlow version: v5.0.12+
- Platform: Desktop
- Browser name and version: 
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello,

I'm sorry to hear you're experiencing this issue. I’ve been using the desktop app for Windows and have tested it extensively for over an hour with various widgets and local runs, and I haven’t encountered any crashes so far. However, I’ll check internally to see if there have been any other reports of similar issues.

In the meantime, you can try the following steps to see if they help resolve the issue on your end:

**For both Windows 10 and 11:**

1. Open **Settings**.
2. Go to **System > Apps > Apps & features**.
3. Find the app in the list, then click on **Advanced options**.
4. Click the **Reset** button.

Let me know if this helps or if the issue persists so we can further investigate.

**Comment by Tridi-Mari** [comment]
I followed your advice, even going as far as uninstalling the application and clearing all its data. While this worked temporarily, the issue soon resurfaced. I also reached out to a FlutterFlow group I’m part of and discovered that my team is not the only one experiencing this problem.

**Comment by Alezanello** [comment]
Could you please share the Logs of the crash?

**Comment by Tridi-Mari** [comment]
Failed application name: flutterflow.exe, version: 5.0.12.0, timestamp: 0x673e4064
Failed module name: flutterflow.exe, version: 5.0.12.0, timestamp: 0x673e4064
Exception code: 0xc0000005
Fault offset: 0x000000000067c5e4
Failed process ID: 0x3670
Failed application start time: 0x01db48a0b6a11721
Failed application path: C:\Program Files\FlutterFlow\flutterflow.exe
Failed module path: C:\Program Files\FlutterFlow\flutterflow.exe
Report ID: 827e9b69-72ec-430f-88d5-ab8fa963314b
Full name of the failed package:
Application ID relative to the failed package:


![image (1)](https://github.com/user-attachments/assets/205e1799-318c-4ba9-af7c-a6439cd2c068)

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?
