### ISSUE TITLE
Can't set Variable to Action

### ISSUE THREAD

**Issue by varzolar** [FlutterFlow/flutterflow-issues#5026]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't set the value [document (productos)] in the parameter (productos) for the navigation action of the container (MenuInicio). When that the value for the parameter is selected, it appears above as selected, but it doesn't open the window to confirm it. 

### Expected Behavior

set the navigation action to (Ordenar) Page with the parameter (productos) using the Document Value 

### Steps to Reproduce

1. Create two pages 2. In the first page I add the parameter 3. In the second page I add a container 1 3. Set navigate action to container (MenuInicio) 4. Add the parameter (productos) 5. Set [Documents (productos)] as variable 6. Opens the last window to confirm the parameter.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

// Generated code for this Image Widget... ClipRRect(   borderRadius: BorderRadius.circular(8),   child: Image.network(     'https://images.unsplash.com/photo-1630492782892-74f99406dc59?w=500&h=500',     width: double.infinity,     height: 200,     fit: BoxFit.cover,   ), )

### Visual documentation

![Captura de pantalla 2024-12-03 112554](https://github.com/user-attachments/assets/4b8b133a-9082-46fb-a0d6-e9251b067776)

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform:Production
- Browser name and version:Microsoft Edge Version 131.0.2903.70 
- Operating system and version affected: HP ProBook x360 11 G5 EE
```

### Additional Information

it doesn't give me a code error, but the action I detailed earlier doesn't function

**Comment by Alezanello** [comment]
Hello!

To take a closer look at your project, we’ll need you to generate a Bug Report Code. Please right-click any widget in the Widget Tree to open the menu, then select the "Generate Bug Report Code" option.

Thank you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
