### ISSUE TITLE
Can't set an library imported app state from consumer project

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5028]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/ee3aa3593bd44a99a660fc06620fc834

- import library with library app state, can access everythign perfectly fine
- go to action editor, select update app state, the library app state appears
- try to compile and it breaks

### Expected Behavior

not break

### Steps to Reproduce

- import library with library app state, can access everythign perfectly fine
- go to action editor, select update app state, the library app state appears
- try to compile and it breaks

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wz8mB25dOtbxZ1rr+c8J7/ScWCDt/U40z0sNxTRMdGLKqBKYPX/z4UBJoTbyndkFmIE2Knj4f3PTNm9z1Ce0pPTuWUaJfzKpiTgKXWl+6b66vPquSZXFUGshMCWKZ1J23vBJ/BNJZWiEWwU6EN+m+cBXaN4z3Pm0FJc/8LZ3XvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

https://www.loom.com/share/ee3aa3593bd44a99a660fc06620fc834

### Environment

```markdown
latest FF mac desktop
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry to hear you're experiencing this issue. The good news is that it will be fixed in the next deployment!

I'll go ahead and mark this issue as a duplicate since we already have an internal ticket tracking it. If the issue persists after the next deployment, please feel free to open a new ticket, and we'll address it right away.

Thank you for your understanding!

**Comment by chuggmuffinReturns** [comment]
Hurray! This will make things waaaaaaayyyyyyyy easier! Love it!

Assuuuuuming that "fixed" means we will be able to edit library app state from consumer project...

...vs what happened with the font size variable where some number of people (including myself) pointed out the variable symbol was there and then no longer was there in the next update........

...that made me :(

But now that it seems like I am low key famous in the FF QA office...

...@Alezanello any chance you'll allow imports into custom functions?
