### ISSUE TITLE
Listview components not loading or show

### ISSUE THREAD

**Issue by KelvemFernandes** [FlutterFlow/flutterflow-issues#5029]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to display data returned from a json array. I can manipulate them perfectly, when I run the test mode of flutterflow, it works, but on android it doesn't work.

### Expected Behavior

The data is displayed regardless of where it is being tested, whether it is debug, run or even deploy.

### Steps to Reproduce

Create a page, add a column to align the components from top to bottom. Now, add a container with width and height, after adding, place a listview inside and generate children so that you can access each data stored in any array, after configuring what will be displayed and downloading the apk. it won't work. I still limited the generation of children to 3, as it is about displaying data for ranking.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki8mB05NOsdtA15CAbfoxiWUQJjM9TL03pu0bFEggGLbrBIYMacjRdRBuZN+idFZDKEWJrEEGwNLshobLEvAVGzKVGYg7wqVIZg/wQke/aoSgPs2CSWslL/tnC1SC3KSNoCV7Os12SnNh7V6mC/CUfCjAHZP6Zwh9f6PHaOI=

### Visual documentation

![Captura de tela 2024-12-03 201036](https://github.com/user-attachments/assets/b9480a53-7629-4f80-b18f-46987d786b09)

https://github.com/user-attachments/assets/d64ca251-7efc-46d0-b220-cc656722680b

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I just accessed your project, and it seems the behavior has changed. Has the issue been resolved on your side?

Looking forward to your update!

**Comment by KelvemFernandes** [comment]
Hello, I tried to do it another way and it still has the same problem, remembering that this problem is like this when I generate the apk and run the app on android, in the test and run it works.

**Comment by KelvemFernandes** [comment]
I went back to the version I was before, to be able to produce this result shown. Basically I'm pulling data from an API through an endpoint, it gives me back arrays, all I'm doing is trying to traverse them in the listview. When I run the "test" or "run" mode it works. But when I try to generate an APK and install it on the device, the data does not show and this gray screen is gray.
