### ISSUE TITLE
Firestore rules change from 'Out Date' to 'Deployed' when I run a test, and sometimes they change randomly

### ISSUE THREAD

**Issue by tech-bio** [FlutterFlow/flutterflow-issues#5031]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been working on a Firebase project without issues, but since I added a new collection, the Firestore Rules switch between 'Deployed' and 'OutDate' when I run a test. I deleted the collection and restored a previous version, but the problem persists. Even if I switch tabs within FlutterFlow, the status changes from 'Deployed' to 'OutDate' for no apparent reason.

### Expected Behavior

I just want to update the Firestore rules to 'Deployed,' but for some reason, they randomly change to 'OutDate' even when I’m not making any changes to the project.

### Steps to Reproduce

1.Project sync to a Firesbase project exist
2.Go to firestore section in flutterflow
3.Down to firestore rules
4.Press deploy
5.State change to deployed
6.Go to another tab, for example app values
7.return to Firestore tab
8.Firestore rules mark as "Out date" again

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Container(   width: 370.0,   height: 230.0,   child: FlutterFlowPieChart(     data: FFPieChartData(       values: [         _model.countNuevoParaPIECHART!,         containerDashboardRecord!.contactado,         containerDashboardRecord!.interesado,         containerDashboardRecord!.calificado,         containerDashboardRecord!.propuesta,         containerDashboardRecord!.ganado       ],       colors: [         FlutterFlowTheme.of(context).primary,         Color(0xFF6F28CB),         Color(0xFF2536A4),         Color(0xFF539A80),         Color(0xFF4A57C1),         Color(0xFF3E8DD0)       ],       radius: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0],       borderColor: [         FlutterFlowTheme.of(context).primaryBackground,         Colors.transparent,         Colors.transparent,         Colors.transparent,         Colors.transparent,         Colors.transparent       ],     ),     donutHoleRadius: 0.0,     donutHoleColor: Colors.transparent,     sectionLabelType: PieChartSectionLabelType.percent,     sectionLabelStyle: FlutterFlowTheme.of(context).headlineSmall.override(           fontFamily: FlutterFlowTheme.of(context).headlineSmallFamily,           letterSpacing: 0.0,           useGoogleFonts: GoogleFonts.asMap()               .containsKey(FlutterFlowTheme.of(context).headlineSmallFamily),         ),   ), )

### Visual documentation

Its mark out of date
![Captura de pantalla 2024-12-03 174149](https://github.com/user-attachments/assets/4af8f2c2-5d6a-4402-a776-359b985c3046)
Deploying, dont show a diff but need deploy anyway
![Captura de pantalla 2024-12-03 174332](https://github.com/user-attachments/assets/bca052a9-3296-4c5e-9521-edecc2d46ae6)
Deployed
![Captura de pantalla 2024-12-03 174441](https://github.com/user-attachments/assets/98ecb0e7-10e6-424d-ad1c-e1e8854be05e)
I go to other tab then return to Firestore tab and its out of date again, i cant use my data in my project
![Captura de pantalla 2024-12-03 174619](https://github.com/user-attachments/assets/59e2d1ef-7d78-4e5b-b63a-505bca3075ca)

### Environment

```markdown
- FlutterFlow version:3.24.2
- Platform:Windows 11 laptop and Web
- Browser name and version:Microsoft Edge Versión 131.0.2903.70
- Operating system and version affected: Windows 11
```

### Additional Information

I was working in a flutter flow chart i made a collection then dont stop change to out of date, then some data dont show propertly. Just want to deployed the firestore rules right

**Comment by Alezanello** [comment]
Hello!

I have a few questions to better understand your issue:

1. Are the rules correctly reflected in your Firestore database?
2. Does your Firebase project contain multiple databases?
3. Are you testing Push Notifications in your current setup?

Additionally, could you please provide a Bug Report Code?<br>To generate it, right-click on any widget in the Widget Tree, and from the popup menu, select "Generate bug report code."

Looking forward to your response so we can assist you further!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
