### ISSUE TITLE
Clicking on the error does not navigate to it, making it impossible to locate the issue

### ISSUE THREAD

**Issue by xiaoyaoyun** [FlutterFlow/flutterflow-issues#5033]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking on the error does not navigate to it, making it impossible to locate the issue. #5032
<img width="329" alt="截屏2024-12-04 15 46 56" src="https://github.com/user-attachments/assets/0c04da6f-635b-4bae-b06c-5cae33e39e12">

### Expected Behavior

<img width="329" alt="截屏2024-12-04 15 46 56" src="https://github.com/user-attachments/assets/80ab8c97-9fdb-475a-8707-84e275a5f778">
Clicking on the error message can automatically navigate to the location of the issue.

### Steps to Reproduce

I don’t know how to reproduce it; this is the first time such a strange phenomenon has occurred.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Clicking on the error does not navigate to it, making it impossible to locate the issue

### Visual documentation

<img width="329" alt="截屏2024-12-04 15 46 56" src="https://github.com/user-attachments/assets/ad0413a7-6c11-4318-9386-5cf73e14450d">

### Environment

```markdown
- FlutterFlow version: 5.0.14
- Platform: FlutterFlow Desktop
- Browser name and version: MacOs
- Operating system and version affected: MacOs Ventura 13.5
```

**Comment by xiaoyaoyun** [comment]
I suspect that the FlutterFlow server experienced issues during this time period.

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue on my end. When I test with a conditional that hasn't been set, it correctly navigates to the expected place. Could you confirm if your conditional is inside an action block?

Additionally, could you please provide a Bug Report Code?<br>To generate it, right-click on any widget in the Widget Tree, and select "Generate bug report code" from the popup menu.

Let me know so we can look into this further!

**Comment by xiaoyaoyun** [comment]
> Hello!
> 
> I wasn't able to replicate the issue on my end. When I test with a conditional that hasn't been set, it correctly navigates to the expected place. Could you confirm if your conditional is inside an action block?
> 
> Additionally, could you please provide a Bug Report Code?To generate it, right-click on any widget in the Widget Tree, and select "Generate bug report code" from the popup menu.
> 
> Let me know so we can look into this further!

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWscpCbw4bIYj2P4lzY876P0tWXumoS2x6IFmMp14C063FkuOSU8IpHzebc659+ZBTFxXyc3GjabWTF7qKZURSQOFUf26B4cKrhRMlH/VZWEIe7zm6fN/JbB/ANIS3PHo8Sq/LZO4=

**Comment by xiaoyaoyun** [comment]
Is there a temporary solution? I'm stuck on this issue right now.

**Comment by Alezanello** [comment]
Hello!

I just accessed your project, and I didn’t encounter any errors related to the conditional action as you mentioned. Could you confirm if this issue has been resolved on your end?

Looking forward to your update!
