### ISSUE TITLE
FlutterFlow Desktop Windows Crash

### ISSUE THREAD

**Issue by syg-eliseu** [FlutterFlow/flutterflow-issues#5036]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow Desktop demonstrates instability on Windows. After being installed on a clean installation of Windows 11 23H2 runs normally, for some reason after being closed, it cannot be executed, it keeps loading infinitely.

I tested it on 2 notebooks and I have the same problem:

**Lenovo Ideapad 3i**
Windows 11 23H2

**Samsung 300E**
Windows 10 22H2

Analyzing the Windows logs I identified the dlls that break: "ntdll.dll" and "KERNELBASE.dll".

My attempts at resolution:

- Windows 11 shallow formatting - Lenovo (Keeps files)

- Full formatting of Windows 11 - Lenovo (erases everything)

- Full formatting of Windows 10 - Samsung

In these 3 situations that normally resolve all problems, FlutterFlow Desktop continues to fail when using these components. After completely formatting Windows, before even installing other things, I installed Visual C++, which installs the system components necessary for Flutterflow to run.

But unfortunately I had the same error happening.

https://github.com/user-attachments/assets/1ff5805a-0282-4f9c-9e11-a2d65ca4c4e8

### Expected Behavior

I hope FlutterFlow can easily run on any Windows device

### Steps to Reproduce

Cannot be reproduced well

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no bug code

### Visual documentation

![Captura de tela 2024-12-04 092259](https://github.com/user-attachments/assets/4016f256-e1c2-467b-92a5-1dbd03ad0f37)
![Captura de tela 2024-12-04 092248](https://github.com/user-attachments/assets/22508bd3-a404-4acf-94d9-2e33cb2bf370)

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Windows Desktop
- Browser name and version: 
- Operating system and version affected: Windows 11 23H2, Windows 11 22H2
```

### Additional Information

If I open and close FlutterFlow several times it logs out, if I try to log in again the infinite loading continues.

**Comment by rzambroni** [comment]
Hello,

Thank you for bringing this to our attention!

This issue is currently being addressed in an ongoing ticket as it’s affecting some Windows users. To assist us with troubleshooting, could you please refer to that ticket ([#2584](https://github.com/FlutterFlow/flutterflow-issues/issues/2584)) and add your details there? This will help us consolidate all the information in one place and streamline our efforts.

To avoid duplicating work, I’ll go ahead and close this ticket as a duplicate. We truly appreciate your understanding and cooperation as we work to resolve this.

Thanks again!

**Comment by syg-eliseu** [comment]
Hello, unfortunately the other ticket did not have a defined resolution and has been discussed for months.

What will be the final resolution that FF will give to me and other users who are facing this problem.

Particularly, I am available for a remote connection or any type of assistance so that your engineering team can effectively capture the problem.

I just want this to be resolved because my productivity using the web version has dropped by almost 50%. The web version does not compare to the desktop version in terms of system fluidity. That's why we need the Windows version to work correctly.

Help us, please.


> (Text translated from Portuguese)

**Comment by WarRusher** [comment]
Hi, 
I have the same issue.  Deleting the "firestore" folder under my AppData allows you to start up the app, but it crashes within a few mins when I click into a project.  Will update the other ticket as well. 
Regards

**Comment by tupfe** [comment]
i have the same issue
