### ISSUE TITLE
StaggeredView blank screen (white) when scroll up

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#5037]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In StaggeredView when I scroll down, everything works smoothly, but when I scroll up it looks like things gets broken and nothing is showing (white screen)

### Expected Behavior

To work normally and be able to scroll up & down

### Steps to Reproduce

1. create new page
2. add a StaggeredView
3. populate it with dynamic content
4. set height to fixed (300 px)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShfLl05dgotdc7ofQLflAhQcgQlgnU+cZjuxEdxMvIrbyOu9/ZuClSFdvUs+/Y1NhHFH/rE8x3MmPi97AVsEEaAiVRrpO/6V2VDnKe3q8R7LREruWPHx5P9pUGG6i5Lujmh0lBNt1dUEj3F+XN+yAQgLqN5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/dc03d662-d301-4525-abb6-a7b29785d9fb)

### Environment

```markdown
FlutterFlow v5.0.12+ released November 20, 2024
Flutter version is 3.24.2
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue on my end. Here’s a public project you can duplicate to check it out yourself: [https://app.flutterflow.io/project/qa-3197-13wwtt](https://app.flutterflow.io/project/qa-3197-13wwtt)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/91bd0cf3-d369-4f45-865f-1706249be54c/c84db3d2-13f5-4cd5-b67c-6c2687680503?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MWJkMGNmMy1kMzY5LTRmNDUtODY1Zi0xNzA2MjQ5YmU1NGMvYzg0ZGIzZDItMTNmNS00Y2Q1LWI2N2MtNmMyNjg3NjgwNTAzIiwiaWF0IjoxNzMzNDA2Mzg5LCJleHAiOjMzMzAzOTY2Mzg5fQ.GmqDNZxO52pIiTezqyAJoQBLp857jgGep6vdvs6pGv4 " alt="asdasdasdasd.gif" width="1803" data-linear-height="898" />

Let me know if you need further assistance!

**Comment by alih552** [comment]
Hello Alezanello,

When I clone your project and run it on test mode it shows like this:
![image](https://github.com/user-attachments/assets/f32a68fe-8834-4c45-8ae3-bd0c6d342a05)


bug report: ITFTh/LhuYVhouYD+KXiLfkxhiI7CUMYXOYvitUbRRQaIoz1CLMqY8mnPhZuZMPgdG9mPmG2p14Hw6HTj+zhE/AqGzCrft1TyqlcFgqXLX+6SrmTF7iWP2hRO5tbI26H06arvSZdLvFhL3wNwGGXOO+ucz/fCbLHC0Q8Sq/LZO4=

**Comment by alih552** [comment]
Hi!

Ok I figured out the cause of the issue:
 - if you set the dynamic generated children to have a conditional visibility like (index in list > 16) it will miss up when you scroll up and hide everything.
 
 
 and the reason why I am doing this is because I want to skip the first 16 items for the generated dynamic children.

**Comment by Alezanello** [comment]
Nice, could you do that in the project you cloned from mine to test it?

**Comment by alih552** [comment]
@Alezanello IDK why but from my end the images are not being generated at all.

Bug report code: ITFTh/LhuYVhouYD+KXiLfkxhiI7CUMYXOYvitUbRRQaIoz1CLMqY8mnPhZuZMPgdG9mPmG2p14EwaDHuePfN/I4PRCZbY85+ZNxWzyWfHyRRa2TF7iWP2hRO5tbI26H06arvSZdLvFhL3wNwGGXOO+ucz/fCbLHC0Q8Sq/LZO4=

**Comment by Alezanello** [comment]
Hello!

I just tested the code from the bug report you provided, and everything is working perfectly on my end. To test it with images, I recommend downloading the code and running it locally or deploying it to the web with Canvas Kit disabled.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e1641f87-86b6-46b0-b33d-dd6a9853cb62/2d11f029-2972-45a1-b923-be914ad29112?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMTY0MWY4Ny04NmI2LTQ2YjAtYjMzZC1kZDZhOTg1M2NiNjIvMmQxMWYwMjktMjk3Mi00NWExLWI5MjMtYmU5MTRhZDI5MTEyIiwiaWF0IjoxNzM0MTIyMzE2LCJleHAiOjMzMzA0NjgyMzE2fQ.ba_lyqBNWRhHislt52J7KJHpldU3x689rSSMCK6BGO4 " alt="staggered view.gif" width="475" data-linear-height="798" />

**Comment by alih552** [comment]
Hi @Alezanello 

On a real device with real data being retrieved from Firestore the bug is happening, I suggest testing with real data.

> * if you set the dynamic generated children to have a conditional visibility like (index in list > 16) it will miss up when you scroll up and hide everything.

**Comment by Alezanello** [comment]
Hello!!<br><br>Sorry for the late response, still can't reproduce on Real Device, I have a Samsung A52 Android 14<br>Can you share a video from the real device to see the behavior?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
