### ISSUE TITLE
 adding strange  %0A to video link => can't display them

### ISSUE THREAD

**Issue by markusbecher** [FlutterFlow/flutterflow-issues#5038]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/b53833137caa44378366f0796a6a1d88

### Expected Behavior

when loading / calling video string - it adds sometimes  %0A to it => can't be displayed.

### Steps to Reproduce

when reading video string don't add anything to it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlfLIwIhhnNxE+s/yY8dvliEwFnIca+YZhOtta0gYNbL1PKQPbuveT1VDXM+rSmNqHVCgmlwHw/CMhYXlJvUoHE6EQ5R8/rVQVAqXJHGmRKaSCZOWVWpQAe1gfxWe0aW7vwp7HNBpWHMtig/GSw==

### Visual documentation

https://www.loom.com/share/b53833137caa44378366f0796a6a1d88

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: windows
- Browser name and version: chromse
- Operating system and version affected: windows
```

**Comment by Alezanello** [comment]
Hello!

This is very interesting! Does this happen with all links, or just the specific one you shared?<br>Have you tried adding it directly to Firestore instead of using the CMS? This could help determine if the issue is specific to the CMS.

Looking forward to your feedback!

**Comment by markusbecher** [comment]
yes - was my error.... there was a blank at the end...   corrected it.. now it works.
