### ISSUE TITLE
Data that is displayed in a "Listview" is not shown when I install the app APK version.

### ISSUE THREAD

**Issue by KelvemFernandes** [FlutterFlow/flutterflow-issues#5040]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to display data from a json array through an API, it doesn't display that data when I install the android version of my app, but it works on the web.

### Expected Behavior

The data is displayed when you install the app, just like on the web.

### Steps to Reproduce

Create a "Widget" for horizontal listing.

Add in the listview the generation of children from a variable that stores json array.

Create components to display the array information.

When you save and generate the APK file, as soon as you install it, you'll see that the screen will turn gray.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki8mB05NOsdtA15CAbfoxiWUQJjM9TL07r+5xb0gvIrbyOu9/ZvT4XEhWTsjgSmlhHFmGpGEF0eD2keH1EfU4PT+VbZxe+KVUVA7Jd3q8R7qQDZaJP398TJ9VIBWe5KaJnCNAWPpoW3gs3DuPNtmXQXXtJ5O/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/9fc9af05-379b-4bea-8f96-03eb55401c9d

![Captura de tela 2024-12-03 201036](https://github.com/user-attachments/assets/05372077-003b-4699-93df-d7ac1dffbcab)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

It seems there might be an issue with how you're retrieving information using JSON Paths. I highly recommend downloading the JSON response, creating a **Data Type** from it, and parsing the response as a Data Type. This approach allows you to directly access the information without the risk of errors related to JSON Paths.

Here’s the documentation to guide you through the process:<br>[API Response JSON To/From Data Type](https://docs.flutterflow.io/resources/backend-logic/rest-api/#api-response-json-tofrom-data-type)

This method is a game-changer—it simplifies how you retrieve and manage data from JSON, making your workflow much more efficient and error-free.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
