### ISSUE TITLE
Figma Importer Not Working

### ISSUE THREAD

**Issue by aaksa** [FlutterFlow/flutterflow-issues#5041]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I tried to import a figma design but it wont work I got only a GET : https://api.figma.com/v1/files/ 404 (Not Found).
and this message on FlutterFLow : Error loading your Figma project. Please check that the URL and access tokens are correct.

### Expected Behavior

The import is started and worked

### Steps to Reproduce

1. Click on Figma theme import
2. Set the url
3. set the token

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sl/H134hItbxH1rXuY+9VtDwsJlg1RYIV09ZAEE4bfbbqOpohXOj9SFRuZNe6T2w7JWCi8Tsxw6mOuOOWF8ItPiibUbZ//7pidjvjWlGQMoSgPZOZP3Z8P9FWf0eHzba3qyRSNbN0SXNn62amF/K9c3LdH4/6PEQzOMiaD9rL+2ChGhzOXn0Jg1ZSfCvr

### Visual documentation

<img width="472" alt="Screenshot 2024-12-05 at 10 31 58" src="https://github.com/user-attachments/assets/6316b3fe-cec8-43bc-a90f-124e71f5ebf1">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I couldn’t replicate this issue on my end. Could you please double-check to ensure that the URL you’re using for the import is correct?

You can refer to the documentation for guidance on the proper URL path:<br>[Import Figma Theme Documentation](https://docs.flutterflow.io/concepts/design-system/#import-figma-theme)

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
