### ISSUE TITLE
VSCode Extension Push Does Absolutely Nothing

### ISSUE THREAD

**Issue by Kemerd** [FlutterFlow/flutterflow-issues#5042]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can pull from my FlutterFlow project just fine, my VScode is all setup. But if I start a code editing session, make an edit on my VScode file, save it. Then push to FlutterFlow, it says it successfully did it, but I see no updates of any kind in FlutterFlow nor any errors or indications the push failed. If I pull again after pushing it deletes my code. 

### Expected Behavior

When I push my code, it should instantly update inside of FlutterFlow, a workflow for a paying customer where I have to copy and paste a file every time I make an edit is awful

### Steps to Reproduce

1. Setup VSCode plugin in Cursor or normal VSCode
2. Pull project
3. Start code editing session
4. Make an edit to a custom widget or action
5. Push to FlutterFlow
6. Note the success message and lack of error messaging
7. Realize that the code was not updated in the FlutterFlow project at all

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

My code

![image](https://github.com/user-attachments/assets/51c3c6aa-5c7a-4e53-bdca-edca4041150c)

I push it to FlutterFlow

![image](https://github.com/user-attachments/assets/f77397a6-e98f-4bca-bf34-8ee85107d1b0)

Note the success message

And no change in FF
![image](https://github.com/user-attachments/assets/61b522a0-9345-4e32-9ac5-506fd184bfde)

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Windows & Mac same results 
- Browser name and version: Chrome
- Operating system and version affected:
```

### Additional Information

Please fix this, I am begging you. This workflow is completely unusable, and the fact that a paying customer has to copy and paste an entire file to make edits is really ridiculous

**Comment by Alezanello** [comment]
Hello!

This issue has been confirmed and forwarded to the engineering team for a fix under the following ticket:<br>[GitHub Issue #4050](https://github.com/FlutterFlow/flutterflow-issues/issues/4050)

I’ll go ahead and mark this one as a duplicate. Thank you for bringing it to our attention!
