### ISSUE TITLE
Deploying Web App using Firebase Hosting for Flutter Web

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#5043]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deployed and test in Beta channel and refresh one of the page after authenticate its showed 
This file does not exist and there was no index.html found in the current directory or 404.html in the root directory.

### Expected Behavior

Should take what we have in firebase json because FF already generate it when you pull the code in local !

### Steps to Reproduce

1. Exporting code 
2. setup project 
3. enable firebase experiments firebase hosting ot flutter project 
4. launch firebase deploy 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jMrluJdgocNJ7qr+KcJV9SU5Jn49R5E/l+17aCosfZT2BLMcec/RVERoONe+T1FEJUyJv2oW3MmNj4f9UsAVAASZQKk/1LthWjqXJV+gRKq0FJWgY3B9P+lmCFClyqW7rx1vCLR1LyEu1GD3GdiQRT3BNu/xOkQWDa/LZO4=

### Visual documentation

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/445769c7-d729-4bf1-96fc-a017d8f9377e">

### Environment

```markdown
- FlutterFlow version: v5.0.14
- Platform: Web
- Browser name and version: chrome latest
- Operating system and version affected: macOS latest
```

**Comment by ImadBouirmane** [comment]
My suggestion here is to support already a good firebase.json config file that solve this issue for every Web App in FF.
Thanks

**Comment by ImadBouirmane** [comment]
I made some changes if you can check the official link: https://app-limacreation.com/
Firebase.json
Adding this bracket 
`  "public": "build/web",
    "headers": [
      {
        "source": "/**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache, no-store, must-revalidate"
          }
        ]
      }
    ],`
    and this one: 
    ` "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]`
    
    **I propose to add this new brackets to be by default and avoiding this issue for next deployments !
    I don't use this custom domain in FF !**

**Comment by Alezanello** [comment]
Hello!

It seems this is not a FlutterFlow issue but rather an implementation-related matter. There are various ways to host a Flutter app across different servers, and it is the user’s responsibility to correctly configure and accommodate the files for their chosen deployment method—especially for web apps.

In your case, you needed to make certain changes to get it working, but these changes may vary depending on the deployment setup. The current default settings are configured to work for many common use cases.

Based on this, I will mark this issue as **Not a Bug**.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
