### ISSUE TITLE
The "page state" and "component state" have an "uploaded file" option, but the "app state" and "custom data type" do not. Could you add the "uploaded file" option to the "app state" and "custom data type"?

### ISSUE THREAD

**Issue by xiaoyaoyun** [FlutterFlow/flutterflow-issues#5048]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3a6b2648-d4da-4767-8877-96522574d0c1/515546ea-29d8-4a68-8346-c94c591fec22?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYTZiMjY0OC1kNGRhLTQ3NjctODg3Ny05NjUyMjU3NGQwYzEvNTE1NTQ2ZWEtMjlkOC00YTY4LTgzNDYtYzk0YzU5MWZlYzIyIiwiaWF0IjoxNzMzNDg0MDUxLCJleHAiOjMzMzA0MDQ0MDUxfQ.ytlsH8qqBik65RUrYSl4se7IbASpXzL67_gexOpGmN4 " alt="截屏2024-12-06 09 37 14" width="531" />

### Expected Behavior

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/05c42d12-bc11-45ea-a3d8-5b89a85cbe56/5a05925c-3785-44f3-b3d7-bddef165481b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNWM0MmQxMi1iYzExLTQ1ZWEtYTNkOC01Yjg5YTg1Y2JlNTYvNWEwNTkyNWMtMzc4NS00NGYzLWIzZDctYmRkZWYxNjU0ODFiIiwiaWF0IjoxNzMzNDg0MDUxLCJleHAiOjMzMzA0MDQ0MDUxfQ.tCpzCdn5ev80D2vgU48jBdxluvVOJkH1wRjHNpRgDPc " alt="截屏2024-12-06 09 37 51" width="319" />

### Steps to Reproduce

a suggestion, not a bug

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWsct/cxQcB4j4E4oiduClXxJWZMCzaHxYGVa0pDgy/+D3ktr1V+0EaCmYfIBizKVUERPPbGCtb5StDKu8ZUZfEfhYGB26yLSZhRRCGPFfLS0t2HGQJNivVT6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fe983cd3-1682-4d7f-a0cb-463ab611a49d/399cae49-175c-419f-9dc4-82dbcb5e6d7e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZTk4M2NkMy0xNjgyLTRkN2YtYTBjYi00NjNhYjYxMWE0OWQvMzk5Y2FlNDktMTc1Yy00MTlmLTlkYzQtODJkYmNiNWU2ZDdlIiwiaWF0IjoxNzMzNDg0MDUxLCJleHAiOjMzMzA0MDQ0MDUxfQ.Srk_2VqkVsIwaVBNkUIC_zBd19Ll3qsG24jeurQWQUM " alt="截屏2024-12-06 09 37 14" width="531" />

### Environment

```markdown
- FlutterFlow version: erery version
- Platform:flutterflow desktop
- Browser name and version:flutterflow desktop
- Operating system and version affected: macos
```

### Additional Information

*No response*

**Comment by paulperez-dev** [comment]
Hi @xiaoyaoyun! This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog, and we will get to it as soon as possible. Thanks for your feedback!
