### ISSUE TITLE
URGENT: Failed building .apk - "AAPT: error: resource android:attr/lStar not found.", succeeded locally

### ISSUE THREAD

**Issue by giladresisi** [FlutterFlow/flutterflow-issues#5049]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Failed buidling for Play Store inside FlutterFlow but succeeded when downloaded the code locally, with both latest Flutter version (v3.24.5) and same as in FlutterFlow (v3.24.2). Got the error in the title.
I currently can't deploy to Google Play, please help here urgently.

### Expected Behavior

Expected successful build

### Steps to Reproduce

1. Deploy to Play Store from within FlutterFlow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8r13ItOxLhc+KrAdfpVnSQ7Qkc3argo0MpOGDsdF4iuPOxzaeDRQExtOdOkTHx9KEWIhlMF+NLMjd7hGsc3Ewecfp9xyZAJSTvjcEW/aoSOPauwZkdAQJhgCXKO3KuNpQpTOrB2dVIM7DuIH+m8aDDYJo/7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-12-06 112620](https://github.com/user-attachments/assets/0703b719-4719-438c-aede-1fc0ab257dcd)

### Environment

```markdown
- FlutterFlow version: v5.0.13+
- Platform: Web
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Windows 11 Pro
```

### Additional Information

Looks as if it might be related to https://github.com/FlutterFlow/flutterflow-issues/issues/3942
Can't deploy app fixes to Google Play as of now, my users are waiting... please help ASAP.

**Comment by Alezanello** [comment]
**Hello!** 

Thank you for sharing details about your project. While it seems that your project can be built locally, we don’t have the necessary permissions to assist with this specific issue.

This GitHub issue tracker is intended for reporting reproducible issues on new, blank projects. For project-specific situations like yours, we recommend reaching out to our support team for personalized assistance. You can contact them via **support@flutterflow.io** or through the **in-app chat** feature.

We appreciate your understanding, and our support team will be happy to assist further!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
