### ISSUE TITLE
Clicking on the error does not navigate to it, making it impossible to locate the issue

### ISSUE THREAD

**Issue by xiaoyaoyun** [FlutterFlow/flutterflow-issues#5050]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking on the error does not navigate to it, making it impossible to locate the issue.
<img width="329" alt="截屏2024-12-04 15 46 56" src="https://github.com/user-attachments/assets/ee7903c3-b4e3-4a6d-b267-d1cead79a55b">

### Expected Behavior

Clicking on the error message can automatically navigate to the location of the issue.

### Steps to Reproduce

I don’t know how to reproduce it; this is the first time such a strange phenomenon has occurred.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWscpCbw4bIYj2P4lzY876P0tWXumoS2x6IFmMp14C063FkuOSU8IpHzebc659+ZBTFxXyc3GjabWTF7qKZURSQOFUf26B4cKrhRMlH/VZWEIe7zm6fN/JbB/ANIS3PHo8Sq/LZO4=

### Visual documentation

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWscpCbw4bIYj2P4lzY876P0tWXumoS2x6IFmMp14C063FkuOSU8IpHzebc659+ZBTFxXyc3GjabWTF7qKZURSQOFUf26B4cKrhRMlH/VZWEIe7zm6fN/JbB/ANIS3PHo8Sq/LZO4=

### Environment

```markdown
- FlutterFlow version: FlutterFlow 5.0.14
- Platform: FlutterFlow Desktop
- Browser name and version:FlutterFlow Desktop
- Operating system and version affected: MacOs
```

**Comment by paulperez-dev** [comment]
Hi @xiaoyaoyun! This issue has already been reported and is being tracked here: #5033. Please feel free to refer to that thread for future updates.

I'm closing this issue.
