### ISSUE TITLE
Max characters allowed does not work with combine text

### ISSUE THREAD

**Issue by glamourhammer** [FlutterFlow/flutterflow-issues#5051]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When combine text is used for a text field, the Max Characters Allowed parameters is ignored or not applied. As a result there is no control over the text string length and character overruns occur.

### Expected Behavior

The Max characters allowed parameters should limit the total character count of the combined text field to the number specified in the parameter.

### Steps to Reproduce

1. Create a page
2. insert a text field and set Max characters allowed to some value
3. set the text field value to combine text and add >1 strings
4. Enter values for each string such that the total character count exceeds that of the Max characters allowed parameter
5. Observe that the Max characters allowed parameter is ignored

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi/Hlx5BOvuFF0b6JKvlVhSQXJmYgaIEZ0cpOEC0jF7KuBuwuPc7BdVtBYM+4aVNcHWejoGcK+Pz9uNrlO+wnNTGcc7ZxyLpAZArOe2ihaaa3DpOaf0FCM/1RIWaa1J6VkxV/PsltL04N7U2AOequZAvDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="140" alt="Screenshot 2024-12-06 at 17 27 10" src="https://github.com/user-attachments/assets/7ff9ceb0-88c2-44c1-99a2-51748b7c7a64">
<img width="188" alt="Screenshot 2024-12-06 at 17 27 23" src="https://github.com/user-attachments/assets/a3efd423-4d12-450f-b97a-fba1f3bddd13">

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Web
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: MacOS Sonoma 14.6
```

**Comment by paulperez-dev** [comment]
Hi @glamourhammer,

Thank you for reporting this issue! I tried to replicate it on my end, but it seems the limit is being applied as expected.

Here’s the project I used to test it: [https://app.flutterflow.io/project/qa-3213-q17bu6](https://app.flutterflow.io/project/qa-3213-q17bu6)

**Comment by glamourhammer** [comment]
Are you hardcoding the values? Perhaps the issue is limited to variables...

**Comment by paulperez-dev** [comment]
Hi @glamourhammer,

I’ve updated the project to combine the text from two variables, and the max length is still working as expected. The previously shared project link should now reflect these updates.

**Comment by glamourhammer** [comment]
The only other difference I see is that I am observing the unexpected behavior within a list item. If you place the combine text within a list item can you reproduce in your environment?

**Comment by paulperez-dev** [comment]
Hi @glamourhammer,

I’m observing the same correct behavior (using a ListView). Are you able to replicate this issue in a blank project?

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
