### ISSUE TITLE
Desktop app crashing when uploading hi-res .jpg

### ISSUE THREAD

**Issue by Kemerd** [FlutterFlow/flutterflow-issues#5058]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The desktop apps when adding a media asset of a large size

### Expected Behavior

It should upload without crashing

### Steps to Reproduce

1. Navigate to Media assets
2. Click Upload Media
3. Upload a jpg of size 4080 x 3072 (around 3MB)
4. Note the crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

![image](https://github.com/user-attachments/assets/924ef0c8-69a1-43cd-a883-f8b457788097)

### Environment

```markdown
- FlutterFlow version: 5.012
- Platform: Windows Desktop App
- Browser name and version: NA
- Operating system and version affected: Windows 11 64 Bit
```

### Additional Information

Not highest priority as it works inside of browser

**Comment by rzambroni** [comment]
Hi Kemerd,

Thank you for the report! I attempted to replicate the issue on my Windows setup, and while I did receive a warning, the file uploaded successfully without crashing.

Would you be able to share the specific file you’re using that causes the crash? Additionally, if you could provide the logs from the moment of the crash, it would greatly help us in troubleshooting the issue.

Thank you for your help!

Best regards,

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/23bfcb6f-0f24-4232-8394-04dec6cf74ce/cc4174c1-bdd2-4ae3-8b1e-da486d073278?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yM2JmY2I2Zi0wZjI0LTQyMzItODM5NC0wNGRlYzZjZjc0Y2UvY2M0MTc0YzEtYmRkMi00YWUzLThiMWUtZGE0ODZkMDczMjc4IiwiaWF0IjoxNzMzNTUzNjkwLCJleHAiOjMzMzA0MTEzNjkwfQ.O3Ai1jOemzhAiBJ6Vyofc4KWCmDgHoqOnkYH8K_dcak " alt="image.png" width="1000" data-linear-height="921" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
