### ISSUE TITLE
Clipped border radius is calculated on the exterior value of the border, not the interior (and clips box shadow)

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5059]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/c6e9372fafb24aa59358968cca6f1002

when you clip content with a border the interior content is shrunk properly to the interior of the border, bot the clipping is calculated on the exterior of the border radius, not the interior of the border. 

So the border itself is blocked by interior content

### Expected Behavior

clipping calculated on the interior of the border radius plus border

also that clipping content clips child content, not its own content (ie clips the box shaddow)

There's a workaround demonstrated in the video to nest a container in a container but that is a bit of a pain 

### Steps to Reproduce

see video

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ozMr15c92pbxD7arydcFB/WAvJjs4a5I70tV6EAsYGJDnB4YMOuHBUFpWTu7hY0NHGlL88X40097PvtnxG/tcOk2Vc4Bk1c8JVh/PRl+XRq6JEZOKW0d8AcNnIWKcyMCJrQknWe5sTHs3wE+EIOyUcBLbGb7SDUVANeSKJpLOjWyBGwzdFiRs+ww+R26UEeljIVDq+f6QspZl1eTjzw==

### Visual documentation

https://www.loom.com/share/c6e9372fafb24aa59358968cca6f1002

### Environment

```markdown
mac desktop latest
```

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturns,

This is the default behavior of Flutter. As an alternative, you could clip the internal container content and apply the same border radius you are using in the external, but subtracting the width of the border you want to use.

I hope this explanation is clear! I’ll go ahead and close this issue.

**Comment by chuggmuffinReturns** [comment]
@paulperez-dev oh really?? strange...

well is what it is I guess thanks a lot! Ill test out that other method :)

**Comment by paulperez-dev** [comment]
You can test it here [https://dartpad.dev/?id=b5c4c10228bde22adf18d5f4eb21d55c](https://dartpad.dev/?id=b5c4c10228bde22adf18d5f4eb21d55c)

**Comment by chuggmuffinReturns** [comment]
thanks!
