### ISSUE TITLE
Repetitive crashes 

### ISSUE THREAD

**Issue by Omet77** [FlutterFlow/flutterflow-issues#5060]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There's no actual effect that I can see and even users while using the app. But I keep receiving crash report from Firebase Crashlytic.
![Screenshot 2024-12-08 144552](https://github.com/user-attachments/assets/7885dd79-8bc4-4e6e-b0c0-f6780cabf8b0)
![Screenshot 2024-12-08 144622](https://github.com/user-attachments/assets/271e110a-06cc-43ff-9102-243080acbfa8)

### Expected Behavior

I'm expecting to resolve these crash reports if possible.

### Steps to Reproduce

I'm not sure for the reproduction, but I can give you a full access to my app if needed. The report is from firebase and no error while using and no error in flutterflow. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError Null check operator used on a null value. Error thrown .

### Visual documentation

![Screenshot 2024-12-08 144552](https://github.com/user-attachments/assets/a1ff69f6-bbd7-4c0d-9fd0-6431c41016cb)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

Just like to ask advice and help from your expertise if there's any ways to resolve my crash reports.

Thank you so much and have a great day.

**Comment by paulperez-dev** [comment]
Hi @Omet77,

I’m so sorry to hear you’re facing this issue. Could you please share the bug report code for your project? This will help us investigate your issue more effectively.

**Comment by Omet77** [comment]
Hi paulperez-dev,
Thank you so much for your response. I resolved the issue yesterday and no crash report as of now. I used the public photo URL as default which caused this issue. I tried to change all the default photos URL and it works. 
Again, thank you so much and have a great day.
