### ISSUE TITLE
APIInterceptor not updating headers from Github code

### ISSUE THREAD

**Issue by vitul-goyal** [FlutterFlow/flutterflow-issues#5061]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to update headers using API Interceptor. When i run the code from FF, or by downloading the code, it works fine on physical device. But when i push the code to Github and pull the code to local system, API Intercept doesn't work on Physical device.

### Expected Behavior

API Interceptor code should update options.headers

### Steps to Reproduce

1. Start a new project
2. Connect to Github
3. Create custom action and attach it to an API as API Interceptor.
4. In Custom action, write this code: options.headers['Authorization'] = "1234";
5. Push to github and take pull request
6. Run on a physical device and the code will not work

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89grs9J1s/XbcZshmQ4H0A+TLJEpu0bWUkbGO/4B7AHP/T8XFZvZOazaHxmDWeJ+WMx/tLvj9/tKu46CzCtRoBl1c52ERPPbF25b5SpCZOCQkRPBZ1WIX3E15izpxFAGNRYWCUA33GYCd+RYz2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="472" alt="Screenshot 2024-12-08 at 11 08 47 PM" src="https://github.com/user-attachments/assets/e2a2269e-4db0-4e44-bd97-bee0db118142">

### Environment

```markdown
- FlutterFlow version: Any
- Platform: I tried on iOS
- Browser name and version:
- Operating system and version affected: iOS
```

**Comment by Alezanello** [comment]
It seems you might be missing some `FFAppState().update(() {});` calls to ensure the changes you make to the AppState are properly reflected.

For example, if you set an Update AppState action *On Page Load* to update the `X` variable and choose "Rebuild All Pages," it should look like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/468e8033-14af-40ce-904c-3440055f5ccc/ed4ea286-1dca-48b5-8d49-0c5911978d43?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NjhlODAzMy0xNGFmLTQwY2UtOTA0Yy0zNDQwMDU1ZjVjY2MvZWQ0ZWEyODYtMWRjYS00OGI1LThkNDktMGM1OTExOTc4ZDQzIiwiaWF0IjoxNzMzODMyNDE4LCJleHAiOjMzMzA0MzkyNDE4fQ.NhHwSpK8g6YKOseFg-5eJ1u_zrozsx9Me4MqdcwKAFg " alt="image.png" width="473" data-linear-height="122" />

Give it a try and let me know how it works for you!

**Comment by vitul-goyal** [comment]
Hi @Alezanello, i have added FFAppState() as a debug log. The problem is not with AppState. The problem is, when i download the code from Github, API Interceptor code doesn't update options.headers. It says options.headers is NULL and cannot be set. I've attached the screenshot of line which is giving the error.

The same code is working fine when i run it directly from FF or download the code and run it. But when i push the code to Github and then take a pull request and run on device, it gives this error.

You can create a new project and try. You will get the same error.

<img width="472" alt="393629671-e2a2269e-4db0-4e44-bd97-bee0db118142" src="https://github.com/user-attachments/assets/c0b47ad4-5f7f-433c-90fd-8b911bfe225c">

**Comment by vitul-goyal** [comment]
Hi @Alezanello. Did you figure out this issue? I can get on a call if required to help in understanding the issue.

**Comment by Alezanello** [comment]
Hello!

I reviewed similar issues, and as you mentioned, everything seems to work properly when using FlutterFlow or downloading the code. Just one quick question: when you push to GitHub, do you have the **Dart Fix** option enabled?

If so, could you please disable it and try pushing again? Let me know how it goes!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
