### ISSUE TITLE
"Add Action on Error" on Form Validation widget missing Page state variables

### ISSUE THREAD

**Issue by icestormpure** [FlutterFlow/flutterflow-issues#5062]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is update app state, but there isn't update page state, which I'm sure is not intended considering the form validation is page level

### Expected Behavior

There is update app state, but there isn't update page state, which I'm sure is not intended considering the form validation is page level

### Steps to Reproduce

1. Put radio button inside form validation
2. Enable Add Action on Error
3. Scroll and you wont find update page state

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsM9Oxd8F17rtKe9Wnj8vC096R5c0t9pEZxMYGOPdOoYUP8+kM0RtZM+4d1ZcIVmko2oW0tbNiPDDIPcpCyqsGq5G+sxIEzmXeHKjRpSLFJWgOnFDL9tmCGGP4J642BFBPsRoR0Y51EyUA+m+bHfdHZTKNlQsDq/LZO4=

### Visual documentation

![bug5](https://github.com/user-attachments/assets/11bf34fb-4a0d-484a-9e99-57c9b7ae814a)

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Web
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Windows 10
```

### Additional Information

The most important action isn't in the list is quite surprising tbh

**Comment by Alezanello** [comment]
Hello!

Currently, this is the expected behavior, as the Page State was never included in the list. This seems more like a feature request to add it rather than a bug. I'll go ahead and close this issue as a feature request and create an entry for it in the engineering team's backlog.

Thank you for your feedback!
