### ISSUE TITLE
Libraries: Build failure when API calls are included - "No such file or directory import '/backend/api_requests/api_calls.dart';"

### ISSUE THREAD

**Issue by ScissorHill** [FlutterFlow/flutterflow-issues#5066]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

API calls, when included in a library and imported as dependencies, cause build failure on the target project.

### Expected Behavior

I expect test mode to work on the target project, and for the API calls to functional.

### Steps to Reproduce

1. In the library project, add a new API call, e.g: https://meowfacts.herokuapp.com/
2. Publish as library
3. Add the library as dependency in the target project
4. Call the API from any action, e.g. a button.
5. Run test mode.
6. Test mode build fails with the following errors:
```
58 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/pages/login_page/login_page_widget.dart:1:8: Error: Error when reading 'lib/backend/api_requests/api_calls.dart': No such file or directory
import '/backend/api_requests/api_calls.dart';
       ^
lib/pages/login_page/login_page_model.dart:1:8: Error: Error when reading 'lib/backend/api_requests/api_calls.dart': No such file or directory
import '/backend/api_requests/api_calls.dart';
       ^
Waiting for connection from debug service on Web Server...         30.1s
Failed to compile application
```

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89gofVA7ZPyccBvoDwWCDs5R4INlMIbcCs8GZT0B4kcYs+kfklUOem8Y0FUfE6apDgX/MmOktntLfAoHzOcf4hd+ZBMdgLLVmegR4iTDoS3b0ElGehbJhG75p+rhx1TLtNhdVJi2zu2CfPIFw/qQrK2PTAjOeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/79988abc-6459-4730-9e97-a5ae25b894db)

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Web
- Browser name and version: Version 131.0.6778.108 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 22.04.3
```

### Additional Information

Libraries sounds great ideal for our scenario - involving a wide variety of apps that talk to our specific backend ecosystem components.  We were particularly excited about not having to update API calls across a number of projects, but this bug is currently a deal-breaker.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that this is a known problem, and a fix is scheduled for today’s release!

I’ll close this issue as a duplicate and link it to our internal ticket. However, if the issue persists after updating to the latest version of FlutterFlow, please don’t hesitate to open a new ticket.

Have a great day!
