### ISSUE TITLE
Nav Bar disappears when passing a parameter to the page

### ISSUE THREAD

**Issue by roystontay** [FlutterFlow/flutterflow-issues#5068]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've given access to a test project to recreate this problem.

1. Two pages, both with nav bar enabled, "Homepage" & "Page2"
2. "Page 2" has two buttons. They simply navigate back to "Homepage"
3. One of the button passes a parameter, one of the button doesn't.
4. The one which passes a parameter causes the nav bar to disappear when navigating to "Homepage". 

### Expected Behavior

Nav bar should render regardless of whether parameter is passed.

### Steps to Reproduce

As described above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ivLq0It1m8tJ+KrUY8Axmjw5JnI9bJE7k+5raCosfZT2BLMcec/RVERtOLCnd0FUOE79r2oW063yueHLOsBcORWeRaJ4/5BUYDnwLDi5aZOaFJWvPEQlBf1gGXad4LuNhxB+FPNYWkZk31yqJOSRSh/cNJDvDTJFD6/LZO4=

### Visual documentation

This video shows the problem.

https://github.com/user-attachments/assets/8693ef18-cab2-47e5-a423-bc8699b4a8c0

### Environment

```markdown
- FlutterFlow version: v5.0.13+
- Platform: Web
- Browser name and version: Version 131.0.6778.109 
- Operating system and version affected: macOSX
```

### Additional Information

Being able to pass parameters to a page and not have the nav bar disappear seems pretty important for apps that relies on nav bars for navigation?

**Comment by paulperez-dev** [comment]
Hi @roystontay,

That behavior is expected because you’re pushing the home page onto the route stack again. If you want the navigation bar to remain visible, you only need to enable the **Always Show Nav Bar on Page** switch.

That said, your approach isn’t recommended. Adding the same page to the stack can result in a navigation loop, which may lead to high memory consumption and poor performance.

I’ll go ahead and close this ticket.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
