### ISSUE TITLE
URGENT : Failed to deploy on Google Playstore 

### ISSUE THREAD

**Issue by MamadAsap** [FlutterFlow/flutterflow-issues#5069]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

failed to  deploy  my app on Google playstore. Status : failed 

### Expected Behavior

App success fully deployed. Status finished 

### Steps to Reproduce

Deploy to Play Store from within FlutterFlow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8iAz4hgoctH176Jc/pV+TsUJlgnbZZMju5xaEo0G5fNGosqZc+kM0RuZNOlY2xhfU78p2oW0fD7htjPO/AENRaWR4hxwpNhExXhUlu7RqaNFJWgQkBBO5hWJm6y58PUuBFQC/V2R1If2juQAOetaHHtK5D1PVUkDq/LZO4=

### Visual documentation

<body style="background-color:#14161C">
<style>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}
</style>
<h4>Failed Step: Build AAB with Flutter</h4>
<div style="white-space: pre-wrap;line-height: 1.5">
Resolving dependencies...
Downloading packages...
  _flutterfire_internals 1.3.44 (1.3.47 available)
  archive 3.6.1 (4.0.1 available)
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  characters 1.3.0 (1.3.1 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.18.0 (1.19.1 available)
! device_info_plus 10.1.2 (overridden) (11.1.1 available)
! device_info_plus_platform_interface 7.0.1 (overridden)
  easy_debounce 2.0.1 (2.0.3 available)
  equatable 2.0.5 (2.0.7 available)
  fake_async 1.3.1 (1.3.2 available)
  file_picker 8.1.2 (8.1.4 available)
  firebase_analytics 11.3.3 (11.3.6 available)
  firebase_analytics_platform_interface 4.2.5 (4.2.8 available)
  firebase_analytics_web 0.5.10+2 (0.5.10+5 available)
  firebase_core 3.6.0 (3.8.1 available)
  firebase_core_platform_interface 5.3.0 (5.3.1 available)
  firebase_core_web 2.18.1 (2.18.2 available)
  firebase_messaging 15.1.3 (15.1.6 available)
  firebase_messaging_platform_interface 4.5.46 (4.5.49 available)
  firebase_messaging_web 3.9.2 (3.9.5 available)
  firebase_performance 0.10.0+8 (0.10.0+11 available)
  firebase_performance_platform_interface 0.1.4+44 (0.1.4+47 available)
  firebase_performance_web 0.1.7+2 (0.1.7+5 available)
  firebase_remote_config 5.1.3 (5.2.0 available)
  firebase_remote_config_platform_interface 1.4.44 (1.4.47 available)
  firebase_remote_config_web 1.7.2 (1.7.5 available)
  flutter_animate 4.5.0 (4.5.2 available)
  flutter_launcher_icons 0.13.1 (0.14.2 available)
  flutter_lints 4.0.0 (5.0.0 available)
  flutter_native_splash 2.4.1 (2.4.3 available)
  flutter_plugin_android_lifecycle 2.0.20 (2.0.23 available)
  flutter_spinkit 5.2.0 (5.2.1 available)
  font_awesome_flutter 10.7.0 (10.8.0 available)
  go_router 12.1.3 (14.6.2 available)
  google_fonts 6.1.0 (6.2.1 available)
! http 1.2.2 (overridden)
  http_parser 4.0.2 (4.1.1 available)
  image 4.2.0 (4.3.0 available)
  intl 0.19.0 (0.20.1 available)
  json_path 0.7.2 (0.7.4 available)
  leak_tracker 10.0.5 (10.0.8 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
  lints 4.0.0 (5.1.0 available)
  matcher 0.12.16+1 (0.12.17 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  mime 1.0.4 (2.0.0 available)
  mime_type 1.0.0 (1.0.1 available)
  path 1.9.0 (1.9.1 available)
  path_provider 2.1.4 (2.1.5 available)
  path_provider_android 2.2.10 (2.2.14 available)
  path_provider_foundation 2.4.0 (2.4.1 available)
  permission_handler_android 12.0.12 (12.0.13 available)
  permission_handler_html 0.1.3+2 (0.1.3+5 available)
! photo_view 0.15.0 (overridden)
! pointer_interceptor 0.10.1+2 (overridden)
! pointer_interceptor_ios 0.10.1 (overridden)
! pointer_interceptor_platform_interface 0.10.0+1 (overridden)
! pointer_interceptor_web 0.10.2+1 (overridden)
  rive 0.12.2 (0.13.20 available)
  rive_common 0.2.8 (0.4.15 available)
  shared_preferences 2.3.2 (2.3.3 available)
  shared_preferences_android 2.3.2 (2.3.4 available)
  shared_preferences_foundation 2.5.2 (2.5.3 available)
  signature 5.4.0 (5.5.0 available)
  smooth_page_indicator 1.1.0 (1.2.0+3 available)
  sqflite 2.3.3+1 (2.4.1 available)
  sqflite_common 2.5.4+3 (2.5.4+6 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.4.0 available)
  test_api 0.7.2 (0.7.4 available)
  timeago 3.6.1 (3.7.0 available)
  url_launcher 6.3.0 (6.3.1 available)
  url_launcher_android 6.3.10 (6.3.14 available)
  url_launcher_ios 6.3.1 (6.3.2 available)
  url_launcher_linux 3.2.0 (3.2.1 available)
  url_launcher_macos 3.2.1 (3.2.2 available)
  url_launcher_windows 3.1.2 (3.1.3 available)
! uuid 4.5.1 (overridden)
  vm_service 14.2.5 (15.0.0 available)
  webview_flutter 4.9.0 (4.10.0 available)
  webview_flutter_android 3.16.7 (4.1.0 available)
  webview_flutter_wkwebview 3.15.0 (3.16.3 available)
! win32 5.5.1 (overridden) (5.9.0 available)
  win32_registry 1.1.5 (2.0.0 available)
Got dependencies!
79 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Upgrading build.gradle
Running Gradle task 'bundleRelease'...                          
Warning: Observed package id 'cmdline-tools;latest' in inconsistent location '/usr/local/share/android-sdk/cmdline-tools/latest-2' (Expected '/usr/local/share/android-sdk/cmdline-tools/latest')
Warning: Observed package id 'cmdline-tools;latest' in inconsistent location '/usr/local/share/android-sdk/cmdline-tools/latest-2' (Expected '/usr/local/share/android-sdk/cmdline-tools/latest')
Warning: Errors during XML parse:
Warning: Additionally, the fallback loader failed to parse the XML.
Checking the license for package NDK (Side by side) 25.1.8937393 in /usr/local/share/android-sdk/licenses
License for package NDK (Side by side) 25.1.8937393 accepted.
Preparing "Install NDK (Side by side) 25.1.8937393 (revision: 25.1.8937393)".
"Install NDK (Side by side) 25.1.8937393 (revision: 25.1.8937393)" ready.
Installing NDK (Side by side) 25.1.8937393 in /usr/local/share/android-sdk/ndk/25.1.8937393
"Install NDK (Side by side) 25.1.8937393 (revision: 25.1.8937393)" complete.
"Install NDK (Side by side) 25.1.8937393 (revision: 25.1.8937393)" finished.
Warning: Observed package id 'cmdline-tools;latest' in inconsistent location '/usr/local/share/android-sdk/cmdline-tools/latest-2' (Expected '/usr/local/share/android-sdk/cmdline-tools/latest')
Warning: Observed package id 'cmdline-tools;latest' in inconsistent location '/usr/local/share/android-sdk/cmdline-tools/latest-2' (Expected '/usr/local/share/android-sdk/cmdline-tools/latest')
Checking the license for package CMake 3.18.1 in /usr/local/share/android-sdk/licenses
License for package CMake 3.18.1 accepted.
Preparing "Install CMake 3.18.1 (revision: 3.18.1)".
"Install CMake 3.18.1 (revision: 3.18.1)" ready.
Installing CMake 3.18.1 in /usr/local/share/android-sdk/cmake/3.18.1
"Install CMake 3.18.1 (revision: 3.18.1)" complete.
"Install CMake 3.18.1 (revision: 3.18.1)" finished.
Warning: Observed package id 'cmdline-tools;latest' in inconsistent location '/usr/local/share/android-sdk/cmdline-tools/latest-2' (Expected '/usr/local/share/android-sdk/cmdline-tools/latest')
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 848 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-solid-900.ttf" was tree-shaken, reducing it from 419720 to 1088 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 3220 bytes (99.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/builder/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR:/home/builder/.gradle/caches/transforms-3/3d979c09ae95ea959e87cfa8d7b64639/transformed/jetified-appcompat-resources-1.7.0-runtime.jar: R8: java.lang.NullPointerException: Cannot invoke "String.length()" because "&lt;parameter1&gt;" is null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
&gt; A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   &gt; Compilation failed to complete, origin: /home/builder/.gradle/caches/transforms-3/3d979c09ae95ea959e87cfa8d7b64639/transformed/jetified-appcompat-resources-1.7.0-runtime.jar:androidx/appcompat/graphics/drawable/DrawableContainerCompat$1.class

* Try:
&gt; Run with --stacktrace option to get the stack trace.
&gt; Run with --info or --debug option to get more log output.
&gt; Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 40s
Running Gradle task 'bundleRelease'...                            461.3s
Gradle task bundleRelease failed with exit code 1

Build failed :|
Step 8 script `Build AAB with Flutter` exited with status code 1
</div>
</body>

### Environment

```markdown
- FlutterFlow version: v5.0.14
- Platform: Mac OS
- Browser name and version:
- Operating system and version affected: Apple M1 Pro / 15.0
```

**Comment by Alezanello** [comment]
Hello,

As mentioned in your previous issue, the main reason your deployment is failing is that you have a component with a required parameter that hasn't been set. This issue is reflected in your logs with the following error:

`Cannot invoke "String.length()" because "<parameter1>" is null.`

If you're confident that all components in your project have their required parameters properly set and this issue persists, please contact our support team so we can investigate further.

You can reach support via the in-app chat or by emailing us at **support@flutterflow.io**.

Thank you!

**Comment by MamadAsap** [comment]
@Alezanello this error message `Cannot invoke "String.length()" because "<parameter1>" is null.`  is related to a deployment issue : https://stackoverflow.com/questions/77587376/cannot-invoke-string-length-because-parameter1-is-null  not a widget issue.

I'm stuck and I can't find any solution for deploying the application, which is having a major impact on my company's business.

Thank you in advance for your help

**Comment by Alezanello** [comment]
Hello again!

I’ve attempted to replicate the issue on my end but haven’t been able to reproduce it. For further assistance with this specific situation, I recommend reaching out to our support team. You can connect with them via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They’ll be happy to help you resolve this!

Thank you for your understanding!

**Comment by MamadAsap** [comment]
Hi ! Are you sure about that ? I just try again to download an apk and to download and i'm still having issues...

<img width="578" alt="Capture d’écran 2024-12-12 à 10 56 00" src="https://github.com/user-attachments/assets/5e0ee78f-3e89-496f-acbe-17734f002ce1" />
