### ISSUE TITLE
Change on Main Axis Alingment at Bar Charts does not compile

### ISSUE THREAD

**Issue by uebenes** [FlutterFlow/flutterflow-issues#507]
I tried out to create a Bar Chart with the **chart** widget. Its works fine so bar, but the default alignment **center** does not look very nice. I used the option in the property windows to set the alignment to **Space Evenly**.

![image](https://user-images.githubusercontent.com/59523839/219847443-a97d2d27-0f24-4f41-8556-c513de724f91.png)

## Expected behavior

The preview has shown the expected behavoir.

![image](https://user-images.githubusercontent.com/59523839/219847449-212ce33a-e483-427f-9f97-df605a32b712.png)

## Current behavior

Unfortunally, it was not able to compile:

![image](https://user-images.githubusercontent.com/59523839/219847705-0d7c1fcb-6048-4f2c-b1f6-c6876d79a0a4.png)

Also other options in **Main Axis Alingment** except *center* does not work. When I changed back to *center* alignment, the complilation was successful. 

## To Reproduce 

1. Build a widget with a bar chart and select *bar chart* as chart type
2. Set some random labels for the x-axis
3. Set some random labels for the y-asis
4. Select **Space Evenly** at Main Axis Alingment
5. Click on **Run your App in Test Mode**

## Your environment
* Version of FlutterFlow used: 3.1
* Platform:  Windows 11
* Browser name and version: Edge Version 110.0.1587.50  
* Operating system and version (desktop or mobile): Desktop

**Comment by organicnz** [comment]
Hi @uebenes. Thanks, Stefan for adding this issue 🙂

Confirming. I've just checked that out and couldn't publish with the Selected Space Evenly at Main Axis Alignment. 

[Screenshot](https://www.loom.com/i/4aec25e3f3dc4dd48cc6f71d2503d1aa)

**Comment by wenkaifan0720** [comment]
Hi @uebenes. This should be fixed in our next update. Thank you for raising this issue.
