### ISSUE TITLE
Can't add data into a sub collection

### ISSUE THREAD

**Issue by maryamza24** [FlutterFlow/flutterflow-issues#5070]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I Can't add data into a subcollection, data set similar to a parent

### Expected Behavior

Adding data into a subcollection data base

### Steps to Reproduce

1. Connect to firebase
2. Create Parent Data collection
3. Create another collection, select sub collection
4. Go to manage Content
5. You will only see the option to populate Parent data and not to populate sub collection

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

import '/backend/backend.dart'; import '/flutter_flow/flutter_flow_icon_button.dart'; import '/flutter_flow/flutter_flow_theme.dart'; import '/flutter_flow/flutter_flow_util.dart'; import '/flutter_flow/flutter_flow_widgets.dart'; import 'package:flutter/material.dart'; import 'package:google_fonts/google_fonts.dart'; import 'package:provider/provider.dart';  import 'home_page_model.dart'; export 'home_page_model.dart';  class HomePageWidget extends StatefulWidget {   const HomePageWidget({super.key});    @override   State<HomePageWidget> createState() => _HomePageWidgetState(); }  class _HomePageWidgetState extends State<HomePageWidget> {   late HomePageModel _model;    final scaffoldKey = GlobalKey<ScaffoldState>();    @override   void initState() {     super.initState();     _model = createModel(context, () => HomePageModel());   }    @override   void dispose() {     _model.dispose();      super.dispose();   }    @override   Widget build(BuildContext context) {     return GestureDetector(       onTap: () => FocusScope.of(context).unfocus(),       child: Scaffold(         key: scaffoldKey,         backgroundColor: FlutterFlowTheme.of(context).primaryBackground,         appBar: AppBar(           backgroundColor: FlutterFlowTheme.of(context).primary,           automaticallyImplyLeading: false,           leading: FlutterFlowIconButton(             borderColor: Colors.transparent,             borderRadius: 30,             borderWidth: 1,             buttonSize: 60,             icon: Icon(               Icons.arrow_back_rounded,               color: Colors.white,               size: 30,             ),             onPressed: () async {               context.pop();             },           ),           title: Text(             'Page Title',             style: FlutterFlowTheme.of(context).headlineMedium.override(                   fontFamily: 'Readex Pro',                   color: Colors.white,                   fontSize: 22,                   letterSpacing: 0.0,                 ),           ),           actions: [],           centerTitle: true,           elevation: 2,         ),         body: SafeArea(           top: true,           child: Column(             mainAxisSize: MainAxisSize.max,             children: [               StreamBuilder<List<RestaurantsRecord>>(                 stream: queryRestaurantsRecord(),                 builder: (context, snapshot) {                   // Customize what your widget looks like when it's loading.                   if (!snapshot.hasData) {                     return Center(                       child: SizedBox(                         width: 50,                         height: 50,                         child: CircularProgressIndicator(                           valueColor: AlwaysStoppedAnimation<Color>(                             FlutterFlowTheme.of(context).primary,                           ),                         ),                       ),                     );                   }                   List<RestaurantsRecord> listViewRestaurantsRecordList =                       snapshot.data!;                    return ListView.builder(                     padding: EdgeInsets.zero,                     shrinkWrap: true,                     scrollDirection: Axis.vertical,                     itemCount: listViewRestaurantsRecordList.length,                     itemBuilder: (context, listViewIndex) {                       final listViewRestaurantsRecord =                           listViewRestaurantsRecordList[listViewIndex];                       return Text(                         listViewRestaurantsRecord.name,                         style: FlutterFlowTheme.of(context).bodyMedium.override(                               fontFamily: 'Inter',                               letterSpacing: 0.0,                             ),                       );                     },                   );                 },               ),             ],           ),         ),       ),     );   } }

### Visual documentation

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/61d41b0b-0125-4229-a44a-7ea53f423c1c">
Option only to add data in parent 

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/4ab2afa2-3fbf-48e6-b841-6a7edb90b911">
Parent and Sub collection both created

### Environment

```markdown
- FlutterFlow version: V5
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment]
Hello!

As noted in the documentation, it’s currently not possible to view or edit subcollections in the CMS. This is expected behavior and not a bug.<br><br>[https://docs.flutterflow.io/integrations/database/cloud-firestore/firestore-content-manager/](https://docs.flutterflow.io/integrations/database/cloud-firestore/firestore-content-manager/)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8cf9c81d-f503-4f43-9d6b-998853f6464d/3e8c99bb-6d7c-4d04-9c9e-576bb7721a13?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84Y2Y5YzgxZC1mNTAzLTRmNDMtOWQ2Yi05OTg4NTNmNjQ2NGQvM2U4Yzk5YmItNmQ3Yy00ZDA0LTljOWUtNTc2YmI3NzIxYTEzIiwiaWF0IjoxNzMzODMzMTkyLCJleHAiOjMzMzA0MzkzMTkyfQ.LYhNvL5uQGIGI7wcoH0QsTi2KZ5cy0JY4BaOjSkoSLM " alt="image.png" width="1150" data-linear-height="336" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
