### ISSUE TITLE
Authentication Sign in (unverified email) Getting Failed to load resource: the server responded with a status of 400 () and Unhandled Promise Rejection: Error

### ISSUE THREAD

**Issue by EzzeddineAlimi** [FlutterFlow/flutterflow-issues#5071]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to do some verifications for my app (sign in without verification of email)
in my OnTap sign in button flow, i set the necessary conditions to where to user should be redirected

everything works great in my driver sign in everytime, but for my mechanic sign in, it works one time out of 4 or 5 tries

### Expected Behavior

i'm expected to have no errors 
the user should be redirected to email verification section like in the flow

### Steps to Reproduce

- sign up as mechanic
- sign in using the email you used without verifying the email
- try twice or three times and the flow never executes, the page is frozen and the sign in button does nothing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi/Hlx5B1obhA7YSJccBKjSQUOWV+UIE7lMpOGDsdF4iuPOxzaff7N0hDTf2iYFVbKEWLoEIB//PIkYXuGPk5OSueGoc41s9Iezrgez6/aoSODquee3AlJ95hBWWO0ImFsSQlPtN2LV1m6juuPO+sfDTaQbn6Zwh9f6PHaOI=

### Visual documentation

just follow the steps above
<img width="940" alt="Screenshot 2024-12-09 at 3 05 58 PM" src="https://github.com/user-attachments/assets/d941cde6-0f69-4238-bac2-e528555eb93c">

### Environment

```markdown
- FlutterFlow version: latest version
- Platform: ios/android
- Browser name and version:chrome and safari
- Operating system and version affected:mac os
```

### Additional Information

nothing to add

**Comment by EzzeddineAlimi** [comment]
i have changed the flow to a simpler one just to investigate more but its the same issue
i removed the on_boarded and mechanic_activated conditions

**Comment by paulperez-dev** [comment]
Hi @EzzeddineAlimi,

I’ve reviewed your project, but with so much going on, it’s challenging to pinpoint the issue. To better understand the problem, we’ll need a blank project with the steps to reproduce the issue clearly set up in it. Without these details, it may be difficult for us to investigate effectively.

Please provide the necessary information so we can assist further.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
