### ISSUE TITLE
Enums in library project cause duplicate extension method to import in FFAppState.

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [FlutterFlow/flutterflow-issues#5072]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Creating an enum in a library and importing that library into a project with enums causes an error in FFAppState when defining an apstate variable that is of a type of an enum in the library due to FFEnumExtensions being generated by both projects and the enums.dart exposing this method.

### Expected Behavior

I would expect that these common extension methods would get generated into the ff_commons instead of into to enums.dart of each project.

### Steps to Reproduce

1. Create a library project with an enum.
2. Create a project with an enum.
3. Create an appstate variable in the project with a type of the library enum.
4. Try to build said project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fk8nc34tgrsNc15DUccFFoGYsKVg/a+dJltVxawEbfJPqB7QIZMnOYlZJYsOGdwlIJFmj8XgK0qCOhePIGMEoH02AeYNezrgJZxWXXluVMaq3CaWKPnwlJ/lQI36Y0Jm0mA9SWeNoW3Nk6ly6A+uyThffH4zqDmodQ+SJBNn4o3ClLSLFVix7wmNecCfn

### Visual documentation

"A member named 'serialize' is defined in extension 'FFEnumExtensions' and extension 'FFEnumExtensions', and none are more specific."

![image](https://github.com/user-attachments/assets/99622d1b-1ef6-4dda-81a2-ff110af31db0)

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Web/Mobile/Desktop
- Browser name and version: Chrome
- Operating system and version affected: Windows/MacOS
```

### Additional Information

I spent about a day moving some code around to make it accessible between two projects to reuse widgets and models and this bug has wasted that time and effort because now I have to duplicate it again in the target project.

Recreated this from #4959

Public projects showing issue:

https://app.flutterflow.io/project/enum-library-0wfvkv
https://app.flutterflow.io/project/enum-serialization-error-b3duwm

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that this is a known problem, and a fix is scheduled for today’s release!

I’ll close this issue as a duplicate and link it to our internal ticket. However, if the issue persists after updating to the latest version of FlutterFlow, please don’t hesitate to open a new ticket.

Have a great day!
