### ISSUE TITLE
Experiencing issues since enabling RevenueCat

### ISSUE THREAD

**Issue by giladresisi** [FlutterFlow/flutterflow-issues#5073]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since enabling RevenueCat in my project I experience 2 major issues:
1. I can't deploy to Play Store from a github branch, seems that FlutterFlow doesn't notice or doesn't use my upload key as I keep getting failures for Play Store deployments saying the SHA1 is different than the expected while the SHA1 of my upload key is the expected one. What's also strange is that the found SHA1 is different on every attempt even though I uploaded my key. Already tried removing and re-uploading the key but the issue persists. I already deployed this project multiple times to Play Store in the past with the same key.
2. When pushing the code to github I don't see the BILLING permission in android/app/src/main/AndroidManifest.xml as I'd expect to see after enabling RevenueCat, which probably means that even if I solve the keystore issue I may not be able to create in-app purchase products and subscriptions when deploying from a github branch.

### Expected Behavior

Successful deployment and an added BILLING permission

### Steps to Reproduce

1. Enable RevenueCat
2. Push to github - see there's no BILLING permission
3. Change deployment source in Mobile Deployment settings
4. Deploy to Play Store - failure due to unexpected SHA1

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8r13ItOxLhc+KrAdfpVnSQ7Qkc3argo0MpOEC0jF7KuBqQuZ8zCTBFtQu3jaVNfMVX8nTgBwvT1iOz9E/QrOTmBc7Zdyc8JcQ/0e2iuVc27Bs/peUElApphGmLD1omjvyN/JfptLS0X2ju6G968cADDFOu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-12-10 103214](https://github.com/user-attachments/assets/682b8c94-7b88-4233-ac38-2123433bc130)
![Screenshot 2024-12-10 103258](https://github.com/user-attachments/assets/010d7cc0-d2d3-4998-bffe-0c5e03e4509b)
![Screenshot 2024-12-10 103332](https://github.com/user-attachments/assets/565014e0-58cc-4888-9e0a-39051408482a)

### Environment

```markdown
- FlutterFlow version: v5.0.13+
- Platform: Web
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Windows 11 Pro
```

### Additional Information

I need to enable subscriptions in my app, however I have some changes in my github branch (I made them because of other open issues you guys have) so I need to make the deployment from github and not directly from my FlutterFlow project.
Please fix this ASAP

**Comment by Alezanello** [comment]
Hello,

In this case, the issue seems to be very specific to your project, as I couldn’t reproduce it in a new blank project. I recommend contacting our support team via the in-app chat or by emailing **support@flutterflow.io** for assistance.

Please note that this GitHub issue tracker is intended for issues that can be replicated in a new blank project.

Thank you for your understanding!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
