### ISSUE TITLE
FlutterFlow Desktop App Keeps on Loading on my Mac 

### ISSUE THREAD

**Issue by beepixl** [FlutterFlow/flutterflow-issues#5075]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Till yesterday everything was working fine but today it keeps on loading. all projects on web are loaded but on desktop its the same issue

### Expected Behavior

should be working fine

### Steps to Reproduce

Installed Latest mac desktop app 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no bug report code 

### Visual documentation

attaching the image 
<img width="2240" alt="Screenshot 2024-12-10 at 1 49 56 PM" src="https://github.com/user-attachments/assets/2f180da3-a6b1-4cce-8f07-0272e3497bdb">

### Environment

```markdown
- FlutterFlow version: 5.0.14
- Platform: macOS 15.1.1 (24B91)
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

that's all for now

**Comment by rzambroni** [comment]
Hi @beepixl,

Thank you for bringing this to our attention! We currently don’t have any other reports of loading issues, so it’s possible that something specific might be causing the issue on your end.

To troubleshoot, I recommend clearing the FlutterFlow cache and restarting the app. Here’s how you can locate the relevant folders:

`/Users/<your_user_name>/Library/Application Support/io.flutterflow.prod.mac `

`/Users/<your_user_name>/Library/Caches/io.flutterflow.prod.mac`

If the issue persists after trying this, I suggest reaching out to FlutterFlow Support directly. They have access to more advanced tools and can provide additional assistance. You can contact them via email at **support@flutterflow.io** or use the in-app chat feature.

I hope this helps!

Best regards,

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
