### ISSUE TITLE
On tap navigation doesn't work for almost all my widgets

### ISSUE THREAD

**Issue by DigaAI** [FlutterFlow/flutterflow-issues#5076]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have multiple widgets (icon buttons, containers, text fields for simple search, buttons) that can't be clicked on the test, run and the deployed web project. The only navigation actions that work are the menu's page titles.

### Expected Behavior

The widgets when clicked should redirect the user to the specified page or allow user to type (for the simple search)

### Steps to Reproduce

1. Create a page;
2. Add an icon button for example;
3. Give it a on tap action to navigate to another page.
4. Test it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ckcjc34hOj71J+KrxbcBF9SkRNkw8RYEVkutTZw8jN5PMC+wIZ/f7XFRuTde0TXx2f1qjgT8ep9HemvH1G/E3NSSdbKY6wqlUZzvzVj65MLquBs2eOG5/Df9RJlSny7envRUnVfdhc14F2DnzeeqUSj3ZJIDEDW4RH/qZIZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/4391025b-63eb-4bf1-9c95-f8865cc908fe)
![image](https://github.com/user-attachments/assets/098a7980-c9f3-4e03-ae03-0f741c13aae9)
![image](https://github.com/user-attachments/assets/1e3f600e-8c71-4562-8e26-64992aaead42)
![image](https://github.com/user-attachments/assets/48fbe41d-8894-4731-9ffc-aff6fc513ab3)

https://github.com/user-attachments/assets/9842cbb3-7cf6-4d7d-b277-ebcf27dcb1f3

### Environment

```markdown
- FlutterFlow version: v5.0.13+ released November 27, 2024 3.24.2
- Platform: Web, Windows Desktop: Web
- Browser name and version: Chrome 131.0.6778.109
- Operating system and version affected: Windows 11 23H2
```

**Comment by Alezanello** [comment]
Hello,

I attempted to test your project, but I encountered significant errors related to the mouse region immediately after signing up or signing in. This issue could be a primary reason why the project isn’t functioning as expected.

To help isolate the problem, could you try creating a new blank project to see if the issue persists? This will help us determine if the error is specific to your current project or a broader issue.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a4a0b0ba-9b49-4ee2-b534-d542634599f6/8a701f83-d33a-40a1-893b-692516508b1c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNGEwYjBiYS05YjQ5LTRlZTItYjUzNC1kNTQyNjM0NTk5ZjYvOGE3MDFmODMtZDMzYS00MGExLTg5M2ItNjkyNTE2NTA4YjFjIiwiaWF0IjoxNzMzODQzODg5LCJleHAiOjMzMzA0NDAzODg5fQ.81Jch85wJRi6WTH3KkA2NsMNOOqigCN5CtPe_EiyWyQ " alt="massiveerror.gif" width="1906" data-linear-height="926" />

**Comment by DigaAI** [comment]
Hey. This issue is isolated since my other project is working fine. But I have no idea how to solve this. What do you mean mouse region? I can see the error in my dev console where it says:
"Uncaught Error: Invalid argument (index): "type"
    at Object.v (main.dart.js:3933:19)
    at bnc.j (main.dart.js:184834:39)
    at Object.K (main.dart.js:196:16)
    at i1W.$1 (main.dart.js:402402:10)
    at h3l.$0 (main.dart.js:187062:20)
    at Object.lom (main.dart.js:5639:12)
    at h3o.$1 (main.dart.js:187059:9)
    at icR.$1 (main.dart.js:192448:21)"
    
And I guess that's happening bcs I'm trying to access a list element using the string "type" as an index, but that index doesn't exist or isn't valid for the data structure. But I don't kown how to troubleshoot this. Can you help me?

**Comment by DigaAI** [comment]
Hey, is there a faster way to get iterations on this issue? I understand you can't help me periodically, but I can't find the in app chat, even though I'm a pro user. Maybe if I email I will get faster responses? I have to deliver this project soon, so I hope there is a faster way to get support. Thank you anyways.

**Comment by DigaAI** [comment]
@Alezanello Accually, on run mode I get this error, which I also have no idea how to solve:

main.dart.js:198 Uncaught TypeError: J.cT(...).ar is not a function
    at Object.iL (main.dart.js:198:24)
    at Object.jT (main.dart.js:6491:3)
    at bkj.$1 (main.dart.js:120032:5)

**Comment by Alezanello** [comment]
Hello again!

Thanks for reaching out! Just to clarify, the GitHub Issue Tracker is specifically meant for reporting reproducible bugs that originate from a new, blank project created within the FlutterFlow platform. It’s designed to help address platform-level issues, not project-specific implementation errors.

For issues related to how things are implemented in your project, we recommend reaching out to our support team. You can do this via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) for assistance.
