### ISSUE TITLE
Custom Function Working On Run Mode... Not On Device

### ISSUE THREAD

**Issue by TheBestLevel** [FlutterFlow/flutterflow-issues#5077]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a custom function that works fine on run mode, but once you go to your device it does not work. I don't know why or how to change this.

(By the way in run mode works perfect, it does the thing that i want)

This is the custom function:

// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:async';

// Main function to convert Program to Program User
Future<ProgramTrainingStruct> programToProgramUser(
  ProgramsRecord programRef,
  DateTime initialDate,
  DocumentReference usersRef,
  List<bool> weekDaysClient,
) async {
  // Temporary structure for TrainingDays
  List<Map<String, dynamic>> tempTrainingDays = [];

  // Get program and user information
  String programName = programRef.name!;
  List<DocumentReference> sessionsList = programRef.sesionsList!;
  int durationWeeks = programRef.durationWeeks!;

  var userDoc = await usersRef.get();
  var userData = userDoc.data() as Map<String, dynamic>;
  String nombreCliente = userData['Nombre'];

  // Adjust initialDate to the Monday of the selected week
  DateTime adjustedInitialDate = initialDate.subtract(
    Duration(days: initialDate.weekday - 1),
  );

  // Step 1: Create a copy of sessions and adjust DaysOfWeek
  List<Map<String, dynamic>> adjustedSessions = [];
  List<int> userDays = [];
  for (int i = 0; i < weekDaysClient.length; i++) {
    if (weekDaysClient[i]) userDays.add(i);
  }

  for (int i = 0; i < sessionsList.length; i++) {
    var sessionRef = sessionsList[i];
    var sessionDoc = await sessionRef.get();
    var sessionData = sessionDoc.data() as Map<String, dynamic>;
    List<bool> sessionDaysOfWeek = List<bool>.from(sessionData['DaysOfWeek']);

    // Adjust DaysOfWeek for the session
    List<bool> adjustedDaysOfWeek = List<bool>.filled(7, false);
    adjustedDaysOfWeek[userDays[i]] = true;

    // Create a copy of the session with adjusted DaysOfWeek
    var adjustedSession = Map<String, dynamic>.from(sessionData);
    adjustedSession['DaysOfWeek'] = adjustedDaysOfWeek;

    adjustedSessions.add(adjustedSession);
  }

  // Step 2: Detect sessions requiring adjustment and mark them
  List<bool> requiresShift = List<bool>.filled(adjustedSessions.length, false);
  for (int i = 0; i < adjustedSessions.length; i++) {
    var sessionData = adjustedSessions[i];
    List<bool> sessionDaysOfWeek = List<bool>.from(sessionData['DaysOfWeek']);

    for (int dayOfWeek = 0; dayOfWeek < 7; dayOfWeek++) {
      if (!sessionDaysOfWeek[dayOfWeek]) continue;

      DateTime firstTrainingDay =
          adjustedInitialDate.add(Duration(days: dayOfWeek));
      if (firstTrainingDay.isBefore(initialDate)) {
        requiresShift[i] = true;
        break;
      }
    }
  }

  // Step 3: Iterate over adjusted sessions and add training days
  for (int i = 0; i < adjustedSessions.length; i++) {
    var sessionData = adjustedSessions[i];
    List<bool> sessionDaysOfWeek = List<bool>.from(sessionData['DaysOfWeek']);
    List<Map<String, dynamic>> trainingExercises =
        List<Map<String, dynamic>>.from(sessionData['Training']);
    List<Map<String, dynamic>> warmupExercises =
        List<Map<String, dynamic>>.from(sessionData['Warmup']);

    for (int dayOfWeek = 0; dayOfWeek < 7; dayOfWeek++) {
      if (!sessionDaysOfWeek[dayOfWeek]) continue;

      for (int week = 0; week < durationWeeks; week++) {
        DateTime weekStartDate =
            adjustedInitialDate.add(Duration(days: week * 7));

        // Add 7 days to the training date if the session requires shifting
        DateTime trainingDayDate = weekStartDate.add(Duration(days: dayOfWeek));
        if (requiresShift[i]) {
          trainingDayDate = trainingDayDate.add(Duration(days: 7));
        }

        if (trainingDayDate.isBefore(initialDate)) continue;

        List<Map<String, dynamic>> updatedTrainingExercises =
            actualizarSetData(trainingExercises, week);
        List<Map<String, dynamic>> updatedWarmupExercises =
            actualizarSetData(warmupExercises, week);

        var trainingDayData = {
          'Date': trainingDayDate,
          'userRef': usersRef,
          'CompletePendingIncomplete': 'Pending',
          'Nombre_Cliente': nombreCliente,
          'Evaluation': false,
          'ProgramaRef': programRef.reference,
          'TrainingExercises': updatedTrainingExercises,
          'WarmupExercises': updatedWarmupExercises,
          'Position': programName,
          'LastTrainingOfProgram': false,
        };

        tempTrainingDays.add(trainingDayData);
      }
    }
  }

  // Step 4: Generate two months of calendars
  List<MonthStruct> trainingMonths = [];
  DateTime currentMonth =
      DateTime(adjustedInitialDate.year, adjustedInitialDate.month);

  for (int i = 0; i < 2; i++) {
    List<CalendarDayStruct> calendar = [];
    DateTime firstOfMonth = DateTime(currentMonth.year, currentMonth.month, 1);
    DateTime lastOfMonth =
        DateTime(currentMonth.year, currentMonth.month + 1, 0);
    DateTime startCalendar =
        firstOfMonth.subtract(Duration(days: firstOfMonth.weekday - 1));
    DateTime endCalendar = lastOfMonth.weekday == 7
        ? lastOfMonth
        : lastOfMonth.add(Duration(days: 7 - lastOfMonth.weekday));

    Map<String, Map<String, dynamic>> trainingDaysMap = {
      for (var item in tempTrainingDays)
        item['Date'].toIso8601String().substring(0, 10): item
    };

    for (DateTime date = startCalendar;
        date.isBefore(endCalendar.add(Duration(days: 1)));
        date = date.add(Duration(days: 1))) {
      bool isPreviousMonth = date.isBefore(firstOfMonth);
      bool isNextMonth = date.isAfter(lastOfMonth);
      bool isTrainingDay =
          trainingDaysMap.containsKey(date.toIso8601String().substring(0, 10));

      bool lastTrainingOfProgram = isTrainingDay
          ? trainingDaysMap[date.toIso8601String().substring(0, 10)]![
              'LastTrainingOfProgram']
          : false;

      List<EjercicioStruct> trainingExercises = isTrainingDay
          ? (trainingDaysMap[date.toIso8601String().substring(0, 10)]![
                  'TrainingExercises'] as List<Map<String, dynamic>>)
              .map((exercise) => EjercicioStruct.fromMap(exercise))
              .toList()
          : [];

      List<EjercicioStruct> warmupExercises = isTrainingDay
          ? (trainingDaysMap[date.toIso8601String().substring(0, 10)]![
                  'WarmupExercises'] as List<Map<String, dynamic>>)
              .map((exercise) => EjercicioStruct.fromMap(exercise))
              .toList()
          : [];

      String completePendingIncomplete = isTrainingDay
          ? trainingDaysMap[date.toIso8601String().substring(0, 10)]![
              'CompletePendingIncomplete']
          : 'Pending';

      calendar.add(CalendarDayStruct(
        calendarDate: date,
        isPreviousMonth: isPreviousMonth,
        isNextMonth: isNextMonth,
        isTrainingDay: isTrainingDay,
        trainingDayDocRef: null,
        completePendingIncomplete: completePendingIncomplete,
        trainingExercises: trainingExercises,
        warmupExercises: warmupExercises,
        isEvaluationDay: false,
        lastTrainingOfProgram: lastTrainingOfProgram,
      ));
    }

    trainingMonths.add(MonthStruct(
      calendarDays: calendar,
      monthReference: DateTime(currentMonth.year, currentMonth.month, 14),
    ));

    currentMonth = DateTime(currentMonth.year, currentMonth.month + 1);
  }

  var infoProgram = UsersProgramsStruct(
    programTemplateRef: programRef.reference,
    startProgramDate: adjustedInitialDate,
    trainingMonths: trainingMonths,
    misedTrainingDaysProgram: 0,
  );

  // Create ProgramTrainingStruct with calendar information
  return ProgramTrainingStruct(
    age: programRef.age,
    category: programRef.category,
    daysOfTheWeek: weekDaysClient,
    description: programRef.description,
    durationWeeks: durationWeeks,
    imageURL: programRef.imageURL,
    implementosStruct: programRef.implementosStruct,
    level: programRef.level,
    materials: programRef.materials,
    name: programRef.name,
    objectives: programRef.objectives,
    proyections: programRef.proyections,
    registeredPeople: programRef.registeredPeople! + 1,
    sesionsList: programRef.sesionsList,
    startDate: adjustedInitialDate,
    status: true,
    userRef: usersRef,
    programFinished: false,
    infoProgram: infoProgram,
    templateDocRef: programRef.reference,
  );
}

// Function to update SetData according to the week
List<Map<String, dynamic>> actualizarSetData(
    List<Map<String, dynamic>> ejercicios, int week) {
  return ejercicios.map((ejercicio) {
    var updatedExercise = Map<String, dynamic>.from(ejercicio);

    if (ejercicio.containsKey('IsACircuit') &&
        ejercicio['IsACircuit'] is bool &&
        ejercicio['IsACircuit'] == true) {
      List<Map<String, dynamic>> exercisesCircuitList =
          List<Map<String, dynamic>>.from(ejercicio['ExercisesCircuitList']);
      List<Map<String, dynamic>> updatedExercisesCircuitList =
          exercisesCircuitList.map((circuitExercise) {
        var updatedCircuitExercise = Map<String, dynamic>.from(circuitExercise);

        switch (week) {
          case 0:
            updatedCircuitExercise['SetData'] = List<Map<String, dynamic>>.from(
                circuitExercise['SetDataWeek1']);
            break;
          case 1:
            updatedCircuitExercise['SetData'] = List<Map<String, dynamic>>.from(
                circuitExercise['SetDataWeek2']);
            break;
          case 2:
            updatedCircuitExercise['SetData'] = List<Map<String, dynamic>>.from(
                circuitExercise['SetDataWeek3']);
            break;
          case 3:
            updatedCircuitExercise['SetData'] = List<Map<String, dynamic>>.from(
                circuitExercise['SetDataWeek4']);
            break;
          default:
            updatedCircuitExercise['SetData'] = [];
        }
        return updatedCircuitExercise;
      }).toList();

      updatedExercise['ExercisesCircuitList'] = updatedExercisesCircuitList;
      updatedExercise.remove('SetData');
      updatedExercise.remove('SetDataWeek1');
      updatedExercise.remove('SetDataWeek2');
      updatedExercise.remove('SetDataWeek3');
      updatedExercise.remove('SetDataWeek4');
    } else {
      switch (week) {
        case 0:
          updatedExercise['SetData'] =
              List<Map<String, dynamic>>.from(ejercicio['SetDataWeek1']);
          break;
        case 1:
          updatedExercise['SetData'] =
              List<Map<String, dynamic>>.from(ejercicio['SetDataWeek2']);
          break;
        case 2:
          updatedExercise['SetData'] =
              List<Map<String, dynamic>>.from(ejercicio['SetDataWeek3']);
          break;
        case 3:
          updatedExercise['SetData'] =
              List<Map<String, dynamic>>.from(ejercicio['SetDataWeek4']);
          break;
        default:
          updatedExercise['SetData'] = [];
      }
    }

    return updatedExercise;
  }).toList();
}

### Expected Behavior

To work in run mode and in production on the device it self. Right now only works well in run mode

### Steps to Reproduce

1. You need all the structs and files so you need access to my proyect (you can create the same on a new proyect but will take a lot of time)
2. Open a new page
3. You need a document form Programs collection, you can query it. 
4. Create a document Programs in firestore tha have this variables: (Name-"Test", Status-True, Category-"General", Level-"Principiante", Proyection-"Amateur", Materials-"Ninguno", Age-"13-18", TemplateAdmin-True)
5. The use the custom function with this inputs: 
6. programRef --> The one we created before
7. initialDate --> Today
8. userRef --> Any user
9. weekDays --> List of bools like this [false, false, true, true, true false, false]
10. I recomend put a show snack before and after the execution of this custom action so you will se it does execute correctly in run mode, but not in the phone it self

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wl/Llz5d1octY7ar+cfpVijgsIjp/RLhEmsFueCs9f5CvOpYUec/6P05DUubmdH9HemKmp14Cw8Lzj9npKO0FMk2dUaE71c5QVg2UTl+iM5OTF7mKPGpQBeJRfmXH0ruvhSR/Ivtic3wT3GWEHtyyZC/DQYDXDWowSq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/e9a6e3c9-03cc-4f6d-a647-d793d71a777a)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.13+ released November 27, 2024
- Platform: Web and mobile
- Browser name and version: Version 131.0.6778.109 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 and any mobile os I have tried
```

### Additional Information

I have deployed this to the users, thinking it will work, because it WORKS in run mode perfectly fine, but in phone it does not, so new users can not pass on boarding and that is VERY BAD

**Comment by Alezanello** [comment]
Hello,

First of all, I’m truly sorry to hear about the issue you’re experiencing.

I’d like to clarify that the GitHub Issue Tracker is specifically for bugs that can be replicated in new blank projects. Unfortunately, we’re unable to debug all custom code that users add to the platform. However, if you’re able to debug the issue and share a minimal example of the custom code that is causing the problem, it would be incredibly helpful. For example, if you’ve found that a specific function (`X`) isn’t triggering correctly, sharing that isolated code would give us a clear starting point for investigation.

I hope this explanation doesn’t come across as dismissive—we genuinely value your feedback and want to address all the issues you and other users report. Identifying a minimal reproducible case helps us better understand *why* the issue is happening and find a solution faster.

Thank you for your understanding and collaboration!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
