### ISSUE TITLE
Pass parameters value displaying Non-selectable #index in List, causing "current variable is not valid"

### ISSUE THREAD

**Issue by MAKM0902** [FlutterFlow/flutterflow-issues#5079]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using SQlite databse for app, children generated  on listview from value simple search results (named as searchresult ) contain card used for navigating data when tapped, but when we set action for card to navigate to other page(which display whole data of that search result item) and when we select parameter (for passing data) and set value to searchresult item(Children generated from simple search results) It has no valid available options but suddenly it pops #index in list 
![Screenshot (75)](https://github.com/user-attachments/assets/6ffccf28-7e3c-451e-aa33-d89b7e9e2ad7)

![Screenshot (72)](https://github.com/user-attachments/assets/9fa41529-437f-4610-85b5-c9a4264cca9e)

### Expected Behavior

I had made project on firebase databse earlier which was working very well. Then I attempted to reproduce the same project on SQlite database in Flutter Flow. I copied and paste the widgets from the earlier project to this project. It must progress every step smoothly and shall pass data to the next page. suddenly parameter (passing parameter) value was displaying #index in the list which shall not happen

### Steps to Reproduce

Created 2 pages in my project, used sqlite database. The first page (homepage) provide search functionality for a specific field while the second page(namely data page) is  set to show all the relevant info(data) of the search result. second page(data page) has page parameter as sqliterow to show the relevant data of the search item. The homepage has list widget to show search results on card widget. then we generated children on the very same list from the value simple search result and named this variable as searchresult.  while setting action on the card to navigate the search results to the next page, I selected the parameter while giving value as searchresult item (generated children of list widget), it display non-selectable #index in list

![Screenshot (70)](https://github.com/user-attachments/assets/debb7774-8c43-48e7-bb47-72fa8505ab60)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEel+b2yIhhpb1I+ZfqL/pV+AMxJEQnargvhNZDawsafJTsOoolbuvTbldvO+HmSm9qO2CYoH800N7LueOeF/koFyuEQ5RfwapcSgLhXn6meJiQC4e7P395Bf1Yfx2/yrWjsxVQIvBacXstig/GSw==

### Visual documentation

![Screenshot (70)](https://github.com/user-attachments/assets/496ee28d-c375-418f-a174-32f086cadbb6)

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: pc
- Browser name and version: chrome
- Operating system and version affected: windows 10
```

### Additional Information

**Comment by MAKM0902** [comment]
It would be great if FF team could possibly resolves the issues occurring again and again in SQLite database app in FF. As SQLite is used by the user and developers of the far-flung and remote areas having low/lacking internet connections. SQLite is the only reliable and best option when dealing with large data(i.e. college/school or hospital data: as all the students or patients data is once loaded, user of the app(school/college administration) has to only edit specific fields or give remarks like discharged / passed in exam or like taken  score in exam) for search functionality and displaying the that data in offline mode. Other database as firebase or supabase cache only a small chunk which may not serve the purpose.
Here is the list of suggested upgrades
1. please add option to limit document to display(single document, list of document) when adding query as SQLite database as it is in firebase database
![Screenshot (67)](https://github.com/user-attachments/assets/09fb2f97-44d7-461c-b286-0ec136f3e3f0)
![Screenshot (68)](https://github.com/user-attachments/assets/0bd555cc-0920-4d25-9fea-babcc53c2e49)

2. when user make updates/edits in app (SQLite database based app) in offline mode, please consider the method to upload that data to the database, if not possible, integrate SQLite to google sheet that all edits/updates may upload there.
3. Testing/debugging is another critical requirement by the users of SQLite database based apps.

**Comment by Alezanello** [comment]
Hello!

Thank you for sharing the project as an example! The issue you’re facing occurs because the Simple Search feature is generating a list of strings, not SQLite rows. As a result, the dynamic children being generated are strings rather than complete SQLite rows.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/5f436d74-54ec-4ae4-a366-5ee624cee217/88675e69-6010-4a6a-812d-61de33aaef48?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81ZjQzNmQ3NC01NGVjLTRhZTQtYTM2Ni01ZWU2MjRjZWUyMTcvODg2NzVlNjktNjAxMC00YTZhLTgxMmQtNjFkZTMzYWFlZjQ4IiwiaWF0IjoxNzM0MDE1NDQ0LCJleHAiOjMzMzA0NTc1NDQ0fQ.YBX2kPjLKhKVAErnNe-JHhVx-k8bN9uoklLZkKtCHaE " alt="image.png" width="1855" data-linear-height="695" />

**Comment by MAKM0902** [comment]
So what could be the possible solution to have simple search and display the data. Isn't it getting complex in case of SQlite search functionality?

**Comment by MAKM0902** [comment]
@Alezanello So what could be the possible solution to have simple search and display the data. Isn't it getting complex in case of SQlite search functionality?. Is there any documentation or tutorial that may assist to resolve the issue.

**Comment by MAKM0902** [comment]
@Alezanello @leighajarett  I had completed the same project using firebase. There was no issue. As search functionality for sqlite data can not be performed through sqlite row, as the only available option is string in sqlite based app. Could you suggest some documentation or tutorial that may serve the purpose. If not so, then could you please make recommendations to FF team to look for some updates in sqlite databade. As for now I dont see any option for sqlite search functionality other than string, which then cause the issue.

**Comment by Alezanello** [comment]
Hello again, I think you could filter the rows in the parameter you are pssing filtering it by the simple search selected, i wanted to show you an example on how maybe could you achieve this but it seems the project you shared was deleted, could you recreate a new one like the one you reported here?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c8565eae-0c1f-479d-b8a2-d368346a8dda/5c136a02-bac0-47d6-93ea-824b5612edd2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jODU2NWVhZS0wYzFmLTQ3OWQtYjhhMi1kMzY4MzQ2YThkZGEvNWMxMzZhMDItYmFjMC00N2Q2LTkzZWEtODI0YjU2MTJlZGQyIiwiaWF0IjoxNzM0MDk4NzAwLCJleHAiOjMzMzA0NjU4NzAwfQ.Oo8qcgq61omxAszSCKl4Ai5dMW87dxERJs5nqJPh_sI " alt="image.png" width="659" data-linear-height="590" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
