### ISSUE TITLE
Screenshot Mode Not Allowing Variables To Be Set

### ISSUE THREAD

**Issue by MartinLockheart** [FlutterFlow/flutterflow-issues#5080]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I go to screenshot mode, I can't set any of the variables on the screen. 

### Expected Behavior

I should be able to set variables for screenshot mode. 

### Steps to Reproduce

1. Open a page in screenshot mode. 
2. Try to set a variable by clicking, double clicking, etc.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekcjf35VOj7wE7qnQdcJvuwMwJ0QlUIInj+0bWRMhNZetB4l+Pvf8X1pLYtebeFY/G1n9gT4GptLPhuHpCPI6JS+dQN1Jzq5XQQvMWmqmaYvQDKjhdEd8TJhgIHau5rejkApSHPBfSk4k7VOQBPCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/6f4f1004-1807-424a-895e-44d594b92c6f)

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: Windows Desktop
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

### Additional Information

I'm not able to easily generate screenshots for my app with sample data.

**Comment by paulperez-dev** [comment]
Hi @MartinLockheart, 

Thank you for reporting this! This is a known issue, and the team already has it in their backlog for resolution. We truly appreciate your patience, and we hope it will be addressed soon. In the meantime, you can refer to the[ original ticket ](https://github.com/FlutterFlow/flutterflow-issues/issues/3390)for any updates.

Thanks again for bringing this to our attention!

**Comment by MartinLockheart** [comment]
Thank you, I did a search for it because I thought I had seen it before,
but I couldn't find it!
