### ISSUE TITLE
Several issues related to database connection appear

### ISSUE THREAD

**Issue by matteomoccia2005** [FlutterFlow/flutterflow-issues#5083]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While changing the Firestore database rules, suddenly many issues pop up related to missing link with actions setup not finding the related database to update, icons not found, collections not found when running queries. I tried to deploy the rules when the issues were not present, still the issue remain. I tried deploy "everyone" rule for all collections, still the issues remain. I tried regenerating config files, the issues are still there.

### Expected Behavior

The many issues should not be there, because they refer to missing data or links which are instead already setup and working perfectly in previous tests

### Steps to Reproduce

1. Open the project
2. Visualize issues (53 issues are now showing)
3. Impossible to run test
4. Impossible to publish

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi87huJJNoblE+br2YMFaqDgwGUwbUOc7j9VEGAsjCeOtEOwfOuLRZRBuSOqHd21ieE6YmlIyw+DPit7lDvkBOQesbL5fzJNbUxDiJTuiSq2YELi0YUFDP8NbIFye4J6NuwhCCOhoWi0h6lOEJOi+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

![error1](https://github.com/user-attachments/assets/db377610-4182-41ac-a423-e5972e71ae17)
![error7](https://github.com/user-attachments/assets/ff2466fa-1c73-431f-bbc9-c8c3f8031e46)
![error6](https://github.com/user-attachments/assets/af1d4a8c-357f-4632-aeb0-dff61327b38c)
![error5](https://github.com/user-attachments/assets/d01aa91c-832c-46a7-af22-619da7bc3072)
![error4](https://github.com/user-attachments/assets/f110de9b-3954-4136-a5da-be7a346278ac)
![error3](https://github.com/user-attachments/assets/35a6a0f0-924e-4be9-9d45-4c7794ce9354)
![error2](https://github.com/user-attachments/assets/6cfa84a1-5fc0-4e4d-a0bd-f946d9789f78)

### Environment

```markdown
- FlutterFlow version: v.5.0.0+
- Platform: Web and Desktop app
- Browser name and version: Chrome most updated version
- Operating system and version affected: Windows 11
```

**Comment by matteomoccia2005** [comment]
Update: I tried with Edge browser and from a different internet connection and the issue is not there anymore. Can you please suggest how to clear the issue on my machine using Windows 11 and Chrome? Simple cache cleaning or something different? Thanks

**Comment by Alezanello** [comment]
Hello!<br><br>Thank you for reaching out! I just checked your project and couldn’t find any issues on my end. Could you please share a video showing the issue? It would be helpful to see the difference between the two browsers you mentioned. This will allow us to better understand and assist you.

**Comment by matteomoccia2005** [comment]
I just cleared the cache on the browser and now the issues have disappeared. I am closing this issue. Thank you for the support.
