### ISSUE TITLE
Mobile deployment - AppID, KeyId, privatekey disappearing after 3 seconds

### ISSUE THREAD

**Issue by TemsSwift** [FlutterFlow/flutterflow-issues#5086]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The AppID, Key ID and the uploaded private key disappear after a few seconds, as soon as they have been entered. It is impossible to deploy the app. 

### Expected Behavior

no disappearance

### Steps to Reproduce

Enter the value in the App ID textfield or KeyID or private Key

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

[Recording 2024-12-12 131332.zip](https://github.com/user-attachments/files/18105816/Recording.2024-12-12.131332.zip)

### Environment

```markdown
- FlutterFlow version: 5.0.13+ release december 12, 2024
- Platform:windows
- Browser name and version: Chrome Version 130.0.6723.71 (Official Build) (64-bit)
- Operating system and version affected: 10.0.22631 Build 22631
```

### Additional Information

Just after the update of Flutterflow

**Comment by Alezanello** [comment]
Hello!<br><br>Thank you for sharing the details! I tried to replicate the issue based on your description but wasn’t able to reproduce it or access your video. Could you please reupload the video in a standard video format (rather than a .zip file)? Alternatively, you can use tools like Loom, a screen recorder, YouTube, or a similar platform to share it with us. This will help us review it more effectively and assist you better.

**Comment by esl417** [comment]
I am having the same issue. video is attached. I just did the key id as an example, but it happens with issuer id, private key, app id as well. it also happens with the version number, it's currently blank and if i enter 1.0.0 it blanks out when the keys disappear as well.

https://github.com/user-attachments/assets/08bdf805-54d0-4c28-9edd-72b546112beb

there's not any actions taken prior to this, it's just pasting in the key information and this happens. It happens both on chrome and the desktop app (windows)

Project ID: forkplay-laf4tm
ProductionFlutterFlow v5.0.0+ released December 11, 2024
Flutter version is 3.24.2

**Comment by Alezanello** [comment]
Thank you a lot for the video, I can confirm it now.<br><br>I'll send it as high priority to the engineer team

**Comment by Gorgon-Cyber** [comment]
There's more to this bug. It also affects apps with existing credentials. Both the App Store and the Play Store.

Here is how the App Store deploy fails:

![image](https://github.com/user-attachments/assets/63b9f045-3b67-4c58-8193-aae5b94bcce0)

and here is how the Play Store fails:

![image](https://github.com/user-attachments/assets/b34fd8fe-bf89-4751-a9bd-81a5be09174d)

**Comment by esl417** [comment]
I see it was marked as completed, but the issue is still persisting for me. Do I need to wait for an update to be pushed?

**Comment by Gorgon-Cyber** [comment]
I got a new version notification @esl417 and updated, but I still have the same problem with the credentials files.

**Comment by esl417** [comment]
ok confirming it works for me for app store, will update this thread if i have issues on android which I will try later today

**Comment by Gorgon-Cyber** [comment]
Ditto for me now. I had to re-upload the credentials and then it worked again.
