### ISSUE TITLE
while calling more than one streaming apis on page load or on an actions we receives streamed  data chunks only from the call first defined in action flow.

### ISSUE THREAD

**Issue by dharinicodexlancers** [FlutterFlow/flutterflow-issues#5087]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

One of our flutter flow web project has scenario like calling 2 streaming apis at same time for multiple widgets , in a browser network console we saw that both api gets called & shows response too but on flutter flow side 'onMessage' listener receives data only from the first call we defined in action flow

### Expected Behavior

1) Other streaming calls 'onMessage' listener should listen new data chunks receives from the apis

Important things while working with streaming calls,
1) we have to take care about is how we can dispose the existing streaming calls on flutter flow. There is no way to stop it until I refresh the page
2) We are unable to add streaming on 'Add Query' panel resides on right side on flutter flow dashboard.The scenario we have - we are using streaming apis on 'on load' of component and rebuild component as our app state value changed but it does not rebuild cause we don't have option to add it on container or column or any widget like we do. 

### Steps to Reproduce

1) cerate a page
2) call 2 streaming apis in different action or in a parallel action 
3) check are you able to show data from second streaming api calls 'onMessage' listener
4) I want to recall the same streaming api with different post parameters & want to stop previous streaming onMessage listener how can I do that

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TiMjfsYtPm8tF1c/ucu9VnjgWQ2Ima+c7m9VqEEo0NuvnEYYTOuLSYXFIX+m4TAk7L2f88XIy06HLk+OTA+UpEE6rc6ZM+KVUEwvgIUetbp+bErigeUdtP5pJJVyyyLuroR4nKvtuWU4j2jv7A9+RdHfrJrWwO1cgD/GZEKDO+GuqQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="639" alt="Screenshot 2024-12-12 at 12 59 57 PM" src="https://github.com/user-attachments/assets/7c813ea9-79b8-4676-9fa0-10c13d065d68" />

### Environment

```markdown
- FlutterFlow version: Version 5.0.15 (5.0.15)
- Platform: web
- Browser name and version:Google Chrome - Version 131.0.6778.139 (Official Build) (arm64)
- Operating system and version affected: Macos - 14.5
```

**Comment by paulperez-dev** [comment]
Hi @dharinicodexlancers,

Could you please share some account credentials with data so we can better investigate and triage the issue?

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
