### ISSUE TITLE
Translation issue with copied DropDown elements

### ISSUE THREAD

**Issue by Dmitry-rman** [FlutterFlow/flutterflow-issues#5089]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I had copied some DropDown elements. Now, when I change the text for one, it also changes the others. This is very bad, and I can't figure out how to fix it. I deleted all the DropDown elements, created new ones, and I still have this bug! There are old translations in new elements appeared... It's terrible!

### Expected Behavior

No overwrite translations

### Steps to Reproduce

1. Create a DropDown with translations.
2. Copy it.
3. Change the translations in the first DropDown.
4. Changes appear in all DropDown elements.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiMmBw891ofpE7arqbcJV+CQQH2Y8U5I0mspBZz0aIuPpDJl/PM/6P0hVXsylTXxcJE6cp14z+PzyjuLhM/cDPTiYbaZ+yc9AdTvKWj2tMa2TF7q8XXcmNNxYfUyB4cKJsRZNLtpqdVJm3GGIf9y+TgTaJqbrIno4Sq/LZO4=

### Visual documentation

<img width="263" alt="Снимок экрана 2024-12-12 в 16 43 37" src="https://github.com/user-attachments/assets/76c7fa81-d61d-4153-938d-d3362e6e4981" />

### Environment

```markdown
- FlutterFlow version: 5.0.15
- Platform: Mac App
- Browser name and version: Safari (I use Mac app)
- Operating system and version affected: Mac OS 15.1.1 (24B91)
```

**Comment by Alezanello** [comment]
Hi there!

Thank you for bringing this up.

I’ve been trying to replicate the issue on my end, but so far, I haven’t been able to reproduce it. It might be something specific to your project.

Would you mind sharing a short recording or video that demonstrates the behavior? This would help me better understand the issue and provide more accurate assistance.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
