### ISSUE TITLE
Text alignment on Textfield hint custom style doesn't work

### ISSUE THREAD

**Issue by iamgenes** [FlutterFlow/flutterflow-issues#509]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior
Text alignment buttons in custom hint style should change the alignment of the hint text in a text field

## Current behavior
The buttons do nothing the hint texts follow the alignment of the text field properties instead of the custom hint style

## To Reproduce
1. Create a new page
2. Add TextField widget
3. add a hint text and toggle on the custom hint style
4. change the text alignment in the custom hint style and observe the text does not get aligned
5. scroll to the Text Field properties and click on the Text align buttons observe the hint getting aligned

### Bug Report Code
IT4klvLqx5NgocNY1rr1bfpaqGUXNkA6TL03t9VxSUgrIrbyPJkUaeDSUFJBUuKrdwhbKEWIgkwJpvzpv/zhDPddA0uuY6JeysxuEDr/Xn/kEuzyT+3IHDUHZbsSXTTm

## Context
I'm trying to align the hint at the center of a Field and when the user adds the text it should be aligned to the left
currently, I left both the hint and value to aligned to the center

## Your environment
* Version of FlutterFlow used: v3.1 web & v1.1.33 macOS Desktop
* Platform: Web, macOS Desktop 
* Browser name and version: Chrome
* Operating system and version: Desktop

**Comment by hariprasadms** [comment]
Hi @yoheisoito - Thanks for reporting this issue. I can re-produce it. Added a quick video below showing the issue. 

https://user-images.githubusercontent.com/17435678/219953607-da05b5fe-dc60-4ba6-bb61-1bf3d0c4452e.mp4

**Comment by agreaves** [comment]
Hi @iamgenes, thank you for the bug report! You are correct, however unfortunately there is no way to do this in Flutter so this is not something we can fix at the moment. We used to not allow setting alignment for Hint and Label text but we mistakenly added it recently. We will remove the option from the editor in the upcoming release. Apologies for the inconvenience!

**Comment by iamgenes** [comment]
Hi @agreaves thanks for the update and clarification.
