### ISSUE TITLE
Flutterflow and Cursor Error: Flutterflow Version Out Of Date

### ISSUE THREAD

**Issue by sasalmarcon** [FlutterFlow/flutterflow-issues#5091]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After I open a project, a pop up saying "flutterflow version is out of date", when I click on refresh it refreshes the page and the same pop up keeps popping up
![Screenshot (5)](https://github.com/user-attachments/assets/a1c82f5f-caa7-415f-93a1-8f838469824c)

### Expected Behavior

After I click on the refresh button in the pop up it should give me the latest updated version and there should not be pop up.

### Steps to Reproduce

1. Create a New Project.
2. Create a new function in the project.
3. Set Up Cursor for flutterflow
4. Download code in the cursor by giving project Id of flutterflow
5. Start Code Editing Session
6. Make some changes in the custom function.
7. Now push latest changes to flutterflow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no bug report code as I cant access project after loading

### Visual documentation

![Uploading Screenshot (5).png…]()

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform:web
- Browser name and version:Google Chrome and Version 131.0.6778.139 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment]
Hello!<br><br>I’m sorry to hear you’re experiencing this issue! In situations where the bug report code isn’t available and the issue can’t be replicated on our end, I recommend reaching out to our support team directly. You can do this via the in-app chat (blue icon in the bottom-left corner of the Dashboard) or by emailing us at [support@flutterflow.io](mailto:support@flutterflow.io).

Our support team will be happy to assist you further!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
