### ISSUE TITLE
It is not possible to select lottie animations from assets

### ISSUE THREAD

**Issue by sebastiannuclea** [FlutterFlow/flutterflow-issues#5097]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to select lottie animations uploaded as assets in the flutterflow project, it is not possible to select any of the uploaded assets; the upload file button always appears

![image](https://github.com/user-attachments/assets/883844a0-940f-4cba-be93-7c8e370d0ffa)
![image](https://github.com/user-attachments/assets/d944ac7d-0708-4fd9-ba2b-7bad18ab5b06)

### Expected Behavior

Lottie animations loaded in the project assets should be selectable

### Steps to Reproduce

1. Add lottie animation widget to the widget tree
2. Select "Assets" in Animation source section
3. Trying to clic on button below "Asset animation"; in this step the assets uploaded doesn´t appear  

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlcrlvJN1m7QA+KrcavpajicsI0MWXZJE0utuTRQoGO/uPIkAP8zBP1dUOO2/SnxEME39oGAX/MnIvtnhJMFcOTOrbYBD/7p+UTmXYDm6VL60DK63b3RtL/JgI1Sj57TUkApDAM12Lnwd7Vz6Nu+8bDbAJ5v7OEVEBeaeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://www.loom.com/share/99735a4e921c439ea5e45399c0de8da5?sid=b2fee82d-35d6-4bc5-bbdc-2037f8b234f3

### Environment

```markdown
- FlutterFlow version: https://www.loom.com/share/99735a4e921c439ea5e45399c0de8da5?sid=b2fee82d-35d6-4bc5-bbdc-2037f8b234f3
- Platform: Web, Windows Desktop
- Browser name and version: Google Chrome Versión 131.0.6778.140
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello! I’m sorry to hear you’ve encountered this issue. The good news is that it has already been reported, and our team is actively working on a fix. You can track the progress here:

[GitHub Issue #5088](https://github.com/FlutterFlow/flutterflow-issues/issues/5088)

Thank you for your patience and understanding!
