### ISSUE TITLE
Flutterflow bug with Firebase

### ISSUE THREAD

**Issue by Vegetto78** [FlutterFlow/flutterflow-issues#5098]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I just have seen new errors on my app on Flutterflow. I hadn't errors one week ago and now I have more than 700 errors. Maybe because of Firebase with a new update ? 
<img width="220" alt="image" src="https://github.com/user-attachments/assets/02416a2c-56d1-4a8c-89ab-913474ac1618" />

### Expected Behavior

No more errors and a way to find a solution

### Steps to Reproduce

1.App created and is functionnal
2. Everything is good
3. I see a new Firebase Update but i's about Google, firefox...
4. More than 700 errors.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

jjj

### Visual documentation

<img width="220" alt="image" src="https://github.com/user-attachments/assets/eeb58d04-be65-4d27-b040-b88e115bbb62" />

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment]
Hi @Vegetto78,

I’m sorry to hear you’re facing this issue. Could you please confirm if you’re experiencing the same behavior on the web? If not, try clearing the cache. You can find it at:

`C:\Users<user_name>\AppData\Roaming\FlutterFlow\flutterflow`

Let me know if this resolves the issue!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
