### ISSUE TITLE
Flutterflow windows app keeps stuck on loading screen

### ISSUE THREAD

**Issue by JorVanDia** [FlutterFlow/flutterflow-issues#5099]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i open the windows desktop app of FlutterFlow on my desktop, it keeps loading (yesterday it worked fine)

### Expected Behavior

Overview of projects or login screen

### Steps to Reproduce

I just open the desktop app, perhaps difficult to reproduce

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

impossible

### Visual documentation

![2024-12-13_12-10-13](https://github.com/user-attachments/assets/9924c62a-29ad-4999-ae52-6e23c41bcabe)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Windows Desktop
- Browser name and version: /
- Operating system and version affected: Windows 11
```

**Comment by JorVanDia** [comment]
UPDATE:

It's after an login attempt that this appears. Tried, Google login and username/password login. Both failed an freeze on load screen.

**Comment by JorVanDia** [comment]
UPDATE:

It seems to work again

**Comment by paulperez-dev** [comment]
Hi @JorVanDia,

Thanks for the update.

**Comment by htsnet** [comment]
I have the same behavior. When I open the Desktop FF, the screen shows that it is loading forever.

I removed the program from Windows, deleted the folder FlutterFlow inside the appdata/user/roaming and reinstall the program—same issue.

I am using Windows11 on PC, where I am experiencing this behavior..

On my note, even with Windows11, it is ok (so, it is not about the account).

Any suggestion?
