### ISSUE TITLE
Expanded text widget alignment not affect when we set it to be selectable

### ISSUE THREAD

**Issue by davidflutterflow** [FlutterFlow/flutterflow-issues#510]
![image](https://user-images.githubusercontent.com/103986553/220112035-cbe53ec5-b3d5-4934-8331-d51fbea7cbb5.png)

When we set a text field selectable, the aligh shouldn't be affected at all.

Text expanded : works fine
Text Expanded selectable : Issue : align to center and the align option not affect anymore

## Current behavior (required)
Text Expanded selectable : Issue : align to center and the align option not affect anymore

## To Reproduce (required)
Project: https://app.flutterflow.io/project/text-selectable-aligh-issue-ollwzv

The issue reproduced in this project

1- Put a text widget in a row
2- make the text expanded
3- now turn on the selectable option

**Comment by hariprasadms** [comment]
Hi @davidflutterflow - I just tested it. I can re-produce the issue.

**Comment by wenkaifan0720** [comment]
Hi @davidflutterflow, @hariprasadms. This is only happening on the web, not on iOS or Android. So I believe this is a Flutter web issue, and we just have to wait for the Flutter team to fix it.
