### ISSUE TITLE
Listview infinite scroll is flickering and jumping to the first list item of the page

### ISSUE THREAD

**Issue by duuetdev** [FlutterFlow/flutterflow-issues#5100]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I activated infinite scroll on a thread of users posts and I kept the page size as 80. When users are scrolling down, the new pages are loading too fast(before a page size of 80). Then, when users are scrolling up, it's flickering and pushing the user to the previous page.  

I've tried keeping the listview widget inside a fixed height container but it still does the same effect.

### Expected Behavior

The page should load after the right amount of page size is completed. When the user scrolls upwards, there should be no flickering effect and it should scroll smoothly. 

### Steps to Reproduce

1. Keep infinite scroll turned on in a listview of objects and then try scrolling down
2. Notice that the loading is happening too early on
3. Notice that when you're scrolling up, it's flickering and the pages are moving upwards way too early.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/q35NItbxb+bnQKMFGiQMxQUQ5a50rlu1FGU00fKqtPYouYePEaXdBQumXewliG1W0ikc0+crXhofLMvQ3PgqsQb1607VQaTvwJXKuRrqPCc60XmtCGehhBWq5yKSs2h4kLrdsc14d20+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/6b2b7fc2-df9d-4943-8ad8-58bd0a4dd702

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.16
- Platform: Web & App versions both
- Browser name and version: Arc Version 1.73.0
- Operating system and version affected: MacOS 15.1.1
```

**Comment by paulperez-dev** [comment]
Hi @duuetdev,

To better isolate this issue, I’d like to rule out some possibilities. Could you please remove or hide the image for each post and check if the issue persists? The goal is to have every card with the same height.

Thanks!

**Comment by cmregazzo** [comment]
Good afternoon,

I'm having the same problem here.

After updating FlutterFlow to version v5.0.13+ released December 11, 2024, when using Infinite Scroll, the API is called twice when assembling the Page.

Even before scrolling the ListiView, the API is called twice.

Thanks.

**Comment by duuetdev** [comment]
> Hi @duuetdev,
> 
> To better isolate this issue, I’d like to rule out some possibilities. Could you please remove or hide the image for each post and check if the issue persists? The goal is to have every card with the same height.
> 
> Thanks!

Hi, yes, I've tried removing the images and fixing the container height. The same effect is occurring.

**Comment by paulperez-dev** [comment]
Hi @duuetdev,

I wasn’t able to reproduce this behavior on my end. Are you able to replicate it in a blank project?

You can also try removing components one by one from the container to see if a specific widget might be causing the scroll jank.

**Comment by arniigreat1** [comment]
Pretty sure relates to this issue:

https://github.com/FlutterFlow/flutterflow-issues/issues/2683

Which was never solved

**Comment by duuetdev** [comment]
I actually tried keeping the containers of the elements at a fixed height again and it worked well. There was no flickering. The problem is now that I can't keep a fixed height for my containers since it's a social media application which allows users to post with and without photos. So the height will inherently be changing as per the child element. Is there any way to fix with children of dynamic height?

**Comment by paulperez-dev** [comment]
Hi @dueetdev,

You could try adding an animation (like changing the image size) to help prevent the quick change in the container size. This might create a smoother transition.

I’ll go ahead and close this for now, as this is not a FlutterFlow issue.
