### ISSUE TITLE
Unable to add Deploy to App Store details

### ISSUE THREAD

**Issue by Rishay97** [FlutterFlow/flutterflow-issues#5102]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to deploy my FlutterFlow app to the iOS App Store. I have a developer account and set up App Store Connect appropriately. I have all the required keys and file. I now want to deploy the app from FlutterFlow to App Store Connect. When I type ANYTHING in either of these fields: issuer ID, key ID, app ID or Upload private key, the inputted text disappears after around 10 seconds. When I past my App ID in, after 10-20 seconds the key disappears and an error message states that app ID has to be a 9 or 10 digit number. The same goes for the other boxes. This means that I am unable to upload my app to the iOS App Store.

### Expected Behavior

I would expect that once I paste my details into the text box, they would remain there. Therefore allowing me to deploy my app to the App Store 

https://github.com/user-attachments/assets/2ab05ac4-dd5a-4b58-9f46-ae8733b32f1f

### Steps to Reproduce

1. Create new project
2. Click on App Settings
3. Click on Mobile Deployment
4. Enter an app ID into the App ID text box
5. Click on another text box (such as key ID)
6. Wait 10 seconds (or 20 seconds)
7. The error will appear: App ID has to be 9 or 10 digit number

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkPHq5c9NsdtJ7q6JccZVqycWJWkcTIMziNZ+exUbfaL1BqQId87SV1hBYMThaVNcM2KkiXMypcrOiYf1OPkBOTqcGbpjzcxyFDree2iRaYShCLidPXJSM/lmCnay5KuNgQpRCMBpSHgR31yUAO7KEy7DFOu/Zwh9f6PHaOI=

### Visual documentation

![IMG_5004](https://github.com/user-attachments/assets/eec3e7f0-609d-4fa6-95b1-48badc91e73b)
![IMG_5005](https://github.com/user-attachments/assets/92ecd1e6-08ad-49d7-8114-2505c5bc0b87)
![IMG_5002](https://github.com/user-attachments/assets/73fae9d2-e74d-4961-b72b-bcf6c9d159fb)

### Environment

```markdown
- FlutterFlow version: 5.01
- Platform: iOS platform to deploy, but affecting all FlutterFlow version, regardless of platform
- Browser name and version:Windows local run, edge browser, IpadOS app, Ipad OS browser
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @Rishay97,

This issue has already been reported and is being tracked under #5086. It should be fixed, so please ensure you’re using the latest version.

I’m closing this as a duplicate. If you’re still experiencing the issue, please comment on the mentioned ticket.
