### ISSUE TITLE
Supabase INSERT action sends a SELECT request

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#5107]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a write-only table in my Supabase DB for storing anonymous user feedback. In order to prevent users to read other users' feedbacks, I restricted the RLS policy for this table to INSERT only.

I created a form and the submit button has a "Supabase Insert Row" action to store the form contents. 

But the action causes an error, because it tries to run a "SELECT * LIMIT 1" query for no reason.

### Expected Behavior

It should only send an INSERT request. Not SELECT.

### Steps to Reproduce

1. Create a supabase table with one text column
2. Set the RLS policy to "INSERT for PUBLIC"
3. Create a form with a single textfield
4. Set the button submit action to "Supabase Insert Row". Send the textfield contents to the created text column.
5. Test and see that the applications tries to send a Select request, which fails due to RLS policy.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzPHq24VIscsA14SJc+0w9TgROUccTeU30+thcw4bI+PtB7MIZcn4YktvWOqHSm1cP1KbhmQGpd3GvuDmUvoVCzaYRa55zJd9UxDiIVKgR4/XDc3oPkcnAfxUCEDFy8OvkyZdNvZvZXAj1DmIeuuub3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="937" alt="image" src="https://github.com/user-attachments/assets/552d487f-d22c-49fa-b1ac-08c8a52a6883" />

<img width="794" alt="image" src="https://github.com/user-attachments/assets/2c28a99c-2637-44c7-afaf-9b577d4e98e1" />

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.16 released December 12, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: MacOS Sequoia
```

### Additional Information

When I change the RLS policy and give SELECT rights, it works. But obviously I don't want to do that in production.

**Comment by paulperez-dev** [comment]
Hi @kantarse,

I can't replicate this issue.

Could you please share the exact configuration of all the RLS policies you’ve set up for your table? This information will help me better understand the issue and assist you more effectively.

Thanks in advance!

**Comment by paulperez-dev** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
