### ISSUE TITLE
ListView backend query fetching Firebase Docs issue

### ISSUE THREAD

**Issue by mUmarBaloch** [FlutterFlow/flutterflow-issues#5108]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Backend query for fetching list of docs from a firebase collection "users". was working fine, suddenly showing error, with the uid of each document of that collection, the error in console is following:-
Error serializing doc users/qlnDTBlE1eTfEZ905VPk30ryjui1:
NoSuchMethodError: 'toDouble'
Dynamic call of null.
Receiver: "f"
Arguments: []

### Expected Behavior

ListView should fetch all Docs successfully in Backend Query, and show respected data of each Doc in text dynamically, without any error

### Steps to Reproduce

1. Create ListView.
2. Add Backend Query to fech firebase list of docs from collection "users"
3. Show data of each doc in a text dynamically
4. Not Showing data of docs
5. Console showing error for each doc :-  Error serializing doc users/qlnDTBlE1eTfEZ905VPk30ryjui1:
NoSuchMethodError: 'toDouble'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8mB4ot1od9E1aqMbcFKjj44Qm4kTL07r+5xb0gvIrbyOu9+duDRXFRVZ7C8T2lhHFKahnwH/+D2j9nPD/lfZDCdfLpNwpFpWxfvf3q8R6qNCLisZXMkJ8dQfxGi1sKJhhVQGNpYdXwt7U+XfeeXbD3sJ5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/f8200a3f-05e6-4045-b9d6-9cfd9e92377e)
![image](https://github.com/user-attachments/assets/7f2ecd81-5e4f-4cba-b84b-7fb1f3670ad9)
![image](https://github.com/user-attachments/assets/16383425-e533-4de3-adc7-7dc72196293c)
![image](https://github.com/user-attachments/assets/aac7deae-bd77-4ad4-9698-e47ac2234e36)

### Environment

```markdown
- FlutterFlow version:  v5.0.0+ released December 13, 2024
- Platform: Web
- Browser name and version: (web): Edge 131.0.2903.99 (Official build) (64-bit)
- Operating system and version affected:  (desktop) Windows 10 Pro 64-bit
```

### Additional Information

This is my Freelance Project, and the client is in hurry, The Project was on testing , this particular issue raised at the very end of testing , and we have to deploy this project Asap, to meet the deadline.

**Comment by Alezanello** [comment]
Hello!

I’ve reviewed the project and couldn’t identify any errors that might be causing this issue. Could you please provide us with a test or demo account so we can log in and investigate further?

Thank you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by mUmarBaloch** [comment]
please tell me what kind of more information you need. @Alezanello
