### ISSUE TITLE
Cannot choose document type in the Return type

### ISSUE THREAD

**Issue by nesanton** [FlutterFlow/flutterflow-issues#5109]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set if/then/else for the gridview child generator value, I have to specify the return type. As of lately I can no longer do it, because all the return types in the drop down turned into IDs and do not populate into the field when clicked on.

### Expected Behavior

Document types in the return type field are displayed as names of the collections and are selectable

### Steps to Reproduce

Have Firebase with a few collections connected to your project, Create a grid view and go to its children generator. Choose if/then/else as the value and without even populating (or with) the if and else values, try to set the return type to Document. When trying to choose the Document Type observe that the items in the drop down are IDs and when clicked they are not populating the return type field.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sicnf3IZOxLhc+KX6KPpr/CkvG1gga4Iascp8RQEYGIjJP4kQPPWlQ1VuUsegY2xAfESmmTgH+crUiPHLDvo6HzGdGqpCz7hcdzrwQkeiUZOBEs63dHBCJ9JYfW6G56Wv2B15IrJ1R1IY2l6qGfCUSnHZNO62IndISq/LZO4=

### Visual documentation

<img width="657" alt="Screenshot 2024-12-15 at 14 59 43" src="https://github.com/user-attachments/assets/0748c1b4-cf85-4b8c-bb28-78175ca8cd4b" />

### Environment

```markdown
- FlutterFlow version: 5.0.16
- Platform: mac
- Browser name and version: chrome
- Operating system and version affected: Sequoia 15.1.1
```

### Additional Information

My MVP is down due to it, which makes me unable to present it next week as planned

**Comment by nesanton** [comment]
grid view can be replaced with just any widget that can generate children

**Comment by Alezanello** [comment]
Thank you for bringing this to our attention! I’ll forward this to our engineering team so they can work on a fix.

**Comment by gzwanepoel** [comment]
I seem to be having the same issue 
![image](https://github.com/user-attachments/assets/0610903d-a9ed-41dc-8d8c-614f9e490348)

**Comment by sunnydutt12** [comment]
I am also facing the same issue. It's been more than 5 days. How long is it going to take to be resolved?

**Comment by yurisouza** [comment]
There is no forecast yet @FlutterFlowEng ?

**Comment by nathankrishnan** [comment]
Hi @yurisouza, we have a fix for this and the ETA for it being live is this Thursday (12/26).

**Comment by B0YTR** [comment]
Finally ! Thank you !
