### ISSUE TITLE
Condition with termination right after it, Could cause build error

### ISSUE THREAD

**Issue by davidflutterflow** [FlutterFlow/flutterflow-issues#511]
![image](https://user-images.githubusercontent.com/103986553/220359116-593c63d4-6fa7-44b4-828a-fe29b082d313.png)

Reproduced in: https://app.flutterflow.io/project/empty-condition-b-u-g-f92fl3
Run mode link: https://app.flutterflow.io/run/RXSKmAxLgjBoXYq5SGhS

1- Put a condition true or false
2- right after that terminate the action

Run the project you will see the build error

![image](https://user-images.githubusercontent.com/103986553/220359483-297e415f-53fb-429f-b6bb-15ed0c9f2820.png)

**Comment by hariprasadms** [comment]
Hi @davidflutterflow - Can you please update issue details as per issue template guideline. Once you have added details we can look into the issue. 

For a quick check, I can test the issue as per the image you have added above. It works fine for me.

**Comment by agreaves** [comment]
Hey @davidflutterflow! Nice catch, we've applied a fix which should be present in the next release! 🙂
