### ISSUE TITLE
Local Test for Real Device Not working !

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#5110]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All the setup is already ready because I'm testing by Flutter first but in FlutterFlow not work ist show up that project need to be set but xcode is running and the ios build is done !

### Expected Behavior

Should to be work, I don't remember if I made a test by a real device before but now seems not !
Why I want real device because I need to test RevenueCat and physical device is required as you know.

### Steps to Reproduce

- Setup xcode project 
- Add device to Devices store connect 
- Setup Local Test in FF

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wis/q24ZNpbxD7qqNY+9ViSQUIjo4bbs3mtZHSis8JJToPLAUZ8zBM05vZryndwliJEyZoHo0/PfqitrEVvQ3NTmAbr1z+JNuURXMWlGmRqagPamBfW1QHfhPJmLG1sKo3BF+Oux1LHtn2mWMIumWcHHACZu2OzINJuW1LdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1671" alt="image" src="https://github.com/user-attachments/assets/1e99f0eb-9966-4ff9-bac8-f2084047377a" />
<img width="987" alt="image" src="https://github.com/user-attachments/assets/2036c4a8-0f7c-4979-a4f6-852c46a28f8c" />

### Environment

```markdown
- FlutterFlow version: v5.0.16
- Platform: iOS
- Browser name and version: chrome
- Operating system and version affected: macos Latest
```

**Comment by Alezanello** [comment]
It seems the issue might be related to your real device not being properly registered with your Apple Developer Program. To resolve this, please ensure the following steps are completed before installing your app:

1. **Specify your Apple ID** in the Account Preferences in Xcode.
2. **Set a valid team** in your project’s **Signing & Capabilities** pane.
3. **Code sign your macOS app** if it includes features that require code signing (e.g., specific capabilities).
4. **Register your device** with your team if you are part of the Apple Developer Program.
5. **Enable Developer Mode** on your iOS, watchOS, or visionOS device as outlined here: [Enabling Developer Mode on a Device](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device).

For detailed guidance, refer to the official Apple documentation: [Running Your App in Simulator or on a Device](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device).

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
