### ISSUE TITLE
Hover Color Glitch On Text Feild

### ISSUE THREAD

**Issue by BalramShah** [FlutterFlow/flutterflow-issues#5113]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Lets say my Scaffold color is light Blue and my text field fill color I set it to White. And I don't any color on hover but There is default hover color which I dont so to nullify it, i kept hover color as white(same as text field fill color). But now, while however its is flashing gray color and then turning white. Its looking very awkward glitched website/app.

### Expected Behavior

1. Need button to disable the hoover color on text field without glitching any color. 

2. Also, if we set any hover color, which is lighter then background, its is glitching (Flashing gray color while on hover for 0.1 sec), So this color glitch need to be removed. 

### Steps to Reproduce

1. Create a Page
2. Set Page scaffold color as #dbe7f9
3. Add a text field
4. Add texfeild fill color as white
5. Add texfeild hover color as white
6. Run the program
7. Just mover the mouse over and outside the text feild.
8. Gray color will appear like a glitching.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXl8j6yIhhsshE+pCBasBVpGYwGUAaU40V0t1ETRQbCIj4EIouPfT8SEhDUtCzaH9LfFGjnkQEw9b5vYX9KfJeA0mrRro6/qhcdRPPbDiiaZikDamRPUZ9J+ZVCX3Gy7bYqx54JvtuSWQs2FyqO+TJYz6Cf9qOYwx5e6fDbOY=

### Visual documentation

Its goes away in 0.1 sec and very difficult to capture its immage

### Environment

```markdown
FlutterFlow v5.0.0+ released December 13, 2024
Flutter version is 3.24.2
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue on my end. Even with dark mode enabled and hovering over the element, I couldn’t observe the gray color you mentioned.

To help investigate further, I’ve created a public project for testing: [QA 3283](https://app.flutterflow.io/project/qa-3283-zkrzd6). Feel free to clone it and test it out. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/817d7803-8298-436d-a7ad-d5292b576b22/7b2abd25-30dd-4b33-9f35-0000200f7521?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MTdkNzgwMy04Mjk4LTQzNmQtYTdhZC1kNTI5MmI1NzZiMjIvN2IyYWJkMjUtMzBkZC00YjMzLTlmMzUtMDAwMDIwMGY3NTIxIiwiaWF0IjoxNzM0MzY4MDEwLCJleHAiOjMzMzA0OTI4MDEwfQ.SQPt0l7cFwfsXzJI-nayCh2vZvfbISoWbTYcW8YV2OM " alt="textfield.gif" width="475" data-linear-height="798" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by BalramShah** [comment]
The test you showed is dark color in text field, make text field white, and keep scaffold as it is(Dark color) you will see the glitch. Also set text field hover color as white.

**Comment by BalramShah** [comment]
And also set color on hover as white.
