### ISSUE TITLE
JSON asset not showing up to be chosen in Lottie Animation widget

### ISSUE THREAD

**Issue by Jeffcyw** [FlutterFlow/flutterflow-issues#5114]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/9ec4ca8f-8c17-4fc6-96b2-60449c582b91)
![image](https://github.com/user-attachments/assets/297a135d-0f02-4692-a89a-555c6c9fa73a)

Uploaded a couple JSON lottie in asset but can't be chosen. Previously is working fine.

### Expected Behavior

Uploaded lottie asset can be chosen

### Steps to Reproduce

Create lottie animation and select an asset

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPVvnRPxJoTem+f2w7OWGZjjsxw6HKhM7DVPk3IU+uGdl63JVqSxfyJHy5eK2VCqi8PkF5P8BnIWmB05jUrxJWA+FYdE4j72b7GeyiaADZJYTsNlgRPciXDKnNjlagFXi+AjtW7xYXEx7eTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

![image](https://github.com/user-attachments/assets/0a962f21-4927-4f91-bbbf-58f4ea0f2e84)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

Thank you for reporting this. This is a known issue and is currently being tracked in this ticket: [GitHub Issue #5088](https://github.com/FlutterFlow/flutterflow-issues/issues/5088).

To keep things organized, I’ll close this thread as a duplicate. Please feel free to follow the linked ticket for updates.

Thank you for your understanding!
