### ISSUE TITLE
Merge dev into main completely borked and no idea why

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5115]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

dev-> main broken: https://www.tella.tv/video/merge-mayhem-5n4d
main->dev working: https://www.tella.tv/video/brians-video-0ijd

Merging main into dev works but dev into main does not... not good

some basic text editing seems to merge dev-> main, but a consistent 79 conflicts and some large  uncounted number of other changes 

(also "restoring" a previous version seems to increment the version counter... not sure if that is expected behaviour or not)

### Expected Behavior

not the above

### Steps to Reproduce

no idea. way to many variables to test

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40sOX126xOscRJ15PqWuxGgmEsHGIjRLgJkNVraCosfZT2BLMcec/RVERoTsu+Y1FpPmaWkWoW0/eNj/DxCsYnFxSdbrlyz6l6cg3NfD+WM7aDFJWvPGhAHehmG3alyrbYmhN+KbZqR1IZwF2EAvOXEwTvH5CxDHo0Da/LZO4=

### Visual documentation

https://www.tella.tv/video/merge-mayhem-5n4d

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturns,

Thank you for reporting this! Unfortunately, we were unable to reproduce the issue in a blank project. It seems to be specific to your project. Could you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io) for further assistance? They’ll be best equipped to help get this resolved.

Thank you for your understanding, and let us know if you need anything else in the meantime!

**Comment by chuggmuffinReturns** [comment]
Ok no worries, Paul I will do that

Thanks a lot for taking a look for me :)
