### ISSUE TITLE
Unable to update headers using API Interceptor

### ISSUE THREAD

**Issue by vitul-goyal** [FlutterFlow/flutterflow-issues#5117]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to update headers using API Interceptor. When i run the code from FF, or by downloading the code, it works fine on physical device. But when i push the code to Github and pull the code to local system, API Intercept doesn't work on Physical device.

### Expected Behavior

API Interceptor should update headers

### Steps to Reproduce

1. Start a new project
2. Connect to Github
3. Create custom action and attach it to an API as API Interceptor.
4. In Custom action, write this code: options.headers['Authorization'] = "1234";
5. Push to Github and take pull request in local machine
6. Run on a physical device and the code will not work

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89grs9J1s/XbcZshmQ4H0A+TLJEpu0bWUkbGO/4B7AHP/T8XFZvZOazaHxmDWeJ+WMx/tLvj9/tKu46CzCtRoBl1c52ERPPbF25b5SpCZOCQkRPBZ1WIX3E15izpxFAGNRYWCUA33GYCd+RYz2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="532" alt="Screenshot 2024-12-16 at 8 17 30 PM" src="https://github.com/user-attachments/assets/53ef6f18-50a5-4759-9a71-f1a4bd599827" />

### Environment

```markdown
- FlutterFlow v5.0.0+ released December 13, 2024
- Flutter version is 3.24.2
- Platform: iOS and Android
```

### Additional Information

This issue is not allowing me to add custom packages or code. Also, i am unable to update strings in Android Manifest required to integrate Meta SDK.
I can get on a call if required to help in understanding the issue.

**Comment by Alezanello** [comment]
Hello!

I reviewed similar issues, and as you mentioned, everything seems to work properly when using FlutterFlow or downloading the code. Just one quick question: when you push to GitHub, do you have the **Dart Fix** option enabled?

If so, could you please disable it and try pushing again? Let me know how it goes!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
