### ISSUE TITLE
Whole screen get repainted with every scroll

### ISSUE THREAD

**Issue by kantarse** [FlutterFlow/flutterflow-issues#5118]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My web app suffers from a lot of jitter. It feels far from smooth, even though I don't have a big widget tree. 

To check if this is the issue, I enabled "Highlight repaints" option in Flutter debugger. So every time an element gets repainted, it shows a frame that changes color.

I realized that everytime I scroll the page, it causes a whole screen repaint. Even on pages with no animations and no images, the whole page gets repainted with every scroll.

See below an example from my Privacy Policy page, with full of (Rich) Text widgets and one switch widget.

### Expected Behavior

Unnecessary repaints must be avoided.

### Steps to Reproduce

1. Create a new page with many static basic widgets like images and text.
2. Test with "Highlight repaints" option of Flutter debugger and see that the page gets repainted with every scroll.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzPHq24VIscsA14SJc+0w9TgROUccTIMziNZ+exUbfaL1Bux/PcjOSFFtTs+/aVNceU6l8DkBwsLViM71IO43HzasGr5B1ZZUZQ/Oe2igbpSvDIe0RHFDL91RfH6j18CC2hYmIu1fciUEwDiAIeSUShHDFOu/Zwh9f6PHaOI=

### Visual documentation

![2024-12-11_22-37-17 (2)](https://github.com/user-attachments/assets/aef90eee-e3d9-47d7-8f67-e1fba6d4ac12)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.16 released December 12, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: MacOS Sequoia
```

### Additional Information

Flutter advises against big repaints and promotes widgets like RepaintBoundary to help avoid repainting big chunks of the page. Here is a good article and video about the issue: https://api.flutter.dev/flutter/widgets/RepaintBoundary-class.html

**Comment by paulperez-dev** [comment]
Hi @kantarse,

Page repaints during scrolling are expected behavior. The key is to avoid unnecessary repaints when the page is not being scrolled or repainting the entire screen when only a single widget requires updating.

I'm closing this issue.
