### ISSUE TITLE
Not possible to upload Lottie animation file, the button upload file doesn't work

### ISSUE THREAD

**Issue by PMFlis** [FlutterFlow/flutterflow-issues#5120]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot upload the lottie animation file. When using animation source Assets, I cannot upload the file or even choose the file for the animations that are already uploaded to media assets. I had animations already added to the project and they were already placed on the screen but when i open the project the links to asset disappeared from the animation source  and it is not possible to add them. I tested on FF web and have the same problem, and created also new project and I have the same problem with a new project too. 

### Expected Behavior

To be able to upload a new lottie animation or choose the one that was already uploded.

### Steps to Reproduce

1. Add widget Lottie Animation
2. Go to Animation source and choose Asset.
3. Tap on Upload file button. Nothing happens.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghvHluJN2vuZE7a6Jae9avCM7KUQ3aJc0sd4bGA0dCJzuPLMQdvWkUElCQtDnTwk7I0Smmk8d+N7RkoaWLcBeFzucfJtzwZZiSRXdcGKne5OBBsy8SnR6DcdnIXKy37W3vCZDIbF2cVIm202QA+jKfC7ZK4exIndISq/LZO4=

### Visual documentation

![Lottie Animation](https://github.com/user-attachments/assets/65ecad84-510f-4d54-a925-0f4b44cc81e1)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ and FlutterFlow v5.0.17 
- Platform: web
- Browser name and version:chrome 
- Operating system and version affected: ios mac book
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re facing this issue. The good news is that it’s a known problem, and the team already has a fix prepared that will be deployed soon!

For reference, here is the original issue: [#5088](https://github.com/FlutterFlow/flutterflow-issues/issues/5088).

I’ll close this one as a duplicate but will link it internally to keep everything tracked. Thank you for your understanding!

**Comment by PMFlis** [comment]
OK, thank you for the update.
