### ISSUE TITLE
List View Scrollable Issues

### ISSUE THREAD

**Issue by ajeets1978** [FlutterFlow/flutterflow-issues#5121]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a custom widget, which has expandable feature on click of a down arrow it shows the hidden content and expand. This is an item to a scrollable list view. I still have the previous app and videos of working version from last night.

It was all working fine till last night, its broken after today flutterflow upgrade.

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
js_primitives.dart:28 The following assertion was thrown during performLayout():
js_primitives.dart:28 RenderFlex children have non-zero flex but incoming height constraints are unbounded.
js_primitives.dart:28 When a column is in a parent that does not provide a finite height constraint, for example if it is
js_primitives.dart:28 in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
js_primitives.dart:28 flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
js_primitives.dart:28 space in the vertical direction.
js_primitives.dart:28 These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
js_primitives.dart:28 cannot simultaneously expand to fit its parent.
js_primitives.dart:28 Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
js_primitives.dart:28 children (using Flexible rather than Expanded). This will allow the flexible children to size
js_primitives.dart:28 themselves to less than the infinite remaining space they would otherwise be forced to take, and
js_primitives.dart:28 then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
js_primitives.dart:28 constraints provided by the parent.
js_primitives.dart:28 If this message did not help you determine the problem, consider using debugDumpRenderTree():
js_primitives.dart:28   https://flutter.dev/to/debug-render-layer
js_primitives.dart:28   https://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html
js_primitives.dart:28 The affected RenderFlex is:
js_primitives.dart:28   RenderFlex#11208 relayoutBoundary=up56 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE(creator: Column ← Column ← Padding ← Padding ← DecoratedBox ← ConstrainedBox ← Container ← AnimatedContainer ← GameCardListItemWidget-[<'Keyzas_0'>] ← DebugFlutterFlowModelContext ← Builder ← _InheritedProviderScope<GameCardListItemModel?> ← ⋯, parentData: offset=Offset(165.5, 104.0); flex=null; fit=null (can use size), constraints: BoxConstraints(0.0<=w<=331.0, 0.0<=h<=Infinity), size: Size(0.0, 0.0), direction: vertical, mainAxisAlignment: start, mainAxisSize: max, crossAxisAlignment: center, verticalDirection: down)
js_primitives.dart:28 The creator information is set to:
js_primitives.dart:28   Column ← Column ← Padding ← Padding ← DecoratedBox ← ConstrainedBox ← Container ←
js_primitives.dart:28   AnimatedContainer ← GameCardListItemWidget-[<'Keyzas_0'>] ← DebugFlutterFlowModelContext ← Builder
js_primitives.dart:28   ← _InheritedProviderScope<GameCardListItemModel?> ← ⋯
js_primitives.dart:28 See also: https://flutter.dev/unbounded-constraints
js_primitives.dart:28 If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
js_primitives.dart:28   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
js_primitives.dart:28 
js_primitives.dart:28 The relevant error-causing widget was:
js_primitives.dart:28   Column
js_primitives.dart:28   Column:file:///tmp/ff_service_scratch/8N7J44G59LMLiKMXGw2k/gamespiggy/lib/components/game_card_list_item_widget.dart:192:13
js_primitives.dart:28 
js_primitives.dart:28 When the exception was thrown, this was the stack:
js_primitives.dart:28 dart:sdk_internal 12007:11                                    throw_
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93651:21   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93654:26   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 107402:13  layoutChild
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93568:74   [_computeSizes]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93655:40   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 108573:34  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 108573:34  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 102436:36  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 88376:45   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 66140:34   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 88245:13   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 68806:17   layoutChildSequence
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 100669:19  [_attemptLayout]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 100600:46  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 106812:13  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 107402:13  layoutChild
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93568:74   [_computeSizes]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93655:40   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 60266:36   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 106812:13  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 107402:13  layoutChild
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93568:74   [_computeSizes]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 93655:40   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 60266:36   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 106812:13  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54896:18   <fn>
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 54898:11   performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 108573:34  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 107402:13  layoutChild
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 108061:27  [_computeSize]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 108081:43  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53188:14   layout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 70012:29   layoutChild
js_primitives.dart:28 packages/flutter/src/material/time.dart.js 83123:14           performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 70056:14   [_callPerformLayout]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 107373:44  performLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 53063:14   [_layoutWithoutResize]
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 113144:44  flushLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 113154:17  flushLayout
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 112840:30  drawFrame
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 207026:15  drawFrame
js_primitives.dart:28 packages/flutter/src/widgets/unique_widget.dart.js 112804:12  [_handlePersistentFrameCallback]
js_primitives.dart:28 packages/flutter/src/scheduler/binding.dart.js 934:9          [_invokeFrameCallback]
js_primitives.dart:28 packages/flutter/src/scheduler/binding.dart.js 893:37         handleDrawFrame
js_primitives.dart:28 packages/flutter/src/scheduler/binding.dart.js 812:12         [_handleDrawFrame]
js_primitives.dart:28 dart:sdk_internal 207808:7                                    invoke
js_primitives.dart:28 dart:sdk_internal 178890:15                                   invokeOnDrawFrame
js_primitives.dart:28 dart:sdk_internal 207579:57                                   <fn>
js_primitives.dart:28 dart:sdk_internal 69535:14                                    _callDartFunctionFast1
js_primitives.dart:28 dart:sdk_internal 69473:22                                    ret
js_primitives.dart:28 
js_primitives.dart:28 The following RenderObject was being processed when the exception was fired: RenderFlex#11208 relayoutBoundary=up56 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
js_primitives.dart:28   creator: Column ← Column ← Padding ← Padding ← DecoratedBox ← ConstrainedBox ← Container ←
js_primitives.dart:28     AnimatedContainer ← GameCardListItemWidget-[<'Keyzas_0'>] ← DebugFlutterFlowModelContext ← Builder
js_primitives.dart:28     ← _InheritedProviderScope<GameCardListItemModel?> ← ⋯
js_primitives.dart:28   parentData: offset=Offset(165.5, 104.0); flex=null; fit=null (can use size)
js_primitives.dart:28   constraints: BoxConstraints(0.0<=w<=331.0, 0.0<=h<=Infinity)
js_primitives.dart:28   size: Size(0.0, 0.0)
js_primitives.dart:28   direction: vertical
js_primitives.dart:28   mainAxisAlignment: start
js_primitives.dart:28   mainAxisSize: max
js_primitives.dart:28   crossAxisAlignment: center
js_primitives.dart:28   verticalDirection: down
js_primitives.dart:28 This RenderObject had the following descendants (showing up to depth 5):
js_primitives.dart:28     child 1: RenderPositionedBox#9c686 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
js_primitives.dart:28       child: RenderConstrainedBox#0c4e3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
js_primitives.dart:28         child: RenderDecoratedBox#983b8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
js_primitives.dart:28           child: RenderPadding#cce04 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
js_primitives.dart:28             child: RenderRepaintBoundary#915c6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
js_primitives.dart:28 ════════════════════════════════════════════════════════════════════════════════════════════════════

### Expected Behavior

List item which has list item, with a custom widget. This item widget has button which on click expands and shows the hidden content. Item expands and List should still be scrollable.

### Steps to Reproduce

1. Create a component
2. This component has a column
3. Column has a container 
4. Container again has a column with some content 
5. Column has another container, which is hidden in begin but on click of the button on this item, it becomes visible.

Add this widget to list view item and test.

List should be scrollable, and item should expand on click of the button on item widget, other items should push down.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8/q24lPm+FY1r6IYMdVvCYWQl8cTeUzlO1hdwwbI+LmPZYIPsnsVFdBSOqHfW9LeVCJ8V0z/9bphofpEvoVAE+sY4RczKhPUxDiZEaQM76JPLWOZH8mI8JbfkCs0ZiNhR54COppWVoaw3GqAfCua3qCf9qOYwx5e6fDbOY=

### Visual documentation

Working Version : https://app.flutterflow.io/run/50zqZt0QgWc43VINMcor
Current Non Working Version: https://app.flutterflow.io/run/50zqZt0QgWc43VINMcor

### Environment

```markdown
- FlutterFlow version: Where do I see that ??
- Platform: Android 
- Browser name and version: N/A
- Operating system and version affected: All
```

### Additional Information

My whole project is busted due to this.

**Comment by ajeets1978** [comment]
Its wierd the errors are in Test Mode, but not in Run Mode.

Following is Test mode and it doesn't work.
![image](https://github.com/user-attachments/assets/66a23c3e-838b-4968-bb65-748c6a5dd338)

Following is Run Mode, and it does work. Same thing no changes.

![image](https://github.com/user-attachments/assets/75d33270-4991-4a39-bc62-af72a9ceda00)

**Comment by ajeets1978** [comment]
1. Doesn't work in Test Web Mode
2. Doesn't work in Test Mode with Device in Local Setup
3. Works in Run Mode on Web
4. Works with apk downloaded on Device

It's so inconsistent behaviour, consumes lot of time to figure out if things are working appropriately.

**Comment by ajeets1978** [comment]
Another False Issue in Test Mode.

![image](https://github.com/user-attachments/assets/c48d0d52-33ad-4ac5-ac72-c640b692a7b9)

**Comment by Alezanello** [comment]
It seems that removing the **"js_primitives.dart:28"** part from your logs gives us the following error:

> ```dart
> The following assertion was thrown during performLayout():
> RenderFlex children have non-zero flex but incoming height constraints are unbounded.
> When a column is in a parent that does not provide a finite height constraint, for example if it is
> in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
> flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
> space in the vertical direction.
> These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
> cannot simultaneously expand to fit its parent.
> Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
> children (using Flexible rather than Expanded). This will allow the flexible children to size
> themselves to less than the infinite remaining space they would otherwise be forced to take, and
> then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
> constraints provided by the parent.
> ```

This happens when a **Column** (or **RenderFlex**) is placed inside a parent widget that does not provide a finite height constraint, such as within a **SingleChildScrollView** or another scrollable widget. In such cases, the column will attempt to shrink-wrap its children vertically. However, if you also use widgets like **Expanded** or **Flexible** within the column, it creates a conflict because these widgets require finite space to properly distribute their layout.<br><br>To fix it try changing the main axis/flex from your columns/rows and containers, if the problem is within the that widget then check first that widgets columns axis

**Comment by ajeets1978** [comment]
Ok, I understand what you said. But then why it only not works in Test Mode, it works when you build apk and install it on Device. It also works in Run Mode as shown in images above, which is confusing that why it will work on real device with APK and Run mode but shows error only in test mode?

**Comment by Alezanello** [comment]
Test Mode is a powerful tool for identifying render layout issues in your app. Even if the APK or Run Mode appears to work correctly, Test Mode provides valuable insights into what might be causing your app to freeze or crash. It’s one of the best ways to pinpoint and understand potential problems in your project.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
