### ISSUE TITLE
'Action Block' missing after merge.

### ISSUE THREAD

**Issue by ihsanberahim-openmindsresources** [FlutterFlow/flutterflow-issues#5122]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

branch [main] got 2 action blocks.
branch [dev] got 0 action blocks.

Action blocks missing from [main] after merge.

### Expected Behavior

Expecting action blocks not gone missing after merge.

### Steps to Reproduce

1. create commit in branch [main]
2. create commit in branch [dev]
3. trigger merge [dev] to [main]

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Visual documentation

<img width="412" alt="image" src="https://github.com/user-attachments/assets/e22cbe46-32a3-470a-8ab9-df96c95ecbda" />

### Environment

```markdown
- FlutterFlow version: 5.0.17
- Platform: Web
- Browser name and version: Application Local/ Chrome Browser
- Operating system and version affected: MacOS
```

### Additional Information

my team progress in dev branch cannot merge to [main] since the merge causing the problem.

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue. Let me share the exact steps I followed along with a video, just in case I missed anything:

1. Added a **Text Widget** on the HomePage.
2. Committed changes to **Main** and created a **Dev branch** with the committed changes.
3. In the **Dev branch**, added a **Button** and committed the changes.
4. In the **Main branch**, added **2 Action Blocks** and committed the changes.
5. Switched back to **Dev** and performed a **merge from Dev to Main**.
6. Reviewed the changes.
7. Merged the branches.
8. After the merge, verified that the **Main branch** retained the 2 previously created Action Blocks and also included the new Button added to the HomePage.

If you think I missed a step or there’s something different in your workflow, please let me know! I’m happy to look into it further.

[Screen-Recording (67).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/01403b6f-767b-4f72-aba5-e73234d80f30/f3097ddd-cd9a-4d29-8595-cf102173469c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMTQwM2I2Zi03NjdiLTRmNzItYWJhNS1lNzMyMzRkODBmMzAvZjMwOTdkZGQtY2Q5YS00ZDI5LTg1OTUtY2YxMDIxNzM0NjljIiwiaWF0IjoxNzM0NDU0NDE5LCJleHAiOjMzMzA1MDE0NDE5fQ.RUEK-Vc3KQdLY0TY6wzzk0gkWHodDkb2MlgS37IfuYE)

**Comment by ihsanberahim-openmindsresources** [comment]
Your flow is correct an exacly. I will re-open this issue later when i got more accurate report about the root cause.
