### ISSUE TITLE
custom code error

### ISSUE THREAD

**Issue by divingjoker** [FlutterFlow/flutterflow-issues#5123]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

always shows an error when i test the custome code

### Expected Behavior

expected to return aclik value

### Steps to Reproduce

the code work on my previous project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelPHhuJRNpb0F+aqNa+xGgQMxQUQ5a50rlu1FGEg0GLbnBJlzeePuaXdWOdOWeWxmeWaLsGAzpsLKuOPDCfAoOSycGI9607htEhbhcDiiWrKKC86CVXwnHZhmFUPD38GVqiQlC/phSV4F7HGHcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="1118" alt="螢幕截圖 2024-12-17 17 11 34" src="https://github.com/user-attachments/assets/efae7e9e-3594-4ced-9fbb-8702be3749e8" />
<img width="1272" alt="螢幕截圖 2024-12-17 17 11 59" src="https://github.com/user-attachments/assets/76906ed2-7e15-43c6-8d7c-945af1c53eeb" />

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform:web
- Browser name and version:chrome
- Operating system and version affected: macOS sonoma 14.4.1
```

### Additional Information

price summary

**Comment by Alezanello** [comment]
Hello!

I just checked your project, but I couldn’t find any custom function matching the one shown in the image. Did you delete it, or were you able to find a solution for this?

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
