### ISSUE TITLE
Cannot type anything when click in other textField only on Safari and Firefox

### ISSUE THREAD

**Issue by jubox974** [FlutterFlow/flutterflow-issues#5124]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have many textField in a Form Validation.

I click in one textField, and I can type anything on the keyboard. When I click in an other textfield, I can't type anything into the clicked textfield.

This happened in Flutter web with this browser : firefox, Safari.

It works well with Chrome (not tested with Edge).

I notice that when I go in other tab then when I go back on the page and click on the other textile that I want to type, it works.

### Expected Behavior

I expect when I click in any other textField I can type into it with firefox, Safari.

### Steps to Reproduce

I think is more useful to access the full project ?

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcrq25Ngod9c14SJbflaniAvKUA1RYIw0O1tZwsbN5PQDLN/ds/APhZCZ+rnTX9lMWC2p14Bw6HMiYT9OsY6AwubRa041ZBTFwvvRT6jb8STF7i8OkZADe1hClyx4LujpyNDLsZ2SmwswE2ACOuva3bZJ5D7DkQ8Sq/LZO4=

### Visual documentation

[https://github.com/user-attachments/assets/e10c6eaa-8967-4afb-9b42-e6155d879a31](https://github.com/user-attachments/assets/e10c6eaa-8967-4afb-9b42-e6155d879a31)

### Environment

```markdown
- FlutterFlow version: 5.0.17
- Platform: web
- Browser name and version: Safari Version 17.6 (19618.3.11.11.5) \ Firefox 133.0.3 
- Operating system and version affected: MacOS 14.6.1 (23G93)
```

### Additional Information

I Have some user complain that use firefox or Safari

**Comment by Alezanello** [comment]
Hello!

Just a quick question: What version of iOS is running on the device you’re using for testing?

**Comment by jubox974** [comment]
@Alezanello for this project I don’t use iOS just a web platform 

I have a staging platform where you can test it directly in browser if necessary

**Comment by Alezanello** [comment]
Anything that you can bring to us to help to identify the issue the best!

**Comment by jubox974** [comment]
@Alezanello possible to give you access in private for the team ?

**Comment by Alezanello** [comment]
Sure, here is my email azanello@somniosoftware.com, if you can give me the url and a password to test it!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
