### ISSUE TITLE
Document type in DocRef in "Has Value" option in Bottom Sheet Dismiss Action

### ISSUE THREAD

**Issue by duuetdev** [FlutterFlow/flutterflow-issues#5126]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you turn on the "has value" toggle after selecting the bottom sheet dismiss action. Now, try to pass a docref. You'll notice that the dropdown of document types are a combination of random letters and it's not possible to select any document type.

### Expected Behavior

All the different document types are shown there correctly and I'm able to select the correct one

### Steps to Reproduce

Turn on the "has value" toggle after selecting the bottom sheet dismiss action on a bottom sheet component. 
Try to pass a docref. 
Notice that the dropdown of document types are a combination of random letters and it's not possible to select any document type.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/q35NItbxb+bnQKMFGiQMxQUB+bZ0vlO1FGU0jfLWqOoYtOuLUaXdVXMeYfwt+AmKj+Dk0/87Wj+PqFcdeHzWCY71607VQaTvwJXKuRrqPCc60XmtCGehhBWq5yKSs2h4kLrdsc14d20+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/7f3da7ea-62a6-454c-89c9-62339749759c

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released December 16, 2024
- Platform: MacOS and web
- Browser name and version: Arc Version 1.73.0 (56815)
- Operating system and version affected: Mac OS 15.1.1
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that it’s a known problem, and the team has already prepared a fix that will be deployed soon!

For reference, here is the original issue: [#5109](https://github.com/FlutterFlow/flutterflow-issues/issues/5109).

I’ll go ahead and close this one as a duplicate but will link it internally to ensure it’s tracked properly. Thank you for your understanding!
