### ISSUE TITLE
Test mode UI not rendering

### ISSUE THREAD

**Issue by zbabs23** [FlutterFlow/flutterflow-issues#5127]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The UI goes white in the test mode even when I can see in debug panel that data is populating. This started happening once I built responsive UI for desktop. 

### Expected Behavior

Normal functional use of test mode

### Steps to Reproduce

1. Launch test mode
2. Go through onboarding steps (select "Business") or tap Sign in at the beginning
3. You will see the current behavior

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40keflsYt1pbwA+KqJb8FvmmU5JVg7aJ07iu1RaCosfZT2BLMcec/RVERvTbyiYH9YMVmKr2oW0cryidrxUO5eCyisbJRT/85Qdg3zUmK6bqaUFJWgVkdPJ+hgCXaw56SJuhFQKvhaSGAs2GayN+yvbHfdNKKwDkUgDq/LZO4=

### Visual documentation

<img width="1266" alt="Screenshot 2024-12-17 at 11 29 39 AM" src="https://github.com/user-attachments/assets/b108a3da-a1cb-4181-9a43-c55f08636e65" />

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform:Web
- Browser name and version: Chrome 131.0.6778.140
- Operating system and version affected: macOS 14.3.1 (23D60)
```

**Comment by Alezanello** [comment]
Hello!

Could you please share the logs generated in the console? This will help us better understand the issue.

**Comment by zbabs23** [comment]
See attached.



*Zack Babin | *Co-founder & CEO

My calendar <https://calendly.com/zack-babin23/meet-with-zack-babin>
www.modernltv.com
M: 201-835-2155


<http://www.modernwallet.co>

**Comment by zbabs23** [comment]
Any update on this? I’m facing some challenges where I need test mode.



*Zack Babin | *Co-founder & CEO

My calendar <https://calendly.com/zack-babin23/meet-with-zack-babin>
www.modernltv.com
M: 201-835-2155


<http://www.modernwallet.co>

**Comment by Alezanello** [comment]
Hello again,

It seems there’s no file attached to the GitHub issue. Could you please upload it directly to the platform instead of sending it via email? This will ensure we have everything we need to assist you.

Thank you!

**Comment by zbabs23** [comment]
[app.flutterflow.io-1734455844813 (1).log](https://github.com/user-attachments/files/18203416/app.flutterflow.io-1734455844813.1.log)

**Comment by Alezanello** [comment]
Hello again!

This issue commonly occurs when an `Expanded` widget is placed inside a `Column` or `Row` that includes a scrollable feature, leading to a `RenderLayout` error in Flutter. To resolve this, try setting the `Expanded` widget to its default state for any widgets within scrollable `Column` or `Row` structures in your project. This adjustment should help prevent the issue. Let me know how it goes!<br><br>For example on the following image you have an expanded container inside a scrolling column, if you set it to the default option everything will work perfectly

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/77ddf3fd-fb83-49c8-bd49-fb6b2ed69a9e/abff2ab5-bca1-41e7-a104-a7e977ed2c4a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83N2RkZjNmZC1mYjgzLTQ5YzgtYmQ0OS1mYjZiMmVkNjlhOWUvYWJmZjJhYjUtYmNhMS00MWU3LWExMDQtYTdlOTc3ZWQyYzRhIiwiaWF0IjoxNzM0NzI4MTA0LCJleHAiOjMzMzA1Mjg4MTA0fQ.D8atWD6LDiWeDbztBSD0OVKrGYgqeUSK9zmO6UzYwWQ " alt="image.png" width="1769" data-linear-height="489" />

**Comment by zbabs23** [comment]
Fantastic, thank you! I'll address this and let you know if any further
issues.


*Zack Babin | *Co-founder & CEO

My calendar <https://calendly.com/zack-babin23/meet-with-zack-babin>
www.modernltv.com
M: 201-835-2155


<http://www.modernwallet.co>

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
