### ISSUE TITLE
Conditional visibility based on the value of a dropdown component does not work

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#513]
## Expected behavior (required)
That conditional visibility works when the condition is an input component (in this case, a dropdown component) having a given value. 

## Current behavior (required)
Conditional visibility only works after another action is made. 

## To Reproduce (required)
1. Create a dropdown component called "dropDownComponent"
2. Give options values to your component (e.g., "Non" and "Oui; French for "no" and "yes")
3. Create a page. 
4. Include the dropdown component in that page and called it "dropDownQuestion". 
5. Add a container (or any other widget) with conditional visibility. 
6. For the conditional visibility, choose a single condition stating that "dropDownComponent" must be equal to "Oui".
7. Add any input widgets in the page (e.g., a slider, another dropdown, a textfield with an action on text change). 
8. Run the app. In the dropDownQuestion, choose "Oui". The conditional visibility will not work unless another action is made (e.g., selecting a value on the slider, writing in the textfield). 

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")
This is the bug report code for the main column in the testpage (see the recording): IT4KivHq389Pm8tD1aXIccdFoCYXGDsnRYIoltVDYwkbCJCsG7l/S8+kfhNuXbC0Y3x2f1r9rH81+tHemvziGPYqNQ6aRa5D+apuUTnxQkmiaL61Ds+gOC0ffaMKRSz+

## Context (required)
I cannot use conditional visibility based on components. 

## Screenshots / recordings
See this recording that illustrates the problem:
https://www.loom.com/share/a137a93f8ab84dc68aef7500d92eb787

## Your environment
Windows 11, Chrome, FF 3.7.3

**Comment by UpmindAI** [comment]
This seems to work normally for me:
https://drive.google.com/file/d/1l92ZXqnbJ63gJbdNjdOvN10w313Smzth/view?usp=sharing

**Comment by aemelyanovff** [comment]
@Alexandre-Lemyre Thanks for reporting the issue, I can reproduce it. The same is true even if you just display the value of the dropdown in a text widget on the main page.

**Comment by aemelyanovff** [comment]
You need to check "Update Page on Changes" when adding the component to your page, then it'll work.

![Screenshot 2023-03-01 at 7 56 10 PM](https://user-images.githubusercontent.com/92294640/222303325-7e788dda-bdf3-416b-86df-de89c8989b4d.png)

**Comment by Alexandre-Lemyre** [comment]
You are correct, it does work!

However, I think I found an actual bug related to conditional visibility based on the answer to a dropdown component. I just reported it on GitHub.

Thank you for your help,
Have a nice day.
