### ISSUE TITLE
FlutterFlow restarts when I click on "create new branch" menu

### ISSUE THREAD

**Issue by mikaelmorvan** [FlutterFlow/flutterflow-issues#5133]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi,

I'm using the Mac Flutterflow app to manage my projects.
With the today's version of Flutterflow, when I click on the "Create New Branch" menu, the app crashes and restart.
I can't see the branch history if the branching window of the FlutterFlow app.

When I try the exact same project on the web version of FlutterFlow, everything works smoothly. 

### Expected Behavior

I must be able to manage my branch like the previous versions.

### Steps to Reproduce

1. Open the project called ribin-player
2. Click the button called "branching"
3. Click the button to display the branch menu
4. Click the button called "Create New Branch"

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohsrlw49On7xH1rr+LPlahSQ4Qno7bIErm8pBZywgfZzzBLN/fPfQPxNoOcilTWNEeGCmp14ywez8i+z1C/A3HAWafLU/yJBMEBaUXnuXVZ+TF7qNPHNBFp9MC2qGyqTYgyRAWfRhR3ss62WpfequcDTXJ5T7IlQ8Sq/LZO4=

### Visual documentation

![Capture d’écran 2024-12-18 à 10 41 04](https://github.com/user-attachments/assets/a691b6f6-ee2c-4c9b-a537-7a012fd6d91e)
[Flutterflow restart bug.txt](https://github.com/user-attachments/files/18178250/Flutterflow.restart.bug.txt)

### Environment

```markdown
FF: Version 5.0.18 (5.0.18)
Apple M1 Max
MacOs
```

**Comment by paulperez-dev** [comment]
Hi @mikaelmorvan,

I was unable to reproduce this behavior on my end. If you’re using the latest version, as shown in the attachment, could you please try reinstalling the app to see if that resolves the issue? Let me know how it goes!

**Comment by mikaelmorvan** [comment]
Hi,

The problem only occurs with the project called Ribin-Player
On other projects, I don't have the problem

Mikaël

**Comment by rzambroni** [comment]
Hi Mikaël,

Thank you for the clarification. Since the issue seems specific to that project, the best approach would be to contact our support team directly. They have the necessary tools to investigate and resolve the issue more effectively.

You can reach them via email at **support@flutterflow.io** or through the chat feature inside the web app.

Thank you for your understanding.

**Comment by mikaelmorvan** [comment]
Ok, thanks for your help
I close the issue
