### ISSUE TITLE
CMS does not show the correct data of prod/dev environment from different firebase projects

### ISSUE THREAD

**Issue by KaRaOkE18** [FlutterFlow/flutterflow-issues#5134]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I switch the ennvironments (prod / dev) with each having its own firebase project, the data in firebase content manager view of flutterflow always shows prod data.

### Expected Behavior

It should dispaly data respective to selected env.

### Steps to Reproduce

1. Set up prod project with firebase
2. Set up dev project with firebase
3. Add data to prod 
4. Add other data to dev
5. Switch envs
6. Look at CMS data
7. You will always see prod data

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klfHl8ZN1mMdY0LXxbfpWmiQXHG1+TL07ttYbZxUjIuPtBJh+P+PBakluQtenYFNhHE3+uGIzwN6MkuzpNMJfKSWafrZByZZQQxbjc3q8RZSrCqiNOH8nL9lTJnKl4ZiR3xVBBNBtcUI822bzGOqWTjDtJ5+/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-12-18 at 13 09 40](https://github.com/user-attachments/assets/7c1b8332-fcb3-4a8d-8fac-41a88f6b019d)

### Environment

```markdown
- FlutterFlow version: most recent
- Platform: WEB, MacOS Desktop, Also Windows): 
- Browser name and version: Chrome 130.0.6723.117
- Operating system and version affected: MacOS, Windows 10
```

### Additional Information

It does not allow to work with dev environment!

**Comment by Alezanello** [comment]
Hello!

Thank you for sharing your concern. I tried to replicate the issue, but it seems to show me the correct information from the selected environment in the Environments Menu. Would it be possible for you to record the steps you followed? This will help me ensure I’m not missing anything in reproducing the issue.

Looking forward to your response!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
