### ISSUE TITLE
Column content disappears because of dynamic Markdown

### ISSUE THREAD

**Issue by developers-mylermedia** [FlutterFlow/flutterflow-issues#5135]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Entire column including a markdown widget with dynamic text is not shown in page

### Expected Behavior

Entire column including a markdown widget with dynamic text is shown in page

### Steps to Reproduce

1. Create a page, with a pageState variable markdownString  of type String, and pass on a long string (I used https://loremipsum.io/generator?n=10&t=p)
2. Add a pageView
3. on the first pageView page, add a scrollable column, with a title "Text Page" add Text Widget with text markdownString
4. on the second pageView page, add a scrollable column, with a title "Markdown Page" add Markdown Widget with text markdownString

Build the app, page 1 works as expected, page 2's content is gone.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i/Lqw41god9G0M+Mbfpsmj45Jn02auca0NZ7aCosCJzwBIgcf/fOYkRDQsO5d2NAeVqWmWoW0tLMidnfDMIBGwiVfIhNzLhIZzniTk2VMKbQFJWvdkdAAppTfGmO0buzgxB/PtFtZXgg62GmJu/LZAnbHZTJO24wD6/LZO4=

### Visual documentation

![IMG_0146](https://github.com/user-attachments/assets/afd4487f-469c-4cfe-a8a4-2592541bd5db)
![IMG_0147](https://github.com/user-attachments/assets/e5a4e896-b35f-47cb-a2f4-3dc26ee7accf)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: iOS
- Browser name and version: 
- Operating system and version affected: 18.0
```

### Additional Information

It's very importent to render application content from external sources (json) as multi line text needs to be provided in markdown syntax

**Comment by Alezanello** [comment]
Hello!

Thank you so much for creating a new project with all the necessary components—it made testing much easier. I’ve identified that the issue isn’t with the Markdown itself but rather with the **Markdown widget when the Expanded property is enabled**. This causes the app to freeze before the Markdown text is rendered.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d7e0f7ee-a098-4a31-909f-87bbb9538c9a/ad70b393-b985-433d-9ded-18fb8dfd2ec9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kN2UwZjdlZS1hMDk4LTRhMzEtOTA5Zi04N2JiYjk1MzhjOWEvYWQ3MGIzOTMtYjk4NS00MzNkLTlkZWQtMThmYjhkZmQyZWM5IiwiaWF0IjoxNzM0NjMxODk5LCJleHAiOjMzMzA1MTkxODk5fQ.FBKy5nmKfGZDtylh8e8kGENOMk9XpFxu4dzQ9DT59Eg " alt="image.png" width="1918" data-linear-height="855" />

To resolve this issue, you can simply remove the Expanded property and set it to **Default**. This should allow the app to compile and run correctly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6d94738-aa1b-44f3-93e5-d33d9e37ad80/fc181108-1f07-4be5-bae1-a4746ced1b47?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNmQ5NDczOC1hYTFiLTQ0ZjMtOTNlNS1kMzNkOWUzN2FkODAvZmMxODExMDgtMWYwNy00YmU1LWJhZTEtYTQ3NDZjZWQxYjQ3IiwiaWF0IjoxNzM0NjMxODk5LCJleHAiOjMzMzA1MTkxODk5fQ.1_U7bkVsspDgUetLiL_bsD2UYeVnEdhwdX8zWKp-CpE " alt="image.png" width="1049" data-linear-height="791" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/effb15e4-d739-428d-98b4-d1c33c05604d/940b505a-01a1-45b0-bb3b-b8278e9fed88?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZmZiMTVlNC1kNzM5LTQyOGQtOThiNC1kMWMzM2MwNTYwNGQvOTQwYjUwNWEtMDFhMS00NWIwLWJiM2ItYjgyNzhlOWZlZDg4IiwiaWF0IjoxNzM0NjMxODk5LCJleHAiOjMzMzA1MTkxODk5fQ.ysKqAO15TlZ3uGR180IsBp0Tgca9mUfjYc4YpCYJaaU " alt="image.png" width="1918" data-linear-height="898" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
