### ISSUE TITLE
Impossible to dismiss bottom sheet with documentReference or Document type

### ISSUE THREAD

**Issue by B0YTR** [FlutterFlow/flutterflow-issues#5136]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,
I am posting this after few replies on the product update news on the community forum. I think no one check the replies.
I had to stop my project development...
As the title says it is impossible to dismiss a bottom sheet with a document reference or just a document.
You cannot choose the type. It happened after the 11th december update.
This happens on web and native app.

![image](https://github.com/user-attachments/assets/968aabfb-d246-43bb-b65a-d2616719afd1)

### Expected Behavior

I should be able to choose a document reference.

### Steps to Reproduce

Create a component.
Create a page. Add a button that opens the component.
After closing the component make it return a document or a document reference.
Assign it to a local state variable.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z8rlx412pbxE+KX5bcBr/SY5JlN7bZIOldZBaCsofePrOpkAf8/7UFtUOc+mT1Z2OmGkrDoX/MqKjtnTGvI6Pk6Wf4Rn+LpubzyVfFKQM5ebPpS3b3QkP/1PBUuMyrWRhyJ5HMhvc11g1E2UP+mQbC7rJrLJPEYkDuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/420f6875-f828-4b20-a73e-2e9208785e7a)
![image](https://github.com/user-attachments/assets/ce68d5be-a70e-46c6-b306-11590595cba5)
![image](https://github.com/user-attachments/assets/0361d234-f2cd-4d87-bc66-7e88aabc3ba9)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.15+ released December 17, 2024
Flutter version is 3.24.2
- Platform: Windows
- Browser name and version: Flutterflow app
- Operating system and version affected: windows 11 home Version	10.0.22631 Build 22631
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that it’s a known problem, and the team has already prepared a fix that will be deployed soon!

For reference, here is the original issue: [#5109](https://github.com/FlutterFlow/flutterflow-issues/issues/5109).

I’ll go ahead and close this one as a duplicate but will link it internally to ensure it’s tracked properly. Thank you for your understanding!
