### ISSUE TITLE
Image not shown when passed through properties

### ISSUE THREAD

**Issue by developers-mylermedia** [FlutterFlow/flutterflow-issues#5137]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

image shows: invalid argument(s): No host specified in URI file: ///

### Expected Behavior

image should be visible

### Steps to Reproduce

1. Create a page
2. add a column with two image widgets
3. for the first image: chose network image and path: https://picsum.photos/seed/127/600
4. add a local page state var: imageUrl with the same path. 
5. set the imageURL as the network image path for the second image.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i/Lqw41god9G0M+Mbfpsmj45Jn02auca0NZ7aDcqGOv2BOwQaePRXBdVOeKoYGw2KEWKoF8Gw6HThobPUvUnOQ6Ab6JCyc9AWAz/ZH6/aouYPaqvPXQmONNWBXac0pmzuhFvAPZedXA93DqAAeiUZAzaHZP6Zwh9f6PHaOI=

### Visual documentation

example of the issue:

![IMG_0148](https://github.com/user-attachments/assets/72fa3ce4-2fcf-410b-88a3-397cf6dd9bb5)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: iOS
- Browser name and version:
- Operating system and version affected: 18.0
```

### Additional Information

This is needed to view details of a list item on a separate page

**Comment by developers-mylermedia** [comment]
I am experiencing the same issue with the PdfViewer Widget when passing the network URL through navigation properties.

**Comment by Alezanello** [comment]
Hello!

Quick question—does this error occur only in **Test Mode**, or do you also experience it in **Run Mode** or when the app is published? Do you see the image displayed correctly in those cases?

Looking forward to your insights!

**Comment by developers-mylermedia** [comment]
@Alezanello Hi, I have some additional findings:
The project which I created to showcase the problem and mentioned above seems to work now for some reason, however I have another project in which the problem still occurs. 

Bug report code: 
IT40iv+Aw5dPnd9B4pDIQO1WlhYUNm4mXOQ3tsF7aDcqGOv2BOwQacj7dlhuXeLjdGxlKEWLnjo1+tWPj/z9FvAoGwqVR75H+pBAWw/wLWW/aouYPaqvPXQmONNWBXac0pmzuhFvAPZedXA93DqAAeiUZAzaHZP6Zwh9f6PHaOI=

In test mode, I get the error mentioned above. In Run Mode, the image keeps its size but is invisible / nothing is shown inside the frame.

When I copy all individual parts surrounding this issue to a new project, everything worked as expected in this new project and I see the image.

When I duplicate the project, everything also works as expected in this new project and I see the image.

I tried restarting FlutterFlow, removing the app from my device etc.

**Comment by Alezanello** [comment]
In this case, I’m still unable to replicate the issue in a new project, which suggests it might be specific to your project. I recommend reaching out to FlutterFlow support via the in-app chat or by emailing **support@flutterflow.io** for further assistance with this.

Please note that this GitHub Issue Tracker is intended for issues that can be reproduced in a new blank project.

Thank you for your patience, and I’m sorry this issue has been unresolved for so long. Wishing you happy holidays!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
