### ISSUE TITLE
Size of the image/container widget doesnt stay and returns tu full wide of collum

### ISSUE THREAD

**Issue by stephansvec** [FlutterFlow/flutterflow-issues#5138]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/fc2b8bc7-5dba-4f46-b0f8-e3d1892c0c4d)

### Expected Behavior

![image](https://github.com/user-attachments/assets/7102d2ef-7eb9-4d0f-b2d8-76a26886a637)

### Steps to Reproduce

1. Create a new page
2. add image or container widget
3. Set up size of the widget
4. wait a few seconds and the selected size resets to predetermined 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMjc35N1m8hE0anUKu54mWMwGUALa+dI0tZ+TQ0jF5D4Pe0ld+PCRFtvXu6zaHNhfFmbsFwdw97tkdn1KvkoYDatGKpR1KhMcBPPY3O6bpSQDKqgTnZtEZ1UN365y57YvRR+VddhZXAs3F2YA+qyQT6Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/fc2b8bc7-5dba-4f46-b0f8-e3d1892c0c4d)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released December 16, 2024
Flutter version is 3.24.2 
- Platform: Web
- Browser name and version:Chrome 131.0.6778.140
- Operating system and version affected: Windows
```

**Comment by JonathanG1702** [comment]
I’m experiencing a similar issue with containers, images, icons, and basically any element where the width can be set. I’m working on responsive layouts, so I use screen width and height. When I set the component width as a percentage, it breaks, just like in your case. However, when I remove the percentage and manually set the width, it displays correctly. I believe the issue with percentage-based width started after the latest update.

First photo with percentage-based width, second with manual size.
![Captura de pantalla 2024-12-18 163143](https://github.com/user-attachments/assets/0c6b410a-ad5d-4e19-a021-c1e1a5286fc5)
![Captura de pantalla 2024-12-18 163223](https://github.com/user-attachments/assets/e491b155-8f51-4962-b9ac-4f6e534f68a1)

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this behavior on my end. If you’re still experiencing the issue, could you please share a recorded video showing the exact behavior you’re encountering? This will help me better understand and assist you.

Looking forward to your response!

**Comment by JonathanG1702** [comment]
> Hello!
> 
> I wasn’t able to replicate this behavior on my end. If you’re still experiencing the issue, could you please share a recorded video showing the exact behavior you’re encountering? This will help me better understand and assist you.
> 
> Looking forward to your response!

Sorry fo the delay. In the video i hope you will see what i meant with width problem that affect to row or colums
https://youtu.be/ayypBYlOYZI

**Comment by Alezanello** [comment]
In this case, since the width is being set dynamically based on a variable tied to the screen resolution, it may not display correctly in the UI Builder.

To address this, you can set a **Default Variable Value** and a **UI Builder Value** at the bottom of the settings. This will allow you to preview how the UI might appear with different values.

**Comment by JonathanG1702** [comment]
How is posible that one week ago everything was fine and after lastest updates my project "bloke" like that...i will open a bug in a few days because if i didnt make changes how is posible these behaviour?

**Comment by Alezanello** [comment]
The project isn’t broken; it’s just how the UI Builder represents the view. As mentioned earlier, when you set the width to a variable, the UI Builder cannot display it correctly because it doesn’t know the value of that variable until the project is compiled.

To address this, you can use the **UI Builder Value** setting to preview the size correctly in the Builder. This allows you to simulate how it will look when tested.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
