### ISSUE TITLE
Build Failed on run mode just now working for web version app version is ok: 'canvasSize' is already declared in this scope

### ISSUE THREAD

**Issue by waminos** [FlutterFlow/flutterflow-issues#514]
![image](https://user-images.githubusercontent.com/18538948/220387133-6a676ffe-dedf-466a-80d2-3f3400fa8c57.png)

**Comment by waminos** [comment]
The error is linked with publishing web version of the app. No error on mobile app version.

**Comment by hariprasadms** [comment]
Hi @waminos - I hope this issue is fixed in latest FF updates. We are closing this issue. Let us know if issue persists again we can re-open the issue and start investigating.
