### ISSUE TITLE
Flutter Flow App Store Deployment Issue "No valid code signing certificates were found"

### ISSUE THREAD

**Issue by AKRehmanKhan** [FlutterFlow/flutterflow-issues#5140]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

HI I use to deploy my app to Test Flight from Github but this morning after the recent update I am unable to deploy my app to app store from Github. It goes till building but fails in publishing phase.

### Expected Behavior

App should be deployed to testflight from github repo

### Steps to Reproduce

Connect your project with github
Add required things for appstore deployment
Add branch name to github in deployment Source|
Hit deploy

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXic/q24x2rtxE7qnqcMZsvGAwGUwbUOc7j9VEGAsjCeKrBJoTO+DCQE1CYuqHeHxIfWCGrD8F/6GKiYfXEMAnAxSaGYRi/qgIUxDjXlKXMZS0OpO8SEd8RPpYGUCn4aWJhRBRIsFucloe3WeAFeu+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

Error Message:
Failed Step: Flutter build ipa and automatic versioning

Found build number 30 from TestFlight version 1.0.0

Archiving com.everlongtech.outlet...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
ios/Runner/AppDelegate.swift uses the deprecated @UIApplicationMain attribute, updating.
════════════════════════════════════════════════════════════════════════════════
No valid code signing certificates were found
You can connect to your Apple Developer account by signing in with your Apple ID
in Xcode and create an iOS Development Certificate as well as a Provisioning 
Profile for your project by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again
  5- Trust your newly created Development Certificate on your iOS device
     via Settings > General > Device Management > [your new certificate] > Trust

For more information, please visit:
  https://developer.apple.com/library/content/documentation/IDEs/Conceptual/
  AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
No development certificates available to code sign app for device deployment

Build failed :|
Step 10 script `Flutter build ipa and automatic versioning` exited with status code 1

![image](https://github.com/user-attachments/assets/e03c4dbc-7b1c-47f3-9117-cd2a9d522fd0)

### Environment

```markdown
- FlutterFlow v5.0.0+ released December 16, 2024: 
- IOS:
- Browser name and version:
- Windows:
```

**Comment by agodoy75** [comment]
I am having the same issue. Deployment to Apple has not been working all day today 12/18/2024. I get the same error.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. Unfortunately, I couldn’t replicate the problem on my side, and since we don’t have access to your **Mobile Deployment** section, we’re unable to verify if the credentials are set up correctly.

To resolve this, please try removing all your mobile deployment certificates (e.g., App ID and related details) and setting them up again. If the issue persists, feel free to reach out to our support team via the in-app chat or at **support@flutterflow.io** for further assistance.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
