### ISSUE TITLE
TextField in component not handling well initial values from argument

### ISSUE THREAD

**Issue by spanishpy** [FlutterFlow/flutterflow-issues#5142]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a data table that shows data from a component state variable and in each row I have a component to show a price amount. The component only has one widget, a TextField to display the amount. The component takes an argument (initialValue).

The problem I'm having is that the initial value isn't set correctly, it always shows the value of the first element added to the component state variable. The most confusing part is that the textfield label shows the correct value.

### Expected Behavior

I would expect the text field in the price component to show the correct initial value, as does the label.

### Steps to Reproduce

1. Create a nested data structure with a price object inside. E.g:
```
{
    "name": String,
    "price: {
        "amount": String
    }
}
```

2. Create a page state variable with a list of these objects.
3. Add a textfield for the name, another textfield for the price and a button to append the inputed information to the page state variable.
4. Add a datatable to show the entries in the page state variable. The rows show (at least) the price by using a TextField (which you are forced to convert into a component).
5. Convert the TextField into a component and add an argument to pass each row's price amount.
6. Use the argument in the initial value and also the label inside the component.
7. Add elements to the page state variable and see how the price shown in the price component is always the same, but not the label.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i8rl5YpIrtxE7ZPuY8JV+TwWQkc7aJIK1u5uZAI8J5DaPOxzP/TBaldWUs+0Y1Z2fWCkrz80p8nemvDtD8cFMk+aY6pizahbFjrJXkWlabWaPZO0S25/AtxNG36/38CJnBMnFPNsdUIs13GYfefIEzbUHZexC1Y3HfyhOZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1197" alt="Captura de pantalla 2024-12-18 a las 20 10 27" src="https://github.com/user-attachments/assets/33b8665f-ec65-4127-830d-5f62b04e53ad" />

### Environment

```markdown
- FlutterFlow version: 5.0.18
- Platform: Web
- Browser name and version:
- Operating system and version affected: Mac Sonoma 14.4.1
```

**Comment by Alezanello** [comment]
Hello!

Let’s try a few steps to troubleshoot this issue. Although I wasn’t able to replicate it on my end, based on the image you provided, it seems like the issue does exist.

1. Try assigning a unique key to the components, such as an index in the list or any value that differentiates them. This might help resolve the issue.
2. If that doesn’t work, could you attempt to replicate the issue in a new blank project with only the necessary components? This will help narrow down the cause.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3c8ae604-5524-41e6-ac82-d8eb1e239ddc/442f34e4-5d2f-42b2-a487-14112d3ecab1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYzhhZTYwNC01NTI0LTQxZTYtYWM4Mi1kOGViMWUyMzlkZGMvNDQyZjM0ZTQtNWQyZi00MmIyLWE0ODctMTQxMTJkM2VjYWIxIiwiaWF0IjoxNzM0NjMzODE2LCJleHAiOjMzMzA1MTkzODE2fQ.sxZRNeOF6ep7zi7ElqHFyfUiYIKdtjzYnJpGtt1m1MM " alt="image.png" width="967" data-linear-height="427" />

**Comment by spanishpy** [comment]
Hi @Alezanello,

Sorry for the delay in getting back to you. I narrowed it down and the issue has to do with how a list is updated. You can see it in this project: https://app.flutterflow.io/project/qa-3274-9uwih0?tab=widgetTree&page=HomePage

Essentially, if you use the "Add to list" in the update state action and pass a new instance it works fine. If you use instead the "Set value" option and use function to append that element to the list and return a new list it doesn't work and you can see the behaviour I was describing.

**Comment by Alezanello** [comment]
Here’s how list updates work in FlutterFlow:<br>[Managing AppStateList](https://docs.flutterflow.io/generated-code/ff-app-state/#managing-appstatelist)

If you use **SET Value**, it will overwrite the entire list with the new value you provide. For example, if you’re trying to add more items to an existing list, you should use the **Add to List** action instead.

To update a specific item in the list, you’ll need to update the item at the desired index. This is explained in more detail in the documentation linked above.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
