### ISSUE TITLE
Bottom Sheet Dismiss not showing collections if choosing firebase document as return data

### ISSUE THREAD

**Issue by VismoDoc** [FlutterFlow/flutterflow-issues#5143]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Create a component
2. Add action block “Dismiss bottom sheet”
3. Enable “Has value”
4. Select data type “Document”
5. When selecting collections it show random strings and if you select one it won’t save and you can’t select the document to return

### Expected Behavior

1. Create a component
2. Add action block “Dismiss bottom sheet”
3. Enable “Has value”
4. Select data type “Document”
5. You can select the Firebase collection

### Steps to Reproduce

1. Create a component
2. Add action block “Dismiss bottom sheet”
3. Enable “Has value”
4. Select data type “Document”
5. When selecting collections it show random strings and if you select one it won’t save and you can’t select the document to return

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lefq3ItPj7xZ1ar2b/owgjg5JmIiUOcr1MF7aCgoIYyuOpl/evWkdlZBZ9zhYAlqJ0Smmmo03NqMivHxDvYqPkiYR6J9+KtqEQ/wJU+he5OBCpDhYXdPINJTfmXF4LSrsCMnWfRZciE42DuMf+i9YAvBJLrsImdISq/LZO4=

### Visual documentation

![Screenshot 2024-12-18 alle 13 21 23](https://github.com/user-attachments/assets/a89dc029-d728-4b55-b224-0a1ff453d8e1)

### Environment

```markdown
- FlutterFlow version: 5.0.18
- Platform: MacOS 15.2
- Browser name and version: Safari, Chrome, MacOS APP
- Operating system and version affected: MacOS 15.2
```

### Additional Information

If you already have one, you’ll see the collection with it’s id and not it's name (I suppose it’s the id)

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that it’s a known problem, and the team has already prepared a fix that will be deployed soon!

For reference, here is the original issue: [#5109](https://github.com/FlutterFlow/flutterflow-issues/issues/5109).

I’ll go ahead and close this one as a duplicate but will link it internally to ensure it’s tracked properly. Thank you for your understanding!
