### ISSUE TITLE
Wrong list of documents type when dismissing a bottom sheet with a value

### ISSUE THREAD

**Issue by andresgj** [FlutterFlow/flutterflow-issues#5146]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The list of document types when creating a dismissing action for a bottom sheet with a value of type Document or Document Reference is incorrectly listed and is not possible to return the value effectively.

<img width="292" alt="Screenshot 2024-12-19 at 6 23 11 PM" src="https://github.com/user-attachments/assets/2015f632-9d37-4d34-8687-852e28bcd03b" />

### Expected Behavior

The list should be populated with the actual list of collections, the same as when creating a page or component parameter of type Document or Document Reference.

<img width="304" alt="Screenshot 2024-12-19 at 6 22 38 PM" src="https://github.com/user-attachments/assets/78fd5eb5-b9fd-4cd1-a89f-e4c091003de1" />

### Steps to Reproduce

1. Create a new project that uses Firebase
2. Create collections
3. Create a component
4. Create a button
5. Set an action of dismiss the bottom sheet to the created button
6. Toggle on the option "Has Value" and select Document Reference for Data type.
7. Check out the wrong collection list, making the option not usable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHq049Osdte7q6ILMFKijwRQlscTOURiO0bFDsdF4iuPOxzaeDBSE1oZPWoYXxhKEWGgToBpNLukez2UMEDCzqqRYA7ybp+bwuXIUK/aouYCs2KZnAmI9xUGUyC0KW3hxBSVLFscmQ1wzmIe+zLSgvqK4f6Zwh9f6PHaOI=

### Visual documentation

<img width="292" alt="Screenshot 2024-12-19 at 6 23 11 PM" src="https://github.com/user-attachments/assets/c2bed31f-5831-42c3-b1eb-26a696322a80" />

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: Web and MacOS Desktop
- Browser name and version: Chrome 131.0.6778.139 (Official Build) (x86_64)
- Operating system and version affected: macOS Sonoma 14.0
```

### Additional Information

I am implementing an App functionality before a release scheduled for the next day

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that it’s a known problem, and the team has already prepared a fix that will be deployed soon!

For reference, here is the original issue: [#5109](https://github.com/FlutterFlow/flutterflow-issues/issues/5109).

I’ll go ahead and close this one as a duplicate but will link it internally to ensure it’s tracked properly. Thank you for your understanding!
