### ISSUE TITLE
Not able to run test mode 

### ISSUE THREAD

**Issue by GillbertWong** [FlutterFlow/flutterflow-issues#5147]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

almost every few days will appear once 

### Expected Behavior

it should end or refresh when test mode expired

### Steps to Reproduce

Open Project 
Start Test Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/vanzo-w-m-s-e1sdud?tab=widgetTree&page=A2StockTake

### Visual documentation

![image](https://github.com/user-attachments/assets/a3f7906c-02f0-4094-b69d-d5a6c1013f07)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi Gilbert,

Apologies for the inconvenience. This is indeed a known issue that the team is aware of, and they’re actively working on a fix.

In the meantime, if you manually "End Session" using the button shown in the screenshot you shared and then start a new session, you should be able to continue testing without further issues.

For updates, you can refer to the [original ticke](https://github.com/FlutterFlow/flutterflow-issues/issues/5078)t.

Thank you for your patience and understanding!
