### ISSUE TITLE
numbers input for all sliders sorts input numbers backwards

### ISSUE THREAD

**Issue by thomasallnice** [FlutterFlow/flutterflow-issues#5148]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when setting the value for a slider (e.g. snackbar life time) the numbers get sorted backwards. 1500 appears as 0051

### Expected Behavior

1500 appears as 1500

### Steps to Reproduce

create snackbar, set life time

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

notneeded

### Visual documentation

https://github.com/user-attachments/assets/6fc34253-d4a2-4481-ae9e-9f4d153924c6

### Environment

```markdown
- FlutterFlow version: newest
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @thomasallnice,

This issue has been previously identified, and the team is actively working on a fix. We’ll keep you updated as progress is made. Thank you for your patience and understanding!
