### ISSUE TITLE
Scroll glitch on web app on phone

### ISSUE THREAD

**Issue by Golicraft** [FlutterFlow/flutterflow-issues#5150]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I scroll down on a page it appears a glitchy duplicate of the already existing component. 

### Expected Behavior

It should not do this. 

### Steps to Reproduce

1. Create a new page
2. Enable scroll effect

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9VniERG258Roc0sNobbxAjIoDoPJkUaeD4dkltZMugT1ZbKEWJvEUJpfD8koTQUvBfFwyWGJxDz5ZTFjvjeF6/aoSMDsyOP0Z9ONNVJ0y/0qerpx1ANupqR0YfwGCMHuzKFx7vK7X6Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/1f4ae2a3-31ac-406a-ab30-2d90adb6092b

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released December 17, 2024
Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome, Safari
```

### Additional Information

I've tested my app on the web with this "version" multiple times. This hasn't happen before and I believe it's a newer version of FlutterFlow that do this. 

I have no additional code/animations/inputs on the page (Tested without nothing)
I've cleared cache
I've tried with a blank project

Only happens on phone. Tried on my computer, couldn't replicate the issue on the web app there. 

This took me time, and I have been annoyed by this for some time now. Thought it was too obvious so I didn't report it but hey, to my surprise it hasn't been fixed/neither or reported by anybody else so I'm wondering what is going on. 

Thank you.

**Comment by Alezanello** [comment]
First off, wow—this is a rare one! On another note, are you deploying using Canvas Kit? Also, could you let me know which version of iOS your phone is running?

**Comment by Golicraft** [comment]
Hello, yeah.. No, I'm not using Canvas Kit. I'm on Iphone 13 with IOS version 18.1.1

**Comment by Alezanello** [comment]
There is a known issue with scrolling on iOS 18.1+ that we are currently working on resolving. The fix for that issue should address your problem as well.

You can track the progress here: [Issue #4907](https://github.com/FlutterFlow/flutterflow-issues/issues/4907).

I’ll close this issue as a duplicate, and all further updates will be provided on the main issue.

Thank you for your understanding, and happy holidays!

**Comment by Golicraft** [comment]
For me updating to version 3.27.1 does not work with this issue which i created a ticket on (but it got closed because of "duplicate"). 

I have updated to 3.27.1, tested with a completly new phone on ios 18.1/2 which has NEVER accessed the app. 
![IMG_3673](https://github.com/user-attachments/assets/81a2ed14-f76c-4351-b4a4-1cd470c340bc)

**Comment by Golicraft** [comment]
@Alezanello Hello. Please open and review my issue again. This is not fixed. Tested on a new device today (friend of mine) Same issue there.

**Comment by Golicraft** [comment]
![Skjermbilde 2025-01-14 152733](https://github.com/user-attachments/assets/89d203cb-c3d8-45ff-bd8c-132af1703b01)
![Skjermbilde 2025-01-14 152801](https://github.com/user-attachments/assets/3a474040-869d-4fdd-9136-d94736050caf)
