### ISSUE TITLE
Switch initial value not affected by On Load actions... bug or counterintuitive?

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5151]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.tella.tv/video/troubleshooting-switches-3lbe

Slightly longer video as I tested figuring things out a bit on the fly so you get some "user confusion" visual.

Let me know if this was helpful AND IF IT WASN"T! If it was annoying then please tell me. I won't be insulted. I want these vids to help you and FF become amazing, not annoy the crap out of you :)

But basically it seems like the issue with switches is that they get "built" before on load actions happen and are not "bound" to a value, in this case in App State. 

This might be expected based on "Switch initial value" but is somewhat counterintuitive. 

### Expected Behavior

It would be super nice to have switches bound to app state and page state variables. :D

### Steps to Reproduce

Crate page
Create app state bool
Create on load action to change the app state bool
Not reflected in toggle

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tlsjf5ZdOmMBE7pDAKMdKnjwWHFA8a+YeltZHdxYaNuv1PLAuPePsZXFJXMu4d2xUJGH8sGAI7tLWkeDAGsErBwmIQ75D/pZTEQ3JTjmtWpCzPZO0ZUdCBe1bGlyx5LCOiglRKu1qcUIB22GqH9+/EwXBNpD6O0QjJf+LOp/LpEqBK3vKFDh2tmNecCfn

### Visual documentation

https://www.tella.tv/video/troubleshooting-switches-3lbe

### Environment

```markdown
FlutterFlow v5.0.18 released December 17, 2024
Flutter version is 3.24.2
```

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturns,

It looks like the issue might be that the switch is reading the value before it’s set. I believe updating the switch after the value is set should resolve the problem.

**Comment by chuggmuffinReturns** [comment]
That does work... however it is a bit counterintuitive, especially considering the toggle icon functionality being bound to the widget and not even working with the toggle trigger.

Not a big deal as I can work with this but maybe add this into a feature request cue?

**Comment by paulperez-dev** [comment]
This is a great idea, to bound the switch to a variable. It would be fantastic if you could submit this Feature Request using the app’s dedicated feature. That’s the best way to ensure they reach the right team for consideration in the roadmap since this tracker is primarily for bugs.<br><br>Thanks for your understanding and contribution!
