### ISSUE TITLE
Auto focus still on even after turning it off

### ISSUE THREAD

**Issue by rogeraleite** [FlutterFlow/flutterflow-issues#5154]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In an Action Flow Editor I have a "Set Form Field" setting a TextField. There, I have the option "Focus Field When Set" off, however it is still putting focus (opening the keyboard) when I start the page.

### Expected Behavior

I expect that no focus happens in the text when the option "Focus Field When Set" off. 

### Steps to Reproduce

1. Create a new page with text field
2. "On Initialization" of the page, set the field to something and turn the option "Focus Field When Set" off. 
3. Check the behavior of focusing automatic on the text field still happening. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l8nf34VIsdtK1aqAbcJKmjk5JUh7bJI3k+5raCsvCIyqOpscf/fBfklUcMTmT1VIJ02grH4X/MnHjeLPJ/E7GyWdGZRlyqVyTg7yIHOWRaaJDa63b0RSEeJWCkyd5sOZmiVCPu52c3w1w3GQAeevb3PbQe/vOEUjLuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/c2f79e55-5db8-48b2-a205-7649b7746df7)

### Environment

```markdown
- FlutterFlow version: I could not find this info easily in FF, but today is 20.12.2024
- Platform: iOS
- Browser name and version: none
- Operating system and version affected: iOS
```

**Comment by paulperez-dev** [comment]
Hi @rogeraleite,

I wasn’t able to replicate the issue. The “Set Form Field” action is working as expected. I tested the app on a real iOS device, and the keyboard did not appear. Could you please verify if the focus is being set by another action? 

[https://app.flutterflow.io/project/qa-3334-uow3qv](https://app.flutterflow.io/project/qa-3334-uow3qv)

**Comment by rogeraleite** [comment]
Please, close this ticket. I kept changing and I believe the compiles file from FF changed and it is now working fine. It was not before.

**Comment by paulperez-dev** [comment]
Ok, thanks for the confirmation!
