### ISSUE TITLE
Toggles can't toggle (plus a weird formatting thing)

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5158]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.tella.tv/video/toggles-cant-toggle-1uvh

the action "toggle value" on a boolean doesn't toggle in a toggle icon

you CAN use the toggle action if you set a conditional first which is kinda funny :)

### Expected Behavior

toggles toggle

### Steps to Reproduce

set toggle action on a toggle

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40sOX126xOscRJ15PqWuxGgmEsHGIjRLgJkNVraCosfZT2BLMcec/RVERoTsu+Y1FpPmaWkWoW06GPkeHhEu4oGASaG706z8x2ajqVd3OXV5CaFJWvPGhAHehmG3alyrbYmhN+KbZqR1IZwF2EAvOXEwTvH5CxDHo0Da/LZO4=

### Visual documentation

https://www.tella.tv/video/toggles-cant-toggle-1uvh

### Environment

```markdown
mac desktop latest
```

**Comment by Alezanello** [comment]
Hello!!<br><br>Please keep in mind that FlutterFlow automatically toggles the icon for you, so there’s no need to add any additional actions manually.

To help you further, I’ve created a public project showcasing how I achieved this functionality: [View Project](https://app.flutterflow.io/project/qa-2936-op5hp0)..

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/141d29ca-78fa-4834-9c4e-0212a2a959f5/11968be1-9288-4303-8b97-a1dc8a0ba775?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNDFkMjljYS03OGZhLTQ4MzQtOWM0ZS0wMjEyYTJhOTU5ZjUvMTE5NjhiZTEtOTI4OC00MzAzLThiOTctYTFkYzhhMGJhNzc1IiwiaWF0IjoxNzM0NzMwMzM3LCJleHAiOjMzMzA1MjkwMzM3fQ.3DW2K_52wWOPwmHKApgloW361f3tc8ljPbt3lOwcfgc " alt="image.png" width="1150" data-linear-height="157" />

**Comment by chuggmuffinReturns** [comment]
well dont I feel silly.......................

**Comment by Alezanello** [comment]
I’ve been using FlutterFlow for the past two years, and it’s incredible—I only learned about this feature three weeks ago, and it completely blew my mind!

I’ll go ahead and close this issue for now. Wishing you happy holidays!

**Comment by chuggmuffinReturns** [comment]
haha happy holidays to you too!!
