### ISSUE TITLE
run mode negative value

### ISSUE THREAD

**Issue by ameer1002** [FlutterFlow/flutterflow-issues#5161]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

run mode negative value

### Expected Behavior

it should end

### Steps to Reproduce

![Screenshot 2024-12-21 123224](https://github.com/user-attachments/assets/df2bc19e-3e55-4748-ad80-18c95ed661ba)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no code

### Visual documentation

![Screenshot 2024-12-21 123224](https://github.com/user-attachments/assets/61509ebe-28aa-4e5d-8090-a8eeee6e1ce7)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @ameer1002,

Apologies for the inconvenience. This is indeed a known issue that the team is aware of, and they are activly working on a fix.

In the meantime, if you manually "End Session" using the button shown in the screenshot you shared and then start a new session, you should be able to continue testing without further issues.

For updates, you can refer to the [original ticke](https://github.com/FlutterFlow/flutterflow-issues/issues/5078)t.

Thank you for your patience and understanding!
