### ISSUE TITLE
Conditional Value Return Type “Document” Displays Gibberish Instead of Firestore Documents

### ISSUE THREAD

**Issue by BenjaminMacaulay** [FlutterFlow/flutterflow-issues#5163]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When selecting the return type as “Document” in a conditional value (if-else statement), the options displayed are random gibberish text instead of the actual Fire store documents that are configured in the application.

### Expected Behavior

The options should display the Firestore collections already configured in the project, allowing for selecting a valid Firestore document as the return type. This would enable conditional logic to return different lists of Firestore documents for use in widgets like ListView or Columns.

### Steps to Reproduce

1.	Start from a blank project.
	2.	Add a ListView or Column widget.
	3.	Set the data source to “Generate Child From Variable.”
	4.	Select “Conditional Value (If-Else).”
	5.	Set the return type to “Document.”
	6.	Observe that the displayed options are random gibberish text instead of actual Firestore documents.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Unable to generate bug report code as the project is unresponsive when attempting to select Firestore documents.

<img width="1025" alt="1111" src="https://github.com/user-attachments/assets/5a6a3d15-dded-42d7-8b61-f628a3088b88" />
<img width="888" alt="Screenshot 2024-12-21 at 6 44 49 PM" src="https://github.com/user-attachments/assets/572cd66f-e39f-46bb-9acb-315f778f61e4" />

### Environment

```markdown
•	FlutterFlow Version: 5.0.0 (Released December 17, 2024)
	•	Browser Name and Version: Microsoft Edge (Version not available)
	•	Operating System and Version: Not specified
	•	Platform: FlutterFlow web interface
```

<img width="888" alt="Screenshot 2024-12-21 at 6 44 49 PM" src="https://github.com/user-attachments/assets/b8b8cc03-e6c6-4920-ad0e-2e8a566da793" />

**Comment by paulperez-dev** [comment]
Hi @BenjaminMacaulay,

Thanks for reaching out! This issue has already been reported and is being tracked in **#5109**. Please refer to that ticket for further updates.

I'm closing this as duplicate.
