### ISSUE TITLE
Dismiss Dialog/Bottom Sheet Return Value shows Gibberish Instead of Firestore Documents

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#5164]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a custom component and add a dismiss dialog or dismiss bottom sheet action. Select Document as return type and it will show random rubbish
![image](https://github.com/user-attachments/assets/475d08b4-ee04-4f14-848a-22e7cf2ae8d9)

### Expected Behavior

Show collection name

### Steps to Reproduce

1. Create a custom component
2. Add dismiss dialog or dismiss bottom sheet action
3. Set it has Value of type Document

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkfHq25B2rsRE0LrcY/logSgwFjMMbY0v0u0bFB4dCKmtBJoif/TsQ0NKTt+rf1VUGmKJ8U0dweD4ufOSMPI7GEyWRaZn0JVPFgzJRlO7RpibErqoPHFPO9xNFUyy1p7YhQlDKbFhL0477F+pNa3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/475d08b4-ee04-4f14-848a-22e7cf2ae8d9)

### Environment

```markdown
- FlutterFlow version: 5.0.18
- Platform:Mac
- Browser name and version: Chrome Version 131.0.6778.205 
- Operating system and version affected: All
```

**Comment by paulperez-dev** [comment]
Hi @itsstevenliu,

This issue was already reported and is being tracked here in #5109. Please refer to that issue for further updates.
