### ISSUE TITLE
Cannot select "Action" parameter in Widget builder

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-issues#5167]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Widget builder accept a component. Component can take Action as parameter. However, it is not possible to add "Action" with "Add WidgetBuilder parameter".

### Expected Behavior

I expect the WidgetBuilder to accept same types as components they implement.

### Steps to Reproduce

See above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not relevant

### Visual documentation

<img width="309" alt="Screenshot 2024-12-22 at 19 19 13" src="https://github.com/user-attachments/assets/98c12755-50dd-4856-b502-bfbc8eb57ef5" />

### Environment

```markdown
- FlutterFlow version: 5.0.18
- Platform: Desktop
- Browser name and version: .
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment]
In this case, the widget builder only accepts widgets with data parameters. For actions, you can set them directly on the component you plan to use. Once you've selected the widget from the widget builder, you can then configure the actions for that specific widget or component, as demonstrated in the video.

[Screen-Recording (69).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8644eddf-7c6c-4fc5-80e9-bc4731fcff69/50d2aa75-078e-48f8-b13a-cf8d06a25664?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NjQ0ZWRkZi03YzZjLTRmYzUtODBlOS1iYzQ3MzFmY2ZmNjkvNTBkMmFhNzUtMDc4ZS00OGY4LWIxM2EtY2Y4ZDA2YTI1NjY0IiwiaWF0IjoxNzM0OTg1NTM0LCJleHAiOjMzMzA1NTQ1NTM0fQ.xjgf5wjqxyLoJkhFGaV2O136_hZFuPB1rZoyyvdIJH0)

**Comment by AdrKacz** [comment]
Yes, that's exactly the issue I'm pointing out, thank you for confirming.

Components **do** accepts **actions** as parameters, however Widget Builders **don't**. I understand you can set the action directly **in** the components, but there are a lot of use cases where you need to **pass down** an action.

Your team understood this critical requirement and so made **Actions** an authorized parameter type. Unfortunately, they forgot to enable this type for Widget Builder (_which are surely not really far from Components in your code source_)

Can you point you this oversight to the team please @Alezanello ?

**Comment by Alezanello** [comment]
Fair point, in the documentation I don't see any restriction, going to ask the team if this is intended to know if I tag this issue as a Bug or a Feature/Enhancement request to enable it.<br><br>Thanks for the patience.

**Comment by Alezanello** [comment]
Hello!

The engineering team has clarified that this is considered a Feature Request rather than a bug, as the current behavior—Widget Builders not accepting actions as parameters—is expected.

I will create a Feature Request and link it to this ticket internally for tracking. For now, I’ll go ahead and close this issue, marking it as a Feature Request.
