### ISSUE TITLE
Can not add a library dependency.  Spinner just spins

### ISSUE THREAD

**Issue by davidmabelle** [FlutterFlow/flutterflow-issues#5168]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I converted a project link preview to a library.  When I try to add it as a dependency the spinner just keeps spinning.

### Expected Behavior

I should be able to see a list of libraries I have added and add one as a dependency.

### Steps to Reproduce

1.  Copy link preview project from the marketplace
2.  Convert it into a library
3. See if you can add as a dependency

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

library-link-preview-dfvxvf

### Visual documentation

<img width="1728" alt="Screenshot 2024-12-23 at 10 28 20 AM" src="https://github.com/user-attachments/assets/d1dd158d-7aca-4bfe-a929-7fccd46d8d31" />

### Environment

```markdown
- FlutterFlow version: 
- Platform:osx
- Browser name and version:
- Operating system and version affected:
```

**Comment by davidmabelle** [comment]
I went out for an hour and when I came back it finally worked.

**Comment by paulperez-dev** [comment]
Hi @davidmabelle,

Thanks for the confirmation. Closing this issue for now.
