### ISSUE TITLE
Button ignores left padding of 0

### ISSUE THREAD

**Issue by ch-angelino** [FlutterFlow/flutterflow-issues#517]
## Expected behavior (required)
When left Padding and Icon left Padding is set to 0, the button has no left padding on the device.

## Current behavior (required)
When left Padding and Icon left Padding is set to 0, the button shows no padding in the editor and in test mode on the browser, however it does show padding on Android and iOS devices.

## To Reproduce (required)
1. Create new page
2. Add a Column widget that contains a Button widget
3. Add an icon and text to the button
4. Set button left padding and left icon padding to 0, leave right paddings unset
5. Observe that padding from the button is removed in the editor
6. Download APK and run on Android
7. Observe that padding is present in the button

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")
IT4sl+fl4otPm9ta1aX6dcB7/GI7JVA4U4IOscsZa0kdB4joPLJ/eMj4RE9BcMu/YWlhHFGioEQfzMnIk/ztC/QoH02cfJh+zLpuZjriUTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)
Trying to align a button (start of the icon) with a text field above to match provided designs.

## Screenshots / recordings
Editor:
![Screenshot 2023-02-22 at 9 53 35 am](https://user-images.githubusercontent.com/96222544/220493426-356e5f97-cac5-48ef-a63f-193431b38a41.png)
Real Device:
![Screenshot 2023-02-22 at 9 54 14 am](https://user-images.githubusercontent.com/96222544/220493445-369b9e8f-41e7-4068-a9e4-3818887633d9.png)

## Your environment
* Version of FlutterFlow used: 3.1
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Browser name and version: Google Chrome Version 110.0.5481.100 (Official Build) (arm64)
* Operating system and version (desktop or mobile): MacOS Ventura 13.1

**Comment by wenkaifan0720** [comment]
This will be fixed in our next update. Thank you for raising this issue.
