### ISSUE TITLE
Cannot edit cache queries

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-issues#5170]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I select "Enable query caching" I must set a **name** to the query. However, I can't (1) update this name or (2) delete this name when I stop using it.

### Expected Behavior

I expect to have control over the list of query names I declared.

### Steps to Reproduce

See above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

Not applicable

### Environment

```markdown
- FlutterFlow version: 5.0.18
- Platform: Desktop
- Browser name and version: Not applicable
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment]
Hello!

You're absolutely correct; currently, there is no functionality to change the name or delete it, even with the cache turned on or off.

I’ll pass this along to the team as a feature request. In the meantime, I’ll close this issue to keep the GitHub issue tracker focused solely on bugs. Thank you for your understanding, and feel free to reach out if you have any additional feedback or questions!
