### ISSUE TITLE
Cannot pass a datatype to an action block

### ISSUE THREAD

**Issue by koosdeklerk** [FlutterFlow/flutterflow-issues#5173]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a datatype with several fields, eg. project with fields project_name String, project_number integer.
Create an action block that takes project as a parameter.
On component create a local component variable with type project.
Update component value (project) and set the values.
Call the action block and pass project as parameter.
In action block, all values for the parameter are null.

### Expected Behavior

The values for the variable should be as passed in and not null.

### Steps to Reproduce

1. Create a datatype with several fields, eg. project with fields project_name String, project_number integer.
2. Create an action block that takes project as a parameter.
3. On component create a local component variable with type project.
4. Update component value (project) and set the values.
5. Call the action block and pass project as parameter.
6. In action block, all values for the parameter are null.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8r13ItIseVA1pDbbcJagSQ4OXolbZEzlcpOGDsdF4iuPOxzaeD8XBduUsPmTWNbKEWIuFsC0s2Nj9/DL/BeOTSVUapg+Kt+VQLKQXK/aoSkC86WT3dRGeJmGGKh356zrghCNu1ZLkVk32D3B97JcAHdN4f7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-12-24 at 12 17 36](https://github.com/user-attachments/assets/575c3fbf-8c03-4732-8ff4-9e55b791a24e)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I wasn't able to replicate the issue on my end. To assist you further, I've created a public project where I attempted to replicate the behavior. You can clone the project, test it, and make any necessary modifications to investigate further.

Here’s the project link: [https://app.flutterflow.io/project/qa-3354-jna6mb](https://app.flutterflow.io/project/qa-3354-jna6mb)

Feel free to let me know if you have any questions or need additional support!

**Comment by koosdeklerk** [comment]
Good day,

I've tried to update the project to replicate the issue, but the project 
doesn't save and keep my changes.  So all widgets, datatypes, anything I 
create, is lost as soon as you refresh the the screen.  The datatypes 
does not even register.  Please create another project or read my 
instructions how to replicate carefully.  It is really not that 
difficult to recreate.

On 2024-12-24 15:47, Alezanello wrote:

> Hello!
> 
> I wasn't able to replicate the issue on my end. To assist you further, 
> I've created a public project where I attempted to replicate the 
> behavior. You can clone the project, test it, and make any necessary 
> modifications to investigate further.
> 
> Here's the project link: 
> https://app.flutterflow.io/project/qa-3354-jna6mb
> 
> Feel free to let me know if you have any questions or need additional 
> support!
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/FlutterFlow/flutterflow-issues/issues/5173#issuecomment-2561148316
[2]

**Comment by Alezanello** [comment]
When you open the project I shared you, you need to CLONE it to generate a new version of it where you are the owner, make the changes and then generate a new bug report code from that project so I can access it!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f6eab712-9a95-45aa-9c00-2edb478be2b1/3678e88e-537f-4d6d-a0c1-8f73d5235060?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNmVhYjcxMi05YTk1LTQ1YWEtOWMwMC0yZWRiNDc4YmUyYjEvMzY3OGU4OGUtNTM3Zi00ZDZkLWEwYzEtOGY3M2Q1MjM1MDYwIiwiaWF0IjoxNzM1MjE4OTA4LCJleHAiOjMzMzA1Nzc4OTA4fQ.V67ihiTCb6SZF8X6FKjnGreUXmqMX1-QiOnjs3MEnMM " alt="image.png" width="1919" data-linear-height="731" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!

**Comment by koosdeklerk** [comment]
I don't understand why you just can't log into the pages I provided you 
when I logged the bug and see the issue.  I had to create a workaround 
which compeletely negates the use of action blocks due to this bug.  I 
do not have time to create new projects, copy projects, rebuild issues.  
I have my own deadlines plus it is not my platform that has the bugs.  
This is the second time that FlutterFlow closes bugs I report because 
they are not prepared to just follow what I'm giving them.  That's the 
way to go guys!  I really like FlutterFlow, and have been using you guys 
for years.  The least you can do is follow instructions when a bug is 
logged (which already takes times from developers) and not expect busy 
developers who do not have enough hours in the day as it is, to 
replicate bugs on new projects.

On 2024-12-31 15:13, Alezanello wrote:

> Closing this issue since we haven't heard back from you. If you are 
> still facing the problem please submit a new issue. Thank you!
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/FlutterFlow/flutterflow-issues/issues/5173#issuecomment-2566446049
[2]
