### ISSUE TITLE
Third Party OAuth Return URL Parameter "code" Leads To Automatic Log Out

### ISSUE THREAD

**Issue by olivierb24** [FlutterFlow/flutterflow-issues#5174]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I log in to my FF app using email.

Part of my software allows users to link their Facebook account to see their ad accounts. I initiate the Facebook login flow.

When being redirected from a third party OAuth provider (Facebook in my case), Flutterflow uses the code returned in the URL to try and refresh the login with Supabase, which causes errors (since the code is not meant to be used for that) and I get instantly logged out of my FF app.

### Expected Behavior

FF shouldn't automatically take codes returned and try to log in with Supabase.

### Steps to Reproduce

1. Go to app.enflowconnect.com
2. Log in/Create an account
3. Try to connect Facebook. Your redirection code will be used by FF to auto refresh the Supabase tokens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wk8nf04xOxe5E7c+BbMFvmjoRMjs/bJ07lsEabCs8GZT0B4kcYs+kfklUON/hYGxiP2egjXIX/MrUivLDGsY7Aw+ZG9VZyZBMFBXMcFiQRbbTDIS3b0ElQO5VGnLG1MOrgSQkOtpZLGQG32D3Ne+Xd3bXJpjGIkY3NOa4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/cd969663-cfef-4257-b9e6-3149f6b2919c)
You can see step 1 we navigate to the Facebook login flow, step 2 we get redirected after successful login, step 3 FF tries to use the code to login with supabase. I

My return url is my FF URL/facebook/callback.

You can see here that the facebook code returned from Facebook is being picked up and sent to Supabase 

### Environment

```markdown
- FlutterFlow version: v5.0.15
- Platform: Windows
- Browser name and version: Chrome Version 131.0.6778.205 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello,

I’m sorry to hear you’re facing this issue. I’ve tested your project but haven’t been able to identify a clear solution. To get more specialized assistance, I recommend reaching out to our support team. You can contact them directly via the in-app chat (blue icon at the bottom-right corner) or by emailing [support@flutterflow.io](mailto:support@flutterflow.io).

The support team will be able to help you determine if this is something that requires a change on FlutterFlow’s end or if there’s an adjustment you can make on your side. Please don’t hesitate to reach out, and I hope this gets resolved quickly for you!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
