### ISSUE TITLE
Changing pod version doesn't update version in local run

### ISSUE THREAD

**Issue by ayjayem** [FlutterFlow/flutterflow-issues#5175]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to update the version of a pod I'm using (searchfield) to a historical version (1.2.0), my local run won't build using that version, and instead continues to attempt to use the version I had listed previously (1.2.1).

<img width="801" alt="Screenshot 2024-12-25 at 11 39 46 AM" src="https://github.com/user-attachments/assets/59ffa166-eaf8-44a0-b5eb-a4e8ebaed43f" />

### Expected Behavior

After updating the version of the pod from 1.2.1 to 1.2.0, I would expect the local run to properly build using the pod version 1.2.0.

### Steps to Reproduce

1. Build using pod searchfield 1.2.1
2. Update pod to version 1.2.0 and recompile
3. Use local run to get failure notice shown in screenshot above

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlfLqy4ZNocNc+KXqc8cxpGU7M0MdXOczitVEew4bCIj4E5l/ZffeaVhoTeKzaH1AHlKZvE0HwvDVveHDA/I4FzSVfoRiyZFcVRPPbH+nVqqXBYeWTndDGZlYfEy+yLaO2xB7OtNpc1IA1Fz3euyvdz2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="801" alt="Screenshot 2024-12-25 at 11 39 46 AM" src="https://github.com/user-attachments/assets/4b9de7bb-245f-4892-af3d-a6e1b3ff0b86" />

### Environment

```markdown
- FlutterFlow version: 5.0.0
- Platform: 3.24.2
- Browser name and version: Chrome 130.0.6723.117
- Operating system and version affected: MacOS Sonoma 14.3.1
```

### Additional Information

Being unable to run locally, I am completely blocked from further project development.

**Comment by ayjayem** [comment]
So far, I have tried and succeeded in previously clearing .pub-cache using "flutter pub cache clean" in case previous build artifacts might have been the culprit; but on each local run build, the same incorrect searchfield dependency version continues to get built into my local run directory, despite the correct version appearing in my FlutterFlow UI:

**Local run directory**
<img width="1061" alt="Screenshot 2024-12-25 at 11 51 49 AM" src="https://github.com/user-attachments/assets/69c4187b-c68c-4554-a1c7-4ae855db52f6" />


**FlutterFlow UI**
<img width="1381" alt="Screenshot 2024-12-25 at 11 52 45 AM" src="https://github.com/user-attachments/assets/3c73f87f-7758-4e0d-af1a-dda59188d121" />

**Comment by paulperez-dev** [comment]
Hi @ayjayem,

Could you try removing the `^` from the version in your custom dependency and try it again? The version should be set as `1.2.0` instead of `^1.2.0`.

Let me know how it goes or if you run into any issues!

**Comment by ayjayem** [comment]
Oh interesting -- this works now! This seems like updated syntax since I was last working with custom dependencies? In any event, appreciate your having helped and happy holidays.
