### ISSUE TITLE
Video Player Has No Thumbnail On Web iPhone

### ISSUE THREAD

**Issue by gentleVirus** [FlutterFlow/flutterflow-issues#5176]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Both Media Display Widget and Video Player Widget have no initial Preview Image/Thumbnail on Web on iPhones.

### Expected Behavior

Both Media Display Widget and Video Player Widget always show an initial Preview Image/Thumbnail (regardless of "load on page load" option).

### Steps to Reproduce

1. Create a new page
2. Add a column
3. Add media widget and video player widget to column
4. Set auto play and loop video option to off everything else to on
5. Set a video path for both widgets
6. Run on web on iPhone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejMrlvJNPj7xH+c/+c/lvrwMzN1A/U5IrlNpuWRAcGIznBqQlduDOT1VWZ8PhaVNfM07/jl0f0+zTiOGeD/pdJSutGq1zwbV2Vwn0e2inSrKVOpbhenckLJ5hfGaF57S42R1AKu9pcloB3V6MJO++dHbDIuu/Zwh9f6PHaOI=

### Visual documentation

Web On Android Phone (Media Display Top, Video Player Bottom):
![Android](https://github.com/user-attachments/assets/c37aaf8f-3e30-421f-80ee-8aa02b205095)

Web On iPhone (Media Display Top, Video Player Bottom [Load On Page Load On]):
![iPhone](https://github.com/user-attachments/assets/6d72ef8c-44a1-4c0e-8624-c1e4298e337a)

### Environment

```markdown
- FlutterFlow version: 5.0.0+
- Platform: Android & iOS
- Browser name and version: Chrome
```

### Additional Information

This dramatically decrease user experience as they perceive the video player as ''broken" (reported several times by my users).

**Comment by paulperez-dev** [comment]
Hi @gentleVirus,

I’m really sorry for the inconvenience. Unfortunately, this is a known issue with the video package itself. Once the Flutter team addresses it and releases a fix, we will need to upgrade to the new version of the package to resolve it in FF.

Reference: [https://github.com/flutter/flutter/issues/139107](https://github.com/flutter/flutter/issues/139107)
