### ISSUE TITLE
Colors directly passed to action blocks throw errors

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5181]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.tella.tv/video/colors-directly-pass-to-action-blocks-throw-errors-033q

title says it all

### Expected Behavior

not that

### Steps to Reproduce

action block with a color as a parameter

try to pass FFTheme color or a regular hex 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40sOX126xOscRJ15PqWuxGgmEsHGIjRLgJkNVraCosfZT2BLMcec/RVERoTsu+Y1FpPmaWkWoW0Pzpkc7DO/cEPS+rGaZb/7hTEzrxQjuuMrXXFJWvPGhAHehmG3alyrbYmhN+KbZqR1IZwF2EAvOXEwTvH5CxDHo0Da/LZO4=

### Visual documentation

https://www.tella.tv/video/colors-directly-pass-to-action-blocks-throw-errors-033q

### Environment

```markdown
FlutterFlow v5.0.20 released December 26, 2024
Flutter version is 3.24.2
```

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturn

Thanks for reaching out! This issue has already been reported and is being tracked in **#5112**. Please refer to that ticket for further updates.

I'm closing this as duplicate.

**Comment by chuggmuffinReturns** [comment]
haha that chuggmuffin guy is on top of things..... 

Thanks Paul!
