### ISSUE TITLE
Generating dynamic children with if/else condition has issues in document type panel

### ISSUE THREAD

**Issue by Nic61** [FlutterFlow/flutterflow-issues#5182]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. I add a list view
2. Generate dynamic children
3. Set the value to a an if/else statement
4. Set return type to document reference or document
5. You cannot see the names of collections

### Expected Behavior

1. I add a list view
2. Generate dynamic children
3. Set the value to a an if/else statement
4. Set return type to document reference or document
5. Collections to choose from are shown

### Steps to Reproduce

1. I add a list view
2. Generate dynamic children
3. Set the value to a an if/else statement
4. Set return type to document reference or document
5. You cannot see the names of collections

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

<img width="681" alt="Screenshot 2024-12-26 at 18 21 58" src="https://github.com/user-attachments/assets/f40c1312-9557-4c62-a040-3e2d666bda41" />

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released December 26, 2024
Flutter version is 3.24.2
- Platform: Macbook 15.1
- Browser name and version: Google Chrome
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @Nic61,

Thanks for reaching out! This issue has already been reported and is being tracked in **#5109**. Please refer to that ticket for further updates.

I'm closing this as duplicate.
