### ISSUE TITLE
Flutterflow settings page goes entirely gray

### ISSUE THREAD

**Issue by leoleo-s** [FlutterFlow/flutterflow-issues#5183]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow settings page just got entirely gray after the newest update (december 26, 2024). 

### Expected Behavior

Settings page should open normally.

### Steps to Reproduce

Log into flutterflow account, try to open settings page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klsn134VPxOFG+KnxbcZFvDsXC0A4TL07ttYbZxUjIuPtBJh/P874RBNpTb3hdENhHGClpEcepPTVivHXV/U6AwiYbqU6zbp+eg/MQXq8R6qrCpedPEdtJ9lWG1SX5rSvpiQkBPRvSCEW60+qIevJbBfsN5+/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/edebf32c-dd46-4bf4-b02f-82f1d6f0fbc0

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released December 26, 2024
- Platform: Web
- Browser name and version: Chrome Version 131.0.6778.205
- Operating system and version affected: MacOS Ventura 13.7.2
```

### Additional Information

It's completely preventing me from developing as I'm unable to integrate my project with Github, deploy any version or access any settings of Flutterflow.

**Comment by Alezanello** [comment]
Hello!

This is a known issue and the team is going to deliver a fix shortly!

You can follow the main issue here: [https://github.com/FlutterFlow/flutterflow-issues/issues/5180](https://github.com/FlutterFlow/flutterflow-issues/issues/5180)

I'll close this one as duplicated for now
