### ISSUE TITLE
Can't see "Settings and Integrations" page neither in MacApp nor Web version

### ISSUE THREAD

**Issue by lightapps-smart-blocks** [FlutterFlow/flutterflow-issues#5184]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After 5.0.20 update, I cannot see "Settings and Integrations" page, neither in mac APP nor in web version, and thus, not able to deploy the app. I can't also use older versions (that I have installed) because it won't allow me (popup forces me to download newest version and won't let me navigate in the project)

### Expected Behavior

To open and see"Settings and Integrations" page normally.

### Steps to Reproduce

Click on "Settings and Integrations" icon.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMmAuIlOm+EA1s7xbccwmjk5Jkw2a4JFmsJRaCosfZT2BLMcec/RVERvOPW7T39bME6Jr2oW09Loi+z1DfkDITeac6ZB+bVqSgzLTliQVKrUFJWgRX8nM8NWJlzF1KWzgRFvKbJ1SHxh7EOuGNytUnPcJ5CwNVcSD6/LZO4=

### Visual documentation

Mac App:
![image](https://github.com/user-attachments/assets/3084f816-e0b0-4247-bdf3-933504e395e9)

Web version:
![image](https://github.com/user-attachments/assets/0d1a7401-ef9e-4892-a492-78af427e93b5)

### Environment

```markdown
- FlutterFlow version: 5.0.20
- Platform: Apple M3 Pro 
- Browser name and version: Google Chrome Version 131.0.6778.205 (Official Build) (arm64)
- Operating system and version affected: 15.2 - Sequoia
```

### Additional Information

I can't deploy a bug fix! Very bad situation.

**Comment by Alezanello** [comment]
Hello!

This is a known issue and the team is going to deliver a fix shortly!

You can follow the main issue here: [https://github.com/FlutterFlow/flutterflow-issues/issues/5180](https://github.com/FlutterFlow/flutterflow-issues/issues/5180)

I'll close this one as duplicated for now
