### ISSUE TITLE
Latest Updated broke Settings in FF

### ISSUE THREAD

**Issue by SebyOnGitHub** [FlutterFlow/flutterflow-issues#5185]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Create a new project and try to open the Settings. I only see a grey screen.

### Expected Behavior

Should open settings.

### Steps to Reproduce

Create new Project
Open Settings

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kvHqx5J2rsNd18/udMAwmj05JUQ1UL8R0tZBaCgofePtOol3evWlQBZWOMuhTwhcIUSmmloe+tbIuM7DC/JdYCuZf6581s1IcDrgfHima5OBDZO8X0RRP99bIECF37bUhBYmOvNhcVoOwVz3A+mvaALZJLLyIlFISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/6a78aaad-7ffb-458f-9f11-62989e46a78a)

### Environment

```markdown
- FlutterFlow version: v5.0.17+
- Platform: Windows
- Browser name and version:
- Operating system and version affected: Windows10
```

### Additional Information

This seems to work in Web, but not in Windows build.

**Comment by markleavitt** [comment]
This just happened to me as well, but in an existing project (with over a year worth of work). After I updated to FlutterFlow Desktop v5.0.20 released Dec 26, the Settings and Integrations tab shows a blank gray screen. Screen cap attached.
![Screenshot 2024-12-26 at 11 25 32 AM](https://github.com/user-attachments/assets/b12e6f24-3717-4317-801c-a305ce83e683)
The web version of the IDE (version 5.0.0+, Dec 26) is still working, but losing Local Run for testing is painful. Please fix!
P.S. Environment is MacBook Pro M4.

**Comment by momininkitabcasi** [comment]
Hello, after the last update, everything is messed up in the panel. Some functions have also disappeared. The names of the sections have changed, widgets have been removed. I am very worried, please. Please fix this, solve this problem.

Thanks in advance...

**Comment by markleavitt** [comment]
FlutterFlow devs, while you are working on this, please please give us a link to the **previous** version of FlutterFlow desktop so we can roll back. This is a critical issue killing development right now!

**Comment by paulperez-dev** [comment]
Hey everyone! 

Thanks for your patience. The fix is now live! Please update to the latest version.

I’ll go ahead and close this issue, but feel free to reach out if you run into anything else.

Appreciate your understanding! 😊

**Comment by markleavitt** [comment]
@paulperez-dev  I can confirm it fixed the problem in my FlutterFlow desktop. Thank you for the prompt attention!

**Comment by momininkitabcasi** [comment]
![Screenshot 2024-12-27 015231](https://github.com/user-attachments/assets/4f9b6f9c-59c5-49b4-9667-7804c120ffa6)
![Screenshot 2024-12-27 015242](https://github.com/user-attachments/assets/50a247ee-ac30-41a0-940e-d550b3a1b33a)
![Screenshot 2024-12-27 015259](https://github.com/user-attachments/assets/1d7ae0fc-ff8b-458a-bf9d-aec16040087a)
![Screenshot 2024-12-27 015314](https://github.com/user-attachments/assets/331640ed-b023-4e50-8bd1-69e066334900)
![Screenshot 2024-12-27 015338](https://github.com/user-attachments/assets/f388aca3-8916-4fd9-9161-f9190eafdf3d)
![Screenshot 2024-12-27 015354](https://github.com/user-attachments/assets/1570c113-0746-4f18-b614-ca04597d29af)
![Screenshot 2024-12-27 085820](https://github.com/user-attachments/assets/7d073a8d-c4ef-4727-8ed0-17c577c668fd)
I checked on my desktop and on the web, it still hasn't been fixed. There's no new update either. I also changed it to the version I saved earlier in the panel, it fixed it for 1-2 minutes, then it got messed up again. Nothing is saved, and if you log in again, it goes back to the previous messed up state.

**Comment by momininkitabcasi** [comment]
Additionally, I would like to note that this error does not occur in a newly created project. All of my previously created projects have this problem.

**Comment by Yashraj76** [comment]
I am also getting the issue with the setting grey out,  I am using chrome browser to access flutterflow
![image](https://github.com/user-attachments/assets/113818e5-edb6-4323-94a0-d9f7cd2ad5fb)

**Comment by paulperez-dev** [comment]
Thanks for confirming, @markleavitt!

@momininkitabcasi, based on the images you provided, this appears to be a different issue than the one originally reported. To keep things organized, could you please create a new issue for it? I’ll go ahead and close this one.

Appreciate your help and understanding! 😊
