### ISSUE TITLE
Screen to small, not all options are shown

### ISSUE THREAD

**Issue by JorVanDia** [FlutterFlow/flutterflow-issues#5187]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I go deep inside the functions and my screen get to small, the last options in a dropdown aren't shown

### Expected Behavior

I want to get acces to all options anytime.
In previous versions of flutterflow this wasn't an issue

### Steps to Reproduce

1. Go deep into the actions menu (see picture)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

impossible

### Visual documentation

![image](https://github.com/user-attachments/assets/e9b7167c-5921-4083-a29f-d5740f64ec10)

### Environment

```markdown
- FlutterFlow version:  v5.0.18+
- Platform: Web/Windows app (on both it occurs)
- Browser name and version: Edge
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment]
Hi @JorVanDia,

It’s possible the issue only appears under certain conditions. Could you share a bug report code for your project? That will help us take a closer look.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f0f4903b-59be-4863-b0c7-cce9911641ef/fe6af928-7b06-48d6-87c0-ff54e2362091?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMGY0OTAzYi01OWJlLTQ4NjMtYjBjNy1jY2U5OTExNjQxZWYvZmU2YWY5MjgtN2IwNi00OGQ2LTg3YzAtZmY1NGUyMzYyMDkxIiwiaWF0IjoxNzM1MzA2MzQ4LCJleHAiOjMzMzA1ODY2MzQ4fQ.46eI4v56aUoO7Fax5EXgV4gJxWt_uUAR2w_lmqb6qf4 " alt="image.png" width="1580" data-linear-height="969" />

**Comment by paulperez-dev** [comment]
Hi @JorVanDia,

Closing this issue since we haven't heard back from you. If you are still facing the problem, please submit a new issue. Happy holidays!
