### ISSUE TITLE
Datatable does not update data with page state after altering its visibility

### ISSUE THREAD

**Issue by Granahh** [FlutterFlow/flutterflow-issues#5188]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,

We are using datatables that, for some reason, are unable to display information. I am sharing a video showcasing the issue and the code. This functionality used to work previously, so it seems to be related to the latest update of this dependency.

### Expected Behavior

Data must change.

### Steps to Reproduce

Just open the page Stats.

Proyect id:  owner-q3t25z

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeic+AvJNPn7xI+c7pYO1aowMxQFgnUL43iuxFGAIYGLauPJYMZ8/EaXdYUuGCd25qC1mb/HI0pqH7v/DxJcAEYC+eGdh607gJVgLgJHGRRrapDc2eYHdRBd9VCGq10Z67nCMlBMdZWiU86nGLcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

[datatable-issue-bug.webm](https://github.com/user-attachments/assets/39b785c5-45b4-4b8a-a939-3480410d1245)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

### Additional Information

I am getting complaints from my customers, please treat it as a priority, because this has alwa

**Comment by Alezanello** [comment]
Hello!!<br><br>Just a quick view on your project.<br><br>On Page Load you are saving the API Response to the Page State variable named `salesReport` BUT in the dynamic children in "Top Ventas" you are generating the children form the Page State variables named `productsReport`

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b7ea1c8d-48c5-4914-8e71-5d2357d61fb7/4dbed1bb-7cfb-4b3c-ab1e-e85af57a5f2d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iN2VhMWM4ZC00OGM1LTQ5MTQtOGU3MS01ZDIzNTdkNjFmYjcvNGRiZWQxYmItN2NmYi00YjNjLWFiMWUtZTg1YWY1N2E1ZjJkIiwiaWF0IjoxNzM1MzI0OTA2LCJleHAiOjMzMzA1ODg0OTA2fQ.u9Vglzv9p3Hqj14V136syl5gHdcFavwCBDRNHqj7nLA " alt="image.png" width="1226" data-linear-height="720" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a7891130-9fe2-4bb4-883c-b231b5001cc5/907b521e-9cce-4afc-8bd5-9bd5d6b6400d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNzg5MTEzMC05ZmUyLTRiYjQtODgzYy1iMjMxYjUwMDFjYzUvOTA3YjUyMWUtOWNjZS00YWZjLThiZDUtOWJkNWQ2YjY0MDBkIiwiaWF0IjoxNzM1MzI0OTA2LCJleHAiOjMzMzA1ODg0OTA2fQ.m0ZVITnCsP9ghAsRQrPSq9GOdaQoEnKZ4pldQcMv-ZE " alt="image.png" width="1874" data-linear-height="538" />

So you are setting the response on variable X but consuming the information on the table from variable Y

**Comment by Granahh** [comment]
Fixed thanks :)
