### ISSUE TITLE
Redirect bug after delete user/logout action

### ISSUE THREAD

**Issue by TemplarDesign** [FlutterFlow/flutterflow-issues#519]
I have a page titled "deleteuser" which uses a countdown timer to delete the user, log out the user, then navigate them to the welcome page.

The user is successfully deleted, logged out, and navigated. However, when a user goes to create a new account after the account has been deleted, they enter their credentials and tap the create account button, they get navigated back to the "deleteuser" page, even though the navigate action says to go to the home page.

Since they get directed to the deleteuser page, the user gets deleted again in an endless loop.

Screen recording: https://komododecks.com/recordings/pNIwAmAjLPHkApqlGmHu
## Expected behavior (required)
When a user creates a new account after deleting their previous account, they should still be navigated properly to the home page.

## Current behavior (required)

The user is successfully deleted, logged out, and navigated. However, when a user goes to create a new account after the account has been deleted, they enter their credentials and tap the create account button, they get navigated back to the "deleteuser" page, even though the navigate action says to go to the home page.

## To Reproduce (required)
1. Create a new account
2. Tap on the person icon on the top left corner
3. Tap "delete account"
4. Tap "yes, delete"
5. Wait to be logged out
6. Create a new account again and you'll be directed to the deleteuser page.

## Context (required)

I just want my users to be able to delete their accounts if they want and create a new account without getting navigated to the incorrect place.

## Screenshots / recordings

https://komododecks.com/recordings/pNIwAmAjLPHkApqlGmHu

## Your environment

* Version of FlutterFlow used: 1.1.44 - flutter3.7.3
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Browser name and version: Chrome 110.0.5481.100
* Operating system and version (desktop or mobile): desktop, iMac, 3.6 GHz 10-Core Intel Core i9, 128 GB 2667 MHz DDR4, operating on macOS Monterey v12.5

**Comment by TemplarDesign** [comment]
Any update?

**Comment by wenkaifan0720** [comment]
Hi @TemplarDesign. Could you provide the bug report code? Thank you.

**Comment by TemplarDesign** [comment]
IT4Cz8r13ItPsfVY0LrUbMdV/CQWNkx8RYEnmsF+VkwYHZPMC+wIZ/f7XFRuTde0T1VAfVn9knkxwM3emvHpM8c6ITKYRr5YwpZtEQnzQmSQbqawPc/sdG5/Df1MCEiEy8HYsRV4GNRuLF4C6lOQGu6/dAHDGI+2C3oRLf+KC5OK2SrDX1iXc2URm05KZDPz

**Comment by TemplarDesign** [comment]
@wenkaifan0720  ?

**Comment by hariprasadms** [comment]
Hi @mravani2 - Can you please look at this issue ?

**Comment by wenkaifan0720** [comment]
Hi @TemplarDesign. I am traveling internationally this week. Will look into this during the weekend. Sorry for the delay.

**Comment by wenkaifan0720** [comment]
Hi @TemplarDesign. I just made a test project (https://app.flutterflow.io/project/flutterflow-issue-519-ivgm9s) and was not able to reproduce the issue. Could you spot what is different between this project and yours?

**Comment by agreaves** [comment]
Oops! Did not mean to close until confirming our solution works. @TemplarDesign please check the latest Run mode on the affected project and let me know if the issue is still occurring. Thanks!

**Comment by wenkaifan0720** [comment]
Since this thread has been stale for 2 weeks. I'll close it for now.
