### ISSUE TITLE
Translation service character encoding

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#52]
## Expected behavior (required)
Characters such as accents to be displayed as such

## Current behavior (required)
`d&#39; `instead of apostrophe.

## To Reproduce (required)
1. Google Translate into French or Italian

1. Create text widget
2. Use the Translation feature to translate into French or Italian. Might be an issue for additional languages.

## Context (required)
I want my app to be available in all languages spoken in the EU.

## Screenshots / recordings
[screenshot from app in prodution (Android)](https://photos.app.goo.gl/1KDLZjG9jrAAVMSH9)
[Flutterflow interface](https://photos.app.goo.gl/hJ2GNxHwLaRqN4keA)
[production web deployment](https://ampower.flutterflow.app/home)

## Your environment
* Operating system and version (desktop or mobile): Android and Web

**Comment by bulgariamitko** [comment]
Can you write the French or the Italian word you are trying to write so I can test this out with the exact same word?

**Comment by ampapplarsen** [comment]
> Can you write the French or the Italian word you are trying to write so I can test this out with the exact same word?

Yes, you can try translating `Today` to French. In my end it becomes `Aujourd&#39;hui` instead of `Aujourd'hui`

**Comment by agreaves** [comment]
Thanks for catching this! We've made the fix which will be deployed in our next update 🙂
