### ISSUE TITLE
Button in the Team Component Information Card does not render properly in builder in light mode

### ISSUE THREAD

**Issue by krabhishek** [FlutterFlow/flutterflow-issues#521]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
The button text should be visible

## Current behavior (required)
button text is not visible

## To Reproduce (required)

1. Open the builder in light mode and create a component in a design system
2. Create a project and add the said component in the project
3. Click on the edit component button
4. Team Component Information Card has a button but it does not show up properly.

## Screenshots / recordings

<img width="335" alt="image (6)" src="https://user-images.githubusercontent.com/883178/220734338-25ac76fb-bc34-4952-a663-bb98e8cb0d27.png">
## Your environment

* Version of FlutterFlow used: 3.1
* Platform (e.g. Web, MacOS Desktop): Web 
* Browser name and version: Chrome 110

* Operating system and version (desktop or mobile):

**Comment by aemelyanovff** [comment]
Will be fixed in the next update.
