### ISSUE TITLE
Page state variable issue

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#526]
Add a Page state variable as integer, i cannot assign an initial value = -1
Add App state variable as integer and i CAN assign an initial value = -1

Tested with FF MacOS v1.1.44 and FF web 3.1 Flutter 3.7.3

Referring #551

**Comment by blondie63** [comment]
Doing other test i've seen also that conditions have problem to evaluate this page state variables!
My test:
I've an icon button and i want to change is color basing on a page state variable with name viewerQuery
viewerQuery can be -1 ; 0 ; 1
i've created an action like this:
if viewerQuery < 2 then viewerQuery++ else viewerQuery = -1
this is IconButton color condition:
<img width="338" alt="FF-page-state-values-issue" src="https://user-images.githubusercontent.com/1261851/221246998-e3c2c26b-5695-46eb-96d5-9a2ed6f1a2b7.png">

when value = -1 the color is wrong !

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @blondie63. Please update the description according to the template.

**Comment by bulgariamitko** [comment]
I made some tests and it is actually working fine for me. 


https://user-images.githubusercontent.com/7221384/222155275-1a9cb479-8b2a-4f04-84f9-263a43a0ebed.mp4

**Comment by blondie63** [comment]
I still have same problems with last version!

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!
