### ISSUE TITLE
Webview widget don't work with any URL except https://flutter.dev/

### ISSUE THREAD

**Issue by funkydevil** [FlutterFlow/flutterflow-issues#527]
## Expected behavior (required)
Webview widget show web page with any URL

## Current behavior (required)
If set URL property to https://flutter.dev/ then it works fine, if set any other url address, then webview shows nothing

## To Reproduce (required)
1. Create new page
2. Add webview widget
3. Set URL to https://flutterflow.io
4. Click Run
5. Observe that webview shows nothing

## Your environment

* Version of FlutterFlow used: 1.1.45
* Platform (e.g. Web, MacOS Desktop): macOS desktop
* Browser name and version: safari 16.1 , chrome 110.0.5481.100
* Operating system and version (desktop or mobile): mac os 13.0

## Errors in console
![Dashboard - FlutterFlow 2023-02-25 13-29-48](https://user-images.githubusercontent.com/446654/221359719-7a204562-7b58-4dcc-abc5-e45568da351a.jpg)

## Screenshot how it looks
![Test Mode - newsApp 2023-02-24 12-42-47](https://user-images.githubusercontent.com/446654/221240410-083a7adb-1e32-4fea-bc95-e15f02a59b64.jpg)

**Comment by hariprasadms** [comment]
Hi @funkydevil - Please update issue details as per recommended issue template. Once details are updated, we can look into the issue.

**Comment by funkydevil** [comment]
@hariprasadms done :)

**Comment by aemelyanovff** [comment]
Try checking "Bypass domain restrictions" in WebView properties.

**Comment by funkydevil** [comment]
@aemelyanovff Thanks for advice. I tried this. Its not helped :(

**Comment by aemelyanovff** [comment]
> @aemelyanovff Thanks for advice. I tried this. Its not helped :(

What's the error in the console?

**Comment by funkydevil** [comment]
> What's the error in the console?

Only ones, that I put in issue description.
Also here is a little discussion about this issue and video with reproducing.
https://community.flutterflow.io/c/discuss-and-get-help/webview-works-strange#comment_wrapper_16202532

**Comment by aemelyanovff** [comment]
Closing as inactive. @funkydevil please reopen if you add details about the error after checking "Bypass domain restrictions".
