### ISSUE TITLE
Cannot assign colors and Fonts in FF from Figma Theme

### ISSUE THREAD

**Issue by harshtonde** [FlutterFlow/flutterflow-issues#530]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I should be able to assign my colors/fonts imported from Figma in the project design theme.

## Current behavior (required)

I'm able to import my Figma theme successfully but when I try to assign the imported colors/fonts in my Project Design Theme then I'm not able to set the colors/fonts from Figma.  

## To Reproduce (required)

The code is for HomePage
IT4Kic/q25NPn7xK17r+c/lR/WAWHEx9U4IKlsJTQk0YF5SvG7YAW/SkQE9WZ7yhdH02M2KkjmU1zPDUuMzIN/Y4FyitGr5n1at5EDzMRmqXeKq0BZOKeXxCIJYGSSDy

## Context (required)

Trying to import Figma Theme into FF

## Screenshots / recordings

![2023-02-26_03-43-30](https://user-images.githubusercontent.com/59639282/221382224-03d19835-b136-4ee8-b88b-0fb6e0be01f3.gif)

## Your environment

* Version of FlutterFlow used: v3.1, Feb 24, 2023
* Platform (e.g. Web, MacOS Desktop): Tested on web and macOS application
* Browser name and version: Google Chrome
* Operating system and version (desktop or mobile):  Testted for windows and macOS

**Comment by katherineqian** [comment]
Fixed and should be resolved in the next release.
