### ISSUE TITLE
The page state variable and action output variable must not be the same.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#532]
## Expected behavior (required)

Let's put that I have a page state named "event" and an action output variable named as "event" also.
Then, these two same variable names conflicts on the page model like below.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/5080329/221392577-fd539c1b-7ba6-4e6c-bfa3-bbc5df2aa34d.png">

The expected behavior would be one of;

- There should be an error on UI builder before the app run.
- Or the app run without error.

## Current behavior (required)

- There is an error and it does not run/build.

## To Reproduce (required)

1. Create new page
2. Do some action and put the result into `event`.
3. Declare a page state variable named `event` also.
4. Click Run
5. Observe that project doesn’t build

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")

ITESz/Hqx89gruFH7YfpY8B6hQIgQ0QnU7gnlO1ucx4gIb2rP5YAYszBYUNKTd+4YwhAD02grDgKpsLSv+PiGu1dZAueRYBzk/UwKlCvHAM=

## Context (required)

- For the development experience, the UI builder should warn the developer if it's not going to work.

## Screenshots / recordings
N/A (see the screentshot above)

## Your environment

* Version of FlutterFlow used:  latest
* Platform (e.g. Web, MacOS Desktop): MacOS desktop
* Browser name and version: Chrome latest
* Operating system and version (desktop or mobile): desktop

**Comment by organicnz** [comment]
Hi @thruthesky. Thank you JaeHo adding this issue, mate 🙂

Hmm, I couldn't reproduce this issue. I've already created the local page state event and the App State hasn't appeared in the code :)

![image](https://user-images.githubusercontent.com/4765090/221945156-3ffc570f-130d-46c6-a1ed-e377f89cf3b0.png)

![image](https://user-images.githubusercontent.com/4765090/221945295-a19d41b5-b65f-4e83-a5e2-720c679d4fd1.png)

**Comment by thruthesky** [comment]
> Hi, @organicnz

Can you create an action output named `event` also?

An action output named `event` and a page state named `event`.

**Comment by thruthesky** [comment]
I just tried to reproduce. But the error does not appear anymore. It says `Name 'event' already in use`.
I will close this issue.
Thank you.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/5080329/222019513-6892e1bb-29f2-4046-ba9a-06c205103463.png">
