### ISSUE TITLE
TimeStamp Range component parameters not showing when component placed onto page

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#533]
## Expected behavior (required)

- when you create a FF component and set a Component Parameter to Timestamp Range the parameter it does not show when that component is placed onto a page
- the parameter is there, and FF will throw an error saying a parameter is not set
- i tested a few different things like re-creating the parameter to make sure it was a bug, i also switched the parameter type to Timestamp and it showed up, then switched back to Timestamp Range and it disappeared from showing as an input when place onto a page
- other interesting thing is if you switch the Timestamp Range to a <List> it does show up

## Current behavior (required)

- component parameter does not show

## To Reproduce (required)

1.
2.
6.
7.

## Your environment

* Version of FlutterFlow used: Flutter Flow 3.7.3
* Platform (e.g. Web, MacOS Desktop):  MacOS Desktop / Web
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Closing this as stale (and because of a lack of reproducible steps or bug report code). Please re-open if you are still experiencing this and have both of these!
