### ISSUE TITLE
Exception: Failed to compile application for the Web.

### ISSUE THREAD

**Issue by lovejune79** [FlutterFlow/flutterflow-issues#534]
An error occurred when I ran the command flutter build web --web-renderer canvaskit --release . 

Before the 3.7.3 version update, I was able to use it normally. 

The error code came out.

../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart:132:9:
Error: 'DrawableParent' isn't a type.
  final DrawableParent drawable;
        ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart:160:14:
Error: 'DrawableParent' isn't a type.
  void _draw(DrawableParent root, Canvas canvas, Paint paint) {
             ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart:163:25:
Error: 'DrawableShape' isn't a type.
        if (drawable is DrawableShape) {
                        ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart:189:32:
Error: 'DrawableParent' isn't a type.
        } else if (drawable is DrawableParent) {
                               ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart:167:32:
Error: The getter 'DrawablePaint' isn't defined for the class 'DrawableSignaturePainter'.
 - 'DrawableSignaturePainter' is from 'package:hand_signature/src/signature_painter.dart'
 ('../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart').
          if (fill != null && !DrawablePaint.isEmpty(fill)) {
                               ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart:172:41:
Error: The getter 'DrawablePaint' isn't defined for the class 'DrawableSignaturePainter'.
 - 'DrawableSignaturePainter' is from 'package:hand_signature/src/signature_painter.dart'
 ('../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_painter.dart').
          } else if (stroke != null && !DrawablePaint.isEmpty(stroke)) {
                                        ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_view.dart:89:9:
Error: 'Drawable' isn't a type.
  final Drawable? data;
        ^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_view.dart:143:50:
Error: 'DrawableRoot' isn't a type.
          size: PathUtil.getDrawableSize(data as DrawableRoot),
                                                 ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_view.dart:146:33:
Error: 'DrawableParent' isn't a type.
              drawable: data as DrawableParent,
                                ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_view.dart:180:3:
Error: 'DrawableParent' isn't a type.
  DrawableParent? drawable;
  ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_view.dart:194:24:
Error: The method 'SvgParser' isn't defined for the class '_HandSignatureViewSvgState'.
 - '_HandSignatureViewSvgState' is from 'package:hand_signature/src/signature_view.dart'
 ('../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/signature_view.dart').
        final parser = SvgParser();
                       ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/nb_utils-4.6.25/lib/src/widgets/overlay_custom_widget.dart:99:13:
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../flutter/packages/flutter/lib/src/widgets/overlay.dart').
    Overlay.of(context)!.insert(entry);
            ^
../../.pub-cache/hosted/pub.dev/extended_image-6.4.1/lib/src/gesture/page_view/widgets/scroll_position.dart:125:17:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart'
 ('../../flutter/packages/flutter/lib/src/widgets/page_storage.dart').
    PageStorage.of(context.storageContext)?.writeState(context.storageContext,
                ^
../../.pub-cache/hosted/pub.dev/extended_image-6.4.1/lib/src/gesture/page_view/widgets/scroll_position.dart:132:41:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart'
 ('../../flutter/packages/flutter/lib/src/widgets/page_storage.dart').
      final double? value = PageStorage.of(context.storageContext)
                                        ^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/utils.dart:312:35:
Error: 'DrawableParent' isn't a type.
  static List<Path> parseDrawable(DrawableParent root) {
                                  ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/utils.dart:320:29:
Error: 'DrawableParent' isn't a type.
  static _parseDrawableRoot(DrawableParent root, List<Path> output) {
                            ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/utils.dart:323:25:
Error: 'DrawableShape' isn't a type.
        if (drawable is DrawableShape) {
                        ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/utils.dart:325:32:
Error: 'DrawableParent' isn't a type.
        } else if (drawable is DrawableParent) {
                               ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/hand_signature-2.3.0+1/lib/src/utils.dart:332:31:
Error: 'DrawableRoot' isn't a type.
  static Size getDrawableSize(DrawableRoot root) => root.viewport.size;
                              ^^^^^^^^^^^^
Error: Compilation failed.

#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             18.7s
Exception: Failed to compile application for the Web.

## Your environment

* Version of FlutterFlow used: 7.3.3
* Platform Web
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by wenkaifan0720** [comment]
Hi @lovejune79. Looks like there is incompatibility between Flutter 3.7.3 and the hand_signature 2.3.0 package that you are using. Could you try to update the hand_signature package to the newest 3.0.1 version? If the problem persists, please attach the bug report code so I can look into the project with our details. Thank you.

**Comment by bulgariamitko** [comment]
Or if that does not work. You can actually try different versions of the hand_signature package until it work :)
