### ISSUE TITLE
Creating a sub-collection document from the collection's action output reference doesn't work

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#536]
## Expected behavior (required)
I want to create a document in a subcollection from the collection document's action output (doc reference) in one action flow. 
So my action looks like this: create the document, wait, and then create a subcollection document for the previous document

## Current behavior (required)
If I execute the action flow, it only creates the collection's document, then the action flow stops

## To Reproduce (required)
1. create a firebase collection
2. create a subcollection for it
3. create a page 
4. add a textfield widget
5. add 3 actions to the actionflow:
      1. create a document for the collection, and add an action output
      2. wait/delay 1000
      3. create a subcollection document and add the document reference from the action output (document reference)
6. execute the action and observe in firebase that only the first action was executed, the subcollection was not created

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")
IT40jM/q4c5PmOZE7rr+KcJV+T45KWJ5a7gr0MFraCsofePrOpkAf8/7UFtUOP3nTHNUPlqjrHkX/MqLvYbLC/lfPTmrUaI5zLV6VzrwUkemMa6YELzlMS0ffaMKRSz+

## Context (required)
I want to create a document in a subcollection from the collection document's action output in one action flow. 
My action flow looks like this:
![CleanShot 2023-02-26 at 22 22 44](https://user-images.githubusercontent.com/45784821/221438074-711997c8-f539-4e66-b873-ee3b40210b11.jpg)

the first create document action creates a document for the collection and contains an action output
the second create document action creates a document for the collection's subcollection and the collection reference is set from the actionoutput (document reference)

## Your environment
* Version of FlutterFlow used: V1.1.45 • Flutter 3.7.3
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): mobile, iOS

**Comment by hariprasadms** [comment]
Hi @mravani2 - Can you please look at this issue ?

**Comment by mravani2** [comment]
Thanks for sharing this, @kicsijohn. I was just about to ask you for more details since I couldn't reproduce the issue, but I'm glad to know that you have found a solution 🙌

Don't hesitate to contact us again if you need further assistance 😉.
