### ISSUE TITLE
Some Language Selection Widget country names are not capitalized

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#54]
## Expected behavior (required)
All country names be capitalized in the language selection widget.

## Current behavior (required)
Some country names are small caps.

## To Reproduce (required)
1. Add some additional languages
2. Add the language selection widget to a page
3. Observe the error 

## Context (required)
To display congruent language selection dropdown options.

## Screenshots / recordings
[Web deployment. Please go to the Settings page](https://ampower.flutterflow.app/home)
[Screenshot](https://photos.app.goo.gl/pSczTHb75rwtxnFd6)

## Your environment
* Browser name and version: Safari 15.6.1 (17613.3.9.1.16)
* Operating system and version (desktop or mobile): MacOS 12.6

**Comment by hariprasadms** [comment]
Hi, I have checked it. It's looks all the languages are starting with capital letter. I also did test this one of my sample app. It works fine int the app. 

![image](https://user-images.githubusercontent.com/17435678/197738431-0fd854cc-52cf-4f46-aca6-b035d2640c02.png)

**Comment by ampapplarsen** [comment]
> Hi, I have checked it. It's looks all the languages are starting with capital letter. I also did a test in my sample app. It works fine in the app.
> 
> ![image](https://user-images.githubusercontent.com/17435678/197738431-0fd854cc-52cf-4f46-aca6-b035d2640c02.png)

No, this is my updated code. Notice the lack of flags in the dropdown. The issue persists in FF code.

**Comment by ampapplarsen** [comment]
Here's a screenshot from the FF interface. 
[Screenshot](https://photos.app.goo.gl/2TFyDEKo6VhRj8uSA)

**Comment by hariprasadms** [comment]
Thanks for the additional screen. 

Now I can notice that language names displaying in setting got the different caps status compare the names displays in page editor.

![image](https://user-images.githubusercontent.com/17435678/197798631-c671732d-ad1d-4ea5-8413-d1f818dc7829.png)

It could be for a reason but not sure why this difference. I can mark this as bug and see what Dev team can decide. 
Thanks

**Comment by ampapplarsen** [comment]
That's it! It's really bugging me as a graphic designer and my OCD but it seems like you hit the nail on the head!
