### ISSUE TITLE
Image not uploading via Backend API

### ISSUE THREAD

**Issue by Neesan** [FlutterFlow/flutterflow-issues#542]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

On Friday the 24th of was the last occurrence we were able to upload a image via our own API, no major functional changes were made and our endpoints remained the same. It seems since Saturday and build after does not send the image via our API , As per the below setup we have custom error responses which now identify that no image was passed via the API. This is an exact replica of an issue that was posted back in December (New Feature 'Image upload to API' not working. #273)

![flow](https://user-images.githubusercontent.com/25178385/221653911-6a85cb0d-e7c8-4f49-b6e4-2fb6a1824fbc.png)

### Expected Behavior

Image passed via API 

### Steps To Reproduce

1. Create a new Button.
2. Add Action 1 > Upload Media > Upload Photo / Video >
3. Select Upload Type > Local Image
4. Add another Action 2 > Backend Call > API
5. Select API Used for uploading media (Use any , ours is hosted on a  dedicated server)
6. Pass variable Local Image and inside the Local mage Variable select Uploaded Image Bytes ( You will have to Select Body of the API call as Multipart. and define the variable type as Local Image in API Call.
7. Test 

### Bug Report Code

ITESk8r15YVgruFE+anibMJAhQAkH1x/bZJEl9cbdxQjfIz0PZYUO+r+VHVaXeGRTVZYHmC0gXExp9b2v+L1D8JcITWAatE2k/UwKlCvHAM=

### Context

Images are unable to be sent to our server which are used to create PDF reports used in solving a process i.e reducing significant time into manually creating these reports via Excel

### Additional info

This issue began occurring after the 24th of Feb 2023
Postman calls outside our server network successfully add an image to the server
We believe this is probably a similar bug that occurred back in December

https://github.com/FlutterFlow/flutterflow-issues/issues/273

### Environment

```markdown
- FlutterFlow version: 3.1 (Prior to this version) 
- Platform: Android
- Browser name and version: N/A
- Operating system and version affected: N/A
```

**Comment by hariprasadms** [comment]
Hi @Neesan - Thanks for reporting this issue. This issue is same as #549 Please watch this issue. As it is duplicate we can close this issue.
