### ISSUE TITLE
Padding in buttons broken since today

### ISSUE THREAD

**Issue by younicornsJH** [FlutterFlow/flutterflow-issues#543]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Until beginning of afternoon (CET), padding in buttons has stopped being applied

### Expected Behavior

Padding applied inside buttons

### Steps To Reproduce

1. Create a page
2. Add a button
3. Add text to the button

Button leaves no padding around text whereas it did until this afternoon (CET)

### Bug Report Code

ITFfiPHq2It1xPUB7ZSJK/kwnScXJWkcTeU30+thcw4bI+PsPewUfvf4blpVcuqHS2xICk79kXwfw9Lpi/OTFfE5HAqYf6pHzodtH1yjEA8=

### Context

Many buttons throughout my app, most of which have seen padding disappear earlier today (CET)

### Environment

```markdown
- FlutterFlow version: v3.1 / Flutter v3.7.3
- Platform: Web, iOS, Android
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @younicornsJH - I can't reproduce the issue. Could you please share a quick video of the issue? And also update which button type you are facing issue.

**Comment by younicornsJH** [comment]
Documented all this in a chat conversation with support team
Seems that the previous behaviour for buttons with no explicit width set was to wrap content with some padding, and now it is without padding
