### ISSUE TITLE
Can not edit projects even ones I own after last update

### ISSUE THREAD

**Issue by abbadabbatech** [FlutterFlow/flutterflow-issues#544]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

After this mornings updates, I can not edit any project even the ones I own and ones that I have worked with several times for clients.  I have on client that has a team and I was changed to reviewer for some reason and they did not do it.  But I can not even edit projects that I own.

### Expected Behavior

I should be able to edit my projects and ones without teams, even if this happens

### Steps To Reproduce

any work on any module does not allow me to edit only review and I should be able to atleast edit my own projects

### Bug Report Code

ITFXzMrqx5ROxL1E+c+MY8cwtGAwGUwbUOc7j9VEGAsjCeLpOrQifPf4RxZtcuqHY25qKE2Ynkkz0c7euOLDVO0pCw6ZGapazs19H1yjEA8=

### Context

I can not work at all right now

### Environment

```markdown
- FlutterFlow version:3.1 
- Platform:all
- Browser name and version:chrome
- Operating system and version affected:  windows 10 and Macos
```

**Comment by agreaves** [comment]
Sorry about that @abbadabbatech! This should be fixed now, please let me know if this is not the case!
