### ISSUE TITLE
.gitignore files gone from code generation + massive unexpected/surprising diff

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#545]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

It appears today's update has caused a massive diff in terms of code generation.

The most concerning changes is the removal of .gitignore files as well as rearranging of imports.

The imports were rearranged in all generated files as follows:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/4561505/221715492-9f6f8a2e-7f70-4f9b-b8f9-6f48f48fcc1b.png">
* screenshots from flutterflow branch

.gitignore were deleted:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/4561505/221713664-963a415b-59ae-46d2-a57e-f2e0b85b1b34.png">

The removal of gitignore is causing git status to show thousands of changes due to ios/android and other generated files to show up as untracked:

<img width="57" alt="image" src="https://user-images.githubusercontent.com/4561505/221714096-b7544159-436c-4984-95fa-4a32d5e46d28.png">

If this is change is on purpose, what is the recommendation in terms of .gitignore as per this workflow? https://docs.flutterflow.io/customizing-your-app/manage-custom-code-in-github

### Expected Behavior

Expected:

git status should not show show any untracked files (as with prior version)

### Steps To Reproduce

1. Commit any project that existed prior to today's update to git.

Examine the commit in flutterflow branch on github. 
Result: .gitignore files will be gone

### Bug Report Code

IT4ghcnfz5Fgobhc0bXuY+9amiE7KXp8aK00rdoacxAgfa74EYoPeMzRdk5DUuqzaHx2JmGapDkHwa3uiNjXU8coKTWtY6JByLpQTBPPbGGlM4yPDLW0e39TGZtWG0yX5MGSkBIkLfpuLkI1wEz3GvOART6Cf9qOYwx5e6fDbOY=

### Context

Today as we pushed code from FF that was meant to be a minor patch (which coincidentally we urgently needed to reploy to production), it ended up committing a massive diff with hundreds of files changed and we unexpectedly had to delay our deployment indefinitely until we review all the changes and understand what this update contains.

### Environment

```markdown
- FlutterFlow version: v1.1.46 (Mon, Feb 24)
- Platform: ios native
- Browser name and version: N/A
- Operating system and version affected: Android, iOS
```

**Comment by agreaves** [comment]
Hi @isegal, the import change is intentional, the `.gititnore` removal is not. I'll take a look soon, as that sounds less than ideal. Where are you seeing all the untracked files, etc.?

**Comment by aemelyanovff** [comment]
@isegal Thanks for reporting the issue. We added .gitignore files back. The import change, as mentioned above, is intentional.
