### ISSUE TITLE
checkbox, checkboxlisttile not working on backend query

### ISSUE THREAD

**Issue by blueprin4** [FlutterFlow/flutterflow-issues#546]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

I have tried all different types of configurations but can not get the checkbox to check or uncheck.  I then tested with toggle icon and it would toggle.  I tried with both listview and gridview.

### Expected Behavior

When clicking on the checkbox it should show its checked

### Steps To Reproduce

1. Create a new page
2. add a listview/gridview
3. create a backend query
4. add checkboxListTile
5. run project
6. click on checkbox

### Bug Report Code

ITFflsjfsMxgocdY15SJdcBsrygQNUMcToAzjdV+bwogIuOqCpkqdcnQVFJuTdO0TGxAfWGKnXMxpt3emvLxUPFeBEmZb6Y4zaV+SQn/TmGnb82wDJDse25/AtJWCW6y0MCFkCNCALdvW05i6julfNitQXLXGLmyCmo3Fsn8B5KK2SrDX1iXc2URm05KZDPz

### Context

I can no longer finish working on project at all.  In creating appointments users can not select multiple services.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: mac
- Browser name and version: safari
- Operating system and version affected: Monterey 12.6
```

**Comment by hariprasadms** [comment]
Hi @blueprin4 - I can test it and see working as expected.

If you are using firestore as backend, make sure rules are deployed successfully and also fields should be mapped to checkbox and checbox-tiles variables. It should be same with any api backends.

https://user-images.githubusercontent.com/17435678/221859355-a3a4e269-06bc-4450-a19e-c377150ae5d0.mp4

**Comment by blueprin4** [comment]
Hello @hariprasadms thanks for reply.  It populates the text fields correctly but does nothing when the checkbox is clicked.  I used the group chat tutorial as a reference point.  In the video when you click on the ListTile and navigate to the checkboxListTile there is only 1.  Is that page a listview from firestore?

**Comment by hariprasadms** [comment]
Hi @blueprin4 -  Yes it is ListView and its data is mapped from Firestore.

**Comment by blueprin4** [comment]
> Hi @blueprin4 - Yes it is ListView and its data is mapped from Fire-store. Check that you have added all relevant actions and also mapped the data to text field.

I guess I am having a disconnect somewhere.  I simply created a page with a listview and added a CheckboxListTIle to the listview.  The listview correctly pulls in all the services as expected so to me its connected to firestore correctly.  Can you point me to docs that maybe explain what I am missing because this is only with checkbox or checkboxListTime I am having this issue.  You keep saying data is mapped so maybe there is something extra I am missing with that.  I thought that was the purpose of the ListView?

**Comment by hariprasadms** [comment]
Refer this please - https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/base-elements/checkboxlisttile You can find one for checkbox as well.

**Comment by blueprin4** [comment]
> Refer this please - https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/base-elements/checkboxlisttile You can find one for checkbox as well.

Yes those are what I have used before. I have tested on both iOS and Chrome and same results.

**Comment by blueprin4** [comment]
> I just checked your project, looks like there are no actions created for ListTile_Checbox actions. Check please.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/17435678/221912357-ce2cb693-3037-474e-afee-168e1e3567b0.png)
> 
>  

So two big questions. Nothing states for checkbox to check or uncheck it's need an action. Second how did you access my project?

**Comment by hariprasadms** [comment]
Hi @blueprin4 - I am from FlutterFlow team, The bug report code which you have shared earlier, we use that code to investigate the issues in the projects. Nothing to worry as we do not alter the projects configurations and data. Regarding no clear information about List tile checkbox actions, we are in the process of updating documents, we will take care of your observation. You can find more information about actions in FlutterFlow YouTube channel. Please have take a look. Thanks

**Comment by hariprasadms** [comment]
As it is related to missing actions configurations from user side, I am closing this bug. Thanks

**Comment by blueprin4** [comment]
I don't think you understand how the checkbox works as all examples docs never show checkbox needs action to work...It is a bug and I would think there would should be consent to open a project that has sensitive information like my stripe keys.  I was able to find that locate the problem and will open a new ticket since you prematurely closed this one.
