### ISSUE TITLE
Storyboard issue

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#548]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

<img width="1728" alt="Screenshot 2023-02-27 at 10 05 37 PM" src="https://user-images.githubusercontent.com/11810973/221768353-2535ff7e-e44a-47ee-8972-5b04356fffde.png">

This is what happens when I zoom into my storyboard

### Expected Behavior

N/A

### Steps To Reproduce

Check out https://app.flutterflow.io/project/washi-washi-ohqvq4

### Bug Report Code

N/A

### Context

N/A

### Environment

```markdown
- FlutterFlow version: Feb 27th
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hello, @DanielEdrisian - I just looked through your project. I don't see the issue while zooming in and out inside storyboard. Pages are loading good to me. I believe it was a server network issue at the time you trying to connect. I hope it is working fine now.

**Comment by aemelyanovff** [comment]
Seems to be working fine. @DanielEdrisian please reopen the issue if you still can reproduce it, and preferably add more details about how to reproduce it.
