### ISSUE TITLE
Language settings are not persistent

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#55]
## Expected behavior (required)
When the user selects a language it should be set when the user reopens the app.

## Current behavior (required)
The app reverts to English.

## To Reproduce (required)
1. Set up an additional language
2. Add language selection widget
3. Build app
4. Select language
5. close app 
6. open app and observe the language has reverted to English.7. 

I have multiple languages in my app. It's annoying for users to have to set language at every run.

## Screenshots / recordings
[Bug is described by other users in the community forum](https://community.flutterflow.io/c/discuss-and-get-help/dual-language)

Version of FlutterFlow used: 1.1.15
Platform (e.g. Web, MacOS Desktop): Android
Browser name and version: n/a
Operating system and version (desktop or mobile): Android 12

**Comment by organicnz** [comment]
Hi @ampapplarsen :) 
Could you pls add on which platform are you encountering this problem Crome or Desktop? 
Wouldn't it be difficult to make a small recording via Loom? 
Have you tried to add the Norwegian language to your app? I've seen some errors in auto-translate with Norwegian though. Maybe it caused the issue?

**Comment by ampapplarsen** [comment]
> Hi @ampapplarsen :)
> Could you pls add on which platform are you encountering this problem Crome or Desktop?
> Wouldn't it be difficult to make a small recording via Loom?
> Have you tried to add the Norwegian language to your app? I've seen some errors in auto-translate with Norwegian though. Maybe it caused the issue?

Thanks! I haven't added Norwegian (yet, coming up in the coming days), thanks for the heads-up on that.

This is in-production app downloaded from Google Play store on an Android phone.

Video https://photos.app.goo.gl/FuppuTNYceX4cFSA9

**Comment by bulgariamitko** [comment]
I never used this functionally of FF and I do not know how it is intended to work, but you can simply fix that by using a local state which will remember which language you choose. I am not use if you close the app and don't save this info someone where if it is FF response to remember which language was choose or it is the dev to store that somewhere. 
But never the less it is good practice to fill the whole information of the template.

**Comment by ampapplarsen** [comment]
> I never used this functionally of FF and I do not know how it is intended to work, but you can simply fix that by using a local state which will remember which language you choose. I am not use if you close the app and don't save this info someone where if it is FF response to remember which language was choose or it is the dev to store that somewhere.
> But never the less it is good practice to fill the whole information of the template.

Yeah, that's what I did but also, just hit the deploy button. I found a range of small issues related to language so decided to hold up and bring attention to them, so people after me have a smoother experience when these things are ironed out. In the day to day of things, at least I do, we tend to just plough ahead and fix things if possible. All these little issues combine to larger impressions, n'est pas?

**Comment by bulgariamitko** [comment]
Also please always include this information as well. So please add it so when FF team check this issue to know where it is coming from

Your environment
Version of FlutterFlow used: 
Platform (e.g. Web, MacOS Desktop): 
Browser name and version: 
Operating system and version (desktop or mobile):

**Comment by ampapplarsen** [comment]
> Also please always include this information as well. So please add it so when FF team check this issue to know where it is coming from
> 
> Your environment Version of FlutterFlow used: Platform (e.g. Web, MacOS Desktop): Browser name and version: Operating system and version (desktop or mobile):

Done!

**Comment by katherineqian** [comment]
Although this is not strictly a bug (the behavior is currently expected on the platform), the behavior can be confusing to users, so we can address this in an update to the language selector widget.

**Comment by ampapplarsen** [comment]
Thank you!

**Comment by organicnz** [comment]
> > Hi @ampapplarsen :)
> > Could you pls add on which platform are you encountering this problem Crome or Desktop?
> > Wouldn't it be difficult to make a small recording via Loom?
> > Have you tried to add the Norwegian language to your app? I've seen some errors in auto-translate with Norwegian though. Maybe it caused the issue?
> 
> Thanks! I haven't added Norwegian (yet, coming up in the coming days), thanks for the heads-up on that.
> 
> This is in-production app downloaded from Google Play store on an Android phone.
> 
> Video https://photos.app.goo.gl/FuppuTNYceX4cFSA9

Thanks you for the recording. Yeah, the language selector widget behaves that way, mate :)

**Comment by agreaves** [comment]
I'm labelling this as a feature request as opposed to a bug, but it is an excellent suggestion and we'll update the behavior soon to persist user's language selection.
