### ISSUE TITLE
API Call (POST) fails when executing

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#555]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Hi there. I have a simple API Call (POST) to connect to stripe. If I test the API in the FF section where I define the API, it works fine. If I add a API call from a Widget or from an Action, there seems to be a problem and it returns failure and status code 400. 

If I call another API method, if it is a GET method, it works fine! It just happens to the POST Calls. (I am using ContentType: application/x-www-form-urlencoded)

I am using secured API Calls, so I already checked that the ffcloud function is ok in terms of being able to be called by any signed/authenticated user.

Here are a few pics:

Here are a few printscr. I tried many options and only the GET calls work (either from an action or from a widget). And the POST calls do not work.
I have tried from a Test/Run instance as well as from a web instance.

### Expected Behavior

Calling the API Post method and getting a Success code and the proper response. 

### Steps To Reproduce

Create a call to a POST API, secure it, try it from the FF API's section and see it it works. Then, call the api method from a widget and check that it does not work.

### Bug Report Code

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMfWOdEket+EA0hfZDtBLATdczCbVVLYtfmS31DPmH+sEkfwvDpkd/1F+04YU+BUaZTzL5XQQ3jVlGhRcmpELqeW3ZBBeFmJ0yi0cHYnRFCNbBidEYk2mGuffCdG3qCf9qOYwx5e6fDbOY=

### Context

I need to create a Stripe Connected account. I am calling the API from the FF API's section and it works fine. It creates the account correctly. Initially I had parameters, but to isolate the problem, I changed the API Call to receive no parameters and hardcode the body params. That way, calling the API is just plain calling the api method. In that way, it cannot happen that trying the API call from the test section and it goes well but executing it from a widget it failed.

### Additional info

<img width="1244" alt="Captura de pantalla 2023-03-01 a la(s) 09 58 26" src="https://user-images.githubusercontent.com/50183743/222150014-b7f87a7d-1f3c-48dd-a1fc-b9da5c39fd85.png">
<img width="1246" alt="Captura de pantalla 2023-03-01 a la(s) 09 59 11" src="https://user-images.githubusercontent.com/50183743/222150018-c17b1936-6f8a-4f3d-ac8f-dfe46ef1ccfe.png">
<img width="1252" alt="Captura de pantalla 2023-03-01 a la(s) 09 59 24" src="https://user-images.githubusercontent.com/50183743/222150020-6b78800c-3297-467b-b25f-96b6ca93d832.png">
<img width="1250" alt="Captura de pantalla 2023-03-01 a la(s) 09 59 31" src="https://user-images.githubusercontent.com/50183743/222150022-d30e0afd-bcb3-4672-ab2f-c66d0f91041d.png">
<img width="1227" alt="Captura de pantalla 2023-03-01 a la(s) 09 59 39" src="https://user-images.githubusercontent.com/50183743/222150026-5d6224b2-f756-440e-924b-12cb9ccdbd4a.png">
<img width="464" alt="Captura de pantalla 2023-03-01 a la(s) 10 01 16" src="https://user-images.githubusercontent.com/50183743/222150708-1d2684f8-3011-4a82-ba6d-081deffbc8e1.png">
<img width="1351" alt="Captura de pantalla 2023-03-01 a la(s) 10 01 28" src="https://user-images.githubusercontent.com/50183743/222150713-9c9067d6-cd4c-4acb-ae3a-e20aaa7e2362.png">
<img width="1229" alt="Captura de pantalla 2023-03-01 a la(s) 10 00 21" src="https://user-images.githubusercontent.com/50183743/222150030-b2caa5bd-39c7-4d73-9347-4af211458aa6.png">
<img width="494" alt="Captura de pantalla 2023-03-01 a la(s) 10 01 45" src="https://user-images.githubusercontent.com/50183743/222150413-936654b5-ad6b-4cbb-a7c5-c297549213d8.png">

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by hariprasadms** [comment]
Hi @pstatile - Thanks for posting this issue. Can you please try the same steps with disabling private api call?
I think I have this issue sometime back where private api call requests was not going through build run. 

Please confirm the details.

**Comment by pstatile** [comment]
I could manage that in a Run/Test environment that it uses a proxy (although I would prefer it to work), BUT in web deployment if I have it Private, it does not work...

**Comment by pstatile** [comment]
> Hi @pstatile - Thanks for posting this issue. Can you please try the same steps with disabling private api call? I think I have this issue sometime back where private api call requests was not going through build run.
> 
> Please confirm the details.

Hi! I have provided the required information. Could you confirm if the status can be checked and accepted to resolve?
Thanks!

**Comment by pstatile** [comment]
Please DO see this issue! I have given all the instructions and required data but no response yet... Thanks

**Comment by pstatile** [comment]
Super appreciated! If not solved I am not being able to call POST Api calls in a secure way. Thanks!

**Comment by wenkaifan0720** [comment]
Hi @pstatile. Have you tried the new `Make Private` feature in API advanced settings?

**Comment by pstatile** [comment]
If I use the Make Private, that’s when it does not work. But as I am sending tokens I need it to be private. That does not happen with GET api calls. 
Let me know if you need any other type of test or information. 
Thanks. 
Pablo

>

**Comment by aemelyanovff** [comment]
@pstatile Thanks for reporting the issue, and sorry for the slow turnaround.

The issue will be fixed in the next update. You'll need to re-deploy the private API after that. I'll update the issue it's ready.

**Comment by aemelyanovff** [comment]
@pstatile The fix has been released. If you redeploy your private API it should work!

**Comment by pstatile** [comment]
Great I’ll try it

>

**Comment by pstatile** [comment]
Seems to be solved, thanks!
Paul
