### ISSUE TITLE
TEAMS: Unable to add users to a team in Flutterflow

### ISSUE THREAD

**Issue by alexrbrowne** [FlutterFlow/flutterflow-issues#556]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Summary: Users who have been added to a team in Flutterflow are unable to see the team's projects, even though they have been marked as "active" in the team.

Impact: This bug prevents team collaboration, as users who have been added to a team are unable to work on team projects.

Workaround: Currently, there is no known workaround for this issue.

### Expected Behavior

Expected Result: The new team member should be able to see the team's projects and have access to them.

Actual Result: The new team member is unable to see the team's projects and is unable to access them.

### Steps To Reproduce

1. Sign in to a free Flutterflow account.
2. Create a team and pay for 2 seats.
3. Add another free user as a team member.
4. Verify that the new team member is marked as "active" in the team.
5. Have the new team member log in to their account.

### Bug Report Code

unknown

### Context

Adding users to the team to have consolidated billing

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: MacOS
- Browser name and version: Chrome 110 & Safari 16.2
- Operating system and version affected: 13.1
```

**Comment by katherineqian** [comment]
Hi @alexrbrowne, can you go into any of your projects and retrieve a bug report code from there? This will help us assess the issue.

**Comment by GriffoDP** [comment]
Hi there,

Please find the code below. @alexrbrowne is my colleague.

IT4glPHluIlgoctH176IYO9avCMsHDI1R600sNobbxAjIoDoPJkUac/BQFdpTdSlSn9XKEWGkl8Bps7sufHfFPcEKSWuRbZ81pZUUg7zUXO/aouaEKWaXmtBHcBVGlSx3Im3pCZQG7JocX9g7GCqBuqvQhbZHY/6Zwh9f6PHaOI=

**Comment by katherineqian** [comment]
Hi, thanks very much for the update. I have made a manual update, so this should be fixed for your team -- please try it out and let me know if not. I think we are experiencing an outage that's causing this, so doubly appreciate the issue report. 

Please leave a comment if you are also experiencing this issue and we will rectify your team access.

**Comment by GriffoDP** [comment]
Thanks very much @katherineqian that seems to have done it :)
