### ISSUE TITLE
CORS Errors for logged Out Users in all API Requests

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#557]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

When i'm testing my app in the browser Test mode i'm getting CORS Errors on all API Requests (Google Cloud Functions, Google Maps Places API in custom widget etc.). I have to log in with a user AND refresh the app for it to work properly. But after that everything works.

### Expected Behavior

API request go through even if users are not logged in. 

### Steps To Reproduce

1. Create a API Request
2. Start App 
3. If logged in - log out
4. Check Chrome Dev Tools
5. CORS Error on Requests

### Bug Report Code

ITFTlcmB34hNodcF+KrqdcJslWQsCUMdXZIRmOtvewgjF774PIYiZs/STBJCUtSzaH4/AFKWhlMCpdKJiYSXUO4BHEiCGbpP/pF6UhPPbF2ibq3WEqWSQUZQGtxXfmK55Lak3CVQPfhZL0Y+20OAPO+URT6Cf9qOYwx5e6fDbOY=

### Context

-

### Additional info

![image](https://user-images.githubusercontent.com/120254395/222269428-f80c05d2-1d29-4433-a43e-220e775f860c.png)

### Environment

```markdown
- FlutterFlow version: FF v3.1 - Flutter 3.7.3
- Platform: MacOS Web
- Browser name and version: Version 110.0.5481.100 (Offizieller Build) (x86_64)
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by organicnz** [comment]
Hi @nicmohr25. Thanks for adding this issue 🙂

I couldn't reproduce the issue. Does it happen when you're on the singing in page?  :)

![image](https://user-images.githubusercontent.com/4765090/222385763-a9c9c7bb-c97a-49f8-9827-64156ed71dbe.png)

**Comment by nicmohr25** [comment]
Are you making an api call to generate the list view? 
Because thats when i get the CORS errors

**Comment by nicmohr25** [comment]
It doesnt matter on which page i am. When there is an API call to google maps or to my cloud functions i'm getting CORS errors when the user is not logged in

**Comment by nicmohr25** [comment]
I could solve the issue by myself. It seems like the error messages I received were misleading. We had an error in our cloud function which caused it to dump. Due to this, the console printed a 503 Server Error with a CORS-Error Notification. 
I don't know if that behavior is caused by the Google Cloud Function, Proxy, or FF.

Anyways, the Ticket can be closed. Thanks.

**Comment by organicnz** [comment]
Glad you've already resolved this issue, @nicmohr25 :)

Yeah, I'm using API calls to generate the list view :)
