### ISSUE TITLE
Supabase - data type Timestamp, Null allowed. Can not Update_row Set Field = null/eset/clear_data

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#558]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

supabase table --> timestamp field --> Null allowed

Fullterflow --> Update row --> Set field --> select date field --> There is no option to clear the date set in this field. 
Firebase has a document --> clear-data option. Similar options need to be provided in supabase integration. 

### Expected Behavior

Fullterflow --> Update row --> Set field --> (New options) Clear_Data/Reset_data/Null_data

### Steps To Reproduce

create supabase table with date field. Null allowed
try following
Update row --> Select date Field   --> Try to null this field

### Bug Report Code

if (widget.dealRow?.dealStatus == 'Verified')   FlutterFlowIconButton(     borderColor: Colors.transparent,     borderWidth: 1,     buttonSize: 40,     icon: Icon(       Icons.check_box_outline_blank,       color: FlutterFlowTheme.of(context).primaryBackground,       size: 20,     ),     showLoadingIndicator: true,     onPressed: () async {       _model.updateRowDealsStatusSalesLostToTheCompetition =           await DealsTable().update(         data: {           'deal_status': 'Sales lost to the competition',           'junk_date': supaSerialize<DateTime>(FFAppState().nullDate),           'sales_lost_date': supaSerialize<DateTime>(getCurrentTimestamp),           'booking_amount_received_date':               supaSerialize<DateTime>(FFAppState().nullDate),           'order_execution_started_date':               supaSerialize<DateTime>(FFAppState().nullDate),           'order_execution_completed_date':               supaSerialize<DateTime>(FFAppState().nullDate),           'full_final_payment_received_date':               supaSerialize<DateTime>(FFAppState().nullDate),           'case_closed_date': supaSerialize<DateTime>(FFAppState().nullDate),         },         matchingRows: (rows) => rows.eq(           'deal_id',           widget.dealRow?.dealId,         ),         returnRows: true,       );       Navigator.pop(context,           _model.updateRowDealsStatusSalesLostToTheCompetition?.first);       await Navigator.pushAndRemoveUntil(         context,         PageTransition(           type: PageTransitionType.fade,           duration: Duration(milliseconds: 0),           reverseDuration: Duration(milliseconds: 0),           child: DealPageWidget(             dealRow:                 _model.updateRowDealsStatusSalesLostToTheCompetition?.first,           ),         ),         (r) => false,       );       setState(() {});     },   )

### Context

I need to cancel/reset the date once the need is over. 

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.3
- Platform: window 10,
- Browser name and version: chrome latest
- Operating system and version affected: window 10
```

**Comment by organicnz** [comment]
Hi, @palmdeskApp. Thanks for adding this issue 🙂

Unfortunately, this is not yet supported only via API Calls, mate. I will add this as a feature request :)
