### ISSUE TITLE
uploaded File optionunable to test in Api

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#559]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

when creating an api which has uploaded file as a variable, then its unable to test it in FF, since add file option missing  
so all api respond as error.

![download (25)](https://user-images.githubusercontent.com/37708853/222415086-6090e0a3-b3f4-4f8c-bed1-f47d8ff1a149.png)
![download (24)](https://user-images.githubusercontent.com/37708853/222415095-d69a544f-aa3f-4e2e-bde1-de8e6f71d727.png)

### Expected Behavior

need an option to add files when testing api 

### Steps To Reproduce

1. create an api which has a variable as uploaded file
2. now try to test it 
3. there is no option to add file 

### Bug Report Code

unable to create bug report code since it is in api 

### Context

since its unable to test any api with  files. its really hard to set json paths  

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:web
- Browser name and version:Version 110.0.5481.178 (Official Build) (64-bit)
- Operating system and version affected:win 10 pro
```

**Comment by hariprasadms** [comment]
@padeepz - Thanks for reporting this issue. It is sounds like feature request. Hence I have marked it as feature request. Meanwhile, can you please add more details about, how you can test this, postman or soupUI kind of applications. so that it helps dev team to visualize the problem around here. Thanks

**Comment by padeepz** [comment]
@hariprasadms hi . the reason i added this as bug because without that feature the response throws error. and unable to proceed it in FF. i have to go external services to map variables. 
kindly reconsider the tag as bug.

**Comment by shelpert** [comment]
Hello,

I agree that this is a feature request, as we don't currently support testing multipart API calls with files in the Response and Test section of the API call configuration. However, you should still be able to test and debug this functionality in test mode! I will close this issue as a feature request and raise it with the team.
