### ISSUE TITLE
WebP images don't upload

### ISSUE THREAD

**Issue by abdrzq16** [FlutterFlow/flutterflow-issues#561]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Failed to upload WebP images on project media tab, but it works when uploading it from image element.

### Expected Behavior

Upload WebP images through project media tap.

### Steps To Reproduce

Go to project media page.
Click "Upload media" button.
Choose WebP image.
Hit Ok.

### Bug Report Code

ITESz/Hqx89grtte7ZPqd/p6hR8mJjsnU+crhOthexEYIZjpPbAXbuvRXG5WOM+7dH9LfFmJvFwF0fvFifPfKMddFyyEQ5RnypAJTg/ifz+6V66gCYeOeXNPJ+lYFWLC0Z+FgxZDKrNaZUEuig/GSw==

### Context

Not able to bulk upload images. I have to upload them one by one from image element.

### Additional info

![111](https://user-images.githubusercontent.com/108595330/222444044-67008f76-5f23-4356-a6bc-68497291ef28.jpg)

### Environment

```markdown
- FlutterFlow version:  3.1
- Platform: web. Windows
- Browser name and version:Firefox
- Operating system and version affected: win 10
```

**Comment by hariprasadms** [comment]
Hi @abdrzq16 - Thanks for reporting this issue. I can re-produce the issue.

**Comment by abdrzq16** [comment]
Hi @hariprasadms. is there any news on this issue.

**Comment by agreaves** [comment]
Hi @abdrzq16, thank you for the bug report! You are correct, we were incorrectly not allowing WebP images in the media tab. This will be fixed in the upcoming release! 🙂

**Comment by abdrzq16** [comment]
Hi Agreaves.

Thank you for your response.

I hope you take a look at this one.

https://github.com/FlutterFlow/flutterflow-issues/issues/522

Regards.
