### ISSUE TITLE
Snack Bar not shown over Bottom Sheet

### ISSUE THREAD

**Issue by Krystian95** [FlutterFlow/flutterflow-issues#563]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

The Snack Bar is not shown over an opened Bottom Sheet, but only when the Bottom Sheet has been closed.

### Expected Behavior

The Snack Bar should be shown over Bottom Sheet, instead.

### Steps To Reproduce

1. Create an empty page that show a Bottom Sheet
2. Inside the Bottom Sheet, add a button to show a Snack Bar when pressed

### Bug Report Code

IT4whvHl05dJtbxK0KX6cfpviiovIjo1R+cnmOwaTis8JJToPLAUZ8zBM05vZr3gTUFEMWaJ/Xk1xvfqveHXV/QCBAqrfpxH+KpUVwrdfH2jb7nWDZGNfW1SP9xmI2q00qun2RB+OuNvS3gM6mGHfO+uQjffJb7uOm0GAOaLKdeK2SrDX1iXc2URm05KZDPz

### Context

I need to show alerts when user try to add an employee, for example when the counter is equal to zero a snack bar will advise the user to increment the counter first. Or for example if the user has already add the maximum employees allowed by the counter.

### Additional info

https://user-images.githubusercontent.com/24765669/222469729-93a7de7d-adbf-403a-b2c7-d54b345adf03.mov

![Screenshot 2023-03-02 alle 16 00 01](https://user-images.githubusercontent.com/24765669/222467689-f91d107b-f5ea-4ca2-9485-5b9579ff8ee5.png)

### Environment

```markdown
- FlutterFlow version: 1.1.47
- Platform: MacOS Desktop
- Browser name and version: Chrome v. 110.0.5481.177
- Operating system and version affected: macOS 13.1 (22C65)
```

**Comment by hariprasadms** [comment]
Hi @Krystian95 - Thanks for reporting this issue. 

Snackbar widgets displays based on for which scaffold it is attached to. At present in FlutterFlow(as standard), Snackbar widgets are attached to page scaffold. It is working as expected. It is not a bug. 

I would suggest you can use alert dialogue widgets instead snack-bar. I can mark this issue as feature request. I hope this can help you.

**Comment by Krystian95** [comment]
> Hi @Krystian95 - Thanks for reporting this issue.
> 
> Snackbar widgets displays based on for which scaffold it is attached to. At present in FlutterFlow(as standard), Snackbar widgets are attached to page scaffold. It is working as expected. It is not a bug.
> 
> I would suggest you can use alert dialogue widgets instead snack-bar. I can mark this issue as feature request. I hope this can help you.

Many thanks! Great! 🙂

**Comment by Golicraft** [comment]
That's not an ideal solution. I use bottom sheet for Auth login/register and when an error accours within Firebase it shows a snackbar below the bottom sheet. I'm surprised this hasn't been working more on ... What about when a snackbar comes it moves the bottom sheet up so the snackbar is below? Just a thought.

**Comment by Golicraft** [comment]
> That's not an ideal solution. I use bottom sheet for Auth login/register and when an error accours within Firebase it shows a snackbar below the bottom sheet. I'm surprised this hasn't been working more on ... What about when a snackbar comes it moves the bottom sheet up so the snackbar is below? Just a thought.

I'm so surprised this issue with Firebase error messages has not yet been addressed and fixed. When you use Bottom Sheet as the login component and insert for example the wrong password you won't be shown any error message because it's hidden UNDER the bottom sheet. THIS NEEDS TO BE FIXED?

**Comment by krystian-dev548** [comment]
Please solve this 🙏
