### ISSUE TITLE
During theme Setup So much flicker issue 

### ISSUE THREAD

**Issue by prashantdwivedi** [FlutterFlow/flutterflow-issues#566]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Please see the video I recorded 
https://cln.sh/pvTXt3DN.

you see, I refresh the browser as well
still, that issue shows 

### Expected Behavior

Take too many graphics during work, and that flickering issue is not able to work.

### Steps To Reproduce

During theme setup

### Bug Report Code

there is not Widget bug

### Context

Take too many graphics during work, and that flickering issue is not able to work.

### Environment

```markdown
- FlutterFlow version: Last which
- Platform: v3.1 - Flutter 3.7.3
- Browser name and version: Version 110.0.5481.177 (Official Build) (arm64)
- Operating system and version affected: Macbook Pro M2 Max macOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @prashantdwivedi - This issue we are not able to re-produce. As we seen earlier, this flickering issue mostly related to browser. Please close all the browser instance and re-open FF editor in a new browser instance. It can solve the issue.
