### ISSUE TITLE
TEAMS: "Project in use" when multiple team members trying to edit a project

### ISSUE THREAD

**Issue by GriffoDP** [FlutterFlow/flutterflow-issues#568]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Summary: Users who have been added to a team in FlutterFlow are unable to simultaneously have a project open. That project been shared via Collaboration-> Organization Sharing.

Impact: This bug is preventing team collaboration as team members are unable to work on team projects together.

Workaround: Currently, there is no known workaround for this issue.

### Expected Behavior

Expected Result: The team members can simultaneously have a project open where that project is shared with the organization.

Actual result: The team members are unable to simultaneously have the project open.

### Steps To Reproduce

1. Two Team members sign into FlutterFlow and are present in Dashboard->My Organization-> Team Members as Owner and Active
2. Both Team members open the same project
3. After ~ a minute the pop-up "Project in use" appears, with "Go to Teams" and "Return Home" as the only options

### Bug Report Code

IT8klMjc4otPxd9Y7c/LbcFVmiksQlw2bIZMidVxbwodCOPpEoYlduCkPxBuWMyAewlAIVmjkn0y08rZkt79GsA3Ewyuc49q3btuZA//VmGgVpfXC6rhVUZ7P/NUC3Kc1Kun3Ax9G/p0R1YGwF2qJOqtVgDXCYDPDkUCR/ihC974olKaGB3jMiJv0iZecCfn

### Context

Attempting to collaborate on a project in order to deliver.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Windows & MasOC
- Browser name and version: Chrome 110 & Safari 16.2
- Operating system and version affected: Windows 10 & MacOS 13.1
```

**Comment by alexrbrowne** [comment]
This is very frustrating

**Comment by agreaves** [comment]
Hey @GriffoDP and @alexrbrowne, sorry for this issue and thank you for the report! I've identified the problem and fixed it for your specific case, but we're working on a broader fix so I'll leave this issue open until then.

**Comment by GriffoDP** [comment]
Hey @agreaves thanks very much for the prompt fix. We'll test shortly.

**Comment by agreaves** [comment]
Broader fix has been applied! Please let me know if you still encounter any issues.
