### ISSUE TITLE
Widget tree jumps by itself issue #40 is back again.  Please stop moving the tree around.

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#57]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The widget tree should not move by itself if the selected widget is visible.

## Current behavior (required)

When a visible widget is selected,  the tree view automatically scrolls up to show the selected widget at the top of the screen.   This should not happen.   When working with complex layouts the relative position of the widgets in the tree is an important context that must be under the designer's control at all times.  PLEASE, PLEASE, PLEASE stop moving it around.   Let the user  completely control the tree view scrolling and which node is expanded and which is collapsed.   Any kind of automatic movement breaks the context and forces the user to require their focus in the tree.  This is very disrupting.

The ONLY EXCEPTION to this is when a widget is not visible in the tree and is selected on the canvas.  In that case it would be helpful for the tree to automatically scroll to show it at the top.   Otherwise the tree should stay put where the user put it.

## To Reproduce (required)

1.
2.
3.
4.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by Pepino-GR** [comment]
I can't reproduce this issue with FlutterFlow v3.0 October 25, 2022 Flutter 3.3.4.

**Comment by KirilOkun** [comment]
@Pepino-GR    Open a page with a long widget tree.  Pick a widget and scroll the tree so that widget is visible at the bottom of the tree.  Then select that widget in the canvas.  The tree jumps to show that widget at the too of the tree.  That shouldn't happen.  If a widget is visible in the tree it's selection should not scroll the tree.

**Comment by KirilOkun** [comment]
I'm thinking of the widget tree as the file outline in visual studio code.  It represents the structural context of the page, its map.   It should not jump around.

**Comment by bulgariamitko** [comment]
If you mean jumping the widget tree when you click on an item on the actual page - this is normal behaviour. The idea is that whatever you are selected on the left side is also selected on the right side and visa versa. If this is your problem I don't consider this as an issue.

**Comment by KirilOkun** [comment]
the problem is that the tree jumps when a selection is made.  it should not.  if a widget is visible in the tree and it's selected on the work canvas the tree should not move.  just like bug #40 it disrupts the users context.   when i'm working on a complex layout i need to see the structure of widgets concurrently with how they look on the page and their properties.   if a tree scrolls automatically to place the selected widget at the top every time i make a selection in the canvas my structural context is disrupted.  there's no benefit to this scrolling and it makes working with the tool extremely frustrating.   

imagine that while you are coding your IDE keeps scrolling by itself so you constantly have to find your place in the file.   that's what's happening now.  take it from somebody who has been spending hours with FF on a daily basis.   this scrolling is a bug and not a feature.  if you want to keep it then please allow the user to turn that synced selection off.  let me control what i see in the widget tree.

**Comment by KirilOkun** [comment]
And lastly.  The current auto-scrolling behavior is not consistent.  It jumps sometimes but not always.   Often when a widget that's not visible in the tree is selected on the canvas but the tree does not auto-scroll to show it.   So it's the worst of both worlds.  It jumps around when it shouldn't and doesn't when it should.  But only sometimes.  So one never knows what to expect.

**Comment by KirilOkun** [comment]
@agreaves    I strongly disagree with the low priority evaluation on this.  And as daily user of FF mine is an informed perspective.     
 
 Just tried the latest release and the same inconsistent tree auto-scrolling behavior is present.   Tree sometimes scrolls to the selected widget but often it does not.  And when it does scroll it repositions the tree so the selected widget is at the top thus hiding it's parent(s) which are important when working on a complex layout.   
 
 The current selection sync / auto scrolling does not work.  It's buggy and makes FF less productive.  I waste a lot of time looking for my place in the tree.  Over the course of a work day it adds up in wasted time and accumulated frustration.   A simple solution is to allow a user to turn it off completely.

**Comment by agreaves** [comment]
Hi @KirilOkun, typically priority is given to bugs that break / negatively impact users's apps, or major issues that prevent people from being able to build. My understanding is that your issue is primarily that the widget tree scrolling behavior is a frustrating UX. Although this is a completely valid point, this UX has been around for quite some time and is not an active or recent bug (for which we reserve higher priority issues). I hope that makes sense.

That being said, it's not a difficult change on our end so I don't expect you'll have to too long for an update.

**Comment by KirilOkun** [comment]
@agreaves    Fair enough.  End users always come first.

**Comment by agreaves** [comment]
The option to turn off scrolling has now been added! Simply click or un-click the lock icon on the widget tree.
