### ISSUE TITLE
Github Push Fails

### ISSUE THREAD

**Issue by alexrbrowne** [FlutterFlow/flutterflow-issues#572]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

After installing the flutterflow github app and providing access to the repo, I linked the repo in the field 'full repository url' and then pushed 'Push to Repository'. Unfortunately it failed with a non-descriptive error message. 

<img width="614" alt="Screenshot 2023-03-04 at 11 45 29" src="https://user-images.githubusercontent.com/61184813/222898689-2d2d64cd-842e-4102-ad36-dd506e56eb88.png">

### Expected Behavior

After successfully linking to the github repo, pressing the button should push the latest code to the main branch. 

### Steps To Reproduce

1. create a new repo in github, with a README & an a dart .gitignore
2. add the flutterflow github app
3. configure the github app to have access to the new repo
4. add the full url for the github repo into flutterflow
5. press 'push to repository'

### Bug Report Code

unknown

### Context

Attempting to add code to a fresh repo

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: macOS
- Browser name and version: Chrome 110.0.5481.177
- Operating system and version affected: macOS Ventura 13.1
```

**Comment by alexrbrowne** [comment]
FYI @GriffoDP

**Comment by alexrbrowne** [comment]
As an update, I removed all the files from the repo so that main was empty, still no joy.

**Comment by hariprasadms** [comment]
Hi @alexrbrowne - I just tested the Github push. It is working fine.

![image](https://user-images.githubusercontent.com/17435678/223108422-e2bcc4fa-b86e-4670-8709-4f7d4d937f05.png)

Before pushing code from FF to Git at first time, repository should be initiated. I hope you have done as below explained.

![image](https://user-images.githubusercontent.com/17435678/223109273-d494321a-34d0-42a8-9876-edf8721d5a0f.png)
