### ISSUE TITLE
Supabase Join statements

### ISSUE THREAD

**Issue by dhurbhat** [FlutterFlow/flutterflow-issues#573]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

No way to issue a Supabase Join Statement on a page.

### Expected Behavior

While DB Schema update is handled well in FF, there is no mechanism to do a SQL JOIN on a page via Supabase Query.

For example, if I have a page that is rendering data from related items, one would have to either create a ReadOnly View in Supabase and then update schema in FF and then use that "table" in Supabase Query or revert to something more complex.

### Steps To Reproduce

1. Create a new Page
2. Define Supabase schema with two tables - tons of examples on the internet
3. Build a page that requires a Join

### Bug Report Code

NONE

### Context

Been stuck on an issue with FF automatically (since the past 3 releases) makes a Primary key on a ReadOnly View Table as Dart nullable... when in fact the field is a PRIMARY KEY.  This is wrong.
Builds in FF consistently fails - and I have to resort to building in Android Code.  

### Environment

```markdown
- FlutterFlow version: v3.1 Flutter 3.7.3
- Platform: MacOS
- Browser name and version:Chrome 110.0.5481.177 (Official Build) (arm64)
- Operating system and version affected: N/A
```

**Comment by hariprasadms** [comment]
Hi @dhurbhat - We recommend that data logics such as joins and etc to keep at the supabase level. Supabase views are the most powerful for fetching data depending on data presentation needs. I would recommend explore more options around views idea.

I can, however, mark this as a feature request. Based on priority visits, the FF team will improve the usability and functionalities around supabase integration in future updates. As a result, this point can be visited before deciding on the appropriate status.

Thanks
