### ISSUE TITLE
Mongodb Atlas Data API works for /find but not works for UpdateOne or InsertOne methods

### ISSUE THREAD

**Issue by DrigoDomingos** [FlutterFlow/flutterflow-issues#58]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Current behavior (required)

Create an api connection to CRUD MongoDB Atlas Data API. It works to read a collection and parse it to a list in FF, but its not working to update or insert a new document. Even including the Header and authentication, it's still showing this message: ("Header missing: please add content-type: application/json or application/ejson to specify payload data types")

## To Reproduce (required)

1. Create API using post method
2. Create a free account on Mongo Atlas 
3. set API URL (https://data.mongodb-api.com/app/XXXXXXXX/endpoint/xxxxxx/v1/action/updateOne)
4. set header, api-key, body
5. Test API

1.
2.
3.
4.

## Context (required)

I'm trying to CRUD MongoDB atlas throught Data API feature using FF. I'm able to run all the codes using postman. Not that On Mongo Atlas I can validate the connection was stablished but the update or insert is not performed.

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/5956222/198099160-9beef993-ed68-4ca1-a269-11ff16060127.png)

![image](https://user-images.githubusercontent.com/5956222/198099340-6f72cbf5-353f-42e6-8596-8ab9215dac59.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3,3,4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile):Desktop

**Comment by Pepino-GR** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/) for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by Pepino-GR** [comment]
I can reproduce the issue. It seems to be an issue with the header handling

**Comment by agreaves** [comment]
Hi @DrigoDomingos, this was a strange one. It seems that the MongoDB API requires the body to be encoded in bytes in order for the call to succeed, though they never specify this. The error response it gives currently about headers is actually a red herring, and honestly it seems like a bug on MongoDBs side.

Nevertheless, in our next release we're adding an option in Advanced Settings to "Encode Body as UTF-8 Bytes" which does what it implies and should fix this problem if you switch that toggle on! Thanks for the bug report!

**Comment by 89286-Ankita** [comment]
"I'm working in FlutterFlow using the free version, and I need to send key-value pairs in a multipart body. However, even after selecting 'Multipart' in the Body tab, FlutterFlow still forces the header to 'Content-Type: application/json' and doesn't allow me to properly set or send key-value parameters."
