### ISSUE TITLE
Trigger Push Notification Action not working

### ISSUE THREAD

**Issue by CODENESS-pl** [FlutterFlow/flutterflow-issues#580]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When Trigger Push Notification Action is added, notifications are not delivered to the specified user reference.

I'll just add that when chatting or sending a test notification in the Push Notification settings - everything works fine

### Expected Behavior

After adding the Trigger Push Notification Action, notifications should be delivered to the specified user reference 

### Steps To Reproduce

For example: 

1. create a button
2. add to Trigger Push Notification Action with given user reference and Lorem ipsum text
3. close edit action
4. click on the button 

A notification should be delivered to user, but unfortunately it doesn't work

### Bug Report Code

Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null)

### Context

I want to send notifications to users when they click on a button

### Environment

```markdown
- FlutterFlow version: Flutterflow v3.1 released March 2, 2023
- Platform: MacOS Desktop or MacOS Safari
- Browser name and version: MacOS Safari 
- Operating system and version affected: macOS Ventura 13.0
```

**Comment by CODENESS-pl** [comment]
Hi, at 7:00 pm (GMT + 01:00) I received a notification - if your developer was testing this project at that time, something worked

**Comment by agreaves** [comment]
Hi @CODENESS-pl, thank you for the bug report! We do not test user's projects without explicit permission, so the notification did not come from us.

In fact, we do not at the moment have the necessary information to begin debugging. Would you mind trying to generate the bug report code? It sounds like you don't have Clipboard permissions enabled, make sure to enable these before trying again (if you're using Chrome you can [access permissions here](chrome://settings/content/clipboard)).

**Comment by CODENESS-pl** [comment]
Hi, I don't know how, what it is due to, but for some reason it started working today. 

I'm analyzing what was the reason, maybe it's a rules firestore acutalization, or maybe something else. But the notifications are working. 

Issue to be closed.

**Comment by agreaves** [comment]
Ok sounds good, thanks for the update!
