### ISSUE TITLE
Revenue Cat not working anymore (might be due to the Price Tag)

### ISSUE THREAD

**Issue by Nokthed** [FlutterFlow/flutterflow-issues#581]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Price String of Revenue Cat on FF always returns a null value despite the correct configuration of Revenue Cat, which brings the red screen of death or grey screen on APKs.

### Expected Behavior

It should show the Price Tag of the current entitlement.

### Steps To Reproduce

1. Define a paywall action with the right entitlement
2. Place a text and set its value to Revenue Cat's Price Tag: any setting should not be working.
3. Try running or building the project: you'll either get a red or a grey screen depending.

### Bug Report Code

ITFflcjf35dIseEC7a6IK/kw+Ck7Qm0cTYMvjuphcx43fYjzELAcOuD7U0NKTbC5emxUJlebmjoz0vfFhvLLKMcDE0uab6pB0JVAQz3zTmCVaZCLPbuzPn8kL8dQFUic08KGkCRACMF2cng47ziLNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I was simply trying to show the Price Tag of the current Revenue Cat entitlement but it doesn't seem to work anymore. It worked correctly a few weeks back but doesn't anymore as of today, despite having not touched anything since then.
This issue is extremely bothering, since it shows a grey or red screen whenever I try to access a page or widget with Revenue Cat, hence making the project unusable and unworkable on.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 110.0.5481.178
- Operating system and version affected: Windows 11 22H2
```

**Comment by bulgariamitko** [comment]
Are you sure the price is not null

**Comment by Nokthed** [comment]
> Are you sure the price is not null

Yes, I'm totally sure. Everything was working fine until recently, I didn't change anything and double checked everything.

**Comment by Nokthed** [comment]
Thanks @bulgariamitko. Not to bother or sound impatient, but any idea how long it could take before a fix? This is unfortunately blocking the project as it is right now. :/

**Comment by bulgariamitko** [comment]
@hariprasadms , this is a question for you :)

**Comment by Nokthed** [comment]
Did lots of testings the last few days: not due to the Price Tag. The whole thing isn't working.

**Comment by aemelyanovff** [comment]
@Nokthed Sorry for the slow turnaround.

It looks like you use incorrect package identifier: try `$rc_monthly` instead of `premium`. Also it would be safer to use a package option from the list rather then get package by identifier, like this:

![Screenshot 2023-04-05 at 11 30 48 AM](https://user-images.githubusercontent.com/92294640/230130216-4279550d-feec-4d95-9064-0db8143fdc02.png)
