### ISSUE TITLE
Deeplink is not working when dynamic link is enabled.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#582]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Deep link is not working as expected.

It is clearly stated like below that you can use Deep link together with Dynamic link.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/5080329/223478565-788de449-85ac-44ad-b92b-4903d1ee235d.png">

But it's not working as stated.

### Expected Behavior

When the deep link is triggered (click, tap), the app should be opened as expected.

For instance, if the scheme is abc, then `abc://abc.page.link` would open the app.

### Steps To Reproduce

1. Enable the Dynamic Link
2. Use Deep link
3. And the deep link is not working.

### Bug Report Code

IT4kkM7qy5Ngrt9Y1rrLbcdF9T47G0QmTL07ttYbZxUjIuPtBJh+O8+kVFZpXsfmSmlhHGCWoHMFpfzwkd7DOO5eGyqWRYB4+LhiVg7yUXq8R4TRCaWzOX8mBeBgGUCu0cGnvyNAKbd2LlYS61z7HOqXFzLXCZ+/Zwh9f6PHaOI=

### Context

I enabled the Dynamic link. and I want to use the Deep link also.

But the deep link is not working due to the missing scheme in AndriodManifest.xml and Info.plist.

### Additional info

When you use the Deep link alone (without dynamic link), you will get the scheme for the Deep link in android/src/main/AndroidManifest.xml and ios/Runner/Info.plist like below.

Android)
```
<!-- Deep linking -->
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="hypetalk" android:host="hypetalk.page.link" />
</intent-filter>
```

iOS)
```
<dict>
<key>CFBundleTypeRole</key>
<string>Editor</string>
<key>CFBundleURLName</key>
<string>hypetalk.page.link</string>
<key>CFBundleURLSchemes</key>
<array>
<string>hypetalk</string>
</array>
</dict>
```

But when you enable the Dynamic link, these are gone and the Deep link is not working.

It is stated in FF -> Settings -> General -> App Details -> Deep Linking & Routing -> URL Scheme ( ** Hint **), that you can use the same Deep link URL scheme.

Please attach the proper schemes for Android and iOS even if the Dynamic link is enabled.

### Environment

```markdown
- FlutterFlow version: 3.1 release March 3, 2023.
- Platform: MacOS
- Browser name and version: Chrome Version 110.0.5481.177 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.0.1
```

**Comment by agreaves** [comment]
Hi @thruthesky, thanks for the bug report! At the moment, we only support one of either deep linking or Firebase Dynamic links. The URL scheme in the App Details page should be the Firebase Dynamic links path if it is enabled, hence why we don't include the deep linking scheme.

Closing this as a feature request for now, however the good news is that we will in the near future allow users to configure their `AndroidManifest.xml` and `Info.plist` which means you can apply this change yourself if you need both to work. Thanks again for the report!

**Comment by thruthesky** [comment]
Wow. If we can edit AndroidManifest.xml & Info.plist, we could do a lot more ~~
