### ISSUE TITLE
Project fails to load on web

### ISSUE THREAD

**Issue by ross-anibles** [FlutterFlow/flutterflow-issues#583]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attempting to load my web project results in a grey screen and the following errors:

**Chrome**
NoSuchMethodError: method not found: 'w' on null

**Safari**
[Error] TypeError: K[L] is not a function. (In 'K[L](R)', 'K[L]' is null)
	(anonymous function) (platform.js:46:172)
	Global Code (cb=gapi.loaded_0:1)

NoSuchMethodError: method not found: 'w' on null

**Firefox**
NoSuchMethodError: $.Q0 is null

### Expected Behavior

I expect the project to load as it does in test mode.

### Steps To Reproduce

1. Attempt to load https://wildya.flutterflow.app/home in any browser

### Bug Report Code

https://wildya.flutterflow.app/home

### Context

I can no longer view my project via web publishing

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 110.0.5481.177 (Official Build) (x86_64)
- Operating system and version affected: MacOS 13.0 (22A380)
```

**Comment by ross-anibles** [comment]
Hi @hariprasadms if you see the attached image carousel, swipe to the end and tap the button, then you should see the issue.
![Screenshot 2023-03-08 at 19 16 51](https://user-images.githubusercontent.com/126021151/223819030-7ba71f89-2ab7-460a-a66c-7e3661190397.png)

If you see something else, can you please send a screenshot?

**Comment by hariprasadms** [comment]
Hi @ross-anibles - Not sure what is the data source for this app. Looks like it is related to data binding to the page. Some where your api ( if you have used apis to bind the data ) request, not loading the data. Hence you can see grey page. 

This issue should be related to data configuration. Looks like this is not a bug.

I can see below error when scroll to end.

![image](https://user-images.githubusercontent.com/17435678/224288661-0b05a728-a38d-4b5d-8e84-226dab7e2e3c.png)

**Comment by ross-anibles** [comment]
Hi @hariprasadms.
The data source is Firebase, and I have no API connections.
Also, it works fine when using test mode, just not when published to web, so I don't think it's a config issue on my side.

Bug report code: IT4ozMrl8ZRJochE1q6JK+9ajSQsQmU1Rp0r0cpBZywgfZzzBLN/fPfQP1VoTearSgl+fWKcp14CwtLphuGSOMY7AxSqfKJEyJdyTw7iTT65MMiTF7m8ZXElJ9pWGX6FyKWvuxIlVchpSmQk2mC6e++UYATsJLrsPUQ4Sq/LZO4=

**Comment by ross-anibles** [comment]
Hi @hariprasadms, any movement on this?
