### ISSUE TITLE
Refresh FF button doesn't work on desktop app

### ISSUE THREAD

**Issue by katherineqian** [FlutterFlow/flutterflow-issues#585]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After a while, the "It looks like you've had this tab open for a while. Please refresh the page to get the latest version of FlutterFlow 😊." dialog pops up, with a Refresh button under it. However, clicking on the button does not do anything.

### Expected Behavior

I expect the dialog to be closed.

### Steps To Reproduce

1. Leave FF desktop app open for multiple days (?)
2. Observe the refresh dialog
3. Attempt to press refresh
4. Observe that nothing happens

### Bug Report Code

User reported bug to FF team

### Context

Users cannot keep working on desktop app without quitting and restarting

### Additional info

![Screen Shot 2023-03-08 at 11 06 19 AM](https://user-images.githubusercontent.com/21981137/223780859-ade03908-7467-4da1-b67e-988afc4ce09f.png)

### Environment

```markdown
- FlutterFlow version: 1.1.45
- Platform: Mac desktop
- Browser name and version: N/A
- Operating system and version affected: Unknown
```

**Comment by victoriahuang1** [comment]
@aemelyanovff would have more context on this -- related to the TODO left [here](https://github.com/FlutterFlow/flutterflow/pull/280/files#diff-108b4b25e09a8d734767f0954b5c8017662a016d52673f606de051c29b19f6c8).

**Comment by HeikoKanzler** [comment]
Happened to me last week. I left FF open for a couple of hours and got prompted with this screen. Button didn't work. Had to close the project and re-open again.

**Comment by victoriahuang1** [comment]
The fix should be coming out with the next deploy!
