### ISSUE TITLE
16.3.1 iOS issues and Application keeps getting rejected 

### ISSUE THREAD

**Issue by timmy1982** [FlutterFlow/flutterflow-issues#588]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

this if from apple during submission 

The issues we previously identified still need your attention.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 

Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app. Specifically, no action occurred after tapping on “submit” with a query. Also, app continually displayed “ad loading” message with no ads. Please review the details below and complete the next steps. 

Review device details:

- Device type: iPad and iPhone 
- OS version: iOS 16.3.1

Next Steps

Please run your app on a device to reproduce the issues, then revise and submit your app for review. If at first you're unable to reproduce the issue, try the following: 

- For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce. 
- For app updates, install the new version as an update to the previous version, then follow the steps to reproduce.

If we misunderstood the intended behavior of your app, please reply to this message in App Store Connect to provide information on how these features were intended to work.

### Expected Behavior

The expected behavior for the app is that it should display a bottom sheet with the query when run on Android and older versions of iPhone. However, on iOS version 16.3.1, the app fails to display the bottom sheet. Unfortunately, I was unable to troubleshoot the issue on Xcode as I do not have access to a 16.3.1 simulator at the moment.

### Steps To Reproduce

1. Test in android studio 
2. running on a mac using ios simulator 
3. test function and ads 
4. build runner into xcode project 
5. deploy onto Apple 
6. Apple rejects due to 16.3.1 incompatibility 

### Bug Report Code

there is no bug report

### Context

I have multiple people ready to use this on apple and I cannot get this to go live until fixed. 

### Additional info

the bug seems to be affecting only a few users out of the 100 who are running iOS 16.3.1. As I do not have access to an iOS 16.3.1 simulator to replicate and troubleshoot the issue, I would appreciate guidance on how to proceed with addressing the bug for these specific users.

### Environment

```markdown
- FlutterFlow version: v3.1 
- Platform: MacOS Desktop (android studio(mac and PC), XCODE (MAC)
- Browser name and version: chrome, brave 
- Operating system and version affected: N/A
```

**Comment by hariprasadms** [comment]
Hi @timmy1982 - This is not related to FlutterFlow issues. This is more related to testing your app as per app store approval requirements. I would suggest test your app in guide line with app store approval requirement before submitting for approval. 

As it is not related to project issues, we are closing this issue.
