### ISSUE TITLE
DataTable widget not working with api json result

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#589]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Have a Rest api call returning json with some columns and rows
try to show in FF DataTable widget and fail with this err:
<img width="344" alt="FF-DataTable-issue-one-column" src="https://user-images.githubusercontent.com/1261851/224033508-0ea21472-ca75-44ba-89c1-321ba62498cb.png">

### Expected Behavior

Expected behavior is to see my data !

### Steps To Reproduce

1. create a page with DataView widget
2. set a custom api with some data, like firebase example here: https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/base-elements/datatable
3. connect DataTable to this api & create children
4. set DataTable columns
5. Run app and see the error

### Bug Report Code

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs8JIj2OpkAWvTBTFFWXL3mYFZmP1mkhng1/Pfqk/LXOvo5AzKeUa5mysxUawn/UT+WeJCLC7qvfW1QFp9hf2Ky1p2zpSRBBOteR0Ihw2GIIvDLVhXaJpO3CzEnDfKlKdeK2SrDX1iXc2URm05KZDPz

### Context

this widget does'nt works!
more info here: https://community.flutterflow.io/c/bugs/datatable

### Additional info

Looking source code i see data_table_2: 2.3.10 , this version is not compatible with Flutter 3.7.3 used in FF 3.1 !!!
https://pub.dev/packages/data_table_2/changelog

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: MacOS
- Browser name and version: Chrome 111.0.5563.64 
- Operating system and version affected: iOS 16 and Browser web app running in test & run mode !
```

**Comment by organicnz** [comment]
Hi, @blondie63. Thanks, Mauro for adding this issue 🙂

I can confirm the issue.

![image](https://user-images.githubusercontent.com/4765090/224545532-e65ee8e1-01f7-4d61-b161-cad054811365.png)

![image](https://user-images.githubusercontent.com/4765090/224545539-ef15de48-3bbc-41f5-bd3e-a5f10a6756d4.png)

**Comment by agreaves** [comment]
Hi @blondie63, thank you for the bug report! We've identified the issue and the fix will be available in our next release 🙂. Sorry for any inconvenience!

**Comment by blondie63** [comment]
> Hi @blondie63, thank you for the bug report! We've identified the issue and the fix will be available in our next release 🙂. Sorry for any inconvenience!

Yesterday March 13th you announced the new version that had actually already been released a few days before but the worst thing is that you didn't insert the fixes for the bugs reported by me and that you closed here on Gitbub as fixed. I honestly don't understand this absurd behavior, do you want your customers to leave FlutterFlow ?

**Comment by eddiebrasil** [comment]
Hello. Just tested, but the bug persists. Any idea when it's going to be published?

**Comment by blondie63** [comment]
> Hello. Just tested, but the bug persists. Any idea when it's going to be published?

Maybe next week :(

**Comment by eddiebrasil** [comment]
@blondie63 was this resolved?

**Comment by eddiebrasil** [comment]
@agreaves is this fix published?

**Comment by bulgariamitko** [comment]
Yes

**Comment by blondie63** [comment]
> @blondie63 was this resolved?

I still need to test it, maybe later today and let you know
