### ISSUE TITLE
{Text Color} Set By {Component Parameter} not working.

### ISSUE THREAD

**Issue by StuttEx** [FlutterFlow/flutterflow-issues#591]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently:
Text color remains the manually set color before clicking on "set".
The same setting works for the fill color of a container

### Expected Behavior

Text color changes to the color set by the parameter

### Steps To Reproduce

1. Create a component
2. create a text widget
3. create a color-parameter
4. (optional) set a certain color to the text color
5. set the text color to the parameter
6. see what happens – nothing (even not in App-Preview)

### Bug Report Code

ITEez/Hqx89hpbxe1ZD+YfkxiQMxJ1gjbJ0vhNZHaxIgIuKuEYlybuveXxBVXdeITX9iBlKlmmAypvPFvoSSMsInFyqEQ5RGypdfWzn/VT+QV4iWC5GOZ0EnO+JWCWac08KJvx54A/hYdX8uig/GSw==

### Context

I multiple times tried to create a parameter in the "set" field. Did not help either.
I compared it with other widgets (icon, container) their attributes by parameters perfectly work

### Additional info

[](url)
<img width="297" alt="Bildschirm­foto 2023-03-09 um 16 54 13" src="https://user-images.githubusercontent.com/127051951/224079729-4ffa5311-8e18-4369-a319-92d82dcf61d7.png">
<img width="299" alt="Bildschirm­foto 2023-03-09 um 16 54 24" src="https://user-images.githubusercontent.com/127051951/224079739-0ce0ba16-cbd6-4da7-8720-3960172af6b2.png">
<img width="263" alt="Bildschirm­foto 2023-03-09 um 16 54 45" src="https://user-images.githubusercontent.com/127051951/224079745-a59fe70e-5f65-4d4d-a126-2bd0b014939a.png">
<img width="158" alt="Bildschirm­foto 2023-03-09 um 17 05 27" src="https://user-images.githubusercontent.com/127051951/224082834-ac9c114e-e860-4de7-a7a7-5bc7c38709ce.png">

### Environment

```markdown
- FlutterFlow version: 1.1.47
- Platform: Mac OS
- Browser name and version: Flutter Native App 1.1.47
- Operating system and version affected: All
```

**Comment by StuttEx** [comment]
As you see in the last screenshot – the parameter shall be dynamic to display a "current Page" styling. This works as expected with the container (the vertical line) and the icon. But not the text.

**Comment by aemelyanovff** [comment]
@StuttEx Sorry for the delayed response. Are you still experiencing the issue? I'm unable to reproduce it from a blank project.

**Comment by aemelyanovff** [comment]
Closing as stale. @StuttEx if you are still experiencing the issue, could you create a new small project just reproducing the issue? I can't reproduce it from a blank project.
