### ISSUE TITLE
Text bug and overflow issues

### ISSUE THREAD

**Issue by ChrisThaNoob** [FlutterFlow/flutterflow-issues#592]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Tried uploading a video for you, can’t tell if it’s here in the report so I’ll try to describe the issue as well. In the tab bar widget my tabs text won’t render correctly. Only showing white area without text. Also I’m having overflow issues when I use the component as a button sheet and on its own. Can’t find overflow issues in the design. 

### Expected Behavior

Clear text and no overflow issue. 

### Steps To Reproduce

1 new component with tabbar widget in place. Insert 4 tabs with icon and text 
2 new page, new container and insert component

### Bug Report Code

import '/components/create_goal_widget.dart'; import '/flutter_flow/flutter_flow_theme.dart'; import '/flutter_flow/flutter_flow_util.dart'; import 'package:flutter/material.dart'; import 'package:google_fonts/google_fonts.dart'; import 'package:provider/provider.dart';  import 'home_page_model.dart'; export 'home_page_model.dart';  class HomePageWidget extends StatefulWidget {   const HomePageWidget({Key? key}) : super(key: key);    @override   _HomePageWidgetState createState() => _HomePageWidgetState(); }  class _HomePageWidgetState extends State<HomePageWidget> {   late HomePageModel _model;    final scaffoldKey = GlobalKey<ScaffoldState>();   final _unfocusNode = FocusNode();    @override   void initState() {     super.initState();     _model = createModel(context, () => HomePageModel());   }    @override   void dispose() {     _model.dispose();      _unfocusNode.dispose();     super.dispose();   }    @override   Widget build(BuildContext context) {     return Scaffold(       key: scaffoldKey,       backgroundColor: FlutterFlowTheme.of(context).primaryBackground,       body: SafeArea(         child: GestureDetector(           onTap: () => FocusScope.of(context).requestFocus(_unfocusNode),           child: Column(             mainAxisSize: MainAxisSize.max,             children: [               Container(                 width: double.infinity,                 height: MediaQuery.of(context).size.height * 1.0,                 decoration: BoxDecoration(                   color: FlutterFlowTheme.of(context).secondaryBackground,                 ),                 child: wrapWithModel(                   model: _model.createGoalModel,                   updateCallback: () => setState(() {}),                   child: CreateGoalWidget(),                 ),               ),             ],           ),         ),       ),     );   } }

### Context

Trying to build a goal app

### Environment

```markdown
- FlutterFlow version: 1.1.49
- Platform:macOS 
- Browser name and version:using the app
- Operating system and version affected: Ventura 13.2.1
```

**Comment by ChrisThaNoob** [comment]
![Uploading image.jpg…]()

**Comment by ChrisThaNoob** [comment]
I’m only able to recreate the issue when padding in the column is 20. Issue is there sometimes when padding is 16 and disappears when padding is 12 or less

**Comment by ChrisThaNoob** [comment]
It’s a bug appearing when there is padding around the tabbar in any regard. Either if it’s the tab bar having the padding, or other mother widgets having it

**Comment by wenkaifan0720** [comment]
Hi @ChrisThaNoob. Could you describe the steps to reproduce this issue? Thank you.

**Comment by ChrisThaNoob** [comment]
Coloumn - container - tab bar. Enter 4 or more tabs. Adjust padding over 12
in either widget will reproduce the issue with text not rendering. Same
happens using the choice pills widget instead of tabbar.

**Comment by wenkaifan0720** [comment]
Hi @ChrisThaNoob. I can reproduce the issue now. Thank you.

**Comment by ChrisThaNoob** [comment]
Great, thanks!

**Comment by wenkaifan0720** [comment]
We'll fix this issue with our next update for tab bar.

**Comment by ChrisThaNoob** [comment]
Great, thanks for the update.

**Comment by wenkaifan0720** [comment]
Hi @ChrisThaNoob. Regarding the tabbar text issue, I think it is because there is not enough horizontal space for the text to render. Could you try setting `scrollable` to `true` in the general properties of the tab bar?

**Comment by wenkaifan0720** [comment]
Hi @ChrisThaNoob. I don't think there was an issue for the tabbar widget (technically it is a layout issue that can be corrected by the user). But this ticket does inspire us to update the tabbar widget with more styling options. Thank you for raising it!

**Comment by ChrisThaNoob** [comment]
Amazing, thank you for addressing the issue!
