### ISSUE TITLE
Checkboxes error when inside a dynamically generated list from an api

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#593]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a checkbox is a dynamically generated child it errors out.

### Expected Behavior

I would expect it to render fine and be bindable. If I convert it to a component it works fine.

### Steps To Reproduce

1. create column
2. bind to api call (e.g. https://jsonplaceholder.typicode.com/todos)
3. create dynamic children variable name
4. put checkbox in column

### Bug Report Code

ITESlvLlvI1gruZK+rX1KMFqhQIkQ2IjUOcJi+0aSR4cC72vPYoXeM7SU0NKTumRem1IC1aGhTkfwa33k+PxG8ACaU2ubKpk0JVAWhWXezmjVK2VDJaoQXNCP99mBWKG0qaZnh57BMZeSmwB206pNq3qNleeY8aSfxBlZ7vfcPo=

### Context

can't make a training video:)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:Web
- Browser name and version: Chrome 110
- Operating system and version affected: MacOS Monterery
```

**Comment by wenkaifan0720** [comment]
Hi @johnbhiggins7. What is the error exactly?

**Comment by johnbhiggins7** [comment]
This was resolved in the latest release.
