### ISSUE TITLE
Mac app - test custom function doesn't working

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#594]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I click run to test a custom function it won't give any result

### Expected Behavior

it should give a result for the test

### Steps To Reproduce

1. Create a custom function
2. go to the test function page
3. run a test and observe that nothing happens 

### Bug Report Code

-

### Context

I don't want to leave the mac app and test on the web for a simple custom function

### Additional info

https://user-images.githubusercontent.com/45784821/224502518-3d9d6db1-7fd5-4874-8999-81538d6200ae.mp4

### Environment

```markdown
- FlutterFlow version: v1.1.50 Flutter 3.7.3
- Platform: Mac
- Browser name and version: -
- Operating system and version affected: macOS 13.2.1 (22D68)
```

**Comment by agreaves** [comment]
Hi @kicsijohn, unfortunately Custom Function tests do not work in MacOS (this is not something we can address in the short term). We should not be showing that tab, so apologies for the confusing. We will hide it from now on but unfortunately for now you will have to use the Web version to test custom functions. Thanks for the heads up!
