### ISSUE TITLE
Barcode Scanner on IOS prepends a 0 to the UPC

### ISSUE THREAD

**Issue by Fibn007** [FlutterFlow/flutterflow-issues#597]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Specifically on IOS, whenever you scan a UPC, all the UPCs have a 0 added to the beginning of the UPC. For example, a UPC of 111111111111, when scanned through an iOS phone, returns as 0111111111111. 

### Expected Behavior

Expected behavior: A UPC is scanned on IOS and the UPC does not have a 0 added at the beginning. 

### Steps To Reproduce

1. Create a new page
2. Create a barcode scanning widget
3. Create a text output that receives the result of the barcode scanner
4. Test on IOS devices

### Bug Report Code

ITFTkvLlw4tNrsdG+Kn+KMZFqCMWGUMfWLsr0utuGA0hfJvpE7MMZOD4YhRLYte/S25cPlSbjkI10/z5koTfMfY6GxGCUYhBzL5XQTvifFmmR5ubBYeKY3FQL+dRCXKF0Z2NmBZ/Puxqc1Fl6lOEffCdG3qCf9qOYwx5e6fDbOY=

### Context

Simply trying to scan UPCs and getting their full value, without any additional numbers. 

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Webapp
- Browser name and version: Chrome 108.0.5359.221
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment]
Hi @Fibn007 - Thanks for posting the issue. I have tested this using few UPS barcodes available online. All works fine for me. I can't reproduce this issues. However, FF barcode feature is implemented using flutter_barcode_scanner flutter package, FF  does not have any control if there are issues in the package. I would suggest test your app project outside FF editor using the same package and see how it works. Lets us know if there are differences. 

Thanks

**Comment by ksabill** [comment]
I have the same problem adding zero at the beginning on IOS

**Comment by timdcochran** [comment]
So this is indeed a bug with the flutter_barcode_scanner package: https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/351

It doesn't look like that package is being maintained anymore. Would it make more sense for FlutterFlow to use another solution rather than knowingly shipping with buggy dependencies?
