### ISSUE TITLE
Expanded not working with progress bar widget

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#599]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have wrapped the page body with a container to set width limit of 900px and used progress bar as Row ->[progress bar with padding] in it which is overflowing. Tried making the progress bar widget expanded but it does not work as expected and overflows the row even though other widget work fine when expanded.

<img width="1086" alt="Screenshot 2023-03-13 at 12 00 57 PM" src="https://user-images.githubusercontent.com/102008213/224627232-b3f2c383-84e2-4678-bfaa-8d21567128b2.png">

<img width="988" alt="Screenshot 2023-03-13 at 11 58 26 AM" src="https://user-images.githubusercontent.com/102008213/224627024-0c1cc9d8-ceaf-4ae1-8cbe-df7f9e2e246d.png">

### Expected Behavior

I want the progress bar to take up the remaining space. When expanded progress bar should take the available space and not overflow. Using a custom widget for this would defeat the purpose of the progress bar widget in the first place.

### Steps To Reproduce

1. Inside a container with max-width(say 400px) add a progress bar widget in row.
2. Make it expanded so it takes only the given space.
3. Notice it overflows even though making other widgets expanded works.

### Bug Report Code

IT40z/Hqx89gocNf7aXpbfpajic5KVgjbY0nlutRaC0sB5DoBO0MY86lSGFVUs+0S3w7IU6Ggn4y+e/emvHfA/E4JTiCRa59+bhUTQLLeGq5MJiVBbigWG5/DZtWGlyz4LujhgpCWdhaV1IG7V6qIe7KVnftGZjWNW0dJPKYE5KK2SrDX1iXc2URm05KZDPz

### Context

Cannot make the progress bar widget expanded even though expanded works well with other widgets.

### Additional info

Might be related to : [issue:465](https://github.com/FlutterFlow/flutterflow-issues/issues/465)
#### Possible Solution:
Commenting the width property, when wrapped with Expanded widget, solves the issue. Tested on local.
```
...
          Row(
            mainAxisSize: MainAxisSize.max,
            children: [
              Expanded(
                child: Padding(
                  padding: EdgeInsetsDirectional.fromSTEB(30.0, 0.0, 30.0, 0.0),
                  child: LinearPercentIndicator(
                    percent: valueOrDefault<double>(
                      (((_model.sliderValue1 ?? 0) +
                                  (_model.sliderValue2 ?? 0) +
                                  (_model.sliderValue3 ?? 0)) /
                              3) /
                          100,
                      0.0,
                    ),
                    // Commented this line
                    // width: MediaQuery.of(context).size.width * 0.85,
                    lineHeight: 27.0,
                    animation: false,
                    progressColor: () {
                      if (((_model.sliderValue1 != null) &&
                              (_model.sliderValue2 != null) &&
                              (_model.sliderValue3 != null)) &&
                          (valueOrDefault<double>(
                                (((_model.sliderValue1 ?? 0) +
                                            (_model.sliderValue2 ?? 0) +
                                            (_model.sliderValue3 ?? 0)) /
                                        3) /
                                    100,
                                0.0,
                              ) <
                              0.4)) {
                        return FlutterFlowTheme.of(context).warningColor;
                      } else if (((_model.sliderValue1 != null) &&
                              (_model.sliderValue2 != null) &&
                              (_model.sliderValue3 != null)) &&
                          (valueOrDefault<double>(
                                (((_model.sliderValue1 ?? 0) +
                                            (_model.sliderValue2 ?? 0) +
                                            (_model.sliderValue3 ?? 0)) /
                                        3) /
                                    100,
                                0.0,
                              ) <
                              0.7)) {
                        return Color(0xFFFBA236);
                      } else {
                        return FlutterFlowTheme.of(context).primaryColor;
                      }
                    }(),
                    backgroundColor:
                        FlutterFlowTheme.of(context).secondaryBackground,
                    center: Text(
                      '${((((_model.sliderValue1 ?? 0) + (_model.sliderValue2 ?? 0) + (_model.sliderValue3 ?? 0)) / 3).floor()).toString()}%',
                      style: FlutterFlowTheme.of(context).bodyText1.override(
                            fontFamily: 'Inter',
                            color: FlutterFlowTheme.of(context).primaryText,
                          ),
                    ),
                    barRadius: Radius.circular(24.0),
                    padding: EdgeInsets.zero,
                  ),
                ),
              ),
            ],
          ),
...
```

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @Shubham-VE - Thanks for reporting the issues. What happens if you do not give any value to width property. Can you try this and let us know please?

**Comment by Shubham-VE** [comment]
If I remove the width value the previous value is retained in the code but I can set it to 0, which is not useful. So I guess FF does not change the code on deletion.

**Comment by agreaves** [comment]
Hi @Shubham-VE, thanks for the bug report! This is because currently you are not able to clear the width of the Progress Indicator. This will be fixed in the upcoming deploy and should fix this issue!
