### ISSUE TITLE
When assigning a JSON data type to Local State it is not accessible/assignable 

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#6]
## Expected behavior
When assigning a JSON data type to a Local State with data and then accessing from a FF using, for example the Text Widget, like this $.Name should display the name, for example "John".

## Current behavior
When assigning a JSON data type to a Local State with data and then accessing from a FF using, for example the Text Widget, like this $.Name it is displaying NULL.

1. Create an API call to get a JSON data.
2. Assign this data with an Action in On Page Load Action
3. Assign the JSON that you get from the API call to a Local State variable called - data for example
4. Create Text widget and try to access the Name stored in the data Local State with $.Name - you will get "null"

## Context
I can't access a JSON data from a Local State.

## Your environment

* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 105
* Operating system and version (desktop or mobile): desktop

**Comment by hariprasadms** [comment]
Not able to reproduce this. It works fine for me. Could you show us the api response how it looks one which you are trying to bind to local state. 

If you could add a quick video link showing the issue that would be great.

**Comment by bulgariamitko** [comment]
I am able to get results right now. I will close this issue, if I got it again I will post a video about it and give my demo JSON data.
