### ISSUE TITLE
Private API post call not working after publishing

### ISSUE THREAD

**Issue by waminos** [FlutterFlow/flutterflow-issues#600]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

hi @hariprasadms @shelpert  @agreaves 
I am using post api call, it works fine when public but throw 400 error when private. You can see the payload below, it seems FF parse the JSON payload also as String.

Parameters: (I use variables)
a string --> OK
b int --> OK
c  JSON --> Parmeter message ,PROBLEM  = should be like this : [{"role":"user1","content":"hi"},{"role":"user2","content":"hey you"}] , when network inspecting, it looks like a string like below:
![image](https://user-images.githubusercontent.com/18538948/224068064-6cca2577-49e8-4262-b212-562c128f9009.png)

Should be like this :
![image](https://user-images.githubusercontent.com/18538948/224646046-717e1014-70a3-43c7-8a32-3501efbe58b4.png)

need help

### Expected Behavior

Private api call should work as public api call 

### Steps To Reproduce

1. create post api call (header : Content-Type: application/json)
2. add a parameter of type JSON 
3. make call private
4. test the response --> works on FF
5. publish web or run locally throw error 400

### Bug Report Code

IT48i87huIhOxMNC7qXpbfl7/Sc5KVs7bLgzlMJhZ008J5TUB+x/evz4UBJoTbyndghYfU6KmT8d0+DIm9z1IfUDFySWQKp7z5NQbRfiQn2gabKyCJOaZXNEGshWBXa80bWFuCQnJsdiSE472WD3F9nLcD/sNb2yIW40QvmZKqzXvgfuQ0SLb3kNh1JWeC/v

### Context

I can not publish my app thats uses chatgpt api.

### Additional info
Error
![image](https://user-images.githubusercontent.com/18538948/224068064-6cca2577-49e8-4262-b212-562c128f9009.png)

Should be like this
![image](https://user-images.githubusercontent.com/18538948/224646148-3ebaf8ce-aed2-4810-9d25-20911c973499.png)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: web, android
- Browser name and version: NA
- Operating system and version affected: NA
```

**Comment by hariprasadms** [comment]
Hi @waminos - Thanks for reporting the issue. Is this the same issue with get request ?. Please add these details.

**Comment by waminos** [comment]
> Hi @waminos - Thanks for reporting the issue. Is this the same issue with get request ?. Please add these details.

I don't understand your question. This is a private post request not a get request.
Here the setup:
![image](https://user-images.githubusercontent.com/18538948/224702914-e443aa4c-c1cd-4358-9209-3fbdb59d6ccf.png)
![image](https://user-images.githubusercontent.com/18538948/224703035-e7e4c034-9371-4e0e-9269-a0fbc03cb3c8.png)

Working in FF platform:
![image](https://user-images.githubusercontent.com/18538948/224703184-9640d2ec-8493-4e47-8695-4ff39faad469.png)


Not working on production:
![image](https://user-images.githubusercontent.com/18538948/224703560-548e5681-7d6d-4949-a88b-f45be95dc773.png)

**Comment by hariprasadms** [comment]
Hello, I was asking, have you got GET requests with keys deployed private. Even GET requests also can be private. How those calls are working in run mode.

**Comment by waminos** [comment]
> Hello, I was asking, have you got GET requests with keys deployed private. Even GET requests also can be private. How those calls are working in run mode.

No i only have one POST request (refer to chatgpt api documentation). I tried GET request, it doesnt work and that make sense because it requieres a payload.
I dont know if i answered your question ?

**Comment by hariprasadms** [comment]
No worries. I test the requests and confirm the issue shorty. Thanks

**Comment by hariprasadms** [comment]
I can reproduce the issue.

**Comment by waminos** [comment]
@hariprasadms  any update here ?

**Comment by waminos** [comment]
@hariprasadms ?

**Comment by agreaves** [comment]
Hi @waminos, thank you for the bug report and apologies for the delayed response! I've finally managed to track down the issue, and it is indeed a bug on our side! We are not currently setting the region for cloud functions in the app, so it's trying to call the function in `us-central1` at the moment.

We've fixed this on our side, which you'll see reflected in the next deploy! In the meantime, the easiest workaround is to set your region back to `us-central1` and redeploy the Private APIs cloud functions. Apologies again for the inconvenience!

**Comment by waminos** [comment]
Hi @agreaves,
I changed cloud function server region by copying the function and setting the region to ´us-central1´  but doesnt work.
Do i need to recreate a new firebase project in us-central1 ?

**Comment by julien-digilink** [comment]
Seems that i have this problem
GET request are ok, but not POST

I wanted to use the "private mode" to avoid CORS issues on the web version of my app but now i'm blocked, CORS issues if I don't use private API and POST parameters problems if I use it :/

**Comment by fj-mzoehr** [comment]
I can confirm this problem.
