### ISSUE TITLE
‘Sign in with Apple’ is not working on android

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#601]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Sign in with Apple is not working on android, it shows this error on android studio console:

<img width="1256" alt="Screenshot 2023-03-10 at 9 49 53 PM" src="https://user-images.githubusercontent.com/126883330/224723348-ad811df1-fa77-4af9-89bd-bf289fc0c26c.png">

### Expected Behavior

It was expected to be working fine on android as well, as its working fine on IOS and Web.

### Steps To Reproduce

1. Complete the Apple Sign in steps in documentation
2. Add an action to a button for Apple Sign in

### Bug Report Code

IT4whfLluIhOsdhE17Xyb8JvmjoRMjt5arhM1Ox+eCs8GZT0B4kcYs+kfklUOfW4TwhDeWK0pD4X/Mr3vfPfV/EEGwyabNg+zs5yZznjUl+tbJiYBa63b398DcFRN0PEyMKg2BVSJbd2LEZk3WD3GtzKHwLcQ+e3OUgjPOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

I wanted to use Apple Sign in for my app for all major platforms, but for android, it shows up an error and doesn't work

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome 106.0.5249.119
- Operating system and version affected: macOS Ventura 13.0
```

**Comment by bulgariamitko** [comment]
@SameerShahzad99, Is there a reason why you closed this issue?

**Comment by SameerShahzad99** [comment]
It’s actually not intended to work on Android (or rather, not supported in FF), we actually hide buttons with Sign In with Apple on non-iOS typically.

**Comment by PrayerShare** [comment]
> It’s actually not intended to work on Android (or rather, not supported in FF), we should actually hide buttons with Sign In with Apple on non-iOS typically.

Hi @SameerShahzad99 ,

I know this is a closed topic, but, I wanted to check / understand what FF would suggest for a user flow where a user had logged in via their Apple ID, but either are borrowing an Android, or have moved away from their iPhone/iPad device to an Android but kept their Apple ID.

Cheers.

Boz.

**Comment by sacco-riffraff** [comment]
> It’s actually not intended to work on Android (or rather, not supported in FF), we should actually hide buttons with Sign In with Apple on non-iOS typically.

I strongly disagree, this is should be a product designer decision, certainly not a developer decision.
Users should be able to sign-in with Apple on non-iOS devices, no one in the UX space ever said otherwise. I run two live consumer apps and we would never release without cross-platform Auth. These are Auth methods, they are designed to be cross-platform.
I think this is a bug - or at least a wrong decision that does not meet production grade standards - and should be reopened.

**Comment by cg-sitiouno** [comment]
I agree with @sacco-riffraff . this is a bug..
