### ISSUE TITLE
No Option for Setting Parameter Type in Components

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#603]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is a bug in components while creating a new parameter from ‘set from variable’, that we cannot set the type of the parameter.

### Expected Behavior

It should allow users to change the parameter type, when creating a new parameter in 'set from variable'

### Steps To Reproduce

1. Create a Component
2. Add a text widget
3. Set the value from variable and inside component parameter, Create a new parameter.

### Bug Report Code

IT4OlPLq4spgofVG7c/+au9agmAsKVgjaqxM0sJDYxYgGI/NG7UIec/4VEptXbC+TVc3eVn8uDoz062LkdzIN/AVBAeZG5g6z6hxWw7ybFiiR5DTC83tQURRINpKCn673MOS3Ql/ItN1SkY9wV+Mf9m/VgjYNKLSPUUROc6ZMtvJo3fuQ0SLb3kNh1JWeC/v

### Context

I wanted to add a new parameter from the set from variable menu for ease, but i found out incomplete implementation of this shortcut

### Additional info

https://drive.google.com/file/d/1HD3078wcyTAH4OObYs0YL9tAI4mQG5YC/view?usp=share_link

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome 106.0.5249.119
- Operating system and version affected: macOS Ventura 13.0
```

**Comment by bulgariamitko** [comment]
@SameerShahzad99 , is there a reason why you closed this issue?

**Comment by SameerShahzad99** [comment]
i have understood that its not a bug, the auto assignment of parameter type is by purpose, it automatically sets to the type we are assigning it to.
