### ISSUE TITLE
Build Error - Issue running App locally on IPhone - Dart library 'dart:js' is not available on this platform.

### ISSUE THREAD

**Issue by nicmohr25** [FlutterFlow/flutterflow-issues#604]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Build is failing when trying to run the app with XCode / VSCode on physical device.
I'm getting the following Error: 
../../.pub-cache/hosted/pub.dev/js-0.6.5/lib/js.dart:10:1: Error: Dart library 'dart:js' is not available on this platform.

### Expected Behavior

App should at least build

### Steps To Reproduce

-

### Bug Report Code

ITFTlcmB34hNodcF+KrqdcJslWQsCUMdXOczitVEew4bCIj4PbMQPvTBZRJtTdCzaH1IeGKknXIx+a3njYSWL/o6CyeWG9VlypZtWhPPbDmVMozTEs2eS3dDL99bfRW60reFmxJSCLBeWE5h2Dn3N+eiTT+Cf9qOYwx5e6fDbOY=

### Context

-

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.3
- Platform: Physical Device - IPhone
- Browser name and version: Chrome Version 111.0.5563.64 (Offizieller Build) (x86_64)
- Operating system and version affected: MacOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hello @nicmohr25 - As you are trying to build the app outside FF editor, there could number of factors why build is failing. Example, your local flutter and dart version is not update and etc. In this case, it is difficult for us to debug the issue. Hence we do not consider this as FF issues.

**Comment by rgjurgens** [comment]
I'm having this issue as well. I think it happens when you want to deploy a piece of code that uses `dart:js` to mobile apps  as well
