### ISSUE TITLE
Bottomsheet missing an onload action for isolating logic into a bottom sheet

### ISSUE THREAD

**Issue by thekvn** [FlutterFlow/flutterflow-issues#606]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow's BottomSheet lacks an onload action, which makes it challenging to execute animations or actions immediately after the bottom sheet opens, thereby hindering the isolation of logic within the bottom sheet.

### Expected Behavior

An onload action that lets me attach actions to kick off when a  bottom sheet has been presented.

### Steps To Reproduce

N/A

### Bug Report Code

N/A

### Context

N/A

### Environment

```markdown
N/A
```

**Comment by hariprasadms** [comment]
Hi @thekvn - Can you please add steps to reproduce details? Without steps details it is difficult to understand the issue you are facing. And also images and a quick video showing the issue will be more appreciated. 

As for as bottom-sheet feature, I can say it is working as expected.

**Comment by agreaves** [comment]
Hi @thekvn, thank you for the feature request! We are working on a feature that will allow something similar in the future. However, this forum is for reporting bugs, so I'm closing this issue.
