### ISSUE TITLE
Custom Function Testing is not working 

### ISSUE THREAD

**Issue by guillo270120** [FlutterFlow/flutterflow-issues#609]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when testing the custom functions, the result does not come out according to the operations and/or functions established

### Expected Behavior

get the correct result according to the function placed

### Steps To Reproduce

1.- Go to Custom functions, create new one.
2.-put a simple function like:

int simplesum(
  int var1,
  int var2,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  int res = var1 + var2;
  return res;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

3.- Go to test function and put example values
4.- the result will be 0

### Bug Report Code

IT4el8j6yIt1j7xa+KX5bcJB/TssKUQgULhEiuxEcAwbF5CqE5oufuj+QHZVOMO/dFY3OlmI8Tse/srSv9nhV+4HPiieftlyyqhMexX/fF+7VJCtDIeCRXxDI+xYChyHzbWnghF7HOpZSi0MwHGULumAcHbaJLrAC0cvMc+XMofXpVnhGhzOXn0Jg1ZSfCvr

### Context

i cant test the functions implemented in FF 

### Additional info

![image](https://user-images.githubusercontent.com/104284249/225095426-468cd5ef-bc2c-4b08-a0ea-2dd9e87836d7.png)
![image](https://user-images.githubusercontent.com/104284249/225095473-b94c064b-3582-4e44-8bb6-0df0f08d5083.png)

I see the same issue on Github but this was closed https://github.com/FlutterFlow/flutterflow-issues/issues/595

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:WEB
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by agreaves** [comment]
Hi @guillo270120, thanks for the report. Yes, as per #595 this issue is closed and the fix will be deployed in the next day or two.
