### ISSUE TITLE
Chart widget does not allow data map (data type) member field to be specified for X / Y axis values

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#61]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When specifying the data source for a chart widget allow the use of the data map (data type) field.  For the data below allow to use amount.total number to be used for either axis.

amount (map)
 - original (double)
 - fee (double)
 - total (double)

## Current behavior (required)

The list of available data fields for the X and Y axis fields lists the map data field in red and does not allow to select its member field.

## To Reproduce (required)

1.  Specify a query of documents with data map fields that include number fields 
2.  Use that collection for a line chart widget
3.  Try to select a data map sub-field for X or Y axis
4.

## Context (required)

Had to duplicate the data in the collection to move the required filed up from the data map to make it accessible by FF.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by agreaves** [comment]
Hi @KirilOkun, apologies for the late response to this issue. As you pointed out, this is simply a limitation of the Chart widget, as you can only select first level fields. I'm marking this as a feature request for now, however it's in the uncanny valley of not actually broken or a bug but certainly quite inconvenient. I'll update the ticket when we add the ability to select Data Types.

**Comment by KirilOkun** [comment]
@agreaves   Thanks Alex.   This is a corner case with a clear workaround.   Just an FYI for your (ever growing) backlog.
