### ISSUE TITLE
Incompatible barcode_widget version 

### ISSUE THREAD

**Issue by JuanEgas** [FlutterFlow/flutterflow-issues#612]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

'flutter pub get' error due to incompatible barcode_widget (2.0.3) and qr_flutter (^4.0.0) versions. These are the default library versions currently used by Flutterflow when such widgets (barcode and qr) are implemented. Our main github branch has barcode_widget (2.0.0) to solve the issue. 

### Expected Behavior

'flutter pub get' command runs with no error

### Steps To Reproduce

1. Implement barcode functionality using Flutterflow. 
2. Download or clone your Flutterflow code 
3. In your code directory, run command 'flutter pub get'
That's it, you should see the error 

### Bug Report Code

dependancyRelated

### Context

I can't deploy directly from Flutterflow, I need to deploy from GitHub after making the change in version barcode_widget from 2.0.3 to 2.0.0. 

### Additional info

**Output log in Flutterflow when attempting to deploy to mobile devices**
Codemagic Deploy Output
Failed Step: Get Flutter packages

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Running "flutter pub get" in flutter_tools...
Resolving dependencies in ../programs/flutter/packages/flutter_tools...
  _fe_analyzer_shared 50.0.0 (55.0.0 available)
  analyzer 5.2.0 (5.7.1 available)
  archive 3.3.2 (3.3.6 available)
  args 2.3.1 (2.4.0 available)
  async 2.10.0 (2.11.0 available)
  built_value 8.4.2 (8.4.4 available)
  checked_yaml 2.0.1 (2.0.2 available)
  collection 1.17.0 (1.17.1 available)
  completion 1.0.0 (1.0.1 available)
  coverage 1.6.1 (1.6.3 available)
  dds 2.5.0 (2.7.6 available)
  dds_service_extensions 1.3.1 (1.3.3 available)
  devtools_shared 2.18.0 (2.22.2 available)
  dwds 16.0.2+1 (18.0.0 available)
  fixnum 1.0.1 (1.1.0 available)
  frontend_server_client 3.1.0 (3.2.0 available)
  html 0.15.1 (0.15.2 available)
  intl 0.17.0 (0.18.0 available)
  io 1.0.3 (1.0.4 available)
  js 0.6.5 (0.6.7 available)
  json_annotation 4.7.0 (4.8.0 available)
  logging 1.1.0 (1.1.1 available)
  matcher 0.12.13 (0.12.14 available)
  meta 1.8.0 (1.9.0 available)
  mime 1.0.2 (1.0.4 available)
  multicast_dns 0.3.2+2 (0.3.2+3 available)
  native_stack_traces 0.5.2 (0.5.5 available)
  node_preamble 2.0.1 (2.0.2 available)
  path 1.8.2 (1.8.3 available)
  petitparser 5.1.0 (5.3.0 available)
  pubspec_parse 1.2.1 (1.2.2 available)
  source_maps 0.10.11 (0.10.12 available)
  sse 4.1.1 (4.1.2 available)
  test 1.22.0 (1.23.1 available)
  test_api 0.4.16 (0.4.18 available)
  test_core 0.4.20 (0.4.24 available)
  vm_service 9.4.0 (11.2.0 available)
  web_socket_channel 2.2.0 (2.3.0 available)
  webdriver 3.0.1 (3.0.2 available)
Got dependencies in ../programs/flutter/packages/flutter_tools!
Resolving dependencies...
Because qr_flutter >=4.0.0 depends on qr ^2.0.0 and barcode >=2.2.0 depends on qr ^3.0.0, qr_flutter >=4.0.0 is incompatible with barcode >=2.2.0.
And because barcode_widget >=2.0.3 depends on barcode ^2.2.2, qr_flutter >=4.0.0 is incompatible with barcode_widget >=2.0.3.
So, because welth_budget depends on both barcode_widget 2.0.3 and qr_flutter ^4.0.0, version solving failed.
pub finished with exit code 1

Build failed :|
Step 4 script `Get Flutter packages` exited with status code 1

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Flutterflow
```

**Comment by victoriahuang1** [comment]
Closing due to inability to reproduce. Feel free to reopen if there is new information to help reproduce the issue.
