### ISSUE TITLE
Using app state as date type is not show

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#614]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When create a app state of date type and try to show in the app is not working

### Expected Behavior

I want show the value of the app state

### Steps To Reproduce

1. Create an app state as date type
2. Choose any date
3. Go to a page and use this app state as timestamp format

When the app builds the date is not showed

### Bug Report Code

ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMBX5Ir1utvGEg3CIurO4kDO+LUaXdpYc+HTVVUAmCihkQK/sLeiuPXCPoBHxKqfo9607ludA2UQl+VVLrQCJeWWXB8J8VXGWqm5JmzuiZQHPVec1o92GGLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want show the value of the app state

### Environment

```markdown
- FlutterFlow version: v3.1 (released March 11, 2023)
- Platform: Web
- Browser name and version: Chrome 111.0.5563.65 
- Operating system and version affected: Windows 11 22H2 - 22621.1344
```

**Comment by hariprasadms** [comment]
Hi @Franco98404 - I am not able to reproduce this issue. I can test this in my projects and it works fine. Please share a quick video of the issue.

**Comment by Franco98404** [comment]
Hi @hariprasadms, I share a link with the bug:

https://schoolfy365.tinytake.com/msc/ODAxODMxN18yMTE1NzE0NA

Let me know if you need more information

**Comment by agreaves** [comment]
Hi @Franco98404, thanks for all the relevant info! We weren't originally able to reproduce because it appears it only happens when it's a persisted field. We've made a fix which should be available on the next deploy! In the meantime you can either not make the field persisted or use a default value.
