### ISSUE TITLE
+ Add Item for App State variable of type List <Double> not working as expected 

### ISSUE THREAD

**Issue by ToddHerron** [FlutterFlow/flutterflow-issues#617]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

App State **+ Add Item** does not work for app state variables of type _List_ *<*Double*>*
<img width="1097" alt="Screenshot 2023-03-15 at 17 35 02" src="https://user-images.githubusercontent.com/2007969/225467243-fedc307e-eb27-46b6-86c4-24b76196525e.png">

When you click on **+ Add Item**, on the UI nothing appears to happen. In the background, it is actually creating list entries with value of **0** (not **0.0**). (I suspect these are **null**.) You can see these added null items when you click on > (right chevron).

This seems to be a problem only with Lists of type <Double>. The other List types work as expected.

### Expected Behavior

When you click on **+ Add Item** a new line should be created with a sample Double value of **0.0**. 

You should be able to change the Double value on the newly created line. 

### Steps To Reproduce

1. Click on App State on the left column
2. Create a state variable of type _List_ *<*Double*>*
3. Click on **+ Add Item**

### Bug Report Code

IT4WiPHlvIpNodtK+KriYMEw/CQUNlwnbbgrl8NxRRcbIb7yP5wPXPykP1doTcOiTFZYMFv9inw009GNveDtC+QHAzSeR6Fx+M5cZjvMRjuWRc2zO7uWeWhtN8pRNEuV07uJmCNDJtpscXgM7E7zLuTIaB7YJKLvNmo4D/+jLtrA+V6pAhm6Xn0Jg1ZSfCvr

### Context

I have internal tables in my app that are stored as lists. I was getting RangeErrors because additional items I thought I'd added to the state list variables weren't being saved. 

### Additional info

<img width="1224" alt="Screenshot 2023-03-15 at 17 19 10" src="https://user-images.githubusercontent.com/2007969/225471629-1b237fb2-38ca-4c9c-9fd2-4c23c20c5a08.png">

### Environment

```markdown
- FlutterFlow version: 1.1.50
- Platform: MacOS
- Browser name and version: Chrome Version 111.0.5563.64 (Official Build) (x86_64)
- Operating system and version affected: MacOS Ventura 13.1 (22C65)
```

**Comment by hariprasadms** [comment]
Hi @ToddHerron - To assign double values to list-type app states, you should click on add item button and add a double value. It is working as expected.

**Comment by ToddHerron** [comment]
I tried that several times. It isn't working as expected. 

When I click on **+ Add Item**, **nothing in the UI changes**. i.e. There is nowhere to add the _Double_ value. The UI should add a line with a field for me to add a _Double_ value. (This is how the UI works for as expected on all other types _except for type Double_.) 

The workaround is to toggle the chevron so you can see the appended list item with the _null_ entry.

**Comment by hariprasadms** [comment]
Hi @ToddHerron - I have looked at your project and able to add double list values with no issues. I hope it is working the same at your end. I'm closing the issue now. Let us know if the issue still persists, we can re-open the issue and investigate. Thanks
