### ISSUE TITLE
MUX Widget grey bar (not a mux issue)

### ISSUE THREAD

**Issue by Arseniidemydov** [FlutterFlow/flutterflow-issues#618]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the mux widget on the live stream page I have a gray on a bottom of a page  bar that can't be removed and it's greatly affects the user's experience with live translation. I texted to Mux but they said that is issue from FF side. Issue should be inside code of a widget.

### Expected Behavior

I want to have a full screen of user content without grey bar

### Steps To Reproduce

1. Create a new page
2. Use mux widget 
3. Run Preview and look at this page

### Bug Report Code

MUX Bug

### Context

![Uploading Screenshot 2023-03-16 at 14.37.58.png…]()

### Environment

```markdown
- FlutterFlow version: v9
- Platform: Mac 
- Browser name and version: Safari, latest
- Operating system and version affected: all systems
```

**Comment by shelpert** [comment]
Hi @Arseniidemydov,

Can you upload a screenshot of the issue you're experiencing, and also provide a link to your project? And where do you see this issue, just in preview mode or also in test mode/locally?

**Comment by shelpert** [comment]
Correction: I don't need the link to your project, but I do need the bug report code. You can generate this by right-clicking on the widget tree and choosing 'Get Bug Report Code'. Some screenshots would also be helpful, it seems like the one you uploaded did not upload properly.
