### ISSUE TITLE
Failed to set repository head to XXXXXXXX

### ISSUE THREAD

**Issue by yoridewit** [FlutterFlow/flutterflow-issues#622]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using codemagics, i'm using the Deploy To App Store with a new App Version number.
However, the first time I do this it ALWAYS gives me this error: "Failed to set repository head to <XXXXXXXX>".
See the enclosed screenshot

When I change nothing, but try again by simple clicking the "Deploy To App Store" again, it works. Nothing changed in between.

### Expected Behavior

New version should build without issues

### Steps To Reproduce

1. Create new version number
2. Deploy to App Store button clicked
3. See the error in the build message
4. Change nothing, click Deploy button again
5. See it work without fail

![image](https://user-images.githubusercontent.com/11245231/225753276-74f053f5-910f-4304-9b19-2d8423753bcb.png)

### Bug Report Code

IT4kl8n1w85Pj7xY17X5bcFvpCk4HE84TLJMt9VxSUghNYDzP4kTds/RYklLYteIY31pM2aZknEdwN6LkuD1NfEpAyyuY6p8zJRXQRXgWjiiMpinEZaoenAlJ8VTIWaw4bbQhQl/JvNYLngm3E6yCPCdG3qCf9qOYwx5e6fDbOY=

### Context

Annoying bug, thankfully i have a workaround

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: MacBook Pro, M1 
- Browser name and version: Chrome 110.0.5481.177 
- Operating system and version affected: MAC OS Ventura 13.0.1
```

**Comment by hariprasadms** [comment]
Hi @yoridewit - Thanks for posting this issue. In general mobile apps deployments are working fine. However, the issue what you are facing must be project specific issue. I can mark this as bug and will let you know once it is fixed. Let us know if it is start working fine.

**Comment by joshensongric** [comment]
Yea I can confirm this bug occurred for my project as well exactly as described in this bug report

**Comment by mandriusis** [comment]
I have experienced this issue as well.

**Comment by shelpert** [comment]
Hi @yoridewit,
When this happens, do you deploy from your own Github repo? Or is that switch turned off?
@joshensongric @mandriusis @stefanlenoach If y'all could post bug report codes as well that would be helpful, so I can try to figure out what is causing this issue. Thanks!

**Comment by agreaves** [comment]
Hi everyone, this was due to a temporary outage at the time which has long been fixed. Just wanted to close out this issue 🙂. Please let me know if for some reason this is still affecting you!
