### ISSUE TITLE
Run mode is missing from one of my apps.

### ISSUE THREAD

**Issue by stealthyloon** [FlutterFlow/flutterflow-issues#624]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The "Run your app in Test Mode" is missing. The purple lightening bolt and the drop down menu for running the app in test mode is missing from my app.. 

### Expected Behavior

I can't run the app in test mode because the button is missing.

### Steps To Reproduce

1. Not sure how to reproduce, because I'm not sure how it went missing in the first place..

### Bug Report Code

IT4WlMrqx89Nobhe0KrUY8JFmjs5Jjsna7hEm8NxSQ0jNbauO5wPXfikSEpWZ9+kTHxcL06ghmEd0+uLhuPAA+UpPU6bGIhP+rpUcxXiRXyhVYiOEqWWPHZPGfNJJVzG0KSZkAhSNrBaL0Y822Dzf96ybHHAGJjOClgZOvmIGLrP+nerQ0SLb3kNh1JWeC/v

### Context

I can't test the app I'm trying to develop. I have to download the APK to test on the android device and this is slowing development down greatley..
![Missing Run Test Mode](https://user-images.githubusercontent.com/18235388/225792527-89355369-7862-485b-b568-d01e2652c051.png)

### Additional info

The run in test mode button is also missing from Microsoft edge browser.

### Environment

```markdown
- FlutterFlow version: v3.1 - flutter 3.7.3
- Platform: Windows 
- Browser name and version: Google Chrome Version 111.0.5563.65 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 64 Bit
```

**Comment by hariprasadms** [comment]
Hi, I just looked at your project and I can see the run button. Are you still seeing the same issue?

![image](https://user-images.githubusercontent.com/17435678/225917908-d6bbf430-216e-4168-bbfb-b20cc4f2c6c5.png)

**Comment by stealthyloon** [comment]
I Still can't see the run button...
![Missing Run Test Mode pic 2](https://user-images.githubusercontent.com/18235388/226067122-9f24c3d8-01c8-4361-9626-b7e2c4901e13.png)

**Comment by stealthyloon** [comment]
I cleared the cache on my browser and it didn't help. I also tried different browsers and the results are the same.

**Comment by stealthyloon** [comment]
I just downloaded Firefox and still I don't have the run button.
![firefox no run button](https://user-images.githubusercontent.com/18235388/226068346-18482c7d-e1e4-4500-9103-f4d80b1fdd1a.png)

@hariprasadms

**Comment by stealthyloon** [comment]
Also tested it in incognito/private browsing mode and still no run button.

**Comment by wenkaifan0720** [comment]
Hi @stealthyloon. Are you still missing the run mode button? I just tested on macos and windows 11 and can see the button.

**Comment by stealthyloon** [comment]
Hi @wenkaifan0720. Yes I am still having this issue. Like I said all of my other apps aren't having this issue. I am at a loss and may have to take my business else were... I have a deadline and this is slowing development progress greatly.. I love flutterflow, but I can't test like this. Please help! I would rather stay with flutterflow...

**Comment by agreaves** [comment]
Fixed and will be deployed later today (see #623)

**Comment by stealthyloon** [comment]
@agreaves thank you!!

**Comment by LuanMakedrive** [comment]
I have the same problem

![Image](https://github.com/user-attachments/assets/1a24cdd5-dd85-4dbc-b7fa-3568de91aad9)
