### ISSUE TITLE
Variables in API Groups do not work

### ISSUE THREAD

**Issue by troykelly** [FlutterFlow/flutterflow-issues#625]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using variables in api group definitions per [the current documentation](https://docs.flutterflow.io/data-and-backend/api-calls/create-and-test-api-call#grouping-api-calls) (image also below) variables remain as their string value name in square brackets.

Using the example in your documentation as an example, if I were to create a group as defined - the header would be passed to the server as `Authorization: Bearer [auth_token]` regardless of the variable being passed or not.

<img width="857" alt="FlutterFlow Documentation" src="https://user-images.githubusercontent.com/4564803/225837624-ca832460-d935-4a84-b15a-9b04b8bd7693.png">

It's fairly clear why this isn't working in the generated code below:
<img width="480" alt="004_Failed_Substitution" src="https://user-images.githubusercontent.com/4564803/225837727-801f6a99-4be8-4051-88b9-4dc3b1d33f73.png">

Whereas a similar substation from an API call uses variables in place of the `[` `VARNAME` `]` nomenclature.
<img width="412" alt="003_Working_Substitution" src="https://user-images.githubusercontent.com/4564803/225837906-686d7510-65d3-4b62-9c2b-3f0ca89ef2f4.png">

### Expected Behavior

Variables defined in the group should, at the very least, be substituted with the variable data passed to the API call.

### Steps To Reproduce

1. Create an API Group
2. Use `[VARNAME]` variables in headers or the URL
3. Create an API Call within the group
4. Use the call within the app
5. See the lack of substitution in debugger or server logs

### Bug Report Code

NA

### Context

This invalidates FlutterFlow as a product ready to be used with API's

### Additional info

Example configuration
<img width="586" alt="002_API_Group_Configuration" src="https://user-images.githubusercontent.com/4564803/225838367-6a7a8b58-b55d-48e8-a38b-b54d1275fdd6.png">

### Environment

```markdown
- FlutterFlow version: Not visible on your site
- Platform: macOS
- Browser name and version: Chrome Version 111.0.5563.64 (Official Build) (x86_64); Safari Version 16.3 (18614.4.6.1.6)
- Operating system and version affected: all - it's server side
```

**Comment by hariprasadms** [comment]
Hi @troykelly - Thanks for posting this issue. At the moment in FF variables not supported at api group level.  I can mark this as feature request. Thanks

**Comment by troykelly** [comment]
This isn't a feature request, it's a bug.

Your documentation even shows it being supported as such.

Let's not be fancy with words, we all used to joke about what a feature request is in the early Dev days.

The lack of support for variables at the group level is a serious failure, APIs almost always need authentication and/or other constants provided.

@hariprasadms please get this resolved as a bug, because it is

**Comment by troykelly** [comment]
The documentation needs to be updated, or the bug resolved. The issue is not stale.

**Comment by MagmaiKH** [comment]
This issue is still not resolved and prevents FlutterFlow from being used with numerous APIs.
A notable example is Digital Ocean.
Documentations still shows it is supported.

Adding e.g. [bearer] to a header generates a pop-up error upon clicking _Add Call_

> Current API endpoint is misconfigured.
> Details: Variables specified in brackets in URL paths, headers, or parameters must be defined in the "Query Parameters" section.
> Missing variables: bearer.

Adding a bearer variable to the Query Parameters does not resolve the issue (nor is correct behavior).

This subtle missing functionality for API variables is a show-stopper Class A bug not a "feature request".
1) It is impacting customers
2) It is preventing customers from getting work done.
3) There is no work-around.

That is Class A; stop what you are doing and fix.

Other post, and even docs, indicate you used to be able to hack around it.
Some change since ~a year ago broke the work-around.

**Comment by troykelly** [comment]
@MagmaiKH we gave up on FlutterFlow, it's just not ready for use yet.
We did try the "work around" and it didn't work - is this new (as in the last few days?)

**Comment by sbarber-dsi** [comment]
I verified it works yesterday.
There's posts from about a year ago suggesting you can work around it but it wasn't super clear how.

You have to add the [variable] to the header in the API Group then define the variable in each API call.
I have a call to Digital Ocean working which requires a header of 'Authorization: Bearer <token>'
So in the API group you put, "Authorization: Bearer [token]" then add a variable to the actual API call for 'token'.

**Comment by aSambuu** [comment]
This bug still have. Api group header not call with variable. My group api call Authorization: Bearer [auth_token]. Not set auth_token.

**Comment by troykelly** [comment]
@aSambuu Flutterflow don't consider it a bug sadly. This "feature" will remain as is - you can't substitute variables in this way.

**Comment by aSambuu** [comment]
> @aSambuu Flutterflow don't consider it a bug sadly. This "feature" will remain as is - you can't substitute variables in this way.

I wasted 2 days searching for the error because I didn't know there was such an error. Now reverting the settings to not use group call header.

**Comment by smr-dev** [comment]
I am also experiencing this bug. Exactly as you have described it.

When I try to use a variable in an API Group, the variable does not get added, only the parameter string text aka:

[auth_token]

Whereas when you use a standard api call, the variable gets inserted, instead of being added as a string as above.

Clearly there is a difference in the way these are getting executed.

If this is not going to be looked into, I will clearly just have to create a long list of individual api calls, which is quite repetitive, when you want to use variables in header request's.

**Comment by troykelly** [comment]
@smr-dev as above, FlutterFlow consider this a "feature" not a bug. In their opinion it is working as intended, you just have to create hundreds of individual API calls. Yes, it's not great. It's why we stopped using FlutterFlow - you might need to find a working alternative as well.

**Comment by rvirpsa** [comment]
Hmmm... maybe FlutterFlow can not allow to use variable in API Group base address if it's not works? I spend couple hours to analyze what is wrong till i found this post :(
