### ISSUE TITLE
Custom widget not compiling

### ISSUE THREAD

**Issue by ryanzh98** [FlutterFlow/flutterflow-issues#628]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the recent update, custom widget is completely broken for me. Even the default boilerplate code can't be compiled.  There is no error or any response after clicking on compile button however on browser console, I am getting this error.

main.dart.js:4508 Uncaught TypeError: Cannot read properties of null (reading 'toString')

### Expected Behavior

No response when clicking on compile button on "custom widget" page

### Steps To Reproduce

1. Go to Custom Widget
2. Copy boilerplate code
3. Click compile

### Bug Report Code

ITEels/1zIt1n7xF7rnqbMZanQMwGkQ5a7sviu5+FBQaI+P0O4kpdvf8RFhWcuqHenxmME2YoEUdw/yOkuPUGsE4OS2BUYhY1c9hUxDhfFmlVK3XBc2eRXRDO8BUfkCB0J+jvyVCKfh0SGQi116EAOSub3qCf9qOYwx5e6fDbOY=

### Context

unable to use custom widget

### Additional info

-

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Android/IOS
- Browser name and version: Chrome Version 111.0.5563.65
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @ryanzh98 - Please update the FF editor for latest updates and check again. It should be fixed in latest updates. Thanks

**Comment by agreaves** [comment]
Hi @ryanzh98, in order to fix you must first fix the project errors in your project. They are causing issues preparing the code for compilation.
