### ISSUE TITLE
Cached Single Document Query Causes Issue On Page - Looking for a List

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#629]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using AppLevel/PageLevel query caching (with Firebase) using Query Type = Single Document you get errors in the code : The argument type 'Future<PlansRecord>' can't be assigned to the parameter type 'Future<List<PlansRecord>>?'

- this behavior happens on App level or Page level cache. 
- if you switch the query to get the document by reference it is corrected since it knows its getting a single document
- there are many instances where you want to query though and return a single document and do not want to store the document ref

THE ISSUE when turning on cache the FutureBuilder is looking for a List<RECORDS> but it is getting <RECORD>
`                      child: **FutureBuilder<List<PlansRecord>>**(
                        future: _model.testPageLevel(
                          requestFn: () => queryPlansRecordOnce(
                            queryBuilder: (plansRecord) => plansRecord
                                .where('user',
                                    isEqualTo: functions.userLoggingAsOrUser())
                                .orderBy('start_time', descending: true),
                            singleRecord: true,
                          ),
                      `

### Expected Behavior

be able to cache a single document query. 

### Steps To Reproduce

1. add a query with either app/page level caching
2. it should be a Query with a return type of Single Document 

### Bug Report Code

IT4si87huJJOxLRb+KrAb/l7/Cc4OW46ROcwscsZbw4bB4zqPLJ/Y+PSYlFVUs+/TGlhHGeguFoCpvTKjvHxFew4Gyutb4hOwalQdTvJUXq8RZCOEYeeWEZRBcZNCEy54J6NuBEmJtdfdCEt6l6qAueyYC/qJ5+/Zwh9f6PHaOI=

### Context

Currently you cant use caching on Firebase queries with Query Type = Single Document

### Additional info

![CleanShot 2023-03-18 at 16 37 44](https://user-images.githubusercontent.com/101305587/226142552-75d1fcca-f71c-4a27-a867-de6e08dd7a42.png)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @trevorFields, thank you for the bug report! This will be fixed in the next deploy. Closing for now, thanks again!
