### ISSUE TITLE
Google Maps Widget - Bottom Sheet Parameter Passing

### ISSUE THREAD

**Issue by tas246** [FlutterFlow/flutterflow-issues#630]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Attempting to follow this tutorial:

https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/base-elements/googlemap

Specifically the "Showing marker data in bottom sheet" section.  Step 4 requests the parameter be set to type "Record".  This does not exist.  Nor does "Document".  

It seems like this functionality is broken for GoogleMap widgets that are displaying a list of FireBase LatLon documents.  

### Expected Behavior

Expect to be able to pass a document reference to a bottom sheet containing the details of the marker tapped.

### Steps To Reproduce

1: Create blank page
2: Add Google Maps widget
3: add backend query to firebase for list of LatLon data
4: set the markers source to be that list
5: Add an action attempting to pass the marker document to a bottom sheet.
6: Confusion

### Bug Report Code

IT4whvLq05N2obVE7c+BbMdKhiYXMjska4I3jtZxZCs8JL7oPOwifPfDN0pvTLzhY0FiJWf9gTse/PfqheOeLcY7H0meGaE6zpBuTxXMXkKVac2KC82zfW1SGdFRCBGlyKWj3CUlHO91SFIb62a6NunIYC3dNYzLNjEzR+aLKdeK2SrDX1iXc2URm05KZDPz

### Context

Cannot perform needed functionality (bottom sheet details of map icons) on any map that has a list of LatLons versus just 1.

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: MacOS
- Browser name and version: Safari/Chrome latest versions
- Operating system and version affected: N/A
```

**Comment by bulgariamitko** [comment]
I think in this case type Record is a type Document. This is an old documentation and it needs to be updated.

**Comment by tas246** [comment]
> I think in this case type Record is a type Document. This is an old documentation and it needs to be updated.

I think it's more than just a documentation issue.  When attempting to add the action to the GoogleMap widget to pass the parameter to the sheet, there is no "Document" or "Record" option for the parameter.  It only has <list>Documents, with no way to specify which one was tapped.

**Comment by tas246** [comment]
https://community.flutterflow.io/c/discuss-and-get-help/marker-record-where-is-it

Other people are asking this as well.

**Comment by bulgariamitko** [comment]
Thanks for reporting that. We will see what FF team has to say about it.

**Comment by agreaves** [comment]
Hi @tas246, thanks for submitting a report! You will only see the option for "Marker Document" if you are setting the GoogleMap from `Marker Type -> Document` and not `LatLng` as you were doing. Hope this helps!

**Comment by thedav22** [comment]
I have the same issue, but my marker type is set to document. I can see an option for "Marker Document," but it comes up as "Conditional Value," not a document. See below.

![image](https://user-images.githubusercontent.com/85451405/232676749-27e93114-2880-4789-b626-76fe18364f72.png)

**Comment by welfoz** [comment]
Hi!
Any news about the fix or a workaround ?

**Comment by bulgariamitko** [comment]
@thedav22 I am not sure but from your ss I think you need to use the markers Documents variable and not the Marker Document. I mighty wrong about it, can you test it?

**Comment by thedav22** [comment]
There is an option for "current index" under Marker Documents that works fine, thanks. My issue is resolved. Still confused why "Marker Document" shows conditional values, though.

**Comment by TeamCS1** [comment]
> There is an option for "current index" under Marker Documents that works fine, thanks. My issue is resolved. Still confused why "Marker Document" shows conditional values, though.

I try and do this by selecting Item Index then it brings up three further options; First, Last, Specific Index? Which did you pick as I'm super confused.
