### ISSUE TITLE
Designe Setting => Error when clicking on "No design selected"

### ISSUE THREAD

**Issue by parisetflorian** [FlutterFlow/flutterflow-issues#631]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on "No design selected", I get a console error, and nothing happens. 
<img width="1728" alt="Screenshot 2023-03-19 at 11 18 54" src="https://user-images.githubusercontent.com/7931903/226168966-b9f7b49e-f7f4-4439-bf8e-780941615a6e.png">

### Expected Behavior

I don't know.

### Steps To Reproduce

1. Go to preference
2. Theme
3. Click on "No design Selected"

### Bug Report Code

ITESz/Hqx89grulZ+7rMde5QhQIgQ0QnU7gnlO1ucx4dIuuqPZYIZff4bUNKTMzgekFHeWL8+V8BpNbNueHtMvY7EzWrRbpx0JVPFg3LTnmgV4ykPpa3dXF8J5tnGB2z4aW0kBBNBNJ2LHA9wU61Nq3qNleeY8aSfxBlZ7vfcPo=

### Context

https://app.flutterflow.io/project/test-wb8ke1

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @parisetflorian - I can't re-produce the issue. Refresh the browser and also make sure you got all the latest FF updates. 
No environment details. Please add these details if the issue still persists. 

As this is not a wider issues, I'm closing the issue. Let us know if the issue persists still in your project. We can look at your project level. Thanks

**Comment by parisetflorian** [comment]
Hi @hariprasadms, I still have the issue on my end :)
Did you manage to test this on my project: https://app.flutterflow.io/project/test-wb8ke1

- FlutterFlow version: 3.1
- Browser name and version:  Version 111.0.5563.64 (Official Build) beta (arm64)
- Operating system and version affected: MacOS Ventura 13.2.1

I've created a new project from scratch, and I don't have a problem there. 
The project that has this issue was copied from the ChatGPT app template.

I hope it helps.

Cheers,
Florian
