### ISSUE TITLE
Container width & paddings

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#632]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Container with width = 100% can have right padding

### Expected Behavior

I'd like to have a right padding like left

### Steps To Reproduce

1. create an empty page
2. Add a column
3. Inside column add a row
4. Inside row add a container
5. set container width to 100%
6. add left padding = 10 -> ok
7. add right padding = 10 -> no right padding

### Bug Report Code

IT40jcjfz4VNsbQC7a6JY8JF9Sc5Jjs+bYJEmNV7aCosfZT2BLMcec/RVERWXu2+Y1Z+J02jv2oW0+iJhdnIG8cpHxebGIBI1pBubQzJXnmhRbXWFJWgYmpfO8NTfVTG1sCk3R57ALNZdV0t1GGMLuivFwXBK7LXDDI8Dq/LZO4=

### Context

I wanted to set a background color for an entire row and I don't know of any other way than to use containers

### Additional info

<img width="1003" alt="FF-container-width-issue" src="https://user-images.githubusercontent.com/1261851/226173220-611d0af9-05f8-4d22-8174-022ba7592427.png">

### Environment

```markdown
- FlutterFlow version: 3.1 released March 17 2023
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.64
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @blondie63 - As per flutter layout rules what you are trying to do is technically is not possible. So you should expand the container inside row and add padding. 

It is not a bug and working as expected.

**Comment by blondie63** [comment]
@hariprasadms This you said is not true, i asked to chatGPT and also tried it creating a test project attached here
This is the chatGPT answer:

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Flutter Example')),
        body: MyColumn(),
      ),
    );
  }
}

class MyColumn extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Expanded(
          child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              return Row(
                children: [
                  Container(
                    width: 10,
                    color: Colors.red,
                  ),
                  Expanded(
                    child: Container(
                      width: constraints.maxWidth - 20,
                      color: Colors.blue,
                      child: Text(
                        'Text in container',
                        style: TextStyle(color: Colors.white),
                      ),
                    ),
                  ),
                  Container(
                    width: 10,
                    color: Colors.green,
                  ),
                ],
              );
            },
          ),
        ),
      ],
    );
  }
}

In this example, the left padding is represented by a Container with a width of 10 and a red background color, while the right padding is represented by another Container with a width of 10 and a green background color. The main Container containing the text has its width set to constraints.maxWidth - 20 to account for the 10-pixel padding on both sides, and it has a blue background color.



[main.dart.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11026744/main.dart.zip)

**Comment by blondie63** [comment]
@hariprasadms Hi Hari, have you seen my previous?

**Comment by Kainkainkain** [comment]
Just put the padding on the row.

create an empty page
Add a column
Inside column add a row <- use this guy for your non-background coloured padding.
Inside row add a container
set container width to 100%
