### ISSUE TITLE
Selecting DateTime Format on an If/Then/Else condition returning a DateTime causes crash

### ISSUE THREAD

**Issue by nogoodconfig** [FlutterFlow/flutterflow-issues#633]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When populating a text field (in text widget, or button widget label at least), and configuring an If/Then/Else that returns a DateTime object, selecting 'DateTime format' from the 'Available options' drop down, causes the 'Set from Variable' window to grey out completely, and the UI to become unresponsive.

### Expected Behavior

1. Create text field
2. Select 'Set from variable' for the text value
3. Build an If/Then/Else condition that returns a DateTime Value
4. Should be able to set a DateTime display format

### Steps To Reproduce

1. Create text field
2. Select 'Set from variable' for the text value
3. Build an If/Then/Else condition that returns a DateTime Value (e.g. in testing - if CombinedText (set to 'Test') is equal to 'Test', then Global Property > Current Time, else Global Property > Current Time)
4. Select 'DateTime format' from the 'Available options' drop down
5. Observe the window grey out, and the UI become unresponse

### Bug Report Code

ITFfls/l6otIsdtK0L6IK8FFuDwXOV8cTYMvjuphcx4cIYjsEJYAP/f8U0NKT8Old1VYJGD8uGUew/DQvuLDCscoBwiqc6ZY0JVAUTyXLWOib8m2PbuSVnMlBcNTIXWO5qSGkR1SKfthdEYa6nGDNa3qNleeY8aSfxBlZ7vfcPo=

### Context

Unable to format DateTime values output from If/Then/Else condition within text fields on multiple widgets (e.g. Text, Button). Causes limitation in building out a UI.

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome 110.0.5481.177
```

**Comment by hariprasadms** [comment]
Hi @nogoodconfig - No able to re-produce the issue. In above steps, step 2, what you value you are setting from variable? steps is not clear. Please share images or a quick video showing the issue. Thanks

**Comment by nogoodconfig** [comment]
https://user-images.githubusercontent.com/19488645/226395007-2ad4456c-6bc2-4699-926c-31c0874c8f44.mp4

Sure, see link.

In this example, setting 'If current time is set' just to reproduce the issue and build a valid if/then/else block. But experiencing it with other logic too. Note the window greying out at the end. Tried on Chrome 111.0.5563.64 and Safari 15.1.

**Comment by hariprasadms** [comment]
Hi @nogoodconfig, Thanks for video details. I can reproduce the issue now. I think this is really an edge case. However, the grey page should not be displayed and it should be fixed. Thanks again.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next update.
