### ISSUE TITLE
Translation inside Action

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#634]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On action setting there a button to translate a string but doing nothing

### Expected Behavior

As logical i'm aspecting that this button open the translation form

### Steps To Reproduce

Create an action like one you can see on screenshot

### Bug Report Code

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs8JJToPLAUZ8zBM05vZry6SkFpeWCZpGEyxvfqvfHpLvUqIkyWfbU5/qtUbQnxfD+VM7XSO5bsfW1QFp9hf2Ky1p2zpSRBBOteR0Ihw2GIIvDLVhXaJpO3CzEnDfKlKdeK2SrDX1iXc2URm05KZDPz

### Context

<img width="1838" alt="FF-action-translation-issue" src="https://user-images.githubusercontent.com/1261851/226191877-0105bdb5-2eaa-4e26-8a54-71b69d78d4e1.png">

### Environment

```markdown
- FlutterFlow version: 3.1 released March 17 2023
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.64
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by blondie63** [comment]
When i close Action editor, below i can find the translation form !
Anyway this is UI bug

**Comment by hariprasadms** [comment]
Hi @blondie63 - Thanks for reporting the issue. I can re-produce the issue. Translation form displaying below the action window instead displaying top of the window.

**Comment by agreaves** [comment]
Hi @blondie63, thanks for the bug report! We've updated this to close the dialog and show the translation form when you press this button. This should be present in the next deploy!
