### ISSUE TITLE
FFPlacePicker doesn't reliably parse city

### ISSUE THREAD

**Issue by MaggieThomann** [FlutterFlow/flutterflow-issues#636]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the address result from the PlacePicker widget, city isn't always parsed properly. Two examples are the following addresses:

- 420 College Avenue, Staten Island, NY 10314
- 75-41 186th Street, Queens, NY 11366

The city is null when parsing these. I believe it's because the PlacePicker widget expects city to be defined as a "locality" type in the Google Maps Places API response, but in the 2 cases listed above, the city is actually defined as 3 other types: "sublocality_level_1", "sublocality", and "political".

<img width="437" alt="Screenshot 2023-03-19 at 11 00 08 PM" src="https://user-images.githubusercontent.com/15825518/226212252-4ac696e1-59f8-4d6c-b399-a626d1ca06d1.png">

### Expected Behavior

In the cases of the addresses mentioned above, I would expect "Staten Island" to be parsed as the city for the first address and "Queens" to be parsed as the city for the second address. 

For other addresses I tried, parsing the city out by filtering for the "locality" type does work correctly. Maybe there can be some sort of priority? "locality" is the preferred type, but then if "locality" is unavailable, perhaps "sublocality" can be considered as the city?

It [looks like](https://issuetracker.google.com/issues/35820656) this has likely been an issue within the Google Maps Places API for a long time (and specifically breaks with NYC addresses 😆). And it [seems like](https://developers.google.com/maps/documentation/geocoding/requests-geocoding#Types) Google considers "sublocality" to be the first-order civil entity below a "locality". Given that, it seems like a safe change to rely on "sublocality" if "locality" doesn't happen to be present in responses like this.

### Steps To Reproduce

1. Create a new page
2. Add the PlacePicker widget
3. Add a text field with the address.city result from the PlacePicker widget
4. Run the project and enter "420 College Avenue, Staten Island, NY 10314" in the PlacePicker widget.
5. City will be blank.

### Bug Report Code

N/A

### Context

We need to be able to properly parse the address to pass it in the parsed format to our shipping partner. In this case, sending a blank city to the shipping partner requires manual intervention on our end.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: All
- Browser name and version: Version 111.0.5563.64 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.2.1 (22D68)
```

**Comment by hariprasadms** [comment]
Hi @MaggieThomann - Thanks for reporting the issue. As you have already pointed this is something existing issue in google places API, I think it is likely not possible to fix in FF as we directly consuming google api packages. However, I can mark this as a bug. Development team can decide what best can do around this issue. Because of nature of the issue, ETA is not possible to provide.

**Comment by agreaves** [comment]
Hi Maggie! Thanks for the heads up, that's super frustrating on the Places API side! From that bug, I think you're right that it should be safe to fallback to "sublocality" if "locality" is not present, so we'll add that to the place picker logic. This change should be present in the next deploy! 🙂

**Comment by MaggieThomann** [comment]
Sweet, that would be amazing @agreaves! Thank you!

**Comment by MaggieThomann** [comment]
Just checked and this works great for me now, thanks @agreaves!

**Comment by programad** [comment]
This is still a bug on web and mac version. When I search for a city, it goes usually fine. But if I search for a full address with street and number, it returns me the neighborhood in the City field. C'mon, guys, this looks simple to fix, just need to parse the Address when getting the worst case scenario.

**Comment by programad** [comment]
Hey, @hariprasadms , check my comment above. This should fix for all situations. Including mine.

**Comment by camopy** [comment]
This issue is still present here, when I select City in FlutterFlow it actually displays the neighborhood.

I think a possible solution is to allow us to select the desired fields directly from the google maps api response.

In my case, cities are located on the `administrative_area_level_2` tag, and neighborhoods on the `sublocality_level_1`, which is not the case for most other countries.
