### ISSUE TITLE
in action sequence the updated data is not transferred to next action

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#637]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. im trying to create documents with a a field transaction no 
2. i have a separate collection "counter" to maintain transaction no from duplicating
3. each created document will have transaction no increamented by 1 (from counter document )and use that no in transaction doc
4. now in action action sequence i have added two action update document which  increase the count no (action 1)and use this no in transaction no
5. but this new increased no is not used by the next action but rather the old no (before increamented) is used 
![download (29)](https://user-images.githubusercontent.com/37708853/226279065-df43cb47-4275-43a3-b54c-a32810baa683.png)

### Expected Behavior

1. the updated data from previous action should be available for next actions
2. this is available for document created from action output.but not for document updates 

### Steps To Reproduce

1. have two collection one is counter with (single document in this collection ) field current transaction no(set 1) .and another collection transaction with field transaction no
2. now in a action sequence have first action to update the counter with increment of 1(current transaction no)
3. now in next action create a new document transaction with current transaction no (from counter )
4. the increased no is not used by next action

### Bug Report Code

IT8Wl/KA4Y92rtdc1pPqL+9VlikXQz9/U4JIicNxRQgdCLLoOoYXe87RQBduXdOnSng/O02KpHofw9XsmOL1DsYnAxusf4Rl+ZAJFwGVTWqyRZSKEpawZXNAJ+NPGEyD17e7rgl+A7BaLlI+xWO6Ct7IVgzYHu/0O2wjOf2XNdvJjFWkLQ3/JRQy+2gIMGmUCvUXZlDq+f6QspZl1eTjzw==

### Context

when multiple user create a transaction at the same time,this is creating the SAME transaction no for all the documents at that particular time.i need it to be increment of 1 without any repetetion
im facing this issue only when multiple user create transaction at the same time - i will face this issue big time because we set a deadline and will receive multiple entries before the deadlines

### Additional info

if multiple user start this action,then in counter document the values is incremented by no of users started but in transaction all are same value. 
there is "action output variable name" Option available for new document created but it is not available  for updated documents. if this is available for updating document then i believe this issue be resolved 

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:web
- Browser name and version:android Version 111.0.5563.65 (Official Build) (64-bit)
- Operating system and version affected: win 10 pro
```

**Comment by Xander0x** [comment]
Getting a similar issue, would like to see this looked at.

**Comment by agreaves** [comment]
Hi @padeepz, thanks for the bug report! This is currently not possible because we are not actually updating a local document but is updating the document in the server. We'd have to apply any changes locally as well every time in order to accomplish this, which is not really feasible.

I think the best course of action is to either keep track of the updates on your end locally (and use the updated value), or do a Firestore Query action to get the up to date document and use that in a subsequent action, so you are reading from the server.

I'm closing this for now as a feature request (an option to read the latest document before updating it), but would love to hear more thoughts on how to accomplish this.
