### ISSUE TITLE
Call a number (action) is not working

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#64]
I am trying to add call a number action but is not working its show empty in the path 

<img width="994" alt="Screenshot 2022-10-30 at 02 37 32" src="https://user-images.githubusercontent.com/40029858/198861859-30f1fb03-5adf-4a24-9575-34c3342e834e.png">
<img width="630" alt="Screenshot 2022-10-30 at 02 37 53" src="https://user-images.githubusercontent.com/40029858/198861864-d44ec1d3-05d4-4235-aef7-eb60244514f9.png">

**To Reproduce (required)**

1. create a button 
2. add call a number action 
3. in the call a number action fields choose specific value 
4. add any number for example 1231313
5. go check developer menu 
6. find the button you have create 
7. in the action of the button you will see schema and path 
8. the path is empty which should have a number inside it and not empty

**Comment by bulgariamitko** [comment]
You need to use the template in order to submit an issue. Please follow this example 
https://github.com/FlutterFlow/flutterflow-issues/issues/14

**Comment by wenkaifan0720** [comment]
Hi sergedahdouh. This is indeed a bug. I have pushed a fix which should be live this week.

**Comment by sergedahdouh** [comment]
> You need to use the template in order to submit an issue. Please follow this example #14

i have update it how you can reproduce the error
