### ISSUE TITLE
Infinite loading after I paid for extra custom domain

### ISSUE THREAD

**Issue by slvkrvnsv** [FlutterFlow/flutterflow-issues#641]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Infinite loading of both web and mac FlutterFlow apps – only branded spinner visible on app launch.
<img width="1440" alt="Screenshot 2023-03-20 at 15 48 27" src="https://user-images.githubusercontent.com/118440068/226392658-2fbddb34-bb06-4c37-8b89-78172d8691bb.png">

### Expected Behavior

One more custom domain added to the plan

### Steps To Reproduce

1. Profile
2. Add extra domain
3. Pay
4. Get modal "Processing"...
5. (In my case it stuck processing for 10 minutes...)
6. Refresh the page
7. Infinite loading

### Bug Report Code

can't access that...

### Context

I wanted to publish my new app on the new domain

### Additional info

I received the receipt by the email.
But in the bank app transaction is still pending, but the amount is slightly lower.

### Environment

```markdown
- FlutterFlow version: 1.1.53
- Platform: macos
- Browser name and version: App / Chrome
- Operating system and version affected: Ventura 13.2.1
```

**Comment by katherineqian** [comment]
Hi @slvkrvnsv, 

I've been able to locate and fix what I believe is the source of the issue. It should be fixed now - if so, could you confirm?

**Comment by slvkrvnsv** [comment]
Hey Kathy,

It's all good now, thank you! 👌
On my way to publish to the new custom domain ;)
Yay
