### ISSUE TITLE
Irresponsive Screen 

### ISSUE THREAD

**Issue by BlueCatSoftware** [FlutterFlow/flutterflow-issues#646]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The upload button is cut of the dialog and can't be clicked neither scrolled in order click
![image](https://user-images.githubusercontent.com/73719772/226588129-9c1e3040-5edc-44e8-a848-9572514284a9.png)

### Expected Behavior

For smaller screen like mine i expected the dialog to be scrollable in order to access the button.

### Steps To Reproduce

1. Create a firebase project 
2. Then try deploying firestore rule
3. All these should be done on 14 inch pc

### Bug Report Code

ITFThvHlvM9goeEA+Kn2Y+1FmScQM0McWOdEl+tuZwgbIoznBqQQYMmlUBRvONzmaVNcPmL9oGcBpfSNiuDEFfcpAyubbIM71pBIZxXke2imMsmlO7qOP2pAQJ9PGn2P56en3BJBPtt2SkIY12a2fu69b3TDFOu/Zwh9f6PHaOI=

### Context

I can't upload firebase firestore rule, except i use my 24 inch monitor, which is very annoying.

### Additional info

![image](https://user-images.githubusercontent.com/73719772/226590024-f18e0311-bebb-4436-98fd-fa5d0814a23b.png)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected: Windows 10
```

**Comment by wenkaifan0720** [comment]
Hi @BlueCatSoftware. For a temporary solution, could you zoom out a bit to show the full dialog? I'll fix this in our next update.
