### ISSUE TITLE
All "Create Account" actions share "Set Fields" values.

### ISSUE THREAD

**Issue by evaqum** [FlutterFlow/flutterflow-issues#652]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Updating any "Create Account" action's "Set Fields" reflects these changes on other "Create Account" actions in the project.

### Expected Behavior

Updating any "Create Account" action's "Set Fields" should only affect the action we're updating.

### Steps To Reproduce

1. Setup Firebase, enable authentication. (kinda optional since the bug is in the FlutterFlow editor, and you're not required to finish setup to add auth actions)
2. Create "users" schema in firestore.
3. Populate schema with suggested fields and any other field, that we will set on signup (ex. "signup_flow" with a "String" type).
4. Create a new page.
5. Add a field for Email, Password and Password Confirm.
6. Add a button.
7. Set its action to "Create Account", choose "Email" as a provider, match all required inputs (email, password, password confirm).
8. In that action, set the field that we added to user schema to any value (ex. set "signup_flow" to "alpha").
9. Following previous steps, create another signup button with same action, except set the field to any other value (ex. set "signup_flow" to "beta").
10. Click on the first button, open action tab, witness how our field value magically changed to what we set for the second button (ex. "signup_flow" is now "beta").
11. Try to change that value back to what it was before and see how it changed in the second button as well.
12. Enjoy infinite loop of changing values back and fouth repeatedly.

### Bug Report Code

ITESiMjfsI5grsNZ1aqAKMdQhQIgQ0QnU7gnlO1ucx40Ib2vEJoTPuP7Q0NKTdOAem9UD2GZnkgKwujqjvztEPE7HE+aGb5k0JVAVQLiXlKuRcnXPM2KVXN6HfpgIWKPy5jVkSYnJbJvc1piwE+pNa3qNleeY8aSfxBlZ7vfcPo=

### Context

In my app, I have two signup flows. 
One is for mobile, which is placed on its own page, and another one for desktop, which can appear as popup on any page. 
Both need to set one property in user's account which I got from action that is executed in popup component on desktop and on signup page on mobile respectively. But you can't really do that. Because once you set any field in one "Create Account", it reflects in the other one, where previously mentioned action output variable isn't accessible.

### Additional info

https://user-images.githubusercontent.com/54950997/226913235-eb1f7dc0-5943-4339-8d15-e783c6c41a34.mp4

### Environment

```markdown
- FlutterFlow version: v3.1 (released March 21, 2023)
- Platform: Web
- Browser name and version: Google Chrome 111.0.5563.110 (Official Build) (64-bit) (cohort: 111_Win_110_Ramup) 
- Operating system and version affected: Windows 10 (19045.2075)
```

**Comment by evaqum** [comment]
@CasperJ as far as I can remember this is the normal behavior of action outputs. They, as well as API responses are stored in the component (or page) model and could be used across that component. I can agree that this is a little confusing, but I guess this is just the intended behavior. Not really related to the issue that I faced 😄

**Comment by victoriahuang1** [comment]
Hi @evaqum , this behavior is actually by design. The intended usage is to have a single way of creating accounts, but then you can follow that up in the action flow editor with other actions -- this should allow you to then implement your 2 separate flows.

Does this work for you?

I agree that the UI/UX is indeed confusing -- I can see if we can make this workflow more intuitive.

**Comment by Zhixory** [comment]
I had the same issue; My solution was for PC-view I removed the set fields from the create account section in Auth-action. Then I created another action right after, updating the user reference of the authenticated user, with the fields. The fields will now not be replaced!
