### ISSUE TITLE
Initial value for TextField NOT updated on underlying AppState change

### ISSUE THREAD

**Issue by dmk23** [FlutterFlow/flutterflow-issues#653]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1) I have complex form logic driven by the underlying AppState, which persists over sessions

2) This includes populating the initial values of TextFields (and other form elements) from this persisted state

3) The state behind the TextField may change by a range of actions (new data loaded by custom actions, change in another field conditionally triggers change of display, etc)

4) However when there is this underlying change of state - TextField keeps displaying outdated initial value

5) It is not feasible to always use SetField action to fix the problem - as state could change by many triggers

### Expected Behavior

I'd like to have an option of forcing reload of the TextField's initial value on every widget rebuild (with possible exception after user changed the input, but before the onChange action chain is fired)

This way the underlying state will always be the "truth of record" regarding the form field value, and my own application logic will take care of saving/ manipulating it there via onChange action chain

Same initial value reload logic should apply to every other available form field...

### Steps To Reproduce

1) Create a TextField with initial value set from AppState variable
2) Create a PeriodicAction that updates this variable every 30s to current timestamp and redraws the page
3) Observe that as the action is running the TextField value is not changing
4) On hard page reload, the TextField of course initializes correctly from persisted state

### Bug Report Code

IT4oi/Lqw412rt8D1brUdPlsgSQWQ319apEo0cpBay0jF7KuDLMqY8/RVERoOeqqSnNhMU38kWoW3M7lvfD9F/knEzqYf6ZA/6oJSjvxQmq7V4i7FJWgZEd5Gd9PCh2F1sO3mB5vBLNqLk4d11OtON+/Hx/UJIOyNVceDq/LZO4=

### Context

This is a showstopper

It is impractical to build complex/conditional/dynamic form logic without centralized state management

### Additional info

The Bug Report Code provided above refers to a TextField created with exact above "Steps to Reproduce"

### Environment

```markdown
- FlutterFlow version: v3.1 (released Mar 20, 2023)
- Platform: Web
- Browser name and version: Chrome Version 110.0.5481.178 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by victoriahuang1** [comment]
Hi @dmk23, thanks for the report.

This is actually the expected behavior -- to change the value of a TextField, you should use the "Set Field" action. If this doesn't work for you, can you provide your use case so that we can understand better how to support your needs?

In the meantime, closing this ticket and putting down setting the value of the TextField to a variable as a feature request.

**Comment by dmk23** [comment]
@victoriahuang1 SetField action does not work for us

As stated in the issue report, our use case is a complex dynamic form that needs to render from the state JSON. All sorts of logic inside custom actions could modify the state, and we just want all widgets to properly re-render

We found a silly ugly hack to fix this - because all our form elements are all inside ListView children. Looks like ListView does a complete rebuild of all elements, but **only if** the number of child components changes. So in all our custom actions we added the code that always changes the size of the list by adding/removing hidden dummy rows

Just the fact that there is no consistent behavior on how components re-render means this is a bug and not a feature request

**Comment by danielmeza** [comment]
I'm having the same scenario here, a text field inside a ListView, I bind the Initial Value to an app state and nothing happen, even I try to update the value using the "Set Field" action in the On Initialize component stage but nothing happens, I check the ListView to rebuild when page change and page changes when the App State is update but again nothing happen, this is a bug for sure.

**Comment by danielmeza** [comment]
links of more users having the same behavior:
https://community.flutterflow.io/c/discuss-and-get-help/update-form-field-from-an-action
https://community.flutterflow.io/c/discuss-and-get-help/updating-form-text-fields
https://community.flutterflow.io/c/discuss-and-get-help/update-the-value-of-a-textfield-with-the-return-of-a-custom-action
https://community.flutterflow.io/c/discuss-and-get-help/update-value-of-textfield-in-listview-dynamically-without-refresh-page
https://community.flutterflow.io/c/discuss-and-get-help/how-to-dynamically-update-the-value-of-a-textfield-from-a-local-state

**Comment by smostovoy** [comment]
I have a similar issue: When I navigate to the same page but with a different firestore document as a reference all fields are changuing their initial values except text_field. @victoriahuang1 is  this also by design, a different issue or we can reopen this issue?

**Comment by victoriahuang1** [comment]
@smostovoy this sounds like a different issue. Please open a separate github issue.

**Comment by thekevinj** [comment]
i am having the same issue - i have a row of data stored in Page State and am wanting to use fields from that row as the initial value for a a number of TextFields but they always show as blank 
If i set the  Label text from the same source it works perfectly.  Why would one behave differently to another.

**Comment by yoooyle** [comment]
as @thekevinj pointed out, the label updates but the initial value does not. the inconsistency itself is a super misleading and unexpected behavior, no? @victoriahuang1

**Comment by Doetheman** [comment]
Having the exact same probelm

**Comment by paulmorino** [comment]
I'm also having this problem and this is causing major loss of time by trying to hack a feature that should be simple and a nobrainer.... this is definitely questioning keeping flutterflow moving forward in the developpement of the app...

**Comment by MauruschatM** [comment]
Still a huge problem. Please fix.
The initial value of textfields only change, when using a component and listing it for every possible state they could have:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/60385231/a3f33d4e-c0da-468b-9967-5650353f12c6)

**Comment by cragroc** [comment]
Can you re-open this? Clearly from the comments there is a lot of demand for this to work as expected.

Adding my current use case as requested above by @victoriahuang1 

* I have a TextField that should show the updated map center when the map is moved. (I need a TextField so the user can edit it, Text widget won't work here.)
* Set TextField initial value to Widget State, Current Map Center
* GoogleMap widget does not support any action triggers except for On Marker Tap. So I can't do an action to Set Form Field when the user moves the map.

**Expected**: TextField widget will display LatLng of map center as configued in Initial Value property.
**Actual**: TextField text is never updated on page rebuild to show LatLng even on initial page build. As noted in other comments, a Text widget works, and the Label Text property of the TextField widget will also work.

Also, based on the text in Victoria's closing comment it's not clear this was really triaged accurately.
   "putting down setting the value of the TextField to a variable as a feature request"

The request isn't to set the value of the TextField to a variable, we can already do that. The request is that it should work like every other place you can set a text field to a variable. Like here in my testing page for example:

<img width="631" alt="image" src="https://github.com/user-attachments/assets/4830be11-a1d8-4877-96c7-cdcdb0dace37">
