### ISSUE TITLE
Function has one or more invalid arguments. Function name ()

### ISSUE THREAD

**Issue by guillo270120** [FlutterFlow/flutterflow-issues#654]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when I create a new custom function mene sends the error message: Function has one or more invalid arguments. Function name.
but I have checked errors and it does not have any since if it compiles and the argument works fine

### Expected Behavior

remove that error to be able to use test mode

### Steps To Reproduce

1. create new custom function 
2. DateTime fechaInicio(DateTime? fechaInicio) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  int year = fechaInicio!.year;
  int mes = fechaInicio.month;
  int dia = fechaInicio.day;

  return DateTime(year, mes, dia, 0, 0, 0);

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
3. check the project issues

### Bug Report Code

IT4el8j6yIt1j7xa+KX5bcJB/TssKUQgULhEiuxEcAwbF5CqE5oufuj+QHZVOMO/dFY3OlmI8WMz+vyLhePhCe4HPiiefLpP+ZZXFj3iUk6heJSWBc60VGpfLNxbGGmHzbWnghF7HOpZSi0MwHGULumAcHbaJLrAC0cvMc+XMofXpVnhGhzOXn0Jg1ZSfCvr

### Context

i can´t use the test mode because the issue appear in the project issues

### Environment

```markdown
- FlutterFlow version: web
- Platform:3.1
- Browser name and version:chrome
- Operating system and version affected: windows
```

**Comment by guillo270120** [comment]
after 9 hours somebody can do the triage?

**Comment by guillo270120** [comment]
after the recent update the problem still exists

**Comment by guillo270120** [comment]
i make a chat with the online support and they tellme that this is a bug on code editor that the team is working to fix please mark this as a bug

**Comment by agreaves** [comment]
Hi @guillo270120, thanks for the report and apologies for the late response. This is because the name of your function and the name of your argument are the same, which is not allowed. To fix you can simply name either of these something else. Very sorry for the lack of triage and response as I could have clarified this for you much sooner 😢.
