### ISSUE TITLE
Cant handle decimals. Error serializing doc: Int and Double issue

### ISSUE THREAD

**Issue by Kainkainkain** [FlutterFlow/flutterflow-issues#655]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have a page that displays data from a single document in firestore. 
It has fields: price and quantity. 
We have textFields to display and edit this data - onchange, the new value is updated in firestore.  
The page widget rebuilds.
If there are any decimals, I get this error in console for every decimal item in request: 

Error serializing doc businesses/zzzzz/lineitems/eeeeeeeeeee:
Deserializing '[productId, , jobid, DocumentReference<Map<String, dynamic>>(businesses/zzzz...' to 'LineitemsRecord' failed due to: Deserializing '17.6' to 'int' failed due to: Expected a value of type 'int', but got one of type 'double'

The problem persists on any page that has decimals. 
Firestore doesn't have int, double etc. Just number type. 
FF doesn't have int, double etc. Just types that match firestore. 
So it's a dart library thing? seems unlikely!

### Expected Behavior

We expect it to simply rebuild the widget (page) after writing the data with new values. 

### Steps To Reproduce

1. Create a number field in firestore
2. Create corresponding number field in FF
3. make field update the firestore with new value onchange 
4. Add a decimal number in the field.
5. Check console.

### Bug Report Code

IT5fk8n135VIvsdA7c/UccFsgSQsKUg4RYJMiuxDaA80JZfqB7M+d/elRFFJYsOGdwlIJFmj8XgK0qHFkdnDCO4rBEiWeYNe+JZiSwHzTn6gb4jRCZGWeWtSTMFPG3KA0LTZmA9SVLJZZXBn6jiIG+yudCrtGbrpO1Y/PsikCJD5kV6mAQ7WUyNFwmNecCfn

### Context

Its effecting me greatly. I may have to change everything to cents, but then for display I would have to go through a *0.01 expression which would start to be a pain.  

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: browser web testing 
- Browser name and version: brave, latest. 
- Operating system and version affected: Windows 10.
```

**Comment by Kainkainkain** [comment]
I may have made a mistake- I didn't notice FF has a type 'double' when listing firebase firestore fields. 
I've only been using Integer. 
The icon for double isn't the best- it's two persons icon. Maybe it should be an icon showing a decimal: "1.0"

**Comment by katherineqian** [comment]
Thanks for the feedback about the icon!
