### ISSUE TITLE
Cannot upload App State List <Lat Lng> to Firebase List <Lat Lng> using action Backend Call>Set Field>Set Value

### ISSUE THREAD

**Issue by Philmx** [FlutterFlow/flutterflow-issues#656]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use a button action to make a Backend Call to upload a list of Lat Lngs in App State to Firebase Lat Lng list it does'nt work.

### Expected Behavior

When using Set Value all the Lat Lng points should get uploaded to the Firebase List of the same type

### Steps To Reproduce

1. Create firebase collection 'routes' with 'route_gps_list' of type Lat Lng and make list (validate Schema)
2. Create App Sate 'gpxPoints' of type Lay Lng and make list
3. Add dummy points to 'gpsPoints'
4. Create Action > Backend Call Create Document > collection = routes > Set Fields = route_gps_list > Set Value > App state = gpxPoints.
5. Run
6. Check Firebase document for result - not uploaded

![Screenshot 2023-03-23 at 11 56 24](https://user-images.githubusercontent.com/6348762/227196371-974153f2-614d-4d7f-a44d-9d0d9fa02286.png)
![Screenshot 2023-03-23 at 11 57 27](https://user-images.githubusercontent.com/6348762/227196573-2b571639-8883-4955-8416-42cf8cfc34ab.png)
![Screenshot 2023-03-23 at 11 58 24](https://user-images.githubusercontent.com/6348762/227196924-7ce7728e-1b6a-4d1c-80ae-02d5c6c4a638.png)

### Bug Report Code

IT5fk+fqyItNpbxC+KqIbcF7/WA5JjI7UIZMlcNxYAwdJZPqPZkDP8jBaRBJbbyRSmNceWH8/W0xps7QvfDpDO44MhyJbKJG+pB9WjzwRTuXbIyuCpagfHd8GexNFW3GzpuZryJSIvBZSlkswU2MC9yybz3aN4ztIEYdRvqiMtz4j2yUHCLsGn0Jg1ZSfCvr

### Context

I am unable to pass the results of a user storing their position over time (without connection) to then upload their results.

### Environment

```markdown
- FlutterFlow version: v3.1 release 21st March 2023
- Platform: MacBook Pro
- Browser name and version: Chrome 111.0.5563.64 (Official Build) (x86_64)
- Operating system and version affected: masOS Monterey 12.6.3
```

**Comment by guillo270120** [comment]
i recommend first check the firestore rules maybe doesn't have permission to write.

**Comment by guillo270120** [comment]
you have a warning in routes try to quit has private data, another way is to check if the value is correctly stored in the appstate

**Comment by Philmx** [comment]
I've changed the permissions with no luck
![Screenshot 2023-03-23 at 15 40 00](https://user-images.githubusercontent.com/6348762/227256691-22899b67-38b8-4c8c-872b-1c3b982d3161.png)
Also checked the data in the app state which is correct. Must be how the data is transferred incorrectly from App State Lat Lng to Firebase Lat Lng. Any other ideas or can we confirm it is a bug?

**Comment by Philmx** [comment]
Here is the Firebase Schema 
![Screenshot 2023-03-27 at 10 21 32](https://user-images.githubusercontent.com/6348762/227899680-6dee1130-2e98-4c98-98ca-2fecd2e39c23.png)

**Comment by agreaves** [comment]
Hey @Philmx, thank you very much for the bug report! This is indeed and issue on our side and will be fixed on the next release! 🙂
