### ISSUE TITLE
Keypad glitch

### ISSUE THREAD

**Issue by LucasBene** [FlutterFlow/flutterflow-issues#658]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Everywhere where we use typing option (chats, posts, comments) and when keyboard appearing or we dismiss it on tap the screen is 'glitching' ? The move is not smooth as should be. There also the same problem when keyboard is open and i navigate to other page  then it looks terrible. Glitching and its not smooth.

### Expected Behavior

expected behavior of the widget should appear and disappear smoothly. 

### Steps To Reproduce

The issue is on every page where there is the option to type the message or text

This problem is on real devices so please check of the bugs and maybe there is quick solution.

### Bug Report Code

a

### Context

I try to accomplish fully functional and smooth interaction with the keypad. 

### Environment

```markdown
- FlutterFlow version: 3.7.2
- Platform: iOS and Android
- Browser name and version: Not aplicable. The bug is on real device
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hi @LucasSalamander - Thanks for reporting the issue. As of now the behaviour of the keypad across the apps is working as expected. All your observation can consider as enhancements around current behaviour of the keypad. Hence, I can mark the issue as feature request.

**Comment by LucasSalamander** [comment]
Hi @hariprasadms 

Thanks for your reply. Let me explain little bit more. Keypad working good and its behaviour is correct, but the screen is glitching when keypad appearing and disappearing. Video below

**Comment by agreaves** [comment]
Hi @LucasBene, thank you for the heads up and the bug report! I can see from the video what you describe, and I agree this is not the smoothest transition. However, unfortunately this is an underlying Flutter issue and there isn't much we can do about it on our end at the moment ([relevant Flutter issue](https://github.com/flutter/flutter/issues/120555)). The good news is it looks like a fix is on it's way and should arrive in stable in the coming month or two.

Closing this issue for now as we are awaiting this.
