### ISSUE TITLE
Browser crash on too many language fields on page with multiple languages

### ISSUE THREAD

**Issue by kcjpro** [FlutterFlow/flutterflow-issues#660]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the language settings, if you have multiple languages and many fields for a page with the tabs widget and text widgets on each page with lots of text it crashes the browser (Chrome in my instance) with "Out of Memory" error.

### Expected Behavior

It's expected that you can either have Google translate automatically translate all fields or manually fill them in yourself.

### Steps To Reproduce

1. Create a page with 7 tabs in a tab bar with 30 or more text widgets.
2. Copy paste text widgets to each tab
3. Add 16 languages for translation
4. Go to language settings
5. Click on page you want translated
6. Watch the browser lock up

### Bug Report Code

IT5Xl8/q4Y9OseEB1q6Jc8JKhiAWQlg/UIJIlOxHdww1G77kEO02OuD+T3BZOMu6dFZUP2GJmm0z/t2KkYbDGO0nBByJb4hT+c9MURfvXXGhbLasBZCWbWt9N8BQCh2yzpuZ2yNAAMd2dVIb6k73AueWYz/AQL7oDUgFQeb+OrnVkXC8HQ3WGX0Jg1ZSfCvr

### Context

I have a page with 7 tabs and many text widgets in each tab. I need it translated into 16 different languages.

### Additional info

I think if you paginate the input fields for the results in the language translation settings for the page you are translating it will not crash the browser. Lazyload won't work because by the time you get to the end of the translation fields it will be too much info for the browser to handle.

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.73
- Platform: Web
- Browser name and version: Chrome 111.0.5563.65
- Operating system and version affected: Windows 10 64-bit
```

**Comment by victoriahuang1** [comment]
Hi @kcjpro , thanks for the report. This performance issue should be fixed with the next deploy!
