### ISSUE TITLE
"Leave Project" doesn't work

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#661]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you in projects view and you try to leave a project you are added on it doesn't work.

### Expected Behavior

To be able to leave a project

### Steps To Reproduce

1. Get added to a project
2. Go into projects view
3. Click three dots in top right of that project
4. Click "Leave Project"

### Bug Report Code

N/A

### Context

You can still leave a project if you go into collaboration and remove yourself.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS/Web
- Browser name and version: Chrome 110
- Operating system and version affected: macOS Monterey 12.5.1
```

**Comment by organicnz** [comment]
Hi @johnbhiggins7. Thank you John for submitting the issue :)

I can confirm that the email invitee cannot leave the project :)

Tested: Safari

Video: https://www.loom.com/share/7131b71427f34ec0b2bb774f84162033

**Comment by wenkaifan0720** [comment]
Hi @johnbhiggins7. This will be fixed in our next update. Thank you!
