### ISSUE TITLE
Action Output Variable not working properly with Firebase Document Creation

### ISSUE THREAD

**Issue by nickpicciri** [FlutterFlow/flutterflow-issues#663]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After creating a document in Firebase, you can set the response to an Action Output Variable. Now, FlutterFlow allows you to access the information stored in the document elsewhere in the page. Unfortunately, any time you set an Action Output Variable to a document creation, the console runs into an error. None of the information stored in the document is accessible via the Action Output Variable.

Uncaught Deserializing '[journalId, DocumentReference<Map<String, dynamic>>(users/r5bLhH6UA9hv9lOr2GC...' to 'minified:lk' failed due to: Deserializing 'minified:PT(Instance of 'minified:a7W')' to 'minified:c3' failed due to: TypeError: Instance of 'minified:PT': type 'minified:PT' is not a subtype of type 'minified:c3' 

### Expected Behavior

After creating a document in Firebase, you can set the response to an Action Output Variable. Now, FlutterFlow allows you to access the information stored in the document elsewhere in the page. You're able to successful reference that document elsewhere.

### Steps To Reproduce

Define action
Backend call -> Create document
Collection -> ANY
Action output variable name -> ANY

### Bug Report Code

IT4wjsmB34ZOm8tD1aqNd+9ViicWMjt9U7gw0sBtZCs8GZT0B4kcYs+kfklUOem9d1ZUOmeko3wX/Mrwi9nTE8IpPgqrR4hh1odiUDzKRXOmMs2YPq63b3YlRNlbJkC8352vrxVDB/hZcXdg7zmPf9ysb3PYHb7NNjMnA+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

It's making creating and then working on a document on the same page extremely difficult. 

Additionally, you cannot create a document and pass it as a parameter to another page. 

### Additional info

![image](https://user-images.githubusercontent.com/66749069/227689339-1d6e4b68-417e-4f72-a241-5ace6c7b8835.png)

p.s. your app is amazing. I've used a bunch of no-code platforms and they all suck--this is the first one that actually works and it's exactly what I've been looking for!  Amazing UX, simple, intuitive. Huge props!! 

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by nickpicciri** [comment]
Looks like it's a problem with the fields containing a firebase server TS.

**Comment by mrflutterlover** [comment]
+1, same problem! launch-critical unfortunately...@nickpicciri - did you find any workaround?

**Comment by Milkyway12934** [comment]
I'm working with @mrflutterlover on this - would love to see this fixed - we've been trying to trying to fix this for quite some time now....

**Comment by aemelyanovff** [comment]
I can reproduce the issue.

@nickpicciri is right, the problem is with Firebase timestamp issues. As a workaround, I would remove DateTime fields for now.

**Comment by nickpicciri** [comment]
> +1, same problem! launch-critical unfortunately...@nickpicciri - did you find any workaround?

Just figured out a workaround in the meantime! First create a document and set any variables that don't contain TS. Then create another action in the action chain where you update the document and add any variables that contain a TS.
