### ISSUE TITLE
We need Algolia search radius as a variable.

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#664]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been unable to reach the FlutterFlow team and am posting my concerns here.
Limitation of Algolia Search: Inability to Set Variable Search Radius.

### Expected Behavior

We need algolia search radius as a variable.
It has been requested by the FlutterFlow community for over a year now to have Algolia search radius as a variable. This change is of utmost importance for a location searching app and implementing it could result in a swift improvement.

### Steps To Reproduce

1. select a listview or Gridview
2. create a query
3. select algolia search
4. set the latlng in the location box
5. look at the search radius box, there is no variable input.

### Bug Report Code

IT4olfLluJZ1ofVY7c/QdcBv9CQWJVg2RLgZkspBZzAaIrb1CLMqY8mnP0ltZ/Wid29YPlqcp14d/sHIkeDxLvY4aE6VGoQ+z6oNdT3wYEOtb8iTF7rtXndABelWf3615MOvsxR5OsZeWl4k1znzCOu9YHfUK737DWowSq/LZO4=

### Context

I'm doing a location search app. This is a core function of the app and without it the app could not run.

### Additional info

![image](https://user-images.githubusercontent.com/5303536/227734776-5903efae-b619-4696-b93a-3fcfbf269099.png)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: mobile
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by wenkaifan0720** [comment]
Hi @ibm777p2. I agree that is should be able to set as a variable. I'll talk to the team about implementing this feature. Thank you!

**Comment by wenkaifan0720** [comment]
This will be supported in our next update. 😁
