### ISSUE TITLE
Cant add value to a List<LatLng> Firebase record.

### ISSUE THREAD

**Issue by FrancoSernaglia** [FlutterFlow/flutterflow-issues#665]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to add a location value to a List of locations in a Firebase record but it gives an error on the debug terminal and the location is not added to the record.

"Error: Invalid argument (dartObject): Could not convert: Instance of 'LatLng'"

### Expected Behavior

I expect to be added the location to the list as a LatLng value but it doesnt.

### Steps To Reproduce

1. Create a Colletion with a List < LatLng > field
2. Create an Update Document action
3. Select the field to update and select the Add to set method
4. Choose the location to add
5. Execute

### Bug Report Code

IT4okvLlx85grs9G1s/AacFvryQQKVgkR78ricpOGDsdF4iuPOxzafSkbkhtTtTnYFVhKEWLjXwC+MHFjuDuUfJcFzSeftlewqhUFjnLXjm/aoSTOqqWP3JPGf5Qf0iH3MCNpBFCGLRYLE4N2Uyqf/CuY3XbHZf6Zwh9f6PHaOI=

### Context

I was trying to add a location to a list of locations using the actions blocks (Add to set method) but it gives an error. I tried uploading the location not to a list but to an individual LatLng field as to detect what the issue could be and it uploads it succesfully but I dont want that (I want it uploaded to a list). So, later, I created a custom action which gets the location to add and creates a list with it and then updates the field unifying the lists:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/128932349/227738822-b6b3e6cc-30c8-488f-b49b-16ab07648945.png">
Though, flutterflow should allow doing the same with the action blocks.

### Additional info
This how the buggy action block looks like
![image](https://user-images.githubusercontent.com/128932349/227738471-d64b7a6b-83ad-4799-85a7-5c0f63651a5c.png)

### Environment

```markdown
- FlutterFlow version:  v3.1
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 11
```

**Comment by shelpert** [comment]
Hi,

Thanks for reporting this bug! It has been fixed and will be released in a future update!
