### ISSUE TITLE
Reserved keyword "int" in Dart

### ISSUE THREAD

**Issue by jc6680** [FlutterFlow/flutterflow-issues#666]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you add "bool" or "double" as a field in the Firestore schema, you will get an a snack bar stating "this is a reserved keyword in Dart". However, if you use "int" and set it as an integer, then no notification. 

This results in a build error.

### Expected Behavior

Notify user that "int" is a reserved keyword to avoid any confusion from a user.

### Steps To Reproduce

1. Click Firestore button on left menu
2. Create collection
3. Add "int" as a fieldname

### Bug Report Code

IT4ClcmAuItIobhA0LXTbcJagioRJlw1RYIVjepHeEkdJ5PMC+wIZ/f7XFRuTde0T2NIeWeJvGUx/t3emvPtJvQrFzWCbqV8+M5cEgvwfH2nMbbUOruOZW5/AtNjIUDH56WRghMlIbBiSCxg6jiLe+vJfHbsNO/xDVQzIv6jA5OK2SrDX1iXc2URm05KZDPz

### Context

Build error when trying to compile.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 111.0.5563.65
- Operating system and version affected: desktop Win 10
```

**Comment by agreaves** [comment]
Hi @jc6680, thank you very much for the bug report! That's a great point, we will add `int` to the list of reserved words to address this.
