### ISSUE TITLE
Boolean nullable page local state variable that is default false treated as no default value set

### ISSUE THREAD

**Issue by tanczosm** [FlutterFlow/flutterflow-issues#667]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding a page level state variable that is a boolean (this may extend further to other state variables) you cannot uncheck nullable and set a default value of false without generating a Local State Config error.

![image](https://user-images.githubusercontent.com/2651588/227752485-d18ec531-2dd6-4e08-8a47-d3b4e2d7bbc4.png)

### Expected Behavior

The solution I would propose is when nullable is false, treat the Switch control as a true/false indicator for the default value.  It should be possible to have a default non-nullable value of false.  

### Steps To Reproduce

1. Create a new page
2. Create a boolean Local Page State variable
3. Set Nullable to off/false
4. Keep the initial value switch off
5. Try to run your project and watch the errors

### Bug Report Code

IT4whsmB05NPn7xa7arAdcFvnjgWGDs6R7871tUbcCs8GZT0B4kcYs+kfklUOe7iSlFIfE39nmIX/Mr6voaSE/Q5BAeVQb5qyId+UQLjcGCnR66rPL63b0Z6AeZQJlyl4KW72x14BOxtWk4k3162Fd6tFxTXH5z1OzMSQuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I want to be able to have non-nullable false default values.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 111.0.5563.65
- Operating system and version affected: Windows 10
```

**Comment by tanczosm** [comment]
This appears to impact any "optional" state variable value when nullable is turned off.  If I declare that a state variable is not nullable then the default value should not be optional anymore.

For string values an empty box should be perfectly valid (an empty string is a valid value for a non-nullable string variable), just like having the switch off for a boolean should be valid as being false.

**Comment by tanczosm** [comment]
Let me know if you need any further information regarding this.  Local state variables are relatively new but the inability to set a default that is either false or an empty string on nullable variable types is definitely a bug.

**Comment by agreaves** [comment]
Hi @tanczosm, thank you for the bug report and the information! This is actually just a failure on our part to show when a default value is unset vs false or empty. You'll notice that currently you can toggle the Switch on and then off and this will resolve the issue. Similarly you can enter text and then delete it to make the default the empty string.

The issue is it looks identical when it is unset vs false or empty. So updated the UI to better reflect that! This should be present in the next release 🙂. Thanks again!
