### ISSUE TITLE
Refresh Page on Browser Redirect to Page 404 - Using Firebase Hosting

### ISSUE THREAD

**Issue by polenvinagre** [FlutterFlow/flutterflow-issues#671]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I recently updated my current project. I am using Firebase Hosting for the Web version.
I am also doing some tests using FlutterFlow Web Publishing (flutterflow.app).

I use android studio to publish the Web version of my project.

Using Chrome if I click on menu bar Refresh button using the domain in FlutterFlow (flutterflow.app) everything works ok on EVERY page.

Using Chrome if I click on menu bar Refresh button using the domain in Firebase Hosting ONLY on HomePage everything works ok.

Using Chrome if I click on menu bar Refresh button using the domain in Firebase Hosting the browser redirects to Page 404. On pages different from HomePage.
project0001.web.app
project0001.firebaseapp.com
app.project0001.com.br

Before the latest updates everything works properly.

### Expected Behavior

Refresh any project page by clicking on Browser Chrome Refresh button

### Steps To Reproduce

1- Create any project with a HomePage and a secondary page.
2- Configure it to deploy on Firebase Hosting.
3- Configure your own domain.
4- Download code and publish the project using Android Studio.
5- Go to your Web version project. Navigate to the secondary page.
6. Click on browser Chrome Refresh page button
7. You will be redirect to Page 404

### Bug Report Code

do not apply 

### Context

My project is already in production and all users when try to refresh any page, diferent from home, receive the error: Page 404
Same erro on Opera browser.

### Additional info

![erro_404](https://user-images.githubusercontent.com/50787371/227799372-126688a4-8d0d-4efc-a5ea-f325a225374d.png)

### Environment

```markdown
- FlutterFlow version: v3.1 (released Mar 22, 2023)
- Platform: Web
- Browser name and version: Chrome Versão 111.0.5563.111 (Compilação oficial) (64 bits)
- My PC: Windows 10 64bits
- Operating system and version affected: Web version
```

**Comment by hariprasadms** [comment]
Hi @polenvinagre  - As we are not supporting firebase hosting, we are not able to investigate the issue. If you can deploy the same project in FF web hosting, what is the behaviour on refresh?

**Comment by polenvinagre** [comment]
Hi @hariprasadms!
The Web Publish version with FlutterFlow domain is OK.
The issue is related to Firebase Hosting.

I understand that, today, FlutterFlow does not support Firebase Hosting.

But I would like to list some items to think about it:
1- In the past when FlutterFlow did not offer the option for web Publish, Firebase Hosting was the better option available. Therefore, I think many developers used Firebase Hosting.
2- In the first moment when FlutterFlow began the Web Publish service there was not any conflict with Firebase Hosting.
3- It seems only with the update to GO ROUTER, the issue was initiated.
4- Today ALL developers who have a project already running in Firebase Hosting are facing this issue with Refresh Page 404.
5- So, to solve the issue, the only option is to migrate to FlutterFlow web Publish service.

**Comment by agreaves** [comment]
Closing this as a stale issue.
