### ISSUE TITLE
Text Align for Dropdown widgeth 

### ISSUE THREAD

**Issue by squidsareevil** [FlutterFlow/flutterflow-issues#676]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The text align setting for the dropdown wdiget is not working. I can toggle it between left align, center align, and right align. However, the text still remains left aligned. 

### Expected Behavior

dropdown text should be aligned based on which setting I select

### Steps To Reproduce

1. create dropdown widget
2. Fill widget with options
3. toggle text align
4. run and see text is not aligned

### Bug Report Code

ITEezsj104lPn7wG0KncavloqwMwJFg2a+Y/p+0aRQ0hfeP0B7AUZM/4VEhLYtfheFZmAFWGjmUd/9LHuODLKvU7HE6sGdVAzq5XQQrgfHyheLq7EZaofmhBM/lWIXam1p6Z2h1dIu9uSkI42U2QB/CdG3qCf9qOYwx5e6fDbOY=

### Context

I am trying to align text to the center

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @squidsareevil, thanks for the bug report! We should not have been showing the Text Align option in this case as it does not actually do anything within the Dropdown. So unfortunately this will not work, although we will be removing it to avoid any future confusion. Thanks again for the report!
