### ISSUE TITLE
Permissions toggles are disabled on new blank project.

### ISSUE THREAD

**Issue by hancheester** [FlutterFlow/flutterflow-issues#679]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On a new blank project, permissions toggles are not working as I cannot enable some of them.

![image](https://user-images.githubusercontent.com/291537/228182865-396255e5-9d8a-4d75-b335-b09bb26789b2.png)

### Expected Behavior

On a new blank project, I should be able to toggle to enable permissions.

### Steps To Reproduce

1. Create new blank project.
2. Go to Settings and Integrations
3. Go to Permissions under Project Setup section on the side menu.
4. Click any of the permission toggles.

### Bug Report Code

ITFThfLlvJR1m7QE+Kr1Y8B4mmE7I0MfWOdEket+EA0hfartE5kLP8/4QElLYteAd25be1H/rHo1092KhvH1UsIrOgWeGIBj+YRXQT3MUnulV7qQO7uBP3cnRNhYCEiD07Szux57IrFZWC0M2WCMBPCNG3qCf9qOYwx5e6fDbOY=

### Context

When I want to test something on my app, I normally will create a new blank project and run some code to see if it works or not. It is more efficient than trying to run on a app which already has a lot of moving parts and also try not to "pollute" the codebase with testing code.

As for testing permissions, I will have no choice but to create a new project using existing templates in FF. However, it is a bit of waste as I don't really need those pre-built pages and settings in the template.

### Environment

```markdown
- FlutterFlow version: v3.1 (released Mar 23,2023)
- Platform: Web
- Browser name and version: Chrome 111.0.5563.147
- Operating system and version affected: Windows 11 10.0.22621.1413
```

**Comment by katherineqian** [comment]
Hi @hancheester, I've reproduced this bug, thanks for reporting.

**Comment by github-serhat** [comment]
Hi all , same issue ...

**Comment by github-serhat** [comment]
@katherineqian Now this page is working, but a real device still does not ask for permission.

**Comment by avantedev** [comment]
I cant select anything too! Same error!

**Comment by agreaves** [comment]
Hi @hancheester and @avantedev, thanks for the information. We've identified the issue and it should be fixed in the next release!

**Comment by avantedev** [comment]
@agreaves When is the next release?

**Comment by avantedev** [comment]
That is fix the problem with input files inside webview component? I cant select files in input field inside my URL trouth webview component.
