### ISSUE TITLE
Width set from variable is gone.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#68]
What happened to width?

I check my other projects and they have it. But the new project I created has no `width set from variable`. Please check.

PS: I found, it is only existing in Components. Not in page screen.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5080329/198884521-08a0764c-e577-4eff-a130-b2de4b6646f8.png">

**Comment by thruthesky** [comment]
I found it is existing on a component. Not in a page screen.

**Comment by bulgariamitko** [comment]
I think this is the normal behavior of FF.
