### ISSUE TITLE
API call returns List<integer> but console throws an error it's a List<dynamic>

### ISSUE THREAD

**Issue by sohaibilyas** [FlutterFlow/flutterflow-issues#683]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

API call returns List<integer>, while creating the JSON path it mentions that it's a List of integers but when I try to save using update app state action it throws this error: Uncaught (in promise) Error: Expected a value of type List\<int>, but got one of type List\<dynamic>

### Expected Behavior

Return type is correct, it should complete the update app  state action.

### Steps To Reproduce

1. Create API endpoint which return a list of integers
2. Create JSON path of List\<integer>
3. Create App State with type List\<integer>
4. Create Login button or Register and use action "Update App State" and save the JSON path to App State variable
5. Run the Test Mode
6. Hit Login or Register button and check browser console for error

### Bug Report Code

IT4sj8iA8ZdOpbxI0KruY8dB/SQsC0whRJIKscsZa0kdB4joPLJ+deDsUFptQu24T0NhHFCIgmMCpuj7i/zpLMJdITaufaF8ws1ASzyXe3q8RqarCKuaQnMnRONmfm6X0qugkyVAKsVtW14Q12WQNu6AThHXGZ+/Zwh9f6PHaOI=

### Context

I tried using List\<String> instead of integer list it worked but then I'm unable to check it against another value using Condition Visibility.

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web, Mobile
- Browser name and version: Brave v1.49.132
- Operating system and version affected: Windows 11

**Comment by sohaibilyas** [comment]
Hi @hariprasadms, I don't write flutter but I think yes because it's updating the app state.

```Did try to changing the app state from List type to List type and also try to use 'add to list' instead set option in the app state update.```

I did not understand this, which List type to try? 

I'll try "add to list" option instead of set state.

**Comment by sohaibilyas** [comment]
@hariprasadms "Add to List" is only for saving one value to List but I'm saving an array not just one value.

**Comment by hariprasadms** [comment]
> Hi @hariprasadms, I don't write flutter but I think yes because it's updating the app state.
> 
> `Did try to changing the app state from List type to List type and also try to use 'add to list' instead set option in the app state update.`
> 
> I did not understand this, which List type to try?
> 
> I'll try "add to list" option instead of set state.

Sorry, I missed the list types. I meant try List<Json> instead of List<Int>. Give a try and let me know please.

**Comment by sohaibilyas** [comment]
I think you missed the types again, I tried List of JSON type, login works now but "remove from list" action is not working as 
expected, app state it persisted. Here's the screen recording https://streamable.com/1g1zlc

**Comment by hariprasadms** [comment]
Hi @sohaibilyas - Thanks for confirming. Good to see that List json (dynamic) type solved the problem. When you updating the app state using 'set' option, you can't remove the data using 'remove from list' option as data is not inside the list. To remove the data, eventually you should add the data into the list and later you can perform remove.  

You can close the issue as it's been resolved now. If you got any other issues, you can create new one. Thanks

**Comment by hariprasadms** [comment]
Hi @sohaibilyas - As per my earlier comment I see List json (dynamic) type solved the problem. Hence I am closing this issue. Let me know if the issue still persists we can re-open the issue and investigate. Thanks
