### ISSUE TITLE
Null No longer working 

### ISSUE THREAD

**Issue by nparkins07** [FlutterFlow/flutterflow-issues#687]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a simple Custom function which essentially checks whether or not a variable is Zero, Empty or Null and if it is to give me TRUE if not FALSE. 

This was working just fine the other day, but now it only seems to work when a "0" is entered. When I leave it empty or try typing in "null" it still reports FALSE - which is throwing a huge wrench into my front end logic.

<img width="1161" alt="Screenshot 2023-03-29 at 10 12 37 PM" src="https://user-images.githubusercontent.com/101225648/228719001-9195295f-c778-4506-9d5b-892758eb5aba.png">

<img width="1162" alt="Screenshot 2023-03-29 at 10 13 17 PM" src="https://user-images.githubusercontent.com/101225648/228719093-463c1d3b-aed2-4060-96aa-298dea652d96.png">

### Expected Behavior

If the variable is zero, empty or null it should give me TRUE as the return value. 

### Steps To Reproduce

1.) Create custom code with the following: 

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

bool zeroEmptyNull(String? check) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // boolean for if 0 or null or empty
  if (check == null) {
    return true;
  } else if (check.isEmpty) {
    return true;
  } else if (check == '0') {
    return true;
  } else {
    return false;
  }
}

2.) Test the function in the custom code section. Try 0, "null" & leaving it blank. 

### Bug Report Code

custom code

### Context

It's preventing me from submitting my app to Apple as this is an item they flagged. They can't see a few of the front end items that should be populating since they are "null". 

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.3 - March 23, 2023
- Platform: MacOS Desktop
- Browser name and version: Chrome testing 
- Operating system and version affected: macOS Ventura 13.1
```

**Comment by nparkins07** [comment]
@elphinehas @shelpert - It looks like "null" is not the only item not working. Mystery continues as "0" and "empty" are both now reporting back as TRUE. However, "null" is still showing false.

<img width="1158" alt="Screenshot 2023-03-30 at 4 38 47 PM" src="https://user-images.githubusercontent.com/101225648/228970894-db09860a-b92d-4af9-b87b-6e033959383b.png">

**Comment by hariprasadms** [comment]
Hi @nparkins07 - I hope above points helped you to achieve what you are looking for. We are closing the issue.
