### ISSUE TITLE
Upload Local File defaults to true when nothing has been uploaded 

### ISSUE THREAD

**Issue by nparkins07** [FlutterFlow/flutterflow-issues#688]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When logging in, I go to upload a document to the file uploader, but it's already indicating that something has been uploaded. 

See attached, the "true" is indicating whether or not the Uploaded Local File is Set or not, and it's indicating True.

"null" is showing up from the Media Height, which makes sense as technically nothing was uploaded. 
 
![Screenshot 2023-03-30 at 12 01 02 AM](https://user-images.githubusercontent.com/101225648/228734182-0e9242c6-8192-4b20-ad0a-c931ef7fb25d.png)

### Expected Behavior

When logging in and trying to upload a document, I should see an icon and message to "upload a file". Once I upload a file I would then expect it to update the image to a "success" image and the text to "success text". 

### Steps To Reproduce

See attached image and Loom.

https://www.loom.com/share/a6ee3d51f6cd41bda9d829be785413c0

<img width="537" alt="Screenshot 2023-03-30 at 12 03 58 AM" src="https://user-images.githubusercontent.com/101225648/228734585-5144bbde-4b79-4209-aaf3-50897258253f.png">

### Bug Report Code

ITFfi87huJZ1ofUA1oSJLMdogiYsKVscTYMvjuphcx4bfa7kB4YfO8mlU0NKTOGVe21UJFSgij0E7sr8v/GWUcAqBzitfrpc0JVAWA6WZEy6eLa6DauwOnFSDZ5Pfmq45om3hRVCJvRaW1ID3TqDNq3qNleeY8aSfxBlZ7vfcPo=

### Context

It's confusing for the user as it looks like something has already been uploaded. 

### Environment

```markdown
- FlutterFlow version: v3.1 Flutter 3.7.3
- Platform: MacOS Desktop
- Browser name and version: Chrome
- Operating system and version affected: macOS Ventura 13.1
```

**Comment by victoriahuang1** [comment]
Hi @nparkins07 , thanks for the report. This issue should be fixed with the next deploy!

**Comment by victoriahuang1** [comment]
Hi @nparkins07, I can confirm that the fix has been made. Our deploys do not happen right as fixes are pushed though -- but the deploy should happen within the next week.

**Comment by victoriahuang1** [comment]
Probably some time after Thursday
