### ISSUE TITLE
Refused to set unsafe header "User-Agent" error when using Algolia Search widget 

### ISSUE THREAD

**Issue by jamesnevada** [FlutterFlow/flutterflow-issues#689]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running an Algolia search action (both On Change and On Submit) no results are returned and the console notes the error: Refused to set unsafe header "User-Agent" (once for On Submit, multiple errors for On Change - every keystroke)

I've attached screenshots below:

<img width="897" alt="Screenshot 2023-03-28 at 1 58 44 PM" src="https://user-images.githubusercontent.com/12664802/228776062-581fd8f5-2f2b-42ae-a764-f8edb11989bf.png">

<img width="540" alt="Screenshot 2023-03-29 at 4 40 55 PM" src="https://user-images.githubusercontent.com/12664802/228776091-5859d650-9c97-449f-917b-4dd0156f131e.png">

### Expected Behavior

The Algolia search should show results from the index I created based on the search term I type in.

Algolia is fully set up and the Firebase extension is running correctly via changes made to documents. I've used the Search API key in Flutterflow.

### Steps To Reproduce

1. Create page

2. Add text input field

3. Add a list view or grid view

4. Add a Card widget to the grid view with a text field

5. Create a Local State variable (String) - I called it searchTerm

6. Create an action chain on the text input field. (you can try both as On Submit and On Change -but search on Algolia via Text Input field not searchTerm when doing On Change)
• Update Local State action for text submitted via Text Input Field
• Algolia Search  > scenes [Index] > searchTerm (or Text Input Field widget value if On Change)

7. On the Grid View, create children from the Algolia search results

8. Use a variable from the children for the text field in the Card widget

9. Run and see if any results populate

### Bug Report Code

IT4SjOflzItPj7xK7c/ubPlR/TssKVgnULg7mNV6EUojIojrP5lyXOjDYlttXdeFT2xYelv8sGMy+c3IueOXGOQHAw2aY65PwpZqWA3wIWeWM762Dc6KfmhSGcVMNEuV07Wo3B5/CNdfLlocw2D3HvDKfBLUNufSDGwWQsmjKoPPjVLhAi+6Xn0Jg1ZSfCvr

### Context

Trying to populate search results from Algolia index instead of pulling in all documents from Firebase -  I need to be able to access all the documents but it is expensive and slow pulling all the documents in and then filtering. Right now Algolia seems like the most effective option for that.

### Additional info

I can provide more details if needed.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web 
- Browser name and version: Chrome 111.0.5563.146
- Operating system and version affected: macOS Ventura 13.3 Beta
```

**Comment by agreaves** [comment]
Hi @jamesnevada, thanks for the bug report! As it turns out, the user agent message is actually more of a warning, and does not actually impact the search results. If you're not seeing any results, it's likely due to the configuration somewhere on the page, as after having tested it the Algolia query does indeed return results. You can test this in Run mode by doing a very basic query (with some test search query), setting the number of returned items to a Page State field, and adding a Text that shows the current Page State field value.

Closing this for now but please let me know if you encounter any other issues!

**Comment by PieterHartog** [comment]
I am experiencing the same issue. The Algolia logs look good; status 200 and it returns data in the response body. But my listView widget keeps spinning with the loading widget and data never shows.
Seeing the same error message in the user agent (chrome).

**Comment by richard-ruah** [comment]
I'm also facing the same issue. Has anyone got a solution?
