### ISSUE TITLE
Unable to add custom Domain on Second Project.

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#69]
When you have two flutter flow projects, 
on the second project You are unable to set a custom domain and it shows you to go premium even though I have a premium account?

![image](https://user-images.githubusercontent.com/67612575/198892744-6d930b3e-4802-4245-ab7a-83c7bef1f982.png)

**Comment by Josefpa** [comment]
"To start you can publish one custom domain per Pro or Teams account, additional options coming soon!"

**Comment by bulgariamitko** [comment]
This is also hard to reproduce so I will expect FF team to have a look. @katherineqian
