### ISSUE TITLE
Content of a scrollable column is not scrollable

### ISSUE THREAD

**Issue by metaflowdev** [FlutterFlow/flutterflow-issues#690]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a scrollable column inside of a tab bar content. The column was set to scrollable without issue (after some restructuring of the page) 2-3 weeks ago and at first it worked. The content scrolled if it was overflowing the available height. However then it stopped working although nothing had changed on the page and the column is still set to be scrollable without errors. This behavior is present both in FlutterFlow in Run mode and Test mode as well as on iOS and Android device builts.
<img width="399" alt="Screenshot 2023-03-30 at 1 47 43 PM" src="https://user-images.githubusercontent.com/129390725/228828765-61648790-aa27-4993-962c-b2179f8f8fac.png">
<img width="409" alt="Screenshot 2023-03-30 at 1 46 51 PM" src="https://user-images.githubusercontent.com/129390725/228828784-964fb404-2fba-4f9a-b13c-6afaa84bcd9f.png">
<img width="1740" alt="Screenshot 2023-03-30 at 1 40 05 PM" src="https://user-images.githubusercontent.com/129390725/228828855-9104d620-d555-4620-b187-8289ee2ed40e.png">

### Expected Behavior

The column content should be scrollable. 

### Steps To Reproduce

As you can see in the screenshot above this is a quite complex page that has grown over time. I can not spend much more time reproducing and testing because my client is on a budget. Here is a rough description of what happened.

1. Create a new page and add tab bars in it.
2. Add content inside the tab bars until the heigh is overflowing on some smaller devices.
3. Wrap the overflowing content in a column and set it to scrollable.
4. The column should be scrollable on smaller devices but is not.

### Bug Report Code

IT4ki/Hq25dgoddD1s7bbcBvlSc4C0d8TLJEpu0bWUkbGO/4BO0ideDRVFBvTsizaHNMHk6jsGI10db6hoTpM/JdZAyaG704+rpcahPPbECmVqrRCqmwPXB5HeRUGX655Le3rwp7BO9hWnw+316YGOitYz6Cf9qOYwx5e6fDbOY=

### Context

The page should be scrollable so additional page content can overflow the available height on smaller devices. I am trying to finish this project and release the app for the client but this bug is blocking it.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iOS and Android
- Browser name and version: Chrome Version 111.0.5563.110 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.2.1 (22D68)
```

**Comment by agreaves** [comment]
Hi @ metaflowdev, thanks for the bug report. This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/).

In your particular case, it's because of the configuration of your page. The column you have made scrollable is not the one experiencing an overflow, instead it is the outermost Column (which is not scrollable). If you have further questions, do please reach out to support!

**Comment by metaflowdev** [comment]
@agreaves Hello, it was not my idea to open this issue. I was sent here from FlutterFlow support because they could reproduce the issue and told me I had definitely found a bug.

<img width="344" alt="Screenshot 2023-05-07 at 4 13 05 PM" src="https://user-images.githubusercontent.com/129390725/236682988-ae065aa0-ce8b-44f3-aba0-5bfb5893da3c.png">

Which column do you mean that has the overflow?

And if this is the case as you describe it, how come then that I don't see the overflow when I show the list view and it only appears when I have the graphic as content. This is very inconsistent and anything I try to do to fix it gives me an error. As you can see above, apparently not even support can figure it out.

<img width="379" alt="Screenshot 2023-05-07 at 4 18 28 PM" src="https://user-images.githubusercontent.com/129390725/236683417-7d1266e8-6d47-4ed3-9514-7db415e65406.png">
<img width="374" alt="Screenshot 2023-05-07 at 4 18 35 PM" src="https://user-images.githubusercontent.com/129390725/236683419-7540b4a0-fb67-4d7b-9b33-63c66295ceff.png">
