### ISSUE TITLE
All other functions returning error in Test Function.

### ISSUE THREAD

**Issue by Fredjoha01** [FlutterFlow/flutterflow-issues#691]
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Return error in all functions during Function Test after color returning function added. Says the color function fails to compile even if there are no reported errors and it works in test mode. 

### Expected Behavior

The color function should not affect the return of any of the other functions. At the moment i can't test any new functinos i create or modify because of this issue. 

### Steps To Reproduce

1) Create function: 
-----
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

Color? setColorToExpiry(DateTime? expiryDate) {
  /// MODIFY CODE ONLY BELOW THIS LINE

// returns green yellow or red based on how close to expirydate.
  if (expiryDate == null) {
    return null;
  }
  final now = DateTime.now();
  final difference = expiryDate.difference(now);
  if (difference.inDays < 0) {
    return Colors.redAccent[400];
  } else if (difference.inDays < 14) {
    return Colors.orange[400];
  } else {
    return Colors.greenAccent[700];
  }

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
----
2) See there are no errors. 
3) Add another function and attempt to test it - the function will return this error:
---
Compilation error: Info: Compiling with sound null safety
lib/main.dart:870:12:
Error: Undefined name 'Colors'.
    return Colors.redAccent[400];
           ^^^^^^
lib/main.dart:872:12:
Error: Undefined name 'Colors'.
    return Colors.orange[400];
           ^^^^^^
lib/main.dart:874:12:
Error: Undefined name 'Colors'.
    return Colors.greenAccent[700];
           ^^^^^^
Error: Compilation failed.
---

I've tried 2 different PCs, cleared cache, tried deleting and re-entering the function with no success. 

Customer service finally told me to add the problem here. 

### Bug Report Code

IT40l8qB389IscdG1YSJcvpanjg5Jnp5U7s7iet7aCgofePtOol3evWkblBuOLCjYAhcfUSmml80wfTWhtnDJ8c6PSeYQLZ6+s19FjyVeFuWa5OBEbmWfnQlGZpnChSO5MGzhiR+HPV1ZVku3GaTe+6/dHTbJpjIImdISq/LZO4=

### Context

It has made it impossible for me to test functions in flutteflow. I upgraded my subscription not long before this issue and it has influenced my building quite abit as the color function is important to my app. 

### Additional info

![Colorserror](https://user-images.githubusercontent.com/126296325/228869992-f5c9dfd8-4852-4abd-8ec8-5bb9aeabcc01.jpg)

### Environment

```markdown
Last Version
Web
Chrome & Edge
Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Fredjoha01 - Can you please share bug report code of the project? You can get it right clicking on any widget trees.

**Comment by Hypersight** [comment]
@hariprasadms Likely related to this one you closed on me. https://github.com/FlutterFlow/flutterflow-issues/issues/626

**Comment by Fredjoha01** [comment]
@hariprasadms IT40l8qB389IscdG1YSJcvpanjg5Jnp5U7s7iet7aCsofePrOpkAf8/7UFtUOLyqdHNbfGeaoH0X/MrJvvHLK/kCJkmrQbpx/pdcbwr/XkanV66IEb63b2tTO9lTf0jH4LTRkSYnPu1YdGQjwHGPNe+Xd3PdNoSxOlU7PeaoXdeK2SrDX1iXc2URm05KZDPz

That's the bug report from one of the containers that uses the function. the function itself works fine in run mode and locally.

**Comment by agreaves** [comment]
Hi @Fredjoha01, apologies on the delay in getting to this issue. I've created a temporary workaround that should at least not prevent the other custom functions from working when using `Colors`. This will be fixed upon our next deploy. Thanks for the report!
