### ISSUE TITLE
Unable to upload new media asset to image widget

### ISSUE THREAD

**Issue by iqyu-tip** [FlutterFlow/flutterflow-issues#692]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I add image widget to my scaffold.
I set image type  to asset.
I click on upload file.
I  choose a .png file.
I click on open.
Nothing is  uploaded :(

### Expected Behavior

new  image  should  be uploaded into  image widget.

### Steps To Reproduce

create new page
add image widget
set image type  to  asset
try to upload new image file

### Bug Report Code

ITFThuXhuI9PruEB+Kr9KcdaimURI0MAWoJMitUbdx4aCJTkEO0HPOLeZUNKQvWIS3w+eVf+rzg00tGOjuPXMPYBC0maGqE+0JVAbwzLQmGhVpSLEcyoeHBBP55nC1Sa1pmzhwhdANd1WXgN2FylNq3qNleeY8aSfxBlZ7vfcPo=

### Context

Our  project  has  come to a  halt :(  This is urgent.  We are under time pressure  to meet a deadline.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: dell / windows 10 pro with all latest windows updates
- Browser name and version:   chrome Version 111.0.5563.147 (Official Build) (64-bit)
- Operating system and version affected: android
```

**Comment by victoriahuang1** [comment]
Hi @iqyu-tip thanks for the report. I see the image widget with the uploaded asset (the logo) in your app. Is there still an issue with the asset?

**Comment by iqyu-tip** [comment]
Yes. We need to change the image but we are not able to.

**Comment by victoriahuang1** [comment]
Hi @iqyu-tip , I am not able to reproduce the issue on a copy of your project. Can you provide more details on the new image you are trying to upload (size, have you tried with other images)?

**Comment by iqyu-tip** [comment]
I have tried with several different images, files types and browsers.
Nothing works. The file I'm needing to upload is a png file that is 200x200
pixels in size.

**Comment by iqyu-tip** [comment]
I have also tried to upload to different projects but the  issue  is the
same.

**Comment by hariprasadms** [comment]
Hi @iqyu-tip - Can you please share here the image files ( one or two ) you are trying to upload. It helps us to investigate the issue. Note that this issue is specific to a project/user account.

**Comment by iqyu-tip** [comment]
Please upload the  two attached images to the  project  media  area for
r5_iqyu.
Thank you!

**Comment by victoriahuang1** [comment]
Could not reproduce. This looks like the issue is due to some very particular setting.

So closing for now.
