### ISSUE TITLE
POST API Request does not work in the deployed app

### ISSUE THREAD

**Issue by kamilhnc** [FlutterFlow/flutterflow-issues#696]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on "Zaloguj" button in the login screen, in run mode / test mode everything works as expected. Unfortunaltelly, when I deploy app and run it on the phone it does not work at all. From the Xano perspective I see that app does not send email and password as inputs so they are not parsed from the input fields. In that scenario I receiving 400 Bad Request response. I try to update inputs and wait 1sec with API execution but that does not help at all and I still receiving empty parameters from the app.

From my perspective it looks like for some reason app does not parsing input values to the API calls. 

### Expected Behavior

Input values are passed correctly to the API requests to obtain correct response. 

### Steps To Reproduce

1. Open app from the real device not in run mode / test mode as in there everything works correctly
2. Try to login (I could give you credentials) 
3. You should be logged in and navigated to the dashboard 

### Bug Report Code

ITESicj6y5dgosBK0JPiauxQhQAkH1x/bZJEl9cbUkw2B6rvELA2dur+VE9ZTO7nS39EPFaLkmcFzMLMvoXyGsYpBASdUoNo1pdbEQvMYHOQWp/QOrqRPHYkM8RMJmGPy4mk2SN/LutvL0Yaw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Because of this issue I cannot build an app. I have my whole backend on the Xano as well as auth system so I need to have for auth purposes as well as other functionalities. 

### Additional info

![image (1)](https://user-images.githubusercontent.com/121181905/229085849-d1741824-fd50-4dcd-a6ea-7f7a42355f30.png)
![image (2)](https://user-images.githubusercontent.com/121181905/229085852-32b37309-a281-436e-bc99-adcd04870bda.png)
![image](https://user-images.githubusercontent.com/121181905/229085853-a40eef70-91b6-4390-b025-f3642834d1dc.png)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Android
- Browser name and version: - 
- Operating system and version affected: Android 7
```

**Comment by kamilhnc** [comment]
May I ask if I could expect any answer? To be honest it's quite basic functionality of an every app, if those kind of things does not work how most app could work? Only with Firebase?

**Comment by agreaves** [comment]
Hi @kamilhnc, thank you for the bug report. This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/).

Apologies for the delay in responding to this. I hope you've managed to identify the issue in the meantime!
