### ISSUE TITLE
Refresh Database Request Action does not work when Algolia search is set in backend query.

### ISSUE THREAD

**Issue by moraemoncom** [FlutterFlow/flutterflow-issues#697]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Refresh Database Request Action does not work when Algolia search is set in backend query.

https://user-images.githubusercontent.com/127755388/229115325-a86cad06-ddfd-45e6-aa23-4454f12151cc.mov

<img width="1280" alt="21" src="https://user-images.githubusercontent.com/127755388/229115369-3a05c668-60e7-4308-a4ad-b605150c5135.png">
<img width="1280" alt="22" src="https://user-images.githubusercontent.com/127755388/229115389-04d2a9bf-61a0-49b8-917b-304107659313.png">
<img width="1280" alt="23" src="https://user-images.githubusercontent.com/127755388/229115404-f6b466dc-60b8-4742-9e17-500ec3f4afe4.png">

### Expected Behavior

Refresh Database Request Action work when Algolia search is set in backend query.

### Steps To Reproduce

1.Set Algolia search to query list backend.
2.Sets the refresh database request action.
3.Action doesn't work when item is added to list.

### Bug Report Code

ITEel8j6yMxhpbxe+bXbLO14pwMwQWYla+dIoetxc0gbfe/4O7QcP8zRflJWYMCzaH1mBlmJvEU1wa3Jht/xKMIVCw+uQI9xyM1AexPPbGqmV4igPLuKfnxCP+lXBXWB37SrrBFRKsB2L3g832CIC+mtaz6Cf9qOYwx5e6fDbOY=

### Context

It goes without saying that it is a basic operation.

### Additional info

FlutterFlow doesn't seem to want to touch this subject.
Is there something wrong?

### Environment

```markdown
- FlutterFlow version: v3.1-3.7.3
- Platform:mobile
- Browser name and version:111.0.5563.110（Official Build） （x86_64）
- Operating system and version affected: macOS 12.2.1
```

**Comment by Prototype36** [comment]
This has become an issue within the last update from FlutterFlow team. It seems when requesting an action from Flutterflow to conduct a search on Algolia for the second time, the value never clears from the previous search. My action checks if a file has been created, and if not, to create a file. Previously, it would return a value of 1 if the file exist. Now, even if the file exists, it keeps returning a value of zero till I refresh the app. It keeps creating duplicates on the firestore.

**Comment by wenkaifan0720** [comment]
Hi. We were caching Algolia search with same query parameters before (which is good for static collections and saves cost). In the next update, you will be able to turn this caching off.
