### ISSUE TITLE
Initial Page for PageView set as a variable not working

### ISSUE THREAD

**Issue by KlausGrosser** [FlutterFlow/flutterflow-issues#698]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using a PageView that has conditional visibility, so the user can toggle to see it or hide it. In order to reappear the PageView at the same exact page that the user previously left, I assigned the Initial Page Index to the value of a PageVariable called measurementsIndex that stores the index of the last page seen by the user.
The measurement index gets the current index through an update action when the pageView is toggled to be hidden, using the widget state variable "Page View Current Index".
The problem is that no matter what variable I assign to the Initial Page Index, it will always return the first page (0). If I use a specific value (i.e. 5) it works, but of course, the page view will always be initialized on page 4.
I even added a text field to display the value stored for measurementsIndex page state variable, and it displays the value properly, so I know that that variable is not returning null or 0.

### Expected Behavior

The PageView should be initialized in the page containing the index set by a variable, and not just a specific value.

### Steps To Reproduce

1. Add a PageView widget
2. Create a page state variable to store the current PageView page index
3. create a page state variable to store a boolean to track if the PageView is hidden or not.
4. Make a button that updates the previous variable to display or hide the PageView
5. Set the Initial Page Index as the value of the variable of step 2.
6. Run the app

### Bug Report Code

ITFXkvHlvIZNrsRE7arbKPlKhSgwGUweUIIZjtlETRQdfuPqELQLd8n4ak1BcuqHTH4/OVGb+UEF7trKhob1Cu4BHzWtf754+qlbUxDhdz+Xb82mPoeOWnJ5I/9NCEiw3J2jnBRBAO9pdU4a2ziqPN+uY3qCf9qOYwx5e6fDbOY=

### Context

This strongly affects the user experience and must be fixed.

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 111.0.5563.146 (Official Build) (x86_64)
Operating system and version (desktop): macOS Ventura 13.3
```

**Comment by Pepino-GR** [comment]
Hi @KlausGrosser,

I cannot reproduce the issue. Did you set the stage variables to persisted?

**Comment by victoriahuang1** [comment]
Hi @KlausGrosser , thanks for the report. The "Initial Page" property is only for setting the _initial_ value. To change the value afterwards, you should use the "Control Page View" action. The ability to use this to jump to any arbitrary page will come out with the next deploy!
