### ISSUE TITLE
When using a Custom Function for the first time with a Bool parameter get "Current variable is not valid"

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#7]
## Expected behavior
When using a Custom Function to assign a Text Widget for example you press Confirm you should not get any errors.

## Current behavior
When using a Custom Function to assign a Text Widget for example and there are parameters which are bool and are False by default if you try to press Confirm you are getting "Current variable is not valid". In order to fix this error you need to make all bools values True and then False again and then click Confirm and it will work. 

## To Reproduce
1. Create a Custom Function with at least 1 parameter that is a bool and the default value is False and it is returning a simple text string for example - "Hello World"
2. Create Text Widget and press on Set From Variable
3. Click on the Custom Function you just created 
4. Without clicking anything else just click Confirm (leaving the default bool value false)

## Context
This error is misleading as there is not an error.

## Your environment

* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): Web 
* Browser name and version: Chrome 105
* Operating system and version (desktop or mobile): desktop

**Comment by hariprasadms** [comment]
Hi, I can reproduce it. I can see it show error message first time as explained above. Adding a screenshot.

![image](https://user-images.githubusercontent.com/17435678/191464747-c8f46b28-45d3-4a19-af3b-ed04ecfb5106.png)

**Comment by agreaves** [comment]
Fixed next deploy!
