### ISSUE TITLE
When touching an icon, it doesn't reproduce the trigger animation

### ISSUE THREAD

**Issue by Franco-Cruz-Schoolfy365** [FlutterFlow/flutterflow-issues#70]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Reproduce the trigger animation when I touch anywhere on the row

## Current behavior (required)

Reproduce the trigger animation ONLY when I touch the text and doesn't work when I touch on the icon

## To Reproduce (required)

1. Create an icon and a text
2. Set the icon with a trigger animation
3. The previous widgets put in a row
5. Create an action for the row to trigger the animation
6. When touch the icon doesn't trigger the animation

**Keep in mind that works with touch the text**

## Context (required)

The idea is create an animation when the user touch an icon

## Screenshots / recordings

https://schoolfy365.tinytake.com/msc/NzUxMTEzMF8yMDQ0NTYxMA
## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: v3.0 - 28 October
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Brave - Version 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - OS Build: 22621.674 - Version: 22H2

**Comment by Pepino-GR** [comment]
I can reproduce the scenario. The Click on the ToggleIcon itself does not trigger the 'On Action Trigger'. It can only be triggered from another widget. You also cannot set an action to the ToogleIcon.  This is by design and not a bug.

**Comment by Franco-Cruz-Schoolfy365** [comment]
Thanks for clarifying, can this feature be added in the future?

**Comment by Pepino-GR** [comment]
I will set it as a Feature Request.
