### ISSUE TITLE
Choice Chip Set FormField Action is Broken

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#701]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to set the form field for the choice chips. If I set the value of String, The project fails to build with the following error:

```
Running "flutter pub get" in choice_chips_bug...
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/pages/home_page/home_page_widget.dart:112:59: Error: A value of type 'String' can't be assigned to a variable of type 'List<String>?'.
 - 'List' is from 'dart:core'.
                    _model.choiceChipsController?.value = 'Option 2';
                                                          ^
Waiting for connection from debug service on Web Server...         41.7s
Failed to compile application.
```

### Expected Behavior

It should set the value of the form field correctly

### Steps To Reproduce

1. Add a Choice Chips, add some options, add some initial value as well
2. Add a button and set the action to "Set Form Field" and set the choice chips value to something.
3. Run the project and the error will be visible

### Bug Report Code

https://app.flutterflow.io/project/choice-chips-bug-7oorcp?tab=uiBuilder&page=HomePage

### Context

I am unable to update the choice chips according to my needs.

### Additional info

<img width="1344" alt="Screenshot 2023-03-31 at 10 31 15 PM" src="https://user-images.githubusercontent.com/126883330/229190314-e8aabbdb-8000-4e60-bfeb-95fbb0865850.png">
<img width="1414" alt="Screenshot 2023-03-31 at 10 31 22 PM" src="https://user-images.githubusercontent.com/126883330/229190329-5dcfe8b0-4a40-42a7-8bff-5319862992b4.png">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 111.0.5563.64
- Operating system and version affected: MacOS Ventura 13.0
```

**Comment by hariprasadms** [comment]
Hi @SameerShahzad99 - Thanks for posting the issue. I can reproduce the issue.

However check these points as well. For choice chips widget, allow multi select is enabled? if this option is on, you can't map the selected values to a string as value type is list. And also check that you have provided a default value while binding selected value to a text widget.

**Comment by SameerShahzad99** [comment]
Hi @hariprasadms, Thank you so much for looking into this issue, the problem is that i am unable to assign a list of strings values here as well.

**Comment by agreaves** [comment]
Hi @SameerShahzad99 🙂. This will be fixed in the upcoming deploy!
