### ISSUE TITLE
google_fonts package needs update in pubspec file

### ISSUE THREAD

**Issue by EmilioSantillana** [FlutterFlow/flutterflow-issues#702]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was working normally and an error appears on my project in flutterflow app. It seems to be related with flutterflow_colorpicker widget and google_fonts package

![image](https://user-images.githubusercontent.com/49165704/229206574-b2d08433-e7e1-43ac-8eb2-47fb7b6be5d9.png)

### Expected Behavior

Error should not be there, i can't edit pubspec.yaml file

### Steps To Reproduce

1. Create a page
2. Add Color_picker widget
3. Make a custom action and the app will not let you compile 

![custom_action_code](https://user-images.githubusercontent.com/49165704/229207312-064681ee-4225-4447-8196-3809e8a89da4.png)

### Bug Report Code

IT4Kis/l34VIvsdY+Kryb/lFiSQWHDMlaOYwlsJTZ04gF4DvG7l/TMnOVBJuOLC0TVVqeGaZnmQK7vPemvDtFvYnCymabN1Y1LtcQw3zeEWWb4i2CbiRPW5/DZpNGHXF18HQhAknKvZic1IT3Ez7CujJYDfdJZDrIFdANOSbJZOK2SrDX1iXc2URm05KZDPz

### Context

My custom action is generating a random string, i want that string be unique at firebase, the code was working as expected but for some reason it starts showing me that error related with pubspec.yaml file

### Additional info

I tested the app on my machine with vscode and i solved the problem updating "google_fonts: 3.0.1" to "google_fonts: 4.0.3

![pubspec_ss](https://user-images.githubusercontent.com/49165704/229208253-d8eaf5ec-c311-44d8-a919-e036216925ed.png)
"

### Environment

```markdown
- FlutterFlow version: v.3.1
- Platform: Web
- Browser name and version: Microsoft Edge 111.0.1661.54
- Operating system and version affected: Windows 11 Home Single Language
```

**Comment by EmilioSantillana** [comment]
UPDATE: It seems they update flutterflow_colorpicker an hour ago.

Commit: https://github.com/FlutterFlow/flutterflow_colorpicker/commit/769f1f3c92fdfd7c59f431117a2c78b224373ef4

![flutterflow_colorpicker](https://user-images.githubusercontent.com/49165704/229210163-442cf4b0-730a-4707-9283-a8e0926d802d.png)

**Comment by agreaves** [comment]
Hi Emilio, sorry about this issue and thank you for the bug report! We reverted the change you pointed out and fixed the issue not long after. Apologies for any inconvenience!
