### ISSUE TITLE
Not able to change height and width of container according to screen width and screen height

### ISSUE THREAD

**Issue by TanuJain2002** [FlutterFlow/flutterflow-issues#705]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The container is not changing its size in mobile and laptop screen even when I am setting the width and height of container by giving condition of screen width and screen height .

### Expected Behavior

I want the container to be responsive and change its size according to screen width and screen height given in conditions

### Steps To Reproduce

1 . create a newPage.
2 . added a column in scaffold
3 . placed a container in it.
4 . set height using set from variable  , conditional value -> if(global property -> screen width <375 ) set from value -> 500.

### Bug Report Code

IT4ghfLluIhOsdhE7aX6bu9WqGYXNno5a5c0sd4bGA0dCJzuPLMQdvWlTFZoZO3kTFVAPUSmmjsJ+PT4uN/XMvECOTSCftlSzLhudwrKITq5a5OBEZGCRnZ7GdhUfRTFyMGFhh1CBO5fc1ot2zmhOOmRdBDbNpyyIlFISq/LZO4=

### Context

I want to design a UI for web ,tab and mobile , for this I need to build many responsive container ,I tried to give one of the container  width and height by 
![width_height_flutterflow](https://user-images.githubusercontent.com/111673705/229272268-10bf0543-2c21-4da3-b9af-fe9ece61b54e.PNG)
giving condition of screen width and screen height .

### Additional info

![width_height_flutterflow](https://user-images.githubusercontent.com/111673705/229272275-3bc2d784-88b8-4c0c-bd6f-92d617754402.PNG)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web and mobile
- Browser name and version: Chrome
- Operating system and version affected: Windows
I tried to adjust the screens by hot reload of flutterflow
```

**Comment by TanuJain2002** [comment]
I want the parameter to be % of screen ,the container should fit 100% screenheight,50% screenwidth in laptop and 100% screenwidth,50% screenheight in mobile

**Comment by hariprasadms** [comment]
Yo can achieve that as well. You can try using responsive visibility.

**Comment by TanuJain2002** [comment]
But in that that case when phone is auto rotated the textfileds value vanishes bcoz I have set different form for laptop and mobile

**Comment by TanuJain2002** [comment]
Can you elaborate a bit about this or share any documentation
