### ISSUE TITLE
Conditional navigation using  choice chip fails

### ISSUE THREAD

**Issue by TanuJain2002** [FlutterFlow/flutterflow-issues#707]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have set onSelected condition for choice chips and guided it for different navigation.But the navigation do not occur.

### Expected Behavior

![choicechips condition](https://user-images.githubusercontent.com/111673705/229308077-e0431436-62a4-4c11-a048-4d5f3f72ad1f.PNG)
I expected the navigation to desired pages using options of choice chips but this is not so.

### Steps To Reproduce

Create 5 pages named Choice1 ,2,3,4,5 
Inserted choice chip with 5 options as given in screenshot
![choicechips condition](https://user-images.githubusercontent.com/111673705/229308265-c03a36e4-bf81-4ae7-8d36-c62d65d3a626.PNG)
![choicechips2](https://user-images.githubusercontent.com/111673705/229308354-ac412d34-75a6-4d92-9e71-cccd1dd834c1.PNG)
![choicechips3](https://user-images.githubusercontent.com/111673705/229308357-357a2f6c-9153-4c85-88ef-2f9c86c175e9.PNG)
 on each page.
Assigned onSelected actions by selecting choicechips from global property and continued actions as given in screenshot

### Bug Report Code

Cg1XcmFwX3lkcGE4NmV5EvcFChRDaG9pY2VDaGlwc184Mnh6cWtrcxgyIo4CegQIABADugOBAhImEh8I/8oDEg1NYXRlcmlhbEljb25zIAAyCHNldHRpbmdzGgMKATESKhIjCKrAAxINTWF0ZXJpYWxJY29ucyAAMgxzaXhfZnRfYXBhcnQaAwoBMhIoEiEIjMADEg1NYXRlcmlhbEljb25zIAAyCm9uZV9rX3BsdXMaAwoBMxIFGgMKATQSBRoDCgE1GioKAhABEgo6Bgj/////D0AGGgYI/////w8hAAAAAAAAMkAxAAAAAAAAEEAiLgoQGg5wcmltYXJ5QnRuVGV4dBIEMAJABRoCEAchAAAAAAAAMkAxAAAAAAAAEEApAAAAAAAANEA6CgoIU2V0dGluZ3NQAVgB+gMAYgCKAcgDEsEDCghzamFpeDM3Yhq0Awo5CjcIClIzEiYSJAgHEhRDaG9pY2VDaGlwc184Mnh6cWtrc0IKQggKBhADIABAABIFCgMSATMiAggBEkUKCGE0am5yMTVsEjkSLBABGhMqEVNjYWZmb2xkX3diMWlwMGd4IABSEVNjYWZmb2xkX3diMWlwMGd4qgIIcnd5Z3o3NDEarwIKCDV4eHNjdWt5GqICCjkKNwgKUjMSJhIkCAcSFENob2ljZUNoaXBzXzgyeHpxa2tzQgpCCAoGEAMgAEAAEgUKAxIBNCICCAESRQoIMDU2N2Q2MXYSORIsEAEaEyoRU2NhZmZvbGRfNWUwNnQ5OG8gAFIRU2NhZmZvbGRfNWUwNnQ5OG+qAgg4eDE0cmx5YhqdAQoIZDQxd2c1eDUakAEKOQo3CApSMxImEiQIBxIUQ2hvaWNlQ2hpcHNfODJ4enFra3NCCkIICgYQAyAAQAASBQoDEgE1IgIIARJFCgg2bGtlM2N3cxI5EiwQARoTKhFTY2FmZm9sZF93b3ExYjVzYiAAUhFTY2FmZm9sZF93b3ExYjVzYqoCCGNpOHlvZzQ4GgwKCGp0ZDB2dTRoIgAaAggWGDciQVobCQAAAAAAAEBAGQAAAAAAAEBAIQAAAAAAADRA4gMeCQAAAAAAAAAAEQAAAAAAAAAAGAEgASgBMAY4AUAC+gMA

### Context

I am  not able to accomplish navigation usingn choicechip

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform:Mobile
- Browser name and version: Chrome 
Just ried to run it preview mode
```

**Comment by bulgariamitko** [comment]
I will close this issue as I think this is not an issue, because you need to have different paths and only one main condition in your Action flow. This is actually coming in the next release of FF so I will mark it as a future request.
