### ISSUE TITLE
Icon Buttons Rebuild after updating app state not working

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#709]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The page does not refresh after updating the app state, even though "rebuild all pages" is selected.
I am unable to see the conditional visibility changes.

### Expected Behavior

The Page should refresh with the latest app state value and i should be able to see the conditional visibility changes.

### Steps To Reproduce

1. Add two icons with conditional visibility set to an app state variable.
2. Update the app state when these icons are preseed to opposite states

### Bug Report Code

IT4oz/Hqx89grs9J1s/IdfoxnSQvQmY+RI0V0MpBbzIgfePrD7AQP8nRP1dUOMDiYwk6fE2aimMX/MrTheLpMfoENgSsG707/5dQEw/LRlOnV6amCpS3b398DcFRN0PEyMKg2BVSJbd2LEZk3WD3GtzKHwLcQ+e3OUgjPOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

I am unable to create the favourites functionality and dark mode due to this problem.

### Additional info

https://user-images.githubusercontent.com/126883330/229344432-c4c2264d-f2ad-4bf1-b0eb-dbbdabab04c7.mov

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 111.0.5563.64
- Operating system and version affected: MacOS Ventura 13.0
```

**Comment by corsaro0** [comment]
Similar issue here, the condition is glitching after the recent flutterflow update. 

I have an icon button that changes color based on the backend query. When I change the backend data, the change is not immediately reflected in the frontend like before. I have to refresh the page. before the update everything works fine

**Comment by agreaves** [comment]
We have identified and fixed the issue, so it should now be working again! 🙂
