### ISSUE TITLE
the named iconColor is not defined

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#710]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the named iconColor is not defined
 iconColor: MaterialStateProperty.resolveWith<Color?>

### Expected Behavior

the iconColor should be defined when the code is generated.

### Steps To Reproduce

1 Create a project.
2 Download the code
3 the named iconColor is not defined
 iconColor: MaterialStateProperty.resolveWith<Color?>

### Bug Report Code

IT4olfLluJZ1ofVY7c/QdcBv9CQWJVg2RLgZkspBZzAaIrb1CLMqY8mnPxdVXb3iTWxbPmC2p141092PufDxUvA4HASbftVSyM9tFjrjUkCiR4uTF7rtXndABelWf3615MOvsxR5OsZeWl4k1znzCOu9YHfUK737DWowSq/LZO4=

### Context

My app can't compile and can't run with the named iconColor is not defined
 iconColor: MaterialStateProperty.resolveWith<Color?>

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform:mobile
- Browser name and version:Chrome 111.0.5563.64
- Operating system and version affected: MacOS Ventura 13.0
```

**Comment by hariprasadms** [comment]
Hi @ibm777p2 - Can you please add images or a quick video showing error. I am not able to re-produce it. add more details to steps details which can help to reproduce the issue. 

Is your app is compiling in the FF editor run and test mode ?
Is this compile is failing while running downloaded code locally?
 
Thanks.

**Comment by wenkaifan0720** [comment]
Hi @ibm777p2. Could you take a look at this [post](https://community.flutterflow.io/c/discuss-and-get-help/no-named-parameter-with-the-name-iconcolor-can-t-compile-android-studio#all_comments)? If you upgrade your Flutter version to 3.7.3 or up, this error should go away.

**Comment by ibm777p2** [comment]
> Hi @ibm777p2. Could you take a look at this [post](https://community.flutterflow.io/c/discuss-and-get-help/no-named-parameter-with-the-name-iconcolor-can-t-compile-android-studio#all_comments)? If you upgrade your Flutter version to 3.7.3 or up, this error should go away.

How exactly I update the version of FF? by refreshing the browser ? do you have a documentation of how do that?
I have this on my browser.
![image](https://user-images.githubusercontent.com/5303536/229546369-6bb15c6f-a268-4fc2-9288-72d052dd8474.png)

**Comment by wenkaifan0720** [comment]
I mean the local Flutter version you have. You should be able to do so by running `flutter upgrade` in your terminal.

**Comment by ibm777p2** [comment]
> I mean the local Flutter version you have. You should be able to do so by running `flutter upgrade` in your terminal.

Yeah, I figured out that would be the local version, did the upgrade, doing some testing now. Thanks
