### ISSUE TITLE
conditional visibility in not instant

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#711]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in a page i have set some icons based on certain conditional visibility. now if the conditions change the visibility must also change instantly. but it is not. if i nav to another page and come back then only can see the change

### Expected Behavior

the conditional visibility must work instantly after data changes

### Steps To Reproduce

1. add conditional visibility to icons on a page(some condition to show/hide)
2. now change the conditions
3. the changes will not reflect immediately
4. you need to nav to another page and return to see the change
5. this works from page state but not from firestore documents

### Bug Report Code

IT8ol/KA4Y92rtdc1pPqL+9VijsXJmY6RYI7l9Vhaw4YGIvqB4YEeOHOVBRBXfW5S3lHBFaj8TgI7vDWkYbPC8YCAxGIQ75T1c0BVQuWVj6VR5CSCLiSf399J5pbJlSk56COihVdIvNoc04i7Dv3GemscHbAJr7JIkcNOvmYFNz/omuqLA7dIDh2tmNecCfn

### Context

i have set some data in a form that needs to reflect based (conditional visibility) on user input. since it is not reflecting immediately, that form is not usable 

### Additional info

this was working earlier. some update created this issue

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:web
- Browser name and version:chrome Version 111.0.5563.147 (Official Build) (64-bit)
- Operating system and version affected: windows 10 pro
```

**Comment by corsaro0** [comment]
Maybe I understood the problem. The widget is now set to Futurebuilder mode. It was probably set in streambuilder before. for this reason the widget does not update. How do I change the widget back to streambuilder format?

**Comment by sohaibilyas** [comment]
same here, it was working fine before the recent flutter themes update.

**Comment by agreaves** [comment]
Hi @padeepz, thanks for the bug report! We have identified and fixed the issue, so it should now be working again for you! 🙂
