### ISSUE TITLE
FlutterFlow Theme Widgets: wrong background color makes them invisible in theme editor

### ISSUE THREAD

**Issue by HeikoKanzler** [FlutterFlow/flutterflow-issues#712]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With the new widget theme editor, the preview of the widgets changes background color depending on the selected theme of the FlutterFlow app (Mac and web). This makes working on designs with the enabled light app theme almost impossible if you use dark fonts and elements as they are shown dark on dark.

![CleanShot 2023-04-03 at 11 16 32](https://user-images.githubusercontent.com/5279575/229470183-acf4fa77-f604-4aff-a291-e3b001637498.jpg)

### Expected Behavior

FlutterFlows look&feel has nothing to do with the app I design, so I expect a white background, no matter what application theme is set.  

### Steps To Reproduce

1. set FlutterFlow app theme to light
2. Open a project
3.  add a new theme widget, e.g. a text input field with dark font and underline
4. see the dark background blends with the theme properties
5. 
![CleanShot 2023-04-03 at 11 33 59](https://user-images.githubusercontent.com/5279575/229471157-771c2554-407e-44c0-bc22-38a331b04901.jpg)

### Bug Report Code

n/a

### Context

n/a

### Environment

```markdown
FlutterFlow version: v1.1.57
Platform (e.g. Web, MacOS Desktop): Mac
Operating system and version (desktop): macOS Ventura 13.2 (22D49)
```

**Comment by wenkaifan0720** [comment]
Hi @HeikoKanzler. You are right. We allow the user to switch the background color between black and white when they enable dark theme colors. But we should allow this even if they don't. This will be fixed in our next update. Thank you for raising this issue.
