### ISSUE TITLE
Test run fails when accessing dropdown component state in list

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#713]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No errors are shown in project but test run gives these error:

Running "flutter pub get" in ag_teams...
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/business_update/business_update_widget.dart:1010:76: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
                                                                          .requesterRoleDropDownValue,
                                                                           ^
lib/business_update/business_update_widget.dart:1066:72: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
                                                                      .requesterRoleDropDownValue,
                                                                       ^
lib/business_update/business_update_widget.dart:1511:78: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
                                                                            .requesterRoleDropDownValue,
                                                                             ^
lib/business_update/business_update_widget.dart:1532:76: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
                                                                          .requesterRoleDropDownValue,
                                                                           ^
Waiting for connection from debug service on Web Server...         60.2s
Failed to compile application.

### Expected Behavior

Show a List with each tile having dropdown components and can access dropdown any component state based on its index.

### Steps To Reproduce

1. Create a list with FB query
2. Use a dropdown component in it.
3. Try to access any dropdown component state and use it in some action.
4. Run Test and you will get errors.

### Bug Report Code

IT40z/Hqx89gocNf7aXpbfpajic5KVgjbY0nlutRaCsofePrOpkAf8/7UFtUOPaqYFV+fWH8sHEX/MrQueOeLcA7PU+Abos7ypBqagvJe3OiM4yRPIS3b0FSRNhQBUyB5LennBBCBPpuR1Id1Du2BNmybz3bQYztOm0zBeaeXdeK2SrDX1iXc2URm05KZDPz

### Context

Trying to show a list with each tile having a dropdown and then using that value in action.

### Additional info

getValueAtIndex is the function causing error:
```
        _model
       .requestorComponentModels
       .getValueAtIndex(requestListIndex,(m) => m.requesterRoleDropDownValue,)
```
but when replacing locally with a fallback value for null then it works fine:
```
        _model
       .requestorComponentModels
       .getValueAtIndex(requestListIndex,(m) => m.requesterRoleDropDownValue,)??'User',)
```
These are the actions causing issue:
<img width="631" alt="Screenshot 2023-03-31 at 9 45 48 AM" src="https://user-images.githubusercontent.com/102008213/229478711-fc2f7a93-fc28-4fa9-8b7f-e1093cf02bfa.png">
<img width="657" alt="Screenshot 2023-03-31 at 9 50 06 AM" src="https://user-images.githubusercontent.com/102008213/229478720-34aebda7-bc3c-4ad8-a374-194bace1b1f9.png">
<img width="321" alt="Screenshot 2023-03-31 at 9 50 34 AM" src="https://user-images.githubusercontent.com/102008213/229478721-59318be9-fe3e-425d-82bb-69c57738cbed.png">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @Shubham-VE - If I have understood the issue correctly, you are trying to get the list of data form firebase and binding that data to a dropdown widget. The selected dropdown value, you are trying to use in a subsequent action. Is that correct ? Correct me if I am wrong. 

In this case, you should have a default value set to the field/parameter you are trying to use the selected dropdown. Use app state or page state variable to hold a default value and set the state of the variable once dropdown value is selected.  I think the error you are seeing because, when page is loading, dropdown value is not yet selected and its value is null. 

Try this solution and see how it works.

**Comment by Shubham-VE** [comment]
I cannot Test run due to this issue, is there any update on this?

**Comment by shelpert** [comment]
Hi, I am trying to investigate your issue, but I cannot find where you are using the RoleDropDownComponent in your project snapshot. Can you post a new bug report code generated from that component in the widget tree? If you aren't currently using it in your project you can create a dummy page with your steps to reproduce so I can better understand the issue. Thanks!

**Comment by shelpert** [comment]
Hi @Shubham-VE,
This issue has been fixed! It should be out with the next new version (but not the one that came out today).

**Comment by Shubham-VE** [comment]
I am still seeing this error on my end.
