### ISSUE TITLE
Test Flight app Crash

### ISSUE THREAD

**Issue by Dom-Cogan** [FlutterFlow/flutterflow-issues#716]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On Flutter Flow the project seems as if everything is connect and setup properly.The app run perfectly fine in the development environment online. I have no issues deploying the app from the flutter Flow website, however once the app is on my Apple connect page and in test flight the app just outright doesn’t work. When downloading the same build that works fine online onto a device it will crash on load

### Expected Behavior

The app the load, and to function and load like it does on the online development environment.

### Steps To Reproduce

1. Delopy app to Apple connect from flutter flow
2. Wait for app to be avail e on test flight
3. Download app
4. Attempt to launch app

### Bug Report Code

No big report code generated as it is happening once the app is downloaded on to the users device

### Context

Trying to deploy the app onto Apple and android devices

### Additional info

I have 5 crash logs that I can and will share if needed.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iOS
- Browser name and version: chrome
- Operating system and version affected: iOS 16.4
```

**Comment by wenkaifan0720** [comment]
Hi @Dom-Cogan. Could you provide the bug report code, and the crash logs? Thank you.

**Comment by Dom-Cogan** [comment]
[crashlog-5E90743A-8C36-4B94-9A8F-0658B4889ACE.txt](https://github.com/FlutterFlow/flutterflow-issues/files/11142406/crashlog-5E90743A-8C36-4B94-9A8F-0658B4889ACE.txt)
[crashlog-30FAFC6A-CFFB-420B-8808-271FC555770F.txt](https://github.com/FlutterFlow/flutterflow-issues/files/11142407/crashlog-30FAFC6A-CFFB-420B-8808-271FC555770F.txt)
[crashlog-EEDABE35-22AE-429D-9F99-557FE938328B.txt](https://github.com/FlutterFlow/flutterflow-issues/files/11142408/crashlog-EEDABE35-22AE-429D-9F99-557FE938328B.txt)
[crashlog-DC168A5D-460A-4CF8-AF3B-BE926395CC1D.txt](https://github.com/FlutterFlow/flutterflow-issues/files/11142409/crashlog-DC168A5D-460A-4CF8-AF3B-BE926395CC1D.txt)

**Comment by wenkaifan0720** [comment]
And the bug report code please? I still need that to access info about your project.

**Comment by Dom-Cogan** [comment]
How do I get the bug report? The bug happens when downloading the app onto an actual device. Not when I’m on flutter flow.

**Comment by wenkaifan0720** [comment]
In you widget tree, right click on any widget, and get the bug report code. This is to prevent sharing your project details on Github directly.

**Comment by Dom-Cogan** [comment]
ITFXz/Ll8YxIrsxE0KnTY8ZKgiMwFjMMbY0v0u0bFB4dGLb3BLM2Zcj7MkNKT7C8em56HGebgnICpK3Jv4TDC/AVFzicY65b0JVAahbgRlqgacjTOruOdHAlEf9YJ0iH4LbQrCZCJthaW14l12b6N63qNleeY8aSfxBlZ7vfcPo=

**Comment by Dom-Cogan** [comment]
sorry for the delay I just got home

**Comment by Dom-Cogan** [comment]
Let me know if you require anything else from me. Thank you

**Comment by kevintonb** [comment]
Hey @Dom-Cogan , we assume this issue has been fixed with latest FF updates. Let us know if you still see the issue. We can re-open and investigate the issue further.
