### ISSUE TITLE
Video/Media display for video never gets refreshed. 

### ISSUE THREAD

**Issue by ISHA7782** [FlutterFlow/flutterflow-issues#717]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For media display or video never gets updated video after initial value sets. 

For example - 
Set a video source to a, and media displays the video a . 
After a trigger lets say button click, change the source to b, video still shows a , instead of b. 

### Expected Behavior

Whenever a video source is updated, flutterflow should show the new video instead of previous one on page build. 

### Steps To Reproduce

1. Create a Media display widget 
2. Create a page state - videoBool , and assign the value as bool true
3. Conditional assign the video based on flag - videoBool , if videoBool true, set value to a , else b. 
4. Create a button, and on click change the value to false, and rebuild the current page. 

Expected behavior is video should be updated, but it is not happening. 

### Bug Report Code

FlutterFlowMediaDisplay(   path: _model.testvar       ? 'https://media.istockphoto.com/id/1455826997/video/vj-loop-neon-room-mirror-room-with-neon-light-abstract-festive-bg-with-bright-reflection-dark.mp4?s=mp4-640x640-is&k=20&c=Y5OVTlH6jEDCjSLZzyvfTosdRkkvBvQizSwXoEmM59I='       : 'https://media.istockphoto.com/id/1347266466/video/luminous-christmas-shooting-star.mp4?s=mp4-640x640-is&k=20&c=VJxeGjcY81qmmDiguJi43296jo8AS7jfWGzv6cbANq8=',   imageBuilder: (path) => Image.network(     path,     width: 300,     height: 300,     fit: BoxFit.cover,   ),   videoPlayerBuilder: (path) => FlutterFlowVideoPlayer(     path: path,     width: 300,     autoPlay: false,     looping: true,     showControls: true,     allowFullScreen: true,     allowPlaybackSpeedMenu: false,   ), )

### Context

Production scenario for user updating the profile video, and displaying in the page.

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac 13.3
```

**Comment by shelpert** [comment]
Hi! We have added a fix for this bug, which you will see in a future deploy! I'd like to note here that the issue was not because of page/app state update issues, but was in the FlutterflowVideoPlayer itself.
