### ISSUE TITLE
Action component parameter cannot be set in showing a Bottom Sheet

### ISSUE THREAD

**Issue by MaggieThomann** [FlutterFlow/flutterflow-issues#718]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to have a bottom sheet that has an action as one of its component parameters so that I can then execute that action via a callback in the action tree. When I define an action to be one of the component parameters of the bottom sheet, I am unable to set it in the page where I show the bottom sheet.

### Expected Behavior

I would expect to be able to set the value of the action component parameter when I show the bottom sheet in a different page.

### Steps To Reproduce

You can go to my project "Test" and view this behavior. Otherwise:
1. Make a page with a button on it.
2. Make a bottom sheet component and define one of the component parameters to be an action.
3. Go back to the page and in the "On tap" action of the button, add an action to Show the bottom sheet.
4. Attempt to pass the action parameter to the bottom sheet and it won't work.

### Bug Report Code

ITESz/Hqx89goeIB0KqBYOxAhQAkH1x/bZJEl9cbRUogfIzxPZYEeur+VBJdX+mGTwpMD1aWrFIBwN7HueL9J/U7NgSaUoNo+bVfEg7NczqQRL7SOrqWZEFPGf5bJ2qZ56S73wokLrNaSF4dw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I want to be able to pass an action to a bottom sheet so that I can execute that action as a callback in the action tree of the bottom sheet. This is ultimately to build a more reusable bottom sheet component in our project.

### Additional info

https://user-images.githubusercontent.com/15825518/229720441-e6e80eea-b981-4cba-a6e5-50b7ef69621a.mov

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Version 111.0.5563.110 (Official Build) (arm64)
- Operating system and version affected: Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @MaggieThomann  - Thanks for reporting the issue. I can re-produce the issue.

**Comment by MaggieThomann** [comment]
@hariprasadms any update on this? I'm still experiencing this issue.

**Comment by MaggieThomann** [comment]
Hi @shelpert any chance this fix will be released soon? I'm still experiencing the bug and would like to standardize my bottom sheets more by using a single one that I pass different actions to.

**Comment by MaggieThomann** [comment]
@agreaves any chance you could take a look at this one, Alex? I just checked and this is still an issue and I have a feeling it might have gotten buried.
