### ISSUE TITLE
Center gets added to loading component even when unselected

### ISSUE THREAD

**Issue by davidoort** [FlutterFlow/flutterflow-issues#719]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a backend query on a text widget. When I select a custom component as a loading indicator and leave center component as false, the generated code still contains a Center wrapper widget on the custom component.

### Expected Behavior

I would expect that the Center wrapper would only appear when the "Center component" option is selected.

### Steps To Reproduce

1. Create a new page
2. Add a text widget
3. Add a backend query to that text widget
4. Create a custom component and add that as the loading component
5. Do not select "Center component"
6. Click on generate code and observe that there's a center widget wrapper around the component.

### Bug Report Code

Padding(   padding: EdgeInsetsDirectional.fromSTEB(12.0, 4.0, 12.0, 4.0),   child: FutureBuilder<int>(     future: queryFriendsRecordCount(       parent: widget.userRef,       queryBuilder: (friendsRecord) =>           friendsRecord.where('is_accepted', isEqualTo: true),     ),     builder: (context, snapshot) {       // Customize what your widget looks like when it's loading.       if (!snapshot.hasData) {         return Center(           child: Container(             width: 50.0,             child: SkeletonPriceTextWidget(),           ),         );       }       int textCount = snapshot.data!;       return Text(         (int? numFriends) {           return numFriends == 0               ? "No friends yet"               : numFriends == 1                   ? "1 friend"                   : "$numFriends friends";         }(valueOrDefault<int>(           textCount,           0,         )),         style: FlutterFlowTheme.of(context).bodyMedium.override(               fontFamily: 'Gilroy',               color: FlutterFlowTheme.of(context).primaryText,               fontSize: 14.0,               fontWeight: FontWeight.w600,               useGoogleFonts: false,             ),       );     },   ), )

### Context

The loading indicator just looks bad when centered so I want to be able to unselect it and remove the Center widget

### Environment

```markdown
- FlutterFlow version: 1.1.57
- Platform: MacOS
- Browser name and version: Not tested on FF webapp
- Operating system and version affected: Macos Ventura 13.2.1
```

**Comment by agreaves** [comment]
Hi @davidoort, thank you very much for this bug report and apologies for the delay in fixing! This is indeed an issue, which will be fixed on our next deploy. To match the current behavior (we don't want to change people's apps suddenly), all such loading indicators will be reset to Centered, so you may need to change them in the UI Builder to your preferred setting.
