### ISSUE TITLE
Pie Chart is not working in Test Mode and generate another one when is clicked

### ISSUE THREAD

**Issue by Franco-Cruz-Schoolfy365** [FlutterFlow/flutterflow-issues#72]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The pie chart should display

## Current behavior (required)

Show an error

## To Reproduce (required)

1. Create a Pie Chart
2. Add random values
3. Run on test mode and it doesn't work: Timestamp: 0:45

If click the Pie Chart generate another Pie Chart: Timestamp 1:49

## Context (required)

I want show a Pie Chart

## Screenshots / recordings

https://schoolfy365.tinytake.com/msc/NzUxMTM0M18yMDQ0NTkyOQ

## Your environment

* **Bug Report Code:** ITFTz/Hqx89grtRI+KX2du1GiigWM0MAWOcViuxHcx4cJZD2PYkXdczObUNKTM+XY25mJ2GYimAEwez0j9/hL/c7OgSuGog/k/UwKlCvHAM=
* Version of FlutterFlow used: v3.0 - 28 October
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Brave - Version 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - OS Build: 22621.674 - Version: 22H2

**Comment by Pepino-GR** [comment]
I can reproduce this issue.

**Comment by agreaves** [comment]
Thanks for the bug report! We've fixed this issue and it will be deployed in the next release!
