### ISSUE TITLE
Dsym not found in ios app

### ISSUE THREAD

**Issue by mixalis795** [FlutterFlow/flutterflow-issues#721]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The dsym is missing so i cant have crashanalytics on my ios project. There is no dsym download button on ios app store page

### Expected Behavior

have the dsym on ios

### Steps To Reproduce

see screenshot. i have deployed 10 times 

### Bug Report Code

ITFfi8mBw5JOxcNA14SJd+14iiQsJmEcTL4zlO1HcxAYGO/yPbJ+eOP7dRJVOdzgSnlhHFmbjkkepPTMufLLDcEnEw6sfL581rl9VQ/xUXq8RZSXEbrpXnMkEcpmGkCg57arswkkPsZ1ckYW2EOqINitYCzDCZu/Zwh9f6PHaOI=

### Context

i cant see any crashanalytics data on ios app
this is my app for ios https://app.flutterflow.io/project/morfosis-g71mai

### Additional info

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/121205987/229811217-a28216f3-72a2-4fa0-992e-b3e11d3afa63.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/121205987/229811280-217d4df5-918d-4598-9a15-7213758dba2a.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/121205987/229811631-178a6f8c-91cb-4c5a-ba48-c774750a49ca.png">
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/121205987/229811700-802821be-69d8-43c3-b5a4-3748dc070135.png">

### Environment

```markdown
- FlutterFlow version: latest
- Platform:ios
- Browser name and version:chrome
- Operating system and version affected: ios all versions after
1.2.26 (145). before it said optional
```

**Comment by HeikoKanzler** [comment]
+1, drive me (and others in the community) crazy. Makes Crashlytics complete useless.

**Comment by wenkaifan0720** [comment]
Hi all. I believe this issue is related to this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/67. To resolve this issue immediately, you can build the iOS app locally and upload the dSYM file manually. We are working on a fix right now, but it could take some time. I'll close this issue as it is a duplicate.

**Comment by dmk23** [comment]
> Hi all. I believe this issue is related to this issue: #67. To resolve this issue immediately, you can build the iOS app locally and upload the dSYM file manually. We are working on a fix right now, but it could take some time. I'll close this issue as it is a duplicate.

Is there an ETA for a fix? Deploying with CodeMagic and getting the same problem
