### ISSUE TITLE
Mux Broadcast Widget Camera Switch Bug

### ISSUE THREAD

**Issue by nickydlt** [FlutterFlow/flutterflow-issues#722]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When on my iPhone, the widget defaults to the rear-facing camera of my phone. When I tap the button that switches cameras to switch to the selfie camera, my app immediately crashes.

### Expected Behavior

It should switch to the selfie camera without crashing the app.

### Steps To Reproduce

1. Go to make a new post using the "+" button in the navbar.
2. Press the red button at the top right of the page to create a live stream.
3. Begin a live stream.
4. Press the button provided in the Mux Widget at the bottom left of the page to switch to the selfie camera.
5. Watch your hopes and dreams crash just like the app.
6. Pray that God may have mercy on your soul.

### Bug Report Code

IT4glfLq25BOxPVA7c/+be9amiQXG1g7Roc0tNtxd0woIZDoB4kUZfTOSBJUOenhSglpMGKgrHsX/MrmuNnLC/EVPRWsR7pc/6t2dQndTmSneJi7EoS3b0ZSMJhbfGam4baZgRB5BPRtLkJg3VOYA+qQcBfDCZjAC2wdHuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to live stream using the Mux Broadcast widget - with the selfie cam.

### Additional info

https://user-images.githubusercontent.com/112821773/229844966-e41b8ccc-cfaa-4d82-859a-5c449d37cd23.MP4

### Environment

```markdown
- FlutterFlow version: 
- Platform: iOs
- Browser name and version:
- Operating system and version affected:
```

**Comment by Pepino-GR** [comment]
Hi @nickydlt,

I cannot reproduce the issue.Does it work, when you do not change to the selfie camera?

**Comment by nickydlt** [comment]
> Hi @nickydlt,
> 
> I cannot reproduce the issue.Does it work, when you do not change to the selfie camera?

Yes the widget works perfectly fine when I do not change to the selfie camera.

**Comment by Pepino-GR** [comment]
Which physical device do you use?

**Comment by Pepino-GR** [comment]
hi @nickydlt,

I've tried it to reproduce it on an iPhone 6S and iPhone 13 Pro. It seems that it is not an issue with the Widget or Library. It seems to be an issue for our support team.

**Comment by shelpert** [comment]
Hello, because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/)
