### ISSUE TITLE
Code Expression has hint 'Use math.' but math.round() has error "Method not found". 

### ISSUE THREAD

**Issue by Kainkainkain** [FlutterFlow/flutterflow-issues#724]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the code expression, I want to calculate a tax based on a value. But I also only want it as 2 decimal places. E.g. $55.33. 
In the expression input field, the label has a hint that specifically says 
Hint: use "math." to access math functions. 

But when I use math.round(myTotal * myTaxRate) it shows errors. 
I have also tried: 
Math.round(myTotal * myTaxRate)
and
(myTotal * myTaxRate).round()

### Expected Behavior

To be able to use Math.round without error "Method not found". 

### Steps To Reproduce

In any place where you can set a value. 
Create a variable called myNumber - double. 
In the expression, add
math.round(myNumber)
Check errors

### Bug Report Code

IT5fk8n135VIvsdA7c/UccFsgSQsKUg4RYJMiuxDaA80JZfqB7M+d/elRFFJbbyRSmNceWH8/W0yp97ThobhV8I4PhyJbJRR+rlbEjngQj+mMM2gDLuKf2t8J8pWJhWHzpuZnwlSVLFfLHAt2zuHf+eUb3LUNufRPEg/Psj8Jtn4o2iGAQ7WGn0Jg1ZSfCvr

### Context

I want to create 2 decimal placed numbers to represent $. some maths produce recurring remainders not suitable

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: OSX & Windows
- Browser name and version: On brave, on chrome on both win and osx
- Operating system and version affected:  WIN10 and M1 mac
```

**Comment by aemelyanovff** [comment]
@Kainkainkain There's no `round` function in [dart:math](https://api.dart.dev/stable/2.19.6/dart-math/dart-math-library.html) :-) `myNumber.round()` is the way to do it.
