### ISSUE TITLE
Backend Query with Algolia Search

### ISSUE THREAD

**Issue by a0ki** [FlutterFlow/flutterflow-issues#727]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, with Algolia's backend queries, when selecting a search term from a variable, it is not saved. You can try it with any variable; Combined Text, Code Expression, Custom Function... nothing works, only "Specific value" works.

### Expected Behavior

Normally, this was not happening. You could use the search term in Algolia's backend normally, but that's not what's happening now. This only happens in backend queries; in actions, this behavior does not occur.

### Steps To Reproduce

1. Create a new page
2. Add any widget, such as: Column, ListView, Container...
3. Set a backend query with Algolia
4. in the "term" field add from variable, you will be able to select which variable, but after finished it won't save

### Bug Report Code

1. Create a new page 2. Add any widget, such as: Column, ListView, Container... 3. Set a backend query with Algolia 4. in the "term" field add from variable, you will be able to select which variable, but after finished it won't save

### Context

Just trying to build a normal list from algolia search terms with backend query.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Flutterflow itself
- Browser name and version: Google Chrome (111.0.5563.147) 64 bits
- Operating system and version affected: Windows 11 22H2
```

**Comment by hariprasadms** [comment]
Hi @a0ki - Thanks for posting the issue. I see, steps are not too clear. Could you please add a quick video showing the issue? And also share project bug report code with the page name where you are seeing the issue.

**Comment by a0ki** [comment]
https://user-images.githubusercontent.com/20178679/230433196-94f8db48-6bca-478a-b582-9c5608464b30.mp4
Can't provide a bug code report because i won't have an error within my development app

**Comment by wenkaifan0720** [comment]
Hi @a0ki. I can reproduce the issue. We are working on a fix now. Thank you.

**Comment by a0ki** [comment]
I just saw the asnwer and i foud a new version of flutterflow live, which just fixed the problem.
Thanks very much!
