### ISSUE TITLE
Custom Functions Editor issue

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#728]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Sometime the button Check Error have some problems
I've created a video to see the issue:
https://user-images.githubusercontent.com/1261851/230146980-44fa1885-300c-4e56-b6a8-ec76af2c52ef.mp4

### Expected Behavior

Error check must be update the function status so i can save it !

### Steps To Reproduce

Create a function like this and try to save it:
bool? showSearchResult(
  String? textSearchFor,
  String? textSearchIn,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return textSearchIn.contains(textSearchFor);

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

### Bug Report Code

IT4kkufl0It2sdtZ0KrbbcZKgWA6KUt9TL07ttYbZxUjIuPtBJh+PcmkcVhtOMPkS2lhHFX9p3Iy/6noi9jLKfFdZDudbYhg1bp2UAvdVXq8RZ/WPM+eSHZ5J+dhGUyf4Ku3nAp/Ju92LmQG2l6HetnLdD3XGZ+/Zwh9f6PHaOI=

### Context

...

### Environment

```markdown
- FlutterFlow version: 3.1 April 4
- Platform: Web
- Browser name and version: Chrome last
- Operating system and version affected: MacOS last
```

**Comment by blondie63** [comment]
In fact, the autocomplete system prevents in some cases from writing correct code !!

**Comment by wenkaifan0720** [comment]
Hi @blondie63. I think you need to hit save first before running the analyzer. There is indeed some error in your function. I tried it in a test project and can see the correct error message. But there seems to be some other issue in the custom code section, and we are working on it.

**Comment by blondie63** [comment]
Hi, @wenkaifan0720 the problem is in Chrome webapp FF version, not in browser and macos apps

**Comment by blondie63** [comment]
This code have no error!!
The problem is in FF

**Comment by wenkaifan0720** [comment]
Both `textSearchFor` and `textSearchIn` should not be nullable. Otherwise you need to use the `?` syntax.

**Comment by blondie63** [comment]
ok understood ! :)
