### ISSUE TITLE
Call number Action don't produce the code right

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#73]
## Expected behavior (required)
To be generated the right code. Right now the number is missing. 

## Current behavior (required)
Generating this code
```
onPressed: () async {
    await launchUrl(Uri(
      scheme: 'tel',
      path: '',
    ));
  },
```

## To Reproduce (required)
1. create a button
2. add call a number action
3. in the call a number action fields choose specific value
4. add any number for example 1231313
5. go check developer menu
6. find the button you have create
7. in the action of the button you will see schema and path
8. the path is empty which should have a number inside it and not empty

## Context (required)
The Call Number Action is not working. 

## Screenshots / recordings
https://community.flutterflow.io/c/bugs/call-a-number-action-is-not-working

## Your environment
ITESz/Hqx89grswE0arQL8J6hQAkH1x/bZJEl9dTSRU0GK7nPZouZur+V1pfOtORfVBUIU6kmj8E0aGNjYftMsYqNgecetE2k/UwKlCvHAM=
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: Chrome 107
* Operating system and version (desktop or mobile): desktop

**Comment by wenkaifan0720** [comment]
Hi. This is a bug we are now aware of and have pushed a fix to it. It should be live by the end of this week.
