### ISSUE TITLE
The conditional visibility is not working on adjacent elements.

### ISSUE THREAD

**Issue by walden4u** [FlutterFlow/flutterflow-issues#730]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am storing a boolean value in the App State and manipulating two icons' conditional visibility based on it. Although the App State's value is changing correctly, why is the screen not updating accordingly. Wrapping the icon in a container resolves the issue and the conditional visibility works properly. It seems to be an error where the conditional visibility does not work properly on adjacent elements.

https://community.flutterflow.io/c/bugs/the-conditional-visibility-is-not-working-on-adjacent-elements

### Expected Behavior

The conditional visibility work properly on adjacent elements.

### Steps to Reproduce
1. make App State(VisualFlag, boolean) 
2. Insert Button in column
3. Insert Row in column
4. Insert IconButton in Row
5. Insert IconButton in Row
6. make conditional visuality on IconButton1 (if ture)
7. make conditional visuality on IconButton1 (if false)
8. make action on Button( update app state if ture -> false, if false -> true) 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4kkub2zIt1od9E1s/xbe54migvKWZ+TL0zqNYbGA0oIYyuOpl/evWldklVZNTgY29iMUSmmjgCpqyKvd7DNO5fCE2VG4hbyZdfWgziUkyla5OBOrm0PUckJ5lmJm2B36SnmRNTIfhtSnhm31yuf+eQSj3DCb62IlFISq/LZO4=

### Context

https://community.flutterflow.io/c/bugs/the-conditional-visibility-is-not-working-on-adjacent-elements

### Visual documentation

https://community.flutterflow.io/c/bugs/the-conditional-visibility-is-not-working-on-adjacent-elements

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web 
- Browser name and version: Chrome
- Operating system and version affected: Mac Os
```

**Comment by aemelyanovff** [comment]
@walden4u Please fill out steps to reproduce. They should start from a blank project.

**Comment by walden4u** [comment]
> @walden4u Please fill out steps to reproduce. They should start from a blank project.

I'm done.

**Comment by NewUser35** [comment]
apologies - I can't see the thumbsup/upvote icon.  

If it helps to add ...I have a very similar issue.

I have two adjacent check box icons that have:
1. action / on-tap update a boolean to the database and 
2. conditional visibility based on that update.  

The database update happens ok, and the icon behaves as if  its visibility has changed (ie when user clicks on it a second time teh response is as though the original ontap change had occurred).  

But the user sees the original icon as unchanged - the conditional visibility is not showing the change.

If the user navigates away from the page in question, and then returns, the conditional visibility will update and it displays correctly at that point.  
Thx

**Comment by corsaro0** [comment]
Same issue, with icon button condition state doesn't work!

I have an icon button that changes color based on the backend query. When I change the backend data, the change is not immediately reflected in the frontend like before. I have to refresh the page. before the update everything works fine.

Same issue with condition visibility.

Please help us soon because our app doesn't work...

**Comment by agreaves** [comment]
Hi @walden4u, thanks for the bug report! @aemelyanovff has identified and fixed the issue, so it should now be working again for you! 🙂

**Comment by walden4u** [comment]
It works fine. Thank you for your prompt action. :)
