### ISSUE TITLE
Does not complete check.

### ISSUE THREAD

**Issue by cleberorati** [FlutterFlow/flutterflow-issues#732]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open the project that I've been working on for over a year and that was working, the function verification indication appears and I click on the verification to be carried out, but it never ends. If I download the code I can compile normally in Android Studio.

https://user-images.githubusercontent.com/17750095/230360805-5337fd83-c535-43bd-a5f6-cc6d613d9158.mp4

### Expected Behavior

I expect the Flutterflow platform compiles and releases the project so it can run.

### Steps to Reproduce

1.Open the project
2.Click in Issues
3.Click to check error on custom functions or custom code
Follow attached video

https://user-images.githubusercontent.com/17750095/230361361-e0bd0c11-60b6-4d2e-b368-48bb684522a2.mp4

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4khcj6w5NJtbxD7arxbcZVgWU4Q2I7TLIFse0aRR4YIuPuPYl3fMnSU0NKTszjeFd+B1ejoHIz+OjnifGWOvEEYCirQIc60JVPWxWVeHOnR5iPDM+8enxPO5phfnK507eN2BB5NsFvLlIZwE2TNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I just can't run the app, I can't generate the apk, etc.!

### Visual documentation

https://user-images.githubusercontent.com/17750095/230363619-1f10d5d9-d961-4122-8453-82abed6a4414.mp4

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Any Browser but if you want one you can use Chrome 111.0.5563.148
- Operating system and version affected: Windows 10 Pro 22H2
```

**Comment by hariprasadms** [comment]
Hi @cleberorati  - Thanks for reporting this bug. Can you please update the issue with bug report code?. Without bug report code code we can investigate the issue.

**Comment by cleberorati** [comment]
> 

I´m sorry, how can I do this? Please let me know the step by step because I can't find where to generate this report.

**Comment by hariprasadms** [comment]
Go to widget tree and right click you can see the option. Copy the code and past it into issue details.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/17435678/230382644-8131ccc1-9385-4f34-bf3d-8b7e2bd4fb97.png">

**Comment by cleberorati** [comment]
> Go to widget tree and right click you can see the option. Copy the code and past it into issue details.
> 
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/17435678/230382644-8131ccc1-9385-4f34-bf3d-8b7e2bd4fb97.png">

Ok, follow the bug report below but s I said before if I download the code and compile it in Android Studio it doesn't give any issue, so there is no issue report, I just get stuck in checking errors.
Bug Report: IT4khcj6w5NJtbxD7arxbcZVgWU4Q2I7TLIFse0aRR4YIuPuPYl3fMnSU0NKTszjeFd+B1ejoHIz+OjnifGWOvEEYCirQIc60JVPWxWVeHOnR5iPDM+8enxPO5phfnK507eN2BB5NsFvLlIZwE2TNq3qNleeY8aSfxBlZ7vfcPo=

**Comment by cleberorati** [comment]
Okay, I've already filed the bug report on GitHub.


Em qui., 6 de abr. de 2023 às 09:47, Hari ***@***.***>
escreveu:

**Comment by cleberorati** [comment]
> Hi @cleberorati - Thanks for reporting this bug. Can you please update the issue with bug report code?. Without bug report code code we can investigate the issue.

The bug report has been provided, could you please check it?

**Comment by cleberorati** [comment]
I would like to know why you are not paying attention to this problem, for
my part I informed everything that was requested.

Em sáb., 15 de abr. de 2023 às 22:56, github-actions[bot] <
***@***.***> escreveu:

**Comment by cleberorati** [comment]
So?

**Comment by cleberorati** [comment]
very sad this indifference


Em dom, 14 de mai de 2023 22:55, github-actions[bot] <
***@***.***> escreveu:

**Comment by cleberorati** [comment]
I never got a solution from you, only promises.

Em seg., 3 de jul. de 2023 às 09:40, Hari ***@***.***>
escreveu:
