### ISSUE TITLE
Bug : iOS Numpad issue with decimals

### ISSUE THREAD

**Issue by williambastard** [FlutterFlow/flutterflow-issues#733]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently there is a problem, in flutterflow, in the TextField widget, we have the option to be able to select the field type.

Among these types, two are of interest to us: Number and Number With signs and decimal.

The problem is that iOS does not support my `TextField.numberWithOption(signed:true, decimal:true)` method, this method thus configured launches the alphanumeric keyboard instead of the numeric keyboard with the signs, the point and the comma.

### Expected Behavior

By creating an option with the following configuration: `textField.numberWithOption(signed:false, decimal:true)`
We could take advantage of the numeric keypad as well as unsigned decimals on iOS and Android.

### Steps to Reproduce

1 - Add the TextField widget
2 - Set it to Number decimal + signs ( Number +/- and decimal)
3 - Realize that the numeric keyboard is not displayed, it is the alphanumeric keyboard that is displayed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4gi/Lq25dPm8hE7c7ybe9VoycWHDN8R4c0sdlud0wdCoDuBIk+ZPXsXxNvXc+6S1ZhPkSmmkYz0dbVi+HLKfJdYBCbbJRC+YdQSAH/XmKna5OBPKiBdnNRGf5MG1SH55jZ2hNNNs1aLWwa22aYHd+XYD3ANITGImdISq/LZO4=

### Context

Impossible for us to correctly manage the numeric field if this option and this problem is not corrected quickly, I had spoken to Barry about it, but obviously, the information did not come back.

This is a simple mini fix to implement.

### Visual documentation

<img width="350" alt="Capture d’écran 2023-04-06 à 17 25 49" src="https://user-images.githubusercontent.com/65223866/230431247-1f4ff504-971c-418c-bf74-869d5284a884.png">

**With method set like this: `textField.numberWithOption(signed:true, decimal:true)`** (with issue)
<img width="327" alt="Capture d’écran 2023-04-06 à 17 49 46" src="https://user-images.githubusercontent.com/65223866/230431542-c228f37c-e933-4016-bd43-bf8a57cf7af7.png">

**With method set like this: `textField.numberWithOption(signed:false, decimal:true)`** ( without bug)
<img width="927" alt="Capture d’écran 2023-04-06 à 17 52 18" src="https://user-images.githubusercontent.com/65223866/230432120-36df57c9-e8af-4f9b-aff4-ee003f1b4c87.png">

### Environment

```markdown
- FlutterFlow version: V3.1 - Flutter 3.7.3
- Platform: iOS
- Browser name and version: N/A
- Operating system and version affected:  iOS
```

**Comment by williambastard** [comment]
Don't forget it :D

**Comment by williambastard** [comment]
Update ?

**Comment by hariprasadms** [comment]
Hi @williambastard, Thanks for submitting this post. Sorry for being late to consider the issue for investigation. Now, I can confirm that the issue I can reproduce. Dev team will update the status of fix. Thanks

**Comment by williambastard** [comment]
Hello @hariprasadms , do you know how many time to resolve ?

**Comment by agreaves** [comment]
Hi! Thank you for the bug report! And sorry for the confusion. As it turns out, the "Signed" option is simply not available on iOS, and it defaults to the normal keyboard when this is specified. We've added an option for "Number (with decimal)", if this happens to suit your needs, which will be available on our next update. But unfortunately if you do need +/- options your users will need to use the regular iOS keyboard.

Thanks again for the report!
