### ISSUE TITLE
Form Widget with a backend Query call, not displaying

### ISSUE THREAD

**Issue by ultimatea8** [FlutterFlow/flutterflow-issues#74]
When I run the app, the Form widget that loads the users credentials and allows the user to update their about me, and phone number. Is not displaying when i run the application.

Also, the Create Account button, with a backend Query call, is not displaying when I have users sign-up

**This is how it should look**
![image](https://user-images.githubusercontent.com/15474079/199082977-8273af24-9a84-4010-95d9-c3cb2882c900.png)

**This is what shows when i run it.**
![image](https://user-images.githubusercontent.com/15474079/199087552-bc868fcc-5f5e-4792-ae16-f056c5d58594.png)

**Comment by bulgariamitko** [comment]
Please look at the temple and complete it in order to review this issue.

**Comment by ultimatea8** [comment]
ok

**Comment by ultimatea8** [comment]
I found the issue. It was user error.
"Hide widget if no match"  was turned on. I don't remember doing that.
Sorry for any time wasted. Please forgive me.
