### ISSUE TITLE
Subcollections not saving to firestore

### ISSUE THREAD

**Issue by mlbdev** [FlutterFlow/flutterflow-issues#740]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have deployed sub collections for the purpose of storing a locations reviews. I discovered that although I have updated the subcollection rules in FlutterFlow to ensure that Authenticated users could Create, Read and Write these rules were not being sent to the firestore rules for this particular project.

Once I had updated the rules manually in the firestore the functions worked as expected. 

### Expected Behavior

When saving the Firestore rules in FlutterFlow for subcollections I expected this to update the firestore rules to allow the the subcollections to be created, edited. 

### Steps to Reproduce

1. Create a project with a collection and sub-collection.
2. Update the firestore rules for the collection and subcollection to all be authenticated user. 
3. Using a button try to create a collection in the firestore subcollection.
4. The collection wont save as the write rules are not saved in the firestore. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

No bug report code

### Context

It was preventing from being able to use sub-collections all together. 

### Visual documentation

None

### Environment

```markdown
- FlutterFlow version: 3.1 (Flutter 3.7.3)
- Platform: MacOS Desktop
- Browser name and version: Chrome
- Operating system and version affected: macOS Monterey 12.4
```

**Comment by hariprasadms** [comment]
Hi @mlbdev - Thanks for reporting the issues. Good to see that you found a solution. However, I can't reproduce it in my test projects. Can you please try with a new collection/sub-connection and try to upload rules please. Share your project link or bug report code. With out these details we can't investigate your project.

**Comment by orchard800** [comment]
I'm having exactly the same issue.

**Comment by wenkaifan0720** [comment]
Hi @mlbdev. I just created a test project and the rules for the sub collections are successfully deployed. Is this issue still happening to you? There might be some glitches when deploying the rules. The manual fix is to copy the rules directly into your Firebase project.

**Comment by Dev-Muhammad-Junaid** [comment]
I just added a document in the sub-collection with one of my projects and neither Firestore nor Flutterflow CMS have any information about it.
Nothing gets created.

**Comment by BirgitPohl** [comment]
Can you check the firestore rules? @Dev-Muhammad-Junaid did anything change outside of Flutterflow?

**Comment by Dev-Muhammad-Junaid** [comment]
Yes. it works with setting up the rules again. Although the sub-collection was already created with rules deployed
 re-creating the sub-collection and deploying the rules again helped resolved it somehow.
Thanks
