### ISSUE TITLE
Still not all colors set by variable

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#745]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

recent changes much better in assisting in highend UI, but the Gradients cannot be set by variable:

![image](https://user-images.githubusercontent.com/122821259/230791527-f0e285c7-5b90-4398-aee9-188c25c1f876.png)

### Expected Behavior

be able to set by variable

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/122821259/230791542-be6b4a65-af7b-4492-9339-e2d7899b0c6b.png)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

na

### Context

cannot design UI totally as desired.  I am creating a timeline, widgets 1,2 and 3 colors are set by variables, i need to be able to set X as a gradient of 1 & 2, and Y as a gradient of 2 and 3, X an Y being containers.
![image](https://user-images.githubusercontent.com/122821259/230791878-78925d35-bd6e-413a-947f-329d4abccd9c.png)

### Visual documentation

see images above

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: 
- Browser name and version:
- Operating system and version affected:
```

**Comment by aemelyanovff** [comment]
Hi @OldFred2023. The issue tracker is only used for reporting bugs. To suggest new features please use our user feedback form.
