### ISSUE TITLE
All the widgets of this feedback form screen are not selectable

### ISSUE THREAD

**Issue by TanuJain2002** [FlutterFlow/flutterflow-issues#747]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the widgets including dropdowns , form and choicechips on this feedback form are not getting selected .

### Expected Behavior

these similar widgwets are working on other screens,but not on this

### Steps to Reproduce

When dropdown is selected as profile settings  ,it navigates to profile setting
When any of other choice chips are selected from profiles page
The other pages are not functioning as expected thier widget are not accepting any input

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT40i/Llx5dPm7RF+KqNb8dFmio5KUwnU4Ew09ZRaCosfZT2BLMcec/RVERDXcu4TW9temeajWoW09bQvd+WUew3Eyutf6o7ybgJVA/iID+nR4iVFJWvdkRDHd1RCn3E1qTQmBN/JrFvWE4m3HGmIdysTgXDNKb1NjJBD6/LZO4=RVERDXcu4TW9temeajWoW09bQvd+WUew3Eyutf6o7ybgJVA/iID+nR4iVFJWvdkRDHd1RCn3E1qTQmBN/JrFvWE4m3HGmIdysTgXDNKb1NjJBD6/LZO4=

### Context

few pages of my project are not accepting any response ,that are approached after clicking on choice chips,even the back icon button is not working

### Visual documentation

![back](https://user-images.githubusercontent.com/111673705/230831823-604afe54-af12-4300-a721-418807c7dc70.PNG)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: Windows
```

**Comment by organicnz** [comment]
Hi, @TanuJain2002. Thanks for adding this issue 🙂

Could you format your reproducible steps and add more visual content? Sorry, but at the moment it's not clear what exactly needs to be added and configured 🙂

**Comment by TanuJain2002** [comment]
Well , the choice chips were causing the screen to freeze I removed it and replaced content with button,Now everything works fine.
