### ISSUE TITLE
when I add new component at my home page whole screen hang and cant access back to the Home page

### ISSUE THREAD

**Issue by GillbertWong** [FlutterFlow/flutterflow-issues#748]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

its okay, just that there's a-lot features are not ready yet

### Expected Behavior

hope there will be more features added in such as share preference and etc...

### Steps to Reproduce

1. Create Home Page
2. Create new component 
3. Add new component at Home Page 

![Issue](https://user-images.githubusercontent.com/33408039/230833528-89628b87-29c1-4ec6-8b37-06e33080c22a.PNG)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITEWzMnqxIthxMtA+Zf6K+ZqigQsQ0wiU7hEkdVvGEggfa7oOpkMZM7+aXdbT+27TWw2eFmamkUJwtrMvob9U8deEE6aGL1607piFDvgeGSuR6quOpaWQ2t8P/FQI3bA14mnuyRRNbFZV3gd72GHcq3qNleeY8aSfxBlZ7vfcPo=

### Context

this issue causes my whole project cant continue. i cant even access the Home page to copy out the widgets that i have createdcan't

### Visual documentation

![Issue](https://user-images.githubusercontent.com/33408039/230834807-4ad9ae42-b919-49a9-8bf3-c282ce1d9640.PNG)

### Environment

```markdown
- FlutterFlow version:3.7.3
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
Do you have any parameters for your Components? Have you passed the right parameters?

**Comment by GillbertWong** [comment]
Hi Dimitar,

The component is taken from a template from Marketplace, it should not have
any parameters yet because once i put in my page it straight hang and
cannot access to the page anymore

[image: image.png]

**Comment by bulgariamitko** [comment]
Which component you are talking about can you place a link to it from the marketplace?

**Comment by GillbertWong** [comment]
This is the Marketplace URL
https://app.flutterflow.io/run/GDVHLOs1hGGZZzjvtRSJ
The component I took is 'webNav'

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @GillbertWong, and sorry for the slow turnaround.

The errors (_SideBar widget does not specify value for parameter ..._) are expected - the component has parameters, and you have to set them.

I can't reproduce "_this issue causes my whole project cant continue_". Could you add details to the steps to reproduce? Something like this:
* Open marketplace item https://app.flutterflow.io/marketplace/item/BEZ7J8tUizwAdXQcfD2G
* Click "Clone Project"
* Add blank
* Drag component abc
* Set parameter xyz to 123
* Observe error asd.

**Comment by aemelyanovff** [comment]
Closing as inactive. @GillbertWong please feel free to reopen the issue if you add the details.
