### ISSUE TITLE
Crash during access Template

### ISSUE THREAD

**Issue by arash-vaziri** [FlutterFlow/flutterflow-issues#749]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on Templates tab it shows the templates then after a second it everything freezes. It happens only when it shows the templates. looks an infinite loop.

### Expected Behavior

List available template like before

### Steps to Reproduce

1. create some templates (mine was 11)
2. Try to access template section to see the list.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITESj8nl5YpgouFD7qX5KuxAhQIgQ0QnU7gnlO1ucx4cIZTyB7AUYuPsX0NKTOm9fVdUE03++Ug13NbPk/HhL+4EKQyAfphE0JVAZzrKbES6bpTQO5CKSnBAP8VYfVCE1Jm4ngpSWbFfLFIN2Ey1Nq3qNleeY8aSfxBlZ7vfcPo=

### Context

Serious. I cannot continue working on my project.

### Visual documentation

https://drive.google.com/file/d/1MZ92VM0s6jLVGNufaEON9Yu08_ZeAS7m/view?usp=share_link

https://drive.google.com/file/d/1zLBiNYCez5h8XwfU_vjI9GrX5rcCBt1z/view?usp=share_link

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 112.0.5615.49 (Official Build) (64-bit)
- Operating system and version affected: MS. Windows 10 x64
```

**Comment by sinasalek** [comment]
Same issue here. It seems like an infinite issue. When I open templates few seconds later everything freezes

**Comment by hariprasadms** [comment]
Hi @sinasalek - I am not able to reproduce the issue. Can you re test and confirm its status please?. Make sure you have updated to latest FF updates.

**Comment by sinasalek** [comment]
Hi hariprasadms,
Yes it's resolved now thank you :)
