### ISSUE TITLE
Custom Domain Deploy Works, Local Build from Github Code Doesn't

### ISSUE THREAD

**Issue by DrewBregman** [FlutterFlow/flutterflow-issues#75]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I should be able to success compile and deploy to a custom domain on Flutterflow's app, and push my code to github from Flutterflow, pull that code, compile, and deploy it using firebase locally as I have been doing for the past months. Web and mobile.

## Current behavior (required)

Flutterflow's custom domain successfully deploys my code, pushing the same code to github, pulling that code, compilling that code, and deploying that code fails for both web and mobile which is a problem because I need to test my code with xcode.

## To Reproduce (required)

1. Push code in my project to github
2. Merge pull request accordingly
3. Pull code in terminal locally
4. flutter build web (or flutter build mobile) fails
5. Deploying the exact same code to a custom domain on Flutterflow's UI works perfectly fine.

## Context (required)

I need to be able to deploy to other domains and xcode. 

## Screenshots / recordings

<img width="900" alt="Screen Shot 2022-10-31 at 3 47 48 PM" src="https://user-images.githubusercontent.com/68543563/199097371-c58d4d7b-e796-4011-8e28-0b781ae9ee42.png">

But this doesn't happen when I run the code in test mode or deploy using Flutterflow's UI

## Your environment

* **Bug Report Code:**
* Newst Flutterflow version (october 31)
* Mac ARM

**Comment by bulgariamitko** [comment]
What do you have on the page post promo page or widget. Can you share an screenshot?

**Comment by DrewBregman** [comment]
@bulgariamitko I rm -rf `pwd` cloned the git repository and redeployed everything and now it's magically working? Idk, I'm confused.
