### ISSUE TITLE
Dynamic link does not work on ios when app is not installed!

### ISSUE THREAD

**Issue by Dentiphoto** [FlutterFlow/flutterflow-issues#750]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Other people have the problem too. Not only me.

**Dynamic links are configured correctly for IOS and Android!**

**I am creating a dynamic short link.**

Route settings /company/:id

1. Create a dynamic link
2. Share

The link is https://dubruapp.page.link/bVRb

**This works great, but only on Android. On the iPhone, an error .... Writes that the dynamic link is incorrect ...**

Help me please. What is the best way to make a link so that it works ...

**When using Android:**

1. If the application is not installed - The store with the application opens.
2. If the application is installed, then the page opens

**Everything is fine!**

On iPhone:
1. If the application is not installed - an error
2. If the application is installed - everything works ...

### Expected Behavior

When the application on IOS is not installed, the app store should be opened to install the application.

### Steps to Reproduce

Please be detailed as possible here so we can help diagnose the issue.
Issues cannot be accepted if they are too vague. For example, "project fails to build" would not be reproducible.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITEelM/lw4ZIpbxb0M/LYexV9AMwJ0QlUIInj+0bWRMhfLmrPLAEOvT4Q1VLYteGfG9leme0oFoJw874jvDPA/oBHxSsGqJx1K5XQQLgLVuQRK6LEKuOXER7M99Yf3aayJ7YgAkmPvJvLEYO1zite/CdG3qCf9qOYwx5e6fDbOY=

### Context

Context
How has this issue affected you? What are you trying to accomplish?

### Visual documentation

I will send you the settings
<img width="1728" alt="1" src="https://user-images.githubusercontent.com/125450278/231157353-36c1b458-6114-4100-bfe1-a81a4f5b711b.png">

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform ios
```

**Comment by Dentiphoto** [comment]
This problem is not only mine. Really need help. I can't use the app...

**Comment by bulgariamitko** [comment]
I think this is a Firebase issue and not FlutterFlow.

**Comment by Dentiphoto** [comment]
> 

Great. So you're saying that this is Firebase's mistake and FlutterFlow should not take part in this???

I don't agree with this. **FlutterFlow tells us how to set up links ONLY WITH HELP OF FIREBASE and it DOESN'T WORK.**

FlutterFlow should be calm about this bug. **Why do we pay money to FlutterFlow if their apps don't work.** I do everything according to THEIR INSTRUCTIONS!

**Comment by Dentiphoto** [comment]
> Your dynamic link has 5 warnings, which could be part of the problem @Dentiphoto See here: https://dubruapp.page.link/bVRb?d=1

Great. Thank you. BUT

An error that the link https://dubruapp.page.link/bVRb Param 'link' should not be on FDL domain.

But this link is generated in FlutterFlow. I don't do it manually.

Other errors refer to applications that are old removed.

**Comment by Dentiphoto** [comment]
> I think this is a Firebase issue and not FlutterFlow.

https://dubruapp.page.link/apple-app-site-association if i check it receive {"applinks":{"apps":[],"details":[{"appID":"S4HMZ6V889.com.dudru.appname","paths":["NOT /_/*","/*"]},{"appID":"S4HMZ6V889.com.dentiphoto.dubru","paths":["NOT /_/*","/*"]}]}}

These are two applications, but the second application is old and has never even been published.

**Comment by Dentiphoto** [comment]
I had remote applications in my project that are not active now and they have been removed. But now Fairbase refers to them. And also Apple. How can I remove them from the system completely?

**Comment by Dentiphoto** [comment]
> Your dynamic link has 5 warnings, which could be part of the problem @Dentiphoto See here: https://dubruapp.page.link/bVRb?d=1

I solved all the problems except one. Param 'link' should not be on FDL domain.

**Comment by MaggieThomann** [comment]
If you look at the "Your Dynamic Link" hyperlink in the [debug view](https://dubruapp.page.link/bVRb?d=1), it looks like it's including `?link=` when it [shouldn't be](https://stackoverflow.com/questions/48798857/are-these-firebase-deeplink-warnings-harmful-in-a-deployed-app):

```
https://dubruapp.page.link/?link=https://dubruapp.page.link/share/92933/LB4my29h5egIkIcNBwdU6Davuy13&apn=com.dudru.appname&ibi=com.dudru.appname&st=%D0%95%D0%B4%D0%B8%D0%BD%D0%BE%D0%B1%D0%BE%D1%80%D1%81%D1%82%D0%B2%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%B5%D0%BA+%D0%B8+%D1%80%D0%B0%D1%81%D1%82%D1%8F%D0%B6%D0%BA%D0%B0&sd=%D0%9F%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D1%82%D0%B5+%D1%83%D1%81%D0%BB%D1%83%D0%B3%D1%83+%D0%B2+%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8+DUB%26RU&si=https://firebasestorage.googleapis.com/v0/b/dub-ru.appspot.com/o/users%252FUGOCdw31sERrSBO3wo4zs6DKw1l2%252Fuploads%252F1680538535290000.jpg?alt%3Dmedia%26token%3Df0e62742-9b21-4de4-bf32-d5a5e02c7b47
```

@Dentiphoto

**Comment by Dentiphoto** [comment]
> If you look at the "Your Dynamic Link" hyperlink in the [debug view](https://dubruapp.page.link/bVRb?d=1), it looks like it's including `?link=` when it [shouldn't be](https://stackoverflow.com/questions/48798857/are-these-firebase-deeplink-warnings-harmful-in-a-deployed-app):
> 
> ```
> https://dubruapp.page.link/?link=https://dubruapp.page.link/share/92933/LB4my29h5egIkIcNBwdU6Davuy13&apn=com.dudru.appname&ibi=com.dudru.appname&st=%D0%95%D0%B4%D0%B8%D0%BD%D0%BE%D0%B1%D0%BE%D1%80%D1%81%D1%82%D0%B2%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%B5%D0%BA+%D0%B8+%D1%80%D0%B0%D1%81%D1%82%D1%8F%D0%B6%D0%BA%D0%B0&sd=%D0%9F%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D1%82%D0%B5+%D1%83%D1%81%D0%BB%D1%83%D0%B3%D1%83+%D0%B2+%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8+DUB%26RU&si=https://firebasestorage.googleapis.com/v0/b/dub-ru.appspot.com/o/users%252FUGOCdw31sERrSBO3wo4zs6DKw1l2%252Fuploads%252F1680538535290000.jpg?alt%3Dmedia%26token%3Df0e62742-9b21-4de4-bf32-d5a5e02c7b47
> ```
> 
> @Dentiphoto

Thank you. I don't understand how can I fix this? I have everything set up in the FlutterFlow project according to the Instructions. The link is generated automatically.

<img width="597" alt="Снимок экрана 2023-04-12 в 12 05 20" src="https://user-images.githubusercontent.com/125450278/231409363-17eef469-81b0-4728-8a3f-a0382818fa02.png">

**Comment by Dentiphoto** [comment]
> https://dubruapp.page.link/bVRb?d=1

@bulgariamitko https://kulturnomie.page.link/?st=kulturnomie.com&apn=com.kulturnomie.app&ibi=com.kulturnomie.app&link=https://kulturnomie.page.link/event?eventID=1 your link has same problem

**Comment by MaggieThomann** [comment]
How are you generating the dynamic link? Are you using the Generate Dynamic Link action in FlutterFlow? @Dentiphoto

**Comment by Dentiphoto** [comment]
> How are you generating the dynamic link? Are you using the Generate Dynamic Link action in FlutterFlow? @Dentiphoto

Yes.
1. Action Generate Page Link
2. Share

Everything works fine on android. Works on iOS when the app is installed.

Does not work when the application is NOT installed on the IOS.

<img width="384" alt="Снимок экрана 2023-04-12 в 18 14 49" src="https://user-images.githubusercontent.com/125450278/231503039-4d8e0e23-2f21-43c9-8e3f-5024c77b4757.png">

**Comment by Dentiphoto** [comment]
@MaggieThomann For some reason, when the application is not installed on IOS, it gets confused to open a link in the WEB.

https://dubruapp.page.link/share/92933/LB4my29h5egIkIcNBwdU6Davuy13

Whereas on Android everything is fine https://play.google.com/store/apps/details?id=com.dudru.appname&pcampaignid=fdl_long&url=https://dubruapp.page.link/share/92933/LB4my29h5egIkIcNBwdU6Davuy13

**Comment by MaggieThomann** [comment]
@Dentiphoto Oh I think I see the problem. You need to include the `isi` parameter as well since, according to the [Firebase docs](https://firebase.google.com/docs/dynamic-links/create-manually), that's what's necessary to redirect users to the App Store if it's not installed:
> Your app's App Store ID, used to send users to the App Store when the app isn't installed

So in your case, your dynamic link will work if it's like this:

https://dubruapp.page.link/?link=https://dubruapp.page.link/share/92933/LB4my29h5egIkIcNBwdU6Davuy13&apn=com.dudru.appname&ibi=com.dudru.appname&st=%D0%95%D0%B4%D0%B8%D0%BD%D0%BE%D0%B1%D0%BE%D1%80%D1%81%D1%82%D0%B2%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%B5%D0%BA+%D0%B8+%D1%80%D0%B0%D1%81%D1%82%D1%8F%D0%B6%D0%BA%D0%B0&sd=%D0%9F%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D1%82%D0%B5+%D1%83%D1%81%D0%BB%D1%83%D0%B3%D1%83+%D0%B2+%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8+DUB%26RU&si=https://firebasestorage.googleapis.com/v0/b/dub-ru.appspot.com/o/users%252FUGOCdw31sERrSBO3wo4zs6DKw1l2%252Fuploads%252F1680538535290000.jpg?alt%3Dmedia%26token%3Df0e62742-9b21-4de4-bf32-d5a5e02c7b47&isi=1663812696

Note that I added `isi=1663812696` at the end.

I've never had luck implementing dynamic links in FlutterFlow using the built in actions they supply because I don't think they give you much flexibility over additional parameters to pass like `isi`. I typically generate the link in a custom function, something that looks like:

```
String dynamicLinkExample(
  DocumentReference uniqueRef
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  const authority = “yourAppName.page.link";
  const path = "/";
  final params = {
    // Enable force refresh = false
    "efr": "0",
    "ibi": "com.appname.ios",
    "apn": "com.appname.ios",
    "isi": “whatever your app id is on the iOS App Store“,
    "ipbi": "com.appname.ios",
    "link":
        "https://appname.flutterflow.app/examplePage/${uniqueRef.id.toString()}",
    // Social Metadata
    "si": “some image URL here”,
    "st": “some message here”,
    "sd": “another “message here,
  };

  return Uri.https(authority, path, params).toString();

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

**Comment by Dentiphoto** [comment]
> @Dentiphoto Oh I think I see the problem. You need to include the `isi` parameter as well since, according to the [Firebase docs](https://firebase.google.com/docs/dynamic-links/create-manually), that's what's necessary to redirect users to the App Store if it's not installed:
> 
> > Your app's App Store ID, used to send users to the App Store when the app isn't installed
> 
> So in your case, your dynamic link will work if it's like this:
> 
> https://dubruapp.page.link/?link=https://dubruapp.page.link/share/92933/LB4my29h5egIkIcNBwdU6Davuy13&apn=com.dudru.appname&ibi=com.dudru.appname&st=%D0%95%D0%B4%D0%B8%D0%BD%D0%BE%D0%B1%D0%BE%D1%80%D1%81%D1%82%D0%B2%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%B5%D0%BA+%D0%B8+%D1%80%D0%B0%D1%81%D1%82%D1%8F%D0%B6%D0%BA%D0%B0&sd=%D0%9F%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D1%82%D0%B5+%D1%83%D1%81%D0%BB%D1%83%D0%B3%D1%83+%D0%B2+%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8+DUB%26RU&si=https://firebasestorage.googleapis.com/v0/b/dub-ru.appspot.com/o/users%252FUGOCdw31sERrSBO3wo4zs6DKw1l2%252Fuploads%252F1680538535290000.jpg?alt%3Dmedia%26token%3Df0e62742-9b21-4de4-bf32-d5a5e02c7b47&isi=1663812696
> 
> Note that I added `isi=1663812696` at the end.
> 
> I've never had luck implementing dynamic links in FlutterFlow using the built in actions they supply because I don't think they give you much flexibility over additional parameters to pass like `isi`. I typically generate the link in a custom function, something that looks like:
> 
> ```
> String dynamicLinkExample(
>   DocumentReference uniqueRef
> ) {
>   /// MODIFY CODE ONLY BELOW THIS LINE
> 
>   const authority = “yourAppName.page.link";
>   const path = "/";
>   final params = {
>     // Enable force refresh = false
>     "efr": "0",
>     "ibi": "com.appname.ios",
>     "apn": "com.appname.ios",
>     "isi": “whatever your app id is on the iOS App Store“,
>     "ipbi": "com.appname.ios",
>     "link":
>         "https://appname.flutterflow.app/examplePage/${uniqueRef.id.toString()}",
>     // Social Metadata
>     "si": “some image URL here”,
>     "st": “some message here”,
>     "sd": “another “message here,
>   };
> 
>   return Uri.https(authority, path, params).toString();
> 
>   /// MODIFY CODE ONLY ABOVE THIS LINE
> }
> ```

@MaggieThomann **Yes I have tried this.** But it no longer works as a dynamic link... After installing the app, the user opens the app on the home screen, not on the screen with the link.

And when the user has the application installed, it is also sent to the App Store and at the same time opens the application on the main screen.

I tried creating custom links, but they always open on the main screen of the app....

**I will try to do it again.**

**Comment by MaggieThomann** [comment]
I see. Once the app is installed and opened, if you click the deep link again, will it redirect correctly?

The 2 apps that I've done deep linking for function that way. Basically, if the app isn't installed, it'll redirect users to the App Store and then prompt them to install it, but it won't open to the deep linked page, it'll just open to the home screen.

If the app is already installed, then it does correctly open to the deep linked page (but sometimes it takes 2 tries to do it, for eg: if the app isn't already open in the background, I have to open it and then press the deep link and then it will work).

So I agree, I haven't gotten it to work either when the app is not installed (other than redirecting to the app store and opening the home screen), but I haven't looked into it much beyond that, because it always works when the user clicks the link again, after installing.

**Comment by Dentiphoto** [comment]
> I see. Once the app is installed and opened, if you click the deep link again, will it redirect correctly?
> 
> The 2 apps that I've done deep linking for function that way. Basically, if the app isn't installed, it'll redirect users to the App Store and then prompt them to install it, but it won't open to the deep linked page, it'll just open to the home screen.
> 
> If the app is already installed, then it does correctly open to the deep linked page (but sometimes it takes 2 tries to do it, for eg: if the app isn't already open in the background, I have to open it and then press the deep link and then it will work).
> 
> So I agree, I haven't gotten it to work either when the app is not installed (other than redirecting to the app store and opening the home screen), but I haven't looked into it much beyond that, because it always works when the user clicks the link again, after installing.

Yes, if the application is installed, the link will open correctly.

I wanted to use a short link as it is more beautiful for users. Thank you. I will test and do it manually with the addition of the ISI.

I also wrote to Apple and am waiting for a response from them

**Comment by bulgariamitko** [comment]
@Dentiphoto so we can conclude it is not a FF issue.

**Comment by Dentiphoto** [comment]
> @Dentiphoto so we can conclude it is not a FF issue.

@bulgariamitko Really? You are not right! Why Firebase generate dynamic link with isi parameter for ios???

Flutterflow generates link without isi parameter

**This is an error in generating a link to the FF page!!!**

**Comment by Dentiphoto** [comment]
@bulgariamitko **You could not solve the problem at the consultation and returned money. I opened an issue here! What right do you have to close it????**

**Comment by bulgariamitko** [comment]
> Several people in the FF community have also written to you, but you can't reply.

Which posts you are talking about? 

Alex the co-found of FF is assign to this issue as well if the decided that this is a FF issue then he can re-open this case. My job is to take decisions if the issues are FF related and to put statuses and close the issue if I think the issue is not FF related. 

**Please try to not be abusive and don't have abusive behavior! They are a lot of issues opened here and spamming issues and attacking people is not the right way if you ask me. I already warn you about this in our private conversations. If you continue like that I will report you in GitHub. Thank you for the understanding. And please be patient **

**Comment by Dentiphoto** [comment]
@agreaves Hi Alex! I ask you to check this. I have been trying to solve this problem for several weeks now. I have met many people who have the same problem.

**There is a bug when generating dynamic links in FF. I cannot use it.**

I think that the topic is closed incorrectly. **Check, please.**

**Comment by kicsijohn** [comment]
> Which posts you are talking about?

The question is not for me, but I saw those posts too

https://community.flutterflow.io/c/discuss-and-get-help/dynamic-link-not-working-in-ios
https://community.flutterflow.io/c/bugs/potential-bug-with-dynamic-links-ios-only
https://community.flutterflow.io/c/bugs/firebasedynamiclinkscustomdomains-in-info-plist-bug
https://community.flutterflow.io/c/discuss-and-get-help/dynamic-links-issue

**Comment by Dentiphoto** [comment]
> > Which posts you are talking about?
> 
> The question is not for me, but I saw those posts too
> 
> https://community.flutterflow.io/c/discuss-and-get-help/dynamic-link-not-working-in-ios https://community.flutterflow.io/c/bugs/potential-bug-with-dynamic-links-ios-only https://community.flutterflow.io/c/bugs/firebasedynamiclinkscustomdomains-in-info-plist-bug https://community.flutterflow.io/c/discuss-and-get-help/dynamic-links-issue

There are many more posts, but they don't want to solve this problem.... It's sad.

**Comment by Dentiphoto** [comment]
> Collaborator

I'll have to thank you every day for the fact that you closed the topic ... Thank you.
