### ISSUE TITLE
Listview error when the list has only one element

### ISSUE THREAD

**Issue by MyKit** [FlutterFlow/flutterflow-issues#752]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Open [Link](https://foodie-1bwwmt.flutterflow.app/menu?resId=19818803) to see the live demo.

When there is a single element in a list, the page breaks.

![image](https://user-images.githubusercontent.com/11173940/231260852-983d0e93-adc8-4ca1-8626-0b2f950a7ee8.png)

### Expected Behavior

The page should render the list view with a single element properly.

### Steps to Reproduce

Widget tree below
![image](https://user-images.githubusercontent.com/11173940/231261229-50ecf9e5-f4d6-48f4-8a39-b8ca37e16a42.png)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITFXksmAsJRNodhE+aryKscw/WAwGUwCaI0z0tlETRQdfuPtOqQEZ+OlRBJCcuqHSm52EE7+nl0d+OiNvfLlKfE7FE+ZbKJnwagIUxDgTjuWRYS1PM+gX38lL/FUCFyk1KurgBVSHNReV3wW1zqIP+m+b3qCf9qOYwx5e6fDbOY=

### Context

Trying to load a list and when there is multiple elements it works however when there is a single element it breaks.

### Visual documentation

![image](https://user-images.githubusercontent.com/11173940/231261735-d16c7f61-e33e-4136-910f-271a4970bf41.png)

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Web
- Browser name and version: Microsoft Edge - Version 112.0.1722.34 (Official build) (64-bit)
- Operating system and version affected: MS Windows 11 Version 21H2
```

**Comment by aemelyanovff** [comment]
Closing the issue as stale. @MyKit, please feel free to reopen the issue if you add details and explained in the comment above.

**Comment by DhaferBA** [comment]
The issue is still there, when a listview returns one entry, it crashes the app...
