### ISSUE TITLE
text validator error message not disappearing 

### ISSUE THREAD

**Issue by TanuJain2002** [FlutterFlow/flutterflow-issues#753]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have password textfield in the form and have set its text validator to username , after typing the password For eg "T@nuj233&$_23" the error message below it do not disappear.

### Expected Behavior

ALthough the form accepts the password entered in textfiled but I want the text error message to disappear once entered value meets desired criteria.
![password](https://user-images.githubusercontent.com/111673705/231420783-faf8ea27-5208-4871-b75d-bcc18848fe77.PNG)

### Steps to Reproduce

Create a page
Add a form
Add textfield
In the form add automatic validation to textfield and set text validator as Username

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITFfiPLqx4VIxLRJ7r6JYcIxhiEUKWkcTIMziNZ+exUbfaL1Bu0iZ8/RXxZpYO7maVNcelSYnl4Jpf+MvoftNPo4Bzurc7pqzs1MZgvOe2i6bqaoDJG0f3MnRZhPf0CZ36SJhSN5IvtuLXcj2mCQGOi/bHfDIuu/Zwh9f6PHaOI=

### Context

The form is not working as expected.

### Visual documentation

![password](https://user-images.githubusercontent.com/111673705/231421306-db390a02-6e95-42ef-96a9-7766ec30aead.PNG)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:Mobile
- Browser name and version:Chrome
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @TanuJain2002 - I have tested it in my project. The form validation is working as expected. There are special chars are used in your input which are not valid. **_T@nuj233&$_23_** remove @&$ ( use this is **_Tnuj233_23_**) and try, it should work as expected. Refer form validation message and update your input accordingly.
