### ISSUE TITLE
TabBar and Transform widgets Issue

### ISSUE THREAD

**Issue by chaseaustin42** [FlutterFlow/flutterflow-issues#755]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When TabBar is a child of the Transform widget, I lose the ability to switch between tab pages within the editor. When I select a different tab page, it properly switches tabs within the properties panel but doesn't switch views within the UI editor. 

I can however get it to switch views if I navigate to a different page and then back.

### Expected Behavior

I expect the UI editor to visually switch between the tab pages.

### Steps to Reproduce

1. Add Container
2. Add TabBar
3. Wrap Container in Transform Widget
4. Attempt to switch between tab pages without success

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT40z/LqyItPscte7q6JKflagmA5JVw8a7ss1+1RaCgvCJz3D7MAdvWlQFdDUt/jYWNDPkSmmnkF/87nuNnhA8IrAzSVfalz/qlQFw7jQlymQZOBCJaobUBCBtNQCB2g0bbQsQl5BMdZdCUD3GD3NfCXbBPvJJ/1IndISq/LZO4=

### Context

It makes it more difficult for me to edit different page tabs visually. 

### Visual documentation

https://user-images.githubusercontent.com/130612346/231600777-efaa2dc9-11e2-4b97-9c05-39ce81bdca08.mov

### Environment

```markdown
- FlutterFlow version: Flutterflow 3.1 Flutter 3.7.3
- Platform: Web
- Browser name and version: Chrome 112.0.5615.49 (Official Build) (arm64)
- Operating system and version affected: macOS Monterey 12.5.1
```

**Comment by wenkaifan0720** [comment]
Hi @chaseaustin42. This is indeed a known issue on our end. My advice is to not wrap the `TabBar` widget (and also other widgets that can have multiple children) within a `Transform` widget. Because the `Transform` widget only renders its child at a different location, but the user gestures are still detected at the original location, so it is really only suitable for transforming basic widgets. With that said, I would mark this issue as low priority.

**Comment by chaseaustin42** [comment]
Thanks for the response.

Is this an issue specifically with Flutterflow or with Flutter in general?
More specifically, if I set up the tab view exactly as I want it and then
wrap it with the transform widget, will the app still function correctly
once published or does flutter not handle this situation very well either?

**Comment by bulgariamitko** [comment]
@wenkaifan0720 Just you clarify when you said FlutterFlow did you ment Flutter?

**Comment by wenkaifan0720** [comment]
@bulgariamitko I meant FlutterFlow. The `Transform` widget needed some special treatment to be rendered correctly in our UI builder (but it will render correctly in your generated apps). 

The not functioning well part is more about the user experience. To me, it is confusing to show a button in a transformed box, while the interact-able area is in a different box, which could easily be happening when you wrap a multi child widget within a `Transform` widget.
