### ISSUE TITLE
Writing custom datatype w children to FB writes incorrectly if from CreateDoc action

### ISSUE THREAD

**Issue by Kainkainkain** [FlutterFlow/flutterflow-issues#757]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Ok so this took me a few days to work out. 
I have a custom data type structured like this: 

colorTheme<Map> 
  dark<Color>
  faint<Color>
  id<int>

When I create a Doc in FB, and in the next action, update that same doc, it's "status" feild. Sucess. 
But if I create a Doc in FB and in the next action update the colorTheme, FF writes this in FB:
colorTheme.dark = X
colorTheme.faint =X
colorTheme.id = X
instead of:
colorTheme 
   dark = X
   faint = X
   id = x
 
Now, you might think my datatype is wrong or some mistake, well check this out: 
if on another page, the Edit Page for the Doc, I make a button that runs the exact same action and set's the colorTheme for the Doc... it works. 

So the difference between the working actions and the failing actions is the action that came after a Create Doc in Firestore action.

   

### Expected Behavior

Create a doc, set a value - should write it correclty. 

### Steps to Reproduce

1. Create a data type with a few children.
2. Set Collection to use this data type. 
3. create a page that is passed the docRef from that collection
4. create a custom action that simply returns the data type with all values, using StructBuilder hack and No Compile. Where the data comes from doesn't matter - so if theres an easier way to create and pass the variable - go for it.  
5. on the page, create an action which sets the data type from the action output. (this is the one that writes to FB correctly.). 
6. on some other page, make a button that runs the custom action but then creates a new Doc with the action output (the new data type) to update the Doc's. 
7. press this button and go check the new record in FB - it will have the field name with dot notation. (the mistake)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT5fk8n135VIvsdA7c/UccFsgSQsKUg4RYJMiuxDaA80JZfqB7M+d/elRFFJbbyRSmNceWH8/W01+anIktr+V8c4AByJY75jybtqdRXKYH+haL7UOpCoeUdfP9xMGmq8zpuZnwlSVLFfLHAt2zuHf+eUb3LUNufRPEg/Psj8Jtn4o2iGAQ7WGn0Jg1ZSfCvr

### Context

I will have to trigger a Google Cloud Function to do all on-create tasks involving datatypes with children,  which will slow down new Doc creation, which will make my app appear sluggish. 

### Visual documentation

![Screen Shot 2023-04-13 at 3 39 19 pm](https://user-images.githubusercontent.com/14058742/231665564-028196ad-a94d-42ab-923f-caf91a1b9674.png)

### Additional Info

I think the issue would be in some function about create document and the way it handles data types with children. 

### Environment

```markdown
- FlutterFlow version: v3.1 flutter 3.7.3
- Platform: Web
- Browser name and version: Brave
- Operating system and version affected:  OSX
```

**Comment by agreaves** [comment]
Hi @Kainkainkain, thanks for the bug report! Apologies for taking so long to get an update to you. This was actually recently fixed! 🙂

Please let me know if the issue persists for you and I can re-open and try reproduce / fix!
