### ISSUE TITLE
Unable to find firebase storage setting 

### ISSUE THREAD

**Issue by chethan9** [FlutterFlow/flutterflow-issues#758]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to find firebase storage setting when i create new blank app. so for found no solution only work around was selected some marketplace app which has storage already enabled then cloning. This is ridiculous why not keep storage enabled by default at least setting.

### Expected Behavior

Should show atleast in firebase setting to enable and disable storage

### Steps to Reproduce

Create a new project
Select bank template 
Setup Firebase 
No Storage enabled in setting

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4kiMjfsI52ocMA+KXfbe0w9SgsQm4nTL07ttYbZxUjIuPtBJh+dcz7cVhDXsfjYHlhHGGb8U8zwa2Mk/PpOPYqByyuR7Vz1agIEjyVRXq8RYyLBpaKeWh7EfFMfW6c152zvBV7IbFaSUI4wV6IBuuRdBTBJ5u/Zwh9f6PHaOI=

### Context

Its tedious to every time start project from marketplace template lot of reworks.

### Visual documentation

![Screenshot 2023-04-14 113754](https://user-images.githubusercontent.com/17822209/231991561-a7bbbccb-91cc-4008-b1f8-00a4812f56d2.png)
![Screenshot 2023-04-14 113813](https://user-images.githubusercontent.com/17822209/231991571-637ef11a-e86b-476f-ac3d-e21d99e5f978.png)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform:All
- Browser name and version: Microsoft Edge 112.00
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @chethan9 - Firebase storage settings option is visible when upload images or media action is used in the project. It is as per design. Try to use the feature and let us know how it goes. However, this is not a issue.

**Comment by chethan9** [comment]
We tried its not available. ...
