### ISSUE TITLE
currentUserDocument Null check operator used on a null value

### ISSUE THREAD

**Issue by TomJFox** [FlutterFlow/flutterflow-issues#760]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When passing a DateTime value from Authenticated User to a custom function, the code generated by FlutterFlow looks like the following:
```
                                                  Text(
                                                    functions
                                                        .trialDaysLeft(
                                                            functions.daysBetween(
                                                                currentUserDocument!
                                                                    .createdDate,
                                                                getCurrentTimestamp),
                                                            60)
                                                        .toString(),
                                                    style: FlutterFlowTheme.of(
                                                            context)
                                                        .titleMedium
                                                        .override(
                                                          fontFamily: 'Inter',
                                                          color: FlutterFlowTheme
                                                                  .of(context)
                                                              .secondaryText,
                                                        ),
                                                  ),
```

![image](https://user-images.githubusercontent.com/106626912/232149986-9c9e8399-b6a8-447d-8cf9-5b554bb515c5.png)

This produces Crashlytics reports with the following error where dashboard_widget.dart points to the code snippet above:

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at _DashboardWidgetState.build.<fn>.<fn>(dashboard_widget.dart:1239)
       at AuthUserStreamWidget.build.<fn>(auth_util.dart:220)
       at StreamBuilder.build(async.dart:444)
       at _StreamBuilderBaseState.build(async.dart:124)
       at StatefulElement.build(framework.dart:5080)
       at ComponentElement.performRebuild(framework.dart:4968)
       at StatefulElement.performRebuild(framework.dart:5133)
       at Element.rebuild(framework.dart:4690)
       at BuildOwner.buildScope(framework.dart:2743)
       at WidgetsBinding.drawFrame(binding.dart:863)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:381)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1289)
       at SchedulerBinding.handleDrawFrame(binding.dart:1218)
       at SchedulerBinding._handleDrawFrame(binding.dart:1076)

The dashboard page is loaded following authentication in our app, so this is a Text displayed on the dashboard screen.

The custom code included is straight forward and doesn't include any Null check operators (code included in Additional Info section below).

### Expected Behavior

Null check performed prior to accessing this code at authentication so that no error is produced from the following
```
                                                                currentUserDocument!
                                                                    .createdDate,
 ```

### Steps to Reproduce

1. Firebase, Authentication, and Crashlytics enabled project
2. Add createdDate field DateTime in user record
3. At Signup, set createdDate to General Properties Current Time
4. Create dashboard page with Text widget as documented in issue above.
5. Build run on Android using APK download
6. signup new user
7. log off
8. login new user
9. Check crashlytics for error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITESjc/1uYVgouFC1pP1KO5qhR4jNlx7bZNEjO5EGAsYF5zwOpwpWvvDM2VoYemRTwhEPk6Zgkwy7taLiuHQG/oEGAyHbLZOzKgNTzuUWkimMrKsCKmCYEZBHdJQCkDH4J67uxJCKbBiZV1pig/GSw==

### Context

We are trying to display the number of days left in a trial period based on a createdDate field stored in firebase by comparing it to current system time.

### Visual documentation

![image](https://user-images.githubusercontent.com/106626912/232153626-c3384f76-64cf-4a5a-ba20-13d877b9fb7d.png)

### Additional Info

Below is the custom code used in the Text Field
```

int daysBetween(
  DateTime? from,
  DateTime? to,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  from ??= DateTime.now();
  to ??= DateTime.now();

  from = DateTime(from.year, from.month, from.day);
  to = DateTime(to.year, to.month, to.day);
  return (to.difference(from).inDays);

  /// MODIFY CODE ONLY ABOVE THIS LINE
}


int trialDaysLeft(
  int? daysBetween,
  int? trialLength,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // Add your function code here!
  return ((trialLength ?? 60) - (daysBetween ?? 0));

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

### Environment

```markdown
- FlutterFlow version: v3.1 (released April 13, 2023)
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.147 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by TomJFox** [comment]
This was marked as a bug, so is there a fix @hariprasadms ?

**Comment by TomJFox** [comment]
@agreaves What is the latest update for this issue?

**Comment by agreaves** [comment]
Hi @TomJFox, thanks for the bug report and apologies for the delay! We've fixed this on our end, which will be available on the next release.
