### ISSUE TITLE
Big bug with json parameter

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#761]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i define a json parameter for a component i can't set it as required !!
This means that the FF verification system does not see any errors but then the build fails !!
Serious FF bug

### Expected Behavior

The lack of this setting actually prevents you from being able to pass json variables to components

### Steps to Reproduce

1. ha a json coming from api call like this:
    "reasons": [
        {
            "id": 2,
            "name": "No reason"
        },
        {
            "id": 4,
            "name": "Extraordinary rest shift"
        },
        {
            "id": 6,
            "name": "Holiday"
        },
        {
            "id": 14,
            "name": "Seats not available"
        }
    ]
    
    Pass it as parameter where you have a dropdown and assign values to id %& labels to name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs8JJToPLAUZ8zBM05vZry6SkFpeWCZpGEyxvfqud/fEPYCYE2WGJxI+rVQeg/gZE6gMs2KPIe/fW1QFp9hf2Ky1p2zpSRBBOteR0Ihw2GIIvDLVhXaJpO3CzEnDfKlKdeK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to do something elementary, a dropdown that displays strings and sets an id to the user's choice

### Visual documentation

<img width="1272" alt="FF-3 1-booking-prj-no-errors" src="https://user-images.githubusercontent.com/1261851/232201026-727b3857-258d-40d3-86cc-e3648189dc4b.png">
<img width="825" alt="FF-3 1-booking-prj-build-fail" src="https://user-images.githubusercontent.com/1261851/232201032-80d49723-2e64-4473-b058-33a9f74f3147.png">

### Environment

```markdown
- FlutterFlow version: 3.1 April 7
- Platform: Web
- Browser name and version: Chrome 112.0.5615.49 
- Operating system and version affected: MacOS Ventura 13.3.1
```

**Comment by hariprasadms** [comment]
Hi @blondie63 - Can you add more details about the statement - `id %& labels `. Passing a dropdown parameter value for above json data structure is working as expected. Please add a quick video showing the issue please.

**Comment by blondie63** [comment]
Hi @hariprasadms In my project I got around the problem using only the options, I see in the day or tomorrow at the latest to create a test project to show the error, assuming that it still exists since in the meantime I have seen two FF updates which however always report the version 3.1 of 13 April

**Comment by Franco98404** [comment]
Hi @blondie63, I think this issue can be useful: https://github.com/FlutterFlow/flutterflow-issues/issues/394

**Comment by blondie63** [comment]
> #394

Hi Franco, so this confirm FF bug..

**Comment by agreaves** [comment]
Hi @blondie63, thanks for the bug report! I've been able to reproduce this issue, and it should be fixed on our next release! 🙂

Sorry for the delay in fixing, and thanks again for the heads up!
