### ISSUE TITLE
Backend Query on Scaffold: Loading Widget causes white flickering

### ISSUE THREAD

**Issue by HeikoKanzler** [FlutterFlow/flutterflow-issues#762]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a backend query on the scaffold, the loading widget causes screen flickering, as it uses a white background and doesn't reflect the set background color. 

Very anyoing on dark designs, see attached video recording.

### Expected Behavior

The loading indicator is shown on the configured background color and not white.

### Steps to Reproduce

1. Create a back end query on the scaffold and configure the loading widget
2. Set a darker background color
3. Switch between tabs, see the loading widget displaying on a white background 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4CkcjfsIVIm9tF1s7xbfowiioUJj85RY0/l+pubxEdJ5PMC+wIZ/f7XFRuTde0Twk/O1n9hmI0w83emvOSFPQnFyWVR4RCwc9AegnKcEm6R8m6EYeze25/DZtnI3a8152g2xFTOtZsdHBl3WWIP9/IbAvDHZz2OGs7H+SbA5CK2SrDX1iXc2URm05KZDPz

### Context

I want to load data once the page is loaded.

### Visual documentation

https://user-images.githubusercontent.com/5279575/232238174-985df8bd-9580-4228-bdc4-8f9ad9d8c9e8.mp4

### Environment

```markdown
- FlutterFlow version: v1.1.61
- Platform: MacOS Desktop
- Operating system and version affected: macOS Ventura 13.2 (22D49)
```

**Comment by hariprasadms** [comment]
Hi @HeikoKanzler - I think flickering feel is expected as delay between data load and displaying loading indicator is too less. I think adding loading placeholder widget using components or images like shimmer can change flickering feel. Try this option and see how it goes. If still showing flickering, we can investigate the issue. Please share a quick video. Thanks

**Comment by HeikoKanzler** [comment]
Hi @hariprasadms 

Thanks for looking into this. I was looking into different ways to mitigate this, including reusing a splash image or so. 

However, it's still a bug that the loading spinner does not reflect the configured background color. If the query runs longer, the pages stays white, while the NavBar, for example, uses the configured color.

A very dark theme, e.g. black background with a white spinner would simply not work.

Thanks,
Heiko

**Comment by danielmcline** [comment]
hi @HeikoKanzler, I had the same issue and agree it seems like a bug, but was able to mitigate by pushing the backend query call one step lower in the widget tree.

**Comment by HeikoKanzler** [comment]
Thanks, @dynnuf, hat's what I did in the end.

**Comment by nugmo** [comment]
Can this be resolved without moving the query down a level? I'm trying to fix this on my app and to move every query and remap each widget connection (1000's) would kill my soul.

**Comment by nugmo** [comment]
Also seems setting a component or image loading widget on the scaffold level query to try improve this doens't come up, only the standard project loading indicator will.

**Comment by agreaves** [comment]
Hi @HeikoKanzler, thank you for the bug report! Sorry for the delay on this one, but finally got to the bottom of this. It should be fixed on our next release! It will instead show the loading indicator on the page but use the same background color as you gave the page / Scaffold.

**Comment by mamadouramadan723** [comment]
Hi
I think you can just use query collection on Page Load and get the output

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72153331/d1b65f8b-0b20-4138-9ba5-319b5a6f43ea)
