### ISSUE TITLE
TextField can not access its own widget state

### ISSUE THREAD

**Issue by ksedix** [FlutterFlow/flutterflow-issues#763]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a TextField widget. I want to make the color of the text in the TextField widget to become green if the text in the TextField widget matches a certain string value. However, it is not possible to access the value of the text in the TextField widget, since the TextFieldWidget can not access its own widget state. If I create another TextField, the first TextField will be able to access the widget state of the second TextField, and the second TextField will be able to access the widget state of the first TextField. However, neither of the TextFields can access their own widget state.
![textfield_bug](https://user-images.githubusercontent.com/76788207/232235367-7b76f13c-841b-4373-ad45-5f177aa4218d.png)

### Expected Behavior

The TextField should be able to access its own widget state.

### Steps to Reproduce

1. Create a new page
2. Add 2 TextField widgets
3. In TextField 1, go to properties and click on **Set from variable** for any of the fields.
4. Click on Set from Widget State
5. You will notice that TextField1 can only get the widget state of TextField2

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4ohfLl5YxOxcRE1876dfpVvyQUNm17RpEvkMpBay0jF7KuDLMqY8/RVERtOMDmSnw7JWKGp2oW3Nr8v+L1G/kCNk2CUYRYybthEjyVID66aKqmFJWgXmsmP59hCFSG1MPQohFCH/tvLFYe3U+mBtnKVivvQ5+3CmskDq/LZO4=

### Context

I am trying to create a "missing word" game. If the user has entered the correct answer in the textfield, the text in that textfield will become green. If the user has entered the wrong answer in the textfield, the text in that textfield will become red. In order for this to be possible, the textfield has its text color set from a variable, which should be the widget state of its own TextField. However, it can not access the widget state of itself.

### Visual documentation

![image](https://user-images.githubusercontent.com/76788207/232237836-a97f3d7f-8457-4d1a-bfee-40865248a21b.png)

### Additional Info

TextField1 can only access the widget state of TextField2 and TextField3. It can not access its own widget state.
![image](https://user-images.githubusercontent.com/76788207/232237836-a97f3d7f-8457-4d1a-bfee-40865248a21b.png)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web Flutterflow
- Browser name and version: Chrome version 111.0.5563.149
- Operating system and version affected: Windows 11 Home Version 22H2
```

**Comment by hariprasadms** [comment]
Hi @ksedix - It is possible using app/page states along with widget state. See a sample below. However, as per flutter text field widget basic feature, updating text value color from text field  is not possible. This is not a issue.

https://user-images.githubusercontent.com/17435678/232346982-1ec089c8-d213-4ed7-9f02-60f6dc08b39e.mp4

**Comment by ksedix** [comment]
Hello, this is simply incorrect. Flutter allows a TextField to access its own widget state, using its own TextController. If you look at the code for when TextField1 uses the widget state of TextField2 to change its color, it looks like this:

`color: _model.textController2.text == 'hello world'
              ? FlutterFlowTheme.of(context).success
              : FlutterFlowTheme.of(context).error,
        ),`

In order for TextField1 to use its own widget state, you simply replace `_model.textController2.text` with `_model.textController1.text` so it becomes:

`color: _model.textController1.text == 'hello world'
              ? FlutterFlowTheme.of(context).success
              : FlutterFlowTheme.of(context).error,
        ),`
