### ISSUE TITLE
Set from Variable not working Progress Bar Text

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#765]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to set the text from variable for the Progress Bar

### Expected Behavior

It should display the correct text from the variable

### Steps to Reproduce

1. Create a new project
2. Add a progress bar
3. Set the progress bar text from a variable (any variable like app state, page state, etc.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4KiMjfsJFPm9tK14SJacFvniAsQ0x/a+Y0lu5+WRQ2C7GsG7YUXs77P0xvZ9OoTQtEIWCi8XwJp8rOkYfLF8EHPiiafpRhzrgJTRbLfz6VR66qDM+We3d9M/FXfU+HzbS7pB4lH7Z1dVoFwF6QJvKuaHfqNqbNOUcBJ/mKBKT/n2jiHCLKXn0Jg1ZSfCvr

### Context

I am unable to get the values presented from the API's

### Visual documentation

![SCR-20230416-pirk](https://user-images.githubusercontent.com/126883330/232310942-f1406819-9deb-4fc0-9299-966015aa645d.png)

### Additional Info

[Sample Project](https://app.flutterflow.io/project/progress-indicator-ile896)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.146 
- Operating system and version affected: MacOS Ventura 13.3
```

**Comment by bulgariamitko** [comment]
To be honest I had no idea that you can write text there and it seems not logical to me as there is no place to display this text so I will mark it as a bug for that reason.

**Comment by eujoseant** [comment]
I am facing the same error.

**Comment by nunezal** [comment]
I am also facing the same error. Please fix.

**Comment by agreaves** [comment]
Hi @SameerShahzad99 and all, thanks for reporting! Sorry for the delay, I've been able to reproduce this issue and it will be fixed in our upcoming release! 🙂
