### ISSUE TITLE
I get stuck in function check

### ISSUE THREAD

**Issue by cleberorati** [FlutterFlow/flutterflow-issues#766]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open the project that I've been working on for over a year and that was working, the function verification indication appears and I click on the verification to be carried out, but it never ends. If I download the code I can compile normally in Android Studio.

### Expected Behavior

I expect the Flutterflow platform compiles and releases the project so it can run.

### Steps to Reproduce

1.Open the project
2.Click in Issues
3.Click to check error on custom functions or custom code
Follow attached video

https://user-images.githubusercontent.com/17750095/232313995-20cee4a3-f94f-41b7-8978-6240e9c1ac61.mp4

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4khcj6w5NJtbxD7arxbcZVgWU4Q2I7TLIFse0aRR4YIbb2EYkfPvTBS0NKTu2KS29IJ2GWml00ptbqj4btNPAFPTCsGoBC0JVPWxWVeHOnR5iPDM+8enxPO5phfnK507eN2BB5NsFvLlIZwE2TNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I just can't run the app, I can't generate the apk, I get stuck in Custom Function checking

### Visual documentation

https://user-images.githubusercontent.com/17750095/232314109-8e77aee0-abe8-4c74-be14-bc70a0c7d944.mp4

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Any Browser but if you want one you can use Chrome 111.0.5563.148
- Operating system and version affected: Windows 10 Pro 22H2
```

**Comment by hariprasadms** [comment]
Hi @cleberorati - Thanks for reporting the issue. I can see there are some issues in custom code compile in you project ( Its project specific issue. In general custom code compile working fine). However downloaded code and compile and works fine. 

We will look into to the issue and let you know once it is fixed.

**Comment by cleberorati** [comment]
Ok, thank you. I´ll keep waiting.

Em dom., 16 de abr. de 2023 às 17:54, Hari ***@***.***>
escreveu:

**Comment by agreaves** [comment]
Hi @cleberorati, thanks for submitting the bug report. This is due to one or more of the custom functions being enormous (multiple thousands of lines). It's unfortunately breaking the custom code evaluator. At the moment, there isn't much we can do to fix the issue, so I'll have to close this for now.

I'd recommend making it a Custom Action if possible or importing it as a pubspec package instead.
