### ISSUE TITLE
chatDetails App Bar Bug

### ISSUE THREAD

**Issue by jimmiethekid** [FlutterFlow/flutterflow-issues#767]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the app bar there is a 3 line icon I can not edit or remove. It links to the end drawer. It is in the top right under the 3 DOT icon. I found this trying to add two icons to the top right of app bar. 

### Expected Behavior

I should be able to edit or remove this icon.

### Steps to Reproduce

1. use the chatDetails template to find the issue.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4skcn15YtOodtJ+Kr+bsBB/SM7HEw4Rp04scp/bxIgGIDzPOw+ZPWlQFNpUs+rT2xEJUSmmkEBpKHzv9nPJ8JdFwyeQYBdwpFqVgKXWlqme5OBPbiBe3xtM+BhIWmP1KWvkSJRANhec1ob706mCdnJfCnYJZz3ImdISq/LZO4=

### Context

stops me from building an app bar for this page.

### Visual documentation

![111111](https://user-images.githubusercontent.com/121631054/232323736-af5522f2-afe2-4d66-9801-17c11f8fa5f5.jpg)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @jimmiethekid - I just checked the issue in your project. The icon you are trying to change or remove is coming from end drawer widget. That is as per design. You can access the widget from scaffold page.

I have duplicated chat details page with the name - chatDetailsCopy_Test and changed from end drawer widget to open drawer widget. Now you should be able to attach this widget to an icon/button with icon of you choice. 

Try this. I hope this can help you. If you are expecting the same, you can close the issue.

**Comment by jimmiethekid** [comment]
I don’t see the copy_test file to see this.

**Comment by hariprasadms** [comment]
Hello, Looks like my changes are not saving in your project. Follow as below. 

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/17435678/232348085-640a2997-4b93-4630-aa41-55e0d149330c.png">

**Comment by jimmiethekid** [comment]
Thanks! That worked.  If I can bug ya for two things I am stuck on.


  1.  I am trying to create a button to open a chat on the userProfile_orig page.
  2.  I am trying to create a long press alert to delete the user from the MyFriends listview as well

Stuck on these things!

Bytheway – love the program! I will be subscribing when the trial ends. Lots to learn but confident I can challenge myself.

Cheers

**Comment by hariprasadms** [comment]
Hi @jimmiethekid - Thanks for confirming. Considering the issue context and it is working for you now, I can close the issue. 
Any features which are not working in FF, you can raise them as issues. For all other queries and help, you can reach FlutterFlow community portal to find solution. I hope that helps you. Thanks
