### ISSUE TITLE
Authenticated User Email Verified not reporting verified users

### ISSUE THREAD

**Issue by TomJFox** [FlutterFlow/flutterflow-issues#769]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This morning we are still seeing issues with users who have verified their email addresses unable to see widgets which are conditionally visible using Authenticated User Email Verified field.  This is an important part of our customer onboarding journey as we require customers to have verified email addresses.  Our customers are unable to progress unless this is fixed!

Our page displays some information for the customer which requests they verify their email.  A Column with conditional visibility of 'NOT email verified' allows the customer to press a button to reload the page once they have verified their email.  A separate Row with conditional visibility 'email verified' should then be displayed allowing the customer to continue to the next step; however, this morning it is not being displayed.

This may be related to #759 but we are seeing this on Web, Android and Apple versions of our app.

### Expected Behavior

After customer has verified their email, they should press the button conditionally displayed with NOT email verified and the page should reload.  When reloaded the page should display the button in the Row conditionally displayed with email verified.

### Steps to Reproduce

1. New Project with Firebase configured.
2. Login page created sends customer to Step0 page
3. Step0 page displays button conditionally visible with condition not email verified
4. Verify customer email using email from Firebase
5. Press the button which reloads the page 
6. Page should show Next button which is conditionally visible for email verified.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESjc/1uYVgouFC1pP1KO5qhR0gHDN8UeY80NYaexUaF7mqGbYUVcjSRE5pTOGjeX9EI1X8vGAe0fyKuITLDvEGPh6VQL5Rz5BiWDuXXkOlMs24EZCOdHJfP+5YfnLA35+nux5BNuh2eClpig/GSw==

### Context

We are trying to launch our app and this is a key step to make sure that customers have verified emails.  Customers are not able to progress through our onboarding journey as they get stuck at this early step in the process.

### Visual documentation

<img width="181" alt="image" src="https://user-images.githubusercontent.com/106626912/232408003-6dfb47d9-dd8c-4ef5-b940-bc5ad31a84f0.png">
<img width="148" alt="image" src="https://user-images.githubusercontent.com/106626912/232408198-00dd5c89-0000-4dd2-be64-80025e3feeed.png">
<img width="173" alt="image" src="https://user-images.githubusercontent.com/106626912/232408369-07a2fc6a-4a3e-4f3b-ac48-111941591651.png">
<img width="151" alt="image" src="https://user-images.githubusercontent.com/106626912/232408497-0550aad7-94bf-4d97-913b-c8d9d86c9cdc.png">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v3.1 released April 13, 2023
- Platform: Web, Android, iOS
- Browser name and version: Chrome Version 111.0.5563.147 (Official Build) (64-bit)
- Operating system and version affected: Windows 11, Android 13, iOS 15.7.3
```

**Comment by TomJFox** [comment]
@organicnz , @victoriahuang1 

Is there anything to update on this issue or do you need any more information to triage?

**Comment by TomJFox** [comment]
Can somebody from FlutterFlow please respond to this ticket? It has been 4 days now with no response.  
This item was working fine for months, but since this weekend has become an issue.

**Comment by TomJFox** [comment]
@agreaves has anyone been able to take a look at this?  You mentioned on #759 that this was unrelated, but seems very similar.  We have had to do a workaround to remove email verification.  Many others seem to be doing this in the community as it is not working.

**Comment by victoriahuang1** [comment]
Hi @TomJFox thanks for the report, I am looking into it and should have a fix out soon.

**Comment by Aequilibria-Health** [comment]
Hi @victoriahuang1 thanks for the response. I'm still in the same situation as @TomJFox . Waiting for a fix...

**Comment by victoriahuang1** [comment]
Hi all, the fix should come out with the next deploy!

**Comment by Aequilibria-Health** [comment]
Hi Victoria,

 

Good news! May I ask you when the next deploy will happen?

 

Many thanks

 

Vincenzo

 

Dr. Vincenzo Varriale, Ph.D.

Psychologist, Psychophysiologist, Co-founder at Aequilibria Health Ltd

Mob: +35677092570 (MT) +393332014304 (IT)

www.aequilibria.eu <http://www.aequilibria.eu/> 

linkedin <http://www.linkedin.com/in/vincenzo-varriale/>

**Comment by TomJFox** [comment]
@victoriahuang1 Thanks for the fix!  The latest version of FF arrived today, and this is working again.
