### ISSUE TITLE
Stack Wiget Does not allow interactivity with elements below on IOS and Android 

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#77]
I have a stack which looks like this

Google Maps (100% vw, vh)
Containter (100% vw, vh)
    -Text
    - Image

on web i am able to move the map that is undernearth (in the stack)
while on IOS and andriod im not able to
Is there an option to make lower levels of the stack be touchable / movable?

I found the answer, but dont know how to add it in flutterflow:
https://stackoverflow.com/questions/50600747/flutter-ignore-touch-events-on-a-widget

**Comment by Pepino-GR** [comment]
Hello Josefpa,
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by Josefpa** [comment]
In Flutterflow Create a Stack Component with 
Google Maps on Level 1
Contianer on Level 2

Level 1 Which is underneath is not touchable on IOS and Android while being on Web

Expected Behaviour, 
That the the map in the stack is movable

Example Images:
![image](https://user-images.githubusercontent.com/67612575/199599901-b8ef382e-d5c8-456a-b388-64487e5203cd.png)
![image](https://user-images.githubusercontent.com/67612575/199599952-b4c684bb-1ef2-4fe9-b8b1-1dc2ebc3df22.png)

**Comment by Pepino-GR** [comment]
Hello JosefPa, 

I can reproduce this issue. If I disable App Bar Behavior Collapsible ( Silver AppBar), it works as expected.

**Comment by agreaves** [comment]
Thanks for reproducing @Pepino-GR! That fix should work, I believe the issue is that the page is technically scrollable with the collapsible bar. @Josefpa, please confirm whether this fix works for you and I'll close this issue.

**Comment by Josefpa** [comment]
See I don't have a Collapsible Bar in my application, and non of the elements were scrollable. 

I fixed it by just having the elements space around so that the space that is stacked on top of something else is only the one that   is not movable. while the empty space is movable.
Green part is scrollable while the overlaying part is not
![image](https://user-images.githubusercontent.com/67612575/201494618-2366cf99-60ce-4bb7-a2b4-8df6c1fee9e9.png)
