### ISSUE TITLE
Drawer + ChoiceChips selected bug

### ISSUE THREAD

**Issue by MailBQ** [FlutterFlow/flutterflow-issues#771]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm doing a project using Drawer + ChoiceChips. I want to use ChoiceChips to filter my listview, it's work fine except this issue : If I click on a chip, if I close and go back the drawer, it should show the selected chip, however it's doesn't. 

### Expected Behavior

I'm doing a project using Drawer + ChoiceChips. I want to use ChoiceChips to filter my listview, it's work fine except this issue : If I click on a chip, if I close and go back the drawer, it should show the selected chip

### Steps to Reproduce

1. Create new project
2. Create blank page
4. Set an App State variable to save the choice chip selection
![image](https://user-images.githubusercontent.com/130987538/232474123-527cd7ae-019b-46e9-9625-2d7c536b2984.png)
6. Add ChoiceChips and TextWidget to page ; Add EndDrawer to page
7. Add Options into ChoiceChips
8. Set an Action for ChoiceChips, purpose is when I click on the chip -> it will save the value to App State variable
![image](https://user-images.githubusercontent.com/130987538/232474185-f1162bb9-8c6c-4694-af97-7166aea20b3c.png)
10. Set variable for TextWidget is App State variable -> to check the App State variable was updated from ChoiceChips select or not
11. Run test mode
12. Open Drawer, click on ChoiceChips, show selected chip, then TextWidget show the same value of selected chip
13. Close the EndDrawer, go back on, TextWidget is still show selected chip, however the ChoiceChips does not update

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfj+flsYtOsdtF14SJcsd4jjkXG18cT5Azje0bTRIjGpTxP4YEdfWldhduZ7CiS29iOkSmml8e/+zIiOzXLMA3Fz+qRohYzqoBYDvKfHqna5OBDbWKRmtCTMBMIX6Oy8KFnxMmNs9oSmAs2maqHtyiTgLYJJiyIlFISq/LZO4=

### Context

Selected chip was not update when close and reopen EndDrawer, hard for user to know what they are choosing

![image](https://user-images.githubusercontent.com/130987538/232474580-b7a99470-e0b0-4a9b-9625-f833469e869a.png)

![image](https://user-images.githubusercontent.com/130987538/232474641-b75f52fc-cb61-4692-a8de-9bbd05c7ee20.png)

### Visual documentation

I attached the short video to explain :

https://user-images.githubusercontent.com/130987538/232474725-eecd7457-5673-4383-a8a4-a250ca616c38.mp4

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web/Android/MacOS
- Browser name and version: Chrome/Edge/Firefox
- Operating system and version affected: Window 10
```

**Comment by hariprasadms** [comment]
HI @MailBQ - I can reproduce the issue now. Thanks for confirming

**Comment by jimnastic** [comment]
Hi @hariprasadms , I came across a very similar issue.
In my case, if a Choice Chip is not visible (conditional visibility set false) when the page loads it fails to load initial state from the app state variables and fails to set the app state variable when a chip is tapped.
You can read a detailed description here: https://community.flutterflow.io/c/discuss-and-get-help/choice-chip-widget-doesn-t-initialise-and-doesn-t-execute-actions-if-not-visible-when-page-loads#comment_wrapper_18154403

**Comment by MailBQ** [comment]
> HI @MailBQ - I can reproduce the issue now. Thanks for confirming

Hi @hariprasadms, any update from reproduce the issue ?

**Comment by wenkaifan0720** [comment]
Hi @MailBQ. Is this still happening to you? If so, I would suggest trying the custom dialog action to open a dialog that is made of a component as a workaround (I know this approach would work).

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This issue has been fixed and will be reflected in our next deploy.
