### ISSUE TITLE
Push notification not showing when the app open/in the foreground

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#772]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The push notification only works if the app is closed or in the background

### Expected Behavior

Show the notification is the app is opened

### Steps to Reproduce

1. implement push notification
2. open the app
3. send a push notification
4. observe that there is no notification

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jM/q4c5PmOZE7rr+KcJV+T45KWJ5a7gr0MFraDUsIuOtBuwPdfT4SFpCXcjhaVNcC02kmn0F+PSLhvDLUfZeC0iuG75mypZ9WzzOe2iWbL3WDLiKSH9PN+ZYfEy7y56vpxFSKvZYSl4hwV+uDdyAaHPDIuu/Zwh9f6PHaOI=

### Context

I want to show the notification if the user is using the app. If another user sends me an invite or adds me to its favorite list etc.

### Visual documentation

-

### Additional Info
There are already some demand in the community:
https://community.flutterflow.io/c/suggestions-and-feedback/in-app-notifications#comment_wrapper_14205953
https://community.flutterflow.io/c/discuss-and-get-help/no-notification-while-the-app-is-open-trigger-notification-work-in-lock-screen-and-off-app
https://community.flutterflow.io/c/suggestions-and-feedback/in-app-messaging

### Environment

```markdown
- FlutterFlow version: v1.1.61
- Platform: Mac
- Browser name and version: - 
- Operating system and version affected: MacOS Ventura 13.2.1 (22D68)
```

**Comment by hariprasadms** [comment]
Hi @kicsijohn - Hi, With the current status of push notification behaviour, foreground is not possible and it is working as per design. To show the notifications in apps foreground, it requires local_notification capability integrations. This feature is planned for future updates.

**Comment by williambastard** [comment]
Hello when the feature will be deployed ?

**Comment by dmk23** [comment]
@hariprasadms I see this is still not implemented?

When shall we have this, users not receiving notifications is a problem...

**Comment by GamxXamg** [comment]
Any idea if this is gonna be implemented soon ? It is a must have as users could miss notification while using app !

**Comment by lesimor** [comment]
I'd love to see this feature deployed as soon as possible!

**Comment by jimff** [comment]
Any news on this one?

**Comment by alih552** [comment]
@leighajarett sorry for the mention, but this feature is crucial. Especially when attempting to implement it, results on leaving FF because It's not feasible with custom actions/functions, so we need to dig deep to achieve it.

**Comment by bdonovan858** [comment]
Echoing all those above - this would be a very helpful feature addition, especially in messaging-heavy apps to help ensure users don’t miss important messages while navigating other pages. Would love to see FF prioritize this feature.
