### ISSUE TITLE
Dropdown widget search not working as expected (Option label search)

### ISSUE THREAD

**Issue by Ipsofacto99** [FlutterFlow/flutterflow-issues#774]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So i was testing the new search feature for the dropdown widget and i found out that

 **you cant search the option labels, just the option values**, 

what i did was defining the option values as the ids of a collection documents, and option labels as the display name field of those documentes. so when i search the name of my customers others would show up because those characters i entered in the search were matching the document id.

i consider this a bug because i expected that the search results would index the option labels not the values

### Expected Behavior

i expected that the search results would index the option labels not the option values

### Steps to Reproduce

1.- Add a dropdown widget
2.- Define the option values as the docuement reference. result of collection query  (List of documents)
3.- Define the option labels as a field name. result of  the same collection query  (List of documents)
4.- Enable search
5.- Test the search 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fl/H1uI9Om+FK0LXycflF9Sk5JlgjRY0/jtVuTRMbfJfqE+wqZOOkM1NJYsOXTVY3PlGJ8Tgy+KHFk/zpG/ldGxStaYNeyLgNbzvyIHOmSqqsCrqsR0F8M8dVJkC7yJjZmA9RALZvR1I+3WWHfNiRHyzaJbLKDjMdM+SICK75nE6RAR73FztVxmNecCfn

### Context

create a dropdown list of my client name that can be searchable, that returns the document id

### Visual documentation

https://user-images.githubusercontent.com/66653634/232588337-5af5f14f-c05c-4690-96f0-c1de7fa1e398.mp4

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by newradius** [comment]
Why close this? It's a bug, bacause a usere would search what he sees not some internal value like an ID. In my case most of my values are UUDIS with labels as text. 

17259789-6344-482d-854a-821309444bfa - Category 1
17259789-6344-482d-854a-821309444bfb - Category 2
17259789-6344-482d-854a-821309444bfc - Category 3

OR

ID:1 - Category 1
ID:2 - Category 2
ID:3 - Category 3

It's a very common case (if not the most common) and the user has no clue about my values, only about the labels.

**Comment by Franco98404** [comment]
I have the same problem. @wenkaifan0720 @bulgariamitko @agreaves can you check this?

**Comment by bulgariamitko** [comment]
@Franco98404 , I agree this could be an issue, but I made a video where I am using dropdowns and filtering the values by the value, so I am not sure if it is a setup mistake or FF issue. What back-end are you using and how did you setup your logic is it the most important part, if you can record a video

this is the video I am talking about
https://www.youtube.com/watch?v=x-kivZ7ChD8&t=1568s
