### ISSUE TITLE
Cannot create _tags (required for Algolia Search API) field name to Firestore Schema in editor, but it is possible in Firebase Console.

### ISSUE THREAD

**Issue by EJS00102** [FlutterFlow/flutterflow-issues#775]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try and add _tags as a field name in Firebase Schema, but the editor says it is not allowed, even though it is possible in Firebase Console and needed to implement Algolia Search Tags functionality.

### Expected Behavior

Expected that it allows be to add any field name starting with an underscore.

### Steps to Reproduce

1.  Go to Firestore in the left "Connect" menu
2. Try and add a field name to a schema starting with an underscore

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkcnLuI1Nod9b1oSJasJF9WM4Q30cTIMziNZ+exUbfaL1BqQIeuD4RFNWOcugaVNcPlSjgT4dpNLwj+zPDPQoAAqaUbVyz855FjrOe2iWMZjUBYeWQ3FBBZ1TGnLC4Ke7myUkLtdvV3AY6jm6AtyycDHDFOu/Zwh9f6PHaOI=

### Context

I am trying to filter by tags using the Algolia Search API, but due to not being able to add _tags to my schema, now I cannot use this functionality.

### Visual documentation

<img width="1115" alt="Screenshot 2023-04-18 at 05 33 50" src="https://user-images.githubusercontent.com/52255287/232665364-0071311e-475c-4bed-8a6b-6b23c8029af0.png">

### Additional Info

https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-tags/

### Environment

```markdown
- FlutterFlow version: Version 1.1.61 (1.1.61)
- Platform: MacOS
- Browser name and version: Safari Version 16.3 (18614.4.6.1.6)
- Operating system and version affected: macOS 13.2.1 (22D68)
```

**Comment by EJS00102** [comment]
Okay, but the issue is that the Algolia Seach API requires a _tag variable for **tagFilters**. Is there another workaround?

**Comment by bulgariamitko** [comment]
Oh, if it is Agnolia Search API based issue then I will remove the status wontfix and put bug and please update the title of the issue to include Algolia into it so we know this issue has to be fixed because of Algolia.

**Comment by EJS00102** [comment]
Thank you very much, I have updated the title.

**Comment by victoriahuang1** [comment]
Hi @EJS00102 , thanks for the report. Unfortunately allowing names to start with underscores in the Firestore schema is a non trivial change, since it could lead to other issues. As such, we do not yet support using this Algolia Search API.

I will put this in as a feature request though.
