### ISSUE TITLE
Custom action, empty error window

### ISSUE THREAD

**Issue by GARLICDOG** [FlutterFlow/flutterflow-issues#777]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating custom actions in a new brand new project with Supabase enabled, FF tells me the code has errors but gives me no indication as to what it is. Previously rollback fixed this issue in other projects, but now copying working code results in the same issue.

The custom action code I'm inserting is this:
![image](https://user-images.githubusercontent.com/23639311/232764132-0fc6e09b-b93b-4873-b07b-799efb0deed8.png)

### Expected Behavior

I would expect some indication as to what the problem is. I get this usually. Sometimes I get a list of errors for a custom action that will result in blank errors when copied over to other projects (same dependencies). So far this was a hit or miss issue, but now I'm getting it in new projects and it makes FF unusable currently.

### Steps to Reproduce

1. create new project
2. enable supabase & add url + anon key
3. create new custom action
4. copy test code
5. add dependency "supabase: ^1.6.1"
6. click refresh button above dependencies
7. save
8. compile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89grsBE7Zf1bexahiMWH1s1TLJEpu0bWUkbGO/4EO0feM6lYlNDTfKzaH5XeFf+vGIDw+zqi+PtGPUoBAeVQa49+JFuWxPPbFqRRbHWDauRe3dfHtJUCFC054mF2hN+B/psWmQX3F6ICty+QT6Cf9qOYwx5e6fDbOY=

### Context

This issue appeared about ~1 month ago in a working project after we didn't interact with it for a few weeks. No code was changed but when we started working on the project again, all of our custom actions (previously working ones too) were unusable and refused to compile with the same issue. This was fixed by rolling back the project to a previous version.

Now the issue comes up randomly in new projects and we can't keep rolling back every time. It's now present in brand new projects too where rollback won't help.

I'm not sure if it's related but the code analyzer frequently disconnects for us while editing custom actions.

### Visual documentation

![image](https://user-images.githubusercontent.com/23639311/232765163-cc3dbee5-cfb7-44a2-9497-228e3af51116.png)
![image](https://user-images.githubusercontent.com/23639311/232765204-09811c6e-0ac9-4478-9d0c-b064774c98ca.png)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 112.0.5615.86
- Operating system and version affected: Windows 10 Pro 19044.2846 (issue is present on Windows 11 too)
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It'll be fixed in the next update.

**Comment by amiel-danao** [comment]
Still occurring to me

**Comment by rvanderleyImagine** [comment]
This issue is still occurring for me too.

**Comment by dvacnt** [comment]
2 years later, the bug is always not resolved !
