### ISSUE TITLE
Issue with FlippableCard when there is a button on the back side

### ISSUE THREAD

**Issue by VictuPlus** [FlutterFlow/flutterflow-issues#778]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a web app and when I use the FlippableCard and the back side has a button. The front side shows the shadow of it. 
I used the same example done in the documentation page https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/layout-elements/flippablecard and made a test screen to show how does that look like 
I did not manage to remove this shadow from the front card 
Front card:
![image](https://user-images.githubusercontent.com/131176037/232804187-c8935026-55cd-48f9-82f7-03355e999fb3.png)

Back card
![image](https://user-images.githubusercontent.com/131176037/232804276-e3206a10-cf55-423b-adaa-5454271d3592.png)

### Expected Behavior

Show the front side of the card without any shadow. 

### Steps to Reproduce

1. follow the steps in the documentation to create a fippablecard example: https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/layout-elements/flippablecard
2. Add a button in the backside 
3. Deploy it on Web
4. Access the page and you will see directly in the front side of the card, the shadow of the button in the backside of the card

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXiMmBw891ofpE7of+Y/lajjgwGVAIa5IRlexuZxEbCIzaB4YMZPWkQFppXsvkSlZ+OESmmnMyp+j5iuDtOvkrGy+CbKpZ+JFQSg3JWkSWQZOBDM+gXXx6DZtMIUzC0J6wkxUkNtFqLFoFwziMfO6UVhfqNOPKIndISq/LZO4=

### Context

One of my pages has a call to action in the backside of the flippable card and now the front side has a shadow that disturb the user experience.

### Visual documentation

![image](https://user-images.githubusercontent.com/131176037/232805504-8e0b10f5-9a4f-4db3-85e4-f444cce48a56.png)
![image](https://user-images.githubusercontent.com/131176037/232805530-f7bf4898-b81e-4837-a6cc-0840ca8514a0.png)

### Environment

```markdown
- FlutterFlow version: v1.1.61
- Platform: Web
- Browser name and version: Chrome Version 112.0.5615.49 (Official Build) (x86_64)
- Operating system and version affected: MacOS ventura 13.1 (22C65)
```

**Comment by VictuPlus** [comment]
Any progress on this?

**Comment by VictuPlus** [comment]
@aemelyanovff Thank you Anton.
I have to reinforce the fact that it does happen in production. Since I deploy it as a web app, and only offer it via browser to my users. Can you please make sure this is taken in consideration when fixing the issue? In my case that is a production issue, does not happen only in test environment.

**Comment by aemelyanovff** [comment]
This appears to be an issue with [`flip_card`](https://pub.dev/packages/flip_card). I don't know how to fix it, so I [filed a bug report there](https://github.com/BrunoJurkovic/flip_card/issues/86).

I'm afraid there's nothing else we can do at this moment, so I'm closing this issue.
