### ISSUE TITLE
Dynamic Link Not Working on IOS

### ISSUE THREAD

**Issue by rossnelson111** [FlutterFlow/flutterflow-issues#779]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am creating a dynamic link so users can share the app, the link should take users to a specific page in the app if they have it downloaded or take them to the app store if they do not have the app. The link works perfectly on Android and on IOS if the user has the app installed, if they user does not have the app installed on IOS then the they get redirected to a page that states "Dynamic Link Not Found" instead of the App store.

### Expected Behavior

The dynamic link should direct the user to the app store if they do not have the app installed.

### Steps to Reproduce

Delete the IOS app from settings in Firebase.
Regenerate config files from FlutterFlow.
Add App store ID and Team ID to app in Firebase.
Create a dynamic link. 
Share to an IOS device without the app installed.

Alternatively, click this link:
https://circlesza.page.link/Zi7X

https://circlesza.page.link/?sd=Join%20my%20lift%20club%21&ibi=com.flutterflow.tester&st=Circles%20Lift%20Club&apn=com.flutterflow.tester&efr=0&link=https%3A%2F%2Fcirclesza.page.link%2FinvitePersonal%3Fuid%3D1rW6NI0ebSdiXCpd0bu0EPJwUbZ2

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz/Hqx892rsRE0If5bsBslmUwFjMMbY0v0u0bFB4aIZyrBIl2PsjCS0NKQt+YewpAOFagoGoe0fzWufLhJ/EEYDeefoRJ0JVPWxXwXmS5aZ/SPrqSPXBCM9FMfVPD0ravsRZANfhvWmwe2E2DNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I cannot move forward with my app as it has a reliance on users being able to share the app for growth.

### Visual documentation

![unnamed (3)](https://user-images.githubusercontent.com/103026082/232857950-ba8c3b7e-f8ee-4048-9a6e-150e2595a85f.png)

### Additional Info

Debugging so far:

The app in Firebase has both the app store ID and team ID, in the apple developer Identifier the app has been set up to allow associated domains.

From Firebase support:
We found that there were 2 IOS apps in Firebase and 2 OAuth IDs in the project's credentials page. Deleted both apps and OAuth IDs and regenerated configs from Flutterflow. After adding the App Store ID a second OAuth 2 ID was created, we deleted the first ID to make sure there was only one.
The deep link flowchart (https://firebase.google.com/docs/dynamic-links/debug#preview_page_flowchart) shown by adding ?d=1 parameter to the end of the link shows that the link logic is correct. However if the user is on IOS and does not have the app installed then they are given a link named "web link" instead of "app store".
Using the parameter https://%7Byour_dynamic_links_domain%7D/apple-app-site-association both the Apple team ID and bundle ID is shown correctly.
Other Firebase possible causes:

"_If clicking the link redirects you to an[ interstitial (app preview) page](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages), click 'Open' first before side-loading the app. The app will receive null value if the app is side-loaded without clicking 'Open' in the app preview page.

If accessing the dynamic link in devices with iOS13+ version, make sure that you implement the SceneDelegate class aside from the AppDelegate class. If you may not be aware of this, there’s[ changes with iOS13+](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/specifying_the_scenes_your_app_supports) where AppDelegate no longer handles Universal Links or associated data properly. Given that, SceneDelegate is now being used to handle certain lifecycle hooks in the app, which was split from the AppDelegate. For below iOS13+ versions, you may still use the AppDelegate class.

For Google-provided *.page.link domains, check the Capabilities tab of the app's Xcode project and make sure that the Associated Domains is enabled. In your Associated Domains list, make sure that applinks:{your_dynamic_links_domain} is added._"

They have also noticed that there is no 'isi' parameter in the link which should have the app store ID.

From FlutterFlow support:
Dynamic links had two URLs, the original Firebase URL and a new created URL. We deleted the original Firebase URL and now only have the custom URL.
Tested the link on a new device.

![Screenshot 2023-04-18 152901](https://user-images.githubusercontent.com/103026082/232861481-aea90ab9-a848-41d9-b5bc-e5bcdee3db7c.jpg)
![Screenshot 2023-04-18 152835](https://user-images.githubusercontent.com/103026082/232861485-c50b6707-07a8-40ed-921a-2e53d1014216.jpg)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome 
- Operating system and version affected: Windows
```

**Comment by agreaves** [comment]
Hi @rossnelson111, thank you for the bug report! We have also been looking into these redirect issues for Dynamic Links. It appears the culprit, as you noticed as well, is that we are not adding `isi=[APP_STORE_ID]` to the link. If everything is properly configured, adding this should work and direct users to the App Store if it's not installed.

We'll have this fixed in the upcoming release on Thursday! Sorry about the frustration you must have dealt with thus far.

**Comment by agreaves** [comment]
Hi @rossnelson111, this is deployed and fixed. It seems to be working in my test case, so I am closing this issue for now as fixed. However, please let me know if you continue to have any issues!

**Comment by yannwehrlin** [comment]
Hi @agreaves, thanks for the quick fix! In my case the link didn't redirect to the iOS app even if the user had the app installed, (working well on Android). Do I need to do something to apply the fix? Rebuild new links on the Firebase console? Or should it work without doing anything?

**Comment by agreaves** [comment]
Hi @yannwehrlin, this is usually because the link is somehow misconfigured. I'd make sure your iOS Firebase config is up to date, and the bundle (e.g. `com.example.app`) matches the one in your FlutterFlow project.

Existing dynamic links may not work properly, so I'd make sure to test with newly generated dynamic links (either directly from your app or from the Firebase console).

One other step you may need to take is to add the appropriate information here, and ensure that the Bundle ID, App Store ID, and Team ID are set correctly. Typically only the Bundle ID is necessary for it to direct to the app if it's already installed, but it's worth making sure those are set correctly.

![image](https://user-images.githubusercontent.com/7757399/234371778-c2f6c3f8-300c-43ac-88db-6b8441eb58be.png)

**Comment by yannwehrlin** [comment]
Hi @agreaves, thank you for your reply, I feel like those are set correctly, or at least I can't find any mistake I would have made there. I newly created a dynamic link but when I click on it on an ios device, it redirects to the store although the app is installed.
If I export the code to an IDE, should the apple-app-site-association file be generated and present in it? I can't find it.

However when I open the myapp.page.link/apple-app-site-association link, I get this:
{"applinks":{"apps":[],"details":[{"appID":"XXXXXXXX.com.example.app","paths":["NOT /_/*","/*"]}]}}, but where the XXXXXXXX is the teamID. 
Though I have set the appID in the App Store ID and the Team ID in the Team ID fields in Firebase.  Is there any misconfiguration there? Or is it supposed to be that way?
