### ISSUE TITLE
App submission to google play java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#780]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I submit my app to google play I get this error from the code downloaded from flutterflow

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com........MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.

### Expected Behavior

Able to submit my app to open testing

### Steps to Reproduce

1. download the code
2. configure everything for submission
3. submit it to google play
4. Get this error 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olfLluJZ1ofVY7c/QdcBv9CQWJVg2RLgZkspBazwbfe+uB4kqevfOTERWXe6oYFVMJ2aGhWoW0dbthd7pIPECIQusUaZkyqlUTDuXIX65bpSRFJWgeXBCI9pTGB2b1J6VrRBAHNRqLHwX71yMO++WdC/qNIC3Im1BD6/LZO4=

### Context

I'm trying to submit my app to open test in google play.
I can't share the app to get feedback about my app.

### Visual documentation

![image](https://user-images.githubusercontent.com/5303536/232879123-703f5c62-72f7-4b66-b016-5bfabc13d72f.png)

### Environment

```markdown
- FlutterFlow version: v3.7.11 
- Platform:android
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by aemelyanovff** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io.
