### ISSUE TITLE
On Marker Tap gives wrong variable type for tapped marker

### ISSUE THREAD

**Issue by thedav22** [FlutterFlow/flutterflow-issues#781]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to create a bottom sheet with information from a tapped marker on a google map. I have done this before and it worked fine, but something has changed. Now when you choose Marker Document from the list of variables, it is not a document at all. It comes up as a Conditional Value instead. See the image below.

![image](https://user-images.githubusercontent.com/85451405/232934820-66110db4-30ab-417a-a11d-28875cd2fd2b.png)

### Expected Behavior

The document is supposed to be available, but it's not. The name "Marker Document" is there, but it's not the actual document.

### Steps to Reproduce

1. Create new page
2. Add Google Map
3. Add document query that places markers on the map
4. Add action to map: On Marker Tap
5. Action should bring up a Bottom Sheet
6. Pass document parameter to Bottom Sheet.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeis7luI91pb0C+7rtK+1ViQMwGm45a+cZkdV8EBAaCePuEZYpd86lR1tCWOqHSgptM1n++XwK+MLJheLPN/FcAASrRaJ4/8xbUxDvQj6jVJikDqiwPHBSTMJQC2GB4KaCnglCItdaV0IN116YG/Kua3qCf9qOYwx5e6fDbOY=

### Context

See above

### Visual documentation

![image](https://user-images.githubusercontent.com/85451405/232935603-3e06eda1-b890-4f82-ad0f-efa792ca104c.png)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by bulgariamitko** [comment]
@thedav22 can you also show us your bottom sheet - component and the parameters you have there as well and how you set them up.

**Comment by thedav22** [comment]
Hi @bulgariamitko. This issue seems to have resolved itself. I believe there used to be an option for "Marker Document" when tapping on a map marker. That option is gone, but under "Marker Documents" (plural), I found an option to pick the document at the current index and that seems to work fine. This may have just been a change in the way FF organized the options.

**Comment by marc007** [comment]
I would like to re-open this as I am experiencing the exact same issue if the "Marker Documents" source for Google map is based on return value of a custom function (in my case List<Properties>), if I use a simple query collection result, the "Marker Document" option is available.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/229745/913fc2b5-9014-4326-aff5-531710c1aa6d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/229745/174aae72-8be8-41ac-bf0d-58224ad55c7a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/229745/6c2fdebe-e02c-4b29-a107-39c1c71eb9a6)

**Comment by marc007** [comment]
@thedav22 Sorry I forgot to mention your name first ;-)

**Comment by sabatage3** [comment]
@marc007 did you solve this?, i'm experiencing the same thing, why "On marker tap" action creates a conditional?
