### ISSUE TITLE
Text is moved up when added a clear field icon

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#782]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a clear field icon is added to a textField the user text is moved up

### Expected Behavior

The user text shouldn't be moved up

### Steps to Reproduce

1. Add a textField
2. Go to additional properties and enable the "Show Clear Field Icon"
3. Now you can see the problem as you can see in the video

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBay0jF7KuDLMqY8/RVERuTemgdFVYe2KJ+GoW0crSiISWL/c5Eyyqbqo51pNhWDzyXnqVR4yhFJWvPXNBO5pXf0ik4Z+OkxFTJsdhLlEu2jmtf+iXTgztO6bWNmwsDq/LZO4=

### Context

I want add the clear field icon

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODExNzkwOV8yMTI5NzE0Mw

https://schoolfy365.tinytake.com/msc/ODExNzQ0MV8yMTI5NjU1MQ

### Environment

```markdown
- FlutterFlow version: v3.1 (April 13)
- Platform: Web
- Browser name and version: Chrome 111.0.5563.149 
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @Franco98404. I don't know if you have solved this issue, but the fix should be to add a content padding to the text field. Flutter decides to add an invisible bounding box to the suffix icon to ensure it occupies enough space for user to touch (48px by 48px to be exact). So the original padding given to the text is not enough and will push the text slightly up.  

We can reduce the size of this bounding box, but it doesn't feel necessary to me as using an appropriate content padding can solve the issue.

**Comment by Franco98404** [comment]
Hi @wenkaifan0720, I tried to do that you told me but is complicated because the editor and the web publish looks different

https://schoolfy365.tinytake.com/msc/ODE2OTA4M18yMTM2NjU4Ng

As you can see in the video in the FF editor looks identical but in the test mode and web publish is very different. I think that could be related to these issues:
https://github.com/FlutterFlow/flutterflow-issues/issues/785
https://github.com/FlutterFlow/flutterflow-issues/issues/786

**Comment by wenkaifan0720** [comment]
Hi @Franco98404. I still think these are separate issues. For this issue, you just need to change the content padding in the text field settings. 


https://user-images.githubusercontent.com/112435854/235164255-a66c6cc7-127c-4d4d-95e0-024851739f94.mp4
