### ISSUE TITLE
Save as Theme Style widget is not working

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#783]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i save a widget as a theme style widget while i am in a project that has a theme style(from my team themes)  it will be there for that session of my development but if i exit the project of reload the browser it will erase all the saved theme style widgets

### Expected Behavior

i expect to have my theme widget styles saved when i finish so that they can be reused across all projects that are using the same theme style

### Steps to Reproduce

1. add a widget to a page
2. right click the widget and save the widget as a Theme Style widget
3. exit the project and reenter

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocdF0bXiY8ZQhR4jNlx7bZNF0sJ9Sk0dfar1BKYpWvf4YhdBXOnmS25DeWCgjnEf3NrLv4fXG8JfHAyHbNlbyZZqaRbJRkehWpS6C6iCX0B7O+hjfmKj06SZuRZ4WdNeS11pig/GSw==

### Context

i saved alot of theme style widgets and i am very excited to use this feature

### Visual documentation

https://user-images.githubusercontent.com/72816439/232958676-c2a664ed-6101-484d-b170-f61b8bdfe986.mov

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: macOs
- Browser name and version:chrome
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @joekman990  - Widget styling Inherits style from default widgets in your project. It can't be used outside of a project. When you renter to the same project, you should be able to see already saved widget styles. I suggest go through  documentations and FlutterFlow yout tube videos related to the features. 

It is working as expected.

**Comment by wenkaifan0720** [comment]
Hi @joekman990. This is indeed a UI issue for theme widgets. You are not supposed to create theme widgets in a project when that project already has a team design library. The theme widgets are now only coming from the design library and we should disable the creation process. 

As for the conditional visibility, that is indeed a bug. We will fix both issues in our next update. Thank you!

**Comment by joekman990** [comment]
@wenkaifan0720 Thanks I would suggest maybe as a future feature to have the ability to add theme style widgets to the design library from a project that is associated with that design library Or a  simple way to jump to the design theme library while in a project

**Comment by wenkaifan0720** [comment]
Hi @joekman990. That is definitely something we'll consider! Thanks for the suggestion. The issues in this ticket will be fixed in our next update.
