### ISSUE TITLE
Lottie Animation do a black flash when is loading on Web

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#784]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Lottie Animation do a black flash when is loading on Web, happens in the FF builder too

### Expected Behavior

Should be load with a transparent color or add an option like "show loading indicator" to enable / disable the loading icon

### Steps to Reproduce

1. Add a Lottie animation
2. Now do a web publish and see the problem

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMWXZJE0utuTRQoGO/uPIkAP8zBP1dUcMu9dwhUfE2KnnwX/MnGiYThLPZcIQyrc75F/qpAVxfybEeQRbaQPK63b2tBI/9mG2qG0Ku7iAokPtFpWHAGwzv7PvO8bCjdHZS0OjI/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I want add some Lottie Animation to give to the users a more friendly experience

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODEzNDA5Nl8yMTMyMDA0Nw

### Environment

```markdown
- FlutterFlow version: v3.1 (April 13)
- Platform: Web
- Browser name and version: Chrome 111.0.5563.149 
- Operating system and version affected: Windows 11
```

**Comment by organicnz** [comment]
Hi, @Franco98404. Thanks for adding this issue, mate 🙂

I can't reproduce this issue, could be fixed in the beta version though. Are you able to reproduce it on another OS by any chance? :)

Screen video:
https://www.loom.com/share/231b9178ea684a01abaf41f52ca52110

OS: macOS Ventura 13.1
Chrome: Version 112.0.5615.121 (Official Build) (x86_64)

**Comment by Franco98404** [comment]
> I can't reproduce this issue, could be fixed in the beta version though. Are you able to reproduce it on another OS by any chance? :)

I tried it on Windows 10 and 11 only and that's where it fails

Windows 11 Pro - 22H2 - 22621.1555
Windows 10 Pro - 21H2 - 19044.2846

**Comment by Franco98404** [comment]
The bug is with all the Lottie Animations, I uploaded 2 videos to prove this. For some reason in the video, some Lottie Animations looks like they load without problem, but in my browser the problem it has, I suppose is related to the framerate of the video because sometimes the black flash very fast, and other times very slow

https://schoolfy365.tinytake.com/msc/ODE1Mzc3Ml8yMTM0NjI0OA
https://schoolfy365.tinytake.com/msc/ODE1Mzc4MV8yMTM0NjI1Nw

Do you want the Lottie Animation anyway?

**Comment by bulgariamitko** [comment]
@Franco98404, yes if you can send the Lottie Animation files so I can test with them as I do not find nay problems with my own Lottie Files.

**Comment by bulgariamitko** [comment]
one of the image is from Test mode and the other is from Web mode. Both have colors. 

![whats-new2](https://user-images.githubusercontent.com/7221384/235212590-9dfa9f06-cd76-4c03-adbe-a81961d0be1d.png)
![Test-Mode-whats-new2](https://user-images.githubusercontent.com/7221384/235212594-8e3657e3-77bd-44bf-a19e-6a8108bae715.png)

**Comment by Franco98404** [comment]
Hi @bulgariamitko, this error is related to a black flash, I think you confused it with this one:

https://github.com/FlutterFlow/flutterflow-issues/issues/296

**Comment by bulgariamitko** [comment]
@Franco98404 , yes you are right, but I was not able to reproduce that issue as well. Can you try to create a new project in FF and test this there and see if you can recreate the issue?

**Comment by Franco98404** [comment]
Yes, I created a new project and I can recreate the issue

New Bug Report Code:
ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMWXZJE0utuTRQoGO/uPIkAP8zBP1dUOdTjS2xceEyZhT8X/MqMk+HyUfcBFxWqRoBhyodTEQHdfGaVbJ/WDK63b2tBI/9mG2qG0Ku7iAokPtFpWHAGwzv7PvO8bCjdHZS0OjI/IOaoXdeK2SrDX1iXc2URm05KZDPz

Project Link
https://app.flutterflow.io/project/testing-yt3h9s

Web page:
https://testing-yt3h9s.flutterflow.app/

**Comment by bulgariamitko** [comment]
Everything loads normal to be.

https://user-images.githubusercontent.com/7221384/236808113-1919d626-3f9c-4daf-b3c8-ecd3ddac1082.mp4

**Comment by Franco98404** [comment]
Is so strange, this is my pc:

https://schoolfy365.tinytake.com/msc/ODIwNzIxOV8yMTQyMDgxOA

But I was trying to replicate the error on other devices and I couldn't. Only suppose that it is related to some specific extension that causes the problem or something like that because in incognito mode works well now. If have the problem and I can replicate I will reopen the issue
