### ISSUE TITLE
Text in the FF editor is not showing correctly when the width is empty

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#785]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Text in the FF editor is show a padding when in the web is not shown

### Expected Behavior

As is shown in the FF editor should be shown in the web

### Steps to Reproduce

1. Add a button
2. Remove the width and see the problem

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMfWLsr0utuGA0hfKruB6QMOvfsUxFLYtTjSlY2eFX9hj4zwtmKiOPTUvAqZByaQYBy/r5XQRbxQl+QVLKSCqWCbWgmJ/hQCkCkyMPYmAlTJu1ocVZi2zmIGPCdG3qCf9qOYwx5e6fDbOY=

### Context

I want remove the width from a button

### Visual documentation

![image](https://user-images.githubusercontent.com/36147203/232962136-be7e00ef-367a-4544-a0ca-5f354a28379e.png)
![image](https://user-images.githubusercontent.com/36147203/232962221-f35d0b21-dc90-4d39-b467-440f5904648e.png)

As you can see in the FF editor show an internal padding but in the web is not shown, you can see the same problem in the "Long text sample" button

### Environment

```markdown
- FlutterFlow version: v3.1 (April 13)
- Platform: Web
- Browser name and version: Chrome 111.0.5563.149 
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @Franco98404. This will be fixed in our next update. Thank you for reporting.
