### ISSUE TITLE
Some widgets are not aligned on Android

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#786]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Some widgets are not aligned on Android

### Expected Behavior

The widgets should be shown as others platforms

### Steps to Reproduce

1. Create a structure like this
2. The icon has 20 left padding
3. The text has 24 left padding

![image](https://user-images.githubusercontent.com/36147203/232965844-8251bf76-1178-4f65-ad3a-8df39f980019.png)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMfWOdEket+EA0hfamqEYkMOvfSUE5LYtece0FmOFG0hkUFzPyJuPzPKvYBFxSsfJhG1L5XQRbxQl+QVLKSCqWCbWgmJ/hQCkCkyMPYmAlTJu1ocVZi2zmIGPCdG3qCf9qOYwx5e6fDbOY=

### Context

In this case as the checkbox doesn't have an option to disable the checkbox, I created one using an icon and a text

### Visual documentation

![image](https://user-images.githubusercontent.com/36147203/232964156-2a2029f7-beca-4bce-9a8f-783f6e95ca9b.png)
![image](https://user-images.githubusercontent.com/36147203/232964563-4191b638-57f8-44da-9a76-96d1428c6ae7.png)

### Additional Info

May can be related to this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/295

### Environment

```markdown
- FlutterFlow version: v3.1 (April 13)
- Platform: Web
- Browser name and version: Chrome 111.0.5563.149 
- Operating system and version affected: Windows 11
```

**Comment by bulgariamitko** [comment]
@Franco98404, is it possible to right click on the main Column and then copy the widgets and paste the code here so I can paste the same widgets in my project and test it?

**Comment by Franco98404** [comment]
> @Franco98404, is it possible to right click on the main Column and then copy the widgets and paste the code here so I can paste the same widgets in my project and test it?

Yes @bulgariamitko!, I will copy the widget code as well

Widget Copy:

Cg9Db2x1bW5fazg5YnlkNWUSZAoZQ2hlY2tib3hMaXN0VGlsZV8xcm5lM2V5ZRgfIimSAiMIABIJCgVUaXRsZUAGGgQKAEAFIAEyAhAFQgIQAVABYgIQB/oDADoYQ2hlY2tib3hMaXN0VGlsZUVkdUxldmVsYgAS1QEKDFJvd19iMHNxazh1cBJoCg1JY29uX3JhcnRhZGxlGAgiUzpDCjQI09ADEg1NYXRlcmlhbEljb25zIAAyHWNoZWNrX2JveF9vdXRsaW5lX2JsYW5rX3NoYXJwEQAAAAAAADhAIgIQCFoJCQAAAAAAADRA+gMAYgASPAoNVGV4dF9nYjZhaG14NRgCIicSFwoLSGVsbG8gV29ybGQoBEAHiAEBqAEAWgkJAAAAAAAAOED6AwBiABgDIhkaAFoSEQAAAAAAABhAIQAAAAAAABhA+gMAYgAYBCIFIgD6AwA=


Widget Code:

```dart
Column(
  mainAxisSize: MainAxisSize.max,
  children: [
    Theme(
      data: ThemeData(
        unselectedWidgetColor: FlutterFlowTheme.of(context).primaryText,
      ),
      child: CheckboxListTile(
        value: _model.checkboxListTileEduLevelValue ??= false,
        onChanged: (newValue) async {
          setState(() => _model.checkboxListTileEduLevelValue = newValue!);
        },
        title: Text(
          'Title',
          style: FlutterFlowTheme.of(context).bodyMedium,
        ),
        tileColor: FlutterFlowTheme.of(context).primaryBackground,
        activeColor: FlutterFlowTheme.of(context).primary,
        dense: true,
        controlAffinity: ListTileControlAffinity.leading,
      ),
    ),
    Padding(
      padding: EdgeInsetsDirectional.fromSTEB(0, 6, 0, 6),
      child: Row(
        mainAxisSize: MainAxisSize.max,
        children: [
          Padding(
            padding: EdgeInsetsDirectional.fromSTEB(20, 0, 0, 0),
            child: Icon(
              Icons.check_box_outline_blank_sharp,
              color: FlutterFlowTheme.of(context).secondaryText,
              size: 24,
            ),
          ),
          Padding(
            padding: EdgeInsetsDirectional.fromSTEB(24, 0, 0, 0),
            child: Text(
              'Hello World',
              style: FlutterFlowTheme.of(context).bodySmall.override(
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.normal,
                    decoration: TextDecoration.lineThrough,
                  ),
            ),
          ),
        ],
      ),
    ),
  ],
)
``` 

Hope you can find useful

**Comment by Franco98404** [comment]
Yes, of course!

Here is the link:
https://app.flutterflow.io/project/not-aligned-ap2alp

**Comment by bulgariamitko** [comment]
@Franco98404 thank you for doing that. I am not a Flutter expert, but I will blame the two different widgets that you are using. I know in theory it sounds like it should work and you should not get this issue, but you are. I will leave this as wont fix, but I will get the FF team confirm this as well or deny my me 🗡️

**Comment by agreaves** [comment]
Hi @Franco98404, thanks as always for the detailed bug report and reproducible steps! 😊

This one was actually a doozy! It comes down to the platform default `VisualDensity` and `MaterialTapTargetSize` within Checkboxes in Flutter. I've now added a toggle for whether to make it Dense vs Padded (or Platform Default, which existing `Checkbox`/`CheckboxListTile` widgets will be). This should be available next release! Thanks again!
