### ISSUE TITLE
Can't able to deploy app in play store

### ISSUE THREAD

**Issue by vickyone0** [FlutterFlow/flutterflow-issues#788]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to update ABB file of my APP in the google play store using the check build status it show some error like " Failed"

### Expected Behavior

Expected that it will give the updated ABB file

### Steps to Reproduce

1.go to Google play store in the mobile deployment
2.Add new service key to the exciting project that have service key already
3.Deploy the app with proper version number
4.after it show submitted click on check build status

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiPLq2492obgA+KX2aflFmSQRNlw7apE4lu1DZwAYfZSuG7l/S8+kfhNuXbC0d1ZYJ2f9gjkx06DemvzLU8JfIRWdfaZzyaV2eAnKZ3KjRpCMDLqCTm5/Ap9TfnaA36WNvBVRIs9udF4Y2lyyAe+AQnLaNYz6C0g3RMq1MZCK2SrDX1iXc2URm05KZDPz

### Context

If it stay like this then I can't deploy my app in play store. I will affect my project

### Visual documentation

![Screenshot (87)](https://user-images.githubusercontent.com/101127083/233083605-0fc4937f-4651-4fd8-b293-f1922da7a6aa.png)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 112.0.5615.121 
- Operating system and version affected: windows 11 pro 21H2
```

**Comment by organicnz** [comment]
Hey @vickyone0m :) 

Apologies for asking, but could you pls delete a duplicate issue and leave the actual one? :)

Thank you :)

**Comment by vickyone0** [comment]
Its solved . I take a duplicate of my project and change package name . now I can able to deploy. thankyou for your help brother
