### ISSUE TITLE
Strange behavior with Pageview image list within a listview since today

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#794]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list of posts and every post contains several images in a pageview. I use blurhash package in the pageview. If I open the app and the list loads it loads all the images on the first page, but if I start swiping I get a null value. But the pageview is not null, and it worked perfectly until now

### Expected Behavior

If I swipe the pageview in a list it loads all images

### Steps to Reproduce

- create a page
- add a listview and query for posts that contain an image list
- add a pageview widget and generate children from the images
- for the images add the blurhash custom widget and use images with a hash string
- observe the behavior when the app loads it loads the first images if you swipe the pageview it doesn't load more, or just randomly

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jM/q4c5PmOZE7rr+KcJV+T45KWJ5a7gr0MFraCosCJzwBIgcf/fOYkRtTfGgYEFmIGKZ8GoW0ezQuez1JsAEOTOWfpxD+ZdfWjvMTkSnbLq1FJWgeUZTHeJQCGqa5raZhxBQG7BiLyUB11zzN+yXEnLBJpDwIjMSD6/LZO4=

### Context

I want to load more images from a list of posts

### Visual documentation

https://user-images.githubusercontent.com/45784821/233460696-c261b9ed-6a18-454a-ad16-5cebce020a30.mp4

### Additional Info

The terminal says:
Another exception was thrown: An adapter was assigned twice.

And if I want to navigate to a different page:
Another exception was thrown: Tried to build dirty widget in the wrong build scope.

### Environment

```markdown
- FlutterFlow version: v1.1.62 Flutter 3.7.3
- Platform: Mac
- Browser name and version: - 
- Operating system and version affected: Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @kicsijohn - I am not able to reproduce the steps. Could you please setup a blank project with showing the issue and share the bug report code of the project? Thanks

**Comment by kicsijohn** [comment]
Hi @hariprasadms - Sorry, I recreated my project settings in a blank project and I was wrong. The blurhash image widget on a pageview works perfectly fine... 
However, I found the issue:
If I place another object to a pageview in a stack and add on click animation to it, then add an animate on click action to the stack, the bug appears.
![CleanShot 2023-04-21 at 15 22 22@2x](https://user-images.githubusercontent.com/45784821/233651270-ba880058-eb32-46fa-836e-4284b07bfe5a.jpg)

Here is a the bug report coded for the blank project:
IT4gls/l6otIsdtK0LruYO9WhiUXJW5/a5c0sNobbxAjIoDoPJkUac74YRFWON/gTX9bKEWJrEgE+sqMiOHhVvZcOQeYb6E7zbp2bDuUVly/aoSXPLmwRXdSO8dhCFyY0raW2x4lXddiSCUs32b2evKvYDXDQLH6Zwh9f6PHaOI=

and here is a video to show the behaviour:
https://user-images.githubusercontent.com/45784821/233651883-eded0b16-af32-4ff1-9281-d16a6a947cf5.mp4

**Comment by HeikoKanzler** [comment]
There's a related bug reported by me: the animations do not work with dynamic elements. Reproduceable with a blank project.
