### ISSUE TITLE
Passing boolean parameters to pages from push notifications does not work

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#795]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Push notification deep link handler does not support boolean parameters and ignores them when they are set as page parameters in the push notification payload.

### Expected Behavior

If a page has a boolean parameter, setting it from push notifications should propagate that parameter all the way to the page.

### Steps to Reproduce

1. Create a new page with that can take a boolean parameter. Eg let's name it `openWallet`
2. Add an element to the page that has conditional visibility based on that boolean parameter.
3. Set the default boolean parameter to false
4. Enable deep linking
5. Enable push notifications
6. Ensure the app not in the foreground on the test device.
7. Send a push notification with a parameter `openWallet`=true
8. On the device tap on the push notification banner

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcnfz5Fgod9c1rrUK/lahmU5JlN9RI0Nke57aCosfZT2BLMcec/RVERWXbXmSlV+IGH9gWoW3PDPv4XlGO04ITStG5x+z7luFjvwYz+tMpStFJWgZnQmBcZRBUiB37eN2RNDBONaLWct2zqDN+jLcCbANOPXIXoWDq/LZO4=

### Context

Although pages support boolean parameter data, deep linking from push notifications does not work correctly when we try to pass boolean page parameters via the push notification data. 

Deep linking from URLs is supported. The issue only happens when sending push notification.

### Visual documentation

See Additional Info

### Additional Info

Hypothesis from codebase perspective:

It is likely that the problem is in the getParameter() function in

`lib/backend/push_notifications/serialization_util.dart`
<img width="762" alt="image" src="https://user-images.githubusercontent.com/4561505/233471849-7ab7208b-9e3b-4e46-9661-45946af5034e.png">

Although push_notification_handler.dart contains invocation with booleans, eg:
```
getParameter<bool>(data, 'paramName'),
```

The getParameter itself has no handler for boolean case. Although it gets invoked with <boolean> form push_notifications_handler.dart, it ends up falling through to  line 149 and attempting to pass it to FirebaseFirestore.instance.doc(), which will throw an exception and hence getParameter will return null.

We also see that all values are forced to String before used in getParameter:
`lib/backend/push_notifications/push_notifications_handler.dart`
<img width="727" alt="image" src="https://user-images.githubusercontent.com/4561505/233473723-252031a4-54b3-4564-ad74-d46fd084d4c7.png">

### Environment

```markdown
- FlutterFlow version: latest
- Platform: all
- Browser name and version: Native FlutterFlow app
- Operating system and version affected: MacOS Ventura 13.1
```

**Comment by bulgariamitko** [comment]
@isegal cna you write your deeplink for reference and also a work-around about this issue will be if you receive it as String to convert it into a bool using a custom function as bool can't be pass in a url by default.

**Comment by bulgariamitko** [comment]
I will close this issue as I think this is more like a future request and there is no feedback from the user.
