### ISSUE TITLE
FlutterFlow Web Published App does "NOT" work on Companies Network

### ISSUE THREAD

**Issue by polenvinagre** [FlutterFlow/flutterflow-issues#796]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My Flutter Web App plublished on FlutterFlow domain does "NOT" work on Companies Network.
It only shows a blank screen when open form desktop browser.
Reason: My clients company network firewall rules block access to site: https://unpkg.com/browse/canvaskit-wasm@0.32.0/bin/
Therefore the canvaskit files are NOT downloaded.

### Expected Behavior

My Flutter Web app open properly on comapnies network, despite firewall rules blocking: https://unpkg.com/browse/canvaskit-wasm@0.32.0/bin/

### Steps to Reproduce

1. Publishes a Flutter Web app using FlutterFlow domain.
2. Access (desktop browser) the App from a company network with firewall rules blocikng: https://unpkg.com/browse/canvaskit-wasm@0.32.0/bin/

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not Aplicable

### Context

Hi!
I am not good at creating titles…

I recently changed my hosting to FlutterFlow.
But, I had to roll back to my old hosting due:
flutter build web --web-renderer canvaskit

This link has more details about the issue.
https://stackoverflow.com/questions/68049390/problem-run-flutter-web-app-in-our-company-network

Most of my clients are business users.
Each company has IT policies, firewalls rules…
And none of them allow access to: 
https://unpkg.com/browse/canvaskit-wasm@0.32.0/bin/

So the result is:
A- When a user accesses the app from an outside network the app opens properly.
B- When the user accesses the app from INSIDE company network the app does NOT open. It shows a blank screen.

Possible solutions:
1- Ask each company's IT department to put the canvaskit site on white list.
This is not a scalable option. It is not easy to talk to every IT department and some of them may not or would not like to change their firewall rules.

2- FlutterFlow allows us to choose what web render to use.
Good option.
https://community.flutterflow.io/c/suggestions-and-feedback/feature-request-option-web-engine

3- FlutterFlow Web app does not download canvaskit from external sites. But, use local files or asset files.

Workaround: 
Use another hosting service. I am using Firebase at the moment.
Download code
flutter build web --web-renderer html

### Visual documentation

![WhatsApp Image 2023-04-20 at 16 08 18](https://user-images.githubusercontent.com/50787371/233497241-fd8cd7e7-7e6b-452f-ab3d-bf9e284a4f5d.jpeg)

### Environment

```markdown
- FlutterFlow version: 3.1 (13-Apr-23)
- Platform: Web 
- Browser name and version: (chrome)
- Operating system and version affected: Web Desktop
```

**Comment by hariprasadms** [comment]
Hi @polenvinagre - Considering the nature of issue,I can say it is not a issue instead it can be a feature request if there is something we can enable in FlutterFlow side. I can mark this as feature request. Thanks

**Comment by hariprasadms** [comment]
Hi! Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!
