### ISSUE TITLE
MyFriends template page has GEEK screen that can not be found or edited

### ISSUE THREAD

**Issue by jimmiethekid** [FlutterFlow/flutterflow-issues#797]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when no friends are in the list the page shows a screen 'No Geeks' that I can not remove or edit.

### Expected Behavior

Should show a screen that I set, not force this screen to show.

### Steps to Reproduce

install myfriends template
try to replace or edit the NO GEEKS text when there are no results

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcn15YtOodtJ0Jfxbccw/SAvJmV+TL03pu0bFEggGLbrBIYMaeD7PxNtcMOgdAhPKEWKgkc1/sLIitn1LMYnNQusbtU+zJBuewzKcF+/aoSRDZeaZmhCBdJXN2600MCn3QhDALRuLyE73DuUfNmXQhHbHuL7Zwh9f6PHaOI=

### Context

Want to edit this without having to recreate the template page.

### Visual documentation

simple to find. Just view the myFriend page with friends, then without friends. No results shows this info and it is uneditable.

### Additional Info

..

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: windows
- Browser name and version:chrome
- Operating system and version affected: win11
```

**Comment by hariprasadms** [comment]
Hi, Here is the block of code show the image you are seeing above. It is not text, it is a image. 
Update accordingly.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/17435678/233683831-762fb923-faee-40ec-949a-00fc118720dc.png">

<img width="312" alt="image" src="https://user-images.githubusercontent.com/17435678/233684014-9f6f6f37-67b4-48c5-bc9e-5acd77c2a1a8.png">

**Comment by jimmiethekid** [comment]
I am unable to edit the code within FF. I am also unable to access an assets/ folder within project media. I don’t see this in the custom code area either. Is there an action or something hidden somewhere?

Can you advise on how I can view this image within FF and edit the image? I would prefer not to have to export the code and do this in Android Studio as I understand that I am not able to import Flutter projects from Android Studio into FF. Is there a way to edit this code in FF?

Thanks,
James

**Comment by hariprasadms** [comment]
Hi, I think this can be a issue at our end. I can mark this as bug and assign for a fix. The work around is, create a new page and setup data accordingly. Let us know if the issue persists in the new pages as well. I hope you have already tried this option, if not try it and share the details.

I hope that works for you.

**Comment by jimmiethekid** [comment]
Thanks. I will try that.

How do I add actions to the buttons in the attached screenshot? This is a template chat file too, perhaps another bug in the templates? I am trying to test out push notifications on sending messages there.

**Comment by jimmiethekid** [comment]
I can not find any documents or tutorials on how to use a badge for chat message count. I am lost of how to create the local or app state to make this work.

**Comment by jimmiethekid** [comment]
Do you have tutorials on how to build out the chat template? Seems like many things are hidden and not accessible. I am trying to see how chatMain is setup for unread messages and to do the logic to read messages, plus adding triggers for push notifications to the send chat in chatDetails.

None of this info I can find and I wouldn’t know how to rebuild this without a tutorial. Your tutorials are AWESOME for all the other things.

Cheers,
James

**Comment by wenkaifan0720** [comment]
Hi @jimmiethekid. I think you have already fixed the issue, as I can't find the relevant asset/widget in your project now. As for the other questions you have, I would suggest you ask them on our community forum (https://community.flutterflow.io) as this repo is focused on bugs.
