### ISSUE TITLE
Email verified boolean does not change properly

### ISSUE THREAD

**Issue by guillediazru** [FlutterFlow/flutterflow-issues#798]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After signing up with email and verifying email, the app does not see the boolean expression and it get stuck checking if is true or false (maybe is null). Only way how to solve it is closing and opening the app again(android), on web is refreshing the page. This might be a bug because i checked with another user and is also having the problem. 

### Expected Behavior

Conditional email verified should be checked instantly and not having to "refresh" or "close-open" to make it work. 

### Steps to Reproduce

1.- sign up via email authentication on firebase
2.- go to email and verify the email
3.- comeback to the app and log in
4.- loads forever if you have a conditional of check email verified

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

--

### Context

It cuts user experience on signing up from your app when the first experience should be smooth and without problems, mostly if we are just using a authentication from firebase.

### Visual documentation

.

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Android and web
- Browser name and version: chrome 12
- Operating system and version affected: Mac OS Catalina
```

**Comment by victoriahuang1** [comment]
This is the same issue as #769
