### ISSUE TITLE
Can't generate APKs for projects with Java keywords in package name

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#8]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior

FlutterFlow should not allow package names that make APK builds fail.

## Current behavior

FlutterFlow allows including Java keywords in package names, but fails to build APKs for these projects.

## To Reproduce

1. Create new project
2. Go to Settings
3. Set package name to `com.foo.null` or something else with Java keywords. Note that FlutterFlow will block names that are keywords in Dart (e.g. `for`, `while`).
4. Initiate APK build.
5. Observe that it fails, even though there are no project errors.

## Context

I'm trying to build APK for my project, but builds are failing because of this issue.

## Screenshots

N/A

## Your environment

* Version of FlutterFlow used: v3.0, September 8 2022.
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 105.0.5195.125 (Official Build) (x86_64).
* Operating system and version (desktop or mobile): MacOS 12.5.1 (Monterey)

**Comment by agreaves** [comment]
This is now fixed internally, and will be fixed on the next deploy! 😀
