### ISSUE TITLE
Chat producing duplicate chat records

### ISSUE THREAD

**Issue by queerncool** [FlutterFlow/flutterflow-issues#80]
## Expected behavior (required)

When users submit a chat to another user, one chat record per user should produce in iPhone.

## Current behavior (required)

When users submit a chat to another user, multiple chat records produce in iPhone. On Android, this does not appear

## To Reproduce (required)
This is being reproduced in my app and after searching for the issue it was found other users have this issue with duplicate records being created. Linking here: https://community.flutterflow.io/c/discuss-and-get-help/duplicated-records

Reproduce in [Jem](https://onelink.to/zh2bbm)
1. Sign up as a user
2. Swipe right to like a user
3. Match with a user
4. Send a message via chat
5. Observe that a duplicate may appear

## Context (required)

This bug disrupts users interest in messaging each other

## Screenshots / recordings

https://user-images.githubusercontent.com/109998437/199287023-f56fb31c-38e0-4112-a5b2-cbd281e08532.MOV

https://user-images.githubusercontent.com/109998437/199287026-14decbf4-c2f4-43aa-8a77-95ab8869c67c.MOV

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: GoogleChrome
* Operating system and version (desktop or mobile): iOS

**Comment by organicnz** [comment]
@queerncool - Bree, could you pls add reproducible steps :)

**Comment by queerncool** [comment]
Added them again, they weren't appearing. @organicnz

**Comment by organicnz** [comment]
@queerncool - Bree, they've already appeared. Thanks for adding them :)

**Comment by organicnz** [comment]
I have one non-duplicated chat for now :)

![image](https://user-images.githubusercontent.com/4765090/200308545-80e2196b-ef24-49a2-ab02-e0d846091779.png)

**Comment by organicnz** [comment]
@queerncool They are in `chats` and `chat_messages` :)

<img width="1440" alt="Screen Shot 2022-11-17 at 10 52 28" src="https://user-images.githubusercontent.com/4765090/202388387-76a63a6c-1b71-4c31-9c8a-e937e1a0d300.png">
