### ISSUE TITLE
Cannot deploy to Google Play Store

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#800]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! Please check this ASAP! I am not able to push a new version to Play Store. After only 2/3 mins of deploying an error appears on the log:

1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':google_sign_in_android:compileReleaseJavaWithJavac'.
> warning: source release 1.8 requires target release 1.8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 3m 15s
Running Gradle task 'bundleRelease'...                            196.9s
Gradle task bundleRelease failed with exit code 1

Build failed :|
Step 7 script `Build AAB with Flutter` exited with status code 1
See less

### Expected Behavior

Deploy to the Play Store Correctly

### Steps to Reproduce

Deploy to the Google Play Store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMcWOdEl+tuZwgbIoznBqQUP874UxFWZMu4aVNcIleloGYE09bTueLxFPU7GE6tRrpkzpdpEBXOe2ihRr64CrrtR2pQM/xRG1S84ZmJvRMnVfZtSE1m12CQP+mQSnXDFOu/Zwh9f6PHaOI=

### Context

I need to push a new version of my app to the play store ASAP. Please check this. Thanks!

### Visual documentation

<img width="1110" alt="Captura de Pantalla 2023-04-22 a la(s) 00 00 11" src="https://user-images.githubusercontent.com/50183743/233758424-62c53d3c-5262-4d47-98c4-6de4a7f113f9.png">

### Environment

```markdown
- FlutterFlow version: 1.1.61
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: -
```

**Comment by aemelyanovff** [comment]
@pstatile Thanks for reporting the issue. It's been fixed, please try again!
