### ISSUE TITLE
🚨 Can't assign animations to GridView elements, FlutterFlow throws exception

### ISSUE THREAD

**Issue by HeikoKanzler** [FlutterFlow/flutterflow-issues#802]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a dynamic GridView with nine elements, where each element contains a stack with two containers. 

On click on the container, I want to animate (flip) the containers to swap them (like the FlippableCards, but controlled from an action, as we can't reset / animate the FlippableCards from actions)

But as soon as I add a simple animation to one of the containers inside the GridView widget, the code crashes:

```
The following assertion was thrown building Expanded(flex: 1):
An adapter was assigned twice.
'package:flutter_animate/src/adapters/adapter.dart':
Failed assertion: line 53 pos 12: '_controller == null'

```

Any ideas on how to mitigate this?

### Expected Behavior

I should be able to add animations to GridView elements.

### Steps to Reproduce

1. Create a List of any data type, e.g. String
2. Add some elements
3. Create page
4. Add GridWidget
5. Generate Dynamic Childred, choose the created list
6. Add a container to the Grid
7. Add any animation to the container
8. Test: the GridView is not rendering, throwing error messages in the console.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz/Hqx89PvsdG1ZDuc8dB/WYWNVt8RL8ascp8RQEYGIjJP4kQPPXsUxZCUsfiYFFLe0SmmXIC08LRjvOTUMcpPTOWQJhTzZNqSAnMYGK5e5OBO7WoPHZCL9xMIXag0MKRoSNAHPtaSC093XGINt+sVgPXJ72xIndISq/LZO4=

### Context

I want to add animations to a simple board game.

### Visual documentation

![CleanShot 2023-04-22 at 11 47 24](https://user-images.githubusercontent.com/5279575/233778911-53508367-79a8-4ed0-875c-33df45ad0183.jpg)

### Environment

```markdown
Affects all versions of web and desktop
```

**Comment by wenkaifan0720** [comment]
Hi @sbis04. I assume this issue is fixed as well by your PR, right?

**Comment by sbis04** [comment]
Yes. @HeikoKanzler this issue should be fixed with the next deploy!

**Comment by HeikoKanzler** [comment]
Aweome, great. Can't wait.

Again, great work and kudos to the team!
