### ISSUE TITLE
Pull to refresh  loading indicator  color not changing

### ISSUE THREAD

**Issue by fuzzball1980** [FlutterFlow/flutterflow-issues#806]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Im using the pull to refresh feature and wanted to change the default blue color of the indicator. I couldn't find a way to do it on FF but I believe it could be taking the color from the project theme so I changed the only color matching the visual color appearing on the app (info color) and it didnt work. I dont know it is currently a bug or a missing feature.

Let me know if you need some more information

### Expected Behavior

Pull to refresh Loading indicator to change to the project theme color

### Steps to Reproduce

1. Create a Page
2. Add a a Container 100%x100%
3. Add a column with a backend query single time and enable pull to fresh
4. Add an action to update the  backend query on the pull to refresh event
5. 5. Change the info color on the theme editor colors section

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ksmBw5ZNod9b7qqMbcZB/WQ5KW07a68nl+1+VUg8KOPaPOw+Ps/BM0RoTum9YHNHfVmGkWoW0ejQjezLIPQCGzOWRYc+wc0AVQ7jRmeRWrq2FJWgOnx7N5pjfXLG17W7uR5/IftpSE4c11OTft6ibAzXJpzHO0dBD6/LZO4=

### Context

I need to change the loading indicator color to match the Theme colors of my app

### Visual documentation

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5295874/233844095-f4e56f21-3c20-4550-ba96-8edc11f007af.png">
![image](https://user-images.githubusercontent.com/5295874/233844208-1d1269b0-7e17-4274-8f86-e302a0db0716.png)

### Environment

```markdown
- FlutterFlow version: current
- Platform: ios / android
- Browser name and version:chrome
- Operating system and version affected:macos
```

**Comment by fuzzball1980** [comment]
hi guys! status changed to feature request means there is no way to change the loading icon color on pull to refresh action?

**Comment by aemelyanovff** [comment]
@fuzzball1980 There's a setting for this: Theme/Design System/Loading Indicator/Color.

**Comment by fuzzball1980** [comment]
Yes but is not working on the pull to refresh indicator. It works well with the rest of loading indicators on Backend Query for buttons/columns/list etc

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/5295874/235788639-8879228f-d43b-45be-a310-6b3d4191fb91.png">

**Comment by aemelyanovff** [comment]
Oh I see. The "Pull on Refresh" indicator is very different than the "regular" loading indicator.

So, the short answer is that at the moment you can't customize its color.

I wouldn't consider it a bug, though. Could you submit it is as a feature requests through the in-app feature request tool? [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help).

**Comment by fuzzball1980** [comment]
OK, you mean the Suggestion and feedback link? https://community.flutterflow.io/c/suggestions-and-feedback/

I cant find any other feature request tool on the Help Menu

tks

**Comment by aemelyanovff** [comment]
> I cant find any other feature request tool on the Help Menu

It's under Help/Feedback/Feature Request.

**Comment by fuzzball1980** [comment]
Thanks! done!
