### ISSUE TITLE
Failed Step: Build AAB with Flutter

### ISSUE THREAD

**Issue by prayersocial** [FlutterFlow/flutterflow-issues#807]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am able to deploy to the Apple App Store but when I try to deploy to the Google Play Store I get this error. I'm just making some slight updates to the App. Any ideas on the cause of this error?

Here's the error:

truncated.............
1.4/android/src/main/java/com/github/rmtmckenzie/native_device_orientation/NativeDeviceOrientationPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/builder/programs/flutter/.pub-cache/hosted/[pub.dev/sqflite-2.2.6/android/src/main/java/com/tekartik/sqflite/Database.java:94](https://pub.dev/sqflite-2.2.6/android/src/main/java/com/tekartik/sqflite/Database.java:94): warning: [deprecation] getApplicationInfo(String,int) in PackageManager has been deprecated
            final ApplicationInfo applicationInfo = context.getPackageManager().getApplicationInfo(packageName, PackageManager.GET_META_DATA);
                                                                               ^
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseJavaResource'.
> A failure occurred while executing [com.android.build](https://com.android.build/).gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/core_release.kotlin_module'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 3m 56s
Running Gradle task 'bundleRelease'...                            237.4s
Gradle task bundleRelease failed with exit code 1

Build failed :|
Step 7 script `Build AAB with Flutter` exited with status code 1

### Expected Behavior

 I basically implemented and used the Mux Livestream Widget:
and followed the instructional video by Flutterflow to implement this widget. This is the instructional video: https://youtu.be/fjLvQwu_eug 

Please note that I am able to publish to the Apple Store without any issues, this error only happens on Google Playstore.

### Steps to Reproduce

1. hit the Deploy to the Playstore button under Mobile Deployment.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiOfqw5JPm7RE+Kr2dvpanSQQHDsnbecam8pBdzYdF7LdPbN/Z/fRSEpvOde0T2xEJ1mjoHgdw93emvL9MfknPRGdQYA/+qVIcTnvd3yWeJikBbuaRG5/Dd1NCFPF5J2rsyYnXcRsSXwDwU6EDOu/dBXqJuP1NW0dQeWiA5OK2SrDX1iXc2URm05KZDPz

### Context

Unable to Deploy to the Google Playstore

### Visual documentation

<img width="227" alt="Screenshot 2023-04-22 170923" src="https://user-images.githubusercontent.com/112043735/233847778-2cf6b29a-b9f8-4f8f-979b-556f0fdae2e8.png">

### Additional Info

<img width="227" alt="Screenshot 2023-04-22 170923" src="https://user-images.githubusercontent.com/112043735/233847638-d6d7342b-299a-44b0-bca1-d130f2d11e7e.png">
<img width="937" alt="Screenshot 2023-04-22 172154" src="https://user-images.githubusercontent.com/112043735/233847654-7806de10-ad79-47d4-a11e-b572b1e5d0ac.png">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by bulgariamitko** [comment]
This will be a hard one for me to reproduce, but I will leave it as bug so the FF team can look into it as to me it seems like a bug.

**Comment by agreaves** [comment]
Hi @prayersocial, thanks for the bug report! This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io.

That being said, we are upgrading the Kotlin version in a coming update and I believe this may fix your issue.
