### ISSUE TITLE
Using a code expression in the progress value of a progress bar generates an error in code view

### ISSUE THREAD

**Issue by Julihan** [FlutterFlow/flutterflow-issues#808]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Adding a code expression to a progress bar (for example var1/var2) causes a bug while trying to view the code.

### Expected Behavior

Code should be generated

### Steps to Reproduce

1. add a progress bar
2. in progress value add a dynamic value
3. select code expression
4. create a simple expression, like a division
5. validate the expression
6. and the dynamic value
7. then view the generate code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

failure to copy bug report card

### Context

Trying to crate a dynamic progress bar

### Visual documentation

https://user-images.githubusercontent.com/1126006/233849716-af61f1fc-c5cb-44d6-95db-dfad75cfe943.mp4

### Environment

```markdown
- FlutterFlow version: v3.1 April 2023
- Platform: web
- Browser name and version: safari
- Operating system and version affected: MacOS 13.1
```

**Comment by hariprasadms** [comment]
Hi @Julihan - I have tested this issue. It all works fine at my end. Can you please setup up the issue in a blank project and share bug report code of the project please. Without blank project with showing issue we can't proceed for issues investigation.

**Comment by Julihan** [comment]
Hey @hariprasadms. I did, you can see that in the video, it's a blank project with just a progress bar.
I tried to copy the bug report code, but I get an error message when trying:
<img width="663" alt="Screenshot 2023-04-23 at 21 34 30" src="https://user-images.githubusercontent.com/1126006/233861103-8c096961-e825-4f6f-bd3a-f953d3f4316f.png">

**Comment by hariprasadms** [comment]
Hi @Julihan - Generate bug report code is working fine now. Check and share the code please. Thanks

**Comment by Julihan** [comment]
@hariprasadms It's still not working on my end. See attached video:

https://user-images.githubusercontent.com/1126006/233984819-849dcc0a-8705-40f8-bddd-e29b28545cae.mp4

**Comment by Julihan** [comment]
Not sure where to find the project id. Can it be `/test-5l2tq0`? It in the url

**Comment by hariprasadms** [comment]
Yes thats the one. See below, it looks fine at my end.

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/17435678/234051878-41fbe6f5-d397-404c-88ee-fd52bfdb5237.png">

**Comment by hariprasadms** [comment]
Hello, Can you try this in chrome browser. FlutterFlow editor is mostly recommended work on chrome browser. We are not yet fully supporting for safari. It is browser specific issue.

**Comment by Julihan** [comment]
Ah yes it works on Chrome. But you have Apple ID sign in/sign up which is not possible on Chrome :(

**Comment by victoriahuang1** [comment]
Hi @Julihan , thanks for the report. Since this looks like a Safari specific issue, we will not be looking into making a fix for Safari just yet (like @hariprasadms said, our main focus is Chrome and are making a choice to not fully support Safari at this moment).

However, you should be able to use Apple ID sign in on Chrome. If this is not the case, please open a separate Github issue for not being able to use Apple ID sign in on Chrome.
