### ISSUE TITLE
App Bar Selection Button Not Clickable

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#809]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I just tried to change one of my app bar layouts and its now not clickable.
Tried adding the new page, but it's still unclickable.

### Expected Behavior

Able to change the App bar layout as usual. But since its unclickable, Can't work it out.

### Steps to Reproduce

1. Create a New Page
2. Blank/Premade Page
3. Click on App Bar Icon.
4. App bar Icon Unclickable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40j8nfvJNPm8Nf1arAcvpajic5Jml7aoER0+5BaCgoF5jpD7MAdvXsSEtvcNe9YGNifESmmkwf3MrGiOz1GvAVH0uufqZbzaoBeDz/RlyjQZOBPZavdWhSEfpgFW6G3MKJrQlCPtNZc38u6lyIBN+9HwzDGJD0IlFISq/LZO4=

### Context

I am trying to change App bar layout.

### Visual documentation

Short Video.
https://www.loom.com/share/a05aee40688a431f94bb79c1c5591b62

### Additional Info

None.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web and MacOS
- Browser name and version: Chrome 112.0.5615.137 Arm
- Operating system and version affected: MacOS Ventura
```

**Comment by SquirrelOverlord** [comment]
I'm having this issue and noticed it yesterday, but thought it was related to my lack of skills and not being able to follow a tutorial correctly.

- FlutterFlow version: 3.1 - Flutter 3.7.3
- Platform: Web and Windows 10 Home 
- Browser name and version: Waterfox G5.1.5 (64 bit) (also replicated on Edge, Chrome, Brave, Opera, Firefox)
- Operating system and version affected: Windows 10 Home (AMD Ryzen 7 4800HS with Radeon Graphics 2.90 GHz) v 22H2, 64 bit

**Comment by Dev-Muhammad-Junaid** [comment]
The mentioned issue is now resolved after the recent Flutter Flow Update.

**Comment by SquirrelOverlord** [comment]
Hi Muhammad,
I can confirm that this is now working as it should, thanks to you and the team for the prompt resolution :)
