### ISSUE TITLE
AudioPlayer not working on web with deep linking enabled for asset audios

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#81]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Audio player loads "asset" audios.

## Current behavior (required)

Audio player can't play asset audios on web in the scenario below.

## To Reproduce (required)

1. Create new project
2. Add new page, e.g. Page2
3. Add link from HomePage to Page2.
4. Add an audio to project assets.
5. On Page2, create an audio player.
6. Select audio type = Asset and the uploaded audio as Asset Audio.
7. Publish to web.
8. Open the published link.
9. Navigate from HomePage to Page2.
10. Observe that the audio widget does not show.
11. Open browser dev tools/network.
12. Observe that it tried to load the audio from `https://<project>.flutterflow.app/page2/assets/assets/audios/<filename>.mp3`. Expected: `https://<project>.flutterflow.app/assets/assets/audios/<filename>.mp3`

Project: https://app.flutterflow.io/project/audio-asset-63344x

## Context (required)

Can't use audio player on web.

## Screenshots / recordings

N/A

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: FlutterFlow v3.0, released October 28, 2022
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: Chrome, Version 107.0.5304.87 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): MacOS 12.5.1 Monterey.

**Comment by AbbyAltes** [comment]
Hello. It works in RUN mode, but once published, they disappear. 
I followed the described step by step, but they don't work. 
<img width="1440" alt="Screenshot 2023-06-01 at 12 01 58" src="https://github.com/FlutterFlow/flutterflow-issues/assets/69810502/f382d8b3-312c-4b97-8730-4afaa1872850">
<img width="1440" alt="Screenshot 2023-06-01 at 12 08 38" src="https://github.com/FlutterFlow/flutterflow-issues/assets/69810502/78973b49-c04c-4d3f-a86d-5519114375fb">
![IMG_68F8FA6F69A9-1](https://github.com/FlutterFlow/flutterflow-issues/assets/69810502/3177d528-5d57-40f2-8e5e-6a06d48562e3)
Any updates in this regard?
Thanks :)

**Comment by aemelyanovff** [comment]
Not sure when it happened, but I no longer can reproduce the issue. Closing as fixed.
