### ISSUE TITLE
Bottom sheet does not respect safe area

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#812]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when opening a bottom sheet in full height it does not respect the safe area at the top. 

### Expected Behavior

to open full height up until the safe area

### Steps to Reproduce

1. create a new page
2. set safe area on the page
3. dont set Height on bottom sheet or set to 100%
4. when it opens it will open to full screen and go behind the safe area
5. i did not test on a blank project as i am testing on a device not in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/my-food-log-00wn3c?tab=pageSelector&component=NutritionFactsBottomSheet

### Context

i inspected the code in showModalBottomSheet and it appears that it should check for safe area, but not sure it is enabled. current workaround is setting a % but this makes for not as clean of a look when you want a full height bottom sheet. 

### Visual documentation

![01A83ADF-5127-4E93-AA43-1BA6B52B2016](https://user-images.githubusercontent.com/101305587/234399243-d5e2f0a0-31a8-4aaf-bbbd-13c8a02765e8.jpeg)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: testing on device
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @trevorFields - I just tested in my projects following above steps. I can reproduce the issue in **Android and iOS simulators**.

In run or debug mode, it does not show up as device frame is not available. However, I can see there is a work around by reducing the height to 90%. We will fix it in next updates.

**Comment by nicmohr25** [comment]
Is their an update to this problem? When will the next update be available?

**Comment by trevorFields** [comment]
update: in the showModalBottomSheet if i set useSafeArea: true it respects the safe area, this is a simple fix please add this as an option or default as true, it seems that if you have a safearea it should be respected.

**Comment by Pask42** [comment]
Hi @hariprasadms when will the correction be available in FlutterFlow?

**Comment by trevorFields** [comment]
> 

here is my current workaround, i created a simple function where you pass in screen height and it removes 60px which is enough for all iphones and most android phones as well. this way i can reuse it everywhere and if i need to change the px amount later it will adjust all bottom sheets. hoping they just turn on respecting safe area as would be expected behavior. 
![CleanShot 2023-07-06 at 18 04 26](https://github.com/FlutterFlow/flutterflow-issues/assets/101305587/fe0089a1-fc90-48b2-8cb1-77860e10adc1)

**Comment by Pask42** [comment]
Hi @trevorFields, thank you very much

**Comment by trevorFields** [comment]
> Hi @trevorFields, thank you very much

i noticed this is now added, i havent tested on a full height bottom sheet but in the code this is exposing and setting the correct respect safe area for bottom sheets. i'm closing the ticket.

<img width="335" alt="CleanShot 2023-08-13 at 13 40 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/101305587/25ef633e-6b30-431d-9bd6-ce4042a3f276">
