### ISSUE TITLE
UI - App state - deleting variables - type<JSON> values stuck

### ISSUE THREAD

**Issue by oomti** [FlutterFlow/flutterflow-issues#815]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After deleting an app state variable the columns of the state variable names and variable values misalign(if they are JSON type).

### Expected Behavior

The variables names and variable values remain aligned.

### Steps to Reproduce

1. Create app state variable string.
2. Create 1st JSON app state variable, fill with value
3. create 2nd JSON app state variable, fill with value
4. Delete first JSON app state variable.

Tested from a blank project.

Regular variables don't have the issue. 

Confirmed JSON variables experience the issue.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8j6yItPxd9Y0LrtbcdFmioRNmY6U6xNmMIaZwwdF5/NG4gIZfTBXE9uOP25dkFiJWCKknox+tKLm9z1NvYpOk6aGapR1rh2dQLgJHGXMsmMEZCCSUREGshYfkyg5J+rvAp4XetqSVkj7066C++vYC3fJL7NNlU/MPiHENnXmAfuQ0SLb3kNh1JWeC/v

### Context

Context: using adblocker.

### Visual documentation

See above

### Additional Info

Example:

![image](https://user-images.githubusercontent.com/23347037/234592900-13f54ef8-f38c-4d01-baff-76292815d4b0.png)

After removing "Reading station" variable:

![image](https://user-images.githubusercontent.com/23347037/234598242-a2822b0a-1f17-49c6-be27-e4565a3511de.png)

You can see the Json document is now on "userRef". Once refreshed the issue is gone.

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: 
- Browser name and version: redacted due to privacy
- Operating system and version affected: redacted due to privacy
```

**Comment by hariprasadms** [comment]
Hi @oomti - Can you please setup the issue in a blank project and share bug report code of the project. Without these details, we can't investigate the issue. Thanks

**Comment by oomti** [comment]
Thanks for the notice.

I've added the bugreport code from a sample project.

**Comment by wenkaifan0720** [comment]
Hi @oomti. This has been fixed and should be live in our next update. Thanks for reporting!
