### ISSUE TITLE
APK Build Error

### ISSUE THREAD

**Issue by pippoberto** [FlutterFlow/flutterflow-issues#816]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click ok download apk, after few seconds, I get this error:
<img width="604" alt="Screenshot 2023-04-26 alle 18 24 29" src="https://user-images.githubusercontent.com/64846189/234666487-07742955-8e92-4687-a213-160e095ae980.png">

### Expected Behavior

It should generate and download the apk of the app.

I daily download the apk of the app to test it on device and It worked fine until today. I haven't 

### Steps to Reproduce

We are working on this app for some months now so it is quite complex. For this reason I don't know what is generating the error but I know what I changed from the last it worked.
I download the apk almost daily to test it on device so I am sure that until the last changes it was working.
I changed just a few things:

- I created an App State Variable to check if the user is visiting some pages for the first time or not
- I added conditional actions which depend by the variable previously created
- I added a check on the email before the login to see if the user has confirmed his email

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksrl8YxNpbwB18/uYO5r/SARQ1B9UL8sscpCbw4bIYj2P4lzY876P0xVOOKoSnxUfGamp141wM7SuPOeGuw6Ik+dRrpyzLl+ehXKeHOXSqmTF7iOYHZtN+Rmf0vH0JmJsyVSHOtvW1Jk2k2uJ+e9dHfbJYf7PGo8Sq/LZO4=

### Context

It does't allow me to download the apk even though the project has no errors end the the test works fine on web.

### Visual documentation

<img width="604" alt="Screenshot 2023-04-26 alle 18 24 29" src="https://user-images.githubusercontent.com/64846189/234671764-9460a74f-53d2-46e0-bef5-8930803a83ea.png">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Safari 16.2 (18614.3.7.1.5)
- Operating system and version affected: MacOs Ventura 13.1

tested also on: 
- FlutterFlow version: v1.1.63
- Platform: MacOs Application
```

**Comment by Thesergiolg99** [comment]
having the same issue here!, glad to know its not just me. Thanks! +1

**Comment by younicornsJH** [comment]
Same using CodeMagic deployment

**Comment by hariprasadms** [comment]
Hi @pippoberto - Thanks for reporting the issue. I can re produce the issue.

**Comment by younicornsJH** [comment]
Seems fixed as of today

**Comment by Thesergiolg99** [comment]
> Seems fixed as of today

i continue having problems. now is the camera-plugin instead of package info plus

**Comment by WellDunDun** [comment]
I'm also getting APK Build Failed on and off depending on when I try. It looks like FlutterFlow needs to upgrade their servers "java.ioIOException: No space left on device"

![image](https://user-images.githubusercontent.com/45949032/234809831-7c06201d-2c7f-46d8-8d7c-75aa50d850cb.png)

**Comment by jerfai** [comment]
I'm now experiencing a new issue:

`Codemagic Deploy Output
Failed Step: Get Flutter packages

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Running "flutter pub get" in flutter_tools...
Resolving dependencies in ../programs/flutter/packages/flutter_tools...
  _fe_analyzer_shared 50.0.0 (59.0.0 available)
  analyzer 5.2.0 (5.11.1 available)
  archive 3.3.2 (3.3.7 available)
  args 2.3.1 (2.4.0 available)
  async 2.10.0 (2.11.0 available)
  built_value 8.4.2 (8.4.4 available)
  checked_yaml 2.0.1 (2.0.2 available)
  collection 1.17.0 (1.17.1 available)
  completion 1.0.0 (1.0.1 available)
  coverage 1.6.1 (1.6.3 available)
  dds 2.5.0 (2.7.9 available)
  dds_service_extensions 1.3.1 (1.3.3 available)
  devtools_shared 2.18.0 (2.23.0 available)
  dwds 16.0.2+1 (19.0.0 available)
  fixnum 1.0.1 (1.1.0 available)
  frontend_server_client 3.1.0 (3.2.0 available)
  html 0.15.1 (0.15.2 available)
  intl 0.17.0 (0.18.1 available)
  io 1.0.3 (1.0.4 available)
  js 0.6.5 (0.6.7 available)
  json_annotation 4.7.0 (4.8.0 available)
  logging 1.1.0 (1.1.1 available)
  matcher 0.12.13 (0.12.15 available)
  meta 1.8.0 (1.9.1 available)
  mime 1.0.2 (1.0.4 available)
  multicast_dns 0.3.2+2 (0.3.2+3 available)
  native_stack_traces 0.5.2 (0.5.5 available)
  node_preamble 2.0.1 (2.0.2 available)
  path 1.8.2 (1.8.3 available)
  petitparser 5.1.0 (5.4.0 available)
  pubspec_parse 1.2.1 (1.2.2 available)
  source_maps 0.10.11 (0.10.12 available)
  source_span 1.9.1 (1.10.0 available)
  sse 4.1.1 (4.1.2 available)
  test 1.22.0 (1.24.2 available)
  test_api 0.4.16 (0.5.2 available)
  test_core 0.4.20 (0.5.2 available)
  usage 4.1.0 (4.1.1 available)
  vm_service 9.4.0 (11.4.0 available)
  web_socket_channel 2.2.0 (2.4.0 available)
  webdriver 3.0.1 (3.0.2 available)
  xml 6.2.2 (6.3.0 available)
Got dependencies in ../programs/flutter/packages/flutter_tools!
Resolving dependencies...
Connection closed before full header was received
pub finished with exit code 69


Build failed :|
Step 5 script `Get Flutter packages` exited with status code 69 `

**Comment by Dentiphoto** [comment]
> Hi @pippoberto - Thanks for reporting the issue. I can re produce the issue.

Hello. Can you help us? This is really long and there is no way to solve it.

**Comment by aemelyanovff** [comment]
@pippoberto Thanks for reporting the issue. Are you still experiencing it? I believe this has been fixed already.

Also for the future, we ask "steps to reproduce" to start from a blank project. It it's a project-specific issue without a simple way to reproduce it from a blank project, we ask you to reach out to FlutterFlow support instead.

**Comment by pippoberto** [comment]
> @pippoberto Thanks for reporting the issue. Are you still experiencing it? I believe this has been fixed already.
> 
> Also for the future, we ask "steps to reproduce" to start from a blank project. It it's a project-specific issue without a simple way to reproduce it from a blank project, we ask you to reach out to FlutterFlow support instead.

Now it is fixed, I can download the apk without errors. Thank you for the advice, next time I will reach out to FlutterFlow support.
