### ISSUE TITLE
Gmail Authentication not working when app deploy in play store

### ISSUE THREAD

**Issue by vickyone0** [FlutterFlow/flutterflow-issues#817]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when click on the Gmail authentication button ,can't able to login/signup using Gmail. This happens only when the app is deploy in play store . Also phone authentication feature is work properly when it deploy to play store. 

### Expected Behavior

when click on Gmail button ,can able to signin/signup . 

### Steps to Reproduce

1.Create a page for Gmail authentication
2.Create a new project in Google play console
3.Add sha-1 key in firebase for the play console
4.create service account and connect with our project in play console
5.deploy app to play store using flutterflow(upload the service key json file)
6.Install app from play store and try Gmail signin feature

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fiPLq2492obgA+KX6avpaoCoRNjM2U4ZMidVxYwsbfLHqE7Mud/f7SxZJbf2BTAhqL079in8d/vDIhc7yA+UqOSeaRphPwahiWz3zcz+VRJibDpO3PkZ9FppJJVPC1MCznx1DANdpW1oZ22CIA+mtVgncCbK3O0YvD8+HItn7s2upQ0SLb3kNh1JWeC/v

### Context

can't use Gmail signin for my app

### Visual documentation

![Screenshot_20230427_105639 1](https://user-images.githubusercontent.com/101127083/234771044-7cb9e59a-e455-40bd-b427-a173b677db98.jpg)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: web
- Browser name and version: Chrome 112.0.5615.138
- Operating system and version affected: windows 11 pro 21h2
```

**Comment by hariprasadms** [comment]
Hi @vickyone0 - Thanks for reporting the issue. I think this issue is related to SHA1 certificate key configuration. Follow below link and configure SHA1 key and see if there are any differences. 

https://docs.flutterflow.io/data-and-backend/firebase/authentication/initial-setup

<img width="814" alt="image" src="https://user-images.githubusercontent.com/17435678/235151300-67ead3cc-a69e-4460-94f2-d70090663474.png">

**Comment by vickyone0** [comment]
when I deploy my app in play store ,Gmail authentication  feature doesn't work. when we deploy app in play store we want to add sha key that generate from the play console want to add in the firebase . I add sha key properly. after that phone OTP authentication works properly but Gmail doesn't work properly

**Comment by hariprasadms** [comment]
Hi @vickyone0 - Its been a while after your last follow on this issue. I hope you got the solution for the issue. Can you please update the issue status accordingly please.

**Comment by vickyone0** [comment]
hi @hariprasadms - still that error occur . I don't know why it occur. when I try to signup in my app using Gmail authentication that error is occur. when Click on the Gmail option a bottom sheet is pop up and inside that my Gmail is mention just like all app. when I click on my Gmail it redirect to the signup page again. my App is deploy in play store as internal testing. do you have and idea about it. I add auth service in my google console and sha-1 key from the play console also added in my firebase. Still same error occur. !!!!!!!!!ANY SOLUTION$$$$$$

**Comment by vickyone0** [comment]
still same bug . no update from your team

**Comment by zulfijm** [comment]
I have same issue, when i deploy app through flutterflow mobile deployment, it doesn't work.
Only time it works when i download the apk file and install it on my mobile phone.

Also do I have to update/generate SHA1 every time I deploy my app's new version?

Please assist.

**Comment by hariprasadms** [comment]
Since the issue is considerably old and there has been no follow-up, we assume that it has been resolved in the latest FlutterFlow updates. If issue still persists, please create a new issue with all required details. Thanks

**Comment by Abadar169** [comment]
I've been attempting to set up Google Sign-In with Firebase in my project, and I've encountered an issue. While it operates correctly in FlutterFlow's test environment, I'm facing problems when I try running the downloaded APK of the app. I've already input both the SHA-1 and SHA-256 keys into the Firebase console.

**Comment by hariprasadms** [comment]
Hi @Abadar169 - Please follow this doc - https://docs.flutterflow.io/data-and-backend/firebase/authentication/initial-setup#1.-generate-the-sha-1-key.  And, follow this section. 1. Generate the SHA-1 key.
