### ISSUE TITLE
Manage content doesn't work with some Data Types

### ISSUE THREAD

**Issue by pippoberto** [FlutterFlow/flutterflow-issues#818]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to modify a document from the manage content console some times it doesn't allow me to modify it and other times it shows a grey screen. After many attempt I found that the problem occurs in particular cases. It happens on the user collection which has many DataTypes.
When I modify a document which I previously created without initializing every field, if I click on a datatype which contains four lists of references and strings and I don't modify anything and click on save data and then update document this button doesn't work, so I can't update the document.
After that if I click again on the datatype to modify it, it shows a grey rectangle instead of the fields which I should compile.
In addition to that when I click on the modify button of some of the document I have in this collection it doesn't do anything and I can't modify any field of this document.

<img width="593" alt="Screenshot 2023-04-27 alle 15 10 42" src="https://user-images.githubusercontent.com/64846189/234872074-b5498aac-7f21-40a0-94fe-29f5dd190655.png">

### Expected Behavior

I should be able to modify every document from manage content. If I want to leave an array of a Data Type empty it should allow me to do it.

### Steps to Reproduce

1. Create the Data Type with an array of references and one of String (I still don't know which list is causing problems)
2. Create a collection which has as field the previous Data Type and some other fields
3. Create from manage content (ore Firestore) a document without compiling the dataType fields
4. Click on modify document from the manage content console
5. Click on the Data Type and without editing anything on save changes
6. Click on update document (it doesn't work)
7. Click again on the datatype (it shows the grey screen)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksrl8YxNpbwB18/uYO5r/SARQ1B9UL8sscpCbw4bIYj2P4lzY876P0xVOOKoSnxUfGamp14ew82LjuPTJscpOU2dftlz1bV1WgzdQXOQVaWTF7igRn9AJ91RCWqi0p63uyNNJtheSiER60OMH+TIQXbvGJjsCmo8Sq/LZO4=

### Context

I connected my application with the Firestore database. The database is quite complex, in particular the user collection, the one is giving me problems, has many maps which I created using DataTypes from flutter flow. If I add documents from Firestore I don't have problems but I don't have a schema to follow so it is difficult to add data. For this reason it would be useful to use manage content.

### Visual documentation

https://user-images.githubusercontent.com/64846189/234870612-cfef3991-4427-4156-b726-0a3c9b4bf4dc.mov

It also give the same error if I add one field to one of the arrays but I live the others empty 

https://user-images.githubusercontent.com/64846189/234871290-c0a3d8bd-d98f-4f5a-81c2-7bb508cdaada.mov

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.3
- Platform: Web
- Browser name and version: Safari 16.2 (18614.3.7.1.5)
- Operating system and version affected: MacOs Ventura 13.1
```

**Comment by hariprasadms** [comment]
Hi @pippoberto - Thanks for reporting the issue. You appear to be using the Safari browser. The Safari browser does not fully support FlutterFlow editor. We are working to resolve the safari browser-specific issues those are exists. The FlutterFlow team recommends to use Chrome as your primary browser when using the FlutterFlow editor. I advise testing this on the Chrome browser to see if the issue persists. Please let us know how it goes on Chrome browser. Thanks

**Comment by pippoberto** [comment]
> Hi @pippoberto - Thanks for reporting the issue. You appear to be using the Safari browser. The Safari browser does not fully support FlutterFlow editor. We are working to resolve the safari browser-specific issues those are exists. The FlutterFlow team recommends to use Chrome as your primary browser when using the FlutterFlow editor. I advise testing this on the Chrome browser to see if the issue persists. Please let us know how it goes on Chrome browser. Thanks

Hi @hariprasadms thank you for your time. I tested it also on windows pc using chrome and the problem is the same.

**Comment by aemelyanovff** [comment]
@pippoberto Sorry for the very slow turnaround.

I'm unable to reproduce the issue by following these steps. Are you still experiencing the issue? If yes, can you try to reproduce it from a blank project?

If you can reproduce it from a blank project, please add a link to the project.

**Comment by aemelyanovff** [comment]
Closing as inactive

**Comment by koya-sunup** [comment]
I am experiencing the same issue. is it already solved?
