### ISSUE TITLE
Dismiss bottom sheet value is not detecting the correct data type. Happened after recent update.

### ISSUE THREAD

**Issue by wmacklin** [FlutterFlow/flutterflow-issues#819]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After recent update all bottom sheet dismiss actions have errors. I have 7 errors in the log but the errors alert says 29.

### Expected Behavior

No errors where there before update.

### Steps to Reproduce

1. Click green refresh button for new update

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i/LlvJd2xNta1rruccFr/TgWOUs7a40R18EbWRU8KOPdOoYUP8+kM0RtYM+/YXxDPmaKjWoW0taKjeOeD+04NTiYbao+z5BTEgKXfGWVM7aDFJWgRmtDEZlUIUiG36Wv3xMkBLRYS04ZwFyyfvCucDDtGLq3Cm0WDq/LZO4=

### Context

Refreshed screen for new update. No errors before that.

### Visual documentation

![screenshot-app flutterflow io-2023 04 27-17_44_50](https://user-images.githubusercontent.com/11440537/234997955-df9a5b4e-5395-4348-ad3e-26f05121ff9c.png)

### Environment

```markdown
- FlutterFlow version: 3.1 -flutter3.7.12
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: desktop windows 10
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @wmacklin. We'll release a fix soon.

For the future, we ask that "Steps to Reproduce" should start from a blank project :-)

**Comment by wmacklin** [comment]
I removed the widgets that had the employeeRecordList error.

**Comment by wmacklin** [comment]
Sorry for not being able to give steps to reproduce. The error you should me were on components that were previously done. That is why I was confused on what was going on. Also The 29 errors were showing on previous days snapshots when it just happened.

**Comment by aemelyanovff** [comment]
Should be fixed now!
