### ISSUE TITLE
Null issue passing a list to another page

### ISSUE THREAD

**Issue by kjoyceee** [FlutterFlow/flutterflow-issues#82]
## Expected behavior (required)

Page A loads queries firebase and loads the list of documents and on a button press to page B passes along the list of documents. Page B has a Page Parameter of List<Document>

## Current behavior (required)
Produces an error both in flutterflow run mode as well exporting to Android Studio

## To Reproduce (required)
1. Create page a
2. Create page b
3. Setup a firebase query
4. On page b setup a page parameter of List<Document>
5. On page a run the query then pass the query to page b
6. run the app

## Context (required)

Cannot use flutter to test apps, have to export and tweak code. Can navigate around this by adding ! before .map

## Screenshots / recordings

![error](https://user-images.githubusercontent.com/115580022/199339240-4d266c96-5049-4181-a299-a83bfacacd79.PNG)

**Comment by hariprasadms** [comment]
Hi @kjoyceee , 

I can test this by passing list of names ( names are stored in list type local state ) to page b. I can see the names are listing in the page with no null error. If it can work for local state it should work for fire-store documents as well. 

Can you please share the code snippets of page 1 and page b which is showing parameter passing from page a and also data receiving in the page b. This can help us to see whats going on with the generating code. 

Below is the example code showing list data passing from page a to page b.

![listissue](https://user-images.githubusercontent.com/17435678/199844780-f7509f1e-a481-465e-9189-c06efd1063eb.jpg)

**Comment by kjoyceee** [comment]
Hi @hariprasadms 

My apologies it appears the issue lies with combining it with a simplesearch. I will post pageA and pageB entire page codes.

**Comment by kjoyceee** [comment]
Page A:

import '../backend/backend.dart';
import '../flutter_flow/flutter_flow_theme.dart';
import '../flutter_flow/flutter_flow_util.dart';
import '../flutter_flow/flutter_flow_widgets.dart';
import '../page_b/page_b_widget.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class PageAWidget extends StatefulWidget {
  const PageAWidget({Key? key}) : super(key: key);

  @override
  _PageAWidgetState createState() => _PageAWidgetState();
}

class _PageAWidgetState extends State<PageAWidget> {
  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<List<FirebaseCollectionRecord>>(
      stream: queryFirebaseCollectionRecord(),
      builder: (context, snapshot) {
        // Customize what your widget looks like when it's loading.
        if (!snapshot.hasData) {
          return Center(
            child: LinearProgressIndicator(
              color: FlutterFlowTheme.of(context).primaryColor,
            ),
          );
        }
        List<FirebaseCollectionRecord> pageAFirebaseCollectionRecordList =
            snapshot.data!;
        return Scaffold(
          key: scaffoldKey,
          backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
          appBar: AppBar(
            backgroundColor: FlutterFlowTheme.of(context).primaryColor,
            automaticallyImplyLeading: false,
            title: Text(
              'Page Title',
              style: FlutterFlowTheme.of(context).title2.override(
                    fontFamily: 'Lafarge',
                    color: Colors.white,
                    fontSize: 22,
                    useGoogleFonts: false,
                  ),
            ),
            actions: [],
            centerTitle: false,
            elevation: 2,
          ),
          body: SafeArea(
            child: GestureDetector(
              onTap: () => FocusScope.of(context).unfocus(),
              child: Column(
                mainAxisSize: MainAxisSize.max,
                children: [
                  FFButtonWidget(
                    onPressed: () async {
                      await Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => PageBWidget(
                            pageBPageParameter:
                                pageAFirebaseCollectionRecordList.toList(),
                          ),
                        ),
                      );
                    },
                    text: 'Button',
                    options: FFButtonOptions(
                      width: 130,
                      height: 40,
                      color: FlutterFlowTheme.of(context).primaryColor,
                      textStyle:
                          FlutterFlowTheme.of(context).subtitle2.override(
                                fontFamily: 'Lafarge',
                                color: Colors.white,
                                useGoogleFonts: false,
                              ),
                      borderSide: BorderSide(
                        color: Colors.transparent,
                        width: 1,
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

**Comment by kjoyceee** [comment]
pageB:

import '../backend/backend.dart';
import '../flutter_flow/flutter_flow_theme.dart';
import '../flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:text_search/text_search.dart';

class PageBWidget extends StatefulWidget {
  const PageBWidget({
    Key? key,
    this.pageBPageParameter,
  }) : super(key: key);

  final List<FirebaseCollectionRecord>? pageBPageParameter;

  @override
  _PageBWidgetState createState() => _PageBWidgetState();
}

class _PageBWidgetState extends State<PageBWidget> {
  List<FirebaseCollectionRecord> simpleSearchResults = [];
  TextEditingController? textController;
  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    textController = TextEditingController();
  }

  @override
  void dispose() {
    textController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
      appBar: AppBar(
        backgroundColor: FlutterFlowTheme.of(context).primaryColor,
        automaticallyImplyLeading: false,
        title: Text(
          'Page Title',
          style: FlutterFlowTheme.of(context).title2.override(
            fontFamily: 'Lafarge',
            color: Colors.white,
            fontSize: 22,
            useGoogleFonts: false,
          ),
        ),
        actions: [],
        centerTitle: false,
        elevation: 2,
      ),
      body: SafeArea(
        child: GestureDetector(
          onTap: () => FocusScope.of(context).unfocus(),
          child: Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              TextFormField(
                controller: textController,
                onFieldSubmitted: (_) async {
                  setState(() {
                    simpleSearchResults = TextSearch(
                      widget.pageBPageParameter
                          .map(
                            (record) => TextSearchItem(
                            record, [record.aField!, record.bField!]),
                      )
                          .toList(),
                    )
                        .search(textController!.text)
                        .map((r) => r.object)
                        .toList();
                  });
                },
                autofocus: true,
                obscureText: false,
                decoration: InputDecoration(
                  hintText: 'search',
                  hintStyle: FlutterFlowTheme.of(context).bodyText2,
                  enabledBorder: UnderlineInputBorder(
                    borderSide: BorderSide(
                      color: Color(0x00000000),
                      width: 1,
                    ),
                    borderRadius: const BorderRadius.only(
                      topLeft: Radius.circular(4.0),
                      topRight: Radius.circular(4.0),
                    ),
                  ),
                  focusedBorder: UnderlineInputBorder(
                    borderSide: BorderSide(
                      color: Color(0x00000000),
                      width: 1,
                    ),
                    borderRadius: const BorderRadius.only(
                      topLeft: Radius.circular(4.0),
                      topRight: Radius.circular(4.0),
                    ),
                  ),
                  errorBorder: UnderlineInputBorder(
                    borderSide: BorderSide(
                      color: Color(0x00000000),
                      width: 1,
                    ),
                    borderRadius: const BorderRadius.only(
                      topLeft: Radius.circular(4.0),
                      topRight: Radius.circular(4.0),
                    ),
                  ),
                  focusedErrorBorder: UnderlineInputBorder(
                    borderSide: BorderSide(
                      color: Color(0x00000000),
                      width: 1,
                    ),
                    borderRadius: const BorderRadius.only(
                      topLeft: Radius.circular(4.0),
                      topRight: Radius.circular(4.0),
                    ),
                  ),
                ),
                style: FlutterFlowTheme.of(context).bodyText1,
              ),
              Builder(
                builder: (context) {
                  final searchedList = simpleSearchResults.toList();
                  return Column(
                    mainAxisSize: MainAxisSize.max,
                    children:
                    List.generate(searchedList.length, (searchedListIndex) {
                      final searchedListItem = searchedList[searchedListIndex];
                      return SelectionArea(
                          child: Text(
                            searchedListItem.aField!,
                            style: FlutterFlowTheme.of(context).bodyText1,
                          ));
                    }),
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by kjoyceee** [comment]
the error is thrown on pageB line 70. If I add a null check on the end of line 69 I experience no issues.

**Comment by matthew-raul** [comment]
Can confirm @kjoyceee 's issue and fix. I am passing a List of Documents to a Page as a Page Parameter from a Firestore Query and have Simple Search on the page.

I had to manually add null check to line 131, and because I checked the length I also had to add a Null Check to line to 228.



`import '../application/application_widget.dart';
import '../backend/backend.dart';
import '../components/applications_filter_comp_widget.dart';
import '../flutter_flow/flutter_flow_animations.dart';
import '../flutter_flow/flutter_flow_icon_button.dart';
import '../flutter_flow/flutter_flow_theme.dart';
import '../flutter_flow/flutter_flow_util.dart';
import 'package:easy_debounce/easy_debounce.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:text_search/text_search.dart';

class ApplicationListWidget extends StatefulWidget {
  const ApplicationListWidget({
    Key? key,
    this.applicationsList,
  }) : super(key: key);

  final List<ApplicationsRecord>? applicationsList;

  @override
  _ApplicationListWidgetState createState() => _ApplicationListWidgetState();
}

class _ApplicationListWidgetState extends State<ApplicationListWidget>
    with TickerProviderStateMixin {
  List<ApplicationsRecord> simpleSearchResults = [];
  TextEditingController? textController;
  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    textController = TextEditingController();
  }

  @override
  void dispose() {
    textController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      backgroundColor: Color(0xFFF1F4F8),
      appBar: AppBar(
        backgroundColor: Color(0xFF4B39EF),
        automaticallyImplyLeading: true,
        title: SvgPicture.network(
          'https://uploads-ssl.webflow.com/5edfdb0f7e71f61d7b6a80e6/63251220cd40a81aa2ec180a_vousconlogowhite.svg',
          width: MediaQuery.of(context).size.width * 0.5,
          fit: BoxFit.contain,
        ),
        actions: [],
        centerTitle: false,
        elevation: 2,
      ),
      body: SafeArea(
        child: GestureDetector(
          onTap: () => FocusScope.of(context).unfocus(),
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.max,
              children: [
                Padding(
                  padding: EdgeInsetsDirectional.fromSTEB(16, 12, 16, 0),
                  child: Row(
                    mainAxisSize: MainAxisSize.max,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Applications',
                        style: FlutterFlowTheme.of(context).subtitle1.override(
                              fontFamily: 'Outfit',
                              color: Color(0xFF14181B),
                              fontSize: 18,
                              fontWeight: FontWeight.normal,
                            ),
                      ),
                      FlutterFlowIconButton(
                        borderColor: Colors.transparent,
                        borderRadius: 30,
                        borderWidth: 1,
                        buttonSize: 40,
                        icon: Icon(
                          Icons.tune_rounded,
                          color: Color(0xFF57636C),
                          size: 20,
                        ),
                        onPressed: () async {
                          await showModalBottomSheet(
                            isScrollControlled: true,
                            backgroundColor: Colors.white,
                            context: context,
                            builder: (context) {
                              return Padding(
                                padding: MediaQuery.of(context).viewInsets,
                                child: Container(
                                  height:
                                      MediaQuery.of(context).size.height * 0.5,
                                  child: ApplicationsFilterCompWidget(),
                                ),
                              );
                            },
                          ).then((value) => setState(() {}));
                        },
                      ),
                    ],
                  ),
                ),
                Padding(
                  padding: EdgeInsetsDirectional.fromSTEB(16, 12, 16, 0),
                  child: Row(
                    mainAxisSize: MainAxisSize.max,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: textController,
                          onChanged: (_) => EasyDebounce.debounce(
                            'textController',
                            Duration(milliseconds: 2000),
                            () async {
                              setState(() {
                                simpleSearchResults = TextSearch(
                                  widget.applicationsList!
                                      .map(
                                        (record) => TextSearchItem(record, [
                                          record.firstName!,
                                          record.lastName!
                                        ]),
                                      )
                                      .toList(),
                                )
                                    .search(textController!.text)
                                    .map((r) => r.object)
                                    .toList();
                              });
                            },
                          ),
                          autofocus: true,
                          obscureText: false,
                          decoration: InputDecoration(
                            hintText: 'Search by name...',
                            hintStyle: FlutterFlowTheme.of(context).bodyText2,
                            enabledBorder: UnderlineInputBorder(
                              borderSide: BorderSide(
                                color: Colors.black,
                                width: 1,
                              ),
                              borderRadius: const BorderRadius.only(
                                topLeft: Radius.circular(4.0),
                                topRight: Radius.circular(4.0),
                              ),
                            ),
                            focusedBorder: UnderlineInputBorder(
                              borderSide: BorderSide(
                                color: Colors.black,
                                width: 1,
                              ),
                              borderRadius: const BorderRadius.only(
                                topLeft: Radius.circular(4.0),
                                topRight: Radius.circular(4.0),
                              ),
                            ),
                            errorBorder: UnderlineInputBorder(
                              borderSide: BorderSide(
                                color: Color(0x00000000),
                                width: 1,
                              ),
                              borderRadius: const BorderRadius.only(
                                topLeft: Radius.circular(4.0),
                                topRight: Radius.circular(4.0),
                              ),
                            ),
                            focusedErrorBorder: UnderlineInputBorder(
                              borderSide: BorderSide(
                                color: Color(0x00000000),
                                width: 1,
                              ),
                              borderRadius: const BorderRadius.only(
                                topLeft: Radius.circular(4.0),
                                topRight: Radius.circular(4.0),
                              ),
                            ),
                            suffixIcon: Icon(
                              Icons.search,
                              color: Color(0xFF757575),
                              size: 22,
                            ),
                          ),
                          style: FlutterFlowTheme.of(context).bodyText1,
                          keyboardType: TextInputType.name,
                        ),
                      ),
                    ],
                  ),
                ),
                Padding(
                  padding: EdgeInsetsDirectional.fromSTEB(0, 12, 0, 44),
                  child: Builder(
                    builder: (context) {
                      final applicationsList = widget.applicationsList
                          ?.where((e) =>
                              ((e.status! == FFAppState().statusFilter) ||
                                  (FFAppState().statusFilter == null ||
                                      FFAppState().statusFilter == '')) &&
                              ((e.chooseYourVousconTeam! ==
                                      FFAppState().teamFilter) ||
                                  (FFAppState().currentTeam == null ||
                                      FFAppState().currentTeam == '')) &&
                              ((e.currentChurch! ==
                                      FFAppState().churchFilter) ||
                                  (FFAppState().churchFilter == null ||
                                      FFAppState().churchFilter == '')) &&
                              (e.status! != 'Submitted'))
                          .toList();
                      return ListView.builder(
                        padding: EdgeInsets.zero,
                        primary: false,
                        shrinkWrap: true,
                        scrollDirection: Axis.vertical,
                        itemCount: applicationsList!.length,
                        itemBuilder: (context, applicationsListIndex) {
                          final applicationsListItem =
                              applicationsList[applicationsListIndex];
                          return Padding(
                            padding:
                                EdgeInsetsDirectional.fromSTEB(16, 0, 16, 12),
                            child: Container(
                              width: 100,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                boxShadow: [
                                  BoxShadow(
                                    blurRadius: 5,
                                    color: Color(0x1F000000),
                                    offset: Offset(0, 2),
                                  )
                                ],
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.max,
                                children: [
                                  Expanded(
                                    child: InkWell(
                                      onTap: () async {
                                        setState(() =>
                                            FFAppState().currentApplicationRef =
                                                applicationsListItem.reference);
                                        await Navigator.push(
                                          context,
                                          PageTransition(
                                            type:
                                                PageTransitionType.bottomToTop,
                                            duration:
                                                Duration(milliseconds: 300),
                                            reverseDuration:
                                                Duration(milliseconds: 300),
                                            child: ApplicationWidget(),
                                          ),
                                        );
                                      },
                                      child: Column(
                                        mainAxisSize: MainAxisSize.max,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Padding(
                                            padding:
                                                EdgeInsetsDirectional.fromSTEB(
                                                    8, 12, 16, 0),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.max,
                                              mainAxisAlignment:
                                                  MainAxisAlignment.start,
                                              children: [
                                                Padding(
                                                  padding: EdgeInsetsDirectional
                                                      .fromSTEB(0, 0, 4, 0),
                                                  child: Text(
                                                    applicationsListItem
                                                        .firstName!,
                                                    style: FlutterFlowTheme.of(
                                                            context)
                                                        .title3
                                                        .override(
                                                          fontFamily: 'Outfit',
                                                          color:
                                                              Color(0xFF14181B),
                                                          fontSize: 20,
                                                          fontWeight:
                                                              FontWeight.w500,
                                                        ),
                                                  ),
                                                ),
                                                Text(
                                                  applicationsListItem
                                                      .lastName!,
                                                  style: FlutterFlowTheme.of(
                                                          context)
                                                      .title3
                                                      .override(
                                                        fontFamily: 'Outfit',
                                                        color:
                                                            Color(0xFF14181B),
                                                        fontSize: 20,
                                                        fontWeight:
                                                            FontWeight.w500,
                                                      ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Padding(
                                            padding:
                                                EdgeInsetsDirectional.fromSTEB(
                                                    8, 0, 0, 0),
                                            child: Column(
                                              mainAxisSize: MainAxisSize.max,
                                              crossAxisAlignment:
                                                  CrossAxisAlignment.start,
                                              children: [
                                                Text(
                                                  valueOrDefault<String>(
                                                    applicationsListItem
                                                                .currentChurch ==
                                                            'Other'
                                                        ? applicationsListItem
                                                            .churchNameOther
                                                        : applicationsListItem
                                                            .currentChurch,
                                                    'Not Provided',
                                                  ),
                                                  style: FlutterFlowTheme.of(
                                                          context)
                                                      .bodyText2
                                                      .override(
                                                        fontFamily: 'Outfit',
                                                        color:
                                                            Color(0xFF57636C),
                                                        fontSize: 12,
                                                        fontWeight:
                                                            FontWeight.normal,
                                                      ),
                                                ),
                                                Text(
                                                  applicationsListItem
                                                      .chooseYourVousconTeam!,
                                                  style: FlutterFlowTheme.of(
                                                          context)
                                                      .bodyText2
                                                      .override(
                                                        fontFamily: 'Outfit',
                                                        color:
                                                            Color(0xFF57636C),
                                                        fontSize: 12,
                                                        fontWeight:
                                                            FontWeight.normal,
                                                      ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Padding(
                                            padding:
                                                EdgeInsetsDirectional.fromSTEB(
                                                    8, 0, 16, 12),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.max,
                                              mainAxisAlignment:
                                                  MainAxisAlignment.end,
                                              children: [
                                                Text(
                                                  applicationsListItem.status!,
                                                  style: FlutterFlowTheme.of(
                                                          context)
                                                      .subtitle1
                                                      .override(
                                                        fontFamily: 'Outfit',
                                                        color:
                                                            Color(0xFF4B39EF),
                                                        fontSize: 18,
                                                        fontWeight:
                                                            FontWeight.normal,
                                                      ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          );
                        },
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
`

**Comment by agreaves** [comment]
Hi @kjoyceee, could you please generate and paste the bug report code here? All you have to do is navigate to the page that is causing issues, and right click anywhere on the widget tree and select the option at the bottom. That will greatly help us fix the issue. Thanks! 🙂

**Comment by kennette21** [comment]
also experiencing this issue, reported on the community: https://community.flutterflow.io/c/bugs/filtering-list-parameter-passed-into-component-results-in-null-saftey-error-bug.

seems like people here are on the right track! looking forward to fix!

**Comment by agreaves** [comment]
Hey folks! Sorry for the delay on this one, it's an old bug but we've finally fixed it! You should see this fix upon our next deploy. Thanks again for all the helpful info 🙂

**Comment by kennette21** [comment]
thanks @agreaves ! i am still experiencing the bug, is it possible the release you speak of is not out yet?

**Comment by agreaves** [comment]
Hey! It should be released now. Are you sure you're on the latest version? Can you add a bug report code for the project you're experiencing issues with?

**Comment by kennette21** [comment]
I am on FF v3.0 released Dec 27th, and the issue is still happening. 

Here is the bug report code generated by the ListView causing the Null error:
IT4slsjfz49On7xa1s7yccFB/SEWH2l+U4E0scp8WQgafIjJP4kQPPWkbRBpTcPndHNUeUSmmnEDpc7KiOHXN/ECGAqcG4B/ws1AdQLjcF27Q8HfU/HUACkbeacOQSj6

My issue is slightly different than the one in this issue, but I thought the solution would address both. I describe my issue fully here:  https://community.flutterflow.io/c/bugs/filtering-list-parameter-passed-into-component-results-in-null-saftey-error-bug

The issue happens if you try to filter the List passed into a component before generating children. The generated code is not null safe with the added filter, but without the filter it is.

**Comment by kennette21** [comment]
@agreaves if you would like me to open a new issue in github please let me know!
