### ISSUE TITLE
Global Property "Is User Logged In" does not work with Supabase Auth

### ISSUE THREAD

**Issue by EJS00102** [FlutterFlow/flutterflow-issues#822]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you add a widget to a page and you set conditional visibility using "Is User Logged In" you cannot run the app in test mode as it fails to build.

### Expected Behavior

If using Supabase Auth and you use conditional visibility with "Is User Logged In" it should work.

### Steps to Reproduce

1. Use Supabase Auth
2. Create a new page
3. Add widget
4. Put conditional visibility on widget using "Is User Logged In"
5. Try to run in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocNc187qdcFAhQAkQzM8bYJMl9dTQgEdGKLrOootP+r+VE5eXc+HfFFYOWKgrEw00a3rvuDLKscFCw6taINo+c5cFALdWkSgVIzUDqqOOEBDL9lgfGaj0buFpSMnFM9aV0Iiw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to use Supabase Auth, but this bug is making it impossible to test.

### Visual documentation

<img width="1107" alt="Screenshot 2023-04-28 at 12 51 29" src="https://user-images.githubusercontent.com/52255287/235132458-02befc17-2261-4d4a-819f-6057695de35b.png">
<img width="1034" alt="Screenshot 2023-04-28 at 12 51 36" src="https://user-images.githubusercontent.com/52255287/235132456-16c737d2-2860-4720-b81c-a9aba546c5e2.png">
<img width="1010" alt="Screenshot 2023-04-28 at 13 11 54" src="https://user-images.githubusercontent.com/52255287/235133055-f62713ff-5304-4562-824c-ad6b6a9ddd8c.png">

### Environment

```markdown
- FlutterFlow version: Version 1.1.64 (1.1.64)
- Platform: All
- Browser name and version: Version 16.3 (18614.4.6.1.6)
- Operating system and version affected: Venture 13.2.1 (22D68)
```

**Comment by EJS00102** [comment]
Here is some more context:
<img width="1344" alt="Screenshot 2023-04-28 at 13 15 17" src="https://user-images.githubusercontent.com/52255287/235133698-aed4efb2-81d2-416b-8251-fc501074f6f1.png">

**Comment by hariprasadms** [comment]
Hi @EJS00102 - Thanks for reporting the issue. I can reproduce the issue in my projects as well. It should be fixed in up coming updates.

**Comment by EJS00102** [comment]
Awesome. It looks like you can do a "workaround" by checking the authenticated user's "id" and if it is set and not empty (i.e logged in) use that as the condition.

**Comment by idea-garage** [comment]
Is this issue figured out? I tested and looks working fine.

**Comment by EJS00102** [comment]
Seems like it is working fine now? Maybe this bug can be closed.
