### ISSUE TITLE
Web deployment error

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#823]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Fails Web deployment with following error:

Error: Command failed: flutter pub get --quiet
Because streeto depends on package_info_plus ^1.0.6 which depends on package_info_plus_platform_interface ^1.0.2, package_info_plus_platform_interface ^1.0.2 is required.
So, because streeto depends on package_info_plus_platform_interface 2.0.1, version solving failed.
pub get failed
command: "/sdks/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/sdks/flutter",
  "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:get",
  "PUB_CACHE": "/opt/.pub-cache",
}
exit code: 1

### Expected Behavior

Publish on web without error

### Steps to Reproduce

Web Publish -> Publish

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMfWOdEket+EA0hfZDtBLATdczCbVVLYtfmS31DPmH+sEkfwvDpkd/1F+04YU+BUaZTzL5XQQ3jVlGhRcmpELqeW3ZBBeFmJ0yi0cHYnRFCNbBidEYk2mGuffCdG3qCf9qOYwx5e6fDbOY=

### Context

Project that commonly piblishes on web

### Visual documentation

![Web publish error](https://user-images.githubusercontent.com/50183743/235189139-f6c68085-dde8-4087-9503-9c61f874487a.jpg)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Win / Mac
```

**Comment by pstatile** [comment]
It also happens in the iOS Deployment:

Codemagic Deploy Output
Failed Step: Get Flutter packages

Running "flutter pub get" in flutter_tools...
Resolving dependencies in ../programs/flutter/packages/flutter_tools...
  _fe_analyzer_shared 50.0.0 (59.0.0 available)
  analyzer 5.2.0 (5.11.1 available)
  archive 3.3.2 (3.3.7 available)
  args 2.3.1 (2.4.0 available)
  async 2.10.0 (2.11.0 available)
  built_value 8.4.2 (8.4.4 available)
  checked_yaml 2.0.1 (2.0.2 available)
  collection 1.17.0 (1.17.1 available)
  completion 1.0.0 (1.0.1 available)
  coverage 1.6.1 (1.6.3 available)
  dds 2.5.0 (2.7.9 available)
  dds_service_extensions 1.3.1 (1.3.3 available)
  devtools_shared 2.18.0 (2.23.0 available)
  dwds 16.0.2+1 (19.0.0 available)
  fixnum 1.0.1 (1.1.0 available)
  frontend_server_client 3.1.0 (3.2.0 available)
  html 0.15.1 (0.15.2 available)
  intl 0.17.0 (0.18.1 available)
  io 1.0.3 (1.0.4 available)
  js 0.6.5 (0.6.7 available)
  json_annotation 4.7.0 (4.8.0 available)
  logging 1.1.0 (1.1.1 available)
  matcher 0.12.13 (0.12.15 available)
  meta 1.8.0 (1.9.1 available)
  mime 1.0.2 (1.0.4 available)
  multicast_dns 0.3.2+2 (0.3.2+3 available)
  native_stack_traces 0.5.2 (0.5.5 available)
  node_preamble 2.0.1 (2.0.2 available)
  path 1.8.2 (1.8.3 available)
  petitparser 5.1.0 (5.4.0 available)
  pubspec_parse 1.2.1 (1.2.2 available)
  source_maps 0.10.11 (0.10.12 available)
  source_span 1.9.1 (1.10.0 available)
  sse 4.1.1 (4.1.2 available)
  test 1.22.0 (1.24.2 available)
  test_api 0.4.16 (0.5.2 available)
  test_core 0.4.20 (0.5.2 available)
  usage 4.1.0 (4.1.1 available)
  vm_service 9.4.0 (11.4.0 available)
  web_socket_channel 2.2.0 (2.4.0 available)
  webdriver 3.0.1 (3.0.2 available)
  xml 6.2.2 (6.3.0 available)
Got dependencies in ../programs/flutter/packages/flutter_tools!
Resolving dependencies...
Because streeto depends on package_info_plus ^1.0.6 which depends on package_info_plus_platform_interface ^1.0.2, package_info_plus_platform_interface ^1.0.2 is required.
So, because streeto depends on package_info_plus_platform_interface 2.0.1, version solving failed.
pub finished with exit code 1


Build failed :|
Step 7 script `Get Flutter packages` exited with status code 1

**Comment by bulgariamitko** [comment]
Are you using any custom code?

**Comment by pstatile** [comment]
In general in my app, YES. But nothing changed these last days. I have
recently (few days) published on mobile without problems. Since yesterday
it is not working.

**Comment by bulgariamitko** [comment]
Ok let's see what FF team has to say about that, but I will assume this is because of the custom code that you use in your app. Sometimes when you use custom code it interferes with the source code of your app.

**Comment by pstatile** [comment]
I deployed one day before, changed two simple things that had nothing to do
with custom code.

**Comment by pstatile** [comment]
I managed to change Old Custom Code that had a dependency that made trouble
today. Solved, thanks!

**Comment by pstatile** [comment]
Solved, it was a dependency problem, even though I did not change that in the last few days...
