### ISSUE TITLE
Can't See Sub-collection Section in Flutterflow CMS 

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#828]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a sub-collection in my Flutterflow projects, but I can't see the section in Flutterflow CMS.
I tried it in another project and so far same response.

Along with this, I tried creating a collection from app and no document is created in Firebase.

### Expected Behavior

The subcollection section should show where I can add documents manually or preview the changed made to the subcollection.changes

### Steps to Reproduce

1. Create a Project
2. Connect Firestore
3. Create Collection
4. Add- Sub Collection
5. Sub-Collection Tabs Don't Shows in Manage Content

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40j8nfvJNPm8Nf1arAcvpajic5Jml7aoER0+5BaCosfZT2BLMcec/RVERvXuLgdFZUP020mWoW0ML3jePpEcE3EyiuGqZH+aVfEAGWQmSnV8jXFJWgeXFTPNxQfGaC5p6NgxBQIbNhWVYh2V+MfuSRVjTsQ7n7PldND6/LZO4=

### Context

I want to store information in my sub-collection based on the information in the Parent collection.

However, the sub-collection is not working as expected.

### Visual documentation

Video Attached
https://www.loom.com/share/3fd9b26d5e7745dba81852cadfd9f55a

### Additional Info

https://www.loom.com/share/3fd9b26d5e7745dba81852cadfd9f55a

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: 112.0.5615.137 (Official Build) (arm64)
- Operating system and version affected: MacOS Ventura 13.3.1 (22E261)
```

**Comment by hariprasadms** [comment]
Hi @Dev-Muhammad-Junaid - Sub collections are not visible in FlutterFlow CMS at the movement. I can mark this as feature request. Thanks

**Comment by Dev-Muhammad-Junaid** [comment]
Okay. But i am still not able to create document that is visible nor in Flutterflow CMS or Firestore Database.

Nothing gets updated there.
