### ISSUE TITLE
Custom Widget rendering problem with 3rd Party widget

### ISSUE THREAD

**Issue by RosilBelli** [FlutterFlow/flutterflow-issues#829]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My custom widget is built with SfDataGrid from Syncfusion but there is a rendering problem on its header columns. The header icon widgets is not being appropriately rendered. 

By running the same widget code on VSCode there is no rendering problem.

### Expected Behavior

Correct Icons rendering

### Steps to Reproduce

1. Create a custom widget and add the dependency syncfusion_flutter_datagrid: ^21.1.41
2. Instantiate a SfDataGrid with some columns and enable sorting and filtering
3. Use this widget on any page - header icons will not be rendered as expected.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiMmBxIt2m/VG0ISJcvpop2MXQ08cTL4zlO1HcxAYGO/yPbJ/ZM/OVEtvXcOgTENhHFWkrE8FpN77huzLIPY6YAutG6JR/7hQFgLgLHq8RYy6Ec6CREd8EZ9bIEiZ0aWOnh5DAMxeR3AW3V2QI++8YCvcGZu/Zwh9f6PHaOI=

### Context

This is an UI problem and does not put on risk any logic or rule.
But affects my customer usage.

### Visual documentation

VS Code rendering:
![VSCode](https://user-images.githubusercontent.com/5960968/235359162-af1b37ec-e9db-4dcc-890c-c8b7cfcd2116.png)

FF rendering:
![flutterflow](https://user-images.githubusercontent.com/5960968/235359140-5ddf310b-4fbe-4488-ab16-a61fbd76815c.png)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: 3.7.12
- Browser name and version: Chrome 112.0.5615.86
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
Hi @RosilBelli - Thanks for submitting the issue. This issue tracker is intended for general bugs that are applicable to all users. Because this issue appears to be specific to your project with a specific third party package and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/). Thanks

**Comment by wenkaifan0720** [comment]
Hi. Since this issue is related to 3rd party package and only seems to happen in test mode, we will not be working on fixing it and I will close it for now.
