### ISSUE TITLE
Long element name set - Impossible to edit again

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#83]
as Edit_button gets hidden behind Button_comment. SS attached. 
![FF Bug Long element name cant be edited](https://user-images.githubusercontent.com/117246043/199383648-daa25e17-6f60-41bf-b86e-d4f544ea3fe3.png)

All double-click element names to activate edit.

**Comment by agreaves** [comment]
Thank very much for this report. This has been fixed and will be deployed in our next release!

**Comment by palmdeskApp** [comment]
Thanks. That was quick.
