### ISSUE TITLE
Thai Text Widget wraping Issue

### ISSUE THREAD

**Issue by abyssmaljib** [FlutterFlow/flutterflow-issues#830]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am experiencing a text wrapping issue in FlutterFlow with some long text strings. Instead of displaying the entire text string on a single line, it splits and wraps across multiple lines unpleasantly. For example, I expect the text to appear as:
"เรารับต่อมาจาก รพ สิรินธร"
However, it is being displayed as:
"เรารับต่อมาจากรพ สิ
ริน
ธร"

This issue only appears in the Thai language in web browsers. The line is broken, and the sentence is split into multiple lines when I try to press enter to go to the new line. Please take a look at my attachment. Thanks

### Expected Behavior

When I press enter the new line, the sentence shouldn't split.

### Steps to Reproduce

1. Add a text widget or text field widget.
2. Run and input Thai text and try to enter the new line.

That's it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oj8jf34p2pbxH1rXuY+9ahSQXNU9/RLsemspBay0jF7KuDLMqY8/RVERuTe2hSm9DPmKar2oW0M7wioXxUMIVNTucc7Z4yJdQEAvhVTi6M7HWFJWgOEZAJ8dhfG6g1reFvhJBANpadGwew1z7GNiXUgHXHu6zNW0sDq/LZO4=

### Context

I'm Thai, and I just need Thai text to appear appropriately on the web browser.

### Visual documentation

https://user-images.githubusercontent.com/119910195/235360385-d18a16b0-0028-4d8c-a2c4-234496d0ed4d.mp4

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.12
- Platform: Web, Window
- Browser name and version: Brave, Chrome
- Operating system and version affected: Window 11
```

**Comment by hariprasadms** [comment]
Hi @abyssmaljib - Thanks for submitting the issue. I can reproduce the issue. As it is specific to one language type, I can mark the issue as project specific. 

https://user-images.githubusercontent.com/17435678/235433294-2d2f7910-7dfc-4da8-bfbe-9eb6bb1bf82c.mp4

**Comment by abyssmaljib** [comment]
> Hi @abyssmaljib - Thanks for submitting the issue. I can reproduce the issue. As it is specific to one language type, I can mark the issue as project specific.
> 
>  2023-05-01_10-11-00.mp4

Thanks

**Comment by teerapat-beyonndcode-academy** [comment]
Could you please provide the estimate when the issue will be resolved?

**Comment by abyssmaljib** [comment]
Any Update? Almost one month now.

Seem like it is not only my issue. A lot of Thai people face this issue too. At least an update on something will be much appreciated.

**Comment by teerapat-beyonndcode-academy** [comment]
Any update is much appreciated as this bug is preventing us from putting our app on production

**Comment by wenkaifan0720** [comment]
Hi @teerapat-beyonndcode-academy. Sorry for the late reply. This is likely caused by a Flutter rendering issue as we don't have any special treatment for any language on our side. Is this issue only happening on the web? One thing I would suggest you to try is to toggle on Use Canvaskit (beta) if you are using web publish. Let me know if this fixes the issue.

**Comment by abyssmaljib** [comment]
> toggle on Use Canvaskit (beta)

Hi, Can you show me how to do that "toggle on Use Canvaskit (beta)" ?? 

@vishalagarwal2 @joshensongric I want to hear an update on this issue. Are you fixing it or is it just an issue on only one language so it is OK to ignore? If you are not fixing it at least let me know. I've been waiting since forever.

Thanks.

**Comment by takashiff** [comment]
Hello, this looks to be a Flutter-specific issue rather than FlutterFlow specific. Please see the following threads for updates:
https://github.com/flutter/flutter/issues/127379
https://github.com/flutter/flutter/issues/127379
