### ISSUE TITLE
I can't see some buttons on UI designer on my 4k monitor

### ISSUE THREAD

**Issue by itstetriser** [FlutterFlow/flutterflow-issues#831]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello,

Some buttons isn't visible on my 4k monitor. I try to press those buttons without seeing them by using 'Tab' key. For example, while trying to add an action to swippable deck, no button is visible.

### Expected Behavior

The buttons should be visible regardless of screen resolution.

### Steps to Reproduce

1. Add a swippable deck
2. Try to add an action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzMmBw5RPxMtH176JYcIxhWAvOU8cT+Qz0e5xYxQgGJDtBIgIP/TBSFBUOLSmY2xiPGKaiT4X/MrrveGfGvcrBzKeGL5Czap9VTmUWmalMbbRDL63b3dQBphmC1SC0ZmNmRNTNshsc3gH3HGMfeq+aDTsJITvOFUZBuaeXdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to add an action to a swippable deck.

### Visual documentation

![bug](https://user-images.githubusercontent.com/132266715/235444817-1d28ab5f-0932-4057-a275-7433a3e44a0e.png)
![bug2](https://user-images.githubusercontent.com/132266715/235444830-d008fb5f-1c17-4726-9310-9a81708ffa4d.png)

### Environment

```markdown
- FlutterFlow version: Final version 
- Platform: Windows PC 
- Browser name and version: Chrome and Opera
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @itstetriser - Thanks for sharing the issue details. Looking at the images, I think your screen resolution is causing the issue. Try to change the screen resolution and see if that can help you. Thanks

**Comment by hariprasadms** [comment]
We assume you discovered a solution to the issue or that latest FlutterFlow releases fixed it. Since there are no ongoing active conversations in the issue, we are closing the issue.
