### ISSUE TITLE
API Endpoint is not permitted to be a single single slash

### ISSUE THREAD

**Issue by sbarber-dsi** [FlutterFlow/flutterflow-issues#832]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On the Define API call page it will not permit you to switch from Call Definition to Response & Test with an empty API Endpoint nor with a single slash as API Endpoint but APIs can have a default endpoint on the root so an empty API Endpoint and single slash are both valid settings.

### Expected Behavior

Accept empty API Endpoint or single slash for API Endpoint
Switch to Response & Test
Execute API accordingly

### Steps to Reproduce

Clear API Endpoint
Click on Response & Test
Error is shown

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjcrlvJNIseFa+Kr+bsBB/WI4GDs8RJEz0sJ+bCs9f5zpPZsMZ876PxZvOPG9SmxDMWemp14e/vDwheDxJu06ByqWGL441s5ybD3wLX+XMKmTF7uWYUdCJJlgfxCP3ImzvCJDPrNZLV4k3EzzJ9/IUnbYQpTNC3o8Sq/LZO4=

### Context

Prevents us from testing root API call
Work-around is to put in two slashes - it also rejects one slash

### Visual documentation

![image](https://user-images.githubusercontent.com/89945338/235450164-5efd6c15-6470-4458-88fa-0d93a2cc08a2.png)

### Environment

```markdown
- FlutterFlow version: v3.1 (flutter 3.7.12)
- Platform: All
- Browser name and version: Firefox 112.0.1
- Operating system and version affected: Ubuntu 22.04, affects all
```

**Comment by sbarber-dsi** [comment]
The expected behavior is not correct and does not follow OpenAPI specifications.
https://swagger.io/specification/

**Comment by sbarber-dsi** [comment]
Remains a but and not a feature request.

**Comment by hariprasadms** [comment]
Hi! Thank you for submitting a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. You can find it in the "Help" menu inside of the FlutterFlow. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas!

**Comment by sbarber-dsi** [comment]
This is not a feature request. This is a bug.
