### ISSUE TITLE
Scan Barcode Bug

### ISSUE THREAD

**Issue by engmosaab** [FlutterFlow/flutterflow-issues#834]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My App language is Arabic, it has a Right to Left layout.
I’m using the “Scan Barcode” action.
The problem is in the scan barcode page, the “Cancel” button does not appear in the correct place, it appears behind the camera flip button !!
I think this is due to the Right to Left layout.

### Expected Behavior

regardless if it's RTL or LTR... the “Cancel” button should appear clearly no matter if it's on the right or left side. or you can solve it by remove the flip camera button, as its not less important that “Cancel” button.

### Steps to Reproduce

Create app with a language Right to Left layout (For example Arabic)
Add a “Scan Barcode” action.
Check the app on iphone device.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4givLqx5N2ob1E7aX6bu9VoCAQKVw3Rpc0sd4bGA0dCJzuPLMQdvWkYRZuZN/kd0FIJESmmkAC/63wkvzpEe5eCwWZUaZxyqlybT3wYGKge5OBPKWRPXB8ROJRfkDA5rSznCUlNbBeR3Ab1FyUH+jLbCnDJoz3ImdISq/LZO4=

### Context

can you please help to fix this either by hiding the "flip camera" button or place the "cancel" button on the right side.

### Visual documentation

You can see the screenshot on the following link:
https://yourimageshare.com/ib/YY9SkDweeD

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iOS and Android
Browser name and version (web): NA
Operating system and version (desktop): NA
```

**Comment by wenkaifan0720** [comment]
Hi @engmosaab. The scan barcode page is designed by the `flutter_barcode_scanner` package and we don't have control over it's layout unfortunately. The only workaround I can come up with is to change the app's language to some LTR language before you start the scan, and change back to Arabic after the scan.

**Comment by rzambroni** [comment]
Hey @engmosaab, were you able to solve this with the provided workaround? 
I'm closing this ticket as we don't have control over the barcode_scanner package.
