### ISSUE TITLE
I Cannot right click on the flutterflow web creator

### ISSUE THREAD

**Issue by SudgeFunday** [FlutterFlow/flutterflow-issues#836]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot right-click on flutterflow in general. So im not able to delete anything.Flutterflow

### Expected Behavior

I expected when pressing control-click on mac it would allow me to delete widgets and such but im not able to. Control-click

### Steps to Reproduce

1. I go to the  widget tree, and try to right click 
2.  nothing happens 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

On the app creator itself

### Context

I havent been able to delete, duplicate, or get a bug report code,etc

### Visual documentation

i was pushing control click 

https://user-images.githubusercontent.com/89611733/235540769-4553e35a-90e9-4e72-83f6-1e141594db44.mov

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: web and macOS Desktop
- Browser name and version: Version 112.0.5615.137 
- Operating system and version affected: Ventura 13.2.1
```

**Comment by hariprasadms** [comment]
Hi @SudgeFunday - I am not able to re-produce the issue. It is working as expected in my projects. Can you please bug report code of the project please. Thanks

**Comment by SudgeFunday** [comment]
the issue however is not just pertaining to a specific project but
pertaining to all flutterflow projects, as i have a problem with the app
creator itself, as its not allowing me to right click on a mac book or Mac
desktop
