### ISSUE TITLE
Flutterflow view doesn't update when clicking on "Make User Uploads Private"

### ISSUE THREAD

**Issue by BirgitPohl** [FlutterFlow/flutterflow-issues#838]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Flutterflow View Firebase Storage rules don't get updates.

First the Flutterflow Firebase Setup page. If I click on "Make User Uploads Private" it does not visually update immediately. It does so only if I re-load the part of the screen. For example, if I press "Manage Outside of Flutterflow" that hides the other part and when re-initiated it loads it again.

Why do I need to have that immediately? Because I want to deploy the rules to Firebase Storage. It would be out of sync.

### Expected Behavior

Flutterflow view does update when clicking on "Make User Uploads Private"

### Steps to Reproduce

Click "Make User Uploads Private"
Observe that nothing happens.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

xxx

### Context

I'd like to deploy the new rules. This only would work, if the view updates.

### Visual documentation

https://user-images.githubusercontent.com/4340405/235603950-3ecd0fbe-f5b8-4403-9edc-94407c671bf7.mov

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Mac OS X Ventura.
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by organicnz** [comment]
Hi, @BirgitPohl.

Thanks for another one hehe. Also reproduced this issue 🙂

[Video](https://www.loom.com/share/b5d4410d3b034251b24065daf45b26ec)

OS: macOS Ventura 13.1
Chrome: Version 112.0.5615.137 (Official Build) (x86_64)

**Comment by wenkaifan0720** [comment]
Hi @BirgitPohl. This issue will be fixed in the next update. Thanks for reporting.
