### ISSUE TITLE
Deploy Firestore Rules Issues

### ISSUE THREAD

**Issue by BirgitPohl** [FlutterFlow/flutterflow-issues#839]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Diff is not scrollable
The Diff view is not scrollable.

### Copy button doesn't work
The copy button in the Before and After view doesn't copy the info into the clipboard. I have my previous content on the clipboard.

### Diff is not scrollable
I can scroll the diff view to fully see the diff.

### Copy button doesn't work
The copy icon copies info onto the clipboard.

### Diff is not scrollable
I can scroll the diff view to fully see the diff.

### Copy button doesn't work
Have something to deploy.
Click the deploy button. View the Before and After screens.
Try copying with the copy icon and paste it to a place of your liking.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

xxx

### Diff is not scrollable
I'd like to see the full diff.

### Copy button doesn't work
I originally wanted to see the full diff, but since it didn't work, So I tried the 'copy' icon on Before and After screens to create my own diff, which didn't work.

### Diff is not scrollable

https://user-images.githubusercontent.com/4340405/235612312-0505bb95-f5e1-4319-a7c6-58916d50af4a.mov

### Copy button doesn't work

https://user-images.githubusercontent.com/4340405/235610820-914057df-2727-4d6b-896c-b2f8ce7095c4.mov

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: MaxOS X Ventura
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issues, @BirgitPohl! Both will be fixed in the next update.
