### ISSUE TITLE
Create Team website validation is rejecting a valid site

### ISSUE THREAD

**Issue by tristdrum** [FlutterFlow/flutterflow-issues#84]
To reproduce:

1. Click 'Create Team'
2. Insert `http://champ.foundation/` into the `Website/Domain` field
3. Notice the validation error

Note: our website is currently being parked by GoDaddy.

<img width="640" alt="Screenshot 2022-11-02 at 08 22 52" src="https://user-images.githubusercontent.com/27028099/199413797-5c985913-ab3a-4a0d-bddd-d23b21e3f938.png">

**Comment by organicnz** [comment]
@tristdrum have you tried adding it without HTTPS by any chance? :)

**Comment by bulgariamitko** [comment]
Try adding it with https instead of http

**Comment by agreaves** [comment]
Hi @tristdrum, this should be fixed next deploy!

**Comment by tristdrum** [comment]
Thank you @agreaves. 🎉
