### ISSUE TITLE
Team api's unassigned and can't be added back

### ISSUE THREAD

**Issue by DeltaForce007** [FlutterFlow/flutterflow-issues#840]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After you latest upgrade all of my third party api's that are part of my team org was unassigned from my project. When I try assigned them back it won't let me select the correct api's from the group selected and won't allow me to select any from the list. 

I have tried to recreate the action fro the api call and can still not select an api from the correct list and defaults to the incorrect api. 

This has impacted every api call in my project. (54 of them) and is the same thing for every one of my projects.

![image](https://user-images.githubusercontent.com/23420174/235676995-34cfd1c4-f3a6-4ef3-9bf6-b239e20dc1fc.png)

![image](https://user-images.githubusercontent.com/23420174/235677076-0aca6465-b59c-4723-872f-3b5153165f69.png)

### Expected Behavior

That my api calls that I have set up as still assigned and works and that I can create actions with api calls from my team org

### Steps to Reproduce

1. Got to an existing api call that is now unassigned
2. try re-assign it
3. It gives the wrong api call

1. Create new action
2. select api call 
3. select from api group
4. wrong api list is in the group

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ddd

### Context

I am trying to continue building my apps but can no longer progress as can't connect any apis'

### Visual documentation

![image](https://user-images.githubusercontent.com/23420174/235680594-60d1ba0f-dc68-4dd5-8a12-e5c471caf542.png)

![image](https://user-images.githubusercontent.com/23420174/235680663-73857253-b6f7-4830-8367-43bb241f63f5.png)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Mac Web
- Browser name and version: Chrome on Mac OS 112.0.5615.137
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @DeltaForce007 - Thanks for submitting the issue. Please setup a blank project with reproducing the issue and share bug report code of the project. Without these details, we are not able to investigate the issue. Thanks

Thanks

**Comment by DeltaForce007** [comment]
Hey @hariprasadms thanks for the response. I have created a new project and get the same issue. But when I try copy the widget code it also gives me an error:

![image](https://user-images.githubusercontent.com/23420174/235708984-56c02eba-baf7-4d4d-aa87-18b6041b229f.png)

**Comment by DeltaForce007** [comment]
@hariprasadms or is there a place where I can get the project's bug report code

**Comment by DeltaForce007** [comment]
@hariprasadms is there any update on this? or anything else that you need to investigate? It has affected all my projects.

**Comment by hariprasadms** [comment]
Hi @DeltaForce007 - As per your last comment, I understand that this issue has been resolved for your projects. Please close the issue. Thanks
