### ISSUE TITLE
Card charged twice for Pro subscription - 3 days but no response from support team!!

### ISSUE THREAD

**Issue by sohaibilyas** [FlutterFlow/flutterflow-issues#843]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

21 April, first unsuccessful subscription and I couldn't find the resubscribe button or retry the payment so I cancelled it and subscribed to Pro again but after about a week it charged my bank card again for the first subscription which I already cancelled.

### Expected Behavior

There should be a button or way to resubscribe/retry on unsuccessful subscription payments.
If subscription is canceled by user then it should leave it cancelled and should not renew it.
It the subscription is already active then it should not subscribe again.

### Steps to Reproduce

1. Subscribe to Pro
2. Unsuccessful payment
3. Cancel the subscription
4. Subscribe to Pro again
5. After some days it will renew the first subscription which is already cancelled

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

This bug is on the flutterflow stripe checkout page.

### Context

It's been 3 days and still no response from support chat team.

### Visual documentation

This bug is on the flutterflow stripe checkout page.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Brave 1.50.121
- Operating system and version affected: macOS Ventura 13.3.1
```

**Comment by hariprasadms** [comment]
Hi @sohaibilyas - Sorry about that you got an issue related to subscriptions. I just shared the details with the team. Some one from support team should be able to look into issue asap.

**Comment by sohaibilyas** [comment]
@hariprasadms thanks

**Comment by sohaibilyas** [comment]
@hariprasadms still no refund on second pro subscription or reply from the support team.
