### ISSUE TITLE
Dropdown produce a compilation error

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#844]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a dropdown is added to a page crash the app

### Expected Behavior

Should be added without problems

### Steps to Reproduce

1. Create a page
2. Add a dropdown
3. The app crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMdW503lOxscw4dfe/4PZkteOLeZRFDTsSzaH1mAE6Zjj4G+PzKi+LtFsEqIgSAfbZH1LhMYRPPYzqiVLLTCs+0XkF7GtFUC26z38KkkxMnA7Jucnwf7UOyG+SWfz6Cf9qOYwx5e6fDbOY=

### Context

I want add a dropdown

### Visual documentation

![image](https://user-images.githubusercontent.com/36147203/236190712-9af2d452-adfb-4706-be6b-4b864ebbc5eb.png)

### Additional Info

I can't add the Bug Report Code by this issue

https://github.com/FlutterFlow/flutterflow-issues/issues/255

### Environment

```markdown
- FlutterFlow version:  v3.1 (released May 2, 2023)
- Platform:Web
- Browser name and version: 112.0.5615.139
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @Franco98404 - Thanks for submitting the issue. We are aware about this issue. It will be fixed in future updates. Thanks

**Comment by Franco98404** [comment]
Thanks, can you give the link of the original issue?

**Comment by hariprasadms** [comment]
Hi @Franco98404 - We got a internal bug of this already. I can change the status to bug and confirmed. No worries. Thanks

**Comment by Prain77** [comment]
Tengo el mismo problema en windows 10 con crhome y no puedo continuar con mi proyecto

**Comment by Franco98404** [comment]
> 
> ![error_dropdown](https://user-images.githubusercontent.com/86490764/236708712-50d81599-1dd6-40a4-a874-6ebb73d3aeb3.png)
> Tengo el mismo problema en windows 10 con crhome y no puedo continuar con mi proyecto, te dieron alguna solución @Franco98404 ?

@Prain77 No me dieron una solución, pero encontré un workaround y es volver a seleccionar las fuentes y eso soluciona el error. Espero te haya sido útil

**Comment by Prain77** [comment]
@Franco98404 , he vuelto a seleccionar las fuentes en el widget y nada, o me puedes indicar donde hacerlo para solucionar, recien estoy utilizando flutterflow disculpa

**Comment by Franco98404** [comment]
No es la fuente del widget, es del proyecto

![image](https://user-images.githubusercontent.com/36147203/236787260-e59cddb2-edee-467c-8039-67b43059b29b.png)

**Comment by Prain77** [comment]
@Franco98404 , con que fuentes funciona el dropdown; por que con poppins y opensans no funciona, he probado con otras y tampoco. He probado en emulador, movil físico y igual sale el error, hasta que no borre el dropdown. :(

**Comment by Paranauerj** [comment]
got same error here

**Comment by Prain77** [comment]
@Paranauerj al parecer lo solucione de una manera singular, gracias a @Franco98404 , pero solo me funciono cuando llene esa fila "Body Large" que faltaba, sin cambiar las fuentes, ni nada, solo eso y mantuve la fuente poppins sugerida por FF.
![error_dropdown_solucion](https://user-images.githubusercontent.com/86490764/236947398-2f86f2c1-d63e-4cb0-816b-e0a3649eceac.png)

**Comment by Franco98404** [comment]
> @Paranauerj al parecer lo solucione de una manera singular, gracias a @Franco98404 , pero solo me funciono cuando llene esa fila "Body Large" que faltaba, sin cambiar las fuentes, ni nada, solo eso y mantuve la fuente poppins sugerida por FF.
> ![error_dropdown_solucion](https://user-images.githubusercontent.com/86490764/236947398-2f86f2c1-d63e-4cb0-816b-e0a3649eceac.png)
> 

Perfecto! Ahora recuerdo que hice ese cambio qué mencionaste, solo que me había olvidado

**Comment by teerapat-beyonndcode-academy** [comment]
I am also experiencing the same issue. It was working previously. Not sure when this issue will be fixed as it prevents us from testing

**Comment by Franco98404** [comment]
As said @Paranauerj you can set the Body Large row as you can see in the image to solve the problem momentary until FF team fix the bug

**Comment by wenkaifan0720** [comment]
Hi all. This is due to a missing font family issue we had on the `Body Large` font. It should be fixed by now. So I will close this issue.
