### ISSUE TITLE
Size of the Icon Button is reduced when Show Loading Indicator is activated

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#845]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Size of the Icon Button is reduced when Show Loading Indicator is activated

### Expected Behavior

Should maintain the same size

### Steps to Reproduce

1. Add an Icon Button
2. Activate Show Loading Indicator
3. Add an action to the button (Delay 1000ms) to simulate a process
4. Do a test and click the button
5. The size is reduced

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KXUKe4wq2UWCUMbWoIzlO1Ca0kdB4joPLJ/dsz8Yk1pZOrmT0NhHGKYjT4C+OjuhvDMG/U4AwWYRpg4wpdQcw7hXXq8Rqq0Cs6OWERBM5lVJ2qj0JizhxJBItJadUYH706yONiWaC7YGZ+/Zwh9f6PHaOI=

### Context

I want add the Loading Indicator 

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODE4OTY2MF8yMTM5NTU4OA

### Environment

```markdown
- FlutterFlow version:  v3.1 (released May 2, 2023)
- Platform:Web
- Browser name and version: 112.0.5615.139
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @Franco98404. This will be fixed in our next update. Thank you for reporting!
