### ISSUE TITLE
Play sound is not working when audio type is given from assets

### ISSUE THREAD

**Issue by KavyaDevv** [FlutterFlow/flutterflow-issues#846]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Play sound is not working when source is given from assets, but working as expected when the source is from the network

### Expected Behavior

Play sound should work even if the source is from assets

### Steps to Reproduce

1. Create a page
2. Define an action. 
3. Select the action as play sound
4. Set the audio type as asset
5. Upload the audio and select
6. Run
7. Observe the behavior

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/luItJpbxB+pfqaMBWhQMwJ0QlUIInj+0bWRMhfJvnOuwydc/7dhJLYteIekFEE1aGgT4E0tb8kdjDGvcDFy2ubtlT1oRXQRXJeHOmac2IELqWQHx6O8JMCUyj4LuJoSVNBO9fc3wa7DqyPPCdG3qCf9qOYwx5e6fDbOY=

### Context

I am trying to play the sound when clicked on a image. But not able to achieve as it is not working as expected.

### Visual documentation

[Test Mode_ng_ng.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11404584/Test.Mode_ng_ng.zip)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version:Microsoft Edge
Version 112.0.1722.64 (Official build) (64-bit)
- Operating system and version affected: Windows 10 Business, 21H2
```

**Comment by hariprasadms** [comment]
Hi @KavyaDevv - Thanks for sharing the issue. I can see warnings displaying for uploaded audio files. See below. The issue which you are seeing may be because of these warnings. Fix these warnings and try please. 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/17435678/236450381-f3b2fa86-1ffa-4860-8c5b-65f16238b53c.png">

**Comment by mohamed110011othman** [comment]
I'm going through the same problem

**Comment by hariprasadms** [comment]
Hi @KavyaDevv @mohamed110011othman - Can you please check is there any errors in browser console while clicking on play audio action button. I can see below error. Please confirm. 

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/17435678/236495909-a5713876-1e1b-4fb4-b68c-cd50bdef3b29.png">

**Comment by mohamed110011othman** [comment]
![image](https://user-images.githubusercontent.com/132679062/236522854-5b6319b1-5aab-4cb6-b740-bb1abe13a133.png)

**Comment by mohamed110011othman** [comment]
![Audio check ](https://user-images.githubusercontent.com/132679062/236523160-d7d164ae-99a0-43d4-9fbd-c8b6c0691a72.jpg)
![browser console check](https://user-images.githubusercontent.com/132679062/236523167-0eda9db3-3680-46d4-8b4f-ff1182572fd0.jpg)
I check Audio fills and browser console and that's what I got when I hit the picture to play the sound

**Comment by vishalagarwal2** [comment]
Hi the issue has been fixed and will be applied very soon in our next deploy.
