### ISSUE TITLE
Passing pagination variable in API call query with 0 cause error

### ISSUE THREAD

**Issue by faroukegypt2** [FlutterFlow/flutterflow-issues#847]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

by default pagination variable is passing 0 which cause error on my api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.

### Expected Behavior

by default pagination variable is passing 0 which cause error on my api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.

### Steps to Reproduce

by default pagination variable is passing 0 which cause error on my api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

x

### Context

by default pagination variable is passing 0 which cause error on my api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.

### Visual documentation

by default pagination variable is passing 0 which cause error on my api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.

### Additional Info

by default pagination variable is passing 0 which cause error on my api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.
x

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: x
- Browser name and version: x
- Operating system and version affected: x
x
```

**Comment by faroukegypt2** [comment]
still not fixed, 

by default pagination variable is passing 0 which cause error on api, since the first page always start with 1 not 0, how can I make the pagination variable start with 1 instead of starting with 0.

you need to make us able to control the pagination start number. instead of the default 0 which cause the error in pagination api call.

**Comment by takashiff** [comment]
Hi, unfortunately your bug report lacks the necessary information to fix. Please provide more information.
