### ISSUE TITLE
Stripe Failed Payment Detection Failure

### ISSUE THREAD

**Issue by gasserwshalaby** [FlutterFlow/flutterflow-issues#848]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when using stripe's integration, in test mode, while using Stripe's own test cards, when a test card set to produce a failed payment, the errror is in the logs only (insufficient funds), with no way of catching the error in the app.

### Expected Behavior

as the code for stripe indicates, it should return an error message with the caught error from having a failed payment.

### Steps to Reproduce

1. integrate Stripe
2. Stripe Action: on sny pagfe, make a button that makes a trial payment using the 'failed payment' test card: 4000000000009995 ; 12/26; CVV: 123
3. open console while running the action in the test mode to find the error logged in the console but no action happens at tyhe app level, meaning the app is not listening to the response somehow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ksrl34x2tbwA15DUbu9VgiMRJkM7U78njOpHZw88KOPdOoYUP8+kM0RBXsTgYGx5MFq0gWoW09b5voXpIfcDITWsG6J/1ZBQawrgczqnWqakFJWgOGpQO8dgCUDC55+rvB1CKuxudC0BwznzH/C9HxTDQpjROFUsDa/LZO4=

### Context

i am trying to use stripe payment to accept payment on my platform, and actually be able to do actions when payments fail, which are not recognized by the app.

### Visual documentation

https://user-images.githubusercontent.com/107878826/236518306-9ff3a4df-3f4a-4ee9-adb8-e2905331acda.mp4

### Environment

```markdown
- FlutterFlow version: 1.1.66
- Platform: Mac App
- Browser name and version: Mac App
- Operating system and version affected: Mac OS Monterey 12.5
```

**Comment by hariprasadms** [comment]
Hi @gasserwshalaby - We appreciate you for submitting the issue. I can recreate the issue. However, you can still direct action flow to different steps based on an api response status code, so I'm not really sure if this is a issue. Nevertheless, given that there are a few more edge cases and that the present Stripe integration state still needs a few enhancements, I can classify this issue as a bug.
Thanks

**Comment by gasserwshalaby** [comment]
as a matter of fact, having the api response as an error, breaks the workflow from continuing, like a broken custom code, wherei CANNOT, direct the action flow, because it breaks, and there is no way to even run a flow if the payment is not successful, whcih returns a paymentID.

**Comment by Rart3001** [comment]
> Hi @gasserwshalaby - We appreciate you for submitting the issue. I can recreate the issue. However, you can still direct action flow to different steps based on an api response status code, so I'm not really sure if this is a issue. Nevertheless, given that there are a few more edge cases and that the present Stripe integration state still needs a few enhancements, I can classify this issue as a bug. Thanks

Hello @hariprasadms, how can I validate the API response status code? because the stripe action only returns the stripe_id, if the action throws an exception is not reached for the app. You can test with a declined test card "4000 0000 0000 0002" and you can see the error on the browser console and the stripe modal still open.
<img width="416" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12099493/ccb7b901-5f10-48e1-8401-daa435f057df">

<img width="312" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12099493/a2a1af6d-7a2b-435f-a0ff-bb94851f325a">

<img width="649" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12099493/eb870d3c-b3aa-4d19-b535-67d9afc75569">

**Comment by ikolcoding** [comment]
> Hi @gasserwshalaby - We appreciate you for submitting the issue. I can recreate the issue. However, you can still direct action flow to different steps based on an api response status code, so **I'm not really sure if this is a issue.** Nevertheless, given that there are a few more edge cases and that the present Stripe integration state still needs a few enhancements, I can classify this issue as a bug. Thanks

At last can you tell us how you direct the flow based on the status code.Because i see the bug is from may open and still no progress at all..

**Comment by joshua-ffio** [comment]
Hi all. I have found the issue with the way paymentId was populated during Stripe payment actions in FlutterFlow. In a new change, the paymentId will correctly populate for both success/failure cases. 

- If the **paymentId is empty** after the action, then the **payment was a failure**
- if the **paymentId has been set**, the **payment was a success** and you can use the paymentId for your record-keeping.

As @Rart3001 (thanks!) had shown in their last comment, your action flow will be able to look similar to the following:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/141682285/3632f6b9-24b8-49e2-9c6f-e8b47c8ab7a6)

This change will be available in the next update!

Any further expansion on the success/failure sub-types would be considered a feature request and I encourage you to submit your feature requests through the in-app feature request tool. You can find it in [the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback.

Thank you all for bringing this one to our attention!
