### ISSUE TITLE
Navigation Issues Causing Random Redirects

### ISSUE THREAD

**Issue by whobick** [FlutterFlow/flutterflow-issues#849]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have actions on the splash page that occur on a timer, however they seem to occur twice, or even occur when a user opens a dynamic link to another page. In this case, the splash page opens, after 4000ms it redirects a user to a home page. However if a user navigates to other pages, it randomly after a few more seconds repeats the action and navigates them back to the home page. Same thing happens when opening dynamic links - it opens the dynamic link page but randomly after 3-4 seconds redirects to a different page.

### Expected Behavior

The expected behavior is that the navigation would only occur one time. The action wouldn't continue to occur elsewhere in the app or occur delayed. Essentially the navigation actions occur twice.

### Steps to Reproduce

1. Create a splash page
2. Add a on load "wait" action for some time (say 2000ms)
3. Add a navigation to another after the wait action
4. start on test mode

Seems the navigation occurs, then if you proceed to navigate elsewhere the navigation action will repeat and send you back to the initial navigation after the wait.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMn1z8p2rsRE7pDUbPlFmik5JmYhaJ0omMFBaCosfZT2BLMcec/RVERuZO2gdEFYPE6jhWoW0+D2hYfXUsIEBw+WfoREz6lqVALJeH+nb83SFJWgYkZfGflhFUCM55mNhR14VcFacUY81EOECvCUc3XbQJTBDkcCDq/LZO4=

### Context

This causes an odd user experience as it skips past user signup processes, randomly jumps users to a different page mid navigation, etc. See my iphone recording for an example - the user is taken to the sign in page and randomly redirected to a logged in page.

### Visual documentation

Video walkthrough:
https://tella.video/random-navigation-gllg

Additional showcase on phone:

https://user-images.githubusercontent.com/50713619/236591054-0bf2562f-01b8-4490-85dd-f1515d309eb7.mp4

### Environment

```markdown
- FlutterFlow version: v3.7 (released May 4th)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by hariprasadms** [comment]
Hi @whobick  - Thanks for submitting the issue. I can see that you have given bug report code from your actual project. It does not help us as it is default to navigate through all the pages to investigate the issue. 
We suggest you to create a blank project with reproducing the issue and share the bug report code from the project.  Once we got these details, we can pick this issue for investigation. Thanks

**Comment by hariprasadms** [comment]
We assume you discovered a solution to the issue or that latest FlutterFlow releases fixed it. Since there are no ongoing active conversations in the issue, we are closing the issue.
