### ISSUE TITLE
Custom Domain: Can't add CNAME records for the root domain.

### ISSUE THREAD

**Issue by wednesdei** [FlutterFlow/flutterflow-issues#85]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I can connect a custom domain to my project using the form located in the App Settings > Web Publishing menu > "Custom Domain" section. 

## Current behavior (required)

When I submit my custom domain URL by hitting the connect button, it provides me with a CNAME record to add to my DNS records. I am getting an error from my provider(Google): 

"Can't add CNAME records for the root domain."

I did a quick google search and found the following information: 

"A CNAME cannot be placed at the root domain level, because the root domain is the DNS Start of Authority (SOA) which must point to an IP address. CNAME records must point to another domain name, never to an IP address."

I think FlutterFlow should provide me with a hostname and a value instead of just a value.

## To Reproduce (required)

Steps to reproduce the behaviour:
1. Create a new FF project
2. Add custom URL to custom domain section, hit connect
3. take the information provided by FF and try to add that to your DNS settings
4. DNS provider will return an error.
5.
6.
7.

## Context (required)

Can't link my custom domain to FF

## Screenshots / recordings

Not applicable, error is pretty straight forward.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: Latest
* Platform (e.g. Web, MacOS Desktop):  Web?
* Browser name and version: Chrome, latest.
* Operating system and version (desktop or mobile): Windows 11 desktop, latest

**Comment by bulgariamitko** [comment]
What error do you get returned from the provider you are using?

**Comment by aemelyanovff** [comment]
Ouch, this is indeed a problem. We never tested it for apex domains... We need to use A records instead.

```
………………..,-~*`¯lllllll`*~,
…………..,-~*`lllllllllllllllllllllllllll¯`*-,
………,-~*llllllllllllllllllllllllllllllllllllllllllll*-,
……,-*llllllllllllllllllllllllllllllllllllllllllllllllllllll.\
….;*`lllllllllllllllllllllllllll,-~*~-,llllllllllllllllllll\
…..\lllllllllllllllllllllllllll/………\;;;;llllllllllll,-`~-.
……\lllllllllllllllllllll,-*………..`~-~-,…(.(¯`*,`,
…….\llllllllllll,-~*…………………)_-\..*`*;..)
……..\,-*`¯,*`)…………,-~*`~……………./
………|/…/…/~,……-~*,-~*`;……………./.\
……../…/…/…/..,-,..*~,.`*~*…………….*…\
…….|…/…/…/.*`…\………………………)….)¯`~,
…….|./…/…./…….)……,.)`*~-,…………/….|..)…`~-,.
……/./…/…,*`-,…..`-,…*`….,—……\…./…../..|………¯“,
……(……….)`*~-,….`*`.,-~*.,-*……|…/…./…/…………\
…….*-,…….`*-,…`~,..“.,,,-*……….|.,*…,*…|……….…..\
……….*,………`-,…)-,…………..,-*`…,-*….(`-,………………\
………….f`-,………`-,/…*-,___,,-~*….,-*……|…`-,………….\
```

**Comment by wednesdei** [comment]
> 
Google domains says:
"Can't add CNAME records for the root domain."

**Comment by sirian-m** [comment]
I use google domains as well, the fix for me was to fill in "www" for the host and then it did connect. But it should be made clear in FF

**Comment by wednesdei** [comment]
> I use google domains as well, the fix for me was to fill in "www" for the host and then it did connect. But it should be made clear in FF

www is a subdomain of yourdomain.com = www.yourdomain.com; however, you wouldn't be able to use yourdomain.com because that is the apex/root domain.

**Comment by aemelyanovff** [comment]
We are working on a fix for this. We are planning to roll it out next week.

After the fix, FlutterFlow will ask users to create A records instead of CNAME records, and it should work for root domains as well as subdomains.

Thanks for reporting the issue, @wednesdei.
