### ISSUE TITLE
Uncaught Operation Error and White Screen after Page Reload or 2nd Redirect

### ISSUE THREAD

**Issue by livingmydesign** [FlutterFlow/flutterflow-issues#851]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The first time, when someone logs in to the app via a Token Parameter, it loads the page correctly.

When one reloads the page(webapp) or tries to use that login the 2nd time it creates a white screen.
When I delete the cache it works again.

### Expected Behavior

The page should be loaded correctly every single time.

### Steps to Reproduce

1.) load that page:
https://rasaid2.flutterflow.app/signin/123

2.) reload that page:
https://rasaid2.flutterflow.app/signin/123

White screen.
uncaught error in the browser console 
operation error in android studio

3.) clear cache & delete cookies

4.) load the page again:
https://rasaid2.flutterflow.app/signin/123

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEek8jcw4lPn7xa0M7qb/lvrwMwJ0QlUIInj+0bWRMhfJjvBIYQOffeSElLYteBdH5UDGL/hn4y0cHGks7DLvlfPTSqbtVN+q5XQTrxRmG7SraKPZGoRkB7HZlYBWaf15m7nx1SC7B1LUYl6l6ECPCdG3qCf9qOYwx5e6fDbOY=

### Context

I try to create a login page with a personalized token. 
since a second login is not possible without a freeze, I can't continue.

### Visual documentation

https://user-images.githubusercontent.com/93006467/236650597-2cc8c9cc-24e5-43ad-af1c-0e35439258c0.mov

### Additional Info

Android Studio Error Message:
(supabase authentication was not used..)

../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10 createErrorWithStack
../dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 355:28 _throw
../dart-sdk/lib/core/errors.dart 120:5 throwWithStackTrace
../dart-sdk/lib/async/zone.dart 1385:11 callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11 _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5 _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15 <fn>
***** Supabase init completed Instance of 'Supabase'
Got object store box in database supabase_authentication.
***** SupabaseDeepLinkingMixin startAuthObserver
Error: OperationError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10 createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 355:28 _throw
dart-sdk/lib/core/errors.dart 120:5 throwWithStackTrace
dart-sdk/lib/async/zone.dart 1385:11 callback
dart-sdk/lib/async/schedule_microtask.dart 40:11 _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5 _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15 <fn>

### Environment

```markdown
- FlutterFlow version: v3.1 - 3.7.12
- Platform: android app
- Browser name and version: google chrome Version 112.0.5615.137 
- Operating system and version affected: macOS 13.0.1
```

**Comment by livingmydesign** [comment]
in the blank-version of the project it was today possible to solve it by disabling supabase and re-deploying again.

this solution is not an option in the live-environment as there are too many DB connections configured .

to test it in the live environment:
open https://rasaid.flutterflow.app/signin/0c460f84-801f-41bf-b1b5-b48cc35501ab41007231111asdf345
then reload after the archive page is loaded.

then a white screen shows up
then you can clear the browser cache
then it works again after a reload

I need a solution that fixes this cache issue without the need to deploy with supabase disabled.

**Comment by hariprasadms** [comment]
Hi @livingmydesign - I have disabled the google analytics and run the app. It seems to be working fine with no error in the browser console. Here is the run mode - https://preview.flutterflow.app/error-cwtofg/W8KQc6c8VgfCfNSLJkQz. 

Try disabling google analytics in the actual project and see if there are any difference.

**Comment by livingmydesign** [comment]
I disabled Google Analytics and redeployed the project. The issue remains although there is one less item to clear in the Browser cache afterwards to get it working again:

<img width="409" alt="Screenshot 2023-05-08 at 16 31 54" src="https://user-images.githubusercontent.com/93006467/236851585-0b2320c3-2b1b-4776-8874-27f72a1126aa.p
<img width="458" alt="Screenshot 2023-05-08 at 16 34 52" src="https://user-images.githubusercontent.com/93006467/236852462-4a833215-4aab-4727-a489-5bd48c942667.png">
ng">

you can again test it with this link yourself:
https://rasaid.flutterflow.app/signin/0c460f84-801f-41bf-b1b5-b48cc35501ab41007231111asdf345

**Comment by victoriahuang1** [comment]
Hi @livingmydesign thanks for the report. This issue should be fixed upon the next deploy!
