### ISSUE TITLE
Text Widget's behavior when press enter (new line) broke different words into new lines when type in Thai  

### ISSUE THREAD

**Issue by teerapat-beyonndcode-academy** [FlutterFlow/flutterflow-issues#852]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we type Thai characters and press enter, different characters or words break and unexpectedly goes to new line as well. This unexpected behavior is not seen in English language

[Link to Video showing the problem](https://drive.google.com/file/d/1aopQeL7fRRzUu3ylgZpI8BIgnUg7tHH1/view?usp=share_link)

### Expected Behavior

When I press Enter or new line, the cursor should just go to new line without bringing other words into new lines as well.

### Steps to Reproduce

1.Navigate to [Link to Project](https://app.flutterflow.io/project/bug-report-fkqi20)
2.Run in test mode
3.Type more than one Thai characters in the text box
4.Press enter on the keyboard

[Link to Video showing the problem](https://drive.google.com/file/d/1aopQeL7fRRzUu3ylgZpI8BIgnUg7tHH1/view?usp=share_link)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otPm9tH1s7yKe9VliIWJmE2RJc0sdlud0wdCoDuBIk+ZPWlUE5vOOmmS1VUeUSmmlkC0NWMk+DEGMBfaCyefLZDz5FqVRXKZEOmQZOBDam0fndTGcZhBUyF5KW7kCUlWbZhL04FwDiACdmtEnPfJOfWImdISq/LZO4=

### Context

I have published another project live on production and now we have to stop using it completely as most of our customers are Thais and filling in textbox is part of our core feature

### Visual documentation

[Link to Video showing the problem](https://drive.google.com/file/d/1aopQeL7fRRzUu3ylgZpI8BIgnUg7tHH1/view?usp=share_link)

### Environment

```markdown
- FlutterFlow version: v3.1 (release May 4,2023
- Platform: Web
- Browser name and version: Chrome Version 112.0.5615.137
- Operating system and version affected: macOS Ventura 13.3.1
```

**Comment by hariprasadms** [comment]
Hi @teerapat-beyonndcode-academy - Thanks for submitting the issue. This issue looks like duplicate with #830. Let me know if this is something different. I can have look. Thanks
