### ISSUE TITLE
Manual Push notification with parameter of Document Reference of subcollection

### ISSUE THREAD

**Issue by stepanic** [FlutterFlow/flutterflow-issues#854]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is possible only to pass the parameter of DocumentReference which is a part of root collection.

### Expected Behavior

To be possible to pass DocumentReference of the document which is the part of subcollection.

### Steps to Reproduce

1. go to
https://app.flutterflow.io/project/<PROJECT_ID>?tab=appSettings&appSettingsTab=pushNotifications

2. select page which has parameter of type DocumentReference

3. set document reference is not possible for subcollection
<img width="719" alt="Screenshot 2023-05-08 at 07 35 58" src="https://user-images.githubusercontent.com/315282/236742987-87d5a9b0-7968-4465-a709-1b4bdb4dfeef.png">

In Firebase Schema `section_activities` is a subcollection of root collection `users`
<img width="307" alt="Screenshot 2023-05-08 at 07 36 15" src="https://user-images.githubusercontent.com/315282/236743099-4c76cb58-1931-448c-bd4c-b2f79f5386e0.png">

But 
https://app.flutterflow.io/project/<PROJECT_ID>?tab=appSettings&appSettingsTab=pushNotifications
requires that DocumentReference starts with `/section_activities/` instead of `/user/<UID>/section_activities/`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

I want to pass on specific DocumentReference of `users` subcollection `section_activities` through notification.message.data

### Visual documentation

<img width="719" alt="Screenshot 2023-05-08 at 07 35 58" src="https://user-images.githubusercontent.com/315282/236743650-44aa6f5b-e763-4036-a954-64626ad6ce8a.png">

### Additional Info

-

### Environment

```markdown
- FlutterFlow version:  v3.1
- Platform: iOS, Android
- Browser name and version: Brave 1.50.121
- Operating system and version affected:  MacOS 13.2.1
```

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This issue has been fixed and will be reflected in our next deploy.
