### ISSUE TITLE
Dark/Light mode is not working in Test Mode

### ISSUE THREAD

**Issue by KavyaDevv** [FlutterFlow/flutterflow-issues#855]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dark/Light mode is not working in Test Mode

### Expected Behavior

Dark/Light mode should work as expected in Test Mode. It is working as expected in Preview mode but not in the test mode.

### Steps to Reproduce

1. Create a Page
2. Add a container to the widget tree
3. Provide background for both dark/light mode.
4. And also, Add a image and select the image type as Asset.
5. Set two different images for both dark/light mode.
6. Now run both Test/Preview mode.
7. Compare the differences.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/luItJpbxB+pfqaMBWhQMwJ0QlUIInj+0bWRMhfJvnOuwydc/7dhJLYteLfVVcHWKlrD0E7vDxvtnfUfoDPQuZb65hypRXQQyXRky7VLqXCbmeWnF7I9NVCHHC3MGZoh15Lu11W1oS7GGpffCNG3qCf9qOYwx5e6fDbOY=

### Context

Not able to test the changes in Test mode with respect to the Dark/Light mode settings.

### Visual documentation

[Test Mode_Dark.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11418806/Test.Mode_Dark.zip)

### Additional Info

Project URL:https://app.flutterflow.io/project/dummy-j64jq2
Page: Webview

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: Microsoft Edge
Version 112.0.1722.64 (Official build) (64-bit)
- Operating system and version affected: Windows 10 Business, 21H2
```

**Comment by hariprasadms** [comment]
Hi @KavyaDevv - Thanks for submitting the issue. I can confirm that dark and light mode settings are working fine in test mode. The way you are testing is wrong. In preview mode, app theme change does not work as preview mode does not consider action changes. 

In your app, you should use 'set dark mode settings' action to achieve dark and light mode behaviour to the app. Please follow documentation / youtube video. 

Help doc link is here - https://docs.flutterflow.io/actions/actions/ui-interactions/set-dark-mode-setting.
