### ISSUE TITLE
Blur Hash - this feature does not work properly

### ISSUE THREAD

**Issue by LucasBene** [FlutterFlow/flutterflow-issues#856]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The blur Hash feature should generate unique hast in database but this does not work. Hash is not generated on image upload to DB. Value in database (string) remain NULL. 

Steps: 

1. on image upload enable Blur Hash toggle 
<img width="281" alt="Screenshot 2023-05-06 at 08 51 55" src="https://user-images.githubusercontent.com/110965153/236763212-1635af22-df9c-4a3f-8353-a1da727e1dc0.png">
2. On backed call 'insert row' (Supabase) when adding the post i add media blur hash.... 
<img width="332" alt="Screenshot 2023-05-06 at 08 52 58" src="https://user-images.githubusercontent.com/110965153/236763309-5b89efcf-63f0-4ce0-a5f6-0a13f9c2a708.png">

Result:
<img width="593" alt="Screenshot 2023-05-06 at 08 49 22" src="https://user-images.githubusercontent.com/110965153/236763639-8017106b-bf4b-4e1e-b2c1-25c5ab3a96e8.png">

File is not generated and remain null. 

### Expected Behavior

I expect from this function and action that blur hash will be automatically generated and added to database, so then on feed screen i can call the 'hash' and image will be blurred before is loaded to the app. 

### Steps to Reproduce

1. on image upload enable Blur Hash toggle
2. On backed call 'insert row' (Supabase) when adding the post i add media blur hash.... 

Blur hash is not generated. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

i dont have

### Context

I am trying to accomplish what the feature should do :)

### Visual documentation

NO

### Additional Info

I've reported this issue to FF support. I was informed that BUG was detected and that team will work on it. However this issue is still there.

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: iOS, ANdroid
- Browser name and version: Google Chrome - but i use FF app to build the app.
- Operating system and version affected: macOS Ventura 13.0.1
```

**Comment by hariprasadms** [comment]
Hi @LucasBene - Thanks for submitting the issue. I have tested generating blur hash for image uploads in my projects and I can see it is working fine with no issues. 

This issues could be project specific or missing configurations. I would suggest double check the documentation and follow the steps. Setup a blank project with reproducible details and share bug report code with us please. Once these details are updated in the issues. We can pick this issue for investigating.

**Comment by LucasBene** [comment]
Hi

Can you forward the documentation about how to set up the Blur Hash
correctly?

Thanks

**Comment by LucasBene** [comment]
[UPDATE] - You we're right. I've rebuild the page and problem is gone. Blur Hash is now generating. 
I've tried to remove action from the image trigger where uploading the image but the action was always back (old action). 

I have to remove the element (image in this case) where i trigger users to upload their pictures for the post and then add the action again to the new (image) element. 

Only by removing this problem could be solved. From some reason FF did not allow me to remove action from image element. 

Problem solved. Thanks
