### ISSUE TITLE
Container Max width is not being recognized when is used in a Bottom Sheet

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#858]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a Bottom Sheet is open doesn't recognize the max width and width setting

### Expected Behavior

The width and max width should be recognized

### Steps to Reproduce

1. Create a component for the Bottom Sheet
2. Create a page and add a button
3. Show a Bottom Sheet in the action of the button
4. Now you see the problem

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KrydsJajjsRCUMcWOdEl+tuZwgbIoznBqQifOPSbRJVZOGiaVNcO1WgrEcG/6nykuztJvAqORedbbo++ahcTgnee2i6VKq2O6uWfHBPL8pPfHal17SFuwolVfN1WV473WWAeejIbBDDFOu/Zwh9f6PHaOI=

### Context

I want add a max width to a container

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODE5OTY4M18yMTQxMDQxOA

### Environment

```markdown
- FlutterFlow version: v3.1 (released May 4, 2023)
- Platform: Web
- Browser name and version: Chrome 112.0.5615.139
- Operating system and version affected: Windows 11
```

**Comment by bulgariamitko** [comment]
I think the bottom sheet will always be 100% width by default and the component is the one which you can set a value to, but it will not affect the width of the bottom sheet. I will set a status that wont fix, but if the FF team does not agree with me they will change it.

**Comment by wenkaifan0720** [comment]
Hi. I think you need to also specify the alignment of the container, otherwise the layout constraints will not be respected.

**Comment by Franco98404** [comment]
> Hi. I think you need to also specify the alignment of the container, otherwise the layout constraints will not be respected.

Thanks, that solved the problem!
