### ISSUE TITLE
Compile process does not recognize FF own functions

### ISSUE THREAD

**Issue by bitgandtter** [FlutterFlow/flutterflow-issues#859]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For project https://app.flutterflow.io/project/snout-zone-zrnm87 function called **deserializePetFromJSON** that internally uses

`serializers.deserializeWith(PetsRecord.serializer, data)`
where serializers its exported from **_../../backend/backend.dart_** but for some reason even when the code editor recognizes it as valid the compiler does not.

It's important to use to be able to convert a JSON response into a DataType object

### Expected Behavior

Recognize and compile successfully

### Steps to Reproduce

1. Create a project
2. setup firebase + configure a database
3. create a custom function and try to use serializers.deserializeWith(<YourDatabaseClass>.serializer, data)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcnfsM5ItbwG1s+Nde9avCkXHDp7R600sNobbxAjIoDoPJkUaePeTBNoOcClYX9tKEWJ/WAE0PPGjob1CvZcFE+cGYBN1KtuVT3MTky/aoSuBqmSRER5BcFmfm6A08CnpBZ+XPVfR3hl612qftmWTh/AQJv7Zwh9f6PHaOI=

### Context

Dealing with API JSON and its paths is complicated. If we can map JSON response to existing datatypes will speed up the design process on a 100% bases + ensure that the data is strong type validated

### Visual documentation

![image](https://user-images.githubusercontent.com/1316125/236817391-3dbb198b-d31f-4940-bed7-9c66663344da.png)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web ? android
- Browser name and version: Chrome Version 113.0.5672.63 (Official Build) (64-bit)
- Operating system and version affected: Linux
```

**Comment by bulgariamitko** [comment]
You can't use source code FF inside a custom function you can only use it inside custom action or widget. this is a known issue for the FF team. We are still expecting that to be fixed in the future.

**Comment by bitgandtter** [comment]
But there is or there is not a solution coming in the near future. at leas for my ORG this will be a deal breaker

**Comment by bulgariamitko** [comment]
@bitgandtter yeah I got that, that's why I marked that as a FF issue as if you ask me the same logic should work for all custom code regardless if it is a custom function action or widget. But keep in mind this was like that since the release of FF so don't expect to be changed in the near feature.
