### ISSUE TITLE
Selecting If/Then/Else from Set from Variable on Data Type causes crash

### ISSUE THREAD

**Issue by TomJFox** [FlutterFlow/flutterflow-issues#860]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have a Data Type defined for Phone which contains 2 Strings.  
<img width="329" alt="image" src="https://user-images.githubusercontent.com/106626912/236911413-62bffe36-16b8-4711-af18-95b2284ae2fa.png">

When we write to Firebase, I wanted to use the If/Then/Else to pick which data I send to this field. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/106626912/236911884-e6fd73e0-6780-457d-a0de-b49c6ff14964.png">

When I click Conditional Value (If/Then/Else) I get a grey screen
<img width="317" alt="image" src="https://user-images.githubusercontent.com/106626912/236911333-27c1234e-513e-4bd2-bd8f-6c38371e73e1.png">

### Expected Behavior

I would expect to be able to set a If/Then/Else with a boolean condition which would then select from 2 DataType definitions for Then and Else.  With each of the Data Type definitions, I would want to be able to 'Set from Variable' or 'Set Individual Fields'

### Steps to Reproduce

1. Create Data type
2. Add Firebase
3. Add a Firebase collection which uses Data Type
4. Use the Data Type in a variable within an action to write to the new collection
5. Select Set from Variable rather than Set Individual Fields
6. Click Conditional Value (If/Then/Else)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OismB2492m+Fa7aXqacEw+CQRNlw1bZZMjMFxQgEjGOrNG7UIec/4VEptXbC+TVc3eGKGjjoxwPTQkszIN8AVOSeCY4RT+ah2UhXhQl25R8WLC8+wbXYkLNpKCn6z0qbUhCQmIsFpL1oa2V+YI96sTj7cNLKzCm0vJf6YJdjDs3PuQ0SLb3kNh1JWeC/v

### Context

I am trying to write different data to the database depending on the outcome of other items on the page.  I would have expected to be able to create the conditional value at the top most level, then selected individual fields within the then and else conditions.  

### Visual documentation

Current Behaviour above shows the grey screen.

### Additional Info

As a workaround,  I am using Conditional Value for each individual field.

### Environment

```markdown
- FlutterFlow version: v3.1 (released May 4, 2023)
- Platform: Web
- Browser name and version: Version 112.0.5615.138 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @TomJFox. This should be fixed in our next update. Thank you for reporting!
