### ISSUE TITLE
"Generate children from variable" function fails with "null list" when a single value is returned from an API (API can return 1-to-many)

### ISSUE THREAD

**Issue by ahappyspace** [FlutterFlow/flutterflow-issues#861]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm interacting with the Google Places Autocomplete API to retrieve suburbs details. Results from a backend query is fed directly to the "Generate children from variables" functionality (lets call it GenChild). That result is then fed to a ListView to display the search results/places found. From there the user is supposed to chose a specific places result, that to be added to a local page state as "chosen suburbs".

Behaviour is as expected when I get multiple results back from the Places API, for example when searching "kenilworth" in cape town, south africa (4 results back). But, some suburb searches will only return a single result back from the API. E.g. when searching "plumstead" in cape town, south africa.

In the API call definition, the JSON path response is set as "Is List".

When a single result is returned, the following data is passed to the GenChild functionally:
[
suburbName
]
*no comma after suburb name*

This result causes GenChild to fail with a null list error even when the API is configured to expect a list (it's looking for a comma when there isn't one returned). GenChild treats the result back as a string and fails.

### Expected Behavior

GenChild needs to be able to handle a single value fed to it if it needs to handle a 1-to-many result scenario. Currently is can only handle >1.

### Steps to Reproduce

1. Setup an API call to [Googles Autocomplete API](https://developers.google.com/maps/documentation/places/web-service/autocomplete)
2. Create api variable: "input" - type = string - is list = false - default = blank
3. Define the following api query params:
4. "input" - from vairable - "input"
5. "types" - specific value - string - "postal_town|locality|neighborhood|sublocality"
6. "key" - specific value - string - "[YOUR_API_KEY"
7. "components" - specific value - string - "country:za"
8. Set API advanced settings: Make Private = true
9. Test API and choose the following JSON paths:
10. $.predictions[:].description - name: description
11. $.predictions[:].place_id - name: placeID
12. $.predictions[:].structured_formatting.main_text - name: suburb
13. $.predictions[:].structured_formatting.secondary_text - name: city
14. Now move onto creating the test screen
15. create blank page
16. add column element
17. inside column add a row and ListView elements
18. inside the row element, add an input TextField and a button (or icon acting as button). Name the textfield "suburbName", and the button "search"
19. For search button define the following action flow: API call (created previously) > if succeed > write result to page state
20. For the ListView element, configure the "generate children from variable" functionality to read the populated Page State with JSON path "$.predictions[:]" - name the GenChild variable "apiResultChild" - your screen will load with a null result error, that's expected. We're looking to see what happens after a search is made.
21. For the ListView text (rows to display), set it to "Set from Variable" and source it's data from "apiResultChild". Use JSON path "$.description"
22. Run the app in test mode
23. In the suburbName field enter "kenilworth" and hit search button - you'll get 4 results. Results show in ListView
24. In the search field enter "plumstead" and hit search button. ListView fails with null list error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l8j6yIt1oeVY17X6LMAxjjgsQ187ap0Nj9YbaAI8J5zKB+wAYvf7P1FWTLzkTX9lfVmZpGM01vfqk+OeA/QoPTCsbJRhyalcWjzzfD+gRLKvPruVfW1TP8JjfECB58C7rBVDAO9YcWQH2F6QC+i/aDbqHozoC2o/G/qlKdeK2SrDX1iXc2URm05KZDPz

### Context

i have a suburb name autocomplete search that fails when i get a single result back from google's places api. This is a major problem and will block the release of my app.

The data I'm to record revolves around location/suburb names. Without a proper functioning suburb search, there is no app.

### Visual documentation

https://user-images.githubusercontent.com/63412962/236923910-76f71896-09de-41e6-8244-b3b6ea5627e5.mov

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web & macos
- Browser name and version: chrome Version 112.0.5615.137 (Official Build) (x86_64)
- Operating system and version affected: MacOS Ventura 13.3.1 (22E261)
```

**Comment by bulgariamitko** [comment]
What is the result that you get if you get the result as list - [] you won't get any errors, but if you get the result as a single variable you will get this error as Generate children from variable is expecting to have a list

**Comment by ahappyspace** [comment]
When the API returns a single result it's like this:

[
suburbName
]

When there are multiple results back it's like this:
[
suburbName,
suburbName,
suburbName,
suburbName
]

The missing comma would be the issue.

**Comment by bulgariamitko** [comment]
@ahappyspace I think the issue is that you do not get any results. you get a null response and thats why you see this error, please check again your data and share it here what you get from your API calls.

**Comment by aemelyanovff** [comment]
Closing as inactive. @ahappyspace please feel free to reopen the issue if you add the details mentioned in the comment above.
