### ISSUE TITLE
Mux Not Deployed

### ISSUE THREAD

**Issue by rei2479** [FlutterFlow/flutterflow-issues#863]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, I try to deploy Mux using its Access Tokens and Token Secret but always got an error
![image](https://user-images.githubusercontent.com/80249352/237007572-39908098-6fbd-41c8-a69e-6cc700f7a24f.png)

and I am already in Blaze plan:
![image (1)](https://user-images.githubusercontent.com/80249352/237007817-3e24db56-1b45-4bfd-bdec-ac38a4787ca6.png)

### Expected Behavior

Success Deployment

### Steps to Reproduce

1. go to setting
2. Open Mux live stream
3. Put Access token & Token Secret
4. Deploy

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wl87lsYtNmNtF1aqBYO9ViicWMjp8UOdN0+pDcCs8GZT0B4kcYs+kfklUcO7hT3xif2f9pHkX/Mr0huDLJMI5GxSdfNlzzpFibwrxZGWhVq6PDpS3b0dfBd9nJ2bA1KWj2xZDNthedV453FOMBfO8ZBbaNYDtPlVEQeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I am building Premium English Learning Apps for kids. And this is for live tutor feature that we have promised to users before. They are waiting for this

### Visual documentation

![image](https://user-images.githubusercontent.com/80249352/237008755-da87b156-aa3d-426b-8857-0fef7e9f43b8.png)
![image (1)](https://user-images.githubusercontent.com/80249352/237008762-0ef9dbf6-b970-4349-9023-dcfeebcea2b0.png)
![Mux Error](https://user-images.githubusercontent.com/80249352/237008765-02c2840d-e537-4c64-8dc4-1c9bf6b6ce1a.png)

### Environment

```markdown
- FlutterFlow version:3.1 
- Platform: Windows 10
- Browser name and version: Google Chrome: Version 112.0.5615.138
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @rei2479 - Thanks submitting the issue. I just tested the Mux keys deployments in my projects. It is working fine. Looks like you got some network issues at the time of deploying. Can you try and re confirm the status please.

**Comment by rei2479** [comment]
Hi @hariprasadms I have tried to deploy it multiple times, also tried to create a new token, but it has not been deployed.
I have already reported this issue to the support chat since 1 month ago, and tried to deploy it again recently and it didn't work..

**Comment by hariprasadms** [comment]
@rei2479 As I can see deployment works fine, It could be project specific issue. I can mark the issue accordingly

**Comment by rei2479** [comment]
Thankyou any data from my app you need to investigate this issue?

Pada tanggal Kam, 11 Mei 2023 23:18, Hari ***@***.***>
menulis:

**Comment by rei2479** [comment]
Hi @hariprasadms any update about this?

**Comment by rei2479** [comment]
No please, i still can't deploy Mux to my flutterflow, i need this feature
so much, i have promised my paid user about this feature and currently they
are waiting for it, some angry and some upset because i cant keep my
promise. Please

**Comment by agreaves** [comment]
Hi @rei2479, I'm so sorry for missing this issue. From what I can see you've managed to fix yourself 😊, I'm glad you were able to! I'll close this issue for now but please let me know if you are still facing this issue.
