### ISSUE TITLE
App state (string variable) Is-Set condition not working properly

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#864]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Even though the string variable is not set to some value the condition of is set is being performed as true and performing the action accordingly

### Expected Behavior

It should go to the false condition if the value is not set, just like the integers if not set.

I have figured out the workaround for this, we can fix this by using this condition as shown in the screenshot
<img width="1207" alt="SCR-20230509-npgv" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/160c14e5-c604-4faf-a8b5-1413bbac38c9">

but this should work properly with the previous condition as well

### Steps to Reproduce

1. Create a String type App state
2. Add condition for if set and test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz/Hqx89NrtxE1YfQK8cwoygwFjMMbY0v0u0bFB43Ir7oELAuY+P4X0NKT8+rT35EOFaajnMK7vzWjuPfMfQEFwmqb6E+0JVATwzgWke7RqWYCrmOSXx9HtFmBXa90Z+zmxMlPspvR3gB6l6tNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I have been trying to navigate to a screen based on this condition but its not working properly

### Visual documentation

<img width="1481" alt="SCR-20230509-nril" src="https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/fa87a0e0-def3-4ec9-afc6-68b79a5acb9e">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 112.0.5615.137
- Operating system and version affected: MacOS Ventura 13.3
```

**Comment by bulgariamitko** [comment]
I can't replicate your issue.

**Comment by SameerShahzad99** [comment]
As I have shared the bug report code, Please try checking this sample project for reference:
https://app.flutterflow.io/project/testit-k8vwj1

**Comment by wenkaifan0720** [comment]
Hi @SameerShahzad99. I am not able to reproduce your issue as well. If you use the `is set/non-empty` condition, then the app would navigate to newpage2, as one would expect. One thing that might be a bit confusing is that these two conditions (`is set` and `non-empty`) are joined by "and", not "or".

**Comment by SameerShahzad99** [comment]
As if the page is empty, it should be navigating to the page 1, but it is still navigating to page 2

https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/27aabbc2-e82e-4f9c-93f3-d0831d68dac7

**Comment by bulgariamitko** [comment]
@SameerShahzad99 in your videoo you are using a string "false" which is different then the bool false, that's why it is going to the TRUE condition, but this is normal and it will be like that in any env

**Comment by SameerShahzad99** [comment]
I have not set any value in the local state.
It's empty, Please recheck.

**Comment by bulgariamitko** [comment]
@SameerShahzad99 yes you are right, are you sure you are not using someone the AppState and re-setting it, is it possible to output the text in your page and see if you really get nothing?

**Comment by SameerShahzad99** [comment]
Apologies from my side for the misunderstanding, the condition name is a little ambiguous.
you can mark the problem that I was facing as not a bug and improve the action name

**Comment by bulgariamitko** [comment]
@SameerShahzad99 , thank you for the feedback
