### ISSUE TITLE
Stripe plugin causing fail builld on Mobile deployment

### ISSUE THREAD

**Issue by AM0100101010** [FlutterFlow/flutterflow-issues#865]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Error output from codemagic on FF builder
Returning local
[!] CocoaPods could not find compatible versions for pod "stripe_ios":
In Podfile:
stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)
Specs satisfying the `stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

### Expected Behavior

Post to App store using FF app deployment code magic 

### Steps to Reproduce

Include Stripe payment and build to ios using app deployment 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OhvHq25dNofpE7qXQc/lVtCMvJj8lU4ZM1MFHb00gG7nNG7UIec/4VEptXbC+TVc2M2KZoGM1wPzOvfbIN/UFAy6uQN1dz6pMFBXKRjuhb6q6CpCwQkB5FtpKChGw5raZpRBSIu5fWHAB21yuPeyUSgHfQpDKOUU7QuSIDJjIs3PuQ0SLb3kNh1JWeC/v

### Context

Can't build to IOS, Also Play store reported the following 
also the android build reported the following 
Crashes

Devices without issues
7

Devices with issues
1

Device(s) with issues
Google Pixel 2 (Pixel2Emulator) - Android 9

Exceptions
at androidx.fragment.app.j.onStart(Unknown Source:20)

### Visual documentation

Briefly described 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/95685898/aca6904b-e859-47e8-98ec-9159ab936688)

### Additional Info

None

### Environment

```markdown
- FlutterFlow version: Current
- Platform: IOS
- Browser name and version: Chrome current
- Operating system and version affected: IOS
```

**Comment by shelpert** [comment]
Hello, 
We recently realized that this occurs when both Stripe and Braintree are being used in a project. A solution has already been implemented, and if it is not already available it should be soon. The temporary workaround is to change this line
`platform: ios, '12.0'`
in `ios/Podfile` to '13.0' and deploying from a Github branch.
