### ISSUE TITLE
Missing Link to Discord and the FlutterFlow Community in the UI

### ISSUE THREAD

**Issue by Julihan** [FlutterFlow/flutterflow-issues#868]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The docs describe a link to access your discord server as well as your community within the FlutterFlow UI. However, there are no link to Discord and no link to get invited to the community.

### Expected Behavior

Links to Discord server with invite
Links 

### Steps to Reproduce

1. Click the ? on any flutterflow project
2. No links to get invited to Discord or the community

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

Can't access community help or ask questions

### Visual documentation

<img width="587" alt="Screenshot 2023-05-09 at 17 27 51" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1126006/ae6ada69-7597-4617-8d1d-5da8d62b0454">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment]
I just tested and the link is working now. I'll close this issue for now.

**Comment by Julihan** [comment]
No, there is still no link to Discord. Does that mean you do not have a Discord anymore?
You haven't touch this issue in 2 months!
