### ISSUE TITLE
Scrolling not working for custom widget

### ISSUE THREAD

**Issue by robby-cirrus360** [FlutterFlow/flutterflow-issues#869]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am building a Web app that needs to display a DAG.  I created a custom widget using the graphite DirectGraph widget and it works as long as the window is large enough to see the whole thing.  I have searched the docs on both FlutterFlow and Flutter.  I tried using Columns and Rows, scrolling won't scroll all the way horizontally or vertically it cuts off the edges of the graph.  I even tried wrapping the widget in an InteractiveViewer or a SingleChildScrollView, those just made things worse.

All the custom widget examples for FF are small so scrolling is never required.  Perhaps there is just missing documentation to explain how to do this.  But it seems like an issue with how the layout widgets deal with scrolling a custom widget.

### Expected Behavior

A custom widget should just be treated like any built-in FF widget by scrolling using a Column and a Row and infinite width or height.

### Steps to Reproduce

See the CustomWidgetScrolling example on my account for this error
1. Add custom widget using graphite DirectGraph
2. Provide data from a custom function (or use example above)
3. View on the smallest phone in landscape view.
4. Try to scroll down to see the whole graph

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tlc/qx89OxL1E0M/UcvkwmmA5KUQlarhEke1uTQ0jNurkP7MDeODRZXFJXMu4d2xUJGH8sGAIpq3Xvc7+G8ICMgqIQ75Z+pBAaQrLZD2haKanBaieeXYkP+5UCWqw0ZqOiiRvKvBudXAs2l+ALti8RXbcQYTuIVY3GPKkJqbJogupFQ/VDjhmtmNecCfn

### Context

Web App cannot be used on small screens.

### Visual documentation

![Screenshot 2023-05-09 at 11 25 18 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/121893560/ef50fac0-3428-4ad8-b405-f7db814ecf88)

### Additional Info

![Screenshot 2023-05-09 at 11 25 18 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/121893560/f485c2b9-68c0-42f3-bc0a-c03389f0b896)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Mac x86
- Browser name and version: Chrome Version 113.0.5672.63(x86_64)
- Operating system and version affected: MacOS 13.3.1 (22E261)
```

**Comment by robby-cirrus360** [comment]
Thanks, Hari.  It is not clear how to contact technical support via the project chat.

**Comment by wenkaifan0720** [comment]
Hi @robby-cirrus360. Sorry for the late reply. Has your issue been resolved? Did you delete the project associated with the bug report code?

**Comment by wenkaifan0720** [comment]
Our general rule that we don't deal with issues related to 3rd party packages. But I see that you have tried probably all the fixes that I can think of and I am very interested to investigate further.

**Comment by robby-cirrus360** [comment]
What I wanted to scroll was a custom widget based on an image.
Actually, an image of a floorplan on which I add widgets for things I add to said floorplan.

I found that InteractiveViewer was the solution and so I built this as a custom widget.

I got interrupted several times but I am closing in on a solution that seems to work.

**Comment by wenkaifan0720** [comment]
Glad to know! In this case I'll close this now.
