### ISSUE TITLE
Not able to create any Custom Function when connecting with Postgres

### ISSUE THREAD

**Issue by Ravi92sr** [FlutterFlow/flutterflow-issues#870]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a simple custom function to get the sum of list of values. But the function is showing it has errors. But the errors are unrelated to my function.

### Expected Behavior

The custom function should work without any errors. Or it should show relevant errors.

### Steps to Reproduce

Enable Cloud SQL and connect to a postgres database. 
Write a simple custom function.
Check the custom function for errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelvLl7Y91j7xb0anyKcdv/AMwJ0QlUIInj+0bWRMhfLLwE4YhPuPeXxZLYte5dGNYGWf/pGIFpqH6iuHDO/QDNQ+VQKFyz75XQTrLVnimRKWYCaqCdEBRGcFNGlCFy7WFuh0mPftiLGQ42ky2OvCrG3qCf9qOYwx5e6fDbOY=

### Context

I'm not able to create any custom function

### Visual documentation

![Screenshot from 2023-05-09 23-10-26](https://github.com/FlutterFlow/flutterflow-issues/assets/123063001/55510008-78af-4f10-a446-510763f3ddaf)

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform : All
Browser name and version (web): Chrome Version 109.0.5414.119 (Official Build) (64-bit)
Operating system and version (desktop): Ubuntu 22.04
```

**Comment by bulgariamitko** [comment]
@Ravi92sr , can you show us where did you Enable Cloud SQL and connect to a postgres database?

**Comment by victoriahuang1** [comment]
Hi @Ravi92sr thanks for the report! This issue should be fixed upon the next deploy.
