### ISSUE TITLE
A Future TimeStamp will only show a Moment Ago

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#872]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when a timestamp is being displayed as a string in an app and you choose to format the string with the relative date format it will only say ' a moment ago'

### Expected Behavior

it should be showing the same style as relative dates in the past e.g. if i were to put in yesterday it would say 'yesterday'/'1 day ago' it should say 'tomorrow'/'in 1 day(s)'   

### Steps to Reproduce

1. create a timestamp
2. add it to a text widget
3. format the datetime as a relative date
4. run in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjPLl05dJodsA0LrtYO9ViSk6JUB9aIc0rNlud0wdCeOtBIkldsjObVtWWOqHekFDe1mWoFoFwNL3huDhV8dfaCmefIc+wsxtUxDgIVumaa6pEZOKQHBPHfNWGH6l4J+vqiYmKtdtSGwE32b3Htiub3qCf9qOYwx5e6fDbOY=

### Context

i want to display future dates in a relative format

### Visual documentation

<img width="1440" alt="Screenshot 2023-05-09 at 10 08 51 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/031aec50-d34a-494e-a82c-20040a4c5268">

https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/b3525ce4-c1c9-4d40-87c7-e90854cf84d1

### Additional Info

i believe this might be an issue with the 'timeago' package i did create a function to solve for it but it might be worth it to polish it up 

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS
- Browser name and version: chrome
- Operating system and version affected: all
```

**Comment by joekman990** [comment]
@bulgariamitko  i think there was a bug report that was assigned to you that was similar to this issue

**Comment by bulgariamitko** [comment]
@joekman990 I am not sure if the code is ment to be used for future dates. :/

**Comment by bulgariamitko** [comment]
@joekman990 ,I haven't look at the package, but what if you are saying is true then this looks like a FF issue to me. I will not touch this issue and leave it to be managed by my fellow FF issue testers which this issue was assigned to  :dancers:

**Comment by wenkaifan0720** [comment]
Hi @joekman990. This is more like a feature request but I think it is a valid request. We will show future relative datetime like what you see in the demo starting from our next update. Thank you.
