### ISSUE TITLE
Record Marker not an option to be selected on the GoogleMaps widget

### ISSUE THREAD

**Issue by bravabird** [FlutterFlow/flutterflow-issues#873]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to add an action so that a bottom sheet can be shown with more information about the selected map marker.  I have set up the bottom sheet and added a document reference but I'm not able to select the marker record

### Expected Behavior

A Record Marker is selectable 

### Steps to Reproduce

1. create a google map widget with multiple markers read from a collection with latLng
2. create a bottom sheet with a document (or document reference)
3. add an action on the google map widget to show the bottom sheet
4. Add the parameter and notice there is no option to select a Record Marker 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozPLq05NgoctJ0LrUY8dKgSQvNnI/ar831MpBazAbfePwPJkQQfTORERVZNO+THx6MFmgkWoW0fDSvofqU+4DPgWYR4hPz7oBEjqVLUCjSpSXFJWvPXdDPJ9YIWKi17SN3BNAJu1hSF4M2F+IBuiAaB3DJ5yxPHoWDa/LZO4=

### Context

I cannot get the bottom sheet to show with the detail information on the selected marker

### Visual documentation

https://vimeo.com/825332242/755210124a

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/110073169/d647c7f0-c322-4078-8045-ebd05b2d6586)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: App
- Browser name and version: Chrome Version 112.0.5615.137 (Official Build) (arm64)
- Operating system and version affected: all
```

**Comment by tas246** [comment]
Did you try passing a "Document" not a "DocumentReference"?  I recall having this issue a while back and was directed to try this, and I recall it fixing my issues.  Good luck, hopefully this helps.

**Comment by bravabird** [comment]
I found this video - the functionality has changed and there is no longer a record marker.  I needed to pass the latLng of the selected marker and then filter the query using the latlng parameter

https://l.messenger.com/l.php?u=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkeNFHkgSCxI&h=AT3iY_wPtNXdiyD_ngqjSSdmkMy3arToyxsnXIEP0jk2rz1RHDgeNRLHQLrzSPlYvFFXV_8qj00a4S1x9DkkNp5Ds4wy6mHYRURAGI5arShfBOAz2w9FNn0XgGH3B59n92x7hBNxZsc

**Comment by bravabird** [comment]
I found this video - the functionality has changed and there is no longer a record marker

https://l.messenger.com/l.php?u=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkeNFHkgSCxI&h=AT3iY_wPtNXdiyD_ngqjSSdmkMy3arToyxsnXIEP0jk2rz1RHDgeNRLHQLrzSPlYvFFXV_8qj00a4S1x9DkkNp5Ds4wy6mHYRURAGI5arShfBOAz2w9FNn0XgGH3B59n92x7hBNxZsc
