### ISSUE TITLE
Keeps adding same rule in Firebase, although it is already there

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#874]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Everytime I deploy the rules to Firebase from FF because they are outdated, it keeps adding these lines, although they are already there:
`    
match /{path=**}/subStatusAfterSalesKitSent/{document} {
      allow read: if request.auth != null;
    }
`

![Screenshot 2023-05-10 085326](https://github.com/FlutterFlow/flutterflow-issues/assets/1053176/2883c460-2d9b-4438-bfcf-f6a31b092962)

### Expected Behavior

It shouldn't add this rule when it is already in the rule-set.

### Steps to Reproduce

I experience this in my project - every time a deployment of the rules is necessary. 
It seems it has to do with a subcollection:
![Screenshot 2023-05-10 085359](https://github.com/FlutterFlow/flutterflow-issues/assets/1053176/57cd12c6-fe10-414d-b6b6-896dd4a7d0bb)

I did not try this in a new project, but I still think it is worth mentioning it to the FF-team.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl8nl3891pbxH1rXuY+9VnjwWQ2Yha788msN+URA2GO/1OrYPXfikSEpWZ9+kTHxcL2eWin4xw+jHhofmA+UqMk2BQYB+1rtqFxaVXlKmMsWhDZCWX3FPL59JJVy+yqugkx57AMl1ckIR2VOACdmRUirUQLroNW0jAf/+Np/OnE2qQ0SLb3kNh1JWeC/v

### Context

The issue does not have an effect, except that from time to time I have to "clean" the Firestore-rules by hand and delete the double entries.

### Visual documentation

![Screenshot 2023-05-10 085326](https://github.com/FlutterFlow/flutterflow-issues/assets/1053176/740f7deb-f256-42a6-bb4a-3905e0ea0c03)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: MS Edge
- Operating system and version affected: Win 11
```

**Comment by hariprasadms** [comment]
Hi @webwurm - Thank for submitting the issue. I am not fully sure this can be a bug. I can mark this as bug and pass to dev team to decide. Thanks

**Comment by aemelyanovff** [comment]
@webwurm Thanks for reporting the issue.

It should be fix now. Please reopen the issue if it's still happening to you.
