### ISSUE TITLE
Video Player widget has bugs in its ability to fill containers adaptively

### ISSUE THREAD

**Issue by charliefairbairn** [FlutterFlow/flutterflow-issues#876]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to extend my bug report of the video player widget.
1. I can set the container dimensions and video player dimensions to almost anything, and it will never look right across all screen dimensions. If I take the example of the container width being infinite (or 100%) and the height blank and then the video player width infinite and height infinite, the size of the video works well in any mobile phone width. It does as expected, the video fills the full width of the phone, and the height adapts to the dimensions of the video. No white space. However, as you expand the width of the screen using first an iPad and then a desktop, rather than the video growing to fill the full width, odd things happen. Firstly if the video was shot in landscape mode, it works fine, and the video expands to fill the phone's width. But if you use a video shot in portrait mode, it starts OK as the width of the screen increases, and the video shrinks! It shrinks in both directions (relative to the size of the screen) so that by the time you get to the desktop, there is a very large white border both top and bottom, left and right. The video controls get corrupted too, the progress bar, which DOES fill the width of the screen, moves up to the middle of the video, and the actual controls disappear. 
The effect is most prominent in web mode where you can use F12 and drag the edge of the app to make it wider. On a video landscape, it adapts correctly until around 480px, but as you make it wider the whole video shrinks and shrinks until it is tiny on the screen. If the video is in portrait there is no such issue. 
An unfortunate consequence of the video controls being corrupted when the width of the screen goes beyond a certain point is that if you have some kind of list that switches from one video to another, the new video will not show. Again you can see the bug creep in during web mode, as it will work until about 480px and then changing the video beyond this width does not work unless you come out of the page and come back into it. 
2. If you do add an Aspect Ratio in the Flutterflow builder and move to another place and back to it, the Aspect Ratio will have disappeared from the field, even though it will respond as though it does still have it set. You need to add a value and delete it again to remove the effect of the Apsct Ratio.
3. If choose to watch the video fullscreen and then reduce it back again, the video goes bank. It will continue to play, as you can hear the audio, but there will be no image.
I hope you can fix thee, or indeed offer a workaround until you do, as I can't publish anything until then. Many thanks. 

### Expected Behavior

The widget grows to fill the container. 

### Steps to Reproduce

Put a video player in a widget of 100% or infinite width, blank height, and a video of infinite or 100% height and width, or no height at all. Observe the video size as you move to form a screen width of phone to tablet to desktop. Or drag the width of the screen in web app using F12.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KzMr134phnMBE7rruK/lVtCYWNjsja7sslu5ERkoYGO6uG7YUWMzBVE5uO8ehd2NiJWCi8WQJptGKhuPXGsYHPiitRYQ61aVQVQ/Me3G6MLqMPKrhRHF6Ae9Xfk+HzbunvghANtpYcXAZ7ziqI+SXbC7ANOfuPDEWAP+YVYvM+GCiAjLOXn0Jg1ZSfCvr

### Context

Unable to currently use the video width (3 bugs at least) 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/8952913/8326b47c-369c-48ab-b83f-eb0b671bbae1)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web 
- Browser name and version: Edge or Chrome, the latest
- Operating system and version affected: Windows latest
```

**Comment by hariprasadms** [comment]
Hi @charliefairbairn - Thanks for submitting the issue. Can you please setup the issue in a blank project and share bug report code of the project please. The code you have given above, is your actual project and I can't find the page name where you got the issue. Please share the details.
