### ISSUE TITLE
I was asked by the Flutterflow support-team to make a request here. When I want to import a CSV document into flutterflow, I cannot get to chose it on my deskop. When I go to manage content and click on "upload CSV", I select my CSV document on my computer but when I select it, it doesn't appear on the pop up, I can't upload it. It's like I didn't select any document

### ISSUE THREAD

**Issue by marielesimple** [FlutterFlow/flutterflow-issues#879]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was asked by the Flutterflow support-team to make a request here. When I want to import a CSV document into flutterflow, I cannot get to chose it on my deskop. When I go to manage content and click on "upload CSV", I select my CSV document on my computer but when I select it, it doesn't appear on the pop up, I can't upload it. It's like I didn't select any document

### Expected Behavior

I am supposed to be able to select the document and for it to be imported into my app

### Steps to Reproduce

1. Go to manager content
2. Click on Upload CVS
3. Select CVS on deskop
4. Choose the right separation type of the CVS
5. Import the data

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olefl0ItIosRK+KXqdcAxnSQvG2YjbYE71spBZywgfZzzBLN/fPfQPltVZOrnTG9fPlqmp14G0MLli/DhL+w4aBSabtw41rh2dA7jeDu6aZ+TF7uoZUQkHcZUJnXCyrarhhUlWbNqdE4h7F+uOe6WQh7qO4zHPEQ4Sq/LZO4=

### Context

I am trying to built an app

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/133350540/709a3b3c-29ff-47c0-953f-c02a96310ccb

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, Windows deskop
- Browser name and version:Chrome
- Operating system and version affected: Surface Microsoft
```

**Comment by bulgariamitko** [comment]
I will assume this is something browser specific as I cannot reproduce it. I made a video you can implement to upload your file if you still have this issue. Delete the cache and try again.

https://www.youtube.com/watch?v=4Ir1j6L48Lg&t=9s

**Comment by aemelyanovff** [comment]
Closing as inactive.

@marielesimple Please feel free to reopen if you are still experiencing the issue. Please include an answer to the question above.
