### ISSUE TITLE
Method 'toGeoPoint' cannot be called on 'LatLng?' because it is potentially null

### ISSUE THREAD

**Issue by gtorodelvalle** [FlutterFlow/flutterflow-issues#88]
## Expected behavior (required)
I am using a LatLng field in a collection of mine. It may be used such any other data type.

## Current behavior (required)
I am using a LatLng field in a collection of mine but I am getting the following error (no need to say that I make sure that the LatLng data is always filled in the database):

Error: Method 'toGeoPoint' cannot be called on 'LatLng?' because it is potentially null.
 - 'LatLng' is from 'package:mialando/flutter_flow/lat_lng.dart' ('lib/flutter_flow/lat_lng.dart').
                      currentUserDocument!.localLatitudeLongitude.toGeoPoint())

## To Reproduce (required)
1. Include a LatLng field in a collection. For example, in the users collection.
2. Try to filter a backend query using the logged user LatLng field created in 1.

## Your environment
* Version of FlutterFlow used: 3.0 (October 28th, 2022)
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome (latest)
* Operating system and version (desktop or mobile): Mac Ventura

**Comment by bulgariamitko** [comment]
There are several ways to filter in FF. Can you please make screen-shots how do you filter or write that step by step? Thanks.

**Comment by gtorodelvalle** [comment]
Sorry, I just saw your comment, @bulgariamitko 😃 
I am just using equal between 2 LatLng fields 😉 
![image](https://user-images.githubusercontent.com/667284/200908937-6ef849d9-53d6-4c50-b503-451d716502b5.png)
![image](https://user-images.githubusercontent.com/667284/200909045-7483a6ee-e3e9-4bad-9b74-cf794ca8f92f.png)

**Comment by agreaves** [comment]
Hi @gtorodelvalle, thanks for the bug report! I was able to reproduce and fix your issue, so it should start working upon our next deploy! 🙂
