### ISSUE TITLE
Swipeable Stack has an issue with sub-collections (probably)

### ISSUE THREAD

**Issue by pete-trak** [FlutterFlow/flutterflow-issues#884]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever I run my project and start swiping and get to the last two swipeable cards,  i get a loading icon for the swipeable stack which does not disappear. This is probably related to the fact, that the part which is not loading is a subcollection. What is weird, is that the card loads correctly behind the actual card, but once swipe the actual card, the card behind it (the new actual card) reloads and keeps reloading without any result. Making the subcollection a single time query solves the issue, but i want it to be a stream, not single time.

Additionally, the swipeable stack stutters in every swipe (see video below)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/133501056/be0420aa-fea3-4628-a941-5941ae6a7130)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/133501056/bedc235b-0791-4a40-87b8-2d6c5db4c777)

### Expected Behavior

I expect the same behaviour thoughout all swipes. Not some swipes to work and others to stutter or reload forever.

### Steps to Reproduce

Create a collection of users
Create a subcollection of data inside the users (e.g. games)

Create a page with a swipeable stack.
Create a card
Create a backend call that retrieves all Users
Retrieve user name and image for every card
Additionally, retrieve a subcollection for the user (in my case, games the user plays) (not the authenticated user, but the one inside the card)
Retrieve name of the game (either directly from the subcollection, or linking to another collection through a reference/backend call)
Display the name of the game (and other attributes)
Run the app and start swiping, the last two swipes will keep loading

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMjfsI52ocMA+Kryb/pahjs5Jlh8UIIK1+praCosfZT2BLMcec/RVERuOLyiYAhAIE2jmWoW0PPHhuzpVvVdaCmsfIRIzbhMajqUUkm5aaWVFJWgYXN6M9hmClyE4cCw2hB5B7duLSEfwDqqBfO/Vg7XQbLOIUYaDq/LZO4=

### Context

The swipeable stack is not usable like this, i would have to pivot to another way of solving my requirement

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/133501056/d3147e1e-8803-4c29-a27f-0dd1b14bf89c

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: Chrome Version 113.0.5672.93 
- Operating system and version affected: Windows 10 Version 10.0.19045 Build 19045
```

**Comment by aemelyanovff** [comment]
@pete-trak Thanks for reporting the issue, and sorry for the slow response.

Are you still experiencing the issue? If yes, could you create a new project just reproducing the issue? I'm afraid I'm having hard time following the steps to reproduce.

Also, do you see any errors in the debug console?

**Comment by aemelyanovff** [comment]
Closing the issue as inactive. @pete-trak please feel free to reopen if you add answers to the questions above.

**Comment by pete-trak** [comment]
Hello,

this seems fixed as of today.
Best
Peter
