### ISSUE TITLE
Getting blank screen when using dropdown widget

### ISSUE THREAD

**Issue by Deepu178** [FlutterFlow/flutterflow-issues#885]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

[screen-capture.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/68677868/b39d2369-72b3-40e0-9776-a6d470560c32)

### Expected Behavior

https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/form-elements-1/dropdown

### Steps to Reproduce

1. Create new page
2. Create widget 
3. Add column
4. Add dropdown widget and add option
5. Run in test mode 
6. Go to the page that contains dropdown menu
7. You will get the blank screen 
<img width="305" alt="fluttererror" src="https://github.com/FlutterFlow/flutterflow-issues/assets/68677868/a18a8767-a830-4e67-b8a5-5408e8bc95dd">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPLqx5B1m7RY15Dpbfloryg6JVw7TL07p+xEGA8rCOOtPLJ/Z8zebltWUuLiTENhHFn8rFse0Nrokt/AV+w3EE6Yft19+c1+EBaVXXq8R4S4Ec2wRXd6M8BTfUym1ruNrx5COtp1cl4Z3HGAGPKvdCrfCZu/Zwh9f6PHaOI=

### Context

[screen-capture.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/68677868/a81fb021-111d-43ba-bad5-99e3e853084f)

### Visual documentation

[screen-capture.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/68677868/52fef3f3-d7b7-4f4d-972b-0a6a27a57614)

### Environment

```markdown
- FlutterFlow version: V 3.1
- Platform: Android
- Browser name and version: Chronme
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment]
HI @Deepu178 - Thanks for submitting the issue. We know this issue. It will be fixed in future updates. Thanks

**Comment by hariprasadms** [comment]
Its duplicate with #844

**Comment by aemelyanovff** [comment]
Closing as duplicate.
