### ISSUE TITLE
Geolocator (geolocator_android) needs an update in FF !

### ISSUE THREAD

**Issue by albluwi1987** [FlutterFlow/flutterflow-issues#886]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've created a custom widget (Compass widget) in my project and compiled the widget and doesn't prompts any errors, But when I run the app on (Test Mode OR Run Mode) this error prompts **(Because calendar_app depends on geolocator ^9.0.2 which depends on geolocator_android ^4.1.3, geolocator_android ^4.1.3 is required.
So, because calendar_app depends on geolocator_android 4.1.0, version solving failed.
pub get failed)**

I've added geolocator dependency and it's up to date, however, I think **_geolocator_android_** is not updated on FF.

### Expected Behavior

It supposed to work properly

### Steps to Reproduce

1. Create Custom Widget (name: Compass)
2. Add these dependencies (flutter_compass: ^0.7.0) and (geolocator: ^9.0.2)
3. Add Full code
```
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:svg';
import 'dart:math' as math;
import 'package:geolocator/geolocator.dart';
import 'package:flutter_compass/flutter_compass.dart';

class Compass extends StatefulWidget {
  const Compass({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);

  final double? width;
  final double? height;

  @override
  _CompassState createState() => _CompassState();
}

class _CompassState extends State<Compass> {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<CompassEvent>(
      stream: FlutterCompass.events,
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Text('Error reading heading: ${snapshot.error}');
        }

        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }

        double? direction = snapshot.data!.heading;

        // if direction is null, then device does not support this sensor
        // show error message
        if (direction == null) {
          return const Center(
            child: Text("Device does not have sensors !"),
          );
        }

        return Transform.rotate(
          angle: (direction * (math.pi / 180) * -1),
          child: Image.asset(
            'assets/compass.svg',
            color: Colors.white,
            fit: BoxFit.fill,
          ),
        );
      },
    );
  }
}
```
4. Compile the widget
5. Add the widget to App Page and Run it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflfLl8ZNOm99Y15SJacZagioUJmUcTL4zlO1HcxAYGO/yPbJ/YcmkZVVWYN+7T1NhHFSZjkU0wfzruePLM/EnCwiVGd1Y+Kl9EQzNd3q8RZiNDKudPXZ9P+VRG3Km15m3qxFSVeptWkIFwFzzPemtbAXtJ5+/Zwh9f6PHaOI=

### Context

It's a key feature of my app and it supposed to guide the user to certain direction

### Visual documentation

(Test or Run Mode screen shot and the error message)
<img width="698" alt="‏لقطة الشاشة ١٤٤٤-١٠-٢٤ في ٩ ٥٢ ٢٩ م" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/58f7028f-e285-47d1-8a86-17bb5b76e5cc">

(Dependencies)
<img width="335" alt="‏لقطة الشاشة ١٤٤٤-١٠-٢٤ في ٩ ٥٣ ٢١ م" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/ba6ac21e-8d05-4c45-ab4c-42bda23e1058">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: FlutterFlow
- Browser name and version: Google Chrome v113.0.5672.92
- Operating system and version affected: IOS
```

**Comment by albluwi1987** [comment]
Any updates!?

**Comment by kevintonb** [comment]
Hey @albluwi1987 , I've tried to reproduce this issue with the steps that are mentioned and was unsuccessful. The build was successful for me. Can you please add more steps / give more context on reproducing the issue?

**Comment by CyberPolymerization** [comment]
I think FF should update other dependencies. As of this writing, they've just recently updated the flutter version of FF, and I cannot  download the APKs and has affected other dependencies.

**Comment by almantas88** [comment]
Having this problem when trying to run on a simulator with commands 'flutter pub get' or 'flutter run'

Because testproject depends on flutter_localizations from sdk which depends on intl
  0.18.0, intl 0.18.0 is required.
So, because testproject depends on intl 0.17.0, version solving failed.

**Comment by wenkaifan0720** [comment]
Hi all. Sorry for the late reply. We recently updated to the latest Flutter version and some custom code dependency issues are expected. My recommendation would be to try to update your dependency to the latest version and see if the error still exists. I see that there is no error in the project from the bug report code in this issue. If you are still experiencing this issue, please attach the bug report code. Thank you.

**Comment by victoriahuang1** [comment]
Hi @albluwi1987 , thank you for your patience. The geolocator package will be upgraded upon the next deploy.
