### ISSUE TITLE
I18n, Android only: Ukrainian-specific chars  are not displayed properly, though other cyrillic chars are ok

### ISSUE THREAD

**Issue by sergiimostovyi** [FlutterFlow/flutterflow-issues#888]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The problem is for all sources - hardcoded, firestore records, API results. The only place it seems to work fine - bottom navbar. I've set default language to EN and a secondary language - ukrainian. It was tested on 2 android phones with ukrainian interface.

### Expected Behavior

"їєі" is displayed as "їєі"

### Steps to Reproduce

1. get AAB for android
2. install on a phone and choose ukrainian language in phone setting
3. go to the registration page
4.  Sign up tab name have squares with crosses for "і" and "є" chars

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESi8rqw5dgouUD+qrAc+1qhR0jNkwmUedMl+tuFUsdfKqqGbYURPrObVtbXMjgeWxmfEyKin8xpujzhobTGPY8Ph6uQaV8/rpUVw7JVTugM7KTPbmCXXJBM9tMJ27GyrS3rRElKbd2aClpig/GSw==

### Context

Can't launch on androids

### Visual documentation

![unnamed](https://github.com/FlutterFlow/flutterflow-issues/assets/103057046/e93e369f-063b-4203-abba-9ebf968acfaa)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Android
- Browser name and version: Chrome 113
- Operating system and version affected: MacOS
```

**Comment by victoriahuang1** [comment]
Hi @sergiimostovyi , thanks for the report. The issue is due to the font choice. Not all fonts support all languages / alphabets. You can check for whether a font supports a specific language here: https://fonts.google.com/?subset=cyrillic-ext&noto.lang=bg_Cyrl.

I was able to reproduce your issue with your font in my own project. And I was able to resolve it by changing it to a font that supprts Cyrillic extended (like Roboto).

**Comment by sergiimostovyi** [comment]
@victoriahuang1 this makes sense, but I wonder maybe it's still an issue on FF, since it works fine on Web and iOS. Maybe FF includes different font packages for android? Or it's an android itself is culprit?

**Comment by victoriahuang1** [comment]
This is an issue with android + font. There isn't really anything we can do on the FF side, since we're just loading the font.
