### ISSUE TITLE
Social Share image not showing up

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#889]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The social share image does not show up when using this URL.

### Expected Behavior

It should show up the correct image when using the URL

### Steps to Reproduce

1. Enable web support
2. Add social share image
3. deploy on web
4. Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Issue in the settings web publishing

### Context

I am trying to use social previews on social media platforms

### Visual documentation

I have tried testing on different social preview testing websites
![SCR-20230516-jwdq](https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/f0c222c2-269d-4b56-9265-3efaa19d76bd)
![SCR-20230516-jwof](https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/f78d1eff-b67d-4cc3-b47b-9a7ad00bbc16)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 113.0.5672.92 
- Operating system and version affected: MacOS Ventura 13.3
```

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, it'll be fixed in the next update.
