### ISSUE TITLE
Can't select an item in dropdown menu on Firestore schema menu.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#89]
I am using Desktop app and I cannot choose a collection on firestore schema page.

![selection-box](https://user-images.githubusercontent.com/5080329/199642679-cb56c0fe-6559-4bad-8c38-155540ab7714.gif)

**Comment by bulgariamitko** [comment]
I already reported this. This should be fixed in the next FF release.

**Comment by katherineqian** [comment]
Thank you @bulgariamitko! Will close this as completed.
