### ISSUE TITLE
Firestore Rules: Deploying Rules > Insufficient Permission Error

### ISSUE THREAD

**Issue by Spellytics** [FlutterFlow/flutterflow-issues#893]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm encountering the following error when clicking the 'Deploy' button on the **Firestore Settings** screen:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70740500/5c9cf9ca-a60b-4fcf-a01f-51077435ed77)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70740500/dc62fab2-3749-4d74-a7d9-9d6a982f8768)

Issue started occurring around 3:00 AM UTC. 

**Issue has been reported by multiple Flutterflow users:**
1. https://community.flutterflow.io/c/discuss-and-get-help/missing-or-insufficient-permissions-help
2. https://community.flutterflow.io/c/discuss-and-get-help/flutterflow-has-insufficient-permissions
3. https://community.flutterflow.io/c/discuss-and-get-help/urgent-issue-with-my-ff-firebase-connection
4. https://community.flutterflow.io/c/bugs/flutterflow-firebase-breakup
5. https://community.flutterflow.io/c/bugs/firestore-rules-deploying-rules-insufficient-permission-error

### Expected Behavior

Firestore Rules deployed successfully. 

### Steps to Reproduce

1. Have a Firestore Collection ready.
2. Create a new **Collection** in Flutterflow. (Note: Suspecting that new schema is the cause)
3. Go to **Firestore Settings** page.
4. Click 'Deploy'. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

It is not related to a Widget, but the backend settings in Flutterflow.

### Context

Many users rely on Flutterflow to deploy their Firestore Rules.
This is causing users to see the 'insufficient permission' errors during run-time on their app.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70740500/5c9cf9ca-a60b-4fcf-a01f-51077435ed77)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70740500/dc62fab2-3749-4d74-a7d9-9d6a982f8768)

### Additional Info

Unsure if the root cause of issue is due to some update to Flutterflow today or Google changing some configuration in Firebase that breaks compatibility to Flutterflow. It's strange because technically you can still 'Manage Content' of Firestore collections via Flutterflow. 

**Deploying Firestore indexes** are working. 
So it's only specific to the deployment of Firestore rules - which seems to be inconsistent, since one would assume that the access management should affect both. It points that the issue is with Flutterflow. 

But Google being Google, and is as much likely to break stuff without telling you. :P

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 113.0.5672.93 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment]
Hi @Spellytics -  We are aware about this issue. It should be handled asap. Thanks

**Comment by Spellytics** [comment]
Thanks team! Confirmed it is fixed. 
We can close this one out.
