### ISSUE TITLE
Optional Query Param's are being populated/included in URI path even when empty

### ISSUE THREAD

**Issue by bozau** [FlutterFlow/flutterflow-issues#895]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After uploading a Swagger JSON from the API Calls screen and attempting to perform a call to my API endpoint without specifying any query parameters (because they are optional) the API call out from FlutterFlow has them either empty or null.

Example call;
```
https://domain.com/endpointname/v1?OwnerUUID=&SortBy=&OrderBy=&Limit=null&Offset=null
```
I suspect that this has something to do with how your OpenAPI/Swagger processor can't handle when parameters don't have a 'required' field which in Swagger V3 is considered optional;

Specification with and without a required query parameter;
```
  "paths": {
    "/endpointname/v1": {
      "get": {
        "tags": [
          "endpoint"
        ],
        "operationId": "EndpointnameGetV1Endpoint",
        "parameters": [
          {
            "name": "OwnerUUID",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "SortBy",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
```

### Expected Behavior

The uploaded API Swagger spec should be correctly reflected by FlutterFlow API call, optional (or non-required) query params should not be included in the call as per the OpenAPI specification: https://swagger.io/specification/

Parameter Object
Fixed Fields
Field Name | Type | Description
-- | -- | --
required | boolean | Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

e.g;

```
https://domain.com/endpointname/v1
```

### Steps to Reproduce

1. Get Swagger JSON with the following OpenAPI Version: `"openapi": "3.0.0",` and same query parameter setup (with and without required). You could also try this with one API spec having no required params and the other WITH required API params, this might make testing more clear cut
2. Upload Swagger file via API Calls Screen.
3. Without modifying the API Call, create an API call from a flutter page, setting and passing no query params except the required field if one exists (set Bearer if API is auth based)
4. Verify that the API call outgoing URI from Flutter includes or excludes the optional query parameters, there should be only the required one if one exists.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CiMjfz8p2rsRE18/QccBvmSQsKUg4RYJJmu1Tbxc0DZPMC+wIZ/f7XFRuTde0TUFEf2f8mnkfzN3emvPAUvYDHzerf4A/yJFfWjzMczuVVqaWDaqgWm5/DfFTG2qz0Z273xR5D7ZhL10j12GUBfOWcDbfHpzvPWovAv6hLZOK2SrDX1iXc2URm05KZDPz

### Context

This issue is a show stopper for importing Swagger OpenAPI v3 spec's and performing any API call that contains optional query params, as they will not succeed in the API call.

### Visual documentation

Swagger Visual;
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/24667304/27cf5aa5-05f6-4902-8244-19f516afb062)

Server-side API Log;
2023-05-18T03:00:26.646805136Z info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2023-05-18T03:00:26.646818120Z       Request finished HTTP/1.1 GET https://domain.com/endpointname/v1?OwnerUUID=&SortBy=&OrderBy=&Limit=null&Offset=null - - - 400 - application/problem+json 4.5561ms

API Spec within the FlutterFlow screen;
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/24667304/0797a4d5-4931-48b5-9539-e5c68cee2b1c)

Widget OnTap action screen;
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/24667304/2f4f4c9c-9e1f-4c1d-8dbc-4b58508b1268)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: iOS/Android
- Browser name and version: Brave v1.51.118 (64-bit)
- Operating system and version affected: Windows 11 22H2 22621.1776
```
required	boolean	Determines whether this parameter is mandatory. If the [parameter location](https://swagger.io/specification/#parameter-in) is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

**Comment by bozau** [comment]
Hi @aemelyanovff  and @SameerShahzad99 ,

Please let me know if you require any further details, happy to help as much as I can.

Cheers.

Boz

**Comment by bozau** [comment]
Hi @aemelyanovff and @SameerShahzad99 ,

Trying to keep this issue from being marked as stale.

Cheers.

Boz.

**Comment by aemelyanovff** [comment]
@bozau Sorry for the delayed response.

FlutterFlow does not support optional query parameters at the moment. If a value is not passed to an API call, the default value will be used.

Could you submit this as a feature requests through the in-app feature request tool? [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help).
