### ISSUE TITLE
Custom Dialogs Do Not Resize After Update

### ISSUE THREAD

**Issue by andrewjhop** [FlutterFlow/flutterflow-issues#897]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom dialogs are fixed to the screen width on load.

For example, if I load a 900px wide container, in the center of the screen, it *maintains* the distance from the left hand side of the screen when I alter the screen width from the right (on web, in this case).

### Expected Behavior

I have all my custom dialogs set to a width of 900px, centered in the middle of the screen. On resize the dialog would remain the center until the screen width became less than 900px, at which point it would snap to the screen width.

### Steps to Reproduce

1. Open any custom dialog (I use it a lot now)
2. Resize window

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci8/qx4l2mOZE0LXuKcExhSQRQ1wmRY030MJHQkw0N5PKDYkIec/9TBNoQtekTFc3MVn8hXMKp87LvszIN8ECJUmYY6J+zYdcYA7wJHy6Moy7Bs2VdXYlBtpKC0y/5rergR1NLrF0SVY971yEB+miZDDqQrLqDGsWDcmZNdv7o3/uQ0SLb3kNh1JWeC/v

### Context

My previously responsive design is now no longer responsive.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111100388/71b59c8d-aabf-42c3-b348-40d747bdda87)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Mac, Web
- Browser name and version: Google Chrome
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
@andrewjhop is it possible to share with us your settings of the widget on the right side?

**Comment by hariprasadms** [comment]
Hi @andrewjhop - I think I can re-produce the issue. See below video. Please confirm if you are seeing the same behaviour. 

As @bulgariamitko asking, please share setting details as well. It helps us to understand exact issue whats happening at your end. Thanks 

Thanks @bulgariamitko 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d446e8f4-b26e-4da1-9100-16e2099d040d

**Comment by andrewjhop** [comment]
The action settings changed over the recent update, so the bug was discovered because I updated FF and saw the change in behaviour. Everything is set to NULL as below, but I've experimented with altering every setting and can't seem to replicate resizing as prior to update.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/111100388/89e3b27d-d70f-4d83-9bdb-47b6246f8a5e)


@bulgariamitko @hariprasadms

**Comment by wenkaifan0720** [comment]
Hi @andrewjhop. Is your issue still happening? I looked into your project and couldn't replicate the issue.

**Comment by andrewjhop** [comment]
@wenkaifan0720  don't rely on my project, I've altered every instance of custom dialog and the components they open to try and fix the issue! But yes, it's still happening.

**Comment by wenkaifan0720** [comment]
OK I've figured it out. This is actually a behavioral change on the FF side. If you want the original behavior, you can set the alignment directly for the dialog component. When we now open the dialog, we don't update the dialog's location dynamically (based on the screen size), otherwise the align with the target widget would not work.

**Comment by andrewjhop** [comment]
@wenkaifan0720 can you recommend what those settings might be? I've tried (seemingly) every possible combination and nothing results in a responsive build like before.

**Comment by wenkaifan0720** [comment]
I meant the alignment setting for the outermost container of the dialog component.

**Comment by andrewjhop** [comment]
@wenkaifan0720 it's pretty hard to settle on a design when basic elements change from update-to-update.

**Comment by andrewjhop** [comment]
![explain](https://github.com/FlutterFlow/flutterflow-issues/assets/111100388/5353c666-086b-4351-b29c-331ffe0d2abc)

@wenkaifan0720 How does this make sense then? The component has a container with 100% W & H, so why is that being supplanted by the static screen width (pictured) when the screen width increases. It seems to respect the width and height when the screen width decreases.
