### ISSUE TITLE
Box Shadow Color Set From Variable Not Actually Set From Variable

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#898]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon setting a Box Shadow Color from a variable, the color isn't actually set from a variable, but the color remains the same as it was before setting it from the variable. Let me explain visually.
The underlying color is "#33000000":
![Screenshot 2023-05-19 at 10 20 20](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/eafecf9c-1e13-492b-9b56-288a93f96fb3)

Now I change this color to be set from variable:
![Screenshot 2023-05-19 at 10 21 16](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/719ac179-8e94-491a-a071-4b06d1abd038)

Now when you check the custom code for this widget, the following is written:
![Screenshot 2023-05-19 at 10 23 15](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/2bdfb0d3-c8aa-43e5-85d7-d425a968233f)

In the code we see that the color of the box shadow is still the same "underlying" color set in step one. The code wasn't re-written to take account the "from variable" part. 

### Expected Behavior

We would expect for the code to be re-written to take account for the "from variable" set. This would also reflect in the project as now it would visually be set from variable too.

So in this case the code would look something like:
```
color: FFAppState().filter == true
                  ? FlutterFlowTheme.of(context).primary
                  : FlutterFlowTheme.of(context).secondaryBackground
```

### Steps to Reproduce

1. create new page
2. add container
3. set Box Shadow Color to something like "#33000000"
4. set Box Shadow Color to be "From Variable"
5. check custom code for that container

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkMmAuI92mOZE0K6JY+9VmSQWGDs+bec3l+1DYCs8JJToPLAUZ8zBM05vZr2lTH9qM2CGjT4yxvfqiNjAG/koZCibQLZxyLtUFzyWVj2gaJjUO6jgfW1QLJtWN0C558Ks2x1BOu9ZLSEG3U+uOfO8RXXqNLLIDkcFAMiLJdeK2SrDX1iXc2URm05KZDPz

### Context

I want a container to have a Box Shadow when it is not clicked, and not have any shadow when it is clicked.

### Visual documentation

Explained above.

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: MacOS
- Browser name and version: Chrome - 113.0.5672.92 
- Operating system and version affected: All
```

**Comment by vishalagarwal2** [comment]
Hi the issue has been fixed and will be applied very soon in our next deploy.
