### ISSUE TITLE
Cannot set the Reference Type of App State Variables correctly 

### ISSUE THREAD

**Issue by MaggieThomann** [FlutterFlow/flutterflow-issues#901]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello!! I'd like to create a new app state variable of type `List < Doc Reference (users) >`, but when I specify that the "Reference type" is "Users", the app state variable is just created as a generic `List < Doc Reference >` and then when I try to refer to it in an action tree that requires `List < Doc Reference (users) >`, I am unable to do so.

### Expected Behavior

I would expect to be able to successfully create an app state variable of type `List < Doc Reference (users) >` as I have done this in other projects and it seems like the selection for "Reference type" is suddenly broken.

### Steps to Reproduce

1. Create a new app state variable with the type as Document Reference and a specific collection in Firestore (eg: users).
2. Attempt to refer to that app state variable in an action tree that requires a certain variable type and it won't work because the app state variable was created with an unknown Reference type and just a generic `Doc Reference`.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kh8/lsM92pbwF1s7tbe1agSgsKWF8TL07ttYbZxUjIuPtBJh/Zc/OSEhCQuKlSlNhHFmloEUy0c7Nkdj9VMIVOUmqbLo61ZZUbQHyXXq8RYTWEbuBOGtPJ/pmBUyc3Ku33BFSJfhaWCU562GMHtmtSi7dN5u/Zwh9f6PHaOI=

### Context

I'm trying to set a hardcoded list of User Document References as an app state variable and am currently unable to refer to that variable because it's not set up properly.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/15825518/39b8df3d-390b-4e5d-bfcf-640c4fbdfe7f

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Version 113.0.5672.92 (Official Build) (arm64)
- Operating system and version affected: 13.2.1 (22D68)
```

**Comment by hariprasadms** [comment]
Hello @MaggieThomann - Thanks for submitting the issue. I agree this cab be a bug. Thanks

**Comment by aemelyanovff** [comment]
@MaggieThomann Thanks for reporting the issue. It'll be fixed in the next update.
