### ISSUE TITLE
Build filed if using custom data type in "array contains" filter in firebase collection query.

### ISSUE THREAD

**Issue by ggabrovski** [FlutterFlow/flutterflow-issues#902]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Build filed because custom data type was used as filter parameter in array contains collection query.

### Expected Behavior

I expect to be able to use custom data type as filter parameter.

### Steps to Reproduce

1. Create new project
2. Create custom data type
3. Use this custom data type as filter in firebase collection query
4. Run the app
5. Build filed

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ez/Hqx89gocMB187qb8FR/TssKVgnRY0v1+xudAw2GJSsPO0MOuj+QG9tUsvieFZiJWf/8Dsxp+jFhuPLUcc9PiicY4A6z6tyUjrwfzq6MbqJPs3pWXYkN8NTG22Hzbu3mBZ4NvhpSkYM61OULvO9UT3rHoTJPFYdGvyXDJ3On0qUHBzOXn0Jg1ZSfCvr

### Context

I cannot querying firebase collection using custom data type.

### Visual documentation

<img width="880" alt="Screenshot 2023-05-19 at 16 30 10" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24413349/d8bf1af8-4f4b-4bc5-ae0c-047f526cf9ef">

<img width="912" alt="Screenshot 2023-05-19 at 16 29 39" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24413349/077687b5-186b-4a24-85bb-ca5db7708884">

### Environment

```markdown
- FlutterFlow version: 3.1 released May 19, 20223
- Platform: Web
- Browser name and version: Google Chrome Version 113.0.5672.92 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.3.1
```

**Comment by hariprasadms** [comment]
Hi @ggabrovski - I have looked at your project and see you are trying to use **create data type** option as a filter while query documents from firestore which is technically not possible. In array contains, you should specify a clarification data type. You can choose to pass datatype (clarification type ) in run-time or store a datatype ( clarification type ) in appstate and pass that in the filters. 

I can confirm that, data type and fire-store filter feature is working as expected. 

<img width="878" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/fca9dd2b-20f5-4e14-9468-8964e8be1906">

**Comment by ggabrovski** [comment]
Hi @hariprasadms thank you for the detailed explanation I will follow your advice, sorry for the noise.
