### ISSUE TITLE
build_runner not included in dev_dependencies when downloading code

### ISSUE THREAD

**Issue by 9PieceNugget** [FlutterFlow/flutterflow-issues#904]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I download my code from Flutterflow, the pubspec.yaml file doesn't include build_runner in the dev_dependencies, which is causing this line of code to fail: flutter packages pub run build_runner build --delete-conflicting-outputs

Incidentally, analyzer and built_value_generator are also now missing from the pubspec.yaml. 

### Expected Behavior

Normally these dependencies are included in the pubspec.yaml. In fact as early as two days ago (May 18th) it was included, so this seems to be a recent issue!

### Steps to Reproduce

1. Download code
2. Check dev_dependencies in pub_spec.yaml

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WksrlvJdOm8NA7arPbflFiioUNkA5UI03icN9SgIbNY+rPaYPQfvRUBZoTL3gTwhmf2Gaq3Ed7PfqvvzDK/BcHwmBG75lzbpAdhbiID+RR8SaPpezfW1TL95QI3KX4aTU2SJBLtZ1LFUsw1OmevOREnPYJ5O2IVcSDfilKdeK2SrDX1iXc2URm05KZDPz

### Context

I wasn't able to deploy my code to Firebase Hosting until I manually updated the pub_spec.yaml file to include the same dev_dependencies that were present in a pub_spec.yaml file which I had from a previous Flutterflow code download from two days ago.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/134110948/de3709fe-d4cf-4fc8-aaee-29adfc566767)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v3.1 released May 20, 2023
- Platform: Web, macOS Desktop
- Browser name and version: Chrome 112
- Operating system and version affected: macOS Monterey 12.6.3
```

**Comment by hariprasadms** [comment]
Hi @9PieceNugget - The difference what you re observing is one of the change as per latest FlutteFlow updates. As per latest change, Firestore Record and Data Struct code to no longer rely on .g. files. So build_runner dependencies no longer required. Thats the reason when you download the code, FlutterFlow does not suggest build runner code to run in terminals ( As per till previous updates, It used to deploy on each code download).

If everything all right at your downloaded code, once get packages is completed, it should be ready to run with no error. Once your project is running locally with no issues, you can deploy that to  Firebase Hosting. 

Let know more details if my understanding is correct. Thanks

**Comment by 9PieceNugget** [comment]
Hi Hari, thanks for the clarification. Can confirm it works without running build_runner. Would be good to have some release notes with these changes as I had checked the website for release notes but couldn't find any!

**Comment by bozau** [comment]
> Hi @9PieceNugget - The difference what you re observing is one of the change as per latest FlutteFlow updates. As per latest change, Firestore Record and Data Struct code to no longer rely on .g. files. So build_runner dependencies no longer required. Thats the reason when you download the code, FlutterFlow does not suggest build runner code to run in terminals ( As per till previous updates, It used to deploy on each code download).
> 
> If everything all right at your downloaded code, once get packages is completed, it should be ready to run with no error. Once your project is running locally with no issues, you can deploy that to Firebase Hosting.
> 
> Let know more details if my understanding is correct. Thanks

Hi @hariprasadms ,

The FlutterFlow documentation does still discuss the use of build_runner: https://docs.flutterflow.io/deploying-your-app/testing-your-app/testing-on-mobile-device#2.-opening-the-project-in-an-editor-android-studio

I also just ran into this issue with the build_runner by following these instructions.

Cheers.

Boz.

**Comment by hariprasadms** [comment]
Thanks @bozau - We will update the doc shortly. Thanks

**Comment by hariprasadms** [comment]
Closed the issue as it is related document update and not a bug in functionalities.
