### ISSUE TITLE
unkown error with supabase backend and customcode

### ISSUE THREAD

**Issue by gasserwshalaby** [FlutterFlow/flutterflow-issues#906]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FF builder shows an unkown error in the error section, and refuses to generate test mode session or generate a run link. it was working perfectly well 2 hours ago. i have an expired session which i regenerate test modes from.otherwise. i am locked out of testing the app

### Expected Behavior

it is expected fpr the CC to compile well and be able to generate run links and test links

### Steps to Reproduce

1. create an app with supabase backend
2. write some CC with supabase authentication
3. you may or may not face the error, as it happened ubruptly without any major changes to the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Chcr1sM9Pj7xe7arUbPlVnSQWCDsmRYIWmNZDdw4jDZPMC+wIZ/f7XFRuTde0SnNiPWH9pGIJzMnemvLxUfkEC0ycc5w+/4dcZTvNXkihVa6oOrqdOG5/DZ9NCmqa57eF3SV5JtdhSFI622D7GvDIFxfDNO/RIjE7JPyaOZCK2SrDX1iXc2URm05KZDPz

### Context

i cannot generate test sessions or run links for my app.

### Visual documentation

<img width="1680" alt="Screenshot 2023-05-20 at 5 38 48 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/107878826/69384d2b-abc1-4d46-a0f9-0849d05a3238">

### Environment

```markdown
- FlutterFlow version: 1.1.72
- Platform: MacOS
- Browser name and version: FF Mac App 1.1.72
- Operating system and version affected: Mac os ventura 13.4
```

**Comment by hariprasadms** [comment]
Hi @gasserwshalaby - The above issue steps are not fully helping us to reproduce the issue. Also, blank project is not setup with issue reproduce details. I suggest follow below steps and share more details with us to investigate the issue. Thanks

1. Reproduce the issue in a blank page and share project bug report code with us.
2. Download code and run locally and see what error you can see. Share those error details to us. 
3. When you see errors, check what error you can see in browser console. Share those details to us.
4. Record a quick video which can failure and error details. Update issue with this details. 

Thanks,

**Comment by EmersonFJ** [comment]
Check if you have created a custom data type; the custom data types appear to break custom actions and custom widgets

**Comment by agreaves** [comment]
Hi @gasserwshalaby, this is the same issue as #899, which has been fixed on our end and will likely be deployed soon. Thanks for the bug report! And apologies for the inconvenience.
