### ISSUE TITLE
Animations are not working as expected

### ISSUE THREAD

**Issue by mehmetkemalbayer** [FlutterFlow/flutterflow-issues#907]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Health.ai template scale effect is:
begin(1.0, 0.0) end(0.0, 1.0) 

### Expected Behavior

Health.ai template scale effect is:
begin(0.0, 0.0) end(1.0, 1.0) 

### Steps to Reproduce

Run application
Click book appointment

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk8iB25NIseFC+Kr+bsBB/WMWHEw7UK8WscpCbw4bIYj2P4lzY876PlpBTbSqd1ViO06cp141wez8voXXIe5cPT6eQJhIzbViWjrxQkSVVaWTF7W0ZHZTP+5nCWqb1sKRsxRBLvJhR3wu12euJuvKdA3bNpjSCmo8Sq/LZO4=

### Context

Elements in page disappears

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/7826969/a56e3d4a-1120-4ffc-bbb7-7b4b715c0c2c

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Android Emulator
- Browser name and version: Pixel 3a API 31
- Operating system and version affected: macOS Venture 13.3.1
```

**Comment by wenkaifan0720** [comment]
Hi @mehmetkemalbayer. I made a test project (https://app.flutterflow.io/project/flutterflow-issue-907-sxrf4m) but couldn't reproduce the issue.

**Comment by mehmetkemalbayer** [comment]
@wenkaifan0720 because you still need to start the template that I mentioned.

**Comment by wenkaifan0720** [comment]
Gotcha. I'll let the designer who created this template to update it. Thank you!

**Comment by hariprasadms** [comment]
Closed the issue as it is related to template modification and not a bug in functionalities.
