### ISSUE TITLE
Swipe Back to "Navigate Back" Gesture on iOS not working

### ISSUE THREAD

**Issue by SamyKhara** [FlutterFlow/flutterflow-issues#908]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The default page transition on iOS is "Slide" and not "Instant". When I override the default transition to "Instant", the swipe to "Navigate back" feature gets disabled. Throughout the app on iOS devices, I am unable to swipe to "Navigate Back". It is not a particular page-related issue.

We asked this question in the community as well- https://community.flutterflow.io/c/discuss-and-get-help/swipe-back-gesture-ios

### Expected Behavior

Swipe to "Navigate Back" should remain with or without overriding the default transition. The swipe transition itself should be "Slide" and not "Instant". This is normal behavior across all other applications on iPhone.

### Steps to Reproduce

1. Theme settings -> Override Default Transition
2. Transition Type -> Instant

Swipe to "Navigate Back" stops working.

![Screen Shot 2023-05-20 at 1 48 40 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/f8fccb5c-7874-402f-8138-6dff332ff8fc)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcmAsIV2pbxY17X5bcAw9TwsJU99TLJEoOxhYzsgF5D4BKQQeczBP0xpXfazaHx+AWaiq3EJpPD1jtnpJvQ5Ez6Abpg4yZB2ERPPbH6uVLaPPc28RHRtL/tXBWKF0baZvBUkNvNaWGAO7E+lfuSiZz6Cf9qOYwx5e6fDbOY=

### Context

I am trying to achieve the following-
1. Override default transition so that it can be instant for both Android and iOS.
2. Maintain the swipe to "Navigate Back" gesture.

### Visual documentation

![Screen Shot 2023-05-20 at 1 48 40 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/3712b5a8-c938-4362-99ca-24713fac9da6)

### Additional Info

Throughout the app, all features are enabled to ensure swipe to "Navigate Back" works. But overriding the default transition disables the gesture.
<img width="269" alt="Screen Shot 2023-05-19 at 10 40 10 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/cfa590ef-7c86-4c22-9245-662cfc9f2736">

### Environment

```markdown
- FlutterFlow version: v3.1 (3.7.12 released May 19 2023)
- Platform: Web
- Browser name and version: Chrome 113.0.5672.126
- Operating system and version affected: iOS
```

**Comment by aemelyanovff** [comment]
@SamyKhara Thanks for reporting the issue.

I'm afraid it's not something we can fix, custom transitions in Flutter don't support swipe back gesture. Reference: https://github.com/flutter/flutter/issues/101696#issuecomment-1099603781
