### ISSUE TITLE
Text widget actions don't fire if text is "Selectable"

### ISSUE THREAD

**Issue by wrunk** [FlutterFlow/flutterflow-issues#91]
Perhaps this is a known quirk, but it seems that if you attach an action to a text widget (on tap) that action should either fire, or there should be an error not allowing you to save said action (or perhaps selectable feature should be disabled)

## Expected behavior

If you attach an action to a text widget (on tap) that action should either fire, or there should be an error not allowing you to save said action

## Current behavior

If you attach an action to a text block where selectable is enabled on the text widget, nothing will happen when you try to tap the  text, no errors are shown and nothing about this is mentioned on either the selectable field or in the actions section

## To Reproduce
- Create a text widget
- Keep settings default (therefore selectable will be true)
- Add an action such as a simple alert box 
- Try to run such an example and tap this text
- Nothing should fire

## Context

Adding a lot of "terms of service" type text that needs to be tappable to take the user to various external links

## My Environment

Platforms tried on: debug mode on chrome, published webapp
FF Version: 3.3.4 (oct 28)
Browser: Chrome Version 106.0.5249.119 (Official Build) (arm64)

Thank you!

**Comment by hariprasadms** [comment]
I can reproduce this. actions on text widget does not work when text is selectable.

**Comment by organicnz** [comment]
@wrunk thanks for the find. Yeah, it's reproducable :)

**Comment by wenkaifan0720** [comment]
@wrunk You are right. Selectable doesn't work well with other gestures. After the next update a project error will be displayed if any action is set for selectable text widget.
