### ISSUE TITLE
math equation and symbols not rendering 

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#910]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the math symbols and equations are not displaying properly 
![download (45)](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/ddcb762c-c0f3-4fd8-b027-d1c991f6c44a)
![Screenshot 2023-05-21 164454](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/19763eab-cc38-475f-a1a9-3ee88cc17c38)

- all e-learning texts are affected by this issue

### Expected Behavior

the math symbols and equations must render properly like this 
![download (46)](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/8b2a356b-a3fc-4431-917c-b05533df66e4)

### Steps to Reproduce

- create the open ai chat gpt - chat as given in the FF blog
- now ask any questions related to math / integration etc 
- if the reply contains equations and formulas it is not rendering properly

tried different fonts for math as well - still not working 
the same api from postman display formulas correctly- so no issue with api 

![download (47)](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/607a5131-07b8-422e-a4cd-928a46965c28)

- 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiPLl25N2rs8G0JfxbflvoCkvJkAnaucolu1DTQ4gIr3kG7l3WvfObhJUOde4YwlIOGGakjkX/MrKi+PQV+1dGyidQKpxzKgJVTngTXKQMoSWDoS3b3dfO9pRIX6A58PUvxNDOrN1Snwfw0y6Au+tUnHrGIf7DEYvNOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

my app is eLearning services - this is causing issues for learners 

### Visual documentation

![Screenshot 2023-05-21 164454](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/8eba34b1-92a9-4e45-b512-ec94844af57f)
![download (45)](https://github.com/FlutterFlow/flutterflow-issues/assets/37708853/b14656cc-b2bd-4377-95e4-8ddf5fa9cbea)
 even in FF dashboard it is not rendering properly 

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:web
- Browser name and version:chrome Version 113.0.5672.127 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

**Comment by wenkaifan0720** [comment]
Hi @padeepz. I believe you need to enable `Decode Response as UTF-8`. 
![iScreen Shoter - Google Chrome - 230521110228](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/b5864d93-3e16-4d98-b679-a92a97a846c8)

**Comment by hariprasadms** [comment]
Hi @wenkaifan0720 - Thanks for looking at the issue. I just changed the status to 'need more information'.
