### ISSUE TITLE
Progressbar don't allow to add value if component

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#911]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I create a component from the progressbar and create a component parameter (progress) then I am unable to add value to the component. 
There is a big grey rectangle or the component don't save the value

### Expected Behavior

If I use a component parameter it should save if I add value to it.

### Steps to Reproduce

1. create a page
2. add a progressbar to it
3. convert the progressbar to component
4. add component parameter (double)
5. in the progressbar properties add the progress value from the component parameter
6. navigate back to the page where is the component and observe that there is a big grey rectangle in the sidebar. Or if you add a value to the parameter it won't persist.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otIsdtK0LruYO9WhiUXJW5/a5c0sd4bGA0dCJzuPLMQdvXsahRuTsyoY1Z2e0Smmlgy0/DUkoThKu1fGzSefNxxyc8JTAuWQj+Va5OBPZOZOHZSJ+9YFWa738KJpAl4IsxtWFIg7V6IOvKuSgXvCZi2IlFISq/LZO4=

### Context

I want to place a progressbar to a pageview and add different values to the component based on the page number

### Visual documentation

In a blank project:
![CleanShot 2023-05-21 at 19 38 35](https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/5a7f063c-1c8e-4f95-ad7e-2523b9c25109)
![CleanShot 2023-05-21 at 19 38 57](https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/fb913dfc-d282-44c5-a95c-e8c43ebca01f)

in the project where I observed this:

https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/bd3230d4-33a5-4016-94f9-a90de7809579

### Environment

```markdown
- FlutterFlow version: 1.1.73 Flutter: 3.7.12
- Platform: macOS 
- Browser name and version:-
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by hariprasadms** [comment]
Hi @kicsijohn - Thanks for submitting the issue. I have tested it and it works fine for me.  It looks like issue is project specific and not consistent. I suggest create a new component in a new page and see how that works. I can mark this issue as project specific bug.

**Comment by kicsijohn** [comment]
Hi @hariprasadms - I created a blank and recreated the issue. It doesn't show the grey rectangle but the component doesn't save the value that I give
See the video:

https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/2c385e24-d379-4fb8-89ea-d347822ffec9

I tried to run my original project locally with this component but it gives a null check error

**Comment by kicsijohn** [comment]
Oh now I see, it's a Mac app issue, it is working on the web for me either, but within the Mac app it doesn't

**Comment by agreaves** [comment]
Hi @kicsijohn, thanks for the bug report! I've identified and fixed the bug, which you should see fixed on the next release. That's very interesting that it is only on Mac, I saw the same thing as well.
