### ISSUE TITLE
Can't create documents reference in App State 

### ISSUE THREAD

**Issue by mdrashedbinkuddus** [FlutterFlow/flutterflow-issues#913]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created an app state ref for users/any other doc. Its created successfully. But when I saw it, it doesn't look ok. 

Its looks like - DocumentReferrence<>

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45509476/30a88495-4342-4133-b448-cdc7ff517107)

Local State for testing

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45509476/6fbdffbc-6c15-4674-bf48-076b5f3ede2b)

Result when I tried to use that

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45509476/b8b7c183-1a6a-4986-984b-9122376f039f)

### Expected Behavior

It should look like this. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45509476/703331dc-abc1-4917-b3ae-38e7c56737ed)

### Steps to Reproduce

1. Go to the app state or local state
2. Create a new documents reference for any Firebase doc
3. Save it
4. And then you can see it.
5. Try to use that app state for any other firebase query. You can't use that

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjMrq05NgoekB1arqde9apGMUHFw+bJc0ht1EWQ4gF4juPLMiTfSlVFJuOLCRSmNceWH8/W0z+t7Vhtr1U+5cHByJY4RH/88JazriLX26VrarPJOzOUF9P9JmCkCxzpuWkSVSIvhocloQ22C6I+q/EnTsN77MOzINBPilOqX7s1aQAA3eGn0Jg1ZSfCvr

### Context

I tried to send a user ref to a chat screen. But for that error I couldn't do that,

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45509476/096ba2fe-76b6-445d-a93a-23e0d0d8bb1f)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45509476/e6fb7865-8ebc-4329-a170-1decd264510c)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: All the platform
- Browser name and version: Chrome
- Operating system and version affected: Win 11
```

**Comment by hariprasadms** [comment]
Hi @mdrashedbinkuddus - Thanks for submitting the issue. I can reproduce the issue.

**Comment by aemelyanovff** [comment]
@mdrashedbinkuddus Thanks for reporting the issue. It'll be fixed in the next update.
