### ISSUE TITLE
Data Type not available as option in App State

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#915]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot add field of type "Data Type" as the option in App State (local storage) doesn't exist:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/a586dee2-566e-4c00-bf9c-687876ae80e1)

It shows in page state.

### Expected Behavior

Have "Data Type" as an option.

### Steps to Reproduce

add a field to app state, the data type option is missing.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8shsrqx5NgoctZ1s7ide9VoGA5KW4/bZIaluwadw8gGJD2PewTe+D4RFNWUu7ma1w/HFmWoDsIp97QuM7DDMIoORSIQ71yz5dcUBbJcEKlV4yoEsy0OkdAQMZMGB275JqOih1+OrRiLyws3DuyH97IbC7sHoDEOVUBI+aaKZDAp2iqAA++OzhmtmNecCfn

### Context

i cannot use the feature, and therefore cannot complete functionality in app.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/b2b775a7-e81b-4f1b-8ccc-b28014a0d7d0)

### Environment

```markdown
- FlutterFlow version: 3.1(3.7.12)
- Platform: windows
- Browser name and version: chrome 113.0.5672.127 (Official Build) (64-bit)
- Operating system and version affected: all.
```

**Comment by OldFred2023** [comment]
How can you say it is "not a bug" when the feature that is supposed to be accessible to everyone is not here, the image clearly shows it is not there when it is supposed to be.  A bug is when something deviates from its intended design, and this clear is as everyone is supposed to use it.

**Comment by hariprasadms** [comment]
Hi @OldFred2023 - I agree with @kevintonb status. At this stage, if the project does not have deep linking enabled, data type option is not visible in that project. We are aware about this limitation. We have plan to make it possible in future builds. For now, I would suggest enable deep linking in your project and see how it works. Thanks
