### ISSUE TITLE
SwipeableStack compilation error

### ISSUE THREAD

**Issue by mateuskiper** [FlutterFlow/flutterflow-issues#916]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A SwipeableStack containing a Card with a Stack of an Image, a column with a FlippableCard and a row with two buttons that replicate the SwipeableStack action of swiping left or right. When swiping to the right, a firebase update action must be performed.

### Expected Behavior

The build is failing due to a compilation error.

### Steps to Reproduce

1. Create a Firebase database with some documents with fields:
  - word: string
  - img_path: string
  - learned: boolean

2. Create a collection in FlutterFlow with the same fields.
3. Create a blank page and add a AppBar and a Stack.
4. On the Stack add an IconButton with an action that redirects to the same page and a SwipeableStack.
5. In SwipeableStack add a Card with a Stack.
6. In the Stack add an Image and a Column.
7. In the Column add a Card and a Row.
8. In the Row add two IconButtons with the actions provided in the attached images.
9. On the Card add a FlippableCard with the Card Front and Card Back containing a Container with a Text.
10. In the SwipeableStack add a backend query and an action according to the attached images.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Whc+A5Yh2octZ1rrtbcAxnjgsQ3k7ULsrjMNxZEgjIuv2BIwPV/ilYlJvTdO6d1Z2JVb9mmMJpuzZvvzDUvkFHwSuf49q3bpIUAziZGqgabXRO7i0VXdRM/JRCECPyLen2gx9FPJiLlIX32CxN96uSnfXJufxIlY/GP2LNoDVjGjmAiXBCCxq0idecCfn

### Context

I'm trying to create a SwipeableStack containing a card with a stack of an image, a column with a FlippableCard, and a row with two buttons that replicate the SwipeableStack action of swiping left or right. On swiping right a firebase update action should be performed. But the code is not compiling.

### Visual documentation

Compilation error:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/103db983-6f59-48cf-a1d6-a6e4844f2ed7)

Widget tree:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/e2ed46f9-005c-41c6-9aa3-289a43093153)

Icon button action:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/317939c4-fd51-4c06-9a9d-8b6a567daf77)

SeeAgainButton action:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/16af576e-c0e9-42a3-88dd-440da2019a3c)

LearnedButton action:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/04db67b6-ef3a-4c83-8db1-87491a6c77dd)

SwipeableStack action:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/cff9bdd0-f14b-408d-9c34-c831931d7ceb)

SwipeableStack backend query:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/b7d1b57d-db1d-4aee-a135-77fa4925cd59)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/2eaf1b51-3c87-4405-ab40-0c3ef466dacd)

Collection:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/53303454/afe3c74b-74cf-4e70-b017-f8ed74f6b39b)

### Additional Info

```Running "flutter pub get" in swipeable_stack_bug...
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/pages/home_page/home_page_widget.dart:150:31: Error: The getter 'swipeableStackWordsRecord' isn't defined for the class '_HomePageWidgetState'.
 - '_HomePageWidgetState' is from 'package:swipeable_stack_bug/pages/home_page/home_page_widget.dart' ('lib/pages/home_page/home_page_widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'swipeableStackWordsRecord'.
                        await swipeableStackWordsRecord.reference
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         46.0s
Failed to compile application.
```

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.12
- Platform: Web
- Browser name and version: Chrome 113.0.5672.126 (Official Build) (64-bit)
```

**Comment by SameerShahzad99** [comment]
Thank you so much for reporting this bug, I can reproduce this now!

**Comment by wenkaifan0720** [comment]
Hi @mateuskiper. Thanks a lot for the detailed report. However, I could compile and run it. Would you mind check again?

![iScreen Shoter - Google Chrome - 230525175417](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/808d0710-8070-4f92-b03a-67592874fddc)

**Comment by mateuskiper** [comment]
It's working now, thank you
