### ISSUE TITLE
Error generated because of a persistent color variable

### ISSUE THREAD

**Issue by syg-eliseu** [FlutterFlow/flutterflow-issues#917]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running, when setting the value of a local variable color constant, when I reopen it, the application no longer responds, an error is generated and I get a blank screen.

In the web version of the app I could understand the cause of the problem. The generated error informs to expect to receive an ?int but it receives a "String"

![Captura de Tela 2023-05-19 às 17 05 53](https://github.com/FlutterFlow/flutterflow-issues/assets/88388127/f372856e-7534-4418-a5fb-a467d0f538c8)

I could understand that it is really about the color variables, because when cleaning them from the local storage of the browser, the application works again without problems.

Another resolution is to remove the quotes from the variables in local storage, the application works again.

![Captura de Tela 2023-05-19 às 17 06 47](https://github.com/FlutterFlow/flutterflow-issues/assets/88388127/962558b1-498c-449c-a765-af7c52d52a84)

### Expected Behavior

The application is expected to open correctly and handle persistent color variables without breaking.

### Steps to Reproduce

1. Go to: https://testes.flutterflow.app/

2. Click the "Select Color" button

3. Set a color

4. Reload the page

5. Error generated in the console and blank application.

6. To be able to use the application again, it will be necessary to clear the memory.

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx892pbwA+pf1K/lKqwMxQUB+bZ0vlO1FGQA3B7XmP5k+e/fuaXdCTMTmdGxmIGGKgT8D/snIiYbhNO4qaA+AY4N607pyFg2VZDmiMISmDbjhZ2pQAcpWfn6B57Wg2wpQKttac1lh6l+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

My users were no longer able to access.

My portal is dynamic, so for each client, different colors and logo.

I set the color and image variables during login and keep them as persistent.

How the application started to show problems. I had to turn the color variables to non-persistent which solved my problem.

But I came here to report the bug to be resolved.

I created a blank project to reproduce the issue.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/88388127/032ad65b-03de-452c-b6ed-3e339115bee5

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: MacOS Desktop
- Browser name and version: Mozila 113.0.1
- Operating system and version affected: All
```

**Comment by hariprasadms** [comment]
Hi @syg-eliseu - Thanks for submitting the issue. I can reproduce the bug. When colour var is persisted type, the app state code should look like below.

<img width="702" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/90a380bf-0fc5-42d2-b497-690f0a16742b">

**Comment by victoriahuang1** [comment]
Hi @syg-eliseu , thanks for the report. This issue should be fixed upon the next deploy.
