### ISSUE TITLE
Custom container element does not respect unit of measure if used with Component parameters

### ISSUE THREAD

**Issue by telboyWA** [FlutterFlow/flutterflow-issues#918]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I create a custom container I want to dynamically set the height and width using variables.
The variables are being passed to the container but it only even displays as pixels, even if percentage if selected.

### Expected Behavior

I expect the value to be in line with the visual editor. If I select pixels then the container will display in pixels. If I select percentage it will display a percentage.

### Steps to Reproduce

1. Create a new page
2. Set Column to Expand, and Cross Axis Alignment to 'Stretch'.
3. Add Container
4. Convert Container to Component.
5. Add 'currentHeight' and 'currentWidth' as component parameters.
6. Set width to percentage and set var to 'currentWidth'
7 Set height to percentage and set var to 'currentHeight'
8 Return to main page.
9 Pass in parameter values
10 View incorrect application.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ck8/f34ZJpbxK1aqNd8FFmSQvNkx6RY0sle1xa0wgHZPMC+wIZ/f7XFRuTde0TUFqJlmjjT4d+e/emvPTU+4CBxCBY4hgzrhyUjnieFGVVbnQCbige25/DehXGlSB1ru7gh0nNbBuLUZn216IeezITg3qJZjWDVY3HPiKOZCK2SrDX1iXc2URm05KZDPz

### Context

It's a minor inconvenience as I'm looking to prototype an idea.

### Visual documentation

![Screenshot 6](https://github.com/FlutterFlow/flutterflow-issues/assets/6072774/64502981-1909-4e09-8114-184c9d5e0bde)

![Screenshot 7](https://github.com/FlutterFlow/flutterflow-issues/assets/6072774/64e485a0-f04e-4193-866c-03443d367979)

![Screenshot 8](https://github.com/FlutterFlow/flutterflow-issues/assets/6072774/658700a4-50ee-4130-87b9-d5f94e3202cd)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iOS, Android
- Browser name and version: Arc Version 0.104.0 (38955) : Chromium Engine Version 113.0.5672.126
- Operating system and version affected: MacOS Ventura 13.3.1
```

**Comment by hariprasadms** [comment]
Hi @telboyWA - Thanks for submitting the issue. The issue you are highlighting here is the limitation at this stage. I can mark the issue as feature request. Thanks
