### ISSUE TITLE
Select Page from a very long list of pages

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#92]
Field to select page name --> PageName list is very very long --> it gets very irritating to keep scrolling up and down to locate a page.  --> Pl do two things to solve this problem. 1) Show list in names sorted alphabetically. 2) Add a search box at the top to search text string
![FF select page long list](https://user-images.githubusercontent.com/117246043/199858991-2e7ddfce-bb5b-4822-bb51-e66339efe3d2.png)

**Comment by Pepino-GR** [comment]
Hello palmdeskApp,
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by palmdeskApp** [comment]
Settings --> App details --> Initial Page --> 
Entry page / Logged in page --> 
I have a long list of pages --> Too much scrolling is needed here. 

Pl do following
1) Always sort List_Page_names alphabetically. Its more intutive.
2) add a search field at the top to search "string_match". string matching anywhere in Page name text. Not nesessarily from begining only.

**Comment by Pepino-GR** [comment]
Because this issue is not a bug, I will generate a feature request.
