### ISSUE TITLE
Project in use even after collaborators leave the project

### ISSUE THREAD

**Issue by ilimpapps** [FlutterFlow/flutterflow-issues#922]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 I have projects with 2-3 collaborators. We are not working at the same time !!!, windows in browsers are closed for all collaborators. But FF anyway shows me that somebody actively editing project (Message "project in use" even if they leave project for few hours ago) and kicking me out from project. 

### Expected Behavior

After first collaborator closed the project, FlutterFlow allows for another to work

### Steps to Reproduce

1. Create project with 2 or more collaborators
2. Start to edit by first collaborator
3. First collaborator should close window and exit from the project
4. After some time 5 min+ enter with another collaborator
5. Observe avatars of first collaborator like he still activelly working inside project
6. Message "Project in use"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hcr15Y1gobxG7ZDUavlR/TgWOUs7U7grkO1hRUw8J5zKB+wAYvf7P1FWTLy4YX9qf1mZsGQz1vfqud/DE/Y4KRSrG75ZyJNcVwGWWmWlVKqrCbmBfW1RM8RWf0Ch18GvoRVSNtZac2Qu2zu2f+qWbBXYHrX6PlQ7A/2lKdeK2SrDX1iXc2URm05KZDPz

### Context

It does not allow to collaborate in assynchrone regime.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/da22a4db-f7b3-4310-b4c1-6e7622cd5b03)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/149ac22b-c747-4d72-a64e-105351b76891)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: PC
- Browser name and version: Chrome 113.0.5672.127
- Operating system and version affected: Windows 10
```

**Comment by aemelyanovff** [comment]
@ilimpapps Thanks for reporting the issue.

Unfortunately I'm unable to reproduce it, and it's not for lack of trying. Could you try these two things:

1. Create a new project and try it there.
2. Check if the clocks on both computers show the correct time.

**Comment by ilimpapps** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/426d94cd-2966-480b-b38f-4867fb35f93f

IT4oz/Hqx89godRE7pSJcMdVryQ4Q3l/a+YNispBZywgfZzzBLN/fPfQPlpCUt+id2NpfWCcp1410/z5uM7DCPVfOkiYfIhmyJFqbDrMLXu6RZOTF7ueY3ElEfxQf2q+17S7vSZ5HPhuL2Bk2WeIHeuXRT/fJ5j2OWo8Sq/LZO4=

So here in new project we have similar bug but without kicking me from the project. All FF windows of this user in Chrome on Mac are closed.

**Comment by ilimpapps** [comment]
Time in all computers is set automatically by system

**Comment by ilimpapps** [comment]
More than 12 hours as my collegue not opened this project. He was using Chrome on Mac.

https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/64cd1332-f47d-4aec-b20d-9c5fcecdcfeb

**Comment by aemelyanovff** [comment]
Thanks for the info!

I _think_ we identified the issue; we'll work on fixing it.

**Comment by ilimpapps** [comment]
@aemelyanovff  Great to hear it!)

**Comment by thejadenode** [comment]
+1 same issue, hoping for a quick fix since the project is technically locked for editing.

**Comment by aemelyanovff** [comment]
Closing the issue as inactive (and probably resolved). @ilimpapps please feel free to reopen if you are still experiencing the problem.

**Comment by ilimpapps** [comment]
@aemelyanovff Appologies for delay. We cant check it again cause we already switched to teamplan)

**Comment by sighencea** [comment]
This is not fixed. We're on Web v4.1 Flutter 3.13.7 and are experiencing the same issue still.

**Comment by FakeJoe** [comment]
Same issue here, I just removed a person as a collaborator, and see that it's actively accessing the project which kicks me off to the action choose screen.
