### ISSUE TITLE
Filtering Supabase rows with "boolean is contained by" not properly works

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#923]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1.Set ListView with Supabase Query
2.Add filter:
 Field: boolean field
 Relation: In (Is Contained By)

Then, Value field turns to GRAY which can't be selected.

### Expected Behavior

When selecting relation, Value field correctly appear.

### Steps to Reproduce

1.Set ListView with Supabase Query
2.Add filter:
 Field: some boolean field
 Relation: In (Is Contained By)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Khc/qy5dgrt9G7rqAbcAxnjgXHFgnargsluthZw0cJbL0G7YAQszOSBJaZ+m+Sgo3eGCWrzofwMrQhtzIN/AoCw2CfpRZyZFpWjrdcGahMq6PCc2SWUQlTdpKCmGO55mjqyJ4WbJuck4A7Wa6AuiRfDHYQ5DROkYdH+b8OrDUs3PuQ0SLb3kNh1JWeC/v

### Context

I can't filter Supabase Query with boolean using contains.

### Visual documentation

<img width="299" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/51488947-0502-4660-979b-c2c9186a523b">

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform:Mac
- Browser name and version:Chrome 113.0.5672.126（Official Build） 
- Operating system and version affected: macOS 11.7.4
```

**Comment by victoriahuang1** [comment]
Hi @idea-garage , thanks for the report. We have found a bug on our end, which should be resolved upon the next deploy.

**Comment by idea-garage** [comment]
Thanks, I'll wait for this fix.
Supabase integration is really cool!
