### ISSUE TITLE
Strange button of editing Supabase Query

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#924]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1.Create new page
2.Add Listview
3. Set Supabase Query and confirm
4. Edit Supabase Query, then Strange "Copy" button appear instead of Confirm button

### Expected Behavior

Edit Supabase Query,  Confirm button will appear

### Steps to Reproduce

1.Create new page
2.Add Listview
3. Set Supabase Query and confirm
4. Edit Supabase Query, then Strange "Copy" button appear instead of Confirm button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hc/qy5dgrt9G7rqAbfpR/Sc5JmE7RJE01sFTQks8J5zTP4YIP/v7ak5oO7y9THNIOlmgpzoe7PfquIfpL/ZfIQedR4A41c1qWAmUXXO6V82TBqmZfW1QMNNgJ2a04J7U2RJ4NtZYcmwZ22CYOevKYBTbNb7qIjMvLeW1KdeK2SrDX1iXc2URm05KZDPz

### Context

Annoying to edit Supabase Query

### Visual documentation

<img width="298" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/294efa2c-272d-4bbc-bc10-96ca30114684">

### Environment

```markdown
- FlutterFlow version: V3.1 / V1.1.74 Mac
- Platform:Mac
- Browser name and version:Chrome 113.0.5672.126（Official Build）
- Operating system and version affected: macOS 11.7.4
```

**Comment by hariprasadms** [comment]
Hi @idea-garage - This is the new change as per new updates. While editing once you changes, you can see '**Confirm**' button appears otherwise in edit mode, it displays **copy** button. Check and let me know if you can see Confirm button. Thanks

**Comment by idea-garage** [comment]
Thanks, I understand. It seems a bit odd when I click Confirm button, 'Copy' appear alightly.

**Comment by OldFred2023** [comment]
i am experiencing the same, i have edited the filter so the confirm button should appear, but it doesn't:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/4bc8818f-7225-4a32-9c01-373271006449)

So i would say this is still a bug.

**Comment by idea-garage** [comment]
> i am experiencing the same, i have edited the filter so the confirm button should appear, but it doesn't:
> 
> ![image](https://user-images.githubusercontent.com/122821259/242806823-4bc8818f-7225-4a32-9c01-373271006449.png)
> 
> So i would say this is still a bug.

You can see Confirm button if you change the height of the dialog. Very annoying.

**Comment by victoriahuang1** [comment]
@idea-garage can you provide a screen recording?

**Comment by victoriahuang1** [comment]
@idea-garage can you provide a screen recording?

**Comment by idea-garage** [comment]
Thanks, It looks fine as newest version of FlutterFlow
