### ISSUE TITLE
Project doesn't run in test mode due to Rive error after FF update

### ISSUE THREAD

**Issue by PaniSPejskem** [FlutterFlow/flutterflow-issues#925]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running test mode, project doesn't compile with following error

`Running "flutter pub get" in ... ...
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/home/.pub-cache/hosted/pub.dev/rive-0.10.3/lib/src/rive_core/artboard.dart:211:22: Error: The class 'DependencySorter' is abstract and can't be instantiated.
    var optimistic = DependencySorter<Component>();
                     ^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/rive-0.10.3/lib/src/rive_core/artboard.dart:215:20: Error: The class 'TarjansDependencySorter' is abstract and can't be instantiated.
      var robust = TarjansDependencySorter<Component>();
                   ^^^^^^^^^^^^^^^^^^^^^^^
/home/.pub-cache/hosted/pub.dev/rive-0.10.3/lib/src/rive_core/artboard.dart:460:18: Error: The class 'DependencySorter' is abstract and can't be instantiated.
    var sorter = DependencySorter<Component>();
                 ^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         57.6s
Failed to compile application`

This didn't happen after some change in project as we didn't touch the project 10th and 22nd May. 

We downloaded the code and **changed rive version to 0.11.1** in `pubspec.yaml`, which solved the problem at least on our devices.

### Expected Behavior

Test mode and run mode compiles the code and run

### Steps to Reproduce

1. Add Rive animation widget to project and set it up
2. Run the project in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlvHluJNOmMNY+KqAY8JsjiQsGUMAXOYvitYbVR4cJbLnOu02dsz4ZUNKTMejYAhUOE6jrGQEwcr9iIfhKfIFGyuZRbpa0JVPWgrLXluXVZiMELqgWnJAROhhJkCZ56WRhiN/ANpfcUIh3GWhNq3qNleeY8aSfxBlZ7vfcPo=

### Context

We can't continue the development of the project

### Visual documentation

Blank project error:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/73820773/97895baf-bcec-4b57-b4b4-3ed3a8832f5a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/73820773/55ee885c-eaa3-423d-a26a-91b3554a21ea)

Fix on our devices:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/73820773/e36edf8d-0b2c-4cc9-9445-53ae9f6d40b4)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Edge, Safari
- Operating system and version affected: Windows, Mac
```

**Comment by WellDunDun** [comment]
I'm having the same issue and [others are too](https://community.flutterflow.io/c/bugs/rive-error-while-compiling).

**Comment by PaniSPejskem** [comment]
> Hi @PaniSPejskem - Thanks for submitting the issue. I can re-produce the issue. This error we get only in test mode. Run mode and web deployment works fine.

It's a strange behaviour - in new. blank project I created, it is only bugged in test mode. However. in the existing project, nothing works - test, build, web, android, ios

**Comment by agreaves** [comment]
Hi @PaniSPejskem, thank you for the bug report! This should now be fixed as of yesterday.
