### ISSUE TITLE
Blank space on top of some keyboards

### ISSUE THREAD

**Issue by sgrprabhu** [FlutterFlow/flutterflow-issues#926]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the 19 May update, some keyboards on devices and emulators when open have a large blank space above them. This sometimes even makes the textfield inaccessible on smaller devices as the whole screen gets filled with the keyboard and blank space.

I think these posts could be referring to the same issue:

https://github.com/FlutterFlow/flutterflow-issues/issues/921
https://community.flutterflow.io/c/discuss-and-get-help/erro-ao-selecionar-o-textfield

### Expected Behavior

The keyboard should not be taking up any more space than it needs!

### Steps to Reproduce

The issue seems to be only present in old projects that started before the update. I tried replicating a screen that currently has the issue in the new project but it seems fine then.  However, I did try to check the code update on my older project since the new version and found that this code snippet from main.dart could be causing the issue. 
![Screenshot 2023-05-24 at 12 42 57 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/26254115/40c680f5-98ea-4c41-a866-8081a3277b91)

Replacing those new lines with the older version seems to fix the issue though. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4syeflx4xNodtF0L6JK+5B/SYvJl9+R7gkscpFcxQcB4jZP4kQfPfQP1ZBTf3hTX9MeGKmp14ywPDUjt7lOPYqMgScRtlqyMxcTQuXQn2XaJeTF7iwYHdTLJtjCUjG0renvR1CNrFiSmA71ziTeuSXaC3sQITANWowSq/LZO4=

### Context

Filling text fields. 

### Visual documentation

![Screenshot 2023-05-24 at 12 35 04 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/26254115/57b0b7a8-d8b5-47e2-9713-4e0675cd4511)

An example tree that seems to show the issue:
![Screenshot 2023-05-24 at 1 13 33 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/26254115/54902a08-4cec-41dd-afd5-aea8c8eea475)

### Environment

```markdown
- FlutterFlow version: 3.1 released 23 May
- Platform: 
- Browser name and version:
- Operating system and version affected:
```

**Comment by corsaro0** [comment]
Same here, i have problem in page with nav bar and textfield. I post issue here https://github.com/FlutterFlow/flutterflow-issues/issues/921

**Comment by paulVu** [comment]
![IMG_1105](https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/f94d8a1b-e814-4010-8558-b0c5665730c3)
Same here

**Comment by agreaves** [comment]
Hi @sgrprabhu, thank you very much for this information! This is the same issue as #921, which will be fixed on our next release.
