### ISSUE TITLE
New Custom Widgets not working after update

### ISSUE THREAD

**Issue by blueprin4** [FlutterFlow/flutterflow-issues#928]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I receive the following error when running the project:
Another exception was thrown: Assertion failed: file:///Users/macbookpro/Documents/flutter/packages/flutter/lib/src/widgets/framework.dart:4692:14
Another exception was thrown: Assertion failed: file:///Users/macbookpro/Documents/flutter/packages/flutter/lib/src/widgets/framework.dart:4692:14

### Expected Behavior

Load the syncfusion calendar.

### Steps to Reproduce

Add customer widget with syncfusion calendar with dependencies syncfusion_flutter_calendar: ^21.2.3. Run the project and goto the created page.
Code from custom widget:
```
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom widgets
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!
import 'package:syncfusion_flutter_calendar/calendar.dart';
class SfCalendar extends StatefulWidget {
  const SfCalendar({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);

  final double? width;
  final double? height;

  @override
  _SfCalendarState createState() => _SfCalendarState();
}

class _SfCalendarState extends State<SfCalendar> {
  @override
  Widget build(BuildContext context) {
    return SfCalendar();
  }
}
```

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

will not copy: Failure to copy to clipboard: PlatformException(copy_fail, Clipboard.setData failed, null, null

### Context

I have an app I can not finish that is at the end of changes and is in production.

### Visual documentation

![screenshot](https://github.com/FlutterFlow/flutterflow-issues/assets/10341681/9ff31898-8c82-4235-b48b-7b640a2b46a2)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Macbook
- Browser name and version: Safari
- Operating system and version affected: Monterey 12.6
```

**Comment by hariprasadms** [comment]
Hi @blueprin4 - The details you have shared shows that you are trying use third party package in local environment. We do not support issues which are outside FlutterFlow editor and the code.  However, I can confirm that syncfusion_flutter_calendar package should work fine in FlutterFlow custom widgets. I have tested in my other test projects. Thanks
