### ISSUE TITLE
Adding new Data Type cause compiling ERROR with no information

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#931]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. Create new project as blank
2. Bypass Setup Firebase
3. Create Data Type as "Test", and add Field as "name", type : String
4. Add App State as "test1", type: Data Type Test
5. Create Custom Action and define argument as "testVal", type: Data Type Test
6. Add Boilerplate code and add no change or dummy code.
7. Save and compile, it display "Custom Code Errors" having no information, so I can't finish compilation.

### Expected Behavior

successful compilation

### Steps to Reproduce

1. Create new project as blank
2. Bypass Setup Firebase
3. Create Data Type as "Test", and add Field as "name", type : String
4. Add App State as "test1", type: Data Type Test
5. Create Custom Action and define argument as "testVal", type: Data Type Test
6. Add Boilerplate code and add no change or dummy code.
7. Save and compile, it fails.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPLq25dgrt9c187pbcdooD84Nm44TL07ttYbZxUjIuPtBJh/YOOkTFZCZ73nSmlhHEyJnkUD0taNk+HAUe4oZCyCfqo5+c1MSzz/QXq8RbmaPZeaTkB6QJtXIH6i5p6ZpBJ+NvRtL1IH202qJ/DJfB3ACZ+/Zwh9f6PHaOI=

### Context

Can't use Data Type

### Visual documentation

<img width="334" alt="スクリーンショット 2023-05-25 11 38 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/809b65d0-8996-42c0-8807-e939ae1e1d4b">
<img width="607" alt="スクリーンショット 2023-05-25 11 39 59" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/7552daa8-45a7-42cd-a696-5092e72d2986">
<img width="513" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/2bcd111e-4a05-47da-8020-791b6881e090">

### Additional Info

If I download code and "flutter run", it works fine.

### Environment

```markdown
- FlutterFlow version: V3.1 / V1.1.74 Mac
- Platform:Mac
- Browser name and version:Chrome 113.0.5672.126（Official Build）
- Operating system and version affected: macOS 11.7.4
```

**Comment by hariprasadms** [comment]
Hi @idea-garage - I just tested these steps in my test project. All works fine. Not able to reproduce the issue. However, I have see this error some time before. This error is kind of inconsistent and project specific. I can mark this issue as project specific and will investigate it accordingly. You can delete the function re create it. I hope that can fix the issue in your project. Thanks

**Comment by EmersonFJ** [comment]
> Hi @idea-garage - I just tested these steps in my test project. All works fine. Not able to reproduce the issue. However, I have see this error some time before. This error is kind of inconsistent and project specific. I can mark this issue as project specific and will investigate it accordingly. You can delete the function re create it. I hope that can fix the issue in your project. Thanks

This isn’t project specific- many on the community website are having issues as well.

See here for how to recreate one version of this problem starting from a new project ; note that Firebase is not enabled; a custom data type and a custom action that is unrelated to the custom data type is all you need to create the error; in this video it shows tying the custom data into app state, for many others that have shared this that step isn’t always required; : https://sos-videos.zefranck.com/gK2CqKxWCYZZ2z3G2gMQ

**Comment by idea-garage** [comment]
I notice fixed in recent version, thanks to the team!
