### ISSUE TITLE
Video and Audio Player crash when is in a Bottom Sheet and is open in Test Mode or Android

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#933]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a Video or Audio Player is open using a Bottom Sheet crash the app in Test Mode or Android

### Expected Behavior

Should load normally the Video or Audio Player

### Steps to Reproduce

1. Create a component
2. To this component add the Video or Audio player
3. Go to a page and create a button
4. To this button's action open a Bottom Sheet using the component created previously
5. Now run on Test Mode or Android and you see the problem

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz/Hqx89Nobhe+KrUYOxagmQ4I0MaX7gRidV+GCkbCJyrBIYMaeLRMxJvOPG4S1FpKEWGgk8C/tLujvLiFfQEByuZGqY91rVpEgrMbGq/aovTCauWPXAlGflmIUuM07WrrB0kKfhvLXtk22aqBN6yVhPXH4/7Zwh9f6PHaOI=

### Context

I want reproduce the Audio or Video in a Bottom Sheet

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODI2NzE5OF8yMTUwMzI4OQ

### Additional Info

I can't test on iOS so I don't know if this problem occurs

### Environment

```markdown
- FlutterFlow version: v3.1 released May 23, 2023
- Platform: Web
- Browser name and version: Chrome Version 113.0.5672.127 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by bulgariamitko** [comment]
@Franco98404 there are some limitations in Test/Run modes, but Android one should work. Do you get the same error in Android as well as you showed in your video?

**Comment by Franco98404** [comment]
> @Franco98404 there are some limitations in Test/Run modes, but Android one should work. Do you get the same error in Android as well as you showed in your video?

I got an error but I didn't run the app on debug mode on Android, so only the gray screen appears.

**Comment by aemelyanovff** [comment]
@Franco98404 Thanks for reporting the issue. It will be fixed in the next update.
