### ISSUE TITLE
Build fails when filtering by Data Type as an App State

### ISSUE THREAD

**Issue by brucevz** [FlutterFlow/flutterflow-issues#934]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is how the query is built.
![CleanShot 2023-05-25 at 13 21 01](https://github.com/FlutterFlow/flutterflow-issues/assets/14323343/445a98ea-e096-4a45-ba61-7a6b1c77088f)

here is our data structure. 
![CleanShot 2023-05-25 at 13 21 58](https://github.com/FlutterFlow/flutterflow-issues/assets/14323343/394f7ef6-7744-4233-a133-27d341a61bf0)

This is the error screen
![CleanShot 2023-05-25 at 13 19 56](https://github.com/FlutterFlow/flutterflow-issues/assets/14323343/d85f203c-8ad4-4548-9a54-d7ffb4c38b5e)

### Expected Behavior

We should be able to filter a list of documents based on an app state that is a data type 

### Steps to Reproduce

1. create new page
2. create a list
3. built a query to get list of documents
4. add a filter to filter if an app state that's a data type
5. try and build

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq0It1xMtH+Kr+bsBB/ToQNV82a7skscp8WQgafIjJP4kQPPWkM0hCZ8DhYXxif0SmmmMezN7Pi/PxO/knAyuBfqJhzLpQaAzvQkyga5OBCLWwR3QlEtxWClCAyqSw2RNQNftidGxg1EOHe++UTivDHrLKImdISq/LZO4=

### Context

We can't build our project when this filter is enabled. We aren't able to build our community dashboard right now until this is fixed

### Visual documentation

Added images above

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: 
- Browser name and version: Chrome
- Operating system and version affected: Mac os X
```

**Comment by organicnz** [comment]
Hi, @brucevz. Thanks for adding this issue, mate 🙂

Hmm, I'm afraid you can't filter within an array. Have you by any chance tried filtering in a document? 🙂

**Comment by agreaves** [comment]
Hi @brucevz, thanks for the bug report! As per your chat with support, I've been able to confirm the bug and indeed it will be fixed upon the next release! Unfortunately there isn't a workaround until then.
