### ISSUE TITLE
TextField Capitalization Not Working On Web+Desktop

### ISSUE THREAD

**Issue by andrewjhop** [FlutterFlow/flutterflow-issues#935]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

TextField Capitalization works in my web-app when accessed via a browser on a mobile device, but does not work in the same browser, the same app, on a desktop computer.

### Expected Behavior

TextFields should be capitalized as they are on mobile devices.

### Steps to Reproduce

Try any capitalized TextField on a desktop.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ci8/qx4l2mOZE0LXuKcExhSQRQ1wmRY030MJHQkw0N5PNCJkQO8nTXFJWXf25dkFAfU38hjkJp/CJm9z1LfoDPTqeGaV8wZBIcAzieGGhbLqxO6u/Pn9uGshVCEyByJ6nhSRdD7duWF4k116mAd6yZHTYQZD7PXo7A/2bNpvXmAfuQ0SLb3kNh1JWeC/v

### Context

It's frustrating for desktop users.

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Mac OS 12.1
- Browser name and version: Safari or Chrome
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment]
@andrewjhop , what do you mean by Capitalization, how do you do that? Using custom code? using FF UI? is the text already Capitalize?

**Comment by andrewjhop** [comment]
@bulgariamitko In FF > TextField > Capitalization (at the bottom) 

Can be None, Words, Sentences, Characters.

**Comment by wenkaifan0720** [comment]
Hi @andrewjhop. Unfortunately this setting only works on mobile (and not even on third party keyboard apps that do not respect these settings). On desktop I don't think you can programmatically turn on/off the caps lock key (especially via the browser). So the Flutter team just didn't implement this feature on desktop.

**Comment by bulgariamitko** [comment]
@wenkaifan0720 you can't turn it on, but you can convert each letter to capital one isn't it?

**Comment by wenkaifan0720** [comment]
Sure you can, but that is not something that comes directly with the `TextField` widget.

**Comment by Krystian95** [comment]
Hi 🙂 Is there any update related to a fix for the Web? It still not work.

**Comment by diegomm796** [comment]
not working ... something really basic
