### ISSUE TITLE
Request to Supabase all appear to be anon

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#937]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All access to Supabase tables through query, and access to Supabase functions via API appear to always be anon access even when the user in FF is authenticated.  The is causing issues with RLS in Supabase.

### Expected Behavior

The authenticated user should show in the "auth" user when authentication against Supabase.

### Steps to Reproduce

Create new project with Supabase as the authentication method.
create table in SB with column of user_id uuid and have RLS enabled, and policy set to ((auth.jwt() ->> 'sub'::text) = user_id)
add query to list widget, to a table
Run app
login to app so user is authenticated by SB
go to page with list

The list is empty as RLS has failed because the auth.jwt is for "anon" and not the authenticated user.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocBH7pDMbMFAhQAkH1x/bZJEl9cbSks0B5TpEYkTP+r+V1ptYNOXeFZLeVL9njoJpOyMk/zXMPBfaEiBQoNowZZuFAGXLHOmMoyyPM+SZUd6I+1UGFCiyKaokx17Pvt0WC0Mw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Causes SB projects to fail if RLS is enabled (which is am important feature for EU users) 

### Visual documentation

n/a.

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by EmersonFJ** [comment]
I agree and see the same thing; ideally we could access the authenticated user access token to solve this with custom APIs in addition to having it work with the native FF query functions

**Comment by ziv-caspi** [comment]
I am experiencing the same problem, could not find a way to reach the auth token after using the Supabase Login action.

**Comment by spatialy** [comment]
Must need to be able to deliver more secure apps

@agreaves, can you look into this please

**Comment by EmersonFJ** [comment]
Ok - I think I figured this out. You can access the JWT through a custom action. you need to exclude the custom action from compilation - then it is simply as follows, I think - still experimenting, but seems simple.

You then call this action whenever you want to use the access token, and then store that as an action output.

// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import '[YOUR PACKAGE NAME]/auth/supabase_auth/auth_util.dart';

Future<String> returnJWT() async {
  // Add your function code here!
  return currentJwtToken;
}

**Comment by ziv-caspi** [comment]
> Ok - I think I figured this out. You can access the JWT through a custom action. you need to exclude the custom action from compilation - then it is simply as follows, I think - still experimenting, but seems simple.
> 
> 
> 
> You then call this action whenever you want to use the access token, and then store that as an action output.
> 
> 
> 
> // Begin custom action code
> 
> // DO NOT REMOVE OR MODIFY THE CODE ABOVE!
> 
> 
> 
> import '[YOUR PACKAGE NAME]/auth/supabase_auth/auth_util.dart';
> 
> 
> 
> Future<String> returnJWT() async {
> 
>   // Add your function code here!
> 
>   return currentJwtToken;
> 
> }

What's supposed to be the code that fetches 'currentJwtToken'?

**Comment by EmersonFJ** [comment]
> return currentJwtToken;

It is literally this line - it’s a defined part of the auth_util.dart

line : return currentJwtToken;

**Comment by EmersonFJ** [comment]
I guess the issue with this is that it is a custom action, so you can't used it as a function or variable outside of action chains, which doesn't solve many important use cases; I cannot get it to work as a custom function, which would enable all these other use cases.

**Comment by OldFred2023** [comment]
Custom code and actions doesn't really solve the issue at all, FF is not sending the authenticated user to Supabase either on API calls or for Queries.

**Comment by EmersonFJ** [comment]
> Custom code and actions doesn't really solve the issue at all, FF is not sending the authenticated user to Supabase either on API calls or for Queries, making RLS unusable and placing a big question on data security, which is one of the biggest points of Supabase, without it the whole Supabase integration seems a bit pointless.

This solves a very related problem, but I guess not the exact same; a powerful part of supabase is custom APIs, but without being able to access the access token directly and feed it as part of the custom API call, you can’t use supabase custom APIs. So I guess I was treating these as the same issue - the JWT isn’t being sent in their integrated calls, nor can you access the JWT directly. We need to be able to do both, and based on my testing, FF is storing and refreshing the access token………thus, I think all @agreaves and team need to do is give us access to it on the Authenticated user options like they do userID and email etc, and then include that JWT as part of the natively integrated FF Supabase calls, or at least as an option…. Meaning this isn’t building something new on their end I hope!

**Comment by beckzg** [comment]
@[agreaves](https://github.com/agreaves) we need the token for API integration!!

**Comment by OldFred2023** [comment]
Reported 5 days ago, and still not Triaged..... Its no good hoping the problem will vanish on its own, when will it be looked at?

**Comment by victoriahuang1** [comment]
Hi @OldFred2023 , thanks for the report. I could not reproduce the issue. Could you inspect the network call that you are making with Supabase queries?

<img width="1103" alt="Screenshot 2023-06-07 at 10 28 58 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/f082ce48-1cf9-4eb0-80c5-6408c1e1d482">

If you take the JWT token used in the API call, you can pass it into https://jwt.io/ to verify if it looks correct. Let me know if there is incorrect info in the JWT token.

And can you let me know if there is any difference between the JWT token passed into the calls for: table queries, functions, storage, ...

**Comment by victoriahuang1** [comment]
I will add the JWT token as a feature request. It should get prioritized and worked on soon!

**Comment by victoriahuang1** [comment]
The JWT token field will be available soon (next deploy)!

**Comment by EmersonFJ** [comment]
> The JWT token field will be available soon (next deploy)!

Thank you so much- this will save me a huge headache with a function listening to things in the background - appreciate all your help on these Supabase topics! You did the refreshed token navigation issues as well (I haven’t checked if that was pushed yet!)

**Comment by emilioescamilla** [comment]
hello guys,
I found this same behavior when connected with a Supabase instance installed with Docker.
Any thoughts?
