### ISSUE TITLE
Calendar swiping issue

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#938]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Calendar widget has a weird behaviour when set to week view. 
Sometimes when you scroll to a different week from the current week and select a new date, the calendar view resets to the week before. This only happens sometimes though. The video below explains it visually:
https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/e0eb68b0-2c3e-4bd5-9a4e-8bac3dc88504

### Expected Behavior

The Calendar view should remain the same and the week shouldn't change.

### Steps to Reproduce

1. Create a new page
2. Add a Calendar widget
3. Set the calendar widget to week view
4. Change currently shown week by swiping on the calendar widget (not pressing on the arrows)
5. Change selected date
6. Try a few times if the bug doesn't show instantly

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fkMmAuI92mOZE7YSJb+9V/CQWMjsnRYJJlu56EBQ1F5fqE5oQfcnRYk5JYsOWd2x2JWGjmmMz+KGNhd7mGu4oJgWtU4Ne/6VyTg/MWmqWRq6tEZaedXFBP+ZUfHKz5LSGmA9SNbJvZXAb7DqPfeeucCrsQePQPEQZAeWJA9j+jl6ZLg/3FBZFzmNecCfn

### Context

Have a functional calendar.

### Visual documentation

Video shown in description.

### Environment

```markdown
- FlutterFlow version: v3.1 (released May 23, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 113.0.5672.126
- Operating system and version affected: macOS Ventura 13.1
```

**Comment by kevintonb** [comment]
Hey @tinrunje , thank you for reporting this bug! I have been able to reproduce this 👍🏼

**Comment by agreaves** [comment]
Hi @tinrunje, as Kevin said thank you for this bug report! Indeed this was behaving quite strangely. We've identified the issue, and it should be fixed upon our next release 🙂
