### ISSUE TITLE
Checkbox not able to stay checked - data from firebase - inside listview

### ISSUE THREAD

**Issue by RECPOS** [FlutterFlow/flutterflow-issues#940]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As soon as I click on a checkbox it becomes uncheck

Notice: that the checkbox has a action, 
on toggeled on => add to list the document for that row, No rebuild
on toggeled off => remove from list the document, which is the one added before, No rebuild

### Expected Behavior

I should be able to check the widget and it should stay checked until i uncheck it again.
The aciton does its job and the item is stored in locallist even though the checkbox is automatically unchecked.

### Steps to Reproduce

- Add Checkbox under a Listview, which is has dynamically chilren or even if you have the backend query on the listview this still happends.
- Create a List<document> in Local page state variables and give et any name 
- Now on the checkbox go to Action
- Set On toggled On to update widget state -> add to list the local page state variable created earlier, with the row document in the list. Remember to set the update type to "no rebuild"
- Set On toggled Off to update widget state -> remove from list the local page state variable created earlier, with the row document in the list. Remember to set the update type to "no rebuild"
- Now Click on any of the specific checkboxes and they automatically are uncheck after a second

Bug Report Code (required, generate from Widget Tree)
IT4shfLl8ZNPj7xd1s7yc/lR/CcWH0wgaoE8scp8bxcjGJTsB7N/O/WkPhZuOP3jdG9MPESmmmIEpPTskez1J/o4CEmcRa06wsxcUgLJfD2me5OBC5eWVHZTL9xhIB214LbQpAhDObZqR1om7FOpOOqQbDHvJID0ImdISq/LZO4=

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfLl8ZNPj7xd1s7yc/lR/CcWH0wgaoE8scp8bxcjGJTsB7N/O/WkPhZuOP3jdG9MPESmmmIEpPTskez1J/o4CEmcRa06wsxcUgLJfD2me5OBC5eWVHZTL9xhIB214LbQpAhDObZqR1om7FOpOOqQbDHvJID0ImdISq/LZO4=

### Context

I would like to check the checkboxes and keep them checked and make sure it adds the rows in the locallist

all was working in the previous version. It looks like the new update of flutterflow in no rebuild does not get set.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/79512137/c5be0b0d-b87c-4aa9-9f87-ddb69f57a13d

### Environment

```markdown
- FlutterFlow version: 3.1 - flutter 3.7.12
- Platform: Android both physical phone and emulator and Web
- Browser name and version: Tested on Edge v113.0.1774.50 (Officielt build) (64-bit) and Chrome v. 113.0.5672.127 (Official Build) (64-bit)
- Operating system and version affected: Using MS windows 11
```

**Comment by hariprasadms** [comment]
Hi @RECPOS - Thanks for submitting the issue. I have tested the checkbox and its behaviour when fire-store data is linked. It is working as expected.

I looked at your project. It looks like you are not handling the checkbox status properly. Checkbox status data type is boolean. So you should modify the action accordingly.

**Comment by RECPOS** [comment]
Hi 

I am not quite sure what you mean :)?

The listview has child, a Row where there are mulitple children:
Checkbox, Textfield, Divider, Textfield, Divider and Textfield. 

The checkbox initial value is set to the document field which is named Selected. This is by default set to be false and a type is boolean from insurance_coverage schema.
Then I created an action which on toggled on adds the document to a page state list, and on toggeled off it removes the same document from the page state list.

Now just to strip it down to what should be done or not:
I just removed the action on the checkbox toggeled. I also set the backend query to be on the listview so it now queries directly and not getting data from a variable (the container).  and the checkbox is still being unchecked, but by what ? since it is not bound to any fields/documents it should not refresh/rebuild ? or am i missing a page of the documentation :) ?


new Widget Bug code:
IT4shfLl8ZNPj7xd1s7yc/lR/CcWH0wgaoE8scp8bxcjGJTsB7N/O/WkPhZuOP3jdG9MPESmmnwBptLnv+OeMfoCZU6CRpRZyc5ISzvNXmOWUZOBC5eWVHZTL9xhIB214LbQpAhDObZqR1om7FOpOOqQbDHvJID0ImdISq/LZO4=

**Comment by younicornsJH** [comment]
Maybe linked to https://github.com/FlutterFlow/flutterflow-issues/issues/944?

**Comment by RECPOS** [comment]
Yes and i will be following the #944  case, and just posted in there with a blank project. Lets just say that I had nothing better to do at all :D

**Comment by hariprasadms** [comment]
Hi, This is duplicate with #944 . Hence closing the issue. Thanks
