### ISSUE TITLE
Multiple Pie Charts Color adjustment

### ISSUE THREAD

**Issue by fettespferd** [FlutterFlow/flutterflow-issues#942]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently I have two pie chart defined on one page. After changing the colors of there I can an error while building the project.
The error is that I have declared the variable 'final pieChartColors' twice.

### Expected Behavior

Expected behavior is to be able to define the colors of each pie chart independently and names shouldn't interfere here. 

### Steps to Reproduce

1. Create a page
2. Create two pie charts with Firestore Documents as data (at least in my case)
3. Change the colors of the pie chart
4. Run in test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESzfHl8YlgosAB0KrudPlQhR8kQ2InarsvhOtDYxQcC7nkOqQTbuvTN2RBcNDmdFA/P2H+oGMD08rHufPLF/EVBAqEQ5tz1ahMFBaURnKmRJ/WC6mCekFAGfJNG2ah1rSZ2CMnD7dfLFUtig/GSw==

### Context

Trying to adjust the colors to my scheme

### Visual documentation

No picture needed.

### Additional Info

In the current setup I reverted my color changes so that I can keep working on my project.

### Environment

```markdown
- FlutterFlow version: 3.7.12 
- Platform: Web
- Browser name and version: Chrome 113.0.5672.126 
- Operating system and version affected:  macOS Ventura 13.2.1
```

**Comment by SameerShahzad99** [comment]
I was able to reproduce this on a local project, Thanks for submission!

**Comment by aemelyanovff** [comment]
@fettespferd Thanks for reporting the issue. It will be fixed in the next update.
