### ISSUE TITLE
Backend Query Infinite Scroll Bug

### ISSUE THREAD

**Issue by EflexoftRD** [FlutterFlow/flutterflow-issues#947]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when Infinite Scroll in Backend query is enabled in a listview widget, it sometimes has an infinite loading animation & in my specific case might duplicate the record shown (database record is not affected)

(you can see from the attached image that the last 2 records are actually identical (they are infact, identical, the database only has 2 records but here its showing 3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87630857/031d9e75-38dd-4732-a3a2-0b3958fbe5f6)

### Expected Behavior

there should be no visual bug or infinity loading animation after fetching data from the database

(the attached image should be the expected results but it was achieved by disabling infinity scroll)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87630857/07aaae5b-dc6e-49b3-844a-088b9e89d76c)

### Steps to Reproduce

1. make a backend query with infinity scroll enabled (page size = 24), query a firebase collection while filtering out many documents by some metric until only 2 remain.
2. you should see that the loading animation continuously spins

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESk8r6w4tgrttC16rccsJQhQIhNmY1bZMnktVxRR4bfIjoELAcYPTCZUNKT+2Yd1dMAVGWnjoKzNrKiuHhG8EoKTGeGoRZ0JVAFBbibFOjVIyoOruaZHBAP9FVJ2q75qW7rwpdBMhic3w66k6HNq3qNleeY8aSfxBlZ7vfcPo=

### Context

in all seriousness it isnt affecting performance so much as its a visual bug. on the end user's side they will see a continuously loading animation and might think that the app is stuck or something when all other page functions still work.

### Visual documentation

before i launched the debug mode
i showed that infinite scrolling is turned on
then i launched debug mode and navigated to the problem page
as shown, there's an infinite loading circle with 3 records shown

i then went back
disabled infinite loading, and reloaded the debug mode, navigated to the same problem page
and now you dont see the infinite loading circle any more

i then switched to a different account (with infinite loading turned off)
to show that there isnt any issues

i then turned on infinite loading
reloaded the debug mode
navigated to the problem page
and while there were a few loading circles, they eventually went away and scrolling down there werent have any issues

https://github.com/FlutterFlow/flutterflow-issues/assets/87630857/fbf31520-d15e-4b07-a7b1-54304a28f565

### Additional Info

one of the query filter conditions is using a document reference that is used to distinguish which company the document belongs to.
the bug only seems to show up in the company where there are only 2 documents using this reference.
i've tried comparing the database data & changing the document fields but nothing seems out of the ordinary and changing the document field doenst seem to affect it at all.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87630857/64e368d2-0373-4000-815a-632806b8c4cc)

### Environment

```markdown
- FlutterFlow version: v3.1 (Flutter 3.7.12
- Platform: web
- Browser name and version: google chrome Version 113.0.5672.127
- Operating system and version affected: desktop Windows 10 Home Single Language
```

**Comment by hariprasadms** [comment]
Hi @EflexoftRD - Thanks for submitting the issue. The infinite loading keeps appearing usually when indexes is not created properly at Firestore. Can you double check for all the filters and order-by you have user in the query, indexes are created properly in Firestore ?. If not, create them manually. Refer here - https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/retrieving-data/adding-indexes

Duplicate record should not appear. That looks a bit wired. Double check you do not have duplicate records in Firestore. 

Confirm these points please.

**Comment by AKRehmanKhan** [comment]
I also noticed a bug that when there is single element in my database then infinite scroll keep on loading, doesn't show that element. As long as I add one more element then that bug disapears.I am using api call as backend query. I have tested that api in editor it returns single ement but list view doesn't show it.
