### ISSUE TITLE
remove document from list of documents page state not working

### ISSUE THREAD

**Issue by gasserwshalaby** [FlutterFlow/flutterflow-issues#948]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when having a page state of type List of documents, any action to remove a document (from that list of documents) out of the page state does not work. (the code does not execute)

### Expected Behavior

To have a document removed from the list of documents stored in a page state.

### Steps to Reproduce

1. create a new app with firebase as a backend
2. create a page with a list of documents of any collection other than users collection
3. build a page that queries the collection and have a page state of list of documents of the collection
4. add a button that adds a document to the page state list of documents with a follow up alert  dialogue that gives the number of documents in the page state
5. add another button that removes the document from the page state with a follow up alert dialouge that shows the number of documents in the page state.
6. after adding the document to the page state, the page state count will be 1
7. after clicking on the button with the action to remove the document from the page state, the page state count will still be 1
8. the bug doesn't show up as an error in the console or anywherein the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjfLqw5dOodtD1rr9bcJaiiUQOVs2TL07ttYbZxUjIuPtBJh/dsn7YlVBXdDgY0NhHGabnkEz0ujyjuDLLvEBExaubqE/1bhpWwzwLHq8SpvWBs+Of2skHd5XIXaa3KSFuhMkPfhZSiwj7DqLNejLbB3cGZu/Zwh9f6PHaOI=

### Context

i am using the page state to run an action logic flow, the flow will continue to work without having the item removed from the list, therefore breaking the logic flow

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/107878826/f1680862-c5e0-4b0e-93e7-cab7e35ef29c

### Additional Info

please try to attend to this matter urgently as this is affecting all my apps and practically preventing me from further developing any of my apps

### Environment

```markdown
- FlutterFlow version: 1.1.74
- Platform: MacOs app
- Browser name and version: FF Mac App v 1.1.74
- Operating system and version affected:  MacOs Ventura 13.3.1(a)
```

**Comment by hariprasadms** [comment]
Hi @gasserwshalaby - Thanks for submitting the issue. Sorry for late responding. To remove item from the list use 'Remove list at index' option instead 'Remove from list'. 

<img width="453" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/36ade7a4-b1e6-490d-a652-14fc0afe5a37">

**Comment by gasserwshalaby** [comment]
> Hi @gasserwshalaby - Thanks for submitting the issue. Sorry for late responding. To remove item from the list use 'Remove list at index' option instead 'Remove from list'.
> 
> <img alt="image" width="453" src="https://user-images.githubusercontent.com/17435678/242952821-36ade7a4-b1e6-490d-a652-14fc0afe5a37.png">

unfortunatly thats not an option as i will never have a way of knowing which index the added item is at, on the time of adding, as users make arbitrary choices add the item to a list. the only way forit to work, is to fix the 'remove item from list' bug. i am hoping this would be fixed ASAP as it is causing me so much embarrassment with my clients. thank you for your understanding.

**Comment by hariprasadms** [comment]
Hi @gasserwshalaby - I see what your are saying. I can see the issue and appears the same in downloaded code as well. I have marked this as bug now . Development team should be looking at it shortly. Thanks

**Comment by aemelyanovff** [comment]
@gasserwshalaby Thanks for reporting the issue. It will be fixed in the next update.
