### ISSUE TITLE
Custom function testing doesn’t support Color data type

### ISSUE THREAD

**Issue by davidflutterflow** [FlutterFlow/flutterflow-issues#95]
**Custom function testing doesn’t support Color data type - it only supports vanilla Dart, while Color is a part of Flutter.**

A custom function test shouldn't rely on whether there is a color type in the database classes or not.
when we have a color type, even if we don't use them in a function, the whole custom function will fail.

1. create a new project, and create any collection with a field type color.
2. create any custom function that do anything and try to test it

It could cause in the whole project we couldn't be able to test our functions and this is very annoying. 

--
lib/main.dart....
Error: Type'Color' not found
Color? containerColor
--

![image](https://user-images.githubusercontent.com/103986553/200015330-29a99c81-d011-4226-ba11-dff9873eafae.png)

**Comment by agreaves** [comment]
Thanks for submitting this bug report! Sorry for the troubles, this has been fixed and will be deployed in our next release 🙂
