### ISSUE TITLE
Can't edit text with translation

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#951]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've recorded two video

https://drive.google.com/file/d/1ilxPbs3O_Lg3Xago5-9NpGH0Jxe2XT2P/view?usp=sharing
https://drive.google.com/file/d/1R1kMpTnIJPHTKiwnU6VZEXPRG2QHJbNw/view?usp=sharing

### Expected Behavior

I can edit the text

### Steps to Reproduce

I don't know, it seems like bug in several project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl+flwItOobRF7qXTbe5r/SMXG1B5bZJJsct/cxQcB4j4Pe0AdcjRbhFCOMizaH5iGVH/hjoH+vCNiYfxCMY3EwyVG9lxz7hcSxPPYzmteL3WEauVPUB8L8RVJlye04mJghEkLvF2LUYQ20+uBdisdz6Cf9qOYwx5e6fDbOY=

### Context

Try to clear cache

### Visual documentation

https://drive.google.com/file/d/1ilxPbs3O_Lg3Xago5-9NpGH0Jxe2XT2P/view?usp=sharing
https://drive.google.com/file/d/1R1kMpTnIJPHTKiwnU6VZEXPRG2QHJbNw/view?usp=sharing

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: web/ios
- Browser name and version: safari
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment]
Hi @oper2k - Thanks for reporting the isssue. Sorry for the delayed response. I believe you have a solution already. 
 I have verified the issue In test projects and I can confirm that everything is working as expected. 

Looks like there could be missing configurations around language settings. Please get in touch with the technical support team using the chat box in the FlutterFlow editor. 

Below is the video showing language feature working. 

Uploading language_settings.mp4…
