### ISSUE TITLE
CheckboxListTile in ListView not maintaining state (guess: it rebuilds page on click)

### ISSUE THREAD

**Issue by Globaldiary2023** [FlutterFlow/flutterflow-issues#952]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm experiencing a bug in my FlutterFlow project. I have a dynamic list of checkbox tiles that used to work perfectly, but now they're suddenly not clickable. It's quite frustrating because this functionality was crucial to the user interaction in my app. I've spent hours trying to figure out what went wrong, but I'm still unable to pinpoint the exact cause of the issue.

Initially, everything was functioning as expected. Each checkbox tile in the list was responsive, allowing users to toggle their selection. However, without any apparent changes to the code or configuration, the checkboxes suddenly became unresponsive. It's baffling to see something that was once working flawlessly suddenly stop functioning altogether.

I've checked my code thoroughly, trying to identify any potential mistakes or overlooked changes, but everything seems to be in order. I've also tested other interactive elements in the app, and they work perfectly fine. It seems to be isolated specifically to the checkbox tiles within the dynamic list.

To troubleshoot the issue, I attempted to simplify the code by removing any unnecessary components and minimizing the logic involved. However, even with this simplified version, the checkboxes remain unclickable. I even tried replicating the functionality in a separate FlutterFlow project, but encountered _almost_ the same issue there as well (see below).

At this point, I'm running out of ideas and resources to resolve this bug. I've searched online forums and documentation for similar cases, but I haven't found any solutions that apply directly to my situation. It's frustrating because this bug is hindering the progress of my project and causing delays in development.

I'm hoping that someone with more experience or knowledge in FlutterFlow can shed some light on this issue. It's essential to restore the clickability of the checkbox tiles as soon as possible to ensure a smooth and interactive user experience in my app.

### Expected Behavior

I expected the checkbox tiles in my FlutterFlow project's dynamic list to be clickable, allowing users to toggle their selection. Previously, the checkboxes worked flawlessly, and users could easily interact with them by tapping on each tile to toggle its checked state. I anticipated that this functionality would continue to work as intended, providing a seamless and interactive user experience in my app.

### Steps to Reproduce

1. To reproduce the issue with the unclickable checkbox tiles in a FlutterFlow project, please follow these steps:

1. Create a new FlutterFlow project.
2. Create a new page within the project.
3. Add a Column widget as the main container for the page.
4. Inside the Column, add a ListView widget.
5. Within the ListView, add a Container widget for each item in the list.
6. Inside each Container, add a Row widget.
7. Within the Row, add a CheckboxListTile widget.
8. Set the Title Text property of the CheckboxListTile to a randomly generated item from a variable (e.g., a list of random names).
9. Click on the ListView widget to select it.
10. Generate children for the ListView from a variable, ensuring it uses the list of random names.
11. Click on the "Run your app in test mode" (lightning bolt) button to launch the app in the test mode.
12. Observe how when you click on a checkbox, the page rebuilds, generating new names for the CheckboxListTile items.

By following these steps, you should be able to reproduce the issue where clicking on the checkbox in the FlutterFlow project rebuilds the page, generating new names for the CheckboxListTile items.

This is the reason it does not 'keep it's state'.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT88lcr135VNxPVA187pbcJV+CQXNmY1bZZM0O5+d0s1GJCvBKd3ZPfBN1RAXeGiTH9EJEycgVEBpvDThYbTC8FcOTCuc6I7zbpUUQLxLWa5VpebEZewYUZ/Gv5VIEPH06uvnSZNCOlpdXAg32CyBfC/Ew/rJ4/zJ0VBAOX/KoP/j2DhGwzNDxdZ5CQDR1OLC8gyRD3Uu5jJ+9Qzj4Km/ol8qBVXzoPSwtX1TBKTWVk=

### Context

This issue has significantly affected me and my project development. As a developer, I rely on the functionality of the checkbox tiles within the dynamic list to provide an interactive user experience in my app. The fact that the checkbox tiles have become unclickable hinders the core functionality of my application and disrupts the intended user flow.

The purpose of my project is to create a seamless and efficient user interface where users can select items from a list using checkboxes. By not being able to click on the checkboxes, users are unable to interact with the app as intended, leading to frustration and a poor user experience. This issue directly impacts the usability and functionality of my app, hindering its overall effectiveness.

Moreover, this problem has caused delays in my development process. I've spent a considerable amount of time trying to debug and troubleshoot the issue, but so far, I haven't been successful in finding a resolution. This setback has prevented me from progressing with other aspects of my project and meeting the desired timeline.

My ultimate goal is to resolve this issue promptly and restore the clickability of the checkbox tiles. By doing so, I aim to provide a smooth and engaging user experience, ensuring that users can easily select items from the dynamic list and continue using the app without any interruptions. I'm actively seeking a solution to this problem to deliver a high-quality product to my users and meet their expectations.

### Visual documentation

[Screen sharing - 2023-06-01 2_51_27 PM.mp4.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11625386/Screen.sharing.-.2023-06-01.2_51_27.PM.mp4.zip)

### Additional Info

You can clone the demo project [here](https://app.flutterflow.io/project/checklist-in-list-view-bug-demo-gil2f9)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: MacOS
- Browser name and version: Chrome Version 113.0.5672.126 (Official Build) (arm64)
- Operating system and version affected: MacOS Ventura 13.3.1 (a) (22E772610a)
```

**Comment by Globaldiary2023** [comment]
Original:
Workaround is to set the initial state of the checkbox's. (using an app state that get's set to the ID of the item at the index you're clicking...an action on the checkbox itself)

It's happening because the page is rebuilding whenever the checkbox is clicked.

ChatGPT version:
To address this issue, you can resolve it by configuring the initial state of the checkbox. This can be achieved by using an application state that is set to the ID of the item at the index where the click event occurs. The checkbox itself triggers an action, resulting in the appropriate initial state configuration. The reason behind this occurrence is the page being rebuilt every time the checkbox is clicked.

**Comment by hariprasadms** [comment]
Hi, This is duplicate with #944. I see your follow the same issue as well. Hence I am closing the issue. 
I have provided the solution in 944. Please follow the same. Thanks

**Comment by Globaldiary2023** [comment]
It it not a duplicate. Review this one by itself.

**Comment by Globaldiary2023** [comment]
@shelpert please help. @hariprasadms is missing something important.

**Comment by YukChenLee** [comment]
#944 is a resolve for Firebase Database, but not if you are using a private API without an extra boolean index for the checkbox.
