### ISSUE TITLE
dash_chat 1.1.16 which depends on intl ^0.17.0, intl ^0.17.0 is required

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#954]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I upgraded flutter then now needs intl 0.18.1 but the dash_chat from flutter flow needs intl 0.17.0, I can't test of deploy anymore.

### Expected Behavior

have the new dash_chat v2 instead of the old one from flutterflow

### Steps to Reproduce

Title: Version conflict with `intl` after Flutter upgrade

Product: Flutter / Flutter Flow / Dash_Chat

Environment: 
Flutter version: (include flutter version you upgraded to)
Operating System: (specify your OS, version)

Description:
After upgrading Flutter, I have encountered an issue where there is a version conflict between the `intl` dependency required by Flutter and `dash_chat` from Flutter Flow. Specifically, the new Flutter version requires `intl` version 0.18.1, while `dash_chat` requires version 0.17.0. This conflict prevents me from testing or deploying my application.

Steps to reproduce:
1. Upgrade Flutter to the latest version.
2. Check the version of `intl` that is now required by Flutter.
3. Compare this with the `intl` version required by `dash_chat` in Flutter Flow.

Expected Result:
After Flutter upgrade, it should be compatible with the `intl` version that is required by `dash_chat` in Flutter Flow. 

Actual Result:
There is a version conflict between `intl` required by Flutter (0.18.1) and `dash_chat` (0.17.0), blocking testing and deployment processes.

I would be very grateful for any suggestions on how to resolve this issue or workarounds that might allow me to continue testing and deployment.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olfLluJZ1ofVY7c/QdcBv9CQWJVg2RLgZkspBZzwYCJyuC5kAYffAP1JoTdzgTGx2I1m2p140wfD7huDPLPA6OTGdfLpa+LpIcwGWTkeiVZOTF7rtXndABelWf3615MOvsxR5OsZeWl4k1znzCOu9YHfUK737DWowSq/LZO4=

### Context

I'm about de deploy the official version but with this bug I have close my startup

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/1798a7e1-251b-4cc9-95ee-32a3d6d8003b)

### Environment

```markdown
- FlutterFlow version:  v3.1 (released Feb 27, 2023)
- Platform:mobile
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by bulgariamitko** [comment]
@ibm777p2 to fix this issue try to use any instead of writing a version of the package 

dash_chat: any

**Comment by aemelyanovff** [comment]
@ibm777p2 I suggest you downgrade Flutter to 3.7.12 until FlutterFlow upgrades to 3.10.

FlutterFlow will always be a little behind on Flutter versions, and if you upgrade Flutter before FF, we can't guarantee that code generated by FF will build.

For context, we try to upgrade Flutter reasonably fast, but Flutter upgrades usually trigger chain reactions of upgrades to other packages, and that's a lot of work for us.
