### ISSUE TITLE
Dropdown and Boolean. Not working

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#955]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you create dropdown with boolean - its not working.

### Expected Behavior

I should work.

### Steps to Reproduce

Create dropdown with such fields
<img width="292" alt="Screenshot 2023-06-02 at 08 07 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/4ab61dbf-ec3b-46c2-93b6-9087326439f8">
You get this errors
<img width="314" alt="Screenshot 2023-06-01 at 10 27 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/df129d4c-c11e-4ae3-acb5-a334457679f2">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis8GojnPO0ESs+lYldUOP2kdFZEJ02kiT4X/MmNkuDLJPUoNSWqQLly+pFhVRbKRn2tVq2bCYS3b0BPJ/tWBUvH1qeniB1SPtR2LmQd2Ez3COevTnTBJ4+yNUdMD+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to use boolean in my dropdown

### Visual documentation

<img width="292" alt="Screenshot 2023-06-02 at 08 07 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/1571f218-bfe5-43aa-b9e5-b14a5973e459">
<img width="314" alt="Screenshot 2023-06-01 at 10 27 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/694f2c46-a740-4238-90ed-dce4ff99e08c">

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Mac
- Browser name and version: Chrome 113.0.5672.126
- Operating system and version affected: MacOs 13.4 (22F66)
```

**Comment by aemelyanovff** [comment]
@khomya Thanks for reporting the issue, it'll be fixed in the next update. It won't fix existing dropdowns though - you'll need to create new dropdown widgets.
