### ISSUE TITLE
Changing item value in index of an App State List doesn't work

### ISSUE THREAD

**Issue by Gabanelli** [FlutterFlow/flutterflow-issues#956]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I used "Update App State" to modify an item of a list in an index, as is presented below:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/a7e6aefd-718e-4bbf-b7d4-e40d97c3d21d)

But the value is not modified. I checked the code generated and it appears to set a value to a primitive value, not the list item reference, it can explain this behavior.

**Code generated to modify itens by index in App State**
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/6992dd3b-2f30-431e-a7ff-053291385ccf)

**Code generated to update the item (note there is a callback with the current value, but in this way the reference doesn't change):**
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/93c7cdd1-1c75-4333-aad4-5a60648b5061)

### Expected Behavior

The expected behavior is that the value specified by index was changed in the list

### Steps to Reproduce

1. Create a List of String in app state with one value
2. Create an action of Update App State trying to change this value to any other

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grtdD1qnTYMZAhQAkH1x/bZJEl9caawA0fYOtP6QTd+r+VBNVO8ufYW1iI1WIpDgC+srGiezlFvo4aCqceINo/6pQUhWXZGa7VJCWPM+eSnRBM95RGFCG1rSvvhZAXelZW3Afw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I'm trying to create a modifiable dynamic list that can accept multiple inputs from user

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/c21573b8-1198-42ca-87da-89f103bc6c1e)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/6442870d-8b7f-4924-872c-5cb97baf7145)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/b38b868a-2d67-42b8-9af9-fdadcd2d0d44)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/8a197351-5b34-4abe-8b6a-21d0c0e4b984)

Before click
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/362645d4-2968-445d-bd08-092b1e975ae7)

After click
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45363782/e9464532-0523-49a1-a512-e9fadef7b00f)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web, but can impact any
- Browser name and version: Chrome 113.0.5672.129
```

**Comment by wenkaifan0720** [comment]
Hi @Gabanelli. I can see the test project is working now, right?

**Comment by Gabanelli** [comment]
@wenkaifan0720 It's working perfectly, thanks!
