### ISSUE TITLE
copyWith now that Built_Value is no longer used

### ISSUE THREAD

**Issue by trevorFields** [FlutterFlow/flutterflow-issues#960]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

this is not a bug but i am reporting it as a bug because it is a major issue for custom code.

now that FF has switched from built_value it causes a lot of issues with side effects on mutable objects.

when this was released/updated there is no copyWith method available creating a lot of extra code when working with data types, this can create hours of hunting down the issue. 

i am currently using the toMap, then fromMap to limit code and not have to explicitly create each field in the new dataType but this is not an elegant solution.

### Expected Behavior

being able to work with datatypes in custom code and now causing lots of side effects if objects are not properly copied.

the issue is when you had a lot of code relying on built_value the conversion has been hard. and during that conversion without copyWith method creating copies of the objects is cumbersome and buggy. 

### Steps to Reproduce

1. need to create a data type
2. use custom code to edit the object
3. i know creating copies of objects is standard but since we are having to convert a lot of code without copy with it is dificult to make sure all objects are copies and not original objects

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

custom code

### Visual documentation

non

### Environment

```markdown
- FlutterFlow version: latest flutter flow using custom code
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @trevorFields - I appreciate you bringing this up. Unfortunately, as this is not a bug, we will not be looking into it. I agree that the built_value update requires some adjustment for the existing custom code. If you require assistance, I advise contacting the support team through the chat window in the FlutterFlow editor. 

I am marking the issue as not a bug. Thanks
