### ISSUE TITLE
Custom Action error

### ISSUE THREAD

**Issue by PhilippBekher** [FlutterFlow/flutterflow-issues#961]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! I'm trying to use the library, but facing troubles. After compiling I see thee error: "Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor."

Action code:
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:al_downloader/al_downloader.dart';

Future<void> downloadObject(String url) async {
[//added](https://added/) the line as get error about AlDownlaoder undefined
  ALDownloader.initialize();

  final taskId = await ALDownloader.download(url);
}

Arguments: url ( string )
Pubspec Dependencies: al_downloader: ^1.7.4
Action Name: downloadObject

Thank you in advance!

### Expected Behavior

Successfully compiled custom action

### Steps to Reproduce

1. Create custom action
2. Add described code 
3. Compile

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

It's not widget

### Context

Trying to download files from url

### Visual documentation

<img width="1470" alt="Step 1" src="https://github.com/FlutterFlow/flutterflow-issues/assets/67826951/783426f5-3003-48dc-8417-f21948bea015">
<img width="1470" alt="Step 2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/67826951/9b8c9c9c-e122-4127-901e-67e1506c3b3b">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, MacOS
- Browser name and version: Chrome, 113.0.5672.92
- Operating system and version affected: macOS v12.5
```

**Comment by hariprasadms** [comment]
Hi @PhilippBekher - Thanks for reporting the issue. In the steps, I do not see you have added package dependencies details.  Follow below image instructions. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b7b9cf9b-8741-4dda-aafe-683f5abc1f91)

**Comment by hariprasadms** [comment]
This is related to missing configurations at the user end. Hence closing the issue.
