### ISSUE TITLE
Custom Data types disappeared from App State ?

### ISSUE THREAD

**Issue by l00f00** [FlutterFlow/flutterflow-issues#962]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://community.flutterflow.io/c/bugs/custom-data-types-disappeared-from-app-state

Latest update disabled options to save datatypes in appstate, and use datatypes in general in all FLUTTERFLOW platform, you can add them but not use them anywhere.

Downloading code i see datatypes are generated as files in \lib\backend\schema\structs but unusable in all flutterflow.

### Expected Behavior

datatypes to be usable as in docs https://docs.flutterflow.io/data-and-backend/custom-data-types#creating-custom-data-type

### Steps to Reproduce

1. add a datatype
2. try to make an app state to save it
3. try to make a list to show datatype from app state var

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEel/H14othpb0F1qqJc8BahQMxQUQ5a50rlu1FGUkdC7nnBKQqZ87EaXduXseDS2x2H02kknEz0MmMkuPhNMIqZDmAbqF607gMWhaVYGOgR82sOruCZUYnAdpPJlPF5KuzuiNSG7ZodXBn31+Pcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Use datatypes to save selts from api call in app state, is blocking to deliver the app.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43296799/ac1702fb-02d7-4a39-a354-67fa70bd6e85)

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Flutterflow
- Browser name and version: Chrome latest
- Operating system and version affected: Win/android/Chrome
```

**Comment by hariprasadms** [comment]
Hi @l00f00 - Thanks for submitting the issue. This is related to configuration. To see datatype option available in **AppState**, **deep linking** should be enabled in the project. See below. 

<img width="1510" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8921aec9-f54b-4d10-b22f-dd4a6163240b">

**Comment by l00f00** [comment]
Thanks alot!

**Comment by l00f00** [comment]
Updating to new release resets deeplinking ?

**Comment by hariprasadms** [comment]
Thanks for confirm the point. We will look into it. However, I am closing this issue.

**Comment by DiegoteWhite** [comment]
Yes!!!!Thank you!!!!!
