### ISSUE TITLE
Permission Util Auth File missing since new Flutterflow Update

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#963]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app doesn't run on local IDE.

### Expected Behavior

I was expecting my app to run without any issues..

Screenshot attached for more details

### Steps to Reproduce

1. Make Changes to your Project
2. Push your integrations on Git
3. Run your project locally.
4. Build the app.
5. Project Fails with error 
6.  **_Error: Error when reading 'lib/auth/auth_util.dart': No such file or directory_**
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcj1sIZIvsBE7aX6bu9Vp2M7HDp7bb00sNobbxAjIoDoPJkUac/RPxFVXu3ndHxDKEWGrFky0NLoueHtEvQFFwmbbp8/zJBcST3NWkC/aoSXO6iKT0d5Fptjfna106aFkQpQD/tZL2AO2EyEf+nLShDbHZP7Zwh9f6PHaOI=

### Context

I want to push my app changes to github and test it out locally in IDE.

However, when building the app. I have checked that the project is missing the permissions_util.dart file from the projectGit Hubproject

### Visual documentation

https://imgur.com/a/Onaek2M

### Additional Info

https://imgur.com/a/Onaek2M

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Version 114.0.5735.90 (Official Build) (arm64)
- Operating system and version affected:  MAC OS Ventura 13.4
```

**Comment by hariprasadms** [comment]
Hi @Dev-Muhammad-Junaid - Thanks for submitting the issue. Below is your project downloaded code folder structure. You can see auth_util.dart file is present under lib/auth/ path. This is new change in the latest update. Make sure your git push got all these latest updates and merged to the local project. 

I hope this helps you. Thanks 

<img width="429" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/cd05f297-87c0-4f4b-8868-2fa75f5078a2">

**Comment by superkeven2020** [comment]
Hi @hariprasadms  I use I had same error when I deploy my app to store from flutterflow, and I didn't change anything since last update
<img width="626" alt="iShot_2023-06-03_20 29 10" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/75b212e7-5734-469e-b33c-56c69fa823bc">

<img width="604" alt="iShot_2023-06-03_20 29 42" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/222e7e4c-e6f9-4875-8f6a-d8d11d321473">
<img width="521" alt="iShot_2023-06-03_20 29 23" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/76d8aa8a-5396-4091-b327-4ee9cdf8726a">
<img width="590" alt="iShot_2023-06-03_20 29 30" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/012cebd7-d1dc-4ff8-a461-940f70e2623f">

I am sure I have set permission in flutterflow

**Comment by jeanlouisliaud** [comment]
Hi @superkeven2020 @hariprasadms , got the same issue with the error : Error (Xcode): lib/location/location_widget.dart:4:8: Error: Error when reading 'lib/flutter_flow/permissions_util.dart': No such file or directory

**Comment by superkeven2020** [comment]
if you request permission as an action on a page, that page will occur this error for sure, I think this is a bug!

**Comment by Dev-Muhammad-Junaid** [comment]
> Hi @Dev-Muhammad-Junaid - Thanks for submitting the issue. Below is your project downloaded code folder structure. You can see auth_util.dart file is present under lib/auth/ path. This is a new change in the latest updates. Make sure your git push got all these latest updates and merged to the local project.
> 
> I hope this helps you. Thanks
> 
> <img alt="image" width="429" src="https://user-images.githubusercontent.com/17435678/243093347-cd05f297-87c0-4f4b-8868-2fa75f5078a2.png">

I always rebase the project on my main branch. I'll give it another go. But something does got changed.

**Comment by agreaves** [comment]
Hi @Dev-Muhammad-Junaid, thank you very much for this bug report. I can indeed confirm this issue, and it will be fixed within the hour. Apologies for this issue and any inconvenience!

**Comment by Dev-Muhammad-Junaid** [comment]
G Thanks.
