### ISSUE TITLE
Data types getter error on Update App State

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#966]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When any Data type is cleared("Clear Value") on "Update App State" the build fails. As i mention in reproduction steps, if appstate var has default value an error appear, if is unset other error appear.

WORKAROUND: It is solver easily using "Update Field(s)"

### Expected Behavior

Using "clear value" should return the variable of AppState to default value.

### Steps to Reproduce

1. Create a data type X with many string field
2. Create AppState var of that type (keep default unset)
3. Create an "Update App State" action (inside a component for example)
4. "clear value" of X.
5. Build on test mode.
6. This error appear: The **method** 'XsampleStruct' isn't defined for the class '_HomePageWidgetState'.
7. Now add a default value to appstate var
8. Build on test mode again
9. This error appear: The **getter** 'XsampleStruct' isn't defined for the class '_HomePageWidgetState'.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/HluIhhpbxI0IfuLO5FpwMxQUB+bZ0vlO1FGBQcGJzzPYl3YePuaXdVXczhfXxUfVKj8D8xwtLyuOHhFPkEJS6CGKF607l6YT3LQkOVb7KWPc+sXEB9HZhhCmnC1qaJgAl5OrFYcnhgw2GPcq3qNleeY8aSfxBlZ7vfcPo=

### Context

No, using "Update Field(s)" solves it, but i think it is still a bug 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/4149e8b8-a00c-4459-b22c-b57daa9cd208)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: chrome 113
- Operating system and version affected: Windows
```

**Comment by victoriahuang1** [comment]
Hi @nev-21 , thanks for the report. We should have this issue fixed in the next deploy!
