### ISSUE TITLE
Supabase Background Token Refresh Resends App to Initial Page - Logged In Page

### ISSUE THREAD

**Issue by EmersonFJ** [FlutterFlow/flutterflow-issues#969]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When FF refreshes the Supabase JWT access token in the background (seems related to a trigger from onAuthStateChange from SupaFlow.client.auth.onAuthStateChange), the app temporarily navigates to the App Details -> Initial Page -> Logged In Page, before quickly reverting to the last page seen before the token refresh.

This breaks any back navigation, and also breaks any in-process user actions, such as typing.

### Expected Behavior

When FF refreshes the Supabase JWT access token, the app should not temporarily navigate to the App Details -> Initial Page -> Logged In Page. It should merely update everything in the background without impacting the use experience

### Steps to Reproduce

1. Create a blank project
2. Enable Supabase Authentication
3. Create a Log-In Page, and then two pages that you can navigate to in a chain (Logged In Page can navigate to New Page 1, and New Page 1 can navigate to New Page 2)
4. Have Back Navigation on both New Page 1 and New Page 2
5. In order to speed up testing, go to your Supabase Console -> Settings -> Auth -> User Sessions -> JWT expiry limit and change this to 60 seconds; this will force a token refresh every 60 seconds
6. Run a Test session of your app, and log in and navigate to New Page 2 (which requires going through New Page 1)
7. Wait for a token refresh (~60 seconds), you should see an update in the console log with the refreshed session, and may see a screen flash
8. Navigate Back from New Page 2, and you will hit Logged in Page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xksn1sIlPnNhJ+KruLcBFmikRMjs6U40v0e0aawo1GJzoPZoAf/T+T3JdOLyhSmw/PFv9ij003MmNkd7mV+QHAEydGpxZ1pdudwnLUk+mbraQCbjodHN8I+ZgNEuV0Z6vvhJ5Ks9ecVoZ31ybf9yATirBNO6wNWtMMOWXMqbDnG/jAj+6Xn0Jg1ZSfCvr

### Context

This breaks the ability to use Supabase authentication natively through FF, unfortunately. A token needs to be refreshed in the background occasionally, and with this temporary navigation to Logged In Page, we would have to rely on "luck" in that a user will never be navigating between pages, or interaction with the app through text input etc, when the token is refreshed. 

### Visual documentation

I do not believe any are needed here given the description above

### Additional Info

Thank you for the help here - we all appreciate your efforts at FlutterFlow!

### Environment

```markdown
- FlutterFlow version:  v3.1 (released Feb 27, 2023)
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.90 
- Operating system and version affected: MacOS
```

**Comment by EmersonFJ** [comment]
You know it is a good day when @victoriahuang1 is on the case! Thank you FF team.

**Comment by victoriahuang1** [comment]
Hi @EmersonFJ , thanks for the report! This issue should be fixed upon the next deploy.

**Comment by EmersonFJ** [comment]
> Hi @EmersonFJ , thanks for the report! This issue should be fixed upon the next deploy.

thank you for doing this so quickly!
