### ISSUE TITLE
Incorrect navigation to Initial page

### ISSUE THREAD

**Issue by gbvolkov** [FlutterFlow/flutterflow-issues#97]
I do have on a login screen a button Forgot password. On the button an action is configured, which updates local state and then navigates to the ForgotPasswordView screen.

## Expected behavior (required)

User is navigated to ForgotPasswordView screen.

## Current behavior (required)

User is navigated to the WelcomeView screen, which is configured as an Entry Page screen on App saettings.

## To Reproduce (required)

1. Create ForgotPasswordView screen.
2. Create SignInView screen with Forgot Passwordbutton, navigating to ForgotPasswordView
3. Create WelcomeVew page with  SignIn button navigating to SignIn screen.
5. Specify WelcomeVew as an Entry Page for your app.
6. Run your app
7. Press SignIn burron on WelcomeView screen
8. Press ForgotPasswrod button on SignIn screen
9. Enjoy you WelcomeView screen again.

## Context (required)

Well, the app is useless, I guess

## Screenshots / recordings

https://user-images.githubusercontent.com/67483462/200052790-4998bdbb-5748-4221-8c60-99a1352da8e7.mp4

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Edge
* Operating system and version (desktop or mobile): Windows 10, desktop.

**Comment by hariprasadms** [comment]
Hi @gbvolkov, What navigation you got while clicking forgot password link?. Can you check in code view, what line of code it has got while clicking forgot password link. As per the apps I have been working on I do not see any issues around navigation  so far. I suggest have a detail look at navigation code lines in code view and add those details here please.

**Comment by gbvolkov** [comment]
// Generated code for this Button Widget...
FFButtonWidget(
  onPressed: () async {
    setState(() => FFAppState().backArrowVisible = false);
    context.pushNamed('ForgotPasswordView');
  },
  text: 'Forgot password?',
  options: FFButtonOptions(
    width: 136,
    height: 40,
    color: FlutterFlowTheme.of(context).noColor,
    textStyle: FlutterFlowTheme.of(context).bodyText2,
    elevation: 0,
    borderSide: BorderSide(
      color: Colors.transparent,
      width: 1,
    ),
    borderRadius: BorderRadius.circular(8),
  ),
)

**Comment by hariprasadms** [comment]
Thanks for sharing the code snippet. It looks like to access the forgot password page, page should be authenticated . 
Can you please check below highlighted check box is checked ?. If it is checked, uncheck it and run the build and try how it goes. 

![image](https://user-images.githubusercontent.com/17435678/200124886-3c2fc474-e1a3-4911-a1bd-3746d9fb9177.png)

**Comment by agreaves** [comment]
Closing this as fixed, as it appears that @hariprasadms found the issue. Please let us know if this is not the case and we can possibly re-open!
