### ISSUE TITLE
Building broken  with latest update 3.7.12

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#970]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Building for web, for app store deployment, and web testing broken since last update...

https://community.flutterflow.io/c/bugs/deploy-issues-since-last-update-anyone

### Expected Behavior

Building should work 

### Steps to Reproduce

Just try to run the app, export the app to the app store, or compile the website :)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhefqwItIn7wG15SIY+xWgmU4C1McTZM3lOsYGAgjCIjoPex3Z8nUaXdCXMuqfQhmE2ekmnwKw97Vv+HLKcYpOT6VbaV607ViTQyWXTiWMq6lCcyaWnZ6AtFXCB2m56bYnyYlKuthdHA+wE+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

Nobody can publish, test, run apps :)

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/5c7d9691-cd3f-452e-af75-5ed068b91965)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/b7d7b8ac-6524-4a73-887a-772c5fcb2c2f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/10898b80-4489-45bd-9ceb-71f733fc1bb9)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/bf4fa56d-bcb2-4640-a5a9-90cb90fadba3)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @Josefpa, thanks for the bug report! This will be fixed upon the next release! It's related to updating DataTypes in your page state. As I mentioned in the community post this is actually not related to the most recent update but has been around for some time.

**Comment by Josefpa** [comment]
> Hi @Josefpa, thanks for the bug report! This will be fixed upon the next release! It's related to updating DataTypes in your page state. As I mentioned in the community post this is actually not related to the most recent update but has been around for some time.


Ahh ok! Thanks for the notice.. will be waiting for the next release for the fix 😅
