### ISSUE TITLE
Load indicator continues to show even after image loads

### ISSUE THREAD

**Issue by swhc1066** [FlutterFlow/flutterflow-issues#973]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you load an image you see the image load indicator and then the image loads but the image load indicator doesn't go away.  Additionally;y, the load indicator isn't the one selected under themes.  Its the default indicator.

### Expected Behavior

After the image loads the load indicator goes away.

### Steps to Reproduce

1. Go to postsList screen
2. Tap the + icon
3. Tap the camera icon and select an image to load.
4.  Add title and post content
5. After image loaded message appears tap Post
6. You are taken back to postList
7. Tap the post just created.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OzMrl8ZNJpbxe0KrUKfpahmMXQkA9aqxMk8FuZ0wdfbXNGrUqe/TBYk5UOfXkSn9pe060insX/Mrlj/LhCfk7GziVQJxH1ZBbEjvyIWe6VLqMOpS3b3BfO+hXfnaYyLSFpCNCNrBfciVh3WWIJtyicHfqH4TvPUg/B+aeXdeK2SrDX1iXc2URm05KZDPz

### Context

I cant push to the App Store with this bug.  The idea of this app is I can send customers images of their guitars as they're being built.  I cant sned them images with image load indicators running over the top.  That's a horrible experience.send

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/6545502/b537bc08-1c1b-4518-8b67-a1c91d16e322

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: macOS
- Browser name and version: Chrome Version 113.0.5672.126
- Operating system and version affected: macOS Monterey 12.5
```

**Comment by aemelyanovff** [comment]
@swhc1066 Thanks for reporting the issue. Can you update the steps to reproduce to start from a blank project?

**Comment by aemelyanovff** [comment]
Closing as inactive. @swhc1066 please feel free to reopen if you add steps to reproduce from a blank project.
