### ISSUE TITLE
Translations bug after copying widget style

### ISSUE THREAD

**Issue by GiovanniBaldo** [FlutterFlow/flutterflow-issues#974]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i have 3 text a row
after copyiing style from one text widget to the other 2, its not possibile to modify the translation of the single text without affecting the other 2. it seems all the 3 text point to the same translation

### Expected Behavior

the expected behaviour is that each text has is own translation

### Steps to Reproduce

0 define 3 languages in the project
1 create new page 
2 add a column
3 add a row 
4 in the row add 3 text
5 adjust spacing as u like
6 define translations for each of the 3 text
7 format the first text as u like (color bold font etc)
8 copy widget style from first text to other 2. U will notice that it will copy also the translations.
9 from this moment u when u will change translation of each of the 3 text will be reflected on the other 2

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cz8jfz4pPxPVY0LrUb8FsgSQsH1whRYJMicB9cxUYN5PMC+wIZ/f7XFRuTde0T3xbM2Gjjjsy08HemvPiGO1cHyutfbpi/7lubgrMRmKmeK3WC5GSYW5/AtJhfHac4be7nBJ/PrFaV39k6mayOuyAYCzYCYOxCkYZPv7/F5OK2SrDX1iXc2URm05KZDPz

### Context

nothing more to say

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70816346/5db1060f-450d-4384-9060-c65b81bbc751)

### Environment

```markdown
- FlutterFlow version: v3.1 - flutter 3.7.12
- Platform: any
- Browser name and version: Chrome Version 113.0.5672.127
- Operating system and version affected: windows 10 (it's the same on macos)

project https://app.flutterflow.io/project/translations-bug-md94fk
```

**Comment by hariprasadms** [comment]
Hi @GiovanniBaldo - Thanks for reporting the issue. I can reproduce the issue in my test project as well. As part of copy style feature, it should copy over the translated text details.

**Comment by hariprasadms** [comment]
> hi @hariprasadms - thanks for your answer. Good that u can reproduce the issue. About "As part of copy style feature, it should copy over the translated text details.", let me say that is not too useful (my opinion). Imagine that u have 10 text all with different translations. Now u change the style of one of them and when u copy the style to the others u will loose all the transaltions?

Hi @GiovanniBaldo - Sorry. my earlier comment giving totally different meaning as I am missing 'Not' in the statement. I agree with your comment. I just updated my earlier comment. Thanks
