### ISSUE TITLE
[Bug] - Page state with Data Type variable has not function update field(s) properly

### ISSUE THREAD

**Issue by davidcast95** [FlutterFlow/flutterflow-issues#976]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to initial a variable with my Data Type in Page State, then I need to update field on that variable's field.
It reproduce a bug, says that the function does not exist

### Expected Behavior

I think in model widget class level, the function must be exist to update the module struct

### Steps to Reproduce

1. Create Date Type, ex: Bug with 1 field name (String)
2. Create a new page
3. Create a variable Data Type, ex: document (Bug / Data Type)
4. Initialize the variable when Page On Load, create Data Type Bug set to document (field name set to null)
5. Connect to label field name (String) inside document (Bug / Data Type)
6. Make a button action to update fields (Update Page State > Update Field(s))
7. Set field name (String) random data, ex: sample First and last name
8. Bug will be reproduce, says that the function does not exist

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kls/l7YVgobxG7rXuavlR/WEWNlgnbZIolu1ue0wbfKr2G7l/TMnOVBJuOLC0TX9ifWCakXMK+dXemvLlEvFdZAqtGLk7yqpUbw6VJVOuVqaJELm0WW5/DfJmGnKO35iG2yVQVdVsWWRn3E62GO6/TgjDK5TyDTJMHfiHMZOK2SrDX1iXc2URm05KZDPz

### Context

I need to update document variable (Data Type) to make a logic into my form

### Visual documentation

<img width="758" alt="Screenshot 2023-06-06 at 23 03 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21123345/0b923865-3663-4a3a-ba1e-ae634d26ceb6">

It says
`Try correcting the name to the name of an existing method, or defining a method named 'updateDocumentStruct'.`

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Any platform
- Browser name and version: Chrome Version 113.0.5672.126 (Official Build) (x86_64)
- Operating system and version affected: macOS
```

**Comment by kevintonb** [comment]
Hey @davidcast95 thank you for reporting this issue and providing the steps, I was able to reproduce the issue!

**Comment by wenkaifan0720** [comment]
Hi @davidcast95. The issue should be fixed by now. Could you double check? Thank you.
