### ISSUE TITLE
Google Maps multiple document markers not working (crashes on compiling)

### ISSUE THREAD

**Issue by Thesergiolg99** [FlutterFlow/flutterflow-issues#977]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you try to query some documents with LATLON fields, and then use them as document markers in google map widget ( multiple markers) it stops working. Only with that configuration. Single marker works and if you do it with LATLOn instead of using document it will work too.

It crashes on compiling. Also if you try to copy that widget code it will give an error.

### Expected Behavior

To let you use the documents as markers, it used to work before last update.

### Steps to Reproduce

1. Create new page
2. Add google maps widget
3. query a collection with LATLON fields
4. Add multiple markers and select the list of documents
5. Now try test mode, will crash. If you try "copy widget code" will show an error too.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kj8ncx891oelJ7aqIbe1KvCAXNnk1TL03qu0bGBYbCIzQB4YEaffRalhuQt+nT0FLKEWKingK0NLKi+OSG8YpBEycf6py/rgBSRbzRki/aouaDpOefnYmM/xbJ0y00JjUkAhAIulZdF4a3GWYO/OvE3bvNLn7Zwh9f6PHaOI=

### Context

To have a map with all the markers from my docs.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/0225c9bc-b83a-412a-b653-8927a1bec71c)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/8e74651b-5310-47eb-8630-8b59574c40e5)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/72013520/3a94e38b-00de-48cb-9a32-5b0944945e31)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Brave v1.52.122
- Operating system and version affected: Windows 11 last build
```

**Comment by hariprasadms** [comment]
Hi @Thesergiolg99, Thanks for reporting the issue. I just tested the map and its multiple marking feature. It works fine. See below. I guess there could be missing configurations. Please have look. If you need more assistance, reach technical support team using chat window inside FF builder. Thanks 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/de35c113-20ed-4558-a14a-66c0af334ee3

**Comment by Thesergiolg99** [comment]
> Hi @Thesergiolg99, Thanks for reporting the issue. I just tested the map and its multiple marking feature. It works fine. See below. I guess there could be missing configurations. Please have look. If you need more assistance, reach technical support team using chat window inside FF builder. Thanks
> 
>  map_multiple_marks.mp4

Thanks for the response, are you using Algolia? We use the results from algolia and its not working. The thing is it used to work and we didnt change anything. If we use the same documents but instead of documents the Latlon option, it will work. So it cant be a missconfiguration issue.
thanks in advance.

**Comment by hariprasadms** [comment]
Hi @Thesergiolg99 - Thanks for confirming. As your describe, can you please setup a blank project with exact issues steps. So that it can easy dev team to point to the issue and come up with a fix asap. Thanks 

I can take another look at the issue once you have updated it with a blank project and the issue steps details. Thanks.

**Comment by Thesergiolg99** [comment]
> Hi @Thesergiolg99 - Thanks for confirming. As your describe, can you please setup a blank project with exact issues steps. So that it can easy dev team to point to the issue and come up with a fix asap. Thanks
> 
> I can take another look at the issue once you have updated it with a blank project and the issue steps details. Thanks.

Hi! thanks for your answers, i finally got to reproduce que exact issue of the google maps. Documents of multiple markers wil ONLY work if the query is done on the google map widget, if done in other site of the page, there is the error.
steps to reproduce:
1) Blank page
2) add some column and stuff
3) add the google map widget somewhere
4) create a collection query to get various documents with latlon fields (this query MUST NOT be in the maps widget)
5) Create multiple document markers of that query
6) Now it wont compile or work. Also it wont let you copy the widget code of the map.

Hope now you can reproduce the issue.
TIA.
Sergio.

**Comment by hariprasadms** [comment]
Hi @Thesergiolg99 - Thanks for confirming the details. To fix this issue you should use App States to pass the list of marker and once map loaded completely, binding list of markers to list of markers variable. I would suggest reach Technical support team to get more help around it. Thanks

**Comment by hariprasadms** [comment]
Hello, I hope you've found a solution to your issue. We think you learned a solution and are no longer blocked. Hence the issue is closed. Thanks

**Comment by ChrisLowCode** [comment]
I am having a similar issue. I have reached out to support and awaiting response. Hoping I can maybe find help here in the meantime as this may beyond their scope.

I am using the Algolia search (also tried Simple Search) and trying to use "Documents" as the Marker Type in the Google Maps widget. The code does not compile and cannot be copied and the app fails to be deployed or tested even though FF doesn't recognize an error before trying to test. If I use LatLon for Marker Type, the map displays the markers just fine. The only problem in my situation is that I need to be able to pass the "Current Index" of the Marker Document to a Bottom Sheet on action "On Marker Tap".

Steps to replicate. 

1. Create bottom sheet with a parameter (document)
2. . Create separate blank page
3. Add Simple or Algolia search
4. Add the Google Map widget 
5. On Google Map Widget Add: 
 - Multiple Markers
 - Marker Documents (choose from search)
 - Everything else can stay as default
7. Add action "On Marker Tap" -> "Bottom Sheet"
8. Send a Document parameter to a bottom sheet using "Marker Document" -> "Current Index".

This was working fine prior to the last or second to last update. 

Now it wont compile or work. Also it wont let you copy the widget code of the map.

**Comment by ChrisLowCode** [comment]
I figured it out that there needs to be two Queries. One in the search (works with Algolia), the other as a backend on the Google Map and then the Marker Document will be able to pass data.
