### ISSUE TITLE
Firebase Rules won't get updated

### ISSUE THREAD

**Issue by slvkrvnsv** [FlutterFlow/flutterflow-issues#978]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The problem is stated in the Title – when I'm trying to deploy the new rules for my database (which has been functioning **properly two days ago**), I receive this error message:
<img width="716" alt="Screenshot 2023-06-08 at 15 53 20" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118440068/1755d79f-0ccb-4f76-8add-2a617bb9ceb4">
It has started yesterday night, I tried to make it few times from mac app and from web, one time succeed, but not anymore.
I see so many messages in Telegram from FF users having the same issue and I'm surprised it's not reported yet.

### Expected Behavior

Rules got deployed as usual:)

### Steps to Reproduce

Create new DB
Try to deploy new rules
Receive the error
Do everything it asks you to do t o fix this (including setting the region)
Try to deploy new rules
Receive the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none

### Context

Regular database hustle, I added user collection and can't update anything in here because old rules won't let me do it.

### Visual documentation

<img width="1068" alt="Screenshot 2023-06-08 at 21 33 25" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118440068/5ea752c6-ec1b-41ee-9361-0b6a4a1fc0e9">

### Environment

```markdown
- FlutterFlow version: 1.1.80
- Platform: mac desktop app and web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by Josefpa** [comment]
May be related: https://github.com/FlutterFlow/flutterflow-issues/issues/979 ?

**Comment by pauloleme93** [comment]
same problem here!

**Comment by hariprasadms** [comment]
Hi, We are aware of a few number of users that are having trouble successfully deploying firebase rules in their projects. We are looking at it. Share your project's bug report code here. We can have a look at it. Thanks

**Comment by aemelyanovff** [comment]
@slvkrvnsv Thanks for reporting the issue. It's been fixed - please try again.
