### ISSUE TITLE
Phone authentication SMS text %APP_NAME% = app.flutterflow.io

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#98]
SMS Template is
%LOGIN_CODE% is your verification code for %APP_NAME%.

Default
%APP_NAME% = app.flutterflow.io

I can find any way to change/edit %APP_NAME%. 
How do i edit this?

**Comment by organicnz** [comment]
@palmdeskApp - hey mate, we need more details so we could reproduce your problem. Could you please edit your issue as 
 it was featured in the FlutterFlow GitHub issue template? :)

**Comment by palmdeskApp** [comment]
Let be explain this problem in detail. 

This is a bug in Fluttflow - firebase_authetication integration
I have successfully integrated fluteerflow with firebase
I have successfully using phone authentication facility.
App is sending authentication message. 

SMS text received by user is;
"123456 is your verification code for app.flutterflow.io."

App name should be name of the project added in FlutterFlow. 

For send OTP message, firebase authetication is asking flutterflow to supply app name (%APP_NAME%) .
App name supplied by flutterflow is app.flutterflow.io.

Hope issue is clear now.

**Comment by palmdeskApp** [comment]
FlutterFlow - Firebase Phone Authetication. 
Bug in SMS template. 

https://console.firebase.google.com/project/ksedmlap/authentication
--> SMS verification --> 

SMS verification
Allow users to sign in using a one-off passcode sent as an SMS to their mobile phone.

Message (template)
%LOGIN_CODE% is your verification code for %APP_NAME%.

.........
Firebase console is receiving %APP_NAME% details from FlutterFlow

.........
SMS received by users is
"123456 is your verification code for app.flutterflow.io."


.........
User should ideal receive following SMS text ..
"123456 is your verification code for app_name_in_FlluterFlow."
"123456 is your verification code for ToDoApp."

**Comment by agreaves** [comment]
Hi @palmdeskApp, what platforms does this occur in? Web, iOS, Android, etc...

Also, if you can please include the bug report code for this project (you can right click anywhere in the widget tree to generate this).

**Comment by palmdeskApp** [comment]
I currently do following .. 
FlutterFlow --> open Project -->  Run --> SignIn Page --> Enter phone number --> Otp SMS is sent on phone number entered. --> SMS text received is as mentioned above. 

As i understand Firebase authenticating is collecting "%APP_NAME%" from Flutterflow-Run.
or
FlutterFlow run is transferring %APP_NAME% to firebase_authetication to send SMS. 

eitherway, Flutterflow is giving wrong string for %APP_NAME%.

**Comment by katherineqian** [comment]
Since this issue has not had any activity for a while, and it is difficult for us to assess or reproduce this without the bug report code for the affected project, I am closing this issue as stale for now. 

If you are a user who is also experiencing this issue, please do not hesitate to leave a comment with details about what's going on, and we will reopen the issue.
