### ISSUE TITLE
Responsive Value variable should also cater for width percentage

### ISSUE THREAD

**Issue by uumdev** [FlutterFlow/flutterflow-issues#980]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to set my container's width with Responsive Value variable as percentage. But currently FF just treat the variable as pixel value.

If we set width PX = 70, the produced code is
```
Container(
                    width: 70, 
                    ...
```

If we set width 50%, the produced code is
```
Container(
                  width: MediaQuery.of(context).size.width * 0.5,
                  ...
```

When we set width with Responsive Value, the produced code is
```
Container(
                width: () {
                  if (MediaQuery.of(context).size.width < kBreakpointSmall) {
                    return 20.0;
                  } else if (MediaQuery.of(context).size.width <
                      kBreakpointMedium) {
                    return 20.0;
                  } else if (MediaQuery.of(context).size.width <
                      kBreakpointLarge) {
                    return 60.0;
                  } else {
                    return 10.0;
                  }
                }(),
                ...
```

### Expected Behavior

Current behavior only cater for PX. You should consider producing this code to cater for %:
```
Container(
                width: () {
                  if (MediaQuery.of(context).size.width < kBreakpointSmall) {
                    return MediaQuery.of(context).size.width * 0.2;
                  } else if (MediaQuery.of(context).size.width <
                      kBreakpointMedium) {
                    return MediaQuery.of(context).size.width * 0.2;
                  } else if (MediaQuery.of(context).size.width <
                      kBreakpointLarge) {
                    return MediaQuery.of(context).size.width * 0.6;
                  } else {
                    return MediaQuery.of(context).size.width * 0.1;
                  }
                }(),
                ...
```

### Steps to Reproduce

1. add container widget
2. set width with Responsive Value
3. Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8KhvHqx4hOxLhK1aXide9aljgXOVwjRY0ZktVhcxc1F5jyPbMIY8/4V1ZVZNO8Ym9AfVmZrDse1tHtiYbpCvkCCwutbL5t1LoJWhXzTmaWaJuDGbioOHRtO9hPfVCF5KurrAlAG/VidCU93XGEAvaSXgHcGOfjPm4zAcmYUaXMpXjhKiToFC9F4w0ORhaWP8kETAmxhouUtpJh0eDnyw==

### Context

I want to set the width percent responsively.

### Visual documentation

<img width="316" alt="Screenshot 2023-06-09 at 8 35 28 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17571660/587cded7-1a4d-4d50-86dc-a05ec2f021e3">
<img width="499" alt="Screenshot 2023-06-09 at 8 33 04 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17571660/543a21ff-21e1-4353-be23-75e4f3b473a0">

https://github.com/FlutterFlow/flutterflow-issues/assets/17571660/e5ca4f94-db29-4ccc-aaa3-ab6caacf6554

### Environment

```markdown
- FlutterFlow version: 3.1 (release June 9, 2023)
- Platform: web
- Browser name and version: Chrome 113.0.5672.126
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment]
Hi @uumdev. You actually can use percentages in conditional values. If you click on the set from variable icon for one of the conditional value, you should find option `Fraction of Screen Width/Height` under global properties.

**Comment by uumdev** [comment]
Your are the man! Thanks.
