### ISSUE TITLE
Using a custom dialog within action block crash the app

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#981]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the app tries to compile fails and crash the app

### Expected Behavior

I want add a custom dialog within an action block

### Steps to Reproduce

1. Create a component and a add text widget
2. Create an action block and add a custom dialog using the component created previously
3. Call the action block on the load page action
4. The app crash when is compiling

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol/KB249OxLlE7ZDAb/owvyQWH1x8U78r0spBZywgfZzzBLN/fPfQPhNCOMO+d1ZUPmKMp14C+ezWhd71FsdePTSYbYRx+ah2EBbNczqtM7WTF7mOWnAkI/9jG2LE0pmvvBJ+PuxuS1oE72GQHNy/VjDrH5jrOWo8Sq/LZO4=

### Context

I want add a custom dialog within an action block

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36147203/2bcd6982-91f2-493f-8a89-ec6fd1d48620)

### Additional Info

https://schoolfy365.tinytake.com/msc/ODMxNzMzM18yMTU3MDUxNg

### Environment

```markdown
- FlutterFlow version: FlutterFlow v3.1 released June 8, 2023
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.110 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hi @Franco98404, thanks as always for the detailed bug report! 🙂

This will be fixed within the hour!
