### ISSUE TITLE
APK download not working

### ISSUE THREAD

**Issue by Shrihari1357** [FlutterFlow/flutterflow-issues#982]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am building an app with complex custom codes. The app was downloaded before. But without doing anything to that same app there is error while downloading. The issue blocked  my development and testing. I came to know that issue is from FF  side. 

### Expected Behavior

APK download 

### Steps to Reproduce

Create an app
Add code from pub dev agora ui kit.
Then download the APP

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5XiPLq2492obgA7pPuasFFiicWOUgnargrke1udws1G4zwPZl3Zc7ET3FdOLynSnxIOWGjnnIIpvPGuIf1FMY4Aw+IQ75Ez81QThXwWT6hWq6SPruKY3ElGf5TfGal56COighQIrJZLUIO2E6TNem8bATdQ+fzO1UWRM6aGL35kWikK3r0Uzh2tmNecCfn

### Context

APK download is must for me to test my App. It blocked my development. I posted it in community and got reply from your expert. He also reported this issue. So Please correct the issue.

### Visual documentation

![errorapk](https://github.com/FlutterFlow/flutterflow-issues/assets/101409498/517b0168-fd8e-4488-90f4-6deb5f94761e)

### Additional Info

![errorapk](https://github.com/FlutterFlow/flutterflow-issues/assets/101409498/22e03d20-8626-40e2-94ee-981e2d0cec59)

### Environment

```markdown
- FlutterFlow version: Latest version 3.7.12
- Platform:Web
- Browser name and version:Google Chrome Latest
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @Shrihari1357 - Thanks for posting the issue. In general, Apk file download feature working fine as per latest updates. I did try in your project as well, Apk file downloaded successfully. I would suggest try once again at your end. If the issue persists I would advise contacting the FF technical support team through the chat window inside the FlutterFlow editor. 

Thanks
