### ISSUE TITLE
Project not saving

### ISSUE THREAD

**Issue by Webberboy** [FlutterFlow/flutterflow-issues#983]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello i am also having this issue 
it saying error saving this project
I have done a lot of stuffs on the app before I noticed it didn't save them
I am building my first app 
pls help

### Expected Behavior

projects should save
all edits i have done should still be in my workspace

### Steps to Reproduce

1. Save project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

there is no way to get the debug code my workspace is blank the works have been deleted

### Context

I want to be able to save my project

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/136114018/840655e0-5ced-46ae-bfe5-f5ec42f8b59e

https://github.com/FlutterFlow/flutterflow-issues/assets/136114018/146a23a6-aaf5-4250-a713-581d13d0ac58

### Environment

```markdown
- FlutterFlow version: 3.1 Released in June 8
- Platform:Mac
- Browser name and version: Chrome Version 114.0.5735.106 (Official Build) (x86_64)
- Operating system and version affected:
```

**Comment by homelogicatl** [comment]
i too am having the same issue with "error saving project"

https://www.loom.com/share/63281ca3fa294d28838ac1fd7e445064

**Comment by homelogicatl** [comment]
> @Webberboy and @homelogicatl can you both post your project links so the team can look at them?

i dont know how to do that   i see a share link on the left but i think that just shares the running app and not the editor

**Comment by bulgariamitko** [comment]
@homelogicatl when you open the project just copy and paste the project link from the url in your browser.

**Comment by homelogicatl** [comment]
oddly enough the problem seems to have solved itself. maybe the flutterflow team found a global solution.  this was actually my 2nd attempt at this project. the first time had the same issue and i decided to just start over since i hadnt gotten that far,  then it happened with the new project as well.  currently both projects seem to be saving correctly. 
thanks for the attempt to assist!

**Comment by cijjas** [comment]
Our team is having the same problem, just one of the users is able to apply changes that get saved, the rest of us are unable to make progress on our 4 month project. Please help us on this one.

**Comment by bulgariamitko** [comment]
@cijjas , please post a link to the project

**Comment by rvcarlig** [comment]
@bulgariamitko I am encountering the same issue on my project: https://app.flutterflow.io/project/reports-helper-b2suj5

**Comment by affanminhas** [comment]
[
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91800612/e59bb54f-fea5-4938-92b8-7e3bd4ac6d15)
](url)

I am working on this project and suddenly it says you are offline but the internet connection is working fine I try to logout and log in again but still there. I can not save my single work. It happens to me most of the time.

**Comment by affanminhas** [comment]
> [ ](url)![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91800612/e59bb54f-fea5-4938-92b8-7e3bd4ac6d15)
> 
> I am working on this project and suddenly it says you are offline but the internet connection is working fine I try to logout and log in again but still there. I can not save my single work. It happens to me most of the time.

I found the temporary solution as I have created a duplicate of my project and it runs fine and also saves successfully! I don't know what is actually the reason for not saving my original project.

**Comment by Koshcush** [comment]
It happened to me also, but its not an optimum solution to glow things like that. FF is exptected to be working much better than this.

**Comment by devjoter** [comment]
Hi is there any new regarding this issue? 
I am having similar issue with the project settings. 
If I turn on toggle for App Check settings for project in Flutterflow, and at some stage i decide to comme back to it later, this toggle switch goes back to off possition. This way i cannot implement App Check for my app. I have that feeling its a part of the issue described above...

**Comment by Koshcush** [comment]
I duplicated the project it worked. Hope it won't occur again. @agreaves is there any updates on web app first Loading speed improvement as it takes 10 to 15 sometimes 20 seconds for my web app to load on any browser which is not optimal for customer Experience I know flutter is not perfect for web app but it even takes more time on Flutterflow. Please advice. Thanks

**Comment by devjoter** [comment]
@agreaves Thank you very much for answering...pleas keep me informed if You find the bug... much appreciated

**Comment by agreaves** [comment]
Hi @devjoter, apologies for the delayed response. The App Check issue should now be fixed if you refresh FlutterFlow! (Assuming you are using web, MacOS fix coming later).

**Comment by devjoter** [comment]
@agreaves thank you very much for solving this issue. I own you a good beer mate...
