### ISSUE TITLE
Dynamic links do not work when App Opened but works when App closed/killed.

### ISSUE THREAD

**Issue by SamyKhara** [FlutterFlow/flutterflow-issues#984]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The following doesn't work:
1. Open App → Click on the shared link → specific link of the shared post doesn't open -> App stops responding.

The following works:
2. Close/Kill App → Click on shared link → Post details of the shared post opens.

### Expected Behavior

1. Open App → Click on the shared link → specific link of the shared post doesn't open
2. Close/Kill App → Click on shared link → Post details of the shared post opens.

### Steps to Reproduce

1. App open
2. Goto another app to open shared link
3. Link stuck on "Root page"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcmAsIV2pbxY17X5bcAw9TwsJU99TL03pu0bFEggGLbrBIYMacmkVEpuUt+5T1ZtKEWLkkw10+jyidmeCPAqIS+uQapF/rtiWg7NeH2/aoSXBauSYUcnEeNTN36m0LunmhNQFNdpLk4l70y2Fd++QXbXK5f7Zwh9f6PHaOI=

### Context

I am facing the same issue. I contacted FF support for this about 7 days ago but received no resolution.

The following doesn't work:
Open App → Click on the shared link → specific link of the shared post doesn't open

The following works:
Close/Kill App → Click on shared link → Post details of the shared post opens.

This means the following work:
1. AppCheck
2. Dynamic Linking
3. Share functionality

The error seems to be due to FF bugs

### Visual documentation

![WhatsApp Image 2023-06-11 at 10 24 06 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/638acfd3-d38a-49c8-bcac-f82494c365b4)
![WhatsApp Image 2023-06-11 at 10 25 00 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/fda47459-823a-4224-abdc-849ba80f91e6)

### Environment

```markdown
- FlutterFlow version: v3.1 (released June 9, 2023)
- Platform: iOS
- Browser name and version: Chrome 113.0.5672.126
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment]
Hi @SamyKhara - Thanks for reporting the issue. Dynamic links are not any more recommended strategy by google. I would suggest try to use deep linking. However, I have tested both deep linking and dynamic links, they are working as expected. 

I just found below points. Do the correction and check if that can help you.

<img width="842" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ba92ec92-4f44-4ee7-9f25-57572c943033">

**Comment by SamyKhara** [comment]
Hi @hariprasadms - I tried changing the scheme name as well. The behavior is still the same. Moreover, Dynamic Link doesn't allow App Name in scheme name. Only https.

Also- currently, in FlutterFlow, if I do not use a Dynamic link, I believe I do not get the optionality to Generate Current Page link with a Title, Description, and Preview Image (see 2nd image).

<img width="738" alt="Screenshot 2023-06-17 at 5 09 49 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/f5186ad6-6b93-485b-b797-55a2f2a27fa9">

<img width="1164" alt="Screenshot 2023-06-17 at 5 12 58 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/3dead365-70d0-41db-886c-3f43ea8bcf49">

**Comment by Djacksonspears** [comment]
Issue still existing for me on both deep and dynamic links

**Comment by Djacksonspears** [comment]
> Was this issue resolved? I'm facing same issue.

did you ever get it working ?
