### ISSUE TITLE
Join Community email never sent. Now unable to join community.

### ISSUE THREAD

**Issue by RobinopdeBeek** [FlutterFlow/flutterflow-issues#988]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I followed the documentation on joining the FF community and clicked on ? > "Join community", but I never received an email. (Yes I checked my spam). The button now says Community Forum, but when I click it it requires me to login, but I never received the email so it is now impossible for me to login/join. 

### Expected Behavior

Either I can request the email to be resent. Or I can sign up in a different way to the Community Forum. 

### Steps to Reproduce

1. Create new account. 
2. Create at least two new project. 
3. Click Join Community from the latest project.
4. Email never received. (or pretend that you never received it)
5. Try logging in to the Community Forum.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl8jfx5BgrtdA7qXcdcBr/WMvJkA1aI0vjsN+cw8bB6roPJwPXfikSEpWZ9+kTHxcL2eJhnkyp8rWhvzuA+UoBAqAfN05+JFyWxXyYFmQM5/TPs2sVkckN95JJVyn0qa3vyVvD7N2R0Yu1DiyHN+9YHHqNpDzOUczHv2JNd/Po2+pQ0SLb3kNh1JWeC/v

### Context

I have questions and issues that I would like to get help with, and now I can't use the Forum, even though it is FlutterFlows recommended way of getting help.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/bcd7516a-b34b-4f7a-b9db-12a943d80b23)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/76245735-ac5a-4677-a1f5-d5a814b250bf)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/be0ea9a0-17bf-4659-82d7-53e43e5da943)

### Additional Info

I have FlutterFlow running in Chrome in a separate window after clicking "Install FlutterFlow" in the Chrome URL area.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by kevintonb** [comment]
Hey @RobinopdeBeek , we have recently been facing some issues with Circle in issuing new invites. If you can confirm that the account linked with the project shared through the bug report code, is the one that needs access, we can manually add you to our community forum! :) Please reply with your confirmation on this thread to receive the invite to the linked account.

**Comment by RobinopdeBeek** [comment]
Ah that would be great! Hopefully no one else has the issue then. 
Yes the account shared through the bug report code is correct.

**Comment by RobinopdeBeek** [comment]
Hi @kevintonb I haven't received an invite yet. Could you send me one? :) 
The account shared through the bug report code is correct.

**Comment by kevintonb** [comment]
We have once again shared a manual invite, please check if it is accessible. If not, please contact **support@flutterflow.io** for further assistance in this.
