### ISSUE TITLE
Theme Widget copies Translation text to every instance - causes all buttons to have the same text.

### ISSUE THREAD

**Issue by RobinopdeBeek** [FlutterFlow/flutterflow-issues#989]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use Theme Widgets on my buttons and tested/published all of them would have the same text. 

In FlutterFlow:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/6a498387-0b5a-4d8e-a2ae-27ad19abf7b4)

Published:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/91de4400-2398-4784-8c22-64d4ca434a8a)

### Expected Behavior

Buttons show the text that was set up in the Editor.

### Steps to Reproduce

1. Create new project
2. Add at least two languages.
3. Create a Button Theme Widget. 
5. Add three buttons to an empty page.
6. Apply the Widget Styling to all three.
7. Change their texts (e.g. Button A, Button B, Button C)
8. Go back to the main Theme Widget and edit text (Button D)
9. Change the text on one of the buttons again. 
10. Inspect the translations on the other buttons. Notice that the translation gets copied over to the other instances. So the translation text for each instance of the Theme Widget become the same as the last edited button text. This only becomes aparant running in "test mode" or when publishing when the translation texts are used.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl8jfx5BgrtdA7qXcdcBr/WMvJkA1aI0vjsN+cw8bB6roPJwPXPykP1doTcOiTFZYMFu0hj41w/TMvt7lGOQHAziBbpRf1rhqewvJcEG7Sr6oEsyCSGhtEehmNEuV0LWNrxFCVLF1S1Jk7TmmeeiXXi/rHYTADmwnH/KjMrzVn3PiAj+6Xn0Jg1ZSfCvr

### Context

It was driving me nuts as to why this was happening. It is also really hard to get rid of when it is happening. 
Luckily for me I hadn't setup any translation texts yet, so I just removed all secondary languages and that fixed it.

### Visual documentation

In FlutterFlow:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/6a498387-0b5a-4d8e-a2ae-27ad19abf7b4)

Published:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/31888353/91de4400-2398-4784-8c22-64d4ca434a8a)

### Additional Info

I tried reproducing from empty project and got it reproduced it, but it took some finicking between the Theme Widget, the widgets instance and languages setup. The repro steps should probably work.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @RobinopdeBeek. I believe this is a duplicate of this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/791. Please wait for a few days before the fix come to prod and see if the issue persists. Thank you!

**Comment by wenkaifan0720** [comment]
I'll close this issue as it is a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/791.
