### ISSUE TITLE
Can't Insert List<String> variable in API Call Body without quotation mark

### ISSUE THREAD

**Issue by sarim** [FlutterFlow/flutterflow-issues#99]
In Api Call, List<String> variables should be added in JSON Body without wrapping it in quotation mark  `"`. Wrapping it in quotation mark makes it a json string, but it should be json array.

A workaround I found is to temporarily change the variable to **Integer, Is List: False**. Now you can drag it inside json body and no quotation will be added. Save It. Now go to variables and change it to **String, Is List: true**. Save it. Don't click Body. Now use in inside your pages, api call will be executed correctly.

## Expected behavior (required)

Dragging a variable which is marked as **Is List: true** to JSON Body should not added quotation mark around it.

## Current behavior (required)

Dragging a variable which is marked as **Is List: true** to JSON Body added quotation marks around it. Delete quotation mark manually results in **Unknown formatting error in JSON Body** error.

## To Reproduce (required)

POST / PUT API call where some fields are json array.

## Screenshots / recordings

This shows the issue. Then I show the workaround of temporality changing it to integer.
https://user-images.githubusercontent.com/1235888/200150964-c9a3e8c8-d525-44d1-a1a8-8ba455b0c157.mp4

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: v3.0 October 29, 2022
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Edge 107, Chrome 107
* Operating system and version (desktop or mobile): Windows 11, Windows 10, Fedora Linux 36

**Comment by agreaves** [comment]
Hi @sarim, thank you very much for the bug report! This has been fixed and will be deployed in our next release.
