### ISSUE TITLE
Page crashes when I switch list view to scroll horizontally

### ISSUE THREAD

**Issue by istvanfedak-nbcu** [FlutterFlow/flutterflow-issues#990]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list view with a page state variable. When I set ListView Properties Axis to Horizontal the webpage crashes.

project: test-button-iaxxni

### Expected Behavior

List view should switch to horizontal axis.

### Steps to Reproduce

1. Add a page state variable called count.
2. Add a page state variable called countList.
3. Add a button with an action to increment count and add the count to the countList.
4. Add a list view with a text widget that contains the items in countList.
5. Update the list view's axis to horizontal.
6. Watch the page crash.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I don't have one

### Context

I can't set the list view to be horizontal.

### Visual documentation

![Screen Shot 2023-06-13 at 8 58 50 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/87091364/31ee6e58-53bd-4d2b-808d-131fb0057a94)

![Screen Shot 2023-06-13 at 8 59 34 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/87091364/f67f4968-896c-4d24-96e9-d08ed556daaa)

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Web
- Browser name and version: Firefox 113.0.2 (64-bit)
- Operating system and version affected: Web
```

**Comment by istvanfedak-nbcu** [comment]
I found the solution.

You need to wrap the list view in a container with infinite width and a fixed height before setting the axis alignment to horizontal: https://docs.flutter.dev/cookbook/lists/horizontal-list

**Comment by agreaves** [comment]
Hi @istvanfedak-nbcu, thanks for the report! The solution you mentioned is correct, the issue arises because a ListView is not bound in both width and height. Because it was in a Column (and shrink-wrapped), this prevented it from crashing in the vertical direction, but when flipped to horizontal it was not longer contained in this direction.

Closing this issue for now!
