### ISSUE TITLE
VideoPlayer in iOS keep loading indicator for ever

### ISSUE THREAD

**Issue by aguerraApplaudo** [FlutterFlow/flutterflow-issues#995]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, I'm making an implementation of video palyer for streaming and in Android works well but in iOS the component never hide the loading indicator making a very bad user expierence. 

### Expected Behavior

When the video loads the video player must hide the loading indicator, and in that way the user can watch the video.

### Steps to Reproduce

1. Create page
2. Add videoplayer 
3. Load a video of mux (for streaming)
4. run
5. Test in iOS device

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhc/635RNodhE7pCJdsdKvDwwGVgYaIIvju0YYwsgF7byPbJ/f8/eUFhBQteqYHlhHGGL+V0E0veKj4TTCfEFCxSZbYB41bVqVz3iRXq8SrKxBZC8Z2hCRZhYGFyayKbV2CZNCOhsWiEl6mCyH+/JTjHtJ5O/Zwh9f6PHaOI=

### Context

We are making a streaming platform as twitch, but when iOS users try to watch a video in very uncomfortable because they have an infinite loading indicator in the middle of the video player. This is a very important bug to us.

### Visual documentation

![WhatsApp Image 2023-06-14 at 4 22 29 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/110511606/6d79748d-efc1-4ef2-aa02-43f2060c8459)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iPhone 11
- Browser name and version: App installed 
- Operating system and version affected: iOS 16.0
```

**Comment by hariprasadms** [comment]
Hi @aguerraApplaudo - Thanks for submitting the issue. 
I looked at the project but I can't locate the issue as there are many pages. For this kind of issues, to make investigate easy, we definitely need a blank project with issue setup details. Please update the issue with a blank project. Also add a quick video showing the issue.

As you mentioned the issue is happening in iOS devices., I suppose it is working fine in Android devices. Please confirm.

**Comment by aguerraApplaudo** [comment]
Hi @hariprasadms, yes in Android is working fine, but in iOS the loading indicator over the videoplayer is visible for ever. I'll try to set a blank project to show you the problem, but I don't know if I would be able to reproduce the environment because we need a testflight and another resources to achieve record a new video but is easy to reproduce if you try it out yourself you only need to create a video player and play in it a live video using any streaming platform with the url provided by that platform. 
Best Regards and thank you for replying

**Comment by aguerraApplaudo** [comment]
@hariprasadms @katherineqian

**Comment by aguerraApplaudo** [comment]
:( @hariprasadms @katherineqian

**Comment by ZeusFunk** [comment]
i got the same problem

**Comment by ZeusFunk** [comment]
@hariprasadms @katherineqian

**Comment by sbis04** [comment]
I tested the `VideoPlayer` widget on iOS for playing a video steam, it worked perfectly fine for me. Were you playing the video while the live streaming was in progress?

**Comment by hariprasadms** [comment]
Hi @aguerraApplaudo - No response for the followup comment. We presume, you got the issue resolved in latest FF updates. If issue still persists, create a new issue with all the required details. Thanks
