### ISSUE TITLE
Font Awesome Icons is not recognized

### ISSUE THREAD

**Issue by LucasSPS** [FlutterFlow/flutterflow-issues#996]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

all icons coming from Font-Awesome are showing as unknown by flutterflow, possible dependency error

### Expected Behavior

Font-awesome icon normalization

### Steps to Reproduce

1. Add icon component
2. Choose any Font Awesome icon
3. Flutterflow report unknown icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8/q25BgrttK7qXxbflapDgXKUg8U4ZMi+xEEQ8aCIvNGosqZc+kM0RoZM+jY2w/Plr9hWoW087NvofiFe45OSuCGaJb1ap+SjnMfzmnbrKRFJWgP3F6P55RJna+0ruzrhFCHO1uV3th6jiIPfDKVgrUJrH4PDACDq/LZO4=

### Context

All my icons are broken, can't run my project

### Visual documentation

![Screenshot_28](https://github.com/FlutterFlow/flutterflow-issues/assets/61060571/5809d06f-ba76-4ae1-b295-90be7725952f)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 114.0.5735.110
- Operating system and version affected: Windows 11
```

**Comment by Fibn007** [comment]
Confirmed, I have this issue as well after latest version update that was triggered roughly 20 mins ago. I assume a ton of others will. Please help!

**Comment by glamourhammer** [comment]
Yup - same here. Came to report the issue and perhaps unsurprisingly already found someone else had done it.

**Comment by Spellytics** [comment]
All users using FontAwesome icons are having the same issue.
https://community.flutterflow.io/c/bugs/font-awesome-icons-showing-error

**Comment by agreaves** [comment]
Hey folks, sorry about this issue. It's now fixed. We were in the process of updating to Material 3 icons and accidentally release a premature list. Apologies for the inconvenience.
