### ISSUE TITLE
Unable to import custom components in Custom Widgets

### ISSUE THREAD

**Issue by danielmeza** [FlutterFlow/flutterflow-issues#998]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since some core features from flutter are not implemented yet in FF, like Dismissible, it's commonly to use wrapper pattern to provide the missing feature and wrap a custom component inside that wrapper and this way complete the missing feature. 

For that reason, Custom Widgets are perfect to provide missing features like this `CustomWidget(child: CustomComponent())`, this way we can keep the design and interaction logic inside the Custom Component and implement the missing feature in the Custom Widget.

When I try to do that, I hit an error waying that the custom component file wasn't found or does not exist.

I report hits as an issue because this is totally posible out off the editor, and in some case the compiler just works, but most of the times it fails whit the error I describe before. I know that the correct way to do this is to allow Custom widget to receive child items as parameter but as that may require extra effort to implement, by fixing this issue FF can provide us with a work around until child widget can be used in te platform. 

Notice that if I disable compilation the project work as expected, the same if I download the code and run it locally. 

Custom Widget that implements Dismissible, consume the AvailableBetItemWidget
![Screenshot 2023-06-16 123256](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/1d8334df-1754-4caa-b779-77b1c6087b9f)

The AvailableBetItem widget
![Screenshot 2023-06-16 123132](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/aa1b9fd1-e350-4514-985c-1f5904fc503d)

![Screenshot 2023-06-16 123401](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/f42e01ee-7721-4b73-967b-922602289a9d)

![Screenshot 2023-06-16 125231](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/f07f3074-ead9-45a8-a309-b76d8c7ef077)

### Expected Behavior

The compiler allows to link custom components from custom widgets. 

### Steps to Reproduce

1. Create a custom component in the editor. 
2. Create a custom widget.
3. Reference the custom component inside the custom widget
4. Use the component as a child in the custom widget. 
5. Build the project. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xlcr1z4xOsdtF7s/uYO9VhjwROVg/a7geltZxYw81F4zqP7AfOvf+T3FdOLynSnxIOWGjnnIIp9KKkobpFsABC0iIQ705wblhVQGWfHulb5iqC6qKOUB8EeJRN3Kh56COih5/CNtqSEIT73GAe9+WfDDaJ4T6IlYFAf+kWabD+l6ULgDsFDh2tmNecCfn

### Context

read current behavior

### Visual documentation

read current behavior

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @danielmeza, Thanks for submitting the issues. I looked at the project and I can see below error in downloaded code.

it says amount field is not defined at **_availableBet_** datatype. Fix the issues accordingly. 

<img width="1512" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6f56878a-b900-48bd-b156-ca608907b39d">

**Comment by danielmeza** [comment]
Hi, I fix the code, but the issue still persis in the FF code editor.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/16217470/7a0f61b1-c25d-4202-8187-39865ae4ea4c)

**Comment by danielmeza** [comment]
@hariprasadms its a bug, please read the description, as I said the issuea appear as soon as I enable the file build, but in VS code the issue do not appear. review again after the code fix in FF code editor not in VS Code.

**Comment by hariprasadms** [comment]
Did you try custom code compile and build after adding amount field in the datatype ?

**Comment by danielmeza** [comment]
The amount issue was introduced after I report the issue, I already fix the `.amount` issue, save the file and enable compilation, when I compile the custom code in FF editor the issue appears again.

**Comment by hariprasadms** [comment]
Go it. Looks like it is project specific custom code compile issue. For some reason, data type structure is not getting updated. I can mark this as project specific bug. We will look into it shortly. Thanks

**Comment by danielmeza** [comment]
@hariprasadms just to confirm, the issues was not about the .amount, sorry for the confusion, this issue is about the import not been recognized as a valid import statement at the 12 line in this [image ](https://user-images.githubusercontent.com/16217470/246490695-1d8334df-1754-4caa-b779-77b1c6087b9f.png)

**Comment by hariprasadms** [comment]
@danielmeza  no worries. There is a code compile issue in your project. We will fix it shorty. Thanks for confirming.

**Comment by danielmeza** [comment]
@hariprasadms ok cool!

**Comment by danielmeza** [comment]
@hariprasadms could you please delete the last image from the comment?

**Comment by wenkaifan0720** [comment]
Hi @danielmeza, @hariprasadms. Is this issue resolved?

**Comment by danielmeza** [comment]
Let me recreate the issue because I removed the code that caused it.

**Comment by KelpME** [comment]
I'm having the same issue, it seems we are unable to import a custom component into a custom widget. What was the solution to this issue?
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/100400724/96f09118-5a62-4070-878b-391129bea878)

**Comment by wenkaifan0720** [comment]
Right now the workaround is to check `Exclude from compilation` and develop the custom widget locally.

**Comment by KlausGrosser** [comment]
facing the same issue, I hope a fix comes soon

**Comment by Tibop02** [comment]
same problem

**Comment by nev-21** [comment]
same problem in my project
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/ddea1bcd-e6c8-4a98-bf27-14f6384da454)

**Comment by laurant94** [comment]
I am facing the same problem too.

**Comment by naumanmir** [comment]
Is this issue resolved? Facing same problem.

**Comment by myendorphin** [comment]
> If the problem is unable to import other custom widgets, then it is indeed a missing feature on our end. The workaround for now is to exclude the widget from compilation.

still does not work after feature completed. Import of component to a custom widget.  
example taken from source code:
`import '/components/quest_marker/quest_marker_widget.dart' `

**Comment by ElyseCastles-ops** [comment]
Hi, is there a solution for this issue? I see original post was June 2023 and it still seems to be an issue. 
![ff-error](https://github.com/FlutterFlow/flutterflow-issues/assets/68953027/bad606eb-6650-4cf3-b59e-ad25ba782a47)

**Comment by lcundiff** [comment]
@wenkaifan0720 Are you able to reopen this issue so the Flutter Flow team can be aware it has not been resolved?

**Comment by louisdavidSpicyMind** [comment]
I have the same problem...

**Comment by Nouss-R** [comment]
same issue here

**Comment by nev-21** [comment]
same here

**Comment by DentalRx** [comment]
I have also had this same problem - exclude from compilation works at this time
